onos: org.onosproject.routing.config.Interface Class Reference
org.onosproject.routing.config.Interface Class Reference
An Interface is a set of addresses that are logically mapped to a switch port in the network.
Public Member Functions
Interface (ConnectPoint connectPoint, Set< InterfaceIpAddress > ipAddresses, MacAddress macAddress, VlanId vlan)
Creates an Interface based on a connection point, a set of interface IP addresses, and a MAC address.
ConnectPoint connectPoint ()
Retrieves the connection point that this interface maps to.
Set< InterfaceIpAddress > ipAddresses ()
Retrieves the set of IP addresses that are assigned to the interface.
MacAddress mac ()
Retrieves the MAC address that is assigned to the interface.
VlanId vlan ()
Retrieves the VLAN ID that is assigned to the interface.
boolean equals (Object other)
int hashCode ()
String toString ()
Detailed Description
An Interface is a set of addresses that are logically mapped to a switch port in the network.
Definition at line 32 of file Interface.java.
Constructor & Destructor Documentation
org.onosproject.routing.config.Interface.Interface (ConnectPoint connectPoint, Set< InterfaceIpAddress > ipAddresses, MacAddress macAddress, VlanId vlan)
Creates an Interface based on a connection point, a set of interface IP addresses, and a MAC address.
Parameters
connectPoint the connect point this interface is mapped to
ipAddresses the IP addresses for the interface
macAddress the MAC address of the interface
vlan VLAN identifier
Definition at line 47 of file Interface.java.
References org.onosproject.routing.config.Interface.connectPoint(), org.onosproject.routing.config.Interface.ipAddresses(), and org.onosproject.routing.config.Interface.vlan().
Referenced by org.onosproject.routing.config.Interface.equals().
Member Function Documentation
ConnectPoint org.onosproject.routing.config.Interface.connectPoint ()
Retrieves the connection point that this interface maps to.
Returns
the connection point
Definition at line 61 of file Interface.java.
Referenced by org.onosproject.routing.config.Interface.hashCode(), org.onosproject.routing.config.Interface.Interface(), and org.onosproject.routing.config.Interface.toString().
boolean org.onosproject.routing.config.Interface.equals (Object other)
Definition at line 93 of file Interface.java.
References org.onlab.packet.VlanId.equals(), org.onosproject.routing.config.Interface.Interface(), org.onosproject.routing.config.Interface.ipAddresses(), and org.onosproject.routing.config.Interface.vlan().
int org.onosproject.routing.config.Interface.hashCode ()
Definition at line 107 of file Interface.java.
References org.onosproject.routing.config.Interface.connectPoint(), org.onosproject.routing.config.Interface.ipAddresses(), and org.onosproject.routing.config.Interface.vlan().
Set<InterfaceIpAddress> org.onosproject.routing.config.Interface.ipAddresses ()
Retrieves the set of IP addresses that are assigned to the interface.
Returns
the set of interface IP addresses
Definition at line 70 of file Interface.java.
Referenced by org.onosproject.routing.config.Interface.equals(), org.onosproject.routing.config.Interface.hashCode(), org.onosproject.routing.config.Interface.Interface(), and org.onosproject.routing.config.Interface.toString().
MacAddress org.onosproject.routing.config.Interface.mac ()
Retrieves the MAC address that is assigned to the interface.
Returns
the MAC address
Definition at line 79 of file Interface.java.
String org.onosproject.routing.config.Interface.toString ()
Definition at line 112 of file Interface.java.
References org.onosproject.routing.config.Interface.connectPoint(), org.onosproject.routing.config.Interface.ipAddresses(), and org.onosproject.routing.config.Interface.vlan().
VlanId org.onosproject.routing.config.Interface.vlan ()
Retrieves the VLAN ID that is assigned to the interface.
Returns
the VLAN ID
Definition at line 88 of file Interface.java.
Referenced by org.onosproject.routing.config.Interface.equals(), org.onosproject.routing.config.Interface.hashCode(), org.onosproject.routing.config.Interface.Interface(), and org.onosproject.routing.config.Interface.toString().
The documentation for this class was generated from the following file:
apps/routing-api/src/main/java/org/onosproject/routing/config/Interface.java