onos: org.onosproject.cluster.impl.MastershipManager Class Reference
org.onosproject.cluster.impl.MastershipManager Class Reference
Classes
class InternalDelegate
Public Member Functions
void activate ()
void deactivate ()
CompletableFuture< Void > setRole (NodeId nodeId, DeviceId deviceId, MastershipRole role)
Applies the current mastership role for the specified device.
MastershipRole getLocalRole (DeviceId deviceId)
Returns the role of the local node for the specified device, without triggering master selection.
CompletableFuture< Void > relinquishMastership (DeviceId deviceId)
Abandons mastership of the specified device on the local node thus forcing selection of a new master.
CompletableFuture< MastershipRole > requestRoleFor (DeviceId deviceId)
Returns the mastership status of the local controller for a given device forcing master selection if necessary.
NodeId getMasterFor (DeviceId deviceId)
Returns the current master for a given device.
Set< DeviceId > getDevicesOf (NodeId nodeId)
Returns the devices for which a controller is master.
RoleInfo getNodesFor (DeviceId deviceId)
Returns controllers connected to a given device, in order of preference.
MastershipTerm getMastershipTerm (DeviceId deviceId)
Returns the term number of mastership change occurred for given device.
MetricsService metricsService ()
Returns MetricService instance.
void balanceRoles ()
Balances the mastership to be shared as evenly as possibly by all online instances.
Public Member Functions inherited from org.onosproject.mastership.MastershipService
default boolean isLocalMaster (DeviceId deviceId)
Returns true if the local controller is the Master for the specified deviceId.
Public Member Functions inherited from org.onosproject.core.MetricsHelper
default Timer createTimer (String component, String feature, String name)
Creates a Timer instance with given name.
Protected Attributes
MastershipStore store
ClusterService clusterService
MetricsService metricsService
Detailed Description
Definition at line 70 of file MastershipManager.java.
Member Function Documentation
void org.onosproject.cluster.impl.MastershipManager.activate ()
Definition at line 96 of file MastershipManager.java.
References org.onosproject.core.MetricsHelper.createTimer().
void org.onosproject.cluster.impl.MastershipManager.balanceRoles ()
Balances the mastership to be shared as evenly as possibly by all online instances.
Implements org.onosproject.mastership.MastershipAdminService.
Definition at line 199 of file MastershipManager.java.
References org.onosproject.cluster.impl.MastershipManager.clusterService, org.onosproject.cluster.impl.MastershipManager.getDevicesOf(), org.onosproject.cluster.ClusterService.getNodes(), org.onosproject.cluster.ClusterService.getState(), create-flow.node, and onos.size.
void org.onosproject.cluster.impl.MastershipManager.deactivate ()
Definition at line 105 of file MastershipManager.java.
Set<DeviceId> org.onosproject.cluster.impl.MastershipManager.getDevicesOf (NodeId nodeId)
Returns the devices for which a controller is master.
Parameters
nodeId the ID of the controller
Returns
a set of device IDs
Implements org.onosproject.mastership.MastershipService.
Definition at line 173 of file MastershipManager.java.
Referenced by org.onosproject.cluster.impl.MastershipManager.balanceRoles(), and org.onosproject.cluster.impl.MastershipManagerTest.getDevicesOf().
MastershipRole org.onosproject.cluster.impl.MastershipManager.getLocalRole (DeviceId deviceId)
Returns the role of the local node for the specified device, without triggering master selection.
Parameters
deviceId the the identifier of the device
Returns
role of the current node
Implements org.onosproject.mastership.MastershipService.
Definition at line 139 of file MastershipManager.java.
References find-flow.deviceId.
Referenced by org.onosproject.cluster.impl.MastershipManagerTest.relinquishMastership(), and org.onosproject.cluster.impl.MastershipManagerTest.setRole().
NodeId org.onosproject.cluster.impl.MastershipManager.getMasterFor (DeviceId deviceId)
Returns the current master for a given device.
Parameters
deviceId the identifier of the device
Returns
the ID of the master controller for the device
Implements org.onosproject.mastership.MastershipService.
Definition at line 165 of file MastershipManager.java.
References find-flow.deviceId.
Referenced by org.onosproject.cluster.impl.MastershipManagerTest.getMasterFor(), and org.onosproject.cluster.impl.MastershipManagerTest.relinquishMastership().
MastershipTerm org.onosproject.cluster.impl.MastershipManager.getMastershipTerm (DeviceId deviceId)
Returns the term number of mastership change occurred for given device.
Parameters
deviceId the identifier of the device
Returns
current master's term.
Implements org.onosproject.mastership.MastershipTermService.
Definition at line 189 of file MastershipManager.java.
References find-flow.deviceId.
RoleInfo org.onosproject.cluster.impl.MastershipManager.getNodesFor (DeviceId deviceId)
Returns controllers connected to a given device, in order of preference.
The first entry in the list is the current master.
Parameters
deviceId the identifier of the device
Returns
a list of controller IDs
Implements org.onosproject.mastership.MastershipService.
Definition at line 181 of file MastershipManager.java.
References find-flow.deviceId.
MetricsService org.onosproject.cluster.impl.MastershipManager.metricsService ()
Returns MetricService instance.
Returns
MetricService instance
Implements org.onosproject.core.MetricsHelper.
Definition at line 194 of file MastershipManager.java.
CompletableFuture<Void> org.onosproject.cluster.impl.MastershipManager.relinquishMastership (DeviceId deviceId)
Abandons mastership of the specified device on the local node thus forcing selection of a new master.
If the local node is not a master for this device, no master selection will occur.
Parameters
deviceId the identifier of the device
Returns
future that is completed when relinquish is complete
Implements org.onosproject.mastership.MastershipService.
Definition at line 147 of file MastershipManager.java.
References find-flow.deviceId.
CompletableFuture<MastershipRole> org.onosproject.cluster.impl.MastershipManager.requestRoleFor (DeviceId deviceId)
Returns the mastership status of the local controller for a given device forcing master selection if necessary.
Parameters
deviceId the the identifier of the device
Returns
the role of this controller instance
Implements org.onosproject.mastership.MastershipService.
Definition at line 155 of file MastershipManager.java.
References find-flow.deviceId.
Referenced by org.onosproject.cluster.impl.MastershipManagerTest.requestRoleFor(), and org.onosproject.cluster.impl.MastershipManagerTest.setRole().
CompletableFuture<Void> org.onosproject.cluster.impl.MastershipManager.setRole (NodeId instance, DeviceId deviceId, MastershipRole role)
Applies the current mastership role for the specified device.
Parameters
instance controller instance identifier
deviceId device identifier
role requested role
Returns
future that is completed when the role is set
Implements org.onosproject.mastership.MastershipAdminService.
Definition at line 112 of file MastershipManager.java.
References find-flow.deviceId.
Member Data Documentation
ClusterService org.onosproject.cluster.impl.MastershipManager.clusterService protected
Definition at line 87 of file MastershipManager.java.
Referenced by org.onosproject.cluster.impl.MastershipManager.balanceRoles(), and org.onosproject.cluster.impl.MastershipManagerTest.setUp().
MetricsService org.onosproject.cluster.impl.MastershipManager.metricsService protected
Definition at line 90 of file MastershipManager.java.
MastershipStore org.onosproject.cluster.impl.MastershipManager.store protected
Definition at line 84 of file MastershipManager.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/cluster/impl/MastershipManager.java