onos: org.onosproject.net.intent.IntentData Class Reference
org.onosproject.net.intent.IntentData Class Reference
A wrapper class that contains an intents, its state, and other metadata for internal use.
Public Member Functions
IntentData (Intent intent, IntentState state, Timestamp version)
Creates a new intent data object.
IntentData (IntentData intentData)
Copy constructor.
Intent intent ()
Returns the intent this metadata references.
IntentState state ()
Returns the state of the intent.
IntentState request ()
Key key ()
Returns the intent key.
Timestamp version ()
Returns the version of the intent for this key.
void setOrigin (NodeId origin)
Sets the origin, which is the node that created the intent.
NodeId origin ()
Returns the origin node that created this intent.
void setState (IntentState newState)
Updates the state of the intent to the given new state.
void setVersion (Timestamp version)
Sets the version for this intent data.
void incrementErrorCount ()
Increments the error count for this intent.
void setErrorCount (int newCount)
Sets the error count for this intent.
int errorCount ()
Returns the number of times that this intent has encountered an error during installation or withdrawal.
void setInstallables (List< Intent > installables)
Sets the intent installables to the given list of intents.
List< Intent > installables ()
Returns the installables associated with this intent.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static boolean isUpdateAcceptable (IntentData currentData, IntentData newData)
Determines whether an intent data update is allowed.
Protected Member Functions
IntentData ()
Detailed Description
A wrapper class that contains an intents, its state, and other metadata for internal use.
Definition at line 38 of file IntentData.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.IntentData.IntentData (Intent intent, IntentState state, Timestamp version)
Creates a new intent data object.
Parameters
intent intent this metadata references
state intent state
version version of the intent for this key
Definition at line 60 of file IntentData.java.
References org.onosproject.net.intent.IntentData.intent(), org.onosproject.net.intent.IntentData.state(), and org.onosproject.net.intent.IntentData.version().
org.onosproject.net.intent.IntentData.IntentData (IntentData intentData)
Copy constructor.
Parameters
intentData intent data to copy
Definition at line 72 of file IntentData.java.
References org.onosproject.net.intent.IntentData.errorCount(), org.onosproject.net.intent.IntentData.installables(), org.onosproject.net.intent.IntentData.intent(), org.onosproject.net.intent.IntentData.origin(), org.onosproject.net.intent.IntentData.request(), org.onosproject.net.intent.IntentData.state(), and org.onosproject.net.intent.IntentData.version().
org.onosproject.net.intent.IntentData.IntentData () protected
Definition at line 85 of file IntentData.java.
References org.onosproject.net.intent.IntentData.intent(), and org.onosproject.net.intent.IntentData.request().
Referenced by org.onosproject.net.intent.IntentData.equals().
Member Function Documentation
boolean org.onosproject.net.intent.IntentData.equals (Object obj)
Definition at line 303 of file IntentData.java.
References org.onosproject.net.intent.IntentData.equals(), and org.onosproject.net.intent.IntentData.IntentData().
Referenced by org.onosproject.net.intent.IntentData.equals().
int org.onosproject.net.intent.IntentData.errorCount ()
Returns the number of times that this intent has encountered an error during installation or withdrawal.
Returns
error count
Definition at line 193 of file IntentData.java.
Referenced by org.onosproject.net.intent.IntentData.incrementErrorCount(), org.onosproject.net.intent.IntentData.IntentData(), and org.onosproject.net.intent.IntentData.setErrorCount().
int org.onosproject.net.intent.IntentData.hashCode ()
Definition at line 298 of file IntentData.java.
References org.onosproject.net.intent.IntentData.intent(), and org.onosproject.net.intent.IntentData.version().
void org.onosproject.net.intent.IntentData.incrementErrorCount ()
Increments the error count for this intent.
Definition at line 174 of file IntentData.java.
References org.onosproject.net.intent.IntentData.errorCount().
List<Intent> org.onosproject.net.intent.IntentData.installables ()
Returns the installables associated with this intent.
Returns
list of installable intents
Definition at line 211 of file IntentData.java.
Referenced by org.onosproject.net.intent.IntentData.IntentData(), org.onosproject.net.intent.IntentData.setInstallables(), and org.onosproject.net.intent.IntentData.toString().
Intent org.onosproject.net.intent.IntentData.intent ()
Returns the intent this metadata references.
Returns
intent
Definition at line 95 of file IntentData.java.
Referenced by org.onosproject.store.trivial.SimpleIntentStore.getIntents(), org.onosproject.store.intent.impl.GossipIntentStore.getIntents(), org.onosproject.store.trivial.SimpleIntentStore.getPending(), org.onosproject.store.intent.impl.GossipIntentStore.getPending(), org.onosproject.net.intent.IntentData.hashCode(), org.onosproject.net.intent.IntentData.IntentData(), and org.onosproject.net.intent.IntentData.toString().
static boolean org.onosproject.net.intent.IntentData.isUpdateAcceptable (IntentData currentData, IntentData newData) static
Determines whether an intent data update is allowed.
The update must either have a higher version than the current data, or the state transition between two updates of the same version must be sane.
Parameters
currentData existing intent data in the store
newData new intent data update proposal
Returns
true if we can apply the update, otherwise false
Definition at line 224 of file IntentData.java.
Referenced by org.onosproject.net.intent.IntentDataTest.testIsUpdateAcceptable(), org.onosproject.store.trivial.SimpleIntentStore.write(), and org.onosproject.store.intent.impl.GossipIntentStore.write().
Key org.onosproject.net.intent.IntentData.key ()
Returns the intent key.
Returns
intent key
Definition at line 117 of file IntentData.java.
Referenced by org.onosproject.store.intent.impl.GossipIntentStore.getPendingData(), and org.onosproject.net.intent.IntentData.toString().
NodeId org.onosproject.net.intent.IntentData.origin ()
Returns the origin node that created this intent.
Returns
origin node ID
Definition at line 144 of file IntentData.java.
Referenced by org.onosproject.net.intent.IntentData.IntentData(), org.onosproject.net.intent.IntentData.setOrigin(), and org.onosproject.net.intent.IntentData.toString().
IntentState org.onosproject.net.intent.IntentData.request ()
Definition at line 108 of file IntentData.java.
Referenced by org.onosproject.net.intent.IntentData.IntentData().
void org.onosproject.net.intent.IntentData.setErrorCount (int newCount)
Sets the error count for this intent.
Parameters
newCount new count
Definition at line 183 of file IntentData.java.
References org.onosproject.net.intent.IntentData.errorCount().
void org.onosproject.net.intent.IntentData.setInstallables (List< Intent > installables)
Sets the intent installables to the given list of intents.
Parameters
installables list of installables for this intent
Definition at line 202 of file IntentData.java.
References org.onosproject.net.intent.IntentData.installables().
void org.onosproject.net.intent.IntentData.setOrigin (NodeId origin)
Sets the origin, which is the node that created the intent.
Parameters
origin origin instance
Definition at line 135 of file IntentData.java.
References org.onosproject.net.intent.IntentData.origin().
void org.onosproject.net.intent.IntentData.setState (IntentState newState)
Updates the state of the intent to the given new state.
Parameters
newState new state of the intent
Definition at line 153 of file IntentData.java.
void org.onosproject.net.intent.IntentData.setVersion (Timestamp version)
Sets the version for this intent data.
The store should call this method only once when the IntentData is first passed into the pending map. Ideally, an IntentData is timestamped on the same thread that the called used to submit the intents.
Parameters
version the version/timestamp for this intent data
Definition at line 167 of file IntentData.java.
References org.onosproject.net.intent.IntentData.version().
IntentState org.onosproject.net.intent.IntentData.state ()
Returns the state of the intent.
Returns
intent state
Definition at line 104 of file IntentData.java.
Referenced by org.onosproject.net.intent.IntentData.IntentData(), and org.onosproject.net.intent.IntentData.toString().
String org.onosproject.net.intent.IntentData.toString ()
Definition at line 316 of file IntentData.java.
References org.onosproject.net.intent.IntentData.installables(), org.onosproject.net.intent.IntentData.intent(), org.onosproject.net.intent.IntentData.key(), org.onosproject.net.intent.IntentData.origin(), org.onosproject.net.intent.IntentData.state(), and org.onosproject.net.intent.IntentData.version().
Timestamp org.onosproject.net.intent.IntentData.version ()
Returns the version of the intent for this key.
Returns
intent version
Definition at line 126 of file IntentData.java.
Referenced by org.onosproject.net.intent.IntentData.hashCode(), org.onosproject.net.intent.IntentData.IntentData(), org.onosproject.net.intent.IntentData.setVersion(), and org.onosproject.net.intent.IntentData.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/IntentData.java