onos: org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1 Class Reference
Provides PCEP iro object.
Classes
class Builder
Builder class for PCEP iro object.
Public Member Functions
PcepIroObjectVer1 ()
Default constructor.
PcepIroObjectVer1 (PcepObjectHeader iroObjHeader, LinkedList< PcepValueType > llSubObjects)
Constructor to initialize member variables.
PcepObjectHeader getIroObjHeader ()
Returns object header.
void setIroObjHeader (PcepObjectHeader obj)
Sets IRO Object Header.
LinkedList< PcepValueType > getSubObjects ()
Returns list of SubObjects.
void setSubObjects (LinkedList< PcepValueType > llSubObjects)
Sets list of SubObjects.
int write (ChannelBuffer cb) throws PcepParseException
Writes the IRO into channel buffer.
String toString ()
Static Public Member Functions
static PcepIroObject read (ChannelBuffer cb) throws PcepParseException
Reads from channel buffer and return object of PcepIroObject.
Static Public Attributes
static final byte IRO_OBJ_TYPE = 1
static final byte IRO_OBJ_CLASS = 10
static final byte IRO_OBJECT_VERSION = 1
static final short IRO_OBJ_MINIMUM_LENGTH = 12
static final int OBJECT_HEADER_LENGTH = 4
static final int YTYPE_SHIFT_VALUE = 0x7F
static final PcepObjectHeader DEFAULT_IRO_OBJECT_HEADER
Static Protected Member Functions
static LinkedList< PcepValueType > parseSubObjects (ChannelBuffer cb) throws PcepParseException
Returns linked list of sub objects.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepIroObjectVer1.class)
Detailed Description
Provides PCEP iro object.
Definition at line 36 of file PcepIroObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.PcepIroObjectVer1 ()
Default constructor.
Definition at line 81 of file PcepIroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.read().
org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.PcepIroObjectVer1 (PcepObjectHeader iroObjHeader, LinkedList< PcepValueType > llSubObjects)
Constructor to initialize member variables.
Parameters
iroObjHeader IRO object header
llSubObjects list of sub-objects
Definition at line 93 of file PcepIroObjectVer1.java.
Member Function Documentation
PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.getIroObjHeader ()
Returns object header.
Returns
iroObjHeader IRO object header
Definition at line 103 of file PcepIroObjectVer1.java.
LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.getSubObjects ()
Returns list of SubObjects.
Returns
list of SubObjects
Implements org.onosproject.pcepio.protocol.PcepIroObject.
Definition at line 117 of file PcepIroObjectVer1.java.
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.parseSubObjects (ChannelBuffer cb) throws PcepParseException static protected
Returns linked list of sub objects.
Parameters
cb of type channel buffer
Returns
linked list of sub objects
Exceptions
PcepParseException while parsing subobjects from channel buffer
Definition at line 153 of file PcepIroObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.YTYPE_SHIFT_VALUE.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.read().
static PcepIroObject org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.read (ChannelBuffer cb) throws PcepParseException static
Reads from channel buffer and return object of PcepIroObject.
Parameters
cb of type channel buffer
Returns
object of PcepIroObject
Exceptions
PcepParseException while parsing from channel buffer
Definition at line 133 of file PcepIroObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.OBJECT_HEADER_LENGTH, org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.parseSubObjects(), and org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.PcepIroObjectVer1().
void org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.setIroObjHeader (PcepObjectHeader obj)
Sets IRO Object Header.
Parameters
obj IRO object header
Definition at line 112 of file PcepIroObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.setSubObjects (LinkedList< PcepValueType > llSubObjects)
Sets list of SubObjects.
Parameters
llSubObjects list of SubObjects
Implements org.onosproject.pcepio.protocol.PcepIroObject.
Definition at line 122 of file PcepIroObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.toString ()
Definition at line 294 of file PcepIroObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the IRO into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException while writing IRO object.
Implements org.onosproject.pcepio.protocol.PcepIroObject.
Definition at line 189 of file PcepIroObjectVer1.java.
References find-link-in-cluster.length.
Member Data Documentation
final PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.DEFAULT_IRO_OBJECT_HEADER static
Initial value:
= new PcepObjectHeader(IRO_OBJ_CLASS, IRO_OBJ_TYPE,
            PcepObjectHeader.REQ_OBJ_OPTIONAL_PROCESS, PcepObjectHeader.RSP_OBJ_PROCESSED, IRO_OBJ_MINIMUM_LENGTH)
Definition at line 68 of file PcepIroObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.IRO_OBJ_CLASS = 10 static
Definition at line 62 of file PcepIroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepAttributeVer1.read().
final short org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.IRO_OBJ_MINIMUM_LENGTH = 12 static
Definition at line 64 of file PcepIroObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.IRO_OBJ_TYPE = 1 static
Definition at line 61 of file PcepIroObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.IRO_OBJECT_VERSION = 1 static
Definition at line 63 of file PcepIroObjectVer1.java.
final Logger org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.log = LoggerFactory.getLogger(PcepIroObjectVer1.class) static protected
Definition at line 59 of file PcepIroObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.OBJECT_HEADER_LENGTH = 4 static
Definition at line 65 of file PcepIroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.read().
final int org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.YTYPE_SHIFT_VALUE = 0x7F static
Definition at line 66 of file PcepIroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepIroObjectVer1.parseSubObjects().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepIroObjectVer1.java