onos: org.onosproject.routing.bgp.BgpSession Class Reference
org.onosproject.routing.bgp.BgpSession Class Reference
Class for handling the BGP peer sessions.
Public Member Functions
BgpSessionInfo localInfo ()
Gets the BGP Session local information.
BgpSessionInfo remoteInfo ()
Gets the BGP Session remote information.
boolean mpExtensions ()
Gets the BGP Multiprotocol Extensions for the session.
boolean isAs4OctetCapable ()
Gets the BGP session 4 octet AS path capability.
Collection< BgpRouteEntry > getBgpRibIn4 ()
Gets the IPv4 BGP RIB-IN routing entries.
Collection< BgpRouteEntry > getBgpRibIn6 ()
Gets the IPv6 BGP RIB-IN routing entries.
BgpRouteEntry findBgpRoute (Ip4Prefix prefix)
Finds an IPv4 BGP routing entry for a prefix in the IPv4 BGP RIB-IN.
BgpRouteEntry findBgpRoute (Ip6Prefix prefix)
Finds an IPv6 BGP routing entry for a prefix in the IPv6 BGP RIB-IN.
BgpRouteEntry findBgpRoute (IpPrefix prefix)
Finds a BGP routing entry for a prefix in the BGP RIB-IN.
void channelOpen (ChannelHandlerContext ctx, ChannelStateEvent channelEvent)
void channelClosed (ChannelHandlerContext ctx, ChannelStateEvent channelEvent)
void channelConnected (ChannelHandlerContext ctx, ChannelStateEvent channelEvent)
void channelDisconnected (ChannelHandlerContext ctx, ChannelStateEvent channelEvent)
void exceptionCaught (ChannelHandlerContext ctx, ExceptionEvent e)
Detailed Description
Class for handling the BGP peer sessions.
There is one instance per each BGP peer session.
Definition at line 46 of file BgpSession.java.
Member Function Documentation
void org.onosproject.routing.bgp.BgpSession.channelClosed (ChannelHandlerContext ctx, ChannelStateEvent channelEvent)
Definition at line 278 of file BgpSession.java.
void org.onosproject.routing.bgp.BgpSession.channelConnected (ChannelHandlerContext ctx, ChannelStateEvent channelEvent)
Definition at line 284 of file BgpSession.java.
References org.onosproject.routing.bgp.BgpSession.localInfo(), and org.onosproject.routing.bgp.BgpSession.remoteInfo().
void org.onosproject.routing.bgp.BgpSession.channelDisconnected (ChannelHandlerContext ctx, ChannelStateEvent channelEvent)
Definition at line 316 of file BgpSession.java.
void org.onosproject.routing.bgp.BgpSession.channelOpen (ChannelHandlerContext ctx, ChannelStateEvent channelEvent)
Definition at line 272 of file BgpSession.java.
void org.onosproject.routing.bgp.BgpSession.exceptionCaught (ChannelHandlerContext ctx, ExceptionEvent e)
Definition at line 325 of file BgpSession.java.
BgpRouteEntry org.onosproject.routing.bgp.BgpSession.findBgpRoute (Ip4Prefix prefix)
Finds an IPv4 BGP routing entry for a prefix in the IPv4 BGP RIB-IN.
Parameters
prefix the IPv4 prefix of the route to search for
Returns
the IPv4 BGP routing entry if found, otherwise null
Definition at line 156 of file BgpSession.java.
References onosUploadBits.prefix.
BgpRouteEntry org.onosproject.routing.bgp.BgpSession.findBgpRoute (Ip6Prefix prefix)
Finds an IPv6 BGP routing entry for a prefix in the IPv6 BGP RIB-IN.
Parameters
prefix the IPv6 prefix of the route to search for
Returns
the IPv6 BGP routing entry if found, otherwise null
Definition at line 166 of file BgpSession.java.
References onosUploadBits.prefix.
BgpRouteEntry org.onosproject.routing.bgp.BgpSession.findBgpRoute (IpPrefix prefix)
Finds a BGP routing entry for a prefix in the BGP RIB-IN.
The prefix can be either IPv4 or IPv6.
Parameters
prefix the IP prefix of the route to search for
Returns
the BGP routing entry if found, otherwise null
Definition at line 177 of file BgpSession.java.
References org.onlab.packet.IpPrefix.isIp4().
Collection<BgpRouteEntry> org.onosproject.routing.bgp.BgpSession.getBgpRibIn4 ()
Gets the IPv4 BGP RIB-IN routing entries.
Returns
the IPv4 BGP RIB-IN routing entries
Definition at line 137 of file BgpSession.java.
Referenced by org.onosproject.routing.cli.BgpRoutesListCommand.execute().
Collection<BgpRouteEntry> org.onosproject.routing.bgp.BgpSession.getBgpRibIn6 ()
Gets the IPv6 BGP RIB-IN routing entries.
Returns
the IPv6 BGP RIB-IN routing entries
Definition at line 146 of file BgpSession.java.
boolean org.onosproject.routing.bgp.BgpSession.isAs4OctetCapable ()
Gets the BGP session 4 octet AS path capability.
Returns
true when the BGP session is 4 octet AS path capable
Definition at line 127 of file BgpSession.java.
References org.onosproject.routing.bgp.BgpSession.localInfo().
BgpSessionInfo org.onosproject.routing.bgp.BgpSession.localInfo ()
Gets the BGP Session local information.
Returns
the BGP Session local information.
Definition at line 99 of file BgpSession.java.
Referenced by org.onosproject.routing.bgp.BgpSession.channelConnected(), org.onosproject.routing.bgp.BgpSession.isAs4OctetCapable(), and org.onosproject.routing.bgp.BgpSession.mpExtensions().
boolean org.onosproject.routing.bgp.BgpSession.mpExtensions ()
Gets the BGP Multiprotocol Extensions for the session.
Returns
true if the BGP Multiprotocol Extensions are enabled for the session, otherwise false
Definition at line 118 of file BgpSession.java.
References org.onosproject.routing.bgp.BgpSession.localInfo().
BgpSessionInfo org.onosproject.routing.bgp.BgpSession.remoteInfo ()
Gets the BGP Session remote information.
Returns
the BGP Session remote information.
Definition at line 108 of file BgpSession.java.
Referenced by org.onosproject.routing.bgp.BgpSession.channelConnected().
The documentation for this class was generated from the following file:
apps/routing/src/main/java/org/onosproject/routing/bgp/BgpSession.java