onos: org.onosproject.net.device.OmsPortDescription Class Reference
org.onosproject.net.device.OmsPortDescription Class Reference
Default implementation of immutable OMS port description.
Public Member Functions
OmsPortDescription (PortNumber number, boolean isEnabled, Frequency minFrequency, Frequency maxFrequency, Frequency grid, SparseAnnotations...annotations)
Creates OMS port description based on the supplied information.
OmsPortDescription (PortDescription base, Frequency minFrequency, Frequency maxFrequency, Frequency grid, SparseAnnotations annotations)
Creates OMS port description based on the supplied information.
Frequency minFrequency ()
Returns minimum frequency.
Frequency maxFrequency ()
Returns maximum frequency.
Frequency grid ()
Returns grid spacing frequency.
String toString ()
Public Member Functions inherited from org.onosproject.net.device.DefaultPortDescription
DefaultPortDescription (PortNumber number, boolean isEnabled, SparseAnnotations...annotations)
Creates a port description using the supplied information.
DefaultPortDescription (PortNumber number, boolean isEnabled, Type type, long portSpeed, SparseAnnotations...annotations)
Creates a port description using the supplied information.
DefaultPortDescription (PortDescription base, SparseAnnotations annotations)
Creates a port description using the supplied information.
PortNumber portNumber ()
Returns the port number.
boolean isEnabled ()
Indicates whether or not the port is up and active.
Type type ()
Returns the port type.
long portSpeed ()
Returns the current port speed in Mbps.
String toString ()
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.AbstractDescription
SparseAnnotations annotations ()
Returns the key/value annotations.
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractDescription
AbstractDescription ()
AbstractDescription (SparseAnnotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of immutable OMS port description.
Definition at line 27 of file OmsPortDescription.java.
Constructor & Destructor Documentation
org.onosproject.net.device.OmsPortDescription.OmsPortDescription (PortNumber number, boolean isEnabled, Frequency minFrequency, Frequency maxFrequency, Frequency grid, SparseAnnotations... annotations)
Creates OMS port description based on the supplied information.
Parameters
number port number
isEnabled port enabled state
minFrequency minimum frequency
maxFrequency maximum frequency
grid grid spacing frequency
annotations optional key/value annotations map
Definition at line 43 of file OmsPortDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.device.OmsPortDescription.grid(), org.onosproject.net.device.OmsPortDescription.maxFrequency(), and org.onosproject.net.device.OmsPortDescription.minFrequency().
org.onosproject.net.device.OmsPortDescription.OmsPortDescription (PortDescription base, Frequency minFrequency, Frequency maxFrequency, Frequency grid, SparseAnnotations annotations)
Creates OMS port description based on the supplied information.
Parameters
base PortDescription to get basic information from
minFrequency minimum frequency
maxFrequency maximum frequency
grid grid spacing frequency
annotations optional key/value annotations map
Definition at line 60 of file OmsPortDescription.java.
References org.onosproject.net.device.OmsPortDescription.grid(), org.onosproject.net.device.OmsPortDescription.maxFrequency(), and org.onosproject.net.device.OmsPortDescription.minFrequency().
Member Function Documentation
Frequency org.onosproject.net.device.OmsPortDescription.grid ()
Returns grid spacing frequency.
Returns
grid spacing frequency
Definition at line 91 of file OmsPortDescription.java.
Referenced by org.onosproject.net.device.OmsPortDescription.OmsPortDescription(), and org.onosproject.net.device.OmsPortDescription.toString().
Frequency org.onosproject.net.device.OmsPortDescription.maxFrequency ()
Returns maximum frequency.
Returns
maximum frequency
Definition at line 82 of file OmsPortDescription.java.
Referenced by org.onosproject.net.device.OmsPortDescription.OmsPortDescription(), and org.onosproject.net.device.OmsPortDescription.toString().
Frequency org.onosproject.net.device.OmsPortDescription.minFrequency ()
Returns minimum frequency.
Returns
minimum frequency
Definition at line 73 of file OmsPortDescription.java.
Referenced by org.onosproject.net.device.OmsPortDescription.OmsPortDescription(), and org.onosproject.net.device.OmsPortDescription.toString().
String org.onosproject.net.device.OmsPortDescription.toString ()
Definition at line 96 of file OmsPortDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.device.OmsPortDescription.grid(), org.onosproject.net.device.DefaultPortDescription.isEnabled(), org.onosproject.net.device.OmsPortDescription.maxFrequency(), org.onosproject.net.device.OmsPortDescription.minFrequency(), org.onosproject.net.device.DefaultPortDescription.portNumber(), and org.onosproject.net.device.DefaultPortDescription.type().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/device/OmsPortDescription.java