onos: org.onosproject.cli.net.FlowsListCommand Class Reference
org.onosproject.cli.net.FlowsListCommand Class Reference
Lists all currently-known flows.
Static Public Attributes
static final String ANY = "any"
Protected Member Functions
void execute ()
Executes this command.
SortedMap< Device, List
< FlowEntry > > getSortedFlows (DeviceService deviceService, FlowRuleService service)
Returns the list of devices sorted using the device ID URIs.
void printFlows (Device d, List< FlowEntry > flows, CoreService coreService)
Prints flows.
Protected Member Functions inherited from org.onosproject.cli.AbstractShellCommand
ApplicationId appId ()
Returns application ID for the CLI.
boolean outputJson ()
Indicates whether JSON format should be output.
Object doExecute () throws Exception
Additional Inherited Members
Public Member Functions inherited from org.onosproject.cli.AbstractShellCommand
void print (String format, Object...args)
Prints the arguments using the specified format.
void error (String format, Object...args)
Prints the arguments using the specified format to error stream.
ObjectMapper mapper ()
Returns the JSON object mapper.
Static Public Member Functions inherited from org.onosproject.cli.AbstractShellCommand
static< T > T get (Class< T > serviceClass)
Returns the reference to the implementation of the specified service.
static String annotations (Annotations annotations)
Produces a string image of the specified key/value annotations.
static ObjectNode annotations (ObjectMapper mapper, Annotations annotations)
Produces a JSON object from the specified key/value annotations.
Detailed Description
Lists all currently-known flows.
Definition at line 49 of file FlowsListCommand.java.
Member Function Documentation
void org.onosproject.cli.net.FlowsListCommand.execute () protected virtual
Executes this command.
Implements org.onosproject.cli.AbstractShellCommand.
Definition at line 67 of file FlowsListCommand.java.
References create-flow.device.
SortedMap<Device, List<FlowEntry> > org.onosproject.cli.net.FlowsListCommand.getSortedFlows (DeviceService deviceService, FlowRuleService service) protected
Returns the list of devices sorted using the device ID URIs.
Parameters
deviceService device service
service flow rule service
Returns
sorted device list
Definition at line 118 of file FlowsListCommand.java.
References org.onosproject.cli.Comparators.ELEMENT_COMPARATOR, org.onosproject.cli.Comparators.FLOW_RULE_COMPARATOR, org.onosproject.net.device.DeviceService.getDevices(), and org.onosproject.net.flow.FlowRuleService.getFlowEntries().
void org.onosproject.cli.net.FlowsListCommand.printFlows (Device d, List< FlowEntry > flows, CoreService coreService) protected
Prints flows.
Parameters
d the device
flows the set of flows for that device
coreService core system service
Definition at line 158 of file FlowsListCommand.java.
References org.onosproject.net.Device.id().
Member Data Documentation
final String org.onosproject.cli.net.FlowsListCommand.ANY = "any" static
Definition at line 51 of file FlowsListCommand.java.
Referenced by org.onosproject.cli.net.FlowRuleStatusCompleter.complete().
The documentation for this class was generated from the following file:
cli/src/main/java/org/onosproject/cli/net/FlowsListCommand.java