onos: org.onosproject.store.intent.impl.PartitionManagerTest Class Reference
org.onosproject.store.intent.impl.PartitionManagerTest Class Reference
Unit tests for the PartitionManager class.
Classes
class TestLeadershipService
LeadershipService that allows us to grab a reference to PartitionManager's LeadershipEventListener.
Public Member Functions
void setUp ()
void testActivate ()
Tests that the PartitionManager's activate method correctly runs for all the leader elections that it should.
void testIsMine ()
Tests that the isMine method returns the correct result based on the underlying leadership service data.
void testRebalanceScheduling ()
Tests sending in LeadershipServiceEvents in the case when we have too many partitions.
void testRebalance ()
Tests rebalance will trigger the right now of leadership withdraw calls.
void testNoRebalance ()
Tests that attempts to rebalance when the paritions are already evenly distributed does not result in any relinquish attempts.
Detailed Description
Unit tests for the PartitionManager class.
Definition at line 55 of file PartitionManagerTest.java.
Member Function Documentation
void org.onosproject.store.intent.impl.PartitionManagerTest.setUp ()
Definition at line 74 of file PartitionManagerTest.java.
References org.onosproject.cluster.LeadershipService.runForLeadership().
void org.onosproject.store.intent.impl.PartitionManagerTest.testActivate ()
Tests that the PartitionManager's activate method correctly runs for all the leader elections that it should.
Definition at line 127 of file PartitionManagerTest.java.
References org.onosproject.cluster.LeadershipService.runForLeadership().
void org.onosproject.store.intent.impl.PartitionManagerTest.testIsMine ()
Tests that the isMine method returns the correct result based on the underlying leadership service data.
Definition at line 150 of file PartitionManagerTest.java.
References org.onosproject.store.intent.impl.PartitionManager.isMine().
void org.onosproject.store.intent.impl.PartitionManagerTest.testNoRebalance ()
Tests that attempts to rebalance when the paritions are already evenly distributed does not result in any relinquish attempts.
Definition at line 222 of file PartitionManagerTest.java.
void org.onosproject.store.intent.impl.PartitionManagerTest.testRebalance ()
Tests rebalance will trigger the right now of leadership withdraw calls.
Definition at line 199 of file PartitionManagerTest.java.
References org.onosproject.cluster.LeadershipService.withdraw().
void org.onosproject.store.intent.impl.PartitionManagerTest.testRebalanceScheduling ()
Tests sending in LeadershipServiceEvents in the case when we have too many partitions.
The event will trigger the partition manager to schedule a rebalancing activity.
Definition at line 180 of file PartitionManagerTest.java.
References org.onosproject.store.intent.impl.PartitionManager.rebalanceScheduled.
The documentation for this class was generated from the following file:
core/store/dist/src/test/java/org/onosproject/store/intent/impl/PartitionManagerTest.java