onos: org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler Class Reference
org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler Class Reference
An intent compiler for org.onosproject.net.intent.MultiPointToSinglePointIntent.
Public Member Functions
void activate ()
void deactivate ()
List< Intent > compile (MultiPointToSinglePointIntent intent, List< Intent > installable, Set< LinkResourceAllocations > resources)
Protected Attributes
IntentExtensionService intentManager
PathService pathService
DeviceService deviceService
Detailed Description
An intent compiler for org.onosproject.net.intent.MultiPointToSinglePointIntent.
Definition at line 54 of file MultiPointToSinglePointIntentCompiler.java.
Member Function Documentation
void org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.activate ()
Definition at line 67 of file MultiPointToSinglePointIntentCompiler.java.
List<Intent> org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.compile (MultiPointToSinglePointIntent intent, List< Intent > installable, Set< LinkResourceAllocations > resources)
Definition at line 77 of file MultiPointToSinglePointIntentCompiler.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.ConnectivityIntent.constraints(), find-flow.deviceId, org.onosproject.net.Path.links(), org.onosproject.net.intent.Intent.priority(), org.onosproject.net.intent.ConnectivityIntent.selector(), and org.onosproject.net.intent.ConnectivityIntent.treatment().
void org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.deactivate ()
Definition at line 72 of file MultiPointToSinglePointIntentCompiler.java.
Member Data Documentation
DeviceService org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.deviceService protected
Definition at line 64 of file MultiPointToSinglePointIntentCompiler.java.
IntentExtensionService org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.intentManager protected
Definition at line 58 of file MultiPointToSinglePointIntentCompiler.java.
PathService org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.pathService protected
Definition at line 61 of file MultiPointToSinglePointIntentCompiler.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/intent/impl/compiler/MultiPointToSinglePointIntentCompiler.java