onos: org.onosproject.segmentrouting.TunnelPolicy Class Reference
org.onosproject.segmentrouting.TunnelPolicy Class Reference
Tunnel Policy.
Classes
class Builder
Tunnel Policy Builder.
Public Member Functions
TunnelPolicy (TunnelPolicy p)
Creates a TunnelPolicy reference.
String id ()
Returns the policy ID.
int priority ()
Returns the priority of the policy.
Type type ()
Returns the policy type.
String srcIp ()
Returns the source IP address of the policy.
String dstIp ()
Returns the destination IP address of the policy.
String ipProto ()
Returns the IP protocol of the policy.
short srcPort ()
Returns the source port of the policy.
short dstPort ()
Returns the destination of the policy.
boolean equals (Object o)
int hashCode ()
String tunnelId ()
Returns the tunnel ID of the policy.
Static Public Member Functions
static TunnelPolicy.Builder builder ()
Returns the TunnelPolicy builder reference.
Detailed Description
Tunnel Policy.
Definition at line 26 of file TunnelPolicy.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.TunnelPolicy.TunnelPolicy (TunnelPolicy p)
Creates a TunnelPolicy reference.
Parameters
p TunnelPolicy reference
Definition at line 57 of file TunnelPolicy.java.
References find-link-in-cluster.dstPort, find-device.id, and find-link-in-cluster.srcPort.
Member Function Documentation
static TunnelPolicy.Builder org.onosproject.segmentrouting.TunnelPolicy.builder () static
Returns the TunnelPolicy builder reference.
Returns
TunnelPolicy builder
Definition at line 74 of file TunnelPolicy.java.
String org.onosproject.segmentrouting.TunnelPolicy.dstIp ()
Returns the destination IP address of the policy.
Returns
destination IP address
Implements org.onosproject.segmentrouting.Policy.
Definition at line 99 of file TunnelPolicy.java.
Referenced by org.onosproject.segmentrouting.TunnelPolicy.hashCode().
short org.onosproject.segmentrouting.TunnelPolicy.dstPort ()
Returns the destination of the policy.
Returns
destination port
Implements org.onosproject.segmentrouting.Policy.
Definition at line 114 of file TunnelPolicy.java.
Referenced by org.onosproject.segmentrouting.TunnelPolicy.hashCode().
boolean org.onosproject.segmentrouting.TunnelPolicy.equals (Object o)
Definition at line 119 of file TunnelPolicy.java.
int org.onosproject.segmentrouting.TunnelPolicy.hashCode ()
Definition at line 143 of file TunnelPolicy.java.
References org.onosproject.segmentrouting.TunnelPolicy.dstIp(), org.onosproject.segmentrouting.TunnelPolicy.dstPort(), org.onosproject.segmentrouting.TunnelPolicy.ipProto(), org.onosproject.segmentrouting.TunnelPolicy.priority(), org.onosproject.segmentrouting.TunnelPolicy.srcIp(), org.onosproject.segmentrouting.TunnelPolicy.srcPort(), org.onosproject.segmentrouting.TunnelPolicy.tunnelId(), and org.onosproject.segmentrouting.TunnelPolicy.type().
String org.onosproject.segmentrouting.TunnelPolicy.id ()
Returns the policy ID.
Returns
policy ID
Implements org.onosproject.segmentrouting.Policy.
Definition at line 79 of file TunnelPolicy.java.
References find-device.id.
String org.onosproject.segmentrouting.TunnelPolicy.ipProto ()
Returns the IP protocol of the policy.
Returns
IP protocol
Implements org.onosproject.segmentrouting.Policy.
Definition at line 104 of file TunnelPolicy.java.
Referenced by org.onosproject.segmentrouting.TunnelPolicy.hashCode().
int org.onosproject.segmentrouting.TunnelPolicy.priority ()
Returns the priority of the policy.
Returns
priority
Implements org.onosproject.segmentrouting.Policy.
Definition at line 84 of file TunnelPolicy.java.
Referenced by org.onosproject.segmentrouting.TunnelPolicy.hashCode().
String org.onosproject.segmentrouting.TunnelPolicy.srcIp ()
Returns the source IP address of the policy.
Returns
source IP address
Implements org.onosproject.segmentrouting.Policy.
Definition at line 94 of file TunnelPolicy.java.
Referenced by org.onosproject.segmentrouting.TunnelPolicy.hashCode().
short org.onosproject.segmentrouting.TunnelPolicy.srcPort ()
Returns the source port of the policy.
Returns
source port
Implements org.onosproject.segmentrouting.Policy.
Definition at line 109 of file TunnelPolicy.java.
Referenced by org.onosproject.segmentrouting.TunnelPolicy.hashCode().
String org.onosproject.segmentrouting.TunnelPolicy.tunnelId ()
Returns the tunnel ID of the policy.
Returns
Tunnel ID
Definition at line 153 of file TunnelPolicy.java.
Referenced by org.onosproject.segmentrouting.TunnelPolicy.hashCode().
Type org.onosproject.segmentrouting.TunnelPolicy.type ()
Returns the policy type.
Returns
policy type
Implements org.onosproject.segmentrouting.Policy.
Definition at line 89 of file TunnelPolicy.java.
Referenced by org.onosproject.segmentrouting.TunnelPolicy.hashCode().
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/TunnelPolicy.java