onos: org.onosproject.incubator.net.tunnel.TunnelId Class Reference
org.onosproject.incubator.net.tunnel.TunnelId Class Reference
Representation of a Tunnel Id.
Public Member Functions
long id ()
Returns the backing value.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static TunnelId valueOf (long value)
Creates an tunnel identifier from the specified tunnel.
static TunnelId valueOf (String value)
Detailed Description
Representation of a Tunnel Id.
Definition at line 25 of file TunnelId.java.
Member Function Documentation
boolean org.onosproject.incubator.net.tunnel.TunnelId.equals (Object obj)
Definition at line 73 of file TunnelId.java.
int org.onosproject.incubator.net.tunnel.TunnelId.hashCode ()
Definition at line 68 of file TunnelId.java.
long org.onosproject.incubator.net.tunnel.TunnelId.id ()
Returns the backing value.
Returns
the value
Definition at line 63 of file TunnelId.java.
Referenced by org.onosproject.incubator.net.tunnel.TunnelIdTest.testConstruction().
String org.onosproject.incubator.net.tunnel.TunnelId.toString ()
Definition at line 85 of file TunnelId.java.
static TunnelId org.onosproject.incubator.net.tunnel.TunnelId.valueOf (long value) static
Creates an tunnel identifier from the specified tunnel.
Parameters
value long value
Returns
tunnel identifier
Definition at line 34 of file TunnelId.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepReleaseTunnelProviderTest.testCasePcepReleaseTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepSetupTunnelProviderTest.testCasePcepSetupTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProviderTest.testCasePcepSetupTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepUpdateTunnelProviderTest.testCasePcepUpdateTunnel(), org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.testTunnelAdded(), and org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.testTunnelRemoved().
static TunnelId org.onosproject.incubator.net.tunnel.TunnelId.valueOf (String value) static
Definition at line 38 of file TunnelId.java.
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/tunnel/TunnelId.java