onos: org.onosproject.net.flow.DefaultFlowRule Class Reference
org.onosproject.net.flow.DefaultFlowRule Class Reference
Classes
class Builder
Public Member Functions
DefaultFlowRule (FlowRule rule)
DefaultFlowRule (DeviceId deviceId, TrafficSelector selector, TrafficTreatment treatment, int priority, ApplicationId appId, int timeout, boolean permanent, FlowRuleExtPayLoad payLoad)
Support for the third party flow rule.
DefaultFlowRule (DeviceId deviceId, TrafficSelector selector, TrafficTreatment treatment, int priority, ApplicationId appId, GroupId groupId, int timeout, boolean permanent, FlowRuleExtPayLoad payLoad)
Support for the third party flow rule.
FlowId id ()
Returns the ID of this flow.
short appId ()
Returns the application id of this flow.
GroupId groupId ()
Returns the group id of this flow.
int priority ()
Returns the flow rule priority given in natural order; higher numbers mean higher priorities.
DeviceId deviceId ()
Returns the identity of the device where this rule applies.
TrafficSelector selector ()
Returns the traffic selector that identifies what traffic this rule should apply to.
TrafficTreatment treatment ()
Returns the traffic treatment that applies to selected traffic.
int hashCode ()
boolean equals (Object obj)
Equality for flow rules only considers 'match equality'. This means that two flow rules with the same match conditions will be equal, regardless of the treatment or other characteristics of the flow.
Parameters
obj the reference object with which to compare.
Returns
true
if this object is the same as the obj argument;
false
otherwise.
boolean exactMatch (FlowRule rule)
Returns whether this flow rule is an exact match to the flow rule given in the argument.
String toString ()
int timeout ()
Returns the timeout for this flow requested by an application.
boolean isPermanent ()
Returns whether the flow is permanent i.e.
int tableId ()
Returns the table id for this rule.
FlowRuleExtPayLoad payLoad ()
Returns the third party original flow rule.
Static Public Member Functions
static Builder builder ()
Additional Inherited Members
Public Attributes inherited from org.onosproject.net.flow.FlowRule
int MAX_TIMEOUT = 60
int MIN_PRIORITY = 0
Detailed Description
Definition at line 29 of file DefaultFlowRule.java.
Constructor & Destructor Documentation
org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule (FlowRule rule)
Definition at line 48 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRule.equals().
org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule (DeviceId deviceId, TrafficSelector selector, TrafficTreatment treatment, int priority, ApplicationId appId, int timeout, boolean permanent, FlowRuleExtPayLoad payLoad)
Support for the third party flow rule.
Creates a flow rule of flow table.
Parameters
deviceId the identity of the device where this rule applies
selector the traffic selector that identifies what traffic this rule
treatment the traffic treatment that applies to selected traffic
priority the flow rule priority given in natural order
appId the application id of this flow
timeout the timeout for this flow requested by an application
permanent whether the flow is permanent i.e. does not time out
payLoad 3rd-party origin private flow
Definition at line 98 of file DefaultFlowRule.java.
References org.onosproject.net.flow.DefaultFlowRule.deviceId(), org.onosproject.net.flow.FlowRule.MIN_PRIORITY, org.onosproject.net.flow.DefaultFlowRule.payLoad(), org.onosproject.net.flow.DefaultFlowRule.priority(), org.onosproject.net.flow.DefaultFlowRule.selector(), org.onosproject.net.flow.DefaultFlowRule.timeout(), and org.onosproject.net.flow.DefaultFlowRule.treatment().
org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule (DeviceId deviceId, TrafficSelector selector, TrafficTreatment treatment, int priority, ApplicationId appId, GroupId groupId, int timeout, boolean permanent, FlowRuleExtPayLoad payLoad)
Support for the third party flow rule.
Creates a flow rule of group table.
Parameters
deviceId the identity of the device where this rule applies
selector the traffic selector that identifies what traffic this rule
treatment the traffic treatment that applies to selected traffic
priority the flow rule priority given in natural order
appId the application id of this flow
groupId the group id of this flow
timeout the timeout for this flow requested by an application
permanent whether the flow is permanent i.e. does not time out
payLoad 3rd-party origin private flow
Definition at line 145 of file DefaultFlowRule.java.
References org.onosproject.net.flow.DefaultFlowRule.deviceId(), org.onosproject.net.flow.DefaultFlowRule.groupId(), org.onosproject.net.flow.FlowRule.MIN_PRIORITY, org.onosproject.net.flow.DefaultFlowRule.payLoad(), org.onosproject.net.flow.DefaultFlowRule.priority(), org.onosproject.net.flow.DefaultFlowRule.selector(), org.onosproject.net.flow.DefaultFlowRule.timeout(), and org.onosproject.net.flow.DefaultFlowRule.treatment().
Member Function Documentation
short org.onosproject.net.flow.DefaultFlowRule.appId ()
Returns the application id of this flow.
Returns
an applicationId
Implements org.onosproject.net.flow.FlowRule.
Definition at line 182 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowEntryTest.testFlowBasedObject().
static Builder org.onosproject.net.flow.DefaultFlowRule.builder () static
Definition at line 287 of file DefaultFlowRule.java.
DeviceId org.onosproject.net.flow.DefaultFlowRule.deviceId ()
Returns the identity of the device where this rule applies.
Returns
device identifier
Implements org.onosproject.net.flow.FlowRule.
Definition at line 197 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule(), org.onosproject.net.flow.DefaultFlowRule.equals(), org.onosproject.net.flow.DefaultFlowRule.hashCode(), org.onosproject.net.flow.DefaultFlowEntryTest.testDeviceBasedObject(), and org.onosproject.net.flow.DefaultFlowEntryTest.testSetters().
boolean org.onosproject.net.flow.DefaultFlowRule.equals (Object obj)
Equality for flow rules only considers 'match equality'. This means that two flow rules with the same match conditions will be equal, regardless of the treatment or other characteristics of the flow.
Parameters
obj the reference object with which to compare.
Returns
true
if this object is the same as the obj argument;
false
otherwise.
Equality for flow rules only considers 'match equality'. This means that two flow rules with the same match conditions will be equal, regardless of the treatment or other characteristics of the flow.
Parameters
obj the reference object with which to compare.
Returns
true
if this object is the same as the obj argument;
false
otherwise.
Implements org.onosproject.net.flow.FlowRule.
Definition at line 236 of file DefaultFlowRule.java.
References org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule(), find-flow.deviceId, org.onosproject.net.flow.DefaultFlowRule.deviceId(), org.onosproject.net.flow.DefaultFlowRule.payLoad(), and org.onosproject.net.flow.DefaultFlowRule.selector().
boolean org.onosproject.net.flow.DefaultFlowRule.exactMatch (FlowRule rule)
Returns whether this flow rule is an exact match to the flow rule given in the argument.
Exact match means that deviceId, priority, selector, tableId, flowId and treatment are equal. Note that this differs from the notion of object equality for flow rules, which does not consider the flowId or treatment when testing equality.
Parameters
rule other rule to match against
Returns
true if the rules are an exact match, otherwise false
Implements org.onosproject.net.flow.FlowRule.
Definition at line 252 of file DefaultFlowRule.java.
References org.onosproject.net.flow.FlowRule.id(), and org.onosproject.net.flow.FlowRule.treatment().
GroupId org.onosproject.net.flow.DefaultFlowRule.groupId ()
Returns the group id of this flow.
Returns
an groupId
Implements org.onosproject.net.flow.FlowRule.
Definition at line 187 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule().
int org.onosproject.net.flow.DefaultFlowRule.hashCode ()
Definition at line 219 of file DefaultFlowRule.java.
References org.onosproject.net.flow.DefaultFlowRule.deviceId(), org.onosproject.net.flow.DefaultFlowRule.payLoad(), org.onosproject.net.flow.DefaultFlowRule.selector(), and org.onosproject.net.flow.DefaultFlowRule.tableId().
FlowId org.onosproject.net.flow.DefaultFlowRule.id ()
Returns the ID of this flow.
Returns
the flow ID
Implements org.onosproject.net.flow.FlowRule.
Definition at line 177 of file DefaultFlowRule.java.
boolean org.onosproject.net.flow.DefaultFlowRule.isPermanent ()
Returns whether the flow is permanent i.e.
does not time out.
Returns
true if the flow is permanent, otherwise false
Implements org.onosproject.net.flow.FlowRule.
Definition at line 278 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithPayLoadByFlowTable(), and org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithPayLoadByGroupTable().
FlowRuleExtPayLoad org.onosproject.net.flow.DefaultFlowRule.payLoad ()
Returns the third party original flow rule.
Returns
FlowRuleExtPayLoad
Implements org.onosproject.net.flow.FlowRule.
Definition at line 393 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule(), org.onosproject.net.flow.DefaultFlowRule.equals(), org.onosproject.net.flow.DefaultFlowRule.hashCode(), and org.onosproject.net.flow.DefaultFlowRule.toString().
int org.onosproject.net.flow.DefaultFlowRule.priority ()
Returns the flow rule priority given in natural order; higher numbers mean higher priorities.
Returns
flow rule priority
Implements org.onosproject.net.flow.FlowRule.
Definition at line 192 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule(), org.onosproject.net.flow.DefaultFlowEntryTest.testFlowBasedObject(), and org.onosproject.net.flow.DefaultFlowRule.toString().
TrafficSelector org.onosproject.net.flow.DefaultFlowRule.selector ()
Returns the traffic selector that identifies what traffic this rule should apply to.
Returns
traffic selector
Implements org.onosproject.net.flow.FlowRule.
Definition at line 202 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule(), org.onosproject.net.flow.DefaultFlowRule.equals(), org.onosproject.net.flow.DefaultFlowRule.hashCode(), org.onosproject.net.flow.DefaultFlowEntryTest.testDeviceBasedObject(), and org.onosproject.net.flow.DefaultFlowEntryTest.testSetters().
int org.onosproject.net.flow.DefaultFlowRule.tableId ()
Returns the table id for this rule.
Returns
an integer.
Implements org.onosproject.net.flow.FlowRule.
Definition at line 283 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRule.hashCode().
int org.onosproject.net.flow.DefaultFlowRule.timeout ()
Returns the timeout for this flow requested by an application.
Returns
integer value of the timeout
Implements org.onosproject.net.flow.FlowRule.
Definition at line 273 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule(), org.onosproject.net.flow.DefaultFlowEntryTest.testDeviceBasedObject(), and org.onosproject.net.flow.DefaultFlowEntryTest.testSetters().
String org.onosproject.net.flow.DefaultFlowRule.toString ()
Definition at line 259 of file DefaultFlowRule.java.
References org.onosproject.net.flow.TrafficTreatment.allInstructions(), org.onosproject.net.flow.TrafficSelector.criteria(), org.onosproject.net.flow.DefaultFlowRule.payLoad(), and org.onosproject.net.flow.DefaultFlowRule.priority().
TrafficTreatment org.onosproject.net.flow.DefaultFlowRule.treatment ()
Returns the traffic treatment that applies to selected traffic.
Returns
traffic treatment
Implements org.onosproject.net.flow.FlowRule.
Definition at line 207 of file DefaultFlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule(), org.onosproject.net.flow.DefaultFlowEntryTest.testDeviceBasedObject(), and org.onosproject.net.flow.DefaultFlowEntryTest.testSetters().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/DefaultFlowRule.java