onos: org.onosproject.net.proxyarp.impl.ProxyArpManagerTest Class Reference
org.onosproject.net.proxyarp.impl.ProxyArpManagerTest Class Reference
Tests for the ProxyArpManager class.
Classes
class TestPacketService
Test PacketService implementation that simply stores OutboundPackets passed to emit(OutboundPacket) for later verification.
Public Member Functions
void setUp () throws Exception
void testNotKnown ()
Tests ProxyArpManager#isKnown(org.onlab.packet.IpAddress) in the case where the IP address is not known.
void testKnown ()
Tests ProxyArpManager#isKnown(org.onlab.packet.IpAddress) in the case where the IP address is known.
void testReplyKnown ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is known.
void testReplyKnownIpv6 ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is known.
void testReplyUnknown ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is not known.
void testReplyUnknownIpv6 ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is not known.
void testReplyDifferentVlan ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is known for that IP address, but is not on the same VLAN as the source host.
void testConfiguredVlan ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the a vlan packet comes in from a port without interfaces configured.
void testConfiguredVlanOnInterfaces ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the a vlan packet comes in from a port without interfaces configured.
void testReplyDifferentVlanIpv6 ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is known for that IP address, but is not on the same VLAN as the source host.
void testReplyToRequestForUs ()
Test ARP request from external network to an internal host.
void testReplyToRequestForUsIpv6 ()
Test NDP request from external network to an internal host.
void testReplyExternalPortBadRequest ()
Request for a valid external IPv4 address but coming in the wrong port.
void testReplyExternalPortBadRequestIpv6 ()
Request for a valid external IPv6 address but coming in the wrong port.
void testReplyToRequestFromUs ()
Test ARP request from internal network to an external host.
void testReplyToRequestFromUsIpv6 ()
Test NDP request from internal network to an external host.
void testForwardToHost ()
Tests ProxyArpManager#forward(Ethernet, ConnectPoint) in the case where the destination host is known.
void testForwardToHostIpv6 ()
Tests ProxyArpManager#forward(Ethernet, ConnectPoint) in the case where the destination host is known.
void testForwardFlood ()
Tests ProxyArpManager#forward(Ethernet, ConnectPoint) in the case where the destination host is not known.
void testForwardFloodIpv6 ()
Tests ProxyArpManager#forward(Ethernet, ConnectPoint) in the case where the destination host is not known.
Detailed Description
Tests for the ProxyArpManager class.
Definition at line 89 of file ProxyArpManagerTest.java.
Member Function Documentation
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.setUp () throws Exception
Definition at line 155 of file ProxyArpManagerTest.java.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testConfiguredVlan ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the a vlan packet comes in from a port without interfaces configured.
The destination host is unknown for that IP address and there are some interfaces configured on the same vlan. It's expected to see the ARP request going out through ports with no interfaces configured, devices 4 and 5, port 1.
Verifies the ARP request is flooded out the correct edge ports.
Definition at line 615 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByIp(), and org.onlab.packet.ARP.OP_REQUEST.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testConfiguredVlanOnInterfaces ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the a vlan packet comes in from a port without interfaces configured.
The destination host is not known for that IP address and there are some interfaces configured on the same vlan. It's expected to see the ARP request going out through ports with no interfaces configured, devices 4 and 5, port 1.
Verifies the ARP request is flooded out the correct edge ports.
Definition at line 646 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByIp(), and org.onlab.packet.ARP.OP_REQUEST.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testForwardFlood ()
Tests ProxyArpManager#forward(Ethernet, ConnectPoint) in the case where the destination host is not known.
Verifies the correct ARP request is flooded out the correct edge ports.
Definition at line 975 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), and org.onlab.packet.ARP.OP_REPLY.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testForwardFloodIpv6 ()
Tests ProxyArpManager#forward(Ethernet, ConnectPoint) in the case where the destination host is not known.
Verifies the correct NDP request is flooded out the correct edge ports.
Definition at line 993 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), and org.onlab.packet.ICMP6.NEIGHBOR_SOLICITATION.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testForwardToHost ()
Tests ProxyArpManager#forward(Ethernet, ConnectPoint) in the case where the destination host is known.
Verifies the correct ARP request is sent out the correct port.
Definition at line 919 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), and org.onlab.packet.ARP.OP_REPLY.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testForwardToHostIpv6 ()
Tests ProxyArpManager#forward(Ethernet, ConnectPoint) in the case where the destination host is known.
Verifies the correct ARP request is sent out the correct port.
Definition at line 946 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), and org.onlab.packet.ICMP6.NEIGHBOR_SOLICITATION.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testKnown ()
Tests ProxyArpManager#isKnown(org.onlab.packet.IpAddress) in the case where the IP address is known.
Verifies the method returns true.
Definition at line 433 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHostsByIp(), and org.onosproject.net.proxyarp.impl.ProxyArpManager.isKnown().
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testNotKnown ()
Tests ProxyArpManager#isKnown(org.onlab.packet.IpAddress) in the case where the IP address is not known.
Verifies the method returns false.
Definition at line 419 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHostsByIp(), and org.onosproject.net.proxyarp.impl.ProxyArpManager.isKnown().
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyDifferentVlan ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is known for that IP address, but is not on the same VLAN as the source host.
An host is connected on device 6, port 1 where no interfaces are defined. It sends ARP requests from VLAN10, not configured anywhere in the network. Another host with the IP address requested lives on device 5, port 1 in the network. Anyway, since the host uses another VLAN it's not found and the ARP packet is flooded out of port 4 and 5.
Verifies the ARP request is flooded out the correct edge ports.
Definition at line 581 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByIp(), and org.onlab.packet.ARP.OP_REQUEST.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyDifferentVlanIpv6 ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is known for that IP address, but is not on the same VLAN as the source host.
Verifies the NDP request is flooded out the correct edge ports.
Definition at line 673 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByIp(), and org.onlab.packet.ICMP6.NEIGHBOR_SOLICITATION.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyExternalPortBadRequest ()
Request for a valid external IPv4 address but coming in the wrong port.
Definition at line 793 of file ProxyArpManagerTest.java.
References org.onlab.packet.ARP.OP_REQUEST, and org.onlab.packet.Ip4Address.valueOf().
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyExternalPortBadRequestIpv6 ()
Request for a valid external IPv6 address but coming in the wrong port.
Definition at line 816 of file ProxyArpManagerTest.java.
References org.onlab.packet.ICMP6.NEIGHBOR_SOLICITATION, and org.onlab.packet.MacAddress.valueOf().
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyKnown ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is known.
Two host using the same VLAN are registered on the host service on devices 5 and 6. Host on port 6 asks for the MAC of the device on port 5. Since the destination mac address is known, the request is not flooded to anywhere and ONOS directly builds an ARP reply, sended back to the requester on device 6. It's verified that a proper ARP reply is received on port 1 of device 6.
Definition at line 455 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onlab.packet.ARP.OP_REPLY, and org.onlab.packet.ARP.OP_REQUEST.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyKnownIpv6 ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is known.
Verifies the correct NDP reply is sent out the correct port.
Definition at line 484 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onlab.packet.ICMP6.NEIGHBOR_ADVERTISEMENT, and org.onlab.packet.ICMP6.NEIGHBOR_SOLICITATION.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestForUs ()
Test ARP request from external network to an internal host.
Definition at line 702 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onlab.packet.ARP.OP_REPLY, and org.onlab.packet.ARP.OP_REQUEST.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestForUsIpv6 ()
Test NDP request from external network to an internal host.
Definition at line 739 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onlab.packet.ICMP6.NEIGHBOR_ADVERTISEMENT, org.onlab.packet.ICMP6.NEIGHBOR_SOLICITATION, and org.onlab.packet.MacAddress.valueOf().
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUs ()
Test ARP request from internal network to an external host.
Definition at line 845 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByIp(), org.onosproject.net.HostId.hostId(), org.onlab.packet.ARP.OP_REQUEST, and org.onlab.packet.IpPrefix.valueOf().
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUsIpv6 ()
Test NDP request from internal network to an external host.
Definition at line 878 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByIp(), org.onosproject.net.HostId.hostId(), org.onlab.packet.ICMP6.NEIGHBOR_SOLICITATION, org.onlab.packet.MacAddress.valueOf(), and org.onlab.packet.IpPrefix.valueOf().
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyUnknown ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is not known.
Only a requestor is present (on device 6, port 1). The device has a VLAN configured which is not configured anywhere in the system. Since the destination is not known, and since the ARP request can't be sent out of interfaces configured, the ARP request is flooded out of ports 4 and 5. Verifies the ARP request is flooded out the correct edge ports.
Definition at line 520 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByIp(), and org.onlab.packet.ARP.OP_REQUEST.
void org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyUnknownIpv6 ()
Tests ProxyArpManager#reply(Ethernet, ConnectPoint) in the case where the destination host is not known.
Verifies the NDP request is flooded out the correct edge ports.
Definition at line 546 of file ProxyArpManagerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.host.HostService.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByIp(), and org.onlab.packet.ICMP6.NEIGHBOR_SOLICITATION.
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/proxyarp/impl/ProxyArpManagerTest.java