onos: org.onosproject.vtnrsc.DefaultRouter Class Reference
org.onosproject.vtnrsc.DefaultRouter Class Reference
Default implementation of router interface.
Public Member Functions
DefaultRouter (RouterId id, String routerName, boolean adminStateUp, Status status, boolean distributed, RouterGateway externalGatewayInfo, VirtualPortId gatewayPortId, TenantId tenantId, List< String > routes)
Creates router object.
RouterId id ()
Returns the router identifier.
String name ()
Returns the router Name.
boolean adminStateUp ()
Returns the router admin state.
Status status ()
Returns the status of router.
boolean distributed ()
Returns the distributed status of this router.
RouterGateway externalGatewayInfo ()
Returns the RouterGateway of router.
VirtualPortId gatewayPortid ()
Returns the gatewayPortid of router.
TenantId tenantId ()
Returns the owner(tenant) of this router.
List< String > routes ()
Returns the router list of router.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of router interface.
Definition at line 27 of file DefaultRouter.java.
Constructor & Destructor Documentation
org.onosproject.vtnrsc.DefaultRouter.DefaultRouter (RouterId id, String routerName, boolean adminStateUp, Status status, boolean distributed, RouterGateway externalGatewayInfo, VirtualPortId gatewayPortId, TenantId tenantId, List< String > routes)
Creates router object.
Parameters
id router identifier
routerName the name of router
adminStateUp the status of admin state
status the status of router
distributed the status of router distributed
externalGatewayInfo the gateway info of router
gatewayPortId the port identifier of router gateway
tenantId the tenant identifier
routes the routes configure
Definition at line 51 of file DefaultRouter.java.
References org.onosproject.vtnrsc.DefaultRouter.externalGatewayInfo(), and org.onosproject.vtnrsc.DefaultRouter.routes().
Referenced by org.onosproject.vtnrsc.DefaultRouter.equals().
Member Function Documentation
boolean org.onosproject.vtnrsc.DefaultRouter.adminStateUp ()
Returns the router admin state.
Returns
true or false
Implements org.onosproject.vtnrsc.Router.
Definition at line 78 of file DefaultRouter.java.
Referenced by org.onosproject.vtnrsc.DefaultRouter.hashCode(), and org.onosproject.vtnrsc.DefaultRouter.toString().
boolean org.onosproject.vtnrsc.DefaultRouter.distributed ()
Returns the distributed status of this router.
If true, indicates a distributed router.
Returns
true or false
Implements org.onosproject.vtnrsc.Router.
Definition at line 88 of file DefaultRouter.java.
Referenced by org.onosproject.vtnrsc.DefaultRouter.hashCode(), and org.onosproject.vtnrsc.DefaultRouter.toString().
boolean org.onosproject.vtnrsc.DefaultRouter.equals (Object obj)
Definition at line 119 of file DefaultRouter.java.
References org.onosproject.vtnrsc.DefaultRouter.DefaultRouter(), and find-device.id.
RouterGateway org.onosproject.vtnrsc.DefaultRouter.externalGatewayInfo ()
Returns the RouterGateway of router.
Returns
routerGateway
Implements org.onosproject.vtnrsc.Router.
Definition at line 93 of file DefaultRouter.java.
Referenced by org.onosproject.vtnrsc.DefaultRouter.DefaultRouter(), org.onosproject.vtnrsc.DefaultRouter.hashCode(), and org.onosproject.vtnrsc.DefaultRouter.toString().
VirtualPortId org.onosproject.vtnrsc.DefaultRouter.gatewayPortid ()
Returns the gatewayPortid of router.
Returns
virtualPortId
Implements org.onosproject.vtnrsc.Router.
Definition at line 98 of file DefaultRouter.java.
int org.onosproject.vtnrsc.DefaultRouter.hashCode ()
Definition at line 113 of file DefaultRouter.java.
References org.onosproject.vtnrsc.DefaultRouter.adminStateUp(), org.onosproject.vtnrsc.DefaultRouter.distributed(), org.onosproject.vtnrsc.DefaultRouter.externalGatewayInfo(), org.onosproject.vtnrsc.DefaultRouter.id(), org.onosproject.vtnrsc.DefaultRouter.name(), org.onosproject.vtnrsc.DefaultRouter.routes(), and org.onosproject.vtnrsc.DefaultRouter.status().
RouterId org.onosproject.vtnrsc.DefaultRouter.id ()
Returns the router identifier.
Returns
identifier
Implements org.onosproject.vtnrsc.Router.
Definition at line 68 of file DefaultRouter.java.
Referenced by org.onosproject.vtnrsc.DefaultRouter.hashCode(), and org.onosproject.vtnrsc.DefaultRouter.toString().
String org.onosproject.vtnrsc.DefaultRouter.name ()
Returns the router Name.
Returns
routerName
Implements org.onosproject.vtnrsc.Router.
Definition at line 73 of file DefaultRouter.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.vtnrsc.DefaultRouter.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.vtnrsc.DefaultRouter.toString().
List<String> org.onosproject.vtnrsc.DefaultRouter.routes ()
Returns the router list of router.
Returns
routes
Implements org.onosproject.vtnrsc.Router.
Definition at line 108 of file DefaultRouter.java.
Referenced by org.onosproject.vtnrsc.DefaultRouter.DefaultRouter(), org.onosproject.vtnrsc.DefaultRouter.hashCode(), and org.onosproject.vtnrsc.DefaultRouter.toString().
Status org.onosproject.vtnrsc.DefaultRouter.status ()
Returns the status of router.
Returns
RouterStatus
Implements org.onosproject.vtnrsc.Router.
Definition at line 83 of file DefaultRouter.java.
Referenced by org.onosproject.vtnrsc.DefaultRouter.hashCode(), and org.onosproject.vtnrsc.DefaultRouter.toString().
TenantId org.onosproject.vtnrsc.DefaultRouter.tenantId ()
Returns the owner(tenant) of this router.
Returns
tenantId
Implements org.onosproject.vtnrsc.Router.
Definition at line 103 of file DefaultRouter.java.
String org.onosproject.vtnrsc.DefaultRouter.toString ()
Definition at line 139 of file DefaultRouter.java.
References org.onosproject.vtnrsc.DefaultRouter.adminStateUp(), org.onosproject.vtnrsc.DefaultRouter.distributed(), org.onosproject.vtnrsc.DefaultRouter.externalGatewayInfo(), org.onosproject.vtnrsc.DefaultRouter.id(), org.onosproject.vtnrsc.DefaultRouter.name(), org.onosproject.vtnrsc.DefaultRouter.routes(), and org.onosproject.vtnrsc.DefaultRouter.status().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultRouter.java