onos: org.onosproject.ui.topo.NodeSelection Class Reference
org.onosproject.ui.topo.NodeSelection Class Reference
Encapsulates a selection of devices and/or hosts from the topology view.
Public Member Functions
NodeSelection (ObjectNode payload, DeviceService deviceService, HostService hostService)
Creates a node selection entity, from the given payload, using the supplied device and host services.
Set< Device > devices ()
Returns a view of the selected devices (hover not included).
Set< Device > devicesWithHover ()
Returns a view of the selected devices, including the hovered device if there was one.
Set< Host > hosts ()
Returns a view of the selected hosts (hover not included).
Set< Host > hostsWithHover ()
Returns a view of the selected hosts, including the hovered host if thee was one.
Element hovered ()
Returns the element (host or device) over which the mouse was hovering, or null.
boolean none ()
Returns true if nothing is selected.
String toString ()
Detailed Description
Encapsulates a selection of devices and/or hosts from the topology view.
Definition at line 42 of file NodeSelection.java.
Constructor & Destructor Documentation
org.onosproject.ui.topo.NodeSelection.NodeSelection (ObjectNode payload, DeviceService deviceService, HostService hostService)
Creates a node selection entity, from the given payload, using the supplied device and host services.
Note that if a device or host was hovered over by the mouse, it is available via hovered().
Parameters
payload message payload
deviceService device service
hostService host service
Definition at line 69 of file NodeSelection.java.
References org.onosproject.ui.topo.NodeSelection.hovered().
Member Function Documentation
Set<Device> org.onosproject.ui.topo.NodeSelection.devices ()
Returns a view of the selected devices (hover not included).
Returns
selected devices
Definition at line 99 of file NodeSelection.java.
Referenced by org.onosproject.ui.topo.NodeSelection.devicesWithHover(), and org.onosproject.ui.topo.NodeSelection.none().
Set<Device> org.onosproject.ui.topo.NodeSelection.devicesWithHover ()
Returns a view of the selected devices, including the hovered device if there was one.
Returns
selected (plus hovered) devices
Definition at line 109 of file NodeSelection.java.
References org.onosproject.ui.topo.NodeSelection.devices(), and org.onosproject.ui.topo.NodeSelection.hovered().
Referenced by org.onosproject.ui.topo.NodeSelectionTest.basic(), org.onosproject.ui.impl.topo.IntentSelection.IntentSelection(), org.onosproject.ui.impl.TrafficMonitor.monitor(), org.onosproject.ui.topo.NodeSelectionTest.oneDevice(), org.onosproject.ui.topo.NodeSelectionTest.oneHost(), org.onosproject.ui.topo.NodeSelectionTest.oneHostAndHoveringDevice(), org.onosproject.ui.topo.NodeSelectionTest.twoDevicesOneHostAndHoveringHost(), and org.onosproject.ui.topo.NodeSelectionTest.twoHostsOneDevice().
Set<Host> org.onosproject.ui.topo.NodeSelection.hosts ()
Returns a view of the selected hosts (hover not included).
Returns
selected hosts
Definition at line 125 of file NodeSelection.java.
Referenced by org.onosproject.ui.topo.NodeSelection.hostsWithHover(), org.onosproject.ui.topo.NodeSelection.none(), and org.onosproject.ui.topo.NodeSelection.toString().
Set<Host> org.onosproject.ui.topo.NodeSelection.hostsWithHover ()
Returns a view of the selected hosts, including the hovered host if thee was one.
Returns
selected (plus hovered) hosts
Definition at line 135 of file NodeSelection.java.
References org.onosproject.ui.topo.NodeSelection.hosts(), and org.onosproject.ui.topo.NodeSelection.hovered().
Referenced by org.onosproject.ui.topo.NodeSelectionTest.basic(), org.onosproject.ui.topo.NodeSelectionTest.oneDevice(), org.onosproject.ui.topo.NodeSelectionTest.oneHost(), org.onosproject.ui.topo.NodeSelectionTest.oneHostAndHoveringDevice(), org.onosproject.ui.topo.NodeSelectionTest.twoDevicesOneHostAndHoveringHost(), and org.onosproject.ui.topo.NodeSelectionTest.twoHostsOneDevice().
Element org.onosproject.ui.topo.NodeSelection.hovered ()
Returns the element (host or device) over which the mouse was hovering, or null.
Returns
element hovered over
Definition at line 152 of file NodeSelection.java.
Referenced by org.onosproject.ui.topo.NodeSelection.devicesWithHover(), org.onosproject.ui.topo.NodeSelection.hostsWithHover(), and org.onosproject.ui.topo.NodeSelection.NodeSelection().
boolean org.onosproject.ui.topo.NodeSelection.none ()
Returns true if nothing is selected.
Returns
true if nothing selected
Definition at line 161 of file NodeSelection.java.
References org.onosproject.ui.topo.NodeSelection.devices(), and org.onosproject.ui.topo.NodeSelection.hosts().
Referenced by org.onosproject.ui.topo.NodeSelectionTest.basic(), org.onosproject.ui.impl.TrafficMonitor.monitor(), org.onosproject.ui.topo.NodeSelectionTest.oneDevice(), org.onosproject.ui.topo.NodeSelectionTest.oneHost(), org.onosproject.ui.topo.NodeSelectionTest.oneHostAndHoveringDevice(), org.onosproject.ui.topo.NodeSelectionTest.twoDevicesOneHostAndHoveringHost(), and org.onosproject.ui.topo.NodeSelectionTest.twoHostsOneDevice().
String org.onosproject.ui.topo.NodeSelection.toString ()
Definition at line 166 of file NodeSelection.java.
References org.onosproject.ui.topo.NodeSelection.hosts().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/topo/NodeSelection.java