onos: org.onosproject.net.newresource.impl.ResourceManager Class Reference
org.onosproject.net.newresource.impl.ResourceManager Class Reference
An implementation of ResourceService.
Public Member Functions
void activate ()
void deactivate ()
List< ResourceAllocation > allocate (ResourceConsumer consumer, List< ResourcePath > resources)
Transactionally allocates the specified resources to the specified user.
boolean release (List< ResourceAllocation > allocations)
Transactionally releases the specified resource allocations.
boolean release (ResourceConsumer consumer)
Transactionally releases the resources allocated to the specified consumer.
Optional< ResourceAllocation > getResourceAllocation (ResourcePath resource)
Returns resource allocation of the specified resource.
Collection< ResourceAllocation > getResourceAllocations (ResourceConsumer consumer)
Returns resources allocated to the specified consumer.
Collection< ResourcePath > getAvailableResources (ResourcePath parent)
Returns resource paths that point available child resources under the specified resource path.
boolean isAvailable (ResourcePath resource)
Returns the availability of the specified resource.
boolean registerResources (List< ResourcePath > resources)
Registers the specified resources.
boolean unregisterResources (List< ResourcePath > resources)
Unregisters the specified resources.
Public Member Functions inherited from org.onosproject.net.newresource.ResourceService
default Optional
< ResourceAllocation > allocate (ResourceConsumer consumer, ResourcePath resource)
Allocates the specified resource to the specified user.
default List< ResourceAllocation > allocate (ResourceConsumer consumer, ResourcePath...resources)
Transactionally allocates the specified resources to the specified user.
default boolean release (ResourceAllocation allocation)
Releases the specified resource allocation.
default boolean release (ResourceAllocation...allocations)
Transactionally releases the specified resource allocations.
Public Member Functions inherited from org.onosproject.net.newresource.ResourceAdminService
default boolean registerResources (ResourcePath...resources)
Registers the specified resources.
default boolean unregisterResources (ResourcePath...resources)
Unregisters the specified resources.
Protected Attributes
ResourceStore store
Detailed Description
An implementation of ResourceService.
Definition at line 51 of file ResourceManager.java.
Member Function Documentation
void org.onosproject.net.newresource.impl.ResourceManager.activate ()
Definition at line 60 of file ResourceManager.java.
List<ResourceAllocation> org.onosproject.net.newresource.impl.ResourceManager.allocate (ResourceConsumer consumer, List< ResourcePath > resources)
Transactionally allocates the specified resources to the specified user.
All allocations are made when this method succeeds, or no allocation is made when this method fails.
Parameters
consumer resource user which the resources are allocated to
resources resources to be allocated
Returns
non-empty list of allocation information if succeeded, otherwise empty list
Implements org.onosproject.net.newresource.ResourceService.
Definition at line 72 of file ResourceManager.java.
void org.onosproject.net.newresource.impl.ResourceManager.deactivate ()
Definition at line 66 of file ResourceManager.java.
Collection<ResourcePath> org.onosproject.net.newresource.impl.ResourceManager.getAvailableResources (ResourcePath parent)
Returns resource paths that point available child resources under the specified resource path.
Parameters
parent parent resource path
Returns
available resource paths under the specified resource path
Implements org.onosproject.net.newresource.ResourceService.
Definition at line 146 of file ResourceManager.java.
References org.onosproject.net.newresource.ResourceStore.getConsumer(), and org.onosproject.net.newresource.impl.ResourceManager.store.
Optional<ResourceAllocation> org.onosproject.net.newresource.impl.ResourceManager.getResourceAllocation (ResourcePath resource)
Returns resource allocation of the specified resource.
Parameters
resource resource to check the allocation
Returns
allocation information enclosed by Optional. If the resource is not allocated, the return value is empty.
Implements org.onosproject.net.newresource.ResourceService.
Definition at line 110 of file ResourceManager.java.
Collection<ResourceAllocation> org.onosproject.net.newresource.impl.ResourceManager.getResourceAllocations (ResourceConsumer consumer)
Returns resources allocated to the specified consumer.
Parameters
consumer consumer whose allocated resources are to be returned
Returns
resources allocated to the consumer
Implements org.onosproject.net.newresource.ResourceService.
Definition at line 136 of file ResourceManager.java.
boolean org.onosproject.net.newresource.impl.ResourceManager.isAvailable (ResourcePath resource)
Returns the availability of the specified resource.
Parameters
resource resource to check the availability
Returns
true if available, otherwise false
Implements org.onosproject.net.newresource.ResourceService.
Definition at line 157 of file ResourceManager.java.
boolean org.onosproject.net.newresource.impl.ResourceManager.registerResources (List< ResourcePath > resources)
Registers the specified resources.
Parameters
resources resources to be registered
Returns
true if registration is successfully done, false otherwise. Registration succeeds when each resource is not registered or unallocated.
Implements org.onosproject.net.newresource.ResourceAdminService.
Definition at line 165 of file ResourceManager.java.
boolean org.onosproject.net.newresource.impl.ResourceManager.release (List< ResourceAllocation > allocations)
Transactionally releases the specified resource allocations.
All allocations are released when this method succeeded, or no allocation is released when this method fails.
Parameters
allocations resource allocations to be released
Returns
true if succeeded, otherwise false
Implements org.onosproject.net.newresource.ResourceService.
Definition at line 88 of file ResourceManager.java.
References org.onosproject.net.newresource.ResourceAllocation.consumer(), and org.onosproject.net.newresource.ResourceAllocation.resource().
Referenced by org.onosproject.net.newresource.impl.ResourceManager.release().
boolean org.onosproject.net.newresource.impl.ResourceManager.release (ResourceConsumer consumer)
Transactionally releases the resources allocated to the specified consumer.
All allocations are released when this method succeeded, or no allocation is released when this method fails.
Parameters
consumer consumer whose allocated resources are to be released
Returns
true if succeeded, otherwise false
Implements org.onosproject.net.newresource.ResourceService.
Definition at line 102 of file ResourceManager.java.
References org.onosproject.net.newresource.impl.ResourceManager.release().
boolean org.onosproject.net.newresource.impl.ResourceManager.unregisterResources (List< ResourcePath > resources)
Unregisters the specified resources.
Parameters
resources resources to be unregistered
Returns
true if unregistration is successfully done, false otherwise. Unregistration succeeds when each resource is not registered or unallocated.
Implements org.onosproject.net.newresource.ResourceAdminService.
Definition at line 172 of file ResourceManager.java.
Member Data Documentation
ResourceStore org.onosproject.net.newresource.impl.ResourceManager.store protected
Definition at line 55 of file ResourceManager.java.
Referenced by org.onosproject.net.newresource.impl.ResourceManager.getAvailableResources().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/newresource/impl/ResourceManager.java