onos: org.onosproject.driver.pipeline.OFDPA2Pipeline Class Reference
org.onosproject.driver.pipeline.OFDPA2Pipeline Class Reference
Driver for Broadcom's OF-DPA v2.0 TTP.
Public Member Functions
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filteringObjective)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
void processStaticFlows ()
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Protected Member Functions
void initializePipeline ()
List< FlowRule > processVlanIdFilter (PortCriterion portCriterion, VlanIdCriterion vidCriterion, VlanId assignedVlan, ApplicationId applicationId)
Allows untagged packets into pipeline by assigning a vlan id.
List< FlowRule > processEthDstFilter (PortCriterion portCriterion, EthCriterion ethCriterion, VlanIdCriterion vidCriterion, VlanId assignedVlan, ApplicationId applicationId)
Allows routed packets with correct destination MAC to be directed to unicast-IP routing table or MPLS forwarding table.
Collection< FlowRule > processSpecific (ForwardingObjective fwd)
In the OF-DPA 2.0 pipeline, specific forwarding refers to the IP table (unicast or multicast) or the L2 table (mac + vlan) or the MPLS table.
void fail (Objective obj, ObjectiveError error)
void processGroupTable ()
void processMplsTable ()
void processPortTable ()
void processTmacTable ()
void processIpTable ()
void processAclTable ()
Protected Attributes
FlowRuleService flowRuleService
GroupService groupService
FlowObjectiveStore flowObjectiveStore
DeviceId deviceId
ApplicationId driverId
PacketService packetService
DeviceService deviceService
KryoNamespace appKryo
Static Protected Attributes
static final int PORT_TABLE = 0
static final int VLAN_TABLE = 10
static final int TMAC_TABLE = 20
static final int UNICAST_ROUTING_TABLE = 30
static final int MULTICAST_ROUTING_TABLE = 40
static final int MPLS_TABLE_0 = 23
static final int MPLS_TABLE_1 = 24
static final int BRIDGING_TABLE = 50
static final int ACL_TABLE = 60
static final int MAC_LEARNING_TABLE = 254
static final long OFPP_MAX = 0xffffff00L
static final int DEFAULT_PRIORITY = 0x8000
static final int LOWEST_PRIORITY = 0x0
Detailed Description
Driver for Broadcom's OF-DPA v2.0 TTP.
Definition at line 119 of file OFDPA2Pipeline.java.
Member Function Documentation
void org.onosproject.driver.pipeline.OFDPA2Pipeline.fail (Objective obj, ObjectiveError error) protected
Definition at line 795 of file OFDPA2Pipeline.java.
References org.onosproject.net.flowobjective.Objective.context().
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.filter(), org.onosproject.driver.pipeline.OFDPA2Pipeline.forward(), org.onosproject.driver.pipeline.OFDPA2Pipeline.init(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
void org.onosproject.driver.pipeline.OFDPA2Pipeline.filter (FilteringObjective filterObjective)
Installs the filtering rules onto the device.
Parameters
filterObjective a filtering objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 237 of file OFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.fail(), org.onosproject.net.flowobjective.Objective.op(), org.onosproject.net.flowobjective.FilteringObjective.type(), and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.forward().
void org.onosproject.driver.pipeline.OFDPA2Pipeline.forward (ForwardingObjective forwardObjective)
Installs the forwarding rules onto the device.
Parameters
forwardObjective a forwarding objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 253 of file OFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.fail(), org.onosproject.driver.pipeline.OFDPA2Pipeline.filter(), org.onosproject.net.flowobjective.ObjectiveError.FLOWINSTALLATIONFAILED, org.onosproject.net.flowobjective.Objective.op(), and org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN.
void org.onosproject.driver.pipeline.OFDPA2Pipeline.init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
Parameters
deviceId the deviceId
context processing context
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 192 of file OFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceService, org.onosproject.driver.pipeline.OFDPA2Pipeline.driverId, org.onosproject.driver.pipeline.OFDPA2Pipeline.fail(), org.onosproject.driver.pipeline.OFDPA2Pipeline.flowObjectiveStore, org.onosproject.driver.pipeline.OFDPA2Pipeline.flowRuleService, org.onosproject.net.flowobjective.ObjectiveError.GROUPINSTALLATIONFAILED, org.onosproject.driver.pipeline.OFDPA2Pipeline.groupService, org.onosproject.driver.pipeline.OFDPA2Pipeline.initializePipeline(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.packetService.
void org.onosproject.driver.pipeline.OFDPA2Pipeline.initializePipeline () protected
Definition at line 228 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.init().
void org.onosproject.driver.pipeline.OFDPA2Pipeline.next (NextObjective nextObjective)
Installs the next hop elements into the device.
Parameters
nextObjective a next objectives
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 290 of file OFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, and org.onosproject.net.flowobjective.Objective.op().
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
void org.onosproject.driver.pipeline.OFDPA2Pipeline.processAclTable () protected
Definition at line 1856 of file OFDPA2Pipeline.java.
List<FlowRule> org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter (PortCriterion portCriterion, EthCriterion ethCriterion, VlanIdCriterion vidCriterion, VlanId assignedVlan, ApplicationId applicationId) protected
Allows routed packets with correct destination MAC to be directed to unicast-IP routing table or MPLS forwarding table.
Parameters
portCriterion port on device for which this filter is programmed
ethCriterion dstMac of device for which is filter is programmed
vidCriterion vlan assigned to port, or NONE for untagged
assignedVlan assigned vlan-id for untagged packets
applicationId for application programming this filter
Returns
list of FlowRule for port-vlan filters
Definition at line 561 of file OFDPA2Pipeline.java.
References org.onosproject.net.PortNumber.ALL, org.onosproject.driver.pipeline.OFDPA2Pipeline.DEFAULT_PRIORITY, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceService, org.onosproject.net.device.DeviceService.getPorts(), org.onosproject.net.flow.criteria.Criteria.matchVlanId(), org.onosproject.driver.pipeline.OFDPA2Pipeline.MPLS_TABLE_0, org.onlab.packet.Ethernet.MPLS_UNICAST, org.onlab.packet.VlanId.NONE, org.onosproject.driver.pipeline.OFDPA2Pipeline.OFPP_MAX, obeliskHostCheck.port, org.onosproject.driver.pipeline.OFDPA2Pipeline.TMAC_TABLE, org.onlab.packet.Ethernet.TYPE_IPV4, and org.onosproject.driver.pipeline.OFDPA2Pipeline.UNICAST_ROUTING_TABLE.
void org.onosproject.driver.pipeline.OFDPA2Pipeline.processGroupTable () protected
Definition at line 1574 of file OFDPA2Pipeline.java.
void org.onosproject.driver.pipeline.OFDPA2Pipeline.processIpTable () protected
Definition at line 1825 of file OFDPA2Pipeline.java.
void org.onosproject.driver.pipeline.OFDPA2Pipeline.processMplsTable () protected
Definition at line 1686 of file OFDPA2Pipeline.java.
void org.onosproject.driver.pipeline.OFDPA2Pipeline.processPortTable () protected
Definition at line 1719 of file OFDPA2Pipeline.java.
Collection<FlowRule> org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific (ForwardingObjective fwd) protected
In the OF-DPA 2.0 pipeline, specific forwarding refers to the IP table (unicast or multicast) or the L2 table (mac + vlan) or the MPLS table.
Parameters
fwd the forwarding objective of type 'specific'
Returns
a collection of flow rules. Typically there will be only one for this type of forwarding objective. An empty set may be returned if there is an issue in processing the objective.
Definition at line 699 of file OFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.ACL_TABLE, org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.fail(), org.onosproject.net.flow.TrafficSelector.getCriterion(), org.onosproject.net.flowobjective.ObjectiveError.GROUPMISSING, org.onosproject.net.group.Group.id(), org.onosproject.net.flow.instructions.L2ModificationInstruction.L2SubType.MPLS_POP, org.onosproject.driver.pipeline.OFDPA2Pipeline.MPLS_TABLE_1, org.onlab.packet.Ethernet.MPLS_UNICAST, org.onosproject.driver.pipeline.OFDPA2Pipeline.next(), org.onosproject.net.flowobjective.ForwardingObjective.nextId(), org.onosproject.net.flowobjective.Objective.permanent(), org.onosproject.net.flowobjective.Objective.priority(), org.onosproject.net.flowobjective.ForwardingObjective.treatment(), org.onlab.packet.Ethernet.TYPE_IPV4, org.onosproject.driver.pipeline.OFDPA2Pipeline.UNICAST_ROUTING_TABLE, and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
void org.onosproject.driver.pipeline.OFDPA2Pipeline.processStaticFlows ()
Definition at line 1561 of file OFDPA2Pipeline.java.
void org.onosproject.driver.pipeline.OFDPA2Pipeline.processTmacTable () protected
Definition at line 1780 of file OFDPA2Pipeline.java.
List<FlowRule> org.onosproject.driver.pipeline.OFDPA2Pipeline.processVlanIdFilter (PortCriterion portCriterion, VlanIdCriterion vidCriterion, VlanId assignedVlan, ApplicationId applicationId) protected
Allows untagged packets into pipeline by assigning a vlan id.
Vlan assignment is done by the application. Allows tagged packets into pipeline as per configured port-vlan info.
Parameters
portCriterion port on device for which this filter is programmed
vidCriterion vlan assigned to port, or NONE for untagged
assignedVlan assigned vlan-id for untagged packets
applicationId for application programming this filter
Returns
list of FlowRule for port-vlan filters
Definition at line 487 of file OFDPA2Pipeline.java.
References org.onosproject.net.PortNumber.ALL, org.onosproject.driver.pipeline.OFDPA2Pipeline.DEFAULT_PRIORITY, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceService, org.onosproject.net.device.DeviceService.getPorts(), org.onlab.packet.VlanId.NONE, org.onosproject.driver.pipeline.OFDPA2Pipeline.OFPP_MAX, obeliskHostCheck.port, org.onosproject.driver.pipeline.OFDPA2Pipeline.TMAC_TABLE, and org.onosproject.driver.pipeline.OFDPA2Pipeline.VLAN_TABLE.
Member Data Documentation
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.ACL_TABLE = 60 static protected
Definition at line 129 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processAclTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processIpTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processMplsTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
KryoNamespace org.onosproject.driver.pipeline.OFDPA2Pipeline.appKryo protected
Initial value:
= new KryoNamespace.Builder()
        .register(KryoNamespaces.API)
        .register(GroupKey.class)
        .register(DefaultGroupKey.class)
        .register(OfdpaNextGroup.class)
        .register(byte[].class)
        .register(ArrayDeque.class)
        .build()
Definition at line 164 of file OFDPA2Pipeline.java.
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.BRIDGING_TABLE = 50 static protected
Definition at line 128 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processTmacTable().
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.DEFAULT_PRIORITY = 0x8000 static protected
Definition at line 134 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processVlanIdFilter(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processVlanIdFilter().
DeviceId org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId protected
Definition at line 159 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.init(), org.onosproject.driver.pipeline.OFDPA2Pipeline.next(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processAclTable(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processIpTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processMplsTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processPortTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processTmacTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processVlanIdFilter(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processVlanIdFilter().
DeviceService org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceService protected
Definition at line 162 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.init(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processVlanIdFilter(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processVlanIdFilter().
ApplicationId org.onosproject.driver.pipeline.OFDPA2Pipeline.driverId protected
Definition at line 160 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.init(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processAclTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processIpTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processMplsTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processPortTable(), and org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processTmacTable().
FlowObjectiveStore org.onosproject.driver.pipeline.OFDPA2Pipeline.flowObjectiveStore protected
Definition at line 158 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.init().
FlowRuleService org.onosproject.driver.pipeline.OFDPA2Pipeline.flowRuleService protected
Definition at line 155 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.init().
GroupService org.onosproject.driver.pipeline.OFDPA2Pipeline.groupService protected
Definition at line 157 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.init().
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.LOWEST_PRIORITY = 0x0 static protected
Definition at line 135 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processAclTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processIpTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processMplsTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processPortTable(), and org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processTmacTable().
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.MAC_LEARNING_TABLE = 254 static protected
Definition at line 130 of file OFDPA2Pipeline.java.
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.MPLS_TABLE_0 = 23 static protected
Definition at line 126 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), and org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processMplsTable().
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.MPLS_TABLE_1 = 24 static protected
Definition at line 127 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processMplsTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.MULTICAST_ROUTING_TABLE = 40 static protected
Definition at line 125 of file OFDPA2Pipeline.java.
final long org.onosproject.driver.pipeline.OFDPA2Pipeline.OFPP_MAX = 0xffffff00L static protected
Definition at line 131 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processVlanIdFilter(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processVlanIdFilter().
PacketService org.onosproject.driver.pipeline.OFDPA2Pipeline.packetService protected
Definition at line 161 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.init().
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.PORT_TABLE = 0 static protected
Definition at line 121 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processPortTable().
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.TMAC_TABLE = 20 static protected
Definition at line 123 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processTmacTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processVlanIdFilter(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processVlanIdFilter().
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.UNICAST_ROUTING_TABLE = 30 static protected
Definition at line 124 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processIpTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
final int org.onosproject.driver.pipeline.OFDPA2Pipeline.VLAN_TABLE = 10 static protected
Definition at line 122 of file OFDPA2Pipeline.java.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processPortTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processVlanIdFilter(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processVlanIdFilter().
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/pipeline/OFDPA2Pipeline.java