onos: org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest Class Reference
org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest Class Reference
Unit tests for PortPairManager class.
Public Member Functions
void testCreatePortPair ()
Checks the operation of createPortPair() method.
void testExists ()
Checks the operation of exists() method.
void testGetPortPairCount ()
Checks the operation of getPortPairCount() method.
void testGetPortPairs ()
Checks the operation of getPortPairs() method.
void testGetPortPair ()
Checks the operation of getPortPair() method.
void testUpdatePortPair ()
Checks the operation of updatePortPair() method.
void testRemovePortPair ()
Checks the operation of removePortPair() method.
Detailed Description
Unit tests for PortPairManager class.
Definition at line 33 of file PortPairManagerTest.java.
Member Function Documentation
void org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testCreatePortPair ()
Checks the operation of createPortPair() method.
Definition at line 49 of file PortPairManagerTest.java.
References org.onosproject.vtnrsc.portpair.impl.PortPairManager.createPortPair().
Referenced by org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testExists(), org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testGetPortPair(), org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testGetPortPairCount(), org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testGetPortPairs(), org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testRemovePortPair(), and org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testUpdatePortPair().
void org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testExists ()
Checks the operation of exists() method.
Definition at line 64 of file PortPairManagerTest.java.
References org.onosproject.vtnrsc.portpair.impl.PortPairManager.exists(), and org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testCreatePortPair().
void org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testGetPortPair ()
Checks the operation of getPortPair() method.
Definition at line 93 of file PortPairManagerTest.java.
References org.onosproject.vtnrsc.portpair.impl.PortPairManager.getPortPair(), and org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testCreatePortPair().
void org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testGetPortPairCount ()
Checks the operation of getPortPairCount() method.
Definition at line 73 of file PortPairManagerTest.java.
References org.onosproject.vtnrsc.portpair.impl.PortPairManager.getPortPairCount(), and org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testCreatePortPair().
void org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testGetPortPairs ()
Checks the operation of getPortPairs() method.
Definition at line 82 of file PortPairManagerTest.java.
References org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testCreatePortPair().
void org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testRemovePortPair ()
Checks the operation of removePortPair() method.
Definition at line 122 of file PortPairManagerTest.java.
References org.onosproject.vtnrsc.portpair.impl.PortPairManager.removePortPair(), and org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testCreatePortPair().
void org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testUpdatePortPair ()
Checks the operation of updatePortPair() method.
Definition at line 103 of file PortPairManagerTest.java.
References org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testCreatePortPair(), and org.onosproject.vtnrsc.portpair.impl.PortPairManager.updatePortPair().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/test/java/org/onosproject/vtnrsc/portpair/impl/PortPairManagerTest.java