onos: org.onosproject.net.topology.TopologyEvent Class Reference
org.onosproject.net.topology.TopologyEvent Class Reference
Describes network topology event.
Classes
enum Type
Type of topology events.
Public Member Functions
TopologyEvent (Type type, Topology topology, List< Event > reasons)
Creates an event of a given type and for the specified topology and the current time.
TopologyEvent (Type type, Topology topology, List< Event > reasons, long time)
Creates an event of a given type and for the specified topology and time.
List< Event > reasons ()
Returns the list of events that triggered the topology change.
Detailed Description
Describes network topology event.
Definition at line 26 of file TopologyEvent.java.
Constructor & Destructor Documentation
org.onosproject.net.topology.TopologyEvent.TopologyEvent (Type type, Topology topology, List< Event > reasons)
Creates an event of a given type and for the specified topology and the current time.
Parameters
type topology event type
topology event topology subject
reasons list of events that triggered topology change
Definition at line 48 of file TopologyEvent.java.
References org.onosproject.net.topology.TopologyEvent.reasons().
org.onosproject.net.topology.TopologyEvent.TopologyEvent (Type type, Topology topology, List< Event > reasons, long time)
Creates an event of a given type and for the specified topology and time.
Parameters
type link event type
topology event topology subject
reasons list of events that triggered topology change
time occurrence time
Definition at line 61 of file TopologyEvent.java.
References org.onosproject.net.topology.TopologyEvent.reasons().
Member Function Documentation
List<Event> org.onosproject.net.topology.TopologyEvent.reasons ()
Returns the list of events that triggered the topology change.
Returns
list of events responsible for change in topology; null if initial topology computation
Definition at line 74 of file TopologyEvent.java.
Referenced by org.onosproject.net.topology.TopologyEvent.TopologyEvent().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/topology/TopologyEvent.java