onos: org.onosproject.net.device.impl.BasicDeviceOperator Class Reference
org.onosproject.net.device.impl.BasicDeviceOperator Class Reference
Implementations of merge policies for various sources of device configuration information.
Static Public Member Functions
static DeviceDescription combine (BasicDeviceConfig bdc, DeviceDescription descr)
Generates a DeviceDescription containing fields from a DeviceDescription and a DeviceConfig.
static SparseAnnotations combine (BasicDeviceConfig bdc, SparseAnnotations an)
Generates an annotation from an existing annotation and DeviceConfig.
static DeviceDescription descriptionOf (Device device)
Static Protected Attributes
static final double DEFAULT_COORD = -1.0
Detailed Description
Implementations of merge policies for various sources of device configuration information.
This includes applications, provides, and network configurations.
Definition at line 37 of file BasicDeviceOperator.java.
Member Function Documentation
static DeviceDescription org.onosproject.net.device.impl.BasicDeviceOperator.combine (BasicDeviceConfig bdc, DeviceDescription descr) static
Generates a DeviceDescription containing fields from a DeviceDescription and a DeviceConfig.
Parameters
bdc the device config entity from network config
descr a DeviceDescription
Returns
DeviceDescription based on both sources
Definition at line 53 of file BasicDeviceOperator.java.
References org.onosproject.net.Description.annotations(), org.onosproject.net.device.DeviceDescription.deviceUri(), org.onosproject.net.device.DeviceDescription.hwVersion(), org.onosproject.net.device.DeviceDescription.serialNumber(), and org.onosproject.net.config.basics.BasicDeviceConfig.type().
static SparseAnnotations org.onosproject.net.device.impl.BasicDeviceOperator.combine (BasicDeviceConfig bdc, SparseAnnotations an) static
Generates an annotation from an existing annotation and DeviceConfig.
Parameters
bdc the device config entity from network config
an the annotation
Returns
annotation combining both sources
Definition at line 76 of file BasicDeviceOperator.java.
References org.onosproject.net.device.impl.BasicDeviceOperator.DEFAULT_COORD, org.onosproject.net.config.basics.BasicDeviceConfig.driver(), org.onosproject.net.AnnotationKeys.DRIVER, org.onosproject.net.AnnotationKeys.LATITUDE, org.onosproject.net.AnnotationKeys.LONGITUDE, org.onosproject.net.AnnotationKeys.MANAGEMENT_ADDRESS, org.onosproject.net.config.basics.BasicDeviceConfig.managementAddress(), org.onosproject.net.AnnotationKeys.NAME, org.onosproject.net.AnnotationKeys.OWNER, and org.onosproject.net.AnnotationKeys.RACK_ADDRESS.
static DeviceDescription org.onosproject.net.device.impl.BasicDeviceOperator.descriptionOf (Device device) static
Definition at line 103 of file BasicDeviceOperator.java.
References org.onosproject.net.Device.hwVersion(), org.onosproject.net.Device.id(), org.onosproject.net.Device.serialNumber(), and org.onosproject.net.Device.type().
Member Data Documentation
final double org.onosproject.net.device.impl.BasicDeviceOperator.DEFAULT_COORD = -1.0 static protected
Definition at line 39 of file BasicDeviceOperator.java.
Referenced by org.onosproject.net.device.impl.BasicDeviceOperator.combine().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/device/impl/BasicDeviceOperator.java