onos: org.onlab.packet.ipv6.Routing Class Reference
org.onlab.packet.ipv6.Routing Class Reference
Implements IPv6 routing extension header format.
Public Member Functions
byte getNextHeader ()
Gets the type of next header.
Routing setNextHeader (final byte nextHeader)
Sets the type of next header.
byte getHeaderExtLength ()
Gets the extension length of this header.
Routing setHeaderExtLength (final byte headerExtLength)
Sets the extension length of this header.
byte getRoutingType ()
Gets the routing type of this header.
Routing setRoutingType (final byte routingType)
Sets the routing type of this header.
byte getSegmentsLeft ()
Gets the number of remaining route segments of this header.
Routing setSegmntsLeft (final byte segmentsLeft)
Sets the number of remaining route segments of this header.
byte[] getRoutingData ()
Gets the routing data.
Routing setRoutingData (final byte[] routingData)
Sets the routing data.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer< Routing > deserializer ()
Deserializer function for routing headers.
Static Public Attributes
static final byte FIXED_HEADER_LENGTH = 4
static final byte FIXED_ROUTING_DATA_LENGTH = 4
static final byte LENGTH_UNIT = 8
Protected Attributes
byte nextHeader
byte headerExtLength
byte routingType
byte segmentsLeft
byte[] routingData
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements IPv6 routing extension header format.
(RFC 2460)
Definition at line 35 of file Routing.java.
Member Function Documentation
IPacket org.onlab.packet.ipv6.Routing.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 172 of file Routing.java.
References org.onlab.packet.ipv6.Routing.deserializer(), org.onlab.packet.ipv6.Routing.FIXED_ROUTING_DATA_LENGTH, find-link-in-cluster.length, org.onlab.packet.ipv6.Routing.LENGTH_UNIT, and org.onlab.packet.IPv6.PROTOCOL_DESERIALIZER_MAP.
static Deserializer<Routing> org.onlab.packet.ipv6.Routing.deserializer () static
Deserializer function for routing headers.
Returns
deserializer function
Definition at line 259 of file Routing.java.
References org.onlab.packet.ipv6.Routing.FIXED_HEADER_LENGTH, org.onlab.packet.ipv6.Routing.FIXED_ROUTING_DATA_LENGTH, find-link-in-cluster.length, org.onlab.packet.ipv6.Routing.LENGTH_UNIT, org.onlab.packet.ipv6.Routing.nextHeader, and org.onlab.packet.IPv6.PROTOCOL_DESERIALIZER_MAP.
Referenced by org.onlab.packet.ipv6.Routing.deserialize().
boolean org.onlab.packet.ipv6.Routing.equals (final Object obj)
Definition at line 225 of file Routing.java.
References org.onlab.packet.ipv6.Routing.headerExtLength, org.onlab.packet.ipv6.Routing.nextHeader, org.onlab.packet.ipv6.Routing.routingData, org.onlab.packet.ipv6.Routing.routingType, and org.onlab.packet.ipv6.Routing.segmentsLeft.
Referenced by org.onlab.packet.ipv6.RoutingTest.testEqual().
byte org.onlab.packet.ipv6.Routing.getHeaderExtLength ()
Gets the extension length of this header.
Returns
header length
Definition at line 62 of file Routing.java.
Referenced by org.onlab.packet.ipv6.RoutingTest.testDeserialize().
byte org.onlab.packet.ipv6.Routing.getNextHeader ()
Gets the type of next header.
Returns
next header
Implements org.onlab.packet.ipv6.IExtensionHeader.
Definition at line 47 of file Routing.java.
Referenced by org.onlab.packet.ipv6.RoutingTest.testDeserialize().
byte [] org.onlab.packet.ipv6.Routing.getRoutingData ()
Gets the routing data.
Returns
the routing data
Definition at line 122 of file Routing.java.
Referenced by org.onlab.packet.ipv6.RoutingTest.testDeserialize().
byte org.onlab.packet.ipv6.Routing.getRoutingType ()
Gets the routing type of this header.
Returns
routing type
Definition at line 82 of file Routing.java.
Referenced by org.onlab.packet.ipv6.RoutingTest.testDeserialize().
byte org.onlab.packet.ipv6.Routing.getSegmentsLeft ()
Gets the number of remaining route segments of this header.
Returns
number of remaining route segments
Definition at line 102 of file Routing.java.
Referenced by org.onlab.packet.ipv6.RoutingTest.testDeserialize().
int org.onlab.packet.ipv6.Routing.hashCode ()
Definition at line 206 of file Routing.java.
References org.onlab.packet.ipv6.Routing.routingData.
byte [] org.onlab.packet.ipv6.Routing.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 139 of file Routing.java.
References org.onlab.packet.ipv6.Routing.FIXED_HEADER_LENGTH, find-link-in-cluster.length, org.onlab.packet.BasePacket.parent, org.onlab.packet.BasePacket.payload, and org.onlab.packet.IPv6.PROTOCOL_ROUTING.
Referenced by org.onlab.packet.ipv6.RoutingTest.testSerialize().
Routing org.onlab.packet.ipv6.Routing.setHeaderExtLength (final byte headerExtLength)
Sets the extension length of this header.
Parameters
headerExtLength the header length to set
Returns
this
Definition at line 72 of file Routing.java.
References org.onlab.packet.ipv6.Routing.headerExtLength.
Routing org.onlab.packet.ipv6.Routing.setNextHeader (final byte nextHeader)
Sets the type of next header.
Parameters
nextHeader the next header to set
Returns
this
Implements org.onlab.packet.ipv6.IExtensionHeader.
Definition at line 52 of file Routing.java.
References org.onlab.packet.ipv6.Routing.nextHeader.
Routing org.onlab.packet.ipv6.Routing.setRoutingData (final byte[] routingData)
Sets the routing data.
Parameters
routingData the routing data to set
Returns
this
Definition at line 132 of file Routing.java.
References find-link-in-cluster.length, and org.onlab.packet.ipv6.Routing.routingData.
Routing org.onlab.packet.ipv6.Routing.setRoutingType (final byte routingType)
Sets the routing type of this header.
Parameters
routingType the routing type to set
Returns
this
Definition at line 92 of file Routing.java.
References org.onlab.packet.ipv6.Routing.routingType.
Routing org.onlab.packet.ipv6.Routing.setSegmntsLeft (final byte segmentsLeft)
Sets the number of remaining route segments of this header.
Parameters
segmentsLeft the number of remaining route segments to set
Returns
this
Definition at line 112 of file Routing.java.
References org.onlab.packet.ipv6.Routing.segmentsLeft.
Member Data Documentation
final byte org.onlab.packet.ipv6.Routing.FIXED_HEADER_LENGTH = 4 static
Definition at line 36 of file Routing.java.
Referenced by org.onlab.packet.ipv6.Routing.deserializer(), and org.onlab.packet.ipv6.Routing.serialize().
final byte org.onlab.packet.ipv6.Routing.FIXED_ROUTING_DATA_LENGTH = 4 static
Definition at line 37 of file Routing.java.
Referenced by org.onlab.packet.ipv6.Routing.deserialize(), and org.onlab.packet.ipv6.Routing.deserializer().
byte org.onlab.packet.ipv6.Routing.headerExtLength protected
Definition at line 41 of file Routing.java.
Referenced by org.onlab.packet.ipv6.Routing.equals(), and org.onlab.packet.ipv6.Routing.setHeaderExtLength().
final byte org.onlab.packet.ipv6.Routing.LENGTH_UNIT = 8 static
Definition at line 38 of file Routing.java.
Referenced by org.onlab.packet.ipv6.Routing.deserialize(), and org.onlab.packet.ipv6.Routing.deserializer().
byte org.onlab.packet.ipv6.Routing.nextHeader protected
Definition at line 40 of file Routing.java.
Referenced by org.onlab.packet.ipv6.Routing.deserializer(), org.onlab.packet.ipv6.Routing.equals(), and org.onlab.packet.ipv6.Routing.setNextHeader().
byte [] org.onlab.packet.ipv6.Routing.routingData protected
Definition at line 44 of file Routing.java.
Referenced by org.onlab.packet.ipv6.Routing.equals(), org.onlab.packet.ipv6.Routing.hashCode(), and org.onlab.packet.ipv6.Routing.setRoutingData().
byte org.onlab.packet.ipv6.Routing.routingType protected
Definition at line 42 of file Routing.java.
Referenced by org.onlab.packet.ipv6.Routing.equals(), and org.onlab.packet.ipv6.Routing.setRoutingType().
byte org.onlab.packet.ipv6.Routing.segmentsLeft protected
Definition at line 43 of file Routing.java.
Referenced by org.onlab.packet.ipv6.Routing.equals(), and org.onlab.packet.ipv6.Routing.setSegmntsLeft().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ipv6/Routing.java