onos: org.onosproject.net.host.impl.BasicHostOperator Class Reference
org.onosproject.net.host.impl.BasicHostOperator Class Reference
Implementations of merge policies for various sources of host configuration information.
Static Public Member Functions
static HostDescription combine (BasicHostConfig cfg, HostDescription descr)
Generates a HostDescription containing fields from a HostDescription and a HostConfig.
static SparseAnnotations combine (BasicHostConfig cfg, SparseAnnotations an)
Generates an annotation from an existing annotation and HostConfig.
Static Protected Attributes
static final double DEFAULT_COORD = -1.0
Detailed Description
Implementations of merge policies for various sources of host configuration information.
This includes applications, provides, and network configurations.
Definition at line 33 of file BasicHostOperator.java.
Member Function Documentation
static HostDescription org.onosproject.net.host.impl.BasicHostOperator.combine (BasicHostConfig cfg, HostDescription descr) static
Generates a HostDescription containing fields from a HostDescription and a HostConfig.
Parameters
cfg the host config entity from network config
descr a HostDescription
Returns
HostDescription based on both sources
Definition at line 49 of file BasicHostOperator.java.
References org.onosproject.net.Description.annotations(), org.onosproject.net.host.HostDescription.hwAddress(), and org.onosproject.net.host.HostDescription.location().
static SparseAnnotations org.onosproject.net.host.impl.BasicHostOperator.combine (BasicHostConfig cfg, SparseAnnotations an) static
Generates an annotation from an existing annotation and HostConfig.
Parameters
cfg the device config entity from network config
an the annotation
Returns
annotation combining both sources
Definition at line 65 of file BasicHostOperator.java.
References org.onosproject.net.host.impl.BasicHostOperator.DEFAULT_COORD, org.onosproject.net.AnnotationKeys.LATITUDE, org.onosproject.net.AnnotationKeys.LONGITUDE, org.onosproject.net.AnnotationKeys.NAME, org.onosproject.net.AnnotationKeys.OWNER, and org.onosproject.net.AnnotationKeys.RACK_ADDRESS.
Member Data Documentation
final double org.onosproject.net.host.impl.BasicHostOperator.DEFAULT_COORD = -1.0 static protected
Definition at line 35 of file BasicHostOperator.java.
Referenced by org.onosproject.net.host.impl.BasicHostOperator.combine().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/host/impl/BasicHostOperator.java