onos: org.onosproject.net.intent.impl.IntentAccumulator Class Reference
org.onosproject.net.intent.impl.IntentAccumulator Class Reference
An accumulator for building batches of intent operations.
Public Member Functions
void processItems (List< IntentData > items)
boolean isReady ()
void ready ()
Protected Member Functions
IntentAccumulator (IntentBatchDelegate delegate)
Creates an intent operation accumulator.
Detailed Description
An accumulator for building batches of intent operations.
Only one batch should be in process per instance at a time.
Definition at line 33 of file IntentAccumulator.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.impl.IntentAccumulator.IntentAccumulator (IntentBatchDelegate delegate) protected
Creates an intent operation accumulator.
Parameters
delegate the intent batch delegate
Definition at line 52 of file IntentAccumulator.java.
References org.onosproject.net.intent.impl.IntentAccumulator.ready().
Member Function Documentation
boolean org.onosproject.net.intent.impl.IntentAccumulator.isReady ()
Definition at line 75 of file IntentAccumulator.java.
References org.onosproject.net.intent.impl.IntentAccumulator.ready().
void org.onosproject.net.intent.impl.IntentAccumulator.processItems (List< IntentData > items)
Definition at line 60 of file IntentAccumulator.java.
References org.onosproject.net.intent.impl.IntentAccumulator.ready().
void org.onosproject.net.intent.impl.IntentAccumulator.ready ()
Definition at line 79 of file IntentAccumulator.java.
Referenced by org.onosproject.net.intent.impl.IntentAccumulator.IntentAccumulator(), org.onosproject.net.intent.impl.IntentAccumulator.isReady(), and org.onosproject.net.intent.impl.IntentAccumulator.processItems().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/intent/impl/IntentAccumulator.java