onos: org.onosproject.incubator.net.tunnel.IpTunnelEndPoint Class Reference
org.onosproject.incubator.net.tunnel.IpTunnelEndPoint Class Reference
Represent for a tunnel point using ip address.
Public Member Functions
IpAddress ip ()
Returns IP address.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static IpTunnelEndPoint ipTunnelPoint (IpAddress ip)
Create a IP tunnel end point.
Detailed Description
Represent for a tunnel point using ip address.
Definition at line 30 of file IpTunnelEndPoint.java.
Member Function Documentation
boolean org.onosproject.incubator.net.tunnel.IpTunnelEndPoint.equals (Object obj)
Definition at line 65 of file IpTunnelEndPoint.java.
int org.onosproject.incubator.net.tunnel.IpTunnelEndPoint.hashCode ()
Definition at line 60 of file IpTunnelEndPoint.java.
References org.onosproject.incubator.net.tunnel.IpTunnelEndPoint.ip().
IpAddress org.onosproject.incubator.net.tunnel.IpTunnelEndPoint.ip ()
Returns IP address.
Returns
IP address
Definition at line 55 of file IpTunnelEndPoint.java.
Referenced by org.onosproject.incubator.net.tunnel.IpTunnelEndPoint.hashCode(), onos.ONOS.start(), and onos.ONOS.updateHazelcast().
static IpTunnelEndPoint org.onosproject.incubator.net.tunnel.IpTunnelEndPoint.ipTunnelPoint (IpAddress ip) static
Create a IP tunnel end point.
Parameters
ip IP address
Returns
IpTunnelEndPoint
Definition at line 47 of file IpTunnelEndPoint.java.
String org.onosproject.incubator.net.tunnel.IpTunnelEndPoint.toString ()
Definition at line 77 of file IpTunnelEndPoint.java.
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/tunnel/IpTunnelEndPoint.java