onos: org.onosproject.net.DefaultPath Class Reference
org.onosproject.net.DefaultPath Class Reference
Default implementation of a network path.
Public Member Functions
DefaultPath (ProviderId providerId, List< Link > links, double cost, Annotations...annotations)
Creates a path from the specified source and destination using the supplied list of links.
List< Link > links ()
Returns sequence of links comprising the path.
double cost ()
Returns the path cost as a unit-less value.
String toString ()
int hashCode ()
boolean equals (Object obj)
Public Member Functions inherited from org.onosproject.net.DefaultLink
DefaultLink (ProviderId providerId, ConnectPoint src, ConnectPoint dst, Type type, Annotations...annotations)
Creates an active infrastructure link using the supplied information.
DefaultLink (ProviderId providerId, ConnectPoint src, ConnectPoint dst, Type type, State state, boolean isDurable, Annotations...annotations)
Creates an infrastructure link using the supplied information.
ConnectPoint src ()
Returns the link source connection point.
ConnectPoint dst ()
Returns the link destination connection point.
Type type ()
Returns the link type.
State state ()
Returns the link state.
boolean isDurable ()
Indicates if the link is to be considered durable.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel ()
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel (ProviderId providerId, Annotations...annotations)
Creates a model entity attributed to the specified provider and optionally annotated.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of a network path.
Definition at line 31 of file DefaultPath.java.
Constructor & Destructor Documentation
org.onosproject.net.DefaultPath.DefaultPath (ProviderId providerId, List< Link > links, double cost, Annotations... annotations)
Creates a path from the specified source and destination using the supplied list of links.
Parameters
providerId provider identity
links contiguous links that comprise the path
cost unit-less path cost
annotations optional key/value annotations
Definition at line 45 of file DefaultPath.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultPath.cost(), org.onosproject.net.Link.Type.INDIRECT, and org.onosproject.net.DefaultPath.links().
Referenced by org.onosproject.net.DefaultPath.equals().
Member Function Documentation
double org.onosproject.net.DefaultPath.cost ()
Returns the path cost as a unit-less value.
Returns
unit-less path cost
Implements org.onosproject.net.Path.
Definition at line 58 of file DefaultPath.java.
Referenced by org.onosproject.net.DefaultPath.DefaultPath(), and org.onosproject.net.DefaultPath.toString().
boolean org.onosproject.net.DefaultPath.equals (Object obj)
Definition at line 95 of file DefaultPath.java.
References org.onosproject.net.DefaultPath.DefaultPath().
int org.onosproject.net.DefaultPath.hashCode ()
Definition at line 90 of file DefaultPath.java.
List<Link> org.onosproject.net.DefaultPath.links ()
Returns sequence of links comprising the path.
Returns
list of links
Implements org.onosproject.net.Path.
Definition at line 53 of file DefaultPath.java.
Referenced by org.onosproject.net.DefaultPath.DefaultPath().
String org.onosproject.net.DefaultPath.toString ()
Definition at line 77 of file DefaultPath.java.
References org.onosproject.net.DefaultPath.cost(), org.onosproject.net.DefaultLink.dst(), org.onosproject.net.DefaultLink.isDurable(), org.onosproject.net.DefaultLink.src(), org.onosproject.net.DefaultLink.state(), and org.onosproject.net.DefaultLink.type().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/DefaultPath.java