onos: org.onlab.packet.ipv6.EncapSecurityPayload Class Reference
org.onlab.packet.ipv6.EncapSecurityPayload Class Reference
Implements IPv6 Encapsulating Security Payload (ESP) extension header format.
Public Member Functions
int getSecurityParamIndex ()
Gets the security parameter index of this header.
EncapSecurityPayload setSecurityParamIndex (final int securityParamIndex)
Sets the security parameter index of this header.
int getSequence ()
Gets the sequence number of this header.
EncapSecurityPayload setSequence (final int sequence)
Sets the sequence number of this header.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer
< EncapSecurityPayload > deserializer ()
Deserializer function for encapsulated security payload headers.
Static Public Attributes
static final byte HEADER_LENGTH = 8
Protected Attributes
int securityParamIndex
int sequence
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements IPv6 Encapsulating Security Payload (ESP) extension header format.
(RFC 4303)
Definition at line 33 of file EncapSecurityPayload.java.
Member Function Documentation
IPacket org.onlab.packet.ipv6.EncapSecurityPayload.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 113 of file EncapSecurityPayload.java.
References find-link-in-cluster.length.
Referenced by org.onlab.packet.ipv6.EncapSecurityPayload.deserializer().
static Deserializer<EncapSecurityPayload> org.onlab.packet.ipv6.EncapSecurityPayload.deserializer () static
Deserializer function for encapsulated security payload headers.
Returns
deserializer function
Definition at line 171 of file EncapSecurityPayload.java.
References org.onlab.packet.ipv6.EncapSecurityPayload.deserialize(), org.onlab.packet.ipv6.EncapSecurityPayload.HEADER_LENGTH, and find-link-in-cluster.length.
boolean org.onlab.packet.ipv6.EncapSecurityPayload.equals (final Object obj)
Definition at line 146 of file EncapSecurityPayload.java.
References org.onlab.packet.ipv6.EncapSecurityPayload.securityParamIndex, and org.onlab.packet.ipv6.EncapSecurityPayload.sequence.
Referenced by org.onlab.packet.ipv6.EncapSecurityPayloadTest.testEqual().
int org.onlab.packet.ipv6.EncapSecurityPayload.getSecurityParamIndex ()
Gets the security parameter index of this header.
Returns
the security parameter index
Definition at line 48 of file EncapSecurityPayload.java.
Referenced by org.onlab.packet.ipv6.EncapSecurityPayloadTest.testDeserialize().
int org.onlab.packet.ipv6.EncapSecurityPayload.getSequence ()
Gets the sequence number of this header.
Returns
the sequence number
Definition at line 68 of file EncapSecurityPayload.java.
Referenced by org.onlab.packet.ipv6.EncapSecurityPayloadTest.testDeserialize().
int org.onlab.packet.ipv6.EncapSecurityPayload.hashCode ()
Definition at line 132 of file EncapSecurityPayload.java.
byte [] org.onlab.packet.ipv6.EncapSecurityPayload.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 84 of file EncapSecurityPayload.java.
References org.onlab.packet.ipv6.EncapSecurityPayload.HEADER_LENGTH, find-link-in-cluster.length, org.onlab.packet.BasePacket.parent, org.onlab.packet.BasePacket.payload, and org.onlab.packet.IPv6.PROTOCOL_ESP.
Referenced by org.onlab.packet.ipv6.EncapSecurityPayloadTest.testSerialize().
EncapSecurityPayload org.onlab.packet.ipv6.EncapSecurityPayload.setSecurityParamIndex (final int securityParamIndex)
Sets the security parameter index of this header.
Parameters
securityParamIndex the security parameter index to set
Returns
this
Definition at line 58 of file EncapSecurityPayload.java.
References org.onlab.packet.ipv6.EncapSecurityPayload.securityParamIndex.
EncapSecurityPayload org.onlab.packet.ipv6.EncapSecurityPayload.setSequence (final int sequence)
Sets the sequence number of this header.
Parameters
sequence the sequence number to set
Returns
this
Definition at line 78 of file EncapSecurityPayload.java.
References org.onlab.packet.ipv6.EncapSecurityPayload.sequence.
Member Data Documentation
final byte org.onlab.packet.ipv6.EncapSecurityPayload.HEADER_LENGTH = 8 static
Definition at line 34 of file EncapSecurityPayload.java.
Referenced by org.onlab.packet.ipv6.EncapSecurityPayload.deserializer(), and org.onlab.packet.ipv6.EncapSecurityPayload.serialize().
int org.onlab.packet.ipv6.EncapSecurityPayload.securityParamIndex protected
Definition at line 36 of file EncapSecurityPayload.java.
Referenced by org.onlab.packet.ipv6.EncapSecurityPayload.equals(), and org.onlab.packet.ipv6.EncapSecurityPayload.setSecurityParamIndex().
int org.onlab.packet.ipv6.EncapSecurityPayload.sequence protected
Definition at line 37 of file EncapSecurityPayload.java.
Referenced by org.onlab.packet.ipv6.EncapSecurityPayload.equals(), and org.onlab.packet.ipv6.EncapSecurityPayload.setSequence().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ipv6/EncapSecurityPayload.java