onos: org.onosproject.ovsdb.rfc.schema.DatabaseSchema Class Reference
org.onosproject.ovsdb.rfc.schema.DatabaseSchema Class Reference
A schema for the database represented by database-schema, which consists of a set of tables.
Public Member Functions
DatabaseSchema (String name, String version, Map< String, TableSchema > tableSchemas)
Constructs a DatabaseSchema object.
String name ()
Returns the name of database.
String version ()
Returns the version of database.
Map< String, TableSchema > tableSchemas ()
Returns a map of TableSchema.
Set< String > getTableNames ()
Returns a set of table name.
boolean hasTable (String tableName)
Determine whether contain the table.
TableSchema getTableSchema (String tableName)
Returns the TableSchema whose name is the tableName.
void generateInitializationColumns ()
generate initialization columns in each table namely _uuid and _version.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
A schema for the database represented by database-schema, which consists of a set of tables.
Definition at line 29 of file DatabaseSchema.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.schema.DatabaseSchema.DatabaseSchema (String name, String version, Map< String, TableSchema > tableSchemas)
Constructs a DatabaseSchema object.
Parameters
name the name of database
version the version of database
tableSchemas a map of TableSchema
Definition at line 41 of file DatabaseSchema.java.
References org.onosproject.ovsdb.rfc.schema.DatabaseSchema.name(), org.onosproject.ovsdb.rfc.schema.DatabaseSchema.tableSchemas(), and org.onosproject.ovsdb.rfc.schema.DatabaseSchema.version().
Referenced by org.onosproject.ovsdb.rfc.schema.DatabaseSchema.equals().
Member Function Documentation
boolean org.onosproject.ovsdb.rfc.schema.DatabaseSchema.equals (Object obj)
Definition at line 117 of file DatabaseSchema.java.
References org.onosproject.ovsdb.rfc.schema.DatabaseSchema.DatabaseSchema(), and create-flow.name.
void org.onosproject.ovsdb.rfc.schema.DatabaseSchema.generateInitializationColumns ()
generate initialization columns in each table namely _uuid and _version.
Definition at line 105 of file DatabaseSchema.java.
References org.onosproject.ovsdb.rfc.schema.DatabaseSchema.tableSchemas().
Set<String> org.onosproject.ovsdb.rfc.schema.DatabaseSchema.getTableNames ()
Returns a set of table name.
Returns
a set of table name
Definition at line 79 of file DatabaseSchema.java.
TableSchema org.onosproject.ovsdb.rfc.schema.DatabaseSchema.getTableSchema (String tableName)
Returns the TableSchema whose name is the tableName.
Parameters
tableName table name
Returns
TableSchema
Definition at line 97 of file DatabaseSchema.java.
int org.onosproject.ovsdb.rfc.schema.DatabaseSchema.hashCode ()
Definition at line 112 of file DatabaseSchema.java.
References org.onosproject.ovsdb.rfc.schema.DatabaseSchema.name(), org.onosproject.ovsdb.rfc.schema.DatabaseSchema.tableSchemas(), and org.onosproject.ovsdb.rfc.schema.DatabaseSchema.version().
boolean org.onosproject.ovsdb.rfc.schema.DatabaseSchema.hasTable (String tableName)
Determine whether contain the table.
Parameters
tableName table name
Returns
boolean
Definition at line 88 of file DatabaseSchema.java.
String org.onosproject.ovsdb.rfc.schema.DatabaseSchema.name ()
Returns the name of database.
Returns
the name of database
Definition at line 55 of file DatabaseSchema.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.ovsdb.rfc.schema.DatabaseSchema.DatabaseSchema(), org.onosproject.ovsdb.rfc.schema.DatabaseSchema.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.ovsdb.rfc.schema.DatabaseSchema.toString().
Map<String, TableSchema> org.onosproject.ovsdb.rfc.schema.DatabaseSchema.tableSchemas ()
Returns a map of TableSchema.
Returns
a map of TableSchema
Definition at line 71 of file DatabaseSchema.java.
Referenced by org.onosproject.ovsdb.rfc.schema.DatabaseSchema.DatabaseSchema(), org.onosproject.ovsdb.rfc.schema.DatabaseSchema.generateInitializationColumns(), org.onosproject.ovsdb.rfc.schema.DatabaseSchema.hashCode(), and org.onosproject.ovsdb.rfc.schema.DatabaseSchema.toString().
String org.onosproject.ovsdb.rfc.schema.DatabaseSchema.toString ()
Definition at line 131 of file DatabaseSchema.java.
References org.onosproject.ovsdb.rfc.schema.DatabaseSchema.name(), org.onosproject.ovsdb.rfc.schema.DatabaseSchema.tableSchemas(), and org.onosproject.ovsdb.rfc.schema.DatabaseSchema.version().
String org.onosproject.ovsdb.rfc.schema.DatabaseSchema.version ()
Returns the version of database.
Returns
the version of database
Definition at line 63 of file DatabaseSchema.java.
Referenced by org.onosproject.ovsdb.rfc.schema.DatabaseSchema.DatabaseSchema(), org.onosproject.ovsdb.rfc.schema.DatabaseSchema.hashCode(), and org.onosproject.ovsdb.rfc.schema.DatabaseSchema.toString().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/schema/DatabaseSchema.java