onos: org.onosproject.incubator.net.tunnel.DomainTunnelId Class Reference
org.onosproject.incubator.net.tunnel.DomainTunnelId Class Reference
A wrapper class for a long used to identify domain level tunnels.
Public Member Functions
DomainTunnelId (long value)
Constructs the Domain ID corresponding to a given long value.
long id ()
Returns the backing value of this domain ID.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static DomainTunnelId valueOf (long value)
Creates a tunnel identifier from the specified tunnel.
static DomainTunnelId valueOf (String value)
Creates a tunnel identifier from the specified tunnel.
Protected Member Functions
DomainTunnelId ()
Constructor for serializer.
Detailed Description
A wrapper class for a long used to identify domain level tunnels.
Definition at line 22 of file DomainTunnelId.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.tunnel.DomainTunnelId.DomainTunnelId () protected
Constructor for serializer.
Definition at line 49 of file DomainTunnelId.java.
Referenced by org.onosproject.incubator.net.tunnel.DomainTunnelId.equals(), and org.onosproject.incubator.net.tunnel.DomainTunnelId.valueOf().
org.onosproject.incubator.net.tunnel.DomainTunnelId.DomainTunnelId (long value)
Constructs the Domain ID corresponding to a given long value.
Parameters
value the underlying value of this domain ID
Definition at line 58 of file DomainTunnelId.java.
Member Function Documentation
boolean org.onosproject.incubator.net.tunnel.DomainTunnelId.equals (Object obj)
Definition at line 77 of file DomainTunnelId.java.
References org.onosproject.incubator.net.tunnel.DomainTunnelId.DomainTunnelId().
int org.onosproject.incubator.net.tunnel.DomainTunnelId.hashCode ()
Definition at line 72 of file DomainTunnelId.java.
long org.onosproject.incubator.net.tunnel.DomainTunnelId.id ()
Returns the backing value of this domain ID.
Returns
the long value
Definition at line 67 of file DomainTunnelId.java.
String org.onosproject.incubator.net.tunnel.DomainTunnelId.toString ()
Definition at line 89 of file DomainTunnelId.java.
static DomainTunnelId org.onosproject.incubator.net.tunnel.DomainTunnelId.valueOf (long value) static
Creates a tunnel identifier from the specified tunnel.
Parameters
value long value
Returns
domain tunnel identifier
Definition at line 32 of file DomainTunnelId.java.
References org.onosproject.incubator.net.tunnel.DomainTunnelId.DomainTunnelId().
static DomainTunnelId org.onosproject.incubator.net.tunnel.DomainTunnelId.valueOf (String value) static
Creates a tunnel identifier from the specified tunnel.
Parameters
value long value as a string
Returns
domain tunnel identifier
Definition at line 42 of file DomainTunnelId.java.
References org.onosproject.incubator.net.tunnel.DomainTunnelId.DomainTunnelId().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/tunnel/DomainTunnelId.java