onos: org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv Class Reference
org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv Class Reference
Provides Remote TE Node Descriptors TLV.
Public Member Functions
RemoteTENodeDescriptorsTlv (LinkedList< PcepValueType > llRemoteTENodeDescriptorSubTLVs)
Constructor to initialize llRemoteTENodeDescriptorSubTLVs.
LinkedList< PcepValueType > getllRemoteTENodeDescriptorSubTLVs ()
Returns Remote TE Node Descriptor Sub TLVs.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static RemoteTENodeDescriptorsTlv of (final LinkedList< PcepValueType > llRemoteTENodeDescriptorSubTLVs)
Returns object of Remote TE Node Descriptors TLV.
static PcepValueType read (ChannelBuffer c, short length) throws PcepParseException
Reads channel buffer and returns object of Remote TE Node Descriptors TLV.
Public Attributes
short hLength
Static Public Attributes
static final short TYPE = 1003
static final int TLV_HEADER_LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(RemoteTENodeDescriptorsTlv.class)
Detailed Description
Provides Remote TE Node Descriptors TLV.
Definition at line 34 of file RemoteTENodeDescriptorsTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.RemoteTENodeDescriptorsTlv (LinkedList< PcepValueType > llRemoteTENodeDescriptorSubTLVs)
Constructor to initialize llRemoteTENodeDescriptorSubTLVs.
Parameters
llRemoteTENodeDescriptorSubTLVs LinkedList of PcepValueType
Definition at line 64 of file RemoteTENodeDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.equals(), org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.of(), and org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.equals (Object obj)
Definition at line 108 of file RemoteTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.RemoteTENodeDescriptorsTlv().
short org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 98 of file RemoteTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.hLength.
LinkedList<PcepValueType> org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.getllRemoteTENodeDescriptorSubTLVs ()
Returns Remote TE Node Descriptor Sub TLVs.
Returns
llRemoteTENodeDescriptorSubTLVs
Definition at line 83 of file RemoteTENodeDescriptorsTlv.java.
short org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 93 of file RemoteTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 88 of file RemoteTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.hashCode ()
Definition at line 103 of file RemoteTENodeDescriptorsTlv.java.
static RemoteTENodeDescriptorsTlv org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.of (final LinkedList< PcepValueType > llRemoteTENodeDescriptorSubTLVs) static
Returns object of Remote TE Node Descriptors TLV.
Parameters
llRemoteTENodeDescriptorSubTLVs LinkedList of PcepValueType
Returns
object of RemoteTENodeDescriptorsTLV
Definition at line 74 of file RemoteTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.RemoteTENodeDescriptorsTlv().
static PcepValueType org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.read (ChannelBuffer c, short length) throws PcepParseException static
Reads channel buffer and returns object of Remote TE Node Descriptors TLV.
Parameters
c input channel buffer
length length of buffer
Returns
object of RemoteTENodeDescriptorsTLV
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 188 of file RemoteTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.hLength, find-link-in-cluster.length, org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.RemoteTENodeDescriptorsTlv(), and org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.TLV_HEADER_LENGTH.
String org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.toString ()
Definition at line 243 of file RemoteTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.hLength, and org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.TYPE.
int org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 144 of file RemoteTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.hLength, org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.TLV_HEADER_LENGTH, and org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.TYPE.
Member Data Documentation
short org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.hLength
Definition at line 53 of file RemoteTENodeDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.getLength(), org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.read(), org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.toString(), and org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.write().
final Logger org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.log = LoggerFactory.getLogger(RemoteTENodeDescriptorsTlv.class) static protected
Definition at line 50 of file RemoteTENodeDescriptorsTlv.java.
final int org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.TLV_HEADER_LENGTH = 4 static
Definition at line 55 of file RemoteTENodeDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.read(), and org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.write().
final short org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.TYPE = 1003 static
Definition at line 52 of file RemoteTENodeDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.getType(), org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.toString(), and org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/RemoteTENodeDescriptorsTlv.java