onos: org.onosproject.cord.gui.CoreModelCacheTest Class Reference
org.onosproject.cord.gui.CoreModelCacheTest Class Reference
Unit tests for CordModelCache.
Public Member Functions
void setUp ()
void basic ()
void basicBundleJson ()
void chooseFamilyBundle ()
void familyBundleJson ()
void checkUsers ()
void usersBasicJson ()
void usersFamilyJson ()
void setNewLevel ()
Detailed Description
Unit tests for CordModelCache.
Definition at line 39 of file CoreModelCacheTest.java.
Member Function Documentation
void org.onosproject.cord.gui.CoreModelCacheTest.basic ()
Definition at line 49 of file CoreModelCacheTest.java.
References org.onosproject.cord.gui.model.BundleFactory.BASIC_BUNDLE, and org.onosproject.cord.gui.CordModelCache.getCurrentBundle().
void org.onosproject.cord.gui.CoreModelCacheTest.basicBundleJson ()
Definition at line 55 of file CoreModelCacheTest.java.
References create-flow.node.
void org.onosproject.cord.gui.CoreModelCacheTest.checkUsers ()
Definition at line 79 of file CoreModelCacheTest.java.
void org.onosproject.cord.gui.CoreModelCacheTest.chooseFamilyBundle ()
Definition at line 63 of file CoreModelCacheTest.java.
References org.onosproject.cord.gui.model.BundleFactory.FAMILY_BUNDLE, and org.onosproject.cord.gui.CordModelCache.getCurrentBundle().
void org.onosproject.cord.gui.CoreModelCacheTest.familyBundleJson ()
Definition at line 70 of file CoreModelCacheTest.java.
References create-flow.node.
void org.onosproject.cord.gui.CoreModelCacheTest.setNewLevel ()
Definition at line 100 of file CoreModelCacheTest.java.
References org.onosproject.cord.gui.CordModelCache.jsonUsers(), and create-flow.node.
void org.onosproject.cord.gui.CoreModelCacheTest.setUp ()
Definition at line 44 of file CoreModelCacheTest.java.
void org.onosproject.cord.gui.CoreModelCacheTest.usersBasicJson ()
Definition at line 85 of file CoreModelCacheTest.java.
void org.onosproject.cord.gui.CoreModelCacheTest.usersFamilyJson ()
Definition at line 92 of file CoreModelCacheTest.java.
The documentation for this class was generated from the following file:
apps/demo/cord-gui/src/test/org/onosproject/cord/gui/CoreModelCacheTest.java