onos: org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv Class Reference
org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv Class Reference
Provides MultiProtocolExtnCapabilityTlv.
Public Member Functions
MultiProtocolExtnCapabilityTlv (short afi, byte res, byte safi)
Constructor to initialize variables.
short getAFI ()
Returns afi Address Family Identifiers value.
byte getRes ()
Returns res reserved field value.
byte getSAFI ()
Returns safi Subsequent Address Family Identifier value.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static
MultiProtocolExtnCapabilityTlv of (short afi, byte res, byte safi)
Returns object of MultiProtocolExtnCapabilityTlv.
static BgpValueType read (ChannelBuffer cb)
Reads from channel buffer and returns object of MultiprotocolCapabilityTlv.
Static Public Attributes
static final byte TYPE = 1
static final byte LENGTH = 4
Static Protected Attributes
static final Logger log
Detailed Description
Provides MultiProtocolExtnCapabilityTlv.
Definition at line 28 of file MultiProtocolExtnCapabilityTlv.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.MultiProtocolExtnCapabilityTlv (short afi, byte res, byte safi)
Constructor to initialize variables.
Parameters
afi Address Family Identifiers
res reserved field
safi Subsequent Address Family Identifier
Definition at line 55 of file MultiProtocolExtnCapabilityTlv.java.
Referenced by org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.equals(), org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.of(), and org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.read().
Member Function Documentation
int org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 162 of file MultiProtocolExtnCapabilityTlv.java.
boolean org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.equals (Object obj)
Definition at line 108 of file MultiProtocolExtnCapabilityTlv.java.
References org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.MultiProtocolExtnCapabilityTlv().
short org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.getAFI ()
Returns afi Address Family Identifiers value.
Returns
afi Address Family Identifiers value
Definition at line 77 of file MultiProtocolExtnCapabilityTlv.java.
byte org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.getRes ()
Returns res reserved field value.
Returns
res reserved field value
Definition at line 85 of file MultiProtocolExtnCapabilityTlv.java.
byte org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.getSAFI ()
Returns safi Subsequent Address Family Identifier value.
Returns
safi Subsequent Address Family Identifier value
Definition at line 93 of file MultiProtocolExtnCapabilityTlv.java.
short org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 98 of file MultiProtocolExtnCapabilityTlv.java.
References org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.TYPE.
int org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.hashCode ()
Definition at line 103 of file MultiProtocolExtnCapabilityTlv.java.
static MultiProtocolExtnCapabilityTlv org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.of (short afi, byte res, byte safi) static
Returns object of MultiProtocolExtnCapabilityTlv.
Parameters
afi Address Family Identifiers
res reserved field
safi Subsequent Address Family Identifier
Returns
object of MultiProtocolExtnCapabilityTlv
Definition at line 68 of file MultiProtocolExtnCapabilityTlv.java.
References org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.MultiProtocolExtnCapabilityTlv().
static BgpValueType org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.read (ChannelBuffer cb) static
Reads from channel buffer and returns object of MultiprotocolCapabilityTlv.
Parameters
cb of type channel buffer
Returns
object of MultiProtocolExtnCapabilityTlv
Definition at line 144 of file MultiProtocolExtnCapabilityTlv.java.
References org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.MultiProtocolExtnCapabilityTlv().
String org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.toString ()
Definition at line 152 of file MultiProtocolExtnCapabilityTlv.java.
References org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.LENGTH, and org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.TYPE.
int org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 122 of file MultiProtocolExtnCapabilityTlv.java.
References org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.LENGTH, and org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.TYPE.
Member Data Documentation
final byte org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.LENGTH = 4 static
Definition at line 43 of file MultiProtocolExtnCapabilityTlv.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpOpenMsgVer4.parseCapabilityTlv(), org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.toString(), and org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.write().
final Logger org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.log static protected
Initial value:
= LoggerFactory
            .getLogger(MultiProtocolExtnCapabilityTlv.class)
Definition at line 39 of file MultiProtocolExtnCapabilityTlv.java.
final byte org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.TYPE = 1 static
Definition at line 42 of file MultiProtocolExtnCapabilityTlv.java.
Referenced by org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.getType(), org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.toString(), and org.onosproject.bgpio.types.MultiProtocolExtnCapabilityTlv.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/MultiProtocolExtnCapabilityTlv.java