onos: org.onosproject.store.trivial.SimpleLinkStore Class Reference
org.onosproject.store.trivial.SimpleLinkStore Class Reference
Manages inventory of infrastructure links using trivial in-memory structures implementation.
Public Member Functions
void activate ()
void deactivate ()
int getLinkCount ()
Returns the number of links in the store.
Iterable< Link > getLinks ()
Returns an iterable collection of all links in the inventory.
Set< Link > getDeviceEgressLinks (DeviceId deviceId)
Returns all links egressing from the specified device.
Set< Link > getDeviceIngressLinks (DeviceId deviceId)
Returns all links ingressing from the specified device.
Link getLink (ConnectPoint src, ConnectPoint dst)
Returns the link between the two end-points.
Set< Link > getEgressLinks (ConnectPoint src)
Returns all links egressing from the specified connection point.
Set< Link > getIngressLinks (ConnectPoint dst)
Returns all links ingressing to the specified connection point.
LinkEvent createOrUpdateLink (ProviderId providerId, LinkDescription linkDescription)
Creates a new link, or updates an existing one, based on the given information.
LinkEvent removeOrDownLink (ConnectPoint src, ConnectPoint dst)
Removes the link, or marks it as inactive if the link is durable, based on the specified information.
LinkEvent removeLink (ConnectPoint src, ConnectPoint dst)
Removes the link based on the specified information.
Detailed Description
Manages inventory of infrastructure links using trivial in-memory structures implementation.
Definition at line 76 of file SimpleLinkStore.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleLinkStore.activate ()
Definition at line 95 of file SimpleLinkStore.java.
LinkEvent org.onosproject.store.trivial.SimpleLinkStore.createOrUpdateLink (ProviderId providerId, LinkDescription linkDescription)
Creates a new link, or updates an existing one, based on the given information.
Parameters
providerId provider identity
linkDescription link description
Returns
create or update link event, or null if no change resulted
Implements org.onosproject.net.link.LinkStore.
Definition at line 172 of file SimpleLinkStore.java.
References org.onosproject.net.link.LinkDescription.src().
void org.onosproject.store.trivial.SimpleLinkStore.deactivate ()
Definition at line 100 of file SimpleLinkStore.java.
Set<Link> org.onosproject.store.trivial.SimpleLinkStore.getDeviceEgressLinks (DeviceId deviceId)
Returns all links egressing from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implements org.onosproject.net.link.LinkStore.
Definition at line 119 of file SimpleLinkStore.java.
References find-flow.deviceId.
Set<Link> org.onosproject.store.trivial.SimpleLinkStore.getDeviceIngressLinks (DeviceId deviceId)
Returns all links ingressing from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implements org.onosproject.net.link.LinkStore.
Definition at line 130 of file SimpleLinkStore.java.
References find-flow.deviceId.
Set<Link> org.onosproject.store.trivial.SimpleLinkStore.getEgressLinks (ConnectPoint src)
Returns all links egressing from the specified connection point.
Parameters
src source connection point
Returns
set of connection point links
Implements org.onosproject.net.link.LinkStore.
Definition at line 146 of file SimpleLinkStore.java.
References org.onosproject.net.ConnectPoint.deviceId(), and create-intent.egress.
Set<Link> org.onosproject.store.trivial.SimpleLinkStore.getIngressLinks (ConnectPoint dst)
Returns all links ingressing to the specified connection point.
Parameters
dst destination connection point
Returns
set of connection point links
Implements org.onosproject.net.link.LinkStore.
Definition at line 159 of file SimpleLinkStore.java.
References org.onosproject.net.ConnectPoint.deviceId(), and create-intent.ingress.
Link org.onosproject.store.trivial.SimpleLinkStore.getLink (ConnectPoint src, ConnectPoint dst)
Returns the link between the two end-points.
Parameters
src source connection point
dst destination connection point
Returns
link or null if one not found between the end-points
Implements org.onosproject.net.link.LinkStore.
Definition at line 141 of file SimpleLinkStore.java.
Referenced by org.onosproject.store.trivial.SimpleLinkStore.removeOrDownLink().
int org.onosproject.store.trivial.SimpleLinkStore.getLinkCount ()
Returns the number of links in the store.
Returns
number of links
Implements org.onosproject.net.link.LinkStore.
Definition at line 109 of file SimpleLinkStore.java.
Iterable<Link> org.onosproject.store.trivial.SimpleLinkStore.getLinks ()
Returns an iterable collection of all links in the inventory.
Returns
collection of all links
Implements org.onosproject.net.link.LinkStore.
Definition at line 114 of file SimpleLinkStore.java.
LinkEvent org.onosproject.store.trivial.SimpleLinkStore.removeLink (ConnectPoint src, ConnectPoint dst)
Removes the link based on the specified information.
Parameters
src link source
dst link destination
Returns
remove link event, or null if no change resulted
Implements org.onosproject.net.link.LinkStore.
Definition at line 260 of file SimpleLinkStore.java.
References find-flow.deviceId.
Referenced by org.onosproject.store.trivial.SimpleLinkStore.removeOrDownLink().
LinkEvent org.onosproject.store.trivial.SimpleLinkStore.removeOrDownLink (ConnectPoint src, ConnectPoint dst)
Removes the link, or marks it as inactive if the link is durable, based on the specified information.
Parameters
src link source
dst link destination
Returns
remove or update link event, or null if no change resulted
Implements org.onosproject.net.link.LinkStore.
Definition at line 190 of file SimpleLinkStore.java.
References org.onosproject.net.Link.dst(), org.onosproject.store.trivial.SimpleLinkStore.getLink(), org.onosproject.net.Link.isDurable(), org.onosproject.net.Provided.providerId(), org.onosproject.store.trivial.SimpleLinkStore.removeLink(), and org.onosproject.net.Link.src().
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleLinkStore.java