onos: org.onosproject.store.trivial.SimpleFlowRuleStore Class Reference
org.onosproject.store.trivial.SimpleFlowRuleStore Class Reference
Manages inventory of flow rules using trivial in-memory implementation.
Public Member Functions
void activate ()
void deactivate ()
int getFlowRuleCount ()
Returns the number of flow rule in the store.
FlowEntry getFlowEntry (FlowRule rule)
Returns the stored flow.
Iterable< FlowEntry > getFlowEntries (DeviceId deviceId)
Returns the flow entries associated with a device.
void storeFlowRule (FlowRule rule)
// TODO: Better description of method behavior.
void deleteFlowRule (FlowRule rule)
Marks a flow rule for deletion.
FlowRuleEvent addOrUpdateFlowRule (FlowEntry rule)
Stores a new flow rule, or updates an existing entry.
FlowRuleEvent removeFlowRule (FlowEntry rule)
void storeBatch (FlowRuleBatchOperation operation)
Stores a batch of flow rules.
void batchOperationComplete (FlowRuleBatchEvent event)
Invoked on the completion of a storeBatch operation.
FlowRuleEvent updateTableStatistics (DeviceId deviceId, List< TableStatisticsEntry > tableStats)
Updates the flow table statistics of the specified device using the given statistics.
Iterable< TableStatisticsEntry > getTableStatistics (DeviceId deviceId)
Returns the flow table statistics associated with a device.
Detailed Description
Manages inventory of flow rules using trivial in-memory implementation.
Definition at line 73 of file SimpleFlowRuleStore.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleFlowRuleStore.activate ()
Definition at line 100 of file SimpleFlowRuleStore.java.
FlowRuleEvent org.onosproject.store.trivial.SimpleFlowRuleStore.addOrUpdateFlowRule (FlowEntry rule)
Stores a new flow rule, or updates an existing entry.
Parameters
rule the flow rule to add or update
Returns
flow_added event, or null if just an update
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 216 of file SimpleFlowRuleStore.java.
References org.onosproject.net.flow.FlowEntry.FlowEntryState.ADDED, org.onosproject.net.flow.FlowRule.deviceId(), and org.onosproject.net.flow.FlowEntry.FlowEntryState.PENDING_ADD.
void org.onosproject.store.trivial.SimpleFlowRuleStore.batchOperationComplete (FlowRuleBatchEvent event)
Invoked on the completion of a storeBatch operation.
Parameters
event flow rule batch event
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 302 of file SimpleFlowRuleStore.java.
void org.onosproject.store.trivial.SimpleFlowRuleStore.deactivate ()
Definition at line 105 of file SimpleFlowRuleStore.java.
void org.onosproject.store.trivial.SimpleFlowRuleStore.deleteFlowRule (FlowRule rule)
Marks a flow rule for deletion.
Actual deletion will occur when the provider indicates that the flow has been removed.
Parameters
rule the flow rule to delete
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 197 of file SimpleFlowRuleStore.java.
References org.onosproject.net.flow.FlowRule.deviceId(), and org.onosproject.net.flow.FlowEntry.FlowEntryState.PENDING_REMOVE.
Referenced by org.onosproject.store.trivial.SimpleFlowRuleStore.storeBatch().
Iterable<FlowEntry> org.onosproject.store.trivial.SimpleFlowRuleStore.getFlowEntries (DeviceId deviceId)
Returns the flow entries associated with a device.
Parameters
deviceId the device ID
Returns
the flow entries
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 168 of file SimpleFlowRuleStore.java.
FlowEntry org.onosproject.store.trivial.SimpleFlowRuleStore.getFlowEntry (FlowRule rule)
Returns the stored flow.
Parameters
rule the rule to look for
Returns
a flow rule
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 163 of file SimpleFlowRuleStore.java.
References org.onosproject.net.flow.FlowRule.deviceId().
int org.onosproject.store.trivial.SimpleFlowRuleStore.getFlowRuleCount ()
Returns the number of flow rule in the store.
Returns
number of flow rules
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 113 of file SimpleFlowRuleStore.java.
Iterable<TableStatisticsEntry> org.onosproject.store.trivial.SimpleFlowRuleStore.getTableStatistics (DeviceId deviceId)
Returns the flow table statistics associated with a device.
Parameters
deviceId the device ID
Returns
the flow table statistics
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 334 of file SimpleFlowRuleStore.java.
References find-flow.deviceId.
FlowRuleEvent org.onosproject.store.trivial.SimpleFlowRuleStore.removeFlowRule (FlowEntry rule)
Parameters
rule the flow entry to remove
Returns
flow_removed event, or null if nothing removed
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 246 of file SimpleFlowRuleStore.java.
References org.onosproject.net.flow.FlowRule.id().
void org.onosproject.store.trivial.SimpleFlowRuleStore.storeBatch (FlowRuleBatchOperation batchOperation)
Stores a batch of flow rules.
Parameters
batchOperation batch of flow rules. A batch can contain flow rules for a single device only.
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 260 of file SimpleFlowRuleStore.java.
References org.onosproject.net.flow.FlowRuleBatchEntry.FlowRuleOperation.ADD, org.onosproject.net.flow.FlowRuleBatchEvent.completed(), org.onosproject.store.trivial.SimpleFlowRuleStore.deleteFlowRule(), org.onosproject.net.flow.FlowRule.deviceId(), org.onosproject.net.flow.FlowRuleBatchEntry.FlowRuleOperation.REMOVE, org.onosproject.net.flow.FlowRuleBatchEvent.requested(), and org.onosproject.store.trivial.SimpleFlowRuleStore.storeFlowRule().
void org.onosproject.store.trivial.SimpleFlowRuleStore.storeFlowRule (FlowRule rule)
// TODO: Better description of method behavior.
Stores a new flow rule without generating events.
Parameters
rule the flow rule to add
Deprecated:
in Cardinal Release
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 175 of file SimpleFlowRuleStore.java.
Referenced by org.onosproject.store.trivial.SimpleFlowRuleStore.storeBatch().
FlowRuleEvent org.onosproject.store.trivial.SimpleFlowRuleStore.updateTableStatistics (DeviceId deviceId, List< TableStatisticsEntry > tableStats)
Updates the flow table statistics of the specified device using the given statistics.
Parameters
deviceId device identifier
tableStats list of table statistics
Returns
ready to send event describing what occurred;
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 327 of file SimpleFlowRuleStore.java.
References find-flow.deviceId.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleFlowRuleStore.java