onos: org.onosproject.net.config.basics.BasicElementConfig< S > Class Reference
org.onosproject.net.config.basics.BasicElementConfig< S > Class Reference
Basic configuration for network elements, e.g.
Public Member Functions
String name ()
Returns friendly label for the element.
BasicElementConfig name (String name)
Sets friendly label for the element.
double latitude ()
Returns element latitude.
BasicElementConfig latitude (Double latitude)
Sets the element latitude.
double longitude ()
Returns element latitude.
BasicElementConfig longitude (Double longitude)
Sets the element longitude.
String rackAddress ()
Returns the element rack address.
BasicElementConfig rackAddress (String address)
Sets element rack address.
String owner ()
Returns owner of the element.
BasicElementConfig owner (String owner)
Sets the owner of the element.
Public Member Functions inherited from org.onosproject.net.config.basics.AllowedEntityConfig< S >
boolean isAllowed ()
Indicates whether the element is allowed for admission into the control domain.
AllowedEntityConfig isAllowed (Boolean isAllowed)
Specifies whether the element is to be allowed for admission into the control domain.
Static Public Attributes
static final String NAME = "name"
static final String LATITUDE = "latitude"
static final String LONGITUDE = "longitude"
static final String RACK_ADDRESS = "rackAddress"
static final String OWNER = "owner"
Static Protected Attributes
static final double DEFAULT_COORD = -1.0
Detailed Description
Basic configuration for network elements, e.g.
devices, hosts. Such elements can have a friendly name, geo-coordinates, logical rack coordinates and an owner entity.
Definition at line 23 of file BasicElementConfig.java.
Member Function Documentation
double org.onosproject.net.config.basics.BasicElementConfig< S >.latitude ()
Returns element latitude.
Returns
element latitude; -1 if not set
Definition at line 59 of file BasicElementConfig.java.
BasicElementConfig org.onosproject.net.config.basics.BasicElementConfig< S >.latitude (Double latitude)
Sets the element latitude.
Parameters
latitude new latitude; null to clear
Returns
self
Definition at line 69 of file BasicElementConfig.java.
double org.onosproject.net.config.basics.BasicElementConfig< S >.longitude ()
Returns element latitude.
Returns
element latitude; -1 if not set
Definition at line 78 of file BasicElementConfig.java.
BasicElementConfig org.onosproject.net.config.basics.BasicElementConfig< S >.longitude (Double longitude)
Sets the element longitude.
Parameters
longitude new longitude; null to clear
Returns
self
Definition at line 88 of file BasicElementConfig.java.
String org.onosproject.net.config.basics.BasicElementConfig< S >.name ()
Returns friendly label for the element.
Returns
friendly label or element id itself if not set
Definition at line 40 of file BasicElementConfig.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
BasicElementConfig org.onosproject.net.config.basics.BasicElementConfig< S >.name (String name)
Sets friendly label for the element.
Parameters
name new friendly label; null to clear
Returns
self
Definition at line 50 of file BasicElementConfig.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.net.config.basics.BasicElementConfig< S >.owner ()
Returns owner of the element.
Returns
owner or null if not set
Definition at line 116 of file BasicElementConfig.java.
BasicElementConfig org.onosproject.net.config.basics.BasicElementConfig< S >.owner (String owner)
Sets the owner of the element.
Parameters
owner new owner; null to clear
Returns
self
Definition at line 126 of file BasicElementConfig.java.
String org.onosproject.net.config.basics.BasicElementConfig< S >.rackAddress ()
Returns the element rack address.
Returns
rack address; null if not set
Definition at line 97 of file BasicElementConfig.java.
BasicElementConfig org.onosproject.net.config.basics.BasicElementConfig< S >.rackAddress (String address)
Sets element rack address.
Parameters
address new rack address; null to clear
Returns
self
Definition at line 107 of file BasicElementConfig.java.
Member Data Documentation
final double org.onosproject.net.config.basics.BasicElementConfig< S >.DEFAULT_COORD = -1.0 static protected
Definition at line 33 of file BasicElementConfig.java.
final String org.onosproject.net.config.basics.BasicElementConfig< S >.LATITUDE = "latitude" static
Definition at line 27 of file BasicElementConfig.java.
final String org.onosproject.net.config.basics.BasicElementConfig< S >.LONGITUDE = "longitude" static
Definition at line 28 of file BasicElementConfig.java.
final String org.onosproject.net.config.basics.BasicElementConfig< S >.NAME = "name" static
Definition at line 25 of file BasicElementConfig.java.
final String org.onosproject.net.config.basics.BasicElementConfig< S >.OWNER = "owner" static
Definition at line 31 of file BasicElementConfig.java.
final String org.onosproject.net.config.basics.BasicElementConfig< S >.RACK_ADDRESS = "rackAddress" static
Definition at line 30 of file BasicElementConfig.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/config/basics/BasicElementConfig.java