onos: org.onlab.packet.Ip6PrefixTest Class Reference
org.onlab.packet.Ip6PrefixTest Class Reference
Tests for class Ip6Prefix.
Public Member Functions
void testImmutable ()
Tests the immutability of Ip6Prefix.
void testAddressVersion ()
Tests the IPv4 prefix address version constant.
void testMaxMaskLength ()
Tests the maximum mask length.
void testVersion ()
Tests returning the IP version of the prefix.
void testAddressAndPrefixLengthIPv6 ()
Tests returning the IP address value and IP address prefix length of an IPv6 prefix.
void testValueOfByteArrayIPv6 ()
Tests valueOf() converter for IPv6 byte array.
void testInvalidValueOfNullArrayIPv6 ()
Tests invalid valueOf() converter for a null array for IPv6.
void testInvalidValueOfShortArrayIPv6 ()
Tests invalid valueOf() converter for a short array for IPv6.
void testInvalidValueOfByteArrayNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 byte array and negative prefix length.
void testInvalidValueOfByteArrayTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 byte array and too long prefix length.
void testValueOfAddressIPv6 ()
Tests valueOf() converter for IPv6 address.
void testInvalidValueOfNullAddress ()
Tests invalid valueOf() converter for a null IP address.
void testInvalidValueOfAddressNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 address and negative prefix length.
void testInvalidValueOfAddressTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 address and too long prefix length.
void testValueOfStringIPv6 ()
Tests valueOf() converter for IPv6 string.
void testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
void testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
void testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
void testInvalidValueOfStringNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 string and negative prefix length.
void testInvalidValueOfStringTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 string and too long prefix length.
void testContainsIpPrefixIPv6 ()
Tests IP prefix contains another IP prefix for IPv6.
void testContainsIpAddressIPv6 ()
Tests IP prefix contains IP address for IPv6.
void testEqualityIPv6 ()
Tests equality of Ip6Prefix for IPv6.
void testToStringIPv6 ()
Tests object string representation for IPv6.
Detailed Description
Tests for class Ip6Prefix.
Definition at line 31 of file Ip6PrefixTest.java.
Member Function Documentation
void org.onlab.packet.Ip6PrefixTest.testAddressAndPrefixLengthIPv6 ()
Tests returning the IP address value and IP address prefix length of an IPv6 prefix.
Definition at line 73 of file Ip6PrefixTest.java.
References org.onlab.packet.Ip6Prefix.address(), org.onlab.packet.IpPrefix.prefixLength(), and org.onlab.packet.Ip6Address.valueOf().
void org.onlab.packet.Ip6PrefixTest.testAddressVersion ()
Tests the IPv4 prefix address version constant.
Definition at line 44 of file Ip6PrefixTest.java.
References org.onlab.packet.Ip6Prefix.VERSION.
void org.onlab.packet.Ip6PrefixTest.testContainsIpAddressIPv6 ()
Tests IP prefix contains IP address for IPv6.
Definition at line 471 of file Ip6PrefixTest.java.
References org.onlab.packet.IpPrefix.contains(), and org.onlab.packet.Ip6Address.valueOf().
void org.onlab.packet.Ip6PrefixTest.testContainsIpPrefixIPv6 ()
Tests IP prefix contains another IP prefix for IPv6.
Definition at line 398 of file Ip6PrefixTest.java.
References org.onlab.packet.IpPrefix.contains(), and org.onlab.packet.Ip6Prefix.valueOf().
void org.onlab.packet.Ip6PrefixTest.testEqualityIPv6 ()
Tests equality of Ip6Prefix for IPv6.
Definition at line 524 of file Ip6PrefixTest.java.
References org.onlab.packet.Ip6Prefix.valueOf().
void org.onlab.packet.Ip6PrefixTest.testImmutable ()
Tests the immutability of Ip6Prefix.
Definition at line 36 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfAddressNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 address and negative prefix length.
Definition at line 274 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfAddressTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 address and too long prefix length.
Definition at line 288 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfByteArrayNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 byte array and negative prefix length.
Definition at line 192 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfByteArrayTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 byte array and too long prefix length.
Definition at line 208 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
Definition at line 350 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
Definition at line 362 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfNullAddress ()
Tests invalid valueOf() converter for a null IP address.
Definition at line 261 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfNullArrayIPv6 ()
Tests invalid valueOf() converter for a null array for IPv6.
Definition at line 167 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
Definition at line 338 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfShortArrayIPv6 ()
Tests invalid valueOf() converter for a short array for IPv6.
Definition at line 179 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfStringNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 string and negative prefix length.
Definition at line 375 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testInvalidValueOfStringTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 string and too long prefix length.
Definition at line 387 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testMaxMaskLength ()
Tests the maximum mask length.
Definition at line 52 of file Ip6PrefixTest.java.
References org.onlab.packet.Ip6Prefix.MAX_MASK_LENGTH.
void org.onlab.packet.Ip6PrefixTest.testToStringIPv6 ()
Tests object string representation for IPv6.
Definition at line 552 of file Ip6PrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.Ip6PrefixTest.testValueOfAddressIPv6 ()
Tests valueOf() converter for IPv6 address.
Definition at line 223 of file Ip6PrefixTest.java.
void org.onlab.packet.Ip6PrefixTest.testValueOfByteArrayIPv6 ()
Tests valueOf() converter for IPv6 byte array.
Definition at line 118 of file Ip6PrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.Ip6PrefixTest.testValueOfStringIPv6 ()
Tests valueOf() converter for IPv6 string.
Definition at line 301 of file Ip6PrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.Ip6PrefixTest.testVersion ()
Tests returning the IP version of the prefix.
Definition at line 60 of file Ip6PrefixTest.java.
References org.onlab.packet.IpPrefix.version().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/Ip6PrefixTest.java