onos: org.onosproject.net.intent.constraint.LatencyConstraintTest Class Reference
org.onosproject.net.intent.constraint.LatencyConstraintTest Class Reference
Public Member Functions
void setUp ()
void testLessThanLatency ()
Tests the path latency is less than the supplied constraint.
void testMoreThanLatency ()
Tests the path latency is more than the supplied constraint.
void testCost ()
Tests the link latency is equal to "latency" annotated value.
void testEquality ()
Tests equality of the instances.
Detailed Description
Definition at line 45 of file LatencyConstraintTest.java.
Member Function Documentation
void org.onosproject.net.intent.constraint.LatencyConstraintTest.setUp ()
Definition at line 66 of file LatencyConstraintTest.java.
void org.onosproject.net.intent.constraint.LatencyConstraintTest.testCost ()
Tests the link latency is equal to "latency" annotated value.
Definition at line 101 of file LatencyConstraintTest.java.
References org.onosproject.net.intent.constraint.LatencyConstraint.cost().
void org.onosproject.net.intent.constraint.LatencyConstraintTest.testEquality ()
Tests equality of the instances.
Definition at line 112 of file LatencyConstraintTest.java.
void org.onosproject.net.intent.constraint.LatencyConstraintTest.testLessThanLatency ()
Tests the path latency is less than the supplied constraint.
Definition at line 81 of file LatencyConstraintTest.java.
References org.onosproject.net.intent.constraint.LatencyConstraint.validate().
void org.onosproject.net.intent.constraint.LatencyConstraintTest.testMoreThanLatency ()
Tests the path latency is more than the supplied constraint.
Definition at line 91 of file LatencyConstraintTest.java.
References org.onosproject.net.intent.constraint.LatencyConstraint.validate().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/intent/constraint/LatencyConstraintTest.java