onos: org.onosproject.segmentrouting.TunnelHandler Class Reference
org.onosproject.segmentrouting.TunnelHandler Class Reference
Tunnel Handler.
Classes
enum Result
Public Member Functions
TunnelHandler (LinkService linkService, DeviceConfiguration deviceConfiguration, Map< DeviceId, DefaultGroupHandler > groupHandlerMap, EventuallyConsistentMap< String, Tunnel > tunnelStore)
Result createTunnel (Tunnel tunnel)
Creates a tunnel.
Result removeTunnel (Tunnel tunnelInfo)
Removes the tunnel with the tunnel ID given.
Tunnel getTunnel (String tid)
Returns the tunnel with the tunnel ID given.
List< Tunnel > getTunnels ()
Returns all tunnels.
Protected Attributes
final Logger log = getLogger(getClass())
Detailed Description
Tunnel Handler.
Definition at line 38 of file TunnelHandler.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.TunnelHandler.TunnelHandler (LinkService linkService, DeviceConfiguration deviceConfiguration, Map< DeviceId, DefaultGroupHandler > groupHandlerMap, EventuallyConsistentMap< String, Tunnel > tunnelStore)
Definition at line 56 of file TunnelHandler.java.
Member Function Documentation
Result org.onosproject.segmentrouting.TunnelHandler.createTunnel (Tunnel tunnel)
Creates a tunnel.
Parameters
tunnel tunnel reference to create a tunnel
Returns
WRONG_PATH if the tunnel path is wrong, ID_EXISTS if the tunnel ID exists already, TUNNEL_EXISTS if the same tunnel exists, INTERNAL_ERROR if the tunnel creation failed internally, SUCCESS if the tunnel is created successfully
Definition at line 75 of file TunnelHandler.java.
References org.onosproject.segmentrouting.Tunnel.id(), org.onosproject.segmentrouting.TunnelHandler.Result.ID_EXISTS, org.onosproject.segmentrouting.TunnelHandler.Result.INTERNAL_ERROR, org.onosproject.segmentrouting.Tunnel.labelIds(), org.onosproject.segmentrouting.TunnelHandler.Result.SUCCESS, org.onosproject.segmentrouting.TunnelHandler.Result.TUNNEL_EXISTS, and org.onosproject.segmentrouting.TunnelHandler.Result.WRONG_PATH.
Tunnel org.onosproject.segmentrouting.TunnelHandler.getTunnel (String tid)
Returns the tunnel with the tunnel ID given.
Parameters
tid Tunnel ID
Returns
Tunnel reference
Definition at line 142 of file TunnelHandler.java.
List<Tunnel> org.onosproject.segmentrouting.TunnelHandler.getTunnels ()
Returns all tunnels.
Returns
list of Tunnels
Definition at line 151 of file TunnelHandler.java.
Result org.onosproject.segmentrouting.TunnelHandler.removeTunnel (Tunnel tunnelInfo)
Removes the tunnel with the tunnel ID given.
Parameters
tunnelInfo tunnel information to delete tunnels
Returns
TUNNEL_NOT_FOUND if the tunnel to remove does not exists, INTERNAL_ERROR if the tunnel creation failed internally, SUCCESS if the tunnel is created successfully.
Definition at line 112 of file TunnelHandler.java.
References find-flow.deviceId, org.onosproject.segmentrouting.TunnelHandler.Result.INTERNAL_ERROR, org.onosproject.segmentrouting.Tunnel.isAllowedToRemoveGroup(), org.onosproject.segmentrouting.TunnelHandler.Result.SUCCESS, and org.onosproject.segmentrouting.TunnelHandler.Result.TUNNEL_NOT_FOUND.
Member Data Documentation
final Logger org.onosproject.segmentrouting.TunnelHandler.log = getLogger(getClass()) protected
Definition at line 39 of file TunnelHandler.java.
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/TunnelHandler.java