onos: org.onosproject.app.impl.ApplicationManagerTest Class Reference
org.onosproject.app.impl.ApplicationManagerTest Class Reference
Test of the application manager implementation.
Public Member Functions
void setUp ()
void tearDown ()
void install ()
void uninstall ()
void activate ()
void deactivate ()
Static Public Attributes
static final DefaultApplicationId APP_ID = new DefaultApplicationId(1, APP_NAME)
Detailed Description
Test of the application manager implementation.
Definition at line 50 of file ApplicationManagerTest.java.
Member Function Documentation
void org.onosproject.app.impl.ApplicationManagerTest.activate ()
Definition at line 109 of file ApplicationManagerTest.java.
References org.onosproject.app.impl.ApplicationManagerTest.APP_ID, org.onosproject.app.impl.ApplicationManager.getState(), and org.onosproject.app.impl.ApplicationManagerTest.install().
Referenced by org.onosproject.app.impl.ApplicationManagerTest.deactivate().
void org.onosproject.app.impl.ApplicationManagerTest.deactivate ()
Definition at line 117 of file ApplicationManagerTest.java.
References org.onosproject.app.impl.ApplicationManagerTest.activate(), org.onosproject.app.impl.ApplicationManagerTest.APP_ID, and org.onosproject.app.impl.ApplicationManager.getState().
void org.onosproject.app.impl.ApplicationManagerTest.install ()
Definition at line 85 of file ApplicationManagerTest.java.
References org.onosproject.app.impl.ApplicationManagerTest.APP_ID, org.onosproject.app.impl.ApplicationManager.getApplication(), org.onosproject.app.impl.ApplicationManager.getApplications(), and org.onosproject.app.impl.ApplicationManager.getState().
Referenced by org.onosproject.app.impl.ApplicationManagerTest.activate(), and org.onosproject.app.impl.ApplicationManagerTest.uninstall().
void org.onosproject.app.impl.ApplicationManagerTest.setUp ()
Definition at line 60 of file ApplicationManagerTest.java.
void org.onosproject.app.impl.ApplicationManagerTest.tearDown ()
Definition at line 69 of file ApplicationManagerTest.java.
void org.onosproject.app.impl.ApplicationManagerTest.uninstall ()
Definition at line 102 of file ApplicationManagerTest.java.
References org.onosproject.app.impl.ApplicationManagerTest.APP_ID, org.onosproject.app.impl.ApplicationManager.getApplications(), and org.onosproject.app.impl.ApplicationManagerTest.install().
Member Data Documentation
final DefaultApplicationId org.onosproject.app.impl.ApplicationManagerTest.APP_ID = new DefaultApplicationId(1, APP_NAME) static
Definition at line 52 of file ApplicationManagerTest.java.
Referenced by org.onosproject.app.impl.ApplicationManagerTest.activate(), org.onosproject.app.impl.ApplicationManagerTest.deactivate(), org.onosproject.app.impl.ApplicationManagerTest.install(), and org.onosproject.app.impl.ApplicationManagerTest.uninstall().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/app/impl/ApplicationManagerTest.java