onos: org.onlab.nio.IOLoopTestClient Class Reference
org.onlab.nio.IOLoopTestClient Class Reference
Auxiliary test fixture to measure speed of NIO-based channels.
Public Member Functions
IOLoopTestClient (InetAddress ip, int wc, int mc, int ml, int port) throws IOException
Creates a speed client.
void start () throws IOException
Starts the client workers.
void await (int secs) throws InterruptedException, ExecutionException, TimeoutException
Waits for the client workers to complete.
void report ()
Reports on the accumulated throughput and latency.
Static Public Member Functions
static void main (String[] args) throws IOException, InterruptedException, ExecutionException, TimeoutException
Main entry point to launch the client.
static void startStandalone (String[] args) throws IOException, InterruptedException, ExecutionException, TimeoutException
Starts a standalone IO loop test client.
Detailed Description
Auxiliary test fixture to measure speed of NIO-based channels.
Definition at line 51 of file IOLoopTestClient.java.
Constructor & Destructor Documentation
org.onlab.nio.IOLoopTestClient.IOLoopTestClient (InetAddress ip, int wc, int mc, int ml, int port) throws IOException
Creates a speed client.
Parameters
ip ip address of server
wc worker count
mc message count to send per client
ml message length in bytes
port socket port
Exceptions
java.io.IOException if unable to create IO loops
Definition at line 120 of file IOLoopTestClient.java.
Referenced by org.onlab.nio.IOLoopTestClient.startStandalone().
Member Function Documentation
void org.onlab.nio.IOLoopTestClient.await (int secs) throws InterruptedException, ExecutionException, TimeoutException
Waits for the client workers to complete.
Parameters
secs timeout in seconds
Exceptions
java.util.concurrent.ExecutionException if execution failed
InterruptedException if interrupt occurred while waiting
java.util.concurrent.TimeoutException if timeout occurred
Definition at line 183 of file IOLoopTestClient.java.
static void org.onlab.nio.IOLoopTestClient.main (String[] args) throws IOException, InterruptedException, ExecutionException, TimeoutException static
Main entry point to launch the client.
Parameters
args command-line arguments
Exceptions
java.io.IOException if unable to connect to server
InterruptedException if latch wait gets interrupted
java.util.concurrent.ExecutionException if wait gets interrupted
java.util.concurrent.TimeoutException if timeout occurred while waiting for completion
Definition at line 79 of file IOLoopTestClient.java.
References org.onlab.nio.IOLoopTestClient.startStandalone().
void org.onlab.nio.IOLoopTestClient.report ()
Reports on the accumulated throughput and latency.
Definition at line 199 of file IOLoopTestClient.java.
References org.onlab.util.Counter.throughput().
void org.onlab.nio.IOLoopTestClient.start () throws IOException
Starts the client workers.
Exceptions
java.io.IOException if unable to open connection
Definition at line 138 of file IOLoopTestClient.java.
static void org.onlab.nio.IOLoopTestClient.startStandalone (String[] args) throws IOException, InterruptedException, ExecutionException, TimeoutException static
Starts a standalone IO loop test client.
Parameters
args command-line arguments
Definition at line 91 of file IOLoopTestClient.java.
References org.onlab.nio.IOLoopTestClient.IOLoopTestClient().
Referenced by org.onlab.nio.IOLoopTestClient.main().
The documentation for this class was generated from the following file:
utils/nio/src/test/java/org/onlab/nio/IOLoopTestClient.java