onos: org.onosproject.openflow.DriverAdapter Class Reference
org.onosproject.openflow.DriverAdapter Class Reference
Created by ray on 11/4/15.
Public Member Functions
String name ()
Returns the driver name.
Driver parent ()
Returns the parent driver from which this driver inherits behaviours and properties.
String manufacturer ()
Returns the device manufacturer name.
String hwVersion ()
Returns the device hardware version.
String swVersion ()
Returns the device software version.
Set< Class<?extends Behaviour > > behaviours ()
Returns the set of behaviours supported by this driver.
Class<?extends Behaviour > implementation (Class<?extends Behaviour > behaviour)
Returns the implementation class for the specified behaviour.
boolean hasBehaviour (Class<?extends Behaviour > behaviourClass)
Indicates whether or not the driver, or any of its parents, support the specified class of behaviour.
Map< String, String > properties ()
Returns the set of annotations as map of key/value properties.
Driver merge (Driver other)
Merges the specified driver behaviours and properties into this one, giving preference to the other driver when dealing with conflicts.
Set< String > keys ()
Returns the set of keys for available annotations.
String value (String key)
Returns the value of the specified annotation.
Detailed Description
Created by ray on 11/4/15.
Definition at line 30 of file DriverAdapter.java.
Member Function Documentation
Set<Class<? extends Behaviour> > org.onosproject.openflow.DriverAdapter.behaviours ()
Returns the set of behaviours supported by this driver.
It reflects behaviours of only this driver and not its parent.
Returns
set of device driver behaviours
Implements org.onosproject.net.driver.Driver.
Definition at line 57 of file DriverAdapter.java.
boolean org.onosproject.openflow.DriverAdapter.hasBehaviour (Class<?extends Behaviour > behaviourClass)
Indicates whether or not the driver, or any of its parents, support the specified class of behaviour.
It
Parameters
behaviourClass behaviour class
Returns
true if behaviour is supported
Implements org.onosproject.net.driver.Driver.
Definition at line 67 of file DriverAdapter.java.
String org.onosproject.openflow.DriverAdapter.hwVersion ()
Returns the device hardware version.
Returns
hardware version
Implements org.onosproject.net.driver.Driver.
Definition at line 47 of file DriverAdapter.java.
Class<? extends Behaviour> org.onosproject.openflow.DriverAdapter.implementation (Class<?extends Behaviour > behaviour)
Returns the implementation class for the specified behaviour.
It reflects behaviours of only this driver and not its parent.
Parameters
behaviour behaviour interface
Returns
implementation class
Implements org.onosproject.net.driver.Driver.
Definition at line 62 of file DriverAdapter.java.
Set<String> org.onosproject.openflow.DriverAdapter.keys ()
Returns the set of keys for available annotations.
Returns
annotation keys
Implements org.onosproject.net.Annotations.
Definition at line 96 of file DriverAdapter.java.
String org.onosproject.openflow.DriverAdapter.manufacturer ()
Returns the device manufacturer name.
Returns
manufacturer name
Implements org.onosproject.net.driver.Driver.
Definition at line 42 of file DriverAdapter.java.
Driver org.onosproject.openflow.DriverAdapter.merge (Driver other)
Merges the specified driver behaviours and properties into this one, giving preference to the other driver when dealing with conflicts.
Parameters
other other driver
Returns
merged driver
Implements org.onosproject.net.driver.Driver.
Definition at line 91 of file DriverAdapter.java.
String org.onosproject.openflow.DriverAdapter.name ()
Returns the driver name.
This is expected to be a reverse-DNS, Java package-like name.
Returns
driver name
Implements org.onosproject.net.driver.Driver.
Definition at line 32 of file DriverAdapter.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
Driver org.onosproject.openflow.DriverAdapter.parent ()
Returns the parent driver from which this driver inherits behaviours and properties.
Returns
parent driver; null if driver has no parent
Implements org.onosproject.net.driver.Driver.
Definition at line 37 of file DriverAdapter.java.
Map<String, String> org.onosproject.openflow.DriverAdapter.properties ()
Returns the set of annotations as map of key/value properties.
Returns
map of properties
Implements org.onosproject.net.driver.Driver.
Definition at line 86 of file DriverAdapter.java.
String org.onosproject.openflow.DriverAdapter.swVersion ()
Returns the device software version.
Returns
software version
Implements org.onosproject.net.driver.Driver.
Definition at line 52 of file DriverAdapter.java.
String org.onosproject.openflow.DriverAdapter.value (String key)
Returns the value of the specified annotation.
Parameters
key annotation key
Returns
annotation value
Implements org.onosproject.net.Annotations.
Definition at line 101 of file DriverAdapter.java.
The documentation for this class was generated from the following file:
protocols/openflow/ctl/src/test/java/org/onosproject/openflow/DriverAdapter.java