onos: org.onosproject.bgpio.protocol.linkstate.NodeDescriptors Class Reference
org.onosproject.bgpio.protocol.linkstate.NodeDescriptors Class Reference
Provides Local and Remote NodeDescriptors which contains Node Descriptor Sub-TLVs.
Public Member Functions
NodeDescriptors ()
Resets parameters.
NodeDescriptors (List< BgpValueType > subTlvs, short deslength, short desType)
Constructor to initialize parameters.
List< BgpValueType > getSubTlvs ()
Returns list of subTlvs.
int hashCode ()
boolean equals (Object obj)
short getLength ()
Returns node descriptors length.
short getType ()
Returns node descriptors type.
String toString ()
int compareTo (Object o)
Static Public Member Functions
static NodeDescriptors read (ChannelBuffer cb, short desLength, short desType, byte protocolId) throws BgpParseException
Reads node descriptors Sub-TLVs.
Static Public Attributes
static final short LOCAL_NODE_DES_TYPE = 256
static final short REMOTE_NODE_DES_TYPE = 257
static final short IGP_ROUTERID_TYPE = 515
static final short IS_IS_LEVEL_1_PROTOCOL_ID = 1
static final short IS_IS_LEVEL_2_PROTOCOL_ID = 2
static final short OSPF_V2_PROTOCOL_ID = 3
static final short OSPF_V3_PROTOCOL_ID = 6
static final int TYPE_AND_LEN = 4
static final int ISISNONPSEUDONODE_LEN = 6
static final int ISISPSEUDONODE_LEN = 7
static final int OSPFNONPSEUDONODE_LEN = 4
static final int OSPFPSEUDONODE_LEN = 8
Detailed Description
Provides Local and Remote NodeDescriptors which contains Node Descriptor Sub-TLVs.
Definition at line 45 of file NodeDescriptors.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.NodeDescriptors ()
Resets parameters.
Definition at line 83 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.compareTo(), org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.equals(), and org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.NodeDescriptors (List< BgpValueType > subTlvs, short deslength, short desType)
Constructor to initialize parameters.
Parameters
subTlvs list of subTlvs
deslength Descriptors length
desType local node descriptor or remote node descriptor type
Definition at line 96 of file NodeDescriptors.java.
Member Function Documentation
int org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.compareTo (Object o)
Definition at line 233 of file NodeDescriptors.java.
References org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.equals(), and org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.NodeDescriptors().
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.compareTo().
boolean org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.equals (Object obj)
Definition at line 117 of file NodeDescriptors.java.
References org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.NodeDescriptors().
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.compareTo().
short org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.getLength ()
Returns node descriptors length.
Returns
node descriptors length
Definition at line 211 of file NodeDescriptors.java.
List<BgpValueType> org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.getSubTlvs ()
Returns list of subTlvs.
Returns
subTlvs list of subTlvs
Definition at line 107 of file NodeDescriptors.java.
short org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.getType ()
Returns node descriptors type.
Returns
node descriptors type
Definition at line 220 of file NodeDescriptors.java.
int org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.hashCode ()
Definition at line 112 of file NodeDescriptors.java.
static NodeDescriptors org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read (ChannelBuffer cb, short desLength, short desType, byte protocolId) throws BgpParseException static
Reads node descriptors Sub-TLVs.
Parameters
cb ChannelBuffer
desLength node descriptor length
desType local node descriptor or remote node descriptor type
protocolId protocol ID
Returns
object of NodeDescriptors
Exceptions
BgpParseException while parsing node descriptors
Definition at line 158 of file NodeDescriptors.java.
References org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.IGP_ROUTERID_TYPE, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.IS_IS_LEVEL_1_PROTOCOL_ID, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.IS_IS_LEVEL_2_PROTOCOL_ID, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.ISISNONPSEUDONODE_LEN, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.ISISPSEUDONODE_LEN, find-link-in-cluster.length, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.NodeDescriptors(), org.onosproject.bgpio.types.BgpErrorType.OPTIONAL_ATTRIBUTE_ERROR, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.OSPF_V2_PROTOCOL_ID, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.OSPF_V3_PROTOCOL_ID, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.OSPFNONPSEUDONODE_LEN, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.OSPFPSEUDONODE_LEN, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.TYPE_AND_LEN, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.toString ()
Definition at line 225 of file NodeDescriptors.java.
Member Data Documentation
final short org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.IGP_ROUTERID_TYPE = 515 static
Definition at line 66 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
final short org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.IS_IS_LEVEL_1_PROTOCOL_ID = 1 static
Definition at line 67 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
final short org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.IS_IS_LEVEL_2_PROTOCOL_ID = 2 static
Definition at line 68 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
final int org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.ISISNONPSEUDONODE_LEN = 6 static
Definition at line 72 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
final int org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.ISISPSEUDONODE_LEN = 7 static
Definition at line 73 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
final short org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.LOCAL_NODE_DES_TYPE = 256 static
Definition at line 64 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkIdendifier(), org.onosproject.bgpio.protocol.linkstate.BgpNodeLSIdentifier.parseLocalNodeDescriptors(), and org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parseLocalNodeDescriptors().
final short org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.OSPF_V2_PROTOCOL_ID = 3 static
Definition at line 69 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
final short org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.OSPF_V3_PROTOCOL_ID = 6 static
Definition at line 70 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
final int org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.OSPFNONPSEUDONODE_LEN = 4 static
Definition at line 74 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
final int org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.OSPFPSEUDONODE_LEN = 8 static
Definition at line 75 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
final short org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.REMOTE_NODE_DES_TYPE = 257 static
Definition at line 65 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkIdendifier().
final int org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.TYPE_AND_LEN = 4 static
Definition at line 71 of file NodeDescriptors.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.read().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/protocol/linkstate/NodeDescriptors.java