onos: org.onlab.packet.IPv6Test Class Reference
org.onlab.packet.IPv6Test Class Reference
Tests for class IPv6.
Public Member Functions
void setUp ()
void testSerialize ()
Tests serialize and setters.
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws DeserializationException
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class IPv6.
Definition at line 36 of file IPv6Test.java.
Member Function Documentation
void org.onlab.packet.IPv6Test.setUp ()
Definition at line 74 of file IPv6Test.java.
static void org.onlab.packet.IPv6Test.setUpBeforeClass () throws Exception static
Definition at line 52 of file IPv6Test.java.
References find-link-in-cluster.length.
void org.onlab.packet.IPv6Test.testDeserialize () throws DeserializationException
Tests deserialize and getters.
Definition at line 114 of file IPv6Test.java.
References org.onlab.packet.IPv6.getDestinationAddress(), org.onlab.packet.IPv6.getFlowLabel(), org.onlab.packet.IPv6.getHopLimit(), org.onlab.packet.IPv6.getNextHeader(), org.onlab.packet.IPv6.getSourceAddress(), org.onlab.packet.IPv6.getTrafficClass(), org.onlab.packet.IPv6.getVersion(), find-link-in-cluster.length, and org.onlab.packet.IPv6.PROTOCOL_UDP.
void org.onlab.packet.IPv6Test.testDeserializeBadInput () throws Exception
Definition at line 97 of file IPv6Test.java.
void org.onlab.packet.IPv6Test.testDeserializeTruncated () throws Exception
Definition at line 102 of file IPv6Test.java.
References org.onlab.packet.IPv6.FIXED_HEADER_LENGTH.
void org.onlab.packet.IPv6Test.testEqual ()
Tests comparator.
Definition at line 130 of file IPv6Test.java.
References org.onlab.packet.IPv6.equals(), and org.onlab.packet.IPv6.PROTOCOL_UDP.
void org.onlab.packet.IPv6Test.testSerialize ()
Tests serialize and setters.
Definition at line 82 of file IPv6Test.java.
References org.onlab.packet.IPv6.PROTOCOL_UDP, and org.onlab.packet.IPv6.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/IPv6Test.java