onos: org.onosproject.net.intent.impl.MockFlowRuleService Class Reference
org.onosproject.net.intent.impl.MockFlowRuleService Class Reference
Public Member Functions
void setErrorFlow (int errorFlow)
void setFuture (boolean success)
void apply (FlowRuleOperations ops)
Applies a batch operation of FlowRules.
int getFlowRuleCount ()
Returns the number of flow rules in the system.
Iterable< FlowEntry > getFlowEntries (DeviceId deviceId)
Returns the collection of flow entries applied on the specified device.
void applyFlowRules (FlowRule...flowRules)
Applies the specified flow rules onto their respective devices.
void removeFlowRules (FlowRule...flowRules)
Removes the specified flow rules from their respective devices.
Iterable< FlowRule > getFlowRulesById (ApplicationId id)
Returns a list of rules with this application id.
Iterable< FlowRule > getFlowRulesByGroupId (ApplicationId appId, short groupId)
Returns a list of rules filterd by application and group id.
Public Member Functions inherited from org.onosproject.net.flow.FlowRuleServiceAdapter
int getFlowRuleCount ()
Returns the number of flow rules in the system.
Iterable< FlowEntry > getFlowEntries (DeviceId deviceId)
Returns the collection of flow entries applied on the specified device.
void applyFlowRules (FlowRule...flowRules)
Applies the specified flow rules onto their respective devices.
void removeFlowRules (FlowRule...flowRules)
Removes the specified flow rules from their respective devices.
void removeFlowRulesById (ApplicationId appId)
Removes all rules by id.
Iterable< FlowRule > getFlowRulesById (ApplicationId id)
Returns a list of rules with this application id.
Iterable< FlowRule > getFlowRulesByGroupId (ApplicationId appId, short groupId)
Returns a list of rules filterd by application and group id.
void apply (FlowRuleOperations ops)
Applies a batch operation of FlowRules.
void addListener (FlowRuleListener listener)
void removeListener (FlowRuleListener listener)
Iterable< TableStatisticsEntry > getFlowTableStatistics (DeviceId deviceId)
Returns the collection of flow table statistics of the specified device.
Additional Inherited Members
Public Attributes inherited from org.onosproject.net.flow.FlowRuleService
String FLOW_OP_TOPIC = "flow-ops-ids"
The topic used for obtaining globally unique ids.
Detailed Description
Definition at line 32 of file MockFlowRuleService.java.
Member Function Documentation
void org.onosproject.net.intent.impl.MockFlowRuleService.apply (FlowRuleOperations ops)
Applies a batch operation of FlowRules.
Parameters
ops batch operation to apply
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 47 of file MockFlowRuleService.java.
void org.onosproject.net.intent.impl.MockFlowRuleService.applyFlowRules (FlowRule... flowRules)
Applies the specified flow rules onto their respective devices.
These flow rules will be retained by the system and re-applied anytime the device reconnects to the controller.
Parameters
flowRules one or more flow rules
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 87 of file MockFlowRuleService.java.
Iterable<FlowEntry> org.onosproject.net.intent.impl.MockFlowRuleService.getFlowEntries (DeviceId deviceId)
Returns the collection of flow entries applied on the specified device.
This will include flow rules which may not yet have been applied to the device.
Parameters
deviceId device identifier
Returns
collection of flow rules
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 79 of file MockFlowRuleService.java.
References find-flow.deviceId.
int org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRuleCount ()
Returns the number of flow rules in the system.
Returns
flow rule count
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 74 of file MockFlowRuleService.java.
Referenced by org.onosproject.net.intent.impl.IntentManagerTest.intentSubclassCompile(), org.onosproject.net.intent.impl.IntentManagerTest.setUp(), org.onosproject.net.intent.impl.IntentManagerTest.stressSubmitWithdrawSame(), org.onosproject.net.intent.impl.IntentManagerTest.stressSubmitWithdrawUnique(), org.onosproject.net.intent.impl.IntentManagerTest.submitIntent(), org.onosproject.net.intent.impl.IntentManagerTest.testCorruptCleanup(), org.onosproject.net.intent.impl.IntentManagerTest.testFlowRemoval(), and org.onosproject.net.intent.impl.IntentManagerTest.withdrawIntent().
Iterable<FlowRule> org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRulesByGroupId (ApplicationId appId, short groupId)
Returns a list of rules filterd by application and group id.
Parameters
appId the application id to lookup
groupId the groupid to lookup
Returns
collection of flow rules
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 106 of file MockFlowRuleService.java.
Iterable<FlowRule> org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRulesById (ApplicationId id)
Returns a list of rules with this application id.
Parameters
id the id to look up
Returns
collection of flow rules
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 99 of file MockFlowRuleService.java.
void org.onosproject.net.intent.impl.MockFlowRuleService.removeFlowRules (FlowRule... flowRules)
Removes the specified flow rules from their respective devices.
If the device is not presently connected to the controller, these flow will be removed once the device reconnects.
Parameters
flowRules one or more flow rules throws SomeKindOfException that indicates which ones were removed and which ones failed
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 92 of file MockFlowRuleService.java.
void org.onosproject.net.intent.impl.MockFlowRuleService.setErrorFlow (int errorFlow)
Definition at line 38 of file MockFlowRuleService.java.
void org.onosproject.net.intent.impl.MockFlowRuleService.setFuture (boolean success)
Definition at line 42 of file MockFlowRuleService.java.
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/intent/impl/MockFlowRuleService.java