onos: org.onlab.packet.ICMP6Test Class Reference
org.onlab.packet.ICMP6Test Class Reference
Tests for class ICMP6.
Public Member Functions
void testSerialize ()
Tests serialize and setters.
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws Exception
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class ICMP6.
Definition at line 33 of file ICMP6Test.java.
Member Function Documentation
static void org.onlab.packet.ICMP6Test.setUpBeforeClass () throws Exception static
Definition at line 51 of file ICMP6Test.java.
References org.onlab.packet.IPv6.PROTOCOL_ICMP6.
void org.onlab.packet.ICMP6Test.testDeserialize () throws Exception
Tests deserialize and getters.
Definition at line 84 of file ICMP6Test.java.
References org.onlab.packet.ICMP6.ECHO_REQUEST, org.onlab.packet.ICMP6.getChecksum(), org.onlab.packet.ICMP6.getIcmpCode(), and org.onlab.packet.ICMP6.getIcmpType().
void org.onlab.packet.ICMP6Test.testDeserializeBadInput () throws Exception
Definition at line 71 of file ICMP6Test.java.
void org.onlab.packet.ICMP6Test.testDeserializeTruncated () throws Exception
Definition at line 76 of file ICMP6Test.java.
void org.onlab.packet.ICMP6Test.testEqual ()
Tests comparator.
Definition at line 96 of file ICMP6Test.java.
References org.onlab.packet.ICMP6.ECHO_REPLY, org.onlab.packet.ICMP6.ECHO_REQUEST, and org.onlab.packet.ICMP6.equals().
void org.onlab.packet.ICMP6Test.testSerialize ()
Tests serialize and setters.
Definition at line 61 of file ICMP6Test.java.
References org.onlab.packet.ICMP6.ECHO_REQUEST, and org.onlab.packet.ICMP6.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ICMP6Test.java