onos: org.onosproject.ui.topo.LinkHighlight Class Reference
org.onosproject.ui.topo.LinkHighlight Class Reference
Denotes the highlighting to be applied to a link.
Classes
enum Flavor
Link highlighting flavor.
Public Member Functions
LinkHighlight (String linkId, Flavor flavor)
Constructs a link highlight entity.
LinkHighlight addMod (Mod mod)
Adds a highlighting modification to this link highlight.
LinkHighlight setLabel (String label)
Adds a label to be displayed on the link.
Flavor flavor ()
Returns the highlight flavor.
Set< Mod > mods ()
Returns the highlight modifications.
String cssClasses ()
Generates the CSS classes string from the flavor and any optional mods.
String label ()
Returns the label text.
Public Member Functions inherited from org.onosproject.ui.topo.AbstractHighlight
AbstractHighlight (TopoElementType type, String elementId)
Constructs the highlight.
void keepSubdued ()
Sets a flag to tell the renderer to keep this element subdued.
TopoElementType type ()
Returns the element type.
String elementId ()
Returns the element identifier.
boolean subdued ()
Returns the subdued flag.
Static Public Attributes
static final Mod MOD_OPTICAL = new Mod("optical")
Denotes a link to be tagged as an optical link.
static final Mod MOD_ANIMATED = new Mod("animated")
Denotes a link to be tagged with animated traffic ("marching ants").
Detailed Description
Denotes the highlighting to be applied to a link.
Flavor is a closed set of NO-, PRIMARY-, or SECONDARY- highlighting. Mod is an open ended set of additional modifications (CSS classes) that may also be applied. Note that MOD_OPTICAL and MOD_ANIMATED are pre-defined mods. Label text may be set, which will also be displayed on the link.
Definition at line 33 of file LinkHighlight.java.
Constructor & Destructor Documentation
org.onosproject.ui.topo.LinkHighlight.LinkHighlight (String linkId, Flavor flavor)
Constructs a link highlight entity.
Parameters
linkId the link identifier
flavor the highlight flavor
Definition at line 51 of file LinkHighlight.java.
References org.onosproject.ui.topo.TopoElementType.LINK.
Member Function Documentation
LinkHighlight org.onosproject.ui.topo.LinkHighlight.addMod (Mod mod)
Adds a highlighting modification to this link highlight.
Parameters
mod mod to be added
Returns
self, for chaining
Definition at line 62 of file LinkHighlight.java.
String org.onosproject.ui.topo.LinkHighlight.cssClasses ()
Generates the CSS classes string from the flavor and any optional mods.
Returns
CSS classes string
Definition at line 102 of file LinkHighlight.java.
References org.onosproject.ui.topo.LinkHighlight.flavor(), and org.onosproject.ui.topo.LinkHighlight.Flavor.toString().
Referenced by org.onosproject.ui.topo.LinkHighlightTest.basic(), org.onosproject.ui.topo.LinkHighlightTest.customMod(), org.onosproject.ui.topo.LinkHighlightTest.primaryOptical(), org.onosproject.ui.topo.LinkHighlightTest.secondaryAnimatedWithLabel(), and org.onosproject.ui.topo.LinkHighlightTest.severalMods().
Flavor org.onosproject.ui.topo.LinkHighlight.flavor ()
Returns the highlight flavor.
Returns
highlight flavor
Definition at line 83 of file LinkHighlight.java.
Referenced by org.onosproject.ui.topo.LinkHighlight.cssClasses().
String org.onosproject.ui.topo.LinkHighlight.label ()
Returns the label text.
Returns
label text
Definition at line 113 of file LinkHighlight.java.
Referenced by org.onosproject.ui.topo.LinkHighlight.setLabel().
Set<Mod> org.onosproject.ui.topo.LinkHighlight.mods ()
Returns the highlight modifications.
Returns
highlight modifications
Definition at line 92 of file LinkHighlight.java.
LinkHighlight org.onosproject.ui.topo.LinkHighlight.setLabel (String label)
Adds a label to be displayed on the link.
Parameters
label the label text
Returns
self, for chaining
Definition at line 73 of file LinkHighlight.java.
References org.onosproject.ui.topo.LinkHighlight.label().
Member Data Documentation
final Mod org.onosproject.ui.topo.LinkHighlight.MOD_ANIMATED = new Mod("animated") static
Denotes a link to be tagged with animated traffic ("marching ants").
Definition at line 145 of file LinkHighlight.java.
Referenced by org.onosproject.ui.topo.LinkHighlightTest.secondaryAnimatedWithLabel(), and org.onosproject.ui.topo.LinkHighlightTest.severalMods().
final Mod org.onosproject.ui.topo.LinkHighlight.MOD_OPTICAL = new Mod("optical") static
Denotes a link to be tagged as an optical link.
Definition at line 140 of file LinkHighlight.java.
Referenced by org.onosproject.ui.topo.LinkHighlightTest.primaryOptical(), and org.onosproject.ui.topo.LinkHighlightTest.severalMods().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/topo/LinkHighlight.java