onos: org.onosproject.bgpio.types.OSPFNonPseudonode Class Reference
org.onosproject.bgpio.types.OSPFNonPseudonode Class Reference
Provides implementation of OSPFNonPseudonode Tlv.
Public Member Functions
OSPFNonPseudonode (int routerID)
Constructor to initialize routerID.
int getrouterID ()
Returns RouterID.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of BGP Message to channel buffer.
short getType ()
Returns the Type of BGP Message.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static OSPFNonPseudonode of (final int routerID)
Returns object of this class with specified routerID.
static OSPFNonPseudonode read (ChannelBuffer cb)
Reads the channel buffer and returns object of OSPFNonPseudonode.
Static Public Attributes
static final short TYPE = 515
static final short LENGTH = 4
Detailed Description
Provides implementation of OSPFNonPseudonode Tlv.
Definition at line 29 of file OSPFNonPseudonode.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.OSPFNonPseudonode.OSPFNonPseudonode (int routerID)
Constructor to initialize routerID.
Parameters
routerID routerID
Definition at line 40 of file OSPFNonPseudonode.java.
Referenced by org.onosproject.bgpio.types.OSPFNonPseudonode.equals(), and org.onosproject.bgpio.types.OSPFNonPseudonode.of().
Member Function Documentation
int org.onosproject.bgpio.types.OSPFNonPseudonode.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 106 of file OSPFNonPseudonode.java.
References org.onosproject.bgpio.types.OSPFNonPseudonode.equals().
boolean org.onosproject.bgpio.types.OSPFNonPseudonode.equals (Object obj)
Definition at line 69 of file OSPFNonPseudonode.java.
References org.onosproject.bgpio.types.OSPFNonPseudonode.OSPFNonPseudonode().
Referenced by org.onosproject.bgpio.types.OSPFNonPseudonode.compareTo().
int org.onosproject.bgpio.types.OSPFNonPseudonode.getrouterID ()
Returns RouterID.
Returns
RouterID
Definition at line 59 of file OSPFNonPseudonode.java.
short org.onosproject.bgpio.types.OSPFNonPseudonode.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 101 of file OSPFNonPseudonode.java.
References org.onosproject.bgpio.types.OSPFNonPseudonode.TYPE.
int org.onosproject.bgpio.types.OSPFNonPseudonode.hashCode ()
Definition at line 64 of file OSPFNonPseudonode.java.
static OSPFNonPseudonode org.onosproject.bgpio.types.OSPFNonPseudonode.of (final int routerID) static
Returns object of this class with specified routerID.
Parameters
routerID routerID
Returns
object of OSPFNonPseudonode
Definition at line 50 of file OSPFNonPseudonode.java.
References org.onosproject.bgpio.types.OSPFNonPseudonode.OSPFNonPseudonode().
static OSPFNonPseudonode org.onosproject.bgpio.types.OSPFNonPseudonode.read (ChannelBuffer cb) static
Reads the channel buffer and returns object of OSPFNonPseudonode.
Parameters
cb ChannelBuffer
Returns
object of OSPFNonPseudonode
Definition at line 96 of file OSPFNonPseudonode.java.
String org.onosproject.bgpio.types.OSPFNonPseudonode.toString ()
Definition at line 114 of file OSPFNonPseudonode.java.
References org.onosproject.bgpio.types.OSPFNonPseudonode.LENGTH, and org.onosproject.bgpio.types.OSPFNonPseudonode.TYPE.
int org.onosproject.bgpio.types.OSPFNonPseudonode.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 82 of file OSPFNonPseudonode.java.
References org.onosproject.bgpio.types.OSPFNonPseudonode.LENGTH, and org.onosproject.bgpio.types.OSPFNonPseudonode.TYPE.
Member Data Documentation
final short org.onosproject.bgpio.types.OSPFNonPseudonode.LENGTH = 4 static
Definition at line 31 of file OSPFNonPseudonode.java.
Referenced by org.onosproject.bgpio.types.OSPFNonPseudonode.toString(), and org.onosproject.bgpio.types.OSPFNonPseudonode.write().
final short org.onosproject.bgpio.types.OSPFNonPseudonode.TYPE = 515 static
Definition at line 30 of file OSPFNonPseudonode.java.
Referenced by org.onosproject.bgpio.types.OSPFNonPseudonode.getType(), org.onosproject.bgpio.types.OSPFNonPseudonode.toString(), and org.onosproject.bgpio.types.OSPFNonPseudonode.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/OSPFNonPseudonode.java