onos: org.onlab.util.FrequencyTest Class Reference
org.onlab.util.FrequencyTest Class Reference
Public Member Functions
void testImmutability ()
Tests immutability of Frequency.
void testEquality ()
Tests equality of Frequency instances.
void testLessThan ()
Tests the first object is less than the second object.
void testGreaterThan ()
void testAdd ()
Tests add operation of two Frequencies.
void testSubtract ()
Tests subtract operation of two Frequencies.
void testMultiply ()
Tests multiply operation of Frequency.
Detailed Description
Definition at line 27 of file FrequencyTest.java.
Member Function Documentation
void org.onlab.util.FrequencyTest.testAdd ()
Tests add operation of two Frequencies.
Definition at line 76 of file FrequencyTest.java.
References org.onlab.util.Frequency.add().
void org.onlab.util.FrequencyTest.testEquality ()
Tests equality of Frequency instances.
Definition at line 49 of file FrequencyTest.java.
void org.onlab.util.FrequencyTest.testGreaterThan ()
Definition at line 67 of file FrequencyTest.java.
void org.onlab.util.FrequencyTest.testImmutability ()
Tests immutability of Frequency.
Definition at line 41 of file FrequencyTest.java.
void org.onlab.util.FrequencyTest.testLessThan ()
Tests the first object is less than the second object.
Definition at line 61 of file FrequencyTest.java.
void org.onlab.util.FrequencyTest.testMultiply ()
Tests multiply operation of Frequency.
Definition at line 100 of file FrequencyTest.java.
References org.onlab.util.Frequency.multiply().
void org.onlab.util.FrequencyTest.testSubtract ()
Tests subtract operation of two Frequencies.
Definition at line 88 of file FrequencyTest.java.
References org.onlab.util.Frequency.subtract().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/util/FrequencyTest.java