onos: org.onlab.packet.Ip4PrefixTest Class Reference
org.onlab.packet.Ip4PrefixTest Class Reference
Tests for class Ip4Prefix.
Public Member Functions
void testImmutable ()
Tests the immutability of Ip4Prefix.
void testAddressVersion ()
Tests the IPv4 prefix address version constant.
void testMaxMaskLength ()
Tests the maximum mask length.
void testVersion ()
Tests returning the IP version of the prefix.
void testAddressAndPrefixLengthIPv4 ()
Tests returning the IP address value and IP address prefix length of an IPv4 prefix.
void testValueOfForIntegerIPv4 ()
Tests valueOf() converter for IPv4 integer value.
void testInvalidValueOfIntegerNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 integer value and negative prefix length.
void testInvalidValueOfIntegerTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 integer value and too long prefix length.
void testValueOfByteArrayIPv4 ()
Tests valueOf() converter for IPv4 byte array.
void testInvalidValueOfNullArrayIPv4 ()
Tests invalid valueOf() converter for a null array for IPv4.
void testInvalidValueOfShortArrayIPv4 ()
Tests invalid valueOf() converter for a short array for IPv4.
void testInvalidValueOfByteArrayNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 byte array and negative prefix length.
void testInvalidValueOfByteArrayTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 byte array and too long prefix length.
void testValueOfAddressIPv4 ()
Tests valueOf() converter for IPv4 address.
void testInvalidValueOfNullAddress ()
Tests invalid valueOf() converter for a null IP address.
void testInvalidValueOfAddressNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 address and negative prefix length.
void testInvalidValueOfAddressTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 address and too long prefix length.
void testValueOfStringIPv4 ()
Tests valueOf() converter for IPv4 string.
void testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
void testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
void testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
void testInvalidValueOfStringNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 string and negative prefix length.
void testInvalidValueOfStringTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 string and too long prefix length.
void testContainsIpPrefixIPv4 ()
Tests IP prefix contains another IP prefix for IPv4.
void testContainsIpAddressIPv4 ()
Tests IP prefix contains IP address for IPv4.
void testEqualityIPv4 ()
Tests equality of Ip4Prefix for IPv4.
void testToStringIPv4 ()
Tests object string representation for IPv4.
Detailed Description
Tests for class Ip4Prefix.
Definition at line 31 of file Ip4PrefixTest.java.
Member Function Documentation
void org.onlab.packet.Ip4PrefixTest.testAddressAndPrefixLengthIPv4 ()
Tests returning the IP address value and IP address prefix length of an IPv4 prefix.
Definition at line 73 of file Ip4PrefixTest.java.
References org.onlab.packet.Ip4Prefix.address(), org.onlab.packet.IpPrefix.prefixLength(), and org.onlab.packet.Ip4Address.valueOf().
void org.onlab.packet.Ip4PrefixTest.testAddressVersion ()
Tests the IPv4 prefix address version constant.
Definition at line 44 of file Ip4PrefixTest.java.
References org.onlab.packet.Ip4Prefix.VERSION.
void org.onlab.packet.Ip4PrefixTest.testContainsIpAddressIPv4 ()
Tests IP prefix contains IP address for IPv4.
Definition at line 461 of file Ip4PrefixTest.java.
References org.onlab.packet.IpPrefix.contains(), and org.onlab.packet.Ip4Address.valueOf().
void org.onlab.packet.Ip4PrefixTest.testContainsIpPrefixIPv4 ()
Tests IP prefix contains another IP prefix for IPv4.
Definition at line 413 of file Ip4PrefixTest.java.
References org.onlab.packet.IpPrefix.contains(), and org.onlab.packet.Ip4Prefix.valueOf().
void org.onlab.packet.Ip4PrefixTest.testEqualityIPv4 ()
Tests equality of Ip4Prefix for IPv4.
Definition at line 497 of file Ip4PrefixTest.java.
References org.onlab.packet.Ip4Prefix.valueOf().
void org.onlab.packet.Ip4PrefixTest.testImmutable ()
Tests the immutability of Ip4Prefix.
Definition at line 36 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfAddressNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 address and negative prefix length.
Definition at line 298 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfAddressTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 address and too long prefix length.
Definition at line 311 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfByteArrayNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 byte array and negative prefix length.
Definition at line 223 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfByteArrayTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 byte array and too long prefix length.
Definition at line 236 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
Definition at line 367 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
Definition at line 379 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfIntegerNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 integer value and negative prefix length.
Definition at line 139 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfIntegerTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 integer value and too long prefix length.
Definition at line 150 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfNullAddress ()
Tests invalid valueOf() converter for a null IP address.
Definition at line 285 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfNullArrayIPv4 ()
Tests invalid valueOf() converter for a null array for IPv4.
Definition at line 198 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
Definition at line 355 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfShortArrayIPv4 ()
Tests invalid valueOf() converter for a short array for IPv4.
Definition at line 210 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfStringNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 string and negative prefix length.
Definition at line 392 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testInvalidValueOfStringTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 string and too long prefix length.
Definition at line 403 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testMaxMaskLength ()
Tests the maximum mask length.
Definition at line 52 of file Ip4PrefixTest.java.
References org.onlab.packet.Ip4Prefix.MAX_MASK_LENGTH.
void org.onlab.packet.Ip4PrefixTest.testToStringIPv4 ()
Tests object string representation for IPv4.
Definition at line 519 of file Ip4PrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.Ip4PrefixTest.testValueOfAddressIPv4 ()
Tests valueOf() converter for IPv4 address.
Definition at line 248 of file Ip4PrefixTest.java.
void org.onlab.packet.Ip4PrefixTest.testValueOfByteArrayIPv4 ()
Tests valueOf() converter for IPv4 byte array.
Definition at line 160 of file Ip4PrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.Ip4PrefixTest.testValueOfForIntegerIPv4 ()
Tests valueOf() converter for IPv4 integer value.
Definition at line 106 of file Ip4PrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.Ip4PrefixTest.testValueOfStringIPv4 ()
Tests valueOf() converter for IPv4 string.
Definition at line 323 of file Ip4PrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.Ip4PrefixTest.testVersion ()
Tests returning the IP version of the prefix.
Definition at line 60 of file Ip4PrefixTest.java.
References org.onlab.packet.IpPrefix.version().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/Ip4PrefixTest.java