onos: org.onosproject.net.DeviceId Class Reference
org.onosproject.net.DeviceId Class Reference
Immutable representation of a device identity.
Public Member Functions
URI uri ()
Returns the backing URI.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static DeviceId deviceId (URI uri)
Creates a device id using the supplied URI.
static DeviceId deviceId (String string)
Creates a device id using the supplied URI string.
Static Public Attributes
static final DeviceId NONE = deviceId("none:none")
Represents either no device, or an unspecified device.
Protected Member Functions
DeviceId ()
Detailed Description
Immutable representation of a device identity.
Definition at line 24 of file DeviceId.java.
Constructor & Destructor Documentation
org.onosproject.net.DeviceId.DeviceId () protected
Definition at line 42 of file DeviceId.java.
Referenced by org.onosproject.net.DeviceId.deviceId(), and org.onosproject.net.DeviceId.equals().
Member Function Documentation
static DeviceId org.onosproject.net.DeviceId.deviceId (URI uri) static
Creates a device id using the supplied URI.
Parameters
uri device URI
Returns
DeviceId
Definition at line 53 of file DeviceId.java.
References org.onosproject.net.DeviceId.DeviceId().
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.applyFromGlobalPool(), org.onosproject.routing.config.BgpPeer.BgpPeer(), org.onosproject.routing.config.BgpSpeaker.BgpSpeaker(), org.onosproject.provider.of.flow.impl.FlowEntryBuilder.build(), org.onosproject.cordvtn.CordVtnConfig.cordVtnNodes(), org.onosproject.net.ConnectPoint.deviceConnectPoint(), org.onosproject.net.DeviceId.deviceId(), org.onosproject.cli.net.DeviceRemoveCommand.execute(), org.onosproject.cli.net.LabelReleaseCommand.execute(), org.onosproject.cli.net.TunnelRemoveCommand.execute(), org.onosproject.cli.net.TunnelQueryCommand.execute(), org.onosproject.cli.net.TunnelReturnCommand.execute(), org.onosproject.cli.net.TunnelBorrowCommand.execute(), org.onosproject.cli.net.TunnelCreateCommand.execute(), org.onosproject.vtnrsc.cli.virtualport.VirtualPortCreateCommand.execute(), org.onosproject.vtnrsc.cli.virtualport.VirtualPortUpdateCommand.execute(), org.onosproject.cli.net.TableStatisticsCommand.getSortedTableStats(), org.onosproject.routing.config.InterfaceAddress.InterfaceAddress(), org.onosproject.incubator.net.domain.IntentDomainConfig.internalDevices(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.releaseToGlobalPool(), org.onosproject.rest.HostResourceTest.testHostsArray(), org.onosproject.rest.HostResourceTest.testSingleHostByIdFetch(), and org.onosproject.rest.HostResourceTest.testSingleHostByMacAndVlanFetch().
static DeviceId org.onosproject.net.DeviceId.deviceId (String string) static
Creates a device id using the supplied URI string.
Parameters
string device URI string
Returns
DeviceId
Definition at line 63 of file DeviceId.java.
References org.onosproject.net.DeviceId.deviceId().
boolean org.onosproject.net.DeviceId.equals (Object obj)
Definition at line 82 of file DeviceId.java.
References org.onosproject.net.DeviceId.DeviceId().
Referenced by org.onosproject.net.topology.impl.PathManager.getDisjointPaths(), and org.onosproject.net.topology.impl.PathManager.getPaths().
int org.onosproject.net.DeviceId.hashCode ()
Definition at line 77 of file DeviceId.java.
String org.onosproject.net.DeviceId.toString ()
Definition at line 95 of file DeviceId.java.
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.createDevicePool(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.getTunnelCount().
URI org.onosproject.net.DeviceId.uri ()
Returns the backing URI.
Returns
backing URI
Definition at line 72 of file DeviceId.java.
Member Data Documentation
final DeviceId org.onosproject.net.DeviceId.NONE = deviceId("none:none") static
Represents either no device, or an unspecified device.
Definition at line 29 of file DeviceId.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/DeviceId.java