onos: org.onlab.packet.TpPort Class Reference
org.onlab.packet.TpPort Class Reference
Representation of a transport layer port.
Public Member Functions
int toInt ()
Returns the integer value for this transport port.
boolean equals (Object obj)
int hashCode ()
String toString ()
Static Public Member Functions
static TpPort tpPort (int value)
Converts an integer into a TpPort.
Static Public Attributes
static final int MAX_PORT = 0xFFFF
static final int MIN_PORT = 0
Protected Member Functions
TpPort (int value)
Constructs a new TpPort.
Detailed Description
Representation of a transport layer port.
Definition at line 22 of file TpPort.java.
Constructor & Destructor Documentation
org.onlab.packet.TpPort.TpPort (int value) protected
Constructs a new TpPort.
Parameters
value the transport layer port
Definition at line 35 of file TpPort.java.
Referenced by org.onlab.packet.TpPort.equals(), and org.onlab.packet.TpPort.tpPort().
Member Function Documentation
boolean org.onlab.packet.TpPort.equals (Object obj)
Definition at line 69 of file TpPort.java.
References org.onlab.packet.TpPort.TpPort().
int org.onlab.packet.TpPort.hashCode ()
Definition at line 91 of file TpPort.java.
References obeliskHostCheck.port.
int org.onlab.packet.TpPort.toInt ()
Returns the integer value for this transport port.
Returns
an integer value
Definition at line 59 of file TpPort.java.
References obeliskHostCheck.port.
String org.onlab.packet.TpPort.toString ()
Definition at line 101 of file TpPort.java.
References obeliskHostCheck.port.
static TpPort org.onlab.packet.TpPort.tpPort (int value) static
Converts an integer into a TpPort.
Parameters
value an integer representing the transport layer port
Returns
a TpPort
Exceptions
IllegalArgumentException if the value is invalid
Definition at line 46 of file TpPort.java.
References org.onlab.packet.TpPort.MAX_PORT, and org.onlab.packet.TpPort.TpPort().
Referenced by org.onosproject.net.flow.criteria.Criteria.matchSctpDst(), org.onosproject.net.flow.criteria.Criteria.matchSctpSrc(), org.onosproject.net.flow.criteria.Criteria.matchTcpDst(), org.onosproject.net.flow.criteria.Criteria.matchTcpSrc(), org.onosproject.net.flow.criteria.Criteria.matchUdpDst(), org.onosproject.net.flow.criteria.Criteria.matchUdpSrc(), org.onosproject.net.flow.instructions.Instructions.modTcpDst(), org.onosproject.net.flow.instructions.Instructions.modTcpSrc(), org.onosproject.net.flow.instructions.Instructions.modUdpDst(), org.onosproject.net.flow.instructions.Instructions.modUdpSrc(), org.onosproject.bgprouter.TunnellingConnectivityManager.notifySwitchAvailable(), and org.onosproject.net.flow.DefaultTrafficSelectorTest.testCriteriaCreation().
Member Data Documentation
final int org.onlab.packet.TpPort.MAX_PORT = 0xFFFF static
Definition at line 27 of file TpPort.java.
Referenced by org.onlab.packet.TpPort.tpPort().
final int org.onlab.packet.TpPort.MIN_PORT = 0 static
Definition at line 28 of file TpPort.java.
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/TpPort.java