onos: org.onosproject.bgpio.types.AutonomousSystemTlv Class Reference
org.onosproject.bgpio.types.AutonomousSystemTlv Class Reference
Provides Autonomous System Tlv which contains opaque value (32 Bit AS Number).
Public Member Functions
AutonomousSystemTlv (int asNum)
Constructor to initialize asNum.
int getAsNum ()
Returns opaque value of AS Number.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of BGP Message to channel buffer.
short getType ()
Returns the Type of BGP Message.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static AutonomousSystemTlv of (final int asNum)
Returns object of this class with specified asNum.
static AutonomousSystemTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of AutonomousSystemTlv.
Static Public Attributes
static final short TYPE = 512
static final short LENGTH = 4
Detailed Description
Provides Autonomous System Tlv which contains opaque value (32 Bit AS Number).
Definition at line 27 of file AutonomousSystemTlv.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.AutonomousSystemTlv.AutonomousSystemTlv (int asNum)
Constructor to initialize asNum.
Parameters
asNum 32 Bit AS Number
Definition at line 49 of file AutonomousSystemTlv.java.
Referenced by org.onosproject.bgpio.types.AutonomousSystemTlv.equals(), and org.onosproject.bgpio.types.AutonomousSystemTlv.of().
Member Function Documentation
int org.onosproject.bgpio.types.AutonomousSystemTlv.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 115 of file AutonomousSystemTlv.java.
References org.onosproject.bgpio.types.AutonomousSystemTlv.equals().
boolean org.onosproject.bgpio.types.AutonomousSystemTlv.equals (Object obj)
Definition at line 78 of file AutonomousSystemTlv.java.
References org.onosproject.bgpio.types.AutonomousSystemTlv.AutonomousSystemTlv().
Referenced by org.onosproject.bgpio.types.AutonomousSystemTlv.compareTo().
int org.onosproject.bgpio.types.AutonomousSystemTlv.getAsNum ()
Returns opaque value of AS Number.
Returns
opaque value of AS Number
Definition at line 68 of file AutonomousSystemTlv.java.
short org.onosproject.bgpio.types.AutonomousSystemTlv.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 110 of file AutonomousSystemTlv.java.
References org.onosproject.bgpio.types.AutonomousSystemTlv.TYPE.
int org.onosproject.bgpio.types.AutonomousSystemTlv.hashCode ()
Definition at line 73 of file AutonomousSystemTlv.java.
static AutonomousSystemTlv org.onosproject.bgpio.types.AutonomousSystemTlv.of (final int asNum) static
Returns object of this class with specified asNum.
Parameters
asNum 32 Bit AS Number
Returns
object of AutonomousSystemTlv
Definition at line 59 of file AutonomousSystemTlv.java.
References org.onosproject.bgpio.types.AutonomousSystemTlv.AutonomousSystemTlv().
static AutonomousSystemTlv org.onosproject.bgpio.types.AutonomousSystemTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of AutonomousSystemTlv.
Parameters
c ChannelBuffer
Returns
object of AutonomousSystemTlv
Definition at line 105 of file AutonomousSystemTlv.java.
String org.onosproject.bgpio.types.AutonomousSystemTlv.toString ()
Definition at line 123 of file AutonomousSystemTlv.java.
References org.onosproject.bgpio.types.AutonomousSystemTlv.LENGTH, and org.onosproject.bgpio.types.AutonomousSystemTlv.TYPE.
int org.onosproject.bgpio.types.AutonomousSystemTlv.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 91 of file AutonomousSystemTlv.java.
References org.onosproject.bgpio.types.AutonomousSystemTlv.LENGTH, and org.onosproject.bgpio.types.AutonomousSystemTlv.TYPE.
Member Data Documentation
final short org.onosproject.bgpio.types.AutonomousSystemTlv.LENGTH = 4 static
Definition at line 40 of file AutonomousSystemTlv.java.
Referenced by org.onosproject.provider.bgp.topology.impl.BgpTopologyProviderTest.bgpTopologyProviderTestAddDevice1(), org.onosproject.provider.bgp.topology.impl.BgpTopologyProviderTest.bgpTopologyProviderTestAddDevice2(), org.onosproject.provider.bgp.topology.impl.BgpTopologyProviderTest.bgpTopologyProviderTestAddDevice3(), org.onosproject.bgpio.types.AutonomousSystemTlv.toString(), and org.onosproject.bgpio.types.AutonomousSystemTlv.write().
final short org.onosproject.bgpio.types.AutonomousSystemTlv.TYPE = 512 static
Definition at line 39 of file AutonomousSystemTlv.java.
Referenced by org.onosproject.provider.bgp.topology.impl.BgpTopologyProviderTest.bgpTopologyProviderTestAddDevice1(), org.onosproject.provider.bgp.topology.impl.BgpTopologyProviderTest.bgpTopologyProviderTestAddDevice2(), org.onosproject.provider.bgp.topology.impl.BgpTopologyProviderTest.bgpTopologyProviderTestAddDevice3(), org.onosproject.bgpio.types.AutonomousSystemTlv.getType(), org.onosproject.bgpio.types.AutonomousSystemTlv.toString(), and org.onosproject.bgpio.types.AutonomousSystemTlv.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/AutonomousSystemTlv.java