onos: org.onosproject.ovsdb.rfc.schema.TableSchema Class Reference
org.onosproject.ovsdb.rfc.schema.TableSchema Class Reference
A schema for the table represented by table-schema, which consists of a set of columns.
Public Member Functions
TableSchema (String name, Map< String, ColumnSchema > columnSchemas)
Constructs a TableSchema object.
String name ()
Returns the name of table.
Map< String, ColumnSchema > columnSchemas ()
Returns a map of ColumnSchema.
Set< String > getColumnNames ()
Returns a set of column name.
boolean hasColumn (String columnName)
Determine whether contain the column.
ColumnSchema getColumnSchema (String columnName)
Returns the ColumnSchema whose name is the columnName.
void generateInitializationColumns ()
Refer to RFC 7047 Section 3.2.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
A schema for the table represented by table-schema, which consists of a set of columns.
Definition at line 32 of file TableSchema.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.schema.TableSchema.TableSchema (String name, Map< String, ColumnSchema > columnSchemas)
Constructs a TableSchema object.
Parameters
name the name of table
columnSchemas a map of ColumnSchema
Definition at line 42 of file TableSchema.java.
References org.onosproject.ovsdb.rfc.schema.TableSchema.columnSchemas(), and org.onosproject.ovsdb.rfc.schema.TableSchema.name().
Referenced by org.onosproject.ovsdb.rfc.schema.TableSchema.equals().
Member Function Documentation
Map<String, ColumnSchema> org.onosproject.ovsdb.rfc.schema.TableSchema.columnSchemas ()
Returns a map of ColumnSchema.
Returns
a map of ColumnSchema
Definition at line 61 of file TableSchema.java.
Referenced by org.onosproject.ovsdb.rfc.schema.TableSchema.hashCode(), org.onosproject.ovsdb.rfc.schema.TableSchema.TableSchema(), and org.onosproject.ovsdb.rfc.schema.TableSchema.toString().
boolean org.onosproject.ovsdb.rfc.schema.TableSchema.equals (Object obj)
Definition at line 112 of file TableSchema.java.
References create-flow.name, and org.onosproject.ovsdb.rfc.schema.TableSchema.TableSchema().
void org.onosproject.ovsdb.rfc.schema.TableSchema.generateInitializationColumns ()
Refer to RFC 7047 Section 3.2.
generate initialization columns in each table namely _uuid and _version.
Definition at line 95 of file TableSchema.java.
Set<String> org.onosproject.ovsdb.rfc.schema.TableSchema.getColumnNames ()
Returns a set of column name.
Returns
a set of column name
Definition at line 69 of file TableSchema.java.
ColumnSchema org.onosproject.ovsdb.rfc.schema.TableSchema.getColumnSchema (String columnName)
Returns the ColumnSchema whose name is the columnName.
Parameters
columnName column name
Returns
ColumnSchema
Definition at line 87 of file TableSchema.java.
boolean org.onosproject.ovsdb.rfc.schema.TableSchema.hasColumn (String columnName)
Determine whether contain the column.
Parameters
columnName column name
Returns
boolean
Definition at line 78 of file TableSchema.java.
int org.onosproject.ovsdb.rfc.schema.TableSchema.hashCode ()
Definition at line 107 of file TableSchema.java.
References org.onosproject.ovsdb.rfc.schema.TableSchema.columnSchemas(), and org.onosproject.ovsdb.rfc.schema.TableSchema.name().
String org.onosproject.ovsdb.rfc.schema.TableSchema.name ()
Returns the name of table.
Returns
the name of table
Definition at line 53 of file TableSchema.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.ovsdb.rfc.schema.TableSchema.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), org.onosproject.ovsdb.rfc.schema.TableSchema.TableSchema(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.ovsdb.rfc.schema.TableSchema.toString().
String org.onosproject.ovsdb.rfc.schema.TableSchema.toString ()
Definition at line 125 of file TableSchema.java.
References org.onosproject.ovsdb.rfc.schema.TableSchema.columnSchemas(), and org.onosproject.ovsdb.rfc.schema.TableSchema.name().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/schema/TableSchema.java