onos: org.onlab.nio.service.DefaultMessage Class Reference
org.onlab.nio.service.DefaultMessage Class Reference
Default message.
Public Member Functions
long id ()
Returns message id.
Endpoint sender ()
Returns message sender.
String type ()
Returns message type.
byte[] payload ()
Returns message payload.
String toString ()
Public Member Functions inherited from org.onlab.nio.AbstractMessage
int length ()
Gets the message length in bytes.
Additional Inherited Members
Protected Attributes inherited from org.onlab.nio.AbstractMessage
int length
Detailed Description
Default message.
Definition at line 31 of file DefaultMessage.java.
Member Function Documentation
long org.onlab.nio.service.DefaultMessage.id ()
Returns message id.
Returns
message id
Definition at line 64 of file DefaultMessage.java.
byte [] org.onlab.nio.service.DefaultMessage.payload ()
Returns message payload.
Returns
payload
Definition at line 91 of file DefaultMessage.java.
Referenced by org.onlab.nio.service.DefaultMessage.toString().
Endpoint org.onlab.nio.service.DefaultMessage.sender ()
Returns message sender.
Returns
message sender
Definition at line 73 of file DefaultMessage.java.
String org.onlab.nio.service.DefaultMessage.toString ()
Definition at line 96 of file DefaultMessage.java.
References org.onlab.nio.service.DefaultMessage.payload(), and org.onlab.nio.service.DefaultMessage.type().
String org.onlab.nio.service.DefaultMessage.type ()
Returns message type.
Returns
message type
Definition at line 82 of file DefaultMessage.java.
Referenced by org.onlab.nio.service.DefaultMessage.toString().
The documentation for this class was generated from the following file:
utils/nio/src/main/java/org/onlab/nio/service/DefaultMessage.java