onos: org.onlab.packet.ICMP6 Class Reference
org.onlab.packet.ICMP6 Class Reference
Implements ICMPv6 packet format.
Public Member Functions
byte getIcmpType ()
Gets ICMP6 type.
ICMP6 setIcmpType (final byte icmpType)
Sets ICMP6 type.
byte getIcmpCode ()
Gets ICMP6 code.
ICMP6 setIcmpCode (final byte icmpCode)
Sets ICMP6 code.
short getChecksum ()
Gets checksum.
ICMP6 setChecksum (final short checksum)
Sets checksum.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (final byte[] data, final int offset, final int length)
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
Static Public Member Functions
static Deserializer< ICMP6 > deserializer ()
Deserializer function for ICMPv6 packets.
Static Public Attributes
static final byte HEADER_LENGTH = 4
static final byte DEST_UNREACH = (byte) 0x01
Destination Unreachable.
static final byte PKT_TOO_BIG = (byte) 0x02
Packet Too Big.
static final byte TIME_EXCEED = (byte) 0x03
Time Exceeded.
static final byte PARAM_ERR = (byte) 0x04
Parameter Problem.
static final byte ECHO_REQUEST = (byte) 0x80
Echo Request.
static final byte ECHO_REPLY = (byte) 0x81
Echo Reply.
static final byte MCAST_QUERY = (byte) 0x82
Multicast Listener Query.
static final byte MCAST_REPORT = (byte) 0x83
Multicast Listener Report.
static final byte MCAST_DONE = (byte) 0x84
Multicast Listener Done.
static final byte ROUTER_SOLICITATION = (byte) 0x85
Router Solicitation.
static final byte ROUTER_ADVERTISEMENT = (byte) 0x86
Router Advertisement.
static final byte NEIGHBOR_SOLICITATION = (byte) 0x87
Neighbor Solicitation.
static final byte NEIGHBOR_ADVERTISEMENT = (byte) 0x88
Neighbor Advertisement.
static final byte REDIRECT = (byte) 0x89
Redirect Message.
static final byte NO_ROUTE = (byte) 0x00
No route to destination.
static final byte COMM_PROHIBIT = (byte) 0x01
Communication with destination administratively prohibited.
static final byte BEYOND_SCOPE = (byte) 0x02
Beyond scope of source address.
static final byte ADDR_UNREACH = (byte) 0x03
Address unreachable.
static final byte PORT_UNREACH = (byte) 0x04
Port unreachable.
static final byte FAIL_POLICY = (byte) 0x05
Source address failed ingress/egress policy.
static final byte REJECT_ROUTE = (byte) 0x06
Reject route to destination.
static final byte SRC_ROUTING_HEADER_ERR = (byte) 0x07
Error in Source Routing Header.
static final byte HOP_LIMIT_EXCEED = (byte) 0x00
Hop limit exceeded in transit.
static final byte DEFRAG_TIME_EXCEED = (byte) 0x01
Fragment reassembly time exceeded.
static final byte HDR_FIELD_ERR = (byte) 0x00
Erroneous header field encountered.
static final byte NEXT_HEADER_ERR = (byte) 0x01
Unrecognized Next Header type encountered.
static final byte IPV6_OPT_ERR = (byte) 0x01
Unrecognized IPv6 option encountered.
static final Map< Byte,
Deserializer<?extends IPacket > > TYPE_DESERIALIZER_MAP
Protected Attributes
byte icmpType
byte icmpCode
short checksum
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements ICMPv6 packet format.
(RFC 4443)
Definition at line 37 of file ICMP6.java.
Member Function Documentation
IPacket org.onlab.packet.ICMP6.deserialize (final byte[] data, final int offset, final int length)
Definition at line 268 of file ICMP6.java.
References org.onlab.packet.ICMP6.deserializer(), org.onlab.packet.ICMP6.icmpType, find-link-in-cluster.length, and org.onlab.packet.ICMP6.TYPE_DESERIALIZER_MAP.
static Deserializer<ICMP6> org.onlab.packet.ICMP6.deserializer () static
Deserializer function for ICMPv6 packets.
Returns
deserializer function
Definition at line 341 of file ICMP6.java.
References org.onlab.packet.ICMP6.HEADER_LENGTH, org.onlab.packet.ICMP6.icmpType, find-link-in-cluster.length, and org.onlab.packet.ICMP6.TYPE_DESERIALIZER_MAP.
Referenced by org.onlab.packet.ICMP6.deserialize().
boolean org.onlab.packet.ICMP6.equals (final Object obj)
Definition at line 313 of file ICMP6.java.
References org.onlab.packet.ICMP6.checksum, org.onlab.packet.ICMP6.icmpCode, and org.onlab.packet.ICMP6.icmpType.
Referenced by org.onlab.packet.ICMP6Test.testEqual().
short org.onlab.packet.ICMP6.getChecksum ()
Gets checksum.
Returns
the checksum
Definition at line 164 of file ICMP6.java.
Referenced by org.onlab.packet.ICMP6Test.testDeserialize().
byte org.onlab.packet.ICMP6.getIcmpCode ()
Gets ICMP6 code.
Returns
the ICMP6 code
Definition at line 144 of file ICMP6.java.
Referenced by org.onlab.packet.ICMP6Test.testDeserialize().
byte org.onlab.packet.ICMP6.getIcmpType ()
Gets ICMP6 type.
Returns
the ICMP6 type
Definition at line 124 of file ICMP6.java.
Referenced by org.onlab.packet.ICMP6Test.testDeserialize().
int org.onlab.packet.ICMP6.hashCode ()
Definition at line 298 of file ICMP6.java.
byte [] org.onlab.packet.ICMP6.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 180 of file ICMP6.java.
References org.onlab.packet.ICMP6.checksum, org.onlab.packet.ICMP6.HEADER_LENGTH, find-link-in-cluster.length, org.onlab.packet.BasePacket.parent, org.onlab.packet.BasePacket.payload, and org.onlab.packet.IPv6.PROTOCOL_ICMP6.
Referenced by org.onlab.packet.ICMP6Test.testSerialize().
ICMP6 org.onlab.packet.ICMP6.setChecksum (final short checksum)
Sets checksum.
Parameters
checksum the checksum to set
Returns
this
Definition at line 174 of file ICMP6.java.
References org.onlab.packet.ICMP6.checksum.
ICMP6 org.onlab.packet.ICMP6.setIcmpCode (final byte icmpCode)
Sets ICMP6 code.
Parameters
icmpCode the ICMP6 code to set
Returns
this
Definition at line 154 of file ICMP6.java.
References org.onlab.packet.ICMP6.icmpCode.
ICMP6 org.onlab.packet.ICMP6.setIcmpType (final byte icmpType)
Sets ICMP6 type.
Parameters
icmpType the ICMP type to set
Returns
this
Definition at line 134 of file ICMP6.java.
References org.onlab.packet.ICMP6.icmpType.
Member Data Documentation
final byte org.onlab.packet.ICMP6.ADDR_UNREACH = (byte) 0x03 static
Address unreachable.
Definition at line 78 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.BEYOND_SCOPE = (byte) 0x02 static
Beyond scope of source address.
Definition at line 76 of file ICMP6.java.
short org.onlab.packet.ICMP6.checksum protected
Definition at line 115 of file ICMP6.java.
Referenced by org.onlab.packet.ICMP6.equals(), org.onlab.packet.ICMP6.serialize(), and org.onlab.packet.ICMP6.setChecksum().
final byte org.onlab.packet.ICMP6.COMM_PROHIBIT = (byte) 0x01 static
Communication with destination administratively prohibited.
Definition at line 74 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.DEFRAG_TIME_EXCEED = (byte) 0x01 static
Fragment reassembly time exceeded.
Definition at line 92 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.DEST_UNREACH = (byte) 0x01 static
Destination Unreachable.
Definition at line 42 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.ECHO_REPLY = (byte) 0x81 static
Echo Reply.
Definition at line 52 of file ICMP6.java.
Referenced by org.onlab.packet.ICMP6Test.testEqual().
final byte org.onlab.packet.ICMP6.ECHO_REQUEST = (byte) 0x80 static
Echo Request.
Definition at line 50 of file ICMP6.java.
Referenced by org.onlab.packet.ICMP6Test.testDeserialize(), org.onlab.packet.ICMP6Test.testEqual(), and org.onlab.packet.ICMP6Test.testSerialize().
final byte org.onlab.packet.ICMP6.FAIL_POLICY = (byte) 0x05 static
Source address failed ingress/egress policy.
Definition at line 82 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.HDR_FIELD_ERR = (byte) 0x00 static
Erroneous header field encountered.
Definition at line 96 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.HEADER_LENGTH = 4 static
Definition at line 38 of file ICMP6.java.
Referenced by org.onlab.packet.ICMP6.deserializer(), and org.onlab.packet.ICMP6.serialize().
final byte org.onlab.packet.ICMP6.HOP_LIMIT_EXCEED = (byte) 0x00 static
Hop limit exceeded in transit.
Definition at line 90 of file ICMP6.java.
byte org.onlab.packet.ICMP6.icmpCode protected
Definition at line 114 of file ICMP6.java.
Referenced by org.onlab.packet.ICMP6.equals(), and org.onlab.packet.ICMP6.setIcmpCode().
byte org.onlab.packet.ICMP6.icmpType protected
Definition at line 113 of file ICMP6.java.
Referenced by org.onlab.packet.ICMP6.deserialize(), org.onlab.packet.ICMP6.deserializer(), org.onlab.packet.ICMP6.equals(), and org.onlab.packet.ICMP6.setIcmpType().
final byte org.onlab.packet.ICMP6.IPV6_OPT_ERR = (byte) 0x01 static
Unrecognized IPv6 option encountered.
Definition at line 100 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.MCAST_DONE = (byte) 0x84 static
Multicast Listener Done.
Definition at line 58 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.MCAST_QUERY = (byte) 0x82 static
Multicast Listener Query.
Definition at line 54 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.MCAST_REPORT = (byte) 0x83 static
Multicast Listener Report.
Definition at line 56 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.NEIGHBOR_ADVERTISEMENT = (byte) 0x88 static
Neighbor Advertisement.
Definition at line 66 of file ICMP6.java.
Referenced by org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyKnownIpv6(), and org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestForUsIpv6().
final byte org.onlab.packet.ICMP6.NEIGHBOR_SOLICITATION = (byte) 0x87 static
Neighbor Solicitation.
Definition at line 64 of file ICMP6.java.
Referenced by org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testForwardFloodIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testForwardToHostIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyDifferentVlanIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyExternalPortBadRequestIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyKnownIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestForUsIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUsIpv6(), and org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyUnknownIpv6().
final byte org.onlab.packet.ICMP6.NEXT_HEADER_ERR = (byte) 0x01 static
Unrecognized Next Header type encountered.
Definition at line 98 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.NO_ROUTE = (byte) 0x00 static
No route to destination.
Definition at line 72 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.PARAM_ERR = (byte) 0x04 static
Parameter Problem.
Definition at line 48 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.PKT_TOO_BIG = (byte) 0x02 static
Packet Too Big.
Definition at line 44 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.PORT_UNREACH = (byte) 0x04 static
Port unreachable.
Definition at line 80 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.REDIRECT = (byte) 0x89 static
Redirect Message.
Definition at line 68 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.REJECT_ROUTE = (byte) 0x06 static
Reject route to destination.
Definition at line 84 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.ROUTER_ADVERTISEMENT = (byte) 0x86 static
Router Advertisement.
Definition at line 62 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.ROUTER_SOLICITATION = (byte) 0x85 static
Router Solicitation.
Definition at line 60 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.SRC_ROUTING_HEADER_ERR = (byte) 0x07 static
Error in Source Routing Header.
Definition at line 86 of file ICMP6.java.
final byte org.onlab.packet.ICMP6.TIME_EXCEED = (byte) 0x03 static
Time Exceeded.
Definition at line 46 of file ICMP6.java.
final Map<Byte, Deserializer<? extends IPacket> > org.onlab.packet.ICMP6.TYPE_DESERIALIZER_MAP static
Initial value:
=
            new HashMap<>()
Definition at line 102 of file ICMP6.java.
Referenced by org.onlab.packet.ICMP6.deserialize(), and org.onlab.packet.ICMP6.deserializer().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ICMP6.java