onos: org.onosproject.provider.of.flow.impl.FlowModBuilderVer13 Class Reference
org.onosproject.provider.of.flow.impl.FlowModBuilderVer13 Class Reference
Flow mod builder for OpenFlow 1.3+.
Public Member Functions
OFFlowAdd buildFlowAdd ()
Builds an ADD flow mod.
OFFlowMod buildFlowMod ()
Builds a MODIFY flow mod.
OFFlowDelete buildFlowDel ()
Builds a DELETE flow mod.
Protected Member Functions
FlowModBuilderVer13 (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService)
Constructor for a flow mod builder for OpenFlow 1.3.
Protected Member Functions inherited from org.onosproject.provider.of.flow.impl.FlowModBuilder
FlowModBuilder (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService)
Constructs a flow mod builder.
Match buildMatch ()
Builds the match for the flow mod.
FlowRule flowRule ()
Returns the flow rule for this builder.
OFFactory factory ()
Returns the factory used for building OpenFlow constructs.
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.provider.of.flow.impl.FlowModBuilder
static FlowModBuilder builder (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService)
Creates a new flow mod builder.
Protected Attributes inherited from org.onosproject.provider.of.flow.impl.FlowModBuilder
final Long xid
final Optional< DriverService > driverService
Detailed Description
Flow mod builder for OpenFlow 1.3+.
Definition at line 92 of file FlowModBuilderVer13.java.
Constructor & Destructor Documentation
org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.FlowModBuilderVer13 (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService) protected
Constructor for a flow mod builder for OpenFlow 1.3.
Parameters
flowRule the flow rule to transform into a flow mod
factory the OpenFlow factory to use to build the flow mod
xid the transaction ID
driverService the device driver service
Definition at line 108 of file FlowModBuilderVer13.java.
Member Function Documentation
OFFlowAdd org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd () virtual
Builds an ADD flow mod.
Returns
the flow mod
Implements org.onosproject.provider.of.flow.impl.FlowModBuilder.
Definition at line 117 of file FlowModBuilderVer13.java.
References org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.net.flow.TrafficTreatment.clearedDeferred(), org.onosproject.net.flow.TrafficTreatment.deferred(), org.onosproject.provider.of.flow.impl.FlowModBuilder.factory(), org.onosproject.provider.of.flow.impl.FlowModBuilder.flowRule(), org.onosproject.net.flow.TrafficTreatment.immediate(), org.onosproject.net.flow.TrafficTreatment.metered(), org.onosproject.net.flow.TrafficTreatment.tableTransition(), org.onosproject.net.flow.TrafficTreatment.writeMetadata(), and org.onosproject.provider.of.flow.impl.FlowModBuilder.xid.
OFFlowDelete org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowDel () virtual
Builds a DELETE flow mod.
Returns
the flow mod
Implements org.onosproject.provider.of.flow.impl.FlowModBuilder.
Definition at line 203 of file FlowModBuilderVer13.java.
References org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.provider.of.flow.impl.FlowModBuilder.factory(), org.onosproject.provider.of.flow.impl.FlowModBuilder.flowRule(), and org.onosproject.provider.of.flow.impl.FlowModBuilder.xid.
OFFlowMod org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod () virtual
Builds a MODIFY flow mod.
Returns
the flow mod
Implements org.onosproject.provider.of.flow.impl.FlowModBuilder.
Definition at line 160 of file FlowModBuilderVer13.java.
References org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.net.flow.TrafficTreatment.clearedDeferred(), org.onosproject.net.flow.TrafficTreatment.deferred(), org.onosproject.provider.of.flow.impl.FlowModBuilder.factory(), org.onosproject.provider.of.flow.impl.FlowModBuilder.flowRule(), org.onosproject.net.flow.TrafficTreatment.immediate(), org.onosproject.net.flow.TrafficTreatment.metered(), org.onosproject.net.flow.TrafficTreatment.tableTransition(), org.onosproject.net.flow.TrafficTreatment.writeMetadata(), and org.onosproject.provider.of.flow.impl.FlowModBuilder.xid.
The documentation for this class was generated from the following file:
providers/openflow/flow/src/main/java/org/onosproject/provider/of/flow/impl/FlowModBuilderVer13.java