onos: org.onosproject.pcepio.types.MaximumLinkBandwidthTlv Class Reference
org.onosproject.pcepio.types.MaximumLinkBandwidthTlv Class Reference
Provide the Maximum Link Bandwidth.
Public Member Functions
MaximumLinkBandwidthTlv (int rawValue)
Constructor to initialize rawValue.
int getInt ()
Returns value of Maximum Link Bandwidth.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static MaximumLinkBandwidthTlv of (final int raw)
Returns newly created MaximumLinkBandwidthTlv object.
static MaximumLinkBandwidthTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of MaximumLinkBandwidthTlv.
Static Public Attributes
static final short TYPE = 9
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(MaximumLinkBandwidthTlv.class)
Detailed Description
Provide the Maximum Link Bandwidth.
Definition at line 30 of file MaximumLinkBandwidthTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.MaximumLinkBandwidthTlv (int rawValue)
Constructor to initialize rawValue.
Parameters
rawValue Maximum-Link-Bandwidth
Definition at line 55 of file MaximumLinkBandwidthTlv.java.
Referenced by org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.equals(), and org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.equals (Object obj)
Definition at line 99 of file MaximumLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.MaximumLinkBandwidthTlv().
int org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.getInt ()
Returns value of Maximum Link Bandwidth.
Returns
rawValue Maximum Link Bandwidth
Definition at line 74 of file MaximumLinkBandwidthTlv.java.
short org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 89 of file MaximumLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.LENGTH.
short org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 84 of file MaximumLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 79 of file MaximumLinkBandwidthTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.hashCode ()
Definition at line 94 of file MaximumLinkBandwidthTlv.java.
static MaximumLinkBandwidthTlv org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.of (final int raw) static
Returns newly created MaximumLinkBandwidthTlv object.
Parameters
raw value of Maximum-Link-Bandwidth
Returns
object of MaximumLinkBandwidthTlv
Definition at line 65 of file MaximumLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.MaximumLinkBandwidthTlv().
static MaximumLinkBandwidthTlv org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of MaximumLinkBandwidthTlv.
Parameters
c input channel buffer
Returns
object of MaximumLinkBandwidthTlv
Definition at line 125 of file MaximumLinkBandwidthTlv.java.
String org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.toString ()
Definition at line 130 of file MaximumLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.LENGTH, and org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.TYPE.
int org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 111 of file MaximumLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.LENGTH, and org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.LENGTH = 4 static
Definition at line 45 of file MaximumLinkBandwidthTlv.java.
Referenced by org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.getLength(), org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.toString(), and org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.write().
final Logger org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.log = LoggerFactory.getLogger(MaximumLinkBandwidthTlv.class) static protected
Definition at line 42 of file MaximumLinkBandwidthTlv.java.
final short org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.TYPE = 9 static
Definition at line 44 of file MaximumLinkBandwidthTlv.java.
Referenced by org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.getType(), org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.toString(), and org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/MaximumLinkBandwidthTlv.java