onos: org.onlab.stc.Scenario Class Reference
org.onlab.stc.Scenario Class Reference
Representation of a re-usable test scenario.
Public Member Functions
String name ()
Returns the scenario name.
String description ()
Returns the scenario description.
HierarchicalConfiguration definition ()
Returns the scenario definition.
Static Public Member Functions
static Scenario loadScenario (HierarchicalConfiguration definition)
Loads a new scenario from the specified hierarchical configuration.
static Scenario loadScenario (InputStream stream)
Loads a new scenario from the specified input stream.
Detailed Description
Representation of a re-usable test scenario.
Definition at line 30 of file Scenario.java.
Member Function Documentation
HierarchicalConfiguration org.onlab.stc.Scenario.definition ()
Returns the scenario definition.
Returns
scenario definition
Definition at line 102 of file Scenario.java.
String org.onlab.stc.Scenario.description ()
Returns the scenario description.
Returns
scenario description
Definition at line 93 of file Scenario.java.
static Scenario org.onlab.stc.Scenario.loadScenario (HierarchicalConfiguration definition) static
Loads a new scenario from the specified hierarchical configuration.
Parameters
definition scenario definition
Returns
loaded scenario
Definition at line 53 of file Scenario.java.
Referenced by org.onlab.stc.Scenario.loadScenario().
static Scenario org.onlab.stc.Scenario.loadScenario (InputStream stream) static
Loads a new scenario from the specified input stream.
Parameters
stream scenario definition stream
Returns
loaded scenario
Definition at line 66 of file Scenario.java.
References org.onlab.stc.Scenario.loadScenario().
String org.onlab.stc.Scenario.name ()
Returns the scenario name.
Returns
scenario name
Definition at line 84 of file Scenario.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
The documentation for this class was generated from the following file:
utils/stc/src/main/java/org/onlab/stc/Scenario.java