onos: org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient Class Reference
org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient Class Reference
An representation of an ovsdb client.
Public Member Functions
DefaultOvsdbClient (OvsdbNodeId nodeId)
Creates an OvsdbClient.
OvsdbNodeId nodeId ()
Gets the node identifier.
void setAgent (OvsdbAgent agent)
Sets the ovsdb agent to be used.
void setChannel (Channel channel)
Sets the associated Netty channel for this node.
void setConnection (boolean connected)
Sets whether the node is connected.
boolean isConnected ()
Checks if the node is still connected.
void nodeAdded ()
Announces to the ovsdb agent that this node has added.
void nodeRemoved ()
Announces to the ovsdb agent that this node has removed.
Row getRow (String dbName, String tableName, String uuid)
Gets the ovsdb row.
void removeRow (String dbName, String tableName, String uuid)
Removes the OVSDB row from local OVSDB store.
void updateOvsdbStore (String dbName, String tableName, String uuid, Row row)
Updates the local OVSDB store.
String getPortUuid (String portName, String bridgeUuid)
Gets the Port uuid.
String getInterfaceUuid (String portUuid, String portName)
Gets the Interface uuid.
String getBridgeUuid (String bridgeName)
Gets the Bridge uuid.
String getControllerUuid (String controllerName, String controllerTarget)
Gets the Controller uuid.
String getOvsUuid (String dbName)
Gets the OVS uuid.
void createPort (String bridgeName, String portName)
Creates a port.
void dropPort (String bridgeName, String portName)
Drops a port.
void createBridge (String bridgeName)
Creates a bridge.
void createBridge (String bridgeName, String dpid, String exPortName)
Creates a bridge.
boolean createBridge (String bridgeName, String dpid, List< ControllerInfo > controllers)
Creates a bridge with given name and dpid.
void setControllersWithUUID (UUID bridgeUuid, List< ControllerInfo > controllers)
Sets the Controllers for the specified bridge.
void setControllersWithDeviceId (DeviceId deviceId, List< ControllerInfo > controllers)
Sets the Controllers for the specified device.
void dropBridge (String bridgeName)
Drops a bridge.
void createTunnel (IpAddress srcIp, IpAddress dstIp)
Creates the configuration for tunnel.
boolean createTunnel (String bridgeName, String portName, String tunnelType, Map< String, String > options)
Creates a tunnel port with given options.
void dropTunnel (IpAddress srcIp, IpAddress dstIp)
Drops the configuration for tunnel.
ListenableFuture< DatabaseSchema > getOvsdbSchema (String dbName)
Gets the OVSDB database schema.
ListenableFuture< TableUpdates > monitorTables (String dbName, String id)
Gets the OVSDB table updates.
ListenableFuture< List
< OperationResult > > transactConfig (String dbName, List< Operation > operations)
Gets the OVSDB config operation result.
ListenableFuture< JsonNode > getSchema (List< String > dbnames)
This operation retrieves a database-schema that describes hosted database db-name.
ListenableFuture< List< String > > echo ()
The "echo" method can be used by both clients and servers to verify the liveness of a database connection.
ListenableFuture< JsonNode > monitor (DatabaseSchema dbSchema, String monitorId)
The "monitor" request enables a client to replicate tables or subsets of tables within an OVSDB database by requesting notifications of changes to those tables and by receiving the complete initial state of a table or a subset of a table.
ListenableFuture< List< String > > listDbs ()
This operation retrieves an array whose elements are the names of the databases that can be accessed over this management protocol connection.
ListenableFuture< List
< JsonNode > > transact (DatabaseSchema dbSchema, List< Operation > operations)
This RPC method causes the database server to execute a series of operations in the specified order on a given database.
void processResult (JsonNode response)
Processes result from ovsdb.
void processRequest (JsonNode requestJson)
processes request from ovsdb.
void setCallback (Callback monitorCallback)
Sets call back.
Set< OvsdbTunnel > getTunnels ()
Gets tunnels of node.
Set< OvsdbBridge > getBridges ()
Gets bridges of node.
Set< ControllerInfo > getControllers (DeviceId openflowDeviceId)
Gets controllers of node.
Set< OvsdbPort > getPorts ()
Gets ports of bridge.
DatabaseSchema getDatabaseSchema (String dbName)
Gets the OVSDB database schema from local.
Set< OvsdbPort > getLocalPorts (Iterable< String > ifaceids)
Gets OVSDB local ports.
void disconnect ()
Disconnects the OVSDB server.
Detailed Description
An representation of an ovsdb client.
Definition at line 94 of file DefaultOvsdbClient.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.DefaultOvsdbClient (OvsdbNodeId nodeId)
Creates an OvsdbClient.
Parameters
nodeId ovsdb node id
Definition at line 121 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.nodeId().
Member Function Documentation
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge (String bridgeName)
Creates a bridge.
Parameters
bridgeName bridge name
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 434 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.rfc.table.OvsdbTable.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.rfc.table.TableGenerator.createTable(), org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getOvsUuid(), org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getRow(), org.onosproject.ovsdb.controller.OvsdbConstant.OPENFLOW13, org.onosproject.ovsdb.rfc.table.OvsdbTable.PORT, org.onosproject.ovsdb.controller.OvsdbConstant.PORT, and obeliskHostCheck.port.
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge (String bridgeName, String dpid, String exPortName)
Creates a bridge.
Parameters
bridgeName bridge name
dpid data path id
exPortName external port name
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 498 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.rfc.table.OvsdbTable.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createPort(), org.onosproject.ovsdb.rfc.table.TableGenerator.createTable(), org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, obeliskHostCheck.dpid, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getOvsUuid(), org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getRow(), org.onosproject.ovsdb.controller.OvsdbConstant.OPENFLOW13, org.onosproject.ovsdb.rfc.table.OvsdbTable.PORT, org.onosproject.ovsdb.controller.OvsdbConstant.PORT, and obeliskHostCheck.port.
boolean org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge (String bridgeName, String dpid, List< ControllerInfo > controllers)
Creates a bridge with given name and dpid.
Sets the bridge's controller with given controllers.
Parameters
bridgeName bridge name
dpid data path id
controllers controllers
Returns
true if bridge creation is successful, false otherwise
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 571 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.rfc.table.OvsdbTable.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, att-onos-ext.controllers, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createPort(), org.onosproject.ovsdb.rfc.table.TableGenerator.createTable(), org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, obeliskHostCheck.dpid, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getOvsUuid(), org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getRow(), org.onosproject.ovsdb.controller.OvsdbConstant.OPENFLOW13, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setControllersWithUUID(), and org.onosproject.ovsdb.rfc.notation.UUID.uuid().
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createPort (String bridgeName, String portName)
Creates a port.
Parameters
bridgeName bridge name
portName port name
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 392 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPortUuid(), org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getRow(), org.onosproject.ovsdb.rfc.table.OvsdbTable.PORT, org.onosproject.ovsdb.controller.OvsdbConstant.PORT, and obeliskHostCheck.port.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge().
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createTunnel (IpAddress srcIp, IpAddress dstIp)
Creates the configuration for tunnel.
Parameters
srcIp source IP address
dstIp destination IP address
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 712 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getInterfaceUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPortUuid(), org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getRow(), org.onosproject.ovsdb.controller.OvsdbConstant.INTEGRATION_BRIDGE, org.onosproject.ovsdb.rfc.table.OvsdbTable.INTERFACE, org.onosproject.ovsdb.controller.OvsdbConstant.INTERFACE, org.onosproject.ovsdb.rfc.table.OvsdbTable.PORT, org.onosproject.ovsdb.controller.OvsdbConstant.PORT, obeliskHostCheck.port, and org.onosproject.ovsdb.controller.OvsdbConstant.TYPEVXLAN.
boolean org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createTunnel (String bridgeName, String portName, String tunnelType, Map< String, String > options)
Creates a tunnel port with given options.
Parameters
bridgeName bridge name
portName port name
tunnelType tunnel type
options tunnel options
Returns
true if tunnel creation is successful, false otherwise
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 783 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.rfc.table.TableGenerator.createTable(), org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPortUuid(), org.onosproject.ovsdb.rfc.table.OvsdbTable.INTERFACE, org.onosproject.ovsdb.rfc.table.OvsdbTable.PORT, obeliskHostCheck.port, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.transactConfig(), and org.onosproject.ovsdb.rfc.notation.UUID.uuid().
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.disconnect ()
Disconnects the OVSDB server.
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 1499 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.nodeId().
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.dropBridge (String bridgeName)
Drops a bridge.
Parameters
bridgeName bridge name
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 701 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid().
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.dropPort (String bridgeName, String portName)
Drops a port.
Parameters
bridgeName bridge name
portName port name
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 418 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPortUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.nodeId(), and org.onosproject.ovsdb.controller.OvsdbConstant.PORT.
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.dropTunnel (IpAddress srcIp, IpAddress dstIp)
Drops the configuration for tunnel.
Parameters
srcIp source IP address
dstIp destination IP address
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 827 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPortUuid(), org.onosproject.ovsdb.controller.OvsdbConstant.INTEGRATION_BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.PORT, and org.onosproject.ovsdb.controller.OvsdbConstant.TYPEVXLAN.
ListenableFuture<List<String> > org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.echo ()
The "echo" method can be used by both clients and servers to verify the liveness of a database connection.
Returns
return info
Implements org.onosproject.ovsdb.rfc.jsonrpc.OvsdbRPC.
Definition at line 1126 of file DefaultOvsdbClient.java.
References find-device.id.
Set<OvsdbBridge> org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridges ()
Gets bridges of node.
Returns
set of bridges; empty if no bridge is find
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 1232 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getRow().
String org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid (String bridgeName)
Gets the Bridge uuid.
Parameters
bridgeName bridge name
Returns
bridge uuid, empty if no uuid is find
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 313 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.rfc.table.OvsdbTable.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, and org.onosproject.ovsdb.rfc.table.Bridge.getName().
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createPort(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createTunnel(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.dropBridge(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.dropPort(), and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.dropTunnel().
Set<ControllerInfo> org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getControllers (DeviceId openflowDeviceId)
Gets controllers of node.
Parameters
openflowDeviceId target device id
Returns
set of controllers; empty if no controller is find
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 1255 of file DefaultOvsdbClient.java.
References att-onos-ext.controllers.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setControllersWithUUID().
String org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getControllerUuid (String controllerName, String controllerTarget)
Gets the Controller uuid.
Parameters
controllerName controller name
controllerTarget controller target
Returns
controller uuid, empty if no uuid is find
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 343 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.rfc.table.OvsdbTable.CONTROLLER, org.onosproject.ovsdb.controller.OvsdbConstant.CONTROLLER, org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, and org.onosproject.ovsdb.rfc.table.Controller.getTargetColumn().
DatabaseSchema org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getDatabaseSchema (String dbName)
Gets the OVSDB database schema from local.
Parameters
dbName database name
Returns
database schema
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 1377 of file DefaultOvsdbClient.java.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getLocalPorts().
String org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getInterfaceUuid (String portUuid, String portName)
Gets the Interface uuid.
Parameters
portUuid port uuid
portName port name
Returns
interface uuid, empty if no uuid is find
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 279 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, org.onosproject.ovsdb.rfc.table.Port.getInterfacesColumn(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getRow(), org.onosproject.ovsdb.rfc.table.TableGenerator.getTable(), org.onosproject.ovsdb.rfc.table.OvsdbTable.INTERFACE, org.onosproject.ovsdb.controller.OvsdbConstant.INTERFACE, org.onosproject.ovsdb.rfc.table.OvsdbTable.PORT, org.onosproject.ovsdb.controller.OvsdbConstant.PORT, and obeliskHostCheck.port.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createTunnel().
Set<OvsdbPort> org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getLocalPorts (Iterable< String > ifaceids)
Gets OVSDB local ports.
Parameters
ifaceids the ifaceid that needed
Returns
OVSDB ports
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 1441 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getDatabaseSchema(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getRow(), org.onosproject.ovsdb.rfc.table.OvsdbTable.INTERFACE, and org.onosproject.ovsdb.controller.OvsdbConstant.INTERFACE.
ListenableFuture<DatabaseSchema> org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getOvsdbSchema (String dbName)
Gets the OVSDB database schema.
Parameters
dbName database name
Returns
database schema
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 1027 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getSchema().
String org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getOvsUuid (String dbName)
Gets the OVS uuid.
Parameters
dbName database name
Returns
ovs uuid, empty if no uuid is find
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 371 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge().
Set<OvsdbPort> org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPorts ()
Gets ports of bridge.
Returns
set of ports; empty if no ports is find
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 1354 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getRow(), and org.onosproject.ovsdb.controller.OvsdbConstant.INTERFACE.
String org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPortUuid (String portName, String bridgeUuid)
Gets the Port uuid.
Parameters
portName port name
bridgeUuid bridge uuid
Returns
port uuid, empty if no uuid is find
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 247 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.rfc.table.OvsdbTable.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, org.onosproject.ovsdb.rfc.table.Bridge.getPortsColumn(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getRow(), org.onosproject.ovsdb.rfc.table.TableGenerator.getTable(), org.onosproject.ovsdb.rfc.table.OvsdbTable.PORT, org.onosproject.ovsdb.controller.OvsdbConstant.PORT, and obeliskHostCheck.port.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createPort(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createTunnel(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.dropPort(), and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.dropTunnel().
Row org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getRow (String dbName, String tableName, String uuid)
Gets the ovsdb row.
Parameters
dbName the ovsdb database name
tableName the ovsdb table name
uuid the key of the row
Returns
row, empty if row is find
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 205 of file DefaultOvsdbClient.java.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridges(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getInterfaceUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getLocalPorts(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPorts(), and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPortUuid().
ListenableFuture<JsonNode> org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getSchema (List< String > dbnames)
This operation retrieves a database-schema that describes hosted database db-name.
Parameters
dbnames database name
Returns
ListenableFuture of JsonNode
Implements org.onosproject.ovsdb.rfc.jsonrpc.OvsdbRPC.
Definition at line 1112 of file DefaultOvsdbClient.java.
References find-device.id.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getOvsdbSchema().
Set<OvsdbTunnel> org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getTunnels ()
Gets tunnels of node.
Returns
set of tunnels; empty if no tunnel is find
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 1227 of file DefaultOvsdbClient.java.
boolean org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.isConnected ()
Checks if the node is still connected.
Returns
true if the node is still connected
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 148 of file DefaultOvsdbClient.java.
ListenableFuture<List<String> > org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.listDbs ()
This operation retrieves an array whose elements are the names of the databases that can be accessed over this management protocol connection.
Returns
database names
Implements org.onosproject.ovsdb.rfc.jsonrpc.OvsdbRPC.
Definition at line 1156 of file DefaultOvsdbClient.java.
References find-device.id.
ListenableFuture<JsonNode> org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.monitor (DatabaseSchema dbSchema, String monitorId)
The "monitor" request enables a client to replicate tables or subsets of tables within an OVSDB database by requesting notifications of changes to those tables and by receiving the complete initial state of a table or a subset of a table.
Parameters
dbSchema databse schema
monitorId a id for monitor
Returns
ListenableFuture of JsonNode
Implements org.onosproject.ovsdb.rfc.jsonrpc.OvsdbRPC.
Definition at line 1140 of file DefaultOvsdbClient.java.
References find-device.id.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.monitorTables().
ListenableFuture<TableUpdates> org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.monitorTables (String dbName, String id)
Gets the OVSDB table updates.
Parameters
dbName database name
id random uuid
Returns
table updates
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 1062 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.monitor().
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.nodeAdded ()
Announces to the ovsdb agent that this node has added.
Implements org.onosproject.ovsdb.controller.driver.OvsdbProviderService.
Definition at line 153 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.nodeId().
OvsdbNodeId org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.nodeId ()
Gets the node identifier.
Returns
node identifier
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 126 of file DefaultOvsdbClient.java.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.DefaultOvsdbClient(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.disconnect(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.dropPort(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.nodeAdded(), and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.nodeRemoved().
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.nodeRemoved ()
Announces to the ovsdb agent that this node has removed.
Implements org.onosproject.ovsdb.controller.driver.OvsdbProviderService.
Definition at line 158 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.nodeId().
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.processRequest (JsonNode request)
processes request from ovsdb.
Parameters
request JsonNode request from ovsdb
Implements org.onosproject.ovsdb.controller.driver.OvsdbProviderService.
Definition at line 1205 of file DefaultOvsdbClient.java.
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.processResult (JsonNode response)
Processes result from ovsdb.
Parameters
response JsonNode response from ovsdb
Implements org.onosproject.ovsdb.controller.driver.OvsdbProviderService.
Definition at line 1187 of file DefaultOvsdbClient.java.
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.removeRow (String dbName, String tableName, String uuid)
Removes the OVSDB row from local OVSDB store.
Parameters
dbName database name
tableName table name
uuid row uuid
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 218 of file DefaultOvsdbClient.java.
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setAgent (OvsdbAgent agent)
Sets the ovsdb agent to be used.
This method can only be called once.
Parameters
agent the agent to set.
Implements org.onosproject.ovsdb.controller.driver.OvsdbProviderService.
Definition at line 131 of file DefaultOvsdbClient.java.
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setCallback (Callback monitorCallback)
Sets call back.
Parameters
monitorCallback the callback to set
Implements org.onosproject.ovsdb.controller.driver.OvsdbProviderService.
Definition at line 1222 of file DefaultOvsdbClient.java.
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setChannel (Channel channel)
Sets the associated Netty channel for this node.
Parameters
channel the Netty channel
Implements org.onosproject.ovsdb.controller.driver.OvsdbProviderService.
Definition at line 138 of file DefaultOvsdbClient.java.
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setConnection (boolean connected)
Sets whether the node is connected.
Parameters
connected whether the node is connected
Implements org.onosproject.ovsdb.controller.driver.OvsdbProviderService.
Definition at line 143 of file DefaultOvsdbClient.java.
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setControllersWithDeviceId (DeviceId deviceId, List< ControllerInfo > controllers)
Sets the Controllers for the specified device.
This method will replace the existing controller list with the new controller list.
Parameters
deviceId device id (likely Openflow device)
controllers list of controllers
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 696 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setControllersWithUUID().
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setControllersWithUUID (UUID bridgeUuid, List< ControllerInfo > controllers)
Sets the Controllers for the specified bridge.
This method will replace the existing controller list with the new controller list.
Parameters
bridgeUuid bridge uuid
controllers list of controllers
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 633 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.rfc.table.OvsdbTable.BRIDGE, org.onosproject.ovsdb.controller.OvsdbConstant.BRIDGE, org.onosproject.ovsdb.rfc.table.OvsdbTable.CONTROLLER, org.onosproject.ovsdb.controller.OvsdbConstant.CONTROLLER, att-onos-ext.controllers, org.onosproject.ovsdb.controller.OvsdbConstant.DATABASENAME, org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getControllers(), and org.onosproject.ovsdb.rfc.table.TableGenerator.getTable().
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge(), and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setControllersWithDeviceId().
ListenableFuture<List<JsonNode> > org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.transact (DatabaseSchema dbSchema, List< Operation > operations)
This RPC method causes the database server to execute a series of operations in the specified order on a given database.
Parameters
dbSchema database schema
operations the operations to execute
Returns
result the transact result
Implements org.onosproject.ovsdb.rfc.jsonrpc.OvsdbRPC.
Definition at line 1170 of file DefaultOvsdbClient.java.
References find-device.id.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.transactConfig().
ListenableFuture<List<OperationResult> > org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.transactConfig (String dbName, List< Operation > operations)
Gets the OVSDB config operation result.
Parameters
dbName database name
operations the list of operations
Returns
operation results
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 1087 of file DefaultOvsdbClient.java.
References org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.transact().
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createTunnel().
void org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.updateOvsdbStore (String dbName, String tableName, String uuid, Row row)
Updates the local OVSDB store.
Parameters
dbName database name
tableName table name
uuid row uuid
row OVSDB row
Implements org.onosproject.ovsdb.controller.OvsdbClientService.
Definition at line 231 of file DefaultOvsdbClient.java.
The documentation for this class was generated from the following file:
protocols/ovsdb/api/src/main/java/org/onosproject/ovsdb/controller/driver/DefaultOvsdbClient.java