onos: org.onosproject.net.group.DefaultGroup Class Reference
org.onosproject.net.group.DefaultGroup Class Reference
ONOS implementation of default group that is stored in the system.
Public Member Functions
DefaultGroup (GroupId id, GroupDescription groupDesc)
Default group object constructor with the parameters.
DefaultGroup (GroupId id, DeviceId deviceId, GroupDescription.Type type, GroupBuckets buckets)
Default group object constructor with the available information from data plane.
GroupId id ()
Returns group identifier associated with a group object.
GroupState state ()
Returns current state of a group object.
long life ()
Returns the number of milliseconds this group has been alive.
long packets ()
Returns the number of packets processed by this group.
long bytes ()
Returns the number of bytes processed by this group.
void setState (Group.GroupState newState)
Sets the new state for this entry.
void setLife (long life)
Sets how long this entry has been entered in the system.
void setPackets (long packets)
Sets number of packets processed by this group entry.
void setBytes (long bytes)
Sets number of bytes processed by this group entry.
void setReferenceCount (long referenceCount)
Sets number of flow rules or groups referencing this group entry.
long referenceCount ()
Returns the number of flow rules or other groups reference this group.
int hashCode ()
boolean equals (Object obj)
String toString ()
void setIsGroupStateAddedFirstTime (boolean isGroupStateAddedFirstTime)
Sets if group has transitioned to ADDED state for the first time.
boolean isGroupStateAddedFirstTime ()
Returns the isGroupStateAddedFirstTime value.
Public Member Functions inherited from org.onosproject.net.group.DefaultGroupDescription
DefaultGroupDescription (DeviceId deviceId, GroupDescription.Type type, GroupBuckets buckets, GroupKey appCookie, Integer groupId, ApplicationId appId)
Constructor to be used by north bound applications.
DefaultGroupDescription (GroupDescription groupDesc)
Constructor to be used by group subsystem internal components.
DefaultGroupDescription (DeviceId deviceId, GroupDescription.Type type, GroupBuckets buckets)
Constructor to be used by group subsystem internal components.
GroupDescription.Type type ()
Returns type of a group object.
DeviceId deviceId ()
Returns device identifier on which this group object is created.
ApplicationId appId ()
Returns application identifier that has created this group object.
GroupKey appCookie ()
Returns application cookie associated with a group object.
GroupBuckets buckets ()
Returns group buckets of a group.
Integer givenGroupId ()
Returns groupId passed in by application.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
ONOS implementation of default group that is stored in the system.
Definition at line 28 of file DefaultGroup.java.
Constructor & Destructor Documentation
org.onosproject.net.group.DefaultGroup.DefaultGroup (GroupId id, GroupDescription groupDesc)
Default group object constructor with the parameters.
Parameters
id group identifier
groupDesc group description parameters
Definition at line 59 of file DefaultGroup.java.
Referenced by org.onosproject.net.group.DefaultGroup.equals().
org.onosproject.net.group.DefaultGroup.DefaultGroup (GroupId id, DeviceId deviceId, GroupDescription.Type type, GroupBuckets buckets)
Default group object constructor with the available information from data plane.
Parameters
id group identifier
deviceId device identifier
type type of the group
buckets immutable list of group bucket
Definition at line 73 of file DefaultGroup.java.
References org.onosproject.net.group.DefaultGroupDescription.type().
Member Function Documentation
long org.onosproject.net.group.DefaultGroup.bytes ()
Returns the number of bytes processed by this group.
Returns
number of bytes
Implements org.onosproject.net.group.Group.
Definition at line 127 of file DefaultGroup.java.
Referenced by org.onosproject.net.group.DefaultGroup.setBytes().
boolean org.onosproject.net.group.DefaultGroup.equals (Object obj)
Definition at line 199 of file DefaultGroup.java.
References org.onosproject.net.group.DefaultGroup.DefaultGroup().
int org.onosproject.net.group.DefaultGroup.hashCode ()
Definition at line 188 of file DefaultGroup.java.
GroupId org.onosproject.net.group.DefaultGroup.id ()
Returns group identifier associated with a group object.
Returns
GroupId Group Identifier
Implements org.onosproject.net.group.Group.
Definition at line 87 of file DefaultGroup.java.
References find-device.id.
Referenced by org.onosproject.net.group.DefaultGroup.toString().
boolean org.onosproject.net.group.DefaultGroup.isGroupStateAddedFirstTime ()
Returns the isGroupStateAddedFirstTime value.
For internal use only.
Returns
isGroupStateAddedFirstTime value
Implements org.onosproject.net.group.StoredGroupEntry.
Definition at line 226 of file DefaultGroup.java.
Referenced by org.onosproject.net.group.DefaultGroup.setIsGroupStateAddedFirstTime().
long org.onosproject.net.group.DefaultGroup.life ()
Returns the number of milliseconds this group has been alive.
Returns
number of millis
Implements org.onosproject.net.group.Group.
Definition at line 107 of file DefaultGroup.java.
Referenced by org.onosproject.net.group.DefaultGroup.setLife().
long org.onosproject.net.group.DefaultGroup.packets ()
Returns the number of packets processed by this group.
Returns
number of packets
Implements org.onosproject.net.group.Group.
Definition at line 117 of file DefaultGroup.java.
Referenced by org.onosproject.net.group.DefaultGroup.setPackets().
long org.onosproject.net.group.DefaultGroup.referenceCount ()
Returns the number of flow rules or other groups reference this group.
Returns
number of flow rules or other groups pointing to this group
Implements org.onosproject.net.group.Group.
Definition at line 177 of file DefaultGroup.java.
Referenced by org.onosproject.net.group.DefaultGroup.setReferenceCount().
void org.onosproject.net.group.DefaultGroup.setBytes (long bytes)
Sets number of bytes processed by this group entry.
Parameters
bytes a long value
Implements org.onosproject.net.group.StoredGroupEntry.
Definition at line 167 of file DefaultGroup.java.
References org.onosproject.net.group.DefaultGroup.bytes().
void org.onosproject.net.group.DefaultGroup.setIsGroupStateAddedFirstTime (boolean isGroupAddedFirstTime)
Sets if group has transitioned to ADDED state for the first time.
This is to differentiate state transitions "from PENDING_ADD to ADDED" and "from PENDING_UPDATE to ADDED". For internal use only.
Parameters
isGroupAddedFirstTime true if group moves to ADDED state for the first time.
Implements org.onosproject.net.group.StoredGroupEntry.
Definition at line 221 of file DefaultGroup.java.
References org.onosproject.net.group.DefaultGroup.isGroupStateAddedFirstTime().
void org.onosproject.net.group.DefaultGroup.setLife (long life)
Sets how long this entry has been entered in the system.
Parameters
life epoch time
Implements org.onosproject.net.group.StoredGroupEntry.
Definition at line 147 of file DefaultGroup.java.
References org.onosproject.net.group.DefaultGroup.life().
void org.onosproject.net.group.DefaultGroup.setPackets (long packets)
Sets number of packets processed by this group entry.
Parameters
packets a long value
Implements org.onosproject.net.group.StoredGroupEntry.
Definition at line 157 of file DefaultGroup.java.
References org.onosproject.net.group.DefaultGroup.packets().
void org.onosproject.net.group.DefaultGroup.setReferenceCount (long referenceCount)
Sets number of flow rules or groups referencing this group entry.
Parameters
referenceCount reference count
Implements org.onosproject.net.group.StoredGroupEntry.
Definition at line 172 of file DefaultGroup.java.
References org.onosproject.net.group.DefaultGroup.referenceCount().
void org.onosproject.net.group.DefaultGroup.setState (Group.GroupState newState)
Sets the new state for this entry.
Parameters
newState new group entry state.
Implements org.onosproject.net.group.StoredGroupEntry.
Definition at line 137 of file DefaultGroup.java.
GroupState org.onosproject.net.group.DefaultGroup.state ()
Returns current state of a group object.
Returns
GroupState Group State
Implements org.onosproject.net.group.Group.
Definition at line 97 of file DefaultGroup.java.
Referenced by org.onosproject.net.group.DefaultGroup.toString().
String org.onosproject.net.group.DefaultGroup.toString ()
Definition at line 212 of file DefaultGroup.java.
References org.onosproject.net.group.DefaultGroup.id(), and org.onosproject.net.group.DefaultGroup.state().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/group/DefaultGroup.java