onos: org.onosproject.store.device.impl.GossipDeviceStoreTest Class Reference
org.onosproject.store.device.impl.GossipDeviceStoreTest Class Reference
Test of the gossip based distributed DeviceStore implementation.
Public Member Functions
void setUp () throws Exception
void tearDown () throws Exception
final void testGetDeviceCount ()
final void testGetDevices ()
final void testGetDevice ()
final void testCreateOrUpdateDevice () throws IOException
final void testCreateOrUpdateDeviceAncillary () throws IOException
final void testMarkOffline ()
final void testUpdatePorts ()
final void testUpdatePortStatus ()
final void testUpdatePortStatusAncillary () throws IOException
final void testGetPorts ()
final void testGetPort ()
final void testRemoveDevice ()
final void testEvents () throws InterruptedException
Static Public Member Functions
static void setUpBeforeClass () throws Exception
static void tearDownAfterClass () throws Exception
Detailed Description
Test of the gossip based distributed DeviceStore implementation.
Definition at line 90 of file GossipDeviceStoreTest.java.
Member Function Documentation
void org.onosproject.store.device.impl.GossipDeviceStoreTest.setUp () throws Exception
Definition at line 153 of file GossipDeviceStoreTest.java.
static void org.onosproject.store.device.impl.GossipDeviceStoreTest.setUpBeforeClass () throws Exception static
Definition at line 144 of file GossipDeviceStoreTest.java.
void org.onosproject.store.device.impl.GossipDeviceStoreTest.tearDown () throws Exception
Definition at line 177 of file GossipDeviceStoreTest.java.
static void org.onosproject.store.device.impl.GossipDeviceStoreTest.tearDownAfterClass () throws Exception static
Definition at line 148 of file GossipDeviceStoreTest.java.
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testCreateOrUpdateDevice () throws IOException
Definition at line 343 of file GossipDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.createOrUpdateDevice().
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testCreateOrUpdateDeviceAncillary () throws IOException
Definition at line 375 of file GossipDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.createOrUpdateDevice(), and org.onosproject.net.device.DeviceStore.isAvailable().
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testEvents () throws InterruptedException
Definition at line 803 of file GossipDeviceStoreTest.java.
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testGetDevice ()
Definition at line 294 of file GossipDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.getDevice().
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testGetDeviceCount ()
Definition at line 261 of file GossipDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.getDeviceCount().
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testGetDevices ()
Definition at line 272 of file GossipDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.getDevices().
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testGetPort ()
Definition at line 733 of file GossipDeviceStoreTest.java.
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testGetPorts ()
Definition at line 710 of file GossipDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.getPorts(), and obeliskHostCheck.port.
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testMarkOffline ()
Definition at line 449 of file GossipDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.isAvailable().
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testRemoveDevice ()
Definition at line 755 of file GossipDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.getDevice(), org.onosproject.net.device.DeviceStore.getDeviceCount(), org.onosproject.net.device.DeviceStore.getPort(), and org.onosproject.net.device.DeviceStore.getPorts().
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testUpdatePorts ()
Definition at line 476 of file GossipDeviceStoreTest.java.
References org.onosproject.net.PortNumber.equals().
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testUpdatePortStatus ()
Definition at line 561 of file GossipDeviceStoreTest.java.
final void org.onosproject.store.device.impl.GossipDeviceStoreTest.testUpdatePortStatusAncillary () throws IOException
Definition at line 585 of file GossipDeviceStoreTest.java.
The documentation for this class was generated from the following file:
core/store/dist/src/test/java/org/onosproject/store/device/impl/GossipDeviceStoreTest.java