onos: org.onosproject.vtnrsc.DefaultHostRoute Class Reference
org.onosproject.vtnrsc.DefaultHostRoute Class Reference
Host route dictionaries for the subnet.
Public Member Functions
DefaultHostRoute (IpAddress nexthop, IpPrefix destination)
Creates a DefaultHostRoute by using the next hop and the destination.
IpAddress nexthop ()
Returns the next hop address.
IpPrefix destination ()
Returns the destination address.
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Host route dictionaries for the subnet.
Definition at line 28 of file DefaultHostRoute.java.
Constructor & Destructor Documentation
org.onosproject.vtnrsc.DefaultHostRoute.DefaultHostRoute (IpAddress nexthop, IpPrefix destination)
Creates a DefaultHostRoute by using the next hop and the destination.
Parameters
nexthop of the DefaultHostRoute
destination of the DefaultHostRoute
Definition at line 40 of file DefaultHostRoute.java.
References org.onosproject.vtnrsc.DefaultHostRoute.destination(), and org.onosproject.vtnrsc.DefaultHostRoute.nexthop().
Referenced by org.onosproject.vtnrsc.DefaultHostRoute.equals().
Member Function Documentation
IpPrefix org.onosproject.vtnrsc.DefaultHostRoute.destination ()
Returns the destination address.
Returns
destination address
Implements org.onosproject.vtnrsc.HostRoute.
Definition at line 51 of file DefaultHostRoute.java.
Referenced by org.onosproject.vtnrsc.DefaultHostRoute.DefaultHostRoute(), org.onosproject.vtnrsc.DefaultHostRoute.hashCode(), and org.onosproject.vtnrsc.DefaultHostRoute.toString().
boolean org.onosproject.vtnrsc.DefaultHostRoute.equals (Object obj)
Definition at line 67 of file DefaultHostRoute.java.
References org.onosproject.vtnrsc.DefaultHostRoute.DefaultHostRoute().
int org.onosproject.vtnrsc.DefaultHostRoute.hashCode ()
Definition at line 62 of file DefaultHostRoute.java.
References org.onosproject.vtnrsc.DefaultHostRoute.destination(), and org.onosproject.vtnrsc.DefaultHostRoute.nexthop().
IpAddress org.onosproject.vtnrsc.DefaultHostRoute.nexthop ()
Returns the next hop address.
Returns
next hop address
Implements org.onosproject.vtnrsc.HostRoute.
Definition at line 46 of file DefaultHostRoute.java.
Referenced by org.onosproject.vtnrsc.DefaultHostRoute.DefaultHostRoute(), org.onosproject.vtnrsc.DefaultHostRoute.hashCode(), and org.onosproject.vtnrsc.DefaultHostRoute.toString().
String org.onosproject.vtnrsc.DefaultHostRoute.toString ()
Definition at line 56 of file DefaultHostRoute.java.
References org.onosproject.vtnrsc.DefaultHostRoute.destination(), and org.onosproject.vtnrsc.DefaultHostRoute.nexthop().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultHostRoute.java