onos: org.onosproject.net.behaviour.ControllerInfo Class Reference
org.onosproject.net.behaviour.ControllerInfo Class Reference
Represents information for a device to connect to a controller.
Public Member Functions
ControllerInfo (IpAddress ip, int port, String type)
Information for contacting the controller.
ControllerInfo (String target)
Information for contacting the controller, if some information is not contained in the target string because it's optional it's leaved as in the field declaration (default values).
IpAddress ip ()
Exposes the ip address of the controller.
int port ()
Exposes the tcp port of the controller.
String type ()
Exposes the type of the controller connection.
String target ()
int hashCode ()
boolean equals (Object toBeCompared)
Detailed Description
Represents information for a device to connect to a controller.
Definition at line 26 of file ControllerInfo.java.
Constructor & Destructor Documentation
org.onosproject.net.behaviour.ControllerInfo.ControllerInfo (IpAddress ip, int port, String type)
Information for contacting the controller.
Parameters
ip the ip address
port the tcp port
type the connection type
Definition at line 39 of file ControllerInfo.java.
References org.onosproject.net.behaviour.ControllerInfo.ip(), org.onosproject.net.behaviour.ControllerInfo.port(), and org.onosproject.net.behaviour.ControllerInfo.type().
Referenced by org.onosproject.net.behaviour.ControllerInfo.equals().
org.onosproject.net.behaviour.ControllerInfo.ControllerInfo (String target)
Information for contacting the controller, if some information is not contained in the target string because it's optional it's leaved as in the field declaration (default values).
Parameters
target column returned from ovsdb query
Definition at line 52 of file ControllerInfo.java.
Member Function Documentation
boolean org.onosproject.net.behaviour.ControllerInfo.equals (Object toBeCompared)
Definition at line 116 of file ControllerInfo.java.
References org.onosproject.net.behaviour.ControllerInfo.ControllerInfo(), and org.onosproject.net.behaviour.ControllerInfo.port().
Referenced by org.onosproject.net.behaviour.ControllerInfoTest.testEquals().
int org.onosproject.net.behaviour.ControllerInfo.hashCode ()
Definition at line 111 of file ControllerInfo.java.
References org.onosproject.net.behaviour.ControllerInfo.ip(), org.onosproject.net.behaviour.ControllerInfo.port(), and org.onosproject.net.behaviour.ControllerInfo.type().
IpAddress org.onosproject.net.behaviour.ControllerInfo.ip ()
Exposes the ip address of the controller.
Returns
IpAddress ip address
Definition at line 79 of file ControllerInfo.java.
Referenced by org.onosproject.net.behaviour.ControllerInfo.ControllerInfo(), org.onosproject.net.behaviour.ControllerInfo.hashCode(), onos.ONOS.start(), org.onosproject.net.behaviour.ControllerInfo.target(), and onos.ONOS.updateHazelcast().
int org.onosproject.net.behaviour.ControllerInfo.port ()
Exposes the tcp port of the controller.
Returns
int tcp port
Definition at line 88 of file ControllerInfo.java.
Referenced by org.onosproject.net.behaviour.ControllerInfo.ControllerInfo(), org.onosproject.net.behaviour.ControllerInfo.equals(), org.onosproject.net.behaviour.ControllerInfo.hashCode(), and org.onosproject.net.behaviour.ControllerInfo.target().
String org.onosproject.net.behaviour.ControllerInfo.target ()
Definition at line 101 of file ControllerInfo.java.
References org.onosproject.net.behaviour.ControllerInfo.ip(), org.onosproject.net.behaviour.ControllerInfo.port(), and org.onosproject.net.behaviour.ControllerInfo.type().
String org.onosproject.net.behaviour.ControllerInfo.type ()
Exposes the type of the controller connection.
Returns
String type
Definition at line 97 of file ControllerInfo.java.
Referenced by org.onosproject.net.behaviour.ControllerInfo.ControllerInfo(), org.onosproject.net.behaviour.ControllerInfo.hashCode(), and org.onosproject.net.behaviour.ControllerInfo.target().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/behaviour/ControllerInfo.java