onos: org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V > Class Reference
org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V > Class Reference
AsyncConsistentMap implementation that is backed by a Raft consensus based database.
Public Member Functions
DefaultAsyncConsistentMap (String name, ApplicationId applicationId, Database database, Serializer serializer, boolean readOnly, boolean purgeOnUninstall, boolean meteringEnabled)
String name ()
Returns this map name.
Serializer serializer ()
Returns the serializer for map entries.
ApplicationId applicationId ()
Returns the applicationId owning this map.
boolean purgeOnUninstall ()
Returns whether the map entries should be purged when the application owning it is uninstalled.
CompletableFuture< Integer > size ()
CompletableFuture< Boolean > isEmpty ()
CompletableFuture< Boolean > containsKey (K key)
CompletableFuture< Boolean > containsValue (V value)
CompletableFuture< Versioned< V > > get (K key)
CompletableFuture< Versioned< V > > computeIfAbsent (K key, Function<?super K,?extends V > mappingFunction)
CompletableFuture< Versioned< V > > computeIfPresent (K key, BiFunction<?super K,?super V,?extends V > remappingFunction)
CompletableFuture< Versioned< V > > compute (K key, BiFunction<?super K,?super V,?extends V > remappingFunction)
CompletableFuture< Versioned< V > > computeIf (K key, Predicate<?super V > condition, BiFunction<?super K,?super V,?extends V > remappingFunction)
CompletableFuture< Versioned< V > > put (K key, V value)
CompletableFuture< Versioned< V > > putAndGet (K key, V value)
CompletableFuture< Versioned< V > > remove (K key)
CompletableFuture< Void > clear ()
CompletableFuture< Set< K > > keySet ()
CompletableFuture< Collection
< Versioned< V > > > values ()
CompletableFuture< Set< Entry
< K, Versioned< V > > > > entrySet ()
CompletableFuture< Versioned< V > > putIfAbsent (K key, V value)
CompletableFuture< Boolean > remove (K key, V value)
CompletableFuture< Boolean > remove (K key, long version)
CompletableFuture< Boolean > replace (K key, V oldValue, V newValue)
CompletableFuture< Boolean > replace (K key, long oldVersion, V newValue)
void addListener (MapEventListener< K, V > listener)
void removeListener (MapEventListener< K, V > listener)
Protected Member Functions
K dK (String key)
void beforeUpdate (K key)
Pre-update hook for performing required checks/actions before going forward with an update operation.
void notifyListeners (MapEvent< K, V > event)
Detailed Description
AsyncConsistentMap implementation that is backed by a Raft consensus based database.
Parameters
<K> type of key.
<V> type of value.
Definition at line 60 of file DefaultAsyncConsistentMap.java.
Constructor & Destructor Documentation
org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.DefaultAsyncConsistentMap (String name, ApplicationId applicationId, Database database, Serializer serializer, boolean readOnly, boolean purgeOnUninstall, boolean meteringEnabled)
Definition at line 109 of file DefaultAsyncConsistentMap.java.
References org.onlab.util.Tools.copyOf(), org.onosproject.store.service.Serializer.decode(), and create-flow.name.
Member Function Documentation
void org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.addListener (MapEventListener< K, V > listener)
Definition at line 451 of file DefaultAsyncConsistentMap.java.
ApplicationId org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.applicationId ()
Returns the applicationId owning this map.
Returns
application Id
Definition at line 179 of file DefaultAsyncConsistentMap.java.
void org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.beforeUpdate (K key) protected
Pre-update hook for performing required checks/actions before going forward with an update operation.
Parameters
key map key.
Definition at line 412 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Void> org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.clear ()
Definition at line 320 of file DefaultAsyncConsistentMap.java.
References create-flow.name.
CompletableFuture<Versioned<V> > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.compute (K key, BiFunction<?super K,?super V,?extends V > remappingFunction)
Definition at line 249 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Versioned<V> > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.computeIf (K key, Predicate<?super V > condition, BiFunction<?super K,?super V,?extends V > remappingFunction)
Definition at line 255 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Versioned<V> > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.computeIfAbsent (K key, Function<?super K,?extends V > mappingFunction)
Definition at line 232 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Versioned<V> > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.computeIfPresent (K key, BiFunction<?super K,?super V,?extends V > remappingFunction)
Definition at line 243 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.containsKey (K key)
Definition at line 207 of file DefaultAsyncConsistentMap.java.
References create-flow.name.
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.containsValue (V value)
Definition at line 215 of file DefaultAsyncConsistentMap.java.
References create-flow.name.
K org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.dK (String key) protected
Definition at line 105 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Set<Entry<K, Versioned<V> > > > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.entrySet ()
Definition at line 350 of file DefaultAsyncConsistentMap.java.
References create-flow.name.
CompletableFuture<Versioned<V> > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.get (K key)
Definition at line 223 of file DefaultAsyncConsistentMap.java.
References create-flow.name.
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.isEmpty ()
Definition at line 200 of file DefaultAsyncConsistentMap.java.
References create-flow.name.
CompletableFuture<Set<K> > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.keySet ()
Definition at line 328 of file DefaultAsyncConsistentMap.java.
References create-flow.name.
String org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.name ()
Returns this map name.
Returns
map name
Definition at line 163 of file DefaultAsyncConsistentMap.java.
References create-flow.name.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
void org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.notifyListeners (MapEvent< K, V > event) protected
Definition at line 460 of file DefaultAsyncConsistentMap.java.
boolean org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.purgeOnUninstall ()
Returns whether the map entries should be purged when the application owning it is uninstalled.
Returns
true is map needs to cleared on app uninstall; false otherwise
Definition at line 188 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Versioned<V> > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.put (K key, V value)
Definition at line 294 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Versioned<V> > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.putAndGet (K key, V value)
Definition at line 303 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Versioned<V> > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.putIfAbsent (K key, V value)
Definition at line 361 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Versioned<V> > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.remove (K key)
Definition at line 312 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.remove (K key, V value)
Definition at line 371 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.remove (K key, long version)
Definition at line 381 of file DefaultAsyncConsistentMap.java.
void org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.removeListener (MapEventListener< K, V > listener)
Definition at line 456 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.replace (K key, V oldValue, V newValue)
Definition at line 390 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.replace (K key, long oldVersion, V newValue)
Definition at line 401 of file DefaultAsyncConsistentMap.java.
Serializer org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.serializer ()
Returns the serializer for map entries.
Returns
map entry serializer
Definition at line 171 of file DefaultAsyncConsistentMap.java.
CompletableFuture<Integer> org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.size ()
Definition at line 193 of file DefaultAsyncConsistentMap.java.
References create-flow.name.
CompletableFuture<Collection<Versioned<V> > > org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.values ()
Definition at line 339 of file DefaultAsyncConsistentMap.java.
References create-flow.name.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DefaultAsyncConsistentMap.java