onos: org.onosproject.pcepio.types.PathKeySubObject Class Reference
org.onosproject.pcepio.types.PathKeySubObject Class Reference
Path Key SubObject: When a PCC needs to expand a path-key in order to expand a CPS, it issues a Path Computation Request (PCReq) to the PCE identified in the PKS in the RSVP-TE ERO that it is processing.
Public Member Functions
PathKeySubObject (short pathKey, int pceID)
Constructor for Path Key sub Object which initializes pathKey and pceId.
short getPathKey ()
Returns Path Key.
int getPceId ()
Returns pceID.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static PathKeySubObject of (short pathKey, int pceID)
Creates Path Key sub Object which initializes pathKey and pceId.
static PcepValueType read (ChannelBuffer c)
Reads the channel buffer and returns new path key sub objects.
Static Public Attributes
static final byte TYPE = 0x40
static final byte LENGTH = 8
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PathKeySubObject.class)
Detailed Description
Path Key SubObject: When a PCC needs to expand a path-key in order to expand a CPS, it issues a Path Computation Request (PCReq) to the PCE identified in the PKS in the RSVP-TE ERO that it is processing.
The PCC supplies the PKS to be expanded in a PATH-KEY SubObject in the PCReq message.
Definition at line 34 of file PathKeySubObject.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PathKeySubObject.PathKeySubObject (short pathKey, int pceID)
Constructor for Path Key sub Object which initializes pathKey and pceId.
Parameters
pathKey path key provided by PCC
pceID ID for the PCE
Definition at line 60 of file PathKeySubObject.java.
Referenced by org.onosproject.pcepio.types.PathKeySubObject.equals(), org.onosproject.pcepio.types.PathKeySubObject.of(), and org.onosproject.pcepio.types.PathKeySubObject.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.PathKeySubObject.equals (Object obj)
Definition at line 115 of file PathKeySubObject.java.
References org.onosproject.pcepio.types.PathKeySubObject.PathKeySubObject().
short org.onosproject.pcepio.types.PathKeySubObject.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 105 of file PathKeySubObject.java.
References org.onosproject.pcepio.types.PathKeySubObject.LENGTH.
short org.onosproject.pcepio.types.PathKeySubObject.getPathKey ()
Returns Path Key.
Returns
pathKey
Definition at line 81 of file PathKeySubObject.java.
int org.onosproject.pcepio.types.PathKeySubObject.getPceId ()
Returns pceID.
Returns
pceID
Definition at line 90 of file PathKeySubObject.java.
short org.onosproject.pcepio.types.PathKeySubObject.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 100 of file PathKeySubObject.java.
References org.onosproject.pcepio.types.PathKeySubObject.TYPE.
PcepVersion org.onosproject.pcepio.types.PathKeySubObject.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 95 of file PathKeySubObject.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.PathKeySubObject.hashCode ()
Definition at line 110 of file PathKeySubObject.java.
static PathKeySubObject org.onosproject.pcepio.types.PathKeySubObject.of (short pathKey, int pceID) static
Creates Path Key sub Object which initializes pathKey and pceId.
Parameters
pathKey path key provided by PCC
pceID PCE id
Returns
new object of type path key sub object
Definition at line 72 of file PathKeySubObject.java.
References org.onosproject.pcepio.types.PathKeySubObject.PathKeySubObject().
static PcepValueType org.onosproject.pcepio.types.PathKeySubObject.read (ChannelBuffer c) static
Reads the channel buffer and returns new path key sub objects.
Parameters
c of type channel buffer
Returns
object of type path key sub object
Definition at line 144 of file PathKeySubObject.java.
References org.onosproject.pcepio.types.PathKeySubObject.PathKeySubObject().
String org.onosproject.pcepio.types.PathKeySubObject.toString ()
Definition at line 151 of file PathKeySubObject.java.
References org.onosproject.pcepio.types.PathKeySubObject.LENGTH, and org.onosproject.pcepio.types.PathKeySubObject.TYPE.
int org.onosproject.pcepio.types.PathKeySubObject.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 127 of file PathKeySubObject.java.
References org.onosproject.pcepio.types.PathKeySubObject.LENGTH, and org.onosproject.pcepio.types.PathKeySubObject.TYPE.
Member Data Documentation
final byte org.onosproject.pcepio.types.PathKeySubObject.LENGTH = 8 static
Definition at line 50 of file PathKeySubObject.java.
Referenced by org.onosproject.pcepio.types.PathKeySubObject.getLength(), org.onosproject.pcepio.types.PathKeySubObject.toString(), and org.onosproject.pcepio.types.PathKeySubObject.write().
final Logger org.onosproject.pcepio.types.PathKeySubObject.log = LoggerFactory.getLogger(PathKeySubObject.class) static protected
Definition at line 47 of file PathKeySubObject.java.
final byte org.onosproject.pcepio.types.PathKeySubObject.TYPE = 0x40 static
Definition at line 49 of file PathKeySubObject.java.
Referenced by org.onosproject.pcepio.types.PathKeySubObject.getType(), org.onosproject.pcepio.types.PathKeySubObject.toString(), and org.onosproject.pcepio.types.PathKeySubObject.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PathKeySubObject.java