onos: org.onosproject.net.flow.criteria.IPDscpCriterion Class Reference
org.onosproject.net.flow.criteria.IPDscpCriterion Class Reference
Implementation of IP DSCP (Differentiated Services Code Point) criterion (6 bits).
Public Member Functions
Type type ()
Returns the type of criterion.
byte ipDscp ()
Gets the IP DSCP value to match.
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Implementation of IP DSCP (Differentiated Services Code Point) criterion (6 bits).
Definition at line 26 of file IPDscpCriterion.java.
Member Function Documentation
boolean org.onosproject.net.flow.criteria.IPDscpCriterion.equals (Object obj)
Definition at line 65 of file IPDscpCriterion.java.
References org.onosproject.net.flow.criteria.IPDscpCriterion.ipDscp().
int org.onosproject.net.flow.criteria.IPDscpCriterion.hashCode ()
Definition at line 60 of file IPDscpCriterion.java.
References org.onosproject.net.flow.criteria.IPDscpCriterion.type().
byte org.onosproject.net.flow.criteria.IPDscpCriterion.ipDscp ()
Gets the IP DSCP value to match.
Returns
the IP DSCP value to match
Definition at line 49 of file IPDscpCriterion.java.
Referenced by org.onosproject.net.flow.criteria.IPDscpCriterion.equals(), and org.onosproject.net.flow.criteria.IPDscpCriterion.toString().
String org.onosproject.net.flow.criteria.IPDscpCriterion.toString ()
Definition at line 54 of file IPDscpCriterion.java.
References org.onosproject.net.flow.criteria.IPDscpCriterion.ipDscp(), and org.onosproject.net.flow.criteria.IPDscpCriterion.type().
Type org.onosproject.net.flow.criteria.IPDscpCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 40 of file IPDscpCriterion.java.
References org.onosproject.net.flow.criteria.Criterion.Type.IP_DSCP.
Referenced by org.onosproject.net.flow.criteria.IPDscpCriterion.hashCode(), and org.onosproject.net.flow.criteria.IPDscpCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/IPDscpCriterion.java