onos: org.onosproject.pcepio.types.AdministrativeGroupTlv Class Reference
org.onosproject.pcepio.types.AdministrativeGroupTlv Class Reference
Provides Administrative Group Tlv which contains value (32 Bit).
Public Member Functions
AdministrativeGroupTlv (int rawValue)
Constructor to initialize rawValue.
int getInt ()
Returns raw value.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static AdministrativeGroupTlv of (final int raw)
Returns newly created AdministrativeGroupTlv object.
static AdministrativeGroupTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of Administrative-Group-Tlv.
Static Public Attributes
static final short TYPE = 3
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(AdministrativeGroupTlv.class)
Detailed Description
Provides Administrative Group Tlv which contains value (32 Bit).
Definition at line 30 of file AdministrativeGroupTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.AdministrativeGroupTlv.AdministrativeGroupTlv (int rawValue)
Constructor to initialize rawValue.
Parameters
rawValue of Administrative-Group-Tlv.
Definition at line 54 of file AdministrativeGroupTlv.java.
Referenced by org.onosproject.pcepio.types.AdministrativeGroupTlv.equals(), and org.onosproject.pcepio.types.AdministrativeGroupTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.AdministrativeGroupTlv.equals (Object obj)
Definition at line 98 of file AdministrativeGroupTlv.java.
References org.onosproject.pcepio.types.AdministrativeGroupTlv.AdministrativeGroupTlv().
int org.onosproject.pcepio.types.AdministrativeGroupTlv.getInt ()
Returns raw value.
Returns
rawValue raw value
Definition at line 73 of file AdministrativeGroupTlv.java.
short org.onosproject.pcepio.types.AdministrativeGroupTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 88 of file AdministrativeGroupTlv.java.
References org.onosproject.pcepio.types.AdministrativeGroupTlv.LENGTH.
short org.onosproject.pcepio.types.AdministrativeGroupTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 83 of file AdministrativeGroupTlv.java.
References org.onosproject.pcepio.types.AdministrativeGroupTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.AdministrativeGroupTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 78 of file AdministrativeGroupTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.AdministrativeGroupTlv.hashCode ()
Definition at line 93 of file AdministrativeGroupTlv.java.
static AdministrativeGroupTlv org.onosproject.pcepio.types.AdministrativeGroupTlv.of (final int raw) static
Returns newly created AdministrativeGroupTlv object.
Parameters
raw value.
Returns
object of Administrative-Group-Tlv
Definition at line 64 of file AdministrativeGroupTlv.java.
References org.onosproject.pcepio.types.AdministrativeGroupTlv.AdministrativeGroupTlv().
static AdministrativeGroupTlv org.onosproject.pcepio.types.AdministrativeGroupTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of Administrative-Group-Tlv.
Parameters
c input channel buffer
Returns
object of Administrative-Group-Tlv
Definition at line 124 of file AdministrativeGroupTlv.java.
String org.onosproject.pcepio.types.AdministrativeGroupTlv.toString ()
Definition at line 129 of file AdministrativeGroupTlv.java.
References org.onosproject.pcepio.types.AdministrativeGroupTlv.LENGTH, and org.onosproject.pcepio.types.AdministrativeGroupTlv.TYPE.
int org.onosproject.pcepio.types.AdministrativeGroupTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 110 of file AdministrativeGroupTlv.java.
References org.onosproject.pcepio.types.AdministrativeGroupTlv.LENGTH, and org.onosproject.pcepio.types.AdministrativeGroupTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.AdministrativeGroupTlv.LENGTH = 4 static
Definition at line 45 of file AdministrativeGroupTlv.java.
Referenced by org.onosproject.pcepio.types.AdministrativeGroupTlv.getLength(), org.onosproject.pcepio.types.AdministrativeGroupTlv.toString(), and org.onosproject.pcepio.types.AdministrativeGroupTlv.write().
final Logger org.onosproject.pcepio.types.AdministrativeGroupTlv.log = LoggerFactory.getLogger(AdministrativeGroupTlv.class) static protected
Definition at line 42 of file AdministrativeGroupTlv.java.
final short org.onosproject.pcepio.types.AdministrativeGroupTlv.TYPE = 3 static
Definition at line 44 of file AdministrativeGroupTlv.java.
Referenced by org.onosproject.pcepio.types.AdministrativeGroupTlv.getType(), org.onosproject.pcepio.types.AdministrativeGroupTlv.toString(), and org.onosproject.pcepio.types.AdministrativeGroupTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/AdministrativeGroupTlv.java