onos: org.onosproject.net.intent.FlowRuleIntent Class Reference
org.onosproject.net.intent.FlowRuleIntent Class Reference
An intent that enables to tell flow level operation.
Public Member Functions
FlowRuleIntent (ApplicationId appId, List< FlowRule > flowRules, Collection< NetworkResource > resources)
Creates a flow rule intent with the specified flow rules and resources.
FlowRuleIntent (ApplicationId appId, Key key, Collection< FlowRule > flowRules, Collection< NetworkResource > resources)
Creates an flow rule intent with the specified key, flow rules to be set, and required network resources.
Collection< FlowRule > flowRules ()
Returns a collection of flow rules to be set.
boolean isInstallable ()
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.Intent
IntentId id ()
Returns the intent identifier.
ApplicationId appId ()
Returns the identifier of the application that requested the intent.
int priority ()
Returns the priority of the intent.
Collection< NetworkResource > resources ()
Returns the collection of resources required for this intent.
boolean isInstallable ()
Indicates whether or not the intent is installable.
final int hashCode ()
final boolean equals (Object obj)
Key key ()
Protected Member Functions
FlowRuleIntent ()
Constructor for serializer.
Protected Member Functions inherited from org.onosproject.net.intent.Intent
Intent ()
Constructor for serializer.
Intent (ApplicationId appId, Key key, Collection< NetworkResource > resources, int priority)
Creates a new intent.
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.net.intent.Intent
static void bindIdGenerator (IdGenerator newIdGenerator)
Binds an id generator for unique intent id generation.
static void unbindIdGenerator (IdGenerator oldIdGenerator)
Unbinds an id generator.
Static Public Attributes inherited from org.onosproject.net.intent.Intent
static final int DEFAULT_INTENT_PRIORITY = 100
static final int MAX_PRIORITY = (1 << 16) - 1
static final int MIN_PRIORITY = 1
Detailed Description
An intent that enables to tell flow level operation.
This instance holds a collection of flow rules that may be executed in parallel.
Definition at line 35 of file FlowRuleIntent.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.FlowRuleIntent.FlowRuleIntent (ApplicationId appId, List< FlowRule > flowRules, Collection< NetworkResource > resources)
Creates a flow rule intent with the specified flow rules and resources.
Parameters
appId application id
flowRules flow rules to be set
resources network resource to be set
Definition at line 46 of file FlowRuleIntent.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.FlowRuleIntent.flowRules(), and org.onosproject.net.intent.Intent.resources().
org.onosproject.net.intent.FlowRuleIntent.FlowRuleIntent (ApplicationId appId, Key key, Collection< FlowRule > flowRules, Collection< NetworkResource > resources)
Creates an flow rule intent with the specified key, flow rules to be set, and required network resources.
Parameters
appId application id
key key
flowRules flow rules
resources network resources
Definition at line 59 of file FlowRuleIntent.java.
References org.onosproject.net.intent.Intent.DEFAULT_INTENT_PRIORITY.
org.onosproject.net.intent.FlowRuleIntent.FlowRuleIntent () protected
Constructor for serializer.
Definition at line 68 of file FlowRuleIntent.java.
Member Function Documentation
Collection<FlowRule> org.onosproject.net.intent.FlowRuleIntent.flowRules ()
Returns a collection of flow rules to be set.
Returns
a collection of flow rules
Definition at line 78 of file FlowRuleIntent.java.
Referenced by org.onosproject.net.intent.FlowRuleIntent.FlowRuleIntent(), and org.onosproject.net.intent.FlowRuleIntent.toString().
boolean org.onosproject.net.intent.FlowRuleIntent.isInstallable ()
Definition at line 83 of file FlowRuleIntent.java.
String org.onosproject.net.intent.FlowRuleIntent.toString ()
Definition at line 88 of file FlowRuleIntent.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.FlowRuleIntent.flowRules(), org.onosproject.net.intent.Intent.key(), and org.onosproject.net.intent.Intent.resources().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/FlowRuleIntent.java