onos: org.onosproject.core.DefaultApplicationId Class Reference
org.onosproject.core.DefaultApplicationId Class Reference
Application identifier.
Public Member Functions
DefaultApplicationId (int id, String name)
Creates a new application ID.
short id ()
Returns the application id.
String name ()
Returns the applications supplied identifier.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Application identifier.
Definition at line 26 of file DefaultApplicationId.java.
Constructor & Destructor Documentation
org.onosproject.core.DefaultApplicationId.DefaultApplicationId (int id, String name)
Creates a new application ID.
Parameters
id application identifier
name application name
Definition at line 37 of file DefaultApplicationId.java.
References org.onosproject.core.DefaultApplicationId.name().
Member Function Documentation
boolean org.onosproject.core.DefaultApplicationId.equals (Object obj)
Definition at line 65 of file DefaultApplicationId.java.
References find-device.id.
int org.onosproject.core.DefaultApplicationId.hashCode ()
Definition at line 60 of file DefaultApplicationId.java.
References org.onosproject.core.DefaultApplicationId.id().
short org.onosproject.core.DefaultApplicationId.id ()
Returns the application id.
Returns
a short value
Implements org.onosproject.core.ApplicationId.
Definition at line 50 of file DefaultApplicationId.java.
Referenced by org.onosproject.core.DefaultApplicationId.hashCode(), and org.onosproject.core.DefaultApplicationId.toString().
String org.onosproject.core.DefaultApplicationId.name ()
Returns the applications supplied identifier.
Returns
a string identifier
Implements org.onosproject.core.ApplicationId.
Definition at line 55 of file DefaultApplicationId.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.core.DefaultApplicationId.DefaultApplicationId(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.core.DefaultApplicationId.toString().
String org.onosproject.core.DefaultApplicationId.toString ()
Definition at line 77 of file DefaultApplicationId.java.
References org.onosproject.core.DefaultApplicationId.id(), and org.onosproject.core.DefaultApplicationId.name().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/core/DefaultApplicationId.java