onos: org.onosproject.cli.net.LinksListCommand Class Reference
org.onosproject.cli.net.LinksListCommand Class Reference
Lists all infrastructure links.
Static Public Member Functions
static JsonNode json (AbstractShellCommand context, Iterable< Link > links)
Produces a JSON array containing the specified links.
static ObjectNode json (AbstractShellCommand context, Link link)
Produces a JSON object for the specified link.
static String linkString (Link link)
Returns a formatted string representing the given link.
static String compactLinkString (Link link)
Returns a compact string representing the given link.
Static Public Member Functions inherited from org.onosproject.cli.AbstractShellCommand
static< T > T get (Class< T > serviceClass)
Returns the reference to the implementation of the specified service.
static String annotations (Annotations annotations)
Produces a string image of the specified key/value annotations.
static ObjectNode annotations (ObjectMapper mapper, Annotations annotations)
Produces a JSON object from the specified key/value annotations.
Protected Member Functions
void execute ()
Executes this command.
Protected Member Functions inherited from org.onosproject.cli.AbstractShellCommand
ApplicationId appId ()
Returns application ID for the CLI.
boolean outputJson ()
Indicates whether JSON format should be output.
Object doExecute () throws Exception
Additional Inherited Members
Public Member Functions inherited from org.onosproject.cli.AbstractShellCommand
void print (String format, Object...args)
Prints the arguments using the specified format.
void error (String format, Object...args)
Prints the arguments using the specified format to error stream.
ObjectMapper mapper ()
Returns the JSON object mapper.
Detailed Description
Lists all infrastructure links.
Definition at line 36 of file LinksListCommand.java.
Member Function Documentation
static String org.onosproject.cli.net.LinksListCommand.compactLinkString (Link link) static
Returns a compact string representing the given link.
Parameters
link infrastructure link
Returns
formatted link string
Definition at line 105 of file LinksListCommand.java.
References find-flow.deviceId, and obeliskHostCheck.port.
void org.onosproject.cli.net.LinksListCommand.execute () protected virtual
Executes this command.
Implements org.onosproject.cli.AbstractShellCommand.
Definition at line 46 of file LinksListCommand.java.
References find-flow.deviceId, and org.onosproject.net.link.LinkService.getLinks().
static JsonNode org.onosproject.cli.net.LinksListCommand.json (AbstractShellCommand context, Iterable< Link > links) static
Produces a JSON array containing the specified links.
Parameters
context context to use for looking up codecs
links collection of links
Returns
JSON array
Definition at line 66 of file LinksListCommand.java.
Referenced by org.onosproject.cli.net.PathListCommand.json().
static ObjectNode org.onosproject.cli.net.LinksListCommand.json (AbstractShellCommand context, Link link) static
Produces a JSON object for the specified link.
Parameters
context context to use for looking up codecs
link link to encode
Returns
JSON object
Definition at line 82 of file LinksListCommand.java.
static String org.onosproject.cli.net.LinksListCommand.linkString (Link link) static
Returns a formatted string representing the given link.
Parameters
link infrastructure link
Returns
formatted link string
Definition at line 92 of file LinksListCommand.java.
References org.onosproject.net.Annotated.annotations(), find-flow.deviceId, obeliskHostCheck.port, and org.onosproject.net.Link.state().
The documentation for this class was generated from the following file:
cli/src/main/java/org/onosproject/cli/net/LinksListCommand.java