onos: org.onosproject.vtnrsc.SegmentationId Class Reference
org.onosproject.vtnrsc.SegmentationId Class Reference
Immutable representation of a Segmentation identifier.
Public Member Functions
String segmentationId ()
Returns the segmentation identifier.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static SegmentationId segmentationId (String segmentationId)
Creates a SegmentationId object.
Detailed Description
Immutable representation of a Segmentation identifier.
Definition at line 25 of file SegmentationId.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.SegmentationId.equals (Object obj)
Definition at line 60 of file SegmentationId.java.
int org.onosproject.vtnrsc.SegmentationId.hashCode ()
Definition at line 55 of file SegmentationId.java.
static SegmentationId org.onosproject.vtnrsc.SegmentationId.segmentationId (String segmentationId) static
Creates a SegmentationId object.
Parameters
segmentationId segmentation identifier
Returns
SegmentationId
Definition at line 41 of file SegmentationId.java.
String org.onosproject.vtnrsc.SegmentationId.segmentationId ()
Returns the segmentation identifier.
Returns
segmentationId
Definition at line 50 of file SegmentationId.java.
Referenced by org.onosproject.vtnrsc.SegmentationId.toString().
String org.onosproject.vtnrsc.SegmentationId.toString ()
Definition at line 73 of file SegmentationId.java.
References org.onosproject.vtnrsc.SegmentationId.segmentationId().
Referenced by org.onosproject.vtn.table.impl.L2ForwardServiceImpl.programLocalBcastRules(), and org.onosproject.vtn.table.impl.L2ForwardServiceImpl.programLocalOut().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/SegmentationId.java