onos: org.onosproject.cli.AbstractShellCommand Class Reference
org.onosproject.cli.AbstractShellCommand Class Reference abstract
Base abstraction of Karaf shell commands.
Inherits AbstractAction, and org.onosproject.codec.CodecContext.
Inherited by AppCommand, AppCommand, it.pkg.AppCommand, org.onosproject.cli.app.ApplicationCommand, org.onosproject.cli.app.ApplicationIdListCommand, org.onosproject.cli.app.ApplicationsListCommand, org.onosproject.cli.BalanceMastersCommand, org.onosproject.cli.cfg.ComponentConfigCommand, org.onosproject.cli.cfg.NetworkConfigCommand, org.onosproject.cli.cfg.NetworkConfigRegistryCommand, org.onosproject.cli.MastersListCommand, org.onosproject.cli.MetricsListCommand, org.onosproject.cli.net.AddMeter, org.onosproject.cli.net.AddTestFlowsCommand, org.onosproject.cli.net.AnnotateDeviceCommand, org.onosproject.cli.net.ConnectivityIntentCommand, org.onosproject.cli.net.CountersListCommand, org.onosproject.cli.net.DeviceControllersCommand, org.onosproject.cli.net.DeviceRemoveCommand, org.onosproject.cli.net.DeviceRoleCommand, org.onosproject.cli.net.DeviceSetControllersCommand, org.onosproject.cli.net.DevicesListCommand, org.onosproject.cli.net.DriversListCommand, org.onosproject.cli.net.EdgePortsListCommand, org.onosproject.cli.net.FlowObjectiveCompositionCommand, org.onosproject.cli.net.FlowsListCommand, org.onosproject.cli.net.GetFlowStatistics, org.onosproject.cli.net.GetStatistics, org.onosproject.cli.net.GlobalLabelApplyCommand, org.onosproject.cli.net.GlobalLabelCommand, org.onosproject.cli.net.GlobalLabelPoolCreateCommand, org.onosproject.cli.net.GlobalLabelPoolDestoryCommand, org.onosproject.cli.net.GlobalLabelReleaseCommand, org.onosproject.cli.net.GroupsListCommand, org.onosproject.cli.net.HostRemoveCommand, org.onosproject.cli.net.HostsListCommand, org.onosproject.cli.net.IntentCycleCommand, org.onosproject.cli.net.IntentPurgeCommand, org.onosproject.cli.net.IntentPushTestCommand, org.onosproject.cli.net.IntentRemoveCommand, org.onosproject.cli.net.IntentsListCommand, org.onosproject.cli.net.InterfaceAddCommand, org.onosproject.cli.net.InterfaceRemoveCommand, org.onosproject.cli.net.InterfacesListCommand, org.onosproject.cli.net.LabelApplyCommand, org.onosproject.cli.net.LabelPoolCreateCommand, org.onosproject.cli.net.LabelPoolDestroyCommand, org.onosproject.cli.net.LabelReleaseCommand, org.onosproject.cli.net.LabelResourceCommand, org.onosproject.cli.net.LeaderCommand, org.onosproject.cli.net.LinkResourceTestCommand, org.onosproject.cli.net.LinksListCommand, org.onosproject.cli.net.MapsListCommand, org.onosproject.cli.net.Meters, org.onosproject.cli.net.PacketProcessorsListCommand, org.onosproject.cli.net.PacketRequestsListCommand, org.onosproject.cli.net.PartitionsListCommand, org.onosproject.cli.net.RandomIntentCommand, org.onosproject.cli.net.ResourceAllocationsCommand, org.onosproject.cli.net.ResourceAvailableCommand, org.onosproject.cli.net.TableStatisticsCommand, org.onosproject.cli.net.TopologyCommand, org.onosproject.cli.net.TransactionsCommand, org.onosproject.cli.net.TunnelBorrowCommand, org.onosproject.cli.net.TunnelCreateCommand, org.onosproject.cli.net.TunnelQueryCommand, org.onosproject.cli.net.TunnelQuerySubscriptionCommand, org.onosproject.cli.net.TunnelRemoveCommand, org.onosproject.cli.net.TunnelReturnCommand, org.onosproject.cli.net.TunnelUpdateCommand, org.onosproject.cli.NodeAddCommand, org.onosproject.cli.NodeRemoveCommand, org.onosproject.cli.NodesListCommand, org.onosproject.cli.RolesCommand, org.onosproject.cli.security.ReviewCommand, org.onosproject.cli.SummaryCommand, org.onosproject.cli.UiViewListCommand, org.onosproject.cordfabric.cli.FabricAddCommand, org.onosproject.cordfabric.cli.FabricRemoveCommand, org.onosproject.cordfabric.cli.FabricShowCommand, org.onosproject.cordvtn.cli.CordVtnNodeAddCommand, org.onosproject.cordvtn.cli.CordVtnNodeDeleteCommand, org.onosproject.cordvtn.cli.CordVtnNodeInitCommand, org.onosproject.cordvtn.cli.CordVtnNodeListCommand, org.onosproject.dhcp.cli.DhcpLeaseDetails, org.onosproject.dhcp.cli.DhcpListAllMappings, org.onosproject.dhcp.cli.DhcpRemoveStaticMapping, org.onosproject.dhcp.cli.DhcpSetStaticMapping, org.onosproject.distributedprimitives.cli.CounterTestIncrementCommand, org.onosproject.distributedprimitives.cli.SetTestAddCommand, org.onosproject.distributedprimitives.cli.SetTestGetCommand, org.onosproject.distributedprimitives.cli.SetTestRemoveCommand, org.onosproject.distributedprimitives.cli.TransactionalMapTestGetCommand, org.onosproject.distributedprimitives.cli.TransactionalMapTestPutCommand, org.onosproject.election.cli.ElectionTestLeaderCommand, org.onosproject.election.cli.ElectionTestRunCommand, org.onosproject.election.cli.ElectionTestWithdrawCommand, org.onosproject.flowanalyzer.FlowAnalysisCommand, org.onosproject.intentperf.IntentPerfListCommand, org.onosproject.intentperf.IntentPerfStartCommand, org.onosproject.intentperf.IntentPerfStopCommand, org.onosproject.metrics.intent.cli.IntentEventsListCommand, org.onosproject.metrics.intent.cli.IntentEventsMetricsCommand, org.onosproject.metrics.topology.cli.TopologyEventsListCommand, org.onosproject.metrics.topology.cli.TopologyEventsMetricsCommand, org.onosproject.mfwd.cli.McastDeleteCommand, org.onosproject.mfwd.cli.McastJoinCommand, org.onosproject.mfwd.cli.McastShowCommand, org.onosproject.olt.SubscriberAddCommand, org.onosproject.pim.cli.PIMShowCommand, org.onosproject.provider.nil.cli.NullControlCommand, org.onosproject.provider.nil.cli.NullLinkCommand, org.onosproject.routing.cli.AddRouteCommand, org.onosproject.routing.cli.BgpNeighborsListCommand, org.onosproject.routing.cli.BgpRoutesListCommand, org.onosproject.routing.cli.BgpSpeakersListCommand, org.onosproject.routing.cli.RemoveRouteCommand, org.onosproject.routing.cli.RoutesListCommand, org.onosproject.sdnip.cli.AddPeerCommand, org.onosproject.sdnip.cli.AddSpeakerCommand, org.onosproject.sdnip.cli.PrimaryChangeCommand, org.onosproject.sdnip.cli.RemovePeerCommand, org.onosproject.sdnip.cli.RemoveSpeakerCommand, org.onosproject.segmentrouting.cli.PolicyAddCommand, org.onosproject.segmentrouting.cli.PolicyListCommand, org.onosproject.segmentrouting.cli.PolicyRemoveCommand, org.onosproject.segmentrouting.cli.TunnelAddCommand, org.onosproject.segmentrouting.cli.TunnelListCommand, org.onosproject.segmentrouting.cli.TunnelRemoveCommand, org.onosproject.virtualbng.cli.MappingListCommand, org.onosproject.vtnrsc.cli.floatingip.FloatingIpCreateCommand, org.onosproject.vtnrsc.cli.floatingip.FloatingIpQueryCommand, org.onosproject.vtnrsc.cli.floatingip.FloatingIpRemoveCommand, org.onosproject.vtnrsc.cli.floatingip.FloatingIpUpdateCommand, org.onosproject.vtnrsc.cli.network.TenantNetworkCreateCommand, org.onosproject.vtnrsc.cli.network.TenantNetworkQueryCommand, org.onosproject.vtnrsc.cli.network.TenantNetworkRemoveCommand, org.onosproject.vtnrsc.cli.network.TenantNetworkUpdateCommand, org.onosproject.vtnrsc.cli.router.RouterCreateCommand, org.onosproject.vtnrsc.cli.router.RouterQueryCommand, org.onosproject.vtnrsc.cli.router.RouterRemoveCommand, org.onosproject.vtnrsc.cli.router.RouterUpdateCommand, org.onosproject.vtnrsc.cli.routerinterface.RouterInterfaceCreateCommand, org.onosproject.vtnrsc.cli.routerinterface.RouterInterfaceQueryCommand, org.onosproject.vtnrsc.cli.routerinterface.RouterInterfaceRemoveCommand, org.onosproject.vtnrsc.cli.subnet.SubnetCreateCommand, org.onosproject.vtnrsc.cli.subnet.SubnetQueryCommand, org.onosproject.vtnrsc.cli.subnet.SubnetRemoveCommand, org.onosproject.vtnrsc.cli.subnet.SubnetUpdateCommand, org.onosproject.vtnrsc.cli.virtualport.VirtualPortCreateCommand, org.onosproject.vtnrsc.cli.virtualport.VirtualPortQueryCommand, org.onosproject.vtnrsc.cli.virtualport.VirtualPortRemoveCommand, org.onosproject.vtnrsc.cli.virtualport.VirtualPortUpdateCommand, org.onosproject.xosintegration.cli.VoltRemoveTenantCommand, org.onosproject.xosintegration.cli.VoltTenantsCreateCommand, and org.onosproject.xosintegration.cli.VoltTenantsListCommand.
Public Member Functions
void print (String format, Object...args)
Prints the arguments using the specified format.
void error (String format, Object...args)
Prints the arguments using the specified format to error stream.
ObjectMapper mapper ()
Returns the JSON object mapper.
Static Public Member Functions
static< T > T get (Class< T > serviceClass)
Returns the reference to the implementation of the specified service.
static String annotations (Annotations annotations)
Produces a string image of the specified key/value annotations.
static ObjectNode annotations (ObjectMapper mapper, Annotations annotations)
Produces a JSON object from the specified key/value annotations.
Protected Member Functions
ApplicationId appId ()
Returns application ID for the CLI.
abstract void execute ()
Executes this command.
boolean outputJson ()
Indicates whether JSON format should be output.
Object doExecute () throws Exception
Detailed Description
Base abstraction of Karaf shell commands.
Definition at line 35 of file AbstractShellCommand.java.
Member Function Documentation
static String org.onosproject.cli.AbstractShellCommand.annotations (Annotations annotations) static
Produces a string image of the specified key/value annotations.
Parameters
annotations key/value annotations
Returns
string image with ", k1=v1, k2=v2, ..." pairs
Definition at line 89 of file AbstractShellCommand.java.
References org.onosproject.net.Annotations.keys(), and org.onosproject.net.Annotations.value().
static ObjectNode org.onosproject.cli.AbstractShellCommand.annotations (ObjectMapper mapper, Annotations annotations) static
Produces a JSON object from the specified key/value annotations.
Parameters
mapper ObjectMapper to use while converting to JSON
annotations key/value annotations
Returns
JSON object
Definition at line 104 of file AbstractShellCommand.java.
References org.onosproject.net.Annotations.keys().
ApplicationId org.onosproject.cli.AbstractShellCommand.appId () protected
Returns application ID for the CLI.
Returns
command-line application identifier
Definition at line 58 of file AbstractShellCommand.java.
Object org.onosproject.cli.AbstractShellCommand.doExecute () throws Exception protected
Definition at line 127 of file AbstractShellCommand.java.
References org.onosproject.cli.AbstractShellCommand.error(), and org.onosproject.cli.AbstractShellCommand.execute().
void org.onosproject.cli.AbstractShellCommand.error (String format, Object... args)
Prints the arguments using the specified format to error stream.
Parameters
format format string; see String#format
args arguments
Definition at line 79 of file AbstractShellCommand.java.
Referenced by org.onosproject.cli.AbstractShellCommand.doExecute().
abstract void org.onosproject.cli.AbstractShellCommand.execute () protected pure virtual
Executes this command.
Implemented in org.onosproject.cli.net.LeaderCommand, org.onosproject.vtnrsc.cli.virtualport.VirtualPortUpdateCommand, org.onosproject.vtnrsc.cli.virtualport.VirtualPortCreateCommand, org.onosproject.cli.net.PartitionsListCommand, org.onosproject.vtnrsc.cli.subnet.SubnetCreateCommand, org.onosproject.vtnrsc.cli.subnet.SubnetUpdateCommand, org.onosproject.cli.net.IntentPushTestCommand, org.onosproject.cli.net.CountersListCommand, org.onosproject.cli.net.IntentCycleCommand, org.onosproject.vtnrsc.cli.network.TenantNetworkCreateCommand, org.onosproject.vtnrsc.cli.network.TenantNetworkUpdateCommand, org.onosproject.cli.net.TransactionsCommand, org.onosproject.cli.net.AddOpticalIntentCommand, org.onosproject.segmentrouting.cli.PolicyAddCommand, org.onosproject.cli.net.GetFlowStatistics, org.onosproject.cli.net.TunnelBorrowCommand, org.onosproject.cli.net.TunnelCreateCommand, org.onosproject.vtnrsc.cli.floatingip.FloatingIpCreateCommand, org.onosproject.vtnrsc.cli.floatingip.FloatingIpUpdateCommand, org.onosproject.vtnrsc.cli.router.RouterCreateCommand, org.onosproject.cli.net.MapsListCommand, org.onosproject.cli.net.TunnelReturnCommand, org.onosproject.vtnrsc.cli.router.RouterUpdateCommand, org.onosproject.cli.net.LinkResourceTestCommand, org.onosproject.cli.cfg.ComponentConfigCommand, org.onosproject.cli.net.GroupsListCommand, org.onosproject.cli.net.IntentRemoveCommand, org.onosproject.cli.net.TunnelQueryCommand, org.onosproject.cli.net.FlowsListCommand, org.onosproject.cli.net.AddTestFlowsCommand, org.onosproject.cli.net.DevicePortsListCommand, org.onosproject.cli.net.TunnelRemoveCommand, org.onosproject.distributedprimitives.cli.CounterTestIncrementCommand, org.onosproject.cli.net.AddMplsIntent, org.onosproject.distributedprimitives.cli.SetTestRemoveCommand, org.onosproject.cli.net.IntentsListCommand, org.onosproject.routing.cli.BgpRoutesListCommand, org.onosproject.cli.net.InterfaceAddCommand, org.onosproject.cli.net.TableStatisticsCommand, org.onosproject.cli.SummaryCommand, org.onosproject.distributedprimitives.cli.SetTestGetCommand, org.onosproject.cli.app.ApplicationsListCommand, org.onosproject.vtnrsc.cli.virtualport.VirtualPortQueryCommand, org.onosproject.sdnip.cli.AddPeerCommand, org.onosproject.cli.net.AnnotateDeviceCommand, org.onosproject.cli.net.TopologyCommand, org.onosproject.routing.cli.BgpNeighborsListCommand, org.onosproject.distributedprimitives.cli.TransactionalMapTestPutCommand, org.onosproject.cli.net.DevicePortStatsCommand, org.onosproject.mfwd.cli.McastJoinCommand, org.onosproject.distributedprimitives.cli.SetTestAddCommand, org.onosproject.cli.cfg.NetworkConfigCommand, org.onosproject.sdnip.cli.AddSpeakerCommand, org.onosproject.cli.MetricsListCommand, org.onosproject.cordvtn.cli.CordVtnNodeAddCommand, org.onosproject.cli.net.DeviceSetControllersCommand, org.onosproject.cli.net.RandomIntentCommand, org.onosproject.routing.cli.RoutesListCommand, org.onosproject.cli.net.PathListCommand, org.onosproject.segmentrouting.cli.TunnelAddCommand, org.onosproject.vtnrsc.cli.routerinterface.RouterInterfaceCreateCommand, org.onosproject.sdnip.cli.RemovePeerCommand, org.onosproject.distributedprimitives.cli.TransactionalMapTestGetCommand, org.onosproject.cli.app.ApplicationCommand, org.onosproject.cli.net.DeviceRoleCommand, org.onosproject.cli.security.ReviewCommand, org.onosproject.olt.SubscriberAddCommand, org.onosproject.sdnip.cli.RemoveSpeakerCommand, org.onosproject.xosintegration.cli.VoltTenantsCreateCommand, org.onosproject.cli.net.AddPointToPointIntentCommand, org.onosproject.provider.nil.cli.NullLinkCommand, org.onosproject.cordfabric.cli.FabricAddCommand, org.onosproject.mfwd.cli.McastDeleteCommand, org.onosproject.routing.cli.BgpSpeakersListCommand, org.onosproject.vtnrsc.cli.floatingip.FloatingIpRemoveCommand, org.onosproject.dhcp.cli.DhcpSetStaticMapping, org.onosproject.metrics.intent.cli.IntentEventsMetricsCommand, org.onosproject.metrics.topology.cli.TopologyEventsMetricsCommand, org.onosproject.vtnrsc.cli.floatingip.FloatingIpQueryCommand, org.onosproject.cli.net.AddMeter, org.onosproject.cli.net.GetStatistics, org.onosproject.cli.net.LinksListCommand, org.onosproject.cli.net.TunnelUpdateCommand, org.onosproject.cli.net.AddHostToHostIntentCommand, org.onosproject.cli.net.AddMultiPointToSinglePointIntentCommand, org.onosproject.cli.net.ResourceAvailableCommand, org.onosproject.cli.NodeAddCommand, org.onosproject.cli.NodesListCommand, org.onosproject.cli.net.AddSinglePointToMultiPointIntentCommand, org.onosproject.cli.net.ClusterDevicesCommand, org.onosproject.cli.net.DevicesListCommand, org.onosproject.cli.net.DriversListCommand, org.onosproject.cli.net.HostsListCommand, org.onosproject.cli.net.InterfaceRemoveCommand, org.onosproject.cli.net.LabelApplyCommand, org.onosproject.cli.net.ResourceAllocationsCommand, org.onosproject.cli.net.WipeOutCommand, org.onosproject.cli.RolesCommand, org.onosproject.vtnrsc.cli.router.RouterRemoveCommand, org.onosproject.xosintegration.cli.VoltTenantsListCommand, org.onosproject.cli.net.LabelReleaseCommand, org.onosproject.cli.net.TunnelQuerySubscriptionCommand, org.onosproject.provider.nil.cli.NullControlCommand, org.onosproject.vtnrsc.cli.router.RouterQueryCommand, org.onosproject.dhcp.cli.DhcpRemoveStaticMapping, org.onosproject.metrics.topology.cli.TopologyEventsListCommand, org.onosproject.routing.cli.AddRouteCommand, org.onosproject.segmentrouting.cli.TunnelRemoveCommand, org.onosproject.cli.MastersListCommand, org.onosproject.cli.net.EdgePortsListCommand, org.onosproject.cli.net.LabelPoolCreateCommand, org.onosproject.cli.net.Meters, org.onosproject.mfwd.cli.McastShowCommand, org.onosproject.routing.cli.RemoveRouteCommand, org.onosproject.virtualbng.cli.MappingListCommand, org.onosproject.vtnrsc.cli.network.TenantNetworkQueryCommand, org.onosproject.vtnrsc.cli.network.TenantNetworkRemoveCommand, org.onosproject.vtnrsc.cli.virtualport.VirtualPortRemoveCommand, org.onosproject.cli.app.ApplicationIdListCommand, org.onosproject.cli.net.ClustersListCommand, org.onosproject.cli.net.FlowObjectiveCompositionCommand, org.onosproject.cli.net.GlobalLabelPoolCreateCommand, org.onosproject.cordvtn.cli.CordVtnNodeDeleteCommand, org.onosproject.cordvtn.cli.CordVtnNodeInitCommand, org.onosproject.metrics.intent.cli.IntentEventsListCommand, org.onosproject.segmentrouting.cli.PolicyRemoveCommand, org.onosproject.intentperf.IntentPerfListCommand, org.onosproject.vtnrsc.cli.subnet.SubnetQueryCommand, org.onosproject.vtnrsc.cli.subnet.SubnetRemoveCommand, org.onosproject.cli.cfg.NetworkConfigRegistryCommand, org.onosproject.cli.net.ClusterLinksCommand, org.onosproject.cli.net.DeviceControllersCommand, org.onosproject.cli.net.GlobalLabelApplyCommand, org.onosproject.cli.net.InterfacesListCommand, org.onosproject.cordvtn.cli.CordVtnNodeListCommand, org.onosproject.cordfabric.cli.FabricRemoveCommand, org.onosproject.cordfabric.cli.FabricShowCommand, org.onosproject.vtnrsc.cli.routerinterface.RouterInterfaceQueryCommand, org.onosproject.cli.UiViewListCommand, org.onosproject.sdnip.cli.PrimaryChangeCommand, org.onosproject.xosintegration.cli.VoltRemoveTenantCommand, org.onosproject.cli.net.DeviceRemoveCommand, org.onosproject.cli.net.GlobalLabelReleaseCommand, org.onosproject.cli.net.HostRemoveCommand, org.onosproject.cli.net.LabelResourceCommand, org.onosproject.cli.net.PacketProcessorsListCommand, org.onosproject.dhcp.cli.DhcpListAllMappings, org.onosproject.segmentrouting.cli.PolicyListCommand, org.onosproject.vtnrsc.cli.routerinterface.RouterInterfaceRemoveCommand, org.onosproject.cli.NodeRemoveCommand, org.onosproject.segmentrouting.cli.TunnelListCommand, org.onosproject.election.cli.ElectionTestLeaderCommand, org.onosproject.pim.cli.PIMShowCommand, org.onosproject.election.cli.ElectionTestWithdrawCommand, org.onosproject.cli.net.PacketRequestsListCommand, org.onosproject.dhcp.cli.DhcpLeaseDetails, org.onosproject.election.cli.ElectionTestRunCommand, org.onosproject.cli.net.IntentPurgeCommand, org.onosproject.cli.net.GlobalLabelCommand, org.onosproject.cli.net.LabelPoolDestroyCommand, org.onosproject.flowanalyzer.FlowAnalysisCommand, org.onosproject.intentperf.IntentPerfStartCommand, org.onosproject.intentperf.IntentPerfStopCommand, org.onosproject.cli.BalanceMastersCommand, AppCommand, AppCommand, it.pkg.AppCommand, and org.onosproject.cli.net.GlobalLabelPoolDestoryCommand.
Referenced by org.onosproject.cli.AbstractShellCommand.doExecute().
static <T> T org.onosproject.cli.AbstractShellCommand.get (Class< T > serviceClass) static
Returns the reference to the implementation of the specified service.
Parameters
serviceClass service class
<T> type of service
Returns
service implementation
Exceptions
org.onlab.osgi.ServiceNotFoundException if service is unavailable
Definition at line 49 of file AbstractShellCommand.java.
ObjectMapper org.onosproject.cli.AbstractShellCommand.mapper ()
Returns the JSON object mapper.
Returns
object mapper
Implements org.onosproject.codec.CodecContext.
Definition at line 141 of file AbstractShellCommand.java.
boolean org.onosproject.cli.AbstractShellCommand.outputJson () protected
Indicates whether JSON format should be output.
Returns
true if JSON is requested
Definition at line 122 of file AbstractShellCommand.java.
void org.onosproject.cli.AbstractShellCommand.print (String format, Object... args)
Prints the arguments using the specified format.
Parameters
format format string; see String#format
args arguments
Definition at line 69 of file AbstractShellCommand.java.
The documentation for this class was generated from the following file:
cli/src/main/java/org/onosproject/cli/AbstractShellCommand.java