onos: org.onosproject.bgpio.types.AreaIDTlv Class Reference
org.onosproject.bgpio.types.AreaIDTlv Class Reference
Provides AreaID Tlv which contains opaque value (32 Bit Area-ID).
Public Member Functions
AreaIDTlv (int areaID)
Constructor to initialize areaID.
int getAreaID ()
Returns opaque value of area id.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of BGP Message to channel buffer.
short getType ()
Returns the Type of BGP Message.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static AreaIDTlv of (final int areaID)
Returns object of this class with specified areaID.
static AreaIDTlv read (ChannelBuffer cb)
Reads the channel buffer and returns object of AreaIDTlv.
Static Public Attributes
static final short TYPE = 514
static final short LENGTH = 4
Detailed Description
Provides AreaID Tlv which contains opaque value (32 Bit Area-ID).
Definition at line 27 of file AreaIDTlv.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.AreaIDTlv.AreaIDTlv (int areaID)
Constructor to initialize areaID.
Parameters
areaID of BGP AreaID Tlv
Definition at line 49 of file AreaIDTlv.java.
Referenced by org.onosproject.bgpio.types.AreaIDTlv.equals(), and org.onosproject.bgpio.types.AreaIDTlv.of().
Member Function Documentation
int org.onosproject.bgpio.types.AreaIDTlv.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 115 of file AreaIDTlv.java.
References org.onosproject.bgpio.types.AreaIDTlv.equals().
boolean org.onosproject.bgpio.types.AreaIDTlv.equals (Object obj)
Definition at line 78 of file AreaIDTlv.java.
References org.onosproject.bgpio.types.AreaIDTlv.AreaIDTlv().
Referenced by org.onosproject.bgpio.types.AreaIDTlv.compareTo().
int org.onosproject.bgpio.types.AreaIDTlv.getAreaID ()
Returns opaque value of area id.
Returns
opaque value of area id
Definition at line 68 of file AreaIDTlv.java.
short org.onosproject.bgpio.types.AreaIDTlv.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 110 of file AreaIDTlv.java.
References org.onosproject.bgpio.types.AreaIDTlv.TYPE.
int org.onosproject.bgpio.types.AreaIDTlv.hashCode ()
Definition at line 73 of file AreaIDTlv.java.
static AreaIDTlv org.onosproject.bgpio.types.AreaIDTlv.of (final int areaID) static
Returns object of this class with specified areaID.
Parameters
areaID opaque value of area id
Returns
object of AreaIDTlv
Definition at line 59 of file AreaIDTlv.java.
References org.onosproject.bgpio.types.AreaIDTlv.AreaIDTlv().
static AreaIDTlv org.onosproject.bgpio.types.AreaIDTlv.read (ChannelBuffer cb) static
Reads the channel buffer and returns object of AreaIDTlv.
Parameters
cb ChannelBuffer
Returns
object of AreaIDTlv
Definition at line 105 of file AreaIDTlv.java.
String org.onosproject.bgpio.types.AreaIDTlv.toString ()
Definition at line 123 of file AreaIDTlv.java.
References org.onosproject.bgpio.types.AreaIDTlv.LENGTH, and org.onosproject.bgpio.types.AreaIDTlv.TYPE.
int org.onosproject.bgpio.types.AreaIDTlv.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 91 of file AreaIDTlv.java.
References org.onosproject.bgpio.types.AreaIDTlv.LENGTH, and org.onosproject.bgpio.types.AreaIDTlv.TYPE.
Member Data Documentation
final short org.onosproject.bgpio.types.AreaIDTlv.LENGTH = 4 static
Definition at line 40 of file AreaIDTlv.java.
Referenced by org.onosproject.bgpio.types.AreaIDTlv.toString(), and org.onosproject.bgpio.types.AreaIDTlv.write().
final short org.onosproject.bgpio.types.AreaIDTlv.TYPE = 514 static
Definition at line 39 of file AreaIDTlv.java.
Referenced by org.onosproject.bgpio.types.AreaIDTlv.getType(), org.onosproject.bgpio.types.AreaIDTlv.toString(), and org.onosproject.bgpio.types.AreaIDTlv.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/AreaIDTlv.java