onos: org.onosproject.pcepio.types.TELinkDescriptorsTlv Class Reference
org.onosproject.pcepio.types.TELinkDescriptorsTlv Class Reference
Provides TE Link Descriptors TLV.
Public Member Functions
TELinkDescriptorsTlv (LinkedList< PcepValueType > llLinkDescriptorsSubTLVs)
Constructor to initialize llLinkDescriptorsSubTLVs.
LinkedList< PcepValueType > getllLinkDescriptorsSubTLVs ()
Returns linked list of Link Attribute of Sub TLV.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static TELinkDescriptorsTlv of (final LinkedList< PcepValueType > llLinkDescriptorsSubTLVs)
Returns object of TELinkDescriptorsTLV.
static PcepValueType read (ChannelBuffer c, short length) throws PcepParseException
Reads channel buffer and returns object of TELinkDescriptorsTLV.
Public Attributes
short hLength
Static Public Attributes
static final short TYPE = 1070
static final int TLV_HEADER_LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(TELinkDescriptorsTlv.class)
Detailed Description
Provides TE Link Descriptors TLV.
Definition at line 34 of file TELinkDescriptorsTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.TELinkDescriptorsTlv.TELinkDescriptorsTlv (LinkedList< PcepValueType > llLinkDescriptorsSubTLVs)
Constructor to initialize llLinkDescriptorsSubTLVs.
Parameters
llLinkDescriptorsSubTLVs of PcepValueType
Definition at line 65 of file TELinkDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkDescriptorsTlv.equals(), org.onosproject.pcepio.types.TELinkDescriptorsTlv.of(), and org.onosproject.pcepio.types.TELinkDescriptorsTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.TELinkDescriptorsTlv.equals (Object obj)
Definition at line 109 of file TELinkDescriptorsTlv.java.
References org.onosproject.pcepio.types.TELinkDescriptorsTlv.TELinkDescriptorsTlv().
short org.onosproject.pcepio.types.TELinkDescriptorsTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 99 of file TELinkDescriptorsTlv.java.
References org.onosproject.pcepio.types.TELinkDescriptorsTlv.hLength.
LinkedList<PcepValueType> org.onosproject.pcepio.types.TELinkDescriptorsTlv.getllLinkDescriptorsSubTLVs ()
Returns linked list of Link Attribute of Sub TLV.
Returns
llLinkDescriptorsSubTLVs linked list of Link Attribute of Sub TLV
Definition at line 84 of file TELinkDescriptorsTlv.java.
short org.onosproject.pcepio.types.TELinkDescriptorsTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 94 of file TELinkDescriptorsTlv.java.
References org.onosproject.pcepio.types.TELinkDescriptorsTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.TELinkDescriptorsTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 89 of file TELinkDescriptorsTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.TELinkDescriptorsTlv.hashCode ()
Definition at line 104 of file TELinkDescriptorsTlv.java.
static TELinkDescriptorsTlv org.onosproject.pcepio.types.TELinkDescriptorsTlv.of (final LinkedList< PcepValueType > llLinkDescriptorsSubTLVs) static
Returns object of TELinkDescriptorsTLV.
Parameters
llLinkDescriptorsSubTLVs of PcepValueType
Returns
object of TELinkDescriptorsTLV
Definition at line 75 of file TELinkDescriptorsTlv.java.
References org.onosproject.pcepio.types.TELinkDescriptorsTlv.TELinkDescriptorsTlv().
static PcepValueType org.onosproject.pcepio.types.TELinkDescriptorsTlv.read (ChannelBuffer c, short length) throws PcepParseException static
Reads channel buffer and returns object of TELinkDescriptorsTLV.
Parameters
c input channel buffer
length length
Returns
object of TELinkDescriptorsTLV
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 183 of file TELinkDescriptorsTlv.java.
References org.onosproject.pcepio.types.TELinkDescriptorsTlv.hLength, find-link-in-cluster.length, org.onosproject.pcepio.types.TELinkDescriptorsTlv.TELinkDescriptorsTlv(), org.onosproject.pcepio.types.TELinkDescriptorsTlv.TLV_HEADER_LENGTH, org.onosproject.pcepio.types.IPv6NeighborAddressTlv.VALUE_LENGTH, and org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.VALUE_LENGTH.
String org.onosproject.pcepio.types.TELinkDescriptorsTlv.toString ()
Definition at line 244 of file TELinkDescriptorsTlv.java.
References org.onosproject.pcepio.types.TELinkDescriptorsTlv.hLength, and org.onosproject.pcepio.types.TELinkDescriptorsTlv.TYPE.
int org.onosproject.pcepio.types.TELinkDescriptorsTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 144 of file TELinkDescriptorsTlv.java.
References org.onosproject.pcepio.types.TELinkDescriptorsTlv.hLength, org.onosproject.pcepio.types.TELinkDescriptorsTlv.TLV_HEADER_LENGTH, and org.onosproject.pcepio.types.TELinkDescriptorsTlv.TYPE.
Member Data Documentation
short org.onosproject.pcepio.types.TELinkDescriptorsTlv.hLength
Definition at line 53 of file TELinkDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkDescriptorsTlv.getLength(), org.onosproject.pcepio.types.TELinkDescriptorsTlv.read(), org.onosproject.pcepio.types.TELinkDescriptorsTlv.toString(), and org.onosproject.pcepio.types.TELinkDescriptorsTlv.write().
final Logger org.onosproject.pcepio.types.TELinkDescriptorsTlv.log = LoggerFactory.getLogger(TELinkDescriptorsTlv.class) static protected
Definition at line 50 of file TELinkDescriptorsTlv.java.
final int org.onosproject.pcepio.types.TELinkDescriptorsTlv.TLV_HEADER_LENGTH = 4 static
Definition at line 55 of file TELinkDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkDescriptorsTlv.read(), and org.onosproject.pcepio.types.TELinkDescriptorsTlv.write().
final short org.onosproject.pcepio.types.TELinkDescriptorsTlv.TYPE = 1070 static
Definition at line 52 of file TELinkDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkDescriptorsTlv.getType(), org.onosproject.pcepio.types.TELinkDescriptorsTlv.toString(), and org.onosproject.pcepio.types.TELinkDescriptorsTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/TELinkDescriptorsTlv.java