onos: org.onlab.util.KryoNamespace Class Reference
org.onlab.util.KryoNamespace Class Reference
Pool of Kryo instances, with classes pre-registered.
Classes
class Builder
KryoNamespace builder.
class RegistrationBlock
Public Member Functions
KryoNamespace populate (int instances)
Populates the Kryo pool.
byte[] serialize (final Object obj)
Serializes given object to byte array using Kryo instance in pool.
byte[] serialize (final Object obj, final int bufferSize)
Serializes given object to byte array using Kryo instance in pool.
void serialize (final Object obj, final ByteBuffer buffer)
Serializes given object to byte buffer using Kryo instance in pool.
void serialize (final Object obj, final OutputStream stream)
Serializes given object to OutputStream using Kryo instance in pool.
void serialize (final Object obj, final OutputStream stream, final int bufferSize)
Serializes given object to OutputStream using Kryo instance in pool.
Kryo create ()
Creates a Kryo instance.
Kryo borrow ()
void release (Kryo kryo)
String toString ()
Static Public Member Functions
static Builder newBuilder ()
Creates a new KryoNamespace builder.
Static Public Attributes
static final int DEFAULT_BUFFER_SIZE = 4096
Default buffer size used for serialization.
static final int MAX_BUFFER_SIZE = 100 * 1000 * 1000
static final int FLOATING_ID = -1
ID to use if this KryoNamespace does not define registration id.
static final int INITIAL_ID = 11
Smallest ID free to use for user defined registrations.
Detailed Description
Pool of Kryo instances, with classes pre-registered.
Definition at line 41 of file KryoNamespace.java.
Member Function Documentation
Kryo org.onlab.util.KryoNamespace.borrow ()
Definition at line 391 of file KryoNamespace.java.
Referenced by org.onlab.util.KryoNamespace.serialize().
Kryo org.onlab.util.KryoNamespace.create ()
Creates a Kryo instance.
Returns
Kryo instance
Definition at line 370 of file KryoNamespace.java.
References org.onlab.util.KryoNamespace.FLOATING_ID.
Referenced by org.onlab.util.KryoNamespace.populate().
static Builder org.onlab.util.KryoNamespace.newBuilder () static
Creates a new KryoNamespace builder.
Returns
builder
Definition at line 186 of file KryoNamespace.java.
KryoNamespace org.onlab.util.KryoNamespace.populate (int instances)
Populates the Kryo pool.
Parameters
instances to add to the pool
Returns
this
Definition at line 207 of file KryoNamespace.java.
References org.onlab.util.KryoNamespace.create(), and org.onlab.util.KryoNamespace.release().
void org.onlab.util.KryoNamespace.release (Kryo kryo)
Definition at line 396 of file KryoNamespace.java.
Referenced by org.onlab.util.KryoNamespace.populate(), and org.onlab.util.KryoNamespace.serialize().
byte [] org.onlab.util.KryoNamespace.serialize (final Object obj)
Serializes given object to byte array using Kryo instance in pool.
Note: Serialized bytes must be smaller than MAX_BUFFER_SIZE.
Parameters
obj Object to serialize
Returns
serialized bytes
Definition at line 223 of file KryoNamespace.java.
References org.onlab.util.KryoNamespace.DEFAULT_BUFFER_SIZE.
Referenced by org.onosproject.driver.pipeline.OVSCorsaPipeline.next(), org.onosproject.driver.pipeline.CentecV350Pipeline.next(), and org.onlab.util.KryoNamespace.serialize().
byte [] org.onlab.util.KryoNamespace.serialize (final Object obj, final int bufferSize)
Serializes given object to byte array using Kryo instance in pool.
Parameters
obj Object to serialize
bufferSize maximum size of serialized bytes
Returns
serialized bytes
Definition at line 234 of file KryoNamespace.java.
References org.onlab.util.KryoNamespace.borrow(), org.onlab.util.KryoNamespace.MAX_BUFFER_SIZE, and org.onlab.util.KryoNamespace.release().
void org.onlab.util.KryoNamespace.serialize (final Object obj, final ByteBuffer buffer)
Serializes given object to byte buffer using Kryo instance in pool.
Parameters
obj Object to serialize
buffer to write to
Definition at line 256 of file KryoNamespace.java.
References org.onlab.util.KryoNamespace.borrow(), and org.onlab.util.KryoNamespace.release().
void org.onlab.util.KryoNamespace.serialize (final Object obj, final OutputStream stream)
Serializes given object to OutputStream using Kryo instance in pool.
Parameters
obj Object to serialize
stream to write to
Definition at line 273 of file KryoNamespace.java.
References org.onlab.util.KryoNamespace.DEFAULT_BUFFER_SIZE, and org.onlab.util.KryoNamespace.serialize().
void org.onlab.util.KryoNamespace.serialize (final Object obj, final OutputStream stream, final int bufferSize)
Serializes given object to OutputStream using Kryo instance in pool.
Parameters
obj Object to serialize
stream to write to
bufferSize size of the buffer in front of the stream
Definition at line 284 of file KryoNamespace.java.
References org.onlab.util.KryoNamespace.borrow(), and org.onlab.util.KryoNamespace.release().
String org.onlab.util.KryoNamespace.toString ()
Definition at line 406 of file KryoNamespace.java.
Member Data Documentation
final int org.onlab.util.KryoNamespace.DEFAULT_BUFFER_SIZE = 4096 static
Default buffer size used for serialization.
See Also
#serialize(Object)
Definition at line 48 of file KryoNamespace.java.
Referenced by org.onlab.util.KryoNamespace.serialize().
final int org.onlab.util.KryoNamespace.FLOATING_ID = -1 static
ID to use if this KryoNamespace does not define registration id.
Definition at line 54 of file KryoNamespace.java.
Referenced by org.onlab.util.KryoNamespace.create().
final int org.onlab.util.KryoNamespace.INITIAL_ID = 11 static
Smallest ID free to use for user defined registrations.
Definition at line 59 of file KryoNamespace.java.
final int org.onlab.util.KryoNamespace.MAX_BUFFER_SIZE = 100 * 1000 * 1000 static
Definition at line 49 of file KryoNamespace.java.
Referenced by org.onlab.util.KryoNamespace.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/util/KryoNamespace.java