onos: org.onosproject.netconf.NetconfDeviceInfo Class Reference
org.onosproject.netconf.NetconfDeviceInfo Class Reference
Represents a Netconf device information.
Public Member Functions
NetconfDeviceInfo (String name, String password, IpAddress ipAddress, int port)
Information for contacting the controller.
NetconfDeviceInfo (String name, String password, IpAddress ipAddress, int port, String keyString)
Information for contacting the controller.
String name ()
Exposes the name of the controller.
String password ()
Exposes the password of the controller.
IpAddress ip ()
Exposes the ip address of the controller.
int port ()
Exposes the port of the controller.
File getKeyFile ()
Exposes the keyFile of the controller.
String toString ()
Return the info about the device in a string.
DeviceId getDeviceId ()
Return the DeviceId about the device containing the URI.
int hashCode ()
boolean equals (Object toBeCompared)
Static Public Attributes
static final Logger log
Detailed Description
Represents a Netconf device information.
Definition at line 33 of file NetconfDeviceInfo.java.
Constructor & Destructor Documentation
org.onosproject.netconf.NetconfDeviceInfo.NetconfDeviceInfo (String name, String password, IpAddress ipAddress, int port)
Information for contacting the controller.
Parameters
name the connection type
password the password for the device
ipAddress the ip address
port the tcp port
Definition at line 53 of file NetconfDeviceInfo.java.
References org.onosproject.netconf.NetconfDeviceInfo.name(), org.onosproject.netconf.NetconfDeviceInfo.password(), and org.onosproject.netconf.NetconfDeviceInfo.port().
Referenced by org.onosproject.netconf.NetconfDeviceInfo.equals().
org.onosproject.netconf.NetconfDeviceInfo.NetconfDeviceInfo (String name, String password, IpAddress ipAddress, int port, String keyString)
Information for contacting the controller.
Parameters
name the connection type
password the password for the device
ipAddress the ip address
port the tcp port
keyString the string cointaing the key.
Definition at line 73 of file NetconfDeviceInfo.java.
References org.onosproject.netconf.NetconfDeviceInfo.name(), org.onosproject.netconf.NetconfDeviceInfo.password(), and org.onosproject.netconf.NetconfDeviceInfo.port().
Member Function Documentation
boolean org.onosproject.netconf.NetconfDeviceInfo.equals (Object toBeCompared)
Definition at line 161 of file NetconfDeviceInfo.java.
References org.onosproject.netconf.NetconfDeviceInfo.ip(), org.onosproject.netconf.NetconfDeviceInfo.name(), org.onosproject.netconf.NetconfDeviceInfo.NetconfDeviceInfo(), org.onosproject.netconf.NetconfDeviceInfo.password(), and org.onosproject.netconf.NetconfDeviceInfo.port().
DeviceId org.onosproject.netconf.NetconfDeviceInfo.getDeviceId ()
Return the DeviceId about the device containing the URI.
Returns
DeviceId
Definition at line 145 of file NetconfDeviceInfo.java.
References org.onosproject.netconf.NetconfDeviceInfo.toString().
Referenced by org.onosproject.netconf.ctl.NetconfControllerImpl.connectDevice(), and org.onosproject.netconf.ctl.NetconfControllerImpl.removeDevice().
File org.onosproject.netconf.NetconfDeviceInfo.getKeyFile ()
Exposes the keyFile of the controller.
Returns
int port address
Definition at line 126 of file NetconfDeviceInfo.java.
int org.onosproject.netconf.NetconfDeviceInfo.hashCode ()
Definition at line 156 of file NetconfDeviceInfo.java.
References org.onosproject.netconf.NetconfDeviceInfo.name(), and org.onosproject.netconf.NetconfDeviceInfo.port().
IpAddress org.onosproject.netconf.NetconfDeviceInfo.ip ()
Exposes the ip address of the controller.
Returns
IpAddress ip address
Definition at line 108 of file NetconfDeviceInfo.java.
Referenced by org.onosproject.netconf.NetconfDeviceInfo.equals(), onos.ONOS.start(), and onos.ONOS.updateHazelcast().
String org.onosproject.netconf.NetconfDeviceInfo.name ()
Exposes the name of the controller.
Returns
String name
Definition at line 90 of file NetconfDeviceInfo.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.netconf.NetconfDeviceInfo.equals(), org.onosproject.netconf.NetconfDeviceInfo.hashCode(), org.onosproject.netconf.NetconfDeviceInfo.NetconfDeviceInfo(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.netconf.NetconfDeviceInfo.toString().
String org.onosproject.netconf.NetconfDeviceInfo.password ()
Exposes the password of the controller.
Returns
String password
Definition at line 99 of file NetconfDeviceInfo.java.
Referenced by org.onosproject.netconf.NetconfDeviceInfo.equals(), and org.onosproject.netconf.NetconfDeviceInfo.NetconfDeviceInfo().
int org.onosproject.netconf.NetconfDeviceInfo.port ()
Exposes the port of the controller.
Returns
int port address
Definition at line 117 of file NetconfDeviceInfo.java.
Referenced by org.onosproject.netconf.NetconfDeviceInfo.equals(), org.onosproject.netconf.NetconfDeviceInfo.hashCode(), org.onosproject.netconf.NetconfDeviceInfo.NetconfDeviceInfo(), and org.onosproject.netconf.NetconfDeviceInfo.toString().
String org.onosproject.netconf.NetconfDeviceInfo.toString ()
Return the info about the device in a string.
String format: "netconf:name@ip:port"
Returns
String device info
Definition at line 136 of file NetconfDeviceInfo.java.
References org.onosproject.netconf.NetconfDeviceInfo.name(), and org.onosproject.netconf.NetconfDeviceInfo.port().
Referenced by org.onosproject.netconf.NetconfDeviceInfo.getDeviceId().
Member Data Documentation
final Logger org.onosproject.netconf.NetconfDeviceInfo.log static
Initial value:
= LoggerFactory
            .getLogger(NetconfDeviceInfo.class)
Definition at line 35 of file NetconfDeviceInfo.java.
The documentation for this class was generated from the following file:
protocols/netconf/api/src/main/java/org/onosproject/netconf/NetconfDeviceInfo.java