onos: org.onosproject.pim.impl.PIMNeighbor Class Reference
org.onosproject.pim.impl.PIMNeighbor Class Reference
PIMNeighbor represents all the PIM routers that have sent us hello messages, or that possibly have been statically configured.
Public Member Functions
PIMNeighbor (IpAddress ipaddr, MacAddress macaddr, PIMInterface pimInterface)
Construct this neighbor from the address and connect point.
IpAddress getPrimaryAddr ()
Get the primary address of this neighbor.
void setPrimaryAddr (IpAddress primaryAddr)
Set the primary address of this neighbor.
int getPriority ()
Get the priority this neighbor has advertised to us.
void setPriority (int priority)
Set the priority for this neighbor.
int getGenId ()
Get the generation ID.
void setGenId (int genId)
Set the generation ID.
short getHoldtime ()
Get the holdtime for this neighbor.
void setholdtime (short holdtime)
Set the holdtime for this neighbor.
boolean isDr ()
Is this neighbor the designated router on this connect point?
void setIsDr (boolean isDr)
Set this router as the designated router on this connect point.
PIMInterface getPimInterface ()
The ConnectPoint this neighbor is connected to.
void refresh (PIMHello hello)
We have received a fresh hello from this neighbor, now we need to process it.
String toString ()
Detailed Description
PIMNeighbor represents all the PIM routers that have sent us hello messages, or that possibly have been statically configured.
Definition at line 37 of file PIMNeighbor.java.
Constructor & Destructor Documentation
org.onosproject.pim.impl.PIMNeighbor.PIMNeighbor (IpAddress ipaddr, MacAddress macaddr, PIMInterface pimInterface)
Construct this neighbor from the address and connect point.
Parameters
ipaddr IP Address of neighbor
macaddr MAC Address of the neighbor
pimInterface The PIMInterface of this neighbor
Definition at line 73 of file PIMNeighbor.java.
Member Function Documentation
int org.onosproject.pim.impl.PIMNeighbor.getGenId ()
Get the generation ID.
Returns
the generation ID.
Definition at line 121 of file PIMNeighbor.java.
short org.onosproject.pim.impl.PIMNeighbor.getHoldtime ()
Get the holdtime for this neighbor.
Returns
the holdtime
Definition at line 139 of file PIMNeighbor.java.
PIMInterface org.onosproject.pim.impl.PIMNeighbor.getPimInterface ()
The ConnectPoint this neighbor is connected to.
Returns
the ConnectPoint
Definition at line 175 of file PIMNeighbor.java.
IpAddress org.onosproject.pim.impl.PIMNeighbor.getPrimaryAddr ()
Get the primary address of this neighbor.
Returns
the primary IP address.
Definition at line 85 of file PIMNeighbor.java.
Referenced by org.onosproject.pim.impl.PIMInterface.addNeighbor(), org.onosproject.pim.impl.PIMInterface.areWeDr(), and org.onosproject.pim.impl.PIMInterface.electDR().
int org.onosproject.pim.impl.PIMNeighbor.getPriority ()
Get the priority this neighbor has advertised to us.
Returns
the priority
Definition at line 103 of file PIMNeighbor.java.
Referenced by org.onosproject.pim.impl.PIMInterface.electDR().
boolean org.onosproject.pim.impl.PIMNeighbor.isDr ()
Is this neighbor the designated router on this connect point?
Returns
true if so, false if not.
Definition at line 157 of file PIMNeighbor.java.
Referenced by org.onosproject.pim.impl.PIMNeighbor.refresh(), org.onosproject.pim.impl.PIMNeighbor.setIsDr(), and org.onosproject.pim.impl.PIMNeighbor.toString().
void org.onosproject.pim.impl.PIMNeighbor.refresh (PIMHello hello)
We have received a fresh hello from this neighbor, now we need to process it.
Depending on the values received in the the hello options may force a re-election process.
We will also refresh the timeout for this neighbor.
Parameters
hello copy of the hello we'll be able to extract options from.
Definition at line 188 of file PIMNeighbor.java.
References org.onosproject.pim.impl.PIMInterface.getDesignatedRouter(), org.onlab.packet.pim.PIMHello.getOptions(), and org.onosproject.pim.impl.PIMNeighbor.isDr().
void org.onosproject.pim.impl.PIMNeighbor.setGenId (int genId)
Set the generation ID.
Parameters
genId the generation ID.
Definition at line 130 of file PIMNeighbor.java.
void org.onosproject.pim.impl.PIMNeighbor.setholdtime (short holdtime)
Set the holdtime for this neighbor.
Parameters
holdtime the holdtime.
Definition at line 148 of file PIMNeighbor.java.
void org.onosproject.pim.impl.PIMNeighbor.setIsDr (boolean isDr)
Set this router as the designated router on this connect point.
Parameters
isDr True is this neighbor is the DR false otherwise
Definition at line 166 of file PIMNeighbor.java.
References org.onosproject.pim.impl.PIMNeighbor.isDr().
void org.onosproject.pim.impl.PIMNeighbor.setPrimaryAddr (IpAddress primaryAddr)
Set the primary address of this neighbor.
Parameters
primaryAddr the address we'll use when sending hello messages
Definition at line 94 of file PIMNeighbor.java.
void org.onosproject.pim.impl.PIMNeighbor.setPriority (int priority)
Set the priority for this neighbor.
Parameters
priority This neighbors priority.
Definition at line 112 of file PIMNeighbor.java.
String org.onosproject.pim.impl.PIMNeighbor.toString ()
Definition at line 307 of file PIMNeighbor.java.
References org.onosproject.pim.impl.PIMNeighbor.isDr().
The documentation for this class was generated from the following file:
apps/pim/src/main/java/org/onosproject/pim/impl/PIMNeighbor.java