onos: org.onlab.packet.ipv6.Fragment Class Reference
org.onlab.packet.ipv6.Fragment Class Reference
Implements IPv6 fragment extension header format.
Public Member Functions
byte getNextHeader ()
Gets the type of next header.
Fragment setNextHeader (final byte nextHeader)
Sets the type of next header.
short getFragmentOffset ()
Gets the fragment offset of this header.
Fragment setFragmentOffset (final short fragmentOffset)
Sets the fragment offset of this header.
byte getMoreFragment ()
Gets the more fragment flag of this header.
Fragment setMoreFragment (final byte moreFragment)
Sets the more fragment flag of this header.
int getIdentification ()
Gets the identification of this header.
Fragment setIdentification (final int identification)
Sets the identification of this header.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer< Fragment > deserializer ()
Deserializer function for fragment headers.
Static Public Attributes
static final byte HEADER_LENGTH = 8
Protected Attributes
byte nextHeader
short fragmentOffset
byte moreFragment
int identification
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements IPv6 fragment extension header format.
(RFC 2460)
Definition at line 33 of file Fragment.java.
Member Function Documentation
IPacket org.onlab.packet.ipv6.Fragment.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 147 of file Fragment.java.
References org.onlab.packet.ipv6.Fragment.deserializer(), find-link-in-cluster.length, and org.onlab.packet.IPv6.PROTOCOL_DESERIALIZER_MAP.
static Deserializer<Fragment> org.onlab.packet.ipv6.Fragment.deserializer () static
Deserializer function for fragment headers.
Returns
deserializer function
Definition at line 226 of file Fragment.java.
References org.onlab.packet.ipv6.Fragment.HEADER_LENGTH, find-link-in-cluster.length, org.onlab.packet.ipv6.Fragment.nextHeader, and org.onlab.packet.IPv6.PROTOCOL_DESERIALIZER_MAP.
Referenced by org.onlab.packet.ipv6.Fragment.deserialize().
boolean org.onlab.packet.ipv6.Fragment.equals (final Object obj)
Definition at line 195 of file Fragment.java.
References org.onlab.packet.ipv6.Fragment.fragmentOffset, org.onlab.packet.ipv6.Fragment.identification, org.onlab.packet.ipv6.Fragment.moreFragment, and org.onlab.packet.ipv6.Fragment.nextHeader.
Referenced by org.onlab.packet.ipv6.FragmentTest.testEqual().
short org.onlab.packet.ipv6.Fragment.getFragmentOffset ()
Gets the fragment offset of this header.
Returns
fragment offset
Definition at line 57 of file Fragment.java.
Referenced by org.onlab.packet.ipv6.FragmentTest.testDeserialize().
int org.onlab.packet.ipv6.Fragment.getIdentification ()
Gets the identification of this header.
Returns
identification
Definition at line 97 of file Fragment.java.
Referenced by org.onlab.packet.ipv6.FragmentTest.testDeserialize().
byte org.onlab.packet.ipv6.Fragment.getMoreFragment ()
Gets the more fragment flag of this header.
Returns
more fragment flag
Definition at line 77 of file Fragment.java.
Referenced by org.onlab.packet.ipv6.FragmentTest.testDeserialize().
byte org.onlab.packet.ipv6.Fragment.getNextHeader ()
Gets the type of next header.
Returns
next header
Implements org.onlab.packet.ipv6.IExtensionHeader.
Definition at line 42 of file Fragment.java.
Referenced by org.onlab.packet.ipv6.FragmentTest.testDeserialize().
int org.onlab.packet.ipv6.Fragment.hashCode ()
Definition at line 179 of file Fragment.java.
byte [] org.onlab.packet.ipv6.Fragment.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 113 of file Fragment.java.
References org.onlab.packet.ipv6.Fragment.fragmentOffset, org.onlab.packet.ipv6.Fragment.HEADER_LENGTH, find-link-in-cluster.length, org.onlab.packet.BasePacket.parent, org.onlab.packet.BasePacket.payload, and org.onlab.packet.IPv6.PROTOCOL_FRAG.
Referenced by org.onlab.packet.ipv6.FragmentTest.testSerialize().
Fragment org.onlab.packet.ipv6.Fragment.setFragmentOffset (final short fragmentOffset)
Sets the fragment offset of this header.
Parameters
fragmentOffset the fragment offset to set
Returns
this
Definition at line 67 of file Fragment.java.
References org.onlab.packet.ipv6.Fragment.fragmentOffset.
Fragment org.onlab.packet.ipv6.Fragment.setIdentification (final int identification)
Sets the identification of this header.
Parameters
identification the identification to set
Returns
this
Definition at line 107 of file Fragment.java.
References org.onlab.packet.ipv6.Fragment.identification.
Fragment org.onlab.packet.ipv6.Fragment.setMoreFragment (final byte moreFragment)
Sets the more fragment flag of this header.
Parameters
moreFragment the more fragment flag to set
Returns
this
Definition at line 87 of file Fragment.java.
References org.onlab.packet.ipv6.Fragment.moreFragment.
Fragment org.onlab.packet.ipv6.Fragment.setNextHeader (final byte nextHeader)
Sets the type of next header.
Parameters
nextHeader the next header to set
Returns
this
Implements org.onlab.packet.ipv6.IExtensionHeader.
Definition at line 47 of file Fragment.java.
References org.onlab.packet.ipv6.Fragment.nextHeader.
Member Data Documentation
short org.onlab.packet.ipv6.Fragment.fragmentOffset protected
Definition at line 37 of file Fragment.java.
Referenced by org.onlab.packet.ipv6.Fragment.equals(), org.onlab.packet.ipv6.Fragment.serialize(), and org.onlab.packet.ipv6.Fragment.setFragmentOffset().
final byte org.onlab.packet.ipv6.Fragment.HEADER_LENGTH = 8 static
Definition at line 34 of file Fragment.java.
Referenced by org.onlab.packet.ipv6.Fragment.deserializer(), and org.onlab.packet.ipv6.Fragment.serialize().
int org.onlab.packet.ipv6.Fragment.identification protected
Definition at line 39 of file Fragment.java.
Referenced by org.onlab.packet.ipv6.Fragment.equals(), and org.onlab.packet.ipv6.Fragment.setIdentification().
byte org.onlab.packet.ipv6.Fragment.moreFragment protected
Definition at line 38 of file Fragment.java.
Referenced by org.onlab.packet.ipv6.Fragment.equals(), and org.onlab.packet.ipv6.Fragment.setMoreFragment().
byte org.onlab.packet.ipv6.Fragment.nextHeader protected
Definition at line 36 of file Fragment.java.
Referenced by org.onlab.packet.ipv6.Fragment.deserializer(), org.onlab.packet.ipv6.Fragment.equals(), and org.onlab.packet.ipv6.Fragment.setNextHeader().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ipv6/Fragment.java