onos: org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg Class Reference
org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg Class Reference
Implements BGP link Shared Risk Link Group attribute.
Public Member Functions
BgpLinkAttrSrlg (List< Integer > sRlg)
Constructor to initialize the date.
List< Integer > attrSrlg ()
Returns the Shared Risk link group data.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpLinkAttrSrlg of (ArrayList< Integer > sRlg)
Returns object of this class with specified values.
static BgpLinkAttrSrlg read (ChannelBuffer cb) throws BgpParseException
Reads the BGP link attributes Shared Risk link group data.
Static Public Attributes
static final short ATTRNODE_SRLG = 1097
Detailed Description
Implements BGP link Shared Risk Link Group attribute.
Definition at line 33 of file BgpLinkAttrSrlg.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.BgpLinkAttrSrlg (List< Integer > sRlg)
Constructor to initialize the date.
Parameters
sRlg Shared Risk link group data
Definition at line 45 of file BgpLinkAttrSrlg.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.equals(), and org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.of().
Member Function Documentation
List<Integer> org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.attrSrlg ()
Returns the Shared Risk link group data.
Returns
array of Shared Risk link group data
Definition at line 93 of file BgpLinkAttrSrlg.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 132 of file BgpLinkAttrSrlg.java.
boolean org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.equals (Object obj)
Definition at line 108 of file BgpLinkAttrSrlg.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.BgpLinkAttrSrlg().
short org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 98 of file BgpLinkAttrSrlg.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.ATTRNODE_SRLG.
int org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.hashCode ()
Definition at line 103 of file BgpLinkAttrSrlg.java.
static BgpLinkAttrSrlg org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.of (ArrayList< Integer > sRlg) static
Returns object of this class with specified values.
Parameters
sRlg Shared Risk link group data
Returns
object of BgpLinkAttrSrlg
Definition at line 55 of file BgpLinkAttrSrlg.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.BgpLinkAttrSrlg().
static BgpLinkAttrSrlg org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.read (ChannelBuffer cb) throws BgpParseException static
Reads the BGP link attributes Shared Risk link group data.
Parameters
cb Channel buffer
Returns
object of type BgpLinkAttrSrlg
Exceptions
BgpParseException while parsing BgpLinkAttrSrlg
Definition at line 66 of file BgpLinkAttrSrlg.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.toString ()
Definition at line 127 of file BgpLinkAttrSrlg.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 121 of file BgpLinkAttrSrlg.java.
Member Data Documentation
final short org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.ATTRNODE_SRLG = 1097 static
Definition at line 35 of file BgpLinkAttrSrlg.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrSrlg.getType().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpLinkAttrSrlg.java