onos: org.onosproject.store.consistent.impl.MutexExecutionManager Class Reference
org.onosproject.store.consistent.impl.MutexExecutionManager Class Reference
Implementation of a MutexExecutionService.
Public Member Functions
void activate ()
void deactivate ()
CompletableFuture< Void > execute (MutexTask task, String exclusionPath, Executor executor)
Runs the specified task in a mutually exclusive fashion.
Protected Member Functions
CompletableFuture< MutexState > lock (String exclusionPath)
void tryLock (String exclusionPath)
Attempts to acquire lock for a path.
void unlock (String exclusionPath)
Releases lock for the specific path.
Protected Attributes
ConsistentMap< String, MutexState > lockMap
NodeId localNodeId
ClusterService clusterService
StorageService storageService
Detailed Description
Implementation of a MutexExecutionService.
Definition at line 59 of file MutexExecutionManager.java.
Member Function Documentation
void org.onosproject.store.consistent.impl.MutexExecutionManager.activate ()
Definition at line 79 of file MutexExecutionManager.java.
References org.onosproject.store.serializers.KryoNamespaces.API, org.onosproject.store.consistent.impl.MutexExecutionManager.localNodeId, org.onosproject.store.consistent.impl.MutexExecutionManager.lockMap, and org.onosproject.store.service.Serializer.using().
void org.onosproject.store.consistent.impl.MutexExecutionManager.deactivate ()
Definition at line 93 of file MutexExecutionManager.java.
References org.onosproject.store.consistent.impl.MutexExecutionManager.unlock().
CompletableFuture<Void> org.onosproject.store.consistent.impl.MutexExecutionManager.execute (MutexTask task, String exclusionPath, Executor executor)
Runs the specified task in a mutually exclusive fashion.
Parameters
task task to run
exclusionPath path on which different instances synchronize
executor executor to use for running the task
Returns
future that is completed when the task execution completes.
Implements org.onosproject.store.service.MutexExecutionService.
Definition at line 105 of file MutexExecutionManager.java.
References org.onosproject.store.consistent.impl.MutexExecutionManager.lock(), and org.onosproject.store.consistent.impl.MutexExecutionManager.unlock().
CompletableFuture<MutexState> org.onosproject.store.consistent.impl.MutexExecutionManager.lock (String exclusionPath) protected
Definition at line 115 of file MutexExecutionManager.java.
References org.onosproject.store.consistent.impl.MutexExecutionManager.tryLock().
Referenced by org.onosproject.store.consistent.impl.MutexExecutionManager.execute().
void org.onosproject.store.consistent.impl.MutexExecutionManager.tryLock (String exclusionPath) protected
Attempts to acquire lock for a path.
If lock is held by some other node, adds this node to the wait list.
Parameters
exclusionPath exclusion path
Definition at line 127 of file MutexExecutionManager.java.
References org.onosproject.store.consistent.impl.MutexExecutionManager.localNodeId, and org.onosproject.store.consistent.impl.MutexExecutionManager.lockMap.
Referenced by org.onosproject.store.consistent.impl.MutexExecutionManager.lock().
void org.onosproject.store.consistent.impl.MutexExecutionManager.unlock (String exclusionPath) protected
Releases lock for the specific path.
This operation is idempotent.
Parameters
exclusionPath exclusion path
Definition at line 140 of file MutexExecutionManager.java.
References org.onosproject.store.consistent.impl.MutexExecutionManager.localNodeId, and org.onosproject.store.consistent.impl.MutexExecutionManager.lockMap.
Referenced by org.onosproject.store.consistent.impl.MutexExecutionManager.deactivate(), and org.onosproject.store.consistent.impl.MutexExecutionManager.execute().
Member Data Documentation
ClusterService org.onosproject.store.consistent.impl.MutexExecutionManager.clusterService protected
Definition at line 67 of file MutexExecutionManager.java.
NodeId org.onosproject.store.consistent.impl.MutexExecutionManager.localNodeId protected
Definition at line 64 of file MutexExecutionManager.java.
Referenced by org.onosproject.store.consistent.impl.MutexExecutionManager.activate(), org.onosproject.store.consistent.impl.MutexExecutionManager.tryLock(), and org.onosproject.store.consistent.impl.MutexExecutionManager.unlock().
ConsistentMap<String, MutexState> org.onosproject.store.consistent.impl.MutexExecutionManager.lockMap protected
Definition at line 63 of file MutexExecutionManager.java.
Referenced by org.onosproject.store.consistent.impl.MutexExecutionManager.activate(), org.onosproject.store.consistent.impl.MutexExecutionManager.tryLock(), and org.onosproject.store.consistent.impl.MutexExecutionManager.unlock().
StorageService org.onosproject.store.consistent.impl.MutexExecutionManager.storageService protected
Definition at line 70 of file MutexExecutionManager.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/MutexExecutionManager.java