onos: org.onosproject.net.flow.instructions.Instructions Class Reference
org.onosproject.net.flow.instructions.Instructions Class Reference
Factory class for creating various traffic treatment instructions.
Classes
class DropInstruction
Drop instruction.
class ExtensionInstructionWrapper
Extension instruction.
class GroupInstruction
Group Instruction.
class MetadataInstruction
Metadata instruction.
class MeterInstruction
A meter instruction.
class NoActionInstruction
No Action instruction.
class OutputInstruction
Output Instruction.
class SetQueueInstruction
Set-Queue Instruction.
class TableTypeTransition
Transition instruction.
Static Public Member Functions
static OutputInstruction createOutput (final PortNumber number)
Creates an output instruction using the specified port number.
static DropInstruction createDrop ()
Creates a drop instruction.
static NoActionInstruction createNoAction ()
Creates a no action instruction.
static GroupInstruction createGroup (final GroupId groupId)
Creates a group instruction.
static SetQueueInstruction setQueue (final long queueId, final PortNumber port)
Creates a set-queue instruction.
static MeterInstruction meterTraffic (final MeterId meterId)
static L0ModificationInstruction modL0Lambda (Lambda lambda)
Creates an L0 modification with the specified OCh signal.
static L1ModificationInstruction modL1OduSignalId (OduSignalId oduSignalId)
Creates an L1 modification with the specified ODU signal Id.
static L2ModificationInstruction modL2Src (MacAddress addr)
Creates a l2 src modification.
static L2ModificationInstruction modL2Dst (MacAddress addr)
Creates a L2 dst modification.
static L2ModificationInstruction modVlanId (VlanId vlanId)
Creates a VLAN ID modification.
static L2ModificationInstruction modVlanPcp (Byte vlanPcp)
Creates a VLAN PCP modification.
static L2ModificationInstruction modMplsLabel (MplsLabel mplsLabel)
Creates a MPLS label modification.
static L2ModificationInstruction modMplsBos (boolean mplsBos)
Creates a MPLS BOS bit modification.
static L2ModificationInstruction decMplsTtl ()
Creates a MPLS decrement TTL modification.
static L3ModificationInstruction modL3Src (IpAddress addr)
Creates a L3 IPv4 src modification.
static L3ModificationInstruction modL3Dst (IpAddress addr)
Creates a L3 IPv4 dst modification.
static L3ModificationInstruction modL3IPv6Src (IpAddress addr)
Creates a L3 IPv6 src modification.
static L3ModificationInstruction modL3IPv6Dst (IpAddress addr)
Creates a L3 IPv6 dst modification.
static L3ModificationInstruction modL3IPv6FlowLabel (int flowLabel)
Creates a L3 IPv6 Flow Label modification.
static L3ModificationInstruction decNwTtl ()
Creates a L3 decrement TTL modification.
static L3ModificationInstruction copyTtlOut ()
Creates a L3 copy TTL to outer header modification.
static L3ModificationInstruction copyTtlIn ()
Creates a L3 copy TTL to inner header modification.
static Instruction pushMpls ()
Creates a push MPLS header instruction.
static Instruction popMpls ()
Creates a pop MPLS header instruction.
static Instruction popMpls (EthType etherType)
Creates a pop MPLS header instruction with a particular ethertype.
static Instruction popVlan ()
Creates a pop VLAN header instruction.
static Instruction pushVlan ()
Creates a push VLAN header instruction.
static Instruction transition (Integer tableId)
Sends the packet to the table id.
static Instruction writeMetadata (long metadata, long metadataMask)
Writes metadata to associate with a packet.
static L2ModificationInstruction modTunnelId (long tunnelId)
Creates a Tunnel ID modification.
static L4ModificationInstruction modTcpSrc (short port)
Creates a TCP src modification.
static L4ModificationInstruction modTcpSrc (TpPort port)
Creates a TCP src modification.
static L4ModificationInstruction modTcpDst (short port)
Creates a TCP dst modification.
static L4ModificationInstruction modTcpDst (TpPort port)
Creates a TCP dst modification.
static L4ModificationInstruction modUdpSrc (short port)
Creates a UDP src modification.
static L4ModificationInstruction modUdpSrc (TpPort port)
Creates a UDP src modification.
static L4ModificationInstruction modUdpDst (short port)
Creates a UDP dst modification.
static L4ModificationInstruction modUdpDst (TpPort port)
Creates a UDP dst modification.
static ExtensionInstructionWrapper extension (ExtensionTreatment extension, DeviceId deviceId)
Creates an extension instruction.
Detailed Description
Factory class for creating various traffic treatment instructions.
Definition at line 52 of file Instructions.java.
Member Function Documentation
static L3ModificationInstruction org.onosproject.net.flow.instructions.Instructions.copyTtlIn () static
Creates a L3 copy TTL to inner header modification.
Returns
a L3 modification
Definition at line 297 of file Instructions.java.
References org.onosproject.net.flow.instructions.L3ModificationInstruction.L3SubType.TTL_IN.
static L3ModificationInstruction org.onosproject.net.flow.instructions.Instructions.copyTtlOut () static
Creates a L3 copy TTL to outer header modification.
Returns
a L3 modification
Definition at line 288 of file Instructions.java.
References org.onosproject.net.flow.instructions.L3ModificationInstruction.L3SubType.TTL_OUT.
static DropInstruction org.onosproject.net.flow.instructions.Instructions.createDrop () static
Creates a drop instruction.
Returns
drop instruction
Definition at line 75 of file Instructions.java.
static GroupInstruction org.onosproject.net.flow.instructions.Instructions.createGroup (final GroupId groupId) static
Creates a group instruction.
Parameters
groupId Group Id
Returns
group instruction
Definition at line 94 of file Instructions.java.
static NoActionInstruction org.onosproject.net.flow.instructions.Instructions.createNoAction () static
Creates a no action instruction.
Returns
no action instruction
Definition at line 84 of file Instructions.java.
static OutputInstruction org.onosproject.net.flow.instructions.Instructions.createOutput (final PortNumber number) static
Creates an output instruction using the specified port number.
This can include logical ports such as CONTROLLER, FLOOD, etc.
Parameters
number port number
Returns
output instruction
Definition at line 64 of file Instructions.java.
Referenced by org.onosproject.flowanalyzer.FlowAnalyzerTest.genFlow().
static L2ModificationInstruction org.onosproject.net.flow.instructions.Instructions.decMplsTtl () static
Creates a MPLS decrement TTL modification.
Returns
a L2 Modification
Definition at line 216 of file Instructions.java.
static L3ModificationInstruction org.onosproject.net.flow.instructions.Instructions.decNwTtl () static
Creates a L3 decrement TTL modification.
Returns
a L3 modification
Definition at line 279 of file Instructions.java.
References org.onosproject.net.flow.instructions.L3ModificationInstruction.L3SubType.DEC_TTL.
static ExtensionInstructionWrapper org.onosproject.net.flow.instructions.Instructions.extension (ExtensionTreatment extension, DeviceId deviceId) static
Creates an extension instruction.
Parameters
extension extension instruction
deviceId device ID
Returns
extension instruction
Definition at line 492 of file Instructions.java.
static MeterInstruction org.onosproject.net.flow.instructions.Instructions.meterTraffic (final MeterId meterId) static
Definition at line 111 of file Instructions.java.
static L0ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modL0Lambda (Lambda lambda) static
Creates an L0 modification with the specified OCh signal.
Parameters
lambda OCh signal
Returns
an L0 modification
Definition at line 122 of file Instructions.java.
References org.onosproject.net.flow.instructions.L0ModificationInstruction.L0SubType.LAMBDA.
Referenced by org.onosproject.codec.impl.IntentCodecTest.intentWithTreatmentSelectorAndConstraints(), org.onosproject.codec.impl.InstructionCodecTest.modLambdaInstructionTest(), org.onosproject.codec.impl.InstructionCodecTest.modOchSignalInstructionTest(), org.onosproject.net.flow.DefaultTrafficTreatmentTest.testEquals(), and org.onosproject.net.flow.DefaultTrafficTreatmentTest.testTreatmentBuilderConstructors().
static L1ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modL1OduSignalId (OduSignalId oduSignalId) static
Creates an L1 modification with the specified ODU signal Id.
Parameters
oduSignalId ODU Signal Id
Returns
a L1 modification
Definition at line 140 of file Instructions.java.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.modOduSignalIdInstructionTest().
static L2ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modL2Dst (MacAddress addr) static
Creates a L2 dst modification.
Parameters
addr the mac address to modify to
Returns
a L2 modification
Definition at line 162 of file Instructions.java.
static L2ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modL2Src (MacAddress addr) static
Creates a l2 src modification.
Parameters
addr the mac address to modify to
Returns
a l2 modification
Definition at line 150 of file Instructions.java.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.modEtherInstructionTest().
static L3ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modL3Dst (IpAddress addr) static
Creates a L3 IPv4 dst modification.
Parameters
addr the IPv4 address to modify to
Returns
a L3 modification
Definition at line 237 of file Instructions.java.
References org.onosproject.net.flow.instructions.L3ModificationInstruction.L3SubType.IPV4_DST.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.modIPDstInstructionTest().
static L3ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modL3IPv6Dst (IpAddress addr) static
Creates a L3 IPv6 dst modification.
Parameters
addr the IPv6 address to modify to
Returns
a L3 modification
Definition at line 259 of file Instructions.java.
References org.onosproject.net.flow.instructions.L3ModificationInstruction.L3SubType.IPV6_DST.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.modIPv6DstInstructionTest().
static L3ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modL3IPv6FlowLabel (int flowLabel) static
Creates a L3 IPv6 Flow Label modification.
Parameters
flowLabel the IPv6 flow label to modify to (20 bits)
Returns
a L3 modification
Definition at line 270 of file Instructions.java.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.modIPv6FlowLabelInstructionTest().
static L3ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modL3IPv6Src (IpAddress addr) static
Creates a L3 IPv6 src modification.
Parameters
addr the IPv6 address to modify to
Returns
a L3 modification
Definition at line 248 of file Instructions.java.
References org.onosproject.net.flow.instructions.L3ModificationInstruction.L3SubType.IPV6_SRC.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.modIPv6SrcInstructionTest().
static L3ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modL3Src (IpAddress addr) static
Creates a L3 IPv4 src modification.
Parameters
addr the IPv4 address to modify to
Returns
a L3 modification
Definition at line 226 of file Instructions.java.
References org.onosproject.net.flow.instructions.L3ModificationInstruction.L3SubType.IPV4_SRC.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.modIPSrcInstructionTest().
static L2ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modMplsBos (boolean mplsBos) static
Creates a MPLS BOS bit modification.
Parameters
mplsBos MPLS BOS bit to set (true) or unset (false)
Returns
a L2 Modification
Definition at line 207 of file Instructions.java.
static L2ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modMplsLabel (MplsLabel mplsLabel) static
Creates a MPLS label modification.
Parameters
mplsLabel MPLS label to set
Returns
a L2 Modification
Definition at line 196 of file Instructions.java.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.modMplsLabelInstructionTest().
static L4ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modTcpDst (short port) static
Creates a TCP dst modification.
Parameters
port the TCP port number to modify to
Returns
a L4 modification
Deprecated:
in Drake release
Definition at line 421 of file Instructions.java.
References org.onosproject.net.flow.instructions.L4ModificationInstruction.L4SubType.TCP_DST, and org.onlab.packet.TpPort.tpPort().
static L4ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modTcpDst (TpPort port) static
Creates a TCP dst modification.
Parameters
port the TCP port number to modify to
Returns
a L4 modification
Definition at line 432 of file Instructions.java.
References org.onosproject.net.flow.instructions.L4ModificationInstruction.L4SubType.TCP_DST.
static L4ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modTcpSrc (short port) static
Creates a TCP src modification.
Parameters
port the TCP port number to modify to
Returns
a L4 modification
Deprecated:
in Drake release
Definition at line 397 of file Instructions.java.
References org.onosproject.net.flow.instructions.L4ModificationInstruction.L4SubType.TCP_SRC, and org.onlab.packet.TpPort.tpPort().
static L4ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modTcpSrc (TpPort port) static
Creates a TCP src modification.
Parameters
port the TCP port number to modify to
Returns
a L4 modification
Definition at line 408 of file Instructions.java.
References org.onosproject.net.flow.instructions.L4ModificationInstruction.L4SubType.TCP_SRC.
static L2ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modTunnelId (long tunnelId) static
Creates a Tunnel ID modification.
Parameters
tunnelId the Tunnel ID to modify to
Returns
a L2 modification
Definition at line 384 of file Instructions.java.
static L4ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modUdpDst (short port) static
Creates a UDP dst modification.
Parameters
port the UDP port number to modify to
Returns
a L4 modification
Deprecated:
in Drake release
Definition at line 469 of file Instructions.java.
References org.onlab.packet.TpPort.tpPort(), and org.onosproject.net.flow.instructions.L4ModificationInstruction.L4SubType.UDP_DST.
static L4ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modUdpDst (TpPort port) static
Creates a UDP dst modification.
Parameters
port the UDP port number to modify to
Returns
a L4 modification
Definition at line 480 of file Instructions.java.
References org.onosproject.net.flow.instructions.L4ModificationInstruction.L4SubType.UDP_DST.
static L4ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modUdpSrc (short port) static
Creates a UDP src modification.
Parameters
port the UDP port number to modify to
Returns
a L4 modification
Deprecated:
in Drake release
Definition at line 445 of file Instructions.java.
References org.onlab.packet.TpPort.tpPort(), and org.onosproject.net.flow.instructions.L4ModificationInstruction.L4SubType.UDP_SRC.
static L4ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modUdpSrc (TpPort port) static
Creates a UDP src modification.
Parameters
port the UDP port number to modify to
Returns
a L4 modification
Definition at line 456 of file Instructions.java.
References org.onosproject.net.flow.instructions.L4ModificationInstruction.L4SubType.UDP_SRC.
static L2ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modVlanId (VlanId vlanId) static
Creates a VLAN ID modification.
Parameters
vlanId the VLAN ID to modify to
Returns
a L2 modification
Definition at line 174 of file Instructions.java.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.modVlanIdInstructionTest().
static L2ModificationInstruction org.onosproject.net.flow.instructions.Instructions.modVlanPcp (Byte vlanPcp) static
Creates a VLAN PCP modification.
Parameters
vlanPcp the PCP to modify to
Returns
a L2 modification
Definition at line 185 of file Instructions.java.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.modVlanPcpInstructionTest().
static Instruction org.onosproject.net.flow.instructions.Instructions.popMpls () static
Creates a pop MPLS header instruction.
Returns
a L2 modification.
Definition at line 317 of file Instructions.java.
static Instruction org.onosproject.net.flow.instructions.Instructions.popMpls (EthType etherType) static
Creates a pop MPLS header instruction with a particular ethertype.
Parameters
etherType Ethernet type to set
Returns
a L2 modification.
Definition at line 329 of file Instructions.java.
static Instruction org.onosproject.net.flow.instructions.Instructions.popVlan () static
Creates a pop VLAN header instruction.
Returns
a L2 modification
Definition at line 340 of file Instructions.java.
static Instruction org.onosproject.net.flow.instructions.Instructions.pushMpls () static
Creates a push MPLS header instruction.
Returns
a L2 modification.
Definition at line 306 of file Instructions.java.
Referenced by org.onosproject.codec.impl.InstructionCodecTest.pushHeaderInstructionsTest().
static Instruction org.onosproject.net.flow.instructions.Instructions.pushVlan () static
Creates a push VLAN header instruction.
Returns
a L2 modification
Definition at line 350 of file Instructions.java.
static SetQueueInstruction org.onosproject.net.flow.instructions.Instructions.setQueue (final long queueId, final PortNumber port) static
Creates a set-queue instruction.
Parameters
queueId Queue Id
port Port number
Returns
set-queue instruction
Definition at line 106 of file Instructions.java.
static Instruction org.onosproject.net.flow.instructions.Instructions.transition (Integer tableId) static
Sends the packet to the table id.
Parameters
tableId flow rule table id
Returns
table type transition instruction
Definition at line 362 of file Instructions.java.
static Instruction org.onosproject.net.flow.instructions.Instructions.writeMetadata (long metadata, long metadataMask) static
Writes metadata to associate with a packet.
Parameters
metadata the metadata value to write
metadataMask the bits to mask for the metadata value
Returns
metadata instruction
Definition at line 374 of file Instructions.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/instructions/Instructions.java