onos: org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1 Class Reference
Provides PCEP Ero Object.
Classes
class Builder
Builder class for PCEP ERO object.
Public Member Functions
PcepEroObjectVer1 ()
reset variables.
PcepEroObjectVer1 (PcepObjectHeader eroObjHeader, LinkedList< PcepValueType > llSubObjects)
Constructor to initialize parameters of ERO object.
PcepObjectHeader getEroObjHeader ()
Returns ERO object header.
void setEroObjHeader (PcepObjectHeader obj)
Sets Object Header.
LinkedList< PcepValueType > getSubObjects ()
Return LinkedList of SubObjects of ERO Object.
void setSubObjects (LinkedList< PcepValueType > llSubObjects)
Sets LinkedList of SubObjects in ERO Object.
int write (ChannelBuffer cb) throws PcepParseException
Writes the ERO Object into channel buffer.
String toString ()
Static Public Member Functions
static PcepEroObject read (ChannelBuffer cb) throws PcepParseException
Reads from channel buffer and returns object of PcepEroObject.
Static Public Attributes
static final byte ERO_OBJ_TYPE = 1
static final byte ERO_OBJ_CLASS = 7
static final byte ERO_OBJECT_VERSION = 1
static final short ERO_OBJ_MINIMUM_LENGTH = 12
static final byte IPV4_TYPE = 1
static final byte PATH_KEY_32_BIT_SUB_OBJ_TYPE = 64
static final int LABEL_SUB_OBJ_TYPE = 3
static final int SR_ERO_SUB_OBJ_TYPE = 96
static final int OBJECT_HEADER_LENGTH = 4
static final int YTYPE_SHIFT_VALUE = 0x7F
Static Protected Member Functions
static LinkedList< PcepValueType > parseSubObjects (ChannelBuffer cb) throws PcepParseException
Parse list of Sub Objects.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepEroObjectVer1.class)
Detailed Description
Provides PCEP Ero Object.
Definition at line 41 of file PcepEroObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.PcepEroObjectVer1 ()
reset variables.
Definition at line 161 of file PcepEroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.read().
org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.PcepEroObjectVer1 (PcepObjectHeader eroObjHeader, LinkedList< PcepValueType > llSubObjects)
Constructor to initialize parameters of ERO object.
Parameters
eroObjHeader ERO object header
llSubObjects list of sub objects.
Definition at line 172 of file PcepEroObjectVer1.java.
Member Function Documentation
PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.getEroObjHeader ()
Returns ERO object header.
Returns
eroObjHeader ERO object header
Definition at line 183 of file PcepEroObjectVer1.java.
LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.getSubObjects ()
Return LinkedList of SubObjects of ERO Object.
Returns
list of subobjects
Implements org.onosproject.pcepio.protocol.PcepEroObject.
Definition at line 197 of file PcepEroObjectVer1.java.
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.parseSubObjects (ChannelBuffer cb) throws PcepParseException static protected
Parse list of Sub Objects.
Parameters
cb channel buffer
Returns
list of Sub Objects
Exceptions
PcepParseException when fails to parse sub object list
Definition at line 240 of file PcepEroObjectVer1.java.
References org.onosproject.pcepio.types.IPv6SubObject.VALUE_LENGTH, and org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.YTYPE_SHIFT_VALUE.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.read().
static PcepEroObject org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.read (ChannelBuffer cb) throws PcepParseException static
Reads from channel buffer and returns object of PcepEroObject.
Parameters
cb channel buffer.
Returns
object of PcepEroObject
Exceptions
PcepParseException when ERO object is not present in channel buffer
Definition at line 213 of file PcepEroObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.ERO_OBJ_CLASS, org.onosproject.pcepio.types.PcepErrorDetailInfo.ERROR_TYPE_6, org.onosproject.pcepio.types.PcepErrorDetailInfo.ERROR_VALUE_9, org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.OBJECT_HEADER_LENGTH, org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.parseSubObjects(), and org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.PcepEroObjectVer1().
void org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.setEroObjHeader (PcepObjectHeader obj)
Sets Object Header.
Parameters
obj ERO object header
Definition at line 192 of file PcepEroObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.setSubObjects (LinkedList< PcepValueType > llSubObjects)
Sets LinkedList of SubObjects in ERO Object.
Parameters
llSubObjects list of subobjects
Implements org.onosproject.pcepio.protocol.PcepEroObject.
Definition at line 202 of file PcepEroObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.toString ()
Definition at line 402 of file PcepEroObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the ERO Object into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException while writing ERO Object into ChannelBuffer
Implements org.onosproject.pcepio.protocol.PcepEroObject.
Definition at line 293 of file PcepEroObjectVer1.java.
References find-link-in-cluster.length.
Member Data Documentation
final byte org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.ERO_OBJ_CLASS = 7 static
Definition at line 142 of file PcepEroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.read().
final short org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.ERO_OBJ_MINIMUM_LENGTH = 12 static
Definition at line 144 of file PcepEroObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.ERO_OBJ_TYPE = 1 static
Definition at line 141 of file PcepEroObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.ERO_OBJECT_VERSION = 1 static
Definition at line 143 of file PcepEroObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.IPV4_TYPE = 1 static
Definition at line 145 of file PcepEroObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.LABEL_SUB_OBJ_TYPE = 3 static
Definition at line 147 of file PcepEroObjectVer1.java.
final Logger org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.log = LoggerFactory.getLogger(PcepEroObjectVer1.class) static protected
Definition at line 139 of file PcepEroObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.OBJECT_HEADER_LENGTH = 4 static
Definition at line 149 of file PcepEroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.read().
final byte org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.PATH_KEY_32_BIT_SUB_OBJ_TYPE = 64 static
Definition at line 146 of file PcepEroObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.SR_ERO_SUB_OBJ_TYPE = 96 static
Definition at line 148 of file PcepEroObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.YTYPE_SHIFT_VALUE = 0x7F static
Definition at line 150 of file PcepEroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.parseSubObjects().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepEroObjectVer1.java