onos: org.onosproject.incubator.net.meter.impl.MeterManager Class Reference
org.onosproject.incubator.net.meter.impl.MeterManager Class Reference
Provides implementation of the meter service APIs.
Public Member Functions
void activate ()
void deactivate ()
Meter submit (MeterRequest request)
Adds a meter to the system and performs it installation.
void withdraw (MeterRequest request, MeterId meterId)
Remove a meter from the system and the dataplane.
Meter getMeter (DeviceId deviceId, MeterId id)
Fetch the meter by the meter id.
Collection< Meter > getAllMeters ()
Fetches all the meters.
Protected Member Functions
MeterProviderService createProviderService (MeterProvider provider)
Protected Attributes
StorageService storageService
MeterStore store
Detailed Description
Provides implementation of the meter service APIs.
Definition at line 62 of file MeterManager.java.
Member Function Documentation
void org.onosproject.incubator.net.meter.impl.MeterManager.activate ()
Definition at line 82 of file MeterManager.java.
References org.onosproject.net.meter.MeterFailReason.UNKNOWN.
MeterProviderService org.onosproject.incubator.net.meter.impl.MeterManager.createProviderService (MeterProvider provider) protected
Definition at line 111 of file MeterManager.java.
void org.onosproject.incubator.net.meter.impl.MeterManager.deactivate ()
Definition at line 105 of file MeterManager.java.
Collection<Meter> org.onosproject.incubator.net.meter.impl.MeterManager.getAllMeters ()
Fetches all the meters.
Returns
a collection of meters
Implements org.onosproject.net.meter.MeterService.
Definition at line 163 of file MeterManager.java.
Referenced by org.onosproject.incubator.net.meter.impl.MeterManagerTest.testAddition(), org.onosproject.incubator.net.meter.impl.MeterManagerTest.testMultipleDevice(), and org.onosproject.incubator.net.meter.impl.MeterManagerTest.testRemove().
Meter org.onosproject.incubator.net.meter.impl.MeterManager.getMeter (DeviceId deviceId, MeterId id)
Fetch the meter by the meter id.
Parameters
deviceId a device id
id a meter id
Returns
a meter
Implements org.onosproject.net.meter.MeterService.
Definition at line 157 of file MeterManager.java.
References find-flow.deviceId, and find-device.id.
Referenced by org.onosproject.incubator.net.meter.impl.MeterManagerTest.testAddition(), org.onosproject.incubator.net.meter.impl.MeterManagerTest.testMultipleDevice(), and org.onosproject.incubator.net.meter.impl.MeterManagerTest.testRemove().
Meter org.onosproject.incubator.net.meter.impl.MeterManager.submit (MeterRequest meter)
Adds a meter to the system and performs it installation.
Parameters
meter a meter
Returns
a meter (with a meter id)
Implements org.onosproject.net.meter.MeterService.
Definition at line 116 of file MeterManager.java.
References org.onosproject.net.meter.MeterRequest.appId(), org.onosproject.net.meter.MeterRequest.bands(), org.onosproject.net.meter.MeterRequest.deviceId(), org.onosproject.net.meter.MeterRequest.isBurst(), and org.onosproject.net.meter.MeterState.PENDING_ADD.
void org.onosproject.incubator.net.meter.impl.MeterManager.withdraw (MeterRequest meter, MeterId meterId)
Remove a meter from the system and the dataplane.
Parameters
meter a meter to remove
meterId the meter id of the meter to remove.
Implements org.onosproject.net.meter.MeterService.
Definition at line 138 of file MeterManager.java.
References org.onosproject.net.meter.MeterRequest.appId(), org.onosproject.net.meter.MeterRequest.bands(), org.onosproject.net.meter.MeterRequest.deviceId(), org.onosproject.net.meter.MeterRequest.isBurst(), and org.onosproject.net.meter.MeterState.PENDING_REMOVE.
Member Data Documentation
StorageService org.onosproject.incubator.net.meter.impl.MeterManager.storageService protected
Definition at line 71 of file MeterManager.java.
MeterStore org.onosproject.incubator.net.meter.impl.MeterManager.store protected
Definition at line 74 of file MeterManager.java.
The documentation for this class was generated from the following file:
incubator/net/src/main/java/org/onosproject/incubator/net/meter/impl/MeterManager.java