onos: org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService Class Reference
org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService Class Reference
Representation of conversion between Ovsdb table and Row.
Public Member Functions
AbstractOvsdbTableService (DatabaseSchema dbSchema, Row row, OvsdbTable table, VersionNum formVersion)
Constructs a AbstractOvsdbTableService object.
Column getColumnHandler (ColumnDescription columnDesc)
Get Column from row.
Object getDataHandler (ColumnDescription columnDesc)
Get Data from row.
void setDataHandler (ColumnDescription columnDesc, Object obj)
Set column data of row.
UUID getTableUuid ()
Returns UUID which column name is _uuid.
Column getTableUuidColumn ()
Returns UUID Column which column name is _uuid.
UUID getTableVersion ()
Returns UUID which column name is _version.
Column getTableVersionColumn ()
Returns UUID Column which column name is _version.
DatabaseSchema dbSchema ()
Get DatabaseSchema entity.
Row getRow ()
Get Row entity.
TableDescription tableDesc ()
Get TableDescription entity.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Representation of conversion between Ovsdb table and Row.
Definition at line 39 of file AbstractOvsdbTableService.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.AbstractOvsdbTableService (DatabaseSchema dbSchema, Row row, OvsdbTable table, VersionNum formVersion)
Constructs a AbstractOvsdbTableService object.
Parameters
dbSchema DatabaseSchema entity
row Row entity
table table name
formVersion the initial version
Definition at line 52 of file AbstractOvsdbTableService.java.
References org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.dbSchema(), and org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.tableDesc().
Referenced by org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.equals().
Member Function Documentation
DatabaseSchema org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.dbSchema ()
Get DatabaseSchema entity.
Returns
DatabaseSchema entity
Definition at line 238 of file AbstractOvsdbTableService.java.
Referenced by org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.AbstractOvsdbTableService().
boolean org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.equals (Object obj)
Definition at line 267 of file AbstractOvsdbTableService.java.
References org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.AbstractOvsdbTableService().
Column org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getColumnHandler (ColumnDescription columndesc)
Get Column from row.
Parameters
columndesc Column description
Returns
Column
Implements org.onosproject.ovsdb.rfc.tableservice.OvsdbTableService.
Definition at line 159 of file AbstractOvsdbTableService.java.
Referenced by org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getTableUuidColumn(), and org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getTableVersionColumn().
Object org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getDataHandler (ColumnDescription columndesc)
Get Data from row.
Parameters
columndesc Column description
Returns
Object column data
Implements org.onosproject.ovsdb.rfc.tableservice.OvsdbTableService.
Definition at line 173 of file AbstractOvsdbTableService.java.
References org.onosproject.ovsdb.rfc.notation.Row.getColumn().
Referenced by org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getTableUuid(), and org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getTableVersion().
Row org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getRow ()
Get Row entity.
Returns
Row entity
Definition at line 246 of file AbstractOvsdbTableService.java.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createPort(), and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createTunnel().
UUID org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getTableUuid ()
Returns UUID which column name is _uuid.
Returns
UUID
Implements org.onosproject.ovsdb.rfc.tableservice.OvsdbTableService.
Definition at line 199 of file AbstractOvsdbTableService.java.
References org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getDataHandler().
Column org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getTableUuidColumn ()
Returns UUID Column which column name is _uuid.
Returns
UUID Column
Implements org.onosproject.ovsdb.rfc.tableservice.OvsdbTableService.
Definition at line 208 of file AbstractOvsdbTableService.java.
References org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getColumnHandler().
UUID org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getTableVersion ()
Returns UUID which column name is _version.
Returns
UUID
Implements org.onosproject.ovsdb.rfc.tableservice.OvsdbTableService.
Definition at line 217 of file AbstractOvsdbTableService.java.
References org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getDataHandler().
Column org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getTableVersionColumn ()
Returns UUID Column which column name is _version.
Returns
UUID Column
Implements org.onosproject.ovsdb.rfc.tableservice.OvsdbTableService.
Definition at line 226 of file AbstractOvsdbTableService.java.
References org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getColumnHandler().
int org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.hashCode ()
Definition at line 262 of file AbstractOvsdbTableService.java.
void org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.setDataHandler (ColumnDescription columndesc, Object obj)
Set column data of row.
Parameters
columndesc Column description
obj column data
Implements org.onosproject.ovsdb.rfc.tableservice.OvsdbTableService.
Definition at line 187 of file AbstractOvsdbTableService.java.
TableDescription org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.tableDesc ()
Get TableDescription entity.
Returns
TableDescription entity
Definition at line 257 of file AbstractOvsdbTableService.java.
Referenced by org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.AbstractOvsdbTableService().
String org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.toString ()
Definition at line 279 of file AbstractOvsdbTableService.java.
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/tableservice/AbstractOvsdbTableService.java