onos: org.onosproject.net.config.basics.BasicDeviceConfig Class Reference
org.onosproject.net.config.basics.BasicDeviceConfig Class Reference
Basic configuration for network infrastructure devices.
Public Member Functions
Device.Type type ()
Returns the device type.
BasicDeviceConfig type (Device.Type type)
Sets the device type.
String driver ()
Returns the device driver name.
BasicElementConfig driver (String driverName)
Sets the driver name.
String managementAddress ()
Returns the device management ip (ip:port).
BasicElementConfig managementAddress (String managementAddress)
Sets the driver name.
Static Public Attributes
static final String TYPE = "type"
static final String DRIVER = "driver"
static final String MANAGEMENT_ADDRESS = "managementAddress"
Detailed Description
Basic configuration for network infrastructure devices.
Definition at line 24 of file BasicDeviceConfig.java.
Member Function Documentation
String org.onosproject.net.config.basics.BasicDeviceConfig.driver ()
Returns the device driver name.
Returns
driver name of null if not set
Definition at line 54 of file BasicDeviceConfig.java.
References org.onosproject.net.config.basics.BasicDeviceConfig.DRIVER.
Referenced by org.onosproject.net.device.impl.BasicDeviceOperator.combine().
BasicElementConfig org.onosproject.net.config.basics.BasicDeviceConfig.driver (String driverName)
Sets the driver name.
Parameters
driverName new driver name; null to clear
Returns
self
Definition at line 64 of file BasicDeviceConfig.java.
References org.onosproject.net.config.basics.BasicDeviceConfig.DRIVER.
String org.onosproject.net.config.basics.BasicDeviceConfig.managementAddress ()
Returns the device management ip (ip:port).
Returns
device management address (ip:port) or null if not set
Definition at line 73 of file BasicDeviceConfig.java.
References org.onosproject.net.config.basics.BasicDeviceConfig.MANAGEMENT_ADDRESS.
Referenced by org.onosproject.net.device.impl.BasicDeviceOperator.combine().
BasicElementConfig org.onosproject.net.config.basics.BasicDeviceConfig.managementAddress (String managementAddress)
Sets the driver name.
Parameters
managementAddress new device management address (ip:port); null to clear
Returns
self
Definition at line 83 of file BasicDeviceConfig.java.
References org.onosproject.net.config.basics.BasicDeviceConfig.MANAGEMENT_ADDRESS.
Device.Type org.onosproject.net.config.basics.BasicDeviceConfig.type ()
Returns the device type.
Returns
device type override
Definition at line 35 of file BasicDeviceConfig.java.
References org.onosproject.net.config.basics.BasicDeviceConfig.TYPE.
Referenced by org.onosproject.net.device.impl.BasicDeviceOperator.combine(), and org.onosproject.net.config.basics.BasicDeviceConfig.type().
BasicDeviceConfig org.onosproject.net.config.basics.BasicDeviceConfig.type (Device.Type type)
Sets the device type.
Parameters
type device type override
Returns
self
Definition at line 45 of file BasicDeviceConfig.java.
References org.onosproject.net.config.basics.BasicDeviceConfig.TYPE, and org.onosproject.net.config.basics.BasicDeviceConfig.type().
Member Data Documentation
final String org.onosproject.net.config.basics.BasicDeviceConfig.DRIVER = "driver" static
Definition at line 27 of file BasicDeviceConfig.java.
Referenced by org.onosproject.net.config.basics.BasicDeviceConfig.driver().
final String org.onosproject.net.config.basics.BasicDeviceConfig.MANAGEMENT_ADDRESS = "managementAddress" static
Definition at line 28 of file BasicDeviceConfig.java.
Referenced by org.onosproject.net.config.basics.BasicDeviceConfig.managementAddress().
final String org.onosproject.net.config.basics.BasicDeviceConfig.TYPE = "type" static
Definition at line 26 of file BasicDeviceConfig.java.
Referenced by org.onosproject.net.config.basics.BasicDeviceConfig.type().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/config/basics/BasicDeviceConfig.java