onos: org.onosproject.driver.ovsdb.OvsdbBridgeConfig Class Reference
org.onosproject.driver.ovsdb.OvsdbBridgeConfig Class Reference
The implementation of BridageConfig.
Public Member Functions
void addBridge (BridgeName bridgeName)
Add a bridge.
void addBridge (BridgeName bridgeName, String dpid, String exPortName)
Adds a bridge with given bridge name, dpid and exPortName.
boolean addBridge (BridgeName bridgeName, String dpid, List< ControllerInfo > controllers)
Adds a bridge with given bridge name and dpid, and sets the controller of the bridge with given controllers.
void deleteBridge (BridgeName bridgeName)
Remove a bridge.
Collection< BridgeDescription > getBridges ()
Remove a bridge.
void addPort (PortDescription port)
Add a logical/virtual port.
void deletePort (PortDescription port)
Delete a logical/virtual port.
Collection< PortDescription > getPorts ()
Delete a logical/virtual port.
Set< PortNumber > getPortNumbers ()
Get a collection of port.
List< PortNumber > getLocalPorts (Iterable< String > ifaceIds)
Get logical/virtual ports by ifaceIds.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Detailed Description
The implementation of BridageConfig.
Definition at line 46 of file OvsdbBridgeConfig.java.
Member Function Documentation
void org.onosproject.driver.ovsdb.OvsdbBridgeConfig.addBridge (BridgeName bridgeName)
Add a bridge.
Parameters
bridgeName bridge name
Implements org.onosproject.net.behaviour.BridgeConfig.
Definition at line 50 of file OvsdbBridgeConfig.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler().
void org.onosproject.driver.ovsdb.OvsdbBridgeConfig.addBridge (BridgeName bridgeName, String dpid, String exPortName)
Adds a bridge with given bridge name, dpid and exPortName.
Parameters
bridgeName bridge name
dpid dpid
exPortName external port name
Implements org.onosproject.net.behaviour.BridgeConfig.
Definition at line 57 of file OvsdbBridgeConfig.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler().
boolean org.onosproject.driver.ovsdb.OvsdbBridgeConfig.addBridge (BridgeName bridgeName, String dpid, List< ControllerInfo > controllers)
Adds a bridge with given bridge name and dpid, and sets the controller of the bridge with given controllers.
Parameters
bridgeName bridge name
dpid dpid
controllers list of controller
Returns
true if succeeds, fail otherwise
Implements org.onosproject.net.behaviour.BridgeConfig.
Definition at line 64 of file OvsdbBridgeConfig.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler().
void org.onosproject.driver.ovsdb.OvsdbBridgeConfig.addPort (PortDescription port)
Add a logical/virtual port.
Parameters
port port number
Implements org.onosproject.net.behaviour.BridgeConfig.
Definition at line 95 of file OvsdbBridgeConfig.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler().
void org.onosproject.driver.ovsdb.OvsdbBridgeConfig.deleteBridge (BridgeName bridgeName)
Remove a bridge.
Parameters
bridgeName bridge name
Implements org.onosproject.net.behaviour.BridgeConfig.
Definition at line 71 of file OvsdbBridgeConfig.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler().
void org.onosproject.driver.ovsdb.OvsdbBridgeConfig.deletePort (PortDescription port)
Delete a logical/virtual port.
Parameters
port port number
Implements org.onosproject.net.behaviour.BridgeConfig.
Definition at line 107 of file OvsdbBridgeConfig.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler().
Collection<BridgeDescription> org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getBridges ()
Remove a bridge.
Returns
bridge collection
Implements org.onosproject.net.behaviour.BridgeConfig.
Definition at line 78 of file OvsdbBridgeConfig.java.
References org.onosproject.net.behaviour.BridgeName.bridgeName(), find-flow.deviceId, and org.onosproject.net.driver.AbstractHandlerBehaviour.handler().
List<PortNumber> org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getLocalPorts (Iterable< String > ifaceIds)
Get logical/virtual ports by ifaceIds.
Parameters
ifaceIds the ifaceid that needed
Returns
list of PortNumber
Implements org.onosproject.net.behaviour.BridgeConfig.
Definition at line 169 of file OvsdbBridgeConfig.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler(), and obeliskHostCheck.port.
Set<PortNumber> org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getPortNumbers ()
Get a collection of port.
Returns
portNumbers set of PortNumber
Implements org.onosproject.net.behaviour.BridgeConfig.
Definition at line 154 of file OvsdbBridgeConfig.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler(), and org.onosproject.net.PortNumber.portNumber().
Collection<PortDescription> org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getPorts ()
Delete a logical/virtual port.
Returns
collection of port
Implements org.onosproject.net.behaviour.BridgeConfig.
Definition at line 119 of file OvsdbBridgeConfig.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler(), and org.onosproject.net.PortNumber.portNumber().
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/ovsdb/OvsdbBridgeConfig.java