onos: org.onosproject.common.app.ApplicationArchiveTest Class Reference
org.onosproject.common.app.ApplicationArchiveTest Class Reference
Suite of tests for the application archive utility.
Public Member Functions
void setUp ()
void tearDown () throws IOException
void saveZippedApp () throws IOException
void savePlainApp () throws IOException
void loadApp () throws IOException
void getAppNames () throws IOException
void purgeApp () throws IOException
void getAppZipStream () throws IOException
void getAppXmlStream () throws IOException
void active () throws IOException
void getBadAppDesc () throws IOException
void getBadAppStream () throws IOException
void setBadActive () throws IOException
void purgeBadApp () throws IOException
Detailed Description
Suite of tests for the application archive utility.
Definition at line 39 of file ApplicationArchiveTest.java.
Member Function Documentation
void org.onosproject.common.app.ApplicationArchiveTest.active () throws IOException
Definition at line 128 of file ApplicationArchiveTest.java.
References org.onosproject.common.app.ApplicationArchive.isActive(), and org.onosproject.common.app.ApplicationArchiveTest.savePlainApp().
void org.onosproject.common.app.ApplicationArchiveTest.getAppNames () throws IOException
Definition at line 93 of file ApplicationArchiveTest.java.
References org.onosproject.common.app.ApplicationArchiveTest.saveZippedApp().
void org.onosproject.common.app.ApplicationArchiveTest.getAppXmlStream () throws IOException
Definition at line 118 of file ApplicationArchiveTest.java.
References org.onosproject.common.app.ApplicationArchiveTest.savePlainApp().
void org.onosproject.common.app.ApplicationArchiveTest.getAppZipStream () throws IOException
Definition at line 108 of file ApplicationArchiveTest.java.
References org.onosproject.common.app.ApplicationArchiveTest.saveZippedApp().
void org.onosproject.common.app.ApplicationArchiveTest.getBadAppDesc () throws IOException
Definition at line 138 of file ApplicationArchiveTest.java.
void org.onosproject.common.app.ApplicationArchiveTest.getBadAppStream () throws IOException
Definition at line 143 of file ApplicationArchiveTest.java.
void org.onosproject.common.app.ApplicationArchiveTest.loadApp () throws IOException
Definition at line 86 of file ApplicationArchiveTest.java.
References org.onosproject.common.app.ApplicationArchiveTest.saveZippedApp().
void org.onosproject.common.app.ApplicationArchiveTest.purgeApp () throws IOException
Definition at line 100 of file ApplicationArchiveTest.java.
References org.onosproject.common.app.ApplicationArchive.getApplicationNames(), and org.onosproject.common.app.ApplicationArchiveTest.saveZippedApp().
void org.onosproject.common.app.ApplicationArchiveTest.purgeBadApp () throws IOException
Definition at line 153 of file ApplicationArchiveTest.java.
void org.onosproject.common.app.ApplicationArchiveTest.savePlainApp () throws IOException
Definition at line 78 of file ApplicationArchiveTest.java.
Referenced by org.onosproject.common.app.ApplicationArchiveTest.active(), and org.onosproject.common.app.ApplicationArchiveTest.getAppXmlStream().
void org.onosproject.common.app.ApplicationArchiveTest.saveZippedApp () throws IOException
Definition at line 70 of file ApplicationArchiveTest.java.
Referenced by org.onosproject.common.app.ApplicationArchiveTest.getAppNames(), org.onosproject.common.app.ApplicationArchiveTest.getAppZipStream(), org.onosproject.common.app.ApplicationArchiveTest.loadApp(), and org.onosproject.common.app.ApplicationArchiveTest.purgeApp().
void org.onosproject.common.app.ApplicationArchiveTest.setBadActive () throws IOException
Definition at line 148 of file ApplicationArchiveTest.java.
void org.onosproject.common.app.ApplicationArchiveTest.setUp ()
Definition at line 46 of file ApplicationArchiveTest.java.
void org.onosproject.common.app.ApplicationArchiveTest.tearDown () throws IOException
Definition at line 51 of file ApplicationArchiveTest.java.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/common/app/ApplicationArchiveTest.java