onos: org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv Class Reference
org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv Class Reference
Provides StatefulIPv4LspIdentidiersTlv.
Public Member Functions
StatefulIPv4LspIdentidiersTlv (int ipv4IngressAddress, short lspId, short tunnelId, int extendedTunnelId, int ipv4EgressAddress)
Constructor to initialize member variables.
short getTunnelId ()
Returns tunnel id.
int getextendedTunnelId ()
Returns extendedTunnelId.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
int getIpv4IngressAddress ()
Returns ipv4IngressAddress.
int getIpv4EgressAddress ()
Returns ipv4EgressAddress.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static
StatefulIPv4LspIdentidiersTlv of (int ipv4IngressAddress, short lspId, short tunnelId, int extendedTunnelId, int ipv4EgressAddress)
Creates object of StatefulIPv4LspIdentidiersTlv.
static PcepValueType read (ChannelBuffer c)
Reads the channel buffer and returns object of StatefulIPv4LspIdentidiersTlv.
Static Public Attributes
static final short TYPE = 18
static final short LENGTH = 16
static final int VALUE_LENGTH = 16
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(StatefulIPv4LspIdentidiersTlv.class)
Detailed Description
Provides StatefulIPv4LspIdentidiersTlv.
Definition at line 31 of file StatefulIPv4LspIdentidiersTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.StatefulIPv4LspIdentidiersTlv (int ipv4IngressAddress, short lspId, short tunnelId, int extendedTunnelId, int ipv4EgressAddress)
Constructor to initialize member variables.
Parameters
ipv4IngressAddress ingress ipv4 address
lspId lsp id
tunnelId tunnel id
extendedTunnelId extended tunnel id
ipv4EgressAddress egress ipv4 address
Definition at line 73 of file StatefulIPv4LspIdentidiersTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.equals(), org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.of(), and org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.equals (Object obj)
Definition at line 156 of file StatefulIPv4LspIdentidiersTlv.java.
References org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.StatefulIPv4LspIdentidiersTlv().
int org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.getextendedTunnelId ()
Returns extendedTunnelId.
Returns
extendedTunnelId
Definition at line 113 of file StatefulIPv4LspIdentidiersTlv.java.
int org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.getIpv4EgressAddress ()
Returns ipv4EgressAddress.
Returns
ipv4EgressAddress
Definition at line 136 of file StatefulIPv4LspIdentidiersTlv.java.
int org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.getIpv4IngressAddress ()
Returns ipv4IngressAddress.
Returns
ipv4IngressAddress
Definition at line 127 of file StatefulIPv4LspIdentidiersTlv.java.
short org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 146 of file StatefulIPv4LspIdentidiersTlv.java.
References org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.LENGTH.
short org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.getTunnelId ()
Returns tunnel id.
Returns
tunnelId
Definition at line 104 of file StatefulIPv4LspIdentidiersTlv.java.
short org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 141 of file StatefulIPv4LspIdentidiersTlv.java.
References org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 118 of file StatefulIPv4LspIdentidiersTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.hashCode ()
Definition at line 151 of file StatefulIPv4LspIdentidiersTlv.java.
static StatefulIPv4LspIdentidiersTlv org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.of (int ipv4IngressAddress, short lspId, short tunnelId, int extendedTunnelId, int ipv4EgressAddress) static
Creates object of StatefulIPv4LspIdentidiersTlv.
Parameters
ipv4IngressAddress ingress ipv4 address
lspId lsp id
tunnelId tunnel id
extendedTunnelId extended tunnel id
ipv4EgressAddress egress ipv4 address
Returns
object of StatefulIPv4LspIdentidiersTlv
Definition at line 93 of file StatefulIPv4LspIdentidiersTlv.java.
References org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.StatefulIPv4LspIdentidiersTlv().
static PcepValueType org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of StatefulIPv4LspIdentidiersTlv.
Parameters
c of type channel buffer
Returns
object of StatefulIPv4LspIdentidiersTlv
Definition at line 190 of file StatefulIPv4LspIdentidiersTlv.java.
References org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.StatefulIPv4LspIdentidiersTlv().
String org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.toString ()
Definition at line 201 of file StatefulIPv4LspIdentidiersTlv.java.
References org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.LENGTH, and org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.TYPE.
int org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 171 of file StatefulIPv4LspIdentidiersTlv.java.
References org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.LENGTH, and org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.LENGTH = 16 static
Definition at line 56 of file StatefulIPv4LspIdentidiersTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.getLength(), org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.toString(), and org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.write().
final Logger org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.log = LoggerFactory.getLogger(StatefulIPv4LspIdentidiersTlv.class) static protected
Definition at line 53 of file StatefulIPv4LspIdentidiersTlv.java.
final short org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.TYPE = 18 static
Definition at line 55 of file StatefulIPv4LspIdentidiersTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.getType(), org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.toString(), and org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.write().
final int org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.VALUE_LENGTH = 16 static
Definition at line 57 of file StatefulIPv4LspIdentidiersTlv.java.
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/StatefulIPv4LspIdentidiersTlv.java