onos: org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier Class Reference
org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier Class Reference
Implementation of local node descriptors, remote node descriptors and link descriptors.
Public Member Functions
BgpLinkLSIdentifier ()
Initialize fields.
BgpLinkLSIdentifier (NodeDescriptors localNodeDescriptors, NodeDescriptors remoteNodeDescriptors, LinkedList< BgpValueType > linkDescriptor)
Constructors to initialize parameters.
NodeDescriptors localNodeDescriptors ()
Returns local node descriptors.
NodeDescriptors remoteNodeDescriptors ()
Returns remote node descriptors.
List< BgpValueType > linkDescriptors ()
Returns link descriptors.
int hashCode ()
boolean equals (Object obj)
String toString ()
int compareTo (Object o)
Static Public Member Functions
static BgpLinkLSIdentifier parseLinkIdendifier (ChannelBuffer cb, byte protocolId) throws BgpParseException
Reads channel buffer and parses link identifier.
static NodeDescriptors parseNodeDescriptors (ChannelBuffer cb, short desType, byte protocolId) throws BgpParseException
Parses Local/Remote node descriptors.
static LinkedList< BgpValueType > parseLinkDescriptors (ChannelBuffer cb) throws BgpParseException
Parses link descriptors.
Static Public Attributes
static final short IPV4_INTERFACE_ADDRESS_TYPE = 259
static final short IPV4_NEIGHBOR_ADDRESS_TYPE = 260
static final short IPV6_INTERFACE_ADDRESS_TYPE = 261
static final short IPV6_NEIGHBOR_ADDRESS_TYPE = 262
Detailed Description
Implementation of local node descriptors, remote node descriptors and link descriptors.
Definition at line 43 of file BgpLinkLSIdentifier.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.BgpLinkLSIdentifier ()
Initialize fields.
Definition at line 57 of file BgpLinkLSIdentifier.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.compareTo(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.equals(), and org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkIdendifier().
org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.BgpLinkLSIdentifier (NodeDescriptors localNodeDescriptors, NodeDescriptors remoteNodeDescriptors, LinkedList< BgpValueType > linkDescriptor)
Constructors to initialize parameters.
Parameters
localNodeDescriptors local node descriptors
remoteNodeDescriptors remote node descriptors
linkDescriptor link descriptors
Definition at line 70 of file BgpLinkLSIdentifier.java.
References org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.localNodeDescriptors(), and org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.remoteNodeDescriptors().
Member Function Documentation
int org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.compareTo (Object o)
Definition at line 260 of file BgpLinkLSIdentifier.java.
References org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.BgpLinkLSIdentifier(), org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.compareTo(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.equals(), and org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.remoteNodeDescriptors().
boolean org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.equals (Object obj)
Definition at line 219 of file BgpLinkLSIdentifier.java.
References org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.BgpLinkLSIdentifier().
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.compareTo().
int org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.hashCode ()
Definition at line 214 of file BgpLinkLSIdentifier.java.
References org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.localNodeDescriptors(), and org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.remoteNodeDescriptors().
List<BgpValueType> org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.linkDescriptors ()
Returns link descriptors.
Returns
link descriptors
Definition at line 209 of file BgpLinkLSIdentifier.java.
NodeDescriptors org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.localNodeDescriptors ()
Returns local node descriptors.
Returns
local node descriptors
Definition at line 191 of file BgpLinkLSIdentifier.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.BgpLinkLSIdentifier(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.hashCode(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkIdendifier(), and org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.toString().
static LinkedList<BgpValueType> org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkDescriptors (ChannelBuffer cb) throws BgpParseException static
Parses link descriptors.
Parameters
cb ChannelBuffer
Returns
list of link descriptors
Exceptions
BgpParseException while parsing link descriptors
Definition at line 137 of file BgpLinkLSIdentifier.java.
References org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.IPV4_INTERFACE_ADDRESS_TYPE, org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.IPV4_NEIGHBOR_ADDRESS_TYPE, org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.IPV6_INTERFACE_ADDRESS_TYPE, org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.IPV6_NEIGHBOR_ADDRESS_TYPE, find-link-in-cluster.length, org.onosproject.bgpio.types.BgpErrorType.OPTIONAL_ATTRIBUTE_ERROR, org.onosproject.bgpio.util.Constants.TYPE_AND_LEN_AS_SHORT, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkIdendifier().
static BgpLinkLSIdentifier org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkIdendifier (ChannelBuffer cb, byte protocolId) throws BgpParseException static
Reads channel buffer and parses link identifier.
Parameters
cb ChannelBuffer
protocolId in linkstate nlri
Returns
object of BGPLinkLSIdentifier
Exceptions
BgpParseException while parsing link identifier
Definition at line 85 of file BgpLinkLSIdentifier.java.
References org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.BgpLinkLSIdentifier(), org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.LOCAL_NODE_DES_TYPE, org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.localNodeDescriptors(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkDescriptors(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseNodeDescriptors(), org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.REMOTE_NODE_DES_TYPE, and org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.remoteNodeDescriptors().
static NodeDescriptors org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseNodeDescriptors (ChannelBuffer cb, short desType, byte protocolId) throws BgpParseException static
Parses Local/Remote node descriptors.
Parameters
cb ChannelBuffer
desType descriptor type
protocolId protocol identifier
Returns
object of NodeDescriptors
Exceptions
BgpParseException while parsing Local/Remote node descriptors
Definition at line 109 of file BgpLinkLSIdentifier.java.
References find-link-in-cluster.length, org.onosproject.bgpio.types.BgpErrorType.MALFORMED_ATTRIBUTE_LIST, org.onosproject.bgpio.types.BgpErrorType.OPTIONAL_ATTRIBUTE_ERROR, org.onosproject.bgpio.util.Constants.TYPE_AND_LEN_AS_SHORT, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkIdendifier().
NodeDescriptors org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.remoteNodeDescriptors ()
Returns remote node descriptors.
Returns
remote node descriptors
Definition at line 200 of file BgpLinkLSIdentifier.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.BgpLinkLSIdentifier(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.compareTo(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.hashCode(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkIdendifier(), and org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.toString().
String org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.toString ()
Definition at line 251 of file BgpLinkLSIdentifier.java.
References org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.localNodeDescriptors(), and org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.remoteNodeDescriptors().
Member Data Documentation
final short org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.IPV4_INTERFACE_ADDRESS_TYPE = 259 static
Definition at line 45 of file BgpLinkLSIdentifier.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkDescriptors().
final short org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.IPV4_NEIGHBOR_ADDRESS_TYPE = 260 static
Definition at line 46 of file BgpLinkLSIdentifier.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkDescriptors().
final short org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.IPV6_INTERFACE_ADDRESS_TYPE = 261 static
Definition at line 47 of file BgpLinkLSIdentifier.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkDescriptors().
final short org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.IPV6_NEIGHBOR_ADDRESS_TYPE = 262 static
Definition at line 48 of file BgpLinkLSIdentifier.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLSIdentifier.parseLinkDescriptors().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/protocol/linkstate/BgpLinkLSIdentifier.java