onos: org.onosproject.pcepio.types.PcepNaiIpv4NodeId Class Reference
org.onosproject.pcepio.types.PcepNaiIpv4NodeId Class Reference
Provides Pcep Nai Ipv4 Node Id.
Public Member Functions
PcepNaiIpv4NodeId (int value)
Constructor to initialize ipv4NodeId.
byte getType ()
To get the ST type of the NAI information.
int write (ChannelBuffer bb)
To write the object information to channelBuffer.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static PcepNaiIpv4NodeId of (int value)
Returns an object of PcepNaiIpv4NodeId.
static PcepNaiIpv4NodeId read (ChannelBuffer bb)
Reads from the channel buffer and returns object of PcepNAIIpv4NodeIdVer1.
Static Public Attributes
static final byte ST_TYPE = 0x01
Detailed Description
Provides Pcep Nai Ipv4 Node Id.
Definition at line 29 of file PcepNaiIpv4NodeId.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PcepNaiIpv4NodeId.PcepNaiIpv4NodeId (int value)
Constructor to initialize ipv4NodeId.
Parameters
value ipv4 node id
Definition at line 40 of file PcepNaiIpv4NodeId.java.
Referenced by org.onosproject.pcepio.types.PcepNaiIpv4NodeId.equals(), org.onosproject.pcepio.types.PcepNaiIpv4NodeId.of(), and org.onosproject.pcepio.types.PcepNaiIpv4NodeId.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.PcepNaiIpv4NodeId.equals (Object obj)
Definition at line 82 of file PcepNaiIpv4NodeId.java.
References org.onosproject.pcepio.types.PcepNaiIpv4NodeId.PcepNaiIpv4NodeId().
byte org.onosproject.pcepio.types.PcepNaiIpv4NodeId.getType ()
To get the ST type of the NAI information.
Returns
type of ST info
Implements org.onosproject.pcepio.protocol.PcepNai.
Definition at line 55 of file PcepNaiIpv4NodeId.java.
References org.onosproject.pcepio.types.PcepNaiIpv4NodeId.ST_TYPE.
int org.onosproject.pcepio.types.PcepNaiIpv4NodeId.hashCode ()
Definition at line 77 of file PcepNaiIpv4NodeId.java.
static PcepNaiIpv4NodeId org.onosproject.pcepio.types.PcepNaiIpv4NodeId.of (int value) static
Returns an object of PcepNaiIpv4NodeId.
Parameters
value ipv4 node id
Returns
object of PcepNaiIpv4NodeId
Definition at line 50 of file PcepNaiIpv4NodeId.java.
References org.onosproject.pcepio.types.PcepNaiIpv4NodeId.PcepNaiIpv4NodeId().
static PcepNaiIpv4NodeId org.onosproject.pcepio.types.PcepNaiIpv4NodeId.read (ChannelBuffer bb) static
Reads from the channel buffer and returns object of PcepNAIIpv4NodeIdVer1.
Parameters
bb of channel buffer.
Returns
object of PcepNAIIpv4NodeIdVer1
Definition at line 72 of file PcepNaiIpv4NodeId.java.
References org.onosproject.pcepio.types.PcepNaiIpv4NodeId.PcepNaiIpv4NodeId().
String org.onosproject.pcepio.types.PcepNaiIpv4NodeId.toString ()
Definition at line 94 of file PcepNaiIpv4NodeId.java.
int org.onosproject.pcepio.types.PcepNaiIpv4NodeId.write (ChannelBuffer cb)
To write the object information to channelBuffer.
Parameters
cb of type channel buffer
Returns
length of written bytes.
Implements org.onosproject.pcepio.protocol.PcepNai.
Definition at line 60 of file PcepNaiIpv4NodeId.java.
Member Data Documentation
final byte org.onosproject.pcepio.types.PcepNaiIpv4NodeId.ST_TYPE = 0x01 static
Definition at line 31 of file PcepNaiIpv4NodeId.java.
Referenced by org.onosproject.pcepio.types.PcepNaiIpv4NodeId.getType().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PcepNaiIpv4NodeId.java