onos: org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler Class Reference
org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler Class Reference
An intent compiler for org.onosproject.net.intent.OpticalConnectivityIntent.
Public Member Functions
void activate ()
void deactivate ()
List< Intent > compile (OpticalConnectivityIntent intent, List< Intent > installable, Set< LinkResourceAllocations > resources)
Protected Attributes
IntentExtensionService intentManager
TopologyService topologyService
DeviceService deviceService
ResourceService resourceService
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(OpticalConnectivityIntentCompiler.class)
Detailed Description
An intent compiler for org.onosproject.net.intent.OpticalConnectivityIntent.
Definition at line 69 of file OpticalConnectivityIntentCompiler.java.
Member Function Documentation
void org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.activate ()
Definition at line 86 of file OpticalConnectivityIntentCompiler.java.
List<Intent> org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.compile (OpticalConnectivityIntent intent, List< Intent > installable, Set< LinkResourceAllocations > resources)
Definition at line 96 of file OpticalConnectivityIntentCompiler.java.
References org.onosproject.net.intent.Intent.appId(), find-link-in-cluster.dstPort, org.onosproject.net.OchSignalType.FIXED_GRID, org.onosproject.net.intent.OpticalConnectivityIntent.getDst(), org.onosproject.net.intent.OpticalConnectivityIntent.getSrc(), org.onlab.util.Frequency.ofHz(), org.onosproject.net.ConnectPoint.port(), find-link-in-cluster.srcPort, and org.onosproject.net.AnnotationKeys.STATIC_LAMBDA.
void org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.deactivate ()
Definition at line 91 of file OpticalConnectivityIntentCompiler.java.
Member Data Documentation
DeviceService org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.deviceService protected
Definition at line 80 of file OpticalConnectivityIntentCompiler.java.
IntentExtensionService org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.intentManager protected
Definition at line 74 of file OpticalConnectivityIntentCompiler.java.
final Logger org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.log = LoggerFactory.getLogger(OpticalConnectivityIntentCompiler.class) static protected
Definition at line 71 of file OpticalConnectivityIntentCompiler.java.
ResourceService org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.resourceService protected
Definition at line 83 of file OpticalConnectivityIntentCompiler.java.
TopologyService org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.topologyService protected
Definition at line 77 of file OpticalConnectivityIntentCompiler.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/intent/impl/compiler/OpticalConnectivityIntentCompiler.java