onos: org.onosproject.rest.resources.NetworkConfigWebResource Class Reference
org.onosproject.rest.resources.NetworkConfigWebResource Class Reference
Manage network configurations.
Public Member Functions
Response download ()
Get entire network configuration base.
Response download (@PathParam("subjectClassKey") String subjectClassKey)
Get all network configuration for a subject class.
Response download (@PathParam("subjectClassKey") String subjectClassKey,@PathParam("subjectKey") String subjectKey)
Get all network configuration for a subjectKey.
Response download (@PathParam("subjectClassKey") String subjectClassKey,@PathParam("subjectKey") String subjectKey,@PathParam("configKey") String configKey)
Get specific network configuration for a subjectKey.
Response upload (InputStream request) throws IOException
Upload bulk network configuration.
Response upload (@PathParam("subjectClassKey") String subjectClassKey, InputStream request) throws IOException
Upload multiple network configurations for a subject class.
Response upload (@PathParam("subjectClassKey") String subjectClassKey,@PathParam("subjectKey") String subjectKey, InputStream request) throws IOException
Upload mutliple network configurations for a subjectKey.
Response upload (@PathParam("subjectClassKey") String subjectClassKey,@PathParam("subjectKey") String subjectKey,@PathParam("configKey") String configKey, InputStream request) throws IOException
Upload specific network configuration for a subjectKey.
Response delete ()
Clear entire network configuration base.
void delete (@PathParam("subjectClassKey") String subjectClassKey)
Clear all network configurations for a subject class.
void delete (@PathParam("subjectClassKey") String subjectClassKey,@PathParam("subjectKey") String subjectKey)
Clear all network configurations for a subjectKey.
void delete (@PathParam("subjectClassKey") String subjectClassKey,@PathParam("subjectKey") String subjectKey,@PathParam("configKey") String configKey)
Clear specific network configuration for a subjectKey.
Public Member Functions inherited from org.onosproject.rest.AbstractWebResource
ObjectMapper mapper ()
Returns the JSON object mapper.
ObjectNode newObject (ObjectNode parent, String key)
Creates and returns a new child object within the specified parent and bound to the given key.
ArrayNode newArray (ObjectNode parent, String key)
Creates and returns a new child array within the specified parent and bound to the given key.
Additional Inherited Members
Static Public Member Functions inherited from org.onlab.rest.BaseResource
static void setServiceDirectory (ServiceDirectory serviceDirectory)
Sets alternate service directory to be used for lookups.
Static Protected Member Functions inherited from org.onlab.rest.BaseResource
static Response.ResponseBuilder ok (Object obj)
Detailed Description
Manage network configurations.
Definition at line 46 of file NetworkConfigWebResource.java.
Member Function Documentation
Response org.onosproject.rest.resources.NetworkConfigWebResource.delete ()
Clear entire network configuration base.
Returns
empty response
Definition at line 298 of file NetworkConfigWebResource.java.
References org.onosproject.net.config.NetworkConfigService.getSubjects(), and org.onosproject.net.config.NetworkConfigService.removeConfig().
void org.onosproject.rest.resources.NetworkConfigWebResource.delete (@PathParam("subjectClassKey") String subjectClassKey)
Clear all network configurations for a subject class.
Parameters
subjectClassKey subject class key
Definition at line 315 of file NetworkConfigWebResource.java.
References org.onosproject.net.config.NetworkConfigService.getConfigs().
void org.onosproject.rest.resources.NetworkConfigWebResource.delete (@PathParam("subjectClassKey") String subjectClassKey, @PathParam("subjectKey") String subjectKey)
Clear all network configurations for a subjectKey.
Parameters
subjectClassKey subjectKey class key
subjectKey subjectKey key
Definition at line 331 of file NetworkConfigWebResource.java.
References org.onosproject.net.config.NetworkConfigService.removeConfig().
void org.onosproject.rest.resources.NetworkConfigWebResource.delete (@PathParam("subjectClassKey") String subjectClassKey, @PathParam("subjectKey") String subjectKey, @PathParam("configKey") String configKey)
Clear specific network configuration for a subjectKey.
Parameters
subjectClassKey subjectKey class key
subjectKey subjectKey key
configKey configuration class key
Definition at line 348 of file NetworkConfigWebResource.java.
Response org.onosproject.rest.resources.NetworkConfigWebResource.download ()
Get entire network configuration base.
NetCfgGet
Returns
network configuration JSON
Definition at line 77 of file NetworkConfigWebResource.java.
Response org.onosproject.rest.resources.NetworkConfigWebResource.download (@PathParam("subjectClassKey") String subjectClassKey)
Get all network configuration for a subject class.
Parameters
subjectClassKey subject class key
Returns
network configuration JSON
Definition at line 98 of file NetworkConfigWebResource.java.
References org.onosproject.net.config.NetworkConfigService.getSubjectFactory().
Response org.onosproject.rest.resources.NetworkConfigWebResource.download (@PathParam("subjectClassKey") String subjectClassKey, @PathParam("subjectKey") String subjectKey)
Get all network configuration for a subjectKey.
Parameters
subjectClassKey subjectKey class key
subjectKey subjectKey key
Returns
network configuration JSON
Definition at line 119 of file NetworkConfigWebResource.java.
References org.onosproject.net.config.NetworkConfigService.getSubjectFactory().
Response org.onosproject.rest.resources.NetworkConfigWebResource.download (@PathParam("subjectClassKey") String subjectClassKey, @PathParam("subjectKey") String subjectKey, @PathParam("configKey") String configKey)
Get specific network configuration for a subjectKey.
Parameters
subjectClassKey subjectKey class key
subjectKey subjectKey key
configKey configuration class key
Returns
network configuration JSON
Definition at line 144 of file NetworkConfigWebResource.java.
References org.onosproject.net.config.NetworkConfigService.getConfig(), org.onosproject.net.config.NetworkConfigService.getConfigClass(), and org.onosproject.net.config.NetworkConfigService.getSubjectFactory().
Response org.onosproject.rest.resources.NetworkConfigWebResource.upload (InputStream request) throws IOException
Upload bulk network configuration.
NetCfgGet
Parameters
request network configuration JSON rooted at the top node
Returns
empty response
Exceptions
IOException if unable to parse the request
Definition at line 196 of file NetworkConfigWebResource.java.
References org.onosproject.net.config.NetworkConfigService.getSubjectFactory().
Response org.onosproject.rest.resources.NetworkConfigWebResource.upload (@PathParam("subjectClassKey") String subjectClassKey, InputStream request) throws IOException
Upload multiple network configurations for a subject class.
Parameters
subjectClassKey subject class key
request network configuration JSON rooted at the top node
Returns
empty response
Exceptions
IOException if unable to parse the request
Definition at line 217 of file NetworkConfigWebResource.java.
References org.onosproject.net.config.NetworkConfigService.getSubjectFactory().
Response org.onosproject.rest.resources.NetworkConfigWebResource.upload (@PathParam("subjectClassKey") String subjectClassKey, @PathParam("subjectKey") String subjectKey, InputStream request) throws IOException
Upload mutliple network configurations for a subjectKey.
Parameters
subjectClassKey subjectKey class key
subjectKey subjectKey key
request network configuration JSON rooted at the top node
Returns
empty response
Exceptions
IOException if unable to parse the request
Definition at line 238 of file NetworkConfigWebResource.java.
References org.onosproject.net.config.NetworkConfigService.getSubjectFactory().
Response org.onosproject.rest.resources.NetworkConfigWebResource.upload (@PathParam("subjectClassKey") String subjectClassKey, @PathParam("subjectKey") String subjectKey, @PathParam("configKey") String configKey, InputStream request) throws IOException
Upload specific network configuration for a subjectKey.
Parameters
subjectClassKey subjectKey class key
subjectKey subjectKey key
configKey configuration class key
request network configuration JSON rooted at the top node
Returns
empty response
Exceptions
IOException if unable to parse the request
Definition at line 263 of file NetworkConfigWebResource.java.
The documentation for this class was generated from the following file:
web/api/src/main/java/org/onosproject/rest/resources/NetworkConfigWebResource.java