onos: org.onosproject.driver.extensions.NiciraExtensionTreatmentInterpreter Class Reference
org.onosproject.driver.extensions.NiciraExtensionTreatmentInterpreter Class Reference
Interpreter for Nicira OpenFlow extensions.
Public Member Functions
boolean supported (ExtensionTreatmentType extensionTreatmentType)
Returns true if the given extension instruction is supported by this driver.
OFAction mapInstruction (OFFactory factory, ExtensionTreatment extensionTreatment)
Maps an extension instruction to an OpenFlow action.
ExtensionTreatment mapAction (OFAction action)
Maps an OpenFlow action to an extension instruction.
ExtensionTreatment getExtensionInstruction (ExtensionTreatmentType type)
Gets an extension instruction instance of the specified type, if supported by the driver.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Detailed Description
Interpreter for Nicira OpenFlow extensions.
Definition at line 36 of file NiciraExtensionTreatmentInterpreter.java.
Member Function Documentation
ExtensionTreatment org.onosproject.driver.extensions.NiciraExtensionTreatmentInterpreter.getExtensionInstruction (ExtensionTreatmentType type)
Gets an extension instruction instance of the specified type, if supported by the driver.
Parameters
type type of extension to get
Returns
extension instruction
Exceptions
UnsupportedOperationException if the extension type is not supported by this driver
Implements org.onosproject.net.behaviour.ExtensionTreatmentResolver.
Definition at line 91 of file NiciraExtensionTreatmentInterpreter.java.
References org.onosproject.net.flow.instructions.ExtensionTreatmentType.equals(), and org.onosproject.net.flow.instructions.ExtensionTreatmentType.toString().
ExtensionTreatment org.onosproject.driver.extensions.NiciraExtensionTreatmentInterpreter.mapAction (OFAction action)
Maps an OpenFlow action to an extension instruction.
Parameters
action OpenFlow action
Returns
extension instruction
Implements org.onosproject.openflow.controller.ExtensionTreatmentInterpreter.
Definition at line 74 of file NiciraExtensionTreatmentInterpreter.java.
References org.onlab.packet.Ip4Address.valueOf().
OFAction org.onosproject.driver.extensions.NiciraExtensionTreatmentInterpreter.mapInstruction (OFFactory factory, ExtensionTreatment extensionTreatment)
Maps an extension instruction to an OpenFlow action.
Parameters
factory OpenFlow factory
extensionTreatment extension instruction
Returns
OpenFlow action
Implements org.onosproject.openflow.controller.ExtensionTreatmentInterpreter.
Definition at line 57 of file NiciraExtensionTreatmentInterpreter.java.
References org.onosproject.net.flow.instructions.ExtensionTreatmentType.equals().
boolean org.onosproject.driver.extensions.NiciraExtensionTreatmentInterpreter.supported (ExtensionTreatmentType extensionTreatmentType)
Returns true if the given extension instruction is supported by this driver.
Parameters
extensionTreatmentType extension instruction type
Returns
true if the instruction is supported, otherwise false
Implements org.onosproject.openflow.controller.ExtensionTreatmentInterpreter.
Definition at line 40 of file NiciraExtensionTreatmentInterpreter.java.
References org.onosproject.net.flow.instructions.ExtensionTreatmentType.equals().
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/extensions/NiciraExtensionTreatmentInterpreter.java