onos: org.onosproject.app.DefaultApplicationDescriptionTest Class Reference
org.onosproject.app.DefaultApplicationDescriptionTest Class Reference
Basic tests of the default app description.
Public Member Functions
void basics ()
Static Public Attributes
static final String APP_NAME = "org.foo.app"
static final Version VER = Version.version(1, 2, "a", null)
static final String DESC = "Awesome application from Circus, Inc."
static final String ORIGIN = "Circus"
static final ApplicationRole ROLE = ApplicationRole.ADMIN
static final Set< Permission > PERMS
static final URI FURL = URI.create("mvn:org.foo-features/1.2a/xml/features")
static final List< String > FEATURES = ImmutableList.of("foo", "bar")
static final List< String > APPS = ImmutableList.of("fifi")
Detailed Description
Basic tests of the default app description.
Definition at line 37 of file DefaultApplicationDescriptionTest.java.
Member Function Documentation
void org.onosproject.app.DefaultApplicationDescriptionTest.basics ()
Definition at line 52 of file DefaultApplicationDescriptionTest.java.
References org.onosproject.app.DefaultApplicationDescriptionTest.APP_NAME, org.onosproject.app.DefaultApplicationDescriptionTest.APPS, org.onosproject.app.DefaultApplicationDescriptionTest.DESC, org.onosproject.app.ApplicationDescription.description(), org.onosproject.app.DefaultApplicationDescriptionTest.FEATURES, org.onosproject.app.ApplicationDescription.features(), org.onosproject.app.ApplicationDescription.featuresRepo(), org.onosproject.app.DefaultApplicationDescriptionTest.FURL, org.onosproject.app.ApplicationDescription.name(), org.onosproject.app.DefaultApplicationDescriptionTest.ORIGIN, org.onosproject.app.ApplicationDescription.origin(), org.onosproject.app.ApplicationDescription.permissions(), org.onosproject.app.DefaultApplicationDescriptionTest.PERMS, org.onosproject.app.ApplicationDescription.requiredApps(), org.onosproject.app.DefaultApplicationDescriptionTest.ROLE, org.onosproject.app.ApplicationDescription.role(), org.onosproject.app.DefaultApplicationDescriptionTest.VER, and org.onosproject.app.ApplicationDescription.version().
Member Data Documentation
final String org.onosproject.app.DefaultApplicationDescriptionTest.APP_NAME = "org.foo.app" static
Definition at line 39 of file DefaultApplicationDescriptionTest.java.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
final List<String> org.onosproject.app.DefaultApplicationDescriptionTest.APPS = ImmutableList.of("fifi") static
Definition at line 49 of file DefaultApplicationDescriptionTest.java.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
final String org.onosproject.app.DefaultApplicationDescriptionTest.DESC = "Awesome application from Circus, Inc." static
Definition at line 41 of file DefaultApplicationDescriptionTest.java.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
final List<String> org.onosproject.app.DefaultApplicationDescriptionTest.FEATURES = ImmutableList.of("foo", "bar") static
Definition at line 48 of file DefaultApplicationDescriptionTest.java.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
final URI org.onosproject.app.DefaultApplicationDescriptionTest.FURL = URI.create("mvn:org.foo-features/1.2a/xml/features") static
Definition at line 47 of file DefaultApplicationDescriptionTest.java.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
final String org.onosproject.app.DefaultApplicationDescriptionTest.ORIGIN = "Circus" static
Definition at line 42 of file DefaultApplicationDescriptionTest.java.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
final Set<Permission> org.onosproject.app.DefaultApplicationDescriptionTest.PERMS static
Initial value:
= ImmutableSet.of(
                            new Permission(AppPermission.class.getName(), "FLOWRULE_WRITE"),
                            new Permission(AppPermission.class.getName(), "FLOWRULE_READ"))
Definition at line 44 of file DefaultApplicationDescriptionTest.java.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
final ApplicationRole org.onosproject.app.DefaultApplicationDescriptionTest.ROLE = ApplicationRole.ADMIN static
Definition at line 43 of file DefaultApplicationDescriptionTest.java.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
final Version org.onosproject.app.DefaultApplicationDescriptionTest.VER = Version.version(1, 2, "a", null) static
Definition at line 40 of file DefaultApplicationDescriptionTest.java.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/app/DefaultApplicationDescriptionTest.java