onos: org.onosproject.net.link.impl.LinkManagerTest Class Reference
org.onosproject.net.link.impl.LinkManagerTest Class Reference
Test codifying the link service & link provider service contracts.
Public Member Functions
void setUp ()
void tearDown ()
void createLink ()
void updateLink ()
void removeLink ()
void removeLinksByConnectionPoint ()
void removeLinksByDevice ()
void removeLinksAsAdminByConnectionPoint ()
void removeLinksAsAdminByDevice ()
void getLinks ()
Protected Member Functions
void validateEvents (Enum...types)
Protected Attributes
LinkService service
LinkAdminService admin
LinkProviderRegistry registry
LinkProviderService providerService
TestProvider provider
TestListener listener = new TestListener()
DeviceManager devmgr = new TestDeviceManager()
Detailed Description
Test codifying the link service & link provider service contracts.
Definition at line 62 of file LinkManagerTest.java.
Member Function Documentation
void org.onosproject.net.link.impl.LinkManagerTest.createLink ()
Definition at line 126 of file LinkManagerTest.java.
References org.onosproject.net.link.LinkService.getLinkCount(), and org.onosproject.net.link.impl.LinkManagerTest.service.
void org.onosproject.net.link.impl.LinkManagerTest.getLinks ()
Definition at line 229 of file LinkManagerTest.java.
References org.onosproject.net.link.LinkService.getLinkCount(), and org.onosproject.net.link.impl.LinkManagerTest.service.
void org.onosproject.net.link.impl.LinkManagerTest.removeLink ()
Definition at line 153 of file LinkManagerTest.java.
References org.onosproject.net.link.LinkService.getLink(), org.onosproject.net.link.LinkService.getLinkCount(), org.onosproject.net.link.impl.LinkManagerTest.listener, org.onosproject.net.link.impl.LinkManagerTest.service, and org.onosproject.net.link.impl.LinkManagerTest.validateEvents().
void org.onosproject.net.link.impl.LinkManagerTest.removeLinksAsAdminByConnectionPoint ()
Definition at line 199 of file LinkManagerTest.java.
References org.onosproject.net.link.LinkService.getLink(), org.onosproject.net.link.LinkService.getLinkCount(), org.onosproject.net.link.impl.LinkManagerTest.service, and org.onosproject.net.Link.src().
void org.onosproject.net.link.impl.LinkManagerTest.removeLinksAsAdminByDevice ()
Definition at line 213 of file LinkManagerTest.java.
References org.onosproject.net.link.LinkService.getLink(), org.onosproject.net.link.LinkService.getLinkCount(), org.onosproject.net.link.impl.LinkManagerTest.service, and org.onosproject.net.Link.src().
void org.onosproject.net.link.impl.LinkManagerTest.removeLinksByConnectionPoint ()
Definition at line 169 of file LinkManagerTest.java.
References org.onosproject.net.link.LinkService.getLink(), org.onosproject.net.link.LinkService.getLinkCount(), org.onosproject.net.link.impl.LinkManagerTest.service, and org.onosproject.net.Link.src().
void org.onosproject.net.link.impl.LinkManagerTest.removeLinksByDevice ()
Definition at line 183 of file LinkManagerTest.java.
References org.onosproject.net.link.LinkService.getLink(), org.onosproject.net.link.LinkService.getLinkCount(), org.onosproject.net.link.impl.LinkManagerTest.service, and org.onosproject.net.Link.src().
void org.onosproject.net.link.impl.LinkManagerTest.setUp ()
Definition at line 93 of file LinkManagerTest.java.
References org.onosproject.net.link.impl.LinkManagerTest.admin, org.onosproject.net.link.impl.LinkManagerTest.devmgr, org.onosproject.net.link.impl.LinkManagerTest.listener, org.onosproject.net.link.impl.LinkManagerTest.provider, org.onosproject.net.link.impl.LinkManagerTest.providerService, org.onosproject.net.link.impl.LinkManagerTest.registry, and org.onosproject.net.link.impl.LinkManagerTest.service.
void org.onosproject.net.link.impl.LinkManagerTest.tearDown ()
Definition at line 117 of file LinkManagerTest.java.
References org.onosproject.net.link.impl.LinkManagerTest.listener, org.onosproject.net.link.impl.LinkManagerTest.provider, and org.onosproject.net.link.impl.LinkManagerTest.registry.
void org.onosproject.net.link.impl.LinkManagerTest.updateLink ()
Definition at line 138 of file LinkManagerTest.java.
References org.onosproject.net.link.LinkService.getLinkCount(), org.onosproject.net.link.impl.LinkManagerTest.listener, org.onosproject.net.link.impl.LinkManagerTest.service, and org.onosproject.net.link.impl.LinkManagerTest.validateEvents().
void org.onosproject.net.link.impl.LinkManagerTest.validateEvents (Enum... types) protected
Definition at line 267 of file LinkManagerTest.java.
References org.onosproject.net.link.impl.LinkManagerTest.listener.
Referenced by org.onosproject.net.link.impl.LinkManagerTest.removeLink(), and org.onosproject.net.link.impl.LinkManagerTest.updateLink().
Member Data Documentation
LinkAdminService org.onosproject.net.link.impl.LinkManagerTest.admin protected
Definition at line 83 of file LinkManagerTest.java.
Referenced by org.onosproject.net.link.impl.LinkManagerTest.setUp().
DeviceManager org.onosproject.net.link.impl.LinkManagerTest.devmgr = new TestDeviceManager() protected
Definition at line 88 of file LinkManagerTest.java.
Referenced by org.onosproject.net.link.impl.LinkManagerTest.setUp().
TestListener org.onosproject.net.link.impl.LinkManagerTest.listener = new TestListener() protected
Definition at line 87 of file LinkManagerTest.java.
Referenced by org.onosproject.net.link.impl.LinkManagerTest.removeLink(), org.onosproject.net.link.impl.LinkManagerTest.setUp(), org.onosproject.net.link.impl.LinkManagerTest.tearDown(), org.onosproject.net.link.impl.LinkManagerTest.updateLink(), and org.onosproject.net.link.impl.LinkManagerTest.validateEvents().
TestProvider org.onosproject.net.link.impl.LinkManagerTest.provider protected
Definition at line 86 of file LinkManagerTest.java.
Referenced by org.onosproject.net.link.impl.LinkManagerTest.setUp(), and org.onosproject.net.link.impl.LinkManagerTest.tearDown().
LinkProviderService org.onosproject.net.link.impl.LinkManagerTest.providerService protected
Definition at line 85 of file LinkManagerTest.java.
Referenced by org.onosproject.net.link.impl.LinkManagerTest.setUp().
LinkProviderRegistry org.onosproject.net.link.impl.LinkManagerTest.registry protected
Definition at line 84 of file LinkManagerTest.java.
Referenced by org.onosproject.net.link.impl.LinkManagerTest.setUp(), and org.onosproject.net.link.impl.LinkManagerTest.tearDown().
LinkService org.onosproject.net.link.impl.LinkManagerTest.service protected
Definition at line 82 of file LinkManagerTest.java.
Referenced by org.onosproject.net.link.impl.LinkManagerTest.createLink(), org.onosproject.net.link.impl.LinkManagerTest.getLinks(), org.onosproject.net.link.impl.LinkManagerTest.removeLink(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksAsAdminByConnectionPoint(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksAsAdminByDevice(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksByConnectionPoint(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksByDevice(), org.onosproject.net.link.impl.LinkManagerTest.setUp(), and org.onosproject.net.link.impl.LinkManagerTest.updateLink().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/link/impl/LinkManagerTest.java