onos: org.onosproject.net.group.GroupBuckets Class Reference
org.onosproject.net.group.GroupBuckets Class Reference
Immutable collection of group bucket.
Public Member Functions
GroupBuckets (List< GroupBucket > buckets)
Creates a immutable list of group bucket.
List< GroupBucket > buckets ()
Returns immutable list of group buckets.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Immutable collection of group bucket.
Definition at line 28 of file GroupBuckets.java.
Constructor & Destructor Documentation
org.onosproject.net.group.GroupBuckets.GroupBuckets (List< GroupBucket > buckets)
Creates a immutable list of group bucket.
Parameters
buckets list of group bucket
Definition at line 36 of file GroupBuckets.java.
Referenced by org.onosproject.net.group.GroupBuckets.equals().
Member Function Documentation
List<GroupBucket> org.onosproject.net.group.GroupBuckets.buckets ()
Returns immutable list of group buckets.
Returns
list of group bucket
Definition at line 45 of file GroupBuckets.java.
Referenced by org.onosproject.net.group.GroupBuckets.equals(), and org.onosproject.net.group.GroupBuckets.hashCode().
boolean org.onosproject.net.group.GroupBuckets.equals (Object obj)
Definition at line 62 of file GroupBuckets.java.
References org.onosproject.net.group.GroupBuckets.buckets(), and org.onosproject.net.group.GroupBuckets.GroupBuckets().
int org.onosproject.net.group.GroupBuckets.hashCode ()
Definition at line 50 of file GroupBuckets.java.
References org.onosproject.net.group.GroupBuckets.buckets().
String org.onosproject.net.group.GroupBuckets.toString ()
Definition at line 71 of file GroupBuckets.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/group/GroupBuckets.java