onos: org.onosproject.net.flow.DefaultTrafficSelectorTest Class Reference
org.onosproject.net.flow.DefaultTrafficSelectorTest Class Reference
Unit tests for default traffic selector class.
Classes
class CriterionExistsMatcher
Hamcrest matcher to check that a selector contains a Criterion with the specified type.
Public Member Functions
void testImmutability ()
Checks that the DefaultFlowRule class is immutable.
void testEquals ()
Tests equals(), hashCode() and toString() methods.
void testCriteriaCreation ()
Tests the builder functions that add specific criteria.
Static Public Member Functions
static Matcher< TrafficSelector > hasCriterionWithType (Criterion.Type type)
Creates a criterion type matcher.
Detailed Description
Unit tests for default traffic selector class.
Definition at line 47 of file DefaultTrafficSelectorTest.java.
Member Function Documentation
static Matcher<TrafficSelector> org.onosproject.net.flow.DefaultTrafficSelectorTest.hasCriterionWithType (Criterion.Type type) static
Creates a criterion type matcher.
Returns a matcher for a criterion with the given type.
Parameters
type type of Criterion to match
Returns
Matcher object
Definition at line 124 of file DefaultTrafficSelectorTest.java.
Referenced by org.onosproject.net.flow.DefaultTrafficSelectorTest.testCriteriaCreation().
void org.onosproject.net.flow.DefaultTrafficSelectorTest.testCriteriaCreation ()
Tests the builder functions that add specific criteria.
Definition at line 133 of file DefaultTrafficSelectorTest.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ETH_DST, org.onosproject.net.flow.criteria.Criterion.Type.ETH_SRC, org.onosproject.net.flow.criteria.Criterion.Type.ETH_TYPE, org.onosproject.net.flow.DefaultTrafficSelectorTest.hasCriterionWithType(), org.onosproject.net.flow.criteria.Criterion.Type.ICMPV4_CODE, org.onosproject.net.flow.criteria.Criterion.Type.ICMPV4_TYPE, org.onosproject.net.flow.criteria.Criterion.Type.ICMPV6_TYPE, org.onosproject.net.flow.criteria.Criterion.Type.IN_PHY_PORT, org.onosproject.net.flow.criteria.Criterion.Type.IN_PORT, org.onosproject.net.flow.criteria.Criterion.Type.IP_DSCP, org.onosproject.net.flow.criteria.Criterion.Type.IP_ECN, org.onosproject.net.flow.criteria.Criterion.Type.IP_PROTO, org.onosproject.net.flow.criteria.Criterion.Type.IPV4_DST, org.onosproject.net.flow.criteria.Criterion.Type.IPV4_SRC, org.onosproject.net.flow.criteria.Criterion.Type.IPV6_DST, org.onosproject.net.flow.criteria.Criterion.Type.IPV6_EXTHDR, org.onosproject.net.flow.criteria.Criterion.Type.IPV6_FLABEL, org.onosproject.net.flow.criteria.Criterion.Type.IPV6_ND_SLL, org.onosproject.net.flow.criteria.Criterion.Type.IPV6_ND_TARGET, org.onosproject.net.flow.criteria.Criterion.Type.IPV6_ND_TLL, org.onosproject.net.flow.criteria.Criterion.Type.IPV6_SRC, org.onosproject.net.flow.criteria.Criteria.matchLambda(), org.onosproject.net.flow.criteria.Criterion.Type.METADATA, org.onosproject.net.flow.criteria.Criterion.Type.MPLS_LABEL, org.onosproject.net.flow.criteria.Criterion.Type.OCH_SIGID, org.onosproject.net.PortNumber.portNumber(), org.onosproject.net.flow.criteria.Criterion.Type.SCTP_DST, org.onosproject.net.flow.criteria.Criterion.Type.SCTP_SRC, org.onosproject.net.flow.criteria.Criterion.Type.TCP_DST, org.onosproject.net.flow.criteria.Criterion.Type.TCP_SRC, org.onlab.packet.TpPort.tpPort(), org.onosproject.net.flow.criteria.Criterion.Type.UDP_DST, org.onosproject.net.flow.criteria.Criterion.Type.UDP_SRC, org.onosproject.net.flow.criteria.Criterion.Type.VLAN_PCP, org.onosproject.net.flow.criteria.Criterion.Type.VLAN_VID, and org.onlab.packet.VlanId.vlanId().
void org.onosproject.net.flow.DefaultTrafficSelectorTest.testEquals ()
Tests equals(), hashCode() and toString() methods.
Definition at line 61 of file DefaultTrafficSelectorTest.java.
References org.onosproject.net.flow.criteria.Criteria.matchLambda().
void org.onosproject.net.flow.DefaultTrafficSelectorTest.testImmutability ()
Checks that the DefaultFlowRule class is immutable.
Definition at line 53 of file DefaultTrafficSelectorTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/flow/DefaultTrafficSelectorTest.java