onos: org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1 Class Reference
Provides PCEP open object.
Classes
class Builder
Builder class for PCPE open object.
Public Member Functions
PcepOpenObjectVer1 ()
Default constructor.
PcepOpenObjectVer1 (PcepObjectHeader openObjHeader, byte keepAliveTime, byte deadTime, byte sessionID, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize all member variables.
PcepObjectHeader getOpenObjHeader ()
Returns Open object header.
void setOpenObjHeader (PcepObjectHeader obj)
Sets Open object header in Open Object.
byte getKeepAliveTime ()
Returns KeepAlive Time in Open Object.
void setKeepAliveTime (byte value)
Sets KeepAlive Time in Open Object with specified value.
PcepVersion getVersion ()
Returns version of Open Object.
byte getDeadTime ()
Returns Dead Time in Open Object.
void setDeadTime (byte value)
Sets Dead Time in Open Object with specified value.
byte getSessionId ()
Returns SessionId in Open Object.
void setSessionId (byte value)
Sets SessionId in Open Object with specified value.
LinkedList< PcepValueType > getOptionalTlv ()
Returns list of Optional Tlvs in Open Object.
void setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets list of Optional Tlvs in Open Object.
int write (ChannelBuffer cb) throws PcepParseException
Writes the Open into channel buffer.
String toString ()
Static Public Member Functions
static PcepOpenObject read (ChannelBuffer cb) throws PcepParseException
Reads from channel buffer and returns object of PcepOpenObject.
Static Public Attributes
static final PcepType MSG_TYPE = PcepType.OPEN
static final byte OPEN_OBJECT_VERSION = 1
static final byte OPEN_OBJ_TYPE = 1
static final byte OPEN_OBJ_CLASS = 1
static final byte DEFAULT_KEEPALIVE_TIME = 30
static final byte DEFAULT_DEAD_TIME = 120
static final short OPEN_OBJ_MINIMUM_LENGTH = 8
static final int DEFAULT_GMPLS_CAPABILITY_TLV_IVALUE = 0X0
static final int DEFAULT_STATEFUL_PCE_CAPABILITY_TLV_IVALUE = 0xf
static final int DEFAULT_PCECC_CAPABILITY_TLV_IVALUE = 0x7
static final int DEFAULT_PCEP_LABEL_DB_VER_TLV_IVALUE = 0X0
static final PcepObjectHeader DEFAULT_OPEN_HEADER
Protected Member Functions
int packOptionalTlv (ChannelBuffer cb)
Returns writer index.
Static Protected Member Functions
static LinkedList< PcepValueType > parseOptionalTlv (ChannelBuffer cb) throws PcepParseException
Returns linkedlist of optional tlvs.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepOpenObjectVer1.class)
Detailed Description
Provides PCEP open object.
Definition at line 43 of file PcepOpenObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.PcepOpenObjectVer1 ()
Default constructor.
Definition at line 87 of file PcepOpenObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.read().
org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.PcepOpenObjectVer1 (PcepObjectHeader openObjHeader, byte keepAliveTime, byte deadTime, byte sessionID, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize all member variables.
Parameters
openObjHeader Open Object Header
keepAliveTime Keepalive timer value
deadTime Dead timer value
sessionID session id
llOptionalTlv Optional TLV
Definition at line 104 of file PcepOpenObjectVer1.java.
Member Function Documentation
byte org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.getDeadTime ()
Returns Dead Time in Open Object.
Returns
Dead Time in Open Object
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 139 of file PcepOpenObjectVer1.java.
byte org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.getKeepAliveTime ()
Returns KeepAlive Time in Open Object.
Returns
KeepAlive Time in Open Object
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 124 of file PcepOpenObjectVer1.java.
PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.getOpenObjHeader ()
Returns Open object header.
Returns
Open object header
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 114 of file PcepOpenObjectVer1.java.
LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.getOptionalTlv ()
Returns list of Optional Tlvs in Open Object.
Returns
list of Optional Tlvs
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 159 of file PcepOpenObjectVer1.java.
byte org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.getSessionId ()
Returns SessionId in Open Object.
Returns
SessionId in Open Object
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 149 of file PcepOpenObjectVer1.java.
PcepVersion org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.getVersion ()
Returns version of Open Object.
Returns
Version of Open Object
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 134 of file PcepOpenObjectVer1.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.packOptionalTlv (ChannelBuffer cb) protected
Returns writer index.
Parameters
cb of type channel buffer.
Returns
writer index
Definition at line 322 of file PcepOpenObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.write().
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.parseOptionalTlv (ChannelBuffer cb) throws PcepParseException static protected
Returns linkedlist of optional tlvs.
Parameters
cb of type channel buffer
Returns
llOptionalTlv Optional TLV
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 212 of file PcepOpenObjectVer1.java.
References org.onosproject.pcepio.types.PceccCapabilityTlv.LENGTH, org.onosproject.pcepio.types.TedCapabilityTlv.LENGTH, org.onosproject.pcepio.types.PcepLabelDbVerTlv.LENGTH, org.onosproject.pcepio.types.GmplsCapabilityTlv.LENGTH, org.onosproject.pcepio.types.StatefulPceCapabilityTlv.LENGTH, and org.onosproject.pcepio.types.StatefulLspDbVerTlv.LENGTH.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.read().
static PcepOpenObject org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.read (ChannelBuffer cb) throws PcepParseException static
Reads from channel buffer and returns object of PcepOpenObject.
Parameters
cb of type channel buffer
Returns
object of PcepOpenObject
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 175 of file PcepOpenObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.OPEN_OBJECT_VERSION, org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.parseOptionalTlv(), org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.PcepOpenObjectVer1(), and org.onosproject.pcepio.protocol.ver1.PcepMessageVer1.SHIFT_FLAG.
void org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.setDeadTime (byte value)
Sets Dead Time in Open Object with specified value.
Parameters
value Dead Time
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 144 of file PcepOpenObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.setKeepAliveTime (byte value)
Sets KeepAlive Time in Open Object with specified value.
Parameters
value KeepAlive Time
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 129 of file PcepOpenObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.setOpenObjHeader (PcepObjectHeader obj)
Sets Open object header in Open Object.
Parameters
obj Open object header
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 119 of file PcepOpenObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets list of Optional Tlvs in Open Object.
Parameters
llOptionalTlv list of Optional Tlvs
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 164 of file PcepOpenObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.setSessionId (byte value)
Sets SessionId in Open Object with specified value.
Parameters
value SessionId
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 154 of file PcepOpenObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.toString ()
Definition at line 482 of file PcepOpenObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the Open into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException while writing Open Object into Channel Buffer.
Implements org.onosproject.pcepio.protocol.PcepOpenObject.
Definition at line 288 of file PcepOpenObjectVer1.java.
References find-link-in-cluster.length, org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.OPEN_OBJECT_VERSION, org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.packOptionalTlv(), and org.onosproject.pcepio.protocol.ver1.PcepMessageVer1.SHIFT_FLAG.
Member Data Documentation
final byte org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.DEFAULT_DEAD_TIME = 120 static
Definition at line 68 of file PcepOpenObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.DEFAULT_GMPLS_CAPABILITY_TLV_IVALUE = 0X0 static
Definition at line 70 of file PcepOpenObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.DEFAULT_KEEPALIVE_TIME = 30 static
Definition at line 67 of file PcepOpenObjectVer1.java.
final PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.DEFAULT_OPEN_HEADER static
Initial value:
= new PcepObjectHeader(OPEN_OBJ_CLASS, OPEN_OBJ_TYPE,
            PcepObjectHeader.REQ_OBJ_OPTIONAL_PROCESS, PcepObjectHeader.RSP_OBJ_PROCESSED, OPEN_OBJ_MINIMUM_LENGTH)
Definition at line 75 of file PcepOpenObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.DEFAULT_PCECC_CAPABILITY_TLV_IVALUE = 0x7 static
Definition at line 72 of file PcepOpenObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.DEFAULT_PCEP_LABEL_DB_VER_TLV_IVALUE = 0X0 static
Definition at line 73 of file PcepOpenObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.DEFAULT_STATEFUL_PCE_CAPABILITY_TLV_IVALUE = 0xf static
Definition at line 71 of file PcepOpenObjectVer1.java.
final Logger org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.log = LoggerFactory.getLogger(PcepOpenObjectVer1.class) static protected
Definition at line 61 of file PcepOpenObjectVer1.java.
final PcepType org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.MSG_TYPE = PcepType.OPEN static
Definition at line 63 of file PcepOpenObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.OPEN_OBJ_CLASS = 1 static
Definition at line 66 of file PcepOpenObjectVer1.java.
final short org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.OPEN_OBJ_MINIMUM_LENGTH = 8 static
Definition at line 69 of file PcepOpenObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.OPEN_OBJ_TYPE = 1 static
Definition at line 65 of file PcepOpenObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.OPEN_OBJECT_VERSION = 1 static
Definition at line 64 of file PcepOpenObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.read(), and org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepOpenObjectVer1.java