onos: org.onosproject.TestApplicationId Class Reference
org.onosproject.TestApplicationId Class Reference
Test application ID.
Public Member Functions
TestApplicationId (String name)
short id ()
Returns the application id.
String name ()
Returns the applications supplied identifier.
Static Public Member Functions
static ApplicationId create (String name)
Detailed Description
Test application ID.
Definition at line 25 of file TestApplicationId.java.
Constructor & Destructor Documentation
org.onosproject.TestApplicationId.TestApplicationId (String name)
Definition at line 30 of file TestApplicationId.java.
References org.onosproject.TestApplicationId.name().
Referenced by org.onosproject.TestApplicationId.create().
Member Function Documentation
static ApplicationId org.onosproject.TestApplicationId.create (String name) static
Definition at line 35 of file TestApplicationId.java.
References org.onosproject.TestApplicationId.TestApplicationId().
short org.onosproject.TestApplicationId.id ()
Returns the application id.
Returns
a short value
Implements org.onosproject.core.ApplicationId.
Definition at line 40 of file TestApplicationId.java.
String org.onosproject.TestApplicationId.name ()
Returns the applications supplied identifier.
Returns
a string identifier
Implements org.onosproject.core.ApplicationId.
Definition at line 45 of file TestApplicationId.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.TestApplicationId.TestApplicationId().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/TestApplicationId.java