onos: org.onosproject.net.host.InterfaceIpAddress Class Reference
org.onosproject.net.host.InterfaceIpAddress Class Reference
Represents a single IP address information on an interface.
Public Member Functions
InterfaceIpAddress (InterfaceIpAddress other)
Copy constructor.
InterfaceIpAddress (IpAddress ipAddress, IpPrefix subnetAddress)
Constructor for a given IP address and a subnet address.
InterfaceIpAddress (IpAddress ipAddress, IpPrefix subnetAddress, IpAddress broadcastAddress)
Constructor for a given IP address and a subnet address.
InterfaceIpAddress (IpAddress ipAddress, IpPrefix subnetAddress, IpAddress broadcastAddress, IpAddress peerAddress)
Constructor for a given IP address and a subnet address.
IpAddress ipAddress ()
Gets the IP address.
IpPrefix subnetAddress ()
Gets the IP subnet address.
IpAddress broadcastAddress ()
Gets the subnet IP broadcast address.
IpAddress peerAddress ()
Gets the IP point-to-point interface peer address.
boolean equals (Object other)
int hashCode ()
String toString ()
Static Public Member Functions
static InterfaceIpAddress valueOf (String value)
Converts a CIDR string literal to an interface IP address.
Detailed Description
Represents a single IP address information on an interface.
TODO:
Add computation for the default broadcast address if it is not specified
Add explicit checks that each IP address or prefix belong to the same IP version: IPv4/IPv6.
Inside the copy constructor we should use copy constructors for each field
Definition at line 37 of file InterfaceIpAddress.java.
Constructor & Destructor Documentation
org.onosproject.net.host.InterfaceIpAddress.InterfaceIpAddress (InterfaceIpAddress other)
Copy constructor.
Parameters
other the object to copy from
Definition at line 48 of file InterfaceIpAddress.java.
Referenced by org.onosproject.net.host.InterfaceIpAddress.equals(), and org.onosproject.net.host.InterfaceIpAddress.valueOf().
org.onosproject.net.host.InterfaceIpAddress.InterfaceIpAddress (IpAddress ipAddress, IpPrefix subnetAddress)
Constructor for a given IP address and a subnet address.
Parameters
ipAddress the IP address
subnetAddress the IP subnet address
Definition at line 62 of file InterfaceIpAddress.java.
org.onosproject.net.host.InterfaceIpAddress.InterfaceIpAddress (IpAddress ipAddress, IpPrefix subnetAddress, IpAddress broadcastAddress)
Constructor for a given IP address and a subnet address.
Parameters
ipAddress the IP address
subnetAddress the IP subnet address
broadcastAddress the IP broadcast address. It can be used to specify non-default broadcast address
Definition at line 79 of file InterfaceIpAddress.java.
References org.onosproject.net.host.InterfaceIpAddress.broadcastAddress().
org.onosproject.net.host.InterfaceIpAddress.InterfaceIpAddress (IpAddress ipAddress, IpPrefix subnetAddress, IpAddress broadcastAddress, IpAddress peerAddress)
Constructor for a given IP address and a subnet address.
Parameters
ipAddress the IP address
subnetAddress the IP subnet address
broadcastAddress the IP broadcast address. It can be used to specify non-default broadcast address. It should be null for point-to-point interfaces with a peer address
peerAddress the peer IP address for point-to-point interfaces
Definition at line 97 of file InterfaceIpAddress.java.
References org.onosproject.net.host.InterfaceIpAddress.broadcastAddress(), and org.onosproject.net.host.InterfaceIpAddress.peerAddress().
Member Function Documentation
IpAddress org.onosproject.net.host.InterfaceIpAddress.broadcastAddress ()
Gets the subnet IP broadcast address.
Returns
the subnet IP broadcast address
Definition at line 129 of file InterfaceIpAddress.java.
Referenced by org.onosproject.net.host.InterfaceIpAddress.hashCode(), and org.onosproject.net.host.InterfaceIpAddress.InterfaceIpAddress().
boolean org.onosproject.net.host.InterfaceIpAddress.equals (Object other)
Definition at line 161 of file InterfaceIpAddress.java.
References org.onosproject.net.host.InterfaceIpAddress.InterfaceIpAddress().
int org.onosproject.net.host.InterfaceIpAddress.hashCode ()
Definition at line 178 of file InterfaceIpAddress.java.
References org.onosproject.net.host.InterfaceIpAddress.broadcastAddress(), org.onosproject.net.host.InterfaceIpAddress.ipAddress(), org.onosproject.net.host.InterfaceIpAddress.peerAddress(), and org.onosproject.net.host.InterfaceIpAddress.subnetAddress().
IpAddress org.onosproject.net.host.InterfaceIpAddress.ipAddress ()
Gets the IP address.
Returns
the IP address
Definition at line 111 of file InterfaceIpAddress.java.
Referenced by org.onosproject.net.host.InterfaceIpAddress.hashCode().
IpAddress org.onosproject.net.host.InterfaceIpAddress.peerAddress ()
Gets the IP point-to-point interface peer address.
Returns
the IP point-to-point interface peer address
Definition at line 138 of file InterfaceIpAddress.java.
Referenced by org.onosproject.net.host.InterfaceIpAddress.hashCode(), and org.onosproject.net.host.InterfaceIpAddress.InterfaceIpAddress().
IpPrefix org.onosproject.net.host.InterfaceIpAddress.subnetAddress ()
Gets the IP subnet address.
Returns
the IP subnet address
Definition at line 120 of file InterfaceIpAddress.java.
Referenced by org.onosproject.net.host.InterfaceIpAddress.hashCode(), and org.onosproject.net.host.InterfaceIpAddress.toString().
String org.onosproject.net.host.InterfaceIpAddress.toString ()
Definition at line 184 of file InterfaceIpAddress.java.
References org.onosproject.net.host.InterfaceIpAddress.subnetAddress().
static InterfaceIpAddress org.onosproject.net.host.InterfaceIpAddress.valueOf (String value) static
Converts a CIDR string literal to an interface IP address.
E.g. 10.0.0.1/24
Parameters
value an IP address value in string form
Returns
an interface IP address
Exceptions
IllegalArgumentException if the argument is invalid
Definition at line 150 of file InterfaceIpAddress.java.
References org.onosproject.net.host.InterfaceIpAddress.InterfaceIpAddress().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/host/InterfaceIpAddress.java