onos: org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType Class Reference
org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType Class Reference
The "atomic-type" specifies the type of data stored in this column.
Public Member Functions
AtomicColumnType (BaseType baseType)
Constructs a AtomicColumnType object.
AtomicColumnType (BaseType baseType, int min, int max)
Constructs a AtomicColumnType object.
BaseType baseType ()
Get baseType.
int min ()
Get min.
int max ()
Get max.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
The "atomic-type" specifies the type of data stored in this column.
Refer to RFC 7047 Section 3.2.
Definition at line 27 of file AtomicColumnType.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.AtomicColumnType (BaseType baseType)
Constructs a AtomicColumnType object.
Parameters
baseType BaseType entity
Definition at line 36 of file AtomicColumnType.java.
References org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.baseType().
Referenced by org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.equals().
org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.AtomicColumnType (BaseType baseType, int min, int max)
Constructs a AtomicColumnType object.
Parameters
baseType BaseType entity
min min constraint
max max constraint
Definition at line 49 of file AtomicColumnType.java.
References org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.baseType(), org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.max(), and org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.min().
Member Function Documentation
BaseType org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.baseType ()
Get baseType.
Returns
baseType
Definition at line 60 of file AtomicColumnType.java.
Referenced by org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.AtomicColumnType(), org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.hashCode(), and org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.toString().
boolean org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.equals (Object obj)
Definition at line 86 of file AtomicColumnType.java.
References org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.AtomicColumnType().
int org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.hashCode ()
Definition at line 81 of file AtomicColumnType.java.
References org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.baseType(), org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.max(), and org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.min().
int org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.max ()
Get max.
Returns
max
Definition at line 76 of file AtomicColumnType.java.
Referenced by org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.AtomicColumnType(), org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.hashCode(), and org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.toString().
int org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.min ()
Get min.
Returns
min
Definition at line 68 of file AtomicColumnType.java.
Referenced by org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.AtomicColumnType(), org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.hashCode(), and org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.toString().
String org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.toString ()
Definition at line 100 of file AtomicColumnType.java.
References org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.baseType(), org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.max(), and org.onosproject.ovsdb.rfc.schema.type.AtomicColumnType.min().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/schema/type/AtomicColumnType.java