onos: org.onosproject.net.DefaultDisjointPath Class Reference
org.onosproject.net.DefaultDisjointPath Class Reference
Default implementation of a network disjoint path pair.
Public Member Functions
DefaultDisjointPath (ProviderId providerId, DefaultPath path1, DefaultPath path2)
Creates a disjoint path pair from two default paths.
List< Link > links ()
Returns sequence of links comprising the path.
double cost ()
Returns the path cost as a unit-less value.
Path primary ()
Gets primary path.
Path backup ()
Gets secondary path.
int hashCode ()
boolean equals (Object obj)
boolean useBackup ()
Uses backup path.
Public Member Functions inherited from org.onosproject.net.DefaultPath
DefaultPath (ProviderId providerId, List< Link > links, double cost, Annotations...annotations)
Creates a path from the specified source and destination using the supplied list of links.
List< Link > links ()
Returns sequence of links comprising the path.
double cost ()
Returns the path cost as a unit-less value.
String toString ()
int hashCode ()
boolean equals (Object obj)
Public Member Functions inherited from org.onosproject.net.DefaultLink
DefaultLink (ProviderId providerId, ConnectPoint src, ConnectPoint dst, Type type, Annotations...annotations)
Creates an active infrastructure link using the supplied information.
DefaultLink (ProviderId providerId, ConnectPoint src, ConnectPoint dst, Type type, State state, boolean isDurable, Annotations...annotations)
Creates an infrastructure link using the supplied information.
ConnectPoint src ()
Returns the link source connection point.
ConnectPoint dst ()
Returns the link destination connection point.
Type type ()
Returns the link type.
State state ()
Returns the link state.
boolean isDurable ()
Indicates if the link is to be considered durable.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel ()
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel (ProviderId providerId, Annotations...annotations)
Creates a model entity attributed to the specified provider and optionally annotated.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of a network disjoint path pair.
Definition at line 28 of file DefaultDisjointPath.java.
Constructor & Destructor Documentation
org.onosproject.net.DefaultDisjointPath.DefaultDisjointPath (ProviderId providerId, DefaultPath path1, DefaultPath path2)
Creates a disjoint path pair from two default paths.
Parameters
providerId provider identity
path1 primary path
path2 backup path
Definition at line 42 of file DefaultDisjointPath.java.
Referenced by org.onosproject.net.DefaultDisjointPath.equals().
Member Function Documentation
Path org.onosproject.net.DefaultDisjointPath.backup ()
Gets secondary path.
Returns
secondary path
Implements org.onosproject.net.DisjointPath.
Definition at line 71 of file DefaultDisjointPath.java.
double org.onosproject.net.DefaultDisjointPath.cost ()
Returns the path cost as a unit-less value.
Returns
unit-less path cost
Implements org.onosproject.net.Path.
Definition at line 58 of file DefaultDisjointPath.java.
boolean org.onosproject.net.DefaultDisjointPath.equals (Object obj)
Definition at line 81 of file DefaultDisjointPath.java.
References org.onosproject.net.DefaultDisjointPath.DefaultDisjointPath().
int org.onosproject.net.DefaultDisjointPath.hashCode ()
Definition at line 76 of file DefaultDisjointPath.java.
References org.onosproject.net.DefaultLink.dst(), and org.onosproject.net.DefaultLink.src().
List<Link> org.onosproject.net.DefaultDisjointPath.links ()
Returns sequence of links comprising the path.
Returns
list of links
Implements org.onosproject.net.Path.
Definition at line 49 of file DefaultDisjointPath.java.
Path org.onosproject.net.DefaultDisjointPath.primary ()
Gets primary path.
Returns
primary path
Implements org.onosproject.net.DisjointPath.
Definition at line 66 of file DefaultDisjointPath.java.
boolean org.onosproject.net.DefaultDisjointPath.useBackup ()
Uses backup path.
Returns
boolean corresponding to whether request to use backup was successful.
Implements org.onosproject.net.DisjointPath.
Definition at line 93 of file DefaultDisjointPath.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/DefaultDisjointPath.java