onos: org.onosproject.segmentrouting.ECMPShortestPathGraph Class Reference
org.onosproject.segmentrouting.ECMPShortestPathGraph Class Reference
This class creates bandwidth constrained breadth first tree and returns paths from root Device to leaf Devices which satisfies the bandwidth condition.
Public Member Functions
ECMPShortestPathGraph (DeviceId rootDevice, List< String > deviceIdListToAvoid, List< Link > linkListToAvoid)
Constructor.
ECMPShortestPathGraph (DeviceId rootDevice, SegmentRoutingManager srManager)
Constructor.
DeviceId getRootDevice ()
Return root Device for the graph.
ArrayList< Path > getECMPPaths (DeviceId targetDevice)
Return the computed ECMP paths from the root Device to a given Device in the network.
HashMap< Integer, HashMap
< DeviceId, ArrayList< Path > > > getCompleteLearnedDeviceesAndPaths ()
Return the complete info of the computed ECMP paths for each Device learned in multiple iterations from the root Device.
HashMap< Integer, HashMap
< DeviceId, ArrayList
< ArrayList< DeviceId > > > > getAllLearnedSwitchesAndVia ()
Return the complete info of the computed ECMP paths for each Device learned in multiple iterations from the root Device.
String toString ()
Detailed Description
This class creates bandwidth constrained breadth first tree and returns paths from root Device to leaf Devices which satisfies the bandwidth condition.
If bandwidth parameter is not specified, the normal breadth first tree will be calculated. The paths are snapshot paths at the point of the class instantiation.
Definition at line 39 of file ECMPShortestPathGraph.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.ECMPShortestPathGraph.ECMPShortestPathGraph (DeviceId rootDevice, List< String > deviceIdListToAvoid, List< Link > linkListToAvoid)
Constructor.
Parameters
rootDevice root of the BFS tree
linkListToAvoid link list to avoid
deviceIdListToAvoid device list to avoid
Definition at line 58 of file ECMPShortestPathGraph.java.
org.onosproject.segmentrouting.ECMPShortestPathGraph.ECMPShortestPathGraph (DeviceId rootDevice, SegmentRoutingManager srManager)
Constructor.
Parameters
rootDevice root of the BFS tree
srManager SegmentRoutingManager object
Definition at line 70 of file ECMPShortestPathGraph.java.
Member Function Documentation
HashMap<Integer, HashMap<DeviceId, ArrayList<ArrayList<DeviceId> > > > org.onosproject.segmentrouting.ECMPShortestPathGraph.getAllLearnedSwitchesAndVia ()
Return the complete info of the computed ECMP paths for each Device learned in multiple iterations from the root Device.
Returns
the hash table of Devices learned in multiple Dijkstra iterations and corresponding ECMP paths in terms of Devices to be traversed to it from the root Device
Definition at line 313 of file ECMPShortestPathGraph.java.
References find-flow.deviceId, and org.onosproject.segmentrouting.ECMPShortestPathGraph.getECMPPaths().
HashMap<Integer, HashMap<DeviceId, ArrayList<Path> > > org.onosproject.segmentrouting.ECMPShortestPathGraph.getCompleteLearnedDeviceesAndPaths ()
Return the complete info of the computed ECMP paths for each Device learned in multiple iterations from the root Device.
Returns
the hash table of Devices learned in multiple Dijkstra iterations and corresponding ECMP paths to it from the root Device
Definition at line 289 of file ECMPShortestPathGraph.java.
References org.onosproject.segmentrouting.ECMPShortestPathGraph.getECMPPaths().
ArrayList<Path> org.onosproject.segmentrouting.ECMPShortestPathGraph.getECMPPaths (DeviceId targetDevice)
Return the computed ECMP paths from the root Device to a given Device in the network.
Parameters
targetDevice the target Device
Returns
the list of ECMP Paths from the root Device to the target Device
Definition at line 268 of file ECMPShortestPathGraph.java.
Referenced by org.onosproject.segmentrouting.ECMPShortestPathGraph.getAllLearnedSwitchesAndVia(), org.onosproject.segmentrouting.ECMPShortestPathGraph.getCompleteLearnedDeviceesAndPaths(), and org.onosproject.segmentrouting.ECMPShortestPathGraph.toString().
DeviceId org.onosproject.segmentrouting.ECMPShortestPathGraph.getRootDevice ()
Return root Device for the graph.
Returns
root Device
Definition at line 257 of file ECMPShortestPathGraph.java.
String org.onosproject.segmentrouting.ECMPShortestPathGraph.toString ()
Definition at line 352 of file ECMPShortestPathGraph.java.
References create-flow.device, org.onosproject.segmentrouting.SegmentRoutingManager.deviceService, org.onosproject.net.Link.dst(), org.onosproject.net.device.DeviceService.getDevices(), and org.onosproject.segmentrouting.ECMPShortestPathGraph.getECMPPaths().
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/ECMPShortestPathGraph.java