onos: org.onosproject.net.behaviour.DefaultBridgeDescription Class Reference
org.onosproject.net.behaviour.DefaultBridgeDescription Class Reference
The default implementation of bridge.
Public Member Functions
DefaultBridgeDescription (BridgeName name, DeviceId controllerId, DeviceId deviceId, SparseAnnotations...annotations)
BridgeName bridgeName ()
Returns bridge name.
DeviceId deviceId ()
Returns bridge identifier .
DeviceId cotrollerDeviceId ()
Returns controller identifier that this bridge belongs to.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractDescription
SparseAnnotations annotations ()
Returns the key/value annotations.
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractDescription
AbstractDescription ()
AbstractDescription (SparseAnnotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
The default implementation of bridge.
Definition at line 29 of file DefaultBridgeDescription.java.
Constructor & Destructor Documentation
org.onosproject.net.behaviour.DefaultBridgeDescription.DefaultBridgeDescription (BridgeName name, DeviceId controllerId, DeviceId deviceId, SparseAnnotations... annotations)
Definition at line 36 of file DefaultBridgeDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), and org.onosproject.net.behaviour.DefaultBridgeDescription.deviceId().
Referenced by org.onosproject.net.behaviour.DefaultBridgeDescription.equals().
Member Function Documentation
BridgeName org.onosproject.net.behaviour.DefaultBridgeDescription.bridgeName ()
Returns bridge name.
Returns
bridge name
Implements org.onosproject.net.behaviour.BridgeDescription.
Definition at line 46 of file DefaultBridgeDescription.java.
DeviceId org.onosproject.net.behaviour.DefaultBridgeDescription.cotrollerDeviceId ()
Returns controller identifier that this bridge belongs to.
Returns
controller identifier
Implements org.onosproject.net.behaviour.BridgeDescription.
Definition at line 56 of file DefaultBridgeDescription.java.
DeviceId org.onosproject.net.behaviour.DefaultBridgeDescription.deviceId ()
Returns bridge identifier .
Returns
bridge identifier
Implements org.onosproject.net.behaviour.BridgeDescription.
Definition at line 51 of file DefaultBridgeDescription.java.
Referenced by org.onosproject.net.behaviour.DefaultBridgeDescription.DefaultBridgeDescription(), org.onosproject.net.behaviour.DefaultBridgeDescription.hashCode(), and org.onosproject.net.behaviour.DefaultBridgeDescription.toString().
boolean org.onosproject.net.behaviour.DefaultBridgeDescription.equals (Object obj)
Definition at line 66 of file DefaultBridgeDescription.java.
References org.onosproject.net.behaviour.DefaultBridgeDescription.DefaultBridgeDescription(), org.onosproject.net.behaviour.DefaultBridgeDescription.equals(), and create-flow.name.
Referenced by org.onosproject.net.behaviour.DefaultBridgeDescription.equals().
int org.onosproject.net.behaviour.DefaultBridgeDescription.hashCode ()
Definition at line 61 of file DefaultBridgeDescription.java.
References org.onosproject.net.behaviour.DefaultBridgeDescription.deviceId().
String org.onosproject.net.behaviour.DefaultBridgeDescription.toString ()
Definition at line 81 of file DefaultBridgeDescription.java.
References org.onosproject.net.behaviour.DefaultBridgeDescription.deviceId().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/behaviour/DefaultBridgeDescription.java