onos: attcli.IperfCLI Class Reference
attcli.IperfCLI Class Reference
Public Member Functions
def __init__
def __del__
def start
def udpstart
def udpstop
def do_udp
def do_stop
def do_bw
def do_rand
def do_jobs
Public Attributes
iperfs
bw
mn
lastbw
Detailed Description
Definition at line 19 of file attcli.py.
Constructor & Destructor Documentation
def attcli.IperfCLI.__init__ (self, net, args, kwargs)
Definition at line 22 of file attcli.py.
def attcli.IperfCLI.__del__ (self)
Definition at line 31 of file attcli.py.
Member Function Documentation
def attcli.IperfCLI.do_bw (self, line)
Definition at line 76 of file attcli.py.
References attcli.IperfCLI.lastbw, and obeliskHostCheck.output.
def attcli.IperfCLI.do_jobs (self, line)
Definition at line 113 of file attcli.py.
References obeliskHostCheck.output.
def attcli.IperfCLI.do_rand (self, line)
rand [N [bw]]: Start N random flows (default: 10)
   at the given bandwidth (default: 12k)
   Note: this may replace existing flows
Definition at line 90 of file attcli.py.
References attcli.IperfCLI.bw, obeliskHostCheck.output, and attcli.IperfCLI.udpstart().
def attcli.IperfCLI.do_stop (self, line)
Definition at line 67 of file attcli.py.
References attcli.IperfCLI.udpstop().
def attcli.IperfCLI.do_udp (self, line)
udp h1 h2 [rate]: start a udp iperf session from h1 to h2
   rate: udp transmit rate [12k]
Definition at line 56 of file attcli.py.
References attcli.IperfCLI.bw, and attcli.IperfCLI.udpstart().
def attcli.IperfCLI.start (self)
Definition at line 35 of file attcli.py.
References attcli.IperfCLI.iperfs.
def attcli.IperfCLI.udpstart (self, h1, h2, bw)
Definition at line 43 of file attcli.py.
References attcli.IperfCLI.udpstop().
Referenced by attcli.IperfCLI.do_rand(), and attcli.IperfCLI.do_udp().
def attcli.IperfCLI.udpstop (self, h)
Definition at line 51 of file attcli.py.
Referenced by attcli.IperfCLI.do_stop(), and attcli.IperfCLI.udpstart().
Member Data Documentation
attcli.IperfCLI.bw
Definition at line 24 of file attcli.py.
Referenced by attcli.IperfCLI.do_rand(), and attcli.IperfCLI.do_udp().
attcli.IperfCLI.iperfs
Definition at line 23 of file attcli.py.
Referenced by attcli.IperfCLI.start().
attcli.IperfCLI.lastbw
Definition at line 26 of file attcli.py.
Referenced by attcli.IperfCLI.do_bw().
attcli.IperfCLI.mn
Definition at line 25 of file attcli.py.
The documentation for this class was generated from the following file:
tools/test/topos/attcli.py