onos: org.onosproject.net.topology.DefaultTopologyVertex Class Reference
org.onosproject.net.topology.DefaultTopologyVertex Class Reference
Implementation of the topology vertex backed by a device id.
Public Member Functions
DefaultTopologyVertex (DeviceId deviceId)
Creates a new topology vertex.
DeviceId deviceId ()
Returns the associated infrastructure device identification.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Implementation of the topology vertex backed by a device id.
Definition at line 25 of file DefaultTopologyVertex.java.
Constructor & Destructor Documentation
org.onosproject.net.topology.DefaultTopologyVertex.DefaultTopologyVertex (DeviceId deviceId)
Creates a new topology vertex.
Parameters
deviceId backing infrastructure device identifier
Definition at line 34 of file DefaultTopologyVertex.java.
References org.onosproject.net.topology.DefaultTopologyVertex.deviceId().
Referenced by org.onosproject.net.topology.DefaultTopologyVertex.equals().
Member Function Documentation
DeviceId org.onosproject.net.topology.DefaultTopologyVertex.deviceId ()
Returns the associated infrastructure device identification.
Returns
device identifier
Implements org.onosproject.net.topology.TopologyVertex.
Definition at line 39 of file DefaultTopologyVertex.java.
Referenced by org.onosproject.net.topology.DefaultTopologyVertex.DefaultTopologyVertex().
boolean org.onosproject.net.topology.DefaultTopologyVertex.equals (Object obj)
Definition at line 49 of file DefaultTopologyVertex.java.
References org.onosproject.net.topology.DefaultTopologyVertex.DefaultTopologyVertex(), and find-flow.deviceId.
int org.onosproject.net.topology.DefaultTopologyVertex.hashCode ()
Definition at line 44 of file DefaultTopologyVertex.java.
String org.onosproject.net.topology.DefaultTopologyVertex.toString ()
Definition at line 61 of file DefaultTopologyVertex.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/topology/DefaultTopologyVertex.java