onos: org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1 Class Reference
Provides PCEP TE Object.
Classes
class Builder
Builder class for PCEP te object.
Public Member Functions
PcepTEObjectVer1 (PcepObjectHeader teObjHeader, byte yProtocolId, boolean bRFlag, boolean bSFlag, int iTEId, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize variables.
PcepObjectHeader getTEObjHeader ()
Returns TE object header.
void setTEObjHeader (PcepObjectHeader obj)
Sets TE Object header.
byte getProtocolId ()
Returns ProtocolId in TE Object.
void setProtocolId (byte yProtId)
Sets ProtocolId in TE Object.
boolean getRFlag ()
Returns R flag in TE Object.
void setRFlag (boolean bRFlag)
Sets R flag in TE Object.
boolean getSFlag ()
Returns S flag in TE Object.
void setSFlag (boolean bSFlag)
Sets S flag in TE Object.
int getTEId ()
Returns TE ID in TE Object.
void setTEId (int iTEId)
Sets TE ID in TE Object.
LinkedList< PcepValueType > getOptionalTlv ()
Returns list of Optional Tlvs in TE Object.
void setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets list of Optional Tlvs in TE Object.
int write (ChannelBuffer cb) throws PcepParseException
Writes the TE Object into channel buffer.
String toString ()
Static Public Member Functions
static PcepTEObject read (ChannelBuffer cb) throws PcepParseException
Reads from the channel buffer and returns Object of PcepTEObject.
Static Public Attributes
static final byte TE_OBJ_TYPE_NODE_VALUE = 1
static final byte TE_OBJ_TYPE_LINK_VALUE = 2
static final byte TE_OBJ_CLASS = 101
static final byte TE_OBJECT_VERSION = 1
static final short TE_OBJ_MINIMUM_LENGTH = 12
static final byte DEFAULT_PROTOCOL_ID = 1
static final boolean DEFAULT_R_FLAG = false
static final boolean DEFAULT_S_FLAG = false
static final int DEFAULT_TE_ID = 0
static final int OBJECT_HEADER_LENGTH = 4
static final int RIGHT_SHIFT_ONE = 1
static final int RIGHT_FIRST_FLAG = 0x1
static final int FLAG_SET_R_FLAG = 0x2
static final int FLAG_SET_S_FLAG = 0x1
static final int MINIMUM_COMMON_HEADER_LENGTH = 4
static final int MINIMUM_TLV_HEADER_LENGTH = 4
static final PcepObjectHeader DEFAULT_TE_OBJECT_HEADER
Protected Member Functions
int packOptionalTlv (ChannelBuffer cb)
Returns the writer index.
Static Protected Member Functions
static LinkedList< PcepValueType > parseOptionalTlv (ChannelBuffer cb) throws PcepParseException
Returns Linked list of PCEP Value Type.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepTEObjectVer1.class)
Detailed Description
Provides PCEP TE Object.
Definition at line 41 of file PcepTEObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.PcepTEObjectVer1 (PcepObjectHeader teObjHeader, byte yProtocolId, boolean bRFlag, boolean bSFlag, int iTEId, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize variables.
Parameters
teObjHeader TE Object header
yProtocolId Protocol-ID
bRFlag R-flag
bSFlag S-flag
iTEId TE-ID
llOptionalTlv linked list of Optional TLV
Definition at line 115 of file PcepTEObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.read().
Member Function Documentation
LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.getOptionalTlv ()
Returns list of Optional Tlvs in TE Object.
Returns
list of Optional Tlvs
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 177 of file PcepTEObjectVer1.java.
byte org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.getProtocolId ()
Returns ProtocolId in TE Object.
Returns
ProtocolId in TE Object
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 137 of file PcepTEObjectVer1.java.
boolean org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.getRFlag ()
Returns R flag in TE Object.
Returns
R flag in TE Object
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 147 of file PcepTEObjectVer1.java.
boolean org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.getSFlag ()
Returns S flag in TE Object.
Returns
S flag in TE Object
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 157 of file PcepTEObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.getTEId ()
Returns TE ID in TE Object.
Returns
TE ID in TE Object
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 167 of file PcepTEObjectVer1.java.
PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.getTEObjHeader ()
Returns TE object header.
Returns
TE object header
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 127 of file PcepTEObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.packOptionalTlv (ChannelBuffer cb) protected
Returns the writer index.
Parameters
cb of type channel buffer
Returns
the writer index.
Definition at line 339 of file PcepTEObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.write().
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.parseOptionalTlv (ChannelBuffer cb) throws PcepParseException static protected
Returns Linked list of PCEP Value Type.
Parameters
cb of channel buffer
Returns
Linked list of PCEP Value Type
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 276 of file PcepTEObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.MINIMUM_TLV_HEADER_LENGTH.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.read().
static PcepTEObject org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.read (ChannelBuffer cb) throws PcepParseException static
Reads from the channel buffer and returns Object of PcepTEObject.
Parameters
cb of type channel buffer
Returns
Object of PcepTEObject
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 193 of file PcepTEObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.FLAG_SET_R_FLAG, org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.FLAG_SET_S_FLAG, org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.OBJECT_HEADER_LENGTH, org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.parseOptionalTlv(), and org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.PcepTEObjectVer1().
void org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets list of Optional Tlvs in TE Object.
Parameters
llOptionalTlv list of Optional Tlvs
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 182 of file PcepTEObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.setProtocolId (byte yProtId)
Sets ProtocolId in TE Object.
Parameters
yProtId ProtocolId in TE Object
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 142 of file PcepTEObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.setRFlag (boolean bRFlag)
Sets R flag in TE Object.
Parameters
bRFlag R flag in TE Object
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 152 of file PcepTEObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.setSFlag (boolean bSFlag)
Sets S flag in TE Object.
Parameters
bSFlag S flag in TE Object
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 162 of file PcepTEObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.setTEId (int iTEId)
Sets TE ID in TE Object.
Parameters
iTEId TE ID in TE Object
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 172 of file PcepTEObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.setTEObjHeader (PcepObjectHeader obj)
Sets TE Object header.
Parameters
obj TE Object header
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 132 of file PcepTEObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.toString ()
Definition at line 496 of file PcepTEObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the TE Object into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException when obj header is not written to channel buffer
Implements org.onosproject.pcepio.protocol.PcepTEObject.
Definition at line 226 of file PcepTEObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.FLAG_SET_R_FLAG, org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.FLAG_SET_S_FLAG, find-link-in-cluster.length, and org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.packOptionalTlv().
Member Data Documentation
final byte org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.DEFAULT_PROTOCOL_ID = 1 static
Definition at line 79 of file PcepTEObjectVer1.java.
final boolean org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.DEFAULT_R_FLAG = false static
Definition at line 80 of file PcepTEObjectVer1.java.
final boolean org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.DEFAULT_S_FLAG = false static
Definition at line 81 of file PcepTEObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.DEFAULT_TE_ID = 0 static
Definition at line 82 of file PcepTEObjectVer1.java.
final PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.DEFAULT_TE_OBJECT_HEADER static
Initial value:
= new PcepObjectHeader(TE_OBJ_CLASS,
            TE_OBJ_TYPE_NODE_VALUE, PcepObjectHeader.REQ_OBJ_OPTIONAL_PROCESS, PcepObjectHeader.RSP_OBJ_PROCESSED,
            TE_OBJ_MINIMUM_LENGTH)
Definition at line 92 of file PcepTEObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.FLAG_SET_R_FLAG = 0x2 static
Definition at line 87 of file PcepTEObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.read(), and org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.write().
final int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.FLAG_SET_S_FLAG = 0x1 static
Definition at line 88 of file PcepTEObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.read(), and org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.write().
final Logger org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.log = LoggerFactory.getLogger(PcepTEObjectVer1.class) static protected
Definition at line 67 of file PcepTEObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.MINIMUM_COMMON_HEADER_LENGTH = 4 static
Definition at line 89 of file PcepTEObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.MINIMUM_TLV_HEADER_LENGTH = 4 static
Definition at line 90 of file PcepTEObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.parseOptionalTlv().
final int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.OBJECT_HEADER_LENGTH = 4 static
Definition at line 84 of file PcepTEObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.read().
final int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.RIGHT_FIRST_FLAG = 0x1 static
Definition at line 86 of file PcepTEObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.RIGHT_SHIFT_ONE = 1 static
Definition at line 85 of file PcepTEObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.TE_OBJ_CLASS = 101 static
Definition at line 72 of file PcepTEObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorVer1.parseTEList(), org.onosproject.pcepio.protocol.ver1.PcepErrorInfoVer1.read(), and org.onosproject.pcepio.protocol.ver1.PcepErrorVer1.read().
final short org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.TE_OBJ_MINIMUM_LENGTH = 12 static
Definition at line 76 of file PcepTEObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.TE_OBJ_TYPE_LINK_VALUE = 2 static
Definition at line 70 of file PcepTEObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorVer1.parseTEList().
final byte org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.TE_OBJ_TYPE_NODE_VALUE = 1 static
Definition at line 69 of file PcepTEObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorVer1.parseTEList().
final byte org.onosproject.pcepio.protocol.ver1.PcepTEObjectVer1.TE_OBJECT_VERSION = 1 static
Definition at line 73 of file PcepTEObjectVer1.java.
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepTEObjectVer1.java