onos: org.onosproject.driver.extensions.NiciraSetNshSpi Class Reference
org.onosproject.driver.extensions.NiciraSetNshSpi Class Reference
Nicira set NSH SPI extension instruction.
Public Member Functions
int nshSpi ()
Gets the nsh service path index.
ExtensionTreatmentType type ()
Gets the type of the extension instruction.
void deserialize (byte[] data)
Deserialize the extension instruction from a byte array.
byte[] serialize ()
Serialize the extension instruction to a byte array.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.flow.instructions.AbstractExtensionTreatment
List< String > getProperties ()
Gets a list of all properties on the extension instruction.
Detailed Description
Nicira set NSH SPI extension instruction.
Definition at line 31 of file NiciraSetNshSpi.java.
Member Function Documentation
void org.onosproject.driver.extensions.NiciraSetNshSpi.deserialize (byte[] data)
Deserialize the extension instruction from a byte array.
The properties of this object will be overwritten with the data in the byte array.
Parameters
data input byte array
Implements org.onosproject.net.flow.instructions.ExtensionTreatment.
Definition at line 71 of file NiciraSetNshSpi.java.
boolean org.onosproject.driver.extensions.NiciraSetNshSpi.equals (Object obj)
Definition at line 86 of file NiciraSetNshSpi.java.
References org.onosproject.driver.extensions.NiciraSetNshSpi.nshSpi().
int org.onosproject.driver.extensions.NiciraSetNshSpi.hashCode ()
Definition at line 81 of file NiciraSetNshSpi.java.
References org.onosproject.driver.extensions.NiciraSetNshSpi.nshSpi().
int org.onosproject.driver.extensions.NiciraSetNshSpi.nshSpi ()
Gets the nsh service path index.
Returns
nsh service path index
Definition at line 61 of file NiciraSetNshSpi.java.
Referenced by org.onosproject.driver.extensions.NiciraSetNshSpi.equals(), org.onosproject.driver.extensions.NiciraSetNshSpi.hashCode(), and org.onosproject.driver.extensions.NiciraSetNshSpi.serialize().
byte [] org.onosproject.driver.extensions.NiciraSetNshSpi.serialize ()
Serialize the extension instruction to a byte array.
Returns
byte array
Implements org.onosproject.net.flow.instructions.ExtensionTreatment.
Definition at line 76 of file NiciraSetNshSpi.java.
References org.onosproject.driver.extensions.NiciraSetNshSpi.nshSpi().
String org.onosproject.driver.extensions.NiciraSetNshSpi.toString ()
Definition at line 99 of file NiciraSetNshSpi.java.
ExtensionTreatmentType org.onosproject.driver.extensions.NiciraSetNshSpi.type ()
Gets the type of the extension instruction.
Returns
type
Implements org.onosproject.net.flow.instructions.ExtensionTreatment.
Definition at line 66 of file NiciraSetNshSpi.java.
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/extensions/NiciraSetNshSpi.java