onos: org.onosproject.codec.impl.ApplicationCodec Class Reference
org.onosproject.codec.impl.ApplicationCodec Class Reference
Application JSON codec.
Public Member Functions
ObjectNode encode (Application app, CodecContext context)
Detailed Description
Application JSON codec.
Definition at line 29 of file ApplicationCodec.java.
Member Function Documentation
ObjectNode org.onosproject.codec.impl.ApplicationCodec.encode (Application app, CodecContext context)
Definition at line 32 of file ApplicationCodec.java.
References org.onosproject.core.Application.description(), org.onosproject.core.Application.id(), create-flow.name, org.onosproject.core.Application.origin(), org.onosproject.core.Application.permissions(), and org.onosproject.core.Application.requiredApps().
The documentation for this class was generated from the following file:
core/common/src/main/java/org/onosproject/codec/impl/ApplicationCodec.java