onos: org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree Class Reference
org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree Class Reference
Provides a policy tree to store all flow tables for each device.
Public Member Functions
FlowObjectiveCompositionTree (short applicationId)
FlowObjectiveCompositionTree (Character ch)
List< ForwardingObjective > updateForward (ForwardingObjective forwardingObjective)
ForwardUpdateTable updateForwardNode (ForwardingObjective forwardingObjective)
List< NextObjective > updateNext (NextObjective nextObjective)
String toString ()
Public Attributes
FlowObjectiveCompositionManager.PolicyOperator operator
FlowObjectiveCompositionTree leftChild
FlowObjectiveCompositionTree rightChild
short applicationId
Protected Member Functions
List< FilteringObjective > updateFilter (FilteringObjective filteringObjective)
List< FilteringObjective > updateFilterParallel (FilteringObjective filteringObjective)
List< FilteringObjective > updateFilterSequential (FilteringObjective filteringObjective)
List< FilteringObjective > updateFilterOverride (FilteringObjective filteringObjective)
ForwardUpdateTable updateForwardComposition (ForwardingObjective forwardingObjective)
List< NextObjective > updateNextComposition (NextObjective nextObjective)
Protected Attributes
FilterTable filterTable
ForwardTable forwardTable
NextTable nextTable
int priorityMultiplier
int priorityAddend
Detailed Description
Provides a policy tree to store all flow tables for each device.
Note: This class uses in-memory structures and is not yet distributed.
Definition at line 31 of file FlowObjectiveCompositionTree.java.
Constructor & Destructor Documentation
org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.FlowObjectiveCompositionTree (short applicationId)
Definition at line 44 of file FlowObjectiveCompositionTree.java.
References org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.applicationId.
org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.FlowObjectiveCompositionTree (Character ch)
Definition at line 56 of file FlowObjectiveCompositionTree.java.
Member Function Documentation
String org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.toString ()
Definition at line 252 of file FlowObjectiveCompositionTree.java.
References org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.applicationId.
List<FilteringObjective> org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilter (FilteringObjective filteringObjective) protected
Definition at line 81 of file FlowObjectiveCompositionTree.java.
References org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.applicationId, org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilterOverride(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilterParallel(), and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilterSequential().
List<FilteringObjective> org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilterOverride (FilteringObjective filteringObjective) protected
Definition at line 120 of file FlowObjectiveCompositionTree.java.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilter().
List<FilteringObjective> org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilterParallel (FilteringObjective filteringObjective) protected
Definition at line 101 of file FlowObjectiveCompositionTree.java.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilter().
List<FilteringObjective> org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilterSequential (FilteringObjective filteringObjective) protected
Definition at line 113 of file FlowObjectiveCompositionTree.java.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilter().
List<ForwardingObjective> org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateForward (ForwardingObjective forwardingObjective)
Definition at line 126 of file FlowObjectiveCompositionTree.java.
ForwardUpdateTable org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateForwardComposition (ForwardingObjective forwardingObjective) protected
Definition at line 147 of file FlowObjectiveCompositionTree.java.
References org.onosproject.net.flowobjective.impl.composition.ForwardUpdateTable.addObjectives, org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.forwardTable, org.onosproject.net.flowobjective.impl.composition.ForwardTable.getForwardingObjectives(), org.onosproject.net.flowobjective.impl.composition.ForwardUpdateTable.removeObjectives, and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.rightChild.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateForwardNode().
ForwardUpdateTable org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateForwardNode (ForwardingObjective forwardingObjective)
Definition at line 130 of file FlowObjectiveCompositionTree.java.
References org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.applicationId, and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateForwardComposition().
List<NextObjective> org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateNext (NextObjective nextObjective)
Definition at line 222 of file FlowObjectiveCompositionTree.java.
References org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.applicationId, and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateNextComposition().
List<NextObjective> org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateNextComposition (NextObjective nextObjective) protected
Definition at line 240 of file FlowObjectiveCompositionTree.java.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateNext().
Member Data Documentation
short org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.applicationId
Definition at line 36 of file FlowObjectiveCompositionTree.java.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.FlowObjectiveCompositionTree(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.toString(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilter(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateForwardNode(), and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateNext().
FilterTable org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.filterTable protected
Definition at line 37 of file FlowObjectiveCompositionTree.java.
ForwardTable org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.forwardTable protected
Definition at line 38 of file FlowObjectiveCompositionTree.java.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateForwardComposition().
FlowObjectiveCompositionTree org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.leftChild
Definition at line 34 of file FlowObjectiveCompositionTree.java.
NextTable org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.nextTable protected
Definition at line 39 of file FlowObjectiveCompositionTree.java.
FlowObjectiveCompositionManager.PolicyOperator org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.operator
Definition at line 33 of file FlowObjectiveCompositionTree.java.
int org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.priorityAddend protected
Definition at line 42 of file FlowObjectiveCompositionTree.java.
int org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.priorityMultiplier protected
Definition at line 41 of file FlowObjectiveCompositionTree.java.
FlowObjectiveCompositionTree org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.rightChild
Definition at line 35 of file FlowObjectiveCompositionTree.java.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateForwardComposition().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/flowobjective/impl/composition/FlowObjectiveCompositionTree.java