onos: org.onosproject.vtnrsc.DefaultPortChain Class Reference
org.onosproject.vtnrsc.DefaultPortChain Class Reference
Implementation of port chain.
Classes
class Builder
Builder class for Port chain.
Public Member Functions
PortChainId portChainId ()
Returns the ID of this port chain.
TenantId tenantId ()
Returns the tenant id of this port chain.
String name ()
Returns the name of this port chain.
String description ()
Returns the description of this port chain.
List< PortPairGroupId > portPairGroups ()
Returns the list of port pair groups associated with this port chain.
List< FlowClassifierId > flowClassifiers ()
Returns the list of flow classifiers associated with this port chain.
int hashCode ()
boolean equals (Object obj)
boolean exactMatch (PortChain portChain)
Returns whether this port chain is an exact match to the port chain given in the argument.
String toString ()
Static Public Member Functions
static Builder builder ()
To create an instance of the builder.
Detailed Description
Implementation of port chain.
Definition at line 29 of file DefaultPortChain.java.
Member Function Documentation
static Builder org.onosproject.vtnrsc.DefaultPortChain.builder () static
To create an instance of the builder.
Returns
instance of builder
Definition at line 138 of file DefaultPortChain.java.
String org.onosproject.vtnrsc.DefaultPortChain.description ()
Returns the description of this port chain.
Returns
description of port chain
Implements org.onosproject.vtnrsc.PortChain.
Definition at line 77 of file DefaultPortChain.java.
Referenced by org.onosproject.vtnrsc.DefaultPortChain.hashCode().
boolean org.onosproject.vtnrsc.DefaultPortChain.equals (Object obj)
Definition at line 98 of file DefaultPortChain.java.
References create-flow.name, org.onosproject.vtnrsc.DefaultPortChain.name(), and org.onosproject.vtnrsc.DefaultPortChain.portChainId().
boolean org.onosproject.vtnrsc.DefaultPortChain.exactMatch (PortChain portChain)
Returns whether this port chain is an exact match to the port chain given in the argument.
Exact match means the port pair groups and flow classifiers match with the given port chain. It does not consider the port chain id, name and description.
Parameters
portChain other port chain to match against
Returns
true if the port chains are an exact match, otherwise false
Implements org.onosproject.vtnrsc.PortChain.
Definition at line 115 of file DefaultPortChain.java.
References org.onosproject.vtnrsc.PortChain.portChainId(), and org.onosproject.vtnrsc.PortChain.tenantId().
List<FlowClassifierId> org.onosproject.vtnrsc.DefaultPortChain.flowClassifiers ()
Returns the list of flow classifiers associated with this port chain.
Returns
list of flow classifiers
Implements org.onosproject.vtnrsc.PortChain.
Definition at line 87 of file DefaultPortChain.java.
int org.onosproject.vtnrsc.DefaultPortChain.hashCode ()
Definition at line 92 of file DefaultPortChain.java.
References org.onosproject.vtnrsc.DefaultPortChain.description(), org.onosproject.vtnrsc.DefaultPortChain.name(), org.onosproject.vtnrsc.DefaultPortChain.portChainId(), and org.onosproject.vtnrsc.DefaultPortChain.tenantId().
String org.onosproject.vtnrsc.DefaultPortChain.name ()
Returns the name of this port chain.
Returns
name of port chain
Implements org.onosproject.vtnrsc.PortChain.
Definition at line 72 of file DefaultPortChain.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.vtnrsc.DefaultPortChain.equals(), org.onosproject.vtnrsc.DefaultPortChain.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.vtnrsc.DefaultPortChain.toString().
PortChainId org.onosproject.vtnrsc.DefaultPortChain.portChainId ()
Returns the ID of this port chain.
Returns
the port chain id
Implements org.onosproject.vtnrsc.PortChain.
Definition at line 62 of file DefaultPortChain.java.
Referenced by org.onosproject.vtnrsc.DefaultPortChain.equals(), and org.onosproject.vtnrsc.DefaultPortChain.hashCode().
List<PortPairGroupId> org.onosproject.vtnrsc.DefaultPortChain.portPairGroups ()
Returns the list of port pair groups associated with this port chain.
Returns
list of port pair groups
Implements org.onosproject.vtnrsc.PortChain.
Definition at line 82 of file DefaultPortChain.java.
TenantId org.onosproject.vtnrsc.DefaultPortChain.tenantId ()
Returns the tenant id of this port chain.
Returns
the tenant id
Implements org.onosproject.vtnrsc.PortChain.
Definition at line 67 of file DefaultPortChain.java.
Referenced by org.onosproject.vtnrsc.DefaultPortChain.hashCode().
String org.onosproject.vtnrsc.DefaultPortChain.toString ()
Definition at line 122 of file DefaultPortChain.java.
References org.onosproject.vtnrsc.DefaultPortChain.name().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultPortChain.java