onos: org.onosproject.net.packet.DefaultPacketContext Class Reference
org.onosproject.net.packet.DefaultPacketContext Class Reference abstract
Default implementation of a packet context.
Public Member Functions
long time ()
Returns the time when the packet was received.
InboundPacket inPacket ()
Returns the inbound packet being processed.
OutboundPacket outPacket ()
Returns the view of the outbound packet.
Builder treatmentBuilder ()
Returns a builder for constructing traffic treatment.
abstract void send ()
Triggers the outbound packet to be sent.
boolean block ()
Blocks the outbound packet from being sent from this point onward.
boolean isHandled ()
Indicates whether the outbound packet is handled, i.e.
Protected Member Functions
DefaultPacketContext (long time, InboundPacket inPkt, OutboundPacket outPkt, boolean block)
Creates a new packet context.
Detailed Description
Default implementation of a packet context.
Definition at line 30 of file DefaultPacketContext.java.
Constructor & Destructor Documentation
org.onosproject.net.packet.DefaultPacketContext.DefaultPacketContext (long time, InboundPacket inPkt, OutboundPacket outPkt, boolean block) protected
Creates a new packet context.
Parameters
time creation time
inPkt inbound packet
outPkt outbound packet
block whether the context is blocked or not
Definition at line 47 of file DefaultPacketContext.java.
References org.onosproject.net.packet.DefaultPacketContext.time().
Member Function Documentation
boolean org.onosproject.net.packet.DefaultPacketContext.block ()
Blocks the outbound packet from being sent from this point onward.
Returns
whether the outbound packet is blocked.
Implements org.onosproject.net.packet.PacketContext.
Definition at line 85 of file DefaultPacketContext.java.
Referenced by org.onosproject.provider.of.packet.impl.OpenFlowCorePacketContext.send().
InboundPacket org.onosproject.net.packet.DefaultPacketContext.inPacket ()
Returns the inbound packet being processed.
Returns
inbound packet
Implements org.onosproject.net.packet.PacketContext.
Definition at line 64 of file DefaultPacketContext.java.
Referenced by org.onosproject.net.packet.DefaultPacketContextTest.testConstruction().
boolean org.onosproject.net.packet.DefaultPacketContext.isHandled ()
Indicates whether the outbound packet is handled, i.e.
sent or blocked.
Returns
true uf the packed is handled
Implements org.onosproject.net.packet.PacketContext.
Definition at line 91 of file DefaultPacketContext.java.
Referenced by org.onosproject.net.packet.DefaultPacketContextTest.testConstruction().
OutboundPacket org.onosproject.net.packet.DefaultPacketContext.outPacket ()
Returns the view of the outbound packet.
Returns
outbound packet
Implements org.onosproject.net.packet.PacketContext.
Definition at line 70 of file DefaultPacketContext.java.
Referenced by org.onosproject.provider.of.packet.impl.OpenFlowCorePacketContext.send(), and org.onosproject.net.packet.DefaultPacketContextTest.testConstruction().
abstract void org.onosproject.net.packet.DefaultPacketContext.send () pure virtual
Triggers the outbound packet to be sent.
Implements org.onosproject.net.packet.PacketContext.
Implemented in org.onosproject.provider.of.packet.impl.OpenFlowCorePacketContext.
long org.onosproject.net.packet.DefaultPacketContext.time ()
Returns the time when the packet was received.
Returns
the time in millis since start of epoch
Implements org.onosproject.net.packet.PacketContext.
Definition at line 58 of file DefaultPacketContext.java.
Referenced by org.onosproject.net.packet.DefaultPacketContext.DefaultPacketContext().
Builder org.onosproject.net.packet.DefaultPacketContext.treatmentBuilder ()
Returns a builder for constructing traffic treatment.
Returns
traffic treatment builder
Implements org.onosproject.net.packet.PacketContext.
Definition at line 76 of file DefaultPacketContext.java.
Referenced by org.onosproject.net.packet.DefaultPacketContextTest.testConstruction().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/packet/DefaultPacketContext.java