onos: org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv Class Reference
org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv Class Reference
Provides IPv4 TE Router Id Of Remote Node.
Public Member Functions
IPv4TERouterIdOfRemoteNodeTlv (int rawValue)
Constructor to initialize rawValue.
int getInt ()
Returns value of IPv4 TE Router Id Of Remote Node.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static
IPv4TERouterIdOfRemoteNodeTlv of (final int raw)
Returns newly created IPv4TERouterIdOfRemoteNodeTlv object.
static
IPv4TERouterIdOfRemoteNodeTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of IPv4TERouterIdOfRemoteNodeTlv.
Static Public Attributes
static final short TYPE = 1340
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IPv4TERouterIdOfRemoteNodeTlv.class)
Detailed Description
Provides IPv4 TE Router Id Of Remote Node.
Definition at line 30 of file IPv4TERouterIdOfRemoteNodeTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.IPv4TERouterIdOfRemoteNodeTlv (int rawValue)
Constructor to initialize rawValue.
Parameters
rawValue IPv4 TE RouterId Of Remote Node Tlv
Definition at line 54 of file IPv4TERouterIdOfRemoteNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.equals(), and org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.equals (Object obj)
Definition at line 99 of file IPv4TERouterIdOfRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.IPv4TERouterIdOfRemoteNodeTlv().
int org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.getInt ()
Returns value of IPv4 TE Router Id Of Remote Node.
Returns
rawValue IPv4 TE Router Id Of Remote Node
Definition at line 74 of file IPv4TERouterIdOfRemoteNodeTlv.java.
short org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 89 of file IPv4TERouterIdOfRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.LENGTH.
short org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 84 of file IPv4TERouterIdOfRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 79 of file IPv4TERouterIdOfRemoteNodeTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.hashCode ()
Definition at line 94 of file IPv4TERouterIdOfRemoteNodeTlv.java.
static IPv4TERouterIdOfRemoteNodeTlv org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.of (final int raw) static
Returns newly created IPv4TERouterIdOfRemoteNodeTlv object.
Parameters
raw IPv4 TE RouterId Of Remote Node
Returns
object of IPv4TERouterIdOfRemoteNodeTlv
Definition at line 65 of file IPv4TERouterIdOfRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.IPv4TERouterIdOfRemoteNodeTlv().
static IPv4TERouterIdOfRemoteNodeTlv org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of IPv4TERouterIdOfRemoteNodeTlv.
Parameters
c input channel buffer
Returns
object of IPv4TERouterIdOfRemoteNodeTlv
Definition at line 125 of file IPv4TERouterIdOfRemoteNodeTlv.java.
String org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.toString ()
Definition at line 130 of file IPv4TERouterIdOfRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.LENGTH, and org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.TYPE.
int org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 111 of file IPv4TERouterIdOfRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.LENGTH, and org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.LENGTH = 4 static
Definition at line 45 of file IPv4TERouterIdOfRemoteNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.getLength(), org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.toString(), and org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.write().
final Logger org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.log = LoggerFactory.getLogger(IPv4TERouterIdOfRemoteNodeTlv.class) static protected
Definition at line 42 of file IPv4TERouterIdOfRemoteNodeTlv.java.
final short org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.TYPE = 1340 static
Definition at line 44 of file IPv4TERouterIdOfRemoteNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.getType(), org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.toString(), and org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IPv4TERouterIdOfRemoteNodeTlv.java