onos: org.onosproject.routing.config.LocalIpPrefixEntry Class Reference
org.onosproject.routing.config.LocalIpPrefixEntry Class Reference
Configuration details for an IP prefix entry.
Classes
enum IpPrefixType
Specifies the type of local IP prefix.
Public Member Functions
LocalIpPrefixEntry (@JsonProperty("ipPrefix") String ipPrefix,@JsonProperty("type") IpPrefixType type,@JsonProperty("gatewayIp") IpAddress gatewayIpAddress)
Creates a new IP prefix entry.
IpPrefix ipPrefix ()
Gets the IP prefix of the IP prefix entry.
IpPrefixType ipPrefixType ()
Gets the IP prefix type of the IP prefix entry.
IpAddress getGatewayIpAddress ()
Gets the gateway IP address of the IP prefix entry.
boolean isIp4 ()
Tests whether the IP version of this entry is IPv4.
boolean isIp6 ()
Tests whether the IP version of this entry is IPv6.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Configuration details for an IP prefix entry.
Definition at line 29 of file LocalIpPrefixEntry.java.
Constructor & Destructor Documentation
org.onosproject.routing.config.LocalIpPrefixEntry.LocalIpPrefixEntry (@JsonProperty("ipPrefix") String ipPrefix, @JsonProperty("type") IpPrefixType type, @JsonProperty("gatewayIp") IpAddress gatewayIpAddress)
Creates a new IP prefix entry.
Parameters
ipPrefix an IP prefix as a String
type an IP prefix type as an IpPrefixType
gatewayIpAddress IP of the gateway
Definition at line 60 of file LocalIpPrefixEntry.java.
References org.onosproject.routing.config.LocalIpPrefixEntry.ipPrefix().
Referenced by org.onosproject.routing.config.LocalIpPrefixEntry.equals().
Member Function Documentation
boolean org.onosproject.routing.config.LocalIpPrefixEntry.equals (Object obj)
Definition at line 120 of file LocalIpPrefixEntry.java.
References org.onosproject.routing.config.LocalIpPrefixEntry.LocalIpPrefixEntry().
IpAddress org.onosproject.routing.config.LocalIpPrefixEntry.getGatewayIpAddress ()
Gets the gateway IP address of the IP prefix entry.
Returns
the gateway IP address
Definition at line 92 of file LocalIpPrefixEntry.java.
int org.onosproject.routing.config.LocalIpPrefixEntry.hashCode ()
Definition at line 115 of file LocalIpPrefixEntry.java.
References org.onosproject.routing.config.LocalIpPrefixEntry.ipPrefix().
IpPrefix org.onosproject.routing.config.LocalIpPrefixEntry.ipPrefix ()
Gets the IP prefix of the IP prefix entry.
Returns
the IP prefix
Definition at line 74 of file LocalIpPrefixEntry.java.
Referenced by org.onosproject.routing.config.LocalIpPrefixEntry.hashCode(), and org.onosproject.routing.config.LocalIpPrefixEntry.LocalIpPrefixEntry().
IpPrefixType org.onosproject.routing.config.LocalIpPrefixEntry.ipPrefixType ()
Gets the IP prefix type of the IP prefix entry.
Returns
the IP prefix type
Definition at line 83 of file LocalIpPrefixEntry.java.
boolean org.onosproject.routing.config.LocalIpPrefixEntry.isIp4 ()
Tests whether the IP version of this entry is IPv4.
Returns
true if the IP version of this entry is IPv4, otherwise false.
Definition at line 101 of file LocalIpPrefixEntry.java.
boolean org.onosproject.routing.config.LocalIpPrefixEntry.isIp6 ()
Tests whether the IP version of this entry is IPv6.
Returns
true if the IP version of this entry is IPv6, otherwise false.
Definition at line 110 of file LocalIpPrefixEntry.java.
String org.onosproject.routing.config.LocalIpPrefixEntry.toString ()
Definition at line 135 of file LocalIpPrefixEntry.java.
The documentation for this class was generated from the following file:
apps/routing-api/src/main/java/org/onosproject/routing/config/LocalIpPrefixEntry.java