onos: org.onosproject.rest.FlowsResourceTest Class Reference
org.onosproject.rest.FlowsResourceTest Class Reference
Unit tests for Flows REST APIs.
Classes
class FlowJsonArrayMatcher
Hamcrest matcher to check that a flow is represented properly in a JSON array of flows.
class FlowJsonMatcher
Hamcrest matcher to check that a flow representation in JSON matches the actual flow entry.
Public Member Functions
void setUpTest ()
Sets up the global values for all the tests.
void tearDownTest ()
Cleans up and verifies the mocks.
void testFlowsEmptyArray ()
Tests the result of the rest api GET when there are no flows.
void testFlowsPopulatedArray ()
Tests the result of the rest api GET when there are active flows.
void testFlowsSingleDevice ()
Tests the result of a rest api GET for a device.
void testFlowsSingleDeviceWithFlowId ()
Tests the result of a rest api GET for a device.
void testBadGet ()
Tests that a fetch of a non-existent device object throws an exception.
void testPost ()
Tests creating a flow with POST.
void testDelete ()
Tests deleting a flow.
Public Member Functions inherited from org.onosproject.rest.ResourceTest
int getPort (int defaultPort)
Assigns an available port for the test.
AppDescriptor configure ()
Detailed Description
Unit tests for Flows REST APIs.
Definition at line 85 of file FlowsResourceTest.java.
Member Function Documentation
void org.onosproject.rest.FlowsResourceTest.setUpTest ()
Sets up the global values for all the tests.
Definition at line 258 of file FlowsResourceTest.java.
References org.onosproject.net.NetTestTools.APP_ID, org.onosproject.core.CoreService.getAppId(), org.onosproject.net.device.DeviceService.getDevice(), org.onosproject.net.device.DeviceService.getDevices(), org.onosproject.core.CoreService.registerApplication(), and org.onosproject.codec.impl.FlowRuleCodec.REST_APP_ID.
void org.onosproject.rest.FlowsResourceTest.tearDownTest ()
Cleans up and verifies the mocks.
Definition at line 291 of file FlowsResourceTest.java.
void org.onosproject.rest.FlowsResourceTest.testBadGet ()
Tests that a fetch of a non-existent device object throws an exception.
Definition at line 558 of file FlowsResourceTest.java.
References org.onosproject.net.flow.FlowRuleService.getFlowEntries().
void org.onosproject.rest.FlowsResourceTest.testDelete ()
Tests deleting a flow.
Definition at line 603 of file FlowsResourceTest.java.
References create-flow.location.
void org.onosproject.rest.FlowsResourceTest.testFlowsEmptyArray ()
Tests the result of the rest api GET when there are no flows.
Definition at line 466 of file FlowsResourceTest.java.
References org.onosproject.net.flow.FlowRuleService.getFlowEntries().
void org.onosproject.rest.FlowsResourceTest.testFlowsPopulatedArray ()
Tests the result of the rest api GET when there are active flows.
Definition at line 482 of file FlowsResourceTest.java.
void org.onosproject.rest.FlowsResourceTest.testFlowsSingleDevice ()
Tests the result of a rest api GET for a device.
Definition at line 505 of file FlowsResourceTest.java.
References org.onosproject.net.flow.FlowRuleService.getFlowEntries().
void org.onosproject.rest.FlowsResourceTest.testFlowsSingleDeviceWithFlowId ()
Tests the result of a rest api GET for a device.
Definition at line 531 of file FlowsResourceTest.java.
References org.onosproject.net.flow.FlowRuleService.getFlowEntries().
void org.onosproject.rest.FlowsResourceTest.testPost ()
Tests creating a flow with POST.
Definition at line 580 of file FlowsResourceTest.java.
References create-flow.location.
The documentation for this class was generated from the following file:
web/api/src/test/java/org/onosproject/rest/FlowsResourceTest.java