onos: org.onosproject.pim.impl.PIMInterface Class Reference
org.onosproject.pim.impl.PIMInterface Class Reference
The PIM Interface is a wrapper around a ConnectPoint and used to provide hello options values when "talking" with PIM other PIM routers.
Public Member Functions
PIMInterface (Interface intf)
Create a PIMInterface.
Interface getInterface ()
Get the PIM Interface.
IpAddress getIpAddress ()
Getter for our IP address.
int getPriority ()
Get our priority.
PIMNeighbor getDesignatedRouter ()
Get the designated router on this connection.
boolean areWeDr ()
Are we the DR on this CP?
Collection< PIMNeighbor > getNeighbors ()
Return a collection of PIM Neighbors.
PIMNeighbor findNeighbor (IpAddress ipaddr)
Find the neighbor with the given IP address on this CP.
void addNeighbor (PIMNeighbor nbr)
Add a new PIM neighbor to this list.
void removeNeighbor (IpAddress ipaddr)
Remove the neighbor from our neighbor list.
void removeNeighbor (PIMNeighbor nbr)
Remove the given neighbor from the neighbor list.
PIMNeighbor electDR ()
Elect a new DR on this ConnectPoint.
PIMNeighbor electDR (PIMNeighbor nbr)
Elect a new DR given the new neighbor.
PIMNeighbor findOrCreate (IpAddress ipaddr, MacAddress mac)
Find or create a pim neighbor with a given ip address and connect point.
void processHello (Ethernet ethPkt, ConnectPoint cp)
Process a hello packet received on this Interface.
void sendHello ()
Send a hello packet from this interface.
String printNeighbors ()
prints the connectPointNeighbors list with each neighbor list.
String toString ()
Detailed Description
The PIM Interface is a wrapper around a ConnectPoint and used to provide hello options values when "talking" with PIM other PIM routers.
Definition at line 42 of file PIMInterface.java.
Constructor & Destructor Documentation
org.onosproject.pim.impl.PIMInterface.PIMInterface (Interface intf)
Create a PIMInterface.
Parameters
intf the network interface configuration
Definition at line 71 of file PIMInterface.java.
References org.onosproject.pim.impl.PIMInterface.sendHello().
Member Function Documentation
void org.onosproject.pim.impl.PIMInterface.addNeighbor (PIMNeighbor nbr)
Add a new PIM neighbor to this list.
Parameters
nbr the neighbor to be added.
Definition at line 161 of file PIMInterface.java.
References org.onosproject.pim.impl.PIMNeighbor.getPrimaryAddr().
boolean org.onosproject.pim.impl.PIMInterface.areWeDr ()
Are we the DR on this CP?
Returns
true if we are, false if not
Definition at line 131 of file PIMInterface.java.
References org.onosproject.pim.impl.PIMNeighbor.getPrimaryAddr().
PIMNeighbor org.onosproject.pim.impl.PIMInterface.electDR ()
Elect a new DR on this ConnectPoint.
Returns
the PIM Neighbor that wins
Definition at line 199 of file PIMInterface.java.
References org.onosproject.pim.impl.PIMNeighbor.getPrimaryAddr().
PIMNeighbor org.onosproject.pim.impl.PIMInterface.electDR (PIMNeighbor nbr)
Elect a new DR given the new neighbor.
Parameters
nbr the new neighbor to use in DR election.
Returns
the PIM Neighbor that wins DR election
Definition at line 228 of file PIMInterface.java.
References org.onosproject.pim.impl.PIMNeighbor.getPrimaryAddr(), and org.onosproject.pim.impl.PIMNeighbor.getPriority().
PIMNeighbor org.onosproject.pim.impl.PIMInterface.findNeighbor (IpAddress ipaddr)
Find the neighbor with the given IP address on this CP.
Parameters
ipaddr the IP address of the neighbor we are interested in
Returns
the pim neighbor if it exists
Definition at line 151 of file PIMInterface.java.
PIMNeighbor org.onosproject.pim.impl.PIMInterface.findOrCreate (IpAddress ipaddr, MacAddress mac)
Find or create a pim neighbor with a given ip address and connect point.
Parameters
ipaddr of the pim neighbor
mac The mac address of our sending neighbor
Returns
an existing or new PIM neighbor
Definition at line 246 of file PIMInterface.java.
PIMNeighbor org.onosproject.pim.impl.PIMInterface.getDesignatedRouter ()
Get the designated router on this connection.
Returns
the PIMNeighbor representing the DR
Definition at line 122 of file PIMInterface.java.
Referenced by org.onosproject.pim.impl.PIMNeighbor.refresh().
Interface org.onosproject.pim.impl.PIMInterface.getInterface ()
Get the PIM Interface.
Returns
the PIM Interface
Definition at line 85 of file PIMInterface.java.
IpAddress org.onosproject.pim.impl.PIMInterface.getIpAddress ()
Getter for our IP address.
Returns
our IP address.
Definition at line 94 of file PIMInterface.java.
Referenced by org.onosproject.pim.impl.PIMPacketHandler.sendPacket().
Collection<PIMNeighbor> org.onosproject.pim.impl.PIMInterface.getNeighbors ()
Return a collection of PIM Neighbors.
Returns
the collection of PIM Neighbors
Definition at line 141 of file PIMInterface.java.
int org.onosproject.pim.impl.PIMInterface.getPriority ()
Get our priority.
Returns
our priority.
Definition at line 113 of file PIMInterface.java.
String org.onosproject.pim.impl.PIMInterface.printNeighbors ()
prints the connectPointNeighbors list with each neighbor list.
Returns
string of neighbors.
Definition at line 319 of file PIMInterface.java.
void org.onosproject.pim.impl.PIMInterface.processHello (Ethernet ethPkt, ConnectPoint cp)
Process a hello packet received on this Interface.
Parameters
ethPkt the ethernet packet containing the hello message
cp the ConnectPoint of this interface
Definition at line 262 of file PIMInterface.java.
References org.onosproject.net.ConnectPoint.equals(), org.onlab.packet.BasePacket.getPayload(), and org.onosproject.pim.impl.PIMInterface.toString().
void org.onosproject.pim.impl.PIMInterface.removeNeighbor (IpAddress ipaddr)
Remove the neighbor from our neighbor list.
Parameters
ipaddr the IP address of the neighbor to remove
Definition at line 175 of file PIMInterface.java.
void org.onosproject.pim.impl.PIMInterface.removeNeighbor (PIMNeighbor nbr)
Remove the given neighbor from the neighbor list.
Parameters
nbr the nbr to be removed.
Definition at line 188 of file PIMInterface.java.
void org.onosproject.pim.impl.PIMInterface.sendHello ()
Send a hello packet from this interface.
Definition at line 295 of file PIMInterface.java.
References org.onlab.packet.PIM.TYPE_HELLO.
Referenced by org.onosproject.pim.impl.PIMInterface.PIMInterface().
String org.onosproject.pim.impl.PIMInterface.toString ()
Definition at line 328 of file PIMInterface.java.
Referenced by org.onosproject.pim.impl.PIMInterface.processHello().
The documentation for this class was generated from the following file:
apps/pim/src/main/java/org/onosproject/pim/impl/PIMInterface.java