onos: org.onosproject.security.SecurityUtil Class Reference
org.onosproject.security.SecurityUtil Class Reference
Utility class to aid Security-Mode ONOS.
Static Public Member Functions
static boolean isSecurityModeEnabled ()
static SecurityAdminService getSecurityService ()
static boolean isAppSecured (ApplicationId appId)
static void register (ApplicationId appId)
Static Protected Attributes
static ServiceDirectory serviceDirectory = new DefaultServiceDirectory()
Detailed Description
Utility class to aid Security-Mode ONOS.
Definition at line 29 of file SecurityUtil.java.
Member Function Documentation
static SecurityAdminService org.onosproject.security.SecurityUtil.getSecurityService () static
Definition at line 50 of file SecurityUtil.java.
Referenced by org.onosproject.security.SecurityUtil.isAppSecured(), and org.onosproject.security.SecurityUtil.register().
static boolean org.onosproject.security.SecurityUtil.isAppSecured (ApplicationId appId) static
Definition at line 64 of file SecurityUtil.java.
References org.onosproject.security.SecurityUtil.getSecurityService(), and org.onosproject.security.SecurityAdminService.isSecured().
Referenced by org.onosproject.app.impl.ApplicationManager.activate().
static boolean org.onosproject.security.SecurityUtil.isSecurityModeEnabled () static
Definition at line 36 of file SecurityUtil.java.
static void org.onosproject.security.SecurityUtil.register (ApplicationId appId) static
Definition at line 78 of file SecurityUtil.java.
References org.onosproject.security.SecurityUtil.getSecurityService().
Member Data Documentation
ServiceDirectory org.onosproject.security.SecurityUtil.serviceDirectory = new DefaultServiceDirectory() static protected
Definition at line 31 of file SecurityUtil.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/security/SecurityUtil.java