onos: org.onosproject.vtnweb.resources.FlowClassifierResourceTest Class Reference
org.onosproject.vtnweb.resources.FlowClassifierResourceTest Class Reference
Unit tests for flow classifier REST APIs.
Public Member Functions
void setUpTest ()
Sets up the global values for all the tests.
void tearDownTest ()
Cleans up.
void testFlowClassifiersEmpty ()
Tests the result of the rest api GET when there are no flow classifiers.
void testGetFlowClassifierId ()
Tests the result of a rest api GET for flow classifier id.
void testBadGet ()
Tests that a fetch of a non-existent flow classifier object throws an exception.
void testPost ()
Tests creating a flow classifier with POST.
void testDelete ()
Tests deleting a flow classifier.
Public Member Functions inherited from org.onosproject.vtnweb.resources.VtnResourceTest
int getPort (int defaultPort)
Assigns an available port for the test.
AppDescriptor configure ()
Detailed Description
Unit tests for flow classifier REST APIs.
Definition at line 56 of file FlowClassifierResourceTest.java.
Member Function Documentation
void org.onosproject.vtnweb.resources.FlowClassifierResourceTest.setUpTest ()
Sets up the global values for all the tests.
Definition at line 194 of file FlowClassifierResourceTest.java.
void org.onosproject.vtnweb.resources.FlowClassifierResourceTest.tearDownTest ()
Cleans up.
Definition at line 205 of file FlowClassifierResourceTest.java.
void org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testBadGet ()
Tests that a fetch of a non-existent flow classifier object throws an exception.
Definition at line 244 of file FlowClassifierResourceTest.java.
References org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.getFlowClassifier().
void org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testDelete ()
Tests deleting a flow classifier.
Definition at line 281 of file FlowClassifierResourceTest.java.
References create-flow.location, and org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.removeFlowClassifier().
void org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testFlowClassifiersEmpty ()
Tests the result of the rest api GET when there are no flow classifiers.
Definition at line 212 of file FlowClassifierResourceTest.java.
References org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.getFlowClassifiers().
void org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testGetFlowClassifierId ()
Tests the result of a rest api GET for flow classifier id.
Definition at line 225 of file FlowClassifierResourceTest.java.
References org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.exists(), and org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.getFlowClassifier().
void org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testPost ()
Tests creating a flow classifier with POST.
Definition at line 262 of file FlowClassifierResourceTest.java.
References org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.createFlowClassifier().
The documentation for this class was generated from the following file:
apps/vtn/vtnweb/src/test/java/org/onosproject/vtnweb/resources/FlowClassifierResourceTest.java