onos: org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv Class Reference
org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv Class Reference
Provides FourOctetAsNumCapabilityTlv Capability Tlv.
Public Member Functions
FourOctetAsNumCapabilityTlv (int rawValue)
constructor to initialize rawValue.
int getInt ()
Returns value of TLV.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static FourOctetAsNumCapabilityTlv of (final int raw)
constructor to initialize raw.
static FourOctetAsNumCapabilityTlv read (ChannelBuffer cb)
Reads the channel buffer and returns object of FourOctetAsNumCapabilityTlv.
Static Public Attributes
static final byte TYPE = 65
static final byte LENGTH = 4
Static Protected Attributes
static final Logger log
support to indicate its support for four-octet AS numbers -CAPABILITY TLV format.
Detailed Description
Provides FourOctetAsNumCapabilityTlv Capability Tlv.
Definition at line 29 of file FourOctetAsNumCapabilityTlv.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.FourOctetAsNumCapabilityTlv (int rawValue)
constructor to initialize rawValue.
Parameters
rawValue FourOctetAsNumCapabilityTlv
Definition at line 46 of file FourOctetAsNumCapabilityTlv.java.
Referenced by org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.equals(), and org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.of().
Member Function Documentation
int org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 116 of file FourOctetAsNumCapabilityTlv.java.
boolean org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.equals (Object obj)
Definition at line 78 of file FourOctetAsNumCapabilityTlv.java.
References org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.FourOctetAsNumCapabilityTlv().
int org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.getInt ()
Returns value of TLV.
Returns
int value of rawValue
Definition at line 63 of file FourOctetAsNumCapabilityTlv.java.
short org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 68 of file FourOctetAsNumCapabilityTlv.java.
References org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.TYPE.
int org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.hashCode ()
Definition at line 73 of file FourOctetAsNumCapabilityTlv.java.
static FourOctetAsNumCapabilityTlv org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.of (final int raw) static
constructor to initialize raw.
Parameters
raw AS number
Returns
object of FourOctetAsNumCapabilityTlv
Definition at line 55 of file FourOctetAsNumCapabilityTlv.java.
References org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.FourOctetAsNumCapabilityTlv().
static FourOctetAsNumCapabilityTlv org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.read (ChannelBuffer cb) static
Reads the channel buffer and returns object of FourOctetAsNumCapabilityTlv.
Parameters
cb type of channel buffer
Returns
object of FourOctetAsNumCapabilityTlv
Definition at line 103 of file FourOctetAsNumCapabilityTlv.java.
String org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.toString ()
Definition at line 108 of file FourOctetAsNumCapabilityTlv.java.
References org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.LENGTH, and org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.TYPE.
int org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 90 of file FourOctetAsNumCapabilityTlv.java.
References org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.LENGTH, and org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.TYPE.
Member Data Documentation
final byte org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.LENGTH = 4 static
Definition at line 38 of file FourOctetAsNumCapabilityTlv.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpOpenMsgVer4.parseCapabilityTlv(), org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.toString(), and org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.write().
final Logger org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.log static protected
Initial value:
= LoggerFactory
            .getLogger(FourOctetAsNumCapabilityTlv.class)
support to indicate its support for four-octet AS numbers -CAPABILITY TLV format.
Definition at line 34 of file FourOctetAsNumCapabilityTlv.java.
final byte org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.TYPE = 65 static
Definition at line 37 of file FourOctetAsNumCapabilityTlv.java.
Referenced by org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.getType(), org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.toString(), and org.onosproject.bgpio.types.FourOctetAsNumCapabilityTlv.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/FourOctetAsNumCapabilityTlv.java