onos: org.onosproject.ui.JsonUtils Class Reference
org.onosproject.ui.JsonUtils Class Reference
Provides convenience methods for dealing with JSON nodes, arrays etc.
Static Public Member Functions
static ObjectNode envelope (String type, long sid, ObjectNode payload)
Wraps a message payload into an event structure for the given event type and sequence ID.
static ObjectNode envelope (String type, ObjectNode payload)
Composes a message structure for the given message type and payload.
static String eventType (ObjectNode event)
Returns the event type from the specified event.
static long sid (ObjectNode event)
Returns the sequence identifier from the specified event, or 0 (zero) if the "sid" property does not exist.
static ObjectNode payload (ObjectNode event)
Returns the payload from the specified event.
static long number (ObjectNode node, String name)
Returns the specified node property as a number.
static String string (ObjectNode node, String name)
Returns the specified node property as a string.
static String string (ObjectNode node, String name, String defaultValue)
Returns the specified node property as a string, with a default fallback.
static ObjectNode node (ObjectNode node, String name)
Returns the specified node property as an object node.
Detailed Description
Provides convenience methods for dealing with JSON nodes, arrays etc.
Definition at line 25 of file JsonUtils.java.
Member Function Documentation
static ObjectNode org.onosproject.ui.JsonUtils.envelope (String type, long sid, ObjectNode payload) static
Wraps a message payload into an event structure for the given event type and sequence ID.
Generally, the sequence ID should be a copy of the ID from the client request event.
Parameters
type event type
sid sequence ID
payload event payload
Returns
the object node representation
Definition at line 42 of file JsonUtils.java.
References org.onosproject.ui.JsonUtils.payload(), and org.onosproject.ui.JsonUtils.sid().
static ObjectNode org.onosproject.ui.JsonUtils.envelope (String type, ObjectNode payload) static
Composes a message structure for the given message type and payload.
Parameters
type message type
payload message payload
Returns
the object node representation
Definition at line 59 of file JsonUtils.java.
References org.onosproject.ui.JsonUtils.payload().
static String org.onosproject.ui.JsonUtils.eventType (ObjectNode event) static
Returns the event type from the specified event.
If the node does not have an "event" property, "unknown" is returned.
Parameters
event message event
Returns
extracted event type
Definition at line 73 of file JsonUtils.java.
References org.onosproject.ui.JsonUtils.string().
static ObjectNode org.onosproject.ui.JsonUtils.node (ObjectNode node, String name) static
Returns the specified node property as an object node.
Parameters
node object node
name property name
Returns
property as a node
Definition at line 139 of file JsonUtils.java.
References create-flow.name.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.updateMetaUi().
static long org.onosproject.ui.JsonUtils.number (ObjectNode node, String name) static
Returns the specified node property as a number.
Parameters
node message event
name property name
Returns
property as number
Definition at line 105 of file JsonUtils.java.
References create-flow.name.
Referenced by org.onosproject.ui.JsonUtils.sid().
static ObjectNode org.onosproject.ui.JsonUtils.payload (ObjectNode event) static
Returns the payload from the specified event.
Parameters
event message event
Returns
extracted payload object
Definition at line 94 of file JsonUtils.java.
Referenced by org.onosproject.ui.JsonUtils.envelope().
static long org.onosproject.ui.JsonUtils.sid (ObjectNode event) static
Returns the sequence identifier from the specified event, or 0 (zero) if the "sid" property does not exist.
Parameters
event message event
Returns
extracted sequence identifier
Definition at line 84 of file JsonUtils.java.
References org.onosproject.ui.JsonUtils.number().
Referenced by org.onosproject.ui.JsonUtils.envelope().
static String org.onosproject.ui.JsonUtils.string (ObjectNode node, String name) static
Returns the specified node property as a string.
Parameters
node message event
name property name
Returns
property as a string
Definition at line 116 of file JsonUtils.java.
References create-flow.name.
Referenced by org.onosproject.ui.JsonUtils.eventType().
static String org.onosproject.ui.JsonUtils.string (ObjectNode node, String name, String defaultValue) static
Returns the specified node property as a string, with a default fallback.
Parameters
node object node
name property name
defaultValue fallback value if property is absent
Returns
property as a string
Definition at line 128 of file JsonUtils.java.
References create-flow.name.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/JsonUtils.java