onos: org.onosproject.pcepio.types.NodeNameTlv Class Reference
org.onosproject.pcepio.types.NodeNameTlv Class Reference
Provide the name for the node.
Public Member Functions
NodeNameTlv (byte[] rawValue, short hLength)
constructor to initialize rawValue.
byte[] getValue ()
Returns RawValue for NodeName.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static NodeNameTlv of (final byte[] raw, short hLength)
Returns newly created NodeNameTlv object.
static PcepValueType read (ChannelBuffer c, short hLength)
Reads the channel buffer and returns object of NodeNameTlv.
Public Attributes
final short hLength
Static Public Attributes
static final short TYPE = 1007
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(NodeNameTlv.class)
Detailed Description
Provide the name for the node.
Definition at line 30 of file NodeNameTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.NodeNameTlv.NodeNameTlv (byte[] rawValue, short hLength)
constructor to initialize rawValue.
Parameters
rawValue of Node Name
hLength length
Definition at line 55 of file NodeNameTlv.java.
References org.onosproject.pcepio.types.NodeNameTlv.hLength.
Referenced by org.onosproject.pcepio.types.NodeNameTlv.equals(), org.onosproject.pcepio.types.NodeNameTlv.of(), and org.onosproject.pcepio.types.NodeNameTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.NodeNameTlv.equals (Object obj)
Definition at line 106 of file NodeNameTlv.java.
References org.onosproject.pcepio.types.NodeNameTlv.NodeNameTlv().
short org.onosproject.pcepio.types.NodeNameTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 96 of file NodeNameTlv.java.
References org.onosproject.pcepio.types.NodeNameTlv.hLength.
short org.onosproject.pcepio.types.NodeNameTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 91 of file NodeNameTlv.java.
References org.onosproject.pcepio.types.NodeNameTlv.TYPE.
byte [] org.onosproject.pcepio.types.NodeNameTlv.getValue ()
Returns RawValue for NodeName.
Returns
rawValue raw value
Definition at line 81 of file NodeNameTlv.java.
PcepVersion org.onosproject.pcepio.types.NodeNameTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 86 of file NodeNameTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.NodeNameTlv.hashCode ()
Definition at line 101 of file NodeNameTlv.java.
static NodeNameTlv org.onosproject.pcepio.types.NodeNameTlv.of (final byte[] raw, short hLength) static
Returns newly created NodeNameTlv object.
Parameters
raw of NodeName
hLength length
Returns
new object of Node Name Tlv
Definition at line 72 of file NodeNameTlv.java.
References org.onosproject.pcepio.types.NodeNameTlv.NodeNameTlv().
static PcepValueType org.onosproject.pcepio.types.NodeNameTlv.read (ChannelBuffer c, short hLength) static
Reads the channel buffer and returns object of NodeNameTlv.
Parameters
c input channel buffer
hLength length
Returns
object of Node Name TLV
Definition at line 133 of file NodeNameTlv.java.
References org.onosproject.pcepio.types.NodeNameTlv.hLength, and org.onosproject.pcepio.types.NodeNameTlv.NodeNameTlv().
String org.onosproject.pcepio.types.NodeNameTlv.toString ()
Definition at line 140 of file NodeNameTlv.java.
References org.onosproject.pcepio.types.NodeNameTlv.hLength, and org.onosproject.pcepio.types.NodeNameTlv.TYPE.
int org.onosproject.pcepio.types.NodeNameTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 118 of file NodeNameTlv.java.
References org.onosproject.pcepio.types.NodeNameTlv.hLength, and org.onosproject.pcepio.types.NodeNameTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.NodeNameTlv.hLength
Definition at line 45 of file NodeNameTlv.java.
Referenced by org.onosproject.pcepio.types.NodeNameTlv.getLength(), org.onosproject.pcepio.types.NodeNameTlv.NodeNameTlv(), org.onosproject.pcepio.types.NodeNameTlv.read(), org.onosproject.pcepio.types.NodeNameTlv.toString(), and org.onosproject.pcepio.types.NodeNameTlv.write().
final Logger org.onosproject.pcepio.types.NodeNameTlv.log = LoggerFactory.getLogger(NodeNameTlv.class) static protected
Definition at line 42 of file NodeNameTlv.java.
final short org.onosproject.pcepio.types.NodeNameTlv.TYPE = 1007 static
Definition at line 44 of file NodeNameTlv.java.
Referenced by org.onosproject.pcepio.types.NodeNameTlv.getType(), org.onosproject.pcepio.types.NodeNameTlv.toString(), and org.onosproject.pcepio.types.NodeNameTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/NodeNameTlv.java