onos: org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData Class Reference
org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData Class Reference
To store all tunnel related information from Core and Path computation client.
Public Member Functions
PcepTunnelData ()
Default constructor.
PcepTunnelData (Tunnel tunnel, Path path, RequestType requestType)
Constructor to initialize Tunnel, Path and Request type.
PcepTunnelData (ElementId elementId, Tunnel tunnel, Path path, RequestType requestType)
Constructor to initialize ElemendId, Tunnel, Path and Request type.
PcepTunnelData (Tunnel tunnel, RequestType requestType)
Constructor to initialize Tunnel and Request type.
PcepTunnelData (ElementId elementId, Tunnel tunnel, RequestType requestType)
Constructor to initialize ElementId, Tunnel and Request type.
void setElementId (ElementId elementId)
Sets ip element id.
void setTunnel (Tunnel tunnel)
Sets tunnel.
void setPath (Path path)
Sets Path.
void setRequestType (RequestType requestType)
Request type for tunnel.
void setPlspId (int plspId)
Sets plspid generated from pcc.
void setLspAFlag (boolean value)
Sets A flag from lsp object.
void setLspOFlag (byte value)
Sets OF flag from lsp object.
void setTunnelId (short value)
Sets tunnel id from PCC.
void setExtTunnelId (int value)
Sets extended tunnel id from PCC.
void setLspId (short value)
Sets lsp id from pcc.
void setStatefulIpv4IndentifierTlv (StatefulIPv4LspIdentidiersTlv value)
Sets statefulIpv4Identifiers tlv.
void setRptFlag (boolean rptFlag)
Sets report flag.
void setLspDFlag (boolean value)
Sets D flag from lsp object.
ElementId elementId ()
To get Ip element id.
Tunnel tunnel ()
To get Tunnel.
Path path ()
To get Path.
RequestType requestType ()
To get request type.
int plspId ()
To get pLspId.
boolean lspAFlag ()
To get A flag.
byte lspOFlag ()
To get OF flag.
short tunnelId ()
To get tunnel id.
int extTunnelId ()
To get extended tunnel id.
short lspId ()
To get pLspId.
boolean lspDFlag ()
To get D Flag.
StatefulIPv4LspIdentidiersTlv statefulIpv4IndentifierTlv ()
To get statefulIpv4Indentifier tlv.
boolean rptFlag ()
To get report flag.
boolean equals (Object obj)
int hashCode ()
String toString ()
Detailed Description
To store all tunnel related information from Core and Path computation client.
Definition at line 30 of file PcepTunnelData.java.
Constructor & Destructor Documentation
org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.PcepTunnelData ()
Default constructor.
Definition at line 51 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals().
org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.PcepTunnelData (Tunnel tunnel, Path path, RequestType requestType)
Constructor to initialize Tunnel, Path and Request type.
Parameters
tunnel mpls tunnel
path Path in network
requestType request type for tunnel
Definition at line 67 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.path(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.requestType(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnel().
org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.PcepTunnelData (ElementId elementId, Tunnel tunnel, Path path, RequestType requestType)
Constructor to initialize ElemendId, Tunnel, Path and Request type.
Parameters
elementId Ip element id
tunnel mpls tunnel
path Path in network
requestType request type for tunnel
Definition at line 81 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.elementId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.path(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.requestType(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnel().
org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.PcepTunnelData (Tunnel tunnel, RequestType requestType)
Constructor to initialize Tunnel and Request type.
Parameters
tunnel Tunnel from core
requestType request type for tunnel
Definition at line 94 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.requestType(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnel().
org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.PcepTunnelData (ElementId elementId, Tunnel tunnel, RequestType requestType)
Constructor to initialize ElementId, Tunnel and Request type.
Parameters
elementId Ip element id
tunnel mpls tunnel
requestType request type for tunnel
Definition at line 106 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.elementId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.requestType(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnel().
Member Function Documentation
ElementId org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.elementId ()
To get Ip element id.
Returns
Ip elemend id
Definition at line 233 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.PcepTunnelData(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setElementId(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
boolean org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals (Object obj)
Definition at line 346 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.elementId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.extTunnelId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspAFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspDFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspOFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.path(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.PcepTunnelData(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.plspId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.requestType(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.rptFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.statefulIpv4IndentifierTlv(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnel(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnelId().
int org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.extTunnelId ()
To get extended tunnel id.
Returns
extended tunnel id
Definition at line 305 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
int org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode ()
Definition at line 372 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.elementId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.extTunnelId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspAFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspDFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspOFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.path(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.plspId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.requestType(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.rptFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.statefulIpv4IndentifierTlv(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnel(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnelId().
boolean org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspAFlag ()
To get A flag.
Returns
A flag
Definition at line 278 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
boolean org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspDFlag ()
To get D Flag.
Returns
d flag
Definition at line 323 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
short org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspId ()
To get pLspId.
Returns
pLspId
Definition at line 314 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
byte org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspOFlag ()
To get OF flag.
Returns
OF flag
Definition at line 287 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
Path org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.path ()
To get Path.
Returns
path
Definition at line 251 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.PcepTunnelData(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setPath(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
int org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.plspId ()
To get pLspId.
Returns
pLspId
Definition at line 269 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setPlspId(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
RequestType org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.requestType ()
To get request type.
Returns
request type
Definition at line 260 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.PcepTunnelData(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setRequestType(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
boolean org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.rptFlag ()
To get report flag.
Returns
report flag
Definition at line 341 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setRptFlag(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setElementId (ElementId elementId)
Sets ip element id.
Parameters
elementId Ip element id
Definition at line 117 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.elementId().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setExtTunnelId (int value)
Sets extended tunnel id from PCC.
Parameters
value extended tunnel id value
Definition at line 189 of file PcepTunnelData.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setLspAFlag (boolean value)
Sets A flag from lsp object.
Parameters
value A flag value
Definition at line 162 of file PcepTunnelData.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setLspDFlag (boolean value)
Sets D flag from lsp object.
Parameters
value D flag value
Definition at line 224 of file PcepTunnelData.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setLspId (short value)
Sets lsp id from pcc.
Parameters
value lsp id
Definition at line 198 of file PcepTunnelData.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setLspOFlag (byte value)
Sets OF flag from lsp object.
Parameters
value OF flag value
Definition at line 171 of file PcepTunnelData.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setPath (Path path)
Sets Path.
Parameters
path Path in network
Definition at line 135 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.path().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setPlspId (int plspId)
Sets plspid generated from pcc.
Parameters
plspId plsp identifier
Definition at line 153 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.plspId().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setRequestType (RequestType requestType)
Request type for tunnel.
Parameters
requestType request type for tunnel
Definition at line 144 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.requestType().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setRptFlag (boolean rptFlag)
Sets report flag.
Parameters
rptFlag report flag
Definition at line 215 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.rptFlag().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setStatefulIpv4IndentifierTlv (StatefulIPv4LspIdentidiersTlv value)
Sets statefulIpv4Identifiers tlv.
Parameters
value statefulIpv4Identifiers tlv
Definition at line 206 of file PcepTunnelData.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setTunnel (Tunnel tunnel)
Sets tunnel.
Parameters
tunnel mpls tunnel
Definition at line 126 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnel().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setTunnelId (short value)
Sets tunnel id from PCC.
Parameters
value tunnel id value
Definition at line 180 of file PcepTunnelData.java.
StatefulIPv4LspIdentidiersTlv org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.statefulIpv4IndentifierTlv ()
To get statefulIpv4Indentifier tlv.
Returns
statefulIpv4Indentifier tlv
Definition at line 332 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
String org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString ()
Definition at line 378 of file PcepTunnelData.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.elementId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.extTunnelId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspAFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspDFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.lspOFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.path(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.plspId(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.requestType(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.rptFlag(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.statefulIpv4IndentifierTlv(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnel(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnelId().
Tunnel org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnel ()
To get Tunnel.
Returns
tunnel
Definition at line 242 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.PcepTunnelData(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.setTunnel(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
short org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.tunnelId ()
To get tunnel id.
Returns
tunnel id
Definition at line 296 of file PcepTunnelData.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.equals(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.hashCode(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelData.toString().
The documentation for this class was generated from the following file:
providers/pcep/tunnel/src/main/java/org/onosproject/provider/pcep/tunnel/impl/PcepTunnelData.java