onos: org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1 Class Reference
Provides PCEP label range object.
Classes
class Builder
Builder class for PCEP label range object.
Public Member Functions
PcepLabelRangeObjectVer1 (PcepObjectHeader labelRangeObjHeader, byte labelType, int rangeSize, int labelBase, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize parameters for PCEP label range object.
void setLabelRangeObjHeader (PcepObjectHeader obj)
Sets LabelRange Object header.
void setLabelType (byte labelType)
Sets LabelType in LabelRange Object.
void setRangeSize (int rangeSize)
Sets RangeSize in LabelRange Object.
void setLabelBase (int labelBase)
Sets LabelBase in LabelRange Object.
PcepObjectHeader getLabelRangeObjHeader ()
Returns LabelRange object header.
byte getLabelType ()
Returns LabelType field in LabelRange object.
int getRangeSize ()
Returns RangeSize field in LabelRange object.
int getLabelBase ()
Returns LabelBase field in LabelRange object.
int write (ChannelBuffer cb) throws PcepParseException
Writes the LabelRange Object into channel buffer.
String toString ()
Static Public Member Functions
static PcepLabelRangeObject read (ChannelBuffer cb) throws PcepParseException
Reads from the channel buffer and returns object of PcepLabelRangeObject.
static LinkedList< PcepValueType > parseOptionalTlv (ChannelBuffer cb) throws PcepParseException
Returns list of optional tlvs.
Static Public Attributes
static final byte LABEL_RANGE_OBJ_TYPE = 1
static final byte LABEL_RANGE_OBJ_CLASS = 60
static final byte LABEL_RANGE_OBJECT_VERSION = 1
static final short LABEL_RANGE_OBJ_MINIMUM_LENGTH = 12
static final int MINIMUM_COMMON_HEADER_LENGTH = 4
Protected Member Functions
boolean packOptionalTlv (ChannelBuffer cb)
Pack optional tlvs.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepLabelRangeObjectVer1.class)
Detailed Description
Provides PCEP label range object.
Definition at line 36 of file PcepLabelRangeObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.PcepLabelRangeObjectVer1 (PcepObjectHeader labelRangeObjHeader, byte labelType, int rangeSize, int labelBase, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize parameters for PCEP label range object.
Parameters
labelRangeObjHeader label range object header
labelType label type
rangeSize range size
labelBase label base
llOptionalTlv list of optional tlvs
Definition at line 82 of file PcepLabelRangeObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.read().
Member Function Documentation
int org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.getLabelBase ()
Returns LabelBase field in LabelRange object.
Returns
LabelBase field in LabelRange object
Implements org.onosproject.pcepio.protocol.PcepLabelRangeObject.
Definition at line 127 of file PcepLabelRangeObjectVer1.java.
PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.getLabelRangeObjHeader ()
Returns LabelRange object header.
Returns
LabelRange object header
Implements org.onosproject.pcepio.protocol.PcepLabelRangeObject.
Definition at line 112 of file PcepLabelRangeObjectVer1.java.
byte org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.getLabelType ()
Returns LabelType field in LabelRange object.
Returns
LabelType field in LabelRange object
Implements org.onosproject.pcepio.protocol.PcepLabelRangeObject.
Definition at line 117 of file PcepLabelRangeObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.getRangeSize ()
Returns RangeSize field in LabelRange object.
Returns
RangeSize field in LabelRange object
Implements org.onosproject.pcepio.protocol.PcepLabelRangeObject.
Definition at line 122 of file PcepLabelRangeObjectVer1.java.
boolean org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.packOptionalTlv (ChannelBuffer cb) protected
Pack optional tlvs.
Parameters
cb of channel buffer
Returns
true
Definition at line 231 of file PcepLabelRangeObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.write().
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.parseOptionalTlv (ChannelBuffer cb) throws PcepParseException static
Returns list of optional tlvs.
Parameters
cb of type channle buffer
Returns
list of optional tlvs
Exceptions
PcepParseException whne fails to parse list of optional tlvs
Definition at line 190 of file PcepLabelRangeObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.MINIMUM_COMMON_HEADER_LENGTH.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.read().
static PcepLabelRangeObject org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.read (ChannelBuffer cb) throws PcepParseException static
Reads from the channel buffer and returns object of PcepLabelRangeObject.
Parameters
cb of type channel buffer
Returns
object of PcepLabelRangeObject
Exceptions
PcepParseException when fails to read from channel buffer
Definition at line 138 of file PcepLabelRangeObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.MINIMUM_COMMON_HEADER_LENGTH, org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.parseOptionalTlv(), and org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.PcepLabelRangeObjectVer1().
void org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.setLabelBase (int labelBase)
Sets LabelBase in LabelRange Object.
Parameters
labelBase label base value
Implements org.onosproject.pcepio.protocol.PcepLabelRangeObject.
Definition at line 107 of file PcepLabelRangeObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.setLabelRangeObjHeader (PcepObjectHeader obj)
Sets LabelRange Object header.
Parameters
obj LabelRange Object header
Implements org.onosproject.pcepio.protocol.PcepLabelRangeObject.
Definition at line 92 of file PcepLabelRangeObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.setLabelType (byte labelType)
Sets LabelType in LabelRange Object.
Parameters
labelType label type value
Implements org.onosproject.pcepio.protocol.PcepLabelRangeObject.
Definition at line 97 of file PcepLabelRangeObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.setRangeSize (int rangeSize)
Sets RangeSize in LabelRange Object.
Parameters
rangeSize range size value
Implements org.onosproject.pcepio.protocol.PcepLabelRangeObject.
Definition at line 102 of file PcepLabelRangeObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.toString ()
Definition at line 369 of file PcepLabelRangeObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the LabelRange Object into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException while writing LABEL RANGE object into Channel Buffer.
Implements org.onosproject.pcepio.protocol.PcepLabelRangeObject.
Definition at line 161 of file PcepLabelRangeObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.packOptionalTlv().
Member Data Documentation
final byte org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.LABEL_RANGE_OBJ_CLASS = 60 static
Definition at line 57 of file PcepLabelRangeObjectVer1.java.
final short org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.LABEL_RANGE_OBJ_MINIMUM_LENGTH = 12 static
Definition at line 59 of file PcepLabelRangeObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.LABEL_RANGE_OBJ_TYPE = 1 static
Definition at line 56 of file PcepLabelRangeObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.LABEL_RANGE_OBJECT_VERSION = 1 static
Definition at line 58 of file PcepLabelRangeObjectVer1.java.
final Logger org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.log = LoggerFactory.getLogger(PcepLabelRangeObjectVer1.class) static protected
Definition at line 54 of file PcepLabelRangeObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.MINIMUM_COMMON_HEADER_LENGTH = 4 static
Definition at line 60 of file PcepLabelRangeObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.parseOptionalTlv(), and org.onosproject.pcepio.protocol.ver1.PcepLabelRangeObjectVer1.read().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepLabelRangeObjectVer1.java