onos: org.onosproject.flowanalyzer.FlowAnalyzer Class Reference
org.onosproject.flowanalyzer.FlowAnalyzer Class Reference
Simple flow space analyzer app.
Public Member Functions
void activate (ComponentContext context)
void deactivate ()
String analyze ()
Analyzes and prints out a report on the status of every flow entry inside the network.
Map< FlowEntry, String > calcLabels ()
String analysisOutput ()
String flowEntryRepresentation (FlowEntry flow)
Protected Attributes
FlowRuleService flowRuleService
TopologyService topologyService
LinkService linkService
Detailed Description
Simple flow space analyzer app.
Definition at line 56 of file FlowAnalyzer.java.
Member Function Documentation
void org.onosproject.flowanalyzer.FlowAnalyzer.activate (ComponentContext context)
Definition at line 70 of file FlowAnalyzer.java.
String org.onosproject.flowanalyzer.FlowAnalyzer.analysisOutput ()
Definition at line 148 of file FlowAnalyzer.java.
String org.onosproject.flowanalyzer.FlowAnalyzer.analyze ()
Analyzes and prints out a report on the status of every flow entry inside the network.
The possible states are: Cleared (implying that the entry leads to a host), Cycle (implying that it is part of cycle), and Black Hole (implying that the entry does not lead to a single host).
Returns
result string
Definition at line 91 of file FlowAnalyzer.java.
References onos.size.
Referenced by org.onosproject.flowanalyzer.FlowAnalysisCommand.execute().
Map<FlowEntry, String> org.onosproject.flowanalyzer.FlowAnalyzer.calcLabels ()
Definition at line 144 of file FlowAnalyzer.java.
void org.onosproject.flowanalyzer.FlowAnalyzer.deactivate ()
Definition at line 75 of file FlowAnalyzer.java.
String org.onosproject.flowanalyzer.FlowAnalyzer.flowEntryRepresentation (FlowEntry flow)
Definition at line 267 of file FlowAnalyzer.java.
References org.onosproject.net.flow.FlowRule.selector(), and org.onosproject.net.flow.FlowRule.treatment().
Member Data Documentation
FlowRuleService org.onosproject.flowanalyzer.FlowAnalyzer.flowRuleService protected
Definition at line 61 of file FlowAnalyzer.java.
LinkService org.onosproject.flowanalyzer.FlowAnalyzer.linkService protected
Definition at line 67 of file FlowAnalyzer.java.
TopologyService org.onosproject.flowanalyzer.FlowAnalyzer.topologyService protected
Definition at line 64 of file FlowAnalyzer.java.
The documentation for this class was generated from the following file:
apps/flowanalyzer/src/main/java/org/onosproject/flowanalyzer/FlowAnalyzer.java