onos: org.onlab.packet.IGMPGroup Class Reference
org.onlab.packet.IGMPGroup Class Reference abstract
A class to represent Groups for membership query and reports.
Public Member Functions
IGMPGroup ()
IGMPGroup (IpAddress gaddr, int auxInfo)
Initialize this object with a multicast group address and additional info.
IpAddress getGaddr ()
Get the multicast group address.
int getAuxInfo ()
Get the auxillary info.
void addSource (IpAddress saddr)
Add a unicast source address to this message.
List< IpAddress > getSources ()
Return the list of source addresses.
abstract IGMPGroup deserialize (ByteBuffer bb) throws DeserializationException
Deserialize an IGMPQuery or IGMPMembership message.
abstract byte[] serialize (ByteBuffer bb)
Serialize the IGMPGroup subclass.
Protected Attributes
int auxInfo
IpAddress gaddr
List< IpAddress > sources = new ArrayList<>()
Detailed Description
A class to represent Groups for membership query and reports.
Definition at line 25 of file IGMPGroup.java.
Constructor & Destructor Documentation
org.onlab.packet.IGMPGroup.IGMPGroup ()
Definition at line 31 of file IGMPGroup.java.
org.onlab.packet.IGMPGroup.IGMPGroup (IpAddress gaddr, int auxInfo)
Initialize this object with a multicast group address and additional info.
Parameters
gaddr,: the multicast group address for this message type.
auxInfo,: additional info potentially used by IGMPQuery
Definition at line 40 of file IGMPGroup.java.
References org.onlab.packet.IGMPGroup.auxInfo, and org.onlab.packet.IGMPGroup.gaddr.
Member Function Documentation
void org.onlab.packet.IGMPGroup.addSource (IpAddress saddr)
Add a unicast source address to this message.
Parameters
saddr IPv4 unicast source address
Definition at line 68 of file IGMPGroup.java.
abstract IGMPGroup org.onlab.packet.IGMPGroup.deserialize (ByteBuffer bb) throws DeserializationException pure virtual
Deserialize an IGMPQuery or IGMPMembership message.
Parameters
bb the ByteBuffer wrapping the serialized message. The position of the ByteBuffer should be pointing at the head of either message type.
Returns
An object populated with the respective IGMPGroup subclass
Exceptions
DeserializationException in case deserialization goes wrong
Implemented in org.onlab.packet.IGMPQuery, and org.onlab.packet.IGMPMembership.
int org.onlab.packet.IGMPGroup.getAuxInfo ()
Get the auxillary info.
Returns
the auxillary info
Definition at line 59 of file IGMPGroup.java.
IpAddress org.onlab.packet.IGMPGroup.getGaddr ()
Get the multicast group address.
Returns
the group address
Definition at line 50 of file IGMPGroup.java.
List<IpAddress> org.onlab.packet.IGMPGroup.getSources ()
Return the list of source addresses.
Returns
list of source addresses
Definition at line 77 of file IGMPGroup.java.
References org.onlab.packet.IGMPGroup.sources.
abstract byte [] org.onlab.packet.IGMPGroup.serialize (ByteBuffer bb) pure virtual
Serialize the IGMPGroup subclass.
Parameters
bb the ByteBuffer to write into, positioned at the next spot to be written to.
Returns
The serialized message
Implemented in org.onlab.packet.IGMPQuery, and org.onlab.packet.IGMPMembership.
Member Data Documentation
int org.onlab.packet.IGMPGroup.auxInfo protected
Definition at line 27 of file IGMPGroup.java.
Referenced by org.onlab.packet.IGMPGroup.IGMPGroup().
IpAddress org.onlab.packet.IGMPGroup.gaddr protected
Definition at line 28 of file IGMPGroup.java.
Referenced by org.onlab.packet.IGMPMembership.deserialize(), org.onlab.packet.IGMPQuery.deserialize(), org.onlab.packet.IGMPMembership.equals(), and org.onlab.packet.IGMPGroup.IGMPGroup().
List<IpAddress> org.onlab.packet.IGMPGroup.sources = new ArrayList<>() protected
Definition at line 29 of file IGMPGroup.java.
Referenced by org.onlab.packet.IGMP.addGroup(), org.onlab.packet.IGMPMembership.equals(), org.onlab.packet.IGMPQuery.equals(), org.onlab.packet.IGMPGroup.getSources(), org.onlab.packet.IGMPMembership.serialize(), and org.onlab.packet.IGMPQuery.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/IGMPGroup.java