onos: org.onosproject.pcepio.types.SymbolicPathNameTlv Class Reference
org.onosproject.pcepio.types.SymbolicPathNameTlv Class Reference
Provides SymbolicPathNameTlv.
Public Member Functions
SymbolicPathNameTlv (byte[] rawValue)
Constructor to initialize raw Value.
SymbolicPathNameTlv (byte[] rawValue, short hLength)
Constructor to initialize raw Value.
byte[] getValue ()
Returns Symbolic path name.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static SymbolicPathNameTlv of (final byte[] raw, short hLength)
Creates an object of SymbolicPathNameTlv.
static SymbolicPathNameTlv read (ChannelBuffer c, short hLength)
Reads channel buffer and returns object of SymbolicPathNameTlv.
Static Public Attributes
static final short TYPE = 17
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(SymbolicPathNameTlv.class)
Detailed Description
Provides SymbolicPathNameTlv.
Definition at line 31 of file SymbolicPathNameTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.SymbolicPathNameTlv.SymbolicPathNameTlv (byte[] rawValue)
Constructor to initialize raw Value.
Parameters
rawValue Symbolic path name
Definition at line 59 of file SymbolicPathNameTlv.java.
Referenced by org.onosproject.pcepio.types.SymbolicPathNameTlv.equals(), org.onosproject.pcepio.types.SymbolicPathNameTlv.of(), and org.onosproject.pcepio.types.SymbolicPathNameTlv.read().
org.onosproject.pcepio.types.SymbolicPathNameTlv.SymbolicPathNameTlv (byte[] rawValue, short hLength)
Constructor to initialize raw Value.
Parameters
rawValue Symbolic path name
hLength length of Symbolic path name
Definition at line 70 of file SymbolicPathNameTlv.java.
Member Function Documentation
boolean org.onosproject.pcepio.types.SymbolicPathNameTlv.equals (Object obj)
Definition at line 120 of file SymbolicPathNameTlv.java.
References org.onosproject.pcepio.types.SymbolicPathNameTlv.SymbolicPathNameTlv().
short org.onosproject.pcepio.types.SymbolicPathNameTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 110 of file SymbolicPathNameTlv.java.
short org.onosproject.pcepio.types.SymbolicPathNameTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 105 of file SymbolicPathNameTlv.java.
References org.onosproject.pcepio.types.SymbolicPathNameTlv.TYPE.
byte [] org.onosproject.pcepio.types.SymbolicPathNameTlv.getValue ()
Returns Symbolic path name.
Returns
Symbolic path name byte array
Definition at line 95 of file SymbolicPathNameTlv.java.
PcepVersion org.onosproject.pcepio.types.SymbolicPathNameTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 100 of file SymbolicPathNameTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.SymbolicPathNameTlv.hashCode ()
Definition at line 115 of file SymbolicPathNameTlv.java.
static SymbolicPathNameTlv org.onosproject.pcepio.types.SymbolicPathNameTlv.of (final byte[] raw, short hLength) static
Creates an object of SymbolicPathNameTlv.
Parameters
raw Symbolic path name
hLength length of Symbolic path name
Returns
object of SymbolicPathNameTlv
Definition at line 86 of file SymbolicPathNameTlv.java.
References org.onosproject.pcepio.types.SymbolicPathNameTlv.SymbolicPathNameTlv().
static SymbolicPathNameTlv org.onosproject.pcepio.types.SymbolicPathNameTlv.read (ChannelBuffer c, short hLength) static
Reads channel buffer and returns object of SymbolicPathNameTlv.
Parameters
c of type channel buffer
hLength length of bytes to read
Returns
object of SymbolicPathNameTlv
Definition at line 147 of file SymbolicPathNameTlv.java.
References org.onosproject.pcepio.types.SymbolicPathNameTlv.SymbolicPathNameTlv().
String org.onosproject.pcepio.types.SymbolicPathNameTlv.toString ()
Definition at line 154 of file SymbolicPathNameTlv.java.
int org.onosproject.pcepio.types.SymbolicPathNameTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 132 of file SymbolicPathNameTlv.java.
References org.onosproject.pcepio.types.SymbolicPathNameTlv.TYPE.
Member Data Documentation
final Logger org.onosproject.pcepio.types.SymbolicPathNameTlv.log = LoggerFactory.getLogger(SymbolicPathNameTlv.class) static protected
Definition at line 47 of file SymbolicPathNameTlv.java.
final short org.onosproject.pcepio.types.SymbolicPathNameTlv.TYPE = 17 static
Definition at line 49 of file SymbolicPathNameTlv.java.
Referenced by org.onosproject.pcepio.types.SymbolicPathNameTlv.getType(), and org.onosproject.pcepio.types.SymbolicPathNameTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/SymbolicPathNameTlv.java