onos: org.onosproject.net.intent.constraint.EncapsulationConstraint Class Reference
org.onosproject.net.intent.constraint.EncapsulationConstraint Class Reference
Encapsulation to manage core transportation.
Public Member Functions
EncapsulationConstraint (EncapsulationType encapType)
Creates a new encapsulation constraint.
boolean isValid (Link link, LinkResourceService resourceService)
Returns true if the specified link satisfies the constraint.
EncapsulationType encapType ()
Returns the encapsulation type required by this constraint.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.constraint.BooleanConstraint
double cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
boolean validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
Detailed Description
Encapsulation to manage core transportation.
Definition at line 30 of file EncapsulationConstraint.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.constraint.EncapsulationConstraint.EncapsulationConstraint (EncapsulationType encapType)
Creates a new encapsulation constraint.
Parameters
encapType the encapsulation type EncapsulationType
Definition at line 39 of file EncapsulationConstraint.java.
References org.onosproject.net.intent.constraint.EncapsulationConstraint.encapType().
Referenced by org.onosproject.net.intent.constraint.EncapsulationConstraint.equals().
Member Function Documentation
EncapsulationType org.onosproject.net.intent.constraint.EncapsulationConstraint.encapType ()
Returns the encapsulation type required by this constraint.
Returns
encapType
Definition at line 58 of file EncapsulationConstraint.java.
Referenced by org.onosproject.net.intent.constraint.EncapsulationConstraint.EncapsulationConstraint(), and org.onosproject.net.intent.constraint.EncapsulationConstraint.toString().
boolean org.onosproject.net.intent.constraint.EncapsulationConstraint.equals (Object obj)
Definition at line 68 of file EncapsulationConstraint.java.
References org.onosproject.net.intent.constraint.EncapsulationConstraint.EncapsulationConstraint().
int org.onosproject.net.intent.constraint.EncapsulationConstraint.hashCode ()
Definition at line 63 of file EncapsulationConstraint.java.
boolean org.onosproject.net.intent.constraint.EncapsulationConstraint.isValid (Link link, LinkResourceService resourceService) virtual
Returns true if the specified link satisfies the constraint.
Parameters
link link to be validated
resourceService resource service for checking available link resources
Returns
true if link is viable
Implements org.onosproject.net.intent.constraint.BooleanConstraint.
Definition at line 46 of file EncapsulationConstraint.java.
String org.onosproject.net.intent.constraint.EncapsulationConstraint.toString ()
Definition at line 80 of file EncapsulationConstraint.java.
References org.onosproject.net.intent.constraint.EncapsulationConstraint.encapType().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/constraint/EncapsulationConstraint.java