onos: org.onosproject.openflow.controller.DefaultOpenFlowPacketContext Class Reference
org.onosproject.openflow.controller.DefaultOpenFlowPacketContext Class Reference
Default implementation of an OpenFlowPacketContext.
Public Member Functions
void send ()
Provided build has been called send the packet out the switch it came in on.
void build (OFPort outPort)
Build the packet out in response to this packet in event.
void build (Ethernet ethFrame, OFPort outPort)
Build the packet out in response to this packet in event.
Ethernet parsed ()
Provided a handle onto the parsed payload.
Dpid dpid ()
Provide the dpid of the switch where the packet in arrived.
Integer inPort ()
Provide the port on which the packet arrived.
byte[] unparsed ()
Provide an unparsed copy of the data.
boolean block ()
Blocks further responses (ie.
boolean isHandled ()
Checks whether the packet has been handled.
boolean isBuffered ()
Indicates that this packet is buffered at the switch.
Static Public Member Functions
static OpenFlowPacketContext packetContextFromPacketIn (OpenFlowSwitch s, OFPacketIn pkt)
Creates an OpenFlow packet context based on a packet-in.
Detailed Description
Default implementation of an OpenFlowPacketContext.
Definition at line 42 of file DefaultOpenFlowPacketContext.java.
Member Function Documentation
boolean org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.block ()
Blocks further responses (ie.
send() calls) on this packet in event.
Returns
true if blocks
Implements org.onosproject.openflow.controller.OpenFlowPacketContext.
Definition at line 162 of file DefaultOpenFlowPacketContext.java.
Referenced by org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.send().
void org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.build (OFPort outPort)
Build the packet out in response to this packet in event.
Parameters
outPort the out port to send to packet out of.
Implements org.onosproject.openflow.controller.OpenFlowPacketContext.
Definition at line 68 of file DefaultOpenFlowPacketContext.java.
Referenced by org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.build().
void org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.build (Ethernet ethFrame, OFPort outPort)
Build the packet out in response to this packet in event.
Parameters
ethFrame the actual packet to send out.
outPort the out port to send to packet out of.
Implements org.onosproject.openflow.controller.OpenFlowPacketContext.
Definition at line 84 of file DefaultOpenFlowPacketContext.java.
References org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.build(), and org.onlab.packet.Ethernet.serialize().
Dpid org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.dpid ()
Provide the dpid of the switch where the packet in arrived.
Returns
the dpid of the switch.
Implements org.onosproject.openflow.controller.OpenFlowPacketContext.
Definition at line 113 of file DefaultOpenFlowPacketContext.java.
References org.onosproject.openflow.controller.OpenFlowSwitch.getId().
Referenced by opticalUtils.LINCSwitch.read_from_cli(), and opticalUtils.LINCSwitch.start().
Integer org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.inPort ()
Provide the port on which the packet arrived.
Returns
the port
Implements org.onosproject.openflow.controller.OpenFlowPacketContext.
Definition at line 132 of file DefaultOpenFlowPacketContext.java.
boolean org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.isBuffered ()
Indicates that this packet is buffered at the switch.
Returns
buffer indication
Implements org.onosproject.openflow.controller.OpenFlowPacketContext.
Definition at line 176 of file DefaultOpenFlowPacketContext.java.
boolean org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.isHandled ()
Checks whether the packet has been handled.
Returns
true if handled, false otherwise.
Implements org.onosproject.openflow.controller.OpenFlowPacketContext.
Definition at line 169 of file DefaultOpenFlowPacketContext.java.
static OpenFlowPacketContext org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.packetContextFromPacketIn (OpenFlowSwitch s, OFPacketIn pkt) static
Creates an OpenFlow packet context based on a packet-in.
Parameters
s OpenFlow switch
pkt OpenFlow packet-in
Returns
the OpenFlow packet context
Definition at line 126 of file DefaultOpenFlowPacketContext.java.
Ethernet org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.parsed ()
Provided a handle onto the parsed payload.
Returns
the parsed form of the payload.
Implements org.onosproject.openflow.controller.OpenFlowPacketContext.
Definition at line 99 of file DefaultOpenFlowPacketContext.java.
References find-link-in-cluster.length.
void org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.send ()
Provided build has been called send the packet out the switch it came in on.
Implements org.onosproject.openflow.controller.OpenFlowPacketContext.
Definition at line 59 of file DefaultOpenFlowPacketContext.java.
References org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.block().
byte [] org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.unparsed ()
Provide an unparsed copy of the data.
Returns
the unparsed form of the payload.
Implements org.onosproject.openflow.controller.OpenFlowPacketContext.
Definition at line 146 of file DefaultOpenFlowPacketContext.java.
The documentation for this class was generated from the following file:
protocols/openflow/api/src/main/java/org/onosproject/openflow/controller/DefaultOpenFlowPacketContext.java