onos: org.onosproject.store.group.impl.DistributedGroupStoreTest Class Reference
org.onosproject.store.group.impl.DistributedGroupStoreTest Class Reference
Distributed group store test.
Classes
class MasterOfAll
class TestDelegate
Public Member Functions
void setUp () throws Exception
void tearDown () throws Exception
void testEmptyStore ()
Tests the initial state of the store.
void testAddPendingGroup () throws Exception
Tests adding a pending group.
void testAddRemoveGroup () throws Exception
Tests adding and removing a group.
void testRemoveGroupDescription () throws Exception
Tests adding and removing a group.
void testPushGroupMetrics ()
Tests pushing group metrics.
void testGroupOperationFailed ()
Tests group operation failed interface.
void testExtraneousOperations ()
Tests extraneous group operations.
void testUpdateGroupDescription ()
Tests updating of group descriptions.
void testEqualsGroupStoreIdMapKey ()
void testEqualsGroupStoreKeyMapKey ()
void testEqualsGroupStoreMapKey ()
Detailed Description
Distributed group store test.
Definition at line 67 of file DistributedGroupStoreTest.java.
Member Function Documentation
void org.onosproject.store.group.impl.DistributedGroupStoreTest.setUp () throws Exception
Definition at line 112 of file DistributedGroupStoreTest.java.
void org.onosproject.store.group.impl.DistributedGroupStoreTest.tearDown () throws Exception
Definition at line 124 of file DistributedGroupStoreTest.java.
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testAddPendingGroup () throws Exception
Tests adding a pending group.
Definition at line 142 of file DistributedGroupStoreTest.java.
References org.onosproject.net.group.GroupStore.getGroup(), and org.onosproject.net.group.GroupStore.getGroupCount().
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testAddRemoveGroup () throws Exception
Tests adding and removing a group.
Definition at line 166 of file DistributedGroupStoreTest.java.
References org.onosproject.net.group.GroupStore.deviceInitialAuditStatus(), org.onosproject.net.group.GroupStore.getGroup(), and org.onosproject.net.group.GroupStore.getGroupCount().
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testEmptyStore ()
Tests the initial state of the store.
Definition at line 132 of file DistributedGroupStoreTest.java.
References org.onosproject.net.group.GroupStore.getGroup(), and org.onosproject.net.group.GroupStore.getGroupCount().
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testEqualsGroupStoreIdMapKey ()
Definition at line 368 of file DistributedGroupStoreTest.java.
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testEqualsGroupStoreKeyMapKey ()
Definition at line 386 of file DistributedGroupStoreTest.java.
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testEqualsGroupStoreMapKey ()
Definition at line 404 of file DistributedGroupStoreTest.java.
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testExtraneousOperations ()
Tests extraneous group operations.
Definition at line 325 of file DistributedGroupStoreTest.java.
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testGroupOperationFailed ()
Tests group operation failed interface.
Definition at line 271 of file DistributedGroupStoreTest.java.
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testPushGroupMetrics ()
Tests pushing group metrics.
Definition at line 220 of file DistributedGroupStoreTest.java.
References org.onosproject.net.group.Group.bytes(), and org.onosproject.net.group.Group.packets().
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testRemoveGroupDescription () throws Exception
Tests adding and removing a group.
Definition at line 202 of file DistributedGroupStoreTest.java.
References org.onosproject.net.group.GroupStore.getGroupCount().
void org.onosproject.store.group.impl.DistributedGroupStoreTest.testUpdateGroupDescription ()
Tests updating of group descriptions.
Definition at line 348 of file DistributedGroupStoreTest.java.
The documentation for this class was generated from the following file:
core/store/dist/src/test/java/org/onosproject/store/group/impl/DistributedGroupStoreTest.java