onos: org.onosproject.core.impl.CoreManager Class Reference
org.onosproject.core.impl.CoreManager Class Reference
Core service implementation.
Public Member Functions
void activate ()
void deactivate ()
Version version ()
Returns the product version.
Set< ApplicationId > getAppIds ()
Returns the set of currently registered application identifiers.
ApplicationId getAppId (Short id)
Returns an existing application id from a given id.
ApplicationId getAppId (String name)
Returns an existing application id from a given id.
ApplicationId registerApplication (String name)
Registers a new application by its name, which is expected to follow the reverse DNS convention, e.g.
ApplicationId registerApplication (String name, Runnable preDeactivate)
Registers a new application by its name, which is expected to follow the reverse DNS convention, e.g.
IdGenerator getIdGenerator (String topic)
Returns an id generator for a given topic.
void modified (ComponentContext context)
Protected Attributes
ApplicationIdStore applicationIdStore
IdBlockStore idBlockStore
ApplicationService appService
ComponentConfigService cfgService
EventDeliveryService eventDeliveryService
Additional Inherited Members
Public Attributes inherited from org.onosproject.core.CoreService
String CORE_APP_NAME = "org.onosproject.core"
Name of the core "application".
ProviderId CORE_PROVIDER_ID = new ProviderId("core", CORE_APP_NAME)
Identifier of the core "provider".
Detailed Description
Core service implementation.
Definition at line 61 of file CoreManager.java.
Member Function Documentation
void org.onosproject.core.impl.CoreManager.activate ()
Definition at line 94 of file CoreManager.java.
References org.onosproject.core.CoreService.CORE_APP_NAME, org.onosproject.core.impl.CoreManager.registerApplication(), and org.onosproject.core.impl.CoreManager.version().
void org.onosproject.core.impl.CoreManager.deactivate ()
Definition at line 110 of file CoreManager.java.
ApplicationId org.onosproject.core.impl.CoreManager.getAppId (Short id)
Returns an existing application id from a given id.
Parameters
id the short value of the id
Returns
an application id
Implements org.onosproject.core.CoreService.
Definition at line 128 of file CoreManager.java.
References find-device.id.
ApplicationId org.onosproject.core.impl.CoreManager.getAppId (String name)
Returns an existing application id from a given id.
Parameters
name the name portion of the ID to look up
Returns
an application id
Implements org.onosproject.core.CoreService.
Definition at line 134 of file CoreManager.java.
References create-flow.name.
Set<ApplicationId> org.onosproject.core.impl.CoreManager.getAppIds ()
Returns the set of currently registered application identifiers.
Returns
set of application ids
Implements org.onosproject.core.CoreService.
Definition at line 122 of file CoreManager.java.
IdGenerator org.onosproject.core.impl.CoreManager.getIdGenerator (String topic)
Returns an id generator for a given topic.
Parameters
topic topic identified
Returns
the id generator
Implements org.onosproject.core.CoreService.
Definition at line 154 of file CoreManager.java.
References org.onosproject.core.impl.CoreManager.idBlockStore.
void org.onosproject.core.impl.CoreManager.modified (ComponentContext context)
Definition at line 161 of file CoreManager.java.
ApplicationId org.onosproject.core.impl.CoreManager.registerApplication (String name)
Registers a new application by its name, which is expected to follow the reverse DNS convention, e.g.
org.flying.circus.app
Parameters
name string identifier
Returns
the application id
Implements org.onosproject.core.CoreService.
Definition at line 141 of file CoreManager.java.
References create-flow.name.
Referenced by org.onosproject.core.impl.CoreManager.activate(), and org.onosproject.core.impl.CoreManager.registerApplication().
ApplicationId org.onosproject.core.impl.CoreManager.registerApplication (String name, Runnable preDeactivate)
Registers a new application by its name, which is expected to follow the reverse DNS convention, e.g.
org.flying.circus.app
, along with its pre-deactivation hook.
Parameters
name string identifier
preDeactivate pre-deactivation hook
Returns
the application id
Implements org.onosproject.core.CoreService.
Definition at line 147 of file CoreManager.java.
References find-device.id, and org.onosproject.core.impl.CoreManager.registerApplication().
Version org.onosproject.core.impl.CoreManager.version ()
Returns the product version.
Returns
product version
Implements org.onosproject.core.CoreService.
Definition at line 116 of file CoreManager.java.
Referenced by org.onosproject.core.impl.CoreManager.activate().
Member Data Documentation
ApplicationIdStore org.onosproject.core.impl.CoreManager.applicationIdStore protected
Definition at line 69 of file CoreManager.java.
ApplicationService org.onosproject.core.impl.CoreManager.appService protected
Definition at line 75 of file CoreManager.java.
ComponentConfigService org.onosproject.core.impl.CoreManager.cfgService protected
Definition at line 78 of file CoreManager.java.
EventDeliveryService org.onosproject.core.impl.CoreManager.eventDeliveryService protected
Definition at line 81 of file CoreManager.java.
IdBlockStore org.onosproject.core.impl.CoreManager.idBlockStore protected
Definition at line 72 of file CoreManager.java.
Referenced by org.onosproject.core.impl.CoreManager.getIdGenerator().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/core/impl/CoreManager.java