onos: org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv Class Reference
org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv Class Reference
NexthopUnnumberedIPv4IDTlv provides the next node's ID and Interface ID.
Public Member Functions
NexthopUnnumberedIPv4IDTlv (int nodeID, int interfaceID)
constructor to initialize nodeID and interfaceID.
int getNodeID ()
Returns Node Id.
int getInterfaceID ()
Returns Interface Id.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static NexthopUnnumberedIPv4IDTlv of (int nodeID, int interfaceID)
Returns new object of NexthopUnnumberedIPv4IDTlv.
static NexthopUnnumberedIPv4IDTlv read (ChannelBuffer cb)
Reads the channel buffer and returns object of NexthopUnnumberedIPv4IDTlv.
Static Public Attributes
static final short TYPE = 1
static final short LENGTH = 12
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(NexthopUnnumberedIPv4IDTlv.class)
Detailed Description
NexthopUnnumberedIPv4IDTlv provides the next node's ID and Interface ID.
Definition at line 31 of file NexthopUnnumberedIPv4IDTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.NexthopUnnumberedIPv4IDTlv (int nodeID, int interfaceID)
constructor to initialize nodeID and interfaceID.
Parameters
nodeID node ID
interfaceID interface ID
Definition at line 64 of file NexthopUnnumberedIPv4IDTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.equals(), org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.of(), and org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.equals (Object obj)
Definition at line 119 of file NexthopUnnumberedIPv4IDTlv.java.
References org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.NexthopUnnumberedIPv4IDTlv().
int org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.getInterfaceID ()
Returns Interface Id.
Returns
interface ID
Definition at line 94 of file NexthopUnnumberedIPv4IDTlv.java.
short org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 109 of file NexthopUnnumberedIPv4IDTlv.java.
References org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.LENGTH.
int org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.getNodeID ()
Returns Node Id.
Returns
node ID
Definition at line 85 of file NexthopUnnumberedIPv4IDTlv.java.
short org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 104 of file NexthopUnnumberedIPv4IDTlv.java.
References org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 99 of file NexthopUnnumberedIPv4IDTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.hashCode ()
Definition at line 114 of file NexthopUnnumberedIPv4IDTlv.java.
static NexthopUnnumberedIPv4IDTlv org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.of (int nodeID, int interfaceID) static
Returns new object of NexthopUnnumberedIPv4IDTlv.
Parameters
nodeID node ID
interfaceID interface ID
Returns
NexthopUnnumberedIPv4IDTlv
Definition at line 76 of file NexthopUnnumberedIPv4IDTlv.java.
References org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.NexthopUnnumberedIPv4IDTlv().
static NexthopUnnumberedIPv4IDTlv org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.read (ChannelBuffer cb) static
Reads the channel buffer and returns object of NexthopUnnumberedIPv4IDTlv.
Parameters
cb type of channel buffer
Returns
object of NexthopUnnumberedIPv4IDTlv
Definition at line 148 of file NexthopUnnumberedIPv4IDTlv.java.
References org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.NexthopUnnumberedIPv4IDTlv().
String org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.toString ()
Definition at line 155 of file NexthopUnnumberedIPv4IDTlv.java.
References org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.LENGTH, and org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.TYPE.
int org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 131 of file NexthopUnnumberedIPv4IDTlv.java.
References org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.LENGTH, and org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.LENGTH = 12 static
Definition at line 53 of file NexthopUnnumberedIPv4IDTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.getLength(), org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.toString(), and org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.write().
final Logger org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.log = LoggerFactory.getLogger(NexthopUnnumberedIPv4IDTlv.class) static protected
Definition at line 49 of file NexthopUnnumberedIPv4IDTlv.java.
final short org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.TYPE = 1 static
Definition at line 51 of file NexthopUnnumberedIPv4IDTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.getType(), org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.toString(), and org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/NexthopUnnumberedIPv4IDTlv.java