onos: org.onlab.packet.EthernetTest Class Reference
org.onlab.packet.EthernetTest Class Reference
Unit tests for the Ethernet class.
Public Member Functions
void setUp ()
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws DeserializationException
void testDeserializeNoVlan () throws Exception
void testDeserializeWithVlan () throws Exception
Detailed Description
Unit tests for the Ethernet class.
Definition at line 29 of file EthernetTest.java.
Member Function Documentation
void org.onlab.packet.EthernetTest.setUp ()
Definition at line 42 of file EthernetTest.java.
References org.onlab.packet.Ethernet.ETHERNET_HEADER_LENGTH, org.onlab.packet.Ethernet.TYPE_VLAN, and org.onlab.packet.Ethernet.VLAN_HEADER_LENGTH.
void org.onlab.packet.EthernetTest.testDeserializeBadInput () throws Exception
Definition at line 74 of file EthernetTest.java.
void org.onlab.packet.EthernetTest.testDeserializeNoVlan () throws Exception
Definition at line 84 of file EthernetTest.java.
References org.onlab.packet.Ethernet.getDestinationMAC(), org.onlab.packet.Ethernet.getEtherType(), org.onlab.packet.Ethernet.getSourceMAC(), org.onlab.packet.Ethernet.getVlanID(), find-link-in-cluster.length, and org.onlab.packet.Ethernet.VLAN_UNTAGGED.
void org.onlab.packet.EthernetTest.testDeserializeTruncated () throws DeserializationException
Definition at line 79 of file EthernetTest.java.
void org.onlab.packet.EthernetTest.testDeserializeWithVlan () throws Exception
Definition at line 94 of file EthernetTest.java.
References org.onlab.packet.Ethernet.getDestinationMAC(), org.onlab.packet.Ethernet.getEtherType(), org.onlab.packet.Ethernet.getSourceMAC(), org.onlab.packet.Ethernet.getVlanID(), and find-link-in-cluster.length.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/EthernetTest.java