onos: org.onosproject.store.flow.impl.NewDistributedFlowRuleStore Class Reference
org.onosproject.store.flow.impl.NewDistributedFlowRuleStore Class Reference
Manages inventory of flow rules using a distributed state management protocol.
Public Member Functions
void activate (ComponentContext context)
void deactivate (ComponentContext context)
void modified (ComponentContext context)
int getFlowRuleCount ()
Returns the number of flow rule in the store.
FlowEntry getFlowEntry (FlowRule rule)
Returns the stored flow.
Iterable< FlowEntry > getFlowEntries (DeviceId deviceId)
Returns the flow entries associated with a device.
void storeFlowRule (FlowRule rule)
// TODO: Better description of method behavior.
void storeBatch (FlowRuleBatchOperation operation)
Stores a batch of flow rules.
void deleteFlowRule (FlowRule rule)
Marks a flow rule for deletion.
FlowRuleEvent addOrUpdateFlowRule (FlowEntry rule)
Stores a new flow rule, or updates an existing entry.
FlowRuleEvent removeFlowRule (FlowEntry rule)
void batchOperationComplete (FlowRuleBatchEvent event)
Invoked on the completion of a storeBatch operation.
FlowRuleEvent updateTableStatistics (DeviceId deviceId, List< TableStatisticsEntry > tableStats)
Updates the flow table statistics of the specified device using the given statistics.
Iterable< TableStatisticsEntry > getTableStatistics (DeviceId deviceId)
Returns the flow table statistics associated with a device.
Protected Attributes
ReplicaInfoService replicaInfoManager
ClusterCommunicationService clusterCommunicator
ClusterService clusterService
DeviceService deviceService
CoreService coreService
ComponentConfigService configService
MastershipService mastershipService
PersistenceService persistenceService
StorageService storageService
Static Protected Attributes
static final StoreSerializer SERIALIZER
static final KryoNamespace.Builder SERIALIZER_BUILDER
Detailed Description
Manages inventory of flow rules using a distributed state management protocol.
Definition at line 110 of file NewDistributedFlowRuleStore.java.
Member Function Documentation
void org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.activate (ComponentContext context)
Definition at line 198 of file NewDistributedFlowRuleStore.java.
References org.onosproject.net.flow.FlowRuleService.FLOW_OP_TOPIC, org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.SERIALIZER_BUILDER, and org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.storageService.
FlowRuleEvent org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.addOrUpdateFlowRule (FlowEntry rule)
Stores a new flow rule, or updates an existing entry.
Parameters
rule the flow rule to add or update
Returns
flow_added event, or null if just an update
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 527 of file NewDistributedFlowRuleStore.java.
void org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.batchOperationComplete (FlowRuleBatchEvent event)
Invoked on the completion of a storeBatch operation.
Parameters
event flow rule batch event
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 596 of file NewDistributedFlowRuleStore.java.
void org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.deactivate (ComponentContext context)
Definition at line 232 of file NewDistributedFlowRuleStore.java.
void org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.deleteFlowRule (FlowRule rule)
Marks a flow rule for deletion.
Actual deletion will occur when the provider indicates that the flow has been removed.
Parameters
rule the flow rule to delete
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 517 of file NewDistributedFlowRuleStore.java.
References org.onosproject.core.IdGenerator.getNewId(), org.onosproject.net.flow.FlowRuleBatchEntry.FlowRuleOperation.REMOVE, and org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.storeBatch().
Iterable<FlowEntry> org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.getFlowEntries (DeviceId deviceId)
Returns the flow entries associated with a device.
Parameters
deviceId the device ID
Returns
the flow entries
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 385 of file NewDistributedFlowRuleStore.java.
References find-flow.deviceId, and org.onosproject.store.flow.impl.FlowStoreMessageSubjects.GET_DEVICE_FLOW_ENTRIES.
Referenced by org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.getFlowRuleCount().
FlowEntry org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.getFlowEntry (FlowRule rule)
Returns the stored flow.
Parameters
rule the rule to look for
Returns
a flow rule
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 359 of file NewDistributedFlowRuleStore.java.
References org.onosproject.store.flow.impl.FlowStoreMessageSubjects.GET_FLOW_ENTRY.
int org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.getFlowRuleCount ()
Returns the number of flow rule in the store.
Returns
number of flow rules
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 352 of file NewDistributedFlowRuleStore.java.
References create-flow.device, and org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.getFlowEntries().
Iterable<TableStatisticsEntry> org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.getTableStatistics (DeviceId deviceId)
Returns the flow table statistics associated with a device.
Parameters
deviceId the device ID
Returns
the flow table statistics
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 857 of file NewDistributedFlowRuleStore.java.
References find-flow.deviceId.
void org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.modified (ComponentContext context)
Definition at line 248 of file NewDistributedFlowRuleStore.java.
FlowRuleEvent org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.removeFlowRule (FlowEntry rule)
Parameters
rule the flow entry to remove
Returns
flow_removed event, or null if nothing removed
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 559 of file NewDistributedFlowRuleStore.java.
References find-flow.deviceId.
void org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.storeBatch (FlowRuleBatchOperation batchOperation)
Stores a batch of flow rules.
Parameters
batchOperation batch of flow rules. A batch can contain flow rules for a single device only.
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 418 of file NewDistributedFlowRuleStore.java.
References org.onosproject.net.flow.FlowRuleBatchEvent.completed(), and find-flow.deviceId.
Referenced by org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.deleteFlowRule(), and org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.storeFlowRule().
void org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.storeFlowRule (FlowRule rule)
// TODO: Better description of method behavior.
Stores a new flow rule without generating events.
Parameters
rule the flow rule to add
Deprecated:
in Cardinal Release
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 411 of file NewDistributedFlowRuleStore.java.
References org.onosproject.net.flow.FlowRuleBatchEntry.FlowRuleOperation.ADD, org.onosproject.core.IdGenerator.getNewId(), and org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.storeBatch().
FlowRuleEvent org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.updateTableStatistics (DeviceId deviceId, List< TableStatisticsEntry > tableStats)
Updates the flow table statistics of the specified device using the given statistics.
Parameters
deviceId device identifier
tableStats list of table statistics
Returns
ready to send event describing what occurred;
Implements org.onosproject.net.flow.FlowRuleStore.
Definition at line 850 of file NewDistributedFlowRuleStore.java.
References find-flow.deviceId.
Member Data Documentation
ClusterCommunicationService org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.clusterCommunicator protected
Definition at line 145 of file NewDistributedFlowRuleStore.java.
ClusterService org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.clusterService protected
Definition at line 148 of file NewDistributedFlowRuleStore.java.
ComponentConfigService org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.configService protected
Definition at line 157 of file NewDistributedFlowRuleStore.java.
CoreService org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.coreService protected
Definition at line 154 of file NewDistributedFlowRuleStore.java.
DeviceService org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.deviceService protected
Definition at line 151 of file NewDistributedFlowRuleStore.java.
MastershipService org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.mastershipService protected
Definition at line 160 of file NewDistributedFlowRuleStore.java.
PersistenceService org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.persistenceService protected
Definition at line 163 of file NewDistributedFlowRuleStore.java.
ReplicaInfoService org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.replicaInfoManager protected
Definition at line 142 of file NewDistributedFlowRuleStore.java.
final StoreSerializer org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.SERIALIZER static protected
Initial value:
= new KryoSerializer() {
        @Override
        protected void setupKryoPool() {
            serializerPool = KryoNamespace.newBuilder()
                    .register(DistributedStoreSerializers.STORE_COMMON)
                    .nextId(DistributedStoreSerializers.STORE_CUSTOM_BEGIN)
                    .build();
        }
    }
Definition at line 179 of file NewDistributedFlowRuleStore.java.
final KryoNamespace.Builder org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.SERIALIZER_BUILDER static protected
Initial value:
= KryoNamespace.newBuilder()
            .register(KryoNamespaces.API)
            .register(MastershipBasedTimestamp.class)
Definition at line 189 of file NewDistributedFlowRuleStore.java.
Referenced by org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.activate().
StorageService org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.storageService protected
Definition at line 177 of file NewDistributedFlowRuleStore.java.
Referenced by org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.activate().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/flow/impl/NewDistributedFlowRuleStore.java