onos: org.onosproject.incubator.rpc.grpc.GrpcRemoteServiceTest Class Reference
org.onosproject.incubator.rpc.grpc.GrpcRemoteServiceTest Class Reference
Set of tests of the gRPC RemoteService components.
Classes
class CTestDeviceProvider
Device Provider on CO side.
class MTestDeviceProviderRegistry
DeviceProvider on Metro side.
class NoOpRemoteServiceProviderRegistry
Public Member Functions
void setUp () throws Exception
void tearDown ()
void basics () throws InterruptedException
Static Public Member Functions
static int pickListenPort ()
Detailed Description
Set of tests of the gRPC RemoteService components.
Definition at line 65 of file GrpcRemoteServiceTest.java.
Member Function Documentation
void org.onosproject.incubator.rpc.grpc.GrpcRemoteServiceTest.basics () throws InterruptedException
Definition at line 147 of file GrpcRemoteServiceTest.java.
References org.onosproject.net.device.DeviceProvider.isReachable(), org.onosproject.net.MastershipRole.MASTER, and org.onosproject.net.MastershipRole.STANDBY.
static int org.onosproject.incubator.rpc.grpc.GrpcRemoteServiceTest.pickListenPort () static
Definition at line 106 of file GrpcRemoteServiceTest.java.
References obeliskHostCheck.port.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcRemoteServiceTest.setUp().
void org.onosproject.incubator.rpc.grpc.GrpcRemoteServiceTest.setUp () throws Exception
Definition at line 120 of file GrpcRemoteServiceTest.java.
References org.onosproject.incubator.rpc.grpc.GrpcRemoteServiceTest.pickListenPort().
void org.onosproject.incubator.rpc.grpc.GrpcRemoteServiceTest.tearDown ()
Definition at line 135 of file GrpcRemoteServiceTest.java.
The documentation for this class was generated from the following file:
incubator/rpc-grpc/src/test/java/org/onosproject/incubator/rpc/grpc/GrpcRemoteServiceTest.java