onos: org.onosproject.cli.net.ConnectivityIntentCommand Class Reference
org.onosproject.cli.net.ConnectivityIntentCommand Class Reference
Base class for command line operations for connectivity based intents.
Protected Member Functions
TrafficSelector buildTrafficSelector ()
Constructs a traffic selector based on the command line arguments presented to the command.
TrafficTreatment buildTrafficTreatment ()
Generates a traffic treatment for this intent based on command line arguments presented to the command.
List< Constraint > buildConstraints ()
Builds the constraint list for this command based on the command line parameters.
ApplicationId appId ()
Key key ()
Creates a key for an intent based on command line arguments.
int priority ()
Gets the priority to use for the intent.
Protected Member Functions inherited from org.onosproject.cli.AbstractShellCommand
ApplicationId appId ()
Returns application ID for the CLI.
abstract void execute ()
Executes this command.
boolean outputJson ()
Indicates whether JSON format should be output.
Object doExecute () throws Exception
Additional Inherited Members
Public Member Functions inherited from org.onosproject.cli.AbstractShellCommand
void print (String format, Object...args)
Prints the arguments using the specified format.
void error (String format, Object...args)
Prints the arguments using the specified format to error stream.
ObjectMapper mapper ()
Returns the JSON object mapper.
Static Public Member Functions inherited from org.onosproject.cli.AbstractShellCommand
static< T > T get (Class< T > serviceClass)
Returns the reference to the implementation of the specified service.
static String annotations (Annotations annotations)
Produces a string image of the specified key/value annotations.
static ObjectNode annotations (ObjectMapper mapper, Annotations annotations)
Produces a JSON object from the specified key/value annotations.
Detailed Description
Base class for command line operations for connectivity based intents.
Definition at line 54 of file ConnectivityIntentCommand.java.
Member Function Documentation
ApplicationId org.onosproject.cli.net.ConnectivityIntentCommand.appId () protected
Definition at line 399 of file ConnectivityIntentCommand.java.
Referenced by org.onosproject.cli.net.ConnectivityIntentCommand.key().
List<Constraint> org.onosproject.cli.net.ConnectivityIntentCommand.buildConstraints () protected
Builds the constraint list for this command based on the command line parameters.
Returns
List of constraint objects describing the constraints requested
Definition at line 369 of file ConnectivityIntentCommand.java.
TrafficSelector org.onosproject.cli.net.ConnectivityIntentCommand.buildTrafficSelector () protected
Constructs a traffic selector based on the command line arguments presented to the command.
Returns
traffic selector
Definition at line 192 of file ConnectivityIntentCommand.java.
References org.onlab.packet.IpPrefix.isIp4(), org.onlab.packet.IpPrefix.isIp6(), org.onosproject.cli.net.ExtHeader.parseFromString(), and org.onlab.packet.IpPrefix.version().
TrafficTreatment org.onosproject.cli.net.ConnectivityIntentCommand.buildTrafficTreatment () protected
Generates a traffic treatment for this intent based on command line arguments presented to the command.
Returns
traffic treatment
Definition at line 307 of file ConnectivityIntentCommand.java.
References obeliskHostCheck.port.
Key org.onosproject.cli.net.ConnectivityIntentCommand.key () protected
Creates a key for an intent based on command line arguments.
If a key has been specified, it is returned. If no key is specified, null is returned.
Returns
intent key if specified, null otherwise
Definition at line 417 of file ConnectivityIntentCommand.java.
References org.onosproject.cli.net.ConnectivityIntentCommand.appId().
int org.onosproject.cli.net.ConnectivityIntentCommand.priority () protected
Gets the priority to use for the intent.
Returns
priority
Definition at line 432 of file ConnectivityIntentCommand.java.
The documentation for this class was generated from the following file:
cli/src/main/java/org/onosproject/cli/net/ConnectivityIntentCommand.java