onos: org.onosproject.pim.impl.PIMPacketHandler.PIMPacketProcessor Class Reference
org.onosproject.pim.impl.PIMPacketHandler.PIMPacketProcessor Class Reference
Packet processor responsible for handling IGMP packets.
Public Member Functions
void process (PacketContext context)
Processes the inbound packet as specified in the given context.
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.net.packet.PacketProcessor
static int advisor (int priority)
Returns a priority in the ADVISOR range, where processors can take early action and influence the packet context.
static int director (int priority)
Returns a priority in the DIRECTOR range, where processors can handle the packet.
static int observer (int priority)
Returns a priority in the OBSERVER range, where processors cannot take any action, but can observe what action has been taken until then.
Public Attributes inherited from org.onosproject.net.packet.PacketProcessor
int ADVISOR_MAX = Integer.MAX_VALUE / 3
int DIRECTOR_MAX = (Integer.MAX_VALUE / 3) * 2
int OBSERVER_MAX = Integer.MAX_VALUE
Detailed Description
Packet processor responsible for handling IGMP packets.
Definition at line 98 of file PIMPacketHandler.java.
Member Function Documentation
void org.onosproject.pim.impl.PIMPacketHandler.PIMPacketProcessor.process (PacketContext context)
Processes the inbound packet as specified in the given context.
Parameters
context packet processing context
Implements org.onosproject.net.packet.PacketProcessor.
Definition at line 102 of file PIMPacketHandler.java.
References org.onlab.packet.Ethernet.getEtherType(), org.onlab.packet.BasePacket.getPayload(), org.onlab.packet.IPv4.getProtocol(), org.onosproject.net.packet.PacketContext.inPacket(), org.onosproject.net.packet.PacketContext.isHandled(), org.onlab.packet.IPv4.PROTOCOL_PIM, org.onlab.packet.IpAddress.toString(), and org.onlab.packet.Ethernet.TYPE_IPV4.
The documentation for this class was generated from the following file:
apps/pim/src/main/java/org/onosproject/pim/impl/PIMPacketHandler.java