onos: org.onosproject.net.OmsPort Class Reference
org.onosproject.net.OmsPort Class Reference
Implementation of OMS port (Optical Multiplexing Section).
Public Member Functions
OmsPort (Element element, PortNumber number, boolean isEnabled, Frequency minFrequency, Frequency maxFrequency, Frequency grid, Annotations...annotations)
Creates an OMS port in the specified network element.
short totalChannels ()
Returns the total number of channels on the port.
Frequency minFrequency ()
Returns the minimum frequency.
Frequency maxFrequency ()
Returns the maximum frequency.
Frequency grid ()
Returns the grid spacing frequency.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.DefaultPort
DefaultPort (Element element, PortNumber number, boolean isEnabled, Annotations...annotations)
Creates a network element attributed to the specified provider.
DefaultPort (Element element, PortNumber number, boolean isEnabled, Type type, long portSpeed, Annotations...annotations)
Creates a network element attributed to the specified provider.
Element element ()
Returns the parent network element to which this port belongs.
PortNumber number ()
Returns the port number.
boolean isEnabled ()
Indicates whether or not the port is currently up and active.
Type type ()
Returns the port type.
long portSpeed ()
Returns the current port speed in Mbps.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Static Public Attributes inherited from org.onosproject.net.DefaultPort
static final long DEFAULT_SPEED = 1_000
Default port speed in Mbps.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Implementation of OMS port (Optical Multiplexing Section).
Also referred to as a WDM port or W-port. See ITU G.709 "Interfaces for the Optical Transport Network (OTN)"
Assumes we only support fixed grid for now.
Definition at line 31 of file OmsPort.java.
Constructor & Destructor Documentation
org.onosproject.net.OmsPort.OmsPort (Element element, PortNumber number, boolean isEnabled, Frequency minFrequency, Frequency maxFrequency, Frequency grid, Annotations... annotations)
Creates an OMS port in the specified network element.
Parameters
element parent network element
number port number
isEnabled port enabled state
minFrequency minimum frequency
maxFrequency maximum frequency
grid grid spacing frequency
annotations optional key/value annotations
Definition at line 49 of file OmsPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.OmsPort.grid(), org.onosproject.net.OmsPort.maxFrequency(), org.onosproject.net.OmsPort.minFrequency(), and org.onosproject.net.Port.Type.OMS.
Referenced by org.onosproject.net.OmsPort.equals().
Member Function Documentation
boolean org.onosproject.net.OmsPort.equals (Object obj)
Definition at line 101 of file OmsPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultPort.isEnabled(), and org.onosproject.net.OmsPort.OmsPort().
Frequency org.onosproject.net.OmsPort.grid ()
Returns the grid spacing frequency.
Returns
grid spacing frequency
Definition at line 90 of file OmsPort.java.
Referenced by org.onosproject.net.OmsPort.hashCode(), org.onosproject.net.OmsPort.OmsPort(), org.onosproject.net.OmsPort.toString(), and org.onosproject.net.OmsPort.totalChannels().
int org.onosproject.net.OmsPort.hashCode ()
Definition at line 95 of file OmsPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.OmsPort.grid(), org.onosproject.net.DefaultPort.isEnabled(), org.onosproject.net.OmsPort.maxFrequency(), org.onosproject.net.OmsPort.minFrequency(), org.onosproject.net.DefaultPort.number(), and org.onosproject.net.DefaultPort.type().
Frequency org.onosproject.net.OmsPort.maxFrequency ()
Returns the maximum frequency.
Returns
maximum frequency
Definition at line 81 of file OmsPort.java.
Referenced by org.onosproject.net.OmsPort.hashCode(), org.onosproject.net.OmsPort.OmsPort(), and org.onosproject.net.OmsPort.toString().
Frequency org.onosproject.net.OmsPort.minFrequency ()
Returns the minimum frequency.
Returns
minimum frequency
Definition at line 72 of file OmsPort.java.
Referenced by org.onosproject.net.OmsPort.hashCode(), org.onosproject.net.OmsPort.OmsPort(), org.onosproject.net.OmsPort.toString(), and org.onosproject.net.OmsPort.totalChannels().
String org.onosproject.net.OmsPort.toString ()
Definition at line 119 of file OmsPort.java.
References org.onosproject.net.DefaultPort.element(), org.onosproject.net.OmsPort.grid(), org.onosproject.net.DefaultPort.isEnabled(), org.onosproject.net.OmsPort.maxFrequency(), org.onosproject.net.OmsPort.minFrequency(), org.onosproject.net.DefaultPort.number(), and org.onosproject.net.DefaultPort.type().
short org.onosproject.net.OmsPort.totalChannels ()
Returns the total number of channels on the port.
Returns
total number of channels
Definition at line 62 of file OmsPort.java.
References org.onlab.util.Frequency.asHz(), org.onosproject.net.OmsPort.grid(), and org.onosproject.net.OmsPort.minFrequency().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/OmsPort.java