onos: org.onosproject.net.packet.DefaultOutboundPacket Class Reference
org.onosproject.net.packet.DefaultOutboundPacket Class Reference
Default implementation of an immutable outbound packet.
Public Member Functions
DefaultOutboundPacket (DeviceId sendThrough, TrafficTreatment treatment, ByteBuffer data)
Creates an immutable outbound packet.
DeviceId sendThrough ()
Returns the identity of a device through which this packet should be sent.
TrafficTreatment treatment ()
Returns how the outbound packet should be treated.
ByteBuffer data ()
Returns immutable view of the raw data to be sent.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of an immutable outbound packet.
Definition at line 29 of file DefaultOutboundPacket.java.
Constructor & Destructor Documentation
org.onosproject.net.packet.DefaultOutboundPacket.DefaultOutboundPacket (DeviceId sendThrough, TrafficTreatment treatment, ByteBuffer data)
Creates an immutable outbound packet.
Parameters
sendThrough identifier through which to send the packet
treatment list of packet treatments
data raw packet data
Definition at line 41 of file DefaultOutboundPacket.java.
References org.onosproject.net.packet.DefaultOutboundPacket.data(), org.onosproject.net.packet.DefaultOutboundPacket.sendThrough(), and org.onosproject.net.packet.DefaultOutboundPacket.treatment().
Referenced by org.onosproject.net.packet.DefaultOutboundPacket.equals().
Member Function Documentation
ByteBuffer org.onosproject.net.packet.DefaultOutboundPacket.data ()
Returns immutable view of the raw data to be sent.
Returns
data to emit
Implements org.onosproject.net.packet.OutboundPacket.
Definition at line 59 of file DefaultOutboundPacket.java.
Referenced by org.onosproject.net.packet.DefaultOutboundPacket.DefaultOutboundPacket(), and org.onosproject.net.packet.DefaultOutboundPacket.hashCode().
boolean org.onosproject.net.packet.DefaultOutboundPacket.equals (Object obj)
Definition at line 70 of file DefaultOutboundPacket.java.
References org.onosproject.net.packet.DefaultOutboundPacket.DefaultOutboundPacket(), and org.onosproject.net.packet.DefaultOutboundPacket.equals().
Referenced by org.onosproject.net.packet.DefaultOutboundPacket.equals().
int org.onosproject.net.packet.DefaultOutboundPacket.hashCode ()
Definition at line 65 of file DefaultOutboundPacket.java.
References org.onosproject.net.packet.DefaultOutboundPacket.data(), org.onosproject.net.packet.DefaultOutboundPacket.sendThrough(), and org.onosproject.net.packet.DefaultOutboundPacket.treatment().
DeviceId org.onosproject.net.packet.DefaultOutboundPacket.sendThrough ()
Returns the identity of a device through which this packet should be sent.
Returns
device identity
Implements org.onosproject.net.packet.OutboundPacket.
Definition at line 49 of file DefaultOutboundPacket.java.
Referenced by org.onosproject.net.packet.DefaultOutboundPacket.DefaultOutboundPacket(), org.onosproject.net.packet.DefaultOutboundPacket.hashCode(), and org.onosproject.net.packet.DefaultOutboundPacket.toString().
String org.onosproject.net.packet.DefaultOutboundPacket.toString ()
Definition at line 83 of file DefaultOutboundPacket.java.
References org.onosproject.net.packet.DefaultOutboundPacket.sendThrough(), and org.onosproject.net.packet.DefaultOutboundPacket.treatment().
TrafficTreatment org.onosproject.net.packet.DefaultOutboundPacket.treatment ()
Returns how the outbound packet should be treated.
Returns
output treatment
Implements org.onosproject.net.packet.OutboundPacket.
Definition at line 54 of file DefaultOutboundPacket.java.
Referenced by org.onosproject.net.packet.DefaultOutboundPacket.DefaultOutboundPacket(), org.onosproject.net.packet.DefaultOutboundPacket.hashCode(), and org.onosproject.net.packet.DefaultOutboundPacket.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/packet/DefaultOutboundPacket.java