onos: org.onosproject.vtnweb.web.SubnetCodec Class Reference
org.onosproject.vtnweb.web.SubnetCodec Class Reference
Subnet JSON codec.
Public Member Functions
ObjectNode encode (Subnet subnet, CodecContext context)
Detailed Description
Subnet JSON codec.
Definition at line 29 of file SubnetCodec.java.
Member Function Documentation
ObjectNode org.onosproject.vtnweb.web.SubnetCodec.encode (Subnet subnet, CodecContext context)
Definition at line 31 of file SubnetCodec.java.
References org.onosproject.vtnrsc.Subnet.dhcpEnabled(), org.onosproject.vtnrsc.Subnet.gatewayIp(), org.onosproject.vtnrsc.Subnet.ipV6AddressMode(), org.onosproject.vtnrsc.Subnet.ipV6RaMode(), org.onosproject.vtnrsc.Subnet.ipVersion(), org.onosproject.vtnrsc.Subnet.shared(), org.onosproject.vtnrsc.Subnet.subnetName(), and org.onosproject.vtnrsc.Subnet.tenantId().
The documentation for this class was generated from the following file:
apps/vtn/vtnweb/src/main/java/org/onosproject/vtnweb/web/SubnetCodec.java