onos: org.onosproject.net.link.impl.BasicLinkOperator Class Reference
org.onosproject.net.link.impl.BasicLinkOperator Class Reference
Implementations of merge policies for various sources of link configuration information.
Static Public Member Functions
static LinkDescription combine (BasicLinkConfig cfg, LinkDescription descr)
Generates a LinkDescription containing fields from a LinkDescription and a LinkConfig.
static SparseAnnotations combine (BasicLinkConfig cfg, SparseAnnotations an)
Generates an annotation from an existing annotation and LinkConfig.
static LinkDescription descriptionOf (ConnectPoint src, ConnectPoint dst, Link link)
Generates a link description from a link description entity.
static LinkDescription descriptionOf (ConnectPoint src, ConnectPoint dst, BasicLinkConfig link)
Generates a link description from a link config entity.
Detailed Description
Implementations of merge policies for various sources of link configuration information.
This includes applications, provides, and network configurations.
Definition at line 38 of file BasicLinkOperator.java.
Member Function Documentation
static LinkDescription org.onosproject.net.link.impl.BasicLinkOperator.combine (BasicLinkConfig cfg, LinkDescription descr) static
Generates a LinkDescription containing fields from a LinkDescription and a LinkConfig.
Parameters
cfg the link config entity from network config
descr a LinkDescription
Returns
LinkDescription based on both sources
Definition at line 55 of file BasicLinkOperator.java.
References org.onosproject.net.Description.annotations(), org.onosproject.net.link.LinkDescription.src(), and org.onosproject.net.config.basics.BasicLinkConfig.type().
Referenced by org.onosproject.net.link.impl.BasicLinkOperator.descriptionOf().
static SparseAnnotations org.onosproject.net.link.impl.BasicLinkOperator.combine (BasicLinkConfig cfg, SparseAnnotations an) static
Generates an annotation from an existing annotation and LinkConfig.
Parameters
cfg the link config entity from network config
an the annotation
Returns
annotation combining both sources
Definition at line 78 of file BasicLinkOperator.java.
References org.onosproject.net.config.basics.BasicLinkConfig.bandwidth(), org.onosproject.net.AnnotationKeys.BANDWIDTH, org.onosproject.net.AnnotationKeys.DURABLE, org.onosproject.net.config.basics.BasicLinkConfig.isDurable(), org.onosproject.net.config.basics.BasicLinkConfig.latency(), and org.onosproject.net.AnnotationKeys.LATENCY.
static LinkDescription org.onosproject.net.link.impl.BasicLinkOperator.descriptionOf (ConnectPoint src, ConnectPoint dst, Link link) static
Generates a link description from a link description entity.
The endpoints must be specified to indicate directionality.
Parameters
src the source ConnectPoint
dst the destination ConnectPoint
link the link config entity
Returns
a linkDescription based on the config
Definition at line 101 of file BasicLinkOperator.java.
References org.onosproject.net.Annotated.annotations(), and org.onosproject.net.Link.type().
static LinkDescription org.onosproject.net.link.impl.BasicLinkOperator.descriptionOf (ConnectPoint src, ConnectPoint dst, BasicLinkConfig link) static
Generates a link description from a link config entity.
This is for links that cannot be discovered and has to be injected. The endpoints must be specified to indicate directionality.
Parameters
src the source ConnectPoint
dst the destination ConnectPoint
link the link config entity
Returns
a linkDescription based on the config
Definition at line 120 of file BasicLinkOperator.java.
References org.onosproject.net.link.impl.BasicLinkOperator.combine(), org.onosproject.net.DefaultAnnotations.EMPTY, and org.onosproject.net.config.basics.BasicLinkConfig.type().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/link/impl/BasicLinkOperator.java