onos: org.onosproject.pcepio.types.NodeFlagBitsTlv Class Reference
org.onosproject.pcepio.types.NodeFlagBitsTlv Class Reference
Provide node Flags bits.
Public Member Functions
NodeFlagBitsTlv (byte rawValue)
constructor to initialize rawValue.
NodeFlagBitsTlv (boolean bOFlag, boolean bTFlag, boolean bEFlag, boolean bBFlag)
constructor to initialize different Flags.
byte getbyte ()
Returns raw value of NodeFlagBitsTlv.
boolean getOFlag ()
Returns O-flag.
boolean getTFlag ()
Returns T-flag.
boolean getEFlag ()
Returns E-flag.
boolean getBFlag ()
Returns B-flag.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static NodeFlagBitsTlv of (final byte raw)
Returns newly created NodeFlagBitsTlv object.
static PcepValueType read (ChannelBuffer c)
Reads the channel buffer and returns object of NodeFlagBitsTlv.
Static Public Attributes
static final short TYPE = 14
static final short LENGTH = 1
static final int SET = 1
static final byte OFLAG_SET = (byte) 0x80
static final byte TFLAG_SET = 0x40
static final byte EFLAG_SET = 0x20
static final byte BFLAG_SET = 0x10
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(NodeFlagBitsTlv.class)
Detailed Description
Provide node Flags bits.
Definition at line 29 of file NodeFlagBitsTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.NodeFlagBitsTlv.NodeFlagBitsTlv (byte rawValue)
constructor to initialize rawValue.
Parameters
rawValue of Node Flag Bits TLV
Definition at line 63 of file NodeFlagBitsTlv.java.
References org.onosproject.pcepio.types.NodeFlagBitsTlv.BFLAG_SET, org.onosproject.pcepio.types.NodeFlagBitsTlv.EFLAG_SET, org.onosproject.pcepio.types.NodeFlagBitsTlv.OFLAG_SET, and org.onosproject.pcepio.types.NodeFlagBitsTlv.TFLAG_SET.
Referenced by org.onosproject.pcepio.types.NodeFlagBitsTlv.equals(), and org.onosproject.pcepio.types.NodeFlagBitsTlv.of().
org.onosproject.pcepio.types.NodeFlagBitsTlv.NodeFlagBitsTlv (boolean bOFlag, boolean bTFlag, boolean bEFlag, boolean bBFlag)
constructor to initialize different Flags.
Parameters
bOFlag O-flag
bTFlag T-flag
bEFlag E-flag
bBFlag B-flag
Definition at line 80 of file NodeFlagBitsTlv.java.
Member Function Documentation
boolean org.onosproject.pcepio.types.NodeFlagBitsTlv.equals (Object obj)
Definition at line 169 of file NodeFlagBitsTlv.java.
References org.onosproject.pcepio.types.NodeFlagBitsTlv.NodeFlagBitsTlv().
boolean org.onosproject.pcepio.types.NodeFlagBitsTlv.getBFlag ()
Returns B-flag.
Returns
bBFlag B-flag
Definition at line 140 of file NodeFlagBitsTlv.java.
byte org.onosproject.pcepio.types.NodeFlagBitsTlv.getbyte ()
Returns raw value of NodeFlagBitsTlv.
Returns
rawValue raw value
Definition at line 104 of file NodeFlagBitsTlv.java.
boolean org.onosproject.pcepio.types.NodeFlagBitsTlv.getEFlag ()
Returns E-flag.
Returns
bEFlag E-flag
Definition at line 131 of file NodeFlagBitsTlv.java.
short org.onosproject.pcepio.types.NodeFlagBitsTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 155 of file NodeFlagBitsTlv.java.
References org.onosproject.pcepio.types.NodeFlagBitsTlv.LENGTH.
boolean org.onosproject.pcepio.types.NodeFlagBitsTlv.getOFlag ()
Returns O-flag.
Returns
bOFlag O-flag
Definition at line 113 of file NodeFlagBitsTlv.java.
boolean org.onosproject.pcepio.types.NodeFlagBitsTlv.getTFlag ()
Returns T-flag.
Returns
bTFlag T-flag
Definition at line 122 of file NodeFlagBitsTlv.java.
short org.onosproject.pcepio.types.NodeFlagBitsTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 150 of file NodeFlagBitsTlv.java.
References org.onosproject.pcepio.types.NodeFlagBitsTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.NodeFlagBitsTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 145 of file NodeFlagBitsTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.NodeFlagBitsTlv.hashCode ()
Definition at line 160 of file NodeFlagBitsTlv.java.
static NodeFlagBitsTlv org.onosproject.pcepio.types.NodeFlagBitsTlv.of (final byte raw) static
Returns newly created NodeFlagBitsTlv object.
Parameters
raw of Node Flag Bits TLV
Returns
new object of NodeFlagBitsTlv
Definition at line 95 of file NodeFlagBitsTlv.java.
References org.onosproject.pcepio.types.NodeFlagBitsTlv.NodeFlagBitsTlv().
static PcepValueType org.onosproject.pcepio.types.NodeFlagBitsTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of NodeFlagBitsTlv.
Parameters
c input channel buffer
Returns
object of NodeFlagBitsTlv
Definition at line 217 of file NodeFlagBitsTlv.java.
String org.onosproject.pcepio.types.NodeFlagBitsTlv.toString ()
Definition at line 223 of file NodeFlagBitsTlv.java.
References org.onosproject.pcepio.types.NodeFlagBitsTlv.LENGTH, and org.onosproject.pcepio.types.NodeFlagBitsTlv.TYPE.
int org.onosproject.pcepio.types.NodeFlagBitsTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 186 of file NodeFlagBitsTlv.java.
References org.onosproject.pcepio.types.NodeFlagBitsTlv.BFLAG_SET, org.onosproject.pcepio.types.NodeFlagBitsTlv.EFLAG_SET, org.onosproject.pcepio.types.NodeFlagBitsTlv.LENGTH, org.onosproject.pcepio.types.NodeFlagBitsTlv.OFLAG_SET, org.onosproject.pcepio.types.NodeFlagBitsTlv.TFLAG_SET, and org.onosproject.pcepio.types.NodeFlagBitsTlv.TYPE.
Member Data Documentation
final byte org.onosproject.pcepio.types.NodeFlagBitsTlv.BFLAG_SET = 0x10 static
Definition at line 49 of file NodeFlagBitsTlv.java.
Referenced by org.onosproject.pcepio.types.NodeFlagBitsTlv.NodeFlagBitsTlv(), and org.onosproject.pcepio.types.NodeFlagBitsTlv.write().
final byte org.onosproject.pcepio.types.NodeFlagBitsTlv.EFLAG_SET = 0x20 static
Definition at line 48 of file NodeFlagBitsTlv.java.
Referenced by org.onosproject.pcepio.types.NodeFlagBitsTlv.NodeFlagBitsTlv(), and org.onosproject.pcepio.types.NodeFlagBitsTlv.write().
final short org.onosproject.pcepio.types.NodeFlagBitsTlv.LENGTH = 1 static
Definition at line 44 of file NodeFlagBitsTlv.java.
Referenced by org.onosproject.pcepio.types.NodeFlagBitsTlv.getLength(), org.onosproject.pcepio.types.NodeFlagBitsTlv.toString(), and org.onosproject.pcepio.types.NodeFlagBitsTlv.write().
final Logger org.onosproject.pcepio.types.NodeFlagBitsTlv.log = LoggerFactory.getLogger(NodeFlagBitsTlv.class) static protected
Definition at line 41 of file NodeFlagBitsTlv.java.
final byte org.onosproject.pcepio.types.NodeFlagBitsTlv.OFLAG_SET = (byte) 0x80 static
Definition at line 46 of file NodeFlagBitsTlv.java.
Referenced by org.onosproject.pcepio.types.NodeFlagBitsTlv.NodeFlagBitsTlv(), and org.onosproject.pcepio.types.NodeFlagBitsTlv.write().
final int org.onosproject.pcepio.types.NodeFlagBitsTlv.SET = 1 static
Definition at line 45 of file NodeFlagBitsTlv.java.
final byte org.onosproject.pcepio.types.NodeFlagBitsTlv.TFLAG_SET = 0x40 static
Definition at line 47 of file NodeFlagBitsTlv.java.
Referenced by org.onosproject.pcepio.types.NodeFlagBitsTlv.NodeFlagBitsTlv(), and org.onosproject.pcepio.types.NodeFlagBitsTlv.write().
final short org.onosproject.pcepio.types.NodeFlagBitsTlv.TYPE = 14 static
Definition at line 43 of file NodeFlagBitsTlv.java.
Referenced by org.onosproject.pcepio.types.NodeFlagBitsTlv.getType(), org.onosproject.pcepio.types.NodeFlagBitsTlv.toString(), and org.onosproject.pcepio.types.NodeFlagBitsTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/NodeFlagBitsTlv.java