onos: org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline Class Reference
org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline Class Reference
Driver for software switch emulation of the OFDPA 2.0 pipeline.
Protected Member Functions
List< FlowRule > processVlanIdFilter (PortCriterion portCriterion, VlanIdCriterion vidCriterion, VlanId assignedVlan, ApplicationId applicationId)
Collection< FlowRule > processSpecific (ForwardingObjective fwd)
void initializePipeline ()
void processPortTable ()
void processTmacTable ()
void processIpTable ()
void processMplsTable ()
void processAclTable ()
Protected Member Functions inherited from org.onosproject.driver.pipeline.OFDPA2Pipeline
void initializePipeline ()
List< FlowRule > processVlanIdFilter (PortCriterion portCriterion, VlanIdCriterion vidCriterion, VlanId assignedVlan, ApplicationId applicationId)
Allows untagged packets into pipeline by assigning a vlan id.
List< FlowRule > processEthDstFilter (PortCriterion portCriterion, EthCriterion ethCriterion, VlanIdCriterion vidCriterion, VlanId assignedVlan, ApplicationId applicationId)
Allows routed packets with correct destination MAC to be directed to unicast-IP routing table or MPLS forwarding table.
Collection< FlowRule > processSpecific (ForwardingObjective fwd)
In the OF-DPA 2.0 pipeline, specific forwarding refers to the IP table (unicast or multicast) or the L2 table (mac + vlan) or the MPLS table.
void fail (Objective obj, ObjectiveError error)
void processGroupTable ()
void processMplsTable ()
void processPortTable ()
void processTmacTable ()
void processIpTable ()
void processAclTable ()
Additional Inherited Members
Public Member Functions inherited from org.onosproject.driver.pipeline.OFDPA2Pipeline
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filteringObjective)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
void processStaticFlows ()
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Protected Attributes inherited from org.onosproject.driver.pipeline.OFDPA2Pipeline
FlowRuleService flowRuleService
GroupService groupService
FlowObjectiveStore flowObjectiveStore
DeviceId deviceId
ApplicationId driverId
PacketService packetService
DeviceService deviceService
KryoNamespace appKryo
Static Protected Attributes inherited from org.onosproject.driver.pipeline.OFDPA2Pipeline
static final int PORT_TABLE = 0
static final int VLAN_TABLE = 10
static final int TMAC_TABLE = 20
static final int UNICAST_ROUTING_TABLE = 30
static final int MULTICAST_ROUTING_TABLE = 40
static final int MPLS_TABLE_0 = 23
static final int MPLS_TABLE_1 = 24
static final int BRIDGING_TABLE = 50
static final int ACL_TABLE = 60
static final int MAC_LEARNING_TABLE = 254
static final long OFPP_MAX = 0xffffff00L
static final int DEFAULT_PRIORITY = 0x8000
static final int LOWEST_PRIORITY = 0x0
Detailed Description
Driver for software switch emulation of the OFDPA 2.0 pipeline.
The software switch is the CPqD OF 1.3 switch.
Definition at line 61 of file CpqdOFDPA2Pipeline.java.
Member Function Documentation
void org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.initializePipeline () protected
Definition at line 202 of file CpqdOFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processAclTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processIpTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processMplsTable(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processPortTable(), and org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processTmacTable().
void org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processAclTable () protected
Definition at line 378 of file CpqdOFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.ACL_TABLE, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.driverId, and org.onosproject.driver.pipeline.OFDPA2Pipeline.LOWEST_PRIORITY.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.initializePipeline().
void org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processIpTable () protected
Definition at line 274 of file CpqdOFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.ACL_TABLE, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.driverId, org.onosproject.driver.pipeline.OFDPA2Pipeline.LOWEST_PRIORITY, and org.onosproject.driver.pipeline.OFDPA2Pipeline.UNICAST_ROUTING_TABLE.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.initializePipeline().
void org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processMplsTable () protected
Definition at line 305 of file CpqdOFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.ACL_TABLE, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.driverId, org.onosproject.driver.pipeline.OFDPA2Pipeline.LOWEST_PRIORITY, org.onosproject.driver.pipeline.OFDPA2Pipeline.MPLS_TABLE_0, and org.onosproject.driver.pipeline.OFDPA2Pipeline.MPLS_TABLE_1.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.initializePipeline().
void org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processPortTable () protected
Definition at line 214 of file CpqdOFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.driverId, org.onosproject.driver.pipeline.OFDPA2Pipeline.LOWEST_PRIORITY, org.onosproject.driver.pipeline.OFDPA2Pipeline.PORT_TABLE, and org.onosproject.driver.pipeline.OFDPA2Pipeline.VLAN_TABLE.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.initializePipeline().
Collection<FlowRule> org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific (ForwardingObjective fwd) protected
Definition at line 126 of file CpqdOFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.ACL_TABLE, org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.fail(), org.onosproject.net.flow.TrafficSelector.getCriterion(), org.onosproject.net.flowobjective.ObjectiveError.GROUPMISSING, org.onosproject.net.group.Group.id(), org.onosproject.driver.pipeline.OFDPA2Pipeline.MPLS_TABLE_1, org.onlab.packet.Ethernet.MPLS_UNICAST, org.onosproject.driver.pipeline.OFDPA2Pipeline.next(), org.onosproject.net.flowobjective.ForwardingObjective.nextId(), org.onosproject.net.flowobjective.Objective.permanent(), org.onosproject.net.flowobjective.Objective.priority(), org.onosproject.net.flowobjective.ForwardingObjective.treatment(), org.onlab.packet.Ethernet.TYPE_IPV4, org.onosproject.driver.pipeline.OFDPA2Pipeline.UNICAST_ROUTING_TABLE, and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
void org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processTmacTable () protected
Definition at line 243 of file CpqdOFDPA2Pipeline.java.
References org.onosproject.driver.pipeline.OFDPA2Pipeline.BRIDGING_TABLE, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.driverId, org.onosproject.driver.pipeline.OFDPA2Pipeline.LOWEST_PRIORITY, and org.onosproject.driver.pipeline.OFDPA2Pipeline.TMAC_TABLE.
Referenced by org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.initializePipeline().
List<FlowRule> org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processVlanIdFilter (PortCriterion portCriterion, VlanIdCriterion vidCriterion, VlanId assignedVlan, ApplicationId applicationId) protected
Definition at line 66 of file CpqdOFDPA2Pipeline.java.
References org.onosproject.net.PortNumber.ALL, org.onosproject.driver.pipeline.OFDPA2Pipeline.DEFAULT_PRIORITY, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceId, org.onosproject.driver.pipeline.OFDPA2Pipeline.deviceService, org.onosproject.net.device.DeviceService.getPorts(), org.onlab.packet.VlanId.NONE, org.onosproject.driver.pipeline.OFDPA2Pipeline.OFPP_MAX, obeliskHostCheck.port, org.onosproject.driver.pipeline.OFDPA2Pipeline.TMAC_TABLE, and org.onosproject.driver.pipeline.OFDPA2Pipeline.VLAN_TABLE.
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/pipeline/CpqdOFDPA2Pipeline.java