onos: org.onosproject.net.device.DefaultPortStatisticsTest Class Reference
org.onosproject.net.device.DefaultPortStatisticsTest Class Reference
DefaultPortStatistics unit tests.
Public Member Functions
void testImmutability ()
Checks that the GroupOperation class is immutable.
void testConstruction ()
void testEquals ()
Tests the equals, hashCode and toString methods using Guava EqualsTester.
void testSerializerConstructor ()
Tests that the empty argument list constructor for serialization is present and creates a proper object.
Detailed Description
DefaultPortStatistics unit tests.
Definition at line 35 of file DefaultPortStatisticsTest.java.
Member Function Documentation
void org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction ()
Definition at line 76 of file DefaultPortStatisticsTest.java.
References org.onosproject.net.device.PortStatistics.bytesReceived(), org.onosproject.net.device.PortStatistics.bytesSent(), org.onosproject.net.device.PortStatistics.durationNano(), org.onosproject.net.device.PortStatistics.durationSec(), org.onosproject.net.device.PortStatistics.packetsReceived(), org.onosproject.net.device.PortStatistics.packetsRxDropped(), org.onosproject.net.device.PortStatistics.packetsRxErrors(), org.onosproject.net.device.PortStatistics.packetsSent(), org.onosproject.net.device.PortStatistics.packetsTxDropped(), org.onosproject.net.device.PortStatistics.packetsTxErrors(), and org.onosproject.net.device.PortStatistics.port().
void org.onosproject.net.device.DefaultPortStatisticsTest.testEquals ()
Tests the equals, hashCode and toString methods using Guava EqualsTester.
Definition at line 94 of file DefaultPortStatisticsTest.java.
void org.onosproject.net.device.DefaultPortStatisticsTest.testImmutability ()
Checks that the GroupOperation class is immutable.
Definition at line 71 of file DefaultPortStatisticsTest.java.
void org.onosproject.net.device.DefaultPortStatisticsTest.testSerializerConstructor ()
Tests that the empty argument list constructor for serialization is present and creates a proper object.
Definition at line 106 of file DefaultPortStatisticsTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/device/DefaultPortStatisticsTest.java