onos: org.onosproject.driver.pipeline.SpringOpenTTPDell Class Reference
org.onosproject.driver.pipeline.SpringOpenTTPDell Class Reference
Spring-open driver implementation for Dell hardware switches.
Public Member Functions
SpringOpenTTPDell ()
Public Member Functions inherited from org.onosproject.driver.pipeline.SpringOpenTTP
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filteringObjective)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Protected Member Functions
void setTableMissEntries ()
Collection< FlowRule > processSpecific (ForwardingObjective fwd)
List< FlowRule > processEthDstFilter (EthCriterion ethCriterion, VlanIdCriterion vlanIdCriterion, FilteringObjective filt, VlanId assignedVlan, ApplicationId applicationId)
List< FlowRule > processVlanIdFilter (VlanIdCriterion vlanIdCriterion, FilteringObjective filt, VlanId assignedVlan, ApplicationId applicationId)
Protected Member Functions inherited from org.onosproject.driver.pipeline.SpringOpenTTP
Collection< FlowRule > processSpecific (ForwardingObjective fwd)
Collection< FlowRule > processEthTypeSpecificObjective (ForwardingObjective fwd)
Collection< FlowRule > processEthDstSpecificObjective (ForwardingObjective fwd)
List< FlowRule > processEthDstFilter (EthCriterion ethCriterion, VlanIdCriterion vlanIdCriterion, FilteringObjective filt, VlanId assignedVlan, ApplicationId applicationId)
List< FlowRule > processVlanIdFilter (VlanIdCriterion vlanIdCriterion, FilteringObjective filt, VlanId assignedVlan, ApplicationId applicationId)
void setTableMissEntries ()
void populateTableMissEntry (int tableToAdd, boolean toControllerNow, boolean toControllerWrite, boolean toTable, int tableToSend)
void fail (Objective obj, ObjectiveError error)
Additional Inherited Members
Protected Attributes inherited from org.onosproject.driver.pipeline.SpringOpenTTP
int vlanTableId = TABLE_VLAN
Set the default values.
int tmacTableId = TABLE_TMAC
int ipv4UnicastTableId = TABLE_IPV4_UNICAST
int mplsTableId = TABLE_MPLS
int dstMacTableId = TABLE_DMAC
int aclTableId = TABLE_ACL
int srcMacTableId = TABLE_SMAC
final Logger log = getLogger(getClass())
GroupService groupService
FlowObjectiveStore flowObjectiveStore
DeviceId deviceId
KryoNamespace appKryo
Detailed Description
Spring-open driver implementation for Dell hardware switches.
Definition at line 49 of file SpringOpenTTPDell.java.
Constructor & Destructor Documentation
org.onosproject.driver.pipeline.SpringOpenTTPDell.SpringOpenTTPDell ()
Definition at line 61 of file SpringOpenTTPDell.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.aclTableId, org.onosproject.driver.pipeline.SpringOpenTTP.ipv4UnicastTableId, org.onosproject.driver.pipeline.SpringOpenTTP.mplsTableId, org.onosproject.driver.pipeline.SpringOpenTTP.tmacTableId, and org.onosproject.driver.pipeline.SpringOpenTTP.vlanTableId.
Member Function Documentation
List<FlowRule> org.onosproject.driver.pipeline.SpringOpenTTPDell.processEthDstFilter (EthCriterion ethCriterion, VlanIdCriterion vlanIdCriterion, FilteringObjective filt, VlanId assignedVlan, ApplicationId applicationId) protected
Definition at line 180 of file SpringOpenTTPDell.java.
Collection<FlowRule> org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific (ForwardingObjective fwd) protected
Definition at line 80 of file SpringOpenTTPDell.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.aclTableId, org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.driver.pipeline.SpringOpenTTP.deviceId, org.onosproject.net.flowobjective.ObjectiveError.DEVICEMISSING, org.onosproject.driver.pipeline.SpringOpenTTP.fail(), org.onosproject.net.flowobjective.ObjectiveError.GROUPMISSING, org.onosproject.driver.pipeline.SpringOpenTTP.ipv4UnicastTableId, org.onlab.packet.Ethernet.MPLS_UNICAST, org.onosproject.driver.pipeline.SpringOpenTTP.mplsTableId, org.onosproject.driver.pipeline.SpringOpenTTP.next(), org.onosproject.net.flowobjective.ForwardingObjective.nextId(), org.onosproject.net.flowobjective.Objective.permanent(), org.onosproject.net.flowobjective.Objective.priority(), org.onosproject.net.flowobjective.ForwardingObjective.treatment(), org.onlab.packet.Ethernet.TYPE_IPV4, and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
List<FlowRule> org.onosproject.driver.pipeline.SpringOpenTTPDell.processVlanIdFilter (VlanIdCriterion vlanIdCriterion, FilteringObjective filt, VlanId assignedVlan, ApplicationId applicationId) protected
Definition at line 195 of file SpringOpenTTPDell.java.
void org.onosproject.driver.pipeline.SpringOpenTTPDell.setTableMissEntries () protected
Definition at line 71 of file SpringOpenTTPDell.java.
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/pipeline/SpringOpenTTPDell.java