onos: org.onosproject.core.DefaultApplication Class Reference
org.onosproject.core.DefaultApplication Class Reference
Default implementation of network control/management application descriptor.
Public Member Functions
DefaultApplication (ApplicationId appId, Version version, String description, String origin, ApplicationRole role, Set< Permission > permissions, Optional< URI > featuresRepo, List< String > features, List< String > requiredApps)
Creates a new application descriptor using the supplied data.
ApplicationId id ()
Returns the application name id.
Version version ()
Returns the application version.
String description ()
Returns description of the application.
String origin ()
Returns the name of the application origin, group or company.
ApplicationRole role ()
Returns the role of the application.
Set< Permission > permissions ()
Returns the permissions requested by the application.
Optional< URI > featuresRepo ()
Returns the feature repository URI.
List< String > features ()
Returns the list of features comprising the application.
List< String > requiredApps ()
Returns list of required application names.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of network control/management application descriptor.
Definition at line 33 of file DefaultApplication.java.
Constructor & Destructor Documentation
org.onosproject.core.DefaultApplication.DefaultApplication (ApplicationId appId, Version version, String description, String origin, ApplicationRole role, Set< Permission > permissions, Optional< URI > featuresRepo, List< String > features, List< String > requiredApps)
Creates a new application descriptor using the supplied data.
Parameters
appId application identifier
version application version
description application description
origin origin company
role application role
permissions requested permissions
featuresRepo optional features repo URI
features application features
requiredApps list of required application names
Definition at line 58 of file DefaultApplication.java.
Referenced by org.onosproject.core.DefaultApplication.equals().
Member Function Documentation
String org.onosproject.core.DefaultApplication.description ()
Returns description of the application.
Returns
application description text
Implements org.onosproject.core.Application.
Definition at line 86 of file DefaultApplication.java.
Referenced by org.onosproject.core.DefaultApplication.hashCode(), and org.onosproject.core.DefaultApplication.toString().
boolean org.onosproject.core.DefaultApplication.equals (Object obj)
Definition at line 127 of file DefaultApplication.java.
References org.onosproject.core.DefaultApplication.DefaultApplication(), and org.onosproject.core.DefaultApplication.equals().
Referenced by org.onosproject.core.DefaultApplication.equals().
List<String> org.onosproject.core.DefaultApplication.features ()
Returns the list of features comprising the application.
At least one feature must be given.
Returns
application features
Implements org.onosproject.core.Application.
Definition at line 111 of file DefaultApplication.java.
Referenced by org.onosproject.core.DefaultApplication.hashCode(), and org.onosproject.core.DefaultApplication.toString().
Optional<URI> org.onosproject.core.DefaultApplication.featuresRepo ()
Returns the feature repository URI.
Null value signifies that the application did not provide its own features repository.
Returns
optional feature repo URL
Implements org.onosproject.core.Application.
Definition at line 106 of file DefaultApplication.java.
Referenced by org.onosproject.core.DefaultApplication.hashCode(), and org.onosproject.core.DefaultApplication.toString().
int org.onosproject.core.DefaultApplication.hashCode ()
Definition at line 121 of file DefaultApplication.java.
References org.onosproject.core.DefaultApplication.description(), org.onosproject.core.DefaultApplication.features(), org.onosproject.core.DefaultApplication.featuresRepo(), org.onosproject.core.DefaultApplication.origin(), org.onosproject.core.DefaultApplication.permissions(), org.onosproject.core.DefaultApplication.requiredApps(), org.onosproject.core.DefaultApplication.role(), and org.onosproject.core.DefaultApplication.version().
ApplicationId org.onosproject.core.DefaultApplication.id ()
Returns the application name id.
Returns
application identifier
Implements org.onosproject.core.Application.
Definition at line 76 of file DefaultApplication.java.
String org.onosproject.core.DefaultApplication.origin ()
Returns the name of the application origin, group or company.
Returns
application origin
Implements org.onosproject.core.Application.
Definition at line 91 of file DefaultApplication.java.
Referenced by org.onosproject.core.DefaultApplication.hashCode(), and org.onosproject.core.DefaultApplication.toString().
Set<Permission> org.onosproject.core.DefaultApplication.permissions ()
Returns the permissions requested by the application.
Returns
requested permissions
Implements org.onosproject.core.Application.
Definition at line 101 of file DefaultApplication.java.
Referenced by org.onosproject.core.DefaultApplication.hashCode(), and org.onosproject.core.DefaultApplication.toString().
List<String> org.onosproject.core.DefaultApplication.requiredApps ()
Returns list of required application names.
Returns
list of application names
Implements org.onosproject.core.Application.
Definition at line 116 of file DefaultApplication.java.
Referenced by org.onosproject.core.DefaultApplication.hashCode(), and org.onosproject.core.DefaultApplication.toString().
ApplicationRole org.onosproject.core.DefaultApplication.role ()
Returns the role of the application.
Returns
application role
Implements org.onosproject.core.Application.
Definition at line 96 of file DefaultApplication.java.
Referenced by org.onosproject.core.DefaultApplication.hashCode(), and org.onosproject.core.DefaultApplication.toString().
String org.onosproject.core.DefaultApplication.toString ()
Definition at line 147 of file DefaultApplication.java.
References org.onosproject.core.DefaultApplication.description(), org.onosproject.core.DefaultApplication.features(), org.onosproject.core.DefaultApplication.featuresRepo(), org.onosproject.core.DefaultApplication.origin(), org.onosproject.core.DefaultApplication.permissions(), org.onosproject.core.DefaultApplication.requiredApps(), org.onosproject.core.DefaultApplication.role(), and org.onosproject.core.DefaultApplication.version().
Version org.onosproject.core.DefaultApplication.version ()
Returns the application version.
Returns
application version
Implements org.onosproject.core.Application.
Definition at line 81 of file DefaultApplication.java.
Referenced by org.onosproject.core.DefaultApplication.hashCode(), and org.onosproject.core.DefaultApplication.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/core/DefaultApplication.java