onos: org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion Class Reference
org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion Class Reference
Implementation of IPv6 Neighbor Discovery link-layer address criterion.
Public Member Functions
Type type ()
Returns the type of criterion.
MacAddress mac ()
Gets the MAC link-layer address to match.
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Implementation of IPv6 Neighbor Discovery link-layer address criterion.
Definition at line 27 of file IPv6NDLinkLayerAddressCriterion.java.
Member Function Documentation
boolean org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.equals (Object obj)
Definition at line 69 of file IPv6NDLinkLayerAddressCriterion.java.
References org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.mac(), and obeliskHostCheck.mac.
int org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.hashCode ()
Definition at line 64 of file IPv6NDLinkLayerAddressCriterion.java.
References org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.type().
MacAddress org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.mac ()
Gets the MAC link-layer address to match.
Returns
the MAC link-layer address to match
Definition at line 53 of file IPv6NDLinkLayerAddressCriterion.java.
References obeliskHostCheck.mac.
Referenced by org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.equals(), and org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.toString().
String org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.toString ()
Definition at line 58 of file IPv6NDLinkLayerAddressCriterion.java.
References org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.mac(), and org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.type().
Type org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 44 of file IPv6NDLinkLayerAddressCriterion.java.
Referenced by org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.hashCode(), and org.onosproject.net.flow.criteria.IPv6NDLinkLayerAddressCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/IPv6NDLinkLayerAddressCriterion.java