onos: org.onosproject.pcepio.types.GmplsCapabilityTlv Class Reference
org.onosproject.pcepio.types.GmplsCapabilityTlv Class Reference
Provides GMPLS Capability Tlv.
Public Member Functions
GmplsCapabilityTlv (int rawValue)
Constructor to initialize raw value.
int getInt ()
Returns value of Flags.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static GmplsCapabilityTlv of (final int raw)
Returns newly created GmplsCapabilityTlv object.
static GmplsCapabilityTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of Gmpls-Capability-Tlv.
Static Public Attributes
static final short TYPE = 14
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(GmplsCapabilityTlv.class)
Detailed Description
Provides GMPLS Capability Tlv.
Definition at line 31 of file GmplsCapabilityTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.GmplsCapabilityTlv.GmplsCapabilityTlv (int rawValue)
Constructor to initialize raw value.
Parameters
rawValue of Gmpls-Capability-Tlv
Definition at line 56 of file GmplsCapabilityTlv.java.
Referenced by org.onosproject.pcepio.types.GmplsCapabilityTlv.equals(), and org.onosproject.pcepio.types.GmplsCapabilityTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.GmplsCapabilityTlv.equals (Object obj)
Definition at line 100 of file GmplsCapabilityTlv.java.
References org.onosproject.pcepio.types.GmplsCapabilityTlv.GmplsCapabilityTlv().
int org.onosproject.pcepio.types.GmplsCapabilityTlv.getInt ()
Returns value of Flags.
Returns
rawValue Flags
Definition at line 75 of file GmplsCapabilityTlv.java.
short org.onosproject.pcepio.types.GmplsCapabilityTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 90 of file GmplsCapabilityTlv.java.
References org.onosproject.pcepio.types.GmplsCapabilityTlv.LENGTH.
short org.onosproject.pcepio.types.GmplsCapabilityTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 85 of file GmplsCapabilityTlv.java.
References org.onosproject.pcepio.types.GmplsCapabilityTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.GmplsCapabilityTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 80 of file GmplsCapabilityTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.GmplsCapabilityTlv.hashCode ()
Definition at line 95 of file GmplsCapabilityTlv.java.
static GmplsCapabilityTlv org.onosproject.pcepio.types.GmplsCapabilityTlv.of (final int raw) static
Returns newly created GmplsCapabilityTlv object.
Parameters
raw Flags value
Returns
object of Gmpls-Capability-Tlv
Definition at line 66 of file GmplsCapabilityTlv.java.
References org.onosproject.pcepio.types.GmplsCapabilityTlv.GmplsCapabilityTlv().
static GmplsCapabilityTlv org.onosproject.pcepio.types.GmplsCapabilityTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of Gmpls-Capability-Tlv.
Parameters
c input channel buffer
Returns
object of Gmpls-Capability-Tlv
Definition at line 126 of file GmplsCapabilityTlv.java.
String org.onosproject.pcepio.types.GmplsCapabilityTlv.toString ()
Definition at line 131 of file GmplsCapabilityTlv.java.
References org.onosproject.pcepio.types.GmplsCapabilityTlv.LENGTH, and org.onosproject.pcepio.types.GmplsCapabilityTlv.TYPE.
int org.onosproject.pcepio.types.GmplsCapabilityTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 112 of file GmplsCapabilityTlv.java.
References org.onosproject.pcepio.types.GmplsCapabilityTlv.LENGTH, and org.onosproject.pcepio.types.GmplsCapabilityTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.GmplsCapabilityTlv.LENGTH = 4 static
Definition at line 47 of file GmplsCapabilityTlv.java.
Referenced by org.onosproject.pcepio.types.GmplsCapabilityTlv.getLength(), org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.parseOptionalTlv(), org.onosproject.pcepio.types.GmplsCapabilityTlv.toString(), and org.onosproject.pcepio.types.GmplsCapabilityTlv.write().
final Logger org.onosproject.pcepio.types.GmplsCapabilityTlv.log = LoggerFactory.getLogger(GmplsCapabilityTlv.class) static protected
Definition at line 44 of file GmplsCapabilityTlv.java.
final short org.onosproject.pcepio.types.GmplsCapabilityTlv.TYPE = 14 static
Definition at line 46 of file GmplsCapabilityTlv.java.
Referenced by org.onosproject.pcepio.types.GmplsCapabilityTlv.getType(), org.onosproject.pcepio.types.GmplsCapabilityTlv.toString(), and org.onosproject.pcepio.types.GmplsCapabilityTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/GmplsCapabilityTlv.java