onos: org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv Class Reference
org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv Class Reference
Provides StatefulRsvpErrorSpecTlv.
Public Member Functions
StatefulRsvpErrorSpecTlv (PcepRsvpErrorSpec rsvpErrSpecObj)
Constructor to initialize errSpecObj.
PcepRsvpErrorSpec getPcepRsvpErrorSpec ()
Returns PcepRsvpErrorSpecObject.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static PcepValueType read (ChannelBuffer cb) throws PcepParseException
Reads channel buffer and returns object of StatefulRsvpErrorSpecTlv.
Static Public Attributes
static final short TYPE = 21
static final int OBJECT_HEADER_LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(StatefulRsvpErrorSpecTlv.class)
Detailed Description
Provides StatefulRsvpErrorSpecTlv.
Definition at line 32 of file StatefulRsvpErrorSpecTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.StatefulRsvpErrorSpecTlv (PcepRsvpErrorSpec rsvpErrSpecObj)
Constructor to initialize errSpecObj.
Parameters
rsvpErrSpecObj Rsvp error spec object
Definition at line 116 of file StatefulRsvpErrorSpecTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.equals(), and org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.equals (Object obj)
Definition at line 180 of file StatefulRsvpErrorSpecTlv.java.
References org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.StatefulRsvpErrorSpecTlv().
short org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 141 of file StatefulRsvpErrorSpecTlv.java.
PcepRsvpErrorSpec org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.getPcepRsvpErrorSpec ()
Returns PcepRsvpErrorSpecObject.
Returns
rsvpErrSpecObj
Definition at line 126 of file StatefulRsvpErrorSpecTlv.java.
short org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 136 of file StatefulRsvpErrorSpecTlv.java.
References org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 131 of file StatefulRsvpErrorSpecTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.hashCode ()
Definition at line 175 of file StatefulRsvpErrorSpecTlv.java.
static PcepValueType org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.read (ChannelBuffer cb) throws PcepParseException static
Reads channel buffer and returns object of StatefulRsvpErrorSpecTlv.
Parameters
cb of type channel buffer
Returns
object of StatefulRsvpErrorSpecTlv
Exceptions
PcepParseException while parsing this tlv from channel buffer
Definition at line 152 of file StatefulRsvpErrorSpecTlv.java.
References org.onosproject.pcepio.types.PcepRsvpIpv4ErrorSpec.CLASS_NUM, org.onosproject.pcepio.types.PcepRsvpIpv6ErrorSpec.CLASS_NUM, org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.CLASS_NUM, and org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.StatefulRsvpErrorSpecTlv().
String org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.toString ()
Definition at line 208 of file StatefulRsvpErrorSpecTlv.java.
References org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.TYPE.
int org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 192 of file StatefulRsvpErrorSpecTlv.java.
References org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.OBJECT_HEADER_LENGTH, and org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.TYPE.
Member Data Documentation
final Logger org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.log = LoggerFactory.getLogger(StatefulRsvpErrorSpecTlv.class) static protected
Definition at line 34 of file StatefulRsvpErrorSpecTlv.java.
final int org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.OBJECT_HEADER_LENGTH = 4 static
Definition at line 105 of file StatefulRsvpErrorSpecTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.write().
final short org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.TYPE = 21 static
Definition at line 104 of file StatefulRsvpErrorSpecTlv.java.
Referenced by org.onosproject.pcepio.types.PcepRsvpIpv4ErrorSpec.getType(), org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.getType(), org.onosproject.pcepio.types.PcepRsvpIpv6ErrorSpec.getType(), org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.getType(), org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.toString(), and org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/StatefulRsvpErrorSpecTlv.java