onos: org.onlab.nio.IOLoopTestServer Class Reference
org.onlab.nio.IOLoopTestServer Class Reference
Auxiliary test fixture to measure speed of NIO-based channels.
Public Member Functions
IOLoopTestServer (InetAddress ip, int wc, int ml, int port) throws IOException
Creates a speed server.
void start ()
Start the server IO loops and kicks off throughput tracking.
void stop ()
Stop the server IO loops and freezes throughput tracking.
void report ()
Reports on the accumulated throughput and latency.
int prune ()
Prunes the IO loops of stale message buffers.
Static Public Member Functions
static void main (String[] args) throws IOException
Main entry point to launch the server.
static void startStandalone (String[] args) throws IOException
Starts a standalone IO loop test server.
Detailed Description
Auxiliary test fixture to measure speed of NIO-based channels.
Definition at line 45 of file IOLoopTestServer.java.
Constructor & Destructor Documentation
org.onlab.nio.IOLoopTestServer.IOLoopTestServer (InetAddress ip, int wc, int ml, int port) throws IOException
Creates a speed server.
Parameters
ip optional ip of the adapter where to bind
wc worker count
ml message length in bytes
port listen port
Exceptions
java.io.IOException if unable to create IO loops
Definition at line 118 of file IOLoopTestServer.java.
References obeliskHostCheck.port.
Referenced by org.onlab.nio.IOLoopTestServer.startStandalone().
Member Function Documentation
static void org.onlab.nio.IOLoopTestServer.main (String[] args) throws IOException static
Main entry point to launch the server.
Parameters
args command-line arguments
Exceptions
java.io.IOException if unable to crate IO loops
Definition at line 79 of file IOLoopTestServer.java.
References org.onlab.nio.IOLoopTestServer.startStandalone().
int org.onlab.nio.IOLoopTestServer.prune ()
Prunes the IO loops of stale message buffers.
Returns
number of remaining IO loops among all workers.
Definition at line 181 of file IOLoopTestServer.java.
void org.onlab.nio.IOLoopTestServer.report ()
Reports on the accumulated throughput and latency.
Definition at line 168 of file IOLoopTestServer.java.
References org.onlab.util.Counter.throughput().
void org.onlab.nio.IOLoopTestServer.start ()
Start the server IO loops and kicks off throughput tracking.
Definition at line 132 of file IOLoopTestServer.java.
static void org.onlab.nio.IOLoopTestServer.startStandalone (String[] args) throws IOException static
Starts a standalone IO loop test server.
Parameters
args command-line arguments
Definition at line 89 of file IOLoopTestServer.java.
References org.onlab.nio.IOLoopTestServer.IOLoopTestServer().
Referenced by org.onlab.nio.IOLoopTestServer.main().
void org.onlab.nio.IOLoopTestServer.stop ()
Stop the server IO loops and freezes throughput tracking.
Definition at line 150 of file IOLoopTestServer.java.
The documentation for this class was generated from the following file:
utils/nio/src/test/java/org/onlab/nio/IOLoopTestServer.java