onos: org.onlab.packet.TCPTest Class Reference
org.onlab.packet.TCPTest Class Reference
Tests for class TCP.
Public Member Functions
void testSerialize ()
Tests serialize and setters.
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws Exception
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class TCP.
Definition at line 33 of file TCPTest.java.
Member Function Documentation
static void org.onlab.packet.TCPTest.setUpBeforeClass () throws Exception static
Definition at line 73 of file TCPTest.java.
References org.onlab.packet.IPv4.PROTOCOL_TCP, and org.onlab.packet.IPv6.PROTOCOL_TCP.
void org.onlab.packet.TCPTest.testDeserialize () throws Exception
Tests deserialize and getters.
Definition at line 121 of file TCPTest.java.
References org.onlab.packet.TCP.getAcknowledge(), org.onlab.packet.TCP.getChecksum(), org.onlab.packet.TCP.getDataOffset(), org.onlab.packet.TCP.getDestinationPort(), org.onlab.packet.TCP.getFlags(), org.onlab.packet.TCP.getSequence(), org.onlab.packet.TCP.getSourcePort(), org.onlab.packet.TCP.getUrgentPointer(), org.onlab.packet.TCP.getWindowSize(), and find-link-in-cluster.length.
void org.onlab.packet.TCPTest.testDeserializeBadInput () throws Exception
Definition at line 108 of file TCPTest.java.
void org.onlab.packet.TCPTest.testDeserializeTruncated () throws Exception
Definition at line 113 of file TCPTest.java.
void org.onlab.packet.TCPTest.testEqual ()
Tests comparator.
Definition at line 139 of file TCPTest.java.
References org.onlab.packet.TCP.equals().
void org.onlab.packet.TCPTest.testSerialize ()
Tests serialize and setters.
Definition at line 89 of file TCPTest.java.
References org.onlab.packet.TCP.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/TCPTest.java