onos: org.onosproject.ui.impl.topo.IntentSelection Class Reference
org.onosproject.ui.impl.topo.IntentSelection Class Reference
Encapsulates a selection of intents (paths) inferred from a selection of devices and/or hosts from the topology view.
Public Member Functions
IntentSelection (NodeSelection nodes, TopoIntentFilter filter)
Creates an intent selection group, based on selected nodes.
IntentSelection (Intent intent)
Creates an intent selection group, for a single intent.
boolean none ()
Returns true if no intents are selected.
boolean all ()
Returns true if all intents in this select group are currently selected.
boolean single ()
Returns true if there is a single intent in this select group, or if a specific intent has been marked (index != ALL).
int size ()
Returns the number of intents in this selection group.
int index ()
Returns the index of the currently selected intent.
List< Intent > intents ()
The list of intents in this selection group.
Intent next ()
Marks and returns the next intent in this group.
Intent prev ()
Marks and returns the previous intent in this group.
Intent current ()
Returns the currently marked intent, or null if "all" intents are marked.
String toString ()
Static Protected Attributes
static final Logger log
Detailed Description
Encapsulates a selection of intents (paths) inferred from a selection of devices and/or hosts from the topology view.
Definition at line 33 of file IntentSelection.java.
Constructor & Destructor Documentation
org.onosproject.ui.impl.topo.IntentSelection.IntentSelection (NodeSelection nodes, TopoIntentFilter filter)
Creates an intent selection group, based on selected nodes.
Parameters
nodes node selection
filter intent filter
Definition at line 51 of file IntentSelection.java.
References org.onosproject.ui.topo.NodeSelection.devicesWithHover(), org.onosproject.ui.impl.topo.IntentSelection.index(), and org.onosproject.ui.impl.topo.IntentSelection.intents().
org.onosproject.ui.impl.topo.IntentSelection.IntentSelection (Intent intent)
Creates an intent selection group, for a single intent.
Parameters
intent the intent
Definition at line 64 of file IntentSelection.java.
References org.onosproject.ui.impl.topo.IntentSelection.index(), and org.onosproject.ui.impl.topo.IntentSelection.intents().
Member Function Documentation
boolean org.onosproject.ui.impl.topo.IntentSelection.all ()
Returns true if all intents in this select group are currently selected.
This is the initial state, so that all intents are shown on the topology view with primary highlighting.
Returns
true if all selected
Definition at line 87 of file IntentSelection.java.
References org.onosproject.ui.impl.topo.IntentSelection.index().
Referenced by org.onosproject.ui.impl.topo.IntentSelection.current(), and org.onosproject.ui.impl.topo.IntentSelection.single().
Intent org.onosproject.ui.impl.topo.IntentSelection.current ()
Returns the currently marked intent, or null if "all" intents are marked.
Returns
the currently marked intent
Definition at line 162 of file IntentSelection.java.
References org.onosproject.ui.impl.topo.IntentSelection.all(), and org.onosproject.ui.impl.topo.IntentSelection.index().
int org.onosproject.ui.impl.topo.IntentSelection.index ()
Returns the index of the currently selected intent.
Returns
the current index
Definition at line 115 of file IntentSelection.java.
Referenced by org.onosproject.ui.impl.topo.IntentSelection.all(), org.onosproject.ui.impl.topo.IntentSelection.current(), org.onosproject.ui.impl.topo.IntentSelection.IntentSelection(), org.onosproject.ui.impl.topo.IntentSelection.next(), org.onosproject.ui.impl.topo.IntentSelection.prev(), and org.onosproject.ui.impl.topo.IntentSelection.toString().
List<Intent> org.onosproject.ui.impl.topo.IntentSelection.intents ()
The list of intents in this selection group.
Returns
list of intents
Definition at line 124 of file IntentSelection.java.
Referenced by org.onosproject.ui.impl.topo.IntentSelection.IntentSelection(), and org.onosproject.ui.impl.topo.IntentSelection.next().
Intent org.onosproject.ui.impl.topo.IntentSelection.next ()
Marks and returns the next intent in this group.
Note that the selection wraps around to the beginning again, if necessary.
Returns
the next intent in the group
Definition at line 134 of file IntentSelection.java.
References org.onosproject.ui.impl.topo.IntentSelection.index(), and org.onosproject.ui.impl.topo.IntentSelection.intents().
boolean org.onosproject.ui.impl.topo.IntentSelection.none ()
Returns true if no intents are selected.
Returns
true if nothing selected
Definition at line 76 of file IntentSelection.java.
Referenced by org.onosproject.ui.impl.TrafficMonitor.monitor().
Intent org.onosproject.ui.impl.topo.IntentSelection.prev ()
Marks and returns the previous intent in this group.
Note that the selection wraps around to the end again, if necessary.
Returns
the previous intent in the group
Definition at line 148 of file IntentSelection.java.
References org.onosproject.ui.impl.topo.IntentSelection.index().
boolean org.onosproject.ui.impl.topo.IntentSelection.single ()
Returns true if there is a single intent in this select group, or if a specific intent has been marked (index != ALL).
Returns
true if single intent marked
Definition at line 97 of file IntentSelection.java.
References org.onosproject.ui.impl.topo.IntentSelection.all().
int org.onosproject.ui.impl.topo.IntentSelection.size ()
Returns the number of intents in this selection group.
Returns
number of intents
Definition at line 106 of file IntentSelection.java.
String org.onosproject.ui.impl.topo.IntentSelection.toString ()
Definition at line 167 of file IntentSelection.java.
References org.onosproject.ui.impl.topo.IntentSelection.index().
Member Data Documentation
final Logger org.onosproject.ui.impl.topo.IntentSelection.log static protected
Initial value:
=
            LoggerFactory.getLogger(IntentSelection.class)
Definition at line 37 of file IntentSelection.java.
The documentation for this class was generated from the following file:
web/gui/src/main/java/org/onosproject/ui/impl/topo/IntentSelection.java