onos: org.onosproject.store.trivial.SimpleDeviceStoreTest Class Reference
org.onosproject.store.trivial.SimpleDeviceStoreTest Class Reference
Test of the simple DeviceStore implementation.
Public Member Functions
void setUp () throws Exception
void tearDown () throws Exception
final void testGetDeviceCount ()
final void testGetDevices ()
final void testGetDevice ()
final void testCreateOrUpdateDevice ()
final void testCreateOrUpdateDeviceAncillary ()
final void testMarkOffline ()
final void testUpdatePorts ()
final void testUpdatePortStatus ()
final void testUpdatePortStatusAncillary ()
final void testGetPorts ()
final void testGetPort ()
final void testRemoveDevice ()
final void testEvents () throws InterruptedException
Static Public Member Functions
static void setUpBeforeClass () throws Exception
static void tearDownAfterClass () throws Exception
Detailed Description
Test of the simple DeviceStore implementation.
Definition at line 65 of file SimpleDeviceStoreTest.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleDeviceStoreTest.setUp () throws Exception
Definition at line 114 of file SimpleDeviceStoreTest.java.
static void org.onosproject.store.trivial.SimpleDeviceStoreTest.setUpBeforeClass () throws Exception static
Definition at line 105 of file SimpleDeviceStoreTest.java.
void org.onosproject.store.trivial.SimpleDeviceStoreTest.tearDown () throws Exception
Definition at line 121 of file SimpleDeviceStoreTest.java.
static void org.onosproject.store.trivial.SimpleDeviceStoreTest.tearDownAfterClass () throws Exception static
Definition at line 109 of file SimpleDeviceStoreTest.java.
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testCreateOrUpdateDevice ()
Definition at line 193 of file SimpleDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.createOrUpdateDevice().
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testCreateOrUpdateDeviceAncillary ()
Definition at line 212 of file SimpleDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.createOrUpdateDevice(), and org.onosproject.net.device.DeviceStore.isAvailable().
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testEvents () throws InterruptedException
Definition at line 480 of file SimpleDeviceStoreTest.java.
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testGetDevice ()
Definition at line 184 of file SimpleDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.getDevice().
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testGetDeviceCount ()
Definition at line 151 of file SimpleDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.getDeviceCount().
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testGetDevices ()
Definition at line 162 of file SimpleDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.getDevices().
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testGetPort ()
Definition at line 419 of file SimpleDeviceStoreTest.java.
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testGetPorts ()
Definition at line 396 of file SimpleDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.getPorts(), and obeliskHostCheck.port.
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testMarkOffline ()
Definition at line 254 of file SimpleDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.isAvailable().
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testRemoveDevice ()
Definition at line 441 of file SimpleDeviceStoreTest.java.
References org.onosproject.net.device.DeviceStore.getDevice(), org.onosproject.net.device.DeviceStore.getDeviceCount(), org.onosproject.net.device.DeviceStore.getPort(), and org.onosproject.net.device.DeviceStore.getPorts().
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testUpdatePorts ()
Definition at line 269 of file SimpleDeviceStoreTest.java.
References org.onosproject.net.PortNumber.equals().
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testUpdatePortStatus ()
Definition at line 338 of file SimpleDeviceStoreTest.java.
final void org.onosproject.store.trivial.SimpleDeviceStoreTest.testUpdatePortStatusAncillary ()
Definition at line 355 of file SimpleDeviceStoreTest.java.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleDeviceStoreTest.java