onos: org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest Class Reference
org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest Class Reference
Unit tests for PortChainManager class.
Public Member Functions
void testCreatePortChain ()
Checks the operation of createPortChain() method.
void testExists ()
Checks the operation of exists() method.
void testGetPortChainCount ()
Checks the operation of getPortChainCount() method.
void testGetPortChains ()
Checks the operation of getPortChains() method.
void testGetPortChain ()
Checks the operation of getPortChain() method.
void testUpdatePortChain ()
Checks the operation of updatePortChain() method.
void testRemovePortChain ()
Checks the operation of removePortChain() method.
Detailed Description
Unit tests for PortChainManager class.
Definition at line 38 of file PortChainManagerTest.java.
Member Function Documentation
void org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testCreatePortChain ()
Checks the operation of createPortChain() method.
Definition at line 55 of file PortChainManagerTest.java.
References org.onosproject.vtnrsc.portchain.impl.PortChainManager.createPortChain().
Referenced by org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testExists(), org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testGetPortChain(), org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testGetPortChainCount(), org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testGetPortChains(), org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testRemovePortChain(), and org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testUpdatePortChain().
void org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testExists ()
Checks the operation of exists() method.
Definition at line 82 of file PortChainManagerTest.java.
References org.onosproject.vtnrsc.portchain.impl.PortChainManager.exists(), and org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testCreatePortChain().
void org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testGetPortChain ()
Checks the operation of getPortChain() method.
Definition at line 111 of file PortChainManagerTest.java.
References org.onosproject.vtnrsc.portchain.impl.PortChainManager.getPortChain(), and org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testCreatePortChain().
void org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testGetPortChainCount ()
Checks the operation of getPortChainCount() method.
Definition at line 91 of file PortChainManagerTest.java.
References org.onosproject.vtnrsc.portchain.impl.PortChainManager.getPortChainCount(), and org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testCreatePortChain().
void org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testGetPortChains ()
Checks the operation of getPortChains() method.
Definition at line 100 of file PortChainManagerTest.java.
References org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testCreatePortChain().
void org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testRemovePortChain ()
Checks the operation of removePortChain() method.
Definition at line 151 of file PortChainManagerTest.java.
References org.onosproject.vtnrsc.portchain.impl.PortChainManager.removePortChain(), and org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testCreatePortChain().
void org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testUpdatePortChain ()
Checks the operation of updatePortChain() method.
Definition at line 121 of file PortChainManagerTest.java.
References org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testCreatePortChain(), and org.onosproject.vtnrsc.portchain.impl.PortChainManager.updatePortChain().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/test/java/org/onosproject/vtnrsc/portchain/impl/PortChainManagerTest.java