onos: org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider Class Reference
org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider Class Reference
Provider which uses an PCEP controller to detect, update, create network tunnels.
Public Member Functions
PcepTunnelProvider ()
Creates a Tunnel provider.
void activate ()
void deactivate ()
void modified (ComponentContext context)
void setupTunnel (Tunnel tunnel, Path path)
Instructs the provider to setup a tunnel.
void setupTunnel (ElementId srcElement, Tunnel tunnel, Path path)
Instructs the provider to setup a tunnel given the respective device.
void releaseTunnel (Tunnel tunnel)
Instructs the provider to release a tunnel.
void releaseTunnel (ElementId srcElement, Tunnel tunnel)
Instructs the provider to release a tunnel given the respective device.
void updateTunnel (Tunnel tunnel, Path path)
Instructs the provider to update a tunnel.
void updateTunnel (ElementId srcElement, Tunnel tunnel, Path path)
Instructs the provider to update a tunnel given the respective device.
TunnelId tunnelAdded (TunnelDescription tunnel)
Signals that the provider has added a tunnel.
void tunnelRemoved (TunnelDescription tunnel)
Signals that the provider has removed a tunnel.
void tunnelUpdated (TunnelDescription tunnel)
Signals that the a tunnel was changed (e.g., sensing changes of tunnel).It's used by producers.
String pathToString (List< Link > links)
Tunnel tunnelQueryById (TunnelId tunnelId)
Signals that the a tunnel was queried.
Public Member Functions inherited from org.onosproject.net.provider.AbstractProvider
ProviderId id ()
Returns the provider identifier.
Protected Attributes
TunnelProviderRegistry tunnelProviderRegistry
PcepController controller
PcepClientController pcepClientController
TunnelService tunnelService
ComponentConfigService cfgService
PcepTunnelApiMapper pcepTunnelAPIMapper = new PcepTunnelApiMapper()
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.provider.AbstractProvider
AbstractProvider (ProviderId id)
Creates a provider with the supplier identifier.
Detailed Description
Provider which uses an PCEP controller to detect, update, create network tunnels.
Definition at line 121 of file PcepTunnelProvider.java.
Constructor & Destructor Documentation
org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.PcepTunnelProvider ()
Creates a Tunnel provider.
Definition at line 165 of file PcepTunnelProvider.java.
Member Function Documentation
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.activate ()
Definition at line 170 of file PcepTunnelProvider.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.deactivate ()
Definition at line 188 of file PcepTunnelProvider.java.
References org.onosproject.provider.pcep.tunnel.impl.TunnelStatsCollector.stop().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.modified (ComponentContext context)
Definition at line 197 of file PcepTunnelProvider.java.
String org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.pathToString (List< Link > links)
Definition at line 510 of file PcepTunnelProvider.java.
References find-flow.deviceId, and obeliskHostCheck.port.
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.releaseTunnel (Tunnel tunnel)
Instructs the provider to release a tunnel.
It's used by consumers.
Parameters
tunnel Tunnel
Implements org.onosproject.incubator.net.tunnel.TunnelProvider.
Definition at line 270 of file PcepTunnelProvider.java.
References org.onosproject.incubator.net.tunnel.Tunnel.dst(), org.onosproject.incubator.net.tunnel.Tunnel.src(), and org.onosproject.incubator.net.tunnel.Tunnel.type().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.releaseTunnel (ElementId srcElement, Tunnel tunnel)
Instructs the provider to release a tunnel given the respective device.
It's used by consumers.
Parameters
srcElement device
tunnel Tunnel
Implements org.onosproject.incubator.net.tunnel.TunnelProvider.
Definition at line 294 of file PcepTunnelProvider.java.
References org.onosproject.incubator.net.tunnel.Tunnel.dst(), org.onosproject.incubator.net.tunnel.Tunnel.src(), and org.onosproject.incubator.net.tunnel.Tunnel.type().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.setupTunnel (Tunnel tunnel, Path path)
Instructs the provider to setup a tunnel.
It's used by consumers.
Parameters
tunnel Tunnel
path explicit route or null for the tunnel
Implements org.onosproject.incubator.net.tunnel.TunnelProvider.
Definition at line 217 of file PcepTunnelProvider.java.
References org.onosproject.incubator.net.tunnel.Tunnel.dst(), org.onosproject.incubator.net.tunnel.Tunnel.src(), and org.onosproject.incubator.net.tunnel.Tunnel.type().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.setupTunnel (ElementId srcElement, Tunnel tunnel, Path path)
Instructs the provider to setup a tunnel given the respective device.
It's used by consumers.
Parameters
srcElement device
tunnel Tunnel
path explicit route (not null) for the tunnel
Implements org.onosproject.incubator.net.tunnel.TunnelProvider.
Definition at line 241 of file PcepTunnelProvider.java.
References org.onosproject.incubator.net.tunnel.Tunnel.dst(), org.onosproject.incubator.net.tunnel.Tunnel.src(), and org.onosproject.incubator.net.tunnel.Tunnel.type().
TunnelId org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelAdded (TunnelDescription tunnel)
Signals that the provider has added a tunnel.
It's used by producers.
Parameters
tunnel tunnel information
Returns
tunnel identity
Implements org.onosproject.incubator.net.tunnel.TunnelProvider.
Definition at line 374 of file PcepTunnelProvider.java.
References org.onosproject.incubator.net.tunnel.TunnelDescription.dst(), find-link-in-cluster.dstPort, org.onosproject.incubator.net.tunnel.OpticalTunnelEndPoint.elementId(), find-link-in-cluster.srcPort, and org.onosproject.incubator.net.tunnel.TunnelDescription.type().
Tunnel org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelQueryById (TunnelId tunnelId)
Signals that the a tunnel was queried.
It's used by producers.
Parameters
tunnelId tunnel identity
Returns
tunnel entity
Implements org.onosproject.incubator.net.tunnel.TunnelProvider.
Definition at line 1227 of file PcepTunnelProvider.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelRemoved(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelUpdated().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelRemoved (TunnelDescription tunnel)
Signals that the provider has removed a tunnel.
It's used by producers.
Parameters
tunnel tunnel information
Implements org.onosproject.incubator.net.tunnel.TunnelProvider.
Definition at line 420 of file PcepTunnelProvider.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.controller, org.onosproject.pcep.api.PcepController.deleteTunnel(), org.onosproject.incubator.net.tunnel.TunnelDescription.id(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelQueryById(), org.onosproject.incubator.net.tunnel.TunnelDescription.type(), and org.onosproject.incubator.net.tunnel.Tunnel.type().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelUpdated (TunnelDescription tunnel)
Signals that the a tunnel was changed (e.g., sensing changes of tunnel).It's used by producers.
Parameters
tunnel tunnel information
Implements org.onosproject.incubator.net.tunnel.TunnelProvider.
Definition at line 443 of file PcepTunnelProvider.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.controller, org.onosproject.incubator.net.tunnel.TunnelDescription.id(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelQueryById(), org.onosproject.incubator.net.tunnel.TunnelDescription.type(), org.onosproject.incubator.net.tunnel.Tunnel.type(), and org.onosproject.pcep.api.PcepController.updateTunnelBandwidth().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.updateTunnel (Tunnel tunnel, Path path)
Instructs the provider to update a tunnel.
It's used by consumers. Maybe some consumers enable to update a tunnel.
Parameters
tunnel Tunnel
path explicit route (path changed) or null (path not changed) for the tunnel
Implements org.onosproject.incubator.net.tunnel.TunnelProvider.
Definition at line 322 of file PcepTunnelProvider.java.
References org.onosproject.incubator.net.tunnel.Tunnel.dst(), org.onosproject.incubator.net.tunnel.Tunnel.src(), and org.onosproject.incubator.net.tunnel.Tunnel.type().
void org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.updateTunnel (ElementId srcElement, Tunnel tunnel, Path path)
Instructs the provider to update a tunnel given the respective device.
It's used by consumers. Maybe some consumers enable to update a tunnel.
Parameters
srcElement device
tunnel Tunnel
path explicit route (path changed) or null (path not changed) for the tunnel
Implements org.onosproject.incubator.net.tunnel.TunnelProvider.
Definition at line 345 of file PcepTunnelProvider.java.
References org.onosproject.incubator.net.tunnel.Tunnel.dst(), org.onosproject.incubator.net.tunnel.Tunnel.src(), and org.onosproject.incubator.net.tunnel.Tunnel.type().
Member Data Documentation
ComponentConfigService org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.cfgService protected
Definition at line 149 of file PcepTunnelProvider.java.
PcepController org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.controller protected
Definition at line 140 of file PcepTunnelProvider.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelRemoved(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelUpdated().
PcepClientController org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.pcepClientController protected
Definition at line 143 of file PcepTunnelProvider.java.
PcepTunnelApiMapper org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.pcepTunnelAPIMapper = new PcepTunnelApiMapper() protected
Definition at line 159 of file PcepTunnelProvider.java.
TunnelProviderRegistry org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelProviderRegistry protected
Definition at line 137 of file PcepTunnelProvider.java.
TunnelService org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelService protected
Definition at line 146 of file PcepTunnelProvider.java.
The documentation for this class was generated from the following file:
providers/pcep/tunnel/src/main/java/org/onosproject/provider/pcep/tunnel/impl/PcepTunnelProvider.java