onos: org.onosproject.net.NetTestTools Class Reference
org.onosproject.net.NetTestTools Class Reference
Miscellaneous tools for testing core related to the network model.
Static Public Member Functions
static DeviceId did (String id)
static HostId hid (String id)
static Device device (String id)
static Host host (String id, String did)
static ConnectPoint connectPoint (String id, int port)
static Link link (String src, int sp, String dst, int dp)
static Path createPath (String...ids)
static OchSignal createLambda ()
static void assertAnnotationsEquals (Annotations actual, SparseAnnotations...annotations)
Verifies that Annotations created by merging.
static void injectEventDispatcher (Object manager, EventDeliveryService svc)
Injects the given event delivery service into the specified manager component.
Static Public Attributes
static final ProviderId PID = new ProviderId("of", "foo")
static final ApplicationId APP_ID = new TestApplicationId("foo")
Detailed Description
Miscellaneous tools for testing core related to the network model.
Definition at line 40 of file NetTestTools.java.
Member Function Documentation
static void org.onosproject.net.NetTestTools.assertAnnotationsEquals (Annotations actual, SparseAnnotations... annotations) static
Verifies that Annotations created by merging.
annotations
is equal to actual Annotations.
Parameters
actual annotations to check
annotations expected annotations
Definition at line 106 of file NetTestTools.java.
References org.onosproject.net.DefaultAnnotations.keys(), and org.onosproject.net.DefaultAnnotations.value().
static ConnectPoint org.onosproject.net.NetTestTools.connectPoint (String id, int port) static
Definition at line 73 of file NetTestTools.java.
References org.onosproject.net.NetTestTools.did().
Referenced by org.onosproject.net.NetTestTools.link(), and org.onosproject.net.edgeservice.impl.EdgeManagerTest.testBasics().
static OchSignal org.onosproject.net.NetTestTools.createLambda () static
Definition at line 95 of file NetTestTools.java.
References org.onosproject.net.ChannelSpacing.CHL_6P25GHZ, and org.onosproject.net.GridType.DWDM.
static Path org.onosproject.net.NetTestTools.createPath (String... ids) static
Definition at line 86 of file NetTestTools.java.
References org.onosproject.net.NetTestTools.link(), and org.onosproject.net.NetTestTools.PID.
static Device org.onosproject.net.NetTestTools.device (String id) static
Definition at line 60 of file NetTestTools.java.
References org.onosproject.net.NetTestTools.did(), and org.onosproject.net.NetTestTools.PID.
static DeviceId org.onosproject.net.NetTestTools.did (String id) static
Definition at line 49 of file NetTestTools.java.
References find-flow.deviceId.
Referenced by org.onosproject.net.group.DefaultGroupTest.checkConstructionWithDid(), org.onosproject.codec.impl.GroupCodecTest.codecTest(), org.onosproject.net.NetTestTools.connectPoint(), org.onosproject.net.NetTestTools.device(), org.onosproject.net.NetTestTools.host(), org.onosproject.net.edgeservice.impl.EdgeManagerTest.testDeviceUpdates(), and org.onosproject.net.edgeservice.impl.EdgeManagerTest.testInternalCache().
static HostId org.onosproject.net.NetTestTools.hid (String id) static
Definition at line 55 of file NetTestTools.java.
Referenced by org.onosproject.net.NetTestTools.host().
static Host org.onosproject.net.NetTestTools.host (String id, String did) static
Definition at line 66 of file NetTestTools.java.
References org.onosproject.net.NetTestTools.did(), org.onosproject.net.NetTestTools.hid(), and org.onosproject.net.NetTestTools.PID.
static void org.onosproject.net.NetTestTools.injectEventDispatcher (Object manager, EventDeliveryService svc) static
Injects the given event delivery service into the specified manager component.
Parameters
manager manager component
svc service reference to be injected
Definition at line 124 of file NetTestTools.java.
static Link org.onosproject.net.NetTestTools.link (String src, int sp, String dst, int dp) static
Definition at line 78 of file NetTestTools.java.
References org.onosproject.net.NetTestTools.connectPoint(), and org.onosproject.net.NetTestTools.PID.
Referenced by org.onosproject.net.NetTestTools.createPath(), and org.onosproject.net.edgeservice.impl.EdgeManagerTest.testLinkUpdates().
Member Data Documentation
final ApplicationId org.onosproject.net.NetTestTools.APP_ID = new TestApplicationId("foo") static
Definition at line 46 of file NetTestTools.java.
Referenced by org.onosproject.net.intent.KeyTest.keysAreImmutable(), org.onosproject.net.intent.KeyTest.longKey(), org.onosproject.net.intent.KeyTest.longKeyConstruction(), org.onosproject.rest.FlowsResourceTest.setUpTest(), org.onosproject.net.intent.KeyTest.stringKey(), org.onosproject.net.intent.KeyTest.stringKeyConstruction(), and org.onosproject.net.packet.DefaultPacketRequestTest.testConstruction().
final ProviderId org.onosproject.net.NetTestTools.PID = new ProviderId("of", "foo") static
Definition at line 45 of file NetTestTools.java.
Referenced by org.onosproject.net.NetTestTools.createPath(), org.onosproject.net.NetTestTools.device(), org.onosproject.net.NetTestTools.host(), and org.onosproject.net.NetTestTools.link().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/NetTestTools.java