onos: org.onosproject.net.intent.IntentEvent Class Reference
org.onosproject.net.intent.IntentEvent Class Reference
A class to represent an intent related event.
Classes
enum Type
Public Member Functions
IntentEvent (Type type, Intent intent, long time)
Creates an event of a given type and for the specified intent and the current time.
IntentEvent (Type type, Intent intent)
Creates an event of a given type and for the specified intent and the current time.
Static Public Member Functions
static IntentEvent getEvent (IntentData data)
Creates an IntentEvent based on the state contained in the given intent data.
static IntentEvent getEvent (IntentState state, Intent intent)
Creates an IntentEvent based on the given state and intent.
Detailed Description
A class to represent an intent related event.
Definition at line 25 of file IntentEvent.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.IntentEvent.IntentEvent (Type type, Intent intent, long time)
Creates an event of a given type and for the specified intent and the current time.
Parameters
type event type
intent subject intent
time time the event created in milliseconds since start of epoch
Definition at line 75 of file IntentEvent.java.
Referenced by org.onosproject.net.intent.IntentEvent.getEvent().
org.onosproject.net.intent.IntentEvent.IntentEvent (Type type, Intent intent)
Creates an event of a given type and for the specified intent and the current time.
Parameters
type event type
intent subject intent
Definition at line 86 of file IntentEvent.java.
Member Function Documentation
static IntentEvent org.onosproject.net.intent.IntentEvent.getEvent (IntentData data) static
Creates an IntentEvent based on the state contained in the given intent data.
Some states are not sent as external events, and these states will return null events.
Parameters
data the intent data to create an event for
Returns
new intent event if the state is valid, otherwise null.
Definition at line 98 of file IntentEvent.java.
Referenced by org.onosproject.store.trivial.SimpleIntentStore.addPending(), and org.onosproject.store.trivial.SimpleIntentStore.write().
static IntentEvent org.onosproject.net.intent.IntentEvent.getEvent (IntentState state, Intent intent) static
Creates an IntentEvent based on the given state and intent.
Some states are not sent as external events, and these states will return null events.
Parameters
state new state of the intent
intent intent to put in event
Returns
new intent event if the state is valid, otherwise null.
Definition at line 110 of file IntentEvent.java.
References org.onosproject.net.intent.IntentEvent.Type.CORRUPT, org.onosproject.net.intent.IntentEvent.Type.FAILED, org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, org.onosproject.net.intent.IntentEvent.Type.INSTALLED, org.onosproject.net.intent.IntentEvent.IntentEvent(), org.onosproject.net.intent.IntentEvent.Type.PURGED, org.onosproject.net.intent.IntentEvent.Type.WITHDRAW_REQ, and org.onosproject.net.intent.IntentEvent.Type.WITHDRAWN.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/IntentEvent.java