onos: org.onosproject.ui.UiMessageHandler Class Reference
org.onosproject.ui.UiMessageHandler Class Reference abstract
Abstraction of an entity capable of processing JSON messages from the user interface client.
Public Member Functions
Set< String > messageTypes ()
Returns the set of message types which this handler is capable of processing.
void process (ObjectNode message)
Processes a JSON message from the user interface client.
void init (UiConnection connection, ServiceDirectory directory)
Initializes the handler with the user interface connection and service directory context.
void destroy ()
Destroys the message handler context.
UiConnection connection ()
Returns the user interface connection with which this handler was primed.
ServiceDirectory directory ()
Returns the user interface connection with which this handler was primed.
Protected Member Functions
abstract Collection
< RequestHandler > createRequestHandlers ()
Subclasses must create and return the collection of request handlers for the message types they handle.
ObjectNode objectNode ()
Returns a freshly minted object node.
ArrayNode arrayNode ()
Returns a freshly minted array node.
synchronized void sendMessage (ObjectNode data)
Sends the specified data to the client.
Detailed Description
Abstraction of an entity capable of processing JSON messages from the user interface client.
The message structure is:
{
    "type": "<em>event-type</em>",
    "payload": {
        arbitrary JSON object structure
    }
}
On initialization the handler will create and cache RequestHandler instances, each of which are bound to a particular event-type. On arrival of a new message, the event-type is determined, and the message dispatched to the corresponding RequestHandler's process method.
Definition at line 55 of file UiMessageHandler.java.
Member Function Documentation
ArrayNode org.onosproject.ui.UiMessageHandler.arrayNode () protected
Returns a freshly minted array node.
Returns
new array node
Definition at line 190 of file UiMessageHandler.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceMessage(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.instanceMessage().
UiConnection org.onosproject.ui.UiMessageHandler.connection ()
Returns the user interface connection with which this handler was primed.
Returns
user interface connection
Definition at line 151 of file UiMessageHandler.java.
Referenced by it.pkg.AppUiTopovMessageHandler.init(), org.onosproject.ui.UiMessageHandler.init(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init(), org.onosproject.ui.impl.TopologyViewMessageHandler.init(), and org.onosproject.ui.UiMessageHandler.sendMessage().
abstract Collection<RequestHandler> org.onosproject.ui.UiMessageHandler.createRequestHandlers () protected pure virtual
Subclasses must create and return the collection of request handlers for the message types they handle.
Note that request handlers should be stateless. When we are destroyed, we will simply drop our references to them and allow them to be garbage collected.
Returns
the message handler instances
Implemented in org.onosproject.ui.impl.TopologyViewMessageHandler, org.onosproject.ui.impl.DeviceViewMessageHandler, AppUiTopovMessageHandler, AppUiTopovMessageHandler, it.pkg.AppUiTopovMessageHandler, org.onosproject.ui.impl.FlowViewMessageHandler, org.onosproject.ui.impl.IntentViewMessageHandler, org.onosproject.ui.impl.LinkViewMessageHandler, org.onosproject.ui.impl.ProcessorViewMessageHandler, org.onosproject.ui.impl.ApplicationViewMessageHandler, AppUiTableMessageHandler, AppUiTableMessageHandler, org.onosproject.ui.impl.GroupViewMessageHandler, org.onosproject.ui.impl.HostViewMessageHandler, org.onosproject.ui.impl.ClusterViewMessageHandler, org.onosproject.ui.impl.PortViewMessageHandler, it.pkg.AppUiTableMessageHandler, org.onosproject.ui.impl.TunnelViewMessageHandler, org.onosproject.dhcp.impl.DhcpViewMessageHandler, org.onosproject.ui.impl.SettingsViewMessageHandler, AppUiMessageHandler, AppUiMessageHandler, and it.pkg.AppUiMessageHandler.
Referenced by org.onosproject.ui.UiMessageHandler.init().
void org.onosproject.ui.UiMessageHandler.destroy ()
Destroys the message handler context.
Definition at line 140 of file UiMessageHandler.java.
ServiceDirectory org.onosproject.ui.UiMessageHandler.directory ()
Returns the user interface connection with which this handler was primed.
Returns
user interface connection
Definition at line 160 of file UiMessageHandler.java.
Referenced by it.pkg.AppUiTopovMessageHandler.init(), org.onosproject.ui.UiMessageHandler.init(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init(), and org.onosproject.ui.impl.TopologyViewMessageHandler.init().
void org.onosproject.ui.UiMessageHandler.init (UiConnection connection, ServiceDirectory directory)
Initializes the handler with the user interface connection and service directory context.
Parameters
connection user interface connection
directory service directory
Definition at line 123 of file UiMessageHandler.java.
References org.onosproject.ui.UiMessageHandler.connection(), org.onosproject.ui.UiMessageHandler.createRequestHandlers(), and org.onosproject.ui.UiMessageHandler.directory().
Set<String> org.onosproject.ui.UiMessageHandler.messageTypes ()
Returns the set of message types which this handler is capable of processing.
Returns
set of message types
Definition at line 83 of file UiMessageHandler.java.
ObjectNode org.onosproject.ui.UiMessageHandler.objectNode () protected
Returns a freshly minted object node.
Returns
new object node
Definition at line 181 of file UiMessageHandler.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceMessage(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.hostMessage(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.instanceMessage(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.linkMessage().
void org.onosproject.ui.UiMessageHandler.process (ObjectNode message)
Processes a JSON message from the user interface client.
Parameters
message JSON message
Definition at line 92 of file UiMessageHandler.java.
synchronized void org.onosproject.ui.UiMessageHandler.sendMessage (ObjectNode data) protected
Sends the specified data to the client.
It is expected that the data is in the prescribed JSON format for events to the client.
Parameters
data data to be sent
Definition at line 201 of file UiMessageHandler.java.
References org.onosproject.ui.UiMessageHandler.connection().
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandler.sendHighlights().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/UiMessageHandler.java