onos: org.onosproject.routing.bgp.BgpRouteEntryTest Class Reference
org.onosproject.routing.bgp.BgpRouteEntryTest Class Reference
Unit tests for the BgpRouteEntry class.
Public Member Functions
void setUp () throws Exception
void testConstructor ()
Tests valid class constructor.
void testInvalidConstructorNullBgpSession ()
Tests invalid class constructor for null BGP Session.
void testInvalidConstructorNullAsPath ()
Tests invalid class constructor for null AS Path.
void testGetFields ()
Tests getting the fields of a BGP route entry.
void testIsLocalRoute ()
Tests whether a BGP route entry is a local route.
void testGetNeighborAs ()
Tests getting the BGP Neighbor AS number for a route.
void testHasAsPathLoop ()
Tests whether a BGP route entry has AS Path loop.
void testBgpDecisionProcessComparison ()
Tests the BGP Decision Process comparison of BGP routes.
void testEquality ()
Tests equality of BgpRouteEntry.
void testNonEquality ()
Tests non-equality of BgpRouteEntry.
void testToString ()
Tests object string representation.
Detailed Description
Unit tests for the BgpRouteEntry class.
Definition at line 34 of file BgpRouteEntryTest.java.
Member Function Documentation
void org.onosproject.routing.bgp.BgpRouteEntryTest.setUp () throws Exception
Definition at line 63 of file BgpRouteEntryTest.java.
void org.onosproject.routing.bgp.BgpRouteEntryTest.testBgpDecisionProcessComparison ()
Tests the BGP Decision Process comparison of BGP routes.
Definition at line 338 of file BgpRouteEntryTest.java.
References onosUploadBits.prefix.
void org.onosproject.routing.bgp.BgpRouteEntryTest.testConstructor ()
Tests valid class constructor.
Definition at line 135 of file BgpRouteEntryTest.java.
References org.onosproject.routing.bgp.BgpRouteEntry.toString().
void org.onosproject.routing.bgp.BgpRouteEntryTest.testEquality ()
Tests equality of BgpRouteEntry.
Definition at line 455 of file BgpRouteEntryTest.java.
void org.onosproject.routing.bgp.BgpRouteEntryTest.testGetFields ()
Tests getting the fields of a BGP route entry.
Definition at line 185 of file BgpRouteEntryTest.java.
References org.onosproject.routing.bgp.BgpRouteEntry.getAsPath(), org.onosproject.routing.bgp.BgpRouteEntry.getBgpSession(), org.onosproject.routing.bgp.BgpRouteEntry.getLocalPref(), org.onosproject.routing.bgp.BgpRouteEntry.getMultiExitDisc(), org.onosproject.routing.bgp.BgpRouteEntry.getOrigin(), org.onosproject.routing.RouteEntry.nextHop(), onosUploadBits.prefix, and org.onosproject.routing.RouteEntry.prefix().
void org.onosproject.routing.bgp.BgpRouteEntryTest.testGetNeighborAs ()
Tests getting the BGP Neighbor AS number for a route.
Definition at line 291 of file BgpRouteEntryTest.java.
References org.onosproject.routing.bgp.BgpConstants.BGP_AS_0, and onosUploadBits.prefix.
void org.onosproject.routing.bgp.BgpRouteEntryTest.testHasAsPathLoop ()
Tests whether a BGP route entry has AS Path loop.
Definition at line 322 of file BgpRouteEntryTest.java.
void org.onosproject.routing.bgp.BgpRouteEntryTest.testInvalidConstructorNullAsPath ()
Tests invalid class constructor for null AS Path.
Definition at line 170 of file BgpRouteEntryTest.java.
References onosUploadBits.prefix.
void org.onosproject.routing.bgp.BgpRouteEntryTest.testInvalidConstructorNullBgpSession ()
Tests invalid class constructor for null BGP Session.
Definition at line 151 of file BgpRouteEntryTest.java.
References onosUploadBits.prefix.
void org.onosproject.routing.bgp.BgpRouteEntryTest.testIsLocalRoute ()
Tests whether a BGP route entry is a local route.
Definition at line 231 of file BgpRouteEntryTest.java.
References onosUploadBits.prefix.
void org.onosproject.routing.bgp.BgpRouteEntryTest.testNonEquality ()
Tests non-equality of BgpRouteEntry.
Definition at line 466 of file BgpRouteEntryTest.java.
References onosUploadBits.prefix.
void org.onosproject.routing.bgp.BgpRouteEntryTest.testToString ()
Tests object string representation.
Definition at line 509 of file BgpRouteEntryTest.java.
References org.onosproject.routing.bgp.BgpRouteEntry.toString().
The documentation for this class was generated from the following file:
apps/routing/src/test/java/org/onosproject/routing/bgp/BgpRouteEntryTest.java