onos: org.onlab.netty.NettyMessaging Class Reference
org.onlab.netty.NettyMessaging Class Reference
Implementation of MessagingService based on Netty framework.
Public Member Functions
void start (int preamble, Endpoint localEp) throws Exception
void stop () throws Exception
CompletableFuture< Void > sendAsync (Endpoint ep, String type, byte[] payload)
Sends a message asynchronously to the specified communication end point.
CompletableFuture< byte[]> sendAndReceive (Endpoint ep, String type, byte[] payload)
Sends a message synchronously and waits for a response.
void registerHandler (String type, Consumer< byte[]> handler, Executor executor)
Registers a new message handler for message type.
void registerHandler (String type, Function< byte[], byte[]> handler, Executor executor)
Registers a new message handler for message type.
void registerHandler (String type, Function< byte[], CompletableFuture< byte[]>> handler)
Registers a new message handler for message type.
void unregisterHandler (String type)
Unregister current handler, if one exists for message type.
Protected Member Functions
CompletableFuture< Void > sendAsync (Endpoint ep, InternalMessage message)
Protected Attributes
boolean enableNettyTls = TLS_DISABLED
String ksLocation
String tsLocation
char[] ksPwd
char[] tsPwd
Static Protected Attributes
static final boolean TLS_DISABLED = false
Detailed Description
Implementation of MessagingService based on Netty framework.
Definition at line 70 of file NettyMessaging.java.
Member Function Documentation
void org.onlab.netty.NettyMessaging.registerHandler (String type, Consumer< byte[]> handler, Executor executor)
Registers a new message handler for message type.
Parameters
type message type.
handler message handler
executor executor to use for running message handler logic.
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 205 of file NettyMessaging.java.
void org.onlab.netty.NettyMessaging.registerHandler (String type, Function< byte[], byte[]> handler, Executor executor)
Registers a new message handler for message type.
Parameters
type message type.
handler message handler
executor executor to use for running message handler logic.
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 210 of file NettyMessaging.java.
References org.onlab.netty.NettyMessaging.sendAsync().
void org.onlab.netty.NettyMessaging.registerHandler (String type, Function< byte[], CompletableFuture< byte[]>> handler)
Registers a new message handler for message type.
Parameters
type message type.
handler message handler
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 228 of file NettyMessaging.java.
References org.onlab.netty.NettyMessaging.sendAsync().
CompletableFuture<byte[]> org.onlab.netty.NettyMessaging.sendAndReceive (Endpoint ep, String type, byte[] payload)
Sends a message synchronously and waits for a response.
Parameters
ep end point to send the message to.
type type of message.
payload message payload.
Returns
a response future
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 190 of file NettyMessaging.java.
References org.onlab.netty.NettyMessaging.sendAsync().
CompletableFuture<Void> org.onlab.netty.NettyMessaging.sendAsync (Endpoint ep, String type, byte[] payload)
Sends a message asynchronously to the specified communication end point.
The message is specified using the type and payload.
Parameters
ep end point to send the message to.
type type of message.
payload message payload bytes.
Returns
future that is completed when the message is sent
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 154 of file NettyMessaging.java.
Referenced by org.onlab.netty.NettyMessaging.registerHandler(), and org.onlab.netty.NettyMessaging.sendAndReceive().
CompletableFuture<Void> org.onlab.netty.NettyMessaging.sendAsync (Endpoint ep, InternalMessage message) protected
Definition at line 162 of file NettyMessaging.java.
References org.onosproject.store.cluster.messaging.Endpoint.equals().
void org.onlab.netty.NettyMessaging.start (int preamble, Endpoint localEp) throws Exception
Definition at line 127 of file NettyMessaging.java.
void org.onlab.netty.NettyMessaging.stop () throws Exception
Definition at line 144 of file NettyMessaging.java.
void org.onlab.netty.NettyMessaging.unregisterHandler (String type)
Unregister current handler, if one exists for message type.
Parameters
type message type
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 247 of file NettyMessaging.java.
Member Data Documentation
boolean org.onlab.netty.NettyMessaging.enableNettyTls = TLS_DISABLED protected
Definition at line 102 of file NettyMessaging.java.
String org.onlab.netty.NettyMessaging.ksLocation protected
Definition at line 104 of file NettyMessaging.java.
char [] org.onlab.netty.NettyMessaging.ksPwd protected
Definition at line 106 of file NettyMessaging.java.
final boolean org.onlab.netty.NettyMessaging.TLS_DISABLED = false static protected
Definition at line 101 of file NettyMessaging.java.
String org.onlab.netty.NettyMessaging.tsLocation protected
Definition at line 105 of file NettyMessaging.java.
char [] org.onlab.netty.NettyMessaging.tsPwd protected
Definition at line 107 of file NettyMessaging.java.
The documentation for this class was generated from the following file:
utils/netty/src/main/java/org/onlab/netty/NettyMessaging.java