onos: org.onosproject.ovsdb.controller.OvsdbNodeId Class Reference
org.onosproject.ovsdb.controller.OvsdbNodeId Class Reference
The class representing a nodeId of node which using ovsdb connection.
Public Member Functions
OvsdbNodeId (IpAddress ipAddress, long port)
Creates a new node identifier from an IpAddress ipAddress, a long port.
int hashCode ()
boolean equals (Object other)
String toString ()
String nodeId ()
Gets the value of the NodeId.
String getIpAddress ()
Get the IP address of the node.
Detailed Description
The class representing a nodeId of node which using ovsdb connection.
This class is immutable.
Definition at line 28 of file OvsdbNodeId.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.controller.OvsdbNodeId.OvsdbNodeId (IpAddress ipAddress, long port)
Creates a new node identifier from an IpAddress ipAddress, a long port.
Parameters
ipAddress node IP address
port node port
Definition at line 39 of file OvsdbNodeId.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbNodeId.equals().
Member Function Documentation
boolean org.onosproject.ovsdb.controller.OvsdbNodeId.equals (Object other)
Definition at line 51 of file OvsdbNodeId.java.
References org.onosproject.ovsdb.controller.OvsdbNodeId.OvsdbNodeId().
String org.onosproject.ovsdb.controller.OvsdbNodeId.getIpAddress ()
Get the IP address of the node.
Returns
the IP address of the node
Definition at line 80 of file OvsdbNodeId.java.
int org.onosproject.ovsdb.controller.OvsdbNodeId.hashCode ()
Definition at line 46 of file OvsdbNodeId.java.
String org.onosproject.ovsdb.controller.OvsdbNodeId.nodeId ()
Gets the value of the NodeId.
Returns
the value of the NodeId.
Definition at line 71 of file OvsdbNodeId.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbNodeId.toString().
String org.onosproject.ovsdb.controller.OvsdbNodeId.toString ()
Definition at line 62 of file OvsdbNodeId.java.
References org.onosproject.ovsdb.controller.OvsdbNodeId.nodeId().
The documentation for this class was generated from the following file:
protocols/ovsdb/api/src/main/java/org/onosproject/ovsdb/controller/OvsdbNodeId.java