onos: org.onosproject.net.topology.impl.DefaultTopologyProvider Class Reference
org.onosproject.net.topology.impl.DefaultTopologyProvider Class Reference
Default implementation of a network topology provider that feeds off device and link subsystem events to trigger assembly and computation of new topology snapshots.
Public Member Functions
DefaultTopologyProvider ()
Creates a provider with the supplier identifier.
synchronized void activate (ComponentContext context)
synchronized void deactivate (ComponentContext context)
void modified (ComponentContext context)
void triggerRecompute ()
Triggers topology recomputation.
Public Member Functions inherited from org.onosproject.net.provider.AbstractProvider
ProviderId id ()
Returns the provider identifier.
Protected Attributes
TopologyProviderRegistry providerRegistry
DeviceService deviceService
LinkService linkService
ComponentConfigService cfgService
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.provider.AbstractProvider
AbstractProvider (ProviderId id)
Creates a provider with the supplier identifier.
Detailed Description
Default implementation of a network topology provider that feeds off device and link subsystem events to trigger assembly and computation of new topology snapshots.
Definition at line 70 of file DefaultTopologyProvider.java.
Constructor & Destructor Documentation
org.onosproject.net.topology.impl.DefaultTopologyProvider.DefaultTopologyProvider ()
Creates a provider with the supplier identifier.
Definition at line 120 of file DefaultTopologyProvider.java.
Member Function Documentation
synchronized void org.onosproject.net.topology.impl.DefaultTopologyProvider.activate (ComponentContext context)
Definition at line 125 of file DefaultTopologyProvider.java.
References org.onosproject.net.topology.impl.DefaultTopologyProvider.modified(), and org.onosproject.net.topology.impl.DefaultTopologyProvider.triggerRecompute().
synchronized void org.onosproject.net.topology.impl.DefaultTopologyProvider.deactivate (ComponentContext context)
Definition at line 143 of file DefaultTopologyProvider.java.
void org.onosproject.net.topology.impl.DefaultTopologyProvider.modified (ComponentContext context)
Definition at line 159 of file DefaultTopologyProvider.java.
Referenced by org.onosproject.net.topology.impl.DefaultTopologyProvider.activate().
void org.onosproject.net.topology.impl.DefaultTopologyProvider.triggerRecompute ()
Triggers topology recomputation.
Implements org.onosproject.net.topology.TopologyProvider.
Definition at line 200 of file DefaultTopologyProvider.java.
Referenced by org.onosproject.net.topology.impl.DefaultTopologyProvider.activate().
Member Data Documentation
ComponentConfigService org.onosproject.net.topology.impl.DefaultTopologyProvider.cfgService protected
Definition at line 106 of file DefaultTopologyProvider.java.
DeviceService org.onosproject.net.topology.impl.DefaultTopologyProvider.deviceService protected
Definition at line 100 of file DefaultTopologyProvider.java.
LinkService org.onosproject.net.topology.impl.DefaultTopologyProvider.linkService protected
Definition at line 103 of file DefaultTopologyProvider.java.
TopologyProviderRegistry org.onosproject.net.topology.impl.DefaultTopologyProvider.providerRegistry protected
Definition at line 97 of file DefaultTopologyProvider.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/topology/impl/DefaultTopologyProvider.java