onos: org.onosproject.driver.extensions.NiciraResubmit Class Reference
org.onosproject.driver.extensions.NiciraResubmit Class Reference
Nicira resubmit extension instruction.
Public Member Functions
NiciraResubmit (PortNumber inPort)
Creates a new resubmit instruction with a particular inPort.
PortNumber inPort ()
Gets the inPort.
ExtensionTreatmentType type ()
Gets the type of the extension instruction.
void deserialize (byte[] data)
Deserialize the extension instruction from a byte array.
byte[] serialize ()
Serialize the extension instruction to a byte array.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.flow.instructions.AbstractExtensionTreatment
List< String > getProperties ()
Gets a list of all properties on the extension instruction.
Detailed Description
Nicira resubmit extension instruction.
Definition at line 33 of file NiciraResubmit.java.
Constructor & Destructor Documentation
org.onosproject.driver.extensions.NiciraResubmit.NiciraResubmit (PortNumber inPort)
Creates a new resubmit instruction with a particular inPort.
Parameters
inPort in port number
Definition at line 54 of file NiciraResubmit.java.
References org.onosproject.driver.extensions.NiciraResubmit.inPort().
Member Function Documentation
void org.onosproject.driver.extensions.NiciraResubmit.deserialize (byte[] data)
Deserialize the extension instruction from a byte array.
The properties of this object will be overwritten with the data in the byte array.
Parameters
data input byte array
Implements org.onosproject.net.flow.instructions.ExtensionTreatment.
Definition at line 74 of file NiciraResubmit.java.
References org.onosproject.driver.extensions.NiciraResubmit.inPort().
boolean org.onosproject.driver.extensions.NiciraResubmit.equals (Object obj)
Definition at line 89 of file NiciraResubmit.java.
References create-flow.inPort, and org.onosproject.driver.extensions.NiciraResubmit.inPort().
int org.onosproject.driver.extensions.NiciraResubmit.hashCode ()
Definition at line 84 of file NiciraResubmit.java.
References org.onosproject.driver.extensions.NiciraResubmit.inPort().
PortNumber org.onosproject.driver.extensions.NiciraResubmit.inPort ()
Gets the inPort.
Returns
inPort
Definition at line 64 of file NiciraResubmit.java.
Referenced by org.onosproject.driver.extensions.NiciraResubmit.deserialize(), org.onosproject.driver.extensions.NiciraResubmit.equals(), org.onosproject.driver.extensions.NiciraResubmit.hashCode(), org.onosproject.driver.extensions.NiciraResubmit.NiciraResubmit(), org.onosproject.driver.extensions.NiciraResubmit.serialize(), and org.onosproject.driver.extensions.NiciraResubmit.toString().
byte [] org.onosproject.driver.extensions.NiciraResubmit.serialize ()
Serialize the extension instruction to a byte array.
Returns
byte array
Implements org.onosproject.net.flow.instructions.ExtensionTreatment.
Definition at line 79 of file NiciraResubmit.java.
References org.onosproject.driver.extensions.NiciraResubmit.inPort().
String org.onosproject.driver.extensions.NiciraResubmit.toString ()
Definition at line 102 of file NiciraResubmit.java.
References org.onosproject.driver.extensions.NiciraResubmit.inPort().
ExtensionTreatmentType org.onosproject.driver.extensions.NiciraResubmit.type ()
Gets the type of the extension instruction.
Returns
type
Implements org.onosproject.net.flow.instructions.ExtensionTreatment.
Definition at line 69 of file NiciraResubmit.java.
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/extensions/NiciraResubmit.java