onos: org.onosproject.pcepio.types.NexthopIPv6addressTlv Class Reference
org.onosproject.pcepio.types.NexthopIPv6addressTlv Class Reference
NexthopIPv6addressTlv provides Ipv6 address of next hop.
Public Member Functions
NexthopIPv6addressTlv (byte[] rawValue)
Constructor to initialize IP address for next hop IPv6 address tlv.
byte[] getBytes ()
Returns next hop IPv6 address.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static NexthopIPv6addressTlv of (final byte[] raw)
Creates next hop IPv6 address tlv.
static NexthopIPv6addressTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of NexthopIPv6addressTlv.
Static Public Attributes
static final short TYPE = 100
static final short LENGTH = 20
static final short VALUE_LENGTH = 16
static final NexthopIPv6addressTlv NONE = new NexthopIPv6addressTlv(NONE_VAL)
static final NexthopIPv6addressTlv NO_MASK = new NexthopIPv6addressTlv(NO_MASK_VAL)
static final NexthopIPv6addressTlv FULL_MASK = NONE
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(NexthopIPv6addressTlv.class)
Detailed Description
NexthopIPv6addressTlv provides Ipv6 address of next hop.
Definition at line 32 of file NexthopIPv6addressTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.NexthopIPv6addressTlv.NexthopIPv6addressTlv (byte[] rawValue)
Constructor to initialize IP address for next hop IPv6 address tlv.
Parameters
rawValue value of Next hop ipAddress
Definition at line 73 of file NexthopIPv6addressTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopIPv6addressTlv.equals(), and org.onosproject.pcepio.types.NexthopIPv6addressTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.NexthopIPv6addressTlv.equals (Object obj)
Definition at line 143 of file NexthopIPv6addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv6addressTlv.NexthopIPv6addressTlv().
byte [] org.onosproject.pcepio.types.NexthopIPv6addressTlv.getBytes ()
Returns next hop IPv6 address.
Returns
next hop IPv6 address
Definition at line 118 of file NexthopIPv6addressTlv.java.
short org.onosproject.pcepio.types.NexthopIPv6addressTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 133 of file NexthopIPv6addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv6addressTlv.LENGTH.
short org.onosproject.pcepio.types.NexthopIPv6addressTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 128 of file NexthopIPv6addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv6addressTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.NexthopIPv6addressTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 123 of file NexthopIPv6addressTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.NexthopIPv6addressTlv.hashCode ()
Definition at line 138 of file NexthopIPv6addressTlv.java.
static NexthopIPv6addressTlv org.onosproject.pcepio.types.NexthopIPv6addressTlv.of (final byte[] raw) static
Creates next hop IPv6 address tlv.
Parameters
raw value of Next hop ipAddress
Returns
object of NexthopIPv6addressTlv
Definition at line 85 of file NexthopIPv6addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv6addressTlv.NexthopIPv6addressTlv(), org.onosproject.pcepio.types.NexthopIPv6addressTlv.NO_MASK, and org.onosproject.pcepio.types.NexthopIPv6addressTlv.NONE.
static NexthopIPv6addressTlv org.onosproject.pcepio.types.NexthopIPv6addressTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of NexthopIPv6addressTlv.
Parameters
c type of channel buffer
Returns
object of NexthopIPv6addressTlv
Definition at line 169 of file NexthopIPv6addressTlv.java.
String org.onosproject.pcepio.types.NexthopIPv6addressTlv.toString ()
Definition at line 176 of file NexthopIPv6addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv6addressTlv.LENGTH, and org.onosproject.pcepio.types.NexthopIPv6addressTlv.TYPE.
int org.onosproject.pcepio.types.NexthopIPv6addressTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 155 of file NexthopIPv6addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv6addressTlv.LENGTH, and org.onosproject.pcepio.types.NexthopIPv6addressTlv.TYPE.
Member Data Documentation
final NexthopIPv6addressTlv org.onosproject.pcepio.types.NexthopIPv6addressTlv.FULL_MASK = NONE static
Definition at line 64 of file NexthopIPv6addressTlv.java.
final short org.onosproject.pcepio.types.NexthopIPv6addressTlv.LENGTH = 20 static
Definition at line 54 of file NexthopIPv6addressTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopIPv6addressTlv.getLength(), org.onosproject.pcepio.types.NexthopIPv6addressTlv.toString(), and org.onosproject.pcepio.types.NexthopIPv6addressTlv.write().
final Logger org.onosproject.pcepio.types.NexthopIPv6addressTlv.log = LoggerFactory.getLogger(NexthopIPv6addressTlv.class) static protected
Definition at line 50 of file NexthopIPv6addressTlv.java.
final NexthopIPv6addressTlv org.onosproject.pcepio.types.NexthopIPv6addressTlv.NO_MASK = new NexthopIPv6addressTlv(NO_MASK_VAL) static
Definition at line 63 of file NexthopIPv6addressTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopIPv6addressTlv.of().
final NexthopIPv6addressTlv org.onosproject.pcepio.types.NexthopIPv6addressTlv.NONE = new NexthopIPv6addressTlv(NONE_VAL) static
Definition at line 58 of file NexthopIPv6addressTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopIPv6addressTlv.of().
final short org.onosproject.pcepio.types.NexthopIPv6addressTlv.TYPE = 100 static
Definition at line 52 of file NexthopIPv6addressTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopIPv6addressTlv.getType(), org.onosproject.pcepio.types.NexthopIPv6addressTlv.toString(), and org.onosproject.pcepio.types.NexthopIPv6addressTlv.write().
final short org.onosproject.pcepio.types.NexthopIPv6addressTlv.VALUE_LENGTH = 16 static
Definition at line 55 of file NexthopIPv6addressTlv.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.parseOptionalTlv().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/NexthopIPv6addressTlv.java