onos: org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey Class Reference
org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey Class Reference
Class definition of Key for Subnet to NextObjective store.
Public Member Functions
SubnetNextObjectiveStoreKey (DeviceId deviceId, IpPrefix prefix)
DeviceId deviceId ()
Gets device id in this SubnetNextObjectiveStoreKey.
IpPrefix prefix ()
Gets subnet information in this SubnetNextObjectiveStoreKey.
boolean equals (Object o)
int hashCode ()
String toString ()
Detailed Description
Class definition of Key for Subnet to NextObjective store.
Definition at line 27 of file SubnetNextObjectiveStoreKey.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.SubnetNextObjectiveStoreKey (DeviceId deviceId, IpPrefix prefix)
Definition at line 31 of file SubnetNextObjectiveStoreKey.java.
References org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.deviceId(), and org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.prefix().
Referenced by org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.equals().
Member Function Documentation
DeviceId org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.deviceId ()
Gets device id in this SubnetNextObjectiveStoreKey.
Returns
device id
Definition at line 42 of file SubnetNextObjectiveStoreKey.java.
References find-flow.deviceId.
Referenced by org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.hashCode(), org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.SubnetNextObjectiveStoreKey(), and org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.toString().
boolean org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.equals (Object o)
Definition at line 56 of file SubnetNextObjectiveStoreKey.java.
References onosUploadBits.prefix, and org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.SubnetNextObjectiveStoreKey().
int org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.hashCode ()
Definition at line 70 of file SubnetNextObjectiveStoreKey.java.
References org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.deviceId(), and org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.prefix().
IpPrefix org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.prefix ()
Gets subnet information in this SubnetNextObjectiveStoreKey.
Returns
subnet information
Definition at line 51 of file SubnetNextObjectiveStoreKey.java.
References onosUploadBits.prefix.
Referenced by org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.hashCode(), org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.SubnetNextObjectiveStoreKey(), and org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.toString().
String org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.toString ()
Definition at line 75 of file SubnetNextObjectiveStoreKey.java.
References org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.deviceId(), and org.onosproject.segmentrouting.grouphandler.SubnetNextObjectiveStoreKey.prefix().
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/grouphandler/SubnetNextObjectiveStoreKey.java