onos: org.onosproject.net.intent.IntentId Class Reference
org.onosproject.net.intent.IntentId Class Reference
Intent identifier suitable as an external key.
Public Member Functions
long fingerprint ()
Returns the backing value.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static IntentId valueOf (long value)
Creates an intent identifier from the specified long representation.
Detailed Description
Intent identifier suitable as an external key.
This class is immutable.
Definition at line 26 of file IntentId.java.
Member Function Documentation
boolean org.onosproject.net.intent.IntentId.equals (Object obj)
Definition at line 71 of file IntentId.java.
long org.onosproject.net.intent.IntentId.fingerprint ()
Returns the backing value.
Returns
the value
Definition at line 61 of file IntentId.java.
Referenced by org.onosproject.net.intent.IntentIdTest.testConstruction().
int org.onosproject.net.intent.IntentId.hashCode ()
Definition at line 66 of file IntentId.java.
String org.onosproject.net.intent.IntentId.toString ()
Definition at line 83 of file IntentId.java.
static IntentId org.onosproject.net.intent.IntentId.valueOf (long value) static
Creates an intent identifier from the specified long representation.
Parameters
value long value
Returns
intent identifier
Definition at line 36 of file IntentId.java.
Referenced by org.onosproject.store.serializers.KryoSerializerTest.testDefaultLinkResourceRequest(), org.onosproject.store.serializers.KryoSerializerTest.testResourceAllocation(), and org.onosproject.net.intent.IntentIdTest.valueOf().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/IntentId.java