onos: org.onlab.packet.pim.PIMAddrSource Class Reference
org.onlab.packet.pim.PIMAddrSource Class Reference
Public Member Functions
PIMAddrSource (String addr)
PIM Encoded Source Address.
PIMAddrSource (IpPrefix spfx)
PIM Encoded Source Address.
PIMAddrSource ()
PIM Encoded Group Address.
void setAddr (String addr)
PIM Encoded Source Address.
void setAddr (IpPrefix spfx)
PIM Encoded Source Address.
byte getFamily ()
Get the IP family of this address: 4 or 6.
IpAddress getAddr ()
Get the address of this encoded address.
int getMasklen ()
Get the masklen of the group address.
boolean getSBit ()
Return the sparse bit.
boolean getWBit ()
Return the wBit, used in Join/Prune messages.
boolean getRBit ()
Return the rBit.
int getByteSize ()
The size in bytes of a serialized address.
byte[] serialize ()
PIMAddrSource deserialize (byte[] data, int offset, int length) throws DeserializationException
PIMAddrSource deserialize (ByteBuffer bb) throws DeserializationException
int hashCode ()
boolean equals (final Object obj)
Static Public Attributes
static final int ENC_SOURCE_IPV4_BYTE_LENGTH = 4 + Ip4Address.BYTE_LENGTH
static final int ENC_SOURCE_IPV6_BYTE_LENGTH = 4 + Ip6Address.BYTE_LENGTH
Detailed Description
Definition at line 29 of file PIMAddrSource.java.
Constructor & Destructor Documentation
org.onlab.packet.pim.PIMAddrSource.PIMAddrSource (String addr)
PIM Encoded Source Address.
Parameters
addr IPv4 or IPv6
Definition at line 47 of file PIMAddrSource.java.
org.onlab.packet.pim.PIMAddrSource.PIMAddrSource (IpPrefix spfx)
PIM Encoded Source Address.
Parameters
spfx IPv4 or IPv6
Definition at line 57 of file PIMAddrSource.java.
org.onlab.packet.pim.PIMAddrSource.PIMAddrSource ()
PIM Encoded Group Address.
Definition at line 65 of file PIMAddrSource.java.
Referenced by org.onlab.packet.pim.PIMAddrSource.equals().
Member Function Documentation
PIMAddrSource org.onlab.packet.pim.PIMAddrSource.deserialize (byte[] data, int offset, int length) throws DeserializationException
Definition at line 191 of file PIMAddrSource.java.
References find-link-in-cluster.length.
PIMAddrSource org.onlab.packet.pim.PIMAddrSource.deserialize (ByteBuffer bb) throws DeserializationException
Definition at line 196 of file PIMAddrSource.java.
References org.onlab.packet.PIM.ADDRESS_FAMILY_IP4, org.onlab.packet.PIM.ADDRESS_FAMILY_IP6, org.onlab.packet.pim.PIMAddrSource.ENC_SOURCE_IPV4_BYTE_LENGTH, and org.onlab.packet.pim.PIMAddrSource.ENC_SOURCE_IPV6_BYTE_LENGTH.
boolean org.onlab.packet.pim.PIMAddrSource.equals (final Object obj)
Definition at line 261 of file PIMAddrSource.java.
References org.onlab.packet.IpAddress.equals(), and org.onlab.packet.pim.PIMAddrSource.PIMAddrSource().
IpAddress org.onlab.packet.pim.PIMAddrSource.getAddr ()
Get the address of this encoded address.
Returns
source address
Definition at line 113 of file PIMAddrSource.java.
int org.onlab.packet.pim.PIMAddrSource.getByteSize ()
The size in bytes of a serialized address.
Returns
the number of bytes when serialized
Definition at line 158 of file PIMAddrSource.java.
References org.onlab.packet.PIM.ADDRESS_FAMILY_IP4, org.onlab.packet.PIM.ADDRESS_FAMILY_IP6, and onos.size.
byte org.onlab.packet.pim.PIMAddrSource.getFamily ()
Get the IP family of this address: 4 or 6.
Returns
the IP address family
Definition at line 104 of file PIMAddrSource.java.
int org.onlab.packet.pim.PIMAddrSource.getMasklen ()
Get the masklen of the group address.
Returns
the masklen
Definition at line 122 of file PIMAddrSource.java.
boolean org.onlab.packet.pim.PIMAddrSource.getRBit ()
Return the rBit.
Used by Rendezvous Point.
Returns
the rBit.
Definition at line 149 of file PIMAddrSource.java.
boolean org.onlab.packet.pim.PIMAddrSource.getSBit ()
Return the sparse bit.
Returns
true or false
Definition at line 131 of file PIMAddrSource.java.
boolean org.onlab.packet.pim.PIMAddrSource.getWBit ()
Return the wBit, used in Join/Prune messages.
Returns
return true or false.
Definition at line 140 of file PIMAddrSource.java.
int org.onlab.packet.pim.PIMAddrSource.hashCode ()
Definition at line 244 of file PIMAddrSource.java.
byte [] org.onlab.packet.pim.PIMAddrSource.serialize ()
Definition at line 164 of file PIMAddrSource.java.
References org.onlab.packet.pim.PIMAddrSource.ENC_SOURCE_IPV4_BYTE_LENGTH, and org.onlab.packet.pim.PIMAddrSource.ENC_SOURCE_IPV6_BYTE_LENGTH.
void org.onlab.packet.pim.PIMAddrSource.setAddr (String addr)
PIM Encoded Source Address.
Parameters
addr IPv4 or IPv6
Definition at line 83 of file PIMAddrSource.java.
void org.onlab.packet.pim.PIMAddrSource.setAddr (IpPrefix spfx)
PIM Encoded Source Address.
Parameters
spfx IPv4 or IPv6 address prefix
Definition at line 93 of file PIMAddrSource.java.
References org.onlab.packet.PIM.ADDRESS_FAMILY_IP4, org.onlab.packet.PIM.ADDRESS_FAMILY_IP6, and org.onlab.packet.IpAddress.isIp4().
Member Data Documentation
final int org.onlab.packet.pim.PIMAddrSource.ENC_SOURCE_IPV4_BYTE_LENGTH = 4 + Ip4Address.BYTE_LENGTH static
Definition at line 39 of file PIMAddrSource.java.
Referenced by org.onlab.packet.pim.PIMAddrSource.deserialize(), org.onlab.packet.pim.PIMJoinPrune.deserializer(), and org.onlab.packet.pim.PIMAddrSource.serialize().
final int org.onlab.packet.pim.PIMAddrSource.ENC_SOURCE_IPV6_BYTE_LENGTH = 4 + Ip6Address.BYTE_LENGTH static
Definition at line 40 of file PIMAddrSource.java.
Referenced by org.onlab.packet.pim.PIMAddrSource.deserialize(), org.onlab.packet.pim.PIMJoinPrune.deserializer(), and org.onlab.packet.pim.PIMAddrSource.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/pim/PIMAddrSource.java