onos: org.onosproject.net.intent.TwoWayP2PIntentTest Class Reference
org.onosproject.net.intent.TwoWayP2PIntentTest Class Reference
Unit tests for the TwoWayP2PIntent class.
Public Member Functions
void twoWatP2PIntentTestSetUp ()
void testImmutability ()
Checks that the TwoWayP2PIntent class is immutable.
void testEquals ()
Checks the operation of equals(), hashCode() and toString() methods.
void testContents ()
Checks that the optical path ntent objects are created correctly.
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Additional Inherited Members
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
Unit tests for the TwoWayP2PIntent class.
Definition at line 35 of file TwoWayP2PIntentTest.java.
Member Function Documentation
void org.onosproject.net.intent.TwoWayP2PIntentTest.testContents ()
Checks that the optical path ntent objects are created correctly.
Definition at line 92 of file TwoWayP2PIntentTest.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.Intent.priority(), org.onosproject.net.intent.ConnectivityIntent.selector(), and org.onosproject.net.intent.ConnectivityIntent.treatment().
void org.onosproject.net.intent.TwoWayP2PIntentTest.testEquals ()
Checks the operation of equals(), hashCode() and toString() methods.
Definition at line 81 of file TwoWayP2PIntentTest.java.
void org.onosproject.net.intent.TwoWayP2PIntentTest.testImmutability ()
Checks that the TwoWayP2PIntent class is immutable.
Definition at line 73 of file TwoWayP2PIntentTest.java.
void org.onosproject.net.intent.TwoWayP2PIntentTest.twoWatP2PIntentTestSetUp ()
Definition at line 46 of file TwoWayP2PIntentTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/intent/TwoWayP2PIntentTest.java