onos: org.onlab.util.BandwidthTest Class Reference
org.onlab.util.BandwidthTest Class Reference
Unit tests for Bandwidth.
Public Member Functions
void testEquality ()
Tests equality of Bandwidth instances.
void testAdd ()
Tests add operation of two Bandwidths.
void testSubtract ()
Tests subtract operation of two Bandwidths.
void testLessThan ()
Tests if the first object is less than the second object.
void testGreaterThan ()
Tests if the first object is greater than the second object.
Detailed Description
Unit tests for Bandwidth.
Definition at line 29 of file BandwidthTest.java.
Member Function Documentation
void org.onlab.util.BandwidthTest.testAdd ()
Tests add operation of two Bandwidths.
Definition at line 49 of file BandwidthTest.java.
References org.onlab.util.Bandwidth.add().
void org.onlab.util.BandwidthTest.testEquality ()
Tests equality of Bandwidth instances.
Definition at line 38 of file BandwidthTest.java.
References org.onlab.util.Bandwidth.gbps().
void org.onlab.util.BandwidthTest.testGreaterThan ()
Tests if the first object is greater than the second object.
Definition at line 78 of file BandwidthTest.java.
void org.onlab.util.BandwidthTest.testLessThan ()
Tests if the first object is less than the second object.
Definition at line 69 of file BandwidthTest.java.
void org.onlab.util.BandwidthTest.testSubtract ()
Tests subtract operation of two Bandwidths.
Definition at line 59 of file BandwidthTest.java.
References org.onlab.util.Bandwidth.subtract().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/util/BandwidthTest.java