onos: org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V > Class Reference
org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V > Class Reference
Distributed Map implementation which uses optimistic replication and gossip based techniques to provide an eventually consistent data store.
Public Member Functions
int size ()
boolean isEmpty ()
boolean containsKey (K key)
boolean containsValue (V value)
V get (K key)
void put (K key, V value)
V remove (K key)
void remove (K key, V value)
V compute (K key, BiFunction< K, V, V > recomputeFunction)
void putAll (Map<?extends K,?extends V > m)
void clear ()
Set< K > keySet ()
Collection< V > values ()
Set< Map.Entry< K, V > > entrySet ()
void addListener (EventuallyConsistentMapListener< K, V > listener)
void removeListener (EventuallyConsistentMapListener< K, V > listener)
void destroy ()
Detailed Description
Distributed Map implementation which uses optimistic replication and gossip based techniques to provide an eventually consistent data store.
Definition at line 75 of file EventuallyConsistentMapImpl.java.
Member Function Documentation
void org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.addListener (EventuallyConsistentMapListener< K, V > listener)
Definition at line 484 of file EventuallyConsistentMapImpl.java.
void org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.clear ()
Definition at line 430 of file EventuallyConsistentMapImpl.java.
V org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.compute (K key, BiFunction< K, V, V > recomputeFunction)
Definition at line 392 of file EventuallyConsistentMapImpl.java.
References org.onosproject.store.ecmap.MapValue< V >.isNewerThan().
boolean org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.containsKey (K key)
Definition at line 289 of file EventuallyConsistentMapImpl.java.
boolean org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.containsValue (V value)
Definition at line 296 of file EventuallyConsistentMapImpl.java.
void org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.destroy ()
Definition at line 498 of file EventuallyConsistentMapImpl.java.
Set<Map.Entry<K, V> > org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.entrySet ()
Definition at line 450 of file EventuallyConsistentMapImpl.java.
V org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.get (K key)
Definition at line 306 of file EventuallyConsistentMapImpl.java.
References org.onosproject.store.ecmap.MapValue< V >.get(), and org.onosproject.store.ecmap.MapValue< V >.isTombstone().
boolean org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.isEmpty ()
Definition at line 283 of file EventuallyConsistentMapImpl.java.
References onos.size.
Set<K> org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.keySet ()
Definition at line 437 of file EventuallyConsistentMapImpl.java.
void org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.put (K key, V value)
Definition at line 315 of file EventuallyConsistentMapImpl.java.
void org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.putAll (Map<?extends K,?extends V > m)
Definition at line 424 of file EventuallyConsistentMapImpl.java.
V org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.remove (K key)
Definition at line 328 of file EventuallyConsistentMapImpl.java.
void org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.remove (K key, V value)
Definition at line 335 of file EventuallyConsistentMapImpl.java.
void org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.removeListener (EventuallyConsistentMapListener< K, V > listener)
Definition at line 491 of file EventuallyConsistentMapImpl.java.
int org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.size ()
Definition at line 276 of file EventuallyConsistentMapImpl.java.
References onos.size.
Collection<V> org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.values ()
Definition at line 444 of file EventuallyConsistentMapImpl.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/ecmap/EventuallyConsistentMapImpl.java