onos: org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType Class Reference
org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType Class Reference
a JSON object that describes the type of a database column, with key and value.
Public Member Functions
KeyValuedColumnType (BaseType keyType, BaseType valueType, int min, int max)
Constructs a KeyValuedColumnType object.
BaseType keyType ()
Get keyType.
BaseType valueType ()
Get valueType.
int min ()
Get min.
int max ()
Get max.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
a JSON object that describes the type of a database column, with key and value.
Refer to RFC 7047 Section 3.2.
Definition at line 27 of file KeyValuedColumnType.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.KeyValuedColumnType (BaseType keyType, BaseType valueType, int min, int max)
Constructs a KeyValuedColumnType object.
Parameters
keyType BaseType entity
valueType BaseType entity
min min constraint
max max constraint
Definition at line 40 of file KeyValuedColumnType.java.
References org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.keyType(), org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.max(), org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.min(), and org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.valueType().
Referenced by org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.equals().
Member Function Documentation
boolean org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.equals (Object obj)
Definition at line 88 of file KeyValuedColumnType.java.
References org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.KeyValuedColumnType().
int org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.hashCode ()
Definition at line 83 of file KeyValuedColumnType.java.
References org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.keyType(), org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.max(), org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.min(), and org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.valueType().
BaseType org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.keyType ()
Get keyType.
Returns
keyType
Definition at line 54 of file KeyValuedColumnType.java.
Referenced by org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.hashCode(), org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.KeyValuedColumnType(), and org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.toString().
int org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.max ()
Get max.
Returns
max
Definition at line 78 of file KeyValuedColumnType.java.
Referenced by org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.hashCode(), org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.KeyValuedColumnType(), and org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.toString().
int org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.min ()
Get min.
Returns
min
Definition at line 70 of file KeyValuedColumnType.java.
Referenced by org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.hashCode(), org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.KeyValuedColumnType(), and org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.toString().
String org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.toString ()
Definition at line 103 of file KeyValuedColumnType.java.
References org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.keyType(), org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.max(), org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.min(), and org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.valueType().
BaseType org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.valueType ()
Get valueType.
Returns
valueType
Definition at line 62 of file KeyValuedColumnType.java.
Referenced by org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.hashCode(), org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.KeyValuedColumnType(), and org.onosproject.ovsdb.rfc.schema.type.KeyValuedColumnType.toString().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/schema/type/KeyValuedColumnType.java