onos: org.onlab.netty.InternalMessage Class Reference
org.onlab.netty.InternalMessage Class Reference
Internal message representation with additional attributes for supporting, synchronous request/reply behavior.
Public Member Functions
InternalMessage (long id, Endpoint sender, String type, byte[] payload)
long id ()
String type ()
Endpoint sender ()
byte[] payload ()
String toString ()
Detailed Description
Internal message representation with additional attributes for supporting, synchronous request/reply behavior.
Definition at line 27 of file InternalMessage.java.
Constructor & Destructor Documentation
org.onlab.netty.InternalMessage.InternalMessage (long id, Endpoint sender, String type, byte[] payload)
Definition at line 34 of file InternalMessage.java.
References org.onlab.netty.InternalMessage.id(), org.onlab.netty.InternalMessage.payload(), org.onlab.netty.InternalMessage.sender(), and org.onlab.netty.InternalMessage.type().
Member Function Documentation
long org.onlab.netty.InternalMessage.id ()
Definition at line 41 of file InternalMessage.java.
Referenced by org.onlab.netty.InternalMessage.InternalMessage().
byte [] org.onlab.netty.InternalMessage.payload ()
Definition at line 53 of file InternalMessage.java.
Referenced by org.onlab.netty.InternalMessage.InternalMessage(), and org.onlab.netty.InternalMessage.toString().
Endpoint org.onlab.netty.InternalMessage.sender ()
Definition at line 49 of file InternalMessage.java.
Referenced by org.onlab.netty.InternalMessage.InternalMessage(), and org.onlab.netty.InternalMessage.toString().
String org.onlab.netty.InternalMessage.toString ()
Definition at line 58 of file InternalMessage.java.
References org.onlab.netty.InternalMessage.payload(), org.onlab.netty.InternalMessage.sender(), and org.onlab.netty.InternalMessage.type().
String org.onlab.netty.InternalMessage.type ()
Definition at line 45 of file InternalMessage.java.
Referenced by org.onlab.netty.InternalMessage.InternalMessage(), and org.onlab.netty.InternalMessage.toString().
The documentation for this class was generated from the following file:
utils/netty/src/main/java/org/onlab/netty/InternalMessage.java