onos: org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext Class Reference
org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext Class Reference
Context for decode parameters.
Public Member Functions
JsonReadContext ()
Constructs a JsonReadContext object.
Stack< Byte > getBufStack ()
Return bufStack.
void setBufStack (Stack< Byte > bufStack)
Set bufStack, used for match the braces and double quotes.
boolean isStartMatch ()
Return isStartMatch.
void setStartMatch (boolean isStartMatch)
Set isStartMatch.
int getLastReadBytes ()
Return lastReadBytes.
void setLastReadBytes (int lastReadBytes)
Set lastReadBytes.
Detailed Description
Context for decode parameters.
Definition at line 23 of file JsonReadContext.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.JsonReadContext ()
Constructs a JsonReadContext object.
This class only need initial parameter value for the readToJsonNode method of JsonRpcReaderUtil entity.
Definition at line 33 of file JsonReadContext.java.
References org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.isStartMatch().
Member Function Documentation
Stack<Byte> org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.getBufStack ()
Return bufStack.
Returns
bufStack
Definition at line 43 of file JsonReadContext.java.
int org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.getLastReadBytes ()
Return lastReadBytes.
Returns
lastReadBytes
Definition at line 75 of file JsonReadContext.java.
boolean org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.isStartMatch ()
Return isStartMatch.
Returns
isStartMatch
Definition at line 59 of file JsonReadContext.java.
Referenced by org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.JsonReadContext(), and org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.setStartMatch().
void org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.setBufStack (Stack< Byte > bufStack)
Set bufStack, used for match the braces and double quotes.
Parameters
bufStack Stack of Byte
Definition at line 51 of file JsonReadContext.java.
void org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.setLastReadBytes (int lastReadBytes)
Set lastReadBytes.
Parameters
lastReadBytes the bytes for last decoding incomplete record
Definition at line 83 of file JsonReadContext.java.
void org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.setStartMatch (boolean isStartMatch)
Set isStartMatch.
Parameters
isStartMatch mark whether the matching has started
Definition at line 67 of file JsonReadContext.java.
References org.onosproject.ovsdb.rfc.jsonrpc.JsonReadContext.isStartMatch().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/jsonrpc/JsonReadContext.java