onos: org.onosproject.net.DefaultAnnotations Class Reference
org.onosproject.net.DefaultAnnotations Class Reference
Represents a set of simple annotations that can be used to add arbitrary attributes to various parts of the data model.
Classes
class Builder
Facility for gradually building model annotations.
Public Member Functions
boolean equals (Object o)
int hashCode ()
HashMap< String, String > asMap ()
Returns the annotations as a map.
Set< String > keys ()
Returns the set of keys for available annotations.
Returns
annotation keys
Note that this set includes keys for any attributes tagged for removal.
String value (String key)
Returns the value of the specified annotation.
boolean isRemoved (String key)
Indicates whether the specified key has been tagged as removed.
String toString ()
Static Public Member Functions
static Builder builder ()
Creates a new annotations builder.
static DefaultAnnotations merge (DefaultAnnotations annotations, SparseAnnotations sparseAnnotations)
Merges the specified base set of annotations and additional sparse annotations into new combined annotations.
static SparseAnnotations union (SparseAnnotations annotations, SparseAnnotations sparseAnnotations)
Creates the union of two given SparseAnnotations.
Static Public Attributes
static final SparseAnnotations EMPTY = DefaultAnnotations.builder().build()
Detailed Description
Represents a set of simple annotations that can be used to add arbitrary attributes to various parts of the data model.
Definition at line 32 of file DefaultAnnotations.java.
Member Function Documentation
HashMap<String, String> org.onosproject.net.DefaultAnnotations.asMap ()
Returns the annotations as a map.
Returns
a copy of the contents of the annotations as a map.
Definition at line 68 of file DefaultAnnotations.java.
static Builder org.onosproject.net.DefaultAnnotations.builder () static
Creates a new annotations builder.
Returns
new annotations builder
Definition at line 86 of file DefaultAnnotations.java.
Referenced by org.onosproject.net.DefaultDeviceTest.annotations(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByDeviceAnnotationConfig(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByPortConfig(), and org.onosproject.provider.lldp.impl.LldpLinkProviderTest.switchSuppressedByAnnotation().
boolean org.onosproject.net.DefaultAnnotations.equals (Object o)
Definition at line 44 of file DefaultAnnotations.java.
int org.onosproject.net.DefaultAnnotations.hashCode ()
Definition at line 59 of file DefaultAnnotations.java.
boolean org.onosproject.net.DefaultAnnotations.isRemoved (String key)
Indicates whether the specified key has been tagged as removed.
This is used for merging sparse annotation sets.
Parameters
key annotation key
Returns
true if the previous annotation has been tagged for removal
Implements org.onosproject.net.SparseAnnotations.
Definition at line 191 of file DefaultAnnotations.java.
Set<String> org.onosproject.net.DefaultAnnotations.keys ()
Returns the set of keys for available annotations.
Returns
annotation keys
Note that this set includes keys for any attributes tagged for removal.
Note that this set includes keys for any attributes tagged for removal.
Implements org.onosproject.net.SparseAnnotations.
Definition at line 180 of file DefaultAnnotations.java.
Referenced by org.onosproject.net.NetTestTools.assertAnnotationsEquals(), org.onosproject.net.DefaultAnnotationsTest.basics(), org.onosproject.net.DefaultAnnotationsTest.empty(), org.onosproject.net.DefaultAnnotationsTest.merge(), org.onosproject.net.DefaultAnnotationsTest.noopMerge(), org.onosproject.net.DefaultAnnotationsTest.remove(), and org.onosproject.net.DefaultAnnotationsTest.union().
static DefaultAnnotations org.onosproject.net.DefaultAnnotations.merge (DefaultAnnotations annotations, SparseAnnotations sparseAnnotations) static
Merges the specified base set of annotations and additional sparse annotations into new combined annotations.
If the supplied sparse annotations are empty, the original base annotations are returned. Any keys tagged for removal in the sparse annotations will be omitted in the resulting merged annotations.
Parameters
annotations base annotations
sparseAnnotations additional sparse annotations
Returns
combined annotations or the original base annotations if there are not additional annotations
Definition at line 102 of file DefaultAnnotations.java.
References org.onosproject.net.SparseAnnotations.isRemoved(), and org.onosproject.net.SparseAnnotations.keys().
Referenced by org.onosproject.net.DefaultAnnotationsTest.noopMerge().
String org.onosproject.net.DefaultAnnotations.toString ()
Definition at line 204 of file DefaultAnnotations.java.
static SparseAnnotations org.onosproject.net.DefaultAnnotations.union (SparseAnnotations annotations, SparseAnnotations sparseAnnotations) static
Creates the union of two given SparseAnnotations.
Unlike the merge(DefaultAnnotations, SparseAnnotations) method, result will be SparseAnnotations instead of Annotations.
A key tagged for removal will remain in the output SparseAnnotations, if the counterpart of the input does not contain the same key.
Parameters
annotations base annotations
sparseAnnotations additional sparse annotations
Returns
combined annotations or the original base annotations if there are not additional annotations
Definition at line 136 of file DefaultAnnotations.java.
References onos.size.
String org.onosproject.net.DefaultAnnotations.value (String key)
Returns the value of the specified annotation.
Parameters
key annotation key
Returns
annotation value
Implements org.onosproject.net.Annotations.
Definition at line 185 of file DefaultAnnotations.java.
Referenced by org.onosproject.net.NetTestTools.assertAnnotationsEquals(), org.onosproject.net.DefaultAnnotationsTest.basics(), and org.onosproject.net.DefaultAnnotationsTest.remove().
Member Data Documentation
final SparseAnnotations org.onosproject.net.DefaultAnnotations.EMPTY = DefaultAnnotations.builder().build() static
Definition at line 34 of file DefaultAnnotations.java.
Referenced by org.onosproject.net.link.impl.BasicLinkOperator.descriptionOf(), and org.onosproject.codec.impl.AnnotatedCodec< T extends Annotated >.extractAnnotations().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/DefaultAnnotations.java