onos: org.onosproject.net.PortNumber Class Reference
org.onosproject.net.PortNumber Class Reference
Representation of a port number.
Classes
enum Logical
Logical PortNumbers.
Public Member Functions
boolean isLogical ()
Indicates whether or not this port number is a reserved logical one or whether it corresponds to a normal physical port of a device or NIC.
long toLong ()
Returns the backing long value.
String name ()
Returns the backing string value.
boolean hasName ()
Indicates whether this port number was created with a port name, or only with a number.
String toString ()
int hashCode ()
boolean equals (Object obj)
Static Public Member Functions
static PortNumber portNumber (long number)
Returns the port number representing the specified long value.
static PortNumber portNumber (String string)
Returns the port number representing the specified string value.
static PortNumber portNumber (long number, String name)
Returns the port number representing the specified long value and name.
static PortNumber fromString (String s)
Returns PortNumber instance from String representation.
Static Public Attributes
static final PortNumber P0 = portNumber(0)
static final PortNumber IN_PORT = new PortNumber(IN_PORT_NUMBER)
static final PortNumber TABLE = new PortNumber(TABLE_NUMBER)
static final PortNumber NORMAL = new PortNumber(NORMAL_NUMBER)
static final PortNumber FLOOD = new PortNumber(FLOOD_NUMBER)
static final PortNumber ALL = new PortNumber(ALL_NUMBER)
static final PortNumber LOCAL = new PortNumber(LOCAL_NUMBER)
static final PortNumber CONTROLLER = new PortNumber(CONTROLLER_NUMBER)
Detailed Description
Representation of a port number.
Definition at line 33 of file PortNumber.java.
Member Function Documentation
boolean org.onosproject.net.PortNumber.equals (Object obj)
Definition at line 261 of file PortNumber.java.
Referenced by org.onosproject.store.trivial.SimpleDeviceStoreTest.testUpdatePorts(), and org.onosproject.store.device.impl.GossipDeviceStoreTest.testUpdatePorts().
static PortNumber org.onosproject.net.PortNumber.fromString (String s) static
Returns PortNumber instance from String representation.
Parameters
s String representation equivalent to PortNumber#toString()
Returns
PortNumber instance
Exceptions
IllegalArgumentException if given String was malformed
Definition at line 217 of file PortNumber.java.
References org.onosproject.net.PortNumber.name(), and org.onosproject.net.PortNumber.portNumber().
Referenced by org.onosproject.net.PortNumberTest.decimalPortNumberIsReconstructableFromString(), org.onosproject.net.PortNumberTest.logicalPortNumberIsReconstructableFromString(), and org.onosproject.net.PortNumberTest.namedPortNumberIsReconstructableFromString().
int org.onosproject.net.PortNumber.hashCode ()
Definition at line 256 of file PortNumber.java.
boolean org.onosproject.net.PortNumber.hasName ()
Indicates whether this port number was created with a port name, or only with a number.
Returns
true if port was created with name
Definition at line 185 of file PortNumber.java.
Referenced by org.onosproject.net.PortNumber.isLogical(), and org.onosproject.net.PortNumber.toString().
boolean org.onosproject.net.PortNumber.isLogical ()
Indicates whether or not this port number is a reserved logical one or whether it corresponds to a normal physical port of a device or NIC.
Returns
true if logical port number
Definition at line 153 of file PortNumber.java.
References org.onosproject.net.PortNumber.hasName().
Referenced by org.onosproject.net.PortNumber.toString().
String org.onosproject.net.PortNumber.name ()
Returns the backing string value.
Returns
port name as string value
Definition at line 175 of file PortNumber.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.net.PortNumber.fromString(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.net.PortNumber.toString().
static PortNumber org.onosproject.net.PortNumber.portNumber (long number) static
Returns the port number representing the specified long value.
Parameters
number port number as long value
Returns
port number
Definition at line 122 of file PortNumber.java.
Referenced by org.onosproject.flowanalyzer.MockLinkService.addLink(), org.onosproject.routing.config.BgpPeer.BgpPeer(), org.onosproject.routing.config.BgpSpeaker.BgpSpeaker(), org.onosproject.provider.nil.TopologySimulator.buildPorts(), org.onosproject.codec.impl.FlowRuleCodecTest.codecCriteriaFlowTest(), org.onosproject.net.device.impl.OpticalPortOperator.combine(), org.onosproject.codec.impl.IntentCodecTest.decodePointToPointIntent(), org.onosproject.cli.net.TunnelRemoveCommand.execute(), org.onosproject.cli.net.AddTestFlowsCommand.execute(), org.onosproject.cli.net.TunnelQueryCommand.execute(), org.onosproject.cli.net.TunnelReturnCommand.execute(), org.onosproject.cli.net.TunnelBorrowCommand.execute(), org.onosproject.cli.net.TunnelCreateCommand.execute(), org.onosproject.net.PortNumber.fromString(), org.onosproject.flowanalyzer.FlowAnalyzerTest.genFlow(), org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getPortNumbers(), org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getPorts(), org.onosproject.net.ConnectPoint.hostConnectPoint(), org.onosproject.routing.config.InterfaceAddress.InterfaceAddress(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByPortBlacklist(), org.onosproject.provider.pcep.tunnel.impl.PcepReleaseTunnelProviderTest.testCasePcepReleaseTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepSetupTunnelProviderTest.testCasePcepSetupTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProviderTest.testCasePcepSetupTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepUpdateTunnelProviderTest.testCasePcepUpdateTunnel(), org.onosproject.net.flow.DefaultTrafficSelectorTest.testCriteriaCreation(), org.onosproject.net.edgeservice.impl.EdgeManagerTest.testDeviceUpdates(), org.onosproject.net.edgeservice.impl.EdgeManagerTest.testEmit(), org.onosproject.net.group.impl.GroupManagerTest.testGroupOperationFailure(), org.onosproject.store.trivial.SimpleGroupStoreTest.testGroupOperationFailure(), org.onosproject.net.device.DeviceEventTest.withoutTime(), and org.onosproject.net.device.DeviceEventTest.withTime().
static PortNumber org.onosproject.net.PortNumber.portNumber (String string) static
Returns the port number representing the specified string value.
Parameters
string port number as string value
Returns
port number
Definition at line 132 of file PortNumber.java.
static PortNumber org.onosproject.net.PortNumber.portNumber (long number, String name) static
Returns the port number representing the specified long value and name.
Parameters
number port number as long value
name port name as string value
Returns
port number
Definition at line 143 of file PortNumber.java.
long org.onosproject.net.PortNumber.toLong ()
Returns the backing long value.
Returns
port number as long
Definition at line 166 of file PortNumber.java.
String org.onosproject.net.PortNumber.toString ()
Definition at line 243 of file PortNumber.java.
References org.onosproject.net.PortNumber.hasName(), org.onosproject.net.PortNumber.isLogical(), and org.onosproject.net.PortNumber.name().
Member Data Documentation
final PortNumber org.onosproject.net.PortNumber.ALL = new PortNumber(ALL_NUMBER) static
Definition at line 86 of file PortNumber.java.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processVlanIdFilter(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processVlanIdFilter().
final PortNumber org.onosproject.net.PortNumber.CONTROLLER = new PortNumber(CONTROLLER_NUMBER) static
Definition at line 88 of file PortNumber.java.
Referenced by org.onosproject.codec.impl.FlowRuleCodecTest.codecSimpleFlowTest(), org.onosproject.codec.impl.FlowRuleCodecTest.decodeInstructionsFlowTest(), org.onosproject.driver.pipeline.OltPipeline.forward(), org.onosproject.codec.impl.IntentCodecTest.intentWithTreatmentSelectorAndConstraints(), org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterIpPunts(), and org.onosproject.driver.pipeline.SpringOpenTTP.populateTableMissEntry().
final PortNumber org.onosproject.net.PortNumber.FLOOD = new PortNumber(FLOOD_NUMBER) static
Definition at line 85 of file PortNumber.java.
final PortNumber org.onosproject.net.PortNumber.IN_PORT = new PortNumber(IN_PORT_NUMBER) static
Definition at line 82 of file PortNumber.java.
Referenced by org.onosproject.net.group.GroupBucketTest.checkFailoverGroup().
final PortNumber org.onosproject.net.PortNumber.LOCAL = new PortNumber(LOCAL_NUMBER) static
Definition at line 87 of file PortNumber.java.
Referenced by org.onosproject.vtn.util.VtnData.getLocalTunnelPorts().
final PortNumber org.onosproject.net.PortNumber.NORMAL = new PortNumber(NORMAL_NUMBER) static
Definition at line 84 of file PortNumber.java.
final PortNumber org.onosproject.net.PortNumber.P0 = portNumber(0) static
Definition at line 35 of file PortNumber.java.
Referenced by org.onosproject.net.DefaultEdgeLink.createEdgeLink().
final PortNumber org.onosproject.net.PortNumber.TABLE = new PortNumber(TABLE_NUMBER) static
Definition at line 83 of file PortNumber.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/PortNumber.java