onos: org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1 Class Reference
Provides PCEP label object.
Classes
class Builder
Builder class for PCEP label object.
Public Member Functions
PcepLabelObjectVer1 (PcepObjectHeader labelObjHeader, boolean bOFlag, int label, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize parameters for PCEP label object.
LinkedList< PcepValueType > getOptionalTlv ()
Returns list of Optional Tlvs.
void setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets Optional Tlvs in Label Object.
boolean getOFlag ()
Returns O flag in Label Object.
void setOFlag (boolean value)
Sets O flag in Label Object with specified value.
int getLabel ()
Returns Label from Label Object.
void setLabel (int value)
Sets Label field in Label Object with specified value.
int write (ChannelBuffer cb) throws PcepParseException
Writes the Label Object into channel buffer.
String toString ()
Static Public Member Functions
static PcepLabelObject read (ChannelBuffer cb) throws PcepParseException
Reads form channel buffer and returns objects of PcepLabelObject.
Static Public Attributes
static final byte LABEL_OBJ_TYPE = 1
static final byte LABEL_OBJ_CLASS = 35
static final byte LABEL_OBJECT_VERSION = 1
static final byte OBJECT_HEADER_LENGTH = 4
static final boolean DEFAULT_OFLAG = false
static final short LABEL_OBJ_MINIMUM_LENGTH = 12
static final int OFLAG_SET = 1
static final int OFLAG_RESET = 0
static final int MINIMUM_COMMON_HEADER_LENGTH = 4
Protected Member Functions
int packOptionalTlv (ChannelBuffer cb)
Returns the writer index.
Static Protected Member Functions
static LinkedList< PcepValueType > parseOptionalTlv (ChannelBuffer cb) throws PcepParseException
Returns list of optional tlvs.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepLspObjectVer1.class)
Detailed Description
Provides PCEP label object.
Definition at line 38 of file PcepLabelObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.PcepLabelObjectVer1 (PcepObjectHeader labelObjHeader, boolean bOFlag, int label, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize parameters for PCEP label object.
Parameters
labelObjHeader label object header
bOFlag O flag
label label
llOptionalTlv list of optional tlvs
Definition at line 88 of file PcepLabelObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.read().
Member Function Documentation
int org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.getLabel ()
Returns Label from Label Object.
Returns
Label value
Implements org.onosproject.pcepio.protocol.PcepLabelObject.
Definition at line 117 of file PcepLabelObjectVer1.java.
boolean org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.getOFlag ()
Returns O flag in Label Object.
Returns
Boolean value
Implements org.onosproject.pcepio.protocol.PcepLabelObject.
Definition at line 107 of file PcepLabelObjectVer1.java.
LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.getOptionalTlv ()
Returns list of Optional Tlvs.
Returns
list of Optional Tlvs
Implements org.onosproject.pcepio.protocol.PcepLabelObject.
Definition at line 97 of file PcepLabelObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.packOptionalTlv (ChannelBuffer cb) protected
Returns the writer index.
Parameters
cb of channel buffer.
Returns
writer index
Definition at line 246 of file PcepLabelObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.write().
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.parseOptionalTlv (ChannelBuffer cb) throws PcepParseException static protected
Returns list of optional tlvs.
Parameters
cb of type channel buffer
Returns
list of optional tlvs.
Exceptions
PcepParseException when fails to parse list of optional tlvs
Definition at line 192 of file PcepLabelObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.MINIMUM_COMMON_HEADER_LENGTH, and org.onosproject.pcepio.types.NexthopIPv6addressTlv.VALUE_LENGTH.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.read().
static PcepLabelObject org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.read (ChannelBuffer cb) throws PcepParseException static
Reads form channel buffer and returns objects of PcepLabelObject.
Parameters
cb of type channel buffer
Returns
objects of PcepLabelObject
Exceptions
PcepParseException when fails to read from channel buffer
Definition at line 133 of file PcepLabelObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.OBJECT_HEADER_LENGTH, org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.parseOptionalTlv(), and org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.PcepLabelObjectVer1().
void org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.setLabel (int value)
Sets Label field in Label Object with specified value.
Parameters
value Label
Implements org.onosproject.pcepio.protocol.PcepLabelObject.
Definition at line 122 of file PcepLabelObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.setOFlag (boolean value)
Sets O flag in Label Object with specified value.
Parameters
value O flag
Implements org.onosproject.pcepio.protocol.PcepLabelObject.
Definition at line 112 of file PcepLabelObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets Optional Tlvs in Label Object.
Parameters
llOptionalTlv list of Optional Tlvs
Implements org.onosproject.pcepio.protocol.PcepLabelObject.
Definition at line 102 of file PcepLabelObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.toString ()
Definition at line 363 of file PcepLabelObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the Label Object into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException while writing LABEL object into Channel Buffer.
Implements org.onosproject.pcepio.protocol.PcepLabelObject.
Definition at line 157 of file PcepLabelObjectVer1.java.
References find-link-in-cluster.length, org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.OFLAG_RESET, org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.OFLAG_SET, and org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.packOptionalTlv().
Member Data Documentation
final boolean org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.DEFAULT_OFLAG = false static
Definition at line 62 of file PcepLabelObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.LABEL_OBJ_CLASS = 35 static
Definition at line 59 of file PcepLabelObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelUpdateVer1.read().
final short org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.LABEL_OBJ_MINIMUM_LENGTH = 12 static
Definition at line 65 of file PcepLabelObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.LABEL_OBJ_TYPE = 1 static
Definition at line 58 of file PcepLabelObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.LABEL_OBJECT_VERSION = 1 static
Definition at line 60 of file PcepLabelObjectVer1.java.
final Logger org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.log = LoggerFactory.getLogger(PcepLspObjectVer1.class) static protected
Definition at line 56 of file PcepLabelObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.MINIMUM_COMMON_HEADER_LENGTH = 4 static
Definition at line 69 of file PcepLabelObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.parseOptionalTlv().
final byte org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.OBJECT_HEADER_LENGTH = 4 static
Definition at line 61 of file PcepLabelObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.read().
final int org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.OFLAG_RESET = 0 static
Definition at line 68 of file PcepLabelObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.write().
final int org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.OFLAG_SET = 1 static
Definition at line 67 of file PcepLabelObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLabelObjectVer1.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepLabelObjectVer1.java