onos: org.onosproject.net.intent.IntentServiceTest Class Reference
org.onosproject.net.intent.IntentServiceTest Class Reference
Suite of tests for the intent service contract.
Classes
class TestListener
Public Member Functions
void setUp ()
void tearDown ()
void basics ()
void failedCompilation ()
void compilerBasics ()
void implicitRegistration ()
Static Public Attributes
static final int IID = 123
static final int INSTALLABLE_IID = 234
Protected Member Functions
TestableIntentService createIntentService ()
Creates a service instance appropriately instrumented for testing.
void validateEvents (Intent intent, IntentEvent.Type...types)
Validates that the test event listener has received the following events for the specified intent.
Protected Attributes
TestableIntentService service
TestListener listener = new TestListener()
IdGenerator idGenerator = new MockIdGenerator()
Static Protected Attributes
static final int GRACE_MS = 500
Detailed Description
Suite of tests for the intent service contract.
Definition at line 37 of file IntentServiceTest.java.
Member Function Documentation
void org.onosproject.net.intent.IntentServiceTest.basics ()
Definition at line 71 of file IntentServiceTest.java.
References org.onosproject.net.intent.IntentService.getIntentCount(), org.onosproject.net.intent.IntentService.getIntentState(), org.onosproject.net.intent.IntentServiceTest.GRACE_MS, org.onosproject.net.intent.IntentServiceTest.IID, org.onosproject.net.intent.IntentServiceTest.INSTALLABLE_IID, org.onosproject.net.intent.IntentState.INSTALLED, org.onosproject.net.intent.IntentServiceTest.service, org.onosproject.net.intent.IntentServiceTest.validateEvents(), and org.onosproject.net.intent.IntentState.WITHDRAWN.
void org.onosproject.net.intent.IntentServiceTest.compilerBasics ()
Definition at line 155 of file IntentServiceTest.java.
References org.onosproject.net.intent.IntentExtensionService.getCompilers(), and org.onosproject.net.intent.IntentServiceTest.service.
TestableIntentService org.onosproject.net.intent.IntentServiceTest.createIntentService () protected
Creates a service instance appropriately instrumented for testing.
Returns
testable intent service
Definition at line 66 of file IntentServiceTest.java.
Referenced by org.onosproject.net.intent.IntentServiceTest.setUp().
void org.onosproject.net.intent.IntentServiceTest.failedCompilation ()
Definition at line 112 of file IntentServiceTest.java.
References org.onosproject.net.intent.IntentState.FAILED, org.onosproject.net.intent.IntentService.getIntentState(), org.onosproject.net.intent.IntentServiceTest.GRACE_MS, org.onosproject.net.intent.IntentServiceTest.IID, org.onosproject.net.intent.IntentServiceTest.service, and org.onosproject.net.intent.IntentServiceTest.validateEvents().
void org.onosproject.net.intent.IntentServiceTest.implicitRegistration ()
Definition at line 172 of file IntentServiceTest.java.
References org.onosproject.net.intent.IntentExtensionService.getCompilers(), org.onosproject.net.intent.IntentService.getIntentState(), org.onosproject.net.intent.IntentServiceTest.GRACE_MS, org.onosproject.net.intent.IntentServiceTest.IID, org.onosproject.net.intent.IntentServiceTest.INSTALLABLE_IID, org.onosproject.net.intent.IntentState.INSTALLED, and org.onosproject.net.intent.IntentServiceTest.service.
void org.onosproject.net.intent.IntentServiceTest.setUp ()
Definition at line 49 of file IntentServiceTest.java.
References org.onosproject.net.intent.IntentServiceTest.createIntentService(), org.onosproject.net.intent.IntentServiceTest.idGenerator, org.onosproject.net.intent.IntentServiceTest.listener, and org.onosproject.net.intent.IntentServiceTest.service.
void org.onosproject.net.intent.IntentServiceTest.tearDown ()
Definition at line 56 of file IntentServiceTest.java.
References org.onosproject.net.intent.IntentServiceTest.idGenerator, and org.onosproject.net.intent.IntentServiceTest.listener.
void org.onosproject.net.intent.IntentServiceTest.validateEvents (Intent intent, IntentEvent.Type... types) protected
Validates that the test event listener has received the following events for the specified intent.
Events received for other intents will not be considered.
Parameters
intent intent subject
types list of event types for which events are expected
Definition at line 136 of file IntentServiceTest.java.
References org.onosproject.net.intent.Intent.equals().
Referenced by org.onosproject.net.intent.IntentServiceTest.basics(), and org.onosproject.net.intent.IntentServiceTest.failedCompilation().
Member Data Documentation
final int org.onosproject.net.intent.IntentServiceTest.GRACE_MS = 500 static protected
Definition at line 42 of file IntentServiceTest.java.
Referenced by org.onosproject.net.intent.IntentServiceTest.basics(), org.onosproject.net.intent.IntentServiceTest.failedCompilation(), and org.onosproject.net.intent.IntentServiceTest.implicitRegistration().
IdGenerator org.onosproject.net.intent.IntentServiceTest.idGenerator = new MockIdGenerator() protected
Definition at line 46 of file IntentServiceTest.java.
Referenced by org.onosproject.net.intent.IntentServiceTest.setUp(), and org.onosproject.net.intent.IntentServiceTest.tearDown().
final int org.onosproject.net.intent.IntentServiceTest.IID = 123 static
Definition at line 39 of file IntentServiceTest.java.
Referenced by org.onosproject.net.intent.IntentServiceTest.basics(), org.onosproject.net.intent.IntentServiceTest.failedCompilation(), and org.onosproject.net.intent.IntentServiceTest.implicitRegistration().
final int org.onosproject.net.intent.IntentServiceTest.INSTALLABLE_IID = 234 static
Definition at line 40 of file IntentServiceTest.java.
Referenced by org.onosproject.net.intent.IntentServiceTest.basics(), and org.onosproject.net.intent.IntentServiceTest.implicitRegistration().
TestListener org.onosproject.net.intent.IntentServiceTest.listener = new TestListener() protected
Definition at line 45 of file IntentServiceTest.java.
Referenced by org.onosproject.net.intent.IntentServiceTest.setUp(), and org.onosproject.net.intent.IntentServiceTest.tearDown().
TestableIntentService org.onosproject.net.intent.IntentServiceTest.service protected
Definition at line 44 of file IntentServiceTest.java.
Referenced by org.onosproject.net.intent.IntentServiceTest.basics(), org.onosproject.net.intent.IntentServiceTest.compilerBasics(), org.onosproject.net.intent.IntentServiceTest.failedCompilation(), org.onosproject.net.intent.IntentServiceTest.implicitRegistration(), and org.onosproject.net.intent.IntentServiceTest.setUp().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/intent/IntentServiceTest.java