onos: org.onosproject.bgp.controller.impl.VpnAdjRibIn Class Reference
org.onosproject.bgp.controller.impl.VpnAdjRibIn Class Reference
Implementation of Adj-RIB-In with VPN for each peer.
Public Member Functions
Map< BgpNodeLSIdentifier,
PathAttrNlriDetails > nodeTree ()
Returns the adjacency node.
Map< BgpLinkLSIdentifier,
PathAttrNlriDetails > linkTree ()
Returns the adjacency link.
Map< BgpPrefixLSIdentifier,
PathAttrNlriDetails > prefixTree ()
Returns the adjacency prefix.
Map< RouteDistinguisher, Map
< BgpNodeLSIdentifier,
PathAttrNlriDetails > > vpnNodeTree ()
Returns the adjacency vpnNode.
Map< RouteDistinguisher, Map
< BgpLinkLSIdentifier,
PathAttrNlriDetails > > vpnLinkTree ()
Returns the adjacency vpnLink.
Map< RouteDistinguisher, Map
< BgpPrefixLSIdentifier,
PathAttrNlriDetails > > vpnPrefixTree ()
Returns the adjacency vpnPrefix.
void add (BgpLSNlri nlri, PathAttrNlriDetails details)
Update vpn nlri identifier into the tree if nlri identifier exists in tree otherwise add this to the tree.
void addVpn (BgpLSNlri nlri, PathAttrNlriDetails details, RouteDistinguisher routeDistinguisher)
Update nlri identifier mapped with route distinguisher if it exists in tree otherwise add nlri infomation mapped to respective route distinguisher in tree.
void removeVpn (BgpLSNlri nlri, RouteDistinguisher routeDistinguisher)
Removes vpn nlri identifier mapped to route distinguisher if it exists in tree.
String toString ()
Detailed Description
Implementation of Adj-RIB-In with VPN for each peer.
Definition at line 37 of file VpnAdjRibIn.java.
Member Function Documentation
void org.onosproject.bgp.controller.impl.VpnAdjRibIn.add (BgpLSNlri nlri, PathAttrNlriDetails details)
Update vpn nlri identifier into the tree if nlri identifier exists in tree otherwise add this to the tree.
Parameters
nlri NLRI info
details has pathattribute , protocolID and identifier
Definition at line 108 of file VpnAdjRibIn.java.
References org.onosproject.bgp.controller.impl.VpnAdjRibIn.linkTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.nodeTree(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.prefixTree().
Referenced by org.onosproject.bgp.controller.impl.VpnAdjRibIn.addVpn(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.toString().
void org.onosproject.bgp.controller.impl.VpnAdjRibIn.addVpn (BgpLSNlri nlri, PathAttrNlriDetails details, RouteDistinguisher routeDistinguisher)
Update nlri identifier mapped with route distinguisher if it exists in tree otherwise add nlri infomation mapped to respective route distinguisher in tree.
Parameters
nlri NLRI info
details has pathattribute , protocolID and identifier
routeDistinguisher unique for for each vpn
Definition at line 141 of file VpnAdjRibIn.java.
References org.onosproject.bgp.controller.impl.VpnAdjRibIn.add(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.linkTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.nodeTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.prefixTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnLinkTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnNodeTree(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnPrefixTree().
Map<BgpLinkLSIdentifier, PathAttrNlriDetails> org.onosproject.bgp.controller.impl.VpnAdjRibIn.linkTree ()
Returns the adjacency link.
Returns
link adjacency RIB node
Definition at line 62 of file VpnAdjRibIn.java.
Referenced by org.onosproject.bgp.controller.impl.VpnAdjRibIn.add(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.addVpn(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.removeVpn(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.toString().
Map<BgpNodeLSIdentifier, PathAttrNlriDetails> org.onosproject.bgp.controller.impl.VpnAdjRibIn.nodeTree ()
Returns the adjacency node.
Returns
node adjacency RIB node
Definition at line 53 of file VpnAdjRibIn.java.
Referenced by org.onosproject.bgp.controller.impl.VpnAdjRibIn.add(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.addVpn(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.removeVpn(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.toString().
Map<BgpPrefixLSIdentifier, PathAttrNlriDetails> org.onosproject.bgp.controller.impl.VpnAdjRibIn.prefixTree ()
Returns the adjacency prefix.
Returns
prefix adjacency RIB node
Definition at line 71 of file VpnAdjRibIn.java.
Referenced by org.onosproject.bgp.controller.impl.VpnAdjRibIn.add(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.addVpn(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.removeVpn(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.toString().
void org.onosproject.bgp.controller.impl.VpnAdjRibIn.removeVpn (BgpLSNlri nlri, RouteDistinguisher routeDistinguisher)
Removes vpn nlri identifier mapped to route distinguisher if it exists in tree.
Parameters
nlri NLRI Info
routeDistinguisher unique for for each vpn
Definition at line 164 of file VpnAdjRibIn.java.
References org.onosproject.bgp.controller.impl.VpnAdjRibIn.linkTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.nodeTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.prefixTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnLinkTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnNodeTree(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnPrefixTree().
String org.onosproject.bgp.controller.impl.VpnAdjRibIn.toString ()
Definition at line 199 of file VpnAdjRibIn.java.
References org.onosproject.bgp.controller.impl.VpnAdjRibIn.add(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.linkTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.nodeTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.prefixTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnLinkTree(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnNodeTree(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnPrefixTree().
Map<RouteDistinguisher, Map<BgpLinkLSIdentifier, PathAttrNlriDetails> > org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnLinkTree ()
Returns the adjacency vpnLink.
Returns
vpnLink adjacency RIB node
Definition at line 89 of file VpnAdjRibIn.java.
Referenced by org.onosproject.bgp.controller.impl.VpnAdjRibIn.addVpn(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.removeVpn(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.toString().
Map<RouteDistinguisher, Map<BgpNodeLSIdentifier, PathAttrNlriDetails> > org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnNodeTree ()
Returns the adjacency vpnNode.
Returns
vpnNode adjacency RIB node
Definition at line 80 of file VpnAdjRibIn.java.
Referenced by org.onosproject.bgp.controller.impl.VpnAdjRibIn.addVpn(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.removeVpn(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.toString().
Map<RouteDistinguisher, Map<BgpPrefixLSIdentifier, PathAttrNlriDetails> > org.onosproject.bgp.controller.impl.VpnAdjRibIn.vpnPrefixTree ()
Returns the adjacency vpnPrefix.
Returns
vpnPrefix adjacency RIB node
Definition at line 98 of file VpnAdjRibIn.java.
Referenced by org.onosproject.bgp.controller.impl.VpnAdjRibIn.addVpn(), org.onosproject.bgp.controller.impl.VpnAdjRibIn.removeVpn(), and org.onosproject.bgp.controller.impl.VpnAdjRibIn.toString().
The documentation for this class was generated from the following file:
bgp/ctl/src/main/java/org/onosproject/bgp/controller/impl/VpnAdjRibIn.java