onos: org.onosproject.net.newresource.ResourcePath Class Reference
org.onosproject.net.newresource.ResourcePath Class Reference
An object that is used to locate a resource in a network.
Classes
class Continuous
Represents a resource path which specifies a resource which can be measured as continuous value.
class Discrete
Represents a resource path which specifies a resource which can be measured as a discrete unit.
Public Member Functions
List< Object > components ()
Returns the components of this resource path.
Optional< Discrete > parent ()
Returns the parent resource path of this instance.
ResourcePath child (Object child)
Returns a child resource path of this instance with specifying the child object.
ResourcePath child (Object child, double value)
Returns a child resource path of this instance with specifying a child object and value.
Object last ()
Returns the last component of this instance.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static ResourcePath discrete (Object...components)
Creates an resource path which represents a discrete-type resource from the specified components.
static ResourcePath continuous (double value, Object...components)
Creates an resource path which represents a continuous-type resource from the specified components.
Static Public Attributes
static final Discrete ROOT = new Discrete()
Detailed Description
An object that is used to locate a resource in a network.
A ResourcePath represents a path that is hierarchical and composed of a sequence of elementary resources that are not globally identifiable. A ResourcePath can be a globally unique resource identifier.
Two types of resource are considered. One is discrete type and the other is continuous type. Discrete type resource is a resource whose amount is measured as a discrete unit. VLAN ID and MPLS label are examples of discrete type resource. Continuous type resource is a resource whose amount is measured as a continuous value. Bandwidth is an example of continuous type resource. A double value is associated with a continuous type value.
Users of this class must keep the semantics of resources regarding the hierarchical structure. For example, resource path, Link:1/VLAN ID:100, is valid, but resource path, VLAN ID:100/Link:1 is not valid because a link is not a sub-component of a VLAN ID.
Definition at line 48 of file ResourcePath.java.
Member Function Documentation
ResourcePath org.onosproject.net.newresource.ResourcePath.child (Object child)
Returns a child resource path of this instance with specifying the child object.
The child resource path is discrete-type.
Parameters
child child object
Returns
a child resource path
Definition at line 153 of file ResourcePath.java.
ResourcePath org.onosproject.net.newresource.ResourcePath.child (Object child, double value)
Returns a child resource path of this instance with specifying a child object and value.
The child resource path is continuous-type.
Parameters
child child object
value value
Returns
a child resource path
Definition at line 167 of file ResourcePath.java.
List<Object> org.onosproject.net.newresource.ResourcePath.components ()
Returns the components of this resource path.
Returns
the components of this resource path
Definition at line 123 of file ResourcePath.java.
References verify-topo-devices.last.
Referenced by org.onosproject.net.newresource.ResourcePath.continuous(), org.onosproject.net.newresource.ResourcePath.discrete(), and org.onosproject.net.newresource.ResourcePathTest.testComponents().
static ResourcePath org.onosproject.net.newresource.ResourcePath.continuous (double value, Object... components) static
Creates an resource path which represents a continuous-type resource from the specified components.
Parameters
value amount of the resource
components components of the path. The order represents hierarchical structure of the resource.
Returns
resource path instance
Definition at line 76 of file ResourcePath.java.
References org.onosproject.net.newresource.ResourcePath.components().
static ResourcePath org.onosproject.net.newresource.ResourcePath.discrete (Object... components) static
Creates an resource path which represents a discrete-type resource from the specified components.
Parameters
components components of the path. The order represents hierarchical structure of the resource.
Returns
resource path instance
Definition at line 61 of file ResourcePath.java.
References org.onosproject.net.newresource.ResourcePath.components(), and org.onosproject.net.newresource.ResourcePath.ROOT.
Referenced by org.onosproject.net.newresource.ResourceAllocationTest.testEquals(), org.onosproject.store.serializers.KryoSerializerTest.testResourceAllocation(), org.onosproject.net.intent.impl.ObjectiveTrackerTest.testResourceEvent(), and org.onosproject.store.serializers.KryoSerializerTest.testResourcePath().
boolean org.onosproject.net.newresource.ResourcePath.equals (Object obj)
Definition at line 189 of file ResourcePath.java.
int org.onosproject.net.newresource.ResourcePath.hashCode ()
Definition at line 184 of file ResourcePath.java.
References verify-topo-devices.last.
Object org.onosproject.net.newresource.ResourcePath.last ()
Returns the last component of this instance.
Returns
the last component of this instance. The return value is equal to the last object of
components()
.
Definition at line 179 of file ResourcePath.java.
Referenced by org.onosproject.net.newresource.ResourcePath.toString().
Optional<Discrete> org.onosproject.net.newresource.ResourcePath.parent ()
Returns the parent resource path of this instance.
E.g. if this path is Link:1/VLAN ID:100, the return value is the resource path for Link:1.
Returns
the parent resource path of this instance. If there is no parent, empty instance will be returned.
Definition at line 142 of file ResourcePath.java.
Referenced by org.onosproject.net.newresource.ResourcePath.toString().
String org.onosproject.net.newresource.ResourcePath.toString ()
Definition at line 202 of file ResourcePath.java.
References org.onosproject.net.newresource.ResourcePath.last(), and org.onosproject.net.newresource.ResourcePath.parent().
Member Data Documentation
final Discrete org.onosproject.net.newresource.ResourcePath.ROOT = new Discrete() static
Definition at line 53 of file ResourcePath.java.
Referenced by org.onosproject.store.newresource.impl.ConsistentResourceStore.activate(), org.onosproject.net.newresource.ResourcePath.discrete(), org.onosproject.net.newresource.ResourcePathTest.testCreateWithZeroComponent(), and org.onosproject.net.newresource.ResourcePathTest.testNoParent().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/newresource/ResourcePath.java