onos: org.onosproject.net.topology.DefaultTopologyCluster Class Reference
org.onosproject.net.topology.DefaultTopologyCluster Class Reference
Default implementation of a network topology cluster.
Public Member Functions
DefaultTopologyCluster (ClusterId id, int deviceCount, int linkCount, TopologyVertex root)
Creates a new topology cluster descriptor with the specified attributes.
ClusterId id ()
Returns the cluster id.
int deviceCount ()
Returns the number of devices in the cluster.
int linkCount ()
Returns the number of infrastructure links in the cluster.
TopologyVertex root ()
Returns the cluster root vertex.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of a network topology cluster.
Definition at line 25 of file DefaultTopologyCluster.java.
Constructor & Destructor Documentation
org.onosproject.net.topology.DefaultTopologyCluster.DefaultTopologyCluster (ClusterId id, int deviceCount, int linkCount, TopologyVertex root)
Creates a new topology cluster descriptor with the specified attributes.
Parameters
id cluster id
deviceCount number of devices in the cluster
linkCount number of links in the cluster
root cluster root node
Definition at line 40 of file DefaultTopologyCluster.java.
References org.onosproject.net.topology.DefaultTopologyCluster.deviceCount(), org.onosproject.net.topology.DefaultTopologyCluster.id(), org.onosproject.net.topology.DefaultTopologyCluster.linkCount(), and org.onosproject.net.topology.DefaultTopologyCluster.root().
Referenced by org.onosproject.net.topology.DefaultTopologyCluster.equals().
Member Function Documentation
int org.onosproject.net.topology.DefaultTopologyCluster.deviceCount ()
Returns the number of devices in the cluster.
Returns
number of cluster devices
Implements org.onosproject.net.topology.TopologyCluster.
Definition at line 54 of file DefaultTopologyCluster.java.
Referenced by org.onosproject.net.topology.DefaultTopologyCluster.DefaultTopologyCluster(), org.onosproject.net.topology.DefaultTopologyCluster.hashCode(), and org.onosproject.net.topology.DefaultTopologyCluster.toString().
boolean org.onosproject.net.topology.DefaultTopologyCluster.equals (Object obj)
Definition at line 74 of file DefaultTopologyCluster.java.
References org.onosproject.net.topology.DefaultTopologyCluster.DefaultTopologyCluster(), and find-device.id.
int org.onosproject.net.topology.DefaultTopologyCluster.hashCode ()
Definition at line 69 of file DefaultTopologyCluster.java.
References org.onosproject.net.topology.DefaultTopologyCluster.deviceCount(), org.onosproject.net.topology.DefaultTopologyCluster.id(), org.onosproject.net.topology.DefaultTopologyCluster.linkCount(), and org.onosproject.net.topology.DefaultTopologyCluster.root().
ClusterId org.onosproject.net.topology.DefaultTopologyCluster.id ()
Returns the cluster id.
Returns
cluster identifier
Implements org.onosproject.net.topology.TopologyCluster.
Definition at line 49 of file DefaultTopologyCluster.java.
Referenced by org.onosproject.net.topology.DefaultTopologyCluster.DefaultTopologyCluster(), org.onosproject.net.topology.DefaultTopologyCluster.hashCode(), and org.onosproject.net.topology.DefaultTopologyCluster.toString().
int org.onosproject.net.topology.DefaultTopologyCluster.linkCount ()
Returns the number of infrastructure links in the cluster.
Returns
number of cluster links
Implements org.onosproject.net.topology.TopologyCluster.
Definition at line 59 of file DefaultTopologyCluster.java.
Referenced by org.onosproject.net.topology.DefaultTopologyCluster.DefaultTopologyCluster(), org.onosproject.net.topology.DefaultTopologyCluster.hashCode(), and org.onosproject.net.topology.DefaultTopologyCluster.toString().
TopologyVertex org.onosproject.net.topology.DefaultTopologyCluster.root ()
Returns the cluster root vertex.
Returns
cluster root vertex
Implements org.onosproject.net.topology.TopologyCluster.
Definition at line 64 of file DefaultTopologyCluster.java.
Referenced by org.onosproject.net.topology.DefaultTopologyCluster.DefaultTopologyCluster(), org.onosproject.net.topology.DefaultTopologyCluster.hashCode(), and org.onosproject.net.topology.DefaultTopologyCluster.toString().
String org.onosproject.net.topology.DefaultTopologyCluster.toString ()
Definition at line 89 of file DefaultTopologyCluster.java.
References org.onosproject.net.topology.DefaultTopologyCluster.deviceCount(), org.onosproject.net.topology.DefaultTopologyCluster.id(), org.onosproject.net.topology.DefaultTopologyCluster.linkCount(), and org.onosproject.net.topology.DefaultTopologyCluster.root().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/topology/DefaultTopologyCluster.java