onos: org.onlab.junit.ExceptionTest Class Reference
org.onlab.junit.ExceptionTest Class Reference abstract
Base for exception tests.
Public Member Functions
void noMessageNoCause ()
void withMessage ()
void withCause ()
Protected Member Functions
abstract Exception getDefault ()
abstract Exception getWithMessage ()
abstract Exception getWithMessageAndCause ()
Static Protected Attributes
static final Throwable CAUSE = new RuntimeException("boom")
static final String MESSAGE = "Uh oh.... boom"
Detailed Description
Base for exception tests.
Definition at line 26 of file ExceptionTest.java.
Member Function Documentation
abstract Exception org.onlab.junit.ExceptionTest.getDefault () protected pure virtual
Implemented in org.onosproject.app.ApplicationExceptionTest, and org.onosproject.core.UnavailableIdExceptionTest.
Referenced by org.onlab.junit.ExceptionTest.noMessageNoCause().
abstract Exception org.onlab.junit.ExceptionTest.getWithMessage () protected pure virtual
Implemented in org.onosproject.app.ApplicationExceptionTest, and org.onosproject.core.UnavailableIdExceptionTest.
Referenced by org.onlab.junit.ExceptionTest.withMessage().
abstract Exception org.onlab.junit.ExceptionTest.getWithMessageAndCause () protected pure virtual
Implemented in org.onosproject.app.ApplicationExceptionTest, and org.onosproject.core.UnavailableIdExceptionTest.
Referenced by org.onlab.junit.ExceptionTest.withCause().
void org.onlab.junit.ExceptionTest.noMessageNoCause ()
Definition at line 36 of file ExceptionTest.java.
References org.onlab.junit.ExceptionTest.getDefault().
void org.onlab.junit.ExceptionTest.withCause ()
Definition at line 50 of file ExceptionTest.java.
References org.onlab.junit.ExceptionTest.CAUSE, org.onlab.junit.ExceptionTest.getWithMessageAndCause(), and org.onlab.junit.ExceptionTest.MESSAGE.
void org.onlab.junit.ExceptionTest.withMessage ()
Definition at line 43 of file ExceptionTest.java.
References org.onlab.junit.ExceptionTest.getWithMessage(), and org.onlab.junit.ExceptionTest.MESSAGE.
Member Data Documentation
final Throwable org.onlab.junit.ExceptionTest.CAUSE = new RuntimeException("boom") static protected
Definition at line 28 of file ExceptionTest.java.
Referenced by org.onosproject.app.ApplicationExceptionTest.getWithMessageAndCause(), org.onosproject.core.UnavailableIdExceptionTest.getWithMessageAndCause(), and org.onlab.junit.ExceptionTest.withCause().
final String org.onlab.junit.ExceptionTest.MESSAGE = "Uh oh.... boom" static protected
Definition at line 29 of file ExceptionTest.java.
Referenced by org.onosproject.app.ApplicationExceptionTest.getWithMessage(), org.onosproject.core.UnavailableIdExceptionTest.getWithMessage(), org.onosproject.app.ApplicationExceptionTest.getWithMessageAndCause(), org.onosproject.core.UnavailableIdExceptionTest.getWithMessageAndCause(), org.onlab.junit.ExceptionTest.withCause(), and org.onlab.junit.ExceptionTest.withMessage().
The documentation for this class was generated from the following file:
utils/junit/src/main/java/org/onlab/junit/ExceptionTest.java