onos: org.onosproject.net.resource.link.LambdaResourceAllocation Class Reference
org.onosproject.net.resource.link.LambdaResourceAllocation Class Reference
Representation of allocated lambda resource.
Public Member Functions
ResourceType type ()
Returns the resource type.
LambdaResourceAllocation (LambdaResource lambda)
Creates a new LambdaResourceAllocation with LambdaResource object.
LambdaResource lambda ()
Returns the lambda resource.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Representation of allocated lambda resource.
Deprecated:
in Emu Release
Definition at line 30 of file LambdaResourceAllocation.java.
Constructor & Destructor Documentation
org.onosproject.net.resource.link.LambdaResourceAllocation.LambdaResourceAllocation (LambdaResource lambda)
Creates a new LambdaResourceAllocation with LambdaResource object.
Parameters
lambda allocated lambda
Definition at line 44 of file LambdaResourceAllocation.java.
References org.onosproject.net.resource.link.LambdaResourceAllocation.lambda().
Referenced by org.onosproject.net.resource.link.LambdaResourceAllocation.equals().
Member Function Documentation
boolean org.onosproject.net.resource.link.LambdaResourceAllocation.equals (Object obj)
Definition at line 63 of file LambdaResourceAllocation.java.
References org.onosproject.net.resource.link.LambdaResourceAllocation.LambdaResourceAllocation().
int org.onosproject.net.resource.link.LambdaResourceAllocation.hashCode ()
Definition at line 58 of file LambdaResourceAllocation.java.
References org.onosproject.net.resource.link.LambdaResourceAllocation.lambda().
LambdaResource org.onosproject.net.resource.link.LambdaResourceAllocation.lambda ()
Returns the lambda resource.
Returns
the lambda resource
Definition at line 53 of file LambdaResourceAllocation.java.
Referenced by org.onosproject.net.resource.link.LambdaResourceAllocation.hashCode(), org.onosproject.net.resource.link.LambdaResourceAllocation.LambdaResourceAllocation(), and org.onosproject.net.resource.link.LambdaResourceAllocation.toString().
String org.onosproject.net.resource.link.LambdaResourceAllocation.toString ()
Definition at line 75 of file LambdaResourceAllocation.java.
References org.onosproject.net.resource.link.LambdaResourceAllocation.lambda().
ResourceType org.onosproject.net.resource.link.LambdaResourceAllocation.type ()
Returns the resource type.
Returns
the resource type
Implements org.onosproject.net.resource.ResourceAllocation.
Definition at line 34 of file LambdaResourceAllocation.java.
References org.onosproject.net.resource.ResourceType.LAMBDA.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/resource/link/LambdaResourceAllocation.java