onos: org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest Class Reference
org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest Class Reference
Unit tests for the open flow controller implementation test.
Classes
class TestSwitchListener
Test harness for a switch listener.
Public Member Functions
void setUp ()
Sets up switches to use as data, mocks and launches a controller instance.
void tearDown ()
void testAddRemoveConnectedSwitch ()
Tests adding and removing connected switches.
void testMasterSwitch ()
Tests adding master switches.
void testEqualSwitch ()
Tests adding equal switches.
void testRoleSetting ()
Tests changing switch role.
Detailed Description
Unit tests for the open flow controller implementation test.
Definition at line 59 of file OpenFlowControllerImplTest.java.
Member Function Documentation
void org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.setUp ()
Sets up switches to use as data, mocks and launches a controller instance.
Definition at line 111 of file OpenFlowControllerImplTest.java.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.tearDown ()
Definition at line 151 of file OpenFlowControllerImplTest.java.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testAddRemoveConnectedSwitch ()
Tests adding and removing connected switches.
Definition at line 174 of file OpenFlowControllerImplTest.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.connectedSwitches, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getSwitches().
void org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testEqualSwitch ()
Tests adding equal switches.
Definition at line 248 of file OpenFlowControllerImplTest.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getEqualSwitches(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getMasterSwitches().
void org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testMasterSwitch ()
Tests adding master switches.
Definition at line 224 of file OpenFlowControllerImplTest.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getEqualSwitches(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getMasterSwitches().
void org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testRoleSetting ()
Tests changing switch role.
Definition at line 272 of file OpenFlowControllerImplTest.java.
References org.onosproject.openflow.controller.RoleState.EQUAL, org.onosproject.openflow.controller.OpenFlowSwitch.getRole(), org.onosproject.openflow.controller.RoleState.MASTER, and org.onosproject.openflow.controller.RoleState.SLAVE.
The documentation for this class was generated from the following file:
protocols/openflow/ctl/src/test/java/org/onosproject/openflow/controller/impl/OpenFlowControllerImplTest.java