onos: org.onosproject.openstackswitching.OpenstackSubnet Class Reference
org.onosproject.openstackswitching.OpenstackSubnet Class Reference
Represents the subnet information given by Neutron.
Classes
class Builder
OpenstackSubnet Builder class.
Public Member Functions
String name ()
boolean enableHhcp ()
String networkId ()
String tenantId ()
List< Ip4Address > dnsNameservers ()
String gatewayIp ()
String cidr ()
String id ()
Static Public Member Functions
static OpenstackSubnet.Builder builder ()
Returns OpenstackSubnet builder object.
Detailed Description
Represents the subnet information given by Neutron.
Definition at line 28 of file OpenstackSubnet.java.
Member Function Documentation
static OpenstackSubnet.Builder org.onosproject.openstackswitching.OpenstackSubnet.builder () static
Returns OpenstackSubnet builder object.
Returns
OpenstackSubnet builder
Definition at line 56 of file OpenstackSubnet.java.
String org.onosproject.openstackswitching.OpenstackSubnet.cidr ()
Definition at line 84 of file OpenstackSubnet.java.
List<Ip4Address> org.onosproject.openstackswitching.OpenstackSubnet.dnsNameservers ()
Definition at line 76 of file OpenstackSubnet.java.
boolean org.onosproject.openstackswitching.OpenstackSubnet.enableHhcp ()
Definition at line 64 of file OpenstackSubnet.java.
String org.onosproject.openstackswitching.OpenstackSubnet.gatewayIp ()
Definition at line 80 of file OpenstackSubnet.java.
String org.onosproject.openstackswitching.OpenstackSubnet.id ()
Definition at line 88 of file OpenstackSubnet.java.
String org.onosproject.openstackswitching.OpenstackSubnet.name ()
Definition at line 60 of file OpenstackSubnet.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.openstackswitching.OpenstackSubnet.networkId ()
Definition at line 68 of file OpenstackSubnet.java.
String org.onosproject.openstackswitching.OpenstackSubnet.tenantId ()
Definition at line 72 of file OpenstackSubnet.java.
The documentation for this class was generated from the following file:
apps/openstackswitching/api/src/main/java/org/onosproject/openstackswitching/OpenstackSubnet.java