onos: org.onosproject.driver.pipeline.OpenVSwitchPipeline Class Reference
org.onosproject.driver.pipeline.OpenVSwitchPipeline Class Reference
Driver for standard OpenVSwitch.
Public Member Functions
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filteringObjective)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
Public Member Functions inherited from org.onosproject.driver.pipeline.DefaultSingleTablePipeline
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filter)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Protected Attributes
FlowObjectiveStore flowObjectiveStore
DeviceId deviceId
ApplicationId appId
FlowRuleService flowRuleService
DeviceService deviceService
Detailed Description
Driver for standard OpenVSwitch.
Definition at line 52 of file OpenVSwitchPipeline.java.
Member Function Documentation
void org.onosproject.driver.pipeline.OpenVSwitchPipeline.filter (FilteringObjective filterObjective)
Installs the filtering rules onto the device.
Parameters
filterObjective a filtering objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 84 of file OpenVSwitchPipeline.java.
Referenced by org.onosproject.driver.pipeline.OpenVSwitchPipeline.forward().
void org.onosproject.driver.pipeline.OpenVSwitchPipeline.forward (ForwardingObjective forwardObjective)
Installs the forwarding rules onto the device.
Parameters
forwardObjective a forwarding objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 89 of file OpenVSwitchPipeline.java.
References org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.driver.pipeline.OpenVSwitchPipeline.filter(), org.onosproject.net.flowobjective.ObjectiveError.FLOWINSTALLATIONFAILED, org.onosproject.net.flowobjective.Objective.op(), and org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN.
void org.onosproject.driver.pipeline.OpenVSwitchPipeline.init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
Parameters
deviceId the deviceId
context processing context
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 70 of file OpenVSwitchPipeline.java.
References org.onosproject.driver.pipeline.OpenVSwitchPipeline.appId, org.onosproject.driver.pipeline.OpenVSwitchPipeline.deviceId, org.onosproject.driver.pipeline.OpenVSwitchPipeline.flowObjectiveStore, and org.onosproject.driver.pipeline.OpenVSwitchPipeline.flowRuleService.
void org.onosproject.driver.pipeline.OpenVSwitchPipeline.next (NextObjective nextObjective)
Installs the next hop elements into the device.
Parameters
nextObjective a next objectives
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 128 of file OpenVSwitchPipeline.java.
Member Data Documentation
ApplicationId org.onosproject.driver.pipeline.OpenVSwitchPipeline.appId protected
Definition at line 61 of file OpenVSwitchPipeline.java.
Referenced by org.onosproject.driver.pipeline.OpenVSwitchPipeline.init().
DeviceId org.onosproject.driver.pipeline.OpenVSwitchPipeline.deviceId protected
Definition at line 60 of file OpenVSwitchPipeline.java.
Referenced by org.onosproject.driver.pipeline.OpenVSwitchPipeline.init().
DeviceService org.onosproject.driver.pipeline.OpenVSwitchPipeline.deviceService protected
Definition at line 63 of file OpenVSwitchPipeline.java.
FlowObjectiveStore org.onosproject.driver.pipeline.OpenVSwitchPipeline.flowObjectiveStore protected
Definition at line 59 of file OpenVSwitchPipeline.java.
Referenced by org.onosproject.driver.pipeline.OpenVSwitchPipeline.init().
FlowRuleService org.onosproject.driver.pipeline.OpenVSwitchPipeline.flowRuleService protected
Definition at line 62 of file OpenVSwitchPipeline.java.
Referenced by org.onosproject.driver.pipeline.OpenVSwitchPipeline.init().
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/pipeline/OpenVSwitchPipeline.java