onos: org.onosproject.driver.pipeline.OVSCorsaPipeline Class Reference
org.onosproject.driver.pipeline.OVSCorsaPipeline Class Reference
OpenvSwitch emulation of the Corsa pipeline handler.
Public Member Functions
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filteringObjective)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Protected Member Functions
void processVlanMplsTable (boolean install)
Protected Attributes
FlowRuleService flowRuleService
DeviceId deviceId
ApplicationId appId
Static Protected Attributes
static final int MAC_TABLE = 0
static final int VLAN_MPLS_TABLE = 1
static final int VLAN_TABLE = 2
static final int ETHER_TABLE = 4
static final int COS_MAP_TABLE = 5
static final int FIB_TABLE = 6
static final int LOCAL_TABLE = 9
static final int CONTROLLER_PRIORITY = 255
Detailed Description
OpenvSwitch emulation of the Corsa pipeline handler.
Definition at line 86 of file OVSCorsaPipeline.java.
Member Function Documentation
void org.onosproject.driver.pipeline.OVSCorsaPipeline.filter (FilteringObjective filterObjective)
Installs the filtering rules onto the device.
Parameters
filterObjective a filtering objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 154 of file OVSCorsaPipeline.java.
References org.onosproject.net.flowobjective.Objective.op(), org.onosproject.net.flowobjective.FilteringObjective.type(), and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
Referenced by org.onosproject.driver.pipeline.OVSCorsaPipeline.forward().
void org.onosproject.driver.pipeline.OVSCorsaPipeline.forward (ForwardingObjective forwardObjective)
Installs the forwarding rules onto the device.
Parameters
forwardObjective a forwarding objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 165 of file OVSCorsaPipeline.java.
References org.onosproject.driver.pipeline.OVSCorsaPipeline.filter(), org.onosproject.net.flowobjective.ObjectiveError.FLOWINSTALLATIONFAILED, org.onosproject.net.flowobjective.Objective.op(), and org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN.
void org.onosproject.driver.pipeline.OVSCorsaPipeline.init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
Parameters
deviceId the deviceId
context processing context
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 126 of file OVSCorsaPipeline.java.
References org.onosproject.driver.pipeline.OVSCorsaPipeline.appId, org.onosproject.driver.pipeline.OVSCorsaPipeline.deviceId, org.onosproject.driver.pipeline.OVSCorsaPipeline.flowRuleService, and org.onosproject.net.flowobjective.ObjectiveError.GROUPINSTALLATIONFAILED.
void org.onosproject.driver.pipeline.OVSCorsaPipeline.next (NextObjective nextObjective)
Installs the next hop elements into the device.
Parameters
nextObjective a next objectives
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 202 of file OVSCorsaPipeline.java.
References org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.driver.pipeline.OVSCorsaPipeline.deviceId, org.onosproject.net.flowobjective.Objective.id(), org.onlab.util.KryoNamespace.serialize(), org.onosproject.net.flowobjective.NextObjective.type(), org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN, and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
void org.onosproject.driver.pipeline.OVSCorsaPipeline.processVlanMplsTable (boolean install) protected
Definition at line 524 of file OVSCorsaPipeline.java.
References org.onlab.packet.VlanId.ANY, org.onosproject.driver.pipeline.OVSCorsaPipeline.appId, org.onosproject.driver.pipeline.OVSCorsaPipeline.CONTROLLER_PRIORITY, org.onosproject.driver.pipeline.OVSCorsaPipeline.deviceId, org.onosproject.driver.pipeline.OVSCorsaPipeline.VLAN_MPLS_TABLE, and org.onosproject.driver.pipeline.OVSCorsaPipeline.VLAN_TABLE.
Member Data Documentation
ApplicationId org.onosproject.driver.pipeline.OVSCorsaPipeline.appId protected
Definition at line 110 of file OVSCorsaPipeline.java.
Referenced by org.onosproject.driver.pipeline.OVSCorsaPipeline.init(), org.onosproject.driver.pipeline.CorsaPipeline.processVlanMplsTable(), and org.onosproject.driver.pipeline.OVSCorsaPipeline.processVlanMplsTable().
final int org.onosproject.driver.pipeline.OVSCorsaPipeline.CONTROLLER_PRIORITY = 255 static protected
Definition at line 98 of file OVSCorsaPipeline.java.
Referenced by org.onosproject.driver.pipeline.CorsaPipeline.processVlanMplsTable(), and org.onosproject.driver.pipeline.OVSCorsaPipeline.processVlanMplsTable().
final int org.onosproject.driver.pipeline.OVSCorsaPipeline.COS_MAP_TABLE = 5 static protected
Definition at line 93 of file OVSCorsaPipeline.java.
DeviceId org.onosproject.driver.pipeline.OVSCorsaPipeline.deviceId protected
Definition at line 109 of file OVSCorsaPipeline.java.
Referenced by org.onosproject.driver.pipeline.OVSCorsaPipeline.init(), org.onosproject.driver.pipeline.OVSCorsaPipeline.next(), org.onosproject.driver.pipeline.CorsaPipeline.processVlanMplsTable(), and org.onosproject.driver.pipeline.OVSCorsaPipeline.processVlanMplsTable().
final int org.onosproject.driver.pipeline.OVSCorsaPipeline.ETHER_TABLE = 4 static protected
Definition at line 92 of file OVSCorsaPipeline.java.
final int org.onosproject.driver.pipeline.OVSCorsaPipeline.FIB_TABLE = 6 static protected
Definition at line 94 of file OVSCorsaPipeline.java.
FlowRuleService org.onosproject.driver.pipeline.OVSCorsaPipeline.flowRuleService protected
Definition at line 105 of file OVSCorsaPipeline.java.
Referenced by org.onosproject.driver.pipeline.OVSCorsaPipeline.init().
final int org.onosproject.driver.pipeline.OVSCorsaPipeline.LOCAL_TABLE = 9 static protected
Definition at line 95 of file OVSCorsaPipeline.java.
final int org.onosproject.driver.pipeline.OVSCorsaPipeline.MAC_TABLE = 0 static protected
Definition at line 88 of file OVSCorsaPipeline.java.
final int org.onosproject.driver.pipeline.OVSCorsaPipeline.VLAN_MPLS_TABLE = 1 static protected
Definition at line 89 of file OVSCorsaPipeline.java.
Referenced by org.onosproject.driver.pipeline.CorsaPipeline.processVlanMplsTable(), and org.onosproject.driver.pipeline.OVSCorsaPipeline.processVlanMplsTable().
final int org.onosproject.driver.pipeline.OVSCorsaPipeline.VLAN_TABLE = 2 static protected
Definition at line 90 of file OVSCorsaPipeline.java.
Referenced by org.onosproject.driver.pipeline.CorsaPipeline.processVlanMplsTable(), and org.onosproject.driver.pipeline.OVSCorsaPipeline.processVlanMplsTable().
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/pipeline/OVSCorsaPipeline.java