onos: org.onlab.packet.LLDPTLV Class Reference
org.onlab.packet.LLDPTLV Class Reference
Public Member Functions
byte getType ()
LLDPTLV setType (final byte type)
short getLength ()
LLDPTLV setLength (final short length)
byte[] getValue ()
LLDPTLV setValue (final byte[] value)
byte[] serialize ()
LLDPTLV deserialize (final ByteBuffer bb) throws DeserializationException
int hashCode ()
boolean equals (final Object obj)
Protected Attributes
byte type
short length
byte[] value
Detailed Description
Definition at line 28 of file LLDPTLV.java.
Member Function Documentation
LLDPTLV org.onlab.packet.LLDPTLV.deserialize (final ByteBuffer bb) throws DeserializationException
Definition at line 98 of file LLDPTLV.java.
References find-link-in-cluster.length, and org.onlab.packet.LLDPTLV.length.
boolean org.onlab.packet.LLDPTLV.equals (final Object obj)
Definition at line 143 of file LLDPTLV.java.
References org.onlab.packet.LLDPTLV.length, org.onlab.packet.LLDPTLV.type, and org.onlab.packet.LLDPTLV.value.
Referenced by org.onlab.packet.LLDP.equals().
short org.onlab.packet.LLDPTLV.getLength ()
Returns
the length
Definition at line 53 of file LLDPTLV.java.
References find-link-in-cluster.length.
Referenced by org.onlab.packet.LLDPOrganizationalTLV.deserialize(), org.onlab.packet.LLDP.serialize(), and org.onlab.packet.LLDPTest.testDeserialize().
byte org.onlab.packet.LLDPTLV.getType ()
Returns
the type
Definition at line 36 of file LLDPTLV.java.
Referenced by org.onlab.packet.LLDPOrganizationalTLV.deserialize(), and org.onlab.packet.LLDPTest.testDeserialize().
byte [] org.onlab.packet.LLDPTLV.getValue ()
Returns
the value
Definition at line 70 of file LLDPTLV.java.
Referenced by org.onlab.packet.LLDPTest.testDeserialize().
int org.onlab.packet.LLDPTLV.hashCode ()
Definition at line 128 of file LLDPTLV.java.
References find-link-in-cluster.length.
byte [] org.onlab.packet.LLDPTLV.serialize ()
Definition at line 84 of file LLDPTLV.java.
References find-link-in-cluster.length, org.onlab.packet.LLDPTLV.type, and org.onlab.packet.LLDPTLV.value.
LLDPTLV org.onlab.packet.LLDPTLV.setLength (final short length)
Parameters
length the length to set
Returns
this
Definition at line 62 of file LLDPTLV.java.
References org.onlab.packet.LLDPTLV.length.
LLDPTLV org.onlab.packet.LLDPTLV.setType (final byte type)
Parameters
type the type to set
Returns
this
Definition at line 45 of file LLDPTLV.java.
References org.onlab.packet.LLDPTLV.type.
LLDPTLV org.onlab.packet.LLDPTLV.setValue (final byte[] value)
Parameters
value the value to set
Returns
this
Definition at line 79 of file LLDPTLV.java.
References org.onlab.packet.LLDPTLV.value.
Referenced by org.onlab.packet.ONOSLLDP.ONOSLLDP().
Member Data Documentation
short org.onlab.packet.LLDPTLV.length protected
Definition at line 30 of file LLDPTLV.java.
Referenced by org.onlab.packet.LLDPTLV.deserialize(), org.onlab.packet.LLDPTLV.equals(), org.onlab.packet.LLDPOrganizationalTLV.equals(), and org.onlab.packet.LLDPTLV.setLength().
byte org.onlab.packet.LLDPTLV.type protected
Definition at line 29 of file LLDPTLV.java.
Referenced by org.onlab.packet.LLDPTLV.equals(), org.onlab.packet.LLDPOrganizationalTLV.equals(), org.onlab.packet.LLDPTLV.serialize(), org.onlab.packet.LLDPOrganizationalTLV.serialize(), and org.onlab.packet.LLDPTLV.setType().
byte [] org.onlab.packet.LLDPTLV.value protected
Definition at line 31 of file LLDPTLV.java.
Referenced by org.onlab.packet.LLDPTLV.equals(), org.onlab.packet.LLDPTLV.serialize(), and org.onlab.packet.LLDPTLV.setValue().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/LLDPTLV.java