onos: org.onlab.packet.ndp.NeighborAdvertisement Class Reference
org.onlab.packet.ndp.NeighborAdvertisement Class Reference
Implements ICMPv6 Neighbor Advertisement packet format (RFC 4861).
Public Member Functions
byte getRouterFlag ()
Gets router flag.
NeighborAdvertisement setRouterFlag (final byte routerFlag)
Sets router flag.
byte getSolicitedFlag ()
Gets solicited flag.
NeighborAdvertisement setSolicitedFlag (final byte solicitedFlag)
Sets solicited flag.
byte getOverrideFlag ()
Gets override flag.
NeighborAdvertisement setOverrideFlag (final byte overrideFlag)
Sets override flag.
byte[] getTargetAddress ()
Gets target address.
NeighborAdvertisement setTargetAddress (final byte[] targetAddress)
Sets target address.
List
< NeighborDiscoveryOptions.Option > getOptions ()
Gets the Neighbor Discovery Protocol packet options.
NeighborAdvertisement addOption (final byte type, final byte[] data)
Adds a Neighbor Discovery Protocol packet option.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer
< NeighborAdvertisement > deserializer ()
Deserializer function for neighbor advertisement packets.
Static Public Attributes
static final byte HEADER_LENGTH = 20
Protected Attributes
byte routerFlag
byte solicitedFlag
byte overrideFlag
byte[] targetAddress = new byte[Ip6Address.BYTE_LENGTH]
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements ICMPv6 Neighbor Advertisement packet format (RFC 4861).
Definition at line 32 of file NeighborAdvertisement.java.
Member Function Documentation
NeighborAdvertisement org.onlab.packet.ndp.NeighborAdvertisement.addOption (final byte type, final byte[] data)
Adds a Neighbor Discovery Protocol packet option.
Parameters
type the option type
data the option data
Returns
this
Definition at line 140 of file NeighborAdvertisement.java.
IPacket org.onlab.packet.ndp.NeighborAdvertisement.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 173 of file NeighborAdvertisement.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, and find-link-in-cluster.length.
Referenced by org.onlab.packet.ndp.NeighborAdvertisement.deserializer().
static Deserializer<NeighborAdvertisement> org.onlab.packet.ndp.NeighborAdvertisement.deserializer () static
Deserializer function for neighbor advertisement packets.
Returns
deserializer function
Definition at line 250 of file NeighborAdvertisement.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, org.onlab.packet.ndp.NeighborAdvertisement.deserialize(), org.onlab.packet.ndp.NeighborAdvertisement.HEADER_LENGTH, and find-link-in-cluster.length.
boolean org.onlab.packet.ndp.NeighborAdvertisement.equals (final Object obj)
Definition at line 216 of file NeighborAdvertisement.java.
References org.onlab.packet.ndp.NeighborDiscoveryOptions.equals(), org.onlab.packet.ndp.NeighborAdvertisement.overrideFlag, org.onlab.packet.ndp.NeighborAdvertisement.routerFlag, org.onlab.packet.ndp.NeighborAdvertisement.solicitedFlag, and org.onlab.packet.ndp.NeighborAdvertisement.targetAddress.
Referenced by org.onlab.packet.ndp.NeighborAdvertisementTest.testEqual().
List<NeighborDiscoveryOptions.Option> org.onlab.packet.ndp.NeighborAdvertisement.getOptions ()
Gets the Neighbor Discovery Protocol packet options.
Returns
the Neighbor Discovery Protocol packet options
Definition at line 129 of file NeighborAdvertisement.java.
Referenced by org.onlab.packet.ndp.NeighborAdvertisementTest.testDeserialize().
byte org.onlab.packet.ndp.NeighborAdvertisement.getOverrideFlag ()
Gets override flag.
Returns
the override flag
Definition at line 88 of file NeighborAdvertisement.java.
Referenced by org.onlab.packet.ndp.NeighborAdvertisementTest.testDeserialize().
byte org.onlab.packet.ndp.NeighborAdvertisement.getRouterFlag ()
Gets router flag.
Returns
the router flag
Definition at line 48 of file NeighborAdvertisement.java.
Referenced by org.onlab.packet.ndp.NeighborAdvertisementTest.testDeserialize().
byte org.onlab.packet.ndp.NeighborAdvertisement.getSolicitedFlag ()
Gets solicited flag.
Returns
the solicited flag
Definition at line 68 of file NeighborAdvertisement.java.
Referenced by org.onlab.packet.ndp.NeighborAdvertisementTest.testDeserialize().
byte [] org.onlab.packet.ndp.NeighborAdvertisement.getTargetAddress ()
Gets target address.
Returns
the target IPv6 address
Definition at line 108 of file NeighborAdvertisement.java.
Referenced by org.onlab.packet.ndp.NeighborAdvertisementTest.testDeserialize().
int org.onlab.packet.ndp.NeighborAdvertisement.hashCode ()
Definition at line 195 of file NeighborAdvertisement.java.
byte [] org.onlab.packet.ndp.NeighborAdvertisement.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 147 of file NeighborAdvertisement.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, org.onlab.packet.ndp.NeighborDiscoveryOptions.hasOptions(), org.onlab.packet.ndp.NeighborAdvertisement.HEADER_LENGTH, find-link-in-cluster.length, and org.onlab.packet.ndp.NeighborAdvertisement.solicitedFlag.
Referenced by org.onlab.packet.ndp.NeighborAdvertisementTest.testSerialize().
NeighborAdvertisement org.onlab.packet.ndp.NeighborAdvertisement.setOverrideFlag (final byte overrideFlag)
Sets override flag.
Parameters
overrideFlag the override flag to set
Returns
this
Definition at line 98 of file NeighborAdvertisement.java.
References org.onlab.packet.ndp.NeighborAdvertisement.overrideFlag.
NeighborAdvertisement org.onlab.packet.ndp.NeighborAdvertisement.setRouterFlag (final byte routerFlag)
Sets router flag.
Parameters
routerFlag the router flag to set
Returns
this
Definition at line 58 of file NeighborAdvertisement.java.
References org.onlab.packet.ndp.NeighborAdvertisement.routerFlag.
NeighborAdvertisement org.onlab.packet.ndp.NeighborAdvertisement.setSolicitedFlag (final byte solicitedFlag)
Sets solicited flag.
Parameters
solicitedFlag the solicited flag to set
Returns
this
Definition at line 78 of file NeighborAdvertisement.java.
References org.onlab.packet.ndp.NeighborAdvertisement.solicitedFlag.
NeighborAdvertisement org.onlab.packet.ndp.NeighborAdvertisement.setTargetAddress (final byte[] targetAddress)
Sets target address.
Parameters
targetAddress the target IPv6 address to set
Returns
this
Definition at line 118 of file NeighborAdvertisement.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, and org.onlab.packet.ndp.NeighborAdvertisement.targetAddress.
Member Data Documentation
final byte org.onlab.packet.ndp.NeighborAdvertisement.HEADER_LENGTH = 20 static
Definition at line 33 of file NeighborAdvertisement.java.
Referenced by org.onlab.packet.ndp.NeighborAdvertisement.deserializer(), org.onlab.packet.ndp.NeighborAdvertisement.serialize(), and org.onlab.packet.ndp.NeighborAdvertisementTest.testDeserializeTruncated().
byte org.onlab.packet.ndp.NeighborAdvertisement.overrideFlag protected
Definition at line 37 of file NeighborAdvertisement.java.
Referenced by org.onlab.packet.ndp.NeighborAdvertisement.equals(), and org.onlab.packet.ndp.NeighborAdvertisement.setOverrideFlag().
byte org.onlab.packet.ndp.NeighborAdvertisement.routerFlag protected
Definition at line 35 of file NeighborAdvertisement.java.
Referenced by org.onlab.packet.ndp.NeighborAdvertisement.equals(), and org.onlab.packet.ndp.NeighborAdvertisement.setRouterFlag().
byte org.onlab.packet.ndp.NeighborAdvertisement.solicitedFlag protected
Definition at line 36 of file NeighborAdvertisement.java.
Referenced by org.onlab.packet.ndp.NeighborAdvertisement.equals(), org.onlab.packet.ndp.NeighborAdvertisement.serialize(), and org.onlab.packet.ndp.NeighborAdvertisement.setSolicitedFlag().
byte [] org.onlab.packet.ndp.NeighborAdvertisement.targetAddress = new byte[Ip6Address.BYTE_LENGTH] protected
Definition at line 38 of file NeighborAdvertisement.java.
Referenced by org.onlab.packet.ndp.NeighborAdvertisement.equals(), and org.onlab.packet.ndp.NeighborAdvertisement.setTargetAddress().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ndp/NeighborAdvertisement.java