onos: org.onosproject.net.intent.impl.compiler.PathIntentCompiler Class Reference
org.onosproject.net.intent.impl.compiler.PathIntentCompiler Class Reference
Public Member Functions
void activate ()
void deactivate ()
List< Intent > compile (PathIntent intent, List< Intent > installable, Set< LinkResourceAllocations > resources)
Protected Attributes
CoreService coreService
IntentExtensionService intentManager
Detailed Description
Definition at line 46 of file PathIntentCompiler.java.
Member Function Documentation
void org.onosproject.net.intent.impl.compiler.PathIntentCompiler.activate ()
Definition at line 57 of file PathIntentCompiler.java.
List<Intent> org.onosproject.net.intent.impl.compiler.PathIntentCompiler.compile (PathIntent intent, List< Intent > installable, Set< LinkResourceAllocations > resources)
Definition at line 68 of file PathIntentCompiler.java.
References create-intent.egress, create-intent.ingress, org.onosproject.net.intent.Intent.priority(), org.onosproject.net.intent.ConnectivityIntent.resources(), and org.onosproject.net.intent.ConnectivityIntent.selector().
void org.onosproject.net.intent.impl.compiler.PathIntentCompiler.deactivate ()
Definition at line 63 of file PathIntentCompiler.java.
Member Data Documentation
CoreService org.onosproject.net.intent.impl.compiler.PathIntentCompiler.coreService protected
Definition at line 49 of file PathIntentCompiler.java.
IntentExtensionService org.onosproject.net.intent.impl.compiler.PathIntentCompiler.intentManager protected
Definition at line 52 of file PathIntentCompiler.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/intent/impl/compiler/PathIntentCompiler.java