onos: org.onosproject.net.intent.constraint.LinkTypeConstraint Class Reference
org.onosproject.net.intent.constraint.LinkTypeConstraint Class Reference
Constraint that evaluates links based on their type.
Public Member Functions
LinkTypeConstraint (boolean inclusive, Link.Type...types)
Creates a new constraint for requesting connectivity using or avoiding the specified link types.
boolean isValid (Link link, LinkResourceService resourceService)
Returns true if the specified link satisfies the constraint.
Set< Link.Type > types ()
Returns the set of link types.
boolean isInclusive ()
Indicates if the constraint is inclusive or exclusive.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.constraint.BooleanConstraint
double cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
boolean validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
Detailed Description
Constraint that evaluates links based on their type.
Definition at line 34 of file LinkTypeConstraint.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.constraint.LinkTypeConstraint.LinkTypeConstraint (boolean inclusive, Link.Type... types)
Creates a new constraint for requesting connectivity using or avoiding the specified link types.
Parameters
inclusive indicates whether the given link types are to be permitted or avoided
types link types
Definition at line 47 of file LinkTypeConstraint.java.
References org.onosproject.net.intent.constraint.LinkTypeConstraint.types().
Member Function Documentation
boolean org.onosproject.net.intent.constraint.LinkTypeConstraint.equals (Object obj)
Definition at line 90 of file LinkTypeConstraint.java.
References org.onosproject.net.intent.constraint.LinkTypeConstraint.equals().
Referenced by org.onosproject.net.intent.constraint.LinkTypeConstraint.equals().
int org.onosproject.net.intent.constraint.LinkTypeConstraint.hashCode ()
Definition at line 85 of file LinkTypeConstraint.java.
References org.onosproject.net.intent.constraint.LinkTypeConstraint.isInclusive(), and org.onosproject.net.intent.constraint.LinkTypeConstraint.types().
boolean org.onosproject.net.intent.constraint.LinkTypeConstraint.isInclusive ()
Indicates if the constraint is inclusive or exclusive.
Returns
true if inclusive
Definition at line 80 of file LinkTypeConstraint.java.
Referenced by org.onosproject.net.intent.constraint.LinkTypeConstraint.hashCode(), org.onosproject.net.intent.constraint.LinkTypeConstraint.isValid(), and org.onosproject.net.intent.constraint.LinkTypeConstraint.toString().
boolean org.onosproject.net.intent.constraint.LinkTypeConstraint.isValid (Link link, LinkResourceService resourceService) virtual
Returns true if the specified link satisfies the constraint.
Parameters
link link to be validated
resourceService resource service for checking available link resources
Returns
true if link is viable
Implements org.onosproject.net.intent.constraint.BooleanConstraint.
Definition at line 61 of file LinkTypeConstraint.java.
References org.onosproject.net.intent.constraint.LinkTypeConstraint.isInclusive().
String org.onosproject.net.intent.constraint.LinkTypeConstraint.toString ()
Definition at line 102 of file LinkTypeConstraint.java.
References org.onosproject.net.intent.constraint.LinkTypeConstraint.isInclusive(), and org.onosproject.net.intent.constraint.LinkTypeConstraint.types().
Set<Link.Type> org.onosproject.net.intent.constraint.LinkTypeConstraint.types ()
Returns the set of link types.
Returns
set of link types
Definition at line 71 of file LinkTypeConstraint.java.
Referenced by org.onosproject.net.intent.constraint.LinkTypeConstraint.hashCode(), org.onosproject.net.intent.constraint.LinkTypeConstraint.LinkTypeConstraint(), and org.onosproject.net.intent.constraint.LinkTypeConstraint.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/constraint/LinkTypeConstraint.java