onos: org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects Class Reference
org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects Class Reference
Static Public Attributes
static final MessageSubject LABEL_POOL_CREATED = new MessageSubject("label-resource-pool-created")
static final MessageSubject LABEL_POOL_DESTROYED = new MessageSubject("label-resource-pool-destroyed")
static final MessageSubject LABEL_POOL_APPLY = new MessageSubject("label-resource-pool-apply")
static final MessageSubject LABEL_POOL_RELEASE = new MessageSubject("label-resource-pool-release")
Detailed Description
Definition at line 20 of file LabelResourceMessageSubjects.java.
Member Data Documentation
final MessageSubject org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_APPLY = new MessageSubject("label-resource-pool-apply") static
Definition at line 29 of file LabelResourceMessageSubjects.java.
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.activate(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.applyFromDevicePool(), and org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.deactivate().
final MessageSubject org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_CREATED = new MessageSubject("label-resource-pool-created") static
Definition at line 25 of file LabelResourceMessageSubjects.java.
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.activate(), and org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.deactivate().
final MessageSubject org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_DESTROYED = new MessageSubject("label-resource-pool-destroyed") static
Definition at line 27 of file LabelResourceMessageSubjects.java.
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.activate(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.deactivate(), and org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.destroyDevicePool().
final MessageSubject org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_RELEASE = new MessageSubject("label-resource-pool-release") static
Definition at line 31 of file LabelResourceMessageSubjects.java.
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.activate(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.deactivate(), and org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.releaseToDevicePool().
The documentation for this class was generated from the following file:
incubator/store/src/main/java/org/onosproject/incubator/store/resource/impl/LabelResourceMessageSubjects.java