onos: org.onlab.packet.ndp.RouterSolicitation Class Reference
org.onlab.packet.ndp.RouterSolicitation Class Reference
Implements ICMPv6 Router Solicitation packet format.
Public Member Functions
List
< NeighborDiscoveryOptions.Option > getOptions ()
Gets the Neighbor Discovery Protocol packet options.
RouterSolicitation addOption (final byte type, final byte[] data)
Adds a Neighbor Discovery Protocol packet option.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer
< RouterSolicitation > deserializer ()
Deserializer function for router solicitation packets.
Static Public Attributes
static final byte HEADER_LENGTH = 4
Additional Inherited Members
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements ICMPv6 Router Solicitation packet format.
(RFC 4861)
Definition at line 30 of file RouterSolicitation.java.
Member Function Documentation
RouterSolicitation org.onlab.packet.ndp.RouterSolicitation.addOption (final byte type, final byte[] data)
Adds a Neighbor Discovery Protocol packet option.
Parameters
type the option type
data the option data
Returns
this
Definition at line 51 of file RouterSolicitation.java.
IPacket org.onlab.packet.ndp.RouterSolicitation.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 81 of file RouterSolicitation.java.
References find-link-in-cluster.length.
Referenced by org.onlab.packet.ndp.RouterSolicitation.deserializer().
static Deserializer<RouterSolicitation> org.onlab.packet.ndp.RouterSolicitation.deserializer () static
Deserializer function for router solicitation packets.
Returns
deserializer function
Definition at line 133 of file RouterSolicitation.java.
References org.onlab.packet.ndp.RouterSolicitation.deserialize(), org.onlab.packet.ndp.RouterSolicitation.HEADER_LENGTH, and find-link-in-cluster.length.
boolean org.onlab.packet.ndp.RouterSolicitation.equals (final Object obj)
Definition at line 111 of file RouterSolicitation.java.
References org.onlab.packet.ndp.NeighborDiscoveryOptions.equals().
Referenced by org.onlab.packet.ndp.RouterSolicitationTest.testEqual().
List<NeighborDiscoveryOptions.Option> org.onlab.packet.ndp.RouterSolicitation.getOptions ()
Gets the Neighbor Discovery Protocol packet options.
Returns
the Neighbor Discovery Protocol packet options
Definition at line 40 of file RouterSolicitation.java.
Referenced by org.onlab.packet.ndp.RouterSolicitationTest.testDeserialize().
int org.onlab.packet.ndp.RouterSolicitation.hashCode ()
Definition at line 98 of file RouterSolicitation.java.
byte [] org.onlab.packet.ndp.RouterSolicitation.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 57 of file RouterSolicitation.java.
References org.onlab.packet.ndp.NeighborDiscoveryOptions.hasOptions(), org.onlab.packet.ndp.RouterSolicitation.HEADER_LENGTH, and find-link-in-cluster.length.
Referenced by org.onlab.packet.ndp.RouterSolicitationTest.testSerialize().
Member Data Documentation
final byte org.onlab.packet.ndp.RouterSolicitation.HEADER_LENGTH = 4 static
Definition at line 31 of file RouterSolicitation.java.
Referenced by org.onlab.packet.ndp.RouterSolicitation.deserializer(), org.onlab.packet.ndp.RouterSolicitation.serialize(), and org.onlab.packet.ndp.RouterSolicitationTest.testDeserializeTruncated().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ndp/RouterSolicitation.java