onos: org.onosproject.pcepio.types.TENodeAttributesTlv Class Reference
org.onosproject.pcepio.types.TENodeAttributesTlv Class Reference
Provides TE Node Attributes Tlv.
Public Member Functions
TENodeAttributesTlv (LinkedList< PcepValueType > llNodeAttributesSubTLVs)
Constructor to initialize llNodeAttributesSubTLVs.
LinkedList< PcepValueType > getllNodeAttributesSubTLVs ()
Returns Node Attributes Sub-TLVs.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static TENodeAttributesTlv of (LinkedList< PcepValueType > llNodeAttributesSubTLVs)
Returns object of TENodeAttributesTlv.
static PcepValueType read (ChannelBuffer c, short hLength) throws PcepParseException
Reads the channel buffer and returns object of TENodeAttributesTlv.
Public Attributes
short hLength
Static Public Attributes
static final short TYPE = 1267
static final int TLV_HEADER_LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(TENodeAttributesTlv.class)
Detailed Description
Provides TE Node Attributes Tlv.
Definition at line 34 of file TENodeAttributesTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.TENodeAttributesTlv.TENodeAttributesTlv (LinkedList< PcepValueType > llNodeAttributesSubTLVs)
Constructor to initialize llNodeAttributesSubTLVs.
Parameters
llNodeAttributesSubTLVs linked list of Node Attributes Sub-TLVs
Definition at line 65 of file TENodeAttributesTlv.java.
Referenced by org.onosproject.pcepio.types.TENodeAttributesTlv.equals(), org.onosproject.pcepio.types.TENodeAttributesTlv.of(), and org.onosproject.pcepio.types.TENodeAttributesTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.TENodeAttributesTlv.equals (Object obj)
Definition at line 109 of file TENodeAttributesTlv.java.
References org.onosproject.pcepio.types.TENodeAttributesTlv.TENodeAttributesTlv().
short org.onosproject.pcepio.types.TENodeAttributesTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 99 of file TENodeAttributesTlv.java.
References org.onosproject.pcepio.types.TENodeAttributesTlv.hLength.
LinkedList<PcepValueType> org.onosproject.pcepio.types.TENodeAttributesTlv.getllNodeAttributesSubTLVs ()
Returns Node Attributes Sub-TLVs.
Returns
llNodeAttributesSubTLVs linked list of Node Attributes Sub-TLVs
Definition at line 84 of file TENodeAttributesTlv.java.
short org.onosproject.pcepio.types.TENodeAttributesTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 94 of file TENodeAttributesTlv.java.
References org.onosproject.pcepio.types.TENodeAttributesTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.TENodeAttributesTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 89 of file TENodeAttributesTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.TENodeAttributesTlv.hashCode ()
Definition at line 104 of file TENodeAttributesTlv.java.
static TENodeAttributesTlv org.onosproject.pcepio.types.TENodeAttributesTlv.of (LinkedList< PcepValueType > llNodeAttributesSubTLVs) static
Returns object of TENodeAttributesTlv.
Parameters
llNodeAttributesSubTLVs LinkedList of PcepValueType
Returns
object of TENodeAttributesTlv
Definition at line 75 of file TENodeAttributesTlv.java.
References org.onosproject.pcepio.types.TENodeAttributesTlv.TENodeAttributesTlv().
static PcepValueType org.onosproject.pcepio.types.TENodeAttributesTlv.read (ChannelBuffer c, short hLength) throws PcepParseException static
Reads the channel buffer and returns object of TENodeAttributesTlv.
Parameters
c input channel buffer
hLength length
Returns
object of TENodeAttributesTlv
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 183 of file TENodeAttributesTlv.java.
References org.onosproject.pcepio.types.TENodeAttributesTlv.hLength, find-link-in-cluster.length, org.onosproject.pcepio.types.TENodeAttributesTlv.TENodeAttributesTlv(), org.onosproject.pcepio.types.TENodeAttributesTlv.TLV_HEADER_LENGTH, and org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.VALUE_LENGTH.
String org.onosproject.pcepio.types.TENodeAttributesTlv.toString ()
Definition at line 243 of file TENodeAttributesTlv.java.
References org.onosproject.pcepio.types.TENodeAttributesTlv.hLength, and org.onosproject.pcepio.types.TENodeAttributesTlv.TYPE.
int org.onosproject.pcepio.types.TENodeAttributesTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 144 of file TENodeAttributesTlv.java.
References org.onosproject.pcepio.types.TENodeAttributesTlv.hLength, org.onosproject.pcepio.types.TENodeAttributesTlv.TLV_HEADER_LENGTH, and org.onosproject.pcepio.types.TENodeAttributesTlv.TYPE.
Member Data Documentation
short org.onosproject.pcepio.types.TENodeAttributesTlv.hLength
Definition at line 54 of file TENodeAttributesTlv.java.
Referenced by org.onosproject.pcepio.types.TENodeAttributesTlv.getLength(), org.onosproject.pcepio.types.TENodeAttributesTlv.read(), org.onosproject.pcepio.types.TENodeAttributesTlv.toString(), and org.onosproject.pcepio.types.TENodeAttributesTlv.write().
final Logger org.onosproject.pcepio.types.TENodeAttributesTlv.log = LoggerFactory.getLogger(TENodeAttributesTlv.class) static protected
Definition at line 51 of file TENodeAttributesTlv.java.
final int org.onosproject.pcepio.types.TENodeAttributesTlv.TLV_HEADER_LENGTH = 4 static
Definition at line 56 of file TENodeAttributesTlv.java.
Referenced by org.onosproject.pcepio.types.TENodeAttributesTlv.read(), and org.onosproject.pcepio.types.TENodeAttributesTlv.write().
final short org.onosproject.pcepio.types.TENodeAttributesTlv.TYPE = 1267 static
Definition at line 53 of file TENodeAttributesTlv.java.
Referenced by org.onosproject.pcepio.types.TENodeAttributesTlv.getType(), org.onosproject.pcepio.types.TENodeAttributesTlv.toString(), and org.onosproject.pcepio.types.TENodeAttributesTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/TENodeAttributesTlv.java