onos: org.onosproject.net.flow.criteria.OduSignalTypeCriterion Class Reference
org.onosproject.net.flow.criteria.OduSignalTypeCriterion Class Reference
Implementation of ODU (Optical channel Data Unit) signal Type criterion.
Public Member Functions
Type type ()
Returns the type of criterion.
OduSignalType signalType ()
Returns the ODU Signal Type to match.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Implementation of ODU (Optical channel Data Unit) signal Type criterion.
This criterion is based on the specification of "OFPXMT_EXP_ODU_SIGTYPE" in Open Networking Foundation "Optical Transport Protocol Extension Version 1.0", but defined in protocol agnostic way.
Definition at line 31 of file OduSignalTypeCriterion.java.
Member Function Documentation
boolean org.onosproject.net.flow.criteria.OduSignalTypeCriterion.equals (Object obj)
Definition at line 64 of file OduSignalTypeCriterion.java.
int org.onosproject.net.flow.criteria.OduSignalTypeCriterion.hashCode ()
Definition at line 59 of file OduSignalTypeCriterion.java.
References org.onosproject.net.flow.criteria.OduSignalTypeCriterion.signalType(), and org.onosproject.net.flow.criteria.OduSignalTypeCriterion.type().
OduSignalType org.onosproject.net.flow.criteria.OduSignalTypeCriterion.signalType ()
Returns the ODU Signal Type to match.
Returns
the ODU signal Type to match
Definition at line 54 of file OduSignalTypeCriterion.java.
Referenced by org.onosproject.net.flow.criteria.OduSignalTypeCriterion.hashCode(), and org.onosproject.net.flow.criteria.OduSignalTypeCriterion.toString().
String org.onosproject.net.flow.criteria.OduSignalTypeCriterion.toString ()
Definition at line 76 of file OduSignalTypeCriterion.java.
References org.onosproject.net.flow.criteria.OduSignalTypeCriterion.signalType(), and org.onosproject.net.flow.criteria.OduSignalTypeCriterion.type().
Type org.onosproject.net.flow.criteria.OduSignalTypeCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 45 of file OduSignalTypeCriterion.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ODU_SIGTYPE.
Referenced by org.onosproject.net.flow.criteria.OduSignalTypeCriterion.hashCode(), and org.onosproject.net.flow.criteria.OduSignalTypeCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/OduSignalTypeCriterion.java