onos: org.onosproject.net.device.DeviceEvent Class Reference
org.onosproject.net.device.DeviceEvent Class Reference
Describes infrastructure device event.
Classes
enum Type
Type of device events.
Public Member Functions
DeviceEvent (Type type, Device device)
Creates an event of a given type and for the specified device and the current time.
DeviceEvent (Type type, Device device, Port port)
Creates an event of a given type and for the specified device, port and the current time.
DeviceEvent (Type type, Device device, Port port, long time)
Creates an event of a given type and for the specified device and time.
Port port ()
Returns the port subject.
String toString ()
Detailed Description
Describes infrastructure device event.
Definition at line 28 of file DeviceEvent.java.
Constructor & Destructor Documentation
org.onosproject.net.device.DeviceEvent.DeviceEvent (Type type, Device device)
Creates an event of a given type and for the specified device and the current time.
Parameters
type device event type
device event device subject
Definition at line 90 of file DeviceEvent.java.
References create-flow.device.
org.onosproject.net.device.DeviceEvent.DeviceEvent (Type type, Device device, Port port)
Creates an event of a given type and for the specified device, port and the current time.
Parameters
type device event type
device event device subject
port optional port subject
Definition at line 102 of file DeviceEvent.java.
References org.onosproject.net.device.DeviceEvent.port().
org.onosproject.net.device.DeviceEvent.DeviceEvent (Type type, Device device, Port port, long time)
Creates an event of a given type and for the specified device and time.
Parameters
type device event type
device event device subject
port optional port subject
time occurrence time
Definition at line 115 of file DeviceEvent.java.
References org.onosproject.net.device.DeviceEvent.port().
Member Function Documentation
Port org.onosproject.net.device.DeviceEvent.port ()
Returns the port subject.
Returns
port subject or null if the event is not port specific.
Definition at line 125 of file DeviceEvent.java.
Referenced by org.onosproject.net.device.DeviceEvent.DeviceEvent(), and org.onosproject.net.device.DeviceEvent.toString().
String org.onosproject.net.device.DeviceEvent.toString ()
Definition at line 130 of file DeviceEvent.java.
References org.onosproject.net.device.DeviceEvent.port().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/device/DeviceEvent.java