onos: org.onosproject.incubator.net.mcast.impl.MulticastRouteManager Class Reference
org.onosproject.incubator.net.mcast.impl.MulticastRouteManager Class Reference
An implementation of a multicast route table.
Public Member Functions
void activate ()
void deactivate ()
void add (McastRoute route)
Adds a route to the information base.
void remove (McastRoute route)
Removes a route from the information base.
void addSource (McastRoute route, ConnectPoint connectPoint)
Adds a source connection to the route from where the data stream is originating.
void addSink (McastRoute route, ConnectPoint connectPoint)
Adds a sink to the route to which a data stream should be sent to.
void removeSink (McastRoute route, ConnectPoint connectPoint)
Removes a sink from the route.
ConnectPoint fetchSource (McastRoute route)
Find the data source association for this multicast route.
List< ConnectPoint > fetchSinks (McastRoute route)
Find the list of sinks for this route.
Protected Attributes
ApplicationId appId
ConsistentMap< McastRoute,
MulticastData > mcastRoutes
Detailed Description
An implementation of a multicast route table.
Definition at line 50 of file MulticastRouteManager.java.
Member Function Documentation
void org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.activate ()
Definition at line 70 of file MulticastRouteManager.java.
References org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.appId, and org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.mcastRoutes.
void org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.add (McastRoute route)
Adds a route to the information base.
Parameters
route a multicast route
Implements org.onosproject.net.mcast.MulticastRouteService.
Definition at line 97 of file MulticastRouteManager.java.
void org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.addSink (McastRoute route, ConnectPoint connectPoint)
Adds a sink to the route to which a data stream should be sent to.
Parameters
route a multicast route
connectPoint a sink connect point
Implements org.onosproject.net.mcast.MulticastRouteService.
Definition at line 126 of file MulticastRouteManager.java.
void org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.addSource (McastRoute route, ConnectPoint connectPoint)
Adds a source connection to the route from where the data stream is originating.
Parameters
route the multicast route
connectPoint a source connect point
Implements org.onosproject.net.mcast.MulticastRouteService.
Definition at line 109 of file MulticastRouteManager.java.
void org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.deactivate ()
Definition at line 92 of file MulticastRouteManager.java.
List<ConnectPoint> org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.fetchSinks (McastRoute route)
Find the list of sinks for this route.
Parameters
route a multicast route
Returns
a list of connect points
Implements org.onosproject.net.mcast.MulticastRouteService.
Definition at line 169 of file MulticastRouteManager.java.
References org.onosproject.incubator.net.mcast.impl.MulticastData.empty().
ConnectPoint org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.fetchSource (McastRoute route)
Find the data source association for this multicast route.
Parameters
route a multicast route
Returns
a connect point
Implements org.onosproject.net.mcast.MulticastRouteService.
Definition at line 162 of file MulticastRouteManager.java.
References org.onosproject.incubator.net.mcast.impl.MulticastData.empty().
Referenced by org.onosproject.incubator.net.mcast.impl.MulticastRouteManagerTest.testAddSource().
void org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.remove (McastRoute route)
Removes a route from the information base.
Parameters
route a multicast route
Implements org.onosproject.net.mcast.MulticastRouteService.
Definition at line 103 of file MulticastRouteManager.java.
void org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.removeSink (McastRoute route, ConnectPoint connectPoint)
Removes a sink from the route.
Parameters
route the multicast route
connectPoint a sink connect point
Implements org.onosproject.net.mcast.MulticastRouteService.
Definition at line 146 of file MulticastRouteManager.java.
Member Data Documentation
ApplicationId org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.appId protected
Definition at line 66 of file MulticastRouteManager.java.
Referenced by org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.activate().
ConsistentMap<McastRoute, MulticastData> org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.mcastRoutes protected
Definition at line 67 of file MulticastRouteManager.java.
Referenced by org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.activate(), org.onosproject.incubator.net.mcast.impl.MulticastRouteManagerTest.testAdd(), and org.onosproject.incubator.net.mcast.impl.MulticastRouteManagerTest.testRemove().
The documentation for this class was generated from the following file:
incubator/net/src/main/java/org/onosproject/incubator/net/mcast/impl/MulticastRouteManager.java