onos: org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter Class Reference
org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter Class Reference
Classes
class PcepClientAgent
Implementation of an Pcep Agent which is responsible for keeping track of connected clients and the state in which they are.
Public Member Functions
void activate ()
void deactivate ()
Collection< PcepClient > getClients ()
Returns list of pcc clients connected to this Pcep controller.
PcepClient getClient (PccId pccId)
Returns the actual pcc client for the given ip address.
void addListener (PcepClientListener listener)
Register a listener for meta events that occur to pcep devices.
void removeListener (PcepClientListener listener)
Unregister a listener.
void addEventListener (PcepEventListener listener)
Register a listener for OF msg events.
void removeEventListener (PcepEventListener listener)
Unregister a listener.
void writeMessage (PccId pccId, PcepMessage msg)
Send a message to a particular pcc client.
void processClientMessage (PccId pccId, PcepMessage msg)
Process a message and notify the appropriate listeners.
void closeConnectedClients ()
Close all connected PCC clients.
Protected Attributes
ConcurrentHashMap< PccId,
PcepClient > connectedClients
PcepClientAgent agent = new PcepClientAgent()
Set< PcepClientListener > pcepClientListener = new HashSet<>()
Set< PcepEventListener > pcepEventListener = Sets.newHashSet()
Detailed Description
Definition at line 38 of file PcepClientControllerAdapter.java.
Member Function Documentation
void org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.activate ()
Definition at line 49 of file PcepClientControllerAdapter.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.addEventListener (PcepEventListener listener)
Register a listener for OF msg events.
Parameters
listener the listener to notify
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 82 of file PcepClientControllerAdapter.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.addListener (PcepClientListener listener)
Register a listener for meta events that occur to pcep devices.
Parameters
listener the listener to notify
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 70 of file PcepClientControllerAdapter.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.pcepClientListener.
void org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.closeConnectedClients ()
Close all connected PCC clients.
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 149 of file PcepClientControllerAdapter.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.connectedClients, and org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.getClient().
void org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.deactivate ()
Definition at line 53 of file PcepClientControllerAdapter.java.
PcepClient org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.getClient (PccId pccId)
Returns the actual pcc client for the given ip address.
Parameters
pccId the id of the pcc client to fetch
Returns
the interface to this pcc client
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 62 of file PcepClientControllerAdapter.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.closeConnectedClients(), and org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.processClientMessage().
Collection<PcepClient> org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.getClients ()
Returns list of pcc clients connected to this Pcep controller.
Returns
list of PcepClient elements
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 57 of file PcepClientControllerAdapter.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.processClientMessage (PccId pccId, PcepMessage msg)
Process a message and notify the appropriate listeners.
Parameters
pccId id of the client the message arrived on
msg the message to process.
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 97 of file PcepClientControllerAdapter.java.
References org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.getClient(), org.onosproject.pcepio.protocol.PcepMessage.getType(), and org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.pcepEventListener.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.PcepClientAgent.processPcepMessage().
void org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.removeEventListener (PcepEventListener listener)
Unregister a listener.
Parameters
listener the listener to unregister
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 87 of file PcepClientControllerAdapter.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.removeListener (PcepClientListener listener)
Unregister a listener.
Parameters
listener the listener to unregister
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 77 of file PcepClientControllerAdapter.java.
void org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.writeMessage (PccId pccId, PcepMessage msg)
Send a message to a particular pcc client.
Parameters
pccId the id of the client to send message.
msg the message to send
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 92 of file PcepClientControllerAdapter.java.
Member Data Documentation
PcepClientAgent org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.agent = new PcepClientAgent() protected
Definition at line 43 of file PcepClientControllerAdapter.java.
ConcurrentHashMap<PccId, PcepClient> org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.connectedClients protected
Initial value:
=
            new ConcurrentHashMap<PccId, PcepClient>()
Definition at line 40 of file PcepClientControllerAdapter.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.PcepClientAgent.addConnectedClient(), org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.closeConnectedClients(), and org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.PcepClientAgent.validActivation().
Set<PcepClientListener> org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.pcepClientListener = new HashSet<>() protected
Definition at line 44 of file PcepClientControllerAdapter.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.PcepClientAgent.addConnectedClient(), org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.addListener(), and org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.PcepClientAgent.removeConnectedClient().
Set<PcepEventListener> org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.pcepEventListener = Sets.newHashSet() protected
Definition at line 46 of file PcepClientControllerAdapter.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.processClientMessage().
The documentation for this class was generated from the following file:
providers/pcep/tunnel/src/test/java/org/onosproject/provider/pcep/tunnel/impl/PcepClientControllerAdapter.java