onos: org.onosproject.net.newresource.ResourceAllocation Class Reference
org.onosproject.net.newresource.ResourceAllocation Class Reference
Represents allocation of resource which is identified by the specifier.
Public Member Functions
ResourceAllocation (ResourcePath resource, ResourceConsumer consumer)
Creates an instance with the specified subject, resource and consumer.
ResourcePath resource ()
Returns the specifier of the resource this allocation uses.
ResourceConsumer consumer ()
Returns the consumer of this resource.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Represents allocation of resource which is identified by the specifier.
Definition at line 29 of file ResourceAllocation.java.
Constructor & Destructor Documentation
org.onosproject.net.newresource.ResourceAllocation.ResourceAllocation (ResourcePath resource, ResourceConsumer consumer)
Creates an instance with the specified subject, resource and consumer.
Parameters
resource resource of the subject
consumer consumer ot this resource
Definition at line 40 of file ResourceAllocation.java.
References org.onosproject.net.newresource.ResourceAllocation.consumer().
Member Function Documentation
ResourceConsumer org.onosproject.net.newresource.ResourceAllocation.consumer ()
Returns the consumer of this resource.
Returns
the consumer of this resource
Definition at line 65 of file ResourceAllocation.java.
Referenced by org.onosproject.net.newresource.ResourceAllocation.hashCode(), org.onosproject.net.newresource.impl.ResourceManager.release(), org.onosproject.net.newresource.ResourceAllocation.ResourceAllocation(), and org.onosproject.net.newresource.ResourceAllocation.toString().
boolean org.onosproject.net.newresource.ResourceAllocation.equals (Object obj)
Definition at line 75 of file ResourceAllocation.java.
int org.onosproject.net.newresource.ResourceAllocation.hashCode ()
Definition at line 70 of file ResourceAllocation.java.
References org.onosproject.net.newresource.ResourceAllocation.consumer(), and org.onosproject.net.newresource.ResourceAllocation.resource().
ResourcePath org.onosproject.net.newresource.ResourceAllocation.resource ()
Returns the specifier of the resource this allocation uses.
Returns
the specifier of the resource this allocation uses
Definition at line 56 of file ResourceAllocation.java.
Referenced by org.onosproject.net.newresource.ResourceAllocation.hashCode(), org.onosproject.net.newresource.impl.ResourceManager.release(), and org.onosproject.net.newresource.ResourceAllocation.toString().
String org.onosproject.net.newresource.ResourceAllocation.toString ()
Definition at line 88 of file ResourceAllocation.java.
References org.onosproject.net.newresource.ResourceAllocation.consumer(), and org.onosproject.net.newresource.ResourceAllocation.resource().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/newresource/ResourceAllocation.java