onos: org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest Class Reference
org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest Class Reference
Unit tests for FlowClassifierManager class.
Public Member Functions
void testCreateFlowClassifier ()
Checks the operation of createFlowClassifier() method.
void testExists ()
Checks the operation of exists() method.
void testGetFlowClassifierCount ()
Checks the operation of getFlowClassifierCount() method.
void testGetFlowClassifiers ()
Checks the operation of getFlowClassifiers() method.
void testGetFlowClassifier ()
Checks the operation of getFlowClassifier() method.
void testUpdateFlowClassifier ()
Checks the operation of updateFlowClassifier() method.
void testRemoveFlowClassifier ()
Checks the operation of removeFlowClassifier() method.
Detailed Description
Unit tests for FlowClassifierManager class.
Definition at line 36 of file FlowClassifierManagerTest.java.
Member Function Documentation
void org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testCreateFlowClassifier ()
Checks the operation of createFlowClassifier() method.
Definition at line 61 of file FlowClassifierManagerTest.java.
References org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.createFlowClassifier().
Referenced by org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testExists(), org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testGetFlowClassifier(), org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testGetFlowClassifierCount(), org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testGetFlowClassifiers(), org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testRemoveFlowClassifier(), and org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testUpdateFlowClassifier().
void org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testExists ()
Checks the operation of exists() method.
Definition at line 79 of file FlowClassifierManagerTest.java.
References org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.exists(), and org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testCreateFlowClassifier().
void org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testGetFlowClassifier ()
Checks the operation of getFlowClassifier() method.
Definition at line 108 of file FlowClassifierManagerTest.java.
References org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.getFlowClassifier(), and org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testCreateFlowClassifier().
void org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testGetFlowClassifierCount ()
Checks the operation of getFlowClassifierCount() method.
Definition at line 88 of file FlowClassifierManagerTest.java.
References org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.getFlowClassifierCount(), and org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testCreateFlowClassifier().
void org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testGetFlowClassifiers ()
Checks the operation of getFlowClassifiers() method.
Definition at line 97 of file FlowClassifierManagerTest.java.
References org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testCreateFlowClassifier().
void org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testRemoveFlowClassifier ()
Checks the operation of removeFlowClassifier() method.
Definition at line 142 of file FlowClassifierManagerTest.java.
References org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.removeFlowClassifier(), and org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testCreateFlowClassifier().
void org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testUpdateFlowClassifier ()
Checks the operation of updateFlowClassifier() method.
Definition at line 118 of file FlowClassifierManagerTest.java.
References org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testCreateFlowClassifier(), and org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.updateFlowClassifier().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/test/java/org/onosproject/vtnrsc/flowclassifier/impl/FlowClassifierManagerTest.java