onos: org.onosproject.store.cluster.messaging.Endpoint Class Reference
org.onosproject.store.cluster.messaging.Endpoint Class Reference
Representation of a TCP/UDP communication end point.
Public Member Functions
Endpoint (IpAddress host, int port)
IpAddress host ()
int port ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Representation of a TCP/UDP communication end point.
Definition at line 29 of file Endpoint.java.
Constructor & Destructor Documentation
org.onosproject.store.cluster.messaging.Endpoint.Endpoint (IpAddress host, int port)
Definition at line 34 of file Endpoint.java.
References org.onosproject.store.cluster.messaging.Endpoint.port().
Referenced by org.onosproject.store.cluster.messaging.Endpoint.equals().
Member Function Documentation
boolean org.onosproject.store.cluster.messaging.Endpoint.equals (Object obj)
Definition at line 61 of file Endpoint.java.
References org.onosproject.store.cluster.messaging.Endpoint.Endpoint(), org.onosproject.store.cluster.messaging.Endpoint.equals(), and obeliskHostCheck.port.
Referenced by org.onosproject.store.cluster.messaging.Endpoint.equals(), org.onlab.nio.service.IOLoopMessaging.sendAsync(), and org.onlab.netty.NettyMessaging.sendAsync().
int org.onosproject.store.cluster.messaging.Endpoint.hashCode ()
Definition at line 56 of file Endpoint.java.
References org.onosproject.store.cluster.messaging.Endpoint.port().
IpAddress org.onosproject.store.cluster.messaging.Endpoint.host ()
Definition at line 39 of file Endpoint.java.
Referenced by org.onlab.nio.service.IOLoopMessaging.start(), and org.onosproject.store.cluster.messaging.EndpointTest.testConstruction().
int org.onosproject.store.cluster.messaging.Endpoint.port ()
Definition at line 43 of file Endpoint.java.
Referenced by org.onosproject.store.cluster.messaging.Endpoint.Endpoint(), org.onosproject.store.cluster.messaging.Endpoint.hashCode(), and org.onosproject.store.cluster.messaging.Endpoint.toString().
String org.onosproject.store.cluster.messaging.Endpoint.toString ()
Definition at line 48 of file Endpoint.java.
References org.onosproject.store.cluster.messaging.Endpoint.port().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/store/cluster/messaging/Endpoint.java