onos: org.onlab.packet.ipv6.EncapSecurityPayloadTest Class Reference
org.onlab.packet.ipv6.EncapSecurityPayloadTest Class Reference
Tests for class EncapSecurityPayload.
Public Member Functions
void setUp ()
void testSerialize ()
Tests serialize and setters.
void testDeserialize () throws DeserializationException
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class EncapSecurityPayload.
Definition at line 37 of file EncapSecurityPayloadTest.java.
Member Function Documentation
void org.onlab.packet.ipv6.EncapSecurityPayloadTest.setUp ()
Definition at line 60 of file EncapSecurityPayloadTest.java.
static void org.onlab.packet.ipv6.EncapSecurityPayloadTest.setUpBeforeClass () throws Exception static
Definition at line 45 of file EncapSecurityPayloadTest.java.
References find-link-in-cluster.length.
void org.onlab.packet.ipv6.EncapSecurityPayloadTest.testDeserialize () throws DeserializationException
Tests deserialize and getters.
Definition at line 81 of file EncapSecurityPayloadTest.java.
References org.onlab.packet.ipv6.EncapSecurityPayload.getSecurityParamIndex(), org.onlab.packet.ipv6.EncapSecurityPayload.getSequence(), and find-link-in-cluster.length.
void org.onlab.packet.ipv6.EncapSecurityPayloadTest.testEqual ()
Tests comparator.
Definition at line 92 of file EncapSecurityPayloadTest.java.
References org.onlab.packet.ipv6.EncapSecurityPayload.equals().
void org.onlab.packet.ipv6.EncapSecurityPayloadTest.testSerialize ()
Tests serialize and setters.
Definition at line 68 of file EncapSecurityPayloadTest.java.
References org.onlab.packet.ipv6.EncapSecurityPayload.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ipv6/EncapSecurityPayloadTest.java