onos: org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier Class Reference
org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier Class Reference
Representation of policy based group identifiers.
Public Member Functions
int hashCode ()
boolean equals (Object obj)
Protected Member Functions
PolicyGroupIdentifier (String id, List< PolicyGroupParams > input, List< GroupBucketIdentifier > bucketIds)
Constructor.
List< GroupBucketIdentifier > bucketIds ()
Returns the bucket identifier list associated with the policy group identifier.
Detailed Description
Representation of policy based group identifiers.
Opaque to group handler applications and only the outermost policy group identifier in a chain is visible to the applications.
Definition at line 25 of file PolicyGroupIdentifier.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier.PolicyGroupIdentifier (String id, List< PolicyGroupParams > input, List< GroupBucketIdentifier > bucketIds) protected
Constructor.
Parameters
id unique identifier associated with the policy group
input policy group params associated with this group
bucketIds buckets associated with this group
Definition at line 37 of file PolicyGroupIdentifier.java.
References org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier.bucketIds().
Referenced by org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier.equals().
Member Function Documentation
List<GroupBucketIdentifier> org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier.bucketIds () protected
Returns the bucket identifier list associated with the policy group identifier.
Returns
list of bucket identifier
Definition at line 51 of file PolicyGroupIdentifier.java.
Referenced by org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier.hashCode(), and org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier.PolicyGroupIdentifier().
boolean org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier.equals (Object obj)
Definition at line 71 of file PolicyGroupIdentifier.java.
References find-device.id, and org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier.PolicyGroupIdentifier().
int org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier.hashCode ()
Definition at line 56 of file PolicyGroupIdentifier.java.
References org.onosproject.segmentrouting.grouphandler.PolicyGroupIdentifier.bucketIds().
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/grouphandler/PolicyGroupIdentifier.java