onos: org.onosproject.cfg.ConfigPropertyTest Class Reference
org.onosproject.cfg.ConfigPropertyTest Class Reference
Set of tests of the configuration property class.
Public Member Functions
void basics ()
void equality ()
void asInteger ()
void asLong ()
void asFloat ()
void asDouble ()
void asBoolean ()
Detailed Description
Set of tests of the configuration property class.
Definition at line 31 of file ConfigPropertyTest.java.
Member Function Documentation
void org.onosproject.cfg.ConfigPropertyTest.asBoolean ()
Definition at line 92 of file ConfigPropertyTest.java.
References org.onosproject.cfg.ConfigProperty.asBoolean().
void org.onosproject.cfg.ConfigPropertyTest.asDouble ()
Definition at line 85 of file ConfigPropertyTest.java.
References org.onosproject.cfg.ConfigProperty.asDouble().
void org.onosproject.cfg.ConfigPropertyTest.asFloat ()
Definition at line 77 of file ConfigPropertyTest.java.
References org.onosproject.cfg.ConfigProperty.asDouble(), and org.onosproject.cfg.ConfigProperty.asFloat().
void org.onosproject.cfg.ConfigPropertyTest.asInteger ()
Definition at line 62 of file ConfigPropertyTest.java.
References org.onosproject.cfg.ConfigProperty.asInteger(), and org.onosproject.cfg.ConfigProperty.asLong().
void org.onosproject.cfg.ConfigPropertyTest.asLong ()
Definition at line 70 of file ConfigPropertyTest.java.
References org.onosproject.cfg.ConfigProperty.asLong().
void org.onosproject.cfg.ConfigPropertyTest.basics ()
Definition at line 34 of file ConfigPropertyTest.java.
void org.onosproject.cfg.ConfigPropertyTest.equality ()
Definition at line 44 of file ConfigPropertyTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/cfg/ConfigPropertyTest.java