onos: org.onosproject.vtnrsc.RouterGateway Class Reference
org.onosproject.vtnrsc.RouterGateway Class Reference
Representation of a Router gateway.
Public Member Functions
TenantNetworkId networkId ()
Returns network identifier.
boolean enableSnat ()
Return SNAT enable or not.
Collection< FixedIp > externalFixedIps ()
Return external fixed Ip.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static RouterGateway routerGateway (TenantNetworkId networkId, boolean enableSnat, Collection< FixedIp > externalFixedIps)
Creates router gateway object.
Detailed Description
Representation of a Router gateway.
Definition at line 27 of file RouterGateway.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.RouterGateway.enableSnat ()
Return SNAT enable or not.
Returns
enableSnat
Definition at line 68 of file RouterGateway.java.
Referenced by org.onosproject.vtnrsc.RouterGateway.hashCode().
boolean org.onosproject.vtnrsc.RouterGateway.equals (Object obj)
Definition at line 87 of file RouterGateway.java.
Collection<FixedIp> org.onosproject.vtnrsc.RouterGateway.externalFixedIps ()
Return external fixed Ip.
Returns
externalFixedIps
Definition at line 77 of file RouterGateway.java.
Referenced by org.onosproject.vtnrsc.RouterGateway.hashCode(), and org.onosproject.vtnrsc.RouterGateway.toString().
int org.onosproject.vtnrsc.RouterGateway.hashCode ()
Definition at line 82 of file RouterGateway.java.
References org.onosproject.vtnrsc.RouterGateway.enableSnat(), org.onosproject.vtnrsc.RouterGateway.externalFixedIps(), and org.onosproject.vtnrsc.RouterGateway.networkId().
TenantNetworkId org.onosproject.vtnrsc.RouterGateway.networkId ()
Returns network identifier.
Returns
networkId
Definition at line 59 of file RouterGateway.java.
Referenced by org.onosproject.vtnrsc.RouterGateway.hashCode(), and org.onosproject.vtnrsc.RouterGateway.toString().
static RouterGateway org.onosproject.vtnrsc.RouterGateway.routerGateway (TenantNetworkId networkId, boolean enableSnat, Collection< FixedIp > externalFixedIps) static
Creates router gateway object.
Parameters
networkId network identifier
enableSnat SNAT enable or not
externalFixedIps external fixed IP
Returns
RouterGateway
Definition at line 49 of file RouterGateway.java.
String org.onosproject.vtnrsc.RouterGateway.toString ()
Definition at line 101 of file RouterGateway.java.
References org.onosproject.vtnrsc.RouterGateway.externalFixedIps(), and org.onosproject.vtnrsc.RouterGateway.networkId().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/RouterGateway.java