onos: org.onosproject.store.impl.LogicalTimestamp Class Reference
org.onosproject.store.impl.LogicalTimestamp Class Reference
Timestamp based on logical sequence value.
Public Member Functions
LogicalTimestamp (long value)
int compareTo (Timestamp o)
int hashCode ()
boolean equals (Object obj)
String toString ()
long value ()
Returns the sequence value.
Public Member Functions inherited from org.onosproject.store.Timestamp
default boolean isNewerThan (Timestamp other)
Tests if this timestamp is newer than the specified timestamp.
default boolean isOlderThan (Timestamp other)
Tests if this timestamp is older than the specified timestamp.
Detailed Description
Timestamp based on logical sequence value.
LogicalTimestamps are ordered by their sequence values.
Definition at line 32 of file LogicalTimestamp.java.
Constructor & Destructor Documentation
org.onosproject.store.impl.LogicalTimestamp.LogicalTimestamp (long value)
Definition at line 36 of file LogicalTimestamp.java.
References org.onosproject.store.impl.LogicalTimestamp.value().
Referenced by org.onosproject.store.impl.LogicalTimestamp.compareTo(), and org.onosproject.store.impl.LogicalTimestamp.equals().
Member Function Documentation
int org.onosproject.store.impl.LogicalTimestamp.compareTo (Timestamp o)
Definition at line 41 of file LogicalTimestamp.java.
References org.onosproject.store.impl.LogicalTimestamp.LogicalTimestamp(), and org.onosproject.store.impl.LogicalTimestamp.value().
boolean org.onosproject.store.impl.LogicalTimestamp.equals (Object obj)
Implements org.onosproject.store.Timestamp.
Definition at line 57 of file LogicalTimestamp.java.
References org.onosproject.store.impl.LogicalTimestamp.LogicalTimestamp().
int org.onosproject.store.impl.LogicalTimestamp.hashCode ()
Implements org.onosproject.store.Timestamp.
Definition at line 52 of file LogicalTimestamp.java.
References org.onosproject.store.impl.LogicalTimestamp.value().
String org.onosproject.store.impl.LogicalTimestamp.toString ()
Definition at line 69 of file LogicalTimestamp.java.
References org.onosproject.store.impl.LogicalTimestamp.value().
long org.onosproject.store.impl.LogicalTimestamp.value ()
Returns the sequence value.
Returns
sequence value
Definition at line 80 of file LogicalTimestamp.java.
Referenced by org.onosproject.store.impl.LogicalTimestamp.compareTo(), org.onosproject.store.impl.LogicalTimestamp.hashCode(), org.onosproject.store.impl.LogicalTimestamp.LogicalTimestamp(), and org.onosproject.store.impl.LogicalTimestamp.toString().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/impl/LogicalTimestamp.java