onos: org.onosproject.pcepio.types.RoutingUniverseTlv Class Reference
org.onosproject.pcepio.types.RoutingUniverseTlv Class Reference
Provides RoutingUniverseTLV identifiers.
Public Member Functions
RoutingUniverseTlv (long rawValue)
Constructor to initialize raw value.
long getLong ()
Returns raw value as Identifier.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static RoutingUniverseTlv of (final long raw)
Returns object of RoutingUniverseTLV.
static RoutingUniverseTlv read (ChannelBuffer c)
Reads from channel buffer and returns object of RoutingUniverseTLV.
Static Public Attributes
static final short TYPE = 14
static final short LENGTH = 8
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(RoutingUniverseTlv.class)
Detailed Description
Provides RoutingUniverseTLV identifiers.
Definition at line 30 of file RoutingUniverseTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.RoutingUniverseTlv.RoutingUniverseTlv (long rawValue)
Constructor to initialize raw value.
Parameters
rawValue raw value
Definition at line 65 of file RoutingUniverseTlv.java.
Referenced by org.onosproject.pcepio.types.RoutingUniverseTlv.equals(), and org.onosproject.pcepio.types.RoutingUniverseTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.RoutingUniverseTlv.equals (Object obj)
Definition at line 109 of file RoutingUniverseTlv.java.
References org.onosproject.pcepio.types.RoutingUniverseTlv.RoutingUniverseTlv().
short org.onosproject.pcepio.types.RoutingUniverseTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 99 of file RoutingUniverseTlv.java.
References org.onosproject.pcepio.types.RoutingUniverseTlv.LENGTH.
long org.onosproject.pcepio.types.RoutingUniverseTlv.getLong ()
Returns raw value as Identifier.
Returns
rawValue Identifier
Definition at line 84 of file RoutingUniverseTlv.java.
short org.onosproject.pcepio.types.RoutingUniverseTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 94 of file RoutingUniverseTlv.java.
References org.onosproject.pcepio.types.RoutingUniverseTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.RoutingUniverseTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 89 of file RoutingUniverseTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.RoutingUniverseTlv.hashCode ()
Definition at line 104 of file RoutingUniverseTlv.java.
static RoutingUniverseTlv org.onosproject.pcepio.types.RoutingUniverseTlv.of (final long raw) static
Returns object of RoutingUniverseTLV.
Parameters
raw value
Returns
object of RoutingUniverseTLV
Definition at line 75 of file RoutingUniverseTlv.java.
References org.onosproject.pcepio.types.RoutingUniverseTlv.RoutingUniverseTlv().
static RoutingUniverseTlv org.onosproject.pcepio.types.RoutingUniverseTlv.read (ChannelBuffer c) static
Reads from channel buffer and returns object of RoutingUniverseTLV.
Parameters
c input channel buffer
Returns
object of RoutingUniverseTLV
Definition at line 135 of file RoutingUniverseTlv.java.
String org.onosproject.pcepio.types.RoutingUniverseTlv.toString ()
Definition at line 140 of file RoutingUniverseTlv.java.
References org.onosproject.pcepio.types.RoutingUniverseTlv.LENGTH, and org.onosproject.pcepio.types.RoutingUniverseTlv.TYPE.
int org.onosproject.pcepio.types.RoutingUniverseTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 121 of file RoutingUniverseTlv.java.
References org.onosproject.pcepio.types.RoutingUniverseTlv.LENGTH, and org.onosproject.pcepio.types.RoutingUniverseTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.RoutingUniverseTlv.LENGTH = 8 static
Definition at line 56 of file RoutingUniverseTlv.java.
Referenced by org.onosproject.pcepio.types.RoutingUniverseTlv.getLength(), org.onosproject.pcepio.types.RoutingUniverseTlv.toString(), and org.onosproject.pcepio.types.RoutingUniverseTlv.write().
final Logger org.onosproject.pcepio.types.RoutingUniverseTlv.log = LoggerFactory.getLogger(RoutingUniverseTlv.class) static protected
Definition at line 53 of file RoutingUniverseTlv.java.
final short org.onosproject.pcepio.types.RoutingUniverseTlv.TYPE = 14 static
Definition at line 55 of file RoutingUniverseTlv.java.
Referenced by org.onosproject.pcepio.types.RoutingUniverseTlv.getType(), org.onosproject.pcepio.types.RoutingUniverseTlv.toString(), and org.onosproject.pcepio.types.RoutingUniverseTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/RoutingUniverseTlv.java