onos: org.onosproject.net.intent.constraint.LambdaConstraint Class Reference
org.onosproject.net.intent.constraint.LambdaConstraint Class Reference
Constraint that evaluates links based on available lambda.
Public Member Functions
LambdaConstraint (IndexedLambda lambda)
Creates a new optical lambda constraint.
boolean isValid (Link link, LinkResourceService resourceService)
Returns true if the specified link satisfies the constraint.
IndexedLambda lambda ()
Returns the lambda required by this constraint.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.constraint.BooleanConstraint
double cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
boolean validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
Detailed Description
Constraint that evaluates links based on available lambda.
Definition at line 33 of file LambdaConstraint.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.constraint.LambdaConstraint.LambdaConstraint (IndexedLambda lambda)
Creates a new optical lambda constraint.
Parameters
lambda optional lambda to indicate a specific lambda
Definition at line 42 of file LambdaConstraint.java.
References org.onosproject.net.intent.constraint.LambdaConstraint.lambda().
Member Function Documentation
boolean org.onosproject.net.intent.constraint.LambdaConstraint.equals (Object obj)
Definition at line 76 of file LambdaConstraint.java.
int org.onosproject.net.intent.constraint.LambdaConstraint.hashCode ()
Definition at line 71 of file LambdaConstraint.java.
References org.onosproject.net.intent.constraint.LambdaConstraint.lambda().
boolean org.onosproject.net.intent.constraint.LambdaConstraint.isValid (Link link, LinkResourceService resourceService) virtual
Returns true if the specified link satisfies the constraint.
Parameters
link link to be validated
resourceService resource service for checking available link resources
Returns
true if link is viable
Implements org.onosproject.net.intent.constraint.BooleanConstraint.
Definition at line 52 of file LambdaConstraint.java.
References org.onosproject.net.resource.link.LinkResourceService.getAvailableResources(), and org.onosproject.net.resource.ResourceType.LAMBDA.
IndexedLambda org.onosproject.net.intent.constraint.LambdaConstraint.lambda ()
Returns the lambda required by this constraint.
Returns
required lambda
Definition at line 66 of file LambdaConstraint.java.
Referenced by org.onosproject.net.intent.constraint.LambdaConstraint.hashCode(), org.onosproject.net.intent.constraint.LambdaConstraint.LambdaConstraint(), and org.onosproject.net.intent.constraint.LambdaConstraint.toString().
String org.onosproject.net.intent.constraint.LambdaConstraint.toString ()
Definition at line 88 of file LambdaConstraint.java.
References org.onosproject.net.intent.constraint.LambdaConstraint.lambda().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/constraint/LambdaConstraint.java