onos: org.onlab.packet.pim.PIMAddrUnicast Class Reference
org.onlab.packet.pim.PIMAddrUnicast Class Reference
Public Member Functions
PIMAddrUnicast ()
PIM Encoded Source Address.
PIMAddrUnicast (String addr)
PIM Encoded Source Address.
void setAddr (IpAddress addr)
PIM Encoded Source Address.
IpAddress getAddr ()
Get the address of this encoded address.
int getFamily ()
Get the IP family of this address: 4 or 6.
int getByteSize ()
The size in bytes of a serialized address.
byte[] serialize ()
PIMAddrUnicast deserialize (ByteBuffer bb) throws DeserializationException
int hashCode ()
boolean equals (final Object obj)
Static Public Attributes
static final int ENC_UNICAST_IPV4_BYTE_LENGTH = 2 + Ip4Address.BYTE_LENGTH
static final int ENC_UNICAST_IPV6_BYTE_LENGTH = 2 + Ip6Address.BYTE_LENGTH
Detailed Description
Definition at line 30 of file PIMAddrUnicast.java.
Constructor & Destructor Documentation
org.onlab.packet.pim.PIMAddrUnicast.PIMAddrUnicast ()
PIM Encoded Source Address.
Definition at line 41 of file PIMAddrUnicast.java.
References org.onlab.packet.PIM.ADDRESS_FAMILY_IP4.
Referenced by org.onlab.packet.pim.PIMAddrUnicast.equals().
org.onlab.packet.pim.PIMAddrUnicast.PIMAddrUnicast (String addr)
PIM Encoded Source Address.
Parameters
addr IPv4 or IPv6
Definition at line 51 of file PIMAddrUnicast.java.
References org.onlab.packet.PIM.ADDRESS_FAMILY_IP4, and org.onlab.packet.PIM.ADDRESS_FAMILY_IP6.
Member Function Documentation
PIMAddrUnicast org.onlab.packet.pim.PIMAddrUnicast.deserialize (ByteBuffer bb) throws DeserializationException
Definition at line 120 of file PIMAddrUnicast.java.
References org.onlab.packet.PIM.ADDRESS_FAMILY_IP4, org.onlab.packet.PIM.ADDRESS_FAMILY_IP6, org.onlab.packet.pim.PIMAddrUnicast.ENC_UNICAST_IPV4_BYTE_LENGTH, and org.onlab.packet.pim.PIMAddrUnicast.ENC_UNICAST_IPV6_BYTE_LENGTH.
boolean org.onlab.packet.pim.PIMAddrUnicast.equals (final Object obj)
Definition at line 164 of file PIMAddrUnicast.java.
References org.onlab.packet.IpAddress.equals(), and org.onlab.packet.pim.PIMAddrUnicast.PIMAddrUnicast().
IpAddress org.onlab.packet.pim.PIMAddrUnicast.getAddr ()
Get the address of this encoded address.
Returns
source address
Definition at line 80 of file PIMAddrUnicast.java.
int org.onlab.packet.pim.PIMAddrUnicast.getByteSize ()
The size in bytes of a serialized address.
Returns
the number of bytes when serialized
Definition at line 98 of file PIMAddrUnicast.java.
References onos.size.
Referenced by org.onlab.packet.pim.PIMAddrUnicast.serialize().
int org.onlab.packet.pim.PIMAddrUnicast.getFamily ()
Get the IP family of this address: 4 or 6.
Returns
the IP address family
Definition at line 89 of file PIMAddrUnicast.java.
int org.onlab.packet.pim.PIMAddrUnicast.hashCode ()
Definition at line 149 of file PIMAddrUnicast.java.
byte [] org.onlab.packet.pim.PIMAddrUnicast.serialize ()
Definition at line 108 of file PIMAddrUnicast.java.
References org.onlab.packet.pim.PIMAddrUnicast.getByteSize().
void org.onlab.packet.pim.PIMAddrUnicast.setAddr (IpAddress addr)
PIM Encoded Source Address.
Parameters
addr IPv4 or IPv6
Definition at line 66 of file PIMAddrUnicast.java.
References org.onlab.packet.PIM.ADDRESS_FAMILY_IP4, org.onlab.packet.PIM.ADDRESS_FAMILY_IP6, and org.onlab.packet.IpAddress.isIp4().
Member Data Documentation
final int org.onlab.packet.pim.PIMAddrUnicast.ENC_UNICAST_IPV4_BYTE_LENGTH = 2 + Ip4Address.BYTE_LENGTH static
Definition at line 35 of file PIMAddrUnicast.java.
Referenced by org.onlab.packet.pim.PIMAddrUnicast.deserialize().
final int org.onlab.packet.pim.PIMAddrUnicast.ENC_UNICAST_IPV6_BYTE_LENGTH = 2 + Ip6Address.BYTE_LENGTH static
Definition at line 36 of file PIMAddrUnicast.java.
Referenced by org.onlab.packet.pim.PIMAddrUnicast.deserialize().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/pim/PIMAddrUnicast.java