onos: org.onosproject.incubator.net.domain.IntentDomain Class Reference
org.onosproject.incubator.net.domain.IntentDomain Class Reference
Representation of an intent domain which includes the set of internal devices, the set of edge ports, and the implementation of the domain provider.
Public Member Functions
IntentDomain (IntentDomainId id, String name, Set< DeviceId > internalDevices, Set< ConnectPoint > edgePorts)
IntentDomainId id ()
Returns the id for the intent domain.
String name ()
Returns the friendly name for the intent domain.
Set< DeviceId > internalDevices ()
Returns the set of internal devices for the intent domain (devices under exclusive control of the intent domain).
Set< ConnectPoint > edgePorts ()
Returns the set of edge ports for the intent domain.
IntentDomainProvider provider ()
Returns the provider for the intent domain.
boolean isActive ()
Returns the status of the intent domain.
void setProvider (IntentDomainProvider provider)
Sets the provider for the intent domain if one is not already set.
void unsetProvider ()
Unsets the provider for the intent domain.
Detailed Description
Representation of an intent domain which includes the set of internal devices, the set of edge ports, and the implementation of the domain provider.
Definition at line 29 of file IntentDomain.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.domain.IntentDomain.IntentDomain (IntentDomainId id, String name, Set< DeviceId > internalDevices, Set< ConnectPoint > edgePorts)
Definition at line 39 of file IntentDomain.java.
References org.onosproject.incubator.net.domain.IntentDomain.edgePorts(), org.onosproject.incubator.net.domain.IntentDomain.id(), org.onosproject.incubator.net.domain.IntentDomain.internalDevices(), and org.onosproject.incubator.net.domain.IntentDomain.name().
Member Function Documentation
Set<ConnectPoint> org.onosproject.incubator.net.domain.IntentDomain.edgePorts ()
Returns the set of edge ports for the intent domain.
Returns
set of edge ports
Definition at line 81 of file IntentDomain.java.
Referenced by org.onosproject.incubator.net.domain.IntentDomain.IntentDomain().
IntentDomainId org.onosproject.incubator.net.domain.IntentDomain.id ()
Returns the id for the intent domain.
Returns
intent domain id
Definition at line 53 of file IntentDomain.java.
Referenced by org.onosproject.incubator.net.domain.IntentDomain.IntentDomain().
Set<DeviceId> org.onosproject.incubator.net.domain.IntentDomain.internalDevices ()
Returns the set of internal devices for the intent domain (devices under exclusive control of the intent domain).
Returns
set of internal devices
Definition at line 72 of file IntentDomain.java.
Referenced by org.onosproject.incubator.net.domain.IntentDomain.IntentDomain().
boolean org.onosproject.incubator.net.domain.IntentDomain.isActive ()
Returns the status of the intent domain.
An intent domain is active if it has an intent domain provider bound, and it is inactive if one is not bound.
Returns
true if active; false otherwise
Definition at line 100 of file IntentDomain.java.
References org.onosproject.incubator.net.domain.IntentDomain.provider().
String org.onosproject.incubator.net.domain.IntentDomain.name ()
Returns the friendly name for the intent domain.
Returns
intent domain name
Definition at line 62 of file IntentDomain.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.incubator.net.domain.IntentDomain.IntentDomain(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
IntentDomainProvider org.onosproject.incubator.net.domain.IntentDomain.provider ()
Returns the provider for the intent domain.
Returns
intent domain provider
Definition at line 90 of file IntentDomain.java.
Referenced by org.onosproject.incubator.net.domain.IntentDomain.isActive(), and org.onosproject.incubator.net.domain.IntentDomain.setProvider().
void org.onosproject.incubator.net.domain.IntentDomain.setProvider (IntentDomainProvider provider)
Sets the provider for the intent domain if one is not already set.
Parameters
provider new intent domain provider
Definition at line 109 of file IntentDomain.java.
References org.onosproject.incubator.net.domain.IntentDomain.provider().
void org.onosproject.incubator.net.domain.IntentDomain.unsetProvider ()
Unsets the provider for the intent domain.
Definition at line 119 of file IntentDomain.java.
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/domain/IntentDomain.java