onos: org.onosproject.provider.of.meter.impl.MeterModBuilder Class Reference
org.onosproject.provider.of.meter.impl.MeterModBuilder Class Reference
Builder for a meter modification.
Public Member Functions
MeterModBuilder (long xid, OFFactory factory)
MeterModBuilder withRateUnit (Meter.Unit unit)
MeterModBuilder burst ()
MeterModBuilder withId (MeterId meterId)
MeterModBuilder withBands (Collection< Band > bands)
OFMeterMod add ()
OFMeterMod remove ()
OFMeterMod modify ()
Static Public Member Functions
static MeterModBuilder builder (long xid, OFFactory factory)
Detailed Description
Builder for a meter modification.
Definition at line 41 of file MeterModBuilder.java.
Constructor & Destructor Documentation
org.onosproject.provider.of.meter.impl.MeterModBuilder.MeterModBuilder (long xid, OFFactory factory)
Definition at line 52 of file MeterModBuilder.java.
Referenced by org.onosproject.provider.of.meter.impl.MeterModBuilder.builder().
Member Function Documentation
OFMeterMod org.onosproject.provider.of.meter.impl.MeterModBuilder.add ()
Definition at line 81 of file MeterModBuilder.java.
References org.onosproject.provider.of.meter.impl.MeterModBuilder.builder().
static MeterModBuilder org.onosproject.provider.of.meter.impl.MeterModBuilder.builder (long xid, OFFactory factory) static
Definition at line 57 of file MeterModBuilder.java.
References org.onosproject.provider.of.meter.impl.MeterModBuilder.MeterModBuilder().
Referenced by org.onosproject.provider.of.meter.impl.MeterModBuilder.add(), org.onosproject.provider.of.meter.impl.MeterModBuilder.modify(), and org.onosproject.provider.of.meter.impl.MeterModBuilder.remove().
MeterModBuilder org.onosproject.provider.of.meter.impl.MeterModBuilder.burst ()
Definition at line 66 of file MeterModBuilder.java.
OFMeterMod org.onosproject.provider.of.meter.impl.MeterModBuilder.modify ()
Definition at line 95 of file MeterModBuilder.java.
References org.onosproject.provider.of.meter.impl.MeterModBuilder.builder().
OFMeterMod org.onosproject.provider.of.meter.impl.MeterModBuilder.remove ()
Definition at line 88 of file MeterModBuilder.java.
References org.onosproject.provider.of.meter.impl.MeterModBuilder.builder().
MeterModBuilder org.onosproject.provider.of.meter.impl.MeterModBuilder.withBands (Collection< Band > bands)
Definition at line 76 of file MeterModBuilder.java.
MeterModBuilder org.onosproject.provider.of.meter.impl.MeterModBuilder.withId (MeterId meterId)
Definition at line 71 of file MeterModBuilder.java.
MeterModBuilder org.onosproject.provider.of.meter.impl.MeterModBuilder.withRateUnit (Meter.Unit unit)
Definition at line 61 of file MeterModBuilder.java.
The documentation for this class was generated from the following file:
providers/openflow/meter/src/main/java/org/onosproject/provider/of/meter/impl/MeterModBuilder.java