onos: org.onosproject.incubator.net.domain.IntentResource Class Reference
org.onosproject.incubator.net.domain.IntentResource Class Reference
The abstract base class for the resource that satisfies an intent primitive.
Public Member Functions
IntentResource (IntentPrimitive primitive, ApplicationId appId, ConnectPoint ingress, ConnectPoint egress)
IntentPrimitive primitive ()
Returns the intent primitive associated with this resource at creation.
ApplicationId appId ()
Returns the application ID associated with this resource at creation.
ConnectPoint ingress ()
Returns the ingress connect point associated with this resource at creation.
ConnectPoint egress ()
Returns the egress connect point associated with this resource at creation.
Detailed Description
The abstract base class for the resource that satisfies an intent primitive.
Definition at line 27 of file IntentResource.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.domain.IntentResource.IntentResource (IntentPrimitive primitive, ApplicationId appId, ConnectPoint ingress, ConnectPoint egress)
Definition at line 42 of file IntentResource.java.
References org.onosproject.incubator.net.domain.IntentResource.appId(), org.onosproject.incubator.net.domain.IntentResource.egress(), org.onosproject.incubator.net.domain.IntentResource.ingress(), and org.onosproject.incubator.net.domain.IntentResource.primitive().
Member Function Documentation
ApplicationId org.onosproject.incubator.net.domain.IntentResource.appId ()
Returns the application ID associated with this resource at creation.
Returns
this resource's application ID.
Definition at line 67 of file IntentResource.java.
Referenced by org.onosproject.incubator.net.domain.IntentResource.IntentResource().
ConnectPoint org.onosproject.incubator.net.domain.IntentResource.egress ()
Returns the egress connect point associated with this resource at creation.
Returns
this resource's connect point.
Definition at line 85 of file IntentResource.java.
Referenced by org.onosproject.incubator.net.domain.IntentResource.IntentResource().
ConnectPoint org.onosproject.incubator.net.domain.IntentResource.ingress ()
Returns the ingress connect point associated with this resource at creation.
Returns
this resource's ingress connect point.
Definition at line 76 of file IntentResource.java.
Referenced by org.onosproject.incubator.net.domain.IntentResource.IntentResource().
IntentPrimitive org.onosproject.incubator.net.domain.IntentResource.primitive ()
Returns the intent primitive associated with this resource at creation.
Returns
this resource's intent primitive.
Definition at line 58 of file IntentResource.java.
Referenced by org.onosproject.incubator.net.domain.IntentResource.IntentResource().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/domain/IntentResource.java