onos: org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric Class Reference
org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric Class Reference
Implements BGP link IGP metric attribute.
Public Member Functions
BgpLinkAttrIgpMetric (final int igpMetric, final int igpMetricLen)
Constructor to initialize the value.
int attrLinkIgpMetric ()
Returns the variable length IGP metric data.
int attrLinkIgpMetricLength ()
Returns IGP metric data length.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpLinkAttrIgpMetric of (final int igpMetric, final int igpMetricLen)
Returns object of this class with specified values.
static BgpLinkAttrIgpMetric read (ChannelBuffer cb) throws BgpParseException
Reads the BGP link attributes IGP Metric.
Static Public Attributes
static final int ATTRLINK_IGPMETRIC = 1095
static final int ATTRLINK_MAX_LEN = 3
static final int ISIS_SMALL_METRIC = 1
static final int OSPF_LINK_METRIC = 2
static final int ISIS_WIDE_METRIC = 3
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP link IGP metric attribute.
Definition at line 33 of file BgpLinkAttrIgpMetric.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.BgpLinkAttrIgpMetric (final int igpMetric, final int igpMetricLen)
Constructor to initialize the value.
Parameters
igpMetric 3 byte IGP metric data.
igpMetricLen length of IGP metric data.
Definition at line 56 of file BgpLinkAttrIgpMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.equals(), and org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.of().
Member Function Documentation
int org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.attrLinkIgpMetric ()
Returns the variable length IGP metric data.
Returns
IGP metric data
Definition at line 123 of file BgpLinkAttrIgpMetric.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.attrLinkIgpMetricLength ()
Returns IGP metric data length.
Returns
IGP metric length
Definition at line 132 of file BgpLinkAttrIgpMetric.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 174 of file BgpLinkAttrIgpMetric.java.
boolean org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.equals (Object obj)
Definition at line 147 of file BgpLinkAttrIgpMetric.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.BgpLinkAttrIgpMetric().
short org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 137 of file BgpLinkAttrIgpMetric.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.ATTRLINK_IGPMETRIC.
int org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.hashCode ()
Definition at line 142 of file BgpLinkAttrIgpMetric.java.
static BgpLinkAttrIgpMetric org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.of (final int igpMetric, final int igpMetricLen) static
Returns object of this class with specified values.
Parameters
igpMetric 3 byte IGP metric data.
igpMetricLen length of IGP metric data.
Returns
object of BgpLinkAttrIgpMetric
Definition at line 68 of file BgpLinkAttrIgpMetric.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.BgpLinkAttrIgpMetric().
static BgpLinkAttrIgpMetric org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.read (ChannelBuffer cb) throws BgpParseException static
Reads the BGP link attributes IGP Metric.
Parameters
cb Channel buffer
Returns
object of type BgpLinkAttrIgpMetric
Exceptions
BgpParseException while parsing BgpLinkAttrIgpMetric
Definition at line 80 of file BgpLinkAttrIgpMetric.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.ATTRLINK_MAX_LEN, org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.ISIS_SMALL_METRIC, org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.ISIS_WIDE_METRIC, org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.OSPF_LINK_METRIC, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.toString ()
Definition at line 167 of file BgpLinkAttrIgpMetric.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 161 of file BgpLinkAttrIgpMetric.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.ATTRLINK_IGPMETRIC = 1095 static
Definition at line 38 of file BgpLinkAttrIgpMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.getType().
final int org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.ATTRLINK_MAX_LEN = 3 static
Definition at line 39 of file BgpLinkAttrIgpMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.read().
final int org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.ISIS_SMALL_METRIC = 1 static
Definition at line 42 of file BgpLinkAttrIgpMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.read().
final int org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.ISIS_WIDE_METRIC = 3 static
Definition at line 44 of file BgpLinkAttrIgpMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.read().
final Logger org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpLinkAttrIgpMetric.class)
Definition at line 35 of file BgpLinkAttrIgpMetric.java.
final int org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.OSPF_LINK_METRIC = 2 static
Definition at line 43 of file BgpLinkAttrIgpMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrIgpMetric.read().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpLinkAttrIgpMetric.java