onos: org.onosproject.net.intent.OpticalConnectivityIntent Class Reference
org.onosproject.net.intent.OpticalConnectivityIntent Class Reference
An optical layer intent for connectivity between two OCh ports.
Classes
class Builder
Builder for optical connectivity intents.
Public Member Functions
ConnectPoint getSrc ()
Returns the source transponder port.
ConnectPoint getDst ()
Returns the destination transponder port.
OduSignalType getSignalType ()
Returns the ODU signal type.
boolean isBidirectional ()
Returns the directionality of the intent.
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.Intent
IntentId id ()
Returns the intent identifier.
ApplicationId appId ()
Returns the identifier of the application that requested the intent.
int priority ()
Returns the priority of the intent.
Collection< NetworkResource > resources ()
Returns the collection of resources required for this intent.
boolean isInstallable ()
Indicates whether or not the intent is installable.
final int hashCode ()
final boolean equals (Object obj)
Key key ()
Static Public Member Functions
static Builder builder ()
Returns a new optical connectivity intent builder.
Static Public Member Functions inherited from org.onosproject.net.intent.Intent
static void bindIdGenerator (IdGenerator newIdGenerator)
Binds an id generator for unique intent id generation.
static void unbindIdGenerator (IdGenerator oldIdGenerator)
Unbinds an id generator.
Protected Member Functions
OpticalConnectivityIntent (ApplicationId appId, Key key, ConnectPoint src, ConnectPoint dst, OduSignalType signalType, boolean isBidirectional, int priority)
Creates an optical connectivity intent between the specified connection points.
OpticalConnectivityIntent ()
Constructor for serializer.
Protected Member Functions inherited from org.onosproject.net.intent.Intent
Intent ()
Constructor for serializer.
Intent (ApplicationId appId, Key key, Collection< NetworkResource > resources, int priority)
Creates a new intent.
Additional Inherited Members
Static Public Attributes inherited from org.onosproject.net.intent.Intent
static final int DEFAULT_INTENT_PRIORITY = 100
static final int MAX_PRIORITY = (1 << 16) - 1
static final int MIN_PRIORITY = 1
Detailed Description
An optical layer intent for connectivity between two OCh ports.
No traffic selector or traffic treatment are needed.
Definition at line 33 of file OpticalConnectivityIntent.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.OpticalConnectivityIntent.OpticalConnectivityIntent (ApplicationId appId, Key key, ConnectPoint src, ConnectPoint dst, OduSignalType signalType, boolean isBidirectional, int priority) protected
Creates an optical connectivity intent between the specified connection points.
Parameters
appId application identification
key intent key
src the source transponder port
dst the destination transponder port
signalType signal type
isBidirectional indicates if intent is unidirectional
priority priority to use for flows from this intent
Definition at line 51 of file OpticalConnectivityIntent.java.
References org.onosproject.net.intent.OpticalConnectivityIntent.isBidirectional(), and org.onosproject.net.intent.Intent.priority().
org.onosproject.net.intent.OpticalConnectivityIntent.OpticalConnectivityIntent () protected
Constructor for serializer.
Definition at line 165 of file OpticalConnectivityIntent.java.
Member Function Documentation
static Builder org.onosproject.net.intent.OpticalConnectivityIntent.builder () static
Returns a new optical connectivity intent builder.
Returns
host to host intent builder
Definition at line 70 of file OpticalConnectivityIntent.java.
ConnectPoint org.onosproject.net.intent.OpticalConnectivityIntent.getDst ()
Returns the destination transponder port.
Returns
source transponder port
Definition at line 187 of file OpticalConnectivityIntent.java.
Referenced by org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.compile(), and org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.compile().
OduSignalType org.onosproject.net.intent.OpticalConnectivityIntent.getSignalType ()
Returns the ODU signal type.
Returns
ODU signal type
Definition at line 196 of file OpticalConnectivityIntent.java.
ConnectPoint org.onosproject.net.intent.OpticalConnectivityIntent.getSrc ()
Returns the source transponder port.
Returns
source transponder port
Definition at line 178 of file OpticalConnectivityIntent.java.
Referenced by org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.compile(), and org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.compile().
boolean org.onosproject.net.intent.OpticalConnectivityIntent.isBidirectional ()
Returns the directionality of the intent.
Returns
true if bidirectional, false if unidirectional
Definition at line 205 of file OpticalConnectivityIntent.java.
Referenced by org.onosproject.net.intent.OpticalConnectivityIntent.OpticalConnectivityIntent(), and org.onosproject.net.intent.OpticalConnectivityIntent.toString().
String org.onosproject.net.intent.OpticalConnectivityIntent.toString ()
Definition at line 210 of file OpticalConnectivityIntent.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.OpticalConnectivityIntent.isBidirectional(), org.onosproject.net.intent.Intent.key(), org.onosproject.net.intent.Intent.priority(), and org.onosproject.net.intent.Intent.resources().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/OpticalConnectivityIntent.java