onos: org.onosproject.net.flow.criteria.ArpPaCriterion Class Reference
org.onosproject.net.flow.criteria.ArpPaCriterion Class Reference
Implementation of arp spa or tpa address criterion.
Public Member Functions
Type type ()
Returns the type of criterion.
Ip4Address ip ()
Gets the Ip4 Address to match.
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Implementation of arp spa or tpa address criterion.
Definition at line 27 of file ArpPaCriterion.java.
Member Function Documentation
boolean org.onosproject.net.flow.criteria.ArpPaCriterion.equals (Object obj)
Definition at line 69 of file ArpPaCriterion.java.
References org.onosproject.net.flow.criteria.ArpPaCriterion.ip().
int org.onosproject.net.flow.criteria.ArpPaCriterion.hashCode ()
Definition at line 64 of file ArpPaCriterion.java.
References org.onosproject.net.flow.criteria.ArpPaCriterion.type().
Ip4Address org.onosproject.net.flow.criteria.ArpPaCriterion.ip ()
Gets the Ip4 Address to match.
Returns
the Ip4 Address to match
Definition at line 53 of file ArpPaCriterion.java.
Referenced by org.onosproject.net.flow.criteria.ArpPaCriterion.equals(), onos.ONOS.start(), org.onosproject.net.flow.criteria.ArpPaCriterion.toString(), and onos.ONOS.updateHazelcast().
String org.onosproject.net.flow.criteria.ArpPaCriterion.toString ()
Definition at line 58 of file ArpPaCriterion.java.
References org.onosproject.net.flow.criteria.ArpPaCriterion.ip(), and org.onosproject.net.flow.criteria.ArpPaCriterion.type().
Type org.onosproject.net.flow.criteria.ArpPaCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 44 of file ArpPaCriterion.java.
Referenced by org.onosproject.net.flow.criteria.ArpPaCriterion.hashCode(), and org.onosproject.net.flow.criteria.ArpPaCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/ArpPaCriterion.java