onos: org.onosproject.segmentrouting.DefaultTunnel Class Reference
org.onosproject.segmentrouting.DefaultTunnel Class Reference
Tunnel class.
Public Member Functions
DefaultTunnel (String tid, List< Integer > labelIds)
Creates a Tunnel reference.
DefaultTunnel (DefaultTunnel tunnel)
Creates a new DefaultTunnel reference using the tunnel reference.
String id ()
Returns the tunnel ID.
List< Integer > labelIds ()
Returns Segment IDs for the tunnel including source and destination.
int groupId ()
Returns the group ID for the tunnel.
void setGroupId (int id)
Sets group ID for the tunnel.
boolean equals (Object o)
int hashCode ()
boolean isAllowedToRemoveGroup ()
Checks if it is allowed to remove the group for the tunnel.
void allowToRemoveGroup (boolean b)
Sets the flag to allow to remove the group or not.
Detailed Description
Tunnel class.
Definition at line 25 of file DefaultTunnel.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.DefaultTunnel.DefaultTunnel (String tid, List< Integer > labelIds)
Creates a Tunnel reference.
Parameters
tid Tunnel ID
labelIds Label stack of the tunnel
Definition at line 39 of file DefaultTunnel.java.
References org.onosproject.segmentrouting.DefaultTunnel.labelIds().
Referenced by org.onosproject.segmentrouting.DefaultTunnel.equals().
org.onosproject.segmentrouting.DefaultTunnel.DefaultTunnel (DefaultTunnel tunnel)
Creates a new DefaultTunnel reference using the tunnel reference.
Parameters
tunnel DefaultTunnel reference
Definition at line 52 of file DefaultTunnel.java.
References find-device.id.
Member Function Documentation
void org.onosproject.segmentrouting.DefaultTunnel.allowToRemoveGroup (boolean ok)
Sets the flag to allow to remove the group or not.
Parameters
ok the flag; true - allow to remove
Implements org.onosproject.segmentrouting.Tunnel.
Definition at line 106 of file DefaultTunnel.java.
boolean org.onosproject.segmentrouting.DefaultTunnel.equals (Object o)
Definition at line 79 of file DefaultTunnel.java.
References org.onosproject.segmentrouting.DefaultTunnel.DefaultTunnel().
int org.onosproject.segmentrouting.DefaultTunnel.groupId ()
Returns the group ID for the tunnel.
Returns
group ID
Implements org.onosproject.segmentrouting.Tunnel.
Definition at line 69 of file DefaultTunnel.java.
int org.onosproject.segmentrouting.DefaultTunnel.hashCode ()
Definition at line 96 of file DefaultTunnel.java.
String org.onosproject.segmentrouting.DefaultTunnel.id ()
Returns the tunnel ID.
Returns
tunnel ID
Implements org.onosproject.segmentrouting.Tunnel.
Definition at line 59 of file DefaultTunnel.java.
References find-device.id.
Referenced by org.onosproject.segmentrouting.DefaultTunnel.setGroupId().
boolean org.onosproject.segmentrouting.DefaultTunnel.isAllowedToRemoveGroup ()
Checks if it is allowed to remove the group for the tunnel.
Returns
true if allowed, false otherwise
Implements org.onosproject.segmentrouting.Tunnel.
Definition at line 101 of file DefaultTunnel.java.
List<Integer> org.onosproject.segmentrouting.DefaultTunnel.labelIds ()
Returns Segment IDs for the tunnel including source and destination.
Returns
List of Node ID
Implements org.onosproject.segmentrouting.Tunnel.
Definition at line 64 of file DefaultTunnel.java.
Referenced by org.onosproject.segmentrouting.DefaultTunnel.DefaultTunnel().
void org.onosproject.segmentrouting.DefaultTunnel.setGroupId (int groupId)
Sets group ID for the tunnel.
Parameters
groupId group identifier
Implements org.onosproject.segmentrouting.Tunnel.
Definition at line 74 of file DefaultTunnel.java.
References org.onosproject.segmentrouting.DefaultTunnel.id().
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/DefaultTunnel.java