onos: org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1 Class Reference
Provides PCEP SRP obejct.
Classes
class Builder
Builder class for PCEP srp Object.
Public Member Functions
PcepSrpObjectVer1 (PcepObjectHeader srpObjHeader, boolean bRFlag, int srpID, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize member variables.
void setSrpObjHeader (PcepObjectHeader obj)
sets the SRP object header.
void setSrpID (int srpID)
Sets SRP ID with specified value.
void setRFlag (boolean bRFlag)
Sets R flag with specified value.
PcepObjectHeader getSrpObjHeader ()
Returns SRP object header.
int getSrpID ()
Returns SRP ID of SRP Object.
boolean getRFlag ()
Returns R flag of SRP Object.
void setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
sets the optional TLvs.
LinkedList< PcepValueType > getOptionalTlv ()
Returns list of optional tlvs.
int write (ChannelBuffer cb) throws PcepParseException
Writes the SRP Object into channel buffer.
String toString ()
Static Public Member Functions
static PcepSrpObject read (ChannelBuffer cb) throws PcepParseException
Reads from channel buffer and returns instance of PCEP SRP object.
static LinkedList< PcepValueType > parseOptionalTlv (ChannelBuffer cb) throws PcepParseException
Parse Optional TLvs from the channel buffer.
Static Public Attributes
static final byte SRP_OBJ_TYPE = 1
static final byte SRP_OBJ_CLASS = 33
static final byte SRP_OBJECT_VERSION = 1
static final short SRP_OBJ_MINIMUM_LENGTH = 12
static final int MINIMUM_COMMON_HEADER_LENGTH = 4
static final boolean DEFAULT_RFLAG = false
static final byte BBIT_SET = 1
static final byte BBIT_RESET = 0
Protected Member Functions
boolean packOptionalTlv (ChannelBuffer cb)
Writes optional tlvs to channel buffer.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepSrpObjectVer1.class)
Detailed Description
Provides PCEP SRP obejct.
Definition at line 36 of file PcepSrpObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.PcepSrpObjectVer1 (PcepObjectHeader srpObjHeader, boolean bRFlag, int srpID, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize member variables.
Parameters
srpObjHeader srp object header
bRFlag R flag
srpID srp Id
llOptionalTlv list of optional tlv
Definition at line 85 of file PcepSrpObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.read().
Member Function Documentation
LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.getOptionalTlv ()
Returns list of optional tlvs.
Returns
llOptionalTlv list of optional tlvs
Implements org.onosproject.pcepio.protocol.PcepSrpObject.
Definition at line 139 of file PcepSrpObjectVer1.java.
boolean org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.getRFlag ()
Returns R flag of SRP Object.
Returns
R flag of SRP Object
Implements org.onosproject.pcepio.protocol.PcepSrpObject.
Definition at line 128 of file PcepSrpObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.getSrpID ()
Returns SRP ID of SRP Object.
Returns
SRP ID of SRP Object
Implements org.onosproject.pcepio.protocol.PcepSrpObject.
Definition at line 123 of file PcepSrpObjectVer1.java.
PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.getSrpObjHeader ()
Returns SRP object header.
Returns
srpObjHeader
Definition at line 118 of file PcepSrpObjectVer1.java.
boolean org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.packOptionalTlv (ChannelBuffer cb) protected
Writes optional tlvs to channel buffer.
Parameters
cb of type channel buffer
Returns
true if writing optional tlv to channel buffer is success.
Definition at line 254 of file PcepSrpObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.write().
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.parseOptionalTlv (ChannelBuffer cb) throws PcepParseException static
Parse Optional TLvs from the channel buffer.
Parameters
cb of type channel buffer
Returns
list of optional tlvs
Exceptions
PcepParseException when unsupported tlv is received in srp object
Definition at line 213 of file PcepSrpObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.MINIMUM_COMMON_HEADER_LENGTH.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.read().
static PcepSrpObject org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.read (ChannelBuffer cb) throws PcepParseException static
Reads from channel buffer and returns instance of PCEP SRP object.
Parameters
cb of channel buffer.
Returns
PCEP SRP object
Exceptions
PcepParseException when srp object is not received in channel buffer
Definition at line 150 of file PcepSrpObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.MINIMUM_COMMON_HEADER_LENGTH, org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.parseOptionalTlv(), org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.PcepSrpObjectVer1(), and org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.SRP_OBJ_CLASS.
void org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
sets the optional TLvs.
Parameters
llOptionalTlv list of optional tlvs
Implements org.onosproject.pcepio.protocol.PcepSrpObject.
Definition at line 133 of file PcepSrpObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.setRFlag (boolean bRFlag)
Sets R flag with specified value.
Parameters
bRFlag R Flag of SRP Object
Implements org.onosproject.pcepio.protocol.PcepSrpObject.
Definition at line 109 of file PcepSrpObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.setSrpID (int srpID)
Sets SRP ID with specified value.
Parameters
srpID SRP ID of SRP Object
Implements org.onosproject.pcepio.protocol.PcepSrpObject.
Definition at line 104 of file PcepSrpObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.setSrpObjHeader (PcepObjectHeader obj)
sets the SRP object header.
Parameters
obj srp object header
Definition at line 99 of file PcepSrpObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.toString ()
Definition at line 385 of file PcepSrpObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the SRP Object into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException when tlv is null
Implements org.onosproject.pcepio.protocol.PcepSrpObject.
Definition at line 178 of file PcepSrpObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.BBIT_RESET, org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.BBIT_SET, and org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.packOptionalTlv().
Member Data Documentation
final byte org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.BBIT_RESET = 0 static
Definition at line 75 of file PcepSrpObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.write().
final byte org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.BBIT_SET = 1 static
Definition at line 74 of file PcepSrpObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.write().
final boolean org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.DEFAULT_RFLAG = false static
Definition at line 62 of file PcepSrpObjectVer1.java.
final Logger org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.log = LoggerFactory.getLogger(PcepSrpObjectVer1.class) static protected
Definition at line 55 of file PcepSrpObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.MINIMUM_COMMON_HEADER_LENGTH = 4 static
Definition at line 61 of file PcepSrpObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.parseOptionalTlv(), and org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.read().
final byte org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.SRP_OBJ_CLASS = 33 static
Definition at line 58 of file PcepSrpObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.read().
final short org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.SRP_OBJ_MINIMUM_LENGTH = 12 static
Definition at line 60 of file PcepSrpObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.SRP_OBJ_TYPE = 1 static
Definition at line 57 of file PcepSrpObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepSrpObjectVer1.SRP_OBJECT_VERSION = 1 static
Definition at line 59 of file PcepSrpObjectVer1.java.
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepSrpObjectVer1.java