onos: org.onosproject.sdnip.PeerConnectivityManagerTest Class Reference
org.onosproject.sdnip.PeerConnectivityManagerTest Class Reference
Unit tests for PeerConnectivityManager.
Public Member Functions
void setUp () throws Exception
void testConnectionSetup ()
Tests whether peer connectivity manager can set up correct BGP and ICMP intents according to specific configuration.
void testNullInterfaces ()
Tests a corner case, when there are no interfaces in the configuration.
void testNullBgpSpeakers ()
Tests a corner case, when there is no BGP speakers in the configuration.
void testNoPeerInterface ()
Tests a corner case, when there is no Interface configured for one BGP peer.
void testNoSpeakerInterface ()
Tests a corner case, when there is no Interface configured for one BGP speaker.
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Additional Inherited Members
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
Unit tests for PeerConnectivityManager.
Definition at line 76 of file PeerConnectivityManagerTest.java.
Member Function Documentation
void org.onosproject.sdnip.PeerConnectivityManagerTest.setUp () throws Exception
Definition at line 120 of file PeerConnectivityManagerTest.java.
void org.onosproject.sdnip.PeerConnectivityManagerTest.testConnectionSetup ()
Tests whether peer connectivity manager can set up correct BGP and ICMP intents according to specific configuration.
Two tricky cases included in the configuration are: 2 peers on a same switch port, peer on the same switch with BGPd.
Definition at line 460 of file PeerConnectivityManagerTest.java.
Referenced by org.onosproject.sdnip.PeerConnectivityManagerTest.testNoPeerInterface(), and org.onosproject.sdnip.PeerConnectivityManagerTest.testNoSpeakerInterface().
void org.onosproject.sdnip.PeerConnectivityManagerTest.testNoPeerInterface ()
Tests a corner case, when there is no Interface configured for one BGP peer.
Definition at line 533 of file PeerConnectivityManagerTest.java.
References org.onosproject.sdnip.PeerConnectivityManagerTest.testConnectionSetup().
void org.onosproject.sdnip.PeerConnectivityManagerTest.testNoSpeakerInterface ()
Tests a corner case, when there is no Interface configured for one BGP speaker.
Definition at line 546 of file PeerConnectivityManagerTest.java.
References org.onosproject.sdnip.PeerConnectivityManagerTest.testConnectionSetup().
void org.onosproject.sdnip.PeerConnectivityManagerTest.testNullBgpSpeakers ()
Tests a corner case, when there is no BGP speakers in the configuration.
Definition at line 513 of file PeerConnectivityManagerTest.java.
References org.onosproject.routing.config.BgpConfig.bgpSpeakers(), and org.onosproject.routing.config.RoutingConfigurationService.getBgpPeers().
void org.onosproject.sdnip.PeerConnectivityManagerTest.testNullInterfaces ()
Tests a corner case, when there are no interfaces in the configuration.
Definition at line 479 of file PeerConnectivityManagerTest.java.
References org.onosproject.incubator.net.intf.InterfaceService.getInterfaces(), org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByIp(), org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByPort(), org.onosproject.incubator.net.intf.InterfaceService.getMatchingInterface(), and org.onlab.packet.IpAddress.valueOf().
The documentation for this class was generated from the following file:
apps/sdnip/src/test/java/org/onosproject/sdnip/PeerConnectivityManagerTest.java