onos: org.onosproject.pcepio.types.LinkNameTlv Class Reference
org.onosproject.pcepio.types.LinkNameTlv Class Reference
Provides the Link Name.
Public Member Functions
LinkNameTlv (byte[] rawValue, short hLength)
Constructor to initialize rawValue.
byte[] getValue ()
Returns value of Link-Name.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static LinkNameTlv of (final byte[] raw, short hLength)
Returns newly created LinkNameTlv object.
static PcepValueType read (ChannelBuffer c, short hLength)
Reads the channel buffer and returns object of LinkNameTlv.
Static Public Attributes
static final short TYPE = 1098
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(LinkNameTlv.class)
Detailed Description
Provides the Link Name.
Definition at line 31 of file LinkNameTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.LinkNameTlv.LinkNameTlv (byte[] rawValue, short hLength)
Constructor to initialize rawValue.
Parameters
rawValue Link-Name
hLength length
Definition at line 57 of file LinkNameTlv.java.
Referenced by org.onosproject.pcepio.types.LinkNameTlv.equals(), org.onosproject.pcepio.types.LinkNameTlv.of(), and org.onosproject.pcepio.types.LinkNameTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.LinkNameTlv.equals (Object obj)
Definition at line 107 of file LinkNameTlv.java.
References org.onosproject.pcepio.types.LinkNameTlv.LinkNameTlv().
short org.onosproject.pcepio.types.LinkNameTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 97 of file LinkNameTlv.java.
short org.onosproject.pcepio.types.LinkNameTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 92 of file LinkNameTlv.java.
References org.onosproject.pcepio.types.LinkNameTlv.TYPE.
byte [] org.onosproject.pcepio.types.LinkNameTlv.getValue ()
Returns value of Link-Name.
Returns
raw value
Definition at line 82 of file LinkNameTlv.java.
PcepVersion org.onosproject.pcepio.types.LinkNameTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 87 of file LinkNameTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.LinkNameTlv.hashCode ()
Definition at line 102 of file LinkNameTlv.java.
static LinkNameTlv org.onosproject.pcepio.types.LinkNameTlv.of (final byte[] raw, short hLength) static
Returns newly created LinkNameTlv object.
Parameters
raw Link-Name
hLength length
Returns
object of LinkNameTlv
Definition at line 73 of file LinkNameTlv.java.
References org.onosproject.pcepio.types.LinkNameTlv.LinkNameTlv().
static PcepValueType org.onosproject.pcepio.types.LinkNameTlv.read (ChannelBuffer c, short hLength) static
Reads the channel buffer and returns object of LinkNameTlv.
Parameters
c input channel buffer
hLength length
Returns
object of LinkNameTlv
Definition at line 134 of file LinkNameTlv.java.
References org.onosproject.pcepio.types.LinkNameTlv.LinkNameTlv().
String org.onosproject.pcepio.types.LinkNameTlv.toString ()
Definition at line 141 of file LinkNameTlv.java.
References org.onosproject.pcepio.types.LinkNameTlv.TYPE.
int org.onosproject.pcepio.types.LinkNameTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 119 of file LinkNameTlv.java.
References org.onosproject.pcepio.types.LinkNameTlv.TYPE.
Member Data Documentation
final Logger org.onosproject.pcepio.types.LinkNameTlv.log = LoggerFactory.getLogger(LinkNameTlv.class) static protected
Definition at line 44 of file LinkNameTlv.java.
final short org.onosproject.pcepio.types.LinkNameTlv.TYPE = 1098 static
Definition at line 46 of file LinkNameTlv.java.
Referenced by org.onosproject.pcepio.types.LinkNameTlv.getType(), org.onosproject.pcepio.types.LinkNameTlv.toString(), and org.onosproject.pcepio.types.LinkNameTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/LinkNameTlv.java