onos: org.onosproject.ui.topo.BiLinkTestBase Class Reference
org.onosproject.ui.topo.BiLinkTestBase Class Reference
Base class for unit tests of BiLink and BiLinkMap.
Classes
class ConcreteLink
class ConcreteLinkMap
class FakeLink
Static Protected Attributes
static final DeviceId DEV_A_ID = DeviceId.deviceId("device-A")
static final DeviceId DEV_B_ID = DeviceId.deviceId("device-B")
static final PortNumber PORT_1 = PortNumber.portNumber(1)
static final PortNumber PORT_2 = PortNumber.portNumber(2)
static final ConnectPoint CP_A1 = new ConnectPoint(DEV_A_ID, PORT_1)
static final ConnectPoint CP_B2 = new ConnectPoint(DEV_B_ID, PORT_2)
static final LinkKey KEY_AB = LinkKey.linkKey(CP_A1, CP_B2)
static final LinkKey KEY_BA = LinkKey.linkKey(CP_B2, CP_A1)
static final Link LINK_AB = new FakeLink(CP_A1, CP_B2)
static final Link LINK_BA = new FakeLink(CP_B2, CP_A1)
Detailed Description
Base class for unit tests of BiLink and BiLinkMap.
Definition at line 30 of file BiLinkTestBase.java.
Member Data Documentation
final ConnectPoint org.onosproject.ui.topo.BiLinkTestBase.CP_A1 = new ConnectPoint(DEV_A_ID, PORT_1) static protected
Definition at line 70 of file BiLinkTestBase.java.
final ConnectPoint org.onosproject.ui.topo.BiLinkTestBase.CP_B2 = new ConnectPoint(DEV_B_ID, PORT_2) static protected
Definition at line 71 of file BiLinkTestBase.java.
final DeviceId org.onosproject.ui.topo.BiLinkTestBase.DEV_A_ID = DeviceId.deviceId("device-A") static protected
Definition at line 65 of file BiLinkTestBase.java.
final DeviceId org.onosproject.ui.topo.BiLinkTestBase.DEV_B_ID = DeviceId.deviceId("device-B") static protected
Definition at line 66 of file BiLinkTestBase.java.
final LinkKey org.onosproject.ui.topo.BiLinkTestBase.KEY_AB = LinkKey.linkKey(CP_A1, CP_B2) static protected
Definition at line 73 of file BiLinkTestBase.java.
Referenced by org.onosproject.ui.topo.BiLinkTest.basic(), org.onosproject.ui.topo.BiLinkTest.nullLink(), and org.onosproject.ui.topo.BiLinkTest.nullOther().
final LinkKey org.onosproject.ui.topo.BiLinkTestBase.KEY_BA = LinkKey.linkKey(CP_B2, CP_A1) static protected
Definition at line 74 of file BiLinkTestBase.java.
final Link org.onosproject.ui.topo.BiLinkTestBase.LINK_AB = new FakeLink(CP_A1, CP_B2) static protected
Definition at line 76 of file BiLinkTestBase.java.
Referenced by org.onosproject.ui.topo.BiLinkMapTest.addPairOfLinks(), org.onosproject.ui.topo.BiLinkMapTest.addSameLinkTwice(), org.onosproject.ui.topo.BiLinkTest.basic(), org.onosproject.ui.topo.BiLinkTest.nullKey(), and org.onosproject.ui.topo.BiLinkTest.nullOther().
final Link org.onosproject.ui.topo.BiLinkTestBase.LINK_BA = new FakeLink(CP_B2, CP_A1) static protected
Definition at line 77 of file BiLinkTestBase.java.
Referenced by org.onosproject.ui.topo.BiLinkMapTest.addPairOfLinks(), and org.onosproject.ui.topo.BiLinkTest.basic().
final PortNumber org.onosproject.ui.topo.BiLinkTestBase.PORT_1 = PortNumber.portNumber(1) static protected
Definition at line 67 of file BiLinkTestBase.java.
final PortNumber org.onosproject.ui.topo.BiLinkTestBase.PORT_2 = PortNumber.portNumber(2) static protected
Definition at line 68 of file BiLinkTestBase.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/ui/topo/BiLinkTestBase.java