onos: org.onosproject.net.config.impl.NetworkConfigManagerTest Class Reference
org.onosproject.net.config.impl.NetworkConfigManagerTest Class Reference
Unit tests for network config registry.
Classes
class BasicConfig1
Config classes for testing.
class BasicConfig2
class MockConfigFactory1
Config factory classes for testing.
class MockConfigFactory2
class MockSubjectFactory
Public Member Functions
void setUp () throws Exception
void tearDown ()
void testRegistry ()
void configIdEquals ()
void configKeyEquals ()
void testAddConfig ()
Tests creation, query and removal of a factory.
void testApplyConfig ()
Tests creation, query and removal of a factory.
Detailed Description
Unit tests for network config registry.
Definition at line 47 of file NetworkConfigManagerTest.java.
Member Function Documentation
void org.onosproject.net.config.impl.NetworkConfigManagerTest.configIdEquals ()
Definition at line 148 of file NetworkConfigManagerTest.java.
void org.onosproject.net.config.impl.NetworkConfigManagerTest.configKeyEquals ()
Definition at line 165 of file NetworkConfigManagerTest.java.
void org.onosproject.net.config.impl.NetworkConfigManagerTest.setUp () throws Exception
Definition at line 107 of file NetworkConfigManagerTest.java.
void org.onosproject.net.config.impl.NetworkConfigManagerTest.tearDown ()
Definition at line 120 of file NetworkConfigManagerTest.java.
void org.onosproject.net.config.impl.NetworkConfigManagerTest.testAddConfig ()
Tests creation, query and removal of a factory.
Definition at line 185 of file NetworkConfigManagerTest.java.
References org.onosproject.net.config.NetworkConfigService.getSubjectFactory().
void org.onosproject.net.config.impl.NetworkConfigManagerTest.testApplyConfig ()
Tests creation, query and removal of a factory.
Definition at line 227 of file NetworkConfigManagerTest.java.
References org.onosproject.net.config.NetworkConfigService.getSubjectFactory().
void org.onosproject.net.config.impl.NetworkConfigManagerTest.testRegistry ()
Definition at line 126 of file NetworkConfigManagerTest.java.
References org.onosproject.net.config.NetworkConfigRegistry.getConfigFactories(), and org.onosproject.net.config.NetworkConfigRegistry.getConfigFactory().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/config/impl/NetworkConfigManagerTest.java