onos: org.onosproject.net.intent.OpticalPathIntent Class Reference
org.onosproject.net.intent.OpticalPathIntent Class Reference
An optical layer intent with explicitly selected path.
Classes
class Builder
Builder for optical path intents.
Public Member Functions
ConnectPoint src ()
ConnectPoint dst ()
Path path ()
OchSignal lambda ()
OchSignalType signalType ()
boolean isBidirectional ()
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.Intent
IntentId id ()
Returns the intent identifier.
ApplicationId appId ()
Returns the identifier of the application that requested the intent.
int priority ()
Returns the priority of the intent.
Collection< NetworkResource > resources ()
Returns the collection of resources required for this intent.
boolean isInstallable ()
Indicates whether or not the intent is installable.
final int hashCode ()
final boolean equals (Object obj)
Key key ()
Static Public Member Functions
static Builder builder ()
Returns a new optical connectivity intent builder.
Static Public Member Functions inherited from org.onosproject.net.intent.Intent
static void bindIdGenerator (IdGenerator newIdGenerator)
Binds an id generator for unique intent id generation.
static void unbindIdGenerator (IdGenerator oldIdGenerator)
Unbinds an id generator.
Protected Member Functions
OpticalPathIntent ()
Protected Member Functions inherited from org.onosproject.net.intent.Intent
Intent ()
Constructor for serializer.
Intent (ApplicationId appId, Key key, Collection< NetworkResource > resources, int priority)
Creates a new intent.
Additional Inherited Members
Static Public Attributes inherited from org.onosproject.net.intent.Intent
static final int DEFAULT_INTENT_PRIORITY = 100
static final int MAX_PRIORITY = (1 << 16) - 1
static final int MIN_PRIORITY = 1
Detailed Description
An optical layer intent with explicitly selected path.
Definition at line 34 of file OpticalPathIntent.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.OpticalPathIntent.OpticalPathIntent () protected
Definition at line 61 of file OpticalPathIntent.java.
Member Function Documentation
static Builder org.onosproject.net.intent.OpticalPathIntent.builder () static
Returns a new optical connectivity intent builder.
Returns
host to host intent builder
Definition at line 75 of file OpticalPathIntent.java.
ConnectPoint org.onosproject.net.intent.OpticalPathIntent.dst ()
Definition at line 199 of file OpticalPathIntent.java.
Referenced by org.onosproject.net.intent.OpticalPathIntent.toString().
boolean org.onosproject.net.intent.OpticalPathIntent.isBidirectional ()
Definition at line 215 of file OpticalPathIntent.java.
Referenced by org.onosproject.net.intent.OpticalPathIntent.toString().
OchSignal org.onosproject.net.intent.OpticalPathIntent.lambda ()
Definition at line 207 of file OpticalPathIntent.java.
Referenced by org.onosproject.net.intent.OpticalPathIntent.toString().
Path org.onosproject.net.intent.OpticalPathIntent.path ()
Definition at line 203 of file OpticalPathIntent.java.
OchSignalType org.onosproject.net.intent.OpticalPathIntent.signalType ()
Definition at line 211 of file OpticalPathIntent.java.
ConnectPoint org.onosproject.net.intent.OpticalPathIntent.src ()
Definition at line 195 of file OpticalPathIntent.java.
String org.onosproject.net.intent.OpticalPathIntent.toString ()
Definition at line 220 of file OpticalPathIntent.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.OpticalPathIntent.dst(), org.onosproject.net.intent.OpticalPathIntent.isBidirectional(), org.onosproject.net.intent.Intent.key(), org.onosproject.net.intent.OpticalPathIntent.lambda(), and org.onosproject.net.intent.Intent.resources().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/OpticalPathIntent.java