onos: org.onosproject.net.DefaultLink Class Reference
org.onosproject.net.DefaultLink Class Reference
Default infrastructure link model implementation.
Public Member Functions
DefaultLink (ProviderId providerId, ConnectPoint src, ConnectPoint dst, Type type, Annotations...annotations)
Creates an active infrastructure link using the supplied information.
DefaultLink (ProviderId providerId, ConnectPoint src, ConnectPoint dst, Type type, State state, boolean isDurable, Annotations...annotations)
Creates an infrastructure link using the supplied information.
ConnectPoint src ()
Returns the link source connection point.
ConnectPoint dst ()
Returns the link destination connection point.
Type type ()
Returns the link type.
State state ()
Returns the link state.
boolean isDurable ()
Indicates if the link is to be considered durable.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel ()
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel (ProviderId providerId, Annotations...annotations)
Creates a model entity attributed to the specified provider and optionally annotated.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default infrastructure link model implementation.
Definition at line 28 of file DefaultLink.java.
Constructor & Destructor Documentation
org.onosproject.net.DefaultLink.DefaultLink (ProviderId providerId, ConnectPoint src, ConnectPoint dst, Type type, Annotations... annotations)
Creates an active infrastructure link using the supplied information.
Parameters
providerId provider identity
src link source
dst link destination
type link type
annotations optional key/value annotations
Definition at line 45 of file DefaultLink.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultLink.dst(), org.onosproject.net.AbstractModel.providerId(), org.onosproject.net.DefaultLink.src(), and org.onosproject.net.DefaultLink.type().
Referenced by org.onosproject.net.DefaultLink.equals().
org.onosproject.net.DefaultLink.DefaultLink (ProviderId providerId, ConnectPoint src, ConnectPoint dst, Type type, State state, boolean isDurable, Annotations... annotations)
Creates an infrastructure link using the supplied information.
Links marked as durable will remain in the inventory when a vanish message is received and instead will be marked as inactive.
Parameters
providerId provider identity
src link source
dst link destination
type link type
state link state
isDurable indicates if the link is to be considered durable
annotations optional key/value annotations
Definition at line 63 of file DefaultLink.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultLink.dst(), org.onosproject.net.DefaultLink.isDurable(), org.onosproject.net.DefaultLink.src(), org.onosproject.net.DefaultLink.state(), and org.onosproject.net.DefaultLink.type().
Member Function Documentation
ConnectPoint org.onosproject.net.DefaultLink.dst ()
Returns the link destination connection point.
Returns
link destination connection point
Implements org.onosproject.net.Link.
Definition at line 80 of file DefaultLink.java.
Referenced by org.onosproject.net.DefaultLink.DefaultLink(), org.onosproject.net.DefaultDisjointPath.hashCode(), org.onosproject.net.DefaultLink.hashCode(), org.onosproject.net.DefaultPath.toString(), and org.onosproject.net.DefaultLink.toString().
boolean org.onosproject.net.DefaultLink.equals (Object obj)
Definition at line 107 of file DefaultLink.java.
References org.onosproject.net.DefaultLink.DefaultLink().
int org.onosproject.net.DefaultLink.hashCode ()
Definition at line 102 of file DefaultLink.java.
References org.onosproject.net.DefaultLink.dst(), org.onosproject.net.DefaultLink.src(), and org.onosproject.net.DefaultLink.type().
boolean org.onosproject.net.DefaultLink.isDurable ()
Indicates if the link is to be considered durable.
Returns
true if the link is durable
Implements org.onosproject.net.Link.
Definition at line 95 of file DefaultLink.java.
Referenced by org.onosproject.net.DefaultLink.DefaultLink(), org.onosproject.net.DefaultPath.toString(), and org.onosproject.net.DefaultLink.toString().
ConnectPoint org.onosproject.net.DefaultLink.src ()
Returns the link source connection point.
Returns
link source connection point
Implements org.onosproject.net.Link.
Definition at line 75 of file DefaultLink.java.
Referenced by org.onosproject.net.DefaultLink.DefaultLink(), org.onosproject.net.DefaultDisjointPath.hashCode(), org.onosproject.net.DefaultLink.hashCode(), org.onosproject.net.DefaultPath.toString(), and org.onosproject.net.DefaultLink.toString().
State org.onosproject.net.DefaultLink.state ()
Returns the link state.
Returns
link state
Implements org.onosproject.net.Link.
Definition at line 90 of file DefaultLink.java.
Referenced by org.onosproject.net.DefaultLink.DefaultLink(), org.onosproject.net.DefaultPath.toString(), and org.onosproject.net.DefaultLink.toString().
String org.onosproject.net.DefaultLink.toString ()
Definition at line 121 of file DefaultLink.java.
References org.onosproject.net.DefaultLink.dst(), org.onosproject.net.DefaultLink.isDurable(), org.onosproject.net.DefaultLink.src(), org.onosproject.net.DefaultLink.state(), and org.onosproject.net.DefaultLink.type().
Type org.onosproject.net.DefaultLink.type ()
Returns the link type.
Returns
link type
Implements org.onosproject.net.Link.
Definition at line 85 of file DefaultLink.java.
Referenced by org.onosproject.net.DefaultLink.DefaultLink(), org.onosproject.net.DefaultLink.hashCode(), org.onosproject.net.DefaultPath.toString(), and org.onosproject.net.DefaultLink.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/DefaultLink.java