onos: org.onlab.junit.TestTools Class Reference
org.onlab.junit.TestTools Class Reference
Utilities to aid in producing JUnit tests.
Static Public Member Functions
static void print (String msg)
static void delay (int ms)
Suspends the current thread for a specified number of millis.
static long now ()
Returns the current time in millis since epoch.
static void assertAfter (int delay, int duration, Runnable assertions)
Runs the specified runnable until it completes successfully or until the specified time expires.
static void assertAfter (int duration, Runnable assertions)
Runs the specified runnable until it completes successfully or until the specified time expires.
static List< File > createTestFiles (List< String > paths) throws IOException
Creates a directory tree of test files.
static List< File > createTestFiles (List< String > paths, int minSize, int maxSize) throws IOException
Creates a directory tree of test files.
static void writeRandomFile (File file, int minSize, int maxSize) throws IOException
Writes random binary content into the specified file.
static void tweakBytes (Random random, byte[] data, int count)
Tweaks the given number of bytes in a byte array.
static void tweakBytes (Random random, byte[] data, int count, int start, int end)
Tweaks the given number of bytes in the specified range of a byte array.
static int findAvailablePort (int defaultPort)
Detailed Description
Utilities to aid in producing JUnit tests.
Definition at line 33 of file TestTools.java.
Member Function Documentation
static void org.onlab.junit.TestTools.assertAfter (int delay, int duration, Runnable assertions) static
Runs the specified runnable until it completes successfully or until the specified time expires.
If the latter occurs, the first encountered assertion on the last attempt will be re-thrown. Errors other than assertion errors will be propagated immediately.
Assertions attempts will not be closer than 10 millis apart and no further than 50 millis.
Parameters
delay number of millis to delay before the first attempt
duration number of milliseconds beyond the current time
assertions test assertions runnable
Definition at line 81 of file TestTools.java.
static void org.onlab.junit.TestTools.assertAfter (int duration, Runnable assertions) static
Runs the specified runnable until it completes successfully or until the specified time expires.
If the latter occurs, the first encountered assertion on the last attempt will be re-thrown. Errors other than assertion errors will be propagated immediately.
Assertions attempts will not be closer than 10 millis apart and no further than 50 millis.
Parameters
duration number of milliseconds beyond the current time
assertions test assertions runnable
Definition at line 119 of file TestTools.java.
static List<File> org.onlab.junit.TestTools.createTestFiles (List< String > paths) throws IOException static
Creates a directory tree of test files.
To signify creating a directory file path should end with '/'.
Parameters
paths list of file paths
Returns
list of created files
Exceptions
java.io.IOException if there is an issue
Definition at line 132 of file TestTools.java.
static List<File> org.onlab.junit.TestTools.createTestFiles (List< String > paths, int minSize, int maxSize) throws IOException static
Creates a directory tree of test files.
To signify creating a directory file path should end with '/'.
Parameters
paths list of file paths
minSize minimum file size in bytes
maxSize maximum file size in bytes
Returns
list of created files
Exceptions
java.io.IOException if there is an issue
Definition at line 146 of file TestTools.java.
static void org.onlab.junit.TestTools.delay (int ms) static
Suspends the current thread for a specified number of millis.
Parameters
ms number of millis
Definition at line 50 of file TestTools.java.
static int org.onlab.junit.TestTools.findAvailablePort (int defaultPort) static
Definition at line 214 of file TestTools.java.
static long org.onlab.junit.TestTools.now () static
Returns the current time in millis since epoch.
Returns
current time
Definition at line 63 of file TestTools.java.
static void org.onlab.junit.TestTools.print (String msg) static
Definition at line 41 of file TestTools.java.
Referenced by org.onlab.util.GroupedThreadFactoryTest.basics(), org.onlab.util.ToolsTest.groupedThreads(), and org.onlab.util.ToolsTest.namedThreads().
static void org.onlab.junit.TestTools.tweakBytes (Random random, byte[] data, int count) static
Tweaks the given number of bytes in a byte array.
Parameters
random random number generator
data byte array to be tweaked
count number of bytes to tweak
Definition at line 190 of file TestTools.java.
static void org.onlab.junit.TestTools.tweakBytes (Random random, byte[] data, int count, int start, int end) static
Tweaks the given number of bytes in the specified range of a byte array.
Parameters
random random number generator
data byte array to be tweaked
count number of bytes to tweak
start index at beginning of range (inclusive)
end index at end of range (exclusive)
Definition at line 203 of file TestTools.java.
static void org.onlab.junit.TestTools.writeRandomFile (File file, int minSize, int maxSize) throws IOException static
Writes random binary content into the specified file.
The number of bytes will be random between the given minimum and maximum.
Parameters
file file to write data to
minSize minimum number of bytes to write
maxSize maximum number of bytes to write
Exceptions
IOException if there is an issue
Definition at line 175 of file TestTools.java.
The documentation for this class was generated from the following file:
utils/junit/src/main/java/org/onlab/junit/TestTools.java