onos: org.onlab.util.Bandwidth Class Reference
org.onlab.util.Bandwidth Class Reference
Representation of bandwidth.
Public Member Functions
double bps ()
Returns bandwidth in bps.
Bandwidth add (Bandwidth value)
Returns a Bandwidth whose value is (this + value).
Bandwidth subtract (Bandwidth value)
Returns a Bandwidth whose value is (this - value).
int compareTo (Bandwidth other)
boolean equals (Object obj)
int hashCode ()
String toString ()
Static Public Member Functions
static Bandwidth of (double v, DataRateUnit unit)
Creates a new instance with given bandwidth.
static Bandwidth bps (double bps)
Creates a new instance with given bandwidth in bps.
static Bandwidth kbps (double kbps)
Creates a new instance with given bandwidth in Kbps.
static Bandwidth mbps (double mbps)
Creates a new instance with given bandwidth in Mbps.
static Bandwidth gbps (double gbps)
Creates a new instance with given bandwidth in Gbps.
Detailed Description
Representation of bandwidth.
Use the static factory method corresponding to the unit (like Kbps) you desire on instantiation.
Definition at line 26 of file Bandwidth.java.
Member Function Documentation
Bandwidth org.onlab.util.Bandwidth.add (Bandwidth value)
Returns a Bandwidth whose value is (this + value).
Parameters
value value to be added to this Frequency
Returns
this + value
Definition at line 110 of file Bandwidth.java.
References org.onlab.util.Bandwidth.bps().
Referenced by org.onlab.util.BandwidthTest.testAdd().
static Bandwidth org.onlab.util.Bandwidth.bps (double bps) static
Creates a new instance with given bandwidth in bps.
Parameters
bps bandwidth value to be assigned
Returns
Bandwidth instance with given bandwidth
Definition at line 61 of file Bandwidth.java.
double org.onlab.util.Bandwidth.bps ()
Returns bandwidth in bps.
Returns
bandwidth in bps.
Definition at line 100 of file Bandwidth.java.
Referenced by org.onlab.util.Bandwidth.add(), org.onlab.util.Bandwidth.gbps(), org.onlab.util.Bandwidth.hashCode(), org.onlab.util.Bandwidth.kbps(), org.onlab.util.Bandwidth.mbps(), and org.onlab.util.Bandwidth.subtract().
int org.onlab.util.Bandwidth.compareTo (Bandwidth other)
Definition at line 125 of file Bandwidth.java.
boolean org.onlab.util.Bandwidth.equals (Object obj)
Definition at line 132 of file Bandwidth.java.
static Bandwidth org.onlab.util.Bandwidth.gbps (double gbps) static
Creates a new instance with given bandwidth in Gbps.
Parameters
gbps bandwidth value to be assigned
Returns
Bandwidth instance with given bandwidth
Definition at line 91 of file Bandwidth.java.
References org.onlab.util.Bandwidth.bps().
Referenced by org.onlab.util.BandwidthTest.testEquality().
int org.onlab.util.Bandwidth.hashCode ()
Definition at line 141 of file Bandwidth.java.
References org.onlab.util.Bandwidth.bps().
static Bandwidth org.onlab.util.Bandwidth.kbps (double kbps) static
Creates a new instance with given bandwidth in Kbps.
Parameters
kbps bandwidth value to be assigned
Returns
Bandwidth instance with given bandwidth
Definition at line 71 of file Bandwidth.java.
References org.onlab.util.Bandwidth.bps().
static Bandwidth org.onlab.util.Bandwidth.mbps (double mbps) static
Creates a new instance with given bandwidth in Mbps.
Parameters
mbps bandwidth value to be assigned
Returns
Bandwidth instance with given bandwidth
Definition at line 81 of file Bandwidth.java.
References org.onlab.util.Bandwidth.bps().
Referenced by org.onosproject.store.serializers.KryoSerializerTest.testBandwidth(), and org.onosproject.store.trivial.SimpleLinkResourceStoreTest.testInitialBandwidth().
static Bandwidth org.onlab.util.Bandwidth.of (double v, DataRateUnit unit) static
Creates a new instance with given bandwidth.
Parameters
v bandwidth value
unit DataRateUnit of
v
Returns
Bandwidth instance with given bandwidth
Definition at line 51 of file Bandwidth.java.
References org.onlab.util.DataRateUnit.toBitsPerSecond().
Referenced by org.onosproject.net.resource.link.BandwidthResource.of(), and org.onosproject.net.intent.constraint.BandwidthConstraint.of().
Bandwidth org.onlab.util.Bandwidth.subtract (Bandwidth value)
Returns a Bandwidth whose value is (this - value).
Parameters
value value to be added to this Frequency
Returns
this - value
Definition at line 120 of file Bandwidth.java.
References org.onlab.util.Bandwidth.bps().
Referenced by org.onlab.util.BandwidthTest.testSubtract().
String org.onlab.util.Bandwidth.toString ()
Definition at line 146 of file Bandwidth.java.
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/util/Bandwidth.java