onos: org.onosproject.cordvtn.CordVtnNode Class Reference
org.onosproject.cordvtn.CordVtnNode Class Reference
Representation of a compute infrastructure node for CORD VTN service.
Public Member Functions
CordVtnNode (String hostname, IpAddress ovsdbIp, TpPort ovsdbPort, DeviceId bridgeId)
Creates a new node.
IpAddress ovsdbIp ()
Returns the OVSDB server IP address.
TpPort ovsdbPort ()
Returns the OVSDB server port number.
String hostname ()
Returns the hostname.
DeviceId intBrId ()
Returns the identifier of the integration bridge.
DeviceId ovsdbId ()
Returns the identifier of the OVSDB device.
boolean equals (Object obj)
int hashCode ()
String toString ()
Static Public Attributes
static final Comparator
< CordVtnNode > CORDVTN_NODE_COMPARATOR
Detailed Description
Representation of a compute infrastructure node for CORD VTN service.
Definition at line 31 of file CordVtnNode.java.
Constructor & Destructor Documentation
org.onosproject.cordvtn.CordVtnNode.CordVtnNode (String hostname, IpAddress ovsdbIp, TpPort ovsdbPort, DeviceId bridgeId)
Creates a new node.
Parameters
hostname hostname
ovsdbIp OVSDB server IP address
ovsdbPort OVSDB server port number
bridgeId integration bridge identifier
Definition at line 49 of file CordVtnNode.java.
Referenced by org.onosproject.cordvtn.CordVtnNode.equals().
Member Function Documentation
boolean org.onosproject.cordvtn.CordVtnNode.equals (Object obj)
Definition at line 102 of file CordVtnNode.java.
References org.onosproject.cordvtn.CordVtnNode.CordVtnNode(), org.onosproject.cordvtn.CordVtnNode.hostname(), org.onosproject.cordvtn.CordVtnNode.ovsdbIp(), and org.onosproject.cordvtn.CordVtnNode.ovsdbPort().
int org.onosproject.cordvtn.CordVtnNode.hashCode ()
Definition at line 120 of file CordVtnNode.java.
References org.onosproject.cordvtn.CordVtnNode.hostname(), org.onosproject.cordvtn.CordVtnNode.ovsdbIp(), and org.onosproject.cordvtn.CordVtnNode.ovsdbPort().
String org.onosproject.cordvtn.CordVtnNode.hostname ()
Returns the hostname.
Returns
hostname
Definition at line 79 of file CordVtnNode.java.
Referenced by org.onosproject.cordvtn.CordVtnNode.equals(), org.onosproject.cordvtn.CordVtnNode.hashCode(), and org.onosproject.cordvtn.CordVtnNode.toString().
DeviceId org.onosproject.cordvtn.CordVtnNode.intBrId ()
Returns the identifier of the integration bridge.
Returns
device id
Definition at line 88 of file CordVtnNode.java.
DeviceId org.onosproject.cordvtn.CordVtnNode.ovsdbId ()
Returns the identifier of the OVSDB device.
Returns
device id
Definition at line 97 of file CordVtnNode.java.
IpAddress org.onosproject.cordvtn.CordVtnNode.ovsdbIp ()
Returns the OVSDB server IP address.
Returns
ip address
Definition at line 61 of file CordVtnNode.java.
Referenced by org.onosproject.cordvtn.CordVtnNode.equals(), org.onosproject.cordvtn.CordVtnNode.hashCode(), and org.onosproject.cordvtn.CordVtnNode.toString().
TpPort org.onosproject.cordvtn.CordVtnNode.ovsdbPort ()
Returns the OVSDB server port number.
Returns
port number
Definition at line 70 of file CordVtnNode.java.
Referenced by org.onosproject.cordvtn.CordVtnNode.equals(), org.onosproject.cordvtn.CordVtnNode.hashCode(), and org.onosproject.cordvtn.CordVtnNode.toString().
String org.onosproject.cordvtn.CordVtnNode.toString ()
Definition at line 125 of file CordVtnNode.java.
References org.onosproject.cordvtn.CordVtnNode.hostname(), org.onosproject.cordvtn.CordVtnNode.ovsdbIp(), and org.onosproject.cordvtn.CordVtnNode.ovsdbPort().
Member Data Documentation
final Comparator<CordVtnNode> org.onosproject.cordvtn.CordVtnNode.CORDVTN_NODE_COMPARATOR static
Initial value:
=
            (node1, node2) -> node1.hostname().compareTo(node2.hostname())
Definition at line 38 of file CordVtnNode.java.
Referenced by org.onosproject.cordvtn.cli.CordVtnNodeListCommand.execute().
The documentation for this class was generated from the following file:
apps/cordvtn/src/main/java/org/onosproject/cordvtn/CordVtnNode.java