onos: org.onosproject.net.intent.Intent Class Reference
org.onosproject.net.intent.Intent Class Reference
Abstraction of an application level intent.
Classes
class Builder
Abstract builder for intents.
Public Member Functions
IntentId id ()
Returns the intent identifier.
ApplicationId appId ()
Returns the identifier of the application that requested the intent.
int priority ()
Returns the priority of the intent.
Collection< NetworkResource > resources ()
Returns the collection of resources required for this intent.
boolean isInstallable ()
Indicates whether or not the intent is installable.
final int hashCode ()
final boolean equals (Object obj)
Key key ()
Static Public Member Functions
static void bindIdGenerator (IdGenerator newIdGenerator)
Binds an id generator for unique intent id generation.
static void unbindIdGenerator (IdGenerator oldIdGenerator)
Unbinds an id generator.
Static Public Attributes
static final int DEFAULT_INTENT_PRIORITY = 100
static final int MAX_PRIORITY = (1 << 16) - 1
static final int MIN_PRIORITY = 1
Protected Member Functions
Intent ()
Constructor for serializer.
Intent (ApplicationId appId, Key key, Collection< NetworkResource > resources, int priority)
Creates a new intent.
Detailed Description
Abstraction of an application level intent.
Make sure that an Intent should be immutable when a new type is defined.
Definition at line 37 of file Intent.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.Intent.Intent () protected
Constructor for serializer.
Definition at line 56 of file Intent.java.
References org.onosproject.net.intent.Intent.DEFAULT_INTENT_PRIORITY.
Referenced by org.onosproject.net.intent.Intent.equals().
org.onosproject.net.intent.Intent.Intent (ApplicationId appId, Key key, Collection< NetworkResource > resources, int priority) protected
Creates a new intent.
Parameters
appId application identifier
key optional key
resources required network resources (optional)
priority flow rule priority
Definition at line 72 of file Intent.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.Intent.MIN_PRIORITY, org.onosproject.net.intent.Key.of(), and org.onosproject.net.intent.Intent.priority().
Member Function Documentation
ApplicationId org.onosproject.net.intent.Intent.appId ()
Returns the identifier of the application that requested the intent.
Returns
application identifier
Definition at line 142 of file Intent.java.
Referenced by org.onosproject.net.intent.MultiPointToSinglePointIntentTest.basics(), org.onosproject.net.intent.PointToPointIntentTest.basics(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.basics(), org.onosproject.net.intent.PathIntentTest.basics(), org.onosproject.net.intent.impl.compiler.TwoWayP2PIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.compile(), org.onosproject.net.intent.FlowRuleIntent.FlowRuleIntent(), org.onosproject.net.intent.Intent.Intent(), org.onosproject.net.intent.OpticalPathIntentTest.testContents(), org.onosproject.net.intent.TwoWayP2PIntentTest.testContents(), org.onosproject.net.intent.MplsPathIntentTest.testContents(), org.onosproject.net.intent.MplsIntentTest.testContents(), org.onosproject.net.intent.FlowRuleIntent.toString(), org.onosproject.net.intent.TwoWayP2PIntent.toString(), org.onosproject.net.intent.PathIntent.toString(), org.onosproject.net.intent.HostToHostIntent.toString(), org.onosproject.net.intent.PointToPointIntent.toString(), org.onosproject.net.intent.SinglePointToMultiPointIntent.toString(), org.onosproject.net.intent.OpticalCircuitIntent.toString(), org.onosproject.net.intent.MultiPointToSinglePointIntent.toString(), org.onosproject.net.intent.OpticalConnectivityIntent.toString(), org.onosproject.net.intent.OpticalPathIntent.toString(), org.onosproject.net.intent.LinkCollectionIntent.toString(), and org.onosproject.net.intent.MplsIntent.toString().
static void org.onosproject.net.intent.Intent.bindIdGenerator (IdGenerator newIdGenerator) static
Binds an id generator for unique intent id generation.
Note: A generator cannot be bound if there is already a generator bound.
Parameters
newIdGenerator id generator
Definition at line 197 of file Intent.java.
final boolean org.onosproject.net.intent.Intent.equals (Object obj)
Definition at line 179 of file Intent.java.
References org.onosproject.net.intent.Intent.Intent().
Referenced by org.onosproject.sdnip.IntentUtils.equals(), org.onosproject.net.intent.PathIntent.validate(), and org.onosproject.net.intent.IntentServiceTest.validateEvents().
final int org.onosproject.net.intent.Intent.hashCode ()
Definition at line 174 of file Intent.java.
IntentId org.onosproject.net.intent.Intent.id ()
Returns the intent identifier.
Returns
intent fingerprint
Definition at line 133 of file Intent.java.
Referenced by org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.compile().
boolean org.onosproject.net.intent.Intent.isInstallable ()
Indicates whether or not the intent is installable.
Returns
true if installable
Definition at line 169 of file Intent.java.
Referenced by org.onosproject.net.intent.LinkCollectionIntentTest.testSerializerConstructor().
Key org.onosproject.net.intent.Intent.key ()
Definition at line 215 of file Intent.java.
Referenced by org.onosproject.net.intent.PathIntentTest.basics(), org.onosproject.net.intent.impl.compiler.TwoWayP2PIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler.compile(), org.onosproject.net.intent.MplsPathIntentTest.testContents(), org.onosproject.sdnip.IntentSyncTest.testIntentSync(), org.onosproject.net.intent.FlowRuleIntent.toString(), org.onosproject.net.intent.TwoWayP2PIntent.toString(), org.onosproject.net.intent.PathIntent.toString(), org.onosproject.net.intent.HostToHostIntent.toString(), org.onosproject.net.intent.PointToPointIntent.toString(), org.onosproject.net.intent.SinglePointToMultiPointIntent.toString(), org.onosproject.net.intent.OpticalCircuitIntent.toString(), org.onosproject.net.intent.MultiPointToSinglePointIntent.toString(), org.onosproject.net.intent.OpticalConnectivityIntent.toString(), org.onosproject.net.intent.OpticalPathIntent.toString(), org.onosproject.net.intent.LinkCollectionIntent.toString(), and org.onosproject.net.intent.MplsIntent.toString().
int org.onosproject.net.intent.Intent.priority ()
Returns the priority of the intent.
Returns
intent priority
Definition at line 151 of file Intent.java.
Referenced by org.onosproject.net.intent.impl.compiler.TwoWayP2PIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.PathIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.compile(), org.onosproject.codec.impl.IntentCodecTest.decodeHostToHostIntent(), org.onosproject.codec.impl.IntentCodecTest.decodePointToPointIntent(), org.onosproject.net.intent.Intent.Intent(), org.onosproject.net.intent.OpticalCircuitIntent.OpticalCircuitIntent(), org.onosproject.net.intent.OpticalConnectivityIntent.OpticalConnectivityIntent(), org.onosproject.net.intent.OpticalPathIntentTest.testContents(), org.onosproject.net.intent.TwoWayP2PIntentTest.testContents(), org.onosproject.net.intent.MplsPathIntentTest.testContents(), org.onosproject.net.intent.MplsIntentTest.testContents(), org.onosproject.net.intent.TwoWayP2PIntent.toString(), org.onosproject.net.intent.PathIntent.toString(), org.onosproject.net.intent.HostToHostIntent.toString(), org.onosproject.net.intent.PointToPointIntent.toString(), org.onosproject.net.intent.SinglePointToMultiPointIntent.toString(), org.onosproject.net.intent.OpticalCircuitIntent.toString(), org.onosproject.net.intent.MultiPointToSinglePointIntent.toString(), org.onosproject.net.intent.OpticalConnectivityIntent.toString(), org.onosproject.net.intent.LinkCollectionIntent.toString(), org.onosproject.net.intent.MplsIntent.toString(), and org.onosproject.reactive.routing.ReactiveRoutingFib.updateExistingMp2pIntent().
Collection<NetworkResource> org.onosproject.net.intent.Intent.resources ()
Returns the collection of resources required for this intent.
Returns
collection of resources; may be null
Definition at line 160 of file Intent.java.
Referenced by org.onosproject.net.intent.impl.compiler.OpticalPathIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.compile(), org.onosproject.net.intent.FlowRuleIntent.FlowRuleIntent(), org.onosproject.net.intent.PathIntent.PathIntent(), org.onosproject.net.intent.FlowRuleIntent.toString(), org.onosproject.net.intent.TwoWayP2PIntent.toString(), org.onosproject.net.intent.PathIntent.toString(), org.onosproject.net.intent.HostToHostIntent.toString(), org.onosproject.net.intent.PointToPointIntent.toString(), org.onosproject.net.intent.SinglePointToMultiPointIntent.toString(), org.onosproject.net.intent.OpticalCircuitIntent.toString(), org.onosproject.net.intent.MultiPointToSinglePointIntent.toString(), org.onosproject.net.intent.OpticalConnectivityIntent.toString(), org.onosproject.net.intent.OpticalPathIntent.toString(), and org.onosproject.net.intent.LinkCollectionIntent.toString().
static void org.onosproject.net.intent.Intent.unbindIdGenerator (IdGenerator oldIdGenerator) static
Unbinds an id generator.
Note: The caller must provide the old id generator to succeed.
Parameters
oldIdGenerator the current id generator
Definition at line 209 of file Intent.java.
Member Data Documentation
final int org.onosproject.net.intent.Intent.DEFAULT_INTENT_PRIORITY = 100 static
Definition at line 45 of file Intent.java.
Referenced by org.onosproject.net.intent.FlowRuleIntent.FlowRuleIntent(), org.onosproject.net.intent.Intent.Intent(), org.onosproject.net.intent.impl.IntentManagerTest.intentWithoutCompiler(), org.onosproject.net.intent.TestInstallableIntent.TestInstallableIntent(), and org.onosproject.net.intent.TestIntent.TestIntent().
final int org.onosproject.net.intent.Intent.MAX_PRIORITY = (1 << 16) - 1 static
Definition at line 46 of file Intent.java.
final int org.onosproject.net.intent.Intent.MIN_PRIORITY = 1 static
Definition at line 47 of file Intent.java.
Referenced by org.onosproject.net.intent.Intent.Intent().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/Intent.java