onos: org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch Class Reference
org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch Class Reference abstract
An abstract representation of an OpenFlow switch.
Public Member Functions
void init (Dpid dpid, OFDescStatsReply desc, OFVersion ofv)
Initialises the behaviour.
final void disconnectSwitch ()
Disconnects the switch by closing the TCP connection.
void sendMsg (OFMessage msg)
Writes the message to the driver.
final void sendMsg (List< OFMessage > msgs)
Writes the OFMessage list to the driver.
final void sendRoleRequest (OFMessage msg)
Sends only role request messages.
final void sendHandshakeMessage (OFMessage message)
Allows the handshaker behaviour to send messages during the handshake phase only.
final boolean isConnected ()
Checks if the switch is still connected.
final void setConnected (boolean connected)
Sets whether the switch is connected.
final void setChannel (Channel channel)
Sets the associated Netty channel for this switch.
String channelId ()
Identifies the channel used to communicate with the switch.
final long getId ()
Gets the datapathId of the switch.
final String getStringId ()
Gets a string version of the ID for this switch.
final void setOFVersion (OFVersion ofV)
Sets the OF version for this switch.
void setTableFull (boolean full)
Sets this switch has having a full flowtable.
void setFeaturesReply (OFFeaturesReply featuresReply)
Sets the features reply for this switch.
abstract Boolean supportNxRole ()
Does this switch support Nicira Role messages.
final void handleMessage (OFMessage m)
Handle the message coming from the dataplane.
RoleState getRole ()
Fetch the role for this switch.
final boolean connectSwitch ()
Announce to the OpenFlow agent that this switch has connected.
final boolean activateMasterSwitch ()
Activate this MASTER switch-controller relationship in the OF agent.
final boolean activateEqualSwitch ()
Activate this EQUAL switch-controller relationship in the OF agent.
final void transitionToEqualSwitch ()
Transition this switch-controller relationship to an EQUAL state.
final void transitionToMasterSwitch ()
Transition this switch-controller relationship to an Master state.
final void removeConnectedSwitch ()
Remove this switch from the openflow agent.
OFFactory factory ()
Provides the factory for this OF version.
void setPortDescReply (OFPortDescStatsReply portDescReply)
Sets the ports on this switch.
void setPortDescReplies (List< OFPortDescStatsReply > portDescReplies)
Sets the ports on this switch.
void returnRoleReply (RoleState requested, RoleState response)
Notifies the controller that the device has responded to a set-role request.
abstract void startDriverHandshake ()
Starts the driver specific handshake process.
abstract boolean isDriverHandshakeComplete ()
Checks whether the driver specific handshake is complete.
abstract void processDriverHandshakeMessage (OFMessage m)
Process a message during the driver specific handshake.
void setRole (RoleState role)
Sets the role for this switch.
void reassertRole ()
Reasserts this controllers role to the switch.
void handleRole (OFMessage m) throws SwitchStateException
Handle OF 1.x (where x > 0) role messages.
void handleNiciraRole (OFMessage m) throws SwitchStateException
If this driver know of Nicira style role messages, these should be handled here.
boolean handleRoleError (OFErrorMsg error)
Handle the situation where the role request triggers an error.
final void setAgent (OpenFlowAgent ag)
Sets the OpenFlow agent to be used.
final void setRoleHandler (RoleHandler roleHandler)
Sets the Role handler object.
void setSwitchDescription (OFDescStatsReply d)
Sets the switch description.
int getNextTransactionId ()
Gets the next transaction id to use.
List< OFPortDesc > getPorts ()
Fetches the ports of this switch.
String manufacturerDescription ()
fetch the manufacturer description.
String datapathDescription ()
fetch the datapath description.
String hardwareDescription ()
fetch the hardware description.
String softwareDescription ()
fetch the software description.
String serialNumber ()
fetch the serial number.
Device.Type deviceType ()
Returns the switch device type.
String toString ()
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Protected Attributes
final Logger log = LoggerFactory.getLogger(getClass())
String channelId
boolean startDriverHandshakeCalled = false
List< OFPortDescStatsReply > ports = new ArrayList<>()
boolean tableFull
volatile RoleState role
OFFeaturesReply features
OFDescStatsReply desc
Detailed Description
An abstract representation of an OpenFlow switch.
Can be extended by others to serve as a base for their vendor specific representation of a switch.
Definition at line 57 of file AbstractOpenFlowSwitch.java.
Member Function Documentation
final boolean org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.activateEqualSwitch ()
Activate this EQUAL switch-controller relationship in the OF agent.
Returns
true is successful, false is switch has not connected or is unknown to the system.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 272 of file AbstractOpenFlowSwitch.java.
final boolean org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.activateMasterSwitch ()
Activate this MASTER switch-controller relationship in the OF agent.
Returns
true is successful, false is switch has not connected or is unknown to the system.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 267 of file AbstractOpenFlowSwitch.java.
String org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.channelId ()
Identifies the channel used to communicate with the switch.
Returns
string representation of the connection to the device
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 205 of file AbstractOpenFlowSwitch.java.
Referenced by org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setChannel().
final boolean org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.connectSwitch ()
Announce to the OpenFlow agent that this switch has connected.
Returns
true if successful, false if duplicate switch.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 262 of file AbstractOpenFlowSwitch.java.
String org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.datapathDescription ()
fetch the datapath description.
Returns
the description
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 463 of file AbstractOpenFlowSwitch.java.
Device.Type org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.deviceType ()
Returns the switch device type.
Returns
device type
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 483 of file AbstractOpenFlowSwitch.java.
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.disconnectSwitch ()
Disconnects the switch by closing the TCP connection.
Results in a call to the channel handler's channelDisconnected method for cleanup
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 100 of file AbstractOpenFlowSwitch.java.
OFFactory org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.factory ()
Provides the factory for this OF version.
Returns
OF version specific factory.
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 303 of file AbstractOpenFlowSwitch.java.
Referenced by org.onosproject.driver.handshaker.DefaultSwitchHandshaker.getPorts(), org.onosproject.driver.handshaker.DefaultSwitchHandshaker.startDriverHandshake(), org.onosproject.driver.handshaker.CorsaSwitchHandshaker.startDriverHandshake(), and org.onosproject.driver.handshaker.NiciraSwitchHandshaker.supportNxRole().
final long org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.getId ()
Gets the datapathId of the switch.
Returns
the switch dpid in long format
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 214 of file AbstractOpenFlowSwitch.java.
Referenced by metro.FabricDomain.build().
int org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.getNextTransactionId ()
Gets the next transaction id to use.
Returns
the xid
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 446 of file AbstractOpenFlowSwitch.java.
Referenced by org.onosproject.driver.handshaker.CorsaSwitchHandshaker.startDriverHandshake().
List<OFPortDesc> org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.getPorts ()
Fetches the ports of this switch.
Returns
unmodifiable list of the ports.
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 451 of file AbstractOpenFlowSwitch.java.
RoleState org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.getRole ()
Fetch the role for this switch.
Returns
the role.
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 257 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.role.
Referenced by org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.reassertRole().
final String org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.getStringId ()
Gets a string version of the ID for this switch.
Returns
string version of the ID
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 219 of file AbstractOpenFlowSwitch.java.
Referenced by org.onosproject.driver.handshaker.OFOpticalSwitch13.processDriverHandshakeMessage(), org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker.processDriverHandshakeMessage(), org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13.processDriverHandshakeMessage(), org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setRole(), org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker.startDriverHandshake(), org.onosproject.driver.handshaker.OFOpticalSwitch13.startDriverHandshake(), org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13.startDriverHandshake(), and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.toString().
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.handleMessage (OFMessage m)
Handle the message coming from the dataplane.
Parameters
m the actual message
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 250 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.RoleState.MASTER, and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.role.
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.handleNiciraRole (OFMessage m) throws SwitchStateException
If this driver know of Nicira style role messages, these should be handled here.
Parameters
m the role message to handle.
Exceptions
SwitchStateException if the message received was not a nicira role or was malformed.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 393 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.RoleState.EQUAL, org.onosproject.openflow.controller.RoleState.MASTER, org.onosproject.openflow.controller.driver.RoleRecvStatus.MATCHED_SET_ROLE, and org.onosproject.openflow.controller.RoleState.SLAVE.
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.handleRole (OFMessage m) throws SwitchStateException
Handle OF 1.x (where x > 0) role messages.
Parameters
m the role message to handle
Exceptions
SwitchStateException if the message received was not a nicira role or was malformed.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 377 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.driver.RoleReplyInfo.getRole(), org.onosproject.openflow.controller.RoleState.MASTER, org.onosproject.openflow.controller.driver.RoleRecvStatus.MATCHED_SET_ROLE, and org.onosproject.openflow.controller.RoleState.SLAVE.
boolean org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.handleRoleError (OFErrorMsg error)
Handle the situation where the role request triggers an error.
Parameters
error the error to handle.
Returns
true if handled, false if not.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 417 of file AbstractOpenFlowSwitch.java.
String org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.hardwareDescription ()
fetch the hardware description.
Returns
the description
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 468 of file AbstractOpenFlowSwitch.java.
Referenced by org.onosproject.driver.handshaker.OFOpticalSwitch13.deviceType().
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.init (Dpid dpid, OFDescStatsReply desc, OFVersion ofv)
Initialises the behaviour.
Parameters
dpid a dpid
desc a switch description
ofv OpenFlow version
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 89 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.desc.
final boolean org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.isConnected ()
Checks if the switch is still connected.
Returns
whether the switch is still connected
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 180 of file AbstractOpenFlowSwitch.java.
abstract boolean org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.isDriverHandshakeComplete () pure virtual
Checks whether the driver specific handshake is complete.
Returns
true is finished, false if not.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Implemented in org.onosproject.driver.handshaker.OFOpticalSwitch13, org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13, org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker, org.onosproject.driver.handshaker.CorsaSwitchHandshaker, and org.onosproject.driver.handshaker.DefaultSwitchHandshaker.
Referenced by org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.sendHandshakeMessage().
String org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.manufacturerDescription ()
fetch the manufacturer description.
Returns
the description
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 458 of file AbstractOpenFlowSwitch.java.
abstract void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.processDriverHandshakeMessage (OFMessage m) pure virtual
Process a message during the driver specific handshake.
Parameters
m the message to process.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Implemented in org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13, org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker, org.onosproject.driver.handshaker.OFOpticalSwitch13, org.onosproject.driver.handshaker.CorsaSwitchHandshaker, and org.onosproject.driver.handshaker.DefaultSwitchHandshaker.
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.reassertRole ()
Reasserts this controllers role to the switch.
Useful in cases where the switch no longer agrees that this controller has the role it claims.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 366 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.getRole(), and org.onosproject.openflow.controller.RoleState.MASTER.
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.removeConnectedSwitch ()
Remove this switch from the openflow agent.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 298 of file AbstractOpenFlowSwitch.java.
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.returnRoleReply (RoleState requested, RoleState response)
Notifies the controller that the device has responded to a set-role request.
Parameters
requested the role requested by the controller
response the role set at the device
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 318 of file AbstractOpenFlowSwitch.java.
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.sendHandshakeMessage (OFMessage message)
Allows the handshaker behaviour to send messages during the handshake phase only.
Parameters
message an OpenFlow message
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 173 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.isDriverHandshakeComplete().
Referenced by org.onosproject.driver.handshaker.DefaultSwitchHandshaker.startDriverHandshake(), and org.onosproject.driver.handshaker.CorsaSwitchHandshaker.startDriverHandshake().
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.sendMsg (OFMessage msg)
Writes the message to the driver.
Note: Messages may be silently dropped/lost due to IOExceptions or role. If this is a concern, then a caller should use barriers.
Parameters
msg the message to write
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 105 of file AbstractOpenFlowSwitch.java.
Referenced by org.onosproject.driver.handshaker.CorsaSwitchHandshaker.startDriverHandshake().
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.sendMsg (List< OFMessage > msgs)
Writes the OFMessage list to the driver.
Note: Messages may be silently dropped/lost due to IOExceptions or role. If this is a concern, then a caller should use barriers.
Parameters
msgs the messages to be written
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 110 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.RoleState.MASTER, and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.role.
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.sendRoleRequest (OFMessage message)
Sends only role request messages.
Parameters
message a role request message.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 162 of file AbstractOpenFlowSwitch.java.
String org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.serialNumber ()
fetch the serial number.
Returns
the serial
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 478 of file AbstractOpenFlowSwitch.java.
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setAgent (OpenFlowAgent agent)
Sets the OpenFlow agent to be used.
This method can only be called once.
Parameters
agent the agent to set.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 427 of file AbstractOpenFlowSwitch.java.
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setChannel (Channel channel)
Sets the associated Netty channel for this switch.
Parameters
channel the Netty channel
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 190 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.channelId(), and org.onlab.packet.IpAddress.isIp4().
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setConnected (boolean connected)
Sets whether the switch is connected.
Parameters
connected whether the switch is connected
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 185 of file AbstractOpenFlowSwitch.java.
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setFeaturesReply (OFFeaturesReply featuresReply)
Sets the features reply for this switch.
Parameters
featuresReply the features to set.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 234 of file AbstractOpenFlowSwitch.java.
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setOFVersion (OFVersion ofV)
Sets the OF version for this switch.
Parameters
ofV the version to set.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 224 of file AbstractOpenFlowSwitch.java.
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setPortDescReplies (List< OFPortDescStatsReply > portDescReplies)
Sets the ports on this switch.
Parameters
portDescReplies list of port set and descriptions
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 313 of file AbstractOpenFlowSwitch.java.
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setPortDescReply (OFPortDescStatsReply portDescReply)
Sets the ports on this switch.
Parameters
portDescReply the port set and descriptions
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 308 of file AbstractOpenFlowSwitch.java.
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setRole (RoleState role)
Sets the role for this switch.
Parameters
role the role to set.
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 335 of file AbstractOpenFlowSwitch.java.
References obeliskHostCheck.dpid, org.onosproject.openflow.controller.RoleState.EQUAL, org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.getStringId(), org.onosproject.openflow.controller.RoleState.MASTER, org.onosproject.openflow.controller.driver.RoleRecvStatus.MATCHED_SET_ROLE, org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.role, org.onosproject.openflow.controller.driver.RoleHandler.sendRoleRequest(), and org.onosproject.openflow.controller.RoleState.SLAVE.
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setRoleHandler (RoleHandler roleHandler)
Sets the Role handler object.
This method can only be called once.
Parameters
roleHandler the roleHandler class
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 434 of file AbstractOpenFlowSwitch.java.
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setSwitchDescription (OFDescStatsReply desc)
Sets the switch description.
Parameters
desc the descriptions
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 441 of file AbstractOpenFlowSwitch.java.
void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setTableFull (boolean full)
Sets this switch has having a full flowtable.
Parameters
full true if full, false otherswise.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 229 of file AbstractOpenFlowSwitch.java.
String org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.softwareDescription ()
fetch the software description.
Returns
the description
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 473 of file AbstractOpenFlowSwitch.java.
abstract void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.startDriverHandshake () pure virtual
Starts the driver specific handshake process.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Implemented in org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13, org.onosproject.driver.handshaker.OFOpticalSwitch13, org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker, org.onosproject.driver.handshaker.CorsaSwitchHandshaker, and org.onosproject.driver.handshaker.DefaultSwitchHandshaker.
abstract Boolean org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.supportNxRole () pure virtual
Does this switch support Nicira Role messages.
Returns
true if supports, false otherwise.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Implemented in org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13, org.onosproject.driver.handshaker.OFOpticalSwitch13, org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker, org.onosproject.driver.handshaker.CorsaSwitchHandshaker, org.onosproject.driver.handshaker.DefaultSwitchHandshaker, and org.onosproject.driver.handshaker.NiciraSwitchHandshaker.
String org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.toString ()
Definition at line 488 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.getStringId().
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.transitionToEqualSwitch ()
Transition this switch-controller relationship to an EQUAL state.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 277 of file AbstractOpenFlowSwitch.java.
final void org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.transitionToMasterSwitch ()
Transition this switch-controller relationship to an Master state.
Implements org.onosproject.openflow.controller.driver.OpenFlowSwitchDriver.
Definition at line 282 of file AbstractOpenFlowSwitch.java.
References org.onosproject.openflow.controller.RoleState.MASTER.
Member Data Documentation
String org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.channelId protected
Definition at line 63 of file AbstractOpenFlowSwitch.java.
OFDescStatsReply org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.desc protected
Definition at line 83 of file AbstractOpenFlowSwitch.java.
Referenced by org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.init().
OFFeaturesReply org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.features protected
Definition at line 82 of file AbstractOpenFlowSwitch.java.
Referenced by onos.ONOS.updateFeatures().
final Logger org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.log = LoggerFactory.getLogger(getClass()) protected
Definition at line 60 of file AbstractOpenFlowSwitch.java.
List<OFPortDescStatsReply> org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.ports = new ArrayList<>() protected
Definition at line 73 of file AbstractOpenFlowSwitch.java.
volatile RoleState org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.role protected
Definition at line 80 of file AbstractOpenFlowSwitch.java.
Referenced by org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.getRole(), org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.handleMessage(), org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.sendMsg(), and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setRole().
boolean org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.startDriverHandshakeCalled = false protected
Definition at line 66 of file AbstractOpenFlowSwitch.java.
Referenced by org.onosproject.driver.handshaker.CorsaSwitchHandshaker.isDriverHandshakeComplete(), org.onosproject.driver.handshaker.CorsaSwitchHandshaker.processDriverHandshakeMessage(), org.onosproject.driver.handshaker.OFOpticalSwitch13.processDriverHandshakeMessage(), org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker.processDriverHandshakeMessage(), org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13.processDriverHandshakeMessage(), org.onosproject.driver.handshaker.CorsaSwitchHandshaker.startDriverHandshake(), org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker.startDriverHandshake(), org.onosproject.driver.handshaker.OFOpticalSwitch13.startDriverHandshake(), and org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13.startDriverHandshake().
boolean org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.tableFull protected
Definition at line 75 of file AbstractOpenFlowSwitch.java.
The documentation for this class was generated from the following file:
protocols/openflow/api/src/main/java/org/onosproject/openflow/controller/driver/AbstractOpenFlowSwitch.java