onos: org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent Class Reference
org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent Class Reference
Implementation of an OpenFlow Agent which is responsible for keeping track of connected switches and the state in which they are.
Public Member Functions
boolean addConnectedSwitch (Dpid dpid, OpenFlowSwitch sw)
Add a switch that has just connected to the system.
boolean validActivation (Dpid dpid)
Checks if the activation for this switch is valid.
boolean addActivatedMasterSwitch (Dpid dpid, OpenFlowSwitch sw)
Called when a switch is activated, with this controller's role as MASTER.
boolean addActivatedEqualSwitch (Dpid dpid, OpenFlowSwitch sw)
Called when a switch is activated, with this controller's role as EQUAL.
void transitionToMasterSwitch (Dpid dpid)
Called when this controller's role for a switch transitions from equal to master.
void transitionToEqualSwitch (Dpid dpid)
Called when this controller's role for a switch transitions to equal.
void removeConnectedSwitch (Dpid dpid)
Clear all state in controller switch maps for a switch that has disconnected from the local controller.
void processMessage (Dpid dpid, OFMessage m)
Process a message coming from a switch.
void returnRoleReply (Dpid dpid, RoleState requested, RoleState response)
Notifies the controller that role assertion has failed.
Detailed Description
Implementation of an OpenFlow Agent which is responsible for keeping track of connected switches and the state in which they are.
Definition at line 467 of file OpenFlowControllerImpl.java.
Member Function Documentation
boolean org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.addActivatedEqualSwitch (Dpid dpid, OpenFlowSwitch sw)
Called when a switch is activated, with this controller's role as EQUAL.
Parameters
dpid the dpid to add.
sw the actual switch
Returns
true if added, false otherwise.
Implements org.onosproject.openflow.controller.driver.OpenFlowAgent.
Definition at line 526 of file OpenFlowControllerImpl.java.
References obeliskHostCheck.dpid, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.validActivation().
boolean org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.addActivatedMasterSwitch (Dpid dpid, OpenFlowSwitch sw)
Called when a switch is activated, with this controller's role as MASTER.
Parameters
dpid the dpid to add.
sw the actual switch
Returns
true if added, false otherwise.
Implements org.onosproject.openflow.controller.driver.OpenFlowAgent.
Definition at line 512 of file OpenFlowControllerImpl.java.
References obeliskHostCheck.dpid, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.validActivation().
boolean org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.addConnectedSwitch (Dpid dpid, OpenFlowSwitch sw)
Add a switch that has just connected to the system.
Parameters
dpid the dpid to add
sw the actual switch object.
Returns
true if added, false otherwise.
Implements org.onosproject.openflow.controller.driver.OpenFlowAgent.
Definition at line 473 of file OpenFlowControllerImpl.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.connectedSwitches, obeliskHostCheck.dpid, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.ofSwitchListener.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.processMessage (Dpid dpid, OFMessage m)
Process a message coming from a switch.
Parameters
dpid the dpid the message came on.
m the message to process
Implements org.onosproject.openflow.controller.driver.OpenFlowAgent.
Definition at line 602 of file OpenFlowControllerImpl.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.processPacket().
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.removeConnectedSwitch (Dpid dpid)
Clear all state in controller switch maps for a switch that has disconnected from the local controller.
Also release control for that switch from the global repository. Notify switch listeners.
Parameters
dpid the dpid to remove.
Implements org.onosproject.openflow.controller.driver.OpenFlowAgent.
Definition at line 589 of file OpenFlowControllerImpl.java.
References obeliskHostCheck.dpid, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.ofSwitchListener.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.returnRoleReply (Dpid dpid, RoleState requested, RoleState response)
Notifies the controller that role assertion has failed.
Parameters
dpid the switch that failed role assertion
requested the role controller requested
response role reply from the switch
Implements org.onosproject.openflow.controller.driver.OpenFlowAgent.
Definition at line 607 of file OpenFlowControllerImpl.java.
References obeliskHostCheck.dpid, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.ofSwitchListener.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.transitionToEqualSwitch (Dpid dpid)
Called when this controller's role for a switch transitions to equal.
For 1.0 switches, we internally refer to the role 'slave' as 'equal'.
Parameters
dpid the dpid to transistion.
Implements org.onosproject.openflow.controller.driver.OpenFlowAgent.
Definition at line 565 of file OpenFlowControllerImpl.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.activeEqualSwitches, obeliskHostCheck.dpid, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getSwitch().
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.transitionToMasterSwitch (Dpid dpid)
Called when this controller's role for a switch transitions from equal to master.
For 1.0 switches, we internally refer to the role 'slave' as 'equal' - so this transition is equivalent to 'addActivatedMasterSwitch'.
Parameters
dpid the dpid to transistion.
Implements org.onosproject.openflow.controller.driver.OpenFlowAgent.
Definition at line 541 of file OpenFlowControllerImpl.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.activeMasterSwitches, obeliskHostCheck.dpid, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getSwitch().
boolean org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.validActivation (Dpid dpid)
Checks if the activation for this switch is valid.
Parameters
dpid the dpid to check
Returns
true if valid, false otherwise
Implements org.onosproject.openflow.controller.driver.OpenFlowAgent.
Definition at line 490 of file OpenFlowControllerImpl.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.activeMasterSwitches, org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.connectedSwitches, and obeliskHostCheck.dpid.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.addActivatedEqualSwitch(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.addActivatedMasterSwitch().
The documentation for this class was generated from the following file:
protocols/openflow/ctl/src/main/java/org/onosproject/openflow/controller/impl/OpenFlowControllerImpl.java