onos: org.onlab.util.HexString Class Reference
org.onlab.util.HexString Class Reference
Static Public Member Functions
static String toHexString (final byte[] bytes)
Convert a byte array to a colon-separated hex string.
static String toHexString (final byte[] bytes, String separator)
Convert a byte array to a hex string separated by given separator.
static String toHexString (final long val, final int padTo)
Convert a long number to colon-separated hex string.
static String toHexString (final long val)
Convert a long number to colon-separated hex string.
static byte[] fromHexString (final String values)
Convert a colon-separated hex string to byte array.
static long toLong (String value)
Convert a colon-separated hex string to long.
Detailed Description
Definition at line 18 of file HexString.java.
Member Function Documentation
static byte [] org.onlab.util.HexString.fromHexString (final String values) static
Convert a colon-separated hex string to byte array.
Parameters
values colon-separated hex string to be converted, e.g. "0f:ca:fe:de:ad:be:ef"
Returns
converted byte array
Exceptions
NumberFormatException if input hex string cannot be parsed
Definition at line 111 of file HexString.java.
References find-link-in-cluster.length.
static String org.onlab.util.HexString.toHexString (final byte[] bytes) static
Convert a byte array to a colon-separated hex string.
Parameters
bytes byte array to be converted
Returns
converted colon-separated hex string, e.g. "0f:ca:fe:de:ad:be:ef", or "(null)" if given byte array is null
Definition at line 30 of file HexString.java.
Referenced by org.onosproject.net.OduSignalId.OduSignalId(), and org.onlab.util.HexString.toHexString().
static String org.onlab.util.HexString.toHexString (final byte[] bytes, String separator) static
Convert a byte array to a hex string separated by given separator.
Parameters
bytes byte array to be converted
separator the string use to separate each byte
Returns
converted hex string, or "(null)" if given byte array is null
Definition at line 41 of file HexString.java.
References find-link-in-cluster.length.
static String org.onlab.util.HexString.toHexString (final long val, final int padTo) static
Convert a long number to colon-separated hex string.
Prepend zero padding until given length.
Parameters
val long number to be converted
padTo prepend zeros until this length
Returns
converted colon-separated hex string, e.g. "0f:ca:fe:de:ad:be:ef"
Definition at line 72 of file HexString.java.
References find-link-in-cluster.length.
static String org.onlab.util.HexString.toHexString (final long val) static
Convert a long number to colon-separated hex string.
Prepend zero padding until 8 bytes.
Parameters
val long number to be converted
Returns
converted colon-separated hex string, e.g. "0f:ca:fe:de:ad:be:ef"
Definition at line 99 of file HexString.java.
References org.onlab.util.HexString.toHexString().
static long org.onlab.util.HexString.toLong (String value) static
Convert a colon-separated hex string to long.
Parameters
value colon-separated hex string to be converted, e.g. "00:0f:ca:fe:de:ad:be:ef"
Returns
converted long number
Exceptions
NumberFormatException if input hex string cannot be parsed
Definition at line 132 of file HexString.java.
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/util/HexString.java