onos: org.onosproject.driver.pipeline.SoftRouterPipeline Class Reference
org.onosproject.driver.pipeline.SoftRouterPipeline Class Reference
Simple 2-Table Pipeline for Software/NPU based routers.
Public Member Functions
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filteringObjective)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Protected Attributes
FlowRuleService flowRuleService
DeviceId deviceId
ApplicationId appId
Static Protected Attributes
static final int FILTER_TABLE = 0
static final int FIB_TABLE = 1
Detailed Description
Simple 2-Table Pipeline for Software/NPU based routers.
This pipeline does not forward IP traffic to next-hop groups. Instead it forwards traffic using OF FlowMod actions.
Definition at line 68 of file SoftRouterPipeline.java.
Member Function Documentation
void org.onosproject.driver.pipeline.SoftRouterPipeline.filter (FilteringObjective filterObjective)
Installs the filtering rules onto the device.
Parameters
filterObjective a filtering objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 111 of file SoftRouterPipeline.java.
References org.onosproject.net.flowobjective.Objective.op(), org.onosproject.net.flowobjective.FilteringObjective.type(), and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
Referenced by org.onosproject.driver.pipeline.SoftRouterPipeline.forward().
void org.onosproject.driver.pipeline.SoftRouterPipeline.forward (ForwardingObjective forwardObjective)
Installs the forwarding rules onto the device.
Parameters
forwardObjective a forwarding objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 122 of file SoftRouterPipeline.java.
References org.onosproject.driver.pipeline.SoftRouterPipeline.filter(), org.onosproject.net.flowobjective.ObjectiveError.FLOWINSTALLATIONFAILED, org.onosproject.net.flowobjective.Objective.op(), and org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN.
void org.onosproject.driver.pipeline.SoftRouterPipeline.init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
Parameters
deviceId the deviceId
context processing context
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 96 of file SoftRouterPipeline.java.
References org.onosproject.driver.pipeline.SoftRouterPipeline.deviceId, and org.onosproject.driver.pipeline.SoftRouterPipeline.flowRuleService.
void org.onosproject.driver.pipeline.SoftRouterPipeline.next (NextObjective nextObjective)
Installs the next hop elements into the device.
Parameters
nextObjective a next objectives
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 159 of file SoftRouterPipeline.java.
References org.onosproject.net.flowobjective.ObjectiveError.BADPARAMS, org.onosproject.net.flowobjective.NextObjective.type(), org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN, and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
Member Data Documentation
ApplicationId org.onosproject.driver.pipeline.SoftRouterPipeline.appId protected
Definition at line 82 of file SoftRouterPipeline.java.
DeviceId org.onosproject.driver.pipeline.SoftRouterPipeline.deviceId protected
Definition at line 81 of file SoftRouterPipeline.java.
Referenced by org.onosproject.driver.pipeline.SoftRouterPipeline.init().
final int org.onosproject.driver.pipeline.SoftRouterPipeline.FIB_TABLE = 1 static protected
Definition at line 71 of file SoftRouterPipeline.java.
final int org.onosproject.driver.pipeline.SoftRouterPipeline.FILTER_TABLE = 0 static protected
Definition at line 70 of file SoftRouterPipeline.java.
FlowRuleService org.onosproject.driver.pipeline.SoftRouterPipeline.flowRuleService protected
Definition at line 78 of file SoftRouterPipeline.java.
Referenced by org.onosproject.driver.pipeline.SoftRouterPipeline.init().
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/pipeline/SoftRouterPipeline.java