onos: org.onosproject.ovsdb.rfc.schema.ColumnSchema Class Reference
org.onosproject.ovsdb.rfc.schema.ColumnSchema Class Reference
A schema for the column represented by column-schema.
Public Member Functions
ColumnSchema (String name, ColumnType columnType)
Constructs a ColumnSchema object.
String name ()
Returns the name of column.
ColumnType type ()
Returns the type of column.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
A schema for the column represented by column-schema.
Definition at line 28 of file ColumnSchema.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.schema.ColumnSchema.ColumnSchema (String name, ColumnType columnType)
Constructs a ColumnSchema object.
Parameters
name the column name
columnType the column type
Definition at line 37 of file ColumnSchema.java.
References org.onosproject.ovsdb.rfc.schema.ColumnSchema.name().
Referenced by org.onosproject.ovsdb.rfc.schema.ColumnSchema.equals().
Member Function Documentation
boolean org.onosproject.ovsdb.rfc.schema.ColumnSchema.equals (Object obj)
Definition at line 66 of file ColumnSchema.java.
References org.onosproject.ovsdb.rfc.schema.ColumnSchema.ColumnSchema(), and create-flow.name.
int org.onosproject.ovsdb.rfc.schema.ColumnSchema.hashCode ()
Definition at line 61 of file ColumnSchema.java.
References org.onosproject.ovsdb.rfc.schema.ColumnSchema.name(), and org.onosproject.ovsdb.rfc.schema.ColumnSchema.type().
String org.onosproject.ovsdb.rfc.schema.ColumnSchema.name ()
Returns the name of column.
Returns
the name of column
Definition at line 48 of file ColumnSchema.java.
Referenced by org.onosproject.ovsdb.rfc.schema.ColumnSchema.ColumnSchema(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.ovsdb.rfc.schema.ColumnSchema.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.ovsdb.rfc.schema.ColumnSchema.toString().
String org.onosproject.ovsdb.rfc.schema.ColumnSchema.toString ()
Definition at line 79 of file ColumnSchema.java.
References org.onosproject.ovsdb.rfc.schema.ColumnSchema.name(), and org.onosproject.ovsdb.rfc.schema.ColumnSchema.type().
ColumnType org.onosproject.ovsdb.rfc.schema.ColumnSchema.type ()
Returns the type of column.
Returns
the type of column
Definition at line 56 of file ColumnSchema.java.
Referenced by org.onosproject.ovsdb.rfc.schema.ColumnSchema.hashCode(), and org.onosproject.ovsdb.rfc.schema.ColumnSchema.toString().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/schema/ColumnSchema.java