onos: org.onosproject.net.resource.link.MplsLabelResourceAllocation Class Reference
org.onosproject.net.resource.link.MplsLabelResourceAllocation Class Reference
Representation of allocated MPLS label resource.
Public Member Functions
ResourceType type ()
Returns the resource type.
MplsLabelResourceAllocation (MplsLabel mplsLabel)
Creates a new MplsLabelResourceAllocation with MplsLabel object.
MplsLabel mplsLabel ()
Returns the MPLS label resource.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Representation of allocated MPLS label resource.
Deprecated:
in Emu Release
Definition at line 31 of file MplsLabelResourceAllocation.java.
Constructor & Destructor Documentation
org.onosproject.net.resource.link.MplsLabelResourceAllocation.MplsLabelResourceAllocation (MplsLabel mplsLabel)
Creates a new MplsLabelResourceAllocation with MplsLabel object.
Parameters
mplsLabel allocated MPLS Label
Definition at line 45 of file MplsLabelResourceAllocation.java.
References org.onosproject.net.resource.link.MplsLabelResourceAllocation.mplsLabel().
Referenced by org.onosproject.net.resource.link.MplsLabelResourceAllocation.equals().
Member Function Documentation
boolean org.onosproject.net.resource.link.MplsLabelResourceAllocation.equals (Object obj)
Definition at line 64 of file MplsLabelResourceAllocation.java.
References org.onosproject.net.resource.link.MplsLabelResourceAllocation.MplsLabelResourceAllocation().
int org.onosproject.net.resource.link.MplsLabelResourceAllocation.hashCode ()
Definition at line 59 of file MplsLabelResourceAllocation.java.
References org.onosproject.net.resource.link.MplsLabelResourceAllocation.mplsLabel().
MplsLabel org.onosproject.net.resource.link.MplsLabelResourceAllocation.mplsLabel ()
Returns the MPLS label resource.
Returns
the MPLS label resource
Definition at line 54 of file MplsLabelResourceAllocation.java.
Referenced by org.onosproject.net.resource.link.MplsLabelResourceAllocation.hashCode(), org.onosproject.net.resource.link.MplsLabelResourceAllocation.MplsLabelResourceAllocation(), and org.onosproject.net.resource.link.MplsLabelResourceAllocation.toString().
String org.onosproject.net.resource.link.MplsLabelResourceAllocation.toString ()
Definition at line 76 of file MplsLabelResourceAllocation.java.
References org.onosproject.net.resource.link.MplsLabelResourceAllocation.mplsLabel().
ResourceType org.onosproject.net.resource.link.MplsLabelResourceAllocation.type ()
Returns the resource type.
Returns
the resource type
Implements org.onosproject.net.resource.ResourceAllocation.
Definition at line 35 of file MplsLabelResourceAllocation.java.
References org.onosproject.net.resource.ResourceType.MPLS_LABEL.
Referenced by org.onosproject.net.resource.MplsObjectsTest.checkLabelResourceAllocationConstruction().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/resource/link/MplsLabelResourceAllocation.java