onos: org.onosproject.vtnrsc.DefaultPortPairGroup Class Reference
org.onosproject.vtnrsc.DefaultPortPairGroup Class Reference
Implementation of port pair group.
Classes
class Builder
Builder class for Port pair group.
Public Member Functions
PortPairGroupId portPairGroupId ()
Returns the ID of this port pair group.
TenantId tenantId ()
Returns the tenant id of this port pair group.
String name ()
Returns the name of this port pair group.
String description ()
Returns the description of this port pair group.
List< PortPairId > portPairs ()
Returns the list of port pairs associated with this port pair group.
int hashCode ()
boolean equals (Object obj)
boolean exactMatch (PortPairGroup portPairGroup)
Returns whether this port pair group is an exact match to the port pair group given in the argument.
String toString ()
Static Public Member Functions
static Builder builder ()
To create an instance of the builder.
Detailed Description
Implementation of port pair group.
Definition at line 29 of file DefaultPortPairGroup.java.
Member Function Documentation
static Builder org.onosproject.vtnrsc.DefaultPortPairGroup.builder () static
To create an instance of the builder.
Returns
instance of builder
Definition at line 127 of file DefaultPortPairGroup.java.
String org.onosproject.vtnrsc.DefaultPortPairGroup.description ()
Returns the description of this port pair group.
Returns
description of port pair group
Implements org.onosproject.vtnrsc.PortPairGroup.
Definition at line 73 of file DefaultPortPairGroup.java.
Referenced by org.onosproject.vtnrsc.DefaultPortPairGroup.hashCode().
boolean org.onosproject.vtnrsc.DefaultPortPairGroup.equals (Object obj)
Definition at line 89 of file DefaultPortPairGroup.java.
References create-flow.name, org.onosproject.vtnrsc.DefaultPortPairGroup.name(), and org.onosproject.vtnrsc.DefaultPortPairGroup.portPairGroupId().
boolean org.onosproject.vtnrsc.DefaultPortPairGroup.exactMatch (PortPairGroup portPairGroup)
Returns whether this port pair group is an exact match to the port pair group given in the argument.
Exact match means the Port pairs match with the given port pair group. It does not consider the port pair group id, name and description.
Parameters
portPairGroup other port pair group to match against
Returns
true if the port pairs are an exact match, otherwise false
Implements org.onosproject.vtnrsc.PortPairGroup.
Definition at line 105 of file DefaultPortPairGroup.java.
References org.onosproject.vtnrsc.PortPairGroup.portPairGroupId(), and org.onosproject.vtnrsc.PortPairGroup.tenantId().
int org.onosproject.vtnrsc.DefaultPortPairGroup.hashCode ()
Definition at line 83 of file DefaultPortPairGroup.java.
References org.onosproject.vtnrsc.DefaultPortPairGroup.description(), org.onosproject.vtnrsc.DefaultPortPairGroup.name(), org.onosproject.vtnrsc.DefaultPortPairGroup.portPairGroupId(), and org.onosproject.vtnrsc.DefaultPortPairGroup.tenantId().
String org.onosproject.vtnrsc.DefaultPortPairGroup.name ()
Returns the name of this port pair group.
Returns
name of port pair group
Implements org.onosproject.vtnrsc.PortPairGroup.
Definition at line 68 of file DefaultPortPairGroup.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.vtnrsc.DefaultPortPairGroup.equals(), org.onosproject.vtnrsc.DefaultPortPairGroup.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.vtnrsc.DefaultPortPairGroup.toString().
PortPairGroupId org.onosproject.vtnrsc.DefaultPortPairGroup.portPairGroupId ()
Returns the ID of this port pair group.
Returns
the port pair group id
Implements org.onosproject.vtnrsc.PortPairGroup.
Definition at line 58 of file DefaultPortPairGroup.java.
Referenced by org.onosproject.vtnrsc.DefaultPortPairGroup.equals(), and org.onosproject.vtnrsc.DefaultPortPairGroup.hashCode().
List<PortPairId> org.onosproject.vtnrsc.DefaultPortPairGroup.portPairs ()
Returns the list of port pairs associated with this port pair group.
Returns
list of port pairs
Implements org.onosproject.vtnrsc.PortPairGroup.
Definition at line 78 of file DefaultPortPairGroup.java.
TenantId org.onosproject.vtnrsc.DefaultPortPairGroup.tenantId ()
Returns the tenant id of this port pair group.
Returns
the tenant id
Implements org.onosproject.vtnrsc.PortPairGroup.
Definition at line 63 of file DefaultPortPairGroup.java.
Referenced by org.onosproject.vtnrsc.DefaultPortPairGroup.hashCode().
String org.onosproject.vtnrsc.DefaultPortPairGroup.toString ()
Definition at line 112 of file DefaultPortPairGroup.java.
References org.onosproject.vtnrsc.DefaultPortPairGroup.name().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultPortPairGroup.java