onos: org.onosproject.incubator.net.intf.Interface Class Reference
org.onosproject.incubator.net.intf.Interface Class Reference
An Interface maps network configuration information (such as addresses and vlans) to a port in the network.
Public Member Functions
Interface (ConnectPoint connectPoint, Set< InterfaceIpAddress > ipAddresses, MacAddress macAddress, VlanId vlan)
Creates new Interface with the provided configuration.
ConnectPoint connectPoint ()
Retrieves the connection point that this interface maps to.
Set< InterfaceIpAddress > ipAddresses ()
Retrieves the set of IP addresses that are assigned to the interface.
MacAddress mac ()
Retrieves the MAC address that is assigned to the interface.
VlanId vlan ()
Retrieves the VLAN ID that is assigned to the interface.
boolean equals (Object other)
int hashCode ()
String toString ()
Detailed Description
An Interface maps network configuration information (such as addresses and vlans) to a port in the network.
This is considered a L2/L3 network interface.
Definition at line 37 of file Interface.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.intf.Interface.Interface (ConnectPoint connectPoint, Set< InterfaceIpAddress > ipAddresses, MacAddress macAddress, VlanId vlan)
Creates new Interface with the provided configuration.
Parameters
connectPoint the connect point this interface maps to
ipAddresses Set of IP addresses
macAddress MAC address
vlan VLAN ID
Definition at line 51 of file Interface.java.
References org.onosproject.incubator.net.intf.Interface.vlan().
Referenced by org.onosproject.incubator.net.intf.Interface.equals().
Member Function Documentation
ConnectPoint org.onosproject.incubator.net.intf.Interface.connectPoint ()
Retrieves the connection point that this interface maps to.
Returns
the connection point
Definition at line 65 of file Interface.java.
Referenced by org.onosproject.incubator.net.intf.Interface.equals(), org.onosproject.incubator.net.intf.Interface.hashCode(), and org.onosproject.incubator.net.intf.Interface.toString().
boolean org.onosproject.incubator.net.intf.Interface.equals (Object other)
Definition at line 97 of file Interface.java.
References org.onosproject.incubator.net.intf.Interface.connectPoint(), org.onosproject.incubator.net.intf.Interface.Interface(), org.onosproject.incubator.net.intf.Interface.ipAddresses(), and org.onosproject.incubator.net.intf.Interface.vlan().
int org.onosproject.incubator.net.intf.Interface.hashCode ()
Definition at line 111 of file Interface.java.
References org.onosproject.incubator.net.intf.Interface.connectPoint(), org.onosproject.incubator.net.intf.Interface.ipAddresses(), and org.onosproject.incubator.net.intf.Interface.vlan().
Set<InterfaceIpAddress> org.onosproject.incubator.net.intf.Interface.ipAddresses ()
Retrieves the set of IP addresses that are assigned to the interface.
Returns
the set of interface IP addresses
Definition at line 74 of file Interface.java.
Referenced by org.onosproject.incubator.net.intf.Interface.equals(), org.onosproject.incubator.net.intf.Interface.hashCode(), and org.onosproject.incubator.net.intf.Interface.toString().
MacAddress org.onosproject.incubator.net.intf.Interface.mac ()
Retrieves the MAC address that is assigned to the interface.
Returns
the MAC address
Definition at line 83 of file Interface.java.
Referenced by org.onosproject.incubator.net.config.basics.InterfaceConfig.addInterface().
String org.onosproject.incubator.net.intf.Interface.toString ()
Definition at line 116 of file Interface.java.
References org.onosproject.incubator.net.intf.Interface.connectPoint(), org.onosproject.incubator.net.intf.Interface.ipAddresses(), and org.onosproject.incubator.net.intf.Interface.vlan().
VlanId org.onosproject.incubator.net.intf.Interface.vlan ()
Retrieves the VLAN ID that is assigned to the interface.
Returns
the VLAN ID
Definition at line 92 of file Interface.java.
Referenced by org.onosproject.incubator.net.intf.Interface.equals(), org.onosproject.incubator.net.intf.Interface.hashCode(), org.onosproject.incubator.net.intf.Interface.Interface(), and org.onosproject.incubator.net.intf.Interface.toString().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/intf/Interface.java