onos: org.onosproject.cfg.ConfigProperty Class Reference
org.onosproject.cfg.ConfigProperty Class Reference
Component configuration property.
Classes
enum Type
Representation of the type of property value.
Public Member Functions
String name ()
Returns the property name.
Type type ()
Returns the property type.
String description ()
Returns the property description.
String defaultValue ()
Returns the property default value as a string.
String value ()
Returns the property value as a string.
boolean isSet ()
Indicates whether the property is set or whether it assumes its default value.
String asString ()
Returns the property value as a string.
int asInteger ()
Returns the property value as an integer.
long asLong ()
Returns the property value as a long.
float asFloat ()
Returns the property value as a float.
double asDouble ()
Returns the property value as a double.
boolean asBoolean ()
Returns the property value as a boolean.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static ConfigProperty defineProperty (String name, Type type, String defaultValue, String description)
Creates a new configuration property with its default value.
static ConfigProperty setProperty (ConfigProperty property, String newValue)
Creates a new configuration property as a copy of an existing one, but with a new value.
static ConfigProperty resetProperty (ConfigProperty property)
Creates a new configuration property as a copy of an existing one, but without a specific value, thus making it take its default value.
Detailed Description
Component configuration property.
Definition at line 28 of file ConfigProperty.java.
Member Function Documentation
boolean org.onosproject.cfg.ConfigProperty.asBoolean ()
Returns the property value as a boolean.
Returns
string value
Definition at line 241 of file ConfigProperty.java.
References org.onosproject.cfg.ConfigProperty.Type.BOOLEAN, org.onosproject.cfg.ConfigProperty.type(), and org.onosproject.cfg.ConfigProperty.value().
Referenced by org.onosproject.cfg.ConfigPropertyTest.asBoolean().
double org.onosproject.cfg.ConfigProperty.asDouble ()
Returns the property value as a double.
Returns
double value
Definition at line 231 of file ConfigProperty.java.
References org.onosproject.cfg.ConfigProperty.Type.DOUBLE, org.onosproject.cfg.ConfigProperty.Type.FLOAT, org.onosproject.cfg.ConfigProperty.type(), and org.onosproject.cfg.ConfigProperty.value().
Referenced by org.onosproject.cfg.ConfigPropertyTest.asDouble(), and org.onosproject.cfg.ConfigPropertyTest.asFloat().
float org.onosproject.cfg.ConfigProperty.asFloat ()
Returns the property value as a float.
Returns
float value
Definition at line 221 of file ConfigProperty.java.
References org.onosproject.cfg.ConfigProperty.Type.FLOAT, org.onosproject.cfg.ConfigProperty.type(), and org.onosproject.cfg.ConfigProperty.value().
Referenced by org.onosproject.cfg.ConfigPropertyTest.asFloat().
int org.onosproject.cfg.ConfigProperty.asInteger ()
Returns the property value as an integer.
Returns
integer value
Definition at line 201 of file ConfigProperty.java.
References org.onosproject.cfg.ConfigProperty.Type.INTEGER, org.onosproject.cfg.ConfigProperty.type(), and org.onosproject.cfg.ConfigProperty.value().
Referenced by org.onosproject.cfg.ConfigPropertyTest.asInteger().
long org.onosproject.cfg.ConfigProperty.asLong ()
Returns the property value as a long.
Returns
long value
Definition at line 211 of file ConfigProperty.java.
References org.onosproject.cfg.ConfigProperty.Type.INTEGER, org.onosproject.cfg.ConfigProperty.Type.LONG, org.onosproject.cfg.ConfigProperty.type(), and org.onosproject.cfg.ConfigProperty.value().
Referenced by org.onosproject.cfg.ConfigPropertyTest.asInteger(), and org.onosproject.cfg.ConfigPropertyTest.asLong().
String org.onosproject.cfg.ConfigProperty.asString ()
Returns the property value as a string.
Returns
string value
Definition at line 192 of file ConfigProperty.java.
References org.onosproject.cfg.ConfigProperty.value().
String org.onosproject.cfg.ConfigProperty.defaultValue ()
Returns the property default value as a string.
Returns
string default value
Definition at line 164 of file ConfigProperty.java.
Referenced by org.onosproject.cfg.ConfigProperty.toString().
static ConfigProperty org.onosproject.cfg.ConfigProperty.defineProperty (String name, Type type, String defaultValue, String description) static
Creates a new configuration property with its default value.
Parameters
name property name
type value type
defaultValue default value as a string
description property description
Returns
newly defined property
Definition at line 81 of file ConfigProperty.java.
String org.onosproject.cfg.ConfigProperty.description ()
Returns the property description.
Returns
string value
Definition at line 155 of file ConfigProperty.java.
Referenced by org.onosproject.cfg.ConfigProperty.toString().
boolean org.onosproject.cfg.ConfigProperty.equals (Object obj)
Equality is considered only on the basis of property name.
Definition at line 257 of file ConfigProperty.java.
References create-flow.name.
int org.onosproject.cfg.ConfigProperty.hashCode ()
Definition at line 247 of file ConfigProperty.java.
boolean org.onosproject.cfg.ConfigProperty.isSet ()
Indicates whether the property is set or whether it assumes its default value.
Returns
true if the property is set
Definition at line 183 of file ConfigProperty.java.
Referenced by org.onosproject.cfg.ConfigProperty.toString().
String org.onosproject.cfg.ConfigProperty.name ()
Returns the property name.
Returns
property name
Definition at line 137 of file ConfigProperty.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.cfg.ConfigProperty.toString().
static ConfigProperty org.onosproject.cfg.ConfigProperty.resetProperty (ConfigProperty property) static
Creates a new configuration property as a copy of an existing one, but without a specific value, thus making it take its default value.
Parameters
property property to be reset
Returns
newly reset property
Definition at line 107 of file ConfigProperty.java.
static ConfigProperty org.onosproject.cfg.ConfigProperty.setProperty (ConfigProperty property, String newValue) static
Creates a new configuration property as a copy of an existing one, but with a new value.
Parameters
property property to be changed
newValue new value as a string
Returns
newly updated property
Definition at line 95 of file ConfigProperty.java.
String org.onosproject.cfg.ConfigProperty.toString ()
Definition at line 269 of file ConfigProperty.java.
References org.onosproject.cfg.ConfigProperty.defaultValue(), org.onosproject.cfg.ConfigProperty.description(), org.onosproject.cfg.ConfigProperty.isSet(), org.onosproject.cfg.ConfigProperty.name(), org.onosproject.cfg.ConfigProperty.type(), and org.onosproject.cfg.ConfigProperty.value().
Type org.onosproject.cfg.ConfigProperty.type ()
Returns the property type.
Returns
property type
Definition at line 146 of file ConfigProperty.java.
Referenced by org.onosproject.cfg.ConfigProperty.asBoolean(), org.onosproject.cfg.ConfigProperty.asDouble(), org.onosproject.cfg.ConfigProperty.asFloat(), org.onosproject.cfg.ConfigProperty.asInteger(), org.onosproject.cfg.ConfigProperty.asLong(), and org.onosproject.cfg.ConfigProperty.toString().
String org.onosproject.cfg.ConfigProperty.value ()
Returns the property value as a string.
Returns
string value
Definition at line 173 of file ConfigProperty.java.
Referenced by org.onosproject.cfg.ConfigProperty.asBoolean(), org.onosproject.cfg.ConfigProperty.asDouble(), org.onosproject.cfg.ConfigProperty.asFloat(), org.onosproject.cfg.ConfigProperty.asInteger(), org.onosproject.cfg.ConfigProperty.asLong(), org.onosproject.cfg.ConfigProperty.asString(), and org.onosproject.cfg.ConfigProperty.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/cfg/ConfigProperty.java