onos: org.onosproject.net.flowobjective.DefaultForwardingObjective Class Reference
org.onosproject.net.flowobjective.DefaultForwardingObjective Class Reference
Default implementation of a forwarding objective.
Classes
class Builder
Public Member Functions
TrafficSelector selector ()
Obtain the selector for this objective.
Integer nextId ()
Obtain the traffic treatment for this objective.
TrafficTreatment treatment ()
A traffic treatment for this forwarding objective.
Flag flag ()
Obtain the type of this objective.
int id ()
An identifier for this objective.
int priority ()
The priority for this objective.
ApplicationId appId ()
The application which applied this objective.
int timeout ()
The timeout for this objective.
boolean permanent ()
Whether this objective is permanent.
Operation op ()
The type of operation for this objective.
Optional< ObjectiveContext > context ()
Obtains an optional context.
int hashCode ()
boolean equals (final Object obj)
Static Public Member Functions
static Builder builder ()
Returns a new builder.
Additional Inherited Members
Public Attributes inherited from org.onosproject.net.flowobjective.Objective
boolean DEFAULT_PERMANENT = true
int DEFAULT_TIMEOUT = 0
int DEFAULT_PRIORITY = 32768
Detailed Description
Default implementation of a forwarding objective.
Definition at line 34 of file DefaultForwardingObjective.java.
Member Function Documentation
ApplicationId org.onosproject.net.flowobjective.DefaultForwardingObjective.appId ()
The application which applied this objective.
Returns
an application id
Implements org.onosproject.net.flowobjective.Objective.
Definition at line 99 of file DefaultForwardingObjective.java.
Referenced by org.onosproject.net.flowobjective.DefaultForwardingObjective.hashCode().
static Builder org.onosproject.net.flowobjective.DefaultForwardingObjective.builder () static
Returns a new builder.
Returns
new builder
Definition at line 175 of file DefaultForwardingObjective.java.
Optional<ObjectiveContext> org.onosproject.net.flowobjective.DefaultForwardingObjective.context ()
Obtains an optional context.
Returns
optional; which will be empty if there is no context. Otherwise it will return the context.
Implements org.onosproject.net.flowobjective.Objective.
Definition at line 119 of file DefaultForwardingObjective.java.
boolean org.onosproject.net.flowobjective.DefaultForwardingObjective.equals (final Object obj)
Definition at line 141 of file DefaultForwardingObjective.java.
References org.onosproject.net.flowobjective.DefaultForwardingObjective.nextId(), org.onosproject.net.flowobjective.DefaultForwardingObjective.priority(), org.onosproject.net.flowobjective.DefaultForwardingObjective.selector(), and org.onosproject.net.flowobjective.DefaultForwardingObjective.treatment().
Flag org.onosproject.net.flowobjective.DefaultForwardingObjective.flag ()
Obtain the type of this objective.
Returns
a flag type
Implements org.onosproject.net.flowobjective.ForwardingObjective.
Definition at line 84 of file DefaultForwardingObjective.java.
Referenced by org.onosproject.net.flowobjective.DefaultForwardingObjective.hashCode().
int org.onosproject.net.flowobjective.DefaultForwardingObjective.hashCode ()
Definition at line 129 of file DefaultForwardingObjective.java.
References org.onosproject.net.flowobjective.DefaultForwardingObjective.appId(), org.onosproject.net.flowobjective.DefaultForwardingObjective.flag(), org.onosproject.net.flowobjective.DefaultForwardingObjective.nextId(), org.onosproject.net.flowobjective.DefaultForwardingObjective.op(), org.onosproject.net.flowobjective.DefaultForwardingObjective.permanent(), org.onosproject.net.flowobjective.DefaultForwardingObjective.priority(), org.onosproject.net.flowobjective.DefaultForwardingObjective.selector(), org.onosproject.net.flowobjective.DefaultForwardingObjective.timeout(), and org.onosproject.net.flowobjective.DefaultForwardingObjective.treatment().
int org.onosproject.net.flowobjective.DefaultForwardingObjective.id ()
An identifier for this objective.
Returns
an integer
Implements org.onosproject.net.flowobjective.Objective.
Definition at line 89 of file DefaultForwardingObjective.java.
Integer org.onosproject.net.flowobjective.DefaultForwardingObjective.nextId ()
Obtain the traffic treatment for this objective.
Mutually exclusive with 'treatment'.
Returns
an integer
Implements org.onosproject.net.flowobjective.ForwardingObjective.
Definition at line 73 of file DefaultForwardingObjective.java.
Referenced by org.onosproject.net.flowobjective.DefaultForwardingObjective.equals(), and org.onosproject.net.flowobjective.DefaultForwardingObjective.hashCode().
Operation org.onosproject.net.flowobjective.DefaultForwardingObjective.op ()
The type of operation for this objective.
Returns
an operation
Implements org.onosproject.net.flowobjective.Objective.
Definition at line 114 of file DefaultForwardingObjective.java.
Referenced by org.onosproject.net.flowobjective.DefaultForwardingObjective.hashCode().
boolean org.onosproject.net.flowobjective.DefaultForwardingObjective.permanent ()
Whether this objective is permanent.
Returns
a boolean
Implements org.onosproject.net.flowobjective.Objective.
Definition at line 109 of file DefaultForwardingObjective.java.
Referenced by org.onosproject.net.flowobjective.DefaultForwardingObjective.hashCode().
int org.onosproject.net.flowobjective.DefaultForwardingObjective.priority ()
The priority for this objective.
Returns
an integer
Implements org.onosproject.net.flowobjective.Objective.
Definition at line 94 of file DefaultForwardingObjective.java.
Referenced by org.onosproject.net.flowobjective.DefaultForwardingObjective.equals(), and org.onosproject.net.flowobjective.DefaultForwardingObjective.hashCode().
TrafficSelector org.onosproject.net.flowobjective.DefaultForwardingObjective.selector ()
Obtain the selector for this objective.
Returns
a traffic selector
Implements org.onosproject.net.flowobjective.ForwardingObjective.
Definition at line 68 of file DefaultForwardingObjective.java.
Referenced by org.onosproject.net.flowobjective.DefaultForwardingObjective.equals(), and org.onosproject.net.flowobjective.DefaultForwardingObjective.hashCode().
int org.onosproject.net.flowobjective.DefaultForwardingObjective.timeout ()
The timeout for this objective.
Returns
an integer
Implements org.onosproject.net.flowobjective.Objective.
Definition at line 104 of file DefaultForwardingObjective.java.
Referenced by org.onosproject.net.flowobjective.DefaultForwardingObjective.hashCode().
TrafficTreatment org.onosproject.net.flowobjective.DefaultForwardingObjective.treatment ()
A traffic treatment for this forwarding objective.
Mutually exclusive with a nextId.
Returns
a traffic treatment
Implements org.onosproject.net.flowobjective.ForwardingObjective.
Definition at line 78 of file DefaultForwardingObjective.java.
Referenced by org.onosproject.net.flowobjective.DefaultForwardingObjective.equals(), and org.onosproject.net.flowobjective.DefaultForwardingObjective.hashCode().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flowobjective/DefaultForwardingObjective.java