onos: org.onosproject.ovsdb.rfc.notation.Column Class Reference
org.onosproject.ovsdb.rfc.notation.Column Class Reference
Column is the basic element of the OpenVswitch database.
Public Member Functions
Column (String columnName, Object obj)
Column constructor.
Object data ()
Returns column data.
String columnName ()
Returns columnName.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Column is the basic element of the OpenVswitch database.
Definition at line 26 of file Column.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.notation.Column.Column (String columnName, Object obj)
Column constructor.
Parameters
columnName the column name
obj the data of the column
Definition at line 35 of file Column.java.
References org.onosproject.ovsdb.rfc.notation.Column.columnName().
Referenced by org.onosproject.ovsdb.rfc.notation.Column.equals().
Member Function Documentation
String org.onosproject.ovsdb.rfc.notation.Column.columnName ()
Returns columnName.
Returns
columnName
Definition at line 54 of file Column.java.
Referenced by org.onosproject.ovsdb.rfc.notation.Column.Column(), org.onosproject.ovsdb.rfc.notation.Column.hashCode(), and org.onosproject.ovsdb.rfc.notation.Column.toString().
Object org.onosproject.ovsdb.rfc.notation.Column.data ()
Returns column data.
Returns
column data
Definition at line 46 of file Column.java.
Referenced by org.onosproject.ovsdb.rfc.notation.Column.hashCode(), and org.onosproject.ovsdb.rfc.notation.Column.toString().
boolean org.onosproject.ovsdb.rfc.notation.Column.equals (Object obj)
Definition at line 64 of file Column.java.
References org.onosproject.ovsdb.rfc.notation.Column.Column().
int org.onosproject.ovsdb.rfc.notation.Column.hashCode ()
Definition at line 59 of file Column.java.
References org.onosproject.ovsdb.rfc.notation.Column.columnName(), and org.onosproject.ovsdb.rfc.notation.Column.data().
String org.onosproject.ovsdb.rfc.notation.Column.toString ()
Definition at line 77 of file Column.java.
References org.onosproject.ovsdb.rfc.notation.Column.columnName(), and org.onosproject.ovsdb.rfc.notation.Column.data().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/notation/Column.java