onos: org.onosproject.net.AbstractAnnotated Class Reference
org.onosproject.net.AbstractAnnotated Class Reference
Base abstraction of an annotated entity.
Public Member Functions
Annotations annotations ()
Returns the key/value annotations.
Protected Member Functions
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Base abstraction of an annotated entity.
Definition at line 24 of file AbstractAnnotated.java.
Constructor & Destructor Documentation
org.onosproject.net.AbstractAnnotated.AbstractAnnotated () protected
Definition at line 29 of file AbstractAnnotated.java.
org.onosproject.net.AbstractAnnotated.AbstractAnnotated (Annotations... annotations) protected
Creates a new entity, annotated with the specified annotations.
Parameters
annotations optional key/value annotations map
Definition at line 38 of file AbstractAnnotated.java.
References org.onosproject.net.AbstractAnnotated.annotations().
Member Function Documentation
Annotations org.onosproject.net.AbstractAnnotated.annotations ()
Returns the key/value annotations.
Returns
key/value annotations
Implements org.onosproject.net.Annotated.
Definition at line 44 of file AbstractAnnotated.java.
Referenced by org.onosproject.net.AbstractAnnotated.AbstractAnnotated(), org.onosproject.net.AbstractElement.AbstractElement(), org.onosproject.net.AbstractModel.AbstractModel(), org.onosproject.net.DefaultDevice.DefaultDevice(), org.onosproject.net.DefaultEdgeLink.DefaultEdgeLink(), org.onosproject.net.DefaultHost.DefaultHost(), org.onosproject.net.DefaultLink.DefaultLink(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.DefaultOpticalTunnelEndPoint(), org.onosproject.net.DefaultPath.DefaultPath(), org.onosproject.net.DefaultPort.DefaultPort(), org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel(), org.onosproject.net.OduCltPort.equals(), org.onosproject.net.OchPort.equals(), org.onosproject.net.OmsPort.equals(), org.onosproject.net.OduCltPort.hashCode(), org.onosproject.net.OchPort.hashCode(), org.onosproject.net.DefaultPort.hashCode(), org.onosproject.net.OmsPort.hashCode(), org.onosproject.net.OchPort.OchPort(), org.onosproject.net.OduCltPort.OduCltPort(), org.onosproject.net.OmsPort.OmsPort(), and org.onosproject.incubator.net.tunnel.TunnelSubscription.TunnelSubscription().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/AbstractAnnotated.java