onos: org.onosproject.store.trivial.SimpleMastershipStoreTest Class Reference
org.onosproject.store.trivial.SimpleMastershipStoreTest Class Reference
Test for the simple MastershipStore implementation.
Public Member Functions
void setUp () throws Exception
void tearDown () throws Exception
void getRole ()
void getMaster ()
void setMaster ()
void getDevices ()
void getTermFor ()
void requestRole ()
void unsetMaster ()
Detailed Description
Test for the simple MastershipStore implementation.
Definition at line 43 of file SimpleMastershipStoreTest.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleMastershipStoreTest.getDevices ()
Definition at line 109 of file SimpleMastershipStoreTest.java.
References org.onosproject.store.trivial.SimpleMastershipStore.getDevices().
void org.onosproject.store.trivial.SimpleMastershipStoreTest.getMaster ()
Definition at line 87 of file SimpleMastershipStoreTest.java.
References org.onosproject.store.trivial.SimpleMastershipStore.getMaster(), and org.onosproject.store.trivial.SimpleMastershipStore.getRole().
void org.onosproject.store.trivial.SimpleMastershipStoreTest.getRole ()
Definition at line 67 of file SimpleMastershipStoreTest.java.
References org.onosproject.store.trivial.SimpleMastershipStore.getRole().
void org.onosproject.store.trivial.SimpleMastershipStoreTest.getTermFor ()
Definition at line 119 of file SimpleMastershipStoreTest.java.
References org.onosproject.mastership.MastershipTerm.of().
void org.onosproject.store.trivial.SimpleMastershipStoreTest.requestRole ()
Definition at line 130 of file SimpleMastershipStoreTest.java.
References org.onosproject.store.trivial.SimpleMastershipStore.requestRole().
void org.onosproject.store.trivial.SimpleMastershipStoreTest.setMaster ()
Definition at line 94 of file SimpleMastershipStoreTest.java.
References org.onosproject.store.trivial.SimpleMastershipStore.getRole(), and org.onosproject.store.trivial.SimpleMastershipStore.setMaster().
void org.onosproject.store.trivial.SimpleMastershipStoreTest.setUp () throws Exception
Definition at line 56 of file SimpleMastershipStoreTest.java.
void org.onosproject.store.trivial.SimpleMastershipStoreTest.tearDown () throws Exception
Definition at line 62 of file SimpleMastershipStoreTest.java.
void org.onosproject.store.trivial.SimpleMastershipStoreTest.unsetMaster ()
Definition at line 149 of file SimpleMastershipStoreTest.java.
References org.onosproject.store.trivial.SimpleMastershipStore.backups, org.onosproject.store.trivial.SimpleMastershipStore.masterMap, org.onosproject.store.trivial.SimpleMastershipStore.setStandby(), and org.onosproject.store.trivial.SimpleMastershipStore.termMap.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleMastershipStoreTest.java