onos: org.onosproject.bgpio.types.NextHop Class Reference
org.onosproject.bgpio.types.NextHop Class Reference
Implementation of NextHop BGP Path Attribute.
Public Member Functions
NextHop (Ip4Address nextHop)
Constructor to initialize parameters.
boolean isNextHopSet ()
Returns whether next hop is present.
Ip4Address nextHop ()
Return nexthop address.
short getType ()
Returns the Type of BGP Message.
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
int hashCode ()
boolean equals (Object obj)
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static NextHop read (ChannelBuffer cb) throws BgpParseException
Reads from ChannelBuffer and parses NextHop.
Static Public Attributes
static final byte NEXTHOP_TYPE = 3
Detailed Description
Implementation of NextHop BGP Path Attribute.
Definition at line 33 of file NextHop.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.NextHop.NextHop (Ip4Address nextHop)
Constructor to initialize parameters.
Parameters
nextHop nextHop address
Definition at line 44 of file NextHop.java.
References org.onosproject.bgpio.types.NextHop.nextHop().
Referenced by org.onosproject.bgpio.types.NextHop.equals(), and org.onosproject.bgpio.types.NextHop.read().
Member Function Documentation
int org.onosproject.bgpio.types.NextHop.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 135 of file NextHop.java.
boolean org.onosproject.bgpio.types.NextHop.equals (Object obj)
Definition at line 116 of file NextHop.java.
References org.onosproject.bgpio.types.NextHop.NextHop(), and org.onosproject.bgpio.types.NextHop.nextHop().
short org.onosproject.bgpio.types.NextHop.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 100 of file NextHop.java.
References org.onosproject.bgpio.types.NextHop.NEXTHOP_TYPE.
int org.onosproject.bgpio.types.NextHop.hashCode ()
Definition at line 111 of file NextHop.java.
References org.onosproject.bgpio.types.NextHop.nextHop().
boolean org.onosproject.bgpio.types.NextHop.isNextHopSet ()
Returns whether next hop is present.
Returns
whether next hop is present
Definition at line 54 of file NextHop.java.
Ip4Address org.onosproject.bgpio.types.NextHop.nextHop ()
Return nexthop address.
Returns
nexthop address
Definition at line 95 of file NextHop.java.
Referenced by org.onosproject.bgpio.types.NextHop.equals(), org.onosproject.bgpio.types.NextHop.hashCode(), org.onosproject.bgpio.types.NextHop.NextHop(), org.onosproject.bgpio.types.NextHop.read(), and org.onosproject.bgpio.types.NextHop.toString().
static NextHop org.onosproject.bgpio.types.NextHop.read (ChannelBuffer cb) throws BgpParseException static
Reads from ChannelBuffer and parses NextHop.
Parameters
cb ChannelBuffer
Returns
object of NextHop
Exceptions
BgpParseException while parsing nexthop attribute
Definition at line 65 of file NextHop.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_FLAGS_ERROR, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.NextHop.NextHop(), org.onosproject.bgpio.types.NextHop.nextHop(), org.onosproject.bgpio.util.Constants.TYPE_AND_LEN_AS_BYTE, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.NextHop.toString ()
Definition at line 128 of file NextHop.java.
References org.onosproject.bgpio.types.NextHop.nextHop().
int org.onosproject.bgpio.types.NextHop.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 105 of file NextHop.java.
Member Data Documentation
final byte org.onosproject.bgpio.types.NextHop.NEXTHOP_TYPE = 3 static
Definition at line 34 of file NextHop.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.checkMandatoryAttr(), and org.onosproject.bgpio.types.NextHop.getType().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/NextHop.java