onos: org.onosproject.driver.pipeline.PicaPipeline Class Reference
org.onosproject.driver.pipeline.PicaPipeline Class Reference
Pica pipeline handler.
Public Member Functions
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filteringObjective)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Static Protected Attributes
static final int IP_UNICAST_TABLE = 252
static final int ACL_TABLE = 0
Detailed Description
Pica pipeline handler.
Definition at line 69 of file PicaPipeline.java.
Member Function Documentation
void org.onosproject.driver.pipeline.PicaPipeline.filter (FilteringObjective filterObjective)
Installs the filtering rules onto the device.
Parameters
filterObjective a filtering objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 113 of file PicaPipeline.java.
References org.onosproject.net.flowobjective.Objective.op(), org.onosproject.net.flowobjective.FilteringObjective.type(), and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
Referenced by org.onosproject.driver.pipeline.PicaPipeline.forward().
void org.onosproject.driver.pipeline.PicaPipeline.forward (ForwardingObjective forwardObjective)
Installs the forwarding rules onto the device.
Parameters
forwardObjective a forwarding objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 124 of file PicaPipeline.java.
References org.onosproject.driver.pipeline.PicaPipeline.filter(), org.onosproject.net.flowobjective.ObjectiveError.FLOWINSTALLATIONFAILED, org.onosproject.net.flowobjective.Objective.op(), and org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN.
void org.onosproject.driver.pipeline.PicaPipeline.init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
Parameters
deviceId the deviceId
context processing context
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 96 of file PicaPipeline.java.
void org.onosproject.driver.pipeline.PicaPipeline.next (NextObjective nextObjective)
Installs the next hop elements into the device.
Parameters
nextObjective a next objectives
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 161 of file PicaPipeline.java.
References org.onosproject.net.flow.TrafficTreatment.allInstructions(), org.onosproject.net.flowobjective.ObjectiveError.BADPARAMS, org.onosproject.net.flow.instructions.L2ModificationInstruction.subtype(), org.onosproject.net.flowobjective.NextObjective.type(), org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN, and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
Member Data Documentation
final int org.onosproject.driver.pipeline.PicaPipeline.ACL_TABLE = 0 static protected
Definition at line 72 of file PicaPipeline.java.
final int org.onosproject.driver.pipeline.PicaPipeline.IP_UNICAST_TABLE = 252 static protected
Definition at line 71 of file PicaPipeline.java.
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/pipeline/PicaPipeline.java