onos: org.onosproject.bgpio.types.MpUnReachNlri Class Reference
org.onosproject.bgpio.types.MpUnReachNlri Class Reference
Provides Implementation of MpUnReach Nlri BGP Path Attribute.
Public Member Functions
MpUnReachNlri (List< BgpLSNlri > mpUnReachNlri, short afi, byte safi, int length)
Constructor to initialize parameters.
short getType ()
Returns the Type of BGP Message.
byte safi ()
Returns SAFI.
short afi ()
Returns AFI.
List< BgpLSNlri > mpUnReachNlri ()
Returns list of MpUnReach Nlri.
boolean isMpUnReachNlriSet ()
Returns whether MpReachNlri is present.
int mpUnReachNlriLen ()
Returns length of MpUnReach.
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static MpUnReachNlri read (ChannelBuffer cb) throws BgpParseException
Reads from ChannelBuffer and parses MpUnReachNlri.
Static Public Attributes
static final byte MPUNREACHNLRI_TYPE = 15
static final byte LINK_NLRITYPE = 2
Detailed Description
Provides Implementation of MpUnReach Nlri BGP Path Attribute.
Definition at line 38 of file MpUnReachNlri.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.MpUnReachNlri.MpUnReachNlri (List< BgpLSNlri > mpUnReachNlri, short afi, byte safi, int length)
Constructor to initialize parameters.
Parameters
mpUnReachNlri MpUnReach Nlri attribute
afi address family identifier
safi subsequent address family identifier
length of MpUnReachNlri
Definition at line 58 of file MpUnReachNlri.java.
References org.onosproject.bgpio.types.MpUnReachNlri.afi(), org.onosproject.bgpio.types.MpUnReachNlri.mpUnReachNlri(), and org.onosproject.bgpio.types.MpUnReachNlri.safi().
Referenced by org.onosproject.bgpio.types.MpUnReachNlri.read().
Member Function Documentation
short org.onosproject.bgpio.types.MpUnReachNlri.afi ()
Returns AFI.
Returns
AFI
Definition at line 158 of file MpUnReachNlri.java.
Referenced by org.onosproject.bgpio.types.MpUnReachNlri.MpUnReachNlri(), org.onosproject.bgpio.types.MpUnReachNlri.read(), and org.onosproject.bgpio.types.MpUnReachNlri.toString().
int org.onosproject.bgpio.types.MpUnReachNlri.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 196 of file MpUnReachNlri.java.
short org.onosproject.bgpio.types.MpUnReachNlri.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 140 of file MpUnReachNlri.java.
References org.onosproject.bgpio.types.MpUnReachNlri.MPUNREACHNLRI_TYPE.
boolean org.onosproject.bgpio.types.MpUnReachNlri.isMpUnReachNlriSet ()
Returns whether MpReachNlri is present.
Returns
whether MpReachNlri is present
Definition at line 176 of file MpUnReachNlri.java.
List<BgpLSNlri> org.onosproject.bgpio.types.MpUnReachNlri.mpUnReachNlri ()
Returns list of MpUnReach Nlri.
Returns
list of MpUnReach Nlri
Definition at line 167 of file MpUnReachNlri.java.
Referenced by org.onosproject.bgpio.types.MpUnReachNlri.MpUnReachNlri(), org.onosproject.bgpio.types.MpUnReachNlri.read(), and org.onosproject.bgpio.types.MpUnReachNlri.toString().
int org.onosproject.bgpio.types.MpUnReachNlri.mpUnReachNlriLen ()
Returns length of MpUnReach.
Returns
length of MpUnReach
Definition at line 185 of file MpUnReachNlri.java.
References find-link-in-cluster.length.
static MpUnReachNlri org.onosproject.bgpio.types.MpUnReachNlri.read (ChannelBuffer cb) throws BgpParseException static
Reads from ChannelBuffer and parses MpUnReachNlri.
Parameters
cb ChannelBuffer
Returns
object of MpUnReachNlri
Exceptions
BgpParseException while parsing MpUnReachNlri
Definition at line 74 of file MpUnReachNlri.java.
References org.onosproject.bgpio.types.MpUnReachNlri.afi(), org.onosproject.bgpio.util.Constants.AFI_VALUE, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_FLAGS_ERROR, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.util.Validation.getLength(), org.onosproject.bgpio.types.MpUnReachNlri.MpUnReachNlri(), org.onosproject.bgpio.types.MpUnReachNlri.mpUnReachNlri(), org.onosproject.bgpio.types.MpUnReachNlri.safi(), org.onosproject.bgpio.util.Constants.SAFI_VALUE, org.onosproject.bgpio.util.Constants.TYPE_AND_LEN_AS_BYTE, org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR, and org.onosproject.bgpio.util.Constants.VPN_SAFI_VALUE.
byte org.onosproject.bgpio.types.MpUnReachNlri.safi ()
Returns SAFI.
Returns
SAFI
Definition at line 149 of file MpUnReachNlri.java.
Referenced by org.onosproject.bgpio.types.MpUnReachNlri.MpUnReachNlri(), org.onosproject.bgpio.types.MpUnReachNlri.read(), and org.onosproject.bgpio.types.MpUnReachNlri.toString().
String org.onosproject.bgpio.types.MpUnReachNlri.toString ()
Definition at line 202 of file MpUnReachNlri.java.
References org.onosproject.bgpio.types.MpUnReachNlri.afi(), org.onosproject.bgpio.types.MpUnReachNlri.mpUnReachNlri(), and org.onosproject.bgpio.types.MpUnReachNlri.safi().
int org.onosproject.bgpio.types.MpUnReachNlri.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 190 of file MpUnReachNlri.java.
Member Data Documentation
final byte org.onosproject.bgpio.types.MpUnReachNlri.LINK_NLRITYPE = 2 static
Definition at line 42 of file MpUnReachNlri.java.
final byte org.onosproject.bgpio.types.MpUnReachNlri.MPUNREACHNLRI_TYPE = 15 static
Definition at line 41 of file MpUnReachNlri.java.
Referenced by org.onosproject.bgpio.types.MpUnReachNlri.getType().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/MpUnReachNlri.java