onos: org.onlab.graph.AbstractGraphPathSearchTest Class Reference
org.onlab.graph.AbstractGraphPathSearchTest Class Reference abstract
Base for all graph search tests.
Public Member Functions
void noSuchSourceArgument ()
void nullGraphArgument ()
void nullSourceArgument ()
void samenessThreshold ()
Protected Member Functions
abstract
AbstractGraphPathSearch
< TestVertex, TestEdge > graphSearch ()
Creates a test-specific graph search to exercise.
Protected Member Functions inherited from org.onlab.graph.GraphTest
void printPaths (Set< Path< TestVertex, TestEdge >> paths)
Set< TestVertex > vertexes ()
Set< TestEdge > edges ()
Additional Inherited Members
Protected Attributes inherited from org.onlab.graph.GraphTest
Graph< TestVertex, TestEdge > graph
EdgeWeight< TestVertex, TestEdge > weight
Detailed Description
Base for all graph search tests.
Definition at line 26 of file AbstractGraphPathSearchTest.java.
Member Function Documentation
abstract AbstractGraphPathSearch<TestVertex, TestEdge> org.onlab.graph.AbstractGraphPathSearchTest.graphSearch () protected pure virtual
Creates a test-specific graph search to exercise.
Returns
graph search
Implemented in org.onlab.graph.SrlgGraphSearchTest, org.onlab.graph.DepthFirstSearchTest, org.onlab.graph.DijkstraGraphSearchTest, org.onlab.graph.SuurballeGraphSearchTest, org.onlab.graph.BellmanFordGraphSearchTest, and org.onlab.graph.BreadthFirstSearchTest.
Referenced by org.onlab.graph.AbstractGraphPathSearchTest.noSuchSourceArgument(), org.onlab.graph.AbstractGraphPathSearchTest.nullGraphArgument(), org.onlab.graph.AbstractGraphPathSearchTest.nullSourceArgument(), and org.onlab.graph.AbstractGraphPathSearchTest.samenessThreshold().
void org.onlab.graph.AbstractGraphPathSearchTest.noSuchSourceArgument ()
Definition at line 36 of file AbstractGraphPathSearchTest.java.
References org.onlab.graph.AbstractGraphPathSearchTest.graphSearch(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.AbstractGraphPathSearchTest.nullGraphArgument ()
Definition at line 43 of file AbstractGraphPathSearchTest.java.
References org.onlab.graph.AbstractGraphPathSearchTest.graphSearch(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.AbstractGraphPathSearchTest.nullSourceArgument ()
Definition at line 48 of file AbstractGraphPathSearchTest.java.
References org.onlab.graph.AbstractGraphPathSearchTest.graphSearch(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.AbstractGraphPathSearchTest.samenessThreshold ()
Definition at line 55 of file AbstractGraphPathSearchTest.java.
References org.onlab.graph.AbstractGraphPathSearchTest.graphSearch().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/graph/AbstractGraphPathSearchTest.java