onos: org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore Class Reference
org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore Class Reference
Manages label resources using copycat.
Public Member Functions
void activate ()
void deactivate ()
boolean createDevicePool (DeviceId deviceId, LabelResourceId beginLabel, LabelResourceId endLabel)
Creates a label resource of some device id from begin label to end label.
boolean createGlobalPool (LabelResourceId beginLabel, LabelResourceId endLabel)
Creates the global label resource pool.
boolean destroyDevicePool (DeviceId deviceId)
Destroys a label resource pool of a specific device id.
Collection< LabelResource > applyFromDevicePool (DeviceId deviceId, long applyNum)
Returns labels from resource pool by a specific device id.
boolean releaseToDevicePool (Multimap< DeviceId, LabelResource > release)
Releases unused labels to device pools .
boolean isDevicePoolFull (DeviceId deviceId)
Judges if the pool of a specific device id is full.
long getFreeNumOfDevicePool (DeviceId deviceId)
Returns the unused label number of a label resource pool by a specific device id.
LabelResourcePool getDeviceLabelResourcePool (DeviceId deviceId)
Returns the label resource pool by a specific device id.
boolean destroyGlobalPool ()
Destroys a the global label resource pool.
Collection< LabelResource > applyFromGlobalPool (long applyNum)
Returns labels from the global label resource pool.
boolean releaseToGlobalPool (Set< LabelResourceId > release)
Releases unused labels to the global resource pool.
boolean isGlobalPoolFull ()
Judges if the global resource pool is full.
long getFreeNumOfGlobalPool ()
Returns the unused number of a global label resource pool.
LabelResourcePool getGlobalLabelResourcePool ()
Returns the global label resource pool.
Protected Attributes
StorageService storageService
MastershipService mastershipService
ClusterCommunicationService clusterCommunicator
ClusterService clusterService
DeviceService deviceService
Detailed Description
Manages label resources using copycat.
Definition at line 75 of file DistributedLabelResourceStore.java.
Member Function Documentation
void org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.activate ()
Definition at line 117 of file DistributedLabelResourceStore.java.
References find-flow.deviceId, org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_APPLY, org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_CREATED, org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_DESTROYED, and org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_RELEASE.
Collection<LabelResource> org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.applyFromDevicePool (DeviceId deviceId, long applyNum)
Returns labels from resource pool by a specific device id.
Parameters
deviceId device identifier
applyNum the applying number
Returns
collection of applying labels
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 303 of file DistributedLabelResourceStore.java.
References org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.clusterCommunicator, org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.clusterService, find-flow.deviceId, org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.deviceService, org.onosproject.cluster.NodeId.equals(), org.onosproject.net.device.DeviceService.getDevice(), org.onosproject.cluster.ClusterService.getLocalNode(), and org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_APPLY.
Collection<LabelResource> org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.applyFromGlobalPool (long applyNum)
Returns labels from the global label resource pool.
Parameters
applyNum apply the number of labels
Returns
collection of labels
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 494 of file DistributedLabelResourceStore.java.
References org.onosproject.net.DeviceId.deviceId().
boolean org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.createDevicePool (DeviceId deviceId, LabelResourceId beginLabel, LabelResourceId endLabel)
Creates a label resource of some device id from begin label to end label.
Parameters
deviceId device identifier
beginLabel represents for the first label id in the range of label pool
endLabel represents for the last label id in the range of label pool
Returns
success or fail
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 203 of file DistributedLabelResourceStore.java.
References org.onosproject.net.DeviceId.toString().
boolean org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.createGlobalPool (LabelResourceId beginLabel, LabelResourceId endLabel)
Creates the global label resource pool.
Parameters
beginLabel represents for the first label id in the range of label pool
endLabel represents for the last label id in the range of label pool
Returns
success or fail
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 213 of file DistributedLabelResourceStore.java.
void org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.deactivate ()
Definition at line 189 of file DistributedLabelResourceStore.java.
References org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_APPLY, org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_CREATED, org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_DESTROYED, and org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_RELEASE.
boolean org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.destroyDevicePool (DeviceId deviceId)
Destroys a label resource pool of a specific device id.
Parameters
deviceId device identifier
Returns
success or fail
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 262 of file DistributedLabelResourceStore.java.
References org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.clusterCommunicator, org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.clusterService, find-flow.deviceId, org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.deviceService, org.onosproject.cluster.NodeId.equals(), org.onosproject.net.device.DeviceService.getDevice(), org.onosproject.cluster.ClusterService.getLocalNode(), and org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_DESTROYED.
boolean org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.destroyGlobalPool ()
Destroys a the global label resource pool.
Returns
success or fail
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 488 of file DistributedLabelResourceStore.java.
LabelResourcePool org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.getDeviceLabelResourcePool (DeviceId deviceId)
Returns the label resource pool by a specific device id.
Parameters
deviceId device identifier
Returns
the device label resource pool
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 482 of file DistributedLabelResourceStore.java.
References find-flow.deviceId.
long org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.getFreeNumOfDevicePool (DeviceId deviceId)
Returns the unused label number of a label resource pool by a specific device id.
Parameters
deviceId device identifier
Returns
number of unused labels
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 471 of file DistributedLabelResourceStore.java.
References find-flow.deviceId.
long org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.getFreeNumOfGlobalPool ()
Returns the unused number of a global label resource pool.
Returns
number of unused labels
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 524 of file DistributedLabelResourceStore.java.
LabelResourcePool org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.getGlobalLabelResourcePool ()
Returns the global label resource pool.
Returns
the global label resource pool
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 530 of file DistributedLabelResourceStore.java.
boolean org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.isDevicePoolFull (DeviceId deviceId)
Judges if the pool of a specific device id is full.
Parameters
deviceId device identifier
Returns
yes or no
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 461 of file DistributedLabelResourceStore.java.
References find-flow.deviceId.
boolean org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.isGlobalPoolFull ()
Judges if the global resource pool is full.
Returns
yes or no
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 518 of file DistributedLabelResourceStore.java.
boolean org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.releaseToDevicePool (Multimap< DeviceId, LabelResource > release)
Releases unused labels to device pools .
Parameters
release the collection of releasing labels
Returns
success or fail
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 380 of file DistributedLabelResourceStore.java.
References org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.clusterCommunicator, org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.clusterService, find-flow.deviceId, org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.deviceService, org.onosproject.cluster.NodeId.equals(), org.onosproject.net.device.DeviceService.getDevice(), org.onosproject.cluster.ClusterService.getLocalNode(), and org.onosproject.incubator.store.resource.impl.LabelResourceMessageSubjects.LABEL_POOL_RELEASE.
boolean org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.releaseToGlobalPool (Set< LabelResourceId > release)
Releases unused labels to the global resource pool.
Parameters
release release the collection of releasing labels
Returns
success or fail
Implements org.onosproject.incubator.net.resource.label.LabelResourceStore.
Definition at line 502 of file DistributedLabelResourceStore.java.
References org.onosproject.net.DeviceId.deviceId().
Member Data Documentation
ClusterCommunicationService org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.clusterCommunicator protected
Definition at line 93 of file DistributedLabelResourceStore.java.
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.applyFromDevicePool(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.destroyDevicePool(), and org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.releaseToDevicePool().
ClusterService org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.clusterService protected
Definition at line 96 of file DistributedLabelResourceStore.java.
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.applyFromDevicePool(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.destroyDevicePool(), and org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.releaseToDevicePool().
DeviceService org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.deviceService protected
Definition at line 99 of file DistributedLabelResourceStore.java.
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.applyFromDevicePool(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.destroyDevicePool(), and org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.releaseToDevicePool().
MastershipService org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.mastershipService protected
Definition at line 90 of file DistributedLabelResourceStore.java.
StorageService org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.storageService protected
Definition at line 87 of file DistributedLabelResourceStore.java.
The documentation for this class was generated from the following file:
incubator/store/src/main/java/org/onosproject/incubator/store/resource/impl/DistributedLabelResourceStore.java