onos: org.onosproject.ui.impl.TrafficMonitor Class Reference
org.onosproject.ui.impl.TrafficMonitor Class Reference
Encapsulates the behavior of monitoring specific traffic patterns.
Classes
enum Mode
Designates the different modes of operation.
Public Member Functions
TrafficMonitor (long trafficPeriod, ServicesBundle servicesBundle, TopologyViewMessageHandler msgHandler)
Constructs a traffic monitor.
synchronized void monitor (Mode mode)
Monitor for traffic data to be sent back to the web client, under the given mode.
synchronized void monitor (Mode mode, NodeSelection nodeSelection)
Monitor for traffic data to be sent back to the web client, under the given mode, using the given selection of devices and hosts.
synchronized void monitor (Intent intent)
Monitor for traffic data to be sent back to the web client, for the given intent.
synchronized void selectNextIntent ()
Selects the next intent in the select group (if there is one), and sends highlighting data back to the web client to display which path is selected.
synchronized void selectPreviousIntent ()
Selects the previous intent in the select group (if there is one), and sends highlighting data back to the web client to display which path is selected.
synchronized void pokeIntent ()
Resends selected intent traffic data.
synchronized void stopMonitoring ()
Stop all traffic monitoring.
Detailed Description
Encapsulates the behavior of monitoring specific traffic patterns.
Definition at line 73 of file TrafficMonitor.java.
Constructor & Destructor Documentation
org.onosproject.ui.impl.TrafficMonitor.TrafficMonitor (long trafficPeriod, ServicesBundle servicesBundle, TopologyViewMessageHandler msgHandler)
Constructs a traffic monitor.
Parameters
trafficPeriod traffic task period in ms
servicesBundle bundle of services
msgHandler our message handler
Definition at line 113 of file TrafficMonitor.java.
Member Function Documentation
synchronized void org.onosproject.ui.impl.TrafficMonitor.monitor (Mode mode)
Monitor for traffic data to be sent back to the web client, under the given mode.
This causes a background traffic task to be scheduled to repeatedly compute and transmit the appropriate traffic data to the client.
The monitoring mode is expected to be one of:
ALL_FLOW_TRAFFIC
ALL_PORT_TRAFFIC
SELECTED_INTENT
Parameters
mode monitoring mode
Definition at line 140 of file TrafficMonitor.java.
synchronized void org.onosproject.ui.impl.TrafficMonitor.monitor (Mode mode, NodeSelection nodeSelection)
Monitor for traffic data to be sent back to the web client, under the given mode, using the given selection of devices and hosts.
In the case of "device link flows", this causes a background traffic task to be scheduled to repeatedly compute and transmit the appropriate traffic data to the client. In the case of "related intents", no repeating task is scheduled.
The monitoring mode is expected to be one of:
DEV_LINK_FLOWS
RELATED_INTENTS
Parameters
mode monitoring mode
nodeSelection how to select a node
Definition at line 186 of file TrafficMonitor.java.
References org.onosproject.ui.topo.NodeSelection.devicesWithHover(), org.onosproject.ui.impl.topo.IntentSelection.none(), and org.onosproject.ui.topo.NodeSelection.none().
synchronized void org.onosproject.ui.impl.TrafficMonitor.monitor (Intent intent)
Monitor for traffic data to be sent back to the web client, for the given intent.
Parameters
intent the intent to monitor
Definition at line 229 of file TrafficMonitor.java.
synchronized void org.onosproject.ui.impl.TrafficMonitor.pokeIntent ()
Resends selected intent traffic data.
This is called, for example, when the system detects an intent update happened.
Definition at line 272 of file TrafficMonitor.java.
synchronized void org.onosproject.ui.impl.TrafficMonitor.selectNextIntent ()
Selects the next intent in the select group (if there is one), and sends highlighting data back to the web client to display which path is selected.
Definition at line 243 of file TrafficMonitor.java.
synchronized void org.onosproject.ui.impl.TrafficMonitor.selectPreviousIntent ()
Selects the previous intent in the select group (if there is one), and sends highlighting data back to the web client to display which path is selected.
Definition at line 258 of file TrafficMonitor.java.
synchronized void org.onosproject.ui.impl.TrafficMonitor.stopMonitoring ()
Stop all traffic monitoring.
Definition at line 281 of file TrafficMonitor.java.
The documentation for this class was generated from the following file:
web/gui/src/main/java/org/onosproject/ui/impl/TrafficMonitor.java