onos: org.onosproject.bgp.controller.impl.BgpSelectionAlgo Class Reference
org.onosproject.bgp.controller.impl.BgpSelectionAlgo Class Reference
Implementation of BGP best path Selection process.
Public Member Functions
int compare (PathAttrNlriDetailsLocalRib pathNlriDetails1, PathAttrNlriDetailsLocalRib pathNlriDetails2)
Detailed Description
Implementation of BGP best path Selection process.
Definition at line 35 of file BgpSelectionAlgo.java.
Member Function Documentation
int org.onosproject.bgp.controller.impl.BgpSelectionAlgo.compare (PathAttrNlriDetailsLocalRib pathNlriDetails1, PathAttrNlriDetailsLocalRib pathNlriDetails2)
Definition at line 47 of file BgpSelectionAlgo.java.
References org.onosproject.bgpio.types.LocalPref.equals(), org.onosproject.bgpio.types.Med.equals(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.equals(), org.onosproject.bgpio.types.Origin.equals(), and org.onosproject.bgpio.types.AsPath.equals().
The documentation for this class was generated from the following file:
bgp/ctl/src/main/java/org/onosproject/bgp/controller/impl/BgpSelectionAlgo.java