onos: org.onosproject.dhcp.impl.DistributedDhcpStore Class Reference
org.onosproject.dhcp.impl.DistributedDhcpStore Class Reference
Manages the pool of available IP Addresses in the network and Remembers the mapping between MAC ID and IP Addresses assigned.
Public Member Functions
Ip4Address suggestIP (HostId hostId, Ip4Address requestedIP)
Returns an IP Address for a Mac ID, in response to a DHCP DISCOVER message.
boolean assignIP (HostId hostId, Ip4Address ipAddr, int leaseTime, boolean rangeNotEnforced, List< Ip4Address > addressList)
Assigns the requested IP to the Mac ID, in response to a DHCP REQUEST message.
Ip4Address releaseIP (HostId hostId)
Releases the IP assigned to a Mac ID into the free pool.
void setDefaultTimeoutForPurge (int timeInSeconds)
Sets the default time for which suggested IP mappings are valid.
Map< HostId, IpAssignment > listAssignedMapping ()
Returns a collection of all the MacAddress to IPAddress mapping assigned to the hosts.
Map< HostId, IpAssignment > listAllMapping ()
Returns a collection of all the MacAddress to IPAddress mapping.
boolean assignStaticIP (MacAddress macID, Ip4Address ipAddr, boolean rangeNotEnforced, List< Ip4Address > addressList)
Assigns the requested IP to the MAC ID (if available) for an indefinite period of time.
boolean removeStaticIP (MacAddress macID)
Removes a static IP mapping associated with the given MAC ID from the DHCP Server.
Iterable< Ip4Address > getAvailableIPs ()
Returns the list of all the available IPs with the server.
void populateIPPoolfromRange (Ip4Address startIP, Ip4Address endIP)
Appends all the IPs in a given range to the free pool of IPs.
IpAssignment getIpAssignmentFromAllocationMap (HostId hostId)
Protected Member Functions
void activate ()
void deactivate ()
Protected Attributes
StorageService storageService
Detailed Description
Manages the pool of available IP Addresses in the network and Remembers the mapping between MAC ID and IP Addresses assigned.
Definition at line 53 of file DistributedDhcpStore.java.
Member Function Documentation
void org.onosproject.dhcp.impl.DistributedDhcpStore.activate () protected
Definition at line 73 of file DistributedDhcpStore.java.
References org.onosproject.store.serializers.KryoNamespaces.API, and org.onosproject.store.service.Serializer.using().
boolean org.onosproject.dhcp.impl.DistributedDhcpStore.assignIP (HostId hostId, Ip4Address ipAddr, int leaseTime, boolean rangeNotEnforced, List< Ip4Address > addressList)
Assigns the requested IP to the Mac ID, in response to a DHCP REQUEST message.
Parameters
hostId Host Id of the client requesting an IP
ipAddr IP Address being requested
leaseTime Lease time offered by the server for this mapping
rangeNotEnforced true if rangeNotEnforced was set
addressList subnetMask, DHCP/Router/DNS IP Addresses if rangeNotEnforced was set
Returns
returns true if the assignment was successful, false otherwise
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 166 of file DistributedDhcpStore.java.
Referenced by org.onosproject.dhcp.impl.DistributedDhcpStore.assignStaticIP().
boolean org.onosproject.dhcp.impl.DistributedDhcpStore.assignStaticIP (MacAddress macID, Ip4Address ipAddr, boolean rangeNotEnforced, List< Ip4Address > addressList)
Assigns the requested IP to the MAC ID (if available) for an indefinite period of time.
Parameters
macID macID of the client
ipAddr IP Address requested for the client
rangeNotEnforced true if rangeNotEnforced was set
addressList subnetMask, DHCP/Router/DNS IP Addresses rangeNotEnforced was set
Returns
true if the mapping was successfully registered, false otherwise
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 282 of file DistributedDhcpStore.java.
References org.onosproject.dhcp.impl.DistributedDhcpStore.assignIP().
void org.onosproject.dhcp.impl.DistributedDhcpStore.deactivate () protected
Definition at line 96 of file DistributedDhcpStore.java.
Iterable<Ip4Address> org.onosproject.dhcp.impl.DistributedDhcpStore.getAvailableIPs ()
Returns the list of all the available IPs with the server.
Returns
list of available IPs
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 312 of file DistributedDhcpStore.java.
IpAssignment org.onosproject.dhcp.impl.DistributedDhcpStore.getIpAssignmentFromAllocationMap (HostId hostId)
Parameters
hostId
Returns
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 333 of file DistributedDhcpStore.java.
Map<HostId, IpAssignment> org.onosproject.dhcp.impl.DistributedDhcpStore.listAllMapping ()
Returns a collection of all the MacAddress to IPAddress mapping.
Returns
the collection of the mappings
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 273 of file DistributedDhcpStore.java.
Map<HostId, IpAssignment> org.onosproject.dhcp.impl.DistributedDhcpStore.listAssignedMapping ()
Returns a collection of all the MacAddress to IPAddress mapping assigned to the hosts.
Returns
the collection of the mappings
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 258 of file DistributedDhcpStore.java.
void org.onosproject.dhcp.impl.DistributedDhcpStore.populateIPPoolfromRange (Ip4Address startIP, Ip4Address endIP)
Appends all the IPs in a given range to the free pool of IPs.
Parameters
startIP Start IP for the range
endIP End IP for the range
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 317 of file DistributedDhcpStore.java.
References org.onlab.packet.Ip4Address.toInt().
Ip4Address org.onosproject.dhcp.impl.DistributedDhcpStore.releaseIP (HostId hostId)
Releases the IP assigned to a Mac ID into the free pool.
Parameters
hostId the host ID for which the mapping needs to be changed
Returns
released ip
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 237 of file DistributedDhcpStore.java.
boolean org.onosproject.dhcp.impl.DistributedDhcpStore.removeStaticIP (MacAddress macID)
Removes a static IP mapping associated with the given MAC ID from the DHCP Server.
Parameters
macID macID of the client
Returns
true if the mapping was successfully registered, false otherwise
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 289 of file DistributedDhcpStore.java.
void org.onosproject.dhcp.impl.DistributedDhcpStore.setDefaultTimeoutForPurge (int timeInSeconds)
Sets the default time for which suggested IP mappings are valid.
Parameters
timeInSeconds default time for IP mappings to be valid
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 253 of file DistributedDhcpStore.java.
Ip4Address org.onosproject.dhcp.impl.DistributedDhcpStore.suggestIP (HostId hostId, Ip4Address requestedIP)
Returns an IP Address for a Mac ID, in response to a DHCP DISCOVER message.
Parameters
hostId Host ID of the client requesting an IP
requestedIP requested IP address
Returns
IP address assigned to the Mac ID
Implements org.onosproject.dhcp.DhcpStore.
Definition at line 101 of file DistributedDhcpStore.java.
References org.onlab.packet.Ip4Address.toInt().
Member Data Documentation
StorageService org.onosproject.dhcp.impl.DistributedDhcpStore.storageService protected
Definition at line 58 of file DistributedDhcpStore.java.
The documentation for this class was generated from the following file:
apps/dhcp/app/src/main/java/org/onosproject/dhcp/impl/DistributedDhcpStore.java