onos: org.onosproject.store.consistent.impl.DatabaseConfig Class Reference
org.onosproject.store.consistent.impl.DatabaseConfig Class Reference
Database configuration.
Public Member Functions
DatabaseConfig ()
DatabaseConfig (Map< String, Object > config)
DatabaseConfig (String resource)
DatabaseConfig copy ()
void setConsistency (String consistency)
Sets the database read consistency.
void setConsistency (Consistency consistency)
Sets the database read consistency.
Consistency getConsistency ()
Returns the database read consistency.
DatabaseConfig withConsistency (String consistency)
Sets the database read consistency, returning the configuration for method chaining.
DatabaseConfig withConsistency (Consistency consistency)
Sets the database read consistency, returning the configuration for method chaining.
String getName ()
Returns the database name.
DatabaseConfig withName (String name)
Sets the database name, returning the configuration for method chaining.
void setName (String name)
Sets the database name.
CoordinatedResourceConfig resolve (ClusterConfig cluster)
Protected Member Functions
DatabaseConfig (DatabaseConfig config)
Detailed Description
Database configuration.
Definition at line 33 of file DatabaseConfig.java.
Constructor & Destructor Documentation
org.onosproject.store.consistent.impl.DatabaseConfig.DatabaseConfig ()
Definition at line 41 of file DatabaseConfig.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseConfig.copy().
org.onosproject.store.consistent.impl.DatabaseConfig.DatabaseConfig (Map< String, Object > config)
Definition at line 45 of file DatabaseConfig.java.
org.onosproject.store.consistent.impl.DatabaseConfig.DatabaseConfig (String resource)
Definition at line 49 of file DatabaseConfig.java.
org.onosproject.store.consistent.impl.DatabaseConfig.DatabaseConfig (DatabaseConfig config) protected
Definition at line 53 of file DatabaseConfig.java.
Member Function Documentation
DatabaseConfig org.onosproject.store.consistent.impl.DatabaseConfig.copy ()
Definition at line 58 of file DatabaseConfig.java.
References org.onosproject.store.consistent.impl.DatabaseConfig.DatabaseConfig().
Consistency org.onosproject.store.consistent.impl.DatabaseConfig.getConsistency ()
Returns the database read consistency.
Returns
The database read consistency.
Definition at line 91 of file DatabaseConfig.java.
String org.onosproject.store.consistent.impl.DatabaseConfig.getName ()
Returns the database name.
Returns
The database name
Definition at line 124 of file DatabaseConfig.java.
CoordinatedResourceConfig org.onosproject.store.consistent.impl.DatabaseConfig.resolve (ClusterConfig cluster)
Definition at line 151 of file DatabaseConfig.java.
References find-link-in-cluster.cluster.
Referenced by org.onosproject.store.consistent.impl.Database.create().
void org.onosproject.store.consistent.impl.DatabaseConfig.setConsistency (String consistency)
Sets the database read consistency.
Parameters
consistency The database read consistency.
Exceptions
java.lang.NullPointerException If the consistency is
null
Definition at line 68 of file DatabaseConfig.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseConfig.withConsistency().
void org.onosproject.store.consistent.impl.DatabaseConfig.setConsistency (Consistency consistency)
Sets the database read consistency.
Parameters
consistency The database read consistency.
Exceptions
java.lang.NullPointerException If the consistency is
null
Definition at line 80 of file DatabaseConfig.java.
void org.onosproject.store.consistent.impl.DatabaseConfig.setName (String name)
Sets the database name.
Parameters
name The database name
Exceptions
java.lang.NullPointerException If the name is
null
Definition at line 146 of file DatabaseConfig.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseConfig.withName().
DatabaseConfig org.onosproject.store.consistent.impl.DatabaseConfig.withConsistency (String consistency)
Sets the database read consistency, returning the configuration for method chaining.
Parameters
consistency The database read consistency.
Returns
The database configuration.
Exceptions
java.lang.NullPointerException If the consistency is
null
Definition at line 102 of file DatabaseConfig.java.
References org.onosproject.store.consistent.impl.DatabaseConfig.setConsistency().
DatabaseConfig org.onosproject.store.consistent.impl.DatabaseConfig.withConsistency (Consistency consistency)
Sets the database read consistency, returning the configuration for method chaining.
Parameters
consistency The database read consistency.
Returns
The database configuration.
Exceptions
java.lang.NullPointerException If the consistency is
null
Definition at line 114 of file DatabaseConfig.java.
References org.onosproject.store.consistent.impl.DatabaseConfig.setConsistency().
DatabaseConfig org.onosproject.store.consistent.impl.DatabaseConfig.withName (String name)
Sets the database name, returning the configuration for method chaining.
Parameters
name The database name
Returns
The database configuration
Exceptions
java.lang.NullPointerException If the name is
null
Definition at line 135 of file DatabaseConfig.java.
References org.onosproject.store.consistent.impl.DatabaseConfig.setName().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DatabaseConfig.java