onos: org.onosproject.net.intent.MplsIntentTest Class Reference
org.onosproject.net.intent.MplsIntentTest Class Reference
Unit tests for the MplsIntent class.
Public Member Functions
void mplsIntentTestSetUp () throws Exception
void testImmutability ()
Checks that the MplsIntent class is immutable.
void testEquals ()
Checks the operation of equals(), hashCode() and toString() methods.
void testContents ()
Checks that the MplsIntent objects are created correctly.
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Additional Inherited Members
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
Unit tests for the MplsIntent class.
Definition at line 39 of file MplsIntentTest.java.
Member Function Documentation
void org.onosproject.net.intent.MplsIntentTest.mplsIntentTestSetUp () throws Exception
Definition at line 52 of file MplsIntentTest.java.
void org.onosproject.net.intent.MplsIntentTest.testContents ()
Checks that the MplsIntent objects are created correctly.
Definition at line 106 of file MplsIntentTest.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.Intent.priority(), org.onosproject.net.intent.ConnectivityIntent.selector(), and org.onosproject.net.intent.ConnectivityIntent.treatment().
void org.onosproject.net.intent.MplsIntentTest.testEquals ()
Checks the operation of equals(), hashCode() and toString() methods.
Definition at line 95 of file MplsIntentTest.java.
void org.onosproject.net.intent.MplsIntentTest.testImmutability ()
Checks that the MplsIntent class is immutable.
Definition at line 87 of file MplsIntentTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/intent/MplsIntentTest.java