onos: org.onosproject.openflow.controller.impl.Controller Class Reference
org.onosproject.openflow.controller.impl.Controller Class Reference
The main controller class.
Public Member Functions
OFFactory getOFMessageFactory10 ()
OFFactory getOFMessageFactory13 ()
void run ()
Tell controller that we're ready to accept switches loop.
void setConfigParams (Dictionary<?,?> properties)
void init ()
Initialize internal data structures.
Map< String, Long > getMemory ()
Long getSystemUptime ()
long getSystemStartTime ()
void start (OpenFlowAgent ag, DriverService driverService)
void stop ()
Protected Member Functions
OpenFlowSwitchDriver getOFSwitchInstance (long dpid, OFDescStatsReply desc, OFVersion ofv)
Forward to the driver-manager to get an IOFSwitch instance.
Protected Attributes
HashMap< String, String > controllerNodeIPsCache
List< Integer > openFlowPorts = ImmutableList.of(6633, 6653)
int workerThreads = 16
long systemStartTime
String ksLocation
String tsLocation
char[] ksPwd
char[] tsPwd
SSLEngine serverSslEngine
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(Controller.class)
static final OFFactory FACTORY13 = OFFactories.getFactory(OFVersion.OF_13)
static final OFFactory FACTORY10 = OFFactories.getFactory(OFVersion.OF_10)
static final int SEND_BUFFER_SIZE = 4 * 1024 * 1024
Detailed Description
The main controller class.
Handles all setup and network listeners
Distributed ownership control of switch through IControllerRegistryService
Definition at line 69 of file Controller.java.
Member Function Documentation
Map<String, Long> org.onosproject.openflow.controller.impl.Controller.getMemory ()
Definition at line 258 of file Controller.java.
OFFactory org.onosproject.openflow.controller.impl.Controller.getOFMessageFactory10 ()
Definition at line 108 of file Controller.java.
References org.onosproject.openflow.controller.impl.Controller.FACTORY10.
OFFactory org.onosproject.openflow.controller.impl.Controller.getOFMessageFactory13 ()
Definition at line 113 of file Controller.java.
References org.onosproject.openflow.controller.impl.Controller.FACTORY13.
OpenFlowSwitchDriver org.onosproject.openflow.controller.impl.Controller.getOFSwitchInstance (long dpid, OFDescStatsReply desc, OFVersion ofv) protected
Forward to the driver-manager to get an IOFSwitch instance.
Parameters
dpid data path id
desc switch description
ofv OpenFlow version
Returns
switch instance
Definition at line 284 of file Controller.java.
References find-flow.deviceId, obeliskHostCheck.dpid, and org.onosproject.net.driver.Driver.hasBehaviour().
long org.onosproject.openflow.controller.impl.Controller.getSystemStartTime ()
Definition at line 272 of file Controller.java.
References org.onosproject.openflow.controller.impl.Controller.systemStartTime.
Long org.onosproject.openflow.controller.impl.Controller.getSystemUptime ()
Definition at line 267 of file Controller.java.
void org.onosproject.openflow.controller.impl.Controller.init ()
Initialize internal data structures.
Definition at line 184 of file Controller.java.
void org.onosproject.openflow.controller.impl.Controller.run ()
Tell controller that we're ready to accept switches loop.
Definition at line 124 of file Controller.java.
References obeliskHostCheck.port, org.onosproject.openflow.controller.impl.Controller.SEND_BUFFER_SIZE, and org.onosproject.openflow.controller.impl.Controller.serverSslEngine.
void org.onosproject.openflow.controller.impl.Controller.setConfigParams (Dictionary<?,?> properties)
Definition at line 165 of file Controller.java.
void org.onosproject.openflow.controller.impl.Controller.start (OpenFlowAgent ag, DriverService driverService)
Definition at line 313 of file Controller.java.
void org.onosproject.openflow.controller.impl.Controller.stop ()
Definition at line 322 of file Controller.java.
Member Data Documentation
HashMap<String, String> org.onosproject.openflow.controller.impl.Controller.controllerNodeIPsCache protected
Definition at line 78 of file Controller.java.
final OFFactory org.onosproject.openflow.controller.impl.Controller.FACTORY10 = OFFactories.getFactory(OFVersion.OF_10) static protected
Definition at line 74 of file Controller.java.
Referenced by org.onosproject.openflow.controller.impl.Controller.getOFMessageFactory10().
final OFFactory org.onosproject.openflow.controller.impl.Controller.FACTORY13 = OFFactories.getFactory(OFVersion.OF_13) static protected
Definition at line 73 of file Controller.java.
Referenced by org.onosproject.openflow.controller.impl.Controller.getOFMessageFactory13().
String org.onosproject.openflow.controller.impl.Controller.ksLocation protected
Definition at line 93 of file Controller.java.
char [] org.onosproject.openflow.controller.impl.Controller.ksPwd protected
Definition at line 95 of file Controller.java.
final Logger org.onosproject.openflow.controller.impl.Controller.log = LoggerFactory.getLogger(Controller.class) static protected
Definition at line 71 of file Controller.java.
List<Integer> org.onosproject.openflow.controller.impl.Controller.openFlowPorts = ImmutableList.of(6633, 6653) protected
Definition at line 83 of file Controller.java.
Referenced by org.onosproject.openflow.controller.impl.ControllerTest.testConfiguration().
final int org.onosproject.openflow.controller.impl.Controller.SEND_BUFFER_SIZE = 4 * 1024 * 1024 static protected
Definition at line 100 of file Controller.java.
Referenced by org.onosproject.openflow.controller.impl.Controller.run().
SSLEngine org.onosproject.openflow.controller.impl.Controller.serverSslEngine protected
Definition at line 97 of file Controller.java.
Referenced by org.onosproject.openflow.controller.impl.Controller.run(), and org.onosproject.openflow.controller.impl.ControllerTest.testSsl().
long org.onosproject.openflow.controller.impl.Controller.systemStartTime protected
Definition at line 87 of file Controller.java.
Referenced by org.onosproject.openflow.controller.impl.Controller.getSystemStartTime().
String org.onosproject.openflow.controller.impl.Controller.tsLocation protected
Definition at line 94 of file Controller.java.
char [] org.onosproject.openflow.controller.impl.Controller.tsPwd protected
Definition at line 96 of file Controller.java.
int org.onosproject.openflow.controller.impl.Controller.workerThreads = 16 protected
Definition at line 84 of file Controller.java.
Referenced by org.onosproject.openflow.controller.impl.ControllerTest.testConfiguration().
The documentation for this class was generated from the following file:
protocols/openflow/ctl/src/main/java/org/onosproject/openflow/controller/impl/Controller.java