onos: org.onosproject.net.intent.LinkCollectionIntentTest Class Reference
org.onosproject.net.intent.LinkCollectionIntentTest Class Reference
Unit tests for the LinkCollectionIntent class.
Public Member Functions
void testImmutability ()
Checks that the LinkCollectionIntent class is immutable.
void testEquals ()
Tests equals(), hashCode() and toString() methods.
void testConstructor ()
Tests constructor without constraints.
void testConstructorWithConstraints ()
Tests constructor with constraints.
void testSerializerConstructor ()
Tests constructor with constraints.
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Protected Member Functions
Intent createOne ()
Creates a new intent, but always a like intent, i.e.
Intent createAnother ()
Creates another intent, not equals to the one created by createOne() and with a different hash code.
Additional Inherited Members
Static Protected Member Functions inherited from org.onosproject.net.intent.IntentTest
static< T > Set< T > itemSet (T[] items)
Produces a set of items from the supplied items.
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
Unit tests for the LinkCollectionIntent class.
Definition at line 46 of file LinkCollectionIntentTest.java.
Member Function Documentation
Intent org.onosproject.net.intent.LinkCollectionIntentTest.createAnother () protected virtual
Creates another intent, not equals to the one created by createOne() and with a different hash code.
Returns
another intent
Implements org.onosproject.net.intent.IntentTest.
Definition at line 197 of file LinkCollectionIntentTest.java.
Intent org.onosproject.net.intent.LinkCollectionIntentTest.createOne () protected virtual
Creates a new intent, but always a like intent, i.e.
all instances will be equal, but should not be the same.
Returns
intent
Implements org.onosproject.net.intent.IntentTest.
Definition at line 183 of file LinkCollectionIntentTest.java.
void org.onosproject.net.intent.LinkCollectionIntentTest.testConstructor ()
Tests constructor without constraints.
Definition at line 101 of file LinkCollectionIntentTest.java.
void org.onosproject.net.intent.LinkCollectionIntentTest.testConstructorWithConstraints ()
Tests constructor with constraints.
Definition at line 130 of file LinkCollectionIntentTest.java.
void org.onosproject.net.intent.LinkCollectionIntentTest.testEquals ()
Tests equals(), hashCode() and toString() methods.
Definition at line 65 of file LinkCollectionIntentTest.java.
void org.onosproject.net.intent.LinkCollectionIntentTest.testImmutability ()
Checks that the LinkCollectionIntent class is immutable.
Definition at line 57 of file LinkCollectionIntentTest.java.
void org.onosproject.net.intent.LinkCollectionIntentTest.testSerializerConstructor ()
Tests constructor with constraints.
Definition at line 165 of file LinkCollectionIntentTest.java.
References org.onosproject.net.intent.Intent.isInstallable(), org.onosproject.net.intent.ConnectivityIntent.selector(), and org.onosproject.net.intent.ConnectivityIntent.treatment().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/intent/LinkCollectionIntentTest.java