onos: org.onosproject.net.flow.DefaultTrafficTreatment Class Reference
org.onosproject.net.flow.DefaultTrafficTreatment Class Reference
Default traffic treatment implementation.
Classes
class Builder
Builds a list of treatments following the following order.
Public Member Functions
List< Instruction > deferred ()
Returns the list of treatment instructions that will be applied further down the pipeline.
List< Instruction > immediate ()
Returns the list of treatment instructions that will be applied immediately.
List< Instruction > allInstructions ()
Returns the list of all instructions in the treatment, both immediate and deferred.
Instructions.TableTypeTransition tableTransition ()
Returns the next table in the pipeline.
boolean clearedDeferred ()
Whether the deferred treatment instructions will be cleared by the device.
Instructions.MetadataInstruction writeMetadata ()
Returns the metadata instruction if there is one.
Instructions.MeterInstruction metered ()
Returns the meter instruction if there is one.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static TrafficTreatment.Builder builder ()
Returns a new traffic treatment builder.
static TrafficTreatment emptyTreatment ()
Returns an empty traffic treatment.
static TrafficTreatment.Builder builder (TrafficTreatment treatment)
Returns a new traffic treatment builder primed to produce entities patterned after the supplied treatment.
Detailed Description
Default traffic treatment implementation.
Definition at line 45 of file DefaultTrafficTreatment.java.
Member Function Documentation
List<Instruction> org.onosproject.net.flow.DefaultTrafficTreatment.allInstructions ()
Returns the list of all instructions in the treatment, both immediate and deferred.
Returns
list of treatment instructions
Implements org.onosproject.net.flow.TrafficTreatment.
Definition at line 111 of file DefaultTrafficTreatment.java.
static TrafficTreatment.Builder org.onosproject.net.flow.DefaultTrafficTreatment.builder () static
Returns a new traffic treatment builder.
Returns
traffic treatment builder
Definition at line 140 of file DefaultTrafficTreatment.java.
Referenced by org.onosproject.net.edgeservice.impl.EdgeManager.emitPacket(), org.onosproject.net.intent.impl.compiler.LinkCollectionIntentCompilerTest.testCompile(), and org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest.testCompile().
static TrafficTreatment.Builder org.onosproject.net.flow.DefaultTrafficTreatment.builder (TrafficTreatment treatment) static
Returns a new traffic treatment builder primed to produce entities patterned after the supplied treatment.
Parameters
treatment base treatment
Returns
traffic treatment builder
Definition at line 160 of file DefaultTrafficTreatment.java.
boolean org.onosproject.net.flow.DefaultTrafficTreatment.clearedDeferred ()
Whether the deferred treatment instructions will be cleared by the device.
Returns
a boolean
Implements org.onosproject.net.flow.TrafficTreatment.
Definition at line 121 of file DefaultTrafficTreatment.java.
List<Instruction> org.onosproject.net.flow.DefaultTrafficTreatment.deferred ()
Returns the list of treatment instructions that will be applied further down the pipeline.
Returns
list of treatment instructions
Implements org.onosproject.net.flow.TrafficTreatment.
Definition at line 101 of file DefaultTrafficTreatment.java.
Referenced by org.onosproject.net.flow.DefaultTrafficTreatment.hashCode(), and org.onosproject.net.flow.DefaultTrafficTreatment.toString().
static TrafficTreatment org.onosproject.net.flow.DefaultTrafficTreatment.emptyTreatment () static
Returns an empty traffic treatment.
Returns
empty traffic treatment
Definition at line 149 of file DefaultTrafficTreatment.java.
boolean org.onosproject.net.flow.DefaultTrafficTreatment.equals (Object obj)
Definition at line 171 of file DefaultTrafficTreatment.java.
References org.onosproject.net.flow.DefaultTrafficTreatment.immediate().
int org.onosproject.net.flow.DefaultTrafficTreatment.hashCode ()
Definition at line 166 of file DefaultTrafficTreatment.java.
References org.onosproject.net.flow.DefaultTrafficTreatment.deferred(), and org.onosproject.net.flow.DefaultTrafficTreatment.immediate().
List<Instruction> org.onosproject.net.flow.DefaultTrafficTreatment.immediate ()
Returns the list of treatment instructions that will be applied immediately.
Returns
list of treatment instructions
Implements org.onosproject.net.flow.TrafficTreatment.
Definition at line 106 of file DefaultTrafficTreatment.java.
Referenced by org.onosproject.net.flow.DefaultTrafficTreatment.equals(), and org.onosproject.net.flow.DefaultTrafficTreatment.hashCode().
Instructions.MeterInstruction org.onosproject.net.flow.DefaultTrafficTreatment.metered ()
Returns the meter instruction if there is one.
Returns
a meter instruction that may be null
Implements org.onosproject.net.flow.TrafficTreatment.
Definition at line 131 of file DefaultTrafficTreatment.java.
Instructions.TableTypeTransition org.onosproject.net.flow.DefaultTrafficTreatment.tableTransition ()
Returns the next table in the pipeline.
Returns
a table transition; may be null.
Implements org.onosproject.net.flow.TrafficTreatment.
Definition at line 116 of file DefaultTrafficTreatment.java.
String org.onosproject.net.flow.DefaultTrafficTreatment.toString ()
Definition at line 187 of file DefaultTrafficTreatment.java.
References org.onosproject.net.flow.DefaultTrafficTreatment.deferred().
Instructions.MetadataInstruction org.onosproject.net.flow.DefaultTrafficTreatment.writeMetadata ()
Returns the metadata instruction if there is one.
Returns
a metadata instruction that may be null
Implements org.onosproject.net.flow.TrafficTreatment.
Definition at line 126 of file DefaultTrafficTreatment.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/DefaultTrafficTreatment.java