onos: org.onosproject.net.config.basics.OpticalPortConfig Class Reference
org.onosproject.net.config.basics.OpticalPortConfig Class Reference
Configurations for an optical port on a device.
Public Member Functions
Port.Type type ()
Returns the Enum value representing the type of port.
String name ()
Returns the port name associated with this port configuration.
String numberName ()
Returns a stringified representation of the port number, configured in some port types without an alphanumeric name as the port name.
String staticPort ()
Returns the string-representation of name of the output port.
Optional< Long > staticLambda ()
Returns the output lambda configured for this port.
Optional< Integer > speed ()
Returns the port speed configured for this port.
OpticalPortConfig portType (Port.Type type)
Sets the port type, or updates it if it's already set.
OpticalPortConfig portName (String name)
Sets the port name, or updates it if already set.
OpticalPortConfig portNumberName (Long name)
Sets the port name from port number, or updates it if already set.
OpticalPortConfig staticPort (String name)
Sets the output port name, or updates it if already set.
OpticalPortConfig staticLambda (Long index)
Sets the output lambda index, or updates it if already set.
OpticalPortConfig speed (Integer bw)
Sets the port speed, or updates it if already set.
Static Public Attributes
static final String TYPE = "type"
static final String NAME = "name"
static final String PORT = "port"
static final String STATIC_PORT = "staticPort"
static final String STATIC_LAMBDA = "staticLambda"
static final String SPEED = "speed"
Detailed Description
Configurations for an optical port on a device.
Definition at line 30 of file OpticalPortConfig.java.
Member Function Documentation
String org.onosproject.net.config.basics.OpticalPortConfig.name ()
Returns the port name associated with this port configuration.
The Name is an alphanumeric string.
Returns
the name of this port, else, an empty string
Definition at line 64 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.NAME.
Referenced by org.onosproject.net.device.impl.OpticalPortOperator.combine(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.incubator.net.config.basics.OpticalPortConfigTest.testBaseAttrs().
String org.onosproject.net.config.basics.OpticalPortConfig.numberName ()
Returns a stringified representation of the port number, configured in some port types without an alphanumeric name as the port name.
Returns
A string representation of the port number
Definition at line 74 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.PORT.
OpticalPortConfig org.onosproject.net.config.basics.OpticalPortConfig.portName (String name)
Sets the port name, or updates it if already set.
A null argument removes this field.
Parameters
name the port's name
Returns
this OpticalPortConfig instance
Definition at line 143 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.NAME.
OpticalPortConfig org.onosproject.net.config.basics.OpticalPortConfig.portNumberName (Long name)
Sets the port name from port number, or updates it if already set.
A null argument removes this field.
Parameters
name the port number, to be used as name
Returns
this OpticalPortConfig instance
Definition at line 154 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.PORT.
OpticalPortConfig org.onosproject.net.config.basics.OpticalPortConfig.portType (Port.Type type)
Sets the port type, or updates it if it's already set.
A null argument removes this field.
Parameters
type the port type
Returns
this OpticalPortConfig instance
Definition at line 130 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.TYPE, and org.onosproject.net.config.basics.OpticalPortConfig.type().
Optional<Integer> org.onosproject.net.config.basics.OpticalPortConfig.speed ()
Returns the port speed configured for this port.
If the port doesn't have a notion of speed, this returns an empty Optional.
Returns
a port speed value whose default is 0.
Definition at line 115 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.SPEED.
OpticalPortConfig org.onosproject.net.config.basics.OpticalPortConfig.speed (Integer bw)
Sets the port speed, or updates it if already set.
A null argument removes this field.
Parameters
bw the port bandwidth
Returns
this OpticalPortConfig instance
Definition at line 187 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.SPEED.
Optional<Long> org.onosproject.net.config.basics.OpticalPortConfig.staticLambda ()
Returns the output lambda configured for this port.
The lambda value is expressed as a frequency value. If the port type doesn't have a notion of lambdas, this returns an empty Optional.
Returns
an Optional that may contain a frequency value.
Definition at line 101 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.STATIC_LAMBDA.
Referenced by org.onosproject.net.device.impl.OpticalPortOperator.combine(), and org.onosproject.incubator.net.config.basics.OpticalPortConfigTest.testAdditionalAttrs().
OpticalPortConfig org.onosproject.net.config.basics.OpticalPortConfig.staticLambda (Long index)
Sets the output lambda index, or updates it if already set.
A null argument removes this field.
Parameters
index the output lambda
Returns
this OpticalPortConfig instance
Definition at line 176 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.STATIC_LAMBDA.
String org.onosproject.net.config.basics.OpticalPortConfig.staticPort ()
Returns the string-representation of name of the output port.
This is usually an OMS port for an OCH input ports, or an OCH port for ODU input ports.
Returns
the name of this port, else, an empty string
Definition at line 85 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.STATIC_PORT.
Referenced by org.onosproject.net.device.impl.OpticalPortOperator.combine(), and org.onosproject.incubator.net.config.basics.OpticalPortConfigTest.testAdditionalAttrs().
OpticalPortConfig org.onosproject.net.config.basics.OpticalPortConfig.staticPort (String name)
Sets the output port name, or updates it if already set.
A null argument removes this field.
Parameters
name the output port's name
Returns
this OpticalPortConfig instance
Definition at line 165 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.STATIC_PORT.
Port.Type org.onosproject.net.config.basics.OpticalPortConfig.type ()
Returns the Enum value representing the type of port.
Returns
the port type, or null if invalid or unset
Definition at line 50 of file OpticalPortConfig.java.
References org.onosproject.net.config.basics.OpticalPortConfig.TYPE.
Referenced by org.onosproject.net.device.impl.OpticalPortOperator.combine(), org.onosproject.net.config.basics.OpticalPortConfig.portType(), and org.onosproject.incubator.net.config.basics.OpticalPortConfigTest.testBaseAttrs().
Member Data Documentation
final String org.onosproject.net.config.basics.OpticalPortConfig.NAME = "name" static
Definition at line 37 of file OpticalPortConfig.java.
Referenced by org.onosproject.net.config.basics.OpticalPortConfig.name(), and org.onosproject.net.config.basics.OpticalPortConfig.portName().
final String org.onosproject.net.config.basics.OpticalPortConfig.PORT = "port" static
Definition at line 38 of file OpticalPortConfig.java.
Referenced by org.onosproject.net.config.basics.OpticalPortConfig.numberName(), and org.onosproject.net.config.basics.OpticalPortConfig.portNumberName().
final String org.onosproject.net.config.basics.OpticalPortConfig.SPEED = "speed" static
Definition at line 43 of file OpticalPortConfig.java.
Referenced by org.onosproject.net.config.basics.OpticalPortConfig.speed().
final String org.onosproject.net.config.basics.OpticalPortConfig.STATIC_LAMBDA = "staticLambda" static
Definition at line 40 of file OpticalPortConfig.java.
Referenced by org.onosproject.net.config.basics.OpticalPortConfig.staticLambda().
final String org.onosproject.net.config.basics.OpticalPortConfig.STATIC_PORT = "staticPort" static
Definition at line 39 of file OpticalPortConfig.java.
Referenced by org.onosproject.net.config.basics.OpticalPortConfig.staticPort().
final String org.onosproject.net.config.basics.OpticalPortConfig.TYPE = "type" static
Definition at line 32 of file OpticalPortConfig.java.
Referenced by org.onosproject.net.config.basics.OpticalPortConfig.portType(), and org.onosproject.net.config.basics.OpticalPortConfig.type().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/config/basics/OpticalPortConfig.java