onos: org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId Class Reference
org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId Class Reference
BGP Multi-Topology ID of the LS attribute.
Public Member Functions
BgpAttrNodeMultiTopologyId (List< Short > multiTopologyId)
Constructor to initialize the Node attribute multi-topology ID.
List< Short > attrMultiTopologyId ()
to get the multi-topology ID.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpAttrNodeMultiTopologyId of (ArrayList< Short > multiTopologyId)
Returns object of this class with specified values.
static BgpAttrNodeMultiTopologyId read (ChannelBuffer cb) throws BgpParseException
Reads the Multi-topology ID of Node attribute.
Static Public Attributes
static final int ATTRNODE_MULTITOPOLOGY = 263
Detailed Description
BGP Multi-Topology ID of the LS attribute.
Definition at line 36 of file BgpAttrNodeMultiTopologyId.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.BgpAttrNodeMultiTopologyId (List< Short > multiTopologyId)
Constructor to initialize the Node attribute multi-topology ID.
Parameters
multiTopologyId multi-topology ID
Definition at line 51 of file BgpAttrNodeMultiTopologyId.java.
Referenced by org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.compareTo(), org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.equals(), org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.of(), and org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.read().
Member Function Documentation
List<Short> org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.attrMultiTopologyId ()
to get the multi-topology ID.
Returns
multitopology ID
Definition at line 98 of file BgpAttrNodeMultiTopologyId.java.
int org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 140 of file BgpAttrNodeMultiTopologyId.java.
References org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.BgpAttrNodeMultiTopologyId(), org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.equals(), and find-device.id.
boolean org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.equals (Object obj)
Definition at line 113 of file BgpAttrNodeMultiTopologyId.java.
References org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.BgpAttrNodeMultiTopologyId().
Referenced by org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.compareTo().
short org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 103 of file BgpAttrNodeMultiTopologyId.java.
References org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.ATTRNODE_MULTITOPOLOGY.
int org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.hashCode ()
Definition at line 108 of file BgpAttrNodeMultiTopologyId.java.
static BgpAttrNodeMultiTopologyId org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.of (ArrayList< Short > multiTopologyId) static
Returns object of this class with specified values.
Parameters
multiTopologyId Prefix Metric
Returns
object of BgpAttrNodeMultiTopologyId
Definition at line 61 of file BgpAttrNodeMultiTopologyId.java.
References org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.BgpAttrNodeMultiTopologyId().
static BgpAttrNodeMultiTopologyId org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.read (ChannelBuffer cb) throws BgpParseException static
Reads the Multi-topology ID of Node attribute.
Parameters
cb ChannelBuffer
Returns
Constructor of BgpAttrNodeMultiTopologyId
Exceptions
BgpParseException while parsing BgpAttrNodeMultiTopologyId
Definition at line 72 of file BgpAttrNodeMultiTopologyId.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.BgpAttrNodeMultiTopologyId(), and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.toString ()
Definition at line 132 of file BgpAttrNodeMultiTopologyId.java.
int org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 126 of file BgpAttrNodeMultiTopologyId.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.ATTRNODE_MULTITOPOLOGY = 263 static
Definition at line 41 of file BgpAttrNodeMultiTopologyId.java.
Referenced by org.onosproject.bgpio.types.attr.BgpAttrNodeMultiTopologyId.getType().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpAttrNodeMultiTopologyId.java