onos: org.onosproject.provider.of.flow.impl.FlowModBuilder Class Reference
org.onosproject.provider.of.flow.impl.FlowModBuilder Class Reference abstract
Builder for OpenFlow flow mods based on FlowRules.
Public Member Functions
abstract OFFlowAdd buildFlowAdd ()
Builds an ADD flow mod.
abstract OFFlowMod buildFlowMod ()
Builds a MODIFY flow mod.
abstract OFFlowDelete buildFlowDel ()
Builds a DELETE flow mod.
Static Public Member Functions
static FlowModBuilder builder (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService)
Creates a new flow mod builder.
Protected Member Functions
FlowModBuilder (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService)
Constructs a flow mod builder.
Match buildMatch ()
Builds the match for the flow mod.
FlowRule flowRule ()
Returns the flow rule for this builder.
OFFactory factory ()
Returns the factory used for building OpenFlow constructs.
Protected Attributes
final Long xid
final Optional< DriverService > driverService
Detailed Description
Builder for OpenFlow flow mods based on FlowRules.
Definition at line 96 of file FlowModBuilder.java.
Constructor & Destructor Documentation
org.onosproject.provider.of.flow.impl.FlowModBuilder.FlowModBuilder (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService) protected
Constructs a flow mod builder.
Parameters
flowRule the flow rule to transform into a flow mod
factory the OpenFlow factory to use to build the flow mod
driverService the device driver service
xid the transaction ID
Definition at line 138 of file FlowModBuilder.java.
References org.onosproject.provider.of.flow.impl.FlowModBuilder.driverService, org.onosproject.provider.of.flow.impl.FlowModBuilder.factory(), and org.onosproject.provider.of.flow.impl.FlowModBuilder.flowRule().
Member Function Documentation
static FlowModBuilder org.onosproject.provider.of.flow.impl.FlowModBuilder.builder (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService) static
Creates a new flow mod builder.
Parameters
flowRule the flow rule to transform into a flow mod
factory the OpenFlow factory to use to build the flow mod
xid the transaction ID
driverService the device driver service
Returns
the new flow mod builder
Definition at line 115 of file FlowModBuilder.java.
abstract OFFlowAdd org.onosproject.provider.of.flow.impl.FlowModBuilder.buildFlowAdd () pure virtual
Builds an ADD flow mod.
Returns
the flow mod
Implemented in org.onosproject.provider.of.flow.impl.FlowModBuilderVer13, and org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.
abstract OFFlowDelete org.onosproject.provider.of.flow.impl.FlowModBuilder.buildFlowDel () pure virtual
Builds a DELETE flow mod.
Returns
the flow mod
Implemented in org.onosproject.provider.of.flow.impl.FlowModBuilderVer13, and org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.
abstract OFFlowMod org.onosproject.provider.of.flow.impl.FlowModBuilder.buildFlowMod () pure virtual
Builds a MODIFY flow mod.
Returns
the flow mod
Implemented in org.onosproject.provider.of.flow.impl.FlowModBuilderVer13, and org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.
Match org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch () protected
Builds the match for the flow mod.
Returns
the match
Definition at line 174 of file FlowModBuilder.java.
References org.onlab.packet.VlanId.ANY, org.onosproject.net.flow.TrafficSelector.criteria(), create-flow.inPort, org.onlab.packet.Ip6Prefix.MAX_MASK_LENGTH, org.onlab.packet.Ip4Prefix.MAX_MASK_LENGTH, org.onlab.packet.VlanId.NONE, org.onlab.packet.IpPrefix.prefixLength(), org.onlab.packet.Ip4Address.toInt(), and org.onlab.packet.IpAddress.toString().
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowAdd(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowDel(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowDel(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowMod(), and org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod().
OFFactory org.onosproject.provider.of.flow.impl.FlowModBuilder.factory () protected
Returns the factory used for building OpenFlow constructs.
Returns
the factory
Definition at line 472 of file FlowModBuilder.java.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowAdd(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowDel(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowDel(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowMod(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod(), and org.onosproject.provider.of.flow.impl.FlowModBuilder.FlowModBuilder().
FlowRule org.onosproject.provider.of.flow.impl.FlowModBuilder.flowRule () protected
Returns the flow rule for this builder.
Returns
the flow rule
Definition at line 463 of file FlowModBuilder.java.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowAdd(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowDel(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowDel(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowMod(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod(), and org.onosproject.provider.of.flow.impl.FlowModBuilder.FlowModBuilder().
Member Data Documentation
final Optional<DriverService> org.onosproject.provider.of.flow.impl.FlowModBuilder.driverService protected
Definition at line 104 of file FlowModBuilder.java.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilder.FlowModBuilder().
final Long org.onosproject.provider.of.flow.impl.FlowModBuilder.xid protected
Definition at line 103 of file FlowModBuilder.java.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowAdd(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowDel(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowDel(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowMod(), and org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod().
The documentation for this class was generated from the following file:
providers/openflow/flow/src/main/java/org/onosproject/provider/of/flow/impl/FlowModBuilder.java