onos: org.onlab.packet.ndp.NeighborAdvertisementTest Class Reference
org.onlab.packet.ndp.NeighborAdvertisementTest Class Reference
Tests for class NeighborAdvertisement.
Public Member Functions
void testSerialize ()
Tests serialize and setters.
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws DeserializationException
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class NeighborAdvertisement.
Definition at line 36 of file NeighborAdvertisementTest.java.
Member Function Documentation
static void org.onlab.packet.ndp.NeighborAdvertisementTest.setUpBeforeClass () throws Exception static
Definition at line 52 of file NeighborAdvertisementTest.java.
References find-link-in-cluster.length.
void org.onlab.packet.ndp.NeighborAdvertisementTest.testDeserialize () throws DeserializationException
Tests deserialize and getters.
Definition at line 100 of file NeighborAdvertisementTest.java.
References org.onlab.packet.ndp.NeighborAdvertisement.getOptions(), org.onlab.packet.ndp.NeighborAdvertisement.getOverrideFlag(), org.onlab.packet.ndp.NeighborAdvertisement.getRouterFlag(), org.onlab.packet.ndp.NeighborAdvertisement.getSolicitedFlag(), org.onlab.packet.ndp.NeighborAdvertisement.getTargetAddress(), find-link-in-cluster.length, and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
void org.onlab.packet.ndp.NeighborAdvertisementTest.testDeserializeBadInput () throws Exception
Definition at line 83 of file NeighborAdvertisementTest.java.
void org.onlab.packet.ndp.NeighborAdvertisementTest.testDeserializeTruncated () throws Exception
Definition at line 88 of file NeighborAdvertisementTest.java.
References org.onlab.packet.ndp.NeighborAdvertisement.HEADER_LENGTH.
void org.onlab.packet.ndp.NeighborAdvertisementTest.testEqual ()
Tests comparator.
Definition at line 120 of file NeighborAdvertisementTest.java.
References org.onlab.packet.ndp.NeighborAdvertisement.equals(), and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
void org.onlab.packet.ndp.NeighborAdvertisementTest.testSerialize ()
Tests serialize and setters.
Definition at line 70 of file NeighborAdvertisementTest.java.
References org.onlab.packet.ndp.NeighborAdvertisement.serialize(), and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ndp/NeighborAdvertisementTest.java