onos: org.onlab.packet.LLC Class Reference
org.onlab.packet.LLC Class Reference
This class represents an Link Local Control header that is used in Ethernet 802.3.
Public Member Functions
byte getDsap ()
void setDsap (final byte dsap)
byte getSsap ()
void setSsap (final byte ssap)
byte getCtrl ()
void setCtrl (final byte ctrl)
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (final byte[] data, final int offset, final int length)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
Static Public Member Functions
static Deserializer< LLC > deserializer ()
Deserializer function for LLC packets.
Static Public Attributes
static final byte LLC_HEADER_LENGTH = 3
Additional Inherited Members
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
This class represents an Link Local Control header that is used in Ethernet 802.3.
Definition at line 31 of file LLC.java.
Member Function Documentation
IPacket org.onlab.packet.LLC.deserialize (final byte[] data, final int offset, final int length)
Definition at line 74 of file LLC.java.
References find-link-in-cluster.length.
static Deserializer<LLC> org.onlab.packet.LLC.deserializer () static
Deserializer function for LLC packets.
Returns
deserializer function
Definition at line 88 of file LLC.java.
References find-link-in-cluster.length, and org.onlab.packet.LLC.LLC_HEADER_LENGTH.
byte org.onlab.packet.LLC.getCtrl ()
Definition at line 55 of file LLC.java.
Referenced by org.onlab.packet.LLCTest.testDeserialize().
byte org.onlab.packet.LLC.getDsap ()
Definition at line 39 of file LLC.java.
Referenced by org.onlab.packet.LLCTest.testDeserialize().
byte org.onlab.packet.LLC.getSsap ()
Definition at line 47 of file LLC.java.
Referenced by org.onlab.packet.LLCTest.testDeserialize().
byte [] org.onlab.packet.LLC.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 64 of file LLC.java.
void org.onlab.packet.LLC.setCtrl (final byte ctrl)
Definition at line 59 of file LLC.java.
void org.onlab.packet.LLC.setDsap (final byte dsap)
Definition at line 43 of file LLC.java.
void org.onlab.packet.LLC.setSsap (final byte ssap)
Definition at line 51 of file LLC.java.
Member Data Documentation
final byte org.onlab.packet.LLC.LLC_HEADER_LENGTH = 3 static
Definition at line 33 of file LLC.java.
Referenced by org.onlab.packet.LLC.deserializer(), and org.onlab.packet.LLCTest.setUp().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/LLC.java