onos: org.onosproject.bgp.controller.impl.BgpPeerImpl Class Reference
org.onosproject.bgp.controller.impl.BgpPeerImpl Class Reference
BGPPeerImpl implements BGPPeer, maintains peer information and store updates in RIB .
Public Member Functions
BgpSessionInfo sessionInfo ()
Return the BGP session info.
BgpPeerImpl (BgpController bgpController, BgpSessionInfo sessionInfo, BgpPacketStatsImpl pktStats)
Initialize peer.
void buildAdjRibIn (List< BgpValueType > pathAttr) throws BgpParseException
Maintaining Adj-RIB-In separately for each peer.
void callAdd (BgpPeerImpl peerImpl, List< BgpLSNlri > nlri, List< BgpValueType > pathAttr) throws BgpParseException
Updates NLRI identifier node in a tree separately based on afi and safi.
PathAttrNlriDetails setPathAttrDetails (BgpLSNlri nlriInfo, List< BgpValueType > pathAttr) throws BgpParseException
Sets BGP path attribute and NLRI details.
void callRemove (BgpPeerImpl peerImpl, List< BgpLSNlri > nlri)
Removes NLRI identifier node in a tree separately based on afi and safi.
AdjRibIn adjRib ()
Return the adjacency RIB-IN.
VpnAdjRibIn vpnAdjRib ()
Return the adjacency RIB-IN with VPN.
final void disconnectPeer ()
Disconnects the bgp peer by closing the TCP connection.
final void sendMessage (BgpMessage m)
Writes the message to the peer.
final void sendMessage (List< BgpMessage > msgs)
Writes the BGPMessage list to the peer.
final boolean isConnected ()
Checks if the bgp peer is still connected.
final void setConnected (boolean connected)
Sets whether the bgp peer is connected.
final void setChannel (Channel channel)
Sets the associated Netty channel for this bgp peer.
final Channel getChannel ()
Gets the associated Netty channel handler for this bgp peer.
String channelId ()
Identifies the channel used to communicate with the bgp peer.
BgpFactory factory ()
Provides the factory for BGP version.
boolean isHandshakeComplete ()
Checks whether the handshake is complete.
String toString ()
Protected Attributes
final Logger log = LoggerFactory.getLogger(BgpPeerImpl.class)
String channelId
boolean isHandShakeComplete = false
Detailed Description
BGPPeerImpl implements BGPPeer, maintains peer information and store updates in RIB .
Definition at line 51 of file BgpPeerImpl.java.
Constructor & Destructor Documentation
org.onosproject.bgp.controller.impl.BgpPeerImpl.BgpPeerImpl (BgpController bgpController, BgpSessionInfo sessionInfo, BgpPacketStatsImpl pktStats)
Initialize peer.
Parameters
bgpController controller instance
sessionInfo bgp session info
pktStats packet statistics
Definition at line 80 of file BgpPeerImpl.java.
References org.onosproject.bgp.controller.impl.BgpPeerImpl.sessionInfo().
Member Function Documentation
AdjRibIn org.onosproject.bgp.controller.impl.BgpPeerImpl.adjRib ()
Return the adjacency RIB-IN.
Returns
adjRib the adjacency RIB-IN
Definition at line 197 of file BgpPeerImpl.java.
void org.onosproject.bgp.controller.impl.BgpPeerImpl.buildAdjRibIn (List< BgpValueType > pathAttr) throws BgpParseException
Maintaining Adj-RIB-In separately for each peer.
Parameters
pathAttr list of Bgp path attributes
Exceptions
BgpParseException while building Adj-Rib-In
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 90 of file BgpPeerImpl.java.
References org.onosproject.bgp.controller.impl.BgpPeerImpl.callAdd(), and org.onosproject.bgp.controller.impl.BgpPeerImpl.callRemove().
void org.onosproject.bgp.controller.impl.BgpPeerImpl.callAdd (BgpPeerImpl peerImpl, List< BgpLSNlri > nlri, List< BgpValueType > pathAttr) throws BgpParseException
Updates NLRI identifier node in a tree separately based on afi and safi.
Parameters
peerImpl BGP peer instance
nlri MpReachNlri path attribute
pathAttr list of BGP path attributes
Exceptions
BgpParseException throws exception
Definition at line 113 of file BgpPeerImpl.java.
References org.onosproject.bgp.controller.impl.BgpPeerImpl.setPathAttrDetails().
Referenced by org.onosproject.bgp.controller.impl.BgpPeerImpl.buildAdjRibIn().
void org.onosproject.bgp.controller.impl.BgpPeerImpl.callRemove (BgpPeerImpl peerImpl, List< BgpLSNlri > nlri)
Removes NLRI identifier node in a tree separately based on afi and safi.
Parameters
peerImpl BGP peer instance
nlri NLRI information
Definition at line 166 of file BgpPeerImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpPeerImpl.buildAdjRibIn().
String org.onosproject.bgp.controller.impl.BgpPeerImpl.channelId ()
Identifies the channel used to communicate with the bgp peer.
Returns
string representation of the connection to the peer
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 277 of file BgpPeerImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpPeerImpl.setChannel(), and org.onosproject.bgp.controller.impl.BgpPeerImpl.toString().
final void org.onosproject.bgp.controller.impl.BgpPeerImpl.disconnectPeer ()
Disconnects the bgp peer by closing the TCP connection.
Results in a call to the channel handler's channelDisconnected method for cleanup
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 215 of file BgpPeerImpl.java.
BgpFactory org.onosproject.bgp.controller.impl.BgpPeerImpl.factory ()
Provides the factory for BGP version.
Returns
BGP version specific factory.
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 282 of file BgpPeerImpl.java.
final Channel org.onosproject.bgp.controller.impl.BgpPeerImpl.getChannel ()
Gets the associated Netty channel handler for this bgp peer.
Returns
Channel channel connected.
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 272 of file BgpPeerImpl.java.
final boolean org.onosproject.bgp.controller.impl.BgpPeerImpl.isConnected ()
Checks if the bgp peer is still connected.
Returns
whether the bgp peer is still connected
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 247 of file BgpPeerImpl.java.
boolean org.onosproject.bgp.controller.impl.BgpPeerImpl.isHandshakeComplete ()
Checks whether the handshake is complete.
Returns
true is finished, false if not.
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 287 of file BgpPeerImpl.java.
References org.onosproject.bgp.controller.impl.BgpPeerImpl.isHandShakeComplete.
final void org.onosproject.bgp.controller.impl.BgpPeerImpl.sendMessage (BgpMessage msg)
Writes the message to the peer.
Parameters
msg the message to write
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 220 of file BgpPeerImpl.java.
final void org.onosproject.bgp.controller.impl.BgpPeerImpl.sendMessage (List< BgpMessage > msgs)
Writes the BGPMessage list to the peer.
Parameters
msgs the messages to be written
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 234 of file BgpPeerImpl.java.
BgpSessionInfo org.onosproject.bgp.controller.impl.BgpPeerImpl.sessionInfo ()
Return the BGP session info.
Returns
sessionInfo bgp session info
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 69 of file BgpPeerImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpPeerImpl.BgpPeerImpl(), and org.onosproject.bgp.controller.impl.BgpPeerImpl.toString().
final void org.onosproject.bgp.controller.impl.BgpPeerImpl.setChannel (Channel channel)
Sets the associated Netty channel for this bgp peer.
Parameters
channel the Netty channel
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 257 of file BgpPeerImpl.java.
References org.onosproject.bgp.controller.impl.BgpPeerImpl.channelId(), and org.onlab.packet.IpAddress.isIp4().
final void org.onosproject.bgp.controller.impl.BgpPeerImpl.setConnected (boolean connected)
Sets whether the bgp peer is connected.
Parameters
connected whether the bgp peer is connected
Implements org.onosproject.bgp.controller.BgpPeer.
Definition at line 252 of file BgpPeerImpl.java.
PathAttrNlriDetails org.onosproject.bgp.controller.impl.BgpPeerImpl.setPathAttrDetails (BgpLSNlri nlriInfo, List< BgpValueType > pathAttr) throws BgpParseException
Sets BGP path attribute and NLRI details.
Parameters
nlriInfo MpReachNlri path attribute
pathAttr list of BGP path attributes
Returns
details object of PathAttrNlriDetails
Exceptions
BgpParseException throw exception
Definition at line 151 of file BgpPeerImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpPeerImpl.callAdd().
String org.onosproject.bgp.controller.impl.BgpPeerImpl.toString ()
Definition at line 292 of file BgpPeerImpl.java.
References org.onosproject.bgp.controller.impl.BgpPeerImpl.channelId(), and org.onosproject.bgp.controller.impl.BgpPeerImpl.sessionInfo().
VpnAdjRibIn org.onosproject.bgp.controller.impl.BgpPeerImpl.vpnAdjRib ()
Return the adjacency RIB-IN with VPN.
Returns
vpnAdjRib the adjacency RIB-IN with VPN
Definition at line 206 of file BgpPeerImpl.java.
Member Data Documentation
String org.onosproject.bgp.controller.impl.BgpPeerImpl.channelId protected
Definition at line 59 of file BgpPeerImpl.java.
boolean org.onosproject.bgp.controller.impl.BgpPeerImpl.isHandShakeComplete = false protected
Definition at line 61 of file BgpPeerImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpPeerImpl.isHandshakeComplete().
final Logger org.onosproject.bgp.controller.impl.BgpPeerImpl.log = LoggerFactory.getLogger(BgpPeerImpl.class) protected
Definition at line 53 of file BgpPeerImpl.java.
The documentation for this class was generated from the following file:
bgp/ctl/src/main/java/org/onosproject/bgp/controller/impl/BgpPeerImpl.java