onos: org.onosproject.net.driver.DefaultDriverHandler Class Reference
org.onosproject.net.driver.DefaultDriverHandler Class Reference
Default implementation of driver handler.
Public Member Functions
DefaultDriverHandler (DefaultDriverData data)
Creates new driver handler with the attached driver data.
Driver driver ()
Returns the parent device driver.
DriverData data ()
Returns the device driver data.
String toString ()
Static Protected Attributes
static ServiceDirectory serviceDirectory = new DefaultServiceDirectory()
Detailed Description
Default implementation of driver handler.
Definition at line 26 of file DefaultDriverHandler.java.
Constructor & Destructor Documentation
org.onosproject.net.driver.DefaultDriverHandler.DefaultDriverHandler (DefaultDriverData data)
Creates new driver handler with the attached driver data.
Parameters
data driver data to attach
Definition at line 38 of file DefaultDriverHandler.java.
References org.onosproject.net.driver.DefaultDriverHandler.data().
Member Function Documentation
DriverData org.onosproject.net.driver.DefaultDriverHandler.data ()
Returns the device driver data.
Returns
device driver data
Implements org.onosproject.net.driver.DriverHandler.
Definition at line 48 of file DefaultDriverHandler.java.
Referenced by org.onosproject.net.driver.DefaultDriverHandler.DefaultDriverHandler(), and org.onosproject.net.driver.DefaultDriverHandler.toString().
Driver org.onosproject.net.driver.DefaultDriverHandler.driver ()
Returns the parent device driver.
Returns
device driver
Implements org.onosproject.net.driver.DriverHandler.
Definition at line 43 of file DefaultDriverHandler.java.
String org.onosproject.net.driver.DefaultDriverHandler.toString ()
Definition at line 63 of file DefaultDriverHandler.java.
References org.onosproject.net.driver.DefaultDriverHandler.data().
Referenced by org.onosproject.net.driver.DefaultDriverHandlerTest.basics().
Member Data Documentation
ServiceDirectory org.onosproject.net.driver.DefaultDriverHandler.serviceDirectory = new DefaultServiceDirectory() static protected
Definition at line 31 of file DefaultDriverHandler.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/driver/DefaultDriverHandler.java