onos: org.onosproject.common.DefaultTopologyTest Class Reference
org.onosproject.common.DefaultTopologyTest Class Reference
Test of the default topology implementation.
Public Member Functions
void setUp ()
void pathRelated ()
void pointRelated ()
void clusterRelated ()
Static Public Member Functions
static Link link (String src, int sp, String dst, int dp)
static Device device (String id)
static DeviceId did (String id)
Static Public Attributes
static final ProviderId PID = new ProviderId("of", "foo.bar")
static final DeviceId D1 = deviceId("of:1")
static final DeviceId D2 = deviceId("of:2")
static final DeviceId D3 = deviceId("of:3")
static final DeviceId D4 = deviceId("of:4")
static final DeviceId D5 = deviceId("of:5")
static final PortNumber P1 = portNumber(1)
static final PortNumber P2 = portNumber(2)
static final LinkWeight WEIGHT
Detailed Description
Test of the default topology implementation.
Definition at line 46 of file DefaultTopologyTest.java.
Member Function Documentation
void org.onosproject.common.DefaultTopologyTest.clusterRelated ()
Definition at line 112 of file DefaultTopologyTest.java.
References org.onosproject.common.DefaultTopologyTest.D1, org.onosproject.common.DefaultTopologyTest.D2, and org.onosproject.common.DefaultTopologyTest.D5.
static Device org.onosproject.common.DefaultTopologyTest.device (String id) static
Definition at line 131 of file DefaultTopologyTest.java.
References org.onosproject.common.DefaultTopologyTest.did(), and org.onosproject.common.DefaultTopologyTest.PID.
Referenced by org.onosproject.common.DefaultTopologyTest.setUp().
static DeviceId org.onosproject.common.DefaultTopologyTest.did (String id) static
Definition at line 137 of file DefaultTopologyTest.java.
References find-flow.deviceId.
Referenced by org.onosproject.common.DefaultTopologyTest.device(), and org.onosproject.common.DefaultTopologyTest.link().
static Link org.onosproject.common.DefaultTopologyTest.link (String src, int sp, String dst, int dp) static
Definition at line 124 of file DefaultTopologyTest.java.
References org.onosproject.common.DefaultTopologyTest.did(), and org.onosproject.common.DefaultTopologyTest.PID.
Referenced by org.onosproject.common.DefaultTopologyTest.setUp().
void org.onosproject.common.DefaultTopologyTest.pathRelated ()
Definition at line 89 of file DefaultTopologyTest.java.
References org.onosproject.common.DefaultTopologyTest.D1, org.onosproject.common.DefaultTopologyTest.D2, org.onosproject.common.DefaultTopologyTest.D3, org.onosproject.common.DefaultTopologyTest.D5, and org.onosproject.common.DefaultTopologyTest.WEIGHT.
void org.onosproject.common.DefaultTopologyTest.pointRelated ()
Definition at line 104 of file DefaultTopologyTest.java.
References org.onosproject.common.DefaultTopologyTest.D1, org.onosproject.common.DefaultTopology.isInfrastructure(), org.onosproject.common.DefaultTopologyTest.P1, and org.onosproject.common.DefaultTopologyTest.P2.
void org.onosproject.common.DefaultTopologyTest.setUp ()
Definition at line 66 of file DefaultTopologyTest.java.
References org.onosproject.net.topology.ClusterId.clusterId(), org.onosproject.common.DefaultTopologyTest.device(), org.onosproject.common.DefaultTopologyTest.link(), and org.onosproject.common.DefaultTopologyTest.PID.
Member Data Documentation
final DeviceId org.onosproject.common.DefaultTopologyTest.D1 = deviceId("of:1") static
Definition at line 50 of file DefaultTopologyTest.java.
Referenced by org.onosproject.common.DefaultTopologyTest.clusterRelated(), org.onosproject.common.DefaultTopologyTest.pathRelated(), and org.onosproject.common.DefaultTopologyTest.pointRelated().
final DeviceId org.onosproject.common.DefaultTopologyTest.D2 = deviceId("of:2") static
Definition at line 51 of file DefaultTopologyTest.java.
Referenced by org.onosproject.common.DefaultTopologyTest.clusterRelated(), and org.onosproject.common.DefaultTopologyTest.pathRelated().
final DeviceId org.onosproject.common.DefaultTopologyTest.D3 = deviceId("of:3") static
Definition at line 52 of file DefaultTopologyTest.java.
Referenced by org.onosproject.common.DefaultTopologyTest.pathRelated().
final DeviceId org.onosproject.common.DefaultTopologyTest.D4 = deviceId("of:4") static
Definition at line 53 of file DefaultTopologyTest.java.
final DeviceId org.onosproject.common.DefaultTopologyTest.D5 = deviceId("of:5") static
Definition at line 54 of file DefaultTopologyTest.java.
Referenced by org.onosproject.common.DefaultTopologyTest.clusterRelated(), and org.onosproject.common.DefaultTopologyTest.pathRelated().
final PortNumber org.onosproject.common.DefaultTopologyTest.P1 = portNumber(1) static
Definition at line 56 of file DefaultTopologyTest.java.
Referenced by org.onosproject.common.DefaultTopologyTest.pointRelated().
final PortNumber org.onosproject.common.DefaultTopologyTest.P2 = portNumber(2) static
Definition at line 57 of file DefaultTopologyTest.java.
Referenced by org.onosproject.common.DefaultTopologyTest.pointRelated().
final ProviderId org.onosproject.common.DefaultTopologyTest.PID = new ProviderId("of", "foo.bar") static
Definition at line 48 of file DefaultTopologyTest.java.
Referenced by org.onosproject.common.DefaultTopologyTest.device(), org.onosproject.common.DefaultTopologyTest.link(), and org.onosproject.common.DefaultTopologyTest.setUp().
final LinkWeight org.onosproject.common.DefaultTopologyTest.WEIGHT static
Initial value:
= edge ->
            edge.src().deviceId().equals(D4) || edge.dst().deviceId().equals(D4)
                    ? 2.0 : 1.0
Definition at line 59 of file DefaultTopologyTest.java.
Referenced by org.onosproject.common.DefaultTopologyTest.pathRelated().
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/common/DefaultTopologyTest.java