onos: org.onosproject.vtnweb.web.PortPairCodecTest Class Reference
org.onosproject.vtnweb.web.PortPairCodecTest Class Reference
Port pair codec unit tests.
Public Member Functions
void setUp ()
Sets up for each test.
void codecPortPairTest () throws IOException
Checks that a simple port pair decodes properly.
Detailed Description
Port pair codec unit tests.
Definition at line 39 of file PortPairCodecTest.java.
Member Function Documentation
void org.onosproject.vtnweb.web.PortPairCodecTest.codecPortPairTest () throws IOException
Checks that a simple port pair decodes properly.
Exceptions
IOException if the resource cannot be processed
Definition at line 78 of file PortPairCodecTest.java.
References org.onosproject.vtnrsc.PortPair.description(), org.onosproject.vtnrsc.PortPair.egress(), org.onosproject.vtnrsc.PortPair.ingress(), org.onosproject.vtnrsc.PortPair.name(), org.onosproject.vtnrsc.PortPair.portPairId(), org.onosproject.vtnrsc.PortPair.tenantId(), and org.onosproject.vtnrsc.PortPairId.toString().
void org.onosproject.vtnweb.web.PortPairCodecTest.setUp ()
Sets up for each test.
Creates a context and fetches the port pair codec.
Definition at line 48 of file PortPairCodecTest.java.
The documentation for this class was generated from the following file:
apps/vtn/vtnweb/src/test/java/org/onosproject/vtnweb/web/PortPairCodecTest.java