onos: org.onosproject.pcepio.types.PcepNaiIpv4Adjacency Class Reference
org.onosproject.pcepio.types.PcepNaiIpv4Adjacency Class Reference
Provides Pcep Nai Ipv4 Adjacency.
Public Member Functions
PcepNaiIpv4Adjacency (int localIpv4, int remoteIpv4)
Constructor to initialize variables.
byte getType ()
To get the ST type of the NAI information.
int write (ChannelBuffer bb)
To write the object information to channelBuffer.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static PcepNaiIpv4Adjacency of (int localIpv4Addr, int remoteIpv4Addr)
Returns Object of Pcep nai Ipv4 Adjacency.
static PcepNaiIpv4Adjacency read (ChannelBuffer cb)
Reads the channel buffer and returns object of PcepNAIIpv4AdjacencyVer1.
Static Public Attributes
static final byte ST_TYPE = 0x03
Detailed Description
Provides Pcep Nai Ipv4 Adjacency.
Definition at line 29 of file PcepNaiIpv4Adjacency.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.PcepNaiIpv4Adjacency (int localIpv4, int remoteIpv4)
Constructor to initialize variables.
Parameters
localIpv4 local ipv4 address
remoteIpv4 remote ipv4 address
Definition at line 41 of file PcepNaiIpv4Adjacency.java.
Referenced by org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.equals(), org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.of(), and org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.equals (Object obj)
Definition at line 88 of file PcepNaiIpv4Adjacency.java.
References org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.PcepNaiIpv4Adjacency().
byte org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.getType ()
To get the ST type of the NAI information.
Returns
type of ST info
Implements org.onosproject.pcepio.protocol.PcepNai.
Definition at line 58 of file PcepNaiIpv4Adjacency.java.
References org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.ST_TYPE.
int org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.hashCode ()
Definition at line 83 of file PcepNaiIpv4Adjacency.java.
static PcepNaiIpv4Adjacency org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.of (int localIpv4Addr, int remoteIpv4Addr) static
Returns Object of Pcep nai Ipv4 Adjacency.
Parameters
localIpv4Addr local ipv4 address
remoteIpv4Addr remote ipv4 address
Returns
Object of Pcep nai Ipv4 Adjacency
Definition at line 53 of file PcepNaiIpv4Adjacency.java.
References org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.PcepNaiIpv4Adjacency().
static PcepNaiIpv4Adjacency org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.read (ChannelBuffer cb) static
Reads the channel buffer and returns object of PcepNAIIpv4AdjacencyVer1.
Parameters
cb of channel buffer
Returns
object of PcepNAIIpv4Adjacency
Definition at line 76 of file PcepNaiIpv4Adjacency.java.
References org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.PcepNaiIpv4Adjacency().
String org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.toString ()
Definition at line 101 of file PcepNaiIpv4Adjacency.java.
int org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.write (ChannelBuffer cb)
To write the object information to channelBuffer.
Parameters
cb of type channel buffer
Returns
length of written bytes.
Implements org.onosproject.pcepio.protocol.PcepNai.
Definition at line 63 of file PcepNaiIpv4Adjacency.java.
Member Data Documentation
final byte org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.ST_TYPE = 0x03 static
Definition at line 31 of file PcepNaiIpv4Adjacency.java.
Referenced by org.onosproject.pcepio.types.PcepNaiIpv4Adjacency.getType().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PcepNaiIpv4Adjacency.java