onos: org.onosproject.pcepio.types.AutonomousSystemTlv Class Reference
org.onosproject.pcepio.types.AutonomousSystemTlv Class Reference
Provides Autonomous-System-Tlv which contains opaque value (32 Bit AS Number).
Public Member Functions
AutonomousSystemTlv (int rawValue)
Constructor to initialize rawValue.
int getInt ()
Returns opaque value.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static AutonomousSystemTlv of (final int raw)
Returns newly created AutonomousSystemTlv object.
static AutonomousSystemTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of AutonomousSystemTlv.
Static Public Attributes
static final short TYPE = 100
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(AutonomousSystemTlv.class)
Detailed Description
Provides Autonomous-System-Tlv which contains opaque value (32 Bit AS Number).
Definition at line 30 of file AutonomousSystemTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.AutonomousSystemTlv.AutonomousSystemTlv (int rawValue)
Constructor to initialize rawValue.
Parameters
rawValue Autonomous-System-Tlv
Definition at line 54 of file AutonomousSystemTlv.java.
Referenced by org.onosproject.pcepio.types.AutonomousSystemTlv.equals(), and org.onosproject.pcepio.types.AutonomousSystemTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.AutonomousSystemTlv.equals (Object obj)
Definition at line 98 of file AutonomousSystemTlv.java.
References org.onosproject.pcepio.types.AutonomousSystemTlv.AutonomousSystemTlv().
int org.onosproject.pcepio.types.AutonomousSystemTlv.getInt ()
Returns opaque value.
Returns
rawValue opaque value.
Definition at line 73 of file AutonomousSystemTlv.java.
short org.onosproject.pcepio.types.AutonomousSystemTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 88 of file AutonomousSystemTlv.java.
References org.onosproject.pcepio.types.AutonomousSystemTlv.LENGTH.
short org.onosproject.pcepio.types.AutonomousSystemTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 83 of file AutonomousSystemTlv.java.
References org.onosproject.pcepio.types.AutonomousSystemTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.AutonomousSystemTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 78 of file AutonomousSystemTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.AutonomousSystemTlv.hashCode ()
Definition at line 93 of file AutonomousSystemTlv.java.
static AutonomousSystemTlv org.onosproject.pcepio.types.AutonomousSystemTlv.of (final int raw) static
Returns newly created AutonomousSystemTlv object.
Parameters
raw value of opaque.
Returns
object of Autonomous-System-Tlv
Definition at line 64 of file AutonomousSystemTlv.java.
References org.onosproject.pcepio.types.AutonomousSystemTlv.AutonomousSystemTlv().
static AutonomousSystemTlv org.onosproject.pcepio.types.AutonomousSystemTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of AutonomousSystemTlv.
Parameters
c input channel buffer
Returns
object of Autonomous-System-Tlv
Definition at line 124 of file AutonomousSystemTlv.java.
String org.onosproject.pcepio.types.AutonomousSystemTlv.toString ()
Definition at line 129 of file AutonomousSystemTlv.java.
References org.onosproject.pcepio.types.AutonomousSystemTlv.LENGTH, and org.onosproject.pcepio.types.AutonomousSystemTlv.TYPE.
int org.onosproject.pcepio.types.AutonomousSystemTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 110 of file AutonomousSystemTlv.java.
References org.onosproject.pcepio.types.AutonomousSystemTlv.LENGTH, and org.onosproject.pcepio.types.AutonomousSystemTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.AutonomousSystemTlv.LENGTH = 4 static
Definition at line 45 of file AutonomousSystemTlv.java.
Referenced by org.onosproject.pcepio.types.AutonomousSystemTlv.getLength(), org.onosproject.pcepio.types.AutonomousSystemTlv.toString(), and org.onosproject.pcepio.types.AutonomousSystemTlv.write().
final Logger org.onosproject.pcepio.types.AutonomousSystemTlv.log = LoggerFactory.getLogger(AutonomousSystemTlv.class) static protected
Definition at line 42 of file AutonomousSystemTlv.java.
final short org.onosproject.pcepio.types.AutonomousSystemTlv.TYPE = 100 static
Definition at line 44 of file AutonomousSystemTlv.java.
Referenced by org.onosproject.pcepio.types.AutonomousSystemTlv.getType(), org.onosproject.pcepio.types.AutonomousSystemTlv.toString(), and org.onosproject.pcepio.types.AutonomousSystemTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/AutonomousSystemTlv.java