onos: org.onosproject.driver.ovsdb.OvsdbTunnelConfig Class Reference
org.onosproject.driver.ovsdb.OvsdbTunnelConfig Class Reference
OVSDB-based implementation of tunnel config behaviour.
Public Member Functions
void createTunnel (TunnelDescription tunnel)
Creates a tunnel on this device.
boolean createTunnelInterface (BridgeName bridgeName, TunnelDescription tunnel)
Creates a tunnel interface on a given bridge of this device.
void removeTunnel (TunnelDescription tunnel)
Removes a tunnel on this device.
void updateTunnel (TunnelDescription tunnel)
Updates a tunnel on this device.
Collection< TunnelDescription > getTunnels ()
Returns tunnels created on this device.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Detailed Description
OVSDB-based implementation of tunnel config behaviour.
Definition at line 42 of file OvsdbTunnelConfig.java.
Member Function Documentation
void org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnel (TunnelDescription tunnel)
Creates a tunnel on this device.
Parameters
tunnel tunnel descriptor
Implements org.onosproject.net.behaviour.TunnelConfig.
Definition at line 50 of file OvsdbTunnelConfig.java.
References org.onosproject.net.behaviour.TunnelDescription.dst(), org.onosproject.net.driver.AbstractHandlerBehaviour.handler(), and org.onosproject.net.behaviour.TunnelDescription.src().
boolean org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnelInterface (BridgeName bridgeName, TunnelDescription tunnel)
Creates a tunnel interface on a given bridge of this device.
Parameters
bridgeName bridge name
tunnel tunnel description
Returns
true if succeeds, false otherwise
Implements org.onosproject.net.behaviour.TunnelConfig.
Definition at line 68 of file OvsdbTunnelConfig.java.
References org.onosproject.net.Description.annotations(), org.onosproject.net.behaviour.TunnelDescription.dst(), org.onosproject.net.driver.AbstractHandlerBehaviour.handler(), org.onosproject.net.behaviour.TunnelDescription.src(), org.onosproject.net.behaviour.TunnelDescription.tunnelName(), and org.onosproject.net.behaviour.TunnelDescription.type().
Collection<TunnelDescription> org.onosproject.driver.ovsdb.OvsdbTunnelConfig.getTunnels ()
Returns tunnels created on this device.
Returns
collection of tunnels
Implements org.onosproject.net.behaviour.TunnelConfig.
Definition at line 108 of file OvsdbTunnelConfig.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler(), org.onosproject.net.behaviour.IpTunnelEndPoint.ipTunnelPoint(), and org.onosproject.net.behaviour.TunnelName.tunnelName().
void org.onosproject.driver.ovsdb.OvsdbTunnelConfig.removeTunnel (TunnelDescription tunnel)
Removes a tunnel on this device.
Parameters
tunnel tunnel descriptor
Implements org.onosproject.net.behaviour.TunnelConfig.
Definition at line 84 of file OvsdbTunnelConfig.java.
References org.onosproject.net.behaviour.TunnelDescription.dst(), org.onosproject.net.driver.AbstractHandlerBehaviour.handler(), and org.onosproject.net.behaviour.TunnelDescription.src().
void org.onosproject.driver.ovsdb.OvsdbTunnelConfig.updateTunnel (TunnelDescription tunnel)
Updates a tunnel on this device.
Parameters
tunnel tunnel descriptor
Implements org.onosproject.net.behaviour.TunnelConfig.
Definition at line 102 of file OvsdbTunnelConfig.java.
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/ovsdb/OvsdbTunnelConfig.java