onos: org.onosproject.store.trivial.SimpleGroupStore Class Reference
org.onosproject.store.trivial.SimpleGroupStore Class Reference
Manages inventory of group entries using trivial in-memory implementation.
Public Member Functions
void activate ()
void deactivate ()
int getGroupCount (DeviceId deviceId)
Returns the number of groups for the specified device in the store.
Iterable< Group > getGroups (DeviceId deviceId)
Returns the groups associated with a device.
Group getGroup (DeviceId deviceId, GroupKey appCookie)
Returns the stored group entry.
Group getGroup (DeviceId deviceId, GroupId groupId)
Returns the stored group entry for an id.
void storeGroupDescription (GroupDescription groupDesc)
Stores a new group entry using the information from group description.
void updateGroupDescription (DeviceId deviceId, GroupKey oldAppCookie, UpdateType type, GroupBuckets newBuckets, GroupKey newAppCookie)
Updates the existing group entry with the information from group description.
void deleteGroupDescription (DeviceId deviceId, GroupKey appCookie)
Triggers deleting the existing group entry.
void addOrUpdateGroupEntry (Group group)
Stores a new group entry, or updates an existing entry.
void removeGroupEntry (Group group)
Removes the group entry from store.
void deviceInitialAuditCompleted (DeviceId deviceId, boolean completed)
Indicates the first group audit is completed.
boolean deviceInitialAuditStatus (DeviceId deviceId)
Retrieves the initial group audit status for a device.
void groupOperationFailed (DeviceId deviceId, GroupOperation operation)
Indicates the group operations failed.
void addOrUpdateExtraneousGroupEntry (Group group)
A group entry that is present in switch but not in the store.
void removeExtraneousGroupEntry (Group group)
Remove the group entry from extraneous database.
Iterable< Group > getExtraneousGroups (DeviceId deviceId)
Returns the extraneous groups associated with a device.
void pushGroupMetrics (DeviceId deviceId, Collection< Group > groupEntries)
Submits the group metrics to store for a given device ID.
Detailed Description
Manages inventory of group entries using trivial in-memory implementation.
Definition at line 66 of file SimpleGroupStore.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleGroupStore.activate ()
Definition at line 90 of file SimpleGroupStore.java.
void org.onosproject.store.trivial.SimpleGroupStore.addOrUpdateExtraneousGroupEntry (Group group)
A group entry that is present in switch but not in the store.
Parameters
group group entry
Implements org.onosproject.net.group.GroupStore.
Definition at line 555 of file SimpleGroupStore.java.
References org.onosproject.net.group.GroupDescription.deviceId(), and org.onosproject.net.group.Group.referenceCount().
void org.onosproject.store.trivial.SimpleGroupStore.addOrUpdateGroupEntry (Group group)
Stores a new group entry, or updates an existing entry.
Parameters
group group entry
Implements org.onosproject.net.group.GroupStore.
Definition at line 410 of file SimpleGroupStore.java.
References org.onosproject.net.group.Group.GroupState.ADDED, org.onosproject.net.group.GroupDescription.buckets(), org.onosproject.net.group.GroupDescription.deviceId(), org.onosproject.net.group.Group.id(), org.onosproject.net.group.Group.GroupState.PENDING_ADD, org.onosproject.net.group.Group.GroupState.PENDING_UPDATE, and org.onosproject.net.group.Group.state().
void org.onosproject.store.trivial.SimpleGroupStore.deactivate ()
Definition at line 95 of file SimpleGroupStore.java.
void org.onosproject.store.trivial.SimpleGroupStore.deleteGroupDescription (DeviceId deviceId, GroupKey appCookie)
Triggers deleting the existing group entry.
Parameters
deviceId the device ID
appCookie the group key
Implements org.onosproject.net.group.GroupStore.
Definition at line 388 of file SimpleGroupStore.java.
References find-flow.deviceId, and org.onosproject.net.group.Group.GroupState.PENDING_DELETE.
void org.onosproject.store.trivial.SimpleGroupStore.deviceInitialAuditCompleted (DeviceId deviceId, boolean completed)
Indicates the first group audit is completed.
Parameters
deviceId the device ID
completed initial audit status
Implements org.onosproject.net.group.GroupStore.
Definition at line 480 of file SimpleGroupStore.java.
References find-flow.deviceId.
Referenced by org.onosproject.store.trivial.SimpleGroupStore.pushGroupMetrics().
boolean org.onosproject.store.trivial.SimpleGroupStore.deviceInitialAuditStatus (DeviceId deviceId)
Retrieves the initial group audit status for a device.
Parameters
deviceId the device ID
Returns
initial group audit status
Implements org.onosproject.net.group.GroupStore.
Definition at line 512 of file SimpleGroupStore.java.
Referenced by org.onosproject.store.trivial.SimpleGroupStore.pushGroupMetrics().
Iterable<Group> org.onosproject.store.trivial.SimpleGroupStore.getExtraneousGroups (DeviceId deviceId)
Returns the extraneous groups associated with a device.
Parameters
deviceId the device ID
Returns
the extraneous group entries
Implements org.onosproject.net.group.GroupStore.
Definition at line 573 of file SimpleGroupStore.java.
Referenced by org.onosproject.store.trivial.SimpleGroupStore.pushGroupMetrics().
Group org.onosproject.store.trivial.SimpleGroupStore.getGroup (DeviceId deviceId, GroupKey appCookie)
Returns the stored group entry.
Parameters
deviceId the device ID
appCookie the group key
Returns
a group associated with the key
Implements org.onosproject.net.group.GroupStore.
Definition at line 202 of file SimpleGroupStore.java.
Referenced by org.onosproject.store.trivial.SimpleGroupStore.pushGroupMetrics(), org.onosproject.store.trivial.SimpleGroupStore.storeGroupDescription(), and org.onosproject.store.trivial.SimpleGroupStore.updateGroupDescription().
Group org.onosproject.store.trivial.SimpleGroupStore.getGroup (DeviceId deviceId, GroupId groupId)
Returns the stored group entry for an id.
Parameters
deviceId the device ID
groupId the group identifier
Returns
a group associated with the key
Implements org.onosproject.net.group.GroupStore.
Definition at line 209 of file SimpleGroupStore.java.
int org.onosproject.store.trivial.SimpleGroupStore.getGroupCount (DeviceId deviceId)
Returns the number of groups for the specified device in the store.
Returns
number of groups for the specified device
Implements org.onosproject.net.group.GroupStore.
Definition at line 174 of file SimpleGroupStore.java.
Iterable<Group> org.onosproject.store.trivial.SimpleGroupStore.getGroups (DeviceId deviceId)
Returns the groups associated with a device.
Parameters
deviceId the device ID
Returns
the group entries
Implements org.onosproject.net.group.GroupStore.
Definition at line 187 of file SimpleGroupStore.java.
Referenced by org.onosproject.store.trivial.SimpleGroupStore.pushGroupMetrics().
void org.onosproject.store.trivial.SimpleGroupStore.groupOperationFailed (DeviceId deviceId, GroupOperation operation)
Indicates the group operations failed.
Parameters
deviceId the device ID
operation the group operation failed
Implements org.onosproject.net.group.GroupStore.
Definition at line 520 of file SimpleGroupStore.java.
References find-flow.deviceId, and org.onosproject.net.group.GroupDescription.deviceId().
void org.onosproject.store.trivial.SimpleGroupStore.pushGroupMetrics (DeviceId deviceId, Collection< Group > groupEntries)
Submits the group metrics to store for a given device ID.
Parameters
deviceId the device ID
groupEntries the group entries as received from southbound
Implements org.onosproject.net.group.GroupStore.
Definition at line 580 of file SimpleGroupStore.java.
References find-flow.deviceId, org.onosproject.store.trivial.SimpleGroupStore.deviceInitialAuditCompleted(), org.onosproject.store.trivial.SimpleGroupStore.deviceInitialAuditStatus(), org.onosproject.store.trivial.SimpleGroupStore.getExtraneousGroups(), org.onosproject.store.trivial.SimpleGroupStore.getGroup(), org.onosproject.store.trivial.SimpleGroupStore.getGroups(), and org.onosproject.store.trivial.SimpleGroupStore.removeExtraneousGroupEntry().
void org.onosproject.store.trivial.SimpleGroupStore.removeExtraneousGroupEntry (Group group)
Remove the group entry from extraneous database.
Parameters
group group entry
Implements org.onosproject.net.group.GroupStore.
Definition at line 566 of file SimpleGroupStore.java.
References org.onosproject.net.group.GroupDescription.deviceId().
Referenced by org.onosproject.store.trivial.SimpleGroupStore.pushGroupMetrics().
void org.onosproject.store.trivial.SimpleGroupStore.removeGroupEntry (Group group)
Removes the group entry from store.
Parameters
group group entry
Implements org.onosproject.net.group.GroupStore.
Definition at line 462 of file SimpleGroupStore.java.
References org.onosproject.net.group.GroupDescription.deviceId(), and org.onosproject.net.group.Group.id().
void org.onosproject.store.trivial.SimpleGroupStore.storeGroupDescription (GroupDescription groupDesc)
Stores a new group entry using the information from group description.
Parameters
groupDesc group description to be used to create group entry
Implements org.onosproject.net.group.GroupStore.
Definition at line 245 of file SimpleGroupStore.java.
References org.onosproject.net.group.GroupDescription.deviceId(), org.onosproject.store.trivial.SimpleGroupStore.getGroup(), and org.onosproject.net.group.Group.GroupState.WAITING_AUDIT_COMPLETE.
void org.onosproject.store.trivial.SimpleGroupStore.updateGroupDescription (DeviceId deviceId, GroupKey oldAppCookie, UpdateType type, GroupBuckets newBuckets, GroupKey newAppCookie)
Updates the existing group entry with the information from group description.
Parameters
deviceId the device ID
oldAppCookie the current group key
type update type
newBuckets group buckets for updates
newAppCookie optional new group key
Implements org.onosproject.net.group.GroupStore.
Definition at line 303 of file SimpleGroupStore.java.
References org.onosproject.net.group.GroupDescription.deviceId(), org.onosproject.store.trivial.SimpleGroupStore.getGroup(), org.onosproject.net.group.GroupDescription.givenGroupId(), org.onosproject.net.group.Group.id(), and org.onosproject.net.group.Group.GroupState.PENDING_UPDATE.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleGroupStore.java