onos: org.onosproject.net.OduSignalId Class Reference
org.onosproject.net.OduSignalId Class Reference
Implementation of ODU Signal ID.
Public Member Functions
OduSignalId (int tributaryPortNumber, int tributarySlotLen, byte[] tributarySlotBitmap)
Creates an instance with the specified arguments.
int tributaryPortNumber ()
Returns tributary port number.
int tributarySlotLength ()
Returns tributary slot length.
byte[] tributarySlotBitmap ()
Returns tributary slot bitmap.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static OduSignalId oduSignalId (int tributaryPortNumber, int tributarySlotLen, byte[] tributarySlotBitmap)
Returns the OduSignalId representing the specified parameters.
Static Public Attributes
static final int TRIBUTARY_SLOT_BITMAP_SIZE = 10
Detailed Description
Implementation of ODU Signal ID.
See ITU G.709 "Interfaces for the Optical Transport Network (OTN)".
Definition at line 33 of file OduSignalId.java.
Constructor & Destructor Documentation
org.onosproject.net.OduSignalId.OduSignalId (int tributaryPortNumber, int tributarySlotLen, byte[] tributarySlotBitmap)
Creates an instance with the specified arguments.
Parameters
tributaryPortNumber tributary port number
tributarySlotLen tributary slot len
tributarySlotBitmap tributary slot bitmap
Definition at line 48 of file OduSignalId.java.
References find-link-in-cluster.length, org.onlab.util.HexString.toHexString(), org.onosproject.net.OduSignalId.TRIBUTARY_SLOT_BITMAP_SIZE, org.onosproject.net.OduSignalId.tributaryPortNumber(), and org.onosproject.net.OduSignalId.tributarySlotBitmap().
Referenced by org.onosproject.net.OduSignalId.equals(), and org.onosproject.net.OduSignalId.oduSignalId().
Member Function Documentation
boolean org.onosproject.net.OduSignalId.equals (Object obj)
Definition at line 115 of file OduSignalId.java.
References org.onosproject.net.OduSignalId.OduSignalId(), and org.onosproject.net.OduSignalId.tributarySlotBitmap().
int org.onosproject.net.OduSignalId.hashCode ()
Definition at line 110 of file OduSignalId.java.
References org.onosproject.net.OduSignalId.tributaryPortNumber(), org.onosproject.net.OduSignalId.tributarySlotBitmap(), and org.onosproject.net.OduSignalId.tributarySlotLength().
static OduSignalId org.onosproject.net.OduSignalId.oduSignalId (int tributaryPortNumber, int tributarySlotLen, byte[] tributarySlotBitmap) static
Returns the OduSignalId representing the specified parameters.
Parameters
tributaryPortNumber tributary port number
tributarySlotLen tributary slot len
tributarySlotBitmap tributary slot bitmap
Returns
OduSignalId
Definition at line 76 of file OduSignalId.java.
References org.onosproject.net.OduSignalId.OduSignalId().
String org.onosproject.net.OduSignalId.toString ()
Definition at line 129 of file OduSignalId.java.
References org.onosproject.net.OduSignalId.tributaryPortNumber(), org.onosproject.net.OduSignalId.tributarySlotBitmap(), and org.onosproject.net.OduSignalId.tributarySlotLength().
int org.onosproject.net.OduSignalId.tributaryPortNumber ()
Returns tributary port number.
Returns
the tributaryPortNumber
Definition at line 87 of file OduSignalId.java.
Referenced by org.onosproject.net.OduSignalId.hashCode(), org.onosproject.net.OduSignalId.OduSignalId(), and org.onosproject.net.OduSignalId.toString().
byte [] org.onosproject.net.OduSignalId.tributarySlotBitmap ()
Returns tributary slot bitmap.
Returns
the tributarySlotBitmap
Definition at line 105 of file OduSignalId.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.net.OduSignalId.equals(), org.onosproject.net.OduSignalId.hashCode(), org.onosproject.net.OduSignalId.OduSignalId(), and org.onosproject.net.OduSignalId.toString().
int org.onosproject.net.OduSignalId.tributarySlotLength ()
Returns tributary slot length.
Returns
the tributarySlotLen
Definition at line 96 of file OduSignalId.java.
Referenced by org.onosproject.net.OduSignalId.hashCode(), and org.onosproject.net.OduSignalId.toString().
Member Data Documentation
final int org.onosproject.net.OduSignalId.TRIBUTARY_SLOT_BITMAP_SIZE = 10 static
Definition at line 39 of file OduSignalId.java.
Referenced by org.onosproject.net.OduSignalId.OduSignalId().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/OduSignalId.java