onos: org.onlab.packet.Ip4Address Class Reference
org.onlab.packet.Ip4Address Class Reference
A class representing an IPv4 address.
Public Member Functions
int toInt ()
Returns the integer value of this IPv4 address.
Public Member Functions inherited from org.onlab.packet.IpAddress
Version version ()
Returns the IP version of this address.
boolean isIp4 ()
Tests whether the IP version of this address is IPv4.
boolean isIp6 ()
Tests whether the IP version of this address is IPv6.
Ip4Address getIp4Address ()
Gets the Ip4Address view of the IP address.
Ip6Address getIp6Address ()
Gets the Ip6Address view of the IP address.
byte[] toOctets ()
Returns the IP address as a byte array.
boolean isZero ()
Check if this IP address is zero.
boolean isSelfAssigned ()
Check if this IP address is self-assigned.
int compareTo (IpAddress o)
int hashCode ()
boolean equals (Object obj)
String toString ()
IpPrefix toIpPrefix ()
Generates an IP prefix.
Static Public Member Functions
static Ip4Address valueOf (int value)
Converts an integer into an IPv4 address.
static Ip4Address valueOf (byte[] value)
Converts a byte array into an IPv4 address.
static Ip4Address valueOf (byte[] value, int offset)
Converts a byte array and a given offset from the beginning of the array into an IPv4 address.
static Ip4Address valueOf (InetAddress inetAddress)
Converts an InetAddress into an IPv4 address.
static Ip4Address valueOf (String value)
Converts an IPv4 string literal (e.g., "10.2.3.4") into an IP address.
static Ip4Address makeMaskPrefix (int prefixLength)
Creates an IPv4 network mask prefix.
static Ip4Address makeMaskedAddress (final Ip4Address address, int prefixLength)
Creates an IPv4 address by masking it with a network mask of given mask length.
Static Public Member Functions inherited from org.onlab.packet.IpAddress
static int byteLength (Version version)
Computes the IP address byte length for a given IP version.
static IpAddress valueOf (int value)
Converts an integer into an IPv4 address.
static IpAddress valueOf (Version version, byte[] value)
Converts a byte array into an IP address.
static IpAddress valueOf (Version version, byte[] value, int offset)
Converts a byte array and a given offset from the beginning of the array into an IP address.
static IpAddress valueOf (InetAddress inetAddress)
Converts an InetAddress into an IP address.
static IpAddress valueOf (String value)
Converts an IPv4 or IPv6 string literal (e.g., "10.2.3.4" or "1111:2222::8888") into an IP address.
static IpAddress makeMaskPrefix (Version version, int prefixLength)
Creates an IP network mask prefix.
static IpAddress makeMaskedAddress (final IpAddress address, int prefixLength)
Creates an IP address by masking it with a network mask of given mask length.
Static Public Attributes
static final IpAddress.Version VERSION = IpAddress.Version.INET
static final int BYTE_LENGTH = IpAddress.INET_BYTE_LENGTH
static final int BIT_LENGTH = IpAddress.INET_BIT_LENGTH
Static Public Attributes inherited from org.onlab.packet.IpAddress
static final int INET_BYTE_LENGTH = 4
static final int INET_BIT_LENGTH = INET_BYTE_LENGTH * Byte.SIZE
static final int INET6_BYTE_LENGTH = 16
static final int INET6_BIT_LENGTH = INET6_BYTE_LENGTH * Byte.SIZE
Additional Inherited Members
Protected Member Functions inherited from org.onlab.packet.IpAddress
IpAddress (Version version, byte[] value)
Constructor for given IP address version and address octets.
Detailed Description
A class representing an IPv4 address.
This class is immutable.
Definition at line 30 of file Ip4Address.java.
Member Function Documentation
static Ip4Address org.onlab.packet.Ip4Address.makeMaskedAddress (final Ip4Address address, int prefixLength) static
Creates an IPv4 address by masking it with a network mask of given mask length.
Parameters
address the address to mask
prefixLength the length of the mask prefix. Must be in the interval [0, 32]
Returns
a new IPv4 address that is masked with a mask prefix of the specified length
Exceptions
IllegalArgumentException if the prefix length is invalid
Definition at line 169 of file Ip4Address.java.
References onos.net.
static Ip4Address org.onlab.packet.Ip4Address.makeMaskPrefix (int prefixLength) static
Creates an IPv4 network mask prefix.
Parameters
prefixLength the length of the mask prefix. Must be in the interval [0, 32]
Returns
a new IPv4 address that contains a mask prefix of the specified length
Exceptions
IllegalArgumentException if the argument is invalid
Definition at line 153 of file Ip4Address.java.
References org.onlab.packet.Ip4Address.VERSION.
int org.onlab.packet.Ip4Address.toInt ()
Returns the integer value of this IPv4 address.
Returns
the IPv4 address's value as an integer
Definition at line 51 of file Ip4Address.java.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.dhcp.impl.DistributedDhcpStore.populateIPPoolfromRange(), org.onosproject.dhcp.impl.DistributedDhcpStore.suggestIP(), and org.onlab.packet.Ip4AddressTest.testToInt().
static Ip4Address org.onlab.packet.Ip4Address.valueOf (int value) static
Converts an integer into an IPv4 address.
Parameters
value an integer representing an IPv4 address value
Returns
an IPv4 address
Definition at line 62 of file Ip4Address.java.
References org.onlab.packet.IpAddress.INET_BYTE_LENGTH.
Referenced by org.onosproject.driver.extensions.NiciraExtensionTreatmentInterpreter.mapAction(), org.onosproject.openstackswitching.OpenstackArpHandler.processPacketIn(), org.onosproject.dhcp.rest.DhcpWebResource.setMapping(), org.onlab.packet.Ip4PrefixTest.testAddressAndPrefixLengthIPv4(), org.onosproject.dhcp.IpAssignmentTest.testConstruction(), org.onlab.packet.Ip4PrefixTest.testContainsIpAddressIPv4(), org.onlab.packet.Ip4AddressTest.testEqualityIPv4(), org.onosproject.sdnip.SdnIpFibTest.testFibAdd(), org.onosproject.sdnip.SdnIpFibTest.testFibAddWithVlan(), org.onosproject.sdnip.SdnIpFibTest.testFibUpdate(), org.onosproject.store.serializers.KryoSerializerTest.testIp4Address(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyExternalPortBadRequest(), org.onosproject.dhcp.IpAssignmentTest.testValidateInputs(), org.onlab.packet.Ip4Prefix.valueOf(), and org.onlab.packet.Ip4Address.valueOf().
static Ip4Address org.onlab.packet.Ip4Address.valueOf (byte[] value) static
Converts a byte array into an IPv4 address.
Parameters
value the IPv4 address value stored in network byte order (i.e., the most significant byte first)
Returns
an IPv4 address
Exceptions
IllegalArgumentException if the argument is invalid
Definition at line 76 of file Ip4Address.java.
static Ip4Address org.onlab.packet.Ip4Address.valueOf (byte[] value, int offset) static
Converts a byte array and a given offset from the beginning of the array into an IPv4 address.
The IP address is stored in network byte order (i.e., the most significant byte first).
Parameters
value the value to use
offset the offset in bytes from the beginning of the byte array
Returns
an IPv4 address
Exceptions
IllegalArgumentException if the arguments are invalid
Definition at line 92 of file Ip4Address.java.
References find-link-in-cluster.length, and org.onlab.packet.Ip4Address.VERSION.
static Ip4Address org.onlab.packet.Ip4Address.valueOf (InetAddress inetAddress) static
Converts an InetAddress into an IPv4 address.
Parameters
inetAddress the InetAddress value to use. It must contain an IPv4 address
Returns
an IPv4 address
Exceptions
IllegalArgumentException if the argument is invalid
Definition at line 106 of file Ip4Address.java.
References org.onlab.packet.IpAddress.INET6_BYTE_LENGTH, and org.onlab.packet.IpAddress.INET_BYTE_LENGTH.
static Ip4Address org.onlab.packet.Ip4Address.valueOf (String value) static
Converts an IPv4 string literal (e.g., "10.2.3.4") into an IP address.
Parameters
value an IPv4 address value in string form
Returns
an IPv4 address
Exceptions
IllegalArgumentException if the argument is invalid
Definition at line 133 of file Ip4Address.java.
References org.onlab.packet.Ip4Address.valueOf().
Member Data Documentation
final int org.onlab.packet.Ip4Address.BIT_LENGTH = IpAddress.INET_BIT_LENGTH static
Definition at line 33 of file Ip4Address.java.
Referenced by org.onosproject.routing.impl.Router.getLongestMatchableRouteEntry(), org.onosproject.routing.config.impl.RoutingConfigurationImpl.isIpAddressLocal(), org.onlab.packet.Ip4AddressTest.testAddrBitLength(), and org.onlab.packet.IpAddress.toIpPrefix().
final int org.onlab.packet.Ip4Address.BYTE_LENGTH = IpAddress.INET_BYTE_LENGTH static
Definition at line 32 of file Ip4Address.java.
Referenced by org.onlab.packet.ARP.buildArpReply(), org.onosproject.segmentrouting.ArpHandler.sendArpRequest(), and org.onlab.packet.Ip4AddressTest.testAddrByteLength().
final IpAddress.Version org.onlab.packet.Ip4Address.VERSION = IpAddress.Version.INET static
Definition at line 31 of file Ip4Address.java.
Referenced by org.onlab.packet.IpAddress.isIp4(), org.onlab.packet.Ip4Address.makeMaskPrefix(), org.onlab.packet.Ip4AddressTest.testAddressVersion(), and org.onlab.packet.Ip4Address.valueOf().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/Ip4Address.java