onos: org.onosproject.driver.pipeline.DefaultSingleTablePipeline Class Reference
org.onosproject.driver.pipeline.DefaultSingleTablePipeline Class Reference
Simple single table pipeline abstraction.
Public Member Functions
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filter)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Detailed Description
Simple single table pipeline abstraction.
Definition at line 43 of file DefaultSingleTablePipeline.java.
Member Function Documentation
void org.onosproject.driver.pipeline.DefaultSingleTablePipeline.filter (FilteringObjective filterObjective)
Installs the filtering rules onto the device.
Parameters
filterObjective a filtering objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 60 of file DefaultSingleTablePipeline.java.
void org.onosproject.driver.pipeline.DefaultSingleTablePipeline.forward (ForwardingObjective forwardObjective)
Installs the forwarding rules onto the device.
Parameters
forwardObjective a forwarding objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 63 of file DefaultSingleTablePipeline.java.
References org.onosproject.net.flowobjective.Objective.context(), org.onosproject.net.flowobjective.ForwardingObjective.flag(), org.onosproject.net.flowobjective.ObjectiveError.FLOWINSTALLATIONFAILED, org.onosproject.net.flowobjective.Objective.op(), org.onosproject.net.flowobjective.Objective.permanent(), onos.size, and org.onosproject.net.flowobjective.ForwardingObjective.treatment().
void org.onosproject.driver.pipeline.DefaultSingleTablePipeline.init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
Parameters
deviceId the deviceId
context processing context
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 52 of file DefaultSingleTablePipeline.java.
void org.onosproject.driver.pipeline.DefaultSingleTablePipeline.next (NextObjective nextObjective)
Installs the next hop elements into the device.
Parameters
nextObjective a next objectives
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 127 of file DefaultSingleTablePipeline.java.
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/pipeline/DefaultSingleTablePipeline.java