onos: org.onosproject.mfwd.impl.McastRouteBase Class Reference
org.onosproject.mfwd.impl.McastRouteBase Class Reference
McastRouteBase base class for McastRouteGroup and McastRouteSource.
Public Member Functions
McastRouteBase (String saddr, String gaddr)
Create a multicast route.
McastRouteBase (String gaddr)
Create a multicast group table entry.
McastRouteBase (IpPrefix gpfx)
Set the source and group address value of a (*, G) group.
McastRouteBase (IpPrefix saddr, IpPrefix gaddr)
Create a multicast route constructor.
IpPrefix getGaddr ()
Get the multicast group address.
IpPrefix getSaddr ()
Get the multicast source address.
boolean isIp4 ()
Is this an IPv4 multicast route.
boolean isIp6 ()
Is this an IPv6 multicast route.
boolean isGroup ()
Is this a multicast group route?
boolean isSource ()
boolean getDirty ()
Get the dirty state.
void setDirty (boolean dirty)
Set the dirty state to indicate that something changed.
boolean addIngressPoint (ConnectPoint ingress)
Add an ingress point to this route.
boolean addIngressPoint (String connectPoint)
Add or modify the ingress connect point.
McastConnectPoint getIngressPoint ()
Get the ingress McastConnectPoint.
McastConnectPoint addEgressPoint (ConnectPoint cp)
Add an egress McastConnectPoint.
McastConnectPoint addEgressPoint (String connectPoint)
Add an egress connect point from a string.
McastConnectPoint addEgressPoint (ConnectPoint cp, McastConnectPoint.JoinSource interest)
Add an egress McastConnectPoint.
boolean removeEgressPoint (String connectPoint)
Remove an egress from McastConnectPoint.
boolean removeEgressPoint (ConnectPoint cp)
Remove an egress from McastConnectPoint.
McastConnectPoint addEgressPoint (String cpstr, McastConnectPoint.JoinSource interest)
Add an egress McastConnectPoint.
Set< McastConnectPoint > getEgressPoints ()
Get egress connect points for the route.
Set< ConnectPoint > getEgressConnectPoints ()
Get egress McastConnectPoints points as ConnectPoints for intent system.
McastConnectPoint findEgressConnectPoint (ConnectPoint cp)
Find the Multicast Connect Point that contains the ConnectPoint.
boolean removeInterest (McastConnectPoint mcp, McastConnectPoint.JoinSource interest)
Remove specified interest from the given ConnectPoint.
int getPuntCount ()
Get the number of times the packet has been punted.
void incrementPuntCount ()
Increment the punt count.
void setIntent ()
Have the McastIntentManager create and set the intent, then save the intent key.
void setIntent (SinglePointToMultiPointIntent intent)
Set the Intent key.
Key getIntentKey ()
Get the intent key represented by this route.
void withdrawIntent ()
Withdraw the intent and set the key to null.
String toString ()
Pretty Print this Multicast Route.
Public Member Functions inherited from org.onosproject.mfwd.impl.McastRoute
IpPrefix getGaddr ()
Gets the group addresses.
IpPrefix getSaddr ()
Gets the source address.
boolean isIp4 ()
Determines if this is an IPv4 multicast route.
boolean isIp6 ()
Determines if this is an IPv6 multicast route.
boolean getDirty ()
Get the dirty state.
void setDirty (boolean dirty)
Set the dirty state to indicate that something changed.
boolean addIngressPoint (String cpstr)
Add the ingress ConnectPoint.
boolean addIngressPoint (ConnectPoint cp)
Add the ingress ConnectPoint.
McastConnectPoint getIngressPoint ()
Get the ingress connect point.
McastConnectPoint addEgressPoint (ConnectPoint cp)
Add an egress connect point.
McastConnectPoint addEgressPoint (String connectPoint)
Add an egress connect point.
McastConnectPoint addEgressPoint (ConnectPoint cp, McastConnectPoint.JoinSource interest)
Add an egress connect point.
McastConnectPoint addEgressPoint (String connectPoint, McastConnectPoint.JoinSource interest)
Add an egress connect point.
Set< McastConnectPoint > getEgressPoints ()
Get the egress connect points.
Set< ConnectPoint > getEgressConnectPoints ()
Get the egress connect points.
McastConnectPoint findEgressConnectPoint (ConnectPoint cp)
Find the egress connect point if it exists.
boolean removeInterest (McastConnectPoint mcp, McastConnectPoint.JoinSource interest)
remove Interest from a McastConnectPoint.
void incrementPuntCount ()
Increment the punt count.
int getPuntCount ()
Get the punt count.
void setIntent ()
Have the McastIntentManager create an intent, attempt to install the intent and then save the key.
void setIntent (SinglePointToMultiPointIntent intent)
Set the Intent key.
void withdrawIntent ()
Withdraw the intent if it has been installed.
Key getIntentKey ()
Get the intent key.
String toString ()
Pretty print the the route.
Protected Attributes
final IpPrefix gaddr
final IpPrefix saddr
McastConnectPoint ingressPoint
Set< McastConnectPoint > egressPoints
boolean isGroup = false
boolean dirty = false
Key intentKey = null
If the intentKey is null that means no intent has been installed.
Detailed Description
McastRouteBase base class for McastRouteGroup and McastRouteSource.
Definition at line 31 of file McastRouteBase.java.
Constructor & Destructor Documentation
org.onosproject.mfwd.impl.McastRouteBase.McastRouteBase (String saddr, String gaddr)
Create a multicast route.
This is the parent class for both the Group and the source.
Parameters
saddr source address
gaddr multicast group address
Definition at line 60 of file McastRouteBase.java.
org.onosproject.mfwd.impl.McastRouteBase.McastRouteBase (String gaddr)
Create a multicast group table entry.
Parameters
gaddr multicast group address
Definition at line 74 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.gaddr.
org.onosproject.mfwd.impl.McastRouteBase.McastRouteBase (IpPrefix gpfx)
Set the source and group address value of a (*, G) group.
Parameters
gpfx the group prefix address
Definition at line 83 of file McastRouteBase.java.
org.onosproject.mfwd.impl.McastRouteBase.McastRouteBase (IpPrefix saddr, IpPrefix gaddr)
Create a multicast route constructor.
Parameters
saddr source address
gaddr group address
Definition at line 93 of file McastRouteBase.java.
Member Function Documentation
McastConnectPoint org.onosproject.mfwd.impl.McastRouteBase.addEgressPoint (ConnectPoint cp)
Add an egress McastConnectPoint.
Parameters
cp egress connect point
Returns
return the McastConnectPoint
Definition at line 230 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.setDirty().
McastConnectPoint org.onosproject.mfwd.impl.McastRouteBase.addEgressPoint (String connectPoint)
Add an egress connect point from a string.
Parameters
connectPoint string representing a connect point
Returns
the MulticastConnectPoint
Definition at line 246 of file McastRouteBase.java.
McastConnectPoint org.onosproject.mfwd.impl.McastRouteBase.addEgressPoint (ConnectPoint cp, McastConnectPoint.JoinSource interest)
Add an egress McastConnectPoint.
Parameters
cp the egress connect point
interest the source of interest for mcast traffic
Definition at line 257 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.setDirty().
McastConnectPoint org.onosproject.mfwd.impl.McastRouteBase.addEgressPoint (String cpstr, McastConnectPoint.JoinSource interest)
Add an egress McastConnectPoint.
Parameters
cpstr deviceId/port of the connect point
Definition at line 300 of file McastRouteBase.java.
boolean org.onosproject.mfwd.impl.McastRouteBase.addIngressPoint (ConnectPoint ingress)
Add an ingress point to this route.
Parameters
ingress incoming connect point
Returns
whether ingress has been added, only add if ingressPoint is null
Definition at line 187 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.ingressPoint, and org.onosproject.mfwd.impl.McastRouteBase.setDirty().
boolean org.onosproject.mfwd.impl.McastRouteBase.addIngressPoint (String connectPoint)
Add or modify the ingress connect point.
Parameters
connectPoint string switch device Id
Returns
whether ingress has been added, only add if ingressPoint is null
Definition at line 205 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.ingressPoint.
McastConnectPoint org.onosproject.mfwd.impl.McastRouteBase.findEgressConnectPoint (ConnectPoint cp)
Find the Multicast Connect Point that contains the ConnectPoint.
Parameters
cp the regular ConnectPoint to match
Returns
the McastConnectPoint that contains cp or null if not found.
Definition at line 335 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.egressPoints.
boolean org.onosproject.mfwd.impl.McastRouteBase.getDirty ()
Get the dirty state.
Returns
whether this route is dirty or not.
Definition at line 167 of file McastRouteBase.java.
Set<ConnectPoint> org.onosproject.mfwd.impl.McastRouteBase.getEgressConnectPoints ()
Get egress McastConnectPoints points as ConnectPoints for intent system.
Returns
Set of egress ConnectPoints
Definition at line 320 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.egressPoints.
Set<McastConnectPoint> org.onosproject.mfwd.impl.McastRouteBase.getEgressPoints ()
Get egress connect points for the route.
Returns
Set of egress connect points
Definition at line 311 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.egressPoints.
Referenced by org.onosproject.mfwd.impl.McastRouteTable.removeRoute().
IpPrefix org.onosproject.mfwd.impl.McastRouteBase.getGaddr ()
Get the multicast group address.
Returns
the multicast group address
Definition at line 112 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.gaddr.
McastConnectPoint org.onosproject.mfwd.impl.McastRouteBase.getIngressPoint ()
Get the ingress McastConnectPoint.
Returns
the ingress McastConnectPoint
Definition at line 220 of file McastRouteBase.java.
Key org.onosproject.mfwd.impl.McastRouteBase.getIntentKey ()
Get the intent key represented by this route.
Returns
intentKey
Definition at line 414 of file McastRouteBase.java.
int org.onosproject.mfwd.impl.McastRouteBase.getPuntCount ()
Get the number of times the packet has been punted.
Returns
the punt count
Definition at line 367 of file McastRouteBase.java.
IpPrefix org.onosproject.mfwd.impl.McastRouteBase.getSaddr ()
Get the multicast source address.
Returns
the multicast source address
Definition at line 122 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.saddr.
void org.onosproject.mfwd.impl.McastRouteBase.incrementPuntCount ()
Increment the punt count.
TODO: we need to handle wrapping.
Definition at line 377 of file McastRouteBase.java.
boolean org.onosproject.mfwd.impl.McastRouteBase.isGroup ()
Is this a multicast group route?
Returns
true if it is a multicast group route.
Definition at line 151 of file McastRouteBase.java.
Referenced by org.onosproject.mfwd.impl.McastRouteBase.isSource().
boolean org.onosproject.mfwd.impl.McastRouteBase.isIp4 ()
Is this an IPv4 multicast route.
Returns
true if it is an IPv4 route
Definition at line 132 of file McastRouteBase.java.
boolean org.onosproject.mfwd.impl.McastRouteBase.isIp6 ()
Is this an IPv6 multicast route.
Returns
true if it is an IPv6 route
Definition at line 142 of file McastRouteBase.java.
boolean org.onosproject.mfwd.impl.McastRouteBase.isSource ()
Returns
true if this is (S, G) false if it (*, G).
Definition at line 158 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.isGroup().
boolean org.onosproject.mfwd.impl.McastRouteBase.removeEgressPoint (String connectPoint)
Remove an egress from McastConnectPoint.
Parameters
connectPoint the egress connect point
Returns
boolean result of removal
Definition at line 274 of file McastRouteBase.java.
boolean org.onosproject.mfwd.impl.McastRouteBase.removeEgressPoint (ConnectPoint cp)
Remove an egress from McastConnectPoint.
Parameters
cp the egress connect point
Returns
boolean result of removal
Definition at line 285 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.setDirty().
boolean org.onosproject.mfwd.impl.McastRouteBase.removeInterest (McastConnectPoint mcp, McastConnectPoint.JoinSource interest)
Remove specified interest from the given ConnectPoint.
Parameters
mcp connect point.
interest the protocol interested in this multicast stream
Returns
true if removed, false otherwise
Definition at line 351 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastConnectPoint.interest, and org.onosproject.mfwd.impl.McastRouteBase.setDirty().
void org.onosproject.mfwd.impl.McastRouteBase.setDirty (boolean dirty)
Set the dirty state to indicate that something changed.
This may require an update to the flow tables (intents).
Parameters
dirty set the dirty bit
Definition at line 177 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.dirty.
Referenced by org.onosproject.mfwd.impl.McastRouteBase.addEgressPoint(), org.onosproject.mfwd.impl.McastRouteBase.addIngressPoint(), org.onosproject.mfwd.impl.McastRouteBase.removeEgressPoint(), and org.onosproject.mfwd.impl.McastRouteBase.removeInterest().
void org.onosproject.mfwd.impl.McastRouteBase.setIntent ()
Have the McastIntentManager create and set the intent, then save the intent key.
If we already have an intent, we will first withdraw the existing intent and replace it with a new one. This will support the case where the ingress connectPoint or group of egress connectPoints change.
Definition at line 389 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.intentKey.
void org.onosproject.mfwd.impl.McastRouteBase.setIntent (SinglePointToMultiPointIntent intent)
Set the Intent key.
Parameters
intent the multicast intent
Definition at line 404 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.intentKey.
String org.onosproject.mfwd.impl.McastRouteBase.toString ()
Pretty Print this Multicast Route.
Works for McastRouteSource and McastRouteGroup.
Returns
pretty string of the multicast route
Definition at line 439 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.egressPoints, org.onosproject.mfwd.impl.McastRouteBase.gaddr, org.onosproject.mfwd.impl.McastConnectPoint.getConnectPoint(), org.onosproject.mfwd.impl.McastRouteBase.ingressPoint, org.onosproject.mfwd.impl.McastRouteBase.intentKey, and org.onlab.packet.IpPrefix.toString().
void org.onosproject.mfwd.impl.McastRouteBase.withdrawIntent ()
Withdraw the intent and set the key to null.
Definition at line 423 of file McastRouteBase.java.
References org.onosproject.mfwd.impl.McastRouteBase.intentKey.
Member Data Documentation
boolean org.onosproject.mfwd.impl.McastRouteBase.dirty = false protected
Definition at line 40 of file McastRouteBase.java.
Referenced by org.onosproject.mfwd.impl.McastRouteBase.setDirty().
Set<McastConnectPoint> org.onosproject.mfwd.impl.McastRouteBase.egressPoints protected
Definition at line 36 of file McastRouteBase.java.
Referenced by org.onosproject.mfwd.impl.McastRouteBase.findEgressConnectPoint(), org.onosproject.mfwd.impl.McastRouteBase.getEgressConnectPoints(), org.onosproject.mfwd.impl.McastRouteBase.getEgressPoints(), and org.onosproject.mfwd.impl.McastRouteBase.toString().
final IpPrefix org.onosproject.mfwd.impl.McastRouteBase.gaddr protected
Definition at line 32 of file McastRouteBase.java.
Referenced by org.onosproject.mfwd.impl.McastRouteBase.getGaddr(), org.onosproject.mfwd.impl.McastRouteBase.McastRouteBase(), and org.onosproject.mfwd.impl.McastRouteBase.toString().
McastConnectPoint org.onosproject.mfwd.impl.McastRouteBase.ingressPoint protected
Definition at line 35 of file McastRouteBase.java.
Referenced by org.onosproject.mfwd.impl.McastRouteBase.addIngressPoint(), and org.onosproject.mfwd.impl.McastRouteBase.toString().
Key org.onosproject.mfwd.impl.McastRouteBase.intentKey = null protected
If the intentKey is null that means no intent has been installed.
Definition at line 51 of file McastRouteBase.java.
Referenced by org.onosproject.mfwd.impl.McastRouteBase.setIntent(), org.onosproject.mfwd.impl.McastRouteBase.toString(), and org.onosproject.mfwd.impl.McastRouteBase.withdrawIntent().
boolean org.onosproject.mfwd.impl.McastRouteBase.isGroup = false protected
Definition at line 38 of file McastRouteBase.java.
final IpPrefix org.onosproject.mfwd.impl.McastRouteBase.saddr protected
Definition at line 33 of file McastRouteBase.java.
Referenced by org.onosproject.mfwd.impl.McastRouteBase.getSaddr().
The documentation for this class was generated from the following file:
apps/mfwd/src/main/java/org/onosproject/mfwd/impl/McastRouteBase.java