onos: org.onosproject.routing.bgp.BgpRouteEntry Class Reference
org.onosproject.routing.bgp.BgpRouteEntry Class Reference
Represents a route in BGP.
Classes
class AsPath
A class to represent AS Path.
class PathSegment
A class to represent AS Path Segment.
Public Member Functions
BgpRouteEntry (BgpSession bgpSession, IpPrefix prefix, IpAddress nextHop, byte origin, BgpRouteEntry.AsPath asPath, long localPref)
Class constructor.
BgpSession getBgpSession ()
Gets the BGP Session the route was received on.
byte getOrigin ()
Gets the route origin: 0=IGP, 1=EGP, 2=INCOMPLETE.
BgpRouteEntry.AsPath getAsPath ()
Gets the route AS path.
long getLocalPref ()
Gets the route local preference.
long getMultiExitDisc ()
Gets the route MED (Multi-Exit Discriminator).
boolean equals (Object other)
Compares whether two objects are equal.
int hashCode ()
Computes the hash code.
String toString ()
Public Member Functions inherited from org.onosproject.routing.RouteEntry
RouteEntry (IpPrefix prefix, IpAddress nextHop)
Class constructor.
IpAddress.Version version ()
Returns the IP version of the route.
boolean isIp4 ()
Tests whether the IP version of this address is IPv4.
boolean isIp6 ()
Tests whether the IP version of this address is IPv6.
IpPrefix prefix ()
Returns the IP prefix of the route.
IpAddress nextHop ()
Returns the next hop IP address for the route.
boolean equals (Object other)
int hashCode ()
String toString ()
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.routing.RouteEntry
static String createBinaryString (IpPrefix ipPrefix)
Creates the binary string representation of an IP prefix.
Detailed Description
Represents a route in BGP.
Definition at line 32 of file BgpRouteEntry.java.
Constructor & Destructor Documentation
org.onosproject.routing.bgp.BgpRouteEntry.BgpRouteEntry (BgpSession bgpSession, IpPrefix prefix, IpAddress nextHop, byte origin, BgpRouteEntry.AsPath asPath, long localPref)
Class constructor.
Parameters
bgpSession the BGP Session the route was received on
prefix the prefix of the route
nextHop the next hop of the route
origin the route origin: 0=IGP, 1=EGP, 2=INCOMPLETE
asPath the AS path
localPref the route local preference
Definition at line 50 of file BgpRouteEntry.java.
Referenced by org.onosproject.routing.bgp.BgpRouteEntry.equals().
Member Function Documentation
boolean org.onosproject.routing.bgp.BgpRouteEntry.equals (Object other)
Compares whether two objects are equal.
NOTE: The bgpSession field is excluded from the comparison.
Returns
true if the two objects are equal, otherwise false.
Definition at line 444 of file BgpRouteEntry.java.
References org.onosproject.routing.bgp.BgpRouteEntry.BgpRouteEntry().
BgpRouteEntry.AsPath org.onosproject.routing.bgp.BgpRouteEntry.getAsPath ()
Gets the route AS path.
Returns
the route AS path
Definition at line 83 of file BgpRouteEntry.java.
Referenced by org.onosproject.routing.bgp.BgpRouteEntryTest.testGetFields().
BgpSession org.onosproject.routing.bgp.BgpRouteEntry.getBgpSession ()
Gets the BGP Session the route was received on.
Returns
the BGP Session the route was received on
Definition at line 65 of file BgpRouteEntry.java.
Referenced by org.onosproject.routing.bgp.BgpRouteEntryTest.testGetFields().
long org.onosproject.routing.bgp.BgpRouteEntry.getLocalPref ()
Gets the route local preference.
Returns
the route local preference
Definition at line 92 of file BgpRouteEntry.java.
Referenced by org.onosproject.routing.bgp.BgpRouteEntryTest.testGetFields().
long org.onosproject.routing.bgp.BgpRouteEntry.getMultiExitDisc ()
Gets the route MED (Multi-Exit Discriminator).
Returns
the route MED (Multi-Exit Discriminator)
Definition at line 101 of file BgpRouteEntry.java.
Referenced by org.onosproject.routing.bgp.BgpRouteEntryTest.testGetFields().
byte org.onosproject.routing.bgp.BgpRouteEntry.getOrigin ()
Gets the route origin: 0=IGP, 1=EGP, 2=INCOMPLETE.
Returns
the route origin: 0=IGP, 1=EGP, 2=INCOMPLETE
Definition at line 74 of file BgpRouteEntry.java.
Referenced by org.onosproject.routing.bgp.BgpRouteEntryTest.testGetFields().
int org.onosproject.routing.bgp.BgpRouteEntry.hashCode ()
Computes the hash code.
NOTE: We return the base class hash code to avoid expensive computation
Returns
the object hash code
Definition at line 478 of file BgpRouteEntry.java.
String org.onosproject.routing.bgp.BgpRouteEntry.toString ()
Definition at line 483 of file BgpRouteEntry.java.
References org.onosproject.routing.RouteEntry.nextHop(), and org.onosproject.routing.RouteEntry.prefix().
Referenced by org.onosproject.routing.bgp.BgpRouteEntryTest.testConstructor(), and org.onosproject.routing.bgp.BgpRouteEntryTest.testToString().
The documentation for this class was generated from the following file:
apps/routing/src/main/java/org/onosproject/routing/bgp/BgpRouteEntry.java