onos: org.onosproject.store.trivial.SimpleDeviceStore Class Reference
org.onosproject.store.trivial.SimpleDeviceStore Class Reference
Manages inventory of infrastructure devices using trivial in-memory structures implementation.
Public Member Functions
void activate ()
void deactivate ()
int getDeviceCount ()
Returns the number of devices known to the system.
Iterable< Device > getDevices ()
Returns an iterable collection of all devices known to the system.
Iterable< Device > getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Device getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
DeviceEvent createOrUpdateDevice (ProviderId providerId, DeviceId deviceId, DeviceDescription deviceDescription)
Creates a new infrastructure device, or updates an existing one using the supplied device description.
DeviceEvent markOffline (DeviceId deviceId)
Removes the specified infrastructure device.
List< DeviceEvent > updatePorts (ProviderId providerId, DeviceId deviceId, List< PortDescription > portDescriptions)
Updates the ports of the specified infrastructure device using the given list of port descriptions.
DeviceEvent updatePortStatus (ProviderId providerId, DeviceId deviceId, PortDescription portDescription)
Updates the port status of the specified infrastructure device using the given port description.
List< Port > getPorts (DeviceId deviceId)
Returns the list of ports that belong to the specified device.
DeviceEvent updatePortStatistics (ProviderId providerId, DeviceId deviceId, Collection< PortStatistics > newStatsCollection)
Updates the port statistics of the specified device using the give port statistics.
PortStatistics calcDeltaStats (DeviceId deviceId, PortStatistics prvStats, PortStatistics newStats)
Port getPort (DeviceId deviceId, PortNumber portNumber)
Returns the specified device port.
List< PortStatistics > getPortStatistics (DeviceId deviceId)
Returns the list of port statistics of the specified device.
List< PortStatistics > getPortDeltaStatistics (DeviceId deviceId)
Returns the list of delta port statistics of the specified device.
boolean isAvailable (DeviceId deviceId)
Indicates whether the specified device is available/online.
DeviceEvent removeDevice (DeviceId deviceId)
Administratively removes the specified device from the store.
Static Public Attributes
static final String DEVICE_NOT_FOUND = "Device with ID %s not found"
Detailed Description
Manages inventory of infrastructure devices using trivial in-memory structures implementation.
Definition at line 84 of file SimpleDeviceStore.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleDeviceStore.activate ()
Definition at line 110 of file SimpleDeviceStore.java.
PortStatistics org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats (DeviceId deviceId, PortStatistics prvStats, PortStatistics newStats)
Definition at line 450 of file SimpleDeviceStore.java.
References org.onosproject.net.device.PortStatistics.bytesReceived(), org.onosproject.net.device.PortStatistics.bytesSent(), find-flow.deviceId, org.onosproject.net.device.PortStatistics.durationNano(), org.onosproject.net.device.PortStatistics.durationSec(), org.onosproject.net.device.PortStatistics.packetsReceived(), org.onosproject.net.device.PortStatistics.packetsRxDropped(), org.onosproject.net.device.PortStatistics.packetsRxErrors(), org.onosproject.net.device.PortStatistics.packetsSent(), org.onosproject.net.device.PortStatistics.packetsTxDropped(), org.onosproject.net.device.PortStatistics.packetsTxErrors(), and org.onosproject.net.device.PortStatistics.port().
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.updatePortStatistics().
DeviceEvent org.onosproject.store.trivial.SimpleDeviceStore.createOrUpdateDevice (ProviderId providerId, DeviceId deviceId, DeviceDescription deviceDescription)
Creates a new infrastructure device, or updates an existing one using the supplied device description.
Parameters
providerId provider identifier
deviceId device identifier
deviceDescription device description
Returns
ready to send event describing what occurred; null if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 145 of file SimpleDeviceStore.java.
References find-flow.deviceId.
void org.onosproject.store.trivial.SimpleDeviceStore.deactivate ()
Definition at line 115 of file SimpleDeviceStore.java.
Iterable<Device> org.onosproject.store.trivial.SimpleDeviceStore.getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Returns
device collection
Implements org.onosproject.net.device.DeviceStore.
Definition at line 134 of file SimpleDeviceStore.java.
References org.onosproject.store.trivial.SimpleDeviceStore.getDevices(), and org.onosproject.store.trivial.SimpleDeviceStore.isAvailable().
Device org.onosproject.store.trivial.SimpleDeviceStore.getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
Parameters
deviceId device identifier
Returns
device
Implements org.onosproject.net.device.DeviceStore.
Definition at line 140 of file SimpleDeviceStore.java.
References find-flow.deviceId.
int org.onosproject.store.trivial.SimpleDeviceStore.getDeviceCount ()
Returns the number of devices known to the system.
Returns
number of devices
Implements org.onosproject.net.device.DeviceStore.
Definition at line 124 of file SimpleDeviceStore.java.
Iterable<Device> org.onosproject.store.trivial.SimpleDeviceStore.getDevices ()
Returns an iterable collection of all devices known to the system.
Returns
device collection
Implements org.onosproject.net.device.DeviceStore.
Definition at line 129 of file SimpleDeviceStore.java.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.getAvailableDevices().
Port org.onosproject.store.trivial.SimpleDeviceStore.getPort (DeviceId deviceId, PortNumber portNumber)
Returns the specified device port.
Parameters
deviceId device identifier
portNumber port number
Returns
device port
Implements org.onosproject.net.device.DeviceStore.
Definition at line 478 of file SimpleDeviceStore.java.
References find-flow.deviceId.
List<PortStatistics> org.onosproject.store.trivial.SimpleDeviceStore.getPortDeltaStatistics (DeviceId deviceId)
Returns the list of delta port statistics of the specified device.
Parameters
deviceId device identifier
Returns
list of delta port statistics of all ports of the device
Implements org.onosproject.net.device.DeviceStore.
Definition at line 493 of file SimpleDeviceStore.java.
References find-flow.deviceId.
List<Port> org.onosproject.store.trivial.SimpleDeviceStore.getPorts (DeviceId deviceId)
Returns the list of ports that belong to the specified device.
Parameters
deviceId device identifier
Returns
list of device ports
Implements org.onosproject.net.device.DeviceStore.
Definition at line 411 of file SimpleDeviceStore.java.
References find-flow.deviceId.
List<PortStatistics> org.onosproject.store.trivial.SimpleDeviceStore.getPortStatistics (DeviceId deviceId)
Returns the list of port statistics of the specified device.
Parameters
deviceId device identifier
Returns
list of port statistics of all ports of the device
Implements org.onosproject.net.device.DeviceStore.
Definition at line 484 of file SimpleDeviceStore.java.
References find-flow.deviceId.
boolean org.onosproject.store.trivial.SimpleDeviceStore.isAvailable (DeviceId deviceId)
Indicates whether the specified device is available/online.
Parameters
deviceId device identifier
Returns
true if device is available
Implements org.onosproject.net.device.DeviceStore.
Definition at line 502 of file SimpleDeviceStore.java.
References find-flow.deviceId.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.getAvailableDevices().
DeviceEvent org.onosproject.store.trivial.SimpleDeviceStore.markOffline (DeviceId deviceId)
Removes the specified infrastructure device.
Parameters
deviceId device identifier
Returns
ready to send event describing what occurred; null if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 228 of file SimpleDeviceStore.java.
References create-flow.device, and find-flow.deviceId.
DeviceEvent org.onosproject.store.trivial.SimpleDeviceStore.removeDevice (DeviceId deviceId)
Administratively removes the specified device from the store.
Parameters
deviceId device to be removed
Returns
null if no such device, or was forwarded to remove master
Implements org.onosproject.net.device.DeviceStore.
Definition at line 507 of file SimpleDeviceStore.java.
References find-flow.deviceId.
List<DeviceEvent> org.onosproject.store.trivial.SimpleDeviceStore.updatePorts (ProviderId providerId, DeviceId deviceId, List< PortDescription > portDescriptions)
Updates the ports of the specified infrastructure device using the given list of port descriptions.
The list is assumed to be comprehensive.
Parameters
providerId provider identifier
deviceId device identifier
portDescriptions list of port descriptions
Returns
ready to send events describing what occurred; empty list if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 248 of file SimpleDeviceStore.java.
References create-flow.device, org.onosproject.store.trivial.SimpleDeviceStore.DEVICE_NOT_FOUND, and find-flow.deviceId.
DeviceEvent org.onosproject.store.trivial.SimpleDeviceStore.updatePortStatistics (ProviderId providerId, DeviceId deviceId, Collection< PortStatistics > portStats)
Updates the port statistics of the specified device using the give port statistics.
Parameters
providerId provider identifier
deviceId device identifier
portStats list of port statistics
Returns
ready to send event describing what occurred;
Implements org.onosproject.net.device.DeviceStore.
Definition at line 420 of file SimpleDeviceStore.java.
References org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), find-flow.deviceId, and obeliskHostCheck.port.
DeviceEvent org.onosproject.store.trivial.SimpleDeviceStore.updatePortStatus (ProviderId providerId, DeviceId deviceId, PortDescription portDescription)
Updates the port status of the specified infrastructure device using the given port description.
Parameters
providerId provider identifier
deviceId device identifier
portDescription port description
Returns
ready to send event describing what occurred; null if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 378 of file SimpleDeviceStore.java.
References org.onosproject.store.trivial.SimpleDeviceStore.DEVICE_NOT_FOUND, and find-flow.deviceId.
Member Data Documentation
final String org.onosproject.store.trivial.SimpleDeviceStore.DEVICE_NOT_FOUND = "Device with ID %s not found" static
Definition at line 90 of file SimpleDeviceStore.java.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.updatePorts(), and org.onosproject.store.trivial.SimpleDeviceStore.updatePortStatus().
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleDeviceStore.java