onos: org.onosproject.cluster.NodeId Class Reference
org.onosproject.cluster.NodeId Class Reference
Controller cluster identity.
Public Member Functions
NodeId (String id)
Creates a new cluster node identifier from the specified string.
int hashCode ()
boolean equals (Object obj)
String toString ()
int compareTo (NodeId that)
Detailed Description
Controller cluster identity.
Definition at line 23 of file NodeId.java.
Constructor & Destructor Documentation
org.onosproject.cluster.NodeId.NodeId (String id)
Creates a new cluster node identifier from the specified string.
Parameters
id string identifier
Definition at line 32 of file NodeId.java.
Referenced by org.onosproject.cluster.NodeId.equals().
Member Function Documentation
int org.onosproject.cluster.NodeId.compareTo (NodeId that)
Definition at line 59 of file NodeId.java.
References find-device.id.
boolean org.onosproject.cluster.NodeId.equals (Object obj)
Definition at line 42 of file NodeId.java.
References find-device.id, and org.onosproject.cluster.NodeId.NodeId().
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.applyFromDevicePool(), org.onosproject.store.device.impl.ECDeviceStore.createOrUpdateDevice(), org.onosproject.store.device.impl.GossipDeviceStore.createOrUpdateDevice(), org.onosproject.store.link.impl.GossipLinkStore.createOrUpdateLink(), org.onosproject.store.consistent.impl.DistributedLeadershipManager.deactivate(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.destroyDevicePool(), org.onosproject.store.packet.impl.DistributedPacketStore.emit(), org.onosproject.store.proxyarp.impl.DistributedProxyArpStore.forward(), org.onosproject.store.trivial.SimpleMastershipStore.getRole(), org.onosproject.store.device.impl.DeviceClockManager.getTimestamp(), org.onosproject.store.consistent.impl.DistributedLeadershipManager.makeTopCandidate(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.releaseToDevicePool(), org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.relinquishRole(), org.onosproject.store.device.impl.ECDeviceStore.removeDevice(), org.onosproject.store.device.impl.GossipDeviceStore.removeDevice(), org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setMaster(), org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setStandby(), org.onosproject.store.device.impl.ECDeviceStore.updatePorts(), and org.onosproject.store.device.impl.GossipDeviceStore.updatePorts().
int org.onosproject.cluster.NodeId.hashCode ()
Definition at line 37 of file NodeId.java.
String org.onosproject.cluster.NodeId.toString ()
Definition at line 54 of file NodeId.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/cluster/NodeId.java