onos: org.onosproject.pcep.tools.PcepTools Class Reference
org.onosproject.pcep.tools.PcepTools Class Reference
tools fo pcep app.
Static Public Member Functions
static String toHexString (byte[] byteArray)
Converts decimal byte array to a hex string.
static byte[] toByteArray (String hexString)
Converts a hex string to a decimal byte array.
static String toDecimalString (byte[] bytes)
Converts a byte array to a decimal string.
static String stringToIp (String str)
convert a string to the form of ip address.
static String longToIp (long ipLong)
convert a long to ip format.
static long ipToLong (String strIp)
convert a string with ip format to a long.
static int tranferHexStringToInt (String str, int base, int offset)
get a integer value from a cut string.
Detailed Description
tools fo pcep app.
Definition at line 23 of file PcepTools.java.
Member Function Documentation
static long org.onosproject.pcep.tools.PcepTools.ipToLong (String strIp) static
convert a string with ip format to a long.
Parameters
strIp a string with ip format
Returns
a long number
Definition at line 95 of file PcepTools.java.
static String org.onosproject.pcep.tools.PcepTools.longToIp (long ipLong) static
convert a long to ip format.
Parameters
ipLong a decimal number.
Returns
a ip format string
Definition at line 80 of file PcepTools.java.
Referenced by org.onosproject.pcep.tools.PcepTools.stringToIp(), and org.onosproject.pcep.api.PcepDpid.uri().
static String org.onosproject.pcep.tools.PcepTools.stringToIp (String str) static
convert a string to the form of ip address.
Parameters
str a string
Returns
a string with ip format
Definition at line 69 of file PcepTools.java.
References org.onosproject.pcep.tools.PcepTools.longToIp().
static byte [] org.onosproject.pcep.tools.PcepTools.toByteArray (String hexString) static
Converts a hex string to a decimal byte array.
Parameters
hexString a hex string
Returns
byte array
Definition at line 45 of file PcepTools.java.
static String org.onosproject.pcep.tools.PcepTools.toDecimalString (byte[] bytes) static
Converts a byte array to a decimal string.
Parameters
bytes a byte array
Returns
a decimal string
Definition at line 55 of file PcepTools.java.
References find-link-in-cluster.length.
static String org.onosproject.pcep.tools.PcepTools.toHexString (byte[] byteArray) static
Converts decimal byte array to a hex string.
Parameters
byteArray byte array
Returns
a hex string
Definition at line 35 of file PcepTools.java.
static int org.onosproject.pcep.tools.PcepTools.tranferHexStringToInt (String str, int base, int offset) static
get a integer value from a cut string.
Parameters
str a whole string
base cut the string from this index
offset the offset when execute the cut
Returns
a integer value
Definition at line 115 of file PcepTools.java.
The documentation for this class was generated from the following file:
apps/pcep-api/src/main/java/org/onosproject/pcep/tools/PcepTools.java