onos: org.onosproject.pcepio.types.SharedRiskLinkGroupTlv Class Reference
org.onosproject.pcepio.types.SharedRiskLinkGroupTlv Class Reference
Provides SharedRiskLinkGroupTlv.
Public Member Functions
SharedRiskLinkGroupTlv (int[] srlgValue, short hLength)
Constructor to initialize SRLG value.
int[] getValue ()
Returns SRLG Value.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static SharedRiskLinkGroupTlv of (final int[] raw, short hLength)
Returns object of SharedRiskLinkGroupTlv.
static PcepValueType read (ChannelBuffer c, short hLength)
Reads from channel buffer and returns object of SharedRiskLinkGroupTlv.
Static Public Attributes
static final short TYPE = 1096
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(SharedRiskLinkGroupTlv.class)
Detailed Description
Provides SharedRiskLinkGroupTlv.
Definition at line 31 of file SharedRiskLinkGroupTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.SharedRiskLinkGroupTlv (int[] srlgValue, short hLength)
Constructor to initialize SRLG value.
Parameters
srlgValue Shared Risk Link Group Value
hLength length
Definition at line 63 of file SharedRiskLinkGroupTlv.java.
Referenced by org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.equals(), org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.of(), and org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.equals (Object obj)
Definition at line 113 of file SharedRiskLinkGroupTlv.java.
References org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.SharedRiskLinkGroupTlv().
short org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 103 of file SharedRiskLinkGroupTlv.java.
short org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 98 of file SharedRiskLinkGroupTlv.java.
References org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.TYPE.
int [] org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.getValue ()
Returns SRLG Value.
Returns
srlgValue
Definition at line 88 of file SharedRiskLinkGroupTlv.java.
PcepVersion org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 93 of file SharedRiskLinkGroupTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.hashCode ()
Definition at line 108 of file SharedRiskLinkGroupTlv.java.
static SharedRiskLinkGroupTlv org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.of (final int[] raw, short hLength) static
Returns object of SharedRiskLinkGroupTlv.
Parameters
raw value
hLength length
Returns
object of SharedRiskLinkGroupTlv
Definition at line 79 of file SharedRiskLinkGroupTlv.java.
References org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.SharedRiskLinkGroupTlv().
static PcepValueType org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.read (ChannelBuffer c, short hLength) static
Reads from channel buffer and returns object of SharedRiskLinkGroupTlv.
Parameters
c input channel buffer
hLength length
Returns
object of SharedRiskLinkGroupTlv
Definition at line 142 of file SharedRiskLinkGroupTlv.java.
References org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.SharedRiskLinkGroupTlv().
String org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.toString ()
Definition at line 153 of file SharedRiskLinkGroupTlv.java.
References org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.TYPE.
int org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 125 of file SharedRiskLinkGroupTlv.java.
References org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.TYPE.
Member Data Documentation
final Logger org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.log = LoggerFactory.getLogger(SharedRiskLinkGroupTlv.class) static protected
Definition at line 49 of file SharedRiskLinkGroupTlv.java.
final short org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.TYPE = 1096 static
Definition at line 51 of file SharedRiskLinkGroupTlv.java.
Referenced by org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.getType(), org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.toString(), and org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/SharedRiskLinkGroupTlv.java