onos: org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler Class Reference
org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler Class Reference
Default ECMP group handler creation module for a transit device.
Public Member Functions
void createGroups ()
Public Member Functions inherited from org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler
void createGroups ()
Creates the auto created groups for this device based on the current snapshot of the topology.
void linkUp (Link newLink, boolean isMaster)
Performs group creation or update procedures when a new link is discovered on this device.
void portDown (PortNumber port)
Performs group recovery procedures when a port goes down on this device.
int getNextObjectiveId (NeighborSet ns, TrafficSelector meta)
Returns the next objective associated with the neighborset.
int getSubnetNextObjectiveId (IpPrefix prefix)
Returns the next objective associated with the subnet.
boolean hasNextObjectiveId (NeighborSet ns)
Checks if the next objective ID (group) for the neighbor set exists or not.
void createGroupsFromNeighborsets (Set< NeighborSet > nsSet, TrafficSelector meta)
Creates Groups from a set of NeighborSet given.
void createGroupsFromSubnetConfig ()
GroupKey getGroupKey (Object obj)
boolean removeGroup (int objectiveId)
Removes groups for the next objective ID given.
Protected Member Functions
DefaultTransitGroupHandler (DeviceId deviceId, ApplicationId appId, DeviceProperties config, LinkService linkService, FlowObjectiveService flowObjService, EventuallyConsistentMap< NeighborSetNextObjectiveStoreKey, Integer > nsNextObjStore, EventuallyConsistentMap< SubnetNextObjectiveStoreKey, Integer > subnetNextObjStore)
void newNeighbor (Link newNeighborLink)
void newPortToExistingNeighbor (Link newNeighborLink)
Set< NeighborSet > computeImpactedNeighborsetForPortEvent (DeviceId impactedNeighbor, Set< DeviceId > updatedNeighbors)
Protected Member Functions inherited from org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler
DefaultGroupHandler (DeviceId deviceId, ApplicationId appId, DeviceProperties config, LinkService linkService, FlowObjectiveService flowObjService, EventuallyConsistentMap< NeighborSetNextObjectiveStoreKey, Integer > nsNextObjStore, EventuallyConsistentMap< SubnetNextObjectiveStoreKey, Integer > subnetNextObjStore)
void newNeighbor (Link newLink)
void newPortToExistingNeighbor (Link newLink)
Set< NeighborSet > computeImpactedNeighborsetForPortEvent (DeviceId impactedNeighbor, Set< DeviceId > updatedNeighbors)
void addNeighborAtPort (DeviceId neighborId, PortNumber portToNeighbor)
Set< Set< DeviceId > > getPowerSetOfNeighbors (Set< DeviceId > neighbors)
List< Integer > getSegmentIdsTobePairedWithNeighborSet (Set< DeviceId > neighbors)
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler
static DefaultGroupHandler createGroupHandler (DeviceId deviceId, ApplicationId appId, DeviceProperties config, LinkService linkService, FlowObjectiveService flowObjService, EventuallyConsistentMap< NeighborSetNextObjectiveStoreKey, Integer > nsNextObjStore, EventuallyConsistentMap< SubnetNextObjectiveStoreKey, Integer > subnetNextObjStore) throws DeviceConfigNotFoundException
Creates a group handler object based on the type of device.
Protected Attributes inherited from org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler
final DeviceId deviceId
final ApplicationId appId
final DeviceProperties deviceConfig
final List< Integer > allSegmentIds
int nodeSegmentId = -1
boolean isEdgeRouter = false
MacAddress nodeMacAddr = null
LinkService linkService
FlowObjectiveService flowObjectiveService
ConcurrentHashMap< DeviceId,
Set< PortNumber > > devicePortMap
ConcurrentHashMap< PortNumber,
DeviceId > portDeviceMap
EventuallyConsistentMap
< NeighborSetNextObjectiveStoreKey,
Integer > nsNextObjStore = null
EventuallyConsistentMap
< SubnetNextObjectiveStoreKey,
Integer > subnetNextObjStore = null
KryoNamespace.Builder kryo
Static Protected Attributes inherited from org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler
static final Logger log = getLogger(DefaultGroupHandler.class)
Detailed Description
Default ECMP group handler creation module for a transit device.
This component creates a set of ECMP groups for every neighbor that this device is connected to. For example, consider a network of 4 devices: D0 (Segment ID: 100), D1 (Segment ID: 101), D2 (Segment ID: 102) and D3 (Segment ID: 103), where D0 and D3 are edge devices and D1 and D2 are transit devices. Assume transit device D1 is connected to 2 neighbors (D0 and D3). The following groups will be created in D1: 1) all ports to D0 + with no label push, 2) all ports to D3 + with no label push,
Definition at line 42 of file DefaultTransitGroupHandler.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler.DefaultTransitGroupHandler (DeviceId deviceId, ApplicationId appId, DeviceProperties config, LinkService linkService, FlowObjectiveService flowObjService, EventuallyConsistentMap< NeighborSetNextObjectiveStoreKey, Integer > nsNextObjStore, EventuallyConsistentMap< SubnetNextObjectiveStoreKey, Integer > subnetNextObjStore) protected
Definition at line 44 of file DefaultTransitGroupHandler.java.
References org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.nsNextObjStore, and org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.subnetNextObjStore.
Member Function Documentation
Set<NeighborSet> org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler.computeImpactedNeighborsetForPortEvent (DeviceId impactedNeighbor, Set< DeviceId > updatedNeighbors) protected
Definition at line 140 of file DefaultTransitGroupHandler.java.
References org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.deviceId, and org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.getPowerSetOfNeighbors().
Referenced by org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler.newNeighbor().
void org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler.createGroups ()
Definition at line 59 of file DefaultTransitGroupHandler.java.
References org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.deviceId, and org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.getPowerSetOfNeighbors().
void org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler.newNeighbor (Link newNeighborLink) protected
Definition at line 88 of file DefaultTransitGroupHandler.java.
References org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.addNeighborAtPort(), org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler.computeImpactedNeighborsetForPortEvent(), org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.deviceId, org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.devicePortMap, org.onosproject.net.Link.dst(), and org.onosproject.net.Link.src().
void org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler.newPortToExistingNeighbor (Link newNeighborLink) protected
Definition at line 102 of file DefaultTransitGroupHandler.java.
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/grouphandler/DefaultTransitGroupHandler.java