onos: org.onosproject.vtnrsc.DefaultFlowClassifier Class Reference
org.onosproject.vtnrsc.DefaultFlowClassifier Class Reference
Provides Default flow classifier.
Classes
class Builder
Builder class for constructing Flow classifier.
Public Member Functions
FlowClassifierId flowClassifierId ()
Returns flow classifier ID.
TenantId tenantId ()
Returns Tenant ID.
String name ()
Returns flow classifier name.
String description ()
Returns flow classifier description.
String etherType ()
Returns EtherType.
String protocol ()
Returns IP Protocol.
int minSrcPortRange ()
Returns minimum source port range.
int maxSrcPortRange ()
Returns maximum source port range.
int minDstPortRange ()
Returns minimum destination port range.
int maxDstPortRange ()
Returns maximum destination port range.
IpPrefix srcIpPrefix ()
Returns Source IP prefix.
IpPrefix dstIpPrefix ()
Returns Destination IP prefix.
VirtualPortId srcPort ()
Returns Source virtual port.
VirtualPortId dstPort ()
Returns Destination virtual port.
int hashCode ()
boolean equals (Object obj)
boolean exactMatch (FlowClassifier flowClassifier)
Returns whether this Flow classifier is an exact match to the Flow classifier given in the argument.
String toString ()
Detailed Description
Provides Default flow classifier.
Definition at line 27 of file DefaultFlowClassifier.java.
Member Function Documentation
String org.onosproject.vtnrsc.DefaultFlowClassifier.description ()
Returns flow classifier description.
Returns
flow classifier description
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 103 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode(), and org.onosproject.vtnrsc.DefaultFlowClassifier.toString().
IpPrefix org.onosproject.vtnrsc.DefaultFlowClassifier.dstIpPrefix ()
Returns Destination IP prefix.
Returns
Destination IP prefix
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 143 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode(), and org.onosproject.vtnrsc.DefaultFlowClassifier.toString().
VirtualPortId org.onosproject.vtnrsc.DefaultFlowClassifier.dstPort ()
Returns Destination virtual port.
Returns
Destination virtual port
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 153 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode(), and org.onosproject.vtnrsc.DefaultFlowClassifier.toString().
boolean org.onosproject.vtnrsc.DefaultFlowClassifier.equals (Object obj)
Definition at line 343 of file DefaultFlowClassifier.java.
References create-flow.name, and find-link-in-cluster.srcPort.
String org.onosproject.vtnrsc.DefaultFlowClassifier.etherType ()
Returns EtherType.
Returns
EtherType
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 108 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode().
boolean org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch (FlowClassifier flowClassifier)
Returns whether this Flow classifier is an exact match to the Flow classifier given in the argument.
Parameters
flowClassifier other flowClassifier to match against
Returns
true if the flowClassifiers are an exact match, otherwise false
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 368 of file DefaultFlowClassifier.java.
References org.onosproject.vtnrsc.FlowClassifier.description(), org.onosproject.vtnrsc.FlowClassifier.dstIpPrefix(), org.onosproject.vtnrsc.FlowClassifier.dstPort(), org.onosproject.vtnrsc.FlowClassifier.etherType(), org.onosproject.vtnrsc.FlowClassifier.flowClassifierId(), org.onosproject.vtnrsc.FlowClassifier.maxDstPortRange(), org.onosproject.vtnrsc.FlowClassifier.maxSrcPortRange(), org.onosproject.vtnrsc.FlowClassifier.minDstPortRange(), org.onosproject.vtnrsc.FlowClassifier.minSrcPortRange(), org.onosproject.vtnrsc.FlowClassifier.name(), org.onosproject.vtnrsc.FlowClassifier.protocol(), org.onosproject.vtnrsc.FlowClassifier.srcIpPrefix(), org.onosproject.vtnrsc.FlowClassifier.srcPort(), and org.onosproject.vtnrsc.FlowClassifier.tenantId().
FlowClassifierId org.onosproject.vtnrsc.DefaultFlowClassifier.flowClassifierId ()
Returns flow classifier ID.
Returns
flow classifier id
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 88 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode().
int org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode ()
Definition at line 337 of file DefaultFlowClassifier.java.
References org.onosproject.vtnrsc.DefaultFlowClassifier.description(), org.onosproject.vtnrsc.DefaultFlowClassifier.dstIpPrefix(), org.onosproject.vtnrsc.DefaultFlowClassifier.dstPort(), org.onosproject.vtnrsc.DefaultFlowClassifier.etherType(), org.onosproject.vtnrsc.DefaultFlowClassifier.flowClassifierId(), org.onosproject.vtnrsc.DefaultFlowClassifier.maxDstPortRange(), org.onosproject.vtnrsc.DefaultFlowClassifier.maxSrcPortRange(), org.onosproject.vtnrsc.DefaultFlowClassifier.minDstPortRange(), org.onosproject.vtnrsc.DefaultFlowClassifier.minSrcPortRange(), org.onosproject.vtnrsc.DefaultFlowClassifier.name(), org.onosproject.vtnrsc.DefaultFlowClassifier.protocol(), org.onosproject.vtnrsc.DefaultFlowClassifier.srcIpPrefix(), org.onosproject.vtnrsc.DefaultFlowClassifier.srcPort(), and org.onosproject.vtnrsc.DefaultFlowClassifier.tenantId().
int org.onosproject.vtnrsc.DefaultFlowClassifier.maxDstPortRange ()
Returns maximum destination port range.
Returns
maximum destination port range.
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 133 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode(), and org.onosproject.vtnrsc.DefaultFlowClassifier.toString().
int org.onosproject.vtnrsc.DefaultFlowClassifier.maxSrcPortRange ()
Returns maximum source port range.
Returns
maximum source port range
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 123 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode(), and org.onosproject.vtnrsc.DefaultFlowClassifier.toString().
int org.onosproject.vtnrsc.DefaultFlowClassifier.minDstPortRange ()
Returns minimum destination port range.
Returns
minimum destination port range
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 128 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode().
int org.onosproject.vtnrsc.DefaultFlowClassifier.minSrcPortRange ()
Returns minimum source port range.
Returns
minimum source port range
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 118 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode().
String org.onosproject.vtnrsc.DefaultFlowClassifier.name ()
Returns flow classifier name.
Returns
flow classifier name
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 98 of file DefaultFlowClassifier.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.vtnrsc.DefaultFlowClassifier.protocol ()
Returns IP Protocol.
Returns
IP protocol
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 113 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode(), and org.onosproject.vtnrsc.DefaultFlowClassifier.toString().
IpPrefix org.onosproject.vtnrsc.DefaultFlowClassifier.srcIpPrefix ()
Returns Source IP prefix.
Returns
Source IP prefix
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 138 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode().
VirtualPortId org.onosproject.vtnrsc.DefaultFlowClassifier.srcPort ()
Returns Source virtual port.
Returns
Source virtual port
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 148 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode().
TenantId org.onosproject.vtnrsc.DefaultFlowClassifier.tenantId ()
Returns Tenant ID.
Returns
tenant Id
Implements org.onosproject.vtnrsc.FlowClassifier.
Definition at line 93 of file DefaultFlowClassifier.java.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.hashCode(), and org.onosproject.vtnrsc.DefaultFlowClassifier.toString().
String org.onosproject.vtnrsc.DefaultFlowClassifier.toString ()
Definition at line 387 of file DefaultFlowClassifier.java.
References org.onosproject.vtnrsc.DefaultFlowClassifier.description(), org.onosproject.vtnrsc.DefaultFlowClassifier.dstIpPrefix(), org.onosproject.vtnrsc.DefaultFlowClassifier.dstPort(), org.onosproject.vtnrsc.DefaultFlowClassifier.maxDstPortRange(), org.onosproject.vtnrsc.DefaultFlowClassifier.maxSrcPortRange(), org.onosproject.vtnrsc.DefaultFlowClassifier.protocol(), and org.onosproject.vtnrsc.DefaultFlowClassifier.tenantId().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultFlowClassifier.java