onos: org.onosproject.vtnweb.resources.RouterWebResource Class Reference
org.onosproject.vtnweb.resources.RouterWebResource Class Reference
Public Member Functions
Response listRouters ()
Response getRouter (@PathParam("routerUUID") String id,@QueryParam("fields") List< String > fields)
Response createRouter (final InputStream input)
Response updateRouter (@PathParam("routerUUID") String id, final InputStream input)
Response deleteSingleRouter (@PathParam("routerUUID") String id) throws IOException
Response addRouterInterface (@PathParam("routerUUID") String id, final InputStream input)
Response removeRouterInterface (@PathParam("routerUUID") String id, final InputStream input)
Collection< Router > changeJsonToSub (JsonNode routerNode) throws Exception
Returns a collection of floatingIps from floatingIpNodes.
Public Member Functions inherited from org.onosproject.rest.AbstractWebResource
ObjectMapper mapper ()
Returns the JSON object mapper.
ObjectNode newObject (ObjectNode parent, String key)
Creates and returns a new child object within the specified parent and bound to the given key.
ArrayNode newArray (ObjectNode parent, String key)
Creates and returns a new child array within the specified parent and bound to the given key.
Static Public Attributes
static final String CREATE_FAIL = "Router is failed to create!"
static final String UPDATE_FAIL = "Router is failed to update!"
static final String GET_FAIL = "Router is failed to get!"
static final String NOT_EXIST = "Router does not exist!"
static final String DELETE_SUCCESS = "Router delete success!"
static final String JSON_NOT_NULL = "JsonNode can not be null"
static final String INTFACR_ADD_SUCCESS = "Interface add success"
static final String INTFACR_DEL_SUCCESS = "Interface delete success"
Additional Inherited Members
Static Public Member Functions inherited from org.onlab.rest.BaseResource
static void setServiceDirectory (ServiceDirectory serviceDirectory)
Sets alternate service directory to be used for lookups.
Static Protected Member Functions inherited from org.onlab.rest.BaseResource
static Response.ResponseBuilder ok (Object obj)
Detailed Description
Definition at line 76 of file RouterWebResource.java.
Member Function Documentation
Response org.onosproject.vtnweb.resources.RouterWebResource.addRouterInterface (@PathParam("routerUUID") String id, final InputStream input)
Definition at line 181 of file RouterWebResource.java.
References find-device.id, and org.onosproject.vtnrsc.RouterId.valueOf().
Collection<Router> org.onosproject.vtnweb.resources.RouterWebResource.changeJsonToSub (JsonNode routerNode) throws Exception
Returns a collection of floatingIps from floatingIpNodes.
Parameters
routerNode the router json node
Returns
routers a collection of router
Exceptions
Exception when any argument is illegal
Definition at line 298 of file RouterWebResource.java.
References find-device.id.
Response org.onosproject.vtnweb.resources.RouterWebResource.createRouter (final InputStream input)
Definition at line 123 of file RouterWebResource.java.
Response org.onosproject.vtnweb.resources.RouterWebResource.deleteSingleRouter (@PathParam("routerUUID") String id) throws IOException
Definition at line 165 of file RouterWebResource.java.
References find-device.id.
Response org.onosproject.vtnweb.resources.RouterWebResource.getRouter (@PathParam("routerUUID") String id, @QueryParam("fields") List< String > fields)
Definition at line 99 of file RouterWebResource.java.
References org.onosproject.vtnrsc.RouterId.valueOf().
Response org.onosproject.vtnweb.resources.RouterWebResource.listRouters ()
Definition at line 89 of file RouterWebResource.java.
Response org.onosproject.vtnweb.resources.RouterWebResource.removeRouterInterface (@PathParam("routerUUID") String id, final InputStream input)
Definition at line 230 of file RouterWebResource.java.
References find-device.id, and org.onosproject.vtnrsc.RouterId.valueOf().
Response org.onosproject.vtnweb.resources.RouterWebResource.updateRouter (@PathParam("routerUUID") String id, final InputStream input)
Definition at line 146 of file RouterWebResource.java.
Member Data Documentation
final String org.onosproject.vtnweb.resources.RouterWebResource.CREATE_FAIL = "Router is failed to create!" static
Definition at line 78 of file RouterWebResource.java.
final String org.onosproject.vtnweb.resources.RouterWebResource.DELETE_SUCCESS = "Router delete success!" static
Definition at line 82 of file RouterWebResource.java.
final String org.onosproject.vtnweb.resources.RouterWebResource.GET_FAIL = "Router is failed to get!" static
Definition at line 80 of file RouterWebResource.java.
final String org.onosproject.vtnweb.resources.RouterWebResource.INTFACR_ADD_SUCCESS = "Interface add success" static
Definition at line 84 of file RouterWebResource.java.
final String org.onosproject.vtnweb.resources.RouterWebResource.INTFACR_DEL_SUCCESS = "Interface delete success" static
Definition at line 85 of file RouterWebResource.java.
final String org.onosproject.vtnweb.resources.RouterWebResource.JSON_NOT_NULL = "JsonNode can not be null" static
Definition at line 83 of file RouterWebResource.java.
final String org.onosproject.vtnweb.resources.RouterWebResource.NOT_EXIST = "Router does not exist!" static
Definition at line 81 of file RouterWebResource.java.
final String org.onosproject.vtnweb.resources.RouterWebResource.UPDATE_FAIL = "Router is failed to update!" static
Definition at line 79 of file RouterWebResource.java.
The documentation for this class was generated from the following file:
apps/vtn/vtnweb/src/main/java/org/onosproject/vtnweb/resources/RouterWebResource.java