onos: org.onosproject.provider.of.group.impl.GroupModBuilder Class Reference
org.onosproject.provider.of.group.impl.GroupModBuilder Class Reference
Public Member Functions
OFGroupAdd buildGroupAdd ()
Builds the GroupAdd OF message.
OFGroupMod buildGroupMod ()
Builds the GroupMod OF message.
OFGroupDelete buildGroupDel ()
Builds the GroupDel OF message.
Static Public Member Functions
static GroupModBuilder builder (GroupBuckets buckets, GroupId groupId, GroupDescription.Type type, OFFactory factory, Optional< Long > xid)
Creates a builder for GroupMod.
static GroupModBuilder builder (GroupBuckets buckets, GroupId groupId, GroupDescription.Type type, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService)
Creates a builder for GroupMod.
Detailed Description
Definition at line 73 of file GroupModBuilder.java.
Member Function Documentation
static GroupModBuilder org.onosproject.provider.of.group.impl.GroupModBuilder.builder (GroupBuckets buckets, GroupId groupId, GroupDescription.Type type, OFFactory factory, Optional< Long > xid) static
Creates a builder for GroupMod.
Parameters
buckets GroupBuckets object
groupId Group Id to create
type Group type
factory OFFactory object
xid transaction ID
Returns
GroupModBuilder object
Definition at line 116 of file GroupModBuilder.java.
static GroupModBuilder org.onosproject.provider.of.group.impl.GroupModBuilder.builder (GroupBuckets buckets, GroupId groupId, GroupDescription.Type type, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService) static
Creates a builder for GroupMod.
Parameters
buckets GroupBuckets object
groupId Group Id to create
type Group type
factory OFFactory object
xid transaction ID
driverService driver Service
Returns
GroupModBuilder object
Definition at line 134 of file GroupModBuilder.java.
OFGroupAdd org.onosproject.provider.of.group.impl.GroupModBuilder.buildGroupAdd ()
Builds the GroupAdd OF message.
Returns
GroupAdd OF message
Definition at line 146 of file GroupModBuilder.java.
References org.onosproject.core.GroupId.id().
OFGroupDelete org.onosproject.provider.of.group.impl.GroupModBuilder.buildGroupDel ()
Builds the GroupDel OF message.
Returns
GroupDel OF message
Definition at line 218 of file GroupModBuilder.java.
References org.onosproject.core.GroupId.id().
OFGroupMod org.onosproject.provider.of.group.impl.GroupModBuilder.buildGroupMod ()
Builds the GroupMod OF message.
Returns
GroupMod OF message
Definition at line 187 of file GroupModBuilder.java.
References org.onosproject.core.GroupId.id().
The documentation for this class was generated from the following file:
providers/openflow/group/src/main/java/org/onosproject/provider/of/group/impl/GroupModBuilder.java