onos: org.onosproject.net.intent.IntentOperation Class Reference
org.onosproject.net.intent.IntentOperation Class Reference
Abstraction of an intent-related operation, e.g.
Classes
enum Type
Operation type.
Public Member Functions
IntentOperation (Type type, Intent intent)
Creates an intent operation.
Type type ()
Returns the type of the operation.
IntentId intentId ()
Returns the identifier of the intent to which this operation applies.
Key key ()
Returns the key for this intent.
Intent intent ()
Returns the intent to which this operation applied.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Abstraction of an intent-related operation, e.g.
add, remove, replace.
Definition at line 30 of file IntentOperation.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.IntentOperation.IntentOperation (Type type, Intent intent)
Creates an intent operation.
Parameters
type operation type
intent intent subject
Definition at line 56 of file IntentOperation.java.
References org.onosproject.net.intent.IntentOperation.intent().
Referenced by org.onosproject.net.intent.IntentOperation.equals().
Member Function Documentation
boolean org.onosproject.net.intent.IntentOperation.equals (Object obj)
Definition at line 104 of file IntentOperation.java.
References org.onosproject.net.intent.IntentOperation.equals(), and org.onosproject.net.intent.IntentOperation.IntentOperation().
Referenced by org.onosproject.net.intent.IntentOperation.equals().
int org.onosproject.net.intent.IntentOperation.hashCode ()
Definition at line 99 of file IntentOperation.java.
References org.onosproject.net.intent.IntentOperation.intent(), and org.onosproject.net.intent.IntentOperation.type().
Intent org.onosproject.net.intent.IntentOperation.intent ()
Returns the intent to which this operation applied.
For remove, this can be null.
Returns
intent that is the subject of the operation; null for remove
Definition at line 94 of file IntentOperation.java.
Referenced by org.onosproject.net.intent.IntentOperation.hashCode(), org.onosproject.net.intent.IntentOperation.IntentOperation(), and org.onosproject.net.intent.IntentOperation.toString().
IntentId org.onosproject.net.intent.IntentOperation.intentId ()
Returns the identifier of the intent to which this operation applies.
Returns
intent identifier
Definition at line 75 of file IntentOperation.java.
Key org.onosproject.net.intent.IntentOperation.key ()
Returns the key for this intent.
Returns
key value
Definition at line 84 of file IntentOperation.java.
String org.onosproject.net.intent.IntentOperation.toString ()
Definition at line 118 of file IntentOperation.java.
References org.onosproject.net.intent.IntentOperation.intent(), and org.onosproject.net.intent.IntentOperation.type().
Type org.onosproject.net.intent.IntentOperation.type ()
Returns the type of the operation.
Returns
operation type
Definition at line 66 of file IntentOperation.java.
Referenced by org.onosproject.net.intent.IntentOperation.hashCode(), and org.onosproject.net.intent.IntentOperation.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/IntentOperation.java