onos: org.onlab.packet.ipv6.AuthenticationTest Class Reference
org.onlab.packet.ipv6.AuthenticationTest Class Reference
Tests for class Authentication.
Public Member Functions
void setUp ()
void testSerialize ()
Tests serialize and setters.
void testDeserialize () throws Exception
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class Authentication.
Definition at line 35 of file AuthenticationTest.java.
Member Function Documentation
void org.onlab.packet.ipv6.AuthenticationTest.setUp ()
Definition at line 65 of file AuthenticationTest.java.
static void org.onlab.packet.ipv6.AuthenticationTest.setUpBeforeClass () throws Exception static
Definition at line 46 of file AuthenticationTest.java.
References find-link-in-cluster.length.
void org.onlab.packet.ipv6.AuthenticationTest.testDeserialize () throws Exception
Tests deserialize and getters.
Definition at line 89 of file AuthenticationTest.java.
References org.onlab.packet.ipv6.Authentication.getIntegrityCheck(), org.onlab.packet.ipv6.Authentication.getNextHeader(), org.onlab.packet.ipv6.Authentication.getPayloadLength(), org.onlab.packet.ipv6.Authentication.getSecurityParamIndex(), org.onlab.packet.ipv6.Authentication.getSequence(), and find-link-in-cluster.length.
void org.onlab.packet.ipv6.AuthenticationTest.testEqual ()
Tests comparator.
Definition at line 103 of file AuthenticationTest.java.
References org.onlab.packet.ipv6.Authentication.equals().
void org.onlab.packet.ipv6.AuthenticationTest.testSerialize ()
Tests serialize and setters.
Definition at line 73 of file AuthenticationTest.java.
References org.onlab.packet.ipv6.Authentication.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ipv6/AuthenticationTest.java