onos: org.onosproject.acl.AclRule Class Reference
org.onosproject.acl.AclRule Class Reference
ACL rule class.
Classes
enum Action
Enum type for ACL rule's action.
class Builder
Builder of an ACL rule.
Public Member Functions
boolean checkMatch (AclRule r)
Check if this ACL rule match the given ACL rule.
RuleId id ()
Ip4Prefix srcIp ()
Ip4Prefix dstIp ()
byte ipProto ()
short dstTpPort ()
Action action ()
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static Builder builder ()
Returns a new ACL rule builder.
static void bindIdGenerator (IdGenerator newIdGenerator)
Binds an id generator for unique ACL rule id generation.
Detailed Description
ACL rule class.
Definition at line 35 of file AclRule.java.
Member Function Documentation
Action org.onosproject.acl.AclRule.action ()
Definition at line 251 of file AclRule.java.
Referenced by org.onosproject.acl.AclRule.equals(), org.onosproject.acl.AclRule.hashCode(), and org.onosproject.acl.AclRule.toString().
static void org.onosproject.acl.AclRule.bindIdGenerator (IdGenerator newIdGenerator) static
Binds an id generator for unique ACL rule id generation.
Note: A generator cannot be bound if there is already a generator bound.
Parameters
newIdGenerator id generator
Definition at line 226 of file AclRule.java.
static Builder org.onosproject.acl.AclRule.builder () static
Returns a new ACL rule builder.
Returns
ACL rule builder
Definition at line 128 of file AclRule.java.
boolean org.onosproject.acl.AclRule.checkMatch (AclRule r)
Check if this ACL rule match the given ACL rule.
Parameters
r ACL rule to check against
Returns
true if this ACL rule matches the given ACL ruleule.
Definition at line 116 of file AclRule.java.
References org.onosproject.acl.AclRule.dstIp(), org.onosproject.acl.AclRule.dstTpPort(), and org.onosproject.acl.AclRule.srcIp().
Ip4Prefix org.onosproject.acl.AclRule.dstIp ()
Definition at line 239 of file AclRule.java.
Referenced by org.onosproject.acl.AclRule.checkMatch(), org.onosproject.acl.AclRule.equals(), org.onosproject.acl.AclRule.hashCode(), and org.onosproject.acl.AclRule.toString().
short org.onosproject.acl.AclRule.dstTpPort ()
Definition at line 247 of file AclRule.java.
Referenced by org.onosproject.acl.AclRule.checkMatch(), org.onosproject.acl.AclRule.equals(), and org.onosproject.acl.AclRule.toString().
boolean org.onosproject.acl.AclRule.equals (Object obj)
Definition at line 261 of file AclRule.java.
References org.onosproject.acl.AclRule.action(), org.onosproject.acl.AclRule.dstIp(), org.onosproject.acl.AclRule.dstTpPort(), find-device.id, org.onosproject.acl.AclRule.id(), org.onosproject.acl.AclRule.ipProto(), and org.onosproject.acl.AclRule.srcIp().
int org.onosproject.acl.AclRule.hashCode ()
Definition at line 256 of file AclRule.java.
References org.onosproject.acl.AclRule.action(), org.onosproject.acl.AclRule.dstIp(), org.onosproject.acl.AclRule.ipProto(), and org.onosproject.acl.AclRule.srcIp().
RuleId org.onosproject.acl.AclRule.id ()
Definition at line 231 of file AclRule.java.
Referenced by org.onosproject.acl.AclRule.equals(), and org.onosproject.acl.AclRule.toString().
byte org.onosproject.acl.AclRule.ipProto ()
Definition at line 243 of file AclRule.java.
Referenced by org.onosproject.acl.AclRule.equals(), org.onosproject.acl.AclRule.hashCode(), and org.onosproject.acl.AclRule.toString().
Ip4Prefix org.onosproject.acl.AclRule.srcIp ()
Definition at line 235 of file AclRule.java.
Referenced by org.onosproject.acl.AclRule.checkMatch(), org.onosproject.acl.AclRule.equals(), org.onosproject.acl.AclRule.hashCode(), and org.onosproject.acl.AclRule.toString().
String org.onosproject.acl.AclRule.toString ()
Definition at line 278 of file AclRule.java.
References org.onosproject.acl.AclRule.action(), org.onosproject.acl.AclRule.dstIp(), org.onosproject.acl.AclRule.dstTpPort(), org.onosproject.acl.AclRule.id(), org.onosproject.acl.AclRule.ipProto(), and org.onosproject.acl.AclRule.srcIp().
The documentation for this class was generated from the following file:
apps/acl/src/main/java/org/onosproject/acl/AclRule.java