onos: org.onosproject.ui.topo.NodeBadge Class Reference
org.onosproject.ui.topo.NodeBadge Class Reference
Designates a badge to be applied to a node in the topology view.
Classes
enum Status
Designates the badge status.
Public Member Functions
String toString ()
Status status ()
Returns the badge status.
boolean isGlyph ()
Returns true if the text for this badge designates a glyph ID.
String text ()
Returns the text for the badge.
String message ()
Returns the message associated with the badge.
Static Public Member Functions
static NodeBadge text (String txt)
Returns an arbitrary text badge, with default status.
static NodeBadge glyph (String gid)
Returns a glyph badge, with default status.
static NodeBadge number (int n)
Returns a numeric badge, with default status.
static NodeBadge text (Status s, String txt)
Returns an arbitrary text badge, with the given status.
static NodeBadge glyph (Status s, String gid)
Returns a glyph badge, with the given status.
static NodeBadge number (Status s, int n)
Returns a numeric badge, with the given status and optional message.
static NodeBadge text (Status s, String txt, String msg)
Returns an arbitrary text badge, with the given status and optional message.
static NodeBadge glyph (Status s, String gid, String msg)
Returns a glyph badge, with the given status and optional message.
static NodeBadge number (Status s, int n, String msg)
Returns a numeric badge, with the given status and optional message.
Detailed Description
Designates a badge to be applied to a node in the topology view.
Definition at line 22 of file NodeBadge.java.
Member Function Documentation
static NodeBadge org.onosproject.ui.topo.NodeBadge.glyph (String gid) static
Returns a glyph badge, with default status.
Parameters
gid the glyph ID
Returns
node badge to display glyph
Definition at line 129 of file NodeBadge.java.
References org.onosproject.ui.topo.NodeBadge.Status.INFO.
static NodeBadge org.onosproject.ui.topo.NodeBadge.glyph (Status s, String gid) static
Returns a glyph badge, with the given status.
Parameters
s the status
gid the glyph ID
Returns
node badge to display glyph
Definition at line 163 of file NodeBadge.java.
static NodeBadge org.onosproject.ui.topo.NodeBadge.glyph (Status s, String gid, String msg) static
Returns a glyph badge, with the given status and optional message.
Parameters
s the status
gid the glyph ID
msg the optional message
Returns
node badge to display glyph
Definition at line 202 of file NodeBadge.java.
boolean org.onosproject.ui.topo.NodeBadge.isGlyph ()
Returns true if the text for this badge designates a glyph ID.
Returns
true if badge uses glyph
Definition at line 84 of file NodeBadge.java.
Referenced by org.onosproject.ui.topo.NodeBadge.toString().
String org.onosproject.ui.topo.NodeBadge.message ()
Returns the message associated with the badge.
Returns
associated message
Definition at line 104 of file NodeBadge.java.
Referenced by org.onosproject.ui.topo.NodeBadge.toString().
static NodeBadge org.onosproject.ui.topo.NodeBadge.number (int n) static
Returns a numeric badge, with default status.
Parameters
n the number
Returns
node badge to display a number
Definition at line 139 of file NodeBadge.java.
References org.onosproject.ui.topo.NodeBadge.Status.INFO.
static NodeBadge org.onosproject.ui.topo.NodeBadge.number (Status s, int n) static
Returns a numeric badge, with the given status and optional message.
Parameters
s the status
n the number
Returns
node badge to display a number
Definition at line 175 of file NodeBadge.java.
References org.onosproject.ui.topo.NodeBadge.Status.toString().
static NodeBadge org.onosproject.ui.topo.NodeBadge.number (Status s, int n, String msg) static
Returns a numeric badge, with the given status and optional message.
Parameters
s the status
n the number
msg the optional message
Returns
node badge to display a number
Definition at line 215 of file NodeBadge.java.
References org.onosproject.ui.topo.NodeBadge.Status.toString().
Status org.onosproject.ui.topo.NodeBadge.status ()
Returns the badge status.
Returns
badge status
Definition at line 75 of file NodeBadge.java.
Referenced by org.onosproject.ui.topo.NodeBadge.toString().
String org.onosproject.ui.topo.NodeBadge.text ()
Returns the text for the badge.
Note that if isGlyph is true, the text is a glyph ID, otherwise the text is displayed verbatim in the badge.
Returns
text for badge
Definition at line 95 of file NodeBadge.java.
Referenced by org.onosproject.ui.topo.NodeBadge.toString().
static NodeBadge org.onosproject.ui.topo.NodeBadge.text (String txt) static
Returns an arbitrary text badge, with default status.
Parameters
txt the text
Returns
node badge to display text
Definition at line 118 of file NodeBadge.java.
References org.onosproject.ui.topo.NodeBadge.Status.INFO.
static NodeBadge org.onosproject.ui.topo.NodeBadge.text (Status s, String txt) static
Returns an arbitrary text badge, with the given status.
Parameters
s the status
txt the text
Returns
node badge to display text
Definition at line 151 of file NodeBadge.java.
static NodeBadge org.onosproject.ui.topo.NodeBadge.text (Status s, String txt, String msg) static
Returns an arbitrary text badge, with the given status and optional message.
Parameters
s the status
txt the text
msg the optional message
Returns
node badge to display text
Definition at line 189 of file NodeBadge.java.
String org.onosproject.ui.topo.NodeBadge.toString ()
Definition at line 63 of file NodeBadge.java.
References org.onosproject.ui.topo.NodeBadge.isGlyph(), org.onosproject.ui.topo.NodeBadge.message(), org.onosproject.ui.topo.NodeBadge.status(), and org.onosproject.ui.topo.NodeBadge.text().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/topo/NodeBadge.java