onos: org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager Class Reference
org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager Class Reference
Provides implementation of the Flow Classifier Service.
Public Member Functions
boolean exists (FlowClassifierId id)
Check whether Flow Classifier is present based on given Flow Classifier Id.
int getFlowClassifierCount ()
Returns the number of flow classifiers known to the system.
Iterable< FlowClassifier > getFlowClassifiers ()
Return the existing collection of Flow Classifier.
FlowClassifier getFlowClassifier (FlowClassifierId id)
Retrieve the Flow Classifier based on given Flow Classifier id.
boolean createFlowClassifier (FlowClassifier flowClassifier)
Store Flow Classifier.
boolean updateFlowClassifier (FlowClassifier flowClassifier)
Update Flow Classifier based on given Flow Classifier Id.
boolean removeFlowClassifier (FlowClassifierId id)
Remove Flow Classifier from store based on given Flow Classifier Id.
Protected Member Functions
void activate ()
void deactivate ()
Protected Attributes
StorageService storageService
Detailed Description
Provides implementation of the Flow Classifier Service.
Definition at line 45 of file FlowClassifierManager.java.
Member Function Documentation
void org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.activate () protected
Definition at line 57 of file FlowClassifierManager.java.
References org.onosproject.store.serializers.KryoNamespaces.API.
boolean org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.createFlowClassifier (FlowClassifier flowClassifier)
Store Flow Classifier.
Parameters
flowClassifier flow classifier
Returns
true if adding flow classifier into store is success otherwise return false
Implements org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.
Definition at line 98 of file FlowClassifierManager.java.
References find-device.id.
Referenced by org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testCreateFlowClassifier().
void org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.deactivate () protected
Definition at line 70 of file FlowClassifierManager.java.
boolean org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.exists (FlowClassifierId id)
Check whether Flow Classifier is present based on given Flow Classifier Id.
Parameters
id flow classifier identifier
Returns
true if flow classifier is present otherwise return false
Implements org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.
Definition at line 76 of file FlowClassifierManager.java.
References find-device.id.
Referenced by org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testExists().
FlowClassifier org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.getFlowClassifier (FlowClassifierId id)
Retrieve the Flow Classifier based on given Flow Classifier id.
Parameters
id flow classifier identifier
Returns
flow classifier if present otherwise returns null
Implements org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.
Definition at line 92 of file FlowClassifierManager.java.
References find-device.id.
Referenced by org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testGetFlowClassifier().
int org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.getFlowClassifierCount ()
Returns the number of flow classifiers known to the system.
Returns
number of flow classifiers
Implements org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.
Definition at line 82 of file FlowClassifierManager.java.
Referenced by org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testGetFlowClassifierCount().
Iterable<FlowClassifier> org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.getFlowClassifiers ()
Return the existing collection of Flow Classifier.
Returns
flow classifier collections
Implements org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.
Definition at line 87 of file FlowClassifierManager.java.
boolean org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.removeFlowClassifier (FlowClassifierId id)
Remove Flow Classifier from store based on given Flow Classifier Id.
Parameters
id flow classifier identifier
Returns
true if flow classifier removal is success otherwise return false
Implements org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.
Definition at line 132 of file FlowClassifierManager.java.
References find-device.id.
Referenced by org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testRemoveFlowClassifier().
boolean org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.updateFlowClassifier (FlowClassifier flowClassifier)
Update Flow Classifier based on given Flow Classifier Id.
Parameters
flowClassifier flow classifier
Returns
true if flow classifier update is success otherwise return false
Implements org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.
Definition at line 112 of file FlowClassifierManager.java.
References org.onosproject.vtnrsc.FlowClassifier.flowClassifierId().
Referenced by org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManagerTest.testUpdateFlowClassifier().
Member Data Documentation
StorageService org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.storageService protected
Definition at line 54 of file FlowClassifierManager.java.
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/flowclassifier/impl/FlowClassifierManager.java