onos: org.onosproject.pcep.controller.impl.PcepClientControllerImpl Class Reference
org.onosproject.pcep.controller.impl.PcepClientControllerImpl Class Reference
Implementation of PCEP client controller.
Classes
class PcepClientAgent
Implementation of an Pcep Agent which is responsible for keeping track of connected clients and the state in which they are.
Public Member Functions
void activate ()
void deactivate ()
Collection< PcepClient > getClients ()
Returns list of pcc clients connected to this Pcep controller.
PcepClient getClient (PccId pccId)
Returns the actual pcc client for the given ip address.
void addListener (PcepClientListener listener)
Register a listener for meta events that occur to pcep devices.
void removeListener (PcepClientListener listener)
Unregister a listener.
void addEventListener (PcepEventListener listener)
Register a listener for OF msg events.
void removeEventListener (PcepEventListener listener)
Unregister a listener.
void writeMessage (PccId pccId, PcepMessage msg)
Send a message to a particular pcc client.
void processClientMessage (PccId pccId, PcepMessage msg)
Process a message and notify the appropriate listeners.
void closeConnectedClients ()
Close all connected PCC clients.
Protected Attributes
ConcurrentHashMap< PccId,
PcepClient > connectedClients
PcepClientAgent agent = new PcepClientAgent()
Set< PcepClientListener > pcepClientListener = new HashSet<>()
Set< PcepEventListener > pcepEventListener = Sets.newHashSet()
Detailed Description
Implementation of PCEP client controller.
Definition at line 45 of file PcepClientControllerImpl.java.
Member Function Documentation
void org.onosproject.pcep.controller.impl.PcepClientControllerImpl.activate ()
Definition at line 60 of file PcepClientControllerImpl.java.
References org.onosproject.pcep.controller.impl.PcepClientControllerImpl.agent.
void org.onosproject.pcep.controller.impl.PcepClientControllerImpl.addEventListener (PcepEventListener listener)
Register a listener for OF msg events.
Parameters
listener the listener to notify
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 96 of file PcepClientControllerImpl.java.
void org.onosproject.pcep.controller.impl.PcepClientControllerImpl.addListener (PcepClientListener listener)
Register a listener for meta events that occur to pcep devices.
Parameters
listener the listener to notify
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 84 of file PcepClientControllerImpl.java.
References org.onosproject.pcep.controller.impl.PcepClientControllerImpl.pcepClientListener.
void org.onosproject.pcep.controller.impl.PcepClientControllerImpl.closeConnectedClients ()
Close all connected PCC clients.
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 162 of file PcepClientControllerImpl.java.
References org.onosproject.pcep.controller.impl.PcepClientControllerImpl.connectedClients, and org.onosproject.pcep.controller.impl.PcepClientControllerImpl.getClient().
Referenced by org.onosproject.pcep.controller.impl.PcepClientControllerImpl.deactivate().
void org.onosproject.pcep.controller.impl.PcepClientControllerImpl.deactivate ()
Definition at line 66 of file PcepClientControllerImpl.java.
References org.onosproject.pcep.controller.impl.PcepClientControllerImpl.closeConnectedClients().
PcepClient org.onosproject.pcep.controller.impl.PcepClientControllerImpl.getClient (PccId pccId)
Returns the actual pcc client for the given ip address.
Parameters
pccId the id of the pcc client to fetch
Returns
the interface to this pcc client
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 79 of file PcepClientControllerImpl.java.
Referenced by org.onosproject.pcep.controller.impl.PcepClientControllerImpl.closeConnectedClients(), and org.onosproject.pcep.controller.impl.PcepClientControllerImpl.processClientMessage().
Collection<PcepClient> org.onosproject.pcep.controller.impl.PcepClientControllerImpl.getClients ()
Returns list of pcc clients connected to this Pcep controller.
Returns
list of PcepClient elements
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 74 of file PcepClientControllerImpl.java.
void org.onosproject.pcep.controller.impl.PcepClientControllerImpl.processClientMessage (PccId pccId, PcepMessage msg)
Process a message and notify the appropriate listeners.
Parameters
pccId id of the client the message arrived on
msg the message to process.
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 111 of file PcepClientControllerImpl.java.
References org.onosproject.pcep.controller.impl.PcepClientControllerImpl.getClient(), org.onosproject.pcepio.protocol.PcepMessage.getType(), and org.onosproject.pcep.controller.impl.PcepClientControllerImpl.pcepEventListener.
Referenced by org.onosproject.pcep.controller.impl.PcepClientControllerImpl.PcepClientAgent.processPcepMessage().
void org.onosproject.pcep.controller.impl.PcepClientControllerImpl.removeEventListener (PcepEventListener listener)
Unregister a listener.
Parameters
listener the listener to unregister
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 101 of file PcepClientControllerImpl.java.
void org.onosproject.pcep.controller.impl.PcepClientControllerImpl.removeListener (PcepClientListener listener)
Unregister a listener.
Parameters
listener the listener to unregister
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 91 of file PcepClientControllerImpl.java.
void org.onosproject.pcep.controller.impl.PcepClientControllerImpl.writeMessage (PccId pccId, PcepMessage msg)
Send a message to a particular pcc client.
Parameters
pccId the id of the client to send message.
msg the message to send
Implements org.onosproject.pcep.controller.PcepClientController.
Definition at line 106 of file PcepClientControllerImpl.java.
Member Data Documentation
PcepClientAgent org.onosproject.pcep.controller.impl.PcepClientControllerImpl.agent = new PcepClientAgent() protected
Definition at line 52 of file PcepClientControllerImpl.java.
Referenced by org.onosproject.pcep.controller.impl.PcepClientControllerImpl.activate().
ConcurrentHashMap<PccId, PcepClient> org.onosproject.pcep.controller.impl.PcepClientControllerImpl.connectedClients protected
Initial value:
=
            new ConcurrentHashMap<>()
Definition at line 49 of file PcepClientControllerImpl.java.
Referenced by org.onosproject.pcep.controller.impl.PcepClientControllerImpl.PcepClientAgent.addConnectedClient(), org.onosproject.pcep.controller.impl.PcepClientControllerImpl.closeConnectedClients(), and org.onosproject.pcep.controller.impl.PcepClientControllerImpl.PcepClientAgent.validActivation().
Set<PcepClientListener> org.onosproject.pcep.controller.impl.PcepClientControllerImpl.pcepClientListener = new HashSet<>() protected
Definition at line 53 of file PcepClientControllerImpl.java.
Referenced by org.onosproject.pcep.controller.impl.PcepClientControllerImpl.PcepClientAgent.addConnectedClient(), org.onosproject.pcep.controller.impl.PcepClientControllerImpl.addListener(), and org.onosproject.pcep.controller.impl.PcepClientControllerImpl.PcepClientAgent.removeConnectedClient().
Set<PcepEventListener> org.onosproject.pcep.controller.impl.PcepClientControllerImpl.pcepEventListener = Sets.newHashSet() protected
Definition at line 55 of file PcepClientControllerImpl.java.
Referenced by org.onosproject.pcep.controller.impl.PcepClientControllerImpl.processClientMessage().
The documentation for this class was generated from the following file:
protocols/pcep/ctl/src/main/java/org/onosproject/pcep/controller/impl/PcepClientControllerImpl.java