onos: org.onosproject.net.DefaultHost Class Reference
org.onosproject.net.DefaultHost Class Reference
A basic implementation of a Host.
Public Member Functions
DefaultHost (ProviderId providerId, HostId id, MacAddress mac, VlanId vlan, HostLocation location, Set< IpAddress > ips, Annotations...annotations)
Creates an end-station host using the supplied information.
HostId id ()
Host identification.
MacAddress mac ()
Returns the host MAC address.
Set< IpAddress > ipAddresses ()
Returns set of IP addresses currently bound to the host MAC address.
HostLocation location ()
Returns the most recent host location where the host attaches to the network edge.
VlanId vlan ()
Returns the VLAN ID tied to this host.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractElement
AbstractElement ()
Public Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel ()
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractElement
AbstractElement (ProviderId providerId, ElementId id, Annotations...annotations)
Creates a network element attributed to the specified provider.
Protected Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel (ProviderId providerId, Annotations...annotations)
Creates a model entity attributed to the specified provider and optionally annotated.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Protected Attributes inherited from org.onosproject.net.AbstractElement
final ElementId id
Detailed Description
A basic implementation of a Host.
Definition at line 33 of file DefaultHost.java.
Constructor & Destructor Documentation
org.onosproject.net.DefaultHost.DefaultHost (ProviderId providerId, HostId id, MacAddress mac, VlanId vlan, HostLocation location, Set< IpAddress > ips, Annotations... annotations)
Creates an end-station host using the supplied information.
Parameters
providerId provider identity
id host identifier
mac host MAC address
vlan host VLAN identifier
location host location
ips host IP addresses
annotations optional key/value annotations
Definition at line 51 of file DefaultHost.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultHost.location(), org.onosproject.net.DefaultHost.mac(), and org.onosproject.net.DefaultHost.vlan().
Referenced by org.onosproject.net.DefaultHost.equals().
Member Function Documentation
boolean org.onosproject.net.DefaultHost.equals (Object obj)
Definition at line 92 of file DefaultHost.java.
References org.onosproject.net.DefaultHost.DefaultHost(), find-device.id, and org.onosproject.net.DefaultHost.ipAddresses().
int org.onosproject.net.DefaultHost.hashCode ()
Definition at line 87 of file DefaultHost.java.
References org.onosproject.net.DefaultHost.id(), org.onosproject.net.DefaultHost.location(), org.onosproject.net.DefaultHost.mac(), and org.onosproject.net.DefaultHost.vlan().
HostId org.onosproject.net.DefaultHost.id ()
Host identification.
Returns
host id
Implements org.onosproject.net.Host.
Definition at line 62 of file DefaultHost.java.
Referenced by org.onosproject.net.DefaultHost.hashCode(), and org.onosproject.net.DefaultHost.toString().
Set<IpAddress> org.onosproject.net.DefaultHost.ipAddresses ()
Returns set of IP addresses currently bound to the host MAC address.
Returns
set of IP addresses; empty if no IP address is bound
Implements org.onosproject.net.Host.
Definition at line 72 of file DefaultHost.java.
Referenced by org.onosproject.net.DefaultHost.equals().
HostLocation org.onosproject.net.DefaultHost.location ()
Returns the most recent host location where the host attaches to the network edge.
Returns
host location
Implements org.onosproject.net.Host.
Definition at line 77 of file DefaultHost.java.
Referenced by org.onosproject.net.DefaultHost.DefaultHost(), org.onosproject.net.DefaultHost.hashCode(), and org.onosproject.net.DefaultHost.toString().
MacAddress org.onosproject.net.DefaultHost.mac ()
Returns the host MAC address.
Returns
mac address
Implements org.onosproject.net.Host.
Definition at line 67 of file DefaultHost.java.
Referenced by org.onosproject.net.DefaultHost.DefaultHost(), org.onosproject.net.DefaultHost.hashCode(), and org.onosproject.net.DefaultHost.toString().
String org.onosproject.net.DefaultHost.toString ()
Definition at line 108 of file DefaultHost.java.
References org.onosproject.net.DefaultHost.id(), org.onosproject.net.DefaultHost.location(), org.onosproject.net.DefaultHost.mac(), and org.onosproject.net.DefaultHost.vlan().
VlanId org.onosproject.net.DefaultHost.vlan ()
Returns the VLAN ID tied to this host.
Returns
VLAN ID value
Implements org.onosproject.net.Host.
Definition at line 82 of file DefaultHost.java.
Referenced by org.onosproject.net.DefaultHost.DefaultHost(), org.onosproject.net.DefaultHost.hashCode(), and org.onosproject.net.DefaultHost.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/DefaultHost.java