onos: org.onosproject.provider.lldp.impl.LldpLinkProvider Class Reference
org.onosproject.provider.lldp.impl.LldpLinkProvider Class Reference
Provider which uses LLDP and BDDP packets to detect network infrastructure links.
Public Member Functions
LldpLinkProvider ()
Creates an OpenFlow link provider.
void activate (ComponentContext context)
void deactivate ()
void modified (ComponentContext context)
Public Member Functions inherited from org.onosproject.net.provider.AbstractProvider
ProviderId id ()
Returns the provider identifier.
Static Public Attributes
static final String NO_LLDP = "no-lldp"
static final String CONFIG_KEY = "suppression"
static final String FEATURE_NAME = "linkDiscovery"
Protected Member Functions
SuppressionRules rules ()
void updateRules (SuppressionRules newRules)
Protected Member Functions inherited from org.onosproject.net.provider.AbstractProvider
AbstractProvider (ProviderId id)
Creates a provider with the supplier identifier.
Protected Attributes
CoreService coreService
LinkProviderRegistry providerRegistry
DeviceService deviceService
LinkService linkService
PacketService packetService
MastershipService masterService
ComponentConfigService cfgService
ClusterService clusterService
NetworkConfigRegistry cfgRegistry
final Map< DeviceId,
LinkDiscovery > discoverers = new ConcurrentHashMap<>()
Detailed Description
Provider which uses LLDP and BDDP packets to detect network infrastructure links.
Definition at line 91 of file LldpLinkProvider.java.
Constructor & Destructor Documentation
org.onosproject.provider.lldp.impl.LldpLinkProvider.LldpLinkProvider ()
Creates an OpenFlow link provider.
Definition at line 215 of file LldpLinkProvider.java.
Member Function Documentation
void org.onosproject.provider.lldp.impl.LldpLinkProvider.activate (ComponentContext context)
Definition at line 220 of file LldpLinkProvider.java.
void org.onosproject.provider.lldp.impl.LldpLinkProvider.deactivate ()
Definition at line 242 of file LldpLinkProvider.java.
void org.onosproject.provider.lldp.impl.LldpLinkProvider.modified (ComponentContext context)
Definition at line 252 of file LldpLinkProvider.java.
SuppressionRules org.onosproject.provider.lldp.impl.LldpLinkProvider.rules () protected
Definition at line 494 of file LldpLinkProvider.java.
void org.onosproject.provider.lldp.impl.LldpLinkProvider.updateRules (SuppressionRules newRules) protected
Definition at line 498 of file LldpLinkProvider.java.
Member Data Documentation
NetworkConfigRegistry org.onosproject.provider.lldp.impl.LldpLinkProvider.cfgRegistry protected
Definition at line 129 of file LldpLinkProvider.java.
ComponentConfigService org.onosproject.provider.lldp.impl.LldpLinkProvider.cfgService protected
Definition at line 123 of file LldpLinkProvider.java.
ClusterService org.onosproject.provider.lldp.impl.LldpLinkProvider.clusterService protected
Definition at line 126 of file LldpLinkProvider.java.
final String org.onosproject.provider.lldp.impl.LldpLinkProvider.CONFIG_KEY = "suppression" static
Definition at line 181 of file LldpLinkProvider.java.
Referenced by org.onosproject.provider.lldp.impl.SuppressionConfigTest.setUp().
CoreService org.onosproject.provider.lldp.impl.LldpLinkProvider.coreService protected
Definition at line 105 of file LldpLinkProvider.java.
DeviceService org.onosproject.provider.lldp.impl.LldpLinkProvider.deviceService protected
Definition at line 111 of file LldpLinkProvider.java.
final Map<DeviceId, LinkDiscovery> org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers = new ConcurrentHashMap<>() protected
Definition at line 167 of file LldpLinkProvider.java.
Referenced by org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portDown(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portRemoved(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByDeviceAnnotationConfig(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByDeviceTypeConfig(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByParentDeviceIdBlacklist(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByPortBlacklist(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByPortConfig(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portUnknown(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portUp(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.switchAdd(), and org.onosproject.provider.lldp.impl.LldpLinkProviderTest.switchSuppressedByAnnotation().
final String org.onosproject.provider.lldp.impl.LldpLinkProvider.FEATURE_NAME = "linkDiscovery" static
Definition at line 182 of file LldpLinkProvider.java.
LinkService org.onosproject.provider.lldp.impl.LldpLinkProvider.linkService protected
Definition at line 114 of file LldpLinkProvider.java.
MastershipService org.onosproject.provider.lldp.impl.LldpLinkProvider.masterService protected
Definition at line 120 of file LldpLinkProvider.java.
final String org.onosproject.provider.lldp.impl.LldpLinkProvider.NO_LLDP = "no-lldp" static
Definition at line 100 of file LldpLinkProvider.java.
Referenced by org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByDeviceAnnotationConfig(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByPortConfig(), and org.onosproject.provider.lldp.impl.LldpLinkProviderTest.switchSuppressedByAnnotation().
PacketService org.onosproject.provider.lldp.impl.LldpLinkProvider.packetService protected
Definition at line 117 of file LldpLinkProvider.java.
LinkProviderRegistry org.onosproject.provider.lldp.impl.LldpLinkProvider.providerRegistry protected
Definition at line 108 of file LldpLinkProvider.java.
The documentation for this class was generated from the following file:
providers/lldp/src/main/java/org/onosproject/provider/lldp/impl/LldpLinkProvider.java