onos: org.onosproject.pcepio.types.StatefulLspDbVerTlv Class Reference
org.onosproject.pcepio.types.StatefulLspDbVerTlv Class Reference
Provides StatefulLspDbVerTlv.
Public Member Functions
StatefulLspDbVerTlv (final long rawValue)
Constructor to initialize rawValue.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
long getLong ()
Returns LSP State DB Version.
short getLength ()
Returns the Length of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static StatefulLspDbVerTlv of (final long raw)
Returns object of StatefulLspDbVerTlv.
static StatefulLspDbVerTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of StatefulLspDbVerTlv.
Static Public Attributes
static final short TYPE = 23
static final short LENGTH = 8
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(StatefulLspDbVerTlv.class)
Detailed Description
Provides StatefulLspDbVerTlv.
Definition at line 31 of file StatefulLspDbVerTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.StatefulLspDbVerTlv.StatefulLspDbVerTlv (final long rawValue)
Constructor to initialize rawValue.
Parameters
rawValue value
Definition at line 61 of file StatefulLspDbVerTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulLspDbVerTlv.equals(), and org.onosproject.pcepio.types.StatefulLspDbVerTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.StatefulLspDbVerTlv.equals (Object obj)
Definition at line 105 of file StatefulLspDbVerTlv.java.
References org.onosproject.pcepio.types.StatefulLspDbVerTlv.StatefulLspDbVerTlv().
short org.onosproject.pcepio.types.StatefulLspDbVerTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 90 of file StatefulLspDbVerTlv.java.
References org.onosproject.pcepio.types.StatefulLspDbVerTlv.LENGTH.
long org.onosproject.pcepio.types.StatefulLspDbVerTlv.getLong ()
Returns LSP State DB Version.
Returns
rawValue value
Definition at line 85 of file StatefulLspDbVerTlv.java.
short org.onosproject.pcepio.types.StatefulLspDbVerTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 95 of file StatefulLspDbVerTlv.java.
References org.onosproject.pcepio.types.StatefulLspDbVerTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.StatefulLspDbVerTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 76 of file StatefulLspDbVerTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.StatefulLspDbVerTlv.hashCode ()
Definition at line 100 of file StatefulLspDbVerTlv.java.
static StatefulLspDbVerTlv org.onosproject.pcepio.types.StatefulLspDbVerTlv.of (final long raw) static
Returns object of StatefulLspDbVerTlv.
Parameters
raw is LSP State DB Version
Returns
object of StatefulLspDbVerTlv
Definition at line 71 of file StatefulLspDbVerTlv.java.
References org.onosproject.pcepio.types.StatefulLspDbVerTlv.StatefulLspDbVerTlv().
static StatefulLspDbVerTlv org.onosproject.pcepio.types.StatefulLspDbVerTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of StatefulLspDbVerTlv.
Parameters
c input channel buffer
Returns
object of StatefulLspDbVerTlv
Definition at line 130 of file StatefulLspDbVerTlv.java.
String org.onosproject.pcepio.types.StatefulLspDbVerTlv.toString ()
Definition at line 135 of file StatefulLspDbVerTlv.java.
References org.onosproject.pcepio.types.StatefulLspDbVerTlv.LENGTH, and org.onosproject.pcepio.types.StatefulLspDbVerTlv.TYPE.
int org.onosproject.pcepio.types.StatefulLspDbVerTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 117 of file StatefulLspDbVerTlv.java.
References org.onosproject.pcepio.types.StatefulLspDbVerTlv.LENGTH, and org.onosproject.pcepio.types.StatefulLspDbVerTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.StatefulLspDbVerTlv.LENGTH = 8 static
Definition at line 53 of file StatefulLspDbVerTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulLspDbVerTlv.getLength(), org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.parseOptionalTlv(), org.onosproject.pcepio.types.StatefulLspDbVerTlv.toString(), and org.onosproject.pcepio.types.StatefulLspDbVerTlv.write().
final Logger org.onosproject.pcepio.types.StatefulLspDbVerTlv.log = LoggerFactory.getLogger(StatefulLspDbVerTlv.class) static protected
Definition at line 50 of file StatefulLspDbVerTlv.java.
final short org.onosproject.pcepio.types.StatefulLspDbVerTlv.TYPE = 23 static
Definition at line 52 of file StatefulLspDbVerTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulLspDbVerTlv.getType(), org.onosproject.pcepio.types.StatefulLspDbVerTlv.toString(), and org.onosproject.pcepio.types.StatefulLspDbVerTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/StatefulLspDbVerTlv.java