onos: org.onosproject.incubator.net.intf.impl.InterfaceManager Class Reference
org.onosproject.incubator.net.intf.impl.InterfaceManager Class Reference
Manages the inventory of interfaces in the system.
Public Member Functions
void activate ()
void deactivate ()
Set< Interface > getInterfaces ()
Returns the set of all interfaces in the system.
Set< Interface > getInterfacesByPort (ConnectPoint port)
Returns the set of interfaces configured on the given port.
Set< Interface > getInterfacesByIp (IpAddress ip)
Returns the set of interfaces with the given IP address.
Interface getMatchingInterface (IpAddress ip)
Returns an interface that has an address that is in the same subnet as the given IP address.
Set< Interface > getInterfacesByVlan (VlanId vlan)
Returns the set of interfaces in the given VLAN.
void add (Interface intf)
Adds a new interface configuration to the system.
void remove (ConnectPoint connectPoint, VlanId vlanId)
Removes an interface configuration from the system.
Protected Attributes
NetworkConfigService configService
Detailed Description
Manages the inventory of interfaces in the system.
Definition at line 54 of file InterfaceManager.java.
Member Function Documentation
void org.onosproject.incubator.net.intf.impl.InterfaceManager.activate ()
Definition at line 70 of file InterfaceManager.java.
void org.onosproject.incubator.net.intf.impl.InterfaceManager.add (Interface intf)
Adds a new interface configuration to the system.
Parameters
intf interface to add
Implements org.onosproject.incubator.net.intf.InterfaceAdminService.
Definition at line 159 of file InterfaceManager.java.
void org.onosproject.incubator.net.intf.impl.InterfaceManager.deactivate ()
Definition at line 86 of file InterfaceManager.java.
Set<Interface> org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfaces ()
Returns the set of all interfaces in the system.
Returns
set of interfaces
Implements org.onosproject.incubator.net.intf.InterfaceService.
Definition at line 93 of file InterfaceManager.java.
Referenced by org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testAddInterface(), org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testGetInterfaces(), org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testRemoveInterface(), and org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testUpdateInterface().
Set<Interface> org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfacesByIp (IpAddress ip)
Returns the set of interfaces with the given IP address.
Parameters
ip IP address
Returns
set of interfaces
Implements org.onosproject.incubator.net.intf.InterfaceService.
Definition at line 110 of file InterfaceManager.java.
Referenced by org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testGetInterfacesByIp().
Set<Interface> org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfacesByPort (ConnectPoint port)
Returns the set of interfaces configured on the given port.
Parameters
port connect point
Returns
set of interfaces
Implements org.onosproject.incubator.net.intf.InterfaceService.
Definition at line 101 of file InterfaceManager.java.
References obeliskHostCheck.port.
Referenced by org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testGetInterfacesByPort(), and org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testUpdateInterface().
Set<Interface> org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfacesByVlan (VlanId vlan)
Returns the set of interfaces in the given VLAN.
Parameters
vlan VLAN ID of the interfaces
Returns
set of interfaces
Implements org.onosproject.incubator.net.intf.InterfaceService.
Definition at line 138 of file InterfaceManager.java.
Referenced by org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testAddInterface(), and org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testGetInterfacesByVlan().
Interface org.onosproject.incubator.net.intf.impl.InterfaceManager.getMatchingInterface (IpAddress ip)
Returns an interface that has an address that is in the same subnet as the given IP address.
Parameters
ip IP address to find matching subnet interface for
Returns
interface
Implements org.onosproject.incubator.net.intf.InterfaceService.
Definition at line 121 of file InterfaceManager.java.
Referenced by org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testGetMatchingInterface().
void org.onosproject.incubator.net.intf.impl.InterfaceManager.remove (ConnectPoint connectPoint, VlanId vlanId)
Removes an interface configuration from the system.
Parameters
connectPoint connect point of the interface
vlanId vlan id
Implements org.onosproject.incubator.net.intf.InterfaceAdminService.
Definition at line 182 of file InterfaceManager.java.
References org.onosproject.incubator.net.config.basics.InterfaceConfig.getInterfaces().
Member Data Documentation
NetworkConfigService org.onosproject.incubator.net.intf.impl.InterfaceManager.configService protected
Definition at line 63 of file InterfaceManager.java.
The documentation for this class was generated from the following file:
incubator/net/src/main/java/org/onosproject/incubator/net/intf/impl/InterfaceManager.java