onos: org.onosproject.ovsdb.rfc.message.RowUpdate Class Reference
org.onosproject.ovsdb.rfc.message.RowUpdate Class Reference
A TableUpdate is an object that maps from the row's UUID to a RowUpdate object.
Public Member Functions
RowUpdate (UUID uuid, Row oldRow, Row newRow)
Constructs a RowUpdate object.
UUID uuid ()
Return uuid.
Row oldRow ()
Return oldRow.
Row newRow ()
Return newRow.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
A TableUpdate is an object that maps from the row's UUID to a RowUpdate object.
A RowUpdate is an object with the following members: "old": row, "new": row. Refer to RFC 7047 Section 4.1.6.
Definition at line 31 of file RowUpdate.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.message.RowUpdate.RowUpdate (UUID uuid, Row oldRow, Row newRow)
Constructs a RowUpdate object.
Parameters
uuid UUID
oldRow present for "delete" and "modify" updates
newRow present for "initial", "insert", and "modify" updates
Definition at line 42 of file RowUpdate.java.
References org.onosproject.ovsdb.rfc.message.RowUpdate.newRow(), org.onosproject.ovsdb.rfc.message.RowUpdate.oldRow(), and org.onosproject.ovsdb.rfc.message.RowUpdate.uuid().
Referenced by org.onosproject.ovsdb.rfc.message.RowUpdate.equals().
Member Function Documentation
boolean org.onosproject.ovsdb.rfc.message.RowUpdate.equals (Object obj)
Definition at line 79 of file RowUpdate.java.
References org.onosproject.ovsdb.rfc.message.RowUpdate.RowUpdate().
int org.onosproject.ovsdb.rfc.message.RowUpdate.hashCode ()
Definition at line 74 of file RowUpdate.java.
References org.onosproject.ovsdb.rfc.message.RowUpdate.newRow(), org.onosproject.ovsdb.rfc.message.RowUpdate.oldRow(), and org.onosproject.ovsdb.rfc.message.RowUpdate.uuid().
Row org.onosproject.ovsdb.rfc.message.RowUpdate.newRow ()
Return newRow.
Returns
newRow
Definition at line 69 of file RowUpdate.java.
Referenced by org.onosproject.ovsdb.rfc.message.RowUpdate.hashCode(), org.onosproject.ovsdb.rfc.message.RowUpdate.RowUpdate(), and org.onosproject.ovsdb.rfc.message.RowUpdate.toString().
Row org.onosproject.ovsdb.rfc.message.RowUpdate.oldRow ()
Return oldRow.
Returns
oldRow
Definition at line 61 of file RowUpdate.java.
Referenced by org.onosproject.ovsdb.rfc.message.RowUpdate.hashCode(), org.onosproject.ovsdb.rfc.message.RowUpdate.RowUpdate(), and org.onosproject.ovsdb.rfc.message.RowUpdate.toString().
String org.onosproject.ovsdb.rfc.message.RowUpdate.toString ()
Definition at line 93 of file RowUpdate.java.
References org.onosproject.ovsdb.rfc.message.RowUpdate.newRow(), org.onosproject.ovsdb.rfc.message.RowUpdate.oldRow(), and org.onosproject.ovsdb.rfc.message.RowUpdate.uuid().
UUID org.onosproject.ovsdb.rfc.message.RowUpdate.uuid ()
Return uuid.
Returns
uuid
Definition at line 53 of file RowUpdate.java.
Referenced by org.onosproject.ovsdb.rfc.message.RowUpdate.hashCode(), org.onosproject.ovsdb.rfc.message.RowUpdate.RowUpdate(), and org.onosproject.ovsdb.rfc.message.RowUpdate.toString().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/message/RowUpdate.java