onos: org.onosproject.net.flow.DefaultTableStatisticsEntry Class Reference
org.onosproject.net.flow.DefaultTableStatisticsEntry Class Reference
Default implementation of table statistics entry interface.
Public Member Functions
DefaultTableStatisticsEntry (DeviceId deviceId, int tableId, long activeFlowEntries, long packetsLookedupCount, long packetsMatchedCount)
Default table statistics constructor.
String toString ()
int tableId ()
Returns the table number.
long activeFlowEntries ()
Returns the number of active flow entries in this table.
long packetsLookedup ()
Returns the number of packets looked up in the table.
long packetsMatched ()
Returns the number of packets that successfully matched in the table.
DeviceId deviceId ()
Returns the device Id.
Detailed Description
Default implementation of table statistics entry interface.
Definition at line 24 of file DefaultTableStatisticsEntry.java.
Constructor & Destructor Documentation
org.onosproject.net.flow.DefaultTableStatisticsEntry.DefaultTableStatisticsEntry (DeviceId deviceId, int tableId, long activeFlowEntries, long packetsLookedupCount, long packetsMatchedCount)
Default table statistics constructor.
Parameters
deviceId device identifier
tableId table identifier
activeFlowEntries number of active flow entries in the table
packetsLookedupCount number of packets looked up in table
packetsMatchedCount number of packets that hit table
Definition at line 41 of file DefaultTableStatisticsEntry.java.
References org.onosproject.net.flow.DefaultTableStatisticsEntry.activeFlowEntries(), and org.onosproject.net.flow.DefaultTableStatisticsEntry.tableId().
Member Function Documentation
long org.onosproject.net.flow.DefaultTableStatisticsEntry.activeFlowEntries ()
Returns the number of active flow entries in this table.
Returns
the number of active flow entries
Implements org.onosproject.net.flow.TableStatisticsEntry.
Definition at line 71 of file DefaultTableStatisticsEntry.java.
Referenced by org.onosproject.net.flow.DefaultTableStatisticsEntry.DefaultTableStatisticsEntry().
DeviceId org.onosproject.net.flow.DefaultTableStatisticsEntry.deviceId ()
Returns the device Id.
Returns
device id
Implements org.onosproject.net.flow.TableStatisticsEntry.
Definition at line 86 of file DefaultTableStatisticsEntry.java.
Referenced by org.onosproject.net.flow.DefaultTableStatisticsEntry.toString().
long org.onosproject.net.flow.DefaultTableStatisticsEntry.packetsLookedup ()
Returns the number of packets looked up in the table.
Returns
the number of packets looked up in the table
Implements org.onosproject.net.flow.TableStatisticsEntry.
Definition at line 76 of file DefaultTableStatisticsEntry.java.
long org.onosproject.net.flow.DefaultTableStatisticsEntry.packetsMatched ()
Returns the number of packets that successfully matched in the table.
Returns
the number of packets that successfully matched in the table
Implements org.onosproject.net.flow.TableStatisticsEntry.
Definition at line 81 of file DefaultTableStatisticsEntry.java.
int org.onosproject.net.flow.DefaultTableStatisticsEntry.tableId ()
Returns the table number.
Returns
table number
Implements org.onosproject.net.flow.TableStatisticsEntry.
Definition at line 66 of file DefaultTableStatisticsEntry.java.
Referenced by org.onosproject.net.flow.DefaultTableStatisticsEntry.DefaultTableStatisticsEntry().
String org.onosproject.net.flow.DefaultTableStatisticsEntry.toString ()
Definition at line 54 of file DefaultTableStatisticsEntry.java.
References org.onosproject.net.flow.DefaultTableStatisticsEntry.deviceId().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/DefaultTableStatisticsEntry.java