onos: org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils Class Reference
org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils Class Reference
gRPC message conversion related utilities.
Static Public Member Functions
static MastershipRole translate (org.onosproject.grpc.Device.MastershipRole role)
Translates gRPC enum MastershipRole to ONOS enum.
static
org.onosproject.grpc.Device.MastershipRole translate (MastershipRole newRole)
Translates ONOS enum MastershipRole to gRPC enum.
static DeviceDescription translate (org.onosproject.grpc.Device.DeviceDescription deviceDescription)
Translates gRPC DeviceDescription to DeviceDescription.
static
org.onosproject.grpc.Device.DeviceDescription translate (DeviceDescription deviceDescription)
Translates DeviceDescription to gRPC DeviceDescription message.
static Device.Type translate (org.onosproject.grpc.Device.DeviceType type)
Translates gRPC DeviceType to Device.Type.
static DeviceType translate (Device.Type type)
Translates Type to gRPC DeviceType.
static PortDescription translate (org.onosproject.grpc.Port.PortDescription portDescription)
Translates gRPC PortDescription message to PortDescription.
static
org.onosproject.grpc.Port.PortDescription translate (PortDescription portDescription)
Translates PortDescription to gRPC PortDescription message.
static Port.Type translate (PortType type)
Translates gRPC PortType to Port.Type.
static PortType translate (Port.Type type)
Translates Port.Type to gRPC PortType.
static PortStatistics translate (org.onosproject.grpc.Port.PortStatistics portStatistics)
Translates gRPC PortStatistics message to PortStatistics.
static
org.onosproject.grpc.Port.PortStatistics translate (PortStatistics portStatistics)
Translates PortStatistics to gRPC PortStatistics message.
static Map< String, String > asMap (Annotations annotations)
Converts Annotations to Map of Strings.
static SparseAnnotations asAnnotations (Map< String, String > annotations)
Converts Map of Strings to SparseAnnotations.
Detailed Description
gRPC message conversion related utilities.
Definition at line 48 of file GrpcDeviceUtils.java.
Member Function Documentation
static SparseAnnotations org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.asAnnotations (Map< String, String > annotations) static
Converts Map of Strings to SparseAnnotations.
Parameters
annotations Map of annotation key and values
Returns
SparseAnnotations
Definition at line 367 of file GrpcDeviceUtils.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static Map<String, String> org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.asMap (Annotations annotations) static
Converts Annotations to Map of Strings.
Parameters
annotations Annotations
Returns
Map of annotation key and values
Definition at line 349 of file GrpcDeviceUtils.java.
References org.onosproject.net.Annotations.value().
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static MastershipRole org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (org.onosproject.grpc.Device.MastershipRole role) static
Translates gRPC enum MastershipRole to ONOS enum.
Parameters
role mastership role in gRPC enum
Returns
equivalent in ONOS enum
Definition at line 58 of file GrpcDeviceUtils.java.
References org.onosproject.net.MastershipRole.MASTER, org.onosproject.net.MastershipRole.NONE, and org.onosproject.net.MastershipRole.STANDBY.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static org.onosproject.grpc.Device.MastershipRole org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (MastershipRole newRole) static
Translates ONOS enum MastershipRole to gRPC enum.
Parameters
newRole ONOS' mastership role
Returns
equivalent in gRPC message enum
Definition at line 79 of file GrpcDeviceUtils.java.
static DeviceDescription org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (org.onosproject.grpc.Device.DeviceDescription deviceDescription) static
Translates gRPC DeviceDescription to DeviceDescription.
Parameters
deviceDescription gRPC message
Returns
DeviceDescription
Definition at line 98 of file GrpcDeviceUtils.java.
References org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.asAnnotations(), and org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static org.onosproject.grpc.Device.DeviceDescription org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (DeviceDescription deviceDescription) static
Translates DeviceDescription to gRPC DeviceDescription message.
Parameters
deviceDescription DeviceDescription
Returns
gRPC DeviceDescription message
Definition at line 118 of file GrpcDeviceUtils.java.
References org.onosproject.net.Description.annotations(), org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.asMap(), org.onosproject.net.device.DeviceDescription.deviceUri(), org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate(), and org.onosproject.net.device.DeviceDescription.type().
static Device.Type org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (org.onosproject.grpc.Device.DeviceType type) static
Translates gRPC DeviceType to Device.Type.
Parameters
type gRPC message
Returns
Device.Type
Definition at line 139 of file GrpcDeviceUtils.java.
static DeviceType org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (Device.Type type) static
Translates Type to gRPC DeviceType.
Parameters
type Type
Returns
gRPC message
Definition at line 183 of file GrpcDeviceUtils.java.
References org.onosproject.grpc.Device.DeviceType.BALANCER, org.onosproject.grpc.Device.DeviceType.CONTROLLER, org.onosproject.grpc.Device.DeviceType.FIBER_SWITCH, org.onosproject.grpc.Device.DeviceType.FIREWALL, org.onosproject.grpc.Device.DeviceType.IDS, org.onosproject.grpc.Device.DeviceType.IPS, org.onosproject.grpc.Device.DeviceType.MICROWAVE, org.onosproject.grpc.Device.DeviceType.OTHER, org.onosproject.grpc.Device.DeviceType.OTN, org.onosproject.grpc.Device.DeviceType.ROADM, org.onosproject.grpc.Device.DeviceType.ROADM_OTN, org.onosproject.grpc.Device.DeviceType.ROUTER, org.onosproject.grpc.Device.DeviceType.SWITCH, and org.onosproject.grpc.Device.DeviceType.VIRTUAL.
static PortDescription org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (org.onosproject.grpc.Port.PortDescription portDescription) static
Translates gRPC PortDescription message to PortDescription.
Parameters
portDescription gRPC message
Returns
PortDescription
Definition at line 226 of file GrpcDeviceUtils.java.
References org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.asAnnotations(), and org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static org.onosproject.grpc.Port.PortDescription org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (PortDescription portDescription) static
Translates PortDescription to gRPC PortDescription message.
Parameters
portDescription PortDescription
Returns
gRPC PortDescription message
Definition at line 242 of file GrpcDeviceUtils.java.
References org.onosproject.net.Description.annotations(), org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.asMap(), org.onosproject.net.device.PortDescription.portNumber(), org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate(), and org.onosproject.net.device.PortDescription.type().
static Port.Type org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (PortType type) static
Translates gRPC PortType to Port.Type.
Parameters
type gRPC message
Returns
Port.Type
Definition at line 259 of file GrpcDeviceUtils.java.
References org.onosproject.net.Device.Type.VIRTUAL.
static PortType org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (Port.Type type) static
Translates Port.Type to gRPC PortType.
Parameters
type Port.Type
Returns
gRPC message
Definition at line 289 of file GrpcDeviceUtils.java.
References org.onosproject.grpc.Port.PortType.COPPER, org.onosproject.grpc.Port.PortType.FIBER, org.onosproject.grpc.Port.PortType.OCH, org.onosproject.grpc.Port.PortType.ODUCLT, org.onosproject.grpc.Port.PortType.OMS, org.onosproject.grpc.Port.PortType.PACKET, and org.onosproject.grpc.Port.PortType.VIRTUAL.
static PortStatistics org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (org.onosproject.grpc.Port.PortStatistics portStatistics) static
Translates gRPC PortStatistics message to PortStatistics.
Parameters
portStatistics gRPC PortStatistics message
Returns
PortStatistics
Definition at line 318 of file GrpcDeviceUtils.java.
static org.onosproject.grpc.Port.PortStatistics org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate (PortStatistics portStatistics) static
Translates PortStatistics to gRPC PortStatistics message.
Parameters
portStatistics PortStatistics
Returns
gRPC PortStatistics message
Definition at line 333 of file GrpcDeviceUtils.java.
References org.onosproject.net.device.PortStatistics.packetsReceived(), org.onosproject.net.device.PortStatistics.packetsSent(), and org.onosproject.net.device.PortStatistics.port().
The documentation for this class was generated from the following file:
incubator/rpc-grpc/src/main/java/org/onosproject/incubator/rpc/grpc/GrpcDeviceUtils.java