onos: org.onosproject.net.packet.DefaultInboundPacket Class Reference
org.onosproject.net.packet.DefaultInboundPacket Class Reference
Default implementation of an immutable inbound packet.
Public Member Functions
DefaultInboundPacket (ConnectPoint receivedFrom, Ethernet parsed, ByteBuffer unparsed)
Creates an immutable inbound packet.
ConnectPoint receivedFrom ()
Returns the device and port from where the packet was received.
Ethernet parsed ()
Returns the parsed form of the packet.
ByteBuffer unparsed ()
Unparsed packet data.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of an immutable inbound packet.
Definition at line 29 of file DefaultInboundPacket.java.
Constructor & Destructor Documentation
org.onosproject.net.packet.DefaultInboundPacket.DefaultInboundPacket (ConnectPoint receivedFrom, Ethernet parsed, ByteBuffer unparsed)
Creates an immutable inbound packet.
Parameters
receivedFrom connection point where received
parsed parsed ethernet frame
unparsed unparsed raw bytes
Definition at line 42 of file DefaultInboundPacket.java.
References org.onosproject.net.packet.DefaultInboundPacket.parsed(), org.onosproject.net.packet.DefaultInboundPacket.receivedFrom(), and org.onosproject.net.packet.DefaultInboundPacket.unparsed().
Referenced by org.onosproject.net.packet.DefaultInboundPacket.equals().
Member Function Documentation
boolean org.onosproject.net.packet.DefaultInboundPacket.equals (Object obj)
Definition at line 71 of file DefaultInboundPacket.java.
References org.onosproject.net.packet.DefaultInboundPacket.DefaultInboundPacket(), and org.onosproject.net.packet.DefaultInboundPacket.equals().
Referenced by org.onosproject.net.packet.DefaultInboundPacket.equals().
int org.onosproject.net.packet.DefaultInboundPacket.hashCode ()
Definition at line 66 of file DefaultInboundPacket.java.
References org.onosproject.net.packet.DefaultInboundPacket.parsed(), org.onosproject.net.packet.DefaultInboundPacket.receivedFrom(), and org.onosproject.net.packet.DefaultInboundPacket.unparsed().
Ethernet org.onosproject.net.packet.DefaultInboundPacket.parsed ()
Returns the parsed form of the packet.
Returns
parsed Ethernet frame; null if the packet is not an Ethernet frame or one for which there is no parser
Implements org.onosproject.net.packet.InboundPacket.
Definition at line 55 of file DefaultInboundPacket.java.
Referenced by org.onosproject.net.packet.DefaultInboundPacket.DefaultInboundPacket(), org.onosproject.net.packet.DefaultInboundPacket.hashCode(), and org.onosproject.net.packet.DefaultInboundPacket.toString().
ConnectPoint org.onosproject.net.packet.DefaultInboundPacket.receivedFrom ()
Returns the device and port from where the packet was received.
Returns
connection point where received
Implements org.onosproject.net.packet.InboundPacket.
Definition at line 50 of file DefaultInboundPacket.java.
Referenced by org.onosproject.net.packet.DefaultInboundPacket.DefaultInboundPacket(), org.onosproject.net.packet.DefaultInboundPacket.hashCode(), and org.onosproject.net.packet.DefaultInboundPacket.toString().
String org.onosproject.net.packet.DefaultInboundPacket.toString ()
Definition at line 85 of file DefaultInboundPacket.java.
References org.onosproject.net.packet.DefaultInboundPacket.parsed(), and org.onosproject.net.packet.DefaultInboundPacket.receivedFrom().
ByteBuffer org.onosproject.net.packet.DefaultInboundPacket.unparsed ()
Unparsed packet data.
Returns
raw packet bytes
Implements org.onosproject.net.packet.InboundPacket.
Definition at line 60 of file DefaultInboundPacket.java.
Referenced by org.onosproject.net.packet.DefaultInboundPacket.DefaultInboundPacket(), and org.onosproject.net.packet.DefaultInboundPacket.hashCode().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/packet/DefaultInboundPacket.java