onos: org.onosproject.pcepio.types.BGPLSidentifierTlv Class Reference
org.onosproject.pcepio.types.BGPLSidentifierTlv Class Reference
Provides BGP LS identifier which contains opaque value (32 Bit ID).
Public Member Functions
BGPLSidentifierTlv (int rawValue)
constructor to initialize rawValue.
int getInt ()
Returns opaque value.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static BGPLSidentifierTlv of (final int raw)
Returns newly created BGPLSidentifierTlv object.
static BGPLSidentifierTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of BGPLSidentifierTlv.
Static Public Attributes
static final short TYPE = 17
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(BGPLSidentifierTlv.class)
Detailed Description
Provides BGP LS identifier which contains opaque value (32 Bit ID).
Definition at line 30 of file BGPLSidentifierTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.BGPLSidentifierTlv.BGPLSidentifierTlv (int rawValue)
constructor to initialize rawValue.
Parameters
rawValue BGP LS identifier Tlv
Definition at line 54 of file BGPLSidentifierTlv.java.
Referenced by org.onosproject.pcepio.types.BGPLSidentifierTlv.equals(), and org.onosproject.pcepio.types.BGPLSidentifierTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.BGPLSidentifierTlv.equals (Object obj)
Definition at line 98 of file BGPLSidentifierTlv.java.
References org.onosproject.pcepio.types.BGPLSidentifierTlv.BGPLSidentifierTlv().
int org.onosproject.pcepio.types.BGPLSidentifierTlv.getInt ()
Returns opaque value.
Returns
rawValue opaque value
Definition at line 73 of file BGPLSidentifierTlv.java.
short org.onosproject.pcepio.types.BGPLSidentifierTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 88 of file BGPLSidentifierTlv.java.
References org.onosproject.pcepio.types.BGPLSidentifierTlv.LENGTH.
short org.onosproject.pcepio.types.BGPLSidentifierTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 83 of file BGPLSidentifierTlv.java.
References org.onosproject.pcepio.types.BGPLSidentifierTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.BGPLSidentifierTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 78 of file BGPLSidentifierTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.BGPLSidentifierTlv.hashCode ()
Definition at line 93 of file BGPLSidentifierTlv.java.
static BGPLSidentifierTlv org.onosproject.pcepio.types.BGPLSidentifierTlv.of (final int raw) static
Returns newly created BGPLSidentifierTlv object.
Parameters
raw value
Returns
object of BGPLSidentifierTlv
Definition at line 64 of file BGPLSidentifierTlv.java.
References org.onosproject.pcepio.types.BGPLSidentifierTlv.BGPLSidentifierTlv().
static BGPLSidentifierTlv org.onosproject.pcepio.types.BGPLSidentifierTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of BGPLSidentifierTlv.
Parameters
c input channel buffer
Returns
object of BGP LS identifier Tlv
Definition at line 124 of file BGPLSidentifierTlv.java.
String org.onosproject.pcepio.types.BGPLSidentifierTlv.toString ()
Definition at line 129 of file BGPLSidentifierTlv.java.
References org.onosproject.pcepio.types.BGPLSidentifierTlv.LENGTH, and org.onosproject.pcepio.types.BGPLSidentifierTlv.TYPE.
int org.onosproject.pcepio.types.BGPLSidentifierTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 110 of file BGPLSidentifierTlv.java.
References org.onosproject.pcepio.types.BGPLSidentifierTlv.LENGTH, and org.onosproject.pcepio.types.BGPLSidentifierTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.BGPLSidentifierTlv.LENGTH = 4 static
Definition at line 45 of file BGPLSidentifierTlv.java.
Referenced by org.onosproject.pcepio.types.BGPLSidentifierTlv.getLength(), org.onosproject.pcepio.types.BGPLSidentifierTlv.toString(), and org.onosproject.pcepio.types.BGPLSidentifierTlv.write().
final Logger org.onosproject.pcepio.types.BGPLSidentifierTlv.log = LoggerFactory.getLogger(BGPLSidentifierTlv.class) static protected
Definition at line 42 of file BGPLSidentifierTlv.java.
final short org.onosproject.pcepio.types.BGPLSidentifierTlv.TYPE = 17 static
Definition at line 44 of file BGPLSidentifierTlv.java.
Referenced by org.onosproject.pcepio.types.BGPLSidentifierTlv.getType(), org.onosproject.pcepio.types.BGPLSidentifierTlv.toString(), and org.onosproject.pcepio.types.BGPLSidentifierTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/BGPLSidentifierTlv.java