onos: org.onosproject.store.service.AtomicValueEvent< V > Class Reference
org.onosproject.store.service.AtomicValueEvent< V > Class Reference
Representation of a AtomicValue update notification.
Classes
enum Type
AtomicValueEvent type.
Public Member Functions
AtomicValueEvent (String name, Type type, V value)
Creates a new event object.
String name ()
Returns the AtomicValue name.
Type type ()
Returns the type of the event.
V value ()
Returns the new updated value.
boolean equals (Object o)
int hashCode ()
String toString ()
Detailed Description
Representation of a AtomicValue update notification.
Parameters
<V> atomic value type
Definition at line 27 of file AtomicValueEvent.java.
Constructor & Destructor Documentation
org.onosproject.store.service.AtomicValueEvent< V >.AtomicValueEvent (String name, Type type, V value)
Creates a new event object.
Parameters
name AtomicValue name
type the type of the event
value the new value
Definition at line 51 of file AtomicValueEvent.java.
References create-flow.name.
Member Function Documentation
boolean org.onosproject.store.service.AtomicValueEvent< V >.equals (Object o)
Definition at line 85 of file AtomicValueEvent.java.
References create-flow.name.
int org.onosproject.store.service.AtomicValueEvent< V >.hashCode ()
Definition at line 97 of file AtomicValueEvent.java.
References create-flow.name.
String org.onosproject.store.service.AtomicValueEvent< V >.name ()
Returns the AtomicValue name.
Returns
name of atomic value
Definition at line 62 of file AtomicValueEvent.java.
References create-flow.name.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.store.service.AtomicValueEvent< V >.toString ()
Definition at line 102 of file AtomicValueEvent.java.
References create-flow.name.
Type org.onosproject.store.service.AtomicValueEvent< V >.type ()
Returns the type of the event.
Returns
the type of the event
Definition at line 71 of file AtomicValueEvent.java.
V org.onosproject.store.service.AtomicValueEvent< V >.value ()
Returns the new updated value.
Returns
the value
Definition at line 80 of file AtomicValueEvent.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/store/service/AtomicValueEvent.java