onos: org.onosproject.net.intent.Key Class Reference
org.onosproject.net.intent.Key Class Reference abstract
Key class for Intents.
Public Member Functions
long hash ()
int hashCode ()
abstract boolean equals (Object obj)
Static Public Member Functions
static Key of (String key, ApplicationId appId)
Creates a key based on the provided string.
static Key of (long key, ApplicationId appId)
Creates a key based on the provided long.
Protected Member Functions
Key (long hash)
Detailed Description
Key class for Intents.
Definition at line 31 of file Key.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.Key.Key (long hash) protected
Definition at line 37 of file Key.java.
References org.onosproject.net.intent.Key.hash().
Member Function Documentation
abstract boolean org.onosproject.net.intent.Key.equals (Object obj) pure virtual
long org.onosproject.net.intent.Key.hash ()
Definition at line 41 of file Key.java.
Referenced by org.onosproject.net.intent.Key.hashCode(), and org.onosproject.net.intent.Key.Key().
int org.onosproject.net.intent.Key.hashCode ()
Definition at line 46 of file Key.java.
References org.onosproject.net.intent.Key.hash().
static Key org.onosproject.net.intent.Key.of (String key, ApplicationId appId) static
Creates a key based on the provided string.
Note: Two keys with equal value, but different appId, are not equal.
Parameters
key the provided string
appId application id to associate with this key
Returns
the key for the string
Definition at line 63 of file Key.java.
Referenced by org.onosproject.rest.resources.IntentsWebResource.deleteIntentById(), org.onosproject.rest.resources.IntentsWebResource.getIntentById(), org.onosproject.net.intent.Intent.Intent(), org.onosproject.rest.IntentsResourceTest.testBadGet(), org.onosproject.rest.IntentsResourceTest.testBadRemove(), org.onosproject.rest.IntentsResourceTest.testIntentsSingle(), and org.onosproject.rest.IntentsResourceTest.testRemove().
static Key org.onosproject.net.intent.Key.of (long key, ApplicationId appId) static
Creates a key based on the provided long.
Note: Two keys with equal value, but different appId, are not equal. Also, "10" and 10L are different.
Parameters
key the provided long
appId application id to associate with this key
Returns
the key for the long
Definition at line 78 of file Key.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/Key.java