onos: org.onlab.packet.PacketUtils Class Reference
org.onlab.packet.PacketUtils Class Reference
Utilities for working with packet headers.
Static Public Member Functions
static void checkBufferLength (int byteLength, int offset, int length) throws DeserializationException
Check the length of the input buffer is appropriate given the offset and length parameters.
static void checkHeaderLength (int givenLength, int requiredLength) throws DeserializationException
Check that there are enough bytes in the buffer to read some number of bytes that we need to read a full header.
static void checkInput (byte[] data, int offset, int length, int requiredLength) throws DeserializationException
Check the input parameters are sane and there's enough bytes to read the required length.
Detailed Description
Utilities for working with packet headers.
Definition at line 24 of file PacketUtils.java.
Member Function Documentation
static void org.onlab.packet.PacketUtils.checkBufferLength (int byteLength, int offset, int length) throws DeserializationException static
Check the length of the input buffer is appropriate given the offset and length parameters.
Parameters
byteLength length of the input buffer array
offset offset given to begin reading bytes from
length length given to read up until
Exceptions
DeserializationException if the input parameters don't match up (i.e we can't read that many bytes from the buffer at the given offest)
Definition at line 39 of file PacketUtils.java.
References find-link-in-cluster.length.
Referenced by org.onlab.packet.PacketUtils.checkInput().
static void org.onlab.packet.PacketUtils.checkHeaderLength (int givenLength, int requiredLength) throws DeserializationException static
Check that there are enough bytes in the buffer to read some number of bytes that we need to read a full header.
Parameters
givenLength given size of the buffer
requiredLength number of bytes we need to read some header fully
Exceptions
DeserializationException if there aren't enough bytes
Definition at line 58 of file PacketUtils.java.
Referenced by org.onlab.packet.PacketUtils.checkInput().
static void org.onlab.packet.PacketUtils.checkInput (byte[] data, int offset, int length, int requiredLength) throws DeserializationException static
Check the input parameters are sane and there's enough bytes to read the required length.
Parameters
data input byte buffer
offset offset of the start of the header
length length given to deserialize the header
requiredLength length needed to deserialize header
Exceptions
DeserializationException if we're unable to deserialize the packet based on the input parameters
Definition at line 78 of file PacketUtils.java.
References org.onlab.packet.PacketUtils.checkBufferLength(), org.onlab.packet.PacketUtils.checkHeaderLength(), and find-link-in-cluster.length.
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/PacketUtils.java