onos: org.onosproject.incubator.net.domain.DomainIntentResource Class Reference
org.onosproject.incubator.net.domain.DomainIntentResource Class Reference
A variant of intent resource specialized for use on the intra-domain level.
Public Member Functions
DomainIntentResource (IntentPrimitive primitive, DomainTunnelId domainTunnelId, IntentDomainId domainId, ApplicationId appId, ConnectPoint ingress, ConnectPoint egress, Path path)
Constructor for a domain intent resource.
Path path ()
Returns the domain path associated with this resource at creation.
DomainTunnelId tunnelId ()
Returns the tunnel ID associated with this domain at creation.
IntentDomainId domainId ()
Returns the domain ID associated with this resource at creation.
Public Member Functions inherited from org.onosproject.incubator.net.domain.IntentResource
IntentResource (IntentPrimitive primitive, ApplicationId appId, ConnectPoint ingress, ConnectPoint egress)
IntentPrimitive primitive ()
Returns the intent primitive associated with this resource at creation.
ApplicationId appId ()
Returns the application ID associated with this resource at creation.
ConnectPoint ingress ()
Returns the ingress connect point associated with this resource at creation.
ConnectPoint egress ()
Returns the egress connect point associated with this resource at creation.
Detailed Description
A variant of intent resource specialized for use on the intra-domain level.
It contains a lower level path.
Definition at line 27 of file DomainIntentResource.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.domain.DomainIntentResource.DomainIntentResource (IntentPrimitive primitive, DomainTunnelId domainTunnelId, IntentDomainId domainId, ApplicationId appId, ConnectPoint ingress, ConnectPoint egress, Path path)
Constructor for a domain intent resource.
Parameters
primitive the primitive associated with this resource
domainTunnelId the id of this tunnel (used as a sorting mechanism)
domainId the ID of the intent domain containing this tunnel
appId the id of the application which created this tunnel
ingress the fist connect point associated with this tunnel (order is irrelevant as long as it is consistent with the path)
egress the second connect point associated with this tunnel (order is irrelevant as long as it is consistent with the path)
path the path followed through the domain
Definition at line 48 of file DomainIntentResource.java.
References org.onosproject.incubator.net.domain.DomainIntentResource.domainId(), and org.onosproject.incubator.net.domain.DomainIntentResource.path().
Member Function Documentation
IntentDomainId org.onosproject.incubator.net.domain.DomainIntentResource.domainId ()
Returns the domain ID associated with this resource at creation.
Returns
this resource's domain ID.
Definition at line 80 of file DomainIntentResource.java.
Referenced by org.onosproject.incubator.net.domain.DomainIntentResource.DomainIntentResource().
Path org.onosproject.incubator.net.domain.DomainIntentResource.path ()
Returns the domain path associated with this resource at creation.
Returns
this resource's domain level path or if this resource backs a network tunnel then null.
Definition at line 62 of file DomainIntentResource.java.
Referenced by org.onosproject.incubator.net.domain.DomainIntentResource.DomainIntentResource().
DomainTunnelId org.onosproject.incubator.net.domain.DomainIntentResource.tunnelId ()
Returns the tunnel ID associated with this domain at creation.
Returns
this resource's tunnel ID.
Definition at line 71 of file DomainIntentResource.java.
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/domain/DomainIntentResource.java