onos: org.onosproject.ovsdb.rfc.notation.Row Class Reference
org.onosproject.ovsdb.rfc.notation.Row Class Reference
Row is the basic element of the OpenVswitch's table.
Public Member Functions
Row ()
Row constructor.
Row (String tableName, UUID uuid, Map< String, Column > columns)
Row constructor.
String tableName ()
Returns tableName.
void setTableName (String tableName)
Set tableName value.
UUID uuid ()
Returns uuid.
void setUuid (UUID uuid)
Sets uuid value.
Column getColumn (String columnName)
Returns Column by ColumnSchema.
Collection< Column > getColumns ()
Returns Collection of Column.
void addColumn (String columnName, Column data)
add Column.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Row is the basic element of the OpenVswitch's table.
Definition at line 30 of file Row.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.notation.Row.Row ()
Row constructor.
Definition at line 38 of file Row.java.
Referenced by org.onosproject.ovsdb.rfc.notation.Row.equals().
org.onosproject.ovsdb.rfc.notation.Row.Row (String tableName, UUID uuid, Map< String, Column > columns)
Row constructor.
Parameters
tableName table name
columns Map of Column entity
uuid UUID of the row
Definition at line 62 of file Row.java.
References org.onosproject.ovsdb.rfc.notation.Row.tableName(), and org.onosproject.ovsdb.rfc.notation.Row.uuid().
Member Function Documentation
void org.onosproject.ovsdb.rfc.notation.Row.addColumn (String columnName, Column data)
add Column.
Parameters
columnName column name
data Column entity
Definition at line 132 of file Row.java.
boolean org.onosproject.ovsdb.rfc.notation.Row.equals (Object obj)
Definition at line 142 of file Row.java.
References org.onosproject.ovsdb.rfc.notation.Row.Row().
Column org.onosproject.ovsdb.rfc.notation.Row.getColumn (String columnName)
Returns Column by ColumnSchema.
Parameters
columnName column name
Returns
Column
Definition at line 113 of file Row.java.
Referenced by org.onosproject.ovsdb.rfc.tableservice.AbstractOvsdbTableService.getDataHandler().
Collection<Column> org.onosproject.ovsdb.rfc.notation.Row.getColumns ()
Returns Collection of Column.
Returns
Collection of Column
Definition at line 122 of file Row.java.
int org.onosproject.ovsdb.rfc.notation.Row.hashCode ()
Definition at line 137 of file Row.java.
References org.onosproject.ovsdb.rfc.notation.Row.tableName().
void org.onosproject.ovsdb.rfc.notation.Row.setTableName (String tableName)
Set tableName value.
Parameters
tableName table name
Definition at line 85 of file Row.java.
References org.onosproject.ovsdb.rfc.notation.Row.tableName().
void org.onosproject.ovsdb.rfc.notation.Row.setUuid (UUID uuid)
Sets uuid value.
Parameters
uuid new uuid
Definition at line 103 of file Row.java.
References org.onosproject.ovsdb.rfc.notation.Row.uuid().
String org.onosproject.ovsdb.rfc.notation.Row.tableName ()
Returns tableName.
Returns
tableName
Definition at line 76 of file Row.java.
Referenced by org.onosproject.ovsdb.rfc.notation.Row.hashCode(), org.onosproject.ovsdb.rfc.notation.Row.Row(), org.onosproject.ovsdb.rfc.notation.Row.setTableName(), and org.onosproject.ovsdb.rfc.notation.Row.toString().
String org.onosproject.ovsdb.rfc.notation.Row.toString ()
Definition at line 155 of file Row.java.
References org.onosproject.ovsdb.rfc.notation.Row.tableName().
UUID org.onosproject.ovsdb.rfc.notation.Row.uuid ()
Returns uuid.
Returns
uuid
Definition at line 94 of file Row.java.
Referenced by org.onosproject.ovsdb.rfc.notation.Row.Row(), and org.onosproject.ovsdb.rfc.notation.Row.setUuid().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/notation/Row.java