onos: org.onosproject.vtnweb.web.RouterCodec Class Reference
org.onosproject.vtnweb.web.RouterCodec Class Reference
Router JSON codec.
Public Member Functions
ObjectNode encode (Router router, CodecContext context)
ObjectNode extracFields (Router router, CodecContext context, List< String > fields)
Detailed Description
Router JSON codec.
Definition at line 32 of file RouterCodec.java.
Member Function Documentation
ObjectNode org.onosproject.vtnweb.web.RouterCodec.encode (Router router, CodecContext context)
Definition at line 34 of file RouterCodec.java.
References org.onosproject.vtnrsc.Router.adminStateUp(), org.onosproject.vtnrsc.Router.routes(), org.onosproject.vtnrsc.Router.status(), and org.onosproject.vtnrsc.Router.tenantId().
ObjectNode org.onosproject.vtnweb.web.RouterCodec.extracFields (Router router, CodecContext context, List< String > fields)
Definition at line 55 of file RouterCodec.java.
The documentation for this class was generated from the following file:
apps/vtn/vtnweb/src/main/java/org/onosproject/vtnweb/web/RouterCodec.java