onos: org.onosproject.pcep.controller.impl.PcepClientImpl Class Reference
org.onosproject.pcep.controller.impl.PcepClientImpl Class Reference
An abstract representation of an OpenFlow switch.
Public Member Functions
void init (PccId pccId, PcepVersion pcepVersion, PcepPacketStats pktStats)
Initializes the behavior.
final void disconnectClient ()
Disconnects the pcc by closing the TCP connection.
final void sendMessage (PcepMessage m)
Writes the message to the driver.
final void sendMessage (List< PcepMessage > msgs)
Writes the PcepMessage list to the driver.
final boolean isConnected ()
Checks if the pcc is still connected.
final void setConnected (boolean connected)
Sets whether the pcc is connected.
final void setChannel (Channel channel)
Sets the associated Netty channel for this pcc.
String channelId ()
Identifies the channel used to communicate with the pcc.
final PccId getPccId ()
Gets the ipAddress of the client.
final String getStringId ()
Gets a string version of the ID for this pcc.
final void setPcVersion (PcepVersion pcepVersion)
Sets the PCEP version for this pcc.
void setPcKeepAliveTime (byte keepAliveTime)
Sets the keep alive time for this pcc.
void setPcDeadTime (byte deadTime)
Sets the dead time for this pcc.
void setPcSessionId (byte sessionId)
Sets the session id for this pcc.
void setIsSyncComplete (boolean value)
To set the status of state synchronization.
boolean isSyncComplete ()
Indicates the state synchronization status of this pcc.
final void handleMessage (PcepMessage m)
Handle a message from the pcc.
final boolean connectClient ()
Announce to the Pcep agent that this pcc client has connected.
final void removeConnectedClient ()
Remove this pcc client from the Pcep agent.
PcepFactory factory ()
Provides the factory for this PCEP version.
boolean isHandshakeComplete ()
Checks whether the handshake is complete.
final void setAgent (PcepAgent ag)
Sets the Pcep agent to be used.
boolean isOptical ()
Indicates if this pcc is optical.
String toString ()
Protected Attributes
final Logger log = LoggerFactory.getLogger(PcepClientImpl.class)
String channelId
boolean startDriverHandshakeCalled = false
boolean isHandShakeComplete = false
boolean isSyncComplete = false
Detailed Description
An abstract representation of an OpenFlow switch.
Can be extended by others to serve as a base for their vendor specific representation of a switch.
Definition at line 44 of file PcepClientImpl.java.
Member Function Documentation
String org.onosproject.pcep.controller.impl.PcepClientImpl.channelId ()
Identifies the channel used to communicate with the pcc.
Returns
string representation of the connection to the client
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 131 of file PcepClientImpl.java.
Referenced by org.onosproject.pcep.controller.impl.PcepClientImpl.setChannel(), and org.onosproject.pcep.controller.impl.PcepClientImpl.toString().
final boolean org.onosproject.pcep.controller.impl.PcepClientImpl.connectClient ()
Announce to the Pcep agent that this pcc client has connected.
Returns
true if successful, false if duplicate switch.
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 182 of file PcepClientImpl.java.
final void org.onosproject.pcep.controller.impl.PcepClientImpl.disconnectClient ()
Disconnects the pcc by closing the TCP connection.
Results in a call to the channel handler's channelDisconnected method for cleanup.
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 74 of file PcepClientImpl.java.
PcepFactory org.onosproject.pcep.controller.impl.PcepClientImpl.factory ()
Provides the factory for this PCEP version.
Returns
PCEP version specific factory.
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 192 of file PcepClientImpl.java.
final PccId org.onosproject.pcep.controller.impl.PcepClientImpl.getPccId ()
Gets the ipAddress of the client.
Returns
the client pccId in IPAddress format
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 136 of file PcepClientImpl.java.
Referenced by org.onosproject.pcep.controller.impl.PcepClientImpl.toString().
final String org.onosproject.pcep.controller.impl.PcepClientImpl.getStringId ()
Gets a string version of the ID for this pcc.
Returns
string version of the ID
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 141 of file PcepClientImpl.java.
final void org.onosproject.pcep.controller.impl.PcepClientImpl.handleMessage (PcepMessage fromClient)
Handle a message from the pcc.
Parameters
fromClient the message to handle
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 176 of file PcepClientImpl.java.
void org.onosproject.pcep.controller.impl.PcepClientImpl.init (PccId pccId, PcepVersion pcepVersion, PcepPacketStats pktStats)
Initializes the behavior.
Parameters
pccId id of pcc
pcepVersion Pcep version
pktStats Pcep Packet Stats
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 67 of file PcepClientImpl.java.
final boolean org.onosproject.pcep.controller.impl.PcepClientImpl.isConnected ()
Checks if the pcc is still connected.
Returns
true if client is connected, false otherwise
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 106 of file PcepClientImpl.java.
boolean org.onosproject.pcep.controller.impl.PcepClientImpl.isHandshakeComplete ()
Checks whether the handshake is complete.
Returns
true is finished, false if not.
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 197 of file PcepClientImpl.java.
References org.onosproject.pcep.controller.impl.PcepClientImpl.isHandShakeComplete.
boolean org.onosproject.pcep.controller.impl.PcepClientImpl.isOptical ()
Indicates if this pcc is optical.
Returns
true if optical
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 209 of file PcepClientImpl.java.
boolean org.onosproject.pcep.controller.impl.PcepClientImpl.isSyncComplete ()
Indicates the state synchronization status of this pcc.
Returns
true/false if the synchronization is completed/not completed
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 171 of file PcepClientImpl.java.
final void org.onosproject.pcep.controller.impl.PcepClientImpl.removeConnectedClient ()
Remove this pcc client from the Pcep agent.
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 187 of file PcepClientImpl.java.
final void org.onosproject.pcep.controller.impl.PcepClientImpl.sendMessage (PcepMessage msg)
Writes the message to the driver.
Parameters
msg the message to write
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 79 of file PcepClientImpl.java.
final void org.onosproject.pcep.controller.impl.PcepClientImpl.sendMessage (List< PcepMessage > msgs)
Writes the PcepMessage list to the driver.
Parameters
msgs the messages to be written
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 93 of file PcepClientImpl.java.
final void org.onosproject.pcep.controller.impl.PcepClientImpl.setAgent (PcepAgent agent)
Sets the Pcep agent to be used.
This method can only be called once.
Parameters
agent the agent to set.
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 202 of file PcepClientImpl.java.
final void org.onosproject.pcep.controller.impl.PcepClientImpl.setChannel (Channel channel)
Sets the associated Netty channel for this pcc.
Parameters
channel the Netty channel
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 116 of file PcepClientImpl.java.
References org.onosproject.pcep.controller.impl.PcepClientImpl.channelId(), and org.onlab.packet.IpAddress.isIp4().
final void org.onosproject.pcep.controller.impl.PcepClientImpl.setConnected (boolean connected)
Sets whether the pcc is connected.
Parameters
connected whether the pcc is connected
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 111 of file PcepClientImpl.java.
void org.onosproject.pcep.controller.impl.PcepClientImpl.setIsSyncComplete (boolean value)
To set the status of state synchronization.
Parameters
value to set the synchronization status
Implements org.onosproject.pcep.controller.PcepClient.
Definition at line 166 of file PcepClientImpl.java.
void org.onosproject.pcep.controller.impl.PcepClientImpl.setPcDeadTime (byte deadTime)
Sets the dead time for this pcc.
Parameters
deadTime the dead timer value to set.
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 156 of file PcepClientImpl.java.
void org.onosproject.pcep.controller.impl.PcepClientImpl.setPcKeepAliveTime (byte keepAliveTime)
Sets the keep alive time for this pcc.
Parameters
keepAliveTime the keep alive time to set.
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 151 of file PcepClientImpl.java.
void org.onosproject.pcep.controller.impl.PcepClientImpl.setPcSessionId (byte sessionId)
Sets the session id for this pcc.
Parameters
sessionId the session id value to set.
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 161 of file PcepClientImpl.java.
final void org.onosproject.pcep.controller.impl.PcepClientImpl.setPcVersion (PcepVersion pcepVersion)
Sets the PCEP version for this pcc.
Parameters
pcepVersion the version to set.
Implements org.onosproject.pcep.controller.driver.PcepClientDriver.
Definition at line 146 of file PcepClientImpl.java.
String org.onosproject.pcep.controller.impl.PcepClientImpl.toString ()
Definition at line 214 of file PcepClientImpl.java.
References org.onosproject.pcep.controller.impl.PcepClientImpl.channelId(), and org.onosproject.pcep.controller.impl.PcepClientImpl.getPccId().
Member Data Documentation
String org.onosproject.pcep.controller.impl.PcepClientImpl.channelId protected
Definition at line 51 of file PcepClientImpl.java.
boolean org.onosproject.pcep.controller.impl.PcepClientImpl.isHandShakeComplete = false protected
Definition at line 55 of file PcepClientImpl.java.
Referenced by org.onosproject.pcep.controller.impl.PcepClientImpl.isHandshakeComplete().
boolean org.onosproject.pcep.controller.impl.PcepClientImpl.isSyncComplete = false protected
Definition at line 56 of file PcepClientImpl.java.
final Logger org.onosproject.pcep.controller.impl.PcepClientImpl.log = LoggerFactory.getLogger(PcepClientImpl.class) protected
Definition at line 46 of file PcepClientImpl.java.
boolean org.onosproject.pcep.controller.impl.PcepClientImpl.startDriverHandshakeCalled = false protected
Definition at line 54 of file PcepClientImpl.java.
The documentation for this class was generated from the following file:
protocols/pcep/ctl/src/main/java/org/onosproject/pcep/controller/impl/PcepClientImpl.java