onos: org.onosproject.net.meter.DefaultMeterRequest Class Reference
org.onosproject.net.meter.DefaultMeterRequest Class Reference
A default implementation of a meter.
Classes
class Builder
Public Member Functions
DeviceId deviceId ()
The target device for this meter.
ApplicationId appId ()
The id of the application which created this meter.
Meter.Unit unit ()
The unit used within this meter.
boolean isBurst ()
Signals whether this meter applies to bursts only.
Collection< Band > bands ()
The collection of bands to apply on the dataplane.
Optional< MeterContext > context ()
Returns the callback context for this meter.
String toString ()
Static Public Member Functions
static Builder builder ()
Detailed Description
A default implementation of a meter.
Definition at line 32 of file DefaultMeterRequest.java.
Member Function Documentation
ApplicationId org.onosproject.net.meter.DefaultMeterRequest.appId ()
The id of the application which created this meter.
Returns
an application id
Implements org.onosproject.net.meter.MeterRequest.
Definition at line 64 of file DefaultMeterRequest.java.
Collection<Band> org.onosproject.net.meter.DefaultMeterRequest.bands ()
The collection of bands to apply on the dataplane.
Returns
a collection of bands.
Implements org.onosproject.net.meter.MeterRequest.
Definition at line 79 of file DefaultMeterRequest.java.
static Builder org.onosproject.net.meter.DefaultMeterRequest.builder () static
Definition at line 90 of file DefaultMeterRequest.java.
Optional<MeterContext> org.onosproject.net.meter.DefaultMeterRequest.context ()
Returns the callback context for this meter.
Returns
an optional meter context
Implements org.onosproject.net.meter.MeterRequest.
Definition at line 84 of file DefaultMeterRequest.java.
DeviceId org.onosproject.net.meter.DefaultMeterRequest.deviceId ()
The target device for this meter.
Returns
a device id
Implements org.onosproject.net.meter.MeterRequest.
Definition at line 58 of file DefaultMeterRequest.java.
Referenced by org.onosproject.net.meter.DefaultMeterRequest.toString().
boolean org.onosproject.net.meter.DefaultMeterRequest.isBurst ()
Signals whether this meter applies to bursts only.
Returns
a boolean
Implements org.onosproject.net.meter.MeterRequest.
Definition at line 74 of file DefaultMeterRequest.java.
String org.onosproject.net.meter.DefaultMeterRequest.toString ()
Definition at line 95 of file DefaultMeterRequest.java.
References org.onosproject.net.meter.DefaultMeterRequest.deviceId(), org.onosproject.core.ApplicationId.name(), and org.onosproject.net.meter.DefaultMeterRequest.unit().
Meter.Unit org.onosproject.net.meter.DefaultMeterRequest.unit ()
The unit used within this meter.
Returns
the unit
Implements org.onosproject.net.meter.MeterRequest.
Definition at line 69 of file DefaultMeterRequest.java.
Referenced by org.onosproject.net.meter.DefaultMeterRequest.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/meter/DefaultMeterRequest.java