onos: org.onosproject.vtnrsc.DefaultTenantNetwork Class Reference
org.onosproject.vtnrsc.DefaultTenantNetwork Class Reference
Default implementation of TenantNetwork interface.
Public Member Functions
DefaultTenantNetwork (TenantNetworkId id, String name, boolean adminStateUp, State state, boolean shared, TenantId tenantId, boolean routerExternal, Type type, PhysicalNetwork physicalNetwork, SegmentationId segmentationId)
Creates a neutronNetwork element attributed to the specified provider.
TenantNetworkId id ()
Returns the tenantNetwork identifier.
String name ()
Returns the tenantNetwork name.
boolean adminStateUp ()
Returns the administrative state of the tenantNetwork,which is up(true) or down(false).
State state ()
Returns the tenantNetwork state.
boolean shared ()
Indicates whether this tenantNetwork is shared across all tenants.
TenantId tenantId ()
Returns the UUID of the tenant that will own the tenantNetwork.
boolean routerExternal ()
Returns the routerExternal.Indicates whether this network is externally accessible.
Type type ()
Returns the tenantNetwork Type.
PhysicalNetwork physicalNetwork ()
Returns the tenantNetwork physical network.
SegmentationId segmentationId ()
Returns the tenantNetwork segmentation id.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of TenantNetwork interface.
Definition at line 25 of file DefaultTenantNetwork.java.
Constructor & Destructor Documentation
org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork (TenantNetworkId id, String name, boolean adminStateUp, State state, boolean shared, TenantId tenantId, boolean routerExternal, Type type, PhysicalNetwork physicalNetwork, SegmentationId segmentationId)
Creates a neutronNetwork element attributed to the specified provider.
Parameters
id network identifier
name the network name
adminStateUp administrative state of the network
state the network state
shared indicates whether this network is shared across all tenants, By default, only administrative user can change this value
tenantId tenant identifier
routerExternal network routerExternal
type the network type
physicalNetwork physicalNetwork identifier
segmentationId segmentation identifier
Definition at line 53 of file DefaultTenantNetwork.java.
References org.onosproject.vtnrsc.DefaultTenantNetwork.adminStateUp(), org.onosproject.vtnrsc.DefaultTenantNetwork.id(), org.onosproject.vtnrsc.DefaultTenantNetwork.name(), org.onosproject.vtnrsc.DefaultTenantNetwork.physicalNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.routerExternal(), org.onosproject.vtnrsc.DefaultTenantNetwork.segmentationId(), org.onosproject.vtnrsc.DefaultTenantNetwork.shared(), org.onosproject.vtnrsc.DefaultTenantNetwork.state(), org.onosproject.vtnrsc.DefaultTenantNetwork.tenantId(), and org.onosproject.vtnrsc.DefaultTenantNetwork.type().
Referenced by org.onosproject.vtnrsc.DefaultTenantNetwork.equals().
Member Function Documentation
boolean org.onosproject.vtnrsc.DefaultTenantNetwork.adminStateUp ()
Returns the administrative state of the tenantNetwork,which is up(true) or down(false).
Returns
true or false
Implements org.onosproject.vtnrsc.TenantNetwork.
Definition at line 82 of file DefaultTenantNetwork.java.
Referenced by org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode(), and org.onosproject.vtnrsc.DefaultTenantNetwork.toString().
boolean org.onosproject.vtnrsc.DefaultTenantNetwork.equals (Object obj)
Definition at line 129 of file DefaultTenantNetwork.java.
References org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), and find-device.id.
int org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode ()
Definition at line 122 of file DefaultTenantNetwork.java.
References org.onosproject.vtnrsc.DefaultTenantNetwork.adminStateUp(), org.onosproject.vtnrsc.DefaultTenantNetwork.id(), org.onosproject.vtnrsc.DefaultTenantNetwork.name(), org.onosproject.vtnrsc.DefaultTenantNetwork.physicalNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.routerExternal(), org.onosproject.vtnrsc.DefaultTenantNetwork.segmentationId(), org.onosproject.vtnrsc.DefaultTenantNetwork.shared(), org.onosproject.vtnrsc.DefaultTenantNetwork.state(), org.onosproject.vtnrsc.DefaultTenantNetwork.tenantId(), and org.onosproject.vtnrsc.DefaultTenantNetwork.type().
TenantNetworkId org.onosproject.vtnrsc.DefaultTenantNetwork.id ()
Returns the tenantNetwork identifier.
Returns
tenantNetwork identifier
Implements org.onosproject.vtnrsc.TenantNetwork.
Definition at line 72 of file DefaultTenantNetwork.java.
Referenced by org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode(), and org.onosproject.vtnrsc.DefaultTenantNetwork.toString().
String org.onosproject.vtnrsc.DefaultTenantNetwork.name ()
Returns the tenantNetwork name.
Returns
tenantNetwork name
Implements org.onosproject.vtnrsc.TenantNetwork.
Definition at line 77 of file DefaultTenantNetwork.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.vtnrsc.DefaultTenantNetwork.toString().
PhysicalNetwork org.onosproject.vtnrsc.DefaultTenantNetwork.physicalNetwork ()
Returns the tenantNetwork physical network.
Returns
tenantNetwork physical network
Implements org.onosproject.vtnrsc.TenantNetwork.
Definition at line 112 of file DefaultTenantNetwork.java.
Referenced by org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode(), and org.onosproject.vtnrsc.DefaultTenantNetwork.toString().
boolean org.onosproject.vtnrsc.DefaultTenantNetwork.routerExternal ()
Returns the routerExternal.Indicates whether this network is externally accessible.
Returns
true or false
Implements org.onosproject.vtnrsc.TenantNetwork.
Definition at line 102 of file DefaultTenantNetwork.java.
Referenced by org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode(), and org.onosproject.vtnrsc.DefaultTenantNetwork.toString().
SegmentationId org.onosproject.vtnrsc.DefaultTenantNetwork.segmentationId ()
Returns the tenantNetwork segmentation id.
Returns
tenantNetwork segmentation id
Implements org.onosproject.vtnrsc.TenantNetwork.
Definition at line 117 of file DefaultTenantNetwork.java.
Referenced by org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode(), and org.onosproject.vtnrsc.DefaultTenantNetwork.toString().
boolean org.onosproject.vtnrsc.DefaultTenantNetwork.shared ()
Indicates whether this tenantNetwork is shared across all tenants.
By default,only administrative user can change this value.
Returns
true or false
Implements org.onosproject.vtnrsc.TenantNetwork.
Definition at line 92 of file DefaultTenantNetwork.java.
Referenced by org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode(), and org.onosproject.vtnrsc.DefaultTenantNetwork.toString().
State org.onosproject.vtnrsc.DefaultTenantNetwork.state ()
Returns the tenantNetwork state.
Returns
tenant network state
Implements org.onosproject.vtnrsc.TenantNetwork.
Definition at line 87 of file DefaultTenantNetwork.java.
Referenced by org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode(), and org.onosproject.vtnrsc.DefaultTenantNetwork.toString().
TenantId org.onosproject.vtnrsc.DefaultTenantNetwork.tenantId ()
Returns the UUID of the tenant that will own the tenantNetwork.
This tenant can be different from the tenant that makes the create tenantNetwork request.
Returns
the tenant identifier
Implements org.onosproject.vtnrsc.TenantNetwork.
Definition at line 97 of file DefaultTenantNetwork.java.
Referenced by org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode(), and org.onosproject.vtnrsc.DefaultTenantNetwork.toString().
String org.onosproject.vtnrsc.DefaultTenantNetwork.toString ()
Definition at line 151 of file DefaultTenantNetwork.java.
References org.onosproject.vtnrsc.DefaultTenantNetwork.adminStateUp(), org.onosproject.vtnrsc.DefaultTenantNetwork.id(), org.onosproject.vtnrsc.DefaultTenantNetwork.name(), org.onosproject.vtnrsc.DefaultTenantNetwork.physicalNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.routerExternal(), org.onosproject.vtnrsc.DefaultTenantNetwork.segmentationId(), org.onosproject.vtnrsc.DefaultTenantNetwork.shared(), org.onosproject.vtnrsc.DefaultTenantNetwork.state(), org.onosproject.vtnrsc.DefaultTenantNetwork.tenantId(), and org.onosproject.vtnrsc.DefaultTenantNetwork.type().
Type org.onosproject.vtnrsc.DefaultTenantNetwork.type ()
Returns the tenantNetwork Type.
Returns
tenantNetwork Type
Implements org.onosproject.vtnrsc.TenantNetwork.
Definition at line 107 of file DefaultTenantNetwork.java.
Referenced by org.onosproject.vtnrsc.DefaultTenantNetwork.DefaultTenantNetwork(), org.onosproject.vtnrsc.DefaultTenantNetwork.hashCode(), and org.onosproject.vtnrsc.DefaultTenantNetwork.toString().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultTenantNetwork.java