onos: org.onosproject.vtnrsc.DefaultAllocationPool Class Reference
org.onosproject.vtnrsc.DefaultAllocationPool Class Reference
The continuous IP address range between the start address and the end address for the allocation pools.
Public Member Functions
DefaultAllocationPool (IpAddress startIp, IpAddress endIp)
Creates an AllocationPool by using the start IP address and the end IP address.
IpAddress startIp ()
The start address for the allocation pool.
IpAddress endIp ()
The end address for the allocation pool.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
The continuous IP address range between the start address and the end address for the allocation pools.
Definition at line 28 of file DefaultAllocationPool.java.
Constructor & Destructor Documentation
org.onosproject.vtnrsc.DefaultAllocationPool.DefaultAllocationPool (IpAddress startIp, IpAddress endIp)
Creates an AllocationPool by using the start IP address and the end IP address.
Parameters
startIp the start IP address of the allocation pool
endIp the end IP address of the allocation pool
Definition at line 40 of file DefaultAllocationPool.java.
References org.onosproject.vtnrsc.DefaultAllocationPool.endIp(), and org.onosproject.vtnrsc.DefaultAllocationPool.startIp().
Referenced by org.onosproject.vtnrsc.DefaultAllocationPool.equals().
Member Function Documentation
IpAddress org.onosproject.vtnrsc.DefaultAllocationPool.endIp ()
The end address for the allocation pool.
Returns
endIp
Implements org.onosproject.vtnrsc.AllocationPool.
Definition at line 53 of file DefaultAllocationPool.java.
Referenced by org.onosproject.vtnrsc.DefaultAllocationPool.DefaultAllocationPool(), org.onosproject.vtnrsc.DefaultAllocationPool.hashCode(), and org.onosproject.vtnrsc.DefaultAllocationPool.toString().
boolean org.onosproject.vtnrsc.DefaultAllocationPool.equals (Object obj)
Definition at line 63 of file DefaultAllocationPool.java.
References org.onosproject.vtnrsc.DefaultAllocationPool.DefaultAllocationPool().
int org.onosproject.vtnrsc.DefaultAllocationPool.hashCode ()
Definition at line 58 of file DefaultAllocationPool.java.
References org.onosproject.vtnrsc.DefaultAllocationPool.endIp(), and org.onosproject.vtnrsc.DefaultAllocationPool.startIp().
IpAddress org.onosproject.vtnrsc.DefaultAllocationPool.startIp ()
The start address for the allocation pool.
Returns
startIp
Implements org.onosproject.vtnrsc.AllocationPool.
Definition at line 48 of file DefaultAllocationPool.java.
Referenced by org.onosproject.vtnrsc.DefaultAllocationPool.DefaultAllocationPool(), org.onosproject.vtnrsc.DefaultAllocationPool.hashCode(), and org.onosproject.vtnrsc.DefaultAllocationPool.toString().
String org.onosproject.vtnrsc.DefaultAllocationPool.toString ()
Definition at line 76 of file DefaultAllocationPool.java.
References org.onosproject.vtnrsc.DefaultAllocationPool.endIp(), and org.onosproject.vtnrsc.DefaultAllocationPool.startIp().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultAllocationPool.java