onos: org.onlab.packet.ICMP Class Reference
org.onlab.packet.ICMP Class Reference
Implements ICMP packet format.
Public Member Functions
byte getIcmpType ()
ICMP setIcmpType (final byte icmpType)
byte getIcmpCode ()
ICMP setIcmpCode (final byte icmpCode)
short getChecksum ()
ICMP setChecksum (final short checksum)
byte[] serialize ()
Serializes the packet.
IPacket deserialize (final byte[] data, final int offset, final int length)
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
Static Public Member Functions
static Deserializer< ICMP > deserializer ()
Deserializer function for ICMP packets.
Static Public Attributes
static final byte TYPE_ECHO_REQUEST = 0x08
static final byte TYPE_ECHO_REPLY = 0x00
static final byte SUBTYPE_ECHO_REPLY = 0x00
static final short ICMP_HEADER_LENGTH = 4
Protected Attributes
byte icmpType
byte icmpCode
short checksum
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements ICMP packet format.
Definition at line 29 of file ICMP.java.
Member Function Documentation
IPacket org.onlab.packet.ICMP.deserialize (final byte[] data, final int offset, final int length)
Definition at line 142 of file ICMP.java.
References find-link-in-cluster.length.
Referenced by org.onlab.packet.ICMP.deserializer().
static Deserializer<ICMP> org.onlab.packet.ICMP.deserializer () static
Deserializer function for ICMP packets.
Returns
deserializer function
Definition at line 205 of file ICMP.java.
References org.onlab.packet.ICMP.deserialize(), org.onlab.packet.ICMP.ICMP_HEADER_LENGTH, and find-link-in-cluster.length.
boolean org.onlab.packet.ICMP.equals (final Object obj)
Definition at line 177 of file ICMP.java.
References org.onlab.packet.ICMP.checksum, org.onlab.packet.ICMP.icmpCode, and org.onlab.packet.ICMP.icmpType.
short org.onlab.packet.ICMP.getChecksum ()
Returns
the checksum
Definition at line 77 of file ICMP.java.
Referenced by org.onlab.packet.ICMPTest.testDeserialize().
byte org.onlab.packet.ICMP.getIcmpCode ()
Returns
the icmp code
Definition at line 60 of file ICMP.java.
Referenced by org.onlab.packet.ICMPTest.testDeserialize().
byte org.onlab.packet.ICMP.getIcmpType ()
Returns
the icmpType
Definition at line 43 of file ICMP.java.
Referenced by org.onlab.packet.ICMPTest.testDeserialize().
int org.onlab.packet.ICMP.hashCode ()
Definition at line 162 of file ICMP.java.
byte [] org.onlab.packet.ICMP.serialize ()
Serializes the packet.
Will compute and set the following fields if they are set to specific values at the time serialize is called: -checksum : 0 -length : 0
Implements org.onlab.packet.IPacket.
Definition at line 97 of file ICMP.java.
References org.onlab.packet.ICMP.checksum, find-link-in-cluster.length, org.onlab.packet.BasePacket.parent, org.onlab.packet.BasePacket.payload, and org.onlab.packet.IPv4.PROTOCOL_ICMP.
ICMP org.onlab.packet.ICMP.setChecksum (final short checksum)
Parameters
checksum the checksum to set
Returns
this
Definition at line 86 of file ICMP.java.
References org.onlab.packet.ICMP.checksum.
ICMP org.onlab.packet.ICMP.setIcmpCode (final byte icmpCode)
Parameters
icmpCode code to set
Returns
this
Definition at line 69 of file ICMP.java.
References org.onlab.packet.ICMP.icmpCode.
ICMP org.onlab.packet.ICMP.setIcmpType (final byte icmpType)
Parameters
icmpType to set
Returns
this
Definition at line 52 of file ICMP.java.
References org.onlab.packet.ICMP.icmpType.
Member Data Documentation
short org.onlab.packet.ICMP.checksum protected
Definition at line 32 of file ICMP.java.
Referenced by org.onlab.packet.ICMP.equals(), org.onlab.packet.ICMP.serialize(), and org.onlab.packet.ICMP.setChecksum().
final short org.onlab.packet.ICMP.ICMP_HEADER_LENGTH = 4 static
Definition at line 38 of file ICMP.java.
Referenced by org.onlab.packet.ICMP.deserializer(), and org.onlab.packet.ICMPTest.setUp().
byte org.onlab.packet.ICMP.icmpCode protected
Definition at line 31 of file ICMP.java.
Referenced by org.onlab.packet.ICMP.equals(), and org.onlab.packet.ICMP.setIcmpCode().
byte org.onlab.packet.ICMP.icmpType protected
Definition at line 30 of file ICMP.java.
Referenced by org.onlab.packet.ICMP.equals(), and org.onlab.packet.ICMP.setIcmpType().
final byte org.onlab.packet.ICMP.SUBTYPE_ECHO_REPLY = 0x00 static
Definition at line 36 of file ICMP.java.
final byte org.onlab.packet.ICMP.TYPE_ECHO_REPLY = 0x00 static
Definition at line 35 of file ICMP.java.
final byte org.onlab.packet.ICMP.TYPE_ECHO_REQUEST = 0x08 static
Definition at line 34 of file ICMP.java.
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ICMP.java