onos: org.onosproject.pcepio.types.PcepLabelDbVerTlv Class Reference
org.onosproject.pcepio.types.PcepLabelDbVerTlv Class Reference
Provides CEP LABEL DB VERSION TLV which contains LSP State DB Version (32 Bit).
Public Member Functions
PcepLabelDbVerTlv (final long rawValue)
constructor to initialize rawValue.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
long getLong ()
Returns LSP State DB Version.
short getLength ()
Returns the Length of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static PcepLabelDbVerTlv of (final long raw)
Returns newly created PcepLabelDbVerTlv object.
static PcepLabelDbVerTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of PcepLabelDbVerTlv.
Static Public Attributes
static final short TYPE = 34
static final short LENGTH = 8
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepLabelDbVerTlv.class)
Detailed Description
Provides CEP LABEL DB VERSION TLV which contains LSP State DB Version (32 Bit).
Definition at line 29 of file PcepLabelDbVerTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PcepLabelDbVerTlv.PcepLabelDbVerTlv (final long rawValue)
constructor to initialize rawValue.
Parameters
rawValue of Pcep Label Db Version Tlv
Definition at line 55 of file PcepLabelDbVerTlv.java.
Referenced by org.onosproject.pcepio.types.PcepLabelDbVerTlv.equals(), and org.onosproject.pcepio.types.PcepLabelDbVerTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.PcepLabelDbVerTlv.equals (Object obj)
Definition at line 99 of file PcepLabelDbVerTlv.java.
References org.onosproject.pcepio.types.PcepLabelDbVerTlv.PcepLabelDbVerTlv().
short org.onosproject.pcepio.types.PcepLabelDbVerTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 84 of file PcepLabelDbVerTlv.java.
References org.onosproject.pcepio.types.PcepLabelDbVerTlv.LENGTH.
long org.onosproject.pcepio.types.PcepLabelDbVerTlv.getLong ()
Returns LSP State DB Version.
Returns
raw value
Definition at line 79 of file PcepLabelDbVerTlv.java.
short org.onosproject.pcepio.types.PcepLabelDbVerTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 89 of file PcepLabelDbVerTlv.java.
References org.onosproject.pcepio.types.PcepLabelDbVerTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.PcepLabelDbVerTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 71 of file PcepLabelDbVerTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.PcepLabelDbVerTlv.hashCode ()
Definition at line 94 of file PcepLabelDbVerTlv.java.
static PcepLabelDbVerTlv org.onosproject.pcepio.types.PcepLabelDbVerTlv.of (final long raw) static
Returns newly created PcepLabelDbVerTlv object.
Parameters
raw LSP State DB Version
Returns
object of PcepLabelDbVerTlv
Definition at line 66 of file PcepLabelDbVerTlv.java.
References org.onosproject.pcepio.types.PcepLabelDbVerTlv.PcepLabelDbVerTlv().
static PcepLabelDbVerTlv org.onosproject.pcepio.types.PcepLabelDbVerTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of PcepLabelDbVerTlv.
Parameters
c input channel buffer
Returns
object of PcepLabelDbVerTlv
Definition at line 125 of file PcepLabelDbVerTlv.java.
String org.onosproject.pcepio.types.PcepLabelDbVerTlv.toString ()
Definition at line 130 of file PcepLabelDbVerTlv.java.
References org.onosproject.pcepio.types.PcepLabelDbVerTlv.LENGTH, and org.onosproject.pcepio.types.PcepLabelDbVerTlv.TYPE.
int org.onosproject.pcepio.types.PcepLabelDbVerTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 111 of file PcepLabelDbVerTlv.java.
References org.onosproject.pcepio.types.PcepLabelDbVerTlv.LENGTH, and org.onosproject.pcepio.types.PcepLabelDbVerTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.PcepLabelDbVerTlv.LENGTH = 8 static
Definition at line 47 of file PcepLabelDbVerTlv.java.
Referenced by org.onosproject.pcepio.types.PcepLabelDbVerTlv.getLength(), org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.parseOptionalTlv(), org.onosproject.pcepio.types.PcepLabelDbVerTlv.toString(), and org.onosproject.pcepio.types.PcepLabelDbVerTlv.write().
final Logger org.onosproject.pcepio.types.PcepLabelDbVerTlv.log = LoggerFactory.getLogger(PcepLabelDbVerTlv.class) static protected
Definition at line 44 of file PcepLabelDbVerTlv.java.
final short org.onosproject.pcepio.types.PcepLabelDbVerTlv.TYPE = 34 static
Definition at line 46 of file PcepLabelDbVerTlv.java.
Referenced by org.onosproject.pcepio.types.PcepLabelDbVerTlv.getType(), org.onosproject.pcepio.types.PcepLabelDbVerTlv.toString(), and org.onosproject.pcepio.types.PcepLabelDbVerTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PcepLabelDbVerTlv.java