onos: org.onosproject.store.link.impl.ECLinkStore Class Reference
org.onosproject.store.link.impl.ECLinkStore Class Reference
Manages the inventory of links using a.
Public Member Functions
void activate ()
void deactivate ()
int getLinkCount ()
Returns the number of links in the store.
Iterable< Link > getLinks ()
Returns an iterable collection of all links in the inventory.
Set< Link > getDeviceEgressLinks (DeviceId deviceId)
Returns all links egressing from the specified device.
Set< Link > getDeviceIngressLinks (DeviceId deviceId)
Returns all links ingressing from the specified device.
Link getLink (ConnectPoint src, ConnectPoint dst)
Returns the link between the two end-points.
Set< Link > getEgressLinks (ConnectPoint src)
Returns all links egressing from the specified connection point.
Set< Link > getIngressLinks (ConnectPoint dst)
Returns all links ingressing to the specified connection point.
LinkEvent createOrUpdateLink (ProviderId providerId, LinkDescription linkDescription)
Creates a new link, or updates an existing one, based on the given information.
LinkEvent removeOrDownLink (ConnectPoint src, ConnectPoint dst)
Removes the link, or marks it as inactive if the link is durable, based on the specified information.
LinkEvent removeLink (ConnectPoint src, ConnectPoint dst)
Removes the link based on the specified information.
Protected Attributes
StorageService storageService
MastershipService mastershipService
DeviceClockService deviceClockService
ClusterCommunicationService clusterCommunicator
ClusterService clusterService
Static Protected Attributes
static final KryoSerializer SERIALIZER
Detailed Description
Manages the inventory of links using a.
EventuallyConsistentMap
.
Definition at line 90 of file ECLinkStore.java.
Member Function Documentation
void org.onosproject.store.link.impl.ECLinkStore.activate ()
Definition at line 131 of file ECLinkStore.java.
References org.onosproject.store.serializers.KryoNamespaces.API, find-flow.deviceId, and org.onosproject.store.link.impl.ECLinkStore.storageService.
LinkEvent org.onosproject.store.link.impl.ECLinkStore.createOrUpdateLink (ProviderId providerId, LinkDescription linkDescription)
Creates a new link, or updates an existing one, based on the given information.
Parameters
providerId provider identity
linkDescription link description
Returns
create or update link event, or null if no change resulted
Implements org.onosproject.net.link.LinkStore.
Definition at line 205 of file ECLinkStore.java.
References org.onosproject.store.link.impl.ECLinkStore.clusterService, find-flow.deviceId, find-link-in-cluster.dstDeviceId, org.onosproject.cluster.ClusterService.getLocalNode(), and org.onosproject.net.link.LinkDescription.src().
void org.onosproject.store.link.impl.ECLinkStore.deactivate ()
Definition at line 160 of file ECLinkStore.java.
Set<Link> org.onosproject.store.link.impl.ECLinkStore.getDeviceEgressLinks (DeviceId deviceId)
Returns all links egressing from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implements org.onosproject.net.link.LinkStore.
Definition at line 180 of file ECLinkStore.java.
References find-flow.deviceId.
Set<Link> org.onosproject.store.link.impl.ECLinkStore.getDeviceIngressLinks (DeviceId deviceId)
Returns all links ingressing from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implements org.onosproject.net.link.LinkStore.
Definition at line 185 of file ECLinkStore.java.
References find-flow.deviceId.
Set<Link> org.onosproject.store.link.impl.ECLinkStore.getEgressLinks (ConnectPoint src)
Returns all links egressing from the specified connection point.
Parameters
src source connection point
Returns
set of connection point links
Implements org.onosproject.net.link.LinkStore.
Definition at line 195 of file ECLinkStore.java.
Set<Link> org.onosproject.store.link.impl.ECLinkStore.getIngressLinks (ConnectPoint dst)
Returns all links ingressing to the specified connection point.
Parameters
dst destination connection point
Returns
set of connection point links
Implements org.onosproject.net.link.LinkStore.
Definition at line 200 of file ECLinkStore.java.
Link org.onosproject.store.link.impl.ECLinkStore.getLink (ConnectPoint src, ConnectPoint dst)
Returns the link between the two end-points.
Parameters
src source connection point
dst destination connection point
Returns
link or null if one not found between the end-points
Implements org.onosproject.net.link.LinkStore.
Definition at line 190 of file ECLinkStore.java.
Referenced by org.onosproject.store.link.impl.ECLinkStore.removeOrDownLink().
int org.onosproject.store.link.impl.ECLinkStore.getLinkCount ()
Returns the number of links in the store.
Returns
number of links
Implements org.onosproject.net.link.LinkStore.
Definition at line 170 of file ECLinkStore.java.
Iterable<Link> org.onosproject.store.link.impl.ECLinkStore.getLinks ()
Returns an iterable collection of all links in the inventory.
Returns
collection of all links
Implements org.onosproject.net.link.LinkStore.
Definition at line 175 of file ECLinkStore.java.
LinkEvent org.onosproject.store.link.impl.ECLinkStore.removeLink (ConnectPoint src, ConnectPoint dst)
Removes the link based on the specified information.
Parameters
src link source
dst link destination
Returns
remove link event, or null if no change resulted
Implements org.onosproject.net.link.LinkStore.
Definition at line 352 of file ECLinkStore.java.
Referenced by org.onosproject.store.link.impl.ECLinkStore.removeOrDownLink().
LinkEvent org.onosproject.store.link.impl.ECLinkStore.removeOrDownLink (ConnectPoint src, ConnectPoint dst)
Removes the link, or marks it as inactive if the link is durable, based on the specified information.
Parameters
src link source
dst link destination
Returns
remove or update link event, or null if no change resulted
Implements org.onosproject.net.link.LinkStore.
Definition at line 332 of file ECLinkStore.java.
References org.onosproject.net.Link.dst(), org.onosproject.store.link.impl.ECLinkStore.getLink(), org.onosproject.net.Link.isDurable(), org.onosproject.net.Provided.providerId(), org.onosproject.store.link.impl.ECLinkStore.removeLink(), and org.onosproject.net.Link.src().
Member Data Documentation
ClusterCommunicationService org.onosproject.store.link.impl.ECLinkStore.clusterCommunicator protected
Definition at line 111 of file ECLinkStore.java.
ClusterService org.onosproject.store.link.impl.ECLinkStore.clusterService protected
Definition at line 114 of file ECLinkStore.java.
Referenced by org.onosproject.store.link.impl.ECLinkStore.createOrUpdateLink().
DeviceClockService org.onosproject.store.link.impl.ECLinkStore.deviceClockService protected
Definition at line 108 of file ECLinkStore.java.
MastershipService org.onosproject.store.link.impl.ECLinkStore.mastershipService protected
Definition at line 105 of file ECLinkStore.java.
final KryoSerializer org.onosproject.store.link.impl.ECLinkStore.SERIALIZER static protected
Initial value:
= new KryoSerializer() {
        @Override
        protected void setupKryoPool() {
            serializerPool = KryoNamespace.newBuilder()
                    .register(DistributedStoreSerializers.STORE_COMMON)
                    .nextId(DistributedStoreSerializers.STORE_CUSTOM_BEGIN)
                    .register(Provided.class)
                    .build();
        }
    }
Definition at line 119 of file ECLinkStore.java.
StorageService org.onosproject.store.link.impl.ECLinkStore.storageService protected
Definition at line 102 of file ECLinkStore.java.
Referenced by org.onosproject.store.link.impl.ECLinkStore.activate().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/link/impl/ECLinkStore.java