onos: org.onosproject.incubator.net.virtual .TenantId Class Reference
org.onosproject.incubator.net.virtual .TenantId Class Reference
Representation of network tenant.
Public Member Functions
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static TenantId tenantId (String id)
Creates a tenant id using the supplied backing id.
Static Public Attributes
static final TenantId NONE = new TenantId()
Represents no tenant, or an unspecified tenant.
Protected Member Functions
TenantId ()
Detailed Description
Representation of network tenant.
Definition at line 28 of file TenantId.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.virtual .TenantId.TenantId () protected
Definition at line 46 of file TenantId.java.
Referenced by org.onosproject.incubator.net.virtual .TenantId.equals(), and org.onosproject.incubator.net.virtual .TenantId.tenantId().
Member Function Documentation
boolean org.onosproject.incubator.net.virtual .TenantId.equals (Object obj)
Definition at line 66 of file TenantId.java.
References find-device.id, and org.onosproject.incubator.net.virtual .TenantId.TenantId().
int org.onosproject.incubator.net.virtual .TenantId.hashCode ()
Definition at line 61 of file TenantId.java.
static TenantId org.onosproject.incubator.net.virtual .TenantId.tenantId (String id) static
Creates a tenant id using the supplied backing id.
Parameters
id network id
Returns
network identifier
Definition at line 56 of file TenantId.java.
References org.onosproject.incubator.net.virtual .TenantId.TenantId().
String org.onosproject.incubator.net.virtual .TenantId.toString ()
Definition at line 79 of file TenantId.java.
Member Data Documentation
final TenantId org.onosproject.incubator.net.virtual .TenantId.NONE = new TenantId() static
Represents no tenant, or an unspecified tenant.
Definition at line 33 of file TenantId.java.
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/virtual/TenantId.java