onos: org.onosproject.net.flow.criteria.EthTypeCriterion Class Reference
org.onosproject.net.flow.criteria.EthTypeCriterion Class Reference
Implementation of Ethernet type criterion (16 bits unsigned integer).
Public Member Functions
Type type ()
Returns the type of criterion.
EthType ethType ()
Gets the Ethernet frame type to match.
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Implementation of Ethernet type criterion (16 bits unsigned integer).
Definition at line 27 of file EthTypeCriterion.java.
Member Function Documentation
boolean org.onosproject.net.flow.criteria.EthTypeCriterion.equals (Object obj)
Definition at line 78 of file EthTypeCriterion.java.
References org.onosproject.net.flow.criteria.EthTypeCriterion.ethType().
EthType org.onosproject.net.flow.criteria.EthTypeCriterion.ethType ()
Gets the Ethernet frame type to match.
Returns
the Ethernet frame type to match (16 bits unsigned integer)
Definition at line 61 of file EthTypeCriterion.java.
Referenced by org.onosproject.net.flow.criteria.EthTypeCriterion.equals().
int org.onosproject.net.flow.criteria.EthTypeCriterion.hashCode ()
Definition at line 73 of file EthTypeCriterion.java.
References org.onosproject.net.flow.criteria.EthTypeCriterion.type().
String org.onosproject.net.flow.criteria.EthTypeCriterion.toString ()
Definition at line 66 of file EthTypeCriterion.java.
References org.onosproject.net.flow.criteria.EthTypeCriterion.type().
Type org.onosproject.net.flow.criteria.EthTypeCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 52 of file EthTypeCriterion.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ETH_TYPE.
Referenced by org.onosproject.net.flow.criteria.EthTypeCriterion.hashCode(), and org.onosproject.net.flow.criteria.EthTypeCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/EthTypeCriterion.java