onos: org.onosproject.bgpio.types.IPReachabilityInformationTlv Class Reference
org.onosproject.bgpio.types.IPReachabilityInformationTlv Class Reference
Provides IP Reachability InformationTlv Tlv which contains IP Prefix.
Public Member Functions
IPReachabilityInformationTlv (byte prefixLen, byte[] ipPrefix, short length)
Constructor to initialize parameters.
IpPrefix getPrefixValue ()
Returns IP Prefix.
byte getPrefixLen ()
Returns IP Prefix length.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
short getType ()
Returns the Type of BGP Message.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static IPReachabilityInformationTlv read (ChannelBuffer cb, short length)
Reads the channel buffer and returns object of IPReachabilityInformationTlv.
static IPReachabilityInformationTlv of (final byte preficLen, final byte[] prefix, final short length)
Public Attributes
short length
Static Public Attributes
static final short TYPE = 265
static final int ONE_BYTE_LEN = 8
Detailed Description
Provides IP Reachability InformationTlv Tlv which contains IP Prefix.
Definition at line 31 of file IPReachabilityInformationTlv.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.IPReachabilityInformationTlv.IPReachabilityInformationTlv (byte prefixLen, byte[] ipPrefix, short length)
Constructor to initialize parameters.
Parameters
prefixLen length of IP Prefix
ipPrefix IP Prefix
length length of value field
Definition at line 61 of file IPReachabilityInformationTlv.java.
References org.onosproject.bgpio.types.IPReachabilityInformationTlv.length.
Referenced by org.onosproject.bgpio.types.IPReachabilityInformationTlv.compareTo(), org.onosproject.bgpio.types.IPReachabilityInformationTlv.equals(), and org.onosproject.bgpio.types.IPReachabilityInformationTlv.of().
Member Function Documentation
int org.onosproject.bgpio.types.IPReachabilityInformationTlv.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 147 of file IPReachabilityInformationTlv.java.
References org.onosproject.bgpio.types.IPReachabilityInformationTlv.equals(), and org.onosproject.bgpio.types.IPReachabilityInformationTlv.IPReachabilityInformationTlv().
boolean org.onosproject.bgpio.types.IPReachabilityInformationTlv.equals (Object obj)
Definition at line 92 of file IPReachabilityInformationTlv.java.
References org.onosproject.bgpio.types.IPReachabilityInformationTlv.IPReachabilityInformationTlv().
Referenced by org.onosproject.bgpio.types.IPReachabilityInformationTlv.compareTo().
byte org.onosproject.bgpio.types.IPReachabilityInformationTlv.getPrefixLen ()
Returns IP Prefix length.
Returns
IP Prefix length
Definition at line 82 of file IPReachabilityInformationTlv.java.
Referenced by org.onosproject.bgpio.types.IPReachabilityInformationTlv.toString().
IpPrefix org.onosproject.bgpio.types.IPReachabilityInformationTlv.getPrefixValue ()
Returns IP Prefix.
Returns
IP Prefix
Definition at line 72 of file IPReachabilityInformationTlv.java.
References onosUploadBits.prefix.
Referenced by org.onosproject.bgpio.types.IPReachabilityInformationTlv.toString().
short org.onosproject.bgpio.types.IPReachabilityInformationTlv.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 142 of file IPReachabilityInformationTlv.java.
References org.onosproject.bgpio.types.IPReachabilityInformationTlv.TYPE.
int org.onosproject.bgpio.types.IPReachabilityInformationTlv.hashCode ()
Definition at line 87 of file IPReachabilityInformationTlv.java.
static IPReachabilityInformationTlv org.onosproject.bgpio.types.IPReachabilityInformationTlv.of (final byte preficLen, final byte[] prefix, final short length) static
Definition at line 138 of file IPReachabilityInformationTlv.java.
References org.onosproject.bgpio.types.IPReachabilityInformationTlv.IPReachabilityInformationTlv().
static IPReachabilityInformationTlv org.onosproject.bgpio.types.IPReachabilityInformationTlv.read (ChannelBuffer cb, short length) static
Reads the channel buffer and returns object of IPReachabilityInformationTlv.
Parameters
cb ChannelBuffer
length of value field
Returns
object of IPReachabilityInformationTlv
Definition at line 121 of file IPReachabilityInformationTlv.java.
References org.onosproject.bgpio.types.IPReachabilityInformationTlv.length, org.onosproject.bgpio.types.IPReachabilityInformationTlv.ONE_BYTE_LEN, and onosUploadBits.prefix.
String org.onosproject.bgpio.types.IPReachabilityInformationTlv.toString ()
Definition at line 157 of file IPReachabilityInformationTlv.java.
References org.onosproject.bgpio.types.IPReachabilityInformationTlv.getPrefixLen(), org.onosproject.bgpio.types.IPReachabilityInformationTlv.getPrefixValue(), org.onosproject.bgpio.types.IPReachabilityInformationTlv.length, and org.onosproject.bgpio.types.IPReachabilityInformationTlv.TYPE.
int org.onosproject.bgpio.types.IPReachabilityInformationTlv.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 105 of file IPReachabilityInformationTlv.java.
References org.onosproject.bgpio.types.IPReachabilityInformationTlv.length, and org.onosproject.bgpio.types.IPReachabilityInformationTlv.TYPE.
Member Data Documentation
short org.onosproject.bgpio.types.IPReachabilityInformationTlv.length
Definition at line 52 of file IPReachabilityInformationTlv.java.
Referenced by org.onosproject.bgpio.types.IPReachabilityInformationTlv.IPReachabilityInformationTlv(), org.onosproject.bgpio.types.IPReachabilityInformationTlv.read(), org.onosproject.bgpio.types.IPReachabilityInformationTlv.toString(), and org.onosproject.bgpio.types.IPReachabilityInformationTlv.write().
final int org.onosproject.bgpio.types.IPReachabilityInformationTlv.ONE_BYTE_LEN = 8 static
Definition at line 48 of file IPReachabilityInformationTlv.java.
Referenced by org.onosproject.bgpio.types.IPReachabilityInformationTlv.read().
final short org.onosproject.bgpio.types.IPReachabilityInformationTlv.TYPE = 265 static
Definition at line 47 of file IPReachabilityInformationTlv.java.
Referenced by org.onosproject.bgpio.types.IPReachabilityInformationTlv.getType(), org.onosproject.bgpio.types.IPReachabilityInformationTlv.toString(), and org.onosproject.bgpio.types.IPReachabilityInformationTlv.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/IPReachabilityInformationTlv.java