onos: org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1 Class Reference
Provides PCEP RRO object.
Classes
class Builder
Builder class for PCEP RRO object.
Public Member Functions
PcepRroObjectVer1 ()
Reset variables.
PcepRroObjectVer1 (PcepObjectHeader rroObjHeader, LinkedList< PcepValueType > llSubObjects)
constructor to initialize parameters for RRO object.
PcepObjectHeader getRroObjHeader ()
Returns PCEP RRO Object Header.
void setRroObjHeader (PcepObjectHeader obj)
Sets PCEP RRO Object Header.
LinkedList< PcepValueType > getSubObjects ()
Returns list of SubObjects.
void setSubObjects (LinkedList< PcepValueType > llSubObjects)
Sets list of SubObjects and return its builder.
int write (ChannelBuffer cb) throws PcepParseException
Writes the RRO Object into channel buffer.
String toString ()
Static Public Member Functions
static PcepRroObject read (ChannelBuffer cb) throws PcepParseException
Reads the channel buffer and returns object of PcepRroObject.
Static Public Attributes
static final byte RRO_OBJ_TYPE = 1
static final byte RRO_OBJ_CLASS = 8
static final byte RRO_OBJECT_VERSION = 1
static final short RRO_OBJ_MINIMUM_LENGTH = 12
static final int OBJECT_HEADER_LENGTH = 4
static final int YTYPE_SHIFT_VALUE = 0x7F
Static Protected Member Functions
static LinkedList< PcepValueType > parseSubObjects (ChannelBuffer cb) throws PcepParseException
Returns list of sub objects.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepRroObjectVer1.class)
Detailed Description
Provides PCEP RRO object.
Definition at line 38 of file PcepRroObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.PcepRroObjectVer1 ()
Reset variables.
Definition at line 119 of file PcepRroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.read().
org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.PcepRroObjectVer1 (PcepObjectHeader rroObjHeader, LinkedList< PcepValueType > llSubObjects)
constructor to initialize parameters for RRO object.
Parameters
rroObjHeader RRO object header
llSubObjects list of sub objects
Definition at line 131 of file PcepRroObjectVer1.java.
Member Function Documentation
PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.getRroObjHeader ()
Returns PCEP RRO Object Header.
Returns
rroObjHeader RRO Object header
Definition at line 141 of file PcepRroObjectVer1.java.
LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.getSubObjects ()
Returns list of SubObjects.
Returns
list of SubObjects
Implements org.onosproject.pcepio.protocol.PcepRroObject.
Definition at line 155 of file PcepRroObjectVer1.java.
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.parseSubObjects (ChannelBuffer cb) throws PcepParseException static protected
Returns list of sub objects.
Parameters
cb of type channel buffer
Returns
list of sub objects
Exceptions
PcepParseException when fails to parse list of sub objects
Definition at line 191 of file PcepRroObjectVer1.java.
References org.onosproject.pcepio.types.IPv6SubObject.VALUE_LENGTH, and org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.YTYPE_SHIFT_VALUE.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.read().
static PcepRroObject org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.read (ChannelBuffer cb) throws PcepParseException static
Reads the channel buffer and returns object of PcepRroObject.
Parameters
cb of type channel buffer
Returns
object of PcepRroObject
Exceptions
PcepParseException when fails to read from channel buffer
Definition at line 171 of file PcepRroObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.OBJECT_HEADER_LENGTH, org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.parseSubObjects(), and org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.PcepRroObjectVer1().
void org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.setRroObjHeader (PcepObjectHeader obj)
Sets PCEP RRO Object Header.
Parameters
obj Object header
Definition at line 150 of file PcepRroObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.setSubObjects (LinkedList< PcepValueType > llSubObjects)
Sets list of SubObjects and return its builder.
Parameters
llSubObjects list of SubObjects
Implements org.onosproject.pcepio.protocol.PcepRroObject.
Definition at line 160 of file PcepRroObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.toString ()
Definition at line 340 of file PcepRroObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the RRO Object into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException when object header failed to write in channel buffer
Implements org.onosproject.pcepio.protocol.PcepRroObject.
Definition at line 235 of file PcepRroObjectVer1.java.
Member Data Documentation
final Logger org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.log = LoggerFactory.getLogger(PcepRroObjectVer1.class) static protected
Definition at line 97 of file PcepRroObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.OBJECT_HEADER_LENGTH = 4 static
Definition at line 103 of file PcepRroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.read().
final byte org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.RRO_OBJ_CLASS = 8 static
Definition at line 100 of file PcepRroObjectVer1.java.
final short org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.RRO_OBJ_MINIMUM_LENGTH = 12 static
Definition at line 102 of file PcepRroObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.RRO_OBJ_TYPE = 1 static
Definition at line 99 of file PcepRroObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.RRO_OBJECT_VERSION = 1 static
Definition at line 101 of file PcepRroObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.YTYPE_SHIFT_VALUE = 0x7F static
Definition at line 104 of file PcepRroObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.parseSubObjects().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepRroObjectVer1.java