onos: org.onlab.jdvue.Catalog Class Reference
org.onlab.jdvue.Catalog Class Reference
Produces a package & source catalogue.
Public Member Functions
void load (String catalogPath) throws IOException
Loads the catalog from the specified catalog file.
void analyze ()
Analyzes the catalog by resolving imports and identifying circular package dependencies.
Collection< JavaSource > getSources ()
Returns the collection of java sources.
JavaSource getSource (String name)
Returns the Java source with the specified name.
Collection< JavaPackage > getPackages ()
Returns the collection of all Java packages.
Set< DependencyCycle > getCycles ()
Returns the set of all Java package dependency cycles.
Set< Dependency > getCycleSegments ()
Returns the set of all Java package dependency cycle segments.
Set< DependencyCycle > getPackageCycles (JavaPackage javaPackage)
Returns the set of dependency cycles which involve the specified package.
Set< Dependency > getPackageCycleSegments (JavaPackage javaPackage)
Returns the set of dependency cycle segments which involve the specified package.
JavaPackage getPackage (String name)
Returns the Java package with the specified name.
String toString ()
Detailed Description
Produces a package & source catalogue.
Author
Thomas Vachuska
Definition at line 40 of file Catalog.java.
Member Function Documentation
void org.onlab.jdvue.Catalog.analyze ()
Analyzes the catalog by resolving imports and identifying circular package dependencies.
Definition at line 98 of file Catalog.java.
Set<DependencyCycle> org.onlab.jdvue.Catalog.getCycles ()
Returns the set of all Java package dependency cycles.
Returns
set of dependency cycles
Definition at line 352 of file Catalog.java.
Referenced by org.onlab.jdvue.CatalogTest.basics().
Set<Dependency> org.onlab.jdvue.Catalog.getCycleSegments ()
Returns the set of all Java package dependency cycle segments.
Returns
set of dependency cycle segments
Definition at line 361 of file Catalog.java.
Referenced by org.onlab.jdvue.CatalogTest.basics().
JavaPackage org.onlab.jdvue.Catalog.getPackage (String name)
Returns the Java package with the specified name.
Parameters
name Java package name
Returns
Java package
Definition at line 393 of file Catalog.java.
References create-flow.name.
Set<DependencyCycle> org.onlab.jdvue.Catalog.getPackageCycles (JavaPackage javaPackage)
Returns the set of dependency cycles which involve the specified package.
Parameters
javaPackage java package
Returns
set of dependency cycles
Definition at line 371 of file Catalog.java.
Referenced by org.onlab.jdvue.CatalogTest.basics().
Set<Dependency> org.onlab.jdvue.Catalog.getPackageCycleSegments (JavaPackage javaPackage)
Returns the set of dependency cycle segments which involve the specified package.
Parameters
javaPackage java package
Returns
set of dependency cycle segments
Definition at line 382 of file Catalog.java.
Collection<JavaPackage> org.onlab.jdvue.Catalog.getPackages ()
Returns the collection of all Java packages.
Returns
collection of java packages
Definition at line 343 of file Catalog.java.
Referenced by org.onlab.jdvue.CatalogTest.basics().
JavaSource org.onlab.jdvue.Catalog.getSource (String name)
Returns the Java source with the specified name.
Parameters
name Java source name
Returns
Java source
Definition at line 334 of file Catalog.java.
References create-flow.name.
Collection<JavaSource> org.onlab.jdvue.Catalog.getSources ()
Returns the collection of java sources.
Returns
collection of java sources
Definition at line 324 of file Catalog.java.
Referenced by org.onlab.jdvue.CatalogTest.basics().
void org.onlab.jdvue.Catalog.load (String catalogPath) throws IOException
Loads the catalog from the specified catalog file.
Parameters
catalogPath catalog file path
Exceptions
IOException if unable to read the catalog file
Definition at line 61 of file Catalog.java.
String org.onlab.jdvue.Catalog.toString ()
Definition at line 398 of file Catalog.java.
The documentation for this class was generated from the following file:
utils/jdvue/src/main/java/org/onlab/jdvue/Catalog.java