onos: org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode Class Reference
org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode Class Reference
Implements BGP attribute opaque node.
Public Member Functions
BgpAttrOpaqueNode (byte[] opaqueNodeAttribute)
Constructor to initialize parameter.
byte[] attrOpaqueNode ()
Returns opaque node attribute.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpAttrOpaqueNode of (byte[] opaqueNodeAttribute)
Returns object of this class with specified values.
static BgpAttrOpaqueNode read (ChannelBuffer cb) throws BgpParseException
Reads the Opaque Node Properties.
Static Public Attributes
static final int ATTRNODE_OPAQUEDATA = 1025
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP attribute opaque node.
Definition at line 33 of file BgpAttrOpaqueNode.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.BgpAttrOpaqueNode (byte[] opaqueNodeAttribute)
Constructor to initialize parameter.
Parameters
opaqueNodeAttribute opaque node attribute
Definition at line 48 of file BgpAttrOpaqueNode.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.equals(), and org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.of().
Member Function Documentation
byte [] org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.attrOpaqueNode ()
Returns opaque node attribute.
Returns
LS node attribute value
Definition at line 93 of file BgpAttrOpaqueNode.java.
int org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 134 of file BgpAttrOpaqueNode.java.
boolean org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.equals (Object obj)
Definition at line 108 of file BgpAttrOpaqueNode.java.
References org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.BgpAttrOpaqueNode().
short org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 98 of file BgpAttrOpaqueNode.java.
References org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.ATTRNODE_OPAQUEDATA.
int org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.hashCode ()
Definition at line 103 of file BgpAttrOpaqueNode.java.
static BgpAttrOpaqueNode org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.of (byte[] opaqueNodeAttribute) static
Returns object of this class with specified values.
Parameters
opaqueNodeAttribute Prefix Metric
Returns
object of BgpAttrOpaqueNode
Definition at line 58 of file BgpAttrOpaqueNode.java.
References org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.BgpAttrOpaqueNode().
static BgpAttrOpaqueNode org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.read (ChannelBuffer cb) throws BgpParseException static
Reads the Opaque Node Properties.
Parameters
cb ChannelBuffer
Returns
object of BgpAttrOpaqueNode
Exceptions
BgpParseException while parsing BgpAttrOpaqueNode
Definition at line 69 of file BgpAttrOpaqueNode.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.toString ()
Definition at line 128 of file BgpAttrOpaqueNode.java.
int org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 122 of file BgpAttrOpaqueNode.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.ATTRNODE_OPAQUEDATA = 1025 static
Definition at line 38 of file BgpAttrOpaqueNode.java.
Referenced by org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.getType().
final Logger org.onosproject.bgpio.types.attr.BgpAttrOpaqueNode.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpAttrOpaqueNode.class)
Definition at line 35 of file BgpAttrOpaqueNode.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpAttrOpaqueNode.java