onos: org.onosproject.ui.impl.TopologyViewMessageHandler Class Reference
org.onosproject.ui.impl.TopologyViewMessageHandler Class Reference
Web socket capable of interacting with the GUI topology view.
Public Member Functions
void init (UiConnection connection, ServiceDirectory directory)
void destroy ()
Public Member Functions inherited from org.onosproject.ui.impl.TopologyViewMessageHandlerBase
void init (UiConnection connection, ServiceDirectory directory)
Public Member Functions inherited from org.onosproject.ui.UiMessageHandler
Set< String > messageTypes ()
Returns the set of message types which this handler is capable of processing.
void process (ObjectNode message)
Processes a JSON message from the user interface client.
void init (UiConnection connection, ServiceDirectory directory)
Initializes the handler with the user interface connection and service directory context.
void destroy ()
Destroys the message handler context.
UiConnection connection ()
Returns the user interface connection with which this handler was primed.
ServiceDirectory directory ()
Returns the user interface connection with which this handler was primed.
Protected Member Functions
Collection< RequestHandler > createRequestHandlers ()
Subclasses must create and return the collection of request handlers for the message types they handle.
void sendHighlights (Highlights highlights)
Protected Member Functions inherited from org.onosproject.ui.impl.TopologyViewMessageHandlerBase
ObjectNode info (long id, String message)
ObjectNode warning (long id, String message)
ObjectNode error (long id, String message)
ObjectNode instanceMessage (ClusterEvent event, String msgType)
ObjectNode deviceMessage (DeviceEvent event)
ObjectNode linkMessage (LinkEvent event)
ObjectNode hostMessage (HostEvent event)
void updateMetaUi (ObjectNode payload)
PropertyPanel summmaryMessage (long sid)
PropertyPanel deviceDetails (DeviceId deviceId, long sid)
int getFlowCount (DeviceId deviceId)
int getTunnelCount (DeviceId deviceId)
PropertyPanel hostDetails (HostId hostId, long sid)
Protected Member Functions inherited from org.onosproject.ui.UiMessageHandler
ObjectNode objectNode ()
Returns a freshly minted object node.
ArrayNode arrayNode ()
Returns a freshly minted array node.
synchronized void sendMessage (ObjectNode data)
Sends the specified data to the client.
Additional Inherited Members
Protected Attributes inherited from org.onosproject.ui.impl.TopologyViewMessageHandlerBase
ServiceDirectory directory
ClusterService clusterService
DeviceService deviceService
LinkService linkService
HostService hostService
MastershipService mastershipService
IntentService intentService
FlowRuleService flowService
StatisticService flowStatsService
PortStatisticsService portStatsService
TopologyService topologyService
TunnelService tunnelService
ServicesBundle servicesBundle
Static Protected Attributes inherited from org.onosproject.ui.impl.TopologyViewMessageHandlerBase
static final Logger log
static final String SHOW_HIGHLIGHTS = "showHighlights"
Detailed Description
Web socket capable of interacting with the GUI topology view.
Definition at line 96 of file TopologyViewMessageHandler.java.
Member Function Documentation
Collection<RequestHandler> org.onosproject.ui.impl.TopologyViewMessageHandler.createRequestHandlers () protected virtual
Subclasses must create and return the collection of request handlers for the message types they handle.
Note that request handlers should be stateless. When we are destroyed, we will simply drop our references to them and allow them to be garbage collected.
Returns
the message handler instances
Implements org.onosproject.ui.UiMessageHandler.
Definition at line 203 of file TopologyViewMessageHandler.java.
void org.onosproject.ui.impl.TopologyViewMessageHandler.destroy ()
Definition at line 196 of file TopologyViewMessageHandler.java.
void org.onosproject.ui.impl.TopologyViewMessageHandler.init (UiConnection connection, ServiceDirectory directory)
Definition at line 189 of file TopologyViewMessageHandler.java.
References org.onosproject.ui.UiMessageHandler.connection(), org.onosproject.ui.UiMessageHandler.directory(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.servicesBundle.
void org.onosproject.ui.impl.TopologyViewMessageHandler.sendHighlights (Highlights highlights) protected
Definition at line 583 of file TopologyViewMessageHandler.java.
References org.onosproject.ui.UiMessageHandler.sendMessage().
The documentation for this class was generated from the following file:
web/gui/src/main/java/org/onosproject/ui/impl/TopologyViewMessageHandler.java