onos: org.onlab.graph.DepthFirstSearchTest Class Reference
org.onlab.graph.DepthFirstSearchTest Class Reference
Test of the DFS algorithm.
Public Member Functions
void defaultGraphTest ()
void defaultHopCountWeight ()
void executeBroadSearch ()
Public Member Functions inherited from org.onlab.graph.AbstractGraphPathSearchTest
void noSuchSourceArgument ()
void nullGraphArgument ()
void nullSourceArgument ()
void samenessThreshold ()
Protected Member Functions
DepthFirstSearch< TestVertex,
TestEdge > graphSearch ()
Creates a test-specific graph search to exercise.
void executeDefaultTest (int minLength, int maxLength, double minCost, double maxCost)
Protected Member Functions inherited from org.onlab.graph.GraphTest
void printPaths (Set< Path< TestVertex, TestEdge >> paths)
Set< TestVertex > vertexes ()
Set< TestEdge > edges ()
Additional Inherited Members
Protected Attributes inherited from org.onlab.graph.GraphTest
Graph< TestVertex, TestEdge > graph
EdgeWeight< TestVertex, TestEdge > weight
Detailed Description
Test of the DFS algorithm.
Definition at line 30 of file DepthFirstSearchTest.java.
Member Function Documentation
void org.onlab.graph.DepthFirstSearchTest.defaultGraphTest ()
Definition at line 38 of file DepthFirstSearchTest.java.
References org.onlab.graph.DepthFirstSearchTest.executeBroadSearch(), and org.onlab.graph.DepthFirstSearchTest.executeDefaultTest().
void org.onlab.graph.DepthFirstSearchTest.defaultHopCountWeight ()
Definition at line 44 of file DepthFirstSearchTest.java.
References org.onlab.graph.DepthFirstSearchTest.executeBroadSearch(), org.onlab.graph.DepthFirstSearchTest.executeDefaultTest(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.DepthFirstSearchTest.executeBroadSearch ()
Definition at line 75 of file DepthFirstSearchTest.java.
References org.onlab.graph.GraphTest.edges(), org.onlab.graph.GraphTest.graph, org.onlab.graph.DepthFirstSearchTest.graphSearch(), org.onlab.graph.GraphTest.vertexes(), and org.onlab.graph.GraphTest.weight.
Referenced by org.onlab.graph.DepthFirstSearchTest.defaultGraphTest(), and org.onlab.graph.DepthFirstSearchTest.defaultHopCountWeight().
void org.onlab.graph.DepthFirstSearchTest.executeDefaultTest (int minLength, int maxLength, double minCost, double maxCost) protected
Definition at line 50 of file DepthFirstSearchTest.java.
References org.onlab.graph.GraphTest.edges(), org.onlab.graph.GraphTest.graph, org.onlab.graph.DepthFirstSearchTest.graphSearch(), org.onlab.graph.GraphTest.printPaths(), onos.size, org.onlab.graph.GraphTest.vertexes(), and org.onlab.graph.GraphTest.weight.
Referenced by org.onlab.graph.DepthFirstSearchTest.defaultGraphTest(), and org.onlab.graph.DepthFirstSearchTest.defaultHopCountWeight().
DepthFirstSearch<TestVertex, TestEdge> org.onlab.graph.DepthFirstSearchTest.graphSearch () protected virtual
Creates a test-specific graph search to exercise.
Returns
graph search
Implements org.onlab.graph.AbstractGraphPathSearchTest.
Definition at line 33 of file DepthFirstSearchTest.java.
Referenced by org.onlab.graph.DepthFirstSearchTest.executeBroadSearch(), and org.onlab.graph.DepthFirstSearchTest.executeDefaultTest().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/graph/DepthFirstSearchTest.java