onos: org.onosproject.net.flowobjective.impl.composition.ForwardTable Class Reference
org.onosproject.net.flowobjective.impl.composition.ForwardTable Class Reference
Provides a table to store Forward.
Public Member Functions
ForwardTable ()
ForwardUpdateTable updateForward (ForwardingObjective forwardingObjective)
ForwardUpdateTable updateForward (List< ForwardingObjective > forwardingObjectives)
void addGeneratedParentForwardingObjective (ForwardingObjective child, ForwardingObjective parent)
void deleteGeneratedParentForwardingObjective (List< ForwardingObjective > children)
List< ForwardingObjective > getGeneratedParentForwardingObjectiveForRemove (ForwardingObjective child)
Collection< ForwardingObjective > getForwardingObjectives ()
Static Public Member Functions
static int forwardingObjectiveHash (ForwardingObjective forwardingObjective)
Protected Attributes
Map< Integer, ForwardingObjective > forwardMap
Map< Integer, List
< ForwardingObjective > > generatedParentForwardingObjectiveMap
Detailed Description
Provides a table to store Forward.
Definition at line 31 of file ForwardTable.java.
Constructor & Destructor Documentation
org.onosproject.net.flowobjective.impl.composition.ForwardTable.ForwardTable ()
Definition at line 36 of file ForwardTable.java.
Member Function Documentation
void org.onosproject.net.flowobjective.impl.composition.ForwardTable.addGeneratedParentForwardingObjective (ForwardingObjective child, ForwardingObjective parent)
Definition at line 69 of file ForwardTable.java.
References org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardingObjectiveHash().
void org.onosproject.net.flowobjective.impl.composition.ForwardTable.deleteGeneratedParentForwardingObjective (List< ForwardingObjective > children)
Definition at line 73 of file ForwardTable.java.
References org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardingObjectiveHash().
static int org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardingObjectiveHash (ForwardingObjective forwardingObjective) static
Definition at line 103 of file ForwardTable.java.
References org.onosproject.net.flowobjective.ForwardingObjective.flag(), org.onosproject.net.flowobjective.Objective.priority(), org.onosproject.net.flowobjective.Objective.timeout(), and org.onosproject.net.flowobjective.ForwardingObjective.treatment().
Referenced by org.onosproject.net.flowobjective.impl.composition.ForwardTable.addGeneratedParentForwardingObjective(), org.onosproject.net.flowobjective.impl.composition.ForwardTable.deleteGeneratedParentForwardingObjective(), org.onosproject.net.flowobjective.impl.composition.ForwardTable.getGeneratedParentForwardingObjectiveForRemove(), and org.onosproject.net.flowobjective.impl.composition.ForwardTable.updateForward().
Collection<ForwardingObjective> org.onosproject.net.flowobjective.impl.composition.ForwardTable.getForwardingObjectives ()
Definition at line 99 of file ForwardTable.java.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateForwardComposition().
List<ForwardingObjective> org.onosproject.net.flowobjective.impl.composition.ForwardTable.getGeneratedParentForwardingObjectiveForRemove (ForwardingObjective child)
Definition at line 83 of file ForwardTable.java.
References org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardingObjectiveHash().
ForwardUpdateTable org.onosproject.net.flowobjective.impl.composition.ForwardTable.updateForward (ForwardingObjective forwardingObjective)
Definition at line 41 of file ForwardTable.java.
References org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardingObjectiveHash(), org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardMap, and org.onosproject.net.flowobjective.Objective.op().
ForwardUpdateTable org.onosproject.net.flowobjective.impl.composition.ForwardTable.updateForward (List< ForwardingObjective > forwardingObjectives)
Definition at line 61 of file ForwardTable.java.
Member Data Documentation
Map<Integer, ForwardingObjective> org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardMap protected
Definition at line 33 of file ForwardTable.java.
Referenced by org.onosproject.net.flowobjective.impl.composition.ForwardTable.updateForward().
Map<Integer, List<ForwardingObjective> > org.onosproject.net.flowobjective.impl.composition.ForwardTable.generatedParentForwardingObjectiveMap protected
Definition at line 34 of file ForwardTable.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/flowobjective/impl/composition/ForwardTable.java