onos: org.onosproject.security.impl.DefaultPolicyBuilder Class Reference
org.onosproject.security.impl.DefaultPolicyBuilder Class Reference
Static Public Member Functions
static List< Permission > getUserApplicationPermissions (Set< org.onosproject.security.Permission > permissions)
static List< Permission > getAdminApplicationPermissions (Set< org.onosproject.security.Permission > permissions)
static List< Permission > convertToJavaPermissions (Set< org.onosproject.security.Permission > permissions)
static Set
< org.onosproject.security.Permission > convertToOnosPermissions (List< Permission > permissions)
static List< Permission > getDefaultPerms ()
static Set< String > getNBServiceList ()
static
org.onosproject.security.Permission getOnosPermission (Permission permission)
Static Protected Attributes
static ConcurrentHashMap
< AppPermission.Type, Set
< String > > serviceDirectory = getServiceDirectory()
static List< Permission > defaultPermissions = getDefaultPerms()
static List< Permission > adminServicePermissions = getAdminDefaultPerms()
Detailed Description
Definition at line 87 of file DefaultPolicyBuilder.java.
Member Function Documentation
static List<Permission> org.onosproject.security.impl.DefaultPolicyBuilder.convertToJavaPermissions (Set< org.onosproject.security.Permission > permissions) static
Definition at line 117 of file DefaultPolicyBuilder.java.
References org.onosproject.security.AppPermission.getType(), and org.onosproject.security.impl.DefaultPolicyBuilder.serviceDirectory.
Referenced by org.onosproject.security.impl.DefaultPolicyBuilder.getAdminApplicationPermissions(), org.onosproject.security.impl.SecurityModeManager.getPrintableGrantedPermissions(), org.onosproject.security.impl.SecurityModeManager.getPrintableRequestedPermissions(), and org.onosproject.security.impl.DefaultPolicyBuilder.getUserApplicationPermissions().
static Set<org.onosproject.security.Permission> org.onosproject.security.impl.DefaultPolicyBuilder.convertToOnosPermissions (List< Permission > permissions) static
Definition at line 145 of file DefaultPolicyBuilder.java.
References org.onosproject.security.impl.DefaultPolicyBuilder.getOnosPermission().
static List<Permission> org.onosproject.security.impl.DefaultPolicyBuilder.getAdminApplicationPermissions (Set< org.onosproject.security.Permission > permissions) static
Definition at line 105 of file DefaultPolicyBuilder.java.
References org.onosproject.security.impl.DefaultPolicyBuilder.adminServicePermissions, org.onosproject.security.impl.DefaultPolicyBuilder.convertToJavaPermissions(), org.onosproject.security.impl.DefaultPolicyBuilder.defaultPermissions, and org.onosproject.security.impl.DefaultPolicyBuilder.serviceDirectory.
static List<Permission> org.onosproject.security.impl.DefaultPolicyBuilder.getDefaultPerms () static
Definition at line 156 of file DefaultPolicyBuilder.java.
static Set<String> org.onosproject.security.impl.DefaultPolicyBuilder.getNBServiceList () static
Definition at line 207 of file DefaultPolicyBuilder.java.
static org.onosproject.security.Permission org.onosproject.security.impl.DefaultPolicyBuilder.getOnosPermission (Permission permission) static
Definition at line 301 of file DefaultPolicyBuilder.java.
Referenced by org.onosproject.security.impl.DefaultPolicyBuilder.convertToOnosPermissions().
static List<Permission> org.onosproject.security.impl.DefaultPolicyBuilder.getUserApplicationPermissions (Set< org.onosproject.security.Permission > permissions) static
Definition at line 98 of file DefaultPolicyBuilder.java.
References org.onosproject.security.impl.DefaultPolicyBuilder.convertToJavaPermissions(), and org.onosproject.security.impl.DefaultPolicyBuilder.defaultPermissions.
Member Data Documentation
List<Permission> org.onosproject.security.impl.DefaultPolicyBuilder.adminServicePermissions = getAdminDefaultPerms() static protected
Definition at line 93 of file DefaultPolicyBuilder.java.
Referenced by org.onosproject.security.impl.DefaultPolicyBuilder.getAdminApplicationPermissions().
List<Permission> org.onosproject.security.impl.DefaultPolicyBuilder.defaultPermissions = getDefaultPerms() static protected
Definition at line 92 of file DefaultPolicyBuilder.java.
Referenced by org.onosproject.security.impl.DefaultPolicyBuilder.getAdminApplicationPermissions(), and org.onosproject.security.impl.DefaultPolicyBuilder.getUserApplicationPermissions().
ConcurrentHashMap<AppPermission.Type, Set<String> > org.onosproject.security.impl.DefaultPolicyBuilder.serviceDirectory = getServiceDirectory() static protected
Definition at line 90 of file DefaultPolicyBuilder.java.
Referenced by org.onosproject.security.impl.DefaultPolicyBuilder.convertToJavaPermissions(), and org.onosproject.security.impl.DefaultPolicyBuilder.getAdminApplicationPermissions().
The documentation for this class was generated from the following file:
core/security/src/main/java/org/onosproject/security/impl/DefaultPolicyBuilder.java