onos: org.onosproject.cfg.ComponentConfigEvent Class Reference
org.onosproject.cfg.ComponentConfigEvent Class Reference
Describes a component configuration event.
Classes
enum Type
Public Member Functions
ComponentConfigEvent (Type type, String componentName, String name, String value)
Creates an event of a given type and for the specified app and the current time.
String name ()
Returns the property name.
String value ()
Returns the property value as a string.
Detailed Description
Describes a component configuration event.
Definition at line 23 of file ComponentConfigEvent.java.
Constructor & Destructor Documentation
org.onosproject.cfg.ComponentConfigEvent.ComponentConfigEvent (Type type, String componentName, String name, String value)
Creates an event of a given type and for the specified app and the current time.
Parameters
type config property event type
componentName component name event subject
name config property name
value config property value
Definition at line 49 of file ComponentConfigEvent.java.
References org.onosproject.cfg.ComponentConfigEvent.name(), and org.onosproject.cfg.ComponentConfigEvent.value().
Member Function Documentation
String org.onosproject.cfg.ComponentConfigEvent.name ()
Returns the property name.
Returns
property name
Definition at line 61 of file ComponentConfigEvent.java.
Referenced by org.onosproject.cfg.ComponentConfigEvent.ComponentConfigEvent(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.cfg.ComponentConfigEvent.value ()
Returns the property value as a string.
Returns
string value
Definition at line 70 of file ComponentConfigEvent.java.
Referenced by org.onosproject.cfg.ComponentConfigEvent.ComponentConfigEvent().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/cfg/ComponentConfigEvent.java