onos: org.onosproject.cli.net.DevicePortsListCommand Class Reference
org.onosproject.cli.net.DevicePortsListCommand Class Reference
Lists all ports or all ports of a device.
Public Member Functions
JsonNode jsonPorts (DeviceService service, Iterable< Device > devices)
Produces JSON array containing ports of the specified devices.
JsonNode jsonPorts (DeviceService service, ObjectMapper mapper, Device device)
Produces JSON array containing ports of the specified device.
Public Member Functions inherited from org.onosproject.cli.AbstractShellCommand
void print (String format, Object...args)
Prints the arguments using the specified format.
void error (String format, Object...args)
Prints the arguments using the specified format to error stream.
ObjectMapper mapper ()
Returns the JSON object mapper.
Protected Member Functions
void execute ()
Executes this command.
void printDevice (DeviceService service, Device device)
Protected Member Functions inherited from org.onosproject.cli.net.DevicesListCommand
void execute ()
Executes this command.
void printDevice (DeviceService service, Device device)
Prints information about the specified device.
Protected Member Functions inherited from org.onosproject.cli.AbstractShellCommand
ApplicationId appId ()
Returns application ID for the CLI.
boolean outputJson ()
Indicates whether JSON format should be output.
Object doExecute () throws Exception
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.cli.net.DevicesListCommand
static List< Device > getSortedDevices (DeviceService service)
Returns the list of devices sorted using the device ID URIs.
Static Public Member Functions inherited from org.onosproject.cli.AbstractShellCommand
static< T > T get (Class< T > serviceClass)
Returns the reference to the implementation of the specified service.
static String annotations (Annotations annotations)
Produces a string image of the specified key/value annotations.
static ObjectNode annotations (ObjectMapper mapper, Annotations annotations)
Produces a JSON object from the specified key/value annotations.
Detailed Description
Lists all ports or all ports of a device.
Definition at line 46 of file DevicePortsListCommand.java.
Member Function Documentation
void org.onosproject.cli.net.DevicePortsListCommand.execute () protected virtual
Executes this command.
Implements org.onosproject.cli.AbstractShellCommand.
Definition at line 66 of file DevicePortsListCommand.java.
References create-flow.device, and find-flow.deviceId.
JsonNode org.onosproject.cli.net.DevicePortsListCommand.jsonPorts (DeviceService service, Iterable< Device > devices)
Produces JSON array containing ports of the specified devices.
Parameters
service device service
devices collection of devices
Returns
JSON array
Definition at line 96 of file DevicePortsListCommand.java.
References create-flow.device.
JsonNode org.onosproject.cli.net.DevicePortsListCommand.jsonPorts (DeviceService service, ObjectMapper mapper, Device device)
Produces JSON array containing ports of the specified device.
Parameters
service device service
mapper object mapper
device infrastructure devices
Returns
JSON array
Definition at line 113 of file DevicePortsListCommand.java.
References org.onosproject.net.device.DeviceService.getPorts(), org.onosproject.net.Device.id(), and obeliskHostCheck.port.
void org.onosproject.cli.net.DevicePortsListCommand.printDevice (DeviceService service, Device device) protected
Definition at line 142 of file DevicePortsListCommand.java.
References create-flow.device, org.onlab.util.Frequency.ofGHz(), obeliskHostCheck.port, org.onosproject.cli.Comparators.PORT_COMPARATOR, and org.onosproject.net.DefaultPort.portSpeed().
The documentation for this class was generated from the following file:
cli/src/main/java/org/onosproject/cli/net/DevicePortsListCommand.java