onos: org.onosproject.net.behaviour.DefaultTunnelDescription Class Reference
org.onosproject.net.behaviour.DefaultTunnelDescription Class Reference
Default implementation of immutable tunnel description entity.
Public Member Functions
DefaultTunnelDescription (TunnelEndPoint src, TunnelEndPoint dst, Type type, TunnelName tunnelName, SparseAnnotations...annotations)
Creates a tunnel description using the supplied information.
TunnelEndPoint src ()
Returns the connection point source.
TunnelEndPoint dst ()
Returns the connection point destination.
Type type ()
Returns the tunnel type.
TunnelName tunnelName ()
Return the name of a tunnel.
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractDescription
SparseAnnotations annotations ()
Returns the key/value annotations.
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractDescription
AbstractDescription ()
AbstractDescription (SparseAnnotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of immutable tunnel description entity.
Definition at line 28 of file DefaultTunnelDescription.java.
Constructor & Destructor Documentation
org.onosproject.net.behaviour.DefaultTunnelDescription.DefaultTunnelDescription (TunnelEndPoint src, TunnelEndPoint dst, Type type, TunnelName tunnelName, SparseAnnotations... annotations)
Creates a tunnel description using the supplied information.
Parameters
src TunnelPoint source
dst TunnelPoint destination
type tunnel type
tunnelName tunnel name
annotations optional key/value annotations
Definition at line 47 of file DefaultTunnelDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.behaviour.DefaultTunnelDescription.dst(), org.onosproject.net.behaviour.DefaultTunnelDescription.src(), org.onosproject.net.behaviour.DefaultTunnelDescription.tunnelName(), and org.onosproject.net.behaviour.DefaultTunnelDescription.type().
Member Function Documentation
TunnelEndPoint org.onosproject.net.behaviour.DefaultTunnelDescription.dst ()
Returns the connection point destination.
Returns
tunnel destination
Implements org.onosproject.net.behaviour.TunnelDescription.
Definition at line 64 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.net.behaviour.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.net.behaviour.DefaultTunnelDescription.toString().
TunnelEndPoint org.onosproject.net.behaviour.DefaultTunnelDescription.src ()
Returns the connection point source.
Returns
tunnel source ConnectionPoint
Implements org.onosproject.net.behaviour.TunnelDescription.
Definition at line 59 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.net.behaviour.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.net.behaviour.DefaultTunnelDescription.toString().
String org.onosproject.net.behaviour.DefaultTunnelDescription.toString ()
Definition at line 79 of file DefaultTunnelDescription.java.
References org.onosproject.net.behaviour.DefaultTunnelDescription.dst(), org.onosproject.net.behaviour.DefaultTunnelDescription.src(), org.onosproject.net.behaviour.DefaultTunnelDescription.tunnelName(), and org.onosproject.net.behaviour.DefaultTunnelDescription.type().
TunnelName org.onosproject.net.behaviour.DefaultTunnelDescription.tunnelName ()
Return the name of a tunnel.
Returns
Tunnel Name
Implements org.onosproject.net.behaviour.TunnelDescription.
Definition at line 74 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.net.behaviour.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.net.behaviour.DefaultTunnelDescription.toString().
Type org.onosproject.net.behaviour.DefaultTunnelDescription.type ()
Returns the tunnel type.
Returns
tunnel type
Implements org.onosproject.net.behaviour.TunnelDescription.
Definition at line 69 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.net.behaviour.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.net.behaviour.DefaultTunnelDescription.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/behaviour/DefaultTunnelDescription.java