onos: org.onosproject.store.cluster.messaging.ClusterMessage Class Reference
org.onosproject.store.cluster.messaging.ClusterMessage Class Reference
Base message for cluster-wide communications.
Public Member Functions
ClusterMessage (NodeId sender, MessageSubject subject, byte[] payload)
Creates a cluster message.
NodeId sender ()
Returns the id of the controller sending this message.
MessageSubject subject ()
Returns the message subject indicator.
byte[] payload ()
Returns the message payload.
void respond (byte[] data)
Records the response to be sent to the sender.
byte[] response ()
Returns the response to be sent to the sender.
String toString ()
boolean equals (Object o)
byte[] getBytes ()
Serializes this instance.
int hashCode ()
Static Public Member Functions
static ClusterMessage fromBytes (byte[] bytes)
Decodes a new ClusterMessage from raw bytes.
Detailed Description
Base message for cluster-wide communications.
Definition at line 32 of file ClusterMessage.java.
Constructor & Destructor Documentation
org.onosproject.store.cluster.messaging.ClusterMessage.ClusterMessage (NodeId sender, MessageSubject subject, byte[] payload)
Creates a cluster message.
Parameters
sender message sender
subject message subject
payload message payload
Definition at line 46 of file ClusterMessage.java.
References org.onosproject.store.cluster.messaging.ClusterMessage.payload(), org.onosproject.store.cluster.messaging.ClusterMessage.sender(), and org.onosproject.store.cluster.messaging.ClusterMessage.subject().
Referenced by org.onosproject.store.cluster.messaging.ClusterMessage.equals(), and org.onosproject.store.cluster.messaging.ClusterMessage.fromBytes().
Member Function Documentation
boolean org.onosproject.store.cluster.messaging.ClusterMessage.equals (Object o)
Definition at line 107 of file ClusterMessage.java.
References org.onosproject.store.cluster.messaging.ClusterMessage.ClusterMessage().
static ClusterMessage org.onosproject.store.cluster.messaging.ClusterMessage.fromBytes (byte[] bytes) static
Decodes a new ClusterMessage from raw bytes.
Parameters
bytes raw bytes
Returns
cluster message
Definition at line 142 of file ClusterMessage.java.
References org.onosproject.store.cluster.messaging.ClusterMessage.ClusterMessage().
byte [] org.onosproject.store.cluster.messaging.ClusterMessage.getBytes ()
Serializes this instance.
Returns
bytes
Definition at line 123 of file ClusterMessage.java.
References find-link-in-cluster.length, and org.onosproject.store.cluster.messaging.ClusterMessage.payload().
int org.onosproject.store.cluster.messaging.ClusterMessage.hashCode ()
Definition at line 157 of file ClusterMessage.java.
References org.onosproject.store.cluster.messaging.ClusterMessage.payload(), org.onosproject.store.cluster.messaging.ClusterMessage.sender(), and org.onosproject.store.cluster.messaging.ClusterMessage.subject().
byte [] org.onosproject.store.cluster.messaging.ClusterMessage.payload ()
Returns the message payload.
Returns
message payload.
Definition at line 75 of file ClusterMessage.java.
Referenced by org.onosproject.store.cluster.messaging.ClusterMessage.ClusterMessage(), org.onosproject.store.cluster.messaging.ClusterMessage.getBytes(), org.onosproject.store.cluster.messaging.ClusterMessage.hashCode(), and org.onosproject.store.cluster.messaging.ClusterMessage.toString().
void org.onosproject.store.cluster.messaging.ClusterMessage.respond (byte[] data)
Records the response to be sent to the sender.
Parameters
data response payload
Definition at line 84 of file ClusterMessage.java.
References org.onosproject.store.cluster.messaging.ClusterMessage.response().
byte [] org.onosproject.store.cluster.messaging.ClusterMessage.response ()
Returns the response to be sent to the sender.
Returns
response bytes
Definition at line 93 of file ClusterMessage.java.
Referenced by org.onosproject.store.cluster.messaging.ClusterMessage.respond().
NodeId org.onosproject.store.cluster.messaging.ClusterMessage.sender ()
Returns the id of the controller sending this message.
Returns
message sender id.
Definition at line 57 of file ClusterMessage.java.
Referenced by org.onosproject.store.cluster.messaging.ClusterMessage.ClusterMessage(), org.onosproject.store.cluster.messaging.ClusterMessage.hashCode(), and org.onosproject.store.cluster.messaging.ClusterMessage.toString().
MessageSubject org.onosproject.store.cluster.messaging.ClusterMessage.subject ()
Returns the message subject indicator.
Returns
message subject
Definition at line 66 of file ClusterMessage.java.
Referenced by org.onosproject.store.cluster.messaging.ClusterMessage.ClusterMessage(), org.onosproject.store.cluster.messaging.ClusterMessage.hashCode(), and org.onosproject.store.cluster.messaging.ClusterMessage.toString().
String org.onosproject.store.cluster.messaging.ClusterMessage.toString ()
Definition at line 98 of file ClusterMessage.java.
References org.onlab.util.ByteArraySizeHashPrinter.of(), org.onosproject.store.cluster.messaging.ClusterMessage.payload(), org.onosproject.store.cluster.messaging.ClusterMessage.sender(), and org.onosproject.store.cluster.messaging.ClusterMessage.subject().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/store/cluster/messaging/ClusterMessage.java