onos: org.onosproject.store.group.impl.DistributedGroupStore Class Reference
org.onosproject.store.group.impl.DistributedGroupStore Class Reference
Manages inventory of group entries using trivial in-memory implementation.
Classes
class GroupStoreIdMapKey
class GroupStoreKeyMapKey
class GroupStoreMapKey
Flattened map key to be used to store group entries.
Public Member Functions
void activate ()
void deactivate ()
int getGroupCount (DeviceId deviceId)
Returns the number of groups for the specified device in the store.
Iterable< Group > getGroups (DeviceId deviceId)
Returns the groups associated with a device.
Group getGroup (DeviceId deviceId, GroupKey appCookie)
Returns the stored group entry.
Group getGroup (DeviceId deviceId, GroupId groupId)
Returns the stored group entry for an id.
void storeGroupDescription (GroupDescription groupDesc)
Stores a new group entry using the information from group description.
void updateGroupDescription (DeviceId deviceId, GroupKey oldAppCookie, UpdateType type, GroupBuckets newBuckets, GroupKey newAppCookie)
Updates the existing group entry with the information from group description.
void deleteGroupDescription (DeviceId deviceId, GroupKey appCookie)
Triggers deleting the existing group entry.
void addOrUpdateGroupEntry (Group group)
Stores a new group entry, or updates an existing entry.
void removeGroupEntry (Group group)
Removes the group entry from store.
void deviceInitialAuditCompleted (DeviceId deviceId, boolean completed)
Indicates the first group audit is completed.
boolean deviceInitialAuditStatus (DeviceId deviceId)
Retrieves the initial group audit status for a device.
void groupOperationFailed (DeviceId deviceId, GroupOperation operation)
Indicates the group operations failed.
void addOrUpdateExtraneousGroupEntry (Group group)
A group entry that is present in switch but not in the store.
void removeExtraneousGroupEntry (Group group)
Remove the group entry from extraneous database.
Iterable< Group > getExtraneousGroups (DeviceId deviceId)
Returns the extraneous groups associated with a device.
void pushGroupMetrics (DeviceId deviceId, Collection< Group > groupEntries)
Submits the group metrics to store for a given device ID.
Protected Attributes
ClusterCommunicationService clusterCommunicator
ClusterService clusterService
StorageService storageService
MastershipService mastershipService
Detailed Description
Manages inventory of group entries using trivial in-memory implementation.
Definition at line 89 of file DistributedGroupStore.java.
Member Function Documentation
void org.onosproject.store.group.impl.DistributedGroupStore.activate ()
Definition at line 134 of file DistributedGroupStore.java.
References org.onosproject.store.serializers.KryoNamespaces.API, and org.onosproject.store.group.impl.GroupStoreMessageSubjects.REMOTE_GROUP_OP_REQUEST.
void org.onosproject.store.group.impl.DistributedGroupStore.addOrUpdateExtraneousGroupEntry (Group group)
A group entry that is present in switch but not in the store.
Parameters
group group entry
Implements org.onosproject.net.group.GroupStore.
Definition at line 932 of file DistributedGroupStore.java.
References org.onosproject.net.group.GroupDescription.deviceId().
void org.onosproject.store.group.impl.DistributedGroupStore.addOrUpdateGroupEntry (Group group)
Stores a new group entry, or updates an existing entry.
Parameters
group group entry
Implements org.onosproject.net.group.GroupStore.
Definition at line 748 of file DistributedGroupStore.java.
References org.onosproject.net.group.Group.GroupState.ADDED, org.onosproject.net.group.GroupDescription.buckets(), org.onosproject.net.group.GroupDescription.deviceId(), org.onosproject.net.group.GroupEvent.Type.GROUP_ADDED, org.onosproject.net.group.GroupEvent.Type.GROUP_UPDATED, org.onosproject.net.group.Group.GroupState.PENDING_ADD, org.onosproject.net.group.Group.GroupState.PENDING_ADD_RETRY, org.onosproject.net.group.Group.GroupState.PENDING_UPDATE, and org.onosproject.net.group.Group.state().
void org.onosproject.store.group.impl.DistributedGroupStore.deactivate ()
Definition at line 198 of file DistributedGroupStore.java.
References org.onosproject.store.group.impl.GroupStoreMessageSubjects.REMOTE_GROUP_OP_REQUEST.
void org.onosproject.store.group.impl.DistributedGroupStore.deleteGroupDescription (DeviceId deviceId, GroupKey appCookie)
Triggers deleting the existing group entry.
Parameters
deviceId the device ID
appCookie the group key
Implements org.onosproject.net.group.GroupStore.
Definition at line 686 of file DistributedGroupStore.java.
References find-flow.deviceId, org.onosproject.mastership.MastershipService.getMasterFor(), org.onosproject.net.MastershipRole.MASTER, org.onosproject.store.group.impl.DistributedGroupStore.mastershipService, and org.onosproject.store.group.impl.GroupStoreMessageSubjects.REMOTE_GROUP_OP_REQUEST.
void org.onosproject.store.group.impl.DistributedGroupStore.deviceInitialAuditCompleted (DeviceId deviceId, boolean completed)
Indicates the first group audit is completed.
Parameters
deviceId the device ID
completed initial audit status
Implements org.onosproject.net.group.GroupStore.
Definition at line 839 of file DistributedGroupStore.java.
References find-flow.deviceId.
Referenced by org.onosproject.store.group.impl.DistributedGroupStore.pushGroupMetrics().
boolean org.onosproject.store.group.impl.DistributedGroupStore.deviceInitialAuditStatus (DeviceId deviceId)
Retrieves the initial group audit status for a device.
Parameters
deviceId the device ID
Returns
initial group audit status
Implements org.onosproject.net.group.GroupStore.
Definition at line 878 of file DistributedGroupStore.java.
References find-flow.deviceId.
Referenced by org.onosproject.store.group.impl.DistributedGroupStore.pushGroupMetrics().
Iterable<Group> org.onosproject.store.group.impl.DistributedGroupStore.getExtraneousGroups (DeviceId deviceId)
Returns the extraneous groups associated with a device.
Parameters
deviceId the device ID
Returns
the extraneous group entries
Implements org.onosproject.net.group.GroupStore.
Definition at line 954 of file DistributedGroupStore.java.
Referenced by org.onosproject.store.group.impl.DistributedGroupStore.pushGroupMetrics().
Group org.onosproject.store.group.impl.DistributedGroupStore.getGroup (DeviceId deviceId, GroupKey appCookie)
Returns the stored group entry.
Parameters
deviceId the device ID
appCookie the group key
Returns
a group associated with the key
Implements org.onosproject.net.group.GroupStore.
Definition at line 300 of file DistributedGroupStore.java.
Referenced by org.onosproject.store.group.impl.DistributedGroupStore.pushGroupMetrics(), and org.onosproject.store.group.impl.DistributedGroupStore.storeGroupDescription().
Group org.onosproject.store.group.impl.DistributedGroupStore.getGroup (DeviceId deviceId, GroupId groupId)
Returns the stored group entry for an id.
Parameters
deviceId the device ID
groupId the group identifier
Returns
a group associated with the key
Implements org.onosproject.net.group.GroupStore.
Definition at line 311 of file DistributedGroupStore.java.
int org.onosproject.store.group.impl.DistributedGroupStore.getGroupCount (DeviceId deviceId)
Returns the number of groups for the specified device in the store.
Returns
number of groups for the specified device
Implements org.onosproject.net.group.GroupStore.
Definition at line 265 of file DistributedGroupStore.java.
References org.onosproject.store.group.impl.DistributedGroupStore.getGroups().
Iterable<Group> org.onosproject.store.group.impl.DistributedGroupStore.getGroups (DeviceId deviceId)
Returns the groups associated with a device.
Parameters
deviceId the device ID
Returns
the group entries
Implements org.onosproject.net.group.GroupStore.
Definition at line 278 of file DistributedGroupStore.java.
Referenced by org.onosproject.store.group.impl.DistributedGroupStore.getGroupCount().
void org.onosproject.store.group.impl.DistributedGroupStore.groupOperationFailed (DeviceId deviceId, GroupOperation operation)
Indicates the group operations failed.
Parameters
deviceId the device ID
operation the group operation failed
Implements org.onosproject.net.group.GroupStore.
Definition at line 886 of file DistributedGroupStore.java.
References org.onosproject.net.group.GroupDescription.deviceId(), org.onosproject.net.group.GroupEvent.Type.GROUP_ADD_FAILED, org.onosproject.net.group.GroupEvent.Type.GROUP_REMOVE_FAILED, org.onosproject.net.group.GroupEvent.Type.GROUP_UPDATE_FAILED, org.onosproject.net.group.Group.id(), org.onosproject.net.group.Group.GroupState.PENDING_ADD, and org.onosproject.net.group.Group.state().
void org.onosproject.store.group.impl.DistributedGroupStore.pushGroupMetrics (DeviceId deviceId, Collection< Group > groupEntries)
Submits the group metrics to store for a given device ID.
Parameters
deviceId the device ID
groupEntries the group entries as received from southbound
Implements org.onosproject.net.group.GroupStore.
Definition at line 1142 of file DistributedGroupStore.java.
References find-flow.deviceId, org.onosproject.store.group.impl.DistributedGroupStore.deviceInitialAuditCompleted(), org.onosproject.store.group.impl.DistributedGroupStore.deviceInitialAuditStatus(), org.onosproject.store.group.impl.DistributedGroupStore.getExtraneousGroups(), org.onosproject.store.group.impl.DistributedGroupStore.getGroup(), and org.onosproject.store.group.impl.DistributedGroupStore.removeExtraneousGroupEntry().
void org.onosproject.store.group.impl.DistributedGroupStore.removeExtraneousGroupEntry (Group group)
Remove the group entry from extraneous database.
Parameters
group group entry
Implements org.onosproject.net.group.GroupStore.
Definition at line 944 of file DistributedGroupStore.java.
References org.onosproject.net.group.GroupDescription.deviceId().
Referenced by org.onosproject.store.group.impl.DistributedGroupStore.pushGroupMetrics().
void org.onosproject.store.group.impl.DistributedGroupStore.removeGroupEntry (Group group)
Removes the group entry from store.
Parameters
group group entry
Implements org.onosproject.net.group.GroupStore.
Definition at line 817 of file DistributedGroupStore.java.
References org.onosproject.net.group.GroupDescription.deviceId(), and org.onosproject.net.group.GroupEvent.Type.GROUP_REMOVED.
void org.onosproject.store.group.impl.DistributedGroupStore.storeGroupDescription (GroupDescription groupDesc)
Stores a new group entry using the information from group description.
Parameters
groupDesc group description to be used to create group entry
Implements org.onosproject.net.group.GroupStore.
Definition at line 348 of file DistributedGroupStore.java.
References org.onosproject.net.group.GroupDescription.deviceId(), org.onosproject.store.group.impl.DistributedGroupStore.getGroup(), org.onosproject.mastership.MastershipService.getLocalRole(), org.onosproject.mastership.MastershipService.getMasterFor(), org.onosproject.net.MastershipRole.MASTER, org.onosproject.store.group.impl.DistributedGroupStore.mastershipService, and org.onosproject.store.group.impl.GroupStoreMessageSubjects.REMOTE_GROUP_OP_REQUEST.
void org.onosproject.store.group.impl.DistributedGroupStore.updateGroupDescription (DeviceId deviceId, GroupKey oldAppCookie, UpdateType type, GroupBuckets newBuckets, GroupKey newAppCookie)
Updates the existing group entry with the information from group description.
Parameters
deviceId the device ID
oldAppCookie the current group key
type update type
newBuckets group buckets for updates
newAppCookie optional new group key
Implements org.onosproject.net.group.GroupStore.
Definition at line 548 of file DistributedGroupStore.java.
References find-flow.deviceId, org.onosproject.mastership.MastershipService.getMasterFor(), org.onosproject.net.MastershipRole.MASTER, org.onosproject.store.group.impl.DistributedGroupStore.mastershipService, and org.onosproject.store.group.impl.GroupStoreMessageSubjects.REMOTE_GROUP_OP_REQUEST.
Member Data Documentation
ClusterCommunicationService org.onosproject.store.group.impl.DistributedGroupStore.clusterCommunicator protected
Definition at line 99 of file DistributedGroupStore.java.
ClusterService org.onosproject.store.group.impl.DistributedGroupStore.clusterService protected
Definition at line 102 of file DistributedGroupStore.java.
MastershipService org.onosproject.store.group.impl.DistributedGroupStore.mastershipService protected
Definition at line 108 of file DistributedGroupStore.java.
Referenced by org.onosproject.store.group.impl.DistributedGroupStore.deleteGroupDescription(), org.onosproject.store.group.impl.DistributedGroupStore.storeGroupDescription(), and org.onosproject.store.group.impl.DistributedGroupStore.updateGroupDescription().
StorageService org.onosproject.store.group.impl.DistributedGroupStore.storageService protected
Definition at line 105 of file DistributedGroupStore.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/group/impl/DistributedGroupStore.java