onos: org.onosproject.net.host.impl.HostMonitorTest Class Reference
org.onosproject.net.host.impl.HostMonitorTest Class Reference
Classes
class TestDeviceService
class TestPacketService
Public Member Functions
void setUp ()
void shutdown ()
void testMonitorIpv4HostExists () throws Exception
void testMonitorIpv6HostExists () throws Exception
void testMonitorIpv4HostDoesNotExist () throws Exception
void testMonitorIpv6HostDoesNotExist () throws Exception
void testMonitorIpv4HostDoesNotExistWithVlan () throws Exception
void testMonitorIpv6HostDoesNotExistWithVlan () throws Exception
Detailed Description
Definition at line 67 of file HostMonitorTest.java.
Member Function Documentation
void org.onosproject.net.host.impl.HostMonitorTest.setUp ()
Definition at line 90 of file HostMonitorTest.java.
References org.onosproject.net.edge.EdgePortService.isEdgePoint().
void org.onosproject.net.host.impl.HostMonitorTest.shutdown ()
Definition at line 98 of file HostMonitorTest.java.
void org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExist () throws Exception
Definition at line 161 of file HostMonitorTest.java.
References create-flow.device, org.onosproject.net.host.impl.HostManager.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getMatchingInterface(), org.onlab.packet.BasePacket.getPayload(), org.onlab.packet.Ethernet.getVlanID(), org.onlab.packet.VlanId.NONE, obeliskHostCheck.port, onos.size, org.onlab.packet.MacAddress.toBytes(), org.onlab.packet.IpAddress.toOctets(), and org.onlab.packet.Ethernet.VLAN_UNTAGGED.
void org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExistWithVlan () throws Exception
Definition at line 298 of file HostMonitorTest.java.
References create-flow.device, org.onosproject.net.host.impl.HostManager.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getMatchingInterface(), org.onlab.packet.BasePacket.getPayload(), org.onlab.packet.Ethernet.getVlanID(), org.onosproject.net.Device.id(), obeliskHostCheck.port, onos.size, org.onlab.packet.MacAddress.toBytes(), and org.onlab.packet.IpAddress.toOctets().
void org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostExists () throws Exception
Definition at line 103 of file HostMonitorTest.java.
References org.onosproject.net.host.impl.HostManager.getHostsByIp(), org.onosproject.net.provider.Provider.id(), and org.onosproject.net.Provided.providerId().
void org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExist () throws Exception
Definition at line 229 of file HostMonitorTest.java.
References create-flow.device, org.onosproject.net.host.impl.HostManager.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getMatchingInterface(), org.onlab.packet.BasePacket.getPayload(), org.onlab.packet.Ethernet.getVlanID(), org.onlab.packet.VlanId.NONE, obeliskHostCheck.port, onos.size, org.onlab.packet.MacAddress.toBytes(), org.onlab.packet.IpAddress.toOctets(), and org.onlab.packet.Ethernet.VLAN_UNTAGGED.
void org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExistWithVlan () throws Exception
Definition at line 367 of file HostMonitorTest.java.
References create-flow.device, org.onosproject.net.host.impl.HostManager.getHostsByIp(), org.onosproject.incubator.net.intf.InterfaceService.getMatchingInterface(), org.onlab.packet.BasePacket.getPayload(), org.onlab.packet.Ethernet.getVlanID(), org.onosproject.net.Device.id(), obeliskHostCheck.port, onos.size, org.onlab.packet.MacAddress.toBytes(), and org.onlab.packet.IpAddress.toOctets().
void org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostExists () throws Exception
Definition at line 132 of file HostMonitorTest.java.
References org.onosproject.net.host.impl.HostManager.getHostsByIp(), org.onosproject.net.provider.Provider.id(), and org.onosproject.net.Provided.providerId().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/host/impl/HostMonitorTest.java