onos: org.onosproject.openflow.controller.impl.OpenFlowControllerImpl Class Reference
org.onosproject.openflow.controller.impl.OpenFlowControllerImpl Class Reference
Classes
class OFMessageHandler
class OpenFlowSwitchAgent
Implementation of an OpenFlow Agent which is responsible for keeping track of connected switches and the state in which they are.
Public Member Functions
void activate (ComponentContext context)
void deactivate ()
void modified (ComponentContext context)
Iterable< OpenFlowSwitch > getSwitches ()
Returns all switches known to this OF controller.
Iterable< OpenFlowSwitch > getMasterSwitches ()
Returns all master switches known to this OF controller.
Iterable< OpenFlowSwitch > getEqualSwitches ()
Returns all equal switches known to this OF controller.
OpenFlowSwitch getSwitch (Dpid dpid)
Returns the actual switch for the given Dpid.
OpenFlowSwitch getMasterSwitch (Dpid dpid)
Returns the actual master switch for the given Dpid, if one exists.
OpenFlowSwitch getEqualSwitch (Dpid dpid)
Returns the actual equal switch for the given Dpid, if one exists.
void addListener (OpenFlowSwitchListener listener)
Register a listener for meta events that occur to OF devices.
void removeListener (OpenFlowSwitchListener listener)
Unregister a listener.
void addPacketListener (int priority, PacketListener listener)
Register a listener for packet events.
void removePacketListener (PacketListener listener)
Unregister a listener.
void addEventListener (OpenFlowEventListener listener)
Register a listener for OF msg events.
void removeEventListener (OpenFlowEventListener listener)
Unregister a listener.
void write (Dpid dpid, OFMessage msg)
Send a message to a particular switch.
void processPacket (Dpid dpid, OFMessage msg)
Process a message and notify the appropriate listeners.
void setRole (Dpid dpid, RoleState role)
Sets the role for a given switch.
Protected Attributes
DriverService driverService
DefaultDriverProviderService defaultDriverProviderService
ComponentConfigService cfgService
ExecutorService executorMsgs
ConcurrentHashMap< Dpid,
OpenFlowSwitch > connectedSwitches
ConcurrentHashMap< Dpid,
OpenFlowSwitch > activeMasterSwitches
ConcurrentHashMap< Dpid,
OpenFlowSwitch > activeEqualSwitches
OpenFlowSwitchAgent agent = new OpenFlowSwitchAgent()
Set< OpenFlowSwitchListener > ofSwitchListener = new CopyOnWriteArraySet<>()
Multimap< Integer, PacketListener > ofPacketListener
Set< OpenFlowEventListener > ofEventListener = new CopyOnWriteArraySet<>()
Multimap< Dpid, OFFlowStatsEntry > fullFlowStats
Multimap< Dpid, OFTableStatsEntry > fullTableStats
Multimap< Dpid, OFGroupStatsEntry > fullGroupStats
Multimap< Dpid,
OFGroupDescStatsEntry > fullGroupDescStats
Multimap< Dpid, OFPortStatsEntry > fullPortStats
Detailed Description
Definition at line 85 of file OpenFlowControllerImpl.java.
Member Function Documentation
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.activate (ComponentContext context)
Definition at line 149 of file OpenFlowControllerImpl.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.agent, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.driverService.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.addEventListener (OpenFlowEventListener listener)
Register a listener for OF msg events.
Parameters
listener the listener to notify
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 221 of file OpenFlowControllerImpl.java.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.addListener (OpenFlowSwitchListener listener)
Register a listener for meta events that occur to OF devices.
Parameters
listener the listener to notify
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 199 of file OpenFlowControllerImpl.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.ofSwitchListener.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.addPacketListener (int priority, PacketListener listener)
Register a listener for packet events.
Parameters
priority the importance of this listener, lower values are more important
listener the listener to notify
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 211 of file OpenFlowControllerImpl.java.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.deactivate ()
Definition at line 156 of file OpenFlowControllerImpl.java.
OpenFlowSwitch org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getEqualSwitch (Dpid dpid)
Returns the actual equal switch for the given Dpid, if one exists.
Parameters
dpid the switch to fetch
Returns
the interface to this switch
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 194 of file OpenFlowControllerImpl.java.
References obeliskHostCheck.dpid.
Iterable<OpenFlowSwitch> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getEqualSwitches ()
Returns all equal switches known to this OF controller.
Returns
Iterable of dpid elements
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 179 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testEqualSwitch(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testMasterSwitch().
OpenFlowSwitch org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getMasterSwitch (Dpid dpid)
Returns the actual master switch for the given Dpid, if one exists.
Parameters
dpid the switch to fetch
Returns
the interface to this switch
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 189 of file OpenFlowControllerImpl.java.
References obeliskHostCheck.dpid.
Iterable<OpenFlowSwitch> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getMasterSwitches ()
Returns all master switches known to this OF controller.
Returns
Iterable of dpid elements
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 174 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testEqualSwitch(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testMasterSwitch().
OpenFlowSwitch org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getSwitch (Dpid dpid)
Returns the actual switch for the given Dpid.
Parameters
dpid the switch to fetch
Returns
the interface to this switch
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 184 of file OpenFlowControllerImpl.java.
References obeliskHostCheck.dpid.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.processPacket(), org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.setRole(), org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.transitionToEqualSwitch(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.transitionToMasterSwitch().
Iterable<OpenFlowSwitch> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getSwitches ()
Returns all switches known to this OF controller.
Returns
Iterable of dpid elements
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 169 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testAddRemoveConnectedSwitch().
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.modified (ComponentContext context)
Definition at line 162 of file OpenFlowControllerImpl.java.
References org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.agent, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.driverService.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.processPacket (Dpid dpid, OFMessage msg)
Process a message and notify the appropriate listeners.
Parameters
dpid the dpid the message arrived on
msg the message to process.
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 236 of file OpenFlowControllerImpl.java.
References obeliskHostCheck.dpid, org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getSwitch(), org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.ofPacketListener, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.ofSwitchListener.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.processMessage().
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.removeEventListener (OpenFlowEventListener listener)
Unregister a listener.
Parameters
listener the listener to unregister
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 226 of file OpenFlowControllerImpl.java.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.removeListener (OpenFlowSwitchListener listener)
Unregister a listener.
Parameters
listener the listener to unregister
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 206 of file OpenFlowControllerImpl.java.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.removePacketListener (PacketListener listener)
Unregister a listener.
Parameters
listener the listener to unregister
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 216 of file OpenFlowControllerImpl.java.
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.setRole (Dpid dpid, RoleState role)
Sets the role for a given switch.
Parameters
role the desired role
dpid the switch to set the role for.
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 453 of file OpenFlowControllerImpl.java.
References obeliskHostCheck.dpid, and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.getSwitch().
void org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.write (Dpid dpid, OFMessage msg)
Send a message to a particular switch.
Parameters
dpid the switch to send to.
msg the message to send
Implements org.onosproject.openflow.controller.OpenFlowController.
Definition at line 231 of file OpenFlowControllerImpl.java.
References obeliskHostCheck.dpid.
Member Data Documentation
ConcurrentHashMap<Dpid, OpenFlowSwitch> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.activeEqualSwitches protected
Initial value:
=
            new ConcurrentHashMap<>()
Definition at line 120 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.transitionToEqualSwitch().
ConcurrentHashMap<Dpid, OpenFlowSwitch> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.activeMasterSwitches protected
Initial value:
=
            new ConcurrentHashMap<>()
Definition at line 118 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.transitionToMasterSwitch(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.validActivation().
OpenFlowSwitchAgent org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.agent = new OpenFlowSwitchAgent() protected
Definition at line 123 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.activate(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.modified().
ComponentConfigService org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.cfgService protected
Definition at line 100 of file OpenFlowControllerImpl.java.
ConcurrentHashMap<Dpid, OpenFlowSwitch> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.connectedSwitches protected
Initial value:
=
            new ConcurrentHashMap<>()
Definition at line 116 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.addConnectedSwitch(), org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testAddRemoveConnectedSwitch(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.validActivation().
DefaultDriverProviderService org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.defaultDriverProviderService protected
Definition at line 97 of file OpenFlowControllerImpl.java.
DriverService org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.driverService protected
Definition at line 93 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.activate(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.modified().
ExecutorService org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.executorMsgs protected
Initial value:
=
        Executors.newFixedThreadPool(32, groupedThreads("onos/of", "event-stats-%d"))
Definition at line 110 of file OpenFlowControllerImpl.java.
Multimap<Dpid, OFFlowStatsEntry> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.fullFlowStats protected
Initial value:
=
            ArrayListMultimap.create()
Definition at line 131 of file OpenFlowControllerImpl.java.
Multimap<Dpid, OFGroupDescStatsEntry> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.fullGroupDescStats protected
Initial value:
=
            ArrayListMultimap.create()
Definition at line 140 of file OpenFlowControllerImpl.java.
Multimap<Dpid, OFGroupStatsEntry> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.fullGroupStats protected
Initial value:
=
            ArrayListMultimap.create()
Definition at line 137 of file OpenFlowControllerImpl.java.
Multimap<Dpid, OFPortStatsEntry> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.fullPortStats protected
Initial value:
=
            ArrayListMultimap.create()
Definition at line 143 of file OpenFlowControllerImpl.java.
Multimap<Dpid, OFTableStatsEntry> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.fullTableStats protected
Initial value:
=
            ArrayListMultimap.create()
Definition at line 134 of file OpenFlowControllerImpl.java.
Set<OpenFlowEventListener> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.ofEventListener = new CopyOnWriteArraySet<>() protected
Definition at line 129 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OFMessageHandler.run().
Multimap<Integer, PacketListener> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.ofPacketListener protected
Initial value:
=
            ArrayListMultimap.create()
Definition at line 126 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.processPacket().
Set<OpenFlowSwitchListener> org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.ofSwitchListener = new CopyOnWriteArraySet<>() protected
Definition at line 124 of file OpenFlowControllerImpl.java.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.addConnectedSwitch(), org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.addListener(), org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.processPacket(), org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.removeConnectedSwitch(), and org.onosproject.openflow.controller.impl.OpenFlowControllerImpl.OpenFlowSwitchAgent.returnRoleReply().
The documentation for this class was generated from the following file:
protocols/openflow/ctl/src/main/java/org/onosproject/openflow/controller/impl/OpenFlowControllerImpl.java