onos: org.onlab.packet.LLDPOrganizationalTLV Class Reference
org.onlab.packet.LLDPOrganizationalTLV Class Reference
The class representing LLDP Organizationally Specific TLV.
Public Member Functions
LLDPOrganizationalTLV ()
LLDPOrganizationalTLV setOUI (final byte[] oui)
Set the value of OUI.
byte[] getOUI ()
Returns the value of the OUI.
LLDPOrganizationalTLV setSubType (final byte subType)
Set the value of sub type.
byte getSubType ()
Returns the value of the sub type.
LLDPOrganizationalTLV setInfoString (final byte[] infoString)
Set the value of information string.
LLDPOrganizationalTLV setInfoString (final String infoString)
Set the value of information string.
byte[] getInfoString ()
Returns the value of information string.
byte[] serialize ()
LLDPTLV deserialize (final ByteBuffer bb) throws DeserializationException
int hashCode ()
boolean equals (final Object o)
Public Member Functions inherited from org.onlab.packet.LLDPTLV
byte getType ()
LLDPTLV setType (final byte type)
short getLength ()
LLDPTLV setLength (final short length)
byte[] getValue ()
LLDPTLV setValue (final byte[] value)
byte[] serialize ()
LLDPTLV deserialize (final ByteBuffer bb) throws DeserializationException
int hashCode ()
boolean equals (final Object obj)
Static Public Attributes
static final int OUI_LENGTH = 3
static final int SUBTYPE_LENGTH = 1
static final byte ORGANIZATIONAL_TLV_TYPE = 127
static final int MAX_INFOSTRING_LENGTH = 507
Protected Attributes
byte[] oui
byte subType
Protected Attributes inherited from org.onlab.packet.LLDPTLV
byte type
short length
byte[] value
Detailed Description
The class representing LLDP Organizationally Specific TLV.
Definition at line 40 of file LLDPOrganizationalTLV.java.
Constructor & Destructor Documentation
org.onlab.packet.LLDPOrganizationalTLV.LLDPOrganizationalTLV ()
Definition at line 50 of file LLDPOrganizationalTLV.java.
References org.onlab.packet.LLDPOrganizationalTLV.ORGANIZATIONAL_TLV_TYPE.
Referenced by org.onlab.packet.LLDPOrganizationalTLV.equals().
Member Function Documentation
LLDPTLV org.onlab.packet.LLDPOrganizationalTLV.deserialize (final ByteBuffer bb) throws DeserializationException
Definition at line 157 of file LLDPOrganizationalTLV.java.
References org.onlab.packet.LLDPTLV.getLength(), org.onlab.packet.LLDPTLV.getType(), org.onlab.packet.LLDPOrganizationalTLV.ORGANIZATIONAL_TLV_TYPE, org.onlab.packet.LLDPOrganizationalTLV.oui, org.onlab.packet.LLDPOrganizationalTLV.OUI_LENGTH, and org.onlab.packet.LLDPOrganizationalTLV.SUBTYPE_LENGTH.
boolean org.onlab.packet.LLDPOrganizationalTLV.equals (final Object o)
Definition at line 197 of file LLDPOrganizationalTLV.java.
References org.onlab.packet.LLDPTLV.length, org.onlab.packet.LLDPOrganizationalTLV.LLDPOrganizationalTLV(), org.onlab.packet.LLDPOrganizationalTLV.oui, org.onlab.packet.LLDPOrganizationalTLV.subType, and org.onlab.packet.LLDPTLV.type.
byte [] org.onlab.packet.LLDPOrganizationalTLV.getInfoString ()
Returns the value of information string.
Returns
the value of information string.
Definition at line 137 of file LLDPOrganizationalTLV.java.
References find-link-in-cluster.length.
Referenced by org.onlab.packet.ONOSLLDP.getDeviceString(), and org.onlab.packet.ONOSLLDP.getNameString().
byte [] org.onlab.packet.LLDPOrganizationalTLV.getOUI ()
Returns the value of the OUI.
Returns
The value of the OUI .
Definition at line 76 of file LLDPOrganizationalTLV.java.
References find-link-in-cluster.length.
byte org.onlab.packet.LLDPOrganizationalTLV.getSubType ()
Returns the value of the sub type.
Returns
The value of the sub type.
Definition at line 97 of file LLDPOrganizationalTLV.java.
Referenced by org.onlab.packet.ONOSLLDP.getDeviceTLV(), and org.onlab.packet.ONOSLLDP.getNameTLV().
int org.onlab.packet.LLDPOrganizationalTLV.hashCode ()
Definition at line 185 of file LLDPOrganizationalTLV.java.
References find-link-in-cluster.length.
byte [] org.onlab.packet.LLDPOrganizationalTLV.serialize ()
Definition at line 142 of file LLDPOrganizationalTLV.java.
References find-link-in-cluster.length, org.onlab.packet.LLDPOrganizationalTLV.ORGANIZATIONAL_TLV_TYPE, and org.onlab.packet.LLDPTLV.type.
LLDPOrganizationalTLV org.onlab.packet.LLDPOrganizationalTLV.setInfoString (final byte[] infoString)
Set the value of information string.
Parameters
infoString the byte array of the value of information string.
Returns
This LLDP Organizationally Specific TLV.
Definition at line 108 of file LLDPOrganizationalTLV.java.
References find-link-in-cluster.length, and org.onlab.packet.LLDPOrganizationalTLV.MAX_INFOSTRING_LENGTH.
LLDPOrganizationalTLV org.onlab.packet.LLDPOrganizationalTLV.setInfoString (final String infoString)
Set the value of information string.
The String value is automatically converted into byte array with UTF-8 encoding.
Parameters
infoString the String value of information string.
Returns
This LLDP Organizationally Specific TLV.
Definition at line 126 of file LLDPOrganizationalTLV.java.
LLDPOrganizationalTLV org.onlab.packet.LLDPOrganizationalTLV.setOUI (final byte[] oui)
Set the value of OUI.
Parameters
oui The value of OUI to be set.
Returns
This LLDP Organizationally Specific TLV.
Definition at line 61 of file LLDPOrganizationalTLV.java.
References find-link-in-cluster.length, org.onlab.packet.LLDPOrganizationalTLV.oui, and org.onlab.packet.LLDPOrganizationalTLV.OUI_LENGTH.
LLDPOrganizationalTLV org.onlab.packet.LLDPOrganizationalTLV.setSubType (final byte subType)
Set the value of sub type.
Parameters
subType The value of sub type to be set.
Returns
This LLDP Organizationally Specific TLV.
Definition at line 87 of file LLDPOrganizationalTLV.java.
References org.onlab.packet.LLDPOrganizationalTLV.subType.
Member Data Documentation
final int org.onlab.packet.LLDPOrganizationalTLV.MAX_INFOSTRING_LENGTH = 507 static
Definition at line 44 of file LLDPOrganizationalTLV.java.
Referenced by org.onlab.packet.LLDPOrganizationalTLV.setInfoString().
final byte org.onlab.packet.LLDPOrganizationalTLV.ORGANIZATIONAL_TLV_TYPE = 127 static
Definition at line 43 of file LLDPOrganizationalTLV.java.
Referenced by org.onlab.packet.LLDPOrganizationalTLV.deserialize(), org.onlab.packet.ONOSLLDP.getDeviceTLV(), org.onlab.packet.ONOSLLDP.getNameTLV(), org.onlab.packet.LLDPOrganizationalTLV.LLDPOrganizationalTLV(), org.onlab.packet.LLDPOrganizationalTLV.serialize(), org.onlab.packet.LLDPTest.setUp(), and org.onlab.packet.LLDPTest.testDeserialize().
byte [] org.onlab.packet.LLDPOrganizationalTLV.oui protected
Definition at line 46 of file LLDPOrganizationalTLV.java.
Referenced by org.onlab.packet.LLDPOrganizationalTLV.deserialize(), org.onlab.packet.LLDPOrganizationalTLV.equals(), and org.onlab.packet.LLDPOrganizationalTLV.setOUI().
final int org.onlab.packet.LLDPOrganizationalTLV.OUI_LENGTH = 3 static
Definition at line 41 of file LLDPOrganizationalTLV.java.
Referenced by org.onlab.packet.LLDPOrganizationalTLV.deserialize(), and org.onlab.packet.LLDPOrganizationalTLV.setOUI().
byte org.onlab.packet.LLDPOrganizationalTLV.subType protected
Definition at line 47 of file LLDPOrganizationalTLV.java.
Referenced by org.onlab.packet.LLDPOrganizationalTLV.equals(), and org.onlab.packet.LLDPOrganizationalTLV.setSubType().
final int org.onlab.packet.LLDPOrganizationalTLV.SUBTYPE_LENGTH = 1 static
Definition at line 42 of file LLDPOrganizationalTLV.java.
Referenced by org.onlab.packet.LLDPOrganizationalTLV.deserialize().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/LLDPOrganizationalTLV.java