onos: org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4 Class Reference
org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4 Class Reference
BGP Update Message: UPDATE messages are used to transfer routing information between BGP peers.
Classes
class Reader
Reader reads BGP Update Message from the channel buffer.
Public Member Functions
BgpUpdateMsgVer4 (BgpHeader bgpHeader, List< IpPrefix > withdrawnRoutes, BgpPathAttributes bgpPathAttributes, List< IpPrefix > nlri)
Constructor to initialize parameters for BGP Update message.
BgpVersion getVersion ()
Returns version of BGP Message.
BgpType getType ()
Returns BGP Type of BGP Message.
void writeTo (ChannelBuffer channelBuffer) throws BgpParseException
Writes byte streams of messages to channel buffer.
BgpPathAttributes bgpPathAttributes ()
Returns path attributes in BGP Update Message.
List< IpPrefix > withdrawnRoutes ()
Returns withdrawn Routes.
List< IpPrefix > nlri ()
Returns NLRI list of prefix.
BgpHeader getHeader ()
Returns BGP Header of BGP Message.
String toString ()
Static Public Member Functions
static LinkedList< IpPrefix > parseNlri (ChannelBuffer cb) throws BgpParseException
Parses NLRI from channel buffer.
static LinkedList< IpPrefix > parseWithdrawnRoutes (ChannelBuffer cb) throws BgpParseException
Parsing withdrawn routes from channel buffer.
Static Public Attributes
static final byte PACKET_VERSION = 4
static final int PACKET_MINIMUM_LENGTH = 4
static final int BYTE_IN_BITS = 8
static final int MIN_LEN_AFTER_WITHDRW_ROUTES = 2
static final int MINIMUM_COMMON_HEADER_LENGTH = 19
static final BgpType MSG_TYPE = BgpType.UPDATE
static final
BgpUpdateMsgVer4.Reader READER = new Reader()
Static Protected Attributes
static final Logger log
Detailed Description
BGP Update Message: UPDATE messages are used to transfer routing information between BGP peers.
The information in the UPDATE message is used by core to construct a graph
Definition at line 41 of file BgpUpdateMsgVer4.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.BgpUpdateMsgVer4 (BgpHeader bgpHeader, List< IpPrefix > withdrawnRoutes, BgpPathAttributes bgpPathAttributes, List< IpPrefix > nlri)
Constructor to initialize parameters for BGP Update message.
Parameters
bgpHeader in Update message
withdrawnRoutes withdrawn routes
bgpPathAttributes BGP Path attributes
nlri Network Layer Reachability Information
Definition at line 94 of file BgpUpdateMsgVer4.java.
References org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.bgpPathAttributes(), org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.nlri(), and org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.withdrawnRoutes().
Member Function Documentation
BgpPathAttributes org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.bgpPathAttributes ()
Returns path attributes in BGP Update Message.
Returns
path attributes in BGP Update Message
Implements org.onosproject.bgpio.protocol.BgpUpdateMsg.
Definition at line 256 of file BgpUpdateMsgVer4.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.BgpUpdateMsgVer4().
BgpHeader org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.getHeader ()
Returns BGP Header of BGP Message.
Returns
BGP Header of BGP Message
Implements org.onosproject.bgpio.protocol.BgpMessage.
Definition at line 271 of file BgpUpdateMsgVer4.java.
BgpType org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.getType ()
Returns BGP Type of BGP Message.
Returns
BGP Type of BGP Message
Implements org.onosproject.bgpio.protocol.BgpMessage.
Definition at line 246 of file BgpUpdateMsgVer4.java.
References org.onosproject.bgpio.protocol.BgpType.UPDATE.
BgpVersion org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.getVersion ()
Returns version of BGP Message.
Returns
version of BGP Message
Implements org.onosproject.bgpio.protocol.BgpMessage.
Definition at line 241 of file BgpUpdateMsgVer4.java.
References org.onosproject.bgpio.protocol.BgpVersion.BGP_4.
List<IpPrefix> org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.nlri ()
Returns NLRI list of prefix.
Returns
NLRI list of prefix
Implements org.onosproject.bgpio.protocol.BgpUpdateMsg.
Definition at line 266 of file BgpUpdateMsgVer4.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.BgpUpdateMsgVer4(), org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.parseNlri(), and org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.toString().
static LinkedList<IpPrefix> org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.parseNlri (ChannelBuffer cb) throws BgpParseException static
Parses NLRI from channel buffer.
Parameters
cb channelBuffer
Returns
list of IP Prefix
Exceptions
BgpParseException while parsing NLRI
Definition at line 172 of file BgpUpdateMsgVer4.java.
References org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.BYTE_IN_BITS, find-link-in-cluster.length, org.onosproject.bgpio.types.BgpErrorType.MALFORMED_ATTRIBUTE_LIST, org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.nlri(), onosUploadBits.prefix, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
static LinkedList<IpPrefix> org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.parseWithdrawnRoutes (ChannelBuffer cb) throws BgpParseException static
Parsing withdrawn routes from channel buffer.
Parameters
cb channelBuffer
Returns
list of IP prefix
Exceptions
BgpParseException while parsing withdrawn routes
Definition at line 209 of file BgpUpdateMsgVer4.java.
References org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.BYTE_IN_BITS, find-link-in-cluster.length, org.onosproject.bgpio.types.BgpErrorType.MALFORMED_ATTRIBUTE_LIST, onosUploadBits.prefix, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.toString ()
Definition at line 276 of file BgpUpdateMsgVer4.java.
References org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.nlri(), and org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.withdrawnRoutes().
List<IpPrefix> org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.withdrawnRoutes ()
Returns withdrawn Routes.
Returns
withdrawn Routes
Implements org.onosproject.bgpio.protocol.BgpUpdateMsg.
Definition at line 261 of file BgpUpdateMsgVer4.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.BgpUpdateMsgVer4(), and org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.toString().
void org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.writeTo (ChannelBuffer cb) throws BgpParseException
Writes byte streams of messages to channel buffer.
Parameters
cb channelBuffer
Exceptions
BgpParseException when error occurs while writing BGP message to channel buffer
Implements org.onosproject.bgpio.protocol.BgpMessage.
Definition at line 251 of file BgpUpdateMsgVer4.java.
Member Data Documentation
final int org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.BYTE_IN_BITS = 8 static
Definition at line 75 of file BgpUpdateMsgVer4.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.parseNlri(), and org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.parseWithdrawnRoutes().
final Logger org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpUpdateMsgVer4.class)
Definition at line 69 of file BgpUpdateMsgVer4.java.
final int org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.MIN_LEN_AFTER_WITHDRW_ROUTES = 2 static
Definition at line 76 of file BgpUpdateMsgVer4.java.
final int org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.MINIMUM_COMMON_HEADER_LENGTH = 19 static
Definition at line 77 of file BgpUpdateMsgVer4.java.
final BgpType org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.MSG_TYPE = BgpType.UPDATE static
Definition at line 78 of file BgpUpdateMsgVer4.java.
final int org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.PACKET_MINIMUM_LENGTH = 4 static
Definition at line 74 of file BgpUpdateMsgVer4.java.
final byte org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.PACKET_VERSION = 4 static
Definition at line 72 of file BgpUpdateMsgVer4.java.
final BgpUpdateMsgVer4.Reader org.onosproject.bgpio.protocol.ver4.BgpUpdateMsgVer4.READER = new Reader() static
Definition at line 79 of file BgpUpdateMsgVer4.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/protocol/ver4/BgpUpdateMsgVer4.java