onos: org.onosproject.pcepio.types.LabelSubObject Class Reference
org.onosproject.pcepio.types.LabelSubObject Class Reference
LabelSubObject: Provides a LabelSubObject.
Public Member Functions
LabelSubObject (byte flags, byte cType, int contents)
constructor to initialize parameters for LabelSubObject.
byte getFlags ()
Returns Flags.
byte getCtype ()
Returns cType.
int getContents ()
Returns contents.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static LabelSubObject of (byte flags, byte cType, int contents)
Return an object of LabelSubObject.
static PcepValueType read (ChannelBuffer c)
Reads the channel buffer and returns object of LabelSubObject.
Static Public Attributes
static final short TYPE = 0x03
static final short LENGTH = 8
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(LabelSubObject.class)
Detailed Description
LabelSubObject: Provides a LabelSubObject.
Definition at line 31 of file LabelSubObject.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.LabelSubObject.LabelSubObject (byte flags, byte cType, int contents)
constructor to initialize parameters for LabelSubObject.
Parameters
flags flags
cType C-Type
contents Contents of label object
Definition at line 59 of file LabelSubObject.java.
Referenced by org.onosproject.pcepio.types.LabelSubObject.equals(), org.onosproject.pcepio.types.LabelSubObject.of(), and org.onosproject.pcepio.types.LabelSubObject.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.LabelSubObject.equals (Object obj)
Definition at line 125 of file LabelSubObject.java.
References org.onosproject.pcepio.types.LabelSubObject.LabelSubObject().
int org.onosproject.pcepio.types.LabelSubObject.getContents ()
Returns contents.
Returns
contents
Definition at line 100 of file LabelSubObject.java.
byte org.onosproject.pcepio.types.LabelSubObject.getCtype ()
Returns cType.
Returns
cType
Definition at line 91 of file LabelSubObject.java.
byte org.onosproject.pcepio.types.LabelSubObject.getFlags ()
Returns Flags.
Returns
flags
Definition at line 82 of file LabelSubObject.java.
short org.onosproject.pcepio.types.LabelSubObject.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 115 of file LabelSubObject.java.
References org.onosproject.pcepio.types.LabelSubObject.LENGTH.
short org.onosproject.pcepio.types.LabelSubObject.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 110 of file LabelSubObject.java.
References org.onosproject.pcepio.types.LabelSubObject.TYPE.
PcepVersion org.onosproject.pcepio.types.LabelSubObject.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 105 of file LabelSubObject.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.LabelSubObject.hashCode ()
Definition at line 120 of file LabelSubObject.java.
static LabelSubObject org.onosproject.pcepio.types.LabelSubObject.of (byte flags, byte cType, int contents) static
Return an object of LabelSubObject.
Parameters
flags flags
cType C-type
contents contents of label objects
Returns
object of LabelSubObject
Definition at line 73 of file LabelSubObject.java.
References org.onosproject.pcepio.types.LabelSubObject.LabelSubObject().
static PcepValueType org.onosproject.pcepio.types.LabelSubObject.read (ChannelBuffer c) static
Reads the channel buffer and returns object of LabelSubObject.
Parameters
c type of channel buffer
Returns
object of LabelSubObject
Definition at line 154 of file LabelSubObject.java.
References org.onosproject.pcepio.types.LabelSubObject.LabelSubObject().
String org.onosproject.pcepio.types.LabelSubObject.toString ()
Definition at line 162 of file LabelSubObject.java.
References org.onosproject.pcepio.types.LabelSubObject.LENGTH, and org.onosproject.pcepio.types.LabelSubObject.TYPE.
int org.onosproject.pcepio.types.LabelSubObject.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 138 of file LabelSubObject.java.
References org.onosproject.pcepio.types.LabelSubObject.LENGTH, and org.onosproject.pcepio.types.LabelSubObject.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.LabelSubObject.LENGTH = 8 static
Definition at line 47 of file LabelSubObject.java.
Referenced by org.onosproject.pcepio.types.LabelSubObject.getLength(), org.onosproject.pcepio.types.LabelSubObject.toString(), and org.onosproject.pcepio.types.LabelSubObject.write().
final Logger org.onosproject.pcepio.types.LabelSubObject.log = LoggerFactory.getLogger(LabelSubObject.class) static protected
Definition at line 44 of file LabelSubObject.java.
final short org.onosproject.pcepio.types.LabelSubObject.TYPE = 0x03 static
Definition at line 46 of file LabelSubObject.java.
Referenced by org.onosproject.pcepio.types.LabelSubObject.getType(), org.onosproject.pcepio.types.LabelSubObject.toString(), and org.onosproject.pcepio.types.LabelSubObject.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/LabelSubObject.java