onos: org.onosproject.net.ConnectPoint Class Reference
org.onosproject.net.ConnectPoint Class Reference
Abstraction of a network connection point expressed as a pair of the network element identifier and port number.
Public Member Functions
ConnectPoint (ElementId elementId, PortNumber portNumber)
Creates a new connection point.
ElementId elementId ()
Returns the network element identifier.
DeviceId deviceId ()
Returns the identifier of the infrastructure device if the connection point belongs to a network element which is indeed an infrastructure device.
HostId hostId ()
Returns the identifier of the infrastructure device if the connection point belongs to a network element which is indeed an end-station host.
IpElementId ipElementId ()
Returns the identifier of the infrastructure device if the connection point belongs to a network element which is indeed an ip of pcc client identifier.
PortNumber port ()
Returns the connection port number.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static ConnectPoint deviceConnectPoint (String string)
Parse a device connect point from a string.
static ConnectPoint hostConnectPoint (String string)
Parse a host connect point from a string.
Detailed Description
Abstraction of a network connection point expressed as a pair of the network element identifier and port number.
Definition at line 29 of file ConnectPoint.java.
Constructor & Destructor Documentation
org.onosproject.net.ConnectPoint.ConnectPoint (ElementId elementId, PortNumber portNumber)
Creates a new connection point.
Parameters
elementId network element identifier
portNumber port number
Definition at line 40 of file ConnectPoint.java.
References org.onosproject.net.ConnectPoint.elementId().
Referenced by org.onosproject.net.ConnectPoint.deviceConnectPoint(), org.onosproject.net.ConnectPoint.equals(), and org.onosproject.net.ConnectPoint.hostConnectPoint().
Member Function Documentation
static ConnectPoint org.onosproject.net.ConnectPoint.deviceConnectPoint (String string) static
Parse a device connect point from a string.
The connect point should be in the format "deviceUri/portNumber".
Parameters
string string to parse
Returns
a ConnectPoint based on the information in the string.
Definition at line 120 of file ConnectPoint.java.
References org.onosproject.net.ConnectPoint.ConnectPoint(), and org.onosproject.net.DeviceId.deviceId().
Referenced by org.onosproject.routing.config.BgpConfig.bgpSpeakers(), org.onosproject.incubator.net.domain.IntentDomainConfig.edgePorts(), org.onosproject.xosintegration.cli.VoltTenantsCreateCommand.execute(), org.onosproject.cli.net.InterfaceAddCommand.execute(), org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.testTunnelAdded(), and org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.testTunnelRemoved().
DeviceId org.onosproject.net.ConnectPoint.deviceId ()
Returns the identifier of the infrastructure device if the connection point belongs to a network element which is indeed an infrastructure device.
Returns
network element identifier as a device identifier
Exceptions
java.lang.IllegalStateException if connection point is not associated with a device
Definition at line 63 of file ConnectPoint.java.
References org.onosproject.net.ConnectPoint.elementId().
Referenced by org.onosproject.net.ConnectPointTest.basics(), org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.MplsIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.PointToPointIntentCompiler.compile(), org.onosproject.incubator.net.domain.impl.IntentDomainManager.getDomains(), org.onosproject.store.trivial.SimpleLinkStore.getEgressLinks(), org.onosproject.store.link.impl.GossipLinkStore.getEgressLinks(), org.onosproject.store.trivial.SimpleLinkStore.getIngressLinks(), org.onosproject.store.link.impl.GossipLinkStore.getIngressLinks(), org.onosproject.net.HostLocation.HostLocation(), org.onosproject.common.DefaultTopology.isBroadcastPoint(), org.onosproject.net.link.impl.LinkManager.removeLinks(), org.onosproject.net.intent.impl.compiler.MplsPathIntentCompilerTest.testCompile(), org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest.testCompile(), org.onosproject.net.edgeservice.impl.EdgeManagerTest.testLinkUpdates(), org.onosproject.net.ConnectPointTest.testParseDeviceConnectPoint(), org.onosproject.routing.impl.RouterAsyncArpTest.testRouteAdd(), and org.onosproject.routing.impl.RouterAsyncArpTest.testRouteUpdate().
ElementId org.onosproject.net.ConnectPoint.elementId ()
Returns the network element identifier.
Returns
element identifier
Definition at line 50 of file ConnectPoint.java.
Referenced by org.onosproject.net.ConnectPoint.ConnectPoint(), org.onosproject.net.ConnectPoint.deviceId(), org.onosproject.net.ConnectPoint.hashCode(), org.onosproject.net.ConnectPoint.hostId(), org.onosproject.net.ConnectPoint.ipElementId(), and org.onosproject.net.ConnectPoint.toString().
boolean org.onosproject.net.ConnectPoint.equals (Object obj)
Definition at line 155 of file ConnectPoint.java.
References org.onosproject.net.ConnectPoint.ConnectPoint().
Referenced by org.onosproject.routing.config.BgpSpeaker.equals(), and org.onosproject.pim.impl.PIMInterface.processHello().
int org.onosproject.net.ConnectPoint.hashCode ()
Definition at line 150 of file ConnectPoint.java.
References org.onosproject.net.ConnectPoint.elementId().
Referenced by org.onosproject.incubator.net.domain.DomainEdge.hashCode().
static ConnectPoint org.onosproject.net.ConnectPoint.hostConnectPoint (String string) static
Parse a host connect point from a string.
The connect point should be in the format "hostId/vlanId/portNumber".
Parameters
string string to parse
Returns
a ConnectPoint based on the information in the string.
Definition at line 137 of file ConnectPoint.java.
References org.onosproject.net.ConnectPoint.ConnectPoint(), org.onosproject.net.HostId.hostId(), and org.onosproject.net.PortNumber.portNumber().
HostId org.onosproject.net.ConnectPoint.hostId ()
Returns the identifier of the infrastructure device if the connection point belongs to a network element which is indeed an end-station host.
Returns
network element identifier as a host identifier
Exceptions
java.lang.IllegalStateException if connection point is not associated with a host
Definition at line 79 of file ConnectPoint.java.
References org.onosproject.net.ConnectPoint.elementId().
Referenced by org.onosproject.net.ConnectPointTest.testParseHostConnectPoint().
IpElementId org.onosproject.net.ConnectPoint.ipElementId ()
Returns the identifier of the infrastructure device if the connection point belongs to a network element which is indeed an ip of pcc client identifier.
Returns
network element identifier as a pcc client identifier
Exceptions
java.lang.IllegalStateException if connection point is not associated with a pcc client
Definition at line 96 of file ConnectPoint.java.
References org.onosproject.net.ConnectPoint.elementId().
PortNumber org.onosproject.net.ConnectPoint.port ()
Returns the connection port number.
Returns
port number
Definition at line 109 of file ConnectPoint.java.
Referenced by org.onosproject.cordfabric.CordFabricManager.addVlan(), org.onosproject.net.ConnectPointTest.basics(), org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.compile(), org.onosproject.codec.impl.HostLocationCodec.encode(), org.onosproject.cli.net.AddOpticalIntentCommand.execute(), org.onosproject.ui.table.cell.ConnectPointFormatter.nonNullFormat(), org.onosproject.ui.table.cell.HostLocationFormatter.nonNullFormat(), org.onosproject.olt.Olt.provisionSubscriber(), org.onosproject.cordfabric.CordFabricManager.removeVlan(), org.onosproject.net.intent.impl.compiler.LinkCollectionIntentCompilerTest.testCompile(), org.onosproject.net.edgeservice.impl.EdgeManagerTest.testLinkUpdates(), org.onosproject.net.ConnectPointTest.testParseDeviceConnectPoint(), and org.onosproject.net.ConnectPointTest.testParseHostConnectPoint().
String org.onosproject.net.ConnectPoint.toString ()
Definition at line 168 of file ConnectPoint.java.
References org.onosproject.net.ConnectPoint.elementId().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/ConnectPoint.java