onos: org.onosproject.net.driver.DefaultDriverDataTest Class Reference
org.onosproject.net.driver.DefaultDriverDataTest Class Reference
Public Member Functions
void setUp ()
void basics ()
void behaviour ()
void setAndClearAnnotations ()
void clearAllAnnotations ()
Static Public Attributes
static final DeviceId DEVICE_ID = deviceId("of:0011223344556677")
Detailed Description
Definition at line 26 of file DefaultDriverDataTest.java.
Member Function Documentation
void org.onosproject.net.driver.DefaultDriverDataTest.basics ()
Definition at line 43 of file DefaultDriverDataTest.java.
References org.onosproject.net.driver.DefaultDriverDataTest.DEVICE_ID, and org.onosproject.net.driver.DefaultDriverData.toString().
void org.onosproject.net.driver.DefaultDriverDataTest.behaviour ()
Definition at line 50 of file DefaultDriverDataTest.java.
void org.onosproject.net.driver.DefaultDriverDataTest.clearAllAnnotations ()
Definition at line 69 of file DefaultDriverDataTest.java.
References org.onosproject.net.driver.DefaultDriverData.keys(), and org.onosproject.net.driver.DefaultDriverData.value().
void org.onosproject.net.driver.DefaultDriverDataTest.setAndClearAnnotations ()
Definition at line 56 of file DefaultDriverDataTest.java.
References org.onosproject.net.driver.DefaultDriverData.keys(), and org.onosproject.net.driver.DefaultDriverData.value().
void org.onosproject.net.driver.DefaultDriverDataTest.setUp ()
Definition at line 34 of file DefaultDriverDataTest.java.
References org.onosproject.net.driver.DefaultDriverDataTest.DEVICE_ID.
Member Data Documentation
final DeviceId org.onosproject.net.driver.DefaultDriverDataTest.DEVICE_ID = deviceId("of:0011223344556677") static
Definition at line 28 of file DefaultDriverDataTest.java.
Referenced by org.onosproject.net.driver.DefaultDriverDataTest.basics(), org.onosproject.net.driver.DefaultDriverHandlerTest.setUp(), and org.onosproject.net.driver.DefaultDriverDataTest.setUp().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/driver/DefaultDriverDataTest.java