onos: org.onosproject.pcepio.types.TEDefaultMetricTlv Class Reference
org.onosproject.pcepio.types.TEDefaultMetricTlv Class Reference
Provides TEDefaultMetricTlv.
Public Member Functions
TEDefaultMetricTlv (int rawValue)
Constructor to initialize rawValue.
int getInt ()
Returns raw value.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static TEDefaultMetricTlv of (final int raw)
Returns newly created TEDefaultMetricTlv object.
static TEDefaultMetricTlv read (ChannelBuffer c)
Reads channel buffer and returns object of TEDefaultMetricTlv.
Static Public Attributes
static final short TYPE = 13400
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(TEDefaultMetricTlv.class)
Detailed Description
Provides TEDefaultMetricTlv.
Definition at line 30 of file TEDefaultMetricTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.TEDefaultMetricTlv.TEDefaultMetricTlv (int rawValue)
Constructor to initialize rawValue.
Parameters
rawValue TE Default Link Metric
Definition at line 55 of file TEDefaultMetricTlv.java.
Referenced by org.onosproject.pcepio.types.TEDefaultMetricTlv.equals(), and org.onosproject.pcepio.types.TEDefaultMetricTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.TEDefaultMetricTlv.equals (Object obj)
Definition at line 99 of file TEDefaultMetricTlv.java.
References org.onosproject.pcepio.types.TEDefaultMetricTlv.TEDefaultMetricTlv().
int org.onosproject.pcepio.types.TEDefaultMetricTlv.getInt ()
Returns raw value.
Returns
rawValue TE Default Link Metric
Definition at line 74 of file TEDefaultMetricTlv.java.
short org.onosproject.pcepio.types.TEDefaultMetricTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 89 of file TEDefaultMetricTlv.java.
References org.onosproject.pcepio.types.TEDefaultMetricTlv.LENGTH.
short org.onosproject.pcepio.types.TEDefaultMetricTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 84 of file TEDefaultMetricTlv.java.
References org.onosproject.pcepio.types.TEDefaultMetricTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.TEDefaultMetricTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 79 of file TEDefaultMetricTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.TEDefaultMetricTlv.hashCode ()
Definition at line 94 of file TEDefaultMetricTlv.java.
static TEDefaultMetricTlv org.onosproject.pcepio.types.TEDefaultMetricTlv.of (final int raw) static
Returns newly created TEDefaultMetricTlv object.
Parameters
raw raw value
Returns
object of TEDefaultMetricTlv.
Definition at line 65 of file TEDefaultMetricTlv.java.
References org.onosproject.pcepio.types.TEDefaultMetricTlv.TEDefaultMetricTlv().
static TEDefaultMetricTlv org.onosproject.pcepio.types.TEDefaultMetricTlv.read (ChannelBuffer c) static
Reads channel buffer and returns object of TEDefaultMetricTlv.
Parameters
c input channel buffer
Returns
object of TEDefaultMetricTlv
Definition at line 125 of file TEDefaultMetricTlv.java.
String org.onosproject.pcepio.types.TEDefaultMetricTlv.toString ()
Definition at line 130 of file TEDefaultMetricTlv.java.
References org.onosproject.pcepio.types.TEDefaultMetricTlv.LENGTH, and org.onosproject.pcepio.types.TEDefaultMetricTlv.TYPE.
int org.onosproject.pcepio.types.TEDefaultMetricTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 111 of file TEDefaultMetricTlv.java.
References org.onosproject.pcepio.types.TEDefaultMetricTlv.LENGTH, and org.onosproject.pcepio.types.TEDefaultMetricTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.TEDefaultMetricTlv.LENGTH = 4 static
Definition at line 46 of file TEDefaultMetricTlv.java.
Referenced by org.onosproject.pcepio.types.TEDefaultMetricTlv.getLength(), org.onosproject.pcepio.types.TEDefaultMetricTlv.toString(), and org.onosproject.pcepio.types.TEDefaultMetricTlv.write().
final Logger org.onosproject.pcepio.types.TEDefaultMetricTlv.log = LoggerFactory.getLogger(TEDefaultMetricTlv.class) static protected
Definition at line 43 of file TEDefaultMetricTlv.java.
final short org.onosproject.pcepio.types.TEDefaultMetricTlv.TYPE = 13400 static
Definition at line 45 of file TEDefaultMetricTlv.java.
Referenced by org.onosproject.pcepio.types.TEDefaultMetricTlv.getType(), org.onosproject.pcepio.types.TEDefaultMetricTlv.toString(), and org.onosproject.pcepio.types.TEDefaultMetricTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/TEDefaultMetricTlv.java