onos: org.onosproject.pcepio.types.StatefulLspErrorCodeTlv Class Reference
org.onosproject.pcepio.types.StatefulLspErrorCodeTlv Class Reference
Provides StatefulLspErrorCodeTlv.
Public Member Functions
StatefulLspErrorCodeTlv (int rawValue)
Constructor to initialize raw Value.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
int getInt ()
Returns lsp error code value.
short getLength ()
Returns the Length of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static StatefulLspErrorCodeTlv of (int raw)
Creates object of StatefulLspErrorCodeTlv.
static StatefulLspErrorCodeTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of StatefulLspErrorCodeTlv.
Static Public Attributes
static final short TYPE = 20
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(StatefulLspErrorCodeTlv.class)
Detailed Description
Provides StatefulLspErrorCodeTlv.
Definition at line 31 of file StatefulLspErrorCodeTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.StatefulLspErrorCodeTlv (int rawValue)
Constructor to initialize raw Value.
Parameters
rawValue lsp error code value
Definition at line 59 of file StatefulLspErrorCodeTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.equals(), and org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.equals (Object obj)
Definition at line 103 of file StatefulLspErrorCodeTlv.java.
References org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.StatefulLspErrorCodeTlv().
int org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.getInt ()
Returns lsp error code value.
Returns
lsp error code value
Definition at line 83 of file StatefulLspErrorCodeTlv.java.
short org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 88 of file StatefulLspErrorCodeTlv.java.
References org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.LENGTH.
short org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 93 of file StatefulLspErrorCodeTlv.java.
References org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 74 of file StatefulLspErrorCodeTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.hashCode ()
Definition at line 98 of file StatefulLspErrorCodeTlv.java.
static StatefulLspErrorCodeTlv org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.of (int raw) static
Creates object of StatefulLspErrorCodeTlv.
Parameters
raw lsp error code value
Returns
object of StatefulLspErrorCodeTlv
Definition at line 69 of file StatefulLspErrorCodeTlv.java.
References org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.StatefulLspErrorCodeTlv().
static StatefulLspErrorCodeTlv org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of StatefulLspErrorCodeTlv.
Parameters
c of type channel buffer
Returns
object of StatefulLspErrorCodeTlv
Definition at line 129 of file StatefulLspErrorCodeTlv.java.
String org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.toString ()
Definition at line 134 of file StatefulLspErrorCodeTlv.java.
References org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.LENGTH, and org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.TYPE.
int org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 115 of file StatefulLspErrorCodeTlv.java.
References org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.LENGTH, and org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.LENGTH = 4 static
Definition at line 51 of file StatefulLspErrorCodeTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.getLength(), org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.toString(), and org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.write().
final Logger org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.log = LoggerFactory.getLogger(StatefulLspErrorCodeTlv.class) static protected
Definition at line 48 of file StatefulLspErrorCodeTlv.java.
final short org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.TYPE = 20 static
Definition at line 50 of file StatefulLspErrorCodeTlv.java.
Referenced by org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.getType(), org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.toString(), and org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/StatefulLspErrorCodeTlv.java