onos: org.onlab.stc.Monitor Class Reference
org.onlab.stc.Monitor Class Reference
Scenario test monitor.
Public Member Functions
void notify (ObjectNode event)
Notifies the process monitor delegate with the specified event.
void onStart (Step step, String command)
Indicates that process step has started.
void onCompletion (Step step, Coordinator.Status status)
Indicates that process step has completed.
void onOutput (Step step, String line)
Notifies when a new line of output becomes available.
Detailed Description
Scenario test monitor.
Definition at line 34 of file Monitor.java.
Member Function Documentation
void org.onlab.stc.Monitor.notify (ObjectNode event)
Notifies the process monitor delegate with the specified event.
Parameters
event JSON event data
Definition at line 73 of file Monitor.java.
Referenced by org.onlab.stc.Monitor.onCompletion(), and org.onlab.stc.Monitor.onStart().
void org.onlab.stc.Monitor.onCompletion (Step step, Coordinator.Status status)
Indicates that process step has completed.
Parameters
step subject step
status step completion status
Implements org.onlab.stc.StepProcessListener.
Definition at line 138 of file Monitor.java.
References org.onlab.stc.Monitor.notify().
void org.onlab.stc.Monitor.onOutput (Step step, String line)
Notifies when a new line of output becomes available.
Parameters
step subject step
line line of output
Implements org.onlab.stc.StepProcessListener.
Definition at line 143 of file Monitor.java.
void org.onlab.stc.Monitor.onStart (Step step, String command)
Indicates that process step has started.
Parameters
step subject step
command actual command executed; includes run-time substitutions
Implements org.onlab.stc.StepProcessListener.
Definition at line 133 of file Monitor.java.
References org.onlab.stc.Monitor.notify().
The documentation for this class was generated from the following file:
utils/stc/src/main/java/org/onlab/stc/Monitor.java