onos: org.onosproject.bgpio.protocol.ver4.BgpPathAttributes Class Reference
org.onosproject.bgpio.protocol.ver4.BgpPathAttributes Class Reference
Provides Implementation of BGP Path Attribute.
Public Member Functions
BgpPathAttributes ()
Initialize parameter.
BgpPathAttributes (List< BgpValueType > pathAttribute)
Constructor to initialize parameters for BGP path attributes.
List< BgpValueType > pathAttributes ()
Returns list of path attributes.
String toString ()
Static Public Member Functions
static BgpPathAttributes read (ChannelBuffer cb) throws BgpParseException
Reads from channelBuffer and parses BGP path attributes.
static void checkMandatoryAttr (boolean isOrigin, boolean isAsPath, boolean isNextHop, boolean isMpReach, boolean isMpUnReach) throws BgpParseException
Checks mandatory attributes are presents, if not present throws exception.
Static Public Attributes
static final int LINK_STATE_ATTRIBUTE_TYPE = 50
static final int MPREACHNLRI_TYPE = 14
static final int MPUNREACHNLRI_TYPE = 15
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(BgpPathAttributes.class)
Detailed Description
Provides Implementation of BGP Path Attribute.
Definition at line 43 of file BgpPathAttributes.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.BgpPathAttributes ()
Initialize parameter.
Definition at line 66 of file BgpPathAttributes.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.read().
org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.BgpPathAttributes (List< BgpValueType > pathAttribute)
Constructor to initialize parameters for BGP path attributes.
Parameters
pathAttribute list of path attributes
Definition at line 75 of file BgpPathAttributes.java.
Member Function Documentation
static void org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.checkMandatoryAttr (boolean isOrigin, boolean isAsPath, boolean isNextHop, boolean isMpReach, boolean isMpUnReach) throws BgpParseException static
Checks mandatory attributes are presents, if not present throws exception.
Parameters
isOrigin say whether origin attribute is present
isAsPath say whether aspath attribute is present
isNextHop say whether nexthop attribute is present
isMpReach say whether mpreach attribute is present
isMpUnReach say whether mpunreach attribute is present
Exceptions
BgpParseException if mandatory path attribute is not present
Definition at line 166 of file BgpPathAttributes.java.
References org.onosproject.bgpio.types.AsPath.ASPATH_TYPE, org.onosproject.bgpio.types.BgpErrorType.MISSING_WELLKNOWN_ATTRIBUTE, org.onosproject.bgpio.types.NextHop.NEXTHOP_TYPE, org.onosproject.bgpio.types.Origin.ORIGIN_TYPE, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.read().
List<BgpValueType> org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.pathAttributes ()
Returns list of path attributes.
Returns
list of path attributes
Definition at line 84 of file BgpPathAttributes.java.
static BgpPathAttributes org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.read (ChannelBuffer cb) throws BgpParseException static
Reads from channelBuffer and parses BGP path attributes.
Parameters
cb channelBuffer
Returns
object of BgpPathAttributes
Exceptions
BgpParseException while parsing BGP path attributes
Definition at line 95 of file BgpPathAttributes.java.
References org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.BgpPathAttributes(), org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.checkMandatoryAttr(), and org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.LINK_STATE_ATTRIBUTE_TYPE.
String org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.toString ()
Definition at line 190 of file BgpPathAttributes.java.
Member Data Documentation
final int org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.LINK_STATE_ATTRIBUTE_TYPE = 50 static
Definition at line 57 of file BgpPathAttributes.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.read().
final Logger org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.log = LoggerFactory.getLogger(BgpPathAttributes.class) static protected
Definition at line 55 of file BgpPathAttributes.java.
final int org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.MPREACHNLRI_TYPE = 14 static
Definition at line 58 of file BgpPathAttributes.java.
final int org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.MPUNREACHNLRI_TYPE = 15 static
Definition at line 59 of file BgpPathAttributes.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/protocol/ver4/BgpPathAttributes.java