onos: org.onosproject.store.trivial.SystemClockTimestamp Class Reference
org.onosproject.store.trivial.SystemClockTimestamp Class Reference
A Timestamp that derives its value from the system clock time (in ns) on the controller where it is generated.
Public Member Functions
SystemClockTimestamp ()
SystemClockTimestamp (long timestamp)
int compareTo (Timestamp o)
int hashCode ()
boolean equals (Object obj)
String toString ()
long nanoTimestamp ()
long systemTimestamp ()
Public Member Functions inherited from org.onosproject.store.Timestamp
default boolean isNewerThan (Timestamp other)
Tests if this timestamp is newer than the specified timestamp.
default boolean isOlderThan (Timestamp other)
Tests if this timestamp is older than the specified timestamp.
Detailed Description
A Timestamp that derives its value from the system clock time (in ns) on the controller where it is generated.
Definition at line 30 of file SystemClockTimestamp.java.
Constructor & Destructor Documentation
org.onosproject.store.trivial.SystemClockTimestamp.SystemClockTimestamp ()
Definition at line 34 of file SystemClockTimestamp.java.
References org.onosproject.store.trivial.SystemClockTimestamp.nanoTimestamp().
Referenced by org.onosproject.store.trivial.SystemClockTimestamp.compareTo(), and org.onosproject.store.trivial.SystemClockTimestamp.equals().
org.onosproject.store.trivial.SystemClockTimestamp.SystemClockTimestamp (long timestamp)
Definition at line 38 of file SystemClockTimestamp.java.
References org.onosproject.store.trivial.SystemClockTimestamp.nanoTimestamp().
Member Function Documentation
int org.onosproject.store.trivial.SystemClockTimestamp.compareTo (Timestamp o)
Definition at line 43 of file SystemClockTimestamp.java.
References org.onosproject.store.trivial.SystemClockTimestamp.nanoTimestamp(), and org.onosproject.store.trivial.SystemClockTimestamp.SystemClockTimestamp().
boolean org.onosproject.store.trivial.SystemClockTimestamp.equals (Object obj)
Implements org.onosproject.store.Timestamp.
Definition at line 58 of file SystemClockTimestamp.java.
References org.onosproject.store.trivial.SystemClockTimestamp.SystemClockTimestamp().
int org.onosproject.store.trivial.SystemClockTimestamp.hashCode ()
Implements org.onosproject.store.Timestamp.
Definition at line 53 of file SystemClockTimestamp.java.
References org.onosproject.store.trivial.SystemClockTimestamp.nanoTimestamp().
long org.onosproject.store.trivial.SystemClockTimestamp.nanoTimestamp ()
Definition at line 76 of file SystemClockTimestamp.java.
Referenced by org.onosproject.store.trivial.SystemClockTimestamp.compareTo(), org.onosproject.store.trivial.SystemClockTimestamp.hashCode(), org.onosproject.store.trivial.SystemClockTimestamp.SystemClockTimestamp(), org.onosproject.store.trivial.SystemClockTimestamp.systemTimestamp(), and org.onosproject.store.trivial.SystemClockTimestamp.toString().
long org.onosproject.store.trivial.SystemClockTimestamp.systemTimestamp ()
Definition at line 80 of file SystemClockTimestamp.java.
References org.onosproject.store.trivial.SystemClockTimestamp.nanoTimestamp().
String org.onosproject.store.trivial.SystemClockTimestamp.toString ()
Definition at line 70 of file SystemClockTimestamp.java.
References org.onosproject.store.trivial.SystemClockTimestamp.nanoTimestamp().
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SystemClockTimestamp.java