onos: org.onlab.nio.AcceptorLoop Class Reference
org.onlab.nio.AcceptorLoop Class Reference abstract
Selector loop derivative tailored to acceptConnection inbound connections.
Public Member Functions
AcceptorLoop (long selectTimeout, SocketAddress listenAddress) throws IOException
Creates an acceptor loop with the specified selection timeout and accepting connections on the the given address.
void shutdown ()
Public Member Functions inherited from org.onlab.nio.SelectorLoop
SelectorLoop (long selectTimeout) throws IOException
Creates a new selector loop with the given selection timeout.
Throwable getError ()
Returns the error, if there was one, that caused the loop to terminate prematurely.
void run ()
void shutdown ()
Triggers loop shutdown.
final synchronized boolean awaitStart (long timeout)
Waits for the loop execution to start.
final synchronized boolean awaitStop (long timeout)
Waits for the loop execution to stop.
Protected Member Functions
abstract void acceptConnection (ServerSocketChannel channel) throws IOException
Hook to accept an inbound connection on the specified socket channel.
synchronized void openChannel () throws IOException
Opens a new server socket channel configured in non-blocking mode and bound to the loop's listen address.
synchronized void closechannel () throws IOException
Closes the server socket channel.
void loop () throws IOException
Contains the body of the I/O selector loop.
Protected Member Functions inherited from org.onlab.nio.SelectorLoop
Selector openSelector () throws IOException
Opens a new selector for the use by the loop.
boolean isRunning ()
Indicates that the loop is marked to run.
synchronized void notifyReady ()
Notifies observers waiting for loop to become ready.
Additional Inherited Members
Protected Attributes inherited from org.onlab.nio.SelectorLoop
final Logger log = LoggerFactory.getLogger(getClass())
final Selector selector
Selector used by this loop to pace the I/O operations.
long selectTimeout
Selection operations timeout; specified in millis.
Detailed Description
Selector loop derivative tailored to acceptConnection inbound connections.
Definition at line 30 of file AcceptorLoop.java.
Constructor & Destructor Documentation
org.onlab.nio.AcceptorLoop.AcceptorLoop (long selectTimeout, SocketAddress listenAddress) throws IOException
Creates an acceptor loop with the specified selection timeout and accepting connections on the the given address.
Parameters
selectTimeout selection timeout; specified in millis
listenAddress socket address where to listen for connections
Exceptions
IOException if the backing selector cannot be opened
Definition at line 43 of file AcceptorLoop.java.
References org.onlab.nio.SelectorLoop.selectTimeout.
Member Function Documentation
abstract void org.onlab.nio.AcceptorLoop.acceptConnection (ServerSocketChannel channel) throws IOException protected pure virtual
Hook to accept an inbound connection on the specified socket channel.
Parameters
channel socketChannel where an accept operation awaits
Exceptions
IOException if the accept operation cannot be processed
Referenced by org.onlab.nio.AcceptorLoop.loop().
synchronized void org.onlab.nio.AcceptorLoop.closechannel () throws IOException protected
Closes the server socket channel.
Exceptions
IOException if unable to close the socketChannel
Definition at line 76 of file AcceptorLoop.java.
Referenced by org.onlab.nio.AcceptorLoop.shutdown().
void org.onlab.nio.AcceptorLoop.loop () throws IOException protected virtual
Contains the body of the I/O selector loop.
Exceptions
IOException if an error is encountered while selecting I/O
Implements org.onlab.nio.SelectorLoop.
Definition at line 94 of file AcceptorLoop.java.
References org.onlab.nio.AcceptorLoop.acceptConnection(), org.onlab.nio.SelectorLoop.isRunning(), org.onlab.nio.SelectorLoop.notifyReady(), org.onlab.nio.AcceptorLoop.openChannel(), and org.onlab.nio.SelectorLoop.selectTimeout.
synchronized void org.onlab.nio.AcceptorLoop.openChannel () throws IOException protected
Opens a new server socket channel configured in non-blocking mode and bound to the loop's listen address.
Exceptions
IOException if unable to open or configure the socket channel
Definition at line 63 of file AcceptorLoop.java.
References org.onlab.nio.SelectorLoop.selector.
Referenced by org.onlab.nio.AcceptorLoop.loop().
void org.onlab.nio.AcceptorLoop.shutdown ()
Definition at line 84 of file AcceptorLoop.java.
References org.onlab.nio.AcceptorLoop.closechannel().
The documentation for this class was generated from the following file:
utils/nio/src/main/java/org/onlab/nio/AcceptorLoop.java