onos: org.onosproject.net.DefaultEdgeLink Class Reference
org.onosproject.net.DefaultEdgeLink Class Reference
Default edge link model implementation.
Public Member Functions
DefaultEdgeLink (ProviderId providerId, ConnectPoint hostPoint, HostLocation hostLocation, boolean isIngress, Annotations...annotations)
Creates an edge link using the supplied information.
HostId hostId ()
Returns the host identification.
HostLocation hostLocation ()
Returns the connection point where the host attaches to the network infrastructure.
Public Member Functions inherited from org.onosproject.net.DefaultLink
DefaultLink (ProviderId providerId, ConnectPoint src, ConnectPoint dst, Type type, Annotations...annotations)
Creates an active infrastructure link using the supplied information.
DefaultLink (ProviderId providerId, ConnectPoint src, ConnectPoint dst, Type type, State state, boolean isDurable, Annotations...annotations)
Creates an infrastructure link using the supplied information.
ConnectPoint src ()
Returns the link source connection point.
ConnectPoint dst ()
Returns the link destination connection point.
Type type ()
Returns the link type.
State state ()
Returns the link state.
boolean isDurable ()
Indicates if the link is to be considered durable.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel ()
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Static Public Member Functions
static DefaultEdgeLink createEdgeLink (ConnectPoint edgePort, boolean isIngress)
Creates a phantom edge link, to an unspecified end-station.
static DefaultEdgeLink createEdgeLink (Host host, boolean isIngress)
Creates a an edge link, to the specified end-station.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel (ProviderId providerId, Annotations...annotations)
Creates a model entity attributed to the specified provider and optionally annotated.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default edge link model implementation.
Definition at line 26 of file DefaultEdgeLink.java.
Constructor & Destructor Documentation
org.onosproject.net.DefaultEdgeLink.DefaultEdgeLink (ProviderId providerId, ConnectPoint hostPoint, HostLocation hostLocation, boolean isIngress, Annotations... annotations)
Creates an edge link using the supplied information.
Parameters
providerId provider identity
hostPoint host-side connection point
hostLocation location where host attaches to the network
isIngress true to indicate host-to-network direction; false for network-to-host direction
annotations optional key/value annotations
Definition at line 41 of file DefaultEdgeLink.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.Link.Type.EDGE, and org.onosproject.net.DefaultEdgeLink.hostLocation().
Referenced by org.onosproject.net.DefaultEdgeLink.createEdgeLink().
Member Function Documentation
static DefaultEdgeLink org.onosproject.net.DefaultEdgeLink.createEdgeLink (ConnectPoint edgePort, boolean isIngress) static
Creates a phantom edge link, to an unspecified end-station.
This link does not represent any actually discovered link stored in the system.
Parameters
edgePort network edge port
isIngress true to indicate host-to-network direction; false for network-to-host direction
Returns
new phantom edge link
Definition at line 71 of file DefaultEdgeLink.java.
References org.onosproject.net.DefaultEdgeLink.DefaultEdgeLink(), create-flow.location, org.onosproject.net.HostId.NONE, org.onosproject.net.provider.ProviderId.NONE, and org.onosproject.net.PortNumber.P0.
static DefaultEdgeLink org.onosproject.net.DefaultEdgeLink.createEdgeLink (Host host, boolean isIngress) static
Creates a an edge link, to the specified end-station.
Parameters
host host
isIngress true to indicate host-to-network direction; false for network-to-host direction
Returns
new phantom edge link
Definition at line 89 of file DefaultEdgeLink.java.
References org.onosproject.net.DefaultEdgeLink.DefaultEdgeLink(), org.onosproject.net.Host.id(), org.onosproject.net.Host.location(), org.onosproject.net.provider.ProviderId.NONE, and org.onosproject.net.PortNumber.P0.
HostId org.onosproject.net.DefaultEdgeLink.hostId ()
Returns the host identification.
Returns
host identifier
Implements org.onosproject.net.EdgeLink.
Definition at line 53 of file DefaultEdgeLink.java.
HostLocation org.onosproject.net.DefaultEdgeLink.hostLocation ()
Returns the connection point where the host attaches to the network infrastructure.
Returns
host location point
Implements org.onosproject.net.EdgeLink.
Definition at line 58 of file DefaultEdgeLink.java.
Referenced by org.onosproject.net.DefaultEdgeLink.DefaultEdgeLink().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/DefaultEdgeLink.java