onos: org.onosproject.incubator.net.tunnel.DefaultTunnel Class Reference
org.onosproject.incubator.net.tunnel.DefaultTunnel Class Reference
The default implementation of an network tunnel.
Public Member Functions
DefaultTunnel (ProviderId producerName, TunnelEndPoint src, TunnelEndPoint dst, Type type, DefaultGroupId groupId, TunnelId tunnelId, TunnelName tunnelName, Path path, Annotations...annotations)
Creates an active infrastructure tunnel using the supplied information.
DefaultTunnel (ProviderId producerName, TunnelEndPoint src, TunnelEndPoint dst, Type type, State state, DefaultGroupId groupId, TunnelId tunnelId, TunnelName tunnelName, Path path, Annotations...annotations)
Creates an tunnel using the supplied information.
TunnelEndPoint src ()
the origin of a tunnel.
TunnelEndPoint dst ()
the terminal of a tunnel.
Type type ()
Returns the tunnel type.
State state ()
Returns the tunnel state.
NetworkResource resource ()
Network resource backing the tunnel, e.g.
TunnelId tunnelId ()
Returns tunnel identify generated by ONOS as primary key.
DefaultGroupId groupId ()
Returns group flow table id which a tunnel match up.
TunnelName tunnelName ()
Return the name of a tunnel.
Path path ()
Returns the path of the tunnel.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel ()
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel (ProviderId providerId, Annotations...annotations)
Creates a model entity attributed to the specified provider and optionally annotated.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
The default implementation of an network tunnel.
supports for creating a tunnel by connect point ,IP address, MAC address, device and so on.
Definition at line 35 of file DefaultTunnel.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel (ProviderId producerName, TunnelEndPoint src, TunnelEndPoint dst, Type type, DefaultGroupId groupId, TunnelId tunnelId, TunnelName tunnelName, Path path, Annotations... annotations)
Creates an active infrastructure tunnel using the supplied information.
Parameters
producerName provider identity
src tunnel source
dst tunnel destination
type tunnel type
groupId groupId
tunnelId tunnelId
tunnelName tunnel name
path the path of tunnel
annotations optional key/value annotations
Definition at line 62 of file DefaultTunnel.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.incubator.net.tunnel.DefaultTunnel.dst(), org.onosproject.incubator.net.tunnel.DefaultTunnel.groupId(), org.onosproject.incubator.net.tunnel.DefaultTunnel.path(), org.onosproject.incubator.net.tunnel.DefaultTunnel.src(), org.onosproject.incubator.net.tunnel.DefaultTunnel.tunnelId(), org.onosproject.incubator.net.tunnel.DefaultTunnel.tunnelName(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.type().
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnel.equals().
org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel (ProviderId producerName, TunnelEndPoint src, TunnelEndPoint dst, Type type, State state, DefaultGroupId groupId, TunnelId tunnelId, TunnelName tunnelName, Path path, Annotations... annotations)
Creates an tunnel using the supplied information.
Parameters
producerName provider identity
src tunnel source
dst tunnel destination
type tunnel type
state tunnel state
groupId groupId
tunnelId tunnelId
tunnelName tunnel name
path the path of tunnel
annotations optional key/value annotations
Definition at line 84 of file DefaultTunnel.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.incubator.net.tunnel.DefaultTunnel.dst(), org.onosproject.incubator.net.tunnel.DefaultTunnel.groupId(), org.onosproject.incubator.net.tunnel.DefaultTunnel.path(), org.onosproject.incubator.net.tunnel.DefaultTunnel.src(), org.onosproject.incubator.net.tunnel.DefaultTunnel.state(), org.onosproject.incubator.net.tunnel.DefaultTunnel.tunnelId(), org.onosproject.incubator.net.tunnel.DefaultTunnel.tunnelName(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.type().
Member Function Documentation
TunnelEndPoint org.onosproject.incubator.net.tunnel.DefaultTunnel.dst ()
the terminal of a tunnel.
Returns
the terminal of a tunnel
Implements org.onosproject.incubator.net.tunnel.Tunnel.
Definition at line 105 of file DefaultTunnel.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel(), org.onosproject.incubator.net.tunnel.DefaultTunnel.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.toString().
boolean org.onosproject.incubator.net.tunnel.DefaultTunnel.equals (Object obj)
Definition at line 152 of file DefaultTunnel.java.
References org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel().
DefaultGroupId org.onosproject.incubator.net.tunnel.DefaultTunnel.groupId ()
Returns group flow table id which a tunnel match up.
Returns
OpenFlowGroupId
Implements org.onosproject.incubator.net.tunnel.Tunnel.
Definition at line 130 of file DefaultTunnel.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel(), org.onosproject.incubator.net.tunnel.DefaultTunnel.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.toString().
int org.onosproject.incubator.net.tunnel.DefaultTunnel.hashCode ()
Definition at line 146 of file DefaultTunnel.java.
References org.onosproject.incubator.net.tunnel.DefaultTunnel.dst(), org.onosproject.incubator.net.tunnel.DefaultTunnel.groupId(), org.onosproject.incubator.net.tunnel.DefaultTunnel.path(), org.onosproject.incubator.net.tunnel.DefaultTunnel.src(), org.onosproject.incubator.net.tunnel.DefaultTunnel.state(), org.onosproject.incubator.net.tunnel.DefaultTunnel.tunnelId(), org.onosproject.incubator.net.tunnel.DefaultTunnel.tunnelName(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.type().
Path org.onosproject.incubator.net.tunnel.DefaultTunnel.path ()
Returns the path of the tunnel.
Returns
the path of the tunnel
Implements org.onosproject.incubator.net.tunnel.Tunnel.
Definition at line 141 of file DefaultTunnel.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel(), org.onosproject.incubator.net.tunnel.DefaultTunnel.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.toString().
NetworkResource org.onosproject.incubator.net.tunnel.DefaultTunnel.resource ()
Network resource backing the tunnel, e.g.
lambda, VLAN id, MPLS tag.
Returns
backing resource
Implements org.onosproject.incubator.net.tunnel.Tunnel.
Definition at line 120 of file DefaultTunnel.java.
TunnelEndPoint org.onosproject.incubator.net.tunnel.DefaultTunnel.src ()
the origin of a tunnel.
Returns
the origin of a tunnel
Implements org.onosproject.incubator.net.tunnel.Tunnel.
Definition at line 100 of file DefaultTunnel.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel(), org.onosproject.incubator.net.tunnel.DefaultTunnel.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.toString().
State org.onosproject.incubator.net.tunnel.DefaultTunnel.state ()
Returns the tunnel state.
Returns
tunnel state
Implements org.onosproject.incubator.net.tunnel.Tunnel.
Definition at line 115 of file DefaultTunnel.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel(), org.onosproject.incubator.net.tunnel.DefaultTunnel.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.toString().
String org.onosproject.incubator.net.tunnel.DefaultTunnel.toString ()
Definition at line 171 of file DefaultTunnel.java.
References org.onosproject.incubator.net.tunnel.DefaultTunnel.dst(), org.onosproject.incubator.net.tunnel.DefaultTunnel.groupId(), org.onosproject.incubator.net.tunnel.DefaultTunnel.path(), org.onosproject.incubator.net.tunnel.DefaultTunnel.src(), org.onosproject.incubator.net.tunnel.DefaultTunnel.state(), org.onosproject.incubator.net.tunnel.DefaultTunnel.tunnelId(), org.onosproject.incubator.net.tunnel.DefaultTunnel.tunnelName(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.type().
TunnelId org.onosproject.incubator.net.tunnel.DefaultTunnel.tunnelId ()
Returns tunnel identify generated by ONOS as primary key.
Returns
TunnelId
Implements org.onosproject.incubator.net.tunnel.Tunnel.
Definition at line 125 of file DefaultTunnel.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel(), org.onosproject.incubator.net.tunnel.DefaultTunnel.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.toString().
TunnelName org.onosproject.incubator.net.tunnel.DefaultTunnel.tunnelName ()
Return the name of a tunnel.
Returns
Tunnel Name
Implements org.onosproject.incubator.net.tunnel.Tunnel.
Definition at line 135 of file DefaultTunnel.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel(), org.onosproject.incubator.net.tunnel.DefaultTunnel.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.toString().
Type org.onosproject.incubator.net.tunnel.DefaultTunnel.type ()
Returns the tunnel type.
Returns
tunnel type
Implements org.onosproject.incubator.net.tunnel.Tunnel.
Definition at line 110 of file DefaultTunnel.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnel.DefaultTunnel(), org.onosproject.incubator.net.tunnel.DefaultTunnel.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultTunnel.toString().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/tunnel/DefaultTunnel.java