onos: org.onosproject.incubator.store.meter.impl.DistributedMeterStore Class Reference
org.onosproject.incubator.store.meter.impl.DistributedMeterStore Class Reference
A distributed meter store implementation.
Public Member Functions
void activate ()
void deactivate ()
CompletableFuture
< MeterStoreResult > storeMeter (Meter meter)
Adds a meter to the store.
CompletableFuture
< MeterStoreResult > deleteMeter (Meter meter)
Deletes a meter from the store.
CompletableFuture
< MeterStoreResult > updateMeter (Meter meter)
Updates a meter whose meter id is the same as the passed meter.
void updateMeterState (Meter meter)
Updates a given meter's state with the provided state.
Meter getMeter (MeterKey key)
Obtains a meter matching the given meter key.
Collection< Meter > getAllMeters ()
Returns all meters stored in the store.
void failedMeter (MeterOperation op, MeterFailReason reason)
Update the store by deleting the failed meter.
void deleteMeterNow (Meter m)
Delete this meter immediately.
Detailed Description
A distributed meter store implementation.
Meters are stored consistently across the cluster.
Definition at line 66 of file DistributedMeterStore.java.
Member Function Documentation
void org.onosproject.incubator.store.meter.impl.DistributedMeterStore.activate ()
Definition at line 91 of file DistributedMeterStore.java.
References org.onosproject.store.serializers.KryoNamespaces.API, and org.onosproject.store.service.Serializer.using().
void org.onosproject.incubator.store.meter.impl.DistributedMeterStore.deactivate ()
Definition at line 115 of file DistributedMeterStore.java.
CompletableFuture<MeterStoreResult> org.onosproject.incubator.store.meter.impl.DistributedMeterStore.deleteMeter (Meter meter)
Deletes a meter from the store.
Parameters
meter a meter
Returns
a future indicating the result of the store operation
Implements org.onosproject.net.meter.MeterStore.
Definition at line 140 of file DistributedMeterStore.java.
References org.onosproject.net.meter.Meter.id().
void org.onosproject.incubator.store.meter.impl.DistributedMeterStore.deleteMeterNow (Meter m)
Delete this meter immediately.
Parameters
m a meter
Implements org.onosproject.net.meter.MeterStore.
Definition at line 213 of file DistributedMeterStore.java.
References org.onosproject.net.meter.Meter.id().
void org.onosproject.incubator.store.meter.impl.DistributedMeterStore.failedMeter (MeterOperation op, MeterFailReason reason)
Update the store by deleting the failed meter.
Notifies the delegate that the meter failed to allow it to nofity the app.
Parameters
op a failed meter operation
reason a failure reason
Implements org.onosproject.net.meter.MeterStore.
Definition at line 206 of file DistributedMeterStore.java.
References find-flow.deviceId.
Collection<Meter> org.onosproject.incubator.store.meter.impl.DistributedMeterStore.getAllMeters ()
Returns all meters stored in the store.
Returns
a collection of meters
Implements org.onosproject.net.meter.MeterStore.
Definition at line 200 of file DistributedMeterStore.java.
References org.onosproject.incubator.store.meter.impl.MeterData.meter().
Meter org.onosproject.incubator.store.meter.impl.DistributedMeterStore.getMeter (MeterKey key)
Obtains a meter matching the given meter key.
Parameters
key a meter key
Returns
a meter
Implements org.onosproject.net.meter.MeterStore.
Definition at line 194 of file DistributedMeterStore.java.
CompletableFuture<MeterStoreResult> org.onosproject.incubator.store.meter.impl.DistributedMeterStore.storeMeter (Meter meter)
Adds a meter to the store.
Parameters
meter a meter
Returns
a future indicating the result of the store operation
Implements org.onosproject.net.meter.MeterStore.
Definition at line 123 of file DistributedMeterStore.java.
References org.onosproject.net.meter.Meter.id().
CompletableFuture<MeterStoreResult> org.onosproject.incubator.store.meter.impl.DistributedMeterStore.updateMeter (Meter meter)
Updates a meter whose meter id is the same as the passed meter.
Parameters
meter a new meter
Returns
a future indicating the result of the store operation
Implements org.onosproject.net.meter.MeterStore.
Definition at line 162 of file DistributedMeterStore.java.
References org.onosproject.net.meter.Meter.id(), and org.onosproject.net.meter.MeterFailReason.INVALID_METER.
void org.onosproject.incubator.store.meter.impl.DistributedMeterStore.updateMeterState (Meter meter)
Updates a given meter's state with the provided state.
Parameters
meter a meter
Implements org.onosproject.net.meter.MeterStore.
Definition at line 179 of file DistributedMeterStore.java.
References org.onosproject.net.meter.Meter.id().
The documentation for this class was generated from the following file:
incubator/store/src/main/java/org/onosproject/incubator/store/meter/impl/DistributedMeterStore.java