onos: org.onosproject.incubator.net.virtual .DefaultVirtualNetwork Class Reference
org.onosproject.incubator.net.virtual .DefaultVirtualNetwork Class Reference
Default implementation of the virtual network descriptor.
Public Member Functions
DefaultVirtualNetwork (NetworkId id, TenantId tenantId)
Creates a new virtual network descriptor.
NetworkId id ()
Returns the network identifier.
TenantId tenantId ()
Returns the identifier of the tenant to which this virtual network belongs.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of the virtual network descriptor.
Definition at line 25 of file DefaultVirtualNetwork.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.DefaultVirtualNetwork (NetworkId id, TenantId tenantId)
Creates a new virtual network descriptor.
Parameters
id network identifier
tenantId tenant identifier
Definition at line 36 of file DefaultVirtualNetwork.java.
References org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.id(), and org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.tenantId().
Referenced by org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.equals().
Member Function Documentation
boolean org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.equals (Object obj)
Definition at line 57 of file DefaultVirtualNetwork.java.
References org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.DefaultVirtualNetwork(), and find-device.id.
int org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.hashCode ()
Definition at line 52 of file DefaultVirtualNetwork.java.
References org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.id(), and org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.tenantId().
NetworkId org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.id ()
Returns the network identifier.
Returns
network id
Implements org.onosproject.incubator.net.virtual .VirtualNetwork.
Definition at line 42 of file DefaultVirtualNetwork.java.
Referenced by org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.DefaultVirtualNetwork(), org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.hashCode(), and org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.toString().
TenantId org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.tenantId ()
Returns the identifier of the tenant to which this virtual network belongs.
Returns
tenant identifier
Implements org.onosproject.incubator.net.virtual .VirtualNetwork.
Definition at line 47 of file DefaultVirtualNetwork.java.
Referenced by org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.DefaultVirtualNetwork(), org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.hashCode(), and org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.toString().
String org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.toString ()
Definition at line 70 of file DefaultVirtualNetwork.java.
References org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.id(), and org.onosproject.incubator.net.virtual .DefaultVirtualNetwork.tenantId().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/virtual/DefaultVirtualNetwork.java