onos: org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1 Class Reference
Provides PCEP RP object.
Classes
class Builder
Builder class for PCEP rp object.
Public Member Functions
PcepRPObjectVer1 (PcepObjectHeader rpObjHeader, int iRequestIdNum, boolean bOFlag, boolean bBFlag, boolean bRFlag, byte yPriFlag, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize variables.
void setRPObjHeader (PcepObjectHeader obj)
Sets RP Object header.
void setRequestIdNum (int iRequestIdNum)
Sets RequestId Number with specified value.
void setOFlag (boolean bOFlag)
Sets O flag with specified value.
void setBFlag (boolean bBFlag)
Sets B flag with specified value.
void setRFlag (boolean bRFlag)
Sets R flag with specified value.
void setPriFlag (byte yPriFlag)
Sets Priority Flag with specified value.
PcepObjectHeader getRPObjHeader ()
Returns RP Object header.
int getRequestIdNum ()
Returns RequestId Number in RP Object.
boolean getOFlag ()
Returns O flag in RP Object.
boolean getBFlag ()
Returns B flag in RP Object.
boolean getRFlag ()
Returns R flag in RP Object.
byte getPriFlag ()
Returns Priority Flag in RP Object.
int write (ChannelBuffer cb) throws PcepParseException
Writes the RP Object into channel buffer.
LinkedList< PcepValueType > getOptionalTlv ()
Returns list of Optional Tlvs in RP Object.
void setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets list of Optional Tlvs in RP Object and returns its builder.
String toString ()
Static Public Member Functions
static PcepRPObject read (ChannelBuffer cb) throws PcepParseException
Reads the channel buffer and returns the object of PcepRPObject.
Static Public Attributes
static final byte RP_OBJ_TYPE = 1
static final byte RP_OBJ_CLASS = 2
static final byte RP_OBJECT_VERSION = 1
static final short RP_OBJ_MINIMUM_LENGTH = 12
static final int DEFAULT_REQUEST_ID_NUM = 0
static final boolean DEFAULT_OFLAG = false
static final boolean DEFAULT_BFLAG = false
static final boolean DEFAULT_RFLAG = false
static final byte DEFAULT_PRIFLAG = 0
static final int OBJECT_HEADER_LENGTH = 4
static final int OFLAG_SHIFT_VALUE = 5
static final int BFLAG_SHIFT_VALUE = 4
static final int RFLAG_SHIFT_VALUE = 3
static final int OFLAG_TEMP_SHIFT_VALUE = 0x20
static final int BFLAG_TEMP_SHIFT_VALUE = 0x10
static final int RFLAG_TEMP_SHIFT_VALUE = 0x08
static final int PRIFLAG_TEMP_SHIFT_VALUE = 0x07
static final int BIT_SET = 1
static final int BIT_RESET = 0
static final int MINIMUM_COMMON_HEADER_LENGTH = 4
static final PcepObjectHeader DEFAULT_RP_OBJECT_HEADER
Protected Member Functions
int packOptionalTlv (ChannelBuffer cb)
Returns optional tlvs.
Static Protected Member Functions
static LinkedList< PcepValueType > parseOptionalTlv (ChannelBuffer cb) throws PcepParseException
Returns list of optional tlvs.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepRPObjectVer1.class)
Detailed Description
Provides PCEP RP object.
Definition at line 34 of file PcepRPObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.PcepRPObjectVer1 (PcepObjectHeader rpObjHeader, int iRequestIdNum, boolean bOFlag, boolean bBFlag, boolean bRFlag, byte yPriFlag, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize variables.
Parameters
rpObjHeader RP-OBJECT header
iRequestIdNum Request-ID-number
bOFlag O-flag
bBFlag B-flag
bRFlag R-flag
yPriFlag Pri-flag
llOptionalTlv linked list of Optional TLV
Definition at line 98 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.read().
Member Function Documentation
boolean org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.getBFlag ()
Returns B flag in RP Object.
Returns
B flag in RP Object
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 163 of file PcepRPObjectVer1.java.
boolean org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.getOFlag ()
Returns O flag in RP Object.
Returns
O flag in RP Object
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 158 of file PcepRPObjectVer1.java.
LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.getOptionalTlv ()
Returns list of Optional Tlvs in RP Object.
Returns
list of Optional Tlvs in RP Object
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 424 of file PcepRPObjectVer1.java.
byte org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.getPriFlag ()
Returns Priority Flag in RP Object.
Returns
Priority Flag in RP Object
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 173 of file PcepRPObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.getRequestIdNum ()
Returns RequestId Number in RP Object.
Returns
RequestId Number in RP Object
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 153 of file PcepRPObjectVer1.java.
boolean org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.getRFlag ()
Returns R flag in RP Object.
Returns
R flag in RP Object
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 168 of file PcepRPObjectVer1.java.
PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.getRPObjHeader ()
Returns RP Object header.
Returns
rpObjHeader
Definition at line 148 of file PcepRPObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.packOptionalTlv (ChannelBuffer cb) protected
Returns optional tlvs.
Parameters
cb of type channel buffer
Returns
llOptionalTlv linked list of Optional TLV
Definition at line 267 of file PcepRPObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.write().
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.write().
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.parseOptionalTlv (ChannelBuffer cb) throws PcepParseException static protected
Returns list of optional tlvs.
Parameters
cb of type channel buffer.
Returns
llOutOptionalTlv linked list of Optional TLV
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 254 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.read().
static PcepRPObject org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.read (ChannelBuffer cb) throws PcepParseException static
Reads the channel buffer and returns the object of PcepRPObject.
Parameters
cb of type channel buffer
Returns
the object of PcepRPObject
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 184 of file PcepRPObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.BFLAG_TEMP_SHIFT_VALUE, org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.OBJECT_HEADER_LENGTH, org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.OFLAG_TEMP_SHIFT_VALUE, org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.parseOptionalTlv(), org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.PcepRPObjectVer1(), org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.PRIFLAG_TEMP_SHIFT_VALUE, and org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.RFLAG_TEMP_SHIFT_VALUE.
void org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.setBFlag (boolean value)
Sets B flag with specified value.
Parameters
value B flag
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 129 of file PcepRPObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.setOFlag (boolean value)
Sets O flag with specified value.
Parameters
value O flag
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 124 of file PcepRPObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets list of Optional Tlvs in RP Object and returns its builder.
Parameters
llOptionalTlv list of Optional Tlvs
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 429 of file PcepRPObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.setPriFlag (byte value)
Sets Priority Flag with specified value.
Parameters
value Priority Flag
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 139 of file PcepRPObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.setRequestIdNum (int value)
Sets RequestId Number with specified value.
Parameters
value RequestId Number
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 119 of file PcepRPObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.setRFlag (boolean value)
Sets R flag with specified value.
Parameters
value R flag
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 134 of file PcepRPObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.setRPObjHeader (PcepObjectHeader obj)
Sets RP Object header.
Parameters
obj RP Object header
Definition at line 114 of file PcepRPObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.toString ()
Definition at line 434 of file PcepRPObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the RP Object into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException while writing RP object into Channel Buffer.
Implements org.onosproject.pcepio.protocol.PcepRPObject.
Definition at line 214 of file PcepRPObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.BFLAG_SHIFT_VALUE, find-link-in-cluster.length, org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.OFLAG_SHIFT_VALUE, org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.packOptionalTlv(), and org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.RFLAG_SHIFT_VALUE.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.packOptionalTlv().
Member Data Documentation
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.BFLAG_SHIFT_VALUE = 4 static
Definition at line 66 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.write().
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.BFLAG_TEMP_SHIFT_VALUE = 0x10 static
Definition at line 69 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.read().
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.BIT_RESET = 0 static
Definition at line 73 of file PcepRPObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.BIT_SET = 1 static
Definition at line 72 of file PcepRPObjectVer1.java.
final boolean org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.DEFAULT_BFLAG = false static
Definition at line 61 of file PcepRPObjectVer1.java.
final boolean org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.DEFAULT_OFLAG = false static
Definition at line 60 of file PcepRPObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.DEFAULT_PRIFLAG = 0 static
Definition at line 63 of file PcepRPObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.DEFAULT_REQUEST_ID_NUM = 0 static
Definition at line 58 of file PcepRPObjectVer1.java.
final boolean org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.DEFAULT_RFLAG = false static
Definition at line 62 of file PcepRPObjectVer1.java.
final PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.DEFAULT_RP_OBJECT_HEADER static
Initial value:
= new PcepObjectHeader(RP_OBJ_CLASS, RP_OBJ_TYPE,
            PcepObjectHeader.REQ_OBJ_OPTIONAL_PROCESS, PcepObjectHeader.RSP_OBJ_PROCESSED, RP_OBJ_MINIMUM_LENGTH)
Definition at line 76 of file PcepRPObjectVer1.java.
final Logger org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.log = LoggerFactory.getLogger(PcepRPObjectVer1.class) static protected
Definition at line 51 of file PcepRPObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.MINIMUM_COMMON_HEADER_LENGTH = 4 static
Definition at line 74 of file PcepRPObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.OBJECT_HEADER_LENGTH = 4 static
Definition at line 64 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.read().
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.OFLAG_SHIFT_VALUE = 5 static
Definition at line 65 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.write().
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.OFLAG_TEMP_SHIFT_VALUE = 0x20 static
Definition at line 68 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.read().
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.PRIFLAG_TEMP_SHIFT_VALUE = 0x07 static
Definition at line 71 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.read().
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.RFLAG_SHIFT_VALUE = 3 static
Definition at line 67 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.write().
final int org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.RFLAG_TEMP_SHIFT_VALUE = 0x08 static
Definition at line 70 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.read().
final byte org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.RP_OBJ_CLASS = 2 static
Definition at line 54 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorVer1.parseRPList(), org.onosproject.pcepio.protocol.ver1.PcepErrorInfoVer1.read(), and org.onosproject.pcepio.protocol.ver1.PcepErrorVer1.read().
final short org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.RP_OBJ_MINIMUM_LENGTH = 12 static
Definition at line 56 of file PcepRPObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.RP_OBJ_TYPE = 1 static
Definition at line 53 of file PcepRPObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorVer1.parseRPList().
final byte org.onosproject.pcepio.protocol.ver1.PcepRPObjectVer1.RP_OBJECT_VERSION = 1 static
Definition at line 55 of file PcepRPObjectVer1.java.
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepRPObjectVer1.java