onos: org.onosproject.net.edgeservice.impl.EdgeManager Class Reference
org.onosproject.net.edgeservice.impl.EdgeManager Class Reference
This is an implementation of the edge net service.
Public Member Functions
void activate ()
void deactivate ()
boolean isEdgePoint (ConnectPoint point)
Indicates whether or not the specified connection point is an edge point.
Iterable< ConnectPoint > getEdgePoints ()
Returns a collection of all edge point within the current topology.
Iterable< ConnectPoint > getEdgePoints (DeviceId deviceId)
Returns a collection of all edge point for the specified device.
void emitPacket (ByteBuffer data, Optional< TrafficTreatment > treatment)
Emits the specified packet, with optional treatment to all edge ports.
void emitPacket (DeviceId deviceId, ByteBuffer data, Optional< TrafficTreatment > treatment)
Emits the specified packet, with optional treatment to all edge ports.
Protected Attributes
PacketService packetService
DeviceService deviceService
TopologyService topologyService
Detailed Description
This is an implementation of the edge net service.
Definition at line 66 of file EdgeManager.java.
Member Function Documentation
void org.onosproject.net.edgeservice.impl.EdgeManager.activate ()
Definition at line 88 of file EdgeManager.java.
void org.onosproject.net.edgeservice.impl.EdgeManager.deactivate ()
Definition at line 95 of file EdgeManager.java.
void org.onosproject.net.edgeservice.impl.EdgeManager.emitPacket (ByteBuffer data, Optional< TrafficTreatment > treatment)
Emits the specified packet, with optional treatment to all edge ports.
Parameters
data packet data
treatment optional traffic treatment to apply to the packet
Implements org.onosproject.net.edge.EdgePortService.
Definition at line 124 of file EdgeManager.java.
References org.onosproject.net.flow.DefaultTrafficTreatment.builder(), and org.onosproject.net.edgeservice.impl.EdgeManager.getEdgePoints().
void org.onosproject.net.edgeservice.impl.EdgeManager.emitPacket (DeviceId deviceId, ByteBuffer data, Optional< TrafficTreatment > treatment)
Emits the specified packet, with optional treatment to all edge ports.
Parameters
deviceId device where to send the packet out
data packet data
treatment optional traffic treatment to apply to the packet
Implements org.onosproject.net.edge.EdgePortService.
Definition at line 132 of file EdgeManager.java.
References org.onosproject.net.flow.DefaultTrafficTreatment.builder(), and org.onosproject.net.edgeservice.impl.EdgeManager.getEdgePoints().
Iterable<ConnectPoint> org.onosproject.net.edgeservice.impl.EdgeManager.getEdgePoints ()
Returns a collection of all edge point within the current topology.
Returns
iterable collection of all edge points
Implements org.onosproject.net.edge.EdgePortService.
Definition at line 107 of file EdgeManager.java.
Referenced by org.onosproject.net.edgeservice.impl.EdgeManager.emitPacket(), org.onosproject.net.edgeservice.impl.EdgeManagerTest.testBasics(), and org.onosproject.net.edgeservice.impl.EdgeManagerTest.testInternalCache().
Iterable<ConnectPoint> org.onosproject.net.edgeservice.impl.EdgeManager.getEdgePoints (DeviceId deviceId)
Returns a collection of all edge point for the specified device.
Parameters
deviceId device identifier
Returns
iterable collection of all edge points for the device
Implements org.onosproject.net.edge.EdgePortService.
Definition at line 114 of file EdgeManager.java.
References find-flow.deviceId.
boolean org.onosproject.net.edgeservice.impl.EdgeManager.isEdgePoint (ConnectPoint point)
Indicates whether or not the specified connection point is an edge point.
Parameters
point connection point
Returns
true if edge point
Implements org.onosproject.net.edge.EdgePortService.
Definition at line 102 of file EdgeManager.java.
Referenced by org.onosproject.net.edgeservice.impl.EdgeManagerTest.testBasics(), and org.onosproject.net.edgeservice.impl.EdgeManagerTest.testInternalCache().
Member Data Documentation
DeviceService org.onosproject.net.edgeservice.impl.EdgeManager.deviceService protected
Definition at line 82 of file EdgeManager.java.
Referenced by org.onosproject.net.edgeservice.impl.EdgeManagerTest.testDeviceUpdates().
PacketService org.onosproject.net.edgeservice.impl.EdgeManager.packetService protected
Definition at line 79 of file EdgeManager.java.
TopologyService org.onosproject.net.edgeservice.impl.EdgeManager.topologyService protected
Definition at line 85 of file EdgeManager.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/edgeservice/impl/EdgeManager.java