onos: org.onosproject.store.trivial.SimpleApplicationStoreTest Class Reference
org.onosproject.store.trivial.SimpleApplicationStoreTest Class Reference
Test of the trivial application store implementation.
Public Member Functions
void setUp ()
void tearDown () throws IOException
void create ()
void remove ()
void activate ()
void deactivate ()
void permissions ()
Detailed Description
Test of the trivial application store implementation.
Definition at line 45 of file SimpleApplicationStoreTest.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleApplicationStoreTest.activate ()
Definition at line 96 of file SimpleApplicationStoreTest.java.
References org.onosproject.core.Application.id().
void org.onosproject.store.trivial.SimpleApplicationStoreTest.create ()
Definition at line 76 of file SimpleApplicationStoreTest.java.
References org.onosproject.core.Application.id().
void org.onosproject.store.trivial.SimpleApplicationStoreTest.deactivate ()
Definition at line 106 of file SimpleApplicationStoreTest.java.
References org.onosproject.core.Application.id().
void org.onosproject.store.trivial.SimpleApplicationStoreTest.permissions ()
Definition at line 116 of file SimpleApplicationStoreTest.java.
References org.onosproject.core.Application.id(), and onos.size.
void org.onosproject.store.trivial.SimpleApplicationStoreTest.remove ()
Definition at line 87 of file SimpleApplicationStoreTest.java.
void org.onosproject.store.trivial.SimpleApplicationStoreTest.setUp ()
Definition at line 54 of file SimpleApplicationStoreTest.java.
void org.onosproject.store.trivial.SimpleApplicationStoreTest.tearDown () throws IOException
Definition at line 62 of file SimpleApplicationStoreTest.java.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleApplicationStoreTest.java