onos: org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId Class Reference
org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId Class Reference
Implements BGP attribute ISIS Area Identifier.
Public Member Functions
BgpAttrNodeIsIsAreaId (byte[] isisAreaId)
Constructor to initialize value.
byte[] attrNodeIsIsAreaId ()
Returns ISIS area Identifier.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpAttrNodeIsIsAreaId of (final byte[] isisAreaId)
Returns object of this class with specified values.
static BgpAttrNodeIsIsAreaId read (ChannelBuffer cb) throws BgpParseException
Reads the IS-IS Area Identifier.
Static Public Attributes
static final int ATTRNODE_ISISAREAID = 1027
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP attribute ISIS Area Identifier.
Definition at line 33 of file BgpAttrNodeIsIsAreaId.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.BgpAttrNodeIsIsAreaId (byte[] isisAreaId)
Constructor to initialize value.
Parameters
isisAreaId ISIS area Identifier
Definition at line 48 of file BgpAttrNodeIsIsAreaId.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.equals(), and org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.of().
Member Function Documentation
byte [] org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.attrNodeIsIsAreaId ()
Returns ISIS area Identifier.
Returns
Area ID
Definition at line 92 of file BgpAttrNodeIsIsAreaId.java.
int org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 132 of file BgpAttrNodeIsIsAreaId.java.
boolean org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.equals (Object obj)
Definition at line 107 of file BgpAttrNodeIsIsAreaId.java.
References org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.BgpAttrNodeIsIsAreaId().
short org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 97 of file BgpAttrNodeIsIsAreaId.java.
References org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.ATTRNODE_ISISAREAID.
int org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.hashCode ()
Definition at line 102 of file BgpAttrNodeIsIsAreaId.java.
static BgpAttrNodeIsIsAreaId org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.of (final byte[] isisAreaId) static
Returns object of this class with specified values.
Parameters
isisAreaId ISIS area Identifier
Returns
object of BgpAttrNodeIsIsAreaId
Definition at line 58 of file BgpAttrNodeIsIsAreaId.java.
References org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.BgpAttrNodeIsIsAreaId().
static BgpAttrNodeIsIsAreaId org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.read (ChannelBuffer cb) throws BgpParseException static
Reads the IS-IS Area Identifier.
Parameters
cb ChannelBuffer
Returns
object of BgpAttrNodeIsIsAreaId
Exceptions
BgpParseException while parsing BgpAttrNodeIsIsAreaId
Definition at line 69 of file BgpAttrNodeIsIsAreaId.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.toString ()
Definition at line 126 of file BgpAttrNodeIsIsAreaId.java.
int org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 120 of file BgpAttrNodeIsIsAreaId.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.ATTRNODE_ISISAREAID = 1027 static
Definition at line 38 of file BgpAttrNodeIsIsAreaId.java.
Referenced by org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.getType().
final Logger org.onosproject.bgpio.types.attr.BgpAttrNodeIsIsAreaId.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpAttrNodeIsIsAreaId.class)
Definition at line 35 of file BgpAttrNodeIsIsAreaId.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpAttrNodeIsIsAreaId.java