onos: org.onosproject.store.service.MapInfo Class Reference
org.onosproject.store.service.MapInfo Class Reference
Metadata information for a consistent map.
Public Member Functions
MapInfo (String name, int size)
String name ()
Returns the name of the map.
int size ()
Returns the number of entries in the map.
Detailed Description
Metadata information for a consistent map.
Definition at line 21 of file MapInfo.java.
Constructor & Destructor Documentation
org.onosproject.store.service.MapInfo.MapInfo (String name, int size)
Definition at line 25 of file MapInfo.java.
References org.onosproject.store.service.MapInfo.name(), and org.onosproject.store.service.MapInfo.size().
Member Function Documentation
String org.onosproject.store.service.MapInfo.name ()
Returns the name of the map.
Returns
map name
Definition at line 35 of file MapInfo.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.store.service.MapInfo.MapInfo(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
int org.onosproject.store.service.MapInfo.size ()
Returns the number of entries in the map.
Returns
map size
Definition at line 44 of file MapInfo.java.
Referenced by org.onosproject.store.service.MapInfo.MapInfo().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/store/service/MapInfo.java