onos: org.onosproject.rest.DevicesResourceTest Class Reference
org.onosproject.rest.DevicesResourceTest Class Reference
Unit tests for devices REST APIs.
Classes
class DeviceJsonMatcher
Hamcrest matcher to check that an device representation in JSON matches the actual device.
Public Member Functions
void setUpMocks ()
Initializes test mocks and environment.
void tearDownMocks ()
Verifies test mocks.
void testDevicesEmptyArray ()
Tests the result of the rest api GET when there are no devices.
void testDevices ()
Tests the result of the rest api GET when there are devices present.
void testDevicesSingle ()
Tests the result of a rest api GET for a single device.
void testDeviceAndPorts ()
Tests the result of a rest api GET for the ports of a single device.
void testBadGet ()
Tests that a fetch of a non-existent device object throws an exception.
Public Member Functions inherited from org.onosproject.rest.ResourceTest
int getPort (int defaultPort)
Assigns an available port for the test.
AppDescriptor configure ()
Detailed Description
Unit tests for devices REST APIs.
Definition at line 62 of file DevicesResourceTest.java.
Member Function Documentation
void org.onosproject.rest.DevicesResourceTest.setUpMocks ()
Initializes test mocks and environment.
Definition at line 213 of file DevicesResourceTest.java.
References org.onosproject.net.device.DeviceService.getRole(), org.onosproject.net.device.DeviceService.isAvailable(), and org.onosproject.net.MastershipRole.MASTER.
void org.onosproject.rest.DevicesResourceTest.tearDownMocks ()
Verifies test mocks.
Definition at line 238 of file DevicesResourceTest.java.
void org.onosproject.rest.DevicesResourceTest.testBadGet ()
Tests that a fetch of a non-existent device object throws an exception.
Definition at line 361 of file DevicesResourceTest.java.
References org.onosproject.net.device.DeviceService.getDevice().
void org.onosproject.rest.DevicesResourceTest.testDeviceAndPorts ()
Tests the result of a rest api GET for the ports of a single device.
Definition at line 314 of file DevicesResourceTest.java.
References create-flow.device, find-flow.deviceId, org.onosproject.net.device.DeviceService.getDevice(), and org.onosproject.net.device.DeviceService.getPorts().
void org.onosproject.rest.DevicesResourceTest.testDevices ()
Tests the result of the rest api GET when there are devices present.
Definition at line 259 of file DevicesResourceTest.java.
References create-flow.device, and org.onosproject.net.device.DeviceService.getDevices().
void org.onosproject.rest.DevicesResourceTest.testDevicesEmptyArray ()
Tests the result of the rest api GET when there are no devices.
Definition at line 246 of file DevicesResourceTest.java.
References org.onosproject.net.device.DeviceService.getDevices().
void org.onosproject.rest.DevicesResourceTest.testDevicesSingle ()
Tests the result of a rest api GET for a single device.
Definition at line 293 of file DevicesResourceTest.java.
References create-flow.device, find-flow.deviceId, and org.onosproject.net.device.DeviceService.getDevice().
The documentation for this class was generated from the following file:
web/api/src/test/java/org/onosproject/rest/DevicesResourceTest.java