onos: org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv Class Reference
org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv Class Reference
Provides Implementation of Link Local/Remote IdentifiersTlv.
Public Member Functions
LinkLocalRemoteIdentifiersTlv (int linkLocalIdentifer, int linkRemoteIdentifer)
Constructor to initialize parameters.
int getLinkRemoteIdentifier ()
Returns link remote Identifer.
int getLinkLocalIdentifier ()
Returns link local Identifer.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static
LinkLocalRemoteIdentifiersTlv read (ChannelBuffer cb)
Reads the channel buffer and returns object of LinkLocalRemoteIdentifiersTlv.
static
LinkLocalRemoteIdentifiersTlv of (final int linkLocalIdentifer, final int linkRemoteIdentifer)
Returns object of this class with specified link local identifer and link remote identifer.
Static Public Attributes
static final short TYPE = 258
Detailed Description
Provides Implementation of Link Local/Remote IdentifiersTlv.
Definition at line 27 of file LinkLocalRemoteIdentifiersTlv.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.LinkLocalRemoteIdentifiersTlv (int linkLocalIdentifer, int linkRemoteIdentifer)
Constructor to initialize parameters.
Parameters
linkLocalIdentifer link local Identifer
linkRemoteIdentifer link remote Identifer
Definition at line 40 of file LinkLocalRemoteIdentifiersTlv.java.
Referenced by org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.compareTo(), org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.equals(), and org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.of().
Member Function Documentation
int org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 120 of file LinkLocalRemoteIdentifiersTlv.java.
References org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.equals(), and org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.LinkLocalRemoteIdentifiersTlv().
boolean org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.equals (Object obj)
Definition at line 74 of file LinkLocalRemoteIdentifiersTlv.java.
References org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.LinkLocalRemoteIdentifiersTlv().
Referenced by org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.compareTo().
int org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.getLinkLocalIdentifier ()
Returns link local Identifer.
Returns
link local Identifer
Definition at line 59 of file LinkLocalRemoteIdentifiersTlv.java.
int org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.getLinkRemoteIdentifier ()
Returns link remote Identifer.
Returns
link remote Identifer
Definition at line 50 of file LinkLocalRemoteIdentifiersTlv.java.
short org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 64 of file LinkLocalRemoteIdentifiersTlv.java.
References org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.TYPE.
int org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.hashCode ()
Definition at line 69 of file LinkLocalRemoteIdentifiersTlv.java.
static LinkLocalRemoteIdentifiersTlv org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.of (final int linkLocalIdentifer, final int linkRemoteIdentifer) static
Returns object of this class with specified link local identifer and link remote identifer.
Parameters
linkLocalIdentifer link local identifier
linkRemoteIdentifer link remote identifier
Returns
object of LinkLocalRemoteIdentifiersTlv
Definition at line 115 of file LinkLocalRemoteIdentifiersTlv.java.
References org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.LinkLocalRemoteIdentifiersTlv().
static LinkLocalRemoteIdentifiersTlv org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.read (ChannelBuffer cb) static
Reads the channel buffer and returns object of LinkLocalRemoteIdentifiersTlv.
Parameters
cb channelBuffer
Returns
object of LinkLocalRemoteIdentifiersTlv
Definition at line 102 of file LinkLocalRemoteIdentifiersTlv.java.
String org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.toString ()
Definition at line 134 of file LinkLocalRemoteIdentifiersTlv.java.
References org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.TYPE.
int org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 87 of file LinkLocalRemoteIdentifiersTlv.java.
References org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.TYPE.
Member Data Documentation
final short org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.TYPE = 258 static
Definition at line 28 of file LinkLocalRemoteIdentifiersTlv.java.
Referenced by org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.getType(), org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.toString(), and org.onosproject.bgpio.types.LinkLocalRemoteIdentifiersTlv.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/LinkLocalRemoteIdentifiersTlv.java