onos: org.onosproject.net.statistic.DefaultLoadTest Class Reference
org.onosproject.net.statistic.DefaultLoadTest Class Reference
Unit tests for DefaultLoad class.
Public Member Functions
void reset ()
void testDefaultConstructor ()
Tests the default constructor.
void testCurrentPreviousConstructor ()
Tests the current-previous constructor.
void testCurrentPreviousIntervalConstructor ()
Tests the current-previous-interval constructor.
void testToString ()
Tests the toString operation.
void testSettingPollInterval ()
Tests setting the poll interval.
Detailed Description
Unit tests for DefaultLoad class.
Definition at line 29 of file DefaultLoadTest.java.
Member Function Documentation
void org.onosproject.net.statistic.DefaultLoadTest.reset ()
Definition at line 32 of file DefaultLoadTest.java.
void org.onosproject.net.statistic.DefaultLoadTest.testCurrentPreviousConstructor ()
Tests the current-previous constructor.
Definition at line 52 of file DefaultLoadTest.java.
References org.onosproject.net.statistic.DefaultLoad.latest(), and org.onosproject.net.statistic.DefaultLoad.rate().
void org.onosproject.net.statistic.DefaultLoadTest.testCurrentPreviousIntervalConstructor ()
Tests the current-previous-interval constructor.
Definition at line 64 of file DefaultLoadTest.java.
References org.onosproject.net.statistic.DefaultLoad.latest(), and org.onosproject.net.statistic.DefaultLoad.rate().
void org.onosproject.net.statistic.DefaultLoadTest.testDefaultConstructor ()
Tests the default constructor.
Definition at line 40 of file DefaultLoadTest.java.
References org.onosproject.net.statistic.DefaultLoad.latest(), and org.onosproject.net.statistic.DefaultLoad.rate().
void org.onosproject.net.statistic.DefaultLoadTest.testSettingPollInterval ()
Tests setting the poll interval.
Definition at line 87 of file DefaultLoadTest.java.
void org.onosproject.net.statistic.DefaultLoadTest.testToString ()
Tests the toString operation.
Definition at line 76 of file DefaultLoadTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/statistic/DefaultLoadTest.java