onos: org.onosproject.openflow.controller.Dpid Class Reference
org.onosproject.openflow.controller.Dpid Class Reference
The class representing a network switch DPID.
Public Member Functions
Dpid ()
Default constructor.
Dpid (long value)
Constructor from a long value.
Dpid (String value)
Constructor from a string.
long value ()
Get the value of the DPID.
String toString ()
Convert the DPID value to a ':' separated hexadecimal string.
boolean equals (Object other)
int hashCode ()
Static Public Member Functions
static Dpid dpid (URI uri)
Returns DPID created from the given device URI.
static URI uri (Dpid dpid)
Produces device URI from the given DPID.
static URI uri (long value)
Produces device URI from the given DPID long.
Detailed Description
The class representing a network switch DPID.
This class is immutable.
Definition at line 31 of file Dpid.java.
Constructor & Destructor Documentation
org.onosproject.openflow.controller.Dpid.Dpid ()
Default constructor.
Definition at line 40 of file Dpid.java.
Referenced by org.onosproject.openflow.controller.Dpid.dpid(), and org.onosproject.openflow.controller.Dpid.equals().
org.onosproject.openflow.controller.Dpid.Dpid (long value)
Constructor from a long value.
Parameters
value the value to use.
Definition at line 49 of file Dpid.java.
References org.onosproject.openflow.controller.Dpid.value().
org.onosproject.openflow.controller.Dpid.Dpid (String value)
Constructor from a string.
Parameters
value the value to use.
Definition at line 58 of file Dpid.java.
References org.onosproject.openflow.controller.Dpid.value().
Member Function Documentation
static Dpid org.onosproject.openflow.controller.Dpid.dpid (URI uri) static
Returns DPID created from the given device URI.
Parameters
uri device URI
Returns
dpid
Definition at line 103 of file Dpid.java.
References org.onosproject.openflow.controller.Dpid.Dpid().
Referenced by opticalUtils.LINCSwitch.read_from_cli(), and opticalUtils.LINCSwitch.start().
boolean org.onosproject.openflow.controller.Dpid.equals (Object other)
Definition at line 82 of file Dpid.java.
References org.onosproject.openflow.controller.Dpid.Dpid(), and org.onosproject.openflow.controller.Dpid.value().
int org.onosproject.openflow.controller.Dpid.hashCode ()
Definition at line 93 of file Dpid.java.
References org.onosproject.openflow.controller.Dpid.value().
String org.onosproject.openflow.controller.Dpid.toString ()
Convert the DPID value to a ':' separated hexadecimal string.
Returns
the DPID value as a ':' separated hexadecimal string.
Definition at line 77 of file Dpid.java.
static URI org.onosproject.openflow.controller.Dpid.uri (Dpid dpid) static
Produces device URI from the given DPID.
Parameters
dpid device dpid
Returns
device URI
Definition at line 114 of file Dpid.java.
Referenced by org.onosproject.provider.of.flow.impl.FlowEntryBuilder.build().
static URI org.onosproject.openflow.controller.Dpid.uri (long value) static
Produces device URI from the given DPID long.
Parameters
value device dpid as long
Returns
device URI
Definition at line 124 of file Dpid.java.
long org.onosproject.openflow.controller.Dpid.value ()
Get the value of the DPID.
Returns
the value of the DPID.
Definition at line 67 of file Dpid.java.
Referenced by org.onosproject.openflow.controller.Dpid.Dpid(), org.onosproject.openflow.controller.Dpid.equals(), and org.onosproject.openflow.controller.Dpid.hashCode().
The documentation for this class was generated from the following file:
protocols/openflow/api/src/main/java/org/onosproject/openflow/controller/Dpid.java