onos: org.onosproject.net.intent.PointToPointIntent Class Reference
org.onosproject.net.intent.PointToPointIntent Class Reference
Abstraction of point-to-point connectivity.
Classes
class Builder
Builder of a point to point intent.
Public Member Functions
ConnectPoint ingressPoint ()
Returns the port on which the ingress traffic should be connected to the egress.
ConnectPoint egressPoint ()
Returns the port on which the traffic should egress.
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.ConnectivityIntent
TrafficSelector selector ()
Returns the match specifying the type of traffic.
TrafficTreatment treatment ()
Returns the action applied to the traffic.
List< Constraint > constraints ()
Returns the set of connectivity constraints.
Public Member Functions inherited from org.onosproject.net.intent.Intent
IntentId id ()
Returns the intent identifier.
ApplicationId appId ()
Returns the identifier of the application that requested the intent.
int priority ()
Returns the priority of the intent.
Collection< NetworkResource > resources ()
Returns the collection of resources required for this intent.
boolean isInstallable ()
Indicates whether or not the intent is installable.
final int hashCode ()
final boolean equals (Object obj)
Key key ()
Static Public Member Functions
static PointToPointIntent.Builder builder ()
Returns a new point to point intent builder.
Static Public Member Functions inherited from org.onosproject.net.intent.Intent
static void bindIdGenerator (IdGenerator newIdGenerator)
Binds an id generator for unique intent id generation.
static void unbindIdGenerator (IdGenerator oldIdGenerator)
Unbinds an id generator.
Protected Member Functions
PointToPointIntent ()
Constructor for serializer.
Protected Member Functions inherited from org.onosproject.net.intent.ConnectivityIntent
ConnectivityIntent (ApplicationId appId, Key key, Collection< NetworkResource > resources, TrafficSelector selector, TrafficTreatment treatment, List< Constraint > constraints, int priority)
Creates a connectivity intent that matches on the specified selector and applies the specified treatment.
ConnectivityIntent ()
Constructor for serializer.
Protected Member Functions inherited from org.onosproject.net.intent.Intent
Intent ()
Constructor for serializer.
Intent (ApplicationId appId, Key key, Collection< NetworkResource > resources, int priority)
Creates a new intent.
Additional Inherited Members
Static Public Attributes inherited from org.onosproject.net.intent.Intent
static final int DEFAULT_INTENT_PRIORITY = 100
static final int MAX_PRIORITY = (1 << 16) - 1
static final int MIN_PRIORITY = 1
Static Protected Member Functions inherited from org.onosproject.net.intent.ConnectivityIntent
static Collection
< NetworkResource > resources (Collection< Link > links)
Produces a collection of network resources from the given links.
Detailed Description
Abstraction of point-to-point connectivity.
Definition at line 36 of file PointToPointIntent.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.PointToPointIntent.PointToPointIntent () protected
Constructor for serializer.
Definition at line 174 of file PointToPointIntent.java.
Member Function Documentation
static PointToPointIntent.Builder org.onosproject.net.intent.PointToPointIntent.builder () static
Returns a new point to point intent builder.
The application id, ingress point and egress point are required fields. If they are not set by calls to the appropriate methods, an exception will be thrown.
Returns
point to point builder
Definition at line 49 of file PointToPointIntent.java.
ConnectPoint org.onosproject.net.intent.PointToPointIntent.egressPoint ()
Returns the port on which the traffic should egress.
Returns
egress port
Definition at line 195 of file PointToPointIntent.java.
Referenced by org.onosproject.net.intent.PointToPointIntent.toString().
ConnectPoint org.onosproject.net.intent.PointToPointIntent.ingressPoint ()
Returns the port on which the ingress traffic should be connected to the egress.
Returns
ingress port
Definition at line 186 of file PointToPointIntent.java.
String org.onosproject.net.intent.PointToPointIntent.toString ()
Definition at line 200 of file PointToPointIntent.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.ConnectivityIntent.constraints(), org.onosproject.net.intent.PointToPointIntent.egressPoint(), org.onosproject.net.intent.Intent.key(), org.onosproject.net.intent.Intent.priority(), org.onosproject.net.intent.Intent.resources(), org.onosproject.net.intent.ConnectivityIntent.selector(), and org.onosproject.net.intent.ConnectivityIntent.treatment().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/PointToPointIntent.java