onos: org.onlab.nio.service.IOLoopMessaging Class Reference
org.onlab.nio.service.IOLoopMessaging Class Reference
MessagingService implementation based on IOLoop.
Public Member Functions
void start (Endpoint localEp) throws IOException
Activates IO Loops.
void stop ()
Shuts down IO loops.
CompletableFuture< Void > sendAsync (Endpoint ep, String type, byte[] payload)
Sends a message asynchronously to the specified communication end point.
CompletableFuture< byte[]> sendAndReceive (Endpoint ep, String type, byte[] payload)
Sends a message synchronously and waits for a response.
void registerHandler (String type, Consumer< byte[]> handler, Executor executor)
Registers a new message handler for message type.
void registerHandler (String type, Function< byte[], byte[]> handler, Executor executor)
Registers a new message handler for message type.
void registerHandler (String type, Function< byte[], CompletableFuture< byte[]>> handler)
Registers a new message handler for message type.
void unregisterHandler (String type)
Unregister current handler, if one exists for message type.
Protected Member Functions
CompletableFuture< Void > sendAsync (Endpoint ep, DefaultMessage message)
void dispatchLocally (DefaultMessage message)
Detailed Description
MessagingService implementation based on IOLoop.
Definition at line 57 of file IOLoopMessaging.java.
Member Function Documentation
void org.onlab.nio.service.IOLoopMessaging.dispatchLocally (DefaultMessage message) protected
Definition at line 238 of file IOLoopMessaging.java.
Referenced by org.onlab.nio.service.IOLoopMessaging.sendAsync().
void org.onlab.nio.service.IOLoopMessaging.registerHandler (String type, Consumer< byte[]> handler, Executor executor)
Registers a new message handler for message type.
Parameters
type message type.
handler message handler
executor executor to use for running message handler logic.
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 194 of file IOLoopMessaging.java.
void org.onlab.nio.service.IOLoopMessaging.registerHandler (String type, Function< byte[], byte[]> handler, Executor executor)
Registers a new message handler for message type.
Parameters
type message type.
handler message handler
executor executor to use for running message handler logic.
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 199 of file IOLoopMessaging.java.
References org.onlab.nio.service.IOLoopMessaging.sendAsync().
void org.onlab.nio.service.IOLoopMessaging.registerHandler (String type, Function< byte[], CompletableFuture< byte[]>> handler)
Registers a new message handler for message type.
Parameters
type message type.
handler message handler
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 215 of file IOLoopMessaging.java.
References org.onlab.nio.service.IOLoopMessaging.sendAsync().
CompletableFuture<byte[]> org.onlab.nio.service.IOLoopMessaging.sendAndReceive (Endpoint ep, String type, byte[] payload)
Sends a message synchronously and waits for a response.
Parameters
ep end point to send the message to.
type type of message.
payload message payload.
Returns
a response future
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 176 of file IOLoopMessaging.java.
References org.onlab.nio.service.IOLoopMessaging.sendAsync().
CompletableFuture<Void> org.onlab.nio.service.IOLoopMessaging.sendAsync (Endpoint ep, String type, byte[] payload)
Sends a message asynchronously to the specified communication end point.
The message is specified using the type and payload.
Parameters
ep end point to send the message to.
type type of message.
payload message payload bytes.
Returns
future that is completed when the message is sent
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 141 of file IOLoopMessaging.java.
Referenced by org.onlab.nio.service.IOLoopMessaging.registerHandler(), and org.onlab.nio.service.IOLoopMessaging.sendAndReceive().
CompletableFuture<Void> org.onlab.nio.service.IOLoopMessaging.sendAsync (Endpoint ep, DefaultMessage message) protected
Definition at line 150 of file IOLoopMessaging.java.
References org.onlab.nio.service.IOLoopMessaging.dispatchLocally(), and org.onosproject.store.cluster.messaging.Endpoint.equals().
void org.onlab.nio.service.IOLoopMessaging.start (Endpoint localEp) throws IOException
Activates IO Loops.
Parameters
localEp local end-point
Exceptions
IOException is activation fails
Definition at line 106 of file IOLoopMessaging.java.
References org.onosproject.store.cluster.messaging.Endpoint.host().
void org.onlab.nio.service.IOLoopMessaging.stop ()
Shuts down IO loops.
Definition at line 129 of file IOLoopMessaging.java.
References org.onlab.nio.SelectorLoop.shutdown().
void org.onlab.nio.service.IOLoopMessaging.unregisterHandler (String type)
Unregister current handler, if one exists for message type.
Parameters
type message type
Implements org.onosproject.store.cluster.messaging.MessagingService.
Definition at line 234 of file IOLoopMessaging.java.
The documentation for this class was generated from the following file:
utils/nio/src/main/java/org/onlab/nio/service/IOLoopMessaging.java