onos: org.onosproject.pcepio.types.PcepNaiIpv6Adjacency Class Reference
org.onosproject.pcepio.types.PcepNaiIpv6Adjacency Class Reference
Provides Pcep Nai Ipv6 Adjacency.
Public Member Functions
PcepNaiIpv6Adjacency (byte[] localIpv6, byte[] remoteIpv6)
Constructor to initialize local ipv6 and remote ipv6.
byte getType ()
To get the ST type of the NAI information.
int write (ChannelBuffer bb)
To write the object information to channelBuffer.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static PcepNaiIpv6Adjacency read (ChannelBuffer bb)
Reads from channel buffer and returns object of PcepNAIIpv6AdjacencyVer1.
static PcepNaiIpv6Adjacency of (final byte[] localIpv6Addr, final byte[] remoteIpv6Addr)
Creates object of PcepNaiIpv6Adjacency with local ipv6 address and remote ipv6 address.
Static Public Attributes
static final byte ST_TYPE = 0x04
static final byte IPV6_LEN = 0x10
Detailed Description
Provides Pcep Nai Ipv6 Adjacency.
Definition at line 29 of file PcepNaiIpv6Adjacency.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.PcepNaiIpv6Adjacency (byte[] localIpv6, byte[] remoteIpv6)
Constructor to initialize local ipv6 and remote ipv6.
Parameters
localIpv6 local ipv6 address
remoteIpv6 remote ipv6 address
Definition at line 43 of file PcepNaiIpv6Adjacency.java.
Referenced by org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.equals(), org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.of(), and org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.equals (Object obj)
Definition at line 81 of file PcepNaiIpv6Adjacency.java.
References org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.PcepNaiIpv6Adjacency().
byte org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.getType ()
To get the ST type of the NAI information.
Returns
type of ST info
Implements org.onosproject.pcepio.protocol.PcepNai.
Definition at line 49 of file PcepNaiIpv6Adjacency.java.
References org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.ST_TYPE.
int org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.hashCode ()
Definition at line 76 of file PcepNaiIpv6Adjacency.java.
static PcepNaiIpv6Adjacency org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.of (final byte[] localIpv6Addr, final byte[] remoteIpv6Addr) static
Creates object of PcepNaiIpv6Adjacency with local ipv6 address and remote ipv6 address.
Parameters
localIpv6Addr local ipv6 address
remoteIpv6Addr remote ipv6 address
Returns
object of PcepNaiIpv6Adjacency
Definition at line 101 of file PcepNaiIpv6Adjacency.java.
References org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.PcepNaiIpv6Adjacency().
static PcepNaiIpv6Adjacency org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.read (ChannelBuffer bb) static
Reads from channel buffer and returns object of PcepNAIIpv6AdjacencyVer1.
Parameters
bb of type channel buffer
Returns
object of PcepNAIIpv6AdjacencyVer1
Definition at line 67 of file PcepNaiIpv6Adjacency.java.
References org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.IPV6_LEN, and org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.PcepNaiIpv6Adjacency().
String org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.toString ()
Definition at line 106 of file PcepNaiIpv6Adjacency.java.
int org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.write (ChannelBuffer cb)
To write the object information to channelBuffer.
Parameters
cb of type channel buffer
Returns
length of written bytes.
Implements org.onosproject.pcepio.protocol.PcepNai.
Definition at line 54 of file PcepNaiIpv6Adjacency.java.
Member Data Documentation
final byte org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.IPV6_LEN = 0x10 static
Definition at line 32 of file PcepNaiIpv6Adjacency.java.
Referenced by org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.read().
final byte org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.ST_TYPE = 0x04 static
Definition at line 31 of file PcepNaiIpv6Adjacency.java.
Referenced by org.onosproject.pcepio.types.PcepNaiIpv6Adjacency.getType().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PcepNaiIpv6Adjacency.java