onos: org.onlab.graph.SrlgGraphSearchTest Class Reference
org.onlab.graph.SrlgGraphSearchTest Class Reference
Test of the Suurballe backup path algorithm.
Public Member Functions
void setDefaultWeights ()
void defaultGraphTest ()
void defaultHopCountWeight ()
void onePathPair ()
void checkIsDisjoint (Path< TestVertex, TestEdge > p, Map< TestEdge, Integer > risks)
void complexGraphTest ()
void multiplePathGraphTest ()
void onePath ()
void noPath ()
Public Member Functions inherited from org.onlab.graph.BreadthFirstSearchTest
void defaultGraphTest ()
void defaultHopCountWeight ()
Public Member Functions inherited from org.onlab.graph.AbstractGraphPathSearchTest
void noSuchSourceArgument ()
void nullGraphArgument ()
void nullSourceArgument ()
void samenessThreshold ()
Protected Member Functions
AbstractGraphPathSearch
< TestVertex, TestEdge > graphSearch ()
Creates a test-specific graph search to exercise.
Protected Member Functions inherited from org.onlab.graph.BreadthFirstSearchTest
void executeDefaultTest (int pathCount, int pathLength, double pathCost)
void executeSearch (GraphPathSearch< TestVertex, TestEdge > search, Graph< TestVertex, TestEdge > graph, TestVertex src, TestVertex dst, EdgeWeight< TestVertex, TestEdge > weight, int pathCount, double pathCost)
void executeSinglePathSearch (GraphPathSearch< TestVertex, TestEdge > search, Graph< TestVertex, TestEdge > graph, TestVertex src, TestVertex dst, EdgeWeight< TestVertex, TestEdge > weight, int pathCount, double pathCost)
Protected Member Functions inherited from org.onlab.graph.GraphTest
void printPaths (Set< Path< TestVertex, TestEdge >> paths)
Set< TestVertex > vertexes ()
Set< TestEdge > edges ()
Additional Inherited Members
Protected Attributes inherited from org.onlab.graph.GraphTest
Graph< TestVertex, TestEdge > graph
EdgeWeight< TestVertex, TestEdge > weight
Detailed Description
Test of the Suurballe backup path algorithm.
Definition at line 34 of file SrlgGraphSearchTest.java.
Member Function Documentation
void org.onlab.graph.SrlgGraphSearchTest.checkIsDisjoint (Path< TestVertex, TestEdge > p, Map< TestEdge, Integer > risks)
Definition at line 74 of file SrlgGraphSearchTest.java.
Referenced by org.onlab.graph.SrlgGraphSearchTest.multiplePathGraphTest(), and org.onlab.graph.SrlgGraphSearchTest.onePathPair().
void org.onlab.graph.SrlgGraphSearchTest.complexGraphTest ()
Definition at line 91 of file SrlgGraphSearchTest.java.
References org.onlab.graph.GraphTest.graph, org.onlab.graph.SrlgGraphSearchTest.setDefaultWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SrlgGraphSearchTest.defaultGraphTest ()
Definition at line 46 of file SrlgGraphSearchTest.java.
void org.onlab.graph.SrlgGraphSearchTest.defaultHopCountWeight ()
Definition at line 50 of file SrlgGraphSearchTest.java.
AbstractGraphPathSearch<TestVertex, TestEdge> org.onlab.graph.SrlgGraphSearchTest.graphSearch () protected virtual
Creates a test-specific graph search to exercise.
Returns
graph search
Reimplemented from org.onlab.graph.BreadthFirstSearchTest.
Definition at line 37 of file SrlgGraphSearchTest.java.
void org.onlab.graph.SrlgGraphSearchTest.multiplePathGraphTest ()
Definition at line 113 of file SrlgGraphSearchTest.java.
References org.onlab.graph.SrlgGraphSearchTest.checkIsDisjoint(), org.onlab.graph.GraphTest.graph, org.onlab.graph.SrlgGraphSearchTest.setDefaultWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SrlgGraphSearchTest.noPath ()
Definition at line 157 of file SrlgGraphSearchTest.java.
References org.onlab.graph.GraphTest.graph, org.onlab.graph.SrlgGraphSearchTest.setDefaultWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SrlgGraphSearchTest.onePath ()
Definition at line 137 of file SrlgGraphSearchTest.java.
References org.onlab.graph.GraphTest.graph, org.onlab.graph.SrlgGraphSearchTest.setDefaultWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SrlgGraphSearchTest.onePathPair ()
Definition at line 54 of file SrlgGraphSearchTest.java.
References org.onlab.graph.SrlgGraphSearchTest.checkIsDisjoint(), org.onlab.graph.GraphTest.graph, org.onlab.graph.SrlgGraphSearchTest.setDefaultWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SrlgGraphSearchTest.setDefaultWeights ()
Definition at line 41 of file SrlgGraphSearchTest.java.
References org.onlab.graph.GraphTest.weight.
Referenced by org.onlab.graph.SrlgGraphSearchTest.complexGraphTest(), org.onlab.graph.SrlgGraphSearchTest.multiplePathGraphTest(), org.onlab.graph.SrlgGraphSearchTest.noPath(), org.onlab.graph.SrlgGraphSearchTest.onePath(), and org.onlab.graph.SrlgGraphSearchTest.onePathPair().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/graph/SrlgGraphSearchTest.java