onos: org.onosproject.routing.config.BgpPeer Class Reference
org.onosproject.routing.config.BgpPeer Class Reference
Configuration details for a BGP peer.
Public Member Functions
BgpPeer (@JsonProperty("attachmentDpid") String dpid,@JsonProperty("attachmentPort") long port,@JsonProperty("ipAddress") String ipAddress)
Creates a new BgpPeer.
ConnectPoint connectPoint ()
Gets the connection point of the peer.
IpAddress ipAddress ()
Gets the IP address of the peer.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Configuration details for a BGP peer.
Definition at line 31 of file BgpPeer.java.
Constructor & Destructor Documentation
org.onosproject.routing.config.BgpPeer.BgpPeer (@JsonProperty("attachmentDpid") String dpid, @JsonProperty("attachmentPort") long port, @JsonProperty("ipAddress") String ipAddress)
Creates a new BgpPeer.
Parameters
dpid the DPID of the switch the peer is attached at, as a String
port the port the peer is attached at
ipAddress the IP address of the peer as a String
Definition at line 42 of file BgpPeer.java.
References org.onosproject.net.DeviceId.deviceId(), org.onosproject.net.NetTools.dpidToUri(), org.onosproject.routing.config.BgpPeer.ipAddress(), and org.onosproject.net.PortNumber.portNumber().
Referenced by org.onosproject.routing.config.BgpPeer.equals().
Member Function Documentation
ConnectPoint org.onosproject.routing.config.BgpPeer.connectPoint ()
Gets the connection point of the peer.
Returns
the connection point
Definition at line 56 of file BgpPeer.java.
Referenced by org.onosproject.routing.config.BgpPeer.hashCode(), and org.onosproject.routing.config.BgpPeer.toString().
boolean org.onosproject.routing.config.BgpPeer.equals (Object obj)
Definition at line 75 of file BgpPeer.java.
References org.onosproject.routing.config.BgpPeer.BgpPeer().
int org.onosproject.routing.config.BgpPeer.hashCode ()
Definition at line 70 of file BgpPeer.java.
References org.onosproject.routing.config.BgpPeer.connectPoint(), and org.onosproject.routing.config.BgpPeer.ipAddress().
IpAddress org.onosproject.routing.config.BgpPeer.ipAddress ()
Gets the IP address of the peer.
Returns
the IP address
Definition at line 65 of file BgpPeer.java.
Referenced by org.onosproject.routing.config.BgpPeer.BgpPeer(), org.onosproject.routing.config.BgpPeer.hashCode(), and org.onosproject.routing.config.BgpPeer.toString().
String org.onosproject.routing.config.BgpPeer.toString ()
Definition at line 90 of file BgpPeer.java.
References org.onosproject.routing.config.BgpPeer.connectPoint(), and org.onosproject.routing.config.BgpPeer.ipAddress().
The documentation for this class was generated from the following file:
apps/routing-api/src/main/java/org/onosproject/routing/config/BgpPeer.java