onos: org.onosproject.net.flow.impl.FlowRuleManagerTest Class Reference
org.onosproject.net.flow.impl.FlowRuleManagerTest Class Reference
Test codifying the flow rule service & flow rule provider service contracts.
Classes
class TestApplicationId
Public Member Functions
void setUp ()
void tearDown ()
void getFlowEntries ()
void applyFlowRules ()
void removeFlowRules ()
void flowRemoved ()
void flowMetrics ()
void extraneousFlow ()
void flowMissingRemove ()
void getByAppId ()
void removeByAppId ()
Protected Attributes
FlowRuleService service
FlowRuleProviderRegistry registry
FlowRuleProviderService providerService
TestProvider provider
TestListener listener = new TestListener()
Detailed Description
Test codifying the flow rule service & flow rule provider service contracts.
Definition at line 93 of file FlowRuleManagerTest.java.
Member Function Documentation
void org.onosproject.net.flow.impl.FlowRuleManagerTest.applyFlowRules ()
Definition at line 225 of file FlowRuleManagerTest.java.
References org.onosproject.net.flow.FlowRuleService.getFlowEntries(), org.onosproject.net.flow.FlowEntry.FlowEntryState.PENDING_ADD, and org.onosproject.net.flow.impl.FlowRuleManagerTest.service.
void org.onosproject.net.flow.impl.FlowRuleManagerTest.extraneousFlow ()
Definition at line 334 of file FlowRuleManagerTest.java.
void org.onosproject.net.flow.impl.FlowRuleManagerTest.flowMetrics ()
Definition at line 308 of file FlowRuleManagerTest.java.
References org.onosproject.net.flow.FlowEntry.FlowEntryState.ADDED, and org.onosproject.net.flow.FlowEntry.FlowEntryState.PENDING_ADD.
void org.onosproject.net.flow.impl.FlowRuleManagerTest.flowMissingRemove ()
Definition at line 359 of file FlowRuleManagerTest.java.
void org.onosproject.net.flow.impl.FlowRuleManagerTest.flowRemoved ()
Definition at line 271 of file FlowRuleManagerTest.java.
References org.onosproject.net.flow.FlowEntry.FlowEntryState.REMOVED.
void org.onosproject.net.flow.impl.FlowRuleManagerTest.getByAppId ()
Definition at line 381 of file FlowRuleManagerTest.java.
References org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesById(), and onos.size.
void org.onosproject.net.flow.impl.FlowRuleManagerTest.getFlowEntries ()
Definition at line 190 of file FlowRuleManagerTest.java.
References org.onosproject.net.flow.FlowRuleService.getFlowEntries(), and org.onosproject.net.flow.impl.FlowRuleManagerTest.service.
void org.onosproject.net.flow.impl.FlowRuleManagerTest.removeByAppId ()
Definition at line 391 of file FlowRuleManagerTest.java.
References org.onosproject.net.flow.FlowEntry.FlowEntryState.PENDING_REMOVE.
void org.onosproject.net.flow.impl.FlowRuleManagerTest.removeFlowRules ()
Definition at line 243 of file FlowRuleManagerTest.java.
References org.onosproject.net.flow.FlowEntry.FlowEntryState.ADDED, and org.onosproject.net.flow.FlowEntry.FlowEntryState.PENDING_REMOVE.
void org.onosproject.net.flow.impl.FlowRuleManagerTest.setUp ()
Definition at line 113 of file FlowRuleManagerTest.java.
References org.onosproject.net.flow.impl.FlowRuleManagerTest.listener, org.onosproject.net.flow.impl.FlowRuleManagerTest.provider, org.onosproject.net.flow.impl.FlowRuleManagerTest.providerService, org.onosproject.net.flow.impl.FlowRuleManagerTest.registry, and org.onosproject.net.flow.impl.FlowRuleManagerTest.service.
void org.onosproject.net.flow.impl.FlowRuleManagerTest.tearDown ()
Definition at line 135 of file FlowRuleManagerTest.java.
References org.onosproject.net.flow.impl.FlowRuleManagerTest.listener, org.onosproject.net.flow.impl.FlowRuleManagerTest.provider, and org.onosproject.net.flow.impl.FlowRuleManagerTest.registry.
Member Data Documentation
TestListener org.onosproject.net.flow.impl.FlowRuleManagerTest.listener = new TestListener() protected
Definition at line 108 of file FlowRuleManagerTest.java.
Referenced by org.onosproject.net.flow.impl.FlowRuleManagerTest.setUp(), and org.onosproject.net.flow.impl.FlowRuleManagerTest.tearDown().
TestProvider org.onosproject.net.flow.impl.FlowRuleManagerTest.provider protected
Definition at line 107 of file FlowRuleManagerTest.java.
Referenced by org.onosproject.net.flow.impl.FlowRuleManagerTest.setUp(), and org.onosproject.net.flow.impl.FlowRuleManagerTest.tearDown().
FlowRuleProviderService org.onosproject.net.flow.impl.FlowRuleManagerTest.providerService protected
Definition at line 106 of file FlowRuleManagerTest.java.
Referenced by org.onosproject.net.flow.impl.FlowRuleManagerTest.setUp().
FlowRuleProviderRegistry org.onosproject.net.flow.impl.FlowRuleManagerTest.registry protected
Definition at line 105 of file FlowRuleManagerTest.java.
Referenced by org.onosproject.net.flow.impl.FlowRuleManagerTest.setUp(), and org.onosproject.net.flow.impl.FlowRuleManagerTest.tearDown().
FlowRuleService org.onosproject.net.flow.impl.FlowRuleManagerTest.service protected
Definition at line 104 of file FlowRuleManagerTest.java.
Referenced by org.onosproject.net.flow.impl.FlowRuleManagerTest.applyFlowRules(), org.onosproject.net.flow.impl.FlowRuleManagerTest.getFlowEntries(), and org.onosproject.net.flow.impl.FlowRuleManagerTest.setUp().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/flow/impl/FlowRuleManagerTest.java