onos: org.onosproject.store.device.impl.InternalDeviceOfflineEvent Class Reference
org.onosproject.store.device.impl.InternalDeviceOfflineEvent Class Reference
Information published by GossipDeviceStore to notify peers of a device going offline.
Public Member Functions
InternalDeviceOfflineEvent (DeviceId deviceId, Timestamp timestamp)
Creates a InternalDeviceOfflineEvent.
DeviceId deviceId ()
Timestamp timestamp ()
String toString ()
Detailed Description
Information published by GossipDeviceStore to notify peers of a device going offline.
Definition at line 27 of file InternalDeviceOfflineEvent.java.
Constructor & Destructor Documentation
org.onosproject.store.device.impl.InternalDeviceOfflineEvent.InternalDeviceOfflineEvent (DeviceId deviceId, Timestamp timestamp)
Creates a InternalDeviceOfflineEvent.
Parameters
deviceId identifier of device going offline.
timestamp timestamp of when the device went offline.
Definition at line 37 of file InternalDeviceOfflineEvent.java.
References org.onosproject.store.device.impl.InternalDeviceOfflineEvent.deviceId(), and org.onosproject.store.device.impl.InternalDeviceOfflineEvent.timestamp().
Member Function Documentation
DeviceId org.onosproject.store.device.impl.InternalDeviceOfflineEvent.deviceId ()
Definition at line 42 of file InternalDeviceOfflineEvent.java.
Referenced by org.onosproject.store.device.impl.InternalDeviceOfflineEvent.InternalDeviceOfflineEvent(), and org.onosproject.store.device.impl.InternalDeviceOfflineEvent.toString().
Timestamp org.onosproject.store.device.impl.InternalDeviceOfflineEvent.timestamp ()
Definition at line 46 of file InternalDeviceOfflineEvent.java.
Referenced by org.onosproject.store.device.impl.InternalDeviceOfflineEvent.InternalDeviceOfflineEvent(), and org.onosproject.store.device.impl.InternalDeviceOfflineEvent.toString().
String org.onosproject.store.device.impl.InternalDeviceOfflineEvent.toString ()
Definition at line 51 of file InternalDeviceOfflineEvent.java.
References org.onosproject.store.device.impl.InternalDeviceOfflineEvent.deviceId(), and org.onosproject.store.device.impl.InternalDeviceOfflineEvent.timestamp().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/device/impl/InternalDeviceOfflineEvent.java