onos: org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse Class Reference
org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse Class Reference
Json Rpc Response information that include id,error,result.
Public Member Functions
JsonRpcResponse (String id)
JsonRpcResponse Constructor.
JsonRpcResponse (String id, String error)
JsonRpcResponse Constructor.
JsonRpcResponse (String id, String error, List< Object > result)
JsonRpcResponse Constructor.
String getId ()
Returns id.
String getError ()
Returns error.
List< Object > getResult ()
Returns result.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Json Rpc Response information that include id,error,result.
Definition at line 29 of file JsonRpcResponse.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.JsonRpcResponse (String id)
JsonRpcResponse Constructor.
Parameters
id the id node of response information
Definition at line 39 of file JsonRpcResponse.java.
Referenced by org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.equals().
org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.JsonRpcResponse (String id, String error)
JsonRpcResponse Constructor.
Parameters
id the id node of response information
error the error node of response information
Definition at line 51 of file JsonRpcResponse.java.
org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.JsonRpcResponse (String id, String error, List< Object > result)
JsonRpcResponse Constructor.
Parameters
id the id node of response information
error the error node of response information
result the result node of response information
Definition at line 65 of file JsonRpcResponse.java.
Member Function Documentation
boolean org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.equals (Object obj)
Definition at line 104 of file JsonRpcResponse.java.
References find-device.id, and org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.JsonRpcResponse().
String org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.getError ()
Returns error.
Returns
error
Definition at line 86 of file JsonRpcResponse.java.
String org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.getId ()
Returns id.
Returns
id
Definition at line 78 of file JsonRpcResponse.java.
Referenced by metro.FabricDomain.build().
List<Object> org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.getResult ()
Returns result.
Returns
result
Definition at line 94 of file JsonRpcResponse.java.
int org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.hashCode ()
Definition at line 99 of file JsonRpcResponse.java.
String org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcResponse.toString ()
Definition at line 118 of file JsonRpcResponse.java.
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/jsonrpc/JsonRpcResponse.java