onos: org.onosproject.vtnrsc.FloatingIpId Class Reference
org.onosproject.vtnrsc.FloatingIpId Class Reference
Immutable representation of a floating IP identifier.
Public Member Functions
UUID floatingIpId ()
Returns the floating IP identifier.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static FloatingIpId of (UUID floatingIpId)
Creates a floating IP identifier.
static FloatingIpId of (String floatingIpId)
Creates a floating IP identifier.
Detailed Description
Immutable representation of a floating IP identifier.
Definition at line 27 of file FloatingIpId.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.FloatingIpId.equals (Object obj)
Definition at line 70 of file FloatingIpId.java.
UUID org.onosproject.vtnrsc.FloatingIpId.floatingIpId ()
Returns the floating IP identifier.
Returns
the floating IP identifier
Definition at line 60 of file FloatingIpId.java.
Referenced by org.onosproject.vtnrsc.FloatingIpId.toString().
int org.onosproject.vtnrsc.FloatingIpId.hashCode ()
Definition at line 65 of file FloatingIpId.java.
static FloatingIpId org.onosproject.vtnrsc.FloatingIpId.of (UUID floatingIpId) static
Creates a floating IP identifier.
Parameters
floatingIpId the UUID id of floating IP identifier
Returns
object of floating IP identifier
Definition at line 41 of file FloatingIpId.java.
Referenced by org.onosproject.vtnrsc.cli.floatingip.FloatingIpCreateCommand.execute(), and org.onosproject.vtnweb.resources.FloatingIpWebResource.getFloatingIp().
static FloatingIpId org.onosproject.vtnrsc.FloatingIpId.of (String floatingIpId) static
Creates a floating IP identifier.
Parameters
floatingIpId the floating IP identifier in string
Returns
object of floating IP identifier
Definition at line 51 of file FloatingIpId.java.
String org.onosproject.vtnrsc.FloatingIpId.toString ()
Definition at line 82 of file FloatingIpId.java.
References org.onosproject.vtnrsc.FloatingIpId.floatingIpId().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/FloatingIpId.java