onos: org.onosproject.net.provider.ProviderId Class Reference
org.onosproject.net.provider.ProviderId Class Reference
External identity of a org.onosproject.net.provider.Provider family.
Public Member Functions
ProviderId (String scheme, String id)
Creates a new primary provider identifier from the specified string.
ProviderId (String scheme, String id, boolean ancillary)
Creates a new provider identifier from the specified string.
String scheme ()
Returns the device URI scheme to which this provider is bound.
String id ()
Returns the device URI scheme specific id portion.
boolean isAncillary ()
Indicates whether this identifier designates an ancillary providers.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Attributes
static final ProviderId NONE = new ProviderId("none", "none")
Represents no provider ID.
Detailed Description
External identity of a org.onosproject.net.provider.Provider family.
It also carriers two designations of external characteristics, the URI scheme and primary/ancillary indicator.
The device URI scheme is used to determine applicability of a provider to operations on a specific device. The ancillary indicator serves to designate a provider as a primary or ancillary.
A org.onosproject.net.provider.ProviderRegistry uses this designation to permit only one primary provider per device URI scheme. Multiple ancillary providers can register with the same device URI scheme however.
Definition at line 38 of file ProviderId.java.
Constructor & Destructor Documentation
org.onosproject.net.provider.ProviderId.ProviderId (String scheme, String id)
Creates a new primary provider identifier from the specified string.
The providers are expected to follow the reverse DNS convention, e.g.
org.onosproject.provider.of.device
Parameters
scheme device URI scheme to which this provider is bound, e.g. "of", "snmp"
id string identifier
Definition at line 64 of file ProviderId.java.
References org.onosproject.net.provider.ProviderId.id(), and org.onosproject.net.provider.ProviderId.scheme().
org.onosproject.net.provider.ProviderId.ProviderId (String scheme, String id, boolean ancillary)
Creates a new provider identifier from the specified string.
The providers are expected to follow the reverse DNS convention, e.g.
org.onosproject.provider.of.device
Parameters
scheme device URI scheme to which this provider is bound, e.g. "of", "snmp"
id string identifier
ancillary ancillary provider indicator
Definition at line 77 of file ProviderId.java.
Member Function Documentation
boolean org.onosproject.net.provider.ProviderId.equals (Object obj)
Definition at line 116 of file ProviderId.java.
Referenced by org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.deleteTunnel(), and org.onosproject.incubator.net.tunnel.impl.TunnelManager.removeTunnels().
int org.onosproject.net.provider.ProviderId.hashCode ()
Definition at line 111 of file ProviderId.java.
References org.onosproject.net.provider.ProviderId.id(), and org.onosproject.net.provider.ProviderId.scheme().
String org.onosproject.net.provider.ProviderId.id ()
Returns the device URI scheme specific id portion.
Returns
id
Definition at line 97 of file ProviderId.java.
Referenced by org.onosproject.net.provider.ProviderId.hashCode(), and org.onosproject.net.provider.ProviderId.ProviderId().
boolean org.onosproject.net.provider.ProviderId.isAncillary ()
Indicates whether this identifier designates an ancillary providers.
Returns
true if the provider is ancillary; false if primary
Definition at line 106 of file ProviderId.java.
String org.onosproject.net.provider.ProviderId.scheme ()
Returns the device URI scheme to which this provider is bound.
Returns
device URI scheme
Definition at line 88 of file ProviderId.java.
Referenced by org.onosproject.net.provider.ProviderId.hashCode(), org.onosproject.net.provider.ProviderId.ProviderId(), and org.onosproject.net.provider.ProviderId.toString().
String org.onosproject.net.provider.ProviderId.toString ()
Definition at line 130 of file ProviderId.java.
References org.onosproject.net.provider.ProviderId.scheme().
Member Data Documentation
final ProviderId org.onosproject.net.provider.ProviderId.NONE = new ProviderId("none", "none") static
Represents no provider ID.
Definition at line 43 of file ProviderId.java.
Referenced by org.onosproject.net.DefaultEdgeLink.createEdgeLink(), org.onosproject.provider.host.impl.HostLocationProviderTest.removeHostByDeviceOffline(), org.onosproject.provider.host.impl.HostLocationProviderTest.removeHostByDevicePortDown(), org.onosproject.provider.host.impl.HostLocationProviderTest.removeHostByDeviceRemove(), org.onosproject.routing.impl.RouterAsyncArpTest.testRouteAdd(), and org.onosproject.routing.impl.RouterAsyncArpTest.testRouteUpdate().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/provider/ProviderId.java