onos: org.onosproject.net.group.DefaultGroupDescription Class Reference
org.onosproject.net.group.DefaultGroupDescription Class Reference
Default implementation of group description interface.
Public Member Functions
DefaultGroupDescription (DeviceId deviceId, GroupDescription.Type type, GroupBuckets buckets, GroupKey appCookie, Integer groupId, ApplicationId appId)
Constructor to be used by north bound applications.
DefaultGroupDescription (GroupDescription groupDesc)
Constructor to be used by group subsystem internal components.
DefaultGroupDescription (DeviceId deviceId, GroupDescription.Type type, GroupBuckets buckets)
Constructor to be used by group subsystem internal components.
GroupDescription.Type type ()
Returns type of a group object.
DeviceId deviceId ()
Returns device identifier on which this group object is created.
ApplicationId appId ()
Returns application identifier that has created this group object.
GroupKey appCookie ()
Returns application cookie associated with a group object.
GroupBuckets buckets ()
Returns group buckets of a group.
Integer givenGroupId ()
Returns groupId passed in by application.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of group description interface.
Definition at line 29 of file DefaultGroupDescription.java.
Constructor & Destructor Documentation
org.onosproject.net.group.DefaultGroupDescription.DefaultGroupDescription (DeviceId deviceId, GroupDescription.Type type, GroupBuckets buckets, GroupKey appCookie, Integer groupId, ApplicationId appId)
Constructor to be used by north bound applications.
NOTE: The caller of this subsystem MUST ensure the appCookie provided in this API is immutable. NOTE: The caller may choose to pass in 'null' for the groupId. This is the typical case, where the caller allows the group subsystem to choose the groupId in a globally unique way. If the caller passes in the groupId, the caller MUST ensure that the id is globally unique (not just unique per device).
Parameters
deviceId device identifier
type type of the group
buckets immutable list of group bucket
appCookie immutable application cookie of type DefaultGroupKey to be associated with the group
groupId group identifier
appId application id
Definition at line 55 of file DefaultGroupDescription.java.
References org.onosproject.net.group.DefaultGroupDescription.appCookie(), org.onosproject.net.group.DefaultGroupDescription.appId(), and org.onosproject.net.group.DefaultGroupDescription.type().
Referenced by org.onosproject.net.group.DefaultGroupDescription.equals().
org.onosproject.net.group.DefaultGroupDescription.DefaultGroupDescription (GroupDescription groupDesc)
Constructor to be used by group subsystem internal components.
Creates group description object from another object of same type.
Parameters
groupDesc group description object
Definition at line 76 of file DefaultGroupDescription.java.
org.onosproject.net.group.DefaultGroupDescription.DefaultGroupDescription (DeviceId deviceId, GroupDescription.Type type, GroupBuckets buckets)
Constructor to be used by group subsystem internal components.
Creates group description object from the information retrieved from data plane.
Parameters
deviceId device identifier
type type of the group
buckets immutable list of group bucket
Definition at line 95 of file DefaultGroupDescription.java.
References org.onosproject.net.group.DefaultGroupDescription.buckets(), org.onosproject.net.group.DefaultGroupDescription.deviceId(), and org.onosproject.net.group.DefaultGroupDescription.type().
Member Function Documentation
GroupKey org.onosproject.net.group.DefaultGroupDescription.appCookie ()
Returns application cookie associated with a group object.
Returns
GroupKey application cookie
Implements org.onosproject.net.group.GroupDescription.
Definition at line 137 of file DefaultGroupDescription.java.
Referenced by org.onosproject.net.group.DefaultGroupDescription.DefaultGroupDescription().
ApplicationId org.onosproject.net.group.DefaultGroupDescription.appId ()
Returns application identifier that has created this group object.
Returns
ApplicationId application identifier
Implements org.onosproject.net.group.GroupDescription.
Definition at line 127 of file DefaultGroupDescription.java.
Referenced by org.onosproject.net.group.DefaultGroupDescription.DefaultGroupDescription(), and org.onosproject.net.group.DefaultGroupDescription.toString().
GroupBuckets org.onosproject.net.group.DefaultGroupDescription.buckets ()
Returns group buckets of a group.
Returns
GroupBuckets immutable list of group bucket
Implements org.onosproject.net.group.GroupDescription.
Definition at line 147 of file DefaultGroupDescription.java.
Referenced by org.onosproject.net.group.DefaultGroupTest.checkConstruction(), org.onosproject.net.group.DefaultGroupTest.checkConstructionWithDid(), org.onosproject.net.group.DefaultGroupDescription.DefaultGroupDescription(), org.onosproject.net.group.DefaultGroupDescription.equals(), org.onosproject.net.group.DefaultGroupDescription.hashCode(), and org.onosproject.net.group.DefaultGroupDescription.toString().
DeviceId org.onosproject.net.group.DefaultGroupDescription.deviceId ()
Returns device identifier on which this group object is created.
Returns
DeviceId device identifier
Implements org.onosproject.net.group.GroupDescription.
Definition at line 117 of file DefaultGroupDescription.java.
References find-flow.deviceId.
Referenced by org.onosproject.net.group.DefaultGroupTest.checkConstructionWithDid(), org.onosproject.net.group.DefaultGroupDescription.DefaultGroupDescription(), org.onosproject.net.group.DefaultGroupDescription.equals(), org.onosproject.net.group.DefaultGroupDescription.hashCode(), and org.onosproject.net.group.DefaultGroupDescription.toString().
boolean org.onosproject.net.group.DefaultGroupDescription.equals (Object obj)
Definition at line 180 of file DefaultGroupDescription.java.
References org.onosproject.net.group.DefaultGroupDescription.buckets(), org.onosproject.net.group.DefaultGroupDescription.DefaultGroupDescription(), find-flow.deviceId, org.onosproject.net.group.DefaultGroupDescription.deviceId(), and org.onosproject.net.group.DefaultGroupDescription.type().
Integer org.onosproject.net.group.DefaultGroupDescription.givenGroupId ()
Returns groupId passed in by application.
Returns
Integer group Id passed in by caller. May be null if caller passed in null during GroupDescription creation.
Implements org.onosproject.net.group.GroupDescription.
Definition at line 158 of file DefaultGroupDescription.java.
Referenced by org.onosproject.net.group.DefaultGroupDescription.toString().
int org.onosproject.net.group.DefaultGroupDescription.hashCode ()
Definition at line 169 of file DefaultGroupDescription.java.
References org.onosproject.net.group.DefaultGroupDescription.buckets(), org.onosproject.net.group.DefaultGroupDescription.deviceId(), and org.onosproject.net.group.DefaultGroupDescription.type().
String org.onosproject.net.group.DefaultGroupDescription.toString ()
Definition at line 195 of file DefaultGroupDescription.java.
References org.onosproject.net.group.DefaultGroupDescription.appId(), org.onosproject.net.group.DefaultGroupDescription.buckets(), org.onosproject.net.group.DefaultGroupDescription.deviceId(), org.onosproject.net.group.DefaultGroupDescription.givenGroupId(), and org.onosproject.net.group.DefaultGroupDescription.type().
GroupDescription.Type org.onosproject.net.group.DefaultGroupDescription.type ()
Returns type of a group object.
Returns
GroupType group type
Implements org.onosproject.net.group.GroupDescription.
Definition at line 107 of file DefaultGroupDescription.java.
Referenced by org.onosproject.net.group.DefaultGroup.DefaultGroup(), org.onosproject.net.group.DefaultGroupDescription.DefaultGroupDescription(), org.onosproject.net.group.DefaultGroupDescription.equals(), org.onosproject.net.group.DefaultGroupDescription.hashCode(), and org.onosproject.net.group.DefaultGroupDescription.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/group/DefaultGroupDescription.java