onos: org.onosproject.net.intent.TestTools Class Reference
org.onosproject.net.intent.TestTools Class Reference
Set of test tools.
Static Public Member Functions
static void delay (int ms)
Utility method to pause the current thread for the specified number of milliseconds.
static void assertAfter (long start, int delay, int step, int duration, Runnable assertions)
Periodically runs the given runnable, which should contain a series of test assertions until all the assertions succeed, in which case it will return, or until the the time expires, in which case it will throw the first failed assertion error.
static void assertAfter (int delay, int step, int duration, Runnable assertions)
Periodically runs the given runnable, which should contain a series of test assertions until all the assertions succeed, in which case it will return, or until the the time expires, in which case it will throw the first failed assertion error.
static void assertAfter (int step, int duration, Runnable assertions)
Periodically runs the given runnable, which should contain a series of test assertions until all the assertions succeed, in which case it will return, or until the the time expires, in which case it will throw the first failed assertion error.
static void assertAfter (int duration, Runnable assertions)
Periodically runs the given runnable, which should contain a series of test assertions until all the assertions succeed, in which case it will return, or until the the time expires, in which case it will throw the first failed assertion error.
Detailed Description
Set of test tools.
Definition at line 23 of file TestTools.java.
Member Function Documentation
static void org.onosproject.net.intent.TestTools.assertAfter (long start, int delay, int step, int duration, Runnable assertions) static
Periodically runs the given runnable, which should contain a series of test assertions until all the assertions succeed, in which case it will return, or until the the time expires, in which case it will throw the first failed assertion error.
Parameters
start start time, in millis since start of epoch from which the duration will be measured
delay initial delay (in milliseconds) before the first assertion attempt
step delay (in milliseconds) between successive assertion attempts
duration number of milliseconds beyond the given start time, after which the failed assertions will be propagated and allowed to fail the test
assertions runnable housing the test assertions
Definition at line 60 of file TestTools.java.
References org.onosproject.net.intent.TestTools.delay().
Referenced by org.onosproject.net.intent.TestTools.assertAfter().
static void org.onosproject.net.intent.TestTools.assertAfter (int delay, int step, int duration, Runnable assertions) static
Periodically runs the given runnable, which should contain a series of test assertions until all the assertions succeed, in which case it will return, or until the the time expires, in which case it will throw the first failed assertion error.
The start of the period is the current time.
Parameters
delay initial delay (in milliseconds) before the first assertion attempt
step delay (in milliseconds) between successive assertion attempts
duration number of milliseconds beyond the current time time, after which the failed assertions will be propagated and allowed to fail the test
assertions runnable housing the test assertions
Definition at line 93 of file TestTools.java.
References org.onosproject.net.intent.TestTools.assertAfter(), and org.onosproject.net.intent.TestTools.delay().
static void org.onosproject.net.intent.TestTools.assertAfter (int step, int duration, Runnable assertions) static
Periodically runs the given runnable, which should contain a series of test assertions until all the assertions succeed, in which case it will return, or until the the time expires, in which case it will throw the first failed assertion error.
The start of the period is the current time and the first assertion attempt is delayed by the value of
step
parameter.
Parameters
step delay (in milliseconds) between successive assertion attempts
duration number of milliseconds beyond the current time time, after which the failed assertions will be propagated and allowed to fail the test
assertions runnable housing the test assertions
Definition at line 115 of file TestTools.java.
References org.onosproject.net.intent.TestTools.assertAfter().
static void org.onosproject.net.intent.TestTools.assertAfter (int duration, Runnable assertions) static
Periodically runs the given runnable, which should contain a series of test assertions until all the assertions succeed, in which case it will return, or until the the time expires, in which case it will throw the first failed assertion error.
The start of the period is the current time and each successive assertion attempt is delayed by at least 10 milliseconds unless the
duration
is less than that, in which case the one and only assertion is made after that delay.
Parameters
duration number of milliseconds beyond the current time, after which the failed assertions will be propagated and allowed to fail the test
assertions runnable housing the test assertions
Definition at line 136 of file TestTools.java.
References org.onosproject.net.intent.TestTools.assertAfter().
static void org.onosproject.net.intent.TestTools.delay (int ms) static
Utility method to pause the current thread for the specified number of milliseconds.
Parameters
ms number of milliseconds to pause
Definition at line 35 of file TestTools.java.
Referenced by org.onosproject.net.intent.TestTools.assertAfter().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/intent/TestTools.java