onos: org.onosproject.net.TestDeviceParams Class Reference
org.onosproject.net.TestDeviceParams Class Reference
Provides a set of test DefaultDevice parameters for use with Host- related tests.
Static Protected Attributes
static final ProviderId PID = new ProviderId("of", "foo")
static final DeviceId DID1 = deviceId("of:foo")
static final DeviceId DID2 = deviceId("of:bar")
static final MacAddress MAC1 = MacAddress.valueOf("00:11:00:00:00:01")
static final MacAddress MAC2 = MacAddress.valueOf("00:22:00:00:00:02")
static final VlanId VLAN1 = VlanId.vlanId((short) 11)
static final VlanId VLAN2 = VlanId.vlanId((short) 22)
static final IpAddress IP1 = IpAddress.valueOf("10.0.0.1")
static final IpAddress IP2 = IpAddress.valueOf("10.0.0.2")
static final IpAddress IP3 = IpAddress.valueOf("10.0.0.3")
static final PortNumber P1 = PortNumber.portNumber(100)
static final PortNumber P2 = PortNumber.portNumber(200)
static final HostId HID1 = HostId.hostId(MAC1, VLAN1)
static final HostId HID2 = HostId.hostId(MAC2, VLAN2)
static final HostLocation LOC1 = new HostLocation(DID1, P1, 123L)
static final HostLocation LOC2 = new HostLocation(DID2, P2, 123L)
static final Set< IpAddress > IPSET1 = Sets.newHashSet(IP1, IP2)
static final Set< IpAddress > IPSET2 = Sets.newHashSet(IP1, IP3)
Detailed Description
Provides a set of test DefaultDevice parameters for use with Host- related tests.
Definition at line 33 of file TestDeviceParams.java.
Member Data Documentation
final DeviceId org.onosproject.net.TestDeviceParams.DID1 = deviceId("of:foo") static protected
Definition at line 36 of file TestDeviceParams.java.
final DeviceId org.onosproject.net.TestDeviceParams.DID2 = deviceId("of:bar") static protected
Definition at line 37 of file TestDeviceParams.java.
final HostId org.onosproject.net.TestDeviceParams.HID1 = HostId.hostId(MAC1, VLAN1) static protected
Definition at line 48 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.basics(), and org.onosproject.net.DefaultHostTest.testEquality().
final HostId org.onosproject.net.TestDeviceParams.HID2 = HostId.hostId(MAC2, VLAN2) static protected
Definition at line 49 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.testEquality().
final IpAddress org.onosproject.net.TestDeviceParams.IP1 = IpAddress.valueOf("10.0.0.1") static protected
Definition at line 42 of file TestDeviceParams.java.
final IpAddress org.onosproject.net.TestDeviceParams.IP2 = IpAddress.valueOf("10.0.0.2") static protected
Definition at line 43 of file TestDeviceParams.java.
final IpAddress org.onosproject.net.TestDeviceParams.IP3 = IpAddress.valueOf("10.0.0.3") static protected
Definition at line 44 of file TestDeviceParams.java.
final Set<IpAddress> org.onosproject.net.TestDeviceParams.IPSET1 = Sets.newHashSet(IP1, IP2) static protected
Definition at line 52 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.basics(), and org.onosproject.net.DefaultHostTest.testEquality().
final Set<IpAddress> org.onosproject.net.TestDeviceParams.IPSET2 = Sets.newHashSet(IP1, IP3) static protected
Definition at line 53 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.testEquality().
final HostLocation org.onosproject.net.TestDeviceParams.LOC1 = new HostLocation(DID1, P1, 123L) static protected
Definition at line 50 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.basics(), and org.onosproject.net.DefaultHostTest.testEquality().
final HostLocation org.onosproject.net.TestDeviceParams.LOC2 = new HostLocation(DID2, P2, 123L) static protected
Definition at line 51 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.testEquality().
final MacAddress org.onosproject.net.TestDeviceParams.MAC1 = MacAddress.valueOf("00:11:00:00:00:01") static protected
Definition at line 38 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.basics(), and org.onosproject.net.DefaultHostTest.testEquality().
final MacAddress org.onosproject.net.TestDeviceParams.MAC2 = MacAddress.valueOf("00:22:00:00:00:02") static protected
Definition at line 39 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.testEquality().
final PortNumber org.onosproject.net.TestDeviceParams.P1 = PortNumber.portNumber(100) static protected
Definition at line 46 of file TestDeviceParams.java.
final PortNumber org.onosproject.net.TestDeviceParams.P2 = PortNumber.portNumber(200) static protected
Definition at line 47 of file TestDeviceParams.java.
final ProviderId org.onosproject.net.TestDeviceParams.PID = new ProviderId("of", "foo") static protected
Definition at line 35 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.basics(), and org.onosproject.net.DefaultHostTest.testEquality().
final VlanId org.onosproject.net.TestDeviceParams.VLAN1 = VlanId.vlanId((short) 11) static protected
Definition at line 40 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.basics(), and org.onosproject.net.DefaultHostTest.testEquality().
final VlanId org.onosproject.net.TestDeviceParams.VLAN2 = VlanId.vlanId((short) 22) static protected
Definition at line 41 of file TestDeviceParams.java.
Referenced by org.onosproject.net.DefaultHostTest.testEquality().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/TestDeviceParams.java