onos: org.onosproject.ui.topo.Highlights Class Reference
org.onosproject.ui.topo.Highlights Class Reference
Encapsulates highlights to be applied to the topology view, such as highlighting links, displaying link labels, perhaps even decorating nodes with badges, etc.
Classes
enum Amount
A notion of amount.
Public Member Functions
Highlights add (DeviceHighlight dh)
Adds highlighting information for a device.
Highlights add (HostHighlight hh)
Adds highlighting information for a host.
Highlights add (LinkHighlight lh)
Adds highlighting information for a link.
Highlights subdueAllElse (Amount amount)
Marks the amount by which all other elements (devices, hosts, links) not explicitly referenced here will be "subdued" visually.
Collection< DeviceHighlight > devices ()
Returns the collection of device highlights.
Collection< HostHighlight > hosts ()
Returns the collection of host highlights.
Collection< LinkHighlight > links ()
Returns the collection of link highlights.
Amount subdueLevel ()
Returns the amount by which all other elements not explicitly referenced here should be "subdued".
NodeHighlight getNode (String id)
Returns the node highlight (device or host) for the given element identifier, or null if no match.
DeviceHighlight getDevice (String id)
Returns the device highlight for the given device identifier, or null if no match.
HostHighlight getHost (String id)
Returns the host highlight for the given host identifier, or null if no match.
LinkHighlight getLink (String id)
Returns the link highlight for the given link identifier, or null if no match.
Detailed Description
Encapsulates highlights to be applied to the topology view, such as highlighting links, displaying link labels, perhaps even decorating nodes with badges, etc.
Definition at line 31 of file Highlights.java.
Member Function Documentation
Highlights org.onosproject.ui.topo.Highlights.add (DeviceHighlight dh)
Adds highlighting information for a device.
Parameters
dh device highlight
Returns
self, for chaining
Definition at line 69 of file Highlights.java.
Highlights org.onosproject.ui.topo.Highlights.add (HostHighlight hh)
Adds highlighting information for a host.
Parameters
hh host highlight
Returns
self, for chaining
Definition at line 80 of file Highlights.java.
Highlights org.onosproject.ui.topo.Highlights.add (LinkHighlight lh)
Adds highlighting information for a link.
Parameters
lh link highlight
Returns
self, for chaining
Definition at line 91 of file Highlights.java.
Collection<DeviceHighlight> org.onosproject.ui.topo.Highlights.devices ()
Returns the collection of device highlights.
Returns
device highlights
Definition at line 113 of file Highlights.java.
DeviceHighlight org.onosproject.ui.topo.Highlights.getDevice (String id)
Returns the device highlight for the given device identifier, or null if no match.
Parameters
id device identifier
Returns
corresponding device highlight
Definition at line 164 of file Highlights.java.
References find-device.id.
Referenced by org.onosproject.ui.topo.HighlightsTest.highlightRetrieval().
HostHighlight org.onosproject.ui.topo.Highlights.getHost (String id)
Returns the host highlight for the given host identifier, or null if no match.
Parameters
id host identifier
Returns
corresponding host highlight
Definition at line 175 of file Highlights.java.
References find-device.id.
Referenced by org.onosproject.ui.topo.HighlightsTest.highlightRetrieval().
LinkHighlight org.onosproject.ui.topo.Highlights.getLink (String id)
Returns the link highlight for the given link identifier, or null if no match.
Parameters
id link identifier
Returns
corresponding link highlight
Definition at line 186 of file Highlights.java.
References find-device.id.
NodeHighlight org.onosproject.ui.topo.Highlights.getNode (String id)
Returns the node highlight (device or host) for the given element identifier, or null if no match.
Parameters
id element identifier
Returns
corresponding node highlight
Definition at line 152 of file Highlights.java.
References find-device.id.
Referenced by org.onosproject.ui.topo.HighlightsTest.highlightRetrieval().
Collection<HostHighlight> org.onosproject.ui.topo.Highlights.hosts ()
Returns the collection of host highlights.
Returns
host highlights
Definition at line 122 of file Highlights.java.
Collection<LinkHighlight> org.onosproject.ui.topo.Highlights.links ()
Returns the collection of link highlights.
Returns
link highlights
Definition at line 131 of file Highlights.java.
Highlights org.onosproject.ui.topo.Highlights.subdueAllElse (Amount amount)
Marks the amount by which all other elements (devices, hosts, links) not explicitly referenced here will be "subdued" visually.
Parameters
amount amount to subdue other elements
Returns
self, for chaining
Definition at line 103 of file Highlights.java.
References org.onosproject.ui.topo.Highlights.subdueLevel().
Amount org.onosproject.ui.topo.Highlights.subdueLevel ()
Returns the amount by which all other elements not explicitly referenced here should be "subdued".
Returns
amount to subdue other elements
Definition at line 141 of file Highlights.java.
Referenced by org.onosproject.ui.topo.Highlights.subdueAllElse().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/topo/Highlights.java