onos: org.onosproject.store.device.impl.GossipDeviceStore Class Reference
org.onosproject.store.device.impl.GossipDeviceStore Class Reference
Manages inventory of infrastructure devices using gossip protocol to distribute information.
Public Member Functions
void activate ()
void deactivate ()
int getDeviceCount ()
Returns the number of devices known to the system.
Iterable< Device > getDevices ()
Returns an iterable collection of all devices known to the system.
Iterable< Device > getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Device getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
synchronized DeviceEvent createOrUpdateDevice (ProviderId providerId, DeviceId deviceId, DeviceDescription deviceDescription)
Creates a new infrastructure device, or updates an existing one using the supplied device description.
DeviceEvent markOffline (DeviceId deviceId)
Removes the specified infrastructure device.
synchronized List< DeviceEvent > updatePorts (ProviderId providerId, DeviceId deviceId, List< PortDescription > portDescriptions)
Updates the ports of the specified infrastructure device using the given list of port descriptions.
synchronized DeviceEvent updatePortStatus (ProviderId providerId, DeviceId deviceId, PortDescription portDescription)
Updates the port status of the specified infrastructure device using the given port description.
List< Port > getPorts (DeviceId deviceId)
Returns the list of ports that belong to the specified device.
DeviceEvent updatePortStatistics (ProviderId providerId, DeviceId deviceId, Collection< PortStatistics > newStatsCollection)
Updates the port statistics of the specified device using the give port statistics.
PortStatistics calcDeltaStats (DeviceId deviceId, PortStatistics prvStats, PortStatistics newStats)
Calculate delta statistics by subtracting previous from new statistics.
List< PortStatistics > getPortStatistics (DeviceId deviceId)
Returns the list of port statistics of the specified device.
List< PortStatistics > getPortDeltaStatistics (DeviceId deviceId)
Returns the list of delta port statistics of the specified device.
Port getPort (DeviceId deviceId, PortNumber portNumber)
Returns the specified device port.
boolean isAvailable (DeviceId deviceId)
Indicates whether the specified device is available/online.
synchronized DeviceEvent removeDevice (DeviceId deviceId)
Administratively removes the specified device from the store.
Protected Attributes
DeviceClockService deviceClockService
StorageService storageService
ClusterCommunicationService clusterCommunicator
ClusterService clusterService
MastershipService mastershipService
MastershipTermService termService
Static Protected Attributes
static final KryoSerializer SERIALIZER
Detailed Description
Manages inventory of infrastructure devices using gossip protocol to distribute information.
Definition at line 121 of file GossipDeviceStore.java.
Member Function Documentation
void org.onosproject.store.device.impl.GossipDeviceStore.activate ()
Definition at line 200 of file GossipDeviceStore.java.
References org.onosproject.store.serializers.KryoNamespaces.API, org.onosproject.store.device.impl.GossipDeviceStoreMessageSubjects.DEVICE_ADVERTISE, org.onosproject.store.device.impl.GossipDeviceStoreMessageSubjects.DEVICE_INJECTED, org.onosproject.store.device.impl.GossipDeviceStoreMessageSubjects.DEVICE_OFFLINE, org.onosproject.store.device.impl.GossipDeviceStoreMessageSubjects.DEVICE_REMOVED, org.onosproject.store.device.impl.GossipDeviceStoreMessageSubjects.DEVICE_UPDATE, org.onosproject.store.device.impl.GossipDeviceStoreMessageSubjects.PORT_INJECTED, org.onosproject.store.device.impl.GossipDeviceStoreMessageSubjects.PORT_STATUS_UPDATE, org.onosproject.store.device.impl.GossipDeviceStoreMessageSubjects.PORT_UPDATE, and org.onosproject.store.device.impl.GossipDeviceStore.storageService.
PortStatistics org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats (DeviceId deviceId, PortStatistics prvStats, PortStatistics newStats)
Calculate delta statistics by subtracting previous from new statistics.
Parameters
deviceId device identifier
prvStats previous port statistics
newStats new port statistics
Returns
PortStatistics
Definition at line 873 of file GossipDeviceStore.java.
References org.onosproject.net.device.PortStatistics.bytesReceived(), org.onosproject.net.device.PortStatistics.bytesSent(), find-flow.deviceId, org.onosproject.net.device.PortStatistics.durationNano(), org.onosproject.net.device.PortStatistics.durationSec(), org.onosproject.net.device.PortStatistics.packetsReceived(), org.onosproject.net.device.PortStatistics.packetsRxDropped(), org.onosproject.net.device.PortStatistics.packetsRxErrors(), org.onosproject.net.device.PortStatistics.packetsSent(), org.onosproject.net.device.PortStatistics.packetsTxDropped(), org.onosproject.net.device.PortStatistics.packetsTxErrors(), and org.onosproject.net.device.PortStatistics.port().
Referenced by org.onosproject.store.device.impl.GossipDeviceStore.updatePortStatistics().
synchronized DeviceEvent org.onosproject.store.device.impl.GossipDeviceStore.createOrUpdateDevice (ProviderId providerId, DeviceId deviceId, DeviceDescription deviceDescription)
Creates a new infrastructure device, or updates an existing one using the supplied device description.
Parameters
providerId provider identifier
deviceId device identifier
deviceDescription device description
Returns
ready to send event describing what occurred; null if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 305 of file GossipDeviceStore.java.
References create-flow.device, find-flow.deviceId, and org.onosproject.cluster.NodeId.equals().
void org.onosproject.store.device.impl.GossipDeviceStore.deactivate ()
Definition at line 262 of file GossipDeviceStore.java.
Iterable<Device> org.onosproject.store.device.impl.GossipDeviceStore.getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Returns
device collection
Implements org.onosproject.net.device.DeviceStore.
Definition at line 294 of file GossipDeviceStore.java.
References org.onosproject.store.device.impl.GossipDeviceStore.getDevices(), and org.onosproject.store.device.impl.GossipDeviceStore.isAvailable().
Device org.onosproject.store.device.impl.GossipDeviceStore.getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
Parameters
deviceId device identifier
Returns
device
Implements org.onosproject.net.device.DeviceStore.
Definition at line 300 of file GossipDeviceStore.java.
References find-flow.deviceId.
int org.onosproject.store.device.impl.GossipDeviceStore.getDeviceCount ()
Returns the number of devices known to the system.
Returns
number of devices
Implements org.onosproject.net.device.DeviceStore.
Definition at line 284 of file GossipDeviceStore.java.
Iterable<Device> org.onosproject.store.device.impl.GossipDeviceStore.getDevices ()
Returns an iterable collection of all devices known to the system.
Returns
device collection
Implements org.onosproject.net.device.DeviceStore.
Definition at line 289 of file GossipDeviceStore.java.
Referenced by org.onosproject.store.device.impl.GossipDeviceStore.getAvailableDevices().
Port org.onosproject.store.device.impl.GossipDeviceStore.getPort (DeviceId deviceId, PortNumber portNumber)
Returns the specified device port.
Parameters
deviceId device identifier
portNumber port number
Returns
device port
Implements org.onosproject.net.device.DeviceStore.
Definition at line 919 of file GossipDeviceStore.java.
References find-flow.deviceId.
List<PortStatistics> org.onosproject.store.device.impl.GossipDeviceStore.getPortDeltaStatistics (DeviceId deviceId)
Returns the list of delta port statistics of the specified device.
Parameters
deviceId device identifier
Returns
list of delta port statistics of all ports of the device
Implements org.onosproject.net.device.DeviceStore.
Definition at line 910 of file GossipDeviceStore.java.
References find-flow.deviceId.
List<Port> org.onosproject.store.device.impl.GossipDeviceStore.getPorts (DeviceId deviceId)
Returns the list of ports that belong to the specified device.
Parameters
deviceId device identifier
Returns
list of device ports
Implements org.onosproject.net.device.DeviceStore.
Definition at line 825 of file GossipDeviceStore.java.
References find-flow.deviceId.
List<PortStatistics> org.onosproject.store.device.impl.GossipDeviceStore.getPortStatistics (DeviceId deviceId)
Returns the list of port statistics of the specified device.
Parameters
deviceId device identifier
Returns
list of port statistics of all ports of the device
Implements org.onosproject.net.device.DeviceStore.
Definition at line 901 of file GossipDeviceStore.java.
References find-flow.deviceId.
boolean org.onosproject.store.device.impl.GossipDeviceStore.isAvailable (DeviceId deviceId)
Indicates whether the specified device is available/online.
Parameters
deviceId device identifier
Returns
true if device is available
Implements org.onosproject.net.device.DeviceStore.
Definition at line 925 of file GossipDeviceStore.java.
References find-flow.deviceId.
Referenced by org.onosproject.store.device.impl.GossipDeviceStore.getAvailableDevices().
DeviceEvent org.onosproject.store.device.impl.GossipDeviceStore.markOffline (DeviceId deviceId)
Removes the specified infrastructure device.
Parameters
deviceId device identifier
Returns
ready to send event describing what occurred; null if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 455 of file GossipDeviceStore.java.
References find-flow.deviceId.
synchronized DeviceEvent org.onosproject.store.device.impl.GossipDeviceStore.removeDevice (DeviceId deviceId)
Administratively removes the specified device from the store.
Parameters
deviceId device to be removed
Returns
null if no such device, or was forwarded to remove master
Implements org.onosproject.net.device.DeviceStore.
Definition at line 930 of file GossipDeviceStore.java.
References find-flow.deviceId, org.onosproject.cluster.NodeId.equals(), and org.onosproject.net.MastershipRole.NONE.
synchronized List<DeviceEvent> org.onosproject.store.device.impl.GossipDeviceStore.updatePorts (ProviderId providerId, DeviceId deviceId, List< PortDescription > portDescriptions)
Updates the ports of the specified infrastructure device using the given list of port descriptions.
The list is assumed to be comprehensive.
Parameters
providerId provider identifier
deviceId device identifier
portDescriptions list of port descriptions
Returns
ready to send events describing what occurred; empty list if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 520 of file GossipDeviceStore.java.
References create-flow.device, find-flow.deviceId, and org.onosproject.cluster.NodeId.equals().
DeviceEvent org.onosproject.store.device.impl.GossipDeviceStore.updatePortStatistics (ProviderId providerId, DeviceId deviceId, Collection< PortStatistics > portStats)
Updates the port statistics of the specified device using the give port statistics.
Parameters
providerId provider identifier
deviceId device identifier
portStats list of port statistics
Returns
ready to send event describing what occurred;
Implements org.onosproject.net.device.DeviceStore.
Definition at line 834 of file GossipDeviceStore.java.
References org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), find-flow.deviceId, and obeliskHostCheck.port.
synchronized DeviceEvent org.onosproject.store.device.impl.GossipDeviceStore.updatePortStatus (ProviderId providerId, DeviceId deviceId, PortDescription portDescription)
Updates the port status of the specified infrastructure device using the given port description.
Parameters
providerId provider identifier
deviceId device identifier
portDescription port description
Returns
ready to send event describing what occurred; null if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 746 of file GossipDeviceStore.java.
References create-flow.device, and find-flow.deviceId.
Member Data Documentation
ClusterCommunicationService org.onosproject.store.device.impl.GossipDeviceStore.clusterCommunicator protected
Definition at line 159 of file GossipDeviceStore.java.
ClusterService org.onosproject.store.device.impl.GossipDeviceStore.clusterService protected
Definition at line 162 of file GossipDeviceStore.java.
DeviceClockService org.onosproject.store.device.impl.GossipDeviceStore.deviceClockService protected
Definition at line 153 of file GossipDeviceStore.java.
MastershipService org.onosproject.store.device.impl.GossipDeviceStore.mastershipService protected
Definition at line 165 of file GossipDeviceStore.java.
final KryoSerializer org.onosproject.store.device.impl.GossipDeviceStore.SERIALIZER static protected
Initial value:
= new KryoSerializer() {
        @Override
        protected void setupKryoPool() {
            serializerPool = KryoNamespace.newBuilder()
                    .register(DistributedStoreSerializers.STORE_COMMON)
                    .nextId(DistributedStoreSerializers.STORE_CUSTOM_BEGIN)
                    .register(new InternalDeviceEventSerializer(), InternalDeviceEvent.class)
                    .register(new InternalDeviceOfflineEventSerializer(), InternalDeviceOfflineEvent.class)
                    .register(InternalDeviceRemovedEvent.class)
                    .register(new InternalPortEventSerializer(), InternalPortEvent.class)
                    .register(new InternalPortStatusEventSerializer(), InternalPortStatusEvent.class)
                    .register(DeviceAntiEntropyAdvertisement.class)
                    .register(DeviceFragmentId.class)
                    .register(PortFragmentId.class)
                    .register(DeviceInjectedEvent.class)
                    .register(PortInjectedEvent.class)
                    .build();
        }
    }
Definition at line 171 of file GossipDeviceStore.java.
StorageService org.onosproject.store.device.impl.GossipDeviceStore.storageService protected
Definition at line 156 of file GossipDeviceStore.java.
Referenced by org.onosproject.store.device.impl.GossipDeviceStore.activate().
MastershipTermService org.onosproject.store.device.impl.GossipDeviceStore.termService protected
Definition at line 168 of file GossipDeviceStore.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/device/impl/GossipDeviceStore.java