onos: org.onosproject.cli.AbstractCompleter Class Reference
org.onosproject.cli.AbstractCompleter Class Reference
Abstract argument completer.
Protected Member Functions
ArgumentCompleter.ArgumentList getArgumentList ()
Returns the argument list.
Detailed Description
Abstract argument completer.
Definition at line 26 of file AbstractCompleter.java.
Member Function Documentation
ArgumentCompleter.ArgumentList org.onosproject.cli.AbstractCompleter.getArgumentList () protected
Returns the argument list.
Returns
argument list
Definition at line 33 of file AbstractCompleter.java.
Referenced by org.onosproject.cli.net.LinkDstCompleter.complete(), org.onosproject.cli.cfg.ComponentPropertyNameCompleter.complete(), and org.onosproject.cli.app.ApplicationNameCompleter.complete().
The documentation for this class was generated from the following file:
cli/src/main/java/org/onosproject/cli/AbstractCompleter.java