onos: org.onosproject.net.device.DeviceServiceAdapter Class Reference
org.onosproject.net.device.DeviceServiceAdapter Class Reference
Test adapter for device service.
Public Member Functions
int getDeviceCount ()
Returns the number of infrastructure devices known to the system.
Iterable< Device > getDevices ()
Returns a collection of the currently known infrastructure devices.
Iterable< Device > getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Device getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
MastershipRole getRole (DeviceId deviceId)
Returns the current mastership role for the specified device.
List< Port > getPorts (DeviceId deviceId)
Returns the list of ports associated with the device.
List< PortStatistics > getPortStatistics (DeviceId deviceId)
Returns the list of port statistics associated with the device.
List< PortStatistics > getPortDeltaStatistics (DeviceId deviceId)
Returns the list of port delta statistics associated with the device.
Port getPort (DeviceId deviceId, PortNumber portNumber)
Returns the port with the specified number and hosted by the given device.
boolean isAvailable (DeviceId deviceId)
Indicates whether or not the device is presently online and available.
void addListener (DeviceListener listener)
void removeListener (DeviceListener listener)
Iterable< Device > getDevices (Type type)
Iterable< Device > getAvailableDevices (Type type)
Public Member Functions inherited from org.onosproject.net.device.DeviceService
Iterable< Device > getDevices (Device.Type type)
Returns a collection of the currently known infrastructure devices by device type.
Iterable< Device > getAvailableDevices (Device.Type type)
Returns an iterable collection of all devices currently available to the system by device type.
Detailed Description
Test adapter for device service.
Definition at line 33 of file DeviceServiceAdapter.java.
Member Function Documentation
void org.onosproject.net.device.DeviceServiceAdapter.addListener (DeviceListener listener)
Definition at line 86 of file DeviceServiceAdapter.java.
Iterable<Device> org.onosproject.net.device.DeviceServiceAdapter.getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Returns
device collection
Implements org.onosproject.net.device.DeviceService.
Definition at line 45 of file DeviceServiceAdapter.java.
References org.onosproject.net.device.DeviceServiceAdapter.getDevices(), and org.onosproject.net.device.DeviceServiceAdapter.isAvailable().
Iterable<Device> org.onosproject.net.device.DeviceServiceAdapter.getAvailableDevices (Type type)
Definition at line 99 of file DeviceServiceAdapter.java.
Device org.onosproject.net.device.DeviceServiceAdapter.getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
Parameters
deviceId device identifier
Returns
device or null if one with the given identifier is not known
Implements org.onosproject.net.device.DeviceService.
Definition at line 51 of file DeviceServiceAdapter.java.
int org.onosproject.net.device.DeviceServiceAdapter.getDeviceCount ()
Returns the number of infrastructure devices known to the system.
Returns
number of infrastructure devices
Implements org.onosproject.net.device.DeviceService.
Definition at line 35 of file DeviceServiceAdapter.java.
Iterable<Device> org.onosproject.net.device.DeviceServiceAdapter.getDevices ()
Returns a collection of the currently known infrastructure devices.
Returns
collection of devices
Implements org.onosproject.net.device.DeviceService.
Definition at line 40 of file DeviceServiceAdapter.java.
Referenced by org.onosproject.net.device.DeviceServiceAdapter.getAvailableDevices().
Iterable<Device> org.onosproject.net.device.DeviceServiceAdapter.getDevices (Type type)
Definition at line 94 of file DeviceServiceAdapter.java.
Port org.onosproject.net.device.DeviceServiceAdapter.getPort (DeviceId deviceId, PortNumber portNumber)
Returns the port with the specified number and hosted by the given device.
Parameters
deviceId device identifier
portNumber port number
Returns
device port
Implements org.onosproject.net.device.DeviceService.
Definition at line 76 of file DeviceServiceAdapter.java.
List<PortStatistics> org.onosproject.net.device.DeviceServiceAdapter.getPortDeltaStatistics (DeviceId deviceId)
Returns the list of port delta statistics associated with the device.
Parameters
deviceId device identifier
Returns
list of port statistics
Implements org.onosproject.net.device.DeviceService.
Definition at line 71 of file DeviceServiceAdapter.java.
List<Port> org.onosproject.net.device.DeviceServiceAdapter.getPorts (DeviceId deviceId)
Returns the list of ports associated with the device.
Parameters
deviceId device identifier
Returns
list of ports
Implements org.onosproject.net.device.DeviceService.
Definition at line 61 of file DeviceServiceAdapter.java.
List<PortStatistics> org.onosproject.net.device.DeviceServiceAdapter.getPortStatistics (DeviceId deviceId)
Returns the list of port statistics associated with the device.
Parameters
deviceId device identifier
Returns
list of port statistics
Implements org.onosproject.net.device.DeviceService.
Definition at line 66 of file DeviceServiceAdapter.java.
MastershipRole org.onosproject.net.device.DeviceServiceAdapter.getRole (DeviceId deviceId)
Returns the current mastership role for the specified device.
Parameters
deviceId device identifier
Returns
designated mastership role
Implements org.onosproject.net.device.DeviceService.
Definition at line 56 of file DeviceServiceAdapter.java.
References org.onosproject.net.MastershipRole.NONE.
boolean org.onosproject.net.device.DeviceServiceAdapter.isAvailable (DeviceId deviceId)
Indicates whether or not the device is presently online and available.
Parameters
deviceId device identifier
Returns
true if the device is available
Implements org.onosproject.net.device.DeviceService.
Definition at line 81 of file DeviceServiceAdapter.java.
Referenced by org.onosproject.net.device.DeviceServiceAdapter.getAvailableDevices().
void org.onosproject.net.device.DeviceServiceAdapter.removeListener (DeviceListener listener)
Definition at line 90 of file DeviceServiceAdapter.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/device/DeviceServiceAdapter.java