onos: org.onosproject.cord.gui.CordModelCache Class Reference
org.onosproject.cord.gui.CordModelCache Class Reference
In memory cache of the model of the subscriber's account.
Public Member Functions
Bundle getCurrentBundle ()
Returns the currently selected bundle.
void setCurrentBundle (String bundleId)
Sets a new bundle.
List< SubscriberUser > getUsers ()
Returns the list of current users for this subscriber account.
void applyPerUserParam (String userId, String funcId, String param, String value)
Applies a function parameter change for a user, pushing that change through to XOS.
synchronized String jsonLogin (String email)
Returns response JSON for login request.
synchronized String jsonDashboard ()
Returns the dashboard page data as JSON.
synchronized String jsonBundle ()
Returns the bundle page data as JSON.
synchronized String jsonUsers ()
Returns the users page data as JSON.
synchronized String jsonLogout ()
Returns logout acknowledgement as JSON.
Static Public Attributes
static final CordModelCache INSTANCE = new CordModelCache()
Singleton instance.
Additional Inherited Members
Static Protected Member Functions inherited from org.onosproject.cord.gui.model.JsonFactory
static ObjectNode objectNode ()
Returns a freshly minted object node.
static ArrayNode arrayNode ()
Returns a freshly minted array node.
Static Protected Attributes inherited from org.onosproject.cord.gui.model.JsonFactory
static final String ID = "id"
static final String NAME = "name"
static final String DESC = "desc"
static final String ICON_ID = "icon_id"
Detailed Description
In memory cache of the model of the subscriber's account.
Definition at line 47 of file CordModelCache.java.
Member Function Documentation
void org.onosproject.cord.gui.CordModelCache.applyPerUserParam (String userId, String funcId, String param, String value)
Applies a function parameter change for a user, pushing that change through to XOS.
Parameters
userId user identifier
funcId function identifier
param function parameter to change
value new value for function parameter
Definition at line 241 of file CordModelCache.java.
Bundle org.onosproject.cord.gui.CordModelCache.getCurrentBundle ()
Returns the currently selected bundle.
Returns
current bundle
Definition at line 194 of file CordModelCache.java.
Referenced by org.onosproject.cord.gui.CoreModelCacheTest.basic(), and org.onosproject.cord.gui.CoreModelCacheTest.chooseFamilyBundle().
List<SubscriberUser> org.onosproject.cord.gui.CordModelCache.getUsers ()
Returns the list of current users for this subscriber account.
Returns
the list of users
Definition at line 228 of file CordModelCache.java.
synchronized String org.onosproject.cord.gui.CordModelCache.jsonBundle ()
Returns the bundle page data as JSON.
Returns
bundle page JSON data
Definition at line 333 of file CordModelCache.java.
References org.onosproject.cord.gui.CordModelCache.jsonLogout().
synchronized String org.onosproject.cord.gui.CordModelCache.jsonDashboard ()
Returns the dashboard page data as JSON.
Returns
dashboard page JSON data
Definition at line 312 of file CordModelCache.java.
References org.onosproject.cord.gui.CordModelCache.jsonLogout(), and org.onosproject.cord.gui.model.JsonFactory.objectNode().
synchronized String org.onosproject.cord.gui.CordModelCache.jsonLogin (String email)
Returns response JSON for login request.
Depending on which email is used, will bind the GUI to the appropriate XOS Subscriber ID.
Parameters
email the supplied email
Returns
JSON acknowledgement
Definition at line 299 of file CordModelCache.java.
References org.onosproject.cord.gui.model.JsonFactory.objectNode().
synchronized String org.onosproject.cord.gui.CordModelCache.jsonLogout ()
Returns logout acknowledgement as JSON.
Returns
logout acknowledgement
Definition at line 368 of file CordModelCache.java.
References org.onosproject.cord.gui.model.JsonFactory.objectNode().
Referenced by org.onosproject.cord.gui.CordModelCache.jsonBundle(), org.onosproject.cord.gui.CordModelCache.jsonDashboard(), and org.onosproject.cord.gui.CordModelCache.jsonUsers().
synchronized String org.onosproject.cord.gui.CordModelCache.jsonUsers ()
Returns the users page data as JSON.
Returns
users page JSON data
Definition at line 350 of file CordModelCache.java.
References org.onosproject.cord.gui.CordModelCache.jsonLogout(), and org.onosproject.cord.gui.model.JsonFactory.objectNode().
Referenced by org.onosproject.cord.gui.CoreModelCacheTest.setNewLevel().
void org.onosproject.cord.gui.CordModelCache.setCurrentBundle (String bundleId)
Sets a new bundle.
Parameters
bundleId bundle identifier
Exceptions
IllegalArgumentException if bundle ID is unknown
Definition at line 204 of file CordModelCache.java.
Member Data Documentation
final CordModelCache org.onosproject.cord.gui.CordModelCache.INSTANCE = new CordModelCache() static
Singleton instance.
Definition at line 381 of file CordModelCache.java.
The documentation for this class was generated from the following file:
apps/demo/cord-gui/src/main/java/org/onosproject/cord/gui/CordModelCache.java