onos: org.onlab.nio.SelectorLoop Class Reference
org.onlab.nio.SelectorLoop Class Reference abstract
Abstraction of an I/O processing loop based on an NIO selector.
Public Member Functions
SelectorLoop (long selectTimeout) throws IOException
Creates a new selector loop with the given selection timeout.
Throwable getError ()
Returns the error, if there was one, that caused the loop to terminate prematurely.
void run ()
void shutdown ()
Triggers loop shutdown.
final synchronized boolean awaitStart (long timeout)
Waits for the loop execution to start.
final synchronized boolean awaitStop (long timeout)
Waits for the loop execution to stop.
Protected Member Functions
Selector openSelector () throws IOException
Opens a new selector for the use by the loop.
boolean isRunning ()
Indicates that the loop is marked to run.
abstract void loop () throws IOException
Contains the body of the I/O selector loop.
synchronized void notifyReady ()
Notifies observers waiting for loop to become ready.
Protected Attributes
final Logger log = LoggerFactory.getLogger(getClass())
final Selector selector
Selector used by this loop to pace the I/O operations.
long selectTimeout
Selection operations timeout; specified in millis.
Detailed Description
Abstraction of an I/O processing loop based on an NIO selector.
Definition at line 30 of file SelectorLoop.java.
Constructor & Destructor Documentation
org.onlab.nio.SelectorLoop.SelectorLoop (long selectTimeout) throws IOException
Creates a new selector loop with the given selection timeout.
Parameters
selectTimeout selection timeout; specified in millis
Exceptions
IOException if the backing selector cannot be opened
Definition at line 59 of file SelectorLoop.java.
References org.onlab.nio.SelectorLoop.openSelector(), and org.onlab.nio.SelectorLoop.selectTimeout.
Member Function Documentation
final synchronized boolean org.onlab.nio.SelectorLoop.awaitStart (long timeout)
Waits for the loop execution to start.
Parameters
timeout number of milliseconds to wait
Returns
true if loop started in time
Definition at line 144 of file SelectorLoop.java.
final synchronized boolean org.onlab.nio.SelectorLoop.awaitStop (long timeout)
Waits for the loop execution to stop.
Parameters
timeout number of milliseconds to wait
Returns
true if loop finished in time
Definition at line 162 of file SelectorLoop.java.
Throwable org.onlab.nio.SelectorLoop.getError ()
Returns the error, if there was one, that caused the loop to terminate prematurely.
Returns
error or null if there was none
Definition at line 89 of file SelectorLoop.java.
boolean org.onlab.nio.SelectorLoop.isRunning () protected
Indicates that the loop is marked to run.
Returns
true if the loop is marked to run
Definition at line 79 of file SelectorLoop.java.
Referenced by org.onlab.nio.AcceptorLoop.loop().
abstract void org.onlab.nio.SelectorLoop.loop () throws IOException protected pure virtual
Contains the body of the I/O selector loop.
Exceptions
IOException if an error is encountered while selecting I/O
Implemented in org.onlab.nio.IOLoop< M extends Message, S extends MessageStream< M > >, and org.onlab.nio.AcceptorLoop.
Referenced by org.onlab.nio.SelectorLoop.run().
synchronized void org.onlab.nio.SelectorLoop.notifyReady () protected
Notifies observers waiting for loop to become ready.
Definition at line 116 of file SelectorLoop.java.
Referenced by org.onlab.nio.AcceptorLoop.loop().
Selector org.onlab.nio.SelectorLoop.openSelector () throws IOException protected
Opens a new selector for the use by the loop.
Returns
newly open selector
Exceptions
IOException if the backing selector cannot be opened
Definition at line 71 of file SelectorLoop.java.
Referenced by org.onlab.nio.SelectorLoop.SelectorLoop().
void org.onlab.nio.SelectorLoop.run ()
Definition at line 101 of file SelectorLoop.java.
References org.onlab.nio.SelectorLoop.loop().
void org.onlab.nio.SelectorLoop.shutdown ()
Triggers loop shutdown.
Definition at line 124 of file SelectorLoop.java.
Referenced by org.onlab.nio.service.IOLoopMessaging.stop().
Member Data Documentation
final Logger org.onlab.nio.SelectorLoop.log = LoggerFactory.getLogger(getClass()) protected
Definition at line 32 of file SelectorLoop.java.
final Selector org.onlab.nio.SelectorLoop.selector protected
Selector used by this loop to pace the I/O operations.
Definition at line 37 of file SelectorLoop.java.
Referenced by org.onlab.nio.AcceptorLoop.openChannel().
long org.onlab.nio.SelectorLoop.selectTimeout protected
Selection operations timeout; specified in millis.
Definition at line 42 of file SelectorLoop.java.
Referenced by org.onlab.nio.AcceptorLoop.AcceptorLoop(), org.onlab.nio.AcceptorLoop.loop(), and org.onlab.nio.SelectorLoop.SelectorLoop().
The documentation for this class was generated from the following file:
utils/nio/src/main/java/org/onlab/nio/SelectorLoop.java