onos: org.onosproject.bgp.controller.BgpDpid Class Reference
org.onosproject.bgp.controller.BgpDpid Class Reference
The class representing a network bgp device id.
Public Member Functions
BgpDpid (final BgpLinkLsNlriVer4 linkNlri, int nodeDescriptorType)
Initialize bgp id to generate URI.
BgpDpid (final BgpNodeLSNlriVer4 nodeNlri)
Initialize bgp id to generate URI.
String toString ()
Static Public Member Functions
static URI uri (String value)
Produces bgp URI.
static BgpDpid bgpDpid (URI uri)
Returns bgpDpid created from the given device URI.
Static Public Attributes
static final int NODE_DESCRIPTOR_LOCAL = 1
static final int NODE_DESCRIPTOR_REMOTE = 2
Detailed Description
The class representing a network bgp device id.
This class is immutable.
Definition at line 30 of file BgpDpid.java.
Constructor & Destructor Documentation
org.onosproject.bgp.controller.BgpDpid.BgpDpid (final BgpLinkLsNlriVer4 linkNlri, int nodeDescriptorType)
Initialize bgp id to generate URI.
Parameters
linkNlri node Nlri.
nodeDescriptorType node descriptor type, local/remote
Definition at line 45 of file BgpDpid.java.
References org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getIdentifier(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getRouteDistinguisher(), org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.localNodeDescriptors(), org.onosproject.bgp.controller.BgpDpid.NODE_DESCRIPTOR_LOCAL, org.onosproject.bgp.controller.BgpDpid.NODE_DESCRIPTOR_REMOTE, and org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.remoteNodeDescriptors().
org.onosproject.bgp.controller.BgpDpid.BgpDpid (final BgpNodeLSNlriVer4 nodeNlri)
Initialize bgp id to generate URI.
Parameters
nodeNlri node Nlri.
Definition at line 72 of file BgpDpid.java.
References org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getIdentifier(), org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getLocalNodeDescriptors(), and org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getRouteDistinguisher().
Member Function Documentation
static BgpDpid org.onosproject.bgp.controller.BgpDpid.bgpDpid (URI uri) static
Returns bgpDpid created from the given device URI.
Parameters
uri device URI
Returns
object of BgpDpid
Definition at line 124 of file BgpDpid.java.
String org.onosproject.bgp.controller.BgpDpid.toString ()
Definition at line 99 of file BgpDpid.java.
static URI org.onosproject.bgp.controller.BgpDpid.uri (String value) static
Produces bgp URI.
Parameters
value string to get URI
Returns
bgp URI, otherwise null
Definition at line 109 of file BgpDpid.java.
Member Data Documentation
final int org.onosproject.bgp.controller.BgpDpid.NODE_DESCRIPTOR_LOCAL = 1 static
Definition at line 36 of file BgpDpid.java.
Referenced by org.onosproject.bgp.controller.BgpDpid.BgpDpid().
final int org.onosproject.bgp.controller.BgpDpid.NODE_DESCRIPTOR_REMOTE = 2 static
Definition at line 37 of file BgpDpid.java.
Referenced by org.onosproject.bgp.controller.BgpDpid.BgpDpid().
The documentation for this class was generated from the following file:
bgp/api/src/main/java/org/onosproject/bgp/controller/BgpDpid.java