onos: org.onlab.packet.RADIUS Class Reference
org.onlab.packet.RADIUS Class Reference
RADIUS packet.
Public Member Functions
RADIUS ()
Default constructor.
RADIUS (byte code, byte identifier)
Constructs a RADIUS packet with the given code and identifier.
byte getCode ()
Gets the code.
void setCode (byte code)
Sets the code.
byte getIdentifier ()
Gets the identifier.
void setIdentifier (byte identifier)
Sets the identifier.
byte[] getAuthenticator ()
Gets the authenticator.
void setAuthenticator (byte[] authenticator)
Sets the authenticator.
byte[] generateAuthCode ()
Generates an authenticator code.
boolean isValidCode ()
Checks if the packet's code field is valid.
RADIUSAttribute addMessageAuthenticator (String key)
Adds a message authenticator to the packet based on the given key.
boolean checkMessageAuthenticator (String key)
Checks the message authenticator in the packet with one generated from the given key.
void encapsulateMessage (EAP message)
Encapsulates an EAP packet in this RADIUS packet.
EAP decapsulateMessage ()
Decapsulates an EAP packet from the RADIUS packet.
ArrayList< RADIUSAttribute > getAttributeList (byte attrType)
Gets a list of attributes from the RADIUS packet.
RADIUSAttribute getAttribute (byte attrType)
Gets an attribute from the RADIUS packet.
RADIUSAttribute setAttribute (byte attrType, byte[] value)
Sets an attribute in the RADIUS packet.
RADIUSAttribute updateAttribute (byte attrType, byte[] value)
Updates an attribute in the RADIUS packet.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (final byte[] data, final int offset, final int length)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
Static Public Member Functions
static Deserializer< RADIUS > deserializer ()
Deserializer for RADIUS packets.
Static Public Attributes
static final short RADIUS_MIN_LENGTH = 20
static final short MAX_ATTR_VALUE_LENGTH = 253
static final short RADIUS_MAX_LENGTH = 4096
static final byte RADIUS_CODE_ACCESS_REQUEST = 0x01
static final byte RADIUS_CODE_ACCESS_ACCEPT = 0x02
static final byte RADIUS_CODE_ACCESS_REJECT = 0x03
static final byte RADIUS_CODE_ACCOUNTING_REQUEST = 0x04
static final byte RADIUS_CODE_ACCOUNTING_RESPONSE = 0x05
static final byte RADIUS_CODE_ACCESS_CHALLENGE = 0x0b
Protected Attributes
byte code
byte identifier
short length = RADIUS_MIN_LENGTH
byte[] authenticator = new byte[16]
List< RADIUSAttribute > attributes = new ArrayList<>()
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
RADIUS packet.
Definition at line 40 of file RADIUS.java.
Constructor & Destructor Documentation
org.onlab.packet.RADIUS.RADIUS ()
Default constructor.
Definition at line 65 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.deserializer().
org.onlab.packet.RADIUS.RADIUS (byte code, byte identifier)
Constructs a RADIUS packet with the given code and identifier.
Parameters
code code
identifier identifier
Definition at line 74 of file RADIUS.java.
References org.onlab.packet.RADIUS.code, and org.onlab.packet.RADIUS.identifier.
Member Function Documentation
RADIUSAttribute org.onlab.packet.RADIUS.addMessageAuthenticator (String key)
Adds a message authenticator to the packet based on the given key.
Parameters
key key to generate message authenticator
Returns
the messgae authenticator RADIUS attribute
Definition at line 163 of file RADIUS.java.
References obeliskHostCheck.mac, and org.onlab.packet.RADIUSAttribute.RADIUS_ATTR_MESSAGE_AUTH.
boolean org.onlab.packet.RADIUS.checkMessageAuthenticator (String key)
Checks the message authenticator in the packet with one generated from the given key.
Parameters
key key to generate message authenticator
Returns
whether the message authenticators match or not
Definition at line 202 of file RADIUS.java.
References obeliskHostCheck.mac, and org.onlab.packet.RADIUSAttribute.RADIUS_ATTR_MESSAGE_AUTH.
EAP org.onlab.packet.RADIUS.decapsulateMessage ()
Decapsulates an EAP packet from the RADIUS packet.
Returns
An EAP object containing the reassembled EAP message
Definition at line 265 of file RADIUS.java.
References org.onlab.packet.RADIUS.getAttributeList(), and org.onlab.packet.RADIUSAttribute.RADIUS_ATTR_EAP_MESSAGE.
IPacket org.onlab.packet.RADIUS.deserialize (final byte[] data, final int offset, final int length)
Definition at line 401 of file RADIUS.java.
References find-link-in-cluster.length, org.onlab.packet.RADIUSAttribute.length, org.onlab.packet.RADIUS.length, and org.onlab.packet.RADIUS.RADIUS_MIN_LENGTH.
static Deserializer<RADIUS> org.onlab.packet.RADIUS.deserializer () static
Deserializer for RADIUS packets.
Returns
deserializer
Definition at line 352 of file RADIUS.java.
References find-link-in-cluster.length, org.onlab.packet.RADIUSAttribute.length, org.onlab.packet.RADIUS.length, org.onlab.packet.RADIUS.RADIUS(), and org.onlab.packet.RADIUS.RADIUS_MIN_LENGTH.
void org.onlab.packet.RADIUS.encapsulateMessage (EAP message)
Encapsulates an EAP packet in this RADIUS packet.
Parameters
message EAP message object to be embedded in the RADIUS EAP-Message attributed
Definition at line 227 of file RADIUS.java.
References find-link-in-cluster.length, org.onlab.packet.EAP.length, org.onlab.packet.RADIUS.MAX_ATTR_VALUE_LENGTH, and org.onlab.packet.RADIUSAttribute.RADIUS_ATTR_EAP_MESSAGE.
byte [] org.onlab.packet.RADIUS.generateAuthCode ()
Generates an authenticator code.
Returns
the authenticator
Definition at line 138 of file RADIUS.java.
RADIUSAttribute org.onlab.packet.RADIUS.getAttribute (byte attrType)
Gets an attribute from the RADIUS packet.
Parameters
attrType the type field of the required attribute
Returns
the first attribute that matches the type or null if does not exist
Definition at line 303 of file RADIUS.java.
References org.onlab.packet.RADIUS.attributes.
Referenced by org.onosproject.aaa.AaaManagerTest.testAuthentication().
ArrayList<RADIUSAttribute> org.onlab.packet.RADIUS.getAttributeList (byte attrType)
Gets a list of attributes from the RADIUS packet.
Parameters
attrType the type field of the required attributes
Returns
List of the attributes that matches the type or an empty list if there is none
Definition at line 287 of file RADIUS.java.
References org.onlab.packet.RADIUS.attributes.
Referenced by org.onlab.packet.RADIUS.decapsulateMessage().
byte [] org.onlab.packet.RADIUS.getAuthenticator ()
Gets the authenticator.
Returns
authenticator
Definition at line 120 of file RADIUS.java.
byte org.onlab.packet.RADIUS.getCode ()
Gets the code.
Returns
code
Definition at line 84 of file RADIUS.java.
Referenced by org.onosproject.aaa.AaaManagerTest.testAuthentication().
byte org.onlab.packet.RADIUS.getIdentifier ()
Gets the identifier.
Returns
identifier
Definition at line 102 of file RADIUS.java.
Referenced by org.onosproject.aaa.AaaManagerTest.testAuthentication().
boolean org.onlab.packet.RADIUS.isValidCode ()
Checks if the packet's code field is valid.
Returns
whether the code is valid
Definition at line 148 of file RADIUS.java.
References org.onlab.packet.RADIUS.RADIUS_CODE_ACCESS_ACCEPT, org.onlab.packet.RADIUS.RADIUS_CODE_ACCESS_CHALLENGE, org.onlab.packet.RADIUS.RADIUS_CODE_ACCESS_REJECT, org.onlab.packet.RADIUS.RADIUS_CODE_ACCESS_REQUEST, org.onlab.packet.RADIUS.RADIUS_CODE_ACCOUNTING_REQUEST, and org.onlab.packet.RADIUS.RADIUS_CODE_ACCOUNTING_RESPONSE.
byte [] org.onlab.packet.RADIUS.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 382 of file RADIUS.java.
References find-link-in-cluster.length.
RADIUSAttribute org.onlab.packet.RADIUS.setAttribute (byte attrType, byte[] value)
Sets an attribute in the RADIUS packet.
Parameters
attrType the type field of the attribute to set
value value to be set
Returns
reference to the attribute object
Definition at line 319 of file RADIUS.java.
void org.onlab.packet.RADIUS.setAuthenticator (byte[] authenticator)
Sets the authenticator.
Parameters
authenticator authenticator
Definition at line 129 of file RADIUS.java.
References org.onlab.packet.RADIUS.authenticator.
void org.onlab.packet.RADIUS.setCode (byte code)
Sets the code.
Parameters
code code
Definition at line 93 of file RADIUS.java.
References org.onlab.packet.RADIUS.code.
void org.onlab.packet.RADIUS.setIdentifier (byte identifier)
Sets the identifier.
Parameters
identifier identifier
Definition at line 111 of file RADIUS.java.
References org.onlab.packet.RADIUS.identifier.
RADIUSAttribute org.onlab.packet.RADIUS.updateAttribute (byte attrType, byte[] value)
Updates an attribute in the RADIUS packet.
Parameters
attrType the type field of the attribute to update
value the value to update to
Returns
reference to the attribute object
Definition at line 334 of file RADIUS.java.
References org.onlab.packet.RADIUS.attributes, and org.onlab.packet.RADIUSAttribute.getLength().
Member Data Documentation
List<RADIUSAttribute> org.onlab.packet.RADIUS.attributes = new ArrayList<>() protected
Definition at line 45 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.getAttribute(), org.onlab.packet.RADIUS.getAttributeList(), and org.onlab.packet.RADIUS.updateAttribute().
byte [] org.onlab.packet.RADIUS.authenticator = new byte[16] protected
Definition at line 44 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.setAuthenticator().
byte org.onlab.packet.RADIUS.code protected
Definition at line 41 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.RADIUS(), and org.onlab.packet.RADIUS.setCode().
byte org.onlab.packet.RADIUS.identifier protected
Definition at line 42 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.RADIUS(), and org.onlab.packet.RADIUS.setIdentifier().
short org.onlab.packet.RADIUS.length = RADIUS_MIN_LENGTH protected
Definition at line 43 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.deserialize(), and org.onlab.packet.RADIUS.deserializer().
final short org.onlab.packet.RADIUS.MAX_ATTR_VALUE_LENGTH = 253 static
Definition at line 49 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.encapsulateMessage().
final byte org.onlab.packet.RADIUS.RADIUS_CODE_ACCESS_ACCEPT = 0x02 static
Definition at line 54 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.isValidCode(), and org.onosproject.aaa.AaaManagerTest.testAuthentication().
final byte org.onlab.packet.RADIUS.RADIUS_CODE_ACCESS_CHALLENGE = 0x0b static
Definition at line 58 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.isValidCode(), and org.onosproject.aaa.AaaManagerTest.testAuthentication().
final byte org.onlab.packet.RADIUS.RADIUS_CODE_ACCESS_REJECT = 0x03 static
Definition at line 55 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.isValidCode().
final byte org.onlab.packet.RADIUS.RADIUS_CODE_ACCESS_REQUEST = 0x01 static
Definition at line 53 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.isValidCode(), and org.onosproject.aaa.AaaManagerTest.testAuthentication().
final byte org.onlab.packet.RADIUS.RADIUS_CODE_ACCOUNTING_REQUEST = 0x04 static
Definition at line 56 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.isValidCode().
final byte org.onlab.packet.RADIUS.RADIUS_CODE_ACCOUNTING_RESPONSE = 0x05 static
Definition at line 57 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.isValidCode().
final short org.onlab.packet.RADIUS.RADIUS_MAX_LENGTH = 4096 static
Definition at line 50 of file RADIUS.java.
final short org.onlab.packet.RADIUS.RADIUS_MIN_LENGTH = 20 static
Definition at line 48 of file RADIUS.java.
Referenced by org.onlab.packet.RADIUS.deserialize(), and org.onlab.packet.RADIUS.deserializer().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/RADIUS.java