onos: org.onosproject.provider.nil.TopologySimulator Class Reference
org.onosproject.provider.nil.TopologySimulator Class Reference abstract
Abstraction of a provider capable to simulate some network topology.
Public Member Functions
void setUpTopology ()
Sets up network topology simulation.
void tearDownTopology ()
Tears down network topology simulation.
boolean contains (DeviceId deviceId)
Indicates whether or not the simulation knows of this device.
Protected Member Functions
void init (String topoShape, int deviceCount, int hostCount, ServiceDirectory directory, DeviceProviderService deviceProviderService, HostProviderService hostProviderService, LinkProviderService linkProviderService)
Initializes a new topology simulator with access to the specified service directory and various provider services.
void processTopoShape (String shape)
Processes the topology shape specifier.
void createDevices ()
Creates simulated devices.
abstract void createLinks ()
Creates simulated links.
abstract void createHosts ()
Creates simulated hosts.
void createDevice (int i)
Creates simulated device.
void createLink (int i, int j, int pi, int pj)
Creates simulated link between two devices on port 1 and port 2.
void createHosts (DeviceId deviceId, int portOffset)
Creates simularted hosts for the specified device.
void prepareForDeviceEvents (int count)
Prepares to count device added/available/removed events.
void waitForDeviceEvents ()
Waits for all expected device added/available/removed events.
void removeHosts ()
Removes any hosts previously advertised by this provider.
void removeLinks ()
Removes any links previously advertised by this provider.
void removeDevices ()
Removes any devices previously advertised by this provider.
List< PortDescription > buildPorts (int portCount)
Generates a list of a configured number of ports.
Protected Attributes
final Logger log = LoggerFactory.getLogger(getClass())
String[] topoShape
int deviceCount
int hostCount
ServiceDirectory directory
NodeId localNode
ClusterService clusterService
MastershipService mastershipService
DeviceAdminService deviceService
HostService hostService
LinkService linkService
DeviceProviderService deviceProviderService
HostProviderService hostProviderService
LinkProviderService linkProviderService
int maxWaitSeconds = 1
int infrastructurePorts = 2
CountDownLatch deviceLatch
final List< DeviceId > deviceIds = Lists.newArrayList()
Detailed Description
Abstraction of a provider capable to simulate some network topology.
Definition at line 68 of file TopologySimulator.java.
Member Function Documentation
List<PortDescription> org.onosproject.provider.nil.TopologySimulator.buildPorts (int portCount) protected
Generates a list of a configured number of ports.
Parameters
portCount number of ports
Returns
list of ports
Definition at line 352 of file TopologySimulator.java.
References org.onosproject.net.PortNumber.portNumber().
Referenced by org.onosproject.provider.nil.TopologySimulator.createDevice().
boolean org.onosproject.provider.nil.TopologySimulator.contains (DeviceId deviceId)
Indicates whether or not the simulation knows of this device.
Parameters
deviceId device identifier
Returns
true if device is known
Definition at line 367 of file TopologySimulator.java.
References find-flow.deviceId.
void org.onosproject.provider.nil.TopologySimulator.createDevice (int i) protected
Creates simulated device.
Parameters
i index of the device id in the list.
Definition at line 179 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.buildPorts(), org.onosproject.provider.nil.TopologySimulator.hostCount, find-device.id, and org.onosproject.provider.nil.TopologySimulator.infrastructurePorts.
Referenced by org.onosproject.provider.nil.TopologySimulator.createDevices().
void org.onosproject.provider.nil.TopologySimulator.createDevices () protected
Creates simulated devices.
Definition at line 158 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.createDevice(), and org.onosproject.provider.nil.TopologySimulator.deviceCount.
Referenced by org.onosproject.provider.nil.LinearTopologySimulator.setUpTopology(), and org.onosproject.provider.nil.TopologySimulator.setUpTopology().
abstract void org.onosproject.provider.nil.TopologySimulator.createHosts () protected pure virtual
Creates simulated hosts.
Implemented in org.onosproject.provider.nil.TreeTopologySimulator, org.onosproject.provider.nil.LinearTopologySimulator, org.onosproject.provider.nil.RerouteTopologySimulator, org.onosproject.provider.nil.MeshTopologySimulator, org.onosproject.provider.nil.SpineLeafTopologySimulator, org.onosproject.provider.nil.ConfiguredTopologySimulator, and org.onosproject.provider.nil.CentipedeTopologySimulator.
Referenced by org.onosproject.provider.nil.TopologySimulator.setUpTopology().
void org.onosproject.provider.nil.TopologySimulator.createHosts (DeviceId deviceId, int portOffset) protected
Creates simularted hosts for the specified device.
Parameters
deviceId device identifier
portOffset port offset where to start attaching hosts
Definition at line 221 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.hostCount, find-device.id, org.onlab.packet.VlanId.NONE, obeliskHostCheck.port, and org.onlab.packet.MacAddress.valueOf().
void org.onosproject.provider.nil.TopologySimulator.createLink (int i, int j, int pi, int pj) protected
Creates simulated link between two devices on port 1 and port 2.
Parameters
i index of one simulated device
j index of another simulated device Creates simulated link between two devices.
i index of one simulated device
j index of another simulated device
pi port number of i-th device
pj port number of j-th device
Definition at line 208 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.deviceIds.
Referenced by org.onosproject.provider.nil.AggLinkTopologySimulator.createLinks(), org.onosproject.provider.nil.RerouteTopologySimulator.createLinks(), org.onosproject.provider.nil.LinearTopologySimulator.createLinks(), and org.onosproject.provider.nil.TreeTopologySimulator.createLinks().
abstract void org.onosproject.provider.nil.TopologySimulator.createLinks () protected pure virtual
Creates simulated links.
Implemented in org.onosproject.provider.nil.TreeTopologySimulator, org.onosproject.provider.nil.LinearTopologySimulator, org.onosproject.provider.nil.RerouteTopologySimulator, org.onosproject.provider.nil.AggLinkTopologySimulator, org.onosproject.provider.nil.MeshTopologySimulator, org.onosproject.provider.nil.SpineLeafTopologySimulator, and org.onosproject.provider.nil.ConfiguredTopologySimulator.
Referenced by org.onosproject.provider.nil.TopologySimulator.setUpTopology().
void org.onosproject.provider.nil.TopologySimulator.init (String topoShape, int deviceCount, int hostCount, ServiceDirectory directory, DeviceProviderService deviceProviderService, HostProviderService hostProviderService, LinkProviderService linkProviderService) protected
Initializes a new topology simulator with access to the specified service directory and various provider services.
Parameters
topoShape topology shape specifier
deviceCount number of devices in the topology
hostCount number of hosts per device
directory service directory
deviceProviderService device provider service
hostProviderService host provider service
linkProviderService link provider service
Definition at line 110 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.deviceCount, org.onosproject.provider.nil.TopologySimulator.deviceProviderService, org.onosproject.provider.nil.TopologySimulator.directory, org.onosproject.provider.nil.TopologySimulator.hostCount, org.onosproject.provider.nil.TopologySimulator.hostProviderService, org.onosproject.provider.nil.TopologySimulator.linkProviderService, org.onosproject.provider.nil.TopologySimulator.localNode, and org.onosproject.provider.nil.TopologySimulator.processTopoShape().
void org.onosproject.provider.nil.TopologySimulator.prepareForDeviceEvents (int count) protected
Prepares to count device added/available/removed events.
Parameters
count number of events to count
Definition at line 243 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.deviceLatch.
Referenced by org.onosproject.provider.nil.TopologySimulator.removeDevices(), org.onosproject.provider.nil.LinearTopologySimulator.setUpTopology(), and org.onosproject.provider.nil.TopologySimulator.setUpTopology().
void org.onosproject.provider.nil.TopologySimulator.processTopoShape (String shape) protected
Processes the topology shape specifier.
Parameters
shape topology shape specifier
Definition at line 139 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.TopologySimulator.init().
void org.onosproject.provider.nil.TopologySimulator.removeDevices () protected
Removes any devices previously advertised by this provider.
Definition at line 289 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.deviceIds, org.onosproject.provider.nil.TopologySimulator.prepareForDeviceEvents(), and org.onosproject.provider.nil.TopologySimulator.waitForDeviceEvents().
Referenced by org.onosproject.provider.nil.TopologySimulator.tearDownTopology().
void org.onosproject.provider.nil.TopologySimulator.removeHosts () protected
Removes any hosts previously advertised by this provider.
Definition at line 273 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.hostProviderService, and org.onosproject.net.host.HostProviderService.hostVanished().
Referenced by org.onosproject.provider.nil.TopologySimulator.tearDownTopology().
void org.onosproject.provider.nil.TopologySimulator.removeLinks () protected
Removes any links previously advertised by this provider.
Definition at line 281 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.linkProviderService, and org.onosproject.net.link.LinkProviderService.linkVanished().
Referenced by org.onosproject.provider.nil.TopologySimulator.tearDownTopology().
void org.onosproject.provider.nil.TopologySimulator.setUpTopology ()
Sets up network topology simulation.
Definition at line 146 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.createDevices(), org.onosproject.provider.nil.TopologySimulator.createHosts(), org.onosproject.provider.nil.TopologySimulator.createLinks(), org.onosproject.provider.nil.TopologySimulator.deviceCount, org.onosproject.provider.nil.TopologySimulator.prepareForDeviceEvents(), and org.onosproject.provider.nil.TopologySimulator.waitForDeviceEvents().
void org.onosproject.provider.nil.TopologySimulator.tearDownTopology ()
Tears down network topology simulation.
Definition at line 264 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.removeDevices(), org.onosproject.provider.nil.TopologySimulator.removeHosts(), and org.onosproject.provider.nil.TopologySimulator.removeLinks().
void org.onosproject.provider.nil.TopologySimulator.waitForDeviceEvents () protected
Waits for all expected device added/available/removed events.
Definition at line 251 of file TopologySimulator.java.
References org.onosproject.provider.nil.TopologySimulator.maxWaitSeconds.
Referenced by org.onosproject.provider.nil.TopologySimulator.removeDevices(), org.onosproject.provider.nil.LinearTopologySimulator.setUpTopology(), and org.onosproject.provider.nil.TopologySimulator.setUpTopology().
Member Data Documentation
ClusterService org.onosproject.provider.nil.TopologySimulator.clusterService protected
Definition at line 79 of file TopologySimulator.java.
int org.onosproject.provider.nil.TopologySimulator.deviceCount protected
Definition at line 73 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.TopologySimulator.createDevices(), org.onosproject.provider.nil.RerouteTopologySimulator.createHosts(), org.onosproject.provider.nil.LinearTopologySimulator.createHosts(), org.onosproject.provider.nil.TreeTopologySimulator.createHosts(), org.onosproject.provider.nil.AggLinkTopologySimulator.createLinks(), org.onosproject.provider.nil.RerouteTopologySimulator.createLinks(), org.onosproject.provider.nil.LinearTopologySimulator.createLinks(), org.onosproject.provider.nil.TopologySimulator.init(), org.onosproject.provider.nil.AggLinkTopologySimulator.processTopoShape(), org.onosproject.provider.nil.RerouteTopologySimulator.processTopoShape(), org.onosproject.provider.nil.LinearTopologySimulator.processTopoShape(), org.onosproject.provider.nil.TreeTopologySimulator.processTopoShape(), org.onosproject.provider.nil.AggLinkTopologySimulator.setUpTopology(), org.onosproject.provider.nil.LinearTopologySimulator.setUpTopology(), org.onosproject.provider.nil.RerouteTopologySimulator.setUpTopology(), and org.onosproject.provider.nil.TopologySimulator.setUpTopology().
final List<DeviceId> org.onosproject.provider.nil.TopologySimulator.deviceIds = Lists.newArrayList() protected
Definition at line 94 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.RerouteTopologySimulator.createHosts(), org.onosproject.provider.nil.LinearTopologySimulator.createHosts(), org.onosproject.provider.nil.TreeTopologySimulator.createHosts(), org.onosproject.provider.nil.TopologySimulator.createLink(), and org.onosproject.provider.nil.TopologySimulator.removeDevices().
CountDownLatch org.onosproject.provider.nil.TopologySimulator.deviceLatch protected
Definition at line 92 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.TopologySimulator.prepareForDeviceEvents().
DeviceProviderService org.onosproject.provider.nil.TopologySimulator.deviceProviderService protected
Definition at line 86 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.ConfiguredTopologySimulator.createDevices(), and org.onosproject.provider.nil.TopologySimulator.init().
DeviceAdminService org.onosproject.provider.nil.TopologySimulator.deviceService protected
Definition at line 82 of file TopologySimulator.java.
ServiceDirectory org.onosproject.provider.nil.TopologySimulator.directory protected
Definition at line 76 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.TopologySimulator.init().
int org.onosproject.provider.nil.TopologySimulator.hostCount protected
Definition at line 74 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.TopologySimulator.createDevice(), org.onosproject.provider.nil.TreeTopologySimulator.createHosts(), org.onosproject.provider.nil.TopologySimulator.createHosts(), and org.onosproject.provider.nil.TopologySimulator.init().
HostProviderService org.onosproject.provider.nil.TopologySimulator.hostProviderService protected
Definition at line 87 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.ConfiguredTopologySimulator.createHosts(), org.onosproject.provider.nil.TopologySimulator.init(), and org.onosproject.provider.nil.TopologySimulator.removeHosts().
HostService org.onosproject.provider.nil.TopologySimulator.hostService protected
Definition at line 83 of file TopologySimulator.java.
int org.onosproject.provider.nil.TopologySimulator.infrastructurePorts = 2 protected
Definition at line 91 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.TopologySimulator.createDevice(), org.onosproject.provider.nil.CentipedeTopologySimulator.createHosts(), org.onosproject.provider.nil.RerouteTopologySimulator.createHosts(), org.onosproject.provider.nil.LinearTopologySimulator.createHosts(), org.onosproject.provider.nil.RerouteTopologySimulator.processTopoShape(), and org.onosproject.provider.nil.AggLinkTopologySimulator.processTopoShape().
LinkProviderService org.onosproject.provider.nil.TopologySimulator.linkProviderService protected
Definition at line 88 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.ConfiguredTopologySimulator.createLinks(), org.onosproject.provider.nil.TopologySimulator.init(), and org.onosproject.provider.nil.TopologySimulator.removeLinks().
LinkService org.onosproject.provider.nil.TopologySimulator.linkService protected
Definition at line 84 of file TopologySimulator.java.
NodeId org.onosproject.provider.nil.TopologySimulator.localNode protected
Definition at line 77 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.TopologySimulator.init().
final Logger org.onosproject.provider.nil.TopologySimulator.log = LoggerFactory.getLogger(getClass()) protected
Definition at line 70 of file TopologySimulator.java.
MastershipService org.onosproject.provider.nil.TopologySimulator.mastershipService protected
Definition at line 80 of file TopologySimulator.java.
int org.onosproject.provider.nil.TopologySimulator.maxWaitSeconds = 1 protected
Definition at line 90 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.TopologySimulator.waitForDeviceEvents().
String [] org.onosproject.provider.nil.TopologySimulator.topoShape protected
Definition at line 72 of file TopologySimulator.java.
Referenced by org.onosproject.provider.nil.LinearTopologySimulator.processTopoShape(), org.onosproject.provider.nil.RerouteTopologySimulator.processTopoShape(), and org.onosproject.provider.nil.TreeTopologySimulator.processTopoShape().
The documentation for this class was generated from the following file:
providers/null/src/main/java/org/onosproject/provider/nil/TopologySimulator.java