onos: org.onlab.packet.Ip4Prefix Class Reference
org.onlab.packet.Ip4Prefix Class Reference
The class representing an IPv4 network address.
Public Member Functions
Ip4Address address ()
Returns the IPv4 address value of the prefix.
Public Member Functions inherited from org.onlab.packet.IpPrefix
IpAddress.Version version ()
Returns the IP version of the prefix.
boolean isIp4 ()
Tests whether the IP version of this prefix is IPv4.
boolean isIp6 ()
Tests whether the IP version of this prefix is IPv6.
IpAddress address ()
Returns the IP address value of the prefix.
int prefixLength ()
Returns the IP address prefix length.
Ip4Prefix getIp4Prefix ()
Gets the Ip4Prefix view of the IP prefix.
Ip6Prefix getIp6Prefix ()
Gets the Ip6Prefix view of the IP prefix.
boolean contains (IpPrefix other)
Determines whether a given IP prefix is contained within this prefix.
boolean contains (IpAddress other)
Determines whether a given IP address is contained within this prefix.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static Ip4Prefix valueOf (int address, int prefixLength)
Converts an integer and a prefix length into an IPv4 prefix.
static Ip4Prefix valueOf (byte[] address, int prefixLength)
Converts a byte array and a prefix length into an IPv4 prefix.
static Ip4Prefix valueOf (Ip4Address address, int prefixLength)
Converts an IPv4 address and a prefix length into an IPv4 prefix.
static Ip4Prefix valueOf (String address)
Converts a CIDR (slash) notation string (e.g., "10.1.0.0/16") into an IPv4 prefix.
Static Public Member Functions inherited from org.onlab.packet.IpPrefix
static IpPrefix valueOf (int address, int prefixLength)
Converts an integer and a prefix length into an IPv4 prefix.
static IpPrefix valueOf (IpAddress.Version version, byte[] address, int prefixLength)
Converts a byte array and a prefix length into an IP prefix.
static IpPrefix valueOf (IpAddress address, int prefixLength)
Converts an IP address and a prefix length into an IP prefix.
static IpPrefix valueOf (String address)
Converts a CIDR (slash) notation string (e.g., "10.1.0.0/16" or "1111:2222::/64") into an IP prefix.
Static Public Attributes
static final IpAddress.Version VERSION = IpAddress.Version.INET
static final int MAX_MASK_LENGTH = IpPrefix.MAX_INET_MASK_LENGTH
Static Public Attributes inherited from org.onlab.packet.IpPrefix
static final int MAX_INET_MASK_LENGTH = IpAddress.INET_BIT_LENGTH
static final int MAX_INET6_MASK_LENGTH = IpAddress.INET6_BIT_LENGTH
Additional Inherited Members
Protected Member Functions inherited from org.onlab.packet.IpPrefix
IpPrefix (IpAddress address, int prefixLength)
Constructor for given IP address, and a prefix length.
Detailed Description
The class representing an IPv4 network address.
This class is immutable.
Definition at line 22 of file Ip4Prefix.java.
Member Function Documentation
Ip4Address org.onlab.packet.Ip4Prefix.address ()
Returns the IPv4 address value of the prefix.
Returns
the IPv4 address value of the prefix
Definition at line 43 of file Ip4Prefix.java.
Referenced by org.onlab.packet.Ip4PrefixTest.testAddressAndPrefixLengthIPv4().
static Ip4Prefix org.onlab.packet.Ip4Prefix.valueOf (int address, int prefixLength) static
Converts an integer and a prefix length into an IPv4 prefix.
Parameters
address an integer representing the IPv4 address
prefixLength the prefix length
Returns
an IPv4 prefix
Exceptions
IllegalArgumentException if the prefix length value is invalid
Definition at line 56 of file Ip4Prefix.java.
References org.onlab.packet.IpPrefix.prefixLength(), and org.onlab.packet.Ip4Address.valueOf().
Referenced by org.onosproject.routing.bgp.BgpSessionManagerTest.testBgpRoutePreference(), org.onlab.packet.Ip4PrefixTest.testContainsIpPrefixIPv4(), org.onlab.packet.Ip4PrefixTest.testEqualityIPv4(), org.onosproject.sdnip.IntentSyncTest.testIntentSync(), org.onosproject.store.serializers.KryoSerializerTest.testIp4Prefix(), org.onosproject.routing.impl.RouterTest.testIpv4LocalRouteAdd(), org.onosproject.routing.impl.RouterTest.testIpv4RouteDelete(), org.onosproject.routing.bgp.BgpSessionManagerTest.testProcessedBgpUpdateMessages(), and org.onosproject.routing.impl.RouterTest.testRouteUpdate().
static Ip4Prefix org.onlab.packet.Ip4Prefix.valueOf (byte[] address, int prefixLength) static
Converts a byte array and a prefix length into an IPv4 prefix.
Parameters
address the IPv4 address value stored in network byte order
prefixLength the prefix length
Returns
an IPv4 prefix
Exceptions
IllegalArgumentException if the prefix length value is invalid
Definition at line 68 of file Ip4Prefix.java.
References org.onlab.packet.IpPrefix.prefixLength(), and org.onlab.packet.Ip4Address.valueOf().
static Ip4Prefix org.onlab.packet.Ip4Prefix.valueOf (Ip4Address address, int prefixLength) static
Converts an IPv4 address and a prefix length into an IPv4 prefix.
Parameters
address the IPv4 address
prefixLength the prefix length
Returns
an IPv4 prefix
Exceptions
IllegalArgumentException if the prefix length value is invalid
Definition at line 80 of file Ip4Prefix.java.
static Ip4Prefix org.onlab.packet.Ip4Prefix.valueOf (String address) static
Converts a CIDR (slash) notation string (e.g., "10.1.0.0/16") into an IPv4 prefix.
Parameters
address an IP prefix in string form (e.g., "10.1.0.0/16")
Returns
an IPv4 prefix
Exceptions
IllegalArgumentException if the arguments are invalid
Definition at line 92 of file Ip4Prefix.java.
References org.onlab.packet.IpPrefix.prefixLength().
Member Data Documentation
final int org.onlab.packet.Ip4Prefix.MAX_MASK_LENGTH = IpPrefix.MAX_INET_MASK_LENGTH static
Definition at line 25 of file Ip4Prefix.java.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), and org.onlab.packet.Ip4PrefixTest.testMaxMaskLength().
final IpAddress.Version org.onlab.packet.Ip4Prefix.VERSION = IpAddress.Version.INET static
Definition at line 23 of file Ip4Prefix.java.
Referenced by org.onlab.packet.Ip4PrefixTest.testAddressVersion().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/Ip4Prefix.java