onos: org.onosproject.store.consistent.impl.CommitResponse Class Reference
org.onosproject.store.consistent.impl.CommitResponse Class Reference
Result of a Transaction commit operation.
Public Member Functions
boolean success ()
List< UpdateResult< String,
byte[]> > updates ()
String toString ()
Static Public Member Functions
static CommitResponse success (List< UpdateResult< String, byte[]>> updates)
static CommitResponse failure ()
Detailed Description
Result of a Transaction commit operation.
Definition at line 28 of file CommitResponse.java.
Member Function Documentation
static CommitResponse org.onosproject.store.consistent.impl.CommitResponse.failure () static
Definition at line 37 of file CommitResponse.java.
static CommitResponse org.onosproject.store.consistent.impl.CommitResponse.success (List< UpdateResult< String, byte[]>> updates) static
Definition at line 33 of file CommitResponse.java.
References org.onosproject.store.consistent.impl.CommitResponse.updates().
boolean org.onosproject.store.consistent.impl.CommitResponse.success ()
Definition at line 46 of file CommitResponse.java.
Referenced by org.onosproject.store.consistent.impl.CommitResponse.toString().
String org.onosproject.store.consistent.impl.CommitResponse.toString ()
Definition at line 55 of file CommitResponse.java.
References org.onosproject.store.consistent.impl.CommitResponse.success(), and org.onosproject.store.consistent.impl.CommitResponse.updates().
List<UpdateResult<String, byte[]> > org.onosproject.store.consistent.impl.CommitResponse.updates ()
Definition at line 50 of file CommitResponse.java.
Referenced by org.onosproject.store.consistent.impl.CommitResponse.success(), and org.onosproject.store.consistent.impl.CommitResponse.toString().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/CommitResponse.java