onos: org.onosproject.store.device.impl.InternalPortEvent Class Reference
org.onosproject.store.device.impl.InternalPortEvent Class Reference
Information published by GossipDeviceStore to notify peers of a port change event.
Public Member Functions
DeviceId deviceId ()
ProviderId providerId ()
Timestamped< List
< PortDescription > > portDescriptions ()
String toString ()
Protected Member Functions
InternalPortEvent (ProviderId providerId, DeviceId deviceId, Timestamped< List< PortDescription >> portDescriptions)
InternalPortEvent ()
Detailed Description
Information published by GossipDeviceStore to notify peers of a port change event.
Definition at line 31 of file InternalPortEvent.java.
Constructor & Destructor Documentation
org.onosproject.store.device.impl.InternalPortEvent.InternalPortEvent (ProviderId providerId, DeviceId deviceId, Timestamped< List< PortDescription >> portDescriptions) protected
Definition at line 37 of file InternalPortEvent.java.
References org.onosproject.store.device.impl.InternalPortEvent.deviceId(), org.onosproject.store.device.impl.InternalPortEvent.portDescriptions(), and org.onosproject.store.device.impl.InternalPortEvent.providerId().
org.onosproject.store.device.impl.InternalPortEvent.InternalPortEvent () protected
Definition at line 68 of file InternalPortEvent.java.
Member Function Documentation
DeviceId org.onosproject.store.device.impl.InternalPortEvent.deviceId ()
Definition at line 46 of file InternalPortEvent.java.
Referenced by org.onosproject.store.device.impl.InternalPortEvent.InternalPortEvent(), and org.onosproject.store.device.impl.InternalPortEvent.toString().
Timestamped<List<PortDescription> > org.onosproject.store.device.impl.InternalPortEvent.portDescriptions ()
Definition at line 54 of file InternalPortEvent.java.
Referenced by org.onosproject.store.device.impl.InternalPortEvent.InternalPortEvent(), and org.onosproject.store.device.impl.InternalPortEvent.toString().
ProviderId org.onosproject.store.device.impl.InternalPortEvent.providerId ()
Definition at line 50 of file InternalPortEvent.java.
Referenced by org.onosproject.store.device.impl.InternalPortEvent.InternalPortEvent(), and org.onosproject.store.device.impl.InternalPortEvent.toString().
String org.onosproject.store.device.impl.InternalPortEvent.toString ()
Definition at line 59 of file InternalPortEvent.java.
References org.onosproject.store.device.impl.InternalPortEvent.deviceId(), org.onosproject.store.device.impl.InternalPortEvent.portDescriptions(), and org.onosproject.store.device.impl.InternalPortEvent.providerId().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/device/impl/InternalPortEvent.java