onos: org.onosproject.pcepio.types.IPv4NeighborAddressTlv Class Reference
org.onosproject.pcepio.types.IPv4NeighborAddressTlv Class Reference
Provides IPv4 Neighbor Address .
Public Member Functions
IPv4NeighborAddressTlv (int rawValue)
Constructor to initialize rawValue.
int getInt ()
Returns value of IPv4 Neighbor Address.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static IPv4NeighborAddressTlv of (final int raw)
Returns newly created IPv4NeighborAddressTlv object.
static IPv4NeighborAddressTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of IPv4-Neighbor-Address-Tlv.
Static Public Attributes
static final short TYPE = 8
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IPv4NeighborAddressTlv.class)
Detailed Description
Provides IPv4 Neighbor Address .
Definition at line 30 of file IPv4NeighborAddressTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IPv4NeighborAddressTlv.IPv4NeighborAddressTlv (int rawValue)
Constructor to initialize rawValue.
Parameters
rawValue IPv4-Neighbor-Address-Tlv
Definition at line 54 of file IPv4NeighborAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4NeighborAddressTlv.equals(), and org.onosproject.pcepio.types.IPv4NeighborAddressTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.IPv4NeighborAddressTlv.equals (Object obj)
Definition at line 99 of file IPv4NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv4NeighborAddressTlv.IPv4NeighborAddressTlv().
int org.onosproject.pcepio.types.IPv4NeighborAddressTlv.getInt ()
Returns value of IPv4 Neighbor Address.
Returns
rawValue IPv4 Neighbor Address
Definition at line 74 of file IPv4NeighborAddressTlv.java.
short org.onosproject.pcepio.types.IPv4NeighborAddressTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 89 of file IPv4NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv4NeighborAddressTlv.LENGTH.
short org.onosproject.pcepio.types.IPv4NeighborAddressTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 84 of file IPv4NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv4NeighborAddressTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.IPv4NeighborAddressTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 79 of file IPv4NeighborAddressTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IPv4NeighborAddressTlv.hashCode ()
Definition at line 94 of file IPv4NeighborAddressTlv.java.
static IPv4NeighborAddressTlv org.onosproject.pcepio.types.IPv4NeighborAddressTlv.of (final int raw) static
Returns newly created IPv4NeighborAddressTlv object.
Parameters
raw value of IPv4-Neighbor-Address
Returns
object of IPv4NeighborAddressTlv
Definition at line 65 of file IPv4NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv4NeighborAddressTlv.IPv4NeighborAddressTlv().
static IPv4NeighborAddressTlv org.onosproject.pcepio.types.IPv4NeighborAddressTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of IPv4-Neighbor-Address-Tlv.
Parameters
c input channel buffer
Returns
object of IPv4-Neighbor-Address-Tlv
Definition at line 125 of file IPv4NeighborAddressTlv.java.
String org.onosproject.pcepio.types.IPv4NeighborAddressTlv.toString ()
Definition at line 130 of file IPv4NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv4NeighborAddressTlv.LENGTH, and org.onosproject.pcepio.types.IPv4NeighborAddressTlv.TYPE.
int org.onosproject.pcepio.types.IPv4NeighborAddressTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 111 of file IPv4NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv4NeighborAddressTlv.LENGTH, and org.onosproject.pcepio.types.IPv4NeighborAddressTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.IPv4NeighborAddressTlv.LENGTH = 4 static
Definition at line 45 of file IPv4NeighborAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4NeighborAddressTlv.getLength(), org.onosproject.pcepio.types.IPv4NeighborAddressTlv.toString(), and org.onosproject.pcepio.types.IPv4NeighborAddressTlv.write().
final Logger org.onosproject.pcepio.types.IPv4NeighborAddressTlv.log = LoggerFactory.getLogger(IPv4NeighborAddressTlv.class) static protected
Definition at line 42 of file IPv4NeighborAddressTlv.java.
final short org.onosproject.pcepio.types.IPv4NeighborAddressTlv.TYPE = 8 static
Definition at line 44 of file IPv4NeighborAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4NeighborAddressTlv.getType(), org.onosproject.pcepio.types.IPv4NeighborAddressTlv.toString(), and org.onosproject.pcepio.types.IPv4NeighborAddressTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IPv4NeighborAddressTlv.java