onos: org.onosproject.net.AbstractModel Class Reference
org.onosproject.net.AbstractModel Class Reference
Base implementation of a network model entity.
Public Member Functions
AbstractModel ()
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Protected Member Functions
AbstractModel (ProviderId providerId, Annotations...annotations)
Creates a model entity attributed to the specified provider and optionally annotated.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Base implementation of a network model entity.
Definition at line 23 of file AbstractModel.java.
Constructor & Destructor Documentation
org.onosproject.net.AbstractModel.AbstractModel ()
Definition at line 28 of file AbstractModel.java.
References org.onosproject.net.AbstractModel.providerId().
org.onosproject.net.AbstractModel.AbstractModel (ProviderId providerId, Annotations... annotations) protected
Creates a model entity attributed to the specified provider and optionally annotated.
Parameters
providerId identity of the provider
annotations optional key/value annotations
Definition at line 39 of file AbstractModel.java.
References org.onosproject.net.AbstractAnnotated.annotations(), and org.onosproject.net.AbstractModel.providerId().
Member Function Documentation
ProviderId org.onosproject.net.AbstractModel.providerId ()
Returns the identifier of the provider which supplied the entity.
Returns
provider identification
Implements org.onosproject.net.Provided.
Definition at line 45 of file AbstractModel.java.
Referenced by org.onosproject.net.AbstractModel.AbstractModel(), org.onosproject.net.DefaultLink.DefaultLink(), and org.onosproject.common.DefaultTopology.DefaultTopology().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/AbstractModel.java