onos: org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter Class Reference
org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter Class Reference
Default implementation for a distributed AsyncAtomicCounter backed by partitioned Raft DB.
Public Member Functions
DefaultAsyncAtomicCounter (String name, Database database, boolean meteringEnabled)
CompletableFuture< Long > incrementAndGet ()
Atomically increment by one the current value.
CompletableFuture< Long > get ()
Returns the current value of the counter without modifying it.
CompletableFuture< Long > getAndIncrement ()
Atomically increment by one the current value.
CompletableFuture< Long > getAndAdd (long delta)
Atomically adds the given value to the current value.
CompletableFuture< Long > addAndGet (long delta)
Atomically adds the given value to the current value.
CompletableFuture< Void > set (long value)
Atomically sets the given value to the current value.
CompletableFuture< Boolean > compareAndSet (long expectedValue, long updateValue)
Atomically sets the given counter to the updated value if the current value is the expected value, otherwise no change occurs.
Detailed Description
Default implementation for a distributed AsyncAtomicCounter backed by partitioned Raft DB.
The initial value will be zero.
Definition at line 30 of file DefaultAsyncAtomicCounter.java.
Constructor & Destructor Documentation
org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.DefaultAsyncAtomicCounter (String name, Database database, boolean meteringEnabled)
Definition at line 45 of file DefaultAsyncAtomicCounter.java.
Member Function Documentation
CompletableFuture<Long> org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.addAndGet (long delta)
Atomically adds the given value to the current value.
Parameters
delta the value to add
Returns
updated value
Implements org.onosproject.store.service.AsyncAtomicCounter.
Definition at line 82 of file DefaultAsyncAtomicCounter.java.
Referenced by org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.incrementAndGet().
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.compareAndSet (long expectedValue, long updateValue)
Atomically sets the given counter to the updated value if the current value is the expected value, otherwise no change occurs.
Parameters
expectedValue the expected current value of the counter
updateValue the new value to be set
Returns
true if the update occurred and the expected value was equal to the current value, false otherwise
Implements org.onosproject.store.service.AsyncAtomicCounter.
Definition at line 96 of file DefaultAsyncAtomicCounter.java.
CompletableFuture<Long> org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.get ()
Returns the current value of the counter without modifying it.
Returns
current value
Implements org.onosproject.store.service.AsyncAtomicCounter.
Definition at line 61 of file DefaultAsyncAtomicCounter.java.
CompletableFuture<Long> org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.getAndAdd (long delta)
Atomically adds the given value to the current value.
Parameters
delta the value to add
Returns
previous value
Implements org.onosproject.store.service.AsyncAtomicCounter.
Definition at line 75 of file DefaultAsyncAtomicCounter.java.
Referenced by org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.getAndIncrement().
CompletableFuture<Long> org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.getAndIncrement ()
Atomically increment by one the current value.
Returns
previous value
Implements org.onosproject.store.service.AsyncAtomicCounter.
Definition at line 68 of file DefaultAsyncAtomicCounter.java.
References org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.getAndAdd().
CompletableFuture<Long> org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.incrementAndGet ()
Atomically increment by one the current value.
Returns
updated value
Implements org.onosproject.store.service.AsyncAtomicCounter.
Definition at line 54 of file DefaultAsyncAtomicCounter.java.
References org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.addAndGet().
CompletableFuture<Void> org.onosproject.store.consistent.impl.DefaultAsyncAtomicCounter.set (long value)
Atomically sets the given value to the current value.
Parameters
value new value
Returns
future void
Implements org.onosproject.store.service.AsyncAtomicCounter.
Definition at line 89 of file DefaultAsyncAtomicCounter.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DefaultAsyncAtomicCounter.java