onos: org.onosproject.provider.lldp.impl.LldpLinkProviderTest Class Reference
org.onosproject.provider.lldp.impl.LldpLinkProviderTest Class Reference
Public Member Functions
void setUp ()
void basics ()
void switchAdd ()
void switchRemove ()
void switchSuppressedByAnnotation ()
Checks that links on a reconfigured switch are properly removed.
void switchSuppressByBlacklist ()
void portUp ()
void portDown ()
void portRemoved ()
void portSuppressedByDeviceAnnotationConfig ()
Checks that discovery on reconfigured switch are properly restarted.
void portSuppressedByParentDeviceIdBlacklist ()
Checks that discovery on reconfigured switch are properly restarted.
void portSuppressedByDeviceTypeConfig ()
Checks that discovery on reconfigured switch are properly restarted.
void portSuppressedByPortConfig ()
Checks that discovery on reconfigured port are properly restarted.
void portSuppressedByPortBlacklist ()
void portUnknown ()
void unknownPktCtx ()
void knownPktCtx ()
void tearDown ()
void addDeviceTypeRule ()
void updateDeviceTypeRule ()
void addAnnotationRule ()
void updateAnnotationRule ()
Detailed Description
Definition at line 92 of file LldpLinkProviderTest.java.
Member Function Documentation
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.addAnnotationRule ()
Definition at line 576 of file LldpLinkProviderTest.java.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.addDeviceTypeRule ()
Definition at line 540 of file LldpLinkProviderTest.java.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.basics ()
Definition at line 151 of file LldpLinkProviderTest.java.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.knownPktCtx ()
Definition at line 450 of file LldpLinkProviderTest.java.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portDown ()
Definition at line 233 of file LldpLinkProviderTest.java.
References org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portRemoved ()
Definition at line 244 of file LldpLinkProviderTest.java.
References org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByDeviceAnnotationConfig ()
Checks that discovery on reconfigured switch are properly restarted.
When Device is configured with suppression:ON, Port also is same
When Device is reconfigured without suppression:OFF, Port should be included for discovery
Definition at line 258 of file LldpLinkProviderTest.java.
References org.onosproject.net.DefaultAnnotations.builder(), org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers, and org.onosproject.provider.lldp.impl.LldpLinkProvider.NO_LLDP.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByDeviceTypeConfig ()
Checks that discovery on reconfigured switch are properly restarted.
When Device is configured without suppression:OFF, Port should be included for discovery
Definition at line 341 of file LldpLinkProviderTest.java.
References org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByParentDeviceIdBlacklist ()
Checks that discovery on reconfigured switch are properly restarted.
When Device is configured without suppression:OFF, Port should be included for discovery
When Device is reconfigured with suppression:ON, Port also is same
Definition at line 297 of file LldpLinkProviderTest.java.
References org.onosproject.net.config.NetworkConfigEvent.Type.CONFIG_ADDED, and org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByPortBlacklist ()
Definition at line 401 of file LldpLinkProviderTest.java.
References org.onosproject.net.config.NetworkConfigEvent.Type.CONFIG_ADDED, org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers, and org.onosproject.net.PortNumber.portNumber().
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portSuppressedByPortConfig ()
Checks that discovery on reconfigured port are properly restarted.
Definition at line 379 of file LldpLinkProviderTest.java.
References org.onosproject.net.DefaultAnnotations.builder(), org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers, and org.onosproject.provider.lldp.impl.LldpLinkProvider.NO_LLDP.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portUnknown ()
Definition at line 429 of file LldpLinkProviderTest.java.
References org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.portUp ()
Definition at line 224 of file LldpLinkProviderTest.java.
References org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.setUp ()
Definition at line 128 of file LldpLinkProviderTest.java.
References org.onosproject.core.ApplicationId.name(), and org.onosproject.core.CoreService.registerApplication().
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.switchAdd ()
Definition at line 157 of file LldpLinkProviderTest.java.
References org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.switchRemove ()
Definition at line 165 of file LldpLinkProviderTest.java.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.switchSuppressByBlacklist ()
Definition at line 204 of file LldpLinkProviderTest.java.
References org.onosproject.net.config.NetworkConfigEvent.Type.CONFIG_ADDED.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.switchSuppressedByAnnotation ()
Checks that links on a reconfigured switch are properly removed.
Definition at line 182 of file LldpLinkProviderTest.java.
References org.onosproject.net.DefaultAnnotations.builder(), org.onosproject.provider.lldp.impl.LldpLinkProvider.discoverers, and org.onosproject.provider.lldp.impl.LldpLinkProvider.NO_LLDP.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.tearDown ()
Definition at line 464 of file LldpLinkProviderTest.java.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.unknownPktCtx ()
Definition at line 440 of file LldpLinkProviderTest.java.
References org.onosproject.net.packet.PacketContext.isHandled().
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.updateAnnotationRule ()
Definition at line 593 of file LldpLinkProviderTest.java.
void org.onosproject.provider.lldp.impl.LldpLinkProviderTest.updateDeviceTypeRule ()
Definition at line 556 of file LldpLinkProviderTest.java.
The documentation for this class was generated from the following file:
providers/lldp/src/test/java/org/onosproject/provider/lldp/impl/LldpLinkProviderTest.java