onos: org.onosproject.routing.impl.Router Class Reference
org.onosproject.routing.impl.Router Class Reference
This class processes route updates and maintains a Routing Information Base (RIB).
Classes
class InternalHostListener
Listener for host events.
Public Member Functions
void activate ()
void deactivate ()
void addFibListener (FibListener fibListener)
Adds FIB listener.
void start ()
Starts the routing service.
void stop ()
Stops the routing service.
Collection< RouteEntry > getRoutes4 ()
Gets all IPv4 routes from the RIB.
Collection< RouteEntry > getRoutes6 ()
Gets all IPv6 routes from the RIB.
RouteEntry getLongestMatchableRouteEntry (IpAddress ipAddress)
Finds out the route entry which has the longest matchable IP prefix.
Protected Attributes
CoreService coreService
HostService hostService
BgpService bgpService
InterfaceService interfaceService
RoutingConfigurationService routingConfigurationService
Additional Inherited Members
Public Attributes inherited from org.onosproject.routing.RoutingService
String ROUTER_APP_ID = "org.onosproject.router"
Class< BgpConfig > CONFIG_CLASS = BgpConfig.class
Detailed Description
This class processes route updates and maintains a Routing Information Base (RIB).
After route updates have been processed and next hops have been resolved, FIB updates are sent to any listening FIB components.
Definition at line 78 of file Router.java.
Member Function Documentation
void org.onosproject.routing.impl.Router.activate ()
Definition at line 119 of file Router.java.
References org.onosproject.routing.RoutingService.ROUTER_APP_ID.
void org.onosproject.routing.impl.Router.addFibListener (FibListener fibListener)
Adds FIB listener.
Parameters
fibListener listener to send FIB updates to
Implements org.onosproject.routing.RoutingService.
Definition at line 141 of file Router.java.
void org.onosproject.routing.impl.Router.deactivate ()
Definition at line 136 of file Router.java.
RouteEntry org.onosproject.routing.impl.Router.getLongestMatchableRouteEntry (IpAddress ipAddress)
Finds out the route entry which has the longest matchable IP prefix.
Parameters
ipAddress IP address used to find out longest matchable IP prefix
Returns
a route entry which has the longest matchable IP prefix if found, otherwise null
Implements org.onosproject.routing.RoutingService.
Definition at line 543 of file Router.java.
References org.onlab.packet.Ip6Address.BIT_LENGTH, org.onlab.packet.Ip4Address.BIT_LENGTH, org.onlab.packet.IpAddress.isIp4(), and org.onlab.packet.IpPrefix.valueOf().
Collection<RouteEntry> org.onosproject.routing.impl.Router.getRoutes4 ()
Gets all IPv4 routes from the RIB.
Returns
all IPv4 routes from the RIB
Implements org.onosproject.routing.RoutingService.
Definition at line 220 of file Router.java.
Referenced by org.onosproject.routing.impl.RouterTest.testIpv4LocalRouteAdd().
Collection<RouteEntry> org.onosproject.routing.impl.Router.getRoutes6 ()
Gets all IPv6 routes from the RIB.
Returns
all IPv6 routes from the RIB
Implements org.onosproject.routing.RoutingService.
Definition at line 240 of file Router.java.
Referenced by org.onosproject.routing.impl.RouterTest.testIpv6LocalRouteAdd().
void org.onosproject.routing.impl.Router.start ()
Starts the routing service.
Implements org.onosproject.routing.RoutingService.
Definition at line 146 of file Router.java.
void org.onosproject.routing.impl.Router.stop ()
Stops the routing service.
Implements org.onosproject.routing.RoutingService.
Definition at line 155 of file Router.java.
Member Data Documentation
BgpService org.onosproject.routing.impl.Router.bgpService protected
Definition at line 107 of file Router.java.
CoreService org.onosproject.routing.impl.Router.coreService protected
Definition at line 101 of file Router.java.
HostService org.onosproject.routing.impl.Router.hostService protected
Definition at line 104 of file Router.java.
InterfaceService org.onosproject.routing.impl.Router.interfaceService protected
Definition at line 110 of file Router.java.
RoutingConfigurationService org.onosproject.routing.impl.Router.routingConfigurationService protected
Definition at line 113 of file Router.java.
The documentation for this class was generated from the following file:
apps/routing/src/main/java/org/onosproject/routing/impl/Router.java