onos: org.onosproject.vtnweb.resources.PortPairResourceTest Class Reference
org.onosproject.vtnweb.resources.PortPairResourceTest Class Reference
Unit tests for port pair REST APIs.
Public Member Functions
void setUpTest ()
Sets up the global values for all the tests.
void tearDownTest ()
Cleans up.
void testPortPairsEmpty ()
Tests the result of the rest api GET when there are no port pairs.
void testGetPortPairId ()
Tests the result of a rest api GET for port pair id.
void testBadGet ()
Tests that a fetch of a non-existent port pair object throws an exception.
void testPost ()
Tests creating a port pair with POST.
void testDelete ()
Tests deleting a port pair.
Public Member Functions inherited from org.onosproject.vtnweb.resources.VtnResourceTest
int getPort (int defaultPort)
Assigns an available port for the test.
AppDescriptor configure ()
Detailed Description
Unit tests for port pair REST APIs.
Definition at line 54 of file PortPairResourceTest.java.
Member Function Documentation
void org.onosproject.vtnweb.resources.PortPairResourceTest.setUpTest ()
Sets up the global values for all the tests.
Definition at line 131 of file PortPairResourceTest.java.
void org.onosproject.vtnweb.resources.PortPairResourceTest.tearDownTest ()
Cleans up.
Definition at line 141 of file PortPairResourceTest.java.
void org.onosproject.vtnweb.resources.PortPairResourceTest.testBadGet ()
Tests that a fetch of a non-existent port pair object throws an exception.
Definition at line 180 of file PortPairResourceTest.java.
References org.onosproject.vtnrsc.portpair.PortPairService.getPortPair().
void org.onosproject.vtnweb.resources.PortPairResourceTest.testDelete ()
Tests deleting a port pair.
Definition at line 217 of file PortPairResourceTest.java.
References create-flow.location, and org.onosproject.vtnrsc.portpair.PortPairService.removePortPair().
void org.onosproject.vtnweb.resources.PortPairResourceTest.testGetPortPairId ()
Tests the result of a rest api GET for port pair id.
Definition at line 161 of file PortPairResourceTest.java.
References org.onosproject.vtnrsc.portpair.PortPairService.exists(), and org.onosproject.vtnrsc.portpair.PortPairService.getPortPair().
void org.onosproject.vtnweb.resources.PortPairResourceTest.testPortPairsEmpty ()
Tests the result of the rest api GET when there are no port pairs.
Definition at line 148 of file PortPairResourceTest.java.
References org.onosproject.vtnrsc.portpair.PortPairService.getPortPairs().
void org.onosproject.vtnweb.resources.PortPairResourceTest.testPost ()
Tests creating a port pair with POST.
Definition at line 198 of file PortPairResourceTest.java.
References org.onosproject.vtnrsc.portpair.PortPairService.createPortPair().
The documentation for this class was generated from the following file:
apps/vtn/vtnweb/src/test/java/org/onosproject/vtnweb/resources/PortPairResourceTest.java