onos: org.onosproject.net.resource.link.BandwidthResourceRequest Class Reference
org.onosproject.net.resource.link.BandwidthResourceRequest Class Reference
Representation of a request for bandwidth resource.
Public Member Functions
BandwidthResourceRequest (BandwidthResource bandwidth)
Creates a new BandwidthResourceRequest with BandwidthResource object.
BandwidthResource bandwidth ()
Returns the bandwidth resource.
ResourceType type ()
Returns the resource type.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Representation of a request for bandwidth resource.
Deprecated:
in Emu Release
Definition at line 30 of file BandwidthResourceRequest.java.
Constructor & Destructor Documentation
org.onosproject.net.resource.link.BandwidthResourceRequest.BandwidthResourceRequest (BandwidthResource bandwidth)
Creates a new BandwidthResourceRequest with BandwidthResource object.
Parameters
bandwidth BandwidthResource object to be requested
Definition at line 39 of file BandwidthResourceRequest.java.
References org.onosproject.net.resource.link.BandwidthResourceRequest.bandwidth().
Referenced by org.onosproject.net.resource.link.BandwidthResourceRequest.equals().
Member Function Documentation
BandwidthResource org.onosproject.net.resource.link.BandwidthResourceRequest.bandwidth ()
Returns the bandwidth resource.
Returns
the bandwidth resource
Definition at line 48 of file BandwidthResourceRequest.java.
Referenced by org.onosproject.net.resource.link.BandwidthResourceRequest.BandwidthResourceRequest(), and org.onosproject.net.resource.link.BandwidthResourceRequest.toString().
boolean org.onosproject.net.resource.link.BandwidthResourceRequest.equals (Object obj)
Definition at line 63 of file BandwidthResourceRequest.java.
References org.onosproject.net.resource.link.BandwidthResourceRequest.BandwidthResourceRequest().
int org.onosproject.net.resource.link.BandwidthResourceRequest.hashCode ()
Definition at line 58 of file BandwidthResourceRequest.java.
String org.onosproject.net.resource.link.BandwidthResourceRequest.toString ()
Definition at line 75 of file BandwidthResourceRequest.java.
References org.onosproject.net.resource.link.BandwidthResourceRequest.bandwidth().
ResourceType org.onosproject.net.resource.link.BandwidthResourceRequest.type ()
Returns the resource type.
Returns
the resource type
Implements org.onosproject.net.resource.ResourceRequest.
Definition at line 53 of file BandwidthResourceRequest.java.
References org.onosproject.net.resource.ResourceType.BANDWIDTH.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/resource/link/BandwidthResourceRequest.java