onos: org.onosproject.grpc.Device Class Reference
org.onosproject.grpc.Device Class Reference
Classes
class DeviceConnected
Protobuf type.
interface DeviceConnectedOrBuilder
class DeviceDescription
Protobuf type.
interface DeviceDescriptionOrBuilder
class DeviceDisconnected
Protobuf type.
interface DeviceDisconnectedOrBuilder
class DeviceProviderMsg
Protobuf type.
interface DeviceProviderMsgOrBuilder
class DeviceProviderServiceMsg
Protobuf type.
interface DeviceProviderServiceMsgOrBuilder
enum DeviceType
Protobuf enum.
class IsReachableRequest
Protobuf type.
interface IsReachableRequestOrBuilder
class IsReachableResponse
Protobuf type.
interface IsReachableResponseOrBuilder
enum MastershipRole
Protobuf enum.
class PortStatusChanged
Protobuf type.
interface PortStatusChangedOrBuilder
class ReceivedRoleReply
Protobuf type.
interface ReceivedRoleReplyOrBuilder
class RegisterProvider
Protobuf type.
interface RegisterProviderOrBuilder
class RoleChanged
Protobuf type.
interface RoleChangedOrBuilder
class TriggerProbe
Protobuf type.
interface TriggerProbeOrBuilder
class UpdatePorts
Protobuf type.
interface UpdatePortsOrBuilder
class UpdatePortStatistics
Protobuf type.
interface UpdatePortStatisticsOrBuilder
Static Public Member Functions
static void registerAllExtensions (com.google.protobuf.ExtensionRegistry registry)
static
com.google.protobuf.Descriptors.FileDescriptor getDescriptor ()
Detailed Description
Definition at line 6 of file Device.java.
Member Function Documentation
static com.google.protobuf.Descriptors.FileDescriptor org.onosproject.grpc.Device.getDescriptor () static
Definition at line 11411 of file Device.java.
Referenced by org.onosproject.grpc.Device.DeviceType.getDescriptorForType(), org.onosproject.grpc.Device.MastershipRole.getDescriptorForType(), org.onosproject.grpc.Device.DeviceType.getValueDescriptor(), org.onosproject.grpc.Device.MastershipRole.getValueDescriptor(), org.onosproject.grpc.Device.DeviceType.valueOf(), and org.onosproject.grpc.Device.MastershipRole.valueOf().
static void org.onosproject.grpc.Device.registerAllExtensions (com.google.protobuf.ExtensionRegistry registry) static
Definition at line 8 of file Device.java.
The documentation for this class was generated from the following file:
incubator/rpc-grpc/target/generated-sources/protobuf/java/org/onosproject/grpc/Device.java