onos: org.onosproject.net.DefaultHostTest Class Reference
org.onosproject.net.DefaultHostTest Class Reference
Public Member Functions
void testEquality ()
void basics ()
Additional Inherited Members
Static Protected Attributes inherited from org.onosproject.net.TestDeviceParams
static final ProviderId PID = new ProviderId("of", "foo")
static final DeviceId DID1 = deviceId("of:foo")
static final DeviceId DID2 = deviceId("of:bar")
static final MacAddress MAC1 = MacAddress.valueOf("00:11:00:00:00:01")
static final MacAddress MAC2 = MacAddress.valueOf("00:22:00:00:00:02")
static final VlanId VLAN1 = VlanId.vlanId((short) 11)
static final VlanId VLAN2 = VlanId.vlanId((short) 22)
static final IpAddress IP1 = IpAddress.valueOf("10.0.0.1")
static final IpAddress IP2 = IpAddress.valueOf("10.0.0.2")
static final IpAddress IP3 = IpAddress.valueOf("10.0.0.3")
static final PortNumber P1 = PortNumber.portNumber(100)
static final PortNumber P2 = PortNumber.portNumber(200)
static final HostId HID1 = HostId.hostId(MAC1, VLAN1)
static final HostId HID2 = HostId.hostId(MAC2, VLAN2)
static final HostLocation LOC1 = new HostLocation(DID1, P1, 123L)
static final HostLocation LOC2 = new HostLocation(DID2, P2, 123L)
static final Set< IpAddress > IPSET1 = Sets.newHashSet(IP1, IP2)
static final Set< IpAddress > IPSET2 = Sets.newHashSet(IP1, IP3)
Detailed Description
Definition at line 24 of file DefaultHostTest.java.
Member Function Documentation
void org.onosproject.net.DefaultHostTest.basics ()
Definition at line 41 of file DefaultHostTest.java.
References org.onosproject.net.TestDeviceParams.HID1, org.onosproject.net.Host.id(), org.onosproject.net.Host.ipAddresses(), org.onosproject.net.TestDeviceParams.IPSET1, org.onosproject.net.TestDeviceParams.LOC1, org.onosproject.net.Host.location(), org.onosproject.net.Host.mac(), org.onosproject.net.TestDeviceParams.MAC1, org.onosproject.net.TestDeviceParams.PID, org.onosproject.net.Provided.providerId(), org.onosproject.net.Host.vlan(), and org.onosproject.net.TestDeviceParams.VLAN1.
void org.onosproject.net.DefaultHostTest.testEquality ()
Definition at line 27 of file DefaultHostTest.java.
References org.onosproject.net.TestDeviceParams.HID1, org.onosproject.net.TestDeviceParams.HID2, org.onosproject.net.TestDeviceParams.IPSET1, org.onosproject.net.TestDeviceParams.IPSET2, org.onosproject.net.TestDeviceParams.LOC1, org.onosproject.net.TestDeviceParams.LOC2, org.onosproject.net.TestDeviceParams.MAC1, org.onosproject.net.TestDeviceParams.MAC2, org.onosproject.net.TestDeviceParams.PID, org.onosproject.net.TestDeviceParams.VLAN1, and org.onosproject.net.TestDeviceParams.VLAN2.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/DefaultHostTest.java