onos: org.onosproject.segmentrouting.RoutingRulePopulator Class Reference
org.onosproject.segmentrouting.RoutingRulePopulator Class Reference
Public Member Functions
RoutingRulePopulator (SegmentRoutingManager srManager)
Creates a RoutingRulePopulator object.
void resetCounter ()
Resets the population counter.
long getCounter ()
Returns the number of rules populated.
void populateIpRuleForHost (DeviceId deviceId, Ip4Address hostIp, MacAddress hostMac, PortNumber outPort)
Populates IP flow rules for specific hosts directly connected to the switch.
void revokeIpRuleForHost (DeviceId deviceId, Ip4Address hostIp, MacAddress hostMac, PortNumber outPort)
boolean populateIpRuleForSubnet (DeviceId deviceId, Set< Ip4Prefix > subnets, DeviceId destSw, Set< DeviceId > nextHops)
Populates IP flow rules for the subnets of the destination router.
boolean populateIpRuleForRouter (DeviceId deviceId, IpPrefix ipPrefix, DeviceId destSw, Set< DeviceId > nextHops)
Populates IP flow rules for the router IP address.
boolean populateMplsRule (DeviceId deviceId, DeviceId destSwId, Set< DeviceId > nextHops)
Populates MPLS flow rules to all routers.
void populateRouterMacVlanFilters (DeviceId deviceId)
Creates a filtering objective to permit all untagged packets with a dstMac corresponding to the router's MAC address.
void populateRouterIpPunts (DeviceId deviceId)
Creates a forwarding objective to punt all IP packets, destined to the router's port IP addresses, to the controller.
void populateSubnetBroadcastRule (DeviceId deviceId)
Populates a forwarding objective to send packets that miss other high priority Bridging Table entries to a group that contains all ports of its subnet.
Detailed Description
Definition at line 57 of file RoutingRulePopulator.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.RoutingRulePopulator.RoutingRulePopulator (SegmentRoutingManager srManager)
Creates a RoutingRulePopulator object.
Parameters
srManager segment routing manager reference
Definition at line 74 of file RoutingRulePopulator.java.
References org.onosproject.segmentrouting.SegmentRoutingManager.deviceConfiguration.
Member Function Documentation
long org.onosproject.segmentrouting.RoutingRulePopulator.getCounter ()
Returns the number of rules populated.
Returns
number of rules
Definition at line 92 of file RoutingRulePopulator.java.
void org.onosproject.segmentrouting.RoutingRulePopulator.populateIpRuleForHost (DeviceId deviceId, Ip4Address hostIp, MacAddress hostMac, PortNumber outPort)
Populates IP flow rules for specific hosts directly connected to the switch.
Parameters
deviceId switch ID to set the rules
hostIp host IP address
hostMac host MAC address
outPort port where the host is connected
Definition at line 105 of file RoutingRulePopulator.java.
References find-flow.deviceId, and create-flow.outPort.
boolean org.onosproject.segmentrouting.RoutingRulePopulator.populateIpRuleForRouter (DeviceId deviceId, IpPrefix ipPrefix, DeviceId destSw, Set< DeviceId > nextHops)
Populates IP flow rules for the router IP address.
Parameters
deviceId target device ID to set the rules
ipPrefix the IP address of the destination router
destSw device ID of the destination router
nextHops next hop switch ID list
Returns
true if all rules are set successfully, false otherwise
Definition at line 199 of file RoutingRulePopulator.java.
References org.onosproject.segmentrouting.SegmentRoutingManager.appId, org.onosproject.segmentrouting.SegmentRoutingManager.ASSIGNED_VLAN_NO_SUBNET, find-flow.deviceId, and org.onlab.packet.Ethernet.TYPE_IPV4.
Referenced by org.onosproject.segmentrouting.RoutingRulePopulator.populateIpRuleForSubnet().
boolean org.onosproject.segmentrouting.RoutingRulePopulator.populateIpRuleForSubnet (DeviceId deviceId, Set< Ip4Prefix > subnets, DeviceId destSw, Set< DeviceId > nextHops)
Populates IP flow rules for the subnets of the destination router.
Parameters
deviceId switch ID to set the rules
subnets subnet information
destSw destination switch ID
nextHops next hop switch ID list
Returns
true if all rules are set successfully, false otherwise
Definition at line 176 of file RoutingRulePopulator.java.
References org.onosproject.segmentrouting.RoutingRulePopulator.populateIpRuleForRouter().
boolean org.onosproject.segmentrouting.RoutingRulePopulator.populateMplsRule (DeviceId deviceId, DeviceId destSwId, Set< DeviceId > nextHops)
Populates MPLS flow rules to all routers.
Parameters
deviceId target device ID of the switch to set the rules
destSwId destination switch device ID
nextHops next hops switch ID list
Returns
true if all rules are set successfully, false otherwise
Definition at line 276 of file RoutingRulePopulator.java.
References org.onosproject.segmentrouting.SegmentRoutingManager.ASSIGNED_VLAN_NO_SUBNET, find-flow.deviceId, and org.onlab.packet.Ethernet.MPLS_UNICAST.
void org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterIpPunts (DeviceId deviceId)
Creates a forwarding objective to punt all IP packets, destined to the router's port IP addresses, to the controller.
Note that the input port should not be matched on, as these packets can come from any input. Furthermore, these are applied only by the master instance.
Parameters
deviceId the switch dpid for the router
Definition at line 475 of file RoutingRulePopulator.java.
References org.onosproject.segmentrouting.SegmentRoutingManager.appId, org.onosproject.net.PortNumber.CONTROLLER, find-flow.deviceId, org.onosproject.mastership.MastershipService.isLocalMaster(), org.onosproject.segmentrouting.SegmentRoutingManager.mastershipService, org.onlab.packet.IpPrefix.MAX_INET_MASK_LENGTH, org.onlab.packet.Ethernet.TYPE_IPV4, and org.onosproject.net.flowobjective.ForwardingObjective.Flag.VERSATILE.
void org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterMacVlanFilters (DeviceId deviceId)
Creates a filtering objective to permit all untagged packets with a dstMac corresponding to the router's MAC address.
For those pipelines that need to internally assign vlans to untagged packets, this method provides per-subnet vlan-ids as metadata.
Note that the vlan assignment is only done by the master-instance for a switch. However we send the filtering objective from slave-instances as well, so that drivers can obtain other information (like Router MAC and IP).
Parameters
deviceId the switch dpid for the router
Definition at line 430 of file RoutingRulePopulator.java.
References org.onosproject.segmentrouting.SegmentRoutingManager.appId, org.onosproject.segmentrouting.SegmentRoutingManager.ASSIGNED_VLAN_NO_SUBNET, find-flow.deviceId, org.onosproject.segmentrouting.SegmentRoutingManager.deviceService, org.onosproject.net.device.DeviceService.getPorts(), org.onosproject.mastership.MastershipService.isLocalMaster(), org.onosproject.segmentrouting.SegmentRoutingManager.mastershipService, org.onosproject.net.flow.criteria.Criteria.matchEthDst(), org.onosproject.net.flow.criteria.Criteria.matchVlanId(), org.onlab.packet.VlanId.NONE, obeliskHostCheck.port, and org.onlab.packet.VlanId.vlanId().
void org.onosproject.segmentrouting.RoutingRulePopulator.populateSubnetBroadcastRule (DeviceId deviceId)
Populates a forwarding objective to send packets that miss other high priority Bridging Table entries to a group that contains all ports of its subnet.
Note: We assume that packets sending from the edge switches to the hosts have untagged VLAN. The VLAN tag will be popped later in the flooding group.
Parameters
deviceId switch ID to set the rules
Definition at line 524 of file RoutingRulePopulator.java.
References org.onosproject.segmentrouting.SegmentRoutingManager.appId, find-flow.deviceId, org.onlab.packet.MacAddress.NONE, and org.onosproject.net.flowobjective.ForwardingObjective.Flag.SPECIFIC.
void org.onosproject.segmentrouting.RoutingRulePopulator.resetCounter ()
Resets the population counter.
Definition at line 83 of file RoutingRulePopulator.java.
void org.onosproject.segmentrouting.RoutingRulePopulator.revokeIpRuleForHost (DeviceId deviceId, Ip4Address hostIp, MacAddress hostMac, PortNumber outPort)
Definition at line 123 of file RoutingRulePopulator.java.
References find-flow.deviceId, and create-flow.outPort.
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/RoutingRulePopulator.java