onos: org.onosproject.ui.table.TableRequestHandler Class Reference
org.onosproject.ui.table.TableRequestHandler Class Reference abstract
Message handler specifically for table views.
Public Member Functions
TableRequestHandler (String reqType, String respType, String nodeName)
Constructs a table request handler for a specific table view.
void process (long sid, ObjectNode payload)
Processes the incoming message payload from the client.
Public Member Functions inherited from org.onosproject.ui.RequestHandler
RequestHandler (String eventType)
String eventType ()
Returns the event type that this handler handles.
Protected Member Functions
TableModel createTableModel ()
Creates the table model (devoid of data) using getColumnIds() to initialize it, ready to be populated.
String defaultColumnId ()
Returns the default column ID to be used when one is not supplied in the payload as the column on which to sort.
abstract String[] getColumnIds ()
Subclasses should return the array of column IDs with which to initialize their table model.
abstract void populateTable (TableModel tm, ObjectNode payload)
Subclasses should populate the table model by adding rows.
Protected Member Functions inherited from org.onosproject.ui.RequestHandler
void sendMessage (String eventType, long sid, ObjectNode payload)
Sends a message back to the client.
void sendMessage (ObjectNode message)
Sends a message back to the client.
void chain (String eventType, long sid, ObjectNode payload)
Allows one request handler to pass the event on to another for further processing.
String string (ObjectNode node, String key)
Returns the specified node property as a string.
String string (ObjectNode node, String key, String defValue)
Returns the specified node property as a string, with a default fallback.
Additional Inherited Members
Static Protected Attributes inherited from org.onosproject.ui.RequestHandler
static final ObjectMapper MAPPER = new ObjectMapper()
Detailed Description
Message handler specifically for table views.
Definition at line 26 of file TableRequestHandler.java.
Constructor & Destructor Documentation
org.onosproject.ui.table.TableRequestHandler.TableRequestHandler (String reqType, String respType, String nodeName)
Constructs a table request handler for a specific table view.
When table requests come in, the handler will generate the appropriate table rows, sort them according the the request sort parameters, and send back the response to the client.
Parameters
reqType type of the request event
respType type of the response event
nodeName name of JSON node holding row data
Definition at line 41 of file TableRequestHandler.java.
Member Function Documentation
TableModel org.onosproject.ui.table.TableRequestHandler.createTableModel () protected
Creates the table model (devoid of data) using getColumnIds() to initialize it, ready to be populated.
This default implementation returns a table model with default formatters and comparators for all columns.
Returns
an empty table model
Definition at line 70 of file TableRequestHandler.java.
References org.onosproject.ui.table.TableRequestHandler.getColumnIds().
Referenced by org.onosproject.ui.table.TableRequestHandler.process().
String org.onosproject.ui.table.TableRequestHandler.defaultColumnId () protected
Returns the default column ID to be used when one is not supplied in the payload as the column on which to sort.
This default implementation returns "id".
Returns
default sort column identifier
Definition at line 82 of file TableRequestHandler.java.
Referenced by org.onosproject.ui.table.TableRequestHandler.process().
abstract String [] org.onosproject.ui.table.TableRequestHandler.getColumnIds () protected pure virtual
Subclasses should return the array of column IDs with which to initialize their table model.
Returns
the column IDs
Referenced by org.onosproject.ui.table.TableRequestHandler.createTableModel().
abstract void org.onosproject.ui.table.TableRequestHandler.populateTable (TableModel tm, ObjectNode payload) protected pure virtual
Subclasses should populate the table model by adding rows.
    tm.addRow()
        .cell(COL_ONE, ...)
        .cell(COL_TWO, ...)
        ... ;
The request payload is provided in case there are request filtering parameters (other than sort column and sort direction) that are required to generate the appropriate data.
Parameters
tm the table model
payload request payload
Referenced by org.onosproject.ui.table.TableRequestHandler.process().
void org.onosproject.ui.table.TableRequestHandler.process (long sid, ObjectNode payload) virtual
Processes the incoming message payload from the client.
Parameters
sid message sequence identifier
payload request message payload
Implements org.onosproject.ui.RequestHandler.
Definition at line 48 of file TableRequestHandler.java.
References org.onosproject.ui.table.TableRequestHandler.createTableModel(), org.onosproject.ui.table.TableRequestHandler.defaultColumnId(), org.onosproject.ui.table.TableRequestHandler.populateTable(), and org.onosproject.ui.RequestHandler.sendMessage().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/table/TableRequestHandler.java