onos: org.onosproject.routing.config.impl.RoutingConfigurationImpl Class Reference
org.onosproject.routing.config.impl.RoutingConfigurationImpl Class Reference
Implementation of RoutingConfigurationService which reads routing configuration from a file.
Public Member Functions
void activate ()
void deactivate ()
void readConfiguration ()
Instructs the configuration reader to read the configuration from the file.
Map< String, BgpSpeaker > getBgpSpeakers ()
Gets the list of BGP speakers inside the SDN network.
Map< IpAddress, BgpPeer > getBgpPeers ()
Gets the list of configured BGP peers.
Set< Interface > getInterfaces ()
Retrieves the entire set of interfaces in the network.
Set< ConnectPoint > getBgpPeerConnectPoints ()
Retrieves the entire set of connect points connected to BGP peers in the network.
Interface getInterface (ConnectPoint connectPoint)
Retrieves the interface associated with the given connect point.
Interface getInterface (IpAddress ip)
Retrieves the interface associated with the given IP address.
Interface getMatchingInterface (IpAddress ipAddress)
Retrieves the interface that matches the given IP address.
boolean isIpAddressLocal (IpAddress ipAddress)
Evaluates whether an IP address belongs to local SDN network.
boolean isIpPrefixLocal (IpPrefix ipPrefix)
Evaluates whether an IP prefix belongs to local SDN network.
boolean isVirtualGatewayIpAddress (IpAddress ipAddress)
Evaluates whether an IP address is a virtual gateway IP address.
MacAddress getVirtualGatewayMacAddress ()
Gets the MAC address configured for virtual gateway in SDN network.
Protected Attributes
NetworkConfigRegistry registry
NetworkConfigService configService
CoreService coreService
InterfaceService interfaceService
Detailed Description
Implementation of RoutingConfigurationService which reads routing configuration from a file.
Definition at line 69 of file RoutingConfigurationImpl.java.
Member Function Documentation
void org.onosproject.routing.config.impl.RoutingConfigurationImpl.activate ()
Definition at line 112 of file RoutingConfigurationImpl.java.
References org.onosproject.routing.config.impl.RoutingConfigurationImpl.readConfiguration().
void org.onosproject.routing.config.impl.RoutingConfigurationImpl.deactivate ()
Definition at line 119 of file RoutingConfigurationImpl.java.
Set<ConnectPoint> org.onosproject.routing.config.impl.RoutingConfigurationImpl.getBgpPeerConnectPoints ()
Retrieves the entire set of connect points connected to BGP peers in the network.
Returns
the set of connect points connected to BGP peers
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 190 of file RoutingConfigurationImpl.java.
References org.onosproject.incubator.net.intf.InterfaceService.getMatchingInterface(), org.onosproject.routing.config.impl.RoutingConfigurationImpl.interfaceService, and org.onosproject.routing.RoutingService.ROUTER_APP_ID.
Map<IpAddress, BgpPeer> org.onosproject.routing.config.impl.RoutingConfigurationImpl.getBgpPeers ()
Gets the list of configured BGP peers.
Returns
the map from peer IP address to BgpPeer object
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 180 of file RoutingConfigurationImpl.java.
Map<String, BgpSpeaker> org.onosproject.routing.config.impl.RoutingConfigurationImpl.getBgpSpeakers ()
Gets the list of BGP speakers inside the SDN network.
Returns
the map of BGP speaker names to BGP speaker objects
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 175 of file RoutingConfigurationImpl.java.
Interface org.onosproject.routing.config.impl.RoutingConfigurationImpl.getInterface (ConnectPoint connectPoint)
Retrieves the interface associated with the given connect point.
Parameters
connectPoint the connect point to retrieve interface information for
Returns
the interface
Deprecated:
in Drake release - use InterfaceService instead
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 211 of file RoutingConfigurationImpl.java.
Interface org.onosproject.routing.config.impl.RoutingConfigurationImpl.getInterface (IpAddress ip)
Retrieves the interface associated with the given IP address.
Parameters
ip IP address of the interface
Returns
the interface
Deprecated:
in Drake release - use InterfaceService instead
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 216 of file RoutingConfigurationImpl.java.
Set<Interface> org.onosproject.routing.config.impl.RoutingConfigurationImpl.getInterfaces ()
Retrieves the entire set of interfaces in the network.
Returns
the set of interfaces
Deprecated:
in Drake release - use InterfaceService instead
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 185 of file RoutingConfigurationImpl.java.
Interface org.onosproject.routing.config.impl.RoutingConfigurationImpl.getMatchingInterface (IpAddress ipAddress)
Retrieves the interface that matches the given IP address.
Matching means that the IP address is in one of the interface's assigned subnets.
Parameters
ipAddress IP address to match
Returns
the matching interface
Deprecated:
in Drake release - use InterfaceService instead
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 221 of file RoutingConfigurationImpl.java.
MacAddress org.onosproject.routing.config.impl.RoutingConfigurationImpl.getVirtualGatewayMacAddress ()
Gets the MAC address configured for virtual gateway in SDN network.
Returns
the MAC address of virtual gateway
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 254 of file RoutingConfigurationImpl.java.
boolean org.onosproject.routing.config.impl.RoutingConfigurationImpl.isIpAddressLocal (IpAddress ipAddress)
Evaluates whether an IP address belongs to local SDN network.
Parameters
ipAddress the IP address to evaluate
Returns
true if the IP address belongs to local SDN network, otherwise false
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 226 of file RoutingConfigurationImpl.java.
References org.onlab.packet.Ip6Address.BIT_LENGTH, org.onlab.packet.Ip4Address.BIT_LENGTH, org.onlab.packet.IpAddress.isIp4(), and org.onlab.packet.IpPrefix.valueOf().
boolean org.onosproject.routing.config.impl.RoutingConfigurationImpl.isIpPrefixLocal (IpPrefix ipPrefix)
Evaluates whether an IP prefix belongs to local SDN network.
Parameters
ipPrefix the IP prefix to evaluate
Returns
true if the IP prefix belongs to local SDN network, otherwise false
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 241 of file RoutingConfigurationImpl.java.
boolean org.onosproject.routing.config.impl.RoutingConfigurationImpl.isVirtualGatewayIpAddress (IpAddress ipAddress)
Evaluates whether an IP address is a virtual gateway IP address.
Parameters
ipAddress the IP address to evaluate
Returns
true if the IP address is a virtual gateway address, otherwise false
Implements org.onosproject.routing.config.RoutingConfigurationService.
Definition at line 249 of file RoutingConfigurationImpl.java.
void org.onosproject.routing.config.impl.RoutingConfigurationImpl.readConfiguration ()
Instructs the configuration reader to read the configuration from the file.
Definition at line 170 of file RoutingConfigurationImpl.java.
Referenced by org.onosproject.routing.config.impl.RoutingConfigurationImpl.activate().
Member Data Documentation
NetworkConfigService org.onosproject.routing.config.impl.RoutingConfigurationImpl.configService protected
Definition at line 81 of file RoutingConfigurationImpl.java.
CoreService org.onosproject.routing.config.impl.RoutingConfigurationImpl.coreService protected
Definition at line 84 of file RoutingConfigurationImpl.java.
InterfaceService org.onosproject.routing.config.impl.RoutingConfigurationImpl.interfaceService protected
Definition at line 87 of file RoutingConfigurationImpl.java.
Referenced by org.onosproject.routing.config.impl.RoutingConfigurationImpl.getBgpPeerConnectPoints().
NetworkConfigRegistry org.onosproject.routing.config.impl.RoutingConfigurationImpl.registry protected
Definition at line 78 of file RoutingConfigurationImpl.java.
The documentation for this class was generated from the following file:
apps/routing/src/main/java/org/onosproject/routing/config/impl/RoutingConfigurationImpl.java