onos: org.onosproject.ui.topo.PropertyPanel Class Reference
org.onosproject.ui.topo.PropertyPanel Class Reference
Models a panel displayed on the Topology View.
Classes
class Prop
Simple data carrier for a property, composed of a key/value pair.
class Separator
Auxiliary class representing a separator property.
Public Member Functions
PropertyPanel (String title, String typeId)
Constructs a property panel model with the given title and type identifier (icon to display).
PropertyPanel id (String id)
Adds an ID field to the panel data, to be included in the returned JSON data to the client.
PropertyPanel addProp (String key, String value)
Adds a property to the panel data.
PropertyPanel addProp (String key, int value)
Adds a property to the panel data, using a decimal formatter.
PropertyPanel addProp (String key, long value)
Adds a property to the panel data, using a decimal formatter.
PropertyPanel addProp (String key, Object value)
Adds a property to the panel data.
PropertyPanel addProp (String key, Object value, String reStrip)
Adds a property to the panel data.
PropertyPanel addSeparator ()
Adds a separator to the panel data.
String title ()
Returns the title text.
String typeId ()
Returns the type identifier.
String id ()
Returns the internal ID.
List< Prop > properties ()
Returns the list of properties to be displayed.
List< ButtonId > buttons ()
Returns the list of button descriptors.
PropertyPanel title (String title)
Sets the title text.
PropertyPanel typeId (String typeId)
Sets the type identifier (icon ID).
PropertyPanel removeProps (String...keys)
Removes properties with the given keys from the list.
PropertyPanel removeAllProps ()
Removes all currently defined properties.
PropertyPanel addButton (ButtonId button)
Adds the given button descriptor to the panel data.
PropertyPanel removeButtons (ButtonId...descriptors)
Removes buttons with the given descriptors from the list.
PropertyPanel removeAllButtons ()
Removes all currently defined buttons.
Protected Member Functions
NumberFormat formatter ()
Returns a number formatter to use for formatting integer and long property values.
Detailed Description
Models a panel displayed on the Topology View.
Definition at line 29 of file PropertyPanel.java.
Constructor & Destructor Documentation
org.onosproject.ui.topo.PropertyPanel.PropertyPanel (String title, String typeId)
Constructs a property panel model with the given title and type identifier (icon to display).
Parameters
title title text
typeId type (icon) ID
Definition at line 46 of file PropertyPanel.java.
References org.onosproject.ui.topo.PropertyPanel.title(), and org.onosproject.ui.topo.PropertyPanel.typeId().
Member Function Documentation
PropertyPanel org.onosproject.ui.topo.PropertyPanel.addButton (ButtonId button)
Adds the given button descriptor to the panel data.
Parameters
button button descriptor
Returns
self, for chaining
Definition at line 263 of file PropertyPanel.java.
PropertyPanel org.onosproject.ui.topo.PropertyPanel.addProp (String key, String value)
Adds a property to the panel data.
Parameters
key property key
value property value
Returns
self, for chaining
Definition at line 88 of file PropertyPanel.java.
PropertyPanel org.onosproject.ui.topo.PropertyPanel.addProp (String key, int value)
Adds a property to the panel data, using a decimal formatter.
Parameters
key property key
value property value
Returns
self, for chaining
Definition at line 100 of file PropertyPanel.java.
References org.onosproject.ui.topo.PropertyPanel.formatter().
PropertyPanel org.onosproject.ui.topo.PropertyPanel.addProp (String key, long value)
Adds a property to the panel data, using a decimal formatter.
Parameters
key property key
value property value
Returns
self, for chaining
Definition at line 112 of file PropertyPanel.java.
References org.onosproject.ui.topo.PropertyPanel.formatter().
PropertyPanel org.onosproject.ui.topo.PropertyPanel.addProp (String key, Object value)
Adds a property to the panel data.
Note that the value's toString() method is used to convert the value to a string.
Parameters
key property key
value property value
Returns
self, for chaining
Definition at line 126 of file PropertyPanel.java.
PropertyPanel org.onosproject.ui.topo.PropertyPanel.addProp (String key, Object value, String reStrip)
Adds a property to the panel data.
Note that the value's toString() method is used to convert the value to a string, from which the characters defined in the given regular expression string are stripped.
Parameters
key property key
value property value
reStrip regexp characters to strip from value string
Returns
self, for chaining
Definition at line 142 of file PropertyPanel.java.
PropertyPanel org.onosproject.ui.topo.PropertyPanel.addSeparator ()
Adds a separator to the panel data.
Returns
self, for chaining
Definition at line 153 of file PropertyPanel.java.
List<ButtonId> org.onosproject.ui.topo.PropertyPanel.buttons ()
Returns the list of button descriptors.
Returns
the button list
Definition at line 201 of file PropertyPanel.java.
Referenced by org.onosproject.ui.topo.PropertyPanel.removeButtons().
NumberFormat org.onosproject.ui.topo.PropertyPanel.formatter () protected
Returns a number formatter to use for formatting integer and long property values.
This default implementation uses a formatter for the default locale. For example:
    Locale.ENGLISH  :  1000 -> "1,000"
    Locale.FRENCH   :  1000 -> "1 000"
    Locale.GERMAN   :  1000 -> "1.000"
Returns
the number formatter
Definition at line 65 of file PropertyPanel.java.
Referenced by org.onosproject.ui.topo.PropertyPanel.addProp().
PropertyPanel org.onosproject.ui.topo.PropertyPanel.id (String id)
Adds an ID field to the panel data, to be included in the returned JSON data to the client.
Parameters
id the identifier
Returns
self, for chaining
Definition at line 76 of file PropertyPanel.java.
References org.onosproject.ui.topo.PropertyPanel.id().
String org.onosproject.ui.topo.PropertyPanel.id ()
Returns the internal ID.
Returns
the ID
Definition at line 181 of file PropertyPanel.java.
Referenced by org.onosproject.ui.topo.PropertyPanel.id().
List<Prop> org.onosproject.ui.topo.PropertyPanel.properties ()
Returns the list of properties to be displayed.
Returns
the property list
Definition at line 191 of file PropertyPanel.java.
Referenced by org.onosproject.ui.topo.PropertyPanel.removeProps().
PropertyPanel org.onosproject.ui.topo.PropertyPanel.removeAllButtons ()
Removes all currently defined buttons.
Returns
self, for chaining
Definition at line 291 of file PropertyPanel.java.
PropertyPanel org.onosproject.ui.topo.PropertyPanel.removeAllProps ()
Removes all currently defined properties.
Returns
self, for chaining
Definition at line 252 of file PropertyPanel.java.
PropertyPanel org.onosproject.ui.topo.PropertyPanel.removeButtons (ButtonId... descriptors)
Removes buttons with the given descriptors from the list.
Parameters
descriptors descriptors to remove
Returns
self, for chaining
Definition at line 274 of file PropertyPanel.java.
References org.onosproject.ui.topo.PropertyPanel.buttons().
PropertyPanel org.onosproject.ui.topo.PropertyPanel.removeProps (String... keys)
Removes properties with the given keys from the list.
Parameters
keys keys of properties to remove
Returns
self, for chaining
Definition at line 235 of file PropertyPanel.java.
References org.onosproject.ui.topo.PropertyPanel.properties().
String org.onosproject.ui.topo.PropertyPanel.title ()
Returns the title text.
Returns
title text
Definition at line 163 of file PropertyPanel.java.
Referenced by org.onosproject.ui.topo.PropertyPanel.PropertyPanel(), and org.onosproject.ui.topo.PropertyPanel.title().
PropertyPanel org.onosproject.ui.topo.PropertyPanel.title (String title)
Sets the title text.
Parameters
title title text
Returns
self, for chaining
Definition at line 213 of file PropertyPanel.java.
References org.onosproject.ui.topo.PropertyPanel.title().
String org.onosproject.ui.topo.PropertyPanel.typeId ()
Returns the type identifier.
Returns
type identifier
Definition at line 172 of file PropertyPanel.java.
Referenced by org.onosproject.ui.topo.PropertyPanel.PropertyPanel(), and org.onosproject.ui.topo.PropertyPanel.typeId().
PropertyPanel org.onosproject.ui.topo.PropertyPanel.typeId (String typeId)
Sets the type identifier (icon ID).
Parameters
typeId type identifier
Returns
self, for chaining
Definition at line 224 of file PropertyPanel.java.
References org.onosproject.ui.topo.PropertyPanel.typeId().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/topo/PropertyPanel.java