onos: org.onosproject.net.behaviour.BridgeName Class Reference
org.onosproject.net.behaviour.BridgeName Class Reference
Represents for a bridge name.
Public Member Functions
String name ()
Returns the bridge name string.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static BridgeName bridgeName (String name)
Creates a bridge name using the supplied string.
Detailed Description
Represents for a bridge name.
Definition at line 25 of file BridgeName.java.
Member Function Documentation
static BridgeName org.onosproject.net.behaviour.BridgeName.bridgeName (String name) static
Creates a bridge name using the supplied string.
Parameters
name bridge name
Returns
BridgeName
Definition at line 40 of file BridgeName.java.
Referenced by org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getBridges().
boolean org.onosproject.net.behaviour.BridgeName.equals (Object obj)
Definition at line 59 of file BridgeName.java.
References create-flow.name.
int org.onosproject.net.behaviour.BridgeName.hashCode ()
Definition at line 54 of file BridgeName.java.
String org.onosproject.net.behaviour.BridgeName.name ()
Returns the bridge name string.
Returns
name string
Definition at line 49 of file BridgeName.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.net.behaviour.BridgeName.toString ()
Definition at line 72 of file BridgeName.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/behaviour/BridgeName.java