onos: org.onosproject.bgp.controller.impl.AdjRibIn Class Reference
org.onosproject.bgp.controller.impl.AdjRibIn Class Reference
Implementation of Adj-RIB-In for each peer.
Public Member Functions
Map< BgpNodeLSIdentifier,
PathAttrNlriDetails > nodeTree ()
Returns the adjacency node.
Map< BgpLinkLSIdentifier,
PathAttrNlriDetails > linkTree ()
Returns the adjacency link.
Map< BgpPrefixLSIdentifier,
PathAttrNlriDetails > prefixTree ()
Returns the adjacency prefix.
void add (BgpLSNlri nlri, PathAttrNlriDetails details)
Update nlri identifier into the tree if nlri identifier exists in tree otherwise add this to the tree.
void remove (BgpLSNlri nlri)
Removes nlri identifier if it exists in the adjacency tree.
String toString ()
Detailed Description
Implementation of Adj-RIB-In for each peer.
Definition at line 36 of file AdjRibIn.java.
Member Function Documentation
void org.onosproject.bgp.controller.impl.AdjRibIn.add (BgpLSNlri nlri, PathAttrNlriDetails details)
Update nlri identifier into the tree if nlri identifier exists in tree otherwise add this to the tree.
Parameters
nlri NLRI Info
details has pathattribute , protocolID and identifier
Definition at line 74 of file AdjRibIn.java.
References org.onosproject.bgp.controller.impl.AdjRibIn.linkTree(), org.onosproject.bgp.controller.impl.AdjRibIn.nodeTree(), and org.onosproject.bgp.controller.impl.AdjRibIn.prefixTree().
Referenced by org.onosproject.bgp.controller.impl.AdjRibIn.toString().
Map<BgpLinkLSIdentifier, PathAttrNlriDetails> org.onosproject.bgp.controller.impl.AdjRibIn.linkTree ()
Returns the adjacency link.
Returns
link adjacency RIB node
Definition at line 55 of file AdjRibIn.java.
Referenced by org.onosproject.bgp.controller.impl.AdjRibIn.add(), org.onosproject.bgp.controller.impl.AdjRibIn.remove(), and org.onosproject.bgp.controller.impl.AdjRibIn.toString().
Map<BgpNodeLSIdentifier, PathAttrNlriDetails> org.onosproject.bgp.controller.impl.AdjRibIn.nodeTree ()
Returns the adjacency node.
Returns
node adjacency RIB node
Definition at line 46 of file AdjRibIn.java.
Referenced by org.onosproject.bgp.controller.impl.AdjRibIn.add(), org.onosproject.bgp.controller.impl.AdjRibIn.remove(), and org.onosproject.bgp.controller.impl.AdjRibIn.toString().
Map<BgpPrefixLSIdentifier, PathAttrNlriDetails> org.onosproject.bgp.controller.impl.AdjRibIn.prefixTree ()
Returns the adjacency prefix.
Returns
prefix adjacency RIB node
Definition at line 64 of file AdjRibIn.java.
Referenced by org.onosproject.bgp.controller.impl.AdjRibIn.add(), org.onosproject.bgp.controller.impl.AdjRibIn.remove(), and org.onosproject.bgp.controller.impl.AdjRibIn.toString().
void org.onosproject.bgp.controller.impl.AdjRibIn.remove (BgpLSNlri nlri)
Removes nlri identifier if it exists in the adjacency tree.
Parameters
nlri NLRI Info
Definition at line 104 of file AdjRibIn.java.
References org.onosproject.bgp.controller.impl.AdjRibIn.linkTree(), org.onosproject.bgp.controller.impl.AdjRibIn.nodeTree(), and org.onosproject.bgp.controller.impl.AdjRibIn.prefixTree().
String org.onosproject.bgp.controller.impl.AdjRibIn.toString ()
Definition at line 124 of file AdjRibIn.java.
References org.onosproject.bgp.controller.impl.AdjRibIn.add(), org.onosproject.bgp.controller.impl.AdjRibIn.linkTree(), org.onosproject.bgp.controller.impl.AdjRibIn.nodeTree(), and org.onosproject.bgp.controller.impl.AdjRibIn.prefixTree().
The documentation for this class was generated from the following file:
bgp/ctl/src/main/java/org/onosproject/bgp/controller/impl/AdjRibIn.java