onos: org.onosproject.store.ecmap.MapValue< V > Class Reference
org.onosproject.store.ecmap.MapValue< V > Class Reference
Representation of a value in EventuallyConsistentMap.
Classes
class Digest
Digest or summary of a MapValue for use during Anti-Entropy exchanges.
Public Member Functions
MapValue (V value, Timestamp timestamp)
boolean isTombstone ()
boolean isAlive ()
Timestamp timestamp ()
V get ()
int compareTo (MapValue< V > o)
boolean isNewerThan (MapValue< V > other)
boolean isNewerThan (Timestamp timestamp)
Digest digest ()
int hashCode ()
boolean equals (Object other)
String toString ()
Static Public Member Functions
static< U > MapValue< U > tombstone (Timestamp timestamp)
Creates a tombstone value with the specified timestamp.
Detailed Description
Representation of a value in EventuallyConsistentMap.
Parameters
<V> value type
Definition at line 28 of file MapValue.java.
Constructor & Destructor Documentation
org.onosproject.store.ecmap.MapValue< V >.MapValue (V value, Timestamp timestamp)
Definition at line 43 of file MapValue.java.
Member Function Documentation
int org.onosproject.store.ecmap.MapValue< V >.compareTo (MapValue< V > o)
Definition at line 65 of file MapValue.java.
Digest org.onosproject.store.ecmap.MapValue< V >.digest ()
Definition at line 77 of file MapValue.java.
boolean org.onosproject.store.ecmap.MapValue< V >.equals (Object other)
Definition at line 88 of file MapValue.java.
V org.onosproject.store.ecmap.MapValue< V >.get ()
Definition at line 60 of file MapValue.java.
Referenced by org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.get().
int org.onosproject.store.ecmap.MapValue< V >.hashCode ()
Definition at line 82 of file MapValue.java.
boolean org.onosproject.store.ecmap.MapValue< V >.isAlive ()
Definition at line 52 of file MapValue.java.
boolean org.onosproject.store.ecmap.MapValue< V >.isNewerThan (MapValue< V > other)
Definition at line 69 of file MapValue.java.
Referenced by org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.compute().
boolean org.onosproject.store.ecmap.MapValue< V >.isNewerThan (Timestamp timestamp)
Definition at line 73 of file MapValue.java.
boolean org.onosproject.store.ecmap.MapValue< V >.isTombstone ()
Definition at line 48 of file MapValue.java.
Referenced by org.onosproject.store.ecmap.EventuallyConsistentMapImpl< K, V >.get().
Timestamp org.onosproject.store.ecmap.MapValue< V >.timestamp ()
Definition at line 56 of file MapValue.java.
static <U> MapValue<U> org.onosproject.store.ecmap.MapValue< V >.tombstone (Timestamp timestamp) static
Creates a tombstone value with the specified timestamp.
Parameters
timestamp timestamp for tombstone
Returns
tombstone MapValue
Parameters
<U> value type
Definition at line 39 of file MapValue.java.
String org.onosproject.store.ecmap.MapValue< V >.toString ()
Definition at line 98 of file MapValue.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/ecmap/MapValue.java