onos: org.onosproject.bgpio.util.Validation Class Reference
org.onosproject.bgpio.util.Validation Class Reference
Provides methods to parse attribute header, validate length and type.
Public Member Functions
boolean getFirstBit ()
Returns first bit in type flags.
boolean getSecondBit ()
Returns second bit in type flags.
boolean getThirdBit ()
Returns third bit in type flags.
boolean getFourthBit ()
Returns fourth bit in type flags.
int getLength ()
Returns attribute length.
boolean isShort ()
Returns whether attribute length read in short or byte.
Static Public Member Functions
static Validation parseAttributeHeader (ChannelBuffer cb)
Parses attribute Header.
static void validateLen (byte errorCode, byte subErrCode, int length) throws BgpParseException
Throws exception if length is not correct.
static void validateType (byte errorCode, byte subErrCode, int type) throws BgpParseException
Throws exception if type is not correct.
static InetAddress toInetAddress (int length, ChannelBuffer cb)
Convert byte array to InetAddress.
static IpPrefix bytesToPrefix (byte[] value, int length)
Converts byte array of prefix value to IpPrefix object.
Static Public Attributes
static final byte FIRST_BIT = (byte) 0x80
static final byte SECOND_BIT = 0x40
static final byte THIRD_BIT = 0x20
static final byte FOURTH_BIT = (byte) 0x10
static final byte IPV4_SIZE = 4
Detailed Description
Provides methods to parse attribute header, validate length and type.
Definition at line 36 of file Validation.java.
Member Function Documentation
static IpPrefix org.onosproject.bgpio.util.Validation.bytesToPrefix (byte[] value, int length) static
Converts byte array of prefix value to IpPrefix object.
Parameters
value byte array of prefix value
length prefix length in bits
Returns
object of IpPrefix
Definition at line 216 of file Validation.java.
References org.onosproject.bgpio.util.Validation.IPV4_SIZE, and find-link-in-cluster.length.
boolean org.onosproject.bgpio.util.Validation.getFirstBit ()
Returns first bit in type flags.
Returns
first bit in type flags
Definition at line 160 of file Validation.java.
Referenced by org.onosproject.bgpio.types.LinkStateAttributes.read().
boolean org.onosproject.bgpio.util.Validation.getFourthBit ()
Returns fourth bit in type flags.
Returns
fourth bit in type flags
Definition at line 187 of file Validation.java.
int org.onosproject.bgpio.util.Validation.getLength ()
Returns attribute length.
Returns
attribute length
Definition at line 196 of file Validation.java.
Referenced by org.onosproject.bgpio.types.MpUnReachNlri.read(), org.onosproject.bgpio.types.Origin.read(), org.onosproject.bgpio.types.MpReachNlri.read(), and org.onosproject.bgpio.types.LinkStateAttributes.read().
boolean org.onosproject.bgpio.util.Validation.getSecondBit ()
Returns second bit in type flags.
Returns
second bit in type flags
Definition at line 169 of file Validation.java.
boolean org.onosproject.bgpio.util.Validation.getThirdBit ()
Returns third bit in type flags.
Returns
third bit in type flags
Definition at line 178 of file Validation.java.
Referenced by org.onosproject.bgpio.types.LinkStateAttributes.read().
boolean org.onosproject.bgpio.util.Validation.isShort ()
Returns whether attribute length read in short or byte.
Returns
whether attribute length read in short or byte
Definition at line 205 of file Validation.java.
Referenced by org.onosproject.bgpio.util.Validation.parseAttributeHeader().
static Validation org.onosproject.bgpio.util.Validation.parseAttributeHeader (ChannelBuffer cb) static
Parses attribute Header.
Parameters
cb ChannelBuffer
Returns
object of Validation
Definition at line 75 of file Validation.java.
References org.onosproject.bgpio.util.Validation.FIRST_BIT, org.onosproject.bgpio.util.Validation.FOURTH_BIT, org.onosproject.bgpio.util.Validation.isShort(), find-link-in-cluster.length, org.onosproject.bgpio.util.Validation.SECOND_BIT, and org.onosproject.bgpio.util.Validation.THIRD_BIT.
static InetAddress org.onosproject.bgpio.util.Validation.toInetAddress (int length, ChannelBuffer cb) static
Convert byte array to InetAddress.
Parameters
length of IpAddress
cb channelBuffer
Returns
InetAddress
Definition at line 143 of file Validation.java.
References find-link-in-cluster.length.
static void org.onosproject.bgpio.util.Validation.validateLen (byte errorCode, byte subErrCode, int length) throws BgpParseException static
Throws exception if length is not correct.
Parameters
errorCode Error code
subErrCode Sub Error Code
length erroneous length
Exceptions
BgpParseException for erroneous length
Definition at line 114 of file Validation.java.
References find-link-in-cluster.length.
static void org.onosproject.bgpio.util.Validation.validateType (byte errorCode, byte subErrCode, int type) throws BgpParseException static
Throws exception if type is not correct.
Parameters
errorCode Error code
subErrCode Sub Error Code
type erroneous type
Exceptions
BgpParseException for erroneous type
Definition at line 129 of file Validation.java.
Member Data Documentation
final byte org.onosproject.bgpio.util.Validation.FIRST_BIT = (byte) 0x80 static
Definition at line 38 of file Validation.java.
Referenced by org.onosproject.bgpio.util.Validation.parseAttributeHeader().
final byte org.onosproject.bgpio.util.Validation.FOURTH_BIT = (byte) 0x10 static
Definition at line 41 of file Validation.java.
Referenced by org.onosproject.bgpio.util.Validation.parseAttributeHeader().
final byte org.onosproject.bgpio.util.Validation.IPV4_SIZE = 4 static
Definition at line 42 of file Validation.java.
Referenced by org.onosproject.bgpio.util.Validation.bytesToPrefix().
final byte org.onosproject.bgpio.util.Validation.SECOND_BIT = 0x40 static
Definition at line 39 of file Validation.java.
Referenced by org.onosproject.bgpio.util.Validation.parseAttributeHeader().
final byte org.onosproject.bgpio.util.Validation.THIRD_BIT = 0x20 static
Definition at line 40 of file Validation.java.
Referenced by org.onosproject.bgpio.util.Validation.parseAttributeHeader().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/util/Validation.java