onos: org.onosproject.driver.extensions.NiciraSetTunnelDst Class Reference
org.onosproject.driver.extensions.NiciraSetTunnelDst Class Reference
Nicira set tunnel destination extension instruction.
Public Member Functions
Ip4Address tunnelDst ()
Gets the tunnel destination IPv4 address.
ExtensionTreatmentType type ()
Gets the type of the extension instruction.
void deserialize (byte[] data)
Deserialize the extension instruction from a byte array.
byte[] serialize ()
Serialize the extension instruction to a byte array.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.flow.instructions.AbstractExtensionTreatment
List< String > getProperties ()
Gets a list of all properties on the extension instruction.
Detailed Description
Nicira set tunnel destination extension instruction.
Definition at line 33 of file NiciraSetTunnelDst.java.
Member Function Documentation
void org.onosproject.driver.extensions.NiciraSetTunnelDst.deserialize (byte[] data)
Deserialize the extension instruction from a byte array.
The properties of this object will be overwritten with the data in the byte array.
Parameters
data input byte array
Implements org.onosproject.net.flow.instructions.ExtensionTreatment.
Definition at line 75 of file NiciraSetTunnelDst.java.
boolean org.onosproject.driver.extensions.NiciraSetTunnelDst.equals (Object obj)
Definition at line 90 of file NiciraSetTunnelDst.java.
References org.onosproject.driver.extensions.NiciraSetTunnelDst.tunnelDst().
int org.onosproject.driver.extensions.NiciraSetTunnelDst.hashCode ()
Definition at line 85 of file NiciraSetTunnelDst.java.
References org.onosproject.driver.extensions.NiciraSetTunnelDst.tunnelDst().
byte [] org.onosproject.driver.extensions.NiciraSetTunnelDst.serialize ()
Serialize the extension instruction to a byte array.
Returns
byte array
Implements org.onosproject.net.flow.instructions.ExtensionTreatment.
Definition at line 80 of file NiciraSetTunnelDst.java.
References org.onosproject.driver.extensions.NiciraSetTunnelDst.tunnelDst().
String org.onosproject.driver.extensions.NiciraSetTunnelDst.toString ()
Definition at line 103 of file NiciraSetTunnelDst.java.
Ip4Address org.onosproject.driver.extensions.NiciraSetTunnelDst.tunnelDst ()
Gets the tunnel destination IPv4 address.
Returns
tunnel destination IPv4 address
Definition at line 65 of file NiciraSetTunnelDst.java.
Referenced by org.onosproject.driver.extensions.NiciraSetTunnelDst.equals(), org.onosproject.driver.extensions.NiciraSetTunnelDst.hashCode(), and org.onosproject.driver.extensions.NiciraSetTunnelDst.serialize().
ExtensionTreatmentType org.onosproject.driver.extensions.NiciraSetTunnelDst.type ()
Gets the type of the extension instruction.
Returns
type
Implements org.onosproject.net.flow.instructions.ExtensionTreatment.
Definition at line 70 of file NiciraSetTunnelDst.java.
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/extensions/NiciraSetTunnelDst.java