onos: org.onlab.packet.ndp.NeighborSolicitation Class Reference
org.onlab.packet.ndp.NeighborSolicitation Class Reference
Implements ICMPv6 Neighbor Solicitation packet format.
Public Member Functions
byte[] getTargetAddress ()
Gets target address.
NeighborSolicitation setTargetAddress (final byte[] targetAddress)
Sets target address.
List
< NeighborDiscoveryOptions.Option > getOptions ()
Gets the Neighbor Discovery Protocol packet options.
NeighborSolicitation addOption (final byte type, final byte[] data)
Adds a Neighbor Discovery Protocol packet option.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer
< NeighborSolicitation > deserializer ()
Deserializer function for neighbor solicitation packets.
Static Public Attributes
static final byte HEADER_LENGTH = 20
Protected Attributes
byte[] targetAddress = new byte[Ip6Address.BYTE_LENGTH]
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements ICMPv6 Neighbor Solicitation packet format.
(RFC 4861)
Definition at line 32 of file NeighborSolicitation.java.
Member Function Documentation
NeighborSolicitation org.onlab.packet.ndp.NeighborSolicitation.addOption (final byte type, final byte[] data)
Adds a Neighbor Discovery Protocol packet option.
Parameters
type the option type
data the option data
Returns
this
Definition at line 77 of file NeighborSolicitation.java.
IPacket org.onlab.packet.ndp.NeighborSolicitation.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 108 of file NeighborSolicitation.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, and find-link-in-cluster.length.
Referenced by org.onlab.packet.ndp.NeighborSolicitation.deserializer().
static Deserializer<NeighborSolicitation> org.onlab.packet.ndp.NeighborSolicitation.deserializer () static
Deserializer function for neighbor solicitation packets.
Returns
deserializer function
Definition at line 169 of file NeighborSolicitation.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, org.onlab.packet.ndp.NeighborSolicitation.deserialize(), org.onlab.packet.ndp.NeighborSolicitation.HEADER_LENGTH, and find-link-in-cluster.length.
boolean org.onlab.packet.ndp.NeighborSolicitation.equals (final Object obj)
Definition at line 144 of file NeighborSolicitation.java.
References org.onlab.packet.ndp.NeighborDiscoveryOptions.equals(), and org.onlab.packet.ndp.NeighborSolicitation.targetAddress.
Referenced by org.onlab.packet.ndp.NeighborSolicitationTest.testEqual().
List<NeighborDiscoveryOptions.Option> org.onlab.packet.ndp.NeighborSolicitation.getOptions ()
Gets the Neighbor Discovery Protocol packet options.
Returns
the Neighbor Discovery Protocol packet options
Definition at line 66 of file NeighborSolicitation.java.
Referenced by org.onlab.packet.ndp.NeighborSolicitationTest.testDeserialize().
byte [] org.onlab.packet.ndp.NeighborSolicitation.getTargetAddress ()
Gets target address.
Returns
the target IPv6 address
Definition at line 45 of file NeighborSolicitation.java.
Referenced by org.onlab.packet.ndp.NeighborSolicitationTest.testDeserialize().
int org.onlab.packet.ndp.NeighborSolicitation.hashCode ()
Definition at line 126 of file NeighborSolicitation.java.
byte [] org.onlab.packet.ndp.NeighborSolicitation.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 84 of file NeighborSolicitation.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, org.onlab.packet.ndp.NeighborDiscoveryOptions.hasOptions(), org.onlab.packet.ndp.NeighborSolicitation.HEADER_LENGTH, and find-link-in-cluster.length.
Referenced by org.onlab.packet.ndp.NeighborSolicitationTest.testSerialize().
NeighborSolicitation org.onlab.packet.ndp.NeighborSolicitation.setTargetAddress (final byte[] targetAddress)
Sets target address.
Parameters
targetAddress the target IPv6 address to set
Returns
this
Definition at line 55 of file NeighborSolicitation.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, and org.onlab.packet.ndp.NeighborSolicitation.targetAddress.
Member Data Documentation
final byte org.onlab.packet.ndp.NeighborSolicitation.HEADER_LENGTH = 20 static
Definition at line 33 of file NeighborSolicitation.java.
Referenced by org.onlab.packet.ndp.NeighborSolicitation.deserializer(), org.onlab.packet.ndp.NeighborSolicitation.serialize(), and org.onlab.packet.ndp.NeighborSolicitationTest.testDeserializeTruncated().
byte [] org.onlab.packet.ndp.NeighborSolicitation.targetAddress = new byte[Ip6Address.BYTE_LENGTH] protected
Definition at line 35 of file NeighborSolicitation.java.
Referenced by org.onlab.packet.ndp.NeighborSolicitation.equals(), and org.onlab.packet.ndp.NeighborSolicitation.setTargetAddress().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ndp/NeighborSolicitation.java