onos: org.onosproject.routing.FibUpdate Class Reference
org.onosproject.routing.FibUpdate Class Reference
Represents a change to the Forwarding Information Base (FIB).
Classes
enum Type
Specifies the type of the FIB update.
Public Member Functions
FibUpdate (Type type, FibEntry entry)
Creates a new FIB update.
Type type ()
Returns the type of the update.
FibEntry entry ()
Returns the FIB entry which contains update information.
boolean equals (Object o)
int hashCode ()
String toString ()
Detailed Description
Represents a change to the Forwarding Information Base (FIB).
Definition at line 25 of file FibUpdate.java.
Constructor & Destructor Documentation
org.onosproject.routing.FibUpdate.FibUpdate (Type type, FibEntry entry)
Creates a new FIB update.
Parameters
type type of the update
entry FIB entry describing the update
Definition at line 51 of file FibUpdate.java.
References org.onosproject.routing.FibUpdate.entry(), and org.onosproject.routing.FibUpdate.type().
Referenced by org.onosproject.routing.FibUpdate.equals().
Member Function Documentation
FibEntry org.onosproject.routing.FibUpdate.entry ()
Returns the FIB entry which contains update information.
Returns
the FIB entry
Definition at line 70 of file FibUpdate.java.
Referenced by org.onosproject.routing.FibUpdate.FibUpdate(), org.onosproject.routing.FibUpdate.hashCode(), and org.onosproject.routing.FibUpdate.toString().
boolean org.onosproject.routing.FibUpdate.equals (Object o)
Definition at line 75 of file FibUpdate.java.
References org.onosproject.routing.FibUpdate.FibUpdate().
int org.onosproject.routing.FibUpdate.hashCode ()
Definition at line 87 of file FibUpdate.java.
References org.onosproject.routing.FibUpdate.entry(), and org.onosproject.routing.FibUpdate.type().
String org.onosproject.routing.FibUpdate.toString ()
Definition at line 92 of file FibUpdate.java.
References org.onosproject.routing.FibUpdate.entry(), and org.onosproject.routing.FibUpdate.type().
Type org.onosproject.routing.FibUpdate.type ()
Returns the type of the update.
Returns
update type
Definition at line 61 of file FibUpdate.java.
Referenced by org.onosproject.routing.FibUpdate.FibUpdate(), org.onosproject.routing.FibUpdate.hashCode(), and org.onosproject.routing.FibUpdate.toString().
The documentation for this class was generated from the following file:
apps/routing-api/src/main/java/org/onosproject/routing/FibUpdate.java