onos: org.onlab.stc.MonitorWebSocket Class Reference
org.onlab.stc.MonitorWebSocket Class Reference
Web socket capable of interacting with the STC monitor GUI.
Public Member Functions
void onOpen (Connection connection)
synchronized void onClose (int closeCode, String message)
boolean onControl (byte controlCode, byte[] data, int offset, int length)
void onMessage (String data)
synchronized void sendMessage (ObjectNode message)
ObjectNode message (String type, ObjectNode payload)
Detailed Description
Web socket capable of interacting with the STC monitor GUI.
Definition at line 29 of file MonitorWebSocket.java.
Member Function Documentation
ObjectNode org.onlab.stc.MonitorWebSocket.message (String type, ObjectNode payload)
Definition at line 134 of file MonitorWebSocket.java.
Referenced by org.onlab.stc.MonitorWebSocket.onMessage(), and org.onlab.stc.MonitorWebSocket.onOpen().
synchronized void org.onlab.stc.MonitorWebSocket.onClose (int closeCode, String message)
Definition at line 102 of file MonitorWebSocket.java.
boolean org.onlab.stc.MonitorWebSocket.onControl (byte controlCode, byte[] data, int offset, int length)
Definition at line 107 of file MonitorWebSocket.java.
void org.onlab.stc.MonitorWebSocket.onMessage (String data)
Definition at line 113 of file MonitorWebSocket.java.
References org.onlab.stc.MonitorWebSocket.message().
void org.onlab.stc.MonitorWebSocket.onOpen (Connection connection)
Definition at line 86 of file MonitorWebSocket.java.
References org.onlab.stc.MonitorWebSocket.message(), and org.onlab.stc.MonitorWebSocket.sendMessage().
synchronized void org.onlab.stc.MonitorWebSocket.sendMessage (ObjectNode message)
Definition at line 124 of file MonitorWebSocket.java.
Referenced by org.onlab.stc.MonitorWebSocket.onOpen().
The documentation for this class was generated from the following file:
utils/stc/src/main/java/org/onlab/stc/MonitorWebSocket.java