onos: org.onosproject.bgprouter.NextHopGroupKey Class Reference
org.onosproject.bgprouter.NextHopGroupKey Class Reference
Identifier for a next hop group.
Public Member Functions
NextHopGroupKey (IpAddress address)
Creates a new next hop group key.
IpAddress address ()
Returns the next hop's IP address.
boolean equals (Object o)
int hashCode ()
String toString ()
Detailed Description
Identifier for a next hop group.
Definition at line 29 of file NextHopGroupKey.java.
Constructor & Destructor Documentation
org.onosproject.bgprouter.NextHopGroupKey.NextHopGroupKey (IpAddress address)
Creates a new next hop group key.
Parameters
address next hop's IP address
Definition at line 38 of file NextHopGroupKey.java.
Referenced by org.onosproject.bgprouter.NextHopGroupKey.equals().
Member Function Documentation
IpAddress org.onosproject.bgprouter.NextHopGroupKey.address ()
Returns the next hop's IP address.
Returns
next hop's IP address
Definition at line 47 of file NextHopGroupKey.java.
Referenced by org.onosproject.bgprouter.NextHopGroupKey.toString().
boolean org.onosproject.bgprouter.NextHopGroupKey.equals (Object o)
Definition at line 52 of file NextHopGroupKey.java.
References org.onosproject.bgprouter.NextHopGroupKey.NextHopGroupKey().
int org.onosproject.bgprouter.NextHopGroupKey.hashCode ()
Definition at line 63 of file NextHopGroupKey.java.
String org.onosproject.bgprouter.NextHopGroupKey.toString ()
Definition at line 68 of file NextHopGroupKey.java.
References org.onosproject.bgprouter.NextHopGroupKey.address().
The documentation for this class was generated from the following file:
apps/bgprouter/src/main/java/org/onosproject/bgprouter/NextHopGroupKey.java