onos: org.onosproject.bgpio.types.As4Path Class Reference
org.onosproject.bgpio.types.As4Path Class Reference
Provides Implementation of As4Path BGP Path Attribute.
Public Member Functions
As4Path ()
Initialize fields.
As4Path (List< Integer > as4pathSet, List< Integer > as4pathSeq)
Constructor to initialize parameters.
short getType ()
Returns the Type of BGP Message.
List< Integer > as4PathSEQ ()
Returns list of ASNum in AS4path Sequence.
List< Integer > as4PathSET ()
Returns list of ASNum in AS4path Set.
int hashCode ()
boolean equals (Object obj)
String toString ()
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static As4Path read (ChannelBuffer cb) throws BgpParseException
Reads from the channel buffer and parses As4Path.
Static Public Attributes
static final byte AS4PATH_TYPE = 17
static final byte ASNUM_SIZE = 4
Detailed Description
Provides Implementation of As4Path BGP Path Attribute.
Definition at line 34 of file As4Path.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.As4Path.As4Path ()
Initialize fields.
Definition at line 45 of file As4Path.java.
Referenced by org.onosproject.bgpio.types.As4Path.equals(), and org.onosproject.bgpio.types.As4Path.read().
org.onosproject.bgpio.types.As4Path.As4Path (List< Integer > as4pathSet, List< Integer > as4pathSeq)
Constructor to initialize parameters.
Parameters
as4pathSet AS4path Set
as4pathSeq AS4path Sequence
Definition at line 56 of file As4Path.java.
Member Function Documentation
List<Integer> org.onosproject.bgpio.types.As4Path.as4PathSEQ ()
Returns list of ASNum in AS4path Sequence.
Returns
list of ASNum in AS4path Sequence
Definition at line 125 of file As4Path.java.
List<Integer> org.onosproject.bgpio.types.As4Path.as4PathSET ()
Returns list of ASNum in AS4path Set.
Returns
list of ASNum in AS4path Set
Definition at line 134 of file As4Path.java.
int org.onosproject.bgpio.types.As4Path.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 171 of file As4Path.java.
boolean org.onosproject.bgpio.types.As4Path.equals (Object obj)
Definition at line 144 of file As4Path.java.
References org.onosproject.bgpio.types.As4Path.As4Path().
short org.onosproject.bgpio.types.As4Path.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 116 of file As4Path.java.
References org.onosproject.bgpio.types.As4Path.AS4PATH_TYPE.
int org.onosproject.bgpio.types.As4Path.hashCode ()
Definition at line 139 of file As4Path.java.
static As4Path org.onosproject.bgpio.types.As4Path.read (ChannelBuffer cb) throws BgpParseException static
Reads from the channel buffer and parses As4Path.
Parameters
cb ChannelBuffer
Returns
object of As4Path
Exceptions
BgpParseException while parsing As4Path
Definition at line 68 of file As4Path.java.
References org.onosproject.bgpio.types.As4Path.As4Path(), org.onosproject.bgpio.types.As4Path.ASNUM_SIZE, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_FLAGS_ERROR, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, find-link-in-cluster.length, org.onosproject.bgpio.util.Constants.TYPE_AND_LEN_AS_BYTE, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.As4Path.toString ()
Definition at line 156 of file As4Path.java.
int org.onosproject.bgpio.types.As4Path.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 165 of file As4Path.java.
Member Data Documentation
final byte org.onosproject.bgpio.types.As4Path.AS4PATH_TYPE = 17 static
Definition at line 36 of file As4Path.java.
Referenced by org.onosproject.bgpio.types.As4Path.getType().
final byte org.onosproject.bgpio.types.As4Path.ASNUM_SIZE = 4 static
Definition at line 37 of file As4Path.java.
Referenced by org.onosproject.bgpio.types.As4Path.read().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/As4Path.java