onos: org.onosproject.pcepio.types.PcepObjectHeader Class Reference
org.onosproject.pcepio.types.PcepObjectHeader Class Reference
Provides PCEP Object Header which is common for all the objects.
Public Member Functions
PcepObjectHeader (byte objClass, byte objType, boolean bPFlag, boolean bIFlag, short objLen)
Constructor to initialize all the variables in object header.
void setObjClass (byte value)
Sets the Object class.
void setObjType (byte value)
Sets the Object TYPE.
void setPFlag (boolean value)
Sets the Object P flag.
void setIFlag (boolean value)
Sets the Object I flag.
void setObjLen (short value)
Sets the Object Length.
boolean getPFlag ()
Returns Object's P flag.
boolean getIFlag ()
Returns Object's i flag.
short getObjLen ()
Returns Object Length.
byte getObjClass ()
Returns Object class.
byte getObjType ()
Returns Object Type.
int write (ChannelBuffer cb)
Writes Byte stream of PCEP object header to channel buffer.
String toString ()
Static Public Member Functions
static PcepObjectHeader read (ChannelBuffer cb)
Read from channel buffer and Returns PCEP Objects header.
Static Public Attributes
static final boolean REQ_OBJ_MUST_PROCESS = true
static final boolean REQ_OBJ_OPTIONAL_PROCESS = false
static final boolean RSP_OBJ_IGNORED = true
static final boolean RSP_OBJ_PROCESSED = false
static final int OBJECT_TYPE_SHIFT_VALUE = 4
static final byte PFLAG_SET = 0x02
static final byte IFLAG_SET = 0x01
static final int SET = 1
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepObjectHeader.class)
Detailed Description
Provides PCEP Object Header which is common for all the objects.
Reference : RFC 5440.
Definition at line 30 of file PcepObjectHeader.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PcepObjectHeader.PcepObjectHeader (byte objClass, byte objType, boolean bPFlag, boolean bIFlag, short objLen)
Constructor to initialize all the variables in object header.
Parameters
objClass PCEP Object class
objType PCEP Object type
bPFlag P flag
bIFlag I flag
objLen PCEP object length
Definition at line 72 of file PcepObjectHeader.java.
Referenced by org.onosproject.pcepio.types.PcepObjectHeader.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.PcepObjectHeader.getIFlag ()
Returns Object's i flag.
Returns
bIFlag I flag
Definition at line 139 of file PcepObjectHeader.java.
byte org.onosproject.pcepio.types.PcepObjectHeader.getObjClass ()
Returns Object class.
Returns
objClass object class
Definition at line 157 of file PcepObjectHeader.java.
short org.onosproject.pcepio.types.PcepObjectHeader.getObjLen ()
Returns Object Length.
Returns
objLen object length
Definition at line 148 of file PcepObjectHeader.java.
byte org.onosproject.pcepio.types.PcepObjectHeader.getObjType ()
Returns Object Type.
Returns
objType object type
Definition at line 166 of file PcepObjectHeader.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepEndPointsObjectVer1.read().
boolean org.onosproject.pcepio.types.PcepObjectHeader.getPFlag ()
Returns Object's P flag.
Returns
bPFlag P flag
Definition at line 130 of file PcepObjectHeader.java.
static PcepObjectHeader org.onosproject.pcepio.types.PcepObjectHeader.read (ChannelBuffer cb) static
Read from channel buffer and Returns PCEP Objects header.
Parameters
cb of type channel buffer
Returns
PCEP Object header
Definition at line 198 of file PcepObjectHeader.java.
References org.onosproject.pcepio.types.PcepObjectHeader.IFLAG_SET, org.onosproject.pcepio.types.PcepObjectHeader.OBJECT_TYPE_SHIFT_VALUE, org.onosproject.pcepio.types.PcepObjectHeader.PcepObjectHeader(), and org.onosproject.pcepio.types.PcepObjectHeader.PFLAG_SET.
void org.onosproject.pcepio.types.PcepObjectHeader.setIFlag (boolean value)
Sets the Object I flag.
Parameters
value I flag
Definition at line 112 of file PcepObjectHeader.java.
void org.onosproject.pcepio.types.PcepObjectHeader.setObjClass (byte value)
Sets the Object class.
Parameters
value object class
Definition at line 85 of file PcepObjectHeader.java.
void org.onosproject.pcepio.types.PcepObjectHeader.setObjLen (short value)
Sets the Object Length.
Parameters
value object length
Definition at line 121 of file PcepObjectHeader.java.
void org.onosproject.pcepio.types.PcepObjectHeader.setObjType (byte value)
Sets the Object TYPE.
Parameters
value object type
Definition at line 94 of file PcepObjectHeader.java.
void org.onosproject.pcepio.types.PcepObjectHeader.setPFlag (boolean value)
Sets the Object P flag.
Parameters
value p flag
Definition at line 103 of file PcepObjectHeader.java.
String org.onosproject.pcepio.types.PcepObjectHeader.toString ()
Definition at line 215 of file PcepObjectHeader.java.
int org.onosproject.pcepio.types.PcepObjectHeader.write (ChannelBuffer cb)
Writes Byte stream of PCEP object header to channel buffer.
Parameters
cb output channel buffer
Returns
objLenIndex object length index in channel buffer
Definition at line 176 of file PcepObjectHeader.java.
References org.onosproject.pcepio.types.PcepObjectHeader.IFLAG_SET, org.onosproject.pcepio.types.PcepObjectHeader.OBJECT_TYPE_SHIFT_VALUE, and org.onosproject.pcepio.types.PcepObjectHeader.PFLAG_SET.
Member Data Documentation
final byte org.onosproject.pcepio.types.PcepObjectHeader.IFLAG_SET = 0x01 static
Definition at line 54 of file PcepObjectHeader.java.
Referenced by org.onosproject.pcepio.types.PcepObjectHeader.read(), and org.onosproject.pcepio.types.PcepObjectHeader.write().
final Logger org.onosproject.pcepio.types.PcepObjectHeader.log = LoggerFactory.getLogger(PcepObjectHeader.class) static protected
Definition at line 46 of file PcepObjectHeader.java.
final int org.onosproject.pcepio.types.PcepObjectHeader.OBJECT_TYPE_SHIFT_VALUE = 4 static
Definition at line 52 of file PcepObjectHeader.java.
Referenced by org.onosproject.pcepio.types.PcepObjectHeader.read(), and org.onosproject.pcepio.types.PcepObjectHeader.write().
final byte org.onosproject.pcepio.types.PcepObjectHeader.PFLAG_SET = 0x02 static
Definition at line 53 of file PcepObjectHeader.java.
Referenced by org.onosproject.pcepio.types.PcepObjectHeader.read(), and org.onosproject.pcepio.types.PcepObjectHeader.write().
final boolean org.onosproject.pcepio.types.PcepObjectHeader.REQ_OBJ_MUST_PROCESS = true static
Definition at line 48 of file PcepObjectHeader.java.
final boolean org.onosproject.pcepio.types.PcepObjectHeader.REQ_OBJ_OPTIONAL_PROCESS = false static
Definition at line 49 of file PcepObjectHeader.java.
final boolean org.onosproject.pcepio.types.PcepObjectHeader.RSP_OBJ_IGNORED = true static
Definition at line 50 of file PcepObjectHeader.java.
final boolean org.onosproject.pcepio.types.PcepObjectHeader.RSP_OBJ_PROCESSED = false static
Definition at line 51 of file PcepObjectHeader.java.
final int org.onosproject.pcepio.types.PcepObjectHeader.SET = 1 static
Definition at line 55 of file PcepObjectHeader.java.
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PcepObjectHeader.java