onos: org.onosproject.store.serializers.KryoSerializerTest Class Reference
org.onosproject.store.serializers.KryoSerializerTest Class Reference
Public Member Functions
void setUp () throws Exception
void tearDown () throws Exception
void testConnectPoint ()
void testDefaultLink ()
void testDefaultPort ()
void testOmsPort ()
void testOchPort ()
void testOduCltPort ()
void testDeviceId ()
void testImmutableMap ()
void testImmutableSet ()
void testImmutableList ()
void testFlowRuleBatchEntry ()
void testIpPrefix ()
void testIp4Prefix ()
void testIp6Prefix ()
void testIpAddress ()
void testIp4Address ()
void testIp6Address ()
void testMacAddress ()
void testLinkKey ()
void testNodeId ()
void testPortNumber ()
void testProviderId ()
void testMastershipTerm ()
void testHostLocation ()
void testFlowId ()
void testRoleInfo ()
void testIndexedLambda ()
void testOchSignal ()
void testDefaultLinkResourceRequest ()
void testDefaultLinkResourceAllocations ()
void testResourcePath ()
void testResourceAllocation ()
void testFrequency ()
void testBandwidth ()
void testLambdaConstraint ()
void testBandwidthConstraint ()
void testLinkTypeConstraint ()
void testLatencyConstraint ()
void testWaypointConstraint ()
void testObstacleConstraint ()
void testArraysAsList ()
void testAnnotationConstraint ()
void testDefaultGroupId ()
void testEmptySet ()
void testAnnotations ()
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Static Protected Member Functions
static void assertAnnotationsEquals (Annotations actual, SparseAnnotations...annotations)
Detailed Description
Definition at line 104 of file KryoSerializerTest.java.
Member Function Documentation
static void org.onosproject.store.serializers.KryoSerializerTest.assertAnnotationsEquals (Annotations actual, SparseAnnotations... annotations) static protected
Definition at line 460 of file KryoSerializerTest.java.
References org.onosproject.net.SparseAnnotations.keys(), and org.onosproject.net.Annotations.value().
Referenced by org.onosproject.store.serializers.KryoSerializerTest.testAnnotations().
void org.onosproject.store.serializers.KryoSerializerTest.setUp () throws Exception
Definition at line 141 of file KryoSerializerTest.java.
References org.onosproject.store.serializers.KryoNamespaces.API, and org.onosproject.store.serializers.KryoNamespaces.BEGIN_USER_CUSTOM_ID.
static void org.onosproject.store.serializers.KryoSerializerTest.setUpBeforeClass () throws Exception static
Definition at line 137 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.tearDown () throws Exception
Definition at line 155 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testAnnotationConstraint ()
Definition at line 433 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testAnnotations ()
Definition at line 448 of file KryoSerializerTest.java.
References org.onosproject.store.serializers.KryoSerializerTest.assertAnnotationsEquals().
void org.onosproject.store.serializers.KryoSerializerTest.testArraysAsList ()
Definition at line 428 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testBandwidth ()
Definition at line 393 of file KryoSerializerTest.java.
References org.onlab.util.Bandwidth.mbps().
void org.onosproject.store.serializers.KryoSerializerTest.testBandwidthConstraint ()
Definition at line 403 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testConnectPoint ()
Definition at line 179 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testDefaultGroupId ()
Definition at line 438 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testDefaultLink ()
Definition at line 184 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testDefaultLinkResourceAllocations ()
Definition at line 362 of file KryoSerializerTest.java.
References org.onosproject.net.Link.Type.DIRECT, and org.onosproject.net.resource.link.LambdaResource.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testDefaultLinkResourceRequest ()
Definition at line 353 of file KryoSerializerTest.java.
References org.onosproject.net.resource.link.DefaultLinkResourceRequest.builder(), and org.onosproject.net.intent.IntentId.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testDefaultPort ()
Definition at line 190 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testDeviceId ()
Definition at line 216 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testEmptySet ()
Definition at line 443 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testFlowId ()
Definition at line 330 of file KryoSerializerTest.java.
References org.onosproject.net.flow.FlowId.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testFlowRuleBatchEntry ()
Definition at line 242 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testFrequency ()
Definition at line 388 of file KryoSerializerTest.java.
References org.onlab.util.Frequency.ofGHz().
void org.onosproject.store.serializers.KryoSerializerTest.testHostLocation ()
Definition at line 325 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testImmutableList ()
Definition at line 235 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testImmutableMap ()
Definition at line 221 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testImmutableSet ()
Definition at line 228 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testIndexedLambda ()
Definition at line 341 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testIp4Address ()
Definition at line 283 of file KryoSerializerTest.java.
References org.onlab.packet.Ip4Address.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testIp4Prefix ()
Definition at line 268 of file KryoSerializerTest.java.
References org.onlab.packet.Ip4Prefix.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testIp6Address ()
Definition at line 288 of file KryoSerializerTest.java.
References org.onlab.packet.Ip6Address.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testIp6Prefix ()
Definition at line 273 of file KryoSerializerTest.java.
References org.onlab.packet.Ip6Prefix.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testIpAddress ()
Definition at line 278 of file KryoSerializerTest.java.
References org.onlab.packet.IpAddress.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testIpPrefix ()
Definition at line 263 of file KryoSerializerTest.java.
References org.onlab.packet.IpPrefix.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testLambdaConstraint ()
Definition at line 398 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testLatencyConstraint ()
Definition at line 413 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testLinkKey ()
Definition at line 298 of file KryoSerializerTest.java.
References org.onosproject.net.LinkKey.linkKey().
void org.onosproject.store.serializers.KryoSerializerTest.testLinkTypeConstraint ()
Definition at line 408 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testMacAddress ()
Definition at line 293 of file KryoSerializerTest.java.
References org.onlab.packet.MacAddress.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testMastershipTerm ()
Definition at line 319 of file KryoSerializerTest.java.
References org.onosproject.mastership.MastershipTerm.of().
void org.onosproject.store.serializers.KryoSerializerTest.testNodeId ()
Definition at line 303 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testObstacleConstraint ()
Definition at line 423 of file KryoSerializerTest.java.
References find-flow.deviceId.
void org.onosproject.store.serializers.KryoSerializerTest.testOchPort ()
Definition at line 204 of file KryoSerializerTest.java.
References org.onosproject.net.OduSignalType.ODU0.
void org.onosproject.store.serializers.KryoSerializerTest.testOchSignal ()
Definition at line 346 of file KryoSerializerTest.java.
References org.onosproject.net.ChannelSpacing.CHL_100GHZ, and org.onosproject.net.GridType.DWDM.
void org.onosproject.store.serializers.KryoSerializerTest.testOduCltPort ()
Definition at line 210 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testOmsPort ()
Definition at line 196 of file KryoSerializerTest.java.
References org.onlab.util.Frequency.ofGHz().
void org.onosproject.store.serializers.KryoSerializerTest.testPortNumber ()
Definition at line 308 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testProviderId ()
Definition at line 313 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testResourceAllocation ()
Definition at line 381 of file KryoSerializerTest.java.
References org.onosproject.net.newresource.ResourcePath.discrete(), org.onosproject.net.LinkKey.linkKey(), and org.onosproject.net.intent.IntentId.valueOf().
void org.onosproject.store.serializers.KryoSerializerTest.testResourcePath ()
Definition at line 376 of file KryoSerializerTest.java.
References org.onosproject.net.newresource.ResourcePath.discrete(), and org.onosproject.net.LinkKey.linkKey().
void org.onosproject.store.serializers.KryoSerializerTest.testRoleInfo ()
Definition at line 335 of file KryoSerializerTest.java.
void org.onosproject.store.serializers.KryoSerializerTest.testWaypointConstraint ()
Definition at line 418 of file KryoSerializerTest.java.
References find-flow.deviceId.
The documentation for this class was generated from the following file:
core/store/serializers/src/test/java/org/onosproject/store/serializers/KryoSerializerTest.java