onos: org.onosproject.app.DefaultApplicationDescription Class Reference
org.onosproject.app.DefaultApplicationDescription Class Reference
Default implementation of network control/management application descriptor.
Public Member Functions
DefaultApplicationDescription (String name, Version version, String description, String origin, ApplicationRole role, Set< Permission > permissions, URI featuresRepo, List< String > features, List< String > requiredApps)
Creates a new application descriptor using the supplied data.
String name ()
Returns the application name id.
Version version ()
Returns the application version.
String description ()
Returns description of the application.
String origin ()
Returns the name of the application origin, group or company.
ApplicationRole role ()
Returns the role of the application.
Set< Permission > permissions ()
Returns the permissions requested by the application.
Optional< URI > featuresRepo ()
Returns the feature repository URI.
List< String > features ()
Returns the list of features comprising the application.
List< String > requiredApps ()
Returns list of required application names.
String toString ()
Detailed Description
Default implementation of network control/management application descriptor.
Definition at line 34 of file DefaultApplicationDescription.java.
Constructor & Destructor Documentation
org.onosproject.app.DefaultApplicationDescription.DefaultApplicationDescription (String name, Version version, String description, String origin, ApplicationRole role, Set< Permission > permissions, URI featuresRepo, List< String > features, List< String > requiredApps)
Creates a new application descriptor using the supplied data.
Parameters
name application name
version application version
description application description
origin origin company
role application role
permissions requested permissions
featuresRepo optional features repo URI
features application features
requiredApps list of required application names
Definition at line 59 of file DefaultApplicationDescription.java.
References org.onosproject.app.DefaultApplicationDescription.featuresRepo().
Member Function Documentation
String org.onosproject.app.DefaultApplicationDescription.description ()
Returns description of the application.
Returns
application description text
Implements org.onosproject.app.ApplicationDescription.
Definition at line 87 of file DefaultApplicationDescription.java.
Referenced by org.onosproject.app.DefaultApplicationDescription.toString().
List<String> org.onosproject.app.DefaultApplicationDescription.features ()
Returns the list of features comprising the application.
At least one feature must be given.
Returns
application features
Implements org.onosproject.app.ApplicationDescription.
Definition at line 112 of file DefaultApplicationDescription.java.
Referenced by org.onosproject.app.DefaultApplicationDescription.toString().
Optional<URI> org.onosproject.app.DefaultApplicationDescription.featuresRepo ()
Returns the feature repository URI.
Null value signifies that the application did not provide its own features repository.
Returns
optional feature repo URL
Implements org.onosproject.app.ApplicationDescription.
Definition at line 107 of file DefaultApplicationDescription.java.
Referenced by org.onosproject.app.DefaultApplicationDescription.DefaultApplicationDescription(), and org.onosproject.app.DefaultApplicationDescription.toString().
String org.onosproject.app.DefaultApplicationDescription.name ()
Returns the application name id.
Returns
application identifier
Implements org.onosproject.app.ApplicationDescription.
Definition at line 77 of file DefaultApplicationDescription.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.app.DefaultApplicationDescription.toString().
String org.onosproject.app.DefaultApplicationDescription.origin ()
Returns the name of the application origin, group or company.
Returns
application origin
Implements org.onosproject.app.ApplicationDescription.
Definition at line 92 of file DefaultApplicationDescription.java.
Referenced by org.onosproject.app.DefaultApplicationDescription.toString().
Set<Permission> org.onosproject.app.DefaultApplicationDescription.permissions ()
Returns the permissions requested by the application.
Returns
requested permissions
Implements org.onosproject.app.ApplicationDescription.
Definition at line 102 of file DefaultApplicationDescription.java.
Referenced by org.onosproject.app.DefaultApplicationDescription.toString().
List<String> org.onosproject.app.DefaultApplicationDescription.requiredApps ()
Returns list of required application names.
Returns
list of application names
Implements org.onosproject.app.ApplicationDescription.
Definition at line 117 of file DefaultApplicationDescription.java.
Referenced by org.onosproject.app.DefaultApplicationDescription.toString().
ApplicationRole org.onosproject.app.DefaultApplicationDescription.role ()
Returns the role of the application.
Returns
application role
Implements org.onosproject.app.ApplicationDescription.
Definition at line 97 of file DefaultApplicationDescription.java.
Referenced by org.onosproject.app.DefaultApplicationDescription.toString().
String org.onosproject.app.DefaultApplicationDescription.toString ()
Definition at line 122 of file DefaultApplicationDescription.java.
References org.onosproject.app.DefaultApplicationDescription.description(), org.onosproject.app.DefaultApplicationDescription.features(), org.onosproject.app.DefaultApplicationDescription.featuresRepo(), org.onosproject.app.DefaultApplicationDescription.name(), org.onosproject.app.DefaultApplicationDescription.origin(), org.onosproject.app.DefaultApplicationDescription.permissions(), org.onosproject.app.DefaultApplicationDescription.requiredApps(), org.onosproject.app.DefaultApplicationDescription.role(), and org.onosproject.app.DefaultApplicationDescription.version().
Version org.onosproject.app.DefaultApplicationDescription.version ()
Returns the application version.
Returns
application version
Implements org.onosproject.app.ApplicationDescription.
Definition at line 82 of file DefaultApplicationDescription.java.
Referenced by org.onosproject.app.DefaultApplicationDescription.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/app/DefaultApplicationDescription.java