onos: org.onosproject.pcepio.types.NexthopIPv4addressTlv Class Reference
org.onosproject.pcepio.types.NexthopIPv4addressTlv Class Reference
NexthopIPv6addressTlv provides Ipv4 address of next hop.
Public Member Functions
NexthopIPv4addressTlv (int rawValue)
Constructor to initialize next hop IPv4 address.
int getInt ()
Returns next hop IPv4 address.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static NexthopIPv4addressTlv of (final int raw)
Return next hop IPv4 address tlv.
static NexthopIPv4addressTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of NexthopIPv4addressTlv.
Static Public Attributes
static final short TYPE = 2
static final short LENGTH = 8
static final short VALUE_LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(NexthopIPv4addressTlv.class)
Detailed Description
NexthopIPv6addressTlv provides Ipv4 address of next hop.
Definition at line 31 of file NexthopIPv4addressTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.NexthopIPv4addressTlv.NexthopIPv4addressTlv (int rawValue)
Constructor to initialize next hop IPv4 address.
Parameters
rawValue next hop IPv4 address
Definition at line 61 of file NexthopIPv4addressTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopIPv4addressTlv.equals(), and org.onosproject.pcepio.types.NexthopIPv4addressTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.NexthopIPv4addressTlv.equals (Object obj)
Definition at line 105 of file NexthopIPv4addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv4addressTlv.NexthopIPv4addressTlv().
int org.onosproject.pcepio.types.NexthopIPv4addressTlv.getInt ()
Returns next hop IPv4 address.
Returns
next hop IPv4 address
Definition at line 80 of file NexthopIPv4addressTlv.java.
short org.onosproject.pcepio.types.NexthopIPv4addressTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 95 of file NexthopIPv4addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv4addressTlv.LENGTH.
short org.onosproject.pcepio.types.NexthopIPv4addressTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 90 of file NexthopIPv4addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv4addressTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.NexthopIPv4addressTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 85 of file NexthopIPv4addressTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.NexthopIPv4addressTlv.hashCode ()
Definition at line 100 of file NexthopIPv4addressTlv.java.
static NexthopIPv4addressTlv org.onosproject.pcepio.types.NexthopIPv4addressTlv.of (final int raw) static
Return next hop IPv4 address tlv.
Parameters
raw of next hop IPv4 address
Returns
object of NexthopIPv4addressTlv
Definition at line 71 of file NexthopIPv4addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv4addressTlv.NexthopIPv4addressTlv().
static NexthopIPv4addressTlv org.onosproject.pcepio.types.NexthopIPv4addressTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of NexthopIPv4addressTlv.
Parameters
c type of channel buffer
Returns
object of NexthopIPv4addressTlv
Definition at line 131 of file NexthopIPv4addressTlv.java.
String org.onosproject.pcepio.types.NexthopIPv4addressTlv.toString ()
Definition at line 136 of file NexthopIPv4addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv4addressTlv.LENGTH, and org.onosproject.pcepio.types.NexthopIPv4addressTlv.TYPE.
int org.onosproject.pcepio.types.NexthopIPv4addressTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 117 of file NexthopIPv4addressTlv.java.
References org.onosproject.pcepio.types.NexthopIPv4addressTlv.LENGTH, and org.onosproject.pcepio.types.NexthopIPv4addressTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.NexthopIPv4addressTlv.LENGTH = 8 static
Definition at line 51 of file NexthopIPv4addressTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopIPv4addressTlv.getLength(), org.onosproject.pcepio.types.NexthopIPv4addressTlv.toString(), and org.onosproject.pcepio.types.NexthopIPv4addressTlv.write().
final Logger org.onosproject.pcepio.types.NexthopIPv4addressTlv.log = LoggerFactory.getLogger(NexthopIPv4addressTlv.class) static protected
Definition at line 47 of file NexthopIPv4addressTlv.java.
final short org.onosproject.pcepio.types.NexthopIPv4addressTlv.TYPE = 2 static
Definition at line 49 of file NexthopIPv4addressTlv.java.
Referenced by org.onosproject.pcepio.types.NexthopIPv4addressTlv.getType(), org.onosproject.pcepio.types.NexthopIPv4addressTlv.toString(), and org.onosproject.pcepio.types.NexthopIPv4addressTlv.write().
final short org.onosproject.pcepio.types.NexthopIPv4addressTlv.VALUE_LENGTH = 4 static
Definition at line 52 of file NexthopIPv4addressTlv.java.
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/NexthopIPv4addressTlv.java