onos: org.onosproject.bgpio.types.AsPath Class Reference
org.onosproject.bgpio.types.AsPath Class Reference
Provides Implementation of AsPath mandatory BGP Path Attribute.
Classes
enum ASTYPE
Enum to provide AS types.
Public Member Functions
AsPath ()
Initialize Fields.
AsPath (List< Short > aspathSet, List< Short > aspathSeq)
Constructor to initialize parameters.
short getType ()
Returns the Type of BGP Message.
boolean isaspathSet ()
Returns whether ASpath path attribute is present.
List< Short > asPathSeq ()
Returns list of ASNum in ASpath Sequence.
List< Short > asPathSet ()
Returns list of ASNum in ASpath SET.
int hashCode ()
boolean equals (Object obj)
String toString ()
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static AsPath read (ChannelBuffer cb) throws BgpParseException
Reads from the channel buffer and parses AsPath.
Static Public Attributes
static final byte ASPATH_TYPE = 2
static final byte ASPATH_SET_TYPE = 1
static final byte ASPATH_SEQ_TYPE = 2
static final byte ASNUM_SIZE = 2
Detailed Description
Provides Implementation of AsPath mandatory BGP Path Attribute.
Definition at line 35 of file AsPath.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.AsPath.AsPath ()
Initialize Fields.
Definition at line 75 of file AsPath.java.
Referenced by org.onosproject.bgpio.types.AsPath.equals(), and org.onosproject.bgpio.types.AsPath.read().
org.onosproject.bgpio.types.AsPath.AsPath (List< Short > aspathSet, List< Short > aspathSeq)
Constructor to initialize parameters.
Parameters
aspathSet ASpath Set type
aspathSeq ASpath Sequence type
Definition at line 86 of file AsPath.java.
Member Function Documentation
List<Short> org.onosproject.bgpio.types.AsPath.asPathSeq ()
Returns list of ASNum in ASpath Sequence.
Returns
list of ASNum in ASpath Sequence
Definition at line 164 of file AsPath.java.
List<Short> org.onosproject.bgpio.types.AsPath.asPathSet ()
Returns list of ASNum in ASpath SET.
Returns
list of ASNum in ASpath SET
Definition at line 173 of file AsPath.java.
int org.onosproject.bgpio.types.AsPath.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 210 of file AsPath.java.
boolean org.onosproject.bgpio.types.AsPath.equals (Object obj)
Definition at line 183 of file AsPath.java.
References org.onosproject.bgpio.types.AsPath.AsPath().
Referenced by org.onosproject.bgp.controller.impl.BgpSelectionAlgo.compare().
short org.onosproject.bgpio.types.AsPath.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 146 of file AsPath.java.
References org.onosproject.bgpio.types.AsPath.ASPATH_TYPE.
int org.onosproject.bgpio.types.AsPath.hashCode ()
Definition at line 178 of file AsPath.java.
boolean org.onosproject.bgpio.types.AsPath.isaspathSet ()
Returns whether ASpath path attribute is present.
Returns
whether ASpath path attribute is present
Definition at line 155 of file AsPath.java.
static AsPath org.onosproject.bgpio.types.AsPath.read (ChannelBuffer cb) throws BgpParseException static
Reads from the channel buffer and parses AsPath.
Parameters
cb ChannelBuffer
Returns
object of AsPath
Exceptions
BgpParseException while parsing AsPath
Definition at line 99 of file AsPath.java.
References org.onosproject.bgpio.types.AsPath.ASNUM_SIZE, org.onosproject.bgpio.types.AsPath.AsPath(), org.onosproject.bgpio.types.AsPath.ASPATH_SEQ_TYPE, org.onosproject.bgpio.types.AsPath.ASPATH_SET_TYPE, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_FLAGS_ERROR, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, find-link-in-cluster.length, org.onosproject.bgpio.util.Constants.TYPE_AND_LEN_AS_BYTE, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.AsPath.toString ()
Definition at line 195 of file AsPath.java.
int org.onosproject.bgpio.types.AsPath.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 204 of file AsPath.java.
Member Data Documentation
final byte org.onosproject.bgpio.types.AsPath.ASNUM_SIZE = 2 static
Definition at line 66 of file AsPath.java.
Referenced by org.onosproject.bgpio.types.AsPath.read().
final byte org.onosproject.bgpio.types.AsPath.ASPATH_SEQ_TYPE = 2 static
Definition at line 65 of file AsPath.java.
Referenced by org.onosproject.bgpio.types.AsPath.read().
final byte org.onosproject.bgpio.types.AsPath.ASPATH_SET_TYPE = 1 static
Definition at line 64 of file AsPath.java.
Referenced by org.onosproject.bgpio.types.AsPath.read().
final byte org.onosproject.bgpio.types.AsPath.ASPATH_TYPE = 2 static
Definition at line 63 of file AsPath.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.checkMandatoryAttr(), and org.onosproject.bgpio.types.AsPath.getType().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/AsPath.java