onos: org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric Class Reference
org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric Class Reference
Implements BGP link state Default TE metric link attribute.
Public Member Functions
BgpLinkAttrTeDefaultMetric (int linkTeMetric)
Constructor to initialize the value.
int attrLinkDefTeMetric ()
Returns the TE default metrics.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpLinkAttrTeDefaultMetric of (final int linkTeMetric)
Returns object of this class with specified values.
static BgpLinkAttrTeDefaultMetric read (ChannelBuffer cb) throws BgpParseException
Reads the BGP link attributes of TE default metric.
Static Public Attributes
static final int ATTRLINK_TEDEFAULTMETRIC = 1092
static final int TE_DATA_LEN = 4
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP link state Default TE metric link attribute.
Definition at line 33 of file BgpLinkAttrTeDefaultMetric.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.BgpLinkAttrTeDefaultMetric (int linkTeMetric)
Constructor to initialize the value.
Parameters
linkTeMetric TE default metric
Definition at line 50 of file BgpLinkAttrTeDefaultMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.equals(), org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.of(), and org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.read().
Member Function Documentation
int org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.attrLinkDefTeMetric ()
Returns the TE default metrics.
Returns
link default metric
Definition at line 94 of file BgpLinkAttrTeDefaultMetric.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 134 of file BgpLinkAttrTeDefaultMetric.java.
boolean org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.equals (Object obj)
Definition at line 109 of file BgpLinkAttrTeDefaultMetric.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.BgpLinkAttrTeDefaultMetric().
short org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 99 of file BgpLinkAttrTeDefaultMetric.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.ATTRLINK_TEDEFAULTMETRIC.
int org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.hashCode ()
Definition at line 104 of file BgpLinkAttrTeDefaultMetric.java.
static BgpLinkAttrTeDefaultMetric org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.of (final int linkTeMetric) static
Returns object of this class with specified values.
Parameters
linkTeMetric TE default metric
Returns
object of BgpLinkAttrTeDefaultMetric
Definition at line 60 of file BgpLinkAttrTeDefaultMetric.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.BgpLinkAttrTeDefaultMetric().
static BgpLinkAttrTeDefaultMetric org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.read (ChannelBuffer cb) throws BgpParseException static
Reads the BGP link attributes of TE default metric.
Parameters
cb Channel buffer
Returns
object of type BgpLinkAttrTeDefaultMetric
Exceptions
BgpParseException while parsing BgpLinkAttrTeDefaultMetric
Definition at line 71 of file BgpLinkAttrTeDefaultMetric.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.BgpLinkAttrTeDefaultMetric(), org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.TE_DATA_LEN, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.toString ()
Definition at line 128 of file BgpLinkAttrTeDefaultMetric.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 122 of file BgpLinkAttrTeDefaultMetric.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.ATTRLINK_TEDEFAULTMETRIC = 1092 static
Definition at line 38 of file BgpLinkAttrTeDefaultMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.getType().
final Logger org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpLinkAttrTeDefaultMetric.class)
Definition at line 35 of file BgpLinkAttrTeDefaultMetric.java.
final int org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.TE_DATA_LEN = 4 static
Definition at line 39 of file BgpLinkAttrTeDefaultMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrTeDefaultMetric.read().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpLinkAttrTeDefaultMetric.java