onos: org.onosproject.cli.net.DevicesListCommand Class Reference
org.onosproject.cli.net.DevicesListCommand Class Reference
Lists all infrastructure devices.
Static Public Member Functions
static List< Device > getSortedDevices (DeviceService service)
Returns the list of devices sorted using the device ID URIs.
Static Public Member Functions inherited from org.onosproject.cli.AbstractShellCommand
static< T > T get (Class< T > serviceClass)
Returns the reference to the implementation of the specified service.
static String annotations (Annotations annotations)
Produces a string image of the specified key/value annotations.
static ObjectNode annotations (ObjectMapper mapper, Annotations annotations)
Produces a JSON object from the specified key/value annotations.
Protected Member Functions
void execute ()
Executes this command.
void printDevice (DeviceService service, Device device)
Prints information about the specified device.
Protected Member Functions inherited from org.onosproject.cli.AbstractShellCommand
ApplicationId appId ()
Returns application ID for the CLI.
boolean outputJson ()
Indicates whether JSON format should be output.
Object doExecute () throws Exception
Additional Inherited Members
Public Member Functions inherited from org.onosproject.cli.AbstractShellCommand
void print (String format, Object...args)
Prints the arguments using the specified format.
void error (String format, Object...args)
Prints the arguments using the specified format to error stream.
ObjectMapper mapper ()
Returns the JSON object mapper.
Detailed Description
Lists all infrastructure devices.
Definition at line 38 of file DevicesListCommand.java.
Member Function Documentation
void org.onosproject.cli.net.DevicesListCommand.execute () protected virtual
Executes this command.
Implements org.onosproject.cli.AbstractShellCommand.
Definition at line 44 of file DevicesListCommand.java.
References create-flow.device.
static List<Device> org.onosproject.cli.net.DevicesListCommand.getSortedDevices (DeviceService service) static
Returns the list of devices sorted using the device ID URIs.
Parameters
service device service
Returns
sorted device list
Definition at line 76 of file DevicesListCommand.java.
References org.onosproject.cli.Comparators.ELEMENT_COMPARATOR, and org.onosproject.net.device.DeviceService.getDevices().
void org.onosproject.cli.net.DevicesListCommand.printDevice (DeviceService service, Device device) protected
Prints information about the specified device.
Parameters
service device service
device infrastructure device
Definition at line 88 of file DevicesListCommand.java.
References org.onosproject.net.Annotated.annotations(), org.onosproject.net.Device.id(), org.onosproject.net.Device.manufacturer(), and org.onosproject.net.Device.swVersion().
The documentation for this class was generated from the following file:
cli/src/main/java/org/onosproject/cli/net/DevicesListCommand.java