onos: org.onosproject.incubator.net.meter.impl.MeterManagerTest Class Reference
org.onosproject.incubator.net.meter.impl.MeterManagerTest Class Reference
Meter manager tests.
Classes
class TestApplicationId
Public Member Functions
void setup () throws Exception
void tearDown ()
void testAddition ()
void testRemove ()
void testMultipleDevice ()
Detailed Description
Meter manager tests.
Definition at line 68 of file MeterManagerTest.java.
Member Function Documentation
void org.onosproject.incubator.net.meter.impl.MeterManagerTest.setup () throws Exception
Definition at line 93 of file MeterManagerTest.java.
void org.onosproject.incubator.net.meter.impl.MeterManagerTest.tearDown ()
Definition at line 154 of file MeterManagerTest.java.
void org.onosproject.incubator.net.meter.impl.MeterManagerTest.testAddition ()
Definition at line 165 of file MeterManagerTest.java.
References org.onosproject.incubator.net.meter.impl.MeterManager.getAllMeters(), org.onosproject.incubator.net.meter.impl.MeterManager.getMeter(), and org.onosproject.net.meter.MeterId.meterId().
void org.onosproject.incubator.net.meter.impl.MeterManagerTest.testMultipleDevice ()
Definition at line 188 of file MeterManagerTest.java.
References org.onosproject.incubator.net.meter.impl.MeterManager.getAllMeters(), org.onosproject.incubator.net.meter.impl.MeterManager.getMeter(), and org.onosproject.net.meter.MeterId.meterId().
void org.onosproject.incubator.net.meter.impl.MeterManagerTest.testRemove ()
Definition at line 174 of file MeterManagerTest.java.
References org.onosproject.incubator.net.meter.impl.MeterManager.getAllMeters(), org.onosproject.incubator.net.meter.impl.MeterManager.getMeter(), org.onosproject.net.meter.Meter.id(), org.onosproject.net.meter.MeterId.meterId(), and org.onosproject.net.meter.MeterState.PENDING_REMOVE.
The documentation for this class was generated from the following file:
incubator/net/src/test/java/org/onosproject/incubator/net/meter/impl/MeterManagerTest.java