onos: org.onosproject.ui.UiView Class Reference
org.onosproject.ui.UiView Class Reference
Represents user interface view addition.
Classes
enum Category
Designates navigation menu category.
Public Member Functions
UiView (Category category, String id, String label)
Creates a new user interface view descriptor.
UiView (Category category, String id, String label, String iconId)
Creates a new user interface view descriptor.
Category category ()
Returns the navigation category.
String id ()
Returns the view identifier.
String label ()
Returns the view label.
String iconId ()
Returns the icon ID.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Represents user interface view addition.
Definition at line 25 of file UiView.java.
Constructor & Destructor Documentation
org.onosproject.ui.UiView.UiView (Category category, String id, String label)
Creates a new user interface view descriptor.
The navigation item will appear in the navigation menu under the specified category.
Parameters
category view category
id view identifier
label view label
Definition at line 82 of file UiView.java.
References org.onosproject.ui.UiView.category(), org.onosproject.ui.UiView.id(), and org.onosproject.ui.UiView.label().
Referenced by org.onosproject.ui.UiView.equals().
org.onosproject.ui.UiView.UiView (Category category, String id, String label, String iconId)
Creates a new user interface view descriptor.
The navigation item will appear in the navigation menu under the specified category, with the specified icon adornment.
Parameters
category view category
id view identifier
label view label
iconId icon id
Definition at line 96 of file UiView.java.
References org.onosproject.ui.UiView.category(), org.onosproject.ui.UiView.iconId(), org.onosproject.ui.UiView.id(), and org.onosproject.ui.UiView.label().
Member Function Documentation
Category org.onosproject.ui.UiView.category ()
Returns the navigation category.
Returns
navigation category
Definition at line 108 of file UiView.java.
Referenced by org.onosproject.ui.UiView.toString(), and org.onosproject.ui.UiView.UiView().
boolean org.onosproject.ui.UiView.equals (Object obj)
Definition at line 145 of file UiView.java.
References find-device.id, and org.onosproject.ui.UiView.UiView().
int org.onosproject.ui.UiView.hashCode ()
Definition at line 140 of file UiView.java.
String org.onosproject.ui.UiView.iconId ()
Returns the icon ID.
Returns
icon ID
Definition at line 135 of file UiView.java.
Referenced by org.onosproject.ui.UiView.toString(), and org.onosproject.ui.UiView.UiView().
String org.onosproject.ui.UiView.id ()
Returns the view identifier.
Returns
view id
Definition at line 117 of file UiView.java.
Referenced by org.onosproject.ui.UiView.toString(), org.onosproject.ui.UiView.UiView(), and org.onosproject.ui.impl.UiExtensionManager.unregister().
String org.onosproject.ui.UiView.label ()
Returns the view label.
Returns
view label
Definition at line 126 of file UiView.java.
Referenced by org.onosproject.ui.UiView.Category.Category(), org.onosproject.ui.UiView.Category.label(), org.onosproject.ui.UiView.toString(), and org.onosproject.ui.UiView.UiView().
String org.onosproject.ui.UiView.toString ()
Definition at line 157 of file UiView.java.
References org.onosproject.ui.UiView.category(), org.onosproject.ui.UiView.iconId(), org.onosproject.ui.UiView.id(), and org.onosproject.ui.UiView.label().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/UiView.java