onos: org.onosproject.store.service.EventuallyConsistentMapEvent< K, V > Class Reference
org.onosproject.store.service.EventuallyConsistentMapEvent< K, V > Class Reference
Representation of a EventuallyConsistentMap update notification.
Classes
enum Type
Public Member Functions
EventuallyConsistentMapEvent (String name, Type type, K key, V value)
Creates a new event object.
String name ()
Returns the map name.
Type type ()
Returns the type of the event.
K key ()
Returns the key this event concerns.
V value ()
Returns the value associated with this event.
boolean equals (Object o)
int hashCode ()
String toString ()
Detailed Description
Representation of a EventuallyConsistentMap update notification.
Definition at line 25 of file EventuallyConsistentMapEvent.java.
Constructor & Destructor Documentation
org.onosproject.store.service.EventuallyConsistentMapEvent< K, V >.EventuallyConsistentMapEvent (String name, Type type, K key, V value)
Creates a new event object.
Parameters
name map name
type the type of the event
key the key the event concerns
value the value mapped to the key
Definition at line 52 of file EventuallyConsistentMapEvent.java.
References create-flow.name.
Member Function Documentation
boolean org.onosproject.store.service.EventuallyConsistentMapEvent< K, V >.equals (Object o)
Definition at line 98 of file EventuallyConsistentMapEvent.java.
int org.onosproject.store.service.EventuallyConsistentMapEvent< K, V >.hashCode ()
Definition at line 111 of file EventuallyConsistentMapEvent.java.
K org.onosproject.store.service.EventuallyConsistentMapEvent< K, V >.key ()
Returns the key this event concerns.
Returns
the key
Definition at line 82 of file EventuallyConsistentMapEvent.java.
String org.onosproject.store.service.EventuallyConsistentMapEvent< K, V >.name ()
Returns the map name.
Returns
name of map
Definition at line 64 of file EventuallyConsistentMapEvent.java.
References create-flow.name.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.store.service.EventuallyConsistentMapEvent< K, V >.toString ()
Definition at line 116 of file EventuallyConsistentMapEvent.java.
References create-flow.name.
Type org.onosproject.store.service.EventuallyConsistentMapEvent< K, V >.type ()
Returns the type of the event.
Returns
the type of the event
Definition at line 73 of file EventuallyConsistentMapEvent.java.
V org.onosproject.store.service.EventuallyConsistentMapEvent< K, V >.value ()
Returns the value associated with this event.
If type is REMOVE, this is the value that was removed. If type is PUT, this is the new value.
Returns
the value
Definition at line 93 of file EventuallyConsistentMapEvent.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/store/service/EventuallyConsistentMapEvent.java