onos: org.onosproject.net.flow.FlowRuleExtPayLoad Class Reference
org.onosproject.net.flow.FlowRuleExtPayLoad Class Reference
Represents for 3rd-party private original flow.
Public Member Functions
byte[] payLoad ()
Returns private flow.
int hashCode ()
int hash ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static FlowRuleExtPayLoad flowRuleExtPayLoad (byte[] payLoad)
Creates a FlowRuleExtPayLoad.
Detailed Description
Represents for 3rd-party private original flow.
Definition at line 25 of file FlowRuleExtPayLoad.java.
Member Function Documentation
boolean org.onosproject.net.flow.FlowRuleExtPayLoad.equals (Object obj)
Definition at line 66 of file FlowRuleExtPayLoad.java.
References org.onosproject.net.flow.FlowRuleExtPayLoad.payLoad().
static FlowRuleExtPayLoad org.onosproject.net.flow.FlowRuleExtPayLoad.flowRuleExtPayLoad (byte[] payLoad) static
Creates a FlowRuleExtPayLoad.
Parameters
payLoad payload byte data
Returns
FlowRuleExtPayLoad payLoad
Definition at line 43 of file FlowRuleExtPayLoad.java.
Referenced by org.onosproject.flowanalyzer.FlowAnalyzerTest.genFlow().
int org.onosproject.net.flow.FlowRuleExtPayLoad.hash ()
Definition at line 61 of file FlowRuleExtPayLoad.java.
References org.onosproject.net.flow.FlowRuleExtPayLoad.payLoad().
int org.onosproject.net.flow.FlowRuleExtPayLoad.hashCode ()
Definition at line 57 of file FlowRuleExtPayLoad.java.
References org.onosproject.net.flow.FlowRuleExtPayLoad.payLoad().
byte [] org.onosproject.net.flow.FlowRuleExtPayLoad.payLoad ()
Returns private flow.
Returns
payLoad private flow
Definition at line 52 of file FlowRuleExtPayLoad.java.
Referenced by org.onosproject.net.flow.FlowRuleExtPayLoad.equals(), org.onosproject.net.flow.FlowRuleExtPayLoad.hash(), org.onosproject.net.flow.FlowRuleExtPayLoad.hashCode(), and org.onosproject.net.flow.FlowRuleExtPayLoad.toString().
String org.onosproject.net.flow.FlowRuleExtPayLoad.toString ()
Definition at line 79 of file FlowRuleExtPayLoad.java.
References org.onosproject.net.flow.FlowRuleExtPayLoad.payLoad().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/FlowRuleExtPayLoad.java