onos: org.onosproject.net.resource.link.MplsLabelResourceRequest Class Reference
org.onosproject.net.resource.link.MplsLabelResourceRequest Class Reference
Representation of a request for lambda resource.
Public Member Functions
MplsLabelResourceRequest (MplsLabel mplsLabel)
Constructs a request specifying the given MPLS label.
MplsLabelResourceRequest ()
Constructs a request asking an arbitrary available MPLS label.
MplsLabel mplsLabel ()
Returns the MPLS label this request expects.
ResourceType type ()
Returns the resource type.
String toString ()
Detailed Description
Representation of a request for lambda resource.
Deprecated:
in Emu Release
Definition at line 31 of file MplsLabelResourceRequest.java.
Constructor & Destructor Documentation
org.onosproject.net.resource.link.MplsLabelResourceRequest.MplsLabelResourceRequest (MplsLabel mplsLabel)
Constructs a request specifying the given MPLS label.
Parameters
mplsLabel MPLS label to be requested
Definition at line 41 of file MplsLabelResourceRequest.java.
org.onosproject.net.resource.link.MplsLabelResourceRequest.MplsLabelResourceRequest ()
Constructs a request asking an arbitrary available MPLS label.
Deprecated:
in Emu Release
Definition at line 51 of file MplsLabelResourceRequest.java.
Member Function Documentation
MplsLabel org.onosproject.net.resource.link.MplsLabelResourceRequest.mplsLabel ()
Returns the MPLS label this request expects.
Returns
the MPLS label this request expects
Definition at line 61 of file MplsLabelResourceRequest.java.
Referenced by org.onosproject.net.resource.impl.LinkResourceManager.requestResources(), and org.onosproject.net.resource.link.MplsLabelResourceRequest.toString().
String org.onosproject.net.resource.link.MplsLabelResourceRequest.toString ()
Definition at line 71 of file MplsLabelResourceRequest.java.
References org.onosproject.net.resource.link.MplsLabelResourceRequest.mplsLabel().
ResourceType org.onosproject.net.resource.link.MplsLabelResourceRequest.type ()
Returns the resource type.
Returns
the resource type
Implements org.onosproject.net.resource.ResourceRequest.
Definition at line 66 of file MplsLabelResourceRequest.java.
References org.onosproject.net.resource.ResourceType.MPLS_LABEL.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/resource/link/MplsLabelResourceRequest.java