onos: org.onosproject.cord.gui.XosManagerRestUtils Class Reference
org.onosproject.cord.gui.XosManagerRestUtils Class Reference
Utility RESTful methods for dealing with the XOS server.
Public Member Functions
XosManagerRestUtils (String xosServerAddress, int xosServerPort, String baseUri)
Constructs a utility class, using the supplied server address and port, using the given base URI.
WebResource.Builder getClientBuilder ()
Gets a client web resource builder for the base XOS REST API with no additional URI.
WebResource.Builder getClientBuilder (String uri)
Gets a client web resource builder for the base XOS REST API with an optional additional URI.
String getRest ()
Performs a REST GET operation on the base XOS REST URI.
String getRest (String uri)
Performs a REST GET operation on the base XOS REST URI with an optional additional URI.
String putRest ()
Performs a REST PUT operation on the base XOS REST URI.
String putRest (String uri)
Performs a REST PUT operation on the base XOS REST URI with an optional additional URI.
void postRest (String json)
Performs a REST POST operation of a json string on the base XOS REST URI with an optional additional URI.
void postRest (String uri, String json)
Performs a REST POST operation of a json string on the base XOS REST URI with an optional additional URI suffix.
void deleteRest (String uri)
Performs a REST DELETE operation on the base XOS REST URI with an optional additional URI.
Detailed Description
Utility RESTful methods for dealing with the XOS server.
Definition at line 34 of file XosManagerRestUtils.java.
Constructor & Destructor Documentation
org.onosproject.cord.gui.XosManagerRestUtils.XosManagerRestUtils (String xosServerAddress, int xosServerPort, String baseUri)
Constructs a utility class, using the supplied server address and port, using the given base URI.
Note that the uri should start and end with a slash; for example:
"/volttenant/"
. This example would result in URIs of the form:
    "http://[server]:[port]/xoslib/volttenant/"
Parameters
xosServerAddress server IP address
xosServerPort server port
baseUri base URI
Definition at line 62 of file XosManagerRestUtils.java.
Member Function Documentation
void org.onosproject.cord.gui.XosManagerRestUtils.deleteRest (String uri)
Performs a REST DELETE operation on the base XOS REST URI with an optional additional URI.
Parameters
uri URI suffix to append to base URI
Definition at line 202 of file XosManagerRestUtils.java.
References org.onosproject.cord.gui.XosManagerRestUtils.getClientBuilder().
WebResource.Builder org.onosproject.cord.gui.XosManagerRestUtils.getClientBuilder ()
Gets a client web resource builder for the base XOS REST API with no additional URI.
Returns
web resource builder
Definition at line 82 of file XosManagerRestUtils.java.
Referenced by org.onosproject.cord.gui.XosManagerRestUtils.deleteRest(), org.onosproject.cord.gui.XosManagerRestUtils.getRest(), org.onosproject.cord.gui.XosManagerRestUtils.postRest(), and org.onosproject.cord.gui.XosManagerRestUtils.putRest().
WebResource.Builder org.onosproject.cord.gui.XosManagerRestUtils.getClientBuilder (String uri)
Gets a client web resource builder for the base XOS REST API with an optional additional URI.
Parameters
uri URI suffix to append to base URI
Returns
web resource builder
Definition at line 93 of file XosManagerRestUtils.java.
String org.onosproject.cord.gui.XosManagerRestUtils.getRest ()
Performs a REST GET operation on the base XOS REST URI.
Returns
JSON string fetched by the GET operation
Definition at line 106 of file XosManagerRestUtils.java.
String org.onosproject.cord.gui.XosManagerRestUtils.getRest (String uri)
Performs a REST GET operation on the base XOS REST URI with an optional additional URI.
Parameters
uri URI suffix to append to base URI
Returns
JSON string fetched by the GET operation
Definition at line 117 of file XosManagerRestUtils.java.
References org.onosproject.cord.gui.XosManagerRestUtils.getClientBuilder().
void org.onosproject.cord.gui.XosManagerRestUtils.postRest (String json)
Performs a REST POST operation of a json string on the base XOS REST URI with an optional additional URI.
Parameters
json JSON string to post
Definition at line 168 of file XosManagerRestUtils.java.
void org.onosproject.cord.gui.XosManagerRestUtils.postRest (String uri, String json)
Performs a REST POST operation of a json string on the base XOS REST URI with an optional additional URI suffix.
Parameters
uri URI suffix to append to base URI
json JSON string to post
Definition at line 179 of file XosManagerRestUtils.java.
References org.onosproject.cord.gui.XosManagerRestUtils.getClientBuilder().
String org.onosproject.cord.gui.XosManagerRestUtils.putRest ()
Performs a REST PUT operation on the base XOS REST URI.
Returns
JSON string returned by the PUT operation
Definition at line 133 of file XosManagerRestUtils.java.
String org.onosproject.cord.gui.XosManagerRestUtils.putRest (String uri)
Performs a REST PUT operation on the base XOS REST URI with an optional additional URI.
Parameters
uri URI suffix to append to base URI
Returns
JSON string returned by the PUT operation
Definition at line 144 of file XosManagerRestUtils.java.
References org.onosproject.cord.gui.XosManagerRestUtils.getClientBuilder().
The documentation for this class was generated from the following file:
apps/demo/cord-gui/src/main/java/org/onosproject/cord/gui/XosManagerRestUtils.java