onos: org.onosproject.net.intent.ConnectivityIntentTest Class Reference
org.onosproject.net.intent.ConnectivityIntentTest Class Reference
Base facilities to test various connectivity tests.
Static Public Attributes
static final ApplicationId APPID = new TestApplicationId("foo")
static final Key KEY = Key.of(1L, APPID)
static final IntentId IID = new IntentId(123)
static final TrafficSelector MATCH = DefaultTrafficSelector.emptySelector()
static final TrafficTreatment NOP = DefaultTrafficTreatment.emptyTreatment()
static final ConnectPoint P1 = new ConnectPoint(DeviceId.deviceId("111"), PortNumber.portNumber(0x1))
static final ConnectPoint P2 = new ConnectPoint(DeviceId.deviceId("222"), PortNumber.portNumber(0x2))
static final ConnectPoint P3 = new ConnectPoint(DeviceId.deviceId("333"), PortNumber.portNumber(0x3))
static final Set< ConnectPoint > PS1 = itemSet(new ConnectPoint[]{P1, P3})
static final Set< ConnectPoint > PS2 = itemSet(new ConnectPoint[]{P2, P3})
Additional Inherited Members
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Protected Member Functions inherited from org.onosproject.net.intent.IntentTest
abstract Intent createOne ()
Creates a new intent, but always a like intent, i.e.
abstract Intent createAnother ()
Creates another intent, not equals to the one created by createOne() and with a different hash code.
Static Protected Member Functions inherited from org.onosproject.net.intent.IntentTest
static< T > Set< T > itemSet (T[] items)
Produces a set of items from the supplied items.
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
Base facilities to test various connectivity tests.
Definition at line 33 of file ConnectivityIntentTest.java.
Member Data Documentation
final ApplicationId org.onosproject.net.intent.ConnectivityIntentTest.APPID = new TestApplicationId("foo") static
Definition at line 35 of file ConnectivityIntentTest.java.
Referenced by org.onosproject.net.intent.MultiPointToSinglePointIntentTest.basics(), org.onosproject.net.intent.PointToPointIntentTest.basics(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.basics(), org.onosproject.net.intent.PathIntentTest.basics(), org.onosproject.net.intent.PointToPointIntentTest.createAnother(), org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createAnother(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.createAnother(), org.onosproject.net.intent.PathIntentTest.createAnother(), org.onosproject.net.intent.PointToPointIntentTest.createOne(), org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createOne(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.createOne(), org.onosproject.net.intent.PathIntentTest.createOne(), org.onosproject.net.intent.PathIntentTest.testRaiseExceptionWhenDifferentDevice(), and org.onosproject.net.intent.PathIntentTest.testRaiseExceptionWhenSameDevices().
final IntentId org.onosproject.net.intent.ConnectivityIntentTest.IID = new IntentId(123) static
Definition at line 38 of file ConnectivityIntentTest.java.
final Key org.onosproject.net.intent.ConnectivityIntentTest.KEY = Key.of(1L, APPID) static
Definition at line 36 of file ConnectivityIntentTest.java.
Referenced by org.onosproject.net.intent.PathIntentTest.basics(), and org.onosproject.net.intent.PathIntentTest.createOne().
final TrafficSelector org.onosproject.net.intent.ConnectivityIntentTest.MATCH = DefaultTrafficSelector.emptySelector() static
Definition at line 39 of file ConnectivityIntentTest.java.
Referenced by org.onosproject.net.intent.MultiPointToSinglePointIntentTest.basics(), org.onosproject.net.intent.PointToPointIntentTest.basics(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.basics(), org.onosproject.net.intent.PathIntentTest.basics(), org.onosproject.net.intent.PointToPointIntentTest.createAnother(), org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createAnother(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.createAnother(), org.onosproject.net.intent.PathIntentTest.createAnother(), org.onosproject.net.intent.PointToPointIntentTest.createOne(), org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createOne(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.createOne(), org.onosproject.net.intent.PathIntentTest.createOne(), org.onosproject.net.intent.PathIntentTest.testRaiseExceptionWhenDifferentDevice(), and org.onosproject.net.intent.PathIntentTest.testRaiseExceptionWhenSameDevices().
final TrafficTreatment org.onosproject.net.intent.ConnectivityIntentTest.NOP = DefaultTrafficTreatment.emptyTreatment() static
Definition at line 40 of file ConnectivityIntentTest.java.
Referenced by org.onosproject.net.intent.PathIntentTest.basics(), org.onosproject.net.intent.PointToPointIntentTest.createAnother(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.createAnother(), org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createAnother(), org.onosproject.net.intent.PathIntentTest.createAnother(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.createOne(), org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createOne(), org.onosproject.net.intent.PointToPointIntentTest.createOne(), org.onosproject.net.intent.PathIntentTest.createOne(), org.onosproject.net.intent.PathIntentTest.testRaiseExceptionWhenDifferentDevice(), and org.onosproject.net.intent.PathIntentTest.testRaiseExceptionWhenSameDevices().
final ConnectPoint org.onosproject.net.intent.ConnectivityIntentTest.P1 = new ConnectPoint(DeviceId.deviceId("111"), PortNumber.portNumber(0x1)) static
Definition at line 42 of file ConnectivityIntentTest.java.
Referenced by org.onosproject.net.intent.PointToPointIntentTest.basics(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.basics(), org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createAnother(), org.onosproject.net.intent.PointToPointIntentTest.createAnother(), org.onosproject.net.intent.PointToPointIntentTest.createOne(), and org.onosproject.net.intent.SinglePointToMultiPointIntentTest.createOne().
final ConnectPoint org.onosproject.net.intent.ConnectivityIntentTest.P2 = new ConnectPoint(DeviceId.deviceId("222"), PortNumber.portNumber(0x2)) static
Definition at line 43 of file ConnectivityIntentTest.java.
Referenced by org.onosproject.net.intent.MultiPointToSinglePointIntentTest.basics(), org.onosproject.net.intent.PointToPointIntentTest.basics(), org.onosproject.net.intent.PointToPointIntentTest.createAnother(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.createAnother(), org.onosproject.net.intent.PointToPointIntentTest.createOne(), and org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createOne().
final ConnectPoint org.onosproject.net.intent.ConnectivityIntentTest.P3 = new ConnectPoint(DeviceId.deviceId("333"), PortNumber.portNumber(0x3)) static
Definition at line 44 of file ConnectivityIntentTest.java.
final Set<ConnectPoint> org.onosproject.net.intent.ConnectivityIntentTest.PS1 = itemSet(new ConnectPoint[]{P1, P3}) static
Definition at line 46 of file ConnectivityIntentTest.java.
Referenced by org.onosproject.net.intent.MultiPointToSinglePointIntentTest.basics(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.createAnother(), and org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createOne().
final Set<ConnectPoint> org.onosproject.net.intent.ConnectivityIntentTest.PS2 = itemSet(new ConnectPoint[]{P2, P3}) static
Definition at line 47 of file ConnectivityIntentTest.java.
Referenced by org.onosproject.net.intent.SinglePointToMultiPointIntentTest.basics(), org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createAnother(), and org.onosproject.net.intent.SinglePointToMultiPointIntentTest.createOne().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/intent/ConnectivityIntentTest.java