onos: org.onosproject.net.meter.DefaultBand Class Reference
org.onosproject.net.meter.DefaultBand Class Reference
A default implementation for a Band.
Classes
class Builder
Public Member Functions
DefaultBand (Type type, long rate, Long burstSize, Short prec)
long rate ()
The rate at which this meter applies.
long burst ()
The burst size at which the meter applies.
short dropPrecedence ()
Only meaningful in the case of a REMARK band type.
Type type ()
Signals the type of band to create.
long packets ()
Returns the packets seen by this band.
long bytes ()
Return the bytes seen by this band.
void setPackets (long packets)
Sets the number of packets seen by this band.
void setBytes (long bytes)
Sets the number of bytes seen by this band.
String toString ()
Static Public Member Functions
static Builder builder ()
Detailed Description
A default implementation for a Band.
Definition at line 24 of file DefaultBand.java.
Constructor & Destructor Documentation
org.onosproject.net.meter.DefaultBand.DefaultBand (Type type, long rate, Long burstSize, Short prec)
Definition at line 34 of file DefaultBand.java.
References org.onosproject.net.meter.DefaultBand.rate(), and org.onosproject.net.meter.DefaultBand.type().
Member Function Documentation
static Builder org.onosproject.net.meter.DefaultBand.builder () static
Definition at line 91 of file DefaultBand.java.
long org.onosproject.net.meter.DefaultBand.burst ()
The burst size at which the meter applies.
Returns
the long value of the size
Implements org.onosproject.net.meter.Band.
Definition at line 48 of file DefaultBand.java.
long org.onosproject.net.meter.DefaultBand.bytes ()
Return the bytes seen by this band.
Returns
a byte counter
Implements org.onosproject.net.meter.Band.
Definition at line 68 of file DefaultBand.java.
Referenced by org.onosproject.net.meter.DefaultBand.setBytes().
short org.onosproject.net.meter.DefaultBand.dropPrecedence ()
Only meaningful in the case of a REMARK band type.
indicates by which amount the drop precedence of the packet should be increase if the band is exceeded.
Returns
a short value
Implements org.onosproject.net.meter.Band.
Definition at line 53 of file DefaultBand.java.
long org.onosproject.net.meter.DefaultBand.packets ()
Returns the packets seen by this band.
Returns
a long value
Implements org.onosproject.net.meter.Band.
Definition at line 63 of file DefaultBand.java.
Referenced by org.onosproject.net.meter.DefaultBand.setPackets().
long org.onosproject.net.meter.DefaultBand.rate ()
The rate at which this meter applies.
Returns
the long value of the rate
Implements org.onosproject.net.meter.Band.
Definition at line 43 of file DefaultBand.java.
Referenced by org.onosproject.net.meter.DefaultBand.DefaultBand(), and org.onosproject.net.meter.DefaultBand.toString().
void org.onosproject.net.meter.DefaultBand.setBytes (long bytes)
Sets the number of bytes seen by this band.
Parameters
bytes a byte counter
Implements org.onosproject.net.meter.BandEntry.
Definition at line 78 of file DefaultBand.java.
References org.onosproject.net.meter.DefaultBand.bytes().
void org.onosproject.net.meter.DefaultBand.setPackets (long packets)
Sets the number of packets seen by this band.
Parameters
packets a packet count
Implements org.onosproject.net.meter.BandEntry.
Definition at line 73 of file DefaultBand.java.
References org.onosproject.net.meter.DefaultBand.packets().
String org.onosproject.net.meter.DefaultBand.toString ()
Definition at line 83 of file DefaultBand.java.
References org.onosproject.net.meter.DefaultBand.rate(), and org.onosproject.net.meter.DefaultBand.type().
Type org.onosproject.net.meter.DefaultBand.type ()
Signals the type of band to create.
Returns
a band type
Implements org.onosproject.net.meter.Band.
Definition at line 58 of file DefaultBand.java.
Referenced by org.onosproject.net.meter.DefaultBand.DefaultBand(), and org.onosproject.net.meter.DefaultBand.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/meter/DefaultBand.java