onos: org.onosproject.pcepio.types.IGPMetricTlv Class Reference
org.onosproject.pcepio.types.IGPMetricTlv Class Reference
Provides IGP Link Metric .
Public Member Functions
IGPMetricTlv (byte[] rawValue, short hLength)
Constructor to initialize raw value.
byte[] getValue ()
Returns value of IGP Link Metric.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static IGPMetricTlv of (final byte[] raw, short hLength)
Returns newly created IGPMetricTlv object.
static PcepValueType read (ChannelBuffer c, short hLength)
Reads the channel buffer and returns object of IGPMetricTlv.
Static Public Attributes
static final short TYPE = 1095
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IGPMetricTlv.class)
Detailed Description
Provides IGP Link Metric .
Definition at line 31 of file IGPMetricTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IGPMetricTlv.IGPMetricTlv (byte[] rawValue, short hLength)
Constructor to initialize raw value.
Parameters
rawValue IGP Link Metric
hLength length
Definition at line 56 of file IGPMetricTlv.java.
Referenced by org.onosproject.pcepio.types.IGPMetricTlv.equals(), org.onosproject.pcepio.types.IGPMetricTlv.of(), and org.onosproject.pcepio.types.IGPMetricTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.IGPMetricTlv.equals (Object obj)
Definition at line 102 of file IGPMetricTlv.java.
References org.onosproject.pcepio.types.IGPMetricTlv.IGPMetricTlv().
short org.onosproject.pcepio.types.IGPMetricTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 92 of file IGPMetricTlv.java.
short org.onosproject.pcepio.types.IGPMetricTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 87 of file IGPMetricTlv.java.
References org.onosproject.pcepio.types.IGPMetricTlv.TYPE.
byte [] org.onosproject.pcepio.types.IGPMetricTlv.getValue ()
Returns value of IGP Link Metric.
Returns
rawValue of IGP Link Metric
Definition at line 77 of file IGPMetricTlv.java.
PcepVersion org.onosproject.pcepio.types.IGPMetricTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 82 of file IGPMetricTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IGPMetricTlv.hashCode ()
Definition at line 97 of file IGPMetricTlv.java.
static IGPMetricTlv org.onosproject.pcepio.types.IGPMetricTlv.of (final byte[] raw, short hLength) static
Returns newly created IGPMetricTlv object.
Parameters
raw value of IGP Link Metric
hLength length
Returns
object of IGPMetricTlv
Definition at line 68 of file IGPMetricTlv.java.
References org.onosproject.pcepio.types.IGPMetricTlv.IGPMetricTlv().
static PcepValueType org.onosproject.pcepio.types.IGPMetricTlv.read (ChannelBuffer c, short hLength) static
Reads the channel buffer and returns object of IGPMetricTlv.
Parameters
c input channel buffer
hLength length
Returns
object of IGPMetricTlv
Definition at line 129 of file IGPMetricTlv.java.
References org.onosproject.pcepio.types.IGPMetricTlv.IGPMetricTlv().
String org.onosproject.pcepio.types.IGPMetricTlv.toString ()
Definition at line 136 of file IGPMetricTlv.java.
References org.onosproject.pcepio.types.IGPMetricTlv.TYPE.
int org.onosproject.pcepio.types.IGPMetricTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 114 of file IGPMetricTlv.java.
References org.onosproject.pcepio.types.IGPMetricTlv.TYPE.
Member Data Documentation
final Logger org.onosproject.pcepio.types.IGPMetricTlv.log = LoggerFactory.getLogger(IGPMetricTlv.class) static protected
Definition at line 43 of file IGPMetricTlv.java.
final short org.onosproject.pcepio.types.IGPMetricTlv.TYPE = 1095 static
Definition at line 45 of file IGPMetricTlv.java.
Referenced by org.onosproject.pcepio.types.IGPMetricTlv.getType(), org.onosproject.pcepio.types.IGPMetricTlv.toString(), and org.onosproject.pcepio.types.IGPMetricTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IGPMetricTlv.java