onos: org.onosproject.net.intent.constraint.AnnotationConstraint Class Reference
org.onosproject.net.intent.constraint.AnnotationConstraint Class Reference
Constraint that evaluates an arbitrary link annotated value is under the specified threshold.
Public Member Functions
AnnotationConstraint (String key, double threshold)
Creates a new constraint to keep the value for the specified key of link annotation under the threshold.
String key ()
Returns the key of link annotation this constraint designates.
double threshold ()
Returns the threshold this constraint ensures as link annotated value.
boolean isValid (Link link, LinkResourceService resourceService)
Returns true if the specified link satisfies the constraint.
double cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.constraint.BooleanConstraint
double cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
boolean validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
Detailed Description
Constraint that evaluates an arbitrary link annotated value is under the specified threshold.
Definition at line 31 of file AnnotationConstraint.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.constraint.AnnotationConstraint.AnnotationConstraint (String key, double threshold)
Creates a new constraint to keep the value for the specified key of link annotation under the threshold.
Parameters
key key of link annotation
threshold threshold value of the specified link annotation
Definition at line 43 of file AnnotationConstraint.java.
References org.onosproject.net.intent.constraint.AnnotationConstraint.key(), and org.onosproject.net.intent.constraint.AnnotationConstraint.threshold().
Member Function Documentation
double org.onosproject.net.intent.constraint.AnnotationConstraint.cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
Implements org.onosproject.net.intent.Constraint.
Definition at line 79 of file AnnotationConstraint.java.
References org.onosproject.net.intent.constraint.AnnotationConstraint.isValid(), and org.onosproject.net.intent.constraint.AnnotationConstraint.key().
Referenced by org.onosproject.net.intent.constraint.AnnotationConstraintTest.testLessThanThreshold(), and org.onosproject.net.intent.constraint.AnnotationConstraintTest.testMoreThanThreshold().
boolean org.onosproject.net.intent.constraint.AnnotationConstraint.equals (Object obj)
Definition at line 93 of file AnnotationConstraint.java.
int org.onosproject.net.intent.constraint.AnnotationConstraint.hashCode ()
Definition at line 88 of file AnnotationConstraint.java.
References org.onosproject.net.intent.constraint.AnnotationConstraint.key(), and org.onosproject.net.intent.constraint.AnnotationConstraint.threshold().
boolean org.onosproject.net.intent.constraint.AnnotationConstraint.isValid (Link link, LinkResourceService resourceService) virtual
Returns true if the specified link satisfies the constraint.
Parameters
link link to be validated
resourceService resource service for checking available link resources
Returns
true if link is viable
Implements org.onosproject.net.intent.constraint.BooleanConstraint.
Definition at line 72 of file AnnotationConstraint.java.
References org.onosproject.net.intent.constraint.AnnotationConstraint.key(), and org.onosproject.net.intent.constraint.AnnotationConstraint.threshold().
Referenced by org.onosproject.net.intent.constraint.AnnotationConstraint.cost(), org.onosproject.net.intent.constraint.AnnotationConstraintTest.testLessThanThreshold(), and org.onosproject.net.intent.constraint.AnnotationConstraintTest.testMoreThanThreshold().
String org.onosproject.net.intent.constraint.AnnotationConstraint.key ()
Returns the key of link annotation this constraint designates.
Returns
key of link annotation
Definition at line 58 of file AnnotationConstraint.java.
Referenced by org.onosproject.net.intent.constraint.AnnotationConstraint.AnnotationConstraint(), org.onosproject.net.intent.constraint.AnnotationConstraint.cost(), org.onosproject.net.intent.constraint.AnnotationConstraint.hashCode(), org.onosproject.net.intent.constraint.AnnotationConstraint.isValid(), and org.onosproject.net.intent.constraint.AnnotationConstraint.toString().
double org.onosproject.net.intent.constraint.AnnotationConstraint.threshold ()
Returns the threshold this constraint ensures as link annotated value.
Returns
threshold as link annotated value
Definition at line 67 of file AnnotationConstraint.java.
Referenced by org.onosproject.net.intent.constraint.AnnotationConstraint.AnnotationConstraint(), org.onosproject.net.intent.constraint.AnnotationConstraint.hashCode(), org.onosproject.net.intent.constraint.AnnotationConstraint.isValid(), and org.onosproject.net.intent.constraint.AnnotationConstraint.toString().
String org.onosproject.net.intent.constraint.AnnotationConstraint.toString ()
Definition at line 107 of file AnnotationConstraint.java.
References org.onosproject.net.intent.constraint.AnnotationConstraint.key(), and org.onosproject.net.intent.constraint.AnnotationConstraint.threshold().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/constraint/AnnotationConstraint.java