onos: org.onosproject.incubator.net.resource.label.LabelResourceRequest Class Reference
org.onosproject.incubator.net.resource.label.LabelResourceRequest Class Reference
Represents for a label request.
Classes
enum Type
Request type.
Public Member Functions
LabelResourceRequest (DeviceId deviceId, Type type, long applyNum, ImmutableSet< LabelResource > releaseCollection)
Creates LabelResourceRequest object.
DeviceId deviceId ()
Returns a device id.
Type type ()
Returns request type.
long applyNum ()
Returns apply label number.
Collection< LabelResource > releaseCollection ()
Returns the collection of release labels.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Represents for a label request.
Definition at line 31 of file LabelResourceRequest.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.resource.label.LabelResourceRequest.LabelResourceRequest (DeviceId deviceId, Type type, long applyNum, ImmutableSet< LabelResource > releaseCollection)
Creates LabelResourceRequest object.
Parameters
deviceId device identifier
type request type
applyNum apply the number of labels
releaseCollection Set of released label
Definition at line 45 of file LabelResourceRequest.java.
References org.onosproject.incubator.net.resource.label.LabelResourceRequest.applyNum(), org.onosproject.incubator.net.resource.label.LabelResourceRequest.deviceId(), org.onosproject.incubator.net.resource.label.LabelResourceRequest.releaseCollection(), and org.onosproject.incubator.net.resource.label.LabelResourceRequest.type().
Referenced by org.onosproject.incubator.net.resource.label.LabelResourceRequest.equals().
Member Function Documentation
long org.onosproject.incubator.net.resource.label.LabelResourceRequest.applyNum ()
Returns apply label number.
Returns
label number
Definition at line 74 of file LabelResourceRequest.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourceRequest.LabelResourceRequest().
DeviceId org.onosproject.incubator.net.resource.label.LabelResourceRequest.deviceId ()
Returns a device id.
Returns
DeviceId
Definition at line 58 of file LabelResourceRequest.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourceRequest.LabelResourceRequest(), and org.onosproject.incubator.net.resource.label.LabelResourceRequest.toString().
boolean org.onosproject.incubator.net.resource.label.LabelResourceRequest.equals (Object obj)
Definition at line 101 of file LabelResourceRequest.java.
References find-flow.deviceId, and org.onosproject.incubator.net.resource.label.LabelResourceRequest.LabelResourceRequest().
int org.onosproject.incubator.net.resource.label.LabelResourceRequest.hashCode ()
Definition at line 95 of file LabelResourceRequest.java.
References find-flow.deviceId.
Collection<LabelResource> org.onosproject.incubator.net.resource.label.LabelResourceRequest.releaseCollection ()
Returns the collection of release labels.
Returns
Collection of DefaultLabelResource
Definition at line 82 of file LabelResourceRequest.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourceRequest.LabelResourceRequest().
String org.onosproject.incubator.net.resource.label.LabelResourceRequest.toString ()
Definition at line 114 of file LabelResourceRequest.java.
References org.onosproject.incubator.net.resource.label.LabelResourceRequest.deviceId(), and org.onosproject.incubator.net.resource.label.LabelResourceRequest.type().
Type org.onosproject.incubator.net.resource.label.LabelResourceRequest.type ()
Returns request type.
Returns
Type
Definition at line 66 of file LabelResourceRequest.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourceRequest.LabelResourceRequest(), and org.onosproject.incubator.net.resource.label.LabelResourceRequest.toString().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/resource/label/LabelResourceRequest.java