onos: org.onosproject.net.group.DefaultGroupBucket Class Reference
org.onosproject.net.group.DefaultGroupBucket Class Reference
Group bucket implementation.
Public Member Functions
GroupDescription.Type type ()
Returns group type of the bucket.
TrafficTreatment treatment ()
Returns list of Traffic instructions that are part of the bucket.
short weight ()
Returns weight of select group bucket.
PortNumber watchPort ()
Returns port number used for liveness detection for a failover bucket.
GroupId watchGroup ()
Returns group identifier used for liveness detection for a failover bucket.
int hashCode ()
boolean equals (Object obj)
String toString ()
long packets ()
Returns the number of packets processed by this group bucket.
long bytes ()
Returns the number of bytes processed by this group bucket.
void setPackets (long packets)
Sets number of packets processed by this group bucket entry.
void setBytes (long bytes)
Sets number of bytes processed by this group bucket entry.
Static Public Member Functions
static GroupBucket createIndirectGroupBucket (TrafficTreatment treatment)
Creates indirect group bucket.
static GroupBucket createSelectGroupBucket (TrafficTreatment treatment)
Creates select group bucket with weight as 1.
static GroupBucket createSelectGroupBucket (TrafficTreatment treatment, short weight)
Creates select group bucket with specified weight.
static GroupBucket createFailoverGroupBucket (TrafficTreatment treatment, PortNumber watchPort, GroupId watchGroup)
Creates failover group bucket with watchport or watchgroup.
static GroupBucket createAllGroupBucket (TrafficTreatment treatment)
Creates all group bucket.
Detailed Description
Group bucket implementation.
A group bucket is collection of instructions that can be performed on a traffic flow. A select Group can have one or more Buckets where traffic will be processed by a single bucket in the group, based on device specific selection algorithm (e.g. hash on some fields of the incoming traffic flows or round robin) and hence can contains optional weight field to define the weights among the buckets in the group. A failover group bucket is associated with a specific port or group that controls its liveness.
Definition at line 41 of file DefaultGroupBucket.java.
Member Function Documentation
long org.onosproject.net.group.DefaultGroupBucket.bytes ()
Returns the number of bytes processed by this group bucket.
Returns
number of bytes
Implements org.onosproject.net.group.GroupBucket.
Definition at line 253 of file DefaultGroupBucket.java.
Referenced by org.onosproject.net.group.DefaultGroupBucket.setBytes(), and org.onosproject.net.group.DefaultGroupBucket.toString().
static GroupBucket org.onosproject.net.group.DefaultGroupBucket.createAllGroupBucket (TrafficTreatment treatment) static
Creates all group bucket.
Parameters
treatment traffic treatment associated with group bucket
Returns
all group bucket object
Definition at line 148 of file DefaultGroupBucket.java.
static GroupBucket org.onosproject.net.group.DefaultGroupBucket.createFailoverGroupBucket (TrafficTreatment treatment, PortNumber watchPort, GroupId watchGroup) static
Creates failover group bucket with watchport or watchgroup.
Parameters
treatment traffic treatment associated with group bucket
watchPort port that determines the liveness of group bucket
watchGroup group that determines the liveness of group bucket
Returns
failover group bucket object
Definition at line 130 of file DefaultGroupBucket.java.
static GroupBucket org.onosproject.net.group.DefaultGroupBucket.createIndirectGroupBucket (TrafficTreatment treatment) static
Creates indirect group bucket.
Parameters
treatment traffic treatment associated with group bucket
Returns
indirect group bucket object
Definition at line 77 of file DefaultGroupBucket.java.
static GroupBucket org.onosproject.net.group.DefaultGroupBucket.createSelectGroupBucket (TrafficTreatment treatment) static
Creates select group bucket with weight as 1.
Parameters
treatment traffic treatment associated with group bucket
Returns
select group bucket object
Definition at line 92 of file DefaultGroupBucket.java.
static GroupBucket org.onosproject.net.group.DefaultGroupBucket.createSelectGroupBucket (TrafficTreatment treatment, short weight) static
Creates select group bucket with specified weight.
Parameters
treatment traffic treatment associated with group bucket
weight weight associated with group bucket
Returns
select group bucket object
Definition at line 108 of file DefaultGroupBucket.java.
boolean org.onosproject.net.group.DefaultGroupBucket.equals (Object obj)
Definition at line 221 of file DefaultGroupBucket.java.
References org.onosproject.net.group.DefaultGroupBucket.type().
int org.onosproject.net.group.DefaultGroupBucket.hashCode ()
Definition at line 210 of file DefaultGroupBucket.java.
References org.onosproject.net.group.DefaultGroupBucket.treatment(), and org.onosproject.net.group.DefaultGroupBucket.type().
long org.onosproject.net.group.DefaultGroupBucket.packets ()
Returns the number of packets processed by this group bucket.
Returns
number of packets
Implements org.onosproject.net.group.GroupBucket.
Definition at line 248 of file DefaultGroupBucket.java.
Referenced by org.onosproject.net.group.DefaultGroupBucket.setPackets(), and org.onosproject.net.group.DefaultGroupBucket.toString().
void org.onosproject.net.group.DefaultGroupBucket.setBytes (long bytes)
Sets number of bytes processed by this group bucket entry.
Parameters
bytes a long value
Implements org.onosproject.net.group.StoredGroupBucketEntry.
Definition at line 263 of file DefaultGroupBucket.java.
References org.onosproject.net.group.DefaultGroupBucket.bytes().
void org.onosproject.net.group.DefaultGroupBucket.setPackets (long packets)
Sets number of packets processed by this group bucket entry.
Parameters
packets a long value
Implements org.onosproject.net.group.StoredGroupBucketEntry.
Definition at line 258 of file DefaultGroupBucket.java.
References org.onosproject.net.group.DefaultGroupBucket.packets().
String org.onosproject.net.group.DefaultGroupBucket.toString ()
Definition at line 238 of file DefaultGroupBucket.java.
References org.onosproject.net.group.DefaultGroupBucket.bytes(), org.onosproject.net.group.DefaultGroupBucket.packets(), and org.onosproject.net.group.DefaultGroupBucket.type().
TrafficTreatment org.onosproject.net.group.DefaultGroupBucket.treatment ()
Returns list of Traffic instructions that are part of the bucket.
Returns
TrafficTreatment Traffic instruction list
Implements org.onosproject.net.group.GroupBucket.
Definition at line 167 of file DefaultGroupBucket.java.
Referenced by org.onosproject.net.group.DefaultGroupBucket.hashCode().
GroupDescription.Type org.onosproject.net.group.DefaultGroupBucket.type ()
Returns group type of the bucket.
Returns
GroupType group type
Implements org.onosproject.net.group.GroupBucket.
Definition at line 157 of file DefaultGroupBucket.java.
Referenced by org.onosproject.net.group.DefaultGroupBucket.equals(), org.onosproject.net.group.DefaultGroupBucket.hashCode(), and org.onosproject.net.group.DefaultGroupBucket.toString().
GroupId org.onosproject.net.group.DefaultGroupBucket.watchGroup ()
Returns group identifier used for liveness detection for a failover bucket.
Returns
GroupId group identifier to be used for liveness detection
Implements org.onosproject.net.group.GroupBucket.
Definition at line 199 of file DefaultGroupBucket.java.
PortNumber org.onosproject.net.group.DefaultGroupBucket.watchPort ()
Returns port number used for liveness detection for a failover bucket.
Returns
PortNumber port number used for liveness detection
Implements org.onosproject.net.group.GroupBucket.
Definition at line 188 of file DefaultGroupBucket.java.
short org.onosproject.net.group.DefaultGroupBucket.weight ()
Returns weight of select group bucket.
Returns
short weight associated with a bucket
Implements org.onosproject.net.group.GroupBucket.
Definition at line 177 of file DefaultGroupBucket.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/group/DefaultGroupBucket.java