onos: org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4 Class Reference
org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4 Class Reference
Provides Pcep Nai Unnumbered Adjacency Ipv4.
Public Member Functions
PcepNaiUnnumberedAdjacencyIpv4 (int localNodeId, int localInterfaceId, int remoteNodeId, int remoteInterfaceId)
Constructor to initialize all the member variables.
byte getType ()
To get the ST type of the NAI information.
int write (ChannelBuffer bb)
To write the object information to channelBuffer.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static
PcepNaiUnnumberedAdjacencyIpv4 of (int localNodeId, int localInterfaceId, int remoteNodeId, int remoteInterfaceId)
Returns PCEP Nai Unnumbered Adjacency Ipv4 object.
static
PcepNaiUnnumberedAdjacencyIpv4 read (ChannelBuffer bb)
Reads from channel buffer and return object of PcepNAIUnnumberedAdjacencyIpv4.
Static Public Attributes
static final byte ST_TYPE = 0x05
draft-ietf-pce-segment-routing-03 section 5.3.2.
Detailed Description
Provides Pcep Nai Unnumbered Adjacency Ipv4.
Definition at line 28 of file PcepNaiUnnumberedAdjacencyIpv4.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.PcepNaiUnnumberedAdjacencyIpv4 (int localNodeId, int localInterfaceId, int remoteNodeId, int remoteInterfaceId)
Constructor to initialize all the member variables.
Parameters
localNodeId local node id
localInterfaceId local interface id
remoteNodeId remote node id
remoteInterfaceId remote interface id
Definition at line 47 of file PcepNaiUnnumberedAdjacencyIpv4.java.
Referenced by org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.equals(), org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.of(), and org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.equals (Object obj)
Definition at line 108 of file PcepNaiUnnumberedAdjacencyIpv4.java.
References org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.PcepNaiUnnumberedAdjacencyIpv4().
byte org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.getType ()
To get the ST type of the NAI information.
Returns
type of ST info
Implements org.onosproject.pcepio.protocol.PcepNai.
Definition at line 70 of file PcepNaiUnnumberedAdjacencyIpv4.java.
References org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.ST_TYPE.
int org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.hashCode ()
Definition at line 103 of file PcepNaiUnnumberedAdjacencyIpv4.java.
static PcepNaiUnnumberedAdjacencyIpv4 org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.of (int localNodeId, int localInterfaceId, int remoteNodeId, int remoteInterfaceId) static
Returns PCEP Nai Unnumbered Adjacency Ipv4 object.
Parameters
localNodeId local node id
localInterfaceId local interface if
remoteNodeId remote node id
remoteInterfaceId remote interface id
Returns
PCEP Nai Unnumbered Adjacency Ipv4 object
Definition at line 64 of file PcepNaiUnnumberedAdjacencyIpv4.java.
References org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.PcepNaiUnnumberedAdjacencyIpv4().
static PcepNaiUnnumberedAdjacencyIpv4 org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.read (ChannelBuffer bb) static
Reads from channel buffer and return object of PcepNAIUnnumberedAdjacencyIpv4.
Parameters
bb of type channel buffer
Returns
object of PcepNAIUnnumberedAdjacencyIpv4
Definition at line 90 of file PcepNaiUnnumberedAdjacencyIpv4.java.
References org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.PcepNaiUnnumberedAdjacencyIpv4().
String org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.toString ()
Definition at line 123 of file PcepNaiUnnumberedAdjacencyIpv4.java.
int org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.write (ChannelBuffer cb)
To write the object information to channelBuffer.
Parameters
cb of type channel buffer
Returns
length of written bytes.
Implements org.onosproject.pcepio.protocol.PcepNai.
Definition at line 75 of file PcepNaiUnnumberedAdjacencyIpv4.java.
Member Data Documentation
final byte org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.ST_TYPE = 0x05 static
draft-ietf-pce-segment-routing-03 section 5.3.2.
Definition at line 32 of file PcepNaiUnnumberedAdjacencyIpv4.java.
Referenced by org.onosproject.pcepio.types.PcepNaiUnnumberedAdjacencyIpv4.getType().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PcepNaiUnnumberedAdjacencyIpv4.java