onos: org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier Class Reference
org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier Class Reference
Provides Implementation of Local node descriptors and prefix descriptors.
Public Member Functions
BgpPrefixLSIdentifier ()
Resets parameters.
BgpPrefixLSIdentifier (NodeDescriptors localNodeDescriptors, List< BgpValueType > prefixDescriptor)
Constructor to initialize parameters.
NodeDescriptors getLocalNodeDescriptors ()
Returns local node descriptors.
List< BgpValueType > getPrefixdescriptor ()
Returns Prefix descriptors.
int hashCode ()
boolean equals (Object obj)
String toString ()
int compareTo (Object o)
Static Public Member Functions
static BgpPrefixLSIdentifier parsePrefixIdendifier (ChannelBuffer cb, byte protocolId) throws BgpParseException
Reads the channel buffer and parses Prefix Identifier.
static NodeDescriptors parseLocalNodeDescriptors (ChannelBuffer cb, byte protocolId) throws BgpParseException
Parse local node descriptors.
static List< BgpValueType > parsePrefixDescriptors (ChannelBuffer cb) throws BgpParseException
Parse list of prefix descriptors.
Static Public Attributes
static final int TYPE_AND_LEN = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(BgpPrefixLSIdentifier.class)
Detailed Description
Provides Implementation of Local node descriptors and prefix descriptors.
Definition at line 41 of file BgpPrefixLSIdentifier.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.BgpPrefixLSIdentifier ()
Resets parameters.
Definition at line 51 of file BgpPrefixLSIdentifier.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.compareTo(), org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.equals(), and org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parsePrefixIdendifier().
org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.BgpPrefixLSIdentifier (NodeDescriptors localNodeDescriptors, List< BgpValueType > prefixDescriptor)
Constructor to initialize parameters.
Parameters
localNodeDescriptors Local node descriptors
prefixDescriptor Prefix Descriptors
Definition at line 62 of file BgpPrefixLSIdentifier.java.
Member Function Documentation
int org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.compareTo (Object o)
Definition at line 236 of file BgpPrefixLSIdentifier.java.
References org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.BgpPrefixLSIdentifier(), and org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.equals().
boolean org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.equals (Object obj)
Definition at line 195 of file BgpPrefixLSIdentifier.java.
References org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.BgpPrefixLSIdentifier().
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.compareTo().
NodeDescriptors org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.getLocalNodeDescriptors ()
Returns local node descriptors.
Returns
local node descriptors
Definition at line 176 of file BgpPrefixLSIdentifier.java.
List<BgpValueType> org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.getPrefixdescriptor ()
Returns Prefix descriptors.
Returns
Prefix descriptors
Definition at line 185 of file BgpPrefixLSIdentifier.java.
int org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.hashCode ()
Definition at line 190 of file BgpPrefixLSIdentifier.java.
static NodeDescriptors org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parseLocalNodeDescriptors (ChannelBuffer cb, byte protocolId) throws BgpParseException static
Parse local node descriptors.
Parameters
cb ChannelBuffer
protocolId protocol identifier
Returns
LocalNodeDescriptors
Exceptions
BgpParseException while parsing local node descriptors
Definition at line 95 of file BgpPrefixLSIdentifier.java.
References find-link-in-cluster.length, org.onosproject.bgpio.protocol.linkstate.NodeDescriptors.LOCAL_NODE_DES_TYPE, org.onosproject.bgpio.types.BgpErrorType.MALFORMED_ATTRIBUTE_LIST, org.onosproject.bgpio.types.BgpErrorType.OPTIONAL_ATTRIBUTE_ERROR, org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.TYPE_AND_LEN, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parsePrefixIdendifier().
static List<BgpValueType> org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parsePrefixDescriptors (ChannelBuffer cb) throws BgpParseException static
Parse list of prefix descriptors.
Parameters
cb ChannelBuffer
Returns
list of prefix descriptors
Exceptions
BgpParseException while parsing list of prefix descriptors
Definition at line 124 of file BgpPrefixLSIdentifier.java.
References find-link-in-cluster.length, org.onosproject.bgpio.types.BgpErrorType.OPTIONAL_ATTRIBUTE_ERROR, org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.TYPE_AND_LEN, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parsePrefixIdendifier().
static BgpPrefixLSIdentifier org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parsePrefixIdendifier (ChannelBuffer cb, byte protocolId) throws BgpParseException static
Reads the channel buffer and parses Prefix Identifier.
Parameters
cb ChannelBuffer
protocolId protocol ID
Returns
object of this class
Exceptions
BgpParseException while parsing Prefix Identifier
Definition at line 75 of file BgpPrefixLSIdentifier.java.
References org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.BgpPrefixLSIdentifier(), org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parseLocalNodeDescriptors(), and org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parsePrefixDescriptors().
String org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.toString ()
Definition at line 228 of file BgpPrefixLSIdentifier.java.
Member Data Documentation
final Logger org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.log = LoggerFactory.getLogger(BgpPrefixLSIdentifier.class) static protected
Definition at line 43 of file BgpPrefixLSIdentifier.java.
final int org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.TYPE_AND_LEN = 4 static
Definition at line 44 of file BgpPrefixLSIdentifier.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parseLocalNodeDescriptors(), and org.onosproject.bgpio.protocol.linkstate.BgpPrefixLSIdentifier.parsePrefixDescriptors().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/protocol/linkstate/BgpPrefixLSIdentifier.java