onos: org.onlab.packet.ndp.RouterAdvertisementTest Class Reference
org.onlab.packet.ndp.RouterAdvertisementTest Class Reference
Tests for class RouterAdvertisement.
Public Member Functions
void testSerialize ()
Tests serialize and setters.
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws DeserializationException
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class RouterAdvertisement.
Definition at line 36 of file RouterAdvertisementTest.java.
Member Function Documentation
static void org.onlab.packet.ndp.RouterAdvertisementTest.setUpBeforeClass () throws Exception static
Definition at line 46 of file RouterAdvertisementTest.java.
References find-link-in-cluster.length.
void org.onlab.packet.ndp.RouterAdvertisementTest.testDeserialize () throws DeserializationException
Tests deserialize and getters.
Definition at line 94 of file RouterAdvertisementTest.java.
References org.onlab.packet.ndp.RouterAdvertisement.getCurrentHopLimit(), org.onlab.packet.ndp.RouterAdvertisement.getMFlag(), org.onlab.packet.ndp.RouterAdvertisement.getOFlag(), org.onlab.packet.ndp.RouterAdvertisement.getOptions(), org.onlab.packet.ndp.RouterAdvertisement.getReachableTime(), org.onlab.packet.ndp.RouterAdvertisement.getRetransmitTimer(), org.onlab.packet.ndp.RouterAdvertisement.getRouterLifetime(), find-link-in-cluster.length, and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
void org.onlab.packet.ndp.RouterAdvertisementTest.testDeserializeBadInput () throws Exception
Definition at line 77 of file RouterAdvertisementTest.java.
void org.onlab.packet.ndp.RouterAdvertisementTest.testDeserializeTruncated () throws Exception
Definition at line 82 of file RouterAdvertisementTest.java.
References org.onlab.packet.ndp.RouterAdvertisement.HEADER_LENGTH.
void org.onlab.packet.ndp.RouterAdvertisementTest.testEqual ()
Tests comparator.
Definition at line 116 of file RouterAdvertisementTest.java.
References org.onlab.packet.ndp.RouterAdvertisement.equals(), and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
void org.onlab.packet.ndp.RouterAdvertisementTest.testSerialize ()
Tests serialize and setters.
Definition at line 62 of file RouterAdvertisementTest.java.
References org.onlab.packet.ndp.RouterAdvertisement.serialize(), and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ndp/RouterAdvertisementTest.java