onos: org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag Class Reference
org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag Class Reference
Implements BGP prefix route Extended tag attribute.
Public Member Functions
BgpPrefixAttrExtRouteTag (List< Long > pfxExtRouteTag)
Constructor to initialize the values.
List< Long > pfxExtRouteTag ()
Returns Extended route tag.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpPrefixAttrExtRouteTag of (ArrayList< Long > pfxExtRouteTag)
Returns object of this class with specified values.
static BgpPrefixAttrExtRouteTag read (ChannelBuffer cb) throws BgpParseException
Reads the Extended Tag.
Static Public Attributes
static final int ATTR_PREFIX_EXTROUTETAG = 1154
static final int ATTR_PREFIX_EXT_LEN = 8
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP prefix route Extended tag attribute.
Definition at line 37 of file BgpPrefixAttrExtRouteTag.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.BgpPrefixAttrExtRouteTag (List< Long > pfxExtRouteTag)
Constructor to initialize the values.
Parameters
pfxExtRouteTag Extended route tag
Definition at line 53 of file BgpPrefixAttrExtRouteTag.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.equals(), org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.of(), and org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.read().
Member Function Documentation
int org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 141 of file BgpPrefixAttrExtRouteTag.java.
boolean org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.equals (Object obj)
Definition at line 116 of file BgpPrefixAttrExtRouteTag.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.BgpPrefixAttrExtRouteTag(), and org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.pfxExtRouteTag().
short org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 106 of file BgpPrefixAttrExtRouteTag.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.ATTR_PREFIX_EXTROUTETAG.
int org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.hashCode ()
Definition at line 111 of file BgpPrefixAttrExtRouteTag.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.pfxExtRouteTag().
static BgpPrefixAttrExtRouteTag org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.of (ArrayList< Long > pfxExtRouteTag) static
Returns object of this class with specified values.
Parameters
pfxExtRouteTag Prefix Metric
Returns
object of BgpPrefixAttrMetric
Definition at line 63 of file BgpPrefixAttrExtRouteTag.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.BgpPrefixAttrExtRouteTag().
List<Long> org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.pfxExtRouteTag ()
Returns Extended route tag.
Returns
route tag
Definition at line 101 of file BgpPrefixAttrExtRouteTag.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.equals(), org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.hashCode(), org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.read(), and org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.toString().
static BgpPrefixAttrExtRouteTag org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.read (ChannelBuffer cb) throws BgpParseException static
Reads the Extended Tag.
Parameters
cb ChannelBuffer
Returns
object of BgpPrefixAttrExtRouteTag
Exceptions
BgpParseException while parsing BgpPrefixAttrExtRouteTag
Definition at line 74 of file BgpPrefixAttrExtRouteTag.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.ATTR_PREFIX_EXT_LEN, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.BgpPrefixAttrExtRouteTag(), org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.pfxExtRouteTag(), and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.toString ()
Definition at line 135 of file BgpPrefixAttrExtRouteTag.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.pfxExtRouteTag().
int org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 129 of file BgpPrefixAttrExtRouteTag.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.ATTR_PREFIX_EXT_LEN = 8 static
Definition at line 43 of file BgpPrefixAttrExtRouteTag.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.read().
final int org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.ATTR_PREFIX_EXTROUTETAG = 1154 static
Definition at line 42 of file BgpPrefixAttrExtRouteTag.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.getType().
final Logger org.onosproject.bgpio.types.attr.BgpPrefixAttrExtRouteTag.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpPrefixAttrExtRouteTag.class)
Definition at line 39 of file BgpPrefixAttrExtRouteTag.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpPrefixAttrExtRouteTag.java