onos: org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv Class Reference
org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv Class Reference
Provides IPv4 TE Router Id Of Local Node.
Public Member Functions
IPv4TERouterIdOfLocalNodeTlv (int rawValue)
Constructor to initialize rawValue.
int getInt ()
Returns value of IPv4 TE Router Id Of Local Node.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static IPv4TERouterIdOfLocalNodeTlv of (final int raw)
Returns newly created IPv4TERouterIdOfLocalNodeTlv object.
static IPv4TERouterIdOfLocalNodeTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of IPv4TERouterIdOfLocalNodeTlv.
Static Public Attributes
static final short TYPE = 134
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IPv4TERouterIdOfLocalNodeTlv.class)
Detailed Description
Provides IPv4 TE Router Id Of Local Node.
Definition at line 30 of file IPv4TERouterIdOfLocalNodeTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.IPv4TERouterIdOfLocalNodeTlv (int rawValue)
Constructor to initialize rawValue.
Parameters
rawValue IPv4-TE-RouterId-Of-Local-Node-Tlv
Definition at line 54 of file IPv4TERouterIdOfLocalNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.equals(), and org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.equals (Object obj)
Definition at line 98 of file IPv4TERouterIdOfLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.IPv4TERouterIdOfLocalNodeTlv().
int org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.getInt ()
Returns value of IPv4 TE Router Id Of Local Node.
Returns
rawValue IPv4 TE Router Id Of Local Node
Definition at line 73 of file IPv4TERouterIdOfLocalNodeTlv.java.
short org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 88 of file IPv4TERouterIdOfLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.LENGTH.
short org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 83 of file IPv4TERouterIdOfLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 78 of file IPv4TERouterIdOfLocalNodeTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.hashCode ()
Definition at line 93 of file IPv4TERouterIdOfLocalNodeTlv.java.
static IPv4TERouterIdOfLocalNodeTlv org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.of (final int raw) static
Returns newly created IPv4TERouterIdOfLocalNodeTlv object.
Parameters
raw value of IPv4-TE-RouterId-Of-Local-Node
Returns
object of IPv4TERouterIdOfLocalNodeTlv
Definition at line 64 of file IPv4TERouterIdOfLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.IPv4TERouterIdOfLocalNodeTlv().
static IPv4TERouterIdOfLocalNodeTlv org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of IPv4TERouterIdOfLocalNodeTlv.
Parameters
c input channel buffer
Returns
object of IPv4TERouterIdOfLocalNodeTlv
Definition at line 124 of file IPv4TERouterIdOfLocalNodeTlv.java.
String org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.toString ()
Definition at line 129 of file IPv4TERouterIdOfLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.LENGTH, and org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.TYPE.
int org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 110 of file IPv4TERouterIdOfLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.LENGTH, and org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.LENGTH = 4 static
Definition at line 45 of file IPv4TERouterIdOfLocalNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.getLength(), org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.toString(), and org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.write().
final Logger org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.log = LoggerFactory.getLogger(IPv4TERouterIdOfLocalNodeTlv.class) static protected
Definition at line 42 of file IPv4TERouterIdOfLocalNodeTlv.java.
final short org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.TYPE = 134 static
Definition at line 44 of file IPv4TERouterIdOfLocalNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.getType(), org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.toString(), and org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IPv4TERouterIdOfLocalNodeTlv.java