onos: org.onosproject.store.consistent.impl.DistributedLeadershipManager Class Reference
org.onosproject.store.consistent.impl.DistributedLeadershipManager Class Reference
Distributed Lock Manager implemented on top of ConsistentMap.
Public Member Functions
void activate ()
void deactivate ()
Map< String, Leadership > getLeaderBoard ()
Returns the current leader board.
Map< String, List< NodeId > > getCandidates ()
Returns the candidates for all known topics.
List< NodeId > getCandidates (String path)
Returns the candidates for a given topic.
NodeId getLeader (String path)
Returns the current leader for the topic.
Leadership getLeadership (String path)
Returns the current leadership info for the topic.
Set< String > ownedTopics (NodeId nodeId)
Returns the set of topics owned by the specified node.
CompletableFuture< Leadership > runForLeadership (String path)
Joins the leadership contest.
CompletableFuture< Void > withdraw (String path)
Withdraws from a leadership contest.
boolean stepdown (String path)
If the local nodeId is the leader for specified topic, this method causes it to step down temporarily from leadership.
void addListener (LeadershipEventListener listener)
void removeListener (LeadershipEventListener listener)
boolean makeTopCandidate (String path, NodeId nodeId)
Moves the specified nodeId to the top of the candidates list for the topic.
Protected Attributes
StorageService storageService
ClusterService clusterService
ClusterCommunicationService clusterCommunicator
EventDeliveryService eventDispatcher
Detailed Description
Distributed Lock Manager implemented on top of ConsistentMap.
This implementation makes use of ClusterService's failure detection capabilities to detect and purge stale locks. TODO: Ensure lock safety and liveness.
Definition at line 84 of file DistributedLeadershipManager.java.
Member Function Documentation
void org.onosproject.store.consistent.impl.DistributedLeadershipManager.activate ()
Definition at line 127 of file DistributedLeadershipManager.java.
void org.onosproject.store.consistent.impl.DistributedLeadershipManager.addListener (LeadershipEventListener listener)
Definition at line 334 of file DistributedLeadershipManager.java.
void org.onosproject.store.consistent.impl.DistributedLeadershipManager.deactivate ()
Definition at line 193 of file DistributedLeadershipManager.java.
References org.onosproject.store.consistent.impl.DistributedLeadershipManager.clusterService, org.onosproject.cluster.NodeId.equals(), org.onosproject.cluster.ClusterService.getNodes(), and org.onosproject.store.consistent.impl.DistributedLeadershipManager.withdraw().
Map<String, List<NodeId> > org.onosproject.store.consistent.impl.DistributedLeadershipManager.getCandidates ()
Returns the candidates for all known topics.
Returns
A mapping from topics to corresponding list of candidates.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 220 of file DistributedLeadershipManager.java.
List<NodeId> org.onosproject.store.consistent.impl.DistributedLeadershipManager.getCandidates (String path)
Returns the candidates for a given topic.
Parameters
path topic
Returns
A lists of NodeIds, which may be empty.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 225 of file DistributedLeadershipManager.java.
NodeId org.onosproject.store.consistent.impl.DistributedLeadershipManager.getLeader (String path)
Returns the current leader for the topic.
Parameters
path topic
Returns
nodeId of the leader, null if so such topic exists.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 231 of file DistributedLeadershipManager.java.
Referenced by org.onosproject.store.consistent.impl.DistributedLeadershipManager.stepdown().
Map<String, Leadership> org.onosproject.store.consistent.impl.DistributedLeadershipManager.getLeaderBoard ()
Returns the current leader board.
Returns
mapping from topic to leadership info.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 215 of file DistributedLeadershipManager.java.
Leadership org.onosproject.store.consistent.impl.DistributedLeadershipManager.getLeadership (String path)
Returns the current leadership info for the topic.
Parameters
path topic
Returns
leadership info or null if so such topic exists.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 237 of file DistributedLeadershipManager.java.
boolean org.onosproject.store.consistent.impl.DistributedLeadershipManager.makeTopCandidate (String path, NodeId nodeId)
Moves the specified nodeId to the top of the candidates list for the topic.
If the node is not a candidate for this topic, this method will be a noop.
Parameters
path leadership topic
nodeId nodeId to make the top candidate
Returns
true if nodeId is now the top candidate, false otherwise
Implements org.onosproject.cluster.LeadershipService.
Definition at line 344 of file DistributedLeadershipManager.java.
References org.onosproject.cluster.NodeId.equals().
Set<String> org.onosproject.store.consistent.impl.DistributedLeadershipManager.ownedTopics (NodeId nodeId)
Returns the set of topics owned by the specified node.
Parameters
nodeId node Id.
Returns
set of topics for which this node is the current leader.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 243 of file DistributedLeadershipManager.java.
void org.onosproject.store.consistent.impl.DistributedLeadershipManager.removeListener (LeadershipEventListener listener)
Definition at line 339 of file DistributedLeadershipManager.java.
CompletableFuture<Leadership> org.onosproject.store.consistent.impl.DistributedLeadershipManager.runForLeadership (String path)
Joins the leadership contest.
Parameters
path topic for which this controller node wishes to be a leader
Returns
Leadership
future
Implements org.onosproject.cluster.LeadershipService.
Definition at line 253 of file DistributedLeadershipManager.java.
boolean org.onosproject.store.consistent.impl.DistributedLeadershipManager.stepdown (String path)
If the local nodeId is the leader for specified topic, this method causes it to step down temporarily from leadership.
The node will continue to be in contention for leadership and can potentially become the leader again if and when it becomes the highest priority candidate
If the local nodeId is not the leader, this method will make no changes and simply return false.
Parameters
path topic for which this controller node should give up leadership
Returns
true if this node stepped down from leadership, false otherwise
Implements org.onosproject.cluster.LeadershipService.
Definition at line 318 of file DistributedLeadershipManager.java.
References org.onosproject.store.consistent.impl.DistributedLeadershipManager.getLeader().
CompletableFuture<Void> org.onosproject.store.consistent.impl.DistributedLeadershipManager.withdraw (String path)
Withdraws from a leadership contest.
Parameters
path topic for which this controller node no longer wishes to be a leader
Returns
future that is successfully completed when withdraw is done
Implements org.onosproject.cluster.LeadershipService.
Definition at line 289 of file DistributedLeadershipManager.java.
Referenced by org.onosproject.store.consistent.impl.DistributedLeadershipManager.deactivate().
Member Data Documentation
ClusterCommunicationService org.onosproject.store.consistent.impl.DistributedLeadershipManager.clusterCommunicator protected
Definition at line 93 of file DistributedLeadershipManager.java.
ClusterService org.onosproject.store.consistent.impl.DistributedLeadershipManager.clusterService protected
Definition at line 90 of file DistributedLeadershipManager.java.
Referenced by org.onosproject.store.consistent.impl.DistributedLeadershipManager.deactivate().
EventDeliveryService org.onosproject.store.consistent.impl.DistributedLeadershipManager.eventDispatcher protected
Definition at line 96 of file DistributedLeadershipManager.java.
StorageService org.onosproject.store.consistent.impl.DistributedLeadershipManager.storageService protected
Definition at line 87 of file DistributedLeadershipManager.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DistributedLeadershipManager.java