onos: org.onosproject.store.device.impl.InternalDeviceEvent Class Reference
org.onosproject.store.device.impl.InternalDeviceEvent Class Reference
Information published by GossipDeviceStore to notify peers of a device change event.
Public Member Functions
DeviceId deviceId ()
ProviderId providerId ()
Timestamped< DeviceDescription > deviceDescription ()
String toString ()
Protected Member Functions
InternalDeviceEvent (ProviderId providerId, DeviceId deviceId, Timestamped< DeviceDescription > deviceDescription)
InternalDeviceEvent ()
Detailed Description
Information published by GossipDeviceStore to notify peers of a device change event.
Definition at line 29 of file InternalDeviceEvent.java.
Constructor & Destructor Documentation
org.onosproject.store.device.impl.InternalDeviceEvent.InternalDeviceEvent (ProviderId providerId, DeviceId deviceId, Timestamped< DeviceDescription > deviceDescription) protected
Definition at line 35 of file InternalDeviceEvent.java.
References org.onosproject.store.device.impl.InternalDeviceEvent.deviceDescription(), org.onosproject.store.device.impl.InternalDeviceEvent.deviceId(), and org.onosproject.store.device.impl.InternalDeviceEvent.providerId().
org.onosproject.store.device.impl.InternalDeviceEvent.InternalDeviceEvent () protected
Definition at line 66 of file InternalDeviceEvent.java.
Member Function Documentation
Timestamped<DeviceDescription> org.onosproject.store.device.impl.InternalDeviceEvent.deviceDescription ()
Definition at line 52 of file InternalDeviceEvent.java.
Referenced by org.onosproject.store.device.impl.InternalDeviceEvent.InternalDeviceEvent(), and org.onosproject.store.device.impl.InternalDeviceEvent.toString().
DeviceId org.onosproject.store.device.impl.InternalDeviceEvent.deviceId ()
Definition at line 44 of file InternalDeviceEvent.java.
Referenced by org.onosproject.store.device.impl.InternalDeviceEvent.InternalDeviceEvent(), and org.onosproject.store.device.impl.InternalDeviceEvent.toString().
ProviderId org.onosproject.store.device.impl.InternalDeviceEvent.providerId ()
Definition at line 48 of file InternalDeviceEvent.java.
Referenced by org.onosproject.store.device.impl.InternalDeviceEvent.InternalDeviceEvent(), and org.onosproject.store.device.impl.InternalDeviceEvent.toString().
String org.onosproject.store.device.impl.InternalDeviceEvent.toString ()
Definition at line 57 of file InternalDeviceEvent.java.
References org.onosproject.store.device.impl.InternalDeviceEvent.deviceDescription(), org.onosproject.store.device.impl.InternalDeviceEvent.deviceId(), and org.onosproject.store.device.impl.InternalDeviceEvent.providerId().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/device/impl/InternalDeviceEvent.java