onos: org.onosproject.store.intent.impl.PartitionManager Class Reference
org.onosproject.store.intent.impl.PartitionManager Class Reference
Manages the assignment of intent keyspace partitions to instances.
Public Member Functions
void activate ()
void deactivate ()
PartitionManager withScheduledExecutor (ScheduledExecutorService executor)
Sets the specified executor to be used for scheduling background tasks.
boolean isMine (Key intentKey)
Returns whether the given intent key is in a partition owned by this instance or not.
NodeId getLeader (Key intentKey)
Returns the leader for a particular key.
void addListener (PartitionEventListener listener)
void removeListener (PartitionEventListener listener)
Protected Member Functions
void doRebalance ()
Protected Attributes
LeadershipService leadershipService
ClusterService clusterService
EventDeliveryService eventDispatcher
final AtomicBoolean rebalanceScheduled = new AtomicBoolean(false)
Detailed Description
Manages the assignment of intent keyspace partitions to instances.
Definition at line 55 of file PartitionManager.java.
Member Function Documentation
void org.onosproject.store.intent.impl.PartitionManager.activate ()
Definition at line 85 of file PartitionManager.java.
void org.onosproject.store.intent.impl.PartitionManager.addListener (PartitionEventListener listener)
Definition at line 149 of file PartitionManager.java.
void org.onosproject.store.intent.impl.PartitionManager.deactivate ()
Definition at line 101 of file PartitionManager.java.
void org.onosproject.store.intent.impl.PartitionManager.doRebalance () protected
Definition at line 158 of file PartitionManager.java.
NodeId org.onosproject.store.intent.impl.PartitionManager.getLeader (Key intentKey)
Returns the leader for a particular key.
Parameters
intentKey intent key to query
Returns
the leader node
Implements org.onosproject.net.intent.PartitionService.
Definition at line 144 of file PartitionManager.java.
boolean org.onosproject.store.intent.impl.PartitionManager.isMine (Key intentKey)
Returns whether the given intent key is in a partition owned by this instance or not.
Parameters
intentKey intent key to query
Returns
true if the key is owned by this instance, otherwise false
Implements org.onosproject.net.intent.PartitionService.
Definition at line 138 of file PartitionManager.java.
References org.onosproject.store.intent.impl.PartitionManager.clusterService, and org.onosproject.cluster.ClusterService.getLocalNode().
Referenced by org.onosproject.store.intent.impl.PartitionManagerTest.testIsMine().
void org.onosproject.store.intent.impl.PartitionManager.removeListener (PartitionEventListener listener)
Definition at line 154 of file PartitionManager.java.
PartitionManager org.onosproject.store.intent.impl.PartitionManager.withScheduledExecutor (ScheduledExecutorService executor)
Sets the specified executor to be used for scheduling background tasks.
Parameters
executor scheduled executor service for background tasks
Returns
this PartitionManager
Definition at line 115 of file PartitionManager.java.
Member Data Documentation
ClusterService org.onosproject.store.intent.impl.PartitionManager.clusterService protected
Definition at line 63 of file PartitionManager.java.
Referenced by org.onosproject.store.intent.impl.PartitionManager.isMine().
EventDeliveryService org.onosproject.store.intent.impl.PartitionManager.eventDispatcher protected
Definition at line 66 of file PartitionManager.java.
LeadershipService org.onosproject.store.intent.impl.PartitionManager.leadershipService protected
Definition at line 60 of file PartitionManager.java.
final AtomicBoolean org.onosproject.store.intent.impl.PartitionManager.rebalanceScheduled = new AtomicBoolean(false) protected
Definition at line 68 of file PartitionManager.java.
Referenced by org.onosproject.store.intent.impl.PartitionManagerTest.testRebalanceScheduling().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/intent/impl/PartitionManager.java