onos: org.onlab.packet.ONOSLLDP Class Reference
org.onlab.packet.ONOSLLDP Class Reference
ONOS LLDP containing organizational TLV for ONOS device dicovery.
Public Member Functions
ONOSLLDP ()
void setName (String name)
void setDevice (String device)
void setChassisId (final ChassisId chassisId)
void setPortId (final int portNumber)
LLDPOrganizationalTLV getNameTLV ()
LLDPOrganizationalTLV getDeviceTLV ()
String getNameString ()
String getDeviceString ()
Integer getPort ()
Public Member Functions inherited from org.onlab.packet.LLDP
LLDP ()
LLDPTLV getChassisId ()
LLDP setChassisId (final LLDPTLV chassis)
LLDPTLV getPortId ()
LLDP setPortId (final LLDPTLV portId)
LLDPTLV getTtl ()
LLDP setTtl (final LLDPTLV ttl)
List< LLDPTLV > getOptionalTLVList ()
LLDP setOptionalTLVList (final List< LLDPTLV > optionalTLVList)
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (final byte[] data, final int offset, final int length)
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
Static Public Member Functions
static ONOSLLDP parseONOSLLDP (Ethernet eth)
Given an ethernet packet, determines if this is an LLDP from ONOS and returns the device the LLDP came from.
Static Public Member Functions inherited from org.onlab.packet.LLDP
static Deserializer< LLDP > deserializer ()
Deserializer function for LLDP packets.
Static Public Attributes
static final byte[] ONLAB_OUI = {(byte) 0xa4, 0x23, 0x05}
static final String DEFAULT_DEVICE = "INVALID"
static final String DEFAULT_NAME = "ONOS Discovery"
static final byte[] LLDP_NICIRA
static final byte[] LLDP_MULTICAST
static final byte[] BDDP_MULTICAST
Static Public Attributes inherited from org.onlab.packet.LLDP
static final byte CHASSIS_TLV_TYPE = 1
static final short CHASSIS_TLV_SIZE = 7
static final byte CHASSIS_TLV_SUBTYPE = 4
static final byte PORT_TLV_TYPE = 2
static final short PORT_TLV_SIZE = 5
static final byte PORT_TLV_SUBTYPE = 2
static final byte TTL_TLV_TYPE = 3
static final short TTL_TLV_SIZE = 2
Additional Inherited Members
Protected Attributes inherited from org.onlab.packet.LLDP
LLDPTLV chassisId
LLDPTLV portId
LLDPTLV ttl
List< LLDPTLV > optionalTLVList
short ethType
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
ONOS LLDP containing organizational TLV for ONOS device dicovery.
Definition at line 27 of file ONOSLLDP.java.
Constructor & Destructor Documentation
org.onlab.packet.ONOSLLDP.ONOSLLDP ()
Definition at line 63 of file ONOSLLDP.java.
References org.onlab.packet.ONOSLLDP.setDevice(), org.onlab.packet.ONOSLLDP.setName(), org.onlab.packet.LLDP.setOptionalTLVList(), org.onlab.packet.LLDP.setTtl(), and org.onlab.packet.LLDPTLV.setValue().
Referenced by org.onlab.packet.ONOSLLDP.parseONOSLLDP().
Member Function Documentation
String org.onlab.packet.ONOSLLDP.getDeviceString ()
Definition at line 150 of file ONOSLLDP.java.
References org.onlab.packet.ONOSLLDP.getDeviceTLV(), and org.onlab.packet.LLDPOrganizationalTLV.getInfoString().
LLDPOrganizationalTLV org.onlab.packet.ONOSLLDP.getDeviceTLV ()
Definition at line 130 of file ONOSLLDP.java.
References org.onlab.packet.LLDP.getOptionalTLVList(), org.onlab.packet.LLDPOrganizationalTLV.getSubType(), and org.onlab.packet.LLDPOrganizationalTLV.ORGANIZATIONAL_TLV_TYPE.
Referenced by org.onlab.packet.ONOSLLDP.getDeviceString().
String org.onlab.packet.ONOSLLDP.getNameString ()
Definition at line 142 of file ONOSLLDP.java.
References org.onlab.packet.LLDPOrganizationalTLV.getInfoString(), and org.onlab.packet.ONOSLLDP.getNameTLV().
Referenced by org.onlab.packet.ONOSLLDP.parseONOSLLDP().
LLDPOrganizationalTLV org.onlab.packet.ONOSLLDP.getNameTLV ()
Definition at line 118 of file ONOSLLDP.java.
References org.onlab.packet.LLDP.getOptionalTLVList(), org.onlab.packet.LLDPOrganizationalTLV.getSubType(), and org.onlab.packet.LLDPOrganizationalTLV.ORGANIZATIONAL_TLV_TYPE.
Referenced by org.onlab.packet.ONOSLLDP.getNameString().
Integer org.onlab.packet.ONOSLLDP.getPort ()
Definition at line 158 of file ONOSLLDP.java.
static ONOSLLDP org.onlab.packet.ONOSLLDP.parseONOSLLDP (Ethernet eth) static
Given an ethernet packet, determines if this is an LLDP from ONOS and returns the device the LLDP came from.
Parameters
eth an ethernet packet
Returns
a the lldp packet or null
Definition at line 170 of file ONOSLLDP.java.
References org.onlab.packet.ONOSLLDP.DEFAULT_NAME, org.onlab.packet.Ethernet.getEtherType(), org.onlab.packet.ONOSLLDP.getNameString(), org.onlab.packet.BasePacket.getPayload(), org.onlab.packet.ONOSLLDP.ONOSLLDP(), and org.onlab.packet.Ethernet.TYPE_BSN.
void org.onlab.packet.ONOSLLDP.setChassisId (final ChassisId chassisId)
Definition at line 95 of file ONOSLLDP.java.
void org.onlab.packet.ONOSLLDP.setDevice (String device)
Definition at line 88 of file ONOSLLDP.java.
References create-flow.device, and org.onlab.packet.ONOSLLDP.ONLAB_OUI.
Referenced by org.onlab.packet.ONOSLLDP.ONOSLLDP().
void org.onlab.packet.ONOSLLDP.setName (String name)
Definition at line 81 of file ONOSLLDP.java.
References create-flow.name, and org.onlab.packet.ONOSLLDP.ONLAB_OUI.
Referenced by org.onlab.packet.ONOSLLDP.ONOSLLDP().
void org.onlab.packet.ONOSLLDP.setPortId (final int portNumber)
Definition at line 107 of file ONOSLLDP.java.
References obeliskHostCheck.port.
Member Data Documentation
final byte [] org.onlab.packet.ONOSLLDP.BDDP_MULTICAST static
Initial value:
= {(byte) 0xff, (byte) 0xff,
            (byte) 0xff, (byte) 0xff, (byte) 0xff, (byte) 0xff}
Definition at line 37 of file ONOSLLDP.java.
final String org.onlab.packet.ONOSLLDP.DEFAULT_DEVICE = "INVALID" static
Definition at line 30 of file ONOSLLDP.java.
final String org.onlab.packet.ONOSLLDP.DEFAULT_NAME = "ONOS Discovery" static
Definition at line 31 of file ONOSLLDP.java.
Referenced by org.onlab.packet.ONOSLLDP.parseONOSLLDP().
final byte [] org.onlab.packet.ONOSLLDP.LLDP_MULTICAST static
Initial value:
= {0x01, (byte) 0x80,
            (byte) 0xc2, 0x00, 0x00, 0x0e}
Definition at line 35 of file ONOSLLDP.java.
final byte [] org.onlab.packet.ONOSLLDP.LLDP_NICIRA static
Initial value:
= {0x01, 0x23, 0x20, 0x00, 0x00,
            0x01}
Definition at line 33 of file ONOSLLDP.java.
final byte [] org.onlab.packet.ONOSLLDP.ONLAB_OUI = {(byte) 0xa4, 0x23, 0x05} static
Definition at line 29 of file ONOSLLDP.java.
Referenced by org.onlab.packet.ONOSLLDP.setDevice(), and org.onlab.packet.ONOSLLDP.setName().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ONOSLLDP.java