onos: org.onosproject.net.flow.impl.FlowRuleManager Class Reference
org.onosproject.net.flow.impl.FlowRuleManager Class Reference
Provides implementation of the flow NB & SB APIs.
Public Member Functions
void activate (ComponentContext context)
void deactivate ()
void modified (ComponentContext context)
int getFlowRuleCount ()
Returns the number of flow rules in the system.
Iterable< FlowEntry > getFlowEntries (DeviceId deviceId)
Returns the collection of flow entries applied on the specified device.
void applyFlowRules (FlowRule...flowRules)
Applies the specified flow rules onto their respective devices.
void removeFlowRules (FlowRule...flowRules)
Removes the specified flow rules from their respective devices.
void removeFlowRulesById (ApplicationId id)
Removes all rules by id.
Iterable< FlowRule > getFlowRulesById (ApplicationId id)
Returns a list of rules with this application id.
Iterable< FlowRule > getFlowRulesByGroupId (ApplicationId appId, short groupId)
Returns a list of rules filterd by application and group id.
void apply (FlowRuleOperations ops)
Applies a batch operation of FlowRules.
Iterable< TableStatisticsEntry > getFlowTableStatistics (DeviceId deviceId)
Returns the collection of flow table statistics of the specified device.
Static Public Attributes
static final String FLOW_RULE_NULL = "FlowRule cannot be null"
Protected Member Functions
FlowRuleProviderService createProviderService (FlowRuleProvider provider)
Protected Attributes
ExecutorService deviceInstallers
ExecutorService operationsService
FlowRuleStore store
DeviceService deviceService
CoreService coreService
ComponentConfigService cfgService
Additional Inherited Members
Public Attributes inherited from org.onosproject.net.flow.FlowRuleService
String FLOW_OP_TOPIC = "flow-ops-ids"
The topic used for obtaining globally unique ids.
Detailed Description
Provides implementation of the flow NB & SB APIs.
Definition at line 92 of file FlowRuleManager.java.
Member Function Documentation
void org.onosproject.net.flow.impl.FlowRuleManager.activate (ComponentContext context)
Definition at line 132 of file FlowRuleManager.java.
References org.onosproject.net.flow.FlowRuleService.FLOW_OP_TOPIC, and org.onosproject.net.flow.impl.FlowRuleManager.modified().
void org.onosproject.net.flow.impl.FlowRuleManager.apply (FlowRuleOperations ops)
Applies a batch operation of FlowRules.
Parameters
ops batch operation to apply
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 241 of file FlowRuleManager.java.
Referenced by org.onosproject.net.flow.impl.FlowRuleManager.applyFlowRules(), and org.onosproject.net.flow.impl.FlowRuleManager.removeFlowRules().
void org.onosproject.net.flow.impl.FlowRuleManager.applyFlowRules (FlowRule... flowRules)
Applies the specified flow rules onto their respective devices.
These flow rules will be retained by the system and re-applied anytime the device reconnects to the controller.
Parameters
flowRules one or more flow rules
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 182 of file FlowRuleManager.java.
References org.onosproject.net.flow.impl.FlowRuleManager.apply(), and find-link-in-cluster.length.
FlowRuleProviderService org.onosproject.net.flow.impl.FlowRuleManager.createProviderService (FlowRuleProvider provider) protected
Definition at line 247 of file FlowRuleManager.java.
void org.onosproject.net.flow.impl.FlowRuleManager.deactivate ()
Definition at line 144 of file FlowRuleManager.java.
Iterable<FlowEntry> org.onosproject.net.flow.impl.FlowRuleManager.getFlowEntries (DeviceId deviceId)
Returns the collection of flow entries applied on the specified device.
This will include flow rules which may not yet have been applied to the device.
Parameters
deviceId device identifier
Returns
collection of flow rules
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 176 of file FlowRuleManager.java.
References find-flow.deviceId.
int org.onosproject.net.flow.impl.FlowRuleManager.getFlowRuleCount ()
Returns the number of flow rules in the system.
Returns
flow rule count
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 170 of file FlowRuleManager.java.
Iterable<FlowRule> org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesByGroupId (ApplicationId appId, short groupId)
Returns a list of rules filterd by application and group id.
Parameters
appId the application id to lookup
groupId the groupid to lookup
Returns
collection of flow rules
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 225 of file FlowRuleManager.java.
References org.onosproject.net.flow.impl.FlowRuleManager.deviceService, org.onosproject.net.device.DeviceService.getDevices(), org.onosproject.net.flow.FlowRuleStore.getFlowEntries(), org.onosproject.core.ApplicationId.id(), and org.onosproject.net.flow.impl.FlowRuleManager.store.
Iterable<FlowRule> org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesById (ApplicationId id)
Returns a list of rules with this application id.
Parameters
id the id to look up
Returns
collection of flow rules
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 210 of file FlowRuleManager.java.
References org.onosproject.net.flow.impl.FlowRuleManager.deviceService, org.onosproject.net.device.DeviceService.getDevices(), org.onosproject.net.flow.FlowRuleStore.getFlowEntries(), and org.onosproject.net.flow.impl.FlowRuleManager.store.
Referenced by org.onosproject.net.flow.impl.FlowRuleManagerTest.getByAppId(), and org.onosproject.net.flow.impl.FlowRuleManager.removeFlowRulesById().
Iterable<TableStatisticsEntry> org.onosproject.net.flow.impl.FlowRuleManager.getFlowTableStatistics (DeviceId deviceId)
Returns the collection of flow table statistics of the specified device.
Parameters
deviceId device identifier
Returns
collection of flow table statistics
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 616 of file FlowRuleManager.java.
References find-flow.deviceId.
void org.onosproject.net.flow.impl.FlowRuleManager.modified (ComponentContext context)
Definition at line 154 of file FlowRuleManager.java.
Referenced by org.onosproject.net.flow.impl.FlowRuleManager.activate().
void org.onosproject.net.flow.impl.FlowRuleManager.removeFlowRules (FlowRule... flowRules)
Removes the specified flow rules from their respective devices.
If the device is not presently connected to the controller, these flow will be removed once the device reconnects.
Parameters
flowRules one or more flow rules throws SomeKindOfException that indicates which ones were removed and which ones failed
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 193 of file FlowRuleManager.java.
References org.onosproject.net.flow.impl.FlowRuleManager.apply(), and find-link-in-cluster.length.
Referenced by org.onosproject.net.flow.impl.FlowRuleManager.removeFlowRulesById().
void org.onosproject.net.flow.impl.FlowRuleManager.removeFlowRulesById (ApplicationId appId)
Removes all rules by id.
Parameters
appId id to remove
Implements org.onosproject.net.flow.FlowRuleService.
Definition at line 204 of file FlowRuleManager.java.
References org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesById(), and org.onosproject.net.flow.impl.FlowRuleManager.removeFlowRules().
Member Data Documentation
ComponentConfigService org.onosproject.net.flow.impl.FlowRuleManager.cfgService protected
Definition at line 129 of file FlowRuleManager.java.
CoreService org.onosproject.net.flow.impl.FlowRuleManager.coreService protected
Definition at line 126 of file FlowRuleManager.java.
ExecutorService org.onosproject.net.flow.impl.FlowRuleManager.deviceInstallers protected
Initial value:
=
            Executors.newFixedThreadPool(32, groupedThreads("onos/flowservice", "device-installer-%d"))
Definition at line 108 of file FlowRuleManager.java.
DeviceService org.onosproject.net.flow.impl.FlowRuleManager.deviceService protected
Definition at line 123 of file FlowRuleManager.java.
Referenced by org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesByGroupId(), and org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesById().
final String org.onosproject.net.flow.impl.FlowRuleManager.FLOW_RULE_NULL = "FlowRule cannot be null" static
Definition at line 97 of file FlowRuleManager.java.
ExecutorService org.onosproject.net.flow.impl.FlowRuleManager.operationsService protected
Initial value:
=
            Executors.newFixedThreadPool(32, groupedThreads("onos/flowservice", "operations-%d"))
Definition at line 111 of file FlowRuleManager.java.
FlowRuleStore org.onosproject.net.flow.impl.FlowRuleManager.store protected
Definition at line 120 of file FlowRuleManager.java.
Referenced by org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesByGroupId(), and org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesById().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/flow/impl/FlowRuleManager.java