onos: org.onosproject.vtnrsc.RouterInterface Class Reference
org.onosproject.vtnrsc.RouterInterface Class Reference
Representation of a Router interface.
Public Member Functions
SubnetId subnetId ()
Returns subnet identifier.
VirtualPortId portId ()
Returns port identifier.
RouterId routerId ()
Returns router identifier.
TenantId tenantId ()
Returns tenant identifier.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static RouterInterface routerInterface (SubnetId subnetId, VirtualPortId portId, RouterId routerId, TenantId tenantId)
Creates router interface object.
Detailed Description
Representation of a Router interface.
Definition at line 26 of file RouterInterface.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.RouterInterface.equals (Object obj)
Definition at line 99 of file RouterInterface.java.
int org.onosproject.vtnrsc.RouterInterface.hashCode ()
Definition at line 94 of file RouterInterface.java.
References org.onosproject.vtnrsc.RouterInterface.portId(), org.onosproject.vtnrsc.RouterInterface.routerId(), org.onosproject.vtnrsc.RouterInterface.subnetId(), and org.onosproject.vtnrsc.RouterInterface.tenantId().
VirtualPortId org.onosproject.vtnrsc.RouterInterface.portId ()
Returns port identifier.
Returns
portId the port identifier
Definition at line 71 of file RouterInterface.java.
Referenced by org.onosproject.vtnrsc.RouterInterface.hashCode().
RouterId org.onosproject.vtnrsc.RouterInterface.routerId ()
Returns router identifier.
Returns
routerId the router identifier
Definition at line 80 of file RouterInterface.java.
Referenced by org.onosproject.vtnrsc.RouterInterface.hashCode(), and org.onosproject.vtnrsc.RouterInterface.toString().
static RouterInterface org.onosproject.vtnrsc.RouterInterface.routerInterface (SubnetId subnetId, VirtualPortId portId, RouterId routerId, TenantId tenantId) static
Creates router interface object.
Parameters
subnetId subnet identifier
portId port identifier
routerId router identifier
tenantId tenant identifier
Returns
RouterInterface
Definition at line 50 of file RouterInterface.java.
SubnetId org.onosproject.vtnrsc.RouterInterface.subnetId ()
Returns subnet identifier.
Returns
subnetId the subnet identifier
Definition at line 62 of file RouterInterface.java.
Referenced by org.onosproject.vtnrsc.RouterInterface.hashCode(), and org.onosproject.vtnrsc.RouterInterface.toString().
TenantId org.onosproject.vtnrsc.RouterInterface.tenantId ()
Returns tenant identifier.
Returns
tenantId the tenant identifier
Definition at line 89 of file RouterInterface.java.
Referenced by org.onosproject.vtnrsc.RouterInterface.hashCode().
String org.onosproject.vtnrsc.RouterInterface.toString ()
Definition at line 114 of file RouterInterface.java.
References org.onosproject.vtnrsc.RouterInterface.routerId(), and org.onosproject.vtnrsc.RouterInterface.subnetId().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/RouterInterface.java