onos: org.onosproject.pcepio.types.IPv4InterfaceAddressTlv Class Reference
org.onosproject.pcepio.types.IPv4InterfaceAddressTlv Class Reference
Provides IPv4 Interface Address .
Public Member Functions
IPv4InterfaceAddressTlv (int rawValue)
Constructor to initialize rawValue.
int getInt ()
Returns value of IPv4 Interface Address.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static IPv4InterfaceAddressTlv of (final int raw)
Returns newly created IPv4InterfaceAddressTlv object.
static IPv4InterfaceAddressTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of IPv4InterfaceAddressTlv.
Static Public Attributes
static final short TYPE = 6
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IPv4InterfaceAddressTlv.class)
Detailed Description
Provides IPv4 Interface Address .
Definition at line 30 of file IPv4InterfaceAddressTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.IPv4InterfaceAddressTlv (int rawValue)
Constructor to initialize rawValue.
Parameters
rawValue of IPv4-Interface-Address.
Definition at line 55 of file IPv4InterfaceAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.equals(), and org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.equals (Object obj)
Definition at line 99 of file IPv4InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.IPv4InterfaceAddressTlv().
int org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.getInt ()
Returns value of IPv4 Interface Address.
Returns
rawValue IPv4 Interface Address
Definition at line 74 of file IPv4InterfaceAddressTlv.java.
short org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 89 of file IPv4InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.LENGTH.
short org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 84 of file IPv4InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 79 of file IPv4InterfaceAddressTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.hashCode ()
Definition at line 94 of file IPv4InterfaceAddressTlv.java.
static IPv4InterfaceAddressTlv org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.of (final int raw) static
Returns newly created IPv4InterfaceAddressTlv object.
Parameters
raw value of IPv4-Interface-Address
Returns
object of IPv4-Interface-Address-Tlv
Definition at line 65 of file IPv4InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.IPv4InterfaceAddressTlv().
static IPv4InterfaceAddressTlv org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of IPv4InterfaceAddressTlv.
Parameters
c input channel buffer
Returns
object of IPv4-Interface-Address-Tlv
Definition at line 125 of file IPv4InterfaceAddressTlv.java.
String org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.toString ()
Definition at line 130 of file IPv4InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.LENGTH, and org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.TYPE.
int org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 111 of file IPv4InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.LENGTH, and org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.LENGTH = 4 static
Definition at line 46 of file IPv4InterfaceAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.getLength(), org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.toString(), and org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.write().
final Logger org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.log = LoggerFactory.getLogger(IPv4InterfaceAddressTlv.class) static protected
Definition at line 43 of file IPv4InterfaceAddressTlv.java.
final short org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.TYPE = 6 static
Definition at line 45 of file IPv4InterfaceAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.getType(), org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.toString(), and org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IPv4InterfaceAddressTlv.java