onos: org.onosproject.common.app.ApplicationArchive Class Reference
org.onosproject.common.app.ApplicationArchive Class Reference
Facility for reading application archive stream and managing application directory structure.
Public Member Functions
String getRootPath ()
Returns the root directory where apps directory is contained.
Set< String > getApplicationNames ()
Returns the set of installed application names.
long getUpdateTime (String appName)
Returns the timestamp in millis since start of epoch, of when the specified application was last modified or changed state.
ApplicationDescription getApplicationDescription (String appName)
Loads the application descriptor from the specified application archive stream and saves the stream in the appropriate application archive directory.
synchronized ApplicationDescription saveApplication (InputStream stream)
Loads the application descriptor from the specified application archive stream and saves the stream in the appropriate application archive directory.
synchronized void purgeApplication (String appName)
Purges the application archive directory.
synchronized InputStream getApplicationInputStream (String appName)
Returns application archive stream for the specified application.
ApplicationRole getRole (String value)
Protected Member Functions
void setRootPath (String root)
Sets the root directory where apps directory is contained.
boolean setActive (String appName)
Marks the app as active by creating token file in the app directory.
boolean clearActive (String appName)
Clears the app as active by deleting token file in the app directory.
boolean updateTime (String appName)
Updates the time-stamp of the app descriptor file.
boolean isActive (String appName)
Indicates whether the app was marked as active by checking for token file.
Detailed Description
Facility for reading application archive stream and managing application directory structure.
Definition at line 64 of file ApplicationArchive.java.
Member Function Documentation
boolean org.onosproject.common.app.ApplicationArchive.clearActive (String appName) protected
Clears the app as active by deleting token file in the app directory.
Parameters
appName application name
Returns
true if file was deleted
Definition at line 366 of file ApplicationArchive.java.
References org.onosproject.common.app.ApplicationArchive.updateTime().
Referenced by org.onosproject.store.trivial.SimpleApplicationStore.deactivate().
ApplicationDescription org.onosproject.common.app.ApplicationArchive.getApplicationDescription (String appName)
Loads the application descriptor from the specified application archive stream and saves the stream in the appropriate application archive directory.
Parameters
appName application name
Returns
application descriptor
Exceptions
org.onosproject.app.ApplicationException if unable to read application description
Definition at line 157 of file ApplicationArchive.java.
synchronized InputStream org.onosproject.common.app.ApplicationArchive.getApplicationInputStream (String appName)
Returns application archive stream for the specified application.
This will be either the application ZIP file or the application XML file.
Parameters
appName application name
Returns
application archive stream
Definition at line 243 of file ApplicationArchive.java.
Referenced by org.onosproject.store.app.GossipApplicationStore.activate().
Set<String> org.onosproject.common.app.ApplicationArchive.getApplicationNames ()
Returns the set of installed application names.
Returns
installed application names
Definition at line 126 of file ApplicationArchive.java.
Referenced by org.onosproject.common.app.ApplicationArchiveTest.purgeApp().
ApplicationRole org.onosproject.common.app.ApplicationArchive.getRole (String value)
Definition at line 425 of file ApplicationArchive.java.
References org.onosproject.core.ApplicationRole.UNSPECIFIED.
String org.onosproject.common.app.ApplicationArchive.getRootPath ()
Returns the root directory where apps directory is contained.
Returns
top-level directory path
Definition at line 117 of file ApplicationArchive.java.
long org.onosproject.common.app.ApplicationArchive.getUpdateTime (String appName)
Returns the timestamp in millis since start of epoch, of when the specified application was last modified or changed state.
Parameters
appName application name
Returns
number of millis since start of epoch
Definition at line 144 of file ApplicationArchive.java.
boolean org.onosproject.common.app.ApplicationArchive.isActive (String appName) protected
Indicates whether the app was marked as active by checking for token file.
Parameters
appName application name
Returns
true if the app is marked as active
Definition at line 386 of file ApplicationArchive.java.
Referenced by org.onosproject.common.app.ApplicationArchiveTest.active().
synchronized void org.onosproject.common.app.ApplicationArchive.purgeApplication (String appName)
Purges the application archive directory.
Parameters
appName application name
Definition at line 224 of file ApplicationArchive.java.
Referenced by org.onosproject.store.trivial.SimpleApplicationStore.remove().
synchronized ApplicationDescription org.onosproject.common.app.ApplicationArchive.saveApplication (InputStream stream)
Loads the application descriptor from the specified application archive stream and saves the stream in the appropriate application archive directory.
Parameters
stream application archive stream
Returns
application descriptor
Exceptions
org.onosproject.app.ApplicationException if unable to read the archive stream or store the application archive
Definition at line 180 of file ApplicationArchive.java.
References org.onosproject.app.ApplicationDescription.name().
Referenced by org.onosproject.store.trivial.SimpleApplicationStore.create().
boolean org.onosproject.common.app.ApplicationArchive.setActive (String appName) protected
Marks the app as active by creating token file in the app directory.
Parameters
appName application name
Returns
true if file was created
Definition at line 352 of file ApplicationArchive.java.
References org.onosproject.common.app.ApplicationArchive.updateTime().
Referenced by org.onosproject.store.trivial.SimpleApplicationStore.activate().
void org.onosproject.common.app.ApplicationArchive.setRootPath (String root) protected
Sets the root directory where apps directory is contained.
Parameters
root top-level directory path
Definition at line 106 of file ApplicationArchive.java.
boolean org.onosproject.common.app.ApplicationArchive.updateTime (String appName) protected
Updates the time-stamp of the app descriptor file.
Parameters
appName application name
Returns
true if the app descriptor was updated
Definition at line 376 of file ApplicationArchive.java.
Referenced by org.onosproject.common.app.ApplicationArchive.clearActive(), and org.onosproject.common.app.ApplicationArchive.setActive().
The documentation for this class was generated from the following file:
core/common/src/main/java/org/onosproject/common/app/ApplicationArchive.java