onos: org.onosproject.net.driver.AbstractHandlerBehaviour Class Reference
org.onosproject.net.driver.AbstractHandlerBehaviour Class Reference
Base implementation of device driver handler behaviour.
Public Member Functions
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Detailed Description
Base implementation of device driver handler behaviour.
Definition at line 23 of file AbstractHandlerBehaviour.java.
Member Function Documentation
DriverHandler org.onosproject.net.driver.AbstractHandlerBehaviour.handler ()
Returns the driver handler context on which this behaviour operates.
Returns
driver handler context
Implements org.onosproject.net.driver.HandlerBehaviour.
Definition at line 29 of file AbstractHandlerBehaviour.java.
Referenced by org.onosproject.driver.ovsdb.OvsdbBridgeConfig.addBridge(), org.onosproject.driver.ovsdb.OvsdbBridgeConfig.addPort(), org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnel(), org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnelInterface(), org.onosproject.driver.ovsdb.OvsdbBridgeConfig.deleteBridge(), org.onosproject.driver.ovsdb.OvsdbBridgeConfig.deletePort(), org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getBridges(), org.onosproject.driver.netconf.NetconfControllerConfig.getControllers(), org.onosproject.driver.ovsdb.OvsdbControllerConfig.getControllers(), org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getLocalPorts(), org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getPortNumbers(), org.onosproject.driver.ovsdb.OvsdbBridgeConfig.getPorts(), org.onosproject.driver.ovsdb.OvsdbTunnelConfig.getTunnels(), org.onosproject.driver.ovsdb.OvsdbTunnelConfig.removeTunnel(), org.onosproject.driver.ovsdb.OvsdbControllerConfig.setControllers(), org.onosproject.driver.netconf.NetconfControllerConfig.setControllers(), and org.onosproject.net.driver.AbstractHandlerBehaviour.setHandler().
void org.onosproject.net.driver.AbstractHandlerBehaviour.setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Parameters
handler driver handler
Implements org.onosproject.net.driver.HandlerBehaviour.
Definition at line 34 of file AbstractHandlerBehaviour.java.
References org.onosproject.net.driver.AbstractHandlerBehaviour.handler().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/driver/AbstractHandlerBehaviour.java