onos: org.onlab.packet.UDPTest Class Reference
org.onlab.packet.UDPTest Class Reference
Tests for class UDP.
Public Member Functions
void testSerialize ()
Tests serialize and setters.
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws Exception
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class UDP.
Definition at line 33 of file UDPTest.java.
Member Function Documentation
static void org.onlab.packet.UDPTest.setUpBeforeClass () throws Exception static
Definition at line 67 of file UDPTest.java.
References org.onlab.packet.IPv4.PROTOCOL_UDP, and org.onlab.packet.IPv6.PROTOCOL_UDP.
void org.onlab.packet.UDPTest.testDeserialize () throws Exception
Tests deserialize and getters.
Definition at line 109 of file UDPTest.java.
References org.onlab.packet.UDP.getChecksum(), org.onlab.packet.UDP.getDestinationPort(), org.onlab.packet.UDP.getLength(), org.onlab.packet.UDP.getSourcePort(), and find-link-in-cluster.length.
void org.onlab.packet.UDPTest.testDeserializeBadInput () throws Exception
Definition at line 96 of file UDPTest.java.
void org.onlab.packet.UDPTest.testDeserializeTruncated () throws Exception
Definition at line 101 of file UDPTest.java.
void org.onlab.packet.UDPTest.testEqual ()
Tests comparator.
Definition at line 122 of file UDPTest.java.
References org.onlab.packet.UDP.equals().
void org.onlab.packet.UDPTest.testSerialize ()
Tests serialize and setters.
Definition at line 83 of file UDPTest.java.
References org.onlab.packet.UDP.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/UDPTest.java