onos: org.onosproject.store.service.PartitionInfo Class Reference
org.onosproject.store.service.PartitionInfo Class Reference
Contains information about a database partition.
Public Member Functions
PartitionInfo (String name, long term, List< String > members, String leader)
Class constructor.
String name ()
Returns the name of the partition.
long term ()
Returns the term number.
List< String > members ()
Returns the list of partition members.
String leader ()
Returns the partition leader.
Detailed Description
Contains information about a database partition.
Definition at line 25 of file PartitionInfo.java.
Constructor & Destructor Documentation
org.onosproject.store.service.PartitionInfo.PartitionInfo (String name, long term, List< String > members, String leader)
Class constructor.
Parameters
name partition name
term term number
members partition members
leader leader name
Definition at line 39 of file PartitionInfo.java.
References org.onosproject.store.service.PartitionInfo.leader(), org.onosproject.store.service.PartitionInfo.members(), org.onosproject.store.service.PartitionInfo.name(), and org.onosproject.store.service.PartitionInfo.term().
Member Function Documentation
String org.onosproject.store.service.PartitionInfo.leader ()
Returns the partition leader.
Returns
partition leader
Definition at line 78 of file PartitionInfo.java.
Referenced by org.onosproject.store.service.PartitionInfo.PartitionInfo().
List<String> org.onosproject.store.service.PartitionInfo.members ()
Returns the list of partition members.
Returns
partition members
Definition at line 69 of file PartitionInfo.java.
Referenced by org.onosproject.store.service.PartitionInfo.PartitionInfo().
String org.onosproject.store.service.PartitionInfo.name ()
Returns the name of the partition.
Returns
partition name
Definition at line 51 of file PartitionInfo.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.store.service.PartitionInfo.PartitionInfo(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
long org.onosproject.store.service.PartitionInfo.term ()
Returns the term number.
Returns
term number
Definition at line 60 of file PartitionInfo.java.
Referenced by org.onosproject.store.service.PartitionInfo.PartitionInfo().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/store/service/PartitionInfo.java