onos: org.onosproject.ui.table.cell.EnumFormatterTest Class Reference
org.onosproject.ui.table.cell.EnumFormatterTest Class Reference
Unit tests for EnumFormatter.
Classes
enum TestEnum
Public Member Functions
void nullValue ()
void noUnderscores ()
void underscores ()
void multiUnderscores ()
Detailed Description
Unit tests for EnumFormatter.
Definition at line 27 of file EnumFormatterTest.java.
Member Function Documentation
void org.onosproject.ui.table.cell.EnumFormatterTest.multiUnderscores ()
Definition at line 54 of file EnumFormatterTest.java.
References org.onosproject.ui.table.CellFormatter.format().
void org.onosproject.ui.table.cell.EnumFormatterTest.noUnderscores ()
Definition at line 43 of file EnumFormatterTest.java.
References org.onosproject.ui.table.CellFormatter.format().
void org.onosproject.ui.table.cell.EnumFormatterTest.nullValue ()
Definition at line 38 of file EnumFormatterTest.java.
References org.onosproject.ui.table.CellFormatter.format().
void org.onosproject.ui.table.cell.EnumFormatterTest.underscores ()
Definition at line 48 of file EnumFormatterTest.java.
References org.onosproject.ui.table.CellFormatter.format().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/ui/table/cell/EnumFormatterTest.java