onos: org.onosproject.net.driver.DefaultDriver Class Reference
org.onosproject.net.driver.DefaultDriver Class Reference
Default implementation of extensible driver.
Public Member Functions
DefaultDriver (String name, Driver parent, String manufacturer, String hwVersion, String swVersion, Map< Class<?extends Behaviour >, Class<?extends Behaviour >> behaviours, Map< String, String > properties)
Creates a driver with the specified name.
Driver merge (Driver other)
Merges the specified driver behaviours and properties into this one, giving preference to the other driver when dealing with conflicts.
String name ()
Returns the driver name.
String manufacturer ()
Returns the device manufacturer name.
String hwVersion ()
Returns the device hardware version.
String swVersion ()
Returns the device software version.
Driver parent ()
Returns the parent driver from which this driver inherits behaviours and properties.
Set< Class<?extends Behaviour > > behaviours ()
Returns the set of behaviours supported by this driver.
Class<?extends Behaviour > implementation (Class<?extends Behaviour > behaviour)
Returns the implementation class for the specified behaviour.
boolean hasBehaviour (Class<?extends Behaviour > behaviourClass)
Indicates whether or not the driver, or any of its parents, support the specified class of behaviour.
Set< String > keys ()
Returns the set of keys for available annotations.
String value (String key)
Returns the value of the specified annotation.
Map< String, String > properties ()
Returns the set of annotations as map of key/value properties.
String toString ()
Detailed Description
Default implementation of extensible driver.
Definition at line 33 of file DefaultDriver.java.
Constructor & Destructor Documentation
org.onosproject.net.driver.DefaultDriver.DefaultDriver (String name, Driver parent, String manufacturer, String hwVersion, String swVersion, Map< Class<?extends Behaviour >, Class<?extends Behaviour >> behaviours, Map< String, String > properties)
Creates a driver with the specified name.
Parameters
name driver name
parent optional parent driver
manufacturer device manufacturer
hwVersion device hardware version
swVersion device software version
behaviours device behaviour classes
properties properties for configuration of device behaviour classes
Definition at line 56 of file DefaultDriver.java.
References org.onosproject.net.driver.DefaultDriver.behaviours(), and org.onosproject.net.driver.DefaultDriver.parent().
Referenced by org.onosproject.net.driver.DefaultDriver.merge().
Member Function Documentation
Set<Class<? extends Behaviour> > org.onosproject.net.driver.DefaultDriver.behaviours ()
Returns the set of behaviours supported by this driver.
It reflects behaviours of only this driver and not its parent.
Returns
set of device driver behaviours
Implements org.onosproject.net.driver.Driver.
Definition at line 114 of file DefaultDriver.java.
Referenced by org.onosproject.net.driver.DefaultDriver.DefaultDriver(), org.onosproject.net.driver.DefaultDriver.merge(), and org.onosproject.net.driver.DefaultDriver.toString().
boolean org.onosproject.net.driver.DefaultDriver.hasBehaviour (Class<?extends Behaviour > behaviourClass)
Indicates whether or not the driver, or any of its parents, support the specified class of behaviour.
It
Parameters
behaviourClass behaviour class
Returns
true if behaviour is supported
Implements org.onosproject.net.driver.Driver.
Definition at line 124 of file DefaultDriver.java.
References org.onosproject.net.driver.Driver.hasBehaviour(), and org.onosproject.net.driver.DefaultDriver.parent().
Referenced by org.onosproject.net.driver.DefaultDriverTest.basics().
String org.onosproject.net.driver.DefaultDriver.hwVersion ()
Returns the device hardware version.
Returns
hardware version
Implements org.onosproject.net.driver.Driver.
Definition at line 99 of file DefaultDriver.java.
Referenced by org.onosproject.net.driver.DefaultDriver.merge(), and org.onosproject.net.driver.DefaultDriver.toString().
Class<? extends Behaviour> org.onosproject.net.driver.DefaultDriver.implementation (Class<?extends Behaviour > behaviour)
Returns the implementation class for the specified behaviour.
It reflects behaviours of only this driver and not its parent.
Parameters
behaviour behaviour interface
Returns
implementation class
Implements org.onosproject.net.driver.Driver.
Definition at line 119 of file DefaultDriver.java.
Set<String> org.onosproject.net.driver.DefaultDriver.keys ()
Returns the set of keys for available annotations.
Returns
annotation keys
Implements org.onosproject.net.Annotations.
Definition at line 187 of file DefaultDriver.java.
Referenced by org.onosproject.net.driver.DefaultDriverTest.basics().
String org.onosproject.net.driver.DefaultDriver.manufacturer ()
Returns the device manufacturer name.
Returns
manufacturer name
Implements org.onosproject.net.driver.Driver.
Definition at line 94 of file DefaultDriver.java.
Referenced by org.onosproject.net.driver.DefaultDriver.merge(), and org.onosproject.net.driver.DefaultDriver.toString().
Driver org.onosproject.net.driver.DefaultDriver.merge (Driver other)
Merges the specified driver behaviours and properties into this one, giving preference to the other driver when dealing with conflicts.
Parameters
other other driver
Returns
merged driver
Implements org.onosproject.net.driver.Driver.
Definition at line 70 of file DefaultDriver.java.
References org.onosproject.net.driver.DefaultDriver.behaviours(), org.onosproject.net.driver.DefaultDriver.DefaultDriver(), org.onosproject.net.driver.DefaultDriver.hwVersion(), org.onosproject.net.driver.Driver.implementation(), org.onosproject.net.driver.DefaultDriver.manufacturer(), org.onosproject.net.driver.DefaultDriver.name(), org.onosproject.net.driver.Driver.parent(), org.onosproject.net.driver.DefaultDriver.parent(), org.onosproject.net.driver.Driver.properties(), org.onosproject.net.driver.DefaultDriver.properties(), and org.onosproject.net.driver.DefaultDriver.swVersion().
String org.onosproject.net.driver.DefaultDriver.name ()
Returns the driver name.
This is expected to be a reverse-DNS, Java package-like name.
Returns
driver name
Implements org.onosproject.net.driver.Driver.
Definition at line 89 of file DefaultDriver.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.net.driver.DefaultDriver.merge(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.net.driver.DefaultDriver.toString().
Driver org.onosproject.net.driver.DefaultDriver.parent ()
Returns the parent driver from which this driver inherits behaviours and properties.
Returns
parent driver; null if driver has no parent
Implements org.onosproject.net.driver.Driver.
Definition at line 109 of file DefaultDriver.java.
Referenced by org.onosproject.net.driver.DefaultDriver.DefaultDriver(), org.onosproject.net.driver.DefaultDriver.hasBehaviour(), org.onosproject.net.driver.DefaultDriver.merge(), and org.onosproject.net.driver.DefaultDriver.toString().
Map<String, String> org.onosproject.net.driver.DefaultDriver.properties ()
Returns the set of annotations as map of key/value properties.
Returns
map of properties
Implements org.onosproject.net.driver.Driver.
Definition at line 197 of file DefaultDriver.java.
Referenced by org.onosproject.net.driver.DefaultDriver.merge(), and org.onosproject.net.driver.DefaultDriver.toString().
String org.onosproject.net.driver.DefaultDriver.swVersion ()
Returns the device software version.
Returns
software version
Implements org.onosproject.net.driver.Driver.
Definition at line 104 of file DefaultDriver.java.
Referenced by org.onosproject.net.driver.DefaultDriver.merge(), and org.onosproject.net.driver.DefaultDriver.toString().
String org.onosproject.net.driver.DefaultDriver.toString ()
Definition at line 202 of file DefaultDriver.java.
References org.onosproject.net.driver.DefaultDriver.behaviours(), org.onosproject.net.driver.DefaultDriver.hwVersion(), org.onosproject.net.driver.DefaultDriver.manufacturer(), org.onosproject.net.driver.DefaultDriver.name(), org.onosproject.net.driver.DefaultDriver.parent(), org.onosproject.net.driver.DefaultDriver.properties(), and org.onosproject.net.driver.DefaultDriver.swVersion().
Referenced by org.onosproject.net.driver.DefaultDriverTest.basics().
String org.onosproject.net.driver.DefaultDriver.value (String key)
Returns the value of the specified annotation.
Parameters
key annotation key
Returns
annotation value
Implements org.onosproject.net.Annotations.
Definition at line 192 of file DefaultDriver.java.
Referenced by org.onosproject.net.driver.DefaultDriverTest.basics().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/driver/DefaultDriver.java