onos: org.onlab.util.Tools Class Reference
org.onlab.util.Tools Class Reference
Miscellaneous utility methods.
Static Public Member Functions
static ThreadFactory namedThreads (String pattern)
Returns a thread factory that produces threads named according to the supplied name pattern.
static ThreadFactory groupedThreads (String groupName, String pattern)
Returns a thread factory that produces threads named according to the supplied name pattern and from the specified thread-group.
static ThreadFactory minPriority (ThreadFactory factory)
Returns a thread factory that produces threads with MIN_PRIORITY.
static boolean isNullOrEmpty (Collection collection)
Returns true if the collection is null or is empty.
static< T > T nullIsNotFound (T item, String message)
Returns the specified item if that item is not null; otherwise throws not found exception.
static< T > Set< T > emptyIsNotFound (Set< T > item, String message)
Returns the specified set if the set is not null and not empty; otherwise throws a not found exception.
static< T > T nullIsIllegal (T item, String message)
Returns the specified item if that item is not null; otherwise throws bad argument exception.
static long fromHex (String string)
Converts a string from hex to long.
static String toHex (long value)
Converts a long value to hex string; 16 wide and sans 0x.
static String toHex (long value, int width)
Converts a long value to hex string; 16 wide and sans 0x.
static byte[] copyOf (byte[] original)
Returns a copy of the input byte array.
static String get (Dictionary<?,?> properties, String propertyName)
Get property as a string value.
static void delay (int ms)
Suspends the current thread for a specified number of millis.
static< U, V > Function< U, V > retryable (Function< U, V > base, Class<?extends Throwable > exceptionClass, int maxRetries, int maxDelayBetweenRetries)
Returns a function that retries execution on failure.
static< V > Supplier< V > retryable (Supplier< V > base, Class<?extends Throwable > exceptionClass, int maxRetries, int maxDelayBetweenRetries)
Returns a Supplier that retries execution on failure.
static void randomDelay (int ms)
Suspends the current thread for a random number of millis between 0 and the indicated limit.
static void delay (int ms, int nanos)
Suspends the current thread for a specified number of millis and nanos.
static List< String > slurp (File path)
Slurps the contents of a file into a list of strings, one per line.
static void removeDirectory (String path) throws IOException
Purges the specified directory path.
static void removeDirectory (File dir) throws IOException
Purges the specified directory path.
static String timeAgo (long unixTime)
Returns a human friendly time ago string for a specified system time.
static void copyDirectory (String src, String dst) throws IOException
Copies the specified directory path.
static void copyDirectory (File src, File dst) throws IOException
Copies the specified directory path.
static< T > T futureGetOrElse (Future< T > future, T defaultValue)
Returns the future value when complete or if future completes exceptionally returns the defaultValue.
static< T > T futureGetOrElse (Future< T > future, long timeout, TimeUnit timeUnit, T defaultValue)
Returns the future value when complete or if future completes exceptionally returns the defaultValue.
static< T > CompletableFuture< T > exceptionalFuture (Throwable t)
Returns a future that is completed exceptionally.
static byte[] byteBuffertoArray (ByteBuffer buffer)
Returns the contents of.
static< T > Stream< T > stream (Iterable< T > it)
Converts an iterable to a stream.
Detailed Description
Miscellaneous utility methods.
Definition at line 64 of file Tools.java.
Member Function Documentation
static byte [] org.onlab.util.Tools.byteBuffertoArray (ByteBuffer buffer) static
Returns the contents of.
ByteBuffer
as byte array.
WARNING: There is a performance cost due to array copy when using this method.
Parameters
buffer byte buffer
Returns
byte array containing the byte buffer contents
Definition at line 528 of file Tools.java.
References find-link-in-cluster.length.
static void org.onlab.util.Tools.copyDirectory (String src, String dst) throws IOException static
Copies the specified directory path.
Use with great caution since no attempt is made to check for symbolic links, which could result in copy of unintended files.
Parameters
src directory to be copied
dst destination directory to be removed
Exceptions
java.io.IOException if unable to remove contents
Definition at line 440 of file Tools.java.
static void org.onlab.util.Tools.copyDirectory (File src, File dst) throws IOException static
Copies the specified directory path.
Use with great caution since no attempt is made to check for symbolic links, which could result in copy of unintended files.
Parameters
src directory to be copied
dst destination directory to be removed
Exceptions
java.io.IOException if unable to remove contents
Definition at line 453 of file Tools.java.
static byte [] org.onlab.util.Tools.copyOf (byte[] original) static
Returns a copy of the input byte array.
Parameters
original input
Returns
copy of original
Definition at line 218 of file Tools.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.DefaultAsyncConsistentMap().
static void org.onlab.util.Tools.delay (int ms) static
Suspends the current thread for a specified number of millis.
Parameters
ms number of millis
Definition at line 241 of file Tools.java.
static void org.onlab.util.Tools.delay (int ms, int nanos) static
Suspends the current thread for a specified number of millis and nanos.
Parameters
ms number of millis
nanos number of nanos
Definition at line 307 of file Tools.java.
static <T> Set<T> org.onlab.util.Tools.emptyIsNotFound (Set< T > item, String message) static
Returns the specified set if the set is not null and not empty; otherwise throws a not found exception.
Parameters
item set to check
message not found message
<T> Set item type
Returns
item if not null and not empty
Exceptions
org.onlab.util.ItemNotFoundException if set is null or empty
Definition at line 157 of file Tools.java.
static <T> CompletableFuture<T> org.onlab.util.Tools.exceptionalFuture (Throwable t) static
Returns a future that is completed exceptionally.
Parameters
t exception
<T> future value type
Returns
future
Definition at line 513 of file Tools.java.
static long org.onlab.util.Tools.fromHex (String string) static
Converts a string from hex to long.
Parameters
string hex number in string form; sans 0x
Returns
long value
Definition at line 187 of file Tools.java.
Referenced by org.onlab.util.ToolsTest.fromHex().
static <T> T org.onlab.util.Tools.futureGetOrElse (Future< T > future, T defaultValue) static
Returns the future value when complete or if future completes exceptionally returns the defaultValue.
Parameters
future future
defaultValue default value
<T> future value type
Returns
future value when complete or if future completes exceptionally returns the defaultValue.
Definition at line 469 of file Tools.java.
static <T> T org.onlab.util.Tools.futureGetOrElse (Future< T > future, long timeout, TimeUnit timeUnit, T defaultValue) static
Returns the future value when complete or if future completes exceptionally returns the defaultValue.
Parameters
future future
timeout time to wait for successful completion
timeUnit time unit
defaultValue default value
<T> future value type
Returns
future value when complete or if future completes exceptionally returns the defaultValue.
Definition at line 492 of file Tools.java.
static String org.onlab.util.Tools.get (Dictionary<?,?> properties, String propertyName) static
Get property as a string value.
Parameters
properties properties to be looked up
propertyName the name of the property to look up
Returns
value when the propertyName is defined or return null
Definition at line 229 of file Tools.java.
static ThreadFactory org.onlab.util.Tools.groupedThreads (String groupName, String pattern) static
Returns a thread factory that produces threads named according to the supplied name pattern and from the specified thread-group.
The thread group name is expected to be specified in slash-delimited format, e.g.
onos/intent
. The thread names will be produced by converting the thread group name into dash-delimited format and pre-pended to the specified pattern.
Parameters
groupName group name in slash-delimited format to indicate hierarchy
pattern name pattern
Returns
thread factory
Definition at line 99 of file Tools.java.
References org.onlab.util.GroupedThreadFactory.DELIMITER.
static boolean org.onlab.util.Tools.isNullOrEmpty (Collection collection) static
Returns true if the collection is null or is empty.
Parameters
collection collection to test
Returns
true if null or empty; false otherwise
Definition at line 126 of file Tools.java.
static ThreadFactory org.onlab.util.Tools.minPriority (ThreadFactory factory) static
Returns a thread factory that produces threads with MIN_PRIORITY.
Parameters
factory backing ThreadFactory
Returns
thread factory
Definition at line 113 of file Tools.java.
static ThreadFactory org.onlab.util.Tools.namedThreads (String pattern) static
Returns a thread factory that produces threads named according to the supplied name pattern.
Parameters
pattern name pattern
Returns
thread factory
Definition at line 80 of file Tools.java.
static <T> T org.onlab.util.Tools.nullIsIllegal (T item, String message) static
Returns the specified item if that item is not null; otherwise throws bad argument exception.
Parameters
item item to check
message not found message
<T> item type
Returns
item if not null
Exceptions
IllegalArgumentException if item is null
Definition at line 174 of file Tools.java.
static <T> T org.onlab.util.Tools.nullIsNotFound (T item, String message) static
Returns the specified item if that item is not null; otherwise throws not found exception.
Parameters
item item to check
message not found message
<T> item type
Returns
item if not null
Exceptions
org.onlab.util.ItemNotFoundException if item is null
Definition at line 140 of file Tools.java.
static void org.onlab.util.Tools.randomDelay (int ms) static
Suspends the current thread for a random number of millis between 0 and the indicated limit.
Parameters
ms max number of millis
Definition at line 293 of file Tools.java.
static void org.onlab.util.Tools.removeDirectory (String path) throws IOException static
Purges the specified directory path.
Use with great caution since no attempt is made to check for symbolic links, which could result in deletion of unintended files.
Parameters
path directory to be removed
Exceptions
java.io.IOException if unable to remove contents
Definition at line 348 of file Tools.java.
static void org.onlab.util.Tools.removeDirectory (File dir) throws IOException static
Purges the specified directory path.
Use with great caution since no attempt is made to check for symbolic links, which could result in deletion of unintended files.
Parameters
dir directory to be removed
Exceptions
java.io.IOException if unable to remove contents
Definition at line 367 of file Tools.java.
static <U,V> Function<U, V> org.onlab.util.Tools.retryable (Function< U, V > base, Class<?extends Throwable > exceptionClass, int maxRetries, int maxDelayBetweenRetries) static
Returns a function that retries execution on failure.
Parameters
base base function
exceptionClass type of exception for which to retry
maxRetries max number of retries before giving up
maxDelayBetweenRetries max delay between successive retries. The actual delay is randomly picked from the interval (0, maxDelayBetweenRetries]
Returns
function
Parameters
<U> type of function input
<V> type of function output
Definition at line 260 of file Tools.java.
static <V> Supplier<V> org.onlab.util.Tools.retryable (Supplier< V > base, Class<?extends Throwable > exceptionClass, int maxRetries, int maxDelayBetweenRetries) static
Returns a Supplier that retries execution on failure.
Parameters
base base supplier
exceptionClass type of exception for which to retry
maxRetries max number of retries before giving up
maxDelayBetweenRetries max delay between successive retries. The actual delay is randomly picked from the interval (0, maxDelayBetweenRetries]
Returns
supplier
Parameters
<V> type of supplied result
Definition at line 277 of file Tools.java.
static List<String> org.onlab.util.Tools.slurp (File path) static
Slurps the contents of a file into a list of strings, one per line.
Parameters
path file path
Returns
file contents
Deprecated:
in Emu release
Definition at line 323 of file Tools.java.
static <T> Stream<T> org.onlab.util.Tools.stream (Iterable< T > it) static
Converts an iterable to a stream.
Parameters
it iterable to convert
<T> type if item
Returns
iterable as a stream
Definition at line 546 of file Tools.java.
static String org.onlab.util.Tools.timeAgo (long unixTime) static
Returns a human friendly time ago string for a specified system time.
Parameters
unixTime system time in millis
Returns
human friendly time ago
Definition at line 412 of file Tools.java.
static String org.onlab.util.Tools.toHex (long value) static
Converts a long value to hex string; 16 wide and sans 0x.
Parameters
value long value
Returns
hex string
Definition at line 197 of file Tools.java.
Referenced by org.onlab.util.ToolsTest.toHex().
static String org.onlab.util.Tools.toHex (long value, int width) static
Converts a long value to hex string; 16 wide and sans 0x.
Parameters
value long value
width string width; zero padded
Returns
hex string
Definition at line 208 of file Tools.java.
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/util/Tools.java