onos: org.onosproject.ovsdb.controller.DefaultEventSubject Class Reference
org.onosproject.ovsdb.controller.DefaultEventSubject Class Reference
This class is default event subject that implements OvsdbEventSubject.
Public Member Functions
DefaultEventSubject (MacAddress mac, Set< IpAddress > ips, OvsdbPortName portname, OvsdbPortNumber portnumber, OvsdbDatapathId dpid, OvsdbPortType portType, OvsdbIfaceId ifaceid)
Creates an end-station event subject using the supplied information.
MacAddress hwAddress ()
Returns the MAC address associated with this host (NIC).
Set< IpAddress > ipAddress ()
Returns the IP address associated with this host's MAC.
OvsdbPortName portName ()
Returns the Port name associated with the host.
OvsdbPortNumber portNumber ()
Returns the Port number associated with the host.
OvsdbPortType portType ()
Returns the Port type associated with the host.
OvsdbDatapathId dpid ()
Returns the Ovs dpid associated with the host.
OvsdbIfaceId ifaceid ()
Returns the vm ifaceid associated with the host.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
This class is default event subject that implements OvsdbEventSubject.
Definition at line 29 of file DefaultEventSubject.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.controller.DefaultEventSubject.DefaultEventSubject (MacAddress mac, Set< IpAddress > ips, OvsdbPortName portname, OvsdbPortNumber portnumber, OvsdbDatapathId dpid, OvsdbPortType portType, OvsdbIfaceId ifaceid)
Creates an end-station event subject using the supplied information.
Parameters
mac host MAC address
ips host MAC ips
portname port name
portnumber port number
dpid ovs dpid
portType port type
ifaceid vm ifaceid
Definition at line 49 of file DefaultEventSubject.java.
References org.onosproject.ovsdb.controller.DefaultEventSubject.dpid(), org.onosproject.ovsdb.controller.DefaultEventSubject.ifaceid(), and org.onosproject.ovsdb.controller.DefaultEventSubject.portType().
Referenced by org.onosproject.ovsdb.controller.DefaultEventSubject.equals().
Member Function Documentation
OvsdbDatapathId org.onosproject.ovsdb.controller.DefaultEventSubject.dpid ()
Returns the Ovs dpid associated with the host.
Returns
Ovs dpid
Implements org.onosproject.ovsdb.controller.OvsdbEventSubject.
Definition at line 88 of file DefaultEventSubject.java.
Referenced by org.onosproject.ovsdb.controller.DefaultEventSubject.DefaultEventSubject(), org.onosproject.ovsdb.controller.DefaultEventSubject.hashCode(), opticalUtils.LINCSwitch.read_from_cli(), opticalUtils.LINCSwitch.start(), and org.onosproject.ovsdb.controller.DefaultEventSubject.toString().
boolean org.onosproject.ovsdb.controller.DefaultEventSubject.equals (Object obj)
Definition at line 103 of file DefaultEventSubject.java.
References org.onosproject.ovsdb.controller.DefaultEventSubject.DefaultEventSubject(), and obeliskHostCheck.mac.
int org.onosproject.ovsdb.controller.DefaultEventSubject.hashCode ()
Definition at line 98 of file DefaultEventSubject.java.
References org.onosproject.ovsdb.controller.DefaultEventSubject.dpid(), org.onosproject.ovsdb.controller.DefaultEventSubject.ifaceid(), and org.onosproject.ovsdb.controller.DefaultEventSubject.portType().
MacAddress org.onosproject.ovsdb.controller.DefaultEventSubject.hwAddress ()
Returns the MAC address associated with this host (NIC).
Returns
the MAC address of this host
Implements org.onosproject.ovsdb.controller.OvsdbEventSubject.
Definition at line 63 of file DefaultEventSubject.java.
OvsdbIfaceId org.onosproject.ovsdb.controller.DefaultEventSubject.ifaceid ()
Returns the vm ifaceid associated with the host.
Returns
vm ifaceid
Implements org.onosproject.ovsdb.controller.OvsdbEventSubject.
Definition at line 93 of file DefaultEventSubject.java.
Referenced by org.onosproject.ovsdb.controller.DefaultEventSubject.DefaultEventSubject(), org.onosproject.ovsdb.controller.DefaultEventSubject.hashCode(), and org.onosproject.ovsdb.controller.DefaultEventSubject.toString().
Set<IpAddress> org.onosproject.ovsdb.controller.DefaultEventSubject.ipAddress ()
Returns the IP address associated with this host's MAC.
Returns
host IP address
Implements org.onosproject.ovsdb.controller.OvsdbEventSubject.
Definition at line 68 of file DefaultEventSubject.java.
OvsdbPortName org.onosproject.ovsdb.controller.DefaultEventSubject.portName ()
Returns the Port name associated with the host.
Returns
port name
Implements org.onosproject.ovsdb.controller.OvsdbEventSubject.
Definition at line 73 of file DefaultEventSubject.java.
OvsdbPortNumber org.onosproject.ovsdb.controller.DefaultEventSubject.portNumber ()
Returns the Port number associated with the host.
Returns
port number
Implements org.onosproject.ovsdb.controller.OvsdbEventSubject.
Definition at line 78 of file DefaultEventSubject.java.
OvsdbPortType org.onosproject.ovsdb.controller.DefaultEventSubject.portType ()
Returns the Port type associated with the host.
Returns
port type
Implements org.onosproject.ovsdb.controller.OvsdbEventSubject.
Definition at line 83 of file DefaultEventSubject.java.
Referenced by org.onosproject.ovsdb.controller.DefaultEventSubject.DefaultEventSubject(), org.onosproject.ovsdb.controller.DefaultEventSubject.hashCode(), and org.onosproject.ovsdb.controller.DefaultEventSubject.toString().
String org.onosproject.ovsdb.controller.DefaultEventSubject.toString ()
Definition at line 120 of file DefaultEventSubject.java.
References org.onosproject.ovsdb.controller.DefaultEventSubject.dpid(), org.onosproject.ovsdb.controller.DefaultEventSubject.ifaceid(), and org.onosproject.ovsdb.controller.DefaultEventSubject.portType().
The documentation for this class was generated from the following file:
protocols/ovsdb/api/src/main/java/org/onosproject/ovsdb/controller/DefaultEventSubject.java