onos: org.onosproject.vtn.table.impl.L2ForwardServiceImpl Class Reference
org.onosproject.vtn.table.impl.L2ForwardServiceImpl Class Reference
Provides implementation of L2ForwardService.
Public Member Functions
L2ForwardServiceImpl (ApplicationId appId)
Constructor.
void programLocalBcastRules (DeviceId deviceId, SegmentationId segmentationId, PortNumber inPort, Iterable< PortNumber > localVmPorts, Iterable< PortNumber > localTunnelPorts, Objective.Operation type)
void programTunnelBcastRules (DeviceId deviceId, SegmentationId segmentationId, Iterable< PortNumber > localVmPorts, Iterable< PortNumber > localTunnelPorts, Objective.Operation type)
void programLocalOut (DeviceId deviceId, SegmentationId segmentationId, PortNumber outPort, MacAddress sourceMac, Objective.Operation type)
void programTunnelOut (DeviceId deviceId, SegmentationId segmentationId, PortNumber tunnelOutPort, MacAddress dstMac, Objective.Operation type, IpAddress ipAddress)
Public Member Functions inherited from org.onosproject.vtn.table.L2ForwardService
void programLocalBcastRules (DeviceId deviceId, SegmentationId segmentationId, PortNumber inPort, Iterable< PortNumber > localVmPorts, Iterable< PortNumber > localTunnelPorts, Objective.Operation type)
The local broadcast rule that message matches Table(50).
void programTunnelBcastRules (DeviceId deviceId, SegmentationId segmentationId, Iterable< PortNumber > localVmPorts, Iterable< PortNumber > localTunnelPorts, Objective.Operation type)
The tunnel broadcast rule that message matches Table(50).
void programLocalOut (DeviceId deviceId, SegmentationId segmentationId, PortNumber outPort, MacAddress sourceMac, Objective.Operation type)
The local out rule that message matches Table(50).
void programTunnelOut (DeviceId deviceId, SegmentationId segmentationId, PortNumber tunnelOutPort, MacAddress dstMac, Objective.Operation type, IpAddress ipAddress)
The tunnel out rule that message matches Table(50).
Static Public Attributes
static final Integer GROUP_ID = 1
Detailed Description
Provides implementation of L2ForwardService.
Definition at line 55 of file L2ForwardServiceImpl.java.
Constructor & Destructor Documentation
org.onosproject.vtn.table.impl.L2ForwardServiceImpl.L2ForwardServiceImpl (ApplicationId appId)
Constructor.
Parameters
appId the application id of vtn
Definition at line 68 of file L2ForwardServiceImpl.java.
Member Function Documentation
void org.onosproject.vtn.table.impl.L2ForwardServiceImpl.programLocalBcastRules (DeviceId deviceId, SegmentationId segmentationId, PortNumber inPort, Iterable< PortNumber > localVmPorts, Iterable< PortNumber > localTunnelPorts, Objective.Operation type)
Definition at line 76 of file L2ForwardServiceImpl.java.
References org.onlab.packet.MacAddress.BROADCAST, find-flow.deviceId, org.onosproject.vtn.table.impl.L2ForwardServiceImpl.GROUP_ID, org.onosproject.net.flow.criteria.Criteria.matchTunnelId(), create-flow.outPort, org.onosproject.net.flowobjective.ForwardingObjective.Flag.SPECIFIC, and org.onosproject.vtnrsc.SegmentationId.toString().
void org.onosproject.vtn.table.impl.L2ForwardServiceImpl.programLocalOut (DeviceId deviceId, SegmentationId segmentationId, PortNumber outPort, MacAddress sourceMac, Objective.Operation type)
Definition at line 157 of file L2ForwardServiceImpl.java.
References find-flow.deviceId, org.onosproject.net.flowobjective.ForwardingObjective.Flag.SPECIFIC, and org.onosproject.vtnrsc.SegmentationId.toString().
void org.onosproject.vtn.table.impl.L2ForwardServiceImpl.programTunnelBcastRules (DeviceId deviceId, SegmentationId segmentationId, Iterable< PortNumber > localVmPorts, Iterable< PortNumber > localTunnelPorts, Objective.Operation type)
Definition at line 118 of file L2ForwardServiceImpl.java.
References org.onlab.packet.MacAddress.BROADCAST, find-flow.deviceId, create-flow.outPort, and org.onosproject.net.flowobjective.ForwardingObjective.Flag.SPECIFIC.
void org.onosproject.vtn.table.impl.L2ForwardServiceImpl.programTunnelOut (DeviceId deviceId, SegmentationId segmentationId, PortNumber tunnelOutPort, MacAddress dstMac, Objective.Operation type, IpAddress ipAddress)
Definition at line 179 of file L2ForwardServiceImpl.java.
References org.onosproject.net.flow.TrafficTreatment.Builder.build(), find-flow.deviceId, and org.onosproject.net.flowobjective.ForwardingObjective.Flag.SPECIFIC.
Member Data Documentation
final Integer org.onosproject.vtn.table.impl.L2ForwardServiceImpl.GROUP_ID = 1 static
Definition at line 59 of file L2ForwardServiceImpl.java.
Referenced by org.onosproject.vtn.table.impl.L2ForwardServiceImpl.programLocalBcastRules().
The documentation for this class was generated from the following file:
apps/vtn/vtnmgr/src/main/java/org/onosproject/vtn/table/impl/L2ForwardServiceImpl.java