onos: org.onosproject.pcepio.types.OpaqueNodeAttributeTlv Class Reference
org.onosproject.pcepio.types.OpaqueNodeAttributeTlv Class Reference
Provides Opaque node attributes.
Public Member Functions
OpaqueNodeAttributeTlv (byte[] rawValue, short hLength)
constructor to initialize rawValue.
byte[] getValue ()
Returns raw value of Opaque Node Attribute Tlv.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static OpaqueNodeAttributeTlv of (final byte[] raw, short hLength)
Returns newly created OpaqueNodeAttributeTlv object.
static PcepValueType read (ChannelBuffer c, short hLength)
Reads the channel buffer and returns object of Opaque Node Attribute Tlv.
Static Public Attributes
static final short TYPE = 1001
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(OpaqueNodeAttributeTlv.class)
Detailed Description
Provides Opaque node attributes.
Definition at line 30 of file OpaqueNodeAttributeTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.OpaqueNodeAttributeTlv (byte[] rawValue, short hLength)
constructor to initialize rawValue.
Parameters
rawValue Opaque Node Attribute
hLength length
Definition at line 55 of file OpaqueNodeAttributeTlv.java.
Referenced by org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.equals(), org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.of(), and org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.equals (Object obj)
Definition at line 106 of file OpaqueNodeAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.OpaqueNodeAttributeTlv().
short org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 96 of file OpaqueNodeAttributeTlv.java.
short org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 91 of file OpaqueNodeAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.TYPE.
byte [] org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.getValue ()
Returns raw value of Opaque Node Attribute Tlv.
Returns
rawValue of Opaque Node Attribute
Definition at line 81 of file OpaqueNodeAttributeTlv.java.
PcepVersion org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 86 of file OpaqueNodeAttributeTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.hashCode ()
Definition at line 101 of file OpaqueNodeAttributeTlv.java.
static OpaqueNodeAttributeTlv org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.of (final byte[] raw, short hLength) static
Returns newly created OpaqueNodeAttributeTlv object.
Parameters
raw value of Opaque Node Attribute
hLength length
Returns
new object of Opaque Node Attribute Tlv
Definition at line 72 of file OpaqueNodeAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.OpaqueNodeAttributeTlv().
static PcepValueType org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.read (ChannelBuffer c, short hLength) static
Reads the channel buffer and returns object of Opaque Node Attribute Tlv.
Parameters
c input channel buffer
hLength length
Returns
object of OpaqueNodeAttributeTlv
Definition at line 133 of file OpaqueNodeAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.OpaqueNodeAttributeTlv().
String org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.toString ()
Definition at line 140 of file OpaqueNodeAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.TYPE.
int org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 118 of file OpaqueNodeAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.TYPE.
Member Data Documentation
final Logger org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.log = LoggerFactory.getLogger(OpaqueNodeAttributeTlv.class) static protected
Definition at line 42 of file OpaqueNodeAttributeTlv.java.
final short org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.TYPE = 1001 static
Definition at line 44 of file OpaqueNodeAttributeTlv.java.
Referenced by org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.getType(), org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.toString(), and org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/OpaqueNodeAttributeTlv.java