onos: org.onosproject.ui.topo.BiLink Class Reference
org.onosproject.ui.topo.BiLink Class Reference abstract
Representation of a link and its inverse, as a partial implementation.
Public Member Functions
BiLink (LinkKey key, Link link)
Constructs a bi-link for the given key and initial link.
void setOther (Link link)
Sets the second link for this bi-link.
String linkId ()
Returns the link identifier in the form expected on the Topology View in the web client.
LinkKey key ()
Returns the key for this bi-link.
Link one ()
Returns the first link in this bi-link.
Link two ()
Returns the second link in this bi-link.
abstract LinkHighlight highlight (Enum<?> type)
Returns the link highlighting to use, based on this bi-link's current state.
Detailed Description
Representation of a link and its inverse, as a partial implementation.
Subclasses will decide how to generate the link highlighting (coloring and labeling) for the topology view.
Definition at line 30 of file BiLink.java.
Constructor & Destructor Documentation
org.onosproject.ui.topo.BiLink.BiLink (LinkKey key, Link link)
Constructs a bi-link for the given key and initial link.
It is expected that the caller will have used TopoUtils#canonicalLinkKey(Link) to generate the key.
Parameters
key canonical key for this bi-link
link first link
Definition at line 44 of file BiLink.java.
Member Function Documentation
abstract LinkHighlight org.onosproject.ui.topo.BiLink.highlight (Enum<?> type) pure virtual
Returns the link highlighting to use, based on this bi-link's current state.
Parameters
type optional highlighting type parameter
Returns
link highlighting model
Implemented in org.onosproject.ui.impl.topo.TrafficLink, DemoLink, DemoLink, it.pkg.DemoLink, and org.onosproject.ui.topo.BaseLink.
LinkKey org.onosproject.ui.topo.BiLink.key ()
Returns the key for this bi-link.
Returns
the key
Definition at line 73 of file BiLink.java.
String org.onosproject.ui.topo.BiLink.linkId ()
Returns the link identifier in the form expected on the Topology View in the web client.
Returns
link identifier
Definition at line 64 of file BiLink.java.
References org.onosproject.ui.topo.BiLink.one().
Referenced by org.onosproject.ui.topo.BiLinkTest.basic(), and it.pkg.DemoLink.highlight().
Link org.onosproject.ui.topo.BiLink.one ()
Returns the first link in this bi-link.
Returns
the first link
Definition at line 82 of file BiLink.java.
Referenced by org.onosproject.ui.topo.BiLink.linkId().
void org.onosproject.ui.topo.BiLink.setOther (Link link)
Sets the second link for this bi-link.
Parameters
link second link
Definition at line 54 of file BiLink.java.
Link org.onosproject.ui.topo.BiLink.two ()
Returns the second link in this bi-link.
Returns
the second link
Definition at line 91 of file BiLink.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/topo/BiLink.java