onos: org.onosproject.incubator.net.intf.impl.InterfaceManagerTest Class Reference
org.onosproject.incubator.net.intf.impl.InterfaceManagerTest Class Reference
Unit tests for InterfaceManager.
Public Member Functions
void setUp () throws Exception
void testGetInterfaces () throws Exception
void testGetInterfacesByPort () throws Exception
void testGetInterfacesByIp () throws Exception
void testGetMatchingInterface () throws Exception
void testGetInterfacesByVlan () throws Exception
void testAddInterface () throws Exception
void testUpdateInterface () throws Exception
void testRemoveInterface () throws Exception
Detailed Description
Unit tests for InterfaceManager.
Definition at line 47 of file InterfaceManagerTest.java.
Member Function Documentation
void org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.setUp () throws Exception
Definition at line 62 of file InterfaceManagerTest.java.
void org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testAddInterface () throws Exception
Definition at line 148 of file InterfaceManagerTest.java.
References org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfaces(), and org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfacesByVlan().
void org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testGetInterfaces () throws Exception
Definition at line 102 of file InterfaceManagerTest.java.
References org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfaces().
void org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testGetInterfacesByIp () throws Exception
Definition at line 116 of file InterfaceManagerTest.java.
References org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfacesByIp().
void org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testGetInterfacesByPort () throws Exception
Definition at line 107 of file InterfaceManagerTest.java.
References org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfacesByPort().
void org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testGetInterfacesByVlan () throws Exception
Definition at line 139 of file InterfaceManagerTest.java.
References org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfacesByVlan().
void org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testGetMatchingInterface () throws Exception
Definition at line 125 of file InterfaceManagerTest.java.
References org.onosproject.incubator.net.intf.impl.InterfaceManager.getMatchingInterface().
void org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testRemoveInterface () throws Exception
Definition at line 218 of file InterfaceManagerTest.java.
References org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfaces().
void org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testUpdateInterface () throws Exception
Definition at line 181 of file InterfaceManagerTest.java.
References org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfaces(), org.onosproject.incubator.net.intf.impl.InterfaceManager.getInterfacesByPort(), and org.onlab.packet.VlanId.vlanId().
The documentation for this class was generated from the following file:
incubator/net/src/test/java/org/onosproject/incubator/net/intf/impl/InterfaceManagerTest.java