onos: org.onosproject.rest.ApplicationsResourceTest Class Reference
org.onosproject.rest.ApplicationsResourceTest Class Reference
Unit tests for applications REST APIs.
Public Member Functions
void setUpMocks ()
Initializes test mocks and environment.
void tearDownMocks ()
Verifies test mocks.
void getAllApplicationsEmpty ()
Tests a GET of all applications when no applications are present.
void getAllApplicationsPopulated ()
Tests a GET of all applications with data.
void getSingleApplication ()
Tests a GET of a single application.
void deleteApplication ()
Tests a DELETE of a single application - this should attempt to uninstall it.
void deleteActiveApplication ()
Tests a DELETE of a single active application - this should attempt to uninstall it.
void postActiveApplication ()
Tests a POST operation to the "active" URL.
void postApplication ()
Tests a POST operation.
Public Member Functions inherited from org.onosproject.rest.ResourceTest
int getPort (int defaultPort)
Assigns an available port for the test.
AppDescriptor configure ()
Detailed Description
Unit tests for applications REST APIs.
Definition at line 60 of file ApplicationsResourceTest.java.
Member Function Documentation
void org.onosproject.rest.ApplicationsResourceTest.deleteActiveApplication ()
Tests a DELETE of a single active application - this should attempt to uninstall it.
Definition at line 282 of file ApplicationsResourceTest.java.
void org.onosproject.rest.ApplicationsResourceTest.deleteApplication ()
Tests a DELETE of a single application - this should attempt to uninstall it.
Definition at line 267 of file ApplicationsResourceTest.java.
void org.onosproject.rest.ApplicationsResourceTest.getAllApplicationsEmpty ()
Tests a GET of all applications when no applications are present.
Definition at line 207 of file ApplicationsResourceTest.java.
References org.onosproject.app.ApplicationService.getApplications().
void org.onosproject.rest.ApplicationsResourceTest.getAllApplicationsPopulated ()
Tests a GET of all applications with data.
Definition at line 221 of file ApplicationsResourceTest.java.
References org.onosproject.app.ApplicationService.getApplications().
void org.onosproject.rest.ApplicationsResourceTest.getSingleApplication ()
Tests a GET of a single application.
Definition at line 250 of file ApplicationsResourceTest.java.
void org.onosproject.rest.ApplicationsResourceTest.postActiveApplication ()
Tests a POST operation to the "active" URL.
This should attempt to activate the application.
Definition at line 297 of file ApplicationsResourceTest.java.
void org.onosproject.rest.ApplicationsResourceTest.postApplication ()
Tests a POST operation.
This should attempt to install the application.
Definition at line 312 of file ApplicationsResourceTest.java.
References org.onosproject.app.ApplicationAdminService.install().
void org.onosproject.rest.ApplicationsResourceTest.setUpMocks ()
Initializes test mocks and environment.
Definition at line 160 of file ApplicationsResourceTest.java.
References org.onosproject.app.ApplicationState.ACTIVE, org.onosproject.app.ApplicationService.getApplication(), org.onosproject.app.ApplicationService.getId(), and org.onosproject.app.ApplicationService.getState().
void org.onosproject.rest.ApplicationsResourceTest.tearDownMocks ()
Verifies test mocks.
Definition at line 199 of file ApplicationsResourceTest.java.
The documentation for this class was generated from the following file:
web/api/src/test/java/org/onosproject/rest/ApplicationsResourceTest.java