onos: org.onosproject.store.consistent.impl.DefaultAtomicCounter Class Reference
org.onosproject.store.consistent.impl.DefaultAtomicCounter Class Reference
Default implementation for a distributed AtomicCounter backed by partitioned Raft DB.
Public Member Functions
DefaultAtomicCounter (String name, Database database, boolean meteringEnabled)
long incrementAndGet ()
Atomically increment by one the current value.
long getAndIncrement ()
Atomically increment by one the current value.
long getAndAdd (long delta)
Atomically adds the given value to the current value.
long addAndGet (long delta)
Atomically adds the given value to the current value.
void set (long value)
Atomically sets the given value to the current value.
boolean compareAndSet (long expectedValue, long updateValue)
Atomically sets the given counter to the updated value if the current value is the expected value, otherwise no change occurs.
long get ()
Returns the current value of the counter without modifying it.
Detailed Description
Default implementation for a distributed AtomicCounter backed by partitioned Raft DB.
The initial value will be zero.
Definition at line 33 of file DefaultAtomicCounter.java.
Constructor & Destructor Documentation
org.onosproject.store.consistent.impl.DefaultAtomicCounter.DefaultAtomicCounter (String name, Database database, boolean meteringEnabled)
Definition at line 39 of file DefaultAtomicCounter.java.
Member Function Documentation
long org.onosproject.store.consistent.impl.DefaultAtomicCounter.addAndGet (long delta)
Atomically adds the given value to the current value.
Parameters
delta the value to add
Returns
updated value
Implements org.onosproject.store.service.AtomicCounter.
Definition at line 61 of file DefaultAtomicCounter.java.
References org.onosproject.store.service.AsyncAtomicCounter.getAndAdd().
boolean org.onosproject.store.consistent.impl.DefaultAtomicCounter.compareAndSet (long expectedValue, long updateValue)
Atomically sets the given counter to the updated value if the current value is the expected value, otherwise no change occurs.
Parameters
expectedValue the expected current value of the counter
updateValue the new value to be set
Returns
true if the update occurred and the expected value was equal to the current value, false otherwise
Implements org.onosproject.store.service.AtomicCounter.
Definition at line 71 of file DefaultAtomicCounter.java.
References org.onosproject.store.service.AsyncAtomicCounter.compareAndSet().
long org.onosproject.store.consistent.impl.DefaultAtomicCounter.get ()
Returns the current value of the counter without modifying it.
Returns
current value
Implements org.onosproject.store.service.AtomicCounter.
Definition at line 76 of file DefaultAtomicCounter.java.
References org.onosproject.store.service.AsyncAtomicCounter.get().
long org.onosproject.store.consistent.impl.DefaultAtomicCounter.getAndAdd (long delta)
Atomically adds the given value to the current value.
Parameters
delta the value to add
Returns
previous value
Implements org.onosproject.store.service.AtomicCounter.
Definition at line 56 of file DefaultAtomicCounter.java.
References org.onosproject.store.service.AsyncAtomicCounter.getAndAdd().
long org.onosproject.store.consistent.impl.DefaultAtomicCounter.getAndIncrement ()
Atomically increment by one the current value.
Returns
previous value
Implements org.onosproject.store.service.AtomicCounter.
Definition at line 51 of file DefaultAtomicCounter.java.
References org.onosproject.store.service.AsyncAtomicCounter.getAndIncrement().
long org.onosproject.store.consistent.impl.DefaultAtomicCounter.incrementAndGet ()
Atomically increment by one the current value.
Returns
updated value
Implements org.onosproject.store.service.AtomicCounter.
Definition at line 46 of file DefaultAtomicCounter.java.
References org.onosproject.store.service.AsyncAtomicCounter.incrementAndGet().
void org.onosproject.store.consistent.impl.DefaultAtomicCounter.set (long value)
Atomically sets the given value to the current value.
Parameters
value the value to set
Implements org.onosproject.store.service.AtomicCounter.
Definition at line 66 of file DefaultAtomicCounter.java.
References org.onosproject.store.service.AsyncAtomicCounter.set().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DefaultAtomicCounter.java