onos: org.onosproject.cluster.Leadership Class Reference
org.onosproject.cluster.Leadership Class Reference
Abstract leadership concept.
Public Member Functions
Leadership (String topic, NodeId leader, long epoch, long electedTime)
Leadership (String topic, NodeId leader, List< NodeId > candidates, long epoch, long electedTime)
Leadership (String topic, List< NodeId > candidates, long epoch, long electedTime)
String topic ()
The topic for which this leadership applies.
NodeId leader ()
The nodeId of leader for this topic.
List< NodeId > candidates ()
Returns an preference-ordered list of nodes that are in the leadership race for this topic.
long epoch ()
The epoch when the leadership was assumed.
long electedTime ()
The system time when the term started.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Abstract leadership concept.
The information carried by this construct include the topic of contention, the NodeIds of Nodes that could become leader for the topic, the epoch when the term for a given leader began, and the system time when the term began. Note:
The list of NodeIds may include the current leader at index 0, and the rest in decreasing preference order.
The epoch is the logical age of a Leadership construct, and should be used for comparing two Leaderships, but only of the same topic.
The leader may be null if its accuracy can't be guaranteed. This applies to CANDIDATES_CHANGED events and candidate board contents.
Definition at line 41 of file Leadership.java.
Constructor & Destructor Documentation
org.onosproject.cluster.Leadership.Leadership (String topic, NodeId leader, long epoch, long electedTime)
Definition at line 49 of file Leadership.java.
References org.onosproject.cluster.Leadership.electedTime(), org.onosproject.cluster.Leadership.epoch(), org.onosproject.cluster.Leadership.leader(), and org.onosproject.cluster.Leadership.topic().
Referenced by org.onosproject.cluster.Leadership.equals().
org.onosproject.cluster.Leadership.Leadership (String topic, NodeId leader, List< NodeId > candidates, long epoch, long electedTime)
Definition at line 57 of file Leadership.java.
References org.onosproject.cluster.Leadership.candidates(), org.onosproject.cluster.Leadership.electedTime(), org.onosproject.cluster.Leadership.epoch(), org.onosproject.cluster.Leadership.leader(), and org.onosproject.cluster.Leadership.topic().
org.onosproject.cluster.Leadership.Leadership (String topic, List< NodeId > candidates, long epoch, long electedTime)
Definition at line 66 of file Leadership.java.
References org.onosproject.cluster.Leadership.candidates(), org.onosproject.cluster.Leadership.electedTime(), org.onosproject.cluster.Leadership.epoch(), and org.onosproject.cluster.Leadership.topic().
Member Function Documentation
List<NodeId> org.onosproject.cluster.Leadership.candidates ()
Returns an preference-ordered list of nodes that are in the leadership race for this topic.
Returns
a list of NodeIds in priority-order, or an empty list.
Definition at line 100 of file Leadership.java.
Referenced by org.onosproject.cluster.Leadership.hashCode(), org.onosproject.cluster.Leadership.Leadership(), and org.onosproject.cluster.Leadership.toString().
long org.onosproject.cluster.Leadership.electedTime ()
The system time when the term started.
The elected time is initially set on the node coordinating the leader election using its local system time. Due to possible clock skew, relying on this value for determining event ordering is discouraged. Epoch is more appropriate for determining event ordering.
Returns
elected time.
Definition at line 129 of file Leadership.java.
Referenced by org.onosproject.cluster.Leadership.hashCode(), org.onosproject.cluster.Leadership.Leadership(), and org.onosproject.cluster.Leadership.toString().
long org.onosproject.cluster.Leadership.epoch ()
The epoch when the leadership was assumed.
Comparing epochs is only appropriate for leadership events for the same topic. The system guarantees that for any given topic the epoch for a new term is higher (not necessarily by 1) than the epoch for any previous term.
Returns
leadership epoch
Definition at line 114 of file Leadership.java.
Referenced by org.onosproject.cluster.Leadership.hashCode(), org.onosproject.cluster.Leadership.Leadership(), and org.onosproject.cluster.Leadership.toString().
boolean org.onosproject.cluster.Leadership.equals (Object obj)
Definition at line 139 of file Leadership.java.
References org.onosproject.cluster.Leadership.Leadership().
int org.onosproject.cluster.Leadership.hashCode ()
Definition at line 134 of file Leadership.java.
References org.onosproject.cluster.Leadership.candidates(), org.onosproject.cluster.Leadership.electedTime(), org.onosproject.cluster.Leadership.epoch(), org.onosproject.cluster.Leadership.leader(), and org.onosproject.cluster.Leadership.topic().
NodeId org.onosproject.cluster.Leadership.leader ()
The nodeId of leader for this topic.
Returns
leader node.
Definition at line 90 of file Leadership.java.
Referenced by org.onosproject.cluster.Leadership.hashCode(), org.onosproject.cluster.Leadership.Leadership(), and org.onosproject.cluster.Leadership.toString().
String org.onosproject.cluster.Leadership.topic ()
The topic for which this leadership applies.
Returns
leadership topic.
Definition at line 80 of file Leadership.java.
Referenced by org.onosproject.cluster.Leadership.hashCode(), org.onosproject.cluster.Leadership.Leadership(), and org.onosproject.cluster.Leadership.toString().
String org.onosproject.cluster.Leadership.toString ()
Definition at line 155 of file Leadership.java.
References org.onosproject.cluster.Leadership.candidates(), org.onosproject.cluster.Leadership.electedTime(), org.onosproject.cluster.Leadership.epoch(), org.onosproject.cluster.Leadership.leader(), and org.onosproject.cluster.Leadership.topic().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/cluster/Leadership.java