onos: org.onosproject.incubator.net.mcast.impl.MulticastData Class Reference
org.onosproject.incubator.net.mcast.impl.MulticastData Class Reference
Simple entity maintaining a mapping between a source and a collection of sink connect points.
Public Member Functions
MulticastData (ConnectPoint source, List< ConnectPoint > sinks)
MulticastData (ConnectPoint source, ConnectPoint sink)
MulticastData (ConnectPoint source)
ConnectPoint source ()
List< ConnectPoint > sinks ()
void appendSink (ConnectPoint sink)
boolean removeSink (ConnectPoint sink)
boolean isEmpty ()
Static Public Member Functions
static MulticastData empty ()
Detailed Description
Simple entity maintaining a mapping between a source and a collection of sink connect points.
Definition at line 31 of file MulticastData.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.mcast.impl.MulticastData.MulticastData (ConnectPoint source, List< ConnectPoint > sinks)
Definition at line 43 of file MulticastData.java.
References org.onosproject.incubator.net.mcast.impl.MulticastData.isEmpty().
org.onosproject.incubator.net.mcast.impl.MulticastData.MulticastData (ConnectPoint source, ConnectPoint sink)
Definition at line 49 of file MulticastData.java.
References org.onosproject.incubator.net.mcast.impl.MulticastData.isEmpty().
org.onosproject.incubator.net.mcast.impl.MulticastData.MulticastData (ConnectPoint source)
Definition at line 55 of file MulticastData.java.
References org.onosproject.incubator.net.mcast.impl.MulticastData.isEmpty().
Member Function Documentation
void org.onosproject.incubator.net.mcast.impl.MulticastData.appendSink (ConnectPoint sink)
Definition at line 69 of file MulticastData.java.
static MulticastData org.onosproject.incubator.net.mcast.impl.MulticastData.empty () static
Definition at line 81 of file MulticastData.java.
Referenced by org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.fetchSinks(), and org.onosproject.incubator.net.mcast.impl.MulticastRouteManager.fetchSource().
boolean org.onosproject.incubator.net.mcast.impl.MulticastData.isEmpty ()
Definition at line 77 of file MulticastData.java.
Referenced by org.onosproject.incubator.net.mcast.impl.MulticastData.MulticastData().
boolean org.onosproject.incubator.net.mcast.impl.MulticastData.removeSink (ConnectPoint sink)
Definition at line 73 of file MulticastData.java.
List<ConnectPoint> org.onosproject.incubator.net.mcast.impl.MulticastData.sinks ()
Definition at line 65 of file MulticastData.java.
ConnectPoint org.onosproject.incubator.net.mcast.impl.MulticastData.source ()
Definition at line 61 of file MulticastData.java.
The documentation for this class was generated from the following file:
incubator/net/src/main/java/org/onosproject/incubator/net/mcast/impl/MulticastData.java