onos: org.onosproject.sdnip.IntentSyncTest Class Reference
org.onosproject.sdnip.IntentSyncTest Class Reference
This class tests the intent synchronization function in the IntentSynchronizer class.
Public Member Functions
void setUp () throws Exception
void testIntentSync () throws TestUtilsException
Tests the synchronization behavior of intent synchronizer.
void testSubmit ()
Tests the behavior of the submit API, both when the synchronizer has leadership and when it does not.
void testWithdraw ()
Tests the behavior of the withdraw API, both when the synchronizer has leadership and when it does not.
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Additional Inherited Members
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
This class tests the intent synchronization function in the IntentSynchronizer class.
Definition at line 67 of file IntentSyncTest.java.
Member Function Documentation
void org.onosproject.sdnip.IntentSyncTest.setUp () throws Exception
Definition at line 93 of file IntentSyncTest.java.
void org.onosproject.sdnip.IntentSyncTest.testIntentSync () throws TestUtilsException
Tests the synchronization behavior of intent synchronizer.
We set up a discrepancy between the intent service state and the intent synchronizer's state and ensure that this is reconciled correctly.
Exceptions
TestUtilsException
Definition at line 154 of file IntentSyncTest.java.
References org.onosproject.sdnip.IntentUtils.equals(), org.onosproject.net.intent.IntentService.getIntents(), org.onosproject.net.intent.IntentService.getIntentState(), org.onosproject.net.intent.IntentState.INSTALLED, org.onosproject.net.intent.Intent.key(), org.onlab.packet.Ip4Prefix.valueOf(), and org.onosproject.net.intent.IntentState.WITHDRAWING.
void org.onosproject.sdnip.IntentSyncTest.testSubmit ()
Tests the behavior of the submit API, both when the synchronizer has leadership and when it does not.
Definition at line 280 of file IntentSyncTest.java.
References org.onosproject.net.intent.IntentService.getIntents(), and onosUploadBits.prefix.
void org.onosproject.sdnip.IntentSyncTest.testWithdraw ()
Tests the behavior of the withdraw API, both when the synchronizer has leadership and when it does not.
Definition at line 317 of file IntentSyncTest.java.
References org.onosproject.net.intent.IntentService.getIntents(), and onosUploadBits.prefix.
The documentation for this class was generated from the following file:
apps/sdnip/src/test/java/org/onosproject/sdnip/IntentSyncTest.java