onos: org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr Class Reference
org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr Class Reference
Implements BGP prefix OSPF Forwarding address attribute.
Public Member Functions
BgpPrefixAttrOspfFwdAddr (short lsAttrLength, Ip4Address ip4RouterId, Ip6Address ip6RouterId)
Constructor to initialize the value.
Ip4Address ospfv4FwdAddr ()
Returns IPV4 Address of OSPF forwarding address.
Ip6Address ospfv6FwdAddr ()
Returns IPV6 Address of OSPF forwarding address.
short ospfFwdAddrLen ()
Returns OSPF forwarding address length.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpPrefixAttrOspfFwdAddr of (final short lsAttrLength, final Ip4Address ip4RouterId, final Ip6Address ip6RouterId)
Returns object of this class with specified values.
static BgpPrefixAttrOspfFwdAddr read (ChannelBuffer cb) throws BgpParseException
Reads the OSPF Forwarding Address.
Static Public Attributes
static final int ATTR_PREFIX_OSPFFWDADDR = 1156
static final int IPV4_LEN = 4
static final int IPV6_LEN = 16
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP prefix OSPF Forwarding address attribute.
Definition at line 35 of file BgpPrefixAttrOspfFwdAddr.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.BgpPrefixAttrOspfFwdAddr (short lsAttrLength, Ip4Address ip4RouterId, Ip6Address ip6RouterId)
Constructor to initialize the value.
Parameters
lsAttrLength length of the IP address
ip4RouterId Valid IPV4 address if length is 4 else null
ip6RouterId Valid IPV6 address if length is 16 else null
Definition at line 56 of file BgpPrefixAttrOspfFwdAddr.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.equals(), and org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.of().
Member Function Documentation
int org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 189 of file BgpPrefixAttrOspfFwdAddr.java.
boolean org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.equals (Object obj)
Definition at line 155 of file BgpPrefixAttrOspfFwdAddr.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.BgpPrefixAttrOspfFwdAddr(), and org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.IPV4_LEN.
short org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 141 of file BgpPrefixAttrOspfFwdAddr.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.ATTR_PREFIX_OSPFFWDADDR.
int org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.hashCode ()
Definition at line 146 of file BgpPrefixAttrOspfFwdAddr.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.IPV4_LEN.
static BgpPrefixAttrOspfFwdAddr org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.of (final short lsAttrLength, final Ip4Address ip4RouterId, final Ip6Address ip6RouterId) static
Returns object of this class with specified values.
Parameters
lsAttrLength length of the IP address
ip4RouterId Valid IPV4 address if length is 4 else null
ip6RouterId Valid IPV6 address if length is 16 else null
Returns
object of BgpPrefixAttrOspfFwdAddr
Definition at line 71 of file BgpPrefixAttrOspfFwdAddr.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.BgpPrefixAttrOspfFwdAddr().
short org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.ospfFwdAddrLen ()
Returns OSPF forwarding address length.
Returns
length of the ip address
Definition at line 136 of file BgpPrefixAttrOspfFwdAddr.java.
Ip4Address org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.ospfv4FwdAddr ()
Returns IPV4 Address of OSPF forwarding address.
Returns
IPV4 address
Definition at line 118 of file BgpPrefixAttrOspfFwdAddr.java.
Ip6Address org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.ospfv6FwdAddr ()
Returns IPV6 Address of OSPF forwarding address.
Returns
IPV6 address
Definition at line 127 of file BgpPrefixAttrOspfFwdAddr.java.
static BgpPrefixAttrOspfFwdAddr org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.read (ChannelBuffer cb) throws BgpParseException static
Reads the OSPF Forwarding Address.
Parameters
cb ChannelBuffer
Returns
object of BgpPrefixAttrOSPFFwdAddr
Exceptions
BgpParseException while parsing BgpPrefixAttrOspfFwdAddr
Definition at line 85 of file BgpPrefixAttrOspfFwdAddr.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.IPV4_LEN, org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.IPV6_LEN, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.toString ()
Definition at line 178 of file BgpPrefixAttrOspfFwdAddr.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.IPV4_LEN.
int org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 172 of file BgpPrefixAttrOspfFwdAddr.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.ATTR_PREFIX_OSPFFWDADDR = 1156 static
Definition at line 40 of file BgpPrefixAttrOspfFwdAddr.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.getType().
final int org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.IPV4_LEN = 4 static
Definition at line 41 of file BgpPrefixAttrOspfFwdAddr.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.equals(), org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.hashCode(), org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.read(), and org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.toString().
final int org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.IPV6_LEN = 16 static
Definition at line 42 of file BgpPrefixAttrOspfFwdAddr.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.read().
final Logger org.onosproject.bgpio.types.attr.BgpPrefixAttrOspfFwdAddr.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpPrefixAttrOspfFwdAddr.class)
Definition at line 37 of file BgpPrefixAttrOspfFwdAddr.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpPrefixAttrOspfFwdAddr.java