onos: org.onosproject.driver.netconf.NetconfControllerConfig Class Reference
org.onosproject.driver.netconf.NetconfControllerConfig Class Reference
Implementation of controller config which allows to get and set controllers through the Netconf protocol.
Public Member Functions
List< ControllerInfo > getControllers ()
Obtain the list of controller which are currently configured.
void setControllers (List< ControllerInfo > controllers)
Set a list of controllers on a device.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Detailed Description
Implementation of controller config which allows to get and set controllers through the Netconf protocol.
Definition at line 40 of file NetconfControllerConfig.java.
Member Function Documentation
List<ControllerInfo> org.onosproject.driver.netconf.NetconfControllerConfig.getControllers ()
Obtain the list of controller which are currently configured.
Returns
a list for controller descriptions
Implements org.onosproject.net.behaviour.ControllerConfig.
Definition at line 46 of file NetconfControllerConfig.java.
References att-onos-ext.controllers, find-flow.deviceId, and org.onosproject.net.driver.AbstractHandlerBehaviour.handler().
void org.onosproject.driver.netconf.NetconfControllerConfig.setControllers (List< ControllerInfo > controllers)
Set a list of controllers on a device.
Parameters
controllers a list of controller descriptions
Implements org.onosproject.net.behaviour.ControllerConfig.
Definition at line 60 of file NetconfControllerConfig.java.
References att-onos-ext.controllers, create-flow.device, find-flow.deviceId, org.onosproject.netconf.NetconfDevice.getSession(), and org.onosproject.net.driver.AbstractHandlerBehaviour.handler().
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/netconf/NetconfControllerConfig.java