onos: org.onosproject.provider.host.impl.HostLocationProviderTest Class Reference
org.onosproject.provider.host.impl.HostLocationProviderTest Class Reference
Public Member Functions
void setUp ()
void basics ()
void events ()
void removeHostByDeviceRemove ()
void removeHostByDeviceOffline ()
void removeHostByDevicePortDown ()
void testReceiveArp ()
When receiving ARP, updates location and IP.
void testReceiveIpv4 ()
When receiving IPv4, updates location only.
void testReceiveNa ()
When receiving NeighborAdvertisement, updates location and IP.
void testReceiveNs ()
When receiving NeighborSolicitation, updates location and IP.
void testReceivesRa ()
When receiving RouterAdvertisement, ignores it.
void testReceiveRs ()
When receiving RouterSolicitation, ignores it.
void testReceiveDad ()
When receiving Duplicate Address Detection (DAD), ignores it.
void testReceiveIpv6Multicast ()
When receiving IPv6 multicast packet, ignores it.
void testReceiveIpv6Unicast ()
When receiving IPv6 unicast packet, updates location only.
void tearDown ()
Static Public Attributes
static final
ComponentContextAdapter CTX_FOR_NO_REMOVE
Detailed Description
Definition at line 86 of file HostLocationProviderTest.java.
Member Function Documentation
void org.onosproject.provider.host.impl.HostLocationProviderTest.basics ()
Definition at line 176 of file HostLocationProviderTest.java.
void org.onosproject.provider.host.impl.HostLocationProviderTest.events ()
Definition at line 182 of file HostLocationProviderTest.java.
void org.onosproject.provider.host.impl.HostLocationProviderTest.removeHostByDeviceOffline ()
Definition at line 230 of file HostLocationProviderTest.java.
References create-flow.device, find-flow.deviceId, and org.onosproject.net.provider.ProviderId.NONE.
void org.onosproject.provider.host.impl.HostLocationProviderTest.removeHostByDevicePortDown ()
Definition at line 247 of file HostLocationProviderTest.java.
References create-flow.device, find-flow.deviceId, and org.onosproject.net.provider.ProviderId.NONE.
void org.onosproject.provider.host.impl.HostLocationProviderTest.removeHostByDeviceRemove ()
Definition at line 213 of file HostLocationProviderTest.java.
References create-flow.device, find-flow.deviceId, and org.onosproject.net.provider.ProviderId.NONE.
void org.onosproject.provider.host.impl.HostLocationProviderTest.setUp ()
Definition at line 156 of file HostLocationProviderTest.java.
References org.onosproject.provider.host.impl.HostLocationProviderTest.CTX_FOR_NO_REMOVE, org.onosproject.core.ApplicationId.name(), and org.onosproject.core.CoreService.registerApplication().
void org.onosproject.provider.host.impl.HostLocationProviderTest.tearDown ()
Definition at line 369 of file HostLocationProviderTest.java.
void org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveArp ()
When receiving ARP, updates location and IP.
Definition at line 269 of file HostLocationProviderTest.java.
void org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveDad ()
When receiving Duplicate Address Detection (DAD), ignores it.
Definition at line 340 of file HostLocationProviderTest.java.
void org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveIpv4 ()
When receiving IPv4, updates location only.
Definition at line 282 of file HostLocationProviderTest.java.
void org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveIpv6Multicast ()
When receiving IPv6 multicast packet, ignores it.
Definition at line 349 of file HostLocationProviderTest.java.
void org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveIpv6Unicast ()
When receiving IPv6 unicast packet, updates location only.
Definition at line 358 of file HostLocationProviderTest.java.
References org.onosproject.net.host.HostDescription.hwAddress(), org.onosproject.net.host.HostDescription.ipAddress(), org.onosproject.net.host.HostDescription.location(), and org.onosproject.net.host.HostDescription.vlan().
void org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveNa ()
When receiving NeighborAdvertisement, updates location and IP.
Definition at line 295 of file HostLocationProviderTest.java.
References org.onosproject.net.host.HostDescription.hwAddress(), org.onosproject.net.host.HostDescription.ipAddress(), org.onosproject.net.host.HostDescription.location(), and org.onosproject.net.host.HostDescription.vlan().
void org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveNs ()
When receiving NeighborSolicitation, updates location and IP.
Definition at line 309 of file HostLocationProviderTest.java.
void org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveRs ()
When receiving RouterSolicitation, ignores it.
Definition at line 331 of file HostLocationProviderTest.java.
void org.onosproject.provider.host.impl.HostLocationProviderTest.testReceivesRa ()
When receiving RouterAdvertisement, ignores it.
Definition at line 322 of file HostLocationProviderTest.java.
Member Data Documentation
final ComponentContextAdapter org.onosproject.provider.host.impl.HostLocationProviderTest.CTX_FOR_NO_REMOVE static
Initial value:
=
            new ComponentContextAdapter() {
                @Override
                public Dictionary getProperties() {
                    return new Hashtable();
                }
            }
Definition at line 133 of file HostLocationProviderTest.java.
Referenced by org.onosproject.provider.host.impl.HostLocationProviderTest.setUp().
The documentation for this class was generated from the following file:
providers/host/src/test/java/org/onosproject/provider/host/impl/HostLocationProviderTest.java