onos: org.onlab.packet.IpAddress Class Reference
org.onlab.packet.IpAddress Class Reference
A class representing an IP address.
Classes
enum Version
Public Member Functions
Version version ()
Returns the IP version of this address.
boolean isIp4 ()
Tests whether the IP version of this address is IPv4.
boolean isIp6 ()
Tests whether the IP version of this address is IPv6.
Ip4Address getIp4Address ()
Gets the Ip4Address view of the IP address.
Ip6Address getIp6Address ()
Gets the Ip6Address view of the IP address.
byte[] toOctets ()
Returns the IP address as a byte array.
boolean isZero ()
Check if this IP address is zero.
boolean isSelfAssigned ()
Check if this IP address is self-assigned.
int compareTo (IpAddress o)
int hashCode ()
boolean equals (Object obj)
String toString ()
IpPrefix toIpPrefix ()
Generates an IP prefix.
Static Public Member Functions
static int byteLength (Version version)
Computes the IP address byte length for a given IP version.
static IpAddress valueOf (int value)
Converts an integer into an IPv4 address.
static IpAddress valueOf (Version version, byte[] value)
Converts a byte array into an IP address.
static IpAddress valueOf (Version version, byte[] value, int offset)
Converts a byte array and a given offset from the beginning of the array into an IP address.
static IpAddress valueOf (InetAddress inetAddress)
Converts an InetAddress into an IP address.
static IpAddress valueOf (String value)
Converts an IPv4 or IPv6 string literal (e.g., "10.2.3.4" or "1111:2222::8888") into an IP address.
static IpAddress makeMaskPrefix (Version version, int prefixLength)
Creates an IP network mask prefix.
static IpAddress makeMaskedAddress (final IpAddress address, int prefixLength)
Creates an IP address by masking it with a network mask of given mask length.
Static Public Attributes
static final int INET_BYTE_LENGTH = 4
static final int INET_BIT_LENGTH = INET_BYTE_LENGTH * Byte.SIZE
static final int INET6_BYTE_LENGTH = 16
static final int INET6_BIT_LENGTH = INET6_BYTE_LENGTH * Byte.SIZE
Protected Member Functions
IpAddress (Version version, byte[] value)
Constructor for given IP address version and address octets.
Detailed Description
A class representing an IP address.
This class is immutable.
Definition at line 32 of file IpAddress.java.
Constructor & Destructor Documentation
org.onlab.packet.IpAddress.IpAddress (Version version, byte[] value) protected
Constructor for given IP address version and address octets.
Parameters
version the IP address version
value the IP address value stored in network byte order (i.e., the most significant byte first)
Exceptions
IllegalArgumentException if the arguments are invalid
Definition at line 55 of file IpAddress.java.
References org.onlab.packet.IpAddress.INET6_BYTE_LENGTH, org.onlab.packet.IpAddress.INET_BYTE_LENGTH, and org.onlab.packet.IpAddress.version().
Referenced by org.onlab.packet.IpAddress.equals(), org.onlab.packet.IpAddress.makeMaskPrefix(), org.onlab.packet.IpAddress.toIpPrefix(), and org.onlab.packet.IpAddress.valueOf().
Member Function Documentation
static int org.onlab.packet.IpAddress.byteLength (Version version) static
Computes the IP address byte length for a given IP version.
Parameters
version the IP version
Returns
the IP address byte length for the IP version
Exceptions
IllegalArgumentException if the IP version is invalid
Definition at line 151 of file IpAddress.java.
References org.onlab.packet.IpAddress.INET6_BYTE_LENGTH, org.onlab.packet.IpAddress.INET_BYTE_LENGTH, and org.onlab.packet.IpAddress.version().
Referenced by org.onlab.nio.service.DefaultMessageStream.read(), and org.onlab.packet.IpAddressTest.testAddrByteLength().
int org.onlab.packet.IpAddress.compareTo (IpAddress o)
Definition at line 318 of file IpAddress.java.
References find-link-in-cluster.length, and org.onlab.packet.IpAddress.version().
Referenced by org.onlab.packet.Ip4AddressTest.testComparisonIPv4(), org.onlab.packet.IpAddressTest.testComparisonIPv4(), org.onlab.packet.Ip6AddressTest.testComparisonIPv6(), and org.onlab.packet.IpAddressTest.testComparisonIPv6().
boolean org.onlab.packet.IpAddress.equals (Object obj)
Definition at line 339 of file IpAddress.java.
References org.onlab.packet.IpAddress.IpAddress(), and org.onlab.packet.IpAddress.version().
Referenced by org.onlab.packet.IGMPMembership.equals(), org.onlab.packet.pim.PIMAddrUnicast.equals(), org.onlab.packet.pim.PIMAddrGroup.equals(), org.onlab.packet.pim.PIMAddrSource.equals(), and org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.fixedIpIsUsed().
Ip4Address org.onlab.packet.IpAddress.getIp4Address ()
Gets the Ip4Address view of the IP address.
Returns
the Ip4Address view of the IP address if it is IPv4, otherwise null
Definition at line 105 of file IpAddress.java.
References org.onlab.packet.IpAddress.isIp4().
Ip6Address org.onlab.packet.IpAddress.getIp6Address ()
Gets the Ip6Address view of the IP address.
Returns
the Ip6Address view of the IP address if it is IPv6, otherwise null
Definition at line 123 of file IpAddress.java.
References org.onlab.packet.IpAddress.isIp6().
int org.onlab.packet.IpAddress.hashCode ()
Definition at line 334 of file IpAddress.java.
References org.onlab.packet.IpAddress.version().
boolean org.onlab.packet.IpAddress.isIp4 ()
Tests whether the IP version of this address is IPv4.
Returns
true if the IP version of this address is IPv4, otherwise false.
Definition at line 86 of file IpAddress.java.
References org.onlab.packet.Ip4Address.VERSION, and org.onlab.packet.IpAddress.version().
Referenced by org.onlab.packet.IpAddress.getIp4Address(), org.onosproject.routing.impl.Router.getLongestMatchableRouteEntry(), org.onosproject.routing.config.impl.RoutingConfigurationImpl.isIpAddressLocal(), org.onlab.packet.IpAddress.isSelfAssigned(), org.onlab.packet.pim.PIMAddrUnicast.setAddr(), org.onlab.packet.pim.PIMAddrGroup.setAddr(), org.onlab.packet.pim.PIMAddrSource.setAddr(), org.onosproject.pcep.controller.impl.PcepClientImpl.setChannel(), org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.setChannel(), org.onosproject.bgp.controller.impl.BgpPeerImpl.setChannel(), org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityInternetToHost(), org.onlab.packet.IpAddressTest.testIsIp4(), and org.onlab.packet.IpAddress.toIpPrefix().
boolean org.onlab.packet.IpAddress.isIp6 ()
Tests whether the IP version of this address is IPv6.
Returns
true if the IP version of this address is IPv6, otherwise false.
Definition at line 95 of file IpAddress.java.
References org.onlab.packet.Ip6Address.VERSION, and org.onlab.packet.IpAddress.version().
Referenced by org.onlab.packet.IpAddress.getIp6Address(), and org.onlab.packet.IpAddressTest.testIsIp6().
boolean org.onlab.packet.IpAddress.isSelfAssigned ()
Check if this IP address is self-assigned.
Returns
true if this address is self-assigned
Definition at line 313 of file IpAddress.java.
References org.onlab.packet.IpAddress.isIp4().
Referenced by org.onlab.packet.IpAddressTest.testIsSelfAssignedIpv4().
boolean org.onlab.packet.IpAddress.isZero ()
Check if this IP address is zero.
Returns
true if this address is zero
Definition at line 299 of file IpAddress.java.
Referenced by org.onlab.packet.IpAddressTest.testIsZeroIPv4(), and org.onlab.packet.IpAddressTest.testIsZeroIPv6().
static IpAddress org.onlab.packet.IpAddress.makeMaskedAddress (final IpAddress address, int prefixLength) static
Creates an IP address by masking it with a network mask of given mask length.
Parameters
address the address to mask
prefixLength the length of the mask prefix. Must be in the interval [0, 32] for IPv4, or [0, 128] for IPv6
Returns
a new IP address that is masked with a mask prefix of the specified length
Exceptions
IllegalArgumentException if the prefix length is invalid
Definition at line 280 of file IpAddress.java.
References onos.net.
static IpAddress org.onlab.packet.IpAddress.makeMaskPrefix (Version version, int prefixLength) static
Creates an IP network mask prefix.
Parameters
version the IP address version
prefixLength the length of the mask prefix. Must be in the interval [0, 32] for IPv4, or [0, 128] for IPv6
Returns
a new IP address that contains a mask prefix of the specified length
Exceptions
IllegalArgumentException if the arguments are invalid
Definition at line 264 of file IpAddress.java.
References org.onlab.packet.IpAddress.IpAddress().
IpPrefix org.onlab.packet.IpAddress.toIpPrefix ()
Generates an IP prefix.
Returns
the IP prefix of the IP address
Definition at line 378 of file IpAddress.java.
References org.onlab.packet.Ip6Address.BIT_LENGTH, org.onlab.packet.Ip4Address.BIT_LENGTH, org.onlab.packet.IpAddress.Version.INET, org.onlab.packet.IpAddress.Version.INET6, org.onlab.packet.IpAddress.IpAddress(), and org.onlab.packet.IpAddress.isIp4().
byte [] org.onlab.packet.IpAddress.toOctets ()
Returns the IP address as a byte array.
Returns
a byte array
Definition at line 140 of file IpAddress.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.segmentrouting.ArpHandler.sendArpRequest(), org.onlab.packet.Ip4AddressTest.testAddressToOctetsIPv4(), org.onlab.packet.IpAddressTest.testAddressToOctetsIPv4(), org.onlab.packet.Ip6AddressTest.testAddressToOctetsIPv6(), org.onlab.packet.IpAddressTest.testAddressToOctetsIPv6(), org.onlab.packet.ArpTest.testDeserialize(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExist(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExistWithVlan(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExist(), and org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExistWithVlan().
String org.onlab.packet.IpAddress.toString ()
Definition at line 359 of file IpAddress.java.
References org.onlab.packet.IpAddress.version().
Referenced by org.onosproject.routing.config.BgpConfig.addPeerToSpeaker(), org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.pim.impl.PIMPacketHandler.PIMPacketProcessor.process(), org.onosproject.routing.config.BgpConfig.removePeerFromSpeaker(), org.onosproject.dhcp.impl.DhcpManager.setStaticMapping(), org.onlab.packet.Ip4AddressTest.testMakeMaskPrefixIPv4(), org.onlab.packet.IpAddressTest.testMakeMaskPrefixIPv4(), org.onlab.packet.Ip6AddressTest.testMakeMaskPrefixIPv6(), org.onlab.packet.IpAddressTest.testMakeMaskPrefixIPv6(), org.onlab.packet.Ip4AddressTest.testToStringIPv4(), org.onlab.packet.IpAddressTest.testToStringIPv4(), org.onlab.packet.Ip6AddressTest.testToStringIPv6(), org.onlab.packet.IpAddressTest.testToStringIPv6(), org.onlab.packet.Ip4AddressTest.testValueOfByteArrayIPv4(), org.onlab.packet.IpAddressTest.testValueOfByteArrayIPv4(), org.onlab.packet.Ip6AddressTest.testValueOfByteArrayIPv6(), org.onlab.packet.IpAddressTest.testValueOfByteArrayIPv6(), org.onlab.packet.Ip4AddressTest.testValueOfByteArrayOffsetIPv4(), org.onlab.packet.IpAddressTest.testValueOfByteArrayOffsetIPv4(), org.onlab.packet.Ip6AddressTest.testValueOfByteArrayOffsetIPv6(), org.onlab.packet.IpAddressTest.testValueOfByteArrayOffsetIPv6(), org.onlab.packet.Ip4AddressTest.testValueOfForIntegerIPv4(), org.onlab.packet.IpAddressTest.testValueOfForIntegerIPv4(), org.onlab.packet.Ip4AddressTest.testValueOfStringIPv4(), org.onlab.packet.IpAddressTest.testValueOfStringIPv4(), org.onlab.packet.Ip6AddressTest.testValueOfStringIPv6(), org.onlab.packet.IpAddressTest.testValueOfStringIPv6(), org.onosproject.pcep.controller.PccId.uri(), and org.onosproject.bgp.controller.BgpId.uri().
static IpAddress org.onlab.packet.IpAddress.valueOf (int value) static
Converts an integer into an IPv4 address.
Parameters
value an integer representing an IPv4 address value
Returns
an IP address
Definition at line 169 of file IpAddress.java.
References org.onlab.packet.IpAddress.Version.INET, org.onlab.packet.IpAddress.INET_BYTE_LENGTH, and org.onlab.packet.IpAddress.IpAddress().
Referenced by org.onosproject.store.cluster.impl.StaticClusterMetadataStore.activate(), org.onosproject.store.trivial.SimpleMastershipStore.activate(), org.onosproject.driver.netconf.XmlConfigParserTest.basics(), org.onosproject.bgp.controller.BgpId.bgpId(), org.onosproject.routing.config.BgpConfig.bgpSpeakers(), org.onosproject.driver.netconf.XmlConfigParserTest.controllersConfig(), org.onosproject.cordvtn.CordVtnConfig.cordVtnNodes(), org.onosproject.codec.impl.FlowRuleCodecTest.decodeInstructionsFlowTest(), org.onosproject.cordvtn.cli.CordVtnNodeAddCommand.execute(), org.onosproject.vtnrsc.cli.floatingip.FloatingIpCreateCommand.execute(), org.onosproject.vtnrsc.cli.subnet.SubnetCreateCommand.execute(), org.onosproject.vtnrsc.cli.subnet.SubnetUpdateCommand.execute(), org.onosproject.provider.netconf.device.impl.NetconfProviderConfig.getDevicesAddresses(), org.onosproject.netconf.ctl.NetconfControllerImpl.getNetconfDevice(), org.onosproject.ovsdb.controller.driver.OvsdbControllerAdapter.getNodeIds(), org.onosproject.pcep.controller.PccId.pccid(), org.onlab.packet.IpPrefixTest.testAddressAndPrefixLengthIPv4(), org.onlab.packet.IpPrefixTest.testAddressAndPrefixLengthIPv6(), org.onlab.packet.IpPrefixTest.testContainsIpAddressIPv4(), org.onlab.packet.IpPrefixTest.testContainsIpAddressIPv6(), org.onlab.packet.IpAddressTest.testEqualityIPv4(), org.onlab.packet.IpAddressTest.testEqualityIPv6(), org.onosproject.rest.HostResourceTest.testHostsArray(), org.onosproject.store.serializers.KryoSerializerTest.testIpAddress(), org.onosproject.sdnip.PeerConnectivityManagerTest.testNullInterfaces(), org.onlab.packet.IpPrefix.valueOf(), and org.onlab.packet.IpAddress.valueOf().
static IpAddress org.onlab.packet.IpAddress.valueOf (Version version, byte[] value) static
Converts a byte array into an IP address.
Parameters
version the IP address version
value the IP address value stored in network byte order (i.e., the most significant byte first)
Returns
an IP address
Exceptions
IllegalArgumentException if the arguments are invalid
Definition at line 184 of file IpAddress.java.
References org.onlab.packet.IpAddress.IpAddress().
static IpAddress org.onlab.packet.IpAddress.valueOf (Version version, byte[] value, int offset) static
Converts a byte array and a given offset from the beginning of the array into an IP address.
The IP address is stored in network byte order (i.e., the most significant byte first).
Parameters
version the IP address version
value the value to use
offset the offset in bytes from the beginning of the byte array
Returns
an IP address
Exceptions
IllegalArgumentException if the arguments are invalid
Definition at line 201 of file IpAddress.java.
References find-link-in-cluster.length, and org.onlab.packet.IpAddress.version().
static IpAddress org.onlab.packet.IpAddress.valueOf (InetAddress inetAddress) static
Converts an InetAddress into an IP address.
Parameters
inetAddress the InetAddress value to use
Returns
an IP address
Exceptions
IllegalArgumentException if the argument is invalid
Definition at line 215 of file IpAddress.java.
References org.onlab.packet.IpAddress.Version.INET, org.onlab.packet.IpAddress.Version.INET6, org.onlab.packet.IpAddress.INET6_BYTE_LENGTH, org.onlab.packet.IpAddress.INET_BYTE_LENGTH, and org.onlab.packet.IpAddress.IpAddress().
static IpAddress org.onlab.packet.IpAddress.valueOf (String value) static
Converts an IPv4 or IPv6 string literal (e.g., "10.2.3.4" or "1111:2222::8888") into an IP address.
Parameters
value an IP address value in string form
Returns
an IP address
Exceptions
IllegalArgumentException if the argument is invalid
Definition at line 243 of file IpAddress.java.
References org.onlab.packet.IpAddress.valueOf().
Version org.onlab.packet.IpAddress.version ()
Returns the IP version of this address.
Returns
the version
Definition at line 77 of file IpAddress.java.
Referenced by org.onlab.packet.IpAddress.byteLength(), org.onlab.packet.IpAddress.compareTo(), org.onlab.packet.IpAddress.equals(), org.onlab.packet.IpAddress.hashCode(), org.onlab.packet.IpAddress.IpAddress(), org.onlab.packet.IpAddress.isIp4(), org.onlab.packet.IpAddress.isIp6(), org.onlab.packet.Ip4AddressTest.testVersion(), org.onlab.packet.IpAddress.toString(), and org.onlab.packet.IpAddress.valueOf().
Member Data Documentation
final int org.onlab.packet.IpAddress.INET6_BIT_LENGTH = INET6_BYTE_LENGTH * Byte.SIZE static
Definition at line 42 of file IpAddress.java.
Referenced by org.onlab.packet.IpAddressTest.testAddrBitLength().
final int org.onlab.packet.IpAddress.INET6_BYTE_LENGTH = 16 static
Definition at line 41 of file IpAddress.java.
Referenced by org.onlab.packet.IpAddress.byteLength(), org.onlab.packet.IpAddress.IpAddress(), org.onosproject.store.serializers.IpAddressSerializer.read(), org.onosproject.store.serializers.IpPrefixSerializer.read(), org.onlab.packet.IpAddressTest.testAddrByteLength(), org.onlab.packet.Ip6Address.valueOf(), org.onlab.packet.Ip4Address.valueOf(), and org.onlab.packet.IpAddress.valueOf().
final int org.onlab.packet.IpAddress.INET_BIT_LENGTH = INET_BYTE_LENGTH * Byte.SIZE static
Definition at line 40 of file IpAddress.java.
Referenced by org.onlab.packet.IpAddressTest.testAddrBitLength().
final int org.onlab.packet.IpAddress.INET_BYTE_LENGTH = 4 static
Definition at line 39 of file IpAddress.java.
Referenced by org.onlab.packet.IpAddress.byteLength(), org.onlab.packet.IpAddress.IpAddress(), org.onosproject.store.serializers.IpAddressSerializer.read(), org.onosproject.store.serializers.IpPrefixSerializer.read(), org.onlab.packet.IpAddressTest.testAddrByteLength(), org.onlab.packet.Ip4Address.valueOf(), org.onlab.packet.Ip6Address.valueOf(), and org.onlab.packet.IpAddress.valueOf().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/IpAddress.java