onos: org.onosproject.net.meter.DefaultMeter Class Reference
org.onosproject.net.meter.DefaultMeter Class Reference
A default implementation of a meter.
Classes
class Builder
Public Member Functions
DeviceId deviceId ()
The target device for this meter.
MeterId id ()
This meters id.
ApplicationId appId ()
The id of the application which created this meter.
Unit unit ()
The unit used within this meter.
boolean isBurst ()
Signals whether this meter applies to bursts only.
Collection< Band > bands ()
The collection of bands to apply on the dataplane.
MeterState state ()
Fetches the state of this meter.
long life ()
The lifetime in seconds of this meter.
long referenceCount ()
The number of flows pointing to this meter.
long packetsSeen ()
Number of packets processed by this meter.
long bytesSeen ()
Number of bytes processed by this meter.
void setState (MeterState state)
Updates the state of this meter.
void setLife (long life)
Set the amount of time the meter has existed in seconds.
void setReferenceCount (long count)
Sets the number of flows which are using this meter.
void setProcessedPackets (long packets)
Updates the number of packets seen by this meter.
void setProcessedBytes (long bytes)
Updates the number of bytes seen by the meter.
String toString ()
boolean equals (Object o)
int hashCode ()
Static Public Member Functions
static Builder builder ()
Detailed Description
A default implementation of a meter.
Definition at line 32 of file DefaultMeter.java.
Member Function Documentation
ApplicationId org.onosproject.net.meter.DefaultMeter.appId ()
The id of the application which created this meter.
Returns
an application id
Implements org.onosproject.net.meter.Meter.
Definition at line 70 of file DefaultMeter.java.
Referenced by org.onosproject.net.meter.DefaultMeter.hashCode().
Collection<Band> org.onosproject.net.meter.DefaultMeter.bands ()
The collection of bands to apply on the dataplane.
Returns
a collection of bands.
Implements org.onosproject.net.meter.Meter.
Definition at line 85 of file DefaultMeter.java.
static Builder org.onosproject.net.meter.DefaultMeter.builder () static
Definition at line 114 of file DefaultMeter.java.
long org.onosproject.net.meter.DefaultMeter.bytesSeen ()
Number of bytes processed by this meter.
Returns
a byte count
Implements org.onosproject.net.meter.Meter.
Definition at line 110 of file DefaultMeter.java.
Referenced by org.onosproject.net.meter.DefaultMeterTest.testConstruction().
DeviceId org.onosproject.net.meter.DefaultMeter.deviceId ()
The target device for this meter.
Returns
a device id
Implements org.onosproject.net.meter.Meter.
Definition at line 60 of file DefaultMeter.java.
Referenced by org.onosproject.net.meter.DefaultMeter.hashCode(), and org.onosproject.net.meter.DefaultMeter.toString().
boolean org.onosproject.net.meter.DefaultMeter.equals (Object o)
Definition at line 156 of file DefaultMeter.java.
References find-device.id, org.onosproject.net.meter.DefaultMeter.id(), and org.onosproject.net.meter.DefaultMeter.unit().
int org.onosproject.net.meter.DefaultMeter.hashCode ()
Definition at line 171 of file DefaultMeter.java.
References org.onosproject.net.meter.DefaultMeter.appId(), org.onosproject.net.meter.DefaultMeter.deviceId(), org.onosproject.net.meter.DefaultMeter.id(), and org.onosproject.net.meter.DefaultMeter.unit().
MeterId org.onosproject.net.meter.DefaultMeter.id ()
This meters id.
Returns
a meter id
Implements org.onosproject.net.meter.Meter.
Definition at line 65 of file DefaultMeter.java.
Referenced by org.onosproject.net.meter.DefaultMeter.equals(), and org.onosproject.net.meter.DefaultMeter.hashCode().
boolean org.onosproject.net.meter.DefaultMeter.isBurst ()
Signals whether this meter applies to bursts only.
Returns
a boolean
Implements org.onosproject.net.meter.Meter.
Definition at line 80 of file DefaultMeter.java.
Referenced by org.onosproject.net.meter.DefaultMeterTest.testConstruction().
long org.onosproject.net.meter.DefaultMeter.life ()
The lifetime in seconds of this meter.
Returns
number of seconds
Implements org.onosproject.net.meter.Meter.
Definition at line 95 of file DefaultMeter.java.
Referenced by org.onosproject.net.meter.DefaultMeter.setLife().
long org.onosproject.net.meter.DefaultMeter.packetsSeen ()
Number of packets processed by this meter.
Returns
a packet count
Implements org.onosproject.net.meter.Meter.
Definition at line 105 of file DefaultMeter.java.
Referenced by org.onosproject.net.meter.DefaultMeterTest.testConstruction().
long org.onosproject.net.meter.DefaultMeter.referenceCount ()
The number of flows pointing to this meter.
Returns
a reference count
Implements org.onosproject.net.meter.Meter.
Definition at line 100 of file DefaultMeter.java.
Referenced by org.onosproject.net.meter.DefaultMeterTest.testConstruction().
void org.onosproject.net.meter.DefaultMeter.setLife (long life)
Set the amount of time the meter has existed in seconds.
Parameters
life number of seconds
Implements org.onosproject.net.meter.MeterEntry.
Definition at line 124 of file DefaultMeter.java.
References org.onosproject.net.meter.DefaultMeter.life().
void org.onosproject.net.meter.DefaultMeter.setProcessedBytes (long bytes)
Updates the number of bytes seen by the meter.
Parameters
bytes a byte counter.
Implements org.onosproject.net.meter.MeterEntry.
Definition at line 139 of file DefaultMeter.java.
void org.onosproject.net.meter.DefaultMeter.setProcessedPackets (long packets)
Updates the number of packets seen by this meter.
Parameters
packets a packet count.
Implements org.onosproject.net.meter.MeterEntry.
Definition at line 134 of file DefaultMeter.java.
void org.onosproject.net.meter.DefaultMeter.setReferenceCount (long count)
Sets the number of flows which are using this meter.
Parameters
count a reference count.
Implements org.onosproject.net.meter.MeterEntry.
Definition at line 129 of file DefaultMeter.java.
void org.onosproject.net.meter.DefaultMeter.setState (MeterState state)
Updates the state of this meter.
Parameters
state a meter state
Implements org.onosproject.net.meter.MeterEntry.
Definition at line 119 of file DefaultMeter.java.
References org.onosproject.net.meter.DefaultMeter.state().
MeterState org.onosproject.net.meter.DefaultMeter.state ()
Fetches the state of this meter.
Returns
a meter state
Implements org.onosproject.net.meter.Meter.
Definition at line 90 of file DefaultMeter.java.
Referenced by org.onosproject.net.meter.DefaultMeter.setState(), and org.onosproject.net.meter.DefaultMeter.toString().
String org.onosproject.net.meter.DefaultMeter.toString ()
Definition at line 144 of file DefaultMeter.java.
References org.onosproject.net.meter.DefaultMeter.deviceId(), org.onosproject.net.meter.DefaultMeter.state(), and org.onosproject.net.meter.DefaultMeter.unit().
Unit org.onosproject.net.meter.DefaultMeter.unit ()
The unit used within this meter.
Returns
the unit
Implements org.onosproject.net.meter.Meter.
Definition at line 75 of file DefaultMeter.java.
Referenced by org.onosproject.net.meter.DefaultMeter.equals(), org.onosproject.net.meter.DefaultMeter.hashCode(), and org.onosproject.net.meter.DefaultMeter.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/meter/DefaultMeter.java