onos: org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest Class Reference
org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest Class Reference
Test for ovsdb tunnel provider.
Public Member Functions
void setUp ()
void basics ()
void testTunnelAdded ()
void testTunnelRemoved ()
void tearDown ()
Detailed Description
Test for ovsdb tunnel provider.
Definition at line 53 of file OvsdbTunnelProviderTest.java.
Member Function Documentation
void org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.basics ()
Definition at line 65 of file OvsdbTunnelProviderTest.java.
void org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.setUp ()
Definition at line 59 of file OvsdbTunnelProviderTest.java.
void org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.tearDown ()
Definition at line 129 of file OvsdbTunnelProviderTest.java.
void org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.testTunnelAdded ()
Definition at line 71 of file OvsdbTunnelProviderTest.java.
References org.onosproject.net.ConnectPoint.deviceConnectPoint(), org.onosproject.net.provider.AbstractProvider.id(), org.onosproject.incubator.net.tunnel.TunnelName.tunnelName(), and org.onosproject.incubator.net.tunnel.TunnelId.valueOf().
void org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.testTunnelRemoved ()
Definition at line 100 of file OvsdbTunnelProviderTest.java.
References org.onosproject.net.ConnectPoint.deviceConnectPoint(), org.onosproject.net.provider.AbstractProvider.id(), org.onosproject.incubator.net.tunnel.TunnelName.tunnelName(), and org.onosproject.incubator.net.tunnel.TunnelId.valueOf().
The documentation for this class was generated from the following file:
providers/ovsdb/tunnel/src/test/java/org/onosproject/ovsdb/provider/tunnel/OvsdbTunnelProviderTest.java