onos: org.onosproject.ui.impl.UiExtensionManager Class Reference
org.onosproject.ui.impl.UiExtensionManager Class Reference
Manages the user interface extensions.
Public Member Functions
void activate ()
void deactivate ()
synchronized void register (UiExtension extension)
Registers the specified user interface extension.
synchronized void unregister (UiExtension extension)
Unregisters the specified user interface extension.
synchronized List< UiExtension > getExtensions ()
Returns the list of user interface extensions.
synchronized UiExtension getViewExtension (String viewId)
Returns the user interface extension that contributed the specified view.
Set< String > getNames ()
Returns set of registered sprite definition names.
void put (String name, JsonNode spriteData)
Registers sprite data under the specified name.
JsonNode get (String name)
Returns the sprite definition registered under the given name.
Protected Attributes
MastershipService mastershipService
Detailed Description
Manages the user interface extensions.
Definition at line 53 of file UiExtensionManager.java.
Member Function Documentation
void org.onosproject.ui.impl.UiExtensionManager.activate ()
Definition at line 123 of file UiExtensionManager.java.
void org.onosproject.ui.impl.UiExtensionManager.deactivate ()
Definition at line 129 of file UiExtensionManager.java.
References org.onosproject.ui.impl.UiExtensionManager.unregister().
JsonNode org.onosproject.ui.impl.UiExtensionManager.get (String name)
Returns the sprite definition registered under the given name.
Parameters
name sprite definition name
Returns
sprite data
Implements org.onosproject.ui.impl.SpriteService.
Definition at line 179 of file UiExtensionManager.java.
References create-flow.name.
synchronized List<UiExtension> org.onosproject.ui.impl.UiExtensionManager.getExtensions ()
Returns the list of user interface extensions.
Returns
list of extensions
Implements org.onosproject.ui.UiExtensionService.
Definition at line 153 of file UiExtensionManager.java.
Set<String> org.onosproject.ui.impl.UiExtensionManager.getNames ()
Returns set of registered sprite definition names.
Returns
set of sprite definition names
Implements org.onosproject.ui.impl.SpriteService.
Definition at line 168 of file UiExtensionManager.java.
synchronized UiExtension org.onosproject.ui.impl.UiExtensionManager.getViewExtension (String viewId)
Returns the user interface extension that contributed the specified view.
Parameters
viewId view identifier
Returns
user interface extension
Implements org.onosproject.ui.UiExtensionService.
Definition at line 158 of file UiExtensionManager.java.
void org.onosproject.ui.impl.UiExtensionManager.put (String name, JsonNode spriteData)
Registers sprite data under the specified name.
Parameters
name sprite definition name
spriteData sprite data
Implements org.onosproject.ui.impl.SpriteService.
Definition at line 173 of file UiExtensionManager.java.
References create-flow.name.
synchronized void org.onosproject.ui.impl.UiExtensionManager.register (UiExtension extension)
Registers the specified user interface extension.
Parameters
extension GUI extension to register
Implements org.onosproject.ui.UiExtensionService.
Definition at line 136 of file UiExtensionManager.java.
synchronized void org.onosproject.ui.impl.UiExtensionManager.unregister (UiExtension extension)
Unregisters the specified user interface extension.
Parameters
extension GUI extension to unregister
Implements org.onosproject.ui.UiExtensionService.
Definition at line 146 of file UiExtensionManager.java.
References org.onosproject.ui.UiView.id().
Referenced by org.onosproject.ui.impl.UiExtensionManager.deactivate().
Member Data Documentation
MastershipService org.onosproject.ui.impl.UiExtensionManager.mastershipService protected
Definition at line 72 of file UiExtensionManager.java.
The documentation for this class was generated from the following file:
web/gui/src/main/java/org/onosproject/ui/impl/UiExtensionManager.java