onos: org.onosproject.store.trivial.SimpleMastershipStore Class Reference
org.onosproject.store.trivial.SimpleMastershipStore Class Reference
Manages inventory of controller mastership over devices using trivial, non-distributed in-memory structures implementation.
Public Member Functions
void activate ()
void deactivate ()
synchronized CompletableFuture
< MastershipEvent > setMaster (NodeId nodeId, DeviceId deviceId)
Sets a device's role for a specified controller instance.
NodeId getMaster (DeviceId deviceId)
Returns the master for a device.
synchronized RoleInfo getNodes (DeviceId deviceId)
Returns the master and backup nodes for a device.
Set< DeviceId > getDevices (NodeId nodeId)
Returns the devices that a controller instance is master of.
synchronized CompletableFuture
< MastershipRole > requestRole (DeviceId deviceId)
Requests role of the local node for the specified device.
MastershipRole getRole (NodeId nodeId, DeviceId deviceId)
Returns the role of a device for a specific controller instance.
synchronized MastershipTerm getTermFor (DeviceId deviceId)
Returns the current master and number of past mastership hand-offs (terms) for a device.
synchronized CompletableFuture
< MastershipEvent > setStandby (NodeId nodeId, DeviceId deviceId)
Sets a controller instance's mastership role to STANDBY for a device.
synchronized CompletableFuture
< MastershipEvent > relinquishRole (NodeId nodeId, DeviceId deviceId)
Allows a controller instance to give up its current role for a device.
synchronized void relinquishAllRole (NodeId nodeId)
Removes all the roles for the specified controller instance.
Protected Attributes
ClusterService clusterService
final Map< DeviceId, NodeId > masterMap = new HashMap<>()
final Map< DeviceId, List
< NodeId > > backups = new HashMap<>()
final Map< DeviceId,
AtomicInteger > termMap = new HashMap<>()
Detailed Description
Manages inventory of controller mastership over devices using trivial, non-distributed in-memory structures implementation.
Definition at line 66 of file SimpleMastershipStore.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleMastershipStore.activate ()
Definition at line 86 of file SimpleMastershipStore.java.
References org.onosproject.cluster.ControllerNode.State.ACTIVE, org.onosproject.store.trivial.SimpleMastershipStore.getNodes(), org.onosproject.cluster.ControllerNode.id(), org.onosproject.cluster.ControllerNode.State.INACTIVE, and org.onlab.packet.IpAddress.valueOf().
void org.onosproject.store.trivial.SimpleMastershipStore.deactivate ()
Definition at line 142 of file SimpleMastershipStore.java.
Set<DeviceId> org.onosproject.store.trivial.SimpleMastershipStore.getDevices (NodeId nodeId)
Returns the devices that a controller instance is master of.
Parameters
nodeId the instance identifier
Returns
a set of device identifiers
Implements org.onosproject.mastership.MastershipStore.
Definition at line 183 of file SimpleMastershipStore.java.
References org.onosproject.store.trivial.SimpleMastershipStore.masterMap.
Referenced by org.onosproject.store.trivial.SimpleMastershipStoreTest.getDevices().
NodeId org.onosproject.store.trivial.SimpleMastershipStore.getMaster (DeviceId deviceId)
Returns the master for a device.
Parameters
deviceId the device identifier
Returns
the instance identifier of the master
Implements org.onosproject.mastership.MastershipStore.
Definition at line 171 of file SimpleMastershipStore.java.
References find-flow.deviceId.
Referenced by org.onosproject.store.trivial.SimpleMastershipStoreTest.getMaster(), and org.onosproject.store.trivial.SimpleMastershipStore.requestRole().
synchronized RoleInfo org.onosproject.store.trivial.SimpleMastershipStore.getNodes (DeviceId deviceId)
Returns the master and backup nodes for a device.
Parameters
deviceId the device identifier
Returns
a RoleInfo containing controller IDs
Implements org.onosproject.mastership.MastershipStore.
Definition at line 177 of file SimpleMastershipStore.java.
References find-flow.deviceId, and org.onosproject.store.trivial.SimpleMastershipStore.masterMap.
Referenced by org.onosproject.store.trivial.SimpleMastershipStore.activate(), org.onosproject.store.trivial.SimpleMastershipStore.relinquishRole(), org.onosproject.store.trivial.SimpleMastershipStore.requestRole(), org.onosproject.store.trivial.SimpleMastershipStore.setMaster(), and org.onosproject.store.trivial.SimpleMastershipStore.setStandby().
MastershipRole org.onosproject.store.trivial.SimpleMastershipStore.getRole (NodeId nodeId, DeviceId deviceId)
Returns the role of a device for a specific controller instance.
Parameters
nodeId the instance identifier
deviceId the device identifiers
Returns
the role
Implements org.onosproject.mastership.MastershipStore.
Definition at line 261 of file SimpleMastershipStore.java.
References org.onosproject.store.trivial.SimpleMastershipStore.backups, find-flow.deviceId, org.onosproject.cluster.NodeId.equals(), org.onosproject.net.MastershipRole.MASTER, org.onosproject.net.MastershipRole.NONE, and org.onosproject.net.MastershipRole.STANDBY.
Referenced by org.onosproject.store.trivial.SimpleMastershipStoreTest.getMaster(), org.onosproject.store.trivial.SimpleMastershipStoreTest.getRole(), org.onosproject.store.trivial.SimpleMastershipStore.relinquishRole(), org.onosproject.store.trivial.SimpleMastershipStore.requestRole(), org.onosproject.store.trivial.SimpleMastershipStoreTest.setMaster(), org.onosproject.store.trivial.SimpleMastershipStore.setMaster(), and org.onosproject.store.trivial.SimpleMastershipStore.setStandby().
synchronized MastershipTerm org.onosproject.store.trivial.SimpleMastershipStore.getTermFor (DeviceId deviceId)
Returns the current master and number of past mastership hand-offs (terms) for a device.
Parameters
deviceId the device identifier
Returns
the current master's ID and the term value for device, or null
Implements org.onosproject.mastership.MastershipStore.
Definition at line 280 of file SimpleMastershipStore.java.
References find-flow.deviceId, and org.onosproject.store.trivial.SimpleMastershipStore.termMap.
synchronized void org.onosproject.store.trivial.SimpleMastershipStore.relinquishAllRole (NodeId nodeId)
Removes all the roles for the specified controller instance.
If the role was MASTER, another controller instance will be selected as a candidate master.
Parameters
nodeId the controller instance identifier
Implements org.onosproject.mastership.MastershipStore.
Definition at line 366 of file SimpleMastershipStore.java.
References find-flow.deviceId, and org.onosproject.store.trivial.SimpleMastershipStore.relinquishRole().
synchronized CompletableFuture<MastershipEvent> org.onosproject.store.trivial.SimpleMastershipStore.relinquishRole (NodeId nodeId, DeviceId deviceId)
Allows a controller instance to give up its current role for a device.
If the role is MASTER, another controller instance will be selected as a candidate master.
Parameters
nodeId the controller instance identifier
deviceId device to revoke mastership role for
Returns
a mastership event
Implements org.onosproject.mastership.MastershipStore.
Definition at line 339 of file SimpleMastershipStore.java.
References find-flow.deviceId, org.onosproject.store.trivial.SimpleMastershipStore.getNodes(), and org.onosproject.store.trivial.SimpleMastershipStore.getRole().
Referenced by org.onosproject.store.trivial.SimpleMastershipStore.relinquishAllRole().
synchronized CompletableFuture<MastershipRole> org.onosproject.store.trivial.SimpleMastershipStore.requestRole (DeviceId deviceId)
Requests role of the local node for the specified device.
Parameters
deviceId device identifier
Returns
established or newly negotiated mastership role
Implements org.onosproject.mastership.MastershipStore.
Definition at line 194 of file SimpleMastershipStore.java.
References find-flow.deviceId, org.onosproject.store.trivial.SimpleMastershipStore.getMaster(), org.onosproject.store.trivial.SimpleMastershipStore.getNodes(), org.onosproject.store.trivial.SimpleMastershipStore.getRole(), org.onosproject.net.MastershipRole.MASTER, create-flow.node, and org.onosproject.net.MastershipRole.STANDBY.
Referenced by org.onosproject.store.trivial.SimpleMastershipStoreTest.requestRole().
synchronized CompletableFuture<MastershipEvent> org.onosproject.store.trivial.SimpleMastershipStore.setMaster (NodeId nodeId, DeviceId deviceId)
Sets a device's role for a specified controller instance.
Parameters
nodeId controller instance identifier
deviceId device identifier
Returns
a mastership event
Implements org.onosproject.mastership.MastershipStore.
Definition at line 147 of file SimpleMastershipStore.java.
References find-flow.deviceId, org.onosproject.store.trivial.SimpleMastershipStore.getNodes(), and org.onosproject.store.trivial.SimpleMastershipStore.getRole().
Referenced by org.onosproject.store.trivial.SimpleMastershipStoreTest.setMaster().
synchronized CompletableFuture<MastershipEvent> org.onosproject.store.trivial.SimpleMastershipStore.setStandby (NodeId nodeId, DeviceId deviceId)
Sets a controller instance's mastership role to STANDBY for a device.
If the role is MASTER, another controller instance will be selected as a candidate master.
Parameters
nodeId the controller instance identifier
deviceId device to revoke mastership role for
Returns
a mastership event
Implements org.onosproject.mastership.MastershipStore.
Definition at line 289 of file SimpleMastershipStore.java.
References find-flow.deviceId, org.onosproject.store.trivial.SimpleMastershipStore.getNodes(), and org.onosproject.store.trivial.SimpleMastershipStore.getRole().
Referenced by org.onosproject.store.trivial.SimpleMastershipStoreTest.unsetMaster().
Member Data Documentation
final Map<DeviceId, List<NodeId> > org.onosproject.store.trivial.SimpleMastershipStore.backups = new HashMap<>() protected
Definition at line 81 of file SimpleMastershipStore.java.
Referenced by org.onosproject.store.trivial.SimpleMastershipStore.getRole(), and org.onosproject.store.trivial.SimpleMastershipStoreTest.unsetMaster().
ClusterService org.onosproject.store.trivial.SimpleMastershipStore.clusterService protected
Definition at line 76 of file SimpleMastershipStore.java.
final Map<DeviceId, NodeId> org.onosproject.store.trivial.SimpleMastershipStore.masterMap = new HashMap<>() protected
Definition at line 79 of file SimpleMastershipStore.java.
Referenced by org.onosproject.store.trivial.SimpleMastershipStore.getDevices(), org.onosproject.store.trivial.SimpleMastershipStore.getNodes(), and org.onosproject.store.trivial.SimpleMastershipStoreTest.unsetMaster().
final Map<DeviceId, AtomicInteger> org.onosproject.store.trivial.SimpleMastershipStore.termMap = new HashMap<>() protected
Definition at line 83 of file SimpleMastershipStore.java.
Referenced by org.onosproject.store.trivial.SimpleMastershipStore.getTermFor(), and org.onosproject.store.trivial.SimpleMastershipStoreTest.unsetMaster().
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleMastershipStore.java