onos: org.onosproject.provider.lldp.impl.SuppressionConfig Class Reference
org.onosproject.provider.lldp.impl.SuppressionConfig Class Reference
LinkDiscovery suppression config class.
Public Member Functions
Set< Device.Type > deviceTypes ()
Returns types of devices on which LinkDiscovery is suppressed.
SuppressionConfig deviceTypes (Set< Device.Type > deviceTypes)
Sets types of devices on which LinkDiscovery is suppressed.
Map< String, String > annotation ()
Returns annotation of Ports on which LinkDiscovery is suppressed.
SuppressionConfig annotation (Map< String, String > annotation)
Sets annotation of Ports on which LinkDiscovery is suppressed.
Detailed Description
LinkDiscovery suppression config class.
Definition at line 43 of file SuppressionConfig.java.
Member Function Documentation
Map<String, String> org.onosproject.provider.lldp.impl.SuppressionConfig.annotation ()
Returns annotation of Ports on which LinkDiscovery is suppressed.
Returns
key-value pairs of annotation
Definition at line 79 of file SuppressionConfig.java.
References org.onosproject.provider.lldp.impl.SuppressionRules.ANY_VALUE.
Referenced by org.onosproject.provider.lldp.impl.SuppressionConfig.annotation(), and org.onosproject.provider.lldp.impl.SuppressionConfigTest.testDeviceAnnotation().
SuppressionConfig org.onosproject.provider.lldp.impl.SuppressionConfig.annotation (Map< String, String > annotation)
Sets annotation of Ports on which LinkDiscovery is suppressed.
Parameters
annotation new key-value pair of annotation; null to clear
Returns
self
Definition at line 127 of file SuppressionConfig.java.
References org.onosproject.provider.lldp.impl.SuppressionConfig.annotation(), and org.onosproject.provider.lldp.impl.SuppressionRules.ANY_VALUE.
Set<Device.Type> org.onosproject.provider.lldp.impl.SuppressionConfig.deviceTypes ()
Returns types of devices on which LinkDiscovery is suppressed.
Returns
set of device types
Definition at line 60 of file SuppressionConfig.java.
Referenced by org.onosproject.provider.lldp.impl.SuppressionConfigTest.testDeviceTypes().
SuppressionConfig org.onosproject.provider.lldp.impl.SuppressionConfig.deviceTypes (Set< Device.Type > deviceTypes)
Sets types of devices on which LinkDiscovery is suppressed.
Parameters
deviceTypes new set of device types; null to clear
Returns
self
Definition at line 70 of file SuppressionConfig.java.
The documentation for this class was generated from the following file:
providers/lldp/src/main/java/org/onosproject/provider/lldp/impl/SuppressionConfig.java