onos: org.onosproject.bgpio.types.OSPFRouteTypeTlv Class Reference
org.onosproject.bgpio.types.OSPFRouteTypeTlv Class Reference
Provides OSPF Route Type Tlv which contains route type.
Classes
enum RouteType
Enum for Route Type.
Public Member Functions
OSPFRouteTypeTlv (byte routeType)
Constructor to initialize routeType.
RouteType getValue () throws BgpParseException
Returns RouteType.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of BGP Message to channel buffer.
short getType ()
Returns the Type of BGP Message.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static OSPFRouteTypeTlv of (final byte routeType)
Returns object of this class with specified routeType.
static OSPFRouteTypeTlv read (ChannelBuffer cb)
Reads from ChannelBuffer and parses OSPFRouteTypeTlv.
Static Public Attributes
static final short TYPE = 264
static final short LENGTH = 1
static final int INTRA_AREA_TYPE = 1
static final short INTER_AREA_TYPE = 2
static final short EXTERNAL_TYPE_1 = 3
static final short EXTERNAL_TYPE_2 = 4
static final short NSSA_TYPE_1 = 5
static final short NSSA_TYPE_2 = 6
Detailed Description
Provides OSPF Route Type Tlv which contains route type.
Definition at line 28 of file OSPFRouteTypeTlv.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.OSPFRouteTypeTlv.OSPFRouteTypeTlv (byte routeType)
Constructor to initialize routeType.
Parameters
routeType Route type
Definition at line 72 of file OSPFRouteTypeTlv.java.
Referenced by org.onosproject.bgpio.types.OSPFRouteTypeTlv.equals(), and org.onosproject.bgpio.types.OSPFRouteTypeTlv.of().
Member Function Documentation
int org.onosproject.bgpio.types.OSPFRouteTypeTlv.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 153 of file OSPFRouteTypeTlv.java.
References org.onosproject.bgpio.types.OSPFRouteTypeTlv.equals().
boolean org.onosproject.bgpio.types.OSPFRouteTypeTlv.equals (Object obj)
Definition at line 117 of file OSPFRouteTypeTlv.java.
References org.onosproject.bgpio.types.OSPFRouteTypeTlv.OSPFRouteTypeTlv().
Referenced by org.onosproject.bgpio.types.OSPFRouteTypeTlv.compareTo().
short org.onosproject.bgpio.types.OSPFRouteTypeTlv.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 148 of file OSPFRouteTypeTlv.java.
References org.onosproject.bgpio.types.OSPFRouteTypeTlv.TYPE.
RouteType org.onosproject.bgpio.types.OSPFRouteTypeTlv.getValue () throws BgpParseException
Returns RouteType.
Returns
RouteType
Exceptions
BgpParseException if routeType is not matched
Definition at line 92 of file OSPFRouteTypeTlv.java.
References org.onosproject.bgpio.types.OSPFRouteTypeTlv.RouteType.External_1, org.onosproject.bgpio.types.OSPFRouteTypeTlv.RouteType.External_2, org.onosproject.bgpio.types.OSPFRouteTypeTlv.EXTERNAL_TYPE_1, org.onosproject.bgpio.types.OSPFRouteTypeTlv.EXTERNAL_TYPE_2, org.onosproject.bgpio.types.OSPFRouteTypeTlv.RouteType.Inter_Area, org.onosproject.bgpio.types.OSPFRouteTypeTlv.INTER_AREA_TYPE, org.onosproject.bgpio.types.OSPFRouteTypeTlv.RouteType.Intra_Area, org.onosproject.bgpio.types.OSPFRouteTypeTlv.INTRA_AREA_TYPE, org.onosproject.bgpio.types.OSPFRouteTypeTlv.RouteType.NSSA_1, org.onosproject.bgpio.types.OSPFRouteTypeTlv.RouteType.NSSA_2, org.onosproject.bgpio.types.OSPFRouteTypeTlv.NSSA_TYPE_1, org.onosproject.bgpio.types.OSPFRouteTypeTlv.NSSA_TYPE_2, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
int org.onosproject.bgpio.types.OSPFRouteTypeTlv.hashCode ()
Definition at line 112 of file OSPFRouteTypeTlv.java.
static OSPFRouteTypeTlv org.onosproject.bgpio.types.OSPFRouteTypeTlv.of (final byte routeType) static
Returns object of this class with specified routeType.
Parameters
routeType Route type
Returns
object of OSPFRouteTypeTlv
Definition at line 82 of file OSPFRouteTypeTlv.java.
References org.onosproject.bgpio.types.OSPFRouteTypeTlv.OSPFRouteTypeTlv().
static OSPFRouteTypeTlv org.onosproject.bgpio.types.OSPFRouteTypeTlv.read (ChannelBuffer cb) static
Reads from ChannelBuffer and parses OSPFRouteTypeTlv.
Parameters
cb channelBuffer
Returns
object of OSPFRouteTypeTlv
Definition at line 143 of file OSPFRouteTypeTlv.java.
String org.onosproject.bgpio.types.OSPFRouteTypeTlv.toString ()
Definition at line 161 of file OSPFRouteTypeTlv.java.
References org.onosproject.bgpio.types.OSPFRouteTypeTlv.LENGTH, and org.onosproject.bgpio.types.OSPFRouteTypeTlv.TYPE.
int org.onosproject.bgpio.types.OSPFRouteTypeTlv.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 129 of file OSPFRouteTypeTlv.java.
References org.onosproject.bgpio.types.OSPFRouteTypeTlv.LENGTH, and org.onosproject.bgpio.types.OSPFRouteTypeTlv.TYPE.
Member Data Documentation
final short org.onosproject.bgpio.types.OSPFRouteTypeTlv.EXTERNAL_TYPE_1 = 3 static
Definition at line 46 of file OSPFRouteTypeTlv.java.
Referenced by org.onosproject.bgpio.types.OSPFRouteTypeTlv.getValue().
final short org.onosproject.bgpio.types.OSPFRouteTypeTlv.EXTERNAL_TYPE_2 = 4 static
Definition at line 47 of file OSPFRouteTypeTlv.java.
Referenced by org.onosproject.bgpio.types.OSPFRouteTypeTlv.getValue().
final short org.onosproject.bgpio.types.OSPFRouteTypeTlv.INTER_AREA_TYPE = 2 static
Definition at line 45 of file OSPFRouteTypeTlv.java.
Referenced by org.onosproject.bgpio.types.OSPFRouteTypeTlv.getValue().
final int org.onosproject.bgpio.types.OSPFRouteTypeTlv.INTRA_AREA_TYPE = 1 static
Definition at line 44 of file OSPFRouteTypeTlv.java.
Referenced by org.onosproject.bgpio.types.OSPFRouteTypeTlv.getValue().
final short org.onosproject.bgpio.types.OSPFRouteTypeTlv.LENGTH = 1 static
Definition at line 43 of file OSPFRouteTypeTlv.java.
Referenced by org.onosproject.bgpio.types.OSPFRouteTypeTlv.toString(), and org.onosproject.bgpio.types.OSPFRouteTypeTlv.write().
final short org.onosproject.bgpio.types.OSPFRouteTypeTlv.NSSA_TYPE_1 = 5 static
Definition at line 48 of file OSPFRouteTypeTlv.java.
Referenced by org.onosproject.bgpio.types.OSPFRouteTypeTlv.getValue().
final short org.onosproject.bgpio.types.OSPFRouteTypeTlv.NSSA_TYPE_2 = 6 static
Definition at line 49 of file OSPFRouteTypeTlv.java.
Referenced by org.onosproject.bgpio.types.OSPFRouteTypeTlv.getValue().
final short org.onosproject.bgpio.types.OSPFRouteTypeTlv.TYPE = 264 static
Definition at line 42 of file OSPFRouteTypeTlv.java.
Referenced by org.onosproject.bgpio.types.OSPFRouteTypeTlv.getType(), org.onosproject.bgpio.types.OSPFRouteTypeTlv.toString(), and org.onosproject.bgpio.types.OSPFRouteTypeTlv.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/OSPFRouteTypeTlv.java