onos: org.onosproject.pcepio.types.UnreservedBandwidthTlv Class Reference
org.onosproject.pcepio.types.UnreservedBandwidthTlv Class Reference
Provides Unreserved Bandwidth Tlv.
Public Member Functions
UnreservedBandwidthTlv (int rawValue)
Constructor to initialize rawValue.
int getInt ()
Returns Unreserved Bandwidth.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static UnreservedBandwidthTlv of (final int raw)
Returns newly created UnreservedBandwidthTlv object.
static UnreservedBandwidthTlv read (ChannelBuffer c)
Reads byte stream from channel buffer and returns object of UnreservedBandwidthTlv.
Static Public Attributes
static final short TYPE = 11
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(UnreservedBandwidthTlv.class)
Detailed Description
Provides Unreserved Bandwidth Tlv.
Definition at line 30 of file UnreservedBandwidthTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.UnreservedBandwidthTlv.UnreservedBandwidthTlv (int rawValue)
Constructor to initialize rawValue.
Parameters
rawValue Unreserved Bandwidth
Definition at line 54 of file UnreservedBandwidthTlv.java.
Referenced by org.onosproject.pcepio.types.UnreservedBandwidthTlv.equals(), and org.onosproject.pcepio.types.UnreservedBandwidthTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.UnreservedBandwidthTlv.equals (Object obj)
Definition at line 98 of file UnreservedBandwidthTlv.java.
References org.onosproject.pcepio.types.UnreservedBandwidthTlv.UnreservedBandwidthTlv().
int org.onosproject.pcepio.types.UnreservedBandwidthTlv.getInt ()
Returns Unreserved Bandwidth.
Returns
rawValue Unreserved Bandwidth
Definition at line 73 of file UnreservedBandwidthTlv.java.
short org.onosproject.pcepio.types.UnreservedBandwidthTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 88 of file UnreservedBandwidthTlv.java.
References org.onosproject.pcepio.types.UnreservedBandwidthTlv.LENGTH.
short org.onosproject.pcepio.types.UnreservedBandwidthTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 83 of file UnreservedBandwidthTlv.java.
References org.onosproject.pcepio.types.UnreservedBandwidthTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.UnreservedBandwidthTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 78 of file UnreservedBandwidthTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.UnreservedBandwidthTlv.hashCode ()
Definition at line 93 of file UnreservedBandwidthTlv.java.
static UnreservedBandwidthTlv org.onosproject.pcepio.types.UnreservedBandwidthTlv.of (final int raw) static
Returns newly created UnreservedBandwidthTlv object.
Parameters
raw as Unreserved Bandwidth
Returns
object of UnreservedBandwidthTlv
Definition at line 64 of file UnreservedBandwidthTlv.java.
References org.onosproject.pcepio.types.UnreservedBandwidthTlv.UnreservedBandwidthTlv().
static UnreservedBandwidthTlv org.onosproject.pcepio.types.UnreservedBandwidthTlv.read (ChannelBuffer c) static
Reads byte stream from channel buffer and returns object of UnreservedBandwidthTlv.
Parameters
c input channel buffer
Returns
object of UnreservedBandwidthTlv
Definition at line 124 of file UnreservedBandwidthTlv.java.
String org.onosproject.pcepio.types.UnreservedBandwidthTlv.toString ()
Definition at line 129 of file UnreservedBandwidthTlv.java.
References org.onosproject.pcepio.types.UnreservedBandwidthTlv.LENGTH, and org.onosproject.pcepio.types.UnreservedBandwidthTlv.TYPE.
int org.onosproject.pcepio.types.UnreservedBandwidthTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 110 of file UnreservedBandwidthTlv.java.
References org.onosproject.pcepio.types.UnreservedBandwidthTlv.LENGTH, and org.onosproject.pcepio.types.UnreservedBandwidthTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.UnreservedBandwidthTlv.LENGTH = 4 static
Definition at line 45 of file UnreservedBandwidthTlv.java.
Referenced by org.onosproject.pcepio.types.UnreservedBandwidthTlv.getLength(), org.onosproject.pcepio.types.UnreservedBandwidthTlv.toString(), and org.onosproject.pcepio.types.UnreservedBandwidthTlv.write().
final Logger org.onosproject.pcepio.types.UnreservedBandwidthTlv.log = LoggerFactory.getLogger(UnreservedBandwidthTlv.class) static protected
Definition at line 42 of file UnreservedBandwidthTlv.java.
final short org.onosproject.pcepio.types.UnreservedBandwidthTlv.TYPE = 11 static
Definition at line 44 of file UnreservedBandwidthTlv.java.
Referenced by org.onosproject.pcepio.types.UnreservedBandwidthTlv.getType(), org.onosproject.pcepio.types.UnreservedBandwidthTlv.toString(), and org.onosproject.pcepio.types.UnreservedBandwidthTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/UnreservedBandwidthTlv.java