onos: org.onlab.metrics.EventMetric Class Reference
org.onlab.metrics.EventMetric Class Reference
Metric measurements for events.
Public Member Functions
EventMetric (MetricsService metricsService, String componentName, String featureName)
Constructor.
void registerMetrics ()
Registers the metrics.
void removeMetrics ()
Removes the metrics.
void eventReceived ()
Updates the metric measurements for a single event.
Gauge< Long > lastEventTimestampGauge ()
Gets the last event timestamp Gauge (ms from the Epoch).
Meter eventRateMeter ()
Gets the event rate meter.
Detailed Description
Metric measurements for events.
Definition at line 24 of file EventMetric.java.
Constructor & Destructor Documentation
org.onlab.metrics.EventMetric.EventMetric (MetricsService metricsService, String componentName, String featureName)
Constructor.
Parameters
metricsService the Metrics Service to use for Metrics registration and deregistration
componentName the Metrics Component Name to use for Metrics registration and deregistration
featureName the Metrics Feature Name to use for Metrics registration and deregistration
Definition at line 49 of file EventMetric.java.
Member Function Documentation
Meter org.onlab.metrics.EventMetric.eventRateMeter ()
Gets the event rate meter.
Returns
the event rate meter
Definition at line 115 of file EventMetric.java.
Referenced by org.onlab.metrics.EventMetric.registerMetrics().
void org.onlab.metrics.EventMetric.eventReceived ()
Updates the metric measurements for a single event.
Definition at line 96 of file EventMetric.java.
Gauge<Long> org.onlab.metrics.EventMetric.lastEventTimestampGauge ()
Gets the last event timestamp Gauge (ms from the Epoch).
Returns
the last event timestamp Gauge (ms from the Epoch)
Definition at line 106 of file EventMetric.java.
Referenced by org.onlab.metrics.EventMetric.registerMetrics().
void org.onlab.metrics.EventMetric.registerMetrics ()
Registers the metrics.
Definition at line 59 of file EventMetric.java.
References org.onlab.metrics.EventMetric.eventRateMeter(), and org.onlab.metrics.EventMetric.lastEventTimestampGauge().
void org.onlab.metrics.EventMetric.removeMetrics ()
Removes the metrics.
Definition at line 83 of file EventMetric.java.
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/metrics/EventMetric.java