onos: org.onosproject.net.statistic.impl.StatisticManager Class Reference
org.onosproject.net.statistic.impl.StatisticManager Class Reference
Provides an implementation of the Statistic Service.
Public Member Functions
void activate ()
void deactivate ()
Load load (Link link)
Obtain the load for a the ingress to the given link.
Load load (Link link, ApplicationId appId, Optional< GroupId > groupId)
Obtain the load for a the ingress to the given link used by the specified application ID and group ID.
Load load (ConnectPoint connectPoint)
Obtain the load for the given port.
Link max (Path path)
Find the most loaded link along a path.
Link min (Path path)
Find the least loaded link along a path.
FlowRule highestHitter (ConnectPoint connectPoint)
Returns the highest hitter (a flow rule) for a given port, ie.
Protected Attributes
FlowRuleService flowRuleService
StatisticStore statisticStore
Detailed Description
Provides an implementation of the Statistic Service.
Definition at line 61 of file StatisticManager.java.
Member Function Documentation
void org.onosproject.net.statistic.impl.StatisticManager.activate ()
Definition at line 75 of file StatisticManager.java.
void org.onosproject.net.statistic.impl.StatisticManager.deactivate ()
Definition at line 82 of file StatisticManager.java.
FlowRule org.onosproject.net.statistic.impl.StatisticManager.highestHitter (ConnectPoint connectPoint)
Returns the highest hitter (a flow rule) for a given port, ie.
the flow rule which is generating the most load.
Parameters
connectPoint the port
Returns
the flow rule
Implements org.onosproject.net.statistic.StatisticService.
Definition at line 161 of file StatisticManager.java.
References org.onosproject.net.statistic.impl.StatisticManager.max().
Load org.onosproject.net.statistic.impl.StatisticManager.load (Link link)
Obtain the load for a the ingress to the given link.
Parameters
link the link to query.
Returns
a Load
Implements org.onosproject.net.statistic.StatisticService.
Definition at line 88 of file StatisticManager.java.
References org.onosproject.net.Link.src().
Referenced by org.onosproject.net.statistic.impl.StatisticManager.max(), and org.onosproject.net.statistic.impl.StatisticManager.min().
Load org.onosproject.net.statistic.impl.StatisticManager.load (Link link, ApplicationId appId, Optional< GroupId > groupId)
Obtain the load for a the ingress to the given link used by the specified application ID and group ID.
Parameters
link link to query
appId application ID to filter with
groupId group ID to filter with
Returns
Load
Implements org.onosproject.net.statistic.StatisticService.
Definition at line 95 of file StatisticManager.java.
References org.onosproject.net.Link.src().
Load org.onosproject.net.statistic.impl.StatisticManager.load (ConnectPoint connectPoint)
Obtain the load for the given port.
Parameters
connectPoint the port to query
Returns
a org.onosproject.net.statistic.Load
Implements org.onosproject.net.statistic.StatisticService.
Definition at line 116 of file StatisticManager.java.
Link org.onosproject.net.statistic.impl.StatisticManager.max (Path path)
Find the most loaded link along a path.
Parameters
path the path to search in
Returns
the most loaded org.onosproject.net.Link.
Implements org.onosproject.net.statistic.StatisticService.
Definition at line 123 of file StatisticManager.java.
References org.onosproject.net.Path.links(), org.onosproject.net.statistic.impl.StatisticManager.load(), and org.onosproject.net.statistic.Load.rate().
Referenced by org.onosproject.net.statistic.impl.StatisticManager.highestHitter().
Link org.onosproject.net.statistic.impl.StatisticManager.min (Path path)
Find the least loaded link along a path.
Parameters
path the path to search in
Returns
the least loaded org.onosproject.net.Link.
Implements org.onosproject.net.statistic.StatisticService.
Definition at line 142 of file StatisticManager.java.
References org.onosproject.net.Path.links(), org.onosproject.net.statistic.impl.StatisticManager.load(), and org.onosproject.net.statistic.Load.rate().
Member Data Documentation
FlowRuleService org.onosproject.net.statistic.impl.StatisticManager.flowRuleService protected
Definition at line 66 of file StatisticManager.java.
StatisticStore org.onosproject.net.statistic.impl.StatisticManager.statisticStore protected
Definition at line 69 of file StatisticManager.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/statistic/impl/StatisticManager.java