onos: org.onosproject.net.intent.constraint.BandwidthConstraint Class Reference
org.onosproject.net.intent.constraint.BandwidthConstraint Class Reference
Constraint that evaluates links based on available bandwidths.
Public Member Functions
BandwidthConstraint (Bandwidth bandwidth)
Creates a new bandwidth constraint.
boolean isValid (Link link, LinkResourceService resourceService)
Returns true if the specified link satisfies the constraint.
Bandwidth bandwidth ()
Returns the bandwidth required by this constraint.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.constraint.BooleanConstraint
double cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
boolean validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
Static Public Member Functions
static BandwidthConstraint of (double v, DataRateUnit unit)
Creates a new bandwidth constraint.
Detailed Description
Constraint that evaluates links based on available bandwidths.
Definition at line 37 of file BandwidthConstraint.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.constraint.BandwidthConstraint.BandwidthConstraint (Bandwidth bandwidth)
Creates a new bandwidth constraint.
Parameters
bandwidth required bandwidth
Definition at line 46 of file BandwidthConstraint.java.
Member Function Documentation
Bandwidth org.onosproject.net.intent.constraint.BandwidthConstraint.bandwidth ()
Returns the bandwidth required by this constraint.
Returns
required bandwidth
Definition at line 84 of file BandwidthConstraint.java.
Referenced by org.onosproject.net.intent.constraint.BandwidthConstraint.isValid(), and org.onosproject.net.intent.constraint.BandwidthConstraint.toString().
boolean org.onosproject.net.intent.constraint.BandwidthConstraint.equals (Object obj)
Definition at line 94 of file BandwidthConstraint.java.
int org.onosproject.net.intent.constraint.BandwidthConstraint.hashCode ()
Definition at line 89 of file BandwidthConstraint.java.
boolean org.onosproject.net.intent.constraint.BandwidthConstraint.isValid (Link link, LinkResourceService resourceService) virtual
Returns true if the specified link satisfies the constraint.
Parameters
link link to be validated
resourceService resource service for checking available link resources
Returns
true if link is viable
Implements org.onosproject.net.intent.constraint.BooleanConstraint.
Definition at line 67 of file BandwidthConstraint.java.
References org.onosproject.net.resource.ResourceType.BANDWIDTH, org.onosproject.net.intent.constraint.BandwidthConstraint.bandwidth(), and org.onosproject.net.resource.link.LinkResourceService.getAvailableResources().
static BandwidthConstraint org.onosproject.net.intent.constraint.BandwidthConstraint.of (double v, DataRateUnit unit) static
Creates a new bandwidth constraint.
Parameters
v required amount of bandwidth
unit DataRateUnit of
v
Returns
BandwidthConstraint instance with given bandwidth requirement
Definition at line 57 of file BandwidthConstraint.java.
References org.onlab.util.Bandwidth.of().
String org.onosproject.net.intent.constraint.BandwidthConstraint.toString ()
Definition at line 106 of file BandwidthConstraint.java.
References org.onosproject.net.intent.constraint.BandwidthConstraint.bandwidth().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/constraint/BandwidthConstraint.java