onos: org.onosproject.net.topology.impl.TopologyManagerTest Class Reference
org.onosproject.net.topology.impl.TopologyManagerTest Class Reference
Test of the topology subsystem.
Public Member Functions
void setUp ()
void tearDown ()
void basics ()
void clusters ()
void structure ()
void graph ()
void precomputedPath ()
void onDemandPath ()
Protected Member Functions
void validateEvents (Enum...types)
Protected Attributes
TopologyService service
TopologyProviderRegistry registry
TopologyProviderService providerService
TestProvider provider
TestListener listener = new TestListener()
Detailed Description
Test of the topology subsystem.
Definition at line 57 of file TopologyManagerTest.java.
Member Function Documentation
void org.onosproject.net.topology.impl.TopologyManagerTest.basics ()
Definition at line 95 of file TopologyManagerTest.java.
References org.onosproject.net.topology.TopologyService.isLatest(), org.onosproject.net.topology.impl.TopologyManagerTest.service, and org.onosproject.net.topology.impl.TopologyManagerTest.validateEvents().
void org.onosproject.net.topology.impl.TopologyManagerTest.clusters ()
Definition at line 122 of file TopologyManagerTest.java.
References find-link-in-cluster.cluster, org.onosproject.net.topology.Topology.clusterCount(), org.onosproject.net.topology.TopologyCluster.deviceCount(), org.onosproject.net.topology.Topology.deviceCount(), org.onosproject.net.topology.TopologyService.getClusterDevices(), org.onosproject.net.topology.TopologyService.getClusterLinks(), org.onosproject.net.topology.TopologyService.getClusters(), org.onosproject.net.topology.TopologyCluster.linkCount(), org.onosproject.net.topology.Topology.linkCount(), and org.onosproject.net.topology.impl.TopologyManagerTest.service.
void org.onosproject.net.topology.impl.TopologyManagerTest.graph ()
Definition at line 154 of file TopologyManagerTest.java.
void org.onosproject.net.topology.impl.TopologyManagerTest.onDemandPath ()
Definition at line 174 of file TopologyManagerTest.java.
void org.onosproject.net.topology.impl.TopologyManagerTest.precomputedPath ()
Definition at line 163 of file TopologyManagerTest.java.
void org.onosproject.net.topology.impl.TopologyManagerTest.setUp ()
Definition at line 70 of file TopologyManagerTest.java.
References org.onosproject.net.topology.impl.TopologyManagerTest.listener, org.onosproject.net.topology.impl.TopologyManagerTest.provider, org.onosproject.net.topology.impl.TopologyManagerTest.providerService, org.onosproject.net.topology.impl.TopologyManagerTest.registry, and org.onosproject.net.topology.impl.TopologyManagerTest.service.
void org.onosproject.net.topology.impl.TopologyManagerTest.structure ()
Definition at line 140 of file TopologyManagerTest.java.
References org.onosproject.net.topology.TopologyService.isBroadcastPoint(), org.onosproject.net.topology.TopologyService.isInfrastructure(), and org.onosproject.net.topology.impl.TopologyManagerTest.service.
void org.onosproject.net.topology.impl.TopologyManagerTest.tearDown ()
Definition at line 89 of file TopologyManagerTest.java.
References org.onosproject.net.topology.impl.TopologyManagerTest.listener.
void org.onosproject.net.topology.impl.TopologyManagerTest.validateEvents (Enum... types) protected
Definition at line 186 of file TopologyManagerTest.java.
References org.onosproject.net.topology.impl.TopologyManagerTest.listener.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.basics().
Member Data Documentation
TestListener org.onosproject.net.topology.impl.TopologyManagerTest.listener = new TestListener() protected
Definition at line 67 of file TopologyManagerTest.java.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.setUp(), org.onosproject.net.topology.impl.TopologyManagerTest.tearDown(), and org.onosproject.net.topology.impl.TopologyManagerTest.validateEvents().
TestProvider org.onosproject.net.topology.impl.TopologyManagerTest.provider protected
Definition at line 66 of file TopologyManagerTest.java.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.setUp().
TopologyProviderService org.onosproject.net.topology.impl.TopologyManagerTest.providerService protected
Definition at line 65 of file TopologyManagerTest.java.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.setUp().
TopologyProviderRegistry org.onosproject.net.topology.impl.TopologyManagerTest.registry protected
Definition at line 64 of file TopologyManagerTest.java.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.setUp().
TopologyService org.onosproject.net.topology.impl.TopologyManagerTest.service protected
Definition at line 63 of file TopologyManagerTest.java.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.basics(), org.onosproject.net.topology.impl.TopologyManagerTest.clusters(), org.onosproject.net.topology.impl.TopologyManagerTest.setUp(), and org.onosproject.net.topology.impl.TopologyManagerTest.structure().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/topology/impl/TopologyManagerTest.java