onos: org.onosproject.incubator.net.config.basics.InterfaceConfig Class Reference
org.onosproject.incubator.net.config.basics.InterfaceConfig Class Reference
Configuration for interfaces.
Public Member Functions
Set< Interface > getInterfaces () throws ConfigException
Retrieves all interfaces configured on this port.
void addInterface (Interface intf)
Adds an interface to the config.
void removeInterface (Interface intf)
Removes an interface from the config.
Static Public Attributes
static final String IPS = "ips"
static final String MAC = "mac"
static final String VLAN = "vlan"
static final String CONFIG_VALUE_ERROR = "Error parsing config value"
Detailed Description
Configuration for interfaces.
Definition at line 37 of file InterfaceConfig.java.
Member Function Documentation
void org.onosproject.incubator.net.config.basics.InterfaceConfig.addInterface (Interface intf)
Adds an interface to the config.
Parameters
intf interface to add
Definition at line 76 of file InterfaceConfig.java.
References org.onosproject.incubator.net.config.basics.InterfaceConfig.IPS, org.onosproject.incubator.net.config.basics.InterfaceConfig.MAC, org.onosproject.incubator.net.intf.Interface.mac(), org.onlab.packet.VlanId.NONE, and org.onosproject.incubator.net.config.basics.InterfaceConfig.VLAN.
Set<Interface> org.onosproject.incubator.net.config.basics.InterfaceConfig.getInterfaces () throws ConfigException
Retrieves all interfaces configured on this port.
Returns
set of interfaces
Exceptions
ConfigException if there is any error in the JSON config
Definition at line 50 of file InterfaceConfig.java.
References org.onosproject.incubator.net.config.basics.InterfaceConfig.CONFIG_VALUE_ERROR, org.onosproject.incubator.net.config.basics.InterfaceConfig.MAC, obeliskHostCheck.mac, and org.onlab.packet.MacAddress.valueOf().
Referenced by org.onosproject.incubator.net.intf.impl.InterfaceManager.remove().
void org.onosproject.incubator.net.config.basics.InterfaceConfig.removeInterface (Interface intf)
Removes an interface from the config.
Parameters
intf interface to remove
Definition at line 97 of file InterfaceConfig.java.
References create-flow.node.
Member Data Documentation
final String org.onosproject.incubator.net.config.basics.InterfaceConfig.CONFIG_VALUE_ERROR = "Error parsing config value" static
Definition at line 42 of file InterfaceConfig.java.
Referenced by org.onosproject.incubator.net.config.basics.InterfaceConfig.getInterfaces().
final String org.onosproject.incubator.net.config.basics.InterfaceConfig.IPS = "ips" static
Definition at line 38 of file InterfaceConfig.java.
Referenced by org.onosproject.incubator.net.config.basics.InterfaceConfig.addInterface().
final String org.onosproject.incubator.net.config.basics.InterfaceConfig.MAC = "mac" static
Definition at line 39 of file InterfaceConfig.java.
Referenced by org.onosproject.incubator.net.config.basics.InterfaceConfig.addInterface(), and org.onosproject.incubator.net.config.basics.InterfaceConfig.getInterfaces().
final String org.onosproject.incubator.net.config.basics.InterfaceConfig.VLAN = "vlan" static
Definition at line 40 of file InterfaceConfig.java.
Referenced by org.onosproject.incubator.net.config.basics.InterfaceConfig.addInterface().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/config/basics/InterfaceConfig.java