onos: org.onosproject.net.flow.DefaultFlowRuleTest Class Reference
org.onosproject.net.flow.DefaultFlowRuleTest Class Reference
Unit tests for the default flow rule class.
Public Member Functions
void testImmutability ()
Checks that the DefaultFlowRule class is immutable but can be inherited from.
void testEquals ()
Tests the equals, hashCode and toString methods using Guava EqualsTester.
void testCreationFromFlowRule ()
Tests creation of a DefaultFlowRule using a FlowRule constructor.
void testCreationWithFlowId ()
Tests creation of a DefaultFlowRule using a FlowId constructor.
void testCreationWithPayLoadByFlowTable ()
Tests creation of a DefaultFlowRule using a PayLoad constructor.
void testCreationWithPayLoadByGroupTable ()
Tests creation of a DefaultFlowRule using a PayLoad constructor.
void testCreationWithAppId ()
Tests the creation of a DefaultFlowRule using an AppId constructor.
Detailed Description
Unit tests for the default flow rule class.
Definition at line 34 of file DefaultFlowRuleTest.java.
Member Function Documentation
void org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule ()
Tests creation of a DefaultFlowRule using a FlowRule constructor.
Definition at line 70 of file DefaultFlowRuleTest.java.
References org.onosproject.net.flow.FlowRule.appId(), org.onosproject.net.flow.FlowRule.deviceId(), org.onosproject.net.flow.FlowRule.id(), org.onosproject.net.flow.FlowRule.isPermanent(), org.onosproject.net.flow.DefaultFlowRule.isPermanent(), org.onosproject.net.flow.FlowRule.payLoad(), org.onosproject.net.flow.FlowRule.priority(), org.onosproject.net.flow.FlowRule.selector(), org.onosproject.net.flow.FlowRule.timeout(), and org.onosproject.net.flow.FlowRule.treatment().
void org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithAppId ()
Tests the creation of a DefaultFlowRule using an AppId constructor.
Definition at line 143 of file DefaultFlowRuleTest.java.
References org.onosproject.net.flow.FlowRule.deviceId(), org.onosproject.net.flow.FlowRule.isPermanent(), org.onosproject.net.flow.FlowRule.priority(), org.onosproject.net.flow.FlowRule.selector(), org.onosproject.net.flow.FlowRule.timeout(), and org.onosproject.net.flow.FlowRule.treatment().
void org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithFlowId ()
Tests creation of a DefaultFlowRule using a FlowId constructor.
Definition at line 87 of file DefaultFlowRuleTest.java.
References org.onosproject.net.flow.FlowRule.deviceId(), org.onosproject.net.flow.FlowRule.isPermanent(), org.onosproject.net.flow.FlowRule.priority(), org.onosproject.net.flow.FlowRule.selector(), org.onosproject.net.flow.FlowRule.timeout(), and org.onosproject.net.flow.FlowRule.treatment().
void org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithPayLoadByFlowTable ()
Tests creation of a DefaultFlowRule using a PayLoad constructor.
Definition at line 111 of file DefaultFlowRuleTest.java.
References org.onosproject.net.flow.DefaultFlowRule.isPermanent().
void org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithPayLoadByGroupTable ()
Tests creation of a DefaultFlowRule using a PayLoad constructor.
Definition at line 127 of file DefaultFlowRuleTest.java.
References org.onosproject.net.flow.DefaultFlowRule.isPermanent().
void org.onosproject.net.flow.DefaultFlowRuleTest.testEquals ()
Tests the equals, hashCode and toString methods using Guava EqualsTester.
Definition at line 60 of file DefaultFlowRuleTest.java.
void org.onosproject.net.flow.DefaultFlowRuleTest.testImmutability ()
Checks that the DefaultFlowRule class is immutable but can be inherited from.
Definition at line 52 of file DefaultFlowRuleTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/flow/DefaultFlowRuleTest.java