onos: org.onosproject.net.topology.DefaultGraphDescriptionTest Class Reference
org.onosproject.net.topology.DefaultGraphDescriptionTest Class Reference
Public Member Functions
void basics ()
void missingVertex ()
Detailed Description
Definition at line 30 of file DefaultGraphDescriptionTest.java.
Member Function Documentation
void org.onosproject.net.topology.DefaultGraphDescriptionTest.basics ()
Definition at line 42 of file DefaultGraphDescriptionTest.java.
References org.onosproject.net.topology.DefaultGraphDescription.timestamp().
void org.onosproject.net.topology.DefaultGraphDescriptionTest.missingVertex ()
Definition at line 52 of file DefaultGraphDescriptionTest.java.
References org.onosproject.net.topology.GraphDescription.edges(), org.onosproject.net.topology.GraphDescription.timestamp(), and org.onosproject.net.topology.GraphDescription.vertexes().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/topology/DefaultGraphDescriptionTest.java