onos: org.onosproject.pcepio.types.PathSetupTypeTlv Class Reference
org.onosproject.pcepio.types.PathSetupTypeTlv Class Reference
Provides PcepSetup type tlv.
Public Member Functions
PathSetupTypeTlv (final int rawValue)
Constructor to initialize parameters for path setup type tlv.
PathSetupTypeTlv (byte pst)
Constructor to initialize pst.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
int getInt ()
Returns parameters for path setup type tlv.
byte getPst ()
Returns the pst value.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static PathSetupTypeTlv of (final int raw)
Returns Object of path setup type tlv.
static PathSetupTypeTlv read (ChannelBuffer c)
Returns the object of type PathSetupTypeTlv.
Static Public Attributes
static final short TYPE = 0
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PathSetupTypeTlv.class)
Detailed Description
Provides PcepSetup type tlv.
Definition at line 30 of file PathSetupTypeTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PathSetupTypeTlv.PathSetupTypeTlv (final int rawValue)
Constructor to initialize parameters for path setup type tlv.
Parameters
rawValue parameter for path setup type tlv
Definition at line 60 of file PathSetupTypeTlv.java.
Referenced by org.onosproject.pcepio.types.PathSetupTypeTlv.equals(), and org.onosproject.pcepio.types.PathSetupTypeTlv.of().
org.onosproject.pcepio.types.PathSetupTypeTlv.PathSetupTypeTlv (byte pst)
Constructor to initialize pst.
Parameters
pst PST
Definition at line 71 of file PathSetupTypeTlv.java.
Member Function Documentation
boolean org.onosproject.pcepio.types.PathSetupTypeTlv.equals (Object obj)
Definition at line 126 of file PathSetupTypeTlv.java.
References org.onosproject.pcepio.types.PathSetupTypeTlv.PathSetupTypeTlv().
int org.onosproject.pcepio.types.PathSetupTypeTlv.getInt ()
Returns parameters for path setup type tlv.
Returns
parameters for path setup type tlv
Definition at line 97 of file PathSetupTypeTlv.java.
short org.onosproject.pcepio.types.PathSetupTypeTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 116 of file PathSetupTypeTlv.java.
References org.onosproject.pcepio.types.PathSetupTypeTlv.LENGTH.
byte org.onosproject.pcepio.types.PathSetupTypeTlv.getPst ()
Returns the pst value.
Returns
pst value
Definition at line 106 of file PathSetupTypeTlv.java.
short org.onosproject.pcepio.types.PathSetupTypeTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 111 of file PathSetupTypeTlv.java.
References org.onosproject.pcepio.types.PathSetupTypeTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.PathSetupTypeTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 88 of file PathSetupTypeTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.PathSetupTypeTlv.hashCode ()
Definition at line 121 of file PathSetupTypeTlv.java.
static PathSetupTypeTlv org.onosproject.pcepio.types.PathSetupTypeTlv.of (final int raw) static
Returns Object of path setup type tlv.
Parameters
raw parameter for path setup type tlv
Returns
object of PathSetupTypeTlv
Definition at line 83 of file PathSetupTypeTlv.java.
References org.onosproject.pcepio.types.PathSetupTypeTlv.PathSetupTypeTlv().
static PathSetupTypeTlv org.onosproject.pcepio.types.PathSetupTypeTlv.read (ChannelBuffer c) static
Returns the object of type PathSetupTypeTlv.
Parameters
c is type Channel buffer
Returns
object of PathSetupTypeTlv
Definition at line 152 of file PathSetupTypeTlv.java.
String org.onosproject.pcepio.types.PathSetupTypeTlv.toString ()
Definition at line 157 of file PathSetupTypeTlv.java.
References org.onosproject.pcepio.types.PathSetupTypeTlv.LENGTH, and org.onosproject.pcepio.types.PathSetupTypeTlv.TYPE.
int org.onosproject.pcepio.types.PathSetupTypeTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 138 of file PathSetupTypeTlv.java.
References org.onosproject.pcepio.types.PathSetupTypeTlv.LENGTH, and org.onosproject.pcepio.types.PathSetupTypeTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.PathSetupTypeTlv.LENGTH = 4 static
Definition at line 49 of file PathSetupTypeTlv.java.
Referenced by org.onosproject.pcepio.types.PathSetupTypeTlv.getLength(), org.onosproject.pcepio.types.PathSetupTypeTlv.toString(), and org.onosproject.pcepio.types.PathSetupTypeTlv.write().
final Logger org.onosproject.pcepio.types.PathSetupTypeTlv.log = LoggerFactory.getLogger(PathSetupTypeTlv.class) static protected
Definition at line 46 of file PathSetupTypeTlv.java.
final short org.onosproject.pcepio.types.PathSetupTypeTlv.TYPE = 0 static
Definition at line 48 of file PathSetupTypeTlv.java.
Referenced by org.onosproject.pcepio.types.PathSetupTypeTlv.getType(), org.onosproject.pcepio.types.PathSetupTypeTlv.toString(), and org.onosproject.pcepio.types.PathSetupTypeTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PathSetupTypeTlv.java