onos: org.onosproject.net.HostLocation Class Reference
org.onosproject.net.HostLocation Class Reference
Representation of a network edge location where an end-station host is connected.
Public Member Functions
HostLocation (DeviceId deviceId, PortNumber portNumber, long time)
Creates a new host location using the supplied device & port.
HostLocation (ConnectPoint connectPoint, long time)
Creates a new host location derived from the supplied connection point.
long time ()
Returns the time when the location was established, given in milliseconds since start of epoch.
Public Member Functions inherited from org.onosproject.net.ConnectPoint
ConnectPoint (ElementId elementId, PortNumber portNumber)
Creates a new connection point.
ElementId elementId ()
Returns the network element identifier.
DeviceId deviceId ()
Returns the identifier of the infrastructure device if the connection point belongs to a network element which is indeed an infrastructure device.
HostId hostId ()
Returns the identifier of the infrastructure device if the connection point belongs to a network element which is indeed an end-station host.
IpElementId ipElementId ()
Returns the identifier of the infrastructure device if the connection point belongs to a network element which is indeed an ip of pcc client identifier.
PortNumber port ()
Returns the connection port number.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Attributes
static final HostLocation NONE = new HostLocation(DeviceId.NONE, P0, 0L)
Represents a no location or an unknown location.
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.net.ConnectPoint
static ConnectPoint deviceConnectPoint (String string)
Parse a device connect point from a string.
static ConnectPoint hostConnectPoint (String string)
Parse a host connect point from a string.
Detailed Description
Representation of a network edge location where an end-station host is connected.
Definition at line 24 of file HostLocation.java.
Constructor & Destructor Documentation
org.onosproject.net.HostLocation.HostLocation (DeviceId deviceId, PortNumber portNumber, long time)
Creates a new host location using the supplied device & port.
Parameters
deviceId device identity
portNumber device port number
time time when detected, in millis since start of epoch
Definition at line 41 of file HostLocation.java.
References org.onosproject.net.HostLocation.time().
org.onosproject.net.HostLocation.HostLocation (ConnectPoint connectPoint, long time)
Creates a new host location derived from the supplied connection point.
Parameters
connectPoint connection point
time time when detected, in millis since start of epoch
Definition at line 52 of file HostLocation.java.
References org.onosproject.net.ConnectPoint.deviceId(), and org.onosproject.net.HostLocation.time().
Member Function Documentation
long org.onosproject.net.HostLocation.time ()
Returns the time when the location was established, given in milliseconds since start of epoch.
Returns
time in milliseconds since start of epoch
Definition at line 63 of file HostLocation.java.
Referenced by org.onosproject.net.HostLocation.HostLocation().
Member Data Documentation
final HostLocation org.onosproject.net.HostLocation.NONE = new HostLocation(DeviceId.NONE, P0, 0L) static
Represents a no location or an unknown location.
Definition at line 29 of file HostLocation.java.
Referenced by org.onosproject.store.host.impl.ECHostStoreTest.testRemoveIp().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/HostLocation.java