onos: org.onosproject.codec.impl.IntentCodecTest Class Reference
org.onosproject.codec.impl.IntentCodecTest Class Reference
Unit tests for the host to host intent class codec.
Public Member Functions
void setUpIntentService ()
void hostToHostIntent ()
Tests the encoding of a host to host intent.
void pointToPointIntent ()
Tests the encoding of a point to point intent.
void intentWithTreatmentSelectorAndConstraints ()
Tests the encoding of an intent with treatment, selector and constraints specified.
void decodePointToPointIntent () throws IOException
Tests the point to point intent JSON codec.
void decodeHostToHostIntent () throws IOException
Tests the host to host intent JSON codec.
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Additional Inherited Members
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
Unit tests for the host to host intent class codec.
Definition at line 87 of file IntentCodecTest.java.
Member Function Documentation
void org.onosproject.codec.impl.IntentCodecTest.decodeHostToHostIntent () throws IOException
Tests the host to host intent JSON codec.
Exceptions
IOException
Definition at line 274 of file IntentCodecTest.java.
References org.onosproject.net.intent.ConnectivityIntent.constraints(), and org.onosproject.net.intent.Intent.priority().
void org.onosproject.codec.impl.IntentCodecTest.decodePointToPointIntent () throws IOException
Tests the point to point intent JSON codec.
Exceptions
IOException if JSON processing fails
Definition at line 233 of file IntentCodecTest.java.
References org.onosproject.net.intent.ConnectivityIntent.constraints(), org.onosproject.net.PortNumber.portNumber(), org.onosproject.net.intent.Intent.priority(), org.onosproject.net.intent.ConnectivityIntent.selector(), and org.onosproject.net.intent.ConnectivityIntent.treatment().
void org.onosproject.codec.impl.IntentCodecTest.hostToHostIntent ()
Tests the encoding of a host to host intent.
Definition at line 113 of file IntentCodecTest.java.
References create-intent.intentJson.
void org.onosproject.codec.impl.IntentCodecTest.intentWithTreatmentSelectorAndConstraints ()
Tests the encoding of an intent with treatment, selector and constraints specified.
Definition at line 158 of file IntentCodecTest.java.
References org.onlab.packet.MacAddress.BROADCAST, org.onosproject.net.ChannelSpacing.CHL_100GHZ, org.onosproject.net.PortNumber.CONTROLLER, org.onosproject.net.GridType.DWDM, create-intent.egress, org.onosproject.net.OchSignalType.FIXED_GRID, create-intent.ingress, create-intent.intentJson, org.onosproject.net.flow.criteria.Criteria.matchLambda(), org.onosproject.net.flow.criteria.Criteria.matchOchSignalType(), and org.onosproject.net.flow.instructions.Instructions.modL0Lambda().
void org.onosproject.codec.impl.IntentCodecTest.pointToPointIntent ()
Tests the encoding of a point to point intent.
Definition at line 133 of file IntentCodecTest.java.
References create-intent.egress, create-intent.ingress, and create-intent.intentJson.
void org.onosproject.codec.impl.IntentCodecTest.setUpIntentService ()
Definition at line 100 of file IntentCodecTest.java.
References org.onosproject.core.CoreService.getAppId(), and org.onosproject.core.ApplicationId.name().
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/codec/impl/IntentCodecTest.java