onos: org.onlab.packet.Ip4AddressTest Class Reference
org.onlab.packet.Ip4AddressTest Class Reference
Tests for class Ip4Address.
Public Member Functions
void testImmutable ()
Tests the immutability of Ip4Address.
void testAddressVersion ()
Tests the IPv4 address version constant.
void testAddrByteLength ()
Tests the length of the address in bytes (octets).
void testAddrBitLength ()
Tests the length of the address in bits.
void testVersion ()
Tests returning the IP address version.
void testAddressToOctetsIPv4 ()
Tests returning an IPv4 address as a byte array.
void testToInt ()
Tests returning an IPv4 address as an integer.
void testValueOfForIntegerIPv4 ()
Tests valueOf() converter for IPv4 integer value.
void testValueOfByteArrayIPv4 ()
Tests valueOf() converter for IPv4 byte array.
void testInvalidValueOfNullArrayIPv4 ()
Tests invalid valueOf() converter for a null array for IPv4.
void testInvalidValueOfShortArrayIPv4 ()
Tests invalid valueOf() converger for an array that is too short for IPv4.
void testValueOfByteArrayOffsetIPv4 ()
Tests valueOf() converter for IPv4 byte array and an offset.
void testInvalidValueOfArrayInvalidOffsetIPv4 ()
Tests invalid valueOf() converger for an array and an invalid offset for IPv4.
void testValueOfInetAddressIPv4 ()
Tests valueOf() converter for IPv4 InetAddress.
void testValueOfStringIPv4 ()
Tests valueOf() converter for IPv4 string.
void testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
void testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
void testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
void testMakeMaskPrefixIPv4 ()
Tests making a mask prefix for a given prefix length for IPv4.
void testInvalidMakeNegativeMaskPrefixIPv4 ()
Tests making a mask prefix for an invalid prefix length for IPv4: negative prefix length.
void testInvalidMakeTooLongMaskPrefixIPv4 ()
Tests making a mask prefix for an invalid prefix length for IPv4: too long prefix length.
void testMakeMaskedAddressIPv4 ()
Tests making of a masked address for IPv4.
void testInvalidMakeNegativeMaskedAddressIPv4 ()
Tests making of a masked address for invalid prefix length for IPv4: negative prefix length.
void testInvalidMakeTooLongMaskedAddressIPv4 ()
Tests making of a masked address for an invalid prefix length for IPv4: too long prefix length.
void testComparisonIPv4 ()
Tests comparison of Ip4Address for IPv4.
void testEqualityIPv4 ()
Tests equality of Ip4Address for IPv4.
void testToStringIPv4 ()
Tests object string representation for IPv4.
Detailed Description
Tests for class Ip4Address.
Definition at line 32 of file Ip4AddressTest.java.
Member Function Documentation
void org.onlab.packet.Ip4AddressTest.testAddrBitLength ()
Tests the length of the address in bits.
Definition at line 61 of file Ip4AddressTest.java.
References org.onlab.packet.Ip4Address.BIT_LENGTH.
void org.onlab.packet.Ip4AddressTest.testAddrByteLength ()
Tests the length of the address in bytes (octets).
Definition at line 53 of file Ip4AddressTest.java.
References org.onlab.packet.Ip4Address.BYTE_LENGTH.
void org.onlab.packet.Ip4AddressTest.testAddressToOctetsIPv4 ()
Tests returning an IPv4 address as a byte array.
Definition at line 81 of file Ip4AddressTest.java.
References org.onlab.packet.IpAddress.toOctets().
void org.onlab.packet.Ip4AddressTest.testAddressVersion ()
Tests the IPv4 address version constant.
Definition at line 45 of file Ip4AddressTest.java.
References org.onlab.packet.Ip4Address.VERSION.
void org.onlab.packet.Ip4AddressTest.testComparisonIPv4 ()
Tests comparison of Ip4Address for IPv4.
Definition at line 379 of file Ip4AddressTest.java.
References org.onlab.packet.IpAddress.compareTo().
void org.onlab.packet.Ip4AddressTest.testEqualityIPv4 ()
Tests equality of Ip4Address for IPv4.
Definition at line 403 of file Ip4AddressTest.java.
References org.onlab.packet.Ip4Address.valueOf().
void org.onlab.packet.Ip4AddressTest.testImmutable ()
Tests the immutability of Ip4Address.
Definition at line 37 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testInvalidMakeNegativeMaskedAddressIPv4 ()
Tests making of a masked address for invalid prefix length for IPv4: negative prefix length.
Definition at line 356 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testInvalidMakeNegativeMaskPrefixIPv4 ()
Tests making a mask prefix for an invalid prefix length for IPv4: negative prefix length.
Definition at line 316 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testInvalidMakeTooLongMaskedAddressIPv4 ()
Tests making of a masked address for an invalid prefix length for IPv4: too long prefix length.
Definition at line 368 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testInvalidMakeTooLongMaskPrefixIPv4 ()
Tests making a mask prefix for an invalid prefix length for IPv4: too long prefix length.
Definition at line 327 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testInvalidValueOfArrayInvalidOffsetIPv4 ()
Tests invalid valueOf() converger for an array and an invalid offset for IPv4.
Definition at line 213 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
Definition at line 276 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
Definition at line 287 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testInvalidValueOfNullArrayIPv4 ()
Tests invalid valueOf() converter for a null array for IPv4.
Definition at line 159 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
Definition at line 265 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testInvalidValueOfShortArrayIPv4 ()
Tests invalid valueOf() converger for an array that is too short for IPv4.
Definition at line 172 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testMakeMaskedAddressIPv4 ()
Tests making of a masked address for IPv4.
Definition at line 337 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testMakeMaskPrefixIPv4 ()
Tests making a mask prefix for a given prefix length for IPv4.
Definition at line 298 of file Ip4AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip4AddressTest.testToInt ()
Tests returning an IPv4 address as an integer.
Definition at line 103 of file Ip4AddressTest.java.
References org.onlab.packet.Ip4Address.toInt().
void org.onlab.packet.Ip4AddressTest.testToStringIPv4 ()
Tests object string representation for IPv4.
Definition at line 420 of file Ip4AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip4AddressTest.testValueOfByteArrayIPv4 ()
Tests valueOf() converter for IPv4 byte array.
Definition at line 137 of file Ip4AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip4AddressTest.testValueOfByteArrayOffsetIPv4 ()
Tests valueOf() converter for IPv4 byte array and an offset.
Definition at line 184 of file Ip4AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip4AddressTest.testValueOfForIntegerIPv4 ()
Tests valueOf() converter for IPv4 integer value.
Definition at line 120 of file Ip4AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip4AddressTest.testValueOfInetAddressIPv4 ()
Tests valueOf() converter for IPv4 InetAddress.
Definition at line 227 of file Ip4AddressTest.java.
void org.onlab.packet.Ip4AddressTest.testValueOfStringIPv4 ()
Tests valueOf() converter for IPv4 string.
Definition at line 248 of file Ip4AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip4AddressTest.testVersion ()
Tests returning the IP address version.
Definition at line 69 of file Ip4AddressTest.java.
References org.onlab.packet.IpAddress.version().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/Ip4AddressTest.java