onos: org.onosproject.rest.LinksResourceTest Class Reference
org.onosproject.rest.LinksResourceTest Class Reference
Unit tests for links REST APIs.
Classes
class LinkJsonMatcher
Hamcrest matcher to check that an link representation in JSON matches the actual link.
Public Member Functions
void setUpTest ()
Initializes test mocks and environment.
void tearDownTest ()
Tears down and verifies test mocks and environment.
void testLinksEmptyArray ()
Tests the result of the rest api GET when there are no links.
void testLinks ()
Tests the result of the rest api GET when there are links present.
void testLinksByDevice ()
Tests the result of the rest api GET of links for a specific device.
void testLinksByDevicePort ()
Tests the result of the rest api GET of links for a specific device and port.
void testLinksByDevicePortDirection ()
Tests the result of the rest api GET of links for a specific device, port, and direction.
void testLinksByDeviceDirection ()
Tests the result of the rest api GET of links for a specific device and direction.
Public Member Functions inherited from org.onosproject.rest.ResourceTest
int getPort (int defaultPort)
Assigns an available port for the test.
AppDescriptor configure ()
Detailed Description
Unit tests for links REST APIs.
Definition at line 54 of file LinksResourceTest.java.
Member Function Documentation
void org.onosproject.rest.LinksResourceTest.setUpTest ()
Initializes test mocks and environment.
Definition at line 153 of file LinksResourceTest.java.
void org.onosproject.rest.LinksResourceTest.tearDownTest ()
Tears down and verifies test mocks and environment.
Definition at line 171 of file LinksResourceTest.java.
void org.onosproject.rest.LinksResourceTest.testLinks ()
Tests the result of the rest api GET when there are links present.
Definition at line 192 of file LinksResourceTest.java.
References org.onosproject.net.link.LinkService.getLinks().
void org.onosproject.rest.LinksResourceTest.testLinksByDevice ()
Tests the result of the rest api GET of links for a specific device.
Definition at line 222 of file LinksResourceTest.java.
References org.onosproject.net.link.LinkService.getDeviceLinks().
void org.onosproject.rest.LinksResourceTest.testLinksByDeviceDirection ()
Tests the result of the rest api GET of links for a specific device and direction.
Definition at line 323 of file LinksResourceTest.java.
References org.onosproject.net.link.LinkService.getDeviceIngressLinks().
void org.onosproject.rest.LinksResourceTest.testLinksByDevicePort ()
Tests the result of the rest api GET of links for a specific device and port.
Definition at line 254 of file LinksResourceTest.java.
References org.onosproject.net.link.LinkService.getLinks().
void org.onosproject.rest.LinksResourceTest.testLinksByDevicePortDirection ()
Tests the result of the rest api GET of links for a specific device, port, and direction.
Definition at line 288 of file LinksResourceTest.java.
References org.onosproject.net.link.LinkService.getIngressLinks().
void org.onosproject.rest.LinksResourceTest.testLinksEmptyArray ()
Tests the result of the rest api GET when there are no links.
Definition at line 179 of file LinksResourceTest.java.
References org.onosproject.net.link.LinkService.getLinks().
The documentation for this class was generated from the following file:
web/api/src/test/java/org/onosproject/rest/LinksResourceTest.java