onos: org.onosproject.net.group.DefaultGroupKey Class Reference
org.onosproject.net.group.DefaultGroupKey Class Reference
Default implementation of group key interface.
Public Member Functions
DefaultGroupKey (byte[] key)
byte[] key ()
Returns the byte representation of key.
boolean equals (Object o)
int hashCode ()
String toString ()
Returns a hex string representation of the byte array that is used as a group key.
Static Protected Attributes
static final char[] HEX_ARRAY = "0123456789ABCDEF".toCharArray()
Detailed Description
Default implementation of group key interface.
Definition at line 25 of file DefaultGroupKey.java.
Constructor & Destructor Documentation
org.onosproject.net.group.DefaultGroupKey.DefaultGroupKey (byte[] key)
Definition at line 30 of file DefaultGroupKey.java.
Referenced by org.onosproject.net.group.DefaultGroupKey.equals().
Member Function Documentation
boolean org.onosproject.net.group.DefaultGroupKey.equals (Object o)
Definition at line 40 of file DefaultGroupKey.java.
References org.onosproject.net.group.DefaultGroupKey.DefaultGroupKey().
int org.onosproject.net.group.DefaultGroupKey.hashCode ()
Definition at line 52 of file DefaultGroupKey.java.
byte [] org.onosproject.net.group.DefaultGroupKey.key ()
Returns the byte representation of key.
Returns
byte array
Implements org.onosproject.net.group.GroupKey.
Definition at line 35 of file DefaultGroupKey.java.
Referenced by org.onosproject.net.group.DefaultGroupKey.toString().
String org.onosproject.net.group.DefaultGroupKey.toString ()
Returns a hex string representation of the byte array that is used as a group key.
This solution was adapted from http://stackoverflow.com/questions/9655181/
Definition at line 62 of file DefaultGroupKey.java.
References org.onosproject.net.group.DefaultGroupKey.HEX_ARRAY, org.onosproject.net.group.DefaultGroupKey.key(), and find-link-in-cluster.length.
Member Data Documentation
final char [] org.onosproject.net.group.DefaultGroupKey.HEX_ARRAY = "0123456789ABCDEF".toCharArray() static protected
Definition at line 28 of file DefaultGroupKey.java.
Referenced by org.onosproject.net.group.DefaultGroupKey.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/group/DefaultGroupKey.java