onos: org.onosproject.ovsdb.rfc.table.TableGenerator Class Reference
org.onosproject.ovsdb.rfc.table.TableGenerator Class Reference
Table generator.
Static Public Member Functions
static Object createTable (DatabaseSchema dbSchema, OvsdbTable tableName)
Create table.
static Object getTable (DatabaseSchema dbSchema, Row row, OvsdbTable tableName)
Get table from Row.
Detailed Description
Table generator.
Definition at line 24 of file TableGenerator.java.
Member Function Documentation
static Object org.onosproject.ovsdb.rfc.table.TableGenerator.createTable (DatabaseSchema dbSchema, OvsdbTable tableName) static
Create table.
Parameters
dbSchema DatabaseSchema entity
tableName table name
Returns
Object table entity
Definition at line 41 of file TableGenerator.java.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge(), and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createTunnel().
static Object org.onosproject.ovsdb.rfc.table.TableGenerator.getTable (DatabaseSchema dbSchema, Row row, OvsdbTable tableName) static
Get table from Row.
Parameters
dbSchema DatabaseSchema entity
row Row entity
tableName table name
Returns
Object table entity
Definition at line 54 of file TableGenerator.java.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getInterfaceUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPortUuid(), and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setControllersWithUUID().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/TableGenerator.java