onos: org.onosproject.bgpio.types.attr.BgpLinkAttrName Class Reference
org.onosproject.bgpio.types.attr.BgpLinkAttrName Class Reference
Implements BGP link name attribute.
Public Member Functions
BgpLinkAttrName (byte[] linkName)
Constructor to initialize the values.
byte[] attrLinkName ()
Returns the link name.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpLinkAttrName of (byte[] linkName)
Returns object of this class with specified values.
static BgpLinkAttrName read (ChannelBuffer cb) throws BgpParseException
Reads the BGP link attributes Name.
Static Public Attributes
static final int ATTRLINK_NAME = 1098
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP link name attribute.
Definition at line 33 of file BgpLinkAttrName.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpLinkAttrName.BgpLinkAttrName (byte[] linkName)
Constructor to initialize the values.
Parameters
linkName link name
Definition at line 48 of file BgpLinkAttrName.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrName.equals(), and org.onosproject.bgpio.types.attr.BgpLinkAttrName.of().
Member Function Documentation
byte [] org.onosproject.bgpio.types.attr.BgpLinkAttrName.attrLinkName ()
Returns the link name.
Returns
link name
Definition at line 90 of file BgpLinkAttrName.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrName.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 130 of file BgpLinkAttrName.java.
boolean org.onosproject.bgpio.types.attr.BgpLinkAttrName.equals (Object obj)
Definition at line 105 of file BgpLinkAttrName.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrName.BgpLinkAttrName().
short org.onosproject.bgpio.types.attr.BgpLinkAttrName.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 95 of file BgpLinkAttrName.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrName.ATTRLINK_NAME.
int org.onosproject.bgpio.types.attr.BgpLinkAttrName.hashCode ()
Definition at line 100 of file BgpLinkAttrName.java.
static BgpLinkAttrName org.onosproject.bgpio.types.attr.BgpLinkAttrName.of (byte[] linkName) static
Returns object of this class with specified values.
Parameters
linkName Prefix Metric
Returns
object of BgpLinkAttrName
Definition at line 58 of file BgpLinkAttrName.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrName.BgpLinkAttrName().
static BgpLinkAttrName org.onosproject.bgpio.types.attr.BgpLinkAttrName.read (ChannelBuffer cb) throws BgpParseException static
Reads the BGP link attributes Name.
Parameters
cb Channel buffer
Returns
object of type BgpLinkAttrName
Exceptions
BgpParseException while parsing BgpLinkAttrName
Definition at line 69 of file BgpLinkAttrName.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpLinkAttrName.toString ()
Definition at line 124 of file BgpLinkAttrName.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrName.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 118 of file BgpLinkAttrName.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpLinkAttrName.ATTRLINK_NAME = 1098 static
Definition at line 38 of file BgpLinkAttrName.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrName.getType().
final Logger org.onosproject.bgpio.types.attr.BgpLinkAttrName.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpLinkAttrName.class)
Definition at line 35 of file BgpLinkAttrName.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpLinkAttrName.java