onos: org.onosproject.bgpio.types.IsIsPseudonode Class Reference
org.onosproject.bgpio.types.IsIsPseudonode Class Reference
Provides implementation of IsIsPseudonode Tlv.
Public Member Functions
IsIsPseudonode (byte[] isoNodeID, byte psnIdentifier)
Constructor to initialize isoNodeID.
byte[] getISONodeID ()
Returns ISO NodeID.
byte getPSNIdentifier ()
Returns PSN Identifier.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of BGP Message to channel buffer.
short getType ()
Returns the Type of BGP Message.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static IsIsPseudonode of (final byte[] isoNodeID, final byte psnIdentifier)
Returns object of this class with specified values.
static IsIsPseudonode read (ChannelBuffer cb)
Reads the channel buffer and returns object of IsIsPseudonode.
Static Public Attributes
static final short TYPE = 515
static final short LENGTH = 7
Detailed Description
Provides implementation of IsIsPseudonode Tlv.
Definition at line 30 of file IsIsPseudonode.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.IsIsPseudonode.IsIsPseudonode (byte[] isoNodeID, byte psnIdentifier)
Constructor to initialize isoNodeID.
Parameters
isoNodeID ISO system-ID
psnIdentifier PSN identifier
Definition at line 43 of file IsIsPseudonode.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.bgpio.types.IsIsPseudonode.compareTo(), org.onosproject.bgpio.types.IsIsPseudonode.equals(), and org.onosproject.bgpio.types.IsIsPseudonode.of().
Member Function Documentation
int org.onosproject.bgpio.types.IsIsPseudonode.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 125 of file IsIsPseudonode.java.
References org.onosproject.bgpio.types.IsIsPseudonode.equals(), and org.onosproject.bgpio.types.IsIsPseudonode.IsIsPseudonode().
boolean org.onosproject.bgpio.types.IsIsPseudonode.equals (Object obj)
Definition at line 84 of file IsIsPseudonode.java.
References org.onosproject.bgpio.types.IsIsPseudonode.IsIsPseudonode().
Referenced by org.onosproject.bgpio.types.IsIsPseudonode.compareTo().
byte [] org.onosproject.bgpio.types.IsIsPseudonode.getISONodeID ()
Returns ISO NodeID.
Returns
ISO NodeID
Definition at line 65 of file IsIsPseudonode.java.
byte org.onosproject.bgpio.types.IsIsPseudonode.getPSNIdentifier ()
Returns PSN Identifier.
Returns
PSN Identifier
Definition at line 74 of file IsIsPseudonode.java.
short org.onosproject.bgpio.types.IsIsPseudonode.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 120 of file IsIsPseudonode.java.
References org.onosproject.bgpio.types.IsIsPseudonode.TYPE.
int org.onosproject.bgpio.types.IsIsPseudonode.hashCode ()
Definition at line 79 of file IsIsPseudonode.java.
static IsIsPseudonode org.onosproject.bgpio.types.IsIsPseudonode.of (final byte[] isoNodeID, final byte psnIdentifier) static
Returns object of this class with specified values.
Parameters
isoNodeID ISO system-ID
psnIdentifier PSN identifier
Returns
object of IsIsPseudonode
Definition at line 55 of file IsIsPseudonode.java.
References org.onosproject.bgpio.types.IsIsPseudonode.IsIsPseudonode().
static IsIsPseudonode org.onosproject.bgpio.types.IsIsPseudonode.read (ChannelBuffer cb) static
Reads the channel buffer and returns object of IsIsPseudonode.
Parameters
cb ChannelBuffer
Returns
object of IsIsPseudonode
Definition at line 112 of file IsIsPseudonode.java.
References org.onosproject.bgpio.types.IsIsPseudonode.LENGTH.
String org.onosproject.bgpio.types.IsIsPseudonode.toString ()
Definition at line 138 of file IsIsPseudonode.java.
References org.onosproject.bgpio.types.IsIsPseudonode.LENGTH, and org.onosproject.bgpio.types.IsIsPseudonode.TYPE.
int org.onosproject.bgpio.types.IsIsPseudonode.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 97 of file IsIsPseudonode.java.
References org.onosproject.bgpio.types.IsIsPseudonode.LENGTH, and org.onosproject.bgpio.types.IsIsPseudonode.TYPE.
Member Data Documentation
final short org.onosproject.bgpio.types.IsIsPseudonode.LENGTH = 7 static
Definition at line 32 of file IsIsPseudonode.java.
Referenced by org.onosproject.bgpio.types.IsIsPseudonode.read(), org.onosproject.bgpio.types.IsIsPseudonode.toString(), and org.onosproject.bgpio.types.IsIsPseudonode.write().
final short org.onosproject.bgpio.types.IsIsPseudonode.TYPE = 515 static
Definition at line 31 of file IsIsPseudonode.java.
Referenced by org.onosproject.bgpio.types.IsIsPseudonode.getType(), org.onosproject.bgpio.types.IsIsPseudonode.toString(), and org.onosproject.bgpio.types.IsIsPseudonode.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/IsIsPseudonode.java