onos: org.onosproject.bgp.controller.impl.Controller Class Reference
org.onosproject.bgp.controller.impl.Controller Class Reference
The main controller class.
Public Member Functions
Controller (BgpController bgpController)
Constructor to initialize the values.
long getSystemStartTime ()
To get system start time.
void run ()
Tell controller that we're ready to accept bgp peer connections.
void init ()
Initialize internal data structures.
Map< String, Long > getMemory ()
Gets run time memory.
Long getUptime ()
Gets UP time.
void start ()
Starts the BGP controller.
void stop ()
Stops the BGP controller.
void setBgpPortNum ()
sets the isPortNumSet as true.
Static Public Member Functions
static ClientBootstrap peerBootstrap ()
Gets peer bootstrap.
static short getBgpPortNum ()
Returns port number.
Public Attributes
Channel serverChannel
Detailed Description
The main controller class.
Handles all setup and network listeners - Distributed ownership control of bgp peer through IControllerRegistryService
Definition at line 46 of file Controller.java.
Constructor & Destructor Documentation
org.onosproject.bgp.controller.impl.Controller.Controller (BgpController bgpController)
Constructor to initialize the values.
Parameters
bgpController bgp controller instance
Definition at line 78 of file Controller.java.
Member Function Documentation
static short org.onosproject.bgp.controller.impl.Controller.getBgpPortNum () static
Returns port number.
Returns
port number
Definition at line 241 of file Controller.java.
Referenced by org.onosproject.bgp.controller.impl.Controller.run().
Map<String, Long> org.onosproject.bgp.controller.impl.Controller.getMemory ()
Gets run time memory.
Returns
m run time memory
Definition at line 199 of file Controller.java.
long org.onosproject.bgp.controller.impl.Controller.getSystemStartTime ()
To get system start time.
Returns
system start time in milliseconds
Definition at line 96 of file Controller.java.
Long org.onosproject.bgp.controller.impl.Controller.getUptime ()
Gets UP time.
Returns
UP time
Definition at line 212 of file Controller.java.
void org.onosproject.bgp.controller.impl.Controller.init ()
Initialize internal data structures.
Definition at line 188 of file Controller.java.
static ClientBootstrap org.onosproject.bgp.controller.impl.Controller.peerBootstrap () static
Gets peer bootstrap.
Returns
peer bootstrap
Definition at line 181 of file Controller.java.
Referenced by org.onosproject.bgp.controller.impl.Controller.run().
void org.onosproject.bgp.controller.impl.Controller.run ()
Tell controller that we're ready to accept bgp peer connections.
Definition at line 103 of file Controller.java.
References org.onosproject.bgp.controller.impl.Controller.getBgpPortNum(), org.onosproject.bgp.controller.impl.Controller.peerBootstrap(), and org.onosproject.bgp.controller.impl.Controller.serverChannel.
void org.onosproject.bgp.controller.impl.Controller.setBgpPortNum ()
sets the isPortNumSet as true.
Definition at line 251 of file Controller.java.
void org.onosproject.bgp.controller.impl.Controller.start ()
Starts the BGP controller.
Definition at line 220 of file Controller.java.
void org.onosproject.bgp.controller.impl.Controller.stop ()
Stops the BGP controller.
Definition at line 229 of file Controller.java.
Member Data Documentation
Channel org.onosproject.bgp.controller.impl.Controller.serverChannel
Definition at line 53 of file Controller.java.
Referenced by org.onosproject.bgp.controller.impl.Controller.run().
The documentation for this class was generated from the following file:
bgp/ctl/src/main/java/org/onosproject/bgp/controller/impl/Controller.java