onos: org.onosproject.bgpio.types.OSPFPseudonode Class Reference
org.onosproject.bgpio.types.OSPFPseudonode Class Reference
Provides implementation of OSPFPseudonode Tlv.
Public Member Functions
OSPFPseudonode (int routerID, Ip4Address drInterface)
Constructor to initialize parameters.
int getrouterID ()
Returns RouterID.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of BGP Message to channel buffer.
short getType ()
Returns the Type of BGP Message.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static OSPFPseudonode of (final int routerID, final Ip4Address drInterface)
Returns object of this class with specified values.
static OSPFPseudonode read (ChannelBuffer cb)
Reads the channel buffer and returns object of OSPFPseudonode.
Static Public Attributes
static final short TYPE = 515
static final short LENGTH = 8
Detailed Description
Provides implementation of OSPFPseudonode Tlv.
Definition at line 29 of file OSPFPseudonode.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.OSPFPseudonode.OSPFPseudonode (int routerID, Ip4Address drInterface)
Constructor to initialize parameters.
Parameters
routerID routerID
drInterface IPv4 address of the DR's interface
Definition at line 42 of file OSPFPseudonode.java.
Referenced by org.onosproject.bgpio.types.OSPFPseudonode.compareTo(), org.onosproject.bgpio.types.OSPFPseudonode.equals(), and org.onosproject.bgpio.types.OSPFPseudonode.of().
Member Function Documentation
int org.onosproject.bgpio.types.OSPFPseudonode.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 112 of file OSPFPseudonode.java.
References org.onosproject.bgpio.types.OSPFPseudonode.equals(), and org.onosproject.bgpio.types.OSPFPseudonode.OSPFPseudonode().
boolean org.onosproject.bgpio.types.OSPFPseudonode.equals (Object obj)
Definition at line 73 of file OSPFPseudonode.java.
References org.onosproject.bgpio.types.OSPFPseudonode.OSPFPseudonode().
Referenced by org.onosproject.bgpio.types.OSPFPseudonode.compareTo().
int org.onosproject.bgpio.types.OSPFPseudonode.getrouterID ()
Returns RouterID.
Returns
RouterID
Definition at line 63 of file OSPFPseudonode.java.
short org.onosproject.bgpio.types.OSPFPseudonode.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 107 of file OSPFPseudonode.java.
References org.onosproject.bgpio.types.OSPFPseudonode.TYPE.
int org.onosproject.bgpio.types.OSPFPseudonode.hashCode ()
Definition at line 68 of file OSPFPseudonode.java.
static OSPFPseudonode org.onosproject.bgpio.types.OSPFPseudonode.of (final int routerID, final Ip4Address drInterface) static
Returns object of this class with specified values.
Parameters
routerID routerID
drInterface IPv4 address of the DR's interface
Returns
object of OSPFPseudonode
Definition at line 54 of file OSPFPseudonode.java.
References org.onosproject.bgpio.types.OSPFPseudonode.OSPFPseudonode().
static OSPFPseudonode org.onosproject.bgpio.types.OSPFPseudonode.read (ChannelBuffer cb) static
Reads the channel buffer and returns object of OSPFPseudonode.
Parameters
cb ChannelBuffer
Returns
object of OSPFPseudonode
Definition at line 100 of file OSPFPseudonode.java.
String org.onosproject.bgpio.types.OSPFPseudonode.toString ()
Definition at line 124 of file OSPFPseudonode.java.
References org.onosproject.bgpio.types.OSPFPseudonode.LENGTH, and org.onosproject.bgpio.types.OSPFPseudonode.TYPE.
int org.onosproject.bgpio.types.OSPFPseudonode.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 85 of file OSPFPseudonode.java.
References org.onosproject.bgpio.types.OSPFPseudonode.LENGTH, and org.onosproject.bgpio.types.OSPFPseudonode.TYPE.
Member Data Documentation
final short org.onosproject.bgpio.types.OSPFPseudonode.LENGTH = 8 static
Definition at line 31 of file OSPFPseudonode.java.
Referenced by org.onosproject.bgpio.types.OSPFPseudonode.toString(), and org.onosproject.bgpio.types.OSPFPseudonode.write().
final short org.onosproject.bgpio.types.OSPFPseudonode.TYPE = 515 static
Definition at line 30 of file OSPFPseudonode.java.
Referenced by org.onosproject.bgpio.types.OSPFPseudonode.getType(), org.onosproject.bgpio.types.OSPFPseudonode.toString(), and org.onosproject.bgpio.types.OSPFPseudonode.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/OSPFPseudonode.java