onos: org.onosproject.routing.bgp.BgpSessionManagerTest Class Reference
org.onosproject.routing.bgp.BgpSessionManagerTest Class Reference
Unit tests for the BgpSessionManager class.
Public Member Functions
void setUp () throws Exception
void tearDown () throws Exception
void testExchangedBgpOpenMessages () throws InterruptedException, TestUtilsException
Tests that the BGP OPEN messages have been exchanged, followed by KEEPALIVE.
void testExchangedBgpOpenCapabilityMessages () throws InterruptedException, TestUtilsException
Tests that the BGP OPEN with Capability messages have been exchanged, followed by KEEPALIVE.
void testProcessedBgpUpdateMessages () throws InterruptedException
Tests that the BGP UPDATE messages have been received and processed.
void testBgpRoutePreference () throws InterruptedException
Tests the BGP route preference.
Detailed Description
Unit tests for the BgpSessionManager class.
Definition at line 61 of file BgpSessionManagerTest.java.
Member Function Documentation
void org.onosproject.routing.bgp.BgpSessionManagerTest.setUp () throws Exception
Definition at line 251 of file BgpSessionManagerTest.java.
void org.onosproject.routing.bgp.BgpSessionManagerTest.tearDown () throws Exception
Definition at line 309 of file BgpSessionManagerTest.java.
void org.onosproject.routing.bgp.BgpSessionManagerTest.testBgpRoutePreference () throws InterruptedException
Tests the BGP route preference.
Definition at line 692 of file BgpSessionManagerTest.java.
References org.onlab.packet.Ip4Prefix.valueOf().
void org.onosproject.routing.bgp.BgpSessionManagerTest.testExchangedBgpOpenCapabilityMessages () throws InterruptedException, TestUtilsException
Tests that the BGP OPEN with Capability messages have been exchanged, followed by KEEPALIVE.
The BGP Peer opens the sessions and transmits OPEN Message, eventually followed by KEEPALIVE. The tested BGP listener should respond by OPEN Message, followed by KEEPALIVE.
Exceptions
TestUtilsException TestUtils error
Definition at line 463 of file BgpSessionManagerTest.java.
References org.onosproject.routing.bgp.BgpConstants.BGP_VERSION, and org.onosproject.routing.bgp.BgpSessionManager.getBgpSessions().
void org.onosproject.routing.bgp.BgpSessionManagerTest.testExchangedBgpOpenMessages () throws InterruptedException, TestUtilsException
Tests that the BGP OPEN messages have been exchanged, followed by KEEPALIVE.
The BGP Peer opens the sessions and transmits OPEN Message, eventually followed by KEEPALIVE. The tested BGP listener should respond by OPEN Message, followed by KEEPALIVE.
Exceptions
TestUtilsException TestUtils error
Definition at line 416 of file BgpSessionManagerTest.java.
References org.onosproject.routing.bgp.BgpConstants.BGP_VERSION, and org.onosproject.routing.bgp.BgpSessionManager.getBgpSessions().
void org.onosproject.routing.bgp.BgpSessionManagerTest.testProcessedBgpUpdateMessages () throws InterruptedException
Tests that the BGP UPDATE messages have been received and processed.
Definition at line 521 of file BgpSessionManagerTest.java.
References org.onlab.packet.Ip4Prefix.valueOf().
The documentation for this class was generated from the following file:
apps/routing/src/test/java/org/onosproject/routing/bgp/BgpSessionManagerTest.java