onos: org.onosproject.mastership.MastershipTerm Class Reference
org.onosproject.mastership.MastershipTerm Class Reference
Public Member Functions
NodeId master ()
long termNumber ()
int hashCode ()
boolean equals (Object other)
String toString ()
Static Public Member Functions
static MastershipTerm of (NodeId master, long term)
Detailed Description
Definition at line 24 of file MastershipTerm.java.
Member Function Documentation
boolean org.onosproject.mastership.MastershipTerm.equals (Object other)
Definition at line 52 of file MastershipTerm.java.
int org.onosproject.mastership.MastershipTerm.hashCode ()
Definition at line 47 of file MastershipTerm.java.
References org.onosproject.mastership.MastershipTerm.master(), and org.onosproject.mastership.MastershipTerm.termNumber().
NodeId org.onosproject.mastership.MastershipTerm.master ()
Definition at line 38 of file MastershipTerm.java.
Referenced by org.onosproject.mastership.MastershipTerm.hashCode().
static MastershipTerm org.onosproject.mastership.MastershipTerm.of (NodeId master, long term) static
Definition at line 34 of file MastershipTerm.java.
Referenced by org.onosproject.store.trivial.SimpleMastershipStoreTest.getTermFor(), and org.onosproject.store.serializers.KryoSerializerTest.testMastershipTerm().
long org.onosproject.mastership.MastershipTerm.termNumber ()
Definition at line 42 of file MastershipTerm.java.
Referenced by org.onosproject.mastership.MastershipTerm.hashCode().
String org.onosproject.mastership.MastershipTerm.toString ()
Definition at line 65 of file MastershipTerm.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/mastership/MastershipTerm.java