onos: org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager Class Reference
org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager Class Reference
Provides implementation of the portPairGroupService.
Public Member Functions
void activate ()
void deactivate ()
boolean exists (PortPairGroupId portPairGroupId)
Returns if the port pair group is existed.
int getPortPairGroupCount ()
Returns the number of port pair groups known to the system.
Iterable< PortPairGroup > getPortPairGroups ()
Returns an iterable collection of the currently known port pair groups.
PortPairGroup getPortPairGroup (PortPairGroupId portPairGroupId)
Returns the portPairGroup with the given identifier.
boolean createPortPairGroup (PortPairGroup portPairGroup)
Creates a PortPairGroup in the store.
boolean updatePortPairGroup (PortPairGroup portPairGroup)
Updates the portPairGroup in the store.
boolean removePortPairGroup (PortPairGroupId portPairGroupId)
Deletes portPairGroup by given portPairGroupId.
Protected Attributes
StorageService storageService
Detailed Description
Provides implementation of the portPairGroupService.
Definition at line 45 of file PortPairGroupManager.java.
Member Function Documentation
void org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.activate ()
Definition at line 58 of file PortPairGroupManager.java.
References org.onosproject.store.serializers.KryoNamespaces.API.
boolean org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.createPortPairGroup (PortPairGroup portPairGroup)
Creates a PortPairGroup in the store.
Parameters
portPairGroup the port pair group to create
Returns
true if given port pair group is created successfully.
Implements org.onosproject.vtnrsc.portpairgroup.PortPairGroupService.
Definition at line 102 of file PortPairGroupManager.java.
References org.onosproject.vtnrsc.PortPairGroup.portPairGroupId().
Referenced by org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testCreatePortPairGroup().
void org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.deactivate ()
Definition at line 74 of file PortPairGroupManager.java.
boolean org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.exists (PortPairGroupId portPairGroupId)
Returns if the port pair group is existed.
Parameters
portPairGroupId port pair group identifier
Returns
true or false if one with the given identifier exists.
Implements org.onosproject.vtnrsc.portpairgroup.PortPairGroupService.
Definition at line 80 of file PortPairGroupManager.java.
Referenced by org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testExists().
PortPairGroup org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.getPortPairGroup (PortPairGroupId portPairGroupId)
Returns the portPairGroup with the given identifier.
Parameters
portPairGroupId port pair group identifier
Returns
PortPairGroup or null if port pair group with the given identifier is not known.
Implements org.onosproject.vtnrsc.portpairgroup.PortPairGroupService.
Definition at line 96 of file PortPairGroupManager.java.
Referenced by org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testGetPortPairGroup().
int org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.getPortPairGroupCount ()
Returns the number of port pair groups known to the system.
Returns
number of port pair groups.
Implements org.onosproject.vtnrsc.portpairgroup.PortPairGroupService.
Definition at line 86 of file PortPairGroupManager.java.
Referenced by org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testGetPortPairGroupCount().
Iterable<PortPairGroup> org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.getPortPairGroups ()
Returns an iterable collection of the currently known port pair groups.
Returns
collection of port pair groups.
Implements org.onosproject.vtnrsc.portpairgroup.PortPairGroupService.
Definition at line 91 of file PortPairGroupManager.java.
boolean org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.removePortPairGroup (PortPairGroupId portPairGroupId)
Deletes portPairGroup by given portPairGroupId.
Parameters
portPairGroupId id of port pair group to remove
Returns
true if the give port pair group is deleted successfully.
Implements org.onosproject.vtnrsc.portpairgroup.PortPairGroupService.
Definition at line 135 of file PortPairGroupManager.java.
Referenced by org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testRemovePortPairGroup().
boolean org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.updatePortPairGroup (PortPairGroup portPairGroup)
Updates the portPairGroup in the store.
Parameters
portPairGroup the port pair group to update
Returns
true if given port pair group is updated successfully.
Implements org.onosproject.vtnrsc.portpairgroup.PortPairGroupService.
Definition at line 115 of file PortPairGroupManager.java.
References org.onosproject.vtnrsc.PortPairGroup.portPairGroupId().
Referenced by org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testUpdatePortPairGroup().
Member Data Documentation
StorageService org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.storageService protected
Definition at line 55 of file PortPairGroupManager.java.
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/portpairgroup/impl/PortPairGroupManager.java