onos: org.onosproject.ui.topo.PropertyPanelTest Class Reference
org.onosproject.ui.topo.PropertyPanelTest Class Reference
Unit tests for PropertyPanel.
Public Member Functions
void basic ()
void changeTitle ()
void changeType ()
void setId ()
void props ()
void separator ()
void removeAllProps ()
void adjustProps ()
void intValues ()
void longValues ()
void objectValue ()
void buttons ()
Static Public Member Functions
static void setUpClass ()
Detailed Description
Unit tests for PropertyPanel.
Definition at line 37 of file PropertyPanelTest.java.
Member Function Documentation
void org.onosproject.ui.topo.PropertyPanelTest.adjustProps ()
Definition at line 184 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.props().
void org.onosproject.ui.topo.PropertyPanelTest.basic ()
Definition at line 100 of file PropertyPanelTest.java.
Referenced by org.onosproject.ui.topo.PropertyPanelTest.buttons(), org.onosproject.ui.topo.PropertyPanelTest.changeTitle(), org.onosproject.ui.topo.PropertyPanelTest.changeType(), org.onosproject.ui.topo.PropertyPanelTest.intValues(), org.onosproject.ui.topo.PropertyPanelTest.longValues(), org.onosproject.ui.topo.PropertyPanelTest.objectValue(), org.onosproject.ui.topo.PropertyPanelTest.props(), and org.onosproject.ui.topo.PropertyPanelTest.setId().
void org.onosproject.ui.topo.PropertyPanelTest.buttons ()
Definition at line 241 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.basic().
void org.onosproject.ui.topo.PropertyPanelTest.changeTitle ()
Definition at line 110 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.basic().
void org.onosproject.ui.topo.PropertyPanelTest.changeType ()
Definition at line 117 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.basic().
void org.onosproject.ui.topo.PropertyPanelTest.intValues ()
Definition at line 192 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.basic().
void org.onosproject.ui.topo.PropertyPanelTest.longValues ()
Definition at line 204 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.basic().
void org.onosproject.ui.topo.PropertyPanelTest.objectValue ()
Definition at line 218 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.basic().
void org.onosproject.ui.topo.PropertyPanelTest.props ()
Definition at line 156 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.basic().
Referenced by org.onosproject.ui.topo.PropertyPanelTest.adjustProps(), org.onosproject.ui.topo.PropertyPanelTest.removeAllProps(), and org.onosproject.ui.topo.PropertyPanelTest.separator().
void org.onosproject.ui.topo.PropertyPanelTest.removeAllProps ()
Definition at line 176 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.props().
void org.onosproject.ui.topo.PropertyPanelTest.separator ()
Definition at line 166 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.props().
void org.onosproject.ui.topo.PropertyPanelTest.setId ()
Definition at line 124 of file PropertyPanelTest.java.
References org.onosproject.ui.topo.PropertyPanelTest.basic().
static void org.onosproject.ui.topo.PropertyPanelTest.setUpClass () static
Definition at line 91 of file PropertyPanelTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/ui/topo/PropertyPanelTest.java