onos: org.onosproject.store.impl.MastershipBasedTimestamp Class Reference
org.onosproject.store.impl.MastershipBasedTimestamp Class Reference
A logical timestamp that derives its value from two things:
Public Member Functions
MastershipBasedTimestamp (long termNumber, long sequenceNumber)
Default version tuple.
int compareTo (Timestamp o)
int hashCode ()
boolean equals (Object obj)
String toString ()
long termNumber ()
Returns the termNumber.
long sequenceNumber ()
Returns the sequenceNumber number.
Public Member Functions inherited from org.onosproject.store.Timestamp
default boolean isNewerThan (Timestamp other)
Tests if this timestamp is newer than the specified timestamp.
default boolean isOlderThan (Timestamp other)
Tests if this timestamp is older than the specified timestamp.
Protected Member Functions
MastershipBasedTimestamp ()
Detailed Description
A logical timestamp that derives its value from two things:
The current mastership term of the device.
The value of the counter used for tracking topology events observed from the device during that current time of a device.
Definition at line 35 of file MastershipBasedTimestamp.java.
Constructor & Destructor Documentation
org.onosproject.store.impl.MastershipBasedTimestamp.MastershipBasedTimestamp (long termNumber, long sequenceNumber)
Default version tuple.
Parameters
termNumber the mastership termNumber
sequenceNumber the sequenceNumber number within the termNumber
Definition at line 46 of file MastershipBasedTimestamp.java.
References org.onosproject.store.impl.MastershipBasedTimestamp.sequenceNumber(), and org.onosproject.store.impl.MastershipBasedTimestamp.termNumber().
org.onosproject.store.impl.MastershipBasedTimestamp.MastershipBasedTimestamp () protected
Deprecated:
in Cardinal Release
Definition at line 113 of file MastershipBasedTimestamp.java.
Referenced by org.onosproject.store.impl.MastershipBasedTimestamp.compareTo(), and org.onosproject.store.impl.MastershipBasedTimestamp.equals().
Member Function Documentation
int org.onosproject.store.impl.MastershipBasedTimestamp.compareTo (Timestamp o)
Definition at line 52 of file MastershipBasedTimestamp.java.
References org.onosproject.store.impl.MastershipBasedTimestamp.MastershipBasedTimestamp(), and org.onosproject.store.impl.MastershipBasedTimestamp.termNumber().
boolean org.onosproject.store.impl.MastershipBasedTimestamp.equals (Object obj)
Implements org.onosproject.store.Timestamp.
Definition at line 69 of file MastershipBasedTimestamp.java.
References org.onosproject.store.impl.MastershipBasedTimestamp.MastershipBasedTimestamp().
int org.onosproject.store.impl.MastershipBasedTimestamp.hashCode ()
Implements org.onosproject.store.Timestamp.
Definition at line 64 of file MastershipBasedTimestamp.java.
References org.onosproject.store.impl.MastershipBasedTimestamp.sequenceNumber(), and org.onosproject.store.impl.MastershipBasedTimestamp.termNumber().
long org.onosproject.store.impl.MastershipBasedTimestamp.sequenceNumber ()
Returns the sequenceNumber number.
Returns
sequenceNumber
Definition at line 103 of file MastershipBasedTimestamp.java.
Referenced by org.onosproject.store.impl.MastershipBasedTimestamp.hashCode(), org.onosproject.store.impl.MastershipBasedTimestamp.MastershipBasedTimestamp(), and org.onosproject.store.impl.MastershipBasedTimestamp.toString().
long org.onosproject.store.impl.MastershipBasedTimestamp.termNumber ()
Returns the termNumber.
Returns
termNumber
Definition at line 94 of file MastershipBasedTimestamp.java.
Referenced by org.onosproject.store.impl.MastershipBasedTimestamp.compareTo(), org.onosproject.store.impl.MastershipBasedTimestamp.hashCode(), org.onosproject.store.impl.MastershipBasedTimestamp.MastershipBasedTimestamp(), and org.onosproject.store.impl.MastershipBasedTimestamp.toString().
String org.onosproject.store.impl.MastershipBasedTimestamp.toString ()
Definition at line 82 of file MastershipBasedTimestamp.java.
References org.onosproject.store.impl.MastershipBasedTimestamp.sequenceNumber(), and org.onosproject.store.impl.MastershipBasedTimestamp.termNumber().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/impl/MastershipBasedTimestamp.java