onos: org.onosproject.store.link.impl.GossipLinkStore Class Reference
org.onosproject.store.link.impl.GossipLinkStore Class Reference
Manages inventory of infrastructure links in distributed data store that uses optimistic replication and gossip based techniques.
Public Member Functions
void activate ()
void deactivate ()
int getLinkCount ()
Returns the number of links in the store.
Iterable< Link > getLinks ()
Returns an iterable collection of all links in the inventory.
Set< Link > getDeviceEgressLinks (DeviceId deviceId)
Returns all links egressing from the specified device.
Set< Link > getDeviceIngressLinks (DeviceId deviceId)
Returns all links ingressing from the specified device.
Link getLink (ConnectPoint src, ConnectPoint dst)
Returns the link between the two end-points.
Set< Link > getEgressLinks (ConnectPoint src)
Returns all links egressing from the specified connection point.
Set< Link > getIngressLinks (ConnectPoint dst)
Returns all links ingressing to the specified connection point.
LinkEvent createOrUpdateLink (ProviderId providerId, LinkDescription linkDescription)
Creates a new link, or updates an existing one, based on the given information.
LinkEvent removeOrDownLink (ConnectPoint src, ConnectPoint dst)
Removes the link, or marks it as inactive if the link is durable, based on the specified information.
LinkEvent removeLink (ConnectPoint src, ConnectPoint dst)
Removes the link based on the specified information.
Protected Attributes
DeviceClockService deviceClockService
ClusterCommunicationService clusterCommunicator
ClusterService clusterService
MastershipService mastershipService
Static Protected Attributes
static final KryoSerializer SERIALIZER
Detailed Description
Manages inventory of infrastructure links in distributed data store that uses optimistic replication and gossip based techniques.
Definition at line 103 of file GossipLinkStore.java.
Member Function Documentation
void org.onosproject.store.link.impl.GossipLinkStore.activate ()
Definition at line 158 of file GossipLinkStore.java.
References org.onosproject.store.link.impl.GossipLinkStoreMessageSubjects.LINK_ANTI_ENTROPY_ADVERTISEMENT, org.onosproject.store.link.impl.GossipLinkStoreMessageSubjects.LINK_INJECTED, org.onosproject.store.link.impl.GossipLinkStoreMessageSubjects.LINK_REMOVED, and org.onosproject.store.link.impl.GossipLinkStoreMessageSubjects.LINK_UPDATE.
LinkEvent org.onosproject.store.link.impl.GossipLinkStore.createOrUpdateLink (ProviderId providerId, LinkDescription linkDescription)
Creates a new link, or updates an existing one, based on the given information.
Parameters
providerId provider identity
linkDescription link description
Returns
create or update link event, or null if no change resulted
Implements org.onosproject.net.link.LinkStore.
Definition at line 293 of file GossipLinkStore.java.
References find-flow.deviceId, find-link-in-cluster.dstDeviceId, org.onosproject.cluster.NodeId.equals(), and org.onosproject.store.link.impl.GossipLinkStoreMessageSubjects.LINK_INJECTED.
void org.onosproject.store.link.impl.GossipLinkStore.deactivate ()
Definition at line 188 of file GossipLinkStore.java.
Set<Link> org.onosproject.store.link.impl.GossipLinkStore.getDeviceEgressLinks (DeviceId deviceId)
Returns all links egressing from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implements org.onosproject.net.link.LinkStore.
Definition at line 219 of file GossipLinkStore.java.
References find-flow.deviceId.
Set<Link> org.onosproject.store.link.impl.GossipLinkStore.getDeviceIngressLinks (DeviceId deviceId)
Returns all links ingressing from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implements org.onosproject.net.link.LinkStore.
Definition at line 230 of file GossipLinkStore.java.
References find-flow.deviceId.
Set<Link> org.onosproject.store.link.impl.GossipLinkStore.getEgressLinks (ConnectPoint src)
Returns all links egressing from the specified connection point.
Parameters
src source connection point
Returns
set of connection point links
Implements org.onosproject.net.link.LinkStore.
Definition at line 246 of file GossipLinkStore.java.
References org.onosproject.net.ConnectPoint.deviceId(), and create-intent.egress.
Set<Link> org.onosproject.store.link.impl.GossipLinkStore.getIngressLinks (ConnectPoint dst)
Returns all links ingressing to the specified connection point.
Parameters
dst destination connection point
Returns
set of connection point links
Implements org.onosproject.net.link.LinkStore.
Definition at line 275 of file GossipLinkStore.java.
References org.onosproject.net.ConnectPoint.deviceId(), and create-intent.ingress.
Link org.onosproject.store.link.impl.GossipLinkStore.getLink (ConnectPoint src, ConnectPoint dst)
Returns the link between the two end-points.
Parameters
src source connection point
dst destination connection point
Returns
link or null if one not found between the end-points
Implements org.onosproject.net.link.LinkStore.
Definition at line 241 of file GossipLinkStore.java.
Referenced by org.onosproject.store.link.impl.GossipLinkStore.removeOrDownLink().
int org.onosproject.store.link.impl.GossipLinkStore.getLinkCount ()
Returns the number of links in the store.
Returns
number of links
Implements org.onosproject.net.link.LinkStore.
Definition at line 209 of file GossipLinkStore.java.
Iterable<Link> org.onosproject.store.link.impl.GossipLinkStore.getLinks ()
Returns an iterable collection of all links in the inventory.
Returns
collection of all links
Implements org.onosproject.net.link.LinkStore.
Definition at line 214 of file GossipLinkStore.java.
LinkEvent org.onosproject.store.link.impl.GossipLinkStore.removeLink (ConnectPoint src, ConnectPoint dst)
Removes the link based on the specified information.
Parameters
src link source
dst link destination
Returns
remove link event, or null if no change resulted
Implements org.onosproject.net.link.LinkStore.
Definition at line 460 of file GossipLinkStore.java.
References find-link-in-cluster.dstDeviceId.
Referenced by org.onosproject.store.link.impl.GossipLinkStore.removeOrDownLink().
LinkEvent org.onosproject.store.link.impl.GossipLinkStore.removeOrDownLink (ConnectPoint src, ConnectPoint dst)
Removes the link, or marks it as inactive if the link is durable, based on the specified information.
Parameters
src link source
dst link destination
Returns
remove or update link event, or null if no change resulted
Implements org.onosproject.net.link.LinkStore.
Definition at line 348 of file GossipLinkStore.java.
References org.onosproject.net.Link.dst(), org.onosproject.store.link.impl.GossipLinkStore.getLink(), org.onosproject.net.Link.isDurable(), org.onosproject.net.Provided.providerId(), org.onosproject.store.link.impl.GossipLinkStore.removeLink(), and org.onosproject.net.Link.src().
Member Data Documentation
ClusterCommunicationService org.onosproject.store.link.impl.GossipLinkStore.clusterCommunicator protected
Definition at line 130 of file GossipLinkStore.java.
ClusterService org.onosproject.store.link.impl.GossipLinkStore.clusterService protected
Definition at line 133 of file GossipLinkStore.java.
DeviceClockService org.onosproject.store.link.impl.GossipLinkStore.deviceClockService protected
Definition at line 127 of file GossipLinkStore.java.
MastershipService org.onosproject.store.link.impl.GossipLinkStore.mastershipService protected
Definition at line 136 of file GossipLinkStore.java.
final KryoSerializer org.onosproject.store.link.impl.GossipLinkStore.SERIALIZER static protected
Initial value:
= new KryoSerializer() {
        @Override
        protected void setupKryoPool() {
            serializerPool = KryoNamespace.newBuilder()
                    .register(DistributedStoreSerializers.STORE_COMMON)
                    .nextId(DistributedStoreSerializers.STORE_CUSTOM_BEGIN)
                    .register(InternalLinkEvent.class)
                    .register(InternalLinkRemovedEvent.class)
                    .register(LinkAntiEntropyAdvertisement.class)
                    .register(LinkFragmentId.class)
                    .register(LinkInjectedEvent.class)
                    .build();
        }
    }
Definition at line 138 of file GossipLinkStore.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/link/impl/GossipLinkStore.java