onos: org.onosproject.cordvtn.DestinationInfo Class Reference
org.onosproject.cordvtn.DestinationInfo Class Reference
Contains destination information.
Classes
class Builder
DestinationInfo builder class.
Public Member Functions
DestinationInfo (Port output, List< IpAddress > ip, MacAddress mac, IpAddress remoteIp, long tunnelId)
Creates a new destination information.
Port output ()
Returns output port.
List< IpAddress > ip ()
Returns destination ip addresses.
MacAddress mac ()
Returns destination mac address.
IpAddress remoteIp ()
Returns tunnel remote ip address.
long tunnelId ()
Returns tunnel id.
Static Public Member Functions
static DestinationInfo.Builder builder (Port output)
Returns a new destination info builder.
Detailed Description
Contains destination information.
Definition at line 29 of file DestinationInfo.java.
Constructor & Destructor Documentation
org.onosproject.cordvtn.DestinationInfo.DestinationInfo (Port output, List< IpAddress > ip, MacAddress mac, IpAddress remoteIp, long tunnelId)
Creates a new destination information.
Parameters
output output port
ip destination ip address
mac destination mac address
remoteIp tunnel remote ip address
tunnelId segment id
Definition at line 46 of file DestinationInfo.java.
References org.onosproject.cordvtn.DestinationInfo.ip(), org.onosproject.cordvtn.DestinationInfo.mac(), org.onosproject.cordvtn.DestinationInfo.remoteIp(), and org.onosproject.cordvtn.DestinationInfo.tunnelId().
Member Function Documentation
static DestinationInfo.Builder org.onosproject.cordvtn.DestinationInfo.builder (Port output) static
Returns a new destination info builder.
Returns
destination info builder
Definition at line 105 of file DestinationInfo.java.
List<IpAddress> org.onosproject.cordvtn.DestinationInfo.ip ()
Returns destination ip addresses.
Returns
list of ip address
Definition at line 69 of file DestinationInfo.java.
Referenced by org.onosproject.cordvtn.DestinationInfo.DestinationInfo(), onos.ONOS.start(), and onos.ONOS.updateHazelcast().
MacAddress org.onosproject.cordvtn.DestinationInfo.mac ()
Returns destination mac address.
Returns
mac address
Definition at line 78 of file DestinationInfo.java.
Referenced by org.onosproject.cordvtn.DestinationInfo.DestinationInfo().
Port org.onosproject.cordvtn.DestinationInfo.output ()
Returns output port.
Returns
port
Definition at line 60 of file DestinationInfo.java.
IpAddress org.onosproject.cordvtn.DestinationInfo.remoteIp ()
Returns tunnel remote ip address.
Returns
ip address
Definition at line 87 of file DestinationInfo.java.
Referenced by org.onosproject.cordvtn.DestinationInfo.DestinationInfo().
long org.onosproject.cordvtn.DestinationInfo.tunnelId ()
Returns tunnel id.
Returns
tunnel id
Definition at line 96 of file DestinationInfo.java.
Referenced by org.onosproject.cordvtn.DestinationInfo.DestinationInfo().
The documentation for this class was generated from the following file:
apps/cordvtn/src/main/java/org/onosproject/cordvtn/DestinationInfo.java