onos: org.onlab.packet.Ethernet Class Reference
org.onlab.packet.Ethernet Class Reference
Public Member Functions
Ethernet ()
By default, set Ethernet to untagged.
byte[] getDestinationMACAddress ()
Gets the destination MAC address.
MacAddress getDestinationMAC ()
Gets the destination MAC address.
Ethernet setDestinationMACAddress (final MacAddress destMac)
Sets the destination MAC address.
Ethernet setDestinationMACAddress (final byte[] destMac)
Sets the destination MAC address.
Ethernet setDestinationMACAddress (final String destMac)
Sets the destination MAC address.
byte[] getSourceMACAddress ()
Gets the source MAC address.
MacAddress getSourceMAC ()
Gets the source MAC address.
Ethernet setSourceMACAddress (final MacAddress sourceMac)
Sets the source MAC address.
Ethernet setSourceMACAddress (final byte[] sourceMac)
Sets the source MAC address.
Ethernet setSourceMACAddress (final String sourceMac)
Sets the source MAC address.
byte getPriorityCode ()
Gets the priority code.
Ethernet setPriorityCode (final byte priority)
Sets the priority code.
short getVlanID ()
Gets the VLAN ID.
Ethernet setVlanID (final short vlan)
Sets the VLAN ID.
short getEtherType ()
Gets the Ethernet type.
Ethernet setEtherType (final short ethType)
Sets the Ethernet type.
boolean isBroadcast ()
boolean isMulticast ()
boolean isPad ()
Pad this packet to 60 bytes minimum, filling with zeros?
Ethernet setPad (final boolean pd)
Pad this packet to 60 bytes minimum, filling with zeros?
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (final byte[] data, final int offset, final int length)
int hashCode ()
boolean equals (final Object obj)
String toString ()
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
Static Public Member Functions
static boolean isMACAddress (final String macAddress)
Checks to see if a string is a valid MAC address.
static byte[] toMACAddress (final String macAddress)
Accepts a MAC address of the form 00:aa:11:bb:22:cc, case does not matter, and returns a corresponding byte[].
static long toLong (final byte[] macAddress)
Accepts a MAC address and returns the corresponding long, where the MAC bytes are set on the lower order bytes of the long.
static byte[] toByteArray (final long macAddress)
Converts a long MAC address to a byte array.
static String bytesToHex (byte[] in)
static Deserializer< Ethernet > deserializer ()
Deserializer function for Ethernet packets.
Static Public Attributes
static final short TYPE_ARP = EthType.EtherType.ARP.ethType().toShort()
static final short TYPE_RARP = EthType.EtherType.RARP.ethType().toShort()
static final short TYPE_IPV4 = EthType.EtherType.IPV4.ethType().toShort()
static final short TYPE_IPV6 = EthType.EtherType.IPV6.ethType().toShort()
static final short TYPE_LLDP = EthType.EtherType.LLDP.ethType().toShort()
static final short TYPE_VLAN = EthType.EtherType.VLAN.ethType().toShort()
static final short TYPE_BSN = EthType.EtherType.BDDP.ethType().toShort()
static final short MPLS_UNICAST = EthType.EtherType.MPLS_UNICAST.ethType().toShort()
static final short MPLS_MULTICAST = EthType.EtherType.MPLS_MULTICAST.ethType().toShort()
static final short VLAN_UNTAGGED = (short) 0xffff
static final short ETHERNET_HEADER_LENGTH = 14
static final short VLAN_HEADER_LENGTH = 4
static final short DATALAYER_ADDRESS_LENGTH = 6
Protected Attributes
MacAddress destinationMACAddress
MacAddress sourceMACAddress
byte priorityCode
short vlanID
short etherType
boolean pad = false
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Definition at line 39 of file Ethernet.java.
Constructor & Destructor Documentation
org.onlab.packet.Ethernet.Ethernet ()
By default, set Ethernet to untagged.
Definition at line 82 of file Ethernet.java.
References org.onlab.packet.Ethernet.VLAN_UNTAGGED.
Referenced by org.onlab.packet.Ethernet.deserializer(), and org.onlab.packet.Ethernet.equals().
Member Function Documentation
static String org.onlab.packet.Ethernet.bytesToHex (byte[] in) static
Definition at line 661 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.toString().
IPacket org.onlab.packet.Ethernet.deserialize (final byte[] data, final int offset, final int length)
Definition at line 316 of file Ethernet.java.
References org.onlab.packet.Ethernet.deserializer(), org.onlab.packet.Ethernet.destinationMACAddress, find-link-in-cluster.length, org.onlab.packet.MacAddress.MAC_ADDRESS_LENGTH, org.onlab.packet.BasePacket.payload, org.onlab.packet.Ethernet.sourceMACAddress, org.onlab.packet.Ethernet.TYPE_VLAN, and org.onlab.packet.Ethernet.VLAN_UNTAGGED.
static Deserializer<Ethernet> org.onlab.packet.Ethernet.deserializer () static
Deserializer function for Ethernet packets.
Returns
deserializer function
Definition at line 674 of file Ethernet.java.
References org.onlab.packet.Ethernet.DATALAYER_ADDRESS_LENGTH, org.onlab.packet.Ethernet.Ethernet(), org.onlab.packet.Ethernet.ETHERNET_HEADER_LENGTH, find-link-in-cluster.length, org.onlab.packet.BasePacket.payload, org.onlab.packet.Ethernet.TYPE_VLAN, org.onlab.packet.Ethernet.VLAN_HEADER_LENGTH, and org.onlab.packet.Ethernet.VLAN_UNTAGGED.
Referenced by org.onlab.packet.Ethernet.deserialize().
boolean org.onlab.packet.Ethernet.equals (final Object obj)
Definition at line 442 of file Ethernet.java.
References org.onlab.packet.Ethernet.destinationMACAddress, org.onlab.packet.MacAddress.equals(), org.onlab.packet.Ethernet.Ethernet(), org.onlab.packet.Ethernet.etherType, org.onlab.packet.Ethernet.pad, org.onlab.packet.Ethernet.priorityCode, org.onlab.packet.Ethernet.sourceMACAddress, and org.onlab.packet.Ethernet.vlanID.
MacAddress org.onlab.packet.Ethernet.getDestinationMAC ()
Gets the destination MAC address.
Returns
the destination MAC
Definition at line 101 of file Ethernet.java.
Referenced by org.onosproject.codec.impl.EthernetCodec.encode(), org.onosproject.net.proxyarp.impl.ProxyArpManager.forward(), org.onosproject.codec.impl.EthernetJsonMatcher.matchesSafely(), org.onlab.packet.EthernetTest.testDeserializeNoVlan(), and org.onlab.packet.EthernetTest.testDeserializeWithVlan().
byte [] org.onlab.packet.Ethernet.getDestinationMACAddress ()
Gets the destination MAC address.
Returns
the destination MAC as a byte array
Definition at line 92 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.toString().
short org.onlab.packet.Ethernet.getEtherType ()
Gets the Ethernet type.
Returns
the etherType
Definition at line 234 of file Ethernet.java.
Referenced by org.onlab.packet.ONOSLLDP.parseONOSLLDP(), org.onosproject.pim.impl.PIMPacketHandler.PIMPacketProcessor.process(), org.onlab.packet.EthernetTest.testDeserializeNoVlan(), and org.onlab.packet.EthernetTest.testDeserializeWithVlan().
byte org.onlab.packet.Ethernet.getPriorityCode ()
Gets the priority code.
Returns
the priorityCode
Definition at line 194 of file Ethernet.java.
MacAddress org.onlab.packet.Ethernet.getSourceMAC ()
Gets the source MAC address.
Returns
the source MACAddress
Definition at line 152 of file Ethernet.java.
Referenced by org.onosproject.codec.impl.EthernetCodec.encode(), org.onosproject.net.proxyarp.impl.ProxyArpManager.forward(), org.onosproject.codec.impl.EthernetJsonMatcher.matchesSafely(), org.onlab.packet.EthernetTest.testDeserializeNoVlan(), and org.onlab.packet.EthernetTest.testDeserializeWithVlan().
byte [] org.onlab.packet.Ethernet.getSourceMACAddress ()
Gets the source MAC address.
Returns
the source MACAddress as a byte array
Definition at line 143 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.toString().
short org.onlab.packet.Ethernet.getVlanID ()
Gets the VLAN ID.
Returns
the vlanID
Definition at line 214 of file Ethernet.java.
Referenced by org.onosproject.net.proxyarp.impl.ProxyArpManager.forward(), org.onlab.packet.EthernetTest.testDeserializeNoVlan(), org.onlab.packet.EthernetTest.testDeserializeWithVlan(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExist(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExistWithVlan(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExist(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExistWithVlan(), and org.onlab.packet.Ethernet.toString().
int org.onlab.packet.Ethernet.hashCode ()
Definition at line 424 of file Ethernet.java.
boolean org.onlab.packet.Ethernet.isBroadcast ()
Returns
True if the Ethernet frame is broadcast, false otherwise
Definition at line 252 of file Ethernet.java.
static boolean org.onlab.packet.Ethernet.isMACAddress (final String macAddress) static
Checks to see if a string is a valid MAC address.
Parameters
macAddress string to test if it is a valid MAC
Returns
True if macAddress is a valid MAC, False otherwise
Definition at line 370 of file Ethernet.java.
boolean org.onlab.packet.Ethernet.isMulticast ()
Returns
True is the Ethernet frame is multicast, False otherwise
Definition at line 260 of file Ethernet.java.
boolean org.onlab.packet.Ethernet.isPad ()
Pad this packet to 60 bytes minimum, filling with zeros?
Returns
the pad
Definition at line 269 of file Ethernet.java.
byte [] org.onlab.packet.Ethernet.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 286 of file Ethernet.java.
References find-link-in-cluster.length, org.onlab.packet.Ethernet.pad, org.onlab.packet.BasePacket.payload, org.onlab.packet.Ethernet.priorityCode, org.onlab.packet.Ethernet.TYPE_VLAN, org.onlab.packet.Ethernet.VLAN_UNTAGGED, and org.onlab.packet.Ethernet.vlanID.
Referenced by org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.build(), org.onosproject.net.proxyarp.impl.ProxyArpManager.forward(), and org.onosproject.segmentrouting.IpHandler.forwardPackets().
Ethernet org.onlab.packet.Ethernet.setDestinationMACAddress (final MacAddress destMac)
Sets the destination MAC address.
Parameters
destMac the destination MAC to set
Returns
the Ethernet frame
Definition at line 111 of file Ethernet.java.
Ethernet org.onlab.packet.Ethernet.setDestinationMACAddress (final byte[] destMac)
Sets the destination MAC address.
Parameters
destMac the destination MAC to set
Returns
the Ethernet frame
Definition at line 122 of file Ethernet.java.
Ethernet org.onlab.packet.Ethernet.setDestinationMACAddress (final String destMac)
Sets the destination MAC address.
Parameters
destMac the destination MAC to set
Returns
the Ethernet frame
Definition at line 133 of file Ethernet.java.
Ethernet org.onlab.packet.Ethernet.setEtherType (final short ethType)
Sets the Ethernet type.
Parameters
ethType the etherType to set
Returns
the Ethernet frame
Definition at line 244 of file Ethernet.java.
Ethernet org.onlab.packet.Ethernet.setPad (final boolean pd)
Pad this packet to 60 bytes minimum, filling with zeros?
Parameters
pd the pad to set
Returns
this
Definition at line 280 of file Ethernet.java.
Ethernet org.onlab.packet.Ethernet.setPriorityCode (final byte priority)
Sets the priority code.
Parameters
priority the priorityCode to set
Returns
the Ethernet frame
Definition at line 204 of file Ethernet.java.
Ethernet org.onlab.packet.Ethernet.setSourceMACAddress (final MacAddress sourceMac)
Sets the source MAC address.
Parameters
sourceMac the source MAC to set
Returns
the Ethernet frame
Definition at line 162 of file Ethernet.java.
Ethernet org.onlab.packet.Ethernet.setSourceMACAddress (final byte[] sourceMac)
Sets the source MAC address.
Parameters
sourceMac the source MAC to set
Returns
the Ethernet frame
Definition at line 173 of file Ethernet.java.
Ethernet org.onlab.packet.Ethernet.setSourceMACAddress (final String sourceMac)
Sets the source MAC address.
Parameters
sourceMac the source MAC to set
Returns
the Ethernet frame
Definition at line 184 of file Ethernet.java.
Ethernet org.onlab.packet.Ethernet.setVlanID (final short vlan)
Sets the VLAN ID.
Parameters
vlan the vlanID to set
Returns
the Ethernet frame
Definition at line 224 of file Ethernet.java.
static byte [] org.onlab.packet.Ethernet.toByteArray (final long macAddress) static
Converts a long MAC address to a byte array.
Parameters
macAddress MAC address set on the lower order bytes of the long
Returns
the bytes of the mac address
Definition at line 414 of file Ethernet.java.
static long org.onlab.packet.Ethernet.toLong (final byte[] macAddress) static
Accepts a MAC address and returns the corresponding long, where the MAC bytes are set on the lower order bytes of the long.
Parameters
macAddress MAC address as a byte array
Returns
a long containing the mac address bytes
Definition at line 404 of file Ethernet.java.
static byte [] org.onlab.packet.Ethernet.toMACAddress (final String macAddress) static
Accepts a MAC address of the form 00:aa:11:bb:22:cc, case does not matter, and returns a corresponding byte[].
Parameters
macAddress The MAC address to convert into a byte array
Returns
The macAddress as a byte array
Definition at line 393 of file Ethernet.java.
String org.onlab.packet.Ethernet.toString ()
Definition at line 480 of file Ethernet.java.
References org.onlab.packet.Ethernet.bytesToHex(), org.onlab.packet.Ethernet.getDestinationMACAddress(), org.onlab.packet.Ethernet.getSourceMACAddress(), org.onlab.packet.Ethernet.getVlanID(), org.onlab.packet.BasePacket.payload, and org.onlab.packet.Ethernet.VLAN_UNTAGGED.
Member Data Documentation
final short org.onlab.packet.Ethernet.DATALAYER_ADDRESS_LENGTH = 6 static
Definition at line 59 of file Ethernet.java.
Referenced by org.onlab.packet.ARP.buildArpReply(), org.onlab.packet.Ethernet.deserializer(), and org.onosproject.segmentrouting.ArpHandler.sendArpRequest().
MacAddress org.onlab.packet.Ethernet.destinationMACAddress protected
Definition at line 72 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.deserialize(), and org.onlab.packet.Ethernet.equals().
final short org.onlab.packet.Ethernet.ETHERNET_HEADER_LENGTH = 14 static
Definition at line 56 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.deserializer(), and org.onlab.packet.EthernetTest.setUp().
short org.onlab.packet.Ethernet.etherType protected
Definition at line 76 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.equals().
final short org.onlab.packet.Ethernet.MPLS_MULTICAST = EthType.EtherType.MPLS_MULTICAST.ethType().toShort() static
Definition at line 51 of file Ethernet.java.
final short org.onlab.packet.Ethernet.MPLS_UNICAST = EthType.EtherType.MPLS_UNICAST.ethType().toShort() static
Definition at line 50 of file Ethernet.java.
Referenced by org.onosproject.codec.impl.FlowRuleCodecTest.decodeInstructionsFlowTest(), org.onosproject.segmentrouting.RoutingRulePopulator.populateMplsRule(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
boolean org.onlab.packet.Ethernet.pad = false protected
Definition at line 77 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.equals(), and org.onlab.packet.Ethernet.serialize().
byte org.onlab.packet.Ethernet.priorityCode protected
Definition at line 74 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.equals(), and org.onlab.packet.Ethernet.serialize().
MacAddress org.onlab.packet.Ethernet.sourceMACAddress protected
Definition at line 73 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.deserialize(), and org.onlab.packet.Ethernet.equals().
final short org.onlab.packet.Ethernet.TYPE_ARP = EthType.EtherType.ARP.ethType().toShort() static
Definition at line 42 of file Ethernet.java.
Referenced by org.onlab.packet.ARP.buildArpReply(), org.onosproject.provider.of.packet.impl.OpenFlowPacketProviderTest.emit(), org.onosproject.codec.impl.EthernetCodecTest.ethernetCodecTest(), org.onosproject.openstackswitching.OpenstackArpHandler.processPacketIn(), and org.onosproject.segmentrouting.ArpHandler.sendArpRequest().
final short org.onlab.packet.Ethernet.TYPE_BSN = EthType.EtherType.BDDP.ethType().toShort() static
Definition at line 48 of file Ethernet.java.
Referenced by org.onlab.packet.ONOSLLDP.parseONOSLLDP().
final short org.onlab.packet.Ethernet.TYPE_IPV4 = EthType.EtherType.IPV4.ethType().toShort() static
Definition at line 44 of file Ethernet.java.
Referenced by org.onosproject.igmp.impl.IGMPComponent.activate(), org.onosproject.mfwd.impl.McastForwarding.activate(), org.onosproject.segmentrouting.IpHandler.forwardPackets(), org.onosproject.pim.impl.PIMPacketHandler.initialize(), org.onosproject.bgprouter.TunnellingConnectivityManager.notifySwitchAvailable(), org.onosproject.segmentrouting.RoutingRulePopulator.populateIpRuleForRouter(), org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterIpPunts(), org.onosproject.pim.impl.PIMPacketHandler.PIMPacketProcessor.process(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific(), org.onosproject.vtn.table.impl.ClassifierServiceImpl.programL3ExPortClassifierRules(), org.onosproject.vtn.table.impl.DnatServiceImpl.programRules(), org.onosproject.vtn.table.impl.SnatServiceImpl.programRules(), org.onosproject.pim.impl.PIMPacketHandler.sendPacket(), org.onosproject.mfwd.impl.McastIntentManager.setIntent(), org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityHostToInternet(), org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityInternetToHost(), org.onosproject.sdnip.SdnIpFibTest.testFibAdd(), org.onosproject.sdnip.SdnIpFibTest.testFibAddWithVlan(), org.onosproject.sdnip.SdnIpFibTest.testFibDelete(), and org.onosproject.sdnip.SdnIpFibTest.testFibUpdate().
final short org.onlab.packet.Ethernet.TYPE_IPV6 = EthType.EtherType.IPV6.ethType().toShort() static
Definition at line 45 of file Ethernet.java.
Referenced by org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityHostToInternet(), and org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityInternetToHost().
final short org.onlab.packet.Ethernet.TYPE_LLDP = EthType.EtherType.LLDP.ethType().toShort() static
Definition at line 46 of file Ethernet.java.
Referenced by org.onlab.packet.LLDP.LLDP().
final short org.onlab.packet.Ethernet.TYPE_RARP = EthType.EtherType.RARP.ethType().toShort() static
Definition at line 43 of file Ethernet.java.
final short org.onlab.packet.Ethernet.TYPE_VLAN = EthType.EtherType.VLAN.ethType().toShort() static
Definition at line 47 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.deserialize(), org.onlab.packet.Ethernet.deserializer(), org.onosproject.driver.pipeline.CorsaPipeline.processVlanMplsTable(), org.onlab.packet.Ethernet.serialize(), and org.onlab.packet.EthernetTest.setUp().
final short org.onlab.packet.Ethernet.VLAN_HEADER_LENGTH = 4 static
Definition at line 57 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.deserializer(), and org.onlab.packet.EthernetTest.setUp().
final short org.onlab.packet.Ethernet.VLAN_UNTAGGED = (short) 0xffff static
Definition at line 54 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.deserialize(), org.onlab.packet.Ethernet.deserializer(), org.onlab.packet.Ethernet.Ethernet(), org.onlab.packet.Ethernet.serialize(), org.onlab.packet.EthernetTest.testDeserializeNoVlan(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExist(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExist(), and org.onlab.packet.Ethernet.toString().
short org.onlab.packet.Ethernet.vlanID protected
Definition at line 75 of file Ethernet.java.
Referenced by org.onlab.packet.Ethernet.equals(), and org.onlab.packet.Ethernet.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/Ethernet.java