onos: org.onosproject.net.flow.CompletedBatchOperation Class Reference
org.onosproject.net.flow.CompletedBatchOperation Class Reference
Representation of a completed flow rule batch operation.
Public Member Functions
CompletedBatchOperation (boolean success, Set<?extends FlowRule > failures, Set< Long > failedIds, DeviceId deviceId)
Creates a new batch completion result.
CompletedBatchOperation (boolean success, Set<?extends FlowRule > failures, DeviceId deviceId)
Creates a new batch completion result.
boolean isSuccess ()
Set< FlowRule > failedItems ()
Set< Long > failedIds ()
DeviceId deviceId ()
String toString ()
Detailed Description
Representation of a completed flow rule batch operation.
Definition at line 29 of file CompletedBatchOperation.java.
Constructor & Destructor Documentation
org.onosproject.net.flow.CompletedBatchOperation.CompletedBatchOperation (boolean success, Set<?extends FlowRule > failures, Set< Long > failedIds, DeviceId deviceId)
Creates a new batch completion result.
Parameters
success indicates whether the completion is successful
failures set of any failures encountered
failedIds (optional) set of failed operation ids
deviceId the device this operation completed for
Definition at line 44 of file CompletedBatchOperation.java.
References org.onosproject.net.flow.CompletedBatchOperation.deviceId(), and org.onosproject.net.flow.CompletedBatchOperation.failedIds().
org.onosproject.net.flow.CompletedBatchOperation.CompletedBatchOperation (boolean success, Set<?extends FlowRule > failures, DeviceId deviceId)
Creates a new batch completion result.
Parameters
success indicates whether the completion is successful.
failures set of any failures encountered
deviceId the device this operation completed for
Definition at line 59 of file CompletedBatchOperation.java.
References org.onosproject.net.flow.CompletedBatchOperation.deviceId().
Member Function Documentation
DeviceId org.onosproject.net.flow.CompletedBatchOperation.deviceId ()
Definition at line 83 of file CompletedBatchOperation.java.
References find-flow.deviceId.
Referenced by org.onosproject.net.flow.CompletedBatchOperation.CompletedBatchOperation(), and org.onosproject.net.flow.CompletedBatchOperation.toString().
Set<Long> org.onosproject.net.flow.CompletedBatchOperation.failedIds ()
Definition at line 79 of file CompletedBatchOperation.java.
Referenced by org.onosproject.net.flow.CompletedBatchOperation.CompletedBatchOperation(), and org.onosproject.net.flow.CompletedBatchOperation.toString().
Set<FlowRule> org.onosproject.net.flow.CompletedBatchOperation.failedItems ()
Definition at line 75 of file CompletedBatchOperation.java.
boolean org.onosproject.net.flow.CompletedBatchOperation.isSuccess ()
Definition at line 70 of file CompletedBatchOperation.java.
String org.onosproject.net.flow.CompletedBatchOperation.toString ()
Definition at line 88 of file CompletedBatchOperation.java.
References org.onosproject.net.flow.CompletedBatchOperation.deviceId(), and org.onosproject.net.flow.CompletedBatchOperation.failedIds().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/CompletedBatchOperation.java