onos: org.onosproject.net.device.impl.DeviceManagerTest Class Reference
org.onosproject.net.device.impl.DeviceManagerTest Class Reference
Test codifying the device service & device provider service contracts.
Public Member Functions
void setUp ()
void tearDown ()
void deviceConnected ()
void deviceDisconnected ()
void deviceUpdated ()
void getRole ()
void updatePorts ()
void updatePortStatus ()
void getPorts ()
void removeDevice ()
Protected Member Functions
void validateEvents (Enum...types)
Protected Attributes
DeviceService service
DeviceAdminService admin
DeviceProviderRegistry registry
DeviceProviderService providerService
TestProvider provider
TestListener listener = new TestListener()
Detailed Description
Test codifying the device service & device provider service contracts.
Definition at line 69 of file DeviceManagerTest.java.
Member Function Documentation
void org.onosproject.net.device.impl.DeviceManagerTest.deviceConnected ()
Definition at line 138 of file DeviceManagerTest.java.
References org.onosproject.net.device.DeviceService.getDevice(), org.onosproject.net.device.DeviceService.getDeviceCount(), org.onosproject.net.device.DeviceService.isAvailable(), org.onosproject.net.device.impl.DeviceManagerTest.service, and org.onosproject.net.device.impl.DeviceManagerTest.validateEvents().
void org.onosproject.net.device.impl.DeviceManagerTest.deviceDisconnected ()
Definition at line 151 of file DeviceManagerTest.java.
References org.onosproject.net.device.DeviceService.getDevice(), org.onosproject.net.device.DeviceService.getDeviceCount(), org.onosproject.net.device.DeviceService.isAvailable(), org.onosproject.net.device.impl.DeviceManagerTest.service, and org.onosproject.net.device.impl.DeviceManagerTest.validateEvents().
void org.onosproject.net.device.impl.DeviceManagerTest.deviceUpdated ()
Definition at line 171 of file DeviceManagerTest.java.
References org.onosproject.net.device.impl.DeviceManagerTest.validateEvents().
void org.onosproject.net.device.impl.DeviceManagerTest.getPorts ()
Definition at line 218 of file DeviceManagerTest.java.
References org.onosproject.net.device.DeviceService.getPort(), org.onosproject.net.device.DeviceService.getPorts(), obeliskHostCheck.port, org.onosproject.net.device.impl.DeviceManagerTest.service, and org.onosproject.net.device.impl.DeviceManagerTest.validateEvents().
void org.onosproject.net.device.impl.DeviceManagerTest.getRole ()
Definition at line 180 of file DeviceManagerTest.java.
References org.onosproject.net.device.DeviceService.getRole(), org.onosproject.net.MastershipRole.MASTER, and org.onosproject.net.device.impl.DeviceManagerTest.service.
void org.onosproject.net.device.impl.DeviceManagerTest.removeDevice ()
Definition at line 233 of file DeviceManagerTest.java.
References org.onosproject.net.device.DeviceService.getDevice(), org.onosproject.net.device.DeviceService.getDeviceCount(), and org.onosproject.net.device.impl.DeviceManagerTest.service.
void org.onosproject.net.device.impl.DeviceManagerTest.setUp ()
Definition at line 97 of file DeviceManagerTest.java.
References org.onosproject.net.device.impl.DeviceManagerTest.admin, org.onosproject.net.device.impl.DeviceManagerTest.listener, org.onosproject.net.device.impl.DeviceManagerTest.provider, org.onosproject.net.device.impl.DeviceManagerTest.providerService, org.onosproject.net.device.impl.DeviceManagerTest.registry, and org.onosproject.net.device.impl.DeviceManagerTest.service.
void org.onosproject.net.device.impl.DeviceManagerTest.tearDown ()
Definition at line 121 of file DeviceManagerTest.java.
References org.onosproject.net.device.impl.DeviceManagerTest.listener, org.onosproject.net.device.impl.DeviceManagerTest.provider, and org.onosproject.net.device.impl.DeviceManagerTest.registry.
void org.onosproject.net.device.impl.DeviceManagerTest.updatePorts ()
Definition at line 186 of file DeviceManagerTest.java.
References org.onosproject.net.device.impl.DeviceManagerTest.validateEvents().
void org.onosproject.net.device.impl.DeviceManagerTest.updatePortStatus ()
Definition at line 203 of file DeviceManagerTest.java.
References org.onosproject.net.device.impl.DeviceManagerTest.listener, and org.onosproject.net.device.impl.DeviceManagerTest.validateEvents().
void org.onosproject.net.device.impl.DeviceManagerTest.validateEvents (Enum... types) protected
Definition at line 244 of file DeviceManagerTest.java.
References org.onosproject.net.device.impl.DeviceManagerTest.listener.
Referenced by org.onosproject.net.device.impl.DeviceManagerTest.deviceConnected(), org.onosproject.net.device.impl.DeviceManagerTest.deviceDisconnected(), org.onosproject.net.device.impl.DeviceManagerTest.deviceUpdated(), org.onosproject.net.device.impl.DeviceManagerTest.getPorts(), org.onosproject.net.device.impl.DeviceManagerTest.updatePorts(), and org.onosproject.net.device.impl.DeviceManagerTest.updatePortStatus().
Member Data Documentation
DeviceAdminService org.onosproject.net.device.impl.DeviceManagerTest.admin protected
Definition at line 90 of file DeviceManagerTest.java.
Referenced by org.onosproject.net.device.impl.DeviceManagerTest.setUp().
TestListener org.onosproject.net.device.impl.DeviceManagerTest.listener = new TestListener() protected
Definition at line 94 of file DeviceManagerTest.java.
Referenced by org.onosproject.net.device.impl.DeviceManagerTest.setUp(), org.onosproject.net.device.impl.DeviceManagerTest.tearDown(), org.onosproject.net.device.impl.DeviceManagerTest.updatePortStatus(), and org.onosproject.net.device.impl.DeviceManagerTest.validateEvents().
TestProvider org.onosproject.net.device.impl.DeviceManagerTest.provider protected
Definition at line 93 of file DeviceManagerTest.java.
Referenced by org.onosproject.net.device.impl.DeviceManagerTest.setUp(), and org.onosproject.net.device.impl.DeviceManagerTest.tearDown().
DeviceProviderService org.onosproject.net.device.impl.DeviceManagerTest.providerService protected
Definition at line 92 of file DeviceManagerTest.java.
Referenced by org.onosproject.net.device.impl.DeviceManagerTest.setUp().
DeviceProviderRegistry org.onosproject.net.device.impl.DeviceManagerTest.registry protected
Definition at line 91 of file DeviceManagerTest.java.
Referenced by org.onosproject.net.device.impl.DeviceManagerTest.setUp(), and org.onosproject.net.device.impl.DeviceManagerTest.tearDown().
DeviceService org.onosproject.net.device.impl.DeviceManagerTest.service protected
Definition at line 89 of file DeviceManagerTest.java.
Referenced by org.onosproject.net.device.impl.DeviceManagerTest.deviceConnected(), org.onosproject.net.device.impl.DeviceManagerTest.deviceDisconnected(), org.onosproject.net.device.impl.DeviceManagerTest.getPorts(), org.onosproject.net.device.impl.DeviceManagerTest.getRole(), org.onosproject.net.device.impl.DeviceManagerTest.removeDevice(), and org.onosproject.net.device.impl.DeviceManagerTest.setUp().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/device/impl/DeviceManagerTest.java