onos: org.onosproject.store.consistent.impl.DatabaseManager Class Reference
org.onosproject.store.consistent.impl.DatabaseManager Class Reference
Database manager.
Public Member Functions
void activate ()
void deactivate ()
TransactionContextBuilder transactionContextBuilder ()
Creates a new transaction context builder.
List< PartitionInfo > getPartitionInfo ()
Returns information about all partitions in the system.
AtomicCounterBuilder atomicCounterBuilder ()
Creates a new AtomicCounterBuilder.
List< MapInfo > getMapInfo ()
Returns information about all the consistent maps in the system.
Map< String, Long > getCounters ()
Returns information about all the atomic counters in the system.
Map< String, Long > getPartitionedDatabaseCounters ()
Returns information about all the atomic partitioned database counters in the system.
Map< String, Long > getInMemoryDatabaseCounters ()
Returns information about all the atomic in-memory database counters in the system.
Collection< Transaction > getTransactions ()
Returns all the transactions in the system.
void redriveTransactions ()
Redrives stuck transactions while removing those that are done.
Static Public Attributes
static final String BASE_PARTITION_NAME = "p0"
Protected Member Functions
String nodeIdToUri (NodeId nodeId)
void bindApplicationService (ApplicationService service)
void unbindApplicationService (ApplicationService service)
Protected Attributes
PartitionedDatabase partitionedDatabase
Database inMemoryDatabase
NodeId localNodeId
ClusterMetadataService clusterMetadataService
ClusterService clusterService
ApplicationService applicationService
ClusterCommunicationService clusterCommunicator
PersistenceService persistenceService
Detailed Description
Database manager.
Definition at line 96 of file DatabaseManager.java.
Member Function Documentation
void org.onosproject.store.consistent.impl.DatabaseManager.activate ()
Definition at line 151 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.DatabaseManager.BASE_PARTITION_NAME, org.onosproject.store.consistent.impl.DatabaseManager.clusterCommunicator, org.onosproject.store.consistent.impl.DatabaseManager.clusterMetadataService, org.onosproject.store.consistent.impl.DatabaseManager.clusterService, org.onosproject.cluster.ClusterMetadataService.getLocalNode(), org.onosproject.store.consistent.impl.DatabaseManager.inMemoryDatabase, org.onosproject.store.consistent.impl.DatabaseManager.localNodeId, org.onosproject.store.consistent.impl.DatabaseManager.nodeIdToUri(), and org.onosproject.store.consistent.impl.DatabaseManager.partitionedDatabase.
AtomicCounterBuilder org.onosproject.store.consistent.impl.DatabaseManager.atomicCounterBuilder ()
Creates a new AtomicCounterBuilder.
Returns
atomic counter builder
Implements org.onosproject.store.service.StorageService.
Definition at line 340 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.DatabaseManager.inMemoryDatabase, and org.onosproject.store.consistent.impl.DatabaseManager.partitionedDatabase.
void org.onosproject.store.consistent.impl.DatabaseManager.bindApplicationService (ApplicationService service) protected
Definition at line 140 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.DatabaseManager.applicationService.
void org.onosproject.store.consistent.impl.DatabaseManager.deactivate ()
Definition at line 228 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.DatabaseManager.applicationService, org.onosproject.store.consistent.impl.PartitionedDatabase.close(), and org.onosproject.store.consistent.impl.DatabaseManager.partitionedDatabase.
Map<String, Long> org.onosproject.store.consistent.impl.DatabaseManager.getCounters ()
Returns information about all the atomic counters in the system.
If 2 counters belonging to 2 different databases have the same name, then only one counter from one database is returned.
Returns
mapping from counter name to that counter's next value
Implements org.onosproject.store.service.StorageAdminService.
Definition at line 367 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.counters(), org.onosproject.store.consistent.impl.DatabaseManager.inMemoryDatabase, and org.onosproject.store.consistent.impl.DatabaseManager.partitionedDatabase.
Map<String, Long> org.onosproject.store.consistent.impl.DatabaseManager.getInMemoryDatabaseCounters ()
Returns information about all the atomic in-memory database counters in the system.
Returns
mapping from counter name to that counter's next value
Implements org.onosproject.store.service.StorageAdminService.
Definition at line 382 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.DatabaseManager.inMemoryDatabase.
List<MapInfo> org.onosproject.store.consistent.impl.DatabaseManager.getMapInfo ()
Returns information about all the consistent maps in the system.
Returns
list of map information
Implements org.onosproject.store.service.StorageAdminService.
Definition at line 350 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.DatabaseManager.inMemoryDatabase, and org.onosproject.store.consistent.impl.DatabaseManager.partitionedDatabase.
Map<String, Long> org.onosproject.store.consistent.impl.DatabaseManager.getPartitionedDatabaseCounters ()
Returns information about all the atomic partitioned database counters in the system.
Returns
mapping from counter name to that counter's next value
Implements org.onosproject.store.service.StorageAdminService.
Definition at line 375 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.counters(), and org.onosproject.store.consistent.impl.DatabaseManager.partitionedDatabase.
List<PartitionInfo> org.onosproject.store.consistent.impl.DatabaseManager.getPartitionInfo ()
Returns information about all partitions in the system.
Returns
list of partition information
Implements org.onosproject.store.service.StorageAdminService.
Definition at line 251 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.DatabaseManager.inMemoryDatabase.
Collection<Transaction> org.onosproject.store.consistent.impl.DatabaseManager.getTransactions ()
Returns all the transactions in the system.
Returns
collection of transactions
Implements org.onosproject.store.service.StorageAdminService.
Definition at line 389 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.TransactionManager.getTransactions().
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.redriveTransactions().
String org.onosproject.store.consistent.impl.DatabaseManager.nodeIdToUri (NodeId nodeId) protected
Definition at line 135 of file DatabaseManager.java.
References create-flow.node, and org.onosproject.cluster.ControllerNode.tcpPort().
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.activate().
void org.onosproject.store.consistent.impl.DatabaseManager.redriveTransactions ()
Redrives stuck transactions while removing those that are done.
Implements org.onosproject.store.service.StorageAdminService.
Definition at line 407 of file DatabaseManager.java.
References org.onosproject.store.consistent.impl.DatabaseManager.getTransactions().
TransactionContextBuilder org.onosproject.store.consistent.impl.DatabaseManager.transactionContextBuilder ()
Creates a new transaction context builder.
Returns
a builder for a transaction context.
Implements org.onosproject.store.service.StorageService.
Definition at line 246 of file DatabaseManager.java.
References org.onosproject.core.IdGenerator.getNewId().
void org.onosproject.store.consistent.impl.DatabaseManager.unbindApplicationService (ApplicationService service) protected
Definition at line 145 of file DatabaseManager.java.
Member Data Documentation
ApplicationService org.onosproject.store.consistent.impl.DatabaseManager.applicationService protected
Definition at line 127 of file DatabaseManager.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.bindApplicationService(), and org.onosproject.store.consistent.impl.DatabaseManager.deactivate().
final String org.onosproject.store.consistent.impl.DatabaseManager.BASE_PARTITION_NAME = "p0" static
Definition at line 100 of file DatabaseManager.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.activate().
ClusterCommunicationService org.onosproject.store.consistent.impl.DatabaseManager.clusterCommunicator protected
Definition at line 130 of file DatabaseManager.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.activate().
ClusterMetadataService org.onosproject.store.consistent.impl.DatabaseManager.clusterMetadataService protected
Definition at line 121 of file DatabaseManager.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.activate().
ClusterService org.onosproject.store.consistent.impl.DatabaseManager.clusterService protected
Definition at line 124 of file DatabaseManager.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.activate().
Database org.onosproject.store.consistent.impl.DatabaseManager.inMemoryDatabase protected
Definition at line 107 of file DatabaseManager.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.activate(), org.onosproject.store.consistent.impl.DatabaseManager.atomicCounterBuilder(), org.onosproject.store.consistent.impl.DefaultTransactionContextBuilder.build(), org.onosproject.store.consistent.impl.DatabaseManager.getCounters(), org.onosproject.store.consistent.impl.DatabaseManager.getInMemoryDatabaseCounters(), org.onosproject.store.consistent.impl.DatabaseManager.getMapInfo(), and org.onosproject.store.consistent.impl.DatabaseManager.getPartitionInfo().
NodeId org.onosproject.store.consistent.impl.DatabaseManager.localNodeId protected
Definition at line 108 of file DatabaseManager.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.activate().
PartitionedDatabase org.onosproject.store.consistent.impl.DatabaseManager.partitionedDatabase protected
Definition at line 106 of file DatabaseManager.java.
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.activate(), org.onosproject.store.consistent.impl.DatabaseManager.atomicCounterBuilder(), org.onosproject.store.consistent.impl.DefaultTransactionContextBuilder.build(), org.onosproject.store.consistent.impl.DatabaseManager.deactivate(), org.onosproject.store.consistent.impl.DatabaseManager.getCounters(), org.onosproject.store.consistent.impl.DatabaseManager.getMapInfo(), and org.onosproject.store.consistent.impl.DatabaseManager.getPartitionedDatabaseCounters().
PersistenceService org.onosproject.store.consistent.impl.DatabaseManager.persistenceService protected
Definition at line 133 of file DatabaseManager.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DatabaseManager.java