onos: org.onosproject.net.intent.MplsPathIntentTest Class Reference
org.onosproject.net.intent.MplsPathIntentTest Class Reference
Unit tests for the MplsPathIntent class.
Public Member Functions
void mplsPathIntentTestSetUp ()
void testImmutability ()
Checks that the MplsPathIntent class is immutable.
void testEquals ()
Checks the operation of equals(), hashCode() and toString() methods.
void testContents ()
Checks that the MPLS path intent objects are created correctly.
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Additional Inherited Members
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
Unit tests for the MplsPathIntent class.
Definition at line 39 of file MplsPathIntentTest.java.
Member Function Documentation
void org.onosproject.net.intent.MplsPathIntentTest.mplsPathIntentTestSetUp ()
Definition at line 53 of file MplsPathIntentTest.java.
void org.onosproject.net.intent.MplsPathIntentTest.testContents ()
Checks that the MPLS path intent objects are created correctly.
Definition at line 102 of file MplsPathIntentTest.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.Intent.key(), org.onosproject.net.intent.PathIntent.path(), org.onosproject.net.intent.Intent.priority(), org.onosproject.net.intent.ConnectivityIntent.selector(), and org.onosproject.net.intent.ConnectivityIntent.treatment().
void org.onosproject.net.intent.MplsPathIntentTest.testEquals ()
Checks the operation of equals(), hashCode() and toString() methods.
Definition at line 91 of file MplsPathIntentTest.java.
void org.onosproject.net.intent.MplsPathIntentTest.testImmutability ()
Checks that the MplsPathIntent class is immutable.
Definition at line 83 of file MplsPathIntentTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/intent/MplsPathIntentTest.java