onos: org.onlab.graph.BreadthFirstSearchTest Class Reference
org.onlab.graph.BreadthFirstSearchTest Class Reference
Test of the BFS and similar path search algorithms.
Public Member Functions
void defaultGraphTest ()
void defaultHopCountWeight ()
Public Member Functions inherited from org.onlab.graph.AbstractGraphPathSearchTest
void noSuchSourceArgument ()
void nullGraphArgument ()
void nullSourceArgument ()
void samenessThreshold ()
Protected Member Functions
AbstractGraphPathSearch
< TestVertex, TestEdge > graphSearch ()
Creates a test-specific graph search to exercise.
void executeDefaultTest (int pathCount, int pathLength, double pathCost)
void executeSearch (GraphPathSearch< TestVertex, TestEdge > search, Graph< TestVertex, TestEdge > graph, TestVertex src, TestVertex dst, EdgeWeight< TestVertex, TestEdge > weight, int pathCount, double pathCost)
void executeSinglePathSearch (GraphPathSearch< TestVertex, TestEdge > search, Graph< TestVertex, TestEdge > graph, TestVertex src, TestVertex dst, EdgeWeight< TestVertex, TestEdge > weight, int pathCount, double pathCost)
Protected Member Functions inherited from org.onlab.graph.GraphTest
void printPaths (Set< Path< TestVertex, TestEdge >> paths)
Set< TestVertex > vertexes ()
Set< TestEdge > edges ()
Additional Inherited Members
Protected Attributes inherited from org.onlab.graph.GraphTest
Graph< TestVertex, TestEdge > graph
EdgeWeight< TestVertex, TestEdge > weight
Detailed Description
Test of the BFS and similar path search algorithms.
Definition at line 28 of file BreadthFirstSearchTest.java.
Member Function Documentation
void org.onlab.graph.BreadthFirstSearchTest.defaultGraphTest ()
Definition at line 36 of file BreadthFirstSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeDefaultTest().
void org.onlab.graph.BreadthFirstSearchTest.defaultHopCountWeight ()
Definition at line 41 of file BreadthFirstSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeDefaultTest(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.BreadthFirstSearchTest.executeDefaultTest (int pathCount, int pathLength, double pathCost) protected
Definition at line 47 of file BreadthFirstSearchTest.java.
References org.onlab.graph.GraphTest.edges(), org.onlab.graph.GraphTest.graph, org.onlab.graph.BreadthFirstSearchTest.graphSearch(), org.onlab.graph.GraphTest.printPaths(), org.onlab.graph.GraphTest.vertexes(), and org.onlab.graph.GraphTest.weight.
Referenced by org.onlab.graph.BreadthFirstSearchTest.defaultGraphTest(), org.onlab.graph.BellmanFordGraphSearchTest.defaultGraphTest(), org.onlab.graph.DijkstraGraphSearchTest.defaultGraphTest(), org.onlab.graph.BreadthFirstSearchTest.defaultHopCountWeight(), org.onlab.graph.BellmanFordGraphSearchTest.defaultHopCountWeight(), and org.onlab.graph.DijkstraGraphSearchTest.defaultHopCountWeight().
void org.onlab.graph.BreadthFirstSearchTest.executeSearch (GraphPathSearch< TestVertex, TestEdge > search, Graph< TestVertex, TestEdge > graph, TestVertex src, TestVertex dst, EdgeWeight< TestVertex, TestEdge > weight, int pathCount, double pathCost) protected
Definition at line 67 of file BreadthFirstSearchTest.java.
References org.onlab.graph.GraphTest.graph, org.onlab.graph.GraphTest.printPaths(), and org.onlab.graph.GraphTest.weight.
Referenced by org.onlab.graph.SuurballeGraphSearchTest.basicGraphTest(), org.onlab.graph.DijkstraGraphSearchTest.denseMultiplePath(), org.onlab.graph.SuurballeGraphSearchTest.differingPrimaryAndBackupPathLengths(), org.onlab.graph.DijkstraGraphSearchTest.disconnected(), org.onlab.graph.DijkstraGraphSearchTest.dualEdgeMultiplePath(), org.onlab.graph.SuurballeGraphSearchTest.multiplePathOnePairGraphTest(), org.onlab.graph.DijkstraGraphSearchTest.negativeWeights(), and org.onlab.graph.DijkstraGraphSearchTest.simpleMultiplePath().
void org.onlab.graph.BreadthFirstSearchTest.executeSinglePathSearch (GraphPathSearch< TestVertex, TestEdge > search, Graph< TestVertex, TestEdge > graph, TestVertex src, TestVertex dst, EdgeWeight< TestVertex, TestEdge > weight, int pathCount, double pathCost) protected
Definition at line 84 of file BreadthFirstSearchTest.java.
References org.onlab.graph.GraphTest.graph, org.onlab.graph.GraphTest.printPaths(), and org.onlab.graph.GraphTest.weight.
Referenced by org.onlab.graph.DijkstraGraphSearchTest.denseMultiplePath(), org.onlab.graph.DijkstraGraphSearchTest.dualEdgeMultiplePath(), org.onlab.graph.DijkstraGraphSearchTest.negativeWeights(), and org.onlab.graph.DijkstraGraphSearchTest.simpleMultiplePath().
AbstractGraphPathSearch<TestVertex, TestEdge> org.onlab.graph.BreadthFirstSearchTest.graphSearch () protected virtual
Creates a test-specific graph search to exercise.
Returns
graph search
Implements org.onlab.graph.AbstractGraphPathSearchTest.
Reimplemented in org.onlab.graph.SrlgGraphSearchTest, org.onlab.graph.DijkstraGraphSearchTest, and org.onlab.graph.SuurballeGraphSearchTest.
Definition at line 31 of file BreadthFirstSearchTest.java.
Referenced by org.onlab.graph.BreadthFirstSearchTest.executeDefaultTest().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/graph/BreadthFirstSearchTest.java