onos: org.onosproject.net.intent.constraint.BooleanConstraint Class Reference
org.onosproject.net.intent.constraint.BooleanConstraint Class Reference abstract
Abstract base class for various constraints that evaluate link viability in a yes/no fashion.
Public Member Functions
abstract boolean isValid (Link link, LinkResourceService resourceService)
Returns true if the specified link satisfies the constraint.
double cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
boolean validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
Detailed Description
Abstract base class for various constraints that evaluate link viability in a yes/no fashion.
Definition at line 29 of file BooleanConstraint.java.
Member Function Documentation
double org.onosproject.net.intent.constraint.BooleanConstraint.cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
Negative return value means the specified link does not satisfy this constraint.
Parameters
link Evaluates the specified link and provides the cost for its traversal.
resourceService Evaluates the specified link and provides the cost for its traversal.
Returns
Evaluates the specified link and provides the cost for its traversal.
Implements org.onosproject.net.intent.Constraint.
Definition at line 50 of file BooleanConstraint.java.
References org.onosproject.net.intent.constraint.BooleanConstraint.isValid().
abstract boolean org.onosproject.net.intent.constraint.BooleanConstraint.isValid (Link link, LinkResourceService resourceService) pure virtual
Returns true if the specified link satisfies the constraint.
Parameters
link link to be validated
resourceService resource service for checking available link resources
Returns
true if link is viable
Implemented in org.onosproject.net.intent.constraint.AnnotationConstraint, org.onosproject.net.intent.constraint.BandwidthConstraint, org.onosproject.net.intent.constraint.LinkTypeConstraint, org.onosproject.net.intent.constraint.ObstacleConstraint, org.onosproject.net.intent.constraint.LambdaConstraint, and org.onosproject.net.intent.constraint.EncapsulationConstraint.
Referenced by org.onosproject.net.intent.constraint.BooleanConstraint.cost(), and org.onosproject.net.intent.constraint.BooleanConstraint.validate().
boolean org.onosproject.net.intent.constraint.BooleanConstraint.validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
Parameters
path path to be validated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
Implements org.onosproject.net.intent.Constraint.
Definition at line 55 of file BooleanConstraint.java.
References org.onosproject.net.intent.constraint.BooleanConstraint.isValid(), and org.onosproject.net.Path.links().
Referenced by org.onosproject.net.intent.constraint.ObstacleConstraintTest.testPathNotThroughObstacles(), and org.onosproject.net.intent.constraint.ObstacleConstraintTest.testPathThroughObstacle().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/constraint/BooleanConstraint.java