onos: org.onosproject.app.impl.ApplicationManager Class Reference
org.onosproject.app.impl.ApplicationManager Class Reference
Implementation of the application management service.
Public Member Functions
void activate ()
void deactivate ()
Set< Application > getApplications ()
Returns the set of all installed applications.
ApplicationId getId (String name)
Returns the registered id of the application with the given name.
Application getApplication (ApplicationId appId)
Returns the application with the supplied application identifier.
ApplicationState getState (ApplicationId appId)
Return the application state.
Set< Permission > getPermissions (ApplicationId appId)
Returns the permissions currently granted to the applications.
void registerDeactivateHook (ApplicationId appId, Runnable hook)
Registers application pre-deactivation processing hook.
Application install (InputStream appDescStream)
Installs the application contained in the specified application archive input stream.
void uninstall (ApplicationId appId)
Uninstalls the specified application.
void activate (ApplicationId appId)
Activates the specified application.
void deactivate (ApplicationId appId)
Deactivates the specified application.
void setPermissions (ApplicationId appId, Set< Permission > permissions)
Updates the permissions granted to the applications.
Protected Attributes
ApplicationStore store
FeaturesService featuresService
Detailed Description
Implementation of the application management service.
Definition at line 56 of file ApplicationManager.java.
Member Function Documentation
void org.onosproject.app.impl.ApplicationManager.activate ()
Definition at line 78 of file ApplicationManager.java.
void org.onosproject.app.impl.ApplicationManager.activate (ApplicationId appId)
Activates the specified application.
Parameters
appId application identifier
Implements org.onosproject.app.ApplicationAdminService.
Definition at line 156 of file ApplicationManager.java.
References org.onosproject.security.SecurityUtil.isAppSecured().
void org.onosproject.app.impl.ApplicationManager.deactivate ()
Definition at line 89 of file ApplicationManager.java.
void org.onosproject.app.impl.ApplicationManager.deactivate (ApplicationId appId)
Deactivates the specified application.
Parameters
appId application identifier
Implements org.onosproject.app.ApplicationAdminService.
Definition at line 165 of file ApplicationManager.java.
Application org.onosproject.app.impl.ApplicationManager.getApplication (ApplicationId appId)
Returns the application with the supplied application identifier.
Parameters
appId application identifier
Returns
application descriptor
Implements org.onosproject.app.ApplicationService.
Definition at line 109 of file ApplicationManager.java.
Referenced by org.onosproject.app.impl.ApplicationManagerTest.install().
Set<Application> org.onosproject.app.impl.ApplicationManager.getApplications ()
Returns the set of all installed applications.
Returns
set of installed apps
Implements org.onosproject.app.ApplicationService.
Definition at line 96 of file ApplicationManager.java.
Referenced by org.onosproject.app.impl.ApplicationManagerTest.install(), and org.onosproject.app.impl.ApplicationManagerTest.uninstall().
ApplicationId org.onosproject.app.impl.ApplicationManager.getId (String name)
Returns the registered id of the application with the given name.
Parameters
name application name
Returns
registered application id
Implements org.onosproject.app.ApplicationService.
Definition at line 102 of file ApplicationManager.java.
References create-flow.name.
Referenced by metro.FabricDomain.build().
Set<Permission> org.onosproject.app.impl.ApplicationManager.getPermissions (ApplicationId appId)
Returns the permissions currently granted to the applications.
Parameters
appId application identifier
Returns
set of granted permissions
Implements org.onosproject.app.ApplicationService.
Definition at line 123 of file ApplicationManager.java.
ApplicationState org.onosproject.app.impl.ApplicationManager.getState (ApplicationId appId)
Return the application state.
Parameters
appId application identifier
Returns
application state
Implements org.onosproject.app.ApplicationService.
Definition at line 116 of file ApplicationManager.java.
Referenced by org.onosproject.app.impl.ApplicationManagerTest.activate(), org.onosproject.app.impl.ApplicationManagerTest.deactivate(), and org.onosproject.app.impl.ApplicationManagerTest.install().
Application org.onosproject.app.impl.ApplicationManager.install (InputStream appDescStream)
Installs the application contained in the specified application archive input stream.
This can be either a ZIP stream containing a compressed application archive or a plain XML stream containing just the
app.xml
application descriptor file.
Parameters
appDescStream application descriptor input stream
Returns
installed application descriptor
Exceptions
org.onosproject.app.ApplicationException if unable to read the app archive stream
Implements org.onosproject.app.ApplicationAdminService.
Definition at line 138 of file ApplicationManager.java.
void org.onosproject.app.impl.ApplicationManager.registerDeactivateHook (ApplicationId appId, Runnable hook)
Registers application pre-deactivation processing hook.
Parameters
appId application identifier
hook pre-deactivation hook
Implements org.onosproject.app.ApplicationService.
Definition at line 130 of file ApplicationManager.java.
void org.onosproject.app.impl.ApplicationManager.setPermissions (ApplicationId appId, Set< Permission > permissions)
Updates the permissions granted to the applications.
Parameters
appId application identifier
permissions set of granted permissions
Implements org.onosproject.app.ApplicationAdminService.
Definition at line 171 of file ApplicationManager.java.
void org.onosproject.app.impl.ApplicationManager.uninstall (ApplicationId appId)
Uninstalls the specified application.
Parameters
appId application identifier
Implements org.onosproject.app.ApplicationAdminService.
Definition at line 146 of file ApplicationManager.java.
Member Data Documentation
FeaturesService org.onosproject.app.impl.ApplicationManager.featuresService protected
Definition at line 70 of file ApplicationManager.java.
ApplicationStore org.onosproject.app.impl.ApplicationManager.store protected
Definition at line 67 of file ApplicationManager.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/app/impl/ApplicationManager.java