onos: org.onosproject.incubator.net.domain.DomainEdge Class Reference
org.onosproject.incubator.net.domain.DomainEdge Class Reference
Representation of a connection between an intent domain and a device.
Public Member Functions
DomainEdge (DomainVertex src, DomainVertex dst, ConnectPoint connectPoint)
int hashCode ()
boolean equals (Object obj)
String toString ()
ConnectPoint connectPoint ()
Returns the connect point associated with the domain edge.
Detailed Description
Representation of a connection between an intent domain and a device.
This must happen using a connect point that is part of both the domain and the device.
Definition at line 31 of file DomainEdge.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.domain.DomainEdge.DomainEdge (DomainVertex src, DomainVertex dst, ConnectPoint connectPoint)
Definition at line 35 of file DomainEdge.java.
References org.onosproject.incubator.net.domain.DomainEdge.connectPoint().
Referenced by org.onosproject.incubator.net.domain.DomainEdge.equals().
Member Function Documentation
ConnectPoint org.onosproject.incubator.net.domain.DomainEdge.connectPoint ()
Returns the connect point associated with the domain edge.
Returns
this edges connect point
Definition at line 72 of file DomainEdge.java.
Referenced by org.onosproject.incubator.net.domain.DomainEdge.DomainEdge(), org.onosproject.incubator.net.domain.DomainEdge.hashCode(), and org.onosproject.incubator.net.domain.DomainEdge.toString().
boolean org.onosproject.incubator.net.domain.DomainEdge.equals (Object obj)
Definition at line 46 of file DomainEdge.java.
References org.onosproject.incubator.net.domain.DomainEdge.DomainEdge().
int org.onosproject.incubator.net.domain.DomainEdge.hashCode ()
Definition at line 41 of file DomainEdge.java.
References org.onosproject.incubator.net.domain.DomainEdge.connectPoint(), and org.onosproject.net.ConnectPoint.hashCode().
String org.onosproject.incubator.net.domain.DomainEdge.toString ()
Definition at line 59 of file DomainEdge.java.
References org.onosproject.incubator.net.domain.DomainEdge.connectPoint().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/domain/DomainEdge.java