onos: org.onosproject.incubator.net.resource.label.LabelResourcePool Class Reference
org.onosproject.incubator.net.resource.label.LabelResourcePool Class Reference
Abstraction of the capacity of device label resource or global label resource.
Public Member Functions
LabelResourcePool (String deviceId, long beginLabel, long endLabel)
Creates a pool by device id,begin label id,end label id.
LabelResourcePool (String deviceId, long beginLabel, long endLabel, long totalNum, long usedNum, long currentUsedMaxLabelId, ImmutableSet< LabelResource > releaseLabelId)
Creates a pool by device id,begin label id,end label id.
DeviceId deviceId ()
Returns a device id.
LabelResourceId beginLabel ()
Returns a begin Label id.
LabelResourceId endLabel ()
Returns an end Label id.
LabelResourceId currentUsedMaxLabelId ()
Returns a begin Label id.
long totalNum ()
Returns total number.
long usedNum ()
Returns used number.
Set< LabelResource > releaseLabelId ()
Returns the Set of released label before.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Abstraction of the capacity of device label resource or global label resource.
It's contiguous range of label resource. When a application apply some labels of some device, first catch from Set that store available labels, if the size of the Set less than the apply number, then get labels by calculating with three attributes, beginLabel,endLabel and currentUsedMaxLabelId.
Definition at line 39 of file LabelResourcePool.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.resource.label.LabelResourcePool.LabelResourcePool (String deviceId, long beginLabel, long endLabel)
Creates a pool by device id,begin label id,end label id.
Parameters
deviceId device identifier
beginLabel represents for the first label id in the range of label resource pool
endLabel represents for the last label id in the range of label resource pool
Definition at line 59 of file LabelResourcePool.java.
References org.onosproject.incubator.net.resource.label.LabelResourcePool.beginLabel(), org.onosproject.incubator.net.resource.label.LabelResourcePool.deviceId(), and org.onosproject.incubator.net.resource.label.LabelResourcePool.endLabel().
Referenced by org.onosproject.incubator.net.resource.label.LabelResourcePool.equals().
org.onosproject.incubator.net.resource.label.LabelResourcePool.LabelResourcePool (String deviceId, long beginLabel, long endLabel, long totalNum, long usedNum, long currentUsedMaxLabelId, ImmutableSet< LabelResource > releaseLabelId)
Creates a pool by device id,begin label id,end label id.
Used to update a pool in the store.
Parameters
deviceId device identifier
beginLabel represents for the first label id in the range of label resource pool
endLabel represents for the last label id in the range of label resource pool
totalNum capacity of label resource pool
usedNum have used label number
currentUsedMaxLabelId the maximal label number id
releaseLabelId Set of released label
Definition at line 78 of file LabelResourcePool.java.
References org.onosproject.incubator.net.resource.label.LabelResourcePool.beginLabel(), org.onosproject.incubator.net.resource.label.LabelResourcePool.currentUsedMaxLabelId(), org.onosproject.incubator.net.resource.label.LabelResourcePool.deviceId(), org.onosproject.incubator.net.resource.label.LabelResourcePool.endLabel(), org.onosproject.incubator.net.resource.label.LabelResourcePool.releaseLabelId(), org.onosproject.incubator.net.resource.label.LabelResourcePool.totalNum(), and org.onosproject.incubator.net.resource.label.LabelResourcePool.usedNum().
Member Function Documentation
LabelResourceId org.onosproject.incubator.net.resource.label.LabelResourcePool.beginLabel ()
Returns a begin Label id.
Returns
begin Label id
Definition at line 109 of file LabelResourcePool.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourcePool.LabelResourcePool().
LabelResourceId org.onosproject.incubator.net.resource.label.LabelResourcePool.currentUsedMaxLabelId ()
Returns a begin Label id.
Returns
current Used Maximal Label Id
Definition at line 127 of file LabelResourcePool.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourcePool.LabelResourcePool().
DeviceId org.onosproject.incubator.net.resource.label.LabelResourcePool.deviceId ()
Returns a device id.
Returns
DeviceId
Definition at line 100 of file LabelResourcePool.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourcePool.LabelResourcePool(), and org.onosproject.incubator.net.resource.label.LabelResourcePool.toString().
LabelResourceId org.onosproject.incubator.net.resource.label.LabelResourcePool.endLabel ()
Returns an end Label id.
Returns
end Label id
Definition at line 118 of file LabelResourcePool.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourcePool.LabelResourcePool(), and org.onosproject.incubator.net.resource.label.LabelResourcePool.toString().
boolean org.onosproject.incubator.net.resource.label.LabelResourcePool.equals (Object obj)
Definition at line 166 of file LabelResourcePool.java.
References find-flow.deviceId, and org.onosproject.incubator.net.resource.label.LabelResourcePool.LabelResourcePool().
int org.onosproject.incubator.net.resource.label.LabelResourcePool.hashCode ()
Definition at line 159 of file LabelResourcePool.java.
References find-flow.deviceId.
Set<LabelResource> org.onosproject.incubator.net.resource.label.LabelResourcePool.releaseLabelId ()
Returns the Set of released label before.
Returns
the Set of LabelResource
Definition at line 154 of file LabelResourcePool.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourcePool.LabelResourcePool(), and org.onosproject.incubator.net.resource.label.LabelResourcePool.toString().
String org.onosproject.incubator.net.resource.label.LabelResourcePool.toString ()
Definition at line 182 of file LabelResourcePool.java.
References org.onosproject.incubator.net.resource.label.LabelResourcePool.deviceId(), org.onosproject.incubator.net.resource.label.LabelResourcePool.endLabel(), org.onosproject.incubator.net.resource.label.LabelResourcePool.releaseLabelId(), and org.onosproject.incubator.net.resource.label.LabelResourcePool.usedNum().
long org.onosproject.incubator.net.resource.label.LabelResourcePool.totalNum ()
Returns total number.
Returns
the total label number
Definition at line 136 of file LabelResourcePool.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourcePool.LabelResourcePool().
long org.onosproject.incubator.net.resource.label.LabelResourcePool.usedNum ()
Returns used number.
Returns
the used label number
Definition at line 145 of file LabelResourcePool.java.
Referenced by org.onosproject.incubator.net.resource.label.LabelResourcePool.LabelResourcePool(), and org.onosproject.incubator.net.resource.label.LabelResourcePool.toString().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/resource/label/LabelResourcePool.java