onos: org.onosproject.net.LinkKey Class Reference
org.onosproject.net.LinkKey Class Reference
Immutable representation of a link identity.
Public Member Functions
ConnectPoint src ()
Returns source connection point.
ConnectPoint dst ()
Returns destination connection point.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static LinkKey linkKey (ConnectPoint src, ConnectPoint dst)
Creates a link identifier with source and destination connection point.
static LinkKey linkKey (Link link)
Creates a link identifier for the specified link.
Detailed Description
Immutable representation of a link identity.
Definition at line 30 of file LinkKey.java.
Member Function Documentation
ConnectPoint org.onosproject.net.LinkKey.dst ()
Returns destination connection point.
Returns
destination connection point
Definition at line 49 of file LinkKey.java.
Referenced by org.onosproject.net.LinkKey.hashCode(), and org.onosproject.net.LinkKey.toString().
boolean org.onosproject.net.LinkKey.equals (Object obj)
Definition at line 91 of file LinkKey.java.
int org.onosproject.net.LinkKey.hashCode ()
Definition at line 86 of file LinkKey.java.
References org.onosproject.net.LinkKey.dst(), and org.onosproject.net.LinkKey.src().
Referenced by org.onosproject.net.LinkKeyTest.testHashCodeEquals(), and org.onosproject.net.LinkKeyTest.testHashCodeNotEquals().
static LinkKey org.onosproject.net.LinkKey.linkKey (ConnectPoint src, ConnectPoint dst) static
Creates a link identifier with source and destination connection point.
Parameters
src source connection point
dst destination connection point
Returns
a link identifier
Definition at line 71 of file LinkKey.java.
Referenced by org.onosproject.net.newresource.ResourcePathTest.testEquals(), org.onosproject.store.serializers.KryoSerializerTest.testLinkKey(), org.onosproject.store.serializers.KryoSerializerTest.testResourceAllocation(), and org.onosproject.store.serializers.KryoSerializerTest.testResourcePath().
static LinkKey org.onosproject.net.LinkKey.linkKey (Link link) static
Creates a link identifier for the specified link.
Parameters
link link descriptor
Returns
a link identifier
Definition at line 81 of file LinkKey.java.
References org.onosproject.net.Link.src().
ConnectPoint org.onosproject.net.LinkKey.src ()
Returns source connection point.
Returns
source connection point
Definition at line 40 of file LinkKey.java.
Referenced by org.onosproject.net.LinkKey.hashCode(), and org.onosproject.net.LinkKey.toString().
String org.onosproject.net.LinkKey.toString ()
Definition at line 104 of file LinkKey.java.
References org.onosproject.net.LinkKey.dst(), and org.onosproject.net.LinkKey.src().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/LinkKey.java