onos: org.onosproject.net.statistic.SummaryFlowEntryWithLoad Class Reference
org.onosproject.net.statistic.SummaryFlowEntryWithLoad Class Reference
Summary Load classified by flow live type.
Public Member Functions
SummaryFlowEntryWithLoad (ConnectPoint cp, Load totalLoad)
Creates a new summary flow entry having load for the given connect point and total load.
SummaryFlowEntryWithLoad (ConnectPoint cp, Load totalLoad, Load immediateLoad, Load shortLoad, Load midLoad, Load longLoad)
Creates a new summary flow entry having load for the given connect point and total, immediate, short, mid, and long load.
SummaryFlowEntryWithLoad (ConnectPoint cp, Load totalLoad, Load immediateLoad, Load shortLoad, Load midLoad, Load longLoad, Load unknownLoad)
Creates a new summary flow entry having load for the given connect point and total, immediate, short, mid, long, and unknown load.
ConnectPoint connectPoint ()
Returns connect point.
Load totalLoad ()
Returns total load of connect point.
Load immediateLoad ()
Returns immediate load of connect point.
Load shortLoad ()
Returns short load of connect point.
Load midLoad ()
Returns mid load of connect point.
Load longLoad ()
Returns long load of connect point.
Load unknownLoad ()
Returns unknown load of connect point.
Detailed Description
Summary Load classified by flow live type.
Definition at line 24 of file SummaryFlowEntryWithLoad.java.
Constructor & Destructor Documentation
org.onosproject.net.statistic.SummaryFlowEntryWithLoad.SummaryFlowEntryWithLoad (ConnectPoint cp, Load totalLoad)
Creates a new summary flow entry having load for the given connect point and total load.
Parameters
cp connect point
totalLoad total load
Definition at line 39 of file SummaryFlowEntryWithLoad.java.
References org.onosproject.net.statistic.SummaryFlowEntryWithLoad.totalLoad().
org.onosproject.net.statistic.SummaryFlowEntryWithLoad.SummaryFlowEntryWithLoad (ConnectPoint cp, Load totalLoad, Load immediateLoad, Load shortLoad, Load midLoad, Load longLoad)
Creates a new summary flow entry having load for the given connect point and total, immediate, short, mid, and long load.
Parameters
cp connect point
totalLoad total load
immediateLoad immediate load
shortLoad short load
midLoad mid load
longLoad long load
Definition at line 60 of file SummaryFlowEntryWithLoad.java.
References org.onosproject.net.statistic.SummaryFlowEntryWithLoad.immediateLoad(), org.onosproject.net.statistic.SummaryFlowEntryWithLoad.longLoad(), org.onosproject.net.statistic.SummaryFlowEntryWithLoad.midLoad(), org.onosproject.net.statistic.SummaryFlowEntryWithLoad.shortLoad(), and org.onosproject.net.statistic.SummaryFlowEntryWithLoad.totalLoad().
org.onosproject.net.statistic.SummaryFlowEntryWithLoad.SummaryFlowEntryWithLoad (ConnectPoint cp, Load totalLoad, Load immediateLoad, Load shortLoad, Load midLoad, Load longLoad, Load unknownLoad)
Creates a new summary flow entry having load for the given connect point and total, immediate, short, mid, long, and unknown load.
Parameters
cp connect point
totalLoad total load
immediateLoad immediate load
shortLoad short load
midLoad mid load
longLoad long load
unknownLoad long load
Definition at line 83 of file SummaryFlowEntryWithLoad.java.
References org.onosproject.net.statistic.SummaryFlowEntryWithLoad.immediateLoad(), org.onosproject.net.statistic.SummaryFlowEntryWithLoad.longLoad(), org.onosproject.net.statistic.SummaryFlowEntryWithLoad.midLoad(), org.onosproject.net.statistic.SummaryFlowEntryWithLoad.shortLoad(), org.onosproject.net.statistic.SummaryFlowEntryWithLoad.totalLoad(), and org.onosproject.net.statistic.SummaryFlowEntryWithLoad.unknownLoad().
Member Function Documentation
ConnectPoint org.onosproject.net.statistic.SummaryFlowEntryWithLoad.connectPoint ()
Returns connect point.
Returns
connect point
Definition at line 100 of file SummaryFlowEntryWithLoad.java.
Load org.onosproject.net.statistic.SummaryFlowEntryWithLoad.immediateLoad ()
Returns immediate load of connect point.
Returns
immediate load
Definition at line 118 of file SummaryFlowEntryWithLoad.java.
Referenced by org.onosproject.net.statistic.SummaryFlowEntryWithLoad.SummaryFlowEntryWithLoad().
Load org.onosproject.net.statistic.SummaryFlowEntryWithLoad.longLoad ()
Returns long load of connect point.
Returns
long load
Definition at line 145 of file SummaryFlowEntryWithLoad.java.
Referenced by org.onosproject.net.statistic.SummaryFlowEntryWithLoad.SummaryFlowEntryWithLoad().
Load org.onosproject.net.statistic.SummaryFlowEntryWithLoad.midLoad ()
Returns mid load of connect point.
Returns
mid load
Definition at line 136 of file SummaryFlowEntryWithLoad.java.
Referenced by org.onosproject.net.statistic.SummaryFlowEntryWithLoad.SummaryFlowEntryWithLoad().
Load org.onosproject.net.statistic.SummaryFlowEntryWithLoad.shortLoad ()
Returns short load of connect point.
Returns
short load
Definition at line 127 of file SummaryFlowEntryWithLoad.java.
Referenced by org.onosproject.net.statistic.SummaryFlowEntryWithLoad.SummaryFlowEntryWithLoad().
Load org.onosproject.net.statistic.SummaryFlowEntryWithLoad.totalLoad ()
Returns total load of connect point.
Returns
total load
Definition at line 109 of file SummaryFlowEntryWithLoad.java.
Referenced by org.onosproject.net.statistic.SummaryFlowEntryWithLoad.SummaryFlowEntryWithLoad().
Load org.onosproject.net.statistic.SummaryFlowEntryWithLoad.unknownLoad ()
Returns unknown load of connect point.
Returns
unknown load
Definition at line 154 of file SummaryFlowEntryWithLoad.java.
Referenced by org.onosproject.net.statistic.SummaryFlowEntryWithLoad.SummaryFlowEntryWithLoad().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/statistic/SummaryFlowEntryWithLoad.java