onos: org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest Class Reference
org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest Class Reference
Unit tests for PathIntentCompiler.
Public Member Functions
void setUp ()
Configures objects used in all the test cases.
void tearDown ()
Tears down objects used in all the test cases.
void testCompile ()
Tests the compilation behavior of the path intent compiler.
Detailed Description
Unit tests for PathIntentCompiler.
Definition at line 61 of file PathIntentCompilerTest.java.
Member Function Documentation
void org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest.setUp ()
Configures objects used in all the test cases.
Definition at line 93 of file PathIntentCompilerTest.java.
References org.onosproject.core.CoreService.registerApplication().
void org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest.tearDown ()
Tears down objects used in all the test cases.
Definition at line 121 of file PathIntentCompilerTest.java.
void org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest.testCompile ()
Tests the compilation behavior of the path intent compiler.
Definition at line 129 of file PathIntentCompilerTest.java.
References org.onosproject.net.flow.DefaultTrafficSelector.builder(), org.onosproject.net.flow.DefaultTrafficTreatment.builder(), org.onosproject.net.ConnectPoint.deviceId(), org.onosproject.net.flow.FlowRule.deviceId(), org.onosproject.net.flow.FlowRule.priority(), org.onosproject.net.flow.FlowRule.selector(), and org.onosproject.net.flow.FlowRule.treatment().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/intent/impl/compiler/PathIntentCompilerTest.java