onos: org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl Class Reference
org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl Class Reference
The implementation of OvsdbController.
Public Member Functions
void activate (ComponentContext context)
void deactivate ()
void addNodeListener (OvsdbNodeListener listener)
Adds Node Event Listener.
void removeNodeListener (OvsdbNodeListener listener)
Removes Node Event Listener.
void addOvsdbEventListener (OvsdbEventListener listener)
Adds ovsdb event listener.
void removeOvsdbEventListener (OvsdbEventListener listener)
Removes ovsdb event listener.
List< OvsdbNodeId > getNodeIds ()
Gets all the nodes information.
OvsdbClientService getOvsdbClient (OvsdbNodeId nodeId)
Gets an ovsdb client by node identifier.
void connect (IpAddress ip, TpPort port)
Connect to the ovsdb server with given ip address and port number.
Static Public Attributes
static final Logger log
Protected Attributes
ConcurrentHashMap< OvsdbNodeId,
OvsdbClientService > ovsdbClients
OvsdbAgent agent = new InternalOvsdbNodeAgent()
InternalMonitorCallBack updateCallback = new InternalMonitorCallBack()
Set< OvsdbNodeListener > ovsdbNodeListener = new CopyOnWriteArraySet<>()
Set< OvsdbEventListener > ovsdbEventListener = new CopyOnWriteArraySet<>()
ConcurrentHashMap< String,
OvsdbClientService > requestNotification
ConcurrentHashMap< String, String > requestDbName = new ConcurrentHashMap<String, String>()
Detailed Description
The implementation of OvsdbController.
Definition at line 78 of file OvsdbControllerImpl.java.
Member Function Documentation
void org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.activate (ComponentContext context)
Definition at line 100 of file OvsdbControllerImpl.java.
References org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.agent, and org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.updateCallback.
void org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.addNodeListener (OvsdbNodeListener listener)
Adds Node Event Listener.
Parameters
listener node listener
Implements org.onosproject.ovsdb.controller.OvsdbController.
Definition at line 112 of file OvsdbControllerImpl.java.
References org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.ovsdbNodeListener.
void org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.addOvsdbEventListener (OvsdbEventListener listener)
Adds ovsdb event listener.
Parameters
listener event listener
Implements org.onosproject.ovsdb.controller.OvsdbController.
Definition at line 124 of file OvsdbControllerImpl.java.
References org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.ovsdbEventListener.
void org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.connect (IpAddress ip, TpPort port)
Connect to the ovsdb server with given ip address and port number.
Parameters
ip ip address
port port number
Implements org.onosproject.ovsdb.controller.OvsdbController.
Definition at line 146 of file OvsdbControllerImpl.java.
References obeliskHostCheck.port.
void org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.deactivate ()
Definition at line 106 of file OvsdbControllerImpl.java.
List<OvsdbNodeId> org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.getNodeIds ()
Gets all the nodes information.
Returns
the list of node id
Implements org.onosproject.ovsdb.controller.OvsdbController.
Definition at line 136 of file OvsdbControllerImpl.java.
OvsdbClientService org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.getOvsdbClient (OvsdbNodeId nodeId)
Gets an ovsdb client by node identifier.
Parameters
nodeId node identifier
Returns
OvsdbClient ovsdb node information
Implements org.onosproject.ovsdb.controller.OvsdbController.
Definition at line 141 of file OvsdbControllerImpl.java.
void org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.removeNodeListener (OvsdbNodeListener listener)
Removes Node Event Listener.
Parameters
listener node listener
Implements org.onosproject.ovsdb.controller.OvsdbController.
Definition at line 119 of file OvsdbControllerImpl.java.
void org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.removeOvsdbEventListener (OvsdbEventListener listener)
Removes ovsdb event listener.
Parameters
listener event listener
Implements org.onosproject.ovsdb.controller.OvsdbController.
Definition at line 131 of file OvsdbControllerImpl.java.
Member Data Documentation
OvsdbAgent org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.agent = new InternalOvsdbNodeAgent() protected
Definition at line 86 of file OvsdbControllerImpl.java.
Referenced by org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.activate().
final Logger org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.log static
Initial value:
= LoggerFactory
            .getLogger(OvsdbControllerImpl.class)
Definition at line 80 of file OvsdbControllerImpl.java.
ConcurrentHashMap<OvsdbNodeId, OvsdbClientService> org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.ovsdbClients protected
Initial value:
=
            new ConcurrentHashMap<OvsdbNodeId, OvsdbClientService>()
Definition at line 83 of file OvsdbControllerImpl.java.
Set<OvsdbEventListener> org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.ovsdbEventListener = new CopyOnWriteArraySet<>() protected
Definition at line 90 of file OvsdbControllerImpl.java.
Referenced by org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.addOvsdbEventListener().
Set<OvsdbNodeListener> org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.ovsdbNodeListener = new CopyOnWriteArraySet<>() protected
Definition at line 89 of file OvsdbControllerImpl.java.
Referenced by org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.addNodeListener().
ConcurrentHashMap<String, String> org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.requestDbName = new ConcurrentHashMap<String, String>() protected
Definition at line 95 of file OvsdbControllerImpl.java.
ConcurrentHashMap<String, OvsdbClientService> org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.requestNotification protected
Initial value:
=
            new ConcurrentHashMap<String, OvsdbClientService>()
Definition at line 92 of file OvsdbControllerImpl.java.
InternalMonitorCallBack org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.updateCallback = new InternalMonitorCallBack() protected
Definition at line 87 of file OvsdbControllerImpl.java.
Referenced by org.onosproject.ovsdb.controller.impl.OvsdbControllerImpl.activate().
The documentation for this class was generated from the following file:
protocols/ovsdb/ctl/src/main/java/org/onosproject/ovsdb/controller/impl/OvsdbControllerImpl.java