onos: org.onosproject.net.group.GroupOperation Class Reference
org.onosproject.net.group.GroupOperation Class Reference
Group operation definition to be used between core and provider layers of group subsystem.
Classes
enum Type
Public Member Functions
Type opType ()
Returns group operation type.
GroupId groupId ()
Returns group identifier attribute of the operation.
GroupDescription.Type groupType ()
Returns group type attribute of the operation.
GroupBuckets buckets ()
Returns group buckets associated with the operation.
int hashCode ()
boolean equals (Object obj)
Static Public Member Functions
static GroupOperation createAddGroupOperation (GroupId groupId, GroupDescription.Type groupType, GroupBuckets buckets)
Creates ADD group operation object.
static GroupOperation createModifyGroupOperation (GroupId groupId, GroupDescription.Type groupType, GroupBuckets buckets)
Creates MODIFY group operation object.
static GroupOperation createDeleteGroupOperation (GroupId groupId, GroupDescription.Type groupType)
Creates DELETE group operation object.
Detailed Description
Group operation definition to be used between core and provider layers of group subsystem.
Definition at line 29 of file GroupOperation.java.
Member Function Documentation
GroupBuckets org.onosproject.net.group.GroupOperation.buckets ()
Returns group buckets associated with the operation.
Returns
GroupBuckets group buckets
Definition at line 144 of file GroupOperation.java.
Referenced by org.onosproject.net.group.GroupOperation.equals(), and org.onosproject.net.group.GroupOperation.hashCode().
static GroupOperation org.onosproject.net.group.GroupOperation.createAddGroupOperation (GroupId groupId, GroupDescription.Type groupType, GroupBuckets buckets) static
Creates ADD group operation object.
Parameters
groupId group Identifier
groupType type of the group
buckets immutable list of group buckets to be part of group
Returns
add group operation object
Definition at line 76 of file GroupOperation.java.
References org.onosproject.net.group.GroupOperation.Type.ADD, and org.onosproject.net.group.GroupOperation.groupType().
static GroupOperation org.onosproject.net.group.GroupOperation.createDeleteGroupOperation (GroupId groupId, GroupDescription.Type groupType) static
Creates DELETE group operation object.
Parameters
groupId group Identifier
groupType type of the group
Returns
delete group operation object
Definition at line 106 of file GroupOperation.java.
References org.onosproject.net.group.GroupOperation.Type.DELETE, and org.onosproject.net.group.GroupOperation.groupType().
static GroupOperation org.onosproject.net.group.GroupOperation.createModifyGroupOperation (GroupId groupId, GroupDescription.Type groupType, GroupBuckets buckets) static
Creates MODIFY group operation object.
Parameters
groupId group Identifier
groupType type of the group
buckets immutable list of group buckets to be part of group
Returns
modify group operation object
Definition at line 91 of file GroupOperation.java.
References org.onosproject.net.group.GroupOperation.groupType(), and org.onosproject.net.group.GroupOperation.Type.MODIFY.
boolean org.onosproject.net.group.GroupOperation.equals (Object obj)
Definition at line 167 of file GroupOperation.java.
References org.onosproject.net.group.GroupOperation.buckets(), org.onosproject.net.group.GroupOperation.groupId(), org.onosproject.net.group.GroupOperation.groupType(), and org.onosproject.net.group.GroupOperation.opType().
GroupId org.onosproject.net.group.GroupOperation.groupId ()
Returns group identifier attribute of the operation.
Returns
GroupId group identifier
Definition at line 126 of file GroupOperation.java.
Referenced by org.onosproject.net.group.GroupOperation.equals(), and org.onosproject.net.group.GroupOperation.hashCode().
GroupDescription.Type org.onosproject.net.group.GroupOperation.groupType ()
Returns group type attribute of the operation.
Returns
GroupType group type
Definition at line 135 of file GroupOperation.java.
Referenced by org.onosproject.net.group.GroupOperation.createAddGroupOperation(), org.onosproject.net.group.GroupOperation.createDeleteGroupOperation(), org.onosproject.net.group.GroupOperation.createModifyGroupOperation(), and org.onosproject.net.group.GroupOperation.equals().
int org.onosproject.net.group.GroupOperation.hashCode ()
Definition at line 155 of file GroupOperation.java.
References org.onosproject.net.group.GroupOperation.buckets(), org.onosproject.net.group.GroupOperation.groupId(), and org.onosproject.net.group.GroupOperation.opType().
Type org.onosproject.net.group.GroupOperation.opType ()
Returns group operation type.
Returns
GroupOpType group operation type
Definition at line 117 of file GroupOperation.java.
Referenced by org.onosproject.net.group.GroupOperation.equals(), and org.onosproject.net.group.GroupOperation.hashCode().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/group/GroupOperation.java