onos: org.onosproject.ovsdb.rfc.tableservice.TableDescription Class Reference
org.onosproject.ovsdb.rfc.tableservice.TableDescription Class Reference
Table description.
Public Member Functions
TableDescription (OvsdbTable table)
Constructs a MonitorRequest object.
TableDescription (OvsdbTable table, VersionNum fromVersion)
Constructs a MonitorRequest object.
TableDescription (OvsdbTable table, VersionNum fromVersion, VersionNum untilVersion)
Constructs a MonitorRequest object.
String name ()
Returns the column name.
String database ()
Returns the database name.
String fromVersion ()
Returns the initial version.
String untilVersion ()
Returns the end of the version.
Detailed Description
Table description.
Definition at line 27 of file TableDescription.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.tableservice.TableDescription.TableDescription (OvsdbTable table)
Constructs a MonitorRequest object.
Parameters
table OvsdbTable entity
Definition at line 42 of file TableDescription.java.
References org.onosproject.ovsdb.rfc.utils.VersionUtil.DEFAULT_VERSION_STRING.
org.onosproject.ovsdb.rfc.tableservice.TableDescription.TableDescription (OvsdbTable table, VersionNum fromVersion)
Constructs a MonitorRequest object.
Parameters
table OvsdbTable entity
fromVersion the initial version
Definition at line 54 of file TableDescription.java.
References org.onosproject.ovsdb.rfc.utils.VersionUtil.DEFAULT_VERSION_STRING.
org.onosproject.ovsdb.rfc.tableservice.TableDescription.TableDescription (OvsdbTable table, VersionNum fromVersion, VersionNum untilVersion)
Constructs a MonitorRequest object.
Parameters
table OvsdbTable entity
fromVersion the initial version
untilVersion the end of the version
Definition at line 68 of file TableDescription.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.tableservice.TableDescription.database ()
Returns the database name.
Returns
the database name
Definition at line 89 of file TableDescription.java.
String org.onosproject.ovsdb.rfc.tableservice.TableDescription.fromVersion ()
Returns the initial version.
Returns
the initial version
Definition at line 97 of file TableDescription.java.
String org.onosproject.ovsdb.rfc.tableservice.TableDescription.name ()
Returns the column name.
Returns
the column name
Definition at line 81 of file TableDescription.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.ovsdb.rfc.tableservice.TableDescription.untilVersion ()
Returns the end of the version.
Returns
the end of the version
Definition at line 105 of file TableDescription.java.
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/tableservice/TableDescription.java