onos: org.onosproject.net.flow.DefaultTypedFlowEntry Class Reference
org.onosproject.net.flow.DefaultTypedFlowEntry Class Reference
Default flow entry class with FlowLiveType value, IMMEDIATE_FLOW, SHORT_FLOW, MID_FLOW, LONG_FLOW.
Public Member Functions
DefaultTypedFlowEntry (FlowRule rule, FlowEntryState state, long life, long packets, long bytes)
Creates a typed flow entry from flow rule and its statistics, with default flow live type(IMMEDIATE_FLOW).
DefaultTypedFlowEntry (FlowRule rule)
Creates a typed flow entry from flow rule, with default flow live type(IMMEDIATE_FLOW).
DefaultTypedFlowEntry (FlowEntry fe)
Creates a typed flow entry from flow entry, with default flow live type(IMMEDIATE_FLOW).
DefaultTypedFlowEntry (FlowRule rule, FlowLiveType liveType)
Creates a typed flow entry from flow rule and flow live type.
DefaultTypedFlowEntry (FlowEntry fe, FlowLiveType liveType)
Creates a typed flow entry from flow entry and flow live type.
DefaultTypedFlowEntry (FlowRule rule, int errType, int errCode, FlowLiveType liveType)
Creates a typed flow entry from flow rule, error code and flow live type.
FlowLiveType flowLiveType ()
Gets the flow live type for this entry.
void setFlowLiveType (FlowLiveType liveType)
Sets the new flow live type for this entry.
String toString ()
Public Member Functions inherited from org.onosproject.net.flow.DefaultFlowEntry
DefaultFlowEntry (FlowRule rule, FlowEntryState state, long life, long packets, long bytes)
DefaultFlowEntry (FlowRule rule)
DefaultFlowEntry (FlowRule rule, int errType, int errCode)
long life ()
Returns the number of milliseconds this flow rule has been applied.
long packets ()
Returns the number of packets this flow rule has matched.
long bytes ()
Returns the number of bytes this flow rule has matched.
FlowEntryState state ()
Returns the flow entry state.
long lastSeen ()
When this flow entry was last deemed active.
void setLastSeen ()
Sets the last active epoch time.
void setState (FlowEntryState newState)
Sets the new state for this entry.
void setLife (long life)
Sets how long this entry has been entered in the system.
void setPackets (long packets)
Number of packets seen by this entry.
void setBytes (long bytes)
Number of bytes seen by this rule.
int errType ()
Indicates the error type.
int errCode ()
Indicates the error code.
String toString ()
Public Member Functions inherited from org.onosproject.net.flow.DefaultFlowRule
DefaultFlowRule (FlowRule rule)
DefaultFlowRule (DeviceId deviceId, TrafficSelector selector, TrafficTreatment treatment, int priority, ApplicationId appId, int timeout, boolean permanent, FlowRuleExtPayLoad payLoad)
Support for the third party flow rule.
DefaultFlowRule (DeviceId deviceId, TrafficSelector selector, TrafficTreatment treatment, int priority, ApplicationId appId, GroupId groupId, int timeout, boolean permanent, FlowRuleExtPayLoad payLoad)
Support for the third party flow rule.
FlowId id ()
Returns the ID of this flow.
short appId ()
Returns the application id of this flow.
GroupId groupId ()
Returns the group id of this flow.
int priority ()
Returns the flow rule priority given in natural order; higher numbers mean higher priorities.
DeviceId deviceId ()
Returns the identity of the device where this rule applies.
TrafficSelector selector ()
Returns the traffic selector that identifies what traffic this rule should apply to.
TrafficTreatment treatment ()
Returns the traffic treatment that applies to selected traffic.
int hashCode ()
boolean equals (Object obj)
Equality for flow rules only considers 'match equality'. This means that two flow rules with the same match conditions will be equal, regardless of the treatment or other characteristics of the flow.
Parameters
obj the reference object with which to compare.
Returns
true
if this object is the same as the obj argument;
false
otherwise.
boolean exactMatch (FlowRule rule)
Returns whether this flow rule is an exact match to the flow rule given in the argument.
String toString ()
int timeout ()
Returns the timeout for this flow requested by an application.
boolean isPermanent ()
Returns whether the flow is permanent i.e.
int tableId ()
Returns the table id for this rule.
FlowRuleExtPayLoad payLoad ()
Returns the third party original flow rule.
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.net.flow.DefaultFlowRule
static Builder builder ()
Public Attributes inherited from org.onosproject.net.flow.FlowRule
int MAX_TIMEOUT = 60
int MIN_PRIORITY = 0
Detailed Description
Default flow entry class with FlowLiveType value, IMMEDIATE_FLOW, SHORT_FLOW, MID_FLOW, LONG_FLOW.
Definition at line 24 of file DefaultTypedFlowEntry.java.
Constructor & Destructor Documentation
org.onosproject.net.flow.DefaultTypedFlowEntry.DefaultTypedFlowEntry (FlowRule rule, FlowEntryState state, long life, long packets, long bytes)
Creates a typed flow entry from flow rule and its statistics, with default flow live type(IMMEDIATE_FLOW).
Parameters
rule the flow rule
state the flow state
life the flow duration since creation
packets the flow packets count
bytes the flow bytes count
Definition at line 38 of file DefaultTypedFlowEntry.java.
References org.onosproject.net.flow.TypedStoredFlowEntry.FlowLiveType.IMMEDIATE_FLOW.
org.onosproject.net.flow.DefaultTypedFlowEntry.DefaultTypedFlowEntry (FlowRule rule)
Creates a typed flow entry from flow rule, with default flow live type(IMMEDIATE_FLOW).
Parameters
rule the flow rule
Definition at line 50 of file DefaultTypedFlowEntry.java.
References org.onosproject.net.flow.TypedStoredFlowEntry.FlowLiveType.IMMEDIATE_FLOW.
org.onosproject.net.flow.DefaultTypedFlowEntry.DefaultTypedFlowEntry (FlowEntry fe)
Creates a typed flow entry from flow entry, with default flow live type(IMMEDIATE_FLOW).
Parameters
fe the flow entry
Definition at line 61 of file DefaultTypedFlowEntry.java.
References org.onosproject.net.flow.TypedStoredFlowEntry.FlowLiveType.IMMEDIATE_FLOW, org.onosproject.net.flow.FlowEntry.packets(), and org.onosproject.net.flow.FlowEntry.state().
org.onosproject.net.flow.DefaultTypedFlowEntry.DefaultTypedFlowEntry (FlowRule rule, FlowLiveType liveType)
Creates a typed flow entry from flow rule and flow live type.
Parameters
rule the flow rule
liveType the flow live type
Definition at line 73 of file DefaultTypedFlowEntry.java.
org.onosproject.net.flow.DefaultTypedFlowEntry.DefaultTypedFlowEntry (FlowEntry fe, FlowLiveType liveType)
Creates a typed flow entry from flow entry and flow live type.
Parameters
fe the flow rule
liveType the flow live type
Definition at line 85 of file DefaultTypedFlowEntry.java.
References org.onosproject.net.flow.FlowEntry.packets(), and org.onosproject.net.flow.FlowEntry.state().
org.onosproject.net.flow.DefaultTypedFlowEntry.DefaultTypedFlowEntry (FlowRule rule, int errType, int errCode, FlowLiveType liveType)
Creates a typed flow entry from flow rule, error code and flow live type.
Parameters
rule the flow rule
errType the flow error type
errCode the flow error code
liveType the flow live type
Definition at line 99 of file DefaultTypedFlowEntry.java.
Member Function Documentation
FlowLiveType org.onosproject.net.flow.DefaultTypedFlowEntry.flowLiveType ()
Gets the flow live type for this entry.
Returns
flow live type
Implements org.onosproject.net.flow.TypedStoredFlowEntry.
Definition at line 105 of file DefaultTypedFlowEntry.java.
void org.onosproject.net.flow.DefaultTypedFlowEntry.setFlowLiveType (FlowLiveType liveType)
Sets the new flow live type for this entry.
Parameters
liveType new flow live type.
Implements org.onosproject.net.flow.TypedStoredFlowEntry.
Definition at line 110 of file DefaultTypedFlowEntry.java.
String org.onosproject.net.flow.DefaultTypedFlowEntry.toString ()
Definition at line 115 of file DefaultTypedFlowEntry.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/DefaultTypedFlowEntry.java