onos: org.onosproject.net.driver.DefaultDriverTest Class Reference
org.onosproject.net.driver.DefaultDriverTest Class Reference
Public Member Functions
void basics ()
void merge ()
Detailed Description
Definition at line 25 of file DefaultDriverTest.java.
Member Function Documentation
void org.onosproject.net.driver.DefaultDriverTest.basics ()
Definition at line 28 of file DefaultDriverTest.java.
References org.onosproject.net.driver.DefaultDriver.hasBehaviour(), org.onosproject.net.driver.DefaultDriver.keys(), org.onosproject.net.driver.DefaultDriver.toString(), and org.onosproject.net.driver.DefaultDriver.value().
void org.onosproject.net.driver.DefaultDriverTest.merge ()
Definition at line 64 of file DefaultDriverTest.java.
References org.onosproject.net.driver.Driver.behaviours(), org.onosproject.net.driver.Driver.hasBehaviour(), org.onosproject.net.driver.Driver.hwVersion(), org.onosproject.net.Annotations.keys(), org.onosproject.net.driver.Driver.manufacturer(), org.onosproject.net.driver.Driver.name(), org.onosproject.net.driver.Driver.properties(), org.onosproject.net.driver.Driver.swVersion(), and org.onosproject.net.Annotations.value().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/driver/DefaultDriverTest.java