onos: org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData Class Reference
org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData Class Reference
Implements BGP prefix opaque data attribute.
Public Member Functions
BgpPrefixAttrOpaqueData (byte[] opaquePrefixAttribute)
Constructor to initialize the values.
byte[] getOpaquePrefixAttribute ()
Returns the Opaque prefix attribute name.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpPrefixAttrOpaqueData of (final byte[] opaquePrefixAttribute)
Returns object of this class with specified values.
static BgpPrefixAttrOpaqueData read (ChannelBuffer cb) throws BgpParseException
Reads the Opaque Prefix Attribute.
Static Public Attributes
static final int ATTR_PREFIX_OPAQUEDATA = 1157
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP prefix opaque data attribute.
Definition at line 33 of file BgpPrefixAttrOpaqueData.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.BgpPrefixAttrOpaqueData (byte[] opaquePrefixAttribute)
Constructor to initialize the values.
Parameters
opaquePrefixAttribute opaque prefix data
Definition at line 48 of file BgpPrefixAttrOpaqueData.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.equals(), and org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.of().
Member Function Documentation
int org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 135 of file BgpPrefixAttrOpaqueData.java.
boolean org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.equals (Object obj)
Definition at line 108 of file BgpPrefixAttrOpaqueData.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.BgpPrefixAttrOpaqueData().
byte [] org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.getOpaquePrefixAttribute ()
Returns the Opaque prefix attribute name.
Returns
opaque prefix name
Definition at line 93 of file BgpPrefixAttrOpaqueData.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.toString().
short org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 98 of file BgpPrefixAttrOpaqueData.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.ATTR_PREFIX_OPAQUEDATA.
int org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.hashCode ()
Definition at line 103 of file BgpPrefixAttrOpaqueData.java.
static BgpPrefixAttrOpaqueData org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.of (final byte[] opaquePrefixAttribute) static
Returns object of this class with specified values.
Parameters
opaquePrefixAttribute opaque prefix data
Returns
object of BgpPrefixAttrOpaqueData
Definition at line 59 of file BgpPrefixAttrOpaqueData.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.BgpPrefixAttrOpaqueData().
static BgpPrefixAttrOpaqueData org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.read (ChannelBuffer cb) throws BgpParseException static
Reads the Opaque Prefix Attribute.
Parameters
cb ChannelBuffer
Returns
object of BgpPrefixAttrOpaqueData
Exceptions
BgpParseException while parsing BgpPrefixAttrOpaqueData
Definition at line 70 of file BgpPrefixAttrOpaqueData.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.toString ()
Definition at line 128 of file BgpPrefixAttrOpaqueData.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.getOpaquePrefixAttribute().
int org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 122 of file BgpPrefixAttrOpaqueData.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.ATTR_PREFIX_OPAQUEDATA = 1157 static
Definition at line 38 of file BgpPrefixAttrOpaqueData.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.getType().
final Logger org.onosproject.bgpio.types.attr.BgpPrefixAttrOpaqueData.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpPrefixAttrOpaqueData.class)
Definition at line 35 of file BgpPrefixAttrOpaqueData.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpPrefixAttrOpaqueData.java