onos: org.onosproject.net.NetTools Class Reference
org.onosproject.net.NetTools Class Reference
Networking domain tools.
Static Public Member Functions
static String dpidToUri (String dpid)
Converts DPIDs of the form xx:xx:xx:xx:xx:xx:xx to OpenFlow provider device URIs.
Detailed Description
Networking domain tools.
Definition at line 21 of file NetTools.java.
Member Function Documentation
static String org.onosproject.net.NetTools.dpidToUri (String dpid) static
Converts DPIDs of the form xx:xx:xx:xx:xx:xx:xx to OpenFlow provider device URIs.
The is helpful for converting DPIDs coming from configuration or REST to URIs that the core understands.
Parameters
dpid the DPID string to convert
Returns
the URI string for this device
Definition at line 34 of file NetTools.java.
Referenced by org.onosproject.routing.config.BgpPeer.BgpPeer(), org.onosproject.routing.config.BgpSpeaker.BgpSpeaker(), and org.onosproject.routing.config.InterfaceAddress.InterfaceAddress().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/NetTools.java