onos: org.onosproject.codec.impl.DeviceCodec Class Reference
org.onosproject.codec.impl.DeviceCodec Class Reference
Device JSON codec.
Public Member Functions
ObjectNode encode (Device device, CodecContext context)
Device decode (ObjectNode json, CodecContext context)
Detailed Description
Device JSON codec.
Definition at line 36 of file DeviceCodec.java.
Member Function Documentation
Device org.onosproject.codec.impl.DeviceCodec.decode (ObjectNode json, CodecContext context)
Note: ProviderId is not part of JSON representation. Returned object will have random ProviderId set.
Definition at line 73 of file DeviceCodec.java.
References find-flow.deviceId.
ObjectNode org.onosproject.codec.impl.DeviceCodec.encode (Device device, CodecContext context)
Definition at line 49 of file DeviceCodec.java.
References org.onosproject.net.Device.chassisId(), org.onosproject.net.device.DeviceService.getRole(), org.onosproject.net.Device.hwVersion(), org.onosproject.net.Device.id(), org.onosproject.net.Device.manufacturer(), org.onosproject.net.Device.serialNumber(), org.onosproject.net.Device.swVersion(), and org.onosproject.net.Device.type().
The documentation for this class was generated from the following file:
core/common/src/main/java/org/onosproject/codec/impl/DeviceCodec.java