onos: org.onosproject.ui.UiTopoOverlay Class Reference
org.onosproject.ui.UiTopoOverlay Class Reference
Represents user interface topology view overlay.
Public Member Functions
UiTopoOverlay (String id)
Creates a new user interface topology view overlay descriptor.
String id ()
Returns the identifier for this overlay.
void init ()
Callback invoked to initialize this overlay, soon after creation.
void activate ()
Callback invoked when this overlay is activated.
void deactivate ()
Callback invoked when this overlay is deactivated.
boolean isActive ()
Returns true if this overlay is currently active.
void destroy ()
Callback invoked to destroy this instance by cleaning up any internal state ready for garbage collection.
void modifySummary (PropertyPanel pp)
Callback to modify the contents of the summary panel.
void modifyDeviceDetails (PropertyPanel pp, DeviceId deviceId)
Callback to modify the contents of the details panel for a selected device.
void modifyHostDetails (PropertyPanel pp, HostId hostId)
Callback to modify the contents of the details panel for a selected host.
Protected Attributes
final Logger log = LoggerFactory.getLogger(getClass())
Logger for this overlay.
Detailed Description
Represents user interface topology view overlay.
Definition at line 28 of file UiTopoOverlay.java.
Constructor & Destructor Documentation
org.onosproject.ui.UiTopoOverlay.UiTopoOverlay (String id)
Creates a new user interface topology view overlay descriptor.
Parameters
id overlay identifier
Definition at line 44 of file UiTopoOverlay.java.
References org.onosproject.ui.UiTopoOverlay.id().
Member Function Documentation
void org.onosproject.ui.UiTopoOverlay.activate ()
Callback invoked when this overlay is activated.
Definition at line 67 of file UiTopoOverlay.java.
References org.onosproject.ui.UiTopoOverlay.isActive().
void org.onosproject.ui.UiTopoOverlay.deactivate ()
Callback invoked when this overlay is deactivated.
Definition at line 74 of file UiTopoOverlay.java.
References org.onosproject.ui.UiTopoOverlay.isActive().
void org.onosproject.ui.UiTopoOverlay.destroy ()
Callback invoked to destroy this instance by cleaning up any internal state ready for garbage collection.
This default implementation holds no state and does nothing.
Definition at line 92 of file UiTopoOverlay.java.
String org.onosproject.ui.UiTopoOverlay.id ()
Returns the identifier for this overlay.
Returns
the identifier
Definition at line 53 of file UiTopoOverlay.java.
Referenced by org.onosproject.ui.UiTopoOverlay.UiTopoOverlay().
void org.onosproject.ui.UiTopoOverlay.init ()
Callback invoked to initialize this overlay, soon after creation.
This default implementation does nothing.
Definition at line 61 of file UiTopoOverlay.java.
boolean org.onosproject.ui.UiTopoOverlay.isActive ()
Returns true if this overlay is currently active.
Returns
true if overlay active
Definition at line 83 of file UiTopoOverlay.java.
Referenced by org.onosproject.ui.UiTopoOverlay.activate(), and org.onosproject.ui.UiTopoOverlay.deactivate().
void org.onosproject.ui.UiTopoOverlay.modifyDeviceDetails (PropertyPanel pp, DeviceId deviceId)
Callback to modify the contents of the details panel for a selected device.
This default implementation does nothing.
Parameters
pp property panel model of summary data
deviceId device id
Definition at line 112 of file UiTopoOverlay.java.
void org.onosproject.ui.UiTopoOverlay.modifyHostDetails (PropertyPanel pp, HostId hostId)
Callback to modify the contents of the details panel for a selected host.
This default implementation does nothing.
Parameters
pp property panel model of summary data
hostId host id
Definition at line 123 of file UiTopoOverlay.java.
void org.onosproject.ui.UiTopoOverlay.modifySummary (PropertyPanel pp)
Callback to modify the contents of the summary panel.
This default implementation does nothing.
Parameters
pp property panel model of summary data
Definition at line 101 of file UiTopoOverlay.java.
Member Data Documentation
final Logger org.onosproject.ui.UiTopoOverlay.log = LoggerFactory.getLogger(getClass()) protected
Logger for this overlay.
Definition at line 33 of file UiTopoOverlay.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/UiTopoOverlay.java