onos: org.onosproject.net.statistic.DefaultLoad Class Reference
org.onosproject.net.statistic.DefaultLoad Class Reference
Implementation of a load.
Public Member Functions
DefaultLoad ()
Creates an invalid load.
DefaultLoad (long current, long previous)
Creates a load value from the parameters.
DefaultLoad (long current, long previous, long interval)
Creates a load value from the parameters.
long rate ()
Obtain the current observed rate (in bytes/s) on a link.
long latest ()
Obtain the latest bytes counter viewed on that link.
boolean isValid ()
Indicates whether this load was built on valid values.
long time ()
Returns when this value was seen.
String toString ()
Static Public Member Functions
static void setPollInterval (long newPollInterval)
Sets the poll interval in seconds.
Detailed Description
Implementation of a load.
Definition at line 25 of file DefaultLoad.java.
Constructor & Destructor Documentation
org.onosproject.net.statistic.DefaultLoad.DefaultLoad ()
Creates an invalid load.
Definition at line 41 of file DefaultLoad.java.
org.onosproject.net.statistic.DefaultLoad.DefaultLoad (long current, long previous)
Creates a load value from the parameters.
Parameters
current the current value
previous the previous value
Definition at line 55 of file DefaultLoad.java.
org.onosproject.net.statistic.DefaultLoad.DefaultLoad (long current, long previous, long interval)
Creates a load value from the parameters.
Parameters
current the current value
previous the previous value
interval poll interval for this load
Definition at line 66 of file DefaultLoad.java.
Member Function Documentation
boolean org.onosproject.net.statistic.DefaultLoad.isValid ()
Indicates whether this load was built on valid values.
Returns
boolean
Implements org.onosproject.net.statistic.Load.
Definition at line 96 of file DefaultLoad.java.
long org.onosproject.net.statistic.DefaultLoad.latest ()
Obtain the latest bytes counter viewed on that link.
Returns
long value
Implements org.onosproject.net.statistic.Load.
Definition at line 91 of file DefaultLoad.java.
Referenced by org.onosproject.net.statistic.DefaultLoadTest.testCurrentPreviousConstructor(), org.onosproject.net.statistic.DefaultLoadTest.testCurrentPreviousIntervalConstructor(), org.onosproject.net.statistic.DefaultLoadTest.testDefaultConstructor(), and org.onosproject.net.statistic.DefaultLoad.toString().
long org.onosproject.net.statistic.DefaultLoad.rate ()
Obtain the current observed rate (in bytes/s) on a link.
Returns
long value
Implements org.onosproject.net.statistic.Load.
Definition at line 86 of file DefaultLoad.java.
Referenced by org.onosproject.net.statistic.DefaultLoadTest.testCurrentPreviousConstructor(), org.onosproject.net.statistic.DefaultLoadTest.testCurrentPreviousIntervalConstructor(), org.onosproject.net.statistic.DefaultLoadTest.testDefaultConstructor(), and org.onosproject.net.statistic.DefaultLoad.toString().
static void org.onosproject.net.statistic.DefaultLoad.setPollInterval (long newPollInterval) static
Sets the poll interval in seconds.
Used solely for the purpose of computing the load.
Parameters
newPollInterval poll interval duration in seconds
Definition at line 81 of file DefaultLoad.java.
long org.onosproject.net.statistic.DefaultLoad.time ()
Returns when this value was seen.
Returns
epoch time
Implements org.onosproject.net.statistic.Load.
Definition at line 101 of file DefaultLoad.java.
String org.onosproject.net.statistic.DefaultLoad.toString ()
Definition at line 106 of file DefaultLoad.java.
References org.onosproject.net.statistic.DefaultLoad.latest(), and org.onosproject.net.statistic.DefaultLoad.rate().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/statistic/DefaultLoad.java