onos: org.onlab.graph.SuurballeGraphSearchTest Class Reference
org.onlab.graph.SuurballeGraphSearchTest Class Reference
Test of the Suurballe backup path algorithm.
Public Member Functions
void setWeights ()
void setDefaultWeights ()
void defaultGraphTest ()
void defaultHopCountWeight ()
void basicGraphTest ()
void multiplePathOnePairGraphTest ()
void multiplePathsMultiplePairs ()
void differingPrimaryAndBackupPathLengths ()
void onePath ()
void noPath ()
void disconnected ()
Public Member Functions inherited from org.onlab.graph.BreadthFirstSearchTest
void defaultGraphTest ()
void defaultHopCountWeight ()
Public Member Functions inherited from org.onlab.graph.AbstractGraphPathSearchTest
void noSuchSourceArgument ()
void nullGraphArgument ()
void nullSourceArgument ()
void samenessThreshold ()
Protected Member Functions
AbstractGraphPathSearch
< TestVertex, TestEdge > graphSearch ()
Creates a test-specific graph search to exercise.
Protected Member Functions inherited from org.onlab.graph.BreadthFirstSearchTest
void executeDefaultTest (int pathCount, int pathLength, double pathCost)
void executeSearch (GraphPathSearch< TestVertex, TestEdge > search, Graph< TestVertex, TestEdge > graph, TestVertex src, TestVertex dst, EdgeWeight< TestVertex, TestEdge > weight, int pathCount, double pathCost)
void executeSinglePathSearch (GraphPathSearch< TestVertex, TestEdge > search, Graph< TestVertex, TestEdge > graph, TestVertex src, TestVertex dst, EdgeWeight< TestVertex, TestEdge > weight, int pathCount, double pathCost)
Protected Member Functions inherited from org.onlab.graph.GraphTest
void printPaths (Set< Path< TestVertex, TestEdge >> paths)
Set< TestVertex > vertexes ()
Set< TestEdge > edges ()
Additional Inherited Members
Protected Attributes inherited from org.onlab.graph.GraphTest
Graph< TestVertex, TestEdge > graph
EdgeWeight< TestVertex, TestEdge > weight
Detailed Description
Test of the Suurballe backup path algorithm.
Definition at line 30 of file SuurballeGraphSearchTest.java.
Member Function Documentation
void org.onlab.graph.SuurballeGraphSearchTest.basicGraphTest ()
Definition at line 59 of file SuurballeGraphSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeSearch(), org.onlab.graph.GraphTest.graph, org.onlab.graph.SuurballeGraphSearchTest.graphSearch(), org.onlab.graph.SuurballeGraphSearchTest.setDefaultWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SuurballeGraphSearchTest.defaultGraphTest ()
Definition at line 49 of file SuurballeGraphSearchTest.java.
void org.onlab.graph.SuurballeGraphSearchTest.defaultHopCountWeight ()
Definition at line 54 of file SuurballeGraphSearchTest.java.
void org.onlab.graph.SuurballeGraphSearchTest.differingPrimaryAndBackupPathLengths ()
Definition at line 103 of file SuurballeGraphSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeSearch(), org.onlab.graph.GraphTest.graph, org.onlab.graph.SuurballeGraphSearchTest.graphSearch(), org.onlab.graph.SuurballeGraphSearchTest.setWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SuurballeGraphSearchTest.disconnected ()
Definition at line 145 of file SuurballeGraphSearchTest.java.
References org.onlab.graph.GraphTest.graph, org.onlab.graph.SuurballeGraphSearchTest.graphSearch(), org.onlab.graph.SuurballeGraphSearchTest.setWeights(), and org.onlab.graph.GraphTest.weight.
AbstractGraphPathSearch<TestVertex, TestEdge> org.onlab.graph.SuurballeGraphSearchTest.graphSearch () protected virtual
Creates a test-specific graph search to exercise.
Returns
graph search
Reimplemented from org.onlab.graph.BreadthFirstSearchTest.
Definition at line 33 of file SuurballeGraphSearchTest.java.
Referenced by org.onlab.graph.SuurballeGraphSearchTest.basicGraphTest(), org.onlab.graph.SuurballeGraphSearchTest.differingPrimaryAndBackupPathLengths(), org.onlab.graph.SuurballeGraphSearchTest.disconnected(), org.onlab.graph.SuurballeGraphSearchTest.multiplePathOnePairGraphTest(), org.onlab.graph.SuurballeGraphSearchTest.multiplePathsMultiplePairs(), org.onlab.graph.SuurballeGraphSearchTest.noPath(), and org.onlab.graph.SuurballeGraphSearchTest.onePath().
void org.onlab.graph.SuurballeGraphSearchTest.multiplePathOnePairGraphTest ()
Definition at line 70 of file SuurballeGraphSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeSearch(), org.onlab.graph.GraphTest.graph, org.onlab.graph.SuurballeGraphSearchTest.graphSearch(), org.onlab.graph.SuurballeGraphSearchTest.setWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SuurballeGraphSearchTest.multiplePathsMultiplePairs ()
Definition at line 83 of file SuurballeGraphSearchTest.java.
References org.onlab.graph.GraphTest.graph, org.onlab.graph.SuurballeGraphSearchTest.graphSearch(), org.onlab.graph.SuurballeGraphSearchTest.setWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SuurballeGraphSearchTest.noPath ()
Definition at line 132 of file SuurballeGraphSearchTest.java.
References org.onlab.graph.GraphTest.graph, org.onlab.graph.SuurballeGraphSearchTest.graphSearch(), org.onlab.graph.SuurballeGraphSearchTest.setWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SuurballeGraphSearchTest.onePath ()
Definition at line 116 of file SuurballeGraphSearchTest.java.
References org.onlab.graph.GraphTest.graph, org.onlab.graph.SuurballeGraphSearchTest.graphSearch(), org.onlab.graph.SuurballeGraphSearchTest.setWeights(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.SuurballeGraphSearchTest.setDefaultWeights ()
Definition at line 45 of file SuurballeGraphSearchTest.java.
References org.onlab.graph.GraphTest.weight.
Referenced by org.onlab.graph.SuurballeGraphSearchTest.basicGraphTest().
void org.onlab.graph.SuurballeGraphSearchTest.setWeights ()
Definition at line 37 of file SuurballeGraphSearchTest.java.
References org.onlab.graph.GraphTest.weight.
Referenced by org.onlab.graph.SuurballeGraphSearchTest.differingPrimaryAndBackupPathLengths(), org.onlab.graph.SuurballeGraphSearchTest.disconnected(), org.onlab.graph.SuurballeGraphSearchTest.multiplePathOnePairGraphTest(), org.onlab.graph.SuurballeGraphSearchTest.multiplePathsMultiplePairs(), org.onlab.graph.SuurballeGraphSearchTest.noPath(), and org.onlab.graph.SuurballeGraphSearchTest.onePath().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/graph/SuurballeGraphSearchTest.java