onos: org.onosproject.ui.impl.TopologyViewMessageHandlerBase Class Reference
org.onosproject.ui.impl.TopologyViewMessageHandlerBase Class Reference
Facility for creating messages bound for the topology viewer.
Public Member Functions
void init (UiConnection connection, ServiceDirectory directory)
Public Member Functions inherited from org.onosproject.ui.UiMessageHandler
Set< String > messageTypes ()
Returns the set of message types which this handler is capable of processing.
void process (ObjectNode message)
Processes a JSON message from the user interface client.
void init (UiConnection connection, ServiceDirectory directory)
Initializes the handler with the user interface connection and service directory context.
void destroy ()
Destroys the message handler context.
UiConnection connection ()
Returns the user interface connection with which this handler was primed.
ServiceDirectory directory ()
Returns the user interface connection with which this handler was primed.
Protected Member Functions
ObjectNode info (long id, String message)
ObjectNode warning (long id, String message)
ObjectNode error (long id, String message)
ObjectNode instanceMessage (ClusterEvent event, String msgType)
ObjectNode deviceMessage (DeviceEvent event)
ObjectNode linkMessage (LinkEvent event)
ObjectNode hostMessage (HostEvent event)
void updateMetaUi (ObjectNode payload)
PropertyPanel summmaryMessage (long sid)
PropertyPanel deviceDetails (DeviceId deviceId, long sid)
int getFlowCount (DeviceId deviceId)
int getTunnelCount (DeviceId deviceId)
PropertyPanel hostDetails (HostId hostId, long sid)
Protected Member Functions inherited from org.onosproject.ui.UiMessageHandler
abstract Collection
< RequestHandler > createRequestHandlers ()
Subclasses must create and return the collection of request handlers for the message types they handle.
ObjectNode objectNode ()
Returns a freshly minted object node.
ArrayNode arrayNode ()
Returns a freshly minted array node.
synchronized void sendMessage (ObjectNode data)
Sends the specified data to the client.
Protected Attributes
ServiceDirectory directory
ClusterService clusterService
DeviceService deviceService
LinkService linkService
HostService hostService
MastershipService mastershipService
IntentService intentService
FlowRuleService flowService
StatisticService flowStatsService
PortStatisticsService portStatsService
TopologyService topologyService
TunnelService tunnelService
ServicesBundle servicesBundle
Static Protected Attributes
static final Logger log
static final String SHOW_HIGHLIGHTS = "showHighlights"
Detailed Description
Facility for creating messages bound for the topology viewer.
Definition at line 94 of file TopologyViewMessageHandlerBase.java.
Member Function Documentation
PropertyPanel org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceDetails (DeviceId deviceId, long sid) protected
Definition at line 401 of file TopologyViewMessageHandlerBase.java.
References create-flow.device, find-flow.deviceId, org.onosproject.ui.impl.TopologyViewMessageHandlerBase.getFlowCount(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.getTunnelCount(), org.onosproject.net.AnnotationKeys.LATITUDE, org.onosproject.net.AnnotationKeys.LONGITUDE, create-flow.name, org.onosproject.net.AnnotationKeys.NAME, org.onosproject.net.AnnotationKeys.PROTOCOL, and onos.size.
ObjectNode org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceMessage (DeviceEvent event) protected
Definition at line 250 of file TopologyViewMessageHandlerBase.java.
References org.onosproject.net.Annotated.annotations(), org.onosproject.ui.UiMessageHandler.arrayNode(), create-flow.device, org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceService, org.onosproject.net.Device.id(), org.onosproject.net.device.DeviceService.isAvailable(), create-flow.name, org.onosproject.net.AnnotationKeys.NAME, org.onosproject.ui.UiMessageHandler.objectNode(), and org.onosproject.net.Device.type().
ObjectNode org.onosproject.ui.impl.TopologyViewMessageHandlerBase.error (long id, String message) protected
Definition at line 213 of file TopologyViewMessageHandlerBase.java.
int org.onosproject.ui.impl.TopologyViewMessageHandlerBase.getFlowCount (DeviceId deviceId) protected
Definition at line 439 of file TopologyViewMessageHandlerBase.java.
References org.onosproject.ui.impl.TopologyViewMessageHandlerBase.flowService, and org.onosproject.net.flow.FlowRuleService.getFlowEntries().
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceDetails().
int org.onosproject.ui.impl.TopologyViewMessageHandlerBase.getTunnelCount (DeviceId deviceId) protected
Definition at line 447 of file TopologyViewMessageHandlerBase.java.
References org.onosproject.incubator.net.tunnel.OpticalTunnelEndPoint.elementId(), and org.onosproject.net.DeviceId.toString().
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceDetails().
PropertyPanel org.onosproject.ui.impl.TopologyViewMessageHandlerBase.hostDetails (HostId hostId, long sid) protected
Definition at line 505 of file TopologyViewMessageHandlerBase.java.
References org.onosproject.net.AnnotationKeys.LATITUDE, org.onosproject.net.AnnotationKeys.LONGITUDE, solar.MAC, create-flow.name, org.onosproject.net.AnnotationKeys.NAME, and org.onosproject.net.AnnotationKeys.TYPE.
ObjectNode org.onosproject.ui.impl.TopologyViewMessageHandlerBase.hostMessage (HostEvent event) protected
Definition at line 292 of file TopologyViewMessageHandlerBase.java.
References org.onosproject.net.Annotated.annotations(), org.onosproject.net.Host.id(), org.onosproject.net.Host.ipAddresses(), org.onosproject.net.Host.location(), org.onosproject.net.Host.mac(), org.onosproject.ui.UiMessageHandler.objectNode(), and org.onosproject.net.AnnotationKeys.TYPE.
ObjectNode org.onosproject.ui.impl.TopologyViewMessageHandlerBase.info (long id, String message) protected
Definition at line 203 of file TopologyViewMessageHandlerBase.java.
void org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init (UiConnection connection, ServiceDirectory directory)
Definition at line 161 of file TopologyViewMessageHandlerBase.java.
References org.onosproject.ui.impl.TopologyViewMessageHandlerBase.clusterService, org.onosproject.ui.UiMessageHandler.connection(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceService, org.onosproject.ui.UiMessageHandler.directory(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.flowService, org.onosproject.ui.impl.TopologyViewMessageHandlerBase.flowStatsService, org.onosproject.ui.impl.TopologyViewMessageHandlerBase.hostService, org.onosproject.ui.impl.TopologyViewMessageHandlerBase.intentService, org.onosproject.ui.impl.TopologyViewMessageHandlerBase.linkService, org.onosproject.ui.impl.TopologyViewMessageHandlerBase.mastershipService, org.onosproject.ui.impl.TopologyViewMessageHandlerBase.portStatsService, org.onosproject.ui.impl.TopologyViewMessageHandlerBase.servicesBundle, org.onosproject.ui.impl.TopologyViewMessageHandlerBase.topologyService, and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.tunnelService.
ObjectNode org.onosproject.ui.impl.TopologyViewMessageHandlerBase.instanceMessage (ClusterEvent event, String msgType) protected
Definition at line 227 of file TopologyViewMessageHandlerBase.java.
References org.onosproject.ui.UiMessageHandler.arrayNode(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.clusterService, org.onosproject.cluster.ClusterService.getLocalNode(), org.onosproject.cluster.ControllerNode.id(), org.onosproject.cluster.ControllerNode.ip(), create-flow.node, and org.onosproject.ui.UiMessageHandler.objectNode().
ObjectNode org.onosproject.ui.impl.TopologyViewMessageHandlerBase.linkMessage (LinkEvent event) protected
Definition at line 276 of file TopologyViewMessageHandlerBase.java.
References find-flow.deviceId, org.onosproject.ui.UiMessageHandler.objectNode(), obeliskHostCheck.port, org.onosproject.net.Link.state(), and org.onosproject.net.Link.type().
PropertyPanel org.onosproject.ui.impl.TopologyViewMessageHandlerBase.summmaryMessage (long sid) protected
Definition at line 385 of file TopologyViewMessageHandlerBase.java.
References org.onosproject.ui.impl.TopologyViewMessageHandlerBase.flowService, org.onosproject.net.flow.FlowRuleService.getFlowRuleCount(), org.onosproject.net.intent.IntentService.getIntentCount(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.intentService, org.onosproject.incubator.net.tunnel.TunnelService.tunnelCount(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.tunnelService.
void org.onosproject.ui.impl.TopologyViewMessageHandlerBase.updateMetaUi (ObjectNode payload) protected
Definition at line 375 of file TopologyViewMessageHandlerBase.java.
References org.onosproject.ui.JsonUtils.node().
ObjectNode org.onosproject.ui.impl.TopologyViewMessageHandlerBase.warning (long id, String message) protected
Definition at line 208 of file TopologyViewMessageHandlerBase.java.
Member Data Documentation
ClusterService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.clusterService protected
Definition at line 132 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.instanceMessage().
DeviceService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceService protected
Definition at line 133 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceMessage(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init().
ServiceDirectory org.onosproject.ui.impl.TopologyViewMessageHandlerBase.directory protected
Definition at line 131 of file TopologyViewMessageHandlerBase.java.
FlowRuleService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.flowService protected
Definition at line 138 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.getFlowCount(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.summmaryMessage().
StatisticService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.flowStatsService protected
Definition at line 139 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init().
HostService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.hostService protected
Definition at line 135 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init().
IntentService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.intentService protected
Definition at line 137 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.summmaryMessage().
LinkService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.linkService protected
Definition at line 134 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init().
final Logger org.onosproject.ui.impl.TopologyViewMessageHandlerBase.log static protected
Initial value:
=
            LoggerFactory.getLogger(TopologyViewMessageHandlerBase.class)
Definition at line 123 of file TopologyViewMessageHandlerBase.java.
MastershipService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.mastershipService protected
Definition at line 136 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init().
PortStatisticsService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.portStatsService protected
Definition at line 140 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init().
ServicesBundle org.onosproject.ui.impl.TopologyViewMessageHandlerBase.servicesBundle protected
Definition at line 144 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init(), and org.onosproject.ui.impl.TopologyViewMessageHandler.init().
final String org.onosproject.ui.impl.TopologyViewMessageHandlerBase.SHOW_HIGHLIGHTS = "showHighlights" static protected
Definition at line 129 of file TopologyViewMessageHandlerBase.java.
TopologyService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.topologyService protected
Definition at line 141 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init().
TunnelService org.onosproject.ui.impl.TopologyViewMessageHandlerBase.tunnelService protected
Definition at line 142 of file TopologyViewMessageHandlerBase.java.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.init(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.summmaryMessage().
The documentation for this class was generated from the following file:
web/gui/src/main/java/org/onosproject/ui/impl/TopologyViewMessageHandlerBase.java