onos: org.onosproject.net.host.DefaultHostDescription Class Reference
org.onosproject.net.host.DefaultHostDescription Class Reference
Default implementation of an immutable host description.
Public Member Functions
DefaultHostDescription (MacAddress mac, VlanId vlan, HostLocation location, SparseAnnotations...annotations)
Creates a host description using the supplied information.
DefaultHostDescription (MacAddress mac, VlanId vlan, HostLocation location, IpAddress ip, SparseAnnotations...annotations)
Creates a host description using the supplied information.
DefaultHostDescription (MacAddress mac, VlanId vlan, HostLocation location, Set< IpAddress > ip, SparseAnnotations...annotations)
Creates a host description using the supplied information.
MacAddress hwAddress ()
Returns the MAC address associated with this host (NIC).
VlanId vlan ()
Returns the VLAN associated with this host.
HostLocation location ()
Returns the location of the host on the network edge.
Set< IpAddress > ipAddress ()
Returns the IP address associated with this host's MAC.
String toString ()
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.AbstractDescription
SparseAnnotations annotations ()
Returns the key/value annotations.
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractDescription
AbstractDescription ()
AbstractDescription (SparseAnnotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of an immutable host description.
Definition at line 36 of file DefaultHostDescription.java.
Constructor & Destructor Documentation
org.onosproject.net.host.DefaultHostDescription.DefaultHostDescription (MacAddress mac, VlanId vlan, HostLocation location, SparseAnnotations... annotations)
Creates a host description using the supplied information.
Parameters
mac host MAC address
vlan host VLAN identifier
location host location
annotations optional key/value annotations map
Definition at line 52 of file DefaultHostDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.host.DefaultHostDescription.location(), and org.onosproject.net.host.DefaultHostDescription.vlan().
Referenced by org.onosproject.net.host.DefaultHostDescription.equals().
org.onosproject.net.host.DefaultHostDescription.DefaultHostDescription (MacAddress mac, VlanId vlan, HostLocation location, IpAddress ip, SparseAnnotations... annotations)
Creates a host description using the supplied information.
Parameters
mac host MAC address
vlan host VLAN identifier
location host location
ip host IP address
annotations optional key/value annotations map
Definition at line 68 of file DefaultHostDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.host.DefaultHostDescription.location(), and org.onosproject.net.host.DefaultHostDescription.vlan().
org.onosproject.net.host.DefaultHostDescription.DefaultHostDescription (MacAddress mac, VlanId vlan, HostLocation location, Set< IpAddress > ip, SparseAnnotations... annotations)
Creates a host description using the supplied information.
Parameters
mac host MAC address
vlan host VLAN identifier
location host location
ip host IP addresses
annotations optional key/value annotations map
Definition at line 83 of file DefaultHostDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.host.DefaultHostDescription.location(), and org.onosproject.net.host.DefaultHostDescription.vlan().
Member Function Documentation
boolean org.onosproject.net.host.DefaultHostDescription.equals (Object object)
Definition at line 129 of file DefaultHostDescription.java.
References org.onosproject.net.host.DefaultHostDescription.DefaultHostDescription(), create-flow.location, and obeliskHostCheck.mac.
int org.onosproject.net.host.DefaultHostDescription.hashCode ()
Definition at line 124 of file DefaultHostDescription.java.
References org.onosproject.net.host.DefaultHostDescription.location(), and org.onosproject.net.host.DefaultHostDescription.vlan().
MacAddress org.onosproject.net.host.DefaultHostDescription.hwAddress ()
Returns the MAC address associated with this host (NIC).
Returns
the MAC address of this host
Implements org.onosproject.net.host.HostDescription.
Definition at line 94 of file DefaultHostDescription.java.
Set<IpAddress> org.onosproject.net.host.DefaultHostDescription.ipAddress ()
Returns the IP address associated with this host's MAC.
Returns
host IP address
Implements org.onosproject.net.host.HostDescription.
Definition at line 109 of file DefaultHostDescription.java.
HostLocation org.onosproject.net.host.DefaultHostDescription.location ()
Returns the location of the host on the network edge.
Returns
the network location
Implements org.onosproject.net.host.HostDescription.
Definition at line 104 of file DefaultHostDescription.java.
Referenced by org.onosproject.net.host.DefaultHostDescription.DefaultHostDescription(), org.onosproject.net.host.DefaultHostDescription.hashCode(), and org.onosproject.net.host.DefaultHostDescription.toString().
String org.onosproject.net.host.DefaultHostDescription.toString ()
Definition at line 114 of file DefaultHostDescription.java.
References org.onosproject.net.host.DefaultHostDescription.location(), and org.onosproject.net.host.DefaultHostDescription.vlan().
VlanId org.onosproject.net.host.DefaultHostDescription.vlan ()
Returns the VLAN associated with this host.
Returns
the VLAN ID value
Implements org.onosproject.net.host.HostDescription.
Definition at line 99 of file DefaultHostDescription.java.
Referenced by org.onosproject.net.host.DefaultHostDescription.DefaultHostDescription(), org.onosproject.net.host.DefaultHostDescription.hashCode(), and org.onosproject.net.host.DefaultHostDescription.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/host/DefaultHostDescription.java