onos: org.onosproject.pcepio.types.OSPFareaIDsubTlv Class Reference
org.onosproject.pcepio.types.OSPFareaIDsubTlv Class Reference
Provides area ID for OSPF area.
Public Member Functions
OSPFareaIDsubTlv (int rawValue)
constructor to initialize rawValue.
int getInt ()
Returns RawValue opaque value of AreaID.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static OSPFareaIDsubTlv of (final int raw)
Returns newly created OSPFareaIDsubTlv object.
static OSPFareaIDsubTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of OSPFAreaIdSubTlv.
Static Public Attributes
static final short TYPE = 600
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(OSPFareaIDsubTlv.class)
Detailed Description
Provides area ID for OSPF area.
Definition at line 29 of file OSPFareaIDsubTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.OSPFareaIDsubTlv.OSPFareaIDsubTlv (int rawValue)
constructor to initialize rawValue.
Parameters
rawValue area ID for OSPF area.
Definition at line 53 of file OSPFareaIDsubTlv.java.
Referenced by org.onosproject.pcepio.types.OSPFareaIDsubTlv.equals(), and org.onosproject.pcepio.types.OSPFareaIDsubTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.OSPFareaIDsubTlv.equals (Object obj)
Definition at line 97 of file OSPFareaIDsubTlv.java.
References org.onosproject.pcepio.types.OSPFareaIDsubTlv.OSPFareaIDsubTlv().
int org.onosproject.pcepio.types.OSPFareaIDsubTlv.getInt ()
Returns RawValue opaque value of AreaID.
Returns
rawValue Area ID
Definition at line 72 of file OSPFareaIDsubTlv.java.
short org.onosproject.pcepio.types.OSPFareaIDsubTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 87 of file OSPFareaIDsubTlv.java.
References org.onosproject.pcepio.types.OSPFareaIDsubTlv.LENGTH.
short org.onosproject.pcepio.types.OSPFareaIDsubTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 82 of file OSPFareaIDsubTlv.java.
References org.onosproject.pcepio.types.OSPFareaIDsubTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.OSPFareaIDsubTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 77 of file OSPFareaIDsubTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.OSPFareaIDsubTlv.hashCode ()
Definition at line 92 of file OSPFareaIDsubTlv.java.
static OSPFareaIDsubTlv org.onosproject.pcepio.types.OSPFareaIDsubTlv.of (final int raw) static
Returns newly created OSPFareaIDsubTlv object.
Parameters
raw opaque value of AreaID
Returns
new object of OSPF area ID sub TLV
Definition at line 63 of file OSPFareaIDsubTlv.java.
References org.onosproject.pcepio.types.OSPFareaIDsubTlv.OSPFareaIDsubTlv().
static OSPFareaIDsubTlv org.onosproject.pcepio.types.OSPFareaIDsubTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of OSPFAreaIdSubTlv.
Parameters
c input channel buffer
Returns
object of OSPFAreaIdSubTlv
Definition at line 123 of file OSPFareaIDsubTlv.java.
String org.onosproject.pcepio.types.OSPFareaIDsubTlv.toString ()
Definition at line 128 of file OSPFareaIDsubTlv.java.
References org.onosproject.pcepio.types.OSPFareaIDsubTlv.LENGTH, and org.onosproject.pcepio.types.OSPFareaIDsubTlv.TYPE.
int org.onosproject.pcepio.types.OSPFareaIDsubTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 109 of file OSPFareaIDsubTlv.java.
References org.onosproject.pcepio.types.OSPFareaIDsubTlv.LENGTH, and org.onosproject.pcepio.types.OSPFareaIDsubTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.OSPFareaIDsubTlv.LENGTH = 4 static
Definition at line 44 of file OSPFareaIDsubTlv.java.
Referenced by org.onosproject.pcepio.types.OSPFareaIDsubTlv.getLength(), org.onosproject.pcepio.types.OSPFareaIDsubTlv.toString(), and org.onosproject.pcepio.types.OSPFareaIDsubTlv.write().
final Logger org.onosproject.pcepio.types.OSPFareaIDsubTlv.log = LoggerFactory.getLogger(OSPFareaIDsubTlv.class) static protected
Definition at line 41 of file OSPFareaIDsubTlv.java.
final short org.onosproject.pcepio.types.OSPFareaIDsubTlv.TYPE = 600 static
Definition at line 43 of file OSPFareaIDsubTlv.java.
Referenced by org.onosproject.pcepio.types.OSPFareaIDsubTlv.getType(), org.onosproject.pcepio.types.OSPFareaIDsubTlv.toString(), and org.onosproject.pcepio.types.OSPFareaIDsubTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/OSPFareaIDsubTlv.java