onos: org.onosproject.store.consistent.impl.DefaultDistributedQueue< E > Class Reference
org.onosproject.store.consistent.impl.DefaultDistributedQueue< E > Class Reference
DistributedQueue implementation that provides FIFO ordering semantics.
Public Member Functions
DefaultDistributedQueue (String name, Database database, Serializer serializer, boolean meteringEnabled)
long size ()
void push (E entry)
CompletableFuture< E > pop ()
E peek ()
String name ()
Protected Member Functions
void tryPoll ()
Detailed Description
DistributedQueue implementation that provides FIFO ordering semantics.
Parameters
<E> queue entry type
Definition at line 36 of file DefaultDistributedQueue.java.
Constructor & Destructor Documentation
org.onosproject.store.consistent.impl.DefaultDistributedQueue< E >.DefaultDistributedQueue (String name, Database database, Serializer serializer, boolean meteringEnabled)
Definition at line 52 of file DefaultDistributedQueue.java.
Member Function Documentation
String org.onosproject.store.consistent.impl.DefaultDistributedQueue< E >.name ()
Definition at line 111 of file DefaultDistributedQueue.java.
References create-flow.name.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
E org.onosproject.store.consistent.impl.DefaultDistributedQueue< E >.peek ()
Definition at line 104 of file DefaultDistributedQueue.java.
References create-flow.name.
CompletableFuture<E> org.onosproject.store.consistent.impl.DefaultDistributedQueue< E >.pop ()
Definition at line 88 of file DefaultDistributedQueue.java.
References create-flow.name.
void org.onosproject.store.consistent.impl.DefaultDistributedQueue< E >.push (E entry)
Definition at line 80 of file DefaultDistributedQueue.java.
References create-flow.name.
long org.onosproject.store.consistent.impl.DefaultDistributedQueue< E >.size ()
Definition at line 74 of file DefaultDistributedQueue.java.
References create-flow.name.
void org.onosproject.store.consistent.impl.DefaultDistributedQueue< E >.tryPoll () protected
Definition at line 115 of file DefaultDistributedQueue.java.
References create-flow.name.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DefaultDistributedQueue.java