onos: org.onosproject.store.trivial.SimpleGroupStoreTest Class Reference
org.onosproject.store.trivial.SimpleGroupStoreTest Class Reference
Test of the simple DeviceStore implementation.
Public Member Functions
void setUp () throws Exception
void tearDown () throws Exception
void testGroupStoreOperations ()
Tests group store operations.
void testGroupOperationFailure ()
Static Public Attributes
static final DeviceId D1 = deviceId("of:1")
Detailed Description
Test of the simple DeviceStore implementation.
Definition at line 60 of file SimpleGroupStoreTest.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleGroupStoreTest.setUp () throws Exception
Definition at line 69 of file SimpleGroupStoreTest.java.
void org.onosproject.store.trivial.SimpleGroupStoreTest.tearDown () throws Exception
Definition at line 75 of file SimpleGroupStoreTest.java.
void org.onosproject.store.trivial.SimpleGroupStoreTest.testGroupOperationFailure ()
Definition at line 399 of file SimpleGroupStoreTest.java.
References org.onosproject.store.trivial.SimpleGroupStoreTest.D1, org.onosproject.net.PortNumber.portNumber(), and org.onlab.packet.MacAddress.valueOf().
void org.onosproject.store.trivial.SimpleGroupStoreTest.testGroupStoreOperations ()
Tests group store operations.
The following operations are tested: a)Tests device group audit completion status change b)Tests storeGroup operation c)Tests getGroupCount operation d)Tests getGroup operation e)Tests getGroups operation f)Tests addOrUpdateGroupEntry operation from southbound g)Tests updateGroupDescription for ADD operation from northbound h)Tests updateGroupDescription for REMOVE operation from northbound i)Tests deleteGroupDescription operation from northbound j)Tests removeGroupEntry operation from southbound
Definition at line 172 of file SimpleGroupStoreTest.java.
References org.onosproject.store.trivial.SimpleGroupStoreTest.D1.
Member Data Documentation
final DeviceId org.onosproject.store.trivial.SimpleGroupStoreTest.D1 = deviceId("of:1") static
Definition at line 66 of file SimpleGroupStoreTest.java.
Referenced by org.onosproject.store.trivial.SimpleGroupStoreTest.testGroupOperationFailure(), and org.onosproject.store.trivial.SimpleGroupStoreTest.testGroupStoreOperations().
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleGroupStoreTest.java