onos: org.onosproject.bgp.controller.BgpId Class Reference
org.onosproject.bgp.controller.BgpId Class Reference
The class representing a network peer bgp ip.
Public Member Functions
IpAddress ipAddress ()
Returns the ip address.
String toString ()
Convert the BGPId value to a ':' separated hexadecimal string.
boolean equals (Object other)
int hashCode ()
Static Public Member Functions
static BgpId bgpId (IpAddress ipAddress)
Create a BGPId from ip address.
static BgpId bgpId (URI uri)
Returns BGPId created from the given device URI.
static URI uri (BgpId bgpId)
Produces device URI from the given DPID.
static URI uri (IpAddress ipAddress)
Produces device URI from the given DPID long.
Detailed Description
The class representing a network peer bgp ip.
This class is immutable.
Definition at line 30 of file BgpId.java.
Member Function Documentation
static BgpId org.onosproject.bgp.controller.BgpId.bgpId (IpAddress ipAddress) static
Create a BGPId from ip address.
Parameters
ipAddress IP address
Returns
object of BGPId
Definition at line 49 of file BgpId.java.
static BgpId org.onosproject.bgp.controller.BgpId.bgpId (URI uri) static
Returns BGPId created from the given device URI.
Parameters
uri device URI
Returns
object of BGPId
Definition at line 93 of file BgpId.java.
References org.onlab.packet.IpAddress.valueOf().
boolean org.onosproject.bgp.controller.BgpId.equals (Object other)
Definition at line 73 of file BgpId.java.
References org.onosproject.bgp.controller.BgpId.ipAddress().
int org.onosproject.bgp.controller.BgpId.hashCode ()
Definition at line 83 of file BgpId.java.
References org.onosproject.bgp.controller.BgpId.ipAddress().
IpAddress org.onosproject.bgp.controller.BgpId.ipAddress ()
Returns the ip address.
Returns
ipAddress
Definition at line 58 of file BgpId.java.
Referenced by org.onosproject.bgp.controller.BgpId.equals(), and org.onosproject.bgp.controller.BgpId.hashCode().
String org.onosproject.bgp.controller.BgpId.toString ()
Convert the BGPId value to a ':' separated hexadecimal string.
Returns
the BGPId value as a ':' separated hexadecimal string.
Definition at line 68 of file BgpId.java.
static URI org.onosproject.bgp.controller.BgpId.uri (BgpId bgpId) static
Produces device URI from the given DPID.
Parameters
bgpId device bgpId
Returns
device URI
Definition at line 104 of file BgpId.java.
static URI org.onosproject.bgp.controller.BgpId.uri (IpAddress ipAddress) static
Produces device URI from the given DPID long.
Parameters
ipAddress device ip address
Returns
device URI
Definition at line 114 of file BgpId.java.
References org.onlab.packet.IpAddress.toString().
The documentation for this class was generated from the following file:
bgp/api/src/main/java/org/onosproject/bgp/controller/BgpId.java