onos: org.onosproject.net.intent.impl.ObjectiveTracker Class Reference
org.onosproject.net.intent.impl.ObjectiveTracker Class Reference
Entity responsible for tracking installed flows and for monitoring topology events to determine what flows are affected by topology changes.
Public Member Functions
void activate ()
void deactivate ()
void setDelegate (TopologyChangeDelegate delegate)
Sets a topology change delegate.
void unsetDelegate (TopologyChangeDelegate delegate)
Unsets topology change delegate.
void addTrackedResources (Key intentKey, Collection< NetworkResource > resources)
Adds a path flow to be tracked.
void removeTrackedResources (Key intentKey, Collection< NetworkResource > resources)
Removes a path flow to be tracked.
void trackIntent (IntentData intentData)
Submits the specified intent data to be tracked.
Protected Member Functions
void bindIntentService (IntentService service)
void unbindIntentService (IntentService service)
void doIntentUpdate ()
Protected Attributes
TopologyService topologyService
ResourceService resourceService
DeviceService deviceService
HostService hostService
IntentService intentService
PartitionService partitionService
final AtomicBoolean updateScheduled = new AtomicBoolean(false)
Detailed Description
Entity responsible for tracking installed flows and for monitoring topology events to determine what flows are affected by topology changes.
Definition at line 90 of file ObjectiveTracker.java.
Member Function Documentation
void org.onosproject.net.intent.impl.ObjectiveTracker.activate ()
Definition at line 135 of file ObjectiveTracker.java.
void org.onosproject.net.intent.impl.ObjectiveTracker.addTrackedResources (Key intentKey, Collection< NetworkResource > resources)
Adds a path flow to be tracked.
Parameters
intentKey intent identity on whose behalf the path is being tracked
resources resources to track
Implements org.onosproject.net.intent.impl.ObjectiveTrackerService.
Definition at line 181 of file ObjectiveTracker.java.
Referenced by org.onosproject.net.intent.impl.ObjectiveTracker.trackIntent().
void org.onosproject.net.intent.impl.ObjectiveTracker.bindIntentService (IntentService service) protected
Definition at line 154 of file ObjectiveTracker.java.
References org.onosproject.net.intent.impl.ObjectiveTracker.intentService.
void org.onosproject.net.intent.impl.ObjectiveTracker.deactivate ()
Definition at line 145 of file ObjectiveTracker.java.
void org.onosproject.net.intent.impl.ObjectiveTracker.doIntentUpdate () protected
Definition at line 421 of file ObjectiveTracker.java.
References org.onosproject.net.intent.IntentService.getIntentData(), org.onosproject.net.intent.impl.ObjectiveTracker.intentService, and org.onosproject.net.intent.impl.ObjectiveTracker.trackIntent().
void org.onosproject.net.intent.impl.ObjectiveTracker.removeTrackedResources (Key intentKey, Collection< NetworkResource > resources)
Removes a path flow to be tracked.
Parameters
intentKey intent identity on whose behalf the path is being tracked
resources resources to stop tracking
Implements org.onosproject.net.intent.impl.ObjectiveTrackerService.
Definition at line 193 of file ObjectiveTracker.java.
Referenced by org.onosproject.net.intent.impl.ObjectiveTracker.trackIntent().
void org.onosproject.net.intent.impl.ObjectiveTracker.setDelegate (TopologyChangeDelegate delegate)
Sets a topology change delegate.
Parameters
delegate topology change delegate
Implements org.onosproject.net.intent.impl.ObjectiveTrackerService.
Definition at line 167 of file ObjectiveTracker.java.
void org.onosproject.net.intent.impl.ObjectiveTracker.trackIntent (IntentData intentData)
Submits the specified intent data to be tracked.
Parameters
intentData intent data object to be tracked
Implements org.onosproject.net.intent.impl.ObjectiveTrackerService.
Definition at line 205 of file ObjectiveTracker.java.
References org.onosproject.net.intent.impl.ObjectiveTracker.addTrackedResources(), org.onosproject.net.intent.impl.ObjectiveTracker.removeTrackedResources(), and onos.size.
Referenced by org.onosproject.net.intent.impl.ObjectiveTracker.doIntentUpdate().
void org.onosproject.net.intent.impl.ObjectiveTracker.unbindIntentService (IntentService service) protected
Definition at line 160 of file ObjectiveTracker.java.
References org.onosproject.net.intent.impl.ObjectiveTracker.intentService.
void org.onosproject.net.intent.impl.ObjectiveTracker.unsetDelegate (TopologyChangeDelegate delegate)
Unsets topology change delegate.
Parameters
delegate topology change delegate
Implements org.onosproject.net.intent.impl.ObjectiveTrackerService.
Definition at line 175 of file ObjectiveTracker.java.
Member Data Documentation
DeviceService org.onosproject.net.intent.impl.ObjectiveTracker.deviceService protected
Definition at line 108 of file ObjectiveTracker.java.
HostService org.onosproject.net.intent.impl.ObjectiveTracker.hostService protected
Definition at line 111 of file ObjectiveTracker.java.
IntentService org.onosproject.net.intent.impl.ObjectiveTracker.intentService protected
Definition at line 115 of file ObjectiveTracker.java.
Referenced by org.onosproject.net.intent.impl.ObjectiveTracker.bindIntentService(), org.onosproject.net.intent.impl.ObjectiveTracker.doIntentUpdate(), and org.onosproject.net.intent.impl.ObjectiveTracker.unbindIntentService().
PartitionService org.onosproject.net.intent.impl.ObjectiveTracker.partitionService protected
Definition at line 118 of file ObjectiveTracker.java.
ResourceService org.onosproject.net.intent.impl.ObjectiveTracker.resourceService protected
Definition at line 105 of file ObjectiveTracker.java.
TopologyService org.onosproject.net.intent.impl.ObjectiveTracker.topologyService protected
Definition at line 102 of file ObjectiveTracker.java.
final AtomicBoolean org.onosproject.net.intent.impl.ObjectiveTracker.updateScheduled = new AtomicBoolean(false) protected
Definition at line 132 of file ObjectiveTracker.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/intent/impl/ObjectiveTracker.java