onos: org.onosproject.store.link.impl.GossipLinkStoreTest Class Reference
org.onosproject.store.link.impl.GossipLinkStoreTest Class Reference
Test of the GossipLinkStoreTest implementation.
Public Member Functions
void setUp () throws Exception
void tearDown () throws Exception
final void testGetLinkCount ()
final void testGetLinks ()
final void testGetDeviceEgressLinks ()
final void testGetDeviceIngressLinks ()
final void testGetLink ()
final void testGetEgressLinks ()
final void testGetIngressLinks ()
final void testCreateOrUpdateLink ()
final void testCreateOrUpdateLinkAncillary ()
final void testRemoveLink ()
final void testAncillaryVisible ()
final void testEvents () throws InterruptedException
Static Public Member Functions
static void setUpBeforeClass () throws Exception
static void tearDownAfterClass () throws Exception
Detailed Description
Test of the GossipLinkStoreTest implementation.
Definition at line 79 of file GossipLinkStoreTest.java.
Member Function Documentation
void org.onosproject.store.link.impl.GossipLinkStoreTest.setUp () throws Exception
Definition at line 133 of file GossipLinkStoreTest.java.
static void org.onosproject.store.link.impl.GossipLinkStoreTest.setUpBeforeClass () throws Exception static
Definition at line 125 of file GossipLinkStoreTest.java.
void org.onosproject.store.link.impl.GossipLinkStoreTest.tearDown () throws Exception
Definition at line 157 of file GossipLinkStoreTest.java.
static void org.onosproject.store.link.impl.GossipLinkStoreTest.tearDownAfterClass () throws Exception static
Definition at line 129 of file GossipLinkStoreTest.java.
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testAncillaryVisible ()
Definition at line 527 of file GossipLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLink(), and org.onosproject.net.link.LinkStore.getLinkCount().
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testCreateOrUpdateLink ()
Definition at line 357 of file GossipLinkStoreTest.java.
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testCreateOrUpdateLinkAncillary ()
Definition at line 423 of file GossipLinkStoreTest.java.
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testEvents () throws InterruptedException
Definition at line 544 of file GossipLinkStoreTest.java.
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testGetDeviceEgressLinks ()
Definition at line 246 of file GossipLinkStoreTest.java.
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testGetDeviceIngressLinks ()
Definition at line 269 of file GossipLinkStoreTest.java.
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testGetEgressLinks ()
Definition at line 307 of file GossipLinkStoreTest.java.
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testGetIngressLinks ()
Definition at line 332 of file GossipLinkStoreTest.java.
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testGetLink ()
Definition at line 292 of file GossipLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLink().
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testGetLinkCount ()
Definition at line 211 of file GossipLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLinkCount().
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testGetLinks ()
Definition at line 222 of file GossipLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLinks().
final void org.onosproject.store.link.impl.GossipLinkStoreTest.testRemoveLink ()
Definition at line 498 of file GossipLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLink().
The documentation for this class was generated from the following file:
core/store/dist/src/test/java/org/onosproject/store/link/impl/GossipLinkStoreTest.java