onos: org.onlab.packet.ndp.NeighborSolicitationTest Class Reference
org.onlab.packet.ndp.NeighborSolicitationTest Class Reference
Tests for class NeighborSolicitation.
Public Member Functions
void testSerialize ()
Tests serialize and setters.
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws DeserializationException
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class NeighborSolicitation.
Definition at line 36 of file NeighborSolicitationTest.java.
Member Function Documentation
static void org.onlab.packet.ndp.NeighborSolicitationTest.setUpBeforeClass () throws Exception static
Definition at line 58 of file NeighborSolicitationTest.java.
References find-link-in-cluster.length.
void org.onlab.packet.ndp.NeighborSolicitationTest.testDeserialize () throws DeserializationException
Tests deserialize and getters.
Definition at line 103 of file NeighborSolicitationTest.java.
References org.onlab.packet.ndp.NeighborSolicitation.getOptions(), org.onlab.packet.ndp.NeighborSolicitation.getTargetAddress(), find-link-in-cluster.length, and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
void org.onlab.packet.ndp.NeighborSolicitationTest.testDeserializeBadInput () throws Exception
Definition at line 86 of file NeighborSolicitationTest.java.
void org.onlab.packet.ndp.NeighborSolicitationTest.testDeserializeTruncated () throws Exception
Definition at line 91 of file NeighborSolicitationTest.java.
References org.onlab.packet.ndp.NeighborSolicitation.HEADER_LENGTH.
void org.onlab.packet.ndp.NeighborSolicitationTest.testEqual ()
Tests comparator.
Definition at line 120 of file NeighborSolicitationTest.java.
References org.onlab.packet.ndp.NeighborSolicitation.equals(), and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
void org.onlab.packet.ndp.NeighborSolicitationTest.testSerialize ()
Tests serialize and setters.
Definition at line 76 of file NeighborSolicitationTest.java.
References org.onlab.packet.ndp.NeighborSolicitation.serialize(), and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ndp/NeighborSolicitationTest.java