onos: org.onosproject.vtnrsc.FixedIp Class Reference
org.onosproject.vtnrsc.FixedIp Class Reference
Immutable representation of a IP address for the port, Include the IP address and subnet identity.
Public Member Functions
SubnetId subnetId ()
Returns the FixedIp subnet identifier.
IpAddress ip ()
Returns the FixedIp IP address.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static FixedIp fixedIp (SubnetId subnetId, IpAddress ip)
Creates a fixed ip using the supplied fixedIp.
Detailed Description
Immutable representation of a IP address for the port, Include the IP address and subnet identity.
Definition at line 29 of file FixedIp.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.FixedIp.equals (Object obj)
Definition at line 75 of file FixedIp.java.
static FixedIp org.onosproject.vtnrsc.FixedIp.fixedIp (SubnetId subnetId, IpAddress ip) static
Creates a fixed ip using the supplied fixedIp.
Parameters
subnetId subnet identity
ip IP address
Returns
FixedIp
Definition at line 65 of file FixedIp.java.
int org.onosproject.vtnrsc.FixedIp.hashCode ()
Definition at line 70 of file FixedIp.java.
References org.onosproject.vtnrsc.FixedIp.ip(), and org.onosproject.vtnrsc.FixedIp.subnetId().
IpAddress org.onosproject.vtnrsc.FixedIp.ip ()
Returns the FixedIp IP address.
Returns
IP address
Definition at line 54 of file FixedIp.java.
Referenced by org.onosproject.vtnrsc.FixedIp.hashCode(), onos.ONOS.start(), and onos.ONOS.updateHazelcast().
SubnetId org.onosproject.vtnrsc.FixedIp.subnetId ()
Returns the FixedIp subnet identifier.
Returns
subnet identifier
Definition at line 45 of file FixedIp.java.
Referenced by org.onosproject.vtnrsc.FixedIp.hashCode(), and org.onosproject.vtnrsc.FixedIp.toString().
String org.onosproject.vtnrsc.FixedIp.toString ()
Definition at line 88 of file FixedIp.java.
References org.onosproject.vtnrsc.FixedIp.subnetId().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/FixedIp.java