onos: org.onosproject.net.mcast.McastRoute Class Reference
org.onosproject.net.mcast.McastRoute Class Reference
An entity representing a multicast route consisting of a source and a multicast group address.
Classes
enum Type
Public Member Functions
McastRoute (IpPrefix source, IpPrefix group, Type type)
IpPrefix source ()
Fetches the source address of this route.
IpPrefix group ()
Fetches the group address of this route.
Type type ()
Obtains how this route was created.
String toString ()
boolean equals (Object o)
int hashCode ()
Detailed Description
An entity representing a multicast route consisting of a source and a multicast group address.
Definition at line 30 of file McastRoute.java.
Constructor & Destructor Documentation
org.onosproject.net.mcast.McastRoute.McastRoute (IpPrefix source, IpPrefix group, Type type)
Definition at line 53 of file McastRoute.java.
References org.onosproject.net.mcast.McastRoute.group(), org.onosproject.net.mcast.McastRoute.source(), and org.onosproject.net.mcast.McastRoute.type().
Referenced by org.onosproject.net.mcast.McastRoute.equals().
Member Function Documentation
boolean org.onosproject.net.mcast.McastRoute.equals (Object o)
Definition at line 99 of file McastRoute.java.
References org.onosproject.net.mcast.McastRoute.group(), org.onosproject.net.mcast.McastRoute.McastRoute(), org.onosproject.net.mcast.McastRoute.source(), and org.onosproject.net.mcast.McastRoute.type().
IpPrefix org.onosproject.net.mcast.McastRoute.group ()
Fetches the group address of this route.
Returns
an ip address
Definition at line 76 of file McastRoute.java.
Referenced by org.onosproject.net.mcast.McastRoute.equals(), org.onosproject.net.mcast.McastRoute.hashCode(), org.onosproject.net.mcast.McastRoute.McastRoute(), and org.onosproject.net.mcast.McastRoute.toString().
int org.onosproject.net.mcast.McastRoute.hashCode ()
Definition at line 113 of file McastRoute.java.
References org.onosproject.net.mcast.McastRoute.group(), org.onosproject.net.mcast.McastRoute.source(), and org.onosproject.net.mcast.McastRoute.type().
IpPrefix org.onosproject.net.mcast.McastRoute.source ()
Fetches the source address of this route.
Returns
an ip address
Definition at line 67 of file McastRoute.java.
Referenced by org.onosproject.net.mcast.McastRoute.equals(), org.onosproject.net.mcast.McastRoute.hashCode(), org.onosproject.net.mcast.McastRoute.McastRoute(), and org.onosproject.net.mcast.McastRoute.toString().
String org.onosproject.net.mcast.McastRoute.toString ()
Definition at line 90 of file McastRoute.java.
References org.onosproject.net.mcast.McastRoute.group(), org.onosproject.net.mcast.McastRoute.source(), and org.onosproject.net.mcast.McastRoute.type().
Type org.onosproject.net.mcast.McastRoute.type ()
Obtains how this route was created.
Returns
a type of route
Definition at line 85 of file McastRoute.java.
Referenced by org.onosproject.net.mcast.McastRoute.equals(), org.onosproject.net.mcast.McastRoute.hashCode(), org.onosproject.net.mcast.McastRoute.McastRoute(), and org.onosproject.net.mcast.McastRoute.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/mcast/McastRoute.java