onos: org.onosproject.vtnrsc.AllowedAddressPair Class Reference
org.onosproject.vtnrsc.AllowedAddressPair Class Reference
Immutable representation of a allowed address pair.
Public Member Functions
IpAddress ip ()
Returns the AllowedAddressPair ip address.
MacAddress mac ()
Returns the AllowedAddressPair MAC address.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static AllowedAddressPair allowedAddressPair (IpAddress ip, MacAddress mac)
Creates a allowedAddressPair using the supplied ipAddress & macAddress.
Detailed Description
Immutable representation of a allowed address pair.
Definition at line 29 of file AllowedAddressPair.java.
Member Function Documentation
static AllowedAddressPair org.onosproject.vtnrsc.AllowedAddressPair.allowedAddressPair (IpAddress ip, MacAddress mac) static
Creates a allowedAddressPair using the supplied ipAddress & macAddress.
Parameters
ip IP address
mac MAC address
Returns
AllowedAddressPair
Definition at line 66 of file AllowedAddressPair.java.
boolean org.onosproject.vtnrsc.AllowedAddressPair.equals (Object obj)
Definition at line 77 of file AllowedAddressPair.java.
int org.onosproject.vtnrsc.AllowedAddressPair.hashCode ()
Definition at line 72 of file AllowedAddressPair.java.
References org.onosproject.vtnrsc.AllowedAddressPair.ip(), and org.onosproject.vtnrsc.AllowedAddressPair.mac().
IpAddress org.onosproject.vtnrsc.AllowedAddressPair.ip ()
Returns the AllowedAddressPair ip address.
Returns
ip address
Definition at line 44 of file AllowedAddressPair.java.
Referenced by org.onosproject.vtnrsc.AllowedAddressPair.hashCode(), onos.ONOS.start(), org.onosproject.vtnrsc.AllowedAddressPair.toString(), and onos.ONOS.updateHazelcast().
MacAddress org.onosproject.vtnrsc.AllowedAddressPair.mac ()
Returns the AllowedAddressPair MAC address.
Returns
MAC address
Definition at line 53 of file AllowedAddressPair.java.
Referenced by org.onosproject.vtnrsc.AllowedAddressPair.hashCode().
String org.onosproject.vtnrsc.AllowedAddressPair.toString ()
Definition at line 90 of file AllowedAddressPair.java.
References org.onosproject.vtnrsc.AllowedAddressPair.ip().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/AllowedAddressPair.java