onos: org.onosproject.ovsdb.controller.OvsdbBridgeName Class Reference
org.onosproject.ovsdb.controller.OvsdbBridgeName Class Reference
The class representing a bridge name.
Public Member Functions
OvsdbBridgeName (String value)
Constructor from a String.
String value ()
Gets the value of bridge name.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
The class representing a bridge name.
This class is immutable.
Definition at line 27 of file OvsdbBridgeName.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.controller.OvsdbBridgeName.OvsdbBridgeName (String value)
Constructor from a String.
Parameters
value the bridge name to use
Definition at line 36 of file OvsdbBridgeName.java.
References org.onosproject.ovsdb.controller.OvsdbBridgeName.value().
Referenced by org.onosproject.ovsdb.controller.OvsdbBridgeName.equals().
Member Function Documentation
boolean org.onosproject.ovsdb.controller.OvsdbBridgeName.equals (Object obj)
Definition at line 56 of file OvsdbBridgeName.java.
References org.onosproject.ovsdb.controller.OvsdbBridgeName.OvsdbBridgeName().
int org.onosproject.ovsdb.controller.OvsdbBridgeName.hashCode ()
Definition at line 51 of file OvsdbBridgeName.java.
String org.onosproject.ovsdb.controller.OvsdbBridgeName.toString ()
Definition at line 68 of file OvsdbBridgeName.java.
References org.onosproject.ovsdb.controller.OvsdbBridgeName.value().
String org.onosproject.ovsdb.controller.OvsdbBridgeName.value ()
Gets the value of bridge name.
Returns
the value of the bridge name
Definition at line 46 of file OvsdbBridgeName.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbBridgeName.OvsdbBridgeName(), and org.onosproject.ovsdb.controller.OvsdbBridgeName.toString().
The documentation for this class was generated from the following file:
protocols/ovsdb/api/src/main/java/org/onosproject/ovsdb/controller/OvsdbBridgeName.java