onos: org.onlab.packet.TCP Class Reference
org.onlab.packet.TCP Class Reference
Implements TCP packet format.
Public Member Functions
int getSourcePort ()
Gets TCP source port.
TCP setSourcePort (final int sourcePort)
Sets TCP source port.
int getDestinationPort ()
Gets TCP destination port.
TCP setDestinationPort (final int destinationPort)
Sets TCP destination port.
short getChecksum ()
Gets checksum.
TCP setChecksum (final short checksum)
Sets checksum.
int getSequence ()
Gets sequence number.
TCP setSequence (final int seq)
Sets sequence number.
int getAcknowledge ()
Gets acknowledge number.
TCP setAcknowledge (final int ack)
Sets acknowledge number.
byte getDataOffset ()
Gets offset.
TCP setDataOffset (final byte offset)
Sets offset.
short getFlags ()
Gets TCP flags.
TCP setFlags (final short flags)
Sets TCP flags.
short getWindowSize ()
Gets TCP window size.
TCP setWindowSize (final short windowSize)
Sets TCP window size.
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
short getUrgentPointer ()
Gets urgent pointer.
TCP setUrgentPointer (final short urgentPointer)
Sets urgent pointer.
byte[] getOptions ()
Gets TCP options.
TCP setOptions (final byte[] options)
Sets TCP options.
byte[] serialize ()
Serializes the packet.
IPacket deserialize (final byte[] data, final int offset, final int length)
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
Static Public Member Functions
static Deserializer< TCP > deserializer ()
Deserializer function for TCP packets.
Protected Attributes
int sourcePort
int destinationPort
int sequence
int acknowledge
byte dataOffset
short flags
short windowSize
short checksum
short urgentPointer
byte[] options
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements TCP packet format.
Definition at line 30 of file TCP.java.
Member Function Documentation
IPacket org.onlab.packet.TCP.deserialize (final byte[] data, final int offset, final int length)
Definition at line 349 of file TCP.java.
References org.onlab.packet.TCP.dataOffset, org.onlab.packet.TCP.flags, and find-link-in-cluster.length.
Referenced by org.onlab.packet.TCP.deserializer().
static Deserializer<TCP> org.onlab.packet.TCP.deserializer () static
Deserializer function for TCP packets.
Returns
deserializer function
Definition at line 432 of file TCP.java.
References org.onlab.packet.TCP.dataOffset, org.onlab.packet.TCP.deserialize(), org.onlab.packet.TCP.flags, and find-link-in-cluster.length.
boolean org.onlab.packet.TCP.equals (final Object obj)
Definition at line 403 of file TCP.java.
Referenced by org.onlab.packet.TCPTest.testEqual().
int org.onlab.packet.TCP.getAcknowledge ()
Gets acknowledge number.
Returns
the acknowledge number
Definition at line 130 of file TCP.java.
Referenced by org.onlab.packet.TCPTest.testDeserialize().
short org.onlab.packet.TCP.getChecksum ()
Gets checksum.
Returns
the checksum
Definition at line 90 of file TCP.java.
Referenced by org.onlab.packet.TCPTest.testDeserialize().
byte org.onlab.packet.TCP.getDataOffset ()
Gets offset.
Returns
the offset
Definition at line 150 of file TCP.java.
Referenced by org.onlab.packet.TCPTest.testDeserialize().
int org.onlab.packet.TCP.getDestinationPort ()
Gets TCP destination port.
Returns
the destinationPort
Definition at line 70 of file TCP.java.
Referenced by org.onlab.packet.TCPTest.testDeserialize().
short org.onlab.packet.TCP.getFlags ()
Gets TCP flags.
Returns
the TCP flags
Definition at line 170 of file TCP.java.
Referenced by org.onlab.packet.TCPTest.testDeserialize().
byte [] org.onlab.packet.TCP.getOptions ()
Gets TCP options.
Returns
the TCP options
Definition at line 236 of file TCP.java.
int org.onlab.packet.TCP.getSequence ()
Gets sequence number.
Returns
the sequence number
Definition at line 110 of file TCP.java.
Referenced by org.onlab.packet.TCPTest.testDeserialize().
int org.onlab.packet.TCP.getSourcePort ()
Gets TCP source port.
Returns
TCP source port
Definition at line 50 of file TCP.java.
Referenced by org.onlab.packet.TCPTest.testDeserialize().
short org.onlab.packet.TCP.getUrgentPointer ()
Gets urgent pointer.
Returns
the urgent pointer
Definition at line 216 of file TCP.java.
Referenced by org.onlab.packet.TCPTest.testDeserialize().
short org.onlab.packet.TCP.getWindowSize ()
Gets TCP window size.
Returns
the TCP window size
Definition at line 190 of file TCP.java.
Referenced by org.onlab.packet.TCPTest.testDeserialize().
int org.onlab.packet.TCP.hashCode ()
Definition at line 388 of file TCP.java.
void org.onlab.packet.TCP.resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
Implements org.onlab.packet.IPacket.
Definition at line 206 of file TCP.java.
byte [] org.onlab.packet.TCP.serialize ()
Serializes the packet.
Will compute and set the following fields if they are set to specific values at the time serialize is called: -checksum : 0 -length : 0
Implements org.onlab.packet.IPacket.
Definition at line 258 of file TCP.java.
References org.onlab.packet.TCP.checksum, org.onlab.packet.TCP.dataOffset, org.onlab.packet.TCP.destinationPort, org.onlab.packet.TCP.flags, find-link-in-cluster.length, org.onlab.packet.TCP.options, org.onlab.packet.BasePacket.parent, org.onlab.packet.BasePacket.payload, org.onlab.packet.IPv4.PROTOCOL_TCP, and org.onlab.packet.TCP.sourcePort.
Referenced by org.onlab.packet.TCPTest.testSerialize().
TCP org.onlab.packet.TCP.setAcknowledge (final int ack)
Sets acknowledge number.
Parameters
ack the acknowledge number to set
Returns
this
Definition at line 140 of file TCP.java.
TCP org.onlab.packet.TCP.setChecksum (final short checksum)
Sets checksum.
Parameters
checksum the checksum to set
Returns
this
Definition at line 100 of file TCP.java.
References org.onlab.packet.TCP.checksum.
TCP org.onlab.packet.TCP.setDataOffset (final byte offset)
Sets offset.
Parameters
offset the offset to set
Returns
this
Definition at line 160 of file TCP.java.
TCP org.onlab.packet.TCP.setDestinationPort (final int destinationPort)
Sets TCP destination port.
Parameters
destinationPort the destinationPort to set (unsigned 16 bits integer)
Returns
this
Definition at line 80 of file TCP.java.
References org.onlab.packet.TCP.destinationPort.
TCP org.onlab.packet.TCP.setFlags (final short flags)
Sets TCP flags.
Parameters
flags the TCP flags to set
Returns
this
Definition at line 180 of file TCP.java.
References org.onlab.packet.TCP.flags.
TCP org.onlab.packet.TCP.setOptions (final byte[] options)
Sets TCP options.
Parameters
options the options to set
Returns
this
Definition at line 246 of file TCP.java.
References org.onlab.packet.TCP.options.
TCP org.onlab.packet.TCP.setSequence (final int seq)
Sets sequence number.
Parameters
seq the sequence number to set
Returns
this
Definition at line 120 of file TCP.java.
TCP org.onlab.packet.TCP.setSourcePort (final int sourcePort)
Sets TCP source port.
Parameters
sourcePort the sourcePort to set (unsigned 16 bits integer)
Returns
this
Definition at line 60 of file TCP.java.
References org.onlab.packet.TCP.sourcePort.
TCP org.onlab.packet.TCP.setUrgentPointer (final short urgentPointer)
Sets urgent pointer.
Parameters
urgentPointer the urgent pointer to set
Returns
this
Definition at line 226 of file TCP.java.
References org.onlab.packet.TCP.urgentPointer.
TCP org.onlab.packet.TCP.setWindowSize (final short windowSize)
Sets TCP window size.
Parameters
windowSize the TCP window size to set
Returns
this
Definition at line 200 of file TCP.java.
References org.onlab.packet.TCP.windowSize.
Member Data Documentation
int org.onlab.packet.TCP.acknowledge protected
Definition at line 37 of file TCP.java.
short org.onlab.packet.TCP.checksum protected
Definition at line 41 of file TCP.java.
Referenced by org.onlab.packet.TCP.serialize(), and org.onlab.packet.TCP.setChecksum().
byte org.onlab.packet.TCP.dataOffset protected
Definition at line 38 of file TCP.java.
Referenced by org.onlab.packet.TCP.deserialize(), org.onlab.packet.TCP.deserializer(), and org.onlab.packet.TCP.serialize().
int org.onlab.packet.TCP.destinationPort protected
Definition at line 35 of file TCP.java.
Referenced by org.onlab.packet.TCP.serialize(), and org.onlab.packet.TCP.setDestinationPort().
short org.onlab.packet.TCP.flags protected
Definition at line 39 of file TCP.java.
Referenced by org.onlab.packet.TCP.deserialize(), org.onlab.packet.TCP.deserializer(), org.onlab.packet.TCP.serialize(), and org.onlab.packet.TCP.setFlags().
byte [] org.onlab.packet.TCP.options protected
Definition at line 43 of file TCP.java.
Referenced by org.onlab.packet.TCP.serialize(), and org.onlab.packet.TCP.setOptions().
int org.onlab.packet.TCP.sequence protected
Definition at line 36 of file TCP.java.
int org.onlab.packet.TCP.sourcePort protected
Definition at line 34 of file TCP.java.
Referenced by org.onlab.packet.TCP.serialize(), and org.onlab.packet.TCP.setSourcePort().
short org.onlab.packet.TCP.urgentPointer protected
Definition at line 42 of file TCP.java.
Referenced by org.onlab.packet.TCP.setUrgentPointer().
short org.onlab.packet.TCP.windowSize protected
Definition at line 40 of file TCP.java.
Referenced by org.onlab.packet.TCP.setWindowSize().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/TCP.java