onos: org.onosproject.incubator.net.tunnel.TunnelName Class Reference
org.onosproject.incubator.net.tunnel.TunnelName Class Reference
Represents for a unique tunnel name.
Public Member Functions
String value ()
The string of tunnel name.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static TunnelName tunnelName (String tunnelName)
Creates a tunnel name using the supplied URI string.
Detailed Description
Represents for a unique tunnel name.
TunnelId is generated by ONOS while TunnelName is given by producer. The consumer can borrow tunnels with TunnelId or TunnelName.
Definition at line 29 of file TunnelName.java.
Member Function Documentation
boolean org.onosproject.incubator.net.tunnel.TunnelName.equals (Object obj)
Definition at line 63 of file TunnelName.java.
int org.onosproject.incubator.net.tunnel.TunnelName.hashCode ()
Definition at line 58 of file TunnelName.java.
String org.onosproject.incubator.net.tunnel.TunnelName.toString ()
Definition at line 76 of file TunnelName.java.
static TunnelName org.onosproject.incubator.net.tunnel.TunnelName.tunnelName (String tunnelName) static
Creates a tunnel name using the supplied URI string.
Parameters
tunnelName tunnel name string
Returns
tunnel name object
Definition at line 44 of file TunnelName.java.
Referenced by org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.testTunnelAdded(), and org.onosproject.ovsdb.provider.tunnel.OvsdbTunnelProviderTest.testTunnelRemoved().
String org.onosproject.incubator.net.tunnel.TunnelName.value ()
The string of tunnel name.
Returns
the string of tunnel name
Definition at line 53 of file TunnelName.java.
Referenced by org.onosproject.incubator.net.tunnel.TunnelNameTest.testConstruction().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/tunnel/TunnelName.java