onos: org.onosproject.pcepio.types.PcepRsvpUserErrorSpec Class Reference
org.onosproject.pcepio.types.PcepRsvpUserErrorSpec Class Reference
Provides Pcep Rsvp User Error Spec.
Public Member Functions
PcepRsvpUserErrorSpec (PcepRsvpSpecObjHeader objHeader, int enterpriseNum, byte subOrg, byte errDescLen, short userErrorValue, byte[] errDesc, LinkedList< PcepValueType > llRsvpUserSpecSubObj)
Default constructor.
int write (ChannelBuffer cb)
To write the object information to channelBuffer.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
byte getClassNum ()
Returns class number.
byte getClassType ()
Returns class type.
String toString ()
Static Public Member Functions
static PcepRsvpErrorSpec read (ChannelBuffer cb) throws PcepParseException
Reads the channel buffer and returns object of PcepRsvpErrorSpec.
Static Public Attributes
static final byte CLASS_NUM = (byte) 0xc2
static final byte CLASS_TYPE = 0x01
Detailed Description
Provides Pcep Rsvp User Error Spec.
Definition at line 30 of file PcepRsvpUserErrorSpec.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.PcepRsvpUserErrorSpec (PcepRsvpSpecObjHeader objHeader, int enterpriseNum, byte subOrg, byte errDescLen, short userErrorValue, byte[] errDesc, LinkedList< PcepValueType > llRsvpUserSpecSubObj)
Default constructor.
Parameters
objHeader pcep rsvp spec object header
enterpriseNum enterprise number
subOrg organization identifier value
errDescLen error description length
userErrorValue user error value
errDesc error description
llRsvpUserSpecSubObj list of subobjects
Definition at line 85 of file PcepRsvpUserErrorSpec.java.
Referenced by org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.read().
Member Function Documentation
byte org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.getClassNum ()
Returns class number.
Returns
class number
Implements org.onosproject.pcepio.types.PcepRsvpErrorSpec.
Definition at line 200 of file PcepRsvpUserErrorSpec.java.
References org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.CLASS_NUM.
byte org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.getClassType ()
Returns class type.
Returns
class type
Implements org.onosproject.pcepio.types.PcepRsvpErrorSpec.
Definition at line 205 of file PcepRsvpUserErrorSpec.java.
References org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.CLASS_TYPE.
short org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 195 of file PcepRsvpUserErrorSpec.java.
short org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 190 of file PcepRsvpUserErrorSpec.java.
References org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 185 of file PcepRsvpUserErrorSpec.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
static PcepRsvpErrorSpec org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.read (ChannelBuffer cb) throws PcepParseException static
Reads the channel buffer and returns object of PcepRsvpErrorSpec.
Parameters
cb of type channel buffer
Returns
object of PcepRsvpErrorSpec
Exceptions
PcepParseException when expected object is not received
Definition at line 137 of file PcepRsvpUserErrorSpec.java.
References org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.CLASS_NUM, org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.CLASS_TYPE, org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.getObjClassNum(), and org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.PcepRsvpUserErrorSpec().
String org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.toString ()
Definition at line 210 of file PcepRsvpUserErrorSpec.java.
int org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.write (ChannelBuffer cb)
To write the object information to channelBuffer.
Parameters
cb of type channel buffer
Implements org.onosproject.pcepio.types.PcepRsvpErrorSpec.
Definition at line 97 of file PcepRsvpUserErrorSpec.java.
Member Data Documentation
final byte org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.CLASS_NUM = (byte) 0xc2 static
Definition at line 63 of file PcepRsvpUserErrorSpec.java.
Referenced by org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.getClassNum(), org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.read(), and org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.read().
final byte org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.CLASS_TYPE = 0x01 static
Definition at line 64 of file PcepRsvpUserErrorSpec.java.
Referenced by org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.getClassType(), and org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.read().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PcepRsvpUserErrorSpec.java