onos: org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth Class Reference
org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth Class Reference
Implements BGP unreserved bandwidth attribute.
Public Member Functions
BgpLinkAttrUnRsrvdLinkBandwidth (List< Float > maxUnResBandwidth, short sType)
Constructor to initialize the values.
List< Float > getLinkAttrUnRsrvdLinkBandwidth ()
Returns maximum unreserved bandwidth.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static
BgpLinkAttrUnRsrvdLinkBandwidth of (List< Float > linkPfxMetric, short sType)
Returns object of this class with specified values.
static
BgpLinkAttrUnRsrvdLinkBandwidth read (ChannelBuffer cb, short sType) throws BgpParseException
Reads the BGP link attributes of Maximum link bandwidth.
Public Attributes
short sType
Static Public Attributes
static final int MAX_BANDWIDTH_LEN = 4
static final int NO_OF_BITS = 8
static final int NO_OF_PRIORITY = 8
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP unreserved bandwidth attribute.
Definition at line 35 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.BgpLinkAttrUnRsrvdLinkBandwidth (List< Float > maxUnResBandwidth, short sType)
Constructor to initialize the values.
Parameters
maxUnResBandwidth Maximum Unreserved bandwidth
sType returns the tag value
Definition at line 55 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.sType.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.equals(), and org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.of().
Member Function Documentation
int org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 159 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
boolean org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.equals (Object obj)
Definition at line 134 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.BgpLinkAttrUnRsrvdLinkBandwidth().
List<Float> org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.getLinkAttrUnRsrvdLinkBandwidth ()
Returns maximum unreserved bandwidth.
Returns
unreserved bandwidth.
Definition at line 106 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
short org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 124 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.hashCode ()
Definition at line 129 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
static BgpLinkAttrUnRsrvdLinkBandwidth org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.of (List< Float > linkPfxMetric, short sType) static
Returns object of this class with specified values.
Parameters
linkPfxMetric Prefix Metric
sType returns the tag value
Returns
object of BgpLinkAttrUnRsrvdLinkBandwidth
Definition at line 68 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.BgpLinkAttrUnRsrvdLinkBandwidth().
static BgpLinkAttrUnRsrvdLinkBandwidth org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.read (ChannelBuffer cb, short sType) throws BgpParseException static
Reads the BGP link attributes of Maximum link bandwidth.
Parameters
cb Channel buffer
Returns
object of type BgpLinkAttrMaxLinkBandwidth
Exceptions
BgpParseException while parsing BgpLinkAttrMaxLinkBandwidth
Definition at line 79 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.MAX_BANDWIDTH_LEN, org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.NO_OF_BITS, org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.NO_OF_PRIORITY, org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.sType, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.toString ()
Definition at line 153 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 147 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
Member Data Documentation
final Logger org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpLinkAttrUnRsrvdLinkBandwidth.class)
Definition at line 37 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
final int org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.MAX_BANDWIDTH_LEN = 4 static
Definition at line 40 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.read().
final int org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.NO_OF_BITS = 8 static
Definition at line 41 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.read().
final int org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.NO_OF_PRIORITY = 8 static
Definition at line 42 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.read().
short org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.sType
Definition at line 44 of file BgpLinkAttrUnRsrvdLinkBandwidth.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.BgpLinkAttrUnRsrvdLinkBandwidth(), and org.onosproject.bgpio.types.attr.BgpLinkAttrUnRsrvdLinkBandwidth.read().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpLinkAttrUnRsrvdLinkBandwidth.java