onos: org.onosproject.cluster.DefaultControllerNode Class Reference
org.onosproject.cluster.DefaultControllerNode Class Reference
Default implementation of a controller instance descriptor.
Public Member Functions
DefaultControllerNode (NodeId id, IpAddress ip)
Creates a new instance with the specified id and IP address.
DefaultControllerNode (NodeId id, IpAddress ip, int tcpPort)
Creates a new instance with the specified id and IP address and TCP port.
NodeId id ()
Returns the instance identifier.
IpAddress ip ()
Returns the IP address of the controller instance.
int tcpPort ()
Returns the TCP port on which the node listens for connections.
int hashCode ()
boolean equals (Object o)
String toString ()
Static Public Attributes
static final int DEFAULT_PORT = 9876
Detailed Description
Default implementation of a controller instance descriptor.
Definition at line 28 of file DefaultControllerNode.java.
Constructor & Destructor Documentation
org.onosproject.cluster.DefaultControllerNode.DefaultControllerNode (NodeId id, IpAddress ip)
Creates a new instance with the specified id and IP address.
Parameters
id instance identifier
ip instance IP address
Definition at line 49 of file DefaultControllerNode.java.
References org.onosproject.cluster.DefaultControllerNode.DEFAULT_PORT, org.onosproject.cluster.DefaultControllerNode.id(), and org.onosproject.cluster.DefaultControllerNode.ip().
org.onosproject.cluster.DefaultControllerNode.DefaultControllerNode (NodeId id, IpAddress ip, int tcpPort)
Creates a new instance with the specified id and IP address and TCP port.
Parameters
id instance identifier
ip instance IP address
tcpPort TCP port
Definition at line 60 of file DefaultControllerNode.java.
References org.onosproject.cluster.DefaultControllerNode.ip(), and org.onosproject.cluster.DefaultControllerNode.tcpPort().
Member Function Documentation
boolean org.onosproject.cluster.DefaultControllerNode.equals (Object o)
Definition at line 87 of file DefaultControllerNode.java.
References find-device.id.
int org.onosproject.cluster.DefaultControllerNode.hashCode ()
Definition at line 82 of file DefaultControllerNode.java.
NodeId org.onosproject.cluster.DefaultControllerNode.id ()
Returns the instance identifier.
Returns
instance identifier
Implements org.onosproject.cluster.ControllerNode.
Definition at line 67 of file DefaultControllerNode.java.
Referenced by org.onosproject.cluster.DefaultControllerNode.DefaultControllerNode(), and org.onosproject.cluster.DefaultControllerNode.toString().
IpAddress org.onosproject.cluster.DefaultControllerNode.ip ()
Returns the IP address of the controller instance.
Returns
IP address
Implements org.onosproject.cluster.ControllerNode.
Definition at line 72 of file DefaultControllerNode.java.
Referenced by org.onosproject.cluster.DefaultControllerNode.DefaultControllerNode(), onos.ONOS.start(), org.onosproject.cluster.DefaultControllerNode.toString(), and onos.ONOS.updateHazelcast().
int org.onosproject.cluster.DefaultControllerNode.tcpPort ()
Returns the TCP port on which the node listens for connections.
Returns
TCP port
Implements org.onosproject.cluster.ControllerNode.
Definition at line 77 of file DefaultControllerNode.java.
Referenced by org.onosproject.cluster.DefaultControllerNode.DefaultControllerNode(), and org.onosproject.cluster.DefaultControllerNode.toString().
String org.onosproject.cluster.DefaultControllerNode.toString ()
Definition at line 99 of file DefaultControllerNode.java.
References org.onosproject.cluster.DefaultControllerNode.id(), org.onosproject.cluster.DefaultControllerNode.ip(), and org.onosproject.cluster.DefaultControllerNode.tcpPort().
Member Data Documentation
final int org.onosproject.cluster.DefaultControllerNode.DEFAULT_PORT = 9876 static
Definition at line 30 of file DefaultControllerNode.java.
Referenced by org.onosproject.cluster.DefaultControllerNode.DefaultControllerNode().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/cluster/DefaultControllerNode.java