onos: org.onosproject.net.driver.impl.DriverManager Class Reference
org.onosproject.net.driver.impl.DriverManager Class Reference
Manages inventory of device drivers.
Public Member Functions
Set< DriverProvider > getProviders ()
Returns the set of driver providers currently registered.
void registerProvider (DriverProvider provider)
Registers the specified driver provider.
void unregisterProvider (DriverProvider provider)
Unregisters the specified driver provider.
Set< Driver > getDrivers ()
Returns the set of driver types and behaviour implementations to be made available by this provider.
Set< Driver > getDrivers (Class<?extends Behaviour > withBehaviour)
Returns the set of drivers which support the specified behaviour.
Driver getDriver (String driverName)
Returns the specified driver.
Driver getDriver (String mfr, String hw, String sw)
Returns the driver that matches the specified primordial device discovery information.
Driver getDriver (DeviceId deviceId)
Returns the driver for the specified device.
DriverHandler createHandler (DeviceId deviceId, String...credentials)
Creates a new driver handler for interacting with the specified device.
Public Member Functions inherited from org.onosproject.net.driver.DefaultDriverProvider
Set< Driver > getDrivers ()
Returns the set of driver types and behaviour implementations to be made available by this provider.
void addDrivers (Set< Driver > drivers)
Adds the specified drivers to the provider.
void addDriver (Driver driver)
Adds the specified driver to the provider.
void removeDrivers (Set< Driver > drivers)
Removes the specified drivers from the provider.
void removeDriver (Driver driver)
Removes the specified driver from the provider.
String toString ()
Protected Member Functions
void activate ()
void deactivate ()
Protected Attributes
DeviceService deviceService
Protected Attributes inherited from org.onosproject.net.driver.DefaultDriverProvider
final Map< String, Driver > drivers = Maps.newConcurrentMap()
Detailed Description
Manages inventory of device drivers.
Definition at line 58 of file DriverManager.java.
Member Function Documentation
void org.onosproject.net.driver.impl.DriverManager.activate () protected
Definition at line 73 of file DriverManager.java.
DriverHandler org.onosproject.net.driver.impl.DriverManager.createHandler (DeviceId deviceId, String... credentials)
Creates a new driver handler for interacting with the specified device.
The driver is looked-up using the same semantics as getDriver(DeviceId) method.
Parameters
deviceId device identifier
credentials optional login credentials in string form
Returns
driver handler
Exceptions
org.onlab.util.ItemNotFoundException if device or driver for it are not found
Implements org.onosproject.net.driver.DriverService.
Definition at line 177 of file DriverManager.java.
References org.onosproject.net.driver.impl.DriverManager.getDriver().
void org.onosproject.net.driver.impl.DriverManager.deactivate () protected
Definition at line 78 of file DriverManager.java.
Driver org.onosproject.net.driver.impl.DriverManager.getDriver (String driverName)
Returns the specified driver.
Parameters
driverName driver name
Returns
driver
Exceptions
org.onlab.util.ItemNotFoundException if driver with the given name is not found
Implements org.onosproject.net.driver.DriverResolver.
Definition at line 129 of file DriverManager.java.
References org.onosproject.net.driver.DefaultDriverProvider.drivers.
Referenced by org.onosproject.net.driver.impl.DriverManager.createHandler(), and org.onosproject.net.driver.impl.DriverManager.getDriver().
Driver org.onosproject.net.driver.impl.DriverManager.getDriver (String mfr, String hw, String sw)
Returns the driver that matches the specified primordial device discovery information.
Parameters
mfr device manufacturer
hw device hardware name/version
sw device software version
Returns
driver or null of no matching one is found
Implements org.onosproject.net.driver.DriverService.
Definition at line 136 of file DriverManager.java.
Driver org.onosproject.net.driver.impl.DriverManager.getDriver (DeviceId deviceId)
Returns the driver for the specified device.
If the device carries
driver
annotation, its value is used to look-up the driver. Otherwise, the device manufacturer, hardware and software version attributes are used to look-up the driver. First using their literal values and if no driver is found, using ERE matching against the driver manufacturer, hardware and software version fields.
Parameters
deviceId device identifier
Returns
driver or null of no matching one is found
Exceptions
org.onlab.util.ItemNotFoundException if device or driver for it are not found
Implements org.onosproject.net.driver.DriverService.
Definition at line 163 of file DriverManager.java.
References create-flow.device, org.onosproject.net.driver.impl.DriverManager.deviceService, org.onosproject.net.device.DeviceService.getDevice(), org.onosproject.net.driver.impl.DriverManager.getDriver(), org.onosproject.net.Device.manufacturer(), and org.onosproject.net.Device.swVersion().
Set<Driver> org.onosproject.net.driver.impl.DriverManager.getDrivers ()
Returns the set of driver types and behaviour implementations to be made available by this provider.
Returns
set of driver types and their behaviours
Implements org.onosproject.net.driver.DriverProvider.
Definition at line 111 of file DriverManager.java.
Set<Driver> org.onosproject.net.driver.impl.DriverManager.getDrivers (Class<?extends Behaviour > withBehaviour)
Returns the set of drivers which support the specified behaviour.
Parameters
withBehaviour behaviour class to query by
Returns
provided drivers
Implements org.onosproject.net.driver.DriverService.
Definition at line 120 of file DriverManager.java.
Set<DriverProvider> org.onosproject.net.driver.impl.DriverManager.getProviders ()
Returns the set of driver providers currently registered.
Returns
registered driver providers
Implements org.onosproject.net.driver.DriverAdminService.
Definition at line 84 of file DriverManager.java.
void org.onosproject.net.driver.impl.DriverManager.registerProvider (DriverProvider provider)
Registers the specified driver provider.
Parameters
provider driver provider to register
Implements org.onosproject.net.driver.DriverAdminService.
Definition at line 89 of file DriverManager.java.
References org.onosproject.net.driver.DefaultDriverProvider.addDrivers(), and org.onosproject.net.driver.DriverProvider.getDrivers().
void org.onosproject.net.driver.impl.DriverManager.unregisterProvider (DriverProvider provider)
Unregisters the specified driver provider.
Parameters
provider driver provider to unregister
Implements org.onosproject.net.driver.DriverAdminService.
Definition at line 100 of file DriverManager.java.
References org.onosproject.net.driver.DriverProvider.getDrivers(), and org.onosproject.net.driver.DefaultDriverProvider.removeDrivers().
Member Data Documentation
DeviceService org.onosproject.net.driver.impl.DriverManager.deviceService protected
Definition at line 67 of file DriverManager.java.
Referenced by org.onosproject.net.driver.impl.DriverManager.getDriver().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/driver/impl/DriverManager.java