onos: org.onosproject.net.device.DefaultDeviceDescription Class Reference
org.onosproject.net.device.DefaultDeviceDescription Class Reference
Default implementation of immutable device description entity.
Public Member Functions
DefaultDeviceDescription (URI uri, Type type, String manufacturer, String hwVersion, String swVersion, String serialNumber, ChassisId chassis, SparseAnnotations...annotations)
Creates a device description using the supplied information.
DefaultDeviceDescription (DeviceDescription base, SparseAnnotations...annotations)
Creates a device description using the supplied information.
DefaultDeviceDescription (DeviceDescription base, Type type, SparseAnnotations...annotations)
Creates a device description using the supplied information.
URI deviceUri ()
Protocol/provider specific URI that can be used to encode the identity information required to communicate with the device externally, e.g.
Type type ()
Returns the type of the infrastructure device.
String manufacturer ()
Returns the device manufacturer name.
String hwVersion ()
Returns the device hardware version.
String swVersion ()
Returns the device software version.
String serialNumber ()
Returns the device serial number.
ChassisId chassisId ()
Returns a device chassis id.
String toString ()
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.AbstractDescription
SparseAnnotations annotations ()
Returns the key/value annotations.
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractDescription
AbstractDescription ()
AbstractDescription (SparseAnnotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of immutable device description entity.
Definition at line 32 of file DefaultDeviceDescription.java.
Constructor & Destructor Documentation
org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription (URI uri, Type type, String manufacturer, String hwVersion, String swVersion, String serialNumber, ChassisId chassis, SparseAnnotations... annotations)
Creates a device description using the supplied information.
Parameters
uri device URI
type device type
manufacturer device manufacturer
hwVersion device HW version
swVersion device SW version
serialNumber device serial number
chassis chassis id
annotations optional key/value annotations map
Definition at line 54 of file DefaultDeviceDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.device.DefaultDeviceDescription.hwVersion(), org.onosproject.net.device.DefaultDeviceDescription.manufacturer(), org.onosproject.net.device.DefaultDeviceDescription.serialNumber(), and org.onosproject.net.device.DefaultDeviceDescription.swVersion().
org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription (DeviceDescription base, SparseAnnotations... annotations)
Creates a device description using the supplied information.
Parameters
base DeviceDescription to basic information
annotations Annotations to use.
Definition at line 73 of file DefaultDeviceDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.device.DeviceDescription.hwVersion(), org.onosproject.net.device.DeviceDescription.serialNumber(), and org.onosproject.net.device.DeviceDescription.type().
org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription (DeviceDescription base, Type type, SparseAnnotations... annotations)
Creates a device description using the supplied information.
Parameters
base DeviceDescription to basic information (except for type)
type device type
annotations Annotations to use.
Definition at line 86 of file DefaultDeviceDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.device.DeviceDescription.chassisId(), org.onosproject.net.device.DeviceDescription.manufacturer(), and org.onosproject.net.device.DeviceDescription.swVersion().
Member Function Documentation
ChassisId org.onosproject.net.device.DefaultDeviceDescription.chassisId ()
Returns a device chassis id.
Returns
chassis id
Implements org.onosproject.net.device.DeviceDescription.
Definition at line 123 of file DefaultDeviceDescription.java.
Referenced by org.onosproject.net.device.DefaultDeviceDescription.hashCode().
URI org.onosproject.net.device.DefaultDeviceDescription.deviceUri ()
Protocol/provider specific URI that can be used to encode the identity information required to communicate with the device externally, e.g.
datapath ID.
Returns
provider specific URI for the device
Implements org.onosproject.net.device.DeviceDescription.
Definition at line 93 of file DefaultDeviceDescription.java.
boolean org.onosproject.net.device.DefaultDeviceDescription.equals (Object object)
Definition at line 143 of file DefaultDeviceDescription.java.
int org.onosproject.net.device.DefaultDeviceDescription.hashCode ()
Definition at line 137 of file DefaultDeviceDescription.java.
References org.onosproject.net.device.DefaultDeviceDescription.chassisId(), org.onosproject.net.device.DefaultDeviceDescription.hwVersion(), org.onosproject.net.device.DefaultDeviceDescription.manufacturer(), org.onosproject.net.device.DefaultDeviceDescription.serialNumber(), org.onosproject.net.device.DefaultDeviceDescription.swVersion(), and org.onosproject.net.device.DefaultDeviceDescription.type().
String org.onosproject.net.device.DefaultDeviceDescription.hwVersion ()
Returns the device hardware version.
Returns
hardware version
Implements org.onosproject.net.device.DeviceDescription.
Definition at line 108 of file DefaultDeviceDescription.java.
Referenced by org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription(), org.onosproject.net.device.DefaultDeviceDescription.hashCode(), and org.onosproject.net.device.DefaultDeviceDescription.toString().
String org.onosproject.net.device.DefaultDeviceDescription.manufacturer ()
Returns the device manufacturer name.
Returns
manufacturer name
Implements org.onosproject.net.device.DeviceDescription.
Definition at line 103 of file DefaultDeviceDescription.java.
Referenced by org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription(), org.onosproject.net.device.DefaultDeviceDescription.hashCode(), and org.onosproject.net.device.DefaultDeviceDescription.toString().
String org.onosproject.net.device.DefaultDeviceDescription.serialNumber ()
Returns the device serial number.
Returns
serial number
Implements org.onosproject.net.device.DeviceDescription.
Definition at line 118 of file DefaultDeviceDescription.java.
Referenced by org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription(), org.onosproject.net.device.DefaultDeviceDescription.hashCode(), and org.onosproject.net.device.DefaultDeviceDescription.toString().
String org.onosproject.net.device.DefaultDeviceDescription.swVersion ()
Returns the device software version.
Returns
software version
Implements org.onosproject.net.device.DeviceDescription.
Definition at line 113 of file DefaultDeviceDescription.java.
Referenced by org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription(), org.onosproject.net.device.DefaultDeviceDescription.hashCode(), and org.onosproject.net.device.DefaultDeviceDescription.toString().
String org.onosproject.net.device.DefaultDeviceDescription.toString ()
Definition at line 128 of file DefaultDeviceDescription.java.
References org.onosproject.net.device.DefaultDeviceDescription.hwVersion(), org.onosproject.net.device.DefaultDeviceDescription.manufacturer(), org.onosproject.net.device.DefaultDeviceDescription.serialNumber(), org.onosproject.net.device.DefaultDeviceDescription.swVersion(), and org.onosproject.net.device.DefaultDeviceDescription.type().
Type org.onosproject.net.device.DefaultDeviceDescription.type ()
Returns the type of the infrastructure device.
Returns
type of the device
Implements org.onosproject.net.device.DeviceDescription.
Definition at line 98 of file DefaultDeviceDescription.java.
Referenced by org.onosproject.net.device.DefaultDeviceDescription.hashCode(), and org.onosproject.net.device.DefaultDeviceDescription.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/device/DefaultDeviceDescription.java