onos: org.onlab.packet.ipv6.RoutingTest Class Reference
org.onlab.packet.ipv6.RoutingTest Class Reference
Tests for class Routing.
Public Member Functions
void setUp ()
void testSerialize ()
Tests serialize and setters.
void testDeserialize () throws DeserializationException
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class Routing.
Definition at line 36 of file RoutingTest.java.
Member Function Documentation
void org.onlab.packet.ipv6.RoutingTest.setUp ()
Definition at line 72 of file RoutingTest.java.
static void org.onlab.packet.ipv6.RoutingTest.setUpBeforeClass () throws Exception static
Definition at line 51 of file RoutingTest.java.
References find-link-in-cluster.length.
void org.onlab.packet.ipv6.RoutingTest.testDeserialize () throws DeserializationException
Tests deserialize and getters.
Definition at line 96 of file RoutingTest.java.
References org.onlab.packet.ipv6.Routing.getHeaderExtLength(), org.onlab.packet.ipv6.Routing.getNextHeader(), org.onlab.packet.ipv6.Routing.getRoutingData(), org.onlab.packet.ipv6.Routing.getRoutingType(), org.onlab.packet.ipv6.Routing.getSegmentsLeft(), and find-link-in-cluster.length.
void org.onlab.packet.ipv6.RoutingTest.testEqual ()
Tests comparator.
Definition at line 110 of file RoutingTest.java.
References org.onlab.packet.ipv6.Routing.equals().
void org.onlab.packet.ipv6.RoutingTest.testSerialize ()
Tests serialize and setters.
Definition at line 80 of file RoutingTest.java.
References org.onlab.packet.ipv6.Routing.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ipv6/RoutingTest.java