onos: org.onosproject.net.IndexedLambda Class Reference
org.onosproject.net.IndexedLambda Class Reference
Implementation of Lambda simply designated by an index number of wavelength.
Public Member Functions
IndexedLambda (long index)
Creates an instance representing the wavelength specified by the given index number.
long index ()
Returns the index number of lambda.
int hashCode ()
boolean equals (Object obj)
String toString ()
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.net.Lambda
static Lambda indexedLambda (long lambda)
Create an Lambda instance with the specified wavelength index number.
static Lambda ochSignal (GridType gridType, ChannelSpacing channelSpacing, int spacingMultiplier, int slotGranularity)
Creates a Lambda instance with the specified arguments.
Detailed Description
Implementation of Lambda simply designated by an index number of wavelength.
Definition at line 23 of file IndexedLambda.java.
Constructor & Destructor Documentation
org.onosproject.net.IndexedLambda.IndexedLambda (long index)
Creates an instance representing the wavelength specified by the given index number.
It is recommended to use Lambda#indexedLambda(long) unless you want to use the concrete type, IndexedLambda, directly.
Parameters
index index number of wavelength
Definition at line 34 of file IndexedLambda.java.
References org.onosproject.net.IndexedLambda.index().
Referenced by org.onosproject.net.IndexedLambda.equals().
Member Function Documentation
boolean org.onosproject.net.IndexedLambda.equals (Object obj)
Definition at line 53 of file IndexedLambda.java.
References org.onosproject.net.IndexedLambda.IndexedLambda().
int org.onosproject.net.IndexedLambda.hashCode ()
Definition at line 48 of file IndexedLambda.java.
References org.onosproject.net.IndexedLambda.index().
long org.onosproject.net.IndexedLambda.index ()
Returns the index number of lambda.
Returns
the index number of lambda
Definition at line 43 of file IndexedLambda.java.
Referenced by org.onosproject.net.IndexedLambda.hashCode(), org.onosproject.net.IndexedLambda.IndexedLambda(), and org.onosproject.net.IndexedLambda.toString().
String org.onosproject.net.IndexedLambda.toString ()
Definition at line 66 of file IndexedLambda.java.
References org.onosproject.net.IndexedLambda.index().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/IndexedLambda.java