onos: org.onosproject.bgprouter.NextHop Class Reference
org.onosproject.bgprouter.NextHop Class Reference
Represents a next hop for routing, whose MAC address has already been resolved.
Public Member Functions
NextHop (IpAddress ip, MacAddress mac, NextHopGroupKey group)
Creates a new next hop.
IpAddress ip ()
Returns the next hop's IP address.
MacAddress mac ()
Returns the next hop's MAC address.
NextHopGroupKey group ()
Returns the next hop group.
boolean equals (Object o)
int hashCode ()
String toString ()
Detailed Description
Represents a next hop for routing, whose MAC address has already been resolved.
Definition at line 28 of file NextHop.java.
Constructor & Destructor Documentation
org.onosproject.bgprouter.NextHop.NextHop (IpAddress ip, MacAddress mac, NextHopGroupKey group)
Creates a new next hop.
Parameters
ip next hop's IP address
mac next hop's MAC address
group next hop's group
Definition at line 41 of file NextHop.java.
References org.onosproject.bgprouter.NextHop.group(), org.onosproject.bgprouter.NextHop.ip(), and org.onosproject.bgprouter.NextHop.mac().
Referenced by org.onosproject.bgprouter.NextHop.equals().
Member Function Documentation
boolean org.onosproject.bgprouter.NextHop.equals (Object o)
Definition at line 75 of file NextHop.java.
References org.onosproject.bgprouter.NextHop.NextHop().
NextHopGroupKey org.onosproject.bgprouter.NextHop.group ()
Returns the next hop group.
Returns
group
Definition at line 70 of file NextHop.java.
Referenced by org.onosproject.bgprouter.NextHop.hashCode(), org.onosproject.bgprouter.NextHop.NextHop(), and org.onosproject.bgprouter.NextHop.toString().
int org.onosproject.bgprouter.NextHop.hashCode ()
Definition at line 88 of file NextHop.java.
References org.onosproject.bgprouter.NextHop.group(), org.onosproject.bgprouter.NextHop.ip(), and org.onosproject.bgprouter.NextHop.mac().
IpAddress org.onosproject.bgprouter.NextHop.ip ()
Returns the next hop's IP address.
Returns
next hop's IP address
Definition at line 52 of file NextHop.java.
Referenced by org.onosproject.bgprouter.NextHop.hashCode(), org.onosproject.bgprouter.NextHop.NextHop(), onos.ONOS.start(), org.onosproject.bgprouter.NextHop.toString(), and onos.ONOS.updateHazelcast().
MacAddress org.onosproject.bgprouter.NextHop.mac ()
Returns the next hop's MAC address.
Returns
next hop's MAC address
Definition at line 61 of file NextHop.java.
Referenced by org.onosproject.bgprouter.NextHop.hashCode(), org.onosproject.bgprouter.NextHop.NextHop(), and org.onosproject.bgprouter.NextHop.toString().
String org.onosproject.bgprouter.NextHop.toString ()
Definition at line 93 of file NextHop.java.
References org.onosproject.bgprouter.NextHop.group(), org.onosproject.bgprouter.NextHop.ip(), and org.onosproject.bgprouter.NextHop.mac().
The documentation for this class was generated from the following file:
apps/bgprouter/src/main/java/org/onosproject/bgprouter/NextHop.java