onos: org.onlab.packet.ndp.NeighborDiscoveryOptions Class Reference
org.onlab.packet.ndp.NeighborDiscoveryOptions Class Reference
Neighbor Discovery Protocol packet options.
Classes
class Option
Packet option.
Public Member Functions
NeighborDiscoveryOptions addOption (byte type, byte[] data)
Adds a Neighbor Discovery Protocol packet option.
List
< NeighborDiscoveryOptions.Option > options ()
Gets the Neighbor Discovery Protocol packet options.
boolean hasOptions ()
Checks whether any options are included.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer
< NeighborDiscoveryOptions > deserializer ()
Static Public Attributes
static final byte TYPE_SOURCE_LL_ADDRESS = 1
static final byte TYPE_TARGET_LL_ADDRESS = 2
static final byte TYPE_PREFIX_INFORMATION = 3
static final byte TYPE_REDIRECTED_HEADER = 4
static final byte TYPE_MTU = 5
static final byte INITIAL_HEADER_REQUIRED = 2
Additional Inherited Members
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Neighbor Discovery Protocol packet options.
Definition at line 33 of file NeighborDiscoveryOptions.java.
Member Function Documentation
NeighborDiscoveryOptions org.onlab.packet.ndp.NeighborDiscoveryOptions.addOption (byte type, byte[] data)
Adds a Neighbor Discovery Protocol packet option.
Parameters
type the option type
data the option data
Returns
this
Definition at line 129 of file NeighborDiscoveryOptions.java.
Referenced by org.onlab.packet.ndp.NeighborDiscoveryOptions.deserialize().
IPacket org.onlab.packet.ndp.NeighborDiscoveryOptions.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 184 of file NeighborDiscoveryOptions.java.
References org.onlab.packet.ndp.NeighborDiscoveryOptions.addOption(), and find-link-in-cluster.length.
static Deserializer<NeighborDiscoveryOptions> org.onlab.packet.ndp.NeighborDiscoveryOptions.deserializer () static
Definition at line 242 of file NeighborDiscoveryOptions.java.
References org.onlab.packet.ndp.NeighborDiscoveryOptions.INITIAL_HEADER_REQUIRED, and find-link-in-cluster.length.
boolean org.onlab.packet.ndp.NeighborDiscoveryOptions.equals (final Object obj)
Definition at line 231 of file NeighborDiscoveryOptions.java.
Referenced by org.onlab.packet.ndp.RouterSolicitation.equals(), org.onlab.packet.ndp.NeighborSolicitation.equals(), org.onlab.packet.ndp.Redirect.equals(), org.onlab.packet.ndp.NeighborAdvertisement.equals(), and org.onlab.packet.ndp.RouterAdvertisement.equals().
int org.onlab.packet.ndp.NeighborDiscoveryOptions.hashCode ()
Definition at line 219 of file NeighborDiscoveryOptions.java.
References org.onlab.packet.ndp.NeighborDiscoveryOptions.options().
boolean org.onlab.packet.ndp.NeighborDiscoveryOptions.hasOptions ()
Checks whether any options are included.
Returns
true if options are included, otherwise false
Definition at line 148 of file NeighborDiscoveryOptions.java.
Referenced by org.onlab.packet.ndp.RouterSolicitation.serialize(), org.onlab.packet.ndp.NeighborSolicitation.serialize(), org.onlab.packet.ndp.Redirect.serialize(), org.onlab.packet.ndp.NeighborAdvertisement.serialize(), and org.onlab.packet.ndp.RouterAdvertisement.serialize().
List<NeighborDiscoveryOptions.Option> org.onlab.packet.ndp.NeighborDiscoveryOptions.options ()
Gets the Neighbor Discovery Protocol packet options.
Returns
the Neighbor Discovery Protocol packet options
Definition at line 139 of file NeighborDiscoveryOptions.java.
Referenced by org.onlab.packet.ndp.NeighborDiscoveryOptions.hashCode(), and org.onlab.packet.ndp.NeighborDiscoveryOptions.serialize().
byte [] org.onlab.packet.ndp.NeighborDiscoveryOptions.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 153 of file NeighborDiscoveryOptions.java.
References org.onlab.packet.ndp.NeighborDiscoveryOptions.options().
Member Data Documentation
final byte org.onlab.packet.ndp.NeighborDiscoveryOptions.INITIAL_HEADER_REQUIRED = 2 static
Definition at line 40 of file NeighborDiscoveryOptions.java.
Referenced by org.onlab.packet.ndp.NeighborDiscoveryOptions.deserializer().
final byte org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_MTU = 5 static
Definition at line 38 of file NeighborDiscoveryOptions.java.
final byte org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_PREFIX_INFORMATION = 3 static
Definition at line 36 of file NeighborDiscoveryOptions.java.
final byte org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_REDIRECTED_HEADER = 4 static
Definition at line 37 of file NeighborDiscoveryOptions.java.
final byte org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_SOURCE_LL_ADDRESS = 1 static
Definition at line 34 of file NeighborDiscoveryOptions.java.
final byte org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS = 2 static
Definition at line 35 of file NeighborDiscoveryOptions.java.
Referenced by org.onlab.packet.ndp.RouterSolicitationTest.testDeserialize(), org.onlab.packet.ndp.RouterAdvertisementTest.testDeserialize(), org.onlab.packet.ndp.NeighborAdvertisementTest.testDeserialize(), org.onlab.packet.ndp.NeighborSolicitationTest.testDeserialize(), org.onlab.packet.ndp.RedirectTest.testDeserialize(), org.onlab.packet.ndp.RouterSolicitationTest.testEqual(), org.onlab.packet.ndp.RouterAdvertisementTest.testEqual(), org.onlab.packet.ndp.NeighborSolicitationTest.testEqual(), org.onlab.packet.ndp.NeighborAdvertisementTest.testEqual(), org.onlab.packet.ndp.RedirectTest.testEqual(), org.onlab.packet.ndp.RouterSolicitationTest.testSerialize(), org.onlab.packet.ndp.RouterAdvertisementTest.testSerialize(), org.onlab.packet.ndp.NeighborAdvertisementTest.testSerialize(), org.onlab.packet.ndp.NeighborSolicitationTest.testSerialize(), and org.onlab.packet.ndp.RedirectTest.testSerialize().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ndp/NeighborDiscoveryOptions.java