onos: org.onosproject.net.intent.impl.compiler.HostToHostIntentCompilerTest Class Reference
org.onosproject.net.intent.impl.compiler.HostToHostIntentCompilerTest Class Reference
Unit tests for the HostToHost intent compiler.
Public Member Functions
void setUp () throws Exception
void testSingleLongPathCompilation ()
Tests a pair of hosts with 8 hops between them.
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Additional Inherited Members
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
Unit tests for the HostToHost intent compiler.
Definition at line 49 of file HostToHostIntentCompilerTest.java.
Member Function Documentation
void org.onosproject.net.intent.impl.compiler.HostToHostIntentCompilerTest.setUp () throws Exception
Definition at line 67 of file HostToHostIntentCompilerTest.java.
References org.onosproject.net.host.HostService.getHost(), org.onosproject.net.Host.mac(), org.onosproject.net.Host.vlan(), and org.onlab.packet.VlanId.vlanId().
void org.onosproject.net.intent.impl.compiler.HostToHostIntentCompilerTest.testSingleLongPathCompilation ()
Tests a pair of hosts with 8 hops between them.
Definition at line 121 of file HostToHostIntentCompilerTest.java.
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/intent/impl/compiler/HostToHostIntentCompilerTest.java