onos: org.onosproject.store.service.DatabaseUpdate Class Reference
org.onosproject.store.service.DatabaseUpdate Class Reference
Database update operation.
Classes
class Builder
DatabaseUpdate builder.
enum Type
Type of database update operation.
Public Member Functions
Type type ()
Returns the type of update operation.
String mapName ()
Returns the name of map being updated.
String key ()
Returns the item key being updated.
byte[] value ()
Returns the new value.
byte[] currentValue ()
Returns the expected current value in the database value for the key.
long currentVersion ()
Returns the expected current version in the database for the key.
String toString ()
Static Public Member Functions
static Builder newBuilder ()
Creates a new builder instance.
Detailed Description
Database update operation.
Definition at line 29 of file DatabaseUpdate.java.
Member Function Documentation
byte [] org.onosproject.store.service.DatabaseUpdate.currentValue ()
Returns the expected current value in the database value for the key.
Returns
current value in database.
Definition at line 113 of file DatabaseUpdate.java.
Referenced by org.onosproject.store.service.DatabaseUpdate.toString().
long org.onosproject.store.service.DatabaseUpdate.currentVersion ()
Returns the expected current version in the database for the key.
Returns
expected version.
Definition at line 121 of file DatabaseUpdate.java.
Referenced by org.onosproject.store.service.DatabaseUpdate.toString().
String org.onosproject.store.service.DatabaseUpdate.key ()
Returns the item key being updated.
Returns
item key
Definition at line 97 of file DatabaseUpdate.java.
Referenced by org.onosproject.store.service.DatabaseUpdate.toString().
String org.onosproject.store.service.DatabaseUpdate.mapName ()
Returns the name of map being updated.
Returns
map name.
Definition at line 89 of file DatabaseUpdate.java.
Referenced by org.onosproject.store.service.DatabaseUpdate.toString().
static Builder org.onosproject.store.service.DatabaseUpdate.newBuilder () static
Creates a new builder instance.
Returns
builder.
Definition at line 142 of file DatabaseUpdate.java.
String org.onosproject.store.service.DatabaseUpdate.toString ()
Definition at line 126 of file DatabaseUpdate.java.
References org.onosproject.store.service.DatabaseUpdate.currentValue(), org.onosproject.store.service.DatabaseUpdate.currentVersion(), org.onosproject.store.service.DatabaseUpdate.key(), org.onosproject.store.service.DatabaseUpdate.mapName(), org.onosproject.store.service.DatabaseUpdate.type(), and org.onosproject.store.service.DatabaseUpdate.value().
Referenced by org.onosproject.store.service.DatabaseUpdateTest.testToString().
Type org.onosproject.store.service.DatabaseUpdate.type ()
Returns the type of update operation.
Returns
type of update.
Definition at line 81 of file DatabaseUpdate.java.
Referenced by org.onosproject.store.service.DatabaseUpdate.toString().
byte [] org.onosproject.store.service.DatabaseUpdate.value ()
Returns the new value.
Returns
item's target value.
Definition at line 105 of file DatabaseUpdate.java.
Referenced by org.onosproject.store.service.DatabaseUpdate.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/store/service/DatabaseUpdate.java