onos: org.onosproject.net.host.HostEvent Class Reference
org.onosproject.net.host.HostEvent Class Reference
Describes end-station host event.
Classes
enum Type
Type of host events.
Public Member Functions
HostEvent (Type type, Host host)
Creates an event of a given type and for the specified host and the current time.
HostEvent (Type type, Host host, long time)
Creates an event of a given type and for the specified host and time.
HostEvent (Type type, Host host, Host prevSubject)
Creates an event with previous subject.
Host prevSubject ()
Gets the previous subject in this host event.
String toString ()
Detailed Description
Describes end-station host event.
Definition at line 27 of file HostEvent.java.
Constructor & Destructor Documentation
org.onosproject.net.host.HostEvent.HostEvent (Type type, Host host)
Creates an event of a given type and for the specified host and the current time.
Parameters
type host event type
host event host subject
Definition at line 63 of file HostEvent.java.
org.onosproject.net.host.HostEvent.HostEvent (Type type, Host host, long time)
Creates an event of a given type and for the specified host and time.
Parameters
type host event type
host event host subject
time occurrence time
Definition at line 74 of file HostEvent.java.
org.onosproject.net.host.HostEvent.HostEvent (Type type, Host host, Host prevSubject)
Creates an event with previous subject.
The previous subject is ignored if the type is not moved or updated
Parameters
type host event type
host event host subject
prevSubject previous host subject
Definition at line 87 of file HostEvent.java.
References org.onosproject.net.host.HostEvent.Type.HOST_MOVED, org.onosproject.net.host.HostEvent.Type.HOST_UPDATED, and org.onosproject.net.host.HostEvent.prevSubject().
Member Function Documentation
Host org.onosproject.net.host.HostEvent.prevSubject ()
Gets the previous subject in this host event.
Returns
the previous subject, or null if previous subject is not specified.
Definition at line 100 of file HostEvent.java.
Referenced by org.onosproject.net.host.HostEvent.HostEvent(), and org.onosproject.net.host.HostEvent.toString().
String org.onosproject.net.host.HostEvent.toString ()
Definition at line 105 of file HostEvent.java.
References org.onosproject.net.host.HostEvent.prevSubject().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/host/HostEvent.java