onos: org.onosproject.bgpio.types.IsIsNonPseudonode Class Reference
org.onosproject.bgpio.types.IsIsNonPseudonode Class Reference
Provides Implementation of IsIsNonPseudonode Tlv.
Public Member Functions
IsIsNonPseudonode (byte[] isoNodeID)
Constructor to initialize isoNodeID.
byte[] getISONodeID ()
Returns ISO NodeID.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of BGP Message to channel buffer.
short getType ()
Returns the Type of BGP Message.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static IsIsNonPseudonode of (final byte[] isoNodeID)
Returns object of this class with specified isoNodeID.
static IsIsNonPseudonode read (ChannelBuffer cb)
Reads the channel buffer and returns object of IsIsNonPseudonode.
Static Public Attributes
static final short TYPE = 515
static final short LENGTH = 6
Detailed Description
Provides Implementation of IsIsNonPseudonode Tlv.
Definition at line 29 of file IsIsNonPseudonode.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.IsIsNonPseudonode.IsIsNonPseudonode (byte[] isoNodeID)
Constructor to initialize isoNodeID.
Parameters
isoNodeID ISO system-ID
Definition at line 40 of file IsIsNonPseudonode.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.bgpio.types.IsIsNonPseudonode.compareTo(), org.onosproject.bgpio.types.IsIsNonPseudonode.equals(), and org.onosproject.bgpio.types.IsIsNonPseudonode.of().
Member Function Documentation
int org.onosproject.bgpio.types.IsIsNonPseudonode.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 107 of file IsIsNonPseudonode.java.
References org.onosproject.bgpio.types.IsIsNonPseudonode.equals(), and org.onosproject.bgpio.types.IsIsNonPseudonode.IsIsNonPseudonode().
boolean org.onosproject.bgpio.types.IsIsNonPseudonode.equals (Object obj)
Definition at line 69 of file IsIsNonPseudonode.java.
References org.onosproject.bgpio.types.IsIsNonPseudonode.IsIsNonPseudonode().
Referenced by org.onosproject.bgpio.types.IsIsNonPseudonode.compareTo().
byte [] org.onosproject.bgpio.types.IsIsNonPseudonode.getISONodeID ()
Returns ISO NodeID.
Returns
ISO NodeID
Definition at line 59 of file IsIsNonPseudonode.java.
short org.onosproject.bgpio.types.IsIsNonPseudonode.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 102 of file IsIsNonPseudonode.java.
References org.onosproject.bgpio.types.IsIsNonPseudonode.TYPE.
int org.onosproject.bgpio.types.IsIsNonPseudonode.hashCode ()
Definition at line 64 of file IsIsNonPseudonode.java.
static IsIsNonPseudonode org.onosproject.bgpio.types.IsIsNonPseudonode.of (final byte[] isoNodeID) static
Returns object of this class with specified isoNodeID.
Parameters
isoNodeID ISO system-ID
Returns
object of IsIsNonPseudonode
Definition at line 50 of file IsIsNonPseudonode.java.
References org.onosproject.bgpio.types.IsIsNonPseudonode.IsIsNonPseudonode().
static IsIsNonPseudonode org.onosproject.bgpio.types.IsIsNonPseudonode.read (ChannelBuffer cb) static
Reads the channel buffer and returns object of IsIsNonPseudonode.
Parameters
cb ChannelBuffer
Returns
object of IsIsNonPseudonode
Definition at line 95 of file IsIsNonPseudonode.java.
References org.onosproject.bgpio.types.IsIsNonPseudonode.LENGTH.
String org.onosproject.bgpio.types.IsIsNonPseudonode.toString ()
Definition at line 117 of file IsIsNonPseudonode.java.
References org.onosproject.bgpio.types.IsIsNonPseudonode.LENGTH, and org.onosproject.bgpio.types.IsIsNonPseudonode.TYPE.
int org.onosproject.bgpio.types.IsIsNonPseudonode.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 81 of file IsIsNonPseudonode.java.
References org.onosproject.bgpio.types.IsIsNonPseudonode.LENGTH, and org.onosproject.bgpio.types.IsIsNonPseudonode.TYPE.
Member Data Documentation
final short org.onosproject.bgpio.types.IsIsNonPseudonode.LENGTH = 6 static
Definition at line 31 of file IsIsNonPseudonode.java.
Referenced by org.onosproject.bgpio.types.IsIsNonPseudonode.read(), org.onosproject.bgpio.types.IsIsNonPseudonode.toString(), and org.onosproject.bgpio.types.IsIsNonPseudonode.write().
final short org.onosproject.bgpio.types.IsIsNonPseudonode.TYPE = 515 static
Definition at line 30 of file IsIsNonPseudonode.java.
Referenced by org.onosproject.bgpio.types.IsIsNonPseudonode.getType(), org.onosproject.bgpio.types.IsIsNonPseudonode.toString(), and org.onosproject.bgpio.types.IsIsNonPseudonode.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/IsIsNonPseudonode.java