onos: org.onosproject.net.flow.criteria.EthCriterion Class Reference
org.onosproject.net.flow.criteria.EthCriterion Class Reference
Implementation of MAC address criterion.
Public Member Functions
Type type ()
Returns the type of criterion.
MacAddress mac ()
Gets the MAC address to match.
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Implementation of MAC address criterion.
Definition at line 27 of file EthCriterion.java.
Member Function Documentation
boolean org.onosproject.net.flow.criteria.EthCriterion.equals (Object obj)
Definition at line 69 of file EthCriterion.java.
References org.onosproject.net.flow.criteria.EthCriterion.mac(), and obeliskHostCheck.mac.
int org.onosproject.net.flow.criteria.EthCriterion.hashCode ()
Definition at line 64 of file EthCriterion.java.
MacAddress org.onosproject.net.flow.criteria.EthCriterion.mac ()
Gets the MAC address to match.
Returns
the MAC address to match
Definition at line 53 of file EthCriterion.java.
References obeliskHostCheck.mac.
Referenced by org.onosproject.net.flow.criteria.EthCriterion.equals(), and org.onosproject.net.flow.criteria.EthCriterion.toString().
String org.onosproject.net.flow.criteria.EthCriterion.toString ()
Definition at line 58 of file EthCriterion.java.
References org.onosproject.net.flow.criteria.EthCriterion.mac(), and org.onosproject.net.flow.criteria.EthCriterion.type().
Type org.onosproject.net.flow.criteria.EthCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 44 of file EthCriterion.java.
Referenced by org.onosproject.net.flow.criteria.EthCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/EthCriterion.java