onos: org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag Class Reference
org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag Class Reference
Implements BGP prefix route tag attribute.
Public Member Functions
BgpPrefixAttrRouteTag (List< Integer > pfxRouteTag)
Constructor to initialize the values.
List< Integer > getPfxRouteTag ()
Returns the prefix route tag.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpPrefixAttrRouteTag of (ArrayList< Integer > pfxRouteTag)
Returns object of this class with specified values.
static BgpPrefixAttrRouteTag read (ChannelBuffer cb) throws BgpParseException
Reads the Route Tag.
Static Public Attributes
static final short ATTR_PREFIX_ROUTETAG = 1153
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP prefix route tag attribute.
Definition at line 35 of file BgpPrefixAttrRouteTag.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.BgpPrefixAttrRouteTag (List< Integer > pfxRouteTag)
Constructor to initialize the values.
Parameters
pfxRouteTag prefix route tag
Definition at line 50 of file BgpPrefixAttrRouteTag.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.equals(), and org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.of().
Member Function Documentation
int org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 138 of file BgpPrefixAttrRouteTag.java.
boolean org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.equals (Object obj)
Definition at line 113 of file BgpPrefixAttrRouteTag.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.BgpPrefixAttrRouteTag().
List<Integer> org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.getPfxRouteTag ()
Returns the prefix route tag.
Returns
route tag
Definition at line 98 of file BgpPrefixAttrRouteTag.java.
short org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 103 of file BgpPrefixAttrRouteTag.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.ATTR_PREFIX_ROUTETAG.
int org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.hashCode ()
Definition at line 108 of file BgpPrefixAttrRouteTag.java.
static BgpPrefixAttrRouteTag org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.of (ArrayList< Integer > pfxRouteTag) static
Returns object of this class with specified values.
Parameters
pfxRouteTag Prefix Metric
Returns
object of BgpPrefixAttrRouteTag
Definition at line 60 of file BgpPrefixAttrRouteTag.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.BgpPrefixAttrRouteTag().
static BgpPrefixAttrRouteTag org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.read (ChannelBuffer cb) throws BgpParseException static
Reads the Route Tag.
Parameters
cb ChannelBuffer
Returns
object of BgpPrefixAttrRouteTag
Exceptions
BgpParseException while parsing BgpPrefixAttrRouteTag
Definition at line 71 of file BgpPrefixAttrRouteTag.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.toString ()
Definition at line 132 of file BgpPrefixAttrRouteTag.java.
int org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 126 of file BgpPrefixAttrRouteTag.java.
Member Data Documentation
final short org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.ATTR_PREFIX_ROUTETAG = 1153 static
Definition at line 40 of file BgpPrefixAttrRouteTag.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.getType().
final Logger org.onosproject.bgpio.types.attr.BgpPrefixAttrRouteTag.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpPrefixAttrRouteTag.class)
Definition at line 37 of file BgpPrefixAttrRouteTag.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpPrefixAttrRouteTag.java