onos: org.onosproject.store.intent.impl.GossipIntentStoreTest Class Reference
org.onosproject.store.intent.impl.GossipIntentStoreTest Class Reference
Gossip Intent Store test using database adapter.
Public Member Functions
void setUp ()
void cleanUp ()
void testGetIntentCount ()
Tests the intent count APIs.
void testBatchAdd ()
Tests the batch add API.
void testAddAndWithdrawIntent ()
Tests adding and withdrawing an Intent.
void testPending ()
Tests the operation of the APIs for the pending map.
Detailed Description
Gossip Intent Store test using database adapter.
Definition at line 45 of file GossipIntentStoreTest.java.
Member Function Documentation
void org.onosproject.store.intent.impl.GossipIntentStoreTest.cleanUp ()
Definition at line 68 of file GossipIntentStoreTest.java.
void org.onosproject.store.intent.impl.GossipIntentStoreTest.setUp ()
Definition at line 52 of file GossipIntentStoreTest.java.
void org.onosproject.store.intent.impl.GossipIntentStoreTest.testAddAndWithdrawIntent ()
Tests adding and withdrawing an Intent.
Definition at line 123 of file GossipIntentStoreTest.java.
References org.onosproject.store.intent.impl.GossipIntentStore.getIntentCount(), org.onosproject.net.intent.IntentState.INSTALLED, and org.onosproject.net.intent.IntentState.PURGE_REQ.
void org.onosproject.store.intent.impl.GossipIntentStoreTest.testBatchAdd ()
Tests the batch add API.
Definition at line 109 of file GossipIntentStoreTest.java.
References org.onosproject.store.intent.impl.GossipIntentStore.getIntentCount().
void org.onosproject.store.intent.impl.GossipIntentStoreTest.testGetIntentCount ()
Tests the intent count APIs.
Definition at line 97 of file GossipIntentStoreTest.java.
References org.onosproject.store.intent.impl.GossipIntentStore.getIntentCount().
void org.onosproject.store.intent.impl.GossipIntentStoreTest.testPending ()
Tests the operation of the APIs for the pending map.
Definition at line 192 of file GossipIntentStoreTest.java.
References org.onosproject.net.intent.IntentState.INSTALLED.
The documentation for this class was generated from the following file:
core/store/dist/src/test/java/org/onosproject/store/intent/impl/GossipIntentStoreTest.java