onos: org.onlab.graph.DijkstraGraphSearchTest Class Reference
org.onlab.graph.DijkstraGraphSearchTest Class Reference
Test of the Dijkstra algorithm.
Public Member Functions
void defaultGraphTest ()
void defaultHopCountWeight ()
void noPath ()
void simpleMultiplePath ()
void denseMultiplePath ()
void dualEdgeMultiplePath ()
void negativeWeights ()
void disconnectedPerf ()
void disconnected ()
Public Member Functions inherited from org.onlab.graph.BreadthFirstSearchTest
void defaultGraphTest ()
void defaultHopCountWeight ()
Public Member Functions inherited from org.onlab.graph.AbstractGraphPathSearchTest
void noSuchSourceArgument ()
void nullGraphArgument ()
void nullSourceArgument ()
void samenessThreshold ()
Protected Member Functions
AbstractGraphPathSearch
< TestVertex, TestEdge > graphSearch ()
Creates a test-specific graph search to exercise.
Protected Member Functions inherited from org.onlab.graph.BreadthFirstSearchTest
void executeDefaultTest (int pathCount, int pathLength, double pathCost)
void executeSearch (GraphPathSearch< TestVertex, TestEdge > search, Graph< TestVertex, TestEdge > graph, TestVertex src, TestVertex dst, EdgeWeight< TestVertex, TestEdge > weight, int pathCount, double pathCost)
void executeSinglePathSearch (GraphPathSearch< TestVertex, TestEdge > search, Graph< TestVertex, TestEdge > graph, TestVertex src, TestVertex dst, EdgeWeight< TestVertex, TestEdge > weight, int pathCount, double pathCost)
Protected Member Functions inherited from org.onlab.graph.GraphTest
void printPaths (Set< Path< TestVertex, TestEdge >> paths)
Set< TestVertex > vertexes ()
Set< TestEdge > edges ()
Additional Inherited Members
Protected Attributes inherited from org.onlab.graph.GraphTest
Graph< TestVertex, TestEdge > graph
EdgeWeight< TestVertex, TestEdge > weight
Detailed Description
Test of the Dijkstra algorithm.
Definition at line 30 of file DijkstraGraphSearchTest.java.
Member Function Documentation
void org.onlab.graph.DijkstraGraphSearchTest.defaultGraphTest ()
Definition at line 39 of file DijkstraGraphSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeDefaultTest().
void org.onlab.graph.DijkstraGraphSearchTest.defaultHopCountWeight ()
Definition at line 45 of file DijkstraGraphSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeDefaultTest(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.DijkstraGraphSearchTest.denseMultiplePath ()
Definition at line 85 of file DijkstraGraphSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeSearch(), org.onlab.graph.BreadthFirstSearchTest.executeSinglePathSearch(), org.onlab.graph.GraphTest.graph, org.onlab.graph.DijkstraGraphSearchTest.graphSearch(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.DijkstraGraphSearchTest.disconnected ()
Definition at line 148 of file DijkstraGraphSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeSearch(), org.onlab.graph.GraphTest.graph, org.onlab.graph.DijkstraGraphSearchTest.graphSearch(), and org.onlab.graph.GraphTest.vertexes().
Referenced by org.onlab.graph.DijkstraGraphSearchTest.disconnectedPerf().
void org.onlab.graph.DijkstraGraphSearchTest.disconnectedPerf ()
Definition at line 133 of file DijkstraGraphSearchTest.java.
References org.onlab.graph.DijkstraGraphSearchTest.disconnected().
void org.onlab.graph.DijkstraGraphSearchTest.dualEdgeMultiplePath ()
Definition at line 101 of file DijkstraGraphSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeSearch(), org.onlab.graph.BreadthFirstSearchTest.executeSinglePathSearch(), org.onlab.graph.GraphTest.graph, org.onlab.graph.DijkstraGraphSearchTest.graphSearch(), and org.onlab.graph.GraphTest.weight.
AbstractGraphPathSearch<TestVertex, TestEdge> org.onlab.graph.DijkstraGraphSearchTest.graphSearch () protected virtual
Creates a test-specific graph search to exercise.
Returns
graph search
Reimplemented from org.onlab.graph.BreadthFirstSearchTest.
Definition at line 33 of file DijkstraGraphSearchTest.java.
Referenced by org.onlab.graph.DijkstraGraphSearchTest.denseMultiplePath(), org.onlab.graph.DijkstraGraphSearchTest.disconnected(), org.onlab.graph.DijkstraGraphSearchTest.dualEdgeMultiplePath(), org.onlab.graph.DijkstraGraphSearchTest.negativeWeights(), org.onlab.graph.DijkstraGraphSearchTest.noPath(), and org.onlab.graph.DijkstraGraphSearchTest.simpleMultiplePath().
void org.onlab.graph.DijkstraGraphSearchTest.negativeWeights ()
Definition at line 115 of file DijkstraGraphSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeSearch(), org.onlab.graph.BreadthFirstSearchTest.executeSinglePathSearch(), org.onlab.graph.GraphTest.graph, org.onlab.graph.DijkstraGraphSearchTest.graphSearch(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.DijkstraGraphSearchTest.noPath ()
Definition at line 51 of file DijkstraGraphSearchTest.java.
References org.onlab.graph.GraphTest.graph, org.onlab.graph.DijkstraGraphSearchTest.graphSearch(), org.onlab.graph.GraphTest.printPaths(), and org.onlab.graph.GraphTest.weight.
void org.onlab.graph.DijkstraGraphSearchTest.simpleMultiplePath ()
Definition at line 74 of file DijkstraGraphSearchTest.java.
References org.onlab.graph.BreadthFirstSearchTest.executeSearch(), org.onlab.graph.BreadthFirstSearchTest.executeSinglePathSearch(), org.onlab.graph.GraphTest.graph, org.onlab.graph.DijkstraGraphSearchTest.graphSearch(), and org.onlab.graph.GraphTest.weight.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/graph/DijkstraGraphSearchTest.java