onos: org.onosproject.pcepio.types.IPv6InterfaceAddressTlv Class Reference
org.onosproject.pcepio.types.IPv6InterfaceAddressTlv Class Reference
Provides IPv6 Interface Address.
Public Member Functions
IPv6InterfaceAddressTlv (byte[] rawValue)
Constructor to initialize rawValue.
byte[] getBytes ()
Returns value of IPv6 Interface Address.
byte[] getValue ()
Returns value of IPv6 Interface Address.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static IPv6InterfaceAddressTlv of (final byte[] raw)
Returns newly created IPv6InterfaceAddressTlv object.
static IPv6InterfaceAddressTlv read20Bytes (ChannelBuffer c)
Reads the channel buffer and returns object of IPv6InterfaceAddressTlv.
Static Public Attributes
static final short TYPE = 12
static final short LENGTH = 20
static final byte VALUE_LENGTH = 18
static final
IPv6InterfaceAddressTlv NONE = new IPv6InterfaceAddressTlv(NONE_VAL)
static final
IPv6InterfaceAddressTlv NO_MASK = new IPv6InterfaceAddressTlv(NO_MASK_VAL)
static final
IPv6InterfaceAddressTlv FULL_MASK = NONE
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IPv6InterfaceAddressTlv.class)
Detailed Description
Provides IPv6 Interface Address.
REFERENCE :[RFC6119]/4.2.
Definition at line 31 of file IPv6InterfaceAddressTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.IPv6InterfaceAddressTlv (byte[] rawValue)
Constructor to initialize rawValue.
Parameters
rawValue IPv6 Interface Address Tlv
Definition at line 55 of file IPv6InterfaceAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.equals(), and org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.equals (Object obj)
Definition at line 134 of file IPv6InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.IPv6InterfaceAddressTlv().
byte [] org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.getBytes ()
Returns value of IPv6 Interface Address.
Returns
rawValue raw value
Definition at line 100 of file IPv6InterfaceAddressTlv.java.
short org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 124 of file IPv6InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.LENGTH.
short org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 119 of file IPv6InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.TYPE.
byte [] org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.getValue ()
Returns value of IPv6 Interface Address.
Returns
rawValue raw value
Definition at line 109 of file IPv6InterfaceAddressTlv.java.
PcepVersion org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 114 of file IPv6InterfaceAddressTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.hashCode ()
Definition at line 129 of file IPv6InterfaceAddressTlv.java.
static IPv6InterfaceAddressTlv org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.of (final byte[] raw) static
Returns newly created IPv6InterfaceAddressTlv object.
Parameters
raw IPv6 Interface Address
Returns
object of IPv6InterfaceAddressTlv
Definition at line 66 of file IPv6InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.IPv6InterfaceAddressTlv(), org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.NO_MASK, and org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.NONE.
static IPv6InterfaceAddressTlv org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.read20Bytes (ChannelBuffer c) static
Reads the channel buffer and returns object of IPv6InterfaceAddressTlv.
Parameters
c input channel buffer
Returns
object of IPv6InterfaceAddressTlv
Definition at line 160 of file IPv6InterfaceAddressTlv.java.
String org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.toString ()
Definition at line 167 of file IPv6InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.LENGTH, and org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.TYPE.
int org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 146 of file IPv6InterfaceAddressTlv.java.
References org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.LENGTH, and org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.TYPE.
Member Data Documentation
final IPv6InterfaceAddressTlv org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.FULL_MASK = NONE static
Definition at line 46 of file IPv6InterfaceAddressTlv.java.
final short org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.LENGTH = 20 static
Definition at line 36 of file IPv6InterfaceAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.getLength(), org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.toString(), and org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.write().
final Logger org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.log = LoggerFactory.getLogger(IPv6InterfaceAddressTlv.class) static protected
Definition at line 33 of file IPv6InterfaceAddressTlv.java.
final IPv6InterfaceAddressTlv org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.NO_MASK = new IPv6InterfaceAddressTlv(NO_MASK_VAL) static
Definition at line 45 of file IPv6InterfaceAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.of().
final IPv6InterfaceAddressTlv org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.NONE = new IPv6InterfaceAddressTlv(NONE_VAL) static
Definition at line 40 of file IPv6InterfaceAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.of().
final short org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.TYPE = 12 static
Definition at line 35 of file IPv6InterfaceAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.getType(), org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.toString(), and org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.write().
final byte org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.VALUE_LENGTH = 18 static
Definition at line 37 of file IPv6InterfaceAddressTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkDescriptorsTlv.read().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IPv6InterfaceAddressTlv.java