onos: org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler Class Reference
org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler Class Reference
Public Member Functions
void activate ()
void deactivate ()
List< Intent > compile (SinglePointToMultiPointIntent intent, List< Intent > installable, Set< LinkResourceAllocations > resources)
Detailed Description
Definition at line 37 of file SinglePointToMultiPointIntentCompiler.java.
Member Function Documentation
void org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler.activate ()
Definition at line 45 of file SinglePointToMultiPointIntentCompiler.java.
List<Intent> org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler.compile (SinglePointToMultiPointIntent intent, List< Intent > installable, Set< LinkResourceAllocations > resources)
Definition at line 57 of file SinglePointToMultiPointIntentCompiler.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.ConnectivityIntent.constraints(), find-flow.deviceId, org.onosproject.net.ConnectPoint.deviceId(), org.onosproject.net.intent.Intent.key(), org.onosproject.net.intent.Intent.priority(), org.onosproject.net.intent.ConnectivityIntent.selector(), and org.onosproject.net.intent.ConnectivityIntent.treatment().
void org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler.deactivate ()
Definition at line 51 of file SinglePointToMultiPointIntentCompiler.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/intent/impl/compiler/SinglePointToMultiPointIntentCompiler.java