onos: org.onosproject.pcepio.types.RouterIDSubTlv Class Reference
org.onosproject.pcepio.types.RouterIDSubTlv Class Reference
Provides router id.
Public Member Functions
RouterIDSubTlv (byte[] rawValue, short hLength)
constructor to initialize rawValue.
byte[] getValue ()
Returns raw value.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static RouterIDSubTlv of (final byte[] raw, short hLength)
Returns object of Router ID Sub Tlv.
static PcepValueType read (ChannelBuffer c, short hLength)
Reads channel buffer and returns object of RouterIDSubTlv.
Static Public Attributes
static final short TYPE = 1000
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(RouterIDSubTlv.class)
Detailed Description
Provides router id.
Definition at line 31 of file RouterIDSubTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.RouterIDSubTlv.RouterIDSubTlv (byte[] rawValue, short hLength)
constructor to initialize rawValue.
Parameters
rawValue raw value
hLength length
Definition at line 56 of file RouterIDSubTlv.java.
Referenced by org.onosproject.pcepio.types.RouterIDSubTlv.equals(), org.onosproject.pcepio.types.RouterIDSubTlv.of(), and org.onosproject.pcepio.types.RouterIDSubTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.RouterIDSubTlv.equals (Object obj)
Definition at line 106 of file RouterIDSubTlv.java.
References org.onosproject.pcepio.types.RouterIDSubTlv.RouterIDSubTlv().
short org.onosproject.pcepio.types.RouterIDSubTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 96 of file RouterIDSubTlv.java.
short org.onosproject.pcepio.types.RouterIDSubTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 91 of file RouterIDSubTlv.java.
References org.onosproject.pcepio.types.RouterIDSubTlv.TYPE.
byte [] org.onosproject.pcepio.types.RouterIDSubTlv.getValue ()
Returns raw value.
Returns
rawValue value
Definition at line 81 of file RouterIDSubTlv.java.
PcepVersion org.onosproject.pcepio.types.RouterIDSubTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 86 of file RouterIDSubTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.RouterIDSubTlv.hashCode ()
Definition at line 101 of file RouterIDSubTlv.java.
static RouterIDSubTlv org.onosproject.pcepio.types.RouterIDSubTlv.of (final byte[] raw, short hLength) static
Returns object of Router ID Sub Tlv.
Parameters
raw value
hLength length
Returns
object of Router ID Sub Tlv
Definition at line 72 of file RouterIDSubTlv.java.
References org.onosproject.pcepio.types.RouterIDSubTlv.RouterIDSubTlv().
static PcepValueType org.onosproject.pcepio.types.RouterIDSubTlv.read (ChannelBuffer c, short hLength) static
Reads channel buffer and returns object of RouterIDSubTlv.
Parameters
c input channel buffer
hLength length
Returns
object of RouterIDSubTlv
Definition at line 133 of file RouterIDSubTlv.java.
References org.onosproject.pcepio.types.RouterIDSubTlv.RouterIDSubTlv().
String org.onosproject.pcepio.types.RouterIDSubTlv.toString ()
Definition at line 140 of file RouterIDSubTlv.java.
References org.onosproject.pcepio.types.RouterIDSubTlv.TYPE.
int org.onosproject.pcepio.types.RouterIDSubTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 118 of file RouterIDSubTlv.java.
References org.onosproject.pcepio.types.RouterIDSubTlv.TYPE.
Member Data Documentation
final Logger org.onosproject.pcepio.types.RouterIDSubTlv.log = LoggerFactory.getLogger(RouterIDSubTlv.class) static protected
Definition at line 43 of file RouterIDSubTlv.java.
final short org.onosproject.pcepio.types.RouterIDSubTlv.TYPE = 1000 static
Definition at line 45 of file RouterIDSubTlv.java.
Referenced by org.onosproject.pcepio.types.RouterIDSubTlv.getType(), org.onosproject.pcepio.types.RouterIDSubTlv.toString(), and org.onosproject.pcepio.types.RouterIDSubTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/RouterIDSubTlv.java