onos: org.onosproject.vtnrsc.portchain.impl.PortChainManager Class Reference
org.onosproject.vtnrsc.portchain.impl.PortChainManager Class Reference
Provides implementation of the portChainService.
Public Member Functions
void activate ()
void deactivate ()
boolean exists (PortChainId portChainId)
Returns if the port chain is existed.
int getPortChainCount ()
Returns the number of port chains known to the system.
Iterable< PortChain > getPortChains ()
Returns an iterable collection of the currently known port chains.
PortChain getPortChain (PortChainId portChainId)
Returns the portChain with the given identifier.
boolean createPortChain (PortChain portChain)
Creates a PortChain in the store.
boolean updatePortChain (PortChain portChain)
Updates the portChain in the store.
boolean removePortChain (PortChainId portChainId)
Deletes portChain by given portChainId.
Protected Attributes
StorageService storageService
Detailed Description
Provides implementation of the portChainService.
Definition at line 45 of file PortChainManager.java.
Member Function Documentation
void org.onosproject.vtnrsc.portchain.impl.PortChainManager.activate ()
Definition at line 58 of file PortChainManager.java.
References org.onosproject.store.serializers.KryoNamespaces.API.
boolean org.onosproject.vtnrsc.portchain.impl.PortChainManager.createPortChain (PortChain portChain)
Creates a PortChain in the store.
Parameters
portChain the port chain to create
Returns
true if given port chain is created successfully.
Implements org.onosproject.vtnrsc.portchain.PortChainService.
Definition at line 102 of file PortChainManager.java.
References org.onosproject.vtnrsc.PortChain.portChainId().
Referenced by org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testCreatePortChain().
void org.onosproject.vtnrsc.portchain.impl.PortChainManager.deactivate ()
Definition at line 74 of file PortChainManager.java.
boolean org.onosproject.vtnrsc.portchain.impl.PortChainManager.exists (PortChainId portChainId)
Returns if the port chain is existed.
Parameters
portChainId port chain identifier
Returns
true or false if one with the given identifier exists.
Implements org.onosproject.vtnrsc.portchain.PortChainService.
Definition at line 80 of file PortChainManager.java.
Referenced by org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testExists().
PortChain org.onosproject.vtnrsc.portchain.impl.PortChainManager.getPortChain (PortChainId portChainId)
Returns the portChain with the given identifier.
Parameters
portChainId port chain identifier
Returns
PortChain or null if port chain with the given identifier is not known.
Implements org.onosproject.vtnrsc.portchain.PortChainService.
Definition at line 96 of file PortChainManager.java.
Referenced by org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testGetPortChain().
int org.onosproject.vtnrsc.portchain.impl.PortChainManager.getPortChainCount ()
Returns the number of port chains known to the system.
Returns
number of port chains.
Implements org.onosproject.vtnrsc.portchain.PortChainService.
Definition at line 86 of file PortChainManager.java.
Referenced by org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testGetPortChainCount().
Iterable<PortChain> org.onosproject.vtnrsc.portchain.impl.PortChainManager.getPortChains ()
Returns an iterable collection of the currently known port chains.
Returns
collection of port chains.
Implements org.onosproject.vtnrsc.portchain.PortChainService.
Definition at line 91 of file PortChainManager.java.
boolean org.onosproject.vtnrsc.portchain.impl.PortChainManager.removePortChain (PortChainId portChainId)
Deletes portChain by given portChainId.
Parameters
portChainId id of port chain to remove
Returns
true if the give port chain is deleted successfully.
Implements org.onosproject.vtnrsc.portchain.PortChainService.
Definition at line 135 of file PortChainManager.java.
Referenced by org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testRemovePortChain().
boolean org.onosproject.vtnrsc.portchain.impl.PortChainManager.updatePortChain (PortChain portChain)
Updates the portChain in the store.
Parameters
portChain the port chain to update
Returns
true if given port chain is updated successfully.
Implements org.onosproject.vtnrsc.portchain.PortChainService.
Definition at line 115 of file PortChainManager.java.
References org.onosproject.vtnrsc.PortChain.portChainId().
Referenced by org.onosproject.vtnrsc.portchain.impl.PortChainManagerTest.testUpdatePortChain().
Member Data Documentation
StorageService org.onosproject.vtnrsc.portchain.impl.PortChainManager.storageService protected
Definition at line 55 of file PortChainManager.java.
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/portchain/impl/PortChainManager.java