onos: org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore Class Reference
org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore Class Reference
Implementation of the MastershipStore on top of Leadership Service.
Public Member Functions
void activate ()
void deactivate ()
CompletableFuture< MastershipRole > requestRole (DeviceId deviceId)
Requests role of the local node for the specified device.
MastershipRole getRole (NodeId nodeId, DeviceId deviceId)
Returns the role of a device for a specific controller instance.
NodeId getMaster (DeviceId deviceId)
Returns the master for a device.
RoleInfo getNodes (DeviceId deviceId)
Returns the master and backup nodes for a device.
Set< DeviceId > getDevices (NodeId nodeId)
Returns the devices that a controller instance is master of.
CompletableFuture
< MastershipEvent > setMaster (NodeId nodeId, DeviceId deviceId)
Sets a device's role for a specified controller instance.
MastershipTerm getTermFor (DeviceId deviceId)
Returns the current master and number of past mastership hand-offs (terms) for a device.
CompletableFuture
< MastershipEvent > setStandby (NodeId nodeId, DeviceId deviceId)
Sets a controller instance's mastership role to STANDBY for a device.
CompletableFuture
< MastershipEvent > relinquishRole (NodeId nodeId, DeviceId deviceId)
Allows a controller instance to give up its current role for a device.
void relinquishAllRole (NodeId nodeId)
Removes all the roles for the specified controller instance.
Static Public Attributes
static final StoreSerializer SERIALIZER
Protected Attributes
LeadershipService leadershipService
ClusterService clusterService
ClusterCommunicationService clusterCommunicator
Detailed Description
Implementation of the MastershipStore on top of Leadership Service.
Definition at line 75 of file ConsistentDeviceMastershipStore.java.
Member Function Documentation
void org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.activate ()
Definition at line 123 of file ConsistentDeviceMastershipStore.java.
void org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.deactivate ()
Definition at line 147 of file ConsistentDeviceMastershipStore.java.
Set<DeviceId> org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getDevices (NodeId nodeId)
Returns the devices that a controller instance is master of.
Parameters
nodeId the instance identifier
Returns
a set of device identifiers
Implements org.onosproject.mastership.MastershipStore.
Definition at line 228 of file ConsistentDeviceMastershipStore.java.
NodeId org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getMaster (DeviceId deviceId)
Returns the master for a device.
Parameters
deviceId the device identifier
Returns
the instance identifier of the master
Implements org.onosproject.mastership.MastershipStore.
Definition at line 193 of file ConsistentDeviceMastershipStore.java.
Referenced by org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setMaster(), and org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setStandby().
RoleInfo org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getNodes (DeviceId deviceId)
Returns the master and backup nodes for a device.
Parameters
deviceId the device identifier
Returns
a RoleInfo containing controller IDs
Implements org.onosproject.mastership.MastershipStore.
Definition at line 201 of file ConsistentDeviceMastershipStore.java.
References find-flow.deviceId, org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getRole(), org.onosproject.net.MastershipRole.MASTER, create-flow.node, and org.onosproject.net.MastershipRole.STANDBY.
MastershipRole org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getRole (NodeId nodeId, DeviceId deviceId)
Returns the role of a device for a specific controller instance.
Parameters
nodeId the instance identifier
deviceId the device identifiers
Returns
the role
Implements org.onosproject.mastership.MastershipStore.
Definition at line 179 of file ConsistentDeviceMastershipStore.java.
References org.onosproject.net.MastershipRole.MASTER, and org.onosproject.net.MastershipRole.NONE.
Referenced by org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getNodes().
MastershipTerm org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getTermFor (DeviceId deviceId)
Returns the current master and number of past mastership hand-offs (terms) for a device.
Parameters
deviceId the device identifier
Returns
the current master's ID and the term value for device, or null
Implements org.onosproject.mastership.MastershipStore.
Definition at line 273 of file ConsistentDeviceMastershipStore.java.
void org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.relinquishAllRole (NodeId nodeId)
Removes all the roles for the specified controller instance.
If the role was MASTER, another controller instance will be selected as a candidate master.
Parameters
nodeId the controller instance identifier
Implements org.onosproject.mastership.MastershipStore.
Definition at line 370 of file ConsistentDeviceMastershipStore.java.
CompletableFuture<MastershipEvent> org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.relinquishRole (NodeId nodeId, DeviceId deviceId)
Allows a controller instance to give up its current role for a device.
If the role is MASTER, another controller instance will be selected as a candidate master.
Parameters
nodeId the controller instance identifier
deviceId device to revoke mastership role for
Returns
a mastership event
Implements org.onosproject.mastership.MastershipStore.
Definition at line 308 of file ConsistentDeviceMastershipStore.java.
References find-flow.deviceId, and org.onosproject.cluster.NodeId.equals().
Referenced by org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setStandby().
CompletableFuture<MastershipRole> org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.requestRole (DeviceId deviceId)
Requests role of the local node for the specified device.
Parameters
deviceId device identifier
Returns
established or newly negotiated mastership role
Implements org.onosproject.mastership.MastershipStore.
Definition at line 158 of file ConsistentDeviceMastershipStore.java.
References org.onosproject.net.MastershipRole.MASTER, and org.onosproject.net.MastershipRole.STANDBY.
CompletableFuture<MastershipEvent> org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setMaster (NodeId nodeId, DeviceId deviceId)
Sets a device's role for a specified controller instance.
Parameters
nodeId controller instance identifier
deviceId device identifier
Returns
a mastership event
Implements org.onosproject.mastership.MastershipStore.
Definition at line 240 of file ConsistentDeviceMastershipStore.java.
References find-flow.deviceId, org.onosproject.cluster.NodeId.equals(), org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getMaster(), org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.leadershipService, and org.onosproject.cluster.LeadershipService.makeTopCandidate().
Referenced by org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setStandby().
CompletableFuture<MastershipEvent> org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setStandby (NodeId nodeId, DeviceId deviceId)
Sets a controller instance's mastership role to STANDBY for a device.
If the role is MASTER, another controller instance will be selected as a candidate master.
Parameters
nodeId the controller instance identifier
deviceId device to revoke mastership role for
Returns
a mastership event
Implements org.onosproject.mastership.MastershipStore.
Definition at line 282 of file ConsistentDeviceMastershipStore.java.
References find-flow.deviceId, org.onosproject.cluster.NodeId.equals(), org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.getMaster(), org.onosproject.net.MastershipRole.NONE, org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.relinquishRole(), and org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setMaster().
Member Data Documentation
ClusterCommunicationService org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.clusterCommunicator protected
Definition at line 88 of file ConsistentDeviceMastershipStore.java.
ClusterService org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.clusterService protected
Definition at line 85 of file ConsistentDeviceMastershipStore.java.
LeadershipService org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.leadershipService protected
Definition at line 82 of file ConsistentDeviceMastershipStore.java.
Referenced by org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setMaster().
final StoreSerializer org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.SERIALIZER static
Initial value:
= new KryoSerializer() {
        @Override
        protected void setupKryoPool() {
            serializerPool = KryoNamespace.newBuilder()
                    .register(KryoNamespaces.API)
                    .register(MastershipRole.class)
                    .register(MastershipEvent.class)
                    .register(MastershipEvent.Type.class)
                    .build();
        }
    }
Definition at line 110 of file ConsistentDeviceMastershipStore.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/mastership/impl/ConsistentDeviceMastershipStore.java