onos: org.onosproject.common.DefaultTopology Class Reference
org.onosproject.common.DefaultTopology Class Reference
Default implementation of the topology descriptor.
Classes
class ClusterIndexes
Public Member Functions
DefaultTopology (ProviderId providerId, GraphDescription description, Function< ConnectPoint, Boolean > broadcastFunction)
Creates a topology descriptor attributed to the specified provider.
DefaultTopology (ProviderId providerId, GraphDescription description)
Creates a topology descriptor attributed to the specified provider.
long time ()
Returns the time, specified in system nanos of when the topology became available.
long creationTime ()
Returns the time, specified in system millis of when the topology became available.
long computeCost ()
Returns the time, specified in system nanos of how long the topology took to compute.
int clusterCount ()
Returns the number of SCCs (strongly connected components) in the topology.
int deviceCount ()
Returns the number of infrastructure devices in the topology.
int linkCount ()
Returns the number of infrastructure links in the topology.
TopologyGraph getGraph ()
Returns the backing topology graph.
Set< TopologyCluster > getClusters ()
Returns the set of topology clusters.
TopologyCluster getCluster (ClusterId clusterId)
Returns the specified topology cluster.
TopologyCluster getCluster (DeviceId deviceId)
Returns the topology cluster that contains the given device.
Set< DeviceId > getClusterDevices (TopologyCluster cluster)
Returns the set of cluster devices.
Set< Link > getClusterLinks (TopologyCluster cluster)
Returns the set of cluster links.
boolean isInfrastructure (ConnectPoint connectPoint)
Indicates whether the given point is an infrastructure link end-point.
boolean isBroadcastPoint (ConnectPoint connectPoint)
Indicates whether the given point is part of a broadcast set.
int broadcastSetSize (ClusterId clusterId)
Returns the size of the cluster broadcast set.
Set< ConnectPoint > broadcastPoints (ClusterId clusterId)
Returns the set of the cluster broadcast points.
Set< Path > getPaths (DeviceId src, DeviceId dst)
Returns the set of pre-computed shortest paths between source and destination devices.
Set< Path > getPaths (DeviceId src, DeviceId dst, LinkWeight weight)
Computes on-demand the set of shortest paths between source and destination devices.
Set< DisjointPath > getDisjointPaths (DeviceId src, DeviceId dst)
/** Returns the set of pre-computed shortest disjoint path pairs between source and destination devices.
Set< DisjointPath > getDisjointPaths (DeviceId src, DeviceId dst, LinkWeight weight)
Computes on-demand the set of shortest disjoint path pairs between source and destination devices.
Set< DisjointPath > getDisjointPaths (DeviceId src, DeviceId dst, LinkWeight weight, Map< Link, Object > riskProfile)
Computes on-demand the set of shortest disjoint risk groups path pairs between source and destination devices.
Set< DisjointPath > getDisjointPaths (DeviceId src, DeviceId dst, Map< Link, Object > riskProfile)
Computes on-demand the set of shortest disjoint risk groups path pairs between source and destination devices.
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel ()
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel (ProviderId providerId, Annotations...annotations)
Creates a model entity attributed to the specified provider and optionally annotated.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of the topology descriptor.
This carries the backing topology data.
Definition at line 72 of file DefaultTopology.java.
Constructor & Destructor Documentation
org.onosproject.common.DefaultTopology.DefaultTopology (ProviderId providerId, GraphDescription description, Function< ConnectPoint, Boolean > broadcastFunction)
Creates a topology descriptor attributed to the specified provider.
Parameters
providerId identity of the provider
description data describing the new topology
broadcastFunction broadcast point function
Definition at line 100 of file DefaultTopology.java.
References org.onosproject.common.DefaultTopology.time(), and org.onosproject.net.topology.GraphDescription.vertexes().
org.onosproject.common.DefaultTopology.DefaultTopology (ProviderId providerId, GraphDescription description)
Creates a topology descriptor attributed to the specified provider.
Parameters
providerId identity of the provider
description data describing the new topology
Definition at line 128 of file DefaultTopology.java.
References org.onosproject.net.AbstractModel.providerId().
Member Function Documentation
Set<ConnectPoint> org.onosproject.common.DefaultTopology.broadcastPoints (ClusterId clusterId)
Returns the set of the cluster broadcast points.
Parameters
clusterId cluster identifier
Returns
set of cluster broadcast points
Definition at line 284 of file DefaultTopology.java.
int org.onosproject.common.DefaultTopology.broadcastSetSize (ClusterId clusterId)
Returns the size of the cluster broadcast set.
Parameters
clusterId cluster identifier
Returns
size of the cluster broadcast set
Definition at line 274 of file DefaultTopology.java.
int org.onosproject.common.DefaultTopology.clusterCount ()
Returns the number of SCCs (strongly connected components) in the topology.
Returns
number of clusters
Implements org.onosproject.net.topology.Topology.
Definition at line 148 of file DefaultTopology.java.
References onos.size.
long org.onosproject.common.DefaultTopology.computeCost ()
Returns the time, specified in system nanos of how long the topology took to compute.
Returns
elapsed time in system nanos
Implements org.onosproject.net.topology.Topology.
Definition at line 143 of file DefaultTopology.java.
long org.onosproject.common.DefaultTopology.creationTime ()
Returns the time, specified in system millis of when the topology became available.
Returns
time in system nanos
Implements org.onosproject.net.topology.Topology.
Definition at line 138 of file DefaultTopology.java.
int org.onosproject.common.DefaultTopology.deviceCount ()
Returns the number of infrastructure devices in the topology.
Returns
number of devices
Implements org.onosproject.net.topology.Topology.
Definition at line 153 of file DefaultTopology.java.
References onos.size.
TopologyCluster org.onosproject.common.DefaultTopology.getCluster (ClusterId clusterId)
Returns the specified topology cluster.
Parameters
clusterId cluster identifier
Returns
topology cluster
Definition at line 198 of file DefaultTopology.java.
TopologyCluster org.onosproject.common.DefaultTopology.getCluster (DeviceId deviceId)
Returns the topology cluster that contains the given device.
Parameters
deviceId device identifier
Returns
topology cluster
Definition at line 208 of file DefaultTopology.java.
References find-flow.deviceId.
Set<DeviceId> org.onosproject.common.DefaultTopology.getClusterDevices (TopologyCluster cluster)
Returns the set of cluster devices.
Parameters
cluster topology cluster
Returns
cluster devices
Definition at line 218 of file DefaultTopology.java.
References find-link-in-cluster.cluster.
Set<Link> org.onosproject.common.DefaultTopology.getClusterLinks (TopologyCluster cluster)
Returns the set of cluster links.
Parameters
cluster topology cluster
Returns
cluster links
Definition at line 228 of file DefaultTopology.java.
References find-link-in-cluster.cluster.
Set<TopologyCluster> org.onosproject.common.DefaultTopology.getClusters ()
Returns the set of topology clusters.
Returns
set of clusters
Definition at line 188 of file DefaultTopology.java.
Set<DisjointPath> org.onosproject.common.DefaultTopology.getDisjointPaths (DeviceId src, DeviceId dst)
/** Returns the set of pre-computed shortest disjoint path pairs between source and destination devices.
Parameters
src source device
dst destination device
Returns
set of shortest disjoint path pairs
Definition at line 336 of file DefaultTopology.java.
Set<DisjointPath> org.onosproject.common.DefaultTopology.getDisjointPaths (DeviceId src, DeviceId dst, LinkWeight weight)
Computes on-demand the set of shortest disjoint path pairs between source and destination devices.
Parameters
src source device
dst destination device
weight link weight function
Returns
set of disjoint shortest path pairs
Definition at line 349 of file DefaultTopology.java.
Set<DisjointPath> org.onosproject.common.DefaultTopology.getDisjointPaths (DeviceId src, DeviceId dst, LinkWeight weight, Map< Link, Object > riskProfile)
Computes on-demand the set of shortest disjoint risk groups path pairs between source and destination devices.
Parameters
src source device
dst destination device
weight edge weight object
riskProfile map representing risk groups for each link
Returns
set of shortest disjoint paths
Definition at line 408 of file DefaultTopology.java.
Set<DisjointPath> org.onosproject.common.DefaultTopology.getDisjointPaths (DeviceId src, DeviceId dst, Map< Link, Object > riskProfile)
Computes on-demand the set of shortest disjoint risk groups path pairs between source and destination devices.
Parameters
src source device
dst destination device
riskProfile map representing risk groups for each link
Returns
set of shortest disjoint paths
Definition at line 440 of file DefaultTopology.java.
TopologyGraph org.onosproject.common.DefaultTopology.getGraph ()
Returns the backing topology graph.
Returns
topology graph
Definition at line 179 of file DefaultTopology.java.
Set<Path> org.onosproject.common.DefaultTopology.getPaths (DeviceId src, DeviceId dst)
Returns the set of pre-computed shortest paths between source and destination devices.
Parameters
src source device
dst destination device
Returns
set of shortest paths
Definition at line 296 of file DefaultTopology.java.
Set<Path> org.onosproject.common.DefaultTopology.getPaths (DeviceId src, DeviceId dst, LinkWeight weight)
Computes on-demand the set of shortest paths between source and destination devices.
Parameters
src source device
dst destination device
weight link weight function
Returns
set of shortest paths
Definition at line 309 of file DefaultTopology.java.
boolean org.onosproject.common.DefaultTopology.isBroadcastPoint (ConnectPoint connectPoint)
Indicates whether the given point is part of a broadcast set.
Parameters
connectPoint connection point
Returns
true if in broadcast set
Definition at line 248 of file DefaultTopology.java.
References find-link-in-cluster.cluster, org.onosproject.net.ConnectPoint.deviceId(), org.onosproject.net.topology.TopologyCluster.id(), and org.onosproject.common.DefaultTopology.isInfrastructure().
boolean org.onosproject.common.DefaultTopology.isInfrastructure (ConnectPoint connectPoint)
Indicates whether the given point is an infrastructure link end-point.
Parameters
connectPoint connection point
Returns
true if infrastructure
Definition at line 238 of file DefaultTopology.java.
Referenced by org.onosproject.common.DefaultTopology.isBroadcastPoint(), and org.onosproject.common.DefaultTopologyTest.pointRelated().
int org.onosproject.common.DefaultTopology.linkCount ()
Returns the number of infrastructure links in the topology.
Returns
number of links
Implements org.onosproject.net.topology.Topology.
Definition at line 158 of file DefaultTopology.java.
References onos.size.
long org.onosproject.common.DefaultTopology.time ()
Returns the time, specified in system nanos of when the topology became available.
Returns
time in system nanos
Implements org.onosproject.net.topology.Topology.
Definition at line 133 of file DefaultTopology.java.
Referenced by org.onosproject.common.DefaultTopology.DefaultTopology().
String org.onosproject.common.DefaultTopology.toString ()
Definition at line 623 of file DefaultTopology.java.
The documentation for this class was generated from the following file:
core/common/src/main/java/org/onosproject/common/DefaultTopology.java