onos: org.onosproject.virtualbng.VbngConfigurationManager Class Reference
org.onosproject.virtualbng.VbngConfigurationManager Class Reference
Implementation of ConfigurationService which reads virtual BNG configuration from a file.
Public Member Functions
void activate ()
void deactivate ()
void readConfiguration ()
Instructs the configuration reader to read the configuration from the file.
IpAddress getNextHopIpAddress ()
Gets the IP address configured for the next hop.
MacAddress getPublicFacingMac ()
Gets the MAC address configured for all the public IP addresses.
IpAddress getXosIpAddress ()
Gets the IP address configured for XOS server.
int getXosRestPort ()
Gets the REST communication port configured for XOS server.
Map< String, ConnectPoint > getNodeToPort ()
Gets the host to port map.
synchronized IpAddress getAvailablePublicIpAddress (IpAddress privateIpAddress)
Gets an available public IP address from local public IP prefixes.
IpAddress getAssignedPublicIpAddress (IpAddress privateIpAddress)
Gets the public IP address already assigned for a private IP address.
boolean isAssignedPublicIpAddress (IpAddress ipAddress)
Evaluates whether an IP address is an assigned public IP address.
synchronized IpAddress recycleAssignedPublicIpAddress (IpAddress privateIpAddress)
Recycles the public IP address assigned for a private IP address, and at the same time deletes the mapping entry from this private IP address to the public IP address.
Map< IpAddress, IpAddress > getIpAddressMappings ()
Gets all the mapping entries from private IP address to public IP address.
synchronized boolean assignSpecifiedPublicIp (IpAddress publicIpAddress, IpAddress privateIpAddress)
Tries to assign a given public IP address to a private IP address.
Detailed Description
Implementation of ConfigurationService which reads virtual BNG configuration from a file.
Definition at line 45 of file VbngConfigurationManager.java.
Member Function Documentation
void org.onosproject.virtualbng.VbngConfigurationManager.activate ()
Definition at line 69 of file VbngConfigurationManager.java.
References org.onosproject.virtualbng.VbngConfigurationManager.readConfiguration().
synchronized boolean org.onosproject.virtualbng.VbngConfigurationManager.assignSpecifiedPublicIp (IpAddress publicIpAddress, IpAddress privateIpAddress)
Tries to assign a given public IP address to a private IP address.
If success, then sets up the mapping from this private IP address to the public IP address, and stores the mapping.
Parameters
publicIpAddress the public IP address try to assign
privateIpAddress a private IP address
Returns
true if this public IP address is available, otherwise false
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 236 of file VbngConfigurationManager.java.
References org.onosproject.virtualbng.VbngConfigurationManager.isAssignedPublicIpAddress(), org.onlab.packet.IpPrefix.MAX_INET_MASK_LENGTH, and onosUploadBits.prefix.
void org.onosproject.virtualbng.VbngConfigurationManager.deactivate ()
Definition at line 75 of file VbngConfigurationManager.java.
IpAddress org.onosproject.virtualbng.VbngConfigurationManager.getAssignedPublicIpAddress (IpAddress privateIpAddress)
Gets the public IP address already assigned for a private IP address.
Parameters
privateIpAddress a private IP address
Returns
the assigned public IP address if it exists, otherwise null
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 199 of file VbngConfigurationManager.java.
synchronized IpAddress org.onosproject.virtualbng.VbngConfigurationManager.getAvailablePublicIpAddress (IpAddress privateIpAddress)
Gets an available public IP address from local public IP prefixes.
Parameters
privateIpAddress a private IP address
Returns
an available public IP address if it exists, otherwise null
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 146 of file VbngConfigurationManager.java.
References org.onlab.packet.IpPrefix.MAX_INET_MASK_LENGTH, and onosUploadBits.prefix.
Map<IpAddress, IpAddress> org.onosproject.virtualbng.VbngConfigurationManager.getIpAddressMappings ()
Gets all the mapping entries from private IP address to public IP address.
Returns
the address map from private IP address to public IP address
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 231 of file VbngConfigurationManager.java.
IpAddress org.onosproject.virtualbng.VbngConfigurationManager.getNextHopIpAddress ()
Gets the IP address configured for the next hop.
Returns
the IP address of next hop
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 119 of file VbngConfigurationManager.java.
Map<String, ConnectPoint> org.onosproject.virtualbng.VbngConfigurationManager.getNodeToPort ()
Gets the host to port map.
Returns
host to port map
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 139 of file VbngConfigurationManager.java.
MacAddress org.onosproject.virtualbng.VbngConfigurationManager.getPublicFacingMac ()
Gets the MAC address configured for all the public IP addresses.
Returns
the MAC address
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 124 of file VbngConfigurationManager.java.
IpAddress org.onosproject.virtualbng.VbngConfigurationManager.getXosIpAddress ()
Gets the IP address configured for XOS server.
Returns
the IP address configured for the XOS server
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 129 of file VbngConfigurationManager.java.
int org.onosproject.virtualbng.VbngConfigurationManager.getXosRestPort ()
Gets the REST communication port configured for XOS server.
Returns
the REST communication port configured for XOS server
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 134 of file VbngConfigurationManager.java.
boolean org.onosproject.virtualbng.VbngConfigurationManager.isAssignedPublicIpAddress (IpAddress ipAddress)
Evaluates whether an IP address is an assigned public IP address.
Parameters
ipAddress the IP address to evaluate
Returns
true if the input IP address is an assigned public IP address, otherwise false
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 204 of file VbngConfigurationManager.java.
Referenced by org.onosproject.virtualbng.VbngConfigurationManager.assignSpecifiedPublicIp().
void org.onosproject.virtualbng.VbngConfigurationManager.readConfiguration ()
Instructs the configuration reader to read the configuration from the file.
Definition at line 83 of file VbngConfigurationManager.java.
Referenced by org.onosproject.virtualbng.VbngConfigurationManager.activate().
synchronized IpAddress org.onosproject.virtualbng.VbngConfigurationManager.recycleAssignedPublicIpAddress (IpAddress privateIpAddress)
Recycles the public IP address assigned for a private IP address, and at the same time deletes the mapping entry from this private IP address to the public IP address.
Parameters
privateIpAddress a private IP address
Returns
the assigned public IP address if it exists, otherwise null
Implements org.onosproject.virtualbng.VbngConfigurationService.
Definition at line 209 of file VbngConfigurationManager.java.
The documentation for this class was generated from the following file:
apps/virtualbng/src/main/java/org/onosproject/virtualbng/VbngConfigurationManager.java