onos: org.onosproject.net.driver.AbstractBehaviour Class Reference
org.onosproject.net.driver.AbstractBehaviour Class Reference
Base implementation of device driver behaviour.
Public Member Functions
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Detailed Description
Base implementation of device driver behaviour.
Definition at line 23 of file AbstractBehaviour.java.
Member Function Documentation
DriverData org.onosproject.net.driver.AbstractBehaviour.data ()
Returns the driver data context.
Returns
driver data
Implements org.onosproject.net.driver.Behaviour.
Definition at line 28 of file AbstractBehaviour.java.
Referenced by org.onosproject.driver.ovsdb.OvsdbControllerConfig.setControllers(), and org.onosproject.net.driver.AbstractBehaviour.setData().
void org.onosproject.net.driver.AbstractBehaviour.setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Parameters
data driver data
Implements org.onosproject.net.driver.Behaviour.
Definition at line 33 of file AbstractBehaviour.java.
References org.onosproject.net.driver.AbstractBehaviour.data().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/driver/AbstractBehaviour.java