onos: org.onosproject.driver.pipeline.SpringOpenTTP Class Reference
org.onosproject.driver.pipeline.SpringOpenTTP Class Reference
Driver for SPRING-OPEN pipeline.
Public Member Functions
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filteringObjective)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Protected Member Functions
Collection< FlowRule > processSpecific (ForwardingObjective fwd)
Collection< FlowRule > processEthTypeSpecificObjective (ForwardingObjective fwd)
Collection< FlowRule > processEthDstSpecificObjective (ForwardingObjective fwd)
List< FlowRule > processEthDstFilter (EthCriterion ethCriterion, VlanIdCriterion vlanIdCriterion, FilteringObjective filt, VlanId assignedVlan, ApplicationId applicationId)
List< FlowRule > processVlanIdFilter (VlanIdCriterion vlanIdCriterion, FilteringObjective filt, VlanId assignedVlan, ApplicationId applicationId)
void setTableMissEntries ()
void populateTableMissEntry (int tableToAdd, boolean toControllerNow, boolean toControllerWrite, boolean toTable, int tableToSend)
void fail (Objective obj, ObjectiveError error)
Protected Attributes
int vlanTableId = TABLE_VLAN
Set the default values.
int tmacTableId = TABLE_TMAC
int ipv4UnicastTableId = TABLE_IPV4_UNICAST
int mplsTableId = TABLE_MPLS
int dstMacTableId = TABLE_DMAC
int aclTableId = TABLE_ACL
int srcMacTableId = TABLE_SMAC
final Logger log = getLogger(getClass())
GroupService groupService
FlowObjectiveStore flowObjectiveStore
DeviceId deviceId
KryoNamespace appKryo
Detailed Description
Driver for SPRING-OPEN pipeline.
Definition at line 93 of file SpringOpenTTP.java.
Member Function Documentation
void org.onosproject.driver.pipeline.SpringOpenTTP.fail (Objective obj, ObjectiveError error) protected
Definition at line 1005 of file SpringOpenTTP.java.
References org.onosproject.net.flowobjective.Objective.context().
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.filter(), org.onosproject.driver.pipeline.SpringOpenTTP.forward(), org.onosproject.driver.pipeline.SpringOpenTTP.init(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), and org.onosproject.driver.pipeline.SpringOpenTTP.processSpecific().
void org.onosproject.driver.pipeline.SpringOpenTTP.filter (FilteringObjective filterObjective)
Installs the filtering rules onto the device.
Parameters
filterObjective a filtering objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 175 of file SpringOpenTTP.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.fail(), org.onosproject.net.flowobjective.Objective.op(), org.onosproject.net.flowobjective.FilteringObjective.type(), and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.forward().
void org.onosproject.driver.pipeline.SpringOpenTTP.forward (ForwardingObjective forwardObjective)
Installs the forwarding rules onto the device.
Parameters
forwardObjective a forwarding objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 188 of file SpringOpenTTP.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.deviceId, org.onosproject.driver.pipeline.SpringOpenTTP.fail(), org.onosproject.driver.pipeline.SpringOpenTTP.filter(), org.onosproject.net.flowobjective.ObjectiveError.FLOWINSTALLATIONFAILED, org.onosproject.net.flowobjective.Objective.op(), and org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN.
void org.onosproject.driver.pipeline.SpringOpenTTP.init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
Parameters
deviceId the deviceId
context processing context
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 143 of file SpringOpenTTP.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.deviceId, org.onosproject.driver.pipeline.SpringOpenTTP.fail(), org.onosproject.driver.pipeline.SpringOpenTTP.flowObjectiveStore, org.onosproject.net.flowobjective.ObjectiveError.GROUPINSTALLATIONFAILED, org.onosproject.driver.pipeline.SpringOpenTTP.groupService, and org.onosproject.driver.pipeline.SpringOpenTTP.setTableMissEntries().
void org.onosproject.driver.pipeline.SpringOpenTTP.next (NextObjective nextObjective)
Installs the next hop elements into the device.
Parameters
nextObjective a next objectives
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 227 of file SpringOpenTTP.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.deviceId, and org.onosproject.net.flowobjective.Objective.op().
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), and org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific().
void org.onosproject.driver.pipeline.SpringOpenTTP.populateTableMissEntry (int tableToAdd, boolean toControllerNow, boolean toControllerWrite, boolean toTable, int tableToSend) protected
Definition at line 972 of file SpringOpenTTP.java.
References org.onosproject.net.PortNumber.CONTROLLER.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.setTableMissEntries().
List<FlowRule> org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstFilter (EthCriterion ethCriterion, VlanIdCriterion vlanIdCriterion, FilteringObjective filt, VlanId assignedVlan, ApplicationId applicationId) protected
Definition at line 776 of file SpringOpenTTP.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.ipv4UnicastTableId, org.onosproject.net.flow.criteria.Criteria.matchVlanId(), org.onlab.packet.Ethernet.MPLS_UNICAST, org.onosproject.driver.pipeline.SpringOpenTTP.mplsTableId, org.onlab.packet.VlanId.NONE, org.onosproject.driver.pipeline.SpringOpenTTP.tmacTableId, and org.onlab.packet.Ethernet.TYPE_IPV4.
Collection<FlowRule> org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective (ForwardingObjective fwd) protected
Definition at line 672 of file SpringOpenTTP.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.aclTableId, org.onosproject.driver.pipeline.SpringOpenTTP.deviceId, org.onosproject.driver.pipeline.SpringOpenTTP.dstMacTableId, org.onosproject.driver.pipeline.SpringOpenTTP.fail(), org.onosproject.net.flowobjective.ObjectiveError.GROUPMISSING, org.onosproject.net.group.Group.id(), org.onosproject.net.flowobjective.Objective.id(), org.onosproject.driver.pipeline.SpringOpenTTP.next(), org.onosproject.net.flowobjective.ForwardingObjective.nextId(), org.onlab.packet.MacAddress.NONE, org.onosproject.net.flowobjective.Objective.permanent(), and org.onosproject.net.flowobjective.ForwardingObjective.treatment().
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processSpecific().
Collection<FlowRule> org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective (ForwardingObjective fwd) protected
Definition at line 584 of file SpringOpenTTP.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.aclTableId, org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.driver.pipeline.SpringOpenTTP.deviceId, org.onosproject.driver.pipeline.SpringOpenTTP.fail(), org.onosproject.net.flow.TrafficSelector.getCriterion(), org.onosproject.net.flowobjective.ObjectiveError.GROUPMISSING, org.onosproject.net.group.Group.id(), org.onosproject.net.flowobjective.Objective.id(), org.onosproject.driver.pipeline.SpringOpenTTP.ipv4UnicastTableId, org.onlab.packet.Ethernet.MPLS_UNICAST, org.onosproject.driver.pipeline.SpringOpenTTP.mplsTableId, org.onosproject.driver.pipeline.SpringOpenTTP.next(), org.onosproject.net.flowobjective.ForwardingObjective.nextId(), org.onosproject.net.flowobjective.Objective.permanent(), org.onosproject.net.flowobjective.Objective.priority(), org.onosproject.net.flowobjective.ForwardingObjective.treatment(), and org.onlab.packet.Ethernet.TYPE_IPV4.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processSpecific().
Collection<FlowRule> org.onosproject.driver.pipeline.SpringOpenTTP.processSpecific (ForwardingObjective fwd) protected
Definition at line 565 of file SpringOpenTTP.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.fail(), org.onosproject.net.flowobjective.ForwardingObjective.nextId(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
List<FlowRule> org.onosproject.driver.pipeline.SpringOpenTTP.processVlanIdFilter (VlanIdCriterion vlanIdCriterion, FilteringObjective filt, VlanId assignedVlan, ApplicationId applicationId) protected
Definition at line 830 of file SpringOpenTTP.java.
References org.onosproject.net.flowobjective.FilteringObjective.key(), org.onlab.packet.VlanId.NONE, org.onosproject.driver.pipeline.SpringOpenTTP.tmacTableId, and org.onosproject.driver.pipeline.SpringOpenTTP.vlanTableId.
void org.onosproject.driver.pipeline.SpringOpenTTP.setTableMissEntries () protected
Definition at line 962 of file SpringOpenTTP.java.
References org.onosproject.driver.pipeline.SpringOpenTTP.aclTableId, org.onosproject.driver.pipeline.SpringOpenTTP.dstMacTableId, org.onosproject.driver.pipeline.SpringOpenTTP.ipv4UnicastTableId, org.onosproject.driver.pipeline.SpringOpenTTP.mplsTableId, org.onosproject.driver.pipeline.SpringOpenTTP.populateTableMissEntry(), org.onosproject.driver.pipeline.SpringOpenTTP.tmacTableId, and org.onosproject.driver.pipeline.SpringOpenTTP.vlanTableId.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.init().
Member Data Documentation
int org.onosproject.driver.pipeline.SpringOpenTTP.aclTableId = TABLE_ACL protected
Definition at line 114 of file SpringOpenTTP.java.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), org.onosproject.driver.pipeline.SpringOpenTTP.setTableMissEntries(), and org.onosproject.driver.pipeline.SpringOpenTTPDell.SpringOpenTTPDell().
KryoNamespace org.onosproject.driver.pipeline.SpringOpenTTP.appKryo protected
Initial value:
= new KryoNamespace.Builder()
            .register(KryoNamespaces.API)
            .register(GroupKey.class)
            .register(DefaultGroupKey.class)
            .register(TrafficTreatment.class)
            .register(SpringOpenGroup.class)
            .register(byte[].class)
            .build()
Definition at line 133 of file SpringOpenTTP.java.
DeviceId org.onosproject.driver.pipeline.SpringOpenTTP.deviceId protected
Definition at line 124 of file SpringOpenTTP.java.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.forward(), org.onosproject.driver.pipeline.SpringOpenTTP.init(), org.onosproject.driver.pipeline.SpringOpenTTP.next(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), and org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific().
int org.onosproject.driver.pipeline.SpringOpenTTP.dstMacTableId = TABLE_DMAC protected
Definition at line 113 of file SpringOpenTTP.java.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), and org.onosproject.driver.pipeline.SpringOpenTTP.setTableMissEntries().
FlowObjectiveStore org.onosproject.driver.pipeline.SpringOpenTTP.flowObjectiveStore protected
Definition at line 123 of file SpringOpenTTP.java.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.init().
GroupService org.onosproject.driver.pipeline.SpringOpenTTP.groupService protected
Definition at line 122 of file SpringOpenTTP.java.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.init().
int org.onosproject.driver.pipeline.SpringOpenTTP.ipv4UnicastTableId = TABLE_IPV4_UNICAST protected
Definition at line 111 of file SpringOpenTTP.java.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), org.onosproject.driver.pipeline.SpringOpenTTP.setTableMissEntries(), and org.onosproject.driver.pipeline.SpringOpenTTPDell.SpringOpenTTPDell().
final Logger org.onosproject.driver.pipeline.SpringOpenTTP.log = getLogger(getClass()) protected
Definition at line 117 of file SpringOpenTTP.java.
int org.onosproject.driver.pipeline.SpringOpenTTP.mplsTableId = TABLE_MPLS protected
Definition at line 112 of file SpringOpenTTP.java.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), org.onosproject.driver.pipeline.SpringOpenTTP.setTableMissEntries(), and org.onosproject.driver.pipeline.SpringOpenTTPDell.SpringOpenTTPDell().
int org.onosproject.driver.pipeline.SpringOpenTTP.srcMacTableId = TABLE_SMAC protected
Definition at line 115 of file SpringOpenTTP.java.
int org.onosproject.driver.pipeline.SpringOpenTTP.tmacTableId = TABLE_TMAC protected
Definition at line 110 of file SpringOpenTTP.java.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.processVlanIdFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.setTableMissEntries(), and org.onosproject.driver.pipeline.SpringOpenTTPDell.SpringOpenTTPDell().
int org.onosproject.driver.pipeline.SpringOpenTTP.vlanTableId = TABLE_VLAN protected
Set the default values.
These variables will get overwritten based on the switch vendor type
Definition at line 109 of file SpringOpenTTP.java.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processVlanIdFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.setTableMissEntries(), and org.onosproject.driver.pipeline.SpringOpenTTPDell.SpringOpenTTPDell().
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/pipeline/SpringOpenTTP.java