onos: org.onosproject.net.intent.MultiPointToSinglePointIntentTest Class Reference
org.onosproject.net.intent.MultiPointToSinglePointIntentTest Class Reference
Suite of tests of the multi-to-single point intent descriptor.
Public Member Functions
void checkImmutability ()
Checks that the MultiPointToSinglePointIntent class is immutable.
void basics ()
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Protected Member Functions
MultiPointToSinglePointIntent createOne ()
Creates a new intent, but always a like intent, i.e.
MultiPointToSinglePointIntent createAnother ()
Creates another intent, not equals to the one created by createOne() and with a different hash code.
Additional Inherited Members
Static Public Attributes inherited from org.onosproject.net.intent.ConnectivityIntentTest
static final ApplicationId APPID = new TestApplicationId("foo")
static final Key KEY = Key.of(1L, APPID)
static final IntentId IID = new IntentId(123)
static final TrafficSelector MATCH = DefaultTrafficSelector.emptySelector()
static final TrafficTreatment NOP = DefaultTrafficTreatment.emptyTreatment()
static final ConnectPoint P1 = new ConnectPoint(DeviceId.deviceId("111"), PortNumber.portNumber(0x1))
static final ConnectPoint P2 = new ConnectPoint(DeviceId.deviceId("222"), PortNumber.portNumber(0x2))
static final ConnectPoint P3 = new ConnectPoint(DeviceId.deviceId("333"), PortNumber.portNumber(0x3))
static final Set< ConnectPoint > PS1 = itemSet(new ConnectPoint[]{P1, P3})
static final Set< ConnectPoint > PS2 = itemSet(new ConnectPoint[]{P2, P3})
Static Protected Member Functions inherited from org.onosproject.net.intent.IntentTest
static< T > Set< T > itemSet (T[] items)
Produces a set of items from the supplied items.
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
Suite of tests of the multi-to-single point intent descriptor.
Definition at line 26 of file MultiPointToSinglePointIntentTest.java.
Member Function Documentation
void org.onosproject.net.intent.MultiPointToSinglePointIntentTest.basics ()
Definition at line 37 of file MultiPointToSinglePointIntentTest.java.
References org.onosproject.net.intent.ConnectivityIntentTest.APPID, org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createOne(), org.onosproject.net.intent.ConnectivityIntentTest.MATCH, org.onosproject.net.intent.ConnectivityIntentTest.P2, org.onosproject.net.intent.ConnectivityIntentTest.PS1, and org.onosproject.net.intent.ConnectivityIntent.selector().
void org.onosproject.net.intent.MultiPointToSinglePointIntentTest.checkImmutability ()
Checks that the MultiPointToSinglePointIntent class is immutable.
Definition at line 32 of file MultiPointToSinglePointIntentTest.java.
MultiPointToSinglePointIntent org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createAnother () protected virtual
Creates another intent, not equals to the one created by createOne() and with a different hash code.
Returns
another intent
Implements org.onosproject.net.intent.IntentTest.
Definition at line 57 of file MultiPointToSinglePointIntentTest.java.
References org.onosproject.net.intent.ConnectivityIntentTest.APPID, org.onosproject.net.intent.ConnectivityIntentTest.MATCH, org.onosproject.net.intent.ConnectivityIntentTest.NOP, org.onosproject.net.intent.ConnectivityIntentTest.P1, and org.onosproject.net.intent.ConnectivityIntentTest.PS2.
MultiPointToSinglePointIntent org.onosproject.net.intent.MultiPointToSinglePointIntentTest.createOne () protected virtual
Creates a new intent, but always a like intent, i.e.
all instances will be equal, but should not be the same.
Returns
intent
Implements org.onosproject.net.intent.IntentTest.
Definition at line 46 of file MultiPointToSinglePointIntentTest.java.
References org.onosproject.net.intent.ConnectivityIntentTest.APPID, org.onosproject.net.intent.ConnectivityIntentTest.MATCH, org.onosproject.net.intent.ConnectivityIntentTest.NOP, org.onosproject.net.intent.ConnectivityIntentTest.P2, and org.onosproject.net.intent.ConnectivityIntentTest.PS1.
Referenced by org.onosproject.net.intent.MultiPointToSinglePointIntentTest.basics().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/intent/MultiPointToSinglePointIntentTest.java