onos: org.onosproject.pcepio.types.OpaqueLinkAttributeTlv Class Reference
org.onosproject.pcepio.types.OpaqueLinkAttributeTlv Class Reference
Provides Opaque Link Attribute.
Public Member Functions
OpaqueLinkAttributeTlv (byte[] rawValue, short hLength)
constructor to initialize rawValue.
byte[] getValue ()
Returns raw value of Opaque Link Attribute Tlv.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static OpaqueLinkAttributeTlv of (final byte[] raw, short hLength)
Returns newly created OpaqueLinkAttributeTlv object.
static PcepValueType read (ChannelBuffer c, short hLength)
Reads the channel buffer and returns object of OpaqueLinkAttributeTlv.
Static Public Attributes
static final short TYPE = 1097
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(OpaqueLinkAttributeTlv.class)
Detailed Description
Provides Opaque Link Attribute.
Definition at line 30 of file OpaqueLinkAttributeTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.OpaqueLinkAttributeTlv (byte[] rawValue, short hLength)
constructor to initialize rawValue.
Parameters
rawValue of Opaque Link Attribute
hLength length
Definition at line 57 of file OpaqueLinkAttributeTlv.java.
Referenced by org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.equals(), org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.of(), and org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.equals (Object obj)
Definition at line 107 of file OpaqueLinkAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.OpaqueLinkAttributeTlv().
short org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 97 of file OpaqueLinkAttributeTlv.java.
short org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 92 of file OpaqueLinkAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.TYPE.
byte [] org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.getValue ()
Returns raw value of Opaque Link Attribute Tlv.
Returns
rawValue raw value
Definition at line 82 of file OpaqueLinkAttributeTlv.java.
PcepVersion org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 87 of file OpaqueLinkAttributeTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.hashCode ()
Definition at line 102 of file OpaqueLinkAttributeTlv.java.
static OpaqueLinkAttributeTlv org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.of (final byte[] raw, short hLength) static
Returns newly created OpaqueLinkAttributeTlv object.
Parameters
raw of Opaque Link Attribute
hLength length
Returns
new object of OpaqueLinkAttributeTlv
Definition at line 74 of file OpaqueLinkAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.OpaqueLinkAttributeTlv().
static PcepValueType org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.read (ChannelBuffer c, short hLength) static
Reads the channel buffer and returns object of OpaqueLinkAttributeTlv.
Parameters
c input channel buffer
hLength length
Returns
object of Opaque Link Attribute Tlv
Definition at line 134 of file OpaqueLinkAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.OpaqueLinkAttributeTlv().
String org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.toString ()
Definition at line 141 of file OpaqueLinkAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.TYPE.
int org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 119 of file OpaqueLinkAttributeTlv.java.
References org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.TYPE.
Member Data Documentation
final Logger org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.log = LoggerFactory.getLogger(OpaqueLinkAttributeTlv.class) static protected
Definition at line 44 of file OpaqueLinkAttributeTlv.java.
final short org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.TYPE = 1097 static
Definition at line 46 of file OpaqueLinkAttributeTlv.java.
Referenced by org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.getType(), org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.toString(), and org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/OpaqueLinkAttributeTlv.java