onos: org.onlab.jdvue.JavaEntity Class Reference
org.onlab.jdvue.JavaEntity Class Reference
Abstraction of a Java source entity.
Public Member Functions
String name ()
Returns the Java source entity name.
boolean equals (Object o)
int hashCode ()
Detailed Description
Abstraction of a Java source entity.
Definition at line 23 of file JavaEntity.java.
Member Function Documentation
boolean org.onlab.jdvue.JavaEntity.equals (Object o)
Definition at line 46 of file JavaEntity.java.
References create-flow.name, and org.onlab.jdvue.JavaEntity.name().
int org.onlab.jdvue.JavaEntity.hashCode ()
Definition at line 56 of file JavaEntity.java.
References org.onlab.jdvue.JavaEntity.name().
String org.onlab.jdvue.JavaEntity.name ()
Returns the Java source entity name.
Returns
source entity name
Definition at line 41 of file JavaEntity.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onlab.jdvue.JavaEntity.equals(), org.onlab.jdvue.JavaEntity.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), org.onlab.jdvue.JavaPackage.toString(), and org.onlab.jdvue.JavaSource.toString().
The documentation for this class was generated from the following file:
utils/jdvue/src/main/java/org/onlab/jdvue/JavaEntity.java