onos: org.onosproject.store.trivial.SimpleLinkStoreTest Class Reference
org.onosproject.store.trivial.SimpleLinkStoreTest Class Reference
Test of the simple LinkStore implementation.
Public Member Functions
void setUp () throws Exception
void tearDown () throws Exception
final void testGetLinkCount ()
final void testGetLinks ()
final void testGetDeviceEgressLinks ()
final void testGetDeviceIngressLinks ()
final void testGetLink ()
final void testGetEgressLinks ()
final void testGetIngressLinks ()
final void testCreateOrUpdateLink ()
final void testCreateOrUpdateLinkAncillary ()
final void testRemoveOrDownLink ()
final void testRemoveOrDownLinkDurable ()
final void testRemoveLink ()
final void testAncillaryVisible ()
void testDurableToNonDurable ()
void testNonDurableToDurable ()
final void testEvents () throws InterruptedException
Static Public Member Functions
static void setUpBeforeClass () throws Exception
static void tearDownAfterClass () throws Exception
Detailed Description
Test of the simple LinkStore implementation.
Definition at line 56 of file SimpleLinkStoreTest.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleLinkStoreTest.setUp () throws Exception
Definition at line 114 of file SimpleLinkStoreTest.java.
static void org.onosproject.store.trivial.SimpleLinkStoreTest.setUpBeforeClass () throws Exception static
Definition at line 106 of file SimpleLinkStoreTest.java.
void org.onosproject.store.trivial.SimpleLinkStoreTest.tearDown () throws Exception
Definition at line 121 of file SimpleLinkStoreTest.java.
static void org.onosproject.store.trivial.SimpleLinkStoreTest.tearDownAfterClass () throws Exception static
Definition at line 110 of file SimpleLinkStoreTest.java.
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testAncillaryVisible ()
Definition at line 453 of file SimpleLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLink(), and org.onosproject.net.link.LinkStore.getLinkCount().
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testCreateOrUpdateLink ()
Definition at line 304 of file SimpleLinkStoreTest.java.
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testCreateOrUpdateLinkAncillary ()
Definition at line 330 of file SimpleLinkStoreTest.java.
void org.onosproject.store.trivial.SimpleLinkStoreTest.testDurableToNonDurable ()
Definition at line 467 of file SimpleLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLink().
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testEvents () throws InterruptedException
Definition at line 494 of file SimpleLinkStoreTest.java.
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testGetDeviceEgressLinks ()
Definition at line 193 of file SimpleLinkStoreTest.java.
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testGetDeviceIngressLinks ()
Definition at line 216 of file SimpleLinkStoreTest.java.
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testGetEgressLinks ()
Definition at line 254 of file SimpleLinkStoreTest.java.
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testGetIngressLinks ()
Definition at line 279 of file SimpleLinkStoreTest.java.
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testGetLink ()
Definition at line 239 of file SimpleLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLink().
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testGetLinkCount ()
Definition at line 158 of file SimpleLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLinkCount().
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testGetLinks ()
Definition at line 169 of file SimpleLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLinks().
void org.onosproject.store.trivial.SimpleLinkStoreTest.testNonDurableToDurable ()
Definition at line 479 of file SimpleLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLink().
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testRemoveLink ()
Definition at line 424 of file SimpleLinkStoreTest.java.
References org.onosproject.net.link.LinkStore.getLink().
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testRemoveOrDownLink ()
Definition at line 383 of file SimpleLinkStoreTest.java.
final void org.onosproject.store.trivial.SimpleLinkStoreTest.testRemoveOrDownLinkDurable ()
Definition at line 388 of file SimpleLinkStoreTest.java.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleLinkStoreTest.java