onos: org.onosproject.bgpio.types.Med Class Reference
org.onosproject.bgpio.types.Med Class Reference
Provides Implementation of Med BGP Path Attribute.
Public Member Functions
Med (int med)
Constructor to initialize med.
int med ()
Returns Med value.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
String toString ()
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static Med read (ChannelBuffer cb) throws BgpParseException
Reads the channel buffer and returns object of Med.
Static Public Attributes
static final byte MED_TYPE = 4
static final byte MED_MAX_LEN = 4
Detailed Description
Provides Implementation of Med BGP Path Attribute.
Definition at line 30 of file Med.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.Med.Med (int med)
Constructor to initialize med.
Parameters
med MULTI_EXIT_DISC value
Definition at line 41 of file Med.java.
References org.onosproject.bgpio.types.Med.med().
Referenced by org.onosproject.bgpio.types.Med.equals(), and org.onosproject.bgpio.types.Med.read().
Member Function Documentation
int org.onosproject.bgpio.types.Med.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 117 of file Med.java.
boolean org.onosproject.bgpio.types.Med.equals (Object obj)
Definition at line 92 of file Med.java.
References org.onosproject.bgpio.types.Med.Med(), and org.onosproject.bgpio.types.Med.med().
Referenced by org.onosproject.bgp.controller.impl.BgpSelectionAlgo.compare().
short org.onosproject.bgpio.types.Med.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 82 of file Med.java.
References org.onosproject.bgpio.types.Med.MED_TYPE.
int org.onosproject.bgpio.types.Med.hashCode ()
Definition at line 87 of file Med.java.
References org.onosproject.bgpio.types.Med.med().
int org.onosproject.bgpio.types.Med.med ()
Returns Med value.
Returns
Med value
Definition at line 50 of file Med.java.
Referenced by org.onosproject.bgpio.types.Med.equals(), org.onosproject.bgpio.types.Med.hashCode(), org.onosproject.bgpio.types.Med.Med(), org.onosproject.bgpio.types.Med.read(), and org.onosproject.bgpio.types.Med.toString().
static Med org.onosproject.bgpio.types.Med.read (ChannelBuffer cb) throws BgpParseException static
Reads the channel buffer and returns object of Med.
Parameters
cb ChannelBuffer
Returns
object of Med
Exceptions
BgpParseException while parsing Med path attribute
Definition at line 61 of file Med.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_FLAGS_ERROR, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.Med.Med(), org.onosproject.bgpio.types.Med.med(), org.onosproject.bgpio.types.Med.MED_MAX_LEN, org.onosproject.bgpio.util.Constants.TYPE_AND_LEN_AS_BYTE, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.Med.toString ()
Definition at line 104 of file Med.java.
References org.onosproject.bgpio.types.Med.med().
int org.onosproject.bgpio.types.Med.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 111 of file Med.java.
Member Data Documentation
final byte org.onosproject.bgpio.types.Med.MED_MAX_LEN = 4 static
Definition at line 32 of file Med.java.
Referenced by org.onosproject.bgpio.types.Med.read().
final byte org.onosproject.bgpio.types.Med.MED_TYPE = 4 static
Definition at line 31 of file Med.java.
Referenced by org.onosproject.bgpio.types.Med.getType().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/Med.java