onos: org.onosproject.net.OchSignal Class Reference
org.onosproject.net.OchSignal Class Reference
Implementation of Lambda representing OCh (Optical Channel) Signal.
Public Member Functions
OchSignal (GridType gridType, ChannelSpacing channelSpacing, int spacingMultiplier, int slotGranularity)
Creates an instance with the specified arguments.
OchSignal (int channel, Frequency maxFrequency, Frequency grid)
Create OCh signal from channel number.
OchSignal (Frequency centerFrequency, ChannelSpacing channelSpacing, int slotGranularity)
GridType gridType ()
Returns grid type.
ChannelSpacing channelSpacing ()
Returns channel spacing.
int spacingMultiplier ()
Returns spacing multiplier.
int slotGranularity ()
Returns slow width granularity.
Frequency centralFrequency ()
Returns central frequency in MHz.
Frequency slotWidth ()
Returns slot width.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Attributes
static final Frequency CENTER_FREQUENCY = Frequency.ofTHz(193.1)
static final Frequency FLEX_GRID_SLOT = Frequency.ofGHz(12.5)
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.net.Lambda
static Lambda indexedLambda (long lambda)
Create an Lambda instance with the specified wavelength index number.
static Lambda ochSignal (GridType gridType, ChannelSpacing channelSpacing, int spacingMultiplier, int slotGranularity)
Creates a Lambda instance with the specified arguments.
Detailed Description
Implementation of Lambda representing OCh (Optical Channel) Signal.
See ITU G.709 "Interfaces for the Optical Transport Network (OTN)".
Definition at line 33 of file OchSignal.java.
Constructor & Destructor Documentation
org.onosproject.net.OchSignal.OchSignal (GridType gridType, ChannelSpacing channelSpacing, int spacingMultiplier, int slotGranularity)
Creates an instance with the specified arguments.
It it recommended to use Lambda#ochSignal(GridType, ChannelSpacing, int, int) unless you want to use the concrete type, OchSignal, directly.
Parameters
gridType grid type
channelSpacing channel spacing
spacingMultiplier channel spacing multiplier
slotGranularity slot width granularity
Definition at line 58 of file OchSignal.java.
References org.onosproject.net.OchSignal.slotGranularity(), and org.onosproject.net.OchSignal.spacingMultiplier().
Referenced by org.onosproject.net.OchSignal.equals().
org.onosproject.net.OchSignal.OchSignal (int channel, Frequency maxFrequency, Frequency grid)
Create OCh signal from channel number.
Parameters
channel channel number
maxFrequency maximum frequency
grid grid spacing frequency
Definition at line 75 of file OchSignal.java.
References org.onlab.util.Frequency.asHz(), org.onosproject.net.OchSignal.CENTER_FREQUENCY, and org.onlab.util.Frequency.subtract().
org.onosproject.net.OchSignal.OchSignal (Frequency centerFrequency, ChannelSpacing channelSpacing, int slotGranularity)
Definition at line 85 of file OchSignal.java.
References org.onlab.util.Frequency.asHz(), org.onosproject.net.OchSignal.CENTER_FREQUENCY, org.onosproject.net.OchSignal.channelSpacing(), and org.onosproject.net.OchSignal.slotGranularity().
Member Function Documentation
Frequency org.onosproject.net.OchSignal.centralFrequency ()
Returns central frequency in MHz.
Returns
frequency in MHz
Definition at line 134 of file OchSignal.java.
References org.onosproject.net.OchSignal.channelSpacing(), and org.onosproject.net.OchSignal.spacingMultiplier().
ChannelSpacing org.onosproject.net.OchSignal.channelSpacing ()
Returns channel spacing.
Returns
channel spacing
Definition at line 107 of file OchSignal.java.
Referenced by org.onosproject.net.OchSignal.centralFrequency(), org.onosproject.net.OchSignal.hashCode(), org.onosproject.net.OchSignal.OchSignal(), and org.onosproject.net.OchSignal.toString().
boolean org.onosproject.net.OchSignal.equals (Object obj)
Definition at line 153 of file OchSignal.java.
References org.onosproject.net.OchSignal.OchSignal().
GridType org.onosproject.net.OchSignal.gridType ()
Returns grid type.
Returns
grid type
Definition at line 98 of file OchSignal.java.
Referenced by org.onosproject.net.OchSignal.hashCode(), and org.onosproject.net.OchSignal.toString().
int org.onosproject.net.OchSignal.hashCode ()
Definition at line 148 of file OchSignal.java.
References org.onosproject.net.OchSignal.channelSpacing(), org.onosproject.net.OchSignal.gridType(), org.onosproject.net.OchSignal.slotGranularity(), and org.onosproject.net.OchSignal.spacingMultiplier().
int org.onosproject.net.OchSignal.slotGranularity ()
Returns slow width granularity.
Returns
slow width granularity
Definition at line 125 of file OchSignal.java.
Referenced by org.onosproject.net.OchSignal.hashCode(), org.onosproject.net.OchSignal.OchSignal(), org.onosproject.net.OchSignal.slotWidth(), and org.onosproject.net.OchSignal.toString().
Frequency org.onosproject.net.OchSignal.slotWidth ()
Returns slot width.
Returns
slot width
Definition at line 143 of file OchSignal.java.
References org.onosproject.net.OchSignal.slotGranularity().
int org.onosproject.net.OchSignal.spacingMultiplier ()
Returns spacing multiplier.
Returns
spacing multiplier
Definition at line 116 of file OchSignal.java.
Referenced by org.onosproject.net.OchSignal.centralFrequency(), org.onosproject.net.OchSignal.hashCode(), org.onosproject.net.OchSignal.OchSignal(), and org.onosproject.net.OchSignal.toString().
String org.onosproject.net.OchSignal.toString ()
Definition at line 168 of file OchSignal.java.
References org.onosproject.net.OchSignal.channelSpacing(), org.onosproject.net.OchSignal.gridType(), org.onosproject.net.OchSignal.slotGranularity(), and org.onosproject.net.OchSignal.spacingMultiplier().
Member Data Documentation
final Frequency org.onosproject.net.OchSignal.CENTER_FREQUENCY = Frequency.ofTHz(193.1) static
Definition at line 35 of file OchSignal.java.
Referenced by org.onosproject.net.OchSignal.OchSignal().
final Frequency org.onosproject.net.OchSignal.FLEX_GRID_SLOT = Frequency.ofGHz(12.5) static
Definition at line 36 of file OchSignal.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/OchSignal.java