onos: org.onosproject.net.statistic.impl.FlowStatisticManager Class Reference
org.onosproject.net.statistic.impl.FlowStatisticManager Class Reference
Provides an implementation of the Flow Statistic Service.
Public Member Functions
void activate ()
void deactivate ()
Map< ConnectPoint,
SummaryFlowEntryWithLoad > loadSummary (Device device)
Obtain the summary load list for the device with the given link.
SummaryFlowEntryWithLoad loadSummary (Device device, PortNumber pNumber)
Obtain the summary load for the device with the given link or port.
Map< ConnectPoint, List
< TypedFlowEntryWithLoad > > loadAllByType (Device device, TypedStoredFlowEntry.FlowLiveType liveType, Instruction.Type instType)
Obtain the set of the flow type and load list for the device with the given link.
List< TypedFlowEntryWithLoad > loadAllByType (Device device, PortNumber pNumber, TypedStoredFlowEntry.FlowLiveType liveType, Instruction.Type instType)
Obtain the flow type and load list for the device with the given link or port.
Map< ConnectPoint, List
< TypedFlowEntryWithLoad > > loadTopnByType (Device device, TypedStoredFlowEntry.FlowLiveType liveType, Instruction.Type instType, int topn)
Obtain the set of the flow type and load topn list for the device with the given link.
List< TypedFlowEntryWithLoad > loadTopnByType (Device device, PortNumber pNumber, TypedStoredFlowEntry.FlowLiveType liveType, Instruction.Type instType, int topn)
Obtain the flow type and load topn list for the device with the given link or port.
Protected Attributes
FlowRuleService flowRuleService
FlowStatisticStore flowStatisticStore
DeviceService deviceService
Detailed Description
Provides an implementation of the Flow Statistic Service.
Definition at line 70 of file FlowStatisticManager.java.
Member Function Documentation
void org.onosproject.net.statistic.impl.FlowStatisticManager.activate ()
Definition at line 85 of file FlowStatisticManager.java.
void org.onosproject.net.statistic.impl.FlowStatisticManager.deactivate ()
Definition at line 91 of file FlowStatisticManager.java.
Map<ConnectPoint, List<TypedFlowEntryWithLoad> > org.onosproject.net.statistic.impl.FlowStatisticManager.loadAllByType (Device device, TypedStoredFlowEntry.FlowLiveType liveType, Instruction.Type instType)
Obtain the set of the flow type and load list for the device with the given link.
Parameters
device the Device to query.
liveType the FlowLiveType to filter, null means no filtering .
instType the InstructionType to filter, null means no filtering.
Returns
map of flow entry load
Implements org.onosproject.net.statistic.FlowStatisticService.
Definition at line 126 of file FlowStatisticManager.java.
References org.onosproject.cli.Comparators.CONNECT_POINT_COMPARATOR, org.onosproject.net.Device.id(), and obeliskHostCheck.port.
List<TypedFlowEntryWithLoad> org.onosproject.net.statistic.impl.FlowStatisticManager.loadAllByType (Device device, PortNumber pNumber, TypedStoredFlowEntry.FlowLiveType liveType, Instruction.Type instType)
Obtain the flow type and load list for the device with the given link or port.
Parameters
device the Device to query.
pNumber the port number of the Device to query
liveType the FlowLiveType to filter, null means no filtering .
instType the InstructionType to filter, null means no filtering.
Returns
list of flow entry load
Implements org.onosproject.net.statistic.FlowStatisticService.
Definition at line 149 of file FlowStatisticManager.java.
References org.onosproject.net.Device.id().
Map<ConnectPoint, SummaryFlowEntryWithLoad> org.onosproject.net.statistic.impl.FlowStatisticManager.loadSummary (Device device)
Obtain the summary load list for the device with the given link.
Parameters
device the Device to query.
Returns
map of summary flow entry load
Implements org.onosproject.net.statistic.FlowStatisticService.
Definition at line 97 of file FlowStatisticManager.java.
References org.onosproject.cli.Comparators.CONNECT_POINT_COMPARATOR, org.onosproject.net.Device.id(), and obeliskHostCheck.port.
SummaryFlowEntryWithLoad org.onosproject.net.statistic.impl.FlowStatisticManager.loadSummary (Device device, PortNumber pNumber)
Obtain the summary load for the device with the given link or port.
Parameters
device the Device to query.
pNumber the port number to query.
Returns
summary flow entry load
Implements org.onosproject.net.statistic.FlowStatisticService.
Definition at line 118 of file FlowStatisticManager.java.
References org.onosproject.net.Device.id().
Map<ConnectPoint, List<TypedFlowEntryWithLoad> > org.onosproject.net.statistic.impl.FlowStatisticManager.loadTopnByType (Device device, TypedStoredFlowEntry.FlowLiveType liveType, Instruction.Type instType, int topn)
Obtain the set of the flow type and load topn list for the device with the given link.
Parameters
device the Device to query.
liveType the FlowLiveType to filter, null means no filtering .
instType the InstructionType to filter, null means no filtering.
topn the top number to filter, null means no filtering.
Returns
map of flow entry load
Implements org.onosproject.net.statistic.FlowStatisticService.
Definition at line 159 of file FlowStatisticManager.java.
References org.onosproject.cli.Comparators.CONNECT_POINT_COMPARATOR, org.onosproject.net.Device.id(), and obeliskHostCheck.port.
List<TypedFlowEntryWithLoad> org.onosproject.net.statistic.impl.FlowStatisticManager.loadTopnByType (Device device, PortNumber pNumber, TypedStoredFlowEntry.FlowLiveType liveType, Instruction.Type instType, int topn)
Obtain the flow type and load topn list for the device with the given link or port.
Parameters
device the Device to query.
pNumber the port number of the Device to query
liveType the FlowLiveType to filter, null means no filtering .
instType the InstructionType to filter, null means no filtering.
topn topn //FIXME what?
Returns
list of flow entry load
Implements org.onosproject.net.statistic.FlowStatisticService.
Definition at line 183 of file FlowStatisticManager.java.
References org.onosproject.net.Device.id().
Member Data Documentation
DeviceService org.onosproject.net.statistic.impl.FlowStatisticManager.deviceService protected
Definition at line 80 of file FlowStatisticManager.java.
FlowRuleService org.onosproject.net.statistic.impl.FlowStatisticManager.flowRuleService protected
Definition at line 74 of file FlowStatisticManager.java.
FlowStatisticStore org.onosproject.net.statistic.impl.FlowStatisticManager.flowStatisticStore protected
Definition at line 77 of file FlowStatisticManager.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/statistic/impl/FlowStatisticManager.java