onos: org.onlab.packet.ArpTest Class Reference
org.onlab.packet.ArpTest Class Reference
Unit tests for the ARP class.
Public Member Functions
void setUp ()
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws Exception
Detailed Description
Unit tests for the ARP class.
Definition at line 31 of file ArpTest.java.
Member Function Documentation
void org.onlab.packet.ArpTest.setUp ()
Definition at line 46 of file ArpTest.java.
References org.onlab.packet.ARP.HW_TYPE_ETHERNET, org.onlab.packet.ARP.OP_REPLY, and org.onlab.packet.ARP.PROTO_TYPE_IP.
void org.onlab.packet.ArpTest.testDeserialize () throws Exception
Definition at line 74 of file ArpTest.java.
References org.onlab.packet.ARP.getHardwareAddressLength(), org.onlab.packet.ARP.getHardwareType(), org.onlab.packet.ARP.getOpCode(), org.onlab.packet.ARP.getProtocolAddressLength(), org.onlab.packet.ARP.getProtocolType(), org.onlab.packet.ARP.HW_TYPE_ETHERNET, find-link-in-cluster.length, org.onlab.packet.ARP.OP_REPLY, org.onlab.packet.ARP.PROTO_TYPE_IP, org.onlab.packet.MacAddress.toBytes(), and org.onlab.packet.IpAddress.toOctets().
void org.onlab.packet.ArpTest.testDeserializeBadInput () throws Exception
Definition at line 64 of file ArpTest.java.
void org.onlab.packet.ArpTest.testDeserializeTruncated () throws Exception
Definition at line 69 of file ArpTest.java.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ArpTest.java