onos: org.onosproject.incubator.net.virtual .NetworkId Class Reference
org.onosproject.incubator.net.virtual .NetworkId Class Reference
Representation of network identity.
Public Member Functions
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static NetworkId networkId (long id)
Creates a network id using the supplied backing id.
Static Public Attributes
static final NetworkId NONE = networkId(-1L)
Represents no network, or an unspecified network.
static final NetworkId PHYSICAL = networkId(0L)
Represents the underlying physical network.
Protected Member Functions
NetworkId ()
Detailed Description
Representation of network identity.
Definition at line 26 of file NetworkId.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.virtual .NetworkId.NetworkId () protected
Definition at line 48 of file NetworkId.java.
Referenced by org.onosproject.incubator.net.virtual .NetworkId.equals(), and org.onosproject.incubator.net.virtual .NetworkId.networkId().
Member Function Documentation
boolean org.onosproject.incubator.net.virtual .NetworkId.equals (Object obj)
Definition at line 68 of file NetworkId.java.
References find-device.id, and org.onosproject.incubator.net.virtual .NetworkId.NetworkId().
int org.onosproject.incubator.net.virtual .NetworkId.hashCode ()
Definition at line 63 of file NetworkId.java.
Referenced by org.onosproject.incubator.net.virtual .DefaultVirtualDevice.hashCode().
static NetworkId org.onosproject.incubator.net.virtual .NetworkId.networkId (long id) static
Creates a network id using the supplied backing id.
Parameters
id network id
Returns
network identifier
Definition at line 58 of file NetworkId.java.
References org.onosproject.incubator.net.virtual .NetworkId.NetworkId().
String org.onosproject.incubator.net.virtual .NetworkId.toString ()
Definition at line 80 of file NetworkId.java.
Member Data Documentation
final NetworkId org.onosproject.incubator.net.virtual .NetworkId.NONE = networkId(-1L) static
Represents no network, or an unspecified network.
Definition at line 31 of file NetworkId.java.
final NetworkId org.onosproject.incubator.net.virtual .NetworkId.PHYSICAL = networkId(0L) static
Represents the underlying physical network.
Definition at line 36 of file NetworkId.java.
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/virtual/NetworkId.java