onos: org.onosproject.net.ConnectPointTest Class Reference
org.onosproject.net.ConnectPointTest Class Reference
Test of the connection point entity.
Public Member Functions
void basics ()
void testEquality ()
void testParseDeviceConnectPoint ()
void testParseHostConnectPoint ()
Detailed Description
Test of the connection point entity.
Definition at line 30 of file ConnectPointTest.java.
Member Function Documentation
void org.onosproject.net.ConnectPointTest.basics ()
Definition at line 38 of file ConnectPointTest.java.
References org.onosproject.net.ConnectPoint.deviceId(), and org.onosproject.net.ConnectPoint.port().
void org.onosproject.net.ConnectPointTest.testEquality ()
Definition at line 45 of file ConnectPointTest.java.
void org.onosproject.net.ConnectPointTest.testParseDeviceConnectPoint ()
Definition at line 54 of file ConnectPointTest.java.
References org.onosproject.net.ConnectPoint.deviceId(), and org.onosproject.net.ConnectPoint.port().
void org.onosproject.net.ConnectPointTest.testParseHostConnectPoint ()
Definition at line 82 of file ConnectPointTest.java.
References org.onosproject.net.ConnectPoint.hostId(), and org.onosproject.net.ConnectPoint.port().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/ConnectPointTest.java