onos: org.onosproject.vtnweb.web.PortChainCodecTest Class Reference
org.onosproject.vtnweb.web.PortChainCodecTest Class Reference
Flow rule codec unit tests.
Public Member Functions
void setUp ()
Sets up for each test.
void codecPortChainTest () throws IOException
Checks that a simple rule decodes properly.
Detailed Description
Flow rule codec unit tests.
Definition at line 39 of file PortChainCodecTest.java.
Member Function Documentation
void org.onosproject.vtnweb.web.PortChainCodecTest.codecPortChainTest () throws IOException
Checks that a simple rule decodes properly.
Exceptions
IOException if the resource cannot be processed
Definition at line 78 of file PortChainCodecTest.java.
References org.onosproject.vtnrsc.PortChain.description(), org.onosproject.vtnrsc.PortChain.flowClassifiers(), org.onosproject.vtnrsc.PortChain.name(), org.onosproject.vtnrsc.PortChain.portChainId(), org.onosproject.vtnrsc.PortChain.portPairGroups(), org.onosproject.vtnrsc.PortChain.tenantId(), and org.onosproject.vtnrsc.PortChainId.toString().
void org.onosproject.vtnweb.web.PortChainCodecTest.setUp ()
Sets up for each test.
Creates a context and fetches the flow rule codec.
Definition at line 48 of file PortChainCodecTest.java.
The documentation for this class was generated from the following file:
apps/vtn/vtnweb/src/test/java/org/onosproject/vtnweb/web/PortChainCodecTest.java