onos: org.onlab.packet.IGMP Class Reference
org.onlab.packet.IGMP Class Reference
Implements IGMP control packet format.
Public Member Functions
IGMP ()
byte getIgmpType ()
Get the IGMP message type.
void setIgmpType (byte msgType)
Set the IGMP message type.
short getChecksum ()
Get the checksum of this message.
byte getMaxRespField ()
get the Max Resp Code.
void setMaxRespCode (byte respCode)
Set the Max Resp Code.
List< IGMPGroup > getGroups ()
Get the list of IGMPGroups.
boolean addGroup (IGMPGroup group)
Add a multicast group to this IGMP message.
byte[] serialize ()
Serialize this IGMP packet.
IPacket deserialize (final byte[] data, final int offset, final int length)
Deserialize an IGMP message.
boolean equals (final Object obj)
int hashCode ()
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
Static Public Member Functions
static Deserializer< IGMP > deserializer ()
Deserializer function for IPv4 packets.
Static Public Attributes
static final byte TYPE_IGMPV3_MEMBERSHIP_QUERY = 0x11
static final byte TYPE_IGMPV1_MEMBERSHIP_REPORT = 0x12
static final byte TYPE_IGMPV2_MEMBERSHIP_REPORT = 0x16
static final byte TYPE_IGMPV2_LEAVE_GROUP = 0x17
static final byte TYPE_IGMPV3_MEMBERSHIP_REPORT = 0x22
static final Map< Byte,
Deserializer<?extends IPacket > > PROTOCOL_DESERIALIZER_MAP = new HashMap<>()
static final int MINIMUM_HEADER_LEN = 12
Additional Inherited Members
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements IGMP control packet format.
Definition at line 33 of file IGMP.java.
Constructor & Destructor Documentation
org.onlab.packet.IGMP.IGMP ()
Definition at line 54 of file IGMP.java.
Referenced by org.onlab.packet.IGMP.deserialize(), org.onlab.packet.IGMP.deserializer(), and org.onlab.packet.IGMP.equals().
Member Function Documentation
boolean org.onlab.packet.IGMP.addGroup (IGMPGroup group)
Add a multicast group to this IGMP message.
Parameters
group the IGMPGroup will be IGMPQuery or IGMPMembership depending on the message type.
Returns
true if group was valid and added, false otherwise.
Definition at line 122 of file IGMP.java.
References org.onlab.packet.IGMPGroup.sources, org.onlab.packet.IGMP.TYPE_IGMPV3_MEMBERSHIP_QUERY, and org.onlab.packet.IGMP.TYPE_IGMPV3_MEMBERSHIP_REPORT.
IPacket org.onlab.packet.IGMP.deserialize (final byte[] data, final int offset, final int length)
Deserialize an IGMP message.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
populated IGMP object
Definition at line 206 of file IGMP.java.
References org.onlab.packet.IGMP.IGMP().
static Deserializer<IGMP> org.onlab.packet.IGMP.deserializer () static
Deserializer function for IPv4 packets.
Returns
deserializer function
Definition at line 228 of file IGMP.java.
References org.onlab.packet.IGMP.IGMP(), find-link-in-cluster.length, org.onlab.packet.IGMP.MINIMUM_HEADER_LEN, org.onlab.packet.IGMP.TYPE_IGMPV1_MEMBERSHIP_REPORT, org.onlab.packet.IGMP.TYPE_IGMPV2_LEAVE_GROUP, org.onlab.packet.IGMP.TYPE_IGMPV2_MEMBERSHIP_REPORT, org.onlab.packet.IGMP.TYPE_IGMPV3_MEMBERSHIP_QUERY, and org.onlab.packet.IGMP.TYPE_IGMPV3_MEMBERSHIP_REPORT.
boolean org.onlab.packet.IGMP.equals (final Object obj)
Definition at line 289 of file IGMP.java.
References org.onlab.packet.IGMP.IGMP().
short org.onlab.packet.IGMP.getChecksum ()
Get the checksum of this message.
Returns
the checksum
Definition at line 80 of file IGMP.java.
List<IGMPGroup> org.onlab.packet.IGMP.getGroups ()
Get the list of IGMPGroups.
The group objects will be either IGMPQuery or IGMPMembership depending on the IGMP message type. For IGMP Query, the groups list should only be one group.
Returns
The list of IGMP groups.
Definition at line 112 of file IGMP.java.
byte org.onlab.packet.IGMP.getIgmpType ()
Get the IGMP message type.
Returns
the IGMP message type
Definition at line 62 of file IGMP.java.
byte org.onlab.packet.IGMP.getMaxRespField ()
get the Max Resp Code.
Returns
The Maximum Time allowed before before sending a responding report.
Definition at line 89 of file IGMP.java.
int org.onlab.packet.IGMP.hashCode ()
Definition at line 325 of file IGMP.java.
byte [] org.onlab.packet.IGMP.serialize ()
Serialize this IGMP packet.
This will take care of serializing IGMPv3 Queries and IGMPv3 Membership Reports.
Returns
the serialized IGMP message
Implements org.onlab.packet.IPacket.
Definition at line 157 of file IGMP.java.
References onos.size.
void org.onlab.packet.IGMP.setIgmpType (byte msgType)
Set the IGMP message type.
Parameters
msgType IGMP message type
Definition at line 71 of file IGMP.java.
void org.onlab.packet.IGMP.setMaxRespCode (byte respCode)
Set the Max Resp Code.
Parameters
respCode the Maximum Response Code.
Definition at line 98 of file IGMP.java.
References org.onlab.packet.IGMP.TYPE_IGMPV3_MEMBERSHIP_QUERY.
Member Data Documentation
final int org.onlab.packet.IGMP.MINIMUM_HEADER_LEN = 12 static
Definition at line 43 of file IGMP.java.
Referenced by org.onlab.packet.IGMP.deserializer().
final Map<Byte, Deserializer<? extends IPacket> > org.onlab.packet.IGMP.PROTOCOL_DESERIALIZER_MAP = new HashMap<>() static
Definition at line 41 of file IGMP.java.
final byte org.onlab.packet.IGMP.TYPE_IGMPV1_MEMBERSHIP_REPORT = 0x12 static
Definition at line 37 of file IGMP.java.
Referenced by org.onlab.packet.IGMP.deserializer().
final byte org.onlab.packet.IGMP.TYPE_IGMPV2_LEAVE_GROUP = 0x17 static
Definition at line 39 of file IGMP.java.
Referenced by org.onlab.packet.IGMP.deserializer().
final byte org.onlab.packet.IGMP.TYPE_IGMPV2_MEMBERSHIP_REPORT = 0x16 static
Definition at line 38 of file IGMP.java.
Referenced by org.onlab.packet.IGMP.deserializer().
final byte org.onlab.packet.IGMP.TYPE_IGMPV3_MEMBERSHIP_QUERY = 0x11 static
Definition at line 36 of file IGMP.java.
Referenced by org.onlab.packet.IGMP.addGroup(), org.onlab.packet.IGMP.deserializer(), org.onlab.packet.IGMP.setMaxRespCode(), and org.onlab.packet.IGMPTest.setUp().
final byte org.onlab.packet.IGMP.TYPE_IGMPV3_MEMBERSHIP_REPORT = 0x22 static
Definition at line 40 of file IGMP.java.
Referenced by org.onlab.packet.IGMP.addGroup(), org.onlab.packet.IGMP.deserializer(), and org.onlab.packet.IGMPTest.setUp().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/IGMP.java