onos: org.onosproject.pcepio.types.IPv6NeighborAddressTlv Class Reference
org.onosproject.pcepio.types.IPv6NeighborAddressTlv Class Reference
Provides IPv6 Neighbor Address.
Public Member Functions
IPv6NeighborAddressTlv (byte[] rawValue)
Constructor to initialize rawValue.
byte[] getBytes ()
Returns value of IPv6 Neighbor Address.
byte[] getValue ()
Returns value of IPv6 Neighbor Address.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static IPv6NeighborAddressTlv of (final byte[] raw)
Returns newly created IPv6NeighborAddressTlv object.
static IPv6NeighborAddressTlv read20Bytes (ChannelBuffer c)
Reads the channel buffer and returns object of IPv6NeighborAddressTlv.
Static Public Attributes
static final short TYPE = 13
static final short LENGTH = 20
static final byte VALUE_LENGTH = 18
static final IPv6NeighborAddressTlv NONE = new IPv6NeighborAddressTlv(NONE_VAL)
static final IPv6NeighborAddressTlv NO_MASK = new IPv6NeighborAddressTlv(NO_MASK_VAL)
static final IPv6NeighborAddressTlv FULL_MASK = NONE
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IPv6NeighborAddressTlv.class)
Detailed Description
Provides IPv6 Neighbor Address.
Reference :[RFC6119]/4.3.
Definition at line 31 of file IPv6NeighborAddressTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IPv6NeighborAddressTlv.IPv6NeighborAddressTlv (byte[] rawValue)
Constructor to initialize rawValue.
Parameters
rawValue IPv6 Neighbor Address Tlv
Definition at line 54 of file IPv6NeighborAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6NeighborAddressTlv.equals(), and org.onosproject.pcepio.types.IPv6NeighborAddressTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.IPv6NeighborAddressTlv.equals (Object obj)
Definition at line 132 of file IPv6NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv6NeighborAddressTlv.IPv6NeighborAddressTlv().
byte [] org.onosproject.pcepio.types.IPv6NeighborAddressTlv.getBytes ()
Returns value of IPv6 Neighbor Address.
Returns
rawValue raw value
Definition at line 98 of file IPv6NeighborAddressTlv.java.
short org.onosproject.pcepio.types.IPv6NeighborAddressTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 122 of file IPv6NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv6NeighborAddressTlv.LENGTH.
short org.onosproject.pcepio.types.IPv6NeighborAddressTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 117 of file IPv6NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv6NeighborAddressTlv.TYPE.
byte [] org.onosproject.pcepio.types.IPv6NeighborAddressTlv.getValue ()
Returns value of IPv6 Neighbor Address.
Returns
rawValue raw value
Definition at line 107 of file IPv6NeighborAddressTlv.java.
PcepVersion org.onosproject.pcepio.types.IPv6NeighborAddressTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 112 of file IPv6NeighborAddressTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IPv6NeighborAddressTlv.hashCode ()
Definition at line 127 of file IPv6NeighborAddressTlv.java.
static IPv6NeighborAddressTlv org.onosproject.pcepio.types.IPv6NeighborAddressTlv.of (final byte[] raw) static
Returns newly created IPv6NeighborAddressTlv object.
Parameters
raw IPv6 Neighbor Address
Returns
object of IPv6 Neighbor Address Tlv
Definition at line 64 of file IPv6NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv6NeighborAddressTlv.IPv6NeighborAddressTlv(), org.onosproject.pcepio.types.IPv6NeighborAddressTlv.NO_MASK, and org.onosproject.pcepio.types.IPv6NeighborAddressTlv.NONE.
static IPv6NeighborAddressTlv org.onosproject.pcepio.types.IPv6NeighborAddressTlv.read20Bytes (ChannelBuffer c) static
Reads the channel buffer and returns object of IPv6NeighborAddressTlv.
Parameters
c input channel buffer
Returns
object of IPv6NeighborAddressTlv
Definition at line 158 of file IPv6NeighborAddressTlv.java.
String org.onosproject.pcepio.types.IPv6NeighborAddressTlv.toString ()
Definition at line 165 of file IPv6NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv6NeighborAddressTlv.LENGTH, and org.onosproject.pcepio.types.IPv6NeighborAddressTlv.TYPE.
int org.onosproject.pcepio.types.IPv6NeighborAddressTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 144 of file IPv6NeighborAddressTlv.java.
References org.onosproject.pcepio.types.IPv6NeighborAddressTlv.LENGTH, and org.onosproject.pcepio.types.IPv6NeighborAddressTlv.TYPE.
Member Data Documentation
final IPv6NeighborAddressTlv org.onosproject.pcepio.types.IPv6NeighborAddressTlv.FULL_MASK = NONE static
Definition at line 45 of file IPv6NeighborAddressTlv.java.
final short org.onosproject.pcepio.types.IPv6NeighborAddressTlv.LENGTH = 20 static
Definition at line 35 of file IPv6NeighborAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6NeighborAddressTlv.getLength(), org.onosproject.pcepio.types.IPv6NeighborAddressTlv.toString(), and org.onosproject.pcepio.types.IPv6NeighborAddressTlv.write().
final Logger org.onosproject.pcepio.types.IPv6NeighborAddressTlv.log = LoggerFactory.getLogger(IPv6NeighborAddressTlv.class) static protected
Definition at line 32 of file IPv6NeighborAddressTlv.java.
final IPv6NeighborAddressTlv org.onosproject.pcepio.types.IPv6NeighborAddressTlv.NO_MASK = new IPv6NeighborAddressTlv(NO_MASK_VAL) static
Definition at line 44 of file IPv6NeighborAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6NeighborAddressTlv.of().
final IPv6NeighborAddressTlv org.onosproject.pcepio.types.IPv6NeighborAddressTlv.NONE = new IPv6NeighborAddressTlv(NONE_VAL) static
Definition at line 39 of file IPv6NeighborAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6NeighborAddressTlv.of().
final short org.onosproject.pcepio.types.IPv6NeighborAddressTlv.TYPE = 13 static
Definition at line 34 of file IPv6NeighborAddressTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6NeighborAddressTlv.getType(), org.onosproject.pcepio.types.IPv6NeighborAddressTlv.toString(), and org.onosproject.pcepio.types.IPv6NeighborAddressTlv.write().
final byte org.onosproject.pcepio.types.IPv6NeighborAddressTlv.VALUE_LENGTH = 18 static
Definition at line 36 of file IPv6NeighborAddressTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkDescriptorsTlv.read().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IPv6NeighborAddressTlv.java