onos: org.onlab.packet.LLDP Class Reference
org.onlab.packet.LLDP Class Reference
Public Member Functions
LLDP ()
LLDPTLV getChassisId ()
LLDP setChassisId (final LLDPTLV chassis)
LLDPTLV getPortId ()
LLDP setPortId (final LLDPTLV portId)
LLDPTLV getTtl ()
LLDP setTtl (final LLDPTLV ttl)
List< LLDPTLV > getOptionalTLVList ()
LLDP setOptionalTLVList (final List< LLDPTLV > optionalTLVList)
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (final byte[] data, final int offset, final int length)
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
Static Public Member Functions
static Deserializer< LLDP > deserializer ()
Deserializer function for LLDP packets.
Static Public Attributes
static final byte CHASSIS_TLV_TYPE = 1
static final short CHASSIS_TLV_SIZE = 7
static final byte CHASSIS_TLV_SUBTYPE = 4
static final byte PORT_TLV_TYPE = 2
static final short PORT_TLV_SIZE = 5
static final byte PORT_TLV_SUBTYPE = 2
static final byte TTL_TLV_TYPE = 3
static final short TTL_TLV_SIZE = 2
Protected Attributes
LLDPTLV chassisId
LLDPTLV portId
LLDPTLV ttl
List< LLDPTLV > optionalTLVList
short ethType
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Definition at line 31 of file LLDP.java.
Constructor & Destructor Documentation
org.onlab.packet.LLDP.LLDP ()
Definition at line 49 of file LLDP.java.
References org.onlab.packet.Ethernet.TYPE_LLDP.
Referenced by org.onlab.packet.LLDP.deserializer(), and org.onlab.packet.LLDP.equals().
Member Function Documentation
IPacket org.onlab.packet.LLDP.deserialize (final byte[] data, final int offset, final int length)
Definition at line 149 of file LLDP.java.
References find-link-in-cluster.length.
static Deserializer<LLDP> org.onlab.packet.LLDP.deserializer () static
Deserializer function for LLDP packets.
Returns
deserializer function
Definition at line 253 of file LLDP.java.
References find-link-in-cluster.length, and org.onlab.packet.LLDP.LLDP().
boolean org.onlab.packet.LLDP.equals (final Object obj)
Definition at line 210 of file LLDP.java.
References org.onlab.packet.LLDP.chassisId, org.onlab.packet.LLDPTLV.equals(), org.onlab.packet.LLDP.LLDP(), org.onlab.packet.LLDP.optionalTLVList, org.onlab.packet.LLDP.portId, and org.onlab.packet.LLDP.ttl.
LLDPTLV org.onlab.packet.LLDP.getChassisId ()
Returns
the chassisId
Definition at line 57 of file LLDP.java.
Referenced by org.onlab.packet.LLDPTest.testDeserialize().
List<LLDPTLV> org.onlab.packet.LLDP.getOptionalTLVList ()
Returns
the optionalTLVList
Definition at line 108 of file LLDP.java.
Referenced by org.onlab.packet.ONOSLLDP.getDeviceTLV(), org.onlab.packet.ONOSLLDP.getNameTLV(), and org.onlab.packet.LLDPTest.testDeserialize().
LLDPTLV org.onlab.packet.LLDP.getPortId ()
Returns
the portId
Definition at line 74 of file LLDP.java.
Referenced by org.onlab.packet.LLDPTest.testDeserialize().
LLDPTLV org.onlab.packet.LLDP.getTtl ()
Returns
the ttl
Definition at line 91 of file LLDP.java.
Referenced by org.onlab.packet.LLDPTest.testDeserialize().
int org.onlab.packet.LLDP.hashCode ()
Definition at line 192 of file LLDP.java.
byte [] org.onlab.packet.LLDP.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 123 of file LLDP.java.
References org.onlab.packet.LLDPTLV.getLength(), find-link-in-cluster.length, org.onlab.packet.LLDP.optionalTLVList, and org.onlab.packet.LLDP.portId.
LLDP org.onlab.packet.LLDP.setChassisId (final LLDPTLV chassis)
Parameters
chassis the chassisId to set
Returns
this
Definition at line 66 of file LLDP.java.
LLDP org.onlab.packet.LLDP.setOptionalTLVList (final List< LLDPTLV > optionalTLVList)
Parameters
optionalTLVList the optionalTLVList to set
Returns
this
Definition at line 117 of file LLDP.java.
References org.onlab.packet.LLDP.optionalTLVList.
Referenced by org.onlab.packet.ONOSLLDP.ONOSLLDP().
LLDP org.onlab.packet.LLDP.setPortId (final LLDPTLV portId)
Parameters
portId the portId to set
Returns
this
Definition at line 83 of file LLDP.java.
References org.onlab.packet.LLDP.portId.
LLDP org.onlab.packet.LLDP.setTtl (final LLDPTLV ttl)
Parameters
ttl the ttl to set
Returns
this
Definition at line 100 of file LLDP.java.
References org.onlab.packet.LLDP.ttl.
Referenced by org.onlab.packet.ONOSLLDP.ONOSLLDP().
Member Data Documentation
final short org.onlab.packet.LLDP.CHASSIS_TLV_SIZE = 7 static
Definition at line 33 of file LLDP.java.
Referenced by org.onlab.packet.LLDPTest.setUp(), and org.onlab.packet.LLDPTest.testDeserialize().
final byte org.onlab.packet.LLDP.CHASSIS_TLV_SUBTYPE = 4 static
Definition at line 34 of file LLDP.java.
final byte org.onlab.packet.LLDP.CHASSIS_TLV_TYPE = 1 static
Definition at line 32 of file LLDP.java.
Referenced by org.onlab.packet.LLDPTest.setUp(), and org.onlab.packet.LLDPTest.testDeserialize().
LLDPTLV org.onlab.packet.LLDP.chassisId protected
Definition at line 43 of file LLDP.java.
Referenced by org.onlab.packet.LLDP.equals().
short org.onlab.packet.LLDP.ethType protected
Definition at line 47 of file LLDP.java.
List<LLDPTLV> org.onlab.packet.LLDP.optionalTLVList protected
Definition at line 46 of file LLDP.java.
Referenced by org.onlab.packet.LLDP.equals(), org.onlab.packet.LLDP.serialize(), and org.onlab.packet.LLDP.setOptionalTLVList().
final short org.onlab.packet.LLDP.PORT_TLV_SIZE = 5 static
Definition at line 37 of file LLDP.java.
Referenced by org.onlab.packet.LLDPTest.setUp(), and org.onlab.packet.LLDPTest.testDeserialize().
final byte org.onlab.packet.LLDP.PORT_TLV_SUBTYPE = 2 static
Definition at line 38 of file LLDP.java.
final byte org.onlab.packet.LLDP.PORT_TLV_TYPE = 2 static
Definition at line 36 of file LLDP.java.
Referenced by org.onlab.packet.LLDPTest.setUp(), and org.onlab.packet.LLDPTest.testDeserialize().
LLDPTLV org.onlab.packet.LLDP.portId protected
Definition at line 44 of file LLDP.java.
Referenced by org.onlab.packet.LLDP.equals(), org.onlab.packet.LLDP.serialize(), and org.onlab.packet.LLDP.setPortId().
LLDPTLV org.onlab.packet.LLDP.ttl protected
Definition at line 45 of file LLDP.java.
Referenced by org.onlab.packet.LLDP.equals(), and org.onlab.packet.LLDP.setTtl().
final short org.onlab.packet.LLDP.TTL_TLV_SIZE = 2 static
Definition at line 41 of file LLDP.java.
Referenced by org.onlab.packet.LLDPTest.setUp(), and org.onlab.packet.LLDPTest.testDeserialize().
final byte org.onlab.packet.LLDP.TTL_TLV_TYPE = 3 static
Definition at line 40 of file LLDP.java.
Referenced by org.onlab.packet.LLDPTest.setUp(), and org.onlab.packet.LLDPTest.testDeserialize().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/LLDP.java