onos: org.onosproject.incubator.net.tunnel.TunnelSubscription Class Reference
org.onosproject.incubator.net.tunnel.TunnelSubscription Class Reference
Represents for a order that consumer subscribe tunnel.
Public Member Functions
TunnelSubscription (ApplicationId consumerId, TunnelEndPoint src, TunnelEndPoint dst, TunnelId tunnelId, Type type, TunnelName tunnelName, Annotations...annotations)
Creates a TunnelSubscription.
ApplicationId consumerId ()
Returns consumer identity.
TunnelEndPoint src ()
Returns source point of tunnel.
TunnelEndPoint dst ()
Returns destination point of tunnel.
Type type ()
Returns tunnel type.
TunnelId tunnelId ()
Returns tunnel identity.
TunnelName tunnelName ()
Returns tunnel name.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Represents for a order that consumer subscribe tunnel.
ONOS maintains request information, it means ONOS knows how much resource echo consumer uses in the ONOS. Although there is no a tunnel that consumer want to use, when producer creates a new tunnel, ONOS will notify the consumers that want to use it.
Definition at line 38 of file TunnelSubscription.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.tunnel.TunnelSubscription.TunnelSubscription (ApplicationId consumerId, TunnelEndPoint src, TunnelEndPoint dst, TunnelId tunnelId, Type type, TunnelName tunnelName, Annotations... annotations)
Creates a TunnelSubscription.
Parameters
consumerId consumer identity
src source tunnel end point of tunnel
dst destination tunnel end point of tunnel
tunnelId tunnel identity
type tunnel type
tunnelName the name of a tunnel
annotations parameter
Definition at line 57 of file TunnelSubscription.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.incubator.net.tunnel.TunnelSubscription.consumerId(), org.onosproject.incubator.net.tunnel.TunnelSubscription.dst(), org.onosproject.incubator.net.tunnel.TunnelSubscription.src(), org.onosproject.incubator.net.tunnel.TunnelSubscription.tunnelId(), org.onosproject.incubator.net.tunnel.TunnelSubscription.tunnelName(), and org.onosproject.incubator.net.tunnel.TunnelSubscription.type().
Referenced by org.onosproject.incubator.net.tunnel.TunnelSubscription.equals().
Member Function Documentation
ApplicationId org.onosproject.incubator.net.tunnel.TunnelSubscription.consumerId ()
Returns consumer identity.
Returns
consumerId consumer id
Definition at line 75 of file TunnelSubscription.java.
Referenced by org.onosproject.incubator.net.tunnel.TunnelSubscription.hashCode(), org.onosproject.incubator.net.tunnel.TunnelSubscription.toString(), and org.onosproject.incubator.net.tunnel.TunnelSubscription.TunnelSubscription().
TunnelEndPoint org.onosproject.incubator.net.tunnel.TunnelSubscription.dst ()
Returns destination point of tunnel.
Returns
destination point
Definition at line 93 of file TunnelSubscription.java.
Referenced by org.onosproject.incubator.net.tunnel.TunnelSubscription.hashCode(), org.onosproject.incubator.net.tunnel.TunnelSubscription.toString(), and org.onosproject.incubator.net.tunnel.TunnelSubscription.TunnelSubscription().
boolean org.onosproject.incubator.net.tunnel.TunnelSubscription.equals (Object obj)
Definition at line 130 of file TunnelSubscription.java.
References org.onosproject.incubator.net.tunnel.TunnelSubscription.TunnelSubscription().
int org.onosproject.incubator.net.tunnel.TunnelSubscription.hashCode ()
Definition at line 125 of file TunnelSubscription.java.
References org.onosproject.incubator.net.tunnel.TunnelSubscription.consumerId(), org.onosproject.incubator.net.tunnel.TunnelSubscription.dst(), org.onosproject.incubator.net.tunnel.TunnelSubscription.src(), org.onosproject.incubator.net.tunnel.TunnelSubscription.tunnelId(), org.onosproject.incubator.net.tunnel.TunnelSubscription.tunnelName(), and org.onosproject.incubator.net.tunnel.TunnelSubscription.type().
TunnelEndPoint org.onosproject.incubator.net.tunnel.TunnelSubscription.src ()
Returns source point of tunnel.
Returns
source point
Definition at line 84 of file TunnelSubscription.java.
Referenced by org.onosproject.incubator.net.tunnel.TunnelSubscription.hashCode(), org.onosproject.incubator.net.tunnel.TunnelSubscription.toString(), and org.onosproject.incubator.net.tunnel.TunnelSubscription.TunnelSubscription().
String org.onosproject.incubator.net.tunnel.TunnelSubscription.toString ()
Definition at line 147 of file TunnelSubscription.java.
References org.onosproject.incubator.net.tunnel.TunnelSubscription.consumerId(), org.onosproject.incubator.net.tunnel.TunnelSubscription.dst(), org.onosproject.incubator.net.tunnel.TunnelSubscription.src(), org.onosproject.incubator.net.tunnel.TunnelSubscription.tunnelId(), org.onosproject.incubator.net.tunnel.TunnelSubscription.tunnelName(), and org.onosproject.incubator.net.tunnel.TunnelSubscription.type().
TunnelId org.onosproject.incubator.net.tunnel.TunnelSubscription.tunnelId ()
Returns tunnel identity.
Returns
tunnel id
Definition at line 111 of file TunnelSubscription.java.
Referenced by org.onosproject.incubator.net.tunnel.TunnelSubscription.hashCode(), org.onosproject.incubator.net.tunnel.TunnelSubscription.toString(), and org.onosproject.incubator.net.tunnel.TunnelSubscription.TunnelSubscription().
TunnelName org.onosproject.incubator.net.tunnel.TunnelSubscription.tunnelName ()
Returns tunnel name.
Returns
tunnel name
Definition at line 120 of file TunnelSubscription.java.
Referenced by org.onosproject.incubator.net.tunnel.TunnelSubscription.hashCode(), org.onosproject.incubator.net.tunnel.TunnelSubscription.toString(), and org.onosproject.incubator.net.tunnel.TunnelSubscription.TunnelSubscription().
Type org.onosproject.incubator.net.tunnel.TunnelSubscription.type ()
Returns tunnel type.
Returns
tunnel type
Definition at line 102 of file TunnelSubscription.java.
Referenced by org.onosproject.incubator.net.tunnel.TunnelSubscription.hashCode(), org.onosproject.incubator.net.tunnel.TunnelSubscription.toString(), and org.onosproject.incubator.net.tunnel.TunnelSubscription.TunnelSubscription().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/tunnel/TunnelSubscription.java