onos: org.onosproject.store.trivial.SimpleIntentStore Class Reference
org.onosproject.store.trivial.SimpleIntentStore Class Reference
Simple single-instance implementation of the intent store.
Public Member Functions
void activate ()
void deactivate ()
long getIntentCount ()
Returns the number of intents in the store.
Iterable< Intent > getIntents ()
Returns an iterable of all intents in the store.
Iterable< IntentData > getIntentData (boolean localOnly, long olderThan)
Returns an iterable of all intent data objects in the store.
IntentState getIntentState (Key intentKey)
Returns the state of the specified intent.
List< Intent > getInstallableIntents (Key intentKey)
Returns the list of the installable events associated with the specified original intent.
void write (IntentData newData)
Writes an IntentData object to the store.
void batchWrite (Iterable< IntentData > updates)
Writes a batch of IntentData objects to the store.
Intent getIntent (Key key)
Returns the intent with the specified identifier.
IntentData getIntentData (Key key)
Returns the intent data object associated with the specified key.
void addPending (IntentData data)
Adds a new operation, which should be persisted and delegated.
boolean isMaster (Key intentKey)
Checks to see whether the calling instance is the master for processing this intent, or more specifically, the key contained in this intent.
Iterable< Intent > getPending ()
Returns the intent requests pending processing.
Iterable< IntentData > getPendingData ()
Returns the intent data objects that are pending processing.
Iterable< IntentData > getPendingData (boolean localOnly, long olderThan)
Returns the intent data objects that are pending processing for longer than the specified duration.
Detailed Description
Simple single-instance implementation of the intent store.
Definition at line 47 of file SimpleIntentStore.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleIntentStore.activate ()
Definition at line 57 of file SimpleIntentStore.java.
void org.onosproject.store.trivial.SimpleIntentStore.addPending (IntentData intent)
Adds a new operation, which should be persisted and delegated.
Parameters
intent operation
Implements org.onosproject.net.intent.IntentStore.
Definition at line 163 of file SimpleIntentStore.java.
References org.onosproject.net.intent.IntentEvent.getEvent().
void org.onosproject.store.trivial.SimpleIntentStore.batchWrite (Iterable< IntentData > updates)
Writes a batch of IntentData objects to the store.
A batch has no semantics, this is simply a convenience API.
Parameters
updates collection of intent data objects to write
Implements org.onosproject.net.intent.IntentStore.
Definition at line 141 of file SimpleIntentStore.java.
References org.onosproject.store.trivial.SimpleIntentStore.write().
void org.onosproject.store.trivial.SimpleIntentStore.deactivate ()
Definition at line 62 of file SimpleIntentStore.java.
List<Intent> org.onosproject.store.trivial.SimpleIntentStore.getInstallableIntents (Key intentKey)
Returns the list of the installable events associated with the specified original intent.
Parameters
intentKey original intent identifier
Returns
compiled installable intents, or null if no installables exist
Implements org.onosproject.net.intent.IntentStore.
Definition at line 98 of file SimpleIntentStore.java.
Intent org.onosproject.store.trivial.SimpleIntentStore.getIntent (Key key)
Returns the intent with the specified identifier.
Parameters
key key
Returns
intent or null if not found
Implements org.onosproject.net.intent.IntentStore.
Definition at line 148 of file SimpleIntentStore.java.
long org.onosproject.store.trivial.SimpleIntentStore.getIntentCount ()
Returns the number of intents in the store.
Returns
the number of intents in the store
Implements org.onosproject.net.intent.IntentStore.
Definition at line 67 of file SimpleIntentStore.java.
Iterable<IntentData> org.onosproject.store.trivial.SimpleIntentStore.getIntentData (boolean localOnly, long olderThan)
Returns an iterable of all intent data objects in the store.
Parameters
localOnly should only intents for which this instance is master be returned
olderThan specified duration in milliseconds (0 for "now")
Returns
iterable of all intent data objects
Implements org.onosproject.net.intent.IntentStore.
Definition at line 79 of file SimpleIntentStore.java.
References org.onosproject.store.trivial.SimpleIntentStore.isMaster().
IntentData org.onosproject.store.trivial.SimpleIntentStore.getIntentData (Key key)
Returns the intent data object associated with the specified key.
Parameters
key key to look up
Returns
intent data object
Implements org.onosproject.net.intent.IntentStore.
Definition at line 154 of file SimpleIntentStore.java.
Iterable<Intent> org.onosproject.store.trivial.SimpleIntentStore.getIntents ()
Returns an iterable of all intents in the store.
Returns
iterable of all intents
Implements org.onosproject.net.intent.IntentStore.
Definition at line 72 of file SimpleIntentStore.java.
References org.onosproject.net.intent.IntentData.intent().
IntentState org.onosproject.store.trivial.SimpleIntentStore.getIntentState (Key intentKey)
Returns the state of the specified intent.
Parameters
intentKey intent identification
Returns
current intent state
Implements org.onosproject.net.intent.IntentStore.
Definition at line 92 of file SimpleIntentStore.java.
Iterable<Intent> org.onosproject.store.trivial.SimpleIntentStore.getPending ()
Returns the intent requests pending processing.
Returns
pending intents
Implements org.onosproject.net.intent.IntentStore.
Definition at line 192 of file SimpleIntentStore.java.
References org.onosproject.net.intent.IntentData.intent().
Iterable<IntentData> org.onosproject.store.trivial.SimpleIntentStore.getPendingData ()
Returns the intent data objects that are pending processing.
Returns
pending intent data objects
Implements org.onosproject.net.intent.IntentStore.
Definition at line 199 of file SimpleIntentStore.java.
Iterable<IntentData> org.onosproject.store.trivial.SimpleIntentStore.getPendingData (boolean localOnly, long olderThan)
Returns the intent data objects that are pending processing for longer than the specified duration.
Parameters
localOnly should only intents for which this instance is master be returned
olderThan specified duration in milliseconds (0 for "now")
Returns
pending intent data objects
Implements org.onosproject.net.intent.IntentStore.
Definition at line 204 of file SimpleIntentStore.java.
References org.onosproject.store.trivial.SimpleIntentStore.isMaster().
boolean org.onosproject.store.trivial.SimpleIntentStore.isMaster (Key intentKey)
Checks to see whether the calling instance is the master for processing this intent, or more specifically, the key contained in this intent.
Parameters
intentKey intentKey to check
Returns
true if master; false, otherwise
Implements org.onosproject.net.intent.IntentStore.
Definition at line 187 of file SimpleIntentStore.java.
Referenced by org.onosproject.store.trivial.SimpleIntentStore.getIntentData(), and org.onosproject.store.trivial.SimpleIntentStore.getPendingData().
void org.onosproject.store.trivial.SimpleIntentStore.write (IntentData newData)
Writes an IntentData object to the store.
Parameters
newData new intent data to write
Implements org.onosproject.net.intent.IntentStore.
Definition at line 107 of file SimpleIntentStore.java.
References org.onosproject.net.intent.IntentEvent.getEvent(), and org.onosproject.net.intent.IntentData.isUpdateAcceptable().
Referenced by org.onosproject.store.trivial.SimpleIntentStore.batchWrite().
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleIntentStore.java