onos: org.onosproject.net.link.impl.LinkManager Class Reference
org.onosproject.net.link.impl.LinkManager Class Reference
Provides basic implementation of the link SB & NB APIs.
Public Member Functions
void activate ()
void deactivate ()
int getLinkCount ()
Returns the count of all known infrastructure links.
Iterable< Link > getLinks ()
Returns a collection of all known infrastructure links.
Iterable< Link > getActiveLinks ()
Returns a collection of all active infrastructure links.
Set< Link > getDeviceLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to and from the specified device.
Set< Link > getDeviceEgressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading from the specified device.
Set< Link > getDeviceIngressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to the specified device.
Set< Link > getLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to and from the specified connection point.
Set< Link > getEgressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading from the specified connection point.
Set< Link > getIngressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to the specified connection point.
Link getLink (ConnectPoint src, ConnectPoint dst)
Returns the infrastructure links between the specified source and destination connection points.
void removeLinks (ConnectPoint connectPoint)
Removes all infrastructure links leading to and from the specified connection point.
void removeLinks (DeviceId deviceId)
Removes all infrastructure links leading to and from the specified device.
void removeLink (ConnectPoint src, ConnectPoint dst)
Removes all links between between the specified src and dst connection points.
Protected Member Functions
LinkProviderService createProviderService (LinkProvider provider)
Protected Attributes
LinkStore store
DeviceService deviceService
NetworkConfigService networkConfigService
Detailed Description
Provides basic implementation of the link SB & NB APIs.
Definition at line 69 of file LinkManager.java.
Member Function Documentation
void org.onosproject.net.link.impl.LinkManager.activate ()
Definition at line 95 of file LinkManager.java.
LinkProviderService org.onosproject.net.link.impl.LinkManager.createProviderService (LinkProvider provider) protected
Definition at line 223 of file LinkManager.java.
void org.onosproject.net.link.impl.LinkManager.deactivate ()
Definition at line 104 of file LinkManager.java.
Iterable<Link> org.onosproject.net.link.impl.LinkManager.getActiveLinks ()
Returns a collection of all active infrastructure links.
Returns
all infrastructure links
Implements org.onosproject.net.link.LinkService.
Definition at line 125 of file LinkManager.java.
References org.onosproject.net.Link.State.ACTIVE, and org.onosproject.net.link.impl.LinkManager.getLinks().
Set<Link> org.onosproject.net.link.impl.LinkManager.getDeviceEgressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading from the specified device.
Parameters
deviceId device identifier
Returns
set of device egress links
Implements org.onosproject.net.link.LinkService.
Definition at line 140 of file LinkManager.java.
References find-flow.deviceId.
Set<Link> org.onosproject.net.link.impl.LinkManager.getDeviceIngressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to the specified device.
Parameters
deviceId device identifier
Returns
set of device ingress links
Implements org.onosproject.net.link.LinkService.
Definition at line 147 of file LinkManager.java.
References find-flow.deviceId.
Set<Link> org.onosproject.net.link.impl.LinkManager.getDeviceLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to and from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implements org.onosproject.net.link.LinkService.
Definition at line 132 of file LinkManager.java.
References find-flow.deviceId, org.onosproject.net.link.LinkStore.getDeviceIngressLinks(), and org.onosproject.net.link.impl.LinkManager.store.
Referenced by org.onosproject.net.link.impl.LinkManager.removeLinks().
Set<Link> org.onosproject.net.link.impl.LinkManager.getEgressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading from the specified connection point.
Parameters
connectPoint connection point
Returns
set of device egress links
Implements org.onosproject.net.link.LinkService.
Definition at line 162 of file LinkManager.java.
Set<Link> org.onosproject.net.link.impl.LinkManager.getIngressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to the specified connection point.
Parameters
connectPoint connection point
Returns
set of device ingress links
Implements org.onosproject.net.link.LinkService.
Definition at line 169 of file LinkManager.java.
Link org.onosproject.net.link.impl.LinkManager.getLink (ConnectPoint src, ConnectPoint dst)
Returns the infrastructure links between the specified source and destination connection points.
Parameters
src source connection point
dst destination connection point
Returns
link from source to destination; null if none found
Implements org.onosproject.net.link.LinkService.
Definition at line 176 of file LinkManager.java.
int org.onosproject.net.link.impl.LinkManager.getLinkCount ()
Returns the count of all known infrastructure links.
Returns
number of infrastructure links
Implements org.onosproject.net.link.LinkService.
Definition at line 113 of file LinkManager.java.
Iterable<Link> org.onosproject.net.link.impl.LinkManager.getLinks ()
Returns a collection of all known infrastructure links.
Returns
all infrastructure links
Implements org.onosproject.net.link.LinkService.
Definition at line 119 of file LinkManager.java.
Referenced by org.onosproject.net.link.impl.LinkManager.getActiveLinks(), and org.onosproject.net.link.impl.LinkManager.removeLinks().
Set<Link> org.onosproject.net.link.impl.LinkManager.getLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to and from the specified connection point.
Parameters
connectPoint connection point
Returns
set of links
Implements org.onosproject.net.link.LinkService.
Definition at line 154 of file LinkManager.java.
References org.onosproject.net.link.LinkStore.getIngressLinks(), and org.onosproject.net.link.impl.LinkManager.store.
void org.onosproject.net.link.impl.LinkManager.removeLink (ConnectPoint src, ConnectPoint dst)
Removes all links between between the specified src and dst connection points.
Parameters
src link source
dst link destination
Implements org.onosproject.net.link.LinkAdminService.
Definition at line 200 of file LinkManager.java.
References org.onosproject.net.link.LinkStore.removeLink(), and org.onosproject.net.link.impl.LinkManager.store.
void org.onosproject.net.link.impl.LinkManager.removeLinks (ConnectPoint connectPoint)
Removes all infrastructure links leading to and from the specified connection point.
Parameters
connectPoint connection point
Implements org.onosproject.net.link.LinkAdminService.
Definition at line 184 of file LinkManager.java.
References org.onosproject.net.ConnectPoint.deviceId(), org.onosproject.net.link.impl.LinkManager.deviceService, org.onosproject.net.link.impl.LinkManager.getLinks(), org.onosproject.net.device.DeviceService.getRole(), and org.onosproject.net.MastershipRole.MASTER.
Referenced by org.onosproject.net.link.impl.LinkManager.removeLinks().
void org.onosproject.net.link.impl.LinkManager.removeLinks (DeviceId deviceId)
Removes all infrastructure links leading to and from the specified device.
Parameters
deviceId device identifier
Implements org.onosproject.net.link.LinkAdminService.
Definition at line 192 of file LinkManager.java.
References org.onosproject.net.link.impl.LinkManager.deviceService, org.onosproject.net.link.impl.LinkManager.getDeviceLinks(), org.onosproject.net.device.DeviceService.getRole(), org.onosproject.net.MastershipRole.MASTER, and org.onosproject.net.link.impl.LinkManager.removeLinks().
Member Data Documentation
DeviceService org.onosproject.net.link.impl.LinkManager.deviceService protected
Definition at line 89 of file LinkManager.java.
Referenced by org.onosproject.net.link.impl.LinkManager.removeLinks().
NetworkConfigService org.onosproject.net.link.impl.LinkManager.networkConfigService protected
Definition at line 92 of file LinkManager.java.
LinkStore org.onosproject.net.link.impl.LinkManager.store protected
Definition at line 86 of file LinkManager.java.
Referenced by org.onosproject.net.link.impl.LinkManager.getDeviceLinks(), org.onosproject.net.link.impl.LinkManager.getLinks(), and org.onosproject.net.link.impl.LinkManager.removeLink().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/link/impl/LinkManager.java