onos: org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails Class Reference
org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails Class Reference
This Class stores path Attributes, protocol ID and Identifier of LinkState NLRI.
Public Member Functions
void setPathAttribute (List< BgpValueType > pathAttributes)
Sets path attribute with specified path attribute.
List< BgpValueType > pathAttributes ()
Returns path attributes.
void setProtocolID (ProtocolType protocolID)
Sets protocolID with specified protocolID.
ProtocolType protocolID ()
Returns protocolID.
void setIdentifier (long identifier)
Sets identifier with specified identifier.
long identifier ()
Returns Identifier.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
This Class stores path Attributes, protocol ID and Identifier of LinkState NLRI.
Definition at line 30 of file PathAttrNlriDetails.java.
Member Function Documentation
boolean org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.equals (Object obj)
Definition at line 95 of file PathAttrNlriDetails.java.
References org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.identifier(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.pathAttributes(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.protocolID().
int org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.hashCode ()
Definition at line 90 of file PathAttrNlriDetails.java.
References org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.identifier(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.pathAttributes(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.protocolID().
long org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.identifier ()
Returns Identifier.
Returns
Identifier
Definition at line 85 of file PathAttrNlriDetails.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.equals(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.hashCode(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.setIdentifier(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.toString().
List<BgpValueType> org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.pathAttributes ()
Returns path attributes.
Returns
path attributes
Definition at line 49 of file PathAttrNlriDetails.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.equals(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.hashCode(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.setPathAttribute(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.toString().
ProtocolType org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.protocolID ()
Returns protocolID.
Returns
protocolID
Definition at line 67 of file PathAttrNlriDetails.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.equals(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.hashCode(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.setProtocolID(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.toString().
void org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.setIdentifier (long identifier)
Sets identifier with specified identifier.
Parameters
identifier in linkstate nlri
Definition at line 76 of file PathAttrNlriDetails.java.
References org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.identifier().
void org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.setPathAttribute (List< BgpValueType > pathAttributes)
Sets path attribute with specified path attribute.
Parameters
pathAttributes in update message
Definition at line 40 of file PathAttrNlriDetails.java.
References org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.pathAttributes().
void org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.setProtocolID (ProtocolType protocolID)
Sets protocolID with specified protocolID.
Parameters
protocolID in linkstate nlri
Definition at line 58 of file PathAttrNlriDetails.java.
References org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.protocolID().
String org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.toString ()
Definition at line 128 of file PathAttrNlriDetails.java.
References org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.identifier(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.pathAttributes(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetails.protocolID().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/protocol/linkstate/PathAttrNlriDetails.java