onos: org.onosproject.net.flow.criteria.IcmpTypeCriterion Class Reference
org.onosproject.net.flow.criteria.IcmpTypeCriterion Class Reference
Implementation of ICMP type criterion (8 bits unsigned integer).
Public Member Functions
Type type ()
Returns the type of criterion.
short icmpType ()
Gets the ICMP type to match.
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Implementation of ICMP type criterion (8 bits unsigned integer).
Definition at line 25 of file IcmpTypeCriterion.java.
Member Function Documentation
boolean org.onosproject.net.flow.criteria.IcmpTypeCriterion.equals (Object obj)
Definition at line 64 of file IcmpTypeCriterion.java.
References org.onosproject.net.flow.criteria.IcmpTypeCriterion.icmpType().
int org.onosproject.net.flow.criteria.IcmpTypeCriterion.hashCode ()
Definition at line 59 of file IcmpTypeCriterion.java.
References org.onosproject.net.flow.criteria.IcmpTypeCriterion.type().
short org.onosproject.net.flow.criteria.IcmpTypeCriterion.icmpType ()
Gets the ICMP type to match.
Returns
the ICMP type to match (8 bits unsigned integer)
Definition at line 48 of file IcmpTypeCriterion.java.
Referenced by org.onosproject.net.flow.criteria.IcmpTypeCriterion.equals(), and org.onosproject.net.flow.criteria.IcmpTypeCriterion.toString().
String org.onosproject.net.flow.criteria.IcmpTypeCriterion.toString ()
Definition at line 53 of file IcmpTypeCriterion.java.
References org.onosproject.net.flow.criteria.IcmpTypeCriterion.icmpType(), and org.onosproject.net.flow.criteria.IcmpTypeCriterion.type().
Type org.onosproject.net.flow.criteria.IcmpTypeCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 39 of file IcmpTypeCriterion.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ICMPV4_TYPE.
Referenced by org.onosproject.net.flow.criteria.IcmpTypeCriterion.hashCode(), and org.onosproject.net.flow.criteria.IcmpTypeCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/IcmpTypeCriterion.java