onos: org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V > Class Reference
org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V > Class Reference
ConsistentMap implementation that is backed by a Raft consensus based database.
Public Member Functions
String name ()
DefaultConsistentMap (DefaultAsyncConsistentMap< K, V > asyncMap)
int size ()
boolean isEmpty ()
boolean containsKey (K key)
boolean containsValue (V value)
Versioned< V > get (K key)
Versioned< V > computeIfAbsent (K key, Function<?super K,?extends V > mappingFunction)
Versioned< V > computeIfPresent (K key, BiFunction<?super K,?super V,?extends V > remappingFunction)
Versioned< V > compute (K key, BiFunction<?super K,?super V,?extends V > remappingFunction)
Versioned< V > computeIf (K key, Predicate<?super V > condition, BiFunction<?super K,?super V,?extends V > remappingFunction)
Versioned< V > put (K key, V value)
Versioned< V > putAndGet (K key, V value)
Versioned< V > remove (K key)
void clear ()
Set< K > keySet ()
Collection< Versioned< V > > values ()
Set< Entry< K, Versioned< V > > > entrySet ()
Versioned< V > putIfAbsent (K key, V value)
boolean remove (K key, V value)
boolean remove (K key, long version)
boolean replace (K key, V oldValue, V newValue)
boolean replace (K key, long oldVersion, V newValue)
void addListener (MapEventListener< K, V > listener)
void removeListener (MapEventListener< K, V > listener)
Map< K, V > asJavaMap ()
Detailed Description
ConsistentMap implementation that is backed by a Raft consensus based database.
Parameters
<K> type of key.
<V> type of value.
Definition at line 43 of file DefaultConsistentMap.java.
Constructor & Destructor Documentation
org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.DefaultConsistentMap (DefaultAsyncConsistentMap< K, V > asyncMap)
Definition at line 54 of file DefaultConsistentMap.java.
Member Function Documentation
void org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.addListener (MapEventListener< K, V > listener)
Definition at line 186 of file DefaultConsistentMap.java.
Map<K, V> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.asJavaMap ()
Definition at line 196 of file DefaultConsistentMap.java.
void org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.clear ()
Definition at line 124 of file DefaultConsistentMap.java.
Versioned<V> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.compute (K key, BiFunction<?super K,?super V,?extends V > remappingFunction)
Definition at line 96 of file DefaultConsistentMap.java.
Versioned<V> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.computeIf (K key, Predicate<?super V > condition, BiFunction<?super K,?super V,?extends V > remappingFunction)
Definition at line 102 of file DefaultConsistentMap.java.
Versioned<V> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.computeIfAbsent (K key, Function<?super K,?extends V > mappingFunction)
Definition at line 84 of file DefaultConsistentMap.java.
Versioned<V> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.computeIfPresent (K key, BiFunction<?super K,?super V,?extends V > remappingFunction)
Definition at line 90 of file DefaultConsistentMap.java.
boolean org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.containsKey (K key)
Definition at line 69 of file DefaultConsistentMap.java.
boolean org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.containsValue (V value)
Definition at line 74 of file DefaultConsistentMap.java.
Set<Entry<K, Versioned<V> > > org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.entrySet ()
Definition at line 139 of file DefaultConsistentMap.java.
Versioned<V> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.get (K key)
Definition at line 79 of file DefaultConsistentMap.java.
boolean org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.isEmpty ()
Definition at line 64 of file DefaultConsistentMap.java.
Set<K> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.keySet ()
Definition at line 129 of file DefaultConsistentMap.java.
String org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.name ()
Definition at line 50 of file DefaultConsistentMap.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
Versioned<V> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.put (K key, V value)
Definition at line 109 of file DefaultConsistentMap.java.
Versioned<V> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.putAndGet (K key, V value)
Definition at line 114 of file DefaultConsistentMap.java.
Versioned<V> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.putIfAbsent (K key, V value)
Definition at line 144 of file DefaultConsistentMap.java.
Versioned<V> org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.remove (K key)
Definition at line 119 of file DefaultConsistentMap.java.
boolean org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.remove (K key, V value)
Definition at line 149 of file DefaultConsistentMap.java.
boolean org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.remove (K key, long version)
Definition at line 154 of file DefaultConsistentMap.java.
void org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.removeListener (MapEventListener< K, V > listener)
Definition at line 191 of file DefaultConsistentMap.java.
boolean org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.replace (K key, V oldValue, V newValue)
Definition at line 159 of file DefaultConsistentMap.java.
boolean org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.replace (K key, long oldVersion, V newValue)
Definition at line 164 of file DefaultConsistentMap.java.
int org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.size ()
Definition at line 59 of file DefaultConsistentMap.java.
Collection<Versioned<V> > org.onosproject.store.consistent.impl.DefaultConsistentMap< K, V >.values ()
Definition at line 134 of file DefaultConsistentMap.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DefaultConsistentMap.java