onos: org.onosproject.bgpio.types.attr.BgpAttrNodeName Class Reference
org.onosproject.bgpio.types.attr.BgpAttrNodeName Class Reference
Implements BGP attribute node name.
Public Member Functions
BgpAttrNodeName (byte[] nodeName)
Constructor to initialize value.
byte[] attrNodeName ()
Returns LS attribute node name.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpAttrNodeName of (final byte[] nodeName)
Returns object of this class with specified values.
static BgpAttrNodeName read (ChannelBuffer cb) throws BgpParseException
Reads the LS attribute node name.
Static Public Attributes
static final int ATTRNODE_NAME = 1026
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP attribute node name.
Definition at line 33 of file BgpAttrNodeName.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpAttrNodeName.BgpAttrNodeName (byte[] nodeName)
Constructor to initialize value.
Parameters
nodeName node name
Definition at line 48 of file BgpAttrNodeName.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.bgpio.types.attr.BgpAttrNodeName.equals(), and org.onosproject.bgpio.types.attr.BgpAttrNodeName.of().
Member Function Documentation
byte [] org.onosproject.bgpio.types.attr.BgpAttrNodeName.attrNodeName ()
Returns LS attribute node name.
Returns
node name
Definition at line 91 of file BgpAttrNodeName.java.
int org.onosproject.bgpio.types.attr.BgpAttrNodeName.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 131 of file BgpAttrNodeName.java.
boolean org.onosproject.bgpio.types.attr.BgpAttrNodeName.equals (Object obj)
Definition at line 106 of file BgpAttrNodeName.java.
References org.onosproject.bgpio.types.attr.BgpAttrNodeName.BgpAttrNodeName().
short org.onosproject.bgpio.types.attr.BgpAttrNodeName.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 96 of file BgpAttrNodeName.java.
References org.onosproject.bgpio.types.attr.BgpAttrNodeName.ATTRNODE_NAME.
int org.onosproject.bgpio.types.attr.BgpAttrNodeName.hashCode ()
Definition at line 101 of file BgpAttrNodeName.java.
static BgpAttrNodeName org.onosproject.bgpio.types.attr.BgpAttrNodeName.of (final byte[] nodeName) static
Returns object of this class with specified values.
Parameters
nodeName node name
Returns
object of BgpAttrNodeName
Definition at line 58 of file BgpAttrNodeName.java.
References org.onosproject.bgpio.types.attr.BgpAttrNodeName.BgpAttrNodeName().
static BgpAttrNodeName org.onosproject.bgpio.types.attr.BgpAttrNodeName.read (ChannelBuffer cb) throws BgpParseException static
Reads the LS attribute node name.
Parameters
cb ChannelBuffer
Returns
object of BgpAttrNodeName
Exceptions
BgpParseException while parsing BgpAttrNodeName
Definition at line 69 of file BgpAttrNodeName.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpAttrNodeName.toString ()
Definition at line 125 of file BgpAttrNodeName.java.
int org.onosproject.bgpio.types.attr.BgpAttrNodeName.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 119 of file BgpAttrNodeName.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpAttrNodeName.ATTRNODE_NAME = 1026 static
Definition at line 38 of file BgpAttrNodeName.java.
Referenced by org.onosproject.bgpio.types.attr.BgpAttrNodeName.getType().
final Logger org.onosproject.bgpio.types.attr.BgpAttrNodeName.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpAttrNodeName.class)
Definition at line 35 of file BgpAttrNodeName.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpAttrNodeName.java