onos: org.onosproject.net.flow.criteria.OduSignalIdCriterion Class Reference
org.onosproject.net.flow.criteria.OduSignalIdCriterion Class Reference
Implementation of ODU (Optical channel Data Unit) signal ID signal criterion.
Public Member Functions
Type type ()
Returns the type of criterion.
OduSignalId oduSignalId ()
Returns the ODU Signal to match.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Implementation of ODU (Optical channel Data Unit) signal ID signal criterion.
This criterion is based on the specification of "OFPXMT_EXP_ODU_SIGID" in Open Networking Foundation "Optical Transport Protocol Extension Version 1.0", but defined in protocol agnostic way.
Definition at line 31 of file OduSignalIdCriterion.java.
Member Function Documentation
boolean org.onosproject.net.flow.criteria.OduSignalIdCriterion.equals (Object obj)
Definition at line 64 of file OduSignalIdCriterion.java.
int org.onosproject.net.flow.criteria.OduSignalIdCriterion.hashCode ()
Definition at line 59 of file OduSignalIdCriterion.java.
References org.onosproject.net.flow.criteria.OduSignalIdCriterion.oduSignalId(), and org.onosproject.net.flow.criteria.OduSignalIdCriterion.type().
OduSignalId org.onosproject.net.flow.criteria.OduSignalIdCriterion.oduSignalId ()
Returns the ODU Signal to match.
Returns
the ODU signal to match
Definition at line 54 of file OduSignalIdCriterion.java.
Referenced by org.onosproject.net.flow.criteria.OduSignalIdCriterion.hashCode(), and org.onosproject.net.flow.criteria.OduSignalIdCriterion.toString().
String org.onosproject.net.flow.criteria.OduSignalIdCriterion.toString ()
Definition at line 76 of file OduSignalIdCriterion.java.
References org.onosproject.net.flow.criteria.OduSignalIdCriterion.oduSignalId(), and org.onosproject.net.flow.criteria.OduSignalIdCriterion.type().
Type org.onosproject.net.flow.criteria.OduSignalIdCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 45 of file OduSignalIdCriterion.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ODU_SIGID.
Referenced by org.onosproject.net.flow.criteria.OduSignalIdCriterion.hashCode(), and org.onosproject.net.flow.criteria.OduSignalIdCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/OduSignalIdCriterion.java