onos: org.onosproject.net.driver.DefaultDriverData Class Reference
org.onosproject.net.driver.DefaultDriverData Class Reference
Default implementation of driver data descriptor.
Public Member Functions
DefaultDriverData (Driver driver, DeviceId deviceId)
Creates new driver data.
Driver driver ()
Returns the parent device driver.
DeviceId deviceId ()
Returns the device identifier.
MutableAnnotations set (String key, String value)
Returns the value of the specified annotation.
MutableAnnotations clear (String...keys)
Clears the specified keys or the all keys if none were specified.
Set< String > keys ()
Returns the set of keys for available annotations.
String value (String key)
Returns the value of the specified annotation.
String toString ()
Detailed Description
Default implementation of driver data descriptor.
Definition at line 31 of file DefaultDriverData.java.
Constructor & Destructor Documentation
org.onosproject.net.driver.DefaultDriverData.DefaultDriverData (Driver driver, DeviceId deviceId)
Creates new driver data.
Parameters
driver parent driver type
deviceId device identifier
Definition at line 43 of file DefaultDriverData.java.
References org.onosproject.net.driver.DefaultDriverData.deviceId(), and org.onosproject.net.driver.DefaultDriverData.driver().
Member Function Documentation
MutableAnnotations org.onosproject.net.driver.DefaultDriverData.clear (String... keys)
Clears the specified keys or the all keys if none were specified.
Parameters
keys keys to be cleared
Returns
self
Implements org.onosproject.net.MutableAnnotations.
Definition at line 71 of file DefaultDriverData.java.
References org.onosproject.net.driver.DefaultDriverData.keys().
DeviceId org.onosproject.net.driver.DefaultDriverData.deviceId ()
Returns the device identifier.
Returns
device identifier
Implements org.onosproject.net.driver.DriverData.
Definition at line 55 of file DefaultDriverData.java.
Referenced by org.onosproject.net.driver.DefaultDriverData.DefaultDriverData().
Driver org.onosproject.net.driver.DefaultDriverData.driver ()
Returns the parent device driver.
Returns
device driver
Implements org.onosproject.net.driver.DriverData.
Definition at line 50 of file DefaultDriverData.java.
Referenced by org.onosproject.net.driver.DefaultDriverData.DefaultDriverData(), and org.onosproject.net.driver.DefaultDriverData.toString().
Set<String> org.onosproject.net.driver.DefaultDriverData.keys ()
Returns the set of keys for available annotations.
Returns
annotation keys
Implements org.onosproject.net.Annotations.
Definition at line 83 of file DefaultDriverData.java.
Referenced by org.onosproject.net.driver.DefaultDriverData.clear(), org.onosproject.net.driver.DefaultDriverDataTest.clearAllAnnotations(), and org.onosproject.net.driver.DefaultDriverDataTest.setAndClearAnnotations().
MutableAnnotations org.onosproject.net.driver.DefaultDriverData.set (String key, String value)
Returns the value of the specified annotation.
Parameters
key annotation key
value annotation value
Returns
self
Implements org.onosproject.net.MutableAnnotations.
Definition at line 65 of file DefaultDriverData.java.
References org.onosproject.net.driver.DefaultDriverData.value().
String org.onosproject.net.driver.DefaultDriverData.toString ()
Definition at line 93 of file DefaultDriverData.java.
References org.onosproject.net.driver.DefaultDriverData.driver().
Referenced by org.onosproject.net.driver.DefaultDriverDataTest.basics().
String org.onosproject.net.driver.DefaultDriverData.value (String key)
Returns the value of the specified annotation.
Parameters
key annotation key
Returns
annotation value
Implements org.onosproject.net.Annotations.
Definition at line 88 of file DefaultDriverData.java.
Referenced by org.onosproject.net.driver.DefaultDriverDataTest.clearAllAnnotations(), org.onosproject.net.driver.DefaultDriverData.set(), and org.onosproject.net.driver.DefaultDriverDataTest.setAndClearAnnotations().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/driver/DefaultDriverData.java