onos: org.onosproject.net.intent.constraint.LatencyConstraint Class Reference
org.onosproject.net.intent.constraint.LatencyConstraint Class Reference
Constraint that evaluates the latency through a path.
Public Member Functions
LatencyConstraint (Duration latency)
Creates a new constraint to keep under specified latency through a path.
Duration latency ()
double cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
boolean validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Constraint that evaluates the latency through a path.
Definition at line 36 of file LatencyConstraint.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.constraint.LatencyConstraint.LatencyConstraint (Duration latency)
Creates a new constraint to keep under specified latency through a path.
Parameters
latency latency to be kept
Definition at line 44 of file LatencyConstraint.java.
References org.onosproject.net.intent.constraint.LatencyConstraint.latency().
Member Function Documentation
double org.onosproject.net.intent.constraint.LatencyConstraint.cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
Implements org.onosproject.net.intent.Constraint.
Definition at line 58 of file LatencyConstraint.java.
Referenced by org.onosproject.net.intent.constraint.LatencyConstraintTest.testCost(), and org.onosproject.net.intent.constraint.LatencyConstraint.validate().
boolean org.onosproject.net.intent.constraint.LatencyConstraint.equals (Object obj)
Definition at line 74 of file LatencyConstraint.java.
int org.onosproject.net.intent.constraint.LatencyConstraint.hashCode ()
Definition at line 69 of file LatencyConstraint.java.
Duration org.onosproject.net.intent.constraint.LatencyConstraint.latency ()
Definition at line 53 of file LatencyConstraint.java.
Referenced by org.onosproject.net.intent.constraint.LatencyConstraint.LatencyConstraint(), org.onosproject.net.intent.constraint.LatencyConstraint.toString(), and org.onosproject.net.intent.constraint.LatencyConstraint.validate().
String org.onosproject.net.intent.constraint.LatencyConstraint.toString ()
Definition at line 88 of file LatencyConstraint.java.
References org.onosproject.net.intent.constraint.LatencyConstraint.latency().
boolean org.onosproject.net.intent.constraint.LatencyConstraint.validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
Parameters
path path to be validated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
Implements org.onosproject.net.intent.Constraint.
Definition at line 63 of file LatencyConstraint.java.
References org.onosproject.net.intent.constraint.LatencyConstraint.cost(), and org.onosproject.net.intent.constraint.LatencyConstraint.latency().
Referenced by org.onosproject.net.intent.constraint.LatencyConstraintTest.testLessThanLatency(), and org.onosproject.net.intent.constraint.LatencyConstraintTest.testMoreThanLatency().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/constraint/LatencyConstraint.java