onos: org.onosproject.ovsdb.rfc.tableservice.ColumnDescription Class Reference
org.onosproject.ovsdb.rfc.tableservice.ColumnDescription Class Reference
Column description.
Public Member Functions
ColumnDescription (String name, String method)
Constructs a MonitorRequest object.
ColumnDescription (String name, String method, VersionNum fromVersion)
Constructs a MonitorRequest object.
ColumnDescription (String name, String method, VersionNum fromVersion, VersionNum untilVersion)
Constructs a MonitorRequest object.
String name ()
Returns the column name.
String method ()
Returns the method name.
String fromVersion ()
Returns the initial version.
String untilVersion ()
Returns the end of the version.
Detailed Description
Column description.
Definition at line 26 of file ColumnDescription.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.ColumnDescription (String name, String method)
Constructs a MonitorRequest object.
Parameters
name column name
method method name
Definition at line 42 of file ColumnDescription.java.
References org.onosproject.ovsdb.rfc.utils.VersionUtil.DEFAULT_VERSION_STRING, org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.method(), and org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.name().
org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.ColumnDescription (String name, String method, VersionNum fromVersion)
Constructs a MonitorRequest object.
Parameters
name column name
method method name
fromVersion the initial version
Definition at line 57 of file ColumnDescription.java.
References org.onosproject.ovsdb.rfc.utils.VersionUtil.DEFAULT_VERSION_STRING, org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.method(), and org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.name().
org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.ColumnDescription (String name, String method, VersionNum fromVersion, VersionNum untilVersion)
Constructs a MonitorRequest object.
Parameters
name column name
method method name
fromVersion the initial version
untilVersion the end of the version
Definition at line 74 of file ColumnDescription.java.
References org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.method(), and org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.name().
Member Function Documentation
String org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.fromVersion ()
Returns the initial version.
Returns
the initial version
Definition at line 106 of file ColumnDescription.java.
String org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.method ()
Returns the method name.
Returns
the method name
Definition at line 98 of file ColumnDescription.java.
Referenced by org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.ColumnDescription().
String org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.name ()
Returns the column name.
Returns
the column name
Definition at line 90 of file ColumnDescription.java.
Referenced by org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.ColumnDescription(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.ovsdb.rfc.tableservice.ColumnDescription.untilVersion ()
Returns the end of the version.
Returns
the end of the version
Definition at line 114 of file ColumnDescription.java.
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/tableservice/ColumnDescription.java