onos: org.onosproject.net.host.impl.HostManagerTest Class Reference
org.onosproject.net.host.impl.HostManagerTest Class Reference
Test codifying the host service & host provider service contracts.
Public Member Functions
void setUp ()
void tearDown ()
void hostDetected ()
void hostDetectedIPv6 ()
void hostVanished ()
void hostVanishedIPv6 ()
void getHosts ()
void getHostsIPv6 ()
Protected Attributes
TestListener listener = new TestListener()
HostProviderRegistry registry
TestHostProvider provider
HostProviderService providerService
Detailed Description
Test codifying the host service & host provider service contracts.
Definition at line 63 of file HostManagerTest.java.
Member Function Documentation
void org.onosproject.net.host.impl.HostManagerTest.getHosts ()
Definition at line 216 of file HostManagerTest.java.
References org.onosproject.net.host.impl.HostManager.getConnectedHosts(), org.onosproject.net.host.impl.HostManager.getHosts(), org.onosproject.net.host.impl.HostManager.getHostsByIp(), org.onosproject.net.host.impl.HostManager.getHostsByMac(), and org.onosproject.net.host.impl.HostManager.getHostsByVlan().
void org.onosproject.net.host.impl.HostManagerTest.getHostsIPv6 ()
Definition at line 229 of file HostManagerTest.java.
References org.onosproject.net.host.impl.HostManager.getConnectedHosts(), org.onosproject.net.host.impl.HostManager.getHosts(), org.onosproject.net.host.impl.HostManager.getHostsByIp(), org.onosproject.net.host.impl.HostManager.getHostsByMac(), and org.onosproject.net.host.impl.HostManager.getHostsByVlan().
void org.onosproject.net.host.impl.HostManagerTest.hostDetected ()
Definition at line 145 of file HostManagerTest.java.
References org.onosproject.net.host.impl.HostManager.getHost(), and org.onosproject.net.host.impl.HostManager.getHostCount().
void org.onosproject.net.host.impl.HostManagerTest.hostDetectedIPv6 ()
Definition at line 167 of file HostManagerTest.java.
References org.onosproject.net.host.impl.HostManager.getHost(), and org.onosproject.net.host.impl.HostManager.getHostCount().
void org.onosproject.net.host.impl.HostManagerTest.hostVanished ()
Definition at line 189 of file HostManagerTest.java.
References org.onosproject.net.host.impl.HostManager.getHost().
void org.onosproject.net.host.impl.HostManagerTest.hostVanishedIPv6 ()
Definition at line 198 of file HostManagerTest.java.
References org.onosproject.net.host.impl.HostManager.getHost().
void org.onosproject.net.host.impl.HostManagerTest.setUp ()
Definition at line 98 of file HostManagerTest.java.
References org.onosproject.net.host.impl.HostManagerTest.listener, org.onosproject.net.host.impl.HostManagerTest.provider, org.onosproject.net.host.impl.HostManagerTest.providerService, and org.onosproject.net.host.impl.HostManagerTest.registry.
void org.onosproject.net.host.impl.HostManagerTest.tearDown ()
Definition at line 115 of file HostManagerTest.java.
References org.onosproject.net.host.impl.HostManagerTest.listener, org.onosproject.net.host.impl.HostManagerTest.provider, and org.onosproject.net.host.impl.HostManagerTest.registry.
Member Data Documentation
TestListener org.onosproject.net.host.impl.HostManagerTest.listener = new TestListener() protected
Definition at line 92 of file HostManagerTest.java.
Referenced by org.onosproject.net.host.impl.HostManagerTest.setUp(), and org.onosproject.net.host.impl.HostManagerTest.tearDown().
TestHostProvider org.onosproject.net.host.impl.HostManagerTest.provider protected
Definition at line 94 of file HostManagerTest.java.
Referenced by org.onosproject.net.host.impl.HostManagerTest.setUp(), and org.onosproject.net.host.impl.HostManagerTest.tearDown().
HostProviderService org.onosproject.net.host.impl.HostManagerTest.providerService protected
Definition at line 95 of file HostManagerTest.java.
Referenced by org.onosproject.net.host.impl.HostManagerTest.setUp().
HostProviderRegistry org.onosproject.net.host.impl.HostManagerTest.registry protected
Definition at line 93 of file HostManagerTest.java.
Referenced by org.onosproject.net.host.impl.HostManagerTest.setUp(), and org.onosproject.net.host.impl.HostManagerTest.tearDown().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/host/impl/HostManagerTest.java