onos: org.onosproject.cluster.impl.MastershipManagerTest Class Reference
org.onosproject.cluster.impl.MastershipManagerTest Class Reference
Test codifying the mastership service contracts.
Public Member Functions
void setUp ()
void tearDown ()
void setRole ()
void relinquishMastership ()
void requestRoleFor ()
void getMasterFor ()
void getDevicesOf ()
void termService ()
Protected Attributes
MastershipService service
Detailed Description
Test codifying the mastership service contracts.
Definition at line 49 of file MastershipManagerTest.java.
Member Function Documentation
void org.onosproject.cluster.impl.MastershipManagerTest.getDevicesOf ()
Definition at line 134 of file MastershipManagerTest.java.
References org.onosproject.cluster.impl.MastershipManager.getDevicesOf().
void org.onosproject.cluster.impl.MastershipManagerTest.getMasterFor ()
Definition at line 122 of file MastershipManagerTest.java.
References org.onosproject.cluster.impl.MastershipManager.getMasterFor().
void org.onosproject.cluster.impl.MastershipManagerTest.relinquishMastership ()
Definition at line 90 of file MastershipManagerTest.java.
References org.onosproject.cluster.impl.MastershipManager.getLocalRole(), and org.onosproject.cluster.impl.MastershipManager.getMasterFor().
void org.onosproject.cluster.impl.MastershipManagerTest.requestRoleFor ()
Definition at line 112 of file MastershipManagerTest.java.
References org.onosproject.cluster.impl.MastershipManager.requestRoleFor().
void org.onosproject.cluster.impl.MastershipManagerTest.setRole ()
Definition at line 79 of file MastershipManagerTest.java.
References org.onosproject.cluster.impl.MastershipManager.getLocalRole(), and org.onosproject.cluster.impl.MastershipManager.requestRoleFor().
void org.onosproject.cluster.impl.MastershipManagerTest.setUp ()
Definition at line 61 of file MastershipManagerTest.java.
References org.onosproject.cluster.impl.MastershipManager.clusterService, and org.onosproject.cluster.impl.MastershipManagerTest.service.
void org.onosproject.cluster.impl.MastershipManagerTest.tearDown ()
Definition at line 71 of file MastershipManagerTest.java.
void org.onosproject.cluster.impl.MastershipManagerTest.termService ()
Definition at line 144 of file MastershipManagerTest.java.
References org.onosproject.mastership.MastershipTermService.getMastershipTerm().
Member Data Documentation
MastershipService org.onosproject.cluster.impl.MastershipManagerTest.service protected
Definition at line 58 of file MastershipManagerTest.java.
Referenced by org.onosproject.cluster.impl.MastershipManagerTest.setUp().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/cluster/impl/MastershipManagerTest.java