onos: org.onosproject.net.resource.link.BandwidthResourceAllocation Class Reference
org.onosproject.net.resource.link.BandwidthResourceAllocation Class Reference
Representation of allocated bandwidth resource.
Public Member Functions
BandwidthResourceAllocation (BandwidthResource bandwidth)
Creates a new BandwidthResourceRequest with BandwidthResource object.
BandwidthResource bandwidth ()
Returns the bandwidth resource.
ResourceType type ()
Returns the resource type.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Representation of allocated bandwidth resource.
Deprecated:
in Emu Release
Definition at line 30 of file BandwidthResourceAllocation.java.
Constructor & Destructor Documentation
org.onosproject.net.resource.link.BandwidthResourceAllocation.BandwidthResourceAllocation (BandwidthResource bandwidth)
Creates a new BandwidthResourceRequest with BandwidthResource object.
Parameters
bandwidth BandwidthResource object to be requested
Definition at line 39 of file BandwidthResourceAllocation.java.
References org.onosproject.net.resource.link.BandwidthResourceAllocation.bandwidth().
Referenced by org.onosproject.net.resource.link.BandwidthResourceAllocation.equals().
Member Function Documentation
BandwidthResource org.onosproject.net.resource.link.BandwidthResourceAllocation.bandwidth ()
Returns the bandwidth resource.
Returns
the bandwidth resource
Definition at line 48 of file BandwidthResourceAllocation.java.
Referenced by org.onosproject.net.resource.link.BandwidthResourceAllocation.BandwidthResourceAllocation(), and org.onosproject.net.resource.link.BandwidthResourceAllocation.toString().
boolean org.onosproject.net.resource.link.BandwidthResourceAllocation.equals (Object obj)
Definition at line 63 of file BandwidthResourceAllocation.java.
References org.onosproject.net.resource.link.BandwidthResourceAllocation.BandwidthResourceAllocation().
int org.onosproject.net.resource.link.BandwidthResourceAllocation.hashCode ()
Definition at line 58 of file BandwidthResourceAllocation.java.
String org.onosproject.net.resource.link.BandwidthResourceAllocation.toString ()
Definition at line 75 of file BandwidthResourceAllocation.java.
References org.onosproject.net.resource.link.BandwidthResourceAllocation.bandwidth().
ResourceType org.onosproject.net.resource.link.BandwidthResourceAllocation.type ()
Returns the resource type.
Returns
the resource type
Implements org.onosproject.net.resource.ResourceAllocation.
Definition at line 53 of file BandwidthResourceAllocation.java.
References org.onosproject.net.resource.ResourceType.BANDWIDTH.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/resource/link/BandwidthResourceAllocation.java