onos: org.onosproject.net.flow.criteria.ArpOpCriterion Class Reference
org.onosproject.net.flow.criteria.ArpOpCriterion Class Reference
Implementation of arp operation type criterion.
Public Member Functions
Type type ()
Returns the type of criterion.
int arpOp ()
Gets the arp operation type to match.
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Implementation of arp operation type criterion.
Definition at line 25 of file ArpOpCriterion.java.
Member Function Documentation
int org.onosproject.net.flow.criteria.ArpOpCriterion.arpOp ()
Gets the arp operation type to match.
Returns
the arp operation type to match
Definition at line 51 of file ArpOpCriterion.java.
Referenced by org.onosproject.net.flow.criteria.ArpOpCriterion.equals(), and org.onosproject.net.flow.criteria.ArpOpCriterion.toString().
boolean org.onosproject.net.flow.criteria.ArpOpCriterion.equals (Object obj)
Definition at line 67 of file ArpOpCriterion.java.
References org.onosproject.net.flow.criteria.ArpOpCriterion.arpOp().
int org.onosproject.net.flow.criteria.ArpOpCriterion.hashCode ()
Definition at line 62 of file ArpOpCriterion.java.
References org.onosproject.net.flow.criteria.ArpOpCriterion.type().
String org.onosproject.net.flow.criteria.ArpOpCriterion.toString ()
Definition at line 56 of file ArpOpCriterion.java.
References org.onosproject.net.flow.criteria.ArpOpCriterion.arpOp(), and org.onosproject.net.flow.criteria.ArpOpCriterion.type().
Type org.onosproject.net.flow.criteria.ArpOpCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 42 of file ArpOpCriterion.java.
Referenced by org.onosproject.net.flow.criteria.ArpOpCriterion.hashCode(), and org.onosproject.net.flow.criteria.ArpOpCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/ArpOpCriterion.java