onos: org.onosproject.net.TributarySlot Class Reference
org.onosproject.net.TributarySlot Class Reference
Implementation of ODU Tributary Slot simply designated by an index number of slot.
Public Member Functions
TributarySlot (long index)
Creates an instance representing the TributarySlot specified by the given index number.
long index ()
Returns the index number of TributarySlot.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static TributarySlot of (long index)
Detailed Description
Implementation of ODU Tributary Slot simply designated by an index number of slot.
Definition at line 23 of file TributarySlot.java.
Constructor & Destructor Documentation
org.onosproject.net.TributarySlot.TributarySlot (long index)
Creates an instance representing the TributarySlot specified by the given index number.
Parameters
index index number of wavelength
Definition at line 32 of file TributarySlot.java.
References org.onosproject.net.TributarySlot.index().
Referenced by org.onosproject.net.TributarySlot.equals(), and org.onosproject.net.TributarySlot.of().
Member Function Documentation
boolean org.onosproject.net.TributarySlot.equals (Object obj)
Definition at line 55 of file TributarySlot.java.
References org.onosproject.net.TributarySlot.TributarySlot().
int org.onosproject.net.TributarySlot.hashCode ()
Definition at line 50 of file TributarySlot.java.
References org.onosproject.net.TributarySlot.index().
long org.onosproject.net.TributarySlot.index ()
Returns the index number of TributarySlot.
Returns
the index number of TributarySlot
Definition at line 45 of file TributarySlot.java.
Referenced by org.onosproject.net.TributarySlot.hashCode(), org.onosproject.net.TributarySlot.toString(), and org.onosproject.net.TributarySlot.TributarySlot().
static TributarySlot org.onosproject.net.TributarySlot.of (long index) static
Definition at line 36 of file TributarySlot.java.
References org.onosproject.net.TributarySlot.TributarySlot().
String org.onosproject.net.TributarySlot.toString ()
Definition at line 68 of file TributarySlot.java.
References org.onosproject.net.TributarySlot.index().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/TributarySlot.java