onos: org.onosproject.pcepio.types.PcepNaiIpv6NodeId Class Reference
org.onosproject.pcepio.types.PcepNaiIpv6NodeId Class Reference
Provides Pcep Nai Ipv6 Node Id.
Public Member Functions
PcepNaiIpv6NodeId (byte[] value)
Constructor to initialize ipv6NodeId.
byte getType ()
To get the ST type of the NAI information.
int write (ChannelBuffer cb)
To write the object information to channelBuffer.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static PcepNaiIpv6NodeId of (byte[] ipv6NodeId)
Return object of Pcep Nai Ipv6 Node ID.
static PcepNaiIpv6NodeId read (ChannelBuffer cb)
Reads from the channel buffer and returns object of PcepNAIIpv6NodeId.
Static Public Attributes
static final byte ST_TYPE = 0x02
static final byte IPV6_LEN = 0x10
Detailed Description
Provides Pcep Nai Ipv6 Node Id.
Definition at line 29 of file PcepNaiIpv6NodeId.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PcepNaiIpv6NodeId.PcepNaiIpv6NodeId (byte[] value)
Constructor to initialize ipv6NodeId.
Parameters
value ipv6 node id
Definition at line 41 of file PcepNaiIpv6NodeId.java.
Referenced by org.onosproject.pcepio.types.PcepNaiIpv6NodeId.equals(), org.onosproject.pcepio.types.PcepNaiIpv6NodeId.of(), and org.onosproject.pcepio.types.PcepNaiIpv6NodeId.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.PcepNaiIpv6NodeId.equals (Object obj)
Definition at line 85 of file PcepNaiIpv6NodeId.java.
References org.onosproject.pcepio.types.PcepNaiIpv6NodeId.PcepNaiIpv6NodeId().
byte org.onosproject.pcepio.types.PcepNaiIpv6NodeId.getType ()
To get the ST type of the NAI information.
Returns
type of ST info
Implements org.onosproject.pcepio.protocol.PcepNai.
Definition at line 56 of file PcepNaiIpv6NodeId.java.
References org.onosproject.pcepio.types.PcepNaiIpv6NodeId.ST_TYPE.
int org.onosproject.pcepio.types.PcepNaiIpv6NodeId.hashCode ()
Definition at line 80 of file PcepNaiIpv6NodeId.java.
static PcepNaiIpv6NodeId org.onosproject.pcepio.types.PcepNaiIpv6NodeId.of (byte[] ipv6NodeId) static
Return object of Pcep Nai Ipv6 Node ID.
Parameters
ipv6NodeId Ipv6 node ID.
Returns
object of Pcep Nai Ipv6 Node ID.
Definition at line 51 of file PcepNaiIpv6NodeId.java.
References org.onosproject.pcepio.types.PcepNaiIpv6NodeId.PcepNaiIpv6NodeId().
static PcepNaiIpv6NodeId org.onosproject.pcepio.types.PcepNaiIpv6NodeId.read (ChannelBuffer cb) static
Reads from the channel buffer and returns object of PcepNAIIpv6NodeId.
Parameters
cb of type channel buffer.
Returns
object of PcepNAIIpv6NodeId
Definition at line 73 of file PcepNaiIpv6NodeId.java.
References org.onosproject.pcepio.types.PcepNaiIpv6NodeId.IPV6_LEN, and org.onosproject.pcepio.types.PcepNaiIpv6NodeId.PcepNaiIpv6NodeId().
String org.onosproject.pcepio.types.PcepNaiIpv6NodeId.toString ()
Definition at line 97 of file PcepNaiIpv6NodeId.java.
int org.onosproject.pcepio.types.PcepNaiIpv6NodeId.write (ChannelBuffer cb)
To write the object information to channelBuffer.
Parameters
cb of type channel buffer
Returns
length of written bytes.
Implements org.onosproject.pcepio.protocol.PcepNai.
Definition at line 61 of file PcepNaiIpv6NodeId.java.
Member Data Documentation
final byte org.onosproject.pcepio.types.PcepNaiIpv6NodeId.IPV6_LEN = 0x10 static
Definition at line 32 of file PcepNaiIpv6NodeId.java.
Referenced by org.onosproject.pcepio.types.PcepNaiIpv6NodeId.read().
final byte org.onosproject.pcepio.types.PcepNaiIpv6NodeId.ST_TYPE = 0x02 static
Definition at line 31 of file PcepNaiIpv6NodeId.java.
Referenced by org.onosproject.pcepio.types.PcepNaiIpv6NodeId.getType().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PcepNaiIpv6NodeId.java