onos: org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler Class Reference
org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler Class Reference
An intent compiler for org.onosproject.net.intent.OpticalCircuitIntent.
Public Member Functions
void modified (ComponentContext context)
void activate (ComponentContext context)
void deactivate ()
List< Intent > compile (OpticalCircuitIntent intent, List< Intent > installable, Set< LinkResourceAllocations > resources)
Protected Attributes
ComponentConfigService cfgService
IntentExtensionService intentManager
CoreService coreService
DeviceService deviceService
ResourceService resourceService
IntentSetMultimap intentSetMultimap
IntentService intentService
Detailed Description
An intent compiler for org.onosproject.net.intent.OpticalCircuitIntent.
Definition at line 75 of file OpticalCircuitIntentCompiler.java.
Member Function Documentation
void org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.activate (ComponentContext context)
Definition at line 136 of file OpticalCircuitIntentCompiler.java.
List<Intent> org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.compile (OpticalCircuitIntent intent, List< Intent > installable, Set< LinkResourceAllocations > resources)
Definition at line 150 of file OpticalCircuitIntentCompiler.java.
References find-link-in-cluster.dstPort, org.onosproject.net.intent.OpticalConnectivityIntent.getDst(), org.onosproject.net.intent.OpticalConnectivityIntent.getSrc(), org.onosproject.net.intent.Intent.id(), org.onosproject.net.OduSignalType.ODU4, org.onosproject.net.ConnectPoint.port(), org.onosproject.net.intent.Intent.resources(), and find-link-in-cluster.srcPort.
void org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.deactivate ()
Definition at line 144 of file OpticalCircuitIntentCompiler.java.
void org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.modified (ComponentContext context)
Definition at line 110 of file OpticalCircuitIntentCompiler.java.
Member Data Documentation
ComponentConfigService org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.cfgService protected
Definition at line 87 of file OpticalCircuitIntentCompiler.java.
CoreService org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.coreService protected
Definition at line 93 of file OpticalCircuitIntentCompiler.java.
DeviceService org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.deviceService protected
Definition at line 96 of file OpticalCircuitIntentCompiler.java.
IntentExtensionService org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.intentManager protected
Definition at line 90 of file OpticalCircuitIntentCompiler.java.
IntentService org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.intentService protected
Definition at line 105 of file OpticalCircuitIntentCompiler.java.
IntentSetMultimap org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.intentSetMultimap protected
Definition at line 102 of file OpticalCircuitIntentCompiler.java.
ResourceService org.onosproject.net.intent.impl.compiler.OpticalCircuitIntentCompiler.resourceService protected
Definition at line 99 of file OpticalCircuitIntentCompiler.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/intent/impl/compiler/OpticalCircuitIntentCompiler.java