onos: org.onosproject.dhcp.rest.DhcpWebResource Class Reference
org.onosproject.dhcp.rest.DhcpWebResource Class Reference
Manage DHCP address assignments.
Public Member Functions
Response getConfigs ()
Get DHCP server configuration data.
Response listMappings ()
Get all MAC/IP mappings.
Response listAvailableIPs ()
Get all available IPs.
Response setMapping (InputStream stream)
Post a new static MAC/IP binding.
Response deleteMapping (@PathParam("macID") String macID)
Delete a static MAC/IP binding.
Public Member Functions inherited from org.onosproject.rest.AbstractWebResource
ObjectMapper mapper ()
Returns the JSON object mapper.
ObjectNode newObject (ObjectNode parent, String key)
Creates and returns a new child object within the specified parent and bound to the given key.
ArrayNode newArray (ObjectNode parent, String key)
Creates and returns a new child array within the specified parent and bound to the given key.
Additional Inherited Members
Static Public Member Functions inherited from org.onlab.rest.BaseResource
static void setServiceDirectory (ServiceDirectory serviceDirectory)
Sets alternate service directory to be used for lookups.
Static Protected Member Functions inherited from org.onlab.rest.BaseResource
static Response.ResponseBuilder ok (Object obj)
Detailed Description
Manage DHCP address assignments.
Definition at line 45 of file DhcpWebResource.java.
Member Function Documentation
Response org.onosproject.dhcp.rest.DhcpWebResource.deleteMapping (@PathParam("macID") String macID)
Delete a static MAC/IP binding.
Removes a static binding from the DHCP Server, and displays the current set of bindings.
Parameters
macID mac address identifier
Returns
200 OK
Definition at line 154 of file DhcpWebResource.java.
References org.onlab.packet.MacAddress.valueOf().
Response org.onosproject.dhcp.rest.DhcpWebResource.getConfigs ()
Get DHCP server configuration data.
Shows lease, renewal and rebinding times in seconds.
Returns
200 OK DhcpConfigGet
Definition at line 58 of file DhcpWebResource.java.
References org.onosproject.dhcp.DhcpService.getLeaseTime(), org.onosproject.dhcp.DhcpService.getRebindingTime(), org.onosproject.dhcp.DhcpService.getRenewalTime(), and create-flow.node.
Response org.onosproject.dhcp.rest.DhcpWebResource.listAvailableIPs ()
Get all available IPs.
Shows all the IPs in the free pool of the DHCP Server.
DhcpConfigGetAvailable
Returns
200 OK
Definition at line 98 of file DhcpWebResource.java.
Response org.onosproject.dhcp.rest.DhcpWebResource.listMappings ()
Get all MAC/IP mappings.
Shows all MAC/IP mappings held by the DHCP server.
DhcpConfigGetMappings
Returns
200 OK
Definition at line 76 of file DhcpWebResource.java.
Response org.onosproject.dhcp.rest.DhcpWebResource.setMapping (InputStream stream)
Post a new static MAC/IP binding.
Registers a static binding to the DHCP server, and displays the current set of bindings.
DhcpConfigPut
Parameters
stream JSON stream
Returns
200 OK
Definition at line 118 of file DhcpWebResource.java.
References org.onlab.packet.MacAddress.valueOf(), and org.onlab.packet.Ip4Address.valueOf().
The documentation for this class was generated from the following file:
apps/dhcp/app/src/main/java/org/onosproject/dhcp/rest/DhcpWebResource.java