onos: org.onosproject.segmentrouting.config.DeviceConfiguration Class Reference
org.onosproject.segmentrouting.config.DeviceConfiguration Class Reference
Segment Routing configuration component that reads the segment routing related configuration from Network Configuration Manager component and organizes in more accessible formats.
Public Member Functions
DeviceConfiguration (NetworkConfigRegistry cfgService)
Constructor.
boolean isConfigured (DeviceId deviceId)
Checks if the device is configured.
int getSegmentId (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the segment id of a device to be used in group creation.
int getSegmentId (MacAddress routerMac)
Returns the Node segment id of a segment router given its Router mac address.
int getSegmentId (Ip4Address routerAddress)
Returns the Node segment id of a segment router given its Router ip address.
MacAddress getDeviceMac (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the Mac address of a device to be used in group creation.
Ip4Address getRouterIp (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the router ip address of a segment router.
boolean isEdgeDevice (DeviceId deviceId) throws DeviceConfigNotFoundException
Indicates whether a device is edge device or transit/core device.
List< Integer > getAllDeviceSegmentIds ()
Returns all segment IDs to be considered in building auto.
Map< Ip4Prefix, List
< PortNumber > > getSubnetPortsMap (DeviceId deviceId)
Returns subnet-to-ports mapping of given device.
DeviceId getDeviceId (int sid)
Returns the device identifier or data plane identifier (dpid) of a segment router given its segment id.
DeviceId getDeviceId (Ip4Address ipAddress)
Returns the device identifier or data plane identifier (dpid) of a segment router given its router ip address.
Set< Ip4Address > getPortIPs (DeviceId deviceId)
Returns the configured port ip addresses for a segment router.
Map< PortNumber, Ip4Address > getPortIPMap (DeviceId deviceId)
Returns the configured IP addresses per port for a segment router.
Set< Ip4Prefix > getSubnets (DeviceId deviceId)
Returns the configured subnet prefixes for a segment router.
Ip4Prefix getPortSubnet (DeviceId deviceId, PortNumber pnum)
Returns the configured subnet on the given port, or null if no subnet has been configured on the port.
Ip4Address getRouterIpAddressForASubnetHost (Ip4Address destIpAddress)
Returns the router ip address of segment router that has the specified ip address in its subnets.
MacAddress getRouterMacForAGatewayIp (Ip4Address gatewayIpAddress)
Returns the router mac address of segment router that has the specified ip address as one of its subnet gateway ip address.
boolean inSameSubnet (DeviceId deviceId, Ip4Address hostIp)
Checks if the host is in the subnet defined in the router with the device ID given.
List< Integer > getPortsForAdjacencySid (DeviceId deviceId, int sid)
Returns the ports corresponding to the adjacency Sid given.
boolean isAdjacencySid (DeviceId deviceId, int sid)
Check if the Sid given is whether adjacency Sid of the router device or not.
Detailed Description
Segment Routing configuration component that reads the segment routing related configuration from Network Configuration Manager component and organizes in more accessible formats.
Definition at line 47 of file DeviceConfiguration.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.config.DeviceConfiguration.DeviceConfiguration (NetworkConfigRegistry cfgService)
Constructor.
Reads all the configuration for all devices of type Segment Router and organizes into various maps for easier access.
Parameters
cfgService config service
Definition at line 77 of file DeviceConfiguration.java.
References find-flow.deviceId, obeliskHostCheck.dpid, and obeliskHostCheck.port.
Member Function Documentation
List<Integer> org.onosproject.segmentrouting.config.DeviceConfiguration.getAllDeviceSegmentIds ()
Returns all segment IDs to be considered in building auto.
created groups.
Returns
list of segment IDs
Implements org.onosproject.segmentrouting.config.DeviceProperties.
Definition at line 215 of file DeviceConfiguration.java.
DeviceId org.onosproject.segmentrouting.config.DeviceConfiguration.getDeviceId (int sid)
Returns the device identifier or data plane identifier (dpid) of a segment router given its segment id.
Parameters
sid segment id
Returns
deviceId device identifier
Definition at line 246 of file DeviceConfiguration.java.
References find-flow.deviceId.
DeviceId org.onosproject.segmentrouting.config.DeviceConfiguration.getDeviceId (Ip4Address ipAddress)
Returns the device identifier or data plane identifier (dpid) of a segment router given its router ip address.
Parameters
ipAddress router ip address
Returns
deviceId device identifier
Definition at line 264 of file DeviceConfiguration.java.
References find-flow.deviceId.
MacAddress org.onosproject.segmentrouting.config.DeviceConfiguration.getDeviceMac (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the Mac address of a device to be used in group creation.
Parameters
deviceId device identifier
Exceptions
DeviceConfigNotFoundException if the device configuration is not found
Returns
mac address of a device
Implements org.onosproject.segmentrouting.config.DeviceProperties.
Definition at line 179 of file DeviceConfiguration.java.
References find-flow.deviceId, and obeliskHostCheck.mac.
Map<PortNumber, Ip4Address> org.onosproject.segmentrouting.config.DeviceConfiguration.getPortIPMap (DeviceId deviceId)
Returns the configured IP addresses per port for a segment router.
Parameters
deviceId device identifier
Returns
map of port to gateway IP addresses or null if not found
Definition at line 300 of file DeviceConfiguration.java.
References find-flow.deviceId.
Set<Ip4Address> org.onosproject.segmentrouting.config.DeviceConfiguration.getPortIPs (DeviceId deviceId)
Returns the configured port ip addresses for a segment router.
These addresses serve as gateway IP addresses for the subnets configured on those ports.
Parameters
deviceId device identifier
Returns
immutable set of ip addresses configured on the ports or null if not found
Definition at line 283 of file DeviceConfiguration.java.
References find-flow.deviceId.
List<Integer> org.onosproject.segmentrouting.config.DeviceConfiguration.getPortsForAdjacencySid (DeviceId deviceId, int sid)
Returns the ports corresponding to the adjacency Sid given.
Parameters
deviceId device identification of the router
sid adjacency Sid
Returns
list of port numbers
Definition at line 415 of file DeviceConfiguration.java.
References find-flow.deviceId, and org.onosproject.segmentrouting.config.SegmentRoutingConfig.AdjacencySid.getAsid().
Ip4Prefix org.onosproject.segmentrouting.config.DeviceConfiguration.getPortSubnet (DeviceId deviceId, PortNumber pnum)
Returns the configured subnet on the given port, or null if no subnet has been configured on the port.
Parameters
deviceId device identifier
pnum port identifier
Returns
configured subnet on port, or null
Definition at line 332 of file DeviceConfiguration.java.
References find-flow.deviceId.
Ip4Address org.onosproject.segmentrouting.config.DeviceConfiguration.getRouterIp (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the router ip address of a segment router.
Parameters
deviceId device identifier
Exceptions
DeviceConfigNotFoundException if the device configuration is not found
Returns
router ip address
Implements org.onosproject.segmentrouting.config.DeviceProperties.
Definition at line 191 of file DeviceConfiguration.java.
References find-flow.deviceId.
Ip4Address org.onosproject.segmentrouting.config.DeviceConfiguration.getRouterIpAddressForASubnetHost (Ip4Address destIpAddress)
Returns the router ip address of segment router that has the specified ip address in its subnets.
Parameters
destIpAddress target ip address
Returns
router ip address
Definition at line 347 of file DeviceConfiguration.java.
References onosUploadBits.prefix.
MacAddress org.onosproject.segmentrouting.config.DeviceConfiguration.getRouterMacForAGatewayIp (Ip4Address gatewayIpAddress)
Returns the router mac address of segment router that has the specified ip address as one of its subnet gateway ip address.
Parameters
gatewayIpAddress router gateway ip address
Returns
router mac address or null if not found
Definition at line 368 of file DeviceConfiguration.java.
References obeliskHostCheck.mac.
int org.onosproject.segmentrouting.config.DeviceConfiguration.getSegmentId (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the segment id of a device to be used in group creation.
Parameters
deviceId device identifier
Exceptions
DeviceConfigNotFoundException if the device configuration is not found
Returns
segment id of a device
Implements org.onosproject.segmentrouting.config.DeviceProperties.
Definition at line 133 of file DeviceConfiguration.java.
References find-flow.deviceId.
int org.onosproject.segmentrouting.config.DeviceConfiguration.getSegmentId (MacAddress routerMac)
Returns the Node segment id of a segment router given its Router mac address.
Parameters
routerMac router mac address
Returns
node segment id, or -1 if not found in config
Definition at line 150 of file DeviceConfiguration.java.
int org.onosproject.segmentrouting.config.DeviceConfiguration.getSegmentId (Ip4Address routerAddress)
Returns the Node segment id of a segment router given its Router ip address.
Parameters
routerAddress router ip address
Returns
node segment id, or -1 if not found in config
Definition at line 167 of file DeviceConfiguration.java.
Map<Ip4Prefix, List<PortNumber> > org.onosproject.segmentrouting.config.DeviceConfiguration.getSubnetPortsMap (DeviceId deviceId)
Returns subnet-to-ports mapping of given device.
For each entry of the map Key: a subnet Value: a list of ports, which are bound to the subnet
Parameters
deviceId device identifier
Returns
a map that contains all subnet-to-ports mapping of given device
Implements org.onosproject.segmentrouting.config.DeviceProperties.
Definition at line 220 of file DeviceConfiguration.java.
References find-flow.deviceId, and obeliskHostCheck.port.
Set<Ip4Prefix> org.onosproject.segmentrouting.config.DeviceConfiguration.getSubnets (DeviceId deviceId)
Returns the configured subnet prefixes for a segment router.
Parameters
deviceId device identifier
Returns
list of ip prefixes or null if not found
Definition at line 314 of file DeviceConfiguration.java.
References find-flow.deviceId.
Referenced by org.onosproject.segmentrouting.config.DeviceConfiguration.inSameSubnet().
boolean org.onosproject.segmentrouting.config.DeviceConfiguration.inSameSubnet (DeviceId deviceId, Ip4Address hostIp)
Checks if the host is in the subnet defined in the router with the device ID given.
Parameters
deviceId device identification of the router
hostIp host IP address to check
Returns
true if the host is within the subnet of the router, false if no subnet is defined under the router or if the host is not within the subnet defined in the router
Definition at line 392 of file DeviceConfiguration.java.
References org.onosproject.segmentrouting.config.DeviceConfiguration.getSubnets().
Referenced by org.onosproject.segmentrouting.IpHandler.forwardPackets(), org.onosproject.segmentrouting.IcmpHandler.processPacketIn(), and org.onosproject.segmentrouting.IpHandler.processPacketIn().
boolean org.onosproject.segmentrouting.config.DeviceConfiguration.isAdjacencySid (DeviceId deviceId, int sid)
Check if the Sid given is whether adjacency Sid of the router device or not.
Parameters
deviceId device identification of the router
sid Sid to check
Returns
true if the Sid given is the adjacency Sid of the device, otherwise false
Definition at line 436 of file DeviceConfiguration.java.
References find-flow.deviceId, and org.onosproject.segmentrouting.config.SegmentRoutingConfig.AdjacencySid.getAsid().
boolean org.onosproject.segmentrouting.config.DeviceConfiguration.isConfigured (DeviceId deviceId)
Checks if the device is configured.
Parameters
deviceId device identifier
Returns
true if the device is configured
Implements org.onosproject.segmentrouting.config.DeviceProperties.
Definition at line 128 of file DeviceConfiguration.java.
References find-flow.deviceId.
boolean org.onosproject.segmentrouting.config.DeviceConfiguration.isEdgeDevice (DeviceId deviceId) throws DeviceConfigNotFoundException
Indicates whether a device is edge device or transit/core device.
Parameters
deviceId device identifier
Exceptions
DeviceConfigNotFoundException if the device configuration is not found
Returns
boolean
Implements org.onosproject.segmentrouting.config.DeviceProperties.
Definition at line 203 of file DeviceConfiguration.java.
References find-flow.deviceId.
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/config/DeviceConfiguration.java