onos: org.onosproject.cord.gui.model.JsonFactory Class Reference
org.onosproject.cord.gui.model.JsonFactory Class Reference
Base class for factories that convert objects to JSON.
Static Protected Member Functions
static ObjectNode objectNode ()
Returns a freshly minted object node.
static ArrayNode arrayNode ()
Returns a freshly minted array node.
Static Protected Attributes
static final String ID = "id"
static final String NAME = "name"
static final String DESC = "desc"
static final String ICON_ID = "icon_id"
Detailed Description
Base class for factories that convert objects to JSON.
Definition at line 27 of file JsonFactory.java.
Member Function Documentation
static ArrayNode org.onosproject.cord.gui.model.JsonFactory.arrayNode () static protected
Returns a freshly minted array node.
Returns
empty array node
Definition at line 50 of file JsonFactory.java.
Referenced by org.onosproject.cord.gui.model.BundleFactory.toObjectNode().
static ObjectNode org.onosproject.cord.gui.model.JsonFactory.objectNode () static protected
Returns a freshly minted object node.
Returns
empty object node
Definition at line 41 of file JsonFactory.java.
Referenced by org.onosproject.cord.gui.CordModelCache.jsonDashboard(), org.onosproject.cord.gui.CordModelCache.jsonLogin(), org.onosproject.cord.gui.CordModelCache.jsonLogout(), org.onosproject.cord.gui.CordModelCache.jsonUsers(), org.onosproject.cord.gui.model.XosFunctionFactory.profileForUser(), org.onosproject.cord.gui.model.XosFunctionFactory.toObjectNode(), org.onosproject.cord.gui.model.UserFactory.toObjectNode(), and org.onosproject.cord.gui.model.BundleFactory.toObjectNode().
Member Data Documentation
final String org.onosproject.cord.gui.model.JsonFactory.DESC = "desc" static protected
Definition at line 33 of file JsonFactory.java.
Referenced by org.onosproject.cord.gui.model.XosFunctionFactory.toObjectNode(), and org.onosproject.cord.gui.model.BundleFactory.toObjectNode().
final String org.onosproject.cord.gui.model.JsonFactory.ICON_ID = "icon_id" static protected
Definition at line 34 of file JsonFactory.java.
Referenced by org.onosproject.cord.gui.model.UserFactory.toObjectNode().
final String org.onosproject.cord.gui.model.JsonFactory.ID = "id" static protected
Definition at line 31 of file JsonFactory.java.
Referenced by org.onosproject.cord.gui.model.XosFunctionFactory.toObjectNode(), org.onosproject.cord.gui.model.UserFactory.toObjectNode(), and org.onosproject.cord.gui.model.BundleFactory.toObjectNode().
final String org.onosproject.cord.gui.model.JsonFactory.NAME = "name" static protected
Definition at line 32 of file JsonFactory.java.
Referenced by org.onosproject.cord.gui.model.XosFunctionFactory.toObjectNode(), org.onosproject.cord.gui.model.UserFactory.toObjectNode(), and org.onosproject.cord.gui.model.BundleFactory.toObjectNode().
The documentation for this class was generated from the following file:
apps/demo/cord-gui/src/main/java/org/onosproject/cord/gui/model/JsonFactory.java