onos: org.onosproject.pcep.api.PcepDpid Class Reference
org.onosproject.pcep.api.PcepDpid Class Reference
The class representing a network switch PCEPDid.
Public Member Functions
PcepDpid ()
Default constructor.
PcepDpid (long value)
Constructor from a long value.
PcepDpid (String value)
Constructor from a String.
long value ()
Return a device id with the form of long.
Static Public Member Functions
static URI uri (PcepDpid dpid)
Produces device URI from the given DPID.
static long toLong (String value)
Produces device long from the given string which comes from the uri method.
static URI uri (long value)
Produces device URI from the given DPID long.
Detailed Description
The class representing a network switch PCEPDid.
This class is immutable.
Definition at line 26 of file PcepDpid.java.
Constructor & Destructor Documentation
org.onosproject.pcep.api.PcepDpid.PcepDpid ()
Default constructor.
Definition at line 35 of file PcepDpid.java.
org.onosproject.pcep.api.PcepDpid.PcepDpid (long value)
Constructor from a long value.
Parameters
value long value for construct
Definition at line 44 of file PcepDpid.java.
References org.onosproject.pcep.api.PcepDpid.value().
org.onosproject.pcep.api.PcepDpid.PcepDpid (String value)
Constructor from a String.
Parameters
value string value for construct
Definition at line 53 of file PcepDpid.java.
References org.onosproject.pcep.api.PcepDpid.value().
Member Function Documentation
static long org.onosproject.pcep.api.PcepDpid.toLong (String value) static
Produces device long from the given string which comes from the uri method.
Parameters
value string value which produced by uri method.
Returns
a long value.
Definition at line 74 of file PcepDpid.java.
static URI org.onosproject.pcep.api.PcepDpid.uri (PcepDpid dpid) static
Produces device URI from the given DPID.
Parameters
dpid device dpid
Returns
device URI
Definition at line 63 of file PcepDpid.java.
static URI org.onosproject.pcep.api.PcepDpid.uri (long value) static
Produces device URI from the given DPID long.
Parameters
value device dpid as long
Returns
device URI
Definition at line 84 of file PcepDpid.java.
References org.onosproject.pcep.tools.PcepTools.longToIp().
long org.onosproject.pcep.api.PcepDpid.value ()
Return a device id with the form of long.
Returns
long value
Definition at line 97 of file PcepDpid.java.
Referenced by org.onosproject.pcep.api.PcepDpid.PcepDpid().
The documentation for this class was generated from the following file:
apps/pcep-api/src/main/java/org/onosproject/pcep/api/PcepDpid.java