onos: org.onlab.packet.ICMPTest Class Reference
org.onlab.packet.ICMPTest Class Reference
Unit tests for the ICMP class.
Public Member Functions
void setUp () throws Exception
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws Exception
Detailed Description
Unit tests for the ICMP class.
Definition at line 29 of file ICMPTest.java.
Member Function Documentation
void org.onlab.packet.ICMPTest.setUp () throws Exception
Definition at line 40 of file ICMPTest.java.
References org.onlab.packet.ICMP.ICMP_HEADER_LENGTH.
void org.onlab.packet.ICMPTest.testDeserialize () throws Exception
Definition at line 63 of file ICMPTest.java.
References org.onlab.packet.ICMP.getChecksum(), org.onlab.packet.ICMP.getIcmpCode(), org.onlab.packet.ICMP.getIcmpType(), and find-link-in-cluster.length.
void org.onlab.packet.ICMPTest.testDeserializeBadInput () throws Exception
Definition at line 53 of file ICMPTest.java.
void org.onlab.packet.ICMPTest.testDeserializeTruncated () throws Exception
Definition at line 58 of file ICMPTest.java.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ICMPTest.java