onos: org.onosproject.store.intent.impl.GossipIntentStore Class Reference
org.onosproject.store.intent.impl.GossipIntentStore Class Reference
Manages inventory of Intents in a distributed data store that uses optimistic replication and gossip based techniques.
Public Member Functions
void activate ()
void deactivate ()
long getIntentCount ()
Returns the number of intents in the store.
Iterable< Intent > getIntents ()
Returns an iterable of all intents in the store.
Iterable< IntentData > getIntentData (boolean localOnly, long olderThan)
Returns an iterable of all intent data objects in the store.
IntentState getIntentState (Key intentKey)
Returns the state of the specified intent.
List< Intent > getInstallableIntents (Key intentKey)
Returns the list of the installable events associated with the specified original intent.
void write (IntentData newData)
Writes an IntentData object to the store.
void batchWrite (Iterable< IntentData > updates)
Writes a batch of IntentData objects to the store.
Intent getIntent (Key key)
Returns the intent with the specified identifier.
IntentData getIntentData (Key key)
Returns the intent data object associated with the specified key.
void addPending (IntentData data)
Adds a new operation, which should be persisted and delegated.
boolean isMaster (Key intentKey)
Checks to see whether the calling instance is the master for processing this intent, or more specifically, the key contained in this intent.
Iterable< Intent > getPending ()
Returns the intent requests pending processing.
Iterable< IntentData > getPendingData ()
Returns the intent data objects that are pending processing.
Iterable< IntentData > getPendingData (boolean localOnly, long olderThan)
Returns the intent data objects that are pending processing for longer than the specified duration.
Protected Attributes
ClusterService clusterService
StorageService storageService
PartitionService partitionService
Detailed Description
Manages inventory of Intents in a distributed data store that uses optimistic replication and gossip based techniques.
Definition at line 67 of file GossipIntentStore.java.
Member Function Documentation
void org.onosproject.store.intent.impl.GossipIntentStore.activate ()
Definition at line 91 of file GossipIntentStore.java.
References org.onosproject.store.serializers.KryoNamespaces.API.
void org.onosproject.store.intent.impl.GossipIntentStore.addPending (IntentData intent)
Adds a new operation, which should be persisted and delegated.
Parameters
intent operation
Implements org.onosproject.net.intent.IntentStore.
Definition at line 252 of file GossipIntentStore.java.
void org.onosproject.store.intent.impl.GossipIntentStore.batchWrite (Iterable< IntentData > updates)
Writes a batch of IntentData objects to the store.
A batch has no semantics, this is simply a convenience API.
Parameters
updates collection of intent data objects to write
Implements org.onosproject.net.intent.IntentStore.
Definition at line 229 of file GossipIntentStore.java.
void org.onosproject.store.intent.impl.GossipIntentStore.deactivate ()
Definition at line 122 of file GossipIntentStore.java.
List<Intent> org.onosproject.store.intent.impl.GossipIntentStore.getInstallableIntents (Key intentKey)
Returns the list of the installable events associated with the specified original intent.
Parameters
intentKey original intent identifier
Returns
compiled installable intents, or null if no installables exist
Implements org.onosproject.net.intent.IntentStore.
Definition at line 164 of file GossipIntentStore.java.
Intent org.onosproject.store.intent.impl.GossipIntentStore.getIntent (Key key)
Returns the intent with the specified identifier.
Parameters
key key
Returns
intent or null if not found
Implements org.onosproject.net.intent.IntentStore.
Definition at line 234 of file GossipIntentStore.java.
long org.onosproject.store.intent.impl.GossipIntentStore.getIntentCount ()
Returns the number of intents in the store.
Returns
the number of intents in the store
Implements org.onosproject.net.intent.IntentStore.
Definition at line 130 of file GossipIntentStore.java.
Referenced by org.onosproject.store.intent.impl.GossipIntentStoreTest.testAddAndWithdrawIntent(), org.onosproject.store.intent.impl.GossipIntentStoreTest.testBatchAdd(), and org.onosproject.store.intent.impl.GossipIntentStoreTest.testGetIntentCount().
Iterable<IntentData> org.onosproject.store.intent.impl.GossipIntentStore.getIntentData (boolean localOnly, long olderThan)
Returns an iterable of all intent data objects in the store.
Parameters
localOnly should only intents for which this instance is master be returned
olderThan specified duration in milliseconds (0 for "now")
Returns
iterable of all intent data objects
Implements org.onosproject.net.intent.IntentStore.
Definition at line 142 of file GossipIntentStore.java.
References org.onosproject.store.intent.impl.GossipIntentStore.isMaster().
IntentData org.onosproject.store.intent.impl.GossipIntentStore.getIntentData (Key key)
Returns the intent data object associated with the specified key.
Parameters
key key to look up
Returns
intent data object
Implements org.onosproject.net.intent.IntentStore.
Definition at line 243 of file GossipIntentStore.java.
Iterable<Intent> org.onosproject.store.intent.impl.GossipIntentStore.getIntents ()
Returns an iterable of all intents in the store.
Returns
iterable of all intents
Implements org.onosproject.net.intent.IntentStore.
Definition at line 135 of file GossipIntentStore.java.
References org.onosproject.net.intent.IntentData.intent().
IntentState org.onosproject.store.intent.impl.GossipIntentStore.getIntentState (Key intentKey)
Returns the state of the specified intent.
Parameters
intentKey intent identification
Returns
current intent state
Implements org.onosproject.net.intent.IntentStore.
Definition at line 155 of file GossipIntentStore.java.
Iterable<Intent> org.onosproject.store.intent.impl.GossipIntentStore.getPending ()
Returns the intent requests pending processing.
Returns
pending intents
Implements org.onosproject.net.intent.IntentStore.
Definition at line 268 of file GossipIntentStore.java.
References org.onosproject.net.intent.IntentData.intent().
Iterable<IntentData> org.onosproject.store.intent.impl.GossipIntentStore.getPendingData ()
Returns the intent data objects that are pending processing.
Returns
pending intent data objects
Implements org.onosproject.net.intent.IntentStore.
Definition at line 275 of file GossipIntentStore.java.
Iterable<IntentData> org.onosproject.store.intent.impl.GossipIntentStore.getPendingData (boolean localOnly, long olderThan)
Returns the intent data objects that are pending processing for longer than the specified duration.
Parameters
localOnly should only intents for which this instance is master be returned
olderThan specified duration in milliseconds (0 for "now")
Returns
pending intent data objects
Implements org.onosproject.net.intent.IntentStore.
Definition at line 280 of file GossipIntentStore.java.
References org.onosproject.store.intent.impl.GossipIntentStore.isMaster(), and org.onosproject.net.intent.IntentData.key().
boolean org.onosproject.store.intent.impl.GossipIntentStore.isMaster (Key intentKey)
Checks to see whether the calling instance is the master for processing this intent, or more specifically, the key contained in this intent.
Parameters
intentKey intentKey to check
Returns
true if master; false, otherwise
Implements org.onosproject.net.intent.IntentStore.
Definition at line 263 of file GossipIntentStore.java.
Referenced by org.onosproject.store.intent.impl.GossipIntentStore.getIntentData(), and org.onosproject.store.intent.impl.GossipIntentStore.getPendingData().
void org.onosproject.store.intent.impl.GossipIntentStore.write (IntentData newData)
Writes an IntentData object to the store.
Parameters
newData new intent data to write
Implements org.onosproject.net.intent.IntentStore.
Definition at line 175 of file GossipIntentStore.java.
References org.onosproject.net.intent.IntentData.isUpdateAcceptable().
Member Data Documentation
ClusterService org.onosproject.store.intent.impl.GossipIntentStore.clusterService protected
Definition at line 80 of file GossipIntentStore.java.
PartitionService org.onosproject.store.intent.impl.GossipIntentStore.partitionService protected
Definition at line 86 of file GossipIntentStore.java.
StorageService org.onosproject.store.intent.impl.GossipIntentStore.storageService protected
Definition at line 83 of file GossipIntentStore.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/intent/impl/GossipIntentStore.java