onos: org.onosproject.ovsdb.controller.OvsdbTunnel Class Reference
org.onosproject.ovsdb.controller.OvsdbTunnel Class Reference
The class representing an ovsdb tunnel.
Classes
enum Type
Public Member Functions
OvsdbTunnel (IpAddress localIp, IpAddress remoteIp, Type tunnelType, OvsdbTunnelName tunnelName)
Constructor from an IpAddress localIp, IpAddress remoteIp Type tunnelType, OvsdbTunnelName tunnelName.
IpAddress localIp ()
Gets the local IP of tunnel.
IpAddress remoteIp ()
Gets the remote IP of tunnel.
Type tunnelType ()
Gets the tunnel type of tunnel.
OvsdbTunnelName tunnelName ()
Gets the tunnel name of tunnel.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
The class representing an ovsdb tunnel.
This class is immutable.
Definition at line 29 of file OvsdbTunnel.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.controller.OvsdbTunnel.OvsdbTunnel (IpAddress localIp, IpAddress remoteIp, Type tunnelType, OvsdbTunnelName tunnelName)
Constructor from an IpAddress localIp, IpAddress remoteIp Type tunnelType, OvsdbTunnelName tunnelName.
Parameters
localIp the localIp to use
remoteIp the remoteIp to use
tunnelType the tunnelType to use
tunnelName the tunnelName to use
Definition at line 50 of file OvsdbTunnel.java.
References org.onosproject.ovsdb.controller.OvsdbTunnel.localIp(), org.onosproject.ovsdb.controller.OvsdbTunnel.remoteIp(), org.onosproject.ovsdb.controller.OvsdbTunnel.tunnelName(), and org.onosproject.ovsdb.controller.OvsdbTunnel.tunnelType().
Referenced by org.onosproject.ovsdb.controller.OvsdbTunnel.equals().
Member Function Documentation
boolean org.onosproject.ovsdb.controller.OvsdbTunnel.equals (Object obj)
Definition at line 103 of file OvsdbTunnel.java.
References org.onosproject.ovsdb.controller.OvsdbTunnel.OvsdbTunnel().
int org.onosproject.ovsdb.controller.OvsdbTunnel.hashCode ()
Definition at line 98 of file OvsdbTunnel.java.
References org.onosproject.ovsdb.controller.OvsdbTunnel.localIp(), org.onosproject.ovsdb.controller.OvsdbTunnel.remoteIp(), org.onosproject.ovsdb.controller.OvsdbTunnel.tunnelName(), and org.onosproject.ovsdb.controller.OvsdbTunnel.tunnelType().
IpAddress org.onosproject.ovsdb.controller.OvsdbTunnel.localIp ()
Gets the local IP of tunnel.
Returns
the local IP of tunnel
Definition at line 66 of file OvsdbTunnel.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbTunnel.hashCode(), and org.onosproject.ovsdb.controller.OvsdbTunnel.OvsdbTunnel().
IpAddress org.onosproject.ovsdb.controller.OvsdbTunnel.remoteIp ()
Gets the remote IP of tunnel.
Returns
the remote IP of tunnel
Definition at line 75 of file OvsdbTunnel.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbTunnel.hashCode(), and org.onosproject.ovsdb.controller.OvsdbTunnel.OvsdbTunnel().
String org.onosproject.ovsdb.controller.OvsdbTunnel.toString ()
Definition at line 120 of file OvsdbTunnel.java.
References org.onosproject.ovsdb.controller.OvsdbTunnel.tunnelName(), and org.onosproject.ovsdb.controller.OvsdbTunnel.tunnelType().
OvsdbTunnelName org.onosproject.ovsdb.controller.OvsdbTunnel.tunnelName ()
Gets the tunnel name of tunnel.
Returns
the tunnel name of tunnel
Definition at line 93 of file OvsdbTunnel.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbTunnel.hashCode(), org.onosproject.ovsdb.controller.OvsdbTunnel.OvsdbTunnel(), and org.onosproject.ovsdb.controller.OvsdbTunnel.toString().
Type org.onosproject.ovsdb.controller.OvsdbTunnel.tunnelType ()
Gets the tunnel type of tunnel.
Returns
the tunnel type of tunnel
Definition at line 84 of file OvsdbTunnel.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbTunnel.hashCode(), org.onosproject.ovsdb.controller.OvsdbTunnel.OvsdbTunnel(), and org.onosproject.ovsdb.controller.OvsdbTunnel.toString().
The documentation for this class was generated from the following file:
protocols/ovsdb/api/src/main/java/org/onosproject/ovsdb/controller/OvsdbTunnel.java