onos: org.onosproject.routing.impl.RouterTest Class Reference
org.onosproject.routing.impl.RouterTest Class Reference
This class tests adding a route, updating a route, deleting a route, and adding a route whose next hop is the local BGP speaker.
Public Member Functions
void setUp () throws Exception
void tearDown ()
void testIpv4RouteAdd ()
Tests adding a IPv4 route entry.
void testIpv6RouteAdd ()
Tests adding a IPv6 route entry.
void testRouteUpdate ()
Tests updating a IPv4 route entry.
void testIpv6RouteUpdate ()
Tests updating a IPv6 route entry.
void testIpv4RouteDelete ()
Tests deleting a IPv4 route entry.
void testIpv6RouteDelete ()
Tests deleting a IPv6 route entry.
void testIpv4LocalRouteAdd ()
Tests adding a IPv4 route whose next hop is the local BGP speaker.
void testIpv6LocalRouteAdd ()
Tests adding a IPv6 route whose next hop is the local BGP speaker.
Detailed Description
This class tests adding a route, updating a route, deleting a route, and adding a route whose next hop is the local BGP speaker.
The HostService answers requests synchronously.
Definition at line 63 of file RouterTest.java.
Member Function Documentation
void org.onosproject.routing.impl.RouterTest.setUp () throws Exception
Definition at line 96 of file RouterTest.java.
void org.onosproject.routing.impl.RouterTest.tearDown ()
Definition at line 120 of file RouterTest.java.
void org.onosproject.routing.impl.RouterTest.testIpv4LocalRouteAdd ()
Tests adding a IPv4 route whose next hop is the local BGP speaker.
Definition at line 402 of file RouterTest.java.
References org.onosproject.routing.impl.Router.getRoutes4(), org.onosproject.routing.config.RoutingConfigurationService.isIpPrefixLocal(), and org.onlab.packet.Ip4Prefix.valueOf().
void org.onosproject.routing.impl.RouterTest.testIpv4RouteAdd ()
Tests adding a IPv4 route entry.
Definition at line 212 of file RouterTest.java.
References onosUploadBits.prefix, and org.onlab.packet.MacAddress.valueOf().
Referenced by org.onosproject.routing.impl.RouterTest.testIpv4RouteDelete(), and org.onosproject.routing.impl.RouterTest.testRouteUpdate().
void org.onosproject.routing.impl.RouterTest.testIpv4RouteDelete ()
Tests deleting a IPv4 route entry.
Definition at line 348 of file RouterTest.java.
References org.onosproject.routing.impl.RouterTest.testIpv4RouteAdd(), and org.onlab.packet.Ip4Prefix.valueOf().
void org.onosproject.routing.impl.RouterTest.testIpv6LocalRouteAdd ()
Tests adding a IPv6 route whose next hop is the local BGP speaker.
Definition at line 431 of file RouterTest.java.
References org.onosproject.routing.impl.Router.getRoutes6(), org.onosproject.routing.config.RoutingConfigurationService.isIpPrefixLocal(), and org.onlab.packet.Ip6Prefix.valueOf().
void org.onosproject.routing.impl.RouterTest.testIpv6RouteAdd ()
Tests adding a IPv6 route entry.
Definition at line 239 of file RouterTest.java.
References onosUploadBits.prefix, and org.onlab.packet.MacAddress.valueOf().
Referenced by org.onosproject.routing.impl.RouterTest.testIpv6RouteDelete(), and org.onosproject.routing.impl.RouterTest.testIpv6RouteUpdate().
void org.onosproject.routing.impl.RouterTest.testIpv6RouteDelete ()
Tests deleting a IPv6 route entry.
Definition at line 375 of file RouterTest.java.
References org.onosproject.routing.impl.RouterTest.testIpv6RouteAdd(), and org.onlab.packet.Ip6Prefix.valueOf().
void org.onosproject.routing.impl.RouterTest.testIpv6RouteUpdate ()
Tests updating a IPv6 route entry.
Definition at line 307 of file RouterTest.java.
References org.onosproject.routing.config.RoutingConfigurationService.isIpPrefixLocal(), org.onosproject.routing.impl.RouterTest.testIpv6RouteAdd(), org.onlab.packet.MacAddress.valueOf(), and org.onlab.packet.Ip6Prefix.valueOf().
void org.onosproject.routing.impl.RouterTest.testRouteUpdate ()
Tests updating a IPv4 route entry.
Definition at line 266 of file RouterTest.java.
References org.onosproject.routing.config.RoutingConfigurationService.isIpPrefixLocal(), org.onosproject.routing.impl.RouterTest.testIpv4RouteAdd(), org.onlab.packet.MacAddress.valueOf(), and org.onlab.packet.Ip4Prefix.valueOf().
The documentation for this class was generated from the following file:
apps/routing/src/test/java/org/onosproject/routing/impl/RouterTest.java