onos: org.onosproject.vtnrsc.DefaultVirtualPort Class Reference
org.onosproject.vtnrsc.DefaultVirtualPort Class Reference
Default implementation of VirtualPort interface .
Public Member Functions
DefaultVirtualPort (VirtualPortId id, TenantNetworkId networkId, Boolean adminStateUp, Map< String, String > strMap, State state, MacAddress macAddress, TenantId tenantId, DeviceId deviceId, Set< FixedIp > fixedIps, BindingHostId bindingHostId, Set< AllowedAddressPair > allowedAddressPairs, Set< SecurityGroup > securityGroups)
Creates a VirtualPort object.
VirtualPortId portId ()
Returns the virtualPort identifier.
TenantNetworkId networkId ()
Returns the network identifier.
String name ()
Returns the symbolic name for the virtualPort.
boolean adminStateUp ()
Returns the administrative status of the port,which is up(true) or down(false).
State state ()
Returns the state.
MacAddress macAddress ()
Returns the MAC address.
TenantId tenantId ()
Returns the port tenantId.
DeviceId deviceId ()
Returns the device identifier.
String deviceOwner ()
Returns the identifier of the entity that uses this port.
Collection< AllowedAddressPair > allowedAddressPairs ()
Returns the virtualPort allowedAddressPairs.
Set< FixedIp > fixedIps ()
Returns set of IP addresses for the port, include the IP addresses and subnet identity.
BindingHostId bindingHostId ()
Returns the virtualPort bindinghostId.
String bindingVnicType ()
Returns the virtualPort bindingVnicType.
String bindingVifType ()
Returns the virtualPort bindingVifType.
String bindingVifDetails ()
Returns the virtualPort bindingvifDetail.
Collection< SecurityGroup > securityGroups ()
Returns the security groups.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of VirtualPort interface .
Definition at line 31 of file DefaultVirtualPort.java.
Constructor & Destructor Documentation
org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort (VirtualPortId id, TenantNetworkId networkId, Boolean adminStateUp, Map< String, String > strMap, State state, MacAddress macAddress, TenantId tenantId, DeviceId deviceId, Set< FixedIp > fixedIps, BindingHostId bindingHostId, Set< AllowedAddressPair > allowedAddressPairs, Set< SecurityGroup > securityGroups)
Creates a VirtualPort object.
Parameters
id the virtual port identifier
networkId the network identifier
adminStateUp adminStateup true or false
strMap the map of properties of virtual port
state virtual port state
macAddress the MAC address
tenantId the tenant identifier
deviceId the device identifier
fixedIps set of fixed IP
bindingHostId the binding host identifier
allowedAddressPairs the collection of allowdeAddressPairs
securityGroups the collection of securityGroups
Definition at line 65 of file DefaultVirtualPort.java.
References org.onosproject.vtnrsc.DefaultVirtualPort.adminStateUp(), org.onosproject.vtnrsc.DefaultVirtualPort.allowedAddressPairs(), org.onosproject.vtnrsc.DefaultVirtualPort.bindingHostId(), org.onosproject.vtnrsc.DefaultVirtualPort.deviceId(), org.onosproject.vtnrsc.DefaultVirtualPort.fixedIps(), org.onosproject.vtnrsc.DefaultVirtualPort.macAddress(), org.onosproject.vtnrsc.DefaultVirtualPort.networkId(), org.onosproject.vtnrsc.DefaultVirtualPort.securityGroups(), org.onosproject.vtnrsc.DefaultVirtualPort.state(), and org.onosproject.vtnrsc.DefaultVirtualPort.tenantId().
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.equals().
Member Function Documentation
boolean org.onosproject.vtnrsc.DefaultVirtualPort.adminStateUp ()
Returns the administrative status of the port,which is up(true) or down(false).
Returns
true if the administrative status of the port is up
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 111 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
Collection<AllowedAddressPair> org.onosproject.vtnrsc.DefaultVirtualPort.allowedAddressPairs ()
Returns the virtualPort allowedAddressPairs.
Returns
virtualPort allowedAddressPairs
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 141 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
BindingHostId org.onosproject.vtnrsc.DefaultVirtualPort.bindingHostId ()
Returns the virtualPort bindinghostId.
Returns
virtualPort bindinghostId
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 151 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
String org.onosproject.vtnrsc.DefaultVirtualPort.bindingVifDetails ()
Returns the virtualPort bindingvifDetail.
Returns
virtualPort bindingvifDetail
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 166 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
String org.onosproject.vtnrsc.DefaultVirtualPort.bindingVifType ()
Returns the virtualPort bindingVifType.
Returns
virtualPort bindingVifType
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 161 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.bindingVnicType(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
String org.onosproject.vtnrsc.DefaultVirtualPort.bindingVnicType ()
Returns the virtualPort bindingVnicType.
Returns
virtualPort bindingVnicType
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 156 of file DefaultVirtualPort.java.
References org.onosproject.vtnrsc.DefaultVirtualPort.bindingVifType().
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
DeviceId org.onosproject.vtnrsc.DefaultVirtualPort.deviceId ()
Returns the device identifier.
Returns
deviceId
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 131 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
String org.onosproject.vtnrsc.DefaultVirtualPort.deviceOwner ()
Returns the identifier of the entity that uses this port.
Returns
deviceOwner
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 136 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
boolean org.onosproject.vtnrsc.DefaultVirtualPort.equals (Object obj)
Definition at line 185 of file DefaultVirtualPort.java.
References org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), find-device.id, and create-flow.name.
Set<FixedIp> org.onosproject.vtnrsc.DefaultVirtualPort.fixedIps ()
Returns set of IP addresses for the port, include the IP addresses and subnet identity.
Returns
FixedIps Set of fixedIp
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 146 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
int org.onosproject.vtnrsc.DefaultVirtualPort.hashCode ()
Definition at line 176 of file DefaultVirtualPort.java.
References org.onosproject.vtnrsc.DefaultVirtualPort.adminStateUp(), org.onosproject.vtnrsc.DefaultVirtualPort.allowedAddressPairs(), org.onosproject.vtnrsc.DefaultVirtualPort.bindingHostId(), org.onosproject.vtnrsc.DefaultVirtualPort.bindingVifDetails(), org.onosproject.vtnrsc.DefaultVirtualPort.bindingVifType(), org.onosproject.vtnrsc.DefaultVirtualPort.bindingVnicType(), org.onosproject.vtnrsc.DefaultVirtualPort.deviceId(), org.onosproject.vtnrsc.DefaultVirtualPort.deviceOwner(), org.onosproject.vtnrsc.DefaultVirtualPort.fixedIps(), org.onosproject.vtnrsc.DefaultVirtualPort.macAddress(), org.onosproject.vtnrsc.DefaultVirtualPort.name(), org.onosproject.vtnrsc.DefaultVirtualPort.networkId(), org.onosproject.vtnrsc.DefaultVirtualPort.securityGroups(), org.onosproject.vtnrsc.DefaultVirtualPort.state(), and org.onosproject.vtnrsc.DefaultVirtualPort.tenantId().
MacAddress org.onosproject.vtnrsc.DefaultVirtualPort.macAddress ()
Returns the MAC address.
Returns
MAC Address
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 121 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
String org.onosproject.vtnrsc.DefaultVirtualPort.name ()
Returns the symbolic name for the virtualPort.
Returns
virtualPort name
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 106 of file DefaultVirtualPort.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
TenantNetworkId org.onosproject.vtnrsc.DefaultVirtualPort.networkId ()
Returns the network identifier.
Returns
tenantNetwork identifier
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 101 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
VirtualPortId org.onosproject.vtnrsc.DefaultVirtualPort.portId ()
Returns the virtualPort identifier.
Returns
virtualPort identifier
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 96 of file DefaultVirtualPort.java.
Collection<SecurityGroup> org.onosproject.vtnrsc.DefaultVirtualPort.securityGroups ()
Returns the security groups.
Returns
port security groups
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 171 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
State org.onosproject.vtnrsc.DefaultVirtualPort.state ()
Returns the state.
Returns
state
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 116 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
TenantId org.onosproject.vtnrsc.DefaultVirtualPort.tenantId ()
Returns the port tenantId.
Returns
port tenantId
Implements org.onosproject.vtnrsc.VirtualPort.
Definition at line 126 of file DefaultVirtualPort.java.
Referenced by org.onosproject.vtnrsc.DefaultVirtualPort.DefaultVirtualPort(), org.onosproject.vtnrsc.DefaultVirtualPort.hashCode(), and org.onosproject.vtnrsc.DefaultVirtualPort.toString().
String org.onosproject.vtnrsc.DefaultVirtualPort.toString ()
Definition at line 215 of file DefaultVirtualPort.java.
References org.onosproject.vtnrsc.DefaultVirtualPort.adminStateUp(), org.onosproject.vtnrsc.DefaultVirtualPort.allowedAddressPairs(), org.onosproject.vtnrsc.DefaultVirtualPort.bindingHostId(), org.onosproject.vtnrsc.DefaultVirtualPort.bindingVifDetails(), org.onosproject.vtnrsc.DefaultVirtualPort.bindingVifType(), org.onosproject.vtnrsc.DefaultVirtualPort.bindingVnicType(), org.onosproject.vtnrsc.DefaultVirtualPort.deviceId(), org.onosproject.vtnrsc.DefaultVirtualPort.deviceOwner(), org.onosproject.vtnrsc.DefaultVirtualPort.fixedIps(), org.onosproject.vtnrsc.DefaultVirtualPort.macAddress(), org.onosproject.vtnrsc.DefaultVirtualPort.name(), org.onosproject.vtnrsc.DefaultVirtualPort.networkId(), org.onosproject.vtnrsc.DefaultVirtualPort.securityGroups(), org.onosproject.vtnrsc.DefaultVirtualPort.state(), and org.onosproject.vtnrsc.DefaultVirtualPort.tenantId().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultVirtualPort.java