onos: org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask Class Reference
org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask Class Reference
Implements BGP MPLS protocol mask attribute.
Public Member Functions
BgpLinkAttrMplsProtocolMask (boolean bLdp, boolean bRsvpTe)
Constructor to initialize the values.
boolean ldpBit ()
Returns true if LDP bit is set.
boolean rsvpBit ()
Returns RSVP TE information.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpLinkAttrMplsProtocolMask of (final boolean bLdp, final boolean bRsvpTe)
Returns object of this class with specified values.
static BgpLinkAttrMplsProtocolMask read (ChannelBuffer cb) throws BgpParseException
Reads the BGP link attributes MPLS protocol mask.
Static Public Attributes
static final int ATTRLINK_MPLSPROTOMASK = 1094
static final int MASK_BYTE_LEN = 1
static final byte FIRST_BIT = (byte) 0x80
static final byte SECOND_BIT = 0x40
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP MPLS protocol mask attribute.
Definition at line 33 of file BgpLinkAttrMplsProtocolMask.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.BgpLinkAttrMplsProtocolMask (boolean bLdp, boolean bRsvpTe)
Constructor to initialize the values.
Parameters
bLdp boolean value true if LDP flag is available
bRsvpTe boolean value true if RSVP TE information is available
Definition at line 53 of file BgpLinkAttrMplsProtocolMask.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.equals(), and org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.of().
Member Function Documentation
int org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 154 of file BgpLinkAttrMplsProtocolMask.java.
boolean org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.equals (Object obj)
Definition at line 128 of file BgpLinkAttrMplsProtocolMask.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.BgpLinkAttrMplsProtocolMask().
short org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 118 of file BgpLinkAttrMplsProtocolMask.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.ATTRLINK_MPLSPROTOMASK.
int org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.hashCode ()
Definition at line 123 of file BgpLinkAttrMplsProtocolMask.java.
boolean org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.ldpBit ()
Returns true if LDP bit is set.
Returns
True if LDP information is set else false.
Definition at line 104 of file BgpLinkAttrMplsProtocolMask.java.
static BgpLinkAttrMplsProtocolMask org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.of (final boolean bLdp, final boolean bRsvpTe) static
Returns object of this class with specified values.
Parameters
bLdp boolean value true if LDP flag is available
bRsvpTe boolean value true if RSVP TE information is available
Returns
object of BgpLinkAttrMplsProtocolMask
Definition at line 65 of file BgpLinkAttrMplsProtocolMask.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.BgpLinkAttrMplsProtocolMask().
static BgpLinkAttrMplsProtocolMask org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.read (ChannelBuffer cb) throws BgpParseException static
Reads the BGP link attributes MPLS protocol mask.
Parameters
cb Channel buffer
Returns
object of type BgpLinkAttrMPLSProtocolMask
Exceptions
BgpParseException while parsing BgpLinkAttrMplsProtocolMask
Definition at line 77 of file BgpLinkAttrMplsProtocolMask.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.FIRST_BIT, org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.MASK_BYTE_LEN, org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.SECOND_BIT, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
boolean org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.rsvpBit ()
Returns RSVP TE information.
Returns
True if RSVP TE information is set else false.
Definition at line 113 of file BgpLinkAttrMplsProtocolMask.java.
String org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.toString ()
Definition at line 148 of file BgpLinkAttrMplsProtocolMask.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 142 of file BgpLinkAttrMplsProtocolMask.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.ATTRLINK_MPLSPROTOMASK = 1094 static
Definition at line 38 of file BgpLinkAttrMplsProtocolMask.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.getType().
final byte org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.FIRST_BIT = (byte) 0x80 static
Definition at line 44 of file BgpLinkAttrMplsProtocolMask.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.read().
final Logger org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpLinkAttrMplsProtocolMask.class)
Definition at line 35 of file BgpLinkAttrMplsProtocolMask.java.
final int org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.MASK_BYTE_LEN = 1 static
Definition at line 39 of file BgpLinkAttrMplsProtocolMask.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.read().
final byte org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.SECOND_BIT = 0x40 static
Definition at line 45 of file BgpLinkAttrMplsProtocolMask.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrMplsProtocolMask.read().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpLinkAttrMplsProtocolMask.java