onos: org.onosproject.bgpio.types.IPv6AddressTlv Class Reference
org.onosproject.bgpio.types.IPv6AddressTlv Class Reference
Provides Implementation of IPv6AddressTlv.
Public Member Functions
IPv6AddressTlv (Ip6Address address, short type)
Constructor to initialize parameters.
Ip6Address address ()
Returns Ipv6 address of interface/neighbor.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static IPv6AddressTlv read (ChannelBuffer cb, short type) throws BgpParseException
Reads the channel buffer and returns object of IPv6AddressTlv.
static IPv6AddressTlv of (final Ip6Address address, final short type)
Returns object of this class with specified values.
Detailed Description
Provides Implementation of IPv6AddressTlv.
Definition at line 32 of file IPv6AddressTlv.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.IPv6AddressTlv.IPv6AddressTlv (Ip6Address address, short type)
Constructor to initialize parameters.
Parameters
address Ipv6 address of interface/neighbor
type address type
Definition at line 44 of file IPv6AddressTlv.java.
References org.onosproject.bgpio.types.IPv6AddressTlv.address().
Referenced by org.onosproject.bgpio.types.IPv6AddressTlv.equals(), and org.onosproject.bgpio.types.IPv6AddressTlv.of().
Member Function Documentation
Ip6Address org.onosproject.bgpio.types.IPv6AddressTlv.address ()
Returns Ipv6 address of interface/neighbor.
Returns
Ipv6 address of interface/neighbor
Definition at line 54 of file IPv6AddressTlv.java.
Referenced by org.onosproject.bgpio.types.IPv6AddressTlv.compareTo(), org.onosproject.bgpio.types.IPv6AddressTlv.hashCode(), org.onosproject.bgpio.types.IPv6AddressTlv.IPv6AddressTlv(), org.onosproject.bgpio.types.IPv6AddressTlv.read(), and org.onosproject.bgpio.types.IPv6AddressTlv.toString().
int org.onosproject.bgpio.types.IPv6AddressTlv.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 118 of file IPv6AddressTlv.java.
References org.onosproject.bgpio.types.IPv6AddressTlv.address(), and org.onosproject.bgpio.types.IPv6AddressTlv.equals().
boolean org.onosproject.bgpio.types.IPv6AddressTlv.equals (Object obj)
Definition at line 69 of file IPv6AddressTlv.java.
References org.onosproject.bgpio.types.IPv6AddressTlv.IPv6AddressTlv().
Referenced by org.onosproject.bgpio.types.IPv6AddressTlv.compareTo().
short org.onosproject.bgpio.types.IPv6AddressTlv.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 59 of file IPv6AddressTlv.java.
int org.onosproject.bgpio.types.IPv6AddressTlv.hashCode ()
Definition at line 64 of file IPv6AddressTlv.java.
References org.onosproject.bgpio.types.IPv6AddressTlv.address().
static IPv6AddressTlv org.onosproject.bgpio.types.IPv6AddressTlv.of (final Ip6Address address, final short type) static
Returns object of this class with specified values.
Parameters
address Ipv6 interface/neighbor address
type says Ipv6 address of interface/neighbor tlv type
Returns
object of this class
Definition at line 113 of file IPv6AddressTlv.java.
References org.onosproject.bgpio.types.IPv6AddressTlv.IPv6AddressTlv().
static IPv6AddressTlv org.onosproject.bgpio.types.IPv6AddressTlv.read (ChannelBuffer cb, short type) throws BgpParseException static
Reads the channel buffer and returns object of IPv6AddressTlv.
Parameters
cb channelBuffer
type address type
Returns
object of IPv6AddressTlv
Exceptions
BgpParseException while parsing IPv6AddressTlv
Definition at line 97 of file IPv6AddressTlv.java.
References org.onosproject.bgpio.types.IPv6AddressTlv.address(), and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.IPv6AddressTlv.toString ()
Definition at line 126 of file IPv6AddressTlv.java.
References org.onosproject.bgpio.types.IPv6AddressTlv.address().
int org.onosproject.bgpio.types.IPv6AddressTlv.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 81 of file IPv6AddressTlv.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/IPv6AddressTlv.java