onos: org.onosproject.net.statistic.TypedFlowEntryWithLoad Class Reference
org.onosproject.net.statistic.TypedFlowEntryWithLoad Class Reference
Load of flow entry of flow live type.
Public Member Functions
TypedFlowEntryWithLoad (ConnectPoint cp, TypedStoredFlowEntry tfe, Load load)
Creates a new typed flow entry with load.
TypedFlowEntryWithLoad (ConnectPoint cp, TypedStoredFlowEntry tfe)
Creates a new typed flow entry with load.
TypedFlowEntryWithLoad (ConnectPoint cp, FlowEntry fe)
Creates a new typed flow entry with load.
ConnectPoint connectPoint ()
TypedStoredFlowEntry typedStoredFlowEntry ()
Load load ()
void setLoad (Load load)
Static Public Member Functions
static int shortPollInterval ()
Returns short polling interval.
static int midPollInterval ()
Returns mid polling interval.
static int longPollInterval ()
Returns long polling interval.
static int avgPollInterval ()
Returns average polling interval.
static long typedPollInterval (TypedStoredFlowEntry tfe)
Returns current typed flow entry's polling interval.
static TypedStoredFlowEntry newTypedStoredFlowEntry (FlowEntry fe)
Creates a new typed flow entry with the given flow entry fe.
Detailed Description
Load of flow entry of flow live type.
Definition at line 29 of file TypedFlowEntryWithLoad.java.
Constructor & Destructor Documentation
org.onosproject.net.statistic.TypedFlowEntryWithLoad.TypedFlowEntryWithLoad (ConnectPoint cp, TypedStoredFlowEntry tfe, Load load)
Creates a new typed flow entry with load.
Parameters
cp connect point
tfe typed flow entry
load load
Definition at line 46 of file TypedFlowEntryWithLoad.java.
References org.onosproject.net.statistic.TypedFlowEntryWithLoad.load().
org.onosproject.net.statistic.TypedFlowEntryWithLoad.TypedFlowEntryWithLoad (ConnectPoint cp, TypedStoredFlowEntry tfe)
Creates a new typed flow entry with load.
Parameters
cp connect point
tfe typed flow entry
Definition at line 58 of file TypedFlowEntryWithLoad.java.
References org.onosproject.net.flow.FlowEntry.bytes(), and org.onosproject.net.statistic.TypedFlowEntryWithLoad.typedPollInterval().
org.onosproject.net.statistic.TypedFlowEntryWithLoad.TypedFlowEntryWithLoad (ConnectPoint cp, FlowEntry fe)
Creates a new typed flow entry with load.
Parameters
cp connect point
fe flow entry
Definition at line 70 of file TypedFlowEntryWithLoad.java.
References org.onosproject.net.flow.FlowEntry.bytes(), org.onosproject.net.statistic.TypedFlowEntryWithLoad.newTypedStoredFlowEntry(), and org.onosproject.net.statistic.TypedFlowEntryWithLoad.typedPollInterval().
Member Function Documentation
static int org.onosproject.net.statistic.TypedFlowEntryWithLoad.avgPollInterval () static
Returns average polling interval.
Returns
average poll interval
Definition at line 121 of file TypedFlowEntryWithLoad.java.
ConnectPoint org.onosproject.net.statistic.TypedFlowEntryWithLoad.connectPoint ()
Definition at line 76 of file TypedFlowEntryWithLoad.java.
Load org.onosproject.net.statistic.TypedFlowEntryWithLoad.load ()
Definition at line 82 of file TypedFlowEntryWithLoad.java.
Referenced by org.onosproject.net.statistic.TypedFlowEntryWithLoad.setLoad(), and org.onosproject.net.statistic.TypedFlowEntryWithLoad.TypedFlowEntryWithLoad().
static int org.onosproject.net.statistic.TypedFlowEntryWithLoad.longPollInterval () static
Returns long polling interval.
Returns
long poll interval
Definition at line 112 of file TypedFlowEntryWithLoad.java.
static int org.onosproject.net.statistic.TypedFlowEntryWithLoad.midPollInterval () static
Returns mid polling interval.
Returns
mid poll interval
Definition at line 103 of file TypedFlowEntryWithLoad.java.
static TypedStoredFlowEntry org.onosproject.net.statistic.TypedFlowEntryWithLoad.newTypedStoredFlowEntry (FlowEntry fe) static
Creates a new typed flow entry with the given flow entry fe.
Parameters
fe flow entry
Returns
new typed flow entry
Definition at line 152 of file TypedFlowEntryWithLoad.java.
Referenced by org.onosproject.net.statistic.TypedFlowEntryWithLoad.TypedFlowEntryWithLoad().
void org.onosproject.net.statistic.TypedFlowEntryWithLoad.setLoad (Load load)
Definition at line 85 of file TypedFlowEntryWithLoad.java.
References org.onosproject.net.statistic.TypedFlowEntryWithLoad.load().
static int org.onosproject.net.statistic.TypedFlowEntryWithLoad.shortPollInterval () static
Returns short polling interval.
Returns
short poll interval
Definition at line 94 of file TypedFlowEntryWithLoad.java.
static long org.onosproject.net.statistic.TypedFlowEntryWithLoad.typedPollInterval (TypedStoredFlowEntry tfe) static
Returns current typed flow entry's polling interval.
Parameters
tfe typed flow entry
Returns
typed poll interval
Definition at line 131 of file TypedFlowEntryWithLoad.java.
References org.onosproject.net.flow.TypedStoredFlowEntry.flowLiveType().
Referenced by org.onosproject.net.statistic.TypedFlowEntryWithLoad.TypedFlowEntryWithLoad().
TypedStoredFlowEntry org.onosproject.net.statistic.TypedFlowEntryWithLoad.typedStoredFlowEntry ()
Definition at line 79 of file TypedFlowEntryWithLoad.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/statistic/TypedFlowEntryWithLoad.java