onos: org.onosproject.net.mcast.McastEvent Class Reference
org.onosproject.net.mcast.McastEvent Class Reference
An entity representing a multicast event.
Classes
enum Type
Public Member Functions
McastEvent (McastEvent.Type type, McastRoute subject, ConnectPoint sink, ConnectPoint source)
McastEvent (McastEvent.Type type, McastRoute subject, long time, ConnectPoint sink, ConnectPoint source)
Optional< ConnectPoint > sink ()
The sink which has been removed or added.
Optional< ConnectPoint > source ()
The source which has been removed or added.
String toString ()
Detailed Description
An entity representing a multicast event.
Event either add or remove sinks or sources.
Definition at line 31 of file McastEvent.java.
Constructor & Destructor Documentation
org.onosproject.net.mcast.McastEvent.McastEvent (McastEvent.Type type, McastRoute subject, ConnectPoint sink, ConnectPoint source)
Definition at line 75 of file McastEvent.java.
References org.onosproject.net.mcast.McastEvent.sink(), and org.onosproject.net.mcast.McastEvent.source().
org.onosproject.net.mcast.McastEvent.McastEvent (McastEvent.Type type, McastRoute subject, long time, ConnectPoint sink, ConnectPoint source)
Definition at line 83 of file McastEvent.java.
References org.onosproject.net.mcast.McastEvent.sink(), and org.onosproject.net.mcast.McastEvent.source().
Member Function Documentation
Optional<ConnectPoint> org.onosproject.net.mcast.McastEvent.sink ()
The sink which has been removed or added.
The field may not be set if the sink has not been detected yet or has been removed.
Returns
an optional connect point
Definition at line 97 of file McastEvent.java.
Referenced by org.onosproject.net.mcast.McastEvent.McastEvent(), and org.onosproject.net.mcast.McastEvent.toString().
Optional<ConnectPoint> org.onosproject.net.mcast.McastEvent.source ()
The source which has been removed or added.
Returns
an optional connect point
Definition at line 106 of file McastEvent.java.
Referenced by org.onosproject.net.mcast.McastEvent.McastEvent(), and org.onosproject.net.mcast.McastEvent.toString().
String org.onosproject.net.mcast.McastEvent.toString ()
Definition at line 111 of file McastEvent.java.
References org.onosproject.net.mcast.McastEvent.sink(), and org.onosproject.net.mcast.McastEvent.source().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/mcast/McastEvent.java