onos: org.onosproject.store.trivial.SimpleLeadershipManager Class Reference
org.onosproject.store.trivial.SimpleLeadershipManager Class Reference
A trivial implementation of the leadership service.
Public Member Functions
NodeId getLeader (String path)
Returns the current leader for the topic.
Leadership getLeadership (String path)
Returns the current leadership info for the topic.
Set< String > ownedTopics (NodeId nodeId)
Returns the set of topics owned by the specified node.
CompletableFuture< Leadership > runForLeadership (String path)
Joins the leadership contest.
CompletableFuture< Void > withdraw (String path)
Withdraws from a leadership contest.
Map< String, Leadership > getLeaderBoard ()
Returns the current leader board.
void addListener (LeadershipEventListener listener)
void removeListener (LeadershipEventListener listener)
Map< String, List< NodeId > > getCandidates ()
Returns the candidates for all known topics.
List< NodeId > getCandidates (String path)
Returns the candidates for a given topic.
boolean stepdown (String path)
If the local nodeId is the leader for specified topic, this method causes it to step down temporarily from leadership.
boolean makeTopCandidate (String path, NodeId nodeId)
Moves the specified nodeId to the top of the candidates list for the topic.
Detailed Description
A trivial implementation of the leadership service.
The service is not distributed, so it can assume there's a single leadership contender. This contender is always granted leadership whenever it asks.
Definition at line 49 of file SimpleLeadershipManager.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleLeadershipManager.addListener (LeadershipEventListener listener)
Definition at line 107 of file SimpleLeadershipManager.java.
Map<String, List<NodeId> > org.onosproject.store.trivial.SimpleLeadershipManager.getCandidates ()
Returns the candidates for all known topics.
Returns
A mapping from topics to corresponding list of candidates.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 117 of file SimpleLeadershipManager.java.
List<NodeId> org.onosproject.store.trivial.SimpleLeadershipManager.getCandidates (String path)
Returns the candidates for a given topic.
Parameters
path topic
Returns
A lists of NodeIds, which may be empty.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 122 of file SimpleLeadershipManager.java.
NodeId org.onosproject.store.trivial.SimpleLeadershipManager.getLeader (String path)
Returns the current leader for the topic.
Parameters
path topic
Returns
nodeId of the leader, null if so such topic exists.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 59 of file SimpleLeadershipManager.java.
References org.onosproject.cluster.ClusterService.getLocalNode().
Map<String, Leadership> org.onosproject.store.trivial.SimpleLeadershipManager.getLeaderBoard ()
Returns the current leader board.
Returns
mapping from topic to leadership info.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 100 of file SimpleLeadershipManager.java.
Leadership org.onosproject.store.trivial.SimpleLeadershipManager.getLeadership (String path)
Returns the current leadership info for the topic.
Parameters
path topic
Returns
leadership info or null if so such topic exists.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 64 of file SimpleLeadershipManager.java.
References org.onosproject.cluster.ClusterService.getLocalNode().
boolean org.onosproject.store.trivial.SimpleLeadershipManager.makeTopCandidate (String path, NodeId nodeId)
Moves the specified nodeId to the top of the candidates list for the topic.
If the node is not a candidate for this topic, this method will be a noop.
Parameters
path leadership topic
nodeId nodeId to make the top candidate
Returns
true if nodeId is now the top candidate, false otherwise
Implements org.onosproject.cluster.LeadershipService.
Definition at line 132 of file SimpleLeadershipManager.java.
Set<String> org.onosproject.store.trivial.SimpleLeadershipManager.ownedTopics (NodeId nodeId)
Returns the set of topics owned by the specified node.
Parameters
nodeId node Id.
Returns
set of topics for which this node is the current leader.
Implements org.onosproject.cluster.LeadershipService.
Definition at line 70 of file SimpleLeadershipManager.java.
void org.onosproject.store.trivial.SimpleLeadershipManager.removeListener (LeadershipEventListener listener)
Definition at line 112 of file SimpleLeadershipManager.java.
CompletableFuture<Leadership> org.onosproject.store.trivial.SimpleLeadershipManager.runForLeadership (String path)
Joins the leadership contest.
Parameters
path topic for which this controller node wishes to be a leader
Returns
Leadership
future
Implements org.onosproject.cluster.LeadershipService.
Definition at line 80 of file SimpleLeadershipManager.java.
References org.onosproject.cluster.ClusterService.getLocalNode(), and org.onosproject.cluster.LeadershipEvent.Type.LEADER_ELECTED.
boolean org.onosproject.store.trivial.SimpleLeadershipManager.stepdown (String path)
If the local nodeId is the leader for specified topic, this method causes it to step down temporarily from leadership.
The node will continue to be in contention for leadership and can potentially become the leader again if and when it becomes the highest priority candidate
If the local nodeId is not the leader, this method will make no changes and simply return false.
Parameters
path topic for which this controller node should give up leadership
Returns
true if this node stepped down from leadership, false otherwise
Implements org.onosproject.cluster.LeadershipService.
Definition at line 127 of file SimpleLeadershipManager.java.
CompletableFuture<Void> org.onosproject.store.trivial.SimpleLeadershipManager.withdraw (String path)
Withdraws from a leadership contest.
Parameters
path topic for which this controller node no longer wishes to be a leader
Returns
future that is successfully completed when withdraw is done
Implements org.onosproject.cluster.LeadershipService.
Definition at line 90 of file SimpleLeadershipManager.java.
References org.onosproject.cluster.ClusterService.getLocalNode(), and org.onosproject.cluster.LeadershipEvent.Type.LEADER_BOOTED.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleLeadershipManager.java