onos: org.onosproject.reactive.routing.ReactiveRoutingFib Class Reference
org.onosproject.reactive.routing.ReactiveRoutingFib Class Reference
FIB component for reactive routing intents.
Public Member Functions
ReactiveRoutingFib (ApplicationId appId, HostService hostService, RoutingConfigurationService configService, InterfaceService interfaceService, IntentSynchronizationService intentSynchronizer)
Class constructor.
void setUpConnectivityInternetToHost (IpAddress hostIpAddress)
Sets up connectivity for packet from Internet to a host in local SDN network.
void setUpConnectivityHostToInternet (IpAddress hostIp, IpPrefix prefix, IpAddress nextHopIpAddress)
Sets up connectivity for packet from a local host to the Internet.
void setUpConnectivityHostToHost (IpAddress dstIpAddress, IpAddress srcIpAddress, MacAddress srcMacAddress, ConnectPoint srcConnectPoint)
Sets up the connectivity for two hosts in local SDN network.
void updateExistingMp2pIntent (IpPrefix ipPrefix, ConnectPoint ingressConnectPoint)
Adds one new ingress connect point into ingress points of an existing intent and resubmits the new intent.
boolean mp2pIntentExists (IpPrefix ipPrefix)
Checks whether there is a MultiPointToSinglePointIntent in memory for a given IP prefix.
Static Protected Attributes
static final ImmutableList
< Constraint > CONSTRAINTS = ImmutableList.of(new PartialFailureConstraint())
Detailed Description
FIB component for reactive routing intents.
Definition at line 56 of file ReactiveRoutingFib.java.
Constructor & Destructor Documentation
org.onosproject.reactive.routing.ReactiveRoutingFib.ReactiveRoutingFib (ApplicationId appId, HostService hostService, RoutingConfigurationService configService, InterfaceService interfaceService, IntentSynchronizationService intentSynchronizer)
Class constructor.
Parameters
appId application ID to use to generate intents
hostService host service
configService routing configuration service
interfaceService interface service
intentSynchronizer intent synchronization service
Definition at line 82 of file ReactiveRoutingFib.java.
Member Function Documentation
boolean org.onosproject.reactive.routing.ReactiveRoutingFib.mp2pIntentExists (IpPrefix ipPrefix)
Checks whether there is a MultiPointToSinglePointIntent in memory for a given IP prefix.
Parameters
ipPrefix the IP prefix used to search the existing MultiPointToSinglePointIntent
Returns
true if there is a MultiPointToSinglePointIntent, otherwise false
Implements org.onosproject.routing.IntentRequestListener.
Definition at line 391 of file ReactiveRoutingFib.java.
Referenced by org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityHostToHost().
void org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityHostToHost (IpAddress dstIpAddress, IpAddress srcIpAddress, MacAddress srcMacAddress, ConnectPoint srcConnectPoint)
Sets up the connectivity for two hosts in local SDN network.
Parameters
dstIpAddress the destination IP address
srcIpAddress the source IP address
srcMacAddress the source MAC address
srcConnectPoint the connectPoint of the source host
Implements org.onosproject.routing.IntentRequestListener.
Definition at line 221 of file ReactiveRoutingFib.java.
References org.onosproject.net.host.HostService.getHostsByIp(), org.onosproject.reactive.routing.ReactiveRoutingFib.mp2pIntentExists(), and org.onosproject.reactive.routing.ReactiveRoutingFib.updateExistingMp2pIntent().
void org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityHostToInternet (IpAddress hostIp, IpPrefix prefix, IpAddress nextHopIpAddress)
Sets up connectivity for packet from a local host to the Internet.
Parameters
hostIp IP address of the local host
prefix external IP prefix that the host is talking to
nextHopIpAddress IP address of the next hop router for the prefix
Implements org.onosproject.routing.IntentRequestListener.
Definition at line 150 of file ReactiveRoutingFib.java.
References org.onlab.packet.VlanId.ANY, org.onosproject.reactive.routing.ReactiveRoutingFib.CONSTRAINTS, create-intent.egressPort, obeliskHostCheck.hosts, org.onlab.packet.VlanId.NONE, onosUploadBits.prefix, org.onlab.packet.Ethernet.TYPE_IPV4, and org.onlab.packet.Ethernet.TYPE_IPV6.
void org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityInternetToHost (IpAddress dstIpAddress)
Sets up connectivity for packet from Internet to a host in local SDN network.
Parameters
dstIpAddress IP address of destination host in local SDN network
Implements org.onosproject.routing.IntentRequestListener.
Definition at line 96 of file ReactiveRoutingFib.java.
References org.onosproject.reactive.routing.ReactiveRoutingFib.CONSTRAINTS, org.onosproject.net.host.HostService.getHostsByIp(), org.onlab.packet.IpAddress.isIp4(), org.onlab.packet.Ethernet.TYPE_IPV4, and org.onlab.packet.Ethernet.TYPE_IPV6.
void org.onosproject.reactive.routing.ReactiveRoutingFib.updateExistingMp2pIntent (IpPrefix ipPrefix, ConnectPoint ingressConnectPoint)
Adds one new ingress connect point into ingress points of an existing intent and resubmits the new intent.
If there is already an intent for an IP prefix in the system, we do not need to create a new one, we only need to update this existing intent by adding more ingress points.
Parameters
ipPrefix the IP prefix used to search the existing MultiPointToSinglePointIntent
ingressConnectPoint the ingress connect point to be added into the exiting intent
Implements org.onosproject.routing.IntentRequestListener.
Definition at line 331 of file ReactiveRoutingFib.java.
References org.onosproject.reactive.routing.ReactiveRoutingFib.CONSTRAINTS, and org.onosproject.net.intent.Intent.priority().
Referenced by org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityHostToHost().
Member Data Documentation
final ImmutableList<Constraint> org.onosproject.reactive.routing.ReactiveRoutingFib.CONSTRAINTS = ImmutableList.of(new PartialFailureConstraint()) static protected
Definition at line 61 of file ReactiveRoutingFib.java.
Referenced by org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityHostToInternet(), org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityInternetToHost(), and org.onosproject.reactive.routing.ReactiveRoutingFib.updateExistingMp2pIntent().
The documentation for this class was generated from the following file:
apps/reactive-routing/src/main/java/org/onosproject/reactive/routing/ReactiveRoutingFib.java