onos: org.onosproject.security.impl.SecurityModeManager Class Reference
org.onosproject.security.impl.SecurityModeManager Class Reference
Security-Mode ONOS management implementation.
Public Member Functions
void activate ()
void deactivate ()
boolean isSecured (ApplicationId appId)
Returns true if security policy has been enforced to specified application.
void review (ApplicationId appId)
Changes SecurityModeState of specified application to REVIEWED.
void acceptPolicy (ApplicationId appId)
Accepts and enforces security policy to specified application.
void register (ApplicationId appId)
Register application to SM-ONOS subsystem.
Map< Integer, List< Permission > > getPrintableSpecifiedPermissions (ApplicationId appId)
Returns sorted developer specified permission Map.
Map< Integer, List< Permission > > getPrintableGrantedPermissions (ApplicationId appId)
Returns sorted granted permission Map.
Map< Integer, List< Permission > > getPrintableRequestedPermissions (ApplicationId appId)
Returns sorted requested permission Map.
Protected Attributes
SecurityModeStore store
ApplicationAdminService appAdminService
LogReaderService logReaderService
EventDeliveryService eventDispatcher
final ListenerRegistry
< SecurityModeEvent,
SecurityModeListener > listenerRegistry = new ListenerRegistry<>()
Detailed Description
Security-Mode ONOS management implementation.
Note: Activating Security-Mode ONOS has significant performance implications in Drake. See the wiki for instructions on how to activate it.
Definition at line 70 of file SecurityModeManager.java.
Member Function Documentation
void org.onosproject.security.impl.SecurityModeManager.acceptPolicy (ApplicationId appId)
Accepts and enforces security policy to specified application.
Parameters
appId application identifier
Implements org.onosproject.security.SecurityAdminService.
Definition at line 146 of file SecurityModeManager.java.
References org.onosproject.security.store.SecurityModeStore.getState(), and org.onosproject.security.impl.SecurityModeManager.store.
void org.onosproject.security.impl.SecurityModeManager.activate ()
Definition at line 97 of file SecurityModeManager.java.
References org.onosproject.security.impl.SecurityModeManager.deactivate(), and org.onosproject.security.impl.SecurityModeManager.listenerRegistry.
void org.onosproject.security.impl.SecurityModeManager.deactivate ()
Definition at line 120 of file SecurityModeManager.java.
Referenced by org.onosproject.security.impl.SecurityModeManager.activate().
Map<Integer, List<Permission> > org.onosproject.security.impl.SecurityModeManager.getPrintableGrantedPermissions (ApplicationId appId)
Returns sorted granted permission Map.
Parameters
appId application identifier
Returns
Map of list of permissions sorted by permission type
Implements org.onosproject.security.SecurityAdminService.
Definition at line 164 of file SecurityModeManager.java.
References org.onosproject.security.impl.DefaultPolicyBuilder.convertToJavaPermissions(), org.onosproject.security.store.SecurityModeStore.getGrantedPermissions(), and org.onosproject.security.impl.SecurityModeManager.store.
Map<Integer, List<Permission> > org.onosproject.security.impl.SecurityModeManager.getPrintableRequestedPermissions (ApplicationId appId)
Returns sorted requested permission Map.
Parameters
appId application identifier
Returns
Map of list of permissions sorted by permission type
Implements org.onosproject.security.SecurityAdminService.
Definition at line 170 of file SecurityModeManager.java.
References org.onosproject.security.impl.DefaultPolicyBuilder.convertToJavaPermissions(), org.onosproject.security.store.SecurityModeStore.getRequestedPermissions(), and org.onosproject.security.impl.SecurityModeManager.store.
Map<Integer, List<Permission> > org.onosproject.security.impl.SecurityModeManager.getPrintableSpecifiedPermissions (ApplicationId appId)
Returns sorted developer specified permission Map.
Parameters
appId application identifier
Returns
Map of list of permissions sorted by permission type
Implements org.onosproject.security.SecurityAdminService.
Definition at line 159 of file SecurityModeManager.java.
boolean org.onosproject.security.impl.SecurityModeManager.isSecured (ApplicationId appId)
Returns true if security policy has been enforced to specified application.
Parameters
appId application identifier
Returns
true if secured.
Implements org.onosproject.security.SecurityAdminService.
Definition at line 129 of file SecurityModeManager.java.
References org.onosproject.security.store.SecurityModeStore.getState(), and org.onosproject.security.impl.SecurityModeManager.store.
void org.onosproject.security.impl.SecurityModeManager.register (ApplicationId appId)
Register application to SM-ONOS subsystem.
Parameters
appId application identifier
Implements org.onosproject.security.SecurityAdminService.
Definition at line 154 of file SecurityModeManager.java.
void org.onosproject.security.impl.SecurityModeManager.review (ApplicationId appId)
Changes SecurityModeState of specified application to REVIEWED.
Parameters
appId application identifier
Implements org.onosproject.security.SecurityAdminService.
Definition at line 138 of file SecurityModeManager.java.
References org.onosproject.security.store.SecurityModeStore.getState(), and org.onosproject.security.impl.SecurityModeManager.store.
Member Data Documentation
ApplicationAdminService org.onosproject.security.impl.SecurityModeManager.appAdminService protected
Definition at line 76 of file SecurityModeManager.java.
EventDeliveryService org.onosproject.security.impl.SecurityModeManager.eventDispatcher protected
Definition at line 82 of file SecurityModeManager.java.
final ListenerRegistry<SecurityModeEvent, SecurityModeListener> org.onosproject.security.impl.SecurityModeManager.listenerRegistry = new ListenerRegistry<>() protected
Definition at line 87 of file SecurityModeManager.java.
Referenced by org.onosproject.security.impl.SecurityModeManager.activate().
LogReaderService org.onosproject.security.impl.SecurityModeManager.logReaderService protected
Definition at line 79 of file SecurityModeManager.java.
SecurityModeStore org.onosproject.security.impl.SecurityModeManager.store protected
Definition at line 73 of file SecurityModeManager.java.
Referenced by org.onosproject.security.impl.SecurityModeManager.acceptPolicy(), org.onosproject.security.impl.SecurityModeManager.getPrintableGrantedPermissions(), org.onosproject.security.impl.SecurityModeManager.getPrintableRequestedPermissions(), org.onosproject.security.impl.SecurityModeManager.isSecured(), and org.onosproject.security.impl.SecurityModeManager.review().
The documentation for this class was generated from the following file:
core/security/src/main/java/org/onosproject/security/impl/SecurityModeManager.java