onos: org.onosproject.rest.IntentsResourceTest Class Reference
org.onosproject.rest.IntentsResourceTest Class Reference
Unit tests for Intents REST APIs.
Classes
class IntentJsonArrayMatcher
Hamcrest matcher to check that an intent is represented properly in a JSON array of intents.
class IntentJsonMatcher
Hamcrest matcher to check that an intent representation in JSON matches the actual intent.
Public Member Functions
void setUpTest ()
Initializes test mocks and environment.
void tearDownTest ()
Tears down and verifies test mocks and environment.
void testIntentsEmptyArray ()
Tests the result of the rest api GET when there are no intents.
void testIntentsArray ()
Tests the result of the rest api GET when intents are defined.
void testIntentsSingle ()
Tests the result of a rest api GET for a single intent.
void testBadGet ()
Tests that a fetch of a non-existent intent object throws an exception.
void testPost ()
Tests creating an intent with POST.
void testBadPost ()
Tests creating an intent with POST and illegal JSON.
void testRemove ()
Tests removing an intent with DELETE.
void testBadRemove ()
Tests removal of a non existent intent with DELETE.
Public Member Functions inherited from org.onosproject.rest.ResourceTest
int getPort (int defaultPort)
Assigns an available port for the test.
AppDescriptor configure ()
Detailed Description
Unit tests for Intents REST APIs.
Definition at line 72 of file IntentsResourceTest.java.
Member Function Documentation
void org.onosproject.rest.IntentsResourceTest.setUpTest ()
Initializes test mocks and environment.
Definition at line 242 of file IntentsResourceTest.java.
References org.onosproject.net.intent.IntentService.getIntents(), org.onosproject.net.intent.IntentService.getIntentState(), and org.onosproject.net.intent.IntentState.INSTALLED.
void org.onosproject.rest.IntentsResourceTest.tearDownTest ()
Tears down and verifies test mocks and environment.
Definition at line 266 of file IntentsResourceTest.java.
void org.onosproject.rest.IntentsResourceTest.testBadGet ()
Tests that a fetch of a non-existent intent object throws an exception.
Definition at line 363 of file IntentsResourceTest.java.
References org.onosproject.net.intent.IntentService.getIntent(), and org.onosproject.net.intent.Key.of().
void org.onosproject.rest.IntentsResourceTest.testBadPost ()
Tests creating an intent with POST and illegal JSON.
Definition at line 410 of file IntentsResourceTest.java.
void org.onosproject.rest.IntentsResourceTest.testBadRemove ()
Tests removal of a non existent intent with DELETE.
Definition at line 468 of file IntentsResourceTest.java.
References org.onosproject.core.CoreService.getAppId(), org.onosproject.net.intent.IntentService.getIntent(), and org.onosproject.net.intent.Key.of().
void org.onosproject.rest.IntentsResourceTest.testIntentsArray ()
Tests the result of the rest api GET when intents are defined.
Definition at line 286 of file IntentsResourceTest.java.
void org.onosproject.rest.IntentsResourceTest.testIntentsEmptyArray ()
Tests the result of the rest api GET when there are no intents.
Definition at line 275 of file IntentsResourceTest.java.
void org.onosproject.rest.IntentsResourceTest.testIntentsSingle ()
Tests the result of a rest api GET for a single intent.
Definition at line 319 of file IntentsResourceTest.java.
References org.onosproject.core.CoreService.getAppId(), org.onosproject.net.intent.IntentService.getIntent(), org.onosproject.core.ApplicationId.name(), and org.onosproject.net.intent.Key.of().
void org.onosproject.rest.IntentsResourceTest.testPost ()
Tests creating an intent with POST.
Definition at line 384 of file IntentsResourceTest.java.
References org.onosproject.core.CoreService.getAppId(), and create-flow.location.
void org.onosproject.rest.IntentsResourceTest.testRemove ()
Tests removing an intent with DELETE.
Definition at line 427 of file IntentsResourceTest.java.
References org.onosproject.core.CoreService.getAppId(), org.onosproject.net.intent.IntentService.getIntent(), and org.onosproject.net.intent.Key.of().
The documentation for this class was generated from the following file:
web/api/src/test/java/org/onosproject/rest/IntentsResourceTest.java