onos: org.onosproject.store.trivial.SimpleApplicationStore Class Reference
org.onosproject.store.trivial.SimpleApplicationStore Class Reference
Manages inventory of network control applications.
Public Member Functions
void activate ()
void deactivate ()
Set< Application > getApplications ()
Returns the set of all installed applications.
ApplicationId getId (String name)
Returns the registered id of the application with the given name.
Application getApplication (ApplicationId appId)
Returns the application with the supplied application identifier.
ApplicationState getState (ApplicationId appId)
Returns the current application state.
Application create (InputStream appDescStream)
Creates the application from the specified application descriptor input stream.
void remove (ApplicationId appId)
Removes the specified application.
void activate (ApplicationId appId)
Mark the application as active.
void deactivate (ApplicationId appId)
Mark the application as deactivated.
Set< Permission > getPermissions (ApplicationId appId)
Returns the permissions granted to the applications.
void setPermissions (ApplicationId appId, Set< Permission > permissions)
Updates the permissions granted to the applications.
Public Member Functions inherited from org.onosproject.common.app.ApplicationArchive
String getRootPath ()
Returns the root directory where apps directory is contained.
Set< String > getApplicationNames ()
Returns the set of installed application names.
long getUpdateTime (String appName)
Returns the timestamp in millis since start of epoch, of when the specified application was last modified or changed state.
ApplicationDescription getApplicationDescription (String appName)
Loads the application descriptor from the specified application archive stream and saves the stream in the appropriate application archive directory.
synchronized ApplicationDescription saveApplication (InputStream stream)
Loads the application descriptor from the specified application archive stream and saves the stream in the appropriate application archive directory.
synchronized void purgeApplication (String appName)
Purges the application archive directory.
synchronized InputStream getApplicationInputStream (String appName)
Returns application archive stream for the specified application.
ApplicationRole getRole (String value)
Protected Attributes
ApplicationIdStore idStore
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.common.app.ApplicationArchive
void setRootPath (String root)
Sets the root directory where apps directory is contained.
boolean setActive (String appName)
Marks the app as active by creating token file in the app directory.
boolean clearActive (String appName)
Clears the app as active by deleting token file in the app directory.
boolean updateTime (String appName)
Updates the time-stamp of the app descriptor file.
boolean isActive (String appName)
Indicates whether the app was marked as active by checking for token file.
Detailed Description
Manages inventory of network control applications.
Definition at line 52 of file SimpleApplicationStore.java.
Member Function Documentation
void org.onosproject.store.trivial.SimpleApplicationStore.activate ()
Definition at line 65 of file SimpleApplicationStore.java.
void org.onosproject.store.trivial.SimpleApplicationStore.activate (ApplicationId appId)
Mark the application as active.
Parameters
appId application identifier
Implements org.onosproject.app.ApplicationStore.
Definition at line 140 of file SimpleApplicationStore.java.
References org.onosproject.core.ApplicationId.name(), and org.onosproject.common.app.ApplicationArchive.setActive().
Application org.onosproject.store.trivial.SimpleApplicationStore.create (InputStream appDescStream)
Creates the application from the specified application descriptor input stream.
Parameters
appDescStream application archive input stream
Returns
application descriptor
Implements org.onosproject.app.ApplicationStore.
Definition at line 115 of file SimpleApplicationStore.java.
References org.onosproject.app.ApplicationDescription.features(), org.onosproject.app.ApplicationDescription.origin(), org.onosproject.app.ApplicationDescription.permissions(), org.onosproject.common.app.ApplicationArchive.saveApplication(), and org.onosproject.app.ApplicationDescription.version().
void org.onosproject.store.trivial.SimpleApplicationStore.deactivate ()
Definition at line 87 of file SimpleApplicationStore.java.
void org.onosproject.store.trivial.SimpleApplicationStore.deactivate (ApplicationId appId)
Mark the application as deactivated.
Parameters
appId application identifier
Implements org.onosproject.app.ApplicationStore.
Definition at line 150 of file SimpleApplicationStore.java.
References org.onosproject.common.app.ApplicationArchive.clearActive(), and org.onosproject.core.ApplicationId.name().
Application org.onosproject.store.trivial.SimpleApplicationStore.getApplication (ApplicationId appId)
Returns the application with the supplied application identifier.
Parameters
appId application identifier
Returns
application descriptor
Implements org.onosproject.app.ApplicationStore.
Definition at line 105 of file SimpleApplicationStore.java.
Referenced by org.onosproject.store.trivial.SimpleApplicationStore.setPermissions().
Set<Application> org.onosproject.store.trivial.SimpleApplicationStore.getApplications ()
Returns the set of all installed applications.
Returns
set of installed apps
Implements org.onosproject.app.ApplicationStore.
Definition at line 95 of file SimpleApplicationStore.java.
ApplicationId org.onosproject.store.trivial.SimpleApplicationStore.getId (String name)
Returns the registered id of the application with the given name.
Parameters
name application name
Returns
registered application id
Implements org.onosproject.app.ApplicationStore.
Definition at line 100 of file SimpleApplicationStore.java.
References create-flow.name.
Referenced by metro.FabricDomain.build().
Set<Permission> org.onosproject.store.trivial.SimpleApplicationStore.getPermissions (ApplicationId appId)
Returns the permissions granted to the applications.
Parameters
appId application identifier
Returns
set of granted permissions
Implements org.onosproject.app.ApplicationStore.
Definition at line 160 of file SimpleApplicationStore.java.
ApplicationState org.onosproject.store.trivial.SimpleApplicationStore.getState (ApplicationId appId)
Returns the current application state.
Parameters
appId application identifier
Returns
application state
Implements org.onosproject.app.ApplicationStore.
Definition at line 110 of file SimpleApplicationStore.java.
void org.onosproject.store.trivial.SimpleApplicationStore.remove (ApplicationId appId)
Removes the specified application.
Parameters
appId application identifier
Implements org.onosproject.app.ApplicationStore.
Definition at line 130 of file SimpleApplicationStore.java.
References org.onosproject.core.Application.id(), and org.onosproject.common.app.ApplicationArchive.purgeApplication().
void org.onosproject.store.trivial.SimpleApplicationStore.setPermissions (ApplicationId appId, Set< Permission > permissions)
Updates the permissions granted to the applications.
Parameters
appId application identifier
permissions set of granted permissions
Implements org.onosproject.app.ApplicationStore.
Definition at line 165 of file SimpleApplicationStore.java.
References org.onosproject.store.trivial.SimpleApplicationStore.getApplication().
Member Data Documentation
ApplicationIdStore org.onosproject.store.trivial.SimpleApplicationStore.idStore protected
Definition at line 62 of file SimpleApplicationStore.java.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/store/trivial/SimpleApplicationStore.java