onos: org.onosproject.ui.table.TableModel Class Reference
org.onosproject.ui.table.TableModel Class Reference
A simple model of table data.
Classes
class Row
Model of a row.
enum SortDir
Designates sorting direction.
Public Member Functions
TableModel (String...columnIds)
Constructs a table (devoid of data) with the given column IDs.
int rowCount ()
Returns the number of rows in this table model.
int columnCount ()
Returns the number of columns in this table model.
String[] getColumnIds ()
Returns the array of column IDs for this table model.
Row[] getRows ()
Returns the raw Row representation of the rows in this table.
void setComparator (String columnId, CellComparator comparator)
Sets a cell comparator for the specified column.
void setFormatter (String columnId, CellFormatter formatter)
Sets a cell formatter for the specified column.
CellFormatter getFormatter (String columnId)
Returns the cell formatter to use on values in the specified column.
Row addRow ()
Adds a row to the table model.
void sort (String columnId, SortDir dir)
Sorts the table rows based on the specified column, in the specified direction.
Static Public Member Functions
static SortDir sortDir (String s)
Returns the appropriate sort direction for the given string.
Detailed Description
A simple model of table data.
Note that this is not a full MVC type model; the expected usage pattern is to create an empty table, add rows (by consulting the business model), sort rows (based on client request parameters), and finally produce the sorted list of rows.
The table also provides a mechanism for defining how cell values for a particular column should be formatted into strings, to help facilitate the encoding of the table data into a JSON structure.
Note that it is expected that all values for a particular column will be the same class.
Definition at line 50 of file TableModel.java.
Constructor & Destructor Documentation
org.onosproject.ui.table.TableModel.TableModel (String... columnIds)
Constructs a table (devoid of data) with the given column IDs.
Parameters
columnIds column identifiers
Definition at line 67 of file TableModel.java.
References find-link-in-cluster.length.
Member Function Documentation
Row org.onosproject.ui.table.TableModel.addRow ()
Adds a row to the table model.
Returns
the row, for chaining
Definition at line 179 of file TableModel.java.
int org.onosproject.ui.table.TableModel.columnCount ()
Returns the number of columns in this table model.
Returns
number of columns
Definition at line 100 of file TableModel.java.
References find-link-in-cluster.length.
Referenced by org.onosproject.ui.table.TableModelTest.basic(), and org.onosproject.ui.table.TableModel.Row.getAsFormattedStrings().
String [] org.onosproject.ui.table.TableModel.getColumnIds ()
Returns the array of column IDs for this table model.
Implementation note: we are knowingly passing you a reference to our internal array to avoid copying. Don't mess with it. It's your table you'll break if you do!
Returns
the column identifiers
Definition at line 113 of file TableModel.java.
Referenced by org.onosproject.ui.table.TableModelTest.getColumnIds().
CellFormatter org.onosproject.ui.table.TableModel.getFormatter (String columnId)
Returns the cell formatter to use on values in the specified column.
Parameters
columnId column identifier
Returns
an appropriate cell formatter
Definition at line 168 of file TableModel.java.
Row [] org.onosproject.ui.table.TableModel.getRows ()
Returns the raw Row representation of the rows in this table.
Returns
raw table rows
Definition at line 122 of file TableModel.java.
Referenced by org.onosproject.ui.table.TableUtils.generateArrayNode().
int org.onosproject.ui.table.TableModel.rowCount ()
Returns the number of rows in this table model.
Returns
number of rows
Definition at line 91 of file TableModel.java.
Referenced by org.onosproject.ui.table.TableModelTest.basic(), org.onosproject.ui.table.TableModelTest.emptyRow(), and org.onosproject.ui.table.TableModelTest.simpleRow().
void org.onosproject.ui.table.TableModel.setComparator (String columnId, CellComparator comparator)
Sets a cell comparator for the specified column.
Parameters
columnId column identifier
comparator comparator to use
Definition at line 132 of file TableModel.java.
void org.onosproject.ui.table.TableModel.setFormatter (String columnId, CellFormatter formatter)
Sets a cell formatter for the specified column.
Parameters
columnId column identifier
formatter formatter to use
Definition at line 156 of file TableModel.java.
void org.onosproject.ui.table.TableModel.sort (String columnId, SortDir dir)
Sorts the table rows based on the specified column, in the specified direction.
Parameters
columnId column identifier
dir sort direction
Definition at line 192 of file TableModel.java.
static SortDir org.onosproject.ui.table.TableModel.sortDir (String s) static
Returns the appropriate sort direction for the given string.
The expected strings are "asc" for ascending and "desc" for descending. Any other value will default to ascending.
Parameters
s sort direction string encoding
Returns
sort direction
Definition at line 301 of file TableModel.java.
References org.onosproject.ui.table.TableModel.SortDir.ASC, and org.onosproject.ui.table.TableModel.SortDir.DESC.
Referenced by org.onosproject.ui.table.TableModelTest.sortDirAsc(), org.onosproject.ui.table.TableModelTest.sortDirDesc(), org.onosproject.ui.table.TableModelTest.sortDirNull(), and org.onosproject.ui.table.TableModelTest.sortDirOther().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/table/TableModel.java