onos: org.onosproject.ovsdb.controller.OvsdbPort Class Reference
org.onosproject.ovsdb.controller.OvsdbPort Class Reference
The class representing a ovsdb port.
Public Member Functions
OvsdbPort (OvsdbPortNumber portNumber, OvsdbPortName portName)
Constructor from OvsdbPortNumber portNumber, OvsdbPortName portName.
OvsdbPortNumber portNumber ()
Gets the port number of port.
OvsdbPortName portName ()
Gets the port name of port.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
The class representing a ovsdb port.
This class is immutable.
Definition at line 26 of file OvsdbPort.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.controller.OvsdbPort.OvsdbPort (OvsdbPortNumber portNumber, OvsdbPortName portName)
Constructor from OvsdbPortNumber portNumber, OvsdbPortName portName.
Parameters
portNumber the portNumber to use
portName the portName to use
Definition at line 37 of file OvsdbPort.java.
References org.onosproject.ovsdb.controller.OvsdbPort.portName(), and org.onosproject.ovsdb.controller.OvsdbPort.portNumber().
Referenced by org.onosproject.ovsdb.controller.OvsdbPort.equals().
Member Function Documentation
boolean org.onosproject.ovsdb.controller.OvsdbPort.equals (Object obj)
Definition at line 68 of file OvsdbPort.java.
References org.onosproject.ovsdb.controller.OvsdbPort.OvsdbPort().
int org.onosproject.ovsdb.controller.OvsdbPort.hashCode ()
Definition at line 63 of file OvsdbPort.java.
References org.onosproject.ovsdb.controller.OvsdbPort.portName(), and org.onosproject.ovsdb.controller.OvsdbPort.portNumber().
OvsdbPortName org.onosproject.ovsdb.controller.OvsdbPort.portName ()
Gets the port name of port.
Returns
the port name of port
Definition at line 58 of file OvsdbPort.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbPort.hashCode(), org.onosproject.ovsdb.controller.OvsdbPort.OvsdbPort(), and org.onosproject.ovsdb.controller.OvsdbPort.toString().
OvsdbPortNumber org.onosproject.ovsdb.controller.OvsdbPort.portNumber ()
Gets the port number of port.
Returns
the port number of port
Definition at line 49 of file OvsdbPort.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbPort.hashCode(), and org.onosproject.ovsdb.controller.OvsdbPort.OvsdbPort().
String org.onosproject.ovsdb.controller.OvsdbPort.toString ()
Definition at line 81 of file OvsdbPort.java.
References org.onosproject.ovsdb.controller.OvsdbPort.portName().
The documentation for this class was generated from the following file:
protocols/ovsdb/api/src/main/java/org/onosproject/ovsdb/controller/OvsdbPort.java