onos: org.onosproject.pcepio.types.ISISAreaIdentifierTlv Class Reference
org.onosproject.pcepio.types.ISISAreaIdentifierTlv Class Reference
Provides ISIS Area Identifier.
Public Member Functions
ISISAreaIdentifierTlv (byte[] rawValue, short hLength)
Constructor to initialize rawValue.
byte[] getValue ()
Returns value of ISIS-Area-Identifier.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static ISISAreaIdentifierTlv of (final byte[] raw, short hLength)
Returns newly created ISISAreaIdentifierTlv object.
static PcepValueType read (ChannelBuffer c, short hLength)
Reads the channel buffer and returns object of ISISAreaIdentifierTlv.
Static Public Attributes
static final short TYPE = 107
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(ISISAreaIdentifierTlv.class)
Detailed Description
Provides ISIS Area Identifier.
Definition at line 31 of file ISISAreaIdentifierTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.ISISAreaIdentifierTlv.ISISAreaIdentifierTlv (byte[] rawValue, short hLength)
Constructor to initialize rawValue.
Parameters
rawValue ISIS-Area-Identifier
hLength length
Definition at line 56 of file ISISAreaIdentifierTlv.java.
Referenced by org.onosproject.pcepio.types.ISISAreaIdentifierTlv.equals(), org.onosproject.pcepio.types.ISISAreaIdentifierTlv.of(), and org.onosproject.pcepio.types.ISISAreaIdentifierTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.ISISAreaIdentifierTlv.equals (Object obj)
Definition at line 107 of file ISISAreaIdentifierTlv.java.
References org.onosproject.pcepio.types.ISISAreaIdentifierTlv.ISISAreaIdentifierTlv().
short org.onosproject.pcepio.types.ISISAreaIdentifierTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 97 of file ISISAreaIdentifierTlv.java.
short org.onosproject.pcepio.types.ISISAreaIdentifierTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 92 of file ISISAreaIdentifierTlv.java.
References org.onosproject.pcepio.types.ISISAreaIdentifierTlv.TYPE.
byte [] org.onosproject.pcepio.types.ISISAreaIdentifierTlv.getValue ()
Returns value of ISIS-Area-Identifier.
Returns
byte array of rawValue
Definition at line 82 of file ISISAreaIdentifierTlv.java.
PcepVersion org.onosproject.pcepio.types.ISISAreaIdentifierTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 87 of file ISISAreaIdentifierTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.ISISAreaIdentifierTlv.hashCode ()
Definition at line 102 of file ISISAreaIdentifierTlv.java.
static ISISAreaIdentifierTlv org.onosproject.pcepio.types.ISISAreaIdentifierTlv.of (final byte[] raw, short hLength) static
Returns newly created ISISAreaIdentifierTlv object.
Parameters
raw ISIS-Area-Identifier
hLength length
Returns
object of ISISAreaIdentifierTlv
Definition at line 73 of file ISISAreaIdentifierTlv.java.
References org.onosproject.pcepio.types.ISISAreaIdentifierTlv.ISISAreaIdentifierTlv().
static PcepValueType org.onosproject.pcepio.types.ISISAreaIdentifierTlv.read (ChannelBuffer c, short hLength) static
Reads the channel buffer and returns object of ISISAreaIdentifierTlv.
Parameters
c input channel buffer
hLength length
Returns
object of ISISAreaIdentifierTlv
Definition at line 134 of file ISISAreaIdentifierTlv.java.
References org.onosproject.pcepio.types.ISISAreaIdentifierTlv.ISISAreaIdentifierTlv().
String org.onosproject.pcepio.types.ISISAreaIdentifierTlv.toString ()
Definition at line 141 of file ISISAreaIdentifierTlv.java.
References org.onosproject.pcepio.types.ISISAreaIdentifierTlv.TYPE.
int org.onosproject.pcepio.types.ISISAreaIdentifierTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 119 of file ISISAreaIdentifierTlv.java.
References org.onosproject.pcepio.types.ISISAreaIdentifierTlv.TYPE.
Member Data Documentation
final Logger org.onosproject.pcepio.types.ISISAreaIdentifierTlv.log = LoggerFactory.getLogger(ISISAreaIdentifierTlv.class) static protected
Definition at line 43 of file ISISAreaIdentifierTlv.java.
final short org.onosproject.pcepio.types.ISISAreaIdentifierTlv.TYPE = 107 static
Definition at line 45 of file ISISAreaIdentifierTlv.java.
Referenced by org.onosproject.pcepio.types.ISISAreaIdentifierTlv.getType(), org.onosproject.pcepio.types.ISISAreaIdentifierTlv.toString(), and org.onosproject.pcepio.types.ISISAreaIdentifierTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/ISISAreaIdentifierTlv.java