onos: org.onosproject.incubator.net.virtual .DefaultVirtualDevice Class Reference
org.onosproject.incubator.net.virtual .DefaultVirtualDevice Class Reference
Default representation of a virtual device.
Public Member Functions
DefaultVirtualDevice (NetworkId networkId, DeviceId id)
Creates a network element attributed to the specified provider.
NetworkId networkId ()
Returns the network identifier to which this virtual element belongs.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default representation of a virtual device.
Definition at line 30 of file DefaultVirtualDevice.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.virtual .DefaultVirtualDevice.DefaultVirtualDevice (NetworkId networkId, DeviceId id)
Creates a network element attributed to the specified provider.
Parameters
networkId network identifier
id device identifier
Definition at line 43 of file DefaultVirtualDevice.java.
References org.onosproject.incubator.net.virtual .DefaultVirtualDevice.networkId().
Referenced by org.onosproject.incubator.net.virtual .DefaultVirtualDevice.equals().
Member Function Documentation
boolean org.onosproject.incubator.net.virtual .DefaultVirtualDevice.equals (Object obj)
Definition at line 60 of file DefaultVirtualDevice.java.
References org.onosproject.incubator.net.virtual .DefaultVirtualDevice.DefaultVirtualDevice().
int org.onosproject.incubator.net.virtual .DefaultVirtualDevice.hashCode ()
Definition at line 55 of file DefaultVirtualDevice.java.
References org.onosproject.incubator.net.virtual .NetworkId.hashCode(), and org.onosproject.incubator.net.virtual .DefaultVirtualDevice.networkId().
NetworkId org.onosproject.incubator.net.virtual .DefaultVirtualDevice.networkId ()
Returns the network identifier to which this virtual element belongs.
Returns
network identifier
Implements org.onosproject.incubator.net.virtual .VirtualElement.
Definition at line 50 of file DefaultVirtualDevice.java.
Referenced by org.onosproject.incubator.net.virtual .DefaultVirtualDevice.DefaultVirtualDevice(), org.onosproject.incubator.net.virtual .DefaultVirtualDevice.hashCode(), and org.onosproject.incubator.net.virtual .DefaultVirtualDevice.toString().
String org.onosproject.incubator.net.virtual .DefaultVirtualDevice.toString ()
Definition at line 72 of file DefaultVirtualDevice.java.
References org.onosproject.incubator.net.virtual .DefaultVirtualDevice.networkId().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/virtual/DefaultVirtualDevice.java