onos: org.onosproject.rest.HostResourceTest Class Reference
org.onosproject.rest.HostResourceTest Class Reference
Simple example on how to write a JAX-RS unit test using Jersey test framework.
Classes
class HostJsonArrayMatcher
Hamcrest matcher to check that a host is represented properly in a JSON array of hosts.
class HostJsonMatcher
Hamcrest matcher to check that a host representation in JSON matches the actual host.
Public Member Functions
void setUpTest ()
Initializes test mocks and environment.
void tearDownTest ()
Verifies mocks.
void testHostsEmptyArray ()
Tests the result of the rest api GET when there are no hosts.
void testHostsArray ()
Tests the result of the rest api GET when hosts are defined.
void testSingleHostByIdFetch ()
Tests fetch of one host by Id.
void testSingleHostByMacAndVlanFetch ()
Tests fetch of one host by mac and vlan.
void testBadGet ()
Tests that a fetch of a non-existent object throws an exception.
void testPost ()
Tests post of a single host via JSON stream.
Public Member Functions inherited from org.onosproject.rest.ResourceTest
int getPort (int defaultPort)
Assigns an available port for the test.
AppDescriptor configure ()
Detailed Description
Simple example on how to write a JAX-RS unit test using Jersey test framework.
A base class should/will be created to provide further assistance for testing.
Definition at line 71 of file HostResourceTest.java.
Member Function Documentation
void org.onosproject.rest.HostResourceTest.setUpTest ()
Initializes test mocks and environment.
Definition at line 81 of file HostResourceTest.java.
References org.onosproject.net.host.HostService.getHosts().
void org.onosproject.rest.HostResourceTest.tearDownTest ()
Verifies mocks.
Definition at line 99 of file HostResourceTest.java.
void org.onosproject.rest.HostResourceTest.testBadGet ()
Tests that a fetch of a non-existent object throws an exception.
Definition at line 345 of file HostResourceTest.java.
References org.onosproject.net.host.HostService.getHost(), and org.onosproject.net.HostId.hostId().
void org.onosproject.rest.HostResourceTest.testHostsArray ()
Tests the result of the rest api GET when hosts are defined.
Definition at line 253 of file HostResourceTest.java.
References org.onosproject.net.DeviceId.deviceId(), org.onosproject.net.HostId.hostId(), and org.onlab.packet.IpAddress.valueOf().
void org.onosproject.rest.HostResourceTest.testHostsEmptyArray ()
Tests the result of the rest api GET when there are no hosts.
Definition at line 242 of file HostResourceTest.java.
void org.onosproject.rest.HostResourceTest.testPost ()
Tests post of a single host via JSON stream.
Definition at line 366 of file HostResourceTest.java.
References create-flow.location.
void org.onosproject.rest.HostResourceTest.testSingleHostByIdFetch ()
Tests fetch of one host by Id.
Definition at line 293 of file HostResourceTest.java.
References org.onosproject.net.DeviceId.deviceId(), org.onosproject.net.host.HostService.getHost(), and org.onosproject.net.HostId.hostId().
void org.onosproject.rest.HostResourceTest.testSingleHostByMacAndVlanFetch ()
Tests fetch of one host by mac and vlan.
Definition at line 319 of file HostResourceTest.java.
References org.onosproject.net.DeviceId.deviceId(), org.onosproject.net.host.HostService.getHost(), and org.onosproject.net.HostId.hostId().
The documentation for this class was generated from the following file:
web/api/src/test/java/org/onosproject/rest/HostResourceTest.java