onos: org.onosproject.netconf.ctl.NetconfControllerImpl Class Reference
org.onosproject.netconf.ctl.NetconfControllerImpl Class Reference
The implementation of NetconfController.
Public Member Functions
void activate (ComponentContext context)
void deactivate ()
void addDeviceListener (NetconfDeviceListener listener)
Adds Device Event Listener.
void removeDeviceListener (NetconfDeviceListener listener)
Removes Device Listener.
NetconfDevice getNetconfDevice (DeviceId deviceInfo)
Gets a Netconf Device by node identifier.
NetconfDevice getNetconfDevice (IpAddress ip, int port)
Gets a Netconf Device by node identifier.
NetconfDevice connectDevice (NetconfDeviceInfo deviceInfo)
Tries to connect to a specific NETCONF device, if the connection is succesful it creates and adds the device to the ONOS core as a NetconfDevice.
void removeDevice (NetconfDeviceInfo deviceInfo)
Removes a Netconf device.
Map< DeviceId, NetconfDevice > getDevicesMap ()
Gets all the nodes information.
Public Attributes
Map< DeviceId, NetconfDevice > netconfDeviceMap = new ConcurrentHashMap<>()
Static Public Attributes
static final Logger log
Protected Attributes
Set< NetconfDeviceListener > netconfDeviceListeners = new CopyOnWriteArraySet<>()
Detailed Description
The implementation of NetconfController.
Definition at line 44 of file NetconfControllerImpl.java.
Member Function Documentation
void org.onosproject.netconf.ctl.NetconfControllerImpl.activate (ComponentContext context)
Definition at line 54 of file NetconfControllerImpl.java.
void org.onosproject.netconf.ctl.NetconfControllerImpl.addDeviceListener (NetconfDeviceListener listener)
Adds Device Event Listener.
Parameters
listener node listener
Implements org.onosproject.netconf.NetconfController.
Definition at line 65 of file NetconfControllerImpl.java.
References org.onosproject.netconf.ctl.NetconfControllerImpl.netconfDeviceListeners.
NetconfDevice org.onosproject.netconf.ctl.NetconfControllerImpl.connectDevice (NetconfDeviceInfo deviceInfo)
Tries to connect to a specific NETCONF device, if the connection is succesful it creates and adds the device to the ONOS core as a NetconfDevice.
Parameters
deviceInfo info about the device to add
Returns
NetconfDevice Netconf device
Implements org.onosproject.netconf.NetconfController.
Definition at line 94 of file NetconfControllerImpl.java.
References org.onosproject.netconf.NetconfDeviceInfo.getDeviceId(), and org.onosproject.netconf.ctl.NetconfControllerImpl.netconfDeviceMap.
void org.onosproject.netconf.ctl.NetconfControllerImpl.deactivate ()
Definition at line 59 of file NetconfControllerImpl.java.
Map<DeviceId, NetconfDevice> org.onosproject.netconf.ctl.NetconfControllerImpl.getDevicesMap ()
Gets all the nodes information.
Returns
map of devices
Implements org.onosproject.netconf.NetconfController.
Definition at line 138 of file NetconfControllerImpl.java.
References org.onosproject.netconf.ctl.NetconfControllerImpl.netconfDeviceMap.
NetconfDevice org.onosproject.netconf.ctl.NetconfControllerImpl.getNetconfDevice (DeviceId deviceInfo)
Gets a Netconf Device by node identifier.
Parameters
deviceInfo node identifier
Returns
NetconfDevice Netconf device
Implements org.onosproject.netconf.NetconfController.
Definition at line 77 of file NetconfControllerImpl.java.
NetconfDevice org.onosproject.netconf.ctl.NetconfControllerImpl.getNetconfDevice (IpAddress ip, int port)
Gets a Netconf Device by node identifier.
Parameters
ip device ip
port device port
Returns
NetconfDevice Netconf device
Implements org.onosproject.netconf.NetconfController.
Definition at line 82 of file NetconfControllerImpl.java.
References create-flow.device, org.onosproject.netconf.ctl.NetconfControllerImpl.netconfDeviceMap, and org.onlab.packet.IpAddress.valueOf().
void org.onosproject.netconf.ctl.NetconfControllerImpl.removeDevice (NetconfDeviceInfo deviceInfo)
Removes a Netconf device.
Parameters
deviceInfo info about the device to remove
Implements org.onosproject.netconf.NetconfController.
Definition at line 105 of file NetconfControllerImpl.java.
References org.onosproject.netconf.NetconfDeviceInfo.getDeviceId(), and org.onosproject.netconf.ctl.NetconfControllerImpl.netconfDeviceMap.
void org.onosproject.netconf.ctl.NetconfControllerImpl.removeDeviceListener (NetconfDeviceListener listener)
Removes Device Listener.
Parameters
listener node listener
Implements org.onosproject.netconf.NetconfController.
Definition at line 72 of file NetconfControllerImpl.java.
Member Data Documentation
final Logger org.onosproject.netconf.ctl.NetconfControllerImpl.log static
Initial value:
= LoggerFactory
            .getLogger(NetconfControllerImpl.class)
Definition at line 46 of file NetconfControllerImpl.java.
Set<NetconfDeviceListener> org.onosproject.netconf.ctl.NetconfControllerImpl.netconfDeviceListeners = new CopyOnWriteArraySet<>() protected
Definition at line 51 of file NetconfControllerImpl.java.
Referenced by org.onosproject.netconf.ctl.NetconfControllerImpl.addDeviceListener().
Map<DeviceId, NetconfDevice> org.onosproject.netconf.ctl.NetconfControllerImpl.netconfDeviceMap = new ConcurrentHashMap<>()
Definition at line 49 of file NetconfControllerImpl.java.
Referenced by org.onosproject.netconf.ctl.NetconfControllerImpl.connectDevice(), org.onosproject.netconf.ctl.NetconfControllerImpl.getDevicesMap(), org.onosproject.netconf.ctl.NetconfControllerImpl.getNetconfDevice(), and org.onosproject.netconf.ctl.NetconfControllerImpl.removeDevice().
The documentation for this class was generated from the following file:
protocols/netconf/ctl/src/main/java/org/onosproject/netconf/ctl/NetconfControllerImpl.java