onos: org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1 Class Reference
Provides PCEP Error Object.
Classes
class Builder
Builder class for PCEP error object.
Public Member Functions
PcepErrorObjectVer1 (PcepObjectHeader errorObjHeader, byte yErrorType, byte yErrorValue, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize variables.
void setLspObjHeader (PcepObjectHeader obj)
sets Object Header.
void setErrorType (byte yErrorType)
Sets Error Type in Error Object.
void setErrorValue (byte yErrorValue)
Sets Error Value in Error Object.
PcepObjectHeader getErrorObjHeader ()
returns object header.
int getErrorType ()
Returns Error Type in Error Object.
byte getErrorValue ()
Returns Error Value in Error Object.
LinkedList< PcepValueType > getOptionalTlv ()
Returns Optional Tlvs in Error Object.
void setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets Optional Tlvs in Error Object.
int write (ChannelBuffer cb) throws PcepParseException
Writes the Error Object into channel buffer.
String toString ()
Static Public Member Functions
static PcepErrorObject read (ChannelBuffer cb)
Reads from channel buffer and returns object of PcepErrorObject.
Static Public Attributes
static final byte ERROR_OBJ_TYPE = 1
static final byte ERROR_OBJ_CLASS = 13
static final byte ERROR_OBJECT_VERSION = 1
static final short ERROR_OBJ_MINIMUM_LENGTH = 8
static final int OBJECT_HEADER_LENGTH = 4
static final PcepObjectHeader DEFAULT_ERROR_OBJECT_HEADER
Protected Member Functions
int packOptionalTlv (ChannelBuffer cb)
Pack the Optional tlvs.
Static Protected Member Functions
static LinkedList< PcepValueType > parseOptionalTlv (ChannelBuffer cb)
returns Linked list of optional tlvs.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepErrorObjectVer1.class)
Detailed Description
Provides PCEP Error Object.
Definition at line 34 of file PcepErrorObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.PcepErrorObjectVer1 (PcepObjectHeader errorObjHeader, byte yErrorType, byte yErrorValue, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize variables.
Parameters
errorObjHeader ERROR Object header
yErrorType Error Type
yErrorValue Error Value
llOptionalTlv list of optional TLV
Definition at line 76 of file PcepErrorObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.read().
Member Function Documentation
PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.getErrorObjHeader ()
returns object header.
Returns
errorObjHeader Error-Object header
Definition at line 108 of file PcepErrorObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.getErrorType ()
Returns Error Type in Error Object.
Returns
Error Type in Error Object
Implements org.onosproject.pcepio.protocol.PcepErrorObject.
Definition at line 113 of file PcepErrorObjectVer1.java.
byte org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.getErrorValue ()
Returns Error Value in Error Object.
Returns
Error Value
Implements org.onosproject.pcepio.protocol.PcepErrorObject.
Definition at line 118 of file PcepErrorObjectVer1.java.
LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.getOptionalTlv ()
Returns Optional Tlvs in Error Object.
Returns
list of Optional Tlvs in Error Object
Implements org.onosproject.pcepio.protocol.PcepErrorObject.
Definition at line 123 of file PcepErrorObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.packOptionalTlv (ChannelBuffer cb) protected
Pack the Optional tlvs.
Parameters
cb channel buffer.
Returns
writer index.
Definition at line 223 of file PcepErrorObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.write().
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.parseOptionalTlv (ChannelBuffer cb) static protected
returns Linked list of optional tlvs.
Parameters
cb channel buffer.
Returns
Linked list of optional tlvs
Definition at line 165 of file PcepErrorObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.read().
static PcepErrorObject org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.read (ChannelBuffer cb) static
Reads from channel buffer and returns object of PcepErrorObject.
Parameters
cb of channel buffer.
Returns
object of PCEP-ERROR-OBJECT
Definition at line 138 of file PcepErrorObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.OBJECT_HEADER_LENGTH, org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.parseOptionalTlv(), and org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.PcepErrorObjectVer1().
void org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.setErrorType (byte value)
Sets Error Type in Error Object.
Parameters
value Error Type
Implements org.onosproject.pcepio.protocol.PcepErrorObject.
Definition at line 94 of file PcepErrorObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.setErrorValue (byte value)
Sets Error Value in Error Object.
Parameters
value Error Value
Implements org.onosproject.pcepio.protocol.PcepErrorObject.
Definition at line 99 of file PcepErrorObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.setLspObjHeader (PcepObjectHeader obj)
sets Object Header.
Parameters
obj Error-Object header
Definition at line 89 of file PcepErrorObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets Optional Tlvs in Error Object.
Parameters
llOptionalTlv list of Optional Tlvs
Implements org.onosproject.pcepio.protocol.PcepErrorObject.
Definition at line 128 of file PcepErrorObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.toString ()
Definition at line 336 of file PcepErrorObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the Error Object into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException while writing Error Object into ChannelBuffer
Implements org.onosproject.pcepio.protocol.PcepErrorObject.
Definition at line 176 of file PcepErrorObjectVer1.java.
References find-link-in-cluster.length, and org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.packOptionalTlv().
Member Data Documentation
final PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.DEFAULT_ERROR_OBJECT_HEADER static
Initial value:
= new PcepObjectHeader(ERROR_OBJ_CLASS,
            ERROR_OBJ_TYPE, PcepObjectHeader.REQ_OBJ_OPTIONAL_PROCESS, PcepObjectHeader.RSP_OBJ_PROCESSED,
            ERROR_OBJ_MINIMUM_LENGTH)
Definition at line 58 of file PcepErrorObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.ERROR_OBJ_CLASS = 13 static
Definition at line 52 of file PcepErrorObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorVer1.parseErrObjList(), org.onosproject.pcepio.protocol.ver1.PcepErrorInfoVer1.read(), and org.onosproject.pcepio.protocol.ver1.PcepErrorVer1.read().
final short org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.ERROR_OBJ_MINIMUM_LENGTH = 8 static
Definition at line 55 of file PcepErrorObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.ERROR_OBJ_TYPE = 1 static
Definition at line 51 of file PcepErrorObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorVer1.parseErrObjList().
final byte org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.ERROR_OBJECT_VERSION = 1 static
Definition at line 53 of file PcepErrorObjectVer1.java.
final Logger org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.log = LoggerFactory.getLogger(PcepErrorObjectVer1.class) static protected
Definition at line 49 of file PcepErrorObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.OBJECT_HEADER_LENGTH = 4 static
Definition at line 56 of file PcepErrorObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepErrorObjectVer1.read().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepErrorObjectVer1.java