onos: org.onosproject.routing.config.BgpConfig Class Reference
org.onosproject.routing.config.BgpConfig Class Reference
Configuration object for BGP config.
Classes
class BgpSpeakerConfig
Configuration for a BGP speaker.
Public Member Functions
Set< BgpSpeakerConfig > bgpSpeakers ()
Gets the set of configured BGP speakers.
BgpSpeakerConfig getSpeakerWithName (String name)
Examines whether a name of BGP speaker exists in configuration.
void addSpeaker (BgpSpeakerConfig speaker)
Adds BGP speaker to configuration.
void removeSpeaker (String speakerName)
Removes BGP speaker from configuration.
void addPeerToSpeaker (String speakerName, IpAddress peerAddress)
Adds peering address to BGP speaker.
BgpSpeakerConfig getSpeakerFromPeer (IpAddress peerAddress)
Finds BGP speaker peering with a given external peer.
void removePeerFromSpeaker (BgpSpeakerConfig speaker, IpAddress peerAddress)
Removes peering address from BGP speaker.
Static Public Attributes
static final String SPEAKERS = "bgpSpeakers"
static final String CONNECT_POINT = "connectPoint"
static final String NAME = "name"
static final String PEERS = "peers"
Detailed Description
Configuration object for BGP config.
Definition at line 38 of file BgpConfig.java.
Member Function Documentation
void org.onosproject.routing.config.BgpConfig.addPeerToSpeaker (String speakerName, IpAddress peerAddress)
Adds peering address to BGP speaker.
Parameters
speakerName name of BGP speaker
peerAddress peering address to be added
Definition at line 143 of file BgpConfig.java.
References org.onosproject.routing.config.BgpConfig.NAME, org.onosproject.routing.config.BgpConfig.PEERS, org.onosproject.routing.config.BgpConfig.SPEAKERS, and org.onlab.packet.IpAddress.toString().
void org.onosproject.routing.config.BgpConfig.addSpeaker (BgpSpeakerConfig speaker)
Adds BGP speaker to configuration.
Parameters
speaker BGP speaker configuration entry
Definition at line 102 of file BgpConfig.java.
References org.onosproject.routing.config.BgpConfig.bgpSpeakers(), org.onosproject.routing.config.BgpConfig.CONNECT_POINT, org.onosproject.routing.config.BgpConfig.NAME, org.onosproject.routing.config.BgpConfig.PEERS, and org.onosproject.routing.config.BgpConfig.SPEAKERS.
Set<BgpSpeakerConfig> org.onosproject.routing.config.BgpConfig.bgpSpeakers ()
Gets the set of configured BGP speakers.
Returns
BGP speakers
Definition at line 52 of file BgpConfig.java.
References org.onosproject.routing.config.BgpConfig.CONNECT_POINT, org.onosproject.net.ConnectPoint.deviceConnectPoint(), create-flow.name, org.onosproject.routing.config.BgpConfig.NAME, org.onosproject.routing.config.BgpConfig.PEERS, org.onosproject.routing.config.BgpConfig.SPEAKERS, and org.onlab.packet.IpAddress.valueOf().
Referenced by org.onosproject.routing.config.BgpConfig.addSpeaker(), org.onosproject.routing.config.BgpConfig.getSpeakerFromPeer(), org.onosproject.routing.config.BgpConfig.getSpeakerWithName(), org.onosproject.routing.config.BgpConfigTest.testAddSpeaker(), org.onosproject.routing.config.BgpConfigTest.testAddSpeakerToEmpty(), org.onosproject.routing.config.BgpConfigTest.testBgpSpeakers(), org.onosproject.routing.config.BgpConfigTest.testEmptyBgpSpeakers(), org.onosproject.sdnip.PeerConnectivityManagerTest.testNullBgpSpeakers(), org.onosproject.routing.config.BgpConfigTest.testRemoveExistingSpeaker(), and org.onosproject.routing.config.BgpConfigTest.testRemoveInexistingSpeaker().
BgpSpeakerConfig org.onosproject.routing.config.BgpConfig.getSpeakerFromPeer (IpAddress peerAddress)
Finds BGP speaker peering with a given external peer.
Parameters
peerAddress peering address to be removed
Returns
speaker
Definition at line 165 of file BgpConfig.java.
References org.onosproject.routing.config.BgpConfig.bgpSpeakers().
Referenced by org.onosproject.routing.config.BgpConfigTest.testGetSpeakerFromPeer().
BgpSpeakerConfig org.onosproject.routing.config.BgpConfig.getSpeakerWithName (String name)
Examines whether a name of BGP speaker exists in configuration.
Parameters
name name of BGP speaker being search
Returns
speaker
Definition at line 88 of file BgpConfig.java.
References org.onosproject.routing.config.BgpConfig.bgpSpeakers().
Referenced by org.onosproject.routing.config.BgpConfigTest.testAddExistingPeerToSpeaker(), org.onosproject.routing.config.BgpConfigTest.testAddPeerToSpeaker(), org.onosproject.routing.config.BgpConfigTest.testGetSpeakerWithName(), org.onosproject.routing.config.BgpConfigTest.testRemoveExistingPeerFromSpeaker(), and org.onosproject.routing.config.BgpConfigTest.testRemoveNonExistingPeerFromSpeaker().
void org.onosproject.routing.config.BgpConfig.removePeerFromSpeaker (BgpSpeakerConfig speaker, IpAddress peerAddress)
Removes peering address from BGP speaker.
Parameters
speaker BGP speaker configuration entries
peerAddress peering address to be removed
Definition at line 180 of file BgpConfig.java.
References org.onosproject.routing.config.BgpConfig.NAME, org.onosproject.routing.config.BgpConfig.PEERS, org.onosproject.routing.config.BgpConfig.SPEAKERS, and org.onlab.packet.IpAddress.toString().
void org.onosproject.routing.config.BgpConfig.removeSpeaker (String speakerName)
Removes BGP speaker from configuration.
Parameters
speakerName BGP speaker name
Definition at line 125 of file BgpConfig.java.
References org.onosproject.routing.config.BgpConfig.NAME, and org.onosproject.routing.config.BgpConfig.SPEAKERS.
Member Data Documentation
final String org.onosproject.routing.config.BgpConfig.CONNECT_POINT = "connectPoint" static
Definition at line 41 of file BgpConfig.java.
Referenced by org.onosproject.routing.config.BgpConfig.addSpeaker(), and org.onosproject.routing.config.BgpConfig.bgpSpeakers().
final String org.onosproject.routing.config.BgpConfig.NAME = "name" static
Definition at line 42 of file BgpConfig.java.
Referenced by org.onosproject.routing.config.BgpConfig.addPeerToSpeaker(), org.onosproject.routing.config.BgpConfig.addSpeaker(), org.onosproject.routing.config.BgpConfig.bgpSpeakers(), org.onosproject.routing.config.BgpConfig.removePeerFromSpeaker(), and org.onosproject.routing.config.BgpConfig.removeSpeaker().
final String org.onosproject.routing.config.BgpConfig.PEERS = "peers" static
Definition at line 43 of file BgpConfig.java.
Referenced by org.onosproject.routing.config.BgpConfig.addPeerToSpeaker(), org.onosproject.routing.config.BgpConfig.addSpeaker(), org.onosproject.routing.config.BgpConfig.bgpSpeakers(), and org.onosproject.routing.config.BgpConfig.removePeerFromSpeaker().
final String org.onosproject.routing.config.BgpConfig.SPEAKERS = "bgpSpeakers" static
Definition at line 40 of file BgpConfig.java.
Referenced by org.onosproject.routing.config.BgpConfig.addPeerToSpeaker(), org.onosproject.routing.config.BgpConfig.addSpeaker(), org.onosproject.routing.config.BgpConfig.bgpSpeakers(), org.onosproject.routing.config.BgpConfig.removePeerFromSpeaker(), and org.onosproject.routing.config.BgpConfig.removeSpeaker().
The documentation for this class was generated from the following file:
apps/routing-api/src/main/java/org/onosproject/routing/config/BgpConfig.java