onos: org.onosproject.dhcp.IpAssignment Class Reference
org.onosproject.dhcp.IpAssignment Class Reference
Stores the MAC ID to IP Address mapping details.
Classes
enum AssignmentStatus
class Builder
IPAssignment Builder.
Public Member Functions
Ip4Address ipAddress ()
Returns the IP Address of the IP assignment.
Date timestamp ()
Returns the timestamp of the IP assignment.
AssignmentStatus assignmentStatus ()
Returns the assignment status of the IP assignment.
int leasePeriod ()
Returns the lease period of the IP assignment.
int leasePeriodMs ()
Returns the lease period of the IP assignment.
Ip4Address subnetMask ()
Ip4Address dhcpServer ()
Ip4Address routerAddress ()
Ip4Address domainServer ()
boolean rangeNotEnforced ()
String toString ()
Static Public Member Functions
static Builder builder ()
Creates and returns a new builder instance.
static Builder builder (IpAssignment assignment)
Creates and returns a new builder instance that clones an existing IPAssignment.
Detailed Description
Stores the MAC ID to IP Address mapping details.
Definition at line 28 of file IpAssignment.java.
Member Function Documentation
AssignmentStatus org.onosproject.dhcp.IpAssignment.assignmentStatus ()
Returns the assignment status of the IP assignment.
Returns
the assignment status
Definition at line 122 of file IpAssignment.java.
Referenced by org.onosproject.dhcp.IpAssignment.toString().
static Builder org.onosproject.dhcp.IpAssignment.builder () static
Creates and returns a new builder instance.
Returns
new builder
Definition at line 184 of file IpAssignment.java.
static Builder org.onosproject.dhcp.IpAssignment.builder (IpAssignment assignment) static
Creates and returns a new builder instance that clones an existing IPAssignment.
Parameters
assignment ip address assignment
Returns
new builder
Definition at line 194 of file IpAssignment.java.
Ip4Address org.onosproject.dhcp.IpAssignment.dhcpServer ()
Definition at line 148 of file IpAssignment.java.
Referenced by org.onosproject.dhcp.IpAssignment.toString().
Ip4Address org.onosproject.dhcp.IpAssignment.domainServer ()
Definition at line 156 of file IpAssignment.java.
Referenced by org.onosproject.dhcp.IpAssignment.toString().
Ip4Address org.onosproject.dhcp.IpAssignment.ipAddress ()
Returns the IP Address of the IP assignment.
Returns
the IP address
Definition at line 104 of file IpAssignment.java.
Referenced by org.onosproject.dhcp.IpAssignment.toString().
int org.onosproject.dhcp.IpAssignment.leasePeriod ()
Returns the lease period of the IP assignment.
Returns
the lease period in seconds
Definition at line 131 of file IpAssignment.java.
Referenced by org.onosproject.dhcp.IpAssignment.toString().
int org.onosproject.dhcp.IpAssignment.leasePeriodMs ()
Returns the lease period of the IP assignment.
Returns
the lease period in milliseconds
Definition at line 140 of file IpAssignment.java.
boolean org.onosproject.dhcp.IpAssignment.rangeNotEnforced ()
Definition at line 160 of file IpAssignment.java.
Referenced by org.onosproject.dhcp.IpAssignment.toString().
Ip4Address org.onosproject.dhcp.IpAssignment.routerAddress ()
Definition at line 152 of file IpAssignment.java.
Referenced by org.onosproject.dhcp.IpAssignment.toString().
Ip4Address org.onosproject.dhcp.IpAssignment.subnetMask ()
Definition at line 144 of file IpAssignment.java.
Referenced by org.onosproject.dhcp.IpAssignment.toString().
Date org.onosproject.dhcp.IpAssignment.timestamp ()
Returns the timestamp of the IP assignment.
Returns
the timestamp
Definition at line 113 of file IpAssignment.java.
Referenced by org.onosproject.dhcp.IpAssignment.toString().
String org.onosproject.dhcp.IpAssignment.toString ()
Definition at line 165 of file IpAssignment.java.
References org.onosproject.dhcp.IpAssignment.assignmentStatus(), org.onosproject.dhcp.IpAssignment.dhcpServer(), org.onosproject.dhcp.IpAssignment.domainServer(), org.onosproject.dhcp.IpAssignment.ipAddress(), org.onosproject.dhcp.IpAssignment.leasePeriod(), org.onosproject.dhcp.IpAssignment.rangeNotEnforced(), org.onosproject.dhcp.IpAssignment.routerAddress(), org.onosproject.dhcp.IpAssignment.subnetMask(), and org.onosproject.dhcp.IpAssignment.timestamp().
Referenced by org.onosproject.dhcp.IpAssignmentTest.testToString().
The documentation for this class was generated from the following file:
apps/dhcp/api/src/main/java/org/onosproject/dhcp/IpAssignment.java