onos: org.onosproject.net.meter.MeterOperation Class Reference
org.onosproject.net.meter.MeterOperation Class Reference
Representation of an operation on the meter table.
Classes
enum Type
Tyoe of meter operation.
Public Member Functions
MeterOperation (Meter meter, Type type)
Type type ()
Returns the type of operation.
Meter meter ()
Returns the meter.
String toString ()
boolean equals (Object o)
int hashCode ()
Detailed Description
Representation of an operation on the meter table.
Definition at line 24 of file MeterOperation.java.
Constructor & Destructor Documentation
org.onosproject.net.meter.MeterOperation.MeterOperation (Meter meter, Type type)
Definition at line 40 of file MeterOperation.java.
References org.onosproject.net.meter.MeterOperation.meter(), and org.onosproject.net.meter.MeterOperation.type().
Referenced by org.onosproject.net.meter.MeterOperation.equals().
Member Function Documentation
boolean org.onosproject.net.meter.MeterOperation.equals (Object o)
Definition at line 72 of file MeterOperation.java.
References org.onosproject.net.meter.MeterOperation.meter(), org.onosproject.net.meter.MeterOperation.MeterOperation(), and org.onosproject.net.meter.MeterOperation.type().
int org.onosproject.net.meter.MeterOperation.hashCode ()
Definition at line 85 of file MeterOperation.java.
References org.onosproject.net.meter.MeterOperation.meter(), and org.onosproject.net.meter.MeterOperation.type().
Meter org.onosproject.net.meter.MeterOperation.meter ()
Returns the meter.
Returns
a meter
Definition at line 59 of file MeterOperation.java.
Referenced by org.onosproject.net.meter.MeterOperation.equals(), org.onosproject.net.meter.MeterOperation.hashCode(), org.onosproject.net.meter.MeterOperation.MeterOperation(), and org.onosproject.net.meter.MeterOperation.toString().
String org.onosproject.net.meter.MeterOperation.toString ()
Definition at line 64 of file MeterOperation.java.
References org.onosproject.net.meter.MeterOperation.meter(), and org.onosproject.net.meter.MeterOperation.type().
Type org.onosproject.net.meter.MeterOperation.type ()
Returns the type of operation.
Returns
type
Definition at line 50 of file MeterOperation.java.
Referenced by org.onosproject.net.meter.MeterOperation.equals(), org.onosproject.net.meter.MeterOperation.hashCode(), org.onosproject.net.meter.MeterOperation.MeterOperation(), and org.onosproject.net.meter.MeterOperation.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/meter/MeterOperation.java