onos: org.onosproject.routing.RouteEntry Class Reference
org.onosproject.routing.RouteEntry Class Reference
Represents a route entry for an IP prefix.
Public Member Functions
RouteEntry (IpPrefix prefix, IpAddress nextHop)
Class constructor.
IpAddress.Version version ()
Returns the IP version of the route.
boolean isIp4 ()
Tests whether the IP version of this address is IPv4.
boolean isIp6 ()
Tests whether the IP version of this address is IPv6.
IpPrefix prefix ()
Returns the IP prefix of the route.
IpAddress nextHop ()
Returns the next hop IP address for the route.
boolean equals (Object other)
int hashCode ()
String toString ()
Static Public Member Functions
static String createBinaryString (IpPrefix ipPrefix)
Creates the binary string representation of an IP prefix.
Detailed Description
Represents a route entry for an IP prefix.
Definition at line 29 of file RouteEntry.java.
Constructor & Destructor Documentation
org.onosproject.routing.RouteEntry.RouteEntry (IpPrefix prefix, IpAddress nextHop)
Class constructor.
Parameters
prefix the IP prefix of the route
nextHop the next hop IP address for the route
Definition at line 39 of file RouteEntry.java.
Referenced by org.onosproject.routing.RouteEntry.equals().
Member Function Documentation
static String org.onosproject.routing.RouteEntry.createBinaryString (IpPrefix ipPrefix) static
Creates the binary string representation of an IP prefix.
The prefix can be either IPv4 or IPv6. The string length is equal to the prefix length + 1.
For each string, we put a extra "0" in the front. The purpose of doing this is to store the default route inside InvertedRadixTree.
Parameters
ipPrefix the IP prefix to use
Returns
the binary string representation
Definition at line 100 of file RouteEntry.java.
Referenced by org.onosproject.routing.RouteEntryTest.testCreateBinaryString().
boolean org.onosproject.routing.RouteEntry.equals (Object other)
Definition at line 120 of file RouteEntry.java.
References org.onosproject.routing.RouteEntry.equals(), onosUploadBits.prefix, and org.onosproject.routing.RouteEntry.RouteEntry().
Referenced by org.onosproject.routing.RouteEntry.equals().
int org.onosproject.routing.RouteEntry.hashCode ()
Definition at line 139 of file RouteEntry.java.
References org.onosproject.routing.RouteEntry.nextHop(), and org.onosproject.routing.RouteEntry.prefix().
boolean org.onosproject.routing.RouteEntry.isIp4 ()
Tests whether the IP version of this address is IPv4.
Returns
true if the IP version of this address is IPv4, otherwise false.
Definition at line 58 of file RouteEntry.java.
boolean org.onosproject.routing.RouteEntry.isIp6 ()
Tests whether the IP version of this address is IPv6.
Returns
true if the IP version of this address is IPv6, otherwise false.
Definition at line 67 of file RouteEntry.java.
IpAddress org.onosproject.routing.RouteEntry.nextHop ()
Returns the next hop IP address for the route.
Returns
the next hop IP address for the route
Definition at line 85 of file RouteEntry.java.
Referenced by org.onosproject.routing.RouteEntry.hashCode(), org.onosproject.routing.bgp.BgpRouteEntryTest.testGetFields(), org.onosproject.routing.RouteEntry.toString(), and org.onosproject.routing.bgp.BgpRouteEntry.toString().
IpPrefix org.onosproject.routing.RouteEntry.prefix ()
Returns the IP prefix of the route.
Returns
the IP prefix of the route
Definition at line 76 of file RouteEntry.java.
Referenced by org.onosproject.routing.RouteEntry.hashCode(), org.onosproject.routing.bgp.BgpRouteEntryTest.testGetFields(), org.onosproject.routing.RouteEntry.toString(), and org.onosproject.routing.bgp.BgpRouteEntry.toString().
String org.onosproject.routing.RouteEntry.toString ()
Definition at line 144 of file RouteEntry.java.
References org.onosproject.routing.RouteEntry.nextHop(), and org.onosproject.routing.RouteEntry.prefix().
IpAddress.Version org.onosproject.routing.RouteEntry.version ()
Returns the IP version of the route.
Returns
the IP version of the route
Definition at line 49 of file RouteEntry.java.
The documentation for this class was generated from the following file:
apps/routing-api/src/main/java/org/onosproject/routing/RouteEntry.java