onos: org.onosproject.bgp.controller.impl.BgpSessionInfoImpl Class Reference
org.onosproject.bgp.controller.impl.BgpSessionInfoImpl Class Reference
Class maintains BGP peer session info.
Public Member Functions
BgpSessionInfoImpl (BgpId remoteBgpId, BgpVersion remoteBgpVersion, long remoteBgpASNum, short remoteBgpholdTime, int remoteBgpIdentifier, short negotiatedholdTime, boolean isIbgpSession)
Initialize session info.
boolean isIbgpSession ()
Gets the bgp session type iBGP/eBGP.
short negotiatedholdTime ()
Gets the negotiated hold time for the session.
BgpId remoteBgpId ()
Gets the BGP ID of BGP peer.
BgpVersion remoteBgpVersion ()
Gets the BGP version of peer.
long remoteBgpASNum ()
Gets the BGP remote bgp AS number.
short remoteBgpHoldTime ()
Gets the BGP peer hold time.
int remoteBgpIdentifier ()
Gets the BGP version for this bgp peer.
Protected Attributes
final Logger log = LoggerFactory.getLogger(BgpSessionInfoImpl.class)
Detailed Description
Class maintains BGP peer session info.
Definition at line 25 of file BgpSessionInfoImpl.java.
Constructor & Destructor Documentation
org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.BgpSessionInfoImpl (BgpId remoteBgpId, BgpVersion remoteBgpVersion, long remoteBgpASNum, short remoteBgpholdTime, int remoteBgpIdentifier, short negotiatedholdTime, boolean isIbgpSession)
Initialize session info.
Parameters
remoteBgpId remote peer id
remoteBgpVersion remote peer version
remoteBgpASNum remote peer AS number
remoteBgpholdTime remote peer hold time
remoteBgpIdentifier remote peer identifier
negotiatedholdTime negotiated hold time
isIbgpSession session type ibgp/ebgp
Definition at line 47 of file BgpSessionInfoImpl.java.
References org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.isIbgpSession(), org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.negotiatedholdTime(), org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.remoteBgpASNum(), org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.remoteBgpId(), org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.remoteBgpIdentifier(), and org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.remoteBgpVersion().
Member Function Documentation
boolean org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.isIbgpSession ()
Gets the bgp session type iBGP/eBGP.
Returns
isiBGPSession, true if session is of type internal, otherwise false.
Implements org.onosproject.bgp.controller.BgpSessionInfo.
Definition at line 60 of file BgpSessionInfoImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.BgpSessionInfoImpl().
short org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.negotiatedholdTime ()
Gets the negotiated hold time for the session.
Returns
negotiated hold time.
Implements org.onosproject.bgp.controller.BgpSessionInfo.
Definition at line 65 of file BgpSessionInfoImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.BgpSessionInfoImpl().
long org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.remoteBgpASNum ()
Gets the BGP remote bgp AS number.
Returns
remoteBgpASNum peer AS number.
Implements org.onosproject.bgp.controller.BgpSessionInfo.
Definition at line 80 of file BgpSessionInfoImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.BgpSessionInfoImpl().
short org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.remoteBgpHoldTime ()
Gets the BGP peer hold time.
Returns
bgp hold time.
Implements org.onosproject.bgp.controller.BgpSessionInfo.
Definition at line 85 of file BgpSessionInfoImpl.java.
BgpId org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.remoteBgpId ()
Gets the BGP ID of BGP peer.
Returns
bgp ID.
Implements org.onosproject.bgp.controller.BgpSessionInfo.
Definition at line 70 of file BgpSessionInfoImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.BgpSessionInfoImpl().
int org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.remoteBgpIdentifier ()
Gets the BGP version for this bgp peer.
Returns
bgp identifier.
Implements org.onosproject.bgp.controller.BgpSessionInfo.
Definition at line 90 of file BgpSessionInfoImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.BgpSessionInfoImpl().
BgpVersion org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.remoteBgpVersion ()
Gets the BGP version of peer.
Returns
bgp version.
Implements org.onosproject.bgp.controller.BgpSessionInfo.
Definition at line 75 of file BgpSessionInfoImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.BgpSessionInfoImpl().
Member Data Documentation
final Logger org.onosproject.bgp.controller.impl.BgpSessionInfoImpl.log = LoggerFactory.getLogger(BgpSessionInfoImpl.class) protected
Definition at line 27 of file BgpSessionInfoImpl.java.
The documentation for this class was generated from the following file:
bgp/ctl/src/main/java/org/onosproject/bgp/controller/impl/BgpSessionInfoImpl.java