onos: org.onosproject.net.flow.DefaultTrafficTreatmentTest Class Reference
org.onosproject.net.flow.DefaultTrafficTreatmentTest Class Reference
Unit tests for the DefaultTrafficTreatment class.
Public Member Functions
void testTreatmentBuilderConstructors ()
Tests that the Builder constructors return equivalent objects when given the same data.
void testBuilderMethods ()
Tests methods defined on the Builder.
void testEquals ()
Tests equals(), hashCode() and toString() methods of DefaultTrafficTreatment.
Detailed Description
Unit tests for the DefaultTrafficTreatment class.
Definition at line 38 of file DefaultTrafficTreatmentTest.java.
Member Function Documentation
void org.onosproject.net.flow.DefaultTrafficTreatmentTest.testBuilderMethods ()
Tests methods defined on the Builder.
Definition at line 61 of file DefaultTrafficTreatmentTest.java.
References org.onlab.packet.MacAddress.BROADCAST, and org.onlab.packet.VlanId.vlanId().
void org.onosproject.net.flow.DefaultTrafficTreatmentTest.testEquals ()
Tests equals(), hashCode() and toString() methods of DefaultTrafficTreatment.
Definition at line 104 of file DefaultTrafficTreatmentTest.java.
References org.onosproject.net.flow.instructions.Instructions.modL0Lambda().
void org.onosproject.net.flow.DefaultTrafficTreatmentTest.testTreatmentBuilderConstructors ()
Tests that the Builder constructors return equivalent objects when given the same data.
Definition at line 47 of file DefaultTrafficTreatmentTest.java.
References org.onosproject.net.flow.instructions.Instructions.modL0Lambda().
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/flow/DefaultTrafficTreatmentTest.java