onos: org.onosproject.openstackswitching.OpenstackSwitchingConfig Class Reference
org.onosproject.openstackswitching.OpenstackSwitchingConfig Class Reference
Handles configuration for OpenstackSwitching app.
Public Member Functions
boolean doNotPushFlows ()
Returns the flag whether the app pushes flows or not.
String neutronServer ()
Returns the Neutron server IP address.
String keystoneServer ()
Returns the Keystone server IP address.
String userName ()
Returns the username for openstack.
String password ()
Returns the password for openstack.
BasicElementConfig doNotPushFlows (boolean flag)
Sets the flag whether the app pushes flows or not.
BasicElementConfig neutronServer (String url)
Sets the neutron server IP address.
BasicElementConfig keystoneServer (String url)
Sets the keystone server IP address.
BasicElementConfig userName (String username)
Sets the username for openstack.
BasicElementConfig password (String password)
Sets the password for openstack.
Static Public Attributes
static final String DONOTPUSH = "do_not_push_flows"
static final String NEUTRON_SERVER = "neutron_server"
static final String KEYSTONE_SERVER = "keystone_server"
static final String USER_NAME = "user_name"
static final String PASSWORD = "password"
Detailed Description
Handles configuration for OpenstackSwitching app.
Definition at line 25 of file OpenstackSwitchingConfig.java.
Member Function Documentation
boolean org.onosproject.openstackswitching.OpenstackSwitchingConfig.doNotPushFlows ()
Returns the flag whether the app pushes flows or not.
Returns
the flag or false if not set
Definition at line 37 of file OpenstackSwitchingConfig.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.DONOTPUSH.
BasicElementConfig org.onosproject.openstackswitching.OpenstackSwitchingConfig.doNotPushFlows (boolean flag)
Sets the flag whether the app pushes flows or not.
Parameters
flag the flag whether the app pushes flows or not
Returns
self
Definition at line 84 of file OpenstackSwitchingConfig.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.DONOTPUSH.
String org.onosproject.openstackswitching.OpenstackSwitchingConfig.keystoneServer ()
Returns the Keystone server IP address.
Returns
Keystone server IP
Definition at line 56 of file OpenstackSwitchingConfig.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.KEYSTONE_SERVER.
Referenced by org.onosproject.openstackswitching.OpenstackRestHandler.OpenstackRestHandler().
BasicElementConfig org.onosproject.openstackswitching.OpenstackSwitchingConfig.keystoneServer (String url)
Sets the keystone server IP address.
Parameters
url keystone server IP address
Returns
itself
Definition at line 104 of file OpenstackSwitchingConfig.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.KEYSTONE_SERVER.
String org.onosproject.openstackswitching.OpenstackSwitchingConfig.neutronServer ()
Returns the Neutron server IP address.
Returns
Neutron server IP
Definition at line 47 of file OpenstackSwitchingConfig.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.NEUTRON_SERVER.
Referenced by org.onosproject.openstackswitching.OpenstackRestHandler.OpenstackRestHandler().
BasicElementConfig org.onosproject.openstackswitching.OpenstackSwitchingConfig.neutronServer (String url)
Sets the neutron server IP address.
Parameters
url neutron server IP address
Returns
itself
Definition at line 94 of file OpenstackSwitchingConfig.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.NEUTRON_SERVER.
String org.onosproject.openstackswitching.OpenstackSwitchingConfig.password ()
Returns the password for openstack.
Returns
password for openstack
Definition at line 74 of file OpenstackSwitchingConfig.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.PASSWORD.
Referenced by org.onosproject.openstackswitching.OpenstackRestHandler.OpenstackRestHandler().
BasicElementConfig org.onosproject.openstackswitching.OpenstackSwitchingConfig.password (String password)
Sets the password for openstack.
Parameters
password password for openstack
Returns
itself
Definition at line 124 of file OpenstackSwitchingConfig.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.PASSWORD.
String org.onosproject.openstackswitching.OpenstackSwitchingConfig.userName ()
Returns the username for openstack.
Returns
username for openstack
Definition at line 65 of file OpenstackSwitchingConfig.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.USER_NAME.
Referenced by org.onosproject.openstackswitching.OpenstackRestHandler.OpenstackRestHandler().
BasicElementConfig org.onosproject.openstackswitching.OpenstackSwitchingConfig.userName (String username)
Sets the username for openstack.
Parameters
username user name for openstack
Returns
itself
Definition at line 114 of file OpenstackSwitchingConfig.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.USER_NAME.
Member Data Documentation
final String org.onosproject.openstackswitching.OpenstackSwitchingConfig.DONOTPUSH = "do_not_push_flows" static
Definition at line 26 of file OpenstackSwitchingConfig.java.
Referenced by org.onosproject.openstackswitching.OpenstackSwitchingConfig.doNotPushFlows().
final String org.onosproject.openstackswitching.OpenstackSwitchingConfig.KEYSTONE_SERVER = "keystone_server" static
Definition at line 28 of file OpenstackSwitchingConfig.java.
Referenced by org.onosproject.openstackswitching.OpenstackSwitchingConfig.keystoneServer().
final String org.onosproject.openstackswitching.OpenstackSwitchingConfig.NEUTRON_SERVER = "neutron_server" static
Definition at line 27 of file OpenstackSwitchingConfig.java.
Referenced by org.onosproject.openstackswitching.OpenstackSwitchingConfig.neutronServer().
final String org.onosproject.openstackswitching.OpenstackSwitchingConfig.PASSWORD = "password" static
Definition at line 30 of file OpenstackSwitchingConfig.java.
Referenced by org.onosproject.openstackswitching.OpenstackSwitchingConfig.password().
final String org.onosproject.openstackswitching.OpenstackSwitchingConfig.USER_NAME = "user_name" static
Definition at line 29 of file OpenstackSwitchingConfig.java.
Referenced by org.onosproject.openstackswitching.OpenstackSwitchingConfig.userName().
The documentation for this class was generated from the following file:
apps/openstackswitching/app/src/main/java/org/onosproject/openstackswitching/OpenstackSwitchingConfig.java