onos: org.onosproject.driver.pipeline.CentecV350Pipeline Class Reference
org.onosproject.driver.pipeline.CentecV350Pipeline Class Reference
Driver for Centec's V350 switches.
Public Member Functions
void init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
void filter (FilteringObjective filteringObjective)
Installs the filtering rules onto the device.
void forward (ForwardingObjective fwd)
Installs the forwarding rules onto the device.
void next (NextObjective nextObjective)
Installs the next hop elements into the device.
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Static Protected Attributes
static final int PORT_VLAN_TABLE = 0
static final int FILTER_TABLE = 1
static final int MAC_TABLE = 2
static final int ROUTE_TABLE = 3
Detailed Description
Driver for Centec's V350 switches.
Definition at line 89 of file CentecV350Pipeline.java.
Member Function Documentation
void org.onosproject.driver.pipeline.CentecV350Pipeline.filter (FilteringObjective filterObjective)
Installs the filtering rules onto the device.
Parameters
filterObjective a filtering objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 172 of file CentecV350Pipeline.java.
References org.onosproject.net.flowobjective.Objective.op(), org.onosproject.net.flowobjective.FilteringObjective.type(), and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
Referenced by org.onosproject.driver.pipeline.CentecV350Pipeline.forward().
void org.onosproject.driver.pipeline.CentecV350Pipeline.forward (ForwardingObjective forwardObjective)
Installs the forwarding rules onto the device.
Parameters
forwardObjective a forwarding objective
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 183 of file CentecV350Pipeline.java.
References org.onosproject.driver.pipeline.CentecV350Pipeline.filter(), org.onosproject.net.flowobjective.ObjectiveError.FLOWINSTALLATIONFAILED, org.onosproject.net.flowobjective.Objective.op(), and org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN.
void org.onosproject.driver.pipeline.CentecV350Pipeline.init (DeviceId deviceId, PipelinerContext context)
Initializes the driver with context required for its operation.
Parameters
deviceId the deviceId
context processing context
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 144 of file CentecV350Pipeline.java.
References org.onosproject.net.flowobjective.ObjectiveError.GROUPINSTALLATIONFAILED.
void org.onosproject.driver.pipeline.CentecV350Pipeline.next (NextObjective nextObjective)
Installs the next hop elements into the device.
Parameters
nextObjective a next objectives
Implements org.onosproject.net.behaviour.Pipeliner.
Definition at line 220 of file CentecV350Pipeline.java.
References org.onosproject.net.flow.TrafficTreatment.allInstructions(), org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.net.flowobjective.Objective.id(), org.onlab.util.KryoNamespace.serialize(), org.onosproject.net.flow.instructions.L2ModificationInstruction.subtype(), org.onosproject.net.flowobjective.NextObjective.type(), org.onosproject.net.flowobjective.ObjectiveError.UNKNOWN, and org.onosproject.net.flowobjective.ObjectiveError.UNSUPPORTED.
Member Data Documentation
final int org.onosproject.driver.pipeline.CentecV350Pipeline.FILTER_TABLE = 1 static protected
Definition at line 92 of file CentecV350Pipeline.java.
final int org.onosproject.driver.pipeline.CentecV350Pipeline.MAC_TABLE = 2 static protected
Definition at line 94 of file CentecV350Pipeline.java.
final int org.onosproject.driver.pipeline.CentecV350Pipeline.PORT_VLAN_TABLE = 0 static protected
Definition at line 91 of file CentecV350Pipeline.java.
final int org.onosproject.driver.pipeline.CentecV350Pipeline.ROUTE_TABLE = 3 static protected
Definition at line 95 of file CentecV350Pipeline.java.
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/pipeline/CentecV350Pipeline.java