onos: org.onosproject.net.edgeservice.impl.EdgeManagerTest Class Reference
org.onosproject.net.edgeservice.impl.EdgeManagerTest Class Reference
Test of the edge port manager.
Public Member Functions
void setUp ()
void tearDown ()
void testBasics ()
void testLinkUpdates ()
void testDeviceUpdates ()
void testInternalCache ()
void testEmit ()
Detailed Description
Test of the edge port manager.
Each device has ports '0' through 'numPorts - 1' as specified by the variable 'numPorts'.
Definition at line 67 of file EdgeManagerTest.java.
Member Function Documentation
void org.onosproject.net.edgeservice.impl.EdgeManagerTest.setUp ()
Definition at line 80 of file EdgeManagerTest.java.
void org.onosproject.net.edgeservice.impl.EdgeManagerTest.tearDown ()
Definition at line 94 of file EdgeManagerTest.java.
void org.onosproject.net.edgeservice.impl.EdgeManagerTest.testBasics ()
Definition at line 100 of file EdgeManagerTest.java.
References org.onosproject.net.NetTestTools.connectPoint(), org.onosproject.net.edgeservice.impl.EdgeManager.getEdgePoints(), and org.onosproject.net.edgeservice.impl.EdgeManager.isEdgePoint().
void org.onosproject.net.edgeservice.impl.EdgeManagerTest.testDeviceUpdates ()
Definition at line 191 of file EdgeManagerTest.java.
References org.onosproject.net.edgeservice.impl.EdgeManager.deviceService, org.onosproject.net.NetTestTools.did(), org.onosproject.net.device.DeviceService.getPorts(), obeliskHostCheck.port, org.onosproject.net.PortNumber.portNumber(), and onos.size.
void org.onosproject.net.edgeservice.impl.EdgeManagerTest.testEmit ()
Definition at line 349 of file EdgeManagerTest.java.
References find-link-in-cluster.length, and org.onosproject.net.PortNumber.portNumber().
void org.onosproject.net.edgeservice.impl.EdgeManagerTest.testInternalCache ()
Definition at line 304 of file EdgeManagerTest.java.
References org.onosproject.net.NetTestTools.did(), org.onosproject.net.edgeservice.impl.EdgeManager.getEdgePoints(), and org.onosproject.net.edgeservice.impl.EdgeManager.isEdgePoint().
void org.onosproject.net.edgeservice.impl.EdgeManagerTest.testLinkUpdates ()
Definition at line 119 of file EdgeManagerTest.java.
References org.onosproject.net.ConnectPoint.deviceId(), org.onosproject.net.NetTestTools.link(), and org.onosproject.net.ConnectPoint.port().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/edgeservice/impl/EdgeManagerTest.java