onos: org.onosproject.vtnrsc.portpair.impl.PortPairManager Class Reference
org.onosproject.vtnrsc.portpair.impl.PortPairManager Class Reference
Provides implementation of the portPairService.
Public Member Functions
void activate ()
void deactivate ()
boolean exists (PortPairId portPairId)
Returns if the port pair is existed.
int getPortPairCount ()
Returns the number of port pairs known to the system.
Iterable< PortPair > getPortPairs ()
Returns an iterable collection of the currently known port pairs.
PortPair getPortPair (PortPairId portPairId)
Returns the portPair with the given identifier.
boolean createPortPair (PortPair portPair)
Creates a PortPair in the store.
boolean updatePortPair (PortPair portPair)
Updates the portPair in the store.
boolean removePortPair (PortPairId portPairId)
Deletes portPair by given portPairId.
Protected Attributes
StorageService storageService
Detailed Description
Provides implementation of the portPairService.
Definition at line 45 of file PortPairManager.java.
Member Function Documentation
void org.onosproject.vtnrsc.portpair.impl.PortPairManager.activate ()
Definition at line 58 of file PortPairManager.java.
References org.onosproject.store.serializers.KryoNamespaces.API.
boolean org.onosproject.vtnrsc.portpair.impl.PortPairManager.createPortPair (PortPair portPair)
Creates a PortPair in the store.
Parameters
portPair the port pair to create
Returns
true if given port pair is created successfully.
Implements org.onosproject.vtnrsc.portpair.PortPairService.
Definition at line 102 of file PortPairManager.java.
References org.onosproject.vtnrsc.PortPair.portPairId().
Referenced by org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testCreatePortPair().
void org.onosproject.vtnrsc.portpair.impl.PortPairManager.deactivate ()
Definition at line 74 of file PortPairManager.java.
boolean org.onosproject.vtnrsc.portpair.impl.PortPairManager.exists (PortPairId portPairId)
Returns if the port pair is existed.
Parameters
portPairId port pair identifier
Returns
true or false if one with the given identifier exists.
Implements org.onosproject.vtnrsc.portpair.PortPairService.
Definition at line 80 of file PortPairManager.java.
Referenced by org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testExists().
PortPair org.onosproject.vtnrsc.portpair.impl.PortPairManager.getPortPair (PortPairId portPairId)
Returns the portPair with the given identifier.
Parameters
portPairId port pair identifier
Returns
PortPair or null if port pair with the given identifier is not known.
Implements org.onosproject.vtnrsc.portpair.PortPairService.
Definition at line 96 of file PortPairManager.java.
Referenced by org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testGetPortPair().
int org.onosproject.vtnrsc.portpair.impl.PortPairManager.getPortPairCount ()
Returns the number of port pairs known to the system.
Returns
number of port pairs.
Implements org.onosproject.vtnrsc.portpair.PortPairService.
Definition at line 86 of file PortPairManager.java.
Referenced by org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testGetPortPairCount().
Iterable<PortPair> org.onosproject.vtnrsc.portpair.impl.PortPairManager.getPortPairs ()
Returns an iterable collection of the currently known port pairs.
Returns
collection of port pairs.
Implements org.onosproject.vtnrsc.portpair.PortPairService.
Definition at line 91 of file PortPairManager.java.
boolean org.onosproject.vtnrsc.portpair.impl.PortPairManager.removePortPair (PortPairId portPairId)
Deletes portPair by given portPairId.
Parameters
portPairId id of port pair to remove
Returns
true if the give port pair is deleted successfully.
Implements org.onosproject.vtnrsc.portpair.PortPairService.
Definition at line 135 of file PortPairManager.java.
Referenced by org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testRemovePortPair().
boolean org.onosproject.vtnrsc.portpair.impl.PortPairManager.updatePortPair (PortPair portPair)
Updates the portPair in the store.
Parameters
portPair the port pair to update
Returns
true if given port pair is updated successfully.
Implements org.onosproject.vtnrsc.portpair.PortPairService.
Definition at line 115 of file PortPairManager.java.
References org.onosproject.vtnrsc.PortPair.portPairId().
Referenced by org.onosproject.vtnrsc.portpair.impl.PortPairManagerTest.testUpdatePortPair().
Member Data Documentation
StorageService org.onosproject.vtnrsc.portpair.impl.PortPairManager.storageService protected
Definition at line 55 of file PortPairManager.java.
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/portpair/impl/PortPairManager.java