onos: org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint Class Reference
org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint Class Reference
Default optical tunnel point model implementation.
Public Member Functions
DefaultOpticalTunnelEndPoint (ProviderId providerId, Optional< ElementId > elementId, Optional< PortNumber > number, Optional< OpticalTunnelEndPoint > parentPoint, Type type, OpticalLogicId id, boolean isGlobal, Annotations...annotations)
Creates a optical tunnel point attributed to the specified provider (may be null).
OpticalLogicId id ()
Returns the identifier.
Optional< ElementId > elementId ()
Returns the parent network element to which this tunnel point belongs.
Optional< PortNumber > portNumber ()
Returns the parent network port to which this tunnel point belongs, can not be be null.
Optional< OpticalTunnelEndPoint > parentPoint ()
Returns the parent tunnel point to which this tunnel point belongs, optional.
boolean isGlobal ()
Indicates whether or not the port is global significant.
Type type ()
Returns the tunnel point type.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel ()
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel (ProviderId providerId, Annotations...annotations)
Creates a model entity attributed to the specified provider and optionally annotated.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default optical tunnel point model implementation.
Definition at line 34 of file DefaultOpticalTunnelEndPoint.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.DefaultOpticalTunnelEndPoint (ProviderId providerId, Optional< ElementId > elementId, Optional< PortNumber > number, Optional< OpticalTunnelEndPoint > parentPoint, Type type, OpticalLogicId id, boolean isGlobal, Annotations... annotations)
Creates a optical tunnel point attributed to the specified provider (may be null).
if provider is null, which means the optical tunnel point is not managed by the SB.
Parameters
providerId tunnelProvider Id
elementId parent network element
number port number
parentPoint parent port or parent label
type port type
id LabelId
isGlobal indicator whether the label is global significant or not
annotations optional key/value annotations
Definition at line 55 of file DefaultOpticalTunnelEndPoint.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.elementId(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.id(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.isGlobal(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.parentPoint(), and org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.type().
Referenced by org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.equals().
Member Function Documentation
Optional<ElementId> org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.elementId ()
Returns the parent network element to which this tunnel point belongs.
Returns
parent network element
Implements org.onosproject.incubator.net.tunnel.OpticalTunnelEndPoint.
Definition at line 73 of file DefaultOpticalTunnelEndPoint.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.DefaultOpticalTunnelEndPoint(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.toString().
boolean org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.equals (Object obj)
Definition at line 103 of file DefaultOpticalTunnelEndPoint.java.
References org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.DefaultOpticalTunnelEndPoint(), and find-device.id.
int org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.hashCode ()
Definition at line 98 of file DefaultOpticalTunnelEndPoint.java.
References org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.elementId(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.id(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.parentPoint(), and org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.portNumber().
OpticalLogicId org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.id ()
Returns the identifier.
Returns
identifier
Implements org.onosproject.incubator.net.tunnel.OpticalTunnelEndPoint.
Definition at line 68 of file DefaultOpticalTunnelEndPoint.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.DefaultOpticalTunnelEndPoint(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.toString().
boolean org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.isGlobal ()
Indicates whether or not the port is global significant.
Returns
true if the port is global significant
Implements org.onosproject.incubator.net.tunnel.OpticalTunnelEndPoint.
Definition at line 88 of file DefaultOpticalTunnelEndPoint.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.DefaultOpticalTunnelEndPoint(), and org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.toString().
Optional<OpticalTunnelEndPoint> org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.parentPoint ()
Returns the parent tunnel point to which this tunnel point belongs, optional.
Returns
parent tunnel point, if it is null, the parent is a physical port
Implements org.onosproject.incubator.net.tunnel.OpticalTunnelEndPoint.
Definition at line 83 of file DefaultOpticalTunnelEndPoint.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.DefaultOpticalTunnelEndPoint(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.toString().
Optional<PortNumber> org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.portNumber ()
Returns the parent network port to which this tunnel point belongs, can not be be null.
Returns
port number
Implements org.onosproject.incubator.net.tunnel.OpticalTunnelEndPoint.
Definition at line 78 of file DefaultOpticalTunnelEndPoint.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.hashCode(), and org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.toString().
String org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.toString ()
Definition at line 120 of file DefaultOpticalTunnelEndPoint.java.
References org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.elementId(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.id(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.isGlobal(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.parentPoint(), org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.portNumber(), and org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.type().
Type org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.type ()
Returns the tunnel point type.
Returns
tunnel point type
Implements org.onosproject.incubator.net.tunnel.OpticalTunnelEndPoint.
Definition at line 93 of file DefaultOpticalTunnelEndPoint.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.DefaultOpticalTunnelEndPoint(), and org.onosproject.incubator.net.tunnel.DefaultOpticalTunnelEndPoint.toString().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/tunnel/DefaultOpticalTunnelEndPoint.java