onos: org.onosproject.segmentrouting.PolicyHandler Class Reference
org.onosproject.segmentrouting.PolicyHandler Class Reference
Segment Routing Policy Handler.
Classes
enum Result
Public Member Functions
PolicyHandler (ApplicationId appId, DeviceConfiguration deviceConfiguration, FlowObjectiveService flowObjectiveService, TunnelHandler tunnelHandler, EventuallyConsistentMap< String, Policy > policyStore)
Creates a reference.
List< Policy > getPolicies ()
Returns the policies.
Result createPolicy (Policy policy)
Creates a policy using the policy information given.
Result removePolicy (Policy policyInfo)
Removes the policy given.
Protected Attributes
final Logger log = getLogger(getClass())
Detailed Description
Segment Routing Policy Handler.
Definition at line 42 of file PolicyHandler.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.PolicyHandler.PolicyHandler (ApplicationId appId, DeviceConfiguration deviceConfiguration, FlowObjectiveService flowObjectiveService, TunnelHandler tunnelHandler, EventuallyConsistentMap< String, Policy > policyStore)
Creates a reference.
Parameters
appId segment routing application ID
deviceConfiguration DeviceConfiguration reference
flowObjectiveService FlowObjectiveService reference
tunnelHandler tunnel handler reference
policyStore policy store
Definition at line 70 of file PolicyHandler.java.
Member Function Documentation
Result org.onosproject.segmentrouting.PolicyHandler.createPolicy (Policy policy)
Creates a policy using the policy information given.
Parameters
policy policy reference to create
Returns
ID_EXISTS if the same policy ID exists, POLICY_EXISTS if the same policy exists, TUNNEL_NOT_FOUND if the tunnel does not exists, UNSUPPORTED_TYPE if the policy type is not supported, SUCCESS if the policy is created successfully
Definition at line 103 of file PolicyHandler.java.
References org.onosproject.segmentrouting.Tunnel.groupId(), org.onosproject.segmentrouting.Policy.id(), org.onosproject.segmentrouting.PolicyHandler.Result.ID_EXISTS, org.onosproject.segmentrouting.PolicyHandler.Result.POLICY_EXISTS, org.onosproject.segmentrouting.PolicyHandler.Result.SUCCESS, org.onosproject.segmentrouting.PolicyHandler.Result.TUNNEL_NOT_FOUND, org.onosproject.segmentrouting.Policy.type(), and org.onosproject.segmentrouting.PolicyHandler.Result.UNSUPPORTED_TYPE.
List<Policy> org.onosproject.segmentrouting.PolicyHandler.getPolicies ()
Returns the policies.
Returns
policy list
Definition at line 87 of file PolicyHandler.java.
Result org.onosproject.segmentrouting.PolicyHandler.removePolicy (Policy policyInfo)
Removes the policy given.
Parameters
policyInfo policy information to remove
Returns
POLICY_NOT_FOUND if the policy to remove does not exists, SUCCESS if it is removed successfully
Definition at line 152 of file PolicyHandler.java.
References org.onosproject.segmentrouting.Tunnel.groupId(), org.onosproject.segmentrouting.Policy.id(), org.onosproject.segmentrouting.PolicyHandler.Result.POLICY_NOT_FOUND, org.onosproject.segmentrouting.PolicyHandler.Result.SUCCESS, and org.onosproject.segmentrouting.Policy.type().
Member Data Documentation
final Logger org.onosproject.segmentrouting.PolicyHandler.log = getLogger(getClass()) protected
Definition at line 44 of file PolicyHandler.java.
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/PolicyHandler.java