onos: org.onosproject.bgpio.types.MpReachNlri Class Reference
org.onosproject.bgpio.types.MpReachNlri Class Reference
Public Member Functions
MpReachNlri (List< BgpLSNlri > mpReachNlri, short afi, byte safi, Ip4Address ipNextHop, int length)
Constructor to initialize parameters.
boolean isMpReachNlriSet ()
Returns whether MpReachNlri is present.
List< BgpLSNlri > mpReachNlri ()
Returns list of MpReach Nlri.
int mpReachNlriLen ()
Returns length of MpReachNlri.
short getType ()
Returns the Type of BGP Message.
short afi ()
Returns AFI.
Ip4Address nexthop4 ()
Returns Nexthop IpAddress.
byte safi ()
Returns SAFI.
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static MpReachNlri read (ChannelBuffer cb) throws BgpParseException
Reads from ChannelBuffer and parses MpReachNlri.
Static Public Attributes
static final byte MPREACHNLRI_TYPE = 14
static final byte LINK_NLRITYPE = 2
Detailed Description
Definition at line 40 of file MpReachNlri.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.MpReachNlri.MpReachNlri (List< BgpLSNlri > mpReachNlri, short afi, byte safi, Ip4Address ipNextHop, int length)
Constructor to initialize parameters.
Parameters
mpReachNlri MpReach Nlri attribute
afi address family identifier
safi subsequent address family identifier
ipNextHop nexthop IpAddress
length of MpReachNlri
Definition at line 62 of file MpReachNlri.java.
References org.onosproject.bgpio.types.MpReachNlri.afi(), org.onosproject.bgpio.types.MpReachNlri.mpReachNlri(), and org.onosproject.bgpio.types.MpReachNlri.safi().
Referenced by org.onosproject.bgpio.types.MpReachNlri.read().
Member Function Documentation
short org.onosproject.bgpio.types.MpReachNlri.afi ()
Returns AFI.
Returns
AFI
Definition at line 181 of file MpReachNlri.java.
Referenced by org.onosproject.bgpio.types.MpReachNlri.MpReachNlri(), org.onosproject.bgpio.types.MpReachNlri.read(), and org.onosproject.bgpio.types.MpReachNlri.toString().
int org.onosproject.bgpio.types.MpReachNlri.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 221 of file MpReachNlri.java.
short org.onosproject.bgpio.types.MpReachNlri.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 172 of file MpReachNlri.java.
References org.onosproject.bgpio.types.MpReachNlri.MPREACHNLRI_TYPE.
boolean org.onosproject.bgpio.types.MpReachNlri.isMpReachNlriSet ()
Returns whether MpReachNlri is present.
Returns
whether MpReachNlri is present
Definition at line 76 of file MpReachNlri.java.
List<BgpLSNlri> org.onosproject.bgpio.types.MpReachNlri.mpReachNlri ()
Returns list of MpReach Nlri.
Returns
list of MpReach Nlri
Definition at line 85 of file MpReachNlri.java.
Referenced by org.onosproject.bgpio.types.MpReachNlri.MpReachNlri(), org.onosproject.bgpio.types.MpReachNlri.read(), and org.onosproject.bgpio.types.MpReachNlri.toString().
int org.onosproject.bgpio.types.MpReachNlri.mpReachNlriLen ()
Returns length of MpReachNlri.
Returns
length of MpReachNlri
Definition at line 94 of file MpReachNlri.java.
References find-link-in-cluster.length.
Ip4Address org.onosproject.bgpio.types.MpReachNlri.nexthop4 ()
Returns Nexthop IpAddress.
Returns
Nexthop IpAddress
Definition at line 190 of file MpReachNlri.java.
static MpReachNlri org.onosproject.bgpio.types.MpReachNlri.read (ChannelBuffer cb) throws BgpParseException static
Reads from ChannelBuffer and parses MpReachNlri.
Parameters
cb channelBuffer
Returns
object of MpReachNlri
Exceptions
BgpParseException while parsing MpReachNlri
Definition at line 105 of file MpReachNlri.java.
References org.onosproject.bgpio.types.MpReachNlri.afi(), org.onosproject.bgpio.util.Constants.AFI_VALUE, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_FLAGS_ERROR, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.util.Validation.getLength(), org.onosproject.bgpio.types.MpReachNlri.MpReachNlri(), org.onosproject.bgpio.types.MpReachNlri.mpReachNlri(), org.onosproject.bgpio.types.MpReachNlri.safi(), org.onosproject.bgpio.util.Constants.SAFI_VALUE, org.onosproject.bgpio.util.Constants.TYPE_AND_LEN_AS_BYTE, org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR, and org.onosproject.bgpio.util.Constants.VPN_SAFI_VALUE.
byte org.onosproject.bgpio.types.MpReachNlri.safi ()
Returns SAFI.
Returns
SAFI
Definition at line 199 of file MpReachNlri.java.
Referenced by org.onosproject.bgpio.types.MpReachNlri.MpReachNlri(), org.onosproject.bgpio.types.MpReachNlri.read(), and org.onosproject.bgpio.types.MpReachNlri.toString().
String org.onosproject.bgpio.types.MpReachNlri.toString ()
Definition at line 210 of file MpReachNlri.java.
References org.onosproject.bgpio.types.MpReachNlri.afi(), org.onosproject.bgpio.types.MpReachNlri.mpReachNlri(), and org.onosproject.bgpio.types.MpReachNlri.safi().
int org.onosproject.bgpio.types.MpReachNlri.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 204 of file MpReachNlri.java.
Member Data Documentation
final byte org.onosproject.bgpio.types.MpReachNlri.LINK_NLRITYPE = 2 static
Definition at line 44 of file MpReachNlri.java.
final byte org.onosproject.bgpio.types.MpReachNlri.MPREACHNLRI_TYPE = 14 static
Definition at line 43 of file MpReachNlri.java.
Referenced by org.onosproject.bgpio.types.MpReachNlri.getType().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/MpReachNlri.java