onos: org.onosproject.net.intent.impl.IntentManagerTest Class Reference
org.onosproject.net.intent.impl.IntentManagerTest Class Reference
Test intent manager and transitions.
Classes
class EntryForIntentMatcher
Hamcrest matcher to check that a collection of Intents contains an Intent with the specified Intent Id.
Public Member Functions
void setUp ()
void verifyState ()
void tearDown ()
void submitIntent ()
void withdrawIntent ()
void stressSubmitWithdrawUnique ()
void stressSubmitWithdrawSame ()
void errorIntentCompile ()
Tests for proper behavior of installation of an intent that triggers a compilation error.
void errorIntentInstallFromFlows ()
Tests handling a future that contains an error as a result of installing an intent.
void errorIntentInstallNeverTrue ()
Tests handling a future that contains an unresolvable error as a result of installing an intent.
void intentSubclassCompile ()
Tests that a compiler for a subclass of an intent that already has a compiler is automatically added.
void intentWithoutCompiler ()
Tests an intent with no compiler.
void intentWithoutInstaller ()
Tests an intent with no installer.
void testIntentFetching ()
Tests that the intent fetching methods are correct.
void testFlowRemoval ()
Tests that removing all intents results in no flows remaining.
void testCorruptCleanup ()
Test failure to install an intent, then succeed on retry via IntentCleanup.
void testCorruptRetry ()
Test failure to install an intent, and verify retries.
void testFlowRemovalInstallError ()
Tests that an intent that fails installation results in no flows remaining.
Protected Attributes
IntentService service
IntentExtensionService extensionService
TestListener listener = new TestListener()
TestIntentCompiler compiler = new TestIntentCompiler()
Detailed Description
Test intent manager and transitions.
TODO implement the following tests:
{submit, withdraw, update, replace} intent
{submit, update, recompiling} intent with failed compilation
failed reservation
push timeout recovery
failed items recovery
in general, verify intents store, flow store, and work queue
Definition at line 84 of file IntentManagerTest.java.
Member Function Documentation
void org.onosproject.net.intent.impl.IntentManagerTest.errorIntentCompile ()
Tests for proper behavior of installation of an intent that triggers a compilation error.
Definition at line 359 of file IntentManagerTest.java.
References org.onosproject.net.intent.IntentEvent.Type.FAILED, org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, and org.onosproject.net.intent.impl.IntentManagerTest.verifyState().
void org.onosproject.net.intent.impl.IntentManagerTest.errorIntentInstallFromFlows ()
Tests handling a future that contains an error as a result of installing an intent.
Definition at line 377 of file IntentManagerTest.java.
References org.onosproject.net.intent.IntentEvent.Type.FAILED, org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, and org.onosproject.net.intent.impl.IntentManagerTest.verifyState().
void org.onosproject.net.intent.impl.IntentManagerTest.errorIntentInstallNeverTrue ()
Tests handling a future that contains an unresolvable error as a result of installing an intent.
Definition at line 396 of file IntentManagerTest.java.
References org.onosproject.net.intent.IntentEvent.Type.CORRUPT, org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, and org.onosproject.net.intent.impl.IntentManagerTest.verifyState().
void org.onosproject.net.intent.impl.IntentManagerTest.intentSubclassCompile ()
Tests that a compiler for a subclass of an intent that already has a compiler is automatically added.
Definition at line 417 of file IntentManagerTest.java.
References org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRuleCount(), org.onosproject.net.intent.IntentService.getIntentCount(), org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, org.onosproject.net.intent.IntentEvent.Type.INSTALLED, org.onosproject.net.intent.impl.IntentManagerTest.service, and org.onosproject.net.intent.impl.IntentManagerTest.verifyState().
void org.onosproject.net.intent.impl.IntentManagerTest.intentWithoutCompiler ()
Tests an intent with no compiler.
Definition at line 446 of file IntentManagerTest.java.
References org.onosproject.net.intent.Intent.DEFAULT_INTENT_PRIORITY, org.onosproject.net.intent.IntentEvent.Type.FAILED, org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, and org.onosproject.net.intent.impl.IntentManagerTest.verifyState().
void org.onosproject.net.intent.impl.IntentManagerTest.intentWithoutInstaller ()
Tests an intent with no installer.
Definition at line 467 of file IntentManagerTest.java.
References org.onosproject.net.intent.IntentEvent.Type.CORRUPT, org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, and org.onosproject.net.intent.impl.IntentManagerTest.verifyState().
void org.onosproject.net.intent.impl.IntentManagerTest.setUp ()
Definition at line 226 of file IntentManagerTest.java.
References org.onosproject.net.intent.impl.IntentManagerTest.compiler, org.onosproject.net.intent.impl.IntentManagerTest.extensionService, org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRuleCount(), org.onosproject.net.intent.IntentService.getIntents(), org.onosproject.net.intent.impl.IntentManagerTest.listener, and org.onosproject.net.intent.impl.IntentManagerTest.service.
void org.onosproject.net.intent.impl.IntentManagerTest.stressSubmitWithdrawSame ()
Definition at line 335 of file IntentManagerTest.java.
References org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRuleCount(), org.onosproject.net.intent.IntentService.getIntentCount(), org.onosproject.net.intent.impl.IntentManagerTest.service, and org.onosproject.net.intent.impl.IntentManagerTest.verifyState().
void org.onosproject.net.intent.impl.IntentManagerTest.stressSubmitWithdrawUnique ()
Definition at line 312 of file IntentManagerTest.java.
References org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRuleCount(), org.onosproject.net.intent.impl.IntentManagerTest.verifyState(), and org.onosproject.net.intent.IntentEvent.Type.WITHDRAWN.
void org.onosproject.net.intent.impl.IntentManagerTest.submitIntent ()
Definition at line 278 of file IntentManagerTest.java.
References org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRuleCount(), org.onosproject.net.intent.IntentService.getIntentCount(), org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, org.onosproject.net.intent.IntentEvent.Type.INSTALLED, org.onosproject.net.intent.impl.IntentManagerTest.service, and org.onosproject.net.intent.impl.IntentManagerTest.verifyState().
void org.onosproject.net.intent.impl.IntentManagerTest.tearDown ()
Definition at line 270 of file IntentManagerTest.java.
References org.onosproject.net.intent.impl.IntentManagerTest.listener.
void org.onosproject.net.intent.impl.IntentManagerTest.testCorruptCleanup ()
Test failure to install an intent, then succeed on retry via IntentCleanup.
Definition at line 558 of file IntentManagerTest.java.
References org.onosproject.net.intent.IntentEvent.Type.CORRUPT, org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRuleCount(), org.onosproject.net.intent.impl.IntentManager.getIntentState(), org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, org.onosproject.net.intent.IntentEvent.Type.INSTALLED, and org.onosproject.net.intent.impl.IntentManagerTest.listener.
void org.onosproject.net.intent.impl.IntentManagerTest.testCorruptRetry ()
Test failure to install an intent, and verify retries.
Definition at line 604 of file IntentManagerTest.java.
References org.onosproject.net.intent.IntentEvent.Type.CORRUPT, org.onosproject.net.intent.impl.IntentManager.getIntentState(), org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, org.onosproject.net.intent.IntentEvent.Type.INSTALLED, org.onosproject.net.intent.impl.IntentManagerTest.listener, and org.onosproject.net.intent.impl.IntentCleanup.retryThreshold.
void org.onosproject.net.intent.impl.IntentManagerTest.testFlowRemoval ()
Tests that removing all intents results in no flows remaining.
Definition at line 513 of file IntentManagerTest.java.
References org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRuleCount(), org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, org.onosproject.net.intent.IntentEvent.Type.INSTALLED, org.onosproject.net.intent.impl.IntentManagerTest.listener, and org.onosproject.net.intent.IntentEvent.Type.WITHDRAWN.
void org.onosproject.net.intent.impl.IntentManagerTest.testFlowRemovalInstallError ()
Tests that an intent that fails installation results in no flows remaining.
Definition at line 647 of file IntentManagerTest.java.
References org.onosproject.net.intent.IntentEvent.Type.CORRUPT, org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, and org.onosproject.net.intent.impl.IntentManagerTest.listener.
void org.onosproject.net.intent.impl.IntentManagerTest.testIntentFetching ()
Tests that the intent fetching methods are correct.
Definition at line 481 of file IntentManagerTest.java.
References org.onosproject.net.intent.IntentEvent.Type.INSTALL_REQ, org.onosproject.net.intent.IntentEvent.Type.INSTALLED, and org.onosproject.net.intent.impl.IntentManagerTest.verifyState().
void org.onosproject.net.intent.impl.IntentManagerTest.verifyState ()
Definition at line 246 of file IntentManagerTest.java.
References org.onosproject.net.intent.IntentService.getIntents(), and org.onosproject.net.intent.impl.IntentManagerTest.service.
Referenced by org.onosproject.net.intent.impl.IntentManagerTest.errorIntentCompile(), org.onosproject.net.intent.impl.IntentManagerTest.errorIntentInstallFromFlows(), org.onosproject.net.intent.impl.IntentManagerTest.errorIntentInstallNeverTrue(), org.onosproject.net.intent.impl.IntentManagerTest.intentSubclassCompile(), org.onosproject.net.intent.impl.IntentManagerTest.intentWithoutCompiler(), org.onosproject.net.intent.impl.IntentManagerTest.intentWithoutInstaller(), org.onosproject.net.intent.impl.IntentManagerTest.stressSubmitWithdrawSame(), org.onosproject.net.intent.impl.IntentManagerTest.stressSubmitWithdrawUnique(), org.onosproject.net.intent.impl.IntentManagerTest.submitIntent(), org.onosproject.net.intent.impl.IntentManagerTest.testIntentFetching(), and org.onosproject.net.intent.impl.IntentManagerTest.withdrawIntent().
void org.onosproject.net.intent.impl.IntentManagerTest.withdrawIntent ()
Definition at line 293 of file IntentManagerTest.java.
References org.onosproject.net.intent.impl.MockFlowRuleService.getFlowRuleCount(), org.onosproject.net.intent.IntentService.getIntentCount(), org.onosproject.net.intent.IntentEvent.Type.INSTALLED, org.onosproject.net.intent.impl.IntentManagerTest.service, org.onosproject.net.intent.impl.IntentManagerTest.verifyState(), and org.onosproject.net.intent.IntentEvent.Type.WITHDRAWN.
Member Data Documentation
TestIntentCompiler org.onosproject.net.intent.impl.IntentManagerTest.compiler = new TestIntentCompiler() protected
Definition at line 95 of file IntentManagerTest.java.
Referenced by org.onosproject.net.intent.impl.IntentManagerTest.setUp().
IntentExtensionService org.onosproject.net.intent.impl.IntentManagerTest.extensionService protected
Definition at line 93 of file IntentManagerTest.java.
Referenced by org.onosproject.net.intent.impl.IntentManagerTest.setUp().
TestListener org.onosproject.net.intent.impl.IntentManagerTest.listener = new TestListener() protected
Definition at line 94 of file IntentManagerTest.java.
Referenced by org.onosproject.net.intent.impl.IntentManagerTest.setUp(), org.onosproject.net.intent.impl.IntentManagerTest.tearDown(), org.onosproject.net.intent.impl.IntentManagerTest.testCorruptCleanup(), org.onosproject.net.intent.impl.IntentManagerTest.testCorruptRetry(), org.onosproject.net.intent.impl.IntentManagerTest.testFlowRemoval(), and org.onosproject.net.intent.impl.IntentManagerTest.testFlowRemovalInstallError().
IntentService org.onosproject.net.intent.impl.IntentManagerTest.service protected
Definition at line 92 of file IntentManagerTest.java.
Referenced by org.onosproject.net.intent.impl.IntentManagerTest.intentSubclassCompile(), org.onosproject.net.intent.impl.IntentManagerTest.setUp(), org.onosproject.net.intent.impl.IntentManagerTest.stressSubmitWithdrawSame(), org.onosproject.net.intent.impl.IntentManagerTest.submitIntent(), org.onosproject.net.intent.impl.IntentManagerTest.verifyState(), and org.onosproject.net.intent.impl.IntentManagerTest.withdrawIntent().
The documentation for this class was generated from the following file:
core/net/src/test/java/org/onosproject/net/intent/impl/IntentManagerTest.java