onos: org.onosproject.routing.config.InterfaceAddress Class Reference
org.onosproject.routing.config.InterfaceAddress Class Reference
Represents an address of a BgpSpeaker configured on an Interface.
Public Member Functions
InterfaceAddress (@JsonProperty("interfaceDpid") String dpid,@JsonProperty("interfacePort") int port,@JsonProperty("ipAddress") String ipAddress)
Creates an InterfaceAddress object.
ConnectPoint connectPoint ()
Gets the connection point of the peer.
IpAddress ipAddress ()
Gets the IP address of a BGP speaker configured on an Interface.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Represents an address of a BgpSpeaker configured on an Interface.
Each InterfaceAddress includes the interface name and an IP address.
Definition at line 35 of file InterfaceAddress.java.
Constructor & Destructor Documentation
org.onosproject.routing.config.InterfaceAddress.InterfaceAddress (@JsonProperty("interfaceDpid") String dpid, @JsonProperty("interfacePort") int port, @JsonProperty("ipAddress") String ipAddress)
Creates an InterfaceAddress object.
Parameters
dpid the DPID of the interface as a String
port the port of the interface
ipAddress the IP address of a BgpSpeaker configured on the interface
Definition at line 47 of file InterfaceAddress.java.
References org.onosproject.net.DeviceId.deviceId(), org.onosproject.net.NetTools.dpidToUri(), org.onosproject.routing.config.InterfaceAddress.ipAddress(), and org.onosproject.net.PortNumber.portNumber().
Referenced by org.onosproject.routing.config.InterfaceAddress.equals().
Member Function Documentation
ConnectPoint org.onosproject.routing.config.InterfaceAddress.connectPoint ()
Gets the connection point of the peer.
Returns
the connection point
Definition at line 61 of file InterfaceAddress.java.
Referenced by org.onosproject.routing.config.InterfaceAddress.hashCode(), and org.onosproject.routing.config.InterfaceAddress.toString().
boolean org.onosproject.routing.config.InterfaceAddress.equals (Object obj)
Definition at line 80 of file InterfaceAddress.java.
References org.onosproject.routing.config.InterfaceAddress.InterfaceAddress().
int org.onosproject.routing.config.InterfaceAddress.hashCode ()
Definition at line 75 of file InterfaceAddress.java.
References org.onosproject.routing.config.InterfaceAddress.connectPoint(), and org.onosproject.routing.config.InterfaceAddress.ipAddress().
IpAddress org.onosproject.routing.config.InterfaceAddress.ipAddress ()
Gets the IP address of a BGP speaker configured on an Interface.
Returns
the IP address
Definition at line 70 of file InterfaceAddress.java.
Referenced by org.onosproject.routing.config.InterfaceAddress.hashCode(), org.onosproject.routing.config.InterfaceAddress.InterfaceAddress(), and org.onosproject.routing.config.InterfaceAddress.toString().
String org.onosproject.routing.config.InterfaceAddress.toString ()
Definition at line 95 of file InterfaceAddress.java.
References org.onosproject.routing.config.InterfaceAddress.connectPoint(), and org.onosproject.routing.config.InterfaceAddress.ipAddress().
The documentation for this class was generated from the following file:
apps/routing-api/src/main/java/org/onosproject/routing/config/InterfaceAddress.java