onos: org.onosproject.net.OduCltPort Class Reference
org.onosproject.net.OduCltPort Class Reference
Implementation of ODU client port (Optical channel Data Unit).
Classes
enum SignalType
Public Member Functions
OduCltPort (Element element, PortNumber number, boolean isEnabled, SignalType signalType, Annotations...annotations)
Creates an ODU client port in the specified network element.
SignalType signalType ()
Returns ODU client signal type.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.DefaultPort
DefaultPort (Element element, PortNumber number, boolean isEnabled, Annotations...annotations)
Creates a network element attributed to the specified provider.
DefaultPort (Element element, PortNumber number, boolean isEnabled, Type type, long portSpeed, Annotations...annotations)
Creates a network element attributed to the specified provider.
Element element ()
Returns the parent network element to which this port belongs.
PortNumber number ()
Returns the port number.
boolean isEnabled ()
Indicates whether or not the port is currently up and active.
Type type ()
Returns the port type.
long portSpeed ()
Returns the current port speed in Mbps.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Static Public Attributes inherited from org.onosproject.net.DefaultPort
static final long DEFAULT_SPEED = 1_000
Default port speed in Mbps.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Implementation of ODU client port (Optical channel Data Unit).
Also referred to as a T-port or wide band port. See ITU G.709 "Interfaces for the Optical Transport Network (OTN)"
Definition at line 28 of file OduCltPort.java.
Constructor & Destructor Documentation
org.onosproject.net.OduCltPort.OduCltPort (Element element, PortNumber number, boolean isEnabled, SignalType signalType, Annotations... annotations)
Creates an ODU client port in the specified network element.
Parameters
element parent network element
number port number
isEnabled port enabled state
signalType ODU client signal type
annotations optional key/value annotations
Definition at line 49 of file OduCltPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.Port.Type.ODUCLT, and org.onosproject.net.OduCltPort.signalType().
Referenced by org.onosproject.net.OduCltPort.equals().
Member Function Documentation
boolean org.onosproject.net.OduCltPort.equals (Object obj)
Definition at line 70 of file OduCltPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultPort.isEnabled(), and org.onosproject.net.OduCltPort.OduCltPort().
int org.onosproject.net.OduCltPort.hashCode ()
Definition at line 65 of file OduCltPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultPort.isEnabled(), org.onosproject.net.DefaultPort.number(), org.onosproject.net.OduCltPort.signalType(), and org.onosproject.net.DefaultPort.type().
SignalType org.onosproject.net.OduCltPort.signalType ()
Returns ODU client signal type.
Returns
ODU client signal type
Definition at line 60 of file OduCltPort.java.
Referenced by org.onosproject.net.OduCltPort.hashCode(), org.onosproject.net.OduCltPort.OduCltPort(), and org.onosproject.net.OduCltPort.toString().
String org.onosproject.net.OduCltPort.toString ()
Definition at line 87 of file OduCltPort.java.
References org.onosproject.net.DefaultPort.element(), org.onosproject.net.DefaultPort.isEnabled(), org.onosproject.net.DefaultPort.number(), org.onosproject.net.OduCltPort.signalType(), and org.onosproject.net.DefaultPort.type().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/OduCltPort.java