onos: org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv Class Reference
org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv Class Reference
Provides Local TE Node Descriptors TLV which contains Node Descriptor Sub-TLVs.
Public Member Functions
LocalTENodeDescriptorsTlv (LinkedList< PcepValueType > llNodeDescriptorSubTLVs)
Constructor to initialize llNodeDescriptorSubTLVs.
LinkedList< PcepValueType > getllNodeDescriptorSubTLVs ()
Returns Linked List of tlvs.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static LocalTENodeDescriptorsTlv of (final LinkedList< PcepValueType > llNodeDescriptorSubTLVs)
Returns a new object of LocalTENodeDescriptorsTLV.
static PcepValueType read (ChannelBuffer c, short hLength) throws PcepParseException
Reads the channel buffer and returns object of AutonomousSystemTlv.
Public Attributes
short hLength
Static Public Attributes
static final short TYPE = 1637
static final int TLV_HEADER_LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(LocalTENodeDescriptorsTlv.class)
Detailed Description
Provides Local TE Node Descriptors TLV which contains Node Descriptor Sub-TLVs.
Definition at line 34 of file LocalTENodeDescriptorsTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.LocalTENodeDescriptorsTlv (LinkedList< PcepValueType > llNodeDescriptorSubTLVs)
Constructor to initialize llNodeDescriptorSubTLVs.
Parameters
llNodeDescriptorSubTLVs LinkedList of PcepValueType
Definition at line 63 of file LocalTENodeDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.equals(), org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.of(), and org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.equals (Object obj)
Definition at line 107 of file LocalTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.LocalTENodeDescriptorsTlv().
short org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 97 of file LocalTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.hLength.
LinkedList<PcepValueType> org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.getllNodeDescriptorSubTLVs ()
Returns Linked List of tlvs.
Returns
llNodeDescriptorSubTLVs linked list of Node Descriptor Sub TLV
Definition at line 82 of file LocalTENodeDescriptorsTlv.java.
short org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 92 of file LocalTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 87 of file LocalTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.hashCode ()
Definition at line 102 of file LocalTENodeDescriptorsTlv.java.
static LocalTENodeDescriptorsTlv org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.of (final LinkedList< PcepValueType > llNodeDescriptorSubTLVs) static
Returns a new object of LocalTENodeDescriptorsTLV.
Parameters
llNodeDescriptorSubTLVs linked list of Node Descriptor Sub TLVs
Returns
object of LocalTENodeDescriptorsTLV
Definition at line 73 of file LocalTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.LocalTENodeDescriptorsTlv().
static PcepValueType org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.read (ChannelBuffer c, short hLength) throws PcepParseException static
Reads the channel buffer and returns object of AutonomousSystemTlv.
Parameters
c input channel buffer
hLength length of subtlvs.
Returns
object of AutonomousSystemTlv
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 184 of file LocalTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.hLength, find-link-in-cluster.length, org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.LocalTENodeDescriptorsTlv(), and org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.TLV_HEADER_LENGTH.
String org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.toString ()
Definition at line 239 of file LocalTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.hLength, and org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.TYPE.
int org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 144 of file LocalTENodeDescriptorsTlv.java.
References org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.hLength, org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.TLV_HEADER_LENGTH, and org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.TYPE.
Member Data Documentation
short org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.hLength
Definition at line 52 of file LocalTENodeDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.getLength(), org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.read(), org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.toString(), and org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.write().
final Logger org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.log = LoggerFactory.getLogger(LocalTENodeDescriptorsTlv.class) static protected
Definition at line 49 of file LocalTENodeDescriptorsTlv.java.
final int org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.TLV_HEADER_LENGTH = 4 static
Definition at line 54 of file LocalTENodeDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.read(), and org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.write().
final short org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.TYPE = 1637 static
Definition at line 51 of file LocalTENodeDescriptorsTlv.java.
Referenced by org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.getType(), org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.toString(), and org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/LocalTENodeDescriptorsTlv.java