onos: org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv Class Reference
org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv Class Reference
Provide the Maximum Reservable Link Bandwidth.
Public Member Functions
MaximumReservableLinkBandwidthTlv (int rawValue)
constructor to initialize rawValue.
int getInt ()
Returns value of Maximum Reservable Link Bandwidth.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static
MaximumReservableLinkBandwidthTlv of (final int raw)
Returns newly created MaximumReservableLinkBandwidth object.
static
MaximumReservableLinkBandwidthTlv read (ChannelBuffer c)
Reads the channel buffer and returns object of MaximumReservableLinkBandwidthTlv.
Static Public Attributes
static final short TYPE = 10
static final short LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(MaximumReservableLinkBandwidthTlv.class)
Detailed Description
Provide the Maximum Reservable Link Bandwidth.
Definition at line 30 of file MaximumReservableLinkBandwidthTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.MaximumReservableLinkBandwidthTlv (int rawValue)
constructor to initialize rawValue.
Parameters
rawValue MaximumReservableLinkBandwidth
Definition at line 54 of file MaximumReservableLinkBandwidthTlv.java.
Referenced by org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.equals(), and org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.equals (Object obj)
Definition at line 98 of file MaximumReservableLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.MaximumReservableLinkBandwidthTlv().
int org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.getInt ()
Returns value of Maximum Reservable Link Bandwidth.
Returns
rawValue Maximum Reservable Link Bandwidth
Definition at line 73 of file MaximumReservableLinkBandwidthTlv.java.
short org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 88 of file MaximumReservableLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.LENGTH.
short org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 83 of file MaximumReservableLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 78 of file MaximumReservableLinkBandwidthTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.hashCode ()
Definition at line 93 of file MaximumReservableLinkBandwidthTlv.java.
static MaximumReservableLinkBandwidthTlv org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.of (final int raw) static
Returns newly created MaximumReservableLinkBandwidth object.
Parameters
raw MaximumReservableLinkBandwidth
Returns
object of MaximumReservableLinkBandwidthTlv
Definition at line 65 of file MaximumReservableLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.MaximumReservableLinkBandwidthTlv().
static MaximumReservableLinkBandwidthTlv org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of MaximumReservableLinkBandwidthTlv.
Parameters
c input channel buffer
Returns
object of MaximumReservableLinkBandwidthTlv
Definition at line 124 of file MaximumReservableLinkBandwidthTlv.java.
String org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.toString ()
Definition at line 129 of file MaximumReservableLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.LENGTH, and org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.TYPE.
int org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 110 of file MaximumReservableLinkBandwidthTlv.java.
References org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.LENGTH, and org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.LENGTH = 4 static
Definition at line 45 of file MaximumReservableLinkBandwidthTlv.java.
Referenced by org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.getLength(), org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.toString(), and org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.write().
final Logger org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.log = LoggerFactory.getLogger(MaximumReservableLinkBandwidthTlv.class) static protected
Definition at line 42 of file MaximumReservableLinkBandwidthTlv.java.
final short org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.TYPE = 10 static
Definition at line 44 of file MaximumReservableLinkBandwidthTlv.java.
Referenced by org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.getType(), org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.toString(), and org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/MaximumReservableLinkBandwidthTlv.java