onos: org.onosproject.net.resource.impl.LinkResourceManager Class Reference
org.onosproject.net.resource.impl.LinkResourceManager Class Reference
Provides basic implementation of link resources allocation.
Public Member Functions
void activate ()
void deactivate ()
LinkResourceAllocations requestResources (LinkResourceRequest req)
Requests resources.
void releaseResources (LinkResourceAllocations allocations)
Releases resources.
LinkResourceAllocations updateResources (LinkResourceRequest req, LinkResourceAllocations oldAllocations)
Updates previously made allocations with a new resource request.
Iterable< LinkResourceAllocations > getAllocations ()
Returns all allocated resources.
Iterable< LinkResourceAllocations > getAllocations (Link link)
Returns all allocated resources to given link.
LinkResourceAllocations getAllocations (IntentId intentId)
Returns the resources allocated for an Intent.
Iterable< ResourceRequest > getAvailableResources (Link link)
Returns available resources for given link.
Iterable< ResourceRequest > getAvailableResources (Link link, LinkResourceAllocations allocations)
Returns available resources for given link.
Detailed Description
Provides basic implementation of link resources allocation.
Definition at line 64 of file LinkResourceManager.java.
Member Function Documentation
void org.onosproject.net.resource.impl.LinkResourceManager.activate ()
Definition at line 74 of file LinkResourceManager.java.
void org.onosproject.net.resource.impl.LinkResourceManager.deactivate ()
Definition at line 80 of file LinkResourceManager.java.
Iterable<LinkResourceAllocations> org.onosproject.net.resource.impl.LinkResourceManager.getAllocations ()
Returns all allocated resources.
Returns
allocated resources
Deprecated:
in Emu Release
Implements org.onosproject.net.resource.link.LinkResourceService.
Definition at line 163 of file LinkResourceManager.java.
Iterable<LinkResourceAllocations> org.onosproject.net.resource.impl.LinkResourceManager.getAllocations (Link link)
Returns all allocated resources to given link.
Parameters
link a target link
Returns
allocated resources
Deprecated:
in Emu Release
Implements org.onosproject.net.resource.link.LinkResourceService.
Definition at line 169 of file LinkResourceManager.java.
LinkResourceAllocations org.onosproject.net.resource.impl.LinkResourceManager.getAllocations (IntentId intentId)
Returns the resources allocated for an Intent.
Parameters
intentId the target Intent's id
Returns
allocated resources for Intent
Deprecated:
in Emu Release
Implements org.onosproject.net.resource.link.LinkResourceService.
Definition at line 175 of file LinkResourceManager.java.
Iterable<ResourceRequest> org.onosproject.net.resource.impl.LinkResourceManager.getAvailableResources (Link link)
Returns available resources for given link.
Parameters
link a target link
Returns
available resources for the target link
Deprecated:
in Emu Release
Implements org.onosproject.net.resource.link.LinkResourceService.
Definition at line 181 of file LinkResourceManager.java.
Referenced by org.onosproject.net.resource.impl.LinkResourceManager.getAvailableResources().
Iterable<ResourceRequest> org.onosproject.net.resource.impl.LinkResourceManager.getAvailableResources (Link link, LinkResourceAllocations allocations)
Returns available resources for given link.
Parameters
link a target link
allocations allocations to be included as available
Returns
available resources for the target link
Deprecated:
in Emu Release
Implements org.onosproject.net.resource.link.LinkResourceService.
Definition at line 208 of file LinkResourceManager.java.
References org.onosproject.net.resource.impl.LinkResourceManager.getAvailableResources().
void org.onosproject.net.resource.impl.LinkResourceManager.releaseResources (LinkResourceAllocations allocations)
Releases resources.
Parameters
allocations resources to be released
Deprecated:
in Emu Release
Implements org.onosproject.net.resource.link.LinkResourceService.
Definition at line 146 of file LinkResourceManager.java.
Referenced by org.onosproject.net.resource.impl.LinkResourceManager.updateResources().
LinkResourceAllocations org.onosproject.net.resource.impl.LinkResourceManager.requestResources (LinkResourceRequest req)
Requests resources.
Parameters
req resources to be allocated
Returns
allocated resources
Deprecated:
in Emu Release
Implements org.onosproject.net.resource.link.LinkResourceService.
Definition at line 87 of file LinkResourceManager.java.
References org.onosproject.net.resource.link.LinkResourceRequest.links(), org.onosproject.net.resource.ResourceType.MPLS_LABEL, org.onosproject.net.resource.link.MplsLabelResourceRequest.mplsLabel(), and org.onosproject.net.resource.link.LinkResourceRequest.resources().
Referenced by org.onosproject.net.resource.impl.LinkResourceManager.updateResources().
LinkResourceAllocations org.onosproject.net.resource.impl.LinkResourceManager.updateResources (LinkResourceRequest req, LinkResourceAllocations oldAllocations)
Updates previously made allocations with a new resource request.
Parameters
req updated resource request
oldAllocations old resource allocations
Returns
new resource allocations
Deprecated:
in Emu Release
Implements org.onosproject.net.resource.link.LinkResourceService.
Definition at line 155 of file LinkResourceManager.java.
References org.onosproject.net.resource.impl.LinkResourceManager.releaseResources(), and org.onosproject.net.resource.impl.LinkResourceManager.requestResources().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/resource/impl/LinkResourceManager.java