onos: org.onosproject.incubator.net.domain.DomainVertex Class Reference
org.onosproject.incubator.net.domain.DomainVertex Class Reference
Representation of the intent domain or a device that is part of the intent domain graph.
Public Member Functions
DomainVertex (IntentDomainId id)
DomainVertex (DeviceId id)
String toString ()
DeviceId deviceId ()
Returns the device ID of this vertex if it is a device, returns null if it is a domain.
IntentDomainId domainId ()
Returns the domain ID of this vertex if it is a domain, returns null if it is a device.
Detailed Description
Representation of the intent domain or a device that is part of the intent domain graph.
Definition at line 30 of file DomainVertex.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.domain.DomainVertex.DomainVertex (IntentDomainId id)
Definition at line 45 of file DomainVertex.java.
org.onosproject.incubator.net.domain.DomainVertex.DomainVertex (DeviceId id)
Definition at line 50 of file DomainVertex.java.
Member Function Documentation
DeviceId org.onosproject.incubator.net.domain.DomainVertex.deviceId ()
Returns the device ID of this vertex if it is a device, returns null if it is a domain.
Returns
the device ID of this vertex if applicable, else null
Definition at line 76 of file DomainVertex.java.
Referenced by org.onosproject.incubator.net.domain.DomainVertex.toString().
IntentDomainId org.onosproject.incubator.net.domain.DomainVertex.domainId ()
Returns the domain ID of this vertex if it is a domain, returns null if it is a device.
Returns
the domain ID of this vertex if applicable, else null
Definition at line 85 of file DomainVertex.java.
Referenced by org.onosproject.incubator.net.domain.DomainVertex.toString().
String org.onosproject.incubator.net.domain.DomainVertex.toString ()
Definition at line 56 of file DomainVertex.java.
References org.onosproject.incubator.net.domain.DomainVertex.deviceId(), and org.onosproject.incubator.net.domain.DomainVertex.domainId().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/domain/DomainVertex.java