onos: org.onosproject.bgpio.types.IPv4AddressTlv Class Reference
org.onosproject.bgpio.types.IPv4AddressTlv Class Reference
Provides Implementation of IPv4AddressTlv.
Public Member Functions
IPv4AddressTlv (Ip4Address address, short type)
Constructor to initialize parameters.
Ip4Address address ()
Returns Ipv4 address of interface/neighbor.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static IPv4AddressTlv read (ChannelBuffer cb, short type) throws BgpParseException
Reads the channel buffer and returns object of IPv4AddressTlv.
static IPv4AddressTlv of (final Ip4Address address, final short type)
Returns object of this class with specified values.
Detailed Description
Provides Implementation of IPv4AddressTlv.
Definition at line 32 of file IPv4AddressTlv.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.IPv4AddressTlv.IPv4AddressTlv (Ip4Address address, short type)
Constructor to initialize parameters.
Parameters
address Ipv4 address of interface/neighbor
type address type
Definition at line 44 of file IPv4AddressTlv.java.
References org.onosproject.bgpio.types.IPv4AddressTlv.address().
Referenced by org.onosproject.bgpio.types.IPv4AddressTlv.equals(), and org.onosproject.bgpio.types.IPv4AddressTlv.of().
Member Function Documentation
Ip4Address org.onosproject.bgpio.types.IPv4AddressTlv.address ()
Returns Ipv4 address of interface/neighbor.
Returns
Ipv4 address of interface/neighbor
Definition at line 54 of file IPv4AddressTlv.java.
Referenced by org.onosproject.bgpio.types.IPv4AddressTlv.compareTo(), org.onosproject.bgpio.types.IPv4AddressTlv.hashCode(), org.onosproject.bgpio.types.IPv4AddressTlv.IPv4AddressTlv(), org.onosproject.bgpio.types.IPv4AddressTlv.read(), and org.onosproject.bgpio.types.IPv4AddressTlv.toString().
int org.onosproject.bgpio.types.IPv4AddressTlv.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 118 of file IPv4AddressTlv.java.
References org.onosproject.bgpio.types.IPv4AddressTlv.address(), and org.onosproject.bgpio.types.IPv4AddressTlv.equals().
boolean org.onosproject.bgpio.types.IPv4AddressTlv.equals (Object obj)
Definition at line 69 of file IPv4AddressTlv.java.
References org.onosproject.bgpio.types.IPv4AddressTlv.IPv4AddressTlv().
Referenced by org.onosproject.bgpio.types.IPv4AddressTlv.compareTo().
short org.onosproject.bgpio.types.IPv4AddressTlv.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 59 of file IPv4AddressTlv.java.
int org.onosproject.bgpio.types.IPv4AddressTlv.hashCode ()
Definition at line 64 of file IPv4AddressTlv.java.
References org.onosproject.bgpio.types.IPv4AddressTlv.address().
static IPv4AddressTlv org.onosproject.bgpio.types.IPv4AddressTlv.of (final Ip4Address address, final short type) static
Returns object of this class with specified values.
Parameters
address Ipv4 interface/neighbor Address
type says Ipv4 address of interface/neighbor tlv type
Returns
object of this class
Definition at line 113 of file IPv4AddressTlv.java.
References org.onosproject.bgpio.types.IPv4AddressTlv.IPv4AddressTlv().
static IPv4AddressTlv org.onosproject.bgpio.types.IPv4AddressTlv.read (ChannelBuffer cb, short type) throws BgpParseException static
Reads the channel buffer and returns object of IPv4AddressTlv.
Parameters
cb channelBuffer
type address type
Returns
object of IPv4AddressTlv
Exceptions
BgpParseException while parsing IPv4AddressTlv
Definition at line 97 of file IPv4AddressTlv.java.
References org.onosproject.bgpio.types.IPv4AddressTlv.address(), and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.IPv4AddressTlv.toString ()
Definition at line 126 of file IPv4AddressTlv.java.
References org.onosproject.bgpio.types.IPv4AddressTlv.address().
int org.onosproject.bgpio.types.IPv4AddressTlv.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 81 of file IPv4AddressTlv.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/IPv4AddressTlv.java