onos: org.onosproject.bgp.controller.impl.BgpControllerImpl Class Reference
org.onosproject.bgp.controller.impl.BgpControllerImpl Class Reference
Classes
class BgpPeerManagerImpl
Implementation of an BGP Peer which is responsible for keeping track of connected peers and the state in which they are.
Public Member Functions
void activate ()
void deactivate ()
Iterable< BgpPeer > getPeers ()
Returns list of bgp peers connected to this BGP controller.
BgpPeer getPeer (BgpId bgpId)
Returns the actual bgp peer for the given ip address.
void addListener (BgpNodeListener listener)
Register a listener for BGP message events.
void removeListener (BgpNodeListener listener)
Unregister a listener.
Set< BgpNodeListener > listener ()
Return BGP node listener.
void writeMsg (BgpId bgpId, BgpMessage msg)
Send a message to a particular bgp peer.
void processBGPPacket (BgpId bgpId, BgpMessage msg) throws BgpParseException
Process a message and notify the appropriate listeners.
void closeConnectedPeers ()
Close all connected BGP peers.
Controller controller ()
Returns controller.
ConcurrentHashMap< BgpId, BgpPeer > connectedPeers ()
Return BGP connected peers.
BgpPeerManagerImpl peerManager ()
Return BGP peer manager.
BgpCfg getConfig ()
Get the BGPConfig class to the caller.
int connectedPeerCount ()
Get the BGP connected peers to this controller.
Protected Attributes
ConcurrentHashMap< BgpId, BgpPeer > connectedPeers = new ConcurrentHashMap<BgpId, BgpPeer>()
BgpPeerManagerImpl peerManager = new BgpPeerManagerImpl()
Set< BgpNodeListener > bgpNodeListener = new CopyOnWriteArraySet<>()
Detailed Description
Definition at line 42 of file BgpControllerImpl.java.
Member Function Documentation
void org.onosproject.bgp.controller.impl.BgpControllerImpl.activate ()
Definition at line 57 of file BgpControllerImpl.java.
void org.onosproject.bgp.controller.impl.BgpControllerImpl.addListener (BgpNodeListener listener)
Register a listener for BGP message events.
Parameters
listener the listener to notify
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 81 of file BgpControllerImpl.java.
References org.onosproject.bgp.controller.impl.BgpControllerImpl.listener().
void org.onosproject.bgp.controller.impl.BgpControllerImpl.closeConnectedPeers ()
Close all connected BGP peers.
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 123 of file BgpControllerImpl.java.
References org.onosproject.bgp.controller.impl.BgpControllerImpl.connectedPeers(), and org.onosproject.bgp.controller.impl.BgpControllerImpl.getPeer().
Referenced by org.onosproject.bgp.controller.impl.BgpControllerImpl.deactivate().
int org.onosproject.bgp.controller.impl.BgpControllerImpl.connectedPeerCount ()
Get the BGP connected peers to this controller.
Returns
the integer number
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 215 of file BgpControllerImpl.java.
ConcurrentHashMap<BgpId, BgpPeer> org.onosproject.bgp.controller.impl.BgpControllerImpl.connectedPeers ()
Return BGP connected peers.
Returns
connectedPeers connected peers
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 200 of file BgpControllerImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpControllerImpl.BgpPeerManagerImpl.addConnectedPeer(), org.onosproject.bgp.controller.impl.BgpControllerImpl.closeConnectedPeers(), and org.onosproject.bgp.controller.impl.BgpControllerImpl.BgpPeerManagerImpl.isPeerConnected().
Controller org.onosproject.bgp.controller.impl.BgpControllerImpl.controller ()
Returns controller.
Returns
controller
Definition at line 195 of file BgpControllerImpl.java.
void org.onosproject.bgp.controller.impl.BgpControllerImpl.deactivate ()
Definition at line 63 of file BgpControllerImpl.java.
References org.onosproject.bgp.controller.impl.BgpControllerImpl.closeConnectedPeers().
BgpCfg org.onosproject.bgp.controller.impl.BgpControllerImpl.getConfig ()
Get the BGPConfig class to the caller.
Returns
configuration object
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 210 of file BgpControllerImpl.java.
BgpPeer org.onosproject.bgp.controller.impl.BgpControllerImpl.getPeer (BgpId bgpId)
Returns the actual bgp peer for the given ip address.
Parameters
bgpId the id of the bgp peer to fetch
Returns
the interface to this bgp peer
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 76 of file BgpControllerImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpControllerImpl.closeConnectedPeers().
Iterable<BgpPeer> org.onosproject.bgp.controller.impl.BgpControllerImpl.getPeers ()
Returns list of bgp peers connected to this BGP controller.
Returns
Iterable of BGPPeer elements
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 71 of file BgpControllerImpl.java.
Set<BgpNodeListener> org.onosproject.bgp.controller.impl.BgpControllerImpl.listener ()
Return BGP node listener.
Returns
node listener
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 91 of file BgpControllerImpl.java.
References org.onosproject.bgp.controller.impl.BgpControllerImpl.bgpNodeListener.
Referenced by org.onosproject.bgp.controller.impl.BgpControllerImpl.addListener(), and org.onosproject.bgp.controller.impl.BgpControllerImpl.removeListener().
BgpPeerManagerImpl org.onosproject.bgp.controller.impl.BgpControllerImpl.peerManager ()
Return BGP peer manager.
Returns
BGPPeerManager peer manager instance
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 205 of file BgpControllerImpl.java.
void org.onosproject.bgp.controller.impl.BgpControllerImpl.processBGPPacket (BgpId bgpId, BgpMessage msg) throws BgpParseException
Process a message and notify the appropriate listeners.
Parameters
bgpId id of the peer the message arrived on
msg the message to process.
Exceptions
BgpParseException on data processing error
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 101 of file BgpControllerImpl.java.
void org.onosproject.bgp.controller.impl.BgpControllerImpl.removeListener (BgpNodeListener listener)
Unregister a listener.
Parameters
listener the listener to unregister
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 86 of file BgpControllerImpl.java.
References org.onosproject.bgp.controller.impl.BgpControllerImpl.listener().
void org.onosproject.bgp.controller.impl.BgpControllerImpl.writeMsg (BgpId bgpId, BgpMessage msg)
Send a message to a particular bgp peer.
Parameters
bgpId the id of the peer to send message.
msg the message to send
Implements org.onosproject.bgp.controller.BgpController.
Definition at line 96 of file BgpControllerImpl.java.
Member Data Documentation
Set<BgpNodeListener> org.onosproject.bgp.controller.impl.BgpControllerImpl.bgpNodeListener = new CopyOnWriteArraySet<>() protected
Definition at line 50 of file BgpControllerImpl.java.
Referenced by org.onosproject.bgp.controller.impl.BgpControllerImpl.listener().
ConcurrentHashMap<BgpId, BgpPeer> org.onosproject.bgp.controller.impl.BgpControllerImpl.connectedPeers = new ConcurrentHashMap<BgpId, BgpPeer>() protected
Definition at line 46 of file BgpControllerImpl.java.
BgpPeerManagerImpl org.onosproject.bgp.controller.impl.BgpControllerImpl.peerManager = new BgpPeerManagerImpl() protected
Definition at line 48 of file BgpControllerImpl.java.
The documentation for this class was generated from the following file:
bgp/ctl/src/main/java/org/onosproject/bgp/controller/impl/BgpControllerImpl.java