onos: org.onlab.stc.Step Class Reference
org.onlab.stc.Step Class Reference
Representation of a test step.
Public Member Functions
Step (String name, String command, String env, String cwd, Group group)
Creates a new test step.
String name ()
Returns the step name.
String command ()
Returns the step command string.
String env ()
Returns the step environment script path.
String cwd ()
Returns the step current working directory path.
Group group ()
Returns the enclosing group; null if none.
int hashCode ()
boolean equals (Object obj)
String toString ()
Protected Attributes
final String name
final String command
final String env
final String cwd
final Group group
Detailed Description
Representation of a test step.
Definition at line 28 of file Step.java.
Constructor & Destructor Documentation
org.onlab.stc.Step.Step (String name, String command, String env, String cwd, Group group)
Creates a new test step.
Parameters
name step name
command step command to execute
env path to file to be sourced into the environment
cwd path to current working directory for the step
group optional group to which this step belongs
Definition at line 45 of file Step.java.
References org.onlab.stc.Step.group().
Referenced by org.onlab.stc.Step.equals().
Member Function Documentation
String org.onlab.stc.Step.command ()
Returns the step command string.
Returns
command string
Definition at line 70 of file Step.java.
Referenced by org.onlab.stc.Step.toString().
String org.onlab.stc.Step.cwd ()
Returns the step current working directory path.
Returns
current working dir path
Definition at line 88 of file Step.java.
Referenced by org.onlab.stc.Step.toString().
String org.onlab.stc.Step.env ()
Returns the step environment script path.
Returns
env script path
Definition at line 79 of file Step.java.
Referenced by org.onlab.stc.Step.toString().
boolean org.onlab.stc.Step.equals (Object obj)
Definition at line 108 of file Step.java.
References create-flow.name, and org.onlab.stc.Step.Step().
Group org.onlab.stc.Step.group ()
Returns the enclosing group; null if none.
Returns
enclosing group or null
Definition at line 97 of file Step.java.
Referenced by org.onlab.stc.Step.Step(), and org.onlab.stc.Step.toString().
int org.onlab.stc.Step.hashCode ()
Definition at line 103 of file Step.java.
String org.onlab.stc.Step.name ()
Returns the step name.
Returns
step name
Definition at line 61 of file Step.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onlab.stc.Step.toString().
String org.onlab.stc.Step.toString ()
Definition at line 120 of file Step.java.
References org.onlab.stc.Step.command(), org.onlab.stc.Step.cwd(), org.onlab.stc.Step.env(), org.onlab.stc.Step.group(), and org.onlab.stc.Step.name().
Member Data Documentation
final String org.onlab.stc.Step.command protected
Definition at line 31 of file Step.java.
Referenced by org.onlab.stc.GroupTest.basics(), org.onlab.stc.StepTest.basics(), and org.onlab.stc.StepProcessorTest.basics().
final String org.onlab.stc.Step.cwd protected
Definition at line 33 of file Step.java.
Referenced by org.onlab.stc.GroupTest.basics(), and org.onlab.stc.StepTest.basics().
final String org.onlab.stc.Step.env protected
Definition at line 32 of file Step.java.
Referenced by org.onlab.stc.GroupTest.basics(), and org.onlab.stc.StepTest.basics().
final Group org.onlab.stc.Step.group protected
Definition at line 34 of file Step.java.
Referenced by org.onlab.stc.GroupTest.basics(), and org.onlab.stc.StepTest.basics().
final String org.onlab.stc.Step.name protected
Definition at line 30 of file Step.java.
Referenced by org.onlab.stc.GroupTest.basics(), org.onlab.stc.StepTest.basics(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
The documentation for this class was generated from the following file:
utils/stc/src/main/java/org/onlab/stc/Step.java