onos: org.onosproject.net.driver.DefaultDriverProvider Class Reference
org.onosproject.net.driver.DefaultDriverProvider Class Reference
Default driver provider implementation.
Public Member Functions
Set< Driver > getDrivers ()
Returns the set of driver types and behaviour implementations to be made available by this provider.
void addDrivers (Set< Driver > drivers)
Adds the specified drivers to the provider.
void addDriver (Driver driver)
Adds the specified driver to the provider.
void removeDrivers (Set< Driver > drivers)
Removes the specified drivers from the provider.
void removeDriver (Driver driver)
Removes the specified driver from the provider.
String toString ()
Protected Attributes
final Map< String, Driver > drivers = Maps.newConcurrentMap()
Detailed Description
Default driver provider implementation.
Definition at line 29 of file DefaultDriverProvider.java.
Member Function Documentation
void org.onosproject.net.driver.DefaultDriverProvider.addDriver (Driver driver)
Adds the specified driver to the provider.
Parameters
driver driver to be provided
Definition at line 52 of file DefaultDriverProvider.java.
References org.onosproject.net.driver.Driver.merge().
void org.onosproject.net.driver.DefaultDriverProvider.addDrivers (Set< Driver > drivers)
Adds the specified drivers to the provider.
Parameters
drivers drivers to be added
Definition at line 43 of file DefaultDriverProvider.java.
Referenced by org.onosproject.net.driver.impl.DriverManager.registerProvider().
Set<Driver> org.onosproject.net.driver.DefaultDriverProvider.getDrivers ()
Returns the set of driver types and behaviour implementations to be made available by this provider.
Returns
set of driver types and their behaviours
Implements org.onosproject.net.driver.DriverProvider.
Definition at line 34 of file DefaultDriverProvider.java.
void org.onosproject.net.driver.DefaultDriverProvider.removeDriver (Driver driver)
Removes the specified driver from the provider.
Parameters
driver driver to be removed
Definition at line 77 of file DefaultDriverProvider.java.
void org.onosproject.net.driver.DefaultDriverProvider.removeDrivers (Set< Driver > drivers)
Removes the specified drivers from the provider.
Parameters
drivers drivers to be removed
Definition at line 68 of file DefaultDriverProvider.java.
Referenced by org.onosproject.net.driver.impl.DriverManager.unregisterProvider().
String org.onosproject.net.driver.DefaultDriverProvider.toString ()
Definition at line 83 of file DefaultDriverProvider.java.
References org.onosproject.net.driver.DefaultDriverProvider.drivers.
Member Data Documentation
final Map<String, Driver> org.onosproject.net.driver.DefaultDriverProvider.drivers = Maps.newConcurrentMap() protected
Definition at line 31 of file DefaultDriverProvider.java.
Referenced by org.onosproject.net.driver.impl.DriverManager.getDriver(), and org.onosproject.net.driver.DefaultDriverProvider.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/driver/DefaultDriverProvider.java