onos: org.onosproject.provider.of.flow.impl.FlowModBuilderVer10 Class Reference
org.onosproject.provider.of.flow.impl.FlowModBuilderVer10 Class Reference
Flow mod builder for OpenFlow 1.0.
Public Member Functions
OFFlowAdd buildFlowAdd ()
Builds an ADD flow mod.
OFFlowMod buildFlowMod ()
Builds a MODIFY flow mod.
OFFlowDelete buildFlowDel ()
Builds a DELETE flow mod.
Protected Member Functions
FlowModBuilderVer10 (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService)
Constructor for a flow mod builder for OpenFlow 1.0.
Protected Member Functions inherited from org.onosproject.provider.of.flow.impl.FlowModBuilder
FlowModBuilder (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService)
Constructs a flow mod builder.
Match buildMatch ()
Builds the match for the flow mod.
FlowRule flowRule ()
Returns the flow rule for this builder.
OFFactory factory ()
Returns the factory used for building OpenFlow constructs.
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.provider.of.flow.impl.FlowModBuilder
static FlowModBuilder builder (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService)
Creates a new flow mod builder.
Protected Attributes inherited from org.onosproject.provider.of.flow.impl.FlowModBuilder
final Long xid
final Optional< DriverService > driverService
Detailed Description
Flow mod builder for OpenFlow 1.0.
Definition at line 59 of file FlowModBuilderVer10.java.
Constructor & Destructor Documentation
org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.FlowModBuilderVer10 (FlowRule flowRule, OFFactory factory, Optional< Long > xid, Optional< DriverService > driverService) protected
Constructor for a flow mod builder for OpenFlow 1.0.
Parameters
flowRule the flow rule to transform into a flow mod
factory the OpenFlow factory to use to build the flow mod
xid the transaction ID
driverService the device driver service
Definition at line 74 of file FlowModBuilderVer10.java.
Member Function Documentation
OFFlowAdd org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowAdd () virtual
Builds an ADD flow mod.
Returns
the flow mod
Implements org.onosproject.provider.of.flow.impl.FlowModBuilder.
Definition at line 83 of file FlowModBuilderVer10.java.
References org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.provider.of.flow.impl.FlowModBuilder.factory(), org.onosproject.provider.of.flow.impl.FlowModBuilder.flowRule(), and org.onosproject.provider.of.flow.impl.FlowModBuilder.xid.
OFFlowDelete org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowDel () virtual
Builds a DELETE flow mod.
Returns
the flow mod
Implements org.onosproject.provider.of.flow.impl.FlowModBuilder.
Definition at line 124 of file FlowModBuilderVer10.java.
References org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.provider.of.flow.impl.FlowModBuilder.factory(), org.onosproject.provider.of.flow.impl.FlowModBuilder.flowRule(), and org.onosproject.provider.of.flow.impl.FlowModBuilder.xid.
OFFlowMod org.onosproject.provider.of.flow.impl.FlowModBuilderVer10.buildFlowMod () virtual
Builds a MODIFY flow mod.
Returns
the flow mod
Implements org.onosproject.provider.of.flow.impl.FlowModBuilder.
Definition at line 104 of file FlowModBuilderVer10.java.
References org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.provider.of.flow.impl.FlowModBuilder.factory(), org.onosproject.provider.of.flow.impl.FlowModBuilder.flowRule(), and org.onosproject.provider.of.flow.impl.FlowModBuilder.xid.
The documentation for this class was generated from the following file:
providers/openflow/flow/src/main/java/org/onosproject/provider/of/flow/impl/FlowModBuilderVer10.java