onos: org.onosproject.net.proxyarp.impl.ProxyArpManager Class Reference
org.onosproject.net.proxyarp.impl.ProxyArpManager Class Reference
Public Member Functions
void activate ()
void deactivate ()
boolean isKnown (IpAddress addr)
Returns whether this particular IP address is known to the system.
void reply (Ethernet eth, ConnectPoint inPort)
Sends a reply for a given request.
void forward (Ethernet eth, ConnectPoint inPort)
Forwards an ARP or neighbor solicitation request to its destination.
boolean handlePacket (PacketContext context)
Handles a arp or neighbor solicitation packet.
Protected Attributes
EdgePortService edgeService
HostService hostService
PacketService packetService
LinkService linkService
DeviceService deviceService
ProxyArpStore store
InterfaceService interfaceService
Detailed Description
Definition at line 69 of file ProxyArpManager.java.
Member Function Documentation
void org.onosproject.net.proxyarp.impl.ProxyArpManager.activate ()
Definition at line 107 of file ProxyArpManager.java.
void org.onosproject.net.proxyarp.impl.ProxyArpManager.deactivate ()
Definition at line 113 of file ProxyArpManager.java.
void org.onosproject.net.proxyarp.impl.ProxyArpManager.forward (Ethernet eth, ConnectPoint inPort)
Forwards an ARP or neighbor solicitation request to its destination.
Floods at the edg the request if the destination is not known.
Parameters
eth an ethernet frame containing an ARP or neighbor solicitation request.
inPort the port the request was received on
Implements org.onosproject.net.proxyarp.ProxyArpService.
Definition at line 329 of file ProxyArpManager.java.
References org.onlab.packet.Ethernet.getDestinationMAC(), org.onlab.packet.Ethernet.getSourceMAC(), org.onlab.packet.Ethernet.getVlanID(), and org.onlab.packet.Ethernet.serialize().
Referenced by org.onosproject.net.proxyarp.impl.ProxyArpManager.handlePacket().
boolean org.onosproject.net.proxyarp.impl.ProxyArpManager.handlePacket (PacketContext context)
Handles a arp or neighbor solicitation packet.
Replies to arp or neighbor solicitation requests and forwards request to the right place.
Parameters
context the packet context to handle
Returns
true if handled, false otherwise.
Implements org.onosproject.net.proxyarp.ProxyArpService.
Definition at line 347 of file ProxyArpManager.java.
References org.onosproject.net.proxyarp.impl.ProxyArpManager.forward(), and org.onosproject.net.packet.InboundPacket.receivedFrom().
boolean org.onosproject.net.proxyarp.impl.ProxyArpManager.isKnown (IpAddress addr)
Returns whether this particular IP address is known to the system.
Parameters
addr an IP address
Returns
true if know, false otherwise
Implements org.onosproject.net.proxyarp.ProxyArpService.
Definition at line 119 of file ProxyArpManager.java.
References obeliskHostCheck.hosts.
Referenced by org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testKnown(), and org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testNotKnown().
void org.onosproject.net.proxyarp.impl.ProxyArpManager.reply (Ethernet eth, ConnectPoint inPort)
Sends a reply for a given request.
If the host is not known then the arp or neighbor solicitation will be flooded at all edge ports.
Parameters
eth an arp or neighbor solicitation request
inPort the port the request was received on
Implements org.onosproject.net.proxyarp.ProxyArpService.
Definition at line 128 of file ProxyArpManager.java.
Member Data Documentation
DeviceService org.onosproject.net.proxyarp.impl.ProxyArpManager.deviceService protected
Definition at line 90 of file ProxyArpManager.java.
EdgePortService org.onosproject.net.proxyarp.impl.ProxyArpManager.edgeService protected
Definition at line 78 of file ProxyArpManager.java.
HostService org.onosproject.net.proxyarp.impl.ProxyArpManager.hostService protected
Definition at line 81 of file ProxyArpManager.java.
InterfaceService org.onosproject.net.proxyarp.impl.ProxyArpManager.interfaceService protected
Definition at line 96 of file ProxyArpManager.java.
LinkService org.onosproject.net.proxyarp.impl.ProxyArpManager.linkService protected
Definition at line 87 of file ProxyArpManager.java.
PacketService org.onosproject.net.proxyarp.impl.ProxyArpManager.packetService protected
Definition at line 84 of file ProxyArpManager.java.
ProxyArpStore org.onosproject.net.proxyarp.impl.ProxyArpManager.store protected
Definition at line 93 of file ProxyArpManager.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/proxyarp/impl/ProxyArpManager.java