onos: org.onosproject.segmentrouting.DefaultRoutingHandler Class Reference
org.onosproject.segmentrouting.DefaultRoutingHandler Class Reference
Classes
enum Status
Represents the default routing population status.
Public Member Functions
DefaultRoutingHandler (SegmentRoutingManager srManager)
Creates a DefaultRoutingHandler object.
boolean populateAllRoutingRules ()
Populates all routing rules to all connected routers, including default routing rules, adjacency rules, and policy rules if any.
boolean populateRoutingRulesForLinkStatusChange (Link linkFail)
Populates the routing rules according to the route changes due to the link failure or link add.
void populatePortAddressingRules (DeviceId deviceId)
Populates filtering rules for permitting Router DstMac and VLAN.
void startPopulationProcess ()
Start the flow rule population process if it was never started.
void resumePopulationProcess ()
Resume the flow rule population process if it was aborted for any reason.
Detailed Description
Definition at line 40 of file DefaultRoutingHandler.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.DefaultRoutingHandler.DefaultRoutingHandler (SegmentRoutingManager srManager)
Creates a DefaultRoutingHandler object.
Parameters
srManager SegmentRoutingManager object
Definition at line 76 of file DefaultRoutingHandler.java.
References org.onosproject.segmentrouting.SegmentRoutingManager.deviceConfiguration, org.onosproject.segmentrouting.DefaultRoutingHandler.Status.IDLE, and org.onosproject.segmentrouting.SegmentRoutingManager.routingRulePopulator.
Member Function Documentation
boolean org.onosproject.segmentrouting.DefaultRoutingHandler.populateAllRoutingRules ()
Populates all routing rules to all connected routers, including default routing rules, adjacency rules, and policy rules if any.
Returns
true if it succeeds in populating all rules, otherwise false
Definition at line 90 of file DefaultRoutingHandler.java.
References org.onosproject.segmentrouting.DefaultRoutingHandler.Status.ABORTED, org.onosproject.segmentrouting.SegmentRoutingManager.deviceService, org.onosproject.net.device.DeviceService.getDevices(), org.onosproject.mastership.MastershipService.isLocalMaster(), org.onosproject.segmentrouting.SegmentRoutingManager.mastershipService, org.onosproject.segmentrouting.DefaultRoutingHandler.Status.STARTED, and org.onosproject.segmentrouting.DefaultRoutingHandler.Status.SUCCEEDED.
Referenced by org.onosproject.segmentrouting.DefaultRoutingHandler.resumePopulationProcess(), and org.onosproject.segmentrouting.DefaultRoutingHandler.startPopulationProcess().
void org.onosproject.segmentrouting.DefaultRoutingHandler.populatePortAddressingRules (DeviceId deviceId)
Populates filtering rules for permitting Router DstMac and VLAN.
Parameters
deviceId Switch ID to set the rules
Definition at line 513 of file DefaultRoutingHandler.java.
References find-flow.deviceId.
boolean org.onosproject.segmentrouting.DefaultRoutingHandler.populateRoutingRulesForLinkStatusChange (Link linkFail)
Populates the routing rules according to the route changes due to the link failure or link add.
It computes the routes changed due to the link changes and repopulates the rules only for the routes.
Parameters
linkFail link failed, null for link added
Returns
true if it succeeds to populate all rules, false otherwise
Definition at line 136 of file DefaultRoutingHandler.java.
References org.onosproject.segmentrouting.DefaultRoutingHandler.Status.ABORTED, org.onosproject.segmentrouting.SegmentRoutingManager.deviceService, org.onosproject.net.device.DeviceService.getDevices(), org.onosproject.mastership.MastershipService.isLocalMaster(), org.onosproject.segmentrouting.SegmentRoutingManager.mastershipService, org.onosproject.segmentrouting.DefaultRoutingHandler.Status.STARTED, and org.onosproject.segmentrouting.DefaultRoutingHandler.Status.SUCCEEDED.
void org.onosproject.segmentrouting.DefaultRoutingHandler.resumePopulationProcess ()
Resume the flow rule population process if it was aborted for any reason.
Mostly the process is aborted when the groups required are not set yet. XXX is this called?
Definition at line 546 of file DefaultRoutingHandler.java.
References org.onosproject.segmentrouting.DefaultRoutingHandler.Status.ABORTED, org.onosproject.segmentrouting.DefaultRoutingHandler.populateAllRoutingRules(), and org.onosproject.segmentrouting.DefaultRoutingHandler.Status.STARTED.
void org.onosproject.segmentrouting.DefaultRoutingHandler.startPopulationProcess ()
Start the flow rule population process if it was never started.
The process finishes successfully when all flow rules are set and stops with ABORTED status when any groups required for flows is not set yet.
Definition at line 523 of file DefaultRoutingHandler.java.
References org.onosproject.segmentrouting.DefaultRoutingHandler.Status.ABORTED, org.onosproject.segmentrouting.DefaultRoutingHandler.Status.IDLE, org.onosproject.segmentrouting.DefaultRoutingHandler.populateAllRoutingRules(), org.onosproject.segmentrouting.DefaultRoutingHandler.Status.STARTED, and org.onosproject.segmentrouting.DefaultRoutingHandler.Status.SUCCEEDED.
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/DefaultRoutingHandler.java