onos: org.onosproject.net.DefaultPort Class Reference
org.onosproject.net.DefaultPort Class Reference
Default port implementation.
Public Member Functions
DefaultPort (Element element, PortNumber number, boolean isEnabled, Annotations...annotations)
Creates a network element attributed to the specified provider.
DefaultPort (Element element, PortNumber number, boolean isEnabled, Type type, long portSpeed, Annotations...annotations)
Creates a network element attributed to the specified provider.
Element element ()
Returns the parent network element to which this port belongs.
PortNumber number ()
Returns the port number.
boolean isEnabled ()
Indicates whether or not the port is currently up and active.
Type type ()
Returns the port type.
long portSpeed ()
Returns the current port speed in Mbps.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Static Public Attributes
static final long DEFAULT_SPEED = 1_000
Default port speed in Mbps.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default port implementation.
Definition at line 25 of file DefaultPort.java.
Constructor & Destructor Documentation
org.onosproject.net.DefaultPort.DefaultPort (Element element, PortNumber number, boolean isEnabled, Annotations... annotations)
Creates a network element attributed to the specified provider.
Parameters
element parent network element
number port number
isEnabled indicator whether the port is up and active
annotations optional key/value annotations
Definition at line 44 of file DefaultPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.Port.Type.COPPER, org.onosproject.net.DefaultPort.DEFAULT_SPEED, org.onosproject.net.DefaultPort.element(), org.onosproject.net.DefaultPort.isEnabled(), and org.onosproject.net.DefaultPort.number().
Referenced by org.onosproject.net.DefaultPort.equals().
org.onosproject.net.DefaultPort.DefaultPort (Element element, PortNumber number, boolean isEnabled, Type type, long portSpeed, Annotations... annotations)
Creates a network element attributed to the specified provider.
Parameters
element parent network element
number port number
isEnabled indicator whether the port is up and active
type port type
portSpeed port speed in Mbs
annotations optional key/value annotations
Definition at line 59 of file DefaultPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultPort.element(), org.onosproject.net.DefaultPort.isEnabled(), org.onosproject.net.DefaultPort.number(), org.onosproject.net.DefaultPort.portSpeed(), and org.onosproject.net.DefaultPort.type().
Member Function Documentation
Element org.onosproject.net.DefaultPort.element ()
Returns the parent network element to which this port belongs.
Returns
parent network element
Implements org.onosproject.net.Port.
Definition at line 70 of file DefaultPort.java.
Referenced by org.onosproject.net.DefaultPort.DefaultPort(), org.onosproject.net.OduCltPort.toString(), org.onosproject.net.OchPort.toString(), and org.onosproject.net.OmsPort.toString().
boolean org.onosproject.net.DefaultPort.equals (Object obj)
Definition at line 100 of file DefaultPort.java.
References org.onosproject.net.DefaultPort.DefaultPort(), and org.onosproject.net.Element.id().
int org.onosproject.net.DefaultPort.hashCode ()
Definition at line 95 of file DefaultPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultPort.isEnabled(), org.onosproject.net.DefaultPort.number(), org.onosproject.net.DefaultPort.portSpeed(), and org.onosproject.net.DefaultPort.type().
boolean org.onosproject.net.DefaultPort.isEnabled ()
Indicates whether or not the port is currently up and active.
Returns
true if the port is operational
Implements org.onosproject.net.Port.
Definition at line 80 of file DefaultPort.java.
Referenced by org.onosproject.net.DefaultPort.DefaultPort(), org.onosproject.net.OduCltPort.equals(), org.onosproject.net.OchPort.equals(), org.onosproject.net.OmsPort.equals(), org.onosproject.net.OduCltPort.hashCode(), org.onosproject.net.OchPort.hashCode(), org.onosproject.net.DefaultPort.hashCode(), org.onosproject.net.OmsPort.hashCode(), org.onosproject.net.OduCltPort.toString(), org.onosproject.net.OchPort.toString(), org.onosproject.net.DefaultPort.toString(), and org.onosproject.net.OmsPort.toString().
PortNumber org.onosproject.net.DefaultPort.number ()
Returns the port number.
Returns
port number
Implements org.onosproject.net.Port.
Definition at line 75 of file DefaultPort.java.
Referenced by org.onosproject.net.DefaultPort.DefaultPort(), org.onosproject.net.OduCltPort.hashCode(), org.onosproject.net.OchPort.hashCode(), org.onosproject.net.OmsPort.hashCode(), org.onosproject.net.DefaultPort.hashCode(), org.onosproject.net.OduCltPort.toString(), org.onosproject.net.OchPort.toString(), org.onosproject.net.DefaultPort.toString(), and org.onosproject.net.OmsPort.toString().
long org.onosproject.net.DefaultPort.portSpeed ()
Returns the current port speed in Mbps.
Returns
current port speed
Implements org.onosproject.net.Port.
Definition at line 90 of file DefaultPort.java.
Referenced by org.onosproject.net.DefaultPort.DefaultPort(), org.onosproject.net.DefaultPort.hashCode(), org.onosproject.cli.net.DevicePortsListCommand.printDevice(), and org.onosproject.net.DefaultPort.toString().
String org.onosproject.net.DefaultPort.toString ()
Definition at line 117 of file DefaultPort.java.
References org.onosproject.net.DefaultPort.isEnabled(), org.onosproject.net.DefaultPort.number(), org.onosproject.net.DefaultPort.portSpeed(), and org.onosproject.net.DefaultPort.type().
Type org.onosproject.net.DefaultPort.type ()
Returns the port type.
Returns
port type
Implements org.onosproject.net.Port.
Definition at line 85 of file DefaultPort.java.
Referenced by org.onosproject.net.DefaultPort.DefaultPort(), org.onosproject.net.OduCltPort.hashCode(), org.onosproject.net.OchPort.hashCode(), org.onosproject.net.OmsPort.hashCode(), org.onosproject.net.DefaultPort.hashCode(), org.onosproject.net.OduCltPort.toString(), org.onosproject.net.OchPort.toString(), org.onosproject.net.DefaultPort.toString(), and org.onosproject.net.OmsPort.toString().
Member Data Documentation
final long org.onosproject.net.DefaultPort.DEFAULT_SPEED = 1_000 static
Default port speed in Mbps.
Definition at line 28 of file DefaultPort.java.
Referenced by org.onosproject.net.DefaultPort.DefaultPort().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/DefaultPort.java