onos: org.onosproject.ui.topo.LinkHighlightTest Class Reference
org.onosproject.ui.topo.LinkHighlightTest Class Reference
Unit tests for LinkHighlight.
Public Member Functions
void basic ()
void primaryOptical ()
void secondaryAnimatedWithLabel ()
void customMod ()
void severalMods ()
void noFlavor ()
void noIdentity ()
Detailed Description
Unit tests for LinkHighlight.
Definition at line 30 of file LinkHighlightTest.java.
Member Function Documentation
void org.onosproject.ui.topo.LinkHighlightTest.basic ()
Definition at line 42 of file LinkHighlightTest.java.
References org.onosproject.ui.topo.LinkHighlight.cssClasses().
void org.onosproject.ui.topo.LinkHighlightTest.customMod ()
Definition at line 79 of file LinkHighlightTest.java.
References org.onosproject.ui.topo.LinkHighlight.cssClasses(), and org.onosproject.ui.topo.Mod.toString().
void org.onosproject.ui.topo.LinkHighlightTest.noFlavor ()
Definition at line 106 of file LinkHighlightTest.java.
void org.onosproject.ui.topo.LinkHighlightTest.noIdentity ()
Definition at line 111 of file LinkHighlightTest.java.
void org.onosproject.ui.topo.LinkHighlightTest.primaryOptical ()
Definition at line 52 of file LinkHighlightTest.java.
References org.onosproject.ui.topo.LinkHighlight.cssClasses(), and org.onosproject.ui.topo.LinkHighlight.MOD_OPTICAL.
void org.onosproject.ui.topo.LinkHighlightTest.secondaryAnimatedWithLabel ()
Definition at line 65 of file LinkHighlightTest.java.
References org.onosproject.ui.topo.LinkHighlight.cssClasses(), and org.onosproject.ui.topo.LinkHighlight.MOD_ANIMATED.
void org.onosproject.ui.topo.LinkHighlightTest.severalMods ()
Definition at line 90 of file LinkHighlightTest.java.
References org.onosproject.ui.topo.LinkHighlight.cssClasses(), org.onosproject.ui.topo.LinkHighlight.MOD_ANIMATED, and org.onosproject.ui.topo.LinkHighlight.MOD_OPTICAL.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/ui/topo/LinkHighlightTest.java