onos: org.onosproject.pcepio.types.PcepRsvpSpecObjHeader Class Reference
org.onosproject.pcepio.types.PcepRsvpSpecObjHeader Class Reference
Provides PcepRsvpObjectHeader.
Public Member Functions
PcepRsvpSpecObjHeader (short objLen, byte objClassNum, byte objClassType)
Constructor to initialize length, class num and type.
void setObjClassNum (byte value)
Sets the Class num.
void setObjClassType (byte value)
Sets the Class type.
void setObjLen (short value)
Sets the Class Length.
short getObjLen ()
Returns Object Length.
byte getObjClassNum ()
Returns Object num.
byte getObjClassType ()
Returns Object type.
int write (ChannelBuffer cb)
Writes the byte stream of PcepRsvpObjectHeader to channel buffer.
String toString ()
Static Public Member Functions
static PcepRsvpSpecObjHeader read (ChannelBuffer cb)
Reads the PcepRsvpObjectHeader.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepRsvpSpecObjHeader.class)
Detailed Description
Provides PcepRsvpObjectHeader.
Definition at line 28 of file PcepRsvpSpecObjHeader.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.PcepRsvpSpecObjHeader (short objLen, byte objClassNum, byte objClassType)
Constructor to initialize length, class num and type.
Parameters
objLen object length
objClassNum pcep rsvp error spec object class num
objClassType pcep rsvp error spec object class type
Definition at line 56 of file PcepRsvpSpecObjHeader.java.
Referenced by org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.read().
Member Function Documentation
byte org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.getObjClassNum ()
Returns Object num.
Returns
objClassNum pcep rsvp error spec object class num
Definition at line 103 of file PcepRsvpSpecObjHeader.java.
Referenced by org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.read().
byte org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.getObjClassType ()
Returns Object type.
Returns
objClassType pcep rsvp error spec object class type
Definition at line 112 of file PcepRsvpSpecObjHeader.java.
short org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.getObjLen ()
Returns Object Length.
Returns
objLen pcep rsvp error spec object length
Definition at line 94 of file PcepRsvpSpecObjHeader.java.
static PcepRsvpSpecObjHeader org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.read (ChannelBuffer cb) static
Reads the PcepRsvpObjectHeader.
Parameters
cb of type channel buffer
Returns
PcepRsvpObjectHeader
Definition at line 137 of file PcepRsvpSpecObjHeader.java.
References org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.PcepRsvpSpecObjHeader().
void org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.setObjClassNum (byte value)
Sets the Class num.
Parameters
value pcep rsvp error spec object class num
Definition at line 67 of file PcepRsvpSpecObjHeader.java.
void org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.setObjClassType (byte value)
Sets the Class type.
Parameters
value pcep rsvp error spec object class type
Definition at line 76 of file PcepRsvpSpecObjHeader.java.
void org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.setObjLen (short value)
Sets the Class Length.
Parameters
value pcep rsvp error spec object length
Definition at line 85 of file PcepRsvpSpecObjHeader.java.
String org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.toString ()
Definition at line 149 of file PcepRsvpSpecObjHeader.java.
int org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.write (ChannelBuffer cb)
Writes the byte stream of PcepRsvpObjectHeader to channel buffer.
Parameters
cb of type channel buffer
Returns
object length index
Definition at line 122 of file PcepRsvpSpecObjHeader.java.
Member Data Documentation
final Logger org.onosproject.pcepio.types.PcepRsvpSpecObjHeader.log = LoggerFactory.getLogger(PcepRsvpSpecObjHeader.class) static protected
Definition at line 43 of file PcepRsvpSpecObjHeader.java.
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/PcepRsvpSpecObjHeader.java