onos: org.onlab.packet.ipv6.FragmentTest Class Reference
org.onlab.packet.ipv6.FragmentTest Class Reference
Tests for class Fragment.
Public Member Functions
void setUp ()
void testSerialize ()
Tests serialize and setters.
void testDeserialize () throws DeserializationException
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class Fragment.
Definition at line 36 of file FragmentTest.java.
Member Function Documentation
void org.onlab.packet.ipv6.FragmentTest.setUp ()
Definition at line 61 of file FragmentTest.java.
static void org.onlab.packet.ipv6.FragmentTest.setUpBeforeClass () throws Exception static
Definition at line 44 of file FragmentTest.java.
References find-link-in-cluster.length.
void org.onlab.packet.ipv6.FragmentTest.testDeserialize () throws DeserializationException
Tests deserialize and getters.
Definition at line 84 of file FragmentTest.java.
References org.onlab.packet.ipv6.Fragment.getFragmentOffset(), org.onlab.packet.ipv6.Fragment.getIdentification(), org.onlab.packet.ipv6.Fragment.getMoreFragment(), org.onlab.packet.ipv6.Fragment.getNextHeader(), and find-link-in-cluster.length.
void org.onlab.packet.ipv6.FragmentTest.testEqual ()
Tests comparator.
Definition at line 97 of file FragmentTest.java.
References org.onlab.packet.ipv6.Fragment.equals().
void org.onlab.packet.ipv6.FragmentTest.testSerialize ()
Tests serialize and setters.
Definition at line 69 of file FragmentTest.java.
References org.onlab.packet.ipv6.Fragment.serialize().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ipv6/FragmentTest.java