onos: org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv Class Reference
org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv Class Reference
Provides IPv6 TE Router Id of Local Node.
Public Member Functions
IPv6TERouterIdofLocalNodeTlv (byte[] rawValue)
Constructor to initialize rawValue.
byte[] getBytes ()
Returns value of IPv6 TE Router Id of Local Node.
byte[] getValue ()
Returns value of IPv6 TE Router Id of Local Node.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static IPv6TERouterIdofLocalNodeTlv of (final byte[] raw)
Returns newly created IPv6TERouterIdofLocalNodeTlv object.
static IPv6TERouterIdofLocalNodeTlv read20Bytes (ChannelBuffer c)
Reads the channel buffer and returns object of IPv6TERouterIdofLocalNodeTlv.
Static Public Attributes
static final short TYPE = 140
static final short LENGTH = 20
static final byte VALUE_LENGTH = 18
static final
IPv6TERouterIdofLocalNodeTlv NONE = new IPv6TERouterIdofLocalNodeTlv(NONE_VAL)
static final
IPv6TERouterIdofLocalNodeTlv NO_MASK = new IPv6TERouterIdofLocalNodeTlv(NO_MASK_VAL)
static final
IPv6TERouterIdofLocalNodeTlv FULL_MASK = NONE
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IPv6TERouterIdofLocalNodeTlv.class)
Detailed Description
Provides IPv6 TE Router Id of Local Node.
Reference :[RFC6119]/4.1.
Definition at line 31 of file IPv6TERouterIdofLocalNodeTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.IPv6TERouterIdofLocalNodeTlv (byte[] rawValue)
Constructor to initialize rawValue.
Parameters
rawValue IPv6TERouterIdofLocalNodeTlv
Definition at line 54 of file IPv6TERouterIdofLocalNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.equals(), and org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.equals (Object obj)
Definition at line 132 of file IPv6TERouterIdofLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.IPv6TERouterIdofLocalNodeTlv().
byte [] org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.getBytes ()
Returns value of IPv6 TE Router Id of Local Node.
Returns
byte array value of rawValue
Definition at line 98 of file IPv6TERouterIdofLocalNodeTlv.java.
short org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 122 of file IPv6TERouterIdofLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.LENGTH.
short org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 117 of file IPv6TERouterIdofLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.TYPE.
byte [] org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.getValue ()
Returns value of IPv6 TE Router Id of Local Node.
Returns
byte array value of rawValue
Definition at line 107 of file IPv6TERouterIdofLocalNodeTlv.java.
PcepVersion org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 112 of file IPv6TERouterIdofLocalNodeTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.hashCode ()
Definition at line 127 of file IPv6TERouterIdofLocalNodeTlv.java.
static IPv6TERouterIdofLocalNodeTlv org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.of (final byte[] raw) static
Returns newly created IPv6TERouterIdofLocalNodeTlv object.
Parameters
raw IPv6 TE Router Id of Local Node
Returns
object of IPv6TERouterIdofLocalNodeTlv
Definition at line 64 of file IPv6TERouterIdofLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.IPv6TERouterIdofLocalNodeTlv(), org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.NO_MASK, and org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.NONE.
static IPv6TERouterIdofLocalNodeTlv org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.read20Bytes (ChannelBuffer c) static
Reads the channel buffer and returns object of IPv6TERouterIdofLocalNodeTlv.
Parameters
c input channel buffer
Returns
object of IPv6TERouterIdofLocalNodeTlv
Definition at line 158 of file IPv6TERouterIdofLocalNodeTlv.java.
String org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.toString ()
Definition at line 165 of file IPv6TERouterIdofLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.LENGTH, and org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.TYPE.
int org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 144 of file IPv6TERouterIdofLocalNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.LENGTH, and org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.TYPE.
Member Data Documentation
final IPv6TERouterIdofLocalNodeTlv org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.FULL_MASK = NONE static
Definition at line 45 of file IPv6TERouterIdofLocalNodeTlv.java.
final short org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.LENGTH = 20 static
Definition at line 35 of file IPv6TERouterIdofLocalNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.getLength(), org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.toString(), and org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.write().
final Logger org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.log = LoggerFactory.getLogger(IPv6TERouterIdofLocalNodeTlv.class) static protected
Definition at line 32 of file IPv6TERouterIdofLocalNodeTlv.java.
final IPv6TERouterIdofLocalNodeTlv org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.NO_MASK = new IPv6TERouterIdofLocalNodeTlv(NO_MASK_VAL) static
Definition at line 44 of file IPv6TERouterIdofLocalNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.of().
final IPv6TERouterIdofLocalNodeTlv org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.NONE = new IPv6TERouterIdofLocalNodeTlv(NONE_VAL) static
Definition at line 39 of file IPv6TERouterIdofLocalNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.of().
final short org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.TYPE = 140 static
Definition at line 34 of file IPv6TERouterIdofLocalNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.getType(), org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.toString(), and org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.write().
final byte org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.VALUE_LENGTH = 18 static
Definition at line 36 of file IPv6TERouterIdofLocalNodeTlv.java.
Referenced by org.onosproject.pcepio.types.TENodeAttributesTlv.read(), and org.onosproject.pcepio.types.TELinkAttributesTlv.read().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IPv6TERouterIdofLocalNodeTlv.java