onos: org.onlab.packet.VlanId Class Reference
org.onlab.packet.VlanId Class Reference
Representation of a VLAN ID.
Public Member Functions
short toShort ()
boolean equals (Object obj)
int hashCode ()
String toString ()
Static Public Member Functions
static VlanId vlanId ()
static VlanId vlanId (short value)
Static Public Attributes
static final short UNTAGGED = (short) 0xffff
static final short ANY_VALUE = (short) 0x1000
static final VlanId NONE = VlanId.vlanId(UNTAGGED)
static final VlanId ANY = VlanId.vlanId(ANY_VALUE)
static final short MAX_VLAN = 4095
Protected Member Functions
VlanId ()
VlanId (short value)
Detailed Description
Representation of a VLAN ID.
Definition at line 21 of file VlanId.java.
Constructor & Destructor Documentation
org.onlab.packet.VlanId.VlanId () protected
Definition at line 39 of file VlanId.java.
References org.onlab.packet.VlanId.UNTAGGED.
Referenced by org.onlab.packet.VlanId.equals(), and org.onlab.packet.VlanId.vlanId().
org.onlab.packet.VlanId.VlanId (short value) protected
Definition at line 43 of file VlanId.java.
Member Function Documentation
boolean org.onlab.packet.VlanId.equals (Object obj)
Definition at line 72 of file VlanId.java.
References org.onlab.packet.VlanId.VlanId().
Referenced by org.onosproject.routing.config.Interface.equals().
int org.onlab.packet.VlanId.hashCode ()
Definition at line 90 of file VlanId.java.
short org.onlab.packet.VlanId.toShort ()
Definition at line 67 of file VlanId.java.
Referenced by org.onosproject.xosintegration.OnosXosIntegrationManager.addTenant(), and org.onlab.packet.VlanIdTest.basics().
String org.onlab.packet.VlanId.toString ()
Definition at line 95 of file VlanId.java.
References org.onlab.packet.VlanId.ANY_VALUE.
static VlanId org.onlab.packet.VlanId.vlanId () static
Definition at line 47 of file VlanId.java.
References org.onlab.packet.VlanId.UNTAGGED, and org.onlab.packet.VlanId.VlanId().
Referenced by org.onosproject.codec.impl.FlowRuleCodecTest.codecCriteriaFlowTest(), org.onosproject.cordfabric.FabricVlanCodec.decode(), org.onosproject.cli.net.InterfaceRemoveCommand.execute(), org.onosproject.net.HostId.hostId(), org.onosproject.codec.impl.InstructionCodecTest.modVlanIdInstructionTest(), org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterMacVlanFilters(), org.onosproject.net.intent.impl.compiler.HostToHostIntentCompilerTest.setUp(), org.onosproject.net.flow.DefaultTrafficTreatmentTest.testBuilderMethods(), org.onosproject.net.flow.DefaultTrafficSelectorTest.testCriteriaCreation(), org.onlab.packet.VlanIdTest.testEquality(), and org.onosproject.incubator.net.intf.impl.InterfaceManagerTest.testUpdateInterface().
static VlanId org.onlab.packet.VlanId.vlanId (short value) static
Definition at line 51 of file VlanId.java.
References org.onlab.packet.VlanId.ANY_VALUE, org.onlab.packet.VlanId.MAX_VLAN, org.onlab.packet.VlanId.UNTAGGED, and org.onlab.packet.VlanId.VlanId().
Member Data Documentation
final VlanId org.onlab.packet.VlanId.ANY = VlanId.vlanId(ANY_VALUE) static
Definition at line 34 of file VlanId.java.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.codec.impl.CriterionCodecTest.matchVlanIdTest(), org.onosproject.driver.pipeline.OVSCorsaPipeline.processVlanMplsTable(), org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityHostToInternet(), and org.onosproject.sdnip.SdnIpFibTest.testFibAddWithVlan().
final short org.onlab.packet.VlanId.ANY_VALUE = (short) 0x1000 static
Definition at line 31 of file VlanId.java.
Referenced by org.onlab.packet.VlanId.toString(), and org.onlab.packet.VlanId.vlanId().
final short org.onlab.packet.VlanId.MAX_VLAN = 4095 static
Definition at line 37 of file VlanId.java.
Referenced by org.onlab.packet.VlanId.vlanId().
final VlanId org.onlab.packet.VlanId.NONE = VlanId.vlanId(UNTAGGED) static
Definition at line 33 of file VlanId.java.
Referenced by org.onosproject.incubator.net.config.basics.InterfaceConfig.addInterface(), org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.provider.nil.TopologySimulator.createHosts(), org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterMacVlanFilters(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstFilter(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processVlanIdFilter(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processVlanIdFilter(), org.onosproject.driver.pipeline.SpringOpenTTP.processVlanIdFilter(), org.onosproject.pim.impl.PIMPacketHandler.sendPacket(), org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityHostToInternet(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExist(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExist(), org.onosproject.routing.impl.RouterAsyncArpTest.testRouteAdd(), and org.onosproject.routing.impl.RouterAsyncArpTest.testRouteUpdate().
final short org.onlab.packet.VlanId.UNTAGGED = (short) 0xffff static
Definition at line 26 of file VlanId.java.
Referenced by org.onlab.packet.VlanIdTest.basics(), org.onosproject.net.HostId.hostId(), org.onlab.packet.VlanId.VlanId(), and org.onlab.packet.VlanId.vlanId().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/VlanId.java