onos: org.onosproject.store.consistent.impl.DefaultTransaction Class Reference
org.onosproject.store.consistent.impl.DefaultTransaction Class Reference
A Default transaction implementation.
Public Member Functions
DefaultTransaction (long transactionId, List< DatabaseUpdate > updates)
long id ()
Returns the transaction Id.
List< DatabaseUpdate > updates ()
Returns the list of updates that are part of this transaction.
State state ()
Returns the current state of this transaction.
Transaction transition (State newState)
Returns a new transaction that is created by transitioning this one to the specified state.
long lastUpdated ()
Returns the system time when the transaction was last updated.
Public Member Functions inherited from org.onosproject.store.service.Transaction
default boolean isDone ()
Returns true if this transaction has completed execution.
Detailed Description
A Default transaction implementation.
Definition at line 28 of file DefaultTransaction.java.
Constructor & Destructor Documentation
org.onosproject.store.consistent.impl.DefaultTransaction.DefaultTransaction (long transactionId, List< DatabaseUpdate > updates)
Definition at line 35 of file DefaultTransaction.java.
References org.onosproject.store.service.Transaction.State.PREPARING, and org.onosproject.store.consistent.impl.DefaultTransaction.updates().
Referenced by org.onosproject.store.consistent.impl.DefaultTransaction.transition().
Member Function Documentation
long org.onosproject.store.consistent.impl.DefaultTransaction.id ()
Returns the transaction Id.
Returns
transaction id
Implements org.onosproject.store.service.Transaction.
Definition at line 47 of file DefaultTransaction.java.
long org.onosproject.store.consistent.impl.DefaultTransaction.lastUpdated ()
Returns the system time when the transaction was last updated.
Returns
last update time
Implements org.onosproject.store.service.Transaction.
Definition at line 67 of file DefaultTransaction.java.
State org.onosproject.store.consistent.impl.DefaultTransaction.state ()
Returns the current state of this transaction.
Returns
transaction state
Implements org.onosproject.store.service.Transaction.
Definition at line 57 of file DefaultTransaction.java.
Transaction org.onosproject.store.consistent.impl.DefaultTransaction.transition (State newState)
Returns a new transaction that is created by transitioning this one to the specified state.
Parameters
newState destination state
Returns
a new transaction instance similar to the current one but its state set to specified state
Implements org.onosproject.store.service.Transaction.
Definition at line 62 of file DefaultTransaction.java.
References org.onosproject.store.consistent.impl.DefaultTransaction.DefaultTransaction(), and org.onosproject.store.consistent.impl.DefaultTransaction.updates().
List<DatabaseUpdate> org.onosproject.store.consistent.impl.DefaultTransaction.updates ()
Returns the list of updates that are part of this transaction.
Returns
list of database updates
Implements org.onosproject.store.service.Transaction.
Definition at line 52 of file DefaultTransaction.java.
Referenced by org.onosproject.store.consistent.impl.DefaultTransaction.DefaultTransaction(), and org.onosproject.store.consistent.impl.DefaultTransaction.transition().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DefaultTransaction.java