onos: org.onosproject.openstackswitching.OpenstackPort Class Reference
org.onosproject.openstackswitching.OpenstackPort Class Reference
It represents the Openstack Port information.
Classes
class Builder
OpenstackPort Builder class.
enum PortStatus
Public Member Functions
PortStatus status ()
Returns port status.
String name ()
Returns port name.
boolean isAdminStateUp ()
Returns whether admin state up or not.
String networkId ()
Returns network ID.
String deviceOwner ()
Returns device owner.
MacAddress macAddress ()
Returns mac address.
HashMap fixedIps ()
Returns the fixed IP information.
String id ()
Returns port ID.
List< String > securityGroups ()
Returns security group information.
String deviceId ()
Returns device ID.
Object clone ()
Static Public Member Functions
static OpenstackPort.Builder builder ()
Returns OpenstackPort builder object.
Detailed Description
It represents the Openstack Port information.
Definition at line 31 of file OpenstackPort.java.
Member Function Documentation
static OpenstackPort.Builder org.onosproject.openstackswitching.OpenstackPort.builder () static
Returns OpenstackPort builder object.
Returns
OpenstackPort builder
Definition at line 79 of file OpenstackPort.java.
Object org.onosproject.openstackswitching.OpenstackPort.clone ()
Definition at line 185 of file OpenstackPort.java.
References org.onosproject.openstackswitching.OpenstackPort.deviceId(), org.onosproject.openstackswitching.OpenstackPort.deviceOwner(), org.onosproject.openstackswitching.OpenstackPort.fixedIps(), find-device.id, org.onosproject.openstackswitching.OpenstackPort.macAddress(), org.onosproject.openstackswitching.OpenstackPort.name(), org.onosproject.openstackswitching.OpenstackPort.networkId(), and org.onosproject.openstackswitching.OpenstackPort.status().
String org.onosproject.openstackswitching.OpenstackPort.deviceId ()
Returns device ID.
Returns
device ID
Definition at line 169 of file OpenstackPort.java.
Referenced by org.onosproject.openstackswitching.OpenstackPort.clone().
String org.onosproject.openstackswitching.OpenstackPort.deviceOwner ()
Returns device owner.
Returns
device owner
Definition at line 124 of file OpenstackPort.java.
Referenced by org.onosproject.openstackswitching.OpenstackPort.clone().
HashMap org.onosproject.openstackswitching.OpenstackPort.fixedIps ()
Returns the fixed IP information.
Returns
fixed IP info
Definition at line 142 of file OpenstackPort.java.
Referenced by org.onosproject.openstackswitching.OpenstackPort.clone().
String org.onosproject.openstackswitching.OpenstackPort.id ()
Returns port ID.
Returns
port ID
Definition at line 151 of file OpenstackPort.java.
boolean org.onosproject.openstackswitching.OpenstackPort.isAdminStateUp ()
Returns whether admin state up or not.
Returns
true if admin state up, false otherwise
Definition at line 106 of file OpenstackPort.java.
MacAddress org.onosproject.openstackswitching.OpenstackPort.macAddress ()
Returns mac address.
Returns
mac address
Definition at line 133 of file OpenstackPort.java.
Referenced by org.onosproject.openstackswitching.OpenstackPort.clone().
String org.onosproject.openstackswitching.OpenstackPort.name ()
Returns port name.
Returns
port name
Definition at line 97 of file OpenstackPort.java.
Referenced by org.onosproject.openstackswitching.OpenstackPort.clone(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.openstackswitching.OpenstackPort.networkId ()
Returns network ID.
Returns
network ID
Definition at line 115 of file OpenstackPort.java.
Referenced by org.onosproject.openstackswitching.OpenstackPort.clone().
List<String> org.onosproject.openstackswitching.OpenstackPort.securityGroups ()
Returns security group information.
Returns
security group info
Definition at line 160 of file OpenstackPort.java.
PortStatus org.onosproject.openstackswitching.OpenstackPort.status ()
Returns port status.
Returns
port status
Definition at line 88 of file OpenstackPort.java.
Referenced by org.onosproject.openstackswitching.OpenstackPort.clone().
The documentation for this class was generated from the following file:
apps/openstackswitching/api/src/main/java/org/onosproject/openstackswitching/OpenstackPort.java