onos: org.onosproject.net.DefaultDevice Class Reference
org.onosproject.net.DefaultDevice Class Reference
Default infrastructure device model implementation.
Public Member Functions
DefaultDevice (ProviderId providerId, DeviceId id, Type type, String manufacturer, String hwVersion, String swVersion, String serialNumber, ChassisId chassisId, Annotations...annotations)
Creates a network element attributed to the specified provider.
DeviceId id ()
Returns the device identifier.
Type type ()
Returns the type of the infrastructure device.
String manufacturer ()
Returns the device manufacturer name.
String hwVersion ()
Returns the device hardware version.
String swVersion ()
Returns the device software version.
String serialNumber ()
Returns the device serial number.
ChassisId chassisId ()
Returns the device chassis id.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractElement
AbstractElement ()
Public Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel ()
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractElement
AbstractElement (ProviderId providerId, ElementId id, Annotations...annotations)
Creates a network element attributed to the specified provider.
Protected Member Functions inherited from org.onosproject.net.AbstractModel
AbstractModel (ProviderId providerId, Annotations...annotations)
Creates a model entity attributed to the specified provider and optionally annotated.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Protected Attributes inherited from org.onosproject.net.AbstractElement
final ElementId id
Detailed Description
Default infrastructure device model implementation.
Definition at line 28 of file DefaultDevice.java.
Constructor & Destructor Documentation
org.onosproject.net.DefaultDevice.DefaultDevice (ProviderId providerId, DeviceId id, Type type, String manufacturer, String hwVersion, String swVersion, String serialNumber, ChassisId chassisId, Annotations... annotations)
Creates a network element attributed to the specified provider.
Parameters
providerId identity of the provider
id device identifier
type device type
manufacturer device manufacturer
hwVersion device HW version
swVersion device SW version
serialNumber device serial number
chassisId chassis id
annotations optional key/value annotations
Definition at line 60 of file DefaultDevice.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultDevice.chassisId(), org.onosproject.net.DefaultDevice.hwVersion(), org.onosproject.net.DefaultDevice.manufacturer(), org.onosproject.net.DefaultDevice.serialNumber(), org.onosproject.net.DefaultDevice.swVersion(), and org.onosproject.net.DefaultDevice.type().
Member Function Documentation
ChassisId org.onosproject.net.DefaultDevice.chassisId ()
Returns the device chassis id.
Returns
chassis id
Implements org.onosproject.net.Device.
Definition at line 104 of file DefaultDevice.java.
Referenced by org.onosproject.net.DefaultDevice.DefaultDevice().
boolean org.onosproject.net.DefaultDevice.equals (Object obj)
Definition at line 114 of file DefaultDevice.java.
References find-device.id.
int org.onosproject.net.DefaultDevice.hashCode ()
Definition at line 109 of file DefaultDevice.java.
References org.onosproject.net.DefaultDevice.hwVersion(), org.onosproject.net.DefaultDevice.id(), org.onosproject.net.DefaultDevice.manufacturer(), org.onosproject.net.DefaultDevice.serialNumber(), org.onosproject.net.DefaultDevice.swVersion(), and org.onosproject.net.DefaultDevice.type().
String org.onosproject.net.DefaultDevice.hwVersion ()
Returns the device hardware version.
Returns
hardware version
Implements org.onosproject.net.Device.
Definition at line 89 of file DefaultDevice.java.
Referenced by org.onosproject.net.DefaultDevice.DefaultDevice(), org.onosproject.net.DefaultDevice.hashCode(), and org.onosproject.net.DefaultDevice.toString().
DeviceId org.onosproject.net.DefaultDevice.id ()
Returns the device identifier.
Returns
device id
Implements org.onosproject.net.Device.
Definition at line 74 of file DefaultDevice.java.
Referenced by org.onosproject.net.DefaultDevice.hashCode(), and org.onosproject.net.DefaultDevice.toString().
String org.onosproject.net.DefaultDevice.manufacturer ()
Returns the device manufacturer name.
Returns
manufacturer name
Implements org.onosproject.net.Device.
Definition at line 84 of file DefaultDevice.java.
Referenced by org.onosproject.net.DefaultDevice.DefaultDevice(), org.onosproject.net.DefaultDevice.hashCode(), and org.onosproject.net.DefaultDevice.toString().
String org.onosproject.net.DefaultDevice.serialNumber ()
Returns the device serial number.
Returns
serial number
Implements org.onosproject.net.Device.
Definition at line 99 of file DefaultDevice.java.
Referenced by org.onosproject.net.DefaultDevice.DefaultDevice(), org.onosproject.net.DefaultDevice.hashCode(), and org.onosproject.net.DefaultDevice.toString().
String org.onosproject.net.DefaultDevice.swVersion ()
Returns the device software version.
Returns
software version
Implements org.onosproject.net.Device.
Definition at line 94 of file DefaultDevice.java.
Referenced by org.onosproject.net.DefaultDevice.DefaultDevice(), org.onosproject.net.DefaultDevice.hashCode(), and org.onosproject.net.DefaultDevice.toString().
String org.onosproject.net.DefaultDevice.toString ()
Definition at line 131 of file DefaultDevice.java.
References org.onosproject.net.DefaultDevice.hwVersion(), org.onosproject.net.DefaultDevice.id(), org.onosproject.net.DefaultDevice.manufacturer(), org.onosproject.net.DefaultDevice.serialNumber(), org.onosproject.net.DefaultDevice.swVersion(), and org.onosproject.net.DefaultDevice.type().
Type org.onosproject.net.DefaultDevice.type ()
Returns the type of the infrastructure device.
Returns
type of the device
Implements org.onosproject.net.Device.
Definition at line 79 of file DefaultDevice.java.
Referenced by org.onosproject.net.DefaultDevice.DefaultDevice(), org.onosproject.net.DefaultDevice.hashCode(), and org.onosproject.net.DefaultDevice.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/DefaultDevice.java