onos: org.onosproject.net.intent.MplsIntent Class Reference
org.onosproject.net.intent.MplsIntent Class Reference
Abstraction of MPLS label-switched connectivity.
Classes
class Builder
Builder of an MPLS intent.
Public Member Functions
ConnectPoint ingressPoint ()
Returns the port on which the ingress traffic should be connected to the egress.
ConnectPoint egressPoint ()
Returns the port on which the traffic should egress.
Optional< MplsLabel > ingressLabel ()
Returns the MPLS label which the ingress traffic should tagged.
Optional< MplsLabel > egressLabel ()
Returns the MPLS label which the egress traffic should tagged.
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.ConnectivityIntent
TrafficSelector selector ()
Returns the match specifying the type of traffic.
TrafficTreatment treatment ()
Returns the action applied to the traffic.
List< Constraint > constraints ()
Returns the set of connectivity constraints.
Public Member Functions inherited from org.onosproject.net.intent.Intent
IntentId id ()
Returns the intent identifier.
ApplicationId appId ()
Returns the identifier of the application that requested the intent.
int priority ()
Returns the priority of the intent.
Collection< NetworkResource > resources ()
Returns the collection of resources required for this intent.
boolean isInstallable ()
Indicates whether or not the intent is installable.
final int hashCode ()
final boolean equals (Object obj)
Key key ()
Static Public Member Functions
static Builder builder ()
Returns a new MPLS intent builder.
Static Public Member Functions inherited from org.onosproject.net.intent.Intent
static void bindIdGenerator (IdGenerator newIdGenerator)
Binds an id generator for unique intent id generation.
static void unbindIdGenerator (IdGenerator oldIdGenerator)
Unbinds an id generator.
Protected Member Functions
MplsIntent ()
Constructor for serializer.
Protected Member Functions inherited from org.onosproject.net.intent.ConnectivityIntent
ConnectivityIntent (ApplicationId appId, Key key, Collection< NetworkResource > resources, TrafficSelector selector, TrafficTreatment treatment, List< Constraint > constraints, int priority)
Creates a connectivity intent that matches on the specified selector and applies the specified treatment.
ConnectivityIntent ()
Constructor for serializer.
Protected Member Functions inherited from org.onosproject.net.intent.Intent
Intent ()
Constructor for serializer.
Intent (ApplicationId appId, Key key, Collection< NetworkResource > resources, int priority)
Creates a new intent.
Additional Inherited Members
Static Public Attributes inherited from org.onosproject.net.intent.Intent
static final int DEFAULT_INTENT_PRIORITY = 100
static final int MAX_PRIORITY = (1 << 16) - 1
static final int MIN_PRIORITY = 1
Static Protected Member Functions inherited from org.onosproject.net.intent.ConnectivityIntent
static Collection
< NetworkResource > resources (Collection< Link > links)
Produces a collection of network resources from the given links.
Detailed Description
Abstraction of MPLS label-switched connectivity.
Definition at line 39 of file MplsIntent.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.MplsIntent.MplsIntent () protected
Constructor for serializer.
Definition at line 211 of file MplsIntent.java.
Member Function Documentation
static Builder org.onosproject.net.intent.MplsIntent.builder () static
Returns a new MPLS intent builder.
The application id, ingress point, egress point, ingress label and egress label are required fields. If they are not set by calls to the appropriate methods, an exception will be thrown.
Returns
point to point builder
Definition at line 93 of file MplsIntent.java.
Optional<MplsLabel> org.onosproject.net.intent.MplsIntent.egressLabel ()
Returns the MPLS label which the egress traffic should tagged.
Returns
egress MPLS label
Definition at line 253 of file MplsIntent.java.
Referenced by org.onosproject.net.intent.MplsIntent.toString().
ConnectPoint org.onosproject.net.intent.MplsIntent.egressPoint ()
Returns the port on which the traffic should egress.
Returns
egress switch port
Definition at line 234 of file MplsIntent.java.
Optional<MplsLabel> org.onosproject.net.intent.MplsIntent.ingressLabel ()
Returns the MPLS label which the ingress traffic should tagged.
Returns
ingress MPLS label
Definition at line 244 of file MplsIntent.java.
Referenced by org.onosproject.net.intent.MplsIntent.toString().
ConnectPoint org.onosproject.net.intent.MplsIntent.ingressPoint ()
Returns the port on which the ingress traffic should be connected to the egress.
Returns
ingress switch port
Definition at line 225 of file MplsIntent.java.
String org.onosproject.net.intent.MplsIntent.toString ()
Definition at line 258 of file MplsIntent.java.
References org.onosproject.net.intent.Intent.appId(), org.onosproject.net.intent.ConnectivityIntent.constraints(), org.onosproject.net.intent.MplsIntent.egressLabel(), org.onosproject.net.intent.MplsIntent.ingressLabel(), org.onosproject.net.intent.Intent.key(), org.onosproject.net.intent.Intent.priority(), org.onosproject.net.intent.ConnectivityIntent.selector(), and org.onosproject.net.intent.ConnectivityIntent.treatment().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/MplsIntent.java