onos: org.onosproject.net.topology.impl.PathManager Class Reference
org.onosproject.net.topology.impl.PathManager Class Reference
Provides implementation of a path selection service atop the current topology and host services.
Public Member Functions
void activate ()
void deactivate ()
Set< Path > getPaths (ElementId src, ElementId dst)
Returns the set of all shortest paths, precomputed in terms of hop-count, between the specified source and destination elements.
Set< Path > getPaths (ElementId src, ElementId dst, LinkWeight weight)
Returns the set of all shortest paths, computed using the supplied edge-weight entity, between the specified source and destination network elements.
Set< DisjointPath > getDisjointPaths (ElementId src, ElementId dst)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Set< DisjointPath > getDisjointPaths (ElementId src, ElementId dst, LinkWeight weight)
Returns the set of all disjoint shortest path pairs, computed using the supplied edge-weight entity, between the specified source and destination devices.
Set< DisjointPath > getDisjointPaths (ElementId src, ElementId dst, Map< Link, Object > riskProfile)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Set< DisjointPath > getDisjointPaths (ElementId src, ElementId dst, LinkWeight weight, Map< Link, Object > riskProfile)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Protected Attributes
TopologyService topologyService
HostService hostService
Detailed Description
Provides implementation of a path selection service atop the current topology and host services.
Definition at line 66 of file PathManager.java.
Member Function Documentation
void org.onosproject.net.topology.impl.PathManager.activate ()
Definition at line 84 of file PathManager.java.
void org.onosproject.net.topology.impl.PathManager.deactivate ()
Definition at line 89 of file PathManager.java.
Set<DisjointPath> org.onosproject.net.topology.impl.PathManager.getDisjointPaths (ElementId src, ElementId dst)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Parameters
src source device
dst destination device
Returns
set of all shortest paths between the two devices
Implements org.onosproject.net.topology.PathService.
Definition at line 136 of file PathManager.java.
Referenced by org.onosproject.net.topology.impl.PathManager.getDisjointPaths().
Set<DisjointPath> org.onosproject.net.topology.impl.PathManager.getDisjointPaths (ElementId src, ElementId dst, LinkWeight weight)
Returns the set of all disjoint shortest path pairs, computed using the supplied edge-weight entity, between the specified source and destination devices.
Parameters
src source device
dst destination device
weight edge-weight entity
Returns
set of all shortest paths between the two devices
Implements org.onosproject.net.topology.PathService.
Definition at line 141 of file PathManager.java.
References find-flow.deviceId, org.onosproject.net.DeviceId.equals(), org.onosproject.net.topology.TopologyService.getDisjointPaths(), and org.onosproject.net.topology.impl.PathManager.topologyService.
Set<DisjointPath> org.onosproject.net.topology.impl.PathManager.getDisjointPaths (ElementId src, ElementId dst, Map< Link, Object > riskProfile)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Parameters
src source device
dst destination device
riskProfile map of edges to risk profiles
Returns
set of all shortest paths between the two devices
Implements org.onosproject.net.topology.PathService.
Definition at line 174 of file PathManager.java.
References org.onosproject.net.topology.impl.PathManager.getDisjointPaths().
Set<DisjointPath> org.onosproject.net.topology.impl.PathManager.getDisjointPaths (ElementId src, ElementId dst, LinkWeight weight, Map< Link, Object > riskProfile)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Parameters
src source device
dst destination device
weight edge-weight entity
riskProfile map of edges to risk profiles
Returns
set of all shortest paths between the two devices
Implements org.onosproject.net.topology.PathService.
Definition at line 180 of file PathManager.java.
References find-flow.deviceId, org.onosproject.net.DeviceId.equals(), org.onosproject.net.topology.TopologyService.getDisjointPaths(), and org.onosproject.net.topology.impl.PathManager.topologyService.
Set<Path> org.onosproject.net.topology.impl.PathManager.getPaths (ElementId src, ElementId dst)
Returns the set of all shortest paths, precomputed in terms of hop-count, between the specified source and destination elements.
Parameters
src source element
dst destination element
Returns
set of all shortest paths between the two elements
Implements org.onosproject.net.topology.PathService.
Definition at line 94 of file PathManager.java.
Set<Path> org.onosproject.net.topology.impl.PathManager.getPaths (ElementId src, ElementId dst, LinkWeight weight)
Returns the set of all shortest paths, computed using the supplied edge-weight entity, between the specified source and destination network elements.
Parameters
src source element
dst destination element
weight edge-weight entity
Returns
set of all shortest paths between the two element
Implements org.onosproject.net.topology.PathService.
Definition at line 101 of file PathManager.java.
References find-flow.deviceId, org.onosproject.net.DeviceId.equals(), org.onosproject.net.topology.TopologyService.getPaths(), and org.onosproject.net.topology.impl.PathManager.topologyService.
Member Data Documentation
HostService org.onosproject.net.topology.impl.PathManager.hostService protected
Definition at line 81 of file PathManager.java.
TopologyService org.onosproject.net.topology.impl.PathManager.topologyService protected
Definition at line 78 of file PathManager.java.
Referenced by org.onosproject.net.topology.impl.PathManager.getDisjointPaths(), and org.onosproject.net.topology.impl.PathManager.getPaths().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/topology/impl/PathManager.java