onos: org.onosproject.pcepio.types.LinkProtectionTypeTlv Class Reference
org.onosproject.pcepio.types.LinkProtectionTypeTlv Class Reference
Provide Link Protection Type.
Public Member Functions
LinkProtectionTypeTlv (byte protectionCap)
Constructor to initialize protectionCap.
LinkProtectionTypeTlv (byte protectionCap, byte reserved)
Constructor to initialize protectionCap, reserved.
byte getProtectionCap ()
Returns Protection Cap.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static PcepValueType read (ChannelBuffer c)
Reads the channel buffer and returns object of LinkProtectionTypeTlv.
Static Public Attributes
static final short TYPE = 20
static final short LENGTH = 2
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(LinkProtectionTypeTlv.class)
Detailed Description
Provide Link Protection Type.
Definition at line 31 of file LinkProtectionTypeTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.LinkProtectionTypeTlv.LinkProtectionTypeTlv (byte protectionCap)
Constructor to initialize protectionCap.
Parameters
protectionCap Protection Cap
Definition at line 54 of file LinkProtectionTypeTlv.java.
Referenced by org.onosproject.pcepio.types.LinkProtectionTypeTlv.equals(), and org.onosproject.pcepio.types.LinkProtectionTypeTlv.read().
org.onosproject.pcepio.types.LinkProtectionTypeTlv.LinkProtectionTypeTlv (byte protectionCap, byte reserved)
Constructor to initialize protectionCap, reserved.
Parameters
protectionCap Protection Cap
reserved Reserved value
Definition at line 65 of file LinkProtectionTypeTlv.java.
Member Function Documentation
boolean org.onosproject.pcepio.types.LinkProtectionTypeTlv.equals (Object obj)
Definition at line 100 of file LinkProtectionTypeTlv.java.
References org.onosproject.pcepio.types.LinkProtectionTypeTlv.LinkProtectionTypeTlv().
short org.onosproject.pcepio.types.LinkProtectionTypeTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 90 of file LinkProtectionTypeTlv.java.
References org.onosproject.pcepio.types.LinkProtectionTypeTlv.LENGTH.
byte org.onosproject.pcepio.types.LinkProtectionTypeTlv.getProtectionCap ()
Returns Protection Cap.
Returns
protectionCap Protection Cap
Definition at line 75 of file LinkProtectionTypeTlv.java.
short org.onosproject.pcepio.types.LinkProtectionTypeTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 85 of file LinkProtectionTypeTlv.java.
References org.onosproject.pcepio.types.LinkProtectionTypeTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.LinkProtectionTypeTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 80 of file LinkProtectionTypeTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.LinkProtectionTypeTlv.hashCode ()
Definition at line 95 of file LinkProtectionTypeTlv.java.
static PcepValueType org.onosproject.pcepio.types.LinkProtectionTypeTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of LinkProtectionTypeTlv.
Parameters
c input channel buffer
Returns
object of LinkProtectionTypeTlv
Definition at line 128 of file LinkProtectionTypeTlv.java.
References org.onosproject.pcepio.types.LinkProtectionTypeTlv.LinkProtectionTypeTlv().
String org.onosproject.pcepio.types.LinkProtectionTypeTlv.toString ()
Definition at line 135 of file LinkProtectionTypeTlv.java.
References org.onosproject.pcepio.types.LinkProtectionTypeTlv.LENGTH, and org.onosproject.pcepio.types.LinkProtectionTypeTlv.TYPE.
int org.onosproject.pcepio.types.LinkProtectionTypeTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 113 of file LinkProtectionTypeTlv.java.
References org.onosproject.pcepio.types.LinkProtectionTypeTlv.LENGTH, and org.onosproject.pcepio.types.LinkProtectionTypeTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.LinkProtectionTypeTlv.LENGTH = 2 static
Definition at line 45 of file LinkProtectionTypeTlv.java.
Referenced by org.onosproject.pcepio.types.LinkProtectionTypeTlv.getLength(), org.onosproject.pcepio.types.LinkProtectionTypeTlv.toString(), and org.onosproject.pcepio.types.LinkProtectionTypeTlv.write().
final Logger org.onosproject.pcepio.types.LinkProtectionTypeTlv.log = LoggerFactory.getLogger(LinkProtectionTypeTlv.class) static protected
Definition at line 42 of file LinkProtectionTypeTlv.java.
final short org.onosproject.pcepio.types.LinkProtectionTypeTlv.TYPE = 20 static
Definition at line 44 of file LinkProtectionTypeTlv.java.
Referenced by org.onosproject.pcepio.types.LinkProtectionTypeTlv.getType(), org.onosproject.pcepio.types.LinkProtectionTypeTlv.toString(), and org.onosproject.pcepio.types.LinkProtectionTypeTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/LinkProtectionTypeTlv.java