onos: org.onosproject.cluster.RoleInfo Class Reference
org.onosproject.cluster.RoleInfo Class Reference
An immutable container for role information for a device, within the current cluster.
Public Member Functions
RoleInfo (NodeId master, List< NodeId > backups)
RoleInfo ()
NodeId master ()
List< NodeId > backups ()
boolean equals (Object other)
int hashCode ()
String toString ()
Detailed Description
An immutable container for role information for a device, within the current cluster.
Role attributes include current master and a preference-ordered list of backup nodes.
Definition at line 30 of file RoleInfo.java.
Constructor & Destructor Documentation
org.onosproject.cluster.RoleInfo.RoleInfo (NodeId master, List< NodeId > backups)
Definition at line 34 of file RoleInfo.java.
References org.onosproject.cluster.RoleInfo.backups(), and org.onosproject.cluster.RoleInfo.master().
org.onosproject.cluster.RoleInfo.RoleInfo ()
Definition at line 39 of file RoleInfo.java.
Referenced by org.onosproject.cluster.RoleInfo.equals().
Member Function Documentation
List<NodeId> org.onosproject.cluster.RoleInfo.backups ()
Definition at line 49 of file RoleInfo.java.
Referenced by org.onosproject.cluster.RoleInfo.hashCode(), org.onosproject.cluster.RoleInfo.RoleInfo(), and org.onosproject.cluster.RoleInfo.toString().
boolean org.onosproject.cluster.RoleInfo.equals (Object other)
Definition at line 54 of file RoleInfo.java.
References org.onosproject.cluster.RoleInfo.RoleInfo().
int org.onosproject.cluster.RoleInfo.hashCode ()
Definition at line 69 of file RoleInfo.java.
References org.onosproject.cluster.RoleInfo.backups(), and org.onosproject.cluster.RoleInfo.master().
NodeId org.onosproject.cluster.RoleInfo.master ()
Definition at line 45 of file RoleInfo.java.
Referenced by org.onosproject.cluster.RoleInfo.hashCode(), and org.onosproject.cluster.RoleInfo.RoleInfo().
String org.onosproject.cluster.RoleInfo.toString ()
Definition at line 74 of file RoleInfo.java.
References org.onosproject.cluster.RoleInfo.backups().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/cluster/RoleInfo.java