onos: org.onlab.packet.ipv6.Authentication Class Reference
org.onlab.packet.ipv6.Authentication Class Reference
Implements IPv6 authentication extension header format.
Public Member Functions
byte getNextHeader ()
Gets the type of next header.
Authentication setNextHeader (final byte nextHeader)
Sets the type of next header.
byte getPayloadLength ()
Gets the payload length of this header.
Authentication setPayloadLength (final byte payloadLength)
Sets the payload length of this header.
int getSecurityParamIndex ()
Gets the security parameter index of this header.
Authentication setSecurityParamIndex (final int securityParamIndex)
Sets the security parameter index of this header.
int getSequence ()
Gets the sequence number of this header.
Authentication setSequence (final int sequence)
Sets the sequence number of this header.
byte[] getIntegrityCheck ()
Gets the integrity check value of this header.
Authentication setIngegrityCheck (final byte[] integrityCheck)
Sets the integrity check value of this header.
int getTotalLength ()
Gets the total length of this header.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer
< Authentication > deserializer ()
Deserializer function for authentication headers.
Static Public Attributes
static final byte FIXED_HEADER_LENGTH = 12
static final byte LENGTH_UNIT = 4
static final byte MINUS = 2
Protected Attributes
byte nextHeader
byte payloadLength
int securityParamIndex
int sequence
byte[] integrityCheck
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements IPv6 authentication extension header format.
(RFC 4302)
Definition at line 34 of file Authentication.java.
Member Function Documentation
IPacket org.onlab.packet.ipv6.Authentication.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 183 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.deserializer(), org.onlab.packet.ipv6.Authentication.FIXED_HEADER_LENGTH, org.onlab.packet.ipv6.Authentication.getTotalLength(), find-link-in-cluster.length, and org.onlab.packet.IPv6.PROTOCOL_DESERIALIZER_MAP.
static Deserializer<Authentication> org.onlab.packet.ipv6.Authentication.deserializer () static
Deserializer function for authentication headers.
Returns
deserializer function
Definition at line 271 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.FIXED_HEADER_LENGTH, find-link-in-cluster.length, org.onlab.packet.ipv6.Authentication.LENGTH_UNIT, org.onlab.packet.ipv6.Authentication.MINUS, org.onlab.packet.ipv6.Authentication.nextHeader, and org.onlab.packet.IPv6.PROTOCOL_DESERIALIZER_MAP.
Referenced by org.onlab.packet.ipv6.Authentication.deserialize().
boolean org.onlab.packet.ipv6.Authentication.equals (final Object obj)
Definition at line 237 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.integrityCheck, org.onlab.packet.ipv6.Authentication.nextHeader, org.onlab.packet.ipv6.Authentication.payloadLength, org.onlab.packet.ipv6.Authentication.securityParamIndex, and org.onlab.packet.ipv6.Authentication.sequence.
Referenced by org.onlab.packet.ipv6.AuthenticationTest.testEqual().
byte [] org.onlab.packet.ipv6.Authentication.getIntegrityCheck ()
Gets the integrity check value of this header.
Returns
the integrity check value
Definition at line 121 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.AuthenticationTest.testDeserialize().
byte org.onlab.packet.ipv6.Authentication.getNextHeader ()
Gets the type of next header.
Returns
next header
Implements org.onlab.packet.ipv6.IExtensionHeader.
Definition at line 46 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.AuthenticationTest.testDeserialize().
byte org.onlab.packet.ipv6.Authentication.getPayloadLength ()
Gets the payload length of this header.
Returns
the payload length
Definition at line 61 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.AuthenticationTest.testDeserialize().
int org.onlab.packet.ipv6.Authentication.getSecurityParamIndex ()
Gets the security parameter index of this header.
Returns
the security parameter index
Definition at line 81 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.AuthenticationTest.testDeserialize().
int org.onlab.packet.ipv6.Authentication.getSequence ()
Gets the sequence number of this header.
Returns
the sequence number
Definition at line 101 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.AuthenticationTest.testDeserialize().
int org.onlab.packet.ipv6.Authentication.getTotalLength ()
Gets the total length of this header.
According to spec, payload length should be the total length of this AH in 4-octet unit, minus 2
Returns
the total length
Definition at line 144 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.LENGTH_UNIT, org.onlab.packet.ipv6.Authentication.MINUS, and org.onlab.packet.ipv6.Authentication.payloadLength.
Referenced by org.onlab.packet.ipv6.Authentication.deserialize().
int org.onlab.packet.ipv6.Authentication.hashCode ()
Definition at line 218 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.integrityCheck.
byte [] org.onlab.packet.ipv6.Authentication.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 149 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.FIXED_HEADER_LENGTH, find-link-in-cluster.length, org.onlab.packet.BasePacket.parent, org.onlab.packet.BasePacket.payload, org.onlab.packet.ipv6.Authentication.payloadLength, and org.onlab.packet.IPv6.PROTOCOL_AH.
Referenced by org.onlab.packet.ipv6.AuthenticationTest.testSerialize().
Authentication org.onlab.packet.ipv6.Authentication.setIngegrityCheck (final byte[] integrityCheck)
Sets the integrity check value of this header.
Parameters
integrityCheck the integrity check value to set
Returns
this
Definition at line 131 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.integrityCheck, and find-link-in-cluster.length.
Authentication org.onlab.packet.ipv6.Authentication.setNextHeader (final byte nextHeader)
Sets the type of next header.
Parameters
nextHeader the next header to set
Returns
this
Implements org.onlab.packet.ipv6.IExtensionHeader.
Definition at line 51 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.nextHeader.
Authentication org.onlab.packet.ipv6.Authentication.setPayloadLength (final byte payloadLength)
Sets the payload length of this header.
Parameters
payloadLength the payload length to set
Returns
this
Definition at line 71 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.payloadLength.
Authentication org.onlab.packet.ipv6.Authentication.setSecurityParamIndex (final int securityParamIndex)
Sets the security parameter index of this header.
Parameters
securityParamIndex the security parameter index to set
Returns
this
Definition at line 91 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.securityParamIndex.
Authentication org.onlab.packet.ipv6.Authentication.setSequence (final int sequence)
Sets the sequence number of this header.
Parameters
sequence the sequence number to set
Returns
this
Definition at line 111 of file Authentication.java.
References org.onlab.packet.ipv6.Authentication.sequence.
Member Data Documentation
final byte org.onlab.packet.ipv6.Authentication.FIXED_HEADER_LENGTH = 12 static
Definition at line 35 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.Authentication.deserialize(), org.onlab.packet.ipv6.Authentication.deserializer(), and org.onlab.packet.ipv6.Authentication.serialize().
byte [] org.onlab.packet.ipv6.Authentication.integrityCheck protected
Definition at line 43 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.Authentication.equals(), org.onlab.packet.ipv6.Authentication.hashCode(), and org.onlab.packet.ipv6.Authentication.setIngegrityCheck().
final byte org.onlab.packet.ipv6.Authentication.LENGTH_UNIT = 4 static
Definition at line 36 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.Authentication.deserializer(), and org.onlab.packet.ipv6.Authentication.getTotalLength().
final byte org.onlab.packet.ipv6.Authentication.MINUS = 2 static
Definition at line 37 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.Authentication.deserializer(), and org.onlab.packet.ipv6.Authentication.getTotalLength().
byte org.onlab.packet.ipv6.Authentication.nextHeader protected
Definition at line 39 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.Authentication.deserializer(), org.onlab.packet.ipv6.Authentication.equals(), and org.onlab.packet.ipv6.Authentication.setNextHeader().
byte org.onlab.packet.ipv6.Authentication.payloadLength protected
Definition at line 40 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.Authentication.equals(), org.onlab.packet.ipv6.Authentication.getTotalLength(), org.onlab.packet.ipv6.Authentication.serialize(), and org.onlab.packet.ipv6.Authentication.setPayloadLength().
int org.onlab.packet.ipv6.Authentication.securityParamIndex protected
Definition at line 41 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.Authentication.equals(), and org.onlab.packet.ipv6.Authentication.setSecurityParamIndex().
int org.onlab.packet.ipv6.Authentication.sequence protected
Definition at line 42 of file Authentication.java.
Referenced by org.onlab.packet.ipv6.Authentication.equals(), and org.onlab.packet.ipv6.Authentication.setSequence().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ipv6/Authentication.java