onos: org.onosproject.net.HostId Class Reference
org.onosproject.net.HostId Class Reference
Immutable representation of a host identity.
Public Member Functions
MacAddress mac ()
Returns the host MAC address.
VlanId vlanId ()
Returns the host vlan Id.
String toString ()
int hashCode ()
boolean equals (Object obj)
Static Public Member Functions
static HostId hostId (String string)
Creates a device id using the supplied ID string.
static HostId hostId (MacAddress mac, VlanId vlanId)
Creates a device id using the supplied MAC & VLAN ID.
static HostId hostId (MacAddress mac)
Creates a device id using the supplied MAC and default VLAN.
Static Public Attributes
static final HostId NONE = new HostId(MacAddress.ZERO, VlanId.NONE)
Represents either no host, or an unspecified host; used for creating open ingress/egress edge links.
Detailed Description
Immutable representation of a host identity.
Definition at line 28 of file HostId.java.
Member Function Documentation
boolean org.onosproject.net.HostId.equals (Object obj)
Definition at line 117 of file HostId.java.
References obeliskHostCheck.mac.
int org.onosproject.net.HostId.hashCode ()
Definition at line 112 of file HostId.java.
References org.onosproject.net.HostId.mac(), and org.onosproject.net.HostId.vlanId().
static HostId org.onosproject.net.HostId.hostId (String string) static
Creates a device id using the supplied ID string.
Parameters
string device URI string
Returns
host identifier
Definition at line 78 of file HostId.java.
References find-link-in-cluster.length, org.onosproject.net.HostId.mac(), and org.onosproject.net.HostId.vlanId().
Referenced by org.onosproject.cli.net.HostRemoveCommand.execute(), org.onosproject.net.ConnectPoint.hostConnectPoint(), org.onosproject.net.HostId.hostId(), org.onosproject.rest.HostResourceTest.testBadGet(), org.onosproject.rest.HostResourceTest.testHostsArray(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUs(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUsIpv6(), org.onosproject.rest.HostResourceTest.testSingleHostByIdFetch(), and org.onosproject.rest.HostResourceTest.testSingleHostByMacAndVlanFetch().
static HostId org.onosproject.net.HostId.hostId (MacAddress mac, VlanId vlanId) static
Creates a device id using the supplied MAC & VLAN ID.
Parameters
mac mac address
vlanId vlan identifier
Returns
host identifier
Definition at line 93 of file HostId.java.
static HostId org.onosproject.net.HostId.hostId (MacAddress mac) static
Creates a device id using the supplied MAC and default VLAN.
Parameters
mac mac address
Returns
host identifier
Definition at line 103 of file HostId.java.
References org.onosproject.net.HostId.hostId(), org.onlab.packet.VlanId.UNTAGGED, and org.onlab.packet.VlanId.vlanId().
MacAddress org.onosproject.net.HostId.mac ()
Returns the host MAC address.
Returns
MAC address
Definition at line 59 of file HostId.java.
Referenced by org.onosproject.net.HostId.hashCode(), org.onosproject.net.HostId.hostId(), and org.onosproject.net.HostId.toString().
String org.onosproject.net.HostId.toString ()
Definition at line 107 of file HostId.java.
References org.onosproject.net.HostId.mac(), and org.onosproject.net.HostId.vlanId().
VlanId org.onosproject.net.HostId.vlanId ()
Returns the host vlan Id.
Returns
vlan Id
Definition at line 68 of file HostId.java.
Referenced by org.onosproject.net.HostId.hashCode(), org.onosproject.net.HostId.hostId(), and org.onosproject.net.HostId.toString().
Member Data Documentation
final HostId org.onosproject.net.HostId.NONE = new HostId(MacAddress.ZERO, VlanId.NONE) static
Represents either no host, or an unspecified host; used for creating open ingress/egress edge links.
Definition at line 34 of file HostId.java.
Referenced by org.onosproject.net.DefaultEdgeLink.createEdgeLink(), org.onosproject.routing.impl.RouterAsyncArpTest.testRouteAdd(), and org.onosproject.routing.impl.RouterAsyncArpTest.testRouteUpdate().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/HostId.java