onos: org.onosproject.segmentrouting.IpHandler Class Reference
org.onosproject.segmentrouting.IpHandler Class Reference
Public Member Functions
IpHandler (SegmentRoutingManager srManager)
Creates an IpHandler object.
void processPacketIn (InboundPacket pkt)
Processes incoming IP packets.
void addToPacketBuffer (IPv4 ipPacket)
Adds the IP packet to a buffer.
void forwardPackets (DeviceId deviceId, Ip4Address destIpAddress)
Forwards IP packets in the buffer to the destination IP address.
Detailed Description
Definition at line 40 of file IpHandler.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.IpHandler.IpHandler (SegmentRoutingManager srManager)
Creates an IpHandler object.
Parameters
srManager SegmentRoutingManager object
Definition at line 52 of file IpHandler.java.
References org.onosproject.segmentrouting.SegmentRoutingManager.deviceConfiguration.
Member Function Documentation
void org.onosproject.segmentrouting.IpHandler.addToPacketBuffer (IPv4 ipPacket)
Adds the IP packet to a buffer.
The packets are forwarded to corresponding destination when the destination MAC address is known via ARP response.
Parameters
ipPacket IP packet to add to the buffer
Definition at line 99 of file IpHandler.java.
References org.onlab.packet.IPv4.getProtocol(), and org.onlab.packet.IPv4.PROTOCOL_TCP.
void org.onosproject.segmentrouting.IpHandler.forwardPackets (DeviceId deviceId, Ip4Address destIpAddress)
Forwards IP packets in the buffer to the destination IP address.
It is called when the controller finds the destination MAC address via ARP responses.
Parameters
deviceId switch device ID
destIpAddress destination IP address
Definition at line 125 of file IpHandler.java.
References find-flow.deviceId, org.onosproject.net.host.HostService.getHostsByIp(), org.onosproject.segmentrouting.SegmentRoutingManager.hostService, org.onosproject.segmentrouting.config.DeviceConfiguration.inSameSubnet(), org.onlab.packet.Ethernet.serialize(), and org.onlab.packet.Ethernet.TYPE_IPV4.
Referenced by org.onosproject.segmentrouting.IpHandler.processPacketIn().
void org.onosproject.segmentrouting.IpHandler.processPacketIn (InboundPacket pkt)
Processes incoming IP packets.
If it is an IP packet for known host, then forward it to the host. If it is an IP packet for unknown host in subnet, then send an ARP request to the subnet.
Parameters
pkt incoming packet
Definition at line 67 of file IpHandler.java.
References find-flow.deviceId, org.onosproject.segmentrouting.IpHandler.forwardPackets(), org.onosproject.net.host.HostService.getHostsByIp(), org.onlab.packet.BasePacket.getPayload(), org.onosproject.segmentrouting.SegmentRoutingManager.hostService, and org.onosproject.segmentrouting.config.DeviceConfiguration.inSameSubnet().
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/IpHandler.java