onos: org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib Class Reference
org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib Class Reference
This Class stores path Attributes, protocol ID and Identifier of LinkState nlri.
Public Member Functions
PathAttrNlriDetailsLocalRib (IpAddress localRibIpAddress, int localRibIdentifier, long localRibAsNum, boolean isLocalRibIbgpSession, PathAttrNlriDetails localRibNlridetails)
Constructor to initialize parameter.
IpAddress localRibIpAddress ()
Gets the Ipaddress updated in local rib.
long localRibAsNum ()
Gets the autonomous system number updated in local rib.
int localRibIdentifier ()
Gets the indetifier updated in local rib.
boolean isLocalRibIbgpSession ()
Gets the bgp session type updated in local rib.
PathAttrNlriDetails localRibNlridetails ()
Returns local RIB Nlri details.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
This Class stores path Attributes, protocol ID and Identifier of LinkState nlri.
Definition at line 23 of file PathAttrNlriDetailsLocalRib.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.PathAttrNlriDetailsLocalRib (IpAddress localRibIpAddress, int localRibIdentifier, long localRibAsNum, boolean isLocalRibIbgpSession, PathAttrNlriDetails localRibNlridetails)
Constructor to initialize parameter.
Parameters
localRibIpAddress peer ip address
localRibIdentifier peer identifier
localRibAsNum peer As number
isLocalRibIbgpSession flag to indicate is Ibgp session
localRibNlridetails Nlri details
Definition at line 41 of file PathAttrNlriDetailsLocalRib.java.
References org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.isLocalRibIbgpSession(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibAsNum(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibIdentifier(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibIpAddress(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibNlridetails().
Referenced by org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.equals().
Member Function Documentation
boolean org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.equals (Object obj)
Definition at line 102 of file PathAttrNlriDetailsLocalRib.java.
References org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.isLocalRibIbgpSession(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibAsNum(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibIdentifier(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibIpAddress(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibNlridetails(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.PathAttrNlriDetailsLocalRib().
Referenced by org.onosproject.bgp.controller.impl.BgpSelectionAlgo.compare().
int org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.hashCode ()
Definition at line 96 of file PathAttrNlriDetailsLocalRib.java.
References org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.isLocalRibIbgpSession(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibAsNum(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibIdentifier(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibIpAddress().
boolean org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.isLocalRibIbgpSession ()
Gets the bgp session type updated in local rib.
Returns
isLocalRibIbgpSession session type
Definition at line 82 of file PathAttrNlriDetailsLocalRib.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.equals(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.hashCode(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.PathAttrNlriDetailsLocalRib().
long org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibAsNum ()
Gets the autonomous system number updated in local rib.
Returns
localRibAsNum autonomous system number
Definition at line 64 of file PathAttrNlriDetailsLocalRib.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.equals(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.hashCode(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.PathAttrNlriDetailsLocalRib().
int org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibIdentifier ()
Gets the indetifier updated in local rib.
Returns
localRibIdentifier identifier
Definition at line 73 of file PathAttrNlriDetailsLocalRib.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.equals(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.hashCode(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.PathAttrNlriDetailsLocalRib(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.toString().
IpAddress org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibIpAddress ()
Gets the Ipaddress updated in local rib.
Returns
localRibIpAddress ip address
Definition at line 55 of file PathAttrNlriDetailsLocalRib.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.equals(), org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.hashCode(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.PathAttrNlriDetailsLocalRib().
PathAttrNlriDetails org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibNlridetails ()
Returns local RIB Nlri details.
Returns
localRibNlridetails Nlri details in local rib
Definition at line 91 of file PathAttrNlriDetailsLocalRib.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.equals(), and org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.PathAttrNlriDetailsLocalRib().
String org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.toString ()
Definition at line 118 of file PathAttrNlriDetailsLocalRib.java.
References org.onosproject.bgpio.protocol.linkstate.PathAttrNlriDetailsLocalRib.localRibIdentifier().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/protocol/linkstate/PathAttrNlriDetailsLocalRib.java