onos: org.onosproject.store.consistent.impl.DefaultDatabaseState Class Reference
org.onosproject.store.consistent.impl.DefaultDatabaseState Class Reference
Default database state.
Public Member Functions
void init (StateContext< DatabaseState< String, byte[]>> context)
Set< String > maps ()
Map< String, Long > counters ()
int mapSize (String mapName)
boolean mapIsEmpty (String mapName)
boolean mapContainsKey (String mapName, String key)
boolean mapContainsValue (String mapName, byte[] value)
Versioned< byte[]> mapGet (String mapName, String key)
Result< UpdateResult< String,
byte[]> > mapUpdate (String mapName, String key, Match< byte[]> valueMatch, Match< Long > versionMatch, byte[] value)
Result< Void > mapClear (String mapName)
Set< String > mapKeySet (String mapName)
Collection< Versioned< byte[]> > mapValues (String mapName)
Set< Entry< String, Versioned
< byte[]> > > mapEntrySet (String mapName)
Long counterAddAndGet (String counterName, long delta)
Long counterGetAndAdd (String counterName, long delta)
Boolean counterCompareAndSet (String counterName, long expectedValue, long updateValue)
Long counterGet (String counterName)
Long queueSize (String queueName)
byte[] queuePeek (String queueName)
byte[] queuePop (String queueName)
void queuePush (String queueName, byte[] entry)
CommitResponse prepareAndCommit (Transaction transaction)
boolean prepare (Transaction transaction)
CommitResponse commit (Transaction transaction)
boolean rollback (Transaction transaction)
Detailed Description
Default database state.
Definition at line 43 of file DefaultDatabaseState.java.
Member Function Documentation
CommitResponse org.onosproject.store.consistent.impl.DefaultDatabaseState.commit (Transaction transaction)
Definition at line 251 of file DefaultDatabaseState.java.
References org.onosproject.store.service.Transaction.id().
Referenced by org.onosproject.store.consistent.impl.DefaultDatabaseState.prepareAndCommit().
Long org.onosproject.store.consistent.impl.DefaultDatabaseState.counterAddAndGet (String counterName, long delta)
Definition at line 187 of file DefaultDatabaseState.java.
Boolean org.onosproject.store.consistent.impl.DefaultDatabaseState.counterCompareAndSet (String counterName, long expectedValue, long updateValue)
Definition at line 197 of file DefaultDatabaseState.java.
Long org.onosproject.store.consistent.impl.DefaultDatabaseState.counterGet (String counterName)
Definition at line 202 of file DefaultDatabaseState.java.
Long org.onosproject.store.consistent.impl.DefaultDatabaseState.counterGetAndAdd (String counterName, long delta)
Definition at line 192 of file DefaultDatabaseState.java.
Map<String, Long> org.onosproject.store.consistent.impl.DefaultDatabaseState.counters ()
Definition at line 97 of file DefaultDatabaseState.java.
Referenced by org.onosproject.store.consistent.impl.DefaultDatabaseState.init().
void org.onosproject.store.consistent.impl.DefaultDatabaseState.init (StateContext< DatabaseState< String, byte[]>> context)
Definition at line 63 of file DefaultDatabaseState.java.
References org.onosproject.store.consistent.impl.DefaultDatabaseState.counters(), and org.onosproject.store.consistent.impl.DefaultDatabaseState.maps().
Result<Void> org.onosproject.store.consistent.impl.DefaultDatabaseState.mapClear (String mapName)
Definition at line 159 of file DefaultDatabaseState.java.
boolean org.onosproject.store.consistent.impl.DefaultDatabaseState.mapContainsKey (String mapName, String key)
Definition at line 114 of file DefaultDatabaseState.java.
boolean org.onosproject.store.consistent.impl.DefaultDatabaseState.mapContainsValue (String mapName, byte[] value)
Definition at line 119 of file DefaultDatabaseState.java.
Set<Entry<String, Versioned<byte[]> > > org.onosproject.store.consistent.impl.DefaultDatabaseState.mapEntrySet (String mapName)
Definition at line 178 of file DefaultDatabaseState.java.
Versioned<byte[]> org.onosproject.store.consistent.impl.DefaultDatabaseState.mapGet (String mapName, String key)
Definition at line 124 of file DefaultDatabaseState.java.
boolean org.onosproject.store.consistent.impl.DefaultDatabaseState.mapIsEmpty (String mapName)
Definition at line 109 of file DefaultDatabaseState.java.
Set<String> org.onosproject.store.consistent.impl.DefaultDatabaseState.mapKeySet (String mapName)
Definition at line 168 of file DefaultDatabaseState.java.
Set<String> org.onosproject.store.consistent.impl.DefaultDatabaseState.maps ()
Definition at line 92 of file DefaultDatabaseState.java.
Referenced by org.onosproject.store.consistent.impl.DefaultDatabaseState.init().
int org.onosproject.store.consistent.impl.DefaultDatabaseState.mapSize (String mapName)
Definition at line 104 of file DefaultDatabaseState.java.
Result<UpdateResult<String, byte[]> > org.onosproject.store.consistent.impl.DefaultDatabaseState.mapUpdate (String mapName, String key, Match< byte[]> valueMatch, Match< Long > versionMatch, byte[] value)
Definition at line 130 of file DefaultDatabaseState.java.
Collection<Versioned<byte[]> > org.onosproject.store.consistent.impl.DefaultDatabaseState.mapValues (String mapName)
Definition at line 173 of file DefaultDatabaseState.java.
boolean org.onosproject.store.consistent.impl.DefaultDatabaseState.prepare (Transaction transaction)
Definition at line 235 of file DefaultDatabaseState.java.
References org.onosproject.store.service.Transaction.id(), and org.onosproject.store.service.Transaction.updates().
Referenced by org.onosproject.store.consistent.impl.DefaultDatabaseState.prepareAndCommit().
CommitResponse org.onosproject.store.consistent.impl.DefaultDatabaseState.prepareAndCommit (Transaction transaction)
Definition at line 227 of file DefaultDatabaseState.java.
References org.onosproject.store.consistent.impl.DefaultDatabaseState.commit(), and org.onosproject.store.consistent.impl.DefaultDatabaseState.prepare().
byte [] org.onosproject.store.consistent.impl.DefaultDatabaseState.queuePeek (String queueName)
Definition at line 212 of file DefaultDatabaseState.java.
byte [] org.onosproject.store.consistent.impl.DefaultDatabaseState.queuePop (String queueName)
Definition at line 217 of file DefaultDatabaseState.java.
void org.onosproject.store.consistent.impl.DefaultDatabaseState.queuePush (String queueName, byte[] entry)
Definition at line 222 of file DefaultDatabaseState.java.
Long org.onosproject.store.consistent.impl.DefaultDatabaseState.queueSize (String queueName)
Definition at line 207 of file DefaultDatabaseState.java.
boolean org.onosproject.store.consistent.impl.DefaultDatabaseState.rollback (Transaction transaction)
Definition at line 257 of file DefaultDatabaseState.java.
References org.onosproject.store.service.Transaction.id().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DefaultDatabaseState.java