onos: org.onlab.packet.LLDPTest Class Reference
org.onlab.packet.LLDPTest Class Reference
Unit tests for the LLDP class.
Public Member Functions
void setUp () throws Exception
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws Exception
Detailed Description
Unit tests for the LLDP class.
Definition at line 31 of file LLDPTest.java.
Member Function Documentation
void org.onlab.packet.LLDPTest.setUp () throws Exception
Definition at line 45 of file LLDPTest.java.
References org.onlab.packet.LLDP.CHASSIS_TLV_SIZE, org.onlab.packet.LLDP.CHASSIS_TLV_TYPE, org.onlab.packet.LLDPOrganizationalTLV.ORGANIZATIONAL_TLV_TYPE, org.onlab.packet.LLDP.PORT_TLV_SIZE, org.onlab.packet.LLDP.PORT_TLV_TYPE, org.onlab.packet.LLDP.TTL_TLV_SIZE, and org.onlab.packet.LLDP.TTL_TLV_TYPE.
void org.onlab.packet.LLDPTest.testDeserialize () throws Exception
Definition at line 93 of file LLDPTest.java.
References org.onlab.packet.LLDP.CHASSIS_TLV_SIZE, org.onlab.packet.LLDP.CHASSIS_TLV_TYPE, org.onlab.packet.LLDP.getChassisId(), org.onlab.packet.LLDPTLV.getLength(), org.onlab.packet.LLDP.getOptionalTLVList(), org.onlab.packet.LLDP.getPortId(), org.onlab.packet.LLDP.getTtl(), org.onlab.packet.LLDPTLV.getType(), org.onlab.packet.LLDPTLV.getValue(), find-link-in-cluster.length, org.onlab.packet.LLDPOrganizationalTLV.ORGANIZATIONAL_TLV_TYPE, org.onlab.packet.LLDP.PORT_TLV_SIZE, org.onlab.packet.LLDP.PORT_TLV_TYPE, org.onlab.packet.LLDP.TTL_TLV_SIZE, and org.onlab.packet.LLDP.TTL_TLV_TYPE.
void org.onlab.packet.LLDPTest.testDeserializeBadInput () throws Exception
Definition at line 83 of file LLDPTest.java.
void org.onlab.packet.LLDPTest.testDeserializeTruncated () throws Exception
Definition at line 88 of file LLDPTest.java.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/LLDPTest.java