onos: org.onosproject.net.DefaultEdgeLinkTest Class Reference
org.onosproject.net.DefaultEdgeLinkTest Class Reference
Test of the default edge link model entity.
Public Member Functions
void testEquality ()
void basics ()
void phantomIngress ()
void phantomEgress ()
Detailed Description
Test of the default edge link model entity.
Definition at line 32 of file DefaultEdgeLinkTest.java.
Member Function Documentation
void org.onosproject.net.DefaultEdgeLinkTest.basics ()
Definition at line 59 of file DefaultEdgeLinkTest.java.
References org.onosproject.net.Link.dst(), org.onosproject.net.EdgeLink.hostId(), org.onosproject.net.EdgeLink.hostLocation(), org.onosproject.net.Link.src(), and org.onosproject.net.Link.type().
void org.onosproject.net.DefaultEdgeLinkTest.phantomEgress ()
Definition at line 81 of file DefaultEdgeLinkTest.java.
References org.onosproject.net.EdgeLink.hostLocation(), org.onosproject.net.Link.src(), and org.onosproject.net.Link.type().
void org.onosproject.net.DefaultEdgeLinkTest.phantomIngress ()
Definition at line 71 of file DefaultEdgeLinkTest.java.
References org.onosproject.net.Link.dst(), org.onosproject.net.EdgeLink.hostLocation(), and org.onosproject.net.Link.type().
void org.onosproject.net.DefaultEdgeLinkTest.testEquality ()
Definition at line 42 of file DefaultEdgeLinkTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/DefaultEdgeLinkTest.java