onos: org.onosproject.mfwd.impl.McastRouteTable Class Reference
org.onosproject.mfwd.impl.McastRouteTable Class Reference
The Mcast Route Table holds all multicast state for the controller.
Public Member Functions
Map< IpPrefix, McastRouteGroup > getMrib4 ()
Get the IPv4 MRIB.
Map< IpPrefix, McastRouteGroup > getMrib6 ()
Get the IPv6 MRIB.
McastRouteBase addRoute (String saddr, String gaddr)
Add a multicast route to the MRIB.
McastRouteBase addRoute (IpPrefix spfx, IpPrefix gpfx)
Add a multicast route to the MRIB.
boolean removeEgress (String saddr, String gaddr, String egress)
Delete a specific egress from the MRIB.
void removeRoute (String saddr, String gaddr)
Delete a multicast route from the MRIB.
void removeRoute (IpPrefix spfx, IpPrefix gpfx)
Remove a multicast route.
McastRouteGroup findMcastGroup (IpPrefix group)
Find the specific multicast group entry.
McastRouteSource findMcastSource (IpPrefix saddr, IpPrefix gaddr)
Find the multicast (S, G) entry if it exists.
McastRoute findBestMatch (IpPrefix saddr, IpPrefix gaddr)
This will first look up a Group entry.
String printMcastRouteTable ()
Print out the multicast route table in it's entirety.
String toString ()
Print out a summary of groups in the MRIB.
Static Public Member Functions
static McastRouteTable getInstance ()
Get the single instance of this multicast group address.
Detailed Description
The Mcast Route Table holds all multicast state for the controller.
State for IPv4 and IPv6 are maintained. The tables are sets of McastRouteGroup structures that represent (*, G) state with a series of egress ConnectPoints. Each (*, G) may also have a set of (S, G) that may have there own set of ingress and egress ConnectPoints.
TODO: perhaps should probably create two separate singleton for IPv4 and IPv6 respectively.
Definition at line 36 of file McastRouteTable.java.
Member Function Documentation
McastRouteBase org.onosproject.mfwd.impl.McastRouteTable.addRoute (String saddr, String gaddr)
Add a multicast route to the MRIB.
This function will.
Parameters
saddr source address * or x.x.x.x or x.x.x.x/y
gaddr group address x.x.x.x or x.x.x.x/y
Returns
the multicast route
Definition at line 125 of file McastRouteTable.java.
McastRouteBase org.onosproject.mfwd.impl.McastRouteTable.addRoute (IpPrefix spfx, IpPrefix gpfx)
Add a multicast route to the MRIB.
This function will store either (S, G) or (*, G) in the mrib if an entry does not already exist. If an entry does exist it is returned to the caller.
Every (S, G) is stored as part of it's parent group entry which also represents (*, G) routes. In the case of a (S, G) we will also create the (*, G) entry if needed then save the (S, G) to the (*, G).
Parameters
spfx the source prefix
gpfx the group prefix
Returns
the resulting McastRouteSource or McastRouteGroup accordingly.
If a group route (*, g) does not exist we will need to make so we can start attaching our sources to the group entry.
If the source prefix length is 0 then we have our (*, g) entry, we can just return now.
We have the group but no source. We need to create the source then add it to the group.
Definition at line 147 of file McastRouteTable.java.
References org.onlab.packet.IpPrefix.isIp4(), and org.onlab.packet.IpPrefix.isIp6().
McastRoute org.onosproject.mfwd.impl.McastRouteTable.findBestMatch (IpPrefix saddr, IpPrefix gaddr)
This will first look up a Group entry.
If no group entry was found null will be returned. If the group entry has been found we will then look up the (s, g) entry. If the (s, g) entry has been found, that will be returned. If no (s, g) was found the (*, g) group entry will be returned.
Parameters
saddr the source address
gaddr the group address
Returns
return the best matching McastRouteSource or McastRouteGroup
Definition at line 317 of file McastRouteTable.java.
McastRouteGroup org.onosproject.mfwd.impl.McastRouteTable.findMcastGroup (IpPrefix group)
Find the specific multicast group entry.
Parameters
group the group address
Returns
McastRouteGroup the multicast (*, G) group route
Definition at line 282 of file McastRouteTable.java.
References org.onlab.packet.IpPrefix.isIp4(), and org.onlab.packet.IpPrefix.isIp6().
McastRouteSource org.onosproject.mfwd.impl.McastRouteTable.findMcastSource (IpPrefix saddr, IpPrefix gaddr)
Find the multicast (S, G) entry if it exists.
Parameters
saddr the source address
gaddr the group address
Returns
The multicast source route entry if it exists, null if it does not.
Definition at line 299 of file McastRouteTable.java.
static McastRouteTable org.onosproject.mfwd.impl.McastRouteTable.getInstance () static
Get the single instance of this multicast group address.
Returns
the multicast route table
Definition at line 66 of file McastRouteTable.java.
Map<IpPrefix, McastRouteGroup> org.onosproject.mfwd.impl.McastRouteTable.getMrib4 ()
Get the IPv4 MRIB.
Returns
the IPv4 MRIB
Definition at line 78 of file McastRouteTable.java.
Map<IpPrefix, McastRouteGroup> org.onosproject.mfwd.impl.McastRouteTable.getMrib6 ()
Get the IPv6 MRIB.
Returns
Return the set of prefix keyed McastGroups
Definition at line 87 of file McastRouteTable.java.
String org.onosproject.mfwd.impl.McastRouteTable.printMcastRouteTable ()
Print out the multicast route table in it's entirety.
TODO: Eventually we will have to implement paging and how to handle large tables.
Returns
String
Definition at line 338 of file McastRouteTable.java.
Referenced by org.onosproject.mfwd.cli.McastShowCommand.printMrib4().
boolean org.onosproject.mfwd.impl.McastRouteTable.removeEgress (String saddr, String gaddr, String egress)
Delete a specific egress from the MRIB.
Parameters
saddr source address * or x.x.x.x or x.x.x.x/y
gaddr group address x.x.x.x or x.x.x.x/y
egress group address x.x.x.x or x.x.x.x/y
Returns
boolean if egress was deleted
Definition at line 202 of file McastRouteTable.java.
References create-intent.egress.
void org.onosproject.mfwd.impl.McastRouteTable.removeRoute (String saddr, String gaddr)
Delete a multicast route from the MRIB.
Parameters
saddr source address * or x.x.x.x or x.x.x.x/y
gaddr group address x.x.x.x or x.x.x.x/y
Definition at line 224 of file McastRouteTable.java.
void org.onosproject.mfwd.impl.McastRouteTable.removeRoute (IpPrefix spfx, IpPrefix gpfx)
Remove a multicast route.
Parameters
spfx the source prefix
gpfx the group prefix
If a group route (*, g) does not exist we will need to make so we can start attaching our sources to the group entry.
If the source prefix length is 0 then we have a (*, g) entry, which means we will remove this group and all of it's sources. We will also withdraw it's intent if need be.
Definition at line 239 of file McastRouteTable.java.
References org.onosproject.mfwd.impl.McastRouteBase.getEgressPoints(), and org.onosproject.mfwd.impl.McastRouteGroup.getSources().
String org.onosproject.mfwd.impl.McastRouteTable.toString ()
Print out a summary of groups in the MRIB.
Returns
String
Definition at line 355 of file McastRouteTable.java.
The documentation for this class was generated from the following file:
apps/mfwd/src/main/java/org/onosproject/mfwd/impl/McastRouteTable.java