onos: org.onosproject.bgpio.types.Origin Class Reference
org.onosproject.bgpio.types.Origin Class Reference
Provides Implementation of mandatory BGP Origin path attribute.
Classes
enum ORIGINTYPE
Enum to provide ORIGIN types.
Public Member Functions
Origin (byte origin)
Constructor to initialize parameters.
boolean isOriginSet ()
Returns true if origin attribute is present otherwise false.
ORIGINTYPE origin ()
Returns type of Origin in Enum values.
short getType ()
Returns the Type of BGP Message.
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
int hashCode ()
boolean equals (Object obj)
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static Origin read (ChannelBuffer cb) throws BgpParseException
Reads from ChannelBuffer and parses Origin.
Static Public Attributes
static final byte ORIGIN_TYPE = 1
static final byte ORIGIN_VALUE_LEN = 1
Detailed Description
Provides Implementation of mandatory BGP Origin path attribute.
Definition at line 30 of file Origin.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.Origin.Origin (byte origin)
Constructor to initialize parameters.
Parameters
origin origin value
Definition at line 68 of file Origin.java.
References org.onosproject.bgpio.types.Origin.origin().
Referenced by org.onosproject.bgpio.types.Origin.equals(), and org.onosproject.bgpio.types.Origin.read().
Member Function Documentation
int org.onosproject.bgpio.types.Origin.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 164 of file Origin.java.
boolean org.onosproject.bgpio.types.Origin.equals (Object obj)
Definition at line 145 of file Origin.java.
References org.onosproject.bgpio.types.Origin.Origin(), and org.onosproject.bgpio.types.Origin.origin().
Referenced by org.onosproject.bgp.controller.impl.BgpSelectionAlgo.compare().
short org.onosproject.bgpio.types.Origin.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 129 of file Origin.java.
References org.onosproject.bgpio.types.Origin.ORIGIN_TYPE.
int org.onosproject.bgpio.types.Origin.hashCode ()
Definition at line 140 of file Origin.java.
References org.onosproject.bgpio.types.Origin.origin().
boolean org.onosproject.bgpio.types.Origin.isOriginSet ()
Returns true if origin attribute is present otherwise false.
Returns
whether origin is present or not
Definition at line 78 of file Origin.java.
ORIGINTYPE org.onosproject.bgpio.types.Origin.origin ()
Returns type of Origin in Enum values.
Returns
type of Origin in Enum values
Definition at line 87 of file Origin.java.
References org.onosproject.bgpio.types.Origin.ORIGINTYPE.EGP, org.onosproject.bgpio.types.Origin.ORIGINTYPE.IGP, and org.onosproject.bgpio.types.Origin.ORIGINTYPE.INCOMPLETE.
Referenced by org.onosproject.bgpio.types.Origin.equals(), org.onosproject.bgpio.types.Origin.hashCode(), org.onosproject.bgpio.types.Origin.Origin(), and org.onosproject.bgpio.types.Origin.toString().
static Origin org.onosproject.bgpio.types.Origin.read (ChannelBuffer cb) throws BgpParseException static
Reads from ChannelBuffer and parses Origin.
Parameters
cb ChannelBuffer
Returns
object of Origin
Exceptions
BgpParseException while parsing Origin path attribute
Definition at line 104 of file Origin.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_FLAGS_ERROR, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.Origin.ORIGINTYPE.EGP, org.onosproject.bgpio.util.Validation.getLength(), org.onosproject.bgpio.types.Origin.ORIGINTYPE.INCOMPLETE, org.onosproject.bgpio.types.BgpErrorType.INVALID_ORIGIN_ATTRIBUTE, org.onosproject.bgpio.types.Origin.Origin(), org.onosproject.bgpio.types.Origin.ORIGIN_VALUE_LEN, org.onosproject.bgpio.util.Constants.TYPE_AND_LEN_AS_BYTE, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.Origin.toString ()
Definition at line 157 of file Origin.java.
References org.onosproject.bgpio.types.Origin.origin().
int org.onosproject.bgpio.types.Origin.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 134 of file Origin.java.
Member Data Documentation
final byte org.onosproject.bgpio.types.Origin.ORIGIN_TYPE = 1 static
Definition at line 57 of file Origin.java.
Referenced by org.onosproject.bgpio.protocol.ver4.BgpPathAttributes.checkMandatoryAttr(), and org.onosproject.bgpio.types.Origin.getType().
final byte org.onosproject.bgpio.types.Origin.ORIGIN_VALUE_LEN = 1 static
Definition at line 58 of file Origin.java.
Referenced by org.onosproject.bgpio.types.Origin.read().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/Origin.java