onos: org.onlab.packet.ndp.Redirect Class Reference
org.onlab.packet.ndp.Redirect Class Reference
Implements ICMPv6 Redirect packet format.
Public Member Functions
byte[] getTargetAddress ()
Gets target address.
Redirect setTargetAddress (final byte[] targetAddress)
Sets target address.
byte[] getDestinationAddress ()
Gets destination address.
Redirect setDestinationAddress (final byte[] destinationAddress)
Sets destination address.
List
< NeighborDiscoveryOptions.Option > getOptions ()
Gets the Neighbor Discovery Protocol packet options.
Redirect addOption (final byte type, final byte[] data)
Adds a Neighbor Discovery Protocol packet option.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer< Redirect > deserializer ()
Deserializer function for redirect packets.
Static Public Attributes
static final byte HEADER_LENGTH = 36
Protected Attributes
byte[] targetAddress = new byte[Ip6Address.BYTE_LENGTH]
byte[] destinationAddress = new byte[Ip6Address.BYTE_LENGTH]
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements ICMPv6 Redirect packet format.
(RFC 4861)
Definition at line 32 of file Redirect.java.
Member Function Documentation
Redirect org.onlab.packet.ndp.Redirect.addOption (final byte type, final byte[] data)
Adds a Neighbor Discovery Protocol packet option.
Parameters
type the option type
data the option data
Returns
this
Definition at line 99 of file Redirect.java.
IPacket org.onlab.packet.ndp.Redirect.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 130 of file Redirect.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, and find-link-in-cluster.length.
Referenced by org.onlab.packet.ndp.Redirect.deserializer().
static Deserializer<Redirect> org.onlab.packet.ndp.Redirect.deserializer () static
Deserializer function for redirect packets.
Returns
deserializer function
Definition at line 200 of file Redirect.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, org.onlab.packet.ndp.Redirect.deserialize(), org.onlab.packet.ndp.Redirect.HEADER_LENGTH, and find-link-in-cluster.length.
boolean org.onlab.packet.ndp.Redirect.equals (final Object obj)
Definition at line 171 of file Redirect.java.
References org.onlab.packet.ndp.Redirect.destinationAddress, org.onlab.packet.ndp.NeighborDiscoveryOptions.equals(), and org.onlab.packet.ndp.Redirect.targetAddress.
Referenced by org.onlab.packet.ndp.RedirectTest.testEqual().
byte [] org.onlab.packet.ndp.Redirect.getDestinationAddress ()
Gets destination address.
Returns
the destination IPv6 address
Definition at line 67 of file Redirect.java.
Referenced by org.onlab.packet.ndp.RedirectTest.testDeserialize().
List<NeighborDiscoveryOptions.Option> org.onlab.packet.ndp.Redirect.getOptions ()
Gets the Neighbor Discovery Protocol packet options.
Returns
the Neighbor Discovery Protocol packet options
Definition at line 88 of file Redirect.java.
Referenced by org.onlab.packet.ndp.RedirectTest.testDeserialize().
byte [] org.onlab.packet.ndp.Redirect.getTargetAddress ()
Gets target address.
Returns
the target IPv6 address
Definition at line 46 of file Redirect.java.
Referenced by org.onlab.packet.ndp.RedirectTest.testDeserialize().
int org.onlab.packet.ndp.Redirect.hashCode ()
Definition at line 149 of file Redirect.java.
byte [] org.onlab.packet.ndp.Redirect.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 105 of file Redirect.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, org.onlab.packet.ndp.NeighborDiscoveryOptions.hasOptions(), org.onlab.packet.ndp.Redirect.HEADER_LENGTH, and find-link-in-cluster.length.
Referenced by org.onlab.packet.ndp.RedirectTest.testSerialize().
Redirect org.onlab.packet.ndp.Redirect.setDestinationAddress (final byte[] destinationAddress)
Sets destination address.
Parameters
destinationAddress the destination IPv6 address to set
Returns
this
Definition at line 77 of file Redirect.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, and org.onlab.packet.ndp.Redirect.destinationAddress.
Redirect org.onlab.packet.ndp.Redirect.setTargetAddress (final byte[] targetAddress)
Sets target address.
Parameters
targetAddress the target IPv6 address to set
Returns
this
Definition at line 56 of file Redirect.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH, and org.onlab.packet.ndp.Redirect.targetAddress.
Member Data Documentation
byte [] org.onlab.packet.ndp.Redirect.destinationAddress = new byte[Ip6Address.BYTE_LENGTH] protected
Definition at line 36 of file Redirect.java.
Referenced by org.onlab.packet.ndp.Redirect.equals(), and org.onlab.packet.ndp.Redirect.setDestinationAddress().
final byte org.onlab.packet.ndp.Redirect.HEADER_LENGTH = 36 static
Definition at line 33 of file Redirect.java.
Referenced by org.onlab.packet.ndp.Redirect.deserializer(), org.onlab.packet.ndp.Redirect.serialize(), and org.onlab.packet.ndp.RedirectTest.testDeserializeTruncated().
byte [] org.onlab.packet.ndp.Redirect.targetAddress = new byte[Ip6Address.BYTE_LENGTH] protected
Definition at line 35 of file Redirect.java.
Referenced by org.onlab.packet.ndp.Redirect.equals(), and org.onlab.packet.ndp.Redirect.setTargetAddress().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ndp/Redirect.java