onos: org.onosproject.net.flow.DefaultFlowEntry Class Reference
org.onosproject.net.flow.DefaultFlowEntry Class Reference
Public Member Functions
DefaultFlowEntry (FlowRule rule, FlowEntryState state, long life, long packets, long bytes)
DefaultFlowEntry (FlowRule rule)
DefaultFlowEntry (FlowRule rule, int errType, int errCode)
long life ()
Returns the number of milliseconds this flow rule has been applied.
long packets ()
Returns the number of packets this flow rule has matched.
long bytes ()
Returns the number of bytes this flow rule has matched.
FlowEntryState state ()
Returns the flow entry state.
long lastSeen ()
When this flow entry was last deemed active.
void setLastSeen ()
Sets the last active epoch time.
void setState (FlowEntryState newState)
Sets the new state for this entry.
void setLife (long life)
Sets how long this entry has been entered in the system.
void setPackets (long packets)
Number of packets seen by this entry.
void setBytes (long bytes)
Number of bytes seen by this rule.
int errType ()
Indicates the error type.
int errCode ()
Indicates the error code.
String toString ()
Public Member Functions inherited from org.onosproject.net.flow.DefaultFlowRule
DefaultFlowRule (FlowRule rule)
DefaultFlowRule (DeviceId deviceId, TrafficSelector selector, TrafficTreatment treatment, int priority, ApplicationId appId, int timeout, boolean permanent, FlowRuleExtPayLoad payLoad)
Support for the third party flow rule.
DefaultFlowRule (DeviceId deviceId, TrafficSelector selector, TrafficTreatment treatment, int priority, ApplicationId appId, GroupId groupId, int timeout, boolean permanent, FlowRuleExtPayLoad payLoad)
Support for the third party flow rule.
FlowId id ()
Returns the ID of this flow.
short appId ()
Returns the application id of this flow.
GroupId groupId ()
Returns the group id of this flow.
int priority ()
Returns the flow rule priority given in natural order; higher numbers mean higher priorities.
DeviceId deviceId ()
Returns the identity of the device where this rule applies.
TrafficSelector selector ()
Returns the traffic selector that identifies what traffic this rule should apply to.
TrafficTreatment treatment ()
Returns the traffic treatment that applies to selected traffic.
int hashCode ()
boolean equals (Object obj)
Equality for flow rules only considers 'match equality'. This means that two flow rules with the same match conditions will be equal, regardless of the treatment or other characteristics of the flow.
Parameters
obj the reference object with which to compare.
Returns
true
if this object is the same as the obj argument;
false
otherwise.
boolean exactMatch (FlowRule rule)
Returns whether this flow rule is an exact match to the flow rule given in the argument.
String toString ()
int timeout ()
Returns the timeout for this flow requested by an application.
boolean isPermanent ()
Returns whether the flow is permanent i.e.
int tableId ()
Returns the table id for this rule.
FlowRuleExtPayLoad payLoad ()
Returns the third party original flow rule.
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.net.flow.DefaultFlowRule
static Builder builder ()
Public Attributes inherited from org.onosproject.net.flow.FlowRule
int MAX_TIMEOUT = 60
int MIN_PRIORITY = 0
Detailed Description
Definition at line 23 of file DefaultFlowEntry.java.
Constructor & Destructor Documentation
org.onosproject.net.flow.DefaultFlowEntry.DefaultFlowEntry (FlowRule rule, FlowEntryState state, long life, long packets, long bytes)
Definition at line 39 of file DefaultFlowEntry.java.
References org.onosproject.net.flow.DefaultFlowEntry.bytes(), org.onosproject.net.flow.DefaultFlowEntry.life(), org.onosproject.net.flow.DefaultFlowEntry.packets(), and org.onosproject.net.flow.DefaultFlowEntry.state().
org.onosproject.net.flow.DefaultFlowEntry.DefaultFlowEntry (FlowRule rule)
Definition at line 51 of file DefaultFlowEntry.java.
References org.onosproject.net.flow.FlowEntry.FlowEntryState.PENDING_ADD.
org.onosproject.net.flow.DefaultFlowEntry.DefaultFlowEntry (FlowRule rule, int errType, int errCode)
Definition at line 62 of file DefaultFlowEntry.java.
References org.onosproject.net.flow.DefaultFlowEntry.errCode(), org.onosproject.net.flow.DefaultFlowEntry.errType(), and org.onosproject.net.flow.FlowEntry.FlowEntryState.FAILED.
Member Function Documentation
long org.onosproject.net.flow.DefaultFlowEntry.bytes ()
Returns the number of bytes this flow rule has matched.
Returns
number of bytes
Implements org.onosproject.net.flow.FlowEntry.
Definition at line 81 of file DefaultFlowEntry.java.
Referenced by org.onosproject.net.flow.DefaultFlowEntry.DefaultFlowEntry(), and org.onosproject.net.flow.DefaultFlowEntry.setBytes().
int org.onosproject.net.flow.DefaultFlowEntry.errCode ()
Indicates the error code.
Returns
an integer value of the error
Implements org.onosproject.net.flow.FlowEntry.
Definition at line 126 of file DefaultFlowEntry.java.
Referenced by org.onosproject.net.flow.DefaultFlowEntry.DefaultFlowEntry().
int org.onosproject.net.flow.DefaultFlowEntry.errType ()
Indicates the error type.
Returns
an integer value of the error
Implements org.onosproject.net.flow.FlowEntry.
Definition at line 121 of file DefaultFlowEntry.java.
Referenced by org.onosproject.net.flow.DefaultFlowEntry.DefaultFlowEntry().
long org.onosproject.net.flow.DefaultFlowEntry.lastSeen ()
When this flow entry was last deemed active.
Returns
epoch time of last activity
Implements org.onosproject.net.flow.FlowEntry.
Definition at line 91 of file DefaultFlowEntry.java.
long org.onosproject.net.flow.DefaultFlowEntry.life ()
Returns the number of milliseconds this flow rule has been applied.
Returns
number of millis
Implements org.onosproject.net.flow.FlowEntry.
Definition at line 71 of file DefaultFlowEntry.java.
Referenced by org.onosproject.net.flow.DefaultFlowEntry.DefaultFlowEntry(), and org.onosproject.net.flow.DefaultFlowEntry.setLife().
long org.onosproject.net.flow.DefaultFlowEntry.packets ()
Returns the number of packets this flow rule has matched.
Returns
number of packets
Implements org.onosproject.net.flow.FlowEntry.
Definition at line 76 of file DefaultFlowEntry.java.
Referenced by org.onosproject.net.flow.DefaultFlowEntry.DefaultFlowEntry(), and org.onosproject.net.flow.DefaultFlowEntry.setPackets().
void org.onosproject.net.flow.DefaultFlowEntry.setBytes (long bytes)
Number of bytes seen by this rule.
Parameters
bytes a long value
Implements org.onosproject.net.flow.StoredFlowEntry.
Definition at line 116 of file DefaultFlowEntry.java.
References org.onosproject.net.flow.DefaultFlowEntry.bytes().
void org.onosproject.net.flow.DefaultFlowEntry.setLastSeen ()
Sets the last active epoch time.
Implements org.onosproject.net.flow.StoredFlowEntry.
Definition at line 96 of file DefaultFlowEntry.java.
void org.onosproject.net.flow.DefaultFlowEntry.setLife (long life)
Sets how long this entry has been entered in the system.
Parameters
life epoch time
Implements org.onosproject.net.flow.StoredFlowEntry.
Definition at line 106 of file DefaultFlowEntry.java.
References org.onosproject.net.flow.DefaultFlowEntry.life().
void org.onosproject.net.flow.DefaultFlowEntry.setPackets (long packets)
Number of packets seen by this entry.
Parameters
packets a long value
Implements org.onosproject.net.flow.StoredFlowEntry.
Definition at line 111 of file DefaultFlowEntry.java.
References org.onosproject.net.flow.DefaultFlowEntry.packets().
void org.onosproject.net.flow.DefaultFlowEntry.setState (FlowEntryState newState)
Sets the new state for this entry.
Parameters
newState new flow entry state.
Implements org.onosproject.net.flow.StoredFlowEntry.
Definition at line 101 of file DefaultFlowEntry.java.
FlowEntryState org.onosproject.net.flow.DefaultFlowEntry.state ()
Returns the flow entry state.
Returns
flow entry state
Implements org.onosproject.net.flow.FlowEntry.
Definition at line 86 of file DefaultFlowEntry.java.
Referenced by org.onosproject.net.flow.DefaultFlowEntry.DefaultFlowEntry(), and org.onosproject.net.flow.DefaultFlowEntry.toString().
String org.onosproject.net.flow.DefaultFlowEntry.toString ()
Definition at line 131 of file DefaultFlowEntry.java.
References org.onosproject.net.flow.DefaultFlowEntry.state().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/DefaultFlowEntry.java