onos: org.onosproject.store.statistic.impl.DistributedFlowStatisticStore Class Reference
org.onosproject.store.statistic.impl.DistributedFlowStatisticStore Class Reference
Maintains flow statistics using RPC calls to collect stats from remote instances on demand.
Public Member Functions
void activate ()
void deactivate ()
synchronized void removeFlowStatistic (FlowRule rule)
Remove entries associated with this rule.
synchronized void addFlowStatistic (FlowEntry rule)
Adds a flow stats observation for a flow rule.
synchronized void updateFlowStatistic (FlowEntry rule)
Updates a stats observation for a flow rule.
Set< FlowEntry > getCurrentFlowStatistic (ConnectPoint connectPoint)
Fetches the current observed flow stats values.
Set< FlowEntry > getPreviousFlowStatistic (ConnectPoint connectPoint)
Fetches the current observed flow stats values.
Protected Attributes
MastershipService mastershipService
ClusterCommunicationService clusterCommunicator
ClusterService clusterService
Static Protected Attributes
static final KryoSerializer SERIALIZER
Detailed Description
Maintains flow statistics using RPC calls to collect stats from remote instances on demand.
Definition at line 65 of file DistributedFlowStatisticStore.java.
Member Function Documentation
void org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.activate ()
Definition at line 103 of file DistributedFlowStatisticStore.java.
synchronized void org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.addFlowStatistic (FlowEntry rule)
Adds a flow stats observation for a flow rule.
The previous flow will be removed.
Parameters
rule a org.onosproject.net.flow.FlowEntry
Implements org.onosproject.net.statistic.FlowStatisticStore.
Definition at line 144 of file DistributedFlowStatisticStore.java.
Referenced by org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.updateFlowStatistic().
void org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.deactivate ()
Definition at line 122 of file DistributedFlowStatisticStore.java.
Set<FlowEntry> org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.getCurrentFlowStatistic (ConnectPoint connectPoint)
Fetches the current observed flow stats values.
Parameters
connectPoint the port to fetch information for
Returns
set of current flow rules
Implements org.onosproject.net.statistic.FlowStatisticStore.
Definition at line 210 of file DistributedFlowStatisticStore.java.
References find-flow.deviceId.
Set<FlowEntry> org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.getPreviousFlowStatistic (ConnectPoint connectPoint)
Fetches the current observed flow stats values.
Parameters
connectPoint the port to fetch information for
Returns
set of current values
Implements org.onosproject.net.statistic.FlowStatisticStore.
Definition at line 239 of file DistributedFlowStatisticStore.java.
References find-flow.deviceId.
synchronized void org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.removeFlowStatistic (FlowRule rule)
Remove entries associated with this rule.
Parameters
rule org.onosproject.net.flow.FlowRule
Implements org.onosproject.net.statistic.FlowStatisticStore.
Definition at line 130 of file DistributedFlowStatisticStore.java.
Referenced by org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.updateFlowStatistic().
synchronized void org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.updateFlowStatistic (FlowEntry rule)
Updates a stats observation for a flow rule.
The old flow stats will be moved to previous stats.
Parameters
rule a org.onosproject.net.flow.FlowEntry
Implements org.onosproject.net.statistic.FlowStatisticStore.
Definition at line 158 of file DistributedFlowStatisticStore.java.
References org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.addFlowStatistic(), org.onosproject.net.flow.FlowEntry.bytes(), org.onosproject.net.flow.FlowRule.equals(), org.onosproject.net.flow.FlowEntry.lastSeen(), and org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.removeFlowStatistic().
Member Data Documentation
ClusterCommunicationService org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.clusterCommunicator protected
Definition at line 75 of file DistributedFlowStatisticStore.java.
ClusterService org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.clusterService protected
Definition at line 78 of file DistributedFlowStatisticStore.java.
MastershipService org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.mastershipService protected
Definition at line 72 of file DistributedFlowStatisticStore.java.
final KryoSerializer org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.SERIALIZER static protected
Initial value:
= new KryoSerializer() {
        @Override
        protected void setupKryoPool() {
            serializerPool = KryoNamespace.newBuilder()
                    .register(KryoNamespaces.API)
                    .nextId(KryoNamespaces.BEGIN_USER_CUSTOM_ID)
                    .build();
        }
    }
Definition at line 86 of file DistributedFlowStatisticStore.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/statistic/impl/DistributedFlowStatisticStore.java