onos: org.onosproject.vtnrsc.DefaultFloatingIp Class Reference
org.onosproject.vtnrsc.DefaultFloatingIp Class Reference
Default implementation of FloatingIp interface.
Public Member Functions
DefaultFloatingIp (FloatingIpId id, TenantId tenantId, TenantNetworkId networkId, VirtualPortId portId, RouterId routerId, IpAddress floatingIp, IpAddress fixedIp, Status status)
Creates a floating Ip object.
FloatingIpId id ()
Returns the floatingIp identifier.
TenantId tenantId ()
Returns the tenant identifier.
TenantNetworkId networkId ()
Returns the network identifier.
VirtualPortId portId ()
Returns the port identifier.
RouterId routerId ()
Returns the router identifier.
IpAddress floatingIp ()
Returns the floating ip address.
IpAddress fixedIp ()
Returns the fixed ip address.
Status status ()
Returns the status of floating ip.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of FloatingIp interface.
Definition at line 28 of file DefaultFloatingIp.java.
Constructor & Destructor Documentation
org.onosproject.vtnrsc.DefaultFloatingIp.DefaultFloatingIp (FloatingIpId id, TenantId tenantId, TenantNetworkId networkId, VirtualPortId portId, RouterId routerId, IpAddress floatingIp, IpAddress fixedIp, Status status)
Creates a floating Ip object.
Parameters
id floatingIp identifier
tenantId tenant identifier
networkId the identifier of network associated with the floating Ip
portId port identifier
routerId router identifier
floatingIp floatingIp address
fixedIp the fixed Ip associated with the floating Ip
status the floating Ip status
Definition at line 52 of file DefaultFloatingIp.java.
References org.onosproject.vtnrsc.DefaultFloatingIp.fixedIp(), org.onosproject.vtnrsc.DefaultFloatingIp.portId(), and org.onosproject.vtnrsc.DefaultFloatingIp.routerId().
Referenced by org.onosproject.vtnrsc.DefaultFloatingIp.equals().
Member Function Documentation
boolean org.onosproject.vtnrsc.DefaultFloatingIp.equals (Object obj)
Definition at line 113 of file DefaultFloatingIp.java.
References org.onosproject.vtnrsc.DefaultFloatingIp.DefaultFloatingIp(), and find-device.id.
IpAddress org.onosproject.vtnrsc.DefaultFloatingIp.fixedIp ()
Returns the fixed ip address.
Returns
fixedIp
Implements org.onosproject.vtnrsc.FloatingIp.
Definition at line 97 of file DefaultFloatingIp.java.
Referenced by org.onosproject.vtnrsc.DefaultFloatingIp.DefaultFloatingIp(), org.onosproject.vtnrsc.DefaultFloatingIp.hashCode(), and org.onosproject.vtnrsc.DefaultFloatingIp.toString().
IpAddress org.onosproject.vtnrsc.DefaultFloatingIp.floatingIp ()
Returns the floating ip address.
Returns
floatingIp
Implements org.onosproject.vtnrsc.FloatingIp.
Definition at line 92 of file DefaultFloatingIp.java.
Referenced by org.onosproject.vtnrsc.DefaultFloatingIp.hashCode(), and org.onosproject.vtnrsc.DefaultFloatingIp.toString().
int org.onosproject.vtnrsc.DefaultFloatingIp.hashCode ()
Definition at line 107 of file DefaultFloatingIp.java.
References org.onosproject.vtnrsc.DefaultFloatingIp.fixedIp(), org.onosproject.vtnrsc.DefaultFloatingIp.floatingIp(), org.onosproject.vtnrsc.DefaultFloatingIp.id(), org.onosproject.vtnrsc.DefaultFloatingIp.networkId(), org.onosproject.vtnrsc.DefaultFloatingIp.portId(), org.onosproject.vtnrsc.DefaultFloatingIp.routerId(), org.onosproject.vtnrsc.DefaultFloatingIp.status(), and org.onosproject.vtnrsc.DefaultFloatingIp.tenantId().
FloatingIpId org.onosproject.vtnrsc.DefaultFloatingIp.id ()
Returns the floatingIp identifier.
Returns
identifier
Implements org.onosproject.vtnrsc.FloatingIp.
Definition at line 67 of file DefaultFloatingIp.java.
Referenced by org.onosproject.vtnrsc.DefaultFloatingIp.hashCode(), and org.onosproject.vtnrsc.DefaultFloatingIp.toString().
TenantNetworkId org.onosproject.vtnrsc.DefaultFloatingIp.networkId ()
Returns the network identifier.
Returns
the network identifier
Implements org.onosproject.vtnrsc.FloatingIp.
Definition at line 77 of file DefaultFloatingIp.java.
Referenced by org.onosproject.vtnrsc.DefaultFloatingIp.hashCode(), and org.onosproject.vtnrsc.DefaultFloatingIp.toString().
VirtualPortId org.onosproject.vtnrsc.DefaultFloatingIp.portId ()
Returns the port identifier.
Returns
the port identifier
Implements org.onosproject.vtnrsc.FloatingIp.
Definition at line 82 of file DefaultFloatingIp.java.
Referenced by org.onosproject.vtnrsc.DefaultFloatingIp.DefaultFloatingIp(), org.onosproject.vtnrsc.DefaultFloatingIp.hashCode(), and org.onosproject.vtnrsc.DefaultFloatingIp.toString().
RouterId org.onosproject.vtnrsc.DefaultFloatingIp.routerId ()
Returns the router identifier.
Returns
the router identifier
Implements org.onosproject.vtnrsc.FloatingIp.
Definition at line 87 of file DefaultFloatingIp.java.
Referenced by org.onosproject.vtnrsc.DefaultFloatingIp.DefaultFloatingIp(), org.onosproject.vtnrsc.DefaultFloatingIp.hashCode(), and org.onosproject.vtnrsc.DefaultFloatingIp.toString().
Status org.onosproject.vtnrsc.DefaultFloatingIp.status ()
Returns the status of floating ip.
Returns
floatingIpStatus
Implements org.onosproject.vtnrsc.FloatingIp.
Definition at line 102 of file DefaultFloatingIp.java.
Referenced by org.onosproject.vtnrsc.DefaultFloatingIp.hashCode(), and org.onosproject.vtnrsc.DefaultFloatingIp.toString().
TenantId org.onosproject.vtnrsc.DefaultFloatingIp.tenantId ()
Returns the tenant identifier.
Returns
the tenant identifier
Implements org.onosproject.vtnrsc.FloatingIp.
Definition at line 72 of file DefaultFloatingIp.java.
Referenced by org.onosproject.vtnrsc.DefaultFloatingIp.hashCode(), and org.onosproject.vtnrsc.DefaultFloatingIp.toString().
String org.onosproject.vtnrsc.DefaultFloatingIp.toString ()
Definition at line 132 of file DefaultFloatingIp.java.
References org.onosproject.vtnrsc.DefaultFloatingIp.fixedIp(), org.onosproject.vtnrsc.DefaultFloatingIp.floatingIp(), org.onosproject.vtnrsc.DefaultFloatingIp.id(), org.onosproject.vtnrsc.DefaultFloatingIp.networkId(), org.onosproject.vtnrsc.DefaultFloatingIp.portId(), org.onosproject.vtnrsc.DefaultFloatingIp.routerId(), org.onosproject.vtnrsc.DefaultFloatingIp.status(), and org.onosproject.vtnrsc.DefaultFloatingIp.tenantId().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultFloatingIp.java