onos: org.onosproject.store.consistent.impl.PartitionedDatabase Class Reference
org.onosproject.store.consistent.impl.PartitionedDatabase Class Reference
A database that partitions the keys across one or more database partitions.
Public Member Functions
PartitionedDatabase (String name, Collection< Database > partitions)
List< Database > getPartitions ()
Returns the databases for individual partitions.
boolean isOpen ()
Returns true if the database is open.
CompletableFuture< Set< String > > maps ()
CompletableFuture< Map< String,
Long > > counters ()
CompletableFuture< Integer > mapSize (String mapName)
CompletableFuture< Boolean > mapIsEmpty (String mapName)
CompletableFuture< Boolean > mapContainsKey (String mapName, String key)
CompletableFuture< Boolean > mapContainsValue (String mapName, byte[] value)
CompletableFuture< Versioned
< byte[]> > mapGet (String mapName, String key)
CompletableFuture< Result
< UpdateResult< String, byte[]> > > mapUpdate (String mapName, String key, Match< byte[]> valueMatch, Match< Long > versionMatch, byte[] value)
CompletableFuture< Result< Void > > mapClear (String mapName)
CompletableFuture< Set< String > > mapKeySet (String mapName)
CompletableFuture< Collection
< Versioned< byte[]> > > mapValues (String mapName)
CompletableFuture< Set< Entry
< String, Versioned< byte[]> > > > mapEntrySet (String mapName)
CompletableFuture< Long > counterGet (String counterName)
CompletableFuture< Long > counterAddAndGet (String counterName, long delta)
CompletableFuture< Long > counterGetAndAdd (String counterName, long delta)
CompletableFuture< Void > counterSet (String counterName, long value)
CompletableFuture< Boolean > counterCompareAndSet (String counterName, long expectedValue, long updateValue)
CompletableFuture< Long > queueSize (String queueName)
CompletableFuture< Void > queuePush (String queueName, byte[] entry)
CompletableFuture< byte[]> queuePop (String queueName)
CompletableFuture< byte[]> queuePeek (String queueName)
CompletableFuture< CommitResponse > prepareAndCommit (Transaction transaction)
CompletableFuture< Boolean > prepare (Transaction transaction)
CompletableFuture< CommitResponse > commit (Transaction transaction)
CompletableFuture< Boolean > rollback (Transaction transaction)
CompletableFuture< Database > open ()
CompletableFuture< Void > close ()
boolean isClosed ()
String name ()
Cluster cluster ()
Database addStartupTask (Task< CompletableFuture< Void >> task)
Database addShutdownTask (Task< CompletableFuture< Void >> task)
ResourceState state ()
void registerConsumer (Consumer< StateMachineUpdate > consumer)
Registers a new consumer of StateMachineUpdates.
void unregisterConsumer (Consumer< StateMachineUpdate > consumer)
Unregisters a consumer of StateMachineUpdates.
Public Member Functions inherited from org.onosproject.store.consistent.impl.Database
default boolean hasChangeNotificationSupport ()
Tells whether the database supports change notifications.
Protected Member Functions
void setTransactionManager (TransactionManager transactionManager)
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.store.consistent.impl.Database
static Database create (String name)
Creates a new database with the default cluster configuration.
static Database create (String name, ClusterConfig cluster)
Creates a new database.
static Database create (String name, ClusterConfig cluster, DatabaseConfig config)
Creates a new database.
Detailed Description
A database that partitions the keys across one or more database partitions.
Definition at line 47 of file PartitionedDatabase.java.
Constructor & Destructor Documentation
org.onosproject.store.consistent.impl.PartitionedDatabase.PartitionedDatabase (String name, Collection< Database > partitions)
Definition at line 56 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.name().
Member Function Documentation
Database org.onosproject.store.consistent.impl.PartitionedDatabase.addShutdownTask (Task< CompletableFuture< Void >> task)
Definition at line 362 of file PartitionedDatabase.java.
Database org.onosproject.store.consistent.impl.PartitionedDatabase.addStartupTask (Task< CompletableFuture< Void >> task)
Definition at line 357 of file PartitionedDatabase.java.
CompletableFuture<Void> org.onosproject.store.consistent.impl.PartitionedDatabase.close ()
Definition at line 333 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.deactivate().
Cluster org.onosproject.store.consistent.impl.PartitionedDatabase.cluster ()
Definition at line 352 of file PartitionedDatabase.java.
CompletableFuture<CommitResponse> org.onosproject.store.consistent.impl.PartitionedDatabase.commit (Transaction transaction)
Definition at line 292 of file PartitionedDatabase.java.
CompletableFuture<Long> org.onosproject.store.consistent.impl.PartitionedDatabase.counterAddAndGet (String counterName, long delta)
Definition at line 211 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.PartitionedDatabase.counterCompareAndSet (String counterName, long expectedValue, long updateValue)
Definition at line 229 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Long> org.onosproject.store.consistent.impl.PartitionedDatabase.counterGet (String counterName)
Definition at line 205 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Long> org.onosproject.store.consistent.impl.PartitionedDatabase.counterGetAndAdd (String counterName, long delta)
Definition at line 217 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Map<String, Long> > org.onosproject.store.consistent.impl.PartitionedDatabase.counters ()
Definition at line 96 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.getCounters(), and org.onosproject.store.consistent.impl.DatabaseManager.getPartitionedDatabaseCounters().
CompletableFuture<Void> org.onosproject.store.consistent.impl.PartitionedDatabase.counterSet (String counterName, long value)
Definition at line 223 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
List<Database> org.onosproject.store.consistent.impl.PartitionedDatabase.getPartitions ()
Returns the databases for individual partitions.
Returns
list of database partitions
Definition at line 71 of file PartitionedDatabase.java.
boolean org.onosproject.store.consistent.impl.PartitionedDatabase.isClosed ()
Definition at line 342 of file PartitionedDatabase.java.
boolean org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen ()
Returns true if the database is open.
Returns
true if open, false otherwise
Definition at line 80 of file PartitionedDatabase.java.
Referenced by org.onosproject.store.consistent.impl.PartitionedDatabase.close(), org.onosproject.store.consistent.impl.PartitionedDatabase.counterAddAndGet(), org.onosproject.store.consistent.impl.PartitionedDatabase.counterCompareAndSet(), org.onosproject.store.consistent.impl.PartitionedDatabase.counterGet(), org.onosproject.store.consistent.impl.PartitionedDatabase.counterGetAndAdd(), org.onosproject.store.consistent.impl.PartitionedDatabase.counters(), org.onosproject.store.consistent.impl.PartitionedDatabase.counterSet(), org.onosproject.store.consistent.impl.PartitionedDatabase.mapClear(), org.onosproject.store.consistent.impl.PartitionedDatabase.mapContainsKey(), org.onosproject.store.consistent.impl.PartitionedDatabase.mapContainsValue(), org.onosproject.store.consistent.impl.PartitionedDatabase.mapEntrySet(), org.onosproject.store.consistent.impl.PartitionedDatabase.mapGet(), org.onosproject.store.consistent.impl.PartitionedDatabase.mapIsEmpty(), org.onosproject.store.consistent.impl.PartitionedDatabase.mapKeySet(), org.onosproject.store.consistent.impl.PartitionedDatabase.maps(), org.onosproject.store.consistent.impl.PartitionedDatabase.mapSize(), org.onosproject.store.consistent.impl.PartitionedDatabase.mapValues(), org.onosproject.store.consistent.impl.PartitionedDatabase.queuePeek(), org.onosproject.store.consistent.impl.PartitionedDatabase.queuePop(), org.onosproject.store.consistent.impl.PartitionedDatabase.queuePush(), and org.onosproject.store.consistent.impl.PartitionedDatabase.queueSize().
CompletableFuture<Result<Void> > org.onosproject.store.consistent.impl.PartitionedDatabase.mapClear (String mapName)
Definition at line 160 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.PartitionedDatabase.mapContainsKey (String mapName, String key)
Definition at line 128 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.PartitionedDatabase.mapContainsValue (String mapName, byte[] value)
Definition at line 134 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Set<Entry<String, Versioned<byte[]> > > > org.onosproject.store.consistent.impl.PartitionedDatabase.mapEntrySet (String mapName)
Definition at line 194 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Versioned<byte[]> > org.onosproject.store.consistent.impl.PartitionedDatabase.mapGet (String mapName, String key)
Definition at line 146 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.PartitionedDatabase.mapIsEmpty (String mapName)
Definition at line 122 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen(), org.onosproject.store.consistent.impl.PartitionedDatabase.mapSize(), and onos.size.
CompletableFuture<Set<String> > org.onosproject.store.consistent.impl.PartitionedDatabase.mapKeySet (String mapName)
Definition at line 172 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Set<String> > org.onosproject.store.consistent.impl.PartitionedDatabase.maps ()
Definition at line 85 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Integer> org.onosproject.store.consistent.impl.PartitionedDatabase.mapSize (String mapName)
Definition at line 111 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
Referenced by org.onosproject.store.consistent.impl.PartitionedDatabase.mapIsEmpty().
CompletableFuture<Result<UpdateResult<String, byte[]> > > org.onosproject.store.consistent.impl.PartitionedDatabase.mapUpdate (String mapName, String key, Match< byte[]> valueMatch, Match< Long > versionMatch, byte[] value)
Definition at line 152 of file PartitionedDatabase.java.
CompletableFuture<Collection<Versioned<byte[]> > > org.onosproject.store.consistent.impl.PartitionedDatabase.mapValues (String mapName)
Definition at line 183 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
String org.onosproject.store.consistent.impl.PartitionedDatabase.name ()
Definition at line 347 of file PartitionedDatabase.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.store.consistent.impl.PartitionedDatabase.PartitionedDatabase(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
CompletableFuture<Database> org.onosproject.store.consistent.impl.PartitionedDatabase.open ()
Definition at line 321 of file PartitionedDatabase.java.
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.PartitionedDatabase.prepare (Transaction transaction)
Definition at line 278 of file PartitionedDatabase.java.
CompletableFuture<CommitResponse> org.onosproject.store.consistent.impl.PartitionedDatabase.prepareAndCommit (Transaction transaction)
Definition at line 261 of file PartitionedDatabase.java.
CompletableFuture<byte[]> org.onosproject.store.consistent.impl.PartitionedDatabase.queuePeek (String queueName)
Definition at line 255 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<byte[]> org.onosproject.store.consistent.impl.PartitionedDatabase.queuePop (String queueName)
Definition at line 249 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Void> org.onosproject.store.consistent.impl.PartitionedDatabase.queuePush (String queueName, byte[] entry)
Definition at line 243 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
CompletableFuture<Long> org.onosproject.store.consistent.impl.PartitionedDatabase.queueSize (String queueName)
Definition at line 237 of file PartitionedDatabase.java.
References org.onosproject.store.consistent.impl.PartitionedDatabase.isOpen().
void org.onosproject.store.consistent.impl.PartitionedDatabase.registerConsumer (Consumer< StateMachineUpdate > consumer)
Registers a new consumer of StateMachineUpdates.
Parameters
consumer consumer to register
Implements org.onosproject.store.consistent.impl.Database.
Definition at line 390 of file PartitionedDatabase.java.
CompletableFuture<Boolean> org.onosproject.store.consistent.impl.PartitionedDatabase.rollback (Transaction transaction)
Definition at line 311 of file PartitionedDatabase.java.
void org.onosproject.store.consistent.impl.PartitionedDatabase.setTransactionManager (TransactionManager transactionManager) protected
Definition at line 385 of file PartitionedDatabase.java.
ResourceState org.onosproject.store.consistent.impl.PartitionedDatabase.state ()
Definition at line 367 of file PartitionedDatabase.java.
void org.onosproject.store.consistent.impl.PartitionedDatabase.unregisterConsumer (Consumer< StateMachineUpdate > consumer)
Unregisters a consumer of StateMachineUpdates.
Parameters
consumer consumer to unregister
Implements org.onosproject.store.consistent.impl.Database.
Definition at line 395 of file PartitionedDatabase.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/PartitionedDatabase.java