onos: org.onosproject.bgpio.types.BgpLSIdentifierTlv Class Reference
org.onosproject.bgpio.types.BgpLSIdentifierTlv Class Reference
Provides BGPLSIdentifier Tlv which contains opaque value (32 Bit BGPLS-Identifier).
Public Member Functions
BgpLSIdentifierTlv (int bgpLsIdentifier)
Constructor to initialize bgpLsIdentifier.
int getBgpLsIdentifier ()
Returns opaque value of BGPLS-Identifier.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of BGP Message to channel buffer.
short getType ()
Returns the Type of BGP Message.
int compareTo (Object o)
Compares two objects.
String toString ()
Static Public Member Functions
static BgpLSIdentifierTlv of (final int bgpLsIdentifier)
Returns object of this class with specified bgpLsIdentifier.
static BgpLSIdentifierTlv read (ChannelBuffer cb)
Reads the channel buffer and parses BGPLS Identifier TLV.
Static Public Attributes
static final short TYPE = 513
static final short LENGTH = 4
Detailed Description
Provides BGPLSIdentifier Tlv which contains opaque value (32 Bit BGPLS-Identifier).
Definition at line 28 of file BgpLSIdentifierTlv.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.BgpLSIdentifierTlv.BgpLSIdentifierTlv (int bgpLsIdentifier)
Constructor to initialize bgpLsIdentifier.
Parameters
bgpLsIdentifier BGPLS-Identifier
Definition at line 50 of file BgpLSIdentifierTlv.java.
Referenced by org.onosproject.bgpio.types.BgpLSIdentifierTlv.equals(), and org.onosproject.bgpio.types.BgpLSIdentifierTlv.of().
Member Function Documentation
int org.onosproject.bgpio.types.BgpLSIdentifierTlv.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 116 of file BgpLSIdentifierTlv.java.
References org.onosproject.bgpio.types.BgpLSIdentifierTlv.equals().
boolean org.onosproject.bgpio.types.BgpLSIdentifierTlv.equals (Object obj)
Definition at line 79 of file BgpLSIdentifierTlv.java.
References org.onosproject.bgpio.types.BgpLSIdentifierTlv.BgpLSIdentifierTlv().
Referenced by org.onosproject.bgpio.types.BgpLSIdentifierTlv.compareTo().
int org.onosproject.bgpio.types.BgpLSIdentifierTlv.getBgpLsIdentifier ()
Returns opaque value of BGPLS-Identifier.
Returns
opaque value of BGPLS-Identifier
Definition at line 69 of file BgpLSIdentifierTlv.java.
short org.onosproject.bgpio.types.BgpLSIdentifierTlv.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 111 of file BgpLSIdentifierTlv.java.
References org.onosproject.bgpio.types.BgpLSIdentifierTlv.TYPE.
int org.onosproject.bgpio.types.BgpLSIdentifierTlv.hashCode ()
Definition at line 74 of file BgpLSIdentifierTlv.java.
static BgpLSIdentifierTlv org.onosproject.bgpio.types.BgpLSIdentifierTlv.of (final int bgpLsIdentifier) static
Returns object of this class with specified bgpLsIdentifier.
Parameters
bgpLsIdentifier BGPLS-Identifier
Returns
BGPLS-Identifier
Definition at line 60 of file BgpLSIdentifierTlv.java.
References org.onosproject.bgpio.types.BgpLSIdentifierTlv.BgpLSIdentifierTlv().
static BgpLSIdentifierTlv org.onosproject.bgpio.types.BgpLSIdentifierTlv.read (ChannelBuffer cb) static
Reads the channel buffer and parses BGPLS Identifier TLV.
Parameters
cb ChannelBuffer
Returns
object of BGPLSIdentifierTlv
Definition at line 106 of file BgpLSIdentifierTlv.java.
String org.onosproject.bgpio.types.BgpLSIdentifierTlv.toString ()
Definition at line 124 of file BgpLSIdentifierTlv.java.
References org.onosproject.bgpio.types.BgpLSIdentifierTlv.LENGTH, and org.onosproject.bgpio.types.BgpLSIdentifierTlv.TYPE.
int org.onosproject.bgpio.types.BgpLSIdentifierTlv.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 92 of file BgpLSIdentifierTlv.java.
References org.onosproject.bgpio.types.BgpLSIdentifierTlv.LENGTH, and org.onosproject.bgpio.types.BgpLSIdentifierTlv.TYPE.
Member Data Documentation
final short org.onosproject.bgpio.types.BgpLSIdentifierTlv.LENGTH = 4 static
Definition at line 41 of file BgpLSIdentifierTlv.java.
Referenced by org.onosproject.bgpio.types.BgpLSIdentifierTlv.toString(), and org.onosproject.bgpio.types.BgpLSIdentifierTlv.write().
final short org.onosproject.bgpio.types.BgpLSIdentifierTlv.TYPE = 513 static
Definition at line 40 of file BgpLSIdentifierTlv.java.
Referenced by org.onosproject.bgpio.types.BgpLSIdentifierTlv.getType(), org.onosproject.bgpio.types.BgpLSIdentifierTlv.toString(), and org.onosproject.bgpio.types.BgpLSIdentifierTlv.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/BgpLSIdentifierTlv.java