onos: org.onosproject.routing.RouteUpdate Class Reference
org.onosproject.routing.RouteUpdate Class Reference
Represents a change in routing information.
Classes
enum Type
Specifies the type of a route update.
Public Member Functions
RouteUpdate (Type type, RouteEntry routeEntry)
Class constructor.
Type type ()
Returns the type of the route update.
RouteEntry routeEntry ()
Returns the route entry the route update is for.
boolean equals (Object other)
int hashCode ()
String toString ()
Detailed Description
Represents a change in routing information.
Definition at line 27 of file RouteUpdate.java.
Constructor & Destructor Documentation
org.onosproject.routing.RouteUpdate.RouteUpdate (Type type, RouteEntry routeEntry)
Class constructor.
Parameters
type the type of the route update
routeEntry the route entry with the update
Definition at line 56 of file RouteUpdate.java.
References org.onosproject.routing.RouteUpdate.type().
Referenced by org.onosproject.routing.RouteUpdate.equals().
Member Function Documentation
boolean org.onosproject.routing.RouteUpdate.equals (Object other)
Definition at line 80 of file RouteUpdate.java.
References org.onosproject.routing.RouteUpdate.RouteUpdate().
int org.onosproject.routing.RouteUpdate.hashCode ()
Definition at line 96 of file RouteUpdate.java.
References org.onosproject.routing.RouteUpdate.routeEntry(), and org.onosproject.routing.RouteUpdate.type().
RouteEntry org.onosproject.routing.RouteUpdate.routeEntry ()
Returns the route entry the route update is for.
Returns
the route entry the route update is for
Definition at line 75 of file RouteUpdate.java.
Referenced by org.onosproject.routing.RouteUpdate.hashCode(), and org.onosproject.routing.RouteUpdate.toString().
String org.onosproject.routing.RouteUpdate.toString ()
Definition at line 101 of file RouteUpdate.java.
References org.onosproject.routing.RouteUpdate.routeEntry(), and org.onosproject.routing.RouteUpdate.type().
Type org.onosproject.routing.RouteUpdate.type ()
Returns the type of the route update.
Returns
the type of the update
Definition at line 66 of file RouteUpdate.java.
Referenced by org.onosproject.routing.RouteUpdate.hashCode(), org.onosproject.routing.RouteUpdate.RouteUpdate(), and org.onosproject.routing.RouteUpdate.toString().
The documentation for this class was generated from the following file:
apps/routing-api/src/main/java/org/onosproject/routing/RouteUpdate.java