onos: org.onosproject.net.AbstractDescription Class Reference
org.onosproject.net.AbstractDescription Class Reference
Base implementation of an annotated model description.
Public Member Functions
SparseAnnotations annotations ()
Returns the key/value annotations.
int hashCode ()
boolean equals (Object object)
Protected Member Functions
AbstractDescription ()
AbstractDescription (SparseAnnotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Base implementation of an annotated model description.
Definition at line 24 of file AbstractDescription.java.
Constructor & Destructor Documentation
org.onosproject.net.AbstractDescription.AbstractDescription () protected
Definition at line 31 of file AbstractDescription.java.
Referenced by org.onosproject.net.AbstractDescription.equals().
org.onosproject.net.AbstractDescription.AbstractDescription (SparseAnnotations... annotations) protected
Creates a new entity, annotated with the specified annotations.
Parameters
annotations optional key/value annotations map
Definition at line 40 of file AbstractDescription.java.
References org.onosproject.net.AbstractDescription.annotations().
Member Function Documentation
SparseAnnotations org.onosproject.net.AbstractDescription.annotations ()
Returns the key/value annotations.
Returns
key/value annotations
Implements org.onosproject.net.Annotated.
Definition at line 46 of file AbstractDescription.java.
Referenced by org.onosproject.net.AbstractDescription.AbstractDescription(), org.onosproject.net.behaviour.DefaultBridgeDescription.DefaultBridgeDescription(), org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription(), org.onosproject.net.topology.DefaultGraphDescription.DefaultGraphDescription(), org.onosproject.net.host.DefaultHostDescription.DefaultHostDescription(), org.onosproject.net.link.DefaultLinkDescription.DefaultLinkDescription(), org.onosproject.net.device.DefaultPortDescription.DefaultPortDescription(), org.onosproject.net.behaviour.DefaultTunnelDescription.DefaultTunnelDescription(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.DefaultTunnelDescription(), org.onosproject.net.AbstractDescription.hashCode(), org.onosproject.net.device.OchPortDescription.OchPortDescription(), org.onosproject.net.device.OduCltPortDescription.OduCltPortDescription(), org.onosproject.net.device.OmsPortDescription.OmsPortDescription(), org.onosproject.net.device.OmsPortDescription.toString(), org.onosproject.net.device.OchPortDescription.toString(), and org.onosproject.net.device.DefaultPortDescription.toString().
boolean org.onosproject.net.AbstractDescription.equals (Object object)
Definition at line 56 of file AbstractDescription.java.
References org.onosproject.net.AbstractDescription.AbstractDescription().
int org.onosproject.net.AbstractDescription.hashCode ()
Definition at line 51 of file AbstractDescription.java.
References org.onosproject.net.AbstractDescription.annotations().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/AbstractDescription.java