onos: org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore Class Reference
org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore Class Reference
Implementation of the network store.
Public Member Functions
void activate ()
void deactivate ()
void addTenantId (TenantId tenantId)
void removeTenantId (TenantId tenantId)
Set< TenantId > getTenantIds ()
VirtualNetwork addNetwork (TenantId tenantId)
void removeNetwork (NetworkId networkId)
VirtualDevice addDevice (NetworkId networkId, DeviceId deviceId)
void removeDevice (NetworkId networkId, DeviceId deviceId)
VirtualLink addLink (NetworkId networkId, ConnectPoint src, ConnectPoint dst, TunnelId realizedBy)
void removeLink (NetworkId networkId, ConnectPoint src, ConnectPoint dst)
VirtualPort addPort (NetworkId networkId, DeviceId deviceId, PortNumber portNumber, Port realizedBy)
void removePort (NetworkId networkId, DeviceId deviceId, PortNumber portNumber)
Set< VirtualNetwork > getNetworks (TenantId tenantId)
Set< VirtualDevice > getDevices (NetworkId networkId)
Set< VirtualLink > getLinks (NetworkId networkId)
Set< VirtualPort > getPorts (NetworkId networkId, DeviceId deviceId)
Detailed Description
Implementation of the network store.
Definition at line 50 of file DistributedVirtualNetworkStore.java.
Member Function Documentation
void org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.activate ()
Definition at line 65 of file DistributedVirtualNetworkStore.java.
VirtualDevice org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.addDevice (NetworkId networkId, DeviceId deviceId)
Definition at line 102 of file DistributedVirtualNetworkStore.java.
VirtualLink org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.addLink (NetworkId networkId, ConnectPoint src, ConnectPoint dst, TunnelId realizedBy)
Definition at line 111 of file DistributedVirtualNetworkStore.java.
Referenced by obelisk.ObeliskTopo.__init__(), topo-200sw-linkalarm.MyTopo.__init__(), chordal.chordalTopo.__init__(), rftesttopo.ReactiveForwardingTestTopo.__init__(), attmpls.AttMplsTopo.__init__(), optical2.OpticalTopo.__init__(), newFuncTopo.MyTopo.__init__(), onos.ControlNetwork.__init__(), optical2.OpticalTopo.addIntf(), optical.OpticalTopo.addIntf(), metro.FabricDomain.addTether(), fractal.FractalTopo.build(), opticalTestBig.BigOpticalTopo.build(), opticalTest.SmallOpticalTopo.build(), tower.TowerTopo.build(), attmplsfast.AttMplsTopo.build(), optical.OpticalTopo.build(), tutorial.SdnIpTopo.build(), tutorial_ipv6.SdnIpTopo.build(), metro.OpticalDomain.build(), and metro.FabricDomain.build().
VirtualNetwork org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.addNetwork (TenantId tenantId)
Definition at line 88 of file DistributedVirtualNetworkStore.java.
VirtualPort org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.addPort (NetworkId networkId, DeviceId deviceId, PortNumber portNumber, Port realizedBy)
Definition at line 120 of file DistributedVirtualNetworkStore.java.
void org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.addTenantId (TenantId tenantId)
Definition at line 75 of file DistributedVirtualNetworkStore.java.
void org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.deactivate ()
Definition at line 70 of file DistributedVirtualNetworkStore.java.
Set<VirtualDevice> org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.getDevices (NetworkId networkId)
Definition at line 134 of file DistributedVirtualNetworkStore.java.
Set<VirtualLink> org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.getLinks (NetworkId networkId)
Definition at line 139 of file DistributedVirtualNetworkStore.java.
Set<VirtualNetwork> org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.getNetworks (TenantId tenantId)
Definition at line 129 of file DistributedVirtualNetworkStore.java.
Set<VirtualPort> org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.getPorts (NetworkId networkId, DeviceId deviceId)
Definition at line 144 of file DistributedVirtualNetworkStore.java.
Set<TenantId> org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.getTenantIds ()
Definition at line 83 of file DistributedVirtualNetworkStore.java.
void org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.removeDevice (NetworkId networkId, DeviceId deviceId)
Definition at line 107 of file DistributedVirtualNetworkStore.java.
void org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.removeLink (NetworkId networkId, ConnectPoint src, ConnectPoint dst)
Definition at line 116 of file DistributedVirtualNetworkStore.java.
void org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.removeNetwork (NetworkId networkId)
Definition at line 98 of file DistributedVirtualNetworkStore.java.
void org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.removePort (NetworkId networkId, DeviceId deviceId, PortNumber portNumber)
Definition at line 125 of file DistributedVirtualNetworkStore.java.
void org.onosproject.incubator.store.virtual .impl.DistributedVirtualNetworkStore.removeTenantId (TenantId tenantId)
Definition at line 79 of file DistributedVirtualNetworkStore.java.
The documentation for this class was generated from the following file:
incubator/store/src/main/java/org/onosproject/incubator/store/virtual/impl/DistributedVirtualNetworkStore.java