onos: org.onlab.packet.IPv4Test Class Reference
org.onlab.packet.IPv4Test Class Reference
Unit tests for IPv4 class.
Public Member Functions
void setUp () throws Exception
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws Exception
Detailed Description
Unit tests for IPv4 class.
Definition at line 30 of file IPv4Test.java.
Member Function Documentation
void org.onlab.packet.IPv4Test.setUp () throws Exception
Definition at line 51 of file IPv4Test.java.
void org.onlab.packet.IPv4Test.testDeserialize () throws Exception
Definition at line 82 of file IPv4Test.java.
References org.onlab.packet.IPv4.getChecksum(), org.onlab.packet.IPv4.getDestinationAddress(), org.onlab.packet.IPv4.getDiffServ(), org.onlab.packet.IPv4.getFlags(), org.onlab.packet.IPv4.getFragmentOffset(), org.onlab.packet.IPv4.getHeaderLength(), org.onlab.packet.IPv4.getIdentification(), org.onlab.packet.IPv4.getProtocol(), org.onlab.packet.IPv4.getSourceAddress(), org.onlab.packet.IPv4.getTotalLength(), org.onlab.packet.IPv4.getTtl(), org.onlab.packet.IPv4.getVersion(), org.onlab.packet.IPv4.isTruncated, and find-link-in-cluster.length.
void org.onlab.packet.IPv4Test.testDeserializeBadInput () throws Exception
Definition at line 72 of file IPv4Test.java.
void org.onlab.packet.IPv4Test.testDeserializeTruncated () throws Exception
Definition at line 77 of file IPv4Test.java.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/IPv4Test.java