onos: org.onosproject.mfwd.impl.McastConnectPoint Class Reference
org.onosproject.mfwd.impl.McastConnectPoint Class Reference
Mulitcast ConnectPoint adds a variable to track the usage of these multicast endpoints.
Classes
enum JoinSource
Public Member Functions
McastConnectPoint (ConnectPoint cp)
McastConnectPoint (ConnectPoint cp, JoinSource src)
McastConnectPoint (String connectPoint, JoinSource src)
ConnectPoint getConnectPoint ()
Get the connect point.
Set< JoinSource > getInterest ()
Get the sources of interest for this egressPoint.
Public Attributes
EnumSet< JoinSource > interest = EnumSet.noneOf(JoinSource.class)
Detailed Description
Mulitcast ConnectPoint adds a variable to track the usage of these multicast endpoints.
Definition at line 26 of file McastConnectPoint.java.
Constructor & Destructor Documentation
org.onosproject.mfwd.impl.McastConnectPoint.McastConnectPoint (ConnectPoint cp)
Definition at line 36 of file McastConnectPoint.java.
org.onosproject.mfwd.impl.McastConnectPoint.McastConnectPoint (ConnectPoint cp, JoinSource src)
Definition at line 40 of file McastConnectPoint.java.
org.onosproject.mfwd.impl.McastConnectPoint.McastConnectPoint (String connectPoint, JoinSource src)
Definition at line 45 of file McastConnectPoint.java.
Member Function Documentation
ConnectPoint org.onosproject.mfwd.impl.McastConnectPoint.getConnectPoint ()
Get the connect point.
Returns
connectPoint
Definition at line 56 of file McastConnectPoint.java.
Referenced by org.onosproject.mfwd.impl.McastRouteBase.toString().
Set<JoinSource> org.onosproject.mfwd.impl.McastConnectPoint.getInterest ()
Get the sources of interest for this egressPoint.
Returns
interest flags
Definition at line 65 of file McastConnectPoint.java.
References org.onosproject.mfwd.impl.McastConnectPoint.interest.
Member Data Documentation
EnumSet<JoinSource> org.onosproject.mfwd.impl.McastConnectPoint.interest = EnumSet.noneOf(JoinSource.class)
Definition at line 34 of file McastConnectPoint.java.
Referenced by org.onosproject.mfwd.impl.McastConnectPoint.getInterest(), and org.onosproject.mfwd.impl.McastRouteBase.removeInterest().
The documentation for this class was generated from the following file:
apps/mfwd/src/main/java/org/onosproject/mfwd/impl/McastConnectPoint.java