onos: org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric Class Reference
org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric Class Reference
Implements BGP prefix metric attribute.
Public Member Functions
BgpPrefixAttrMetric (int linkPfxMetric)
Constructor to initialize value.
int attrPfxMetric ()
Returns the Prefix Metric.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpPrefixAttrMetric of (final int linkPfxMetric)
Returns object of this class with specified values.
static BgpPrefixAttrMetric read (ChannelBuffer cb) throws BgpParseException
Reads the Prefix Metric.
Static Public Attributes
static final int ATTR_PREFIX_METRIC = 1155
static final int ATTR_PREFIX_LEN = 4
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP prefix metric attribute.
Definition at line 33 of file BgpPrefixAttrMetric.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.BgpPrefixAttrMetric (int linkPfxMetric)
Constructor to initialize value.
Parameters
linkPfxMetric Prefix Metric
Definition at line 49 of file BgpPrefixAttrMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.equals(), and org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.of().
Member Function Documentation
int org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.attrPfxMetric ()
Returns the Prefix Metric.
Returns
Prefix Metric
Definition at line 93 of file BgpPrefixAttrMetric.java.
int org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 133 of file BgpPrefixAttrMetric.java.
boolean org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.equals (Object obj)
Definition at line 108 of file BgpPrefixAttrMetric.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.BgpPrefixAttrMetric().
short org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 98 of file BgpPrefixAttrMetric.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.ATTR_PREFIX_METRIC.
int org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.hashCode ()
Definition at line 103 of file BgpPrefixAttrMetric.java.
static BgpPrefixAttrMetric org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.of (final int linkPfxMetric) static
Returns object of this class with specified values.
Parameters
linkPfxMetric Prefix Metric
Returns
object of BgpPrefixAttrMetric
Definition at line 59 of file BgpPrefixAttrMetric.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.BgpPrefixAttrMetric().
static BgpPrefixAttrMetric org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.read (ChannelBuffer cb) throws BgpParseException static
Reads the Prefix Metric.
Parameters
cb ChannelBuffer
Returns
object of BgpPrefixAttrMetric
Exceptions
BgpParseException while parsing BgpPrefixAttrMetric
Definition at line 70 of file BgpPrefixAttrMetric.java.
References org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.ATTR_PREFIX_LEN, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.toString ()
Definition at line 127 of file BgpPrefixAttrMetric.java.
int org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 121 of file BgpPrefixAttrMetric.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.ATTR_PREFIX_LEN = 4 static
Definition at line 39 of file BgpPrefixAttrMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.read().
final int org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.ATTR_PREFIX_METRIC = 1155 static
Definition at line 38 of file BgpPrefixAttrMetric.java.
Referenced by org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.getType().
final Logger org.onosproject.bgpio.types.attr.BgpPrefixAttrMetric.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpPrefixAttrMetric.class)
Definition at line 35 of file BgpPrefixAttrMetric.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpPrefixAttrMetric.java