onos: org.onosproject.bgpio.types.LocalPref Class Reference
org.onosproject.bgpio.types.LocalPref Class Reference
Provides implementation of LocalPref BGP Path Attribute.
Public Member Functions
LocalPref (int localPref)
Constructor to initialize LocalPref.
int localPref ()
Returns local preference value.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
String toString ()
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static LocalPref read (ChannelBuffer cb) throws BgpParseException
Reads the channel buffer and returns object of LocalPref.
Static Public Attributes
static final byte LOCAL_PREF_TYPE = 5
static final byte LOCAL_PREF_MAX_LEN = 4
Detailed Description
Provides implementation of LocalPref BGP Path Attribute.
Definition at line 30 of file LocalPref.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.LocalPref.LocalPref (int localPref)
Constructor to initialize LocalPref.
Parameters
localPref local preference
Definition at line 41 of file LocalPref.java.
References org.onosproject.bgpio.types.LocalPref.localPref().
Referenced by org.onosproject.bgpio.types.LocalPref.equals(), and org.onosproject.bgpio.types.LocalPref.read().
Member Function Documentation
int org.onosproject.bgpio.types.LocalPref.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 117 of file LocalPref.java.
boolean org.onosproject.bgpio.types.LocalPref.equals (Object obj)
Definition at line 92 of file LocalPref.java.
References org.onosproject.bgpio.types.LocalPref.LocalPref(), and org.onosproject.bgpio.types.LocalPref.localPref().
Referenced by org.onosproject.bgp.controller.impl.BgpSelectionAlgo.compare().
short org.onosproject.bgpio.types.LocalPref.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 82 of file LocalPref.java.
References org.onosproject.bgpio.types.LocalPref.LOCAL_PREF_TYPE.
int org.onosproject.bgpio.types.LocalPref.hashCode ()
Definition at line 87 of file LocalPref.java.
References org.onosproject.bgpio.types.LocalPref.localPref().
int org.onosproject.bgpio.types.LocalPref.localPref ()
Returns local preference value.
Returns
local preference value
Definition at line 50 of file LocalPref.java.
Referenced by org.onosproject.bgpio.types.LocalPref.equals(), org.onosproject.bgpio.types.LocalPref.hashCode(), org.onosproject.bgpio.types.LocalPref.LocalPref(), org.onosproject.bgpio.types.LocalPref.read(), and org.onosproject.bgpio.types.LocalPref.toString().
static LocalPref org.onosproject.bgpio.types.LocalPref.read (ChannelBuffer cb) throws BgpParseException static
Reads the channel buffer and returns object of LocalPref.
Parameters
cb channelBuffer
Returns
object of LocalPref
Exceptions
BgpParseException while parsing localPref attribute
Definition at line 61 of file LocalPref.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_FLAGS_ERROR, org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.LocalPref.LOCAL_PREF_MAX_LEN, org.onosproject.bgpio.types.LocalPref.LocalPref(), org.onosproject.bgpio.types.LocalPref.localPref(), org.onosproject.bgpio.util.Constants.TYPE_AND_LEN_AS_BYTE, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.LocalPref.toString ()
Definition at line 104 of file LocalPref.java.
References org.onosproject.bgpio.types.LocalPref.localPref().
int org.onosproject.bgpio.types.LocalPref.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 111 of file LocalPref.java.
Member Data Documentation
final byte org.onosproject.bgpio.types.LocalPref.LOCAL_PREF_MAX_LEN = 4 static
Definition at line 32 of file LocalPref.java.
Referenced by org.onosproject.bgpio.types.LocalPref.read().
final byte org.onosproject.bgpio.types.LocalPref.LOCAL_PREF_TYPE = 5 static
Definition at line 31 of file LocalPref.java.
Referenced by org.onosproject.bgpio.types.LocalPref.getType().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/LocalPref.java