onos: org.onosproject.net.device.impl.OpticalPortOperator Class Reference
org.onosproject.net.device.impl.OpticalPortOperator Class Reference
Implementations of merge policies for various sources of optical port configuration information.
Static Public Member Functions
static PortDescription combine (OpticalPortConfig opc, PortDescription descr)
Generates a PortDescription containing fields from a PortDescription and an OpticalPortConfig.
static SparseAnnotations combine (OpticalPortConfig opc, SparseAnnotations an)
Generates an annotation from an existing annotation and OptcalPortConfig.
static PortDescription descriptionOf (Port port)
Returns a description built from an existing port.
Detailed Description
Implementations of merge policies for various sources of optical port configuration information.
This includes applications, provides, and network configurations.
Definition at line 43 of file OpticalPortOperator.java.
Member Function Documentation
static PortDescription org.onosproject.net.device.impl.OpticalPortOperator.combine (OpticalPortConfig opc, PortDescription descr) static
Generates a PortDescription containing fields from a PortDescription and an OpticalPortConfig.
Parameters
opc the port config entity from network config
descr a PortDescription
Returns
PortDescription based on both sources
Definition at line 58 of file OpticalPortOperator.java.
References org.onosproject.net.Description.annotations(), create-flow.name, obeliskHostCheck.port, org.onosproject.net.PortNumber.portNumber(), org.onosproject.net.device.PortDescription.type(), and org.onosproject.net.config.basics.OpticalPortConfig.type().
Referenced by org.onosproject.net.device.impl.OpticalPortOperatorTest.testDescOps().
static SparseAnnotations org.onosproject.net.device.impl.OpticalPortOperator.combine (OpticalPortConfig opc, SparseAnnotations an) static
Generates an annotation from an existing annotation and OptcalPortConfig.
Parameters
opc the port config entity from network config
an the annotation
Returns
annotation combining both sources
Definition at line 131 of file OpticalPortOperator.java.
References org.onosproject.net.config.basics.OpticalPortConfig.name(), org.onosproject.net.AnnotationKeys.PORT_NAME, org.onosproject.net.AnnotationKeys.STATIC_LAMBDA, org.onosproject.net.AnnotationKeys.STATIC_PORT, org.onosproject.net.config.basics.OpticalPortConfig.staticLambda(), and org.onosproject.net.config.basics.OpticalPortConfig.staticPort().
static PortDescription org.onosproject.net.device.impl.OpticalPortOperator.descriptionOf (Port port) static
Returns a description built from an existing port.
Parameters
port the device port
Returns
a PortDescription based on the port
Definition at line 152 of file OpticalPortOperator.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/device/impl/OpticalPortOperator.java