onos: org.onosproject.codec.impl.FlowRuleCodecTest Class Reference
org.onosproject.codec.impl.FlowRuleCodecTest Class Reference
Flow rule codec unit tests.
Public Member Functions
void setUp ()
Sets up for each test.
void codecSimpleFlowTest () throws IOException
Checks that a simple rule decodes properly.
void decodeInstructionsFlowTest () throws Exception
Checks that a rule with one of each instruction type decodes properly.
void codecCriteriaFlowTest () throws Exception
Checks that a rule with one of each kind of criterion decodes properly.
void codecSigIdCriteriaFlowTest () throws Exception
Checks that a rule with a SigId criterion decodes properly.
Detailed Description
Flow rule codec unit tests.
Definition at line 92 of file FlowRuleCodecTest.java.
Member Function Documentation
void org.onosproject.codec.impl.FlowRuleCodecTest.codecCriteriaFlowTest () throws Exception
Checks that a rule with one of each kind of criterion decodes properly.
Exceptions
IOException if the resource cannot be processed
Definition at line 385 of file FlowRuleCodecTest.java.
References org.onosproject.net.OchSignalType.FIXED_GRID, org.onosproject.net.Lambda.indexedLambda(), obeliskHostCheck.mac, org.onosproject.net.OduSignalType.ODU4, obeliskHostCheck.port, org.onosproject.net.PortNumber.portNumber(), org.onosproject.net.flow.FlowRule.selector(), onos.size, org.onlab.packet.MacAddress.valueOf(), org.onlab.packet.IpPrefix.valueOf(), and org.onlab.packet.VlanId.vlanId().
void org.onosproject.codec.impl.FlowRuleCodecTest.codecSigIdCriteriaFlowTest () throws Exception
Checks that a rule with a SigId criterion decodes properly.
Exceptions
IOException if the resource cannot be processed
Definition at line 553 of file FlowRuleCodecTest.java.
References org.onosproject.net.ChannelSpacing.CHL_25GHZ, org.onosproject.net.GridType.CWDM, org.onosproject.net.flow.FlowRule.selector(), and onos.size.
void org.onosproject.codec.impl.FlowRuleCodecTest.codecSimpleFlowTest () throws IOException
Checks that a simple rule decodes properly.
Exceptions
IOException if the resource cannot be processed
Definition at line 151 of file FlowRuleCodecTest.java.
References org.onosproject.net.PortNumber.CONTROLLER, org.onosproject.net.flow.FlowRule.selector(), onos.size, and org.onosproject.net.flow.FlowRule.treatment().
void org.onosproject.codec.impl.FlowRuleCodecTest.decodeInstructionsFlowTest () throws Exception
Checks that a rule with one of each instruction type decodes properly.
Exceptions
IOException if the resource cannot be processed
Definition at line 189 of file FlowRuleCodecTest.java.
References org.onosproject.net.ChannelSpacing.CHL_100GHZ, org.onosproject.net.PortNumber.CONTROLLER, org.onosproject.net.GridType.DWDM, org.onlab.packet.MplsLabel.MAX_MPLS, org.onlab.packet.Ethernet.MPLS_UNICAST, create-flow.name, onos.size, org.onosproject.net.flow.FlowRule.treatment(), org.onlab.packet.MacAddress.valueOf(), and org.onlab.packet.IpAddress.valueOf().
void org.onosproject.codec.impl.FlowRuleCodecTest.setUp ()
Sets up for each test.
Creates a context and fetches the flow rule codec.
Definition at line 103 of file FlowRuleCodecTest.java.
References org.onosproject.core.CoreService.registerApplication(), and org.onosproject.codec.impl.FlowRuleCodec.REST_APP_ID.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/codec/impl/FlowRuleCodecTest.java