onos: org.onosproject.vtnrsc.RouterId Class Reference
org.onosproject.vtnrsc.RouterId Class Reference
Immutable representation of a router identifier.
Public Member Functions
String routerId ()
Returns the router identifier.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static RouterId valueOf (String routerId)
Creates a router identifier.
Detailed Description
Immutable representation of a router identifier.
Definition at line 26 of file RouterId.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.RouterId.equals (Object obj)
Definition at line 61 of file RouterId.java.
int org.onosproject.vtnrsc.RouterId.hashCode ()
Definition at line 56 of file RouterId.java.
String org.onosproject.vtnrsc.RouterId.routerId ()
Returns the router identifier.
Returns
the router identifier
Definition at line 51 of file RouterId.java.
Referenced by org.onosproject.vtnrsc.RouterId.toString().
String org.onosproject.vtnrsc.RouterId.toString ()
Definition at line 73 of file RouterId.java.
References org.onosproject.vtnrsc.RouterId.routerId().
static RouterId org.onosproject.vtnrsc.RouterId.valueOf (String routerId) static
Creates a router identifier.
Parameters
routerId the router identifier
Returns
the router identifier
Definition at line 42 of file RouterId.java.
Referenced by org.onosproject.vtnweb.resources.RouterWebResource.addRouterInterface(), org.onosproject.vtnrsc.cli.router.RouterUpdateCommand.execute(), org.onosproject.vtnrsc.cli.router.RouterCreateCommand.execute(), org.onosproject.vtnrsc.cli.floatingip.FloatingIpCreateCommand.execute(), org.onosproject.vtnweb.resources.RouterWebResource.getRouter(), and org.onosproject.vtnweb.resources.RouterWebResource.removeRouterInterface().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/RouterId.java