onos: org.onosproject.vtnrsc.DefaultPortPair Class Reference
org.onosproject.vtnrsc.DefaultPortPair Class Reference
Implementation of port pair.
Classes
class Builder
Builder class for Port pair.
Public Member Functions
PortPairId portPairId ()
Returns the ID of this port Pair.
TenantId tenantId ()
Returns the tenant id of this port pair.
String name ()
Returns the description of this port pair.
String description ()
Returns the description of this port pair.
String ingress ()
Returns the ingress port of this port pair.
String egress ()
Returns the egress port of this port pair.
int hashCode ()
boolean equals (Object obj)
boolean exactMatch (PortPair portPair)
Returns whether this port pair is an exact match to the port pair given in the argument.
String toString ()
Static Public Member Functions
static Builder builder ()
To create an instance of the builder.
Detailed Description
Implementation of port pair.
Definition at line 26 of file DefaultPortPair.java.
Member Function Documentation
static Builder org.onosproject.vtnrsc.DefaultPortPair.builder () static
To create an instance of the builder.
Returns
instance of builder
Definition at line 134 of file DefaultPortPair.java.
String org.onosproject.vtnrsc.DefaultPortPair.description ()
Returns the description of this port pair.
Returns
description of port pair
Implements org.onosproject.vtnrsc.PortPair.
Definition at line 73 of file DefaultPortPair.java.
Referenced by org.onosproject.vtnrsc.DefaultPortPair.hashCode().
String org.onosproject.vtnrsc.DefaultPortPair.egress ()
Returns the egress port of this port pair.
Returns
egress of port pair
Implements org.onosproject.vtnrsc.PortPair.
Definition at line 83 of file DefaultPortPair.java.
Referenced by org.onosproject.vtnrsc.DefaultPortPair.hashCode().
boolean org.onosproject.vtnrsc.DefaultPortPair.equals (Object obj)
Definition at line 94 of file DefaultPortPair.java.
References create-intent.ingress, org.onosproject.vtnrsc.DefaultPortPair.ingress(), create-flow.name, org.onosproject.vtnrsc.DefaultPortPair.name(), and org.onosproject.vtnrsc.DefaultPortPair.portPairId().
boolean org.onosproject.vtnrsc.DefaultPortPair.exactMatch (PortPair portPair)
Returns whether this port pair is an exact match to the port pair given in the argument.
Exact match means the Port port pairs match with the given port pair. It does not consider the port pair id, name and description.
Parameters
portPair other port pair to match against
Returns
true if the port pairs are an exact match, otherwise false
Implements org.onosproject.vtnrsc.PortPair.
Definition at line 111 of file DefaultPortPair.java.
References org.onosproject.vtnrsc.PortPair.portPairId(), and org.onosproject.vtnrsc.PortPair.tenantId().
int org.onosproject.vtnrsc.DefaultPortPair.hashCode ()
Definition at line 88 of file DefaultPortPair.java.
References org.onosproject.vtnrsc.DefaultPortPair.description(), org.onosproject.vtnrsc.DefaultPortPair.egress(), org.onosproject.vtnrsc.DefaultPortPair.ingress(), org.onosproject.vtnrsc.DefaultPortPair.name(), org.onosproject.vtnrsc.DefaultPortPair.portPairId(), and org.onosproject.vtnrsc.DefaultPortPair.tenantId().
String org.onosproject.vtnrsc.DefaultPortPair.ingress ()
Returns the ingress port of this port pair.
Returns
ingress of port pair
Implements org.onosproject.vtnrsc.PortPair.
Definition at line 78 of file DefaultPortPair.java.
Referenced by org.onosproject.vtnrsc.DefaultPortPair.equals(), org.onosproject.vtnrsc.DefaultPortPair.hashCode(), and org.onosproject.vtnrsc.DefaultPortPair.toString().
String org.onosproject.vtnrsc.DefaultPortPair.name ()
Returns the description of this port pair.
Returns
description of port pair
Implements org.onosproject.vtnrsc.PortPair.
Definition at line 68 of file DefaultPortPair.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.vtnrsc.DefaultPortPair.equals(), org.onosproject.vtnrsc.DefaultPortPair.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.vtnrsc.DefaultPortPair.toString().
PortPairId org.onosproject.vtnrsc.DefaultPortPair.portPairId ()
Returns the ID of this port Pair.
Returns
the port pair id
Implements org.onosproject.vtnrsc.PortPair.
Definition at line 58 of file DefaultPortPair.java.
Referenced by org.onosproject.vtnrsc.DefaultPortPair.equals(), and org.onosproject.vtnrsc.DefaultPortPair.hashCode().
TenantId org.onosproject.vtnrsc.DefaultPortPair.tenantId ()
Returns the tenant id of this port pair.
Returns
an tenant id
Implements org.onosproject.vtnrsc.PortPair.
Definition at line 63 of file DefaultPortPair.java.
Referenced by org.onosproject.vtnrsc.DefaultPortPair.hashCode().
String org.onosproject.vtnrsc.DefaultPortPair.toString ()
Definition at line 118 of file DefaultPortPair.java.
References org.onosproject.vtnrsc.DefaultPortPair.ingress(), and org.onosproject.vtnrsc.DefaultPortPair.name().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultPortPair.java