onos: org.onlab.packet.MacAddress Class Reference
org.onlab.packet.MacAddress Class Reference
The class representing MAC address.
Public Member Functions
MacAddress (final byte[] address)
int length ()
Returns the length of the.
byte[] toBytes ()
Returns the value of the.
long toLong ()
Returns the value of the.
boolean isBroadcast ()
Returns.
boolean isMulticast ()
Returns.
boolean isLinkLocal ()
Returns true if this MAC address is link local.
boolean equals (final Object o)
int hashCode ()
String toString ()
String toStringNoColon ()
Static Public Member Functions
static MacAddress valueOf (final String address)
Returns a MAC address instance representing the value of the specified.
static MacAddress valueOf (final byte[] address)
Returns a MAC address instance representing the specified.
static MacAddress valueOf (final long address)
Returns a MAC address instance representing the specified.
Static Public Attributes
static final MacAddress NONE = valueOf("a4:23:05:00:00:00")
static final MacAddress ZERO = valueOf("00:00:00:00:00:00")
static final MacAddress BROADCAST = valueOf("ff:ff:ff:ff:ff:ff")
static final int MAC_ADDRESS_LENGTH = 6
Detailed Description
The class representing MAC address.
Definition at line 23 of file MacAddress.java.
Constructor & Destructor Documentation
org.onlab.packet.MacAddress.MacAddress (final byte[] address)
Definition at line 37 of file MacAddress.java.
References org.onlab.packet.MacAddress.MAC_ADDRESS_LENGTH.
Referenced by org.onlab.packet.MacAddress.equals(), and org.onlab.packet.MacAddress.valueOf().
Member Function Documentation
boolean org.onlab.packet.MacAddress.equals (final Object o)
Definition at line 177 of file MacAddress.java.
References org.onlab.packet.MacAddress.MacAddress().
Referenced by org.onlab.packet.Ethernet.equals().
int org.onlab.packet.MacAddress.hashCode ()
Definition at line 191 of file MacAddress.java.
References org.onlab.packet.MacAddress.toLong().
boolean org.onlab.packet.MacAddress.isBroadcast ()
Returns.
true
if the MAC address is the broadcast address.
Returns
true
if the MAC address is the broadcast address.
Definition at line 144 of file MacAddress.java.
Referenced by org.onlab.packet.MacAddress.isMulticast().
boolean org.onlab.packet.MacAddress.isLinkLocal ()
Returns true if this MAC address is link local.
Returns
true if link local
Definition at line 170 of file MacAddress.java.
boolean org.onlab.packet.MacAddress.isMulticast ()
Returns.
true
if the MAC address is the multicast address.
Returns
true
if the MAC address is the multicast address.
Definition at line 158 of file MacAddress.java.
References org.onlab.packet.MacAddress.isBroadcast().
int org.onlab.packet.MacAddress.length ()
Returns the length of the.
MACAddress
.
Returns
the length of the
MACAddress
.
Definition at line 110 of file MacAddress.java.
References find-link-in-cluster.length.
byte [] org.onlab.packet.MacAddress.toBytes ()
Returns the value of the.
MACAddress
as a
byte
array.
Returns
the numeric value represented by this object after conversion to type
byte
array.
Definition at line 120 of file MacAddress.java.
References find-link-in-cluster.length.
Referenced by org.onlab.packet.ArpTest.testDeserialize(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExist(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExistWithVlan(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExist(), and org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExistWithVlan().
long org.onlab.packet.MacAddress.toLong ()
Returns the value of the.
MACAddress
as a
long
.
Returns
the numeric value represented by this object after conversion to type
long
.
Definition at line 130 of file MacAddress.java.
References obeliskHostCheck.mac.
Referenced by org.onlab.packet.MacAddress.hashCode().
String org.onlab.packet.MacAddress.toString ()
Definition at line 196 of file MacAddress.java.
String org.onlab.packet.MacAddress.toStringNoColon ()
Returns
MAC address in string representation without colons (useful for radix tree storage)
Definition at line 211 of file MacAddress.java.
static MacAddress org.onlab.packet.MacAddress.valueOf (final String address) static
Returns a MAC address instance representing the value of the specified.
String
.
Parameters
address the String representation of the MAC Address to be parsed.
Returns
a MAC Address instance representing the value of the specified
String
.
Exceptions
IllegalArgumentException if the string cannot be parsed as a MAC address.
Definition at line 50 of file MacAddress.java.
References org.onlab.packet.MacAddress.MAC_ADDRESS_LENGTH, and org.onlab.packet.MacAddress.MacAddress().
Referenced by org.onosproject.codec.impl.FlowRuleCodecTest.codecCriteriaFlowTest(), org.onosproject.provider.nil.TopologySimulator.createHosts(), org.onosproject.openstackswitching.web.OpenstackPortCodec.decode(), org.onosproject.codec.impl.FlowRuleCodecTest.decodeInstructionsFlowTest(), org.onosproject.dhcp.rest.DhcpWebResource.deleteMapping(), org.onosproject.cli.net.AddTestFlowsCommand.execute(), org.onosproject.vtnrsc.cli.virtualport.VirtualPortCreateCommand.execute(), org.onosproject.vtnrsc.cli.virtualport.VirtualPortUpdateCommand.execute(), org.onosproject.incubator.net.config.basics.InterfaceConfig.getInterfaces(), org.onosproject.codec.impl.InstructionCodecTest.modEtherInstructionTest(), org.onosproject.dhcp.rest.DhcpWebResource.setMapping(), org.onosproject.net.group.impl.GroupManagerTest.testGroupOperationFailure(), org.onosproject.store.trivial.SimpleGroupStoreTest.testGroupOperationFailure(), org.onosproject.routing.impl.RouterTest.testIpv4RouteAdd(), org.onosproject.routing.impl.RouterTest.testIpv6RouteAdd(), org.onosproject.routing.impl.RouterTest.testIpv6RouteUpdate(), org.onosproject.store.serializers.KryoSerializerTest.testMacAddress(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyExternalPortBadRequestIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestForUsIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUsIpv6(), org.onosproject.routing.impl.RouterAsyncArpTest.testRouteAdd(), org.onosproject.routing.impl.RouterAsyncArpTest.testRouteUpdate(), and org.onosproject.routing.impl.RouterTest.testRouteUpdate().
static MacAddress org.onlab.packet.MacAddress.valueOf (final byte[] address) static
Returns a MAC address instance representing the specified.
byte
array.
Parameters
address the byte array to be parsed.
Returns
a MAC address instance representing the specified
byte
array.
Exceptions
IllegalArgumentException if the byte array cannot be parsed as a MAC address.
Definition at line 76 of file MacAddress.java.
References org.onlab.packet.MacAddress.MAC_ADDRESS_LENGTH, and org.onlab.packet.MacAddress.MacAddress().
static MacAddress org.onlab.packet.MacAddress.valueOf (final long address) static
Returns a MAC address instance representing the specified.
long
value. The lower 48 bits of the long value are used to parse as a MAC address.
Parameters
address the long value to be parsed. The lower 48 bits are used for a MAC address.
Returns
a MAC address instance representing the specified
long
value.
Exceptions
IllegalArgumentException if the long value cannot be parsed as a MAC address.
Definition at line 96 of file MacAddress.java.
References org.onlab.packet.MacAddress.MacAddress().
Member Data Documentation
final MacAddress org.onlab.packet.MacAddress.BROADCAST = valueOf("ff:ff:ff:ff:ff:ff") static
Definition at line 27 of file MacAddress.java.
Referenced by org.onosproject.codec.impl.IntentCodecTest.intentWithTreatmentSelectorAndConstraints(), org.onosproject.vtn.table.impl.L2ForwardServiceImpl.programLocalBcastRules(), org.onosproject.vtn.table.impl.L2ForwardServiceImpl.programTunnelBcastRules(), and org.onosproject.net.flow.DefaultTrafficTreatmentTest.testBuilderMethods().
final int org.onlab.packet.MacAddress.MAC_ADDRESS_LENGTH = 6 static
Definition at line 34 of file MacAddress.java.
Referenced by org.onlab.packet.Ethernet.deserialize(), org.onlab.packet.MacAddress.MacAddress(), org.onosproject.store.serializers.MacAddressSerializer.read(), and org.onlab.packet.MacAddress.valueOf().
final MacAddress org.onlab.packet.MacAddress.NONE = valueOf("a4:23:05:00:00:00") static
Definition at line 25 of file MacAddress.java.
Referenced by org.onosproject.segmentrouting.RoutingRulePopulator.populateSubnetBroadcastRule(), and org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective().
final MacAddress org.onlab.packet.MacAddress.ZERO = valueOf("00:00:00:00:00:00") static
Definition at line 26 of file MacAddress.java.
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/MacAddress.java