onos: org.onlab.packet.IpPrefixTest Class Reference
org.onlab.packet.IpPrefixTest Class Reference
Tests for class IpPrefix.
Public Member Functions
void testImmutable ()
Tests the immutability of IpPrefix.
void testMaxMaskLength ()
Tests the maximum mask length.
void testVersion ()
Tests returning the IP version of the prefix.
void testIsIp4 ()
Tests whether the IP version of a prefix is IPv4.
void testIsIp6 ()
Tests whether the IP version of a prefix is IPv6.
void testAddressAndPrefixLengthIPv4 ()
Tests returning the IP address value and IP address prefix length of an IPv4 prefix.
void testAddressAndPrefixLengthIPv6 ()
Tests returning the IP address value and IP address prefix length of an IPv6 prefix.
void testGetIp4AndIp6PrefixView ()
Tests getting the Ip4Prefix and Ip6Prefix view of the IP prefix.
void testValueOfForIntegerIPv4 ()
Tests valueOf() converter for IPv4 integer value.
void testInvalidValueOfIntegerNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 integer value and negative prefix length.
void testInvalidValueOfIntegerTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 integer value and too long prefix length.
void testValueOfByteArrayIPv4 ()
Tests valueOf() converter for IPv4 byte array.
void testValueOfByteArrayIPv6 ()
Tests valueOf() converter for IPv6 byte array.
void testInvalidValueOfNullArrayIPv4 ()
Tests invalid valueOf() converter for a null array for IPv4.
void testInvalidValueOfNullArrayIPv6 ()
Tests invalid valueOf() converter for a null array for IPv6.
void testInvalidValueOfShortArrayIPv4 ()
Tests invalid valueOf() converter for a short array for IPv4.
void testInvalidValueOfShortArrayIPv6 ()
Tests invalid valueOf() converter for a short array for IPv6.
void testInvalidValueOfByteArrayNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 byte array and negative prefix length.
void testInvalidValueOfByteArrayNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 byte array and negative prefix length.
void testInvalidValueOfByteArrayTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 byte array and too long prefix length.
void testInvalidValueOfByteArrayTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 byte array and too long prefix length.
void testValueOfAddressIPv4 ()
Tests valueOf() converter for IPv4 address.
void testValueOfAddressIPv6 ()
Tests valueOf() converter for IPv6 address.
void testInvalidValueOfNullAddress ()
Tests invalid valueOf() converter for a null IP address.
void testInvalidValueOfAddressNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 address and negative prefix length.
void testInvalidValueOfAddressNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 address and negative prefix length.
void testInvalidValueOfAddressTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 address and too long prefix length.
void testInvalidValueOfAddressTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 address and too long prefix length.
void testValueOfStringIPv4 ()
Tests valueOf() converter for IPv4 string.
void testValueOfStringIPv6 ()
Tests valueOf() converter for IPv6 string.
void testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
void testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
void testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
void testInvalidValueOfStringNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 string and negative prefix length.
void testInvalidValueOfStringNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 string and negative prefix length.
void testInvalidValueOfStringTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 string and too long prefix length.
void testInvalidValueOfStringTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 string and too long prefix length.
void testContainsIpPrefixIPv4 ()
Tests IP prefix contains another IP prefix for IPv4.
void testContainsIpPrefixIPv6 ()
Tests IP prefix contains another IP prefix for IPv6.
void testContainsIpAddressIPv4 ()
Tests IP prefix contains IP address for IPv4.
void testContainsIpAddressIPv6 ()
Tests IP prefix contains IP address for IPv6.
void testEqualityIPv4 ()
Tests equality of IpPrefix for IPv4.
void testEqualityIPv6 ()
Tests equality of IpPrefix for IPv6.
void testToStringIPv4 ()
Tests object string representation for IPv4.
void testToStringIPv6 ()
Tests object string representation for IPv6.
Detailed Description
Tests for class IpPrefix.
Definition at line 33 of file IpPrefixTest.java.
Member Function Documentation
void org.onlab.packet.IpPrefixTest.testAddressAndPrefixLengthIPv4 ()
Tests returning the IP address value and IP address prefix length of an IPv4 prefix.
Definition at line 104 of file IpPrefixTest.java.
References org.onlab.packet.IpAddress.valueOf().
void org.onlab.packet.IpPrefixTest.testAddressAndPrefixLengthIPv6 ()
Tests returning the IP address value and IP address prefix length of an IPv6 prefix.
Definition at line 138 of file IpPrefixTest.java.
References org.onlab.packet.IpAddress.valueOf().
void org.onlab.packet.IpPrefixTest.testContainsIpAddressIPv4 ()
Tests IP prefix contains IP address for IPv4.
Definition at line 893 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.contains(), and org.onlab.packet.IpAddress.valueOf().
void org.onlab.packet.IpPrefixTest.testContainsIpAddressIPv6 ()
Tests IP prefix contains IP address for IPv6.
Definition at line 935 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.contains(), and org.onlab.packet.IpAddress.valueOf().
void org.onlab.packet.IpPrefixTest.testContainsIpPrefixIPv4 ()
Tests IP prefix contains another IP prefix for IPv4.
Definition at line 760 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.contains(), and org.onlab.packet.IpPrefix.valueOf().
void org.onlab.packet.IpPrefixTest.testContainsIpPrefixIPv6 ()
Tests IP prefix contains another IP prefix for IPv6.
Definition at line 814 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.contains(), and org.onlab.packet.IpPrefix.valueOf().
void org.onlab.packet.IpPrefixTest.testEqualityIPv4 ()
Tests equality of IpPrefix for IPv4.
Definition at line 994 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.valueOf().
void org.onlab.packet.IpPrefixTest.testEqualityIPv6 ()
Tests equality of IpPrefix for IPv6.
Definition at line 1016 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.valueOf().
void org.onlab.packet.IpPrefixTest.testGetIp4AndIp6PrefixView ()
Tests getting the Ip4Prefix and Ip6Prefix view of the IP prefix.
Definition at line 183 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testImmutable ()
Tests the immutability of IpPrefix.
Definition at line 38 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfAddressNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 address and negative prefix length.
Definition at line 556 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfAddressNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 address and negative prefix length.
Definition at line 569 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfAddressTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 address and too long prefix length.
Definition at line 583 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfAddressTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 address and too long prefix length.
Definition at line 596 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfByteArrayNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 byte array and negative prefix length.
Definition at line 411 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfByteArrayNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 byte array and negative prefix length.
Definition at line 424 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfByteArrayTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 byte array and too long prefix length.
Definition at line 440 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfByteArrayTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 byte array and too long prefix length.
Definition at line 453 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
Definition at line 690 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
Definition at line 702 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfIntegerNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 integer value and negative prefix length.
Definition at line 254 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfIntegerTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 integer value and too long prefix length.
Definition at line 265 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfNullAddress ()
Tests invalid valueOf() converter for a null IP address.
Definition at line 543 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfNullArrayIPv4 ()
Tests invalid valueOf() converter for a null array for IPv4.
Definition at line 362 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfNullArrayIPv6 ()
Tests invalid valueOf() converter for a null array for IPv6.
Definition at line 374 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
Definition at line 678 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfShortArrayIPv4 ()
Tests invalid valueOf() converter for a short array for IPv4.
Definition at line 386 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfShortArrayIPv6 ()
Tests invalid valueOf() converter for a short array for IPv6.
Definition at line 398 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfStringNegativePrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 string and negative prefix length.
Definition at line 715 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfStringNegativePrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 string and negative prefix length.
Definition at line 726 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfStringTooLongPrefixLengthIPv4 ()
Tests invalid valueOf() converter for IPv4 string and too long prefix length.
Definition at line 738 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testInvalidValueOfStringTooLongPrefixLengthIPv6 ()
Tests invalid valueOf() converter for IPv6 string and too long prefix length.
Definition at line 749 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testIsIp4 ()
Tests whether the IP version of a prefix is IPv4.
Definition at line 71 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.isIp4().
void org.onlab.packet.IpPrefixTest.testIsIp6 ()
Tests whether the IP version of a prefix is IPv6.
Definition at line 87 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.isIp6().
void org.onlab.packet.IpPrefixTest.testMaxMaskLength ()
Tests the maximum mask length.
Definition at line 46 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.MAX_INET6_MASK_LENGTH, and org.onlab.packet.IpPrefix.MAX_INET_MASK_LENGTH.
void org.onlab.packet.IpPrefixTest.testToStringIPv4 ()
Tests object string representation for IPv4.
Definition at line 1044 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.IpPrefixTest.testToStringIPv6 ()
Tests object string representation for IPv6.
Definition at line 1064 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.IpPrefixTest.testValueOfAddressIPv4 ()
Tests valueOf() converter for IPv4 address.
Definition at line 468 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testValueOfAddressIPv6 ()
Tests valueOf() converter for IPv6 address.
Definition at line 505 of file IpPrefixTest.java.
void org.onlab.packet.IpPrefixTest.testValueOfByteArrayIPv4 ()
Tests valueOf() converter for IPv4 byte array.
Definition at line 275 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.IpPrefixTest.testValueOfByteArrayIPv6 ()
Tests valueOf() converter for IPv6 byte array.
Definition at line 313 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.IpPrefixTest.testValueOfForIntegerIPv4 ()
Tests valueOf() converter for IPv4 integer value.
Definition at line 221 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.IpPrefixTest.testValueOfStringIPv4 ()
Tests valueOf() converter for IPv4 string.
Definition at line 609 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.IpPrefixTest.testValueOfStringIPv6 ()
Tests valueOf() converter for IPv6 string.
Definition at line 641 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.toString().
void org.onlab.packet.IpPrefixTest.testVersion ()
Tests returning the IP version of the prefix.
Definition at line 55 of file IpPrefixTest.java.
References org.onlab.packet.IpPrefix.version().
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/IpPrefixTest.java