onos: org.onosproject.net.topology.DefaultTopologyClusterTest Class Reference
org.onosproject.net.topology.DefaultTopologyClusterTest Class Reference
Test of the default topology cluster implementation.
Public Member Functions
void testEquals ()
void basics ()
Detailed Description
Test of the default topology cluster implementation.
Definition at line 28 of file DefaultTopologyClusterTest.java.
Member Function Documentation
void org.onosproject.net.topology.DefaultTopologyClusterTest.basics ()
Definition at line 41 of file DefaultTopologyClusterTest.java.
References org.onosproject.net.topology.TopologyCluster.deviceCount(), find-flow.deviceId, org.onosproject.net.topology.TopologyCluster.id(), org.onosproject.net.topology.TopologyCluster.linkCount(), and org.onosproject.net.topology.TopologyCluster.root().
void org.onosproject.net.topology.DefaultTopologyClusterTest.testEquals ()
Definition at line 31 of file DefaultTopologyClusterTest.java.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/topology/DefaultTopologyClusterTest.java