onos: org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1 Class Reference
org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1 Class Reference
Provides PCEP label Object .
Classes
class Builder
Builder class for PCEP lspa object.
Public Member Functions
PcepLspaObjectVer1 (PcepObjectHeader lspaObjHeader, boolean bLFlag, int iExcludeAny, int iIncludeAny, int iIncludeAll, byte cSetupPriority, byte cHoldPriority, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize member variables.
void setLspaObjHeader (PcepObjectHeader obj)
Sets Object Header.
void setExcludeAny (int iExcludeAny)
Sets Exclude Any field in LSPA Object.
void setIncludeAny (int iIncludeAny)
Sets Include Any field in LSPA Object.
void setSetupPriority (byte cSetupPriority)
Sets Setup Priority field in LSPA Object.
void setHoldPriority (byte cHoldPriority)
Sets Hold Priority field in LSPA Object.
void setLFlag (boolean bLFlag)
Sets L flag in LSPA Object.
PcepObjectHeader getLspaObjHeader ()
Returns lspa Object Header.
int getExcludeAny ()
Returns Exclude Any field in LSPA Object.
int getIncludeAny ()
Returns Include Any field in LSPA Object.
int getIncludeAll ()
Returns Include All field in LSPA Object.
byte getSetupPriority ()
Returns Setup Priority field in LSPA Object.
byte getHoldPriority ()
Returns Hold Priority field in LSPA Object.
boolean getLFlag ()
Returns L flag in LSPA Object.
void setIncludeAll (int value)
Sets Include All field in LSPA Object.
LinkedList< PcepValueType > getOptionalTlv ()
Returns list of Optional Tlvs in LSPA Object.
void setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets Optional Tlvs in LSPA Object.
int write (ChannelBuffer cb) throws PcepParseException
Writes the LSPA Object into channel buffer.
String toString ()
Static Public Member Functions
static PcepLspaObject read (ChannelBuffer cb) throws PcepParseException
Reads channel buffer and returns object of PcepLspaObject.
static LinkedList< PcepValueType > parseOptionalTlv (ChannelBuffer cb) throws PcepParseException
Parse list of optional tlvs.
Static Public Attributes
static final byte LSPA_OBJ_TYPE = 1
static final byte LSPA_OBJ_CLASS = 9
static final byte LSPA_OBJECT_VERSION = 1
static final short LSPA_OBJ_MINIMUM_LENGTH = 20
static final int OBJECT_HEADER_LENGTH = 4
static final int SETUP_PRIORITY_SHIFT_VALUE = 24
static final int HOLD_PRIORITY_SHIFT_VALUE = 16
static final int BFLAG_SHIFT_VALUE = 8
static final int LFLAG_SET = 1
static final int LFLAG_RESET = 0
Protected Member Functions
boolean packOptionalTlv (ChannelBuffer cb)
Writes optional tlvs to channel buffer.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(PcepLspaObjectVer1.class)
Detailed Description
Provides PCEP label Object .
Definition at line 35 of file PcepLspaObjectVer1.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.PcepLspaObjectVer1 (PcepObjectHeader lspaObjHeader, boolean bLFlag, int iExcludeAny, int iIncludeAny, int iIncludeAll, byte cSetupPriority, byte cHoldPriority, LinkedList< PcepValueType > llOptionalTlv)
Constructor to initialize member variables.
Parameters
lspaObjHeader lspa object header
bLFlag b l flag
iExcludeAny excludeAny value
iIncludeAny includeAny value
iIncludeAll includeAll value
cSetupPriority setup priority value
cHoldPriority hold priority value
llOptionalTlv list of optional tlv
Definition at line 93 of file PcepLspaObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.read().
Member Function Documentation
int org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.getExcludeAny ()
Returns Exclude Any field in LSPA Object.
Returns
Exclude Any field in LSPA Object
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 150 of file PcepLspaObjectVer1.java.
byte org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.getHoldPriority ()
Returns Hold Priority field in LSPA Object.
Returns
Hold Priority field in LSPA Object
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 170 of file PcepLspaObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.getIncludeAll ()
Returns Include All field in LSPA Object.
Returns
Include All field in LSPA Object
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 160 of file PcepLspaObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.getIncludeAny ()
Returns Include Any field in LSPA Object.
Returns
Include Any field in LSPA Object
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 155 of file PcepLspaObjectVer1.java.
boolean org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.getLFlag ()
Returns L flag in LSPA Object.
Returns
L flag in LSPA Object
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 175 of file PcepLspaObjectVer1.java.
PcepObjectHeader org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.getLspaObjHeader ()
Returns lspa Object Header.
Returns
lspa Object Header
Definition at line 145 of file PcepLspaObjectVer1.java.
LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.getOptionalTlv ()
Returns list of Optional Tlvs in LSPA Object.
Returns
list of Optional Tlvs in LSPA Object
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 186 of file PcepLspaObjectVer1.java.
byte org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.getSetupPriority ()
Returns Setup Priority field in LSPA Object.
Returns
Setup Priority field in LSPA Object
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 165 of file PcepLspaObjectVer1.java.
boolean org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.packOptionalTlv (ChannelBuffer cb) protected
Writes optional tlvs to channel buffer.
Parameters
cb channel buffer
Returns
true
Definition at line 304 of file PcepLspaObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.write().
static LinkedList<PcepValueType> org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.parseOptionalTlv (ChannelBuffer cb) throws PcepParseException static
Parse list of optional tlvs.
Parameters
cb channel buffer
Returns
list of optional tlvs.
Exceptions
PcepParseException when fails to parse optional tlv list.
Definition at line 291 of file PcepLspaObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.read().
static PcepLspaObject org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.read (ChannelBuffer cb) throws PcepParseException static
Reads channel buffer and returns object of PcepLspaObject.
Parameters
cb of type channel buffer.
Returns
object of PcepLspaObject
Exceptions
PcepParseException while parsing lspa object from channel buffer
Definition at line 203 of file PcepLspaObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.LFLAG_SET, org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.OBJECT_HEADER_LENGTH, org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.parseOptionalTlv(), and org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.PcepLspaObjectVer1().
void org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.setExcludeAny (int value)
Sets Exclude Any field in LSPA Object.
Parameters
value Exclude Any field
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 116 of file PcepLspaObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.setHoldPriority (byte value)
Sets Hold Priority field in LSPA Object.
Parameters
value Hold Priority field
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 131 of file PcepLspaObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.setIncludeAll (int value)
Sets Include All field in LSPA Object.
Parameters
value Include All field
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 180 of file PcepLspaObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.setIncludeAny (int value)
Sets Include Any field in LSPA Object.
Parameters
value Include Any field
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 121 of file PcepLspaObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.setLFlag (boolean value)
Sets L flag in LSPA Object.
Parameters
value L flag
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 136 of file PcepLspaObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.setLspaObjHeader (PcepObjectHeader obj)
Sets Object Header.
Parameters
obj lspa object header
Definition at line 111 of file PcepLspaObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.setOptionalTlv (LinkedList< PcepValueType > llOptionalTlv)
Sets Optional Tlvs in LSPA Object.
Parameters
llOptionalTlv Optional Tlvs in LSPA Object
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 191 of file PcepLspaObjectVer1.java.
void org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.setSetupPriority (byte value)
Sets Setup Priority field in LSPA Object.
Parameters
value Setup Priority field
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 126 of file PcepLspaObjectVer1.java.
String org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.toString ()
Definition at line 518 of file PcepLspaObjectVer1.java.
int org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.write (ChannelBuffer bb) throws PcepParseException
Writes the LSPA Object into channel buffer.
Parameters
bb channel buffer
Returns
Returns the writerIndex of this buffer
Exceptions
PcepParseException while writing LSPA object into Channel Buffer.
Implements org.onosproject.pcepio.protocol.PcepLspaObject.
Definition at line 239 of file PcepLspaObjectVer1.java.
References org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.BFLAG_SHIFT_VALUE, org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.HOLD_PRIORITY_SHIFT_VALUE, find-link-in-cluster.length, org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.LFLAG_RESET, org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.LFLAG_SET, org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.packOptionalTlv(), and org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.SETUP_PRIORITY_SHIFT_VALUE.
Member Data Documentation
final int org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.BFLAG_SHIFT_VALUE = 8 static
Definition at line 69 of file PcepLspaObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.write().
final int org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.HOLD_PRIORITY_SHIFT_VALUE = 16 static
Definition at line 68 of file PcepLspaObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.write().
final int org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.LFLAG_RESET = 0 static
Definition at line 71 of file PcepLspaObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.write().
final int org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.LFLAG_SET = 1 static
Definition at line 70 of file PcepLspaObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.read(), and org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.write().
final Logger org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.log = LoggerFactory.getLogger(PcepLspaObjectVer1.class) static protected
Definition at line 56 of file PcepLspaObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.LSPA_OBJ_CLASS = 9 static
Definition at line 59 of file PcepLspaObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepAttributeVer1.read().
final short org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.LSPA_OBJ_MINIMUM_LENGTH = 20 static
Definition at line 61 of file PcepLspaObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.LSPA_OBJ_TYPE = 1 static
Definition at line 58 of file PcepLspaObjectVer1.java.
final byte org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.LSPA_OBJECT_VERSION = 1 static
Definition at line 60 of file PcepLspaObjectVer1.java.
final int org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.OBJECT_HEADER_LENGTH = 4 static
Definition at line 62 of file PcepLspaObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.read().
final int org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.SETUP_PRIORITY_SHIFT_VALUE = 24 static
Definition at line 67 of file PcepLspaObjectVer1.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepLspaObjectVer1.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/ver1/PcepLspaObjectVer1.java