onos: org.onosproject.sdnip.SdnIpFibTest Class Reference
org.onosproject.sdnip.SdnIpFibTest Class Reference
Unit tests for SdnIpFib.
Public Member Functions
void setUp () throws Exception
void testFibAdd ()
Tests adding a FIB entry to the IntentSynchronizer.
void testFibAddWithVlan ()
Tests adding a FIB entry with to a next hop in a VLAN.
void testFibUpdate ()
Tests updating a FIB entry.
void testFibDelete ()
Tests deleting a FIB entry.
Public Member Functions inherited from org.onosproject.net.intent.AbstractIntentTest
void setUp () throws Exception
void tearDown ()
Additional Inherited Members
Protected Attributes inherited from org.onosproject.net.intent.AbstractIntentTest
IdGenerator idGenerator = new MockIdGenerator()
Detailed Description
Unit tests for SdnIpFib.
Definition at line 66 of file SdnIpFibTest.java.
Member Function Documentation
void org.onosproject.sdnip.SdnIpFibTest.setUp () throws Exception
Definition at line 94 of file SdnIpFibTest.java.
void org.onosproject.sdnip.SdnIpFibTest.testFibAdd ()
Tests adding a FIB entry to the IntentSynchronizer.
We verify that the synchronizer records the correct state and that the correct intent is submitted to the IntentService.
Definition at line 207 of file SdnIpFibTest.java.
References org.onosproject.sdnip.SdnIpFib.CONSTRAINTS, onosUploadBits.prefix, org.onlab.packet.Ethernet.TYPE_IPV4, and org.onlab.packet.Ip4Address.valueOf().
Referenced by org.onosproject.sdnip.SdnIpFibTest.testFibDelete(), and org.onosproject.sdnip.SdnIpFibTest.testFibUpdate().
void org.onosproject.sdnip.SdnIpFibTest.testFibAddWithVlan ()
Tests adding a FIB entry with to a next hop in a VLAN.
We verify that the synchronizer records the correct state and that the correct intent is submitted to the IntentService.
Definition at line 257 of file SdnIpFibTest.java.
References org.onlab.packet.VlanId.ANY, org.onosproject.sdnip.SdnIpFib.CONSTRAINTS, onosUploadBits.prefix, org.onlab.packet.Ethernet.TYPE_IPV4, and org.onlab.packet.Ip4Address.valueOf().
void org.onosproject.sdnip.SdnIpFibTest.testFibDelete ()
Tests deleting a FIB entry.
We verify that the synchronizer records the correct state and that the correct intent is withdrawn from the IntentService.
Definition at line 370 of file SdnIpFibTest.java.
References org.onosproject.sdnip.SdnIpFib.CONSTRAINTS, onosUploadBits.prefix, org.onosproject.sdnip.SdnIpFibTest.testFibAdd(), and org.onlab.packet.Ethernet.TYPE_IPV4.
void org.onosproject.sdnip.SdnIpFibTest.testFibUpdate ()
Tests updating a FIB entry.
We verify that the synchronizer records the correct state and that the correct intent is submitted to the IntentService.
Definition at line 310 of file SdnIpFibTest.java.
References org.onosproject.sdnip.SdnIpFib.CONSTRAINTS, onosUploadBits.prefix, org.onosproject.sdnip.SdnIpFibTest.testFibAdd(), org.onlab.packet.Ethernet.TYPE_IPV4, and org.onlab.packet.Ip4Address.valueOf().
The documentation for this class was generated from the following file:
apps/sdnip/src/test/java/org/onosproject/sdnip/SdnIpFibTest.java