onos: org.onosproject.net.DefaultPortTest Class Reference
org.onosproject.net.DefaultPortTest Class Reference
Test of the default port model entity.
Public Member Functions
void testEquality ()
void basics ()
Detailed Description
Test of the default port model entity.
Definition at line 33 of file DefaultPortTest.java.
Member Function Documentation
void org.onosproject.net.DefaultPortTest.basics ()
Definition at line 59 of file DefaultPortTest.java.
References create-flow.device, org.onosproject.net.Port.element(), org.onosproject.net.Port.isEnabled(), org.onosproject.net.Port.number(), obeliskHostCheck.port, org.onosproject.net.Port.portSpeed(), and org.onosproject.net.Port.type().
void org.onosproject.net.DefaultPortTest.testEquality ()
Definition at line 43 of file DefaultPortTest.java.
References create-flow.device.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/net/DefaultPortTest.java