onos: org.onosproject.pcep.controller.PccId Class Reference
org.onosproject.pcep.controller.PccId Class Reference
The class representing a network client pc ip.
Public Member Functions
IpAddress ipAddress ()
Returns the ip address.
String toString ()
Convert the PccId value to a ':' separated hexadecimal string.
boolean equals (Object other)
int hashCode ()
Static Public Member Functions
static PccId pccId (IpAddress ipAddress)
Create a PccId from ip address.
static PccId pccid (URI uri)
Returns PccId created from the given client URI.
static URI uri (PccId pccid)
Produces client URI from the given DPID.
static URI uri (IpAddress ipAddress)
Produces client URI from the given ip address.
Detailed Description
The class representing a network client pc ip.
This class is immutable.
Definition at line 29 of file PccId.java.
Member Function Documentation
boolean org.onosproject.pcep.controller.PccId.equals (Object other)
Definition at line 72 of file PccId.java.
References org.onosproject.pcep.controller.PccId.ipAddress().
int org.onosproject.pcep.controller.PccId.hashCode ()
Definition at line 82 of file PccId.java.
References org.onosproject.pcep.controller.PccId.ipAddress().
IpAddress org.onosproject.pcep.controller.PccId.ipAddress ()
Returns the ip address.
Returns
ipAddress
Definition at line 57 of file PccId.java.
Referenced by org.onosproject.pcep.controller.PccId.equals(), and org.onosproject.pcep.controller.PccId.hashCode().
static PccId org.onosproject.pcep.controller.PccId.pccId (IpAddress ipAddress) static
Create a PccId from ip address.
Parameters
ipAddress IP address
Returns
ipAddress
Definition at line 48 of file PccId.java.
static PccId org.onosproject.pcep.controller.PccId.pccid (URI uri) static
Returns PccId created from the given client URI.
Parameters
uri device URI
Returns
pccid
Definition at line 92 of file PccId.java.
References org.onlab.packet.IpAddress.valueOf().
String org.onosproject.pcep.controller.PccId.toString ()
Convert the PccId value to a ':' separated hexadecimal string.
Returns
the PccId value as a ':' separated hexadecimal string.
Definition at line 67 of file PccId.java.
static URI org.onosproject.pcep.controller.PccId.uri (PccId pccid) static
Produces client URI from the given DPID.
Parameters
pccid client pccid
Returns
client URI
Definition at line 103 of file PccId.java.
static URI org.onosproject.pcep.controller.PccId.uri (IpAddress ipAddress) static
Produces client URI from the given ip address.
Parameters
ipAddress ip of client
Returns
client URI
Definition at line 113 of file PccId.java.
References org.onlab.packet.IpAddress.toString().
The documentation for this class was generated from the following file:
protocols/pcep/api/src/main/java/org/onosproject/pcep/controller/PccId.java