onos: org.onlab.packet.pim.PIMAddrGroup Class Reference
org.onlab.packet.pim.PIMAddrGroup Class Reference
Public Member Functions
PIMAddrGroup ()
PIM Encoded Group Address.
PIMAddrGroup (String addr)
PIM Encoded Source Address.
PIMAddrGroup (IpPrefix gpfx)
PIM Encoded Group Address.
void setAddr (String addr)
PIM encoded source address.
void setAddr (IpPrefix pfx)
Set the encoded source address.
int getFamily ()
Get the IP family of this address: 4 or 6.
IpAddress getAddr ()
Get the address of this encoded address.
int getMasklen ()
Get the masklen of the group address.
boolean getZBit ()
Return the z bit for admin scoping.
boolean getBBit ()
Return the bBit.
int getByteSize ()
The size in bytes of a serialized address.
byte[] serialize ()
Serialize this group address.
PIMAddrGroup deserialize (ByteBuffer bb) throws DeserializationException
Deserialze from a ByteBuffer.
int hashCode ()
boolean equals (final Object obj)
Static Public Attributes
static final int ENC_GROUP_IPV4_BYTE_LENGTH = 4 + Ip4Address.BYTE_LENGTH
static final int ENC_GROUP_IPV6_BYTE_LENGTH = 4 + Ip6Address.BYTE_LENGTH
Detailed Description
Definition at line 30 of file PIMAddrGroup.java.
Constructor & Destructor Documentation
org.onlab.packet.pim.PIMAddrGroup.PIMAddrGroup ()
PIM Encoded Group Address.
Definition at line 45 of file PIMAddrGroup.java.
References org.onlab.packet.PIM.ADDRESS_FAMILY_IP4.
Referenced by org.onlab.packet.pim.PIMAddrGroup.equals().
org.onlab.packet.pim.PIMAddrGroup.PIMAddrGroup (String addr)
PIM Encoded Source Address.
Parameters
addr IPv4 or IPv6
Definition at line 58 of file PIMAddrGroup.java.
org.onlab.packet.pim.PIMAddrGroup.PIMAddrGroup (IpPrefix gpfx)
PIM Encoded Group Address.
Parameters
gpfx PIM encoded group address.
Definition at line 67 of file PIMAddrGroup.java.
Member Function Documentation
PIMAddrGroup org.onlab.packet.pim.PIMAddrGroup.deserialize (ByteBuffer bb) throws DeserializationException
Deserialze from a ByteBuffer.
Parameters
bb the ByteBuffer
Returns
an encoded PIM group address
Exceptions
DeserializationException if unable to deserialize the packet data
Definition at line 176 of file PIMAddrGroup.java.
References org.onlab.packet.PIM.ADDRESS_FAMILY_IP4, org.onlab.packet.PIM.ADDRESS_FAMILY_IP6, org.onlab.packet.pim.PIMAddrGroup.ENC_GROUP_IPV4_BYTE_LENGTH, and org.onlab.packet.pim.PIMAddrGroup.ENC_GROUP_IPV6_BYTE_LENGTH.
boolean org.onlab.packet.pim.PIMAddrGroup.equals (final Object obj)
Definition at line 238 of file PIMAddrGroup.java.
References org.onlab.packet.IpAddress.equals(), and org.onlab.packet.pim.PIMAddrGroup.PIMAddrGroup().
IpAddress org.onlab.packet.pim.PIMAddrGroup.getAddr ()
Get the address of this encoded address.
Returns
source address
Definition at line 105 of file PIMAddrGroup.java.
boolean org.onlab.packet.pim.PIMAddrGroup.getBBit ()
Return the bBit.
Used to indicate this is a bidir
Returns
return true or false.
Definition at line 132 of file PIMAddrGroup.java.
int org.onlab.packet.pim.PIMAddrGroup.getByteSize ()
The size in bytes of a serialized address.
Returns
the number of bytes when serialized
Definition at line 141 of file PIMAddrGroup.java.
References onos.size.
Referenced by org.onlab.packet.pim.PIMAddrGroup.serialize().
int org.onlab.packet.pim.PIMAddrGroup.getFamily ()
Get the IP family of this address: 4 or 6.
Returns
the IP address family
Definition at line 96 of file PIMAddrGroup.java.
int org.onlab.packet.pim.PIMAddrGroup.getMasklen ()
Get the masklen of the group address.
Returns
the masklen
Definition at line 114 of file PIMAddrGroup.java.
boolean org.onlab.packet.pim.PIMAddrGroup.getZBit ()
Return the z bit for admin scoping.
Only used for the Bootstrap router.
Returns
true or false
Definition at line 123 of file PIMAddrGroup.java.
int org.onlab.packet.pim.PIMAddrGroup.hashCode ()
Definition at line 220 of file PIMAddrGroup.java.
byte [] org.onlab.packet.pim.PIMAddrGroup.serialize ()
Serialize this group address.
Returns
the serialized address in a buffer
Definition at line 152 of file PIMAddrGroup.java.
References org.onlab.packet.pim.PIMAddrGroup.getByteSize().
void org.onlab.packet.pim.PIMAddrGroup.setAddr (String addr)
PIM encoded source address.
Parameters
addr IPv4 or IPv6
Definition at line 76 of file PIMAddrGroup.java.
References org.onlab.packet.IpPrefix.valueOf().
void org.onlab.packet.pim.PIMAddrGroup.setAddr (IpPrefix pfx)
Set the encoded source address.
Parameters
pfx address prefix
Definition at line 85 of file PIMAddrGroup.java.
References org.onlab.packet.PIM.ADDRESS_FAMILY_IP4, org.onlab.packet.PIM.ADDRESS_FAMILY_IP6, and org.onlab.packet.IpAddress.isIp4().
Member Data Documentation
final int org.onlab.packet.pim.PIMAddrGroup.ENC_GROUP_IPV4_BYTE_LENGTH = 4 + Ip4Address.BYTE_LENGTH static
Definition at line 39 of file PIMAddrGroup.java.
Referenced by org.onlab.packet.pim.PIMAddrGroup.deserialize().
final int org.onlab.packet.pim.PIMAddrGroup.ENC_GROUP_IPV6_BYTE_LENGTH = 4 + Ip6Address.BYTE_LENGTH static
Definition at line 40 of file PIMAddrGroup.java.
Referenced by org.onlab.packet.pim.PIMAddrGroup.deserialize().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/pim/PIMAddrGroup.java