onos: org.onosproject.net.topology.DefaultTopologyEdge Class Reference
org.onosproject.net.topology.DefaultTopologyEdge Class Reference
Implementation of the topology edge backed by a link.
Public Member Functions
DefaultTopologyEdge (TopologyVertex src, TopologyVertex dst, Link link)
Creates a new topology edge.
Link link ()
Returns the associated infrastructure link.
TopologyVertex src ()
TopologyVertex dst ()
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Implementation of the topology edge backed by a link.
Definition at line 28 of file DefaultTopologyEdge.java.
Constructor & Destructor Documentation
org.onosproject.net.topology.DefaultTopologyEdge.DefaultTopologyEdge (TopologyVertex src, TopologyVertex dst, Link link)
Creates a new topology edge.
Parameters
src source vertex
dst destination vertex
link infrastructure link
Definition at line 41 of file DefaultTopologyEdge.java.
References org.onosproject.net.topology.DefaultTopologyEdge.dst(), and org.onosproject.net.topology.DefaultTopologyEdge.src().
Referenced by org.onosproject.net.topology.DefaultTopologyEdge.equals().
Member Function Documentation
TopologyVertex org.onosproject.net.topology.DefaultTopologyEdge.dst ()
Definition at line 58 of file DefaultTopologyEdge.java.
Referenced by org.onosproject.net.topology.DefaultTopologyEdge.DefaultTopologyEdge(), and org.onosproject.net.topology.DefaultTopologyEdge.toString().
boolean org.onosproject.net.topology.DefaultTopologyEdge.equals (Object obj)
Definition at line 68 of file DefaultTopologyEdge.java.
References org.onosproject.net.topology.DefaultTopologyEdge.DefaultTopologyEdge().
int org.onosproject.net.topology.DefaultTopologyEdge.hashCode ()
Definition at line 63 of file DefaultTopologyEdge.java.
Link org.onosproject.net.topology.DefaultTopologyEdge.link ()
Returns the associated infrastructure link.
Returns
backing infrastructure link
Implements org.onosproject.net.topology.TopologyEdge.
Definition at line 48 of file DefaultTopologyEdge.java.
TopologyVertex org.onosproject.net.topology.DefaultTopologyEdge.src ()
Definition at line 53 of file DefaultTopologyEdge.java.
Referenced by org.onosproject.net.topology.DefaultTopologyEdge.DefaultTopologyEdge(), and org.onosproject.net.topology.DefaultTopologyEdge.toString().
String org.onosproject.net.topology.DefaultTopologyEdge.toString ()
Definition at line 80 of file DefaultTopologyEdge.java.
References org.onosproject.net.topology.DefaultTopologyEdge.dst(), and org.onosproject.net.topology.DefaultTopologyEdge.src().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/topology/DefaultTopologyEdge.java