onos: org.onosproject.net.intent.ConnectivityIntent Class Reference
org.onosproject.net.intent.ConnectivityIntent Class Reference
Abstraction of connectivity intent for traffic matching some criteria.
Classes
class Builder
Abstract builder for connectivity intents.
Public Member Functions
TrafficSelector selector ()
Returns the match specifying the type of traffic.
TrafficTreatment treatment ()
Returns the action applied to the traffic.
List< Constraint > constraints ()
Returns the set of connectivity constraints.
Public Member Functions inherited from org.onosproject.net.intent.Intent
IntentId id ()
Returns the intent identifier.
ApplicationId appId ()
Returns the identifier of the application that requested the intent.
int priority ()
Returns the priority of the intent.
Collection< NetworkResource > resources ()
Returns the collection of resources required for this intent.
boolean isInstallable ()
Indicates whether or not the intent is installable.
final int hashCode ()
final boolean equals (Object obj)
Key key ()
Protected Member Functions
ConnectivityIntent (ApplicationId appId, Key key, Collection< NetworkResource > resources, TrafficSelector selector, TrafficTreatment treatment, List< Constraint > constraints, int priority)
Creates a connectivity intent that matches on the specified selector and applies the specified treatment.
ConnectivityIntent ()
Constructor for serializer.
Protected Member Functions inherited from org.onosproject.net.intent.Intent
Intent ()
Constructor for serializer.
Intent (ApplicationId appId, Key key, Collection< NetworkResource > resources, int priority)
Creates a new intent.
Static Protected Member Functions
static Collection
< NetworkResource > resources (Collection< Link > links)
Produces a collection of network resources from the given links.
Additional Inherited Members
Static Public Member Functions inherited from org.onosproject.net.intent.Intent
static void bindIdGenerator (IdGenerator newIdGenerator)
Binds an id generator for unique intent id generation.
static void unbindIdGenerator (IdGenerator oldIdGenerator)
Unbinds an id generator.
Static Public Attributes inherited from org.onosproject.net.intent.Intent
static final int DEFAULT_INTENT_PRIORITY = 100
static final int MAX_PRIORITY = (1 << 16) - 1
static final int MIN_PRIORITY = 1
Detailed Description
Abstraction of connectivity intent for traffic matching some criteria.
Definition at line 39 of file ConnectivityIntent.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.ConnectivityIntent.ConnectivityIntent (ApplicationId appId, Key key, Collection< NetworkResource > resources, TrafficSelector selector, TrafficTreatment treatment, List< Constraint > constraints, int priority) protected
Creates a connectivity intent that matches on the specified selector and applies the specified treatment.
Path will be optimized based on the first constraint if one is given.
Parameters
appId application identifier
key explicit key to use for intent
resources required network resources (optional)
selector traffic selector
treatment treatment
constraints optional prioritized list of constraints
priority priority to use for flows generated by this intent
Exceptions
NullPointerException if the selector or treatment is null
Definition at line 68 of file ConnectivityIntent.java.
org.onosproject.net.intent.ConnectivityIntent.ConnectivityIntent () protected
Constructor for serializer.
Definition at line 84 of file ConnectivityIntent.java.
Member Function Documentation
List<Constraint> org.onosproject.net.intent.ConnectivityIntent.constraints ()
Returns the set of connectivity constraints.
Returns
list of intent constraints
Definition at line 173 of file ConnectivityIntent.java.
Referenced by org.onosproject.net.intent.impl.compiler.TwoWayP2PIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.compile(), org.onosproject.codec.impl.IntentCodecTest.decodeHostToHostIntent(), org.onosproject.codec.impl.IntentCodecTest.decodePointToPointIntent(), org.onosproject.net.intent.TwoWayP2PIntent.toString(), org.onosproject.net.intent.PathIntent.toString(), org.onosproject.net.intent.HostToHostIntent.toString(), org.onosproject.net.intent.PointToPointIntent.toString(), org.onosproject.net.intent.SinglePointToMultiPointIntent.toString(), org.onosproject.net.intent.MultiPointToSinglePointIntent.toString(), and org.onosproject.net.intent.MplsIntent.toString().
static Collection<NetworkResource> org.onosproject.net.intent.ConnectivityIntent.resources (Collection< Link > links) static protected
Produces a collection of network resources from the given links.
Parameters
links collection of links
Returns
collection of link resources
Definition at line 183 of file ConnectivityIntent.java.
Referenced by org.onosproject.net.intent.impl.compiler.PathIntentCompiler.compile(), and org.onosproject.net.intent.impl.compiler.LinkCollectionIntentCompiler.compile().
TrafficSelector org.onosproject.net.intent.ConnectivityIntent.selector ()
Returns the match specifying the type of traffic.
Returns
traffic match
Definition at line 155 of file ConnectivityIntent.java.
Referenced by org.onosproject.net.intent.MultiPointToSinglePointIntentTest.basics(), org.onosproject.net.intent.SinglePointToMultiPointIntentTest.basics(), org.onosproject.net.intent.PointToPointIntentTest.basics(), org.onosproject.net.intent.PathIntentTest.basics(), org.onosproject.net.intent.impl.compiler.TwoWayP2PIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.PathIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.compile(), org.onosproject.codec.impl.IntentCodecTest.decodePointToPointIntent(), org.onosproject.sdnip.IntentUtils.equals(), org.onosproject.net.intent.TwoWayP2PIntentTest.testContents(), org.onosproject.net.intent.MplsPathIntentTest.testContents(), org.onosproject.net.intent.MplsIntentTest.testContents(), org.onosproject.net.intent.LinkCollectionIntentTest.testSerializerConstructor(), org.onosproject.net.intent.TwoWayP2PIntent.toString(), org.onosproject.net.intent.PathIntent.toString(), org.onosproject.net.intent.HostToHostIntent.toString(), org.onosproject.net.intent.PointToPointIntent.toString(), org.onosproject.net.intent.SinglePointToMultiPointIntent.toString(), org.onosproject.net.intent.MultiPointToSinglePointIntent.toString(), org.onosproject.net.intent.LinkCollectionIntent.toString(), and org.onosproject.net.intent.MplsIntent.toString().
TrafficTreatment org.onosproject.net.intent.ConnectivityIntent.treatment ()
Returns the action applied to the traffic.
Returns
applied action
Definition at line 164 of file ConnectivityIntent.java.
Referenced by org.onosproject.net.intent.PathIntentTest.basics(), org.onosproject.net.intent.impl.compiler.TwoWayP2PIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.SinglePointToMultiPointIntentCompiler.compile(), org.onosproject.net.intent.impl.compiler.MultiPointToSinglePointIntentCompiler.compile(), org.onosproject.codec.impl.IntentCodecTest.decodePointToPointIntent(), org.onosproject.sdnip.IntentUtils.equals(), org.onosproject.net.intent.TwoWayP2PIntentTest.testContents(), org.onosproject.net.intent.MplsPathIntentTest.testContents(), org.onosproject.net.intent.MplsIntentTest.testContents(), org.onosproject.net.intent.LinkCollectionIntentTest.testSerializerConstructor(), org.onosproject.net.intent.TwoWayP2PIntent.toString(), org.onosproject.net.intent.PathIntent.toString(), org.onosproject.net.intent.HostToHostIntent.toString(), org.onosproject.net.intent.PointToPointIntent.toString(), org.onosproject.net.intent.SinglePointToMultiPointIntent.toString(), org.onosproject.net.intent.MultiPointToSinglePointIntent.toString(), org.onosproject.net.intent.LinkCollectionIntent.toString(), and org.onosproject.net.intent.MplsIntent.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/ConnectivityIntent.java