onos: org.onosproject.bgpio.types.BgpHeader Class Reference
org.onosproject.bgpio.types.BgpHeader Class Reference
Provides BGP Message Header which is common for all the Messages.
Public Member Functions
BgpHeader ()
Reset fields.
BgpHeader (byte[] marker, short length, byte type)
Constructors to initialize parameters.
void setMarker (byte[] value)
Sets marker field.
void setType (byte value)
Sets message type.
void setLength (short value)
Sets message length.
short getLength ()
Returns message length.
byte[] getMarker ()
Returns message marker.
byte getType ()
Returns message type.
int write (ChannelBuffer cb)
Writes Byte stream of BGP header to channel buffer.
Static Public Member Functions
static BgpHeader read (ChannelBuffer cb)
Read from channel buffer and Returns BGP header.
Static Public Attributes
static final int MARKER_LENGTH = 16
static final short DEFAULT_HEADER_LENGTH = 19
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(BgpHeader.class)
Detailed Description
Provides BGP Message Header which is common for all the Messages.
Definition at line 26 of file BgpHeader.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.BgpHeader.BgpHeader ()
Reset fields.
Definition at line 55 of file BgpHeader.java.
Referenced by org.onosproject.bgpio.types.BgpHeader.read().
org.onosproject.bgpio.types.BgpHeader.BgpHeader (byte[] marker, short length, byte type)
Constructors to initialize parameters.
Parameters
marker field in BGP header
length message length
type message type
Definition at line 68 of file BgpHeader.java.
Member Function Documentation
short org.onosproject.bgpio.types.BgpHeader.getLength ()
Returns message length.
Returns
message length
Definition at line 106 of file BgpHeader.java.
References find-link-in-cluster.length.
byte [] org.onosproject.bgpio.types.BgpHeader.getMarker ()
Returns message marker.
Returns
message marker
Definition at line 115 of file BgpHeader.java.
Referenced by org.onosproject.bgpio.types.BgpHeader.write().
byte org.onosproject.bgpio.types.BgpHeader.getType ()
Returns message type.
Returns
message type
Definition at line 124 of file BgpHeader.java.
static BgpHeader org.onosproject.bgpio.types.BgpHeader.read (ChannelBuffer cb) static
Read from channel buffer and Returns BGP header.
Parameters
cb ChannelBuffer
Returns
object of BGPHeader
Definition at line 151 of file BgpHeader.java.
References org.onosproject.bgpio.types.BgpHeader.BgpHeader(), and org.onosproject.bgpio.types.BgpHeader.MARKER_LENGTH.
void org.onosproject.bgpio.types.BgpHeader.setLength (short value)
Sets message length.
Parameters
value message length
Definition at line 97 of file BgpHeader.java.
void org.onosproject.bgpio.types.BgpHeader.setMarker (byte[] value)
Sets marker field.
Parameters
value marker field
Definition at line 79 of file BgpHeader.java.
void org.onosproject.bgpio.types.BgpHeader.setType (byte value)
Sets message type.
Parameters
value message type
Definition at line 88 of file BgpHeader.java.
int org.onosproject.bgpio.types.BgpHeader.write (ChannelBuffer cb)
Writes Byte stream of BGP header to channel buffer.
Parameters
cb ChannelBuffer
Returns
length index of message header
Definition at line 134 of file BgpHeader.java.
References org.onosproject.bgpio.types.BgpHeader.getMarker(), and org.onosproject.bgpio.types.BgpHeader.MARKER_LENGTH.
Member Data Documentation
final short org.onosproject.bgpio.types.BgpHeader.DEFAULT_HEADER_LENGTH = 19 static
Definition at line 46 of file BgpHeader.java.
final Logger org.onosproject.bgpio.types.BgpHeader.log = LoggerFactory.getLogger(BgpHeader.class) static protected
Definition at line 43 of file BgpHeader.java.
final int org.onosproject.bgpio.types.BgpHeader.MARKER_LENGTH = 16 static
Definition at line 45 of file BgpHeader.java.
Referenced by org.onosproject.bgpio.types.BgpHeader.read(), and org.onosproject.bgpio.types.BgpHeader.write().
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/BgpHeader.java