onos: org.onosproject.net.host.impl.HostManager Class Reference
org.onosproject.net.host.impl.HostManager Class Reference
Provides basic implementation of the host SB & NB APIs.
Public Member Functions
void activate ()
void deactivate ()
int getHostCount ()
Returns the number of end-station hosts known to the system.
Iterable< Host > getHosts ()
Returns a collection of all end-station hosts.
Host getHost (HostId hostId)
Returns the host with the specified identifier.
Set< Host > getHostsByVlan (VlanId vlanId)
Returns the set of hosts that belong to the specified VLAN.
Set< Host > getHostsByMac (MacAddress mac)
Returns the set of hosts that have the specified MAC address.
Set< Host > getHostsByIp (IpAddress ip)
Returns the set of hosts that have the specified IP address.
Set< Host > getConnectedHosts (ConnectPoint connectPoint)
Returns the set of hosts whose most recent location is the specified connection point.
Set< Host > getConnectedHosts (DeviceId deviceId)
Returns the set of hosts whose most recent location is the specified infrastructure device.
void startMonitoringIp (IpAddress ip)
Requests the host service to monitor hosts with the given IP address and notify listeners of changes.
void stopMonitoringIp (IpAddress ip)
Stops the host service from monitoring an IP address.
void requestMac (IpAddress ip)
Requests the host service to resolve the MAC address for the given IP address.
void removeHost (HostId hostId)
Removes the end-station host with the specified identifier.
Static Public Attributes
static final String HOST_ID_NULL = "Host ID cannot be null"
Protected Member Functions
HostProviderService createProviderService (HostProvider provider)
Protected Attributes
HostStore store
DeviceService deviceService
PacketService packetService
NetworkConfigService networkConfigService
InterfaceService interfaceService
EdgePortService edgePortService
Detailed Description
Provides basic implementation of the host SB & NB APIs.
Definition at line 66 of file HostManager.java.
Member Function Documentation
void org.onosproject.net.host.impl.HostManager.activate ()
Definition at line 99 of file HostManager.java.
HostProviderService org.onosproject.net.host.impl.HostManager.createProviderService (HostProvider provider) protected
Definition at line 117 of file HostManager.java.
void org.onosproject.net.host.impl.HostManager.deactivate ()
Definition at line 109 of file HostManager.java.
Set<Host> org.onosproject.net.host.impl.HostManager.getConnectedHosts (ConnectPoint connectPoint)
Returns the set of hosts whose most recent location is the specified connection point.
Parameters
connectPoint connection point
Returns
set of hosts connected to the connection point
Implements org.onosproject.net.host.HostService.
Definition at line 162 of file HostManager.java.
Referenced by org.onosproject.net.host.impl.HostManagerTest.getHosts(), and org.onosproject.net.host.impl.HostManagerTest.getHostsIPv6().
Set<Host> org.onosproject.net.host.impl.HostManager.getConnectedHosts (DeviceId deviceId)
Returns the set of hosts whose most recent location is the specified infrastructure device.
Parameters
deviceId device identifier
Returns
set of hosts connected to the device
Implements org.onosproject.net.host.HostService.
Definition at line 169 of file HostManager.java.
References find-flow.deviceId.
Host org.onosproject.net.host.impl.HostManager.getHost (HostId hostId)
Returns the host with the specified identifier.
Parameters
hostId host identifier
Returns
host or null if one with the given identifier is not known
Implements org.onosproject.net.host.HostService.
Definition at line 135 of file HostManager.java.
References org.onosproject.net.host.impl.HostManager.HOST_ID_NULL.
Referenced by org.onosproject.net.host.impl.HostManagerTest.hostDetected(), org.onosproject.net.host.impl.HostManagerTest.hostDetectedIPv6(), org.onosproject.net.host.impl.HostManagerTest.hostVanished(), and org.onosproject.net.host.impl.HostManagerTest.hostVanishedIPv6().
int org.onosproject.net.host.impl.HostManager.getHostCount ()
Returns the number of end-station hosts known to the system.
Returns
number of end-station hosts
Implements org.onosproject.net.host.HostService.
Definition at line 123 of file HostManager.java.
Referenced by org.onosproject.net.host.impl.HostManagerTest.hostDetected(), and org.onosproject.net.host.impl.HostManagerTest.hostDetectedIPv6().
Iterable<Host> org.onosproject.net.host.impl.HostManager.getHosts ()
Returns a collection of all end-station hosts.
Returns
collection of hosts
Implements org.onosproject.net.host.HostService.
Definition at line 129 of file HostManager.java.
Referenced by org.onosproject.net.host.impl.HostManagerTest.getHosts(), and org.onosproject.net.host.impl.HostManagerTest.getHostsIPv6().
Set<Host> org.onosproject.net.host.impl.HostManager.getHostsByIp (IpAddress ip)
Returns the set of hosts that have the specified IP address.
Parameters
ip ip address
Returns
set of hosts with the given IP
Implements org.onosproject.net.host.HostService.
Definition at line 155 of file HostManager.java.
Referenced by org.onosproject.net.host.impl.HostManagerTest.getHosts(), org.onosproject.net.host.impl.HostManagerTest.getHostsIPv6(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExist(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExistWithVlan(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostExists(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExist(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExistWithVlan(), and org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostExists().
Set<Host> org.onosproject.net.host.impl.HostManager.getHostsByMac (MacAddress mac)
Returns the set of hosts that have the specified MAC address.
Parameters
mac mac address
Returns
set of hosts with the given mac
Implements org.onosproject.net.host.HostService.
Definition at line 148 of file HostManager.java.
References obeliskHostCheck.mac.
Referenced by org.onosproject.net.host.impl.HostManagerTest.getHosts(), and org.onosproject.net.host.impl.HostManagerTest.getHostsIPv6().
Set<Host> org.onosproject.net.host.impl.HostManager.getHostsByVlan (VlanId vlanId)
Returns the set of hosts that belong to the specified VLAN.
Parameters
vlanId vlan identifier
Returns
set of hosts in the given vlan id
Implements org.onosproject.net.host.HostService.
Definition at line 142 of file HostManager.java.
Referenced by org.onosproject.net.host.impl.HostManagerTest.getHosts(), and org.onosproject.net.host.impl.HostManagerTest.getHostsIPv6().
void org.onosproject.net.host.impl.HostManager.removeHost (HostId hostId)
Removes the end-station host with the specified identifier.
Parameters
hostId host identifier
Implements org.onosproject.net.host.HostAdminService.
Definition at line 193 of file HostManager.java.
References org.onosproject.net.host.impl.HostManager.HOST_ID_NULL.
void org.onosproject.net.host.impl.HostManager.requestMac (IpAddress ip)
Requests the host service to resolve the MAC address for the given IP address.
This will trigger a notification to the host listeners if the MAC address is found.
Parameters
ip IP address to find the MAC address for
Implements org.onosproject.net.host.HostService.
Definition at line 188 of file HostManager.java.
void org.onosproject.net.host.impl.HostManager.startMonitoringIp (IpAddress ip)
Requests the host service to monitor hosts with the given IP address and notify listeners of changes.
Parameters
ip IP address of the host to monitor
Implements org.onosproject.net.host.HostService.
Definition at line 176 of file HostManager.java.
void org.onosproject.net.host.impl.HostManager.stopMonitoringIp (IpAddress ip)
Stops the host service from monitoring an IP address.
Parameters
ip IP address to stop monitoring
Implements org.onosproject.net.host.HostService.
Definition at line 182 of file HostManager.java.
Member Data Documentation
DeviceService org.onosproject.net.host.impl.HostManager.deviceService protected
Definition at line 82 of file HostManager.java.
EdgePortService org.onosproject.net.host.impl.HostManager.edgePortService protected
Definition at line 94 of file HostManager.java.
final String org.onosproject.net.host.impl.HostManager.HOST_ID_NULL = "Host ID cannot be null" static
Definition at line 72 of file HostManager.java.
Referenced by org.onosproject.net.host.impl.HostManager.getHost(), and org.onosproject.net.host.impl.HostManager.removeHost().
InterfaceService org.onosproject.net.host.impl.HostManager.interfaceService protected
Definition at line 91 of file HostManager.java.
NetworkConfigService org.onosproject.net.host.impl.HostManager.networkConfigService protected
Definition at line 88 of file HostManager.java.
PacketService org.onosproject.net.host.impl.HostManager.packetService protected
Definition at line 85 of file HostManager.java.
HostStore org.onosproject.net.host.impl.HostManager.store protected
Definition at line 79 of file HostManager.java.
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/host/impl/HostManager.java