onos: org.onosproject.bgp.controller.impl.BgpConfig Class Reference
org.onosproject.bgp.controller.impl.BgpConfig Class Reference
Provides BGP configuration of this BGP speaker.
Public Member Functions
BgpConfig ()
Constructor to initialize the values.
State getState ()
Returns the status of the configuration based on this state certain operations like connection is handled.
void setState (State state)
int getAsNumber ()
Get the AS number to which this BGP speaker belongs.
void setAsNumber (int localAs)
Set the AS number to which this BGP speaker belongs.
int getMaxSession ()
Returns the maximum number of session supported.
void setMaxSession (int maxSession)
Set the maximum number of sessions to support.
boolean getLsCapability ()
Get the status of the link state support for this BGP speaker.
void setLsCapability (boolean lsCapability)
Set the link state support to this BGP speaker.
String getRouterId ()
Returns the Router ID of this BGP speaker.
void setRouterId (String routerId)
Set the Router ID of this BGP speaker.
boolean addPeer (String routerid, int remoteAs)
Add the BGP peer IP address and the AS number to which it belongs.
boolean addPeer (String routerid, short holdTime)
Add the BGP peer IP address and the keep alive time.
boolean addPeer (String routerid, int remoteAs, short holdTime)
Add the BGP peer IP address, the AS number to which it belongs and keep alive time.
boolean connectPeer (String routerid)
Connect to BGP peer with this IP address.
boolean removePeer (String routerid)
Remove the BGP peer with this IP address.
boolean disconnectPeer (String routerid)
Disconnect this BGP peer with this IP address.
void setPeerConnState (String routerid, BgpPeerCfg.State state)
BgpPeerCfg.State getPeerConnState (String routerid)
Get the current peer connection state information.
boolean isPeerConnectable (String routerid)
Check if the peer can be connected or not.
TreeMap< String, BgpPeerCfg > getPeerTree ()
Return the peer tree map.
TreeMap< String, BgpPeerCfg > displayPeers ()
Returns the peer tree information.
BgpPeerCfg displayPeers (String routerid)
Return the BGP Peer information with this matching IP.
void setHoldTime (short holdTime)
Set the keep alive timer for the connection.
short getHoldTime ()
Returns the connection hold timer in seconds.
boolean getLargeASCapability ()
Get the status of the 32 bit AS support for this BGP speaker.
void setLargeASCapability (boolean largeAs)
Set the 32 bit AS support capability to this BGP speaker.
boolean isPeerConfigured (String routerid)
Check if this BGP peer is configured.
boolean isPeerConnected (String routerid)
Check if this BGP speaker is having connection with the peer.
int getMaxConnRetryCount ()
Get the connection retry count number.
void setMaxConnRetryCout (int retryCount)
Set the connection retry count.
int getMaxConnRetryTime ()
Get the connection retry time in seconds.
void setMaxConnRetryTime (int retryTime)
Set the connection retry time in seconds.
Public Member Functions inherited from org.onosproject.bgp.controller.BgpCfg
void setState (State state)
To set the current state of the configuration.
void setPeerConnState (String routerid, BgpPeerCfg.State state)
Set the current connection state information.
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(BgpConfig.class)
Detailed Description
Provides BGP configuration of this BGP speaker.
Definition at line 32 of file BgpConfig.java.
Constructor & Destructor Documentation
org.onosproject.bgp.controller.impl.BgpConfig.BgpConfig ()
Constructor to initialize the values.
Definition at line 55 of file BgpConfig.java.
Member Function Documentation
boolean org.onosproject.bgp.controller.impl.BgpConfig.addPeer (String routerid, int remoteAs)
Add the BGP peer IP address and the AS number to which it belongs.
Parameters
routerid IP address in string format
remoteAs AS number to which it belongs
Returns
true if added successfully else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 134 of file BgpConfig.java.
Referenced by org.onosproject.bgp.controller.impl.BgpConfig.addPeer().
boolean org.onosproject.bgp.controller.impl.BgpConfig.addPeer (String routerid, short holdTime)
Add the BGP peer IP address and the keep alive time.
Parameters
routerid IP address in string format
holdTime keep alive time for the connection
Returns
true if added successfully else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 139 of file BgpConfig.java.
References org.onosproject.bgp.controller.impl.BgpConfig.addPeer(), and org.onosproject.bgp.controller.impl.BgpConfig.getAsNumber().
boolean org.onosproject.bgp.controller.impl.BgpConfig.addPeer (String routerid, int remoteAs, short holdTime)
Add the BGP peer IP address, the AS number to which it belongs and keep alive time.
Parameters
routerid IP address in string format
remoteAs AS number to which it belongs
holdTime keep alive time for the connection
Returns
true if added successfully else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 144 of file BgpConfig.java.
References org.onosproject.bgp.controller.impl.BgpConfig.getAsNumber().
boolean org.onosproject.bgp.controller.impl.BgpConfig.connectPeer (String routerid)
Connect to BGP peer with this IP address.
Parameters
routerid router IP address
Returns
true of the configuration is found and able to connect else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 170 of file BgpConfig.java.
boolean org.onosproject.bgp.controller.impl.BgpConfig.disconnectPeer (String routerid)
Disconnect this BGP peer with this IP address.
Parameters
routerid router IP address in string format
Returns
true if the configuration is found and able to disconnect else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 202 of file BgpConfig.java.
Referenced by org.onosproject.bgp.controller.impl.BgpConfig.removePeer().
TreeMap<String, BgpPeerCfg> org.onosproject.bgp.controller.impl.BgpConfig.displayPeers ()
Returns the peer tree information.
Returns
return the tree map with IP as key and BGPPeerCfg as object
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 262 of file BgpConfig.java.
BgpPeerCfg org.onosproject.bgp.controller.impl.BgpConfig.displayPeers (String routerid)
Return the BGP Peer information with this matching IP.
Parameters
routerid router IP address in string format
Returns
BGPPeerCfg object
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 283 of file BgpConfig.java.
int org.onosproject.bgp.controller.impl.BgpConfig.getAsNumber ()
Get the AS number to which this BGP speaker belongs.
Returns
16 or 32 bit AS number, length is dependent on the capability
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 73 of file BgpConfig.java.
Referenced by org.onosproject.bgp.controller.impl.BgpConfig.addPeer().
short org.onosproject.bgp.controller.impl.BgpConfig.getHoldTime ()
Returns the connection hold timer in seconds.
Returns
connection hold timer in seconds
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 299 of file BgpConfig.java.
boolean org.onosproject.bgp.controller.impl.BgpConfig.getLargeASCapability ()
Get the status of the 32 bit AS support for this BGP speaker.
Returns
true if the 32 bit AS number is supported else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 304 of file BgpConfig.java.
boolean org.onosproject.bgp.controller.impl.BgpConfig.getLsCapability ()
Get the status of the link state support for this BGP speaker.
Returns
true if the link state is supported else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 102 of file BgpConfig.java.
int org.onosproject.bgp.controller.impl.BgpConfig.getMaxConnRetryCount ()
Get the connection retry count number.
Returns
connection retry count if there is a connection error
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 326 of file BgpConfig.java.
int org.onosproject.bgp.controller.impl.BgpConfig.getMaxConnRetryTime ()
Get the connection retry time in seconds.
Returns
connection retry time in seconds
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 336 of file BgpConfig.java.
int org.onosproject.bgp.controller.impl.BgpConfig.getMaxSession ()
Returns the maximum number of session supported.
Returns
maximum number of session supported
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 92 of file BgpConfig.java.
BgpPeerCfg.State org.onosproject.bgp.controller.impl.BgpConfig.getPeerConnState (String routerid)
Get the current peer connection state information.
Parameters
routerid router IP address in string format
Returns
state information
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 235 of file BgpConfig.java.
TreeMap<String, BgpPeerCfg> org.onosproject.bgp.controller.impl.BgpConfig.getPeerTree ()
Return the peer tree map.
Returns
return the tree map with IP as key and BGPPeerCfg as object
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 257 of file BgpConfig.java.
String org.onosproject.bgp.controller.impl.BgpConfig.getRouterId ()
Returns the Router ID of this BGP speaker.
Returns
IP address in string format
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 112 of file BgpConfig.java.
State org.onosproject.bgp.controller.impl.BgpConfig.getState ()
Returns the status of the configuration based on this state certain operations like connection is handled.
Returns
State of the configuration
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 63 of file BgpConfig.java.
Referenced by org.onosproject.bgp.controller.impl.BgpConfig.setAsNumber(), and org.onosproject.bgp.controller.impl.BgpConfig.setRouterId().
boolean org.onosproject.bgp.controller.impl.BgpConfig.isPeerConfigured (String routerid)
Check if this BGP peer is configured.
Parameters
routerid router IP address in string format
Returns
true if configured exists else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 314 of file BgpConfig.java.
boolean org.onosproject.bgp.controller.impl.BgpConfig.isPeerConnectable (String routerid)
Check if the peer can be connected or not.
Parameters
routerid router IP address in string format
Returns
true if the peer can be connected else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 246 of file BgpConfig.java.
boolean org.onosproject.bgp.controller.impl.BgpConfig.isPeerConnected (String routerid)
Check if this BGP speaker is having connection with the peer.
Parameters
routerid router IP address in string format
Returns
true if the connection exists else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 320 of file BgpConfig.java.
boolean org.onosproject.bgp.controller.impl.BgpConfig.removePeer (String routerid)
Remove the BGP peer with this IP address.
Parameters
routerid router IP address
Returns
true if removed successfully else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 183 of file BgpConfig.java.
References org.onosproject.bgp.controller.impl.BgpConfig.disconnectPeer().
void org.onosproject.bgp.controller.impl.BgpConfig.setAsNumber (int localAs)
Set the AS number to which this BGP speaker belongs.
Parameters
localAs 16 or 32 bit AS number, length is dependent on the capability
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 78 of file BgpConfig.java.
References org.onosproject.bgp.controller.impl.BgpConfig.getState(), and org.onosproject.bgp.controller.impl.BgpConfig.setState().
void org.onosproject.bgp.controller.impl.BgpConfig.setHoldTime (short holdTime)
Set the keep alive timer for the connection.
Parameters
holdTime connection hold timer in seconds
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 294 of file BgpConfig.java.
void org.onosproject.bgp.controller.impl.BgpConfig.setLargeASCapability (boolean largeAs)
Set the 32 bit AS support capability to this BGP speaker.
Parameters
largeAs true value if the 32 bit AS is supported else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 309 of file BgpConfig.java.
void org.onosproject.bgp.controller.impl.BgpConfig.setLsCapability (boolean lscapability)
Set the link state support to this BGP speaker.
Parameters
lscapability true value if link state is supported else false
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 107 of file BgpConfig.java.
void org.onosproject.bgp.controller.impl.BgpConfig.setMaxConnRetryCout (int retryCount)
Set the connection retry count.
Parameters
retryCount number of times to try to connect if there is any error
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 331 of file BgpConfig.java.
void org.onosproject.bgp.controller.impl.BgpConfig.setMaxConnRetryTime (int retryTime)
Set the connection retry time in seconds.
Parameters
retryTime connection retry times in seconds
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 341 of file BgpConfig.java.
void org.onosproject.bgp.controller.impl.BgpConfig.setMaxSession (int maxsession)
Set the maximum number of sessions to support.
Parameters
maxsession maximum number of session
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 97 of file BgpConfig.java.
void org.onosproject.bgp.controller.impl.BgpConfig.setPeerConnState (String routerid, BgpPeerCfg.State state)
Definition at line 220 of file BgpConfig.java.
void org.onosproject.bgp.controller.impl.BgpConfig.setRouterId (String routerid)
Set the Router ID of this BGP speaker.
Parameters
routerid IP address in string format
Implements org.onosproject.bgp.controller.BgpCfg.
Definition at line 121 of file BgpConfig.java.
References org.onosproject.bgp.controller.impl.BgpConfig.getState(), and org.onosproject.bgp.controller.impl.BgpConfig.setState().
void org.onosproject.bgp.controller.impl.BgpConfig.setState (State state)
Definition at line 68 of file BgpConfig.java.
Referenced by org.onosproject.bgp.controller.impl.BgpConfig.setAsNumber(), and org.onosproject.bgp.controller.impl.BgpConfig.setRouterId().
Member Data Documentation
final Logger org.onosproject.bgp.controller.impl.BgpConfig.log = LoggerFactory.getLogger(BgpConfig.class) static protected
Definition at line 34 of file BgpConfig.java.
The documentation for this class was generated from the following file:
bgp/ctl/src/main/java/org/onosproject/bgp/controller/impl/BgpConfig.java