onos: org.onosproject.ui.table.TableModelTest Class Reference
org.onosproject.ui.table.TableModelTest Class Reference
Unit tests for TableModel.
Public Member Functions
void guardAgainstNull ()
void guardAgainstEmpty ()
void guardAgainstDuplicateCols ()
void basic ()
void defaultFormatter ()
void formatterBadColumn ()
void altFormatter ()
void emptyRow ()
void rowBadColumn ()
void simpleRow ()
void verifyTestData ()
void tableStringSort ()
void tableNumberSort ()
void sortAndFormat ()
void sortAndFormatTwo ()
void getColumnIds ()
void sortDirAsc ()
void sortDirDesc ()
void sortDirOther ()
void sortDirNull ()
void enumSort ()
Detailed Description
Unit tests for TableModel.
Definition at line 29 of file TableModelTest.java.
Member Function Documentation
void org.onosproject.ui.table.TableModelTest.altFormatter ()
Definition at line 89 of file TableModelTest.java.
void org.onosproject.ui.table.TableModelTest.basic ()
Definition at line 69 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.columnCount(), and org.onosproject.ui.table.TableModel.rowCount().
void org.onosproject.ui.table.TableModelTest.defaultFormatter ()
Definition at line 76 of file TableModelTest.java.
void org.onosproject.ui.table.TableModelTest.emptyRow ()
Definition at line 103 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.rowCount().
void org.onosproject.ui.table.TableModelTest.enumSort ()
Definition at line 318 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.SortDir.ASC, and find-link-in-cluster.length.
void org.onosproject.ui.table.TableModelTest.formatterBadColumn ()
Definition at line 83 of file TableModelTest.java.
void org.onosproject.ui.table.TableModelTest.getColumnIds ()
Definition at line 291 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.getColumnIds().
void org.onosproject.ui.table.TableModelTest.guardAgainstDuplicateCols ()
Definition at line 64 of file TableModelTest.java.
void org.onosproject.ui.table.TableModelTest.guardAgainstEmpty ()
Definition at line 59 of file TableModelTest.java.
void org.onosproject.ui.table.TableModelTest.guardAgainstNull ()
Definition at line 54 of file TableModelTest.java.
void org.onosproject.ui.table.TableModelTest.rowBadColumn ()
Definition at line 110 of file TableModelTest.java.
void org.onosproject.ui.table.TableModelTest.simpleRow ()
Definition at line 116 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.rowCount().
void org.onosproject.ui.table.TableModelTest.sortAndFormat ()
Definition at line 245 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.SortDir.ASC, org.onosproject.ui.table.cell.HexFormatter.INSTANCE, and find-link-in-cluster.length.
void org.onosproject.ui.table.TableModelTest.sortAndFormatTwo ()
Definition at line 275 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.SortDir.ASC, org.onosproject.ui.table.cell.HexFormatter.INSTANCE, and find-link-in-cluster.length.
void org.onosproject.ui.table.TableModelTest.sortDirAsc ()
Definition at line 297 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.SortDir.ASC, and org.onosproject.ui.table.TableModel.sortDir().
void org.onosproject.ui.table.TableModelTest.sortDirDesc ()
Definition at line 302 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.SortDir.DESC, and org.onosproject.ui.table.TableModel.sortDir().
void org.onosproject.ui.table.TableModelTest.sortDirNull ()
Definition at line 312 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.SortDir.ASC, and org.onosproject.ui.table.TableModel.sortDir().
void org.onosproject.ui.table.TableModelTest.sortDirOther ()
Definition at line 307 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.SortDir.ASC, and org.onosproject.ui.table.TableModel.sortDir().
void org.onosproject.ui.table.TableModelTest.tableNumberSort ()
Definition at line 217 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.SortDir.ASC, org.onosproject.ui.table.TableModel.SortDir.DESC, and find-link-in-cluster.length.
void org.onosproject.ui.table.TableModelTest.tableStringSort ()
Definition at line 189 of file TableModelTest.java.
References org.onosproject.ui.table.TableModel.SortDir.ASC, org.onosproject.ui.table.TableModel.SortDir.DESC, and find-link-in-cluster.length.
void org.onosproject.ui.table.TableModelTest.verifyTestData ()
Definition at line 169 of file TableModelTest.java.
References find-link-in-cluster.length.
The documentation for this class was generated from the following file:
core/api/src/test/java/org/onosproject/ui/table/TableModelTest.java