onos: org.onosproject.ovsdb.controller.OvsdbIfaceId Class Reference
org.onosproject.ovsdb.controller.OvsdbIfaceId Class Reference
The class representing an ifaceid.
Public Member Functions
OvsdbIfaceId (String value)
Constructor from a String.
String value ()
Gets the value of ifaceid.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
The class representing an ifaceid.
This class is immutable.
Definition at line 26 of file OvsdbIfaceId.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.controller.OvsdbIfaceId.OvsdbIfaceId (String value)
Constructor from a String.
Parameters
value the ifaceid to use
Definition at line 34 of file OvsdbIfaceId.java.
References org.onosproject.ovsdb.controller.OvsdbIfaceId.value().
Referenced by org.onosproject.ovsdb.controller.OvsdbIfaceId.equals().
Member Function Documentation
boolean org.onosproject.ovsdb.controller.OvsdbIfaceId.equals (Object obj)
Definition at line 54 of file OvsdbIfaceId.java.
References org.onosproject.ovsdb.controller.OvsdbIfaceId.OvsdbIfaceId().
int org.onosproject.ovsdb.controller.OvsdbIfaceId.hashCode ()
Definition at line 49 of file OvsdbIfaceId.java.
String org.onosproject.ovsdb.controller.OvsdbIfaceId.toString ()
Definition at line 66 of file OvsdbIfaceId.java.
References org.onosproject.ovsdb.controller.OvsdbIfaceId.value().
String org.onosproject.ovsdb.controller.OvsdbIfaceId.value ()
Gets the value of ifaceid.
Returns
the value of ifaceid
Definition at line 44 of file OvsdbIfaceId.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbIfaceId.OvsdbIfaceId(), and org.onosproject.ovsdb.controller.OvsdbIfaceId.toString().
The documentation for this class was generated from the following file:
protocols/ovsdb/api/src/main/java/org/onosproject/ovsdb/controller/OvsdbIfaceId.java