onos: org.onosproject.net.intent.constraint.ObstacleConstraint Class Reference
org.onosproject.net.intent.constraint.ObstacleConstraint Class Reference
Constraint that evaluates elements not passed through.
Public Member Functions
ObstacleConstraint (DeviceId...obstacles)
Creates a new constraint that the specified device are not passed through.
Set< DeviceId > obstacles ()
Returns the obstacle device ids.
boolean isValid (Link link, LinkResourceService resourceService)
Returns true if the specified link satisfies the constraint.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.intent.constraint.BooleanConstraint
double cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
boolean validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
Detailed Description
Constraint that evaluates elements not passed through.
Definition at line 33 of file ObstacleConstraint.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.constraint.ObstacleConstraint.ObstacleConstraint (DeviceId... obstacles)
Creates a new constraint that the specified device are not passed through.
Parameters
obstacles devices not to be passed
Definition at line 41 of file ObstacleConstraint.java.
References org.onosproject.net.intent.constraint.ObstacleConstraint.obstacles().
Member Function Documentation
boolean org.onosproject.net.intent.constraint.ObstacleConstraint.equals (Object obj)
Definition at line 73 of file ObstacleConstraint.java.
int org.onosproject.net.intent.constraint.ObstacleConstraint.hashCode ()
Definition at line 68 of file ObstacleConstraint.java.
boolean org.onosproject.net.intent.constraint.ObstacleConstraint.isValid (Link link, LinkResourceService resourceService) virtual
Returns true if the specified link satisfies the constraint.
Parameters
link link to be validated
resourceService resource service for checking available link resources
Returns
true if link is viable
Implements org.onosproject.net.intent.constraint.BooleanConstraint.
Definition at line 60 of file ObstacleConstraint.java.
References find-flow.deviceId, and org.onosproject.net.intent.constraint.ObstacleConstraint.obstacles().
Set<DeviceId> org.onosproject.net.intent.constraint.ObstacleConstraint.obstacles ()
Returns the obstacle device ids.
Returns
Set of obstacle device ids
Definition at line 55 of file ObstacleConstraint.java.
Referenced by org.onosproject.net.intent.constraint.ObstacleConstraint.isValid(), org.onosproject.net.intent.constraint.ObstacleConstraint.ObstacleConstraint(), and org.onosproject.net.intent.constraint.ObstacleConstraint.toString().
String org.onosproject.net.intent.constraint.ObstacleConstraint.toString ()
Definition at line 87 of file ObstacleConstraint.java.
References org.onosproject.net.intent.constraint.ObstacleConstraint.obstacles().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/constraint/ObstacleConstraint.java