onos: org.onosproject.store.service.SetEvent< E > Class Reference
org.onosproject.store.service.SetEvent< E > Class Reference
Representation of a DistributedSet update notification.
Classes
enum Type
SetEvent type.
Public Member Functions
SetEvent (String name, Type type, E entry)
Creates a new event object.
String name ()
Returns the set name.
Type type ()
Returns the type of the event.
E entry ()
Returns the entry this event concerns.
boolean equals (Object o)
int hashCode ()
String toString ()
Detailed Description
Representation of a DistributedSet update notification.
Parameters
<E> set element type
Definition at line 27 of file SetEvent.java.
Constructor & Destructor Documentation
org.onosproject.store.service.SetEvent< E >.SetEvent (String name, Type type, E entry)
Creates a new event object.
Parameters
name set name
type type of the event
entry entry the event concerns
Definition at line 55 of file SetEvent.java.
References create-flow.name.
Member Function Documentation
E org.onosproject.store.service.SetEvent< E >.entry ()
Returns the entry this event concerns.
Returns
the entry
Definition at line 84 of file SetEvent.java.
boolean org.onosproject.store.service.SetEvent< E >.equals (Object o)
Definition at line 89 of file SetEvent.java.
References create-flow.name.
int org.onosproject.store.service.SetEvent< E >.hashCode ()
Definition at line 101 of file SetEvent.java.
References create-flow.name.
String org.onosproject.store.service.SetEvent< E >.name ()
Returns the set name.
Returns
name of set
Definition at line 66 of file SetEvent.java.
References create-flow.name.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.store.service.SetEvent< E >.toString ()
Definition at line 106 of file SetEvent.java.
References create-flow.name.
Type org.onosproject.store.service.SetEvent< E >.type ()
Returns the type of the event.
Returns
type of the event
Definition at line 75 of file SetEvent.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/store/service/SetEvent.java