onos: org.onlab.packet.ipv6.BaseOptions Class Reference
org.onlab.packet.ipv6.BaseOptions Class Reference
Base class for hop-by-hop options and destination options.
Public Member Functions
byte getNextHeader ()
Gets the type of next header.
BaseOptions setNextHeader (final byte nextHeader)
Sets the type of next header.
byte getHeaderExtLength ()
Gets the extension length of this header.
BaseOptions setHeaderExtLength (final byte headerExtLength)
Sets the extension length of this header.
byte[] getOptions ()
Gets the options.
BaseOptions setOptions (final byte[] options)
Sets the options.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer< BaseOptions > deserializer ()
Deserializer function for IPv6 base options.
Static Public Attributes
static final byte FIXED_HEADER_LENGTH = 2
static final byte FIXED_OPTIONS_LENGTH = 6
static final byte LENGTH_UNIT = 8
Protected Member Functions
byte getType ()
Gets the type of this option.
BaseOptions setType (final byte type)
Sets the type of this option.
Protected Attributes
byte nextHeader
byte headerExtLength
byte[] options
byte type
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Base class for hop-by-hop options and destination options.
Definition at line 35 of file BaseOptions.java.
Member Function Documentation
IPacket org.onlab.packet.ipv6.BaseOptions.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 150 of file BaseOptions.java.
References org.onlab.packet.ipv6.BaseOptions.deserializer(), org.onlab.packet.ipv6.BaseOptions.FIXED_OPTIONS_LENGTH, find-link-in-cluster.length, org.onlab.packet.ipv6.BaseOptions.LENGTH_UNIT, and org.onlab.packet.IPv6.PROTOCOL_DESERIALIZER_MAP.
static Deserializer<BaseOptions> org.onlab.packet.ipv6.BaseOptions.deserializer () static
Deserializer function for IPv6 base options.
Returns
deserializer function
Definition at line 230 of file BaseOptions.java.
References org.onlab.packet.ipv6.BaseOptions.FIXED_HEADER_LENGTH, org.onlab.packet.ipv6.BaseOptions.FIXED_OPTIONS_LENGTH, find-link-in-cluster.length, org.onlab.packet.ipv6.BaseOptions.LENGTH_UNIT, org.onlab.packet.ipv6.BaseOptions.nextHeader, and org.onlab.packet.IPv6.PROTOCOL_DESERIALIZER_MAP.
Referenced by org.onlab.packet.ipv6.BaseOptions.deserialize().
boolean org.onlab.packet.ipv6.BaseOptions.equals (final Object obj)
Definition at line 199 of file BaseOptions.java.
References org.onlab.packet.ipv6.BaseOptions.headerExtLength, org.onlab.packet.ipv6.BaseOptions.nextHeader, org.onlab.packet.ipv6.BaseOptions.options, and org.onlab.packet.ipv6.BaseOptions.type.
Referenced by org.onlab.packet.ipv6.BaseOptionsTest.testEqual().
byte org.onlab.packet.ipv6.BaseOptions.getHeaderExtLength ()
Gets the extension length of this header.
Returns
header length
Definition at line 61 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.BaseOptionsTest.testDeserialize().
byte org.onlab.packet.ipv6.BaseOptions.getNextHeader ()
Gets the type of next header.
Returns
next header
Implements org.onlab.packet.ipv6.IExtensionHeader.
Definition at line 46 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.BaseOptionsTest.testDeserialize().
byte [] org.onlab.packet.ipv6.BaseOptions.getOptions ()
Gets the options.
Returns
the options
Definition at line 81 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.BaseOptionsTest.testDeserialize().
byte org.onlab.packet.ipv6.BaseOptions.getType () protected
Gets the type of this option.
Returns
the type
Definition at line 102 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.DestinationOptionsTest.testConstructor(), and org.onlab.packet.ipv6.HopByHopOptionsTest.testConstructor().
int org.onlab.packet.ipv6.BaseOptions.hashCode ()
Definition at line 182 of file BaseOptions.java.
References org.onlab.packet.ipv6.BaseOptions.options.
byte [] org.onlab.packet.ipv6.BaseOptions.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 119 of file BaseOptions.java.
References org.onlab.packet.ipv6.BaseOptions.FIXED_HEADER_LENGTH, find-link-in-cluster.length, org.onlab.packet.BasePacket.parent, and org.onlab.packet.BasePacket.payload.
Referenced by org.onlab.packet.ipv6.BaseOptionsTest.testSerialize().
BaseOptions org.onlab.packet.ipv6.BaseOptions.setHeaderExtLength (final byte headerExtLength)
Sets the extension length of this header.
Parameters
headerExtLength the header length to set
Returns
this
Definition at line 71 of file BaseOptions.java.
References org.onlab.packet.ipv6.BaseOptions.headerExtLength.
BaseOptions org.onlab.packet.ipv6.BaseOptions.setNextHeader (final byte nextHeader)
Sets the type of next header.
Parameters
nextHeader the next header to set
Returns
this
Implements org.onlab.packet.ipv6.IExtensionHeader.
Definition at line 51 of file BaseOptions.java.
References org.onlab.packet.ipv6.BaseOptions.nextHeader.
BaseOptions org.onlab.packet.ipv6.BaseOptions.setOptions (final byte[] options)
Sets the options.
Parameters
options the options to set
Returns
this
Definition at line 91 of file BaseOptions.java.
References find-link-in-cluster.length, and org.onlab.packet.ipv6.BaseOptions.options.
BaseOptions org.onlab.packet.ipv6.BaseOptions.setType (final byte type) protected
Sets the type of this option.
Must be either IPv6.PROTOCOL_HOPOPT or IPv6.PROTOCOL_DSTOPT
Parameters
type the type to set
Returns
this
Definition at line 113 of file BaseOptions.java.
References org.onlab.packet.ipv6.BaseOptions.type.
Member Data Documentation
final byte org.onlab.packet.ipv6.BaseOptions.FIXED_HEADER_LENGTH = 2 static
Definition at line 36 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.BaseOptions.deserializer(), and org.onlab.packet.ipv6.BaseOptions.serialize().
final byte org.onlab.packet.ipv6.BaseOptions.FIXED_OPTIONS_LENGTH = 6 static
Definition at line 37 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.BaseOptions.deserialize(), and org.onlab.packet.ipv6.BaseOptions.deserializer().
byte org.onlab.packet.ipv6.BaseOptions.headerExtLength protected
Definition at line 41 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.BaseOptions.equals(), and org.onlab.packet.ipv6.BaseOptions.setHeaderExtLength().
final byte org.onlab.packet.ipv6.BaseOptions.LENGTH_UNIT = 8 static
Definition at line 38 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.BaseOptions.deserialize(), and org.onlab.packet.ipv6.BaseOptions.deserializer().
byte org.onlab.packet.ipv6.BaseOptions.nextHeader protected
Definition at line 40 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.BaseOptions.deserializer(), org.onlab.packet.ipv6.BaseOptions.equals(), and org.onlab.packet.ipv6.BaseOptions.setNextHeader().
byte [] org.onlab.packet.ipv6.BaseOptions.options protected
Definition at line 42 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.BaseOptions.equals(), org.onlab.packet.ipv6.BaseOptions.hashCode(), and org.onlab.packet.ipv6.BaseOptions.setOptions().
byte org.onlab.packet.ipv6.BaseOptions.type protected
Definition at line 43 of file BaseOptions.java.
Referenced by org.onlab.packet.ipv6.BaseOptions.equals(), and org.onlab.packet.ipv6.BaseOptions.setType().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ipv6/BaseOptions.java