onos: org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4 Class Reference
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4 Class Reference
Implementation of Node LS NLRI.
Classes
enum ProtocolType
Enum to provide PROTOCOLTYPE.
Public Member Functions
BgpNodeLSNlriVer4 ()
Reset fields.
BgpNodeLSNlriVer4 (long identifier, byte protocolId, BgpNodeLSIdentifier localNodeDescriptors, boolean isVpn, RouteDistinguisher routeDistinguisher)
Constructors to initialize its parameters.
NlriType getNlriType ()
Returns NlriType of BGP-LS NLRI.
BgpNodeLSIdentifier getLocalNodeDescriptors ()
Returns local node descriptors.
boolean isVpnPresent ()
Returns whether VPN is present or not.
RouteDistinguisher getRouteDistinguisher ()
Returns Route distinguisher in Nlri.
long getIdentifier ()
Returns Identifier in Nlri.
void setNodeLSIdentifier (BgpNodeLSIdentifier localNodeDescriptors)
Set the node LS identifier.
ProtocolType getProtocolId () throws BgpParseException
Returns Protocol Id in Nlri.
String toString ()
Static Public Member Functions
static BgpNodeLSNlriVer4 read (ChannelBuffer cb, short afi, byte safi) throws BgpParseException
Reads from channelBuffer and parses Node LS Nlri.
Static Public Attributes
static final int NODE_NLRITYPE = 1
static final int IDENTIFIER_LENGTH = 16
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(BgpNodeLSNlriVer4.class)
Detailed Description
Implementation of Node LS NLRI.
Definition at line 33 of file BgpNodeLSNlriVer4.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.BgpNodeLSNlriVer4 ()
Reset fields.
Definition at line 90 of file BgpNodeLSNlriVer4.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.read().
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.BgpNodeLSNlriVer4 (long identifier, byte protocolId, BgpNodeLSIdentifier localNodeDescriptors, boolean isVpn, RouteDistinguisher routeDistinguisher)
Constructors to initialize its parameters.
Parameters
identifier of LinkState Nlri
protocolId of LinkState Nlri
localNodeDescriptors local node descriptors
isVpn true if VPN info is present
routeDistinguisher unique for each VPN
Definition at line 107 of file BgpNodeLSNlriVer4.java.
Member Function Documentation
long org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getIdentifier ()
Returns Identifier in Nlri.
Returns
Identifier in Nlri
Implements org.onosproject.bgpio.protocol.BgpLSNlri.
Definition at line 169 of file BgpNodeLSNlriVer4.java.
Referenced by org.onosproject.bgp.controller.BgpDpid.BgpDpid().
BgpNodeLSIdentifier org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getLocalNodeDescriptors ()
Returns local node descriptors.
Returns
local node descriptors
Implements org.onosproject.bgpio.protocol.BgpNodeLSNlri.
Definition at line 150 of file BgpNodeLSNlriVer4.java.
Referenced by org.onosproject.bgp.controller.BgpDpid.BgpDpid().
NlriType org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getNlriType ()
Returns NlriType of BGP-LS NLRI.
Returns
NlriType of BGP-LS NLRI
Implements org.onosproject.bgpio.protocol.BgpLSNlri.
Definition at line 145 of file BgpNodeLSNlriVer4.java.
References org.onosproject.bgpio.protocol.NlriType.NODE.
ProtocolType org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getProtocolId () throws BgpParseException
Returns Protocol Id in Nlri.
Returns
Protocol Id in Nlri
Exceptions
BgpParseException while getting protocol ID
Implements org.onosproject.bgpio.protocol.BgpLSNlri.
Definition at line 183 of file BgpNodeLSNlriVer4.java.
References org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.DIRECT, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.ISIS_LEVEL_ONE, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.ISIS_LEVEL_TWO, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.OSPF_V2, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.OSPF_V3, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.STATIC_CONFIGURATION, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
RouteDistinguisher org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getRouteDistinguisher ()
Returns Route distinguisher in Nlri.
Returns
Route distinguisher in Nlri
Implements org.onosproject.bgpio.protocol.BgpLSNlri.
Definition at line 164 of file BgpNodeLSNlriVer4.java.
Referenced by org.onosproject.bgp.controller.BgpDpid.BgpDpid().
boolean org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.isVpnPresent ()
Returns whether VPN is present or not.
Returns
whether VPN is present or not
Definition at line 159 of file BgpNodeLSNlriVer4.java.
static BgpNodeLSNlriVer4 org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.read (ChannelBuffer cb, short afi, byte safi) throws BgpParseException static
Reads from channelBuffer and parses Node LS Nlri.
Parameters
cb ChannelBuffer
afi Address Family Identifier
safi Subsequent Address Family Identifier
Returns
object of this class
Exceptions
BgpParseException while parsing node descriptors
Definition at line 125 of file BgpNodeLSNlriVer4.java.
References org.onosproject.bgpio.util.Constants.AFI_VALUE, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.BgpNodeLSNlriVer4(), and org.onosproject.bgpio.util.Constants.VPN_SAFI_VALUE.
void org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.setNodeLSIdentifier (BgpNodeLSIdentifier localNodeDescriptors)
Set the node LS identifier.
Parameters
localNodeDescriptors node LS identifier to set
Definition at line 178 of file BgpNodeLSNlriVer4.java.
String org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.toString ()
Definition at line 203 of file BgpNodeLSNlriVer4.java.
Member Data Documentation
final int org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.IDENTIFIER_LENGTH = 16 static
Definition at line 54 of file BgpNodeLSNlriVer4.java.
final Logger org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.log = LoggerFactory.getLogger(BgpNodeLSNlriVer4.class) static protected
Definition at line 51 of file BgpNodeLSNlriVer4.java.
final int org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.NODE_NLRITYPE = 1 static
Definition at line 53 of file BgpNodeLSNlriVer4.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/protocol/linkstate/BgpNodeLSNlriVer4.java