onos: org.onlab.packet.ndp.RouterAdvertisement Class Reference
org.onlab.packet.ndp.RouterAdvertisement Class Reference
Implements ICMPv6 Router Advertisement packet format.
Public Member Functions
byte getCurrentHopLimit ()
Gets current hop limit.
RouterAdvertisement setCurrentHopLimit (final byte currentHopLimit)
Sets current hop limit.
byte getMFlag ()
Gets managed address configuration flag.
RouterAdvertisement setMFlag (final byte mFlag)
Sets managed address configuration flag.
byte getOFlag ()
Gets other configuration flag.
RouterAdvertisement setOFlag (final byte oFlag)
Sets other configuration flag.
short getRouterLifetime ()
Gets router lifetime.
RouterAdvertisement setRouterLifetime (final short routerLifetime)
Sets router lifetime.
int getReachableTime ()
Gets reachable time.
RouterAdvertisement setReachableTime (final int reachableTime)
Sets reachable time.
int getRetransmitTimer ()
Gets retransmission timer.
RouterAdvertisement setRetransmitTimer (final int retransmitTimer)
Sets retransmission timer.
List
< NeighborDiscoveryOptions.Option > getOptions ()
Gets the Neighbor Discovery Protocol packet options.
RouterAdvertisement addOption (final byte type, final byte[] data)
Adds a Neighbor Discovery Protocol packet option.
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
Static Public Member Functions
static Deserializer
< RouterAdvertisement > deserializer ()
Deserializer function for router advertisement packets.
Static Public Attributes
static final byte HEADER_LENGTH = 12
Protected Attributes
byte currentHopLimit
byte mFlag
byte oFlag
short routerLifetime
int reachableTime
int retransmitTimer
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Implements ICMPv6 Router Advertisement packet format.
(RFC 4861)
Definition at line 30 of file RouterAdvertisement.java.
Member Function Documentation
RouterAdvertisement org.onlab.packet.ndp.RouterAdvertisement.addOption (final byte type, final byte[] data)
Adds a Neighbor Discovery Protocol packet option.
Parameters
type the option type
data the option data
Returns
this
Definition at line 179 of file RouterAdvertisement.java.
IPacket org.onlab.packet.ndp.RouterAdvertisement.deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
NOTE: This method has been deprecated and will be removed in a future release. It is now recommended to use the Deserializer function provided by the deserialize() method on each packet to deserialize them. The Deserializer functions are robust to malformed input.
Parameters
data bytes to deserialize
offset offset to start deserializing from
length length of the data to deserialize
Returns
the deserialized data
Deprecated:
in Cardinal Release
Implements org.onlab.packet.IPacket.
Definition at line 213 of file RouterAdvertisement.java.
References find-link-in-cluster.length.
Referenced by org.onlab.packet.ndp.RouterAdvertisement.deserializer().
static Deserializer<RouterAdvertisement> org.onlab.packet.ndp.RouterAdvertisement.deserializer () static
Deserializer function for router advertisement packets.
Returns
deserializer function
Definition at line 296 of file RouterAdvertisement.java.
References org.onlab.packet.ndp.RouterAdvertisement.deserialize(), org.onlab.packet.ndp.RouterAdvertisement.HEADER_LENGTH, and find-link-in-cluster.length.
boolean org.onlab.packet.ndp.RouterAdvertisement.equals (final Object obj)
Definition at line 256 of file RouterAdvertisement.java.
References org.onlab.packet.ndp.RouterAdvertisement.currentHopLimit, org.onlab.packet.ndp.NeighborDiscoveryOptions.equals(), org.onlab.packet.ndp.RouterAdvertisement.mFlag, org.onlab.packet.ndp.RouterAdvertisement.oFlag, org.onlab.packet.ndp.RouterAdvertisement.reachableTime, org.onlab.packet.ndp.RouterAdvertisement.retransmitTimer, and org.onlab.packet.ndp.RouterAdvertisement.routerLifetime.
Referenced by org.onlab.packet.ndp.RouterAdvertisementTest.testEqual().
byte org.onlab.packet.ndp.RouterAdvertisement.getCurrentHopLimit ()
Gets current hop limit.
Returns
the current hop limit
Definition at line 48 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisementTest.testDeserialize().
byte org.onlab.packet.ndp.RouterAdvertisement.getMFlag ()
Gets managed address configuration flag.
Returns
the managed address configuration flag
Definition at line 68 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisementTest.testDeserialize().
byte org.onlab.packet.ndp.RouterAdvertisement.getOFlag ()
Gets other configuration flag.
Returns
the other configuration flag
Definition at line 88 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisementTest.testDeserialize().
List<NeighborDiscoveryOptions.Option> org.onlab.packet.ndp.RouterAdvertisement.getOptions ()
Gets the Neighbor Discovery Protocol packet options.
Returns
the Neighbor Discovery Protocol packet options
Definition at line 168 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisementTest.testDeserialize().
int org.onlab.packet.ndp.RouterAdvertisement.getReachableTime ()
Gets reachable time.
Returns
the reachable time
Definition at line 128 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisementTest.testDeserialize().
int org.onlab.packet.ndp.RouterAdvertisement.getRetransmitTimer ()
Gets retransmission timer.
Returns
the retransmission timer
Definition at line 148 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisementTest.testDeserialize().
short org.onlab.packet.ndp.RouterAdvertisement.getRouterLifetime ()
Gets router lifetime.
Returns
the router lifetime
Definition at line 108 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisementTest.testDeserialize().
int org.onlab.packet.ndp.RouterAdvertisement.hashCode ()
Definition at line 237 of file RouterAdvertisement.java.
byte [] org.onlab.packet.ndp.RouterAdvertisement.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 185 of file RouterAdvertisement.java.
References org.onlab.packet.ndp.NeighborDiscoveryOptions.hasOptions(), org.onlab.packet.ndp.RouterAdvertisement.HEADER_LENGTH, find-link-in-cluster.length, org.onlab.packet.ndp.RouterAdvertisement.mFlag, org.onlab.packet.ndp.RouterAdvertisement.reachableTime, org.onlab.packet.ndp.RouterAdvertisement.retransmitTimer, and org.onlab.packet.ndp.RouterAdvertisement.routerLifetime.
Referenced by org.onlab.packet.ndp.RouterAdvertisementTest.testSerialize().
RouterAdvertisement org.onlab.packet.ndp.RouterAdvertisement.setCurrentHopLimit (final byte currentHopLimit)
Sets current hop limit.
Parameters
currentHopLimit the current hop limit to set
Returns
this
Definition at line 58 of file RouterAdvertisement.java.
References org.onlab.packet.ndp.RouterAdvertisement.currentHopLimit.
RouterAdvertisement org.onlab.packet.ndp.RouterAdvertisement.setMFlag (final byte mFlag)
Sets managed address configuration flag.
Parameters
mFlag the managed address configuration flag to set
Returns
this
Definition at line 78 of file RouterAdvertisement.java.
References org.onlab.packet.ndp.RouterAdvertisement.mFlag.
RouterAdvertisement org.onlab.packet.ndp.RouterAdvertisement.setOFlag (final byte oFlag)
Sets other configuration flag.
Parameters
oFlag the other configuration flag to set
Returns
this
Definition at line 98 of file RouterAdvertisement.java.
References org.onlab.packet.ndp.RouterAdvertisement.oFlag.
RouterAdvertisement org.onlab.packet.ndp.RouterAdvertisement.setReachableTime (final int reachableTime)
Sets reachable time.
Parameters
reachableTime the reachable time to set
Returns
this
Definition at line 138 of file RouterAdvertisement.java.
References org.onlab.packet.ndp.RouterAdvertisement.reachableTime.
RouterAdvertisement org.onlab.packet.ndp.RouterAdvertisement.setRetransmitTimer (final int retransmitTimer)
Sets retransmission timer.
Parameters
retransmitTimer the retransmission timer to set
Returns
this
Definition at line 158 of file RouterAdvertisement.java.
References org.onlab.packet.ndp.RouterAdvertisement.retransmitTimer.
RouterAdvertisement org.onlab.packet.ndp.RouterAdvertisement.setRouterLifetime (final short routerLifetime)
Sets router lifetime.
Parameters
routerLifetime the router lifetime to set
Returns
this
Definition at line 118 of file RouterAdvertisement.java.
References org.onlab.packet.ndp.RouterAdvertisement.routerLifetime.
Member Data Documentation
byte org.onlab.packet.ndp.RouterAdvertisement.currentHopLimit protected
Definition at line 33 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisement.equals(), and org.onlab.packet.ndp.RouterAdvertisement.setCurrentHopLimit().
final byte org.onlab.packet.ndp.RouterAdvertisement.HEADER_LENGTH = 12 static
Definition at line 31 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisement.deserializer(), org.onlab.packet.ndp.RouterAdvertisement.serialize(), and org.onlab.packet.ndp.RouterAdvertisementTest.testDeserializeTruncated().
byte org.onlab.packet.ndp.RouterAdvertisement.mFlag protected
Definition at line 34 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisement.equals(), org.onlab.packet.ndp.RouterAdvertisement.serialize(), and org.onlab.packet.ndp.RouterAdvertisement.setMFlag().
byte org.onlab.packet.ndp.RouterAdvertisement.oFlag protected
Definition at line 35 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisement.equals(), and org.onlab.packet.ndp.RouterAdvertisement.setOFlag().
int org.onlab.packet.ndp.RouterAdvertisement.reachableTime protected
Definition at line 37 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisement.equals(), org.onlab.packet.ndp.RouterAdvertisement.serialize(), and org.onlab.packet.ndp.RouterAdvertisement.setReachableTime().
int org.onlab.packet.ndp.RouterAdvertisement.retransmitTimer protected
Definition at line 38 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisement.equals(), org.onlab.packet.ndp.RouterAdvertisement.serialize(), and org.onlab.packet.ndp.RouterAdvertisement.setRetransmitTimer().
short org.onlab.packet.ndp.RouterAdvertisement.routerLifetime protected
Definition at line 36 of file RouterAdvertisement.java.
Referenced by org.onlab.packet.ndp.RouterAdvertisement.equals(), org.onlab.packet.ndp.RouterAdvertisement.serialize(), and org.onlab.packet.ndp.RouterAdvertisement.setRouterLifetime().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/ndp/RouterAdvertisement.java