onos: org.onosproject.store.consistent.impl.DefaultTransactionContext Class Reference
org.onosproject.store.consistent.impl.DefaultTransactionContext Class Reference
Default TransactionContext implementation.
Public Member Functions
DefaultTransactionContext (long transactionId, Database database, Supplier< ConsistentMapBuilder > mapBuilderSupplier)
long transactionId ()
Returns the unique transactionId.
void begin ()
Starts a new transaction.
boolean isOpen ()
Returns if this transaction context is open.
boolean commit ()
Commits a transaction that was previously started thereby making its changes permanent and externally visible.
void abort ()
Aborts any changes made in this transaction context and discarding all locally cached updates.
Detailed Description
Default TransactionContext implementation.
Definition at line 39 of file DefaultTransactionContext.java.
Constructor & Destructor Documentation
org.onosproject.store.consistent.impl.DefaultTransactionContext.DefaultTransactionContext (long transactionId, Database database, Supplier< ConsistentMapBuilder > mapBuilderSupplier)
Definition at line 49 of file DefaultTransactionContext.java.
References org.onosproject.store.consistent.impl.DefaultTransactionContext.transactionId().
Member Function Documentation
void org.onosproject.store.consistent.impl.DefaultTransactionContext.abort ()
Aborts any changes made in this transaction context and discarding all locally cached updates.
Implements org.onosproject.store.service.TransactionContext.
Definition at line 108 of file DefaultTransactionContext.java.
References org.onosproject.store.consistent.impl.DefaultTransactionContext.isOpen().
Referenced by org.onosproject.store.consistent.impl.DefaultTransactionContext.commit().
void org.onosproject.store.consistent.impl.DefaultTransactionContext.begin ()
Starts a new transaction.
Implements org.onosproject.store.service.TransactionContext.
Definition at line 63 of file DefaultTransactionContext.java.
References org.onosproject.store.consistent.impl.DefaultTransactionContext.isOpen().
boolean org.onosproject.store.consistent.impl.DefaultTransactionContext.commit ()
Commits a transaction that was previously started thereby making its changes permanent and externally visible.
Returns
true if this transaction succeeded, otherwise false.
Implements org.onosproject.store.service.TransactionContext.
Definition at line 89 of file DefaultTransactionContext.java.
References org.onosproject.store.consistent.impl.DefaultTransactionContext.abort(), org.onosproject.store.consistent.impl.DefaultTransactionContext.isOpen(), and org.onosproject.store.consistent.impl.DefaultTransactionContext.transactionId().
boolean org.onosproject.store.consistent.impl.DefaultTransactionContext.isOpen ()
Returns if this transaction context is open.
Returns
true if open, false otherwise
Implements org.onosproject.store.service.TransactionContext.
Definition at line 69 of file DefaultTransactionContext.java.
Referenced by org.onosproject.store.consistent.impl.DefaultTransactionContext.abort(), org.onosproject.store.consistent.impl.DefaultTransactionContext.begin(), and org.onosproject.store.consistent.impl.DefaultTransactionContext.commit().
long org.onosproject.store.consistent.impl.DefaultTransactionContext.transactionId ()
Returns the unique transactionId.
Returns
transaction id
Implements org.onosproject.store.service.TransactionContext.
Definition at line 58 of file DefaultTransactionContext.java.
Referenced by org.onosproject.store.consistent.impl.DefaultTransactionContext.commit(), and org.onosproject.store.consistent.impl.DefaultTransactionContext.DefaultTransactionContext().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/DefaultTransactionContext.java