onos: org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore Class Reference
org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore Class Reference
Manages inventory of tunnel in distributed data store that uses optimistic replication and gossip based techniques.
Public Member Functions
void activate ()
void deactivate ()
TunnelId createOrUpdateTunnel (Tunnel tunnel)
Creates or updates a tunnel.
void deleteTunnel (TunnelId tunnelId)
Deletes a tunnel by a specific tunnel identifier.
void deleteTunnel (TunnelEndPoint src, TunnelEndPoint dst, ProviderId producerName)
Deletes all tunnels between source point and destination point.
void deleteTunnel (TunnelEndPoint src, TunnelEndPoint dst, Type type, ProviderId producerName)
Tunnel borrowTunnel (ApplicationId appId, TunnelId tunnelId, Annotations...annotations)
Returns a specific tunnel.
Collection< Tunnel > borrowTunnel (ApplicationId appId, TunnelEndPoint src, TunnelEndPoint dst, Annotations...annotations)
Returns all tunnels between source and destination.
Collection< Tunnel > borrowTunnel (ApplicationId appId, TunnelEndPoint src, TunnelEndPoint dst, Type type, Annotations...annotations)
Returns all specified type tunnels between source and destination.
Collection< Tunnel > borrowTunnel (ApplicationId appId, TunnelName tunnelName, Annotations...annotations)
Returns a specific tunnel by tunnelName.
boolean returnTunnel (ApplicationId appId, TunnelName tunnelName, Annotations...annotations)
Returns all specific name tunnel back store.
boolean returnTunnel (ApplicationId appId, TunnelId tunnelId, Annotations...annotations)
Returns back a specific tunnel to store.
boolean returnTunnel (ApplicationId appId, TunnelEndPoint src, TunnelEndPoint dst, Type type, Annotations...annotations)
Returns all specific type tunnels between source and destination back store.
boolean returnTunnel (ApplicationId appId, TunnelEndPoint src, TunnelEndPoint dst, Annotations...annotations)
Returns all tunnels between source and destination back the store.
Tunnel queryTunnel (TunnelId tunnelId)
Returns a tunnel by a specific tunnel identity.
Collection< TunnelSubscription > queryTunnelSubscription (ApplicationId appId)
Returns all tunnel subscription record by consumer.
Collection< Tunnel > queryTunnel (Type type)
Returns all specified type tunnels.
Collection< Tunnel > queryTunnel (TunnelEndPoint src, TunnelEndPoint dst)
Returns all tunnels between source point and destination point.
Collection< Tunnel > queryAllTunnels ()
Returns all tunnels.
int tunnelCount ()
Returns all tunnels.
Public Member Functions inherited from org.onosproject.incubator.net.tunnel.TunnelStore
void deleteTunnel (TunnelEndPoint src, TunnelEndPoint dst, Tunnel.Type type, ProviderId producerName)
Deletes all specific type tunnels between source point and destination point.
Protected Attributes
ClusterCommunicationService clusterCommunicator
ClusterService clusterService
CoreService coreService
StorageService storageService
Detailed Description
Manages inventory of tunnel in distributed data store that uses optimistic replication and gossip based techniques.
Definition at line 72 of file DistributedTunnelStore.java.
Member Function Documentation
void org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.activate ()
Definition at line 109 of file DistributedTunnelStore.java.
References org.onosproject.store.serializers.KryoNamespaces.API.
Tunnel org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.borrowTunnel (ApplicationId consumerId, TunnelId tunnelId, Annotations... annotations)
Returns a specific tunnel.
Annotations parameter is reserved. If there is no tunnel in the store, return a "null" object, and record the tunnel subscription. Where tunnel is created, ONOS notifies this consumer actively.
Parameters
consumerId a tunnel consumer
tunnelId tunnel identify generated by onos
annotations parameter
Returns
Tunnel subscribed tunnel
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 284 of file DistributedTunnelStore.java.
References org.onosproject.incubator.net.tunnel.Tunnel.state().
Collection<Tunnel> org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.borrowTunnel (ApplicationId consumerId, TunnelEndPoint src, TunnelEndPoint dst, Annotations... annotations)
Returns all tunnels between source and destination.
Annotations parameter is reserved. If there is no any tunnel in the store, return a empty collection, and record the tunnel subscription. Where tunnel is created, ONOS notifies this consumer actively. Otherwise ONOS core returns all the tunnels, consumer determined which one to use.
Parameters
consumerId a tunnel consumer
src a source point of tunnel.
dst a destination point of tunnel
annotations parameter
Returns
collection of subscribed Tunnels
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 303 of file DistributedTunnelStore.java.
References org.onosproject.incubator.net.tunnel.Tunnel.state().
Collection<Tunnel> org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.borrowTunnel (ApplicationId consumerId, TunnelEndPoint src, TunnelEndPoint dst, Type type, Annotations... annotations)
Returns all specified type tunnels between source and destination.
Annotations parameter is reserved. If there is no any tunnel in the store, return a empty collection, and record the tunnel subscription. Where tunnel is created, ONOS notifies this consumer actively. Otherwise,ONOS core returns all available tunnels, consumer determined which one to use.
Parameters
consumerId a tunnel consumer
src a source point of tunnel.
dst a destination point of tunnel
type tunnel type
annotations Annotations
Returns
collection of available Tunnels
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 333 of file DistributedTunnelStore.java.
References org.onosproject.incubator.net.tunnel.Tunnel.state(), and org.onosproject.incubator.net.tunnel.Tunnel.type().
Collection<Tunnel> org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.borrowTunnel (ApplicationId consumerId, TunnelName tunnelName, Annotations... annotations)
Returns a specific tunnel by tunnelName.
Annotations parameter is reserved. If there is no tunnel in the store, return a "null" object,and record the tunnel subscription. Where tunnel is created, ONOS notifies this consumer actively.
Parameters
consumerId a tunnel consumer
tunnelName tunnel name
annotations parameter
Returns
collection of subscribed Tunnels
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 364 of file DistributedTunnelStore.java.
References org.onosproject.incubator.net.tunnel.Tunnel.state().
TunnelId org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.createOrUpdateTunnel (Tunnel tunnel)
Creates or updates a tunnel.
Parameters
tunnel tunnel
Returns
tunnel identity
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 149 of file DistributedTunnelStore.java.
References org.onosproject.net.Annotated.annotations(), org.onosproject.incubator.net.tunnel.Tunnel.dst(), org.onosproject.incubator.net.tunnel.Tunnel.path(), org.onosproject.net.Provided.providerId(), org.onosproject.incubator.net.tunnel.Tunnel.state(), org.onosproject.incubator.net.tunnel.Tunnel.tunnelId(), and org.onosproject.incubator.net.tunnel.Tunnel.tunnelName().
void org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.deactivate ()
Definition at line 139 of file DistributedTunnelStore.java.
void org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.deleteTunnel (TunnelId tunnelId)
Deletes a tunnel by a specific tunnel identifier.
Parameters
tunnelId tunnel unique identifier generated by ONOS
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 211 of file DistributedTunnelStore.java.
References org.onosproject.incubator.net.tunnel.Tunnel.src().
void org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.deleteTunnel (TunnelEndPoint src, TunnelEndPoint dst, ProviderId producerName)
Deletes all tunnels between source point and destination point.
Parameters
src a source point of tunnel.
dst a destination point of tunnel.
producerName producerName
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 227 of file DistributedTunnelStore.java.
References org.onosproject.net.provider.ProviderId.equals(), find-device.id, org.onosproject.net.Provided.providerId(), and org.onosproject.incubator.net.tunnel.Tunnel.tunnelId().
void org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.deleteTunnel (TunnelEndPoint src, TunnelEndPoint dst, Type type, ProviderId producerName)
Definition at line 255 of file DistributedTunnelStore.java.
References org.onosproject.net.provider.ProviderId.equals(), find-device.id, org.onosproject.net.Provided.providerId(), org.onosproject.incubator.net.tunnel.Tunnel.tunnelId(), and org.onosproject.incubator.net.tunnel.Tunnel.type().
Collection<Tunnel> org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.queryAllTunnels ()
Returns all tunnels.
Returns
Collection of tunnels
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 476 of file DistributedTunnelStore.java.
Tunnel org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.queryTunnel (TunnelId tunnelId)
Returns a tunnel by a specific tunnel identity.
Parameters
tunnelId tunnel identify generated by tunnel producer
Returns
Tunnel
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 436 of file DistributedTunnelStore.java.
Collection<Tunnel> org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.queryTunnel (Type type)
Returns all specified type tunnels.
Parameters
type tunnel type
Returns
Collection of tunnels
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 447 of file DistributedTunnelStore.java.
References find-device.id.
Collection<Tunnel> org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.queryTunnel (TunnelEndPoint src, TunnelEndPoint dst)
Returns all tunnels between source point and destination point.
Parameters
src a source point of tunnel.
dst a destination point of tunnel.
Returns
Collection of tunnels
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 461 of file DistributedTunnelStore.java.
References find-device.id.
Collection<TunnelSubscription> org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.queryTunnelSubscription (ApplicationId consumerId)
Returns all tunnel subscription record by consumer.
Parameters
consumerId consumer identity
Returns
Collection of TunnelSubscription
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 441 of file DistributedTunnelStore.java.
boolean org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.returnTunnel (ApplicationId consumerId, TunnelName tunnelName, Annotations... annotations)
Returns all specific name tunnel back store.
Annotations parameter is reserved.If there is no tunnel in the store, return a "null" object,and record the tunnel subscription. Where tunnel is created, ONOS notifies this consumer actively.
Parameters
consumerId a tunnel consumer
tunnelName tunnel name
annotations Annotations
Returns
boolean
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 393 of file DistributedTunnelStore.java.
boolean org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.returnTunnel (ApplicationId consumerId, TunnelId tunnelId, Annotations... annotations)
Returns back a specific tunnel to store.
Parameters
consumerId a tunnel consumer
tunnelId tunnel identify generated by ONOS
annotations Annotations
Returns
success or fail
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 401 of file DistributedTunnelStore.java.
boolean org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.returnTunnel (ApplicationId consumerId, TunnelEndPoint src, TunnelEndPoint dst, Type type, Annotations... annotations)
Returns all specific type tunnels between source and destination back store.
Annotations parameter is reserved.
Parameters
consumerId a tunnel consumer
src a source point of tunnel.
dst a destination point of tunnel
type tunnel type
annotations Annotations
Returns
success or fail
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 409 of file DistributedTunnelStore.java.
boolean org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.returnTunnel (ApplicationId consumerId, TunnelEndPoint src, TunnelEndPoint dst, Annotations... annotations)
Returns all tunnels between source and destination back the store.
Annotations parameter is reserved.
Parameters
consumerId a tunnel consumer
src a source point of tunnel.
dst a destination point of tunnel.
annotations Annotations
Returns
success or fail
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 417 of file DistributedTunnelStore.java.
int org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.tunnelCount ()
Returns all tunnels.
Returns
all tunnels
Implements org.onosproject.incubator.net.tunnel.TunnelStore.
Definition at line 481 of file DistributedTunnelStore.java.
Member Data Documentation
ClusterCommunicationService org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.clusterCommunicator protected
Definition at line 84 of file DistributedTunnelStore.java.
ClusterService org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.clusterService protected
Definition at line 87 of file DistributedTunnelStore.java.
CoreService org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.coreService protected
Definition at line 90 of file DistributedTunnelStore.java.
StorageService org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.storageService protected
Definition at line 93 of file DistributedTunnelStore.java.
The documentation for this class was generated from the following file:
incubator/store/src/main/java/org/onosproject/incubator/store/tunnel/impl/DistributedTunnelStore.java