onos: org.onosproject.codec.impl.GroupBucketCodec Class Reference
org.onosproject.codec.impl.GroupBucketCodec Class Reference
Group bucket JSON codec.
Public Member Functions
ObjectNode encode (GroupBucket bucket, CodecContext context)
Detailed Description
Group bucket JSON codec.
Definition at line 30 of file GroupBucketCodec.java.
Member Function Documentation
ObjectNode org.onosproject.codec.impl.GroupBucketCodec.encode (GroupBucket bucket, CodecContext context)
Definition at line 41 of file GroupBucketCodec.java.
References org.onosproject.net.group.GroupBucket.bytes(), org.onosproject.net.group.GroupBucket.packets(), org.onosproject.net.group.GroupBucket.treatment(), org.onosproject.net.group.GroupBucket.watchGroup(), org.onosproject.net.group.GroupBucket.watchPort(), and org.onosproject.net.group.GroupBucket.weight().
The documentation for this class was generated from the following file:
core/common/src/main/java/org/onosproject/codec/impl/GroupBucketCodec.java