onos: org.onosproject.codec.impl.InstructionCodecTest Class Reference
org.onosproject.codec.impl.InstructionCodecTest Class Reference
Unit tests for Instruction codec.
Public Member Functions
void setUp ()
Sets up for each test.
void pushHeaderInstructionsTest ()
Tests the encoding of push header instructions.
void dropInstructionTest ()
Tests the encoding of drop instructions.
void outputInstructionTest ()
Tests the encoding of output instructions.
void modLambdaInstructionTest ()
Tests the encoding of mod lambda instructions.
void modOchSignalInstructionTest ()
Tests the encoding of mod OCh signal instructions.
void modOduSignalIdInstructionTest ()
Tests the encoding of mod ODU signal ID instructions.
void modEtherInstructionTest ()
Tests the encoding of mod ether instructions.
void modVlanIdInstructionTest ()
Tests the encoding of mod vlan id instructions.
void modVlanPcpInstructionTest ()
Tests the encoding of mod vlan pcp instructions.
void modIPSrcInstructionTest ()
Tests the encoding of mod IPv4 src instructions.
void modIPDstInstructionTest ()
Tests the encoding of mod IPv4 dst instructions.
void modIPv6SrcInstructionTest ()
Tests the encoding of mod IPv6 src instructions.
void modIPv6DstInstructionTest ()
Tests the encoding of mod IPv6 dst instructions.
void modIPv6FlowLabelInstructionTest ()
Tests the encoding of mod IPv6 flow label instructions.
void modMplsLabelInstructionTest ()
Tests the encoding of mod MPLS label instructions.
Detailed Description
Unit tests for Instruction codec.
Definition at line 49 of file InstructionCodecTest.java.
Member Function Documentation
void org.onosproject.codec.impl.InstructionCodecTest.dropInstructionTest ()
Tests the encoding of drop instructions.
Definition at line 79 of file InstructionCodecTest.java.
void org.onosproject.codec.impl.InstructionCodecTest.modEtherInstructionTest ()
Tests the encoding of mod ether instructions.
Definition at line 143 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modL2Src(), and org.onlab.packet.MacAddress.valueOf().
void org.onosproject.codec.impl.InstructionCodecTest.modIPDstInstructionTest ()
Tests the encoding of mod IPv4 dst instructions.
Definition at line 197 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modL3Dst().
void org.onosproject.codec.impl.InstructionCodecTest.modIPSrcInstructionTest ()
Tests the encoding of mod IPv4 src instructions.
Definition at line 183 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modL3Src().
void org.onosproject.codec.impl.InstructionCodecTest.modIPv6DstInstructionTest ()
Tests the encoding of mod IPv6 dst instructions.
Definition at line 225 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modL3IPv6Dst().
void org.onosproject.codec.impl.InstructionCodecTest.modIPv6FlowLabelInstructionTest ()
Tests the encoding of mod IPv6 flow label instructions.
Definition at line 239 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modL3IPv6FlowLabel().
void org.onosproject.codec.impl.InstructionCodecTest.modIPv6SrcInstructionTest ()
Tests the encoding of mod IPv6 src instructions.
Definition at line 211 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modL3IPv6Src().
void org.onosproject.codec.impl.InstructionCodecTest.modLambdaInstructionTest ()
Tests the encoding of mod lambda instructions.
Definition at line 103 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modL0Lambda().
void org.onosproject.codec.impl.InstructionCodecTest.modMplsLabelInstructionTest ()
Tests the encoding of mod MPLS label instructions.
Definition at line 253 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modMplsLabel().
void org.onosproject.codec.impl.InstructionCodecTest.modOchSignalInstructionTest ()
Tests the encoding of mod OCh signal instructions.
Definition at line 116 of file InstructionCodecTest.java.
References org.onosproject.net.ChannelSpacing.CHL_100GHZ, org.onosproject.net.GridType.DWDM, org.onosproject.net.flow.instructions.Instructions.modL0Lambda(), and org.onosproject.net.Lambda.ochSignal().
void org.onosproject.codec.impl.InstructionCodecTest.modOduSignalIdInstructionTest ()
Tests the encoding of mod ODU signal ID instructions.
Definition at line 129 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modL1OduSignalId().
void org.onosproject.codec.impl.InstructionCodecTest.modVlanIdInstructionTest ()
Tests the encoding of mod vlan id instructions.
Definition at line 156 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modVlanId(), and org.onlab.packet.VlanId.vlanId().
void org.onosproject.codec.impl.InstructionCodecTest.modVlanPcpInstructionTest ()
Tests the encoding of mod vlan pcp instructions.
Definition at line 170 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.modVlanPcp().
void org.onosproject.codec.impl.InstructionCodecTest.outputInstructionTest ()
Tests the encoding of output instructions.
Definition at line 91 of file InstructionCodecTest.java.
void org.onosproject.codec.impl.InstructionCodecTest.pushHeaderInstructionsTest ()
Tests the encoding of push header instructions.
Definition at line 67 of file InstructionCodecTest.java.
References org.onosproject.net.flow.instructions.Instructions.pushMpls().
void org.onosproject.codec.impl.InstructionCodecTest.setUp ()
Sets up for each test.
Creates a context and fetches the instruction codec.
Definition at line 57 of file InstructionCodecTest.java.
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/codec/impl/InstructionCodecTest.java