onos: org.onosproject.net.flow.criteria.Criteria Class Reference
org.onosproject.net.flow.criteria.Criteria Class Reference
Factory class to create various traffic selection criteria.
Static Public Member Functions
static Criterion matchInPort (PortNumber port)
Creates a match on IN_PORT field using the specified value.
static Criterion matchInPhyPort (PortNumber port)
Creates a match on IN_PHY_PORT field using the specified value.
static Criterion matchMetadata (long metadata)
Creates a match on METADATA field using the specified value.
static Criterion matchEthDst (MacAddress mac)
Creates a match on ETH_DST field using the specified value.
static Criterion matchEthSrc (MacAddress mac)
Creates a match on ETH_SRC field using the specified value.
static Criterion matchEthType (int ethType)
Creates a match on ETH_TYPE field using the specified value.
static Criterion matchEthType (EthType ethType)
Creates a match on ETH_TYPE field using the specified value.
static Criterion matchVlanId (VlanId vlanId)
Creates a match on VLAN ID field using the specified value.
static Criterion matchVlanPcp (byte vlanPcp)
Creates a match on VLAN PCP field using the specified value.
static Criterion matchIPDscp (byte ipDscp)
Creates a match on IP DSCP field using the specified value.
static Criterion matchIPEcn (byte ipEcn)
Creates a match on IP ECN field using the specified value.
static Criterion matchIPProtocol (short proto)
Creates a match on IP proto field using the specified value.
static Criterion matchIPSrc (IpPrefix ip)
Creates a match on IPv4 source field using the specified value.
static Criterion matchIPDst (IpPrefix ip)
Creates a match on IPv4 destination field using the specified value.
static Criterion matchTcpSrc (short tcpPort)
Creates a match on TCP source port field using the specified value.
static Criterion matchTcpSrc (TpPort tcpPort)
Creates a match on TCP source port field using the specified value.
static Criterion matchTcpDst (short tcpPort)
Creates a match on TCP destination port field using the specified value.
static Criterion matchTcpDst (TpPort tcpPort)
Creates a match on TCP destination port field using the specified value.
static Criterion matchTcpFlags (int flags)
Creates a match on TCP flags using the specified value.
static Criterion matchUdpSrc (short udpPort)
Creates a match on UDP source port field using the specified value.
static Criterion matchUdpSrc (TpPort udpPort)
Creates a match on UDP source port field using the specified value.
static Criterion matchUdpDst (short udpPort)
Creates a match on UDP destination port field using the specified value.
static Criterion matchUdpDst (TpPort udpPort)
Creates a match on UDP destination port field using the specified value.
static Criterion matchSctpSrc (short sctpPort)
Creates a match on SCTP source port field using the specified value.
static Criterion matchSctpSrc (TpPort sctpPort)
Creates a match on SCTP source port field using the specified value.
static Criterion matchSctpDst (short sctpPort)
Creates a match on SCTP destination port field using the specified value.
static Criterion matchSctpDst (TpPort sctpPort)
Creates a match on SCTP destination port field using the specified value.
static Criterion matchIcmpType (short icmpType)
Creates a match on ICMP type field using the specified value.
static Criterion matchIcmpCode (short icmpCode)
Creates a match on ICMP code field using the specified value.
static Criterion matchIPv6Src (IpPrefix ip)
Creates a match on IPv6 source field using the specified value.
static Criterion matchIPv6Dst (IpPrefix ip)
Creates a match on IPv6 destination field using the specified value.
static Criterion matchIPv6FlowLabel (int flowLabel)
Creates a match on IPv6 flow label field using the specified value.
static Criterion matchIcmpv6Type (short icmpv6Type)
Creates a match on ICMPv6 type field using the specified value.
static Criterion matchIcmpv6Code (short icmpv6Code)
Creates a match on ICMPv6 code field using the specified value.
static Criterion matchIPv6NDTargetAddress (Ip6Address targetAddress)
Creates a match on IPv6 Neighbor Discovery target address using the specified value.
static Criterion matchIPv6NDSourceLinkLayerAddress (MacAddress mac)
Creates a match on IPv6 Neighbor Discovery source link-layer address using the specified value.
static Criterion matchIPv6NDTargetLinkLayerAddress (MacAddress mac)
Creates a match on IPv6 Neighbor Discovery target link-layer address using the specified value.
static Criterion matchMplsLabel (MplsLabel mplsLabel)
Creates a match on MPLS label.
static Criterion matchMplsBos (boolean mplsBos)
Creates a match on MPLS Bottom-of-Stack indicator bit.
static Criterion matchMplsTc (byte mplsTc)
Creates a match on MPLS TC.
static Criterion matchTunnelId (long tunnelId)
Creates a match on Tunnel ID.
static Criterion matchIPv6ExthdrFlags (int exthdrFlags)
Creates a match on IPv6 Extension Header pseudo-field fiags.
static Criterion matchLambda (Lambda lambda)
Creates a match on lambda using the specified value.
static Criterion matchOchSignalType (OchSignalType signalType)
Create a match on OCh (Optical Channel) signal type.
static Criterion matchOduSignalId (OduSignalId oduSignalId)
Creates a match on ODU (Optical channel Data Unit) signal ID using the specified value.
static Criterion matchOduSignalType (OduSignalType signalType)
Creates a match on ODU (Optical channel Data Unit) signal Type using the specified value.
static Criterion matchArpTpa (Ip4Address ip)
Creates a match on IPv4 destination field using the specified value.
static Criterion matchArpSpa (Ip4Address ip)
Creates a match on IPv4 source field using the specified value.
static Criterion matchArpTha (MacAddress mac)
Creates a match on MAC destination field using the specified value.
static Criterion matchArpSha (MacAddress mac)
Creates a match on MAC source field using the specified value.
static Criterion matchArpOp (int arpOp)
Creates a match on arp operation type field using the specified value.
static Criterion dummy ()
Detailed Description
Factory class to create various traffic selection criteria.
Definition at line 38 of file Criteria.java.
Member Function Documentation
static Criterion org.onosproject.net.flow.criteria.Criteria.dummy () static
Definition at line 582 of file Criteria.java.
Referenced by org.onosproject.codec.impl.CriterionCodecTest.checkCriterionTypes().
static Criterion org.onosproject.net.flow.criteria.Criteria.matchArpOp (int arpOp) static
Creates a match on arp operation type field using the specified value.
Parameters
arpOp arp operation type value
Returns
match criterion
Definition at line 578 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ARP_OP.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchArpSha (MacAddress mac) static
Creates a match on MAC source field using the specified value.
Parameters
mac MAC source value
Returns
match criterion
Definition at line 568 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ARP_SHA.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchArpSpa (Ip4Address ip) static
Creates a match on IPv4 source field using the specified value.
Parameters
ip ipv4 source value
Returns
match criterion
Definition at line 548 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ARP_SPA.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchArpTha (MacAddress mac) static
Creates a match on MAC destination field using the specified value.
Parameters
mac MAC destination value
Returns
match criterion
Definition at line 558 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ARP_THA.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchArpTpa (Ip4Address ip) static
Creates a match on IPv4 destination field using the specified value.
Parameters
ip ipv4 destination value
Returns
match criterion
Definition at line 538 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ARP_TPA.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchEthDst (MacAddress mac) static
Creates a match on ETH_DST field using the specified value.
This value may be a wildcard mask.
Parameters
mac MAC address value or wildcard mask
Returns
match criterion
Definition at line 83 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ETH_DST.
Referenced by org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterMacVlanFilters().
static Criterion org.onosproject.net.flow.criteria.Criteria.matchEthSrc (MacAddress mac) static
Creates a match on ETH_SRC field using the specified value.
This value may be a wildcard mask.
Parameters
mac MAC address value or wildcard mask
Returns
match criterion
Definition at line 94 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.ETH_SRC.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchEthType (int ethType) static
Creates a match on ETH_TYPE field using the specified value.
Parameters
ethType eth type value (16 bits unsigned integer)
Returns
match criterion
Definition at line 104 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchEthType (EthType ethType) static
Creates a match on ETH_TYPE field using the specified value.
Parameters
ethType eth type value
Returns
match criterion
Definition at line 114 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIcmpCode (short icmpCode) static
Creates a match on ICMP code field using the specified value.
Parameters
icmpCode ICMP code (8 bits unsigned integer)
Returns
match criterion
Definition at line 348 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIcmpType (short icmpType) static
Creates a match on ICMP type field using the specified value.
Parameters
icmpType ICMP type (8 bits unsigned integer)
Returns
match criterion
Definition at line 338 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIcmpv6Code (short icmpv6Code) static
Creates a match on ICMPv6 code field using the specified value.
Parameters
icmpv6Code ICMPv6 code (8 bits unsigned integer)
Returns
match criterion
Definition at line 398 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIcmpv6Type (short icmpv6Type) static
Creates a match on ICMPv6 type field using the specified value.
Parameters
icmpv6Type ICMPv6 type (8 bits unsigned integer)
Returns
match criterion
Definition at line 388 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchInPhyPort (PortNumber port) static
Creates a match on IN_PHY_PORT field using the specified value.
Parameters
port inport value
Returns
match criterion
Definition at line 62 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.IN_PHY_PORT.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchInPort (PortNumber port) static
Creates a match on IN_PORT field using the specified value.
Parameters
port inport value
Returns
match criterion
Definition at line 52 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.IN_PORT.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPDscp (byte ipDscp) static
Creates a match on IP DSCP field using the specified value.
Parameters
ipDscp ip dscp value (6 bits)
Returns
match criterion
Definition at line 144 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPDst (IpPrefix ip) static
Creates a match on IPv4 destination field using the specified value.
Parameters
ip ipv4 source value
Returns
match criterion
Definition at line 184 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.IPV4_DST.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPEcn (byte ipEcn) static
Creates a match on IP ECN field using the specified value.
Parameters
ipEcn ip ecn value (2 bits)
Returns
match criterion
Definition at line 154 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPProtocol (short proto) static
Creates a match on IP proto field using the specified value.
Parameters
proto ip protocol value (8 bits unsigned integer)
Returns
match criterion
Definition at line 164 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPSrc (IpPrefix ip) static
Creates a match on IPv4 source field using the specified value.
Parameters
ip ipv4 source value
Returns
match criterion
Definition at line 174 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.IPV4_SRC.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPv6Dst (IpPrefix ip) static
Creates a match on IPv6 destination field using the specified value.
Parameters
ip ipv6 destination value
Returns
match criterion
Definition at line 368 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.IPV6_DST.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPv6ExthdrFlags (int exthdrFlags) static
Creates a match on IPv6 Extension Header pseudo-field fiags.
Those are defined in Criterion.IPv6ExthdrFlags.
Parameters
exthdrFlags IPv6 Extension Header pseudo-field flags (16 bits)
Returns
match criterion
Definition at line 482 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPv6FlowLabel (int flowLabel) static
Creates a match on IPv6 flow label field using the specified value.
Parameters
flowLabel IPv6 flow label (20 bits)
Returns
match criterion
Definition at line 378 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPv6NDSourceLinkLayerAddress (MacAddress mac) static
Creates a match on IPv6 Neighbor Discovery source link-layer address using the specified value.
Parameters
mac IPv6 Neighbor Discovery source link-layer address
Returns
match criterion
Definition at line 420 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.IPV6_ND_SLL.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPv6NDTargetAddress (Ip6Address targetAddress) static
Creates a match on IPv6 Neighbor Discovery target address using the specified value.
Parameters
targetAddress IPv6 Neighbor Discovery target address
Returns
match criterion
Definition at line 409 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPv6NDTargetLinkLayerAddress (MacAddress mac) static
Creates a match on IPv6 Neighbor Discovery target link-layer address using the specified value.
Parameters
mac IPv6 Neighbor Discovery target link-layer address
Returns
match criterion
Definition at line 431 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.IPV6_ND_TLL.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchIPv6Src (IpPrefix ip) static
Creates a match on IPv6 source field using the specified value.
Parameters
ip ipv6 source value
Returns
match criterion
Definition at line 358 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.IPV6_SRC.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchLambda (Lambda lambda) static
Creates a match on lambda using the specified value.
Parameters
lambda lambda
Returns
match criterion
Definition at line 492 of file Criteria.java.
Referenced by org.onosproject.codec.impl.IntentCodecTest.intentWithTreatmentSelectorAndConstraints(), org.onosproject.net.flow.DefaultTrafficSelectorTest.testCriteriaCreation(), and org.onosproject.net.flow.DefaultTrafficSelectorTest.testEquals().
static Criterion org.onosproject.net.flow.criteria.Criteria.matchMetadata (long metadata) static
Creates a match on METADATA field using the specified value.
Parameters
metadata metadata value (64 bits data)
Returns
match criterion
Definition at line 72 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchMplsBos (boolean mplsBos) static
Creates a match on MPLS Bottom-of-Stack indicator bit.
Parameters
mplsBos boolean value indicating true (BOS=1) or false (BOS=0)
Returns
match criterion
Definition at line 451 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchMplsLabel (MplsLabel mplsLabel) static
Creates a match on MPLS label.
Parameters
mplsLabel MPLS label (20 bits)
Returns
match criterion
Definition at line 441 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchMplsTc (byte mplsTc) static
Creates a match on MPLS TC.
Parameters
mplsTc MPLS TC (3 bits)
Returns
match criterion
Definition at line 461 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchOchSignalType (OchSignalType signalType) static
Create a match on OCh (Optical Channel) signal type.
Parameters
signalType OCh signal type
Returns
match criterion
Definition at line 508 of file Criteria.java.
Referenced by org.onosproject.codec.impl.IntentCodecTest.intentWithTreatmentSelectorAndConstraints().
static Criterion org.onosproject.net.flow.criteria.Criteria.matchOduSignalId (OduSignalId oduSignalId) static
Creates a match on ODU (Optical channel Data Unit) signal ID using the specified value.
Parameters
oduSignalId ODU Signal Id
Returns
match criterion
Definition at line 518 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchOduSignalType (OduSignalType signalType) static
Creates a match on ODU (Optical channel Data Unit) signal Type using the specified value.
Parameters
signalType ODU Signal Type
Returns
match criterion
Definition at line 528 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchSctpDst (short sctpPort) static
Creates a match on SCTP destination port field using the specified value.
Parameters
sctpPort SCTP destination port
Returns
match criterion
Deprecated:
in Drake release
Definition at line 317 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.SCTP_DST, and org.onlab.packet.TpPort.tpPort().
static Criterion org.onosproject.net.flow.criteria.Criteria.matchSctpDst (TpPort sctpPort) static
Creates a match on SCTP destination port field using the specified value.
Parameters
sctpPort SCTP destination port
Returns
match criterion
Definition at line 328 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.SCTP_DST.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchSctpSrc (short sctpPort) static
Creates a match on SCTP source port field using the specified value.
Parameters
sctpPort SCTP source port
Returns
match criterion
Deprecated:
in Drake release
Definition at line 294 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.SCTP_SRC, and org.onlab.packet.TpPort.tpPort().
static Criterion org.onosproject.net.flow.criteria.Criteria.matchSctpSrc (TpPort sctpPort) static
Creates a match on SCTP source port field using the specified value.
Parameters
sctpPort SCTP source port
Returns
match criterion
Definition at line 304 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.SCTP_SRC.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchTcpDst (short tcpPort) static
Creates a match on TCP destination port field using the specified value.
Parameters
tcpPort TCP destination port
Returns
match criterion
Deprecated:
in Drake release
Definition at line 218 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.TCP_DST, and org.onlab.packet.TpPort.tpPort().
static Criterion org.onosproject.net.flow.criteria.Criteria.matchTcpDst (TpPort tcpPort) static
Creates a match on TCP destination port field using the specified value.
Parameters
tcpPort TCP destination port
Returns
match criterion
Definition at line 228 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.TCP_DST.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchTcpFlags (int flags) static
Creates a match on TCP flags using the specified value.
Parameters
flags TCP flags
Returns
match criterion
Definition at line 238 of file Criteria.java.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchTcpSrc (short tcpPort) static
Creates a match on TCP source port field using the specified value.
Parameters
tcpPort TCP source port
Returns
match criterion
Deprecated:
in Drake release
Definition at line 196 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.TCP_SRC, and org.onlab.packet.TpPort.tpPort().
static Criterion org.onosproject.net.flow.criteria.Criteria.matchTcpSrc (TpPort tcpPort) static
Creates a match on TCP source port field using the specified value.
Parameters
tcpPort TCP source port
Returns
match criterion
Definition at line 206 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.TCP_SRC.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchTunnelId (long tunnelId) static
Creates a match on Tunnel ID.
Parameters
tunnelId Tunnel ID (64 bits)
Returns
match criterion
Definition at line 471 of file Criteria.java.
Referenced by org.onosproject.vtn.table.impl.L2ForwardServiceImpl.programLocalBcastRules().
static Criterion org.onosproject.net.flow.criteria.Criteria.matchUdpDst (short udpPort) static
Creates a match on UDP destination port field using the specified value.
Parameters
udpPort UDP destination port
Returns
match criterion
Deprecated:
in Drake release
Definition at line 272 of file Criteria.java.
References org.onlab.packet.TpPort.tpPort(), and org.onosproject.net.flow.criteria.Criterion.Type.UDP_DST.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchUdpDst (TpPort udpPort) static
Creates a match on UDP destination port field using the specified value.
Parameters
udpPort UDP destination port
Returns
match criterion
Definition at line 282 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.UDP_DST.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchUdpSrc (short udpPort) static
Creates a match on UDP source port field using the specified value.
Parameters
udpPort UDP source port
Returns
match criterion
Deprecated:
in Drake release
Definition at line 250 of file Criteria.java.
References org.onlab.packet.TpPort.tpPort(), and org.onosproject.net.flow.criteria.Criterion.Type.UDP_SRC.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchUdpSrc (TpPort udpPort) static
Creates a match on UDP source port field using the specified value.
Parameters
udpPort UDP source port
Returns
match criterion
Definition at line 260 of file Criteria.java.
References org.onosproject.net.flow.criteria.Criterion.Type.UDP_SRC.
static Criterion org.onosproject.net.flow.criteria.Criteria.matchVlanId (VlanId vlanId) static
Creates a match on VLAN ID field using the specified value.
Parameters
vlanId vlan id value
Returns
match criterion
Definition at line 124 of file Criteria.java.
Referenced by org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterMacVlanFilters(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), and org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstFilter().
static Criterion org.onosproject.net.flow.criteria.Criteria.matchVlanPcp (byte vlanPcp) static
Creates a match on VLAN PCP field using the specified value.
Parameters
vlanPcp vlan pcp value (3 bits)
Returns
match criterion
Definition at line 134 of file Criteria.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/Criteria.java