onos: org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4 Class Reference
org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4 Class Reference
Implementation of Link LS NLRI.
Public Member Functions
BgpLinkLsNlriVer4 ()
Initialize fields.
BgpLinkLsNlriVer4 (byte protocolId, long identifier, BgpLinkLSIdentifier linkLSIdentifier, RouteDistinguisher routeDistinguisher, boolean isVpn)
Constructor to initialize parameters for BGP LinkLSNlri.
NlriType getNlriType ()
Returns NlriType of BGP-LS NLRI.
long getIdentifier ()
Returns Identifier in Nlri.
void setLinkLSIdentifier (BgpLinkLSIdentifier linkLSIdentifier)
Set the link LS identifier.
ProtocolType getProtocolId () throws BgpParseException
Returns Protocol Id in Nlri.
NodeDescriptors localNodeDescriptors ()
Returns local node descriptors.
NodeDescriptors remoteNodeDescriptors ()
Returns remote node descriptors.
boolean isVpnPresent ()
Returns whether VPN is present or not.
RouteDistinguisher getRouteDistinguisher ()
Returns Route distinguisher in Nlri.
BgpLinkLSIdentifier getLinkIdentifier ()
Returns link identifier.
List< BgpValueType > linkDescriptors ()
Returns link descriptors.
String toString ()
Static Public Member Functions
static BgpLinkLsNlriVer4 read (ChannelBuffer cb, short afi, byte safi) throws BgpParseException
Reads from channelBuffer and parses Link LS Nlri.
Static Public Attributes
static final int LINK_NLRITYPE = 2
Detailed Description
Implementation of Link LS NLRI.
Definition at line 37 of file BgpLinkLsNlriVer4.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.BgpLinkLsNlriVer4 ()
Initialize fields.
Definition at line 70 of file BgpLinkLsNlriVer4.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.read().
org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.BgpLinkLsNlriVer4 (byte protocolId, long identifier, BgpLinkLSIdentifier linkLSIdentifier, RouteDistinguisher routeDistinguisher, boolean isVpn)
Constructor to initialize parameters for BGP LinkLSNlri.
Parameters
protocolId protocol Id
identifier field in BGP LinkLSNlri
linkLSIdentifier link LS identifier
routeDistinguisher route distinguisher from message
isVpn vpn info availability in message
Definition at line 87 of file BgpLinkLsNlriVer4.java.
Member Function Documentation
long org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getIdentifier ()
Returns Identifier in Nlri.
Returns
Identifier in Nlri
Implements org.onosproject.bgpio.protocol.BgpLSNlri.
Definition at line 129 of file BgpLinkLsNlriVer4.java.
Referenced by org.onosproject.bgp.controller.BgpDpid.BgpDpid().
BgpLinkLSIdentifier org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getLinkIdentifier ()
Returns link identifier.
Returns
link identifier
Definition at line 191 of file BgpLinkLsNlriVer4.java.
NlriType org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getNlriType ()
Returns NlriType of BGP-LS NLRI.
Returns
NlriType of BGP-LS NLRI
Implements org.onosproject.bgpio.protocol.BgpLSNlri.
Definition at line 124 of file BgpLinkLsNlriVer4.java.
References org.onosproject.bgpio.protocol.NlriType.LINK.
ProtocolType org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getProtocolId () throws BgpParseException
Returns Protocol Id in Nlri.
Returns
Protocol Id in Nlri
Exceptions
BgpParseException while getting protocol ID
Implements org.onosproject.bgpio.protocol.BgpLSNlri.
Definition at line 143 of file BgpLinkLsNlriVer4.java.
References org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.DIRECT, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.ISIS_LEVEL_ONE, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.ISIS_LEVEL_TWO, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.OSPF_V2, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.OSPF_V3, org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.STATIC_CONFIGURATION, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
RouteDistinguisher org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getRouteDistinguisher ()
Returns Route distinguisher in Nlri.
Returns
Route distinguisher in Nlri
Implements org.onosproject.bgpio.protocol.BgpLSNlri.
Definition at line 182 of file BgpLinkLsNlriVer4.java.
Referenced by org.onosproject.bgp.controller.BgpDpid.BgpDpid().
boolean org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.isVpnPresent ()
Returns whether VPN is present or not.
Returns
whether VPN is present or not
Definition at line 177 of file BgpLinkLsNlriVer4.java.
List<BgpValueType> org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.linkDescriptors ()
Returns link descriptors.
Returns
link descriptors
Implements org.onosproject.bgpio.protocol.BgpLinkLsNlri.
Definition at line 196 of file BgpLinkLsNlriVer4.java.
NodeDescriptors org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.localNodeDescriptors ()
Returns local node descriptors.
Returns
local node descriptors
Implements org.onosproject.bgpio.protocol.BgpLinkLsNlri.
Definition at line 163 of file BgpLinkLsNlriVer4.java.
Referenced by org.onosproject.bgp.controller.BgpDpid.BgpDpid().
static BgpLinkLsNlriVer4 org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.read (ChannelBuffer cb, short afi, byte safi) throws BgpParseException static
Reads from channelBuffer and parses Link LS Nlri.
Parameters
cb ChannelBuffer
afi Address Family Identifier
safi Subsequent Address Family Identifier
Returns
object of this class
Exceptions
BgpParseException while parsing Link LS NLRI
Definition at line 105 of file BgpLinkLsNlriVer4.java.
References org.onosproject.bgpio.util.Constants.AFI_VALUE, org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.BgpLinkLsNlriVer4(), and org.onosproject.bgpio.util.Constants.VPN_SAFI_VALUE.
NodeDescriptors org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.remoteNodeDescriptors ()
Returns remote node descriptors.
Returns
remote node descriptors
Implements org.onosproject.bgpio.protocol.BgpLinkLsNlri.
Definition at line 168 of file BgpLinkLsNlriVer4.java.
Referenced by org.onosproject.bgp.controller.BgpDpid.BgpDpid().
void org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.setLinkLSIdentifier (BgpLinkLSIdentifier linkLSIdentifier)
Set the link LS identifier.
Parameters
linkLSIdentifier link LS identifier to set
Definition at line 138 of file BgpLinkLsNlriVer4.java.
String org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.toString ()
Definition at line 201 of file BgpLinkLsNlriVer4.java.
Member Data Documentation
final int org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.LINK_NLRITYPE = 2 static
Definition at line 59 of file BgpLinkLsNlriVer4.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/protocol/linkstate/BgpLinkLsNlriVer4.java