onos: org.onosproject.incubator.net.resource.label.DefaultLabelResource Class Reference
org.onosproject.incubator.net.resource.label.DefaultLabelResource Class Reference
the implementation of a label resource of a device.
Public Member Functions
DefaultLabelResource (String deviceId, long labelResourceId)
Initialize a label resource object.
DefaultLabelResource (DeviceId deviceId, LabelResourceId labelResourceId)
Initialize a label resource object.
DeviceId deviceId ()
Returns device id.
LabelResourceId labelResourceId ()
Returns label resource identifier.
Annotations annotations ()
Returns the key/value annotations.
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
the implementation of a label resource of a device.
Definition at line 30 of file DefaultLabelResource.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.resource.label.DefaultLabelResource.DefaultLabelResource (String deviceId, long labelResourceId)
Initialize a label resource object.
Parameters
deviceId device identifier
labelResourceId label resource id
Definition at line 41 of file DefaultLabelResource.java.
References org.onosproject.incubator.net.resource.label.DefaultLabelResource.deviceId(), and org.onosproject.incubator.net.resource.label.DefaultLabelResource.labelResourceId().
Referenced by org.onosproject.incubator.net.resource.label.DefaultLabelResource.equals().
org.onosproject.incubator.net.resource.label.DefaultLabelResource.DefaultLabelResource (DeviceId deviceId, LabelResourceId labelResourceId)
Initialize a label resource object.
Parameters
deviceId device identifier
labelResourceId label resource id
Definition at line 51 of file DefaultLabelResource.java.
References org.onosproject.incubator.net.resource.label.DefaultLabelResource.deviceId(), and org.onosproject.incubator.net.resource.label.DefaultLabelResource.labelResourceId().
Member Function Documentation
Annotations org.onosproject.incubator.net.resource.label.DefaultLabelResource.annotations ()
Returns the key/value annotations.
Returns
key/value annotations
Implements org.onosproject.net.Annotated.
Definition at line 68 of file DefaultLabelResource.java.
DeviceId org.onosproject.incubator.net.resource.label.DefaultLabelResource.deviceId ()
Returns device id.
Returns
DeviceId
Implements org.onosproject.incubator.net.resource.label.LabelResource.
Definition at line 58 of file DefaultLabelResource.java.
Referenced by org.onosproject.incubator.net.resource.label.DefaultLabelResource.DefaultLabelResource(), org.onosproject.incubator.net.resource.label.DefaultLabelResource.hashCode(), and org.onosproject.incubator.net.resource.label.DefaultLabelResource.toString().
boolean org.onosproject.incubator.net.resource.label.DefaultLabelResource.equals (Object obj)
Definition at line 83 of file DefaultLabelResource.java.
References org.onosproject.incubator.net.resource.label.DefaultLabelResource.DefaultLabelResource(), and find-flow.deviceId.
int org.onosproject.incubator.net.resource.label.DefaultLabelResource.hashCode ()
Definition at line 78 of file DefaultLabelResource.java.
References org.onosproject.incubator.net.resource.label.DefaultLabelResource.deviceId(), and org.onosproject.incubator.net.resource.label.DefaultLabelResource.labelResourceId().
LabelResourceId org.onosproject.incubator.net.resource.label.DefaultLabelResource.labelResourceId ()
Returns label resource identifier.
Returns
resource id
Implements org.onosproject.incubator.net.resource.label.LabelResource.
Definition at line 63 of file DefaultLabelResource.java.
Referenced by org.onosproject.incubator.net.resource.label.DefaultLabelResource.DefaultLabelResource(), org.onosproject.incubator.net.resource.label.DefaultLabelResource.hashCode(), and org.onosproject.incubator.net.resource.label.DefaultLabelResource.toString().
ProviderId org.onosproject.incubator.net.resource.label.DefaultLabelResource.providerId ()
Returns the identifier of the provider which supplied the entity.
Returns
provider identification
Implements org.onosproject.net.Provided.
Definition at line 73 of file DefaultLabelResource.java.
String org.onosproject.incubator.net.resource.label.DefaultLabelResource.toString ()
Definition at line 94 of file DefaultLabelResource.java.
References org.onosproject.incubator.net.resource.label.DefaultLabelResource.deviceId(), and org.onosproject.incubator.net.resource.label.DefaultLabelResource.labelResourceId().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/resource/label/DefaultLabelResource.java