onos: org.onosproject.routing.config.BgpConfigTest Class Reference
org.onosproject.routing.config.BgpConfigTest Class Reference
Public Member Functions
void setUp () throws Exception
void testBgpSpeakers () throws Exception
Tests if speakers can be retrieved from JSON.
void testEmptyBgpSpeakers () throws Exception
Tests if speakers can be retrieved from empty JSON.
void testGetSpeakerWithName () throws Exception
Tests if speaker can be found by name.
void testAddSpeaker () throws Exception
Tests addition of new speaker.
void testAddSpeakerToEmpty () throws Exception
Tests addition of new speaker to empty configuration.
void testRemoveExistingSpeaker () throws Exception
Tests removal of existing speaker.
void testRemoveInexistingSpeaker () throws Exception
Tests removal of non-existing speaker.
void testAddPeerToSpeaker () throws Exception
Tests addition of new speaker.
void testAddExistingPeerToSpeaker () throws Exception
Tests addition of new speaker when peer already exists.
void testGetSpeakerFromPeer () throws Exception
Tests retrieval of speaker based on peering address.
void testRemoveExistingPeerFromSpeaker () throws Exception
Tests removal of peer.
void testRemoveNonExistingPeerFromSpeaker () throws Exception
Tests peer removal when peer does not exist.
void testIsConnectedToPeer ()
Tests if connections to peers are found.
Static Public Attributes
static final IpAddress IP_NON_EXIST = IpAddress.valueOf("10.101.1.1")
static final ConnectPoint CONNECT_POINT1
static final ConnectPoint CONNECT_POINT2
Detailed Description
Definition at line 42 of file BgpConfigTest.java.
Member Function Documentation
void org.onosproject.routing.config.BgpConfigTest.setUp () throws Exception
Definition at line 76 of file BgpConfigTest.java.
void org.onosproject.routing.config.BgpConfigTest.testAddExistingPeerToSpeaker () throws Exception
Tests addition of new speaker when peer already exists.
Definition at line 170 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.getSpeakerWithName(), and onos.size.
void org.onosproject.routing.config.BgpConfigTest.testAddPeerToSpeaker () throws Exception
Tests addition of new speaker.
Definition at line 159 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.getSpeakerWithName(), and onos.size.
void org.onosproject.routing.config.BgpConfigTest.testAddSpeaker () throws Exception
Tests addition of new speaker.
Definition at line 113 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.bgpSpeakers(), and onos.size.
void org.onosproject.routing.config.BgpConfigTest.testAddSpeakerToEmpty () throws Exception
Tests addition of new speaker to empty configuration.
Definition at line 126 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.bgpSpeakers().
void org.onosproject.routing.config.BgpConfigTest.testBgpSpeakers () throws Exception
Tests if speakers can be retrieved from JSON.
Definition at line 88 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.bgpSpeakers().
void org.onosproject.routing.config.BgpConfigTest.testEmptyBgpSpeakers () throws Exception
Tests if speakers can be retrieved from empty JSON.
Definition at line 96 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.bgpSpeakers().
void org.onosproject.routing.config.BgpConfigTest.testGetSpeakerFromPeer () throws Exception
Tests retrieval of speaker based on peering address.
Definition at line 181 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.getSpeakerFromPeer(), and org.onosproject.routing.config.BgpConfigTest.IP_NON_EXIST.
void org.onosproject.routing.config.BgpConfigTest.testGetSpeakerWithName () throws Exception
Tests if speaker can be found by name.
Definition at line 104 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.getSpeakerWithName().
void org.onosproject.routing.config.BgpConfigTest.testIsConnectedToPeer ()
Tests if connections to peers are found.
Definition at line 212 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfigTest.IP_NON_EXIST.
void org.onosproject.routing.config.BgpConfigTest.testRemoveExistingPeerFromSpeaker () throws Exception
Tests removal of peer.
Definition at line 190 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.getSpeakerWithName(), and onos.size.
void org.onosproject.routing.config.BgpConfigTest.testRemoveExistingSpeaker () throws Exception
Tests removal of existing speaker.
Definition at line 137 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.bgpSpeakers(), and onos.size.
void org.onosproject.routing.config.BgpConfigTest.testRemoveInexistingSpeaker () throws Exception
Tests removal of non-existing speaker.
Definition at line 148 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.bgpSpeakers(), and onos.size.
void org.onosproject.routing.config.BgpConfigTest.testRemoveNonExistingPeerFromSpeaker () throws Exception
Tests peer removal when peer does not exist.
Definition at line 201 of file BgpConfigTest.java.
References org.onosproject.routing.config.BgpConfig.getSpeakerWithName(), org.onosproject.routing.config.BgpConfigTest.IP_NON_EXIST, and onos.size.
Member Data Documentation
final ConnectPoint org.onosproject.routing.config.BgpConfigTest.CONNECT_POINT1 static
Initial value:
= ConnectPoint.
            deviceConnectPoint("of:0000000000000001/1")
Definition at line 54 of file BgpConfigTest.java.
final ConnectPoint org.onosproject.routing.config.BgpConfigTest.CONNECT_POINT2 static
Initial value:
= ConnectPoint.
            deviceConnectPoint("of:00000000000000a3/1")
Definition at line 56 of file BgpConfigTest.java.
final IpAddress org.onosproject.routing.config.BgpConfigTest.IP_NON_EXIST = IpAddress.valueOf("10.101.1.1") static
Definition at line 52 of file BgpConfigTest.java.
Referenced by org.onosproject.routing.config.BgpConfigTest.testGetSpeakerFromPeer(), org.onosproject.routing.config.BgpConfigTest.testIsConnectedToPeer(), and org.onosproject.routing.config.BgpConfigTest.testRemoveNonExistingPeerFromSpeaker().
The documentation for this class was generated from the following file:
apps/routing-api/src/test/java/org/onosproject/routing/config/BgpConfigTest.java