onos: org.onlab.stc.StepEvent Class Reference
org.onlab.stc.StepEvent Class Reference
Represents an event of execution of a scenario step or group.
Public Member Functions
StepEvent (String name, long time, Status status, String command)
Creates a new step record.
StepEvent (String name, Status status, String command)
Creates a new step record for non-running status.
String name ()
Returns the test step or test group name.
long time ()
Returns the step event time.
Status status ()
Returns the step completion status.
String command ()
Returns the step command.
String toString ()
Static Public Member Functions
static StepEvent fromString (String string)
Returns a record parsed from the specified string.
Detailed Description
Represents an event of execution of a scenario step or group.
Definition at line 26 of file StepEvent.java.
Constructor & Destructor Documentation
org.onlab.stc.StepEvent.StepEvent (String name, long time, Status status, String command)
Creates a new step record.
Parameters
name test step or group name
time time in millis since start of epoch
status step completion status
command step command
Definition at line 43 of file StepEvent.java.
References org.onlab.stc.StepEvent.command(), org.onlab.stc.StepEvent.name(), org.onlab.stc.StepEvent.status(), and org.onlab.stc.StepEvent.time().
Referenced by org.onlab.stc.StepEvent.fromString().
org.onlab.stc.StepEvent.StepEvent (String name, Status status, String command)
Creates a new step record for non-running status.
Parameters
name test step or group name
status status
command step command
Definition at line 57 of file StepEvent.java.
References org.onlab.stc.StepEvent.name().
Member Function Documentation
String org.onlab.stc.StepEvent.command ()
Returns the step command.
Returns
step command
Definition at line 93 of file StepEvent.java.
Referenced by org.onlab.stc.StepEvent.StepEvent(), and org.onlab.stc.StepEvent.toString().
static StepEvent org.onlab.stc.StepEvent.fromString (String string) static
Returns a record parsed from the specified string.
Parameters
string string encoding
Returns
step record
Definition at line 109 of file StepEvent.java.
References org.onlab.stc.StepEvent.StepEvent(), and org.onlab.stc.Coordinator.Status.WAITING.
String org.onlab.stc.StepEvent.name ()
Returns the test step or test group name.
Returns
step or group name
Definition at line 66 of file StepEvent.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), org.onlab.stc.StepEvent.StepEvent(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onlab.stc.StepEvent.toString().
Status org.onlab.stc.StepEvent.status ()
Returns the step completion status.
Returns
completion status
Definition at line 84 of file StepEvent.java.
Referenced by org.onlab.stc.StepEvent.StepEvent(), and org.onlab.stc.StepEvent.toString().
long org.onlab.stc.StepEvent.time ()
Returns the step event time.
Returns
time in millis since start of epoch
Definition at line 75 of file StepEvent.java.
Referenced by org.onlab.stc.StepEvent.StepEvent(), and org.onlab.stc.StepEvent.toString().
String org.onlab.stc.StepEvent.toString ()
Definition at line 99 of file StepEvent.java.
References org.onlab.stc.StepEvent.command(), org.onlab.stc.StepEvent.name(), org.onlab.stc.StepEvent.status(), and org.onlab.stc.StepEvent.time().
The documentation for this class was generated from the following file:
utils/stc/src/main/java/org/onlab/stc/StepEvent.java