onos: org.onosproject.net.OchPort Class Reference
org.onosproject.net.OchPort Class Reference
Implementation of OCh port (Optical Channel).
Public Member Functions
OchPort (Element element, PortNumber number, boolean isEnabled, OduSignalType signalType, boolean isTunable, OchSignal lambda, Annotations...annotations)
Creates an OCh port in the specified network element.
OduSignalType signalType ()
Returns ODU signal type.
boolean isTunable ()
Returns true if port is wavelength tunable.
OchSignal lambda ()
Returns OCh signal.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.DefaultPort
DefaultPort (Element element, PortNumber number, boolean isEnabled, Annotations...annotations)
Creates a network element attributed to the specified provider.
DefaultPort (Element element, PortNumber number, boolean isEnabled, Type type, long portSpeed, Annotations...annotations)
Creates a network element attributed to the specified provider.
Element element ()
Returns the parent network element to which this port belongs.
PortNumber number ()
Returns the port number.
boolean isEnabled ()
Indicates whether or not the port is currently up and active.
Type type ()
Returns the port type.
long portSpeed ()
Returns the current port speed in Mbps.
int hashCode ()
boolean equals (Object obj)
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractAnnotated
Annotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Static Public Attributes inherited from org.onosproject.net.DefaultPort
static final long DEFAULT_SPEED = 1_000
Default port speed in Mbps.
Protected Member Functions inherited from org.onosproject.net.AbstractAnnotated
AbstractAnnotated ()
AbstractAnnotated (Annotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Implementation of OCh port (Optical Channel).
Also referred to as a line side port (L-port) or narrow band port. See ITU G.709 "Interfaces for the Optical Transport Network (OTN)"
Definition at line 28 of file OchPort.java.
Constructor & Destructor Documentation
org.onosproject.net.OchPort.OchPort (Element element, PortNumber number, boolean isEnabled, OduSignalType signalType, boolean isTunable, OchSignal lambda, Annotations... annotations)
Creates an OCh port in the specified network element.
Parameters
element parent network element
number port number
isEnabled port enabled state
signalType ODU signal type
isTunable tunable wavelength capability
lambda OCh signal
annotations optional key/value annotations
Definition at line 45 of file OchPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.OchPort.isTunable(), org.onosproject.net.Port.Type.OCH, and org.onosproject.net.OchPort.signalType().
Referenced by org.onosproject.net.OchPort.equals().
Member Function Documentation
boolean org.onosproject.net.OchPort.equals (Object obj)
Definition at line 86 of file OchPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultPort.isEnabled(), and org.onosproject.net.OchPort.OchPort().
int org.onosproject.net.OchPort.hashCode ()
Definition at line 81 of file OchPort.java.
References org.onosproject.net.AbstractAnnotated.annotations(), org.onosproject.net.DefaultPort.isEnabled(), org.onosproject.net.OchPort.isTunable(), org.onosproject.net.OchPort.lambda(), org.onosproject.net.DefaultPort.number(), org.onosproject.net.OchPort.signalType(), and org.onosproject.net.DefaultPort.type().
boolean org.onosproject.net.OchPort.isTunable ()
Returns true if port is wavelength tunable.
Returns
tunable wavelength capability
Definition at line 67 of file OchPort.java.
Referenced by org.onosproject.net.OchPort.hashCode(), org.onosproject.net.OchPort.OchPort(), and org.onosproject.net.OchPort.toString().
OchSignal org.onosproject.net.OchPort.lambda ()
Returns OCh signal.
Returns
OCh signal
Definition at line 76 of file OchPort.java.
Referenced by org.onosproject.net.OchPort.hashCode(), and org.onosproject.net.OchPort.toString().
OduSignalType org.onosproject.net.OchPort.signalType ()
Returns ODU signal type.
Returns
ODU signal type
Definition at line 58 of file OchPort.java.
Referenced by org.onosproject.net.OchPort.hashCode(), org.onosproject.net.OchPort.OchPort(), and org.onosproject.net.OchPort.toString().
String org.onosproject.net.OchPort.toString ()
Definition at line 104 of file OchPort.java.
References org.onosproject.net.DefaultPort.element(), org.onosproject.net.DefaultPort.isEnabled(), org.onosproject.net.OchPort.isTunable(), org.onosproject.net.OchPort.lambda(), org.onosproject.net.DefaultPort.number(), org.onosproject.net.OchPort.signalType(), and org.onosproject.net.DefaultPort.type().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/OchPort.java