onos: org.onosproject.xosintegration.VoltTenant Class Reference
org.onosproject.xosintegration.VoltTenant Class Reference
Classes
class Builder
Builder class to allow callers to assemble tenants.
Public Member Functions
String humanReadableName ()
Fetches the name of the tenant.
long id ()
Fetches the ID of the tenant object.
long providerService ()
Fetches the identifier for the provider service.
String serviceSpecificId ()
Fetches the server specific ID (user id).
String vlanId ()
Fetches the vlan id for this tenant.
ConnectPoint port ()
String toString ()
Static Public Member Functions
static Builder builder ()
Fetches a builder to make a tenant.
Detailed Description
Definition at line 21 of file VoltTenant.java.
Member Function Documentation
static Builder org.onosproject.xosintegration.VoltTenant.builder () static
Fetches a builder to make a tenant.
Returns
tenant builder
Definition at line 54 of file VoltTenant.java.
String org.onosproject.xosintegration.VoltTenant.humanReadableName ()
Fetches the name of the tenant.
Returns
human readable name
Definition at line 63 of file VoltTenant.java.
Referenced by org.onosproject.xosintegration.VoltTenant.toString().
long org.onosproject.xosintegration.VoltTenant.id ()
Fetches the ID of the tenant object.
Returns
ID of tenant object.
Definition at line 72 of file VoltTenant.java.
Referenced by org.onosproject.xosintegration.cli.TenantIdCompleter.choices().
ConnectPoint org.onosproject.xosintegration.VoltTenant.port ()
Definition at line 103 of file VoltTenant.java.
Referenced by org.onosproject.xosintegration.VoltTenant.toString().
long org.onosproject.xosintegration.VoltTenant.providerService ()
Fetches the identifier for the provider service.
Returns
provider service ID
Definition at line 81 of file VoltTenant.java.
Referenced by org.onosproject.xosintegration.VoltTenant.toString().
String org.onosproject.xosintegration.VoltTenant.serviceSpecificId ()
Fetches the server specific ID (user id).
Returns
server specific ID
Definition at line 90 of file VoltTenant.java.
Referenced by org.onosproject.xosintegration.VoltTenant.toString().
String org.onosproject.xosintegration.VoltTenant.toString ()
Definition at line 191 of file VoltTenant.java.
References org.onosproject.xosintegration.VoltTenant.humanReadableName(), org.onosproject.xosintegration.VoltTenant.port(), org.onosproject.xosintegration.VoltTenant.providerService(), org.onosproject.xosintegration.VoltTenant.serviceSpecificId(), and org.onosproject.xosintegration.VoltTenant.vlanId().
Referenced by org.onosproject.xosintegration.cli.VoltTenantsListCommand.execute().
String org.onosproject.xosintegration.VoltTenant.vlanId ()
Fetches the vlan id for this tenant.
Returns
VLAN ID
Definition at line 99 of file VoltTenant.java.
Referenced by org.onosproject.xosintegration.VoltTenant.toString().
The documentation for this class was generated from the following file:
apps/xos-integration/src/main/java/org/onosproject/xosintegration/VoltTenant.java