onos: org.onosproject.net.flow.criteria.UdpPortCriterion Class Reference
org.onosproject.net.flow.criteria.UdpPortCriterion Class Reference
Implementation of UDP port criterion (16 bits unsigned integer).
Public Member Functions
Type type ()
Returns the type of criterion.
TpPort udpPort ()
Gets the UDP port to match.
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Implementation of UDP port criterion (16 bits unsigned integer).
Definition at line 27 of file UdpPortCriterion.java.
Member Function Documentation
boolean org.onosproject.net.flow.criteria.UdpPortCriterion.equals (Object obj)
Definition at line 69 of file UdpPortCriterion.java.
References org.onosproject.net.flow.criteria.UdpPortCriterion.udpPort().
int org.onosproject.net.flow.criteria.UdpPortCriterion.hashCode ()
Definition at line 64 of file UdpPortCriterion.java.
References org.onosproject.net.flow.criteria.UdpPortCriterion.type().
String org.onosproject.net.flow.criteria.UdpPortCriterion.toString ()
Definition at line 58 of file UdpPortCriterion.java.
References org.onosproject.net.flow.criteria.UdpPortCriterion.type(), and org.onosproject.net.flow.criteria.UdpPortCriterion.udpPort().
Type org.onosproject.net.flow.criteria.UdpPortCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 44 of file UdpPortCriterion.java.
Referenced by org.onosproject.net.flow.criteria.UdpPortCriterion.hashCode(), and org.onosproject.net.flow.criteria.UdpPortCriterion.toString().
TpPort org.onosproject.net.flow.criteria.UdpPortCriterion.udpPort ()
Gets the UDP port to match.
Returns
the UDP port to match
Definition at line 53 of file UdpPortCriterion.java.
Referenced by org.onosproject.net.flow.criteria.UdpPortCriterion.equals(), and org.onosproject.net.flow.criteria.UdpPortCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/UdpPortCriterion.java