onos: org.onosproject.segmentrouting.SubnetAssignedVidStoreKey Class Reference
org.onosproject.segmentrouting.SubnetAssignedVidStoreKey Class Reference
Class definition for key used to map per device subnets to assigned Vlan ids.
Public Member Functions
SubnetAssignedVidStoreKey (DeviceId deviceId, Ip4Prefix subnet)
DeviceId deviceId ()
Returns the device identification used to create this key.
Ip4Prefix subnet ()
Returns the subnet information used to create this key.
boolean equals (Object o)
int hashCode ()
String toString ()
Detailed Description
Class definition for key used to map per device subnets to assigned Vlan ids.
Definition at line 12 of file SubnetAssignedVidStoreKey.java.
Constructor & Destructor Documentation
org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.SubnetAssignedVidStoreKey (DeviceId deviceId, Ip4Prefix subnet)
Definition at line 16 of file SubnetAssignedVidStoreKey.java.
References org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.deviceId(), and org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.subnet().
Referenced by org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.equals().
Member Function Documentation
DeviceId org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.deviceId ()
Returns the device identification used to create this key.
Returns
the device identifier
Definition at line 26 of file SubnetAssignedVidStoreKey.java.
Referenced by org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.hashCode(), org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.SubnetAssignedVidStoreKey(), and org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.toString().
boolean org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.equals (Object o)
Definition at line 40 of file SubnetAssignedVidStoreKey.java.
References org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.SubnetAssignedVidStoreKey().
int org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.hashCode ()
Definition at line 54 of file SubnetAssignedVidStoreKey.java.
References org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.deviceId(), and org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.subnet().
Ip4Prefix org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.subnet ()
Returns the subnet information used to create this key.
Returns
the subnet
Definition at line 35 of file SubnetAssignedVidStoreKey.java.
Referenced by org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.hashCode(), org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.SubnetAssignedVidStoreKey(), and org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.toString().
String org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.toString ()
Definition at line 62 of file SubnetAssignedVidStoreKey.java.
References org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.deviceId(), and org.onosproject.segmentrouting.SubnetAssignedVidStoreKey.subnet().
The documentation for this class was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/SubnetAssignedVidStoreKey.java