onos: org.onosproject.cord.gui.model.UrlFilterFunction Class Reference
org.onosproject.cord.gui.model.UrlFilterFunction Class Reference
Specialization of XosFunction for URL filtering.
Classes
enum Level
Denotes the URL filtering levels available.
class UrlFilterMemento
Public Member Functions
UrlFilterFunction ()
void applyParam (SubscriberUser user, String param, String value)
Applies a parameter change for the given user.
Memento createMemento ()
Create an initialized memento.
String xosUrlApply (SubscriberUser user)
Create the XOS specific URL suffix for applying state change for the given user.
Public Member Functions inherited from org.onosproject.cord.gui.model.DefaultXosFunction
DefaultXosFunction (XosFunctionDescriptor xfd)
XosFunctionDescriptor descriptor ()
Returns the descriptor for this function.
void applyParam (SubscriberUser user, String param, String value)
Applies a parameter change for the given user.
Parameters
user user to apply change to
param parameter name
value new parameter value
Memento createMemento ()
Create an initialized memento.
String xosUrlApply (SubscriberUser user)
Create the XOS specific URL suffix for applying state change for the given user.
String toString ()
Static Public Attributes
static final Level DEFAULT_LEVEL = Level.G
The default URL filtering level.
Additional Inherited Members
Static Protected Attributes inherited from org.onosproject.cord.gui.model.DefaultXosFunction
static final ObjectMapper MAPPER = new ObjectMapper()
Detailed Description
Specialization of XosFunction for URL filtering.
Definition at line 27 of file UrlFilterFunction.java.
Constructor & Destructor Documentation
org.onosproject.cord.gui.model.UrlFilterFunction.UrlFilterFunction ()
Definition at line 44 of file UrlFilterFunction.java.
References org.onosproject.cord.gui.model.XosFunctionDescriptor.URL_FILTER.
Member Function Documentation
void org.onosproject.cord.gui.model.UrlFilterFunction.applyParam (SubscriberUser user, String param, String value)
Applies a parameter change for the given user.
Parameters
user user to apply change to
param parameter name
value new parameter value
Implements org.onosproject.cord.gui.model.XosFunction.
Definition at line 49 of file UrlFilterFunction.java.
References org.onosproject.cord.gui.model.DefaultXosFunction.descriptor().
Memento org.onosproject.cord.gui.model.UrlFilterFunction.createMemento ()
Create an initialized memento.
If the function maintains no state per user, return null.
Returns
a new memento
Implements org.onosproject.cord.gui.model.XosFunction.
Definition at line 65 of file UrlFilterFunction.java.
Referenced by org.onosproject.cord.gui.model.UrlFilterFunctionTest.applyMemo().
String org.onosproject.cord.gui.model.UrlFilterFunction.xosUrlApply (SubscriberUser user)
Create the XOS specific URL suffix for applying state change for the given user.
Parameters
user the user
Returns
URL suffix
Implements org.onosproject.cord.gui.model.XosFunction.
Definition at line 88 of file UrlFilterFunction.java.
References org.onosproject.cord.gui.model.SubscriberUser.getMemento(), and org.onosproject.cord.gui.model.XosFunctionDescriptor.URL_FILTER.
Referenced by org.onosproject.cord.gui.model.UrlFilterFunctionTest.applyMemo().
Member Data Documentation
final Level org.onosproject.cord.gui.model.UrlFilterFunction.DEFAULT_LEVEL = Level.G static
The default URL filtering level.
Definition at line 42 of file UrlFilterFunction.java.
The documentation for this class was generated from the following file:
apps/demo/cord-gui/src/main/java/org/onosproject/cord/gui/model/UrlFilterFunction.java