onos: org.onlab.packet.Data Class Reference
org.onlab.packet.Data Class Reference
Public Member Functions
Data ()
Data (final byte[] data)
byte[] getData ()
Data setData (final byte[] data)
byte[] serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
IPacket deserialize (final byte[] data, final int offset, final int length)
int hashCode ()
boolean equals (final Object obj)
Public Member Functions inherited from org.onlab.packet.BasePacket
IPacket getParent ()
IPacket setParent (final IPacket parent)
IPacket getPayload ()
IPacket setPayload (final IPacket payload)
void resetChecksum ()
Reset any checksums as needed, and call resetChecksum on all parents.
int hashCode ()
boolean equals (final Object obj)
Object clone ()
Clone this packet and its payload packet but not its parent.
Public Member Functions inherited from org.onlab.packet.IPacket
IPacket setPayload (IPacket packet)
IPacket setParent (IPacket packet)
IPacket deserialize (byte[] data, int offset, int length)
Deserializes this packet layer and all possible payloads.
Static Public Member Functions
static Deserializer< Data > deserializer ()
Deserializer function for generic payload data.
Protected Attributes
byte[] data
Protected Attributes inherited from org.onlab.packet.BasePacket
IPacket parent
IPacket payload
Detailed Description
Definition at line 28 of file Data.java.
Constructor & Destructor Documentation
org.onlab.packet.Data.Data ()
Definition at line 34 of file Data.java.
References org.onlab.packet.Data.data.
Referenced by org.onlab.packet.Data.deserializer(), and org.onlab.packet.Data.equals().
org.onlab.packet.Data.Data (final byte[] data)
Parameters
data the data
Definition at line 41 of file Data.java.
References org.onlab.packet.Data.data.
Member Function Documentation
IPacket org.onlab.packet.Data.deserialize (final byte[] data, final int offset, final int length)
Definition at line 68 of file Data.java.
References org.onlab.packet.Data.data, and find-link-in-cluster.length.
static Deserializer<Data> org.onlab.packet.Data.deserializer () static
Deserializer function for generic payload data.
Returns
deserializer function
Definition at line 115 of file Data.java.
References org.onlab.packet.Data.data, org.onlab.packet.Data.Data(), and find-link-in-cluster.length.
boolean org.onlab.packet.Data.equals (final Object obj)
Definition at line 93 of file Data.java.
References org.onlab.packet.Data.data, and org.onlab.packet.Data.Data().
byte [] org.onlab.packet.Data.getData ()
Returns
the data
Definition at line 48 of file Data.java.
int org.onlab.packet.Data.hashCode ()
Definition at line 80 of file Data.java.
byte [] org.onlab.packet.Data.serialize ()
Sets all payloads parent packet if applicable, then serializes this packet and all payloads.
Returns
a byte[] containing this packet and payloads
Implements org.onlab.packet.IPacket.
Definition at line 63 of file Data.java.
Data org.onlab.packet.Data.setData (final byte[] data)
Parameters
data the data to set
Returns
self
Definition at line 57 of file Data.java.
References org.onlab.packet.Data.data.
Member Data Documentation
byte [] org.onlab.packet.Data.data protected
Definition at line 29 of file Data.java.
Referenced by org.onlab.packet.Data.Data(), org.onlab.packet.Data.deserialize(), org.onlab.packet.Data.deserializer(), org.onlab.packet.Data.equals(), and org.onlab.packet.Data.setData().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/Data.java