onos: org.onosproject.net.resource.link.DefaultLinkResourceRequest Class Reference
org.onosproject.net.resource.link.DefaultLinkResourceRequest Class Reference
Implementation of LinkResourceRequest.
Classes
class Builder
Builder of link resource request.
Public Member Functions
ResourceType type ()
Returns the resource type.
IntentId intentId ()
Returns the IntentId associated with the request.
Collection< Link > links ()
Returns the set of target links.
Set< ResourceRequest > resources ()
Returns the set of resource requests.
Set< ResourceRequest > resources (Link link)
Returns the set of resource request against the specified link.
int hashCode ()
boolean equals (Object obj)
Static Public Member Functions
static LinkResourceRequest.Builder builder (IntentId intentId, Collection< Link > links)
Returns builder of link resource request.
Protected Attributes
final Map< Link, Set
< ResourceRequest > > requests
Detailed Description
Implementation of LinkResourceRequest.
Deprecated:
in Emu Release
Definition at line 46 of file DefaultLinkResourceRequest.java.
Member Function Documentation
static LinkResourceRequest.Builder org.onosproject.net.resource.link.DefaultLinkResourceRequest.builder (IntentId intentId, Collection< Link > links) static
Returns builder of link resource request.
Parameters
intentId intent ID related to this request
links a set of links for the request
Returns
builder of link resource request
Definition at line 97 of file DefaultLinkResourceRequest.java.
Referenced by org.onosproject.store.serializers.KryoSerializerTest.testDefaultLinkResourceRequest().
boolean org.onosproject.net.resource.link.DefaultLinkResourceRequest.equals (Object obj)
Definition at line 226 of file DefaultLinkResourceRequest.java.
References org.onosproject.net.resource.link.DefaultLinkResourceRequest.equals().
Referenced by org.onosproject.net.resource.link.DefaultLinkResourceRequest.equals().
int org.onosproject.net.resource.link.DefaultLinkResourceRequest.hashCode ()
Definition at line 221 of file DefaultLinkResourceRequest.java.
References org.onosproject.net.resource.link.DefaultLinkResourceRequest.intentId(), and org.onosproject.net.resource.link.DefaultLinkResourceRequest.links().
IntentId org.onosproject.net.resource.link.DefaultLinkResourceRequest.intentId ()
Returns the IntentId associated with the request.
Returns
the IntentId associated with the request
Implements org.onosproject.net.resource.link.LinkResourceRequest.
Definition at line 69 of file DefaultLinkResourceRequest.java.
Referenced by org.onosproject.net.resource.link.DefaultLinkResourceRequest.hashCode().
Collection<Link> org.onosproject.net.resource.link.DefaultLinkResourceRequest.links ()
Returns the set of target links.
Returns
the set of target links
Implements org.onosproject.net.resource.link.LinkResourceRequest.
Definition at line 74 of file DefaultLinkResourceRequest.java.
Referenced by org.onosproject.net.resource.link.DefaultLinkResourceRequest.hashCode().
Set<ResourceRequest> org.onosproject.net.resource.link.DefaultLinkResourceRequest.resources ()
Returns the set of resource requests.
Returns
the set of resource requests
Implements org.onosproject.net.resource.link.LinkResourceRequest.
Definition at line 79 of file DefaultLinkResourceRequest.java.
Set<ResourceRequest> org.onosproject.net.resource.link.DefaultLinkResourceRequest.resources (Link link)
Returns the set of resource request against the specified link.
Parameters
link link whose associated resource request is to be returned
Returns
set of resource request against the specified link
Implements org.onosproject.net.resource.link.LinkResourceRequest.
Definition at line 86 of file DefaultLinkResourceRequest.java.
ResourceType org.onosproject.net.resource.link.DefaultLinkResourceRequest.type ()
Returns the resource type.
Returns
the resource type
Implements org.onosproject.net.resource.ResourceRequest.
Definition at line 64 of file DefaultLinkResourceRequest.java.
Member Data Documentation
final Map<Link, Set<ResourceRequest> > org.onosproject.net.resource.link.DefaultLinkResourceRequest.requests protected
Definition at line 49 of file DefaultLinkResourceRequest.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/resource/link/DefaultLinkResourceRequest.java