onos: org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil Class Reference
org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil Class Reference
Provide util functions for FlowObjectiveComposition.
Static Public Member Functions
static ForwardingObjective composeParallel (ForwardingObjective fo1, ForwardingObjective fo2)
static ForwardingObjective composeSequential (ForwardingObjective fo1, ForwardingObjective fo2, int priorityMultiplier)
static ForwardingObjective composeOverride (ForwardingObjective fo, int priorityAddend)
static TrafficSelector intersectTrafficSelector (TrafficSelector ts1, TrafficSelector ts2)
static TrafficTreatment unionTrafficTreatment (TrafficTreatment tt1, TrafficTreatment tt2)
static TrafficSelector revertTreatmentSelector (TrafficTreatment trafficTreatment, TrafficSelector trafficSelector)
static Set< Criterion.Type > getTypeSet (TrafficSelector trafficSelector)
static Criterion intersectCriterion (Criterion c1, Criterion c2)
static IpPrefix intersectIpPrefix (IpPrefix ip1, IpPrefix ip2)
static FlowObjectiveCompositionTree parsePolicyString (String policy)
static Collection
< ForwardingObjective > minusForwardingObjectives (Collection< ForwardingObjective > fo1, Collection< ForwardingObjective > fo2)
Detailed Description
Provide util functions for FlowObjectiveComposition.
Definition at line 54 of file FlowObjectiveCompositionUtil.java.
Member Function Documentation
static ForwardingObjective org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeOverride (ForwardingObjective fo, int priorityAddend) static
Definition at line 104 of file FlowObjectiveCompositionUtil.java.
References org.onosproject.net.flowobjective.Objective.appId().
static ForwardingObjective org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeParallel (ForwardingObjective fo1, ForwardingObjective fo2) static
Definition at line 59 of file FlowObjectiveCompositionUtil.java.
References org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectTrafficSelector(), org.onosproject.net.flowobjective.Objective.priority(), org.onosproject.net.flowobjective.ForwardingObjective.selector(), org.onosproject.net.flowobjective.ForwardingObjective.treatment(), and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.unionTrafficTreatment().
static ForwardingObjective org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeSequential (ForwardingObjective fo1, ForwardingObjective fo2, int priorityMultiplier) static
Definition at line 78 of file FlowObjectiveCompositionUtil.java.
References org.onosproject.net.flowobjective.Objective.appId(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectTrafficSelector(), org.onosproject.net.flowobjective.Objective.priority(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.revertTreatmentSelector(), org.onosproject.net.flowobjective.ForwardingObjective.selector(), org.onosproject.net.flowobjective.ForwardingObjective.treatment(), and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.unionTrafficTreatment().
static Set<Criterion.Type> org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.getTypeSet (TrafficSelector trafficSelector) static
Definition at line 368 of file FlowObjectiveCompositionUtil.java.
References org.onosproject.net.flow.TrafficSelector.criteria().
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectTrafficSelector().
static Criterion org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectCriterion (Criterion c1, Criterion c2) static
Definition at line 376 of file FlowObjectiveCompositionUtil.java.
References org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectIpPrefix(), and org.onosproject.net.flow.criteria.Criterion.type().
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectTrafficSelector().
static IpPrefix org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectIpPrefix (IpPrefix ip1, IpPrefix ip2) static
Definition at line 419 of file FlowObjectiveCompositionUtil.java.
References org.onlab.packet.IpPrefix.contains().
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectCriterion().
static TrafficSelector org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectTrafficSelector (TrafficSelector ts1, TrafficSelector ts2) static
Definition at line 115 of file FlowObjectiveCompositionUtil.java.
References org.onosproject.net.flow.TrafficSelector.getCriterion(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.getTypeSet(), and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectCriterion().
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeParallel(), and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeSequential().
static Collection<ForwardingObjective> org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.minusForwardingObjectives (Collection< ForwardingObjective > fo1, Collection< ForwardingObjective > fo2) static
Definition at line 495 of file FlowObjectiveCompositionUtil.java.
static FlowObjectiveCompositionTree org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.parsePolicyString (String policy) static
Definition at line 429 of file FlowObjectiveCompositionUtil.java.
static TrafficSelector org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.revertTreatmentSelector (TrafficTreatment trafficTreatment, TrafficSelector trafficSelector) static
Definition at line 161 of file FlowObjectiveCompositionUtil.java.
References org.onosproject.net.flow.TrafficTreatment.allInstructions(), org.onosproject.net.flow.TrafficSelector.criteria(), obeliskHostCheck.mac, org.onosproject.net.flow.instructions.L1ModificationInstruction.subtype(), org.onosproject.net.flow.instructions.L0ModificationInstruction.subtype(), org.onosproject.net.flow.instructions.L3ModificationInstruction.subtype(), and org.onosproject.net.flow.instructions.L2ModificationInstruction.subtype().
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeSequential().
static TrafficTreatment org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.unionTrafficTreatment (TrafficTreatment tt1, TrafficTreatment tt2) static
Definition at line 145 of file FlowObjectiveCompositionUtil.java.
References org.onosproject.net.flow.TrafficTreatment.allInstructions().
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeParallel(), and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeSequential().
The documentation for this class was generated from the following file:
core/net/src/main/java/org/onosproject/net/flowobjective/impl/composition/FlowObjectiveCompositionUtil.java