onos: org.onosproject.openstackswitching.OpenstackRestHandler Class Reference
org.onosproject.openstackswitching.OpenstackRestHandler Class Reference
Handles REST Calls to Openstack Neutron.
Public Member Functions
OpenstackRestHandler (OpenstackSwitchingConfig cfg)
Creates OpenstackRestHandler instance.
Collection< OpenstackNetwork > getNetworks ()
Returns network information stored in Neutron.
Collection< OpenstackPort > getPorts ()
Returns port information stored in Neutron.
Collection< OpenstackSubnet > getSubnets ()
Returns Subnet information in Neutron.
Detailed Description
Handles REST Calls to Openstack Neutron.
Definition at line 41 of file OpenstackRestHandler.java.
Constructor & Destructor Documentation
org.onosproject.openstackswitching.OpenstackRestHandler.OpenstackRestHandler (OpenstackSwitchingConfig cfg)
Creates OpenstackRestHandler instance.
Parameters
cfg OpenstackSwitchingConfig reference
Definition at line 55 of file OpenstackRestHandler.java.
References org.onosproject.openstackswitching.OpenstackSwitchingConfig.keystoneServer(), org.onosproject.openstackswitching.OpenstackSwitchingConfig.neutronServer(), org.onosproject.openstackswitching.OpenstackSwitchingConfig.password(), and org.onosproject.openstackswitching.OpenstackSwitchingConfig.userName().
Member Function Documentation
Collection<OpenstackNetwork> org.onosproject.openstackswitching.OpenstackRestHandler.getNetworks ()
Returns network information stored in Neutron.
Returns
List of OpenstackNetwork
Definition at line 67 of file OpenstackRestHandler.java.
References optical.n, and create-flow.node.
Collection<OpenstackPort> org.onosproject.openstackswitching.OpenstackRestHandler.getPorts ()
Returns port information stored in Neutron.
Returns
List of OpenstackPort
Definition at line 95 of file OpenstackRestHandler.java.
References optical.n, and create-flow.node.
Collection<OpenstackSubnet> org.onosproject.openstackswitching.OpenstackRestHandler.getSubnets ()
Returns Subnet information in Neutron.
Returns
List of OpenstackSubnet
Definition at line 123 of file OpenstackRestHandler.java.
References create-flow.node.
The documentation for this class was generated from the following file:
apps/openstackswitching/app/src/main/java/org/onosproject/openstackswitching/OpenstackRestHandler.java