onos: org.onosproject.ovsdb.rfc.notation.RefTableRow Class Reference
org.onosproject.ovsdb.rfc.notation.RefTableRow Class Reference
The RefTable type that can be expanded to Row.
Public Member Functions
RefTableRow (String refTable, JsonNode jsonNode)
RefTableRow constructor.
JsonNode jsonNode ()
Returns JsonNode.
String refTable ()
Returns refTable.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
The RefTable type that can be expanded to Row.
Refer to RFC 7047 Section 3.2.
Definition at line 28 of file RefTableRow.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.notation.RefTableRow.RefTableRow (String refTable, JsonNode jsonNode)
RefTableRow constructor.
Parameters
refTable the refTable value of JsonNode
jsonNode JsonNode
Definition at line 38 of file RefTableRow.java.
References org.onosproject.ovsdb.rfc.notation.RefTableRow.jsonNode(), and org.onosproject.ovsdb.rfc.notation.RefTableRow.refTable().
Referenced by org.onosproject.ovsdb.rfc.notation.RefTableRow.equals().
Member Function Documentation
boolean org.onosproject.ovsdb.rfc.notation.RefTableRow.equals (Object obj)
Definition at line 67 of file RefTableRow.java.
References org.onosproject.ovsdb.rfc.notation.RefTableRow.RefTableRow().
int org.onosproject.ovsdb.rfc.notation.RefTableRow.hashCode ()
Definition at line 62 of file RefTableRow.java.
References org.onosproject.ovsdb.rfc.notation.RefTableRow.jsonNode(), and org.onosproject.ovsdb.rfc.notation.RefTableRow.refTable().
JsonNode org.onosproject.ovsdb.rfc.notation.RefTableRow.jsonNode ()
Returns JsonNode.
Returns
JsonNode
Definition at line 49 of file RefTableRow.java.
Referenced by org.onosproject.ovsdb.rfc.notation.RefTableRow.hashCode(), org.onosproject.ovsdb.rfc.notation.RefTableRow.RefTableRow(), and org.onosproject.ovsdb.rfc.notation.RefTableRow.toString().
String org.onosproject.ovsdb.rfc.notation.RefTableRow.refTable ()
Returns refTable.
Returns
refTable
Definition at line 57 of file RefTableRow.java.
Referenced by org.onosproject.ovsdb.rfc.notation.RefTableRow.hashCode(), org.onosproject.ovsdb.rfc.notation.RefTableRow.RefTableRow(), and org.onosproject.ovsdb.rfc.notation.RefTableRow.toString().
String org.onosproject.ovsdb.rfc.notation.RefTableRow.toString ()
Definition at line 80 of file RefTableRow.java.
References org.onosproject.ovsdb.rfc.notation.RefTableRow.jsonNode(), and org.onosproject.ovsdb.rfc.notation.RefTableRow.refTable().
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/notation/RefTableRow.java