onos: org.onosproject.store.app.GossipApplicationStore Class Reference
org.onosproject.store.app.GossipApplicationStore Class Reference
Manages inventory of applications in a distributed data store that uses optimistic replication and gossip based anti-entropy techniques.
Classes
enum InternalState
Public Member Functions
void activate ()
void deactivate ()
void setDelegate (ApplicationStoreDelegate delegate)
Set< Application > getApplications ()
Returns the set of all installed applications.
ApplicationId getId (String name)
Returns the registered id of the application with the given name.
Application getApplication (ApplicationId appId)
Returns the application with the supplied application identifier.
ApplicationState getState (ApplicationId appId)
Returns the current application state.
Application create (InputStream appDescStream)
Creates the application from the specified application descriptor input stream.
void remove (ApplicationId appId)
Removes the specified application.
void activate (ApplicationId appId)
Mark the application as active.
void deactivate (ApplicationId appId)
Mark the application as deactivated.
Set< Permission > getPermissions (ApplicationId appId)
Returns the permissions granted to the applications.
void setPermissions (ApplicationId appId, Set< Permission > permissions)
Updates the permissions granted to the applications.
Public Member Functions inherited from org.onosproject.common.app.ApplicationArchive
String getRootPath ()
Returns the root directory where apps directory is contained.
Set< String > getApplicationNames ()
Returns the set of installed application names.
long getUpdateTime (String appName)
Returns the timestamp in millis since start of epoch, of when the specified application was last modified or changed state.
ApplicationDescription getApplicationDescription (String appName)
Loads the application descriptor from the specified application archive stream and saves the stream in the appropriate application archive directory.
synchronized ApplicationDescription saveApplication (InputStream stream)
Loads the application descriptor from the specified application archive stream and saves the stream in the appropriate application archive directory.
synchronized void purgeApplication (String appName)
Purges the application archive directory.
synchronized InputStream getApplicationInputStream (String appName)
Returns application archive stream for the specified application.
ApplicationRole getRole (String value)
Protected Attributes
ClusterCommunicationService clusterCommunicator
ClusterService clusterService
StorageService storageService
LogicalClockService clockService
ApplicationIdStore idStore
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.common.app.ApplicationArchive
void setRootPath (String root)
Sets the root directory where apps directory is contained.
boolean setActive (String appName)
Marks the app as active by creating token file in the app directory.
boolean clearActive (String appName)
Clears the app as active by deleting token file in the app directory.
boolean updateTime (String appName)
Updates the time-stamp of the app descriptor file.
boolean isActive (String appName)
Indicates whether the app was marked as active by checking for token file.
Detailed Description
Manages inventory of applications in a distributed data store that uses optimistic replication and gossip based anti-entropy techniques.
Definition at line 85 of file GossipApplicationStore.java.
Member Function Documentation
void org.onosproject.store.app.GossipApplicationStore.activate ()
Definition at line 132 of file GossipApplicationStore.java.
References org.onosproject.store.serializers.KryoNamespaces.API, org.onosproject.common.app.ApplicationArchive.getApplicationInputStream(), and create-flow.name.
void org.onosproject.store.app.GossipApplicationStore.activate (ApplicationId appId)
Mark the application as active.
Parameters
appId application identifier
Implements org.onosproject.app.ApplicationStore.
Definition at line 299 of file GossipApplicationStore.java.
Application org.onosproject.store.app.GossipApplicationStore.create (InputStream appDescStream)
Creates the application from the specified application descriptor input stream.
Parameters
appDescStream application archive input stream
Returns
application descriptor
Implements org.onosproject.app.ApplicationStore.
Definition at line 257 of file GossipApplicationStore.java.
References org.onosproject.app.ApplicationDescription.name().
void org.onosproject.store.app.GossipApplicationStore.deactivate ()
Definition at line 217 of file GossipApplicationStore.java.
void org.onosproject.store.app.GossipApplicationStore.deactivate (ApplicationId appId)
Mark the application as deactivated.
Parameters
appId application identifier
Implements org.onosproject.app.ApplicationStore.
Definition at line 326 of file GossipApplicationStore.java.
Application org.onosproject.store.app.GossipApplicationStore.getApplication (ApplicationId appId)
Returns the application with the supplied application identifier.
Parameters
appId application identifier
Returns
application descriptor
Implements org.onosproject.app.ApplicationStore.
Definition at line 244 of file GossipApplicationStore.java.
Set<Application> org.onosproject.store.app.GossipApplicationStore.getApplications ()
Returns the set of all installed applications.
Returns
set of installed apps
Implements org.onosproject.app.ApplicationStore.
Definition at line 234 of file GossipApplicationStore.java.
ApplicationId org.onosproject.store.app.GossipApplicationStore.getId (String name)
Returns the registered id of the application with the given name.
Parameters
name application name
Returns
registered application id
Implements org.onosproject.app.ApplicationStore.
Definition at line 239 of file GossipApplicationStore.java.
References create-flow.name.
Referenced by metro.FabricDomain.build().
Set<Permission> org.onosproject.store.app.GossipApplicationStore.getPermissions (ApplicationId appId)
Returns the permissions granted to the applications.
Parameters
appId application identifier
Returns
set of granted permissions
Implements org.onosproject.app.ApplicationStore.
Definition at line 359 of file GossipApplicationStore.java.
ApplicationState org.onosproject.store.app.GossipApplicationStore.getState (ApplicationId appId)
Returns the current application state.
Parameters
appId application identifier
Returns
application state
Implements org.onosproject.app.ApplicationStore.
Definition at line 249 of file GossipApplicationStore.java.
void org.onosproject.store.app.GossipApplicationStore.remove (ApplicationId appId)
Removes the specified application.
Parameters
appId application identifier
Implements org.onosproject.app.ApplicationStore.
Definition at line 281 of file GossipApplicationStore.java.
void org.onosproject.store.app.GossipApplicationStore.setDelegate (ApplicationStoreDelegate delegate)
Definition at line 228 of file GossipApplicationStore.java.
void org.onosproject.store.app.GossipApplicationStore.setPermissions (ApplicationId appId, Set< Permission > permissions)
Updates the permissions granted to the applications.
Parameters
appId application identifier
permissions set of granted permissions
Implements org.onosproject.app.ApplicationStore.
Definition at line 365 of file GossipApplicationStore.java.
Member Data Documentation
LogicalClockService org.onosproject.store.app.GossipApplicationStore.clockService protected
Definition at line 118 of file GossipApplicationStore.java.
ClusterCommunicationService org.onosproject.store.app.GossipApplicationStore.clusterCommunicator protected
Definition at line 109 of file GossipApplicationStore.java.
ClusterService org.onosproject.store.app.GossipApplicationStore.clusterService protected
Definition at line 112 of file GossipApplicationStore.java.
ApplicationIdStore org.onosproject.store.app.GossipApplicationStore.idStore protected
Definition at line 121 of file GossipApplicationStore.java.
StorageService org.onosproject.store.app.GossipApplicationStore.storageService protected
Definition at line 115 of file GossipApplicationStore.java.
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/app/GossipApplicationStore.java