onos: org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv Class Reference
org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv Class Reference
Provides IPv6 TE Router Id of Remote Node.
Public Member Functions
IPv6TERouterIdofRemoteNodeTlv (byte[] rawValue)
constructor to initialize rawValue.
byte[] getBytes ()
Returns value of IPv6 TE Router Id of Remote Node.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static
IPv6TERouterIdofRemoteNodeTlv of (final byte[] raw)
Returns newly created IPv6TERouterIdofRemoteNodeTlv object.
static
IPv6TERouterIdofRemoteNodeTlv read20Bytes (ChannelBuffer c)
Reads the channel buffer and returns object of IPv6TERouterIdofRemoteNodeTlv.
Static Public Attributes
static final short TYPE = 1400
static final short LENGTH = 20
static final byte VALUE_LENGTH = 18
static final
IPv6TERouterIdofRemoteNodeTlv NONE = new IPv6TERouterIdofRemoteNodeTlv(NONE_VAL)
static final
IPv6TERouterIdofRemoteNodeTlv NO_MASK = new IPv6TERouterIdofRemoteNodeTlv(NO_MASK_VAL)
static final
IPv6TERouterIdofRemoteNodeTlv FULL_MASK = NONE
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IPv6TERouterIdofRemoteNodeTlv.class)
Detailed Description
Provides IPv6 TE Router Id of Remote Node.
Reference :[RFC6119]/4.1.
Definition at line 31 of file IPv6TERouterIdofRemoteNodeTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.IPv6TERouterIdofRemoteNodeTlv (byte[] rawValue)
constructor to initialize rawValue.
Parameters
rawValue IPv6TERouterIdofRemoteNodeTlv
Definition at line 54 of file IPv6TERouterIdofRemoteNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.equals(), and org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.equals (Object obj)
Definition at line 124 of file IPv6TERouterIdofRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.IPv6TERouterIdofRemoteNodeTlv().
byte [] org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.getBytes ()
Returns value of IPv6 TE Router Id of Remote Node.
Returns
byte array value of rawValue
Definition at line 99 of file IPv6TERouterIdofRemoteNodeTlv.java.
short org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 114 of file IPv6TERouterIdofRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.LENGTH.
short org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 109 of file IPv6TERouterIdofRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 104 of file IPv6TERouterIdofRemoteNodeTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.hashCode ()
Definition at line 119 of file IPv6TERouterIdofRemoteNodeTlv.java.
static IPv6TERouterIdofRemoteNodeTlv org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.of (final byte[] raw) static
Returns newly created IPv6TERouterIdofRemoteNodeTlv object.
Parameters
raw IPv6 TE Router Id of RemoteNode
Returns
object of IPv6TERouterIdofRemoteNodeTlv
Definition at line 65 of file IPv6TERouterIdofRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.IPv6TERouterIdofRemoteNodeTlv(), org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.NO_MASK, and org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.NONE.
static IPv6TERouterIdofRemoteNodeTlv org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.read20Bytes (ChannelBuffer c) static
Reads the channel buffer and returns object of IPv6TERouterIdofRemoteNodeTlv.
Parameters
c input channel buffer
Returns
object of IPv6TERouterIdofRemoteNodeTlv
Definition at line 150 of file IPv6TERouterIdofRemoteNodeTlv.java.
String org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.toString ()
Definition at line 157 of file IPv6TERouterIdofRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.LENGTH, and org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.TYPE.
int org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 136 of file IPv6TERouterIdofRemoteNodeTlv.java.
References org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.LENGTH, and org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.TYPE.
Member Data Documentation
final IPv6TERouterIdofRemoteNodeTlv org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.FULL_MASK = NONE static
Definition at line 45 of file IPv6TERouterIdofRemoteNodeTlv.java.
final short org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.LENGTH = 20 static
Definition at line 35 of file IPv6TERouterIdofRemoteNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.getLength(), org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.toString(), and org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.write().
final Logger org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.log = LoggerFactory.getLogger(IPv6TERouterIdofRemoteNodeTlv.class) static protected
Definition at line 32 of file IPv6TERouterIdofRemoteNodeTlv.java.
final IPv6TERouterIdofRemoteNodeTlv org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.NO_MASK = new IPv6TERouterIdofRemoteNodeTlv(NO_MASK_VAL) static
Definition at line 44 of file IPv6TERouterIdofRemoteNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.of().
final IPv6TERouterIdofRemoteNodeTlv org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.NONE = new IPv6TERouterIdofRemoteNodeTlv(NONE_VAL) static
Definition at line 39 of file IPv6TERouterIdofRemoteNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.of().
final short org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.TYPE = 1400 static
Definition at line 34 of file IPv6TERouterIdofRemoteNodeTlv.java.
Referenced by org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.getType(), org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.toString(), and org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.write().
final byte org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.VALUE_LENGTH = 18 static
Definition at line 36 of file IPv6TERouterIdofRemoteNodeTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkAttributesTlv.read().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IPv6TERouterIdofRemoteNodeTlv.java