onos: org.onosproject.net.intent.constraint.WaypointConstraint Class Reference
org.onosproject.net.intent.constraint.WaypointConstraint Class Reference
Constraint that evaluates elements passed through in order.
Public Member Functions
WaypointConstraint (DeviceId...waypoints)
Creates a new waypoint constraint.
List< DeviceId > waypoints ()
double cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
boolean validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Constraint that evaluates elements passed through in order.
Definition at line 39 of file WaypointConstraint.java.
Constructor & Destructor Documentation
org.onosproject.net.intent.constraint.WaypointConstraint.WaypointConstraint (DeviceId... waypoints)
Creates a new waypoint constraint.
Parameters
waypoints waypoints
Definition at line 48 of file WaypointConstraint.java.
References org.onosproject.net.intent.constraint.WaypointConstraint.waypoints().
Member Function Documentation
double org.onosproject.net.intent.constraint.WaypointConstraint.cost (Link link, LinkResourceService resourceService)
Evaluates the specified link and provides the cost for its traversal.
Parameters
link link to be evaluated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
Implements org.onosproject.net.intent.Constraint.
Definition at line 64 of file WaypointConstraint.java.
boolean org.onosproject.net.intent.constraint.WaypointConstraint.equals (Object obj)
Definition at line 98 of file WaypointConstraint.java.
Referenced by org.onosproject.net.intent.constraint.WaypointConstraint.validate().
int org.onosproject.net.intent.constraint.WaypointConstraint.hashCode ()
Definition at line 93 of file WaypointConstraint.java.
String org.onosproject.net.intent.constraint.WaypointConstraint.toString ()
Definition at line 112 of file WaypointConstraint.java.
References org.onosproject.net.intent.constraint.WaypointConstraint.waypoints().
boolean org.onosproject.net.intent.constraint.WaypointConstraint.validate (Path path, LinkResourceService resourceService)
Validates that the specified path satisfies the constraint.
Parameters
path path to be validated
resourceService resource service for validating availability of link resources
Returns
cost of link traversal
Implements org.onosproject.net.intent.Constraint.
Definition at line 70 of file WaypointConstraint.java.
References org.onosproject.net.intent.constraint.WaypointConstraint.equals(), org.onosproject.net.Path.links(), and org.onosproject.net.intent.constraint.WaypointConstraint.waypoints().
Referenced by org.onosproject.net.intent.constraint.WaypointConstraintTest.testNotSatisfyWaypoint(), and org.onosproject.net.intent.constraint.WaypointConstraintTest.testSatisfyWaypoints().
List<DeviceId> org.onosproject.net.intent.constraint.WaypointConstraint.waypoints ()
Definition at line 59 of file WaypointConstraint.java.
Referenced by org.onosproject.net.intent.constraint.WaypointConstraint.toString(), org.onosproject.net.intent.constraint.WaypointConstraint.validate(), and org.onosproject.net.intent.constraint.WaypointConstraint.WaypointConstraint().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/constraint/WaypointConstraint.java