onos: org.onosproject.sdnip.SdnIpFib Class Reference
org.onosproject.sdnip.SdnIpFib Class Reference
FIB component of SDN-IP.
Public Member Functions
SdnIpFib (ApplicationId appId, InterfaceService interfaceService, IntentSynchronizationService intentSynchronizer)
Class constructor.
void update (Collection< FibUpdate > updates, Collection< FibUpdate > withdraws)
Signals the FIB component of changes to the FIB.
Static Protected Attributes
static final ImmutableList
< Constraint > CONSTRAINTS = ImmutableList.of(new PartialFailureConstraint())
Detailed Description
FIB component of SDN-IP.
Definition at line 54 of file SdnIpFib.java.
Constructor & Destructor Documentation
org.onosproject.sdnip.SdnIpFib.SdnIpFib (ApplicationId appId, InterfaceService interfaceService, IntentSynchronizationService intentSynchronizer)
Class constructor.
Parameters
appId application ID to use when generating intents
interfaceService interface service
intentSynchronizer intent synchronizer
Definition at line 75 of file SdnIpFib.java.
Member Function Documentation
void org.onosproject.sdnip.SdnIpFib.update (Collection< FibUpdate > updates, Collection< FibUpdate > withdraws)
Signals the FIB component of changes to the FIB.
Parameters
updates FIB updates of the UDPATE type
withdraws FIB updates of the WITHDRAW type
Implements org.onosproject.routing.FibListener.
Definition at line 86 of file SdnIpFib.java.
References onosUploadBits.prefix.
Member Data Documentation
final ImmutableList<Constraint> org.onosproject.sdnip.SdnIpFib.CONSTRAINTS = ImmutableList.of(new PartialFailureConstraint()) static protected
Definition at line 60 of file SdnIpFib.java.
Referenced by org.onosproject.sdnip.SdnIpFibTest.testFibAdd(), org.onosproject.sdnip.SdnIpFibTest.testFibAddWithVlan(), org.onosproject.sdnip.SdnIpFibTest.testFibDelete(), and org.onosproject.sdnip.SdnIpFibTest.testFibUpdate().
The documentation for this class was generated from the following file:
apps/sdnip/src/main/java/org/onosproject/sdnip/SdnIpFib.java