onos: org.onlab.packet.IpPrefix Class Reference
org.onlab.packet.IpPrefix Class Reference
A class representing an IP prefix.
Public Member Functions
IpAddress.Version version ()
Returns the IP version of the prefix.
boolean isIp4 ()
Tests whether the IP version of this prefix is IPv4.
boolean isIp6 ()
Tests whether the IP version of this prefix is IPv6.
IpAddress address ()
Returns the IP address value of the prefix.
int prefixLength ()
Returns the IP address prefix length.
Ip4Prefix getIp4Prefix ()
Gets the Ip4Prefix view of the IP prefix.
Ip6Prefix getIp6Prefix ()
Gets the Ip6Prefix view of the IP prefix.
boolean contains (IpPrefix other)
Determines whether a given IP prefix is contained within this prefix.
boolean contains (IpAddress other)
Determines whether a given IP address is contained within this prefix.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static IpPrefix valueOf (int address, int prefixLength)
Converts an integer and a prefix length into an IPv4 prefix.
static IpPrefix valueOf (IpAddress.Version version, byte[] address, int prefixLength)
Converts a byte array and a prefix length into an IP prefix.
static IpPrefix valueOf (IpAddress address, int prefixLength)
Converts an IP address and a prefix length into an IP prefix.
static IpPrefix valueOf (String address)
Converts a CIDR (slash) notation string (e.g., "10.1.0.0/16" or "1111:2222::/64") into an IP prefix.
Static Public Attributes
static final int MAX_INET_MASK_LENGTH = IpAddress.INET_BIT_LENGTH
static final int MAX_INET6_MASK_LENGTH = IpAddress.INET6_BIT_LENGTH
Protected Member Functions
IpPrefix (IpAddress address, int prefixLength)
Constructor for given IP address, and a prefix length.
Detailed Description
A class representing an IP prefix.
A prefix consists of an IP address and a subnet mask. This class is immutable.
NOTE: The stored IP address in the result IP prefix is masked to contain zeroes in all bits after the prefix length.
Definition at line 29 of file IpPrefix.java.
Constructor & Destructor Documentation
org.onlab.packet.IpPrefix.IpPrefix (IpAddress address, int prefixLength) protected
Constructor for given IP address, and a prefix length.
Parameters
address the IP address
prefixLength the prefix length
Exceptions
IllegalArgumentException if the prefix length value is invalid
Definition at line 44 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.address(), and org.onlab.packet.IpPrefix.prefixLength().
Referenced by org.onlab.packet.IpPrefix.equals(), and org.onlab.packet.IpPrefix.valueOf().
Member Function Documentation
IpAddress org.onlab.packet.IpPrefix.address ()
Returns the IP address value of the prefix.
Returns
the IP address value of the prefix
Definition at line 82 of file IpPrefix.java.
Referenced by org.onlab.packet.IpPrefix.hashCode(), and org.onlab.packet.IpPrefix.IpPrefix().
boolean org.onlab.packet.IpPrefix.contains (IpPrefix other)
Determines whether a given IP prefix is contained within this prefix.
Parameters
other the IP prefix to test
Returns
true if the other IP prefix is contained in this prefix, otherwise false
Definition at line 199 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.prefixLength(), and org.onlab.packet.IpPrefix.version().
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectIpPrefix(), org.onlab.packet.Ip4PrefixTest.testContainsIpAddressIPv4(), org.onlab.packet.IpPrefixTest.testContainsIpAddressIPv4(), org.onlab.packet.Ip6PrefixTest.testContainsIpAddressIPv6(), org.onlab.packet.IpPrefixTest.testContainsIpAddressIPv6(), org.onlab.packet.Ip4PrefixTest.testContainsIpPrefixIPv4(), org.onlab.packet.IpPrefixTest.testContainsIpPrefixIPv4(), org.onlab.packet.Ip6PrefixTest.testContainsIpPrefixIPv6(), and org.onlab.packet.IpPrefixTest.testContainsIpPrefixIPv6().
boolean org.onlab.packet.IpPrefix.contains (IpAddress other)
Determines whether a given IP address is contained within this prefix.
Parameters
other the IP address to test
Returns
true if the IP address is contained in this prefix, otherwise false
Definition at line 225 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.version().
boolean org.onlab.packet.IpPrefix.equals (Object obj)
Definition at line 246 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.IpPrefix(), and org.onlab.packet.IpPrefix.prefixLength().
Ip4Prefix org.onlab.packet.IpPrefix.getIp4Prefix ()
Gets the Ip4Prefix view of the IP prefix.
Returns
the Ip4Prefix view of the IP prefix if it is IPv4, otherwise null
Definition at line 101 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.isIp4(), and org.onlab.packet.IpPrefix.prefixLength().
Ip6Prefix org.onlab.packet.IpPrefix.getIp6Prefix ()
Gets the Ip6Prefix view of the IP prefix.
Returns
the Ip6Prefix view of the IP prefix if it is IPv6, otherwise null
Definition at line 119 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.isIp6(), and org.onlab.packet.IpPrefix.prefixLength().
int org.onlab.packet.IpPrefix.hashCode ()
Definition at line 241 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.address(), and org.onlab.packet.IpPrefix.prefixLength().
boolean org.onlab.packet.IpPrefix.isIp4 ()
Tests whether the IP version of this prefix is IPv4.
Returns
true if the IP version of this prefix is IPv4, otherwise false.
Definition at line 64 of file IpPrefix.java.
Referenced by org.onosproject.mfwd.impl.McastRouteTable.addRoute(), org.onosproject.cli.net.ConnectivityIntentCommand.buildTrafficSelector(), org.onosproject.routing.bgp.BgpSession.findBgpRoute(), org.onosproject.mfwd.impl.McastRouteTable.findMcastGroup(), org.onlab.packet.IpPrefix.getIp4Prefix(), and org.onlab.packet.IpPrefixTest.testIsIp4().
boolean org.onlab.packet.IpPrefix.isIp6 ()
Tests whether the IP version of this prefix is IPv6.
Returns
true if the IP version of this prefix is IPv6, otherwise false.
Definition at line 73 of file IpPrefix.java.
Referenced by org.onosproject.mfwd.impl.McastRouteTable.addRoute(), org.onosproject.cli.net.ConnectivityIntentCommand.buildTrafficSelector(), org.onosproject.mfwd.impl.McastRouteTable.findMcastGroup(), org.onlab.packet.IpPrefix.getIp6Prefix(), and org.onlab.packet.IpPrefixTest.testIsIp6().
int org.onlab.packet.IpPrefix.prefixLength ()
Returns the IP address prefix length.
Returns
the IP address prefix length
Definition at line 91 of file IpPrefix.java.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onlab.packet.IpPrefix.contains(), org.onlab.packet.IpPrefix.equals(), org.onlab.packet.IpPrefix.getIp4Prefix(), org.onlab.packet.IpPrefix.getIp6Prefix(), org.onlab.packet.IpPrefix.hashCode(), org.onlab.packet.IpPrefix.IpPrefix(), org.onlab.packet.Ip4PrefixTest.testAddressAndPrefixLengthIPv4(), org.onlab.packet.Ip6PrefixTest.testAddressAndPrefixLengthIPv6(), org.onlab.packet.IpPrefix.toString(), org.onlab.packet.Ip4Prefix.valueOf(), org.onlab.packet.Ip6Prefix.valueOf(), and org.onlab.packet.IpPrefix.valueOf().
String org.onlab.packet.IpPrefix.toString ()
Definition at line 265 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.prefixLength().
Referenced by org.onlab.packet.Ip4PrefixTest.testToStringIPv4(), org.onlab.packet.IpPrefixTest.testToStringIPv4(), org.onlab.packet.Ip6PrefixTest.testToStringIPv6(), org.onlab.packet.IpPrefixTest.testToStringIPv6(), org.onlab.packet.Ip4PrefixTest.testValueOfByteArrayIPv4(), org.onlab.packet.IpPrefixTest.testValueOfByteArrayIPv4(), org.onlab.packet.Ip6PrefixTest.testValueOfByteArrayIPv6(), org.onlab.packet.IpPrefixTest.testValueOfByteArrayIPv6(), org.onlab.packet.Ip4PrefixTest.testValueOfForIntegerIPv4(), org.onlab.packet.IpPrefixTest.testValueOfForIntegerIPv4(), org.onlab.packet.Ip4PrefixTest.testValueOfStringIPv4(), org.onlab.packet.IpPrefixTest.testValueOfStringIPv4(), org.onlab.packet.Ip6PrefixTest.testValueOfStringIPv6(), org.onlab.packet.IpPrefixTest.testValueOfStringIPv6(), and org.onosproject.mfwd.impl.McastRouteBase.toString().
static IpPrefix org.onlab.packet.IpPrefix.valueOf (int address, int prefixLength) static
Converts an integer and a prefix length into an IPv4 prefix.
Parameters
address an integer representing the IPv4 address
prefixLength the prefix length
Returns
an IP prefix
Exceptions
IllegalArgumentException if the prefix length value is invalid
Definition at line 139 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.IpPrefix(), org.onlab.packet.IpPrefix.prefixLength(), and org.onlab.packet.IpAddress.valueOf().
Referenced by org.onosproject.codec.impl.FlowRuleCodecTest.codecCriteriaFlowTest(), org.onosproject.routing.impl.Router.getLongestMatchableRouteEntry(), org.onosproject.routing.config.impl.RoutingConfigurationImpl.isIpAddressLocal(), org.onosproject.vtn.table.impl.ClassifierServiceImpl.programL3ExPortClassifierRules(), org.onosproject.vtn.table.impl.L3ForwardServiceImpl.programRouteRules(), org.onosproject.vtn.table.impl.SnatServiceImpl.programRules(), org.onlab.packet.pim.PIMAddrGroup.setAddr(), org.onlab.packet.IpPrefixTest.testContainsIpPrefixIPv4(), org.onlab.packet.IpPrefixTest.testContainsIpPrefixIPv6(), org.onlab.packet.IpPrefixTest.testEqualityIPv4(), org.onlab.packet.IpPrefixTest.testEqualityIPv6(), org.onosproject.store.serializers.KryoSerializerTest.testIpPrefix(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUs(), and org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUsIpv6().
static IpPrefix org.onlab.packet.IpPrefix.valueOf (IpAddress.Version version, byte[] address, int prefixLength) static
Converts a byte array and a prefix length into an IP prefix.
Parameters
version the IP address version
address the IP address value stored in network byte order
prefixLength the prefix length
Returns
an IP prefix
Exceptions
IllegalArgumentException if the prefix length value is invalid
Definition at line 152 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.IpPrefix(), org.onlab.packet.IpPrefix.prefixLength(), org.onlab.packet.IpAddress.valueOf(), and org.onlab.packet.IpPrefix.version().
static IpPrefix org.onlab.packet.IpPrefix.valueOf (IpAddress address, int prefixLength) static
Converts an IP address and a prefix length into an IP prefix.
Parameters
address the IP address
prefixLength the prefix length
Returns
an IP prefix
Exceptions
IllegalArgumentException if the prefix length value is invalid
Definition at line 165 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.IpPrefix().
static IpPrefix org.onlab.packet.IpPrefix.valueOf (String address) static
Converts a CIDR (slash) notation string (e.g., "10.1.0.0/16" or "1111:2222::/64") into an IP prefix.
Parameters
address an IP prefix in string form (e.g. "10.1.0.0/16" or "1111:2222::/64")
Returns
an IP prefix
Exceptions
IllegalArgumentException if the arguments are invalid
Definition at line 178 of file IpPrefix.java.
References org.onlab.packet.IpPrefix.IpPrefix(), and org.onlab.packet.IpPrefix.prefixLength().
IpAddress.Version org.onlab.packet.IpPrefix.version ()
Returns the IP version of the prefix.
Returns
the IP version of the prefix
Definition at line 55 of file IpPrefix.java.
Referenced by org.onosproject.cli.net.ConnectivityIntentCommand.buildTrafficSelector(), org.onlab.packet.IpPrefix.contains(), org.onlab.packet.IpPrefixTest.testVersion(), org.onlab.packet.Ip4PrefixTest.testVersion(), org.onlab.packet.Ip6PrefixTest.testVersion(), and org.onlab.packet.IpPrefix.valueOf().
Member Data Documentation
final int org.onlab.packet.IpPrefix.MAX_INET6_MASK_LENGTH = IpAddress.INET6_BIT_LENGTH static
Definition at line 32 of file IpPrefix.java.
Referenced by org.onlab.packet.IpPrefixTest.testMaxMaskLength().
final int org.onlab.packet.IpPrefix.MAX_INET_MASK_LENGTH = IpAddress.INET_BIT_LENGTH static
Definition at line 31 of file IpPrefix.java.
Referenced by org.onosproject.virtualbng.VbngConfigurationManager.assignSpecifiedPublicIp(), org.onosproject.virtualbng.VbngConfigurationManager.getAvailablePublicIpAddress(), org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterIpPunts(), org.onosproject.segmentrouting.IcmpHandler.processPacketIn(), and org.onlab.packet.IpPrefixTest.testMaxMaskLength().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/packet/IpPrefix.java