onos: org.onlab.packet.ndp.RedirectTest Class Reference
org.onlab.packet.ndp.RedirectTest Class Reference
Tests for class Redirect.
Public Member Functions
void testSerialize ()
Tests serialize and setters.
void testDeserializeBadInput () throws Exception
void testDeserializeTruncated () throws Exception
void testDeserialize () throws DeserializationException
Tests deserialize and getters.
void testEqual ()
Tests comparator.
Static Public Member Functions
static void setUpBeforeClass () throws Exception
Detailed Description
Tests for class Redirect.
Definition at line 36 of file RedirectTest.java.
Member Function Documentation
static void org.onlab.packet.ndp.RedirectTest.setUpBeforeClass () throws Exception static
Definition at line 63 of file RedirectTest.java.
References find-link-in-cluster.length.
void org.onlab.packet.ndp.RedirectTest.testDeserialize () throws DeserializationException
Tests deserialize and getters.
Definition at line 113 of file RedirectTest.java.
References org.onlab.packet.ndp.Redirect.getDestinationAddress(), org.onlab.packet.ndp.Redirect.getOptions(), org.onlab.packet.ndp.Redirect.getTargetAddress(), find-link-in-cluster.length, and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
void org.onlab.packet.ndp.RedirectTest.testDeserializeBadInput () throws Exception
Definition at line 96 of file RedirectTest.java.
void org.onlab.packet.ndp.RedirectTest.testDeserializeTruncated () throws Exception
Definition at line 101 of file RedirectTest.java.
References org.onlab.packet.ndp.Redirect.HEADER_LENGTH.
void org.onlab.packet.ndp.RedirectTest.testEqual ()
Tests comparator.
Definition at line 131 of file RedirectTest.java.
References org.onlab.packet.ndp.Redirect.equals(), and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
void org.onlab.packet.ndp.RedirectTest.testSerialize ()
Tests serialize and setters.
Definition at line 85 of file RedirectTest.java.
References org.onlab.packet.ndp.Redirect.serialize(), and org.onlab.packet.ndp.NeighborDiscoveryOptions.TYPE_TARGET_LL_ADDRESS.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/ndp/RedirectTest.java