onos: org.onosproject.net.config.basics.BasicLinkConfig Class Reference
org.onosproject.net.config.basics.BasicLinkConfig Class Reference
Basic configuration for network infrastructure link.
Public Member Functions
Link.Type type ()
Returns the link type.
BasicLinkConfig type (Link.Type type)
Sets the link type.
Duration latency ()
Returns link latency in terms of nanos.
BasicLinkConfig latency (Duration latency)
Sets the link latency.
long bandwidth ()
Returns link bandwidth in terms of Mbps.
BasicLinkConfig bandwidth (Long bandwidth)
Sets the link bandwidth.
Boolean isDurable ()
Returns if link is durable in the network model or not.
BasicLinkConfig isDurable (Boolean isDurable)
Sets durability for this link.
Static Public Attributes
static final String TYPE = "type"
static final String LATENCY = "latency"
static final String BANDWIDTH = "bandwidth"
static final String IS_DURABLE = "durable"
Detailed Description
Basic configuration for network infrastructure link.
Definition at line 27 of file BasicLinkConfig.java.
Member Function Documentation
long org.onosproject.net.config.basics.BasicLinkConfig.bandwidth ()
Returns link bandwidth in terms of Mbps.
Returns
link bandwidth; -1 if not set
Definition at line 78 of file BasicLinkConfig.java.
References org.onosproject.net.config.basics.BasicLinkConfig.BANDWIDTH.
Referenced by org.onosproject.net.link.impl.BasicLinkOperator.combine().
BasicLinkConfig org.onosproject.net.config.basics.BasicLinkConfig.bandwidth (Long bandwidth)
Sets the link bandwidth.
Parameters
bandwidth new bandwidth; null to clear
Returns
self
Definition at line 88 of file BasicLinkConfig.java.
References org.onosproject.net.config.basics.BasicLinkConfig.BANDWIDTH.
Boolean org.onosproject.net.config.basics.BasicLinkConfig.isDurable ()
Returns if link is durable in the network model or not.
Returns
true for durable, false otherwise
Definition at line 97 of file BasicLinkConfig.java.
References org.onosproject.net.config.basics.BasicLinkConfig.IS_DURABLE.
Referenced by org.onosproject.net.link.impl.BasicLinkOperator.combine().
BasicLinkConfig org.onosproject.net.config.basics.BasicLinkConfig.isDurable (Boolean isDurable)
Sets durability for this link.
Parameters
isDurable true for durable, false otherwise
Returns
this BasicLinkConfig
Definition at line 111 of file BasicLinkConfig.java.
References org.onosproject.net.config.basics.BasicLinkConfig.IS_DURABLE.
Duration org.onosproject.net.config.basics.BasicLinkConfig.latency ()
Returns link latency in terms of nanos.
Returns
link latency; -1 if not set
Definition at line 58 of file BasicLinkConfig.java.
References org.onosproject.net.config.basics.BasicLinkConfig.LATENCY.
Referenced by org.onosproject.net.link.impl.BasicLinkOperator.combine().
BasicLinkConfig org.onosproject.net.config.basics.BasicLinkConfig.latency (Duration latency)
Sets the link latency.
Parameters
latency new latency; null to clear
Returns
self
Definition at line 68 of file BasicLinkConfig.java.
References org.onosproject.net.config.basics.BasicLinkConfig.LATENCY.
Link.Type org.onosproject.net.config.basics.BasicLinkConfig.type ()
Returns the link type.
Returns
link type override
Definition at line 39 of file BasicLinkConfig.java.
References org.onosproject.net.config.basics.BasicLinkConfig.TYPE.
Referenced by org.onosproject.net.link.impl.BasicLinkOperator.combine(), org.onosproject.net.link.impl.BasicLinkOperator.descriptionOf(), and org.onosproject.net.config.basics.BasicLinkConfig.type().
BasicLinkConfig org.onosproject.net.config.basics.BasicLinkConfig.type (Link.Type type)
Sets the link type.
Parameters
type link type override
Returns
self
Definition at line 49 of file BasicLinkConfig.java.
References org.onosproject.net.config.basics.BasicLinkConfig.TYPE, and org.onosproject.net.config.basics.BasicLinkConfig.type().
Member Data Documentation
final String org.onosproject.net.config.basics.BasicLinkConfig.BANDWIDTH = "bandwidth" static
Definition at line 31 of file BasicLinkConfig.java.
Referenced by org.onosproject.net.config.basics.BasicLinkConfig.bandwidth().
final String org.onosproject.net.config.basics.BasicLinkConfig.IS_DURABLE = "durable" static
Definition at line 32 of file BasicLinkConfig.java.
Referenced by org.onosproject.net.config.basics.BasicLinkConfig.isDurable().
final String org.onosproject.net.config.basics.BasicLinkConfig.LATENCY = "latency" static
Definition at line 30 of file BasicLinkConfig.java.
Referenced by org.onosproject.net.config.basics.BasicLinkConfig.latency().
final String org.onosproject.net.config.basics.BasicLinkConfig.TYPE = "type" static
Definition at line 29 of file BasicLinkConfig.java.
Referenced by org.onosproject.net.config.basics.BasicLinkConfig.type().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/config/basics/BasicLinkConfig.java