onos: org.onosproject.net.resource.link.MplsLabel Class Reference
org.onosproject.net.resource.link.MplsLabel Class Reference
Representation of MPLS label resource.
Public Member Functions
MplsLabel (int mplsLabel)
Creates a new instance with given MPLS label.
org.onlab.packet.MplsLabel label ()
Returns MPLS Label as an MPLS Label Object.
boolean equals (Object obj)
int hashCode ()
String toString ()
Static Public Member Functions
static MplsLabel valueOf (int mplsLabel)
Creates a new instance with given MPLS label.
Detailed Description
Representation of MPLS label resource.
Deprecated:
in Emu Release
Definition at line 27 of file MplsLabel.java.
Constructor & Destructor Documentation
org.onosproject.net.resource.link.MplsLabel.MplsLabel (int mplsLabel)
Creates a new instance with given MPLS label.
Parameters
mplsLabel MPLS Label value to be assigned
Definition at line 37 of file MplsLabel.java.
Referenced by org.onosproject.net.resource.link.MplsLabel.equals(), and org.onosproject.net.resource.link.MplsLabel.valueOf().
Member Function Documentation
boolean org.onosproject.net.resource.link.MplsLabel.equals (Object obj)
Definition at line 61 of file MplsLabel.java.
References org.onosproject.net.resource.link.MplsLabel.MplsLabel().
int org.onosproject.net.resource.link.MplsLabel.hashCode ()
Definition at line 70 of file MplsLabel.java.
org.onlab.packet.MplsLabel org.onosproject.net.resource.link.MplsLabel.label ()
Returns MPLS Label as an MPLS Label Object.
Returns
MPLS label as an MPLS Label Object.
Definition at line 56 of file MplsLabel.java.
Referenced by org.onosproject.net.resource.MplsObjectsTest.checkLabelConstruction().
String org.onosproject.net.resource.link.MplsLabel.toString ()
Definition at line 75 of file MplsLabel.java.
static MplsLabel org.onosproject.net.resource.link.MplsLabel.valueOf (int mplsLabel) static
Creates a new instance with given MPLS label.
Parameters
mplsLabel mplsLabel value to be assigned
Returns
MplsLabel instance with given bandwidth
Definition at line 47 of file MplsLabel.java.
References org.onosproject.net.resource.link.MplsLabel.MplsLabel().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/resource/link/MplsLabel.java