onos: org.onlab.junit.TestUtils Class Reference
org.onlab.junit.TestUtils Class Reference
Utilities for testing.
Classes
class TestUtilsException
Exception that can be thrown if problems are encountered while executing the utility method.
Static Public Member Functions
static< T, U > void setField (T subject, String fieldName, U value) throws TestUtilsException
Sets the field, bypassing scope restriction.
static< T, U > U getField (T subject, String fieldName) throws TestUtilsException
Gets the field, bypassing scope restriction.
static< T, U > U callMethod (T subject, String methodName, Class<?>[] paramTypes, Object...args) throws TestUtilsException
Calls the method, bypassing scope restriction.
static< T, U > U callMethod (T subject, String methodName, Class<?> paramType, Object arg) throws TestUtilsException
Calls the method, bypassing scope restriction.
static< T > T callConstructor (Constructor< T > constructor) throws TestUtilsException
Triggers an allocation of an object of type T and forces a call to the private constructor.
Detailed Description
Utilities for testing.
Definition at line 27 of file TestUtils.java.
Member Function Documentation
static <T> T org.onlab.junit.TestUtils.callConstructor (Constructor< T > constructor) throws TestUtilsException static
Triggers an allocation of an object of type T and forces a call to the private constructor.
Parameters
constructor Constructor to call
<T> type of the object to create
Returns
created object of type T
Exceptions
TestUtilsException if there are reflection errors while calling the constructor
Definition at line 170 of file TestUtils.java.
static <T,U> U org.onlab.junit.TestUtils.callMethod (T subject, String methodName, Class<?>[] paramTypes, Object... args) throws TestUtilsException static
Calls the method, bypassing scope restriction.
Parameters
subject Object where the method belongs
methodName name of the method to call
paramTypes formal parameter type array
args arguments
Returns
return value or null if void
Parameters
<T> subject type
<U> return value type
Exceptions
TestUtilsException if there are reflection errors while calling the method
Definition at line 118 of file TestUtils.java.
Referenced by org.onlab.junit.TestUtils.callMethod().
static <T,U> U org.onlab.junit.TestUtils.callMethod (T subject, String methodName, Class<?> paramType, Object arg) throws TestUtilsException static
Calls the method, bypassing scope restriction.
Parameters
subject Object where the method belongs
methodName name of the method to call
paramType formal parameter type
arg argument
Returns
return value or null if void
Parameters
<T> subject type
<U> return value type
Exceptions
TestUtilsException if there are reflection errors while calling the method
Definition at line 155 of file TestUtils.java.
References org.onlab.junit.TestUtils.callMethod().
static <T,U> U org.onlab.junit.TestUtils.getField (T subject, String fieldName) throws TestUtilsException static
Gets the field, bypassing scope restriction.
Parameters
subject Object where the field belongs
fieldName name of the field to get
<T> subject type
<U> fieldO value type
Returns
value of the field.
Exceptions
TestUtilsException if there are reflection errors while getting the field
Definition at line 75 of file TestUtils.java.
Referenced by org.onlab.junit.TestUtilsTest.testSetGetPrivateField(), and org.onlab.junit.TestUtilsTest.testSetGetProtectedField().
static <T,U> void org.onlab.junit.TestUtils.setField (T subject, String fieldName, U value) throws TestUtilsException static
Sets the field, bypassing scope restriction.
Parameters
subject Object where the field belongs
fieldName name of the field to set
value value to set to the field.
<T> subject type
<U> value type
Exceptions
TestUtilsException if there are reflection errors while setting the field
Definition at line 40 of file TestUtils.java.
The documentation for this class was generated from the following file:
utils/junit/src/main/java/org/onlab/junit/TestUtils.java