onos: org.onosproject.net.device.DefaultPortDescription Class Reference
org.onosproject.net.device.DefaultPortDescription Class Reference
Default implementation of immutable port description.
Public Member Functions
DefaultPortDescription (PortNumber number, boolean isEnabled, SparseAnnotations...annotations)
Creates a port description using the supplied information.
DefaultPortDescription (PortNumber number, boolean isEnabled, Type type, long portSpeed, SparseAnnotations...annotations)
Creates a port description using the supplied information.
DefaultPortDescription (PortDescription base, SparseAnnotations annotations)
Creates a port description using the supplied information.
PortNumber portNumber ()
Returns the port number.
boolean isEnabled ()
Indicates whether or not the port is up and active.
Type type ()
Returns the port type.
long portSpeed ()
Returns the current port speed in Mbps.
String toString ()
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.AbstractDescription
SparseAnnotations annotations ()
Returns the key/value annotations.
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractDescription
AbstractDescription ()
AbstractDescription (SparseAnnotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of immutable port description.
Definition at line 29 of file DefaultPortDescription.java.
Constructor & Destructor Documentation
org.onosproject.net.device.DefaultPortDescription.DefaultPortDescription (PortNumber number, boolean isEnabled, SparseAnnotations... annotations)
Creates a port description using the supplied information.
Parameters
number port number
isEnabled port enabled state
annotations optional key/value annotations map
Definition at line 46 of file DefaultPortDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), and org.onosproject.net.device.DefaultPortDescription.isEnabled().
org.onosproject.net.device.DefaultPortDescription.DefaultPortDescription (PortNumber number, boolean isEnabled, Type type, long portSpeed, SparseAnnotations... annotations)
Creates a port description using the supplied information.
Parameters
number port number
isEnabled port enabled state
type port type
portSpeed port speed in Mbps
annotations optional key/value annotations map
Definition at line 60 of file DefaultPortDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.device.DefaultPortDescription.isEnabled(), org.onosproject.net.device.DefaultPortDescription.portSpeed(), and org.onosproject.net.device.DefaultPortDescription.type().
org.onosproject.net.device.DefaultPortDescription.DefaultPortDescription (PortDescription base, SparseAnnotations annotations)
Creates a port description using the supplied information.
Parameters
base PortDescription to get basic information from
annotations optional key/value annotations map
Definition at line 84 of file DefaultPortDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.device.PortDescription.isEnabled(), and org.onosproject.net.device.PortDescription.portSpeed().
Member Function Documentation
boolean org.onosproject.net.device.DefaultPortDescription.equals (Object object)
Definition at line 128 of file DefaultPortDescription.java.
int org.onosproject.net.device.DefaultPortDescription.hashCode ()
Definition at line 122 of file DefaultPortDescription.java.
References org.onosproject.net.device.DefaultPortDescription.isEnabled(), org.onosproject.net.device.DefaultPortDescription.portSpeed(), and org.onosproject.net.device.DefaultPortDescription.type().
boolean org.onosproject.net.device.DefaultPortDescription.isEnabled ()
Indicates whether or not the port is up and active.
Returns
true if the port is active and has carrier signal
Implements org.onosproject.net.device.PortDescription.
Definition at line 96 of file DefaultPortDescription.java.
Referenced by org.onosproject.net.device.DefaultPortDescription.DefaultPortDescription(), org.onosproject.net.device.DefaultPortDescription.hashCode(), org.onosproject.net.device.OduCltPortDescription.toString(), org.onosproject.net.device.OmsPortDescription.toString(), org.onosproject.net.device.OchPortDescription.toString(), and org.onosproject.net.device.DefaultPortDescription.toString().
PortNumber org.onosproject.net.device.DefaultPortDescription.portNumber ()
Returns the port number.
Returns
port number
Implements org.onosproject.net.device.PortDescription.
Definition at line 91 of file DefaultPortDescription.java.
Referenced by org.onosproject.net.device.impl.OpticalPortOperatorTest.testDescOps(), org.onosproject.net.device.OduCltPortDescription.toString(), org.onosproject.net.device.OmsPortDescription.toString(), and org.onosproject.net.device.OchPortDescription.toString().
long org.onosproject.net.device.DefaultPortDescription.portSpeed ()
Returns the current port speed in Mbps.
Returns
current port speed
Implements org.onosproject.net.device.PortDescription.
Definition at line 106 of file DefaultPortDescription.java.
Referenced by org.onosproject.net.device.DefaultPortDescription.DefaultPortDescription(), org.onosproject.net.device.DefaultPortDescription.hashCode(), and org.onosproject.net.device.DefaultPortDescription.toString().
String org.onosproject.net.device.DefaultPortDescription.toString ()
Definition at line 111 of file DefaultPortDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.device.DefaultPortDescription.isEnabled(), org.onosproject.net.device.DefaultPortDescription.portSpeed(), and org.onosproject.net.device.DefaultPortDescription.type().
Type org.onosproject.net.device.DefaultPortDescription.type ()
Returns the port type.
Returns
port type
Implements org.onosproject.net.device.PortDescription.
Definition at line 101 of file DefaultPortDescription.java.
Referenced by org.onosproject.net.device.DefaultPortDescription.DefaultPortDescription(), org.onosproject.net.device.DefaultPortDescription.hashCode(), org.onosproject.net.device.OduCltPortDescription.toString(), org.onosproject.net.device.OmsPortDescription.toString(), org.onosproject.net.device.OchPortDescription.toString(), and org.onosproject.net.device.DefaultPortDescription.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/device/DefaultPortDescription.java