onos: org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest Class Reference
org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest Class Reference
Json Rpc Request information that include id,method,params.
Public Member Functions
JsonRpcRequest (String id, String method)
JsonRpcRequest Constructor.
JsonRpcRequest (String id, String method, List< Object > params)
JsonRpcRequest Constructor.
String getId ()
Returns id.
String getMethod ()
Returns method.
List< Object > getParams ()
Returns params.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Json Rpc Request information that include id,method,params.
Definition at line 29 of file JsonRpcRequest.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest.JsonRpcRequest (String id, String method)
JsonRpcRequest Constructor.
Parameters
id the id node of request information
method the method node of request information
Definition at line 40 of file JsonRpcRequest.java.
Referenced by org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest.equals().
org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest.JsonRpcRequest (String id, String method, List< Object > params)
JsonRpcRequest Constructor.
Parameters
id the id node of request information
method the method node of request information
params the params node of request information
Definition at line 54 of file JsonRpcRequest.java.
Member Function Documentation
boolean org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest.equals (Object obj)
Definition at line 93 of file JsonRpcRequest.java.
References find-device.id, and org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest.JsonRpcRequest().
String org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest.getId ()
Returns id.
Returns
id
Definition at line 67 of file JsonRpcRequest.java.
Referenced by metro.FabricDomain.build().
String org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest.getMethod ()
Returns method.
Returns
method
Definition at line 75 of file JsonRpcRequest.java.
List<Object> org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest.getParams ()
Returns params.
Returns
params
Definition at line 83 of file JsonRpcRequest.java.
int org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest.hashCode ()
Definition at line 88 of file JsonRpcRequest.java.
String org.onosproject.ovsdb.rfc.jsonrpc.JsonRpcRequest.toString ()
Definition at line 107 of file JsonRpcRequest.java.
The documentation for this class was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/jsonrpc/JsonRpcRequest.java