onos: org.onosproject.net.resource.link.DefaultLinkResourceAllocations Class Reference
org.onosproject.net.resource.link.DefaultLinkResourceAllocations Class Reference
Implementation of LinkResourceAllocations.
Public Member Functions
DefaultLinkResourceAllocations (LinkResourceRequest request, Map< Link, Set< ResourceAllocation >> allocations)
Creates a new link resource allocations.
IntentId intentId ()
Returns the IntentId associated with the request.
Collection< Link > links ()
Returns the set of target links.
Set< ResourceRequest > resources ()
Returns the set of resource requests.
ResourceType type ()
Returns the resource type.
Set< ResourceAllocation > getResourceAllocation (Link link)
Returns allocated resource for the given link.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Implementation of LinkResourceAllocations.
Deprecated:
in Emu Release
Definition at line 43 of file DefaultLinkResourceAllocations.java.
Constructor & Destructor Documentation
org.onosproject.net.resource.link.DefaultLinkResourceAllocations.DefaultLinkResourceAllocations (LinkResourceRequest request, Map< Link, Set< ResourceAllocation >> allocations)
Creates a new link resource allocations.
Parameters
request requested resources
allocations allocated resources
Definition at line 54 of file DefaultLinkResourceAllocations.java.
Referenced by org.onosproject.net.resource.link.DefaultLinkResourceAllocations.equals().
Member Function Documentation
boolean org.onosproject.net.resource.link.DefaultLinkResourceAllocations.equals (Object obj)
Definition at line 97 of file DefaultLinkResourceAllocations.java.
References org.onosproject.net.resource.link.DefaultLinkResourceAllocations.DefaultLinkResourceAllocations(), and org.onosproject.net.resource.link.DefaultLinkResourceAllocations.equals().
Referenced by org.onosproject.net.resource.link.DefaultLinkResourceAllocations.equals().
Set<ResourceAllocation> org.onosproject.net.resource.link.DefaultLinkResourceAllocations.getResourceAllocation (Link link)
Returns allocated resource for the given link.
Parameters
link the target link
Returns
allocated resource for the link
Implements org.onosproject.net.resource.link.LinkResourceAllocations.
Definition at line 83 of file DefaultLinkResourceAllocations.java.
int org.onosproject.net.resource.link.DefaultLinkResourceAllocations.hashCode ()
Definition at line 92 of file DefaultLinkResourceAllocations.java.
IntentId org.onosproject.net.resource.link.DefaultLinkResourceAllocations.intentId ()
Returns the IntentId associated with the request.
Returns
the IntentId associated with the request
Implements org.onosproject.net.resource.link.LinkResourceAllocations.
Definition at line 65 of file DefaultLinkResourceAllocations.java.
Collection<Link> org.onosproject.net.resource.link.DefaultLinkResourceAllocations.links ()
Returns the set of target links.
Returns
the set of target links
Implements org.onosproject.net.resource.link.LinkResourceAllocations.
Definition at line 69 of file DefaultLinkResourceAllocations.java.
Set<ResourceRequest> org.onosproject.net.resource.link.DefaultLinkResourceAllocations.resources ()
Returns the set of resource requests.
Returns
the set of resource requests
Implements org.onosproject.net.resource.link.LinkResourceAllocations.
Definition at line 73 of file DefaultLinkResourceAllocations.java.
String org.onosproject.net.resource.link.DefaultLinkResourceAllocations.toString ()
Definition at line 110 of file DefaultLinkResourceAllocations.java.
ResourceType org.onosproject.net.resource.link.DefaultLinkResourceAllocations.type ()
Returns the resource type.
Returns
the resource type
Implements org.onosproject.net.resource.ResourceAllocation.
Definition at line 78 of file DefaultLinkResourceAllocations.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/resource/link/DefaultLinkResourceAllocations.java