onos: org.onosproject.store.device.impl.ECDeviceStore Class Reference
org.onosproject.store.device.impl.ECDeviceStore Class Reference
Manages the inventory of devices using a.
Public Member Functions
void activate ()
void deactivate ()
Iterable< Device > getDevices ()
Returns an iterable collection of all devices known to the system.
int getDeviceCount ()
Returns the number of devices known to the system.
Device getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
DeviceEvent createOrUpdateDevice (ProviderId providerId, DeviceId deviceId, DeviceDescription deviceDescription)
Creates a new infrastructure device, or updates an existing one using the supplied device description.
DeviceEvent markOffline (DeviceId deviceId)
Removes the specified infrastructure device.
List< DeviceEvent > updatePorts (ProviderId providerId, DeviceId deviceId, List< PortDescription > descriptions)
Updates the ports of the specified infrastructure device using the given list of port descriptions.
DeviceEvent updatePortStatus (ProviderId providerId, DeviceId deviceId, PortDescription portDescription)
Updates the port status of the specified infrastructure device using the given port description.
List< Port > getPorts (DeviceId deviceId)
Returns the list of ports that belong to the specified device.
Port getPort (DeviceId deviceId, PortNumber portNumber)
Returns the specified device port.
DeviceEvent updatePortStatistics (ProviderId providerId, DeviceId deviceId, Collection< PortStatistics > newStatsCollection)
Updates the port statistics of the specified device using the give port statistics.
PortStatistics calcDeltaStats (DeviceId deviceId, PortStatistics prvStats, PortStatistics newStats)
Calculate delta statistics by subtracting previous from new statistics.
List< PortStatistics > getPortStatistics (DeviceId deviceId)
Returns the list of port statistics of the specified device.
List< PortStatistics > getPortDeltaStatistics (DeviceId deviceId)
Returns the list of delta port statistics of the specified device.
boolean isAvailable (DeviceId deviceId)
Indicates whether the specified device is available/online.
Iterable< Device > getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
DeviceEvent removeDevice (DeviceId deviceId)
Administratively removes the specified device from the store.
Protected Attributes
StorageService storageService
MastershipService mastershipService
MastershipTermService mastershipTermService
DeviceClockService deviceClockService
ClusterCommunicationService clusterCommunicator
ClusterService clusterService
Static Protected Attributes
static final KryoSerializer SERIALIZER
static final KryoNamespace.Builder SERIALIZER_BUILDER
Detailed Description
Manages the inventory of devices using a.
EventuallyConsistentMap
.
Definition at line 112 of file ECDeviceStore.java.
Member Function Documentation
void org.onosproject.store.device.impl.ECDeviceStore.activate ()
Definition at line 180 of file ECDeviceStore.java.
References org.onosproject.store.serializers.KryoNamespaces.API, org.onosproject.store.device.impl.ECDeviceStore.SERIALIZER_BUILDER, org.onosproject.store.device.impl.ECDeviceStore.storageService, and org.onosproject.store.service.Serializer.using().
PortStatistics org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats (DeviceId deviceId, PortStatistics prvStats, PortStatistics newStats)
Calculate delta statistics by subtracting previous from new statistics.
Parameters
deviceId device indentifier
prvStats previous port statistics
newStats new port statistics
Returns
PortStatistics
Definition at line 597 of file ECDeviceStore.java.
References org.onosproject.net.device.PortStatistics.bytesReceived(), org.onosproject.net.device.PortStatistics.bytesSent(), find-flow.deviceId, org.onosproject.net.device.PortStatistics.durationNano(), org.onosproject.net.device.PortStatistics.durationSec(), org.onosproject.net.device.PortStatistics.packetsReceived(), org.onosproject.net.device.PortStatistics.packetsRxDropped(), org.onosproject.net.device.PortStatistics.packetsRxErrors(), org.onosproject.net.device.PortStatistics.packetsSent(), org.onosproject.net.device.PortStatistics.packetsTxDropped(), org.onosproject.net.device.PortStatistics.packetsTxErrors(), and org.onosproject.net.device.PortStatistics.port().
Referenced by org.onosproject.store.device.impl.ECDeviceStore.updatePortStatistics().
DeviceEvent org.onosproject.store.device.impl.ECDeviceStore.createOrUpdateDevice (ProviderId providerId, DeviceId deviceId, DeviceDescription deviceDescription)
Creates a new infrastructure device, or updates an existing one using the supplied device description.
Parameters
providerId provider identifier
deviceId device identifier
deviceDescription device description
Returns
ready to send event describing what occurred; null if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 281 of file ECDeviceStore.java.
References find-flow.deviceId, and org.onosproject.cluster.NodeId.equals().
void org.onosproject.store.device.impl.ECDeviceStore.deactivate ()
Definition at line 249 of file ECDeviceStore.java.
Iterable<Device> org.onosproject.store.device.impl.ECDeviceStore.getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Returns
device collection
Implements org.onosproject.net.device.DeviceStore.
Definition at line 648 of file ECDeviceStore.java.
Device org.onosproject.store.device.impl.ECDeviceStore.getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
Parameters
deviceId device identifier
Returns
device
Implements org.onosproject.net.device.DeviceStore.
Definition at line 276 of file ECDeviceStore.java.
References find-flow.deviceId.
int org.onosproject.store.device.impl.ECDeviceStore.getDeviceCount ()
Returns the number of devices known to the system.
Returns
number of devices
Implements org.onosproject.net.device.DeviceStore.
Definition at line 271 of file ECDeviceStore.java.
Iterable<Device> org.onosproject.store.device.impl.ECDeviceStore.getDevices ()
Returns an iterable collection of all devices known to the system.
Returns
device collection
Implements org.onosproject.net.device.DeviceStore.
Definition at line 266 of file ECDeviceStore.java.
Port org.onosproject.store.device.impl.ECDeviceStore.getPort (DeviceId deviceId, PortNumber portNumber)
Returns the specified device port.
Parameters
deviceId device identifier
portNumber port number
Returns
device port
Implements org.onosproject.net.device.DeviceStore.
Definition at line 552 of file ECDeviceStore.java.
References find-flow.deviceId.
List<PortStatistics> org.onosproject.store.device.impl.ECDeviceStore.getPortDeltaStatistics (DeviceId deviceId)
Returns the list of delta port statistics of the specified device.
Parameters
deviceId device identifier
Returns
list of delta port statistics of all ports of the device
Implements org.onosproject.net.device.DeviceStore.
Definition at line 634 of file ECDeviceStore.java.
References find-flow.deviceId.
List<Port> org.onosproject.store.device.impl.ECDeviceStore.getPorts (DeviceId deviceId)
Returns the list of ports that belong to the specified device.
Parameters
deviceId device identifier
Returns
list of device ports
Implements org.onosproject.net.device.DeviceStore.
Definition at line 547 of file ECDeviceStore.java.
References find-flow.deviceId.
List<PortStatistics> org.onosproject.store.device.impl.ECDeviceStore.getPortStatistics (DeviceId deviceId)
Returns the list of port statistics of the specified device.
Parameters
deviceId device identifier
Returns
list of port statistics of all ports of the device
Implements org.onosproject.net.device.DeviceStore.
Definition at line 625 of file ECDeviceStore.java.
References find-flow.deviceId.
boolean org.onosproject.store.device.impl.ECDeviceStore.isAvailable (DeviceId deviceId)
Indicates whether the specified device is available/online.
Parameters
deviceId device identifier
Returns
true if device is available
Implements org.onosproject.net.device.DeviceStore.
Definition at line 643 of file ECDeviceStore.java.
References find-flow.deviceId.
DeviceEvent org.onosproject.store.device.impl.ECDeviceStore.markOffline (DeviceId deviceId)
Removes the specified infrastructure device.
Parameters
deviceId device identifier
Returns
ready to send event describing what occurred; null if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 397 of file ECDeviceStore.java.
References find-flow.deviceId.
DeviceEvent org.onosproject.store.device.impl.ECDeviceStore.removeDevice (DeviceId deviceId)
Administratively removes the specified device from the store.
Parameters
deviceId device to be removed
Returns
null if no such device, or was forwarded to remove master
Implements org.onosproject.net.device.DeviceStore.
Definition at line 653 of file ECDeviceStore.java.
References find-flow.deviceId, org.onosproject.cluster.NodeId.equals(), org.onosproject.net.MastershipRole.MASTER, and org.onosproject.net.MastershipRole.NONE.
List<DeviceEvent> org.onosproject.store.device.impl.ECDeviceStore.updatePorts (ProviderId providerId, DeviceId deviceId, List< PortDescription > portDescriptions)
Updates the ports of the specified infrastructure device using the given list of port descriptions.
The list is assumed to be comprehensive.
Parameters
providerId provider identifier
deviceId device identifier
portDescriptions list of port descriptions
Returns
ready to send events describing what occurred; empty list if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 404 of file ECDeviceStore.java.
References find-flow.deviceId, and org.onosproject.cluster.NodeId.equals().
DeviceEvent org.onosproject.store.device.impl.ECDeviceStore.updatePortStatistics (ProviderId providerId, DeviceId deviceId, Collection< PortStatistics > portStats)
Updates the port statistics of the specified device using the give port statistics.
Parameters
providerId provider identifier
deviceId device identifier
portStats list of port statistics
Returns
ready to send event describing what occurred;
Implements org.onosproject.net.device.DeviceStore.
Definition at line 557 of file ECDeviceStore.java.
References org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), find-flow.deviceId, and obeliskHostCheck.port.
DeviceEvent org.onosproject.store.device.impl.ECDeviceStore.updatePortStatus (ProviderId providerId, DeviceId deviceId, PortDescription portDescription)
Updates the port status of the specified infrastructure device using the given port description.
Parameters
providerId provider identifier
deviceId device identifier
portDescription port description
Returns
ready to send event describing what occurred; null if no change
Implements org.onosproject.net.device.DeviceStore.
Definition at line 537 of file ECDeviceStore.java.
References org.onosproject.net.device.PortDescription.portNumber().
Member Data Documentation
ClusterCommunicationService org.onosproject.store.device.impl.ECDeviceStore.clusterCommunicator protected
Definition at line 144 of file ECDeviceStore.java.
ClusterService org.onosproject.store.device.impl.ECDeviceStore.clusterService protected
Definition at line 147 of file ECDeviceStore.java.
DeviceClockService org.onosproject.store.device.impl.ECDeviceStore.deviceClockService protected
Definition at line 141 of file ECDeviceStore.java.
MastershipService org.onosproject.store.device.impl.ECDeviceStore.mastershipService protected
Definition at line 135 of file ECDeviceStore.java.
MastershipTermService org.onosproject.store.device.impl.ECDeviceStore.mastershipTermService protected
Definition at line 138 of file ECDeviceStore.java.
final KryoSerializer org.onosproject.store.device.impl.ECDeviceStore.SERIALIZER static protected
Initial value:
= new KryoSerializer() {
        @Override
        protected void setupKryoPool() {
            serializerPool = KryoNamespace.newBuilder()
                    .register(DistributedStoreSerializers.STORE_COMMON)
                    .nextId(DistributedStoreSerializers.STORE_CUSTOM_BEGIN)
                    .register(DeviceInjectedEvent.class)
                    .register(PortInjectedEvent.class)
                    .build();
        }
    }
Definition at line 159 of file ECDeviceStore.java.
final KryoNamespace.Builder org.onosproject.store.device.impl.ECDeviceStore.SERIALIZER_BUILDER static protected
Initial value:
= KryoNamespace.newBuilder()
            .register(KryoNamespaces.API)
            .register(DeviceKey.class)
            .register(PortKey.class)
            .register(DeviceKey.class)
            .register(PortKey.class)
            .register(MastershipBasedTimestamp.class)
Definition at line 171 of file ECDeviceStore.java.
Referenced by org.onosproject.store.device.impl.ECDeviceStore.activate().
StorageService org.onosproject.store.device.impl.ECDeviceStore.storageService protected
Definition at line 132 of file ECDeviceStore.java.
Referenced by org.onosproject.store.device.impl.ECDeviceStore.activate().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/device/impl/ECDeviceStore.java