onos: org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp Class Reference
org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp Class Reference
Implements BGP attribute Is Is Administrative area.
Public Member Functions
BgpLinkAttrIsIsAdminstGrp (long isisAdminGrp)
Constructor to initialize the values.
long linkAttrIsIsAdminGrp ()
Link attributes of ISIS administrative group area.
short getType ()
Returns the Type of BGP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
String toString ()
int compareTo (Object o)
Compares two objects.
Static Public Member Functions
static BgpLinkAttrIsIsAdminstGrp of (final long isisAdminGrp)
Returns object of this class with specified values.
static BgpLinkAttrIsIsAdminstGrp read (ChannelBuffer cb) throws BgpParseException
Reads the BGP link attributes of ISIS administrative group area.
Static Public Attributes
static final int ATTRLINK_PROTECTIONTYPE = 1088
static final int ISIS_ADMIN_DATA_LEN = 4
Static Protected Attributes
static final Logger log
Detailed Description
Implements BGP attribute Is Is Administrative area.
Definition at line 33 of file BgpLinkAttrIsIsAdminstGrp.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.BgpLinkAttrIsIsAdminstGrp (long isisAdminGrp)
Constructor to initialize the values.
Parameters
isisAdminGrp ISIS protocol admin group
Definition at line 49 of file BgpLinkAttrIsIsAdminstGrp.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.equals(), and org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.of().
Member Function Documentation
int org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.compareTo (Object o)
Compares two objects.
Parameters
o object
Returns
result after comparing two objects
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 132 of file BgpLinkAttrIsIsAdminstGrp.java.
boolean org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.equals (Object obj)
Definition at line 107 of file BgpLinkAttrIsIsAdminstGrp.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.BgpLinkAttrIsIsAdminstGrp().
short org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.getType ()
Returns the Type of BGP Message.
Returns
short value of type
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 97 of file BgpLinkAttrIsIsAdminstGrp.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.ATTRLINK_PROTECTIONTYPE.
int org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.hashCode ()
Definition at line 102 of file BgpLinkAttrIsIsAdminstGrp.java.
long org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.linkAttrIsIsAdminGrp ()
Link attributes of ISIS administrative group area.
Returns
long value of the administrative group area
Definition at line 92 of file BgpLinkAttrIsIsAdminstGrp.java.
static BgpLinkAttrIsIsAdminstGrp org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.of (final long isisAdminGrp) static
Returns object of this class with specified values.
Parameters
isisAdminGrp ISIS admin group
Returns
object of BgpLinkAttrIsIsAdminstGrp
Definition at line 59 of file BgpLinkAttrIsIsAdminstGrp.java.
References org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.BgpLinkAttrIsIsAdminstGrp().
static BgpLinkAttrIsIsAdminstGrp org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.read (ChannelBuffer cb) throws BgpParseException static
Reads the BGP link attributes of ISIS administrative group area.
Parameters
cb Channel buffer
Returns
object of type BgpLinkAttrIsIsAdminstGrp
Exceptions
BgpParseException while parsing BgpLinkAttrIsIsAdminstGrp
Definition at line 70 of file BgpLinkAttrIsIsAdminstGrp.java.
References org.onosproject.bgpio.types.BgpErrorType.ATTRIBUTE_LENGTH_ERROR, org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.ISIS_ADMIN_DATA_LEN, and org.onosproject.bgpio.types.BgpErrorType.UPDATE_MESSAGE_ERROR.
String org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.toString ()
Definition at line 126 of file BgpLinkAttrIsIsAdminstGrp.java.
int org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.write (ChannelBuffer cb)
Writes the byte Stream of BGP Message to channel buffer.
Parameters
cb channel buffer
Returns
length written to channel buffer
Implements org.onosproject.bgpio.types.BgpValueType.
Definition at line 120 of file BgpLinkAttrIsIsAdminstGrp.java.
Member Data Documentation
final int org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.ATTRLINK_PROTECTIONTYPE = 1088 static
Definition at line 38 of file BgpLinkAttrIsIsAdminstGrp.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.getType().
final int org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.ISIS_ADMIN_DATA_LEN = 4 static
Definition at line 39 of file BgpLinkAttrIsIsAdminstGrp.java.
Referenced by org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.read().
final Logger org.onosproject.bgpio.types.attr.BgpLinkAttrIsIsAdminstGrp.log static protected
Initial value:
= LoggerFactory
            .getLogger(BgpLinkAttrIsIsAdminstGrp.class)
Definition at line 35 of file BgpLinkAttrIsIsAdminstGrp.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/attr/BgpLinkAttrIsIsAdminstGrp.java