onos: org.onosproject.flowanalyzer.MockLinkService Class Reference
org.onosproject.flowanalyzer.MockLinkService Class Reference
Created by nikcheerla on 7/21/15.
Public Member Functions
int getLinkCount ()
Returns the count of all known infrastructure links.
Iterable< Link > getLinks ()
Returns a collection of all known infrastructure links.
Set< Link > getDeviceLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to and from the specified device.
Set< Link > getDeviceEgressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading from the specified device.
Set< Link > getDeviceIngressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to the specified device.
Set< Link > getEgressLinks (ConnectPoint pt)
Returns set of all infrastructure links leading from the specified connection point.
Set< Link > getIngressLinks (ConnectPoint pt)
Returns set of all infrastructure links leading to the specified connection point.
Set< Link > getLinks (ConnectPoint pt)
Returns set of all infrastructure links leading to and from the specified connection point.
void addLink (String device, long port, String device2, long port2)
Public Member Functions inherited from org.onosproject.net.link.LinkServiceAdapter
int getLinkCount ()
Returns the count of all known infrastructure links.
Iterable< Link > getLinks ()
Returns a collection of all known infrastructure links.
Iterable< Link > getActiveLinks ()
Returns a collection of all active infrastructure links.
Set< Link > getDeviceLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to and from the specified device.
Set< Link > getDeviceEgressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading from the specified device.
Set< Link > getDeviceIngressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to the specified device.
Set< Link > getLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to and from the specified connection point.
Set< Link > getEgressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading from the specified connection point.
Set< Link > getIngressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to the specified connection point.
Link getLink (ConnectPoint src, ConnectPoint dst)
Returns the infrastructure links between the specified source and destination connection points.
void addListener (LinkListener listener)
void removeListener (LinkListener listener)
Detailed Description
Created by nikcheerla on 7/21/15.
Definition at line 26 of file MockLinkService.java.
Member Function Documentation
void org.onosproject.flowanalyzer.MockLinkService.addLink (String device, long port, String device2, long port2)
Definition at line 103 of file MockLinkService.java.
References create-flow.device, and org.onosproject.net.PortNumber.portNumber().
Referenced by obelisk.ObeliskTopo.__init__(), topo-200sw-linkalarm.MyTopo.__init__(), chordal.chordalTopo.__init__(), rftesttopo.ReactiveForwardingTestTopo.__init__(), attmpls.AttMplsTopo.__init__(), optical2.OpticalTopo.__init__(), newFuncTopo.MyTopo.__init__(), onos.ControlNetwork.__init__(), optical2.OpticalTopo.addIntf(), optical.OpticalTopo.addIntf(), metro.FabricDomain.addTether(), fractal.FractalTopo.build(), opticalTestBig.BigOpticalTopo.build(), opticalTest.SmallOpticalTopo.build(), tower.TowerTopo.build(), attmplsfast.AttMplsTopo.build(), optical.OpticalTopo.build(), tutorial.SdnIpTopo.build(), tutorial_ipv6.SdnIpTopo.build(), metro.OpticalDomain.build(), and metro.FabricDomain.build().
Set<Link> org.onosproject.flowanalyzer.MockLinkService.getDeviceEgressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading from the specified device.
Parameters
deviceId device identifier
Returns
set of device egress links
Implements org.onosproject.net.link.LinkService.
Definition at line 48 of file MockLinkService.java.
Referenced by org.onosproject.flowanalyzer.MockLinkService.getDeviceLinks().
Set<Link> org.onosproject.flowanalyzer.MockLinkService.getDeviceIngressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to the specified device.
Parameters
deviceId device identifier
Returns
set of device ingress links
Implements org.onosproject.net.link.LinkService.
Definition at line 59 of file MockLinkService.java.
Referenced by org.onosproject.flowanalyzer.MockLinkService.getDeviceLinks().
Set<Link> org.onosproject.flowanalyzer.MockLinkService.getDeviceLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to and from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implements org.onosproject.net.link.LinkService.
Definition at line 41 of file MockLinkService.java.
References create-intent.egress, org.onosproject.flowanalyzer.MockLinkService.getDeviceEgressLinks(), and org.onosproject.flowanalyzer.MockLinkService.getDeviceIngressLinks().
Set<Link> org.onosproject.flowanalyzer.MockLinkService.getEgressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading from the specified connection point.
Parameters
connectPoint connection point
Returns
set of device egress links
Implements org.onosproject.net.link.LinkService.
Definition at line 71 of file MockLinkService.java.
Set<Link> org.onosproject.flowanalyzer.MockLinkService.getIngressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to the specified connection point.
Parameters
connectPoint connection point
Returns
set of device ingress links
Implements org.onosproject.net.link.LinkService.
Definition at line 82 of file MockLinkService.java.
int org.onosproject.flowanalyzer.MockLinkService.getLinkCount ()
Returns the count of all known infrastructure links.
Returns
number of infrastructure links
Implements org.onosproject.net.link.LinkService.
Definition at line 31 of file MockLinkService.java.
Iterable<Link> org.onosproject.flowanalyzer.MockLinkService.getLinks ()
Returns a collection of all known infrastructure links.
Returns
all infrastructure links
Implements org.onosproject.net.link.LinkService.
Definition at line 36 of file MockLinkService.java.
Set<Link> org.onosproject.flowanalyzer.MockLinkService.getLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to and from the specified connection point.
Parameters
connectPoint connection point
Returns
set of links
Implements org.onosproject.net.link.LinkService.
Definition at line 93 of file MockLinkService.java.
The documentation for this class was generated from the following file:
apps/flowanalyzer/src/test/java/org/onosproject/flowanalyzer/MockLinkService.java