onos: org.onosproject.pcepio.types.IPv4SubObject Class Reference
org.onosproject.pcepio.types.IPv4SubObject Class Reference
Provides IPv4 Sub Object.
Public Member Functions
IPv4SubObject (int ipAddr)
Constructor to initialize ipv4 address.
IPv4SubObject (int ipAddress, byte prefixLen, byte resvd)
constructor to initialize ipAddress, prefixLen and resvd.
byte getPrefixLen ()
Returns prefixLen of IPv4 IP address.
int getIpAddress ()
Returns value of IPv4 IP address.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static IPv4SubObject of (int ipAddress, byte prefixLen, byte resvd)
Returns a new instance of IPv4SubObject.
static PcepValueType read (ChannelBuffer c)
Reads the channel buffer and returns object of IPv4SubObject.
Static Public Attributes
static final byte TYPE = 0x01
static final byte LENGTH = 8
static final byte VALUE_LENGTH = 6
static final byte OBJ_LENGTH = 8
static final byte LBIT = 0
static final int SHIFT_LBIT_POSITION = 7
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IPv4SubObject.class)
Detailed Description
Provides IPv4 Sub Object.
Definition at line 35 of file IPv4SubObject.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IPv4SubObject.IPv4SubObject (int ipAddr)
Constructor to initialize ipv4 address.
Parameters
ipAddr ipv4 address
Definition at line 63 of file IPv4SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv4SubObject.equals(), org.onosproject.pcepio.types.IPv4SubObject.of(), and org.onosproject.pcepio.types.IPv4SubObject.read().
org.onosproject.pcepio.types.IPv4SubObject.IPv4SubObject (int ipAddress, byte prefixLen, byte resvd)
constructor to initialize ipAddress, prefixLen and resvd.
Parameters
ipAddress ipv4 address
prefixLen prefix length
resvd reserved flags value
Definition at line 74 of file IPv4SubObject.java.
Member Function Documentation
boolean org.onosproject.pcepio.types.IPv4SubObject.equals (Object obj)
Definition at line 131 of file IPv4SubObject.java.
References org.onosproject.pcepio.types.IPv4SubObject.IPv4SubObject().
int org.onosproject.pcepio.types.IPv4SubObject.getIpAddress ()
Returns value of IPv4 IP address.
Returns
int value of ipv4 address
Definition at line 106 of file IPv4SubObject.java.
short org.onosproject.pcepio.types.IPv4SubObject.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 121 of file IPv4SubObject.java.
References org.onosproject.pcepio.types.IPv4SubObject.LENGTH.
byte org.onosproject.pcepio.types.IPv4SubObject.getPrefixLen ()
Returns prefixLen of IPv4 IP address.
Returns
byte value of rawValue
Definition at line 97 of file IPv4SubObject.java.
short org.onosproject.pcepio.types.IPv4SubObject.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 116 of file IPv4SubObject.java.
References org.onosproject.pcepio.types.IPv4SubObject.TYPE.
PcepVersion org.onosproject.pcepio.types.IPv4SubObject.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 111 of file IPv4SubObject.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IPv4SubObject.hashCode ()
Definition at line 126 of file IPv4SubObject.java.
static IPv4SubObject org.onosproject.pcepio.types.IPv4SubObject.of (int ipAddress, byte prefixLen, byte resvd) static
Returns a new instance of IPv4SubObject.
Parameters
ipAddress ipv4 address
prefixLen prefix length
resvd reserved flags value
Returns
object of IPv4SubObject
Definition at line 88 of file IPv4SubObject.java.
References org.onosproject.pcepio.types.IPv4SubObject.IPv4SubObject().
static PcepValueType org.onosproject.pcepio.types.IPv4SubObject.read (ChannelBuffer c) static
Reads the channel buffer and returns object of IPv4SubObject.
Parameters
c type of channel buffer
Returns
object of IPv4SubObject
Definition at line 149 of file IPv4SubObject.java.
References org.onosproject.pcepio.types.IPv4SubObject.IPv4SubObject().
String org.onosproject.pcepio.types.IPv4SubObject.toString ()
Definition at line 172 of file IPv4SubObject.java.
References org.onosproject.pcepio.types.IPv4SubObject.LENGTH, and org.onosproject.pcepio.types.IPv4SubObject.TYPE.
int org.onosproject.pcepio.types.IPv4SubObject.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 157 of file IPv4SubObject.java.
References org.onosproject.pcepio.types.IPv4SubObject.LBIT, org.onosproject.pcepio.types.IPv4SubObject.OBJ_LENGTH, org.onosproject.pcepio.types.IPv4SubObject.SHIFT_LBIT_POSITION, and org.onosproject.pcepio.types.IPv4SubObject.TYPE.
Member Data Documentation
final byte org.onosproject.pcepio.types.IPv4SubObject.LBIT = 0 static
Definition at line 52 of file IPv4SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv4SubObject.write().
final byte org.onosproject.pcepio.types.IPv4SubObject.LENGTH = 8 static
Definition at line 49 of file IPv4SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv4SubObject.getLength(), and org.onosproject.pcepio.types.IPv4SubObject.toString().
final Logger org.onosproject.pcepio.types.IPv4SubObject.log = LoggerFactory.getLogger(IPv4SubObject.class) static protected
Definition at line 46 of file IPv4SubObject.java.
final byte org.onosproject.pcepio.types.IPv4SubObject.OBJ_LENGTH = 8 static
Definition at line 51 of file IPv4SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv4SubObject.write().
final int org.onosproject.pcepio.types.IPv4SubObject.SHIFT_LBIT_POSITION = 7 static
Definition at line 53 of file IPv4SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv4SubObject.write().
final byte org.onosproject.pcepio.types.IPv4SubObject.TYPE = 0x01 static
Definition at line 48 of file IPv4SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv4SubObject.getType(), org.onosproject.pcepio.types.IPv4SubObject.toString(), and org.onosproject.pcepio.types.IPv4SubObject.write().
final byte org.onosproject.pcepio.types.IPv4SubObject.VALUE_LENGTH = 6 static
Definition at line 50 of file IPv4SubObject.java.
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IPv4SubObject.java