onos: org.onosproject.pcepio.types.IPv6SubObject Class Reference
org.onosproject.pcepio.types.IPv6SubObject Class Reference
Provides IPv6 Sub Object.
Public Member Functions
IPv6SubObject (byte[] rawValue)
constructor to initialize rawValue with ipv6 address.
byte[] getValue ()
Returns value of IPv6 Sub Object.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static IPv6SubObject of (final byte[] raw)
To create instance of IPv6SubObject.
static IPv6SubObject read20Bytes (ChannelBuffer c)
Reads the channel buffer and returns object of IPv6SubObject.
Static Public Attributes
static final short TYPE = 0x02
static final short LENGTH = 20
static final byte VALUE_LENGTH = 18
static final IPv6SubObject NONE = new IPv6SubObject(NONE_VAL)
static final IPv6SubObject NO_MASK = new IPv6SubObject(NO_MASK_VAL)
static final IPv6SubObject FULL_MASK = NONE
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(IPv6SubObject.class)
Detailed Description
Provides IPv6 Sub Object.
Definition at line 32 of file IPv6SubObject.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.IPv6SubObject.IPv6SubObject (byte[] rawValue)
constructor to initialize rawValue with ipv6 address.
Parameters
rawValue ipv6 address
Definition at line 106 of file IPv6SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv6SubObject.equals(), and org.onosproject.pcepio.types.IPv6SubObject.of().
Member Function Documentation
boolean org.onosproject.pcepio.types.IPv6SubObject.equals (Object obj)
Definition at line 175 of file IPv6SubObject.java.
References org.onosproject.pcepio.types.IPv6SubObject.IPv6SubObject().
short org.onosproject.pcepio.types.IPv6SubObject.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 165 of file IPv6SubObject.java.
References org.onosproject.pcepio.types.IPv6SubObject.LENGTH.
short org.onosproject.pcepio.types.IPv6SubObject.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 160 of file IPv6SubObject.java.
References org.onosproject.pcepio.types.IPv6SubObject.TYPE.
byte [] org.onosproject.pcepio.types.IPv6SubObject.getValue ()
Returns value of IPv6 Sub Object.
Returns
byte array of ipv6 address
Definition at line 150 of file IPv6SubObject.java.
PcepVersion org.onosproject.pcepio.types.IPv6SubObject.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 155 of file IPv6SubObject.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.IPv6SubObject.hashCode ()
Definition at line 170 of file IPv6SubObject.java.
static IPv6SubObject org.onosproject.pcepio.types.IPv6SubObject.of (final byte[] raw) static
To create instance of IPv6SubObject.
Parameters
raw byte array of ipv6 address
Returns
object of IPv6SubObject
Definition at line 116 of file IPv6SubObject.java.
References org.onosproject.pcepio.types.IPv6SubObject.IPv6SubObject(), org.onosproject.pcepio.types.IPv6SubObject.NO_MASK, and org.onosproject.pcepio.types.IPv6SubObject.NONE.
static IPv6SubObject org.onosproject.pcepio.types.IPv6SubObject.read20Bytes (ChannelBuffer c) static
Reads the channel buffer and returns object of IPv6SubObject.
Parameters
c type of channel buffer
Returns
object of IPv6SubObject
Definition at line 201 of file IPv6SubObject.java.
String org.onosproject.pcepio.types.IPv6SubObject.toString ()
Definition at line 208 of file IPv6SubObject.java.
References org.onosproject.pcepio.types.IPv6SubObject.LENGTH, and org.onosproject.pcepio.types.IPv6SubObject.TYPE.
int org.onosproject.pcepio.types.IPv6SubObject.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 187 of file IPv6SubObject.java.
References org.onosproject.pcepio.types.IPv6SubObject.LENGTH, and org.onosproject.pcepio.types.IPv6SubObject.TYPE.
Member Data Documentation
final IPv6SubObject org.onosproject.pcepio.types.IPv6SubObject.FULL_MASK = NONE static
Definition at line 97 of file IPv6SubObject.java.
final short org.onosproject.pcepio.types.IPv6SubObject.LENGTH = 20 static
Definition at line 87 of file IPv6SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv6SubObject.getLength(), org.onosproject.pcepio.types.IPv6SubObject.toString(), and org.onosproject.pcepio.types.IPv6SubObject.write().
final Logger org.onosproject.pcepio.types.IPv6SubObject.log = LoggerFactory.getLogger(IPv6SubObject.class) static protected
Definition at line 84 of file IPv6SubObject.java.
final IPv6SubObject org.onosproject.pcepio.types.IPv6SubObject.NO_MASK = new IPv6SubObject(NO_MASK_VAL) static
Definition at line 96 of file IPv6SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv6SubObject.of().
final IPv6SubObject org.onosproject.pcepio.types.IPv6SubObject.NONE = new IPv6SubObject(NONE_VAL) static
Definition at line 91 of file IPv6SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv6SubObject.of().
final short org.onosproject.pcepio.types.IPv6SubObject.TYPE = 0x02 static
Definition at line 86 of file IPv6SubObject.java.
Referenced by org.onosproject.pcepio.types.IPv6SubObject.getType(), org.onosproject.pcepio.types.IPv6SubObject.toString(), and org.onosproject.pcepio.types.IPv6SubObject.write().
final byte org.onosproject.pcepio.types.IPv6SubObject.VALUE_LENGTH = 18 static
Definition at line 88 of file IPv6SubObject.java.
Referenced by org.onosproject.pcepio.protocol.ver1.PcepRroObjectVer1.parseSubObjects(), and org.onosproject.pcepio.protocol.ver1.PcepEroObjectVer1.parseSubObjects().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/IPv6SubObject.java