onos: org.onosproject.pcepio.types.MPLSProtocolMaskTlv Class Reference
org.onosproject.pcepio.types.MPLSProtocolMaskTlv Class Reference
Provides MPLS Protocol Mask.
Public Member Functions
MPLSProtocolMaskTlv (byte rawValue)
constructor to initialize rawValue.
MPLSProtocolMaskTlv (boolean bLFlag, boolean bRFlag)
constructor to initialize different Flags.
boolean getbLFlag ()
Returns L-flag.
boolean getbRFlag ()
Returns R-flag.
byte getByte ()
Returns raw value.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static MPLSProtocolMaskTlv of (final byte raw)
Returns newly created MPLSProtocolMaskTlv object.
static PcepValueType read (ChannelBuffer c)
Reads the channel buffer and returns object of MPLS Protocol Mask Tlv.
Static Public Attributes
static final short TYPE = 1094
static final short LENGTH = 1
static final byte LFLAG_SET = (byte) 0x80
static final byte RFLAG_SET = 0x40
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(MPLSProtocolMaskTlv.class)
Detailed Description
Provides MPLS Protocol Mask.
Definition at line 30 of file MPLSProtocolMaskTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.MPLSProtocolMaskTlv.MPLSProtocolMaskTlv (byte rawValue)
constructor to initialize rawValue.
Parameters
rawValue MPLS Protocol Mask Flag Bits
Definition at line 58 of file MPLSProtocolMaskTlv.java.
References org.onosproject.pcepio.types.MPLSProtocolMaskTlv.LFLAG_SET, and org.onosproject.pcepio.types.MPLSProtocolMaskTlv.RFLAG_SET.
Referenced by org.onosproject.pcepio.types.MPLSProtocolMaskTlv.equals(), org.onosproject.pcepio.types.MPLSProtocolMaskTlv.of(), and org.onosproject.pcepio.types.MPLSProtocolMaskTlv.read().
org.onosproject.pcepio.types.MPLSProtocolMaskTlv.MPLSProtocolMaskTlv (boolean bLFlag, boolean bRFlag)
constructor to initialize different Flags.
Parameters
bLFlag L-flag
bRFlag R-flag
Definition at line 71 of file MPLSProtocolMaskTlv.java.
Member Function Documentation
boolean org.onosproject.pcepio.types.MPLSProtocolMaskTlv.equals (Object obj)
Definition at line 140 of file MPLSProtocolMaskTlv.java.
References org.onosproject.pcepio.types.MPLSProtocolMaskTlv.MPLSProtocolMaskTlv().
boolean org.onosproject.pcepio.types.MPLSProtocolMaskTlv.getbLFlag ()
Returns L-flag.
Returns
bLFlag L-flag
Definition at line 93 of file MPLSProtocolMaskTlv.java.
boolean org.onosproject.pcepio.types.MPLSProtocolMaskTlv.getbRFlag ()
Returns R-flag.
Returns
bRFlag R-flag
Definition at line 102 of file MPLSProtocolMaskTlv.java.
byte org.onosproject.pcepio.types.MPLSProtocolMaskTlv.getByte ()
Returns raw value.
Returns
rawValue raw value
Definition at line 111 of file MPLSProtocolMaskTlv.java.
short org.onosproject.pcepio.types.MPLSProtocolMaskTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 126 of file MPLSProtocolMaskTlv.java.
References org.onosproject.pcepio.types.MPLSProtocolMaskTlv.LENGTH.
short org.onosproject.pcepio.types.MPLSProtocolMaskTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 121 of file MPLSProtocolMaskTlv.java.
References org.onosproject.pcepio.types.MPLSProtocolMaskTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.MPLSProtocolMaskTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 116 of file MPLSProtocolMaskTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.MPLSProtocolMaskTlv.hashCode ()
Definition at line 131 of file MPLSProtocolMaskTlv.java.
static MPLSProtocolMaskTlv org.onosproject.pcepio.types.MPLSProtocolMaskTlv.of (final byte raw) static
Returns newly created MPLSProtocolMaskTlv object.
Parameters
raw MPLS Protocol Mask Tlv
Returns
new object of MPLS Protocol Mask Tlv
Definition at line 84 of file MPLSProtocolMaskTlv.java.
References org.onosproject.pcepio.types.MPLSProtocolMaskTlv.MPLSProtocolMaskTlv().
static PcepValueType org.onosproject.pcepio.types.MPLSProtocolMaskTlv.read (ChannelBuffer c) static
Reads the channel buffer and returns object of MPLS Protocol Mask Tlv.
Parameters
c input channel buffer
Returns
object of MPLS Protocol Mask Tlv
Definition at line 181 of file MPLSProtocolMaskTlv.java.
References org.onosproject.pcepio.types.MPLSProtocolMaskTlv.LFLAG_SET, org.onosproject.pcepio.types.MPLSProtocolMaskTlv.MPLSProtocolMaskTlv(), and org.onosproject.pcepio.types.MPLSProtocolMaskTlv.RFLAG_SET.
String org.onosproject.pcepio.types.MPLSProtocolMaskTlv.toString ()
Definition at line 193 of file MPLSProtocolMaskTlv.java.
References org.onosproject.pcepio.types.MPLSProtocolMaskTlv.LENGTH, and org.onosproject.pcepio.types.MPLSProtocolMaskTlv.TYPE.
int org.onosproject.pcepio.types.MPLSProtocolMaskTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 156 of file MPLSProtocolMaskTlv.java.
References org.onosproject.pcepio.types.MPLSProtocolMaskTlv.LENGTH, org.onosproject.pcepio.types.MPLSProtocolMaskTlv.LFLAG_SET, org.onosproject.pcepio.types.MPLSProtocolMaskTlv.RFLAG_SET, and org.onosproject.pcepio.types.MPLSProtocolMaskTlv.TYPE.
Member Data Documentation
final short org.onosproject.pcepio.types.MPLSProtocolMaskTlv.LENGTH = 1 static
Definition at line 44 of file MPLSProtocolMaskTlv.java.
Referenced by org.onosproject.pcepio.types.MPLSProtocolMaskTlv.getLength(), org.onosproject.pcepio.types.MPLSProtocolMaskTlv.toString(), and org.onosproject.pcepio.types.MPLSProtocolMaskTlv.write().
final byte org.onosproject.pcepio.types.MPLSProtocolMaskTlv.LFLAG_SET = (byte) 0x80 static
Definition at line 45 of file MPLSProtocolMaskTlv.java.
Referenced by org.onosproject.pcepio.types.MPLSProtocolMaskTlv.MPLSProtocolMaskTlv(), org.onosproject.pcepio.types.MPLSProtocolMaskTlv.read(), and org.onosproject.pcepio.types.MPLSProtocolMaskTlv.write().
final Logger org.onosproject.pcepio.types.MPLSProtocolMaskTlv.log = LoggerFactory.getLogger(MPLSProtocolMaskTlv.class) static protected
Definition at line 41 of file MPLSProtocolMaskTlv.java.
final byte org.onosproject.pcepio.types.MPLSProtocolMaskTlv.RFLAG_SET = 0x40 static
Definition at line 46 of file MPLSProtocolMaskTlv.java.
Referenced by org.onosproject.pcepio.types.MPLSProtocolMaskTlv.MPLSProtocolMaskTlv(), org.onosproject.pcepio.types.MPLSProtocolMaskTlv.read(), and org.onosproject.pcepio.types.MPLSProtocolMaskTlv.write().
final short org.onosproject.pcepio.types.MPLSProtocolMaskTlv.TYPE = 1094 static
Definition at line 43 of file MPLSProtocolMaskTlv.java.
Referenced by org.onosproject.pcepio.types.MPLSProtocolMaskTlv.getType(), org.onosproject.pcepio.types.MPLSProtocolMaskTlv.toString(), and org.onosproject.pcepio.types.MPLSProtocolMaskTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/MPLSProtocolMaskTlv.java