onos: org.onosproject.net.packet.DefaultPacketRequest Class Reference
org.onosproject.net.packet.DefaultPacketRequest Class Reference
Default implementation of a packet request.
Public Member Functions
DefaultPacketRequest (TrafficSelector selector, PacketPriority priority, ApplicationId appId)
Creates a new packet request.
TrafficSelector selector ()
Obtain the traffic selector.
PacketPriority priority ()
Obtain the priority.
ApplicationId appId ()
Obtain the application id.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of a packet request.
Definition at line 27 of file DefaultPacketRequest.java.
Constructor & Destructor Documentation
org.onosproject.net.packet.DefaultPacketRequest.DefaultPacketRequest (TrafficSelector selector, PacketPriority priority, ApplicationId appId)
Creates a new packet request.
Parameters
selector traffic selector
priority intercept priority
appId application id
Definition at line 39 of file DefaultPacketRequest.java.
References org.onosproject.net.packet.DefaultPacketRequest.appId(), org.onosproject.net.packet.DefaultPacketRequest.priority(), and org.onosproject.net.packet.DefaultPacketRequest.selector().
Referenced by org.onosproject.net.packet.DefaultPacketRequest.equals().
Member Function Documentation
ApplicationId org.onosproject.net.packet.DefaultPacketRequest.appId ()
Obtain the application id.
Returns
an application id
Implements org.onosproject.net.packet.PacketRequest.
Definition at line 54 of file DefaultPacketRequest.java.
Referenced by org.onosproject.net.packet.DefaultPacketRequest.DefaultPacketRequest(), org.onosproject.net.packet.DefaultPacketRequest.hashCode(), and org.onosproject.net.packet.DefaultPacketRequest.toString().
boolean org.onosproject.net.packet.DefaultPacketRequest.equals (Object obj)
Definition at line 64 of file DefaultPacketRequest.java.
References org.onosproject.net.packet.DefaultPacketRequest.DefaultPacketRequest(), and org.onosproject.net.packet.DefaultPacketRequest.equals().
Referenced by org.onosproject.net.packet.DefaultPacketRequest.equals().
int org.onosproject.net.packet.DefaultPacketRequest.hashCode ()
Definition at line 59 of file DefaultPacketRequest.java.
References org.onosproject.net.packet.DefaultPacketRequest.appId(), org.onosproject.net.packet.DefaultPacketRequest.priority(), and org.onosproject.net.packet.DefaultPacketRequest.selector().
PacketPriority org.onosproject.net.packet.DefaultPacketRequest.priority ()
Obtain the priority.
Returns
a PacketPriority
Implements org.onosproject.net.packet.PacketRequest.
Definition at line 50 of file DefaultPacketRequest.java.
Referenced by org.onosproject.net.packet.DefaultPacketRequest.DefaultPacketRequest(), org.onosproject.net.packet.DefaultPacketRequest.hashCode(), and org.onosproject.net.packet.DefaultPacketRequest.toString().
TrafficSelector org.onosproject.net.packet.DefaultPacketRequest.selector ()
Obtain the traffic selector.
Returns
a traffic selector
Implements org.onosproject.net.packet.PacketRequest.
Definition at line 46 of file DefaultPacketRequest.java.
Referenced by org.onosproject.net.packet.DefaultPacketRequest.DefaultPacketRequest(), org.onosproject.net.packet.DefaultPacketRequest.hashCode(), and org.onosproject.net.packet.DefaultPacketRequest.toString().
String org.onosproject.net.packet.DefaultPacketRequest.toString ()
Definition at line 78 of file DefaultPacketRequest.java.
References org.onosproject.net.packet.DefaultPacketRequest.appId(), org.onosproject.net.packet.DefaultPacketRequest.priority(), and org.onosproject.net.packet.DefaultPacketRequest.selector().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/packet/DefaultPacketRequest.java