onos: org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector Class Reference
org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector Class Reference
Efficiently and adaptively collects flow statistics for the specified switch.
Public Member Functions
synchronized void start ()
start adaptive flow statistic collection.
synchronized void stop ()
stop adaptive flow statistic collection.
synchronized void addWithFlowRule (FlowRule...flowRules)
add typed flow entry from flow rule into the internal flow table.
synchronized void addOrUpdateFlows (FlowEntry...flowEntries)
add or update typed flow entry from flow entry into the internal flow table.
synchronized void removeFlows (FlowRule...flowRules)
remove typed flow entry from the internal flow table.
void flowRemoved (FlowRule...flowRules)
remove typed flow entry from the internal flow table.
void pushFlowMetrics (List< FlowEntry > flowEntries)
add or update typed flow entry from flow entry into the internal flow table.
long getFlowMissingXid ()
returns flowMissingXid that indicates the execution of flowMissing process or not(NO_FLOW_MISSING_XID(-1)).
void setFlowMissingXid (long flowMissingXid)
set flowMissingXid, namely OFFlowStatsRequest match any ALL message Id.
Static Public Attributes
static final long NO_FLOW_MISSING_XID = (-1)
Detailed Description
Efficiently and adaptively collects flow statistics for the specified switch.
Definition at line 57 of file NewAdaptiveFlowStatsCollector.java.
Member Function Documentation
synchronized void org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.addOrUpdateFlows (FlowEntry... flowEntries)
add or update typed flow entry from flow entry into the internal flow table.
Parameters
flowEntries the flow entries
Definition at line 405 of file NewAdaptiveFlowStatsCollector.java.
References org.onosproject.net.flow.FlowEntry.bytes(), org.onosproject.openflow.controller.OpenFlowSwitch.getStringId(), org.onosproject.net.flow.FlowRule.id(), org.onosproject.net.flow.TypedStoredFlowEntry.FlowLiveType.IMMEDIATE_FLOW, org.onosproject.net.flow.FlowEntry.lastSeen(), org.onosproject.net.flow.FlowEntry.life(), and org.onosproject.net.flow.FlowEntry.state().
Referenced by org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.pushFlowMetrics().
synchronized void org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.addWithFlowRule (FlowRule... flowRules)
add typed flow entry from flow rule into the internal flow table.
Parameters
flowRules the flow rules
Definition at line 387 of file NewAdaptiveFlowStatsCollector.java.
References org.onosproject.net.flow.TypedStoredFlowEntry.FlowLiveType.IMMEDIATE_FLOW.
void org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.flowRemoved (FlowRule... flowRules)
remove typed flow entry from the internal flow table.
Parameters
flowRules the flow entries
Definition at line 475 of file NewAdaptiveFlowStatsCollector.java.
References org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.removeFlows().
long org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.getFlowMissingXid ()
returns flowMissingXid that indicates the execution of flowMissing process or not(NO_FLOW_MISSING_XID(-1)).
Returns
xid of missing flow
Definition at line 497 of file NewAdaptiveFlowStatsCollector.java.
void org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.pushFlowMetrics (List< FlowEntry > flowEntries)
add or update typed flow entry from flow entry into the internal flow table.
Parameters
flowEntries the flow entry list
Definition at line 486 of file NewAdaptiveFlowStatsCollector.java.
References org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.addOrUpdateFlows().
synchronized void org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.removeFlows (FlowRule... flowRules)
remove typed flow entry from the internal flow table.
Parameters
flowRules the flow entries
Definition at line 462 of file NewAdaptiveFlowStatsCollector.java.
Referenced by org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.flowRemoved().
void org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.setFlowMissingXid (long flowMissingXid)
set flowMissingXid, namely OFFlowStatsRequest match any ALL message Id.
Parameters
flowMissingXid the OFFlowStatsRequest message Id
Definition at line 507 of file NewAdaptiveFlowStatsCollector.java.
synchronized void org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.start ()
start adaptive flow statistic collection.
Definition at line 325 of file NewAdaptiveFlowStatsCollector.java.
synchronized void org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.stop ()
stop adaptive flow statistic collection.
Definition at line 362 of file NewAdaptiveFlowStatsCollector.java.
Member Data Documentation
final long org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.NO_FLOW_MISSING_XID = (-1) static
Definition at line 103 of file NewAdaptiveFlowStatsCollector.java.
The documentation for this class was generated from the following file:
providers/openflow/flow/src/main/java/org/onosproject/provider/of/flow/impl/NewAdaptiveFlowStatsCollector.java