onos: org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager Class Reference
org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager Class Reference
Provides implementation of the FloatingIp service.
Public Member Functions
void activate ()
void deactivate ()
Collection< FloatingIp > getFloatingIps ()
Returns a collection of the currently known floating IP.
FloatingIp getFloatingIp (FloatingIpId floatingIpId)
Returns the floatingIp with the specified identifier.
boolean exists (FloatingIpId floatingIpId)
Returns exists or not of specific floatingIp identifier.
boolean floatingIpIsUsed (IpAddress floatingIpAddr, FloatingIpId floatingIpId)
Returns is used or not of specific floating IP address.
boolean fixedIpIsUsed (IpAddress fixedIpAddr, TenantId tenantId, FloatingIpId floatingIpId)
Returns is used or not of specific fixed IP address.
boolean createFloatingIps (Collection< FloatingIp > floatingIps)
Creates new floatingIps.
boolean updateFloatingIps (Collection< FloatingIp > floatingIps)
Updates existing floatingIps.
boolean removeFloatingIps (Collection< FloatingIpId > floatingIpIds)
Removes the specified floatingIp from the store.
void addListener (FloatingIpListener listener)
Adds the specified listener to floating Ip manager.
void removeListener (FloatingIpListener listener)
Removes the specified listener to floating Ip manager.
Protected Attributes
EventuallyConsistentMap
< FloatingIpId, FloatingIp > floatingIpStore
ApplicationId appId
StorageService storageService
CoreService coreService
TenantNetworkService tenantNetworkService
VirtualPortService virtualPortService
RouterService routerService
Detailed Description
Provides implementation of the FloatingIp service.
Definition at line 63 of file FloatingIpManager.java.
Member Function Documentation
void org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.activate ()
Definition at line 95 of file FloatingIpManager.java.
References org.onosproject.store.serializers.KryoNamespaces.API, org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.appId, and org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.floatingIpStore.
void org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.addListener (FloatingIpListener listener)
Adds the specified listener to floating Ip manager.
Parameters
listener floating Ip listener
Implements org.onosproject.vtnrsc.floatingip.FloatingIpService.
Definition at line 257 of file FloatingIpManager.java.
boolean org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.createFloatingIps (Collection< FloatingIp > floatingIps)
Creates new floatingIps.
Parameters
floatingIps the collection of floatingIp
Returns
true if the identifier floatingIp has been created right
Implements org.onosproject.vtnrsc.floatingip.FloatingIpService.
Definition at line 174 of file FloatingIpManager.java.
References org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.floatingIpStore.
void org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.deactivate ()
Definition at line 114 of file FloatingIpManager.java.
boolean org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.exists (FloatingIpId floatingIpId)
Returns exists or not of specific floatingIp identifier.
Parameters
floatingIpId floatingIp identifier
Returns
true or false
Implements org.onosproject.vtnrsc.floatingip.FloatingIpService.
Definition at line 133 of file FloatingIpManager.java.
boolean org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.fixedIpIsUsed (IpAddress fixedIpAddr, TenantId tenantId, FloatingIpId floatingIpId)
Returns is used or not of specific fixed IP address.
Parameters
fixedIpAddr fixedIp address
tenantId the tenant identifier of floating IP
floatingIpId floatingIp identifier
Returns
true or false
Implements org.onosproject.vtnrsc.floatingip.FloatingIpService.
Definition at line 154 of file FloatingIpManager.java.
References org.onlab.packet.IpAddress.equals(), and org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.getFloatingIps().
boolean org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.floatingIpIsUsed (IpAddress floatingIpAddr, FloatingIpId floatingIpId)
Returns is used or not of specific floating IP address.
Parameters
floatingIpAddr floatingIp address
floatingIpId floatingIp identifier
Returns
true or false
Implements org.onosproject.vtnrsc.floatingip.FloatingIpService.
Definition at line 139 of file FloatingIpManager.java.
References org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.getFloatingIps().
FloatingIp org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.getFloatingIp (FloatingIpId floatingIpId)
Returns the floatingIp with the specified identifier.
Parameters
floatingIpId floatingIp identifier
Returns
floatingIp or null if one with the given identifier is not known
Implements org.onosproject.vtnrsc.floatingip.FloatingIpService.
Definition at line 127 of file FloatingIpManager.java.
Collection<FloatingIp> org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.getFloatingIps ()
Returns a collection of the currently known floating IP.
Returns
collection of floating IP
Implements org.onosproject.vtnrsc.floatingip.FloatingIpService.
Definition at line 122 of file FloatingIpManager.java.
Referenced by org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.fixedIpIsUsed(), and org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.floatingIpIsUsed().
boolean org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.removeFloatingIps (Collection< FloatingIpId > floatingIpIds)
Removes the specified floatingIp from the store.
Parameters
floatingIpIds the collection of floatingIp identifier
Returns
true if remove identifier floatingIp successfully
Implements org.onosproject.vtnrsc.floatingip.FloatingIpService.
Definition at line 233 of file FloatingIpManager.java.
References org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.floatingIpStore.
void org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.removeListener (FloatingIpListener listener)
Removes the specified listener to floating Ip manager.
Parameters
listener floating Ip listener
Implements org.onosproject.vtnrsc.floatingip.FloatingIpService.
Definition at line 263 of file FloatingIpManager.java.
boolean org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.updateFloatingIps (Collection< FloatingIp > floatingIps)
Updates existing floatingIps.
Parameters
floatingIps the collection of floatingIp
Returns
true if all floatingIp were updated successfully
Implements org.onosproject.vtnrsc.floatingip.FloatingIpService.
Definition at line 202 of file FloatingIpManager.java.
References org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.floatingIpStore.
Member Data Documentation
ApplicationId org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.appId protected
Definition at line 77 of file FloatingIpManager.java.
Referenced by org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.activate().
CoreService org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.coreService protected
Definition at line 83 of file FloatingIpManager.java.
EventuallyConsistentMap<FloatingIpId, FloatingIp> org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.floatingIpStore protected
Definition at line 76 of file FloatingIpManager.java.
Referenced by org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.activate(), org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.createFloatingIps(), org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.removeFloatingIps(), and org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.updateFloatingIps().
RouterService org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.routerService protected
Definition at line 92 of file FloatingIpManager.java.
StorageService org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.storageService protected
Definition at line 80 of file FloatingIpManager.java.
TenantNetworkService org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.tenantNetworkService protected
Definition at line 86 of file FloatingIpManager.java.
VirtualPortService org.onosproject.vtnrsc.floatingip.impl.FloatingIpManager.virtualPortService protected
Definition at line 89 of file FloatingIpManager.java.
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/floatingip/impl/FloatingIpManager.java