onos: org.onosproject.cord.gui.model.SubscriberUser Class Reference
org.onosproject.cord.gui.model.SubscriberUser Class Reference
Designates a user of a subscriber's account.
Public Member Functions
SubscriberUser (int id, String name, String mac, String level)
Constructs a subscriber user from the given parameters.
int id ()
Returns the internal identifier.
String name ()
Returns the display name.
String mac ()
Returns the MAC address of the associated device.
String urlFilterLevel ()
Returns the URL filter level.
void setUrlFilterLevel (String level)
Sets the URL filter level.
void setMemento (XosFunctionDescriptor f, XosFunction.Memento m)
Stores a memento for the given XOS function.
XosFunction.Memento getMemento (XosFunctionDescriptor f)
Returns the memento stored on this user, for the given XOS function.
void clearMementos ()
Clears the memento map.
String toString ()
Detailed Description
Designates a user of a subscriber's account.
Definition at line 26 of file SubscriberUser.java.
Constructor & Destructor Documentation
org.onosproject.cord.gui.model.SubscriberUser.SubscriberUser (int id, String name, String mac, String level)
Constructs a subscriber user from the given parameters.
Parameters
id internal identifier
name display name
mac MAC address of the associated device
level URL filter level
Definition at line 46 of file SubscriberUser.java.
References org.onosproject.cord.gui.model.SubscriberUser.id(), org.onosproject.cord.gui.model.SubscriberUser.mac(), and org.onosproject.cord.gui.model.SubscriberUser.name().
Member Function Documentation
void org.onosproject.cord.gui.model.SubscriberUser.clearMementos ()
Clears the memento map.
Definition at line 123 of file SubscriberUser.java.
XosFunction.Memento org.onosproject.cord.gui.model.SubscriberUser.getMemento (XosFunctionDescriptor f)
Returns the memento stored on this user, for the given XOS function.
Parameters
f XOS function
Returns
memento
Definition at line 116 of file SubscriberUser.java.
Referenced by org.onosproject.cord.gui.model.UrlFilterFunction.xosUrlApply().
int org.onosproject.cord.gui.model.SubscriberUser.id ()
Returns the internal identifier.
Returns
the identifier
Definition at line 58 of file SubscriberUser.java.
Referenced by org.onosproject.cord.gui.model.SubscriberUser.SubscriberUser().
String org.onosproject.cord.gui.model.SubscriberUser.mac ()
Returns the MAC address of the associated device.
Returns
MAC address
Definition at line 76 of file SubscriberUser.java.
Referenced by org.onosproject.cord.gui.model.SubscriberUser.SubscriberUser().
String org.onosproject.cord.gui.model.SubscriberUser.name ()
Returns the display name.
Returns
display name
Definition at line 67 of file SubscriberUser.java.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), org.onosproject.cord.gui.model.SubscriberUser.SubscriberUser(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), and org.onosproject.cord.gui.model.SubscriberUser.toString().
void org.onosproject.cord.gui.model.SubscriberUser.setMemento (XosFunctionDescriptor f, XosFunction.Memento m)
Stores a memento for the given XOS function.
Parameters
f XOS function
m memento
Definition at line 104 of file SubscriberUser.java.
void org.onosproject.cord.gui.model.SubscriberUser.setUrlFilterLevel (String level)
Sets the URL filter level.
Parameters
level URL filter level
Definition at line 94 of file SubscriberUser.java.
String org.onosproject.cord.gui.model.SubscriberUser.toString ()
Definition at line 128 of file SubscriberUser.java.
References org.onosproject.cord.gui.model.SubscriberUser.name().
String org.onosproject.cord.gui.model.SubscriberUser.urlFilterLevel ()
Returns the URL filter level.
Returns
URL filter level
Definition at line 85 of file SubscriberUser.java.
The documentation for this class was generated from the following file:
apps/demo/cord-gui/src/main/java/org/onosproject/cord/gui/model/SubscriberUser.java