onos: org.onlab.util.SlidingWindowCounter Class Reference
org.onlab.util.SlidingWindowCounter Class Reference
Maintains a sliding window of value counts.
Public Member Functions
SlidingWindowCounter (int windowSlots)
Creates a new sliding window counter with the given total number of window slots.
void destroy ()
Releases resources used by the SlidingWindowCounter.
void incrementCount ()
Increments the count of the current window slot by 1.
void incrementCount (long value)
Increments the count of the current window slot by the given value.
long get (int slots)
Gets the total count for the last N window slots.
Detailed Description
Maintains a sliding window of value counts.
The sliding window counter is initialized with a number of window slots. Calls to incrementCount() will increment the value in the current window slot. Periodically the window slides and the oldest value count is dropped. Calls to get() will get the total count for the last N window slots.
Definition at line 36 of file SlidingWindowCounter.java.
Constructor & Destructor Documentation
org.onlab.util.SlidingWindowCounter.SlidingWindowCounter (int windowSlots)
Creates a new sliding window counter with the given total number of window slots.
Parameters
windowSlots total number of window slots
Definition at line 53 of file SlidingWindowCounter.java.
Member Function Documentation
void org.onlab.util.SlidingWindowCounter.destroy ()
Releases resources used by the SlidingWindowCounter.
Definition at line 73 of file SlidingWindowCounter.java.
long org.onlab.util.SlidingWindowCounter.get (int slots)
Gets the total count for the last N window slots.
Parameters
slots number of slots to include in the count
Returns
total count for last N slots
Definition at line 103 of file SlidingWindowCounter.java.
Referenced by org.onlab.util.SlidingWindowCounterTest.testIncrementCount(), org.onlab.util.SlidingWindowCounterTest.testSlide(), and org.onlab.util.SlidingWindowCounterTest.testWrap().
void org.onlab.util.SlidingWindowCounter.incrementCount ()
Increments the count of the current window slot by 1.
Definition at line 80 of file SlidingWindowCounter.java.
Referenced by org.onlab.util.SlidingWindowCounter.incrementCount().
void org.onlab.util.SlidingWindowCounter.incrementCount (long value)
Increments the count of the current window slot by the given value.
Parameters
value value to increment by
Definition at line 89 of file SlidingWindowCounter.java.
References org.onlab.util.SlidingWindowCounter.incrementCount().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/util/SlidingWindowCounter.java