onos: org.onosproject.store.cluster.impl.NodeInfo Class Reference
org.onosproject.store.cluster.impl.NodeInfo Class Reference
Node info read from configuration files during bootstrap.
Public Member Functions
String getId ()
Returns node id.
String getIp ()
Returns node ip.
int getTcpPort ()
Returns node port.
int hashCode ()
boolean equals (Object o)
String toString ()
Static Public Member Functions
static NodeInfo from (String id, String ip, int port)
Creates a new instance.
static NodeInfo of (ControllerNode node)
Returns the NodeInfo for a controller node.
Detailed Description
Node info read from configuration files during bootstrap.
Definition at line 27 of file NodeInfo.java.
Member Function Documentation
boolean org.onosproject.store.cluster.impl.NodeInfo.equals (Object o)
Definition at line 98 of file NodeInfo.java.
References find-device.id.
static NodeInfo org.onosproject.store.cluster.impl.NodeInfo.from (String id, String ip, int port) static
Creates a new instance.
Parameters
id node id
ip node ip address
port tcp port
Returns
NodeInfo
Definition at line 54 of file NodeInfo.java.
References create-flow.node.
String org.onosproject.store.cluster.impl.NodeInfo.getId ()
Returns node id.
Returns
node id
Definition at line 72 of file NodeInfo.java.
Referenced by metro.FabricDomain.build().
String org.onosproject.store.cluster.impl.NodeInfo.getIp ()
Returns node ip.
Returns
node ip
Definition at line 80 of file NodeInfo.java.
int org.onosproject.store.cluster.impl.NodeInfo.getTcpPort ()
Returns node port.
Returns
port
Definition at line 88 of file NodeInfo.java.
int org.onosproject.store.cluster.impl.NodeInfo.hashCode ()
Definition at line 93 of file NodeInfo.java.
static NodeInfo org.onosproject.store.cluster.impl.NodeInfo.of (ControllerNode node) static
Returns the NodeInfo for a controller node.
Parameters
node controller node
Returns
NodeInfo
Definition at line 64 of file NodeInfo.java.
References org.onosproject.store.cluster.impl.NodeInfo.toString().
String org.onosproject.store.cluster.impl.NodeInfo.toString ()
Definition at line 112 of file NodeInfo.java.
Referenced by org.onosproject.store.cluster.impl.NodeInfo.of().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/cluster/impl/NodeInfo.java