onos: org.onosproject.vtnrsc.FlowClassifierId Class Reference
org.onosproject.vtnrsc.FlowClassifierId Class Reference
Flow classification identifier.
Public Member Functions
UUID value ()
Returns the value of flow classifier id.
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static FlowClassifierId of (final UUID flowClassifierId)
Returns new flow classifier id.
static FlowClassifierId of (final String flowClassifierId)
Returns new flow classifier id.
Detailed Description
Flow classification identifier.
Definition at line 28 of file FlowClassifierId.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.FlowClassifierId.equals (Object obj)
Definition at line 77 of file FlowClassifierId.java.
int org.onosproject.vtnrsc.FlowClassifierId.hashCode ()
Definition at line 72 of file FlowClassifierId.java.
static FlowClassifierId org.onosproject.vtnrsc.FlowClassifierId.of (final UUID flowClassifierId) static
Returns new flow classifier id.
Parameters
flowClassifierId flow classifier id
Returns
new flow classifier id
Definition at line 48 of file FlowClassifierId.java.
Referenced by org.onosproject.vtnweb.resources.FlowClassifierWebResource.getFlowClassifier().
static FlowClassifierId org.onosproject.vtnrsc.FlowClassifierId.of (final String flowClassifierId) static
Returns new flow classifier id.
Parameters
flowClassifierId flow classifier id
Returns
new flow classifier id
Definition at line 58 of file FlowClassifierId.java.
String org.onosproject.vtnrsc.FlowClassifierId.toString ()
Definition at line 89 of file FlowClassifierId.java.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest().
UUID org.onosproject.vtnrsc.FlowClassifierId.value ()
Returns the value of flow classifier id.
Returns
flow classifier id.
Definition at line 67 of file FlowClassifierId.java.
Referenced by org.onosproject.vtnrsc.FlowClassifierIdTest.testConstruction().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/FlowClassifierId.java