onos: org.onosproject.incubator.net.tunnel.DefaultTunnelDescription Class Reference
org.onosproject.incubator.net.tunnel.DefaultTunnelDescription Class Reference
Default implementation of immutable tunnel description entity.
Public Member Functions
DefaultTunnelDescription (TunnelId id, TunnelEndPoint src, TunnelEndPoint dst, Tunnel.Type type, DefaultGroupId groupId, ProviderId producerName, TunnelName tunnelName, Path path, SparseAnnotations...annotations)
Creates a tunnel description using the supplied information.
TunnelId id ()
Returns the tunnel id.
TunnelEndPoint src ()
Returns the connection point source.
TunnelEndPoint dst ()
Returns the connection point destination.
Tunnel.Type type ()
Returns the tunnel type.
DefaultGroupId groupId ()
Returns group flow table id which a tunnel match up.
ProviderId producerName ()
Returns tunnel producer name.
TunnelName tunnelName ()
Return the name of a tunnel.
Path path ()
Returns the path of the tunnel.
String toString ()
Public Member Functions inherited from org.onosproject.net.AbstractDescription
SparseAnnotations annotations ()
Returns the key/value annotations.
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractDescription
AbstractDescription ()
AbstractDescription (SparseAnnotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of immutable tunnel description entity.
Definition at line 31 of file DefaultTunnelDescription.java.
Constructor & Destructor Documentation
org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.DefaultTunnelDescription (TunnelId id, TunnelEndPoint src, TunnelEndPoint dst, Tunnel.Type type, DefaultGroupId groupId, ProviderId producerName, TunnelName tunnelName, Path path, SparseAnnotations... annotations)
Creates a tunnel description using the supplied information.
Parameters
id TunnelId
src TunnelPoint source
dst TunnelPoint destination
type tunnel type
groupId groupId
producerName tunnel producer
tunnelName tunnel name
path the path of tunnel
annotations optional key/value annotations
Definition at line 58 of file DefaultTunnelDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.dst(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.groupId(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.id(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.path(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.producerName(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.src(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.tunnelName(), and org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.type().
Member Function Documentation
TunnelEndPoint org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.dst ()
Returns the connection point destination.
Returns
tunnel destination
Implements org.onosproject.incubator.net.tunnel.TunnelDescription.
Definition at line 87 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.toString().
DefaultGroupId org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.groupId ()
Returns group flow table id which a tunnel match up.
Returns
OpenFlowGroupId
Implements org.onosproject.incubator.net.tunnel.TunnelDescription.
Definition at line 97 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.toString().
TunnelId org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.id ()
Returns the tunnel id.
Returns
tunnelId
Implements org.onosproject.incubator.net.tunnel.TunnelDescription.
Definition at line 77 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.DefaultTunnelDescription().
Path org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.path ()
Returns the path of the tunnel.
Returns
the path of the tunnel
Implements org.onosproject.incubator.net.tunnel.TunnelDescription.
Definition at line 113 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.toString().
ProviderId org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.producerName ()
Returns tunnel producer name.
Returns
producer name
Implements org.onosproject.incubator.net.tunnel.TunnelDescription.
Definition at line 102 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.toString().
TunnelEndPoint org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.src ()
Returns the connection point source.
Returns
tunnel source ConnectionPoint
Implements org.onosproject.incubator.net.tunnel.TunnelDescription.
Definition at line 82 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.toString().
String org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.toString ()
Definition at line 118 of file DefaultTunnelDescription.java.
References org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.dst(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.groupId(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.path(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.producerName(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.src(), org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.tunnelName(), and org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.type().
TunnelName org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.tunnelName ()
Return the name of a tunnel.
Returns
Tunnel Name
Implements org.onosproject.incubator.net.tunnel.TunnelDescription.
Definition at line 107 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.toString().
Tunnel.Type org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.type ()
Returns the tunnel type.
Returns
tunnel type
Implements org.onosproject.incubator.net.tunnel.TunnelDescription.
Definition at line 92 of file DefaultTunnelDescription.java.
Referenced by org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.DefaultTunnelDescription(), and org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.toString().
The documentation for this class was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/tunnel/DefaultTunnelDescription.java