onos: org.onosproject.vtnweb.web.FlowClassifierCodecTest Class Reference
org.onosproject.vtnweb.web.FlowClassifierCodecTest Class Reference
Flow classifier codec unit tests.
Public Member Functions
void setUp ()
Sets up for each test.
void codecFlowClassifierTest () throws IOException
Checks that a simple flow classifier decodes properly.
Detailed Description
Flow classifier codec unit tests.
Definition at line 39 of file FlowClassifierCodecTest.java.
Member Function Documentation
void org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest () throws IOException
Checks that a simple flow classifier decodes properly.
Exceptions
IOException if the resource cannot be processed
Definition at line 78 of file FlowClassifierCodecTest.java.
References org.onosproject.vtnrsc.FlowClassifier.description(), org.onosproject.vtnrsc.FlowClassifier.flowClassifierId(), org.onosproject.vtnrsc.FlowClassifier.maxDstPortRange(), org.onosproject.vtnrsc.FlowClassifier.maxSrcPortRange(), org.onosproject.vtnrsc.FlowClassifier.minDstPortRange(), org.onosproject.vtnrsc.FlowClassifier.minSrcPortRange(), org.onosproject.vtnrsc.FlowClassifier.name(), org.onosproject.vtnrsc.FlowClassifier.protocol(), org.onosproject.vtnrsc.FlowClassifier.tenantId(), and org.onosproject.vtnrsc.FlowClassifierId.toString().
void org.onosproject.vtnweb.web.FlowClassifierCodecTest.setUp ()
Sets up for each test.
Creates a context and fetches the flow classifier codec.
Definition at line 48 of file FlowClassifierCodecTest.java.
The documentation for this class was generated from the following file:
apps/vtn/vtnweb/src/test/java/org/onosproject/vtnweb/web/FlowClassifierCodecTest.java