onos: org.onosproject.ui.RequestHandler Class Reference
org.onosproject.ui.RequestHandler Class Reference abstract
Abstraction of an entity that handles a specific request from the user interface client.
Public Member Functions
RequestHandler (String eventType)
String eventType ()
Returns the event type that this handler handles.
abstract void process (long sid, ObjectNode payload)
Processes the incoming message payload from the client.
Protected Member Functions
void sendMessage (String eventType, long sid, ObjectNode payload)
Sends a message back to the client.
void sendMessage (ObjectNode message)
Sends a message back to the client.
void chain (String eventType, long sid, ObjectNode payload)
Allows one request handler to pass the event on to another for further processing.
String string (ObjectNode node, String key)
Returns the specified node property as a string.
String string (ObjectNode node, String key, String defValue)
Returns the specified node property as a string, with a default fallback.
Static Protected Attributes
static final ObjectMapper MAPPER = new ObjectMapper()
Detailed Description
Abstraction of an entity that handles a specific request from the user interface client.
See Also
UiMessageHandler
Definition at line 27 of file RequestHandler.java.
Constructor & Destructor Documentation
org.onosproject.ui.RequestHandler.RequestHandler (String eventType)
Definition at line 35 of file RequestHandler.java.
References org.onosproject.ui.RequestHandler.eventType().
Member Function Documentation
void org.onosproject.ui.RequestHandler.chain (String eventType, long sid, ObjectNode payload) protected
Allows one request handler to pass the event on to another for further processing.
Note that the message handlers must be defined in the same parent.
Parameters
eventType event type
sid sequence identifier
payload message payload
Definition at line 112 of file RequestHandler.java.
References org.onosproject.ui.RequestHandler.eventType().
String org.onosproject.ui.RequestHandler.eventType ()
Returns the event type that this handler handles.
Returns
event type
Definition at line 49 of file RequestHandler.java.
Referenced by org.onosproject.ui.RequestHandler.chain(), and org.onosproject.ui.RequestHandler.RequestHandler().
abstract void org.onosproject.ui.RequestHandler.process (long sid, ObjectNode payload) pure virtual
Processes the incoming message payload from the client.
Parameters
sid message sequence identifier
payload request message payload
Implemented in org.onosproject.ui.table.TableRequestHandler.
void org.onosproject.ui.RequestHandler.sendMessage (String eventType, long sid, ObjectNode payload) protected
Sends a message back to the client.
Parameters
eventType message event type
sid message sequence identifier
payload message payload
Definition at line 87 of file RequestHandler.java.
Referenced by org.onosproject.ui.table.TableRequestHandler.process(), and org.onosproject.ui.RequestHandler.sendMessage().
void org.onosproject.ui.RequestHandler.sendMessage (ObjectNode message) protected
Sends a message back to the client.
Here, the message is preformatted; the assumption is it has its eventType, sid and payload attributes already filled in.
Parameters
message the message to send
Definition at line 98 of file RequestHandler.java.
References org.onosproject.ui.RequestHandler.sendMessage().
String org.onosproject.ui.RequestHandler.string (ObjectNode node, String key) protected
Returns the specified node property as a string.
Parameters
node message event
key property name
Returns
property as a string
Definition at line 126 of file RequestHandler.java.
References create-flow.node.
String org.onosproject.ui.RequestHandler.string (ObjectNode node, String key, String defValue) protected
Returns the specified node property as a string, with a default fallback.
Parameters
node object node
key property name
defValue fallback value if property is absent
Returns
property as a string
Definition at line 138 of file RequestHandler.java.
References create-flow.node.
Member Data Documentation
final ObjectMapper org.onosproject.ui.RequestHandler.MAPPER = new ObjectMapper() static protected
Definition at line 29 of file RequestHandler.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/ui/RequestHandler.java