onos: org.onlab.util.ByteArraySizeHashPrinter Class Reference
org.onlab.util.ByteArraySizeHashPrinter Class Reference
Helper to print byte[] length and hashCode.
Public Member Functions
ByteArraySizeHashPrinter (byte[] bytes)
String toString ()
Static Public Member Functions
static ByteArraySizeHashPrinter of (byte[] bytes)
Returns ByteArraySizeHashPrinter wrapping given byte[].
static ByteArraySizeHashPrinter orNull (byte[] bytes)
Returns ByteArraySizeHashPrinter wrapping given byte[].
Detailed Description
Helper to print byte[] length and hashCode.
Definition at line 27 of file ByteArraySizeHashPrinter.java.
Constructor & Destructor Documentation
org.onlab.util.ByteArraySizeHashPrinter.ByteArraySizeHashPrinter (byte[] bytes)
Definition at line 54 of file ByteArraySizeHashPrinter.java.
Referenced by org.onlab.util.ByteArraySizeHashPrinter.of(), and org.onlab.util.ByteArraySizeHashPrinter.orNull().
Member Function Documentation
static ByteArraySizeHashPrinter org.onlab.util.ByteArraySizeHashPrinter.of (byte[] bytes) static
Returns ByteArraySizeHashPrinter wrapping given byte[].
Parameters
bytes bytes to wrap around
Returns
ByteArraySizeHashPrinter
Definition at line 37 of file ByteArraySizeHashPrinter.java.
References org.onlab.util.ByteArraySizeHashPrinter.ByteArraySizeHashPrinter().
Referenced by org.onlab.util.ByteArraySizeHashPrinterTest.testToString(), org.onlab.util.ByteArraySizeHashPrinterTest.testToStringNull(), and org.onosproject.store.cluster.messaging.ClusterMessage.toString().
static ByteArraySizeHashPrinter org.onlab.util.ByteArraySizeHashPrinter.orNull (byte[] bytes) static
Returns ByteArraySizeHashPrinter wrapping given byte[].
Parameters
bytes bytes to wrap around
Returns
null if
bytes == null
, ByteArraySizeHashPrinter otherwise
Definition at line 47 of file ByteArraySizeHashPrinter.java.
References org.onlab.util.ByteArraySizeHashPrinter.ByteArraySizeHashPrinter().
Referenced by org.onlab.util.ByteArraySizeHashPrinterTest.testToString(), and org.onlab.util.ByteArraySizeHashPrinterTest.testToStringNull().
String org.onlab.util.ByteArraySizeHashPrinter.toString ()
Definition at line 59 of file ByteArraySizeHashPrinter.java.
References find-link-in-cluster.length.
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/util/ByteArraySizeHashPrinter.java