onos: org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest Class Reference
org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest Class Reference
Unit tests for PortPairGroupManager class.
Public Member Functions
void testCreatePortPairGroup ()
Checks the operation of createPortPairGroup() method.
void testExists ()
Checks the operation of exists() method.
void testGetPortPairGroupCount ()
Checks the operation of getPortPairGroupCount() method.
void testGetPortPairGroups ()
Checks the operation of getPortPairGroups() method.
void testGetPortPairGroup ()
Checks the operation of getPortPairGroup() method.
void testUpdatePortPairGroup ()
Checks the operation of updatePortPairGroup() method.
void testRemovePortPairGroup ()
Checks the operation of removePortPairGroup() method.
Detailed Description
Unit tests for PortPairGroupManager class.
Definition at line 36 of file PortPairGroupManagerTest.java.
Member Function Documentation
void org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testCreatePortPairGroup ()
Checks the operation of createPortPairGroup() method.
Definition at line 51 of file PortPairGroupManagerTest.java.
References org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.createPortPairGroup().
Referenced by org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testExists(), org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testGetPortPairGroup(), org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testGetPortPairGroupCount(), org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testGetPortPairGroups(), org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testRemovePortPairGroup(), and org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testUpdatePortPairGroup().
void org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testExists ()
Checks the operation of exists() method.
Definition at line 72 of file PortPairGroupManagerTest.java.
References org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.exists(), and org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testCreatePortPairGroup().
void org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testGetPortPairGroup ()
Checks the operation of getPortPairGroup() method.
Definition at line 101 of file PortPairGroupManagerTest.java.
References org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.getPortPairGroup(), and org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testCreatePortPairGroup().
void org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testGetPortPairGroupCount ()
Checks the operation of getPortPairGroupCount() method.
Definition at line 81 of file PortPairGroupManagerTest.java.
References org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.getPortPairGroupCount(), and org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testCreatePortPairGroup().
void org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testGetPortPairGroups ()
Checks the operation of getPortPairGroups() method.
Definition at line 90 of file PortPairGroupManagerTest.java.
References org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testCreatePortPairGroup().
void org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testRemovePortPairGroup ()
Checks the operation of removePortPairGroup() method.
Definition at line 136 of file PortPairGroupManagerTest.java.
References org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.removePortPairGroup(), and org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testCreatePortPairGroup().
void org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testUpdatePortPairGroup ()
Checks the operation of updatePortPairGroup() method.
Definition at line 111 of file PortPairGroupManagerTest.java.
References org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManagerTest.testCreatePortPairGroup(), and org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.updatePortPairGroup().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/test/java/org/onosproject/vtnrsc/portpairgroup/impl/PortPairGroupManagerTest.java