onos: org.onosproject.vtnrsc.DefaultSubnet Class Reference
org.onosproject.vtnrsc.DefaultSubnet Class Reference
Default implementation of Subnet interface .
Public Member Functions
DefaultSubnet (SubnetId id, String subnetName, TenantNetworkId networkId, TenantId tenantId, Version ipVersion, IpPrefix cidr, IpAddress gatewayIp, boolean dhcpEnabled, boolean shared, Set< HostRoute > hostRoutes, Mode ipV6AddressMode, Mode ipV6RaMode, Set< AllocationPool > allocationPoolsIt)
Creates a subnet object.
SubnetId id ()
Returns the subnet identifier.
String subnetName ()
Returns the name of the subnet.
TenantNetworkId networkId ()
Returns the network identifier.
TenantId tenantId ()
Returns tenant identifier.
Version ipVersion ()
Returns the IP version, which is 4 or 6.
IpPrefix cidr ()
Returns the cidr.
IpAddress gatewayIp ()
Returns the gateway IP address.
boolean dhcpEnabled ()
Returns true if DHCP is enabled and return false if DHCP is disabled.
boolean shared ()
Indicates whether this tenantNetwork is shared across all tenants.
Iterable< HostRoute > hostRoutes ()
Returns a collection of hostRoutes.
Mode ipV6AddressMode ()
Returns the ipV6AddressMode.
Mode ipV6RaMode ()
Returns the ipV6RaMode.A valid value is dhcpv6-stateful, dhcpv6-stateless, or slaac.
Iterable< AllocationPool > allocationPools ()
Returns a collection of allocation_pools.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Default implementation of Subnet interface .
Definition at line 30 of file DefaultSubnet.java.
Constructor & Destructor Documentation
org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet (SubnetId id, String subnetName, TenantNetworkId networkId, TenantId tenantId, Version ipVersion, IpPrefix cidr, IpAddress gatewayIp, boolean dhcpEnabled, boolean shared, Set< HostRoute > hostRoutes, Mode ipV6AddressMode, Mode ipV6RaMode, Set< AllocationPool > allocationPoolsIt)
Creates a subnet object.
Parameters
id subnet identifier
subnetName the name of subnet
networkId network identifier
tenantId tenant identifier
ipVersion Version of ipv4 or ipv6
cidr the cidr
gatewayIp gateway ip
dhcpEnabled dhcp enabled or not
shared indicates whether this network is shared across all tenants, By default, only administrative user can change this value
hostRoutes a collection of host routes
ipV6AddressMode ipV6AddressMode
ipV6RaMode ipV6RaMode
allocationPoolsIt a collection of allocationPools
Definition at line 64 of file DefaultSubnet.java.
References org.onosproject.vtnrsc.DefaultSubnet.cidr(), org.onosproject.vtnrsc.DefaultSubnet.dhcpEnabled(), org.onosproject.vtnrsc.DefaultSubnet.gatewayIp(), org.onosproject.vtnrsc.DefaultSubnet.hostRoutes(), org.onosproject.vtnrsc.DefaultSubnet.id(), org.onosproject.vtnrsc.DefaultSubnet.ipV6AddressMode(), org.onosproject.vtnrsc.DefaultSubnet.ipV6RaMode(), org.onosproject.vtnrsc.DefaultSubnet.ipVersion(), org.onosproject.vtnrsc.DefaultSubnet.networkId(), org.onosproject.vtnrsc.DefaultSubnet.shared(), org.onosproject.vtnrsc.DefaultSubnet.subnetName(), and org.onosproject.vtnrsc.DefaultSubnet.tenantId().
Referenced by org.onosproject.vtnrsc.DefaultSubnet.equals().
Member Function Documentation
Iterable<AllocationPool> org.onosproject.vtnrsc.DefaultSubnet.allocationPools ()
Returns a collection of allocation_pools.
Returns
a collection of allocationPools
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 147 of file DefaultSubnet.java.
IpPrefix org.onosproject.vtnrsc.DefaultSubnet.cidr ()
Returns the cidr.
Returns
cidr
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 112 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet(), org.onosproject.vtnrsc.DefaultSubnet.hashCode(), and org.onosproject.vtnrsc.DefaultSubnet.toString().
boolean org.onosproject.vtnrsc.DefaultSubnet.dhcpEnabled ()
Returns true if DHCP is enabled and return false if DHCP is disabled.
Returns
true or false
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 122 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet(), org.onosproject.vtnrsc.DefaultSubnet.hashCode(), and org.onosproject.vtnrsc.DefaultSubnet.toString().
boolean org.onosproject.vtnrsc.DefaultSubnet.equals (Object obj)
Definition at line 158 of file DefaultSubnet.java.
References org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet(), and find-device.id.
IpAddress org.onosproject.vtnrsc.DefaultSubnet.gatewayIp ()
Returns the gateway IP address.
Returns
gatewayIp
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 117 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet(), org.onosproject.vtnrsc.DefaultSubnet.hashCode(), and org.onosproject.vtnrsc.DefaultSubnet.toString().
int org.onosproject.vtnrsc.DefaultSubnet.hashCode ()
Definition at line 152 of file DefaultSubnet.java.
References org.onosproject.vtnrsc.DefaultSubnet.cidr(), org.onosproject.vtnrsc.DefaultSubnet.dhcpEnabled(), org.onosproject.vtnrsc.DefaultSubnet.gatewayIp(), org.onosproject.vtnrsc.DefaultSubnet.id(), org.onosproject.vtnrsc.DefaultSubnet.ipVersion(), org.onosproject.vtnrsc.DefaultSubnet.shared(), org.onosproject.vtnrsc.DefaultSubnet.subnetName(), and org.onosproject.vtnrsc.DefaultSubnet.tenantId().
Iterable<HostRoute> org.onosproject.vtnrsc.DefaultSubnet.hostRoutes ()
Returns a collection of hostRoutes.
Returns
a collection of hostRoutes
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 132 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet().
SubnetId org.onosproject.vtnrsc.DefaultSubnet.id ()
Returns the subnet identifier.
Returns
identifier
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 87 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet(), org.onosproject.vtnrsc.DefaultSubnet.hashCode(), and org.onosproject.vtnrsc.DefaultSubnet.toString().
Mode org.onosproject.vtnrsc.DefaultSubnet.ipV6AddressMode ()
Returns the ipV6AddressMode.
A valid value is dhcpv6-stateful, dhcpv6-stateless, or slaac.
Returns
ipV6AddressMode whose value is dhcpv6-stateful, dhcpv6-stateless or slaac
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 137 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet().
Mode org.onosproject.vtnrsc.DefaultSubnet.ipV6RaMode ()
Returns the ipV6RaMode.A valid value is dhcpv6-stateful, dhcpv6-stateless, or slaac.
Returns
ipV6RaMode whose value is dhcpv6-stateful, dhcpv6-stateless or slaac
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 142 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet().
Version org.onosproject.vtnrsc.DefaultSubnet.ipVersion ()
Returns the IP version, which is 4 or 6.
Returns
ipVersion
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 107 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet(), org.onosproject.vtnrsc.DefaultSubnet.hashCode(), and org.onosproject.vtnrsc.DefaultSubnet.toString().
TenantNetworkId org.onosproject.vtnrsc.DefaultSubnet.networkId ()
Returns the network identifier.
Returns
the network identifier
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 97 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet().
boolean org.onosproject.vtnrsc.DefaultSubnet.shared ()
Indicates whether this tenantNetwork is shared across all tenants.
By default, only administrative user can change this value.
Returns
true or false
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 127 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet(), org.onosproject.vtnrsc.DefaultSubnet.hashCode(), and org.onosproject.vtnrsc.DefaultSubnet.toString().
String org.onosproject.vtnrsc.DefaultSubnet.subnetName ()
Returns the name of the subnet.
Returns
subnetName
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 92 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet(), org.onosproject.vtnrsc.DefaultSubnet.hashCode(), and org.onosproject.vtnrsc.DefaultSubnet.toString().
TenantId org.onosproject.vtnrsc.DefaultSubnet.tenantId ()
Returns tenant identifier.
Returns
the tenant identifier
Implements org.onosproject.vtnrsc.Subnet.
Definition at line 102 of file DefaultSubnet.java.
Referenced by org.onosproject.vtnrsc.DefaultSubnet.DefaultSubnet(), and org.onosproject.vtnrsc.DefaultSubnet.hashCode().
String org.onosproject.vtnrsc.DefaultSubnet.toString ()
Definition at line 176 of file DefaultSubnet.java.
References org.onosproject.vtnrsc.DefaultSubnet.cidr(), org.onosproject.vtnrsc.DefaultSubnet.dhcpEnabled(), org.onosproject.vtnrsc.DefaultSubnet.gatewayIp(), org.onosproject.vtnrsc.DefaultSubnet.id(), org.onosproject.vtnrsc.DefaultSubnet.ipVersion(), org.onosproject.vtnrsc.DefaultSubnet.shared(), and org.onosproject.vtnrsc.DefaultSubnet.subnetName().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/DefaultSubnet.java