onos: org.onlab.util.Frequency Class Reference
org.onlab.util.Frequency Class Reference
Class representing frequency.
Public Member Functions
long asHz ()
Return the value this instance represents as Hz.
Frequency add (Frequency value)
Returns a Frequency whose value is (this + value).
Frequency subtract (Frequency value)
Returns a Frequency whose value is (this - value).
Frequency multiply (long value)
Returns a Frequency whose value is (this * value).
Frequency floorDivision (long value)
Returns a Frequency whose value is Math.floorDiv(this, value).
int compareTo (Frequency other)
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static Frequency ofHz (long value)
Returns an instance representing the specified value in Hz.
static Frequency ofKHz (double value)
Returns an instance representing the specified value in KHz.
static Frequency ofMHz (double value)
Returns an instance representing the specified value in MHz.
static Frequency ofGHz (double value)
Returns an instance representing the specified value in GHz.
static Frequency ofTHz (double value)
Returns an instance representing the specified value in THz.
Detailed Description
Class representing frequency.
This class is intended to be used for a value whose unit is Hz and its family (KHz, MHz, etc.).
Note: this class is mainly intended to be used for lambda, which represents THz order. Long has enough space to represent over THz frequency as Hz, and the underlying value is long as Hz. This means this class can't represent sub-Hz accuracy.
Definition at line 32 of file Frequency.java.
Member Function Documentation
Frequency org.onlab.util.Frequency.add (Frequency value)
Returns a Frequency whose value is (this + value).
Parameters
value value to be added to this Frequency
Returns
this + value
Definition at line 115 of file Frequency.java.
Referenced by org.onlab.util.FrequencyTest.testAdd(), and org.onlab.util.Frequency.toString().
long org.onlab.util.Frequency.asHz ()
Return the value this instance represents as Hz.
Returns
frequency in Hz
Definition at line 55 of file Frequency.java.
Referenced by org.onosproject.net.OchSignal.OchSignal(), and org.onosproject.net.OmsPort.totalChannels().
int org.onlab.util.Frequency.compareTo (Frequency other)
Definition at line 150 of file Frequency.java.
boolean org.onlab.util.Frequency.equals (Object obj)
Definition at line 162 of file Frequency.java.
Frequency org.onlab.util.Frequency.floorDivision (long value)
Returns a Frequency whose value is Math.floorDiv(this, value).
Parameters
value value to be divided by this Frequency
Returns
Math.floorDiv(this, value)
Definition at line 145 of file Frequency.java.
int org.onlab.util.Frequency.hashCode ()
Definition at line 157 of file Frequency.java.
Frequency org.onlab.util.Frequency.multiply (long value)
Returns a Frequency whose value is (this * value).
Parameters
value value to be multiplied by this Frequency
Returns
this * value
Definition at line 135 of file Frequency.java.
Referenced by org.onlab.util.FrequencyTest.testMultiply().
static Frequency org.onlab.util.Frequency.ofGHz (double value) static
Returns an instance representing the specified value in GHz.
Parameters
value frequency in GHz
Returns
instance representing the given frequency
Definition at line 95 of file Frequency.java.
Referenced by org.onosproject.cli.net.DevicePortsListCommand.printDevice(), org.onosproject.store.serializers.KryoSerializerTest.testFrequency(), and org.onosproject.store.serializers.KryoSerializerTest.testOmsPort().
static Frequency org.onlab.util.Frequency.ofHz (long value) static
Returns an instance representing the specified value in Hz.
Parameters
value frequency in Hz
Returns
instance representing the given frequency
Definition at line 65 of file Frequency.java.
Referenced by org.onosproject.net.intent.impl.compiler.OpticalConnectivityIntentCompiler.compile().
static Frequency org.onlab.util.Frequency.ofKHz (double value) static
Returns an instance representing the specified value in KHz.
Parameters
value frequency in KHz
Returns
instance representing the given frequency
Definition at line 75 of file Frequency.java.
static Frequency org.onlab.util.Frequency.ofMHz (double value) static
Returns an instance representing the specified value in MHz.
Parameters
value frequency in MHz
Returns
instance representing the given frequency
Definition at line 85 of file Frequency.java.
static Frequency org.onlab.util.Frequency.ofTHz (double value) static
Returns an instance representing the specified value in THz.
Parameters
value frequency in THz
Returns
instance representing the given frequency
Definition at line 105 of file Frequency.java.
Frequency org.onlab.util.Frequency.subtract (Frequency value)
Returns a Frequency whose value is (this - value).
Parameters
value value to be subtracted from this Frequency
Returns
this - value
Definition at line 125 of file Frequency.java.
Referenced by org.onosproject.net.OchSignal.OchSignal(), and org.onlab.util.FrequencyTest.testSubtract().
String org.onlab.util.Frequency.toString ()
Definition at line 176 of file Frequency.java.
References org.onlab.util.Frequency.add().
The documentation for this class was generated from the following file:
utils/misc/src/main/java/org/onlab/util/Frequency.java