onos: org.onosproject.store.device.impl.PortKey Class Reference
org.onosproject.store.device.impl.PortKey Class Reference
Key for PortDescriptions in ECDeviceStore.
Public Member Functions
PortKey (ProviderId providerId, DeviceId deviceId, PortNumber portNumber)
ProviderId providerId ()
DeviceId deviceId ()
PortNumber portNumber ()
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Key for PortDescriptions in ECDeviceStore.
Definition at line 29 of file PortKey.java.
Constructor & Destructor Documentation
org.onosproject.store.device.impl.PortKey.PortKey (ProviderId providerId, DeviceId deviceId, PortNumber portNumber)
Definition at line 34 of file PortKey.java.
References org.onosproject.store.device.impl.PortKey.deviceId(), org.onosproject.store.device.impl.PortKey.portNumber(), and org.onosproject.store.device.impl.PortKey.providerId().
Referenced by org.onosproject.store.device.impl.PortKey.equals().
Member Function Documentation
DeviceId org.onosproject.store.device.impl.PortKey.deviceId ()
Definition at line 44 of file PortKey.java.
Referenced by org.onosproject.store.device.impl.PortKey.hashCode(), org.onosproject.store.device.impl.PortKey.PortKey(), and org.onosproject.store.device.impl.PortKey.toString().
boolean org.onosproject.store.device.impl.PortKey.equals (Object obj)
Definition at line 58 of file PortKey.java.
References find-flow.deviceId, and org.onosproject.store.device.impl.PortKey.PortKey().
int org.onosproject.store.device.impl.PortKey.hashCode ()
Definition at line 53 of file PortKey.java.
References org.onosproject.store.device.impl.PortKey.deviceId(), org.onosproject.store.device.impl.PortKey.portNumber(), and org.onosproject.store.device.impl.PortKey.providerId().
PortNumber org.onosproject.store.device.impl.PortKey.portNumber ()
Definition at line 48 of file PortKey.java.
Referenced by org.onosproject.store.device.impl.PortKey.hashCode(), org.onosproject.store.device.impl.PortKey.PortKey(), and org.onosproject.store.device.impl.PortKey.toString().
ProviderId org.onosproject.store.device.impl.PortKey.providerId ()
Definition at line 40 of file PortKey.java.
Referenced by org.onosproject.store.device.impl.PortKey.hashCode(), org.onosproject.store.device.impl.PortKey.PortKey(), and org.onosproject.store.device.impl.PortKey.toString().
String org.onosproject.store.device.impl.PortKey.toString ()
Definition at line 72 of file PortKey.java.
References org.onosproject.store.device.impl.PortKey.deviceId(), org.onosproject.store.device.impl.PortKey.portNumber(), and org.onosproject.store.device.impl.PortKey.providerId().
The documentation for this class was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/device/impl/PortKey.java