onos: org.onosproject.net.device.OduCltPortDescription Class Reference
org.onosproject.net.device.OduCltPortDescription Class Reference
Default implementation of immutable ODU client port description.
Public Member Functions
OduCltPortDescription (PortNumber number, boolean isEnabled, OduCltPort.SignalType signalType, SparseAnnotations...annotations)
Creates ODU client port description based on the supplied information.
OduCltPortDescription (PortDescription base, OduCltPort.SignalType signalType, SparseAnnotations annotations)
Creates ODU client port description based on the supplied information.
OduCltPort.SignalType signalType ()
Returns ODU client signal type.
String toString ()
Public Member Functions inherited from org.onosproject.net.device.DefaultPortDescription
DefaultPortDescription (PortNumber number, boolean isEnabled, SparseAnnotations...annotations)
Creates a port description using the supplied information.
DefaultPortDescription (PortNumber number, boolean isEnabled, Type type, long portSpeed, SparseAnnotations...annotations)
Creates a port description using the supplied information.
DefaultPortDescription (PortDescription base, SparseAnnotations annotations)
Creates a port description using the supplied information.
PortNumber portNumber ()
Returns the port number.
boolean isEnabled ()
Indicates whether or not the port is up and active.
Type type ()
Returns the port type.
long portSpeed ()
Returns the current port speed in Mbps.
String toString ()
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.AbstractDescription
SparseAnnotations annotations ()
Returns the key/value annotations.
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractDescription
AbstractDescription ()
AbstractDescription (SparseAnnotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of immutable ODU client port description.
Definition at line 27 of file OduCltPortDescription.java.
Constructor & Destructor Documentation
org.onosproject.net.device.OduCltPortDescription.OduCltPortDescription (PortNumber number, boolean isEnabled, OduCltPort.SignalType signalType, SparseAnnotations... annotations)
Creates ODU client port description based on the supplied information.
Parameters
number port number
isEnabled port enabled state
signalType ODU client signal type
annotations optional key/value annotations map
Definition at line 39 of file OduCltPortDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), and org.onosproject.net.device.OduCltPortDescription.signalType().
org.onosproject.net.device.OduCltPortDescription.OduCltPortDescription (PortDescription base, OduCltPort.SignalType signalType, SparseAnnotations annotations)
Creates ODU client port description based on the supplied information.
Parameters
base PortDescription to get basic information from
signalType ODU client signal type
annotations optional key/value annotations map
Definition at line 52 of file OduCltPortDescription.java.
References org.onosproject.net.device.OduCltPortDescription.signalType().
Member Function Documentation
OduCltPort.SignalType org.onosproject.net.device.OduCltPortDescription.signalType ()
Returns ODU client signal type.
Returns
ODU client signal type
Definition at line 63 of file OduCltPortDescription.java.
Referenced by org.onosproject.net.device.OduCltPortDescription.OduCltPortDescription(), and org.onosproject.net.device.OduCltPortDescription.toString().
String org.onosproject.net.device.OduCltPortDescription.toString ()
Definition at line 68 of file OduCltPortDescription.java.
References org.onosproject.net.device.DefaultPortDescription.isEnabled(), org.onosproject.net.device.DefaultPortDescription.portNumber(), org.onosproject.net.device.OduCltPortDescription.signalType(), and org.onosproject.net.device.DefaultPortDescription.type().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/device/OduCltPortDescription.java