onos: org.onosproject.net.link.DefaultLinkDescription Class Reference
org.onosproject.net.link.DefaultLinkDescription Class Reference
Default implementation of immutable link description entity.
Public Member Functions
DefaultLinkDescription (ConnectPoint src, ConnectPoint dst, Link.Type type, SparseAnnotations...annotations)
Creates a link description using the supplied information.
ConnectPoint src ()
Returns the link source.
ConnectPoint dst ()
Returns the link destination.
Link.Type type ()
Returns the link type.
String toString ()
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.AbstractDescription
SparseAnnotations annotations ()
Returns the key/value annotations.
int hashCode ()
boolean equals (Object object)
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Additional Inherited Members
Protected Member Functions inherited from org.onosproject.net.AbstractDescription
AbstractDescription ()
AbstractDescription (SparseAnnotations...annotations)
Creates a new entity, annotated with the specified annotations.
Detailed Description
Default implementation of immutable link description entity.
Definition at line 28 of file DefaultLinkDescription.java.
Constructor & Destructor Documentation
org.onosproject.net.link.DefaultLinkDescription.DefaultLinkDescription (ConnectPoint src, ConnectPoint dst, Link.Type type, SparseAnnotations... annotations)
Creates a link description using the supplied information.
Parameters
src link source
dst link destination
type link type
annotations optional key/value annotations
Definition at line 43 of file DefaultLinkDescription.java.
References org.onosproject.net.AbstractDescription.annotations(), org.onosproject.net.link.DefaultLinkDescription.dst(), org.onosproject.net.link.DefaultLinkDescription.src(), and org.onosproject.net.link.DefaultLinkDescription.type().
Referenced by org.onosproject.net.link.DefaultLinkDescription.equals().
Member Function Documentation
ConnectPoint org.onosproject.net.link.DefaultLinkDescription.dst ()
Returns the link destination.
Returns
links destination
Implements org.onosproject.net.link.LinkDescription.
Definition at line 57 of file DefaultLinkDescription.java.
Referenced by org.onosproject.net.link.DefaultLinkDescription.DefaultLinkDescription(), org.onosproject.net.link.DefaultLinkDescription.hashCode(), and org.onosproject.net.link.DefaultLinkDescription.toString().
boolean org.onosproject.net.link.DefaultLinkDescription.equals (Object object)
Definition at line 80 of file DefaultLinkDescription.java.
References org.onosproject.net.link.DefaultLinkDescription.DefaultLinkDescription().
int org.onosproject.net.link.DefaultLinkDescription.hashCode ()
Definition at line 75 of file DefaultLinkDescription.java.
References org.onosproject.net.link.DefaultLinkDescription.dst(), org.onosproject.net.link.DefaultLinkDescription.src(), and org.onosproject.net.link.DefaultLinkDescription.type().
ConnectPoint org.onosproject.net.link.DefaultLinkDescription.src ()
Returns the link source.
Returns
links source
Implements org.onosproject.net.link.LinkDescription.
Definition at line 52 of file DefaultLinkDescription.java.
Referenced by org.onosproject.net.link.DefaultLinkDescription.DefaultLinkDescription(), org.onosproject.net.link.DefaultLinkDescription.hashCode(), and org.onosproject.net.link.DefaultLinkDescription.toString().
String org.onosproject.net.link.DefaultLinkDescription.toString ()
Definition at line 67 of file DefaultLinkDescription.java.
References org.onosproject.net.link.DefaultLinkDescription.dst(), org.onosproject.net.link.DefaultLinkDescription.src(), and org.onosproject.net.link.DefaultLinkDescription.type().
Link.Type org.onosproject.net.link.DefaultLinkDescription.type ()
Returns the link type.
Returns
link type
Implements org.onosproject.net.link.LinkDescription.
Definition at line 62 of file DefaultLinkDescription.java.
Referenced by org.onosproject.net.link.DefaultLinkDescription.DefaultLinkDescription(), org.onosproject.net.link.DefaultLinkDescription.hashCode(), and org.onosproject.net.link.DefaultLinkDescription.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/link/DefaultLinkDescription.java