onos: org.onosproject.bgpio.types.RouteDistinguisher Class Reference
org.onosproject.bgpio.types.RouteDistinguisher Class Reference
Implementation of RouteDistinguisher.
Public Member Functions
RouteDistinguisher ()
Resets fields.
RouteDistinguisher (long routeDistinguisher)
Constructor to initialize parameters.
long getRouteDistinguisher ()
Returns route distinguisher.
int compareTo (RouteDistinguisher rd)
String toString ()
Static Public Member Functions
static RouteDistinguisher read (ChannelBuffer cb)
Reads route distinguisher from channelBuffer.
Detailed Description
Implementation of RouteDistinguisher.
Definition at line 26 of file RouteDistinguisher.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.types.RouteDistinguisher.RouteDistinguisher ()
Resets fields.
Definition at line 33 of file RouteDistinguisher.java.
Referenced by org.onosproject.bgpio.types.RouteDistinguisher.read().
org.onosproject.bgpio.types.RouteDistinguisher.RouteDistinguisher (long routeDistinguisher)
Constructor to initialize parameters.
Parameters
routeDistinguisher route distinguisher
Definition at line 42 of file RouteDistinguisher.java.
Member Function Documentation
int org.onosproject.bgpio.types.RouteDistinguisher.compareTo (RouteDistinguisher rd)
Definition at line 66 of file RouteDistinguisher.java.
References org.onosproject.bgpio.types.RouteDistinguisher.getRouteDistinguisher().
long org.onosproject.bgpio.types.RouteDistinguisher.getRouteDistinguisher ()
Returns route distinguisher.
Returns
route distinguisher
Definition at line 61 of file RouteDistinguisher.java.
Referenced by org.onosproject.bgpio.types.RouteDistinguisher.compareTo().
static RouteDistinguisher org.onosproject.bgpio.types.RouteDistinguisher.read (ChannelBuffer cb) static
Reads route distinguisher from channelBuffer.
Parameters
cb channelBuffer
Returns
object of RouteDistinguisher
Definition at line 52 of file RouteDistinguisher.java.
References org.onosproject.bgpio.types.RouteDistinguisher.RouteDistinguisher().
String org.onosproject.bgpio.types.RouteDistinguisher.toString ()
Definition at line 74 of file RouteDistinguisher.java.
The documentation for this class was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/types/RouteDistinguisher.java