onos: org.onlab.stc.Compiler Class Reference
org.onlab.stc.Compiler Class Reference
Entity responsible for loading a scenario and producing a redy-to-execute process flow graph.
Public Member Functions
Compiler (Scenario scenario)
Creates a new compiler for the specified scenario.
Scenario scenario ()
Returns the scenario being compiled.
void compile ()
Compiles the specified scenario to produce a final process flow graph.
Step getStep (String name)
Returns the step with the specified name.
ProcessFlow processFlow ()
Returns the process flow generated from this scenario definition.
File logDir ()
Returns the log directory where scenario logs should be kept.
Detailed Description
Entity responsible for loading a scenario and producing a redy-to-execute process flow graph.
Definition at line 43 of file Compiler.java.
Constructor & Destructor Documentation
org.onlab.stc.Compiler.Compiler (Scenario scenario)
Creates a new compiler for the specified scenario.
Parameters
scenario scenario to be compiled
Definition at line 94 of file Compiler.java.
References org.onlab.stc.Compiler.scenario().
Member Function Documentation
void org.onlab.stc.Compiler.compile ()
Compiles the specified scenario to produce a final process flow graph.
Definition at line 110 of file Compiler.java.
References org.onlab.stc.Compiler.logDir(), org.onlab.stc.Compiler.processFlow(), and org.onlab.stc.Compiler.scenario().
Step org.onlab.stc.Compiler.getStep (String name)
Returns the step with the specified name.
Parameters
name step or group name
Returns
test step or group
Definition at line 132 of file Compiler.java.
References create-flow.name.
File org.onlab.stc.Compiler.logDir ()
Returns the log directory where scenario logs should be kept.
Returns
scenario logs directory
Definition at line 150 of file Compiler.java.
Referenced by org.onlab.stc.Compiler.compile().
ProcessFlow org.onlab.stc.Compiler.processFlow ()
Returns the process flow generated from this scenario definition.
Returns
process flow as a graph
Definition at line 141 of file Compiler.java.
Referenced by org.onlab.stc.Compiler.compile().
Scenario org.onlab.stc.Compiler.scenario ()
Returns the scenario being compiled.
Returns
test scenario
Definition at line 103 of file Compiler.java.
Referenced by org.onlab.stc.Compiler.compile(), and org.onlab.stc.Compiler.Compiler().
The documentation for this class was generated from the following file:
utils/stc/src/main/java/org/onlab/stc/Compiler.java