onos: org.onlab.packet.IpAddressTest Class Reference
org.onlab.packet.IpAddressTest Class Reference
Tests for class IpAddress.
Public Member Functions
void testImmutable ()
Tests the immutability of IpAddress.
void testAddrByteLength ()
Tests the length of the address in bytes (octets).
void testAddrBitLength ()
Tests the length of the address in bits.
void testVersion ()
Tests returning the IP address version.
void testIsIp4 ()
Tests whether the IP version of an address is IPv4.
void testIsIp6 ()
Tests whether the IP version of an address is IPv6.
void testGetIp4AndIp6AddressView ()
Tests getting the Ip4Address and Ip6Address view of the IP address.
void testAddressToOctetsIPv4 ()
Tests returning an IPv4 address as a byte array.
void testAddressToOctetsIPv6 ()
Tests returning an IPv6 address as a byte array.
void testValueOfForIntegerIPv4 ()
Tests valueOf() converter for IPv4 integer value.
void testValueOfByteArrayIPv4 ()
Tests valueOf() converter for IPv4 byte array.
void testValueOfByteArrayIPv6 ()
Tests valueOf() converter for IPv6 byte array.
void testInvalidValueOfNullArrayIPv4 ()
Tests invalid valueOf() converter for a null array for IPv4.
void testInvalidValueOfNullArrayIPv6 ()
Tests invalid valueOf() converter for a null array for IPv6.
void testInvalidValueOfShortArrayIPv4 ()
Tests invalid valueOf() converger for an array that is too short for IPv4.
void testInvalidValueOfShortArrayIPv6 ()
Tests invalid valueOf() converger for an array that is too short for IPv6.
void testValueOfByteArrayOffsetIPv4 ()
Tests valueOf() converter for IPv4 byte array and an offset.
void testValueOfByteArrayOffsetIPv6 ()
Tests valueOf() converter for IPv6 byte array and an offset.
void testInvalidValueOfArrayInvalidOffsetIPv4 ()
Tests invalid valueOf() converger for an array and an invalid offset for IPv4.
void testInvalidValueOfArrayInvalidOffsetIPv6 ()
Tests invalid valueOf() converger for an array and an invalid offset for IPv6.
void testValueOfInetAddressIPv4 ()
Tests valueOf() converter for IPv4 InetAddress.
void testValueOfInetAddressIPv6 ()
Tests valueOf() converter for IPv6 InetAddress.
void testValueOfStringIPv4 ()
Tests valueOf() converter for IPv4 string.
void testValueOfStringIPv6 ()
Tests valueOf() converter for IPv6 string.
void testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
void testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
void testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
void testMakeMaskPrefixIPv4 ()
Tests making a mask prefix for a given prefix length for IPv4.
void testMakeMaskPrefixIPv6 ()
Tests making a mask prefix for a given prefix length for IPv6.
void testInvalidMakeNegativeMaskPrefixIPv4 ()
Tests making a mask prefix for an invalid prefix length for IPv4: negative prefix length.
void testInvalidMakeNegativeMaskPrefixIPv6 ()
Tests making a mask prefix for an invalid prefix length for IPv6: negative prefix length.
void testInvalidMakeTooLongMaskPrefixIPv4 ()
Tests making a mask prefix for an invalid prefix length for IPv4: too long prefix length.
void testInvalidMakeTooLongMaskPrefixIPv6 ()
Tests making a mask prefix for an invalid prefix length for IPv6: too long prefix length.
void testMakeMaskedAddressIPv4 ()
Tests making of a masked address for IPv4.
void testMakeMaskedAddressIPv6 ()
Tests making of a masked address for IPv6.
void testInvalidMakeNegativeMaskedAddressIPv4 ()
Tests making of a masked address for invalid prefix length for IPv4: negative prefix length.
void testInvalidMakeNegativeMaskedAddressIPv6 ()
Tests making of a masked address for invalid prefix length for IPv6: negative prefix length.
void testInvalidMakeTooLongMaskedAddressIPv4 ()
Tests making of a masked address for an invalid prefix length for IPv4: too long prefix length.
void testInvalidMakeTooLongMaskedAddressIPv6 ()
Tests making of a masked address for an invalid prefix length for IPv6: too long prefix length.
void testIsZeroIPv4 ()
Tests if address is zero for IPv4.
void testIsZeroIPv6 ()
Tests if address is zero for IPv6.
void testIsSelfAssignedIpv4 ()
Tests if address is self-assigned for IPv4.
void testComparisonIPv4 ()
Tests comparison of IpAddress for IPv4.
void testComparisonIPv6 ()
Tests comparison of IpAddress for IPv6.
void testEqualityIPv4 ()
Tests equality of IpAddress for IPv4.
void testEqualityIPv6 ()
Tests equality of IpAddress for IPv6.
void testToStringIPv4 ()
Tests object string representation for IPv4.
void testToStringIPv6 ()
Tests object string representation for IPv6.
Detailed Description
Tests for class IpAddress.
Definition at line 35 of file IpAddressTest.java.
Member Function Documentation
void org.onlab.packet.IpAddressTest.testAddrBitLength ()
Tests the length of the address in bits.
Definition at line 59 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.INET6_BIT_LENGTH, and org.onlab.packet.IpAddress.INET_BIT_LENGTH.
void org.onlab.packet.IpAddressTest.testAddrByteLength ()
Tests the length of the address in bytes (octets).
Definition at line 48 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.byteLength(), org.onlab.packet.IpAddress.INET6_BYTE_LENGTH, and org.onlab.packet.IpAddress.INET_BYTE_LENGTH.
void org.onlab.packet.IpAddressTest.testAddressToOctetsIPv4 ()
Tests returning an IPv4 address as a byte array.
Definition at line 154 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toOctets().
void org.onlab.packet.IpAddressTest.testAddressToOctetsIPv6 ()
Tests returning an IPv6 address as a byte array.
Definition at line 176 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toOctets().
void org.onlab.packet.IpAddressTest.testComparisonIPv4 ()
Tests comparison of IpAddress for IPv4.
Definition at line 775 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.compareTo().
void org.onlab.packet.IpAddressTest.testComparisonIPv6 ()
Tests comparison of IpAddress for IPv6.
Definition at line 799 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.compareTo().
void org.onlab.packet.IpAddressTest.testEqualityIPv4 ()
Tests equality of IpAddress for IPv4.
Definition at line 831 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.valueOf().
void org.onlab.packet.IpAddressTest.testEqualityIPv6 ()
Tests equality of IpAddress for IPv6.
Definition at line 848 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.valueOf().
void org.onlab.packet.IpAddressTest.testGetIp4AndIp6AddressView ()
Tests getting the Ip4Address and Ip6Address view of the IP address.
Definition at line 116 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testImmutable ()
Tests the immutability of IpAddress.
Definition at line 40 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidMakeNegativeMaskedAddressIPv4 ()
Tests making of a masked address for invalid prefix length for IPv4: negative prefix length.
Definition at line 693 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidMakeNegativeMaskedAddressIPv6 ()
Tests making of a masked address for invalid prefix length for IPv6: negative prefix length.
Definition at line 705 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidMakeNegativeMaskPrefixIPv4 ()
Tests making a mask prefix for an invalid prefix length for IPv4: negative prefix length.
Definition at line 604 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidMakeNegativeMaskPrefixIPv6 ()
Tests making a mask prefix for an invalid prefix length for IPv6: negative prefix length.
Definition at line 615 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidMakeTooLongMaskedAddressIPv4 ()
Tests making of a masked address for an invalid prefix length for IPv4: too long prefix length.
Definition at line 718 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidMakeTooLongMaskedAddressIPv6 ()
Tests making of a masked address for an invalid prefix length for IPv6: too long prefix length.
Definition at line 730 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidMakeTooLongMaskPrefixIPv4 ()
Tests making a mask prefix for an invalid prefix length for IPv4: too long prefix length.
Definition at line 626 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidMakeTooLongMaskPrefixIPv6 ()
Tests making a mask prefix for an invalid prefix length for IPv6: too long prefix length.
Definition at line 637 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidValueOfArrayInvalidOffsetIPv4 ()
Tests invalid valueOf() converger for an array and an invalid offset for IPv4.
Definition at line 411 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidValueOfArrayInvalidOffsetIPv6 ()
Tests invalid valueOf() converger for an array and an invalid offset for IPv6.
Definition at line 426 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
Definition at line 539 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
Definition at line 550 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidValueOfNullArrayIPv4 ()
Tests invalid valueOf() converter for a null array for IPv4.
Definition at line 289 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidValueOfNullArrayIPv6 ()
Tests invalid valueOf() converter for a null array for IPv6.
Definition at line 301 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
Definition at line 528 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidValueOfShortArrayIPv4 ()
Tests invalid valueOf() converger for an array that is too short for IPv4.
Definition at line 314 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testInvalidValueOfShortArrayIPv6 ()
Tests invalid valueOf() converger for an array that is too short for IPv6.
Definition at line 327 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testIsIp4 ()
Tests whether the IP version of an address is IPv4.
Definition at line 84 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.isIp4().
void org.onlab.packet.IpAddressTest.testIsIp6 ()
Tests whether the IP version of an address is IPv6.
Definition at line 100 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.isIp6().
void org.onlab.packet.IpAddressTest.testIsSelfAssignedIpv4 ()
Tests if address is self-assigned for IPv4.
Definition at line 764 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.isSelfAssigned().
void org.onlab.packet.IpAddressTest.testIsZeroIPv4 ()
Tests if address is zero for IPv4.
Definition at line 742 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.isZero().
void org.onlab.packet.IpAddressTest.testIsZeroIPv6 ()
Tests if address is zero for IPv6.
Definition at line 753 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.isZero().
void org.onlab.packet.IpAddressTest.testMakeMaskedAddressIPv4 ()
Tests making of a masked address for IPv4.
Definition at line 647 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testMakeMaskedAddressIPv6 ()
Tests making of a masked address for IPv6.
Definition at line 665 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testMakeMaskPrefixIPv4 ()
Tests making a mask prefix for a given prefix length for IPv4.
Definition at line 561 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testMakeMaskPrefixIPv6 ()
Tests making a mask prefix for a given prefix length for IPv6.
Definition at line 578 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testToStringIPv4 ()
Tests object string representation for IPv4.
Definition at line 869 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testToStringIPv6 ()
Tests object string representation for IPv6.
Definition at line 886 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testValueOfByteArrayIPv4 ()
Tests valueOf() converter for IPv4 byte array.
Definition at line 230 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testValueOfByteArrayIPv6 ()
Tests valueOf() converter for IPv6 byte array.
Definition at line 252 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testValueOfByteArrayOffsetIPv4 ()
Tests valueOf() converter for IPv4 byte array and an offset.
Definition at line 339 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testValueOfByteArrayOffsetIPv6 ()
Tests valueOf() converter for IPv6 byte array and an offset.
Definition at line 367 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testValueOfForIntegerIPv4 ()
Tests valueOf() converter for IPv4 integer value.
Definition at line 213 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testValueOfInetAddressIPv4 ()
Tests valueOf() converter for IPv4 InetAddress.
Definition at line 444 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testValueOfInetAddressIPv6 ()
Tests valueOf() converter for IPv6 InetAddress.
Definition at line 465 of file IpAddressTest.java.
void org.onlab.packet.IpAddressTest.testValueOfStringIPv4 ()
Tests valueOf() converter for IPv4 string.
Definition at line 490 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testValueOfStringIPv6 ()
Tests valueOf() converter for IPv6 string.
Definition at line 507 of file IpAddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.IpAddressTest.testVersion ()
Tests returning the IP address version.
Definition at line 68 of file IpAddressTest.java.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/IpAddressTest.java