onos: org.onosproject.ovsdb.controller.OvsdbBridge Class Reference
org.onosproject.ovsdb.controller.OvsdbBridge Class Reference
The class representing an ovsdb bridge.
Public Member Functions
OvsdbBridge (OvsdbBridgeName bridgeName, OvsdbDatapathId datapathId)
Constructor from an OvsdbBridgeName bridgeName and an OvsdbDatapathId datapathId.
OvsdbBridgeName bridgeName ()
Gets the bridge name of bridge.
OvsdbDatapathId datapathId ()
Gets the datapathId of bridge.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
The class representing an ovsdb bridge.
This class is immutable.
Definition at line 27 of file OvsdbBridge.java.
Constructor & Destructor Documentation
org.onosproject.ovsdb.controller.OvsdbBridge.OvsdbBridge (OvsdbBridgeName bridgeName, OvsdbDatapathId datapathId)
Constructor from an OvsdbBridgeName bridgeName and an OvsdbDatapathId datapathId.
Parameters
bridgeName the bridgeName to use
datapathId the datapathId to use
Definition at line 39 of file OvsdbBridge.java.
References org.onosproject.ovsdb.controller.OvsdbBridge.bridgeName(), and org.onosproject.ovsdb.controller.OvsdbBridge.datapathId().
Referenced by org.onosproject.ovsdb.controller.OvsdbBridge.equals().
Member Function Documentation
OvsdbBridgeName org.onosproject.ovsdb.controller.OvsdbBridge.bridgeName ()
Gets the bridge name of bridge.
Returns
the bridge name of bridge
Definition at line 51 of file OvsdbBridge.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbBridge.hashCode(), and org.onosproject.ovsdb.controller.OvsdbBridge.OvsdbBridge().
OvsdbDatapathId org.onosproject.ovsdb.controller.OvsdbBridge.datapathId ()
Gets the datapathId of bridge.
Returns
datapathId the datapathId to use
Definition at line 60 of file OvsdbBridge.java.
Referenced by org.onosproject.ovsdb.controller.OvsdbBridge.hashCode(), and org.onosproject.ovsdb.controller.OvsdbBridge.OvsdbBridge().
boolean org.onosproject.ovsdb.controller.OvsdbBridge.equals (Object obj)
Definition at line 70 of file OvsdbBridge.java.
References org.onosproject.ovsdb.controller.OvsdbBridge.OvsdbBridge().
int org.onosproject.ovsdb.controller.OvsdbBridge.hashCode ()
Definition at line 65 of file OvsdbBridge.java.
References org.onosproject.ovsdb.controller.OvsdbBridge.bridgeName(), and org.onosproject.ovsdb.controller.OvsdbBridge.datapathId().
String org.onosproject.ovsdb.controller.OvsdbBridge.toString ()
Definition at line 84 of file OvsdbBridge.java.
The documentation for this class was generated from the following file:
protocols/ovsdb/api/src/main/java/org/onosproject/ovsdb/controller/OvsdbBridge.java