onos: org.onosproject.driver.handshaker.DefaultSwitchHandshaker Class Reference
org.onosproject.driver.handshaker.DefaultSwitchHandshaker Class Reference
Default driver to fallback on if no other driver is available.
Public Member Functions
Boolean supportNxRole ()
Does this switch support Nicira Role messages.
void startDriverHandshake ()
Starts the driver specific handshake process.
void processDriverHandshakeMessage (OFMessage m)
Process a message during the driver specific handshake.
boolean isDriverHandshakeComplete ()
Checks whether the driver specific handshake is complete.
List< OFPortDesc > getPorts ()
Fetches the ports of this switch.
Public Member Functions inherited from org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch
void init (Dpid dpid, OFDescStatsReply desc, OFVersion ofv)
Initialises the behaviour.
final void disconnectSwitch ()
Disconnects the switch by closing the TCP connection.
void sendMsg (OFMessage msg)
Writes the message to the driver.
final void sendMsg (List< OFMessage > msgs)
Writes the OFMessage list to the driver.
final void sendRoleRequest (OFMessage msg)
Sends only role request messages.
final void sendHandshakeMessage (OFMessage message)
Allows the handshaker behaviour to send messages during the handshake phase only.
final boolean isConnected ()
Checks if the switch is still connected.
final void setConnected (boolean connected)
Sets whether the switch is connected.
final void setChannel (Channel channel)
Sets the associated Netty channel for this switch.
String channelId ()
Identifies the channel used to communicate with the switch.
final long getId ()
Gets the datapathId of the switch.
final String getStringId ()
Gets a string version of the ID for this switch.
final void setOFVersion (OFVersion ofV)
Sets the OF version for this switch.
void setTableFull (boolean full)
Sets this switch has having a full flowtable.
void setFeaturesReply (OFFeaturesReply featuresReply)
Sets the features reply for this switch.
final void handleMessage (OFMessage m)
Handle the message coming from the dataplane.
RoleState getRole ()
Fetch the role for this switch.
final boolean connectSwitch ()
Announce to the OpenFlow agent that this switch has connected.
final boolean activateMasterSwitch ()
Activate this MASTER switch-controller relationship in the OF agent.
final boolean activateEqualSwitch ()
Activate this EQUAL switch-controller relationship in the OF agent.
final void transitionToEqualSwitch ()
Transition this switch-controller relationship to an EQUAL state.
final void transitionToMasterSwitch ()
Transition this switch-controller relationship to an Master state.
final void removeConnectedSwitch ()
Remove this switch from the openflow agent.
OFFactory factory ()
Provides the factory for this OF version.
void setPortDescReply (OFPortDescStatsReply portDescReply)
Sets the ports on this switch.
void setPortDescReplies (List< OFPortDescStatsReply > portDescReplies)
Sets the ports on this switch.
void returnRoleReply (RoleState requested, RoleState response)
Notifies the controller that the device has responded to a set-role request.
void setRole (RoleState role)
Sets the role for this switch.
void reassertRole ()
Reasserts this controllers role to the switch.
void handleRole (OFMessage m) throws SwitchStateException
Handle OF 1.x (where x > 0) role messages.
void handleNiciraRole (OFMessage m) throws SwitchStateException
If this driver know of Nicira style role messages, these should be handled here.
boolean handleRoleError (OFErrorMsg error)
Handle the situation where the role request triggers an error.
final void setAgent (OpenFlowAgent ag)
Sets the OpenFlow agent to be used.
final void setRoleHandler (RoleHandler roleHandler)
Sets the Role handler object.
void setSwitchDescription (OFDescStatsReply d)
Sets the switch description.
int getNextTransactionId ()
Gets the next transaction id to use.
List< OFPortDesc > getPorts ()
Fetches the ports of this switch.
String manufacturerDescription ()
fetch the manufacturer description.
String datapathDescription ()
fetch the datapath description.
String hardwareDescription ()
fetch the hardware description.
String softwareDescription ()
fetch the software description.
String serialNumber ()
fetch the serial number.
Device.Type deviceType ()
Returns the switch device type.
String toString ()
Public Member Functions inherited from org.onosproject.net.driver.AbstractHandlerBehaviour
DriverHandler handler ()
Returns the driver handler context on which this behaviour operates.
void setHandler (DriverHandler handler)
Sets the driver handler context for this behaviour.
Public Member Functions inherited from org.onosproject.net.driver.AbstractBehaviour
DriverData data ()
Returns the driver data context.
void setData (DriverData data)
Sets the driver data context on this this behaviour should operate.
Additional Inherited Members
Protected Attributes inherited from org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch
final Logger log = LoggerFactory.getLogger(getClass())
String channelId
boolean startDriverHandshakeCalled = false
List< OFPortDescStatsReply > ports = new ArrayList<>()
boolean tableFull
volatile RoleState role
OFFeaturesReply features
OFDescStatsReply desc
Detailed Description
Default driver to fallback on if no other driver is available.
Definition at line 31 of file DefaultSwitchHandshaker.java.
Member Function Documentation
List<OFPortDesc> org.onosproject.driver.handshaker.DefaultSwitchHandshaker.getPorts ()
Fetches the ports of this switch.
Returns
unmodifiable list of the ports.
Implements org.onosproject.openflow.controller.OpenFlowSwitch.
Definition at line 58 of file DefaultSwitchHandshaker.java.
References org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.factory().
boolean org.onosproject.driver.handshaker.DefaultSwitchHandshaker.isDriverHandshakeComplete () virtual
Checks whether the driver specific handshake is complete.
Returns
true is finished, false if not.
Implements org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
Definition at line 53 of file DefaultSwitchHandshaker.java.
void org.onosproject.driver.handshaker.DefaultSwitchHandshaker.processDriverHandshakeMessage (OFMessage m) virtual
Process a message during the driver specific handshake.
Parameters
m the message to process.
Implements org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
Definition at line 50 of file DefaultSwitchHandshaker.java.
void org.onosproject.driver.handshaker.DefaultSwitchHandshaker.startDriverHandshake () virtual
Starts the driver specific handshake process.
Implements org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
Definition at line 41 of file DefaultSwitchHandshaker.java.
References org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.factory(), and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.sendHandshakeMessage().
Boolean org.onosproject.driver.handshaker.DefaultSwitchHandshaker.supportNxRole () virtual
Does this switch support Nicira Role messages.
Returns
true if supports, false otherwise.
Implements org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
Reimplemented in org.onosproject.driver.handshaker.NiciraSwitchHandshaker.
Definition at line 36 of file DefaultSwitchHandshaker.java.
The documentation for this class was generated from the following file:
drivers/src/main/java/org/onosproject/driver/handshaker/DefaultSwitchHandshaker.java