onos: org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion Class Reference
org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion Class Reference
Implementation of IPv6 Neighbor Discovery target address criterion.
Public Member Functions
Type type ()
Returns the type of criterion.
Ip6Address targetAddress ()
Gets the IPv6 target address to match.
String toString ()
int hashCode ()
boolean equals (Object obj)
Detailed Description
Implementation of IPv6 Neighbor Discovery target address criterion.
Definition at line 27 of file IPv6NDTargetAddressCriterion.java.
Member Function Documentation
boolean org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.equals (Object obj)
Definition at line 65 of file IPv6NDTargetAddressCriterion.java.
References org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.targetAddress(), and org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.type().
int org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.hashCode ()
Definition at line 60 of file IPv6NDTargetAddressCriterion.java.
References org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.type().
Ip6Address org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.targetAddress ()
Gets the IPv6 target address to match.
Returns
the IPv6 target address to match
Definition at line 49 of file IPv6NDTargetAddressCriterion.java.
Referenced by org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.equals(), and org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.toString().
String org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.toString ()
Definition at line 54 of file IPv6NDTargetAddressCriterion.java.
References org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.targetAddress(), and org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.type().
Type org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.type ()
Returns the type of criterion.
Returns
type of criterion
Implements org.onosproject.net.flow.criteria.Criterion.
Definition at line 40 of file IPv6NDTargetAddressCriterion.java.
References org.onosproject.net.flow.criteria.Criterion.Type.IPV6_ND_TARGET.
Referenced by org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.equals(), org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.hashCode(), and org.onosproject.net.flow.criteria.IPv6NDTargetAddressCriterion.toString().
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/criteria/IPv6NDTargetAddressCriterion.java