onos: org.onosproject.net.meter.MeterId Class Reference
org.onosproject.net.meter.MeterId Class Reference
A representation of a meter id.
Public Member Functions
long id ()
The integer representation of the meter id.
boolean equals (Object o)
int hashCode ()
String toString ()
Static Public Member Functions
static MeterId meterId (long id)
Static Public Attributes
static final MeterId SLOWPATH = new MeterId(0xFFFFFFFD)
static final MeterId CONTROLLER = new MeterId(0xFFFFFFFE)
static final MeterId ALL = new MeterId(0xFFFFFFFF)
Detailed Description
A representation of a meter id.
Uniquely identifies a meter system wide.
Definition at line 24 of file MeterId.java.
Member Function Documentation
boolean org.onosproject.net.meter.MeterId.equals (Object o)
Definition at line 49 of file MeterId.java.
References find-device.id, and org.onosproject.net.meter.MeterId.meterId().
int org.onosproject.net.meter.MeterId.hashCode ()
Definition at line 64 of file MeterId.java.
References org.onosproject.net.meter.MeterId.id().
long org.onosproject.net.meter.MeterId.id ()
The integer representation of the meter id.
Returns
a long
Definition at line 44 of file MeterId.java.
Referenced by org.onosproject.net.meter.MeterId.hashCode().
static MeterId org.onosproject.net.meter.MeterId.meterId (long id) static
Definition at line 73 of file MeterId.java.
Referenced by org.onosproject.net.meter.MeterId.equals(), org.onosproject.incubator.net.meter.impl.MeterManagerTest.testAddition(), org.onosproject.net.meter.DefaultMeterTest.testConstruction(), org.onosproject.incubator.net.meter.impl.MeterManagerTest.testMultipleDevice(), and org.onosproject.incubator.net.meter.impl.MeterManagerTest.testRemove().
String org.onosproject.net.meter.MeterId.toString ()
Definition at line 69 of file MeterId.java.
References find-device.id.
Member Data Documentation
final MeterId org.onosproject.net.meter.MeterId.ALL = new MeterId(0xFFFFFFFF) static
Definition at line 32 of file MeterId.java.
final MeterId org.onosproject.net.meter.MeterId.CONTROLLER = new MeterId(0xFFFFFFFE) static
Definition at line 31 of file MeterId.java.
final MeterId org.onosproject.net.meter.MeterId.SLOWPATH = new MeterId(0xFFFFFFFD) static
Definition at line 30 of file MeterId.java.
The documentation for this class was generated from the following file:
core/api/src/main/java/org/onosproject/net/meter/MeterId.java