onos: org.onlab.packet.Ip6AddressTest Class Reference
org.onlab.packet.Ip6AddressTest Class Reference
Tests for class Ip6Address.
Public Member Functions
void testImmutable ()
Tests the immutability of Ip6Address.
void testAddressVersion ()
Tests the IPv4 address version constant.
void testAddrByteLength ()
Tests the length of the address in bytes (octets).
void testAddrBitLength ()
Tests the length of the address in bits.
void testVersion ()
Tests returning the IP address version.
void testAddressToOctetsIPv6 ()
Tests returning an IPv6 address as a byte array.
void testValueOfByteArrayIPv6 ()
Tests valueOf() converter for IPv6 byte array.
void testInvalidValueOfNullArrayIPv6 ()
Tests invalid valueOf() converter for a null array for IPv6.
void testInvalidValueOfShortArrayIPv6 ()
Tests invalid valueOf() converger for an array that is too short for IPv6.
void testValueOfByteArrayOffsetIPv6 ()
Tests valueOf() converter for IPv6 byte array and an offset.
void testInvalidValueOfArrayInvalidOffsetIPv6 ()
Tests invalid valueOf() converger for an array and an invalid offset for IPv6.
void testValueOfInetAddressIPv6 ()
Tests valueOf() converter for IPv6 InetAddress.
void testValueOfStringIPv6 ()
Tests valueOf() converter for IPv6 string.
void testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
void testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
void testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
void testMakeMaskPrefixIPv6 ()
Tests making a mask prefix for a given prefix length for IPv6.
void testInvalidMakeNegativeMaskPrefixIPv6 ()
Tests making a mask prefix for an invalid prefix length for IPv6: negative prefix length.
void testInvalidMakeTooLongMaskPrefixIPv6 ()
Tests making a mask prefix for an invalid prefix length for IPv6: too long prefix length.
void testMakeMaskedAddressIPv6 ()
Tests making of a masked address for IPv6.
void testInvalidMakeNegativeMaskedAddressIPv6 ()
Tests making of a masked address for invalid prefix length for IPv6: negative prefix length.
void testInvalidMakeTooLongMaskedAddressIPv6 ()
Tests making of a masked address for an invalid prefix length for IPv6: too long prefix length.
void testComparisonIPv6 ()
Tests comparison of Ip6Address for IPv6.
void testEqualityIPv6 ()
Tests equality of Ip6Address for IPv6.
void testToStringIPv6 ()
Tests object string representation for IPv6.
Detailed Description
Tests for class Ip6Address.
Definition at line 32 of file Ip6AddressTest.java.
Member Function Documentation
void org.onlab.packet.Ip6AddressTest.testAddrBitLength ()
Tests the length of the address in bits.
Definition at line 61 of file Ip6AddressTest.java.
References org.onlab.packet.Ip6Address.BIT_LENGTH.
void org.onlab.packet.Ip6AddressTest.testAddrByteLength ()
Tests the length of the address in bytes (octets).
Definition at line 53 of file Ip6AddressTest.java.
References org.onlab.packet.Ip6Address.BYTE_LENGTH.
void org.onlab.packet.Ip6AddressTest.testAddressToOctetsIPv6 ()
Tests returning an IPv6 address as a byte array.
Definition at line 81 of file Ip6AddressTest.java.
References org.onlab.packet.IpAddress.toOctets().
void org.onlab.packet.Ip6AddressTest.testAddressVersion ()
Tests the IPv4 address version constant.
Definition at line 45 of file Ip6AddressTest.java.
References org.onlab.packet.Ip6Address.VERSION.
void org.onlab.packet.Ip6AddressTest.testComparisonIPv6 ()
Tests comparison of Ip6Address for IPv6.
Definition at line 421 of file Ip6AddressTest.java.
References org.onlab.packet.IpAddress.compareTo().
void org.onlab.packet.Ip6AddressTest.testEqualityIPv6 ()
Tests equality of Ip6Address for IPv6.
Definition at line 453 of file Ip6AddressTest.java.
References org.onlab.packet.Ip6Address.valueOf().
void org.onlab.packet.Ip6AddressTest.testImmutable ()
Tests the immutability of Ip6Address.
Definition at line 37 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testInvalidMakeNegativeMaskedAddressIPv6 ()
Tests making of a masked address for invalid prefix length for IPv6: negative prefix length.
Definition at line 396 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testInvalidMakeNegativeMaskPrefixIPv6 ()
Tests making a mask prefix for an invalid prefix length for IPv6: negative prefix length.
Definition at line 347 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testInvalidMakeTooLongMaskedAddressIPv6 ()
Tests making of a masked address for an invalid prefix length for IPv6: too long prefix length.
Definition at line 409 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testInvalidMakeTooLongMaskPrefixIPv6 ()
Tests making a mask prefix for an invalid prefix length for IPv6: too long prefix length.
Definition at line 358 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testInvalidValueOfArrayInvalidOffsetIPv6 ()
Tests invalid valueOf() converger for an array and an invalid offset for IPv6.
Definition at line 224 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testInvalidValueOfEmptyString ()
Tests invalid valueOf() converter for an empty string.
Definition at line 299 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testInvalidValueOfIncorrectString ()
Tests invalid valueOf() converter for an incorrect string.
Definition at line 310 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testInvalidValueOfNullArrayIPv6 ()
Tests invalid valueOf() converter for a null array for IPv6.
Definition at line 155 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testInvalidValueOfNullString ()
Tests invalid valueOf() converter for a null string.
Definition at line 288 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testInvalidValueOfShortArrayIPv6 ()
Tests invalid valueOf() converger for an array that is too short for IPv6.
Definition at line 168 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testMakeMaskedAddressIPv6 ()
Tests making of a masked address for IPv6.
Definition at line 368 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testMakeMaskPrefixIPv6 ()
Tests making a mask prefix for a given prefix length for IPv6.
Definition at line 321 of file Ip6AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip6AddressTest.testToStringIPv6 ()
Tests object string representation for IPv6.
Definition at line 474 of file Ip6AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip6AddressTest.testValueOfByteArrayIPv6 ()
Tests valueOf() converter for IPv6 byte array.
Definition at line 118 of file Ip6AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip6AddressTest.testValueOfByteArrayOffsetIPv6 ()
Tests valueOf() converter for IPv6 byte array and an offset.
Definition at line 180 of file Ip6AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip6AddressTest.testValueOfInetAddressIPv6 ()
Tests valueOf() converter for IPv6 InetAddress.
Definition at line 242 of file Ip6AddressTest.java.
void org.onlab.packet.Ip6AddressTest.testValueOfStringIPv6 ()
Tests valueOf() converter for IPv6 string.
Definition at line 267 of file Ip6AddressTest.java.
References org.onlab.packet.IpAddress.toString().
void org.onlab.packet.Ip6AddressTest.testVersion ()
Tests returning the IP address version.
Definition at line 69 of file Ip6AddressTest.java.
The documentation for this class was generated from the following file:
utils/misc/src/test/java/org/onlab/packet/Ip6AddressTest.java