onos: org.onosproject.codec.impl.GroupBucketJsonMatcher Class Reference
org.onosproject.codec.impl.GroupBucketJsonMatcher Class Reference
Hamcrest matcher for instructions.
Public Member Functions
boolean matchesSafely (JsonNode bucketJson, Description description)
Matches the contents of a group bucket.
void describeTo (Description description)
Static Public Member Functions
static GroupBucketJsonMatcher matchesGroupBucket (GroupBucket bucket)
Factory to allocate an bucket matcher.
Detailed Description
Hamcrest matcher for instructions.
Definition at line 27 of file GroupBucketJsonMatcher.java.
Member Function Documentation
void org.onosproject.codec.impl.GroupBucketJsonMatcher.describeTo (Description description)
Definition at line 74 of file GroupBucketJsonMatcher.java.
static GroupBucketJsonMatcher org.onosproject.codec.impl.GroupBucketJsonMatcher.matchesGroupBucket (GroupBucket bucket) static
Factory to allocate an bucket matcher.
Parameters
bucket bucket object we are looking for
Returns
matcher
Definition at line 84 of file GroupBucketJsonMatcher.java.
boolean org.onosproject.codec.impl.GroupBucketJsonMatcher.matchesSafely (JsonNode bucketJson, Description description)
Matches the contents of a group bucket.
Parameters
bucketJson JSON representation of bucket to match
description Description object used for recording errors
Returns
true if contents match, false otherwise
Definition at line 43 of file GroupBucketJsonMatcher.java.
References org.onosproject.net.group.GroupBucket.bytes(), org.onosproject.net.group.GroupBucket.packets(), org.onosproject.net.group.GroupBucket.type(), and org.onosproject.net.group.GroupBucket.weight().
The documentation for this class was generated from the following file:
core/common/src/test/java/org/onosproject/codec/impl/GroupBucketJsonMatcher.java