onos: org.onosproject.pcepio.types.TELinkAttributesTlv Class Reference
org.onosproject.pcepio.types.TELinkAttributesTlv Class Reference
Provides TELinkAttributesTlv.
Public Member Functions
TELinkAttributesTlv (LinkedList< PcepValueType > llLinkAttributesSubTLVs)
Constructor to initialize Link Attributes Sub TLVs.
LinkedList< PcepValueType > getllLinkAttributesSubTLVs ()
Returns linked list of Link Attribute of Sub TLV.
PcepVersion getVersion ()
Returns the Version Of PCEP Message.
short getType ()
Returns the Type of PCEP Message.
short getLength ()
Returns the Length of PCEP Message.
int hashCode ()
boolean equals (Object obj)
int write (ChannelBuffer c)
Writes the byte Stream of PCEP Message to channel buffer.
String toString ()
Static Public Member Functions
static TELinkAttributesTlv of (final LinkedList< PcepValueType > llLinkAttributesSubTLVs)
Returns object of TE Link Attributes TLV.
static PcepValueType read (ChannelBuffer c, short hLength) throws PcepParseException
Reads channel buffer and returns object of TE Link Attributes TLV.
Public Attributes
short hLength
Static Public Attributes
static final short TYPE = 1897
static final int TLV_HEADER_LENGTH = 4
Static Protected Attributes
static final Logger log = LoggerFactory.getLogger(TELinkAttributesTlv.class)
Detailed Description
Provides TELinkAttributesTlv.
Definition at line 34 of file TELinkAttributesTlv.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.types.TELinkAttributesTlv.TELinkAttributesTlv (LinkedList< PcepValueType > llLinkAttributesSubTLVs)
Constructor to initialize Link Attributes Sub TLVs.
Parameters
llLinkAttributesSubTLVs linked list of PcepValueType
Definition at line 64 of file TELinkAttributesTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkAttributesTlv.equals(), org.onosproject.pcepio.types.TELinkAttributesTlv.of(), and org.onosproject.pcepio.types.TELinkAttributesTlv.read().
Member Function Documentation
boolean org.onosproject.pcepio.types.TELinkAttributesTlv.equals (Object obj)
Definition at line 108 of file TELinkAttributesTlv.java.
References org.onosproject.pcepio.types.TELinkAttributesTlv.TELinkAttributesTlv().
short org.onosproject.pcepio.types.TELinkAttributesTlv.getLength ()
Returns the Length of PCEP Message.
Returns
value of Length
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 98 of file TELinkAttributesTlv.java.
References org.onosproject.pcepio.types.TELinkAttributesTlv.hLength.
LinkedList<PcepValueType> org.onosproject.pcepio.types.TELinkAttributesTlv.getllLinkAttributesSubTLVs ()
Returns linked list of Link Attribute of Sub TLV.
Returns
llLinkAttributesSubTLVs linked list of Link Attribute of Sub TLV
Definition at line 83 of file TELinkAttributesTlv.java.
short org.onosproject.pcepio.types.TELinkAttributesTlv.getType ()
Returns the Type of PCEP Message.
Returns
value of type
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 93 of file TELinkAttributesTlv.java.
References org.onosproject.pcepio.types.TELinkAttributesTlv.TYPE.
PcepVersion org.onosproject.pcepio.types.TELinkAttributesTlv.getVersion ()
Returns the Version Of PCEP Message.
Returns
Version of PcepVersion Type.
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 88 of file TELinkAttributesTlv.java.
References org.onosproject.pcepio.protocol.PcepVersion.PCEP_1.
int org.onosproject.pcepio.types.TELinkAttributesTlv.hashCode ()
Definition at line 103 of file TELinkAttributesTlv.java.
static TELinkAttributesTlv org.onosproject.pcepio.types.TELinkAttributesTlv.of (final LinkedList< PcepValueType > llLinkAttributesSubTLVs) static
Returns object of TE Link Attributes TLV.
Parameters
llLinkAttributesSubTLVs linked list of Link Attribute of Sub TLV
Returns
object of TELinkAttributesTlv
Definition at line 74 of file TELinkAttributesTlv.java.
References org.onosproject.pcepio.types.TELinkAttributesTlv.TELinkAttributesTlv().
static PcepValueType org.onosproject.pcepio.types.TELinkAttributesTlv.read (ChannelBuffer c, short hLength) throws PcepParseException static
Reads channel buffer and returns object of TE Link Attributes TLV.
Parameters
c input channel buffer
hLength length
Returns
object of TELinkAttributesTlv
Exceptions
PcepParseException if mandatory fields are missing
Definition at line 186 of file TELinkAttributesTlv.java.
References org.onosproject.pcepio.types.TELinkAttributesTlv.hLength, find-link-in-cluster.length, org.onosproject.pcepio.types.TELinkAttributesTlv.TELinkAttributesTlv(), org.onosproject.pcepio.types.TELinkAttributesTlv.TLV_HEADER_LENGTH, org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.VALUE_LENGTH, and org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.VALUE_LENGTH.
String org.onosproject.pcepio.types.TELinkAttributesTlv.toString ()
Definition at line 285 of file TELinkAttributesTlv.java.
References org.onosproject.pcepio.types.TELinkAttributesTlv.hLength, and org.onosproject.pcepio.types.TELinkAttributesTlv.TYPE.
int org.onosproject.pcepio.types.TELinkAttributesTlv.write (ChannelBuffer bb)
Writes the byte Stream of PCEP Message to channel buffer.
Parameters
bb of type channel buffer
Returns
length of bytes written to channel buffer
Implements org.onosproject.pcepio.types.PcepValueType.
Definition at line 143 of file TELinkAttributesTlv.java.
References org.onosproject.pcepio.types.TELinkAttributesTlv.hLength, org.onosproject.pcepio.types.TELinkAttributesTlv.TLV_HEADER_LENGTH, and org.onosproject.pcepio.types.TELinkAttributesTlv.TYPE.
Member Data Documentation
short org.onosproject.pcepio.types.TELinkAttributesTlv.hLength
Definition at line 52 of file TELinkAttributesTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkAttributesTlv.getLength(), org.onosproject.pcepio.types.TELinkAttributesTlv.read(), org.onosproject.pcepio.types.TELinkAttributesTlv.toString(), and org.onosproject.pcepio.types.TELinkAttributesTlv.write().
final Logger org.onosproject.pcepio.types.TELinkAttributesTlv.log = LoggerFactory.getLogger(TELinkAttributesTlv.class) static protected
Definition at line 49 of file TELinkAttributesTlv.java.
final int org.onosproject.pcepio.types.TELinkAttributesTlv.TLV_HEADER_LENGTH = 4 static
Definition at line 54 of file TELinkAttributesTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkAttributesTlv.read(), and org.onosproject.pcepio.types.TELinkAttributesTlv.write().
final short org.onosproject.pcepio.types.TELinkAttributesTlv.TYPE = 1897 static
Definition at line 51 of file TELinkAttributesTlv.java.
Referenced by org.onosproject.pcepio.types.TELinkAttributesTlv.getType(), org.onosproject.pcepio.types.TELinkAttributesTlv.toString(), and org.onosproject.pcepio.types.TELinkAttributesTlv.write().
The documentation for this class was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/types/TELinkAttributesTlv.java