onos: org.onosproject.routing.bgp.BgpSessionInfo Class Reference
org.onosproject.routing.bgp.BgpSessionInfo Class Reference
Class for keeping information about a BGP session.
Public Member Functions
SocketAddress address ()
Gets the BGP session address: local or remote.
void setAddress (SocketAddress address)
Sets the BGP session address: local or remote.
Ip4Address ip4Address ()
Gets the BGP session IPv4 address: local or remote.
void setIp4Address (Ip4Address ip4Address)
Sets the BGP session IPv4 address: local or remote.
int bgpVersion ()
Gets the BGP session BGP version: local or remote.
void setBgpVersion (int bgpVersion)
Sets the BGP session BGP version: local or remote.
long asNumber ()
Gets the BGP session AS number: local or remote.
void setAsNumber (long asNumber)
Sets the BGP session AS number: local or remote.
long as4Number ()
Gets the BGP session AS4 number: local or remote.
void setAs4Number (long as4Number)
Sets the BGP session AS4 number: local or remote.
long holdtime ()
Gets the BGP session holdtime: local or remote.
void setHoldtime (long holdtime)
Sets the BGP session holdtime: local or remote.
Ip4Address bgpId ()
Gets the BGP session BGP Identifier as an IPv4 address: local or remote.
void setBgpId (Ip4Address bgpId)
Sets the BGP session BGP Identifier as an IPv4 address: local or remote.
boolean mpExtensions ()
Gets the BGP Multiprotocol Extensions: local or remote.
boolean ipv4Unicast ()
Gets the BGP session AFI/SAFI configuration for IPv4 unicast: local or remote.
void setIpv4Unicast ()
Sets the BGP session AFI/SAFI configuration for IPv4 unicast: local or remote.
boolean ipv4Multicast ()
Gets the BGP session AFI/SAFI configuration for IPv4 multicast: local or remote.
void setIpv4Multicast ()
Sets the BGP session AFI/SAFI configuration for IPv4 multicast: local or remote.
boolean ipv6Unicast ()
Gets the BGP session AFI/SAFI configuration for IPv6 unicast: local or remote.
boolean ipv6Multicast ()
Gets the BGP session AFI/SAFI configuration for IPv6 multicast: local or remote.
void setIpv6Multicast ()
Sets the BGP session AFI/SAFI configuration for IPv6 multicast: local or remote.
boolean as4OctetCapability ()
Gets the BGP session 4 octet AS path capability: local or remote.
void setAs4OctetCapability ()
Sets the BGP session 4 octet AS path capability.
Detailed Description
Class for keeping information about a BGP session.
There are two instances per each BGP peer session: one to keep the local information about the BGP session, and another to keep information about the remote BGP peer.
Definition at line 29 of file BgpSessionInfo.java.
Member Function Documentation
SocketAddress org.onosproject.routing.bgp.BgpSessionInfo.address ()
Gets the BGP session address: local or remote.
Returns
the BGP session address
Definition at line 50 of file BgpSessionInfo.java.
Referenced by org.onosproject.routing.bgp.BgpSessionInfo.setAddress().
long org.onosproject.routing.bgp.BgpSessionInfo.as4Number ()
Gets the BGP session AS4 number: local or remote.
Returns
the BGP session AS4 number
Definition at line 122 of file BgpSessionInfo.java.
Referenced by org.onosproject.routing.bgp.BgpSessionInfo.setAs4Number().
boolean org.onosproject.routing.bgp.BgpSessionInfo.as4OctetCapability ()
Gets the BGP session 4 octet AS path capability: local or remote.
Returns
true when the BGP session has 4 octet AS path capability
Definition at line 262 of file BgpSessionInfo.java.
long org.onosproject.routing.bgp.BgpSessionInfo.asNumber ()
Gets the BGP session AS number: local or remote.
Returns
the BGP session AS number
Definition at line 104 of file BgpSessionInfo.java.
Referenced by org.onosproject.routing.bgp.BgpSessionInfo.setAsNumber().
Ip4Address org.onosproject.routing.bgp.BgpSessionInfo.bgpId ()
Gets the BGP session BGP Identifier as an IPv4 address: local or remote.
Returns
the BGP session BGP Identifier as an IPv4 address
Definition at line 158 of file BgpSessionInfo.java.
Referenced by org.onosproject.routing.bgp.BgpSessionInfo.setBgpId().
int org.onosproject.routing.bgp.BgpSessionInfo.bgpVersion ()
Gets the BGP session BGP version: local or remote.
Returns
the BGP session BGP version
Definition at line 86 of file BgpSessionInfo.java.
Referenced by org.onosproject.routing.bgp.BgpSessionInfo.setBgpVersion().
long org.onosproject.routing.bgp.BgpSessionInfo.holdtime ()
Gets the BGP session holdtime: local or remote.
Returns
the BGP session holdtime
Definition at line 140 of file BgpSessionInfo.java.
Referenced by org.onosproject.routing.bgp.BgpSessionInfo.setHoldtime().
Ip4Address org.onosproject.routing.bgp.BgpSessionInfo.ip4Address ()
Gets the BGP session IPv4 address: local or remote.
Returns
the BGP session IPv4 address
Definition at line 68 of file BgpSessionInfo.java.
Referenced by org.onosproject.routing.bgp.BgpSessionInfo.setIp4Address().
boolean org.onosproject.routing.bgp.BgpSessionInfo.ipv4Multicast ()
Gets the BGP session AFI/SAFI configuration for IPv4 multicast: local or remote.
Returns
the BGP session AFI/SAFI configuration for IPv4 multicast
Definition at line 206 of file BgpSessionInfo.java.
boolean org.onosproject.routing.bgp.BgpSessionInfo.ipv4Unicast ()
Gets the BGP session AFI/SAFI configuration for IPv4 unicast: local or remote.
Returns
the BGP session AFI/SAFI configuration for IPv4 unicast
Definition at line 187 of file BgpSessionInfo.java.
boolean org.onosproject.routing.bgp.BgpSessionInfo.ipv6Multicast ()
Gets the BGP session AFI/SAFI configuration for IPv6 multicast: local or remote.
Returns
the BGP session AFI/SAFI configuration for IPv6 multicast
Definition at line 244 of file BgpSessionInfo.java.
boolean org.onosproject.routing.bgp.BgpSessionInfo.ipv6Unicast ()
Gets the BGP session AFI/SAFI configuration for IPv6 unicast: local or remote.
Returns
the BGP session AFI/SAFI configuration for IPv6 unicast
Definition at line 225 of file BgpSessionInfo.java.
boolean org.onosproject.routing.bgp.BgpSessionInfo.mpExtensions ()
Gets the BGP Multiprotocol Extensions: local or remote.
Returns
true if the BGP Multiprotocol Extensions are enabled, otherwise false
Definition at line 177 of file BgpSessionInfo.java.
void org.onosproject.routing.bgp.BgpSessionInfo.setAddress (SocketAddress address)
Sets the BGP session address: local or remote.
Parameters
address the BGP session address to set
Definition at line 59 of file BgpSessionInfo.java.
References org.onosproject.routing.bgp.BgpSessionInfo.address().
void org.onosproject.routing.bgp.BgpSessionInfo.setAs4Number (long as4Number)
Sets the BGP session AS4 number: local or remote.
Parameters
as4Number the BGP session AS4 number to set
Definition at line 131 of file BgpSessionInfo.java.
References org.onosproject.routing.bgp.BgpSessionInfo.as4Number().
void org.onosproject.routing.bgp.BgpSessionInfo.setAs4OctetCapability ()
Sets the BGP session 4 octet AS path capability.
Definition at line 269 of file BgpSessionInfo.java.
void org.onosproject.routing.bgp.BgpSessionInfo.setAsNumber (long asNumber)
Sets the BGP session AS number: local or remote.
Parameters
asNumber the BGP session AS number to set
Definition at line 113 of file BgpSessionInfo.java.
References org.onosproject.routing.bgp.BgpSessionInfo.asNumber().
void org.onosproject.routing.bgp.BgpSessionInfo.setBgpId (Ip4Address bgpId)
Sets the BGP session BGP Identifier as an IPv4 address: local or remote.
Parameters
bgpId the BGP session BGP Identifier to set
Definition at line 167 of file BgpSessionInfo.java.
References org.onosproject.routing.bgp.BgpSessionInfo.bgpId().
void org.onosproject.routing.bgp.BgpSessionInfo.setBgpVersion (int bgpVersion)
Sets the BGP session BGP version: local or remote.
Parameters
bgpVersion the BGP session BGP version to set
Definition at line 95 of file BgpSessionInfo.java.
References org.onosproject.routing.bgp.BgpSessionInfo.bgpVersion().
void org.onosproject.routing.bgp.BgpSessionInfo.setHoldtime (long holdtime)
Sets the BGP session holdtime: local or remote.
Parameters
holdtime the BGP session holdtime to set
Definition at line 149 of file BgpSessionInfo.java.
References org.onosproject.routing.bgp.BgpSessionInfo.holdtime().
void org.onosproject.routing.bgp.BgpSessionInfo.setIp4Address (Ip4Address ip4Address)
Sets the BGP session IPv4 address: local or remote.
Parameters
ip4Address the BGP session IPv4 address to set
Definition at line 77 of file BgpSessionInfo.java.
References org.onosproject.routing.bgp.BgpSessionInfo.ip4Address().
void org.onosproject.routing.bgp.BgpSessionInfo.setIpv4Multicast ()
Sets the BGP session AFI/SAFI configuration for IPv4 multicast: local or remote.
Definition at line 214 of file BgpSessionInfo.java.
void org.onosproject.routing.bgp.BgpSessionInfo.setIpv4Unicast ()
Sets the BGP session AFI/SAFI configuration for IPv4 unicast: local or remote.
Definition at line 195 of file BgpSessionInfo.java.
void org.onosproject.routing.bgp.BgpSessionInfo.setIpv6Multicast ()
Sets the BGP session AFI/SAFI configuration for IPv6 multicast: local or remote.
Definition at line 252 of file BgpSessionInfo.java.
The documentation for this class was generated from the following file:
apps/routing/src/main/java/org/onosproject/routing/bgp/BgpSessionInfo.java