onos: org.onosproject.vtnrsc.event.VtnRscEventFeedback Class Reference
org.onosproject.vtnrsc.event.VtnRscEventFeedback Class Reference
Representation of a VtnRsc event feedback.
Public Member Functions
VtnRscEventFeedback (FloatingIp floatingIp)
Creates VtnRscEventFeedback object.
VtnRscEventFeedback (Router router)
Creates VtnRscEventFeedback object.
VtnRscEventFeedback (RouterInterface routerInterface)
Creates VtnRscEventFeedback object.
FloatingIp floatingIp ()
Returns floating IP.
Router router ()
Returns router.
RouterInterface routerInterface ()
Returns router interface.
int hashCode ()
boolean equals (Object obj)
String toString ()
Detailed Description
Representation of a VtnRsc event feedback.
Definition at line 30 of file VtnRscEventFeedback.java.
Constructor & Destructor Documentation
org.onosproject.vtnrsc.event.VtnRscEventFeedback.VtnRscEventFeedback (FloatingIp floatingIp)
Creates VtnRscEventFeedback object.
Parameters
floatingIp the floating Ip
Definition at line 40 of file VtnRscEventFeedback.java.
Referenced by org.onosproject.vtnrsc.event.VtnRscEventFeedback.equals().
org.onosproject.vtnrsc.event.VtnRscEventFeedback.VtnRscEventFeedback (Router router)
Creates VtnRscEventFeedback object.
Parameters
router the router
Definition at line 51 of file VtnRscEventFeedback.java.
org.onosproject.vtnrsc.event.VtnRscEventFeedback.VtnRscEventFeedback (RouterInterface routerInterface)
Creates VtnRscEventFeedback object.
Parameters
routerInterface the router interface
Definition at line 62 of file VtnRscEventFeedback.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.event.VtnRscEventFeedback.equals (Object obj)
Definition at line 102 of file VtnRscEventFeedback.java.
References org.onosproject.vtnrsc.event.VtnRscEventFeedback.VtnRscEventFeedback().
FloatingIp org.onosproject.vtnrsc.event.VtnRscEventFeedback.floatingIp ()
Returns floating IP.
Returns
floaingtIp the floating IP
Definition at line 74 of file VtnRscEventFeedback.java.
int org.onosproject.vtnrsc.event.VtnRscEventFeedback.hashCode ()
Definition at line 97 of file VtnRscEventFeedback.java.
References org.onosproject.vtnrsc.event.VtnRscEventFeedback.router(), and org.onosproject.vtnrsc.event.VtnRscEventFeedback.routerInterface().
Router org.onosproject.vtnrsc.event.VtnRscEventFeedback.router ()
Returns router.
Returns
router the router
Definition at line 83 of file VtnRscEventFeedback.java.
Referenced by org.onosproject.vtnrsc.event.VtnRscEventFeedback.hashCode(), and org.onosproject.vtnrsc.event.VtnRscEventFeedback.toString().
RouterInterface org.onosproject.vtnrsc.event.VtnRscEventFeedback.routerInterface ()
Returns router interface.
Returns
routerInterface the router interface
Definition at line 92 of file VtnRscEventFeedback.java.
Referenced by org.onosproject.vtnrsc.event.VtnRscEventFeedback.hashCode(), and org.onosproject.vtnrsc.event.VtnRscEventFeedback.toString().
String org.onosproject.vtnrsc.event.VtnRscEventFeedback.toString ()
Definition at line 116 of file VtnRscEventFeedback.java.
References org.onosproject.vtnrsc.event.VtnRscEventFeedback.router(), and org.onosproject.vtnrsc.event.VtnRscEventFeedback.routerInterface().
The documentation for this class was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/event/VtnRscEventFeedback.java