onos: org.onosproject.routing.config.BgpSpeaker Class Reference
org.onosproject.routing.config.BgpSpeaker Class Reference
Represents a BGP daemon in SDN network.
Public Member Functions
BgpSpeaker (@JsonProperty("name") String name,@JsonProperty("attachmentDpid") String attachmentDpid,@JsonProperty("attachmentPort") long attachmentPort,@JsonProperty("macAddress") String macAddress)
Class constructor used by the JSON library to create an object.
void setInterfaceAddresses (List< InterfaceAddress > interfaceAddresses)
Sets the addresses we configured for the BGP speaker on all virtual Interfaces.
String name ()
Gets the BGP speaker name.
ConnectPoint connectPoint ()
Gets the connect point where the BGP speaker is attached.
MacAddress macAddress ()
Gets the MAC address of the BGP speaker.
List< InterfaceAddress > interfaceAddresses ()
Gets all IP addresses configured on all Interfaces of the BGP speaker.
boolean equals (Object other)
int hashCode ()
String toString ()
Detailed Description
Represents a BGP daemon in SDN network.
Each BGP speaker has a attachment point, which includes a switch DPID and a switch port. Each BGP speaker has one MAC address and several IP addresses, which are used to peer with BGP peers outside the SDN network. For each peer outside the SDN network, we configure a different IP address to BGP speaker inside the SDN network.
Each BGP speaker has a name, which is a unique identifying String that is used to reference this speaker in the configuration.
Definition at line 44 of file BgpSpeaker.java.
Constructor & Destructor Documentation
org.onosproject.routing.config.BgpSpeaker.BgpSpeaker (@JsonProperty("name") String name, @JsonProperty("attachmentDpid") String attachmentDpid, @JsonProperty("attachmentPort") long attachmentPort, @JsonProperty("macAddress") String macAddress)
Class constructor used by the JSON library to create an object.
Parameters
name the name of the BGP speaker inside SDN network
attachmentDpid the DPID where the BGP speaker is attached to
attachmentPort the port where the BGP speaker is attached to
macAddress the MAC address of the BGP speaker
Definition at line 59 of file BgpSpeaker.java.
References org.onosproject.net.DeviceId.deviceId(), org.onosproject.net.NetTools.dpidToUri(), org.onosproject.routing.config.BgpSpeaker.macAddress(), org.onosproject.routing.config.BgpSpeaker.name(), and org.onosproject.net.PortNumber.portNumber().
Referenced by org.onosproject.routing.config.BgpSpeaker.equals().
Member Function Documentation
ConnectPoint org.onosproject.routing.config.BgpSpeaker.connectPoint ()
Gets the connect point where the BGP speaker is attached.
Returns
the connect point
Definition at line 98 of file BgpSpeaker.java.
Referenced by org.onosproject.routing.config.BgpSpeaker.equals(), org.onosproject.routing.config.BgpSpeaker.hashCode(), and org.onosproject.routing.config.BgpSpeaker.toString().
boolean org.onosproject.routing.config.BgpSpeaker.equals (Object other)
Definition at line 123 of file BgpSpeaker.java.
References org.onosproject.routing.config.BgpSpeaker.BgpSpeaker(), org.onosproject.routing.config.BgpSpeaker.connectPoint(), org.onosproject.net.ConnectPoint.equals(), org.onosproject.routing.config.BgpSpeaker.interfaceAddresses(), and create-flow.name.
int org.onosproject.routing.config.BgpSpeaker.hashCode ()
Definition at line 138 of file BgpSpeaker.java.
References org.onosproject.routing.config.BgpSpeaker.connectPoint(), org.onosproject.routing.config.BgpSpeaker.interfaceAddresses(), org.onosproject.routing.config.BgpSpeaker.macAddress(), and org.onosproject.routing.config.BgpSpeaker.name().
List<InterfaceAddress> org.onosproject.routing.config.BgpSpeaker.interfaceAddresses ()
Gets all IP addresses configured on all Interfaces of the BGP speaker.
Returns
a list of IP addresses of the BGP speaker configured on all virtual interfaces
Definition at line 118 of file BgpSpeaker.java.
Referenced by org.onosproject.routing.config.BgpSpeaker.equals(), org.onosproject.routing.config.BgpSpeaker.hashCode(), org.onosproject.routing.config.BgpSpeaker.setInterfaceAddresses(), and org.onosproject.routing.config.BgpSpeaker.toString().
MacAddress org.onosproject.routing.config.BgpSpeaker.macAddress ()
Gets the MAC address of the BGP speaker.
Returns
the MAC address
Definition at line 107 of file BgpSpeaker.java.
Referenced by org.onosproject.routing.config.BgpSpeaker.BgpSpeaker(), org.onosproject.routing.config.BgpSpeaker.hashCode(), and org.onosproject.routing.config.BgpSpeaker.toString().
String org.onosproject.routing.config.BgpSpeaker.name ()
Gets the BGP speaker name.
Returns
the BGP speaker name
Definition at line 89 of file BgpSpeaker.java.
Referenced by org.onosproject.routing.config.BgpSpeaker.BgpSpeaker(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.routing.config.BgpSpeaker.hashCode(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
void org.onosproject.routing.config.BgpSpeaker.setInterfaceAddresses (List< InterfaceAddress > interfaceAddresses)
Sets the addresses we configured for the BGP speaker on all virtual Interfaces.
Parameters
interfaceAddresses a list of IP addresses of the BGP speaker configured on all virtual interfaces
Definition at line 79 of file BgpSpeaker.java.
References org.onosproject.routing.config.BgpSpeaker.interfaceAddresses().
String org.onosproject.routing.config.BgpSpeaker.toString ()
Definition at line 145 of file BgpSpeaker.java.
References org.onosproject.routing.config.BgpSpeaker.connectPoint(), org.onosproject.routing.config.BgpSpeaker.interfaceAddresses(), and org.onosproject.routing.config.BgpSpeaker.macAddress().
The documentation for this class was generated from the following file:
apps/routing-api/src/main/java/org/onosproject/routing/config/BgpSpeaker.java