onos: org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn Enum Reference
org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn Enum Reference
Mirror table column name.
Public Member Functions
String columnName ()
Returns the table column name for MirrorColumn.
Public Attributes
NAME =("name")
SELECTSRCPORT =("select_src_port")
SELECTDSTPORT =("select_dst_port")
SELECTVLAN =("select_vlan")
OUTPUTPORT =("output_port")
EXTERNALIDS =("external_ids")
OUTPUTVLAN =("output_vlan")
STATISTICS =("statistics")
SELECTALL =("select_all")
Detailed Description
Mirror table column name.
Definition at line 35 of file Mirror.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn.columnName ()
Returns the table column name for MirrorColumn.
Returns
the table column name
Definition at line 50 of file Mirror.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn.EXTERNALIDS =("external_ids")
Definition at line 37 of file Mirror.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.Mirror.setExternalIds().
org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn.NAME =("name")
Definition at line 36 of file Mirror.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.getName(), org.onosproject.ovsdb.rfc.table.Mirror.getNameColumn(), and org.onosproject.ovsdb.rfc.table.Mirror.setName().
org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn.OUTPUTPORT =("output_port")
Definition at line 37 of file Mirror.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.getOutputPortColumn(), and org.onosproject.ovsdb.rfc.table.Mirror.setOutputPort().
org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn.OUTPUTVLAN =("output_vlan")
Definition at line 38 of file Mirror.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.getOutputVlanColumn(), and org.onosproject.ovsdb.rfc.table.Mirror.setOutputVlan().
org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn.SELECTALL =("select_all")
Definition at line 38 of file Mirror.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.getSelectAllColumn(), and org.onosproject.ovsdb.rfc.table.Mirror.setSelectAll().
org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn.SELECTDSTPORT =("select_dst_port")
Definition at line 36 of file Mirror.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.getSelectDstPortColumn(), and org.onosproject.ovsdb.rfc.table.Mirror.setSelectDstPort().
org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn.SELECTSRCPORT =("select_src_port")
Definition at line 36 of file Mirror.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.getSelectSrcPortColumn(), and org.onosproject.ovsdb.rfc.table.Mirror.setSelectSrcPort().
org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn.SELECTVLAN =("select_vlan")
Definition at line 37 of file Mirror.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.getSelectVlanColumn(), and org.onosproject.ovsdb.rfc.table.Mirror.setSelectVlan().
org.onosproject.ovsdb.rfc.table.Mirror.MirrorColumn.STATISTICS =("statistics")
Definition at line 38 of file Mirror.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.getStatisticsColumn(), and org.onosproject.ovsdb.rfc.table.Mirror.setStatistics().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/Mirror.java