onos: org.onosproject.openflow.controller.PortDescPropertyType Enum Reference
org.onosproject.openflow.controller.PortDescPropertyType Enum Reference
Port description property types (OFPPDPT enums) in OF 1.3 <.
Public Member Functions
PortDescPropertyType (int v)
int valueOf ()
Public Attributes
ETHERNET =(0)
OPTICAL =(1)
OPTICAL_TRANSPORT =(2)
PIPELINE_INPUT =(2)
PIPELINE_OUTPUT =(3)
RECIRCULATE =(4)
EXPERIMENTER =(0xffff)
Detailed Description
Port description property types (OFPPDPT enums) in OF 1.3 <.
Definition at line 21 of file PortDescPropertyType.java.
Constructor & Destructor Documentation
org.onosproject.openflow.controller.PortDescPropertyType.PortDescPropertyType (int v)
Definition at line 32 of file PortDescPropertyType.java.
Member Function Documentation
int org.onosproject.openflow.controller.PortDescPropertyType.valueOf ()
Definition at line 36 of file PortDescPropertyType.java.
Member Data Documentation
org.onosproject.openflow.controller.PortDescPropertyType.ETHERNET =(0)
Definition at line 22 of file PortDescPropertyType.java.
org.onosproject.openflow.controller.PortDescPropertyType.EXPERIMENTER =(0xffff)
Definition at line 28 of file PortDescPropertyType.java.
org.onosproject.openflow.controller.PortDescPropertyType.OPTICAL =(1)
Definition at line 23 of file PortDescPropertyType.java.
org.onosproject.openflow.controller.PortDescPropertyType.OPTICAL_TRANSPORT =(2)
Definition at line 24 of file PortDescPropertyType.java.
Referenced by org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13.getPortsOf(), org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker.getPortTypes(), org.onosproject.driver.handshaker.OFOpticalSwitch13.getPortTypes(), and org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13.getPortTypes().
org.onosproject.openflow.controller.PortDescPropertyType.PIPELINE_INPUT =(2)
Definition at line 25 of file PortDescPropertyType.java.
org.onosproject.openflow.controller.PortDescPropertyType.PIPELINE_OUTPUT =(3)
Definition at line 26 of file PortDescPropertyType.java.
org.onosproject.openflow.controller.PortDescPropertyType.RECIRCULATE =(4)
Definition at line 27 of file PortDescPropertyType.java.
The documentation for this enum was generated from the following file:
protocols/openflow/api/src/main/java/org/onosproject/openflow/controller/PortDescPropertyType.java