onos: org.onosproject.ui.UiView.Category Enum Reference
org.onosproject.ui.UiView.Category Enum Reference
Designates navigation menu category.
Public Member Functions
Category (String label)
String label ()
Returns display label for the category.
Public Attributes
PLATFORM =("Platform")
Represents platform related views.
NETWORK =("Network")
Represents network-control related views.
OTHER =("Other")
Represents miscellaneous views.
HIDDEN =("(hidden)")
Represents views that do not show in the navigation menu.
Detailed Description
Designates navigation menu category.
Definition at line 30 of file UiView.java.
Constructor & Destructor Documentation
org.onosproject.ui.UiView.Category.Category (String label)
Definition at line 55 of file UiView.java.
References org.onosproject.ui.UiView.label().
Member Function Documentation
String org.onosproject.ui.UiView.Category.label ()
Returns display label for the category.
Returns
display label
Definition at line 64 of file UiView.java.
References org.onosproject.ui.UiView.label().
Member Data Documentation
org.onosproject.ui.UiView.Category.HIDDEN =("(hidden)")
Represents views that do not show in the navigation menu.
This category should not be specified directly; rather, use the UiViewHidden constructor instead of UiView.
Definition at line 51 of file UiView.java.
Referenced by org.onosproject.ui.UiViewHidden.UiViewHidden().
org.onosproject.ui.UiView.Category.NETWORK =("Network")
Represents network-control related views.
Definition at line 39 of file UiView.java.
org.onosproject.ui.UiView.Category.OTHER =("Other")
Represents miscellaneous views.
Definition at line 44 of file UiView.java.
org.onosproject.ui.UiView.Category.PLATFORM =("Platform")
Represents platform related views.
Definition at line 34 of file UiView.java.
The documentation for this enum was generated from the following file:
core/api/src/main/java/org/onosproject/ui/UiView.java