onos: org.onosproject.ovsdb.rfc.table.Queue.QueueColumn Enum Reference
org.onosproject.ovsdb.rfc.table.Queue.QueueColumn Enum Reference
Queue table column name.
Public Member Functions
String columnName ()
Returns the table column name for QueueColumn.
Public Attributes
DSCP =("dscp")
OTHERCONFIG =("other_config")
EXTERNALIDS =("external_ids")
Detailed Description
Queue table column name.
Definition at line 34 of file Queue.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.Queue.QueueColumn.columnName ()
Returns the table column name for QueueColumn.
Returns
the table column name
Definition at line 47 of file Queue.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.Queue.QueueColumn.DSCP =("dscp")
Definition at line 35 of file Queue.java.
Referenced by org.onosproject.ovsdb.rfc.table.Queue.getDscpColumn(), and org.onosproject.ovsdb.rfc.table.Queue.setDscp().
org.onosproject.ovsdb.rfc.table.Queue.QueueColumn.EXTERNALIDS =("external_ids")
Definition at line 35 of file Queue.java.
Referenced by org.onosproject.ovsdb.rfc.table.Queue.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.Queue.setExternalIds().
org.onosproject.ovsdb.rfc.table.Queue.QueueColumn.OTHERCONFIG =("other_config")
Definition at line 35 of file Queue.java.
Referenced by org.onosproject.ovsdb.rfc.table.Queue.getOtherConfigColumn(), and org.onosproject.ovsdb.rfc.table.Queue.setOtherConfig().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/Queue.java