onos: org.onosproject.ovsdb.rfc.table.Ipfix.IpfixColumn Enum Reference
org.onosproject.ovsdb.rfc.table.Ipfix.IpfixColumn Enum Reference
Ipfix table column name.
Public Member Functions
String columnName ()
Returns the table column name for IpfixColumn.
Public Attributes
TARGETS =("targets")
SAMPLING =("sampling")
OBSDOMAINID =("obs_domain_id")
OBSPOINTID =("obs_point_id")
CACHEACTIVETIMEOUT =("cache_active_timeout")
EXTERNALIDS =("external_ids")
CACHEMAXFLOWS =("cache_max_flows")
Detailed Description
Ipfix table column name.
Definition at line 34 of file Ipfix.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.Ipfix.IpfixColumn.columnName ()
Returns the table column name for IpfixColumn.
Returns
the table column name
Definition at line 49 of file Ipfix.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.Ipfix.IpfixColumn.CACHEACTIVETIMEOUT =("cache_active_timeout")
Definition at line 36 of file Ipfix.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ipfix.getCacheActiveTimeoutColumn(), and org.onosproject.ovsdb.rfc.table.Ipfix.setCacheActiveTimeout().
org.onosproject.ovsdb.rfc.table.Ipfix.IpfixColumn.CACHEMAXFLOWS =("cache_max_flows")
Definition at line 37 of file Ipfix.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ipfix.getCacheMaxFlowsColumn(), and org.onosproject.ovsdb.rfc.table.Ipfix.setCacheMaxFlows().
org.onosproject.ovsdb.rfc.table.Ipfix.IpfixColumn.EXTERNALIDS =("external_ids")
Definition at line 36 of file Ipfix.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ipfix.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.Ipfix.setExternalIds().
org.onosproject.ovsdb.rfc.table.Ipfix.IpfixColumn.OBSDOMAINID =("obs_domain_id")
Definition at line 35 of file Ipfix.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ipfix.getObsDomainIdColumn(), and org.onosproject.ovsdb.rfc.table.Ipfix.setObsDomainId().
org.onosproject.ovsdb.rfc.table.Ipfix.IpfixColumn.OBSPOINTID =("obs_point_id")
Definition at line 35 of file Ipfix.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ipfix.getObsPointIdColumn(), and org.onosproject.ovsdb.rfc.table.Ipfix.setObsPointId().
org.onosproject.ovsdb.rfc.table.Ipfix.IpfixColumn.SAMPLING =("sampling")
Definition at line 35 of file Ipfix.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ipfix.getSamplingColumn(), and org.onosproject.ovsdb.rfc.table.Ipfix.setSampling().
org.onosproject.ovsdb.rfc.table.Ipfix.IpfixColumn.TARGETS =("targets")
Definition at line 35 of file Ipfix.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ipfix.getTargetsColumn(), and org.onosproject.ovsdb.rfc.table.Ipfix.setTargets().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/Ipfix.java