onos: org.onosproject.ovsdb.rfc.table.OvsdbTable Enum Reference
org.onosproject.ovsdb.rfc.table.OvsdbTable Enum Reference
Ovsdb table name.
Public Member Functions
String tableName ()
Returns the table name for OvsdbTable.
Public Attributes
INTERFACE =("Interface")
BRIDGE =("Bridge")
CONTROLLER =("Controller")
PORT =("Port")
OPENVSWITCH =("Open_vSwitch")
FLWTABLE =("Flow_Table")
QOS =("Qos")
QUEUE =("Queue")
MIRROR =("Mirror")
MANAGER =("Manager")
NETFLOW =("NetFlow")
SSL =("SSL")
SFLOW =("sFlow")
IPFIX =("IPFIX")
FLOWSAMPLECOLLECTORSET =("Flow_Sample_Collector_Set")
Detailed Description
Ovsdb table name.
Refer to RFC7047's Section 9.2.
Definition at line 21 of file OvsdbTable.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.OvsdbTable.tableName ()
Returns the table name for OvsdbTable.
Returns
the table name
Definition at line 38 of file OvsdbTable.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.OvsdbTable.BRIDGE =("Bridge")
Definition at line 22 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.Bridge(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getBridgeUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPortUuid(), and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setControllersWithUUID().
org.onosproject.ovsdb.rfc.table.OvsdbTable.CONTROLLER =("Controller")
Definition at line 22 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.Controller(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getControllerUuid(), and org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.setControllersWithUUID().
org.onosproject.ovsdb.rfc.table.OvsdbTable.FLOWSAMPLECOLLECTORSET =("Flow_Sample_Collector_Set")
Definition at line 26 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.FlowSampleCollectorSet().
org.onosproject.ovsdb.rfc.table.OvsdbTable.FLWTABLE =("Flow_Table")
Definition at line 23 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowTable.FlowTable().
org.onosproject.ovsdb.rfc.table.OvsdbTable.INTERFACE =("Interface")
Definition at line 22 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createTunnel(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getInterfaceUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getLocalPorts(), and org.onosproject.ovsdb.rfc.table.Interface.Interface().
org.onosproject.ovsdb.rfc.table.OvsdbTable.IPFIX =("IPFIX")
Definition at line 25 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ipfix.Ipfix().
org.onosproject.ovsdb.rfc.table.OvsdbTable.MANAGER =("Manager")
Definition at line 24 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.Manager.Manager().
org.onosproject.ovsdb.rfc.table.OvsdbTable.MIRROR =("Mirror")
Definition at line 24 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.Mirror().
org.onosproject.ovsdb.rfc.table.OvsdbTable.NETFLOW =("NetFlow")
Definition at line 25 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.Netflow.Netflow().
org.onosproject.ovsdb.rfc.table.OvsdbTable.OPENVSWITCH =("Open_vSwitch")
Definition at line 23 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitch().
org.onosproject.ovsdb.rfc.table.OvsdbTable.PORT =("Port")
Definition at line 23 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createBridge(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createPort(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.createTunnel(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getInterfaceUuid(), org.onosproject.ovsdb.controller.driver.DefaultOvsdbClient.getPortUuid(), and org.onosproject.ovsdb.rfc.table.Port.Port().
org.onosproject.ovsdb.rfc.table.OvsdbTable.QOS =("Qos")
Definition at line 24 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.Qos.Qos().
org.onosproject.ovsdb.rfc.table.OvsdbTable.QUEUE =("Queue")
Definition at line 24 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.Queue.Queue().
org.onosproject.ovsdb.rfc.table.OvsdbTable.SFLOW =("sFlow")
Definition at line 25 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.Sflow.Sflow().
org.onosproject.ovsdb.rfc.table.OvsdbTable.SSL =("SSL")
Definition at line 25 of file OvsdbTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ssl.Ssl().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/OvsdbTable.java