onos: org.onosproject.net.packet.PacketPriority Enum Reference
org.onosproject.net.packet.PacketPriority Enum Reference
Priorities available to applications for requests for packets from the data plane.
Public Member Functions
PacketPriority (int priorityValue)
int priorityValue ()
Returns the integer value of the priority level.
String toString ()
Public Attributes
CONTROL =(40000)
High priority for control traffic.
REACTIVE =(5)
Low priority for reactive applications.
Detailed Description
Priorities available to applications for requests for packets from the data plane.
Definition at line 22 of file PacketPriority.java.
Constructor & Destructor Documentation
org.onosproject.net.packet.PacketPriority.PacketPriority (int priorityValue)
Definition at line 37 of file PacketPriority.java.
Member Function Documentation
int org.onosproject.net.packet.PacketPriority.priorityValue ()
Returns the integer value of the priority level.
Returns
priority value
Definition at line 46 of file PacketPriority.java.
String org.onosproject.net.packet.PacketPriority.toString ()
Definition at line 50 of file PacketPriority.java.
Member Data Documentation
org.onosproject.net.packet.PacketPriority.CONTROL =(40000)
High priority for control traffic.
This will result in all traffic matching the selector being sent to the controller.
Definition at line 27 of file PacketPriority.java.
Referenced by org.onosproject.driver.pipeline.OltPipeline.init(), and org.onosproject.net.packet.DefaultPacketRequestTest.testConstruction().
org.onosproject.net.packet.PacketPriority.REACTIVE =(5)
Low priority for reactive applications.
Packets are only sent to the controller if they fail to match any of the rules installed in the switch.
Definition at line 33 of file PacketPriority.java.
Referenced by org.onosproject.igmp.impl.IGMPComponent.activate(), org.onosproject.mfwd.impl.McastForwarding.activate(), and org.onosproject.pim.impl.PIMPacketHandler.initialize().
The documentation for this enum was generated from the following file:
core/api/src/main/java/org/onosproject/net/packet/PacketPriority.java