onos: org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn Enum Reference
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn Enum Reference
OpenVSwitch table column name.
Public Member Functions
String columnName ()
Returns the table column name for OpenVSwitchColumn.
Public Attributes
BRIDGES =("bridges")
MANAGERS =("managers")
MANAGEROPTIONS =("manager_options")
SSL =("ssl")
OTHERCONFIG =("other_config")
EXTERNALIDS =("external_ids")
NEXTCFG =("next_cfg")
CURCFG =("cur_cfg")
CAPABILITIES =("capabilities")
STATISTICS =("statistics")
OVSVERSION =("ovs_version")
DBVERSION =("db_version")
SYSTEMTYPE =("system_type")
SYSTEMVERSION =("system_version")
Detailed Description
OpenVSwitch table column name.
Definition at line 36 of file OpenVSwitch.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.columnName ()
Returns the table column name for OpenVSwitchColumn.
Returns
the table column name
Definition at line 55 of file OpenVSwitch.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.BRIDGES =("bridges")
Definition at line 37 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getBridgesColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setBridges().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.CAPABILITIES =("capabilities")
Definition at line 40 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getCapabilitiesColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setCapabilities().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.CURCFG =("cur_cfg")
Definition at line 40 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getCurrentConfigColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setCurrentConfig().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.DBVERSION =("db_version")
Definition at line 42 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getDbVersionColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setDbVersion().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.EXTERNALIDS =("external_ids")
Definition at line 39 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setExternalIds().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.MANAGEROPTIONS =("manager_options")
Definition at line 38 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getManagerOptionsColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setManagerOptions().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.MANAGERS =("managers")
Definition at line 37 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getManagersColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setManagers().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.NEXTCFG =("next_cfg")
Definition at line 40 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getNextConfigColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setNextConfig().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.OTHERCONFIG =("other_config")
Definition at line 39 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getOtherConfigColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setOtherConfig().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.OVSVERSION =("ovs_version")
Definition at line 41 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getOvsVersionColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setOvsVersion().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.SSL =("ssl")
Definition at line 38 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getSslColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setSsl().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.STATISTICS =("statistics")
Definition at line 41 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getStatisticsColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setStatistics().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.SYSTEMTYPE =("system_type")
Definition at line 42 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getSystemTypeColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setSystemType().
org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitchColumn.SYSTEMVERSION =("system_version")
Definition at line 43 of file OpenVSwitch.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getSystemVersionColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setSystemVersion().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/OpenVSwitch.java