onos: org.onosproject.ui.topo.NodeBadge.Status Enum Reference
org.onosproject.ui.topo.NodeBadge.Status Enum Reference
Designates the badge status.
Public Member Functions
Status (String code)
String toString ()
String code ()
Public Attributes
INFO =("i")
WARN =("w")
ERROR =("e")
Detailed Description
Designates the badge status.
Definition at line 27 of file NodeBadge.java.
Constructor & Destructor Documentation
org.onosproject.ui.topo.NodeBadge.Status.Status (String code)
Definition at line 34 of file NodeBadge.java.
Member Function Documentation
String org.onosproject.ui.topo.NodeBadge.Status.code ()
Definition at line 44 of file NodeBadge.java.
String org.onosproject.ui.topo.NodeBadge.Status.toString ()
Definition at line 39 of file NodeBadge.java.
Referenced by org.onosproject.ui.topo.NodeBadge.number().
Member Data Documentation
org.onosproject.ui.topo.NodeBadge.Status.ERROR =("e")
Definition at line 30 of file NodeBadge.java.
Referenced by org.onosproject.ui.topo.NodeBadgeTest.badgeTypes(), org.onosproject.ui.topo.NodeBadgeTest.numberError(), and org.onosproject.ui.topo.NodeBadgeTest.numberErrorMsg().
org.onosproject.ui.topo.NodeBadge.Status.INFO =("i")
Definition at line 28 of file NodeBadge.java.
Referenced by org.onosproject.ui.topo.NodeBadgeTest.badgeTypes(), org.onosproject.ui.topo.NodeBadge.glyph(), org.onosproject.ui.topo.NodeBadgeTest.glyphOnly(), org.onosproject.ui.topo.NodeBadge.number(), org.onosproject.ui.topo.NodeBadgeTest.numberOnly(), org.onosproject.ui.topo.NodeBadge.text(), org.onosproject.ui.topo.NodeBadgeTest.textInfo(), org.onosproject.ui.topo.NodeBadgeTest.textInfoMsg(), and org.onosproject.ui.topo.NodeBadgeTest.textOnly().
org.onosproject.ui.topo.NodeBadge.Status.WARN =("w")
Definition at line 29 of file NodeBadge.java.
Referenced by org.onosproject.ui.topo.TopoJsonTest.badgedDevice(), org.onosproject.ui.topo.NodeBadgeTest.badgeTypes(), org.onosproject.ui.topo.NodeBadgeTest.glyphWarn(), and org.onosproject.ui.topo.NodeBadgeTest.glyphWarnMsg().
The documentation for this enum was generated from the following file:
core/api/src/main/java/org/onosproject/ui/topo/NodeBadge.java