onos: org.onosproject.grpc.Port.PortType Enum Reference
org.onosproject.grpc.Port.PortType Enum Reference
Protobuf enum.
Public Member Functions
final int getNumber ()
final
com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor ()
final
com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType ()
Static Public Member Functions
static PortType valueOf (int value)
static
com.google.protobuf.Internal.EnumLiteMap
< PortType > internalGetValueMap ()
static final
com.google.protobuf.Descriptors.EnumDescriptor getDescriptor ()
static PortType valueOf (com.google.protobuf.Descriptors.EnumValueDescriptor desc)
Public Attributes
COPPER =(0, 0)
COPPER = 0;
FIBER =(1, 1)
FIBER = 1;
PACKET =(2, 2)
PACKET = 2;
ODUCLT =(3, 3)
ODUCLT = 3;
OCH =(4, 4)
OCH = 4;
OMS =(5, 5)
OMS = 5;
VIRTUAL =(6, 6)
VIRTUAL = 6;
UNRECOGNIZED =(-1, -1)
Static Public Attributes
staticfinal int COPPER_VALUE = 0
COPPER = 0;
staticfinal int FIBER_VALUE = 1
FIBER = 1;
staticfinal int PACKET_VALUE = 2
PACKET = 2;
staticfinal int ODUCLT_VALUE = 3
ODUCLT = 3;
staticfinal int OCH_VALUE = 4
OCH = 4;
staticfinal int OMS_VALUE = 5
OMS = 5;
staticfinal int VIRTUAL_VALUE = 6
VIRTUAL = 6;
Detailed Description
Protobuf enum.
Port.PortType
Definition at line 14 of file Port.java.
Member Function Documentation
static final com.google.protobuf.Descriptors.EnumDescriptor org.onosproject.grpc.Port.PortType.getDescriptor () static
Definition at line 179 of file Port.java.
final com.google.protobuf.Descriptors.EnumDescriptor org.onosproject.grpc.Port.PortType.getDescriptorForType ()
Definition at line 175 of file Port.java.
References org.onosproject.grpc.Port.getDescriptor().
final int org.onosproject.grpc.Port.PortType.getNumber ()
Definition at line 137 of file Port.java.
final com.google.protobuf.Descriptors.EnumValueDescriptor org.onosproject.grpc.Port.PortType.getValueDescriptor ()
Definition at line 171 of file Port.java.
References org.onosproject.grpc.Port.getDescriptor().
static com.google.protobuf.Internal.EnumLiteMap<PortType> org.onosproject.grpc.Port.PortType.internalGetValueMap () static
Definition at line 159 of file Port.java.
static PortType org.onosproject.grpc.Port.PortType.valueOf (int value) static
Definition at line 145 of file Port.java.
static PortType org.onosproject.grpc.Port.PortType.valueOf (com.google.protobuf.Descriptors.EnumValueDescriptor desc) static
Definition at line 185 of file Port.java.
References org.onosproject.grpc.Port.getDescriptor().
Member Data Documentation
org.onosproject.grpc.Port.PortType.COPPER =(0, 0)
COPPER = 0;
Signifies copper-based connectivity.
Definition at line 23 of file Port.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Port.PortType.COPPER_VALUE = 0 static
COPPER = 0;
Signifies copper-based connectivity.
Definition at line 84 of file Port.java.
org.onosproject.grpc.Port.PortType.FIBER =(1, 1)
FIBER = 1;
Signifies optical fiber-based connectivity.
Definition at line 31 of file Port.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Port.PortType.FIBER_VALUE = 1 static
FIBER = 1;
Signifies optical fiber-based connectivity.
Definition at line 92 of file Port.java.
org.onosproject.grpc.Port.PortType.OCH =(4, 4)
OCH = 4;
Signifies optical fiber-based Line-side port (called L-port).
Definition at line 56 of file Port.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Port.PortType.OCH_VALUE = 4 static
OCH = 4;
Signifies optical fiber-based Line-side port (called L-port).
Definition at line 117 of file Port.java.
org.onosproject.grpc.Port.PortType.ODUCLT =(3, 3)
ODUCLT = 3;
 Signifies optical fiber-based optical tributary port (called T-port).
The signal from the client side will be formed into a ITU G.709 (OTN) frame.
Definition at line 48 of file Port.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Port.PortType.ODUCLT_VALUE = 3 static
ODUCLT = 3;
 Signifies optical fiber-based optical tributary port (called T-port).
The signal from the client side will be formed into a ITU G.709 (OTN) frame.
Definition at line 109 of file Port.java.
org.onosproject.grpc.Port.PortType.OMS =(5, 5)
OMS = 5;
 Signifies optical fiber-based WDM port (called W-port).
Optical Multiplexing Section (See ITU G.709).
Definition at line 65 of file Port.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Port.PortType.OMS_VALUE = 5 static
OMS = 5;
 Signifies optical fiber-based WDM port (called W-port).
Optical Multiplexing Section (See ITU G.709).
Definition at line 126 of file Port.java.
org.onosproject.grpc.Port.PortType.PACKET =(2, 2)
PACKET = 2;
Signifies optical fiber-based packet port.
Definition at line 39 of file Port.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Port.PortType.PACKET_VALUE = 2 static
PACKET = 2;
Signifies optical fiber-based packet port.
Definition at line 100 of file Port.java.
org.onosproject.grpc.Port.PortType.UNRECOGNIZED =(-1, -1)
Definition at line 74 of file Port.java.
org.onosproject.grpc.Port.PortType.VIRTUAL =(6, 6)
VIRTUAL = 6;
Signifies virtual port.
Definition at line 73 of file Port.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Port.PortType.VIRTUAL_VALUE = 6 static
VIRTUAL = 6;
Signifies virtual port.
Definition at line 134 of file Port.java.
The documentation for this enum was generated from the following file:
incubator/rpc-grpc/target/generated-sources/protobuf/java/org/onosproject/grpc/Port.java