onos: org.onosproject.grpc.Device.DeviceType Enum Reference
org.onosproject.grpc.Device.DeviceType Enum Reference
Protobuf enum.
Public Member Functions
final int getNumber ()
final
com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor ()
final
com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType ()
Static Public Member Functions
static DeviceType valueOf (int value)
static
com.google.protobuf.Internal.EnumLiteMap
< DeviceType > internalGetValueMap ()
static final
com.google.protobuf.Descriptors.EnumDescriptor getDescriptor ()
static DeviceType valueOf (com.google.protobuf.Descriptors.EnumValueDescriptor desc)
Public Attributes
OTHER =(0, 0)
OTHER = 0;
SWITCH =(1, 1)
SWITCH = 1;
ROUTER =(2, 2)
ROUTER = 2;
ROADM =(3, 3)
ROADM = 3;
OTN =(4, 4)
OTN = 4;
ROADM_OTN =(5, 5)
ROADM_OTN = 5;
FIREWALL =(6, 6)
FIREWALL = 6;
BALANCER =(7, 7)
BALANCER = 7;
IPS =(8, 8)
IPS = 8;
IDS =(9, 9)
IDS = 9;
CONTROLLER =(10, 10)
CONTROLLER = 10;
VIRTUAL =(11, 11)
VIRTUAL = 11;
FIBER_SWITCH =(12, 12)
FIBER_SWITCH = 12;
MICROWAVE =(13, 13)
MICROWAVE = 13;
UNRECOGNIZED =(-1, -1)
Static Public Attributes
staticfinal int OTHER_VALUE = 0
OTHER = 0;
staticfinal int SWITCH_VALUE = 1
SWITCH = 1;
staticfinal int ROUTER_VALUE = 2
ROUTER = 2;
staticfinal int ROADM_VALUE = 3
ROADM = 3;
staticfinal int OTN_VALUE = 4
OTN = 4;
staticfinal int ROADM_OTN_VALUE = 5
ROADM_OTN = 5;
staticfinal int FIREWALL_VALUE = 6
FIREWALL = 6;
staticfinal int BALANCER_VALUE = 7
BALANCER = 7;
staticfinal int IPS_VALUE = 8
IPS = 8;
staticfinal int IDS_VALUE = 9
IDS = 9;
staticfinal int CONTROLLER_VALUE = 10
CONTROLLER = 10;
staticfinal int VIRTUAL_VALUE = 11
VIRTUAL = 11;
staticfinal int FIBER_SWITCH_VALUE = 12
FIBER_SWITCH = 12;
staticfinal int MICROWAVE_VALUE = 13
MICROWAVE = 13;
Detailed Description
Protobuf enum.
Device.DeviceType
Definition at line 14 of file Device.java.
Member Function Documentation
static final com.google.protobuf.Descriptors.EnumDescriptor org.onosproject.grpc.Device.DeviceType.getDescriptor () static
Definition at line 182 of file Device.java.
final com.google.protobuf.Descriptors.EnumDescriptor org.onosproject.grpc.Device.DeviceType.getDescriptorForType ()
Definition at line 178 of file Device.java.
References org.onosproject.grpc.Device.getDescriptor().
final int org.onosproject.grpc.Device.DeviceType.getNumber ()
Definition at line 133 of file Device.java.
final com.google.protobuf.Descriptors.EnumValueDescriptor org.onosproject.grpc.Device.DeviceType.getValueDescriptor ()
Definition at line 174 of file Device.java.
References org.onosproject.grpc.Device.getDescriptor().
static com.google.protobuf.Internal.EnumLiteMap<DeviceType> org.onosproject.grpc.Device.DeviceType.internalGetValueMap () static
Definition at line 162 of file Device.java.
static DeviceType org.onosproject.grpc.Device.DeviceType.valueOf (int value) static
Definition at line 141 of file Device.java.
static DeviceType org.onosproject.grpc.Device.DeviceType.valueOf (com.google.protobuf.Descriptors.EnumValueDescriptor desc) static
Definition at line 188 of file Device.java.
References org.onosproject.grpc.Device.getDescriptor().
Member Data Documentation
org.onosproject.grpc.Device.DeviceType.BALANCER =(7, 7)
BALANCER = 7;
Definition at line 47 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.BALANCER_VALUE = 7 static
BALANCER = 7;
Definition at line 106 of file Device.java.
org.onosproject.grpc.Device.DeviceType.CONTROLLER =(10, 10)
CONTROLLER = 10;
Definition at line 59 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.CONTROLLER_VALUE = 10 static
CONTROLLER = 10;
Definition at line 118 of file Device.java.
org.onosproject.grpc.Device.DeviceType.FIBER_SWITCH =(12, 12)
FIBER_SWITCH = 12;
Definition at line 67 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.FIBER_SWITCH_VALUE = 12 static
FIBER_SWITCH = 12;
Definition at line 126 of file Device.java.
org.onosproject.grpc.Device.DeviceType.FIREWALL =(6, 6)
FIREWALL = 6;
Definition at line 43 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.FIREWALL_VALUE = 6 static
FIREWALL = 6;
Definition at line 102 of file Device.java.
org.onosproject.grpc.Device.DeviceType.IDS =(9, 9)
IDS = 9;
Definition at line 55 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.IDS_VALUE = 9 static
IDS = 9;
Definition at line 114 of file Device.java.
org.onosproject.grpc.Device.DeviceType.IPS =(8, 8)
IPS = 8;
Definition at line 51 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.IPS_VALUE = 8 static
IPS = 8;
Definition at line 110 of file Device.java.
org.onosproject.grpc.Device.DeviceType.MICROWAVE =(13, 13)
MICROWAVE = 13;
Definition at line 71 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.MICROWAVE_VALUE = 13 static
MICROWAVE = 13;
Definition at line 130 of file Device.java.
org.onosproject.grpc.Device.DeviceType.OTHER =(0, 0)
OTHER = 0;
Definition at line 19 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.OTHER_VALUE = 0 static
OTHER = 0;
Definition at line 78 of file Device.java.
org.onosproject.grpc.Device.DeviceType.OTN =(4, 4)
OTN = 4;
Definition at line 35 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.OTN_VALUE = 4 static
OTN = 4;
Definition at line 94 of file Device.java.
org.onosproject.grpc.Device.DeviceType.ROADM =(3, 3)
ROADM = 3;
Definition at line 31 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
org.onosproject.grpc.Device.DeviceType.ROADM_OTN =(5, 5)
ROADM_OTN = 5;
Definition at line 39 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.ROADM_OTN_VALUE = 5 static
ROADM_OTN = 5;
Definition at line 98 of file Device.java.
static final int org.onosproject.grpc.Device.DeviceType.ROADM_VALUE = 3 static
ROADM = 3;
Definition at line 90 of file Device.java.
org.onosproject.grpc.Device.DeviceType.ROUTER =(2, 2)
ROUTER = 2;
Definition at line 27 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.ROUTER_VALUE = 2 static
ROUTER = 2;
Definition at line 86 of file Device.java.
org.onosproject.grpc.Device.DeviceType.SWITCH =(1, 1)
SWITCH = 1;
Definition at line 23 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.SWITCH_VALUE = 1 static
SWITCH = 1;
Definition at line 82 of file Device.java.
org.onosproject.grpc.Device.DeviceType.UNRECOGNIZED =(-1, -1)
Definition at line 72 of file Device.java.
org.onosproject.grpc.Device.DeviceType.VIRTUAL =(11, 11)
VIRTUAL = 11;
Definition at line 63 of file Device.java.
Referenced by org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
static final int org.onosproject.grpc.Device.DeviceType.VIRTUAL_VALUE = 11 static
VIRTUAL = 11;
Definition at line 122 of file Device.java.
The documentation for this enum was generated from the following file:
incubator/rpc-grpc/target/generated-sources/protobuf/java/org/onosproject/grpc/Device.java