onos: org.onosproject.ovsdb.rfc.table.Ssl.SslColumn Enum Reference
org.onosproject.ovsdb.rfc.table.Ssl.SslColumn Enum Reference
Ssl table column name.
Public Member Functions
String columnName ()
Returns the table column name for SslColumn.
Public Attributes
CACERT =("ca_cert")
EXTERNALIDS =("external_ids")
BOOTSTRAPCACERT =("bootstrap_ca_cert")
CERTIFICATE =("certificate")
PRIVATEKEY =("private_key")
Detailed Description
Ssl table column name.
Definition at line 33 of file Ssl.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.Ssl.SslColumn.columnName ()
Returns the table column name for SslColumn.
Returns
the table column name
Definition at line 47 of file Ssl.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.Ssl.SslColumn.BOOTSTRAPCACERT =("bootstrap_ca_cert")
Definition at line 34 of file Ssl.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ssl.getBootstrapCaCertColumn(), and org.onosproject.ovsdb.rfc.table.Ssl.setBootstrapCaCert().
org.onosproject.ovsdb.rfc.table.Ssl.SslColumn.CACERT =("ca_cert")
Definition at line 34 of file Ssl.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ssl.getCaCertColumn(), and org.onosproject.ovsdb.rfc.table.Ssl.setCaCert().
org.onosproject.ovsdb.rfc.table.Ssl.SslColumn.CERTIFICATE =("certificate")
Definition at line 35 of file Ssl.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ssl.getCertificateColumn(), and org.onosproject.ovsdb.rfc.table.Ssl.setCertificate().
org.onosproject.ovsdb.rfc.table.Ssl.SslColumn.EXTERNALIDS =("external_ids")
Definition at line 34 of file Ssl.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ssl.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.Ssl.setExternalIds().
org.onosproject.ovsdb.rfc.table.Ssl.SslColumn.PRIVATEKEY =("private_key")
Definition at line 35 of file Ssl.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ssl.getPrivateKeyColumn(), and org.onosproject.ovsdb.rfc.table.Ssl.setPrivateKey().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/Ssl.java