onos: org.onosproject.ovsdb.rfc.notation.Mutation.Mutator Enum Reference
org.onosproject.ovsdb.rfc.notation.Mutation.Mutator Enum Reference
Mutator must be "+=", "-=", "*=", "/=", or (integer only) "%=".
Public Member Functions
String mutator ()
Returns the mutator for Mutator.
Public Attributes
SUM =("+=")
DIFFERENCE =("-=")
PRODUCT =("*=")
QUOTIENT =("/=")
REMAINDER =("%=")
INSERT =("insert")
DELETE =("delete")
Detailed Description
Mutator must be "+=", "-=", "*=", "/=", or (integer only) "%=".
The value of column is changed to the sum, difference, product, quotient, or remainder, respectively, of column and value.
Definition at line 38 of file Mutation.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.notation.Mutation.Mutator.mutator ()
Returns the mutator for Mutator.
Returns
the mutator
Definition at line 52 of file Mutation.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.notation.Mutation.Mutator.DELETE =("delete")
Definition at line 40 of file Mutation.java.
Referenced by org.onosproject.ovsdb.rfc.utils.MutationUtil.delete().
org.onosproject.ovsdb.rfc.notation.Mutation.Mutator.DIFFERENCE =("-=")
Definition at line 39 of file Mutation.java.
Referenced by org.onosproject.ovsdb.rfc.utils.MutationUtil.difference().
org.onosproject.ovsdb.rfc.notation.Mutation.Mutator.INSERT =("insert")
Definition at line 40 of file Mutation.java.
Referenced by org.onosproject.ovsdb.rfc.utils.MutationUtil.insert().
org.onosproject.ovsdb.rfc.notation.Mutation.Mutator.PRODUCT =("*=")
Definition at line 39 of file Mutation.java.
Referenced by org.onosproject.ovsdb.rfc.utils.MutationUtil.product().
org.onosproject.ovsdb.rfc.notation.Mutation.Mutator.QUOTIENT =("/=")
Definition at line 39 of file Mutation.java.
Referenced by org.onosproject.ovsdb.rfc.utils.MutationUtil.quotient().
org.onosproject.ovsdb.rfc.notation.Mutation.Mutator.REMAINDER =("%=")
Definition at line 40 of file Mutation.java.
Referenced by org.onosproject.ovsdb.rfc.utils.MutationUtil.remainder().
org.onosproject.ovsdb.rfc.notation.Mutation.Mutator.SUM =("+=")
Definition at line 39 of file Mutation.java.
Referenced by org.onosproject.ovsdb.rfc.utils.MutationUtil.sum().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/notation/Mutation.java