onos: org.onosproject.grpc.Device.MastershipRole Enum Reference
org.onosproject.grpc.Device.MastershipRole Enum Reference
Protobuf enum.
Public Member Functions
final int getNumber ()
final
com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor ()
final
com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType ()
Static Public Member Functions
static MastershipRole valueOf (int value)
static
com.google.protobuf.Internal.EnumLiteMap
< MastershipRole > internalGetValueMap ()
static final
com.google.protobuf.Descriptors.EnumDescriptor getDescriptor ()
static MastershipRole valueOf (com.google.protobuf.Descriptors.EnumValueDescriptor desc)
Public Attributes
NONE =(0, 0)
NONE = 0;
MASTER =(1, 1)
MASTER = 1;
STANDBY =(2, 2)
STANDBY = 2;
UNRECOGNIZED =(-1, -1)
Static Public Attributes
staticfinal int NONE_VALUE = 0
NONE = 0;
staticfinal int MASTER_VALUE = 1
MASTER = 1;
staticfinal int STANDBY_VALUE = 2
STANDBY = 2;
Detailed Description
Protobuf enum.
Device.MastershipRole
Definition at line 214 of file Device.java.
Member Function Documentation
static final com.google.protobuf.Descriptors.EnumDescriptor org.onosproject.grpc.Device.MastershipRole.getDescriptor () static
Definition at line 283 of file Device.java.
final com.google.protobuf.Descriptors.EnumDescriptor org.onosproject.grpc.Device.MastershipRole.getDescriptorForType ()
Definition at line 279 of file Device.java.
References org.onosproject.grpc.Device.getDescriptor().
final int org.onosproject.grpc.Device.MastershipRole.getNumber ()
Definition at line 245 of file Device.java.
final com.google.protobuf.Descriptors.EnumValueDescriptor org.onosproject.grpc.Device.MastershipRole.getValueDescriptor ()
Definition at line 275 of file Device.java.
References org.onosproject.grpc.Device.getDescriptor().
static com.google.protobuf.Internal.EnumLiteMap<MastershipRole> org.onosproject.grpc.Device.MastershipRole.internalGetValueMap () static
Definition at line 263 of file Device.java.
static MastershipRole org.onosproject.grpc.Device.MastershipRole.valueOf (int value) static
Definition at line 253 of file Device.java.
static MastershipRole org.onosproject.grpc.Device.MastershipRole.valueOf (com.google.protobuf.Descriptors.EnumValueDescriptor desc) static
Definition at line 289 of file Device.java.
References org.onosproject.grpc.Device.getDescriptor().
Member Data Documentation
org.onosproject.grpc.Device.MastershipRole.MASTER =(1, 1)
MASTER = 1;
Definition at line 223 of file Device.java.
static final int org.onosproject.grpc.Device.MastershipRole.MASTER_VALUE = 1 static
MASTER = 1;
Definition at line 238 of file Device.java.
org.onosproject.grpc.Device.MastershipRole.NONE =(0, 0)
NONE = 0;
Definition at line 219 of file Device.java.
static final int org.onosproject.grpc.Device.MastershipRole.NONE_VALUE = 0 static
NONE = 0;
Definition at line 234 of file Device.java.
org.onosproject.grpc.Device.MastershipRole.STANDBY =(2, 2)
STANDBY = 2;
Definition at line 227 of file Device.java.
static final int org.onosproject.grpc.Device.MastershipRole.STANDBY_VALUE = 2 static
STANDBY = 2;
Definition at line 242 of file Device.java.
org.onosproject.grpc.Device.MastershipRole.UNRECOGNIZED =(-1, -1)
Definition at line 228 of file Device.java.
The documentation for this enum was generated from the following file:
incubator/rpc-grpc/target/generated-sources/protobuf/java/org/onosproject/grpc/Device.java