onos: org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn Enum Reference
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn Enum Reference
Interface table column name.
Public Member Functions
String columnName ()
Returns the table column name for InterfaceColumn.
Public Attributes
NAME =("name")
TYPE =("type")
OPTIONS =("options")
INGRESSPOLICINGRATE =("ingress_policing_rate")
INGRESSPOLICINGBURST =("ingress_policing_burst")
MACINUSE =("mac_in_use")
MAC =("mac")
IFINDEX =("ifindex")
EXTERNALIDS =("external_ids")
OFPORT =("ofport")
OFPORTREQUEST =("ofport_request")
BFD =("bfd")
BFDSTATUS =("bfd_status")
MONITOR =("monitor")
CFMMPID =("cfm_mpid")
CFMREMOTEMPID =("cfm_remote_mpid")
CFMREMOTEMPIDS =("cfm_remote_mpids")
CFMFLAPCOUNT =("cfm_flap_count")
CFMFAULT =("cfm_fault")
CFMFAULTSTATUS =("cfm_fault_status")
CFMREMOTEOPSTATE =("cfm_remote_opstate")
CFMHEALTH =("cfm_health")
LACPCURRENT =("lacp_current")
OTHERCONFIG =("other_config")
STATISTICS =("statistics")
STATUS =("status")
ADMINSTATE =("admin_state")
LINKSTATE =("link_state")
LINKRESETS =("link_resets")
LINKSPEED =("link_speed")
DUPLEX =("duplex")
MTU =("mtu")
ERROR =("error")
Detailed Description
Interface table column name.
Definition at line 35 of file Interface.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.columnName ()
Returns the table column name for InterfaceColumn.
Returns
the table column name
Definition at line 61 of file Interface.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.ADMINSTATE =("admin_state")
Definition at line 47 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getAdminStateColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setAdminState().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.BFD =("bfd")
Definition at line 40 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getBfdColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setBfd().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.BFDSTATUS =("bfd_status")
Definition at line 41 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getBfdStatusColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setBfdStatus().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.CFMFAULT =("cfm_fault")
Definition at line 43 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmFaultColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmFault().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.CFMFAULTSTATUS =("cfm_fault_status")
Definition at line 44 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmFaultStatusColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmFaultStatus().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.CFMFLAPCOUNT =("cfm_flap_count")
Definition at line 43 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmFlapCountColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmFlapCount().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.CFMHEALTH =("cfm_health")
Definition at line 45 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmHealthColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmHealth().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.CFMMPID =("cfm_mpid")
Definition at line 41 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmMpidColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmMpid().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.CFMREMOTEMPID =("cfm_remote_mpid")
Definition at line 42 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmRemoteMpidColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmRemoteMpid().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.CFMREMOTEMPIDS =("cfm_remote_mpids")
Definition at line 42 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmRemoteMpidsColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmRemoteMpids().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.CFMREMOTEOPSTATE =("cfm_remote_opstate")
Definition at line 45 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmRemoteOpStateColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmRemoteOpState().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.DUPLEX =("duplex")
Definition at line 49 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getDuplexColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setDuplex().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.ERROR =("error")
Definition at line 49 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getErrorColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setError().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.EXTERNALIDS =("external_ids")
Definition at line 39 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setExternalIds().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.IFINDEX =("ifindex")
Definition at line 39 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getIfIndexColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setIfIndex().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.INGRESSPOLICINGBURST =("ingress_policing_burst")
Definition at line 38 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getIngressPolicingBurstColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setIngressPolicingBurst().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.INGRESSPOLICINGRATE =("ingress_policing_rate")
Definition at line 37 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getIngressPolicingRateColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setIngressPolicingRate().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.LACPCURRENT =("lacp_current")
Definition at line 46 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getLacpCurrentColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setLacpCurrent().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.LINKRESETS =("link_resets")
Definition at line 48 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getLinkResetsColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setLinkResets().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.LINKSPEED =("link_speed")
Definition at line 49 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getLinkSpeedColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setLinkSpeed().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.LINKSTATE =("link_state")
Definition at line 48 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getLinkStateColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setLinkState().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.MAC =("mac")
Definition at line 39 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getMacColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setMac().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.MACINUSE =("mac_in_use")
Definition at line 38 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getMacInUseColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setMacInUse().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.MONITOR =("monitor")
Definition at line 41 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getMonitorColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setMonitor().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.MTU =("mtu")
Definition at line 49 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getMtuColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setMtu().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.NAME =("name")
Definition at line 36 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getName(), org.onosproject.ovsdb.rfc.table.Interface.getNameColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setName().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.OFPORT =("ofport")
Definition at line 40 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getOpenFlowPortColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setOpenFlowPort().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.OFPORTREQUEST =("ofport_request")
Definition at line 40 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getOpenFlowPortRequestColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setOpenFlowPortRequest().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.OPTIONS =("options")
Definition at line 36 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getOptionsColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setOptions().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.OTHERCONFIG =("other_config")
Definition at line 46 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getOtherConfigColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setOtherConfig().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.STATISTICS =("statistics")
Definition at line 47 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getStatisticsColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setStatistics().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.STATUS =("status")
Definition at line 47 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getStatusColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setStatus().
org.onosproject.ovsdb.rfc.table.Interface.InterfaceColumn.TYPE =("type")
Definition at line 36 of file Interface.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getTypeColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setType().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/Interface.java