onos: org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.FlowSampleCollectorSetColumn Enum Reference
org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.FlowSampleCollectorSetColumn Enum Reference
FlowSampleCollectorSet table column name.
Public Member Functions
String columnName ()
Returns the table column name for FlowSampleCollectorSetColumn.
Public Attributes
ID =("id")
BRIDGE =("bridge")
IPFIX =("ipfix")
EXTERNALIDS =("external_ids")
Detailed Description
FlowSampleCollectorSet table column name.
Definition at line 34 of file FlowSampleCollectorSet.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.FlowSampleCollectorSetColumn.columnName ()
Returns the table column name for FlowSampleCollectorSetColumn.
Returns
the table column name
Definition at line 47 of file FlowSampleCollectorSet.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.FlowSampleCollectorSetColumn.BRIDGE =("bridge")
Definition at line 35 of file FlowSampleCollectorSet.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.getBridgeColumn(), and org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.setBridge().
org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.FlowSampleCollectorSetColumn.EXTERNALIDS =("external_ids")
Definition at line 35 of file FlowSampleCollectorSet.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.setExternalIds().
org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.FlowSampleCollectorSetColumn.ID =("id")
Definition at line 35 of file FlowSampleCollectorSet.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.getIdColumn(), and org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.setId().
org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.FlowSampleCollectorSetColumn.IPFIX =("ipfix")
Definition at line 35 of file FlowSampleCollectorSet.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.getIpfixColumn(), and org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.setIpfix().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/FlowSampleCollectorSet.java