onos: org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType Enum Reference
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType Enum Reference
Enum to provide PROTOCOLTYPE.
Public Member Functions
ProtocolType (int val)
Assign val with the value as the protocol type.
byte getType ()
Returns value of protocol type.
Public Attributes
ISIS_LEVEL_ONE =(1)
ISIS_LEVEL_TWO =(2)
OSPF_V2 =(3)
DIRECT =(4)
STATIC_CONFIGURATION =(5)
OSPF_V3 =(6)
int value
Detailed Description
Enum to provide PROTOCOLTYPE.
Definition at line 64 of file BgpNodeLSNlriVer4.java.
Constructor & Destructor Documentation
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.ProtocolType (int val)
Assign val with the value as the protocol type.
Parameters
val protocol type
Definition at line 73 of file BgpNodeLSNlriVer4.java.
Member Function Documentation
byte org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.getType ()
Returns value of protocol type.
Returns
protocol type
Definition at line 82 of file BgpNodeLSNlriVer4.java.
Member Data Documentation
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.DIRECT =(4)
Definition at line 65 of file BgpNodeLSNlriVer4.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getProtocolId(), org.onosproject.bgpio.protocol.linkstate.BgpPrefixIPv4LSNlriVer4.getProtocolId(), and org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getProtocolId().
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.ISIS_LEVEL_ONE =(1)
Definition at line 65 of file BgpNodeLSNlriVer4.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getProtocolId(), org.onosproject.bgpio.protocol.linkstate.BgpPrefixIPv4LSNlriVer4.getProtocolId(), org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getProtocolId(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest1(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest2(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest3(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest4(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest5(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest6(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest7(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest8(), and org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest9().
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.ISIS_LEVEL_TWO =(2)
Definition at line 65 of file BgpNodeLSNlriVer4.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getProtocolId(), org.onosproject.bgpio.protocol.linkstate.BgpPrefixIPv4LSNlriVer4.getProtocolId(), and org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getProtocolId().
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.OSPF_V2 =(3)
Definition at line 65 of file BgpNodeLSNlriVer4.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getProtocolId(), org.onosproject.bgpio.protocol.linkstate.BgpPrefixIPv4LSNlriVer4.getProtocolId(), org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getProtocolId(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest1(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest2(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest3(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest4(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest5(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest6(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest7(), org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest8(), and org.onosproject.controller.impl.BgpSelectionAlgoTest.selectionAlgoTest9().
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.OSPF_V3 =(6)
Definition at line 65 of file BgpNodeLSNlriVer4.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getProtocolId(), org.onosproject.bgpio.protocol.linkstate.BgpPrefixIPv4LSNlriVer4.getProtocolId(), and org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getProtocolId().
org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.STATIC_CONFIGURATION =(5)
Definition at line 65 of file BgpNodeLSNlriVer4.java.
Referenced by org.onosproject.bgpio.protocol.linkstate.BgpLinkLsNlriVer4.getProtocolId(), org.onosproject.bgpio.protocol.linkstate.BgpPrefixIPv4LSNlriVer4.getProtocolId(), and org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.getProtocolId().
int org.onosproject.bgpio.protocol.linkstate.BgpNodeLSNlriVer4.ProtocolType.value
Definition at line 66 of file BgpNodeLSNlriVer4.java.
The documentation for this enum was generated from the following file:
bgp/bgpio/src/main/java/org/onosproject/bgpio/protocol/linkstate/BgpNodeLSNlriVer4.java