onos: org.onosproject.ovsdb.rfc.table.FlowTable.FlowTableColumn Enum Reference
org.onosproject.ovsdb.rfc.table.FlowTable.FlowTableColumn Enum Reference
FlowTable table column name.
Public Member Functions
String columnName ()
Returns the table column name for FlowTableColumn.
Public Attributes
FLOWLIMIT =("flow_limit")
OVERFLOWPOLICY =("overflow_policy")
GROUPS =("groups")
NAME =("name")
PREFIXES =("prefixes")
EXTERNALIDS =("external_ids")
Detailed Description
FlowTable table column name.
Definition at line 34 of file FlowTable.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.FlowTable.FlowTableColumn.columnName ()
Returns the table column name for FlowTableColumn.
Returns
the table column name
Definition at line 48 of file FlowTable.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.FlowTable.FlowTableColumn.EXTERNALIDS =("external_ids")
Definition at line 36 of file FlowTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowTable.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.FlowTable.setExternalIds().
org.onosproject.ovsdb.rfc.table.FlowTable.FlowTableColumn.FLOWLIMIT =("flow_limit")
Definition at line 35 of file FlowTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowTable.getFlowLimitColumn(), and org.onosproject.ovsdb.rfc.table.FlowTable.setFlowLimit().
org.onosproject.ovsdb.rfc.table.FlowTable.FlowTableColumn.GROUPS =("groups")
Definition at line 35 of file FlowTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowTable.getGroupsColumn(), and org.onosproject.ovsdb.rfc.table.FlowTable.setGroups().
org.onosproject.ovsdb.rfc.table.FlowTable.FlowTableColumn.NAME =("name")
Definition at line 35 of file FlowTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowTable.getNameColumn(), and org.onosproject.ovsdb.rfc.table.FlowTable.setName().
org.onosproject.ovsdb.rfc.table.FlowTable.FlowTableColumn.OVERFLOWPOLICY =("overflow_policy")
Definition at line 35 of file FlowTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowTable.getOverflowPolicyColumn(), and org.onosproject.ovsdb.rfc.table.FlowTable.setOverflowPolicy().
org.onosproject.ovsdb.rfc.table.FlowTable.FlowTableColumn.PREFIXES =("prefixes")
Definition at line 36 of file FlowTable.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowTable.getPrefixesColumn(), and org.onosproject.ovsdb.rfc.table.FlowTable.setPrefixes().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/FlowTable.java