onos: org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn Enum Reference
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn Enum Reference
Controller table column name.
Public Member Functions
String columnName ()
Returns the table column name for ControllerColumn.
Public Attributes
TARGET =("target")
BURSTLIMIT =("controller_burst_limit")
RATELIMIT =("controller_rate_limit")
CONNECTIONMODE =("connection_mode")
ENABLEASYNCMESSAGES =("enable_async_messages")
EXTERNALIDS =("external_ids")
LOCALNETMASK =("local_netmask")
LOCALGATEWAY =("local_gateway")
STATUS =("status")
ROLE =("role")
INACTIVITYPROBE =("inactivity_probe")
ISCONNECTED =("is_connected")
OTHERCONFIG =("other_config")
MAXBACKOFF =("max_backoff")
LOCALIP =("local_ip")
DISCOVERUPDATERESOLVCONF =("discover_update_resolv_conf")
DISCOVERACCEPTREGEX =("discover_accept_regex")
Detailed Description
Controller table column name.
Definition at line 35 of file Controller.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.columnName ()
Returns the table column name for ControllerColumn.
Returns
the table column name
Definition at line 57 of file Controller.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.BURSTLIMIT =("controller_burst_limit")
Definition at line 36 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getBurstLimitColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setBurstLimit().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.CONNECTIONMODE =("connection_mode")
Definition at line 37 of file Controller.java.
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.DISCOVERACCEPTREGEX =("discover_accept_regex")
Definition at line 45 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getDiscoverAcceptRegexColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setDiscoverAcceptRegex().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.DISCOVERUPDATERESOLVCONF =("discover_update_resolv_conf")
Definition at line 44 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getDiscoverUpdateResolvConfColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setDiscoverUpdateResolvConf().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.ENABLEASYNCMESSAGES =("enable_async_messages")
Definition at line 38 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getEnableAsyncMessagesColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setEnableAsyncMessages().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.EXTERNALIDS =("external_ids")
Definition at line 39 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setExternalIds().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.INACTIVITYPROBE =("inactivity_probe")
Definition at line 41 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getInactivityProbeColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setInactivityProbe().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.ISCONNECTED =("is_connected")
Definition at line 41 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getIsConnectedColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setIsConnected().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.LOCALGATEWAY =("local_gateway")
Definition at line 40 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getLocalGatewayColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setLocalGateway().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.LOCALIP =("local_ip")
Definition at line 43 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getLocalIpColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setLocalIp().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.LOCALNETMASK =("local_netmask")
Definition at line 39 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getLocalNetmaskColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setLocalNetmask().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.MAXBACKOFF =("max_backoff")
Definition at line 42 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getMaxBackoffColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setMaxBackoff().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.OTHERCONFIG =("other_config")
Definition at line 42 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getOtherConfigColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setOtherConfig().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.RATELIMIT =("controller_rate_limit")
Definition at line 37 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getRateLimitColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setConnectionMode().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.ROLE =("role")
Definition at line 40 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getRoleColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setRole().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.STATUS =("status")
Definition at line 40 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getStatusColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setStatus().
org.onosproject.ovsdb.rfc.table.Controller.ControllerColumn.TARGET =("target")
Definition at line 36 of file Controller.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getTargetColumn(), and org.onosproject.ovsdb.rfc.table.Controller.setTarget().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/Controller.java