onos: org.onosproject.ovsdb.rfc.table.VersionNum Enum Reference
org.onosproject.ovsdb.rfc.table.VersionNum Enum Reference
The version number of tables and columns.
Public Member Functions
String versionNum ()
Returns the version number for VersionNum.
Public Attributes
VERSION100 =("1.0.0")
VERSION102 =("1.0.2")
VERSION103 =("1.0.3")
VERSION104 =("1.0.4")
VERSION106 =("1.0.6")
VERSION110 =("1.1.0")
VERSION130 =("1.3.0")
VERSION200 =("2.0.0")
VERSION300 =("3.0.0")
VERSION330 =("3.3.0")
VERSION350 =("3.5.0")
VERSION400 =("4.0.0")
VERSION510 =("5.1.0")
VERSION520 =("5.2.0")
VERSION600 =("6.0.0")
VERSION610 =("6.1.0")
VERSION620 =("6.2.0")
VERSION630 =("6.3.0")
VERSION640 =("6.4.0")
VERSION650 =("6.5.0")
VERSION660 =("6.6.0")
VERSION670 =("6.7.0")
VERSION680 =("6.8.0")
VERSION690 =("6.9.0")
VERSION6100 =("6.10.0")
VERSION6111 =("6.11.1")
VERSION710 =("7.1.0")
VERSION720 =("7.2.0")
VERSION721 =("7.2.1")
VERSION730 =("7.3.0")
VERSION740 =("7.4.0")
VERSION750 =("7.5.0")
VERSION770 =("7.7.0")
Detailed Description
The version number of tables and columns.
Definition at line 21 of file VersionNum.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.VersionNum.versionNum ()
Returns the version number for VersionNum.
Returns
the version number
Definition at line 44 of file VersionNum.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION100 =("1.0.0")
Definition at line 22 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.Bridge(), org.onosproject.ovsdb.rfc.table.Controller.Controller(), org.onosproject.ovsdb.rfc.table.Netflow.getActiveTimeoutColumn(), org.onosproject.ovsdb.rfc.table.Netflow.getAddIdToInterfaceColumn(), org.onosproject.ovsdb.rfc.table.Sflow.getAgentColumn(), org.onosproject.ovsdb.rfc.table.Port.getBondDownDelayColumn(), org.onosproject.ovsdb.rfc.table.Port.getBondFakeInterfaceColumn(), org.onosproject.ovsdb.rfc.table.Port.getBondUpDelayColumn(), org.onosproject.ovsdb.rfc.table.Ssl.getBootstrapCaCertColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getBridgesColumn(), org.onosproject.ovsdb.rfc.table.Controller.getBurstLimitColumn(), org.onosproject.ovsdb.rfc.table.Ssl.getCaCertColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getCapabilitiesColumn(), org.onosproject.ovsdb.rfc.table.Ssl.getCertificateColumn(), org.onosproject.ovsdb.rfc.table.Controller.getConnectionModeColumn(), org.onosproject.ovsdb.rfc.table.Manager.getConnectionModeColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getControllerColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getCurrentConfigColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getDatapathIdColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getDatapathTypeColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getDbVersionColumn(), org.onosproject.ovsdb.rfc.table.Controller.getDiscoverAcceptRegexColumn(), org.onosproject.ovsdb.rfc.table.Controller.getDiscoverUpdateResolvConfColumn(), org.onosproject.ovsdb.rfc.table.Queue.getDscpColumn(), org.onosproject.ovsdb.rfc.table.Netflow.getEngineIdColumn(), org.onosproject.ovsdb.rfc.table.Netflow.getEngineTypeColumn(), org.onosproject.ovsdb.rfc.table.Ssl.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Queue.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Sflow.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Qos.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Netflow.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Manager.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Controller.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Mirror.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Interface.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Port.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getFailModeColumn(), org.onosproject.ovsdb.rfc.table.Port.getFakeBridgeColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getFloodVlansColumn(), org.onosproject.ovsdb.rfc.table.Sflow.getHeaderColumn(), org.onosproject.ovsdb.rfc.table.Manager.getInactivityProbeColumn(), org.onosproject.ovsdb.rfc.table.Controller.getInactivityProbeColumn(), org.onosproject.ovsdb.rfc.table.Interface.getIngressPolicingBurstColumn(), org.onosproject.ovsdb.rfc.table.Interface.getIngressPolicingRateColumn(), org.onosproject.ovsdb.rfc.table.Port.getInterfacesColumn(), org.onosproject.ovsdb.rfc.table.Controller.getLocalGatewayColumn(), org.onosproject.ovsdb.rfc.table.Controller.getLocalIpColumn(), org.onosproject.ovsdb.rfc.table.Controller.getLocalNetmaskColumn(), org.onosproject.ovsdb.rfc.table.Port.getMacColumn(), org.onosproject.ovsdb.rfc.table.Interface.getMacColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getManagerOptionsColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getManagersColumn(), org.onosproject.ovsdb.rfc.table.Manager.getMaxBackoffColumn(), org.onosproject.ovsdb.rfc.table.Controller.getMaxBackoffColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getMirrorsColumn(), org.onosproject.ovsdb.rfc.table.Interface.getMonitorColumn(), org.onosproject.ovsdb.rfc.table.Mirror.getName(), org.onosproject.ovsdb.rfc.table.Port.getName(), org.onosproject.ovsdb.rfc.table.Bridge.getName(), org.onosproject.ovsdb.rfc.table.Interface.getName(), org.onosproject.ovsdb.rfc.table.Mirror.getNameColumn(), org.onosproject.ovsdb.rfc.table.Port.getNameColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getNameColumn(), org.onosproject.ovsdb.rfc.table.Interface.getNameColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getNetflowColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getNextConfigColumn(), org.onosproject.ovsdb.rfc.table.Interface.getOpenFlowPortColumn(), org.onosproject.ovsdb.rfc.table.Interface.getOptionsColumn(), org.onosproject.ovsdb.rfc.table.Queue.getOtherConfigColumn(), org.onosproject.ovsdb.rfc.table.Qos.getOtherConfigColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getOtherConfigColumn(), org.onosproject.ovsdb.rfc.table.Port.getOtherConfigColumn(), org.onosproject.ovsdb.rfc.table.Interface.getOtherConfigColumn(), org.onosproject.ovsdb.rfc.table.Mirror.getOutputPortColumn(), org.onosproject.ovsdb.rfc.table.Mirror.getOutputVlanColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getOvsVersionColumn(), org.onosproject.ovsdb.rfc.table.Sflow.getPollingColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getPortsColumn(), org.onosproject.ovsdb.rfc.table.Ssl.getPrivateKeyColumn(), org.onosproject.ovsdb.rfc.table.Port.getQosColumn(), org.onosproject.ovsdb.rfc.table.Qos.getQueuesColumn(), org.onosproject.ovsdb.rfc.table.Controller.getRateLimitColumn(), org.onosproject.ovsdb.rfc.table.Sflow.getSamplingColumn(), org.onosproject.ovsdb.rfc.table.Mirror.getSelectDstPortColumn(), org.onosproject.ovsdb.rfc.table.Mirror.getSelectSrcPortColumn(), org.onosproject.ovsdb.rfc.table.Mirror.getSelectVlanColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getSflowColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getSslColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getStatisticsColumn(), org.onosproject.ovsdb.rfc.table.Interface.getStatisticsColumn(), org.onosproject.ovsdb.rfc.table.Controller.getStatusColumn(), org.onosproject.ovsdb.rfc.table.Interface.getStatusColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getSystemTypeColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.getSystemVersionColumn(), org.onosproject.ovsdb.rfc.table.Port.getTagColumn(), org.onosproject.ovsdb.rfc.table.Manager.getTargetColumn(), org.onosproject.ovsdb.rfc.table.Controller.getTargetColumn(), org.onosproject.ovsdb.rfc.table.Netflow.getTargetsColumn(), org.onosproject.ovsdb.rfc.table.Sflow.getTargetsColumn(), org.onosproject.ovsdb.rfc.table.Port.getTrunksColumn(), org.onosproject.ovsdb.rfc.table.Qos.getTypeColumn(), org.onosproject.ovsdb.rfc.table.Interface.getTypeColumn(), org.onosproject.ovsdb.rfc.table.Interface.Interface(), org.onosproject.ovsdb.rfc.table.Manager.Manager(), org.onosproject.ovsdb.rfc.table.Mirror.Mirror(), org.onosproject.ovsdb.rfc.table.Netflow.Netflow(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.OpenVSwitch(), org.onosproject.ovsdb.rfc.table.Port.Port(), org.onosproject.ovsdb.rfc.table.Qos.Qos(), org.onosproject.ovsdb.rfc.table.Queue.Queue(), org.onosproject.ovsdb.rfc.table.Netflow.setActiveTimeout(), org.onosproject.ovsdb.rfc.table.Netflow.setAddIdToInterface(), org.onosproject.ovsdb.rfc.table.Sflow.setAgent(), org.onosproject.ovsdb.rfc.table.Port.setBondDownDelay(), org.onosproject.ovsdb.rfc.table.Port.setBondFakeInterface(), org.onosproject.ovsdb.rfc.table.Port.setBondUpDelay(), org.onosproject.ovsdb.rfc.table.Ssl.setBootstrapCaCert(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setBridges(), org.onosproject.ovsdb.rfc.table.Controller.setBurstLimit(), org.onosproject.ovsdb.rfc.table.Ssl.setCaCert(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setCapabilities(), org.onosproject.ovsdb.rfc.table.Ssl.setCertificate(), org.onosproject.ovsdb.rfc.table.Controller.setConnectionMode(), org.onosproject.ovsdb.rfc.table.Manager.setConnectionMode(), org.onosproject.ovsdb.rfc.table.Bridge.setController(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setCurrentConfig(), org.onosproject.ovsdb.rfc.table.Bridge.setDatapathId(), org.onosproject.ovsdb.rfc.table.Bridge.setDatapathType(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setDbVersion(), org.onosproject.ovsdb.rfc.table.Controller.setDiscoverAcceptRegex(), org.onosproject.ovsdb.rfc.table.Controller.setDiscoverUpdateResolvConf(), org.onosproject.ovsdb.rfc.table.Queue.setDscp(), org.onosproject.ovsdb.rfc.table.Netflow.setEngineId(), org.onosproject.ovsdb.rfc.table.Netflow.setEngineType(), org.onosproject.ovsdb.rfc.table.Ssl.setExternalIds(), org.onosproject.ovsdb.rfc.table.Queue.setExternalIds(), org.onosproject.ovsdb.rfc.table.Sflow.setExternalIds(), org.onosproject.ovsdb.rfc.table.Qos.setExternalIds(), org.onosproject.ovsdb.rfc.table.Netflow.setExternalIds(), org.onosproject.ovsdb.rfc.table.Manager.setExternalIds(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setExternalIds(), org.onosproject.ovsdb.rfc.table.Controller.setExternalIds(), org.onosproject.ovsdb.rfc.table.Mirror.setExternalIds(), org.onosproject.ovsdb.rfc.table.Interface.setExternalIds(), org.onosproject.ovsdb.rfc.table.Bridge.setExternalIds(), org.onosproject.ovsdb.rfc.table.Port.setExternalIds(), org.onosproject.ovsdb.rfc.table.Bridge.setFailMode(), org.onosproject.ovsdb.rfc.table.Port.setFakeBridge(), org.onosproject.ovsdb.rfc.table.Bridge.setFloodVlans(), org.onosproject.ovsdb.rfc.table.Sflow.setHeader(), org.onosproject.ovsdb.rfc.table.Manager.setInactivityProbe(), org.onosproject.ovsdb.rfc.table.Controller.setInactivityProbe(), org.onosproject.ovsdb.rfc.table.Interface.setIngressPolicingBurst(), org.onosproject.ovsdb.rfc.table.Interface.setIngressPolicingRate(), org.onosproject.ovsdb.rfc.table.Port.setInterfaces(), org.onosproject.ovsdb.rfc.table.Controller.setLocalGateway(), org.onosproject.ovsdb.rfc.table.Controller.setLocalIp(), org.onosproject.ovsdb.rfc.table.Controller.setLocalNetmask(), org.onosproject.ovsdb.rfc.table.Port.setMac(), org.onosproject.ovsdb.rfc.table.Interface.setMac(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setManagerOptions(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setManagers(), org.onosproject.ovsdb.rfc.table.Manager.setMaxBackoff(), org.onosproject.ovsdb.rfc.table.Controller.setMaxBackoff(), org.onosproject.ovsdb.rfc.table.Bridge.setMirrors(), org.onosproject.ovsdb.rfc.table.Interface.setMonitor(), org.onosproject.ovsdb.rfc.table.Mirror.setName(), org.onosproject.ovsdb.rfc.table.Port.setName(), org.onosproject.ovsdb.rfc.table.Bridge.setName(), org.onosproject.ovsdb.rfc.table.Interface.setName(), org.onosproject.ovsdb.rfc.table.Bridge.setNetflow(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setNextConfig(), org.onosproject.ovsdb.rfc.table.Interface.setOpenFlowPort(), org.onosproject.ovsdb.rfc.table.Interface.setOptions(), org.onosproject.ovsdb.rfc.table.Queue.setOtherConfig(), org.onosproject.ovsdb.rfc.table.Qos.setOtherConfig(), org.onosproject.ovsdb.rfc.table.Bridge.setOtherConfig(), org.onosproject.ovsdb.rfc.table.Port.setOtherConfig(), org.onosproject.ovsdb.rfc.table.Interface.setOtherConfig(), org.onosproject.ovsdb.rfc.table.Mirror.setOutputPort(), org.onosproject.ovsdb.rfc.table.Mirror.setOutputVlan(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setOvsVersion(), org.onosproject.ovsdb.rfc.table.Sflow.setPolling(), org.onosproject.ovsdb.rfc.table.Bridge.setPorts(), org.onosproject.ovsdb.rfc.table.Ssl.setPrivateKey(), org.onosproject.ovsdb.rfc.table.Port.setQos(), org.onosproject.ovsdb.rfc.table.Qos.setQueues(), org.onosproject.ovsdb.rfc.table.Controller.setRateLimit(), org.onosproject.ovsdb.rfc.table.Sflow.setSampling(), org.onosproject.ovsdb.rfc.table.Mirror.setSelectDstPort(), org.onosproject.ovsdb.rfc.table.Mirror.setSelectSrcPort(), org.onosproject.ovsdb.rfc.table.Mirror.setSelectVlan(), org.onosproject.ovsdb.rfc.table.Bridge.setSflow(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setSsl(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setStatistics(), org.onosproject.ovsdb.rfc.table.Interface.setStatistics(), org.onosproject.ovsdb.rfc.table.Controller.setStatus(), org.onosproject.ovsdb.rfc.table.Interface.setStatus(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setSystemType(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setSystemVersion(), org.onosproject.ovsdb.rfc.table.Port.setTag(), org.onosproject.ovsdb.rfc.table.Manager.setTarget(), org.onosproject.ovsdb.rfc.table.Controller.setTarget(), org.onosproject.ovsdb.rfc.table.Netflow.setTargets(), org.onosproject.ovsdb.rfc.table.Sflow.setTargets(), org.onosproject.ovsdb.rfc.table.Port.setTrunks(), org.onosproject.ovsdb.rfc.table.Qos.setType(), org.onosproject.ovsdb.rfc.table.Interface.setType(), org.onosproject.ovsdb.rfc.table.Sflow.Sflow(), and org.onosproject.ovsdb.rfc.table.Ssl.Ssl().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION102 =("1.0.2")
Definition at line 22 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getBondTypeColumn(), and org.onosproject.ovsdb.rfc.table.Port.setBondType().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION103 =("1.0.3")
Definition at line 22 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getBondTypeColumn(), and org.onosproject.ovsdb.rfc.table.Port.setBondType().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION104 =("1.0.4")
Definition at line 23 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getBondModeColumn(), and org.onosproject.ovsdb.rfc.table.Port.setBondMode().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION106 =("1.0.6")
Definition at line 23 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getAdminStateColumn(), org.onosproject.ovsdb.rfc.table.Interface.getDuplexColumn(), org.onosproject.ovsdb.rfc.table.Interface.getLinkSpeedColumn(), org.onosproject.ovsdb.rfc.table.Interface.getLinkStateColumn(), org.onosproject.ovsdb.rfc.table.Interface.getMtuColumn(), org.onosproject.ovsdb.rfc.table.Interface.setAdminState(), org.onosproject.ovsdb.rfc.table.Interface.setDuplex(), org.onosproject.ovsdb.rfc.table.Interface.setLinkSpeed(), org.onosproject.ovsdb.rfc.table.Interface.setLinkState(), and org.onosproject.ovsdb.rfc.table.Interface.setMtu().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION110 =("1.1.0")
Definition at line 23 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Manager.getIsConnectedColumn(), org.onosproject.ovsdb.rfc.table.Controller.getIsConnectedColumn(), org.onosproject.ovsdb.rfc.table.Controller.getRoleColumn(), org.onosproject.ovsdb.rfc.table.Manager.getStatusColumn(), org.onosproject.ovsdb.rfc.table.Manager.setIsConnected(), org.onosproject.ovsdb.rfc.table.Controller.setIsConnected(), org.onosproject.ovsdb.rfc.table.Controller.setRole(), and org.onosproject.ovsdb.rfc.table.Manager.setStatus().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION130 =("1.3.0")
Definition at line 24 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getLacpColumn(), and org.onosproject.ovsdb.rfc.table.Port.setLacp().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION200 =("2.0.0")
Definition at line 24 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getManagersColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setManagers().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION300 =("3.0.0")
Definition at line 24 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Controller.getDiscoverAcceptRegexColumn(), org.onosproject.ovsdb.rfc.table.Controller.getDiscoverUpdateResolvConfColumn(), org.onosproject.ovsdb.rfc.table.Controller.setDiscoverAcceptRegex(), and org.onosproject.ovsdb.rfc.table.Controller.setDiscoverUpdateResolvConf().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION330 =("3.3.0")
Definition at line 25 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getLacpCurrentColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setLacpCurrent().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION350 =("3.5.0")
Definition at line 25 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getMonitorColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setMonitor().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION400 =("4.0.0")
Definition at line 25 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmFaultColumn(), org.onosproject.ovsdb.rfc.table.Interface.getCfmMpidColumn(), org.onosproject.ovsdb.rfc.table.Interface.getCfmRemoteMpidColumn(), org.onosproject.ovsdb.rfc.table.Interface.setCfmFault(), org.onosproject.ovsdb.rfc.table.Interface.setCfmMpid(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmRemoteMpid().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION510 =("5.1.0")
Definition at line 26 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getOtherConfigColumn(), and org.onosproject.ovsdb.rfc.table.OpenVSwitch.setOtherConfig().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION520 =("5.2.0")
Definition at line 26 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmRemoteMpidColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmRemoteMpid().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION600 =("6.0.0")
Definition at line 26 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmRemoteMpidsColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmRemoteMpids().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION610 =("6.1.0")
Definition at line 27 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getVlanModeColumn(), and org.onosproject.ovsdb.rfc.table.Port.setVlanMode().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION6100 =("6.10.0")
Definition at line 30 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmRemoteOpStateColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmRemoteOpState().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION6111 =("6.11.1")
Definition at line 30 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getProtocolsColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setProtocols().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION620 =("6.2.0")
Definition at line 27 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getLinkResetsColumn(), org.onosproject.ovsdb.rfc.table.Interface.getOpenFlowPortRequestColumn(), org.onosproject.ovsdb.rfc.table.Mirror.getSelectAllColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getStatusColumn(), org.onosproject.ovsdb.rfc.table.Port.getStatusColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getStpEnableColumn(), org.onosproject.ovsdb.rfc.table.Interface.setLinkResets(), org.onosproject.ovsdb.rfc.table.Interface.setOpenFlowPortRequest(), org.onosproject.ovsdb.rfc.table.Mirror.setSelectAll(), org.onosproject.ovsdb.rfc.table.Bridge.setStatus(), org.onosproject.ovsdb.rfc.table.Port.setStatus(), and org.onosproject.ovsdb.rfc.table.Bridge.setStpEnable().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION630 =("6.3.0")
Definition at line 27 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getStatisticsColumn(), and org.onosproject.ovsdb.rfc.table.Port.setStatistics().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION640 =("6.4.0")
Definition at line 28 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Mirror.getStatisticsColumn(), and org.onosproject.ovsdb.rfc.table.Mirror.setStatistics().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION650 =("6.5.0")
Definition at line 28 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowTable.FlowTable(), org.onosproject.ovsdb.rfc.table.FlowTable.getFlowLimitColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getFlowTablesColumn(), org.onosproject.ovsdb.rfc.table.FlowTable.getGroupsColumn(), org.onosproject.ovsdb.rfc.table.FlowTable.getNameColumn(), org.onosproject.ovsdb.rfc.table.FlowTable.getOverflowPolicyColumn(), org.onosproject.ovsdb.rfc.table.FlowTable.setFlowLimit(), org.onosproject.ovsdb.rfc.table.Bridge.setFlowTables(), org.onosproject.ovsdb.rfc.table.FlowTable.setGroups(), org.onosproject.ovsdb.rfc.table.FlowTable.setName(), and org.onosproject.ovsdb.rfc.table.FlowTable.setOverflowPolicy().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION660 =("6.6.0")
Definition at line 28 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmFaultStatusColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmFaultStatus().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION670 =("6.7.0")
Definition at line 29 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.OpenVSwitch.getCapabilitiesColumn(), org.onosproject.ovsdb.rfc.table.Controller.getEnableAsyncMessagesColumn(), org.onosproject.ovsdb.rfc.table.OpenVSwitch.setCapabilities(), and org.onosproject.ovsdb.rfc.table.Controller.setEnableAsyncMessages().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION680 =("6.8.0")
Definition at line 29 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Manager.getOtherConfigColumn(), org.onosproject.ovsdb.rfc.table.Controller.getOtherConfigColumn(), org.onosproject.ovsdb.rfc.table.Manager.setOtherConfig(), and org.onosproject.ovsdb.rfc.table.Controller.setOtherConfig().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION690 =("6.9.0")
Definition at line 29 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getCfmHealthColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmHealth().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION710 =("7.1.0")
Definition at line 30 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.FlowSampleCollectorSet(), org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.getBridgeColumn(), org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.Ipfix.getExternalIdsColumn(), org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.getIdColumn(), org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.getIpfixColumn(), org.onosproject.ovsdb.rfc.table.Bridge.getIpfixColumn(), org.onosproject.ovsdb.rfc.table.Interface.getMacInUseColumn(), org.onosproject.ovsdb.rfc.table.Ipfix.getObsDomainIdColumn(), org.onosproject.ovsdb.rfc.table.Ipfix.getObsPointIdColumn(), org.onosproject.ovsdb.rfc.table.Ipfix.getSamplingColumn(), org.onosproject.ovsdb.rfc.table.Ipfix.getTargetsColumn(), org.onosproject.ovsdb.rfc.table.Ipfix.Ipfix(), org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.setBridge(), org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.setExternalIds(), org.onosproject.ovsdb.rfc.table.Ipfix.setExternalIds(), org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.setId(), org.onosproject.ovsdb.rfc.table.FlowSampleCollectorSet.setIpfix(), org.onosproject.ovsdb.rfc.table.Bridge.setIpfix(), org.onosproject.ovsdb.rfc.table.Interface.setMacInUse(), org.onosproject.ovsdb.rfc.table.Ipfix.setObsDomainId(), org.onosproject.ovsdb.rfc.table.Ipfix.setObsPointId(), org.onosproject.ovsdb.rfc.table.Ipfix.setSampling(), and org.onosproject.ovsdb.rfc.table.Ipfix.setTargets().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION720 =("7.2.0")
Definition at line 31 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getBfdColumn(), org.onosproject.ovsdb.rfc.table.Interface.getBfdStatusColumn(), org.onosproject.ovsdb.rfc.table.Interface.setBfd(), and org.onosproject.ovsdb.rfc.table.Interface.setBfdStatus().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION721 =("7.2.1")
Definition at line 31 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getIfIndexColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setIfIndex().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION730 =("7.3.0")
Definition at line 31 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Ipfix.getCacheActiveTimeoutColumn(), org.onosproject.ovsdb.rfc.table.Ipfix.getCacheMaxFlowsColumn(), org.onosproject.ovsdb.rfc.table.Interface.getCfmFlapCountColumn(), org.onosproject.ovsdb.rfc.table.Ipfix.setCacheActiveTimeout(), org.onosproject.ovsdb.rfc.table.Ipfix.setCacheMaxFlows(), and org.onosproject.ovsdb.rfc.table.Interface.setCfmFlapCount().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION740 =("7.4.0")
Definition at line 32 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowTable.getPrefixesColumn(), and org.onosproject.ovsdb.rfc.table.FlowTable.setPrefixes().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION750 =("7.5.0")
Definition at line 32 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.FlowTable.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.FlowTable.setExternalIds().
org.onosproject.ovsdb.rfc.table.VersionNum.VERSION770 =("7.7.0")
Definition at line 32 of file VersionNum.java.
Referenced by org.onosproject.ovsdb.rfc.table.Interface.getErrorColumn(), and org.onosproject.ovsdb.rfc.table.Interface.setError().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/VersionNum.java