onos: org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn Enum Reference
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn Enum Reference
Bridge table column name.
Public Member Functions
String columnName ()
Returns the table column name for BridgeColumn.
Public Attributes
NAME =("name")
DATAPATHTYPE =("datapath_type")
DATAPATHID =("datapath_id")
STPENABLE =("stpenable")
PORTS =("ports")
MIRRORS =("mirrors")
NETFLOW =("netflow")
SFLOW =("sflow")
IPFIX =("ipfix")
CONTROLLER =("controller")
PROTOCOLS =("protocols")
FAILMODE =("fail_mode")
STATUS =("status")
OTHERCONFIG =("other_config")
EXTERNALIDS =("external_ids")
FLOODVLANS =("flood_vlans")
FLOWTABLES =("flow_tables")
Detailed Description
Bridge table column name.
Definition at line 37 of file Bridge.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.columnName ()
Returns the table column name for BridgeColumn.
Returns
the table column name
Definition at line 56 of file Bridge.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.CONTROLLER =("controller")
Definition at line 41 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getControllerColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setController().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.DATAPATHID =("datapath_id")
Definition at line 38 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getDatapathIdColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setDatapathId().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.DATAPATHTYPE =("datapath_type")
Definition at line 38 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getDatapathTypeColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setDatapathType().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.EXTERNALIDS =("external_ids")
Definition at line 43 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setExternalIds().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.FAILMODE =("fail_mode")
Definition at line 42 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getFailModeColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setFailMode().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.FLOODVLANS =("flood_vlans")
Definition at line 43 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getFloodVlansColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setFloodVlans().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.FLOWTABLES =("flow_tables")
Definition at line 44 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getFlowTablesColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setFlowTables().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.IPFIX =("ipfix")
Definition at line 40 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getIpfixColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setIpfix().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.MIRRORS =("mirrors")
Definition at line 39 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getMirrorsColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setMirrors().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.NAME =("name")
Definition at line 38 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getName(), org.onosproject.ovsdb.rfc.table.Bridge.getNameColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setName().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.NETFLOW =("netflow")
Definition at line 40 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getNetflowColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setNetflow().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.OTHERCONFIG =("other_config")
Definition at line 42 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getOtherConfigColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setOtherConfig().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.PORTS =("ports")
Definition at line 39 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getPortsColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setPorts().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.PROTOCOLS =("protocols")
Definition at line 41 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getProtocolsColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setProtocols().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.SFLOW =("sflow")
Definition at line 40 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getSflowColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setSflow().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.STATUS =("status")
Definition at line 42 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getStatusColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setStatus().
org.onosproject.ovsdb.rfc.table.Bridge.BridgeColumn.STPENABLE =("stpenable")
Definition at line 39 of file Bridge.java.
Referenced by org.onosproject.ovsdb.rfc.table.Bridge.getStpEnableColumn(), and org.onosproject.ovsdb.rfc.table.Bridge.setStpEnable().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/Bridge.java