onos: org.onosproject.pcepio.protocol.PcepVersion Enum Reference
org.onosproject.pcepio.protocol.PcepVersion Enum Reference
Enum to provide PCEP Message Version.
Public Member Functions
PcepVersion (final int wireVersion)
Assign PCEP PacketVersion with WireVersion.
int getWireVersion ()
Returns Wire version of PCEP Message.
Public Attributes
PCEP_1 =(1)
final int packetVersion
Detailed Description
Enum to provide PCEP Message Version.
Definition at line 22 of file PcepVersion.java.
Constructor & Destructor Documentation
org.onosproject.pcepio.protocol.PcepVersion.PcepVersion (final int wireVersion)
Assign PCEP PacketVersion with WireVersion.
Parameters
wireVersion version of pcep
Definition at line 33 of file PcepVersion.java.
Member Function Documentation
int org.onosproject.pcepio.protocol.PcepVersion.getWireVersion ()
Returns Wire version of PCEP Message.
Returns
packetVersion
Definition at line 43 of file PcepVersion.java.
Member Data Documentation
final int org.onosproject.pcepio.protocol.PcepVersion.packetVersion
Definition at line 26 of file PcepVersion.java.
org.onosproject.pcepio.protocol.PcepVersion.PCEP_1 =(1)
Definition at line 24 of file PcepVersion.java.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepClientControllerAdapter.getClient(), org.onosproject.pcepio.types.PcepLabelDbVerTlv.getVersion(), org.onosproject.pcepio.types.StatefulLspErrorCodeTlv.getVersion(), org.onosproject.pcepio.types.StatefulLspDbVerTlv.getVersion(), org.onosproject.pcepio.types.OSPFareaIDsubTlv.getVersion(), org.onosproject.pcepio.types.MaximumReservableLinkBandwidthTlv.getVersion(), org.onosproject.pcepio.types.UnreservedBandwidthTlv.getVersion(), org.onosproject.pcepio.types.AutonomousSystemTlv.getVersion(), org.onosproject.pcepio.types.IPv4TERouterIdOfLocalNodeTlv.getVersion(), org.onosproject.pcepio.types.AdministrativeGroupTlv.getVersion(), org.onosproject.pcepio.types.BGPLSidentifierTlv.getVersion(), org.onosproject.pcepio.types.IPv4InterfaceAddressTlv.getVersion(), org.onosproject.pcepio.types.IPv4NeighborAddressTlv.getVersion(), org.onosproject.pcepio.types.IPv4TERouterIdOfRemoteNodeTlv.getVersion(), org.onosproject.pcepio.types.MaximumLinkBandwidthTlv.getVersion(), org.onosproject.pcepio.types.TEDefaultMetricTlv.getVersion(), org.onosproject.pcepio.types.LinkProtectionTypeTlv.getVersion(), org.onosproject.pcepio.types.GmplsCapabilityTlv.getVersion(), org.onosproject.pcepio.types.IGPMetricTlv.getVersion(), org.onosproject.pcepio.protocol.ver1.PcepOpenMsgVer1.getVersion(), org.onosproject.pcepio.types.NexthopIPv4addressTlv.getVersion(), org.onosproject.pcepio.types.NodeNameTlv.getVersion(), org.onosproject.pcepio.types.OpaqueNodeAttributeTlv.getVersion(), org.onosproject.pcepio.types.RouterIDSubTlv.getVersion(), org.onosproject.pcepio.types.OpaqueLinkAttributeTlv.getVersion(), org.onosproject.pcepio.types.LocalTENodeDescriptorsTlv.getVersion(), org.onosproject.pcepio.types.ISISAreaIdentifierTlv.getVersion(), org.onosproject.pcepio.types.LinkNameTlv.getVersion(), org.onosproject.pcepio.types.TELinkAttributesTlv.getVersion(), org.onosproject.pcepio.types.PathSetupTypeTlv.getVersion(), org.onosproject.pcepio.types.RemoteTENodeDescriptorsTlv.getVersion(), org.onosproject.pcepio.types.TELinkDescriptorsTlv.getVersion(), org.onosproject.pcepio.types.RoutingUniverseTlv.getVersion(), org.onosproject.pcepio.types.TENodeAttributesTlv.getVersion(), org.onosproject.pcepio.types.LinkLocalRemoteIdentifiersTlv.getVersion(), org.onosproject.pcepio.types.PceccCapabilityTlv.getVersion(), org.onosproject.pcepio.types.SharedRiskLinkGroupTlv.getVersion(), org.onosproject.pcepio.types.PathKeySubObject.getVersion(), org.onosproject.pcepio.types.NexthopUnnumberedIPv4IDTlv.getVersion(), org.onosproject.pcepio.types.SymbolicPathNameTlv.getVersion(), org.onosproject.pcepio.types.TedCapabilityTlv.getVersion(), org.onosproject.pcepio.types.IPv6TERouterIdofRemoteNodeTlv.getVersion(), org.onosproject.pcepio.types.LabelSubObject.getVersion(), org.onosproject.pcepio.protocol.ver1.PcepFactoryVer1.getVersion(), org.onosproject.pcepio.types.StatefulPceCapabilityTlv.getVersion(), org.onosproject.pcepio.types.IPv4SubObject.getVersion(), org.onosproject.pcepio.types.IPv6NeighborAddressTlv.getVersion(), org.onosproject.pcepio.types.IPv6TERouterIdofLocalNodeTlv.getVersion(), org.onosproject.pcepio.types.IPv6InterfaceAddressTlv.getVersion(), org.onosproject.pcepio.types.MPLSProtocolMaskTlv.getVersion(), org.onosproject.pcepio.types.StatefulIPv4LspIdentidiersTlv.getVersion(), org.onosproject.pcepio.types.NexthopIPv6addressTlv.getVersion(), org.onosproject.pcepio.types.PcepRsvpIpv4ErrorSpec.getVersion(), org.onosproject.pcepio.types.StatefulRsvpErrorSpecTlv.getVersion(), org.onosproject.pcepio.types.PcepRsvpIpv6ErrorSpec.getVersion(), org.onosproject.pcepio.protocol.ver1.PcepOpenObjectVer1.getVersion(), org.onosproject.pcepio.types.NodeFlagBitsTlv.getVersion(), org.onosproject.pcepio.types.IPv6SubObject.getVersion(), org.onosproject.pcepio.types.PcepRsvpUserErrorSpec.getVersion(), org.onosproject.pcepio.types.SrEroSubObject.getVersion(), org.onosproject.pcepio.protocol.ver1.PcepFecObjectIPv4Ver1.getVersion(), org.onosproject.pcepio.protocol.ver1.PcepFecObjectIPv6Ver1.getVersion(), org.onosproject.pcepio.protocol.ver1.PcepFecObjectIPv6AdjacencyVer1.getVersion(), org.onosproject.pcepio.protocol.ver1.PcepFecObjectIPv4AdjacencyVer1.getVersion(), org.onosproject.pcepio.protocol.ver1.PcepErrorMsgVer1.getVersion(), and org.onosproject.pcepio.protocol.ver1.PcepFecObjectIPv4UnnumberedAdjacencyVer1.getVersion().
The documentation for this enum was generated from the following file:
protocols/pcep/pcepio/src/main/java/org/onosproject/pcepio/protocol/PcepVersion.java