onos: org.onosproject.ovsdb.rfc.table.Port.PortColumn Enum Reference
org.onosproject.ovsdb.rfc.table.Port.PortColumn Enum Reference
Port table column name.
Public Member Functions
String columnName ()
Returns the table column name for PortColumn.
Public Attributes
NAME =("name")
INTERFACES =("interfaces")
TRUNKS =("trunks")
TAG =("tag")
VLANMODE =("vlan_mode")
QOS =("qos")
MAC =("mac")
BONDTYPE =("bond_type")
BONDMODE =("bond_mode")
LACP =("lacp")
BONDUPDELAY =("bond_updelay")
BONDDOWNDELAY =("bond_downdelay")
BONDFAKEIFACE =("bond_fake_iface")
FAKEBRIDGE =("fake_bridge")
STATUS =("status")
STATISTICS =("statistics")
OTHERCONFIG =("other_config")
EXTERNALIDS =("external_ids")
Detailed Description
Port table column name.
Definition at line 36 of file Port.java.
Member Function Documentation
String org.onosproject.ovsdb.rfc.table.Port.PortColumn.columnName ()
Returns the table column name for PortColumn.
Returns
the table column name
Definition at line 54 of file Port.java.
Member Data Documentation
org.onosproject.ovsdb.rfc.table.Port.PortColumn.BONDDOWNDELAY =("bond_downdelay")
Definition at line 40 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getBondDownDelayColumn(), and org.onosproject.ovsdb.rfc.table.Port.setBondDownDelay().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.BONDFAKEIFACE =("bond_fake_iface")
Definition at line 40 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getBondFakeInterfaceColumn(), and org.onosproject.ovsdb.rfc.table.Port.setBondFakeInterface().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.BONDMODE =("bond_mode")
Definition at line 39 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getBondModeColumn(), and org.onosproject.ovsdb.rfc.table.Port.setBondMode().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.BONDTYPE =("bond_type")
Definition at line 38 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getBondTypeColumn(), and org.onosproject.ovsdb.rfc.table.Port.setBondType().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.BONDUPDELAY =("bond_updelay")
Definition at line 39 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getBondUpDelayColumn(), and org.onosproject.ovsdb.rfc.table.Port.setBondUpDelay().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.EXTERNALIDS =("external_ids")
Definition at line 42 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getExternalIdsColumn(), and org.onosproject.ovsdb.rfc.table.Port.setExternalIds().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.FAKEBRIDGE =("fake_bridge")
Definition at line 41 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getFakeBridgeColumn(), and org.onosproject.ovsdb.rfc.table.Port.setFakeBridge().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.INTERFACES =("interfaces")
Definition at line 37 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getInterfacesColumn(), and org.onosproject.ovsdb.rfc.table.Port.setInterfaces().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.LACP =("lacp")
Definition at line 39 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getLacpColumn(), and org.onosproject.ovsdb.rfc.table.Port.setLacp().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.MAC =("mac")
Definition at line 38 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getMacColumn(), and org.onosproject.ovsdb.rfc.table.Port.setMac().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.NAME =("name")
Definition at line 37 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getName(), org.onosproject.ovsdb.rfc.table.Port.getNameColumn(), and org.onosproject.ovsdb.rfc.table.Port.setName().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.OTHERCONFIG =("other_config")
Definition at line 42 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getOtherConfigColumn(), and org.onosproject.ovsdb.rfc.table.Port.setOtherConfig().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.QOS =("qos")
Definition at line 38 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getQosColumn(), and org.onosproject.ovsdb.rfc.table.Port.setQos().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.STATISTICS =("statistics")
Definition at line 41 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getStatisticsColumn(), and org.onosproject.ovsdb.rfc.table.Port.setStatistics().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.STATUS =("status")
Definition at line 41 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getStatusColumn(), and org.onosproject.ovsdb.rfc.table.Port.setStatus().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.TAG =("tag")
Definition at line 37 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getTagColumn(), and org.onosproject.ovsdb.rfc.table.Port.setTag().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.TRUNKS =("trunks")
Definition at line 37 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getTrunksColumn(), and org.onosproject.ovsdb.rfc.table.Port.setTrunks().
org.onosproject.ovsdb.rfc.table.Port.PortColumn.VLANMODE =("vlan_mode")
Definition at line 38 of file Port.java.
Referenced by org.onosproject.ovsdb.rfc.table.Port.getVlanModeColumn(), and org.onosproject.ovsdb.rfc.table.Port.setVlanMode().
The documentation for this enum was generated from the following file:
protocols/ovsdb/rfc/src/main/java/org/onosproject/ovsdb/rfc/table/Port.java