onos: org.onosproject.ui.table.CellFormatter Interface Reference
org.onosproject.ui.table.CellFormatter Interface Reference
Defines a formatter for cell values.
Public Member Functions
String format (Object value)
Formats the specified value into a string appropriate for displaying in a table cell.
Detailed Description
Defines a formatter for cell values.
Definition at line 22 of file CellFormatter.java.
Member Function Documentation
String org.onosproject.ui.table.CellFormatter.format (Object value)
Formats the specified value into a string appropriate for displaying in a table cell.
Note that null values are acceptable, and will result in the empty string.
Parameters
value the value
Returns
the formatted string
Implemented in org.onosproject.ui.table.cell.AbstractCellFormatter.
Referenced by org.onosproject.ui.table.cell.ConnectPointFormatterTest.basic(), org.onosproject.ui.table.cell.HostLocationFormatterTest.basic(), org.onosproject.ui.table.cell.AppIdFormatterTest.basic(), org.onosproject.ui.table.cell.TimeFormatterTest.basic(), org.onosproject.ui.table.cell.DefaultCellFormatterTest.formatFalse(), org.onosproject.ui.table.cell.DefaultCellFormatterTest.formatInteger(), org.onosproject.ui.table.cell.DefaultCellFormatterTest.formatNull(), org.onosproject.ui.table.cell.DefaultCellFormatterTest.formatObject(), org.onosproject.ui.table.cell.DefaultCellFormatterTest.formatString(), org.onosproject.ui.table.cell.DefaultCellFormatterTest.formatTrue(), org.onosproject.ui.table.cell.EnumFormatterTest.multiUnderscores(), org.onosproject.ui.table.cell.AbstractCellFormatterTest.nonNullInput(), org.onosproject.ui.table.cell.EnumFormatterTest.noUnderscores(), org.onosproject.ui.table.cell.AbstractCellFormatterTest.nullInput(), org.onosproject.ui.table.cell.HexFormatterTest.nullValue(), org.onosproject.ui.table.cell.EnumFormatterTest.nullValue(), org.onosproject.ui.table.cell.HexFormatterTest.one(), org.onosproject.ui.table.cell.HexFormatterTest.ten(), org.onosproject.ui.table.cell.HexFormatterTest.twenty(), org.onosproject.ui.table.cell.EnumFormatterTest.underscores(), and org.onosproject.ui.table.cell.HexFormatterTest.zero().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/ui/table/CellFormatter.java