onos: org.onosproject.app.ApplicationService Interface Reference
org.onosproject.app.ApplicationService Interface Reference
Service for inspecting inventory of network control applications.
Public Member Functions
Set< Application > getApplications ()
Returns the set of all installed applications.
ApplicationId getId (String name)
Returns the registered id of the application with the given name.
Application getApplication (ApplicationId appId)
Returns the application with the supplied application identifier.
ApplicationState getState (ApplicationId appId)
Return the application state.
Set< Permission > getPermissions (ApplicationId appId)
Returns the permissions currently granted to the applications.
void registerDeactivateHook (ApplicationId appId, Runnable hook)
Registers application pre-deactivation processing hook.
Detailed Description
Service for inspecting inventory of network control applications.
Definition at line 28 of file ApplicationService.java.
Member Function Documentation
Application org.onosproject.app.ApplicationService.getApplication (ApplicationId appId)
Returns the application with the supplied application identifier.
Parameters
appId application identifier
Returns
application descriptor
Implemented in org.onosproject.app.impl.ApplicationManager, org.onosproject.app.ApplicationServiceAdapter, and org.onosproject.app.ApplicationAdminServiceAdapter.
Referenced by org.onosproject.rest.ApplicationsResourceTest.setUpMocks().
Set<Application> org.onosproject.app.ApplicationService.getApplications ()
Returns the set of all installed applications.
Returns
set of installed apps
Implemented in org.onosproject.app.impl.ApplicationManager, org.onosproject.app.ApplicationAdminServiceAdapter, and org.onosproject.app.ApplicationServiceAdapter.
Referenced by org.onosproject.cli.app.ApplicationsListCommand.execute(), org.onosproject.rest.ApplicationsResourceTest.getAllApplicationsEmpty(), and org.onosproject.rest.ApplicationsResourceTest.getAllApplicationsPopulated().
ApplicationId org.onosproject.app.ApplicationService.getId (String name)
Returns the registered id of the application with the given name.
Parameters
name application name
Returns
registered application id
Implemented in org.onosproject.app.impl.ApplicationManager, and org.onosproject.app.ApplicationServiceAdapter.
Referenced by metro.FabricDomain.build(), and org.onosproject.rest.ApplicationsResourceTest.setUpMocks().
Set<Permission> org.onosproject.app.ApplicationService.getPermissions (ApplicationId appId)
Returns the permissions currently granted to the applications.
Parameters
appId application identifier
Returns
set of granted permissions
Implemented in org.onosproject.app.impl.ApplicationManager, org.onosproject.app.ApplicationServiceAdapter, and org.onosproject.app.ApplicationAdminServiceAdapter.
ApplicationState org.onosproject.app.ApplicationService.getState (ApplicationId appId)
Return the application state.
Parameters
appId application identifier
Returns
application state
Implemented in org.onosproject.app.impl.ApplicationManager, org.onosproject.app.ApplicationServiceAdapter, and org.onosproject.app.ApplicationAdminServiceAdapter.
Referenced by org.onosproject.rest.ApplicationsResourceTest.setUpMocks().
void org.onosproject.app.ApplicationService.registerDeactivateHook (ApplicationId appId, Runnable hook)
Registers application pre-deactivation processing hook.
Parameters
appId application identifier
hook pre-deactivation hook
Implemented in org.onosproject.app.impl.ApplicationManager, and org.onosproject.app.ApplicationServiceAdapter.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/app/ApplicationService.java