onos: org.onosproject.net.flowobjective.ForwardingObjective Interface Reference
org.onosproject.net.flowobjective.ForwardingObjective Interface Reference
Represents a description of which types of traffic need to be forwarded through the device.
Classes
interface Builder
A forwarding objective builder.
enum Flag
Represents whether this objective is monolithic or may be broken down into parts.
Public Member Functions
TrafficSelector selector ()
Obtain the selector for this objective.
Integer nextId ()
Obtain the traffic treatment for this objective.
TrafficTreatment treatment ()
A traffic treatment for this forwarding objective.
Flag flag ()
Obtain the type of this objective.
Public Member Functions inherited from org.onosproject.net.flowobjective.Objective
int id ()
An identifier for this objective.
int priority ()
The priority for this objective.
ApplicationId appId ()
The application which applied this objective.
int timeout ()
The timeout for this objective.
boolean permanent ()
Whether this objective is permanent.
Operation op ()
The type of operation for this objective.
Optional< ObjectiveContext > context ()
Obtains an optional context.
Additional Inherited Members
Public Attributes inherited from org.onosproject.net.flowobjective.Objective
boolean DEFAULT_PERMANENT = true
int DEFAULT_TIMEOUT = 0
int DEFAULT_PRIORITY = 32768
Detailed Description
Represents a description of which types of traffic need to be forwarded through the device.
A forwarding objective may result in multiple rules at the device. There are two main types of forwarding objectives:
Versatile
Specific
A versatile forwarding objective represents a composite rule that matches two or more header fields. The use of versatile usually indicates that this rule should be inserted in its entirety into the ACL table. Although, drivers for some devices are free to implement this differently.
A specific forwarding objective represents a specific rule matching one or more header fields. The installation of this rule may result in several rules at the device. For example, one per table type.
Definition at line 41 of file ForwardingObjective.java.
Member Function Documentation
Flag org.onosproject.net.flowobjective.ForwardingObjective.flag ()
Obtain the type of this objective.
Returns
a flag type
Implemented in org.onosproject.net.flowobjective.DefaultForwardingObjective.
Referenced by org.onosproject.driver.pipeline.DefaultSingleTablePipeline.forward(), org.onosproject.driver.pipeline.OltPipeline.forward(), and org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardingObjectiveHash().
Integer org.onosproject.net.flowobjective.ForwardingObjective.nextId ()
Obtain the traffic treatment for this objective.
Mutually exclusive with 'treatment'.
Returns
an integer
Implemented in org.onosproject.net.flowobjective.DefaultForwardingObjective.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), org.onosproject.driver.pipeline.SpringOpenTTP.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
TrafficSelector org.onosproject.net.flowobjective.ForwardingObjective.selector ()
Obtain the selector for this objective.
Returns
a traffic selector
Implemented in org.onosproject.net.flowobjective.DefaultForwardingObjective.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeParallel(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeSequential(), and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionManager.forwardingObjectiveToString().
TrafficTreatment org.onosproject.net.flowobjective.ForwardingObjective.treatment ()
A traffic treatment for this forwarding objective.
Mutually exclusive with a nextId.
Returns
a traffic treatment
Implemented in org.onosproject.net.flowobjective.DefaultForwardingObjective.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeParallel(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeSequential(), org.onosproject.driver.pipeline.DefaultSingleTablePipeline.forward(), org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardingObjectiveHash(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionManager.forwardingObjectiveToString(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/flowobjective/ForwardingObjective.java