onos: org.onosproject.store.consistent.impl.Database Interface Reference
org.onosproject.store.consistent.impl.Database Interface Reference
Database.
Public Member Functions
default boolean hasChangeNotificationSupport ()
Tells whether the database supports change notifications.
void registerConsumer (Consumer< StateMachineUpdate > consumer)
Registers a new consumer of StateMachineUpdates.
void unregisterConsumer (Consumer< StateMachineUpdate > consumer)
Unregisters a consumer of StateMachineUpdates.
Static Public Member Functions
static Database create (String name)
Creates a new database with the default cluster configuration.
static Database create (String name, ClusterConfig cluster)
Creates a new database.
static Database create (String name, ClusterConfig cluster, DatabaseConfig config)
Creates a new database.
Detailed Description
Database.
Definition at line 31 of file Database.java.
Member Function Documentation
static Database org.onosproject.store.consistent.impl.Database.create (String name) static
Creates a new database with the default cluster configuration.
The database will be constructed with the default cluster configuration. The default cluster configuration searches for two resources on the classpath -
cluster
and {cluster-defaults} - in that order. Configuration options specified in
cluster.conf
will override those in {cluster-defaults.conf}.
Additionally, the database will be constructed with an database configuration that searches the classpath for three configuration files -
name
,
database
,
database-defaults
,
resource
, and
resource-defaults
- in that order. The first resource is a configuration resource with the same name as the map resource. If the resource is namespaced - e.g. databases.my-database.conf - then resource configurations will be loaded according to namespaces as well; for example, databases.conf.
Parameters
name The database name.
Returns
The database.
Definition at line 49 of file Database.java.
Referenced by org.onosproject.store.consistent.impl.Database.create().
static Database org.onosproject.store.consistent.impl.Database.create (String name, ClusterConfig cluster) static
Creates a new database.
The database will be constructed with an database configuration that searches the classpath for three configuration files -
name
,
database
,
database-defaults
,
resource
, and
resource-defaults
- in that order. The first resource is a configuration resource with the same name as the database resource. If the resource is namespaced - e.g. databases.my-database.conf - then resource configurations will be loaded according to namespaces as well; for example, databases.conf.
Parameters
name The database name.
cluster The cluster configuration.
Returns
The database.
Definition at line 66 of file Database.java.
References org.onosproject.store.consistent.impl.Database.create().
static Database org.onosproject.store.consistent.impl.Database.create (String name, ClusterConfig cluster, DatabaseConfig config) static
Creates a new database.
Parameters
name The database name.
cluster The cluster configuration.
config The database configuration.
Returns
The database.
Definition at line 79 of file Database.java.
References org.onosproject.store.consistent.impl.DatabaseConfig.resolve().
default boolean org.onosproject.store.consistent.impl.Database.hasChangeNotificationSupport ()
Tells whether the database supports change notifications.
Returns
true if notifications are supported; false otherwise
Definition at line 91 of file Database.java.
void org.onosproject.store.consistent.impl.Database.registerConsumer (Consumer< StateMachineUpdate > consumer)
Registers a new consumer of StateMachineUpdates.
Parameters
consumer consumer to register
Implemented in org.onosproject.store.consistent.impl.PartitionedDatabase, and org.onosproject.store.consistent.impl.DefaultDatabase.
void org.onosproject.store.consistent.impl.Database.unregisterConsumer (Consumer< StateMachineUpdate > consumer)
Unregisters a consumer of StateMachineUpdates.
Parameters
consumer consumer to unregister
Implemented in org.onosproject.store.consistent.impl.PartitionedDatabase, and org.onosproject.store.consistent.impl.DefaultDatabase.
The documentation for this interface was generated from the following file:
core/store/dist/src/main/java/org/onosproject/store/consistent/impl/Database.java