onos: org.onosproject.vtnrsc.PortPair Interface Reference
org.onosproject.vtnrsc.PortPair Interface Reference
Abstraction of an entity providing Port Pair information.
Classes
interface Builder
A port pair builder.
Public Member Functions
PortPairId portPairId ()
Returns the ID of this port Pair.
TenantId tenantId ()
Returns the tenant id of this port pair.
String name ()
Returns the description of this port pair.
String description ()
Returns the description of this port pair.
String ingress ()
Returns the ingress port of this port pair.
String egress ()
Returns the egress port of this port pair.
boolean exactMatch (PortPair portPair)
Returns whether this port pair is an exact match to the port pair given in the argument.
Detailed Description
Abstraction of an entity providing Port Pair information.
A port pair represents a service function instance.
Definition at line 23 of file PortPair.java.
Member Function Documentation
String org.onosproject.vtnrsc.PortPair.description ()
Returns the description of this port pair.
Returns
description of port pair
Implemented in org.onosproject.vtnrsc.DefaultPortPair.
Referenced by org.onosproject.vtnweb.web.PortPairCodecTest.codecPortPairTest().
String org.onosproject.vtnrsc.PortPair.egress ()
Returns the egress port of this port pair.
Returns
egress of port pair
Implemented in org.onosproject.vtnrsc.DefaultPortPair.
Referenced by org.onosproject.vtnweb.web.PortPairCodecTest.codecPortPairTest().
boolean org.onosproject.vtnrsc.PortPair.exactMatch (PortPair portPair)
Returns whether this port pair is an exact match to the port pair given in the argument.
Exact match means the Port port pairs match with the given port pair. It does not consider the port pair id, name and description.
Parameters
portPair other port pair to match against
Returns
true if the port pairs are an exact match, otherwise false
Implemented in org.onosproject.vtnrsc.DefaultPortPair.
String org.onosproject.vtnrsc.PortPair.ingress ()
Returns the ingress port of this port pair.
Returns
ingress of port pair
Implemented in org.onosproject.vtnrsc.DefaultPortPair.
Referenced by org.onosproject.vtnweb.web.PortPairCodecTest.codecPortPairTest().
String org.onosproject.vtnrsc.PortPair.name ()
Returns the description of this port pair.
Returns
description of port pair
Implemented in org.onosproject.vtnrsc.DefaultPortPair.
Referenced by org.onosproject.vtnweb.web.PortPairCodecTest.codecPortPairTest(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
PortPairId org.onosproject.vtnrsc.PortPair.portPairId ()
Returns the ID of this port Pair.
Returns
the port pair id
Implemented in org.onosproject.vtnrsc.DefaultPortPair.
Referenced by org.onosproject.vtnweb.web.PortPairCodecTest.codecPortPairTest(), org.onosproject.vtnrsc.portpair.impl.PortPairManager.createPortPair(), org.onosproject.vtnrsc.DefaultPortPair.exactMatch(), and org.onosproject.vtnrsc.portpair.impl.PortPairManager.updatePortPair().
TenantId org.onosproject.vtnrsc.PortPair.tenantId ()
Returns the tenant id of this port pair.
Returns
an tenant id
Implemented in org.onosproject.vtnrsc.DefaultPortPair.
Referenced by org.onosproject.vtnweb.web.PortPairCodecTest.codecPortPairTest(), org.onosproject.vtnweb.web.PortPairCodec.encode(), and org.onosproject.vtnrsc.DefaultPortPair.exactMatch().
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/PortPair.java