onos: org.onosproject.incubator.net.tunnel.TunnelDescription Interface Reference
org.onosproject.incubator.net.tunnel.TunnelDescription Interface Reference
Describes a tunnel.
Public Member Functions
TunnelId id ()
Returns the tunnel id.
TunnelEndPoint src ()
Returns the connection point source.
TunnelEndPoint dst ()
Returns the connection point destination.
Type type ()
Returns the tunnel type.
DefaultGroupId groupId ()
Returns group flow table id which a tunnel match up.
ProviderId producerName ()
Returns tunnel producer name.
TunnelName tunnelName ()
Return the name of a tunnel.
Path path ()
Returns the path of the tunnel.
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Detailed Description
Describes a tunnel.
Definition at line 30 of file TunnelDescription.java.
Member Function Documentation
TunnelEndPoint org.onosproject.incubator.net.tunnel.TunnelDescription.dst ()
Returns the connection point destination.
Returns
tunnel destination
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelAdded().
DefaultGroupId org.onosproject.incubator.net.tunnel.TunnelDescription.groupId ()
Returns group flow table id which a tunnel match up.
Returns
OpenFlowGroupId
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.
TunnelId org.onosproject.incubator.net.tunnel.TunnelDescription.id ()
Returns the tunnel id.
Returns
tunnelId
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelRemoved(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelUpdated().
Path org.onosproject.incubator.net.tunnel.TunnelDescription.path ()
Returns the path of the tunnel.
Returns
the path of the tunnel
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.
ProviderId org.onosproject.incubator.net.tunnel.TunnelDescription.producerName ()
Returns tunnel producer name.
Returns
producer name
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.
TunnelEndPoint org.onosproject.incubator.net.tunnel.TunnelDescription.src ()
Returns the connection point source.
Returns
tunnel source ConnectionPoint
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.
TunnelName org.onosproject.incubator.net.tunnel.TunnelDescription.tunnelName ()
Return the name of a tunnel.
Returns
Tunnel Name
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.
Type org.onosproject.incubator.net.tunnel.TunnelDescription.type ()
Returns the tunnel type.
Returns
tunnel type
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnelDescription.
Referenced by org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelAdded(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelRemoved(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelUpdated().
The documentation for this interface was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/tunnel/TunnelDescription.java