onos: org.onosproject.net.flow.FlowRule Interface Reference
org.onosproject.net.flow.FlowRule Interface Reference
Represents a generalized match & action pair to be applied to an infrastructure device.
Classes
interface Builder
A flowrule builder.
Public Member Functions
FlowId id ()
Returns the ID of this flow.
short appId ()
Returns the application id of this flow.
GroupId groupId ()
Returns the group id of this flow.
int priority ()
Returns the flow rule priority given in natural order; higher numbers mean higher priorities.
DeviceId deviceId ()
Returns the identity of the device where this rule applies.
TrafficSelector selector ()
Returns the traffic selector that identifies what traffic this rule should apply to.
TrafficTreatment treatment ()
Returns the traffic treatment that applies to selected traffic.
int timeout ()
Returns the timeout for this flow requested by an application.
boolean isPermanent ()
Returns whether the flow is permanent i.e.
int tableId ()
Returns the table id for this rule.
boolean equals (Object obj)
boolean exactMatch (FlowRule rule)
Returns whether this flow rule is an exact match to the flow rule given in the argument.
FlowRuleExtPayLoad payLoad ()
Returns the third party original flow rule.
Public Attributes
int MAX_TIMEOUT = 60
int MIN_PRIORITY = 0
Detailed Description
Represents a generalized match & action pair to be applied to an infrastructure device.
Definition at line 26 of file FlowRule.java.
Member Function Documentation
short org.onosproject.net.flow.FlowRule.appId ()
Returns the application id of this flow.
Returns
an applicationId
Implemented in org.onosproject.net.flow.DefaultFlowRule.
Referenced by org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule().
DeviceId org.onosproject.net.flow.FlowRule.deviceId ()
Returns the identity of the device where this rule applies.
Returns
device identifier
Implemented in org.onosproject.net.flow.DefaultFlowRule.
Referenced by org.onosproject.store.trivial.SimpleFlowRuleStore.addOrUpdateFlowRule(), org.onosproject.store.trivial.SimpleFlowRuleStore.deleteFlowRule(), org.onosproject.codec.impl.FlowEntryCodec.encode(), org.onosproject.store.trivial.SimpleFlowRuleStore.getFlowEntry(), org.onosproject.store.trivial.SimpleFlowRuleStore.storeBatch(), org.onosproject.net.intent.impl.compiler.MplsPathIntentCompilerTest.testCompile(), org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest.testCompile(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithAppId(), and org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithFlowId().
boolean org.onosproject.net.flow.FlowRule.equals (Object obj)
Equality for flow rules only considers 'match equality'. This means that two flow rules with the same match conditions will be equal, regardless of the treatment or other characteristics of the flow.
Parameters
obj the reference object with which to compare.
Returns
true
if this object is the same as the obj argument;
false
otherwise.
Implemented in org.onosproject.net.flow.DefaultFlowRule.
Referenced by org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.updateFlowStatistic().
boolean org.onosproject.net.flow.FlowRule.exactMatch (FlowRule rule)
Returns whether this flow rule is an exact match to the flow rule given in the argument.
Exact match means that deviceId, priority, selector, tableId, flowId and treatment are equal. Note that this differs from the notion of object equality for flow rules, which does not consider the flowId or treatment when testing equality.
Parameters
rule other rule to match against
Returns
true if the rules are an exact match, otherwise false
Implemented in org.onosproject.net.flow.DefaultFlowRule.
GroupId org.onosproject.net.flow.FlowRule.groupId ()
Returns the group id of this flow.
Returns
an groupId
Implemented in org.onosproject.net.flow.DefaultFlowRule.
FlowId org.onosproject.net.flow.FlowRule.id ()
Returns the ID of this flow.
Returns
the flow ID
Implemented in org.onosproject.net.flow.DefaultFlowRule.
Referenced by org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.addOrUpdateFlows(), org.onosproject.net.flow.DefaultFlowRule.exactMatch(), org.onosproject.store.trivial.SimpleFlowRuleStore.removeFlowRule(), and org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule().
boolean org.onosproject.net.flow.FlowRule.isPermanent ()
Returns whether the flow is permanent i.e.
does not time out.
Returns
true if the flow is permanent, otherwise false
Implemented in org.onosproject.net.flow.DefaultFlowRule.
Referenced by org.onosproject.codec.impl.FlowEntryCodec.encode(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithAppId(), and org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithFlowId().
FlowRuleExtPayLoad org.onosproject.net.flow.FlowRule.payLoad ()
Returns the third party original flow rule.
Returns
FlowRuleExtPayLoad
Implemented in org.onosproject.net.flow.DefaultFlowRule.
Referenced by org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule().
int org.onosproject.net.flow.FlowRule.priority ()
Returns the flow rule priority given in natural order; higher numbers mean higher priorities.
Returns
flow rule priority
Implemented in org.onosproject.net.flow.DefaultFlowRule.
Referenced by org.onosproject.codec.impl.FlowEntryCodec.encode(), org.onosproject.net.intent.impl.compiler.LinkCollectionIntentCompilerTest.testCompile(), org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest.testCompile(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithAppId(), and org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithFlowId().
TrafficSelector org.onosproject.net.flow.FlowRule.selector ()
Returns the traffic selector that identifies what traffic this rule should apply to.
Returns
traffic selector
Implemented in org.onosproject.net.flow.DefaultFlowRule.
Referenced by org.onosproject.codec.impl.FlowRuleCodecTest.codecCriteriaFlowTest(), org.onosproject.codec.impl.FlowRuleCodecTest.codecSigIdCriteriaFlowTest(), org.onosproject.codec.impl.FlowRuleCodecTest.codecSimpleFlowTest(), org.onosproject.codec.impl.FlowEntryCodec.encode(), org.onosproject.flowanalyzer.FlowAnalyzer.flowEntryRepresentation(), org.onosproject.net.intent.impl.compiler.LinkCollectionIntentCompilerTest.testCompile(), org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest.testCompile(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithAppId(), and org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithFlowId().
int org.onosproject.net.flow.FlowRule.tableId ()
Returns the table id for this rule.
Returns
an integer.
Implemented in org.onosproject.net.flow.DefaultFlowRule.
int org.onosproject.net.flow.FlowRule.timeout ()
Returns the timeout for this flow requested by an application.
Returns
integer value of the timeout
Implemented in org.onosproject.net.flow.DefaultFlowRule.
Referenced by org.onosproject.codec.impl.FlowEntryCodec.encode(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithAppId(), and org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithFlowId().
TrafficTreatment org.onosproject.net.flow.FlowRule.treatment ()
Returns the traffic treatment that applies to selected traffic.
Returns
traffic treatment
Implemented in org.onosproject.net.flow.DefaultFlowRule.
Referenced by org.onosproject.codec.impl.FlowRuleCodecTest.codecSimpleFlowTest(), org.onosproject.codec.impl.FlowRuleCodecTest.decodeInstructionsFlowTest(), org.onosproject.codec.impl.FlowEntryCodec.encode(), org.onosproject.net.flow.DefaultFlowRule.exactMatch(), org.onosproject.flowanalyzer.FlowAnalyzer.flowEntryRepresentation(), org.onosproject.net.intent.impl.compiler.LinkCollectionIntentCompilerTest.testCompile(), org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest.testCompile(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationFromFlowRule(), org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithAppId(), and org.onosproject.net.flow.DefaultFlowRuleTest.testCreationWithFlowId().
Member Data Documentation
int org.onosproject.net.flow.FlowRule.MAX_TIMEOUT = 60
Definition at line 28 of file FlowRule.java.
int org.onosproject.net.flow.FlowRule.MIN_PRIORITY = 0
Definition at line 29 of file FlowRule.java.
Referenced by org.onosproject.net.flow.DefaultFlowRule.DefaultFlowRule().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/FlowRule.java