onos: org.onosproject.vtnrsc.Router Interface Reference
org.onosproject.vtnrsc.Router Interface Reference
Representation of a Router.
Classes
enum Status
Coarse classification of the type of the Router.
Public Member Functions
RouterId id ()
Returns the router identifier.
String name ()
Returns the router Name.
boolean adminStateUp ()
Returns the router admin state.
Status status ()
Returns the status of router.
boolean distributed ()
Returns the distributed status of this router.
RouterGateway externalGatewayInfo ()
Returns the RouterGateway of router.
VirtualPortId gatewayPortid ()
Returns the gatewayPortid of router.
TenantId tenantId ()
Returns the owner(tenant) of this router.
List< String > routes ()
Returns the router list of router.
Detailed Description
Representation of a Router.
Definition at line 23 of file Router.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.Router.adminStateUp ()
Returns the router admin state.
Returns
true or false
Implemented in org.onosproject.vtnrsc.DefaultRouter.
Referenced by org.onosproject.vtnweb.web.RouterCodec.encode().
boolean org.onosproject.vtnrsc.Router.distributed ()
Returns the distributed status of this router.
If true, indicates a distributed router.
Returns
true or false
Implemented in org.onosproject.vtnrsc.DefaultRouter.
RouterGateway org.onosproject.vtnrsc.Router.externalGatewayInfo ()
Returns the RouterGateway of router.
Returns
routerGateway
Implemented in org.onosproject.vtnrsc.DefaultRouter.
Referenced by org.onosproject.vtnrsc.router.DefaultRouterTest.testConstruction().
VirtualPortId org.onosproject.vtnrsc.Router.gatewayPortid ()
Returns the gatewayPortid of router.
Returns
virtualPortId
Implemented in org.onosproject.vtnrsc.DefaultRouter.
RouterId org.onosproject.vtnrsc.Router.id ()
Returns the router identifier.
Returns
identifier
Implemented in org.onosproject.vtnrsc.DefaultRouter.
Referenced by org.onosproject.vtnrsc.router.DefaultRouterTest.testConstruction().
String org.onosproject.vtnrsc.Router.name ()
Returns the router Name.
Returns
routerName
Implemented in org.onosproject.vtnrsc.DefaultRouter.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
List<String> org.onosproject.vtnrsc.Router.routes ()
Returns the router list of router.
Returns
routes
Implemented in org.onosproject.vtnrsc.DefaultRouter.
Referenced by org.onosproject.vtnweb.web.RouterCodec.encode().
Status org.onosproject.vtnrsc.Router.status ()
Returns the status of router.
Returns
RouterStatus
Implemented in org.onosproject.vtnrsc.DefaultRouter.
Referenced by org.onosproject.vtnweb.web.RouterCodec.encode().
TenantId org.onosproject.vtnrsc.Router.tenantId ()
Returns the owner(tenant) of this router.
Returns
tenantId
Implemented in org.onosproject.vtnrsc.DefaultRouter.
Referenced by org.onosproject.vtnweb.web.RouterCodec.encode(), and org.onosproject.vtnrsc.router.DefaultRouterTest.testConstruction().
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/Router.java