onos: org.onosproject.mastership.MastershipService Interface Reference
org.onosproject.mastership.MastershipService Interface Reference
Service responsible for determining the controller instance mastership of a device in a clustered environment.
Public Member Functions
MastershipRole getLocalRole (DeviceId deviceId)
Returns the role of the local node for the specified device, without triggering master selection.
default boolean isLocalMaster (DeviceId deviceId)
Returns true if the local controller is the Master for the specified deviceId.
CompletableFuture< MastershipRole > requestRoleFor (DeviceId deviceId)
Returns the mastership status of the local controller for a given device forcing master selection if necessary.
CompletableFuture< Void > relinquishMastership (DeviceId deviceId)
Abandons mastership of the specified device on the local node thus forcing selection of a new master.
NodeId getMasterFor (DeviceId deviceId)
Returns the current master for a given device.
RoleInfo getNodesFor (DeviceId deviceId)
Returns controllers connected to a given device, in order of preference.
Set< DeviceId > getDevicesOf (NodeId nodeId)
Returns the devices for which a controller is master.
Detailed Description
Service responsible for determining the controller instance mastership of a device in a clustered environment.
This is the central authority for determining mastership, but is not responsible for actually applying it to the devices; this falls on the device service.
Definition at line 35 of file MastershipService.java.
Member Function Documentation
Set<DeviceId> org.onosproject.mastership.MastershipService.getDevicesOf (NodeId nodeId)
Returns the devices for which a controller is master.
Parameters
nodeId the ID of the controller
Returns
a set of device IDs
Implemented in org.onosproject.cluster.impl.MastershipManager, and org.onosproject.mastership.MastershipServiceAdapter.
MastershipRole org.onosproject.mastership.MastershipService.getLocalRole (DeviceId deviceId)
Returns the role of the local node for the specified device, without triggering master selection.
Parameters
deviceId the the identifier of the device
Returns
role of the current node
Implemented in org.onosproject.cluster.impl.MastershipManager, and org.onosproject.mastership.MastershipServiceAdapter.
Referenced by org.onosproject.mastership.MastershipService.isLocalMaster(), and org.onosproject.store.group.impl.DistributedGroupStore.storeGroupDescription().
NodeId org.onosproject.mastership.MastershipService.getMasterFor (DeviceId deviceId)
Returns the current master for a given device.
Parameters
deviceId the identifier of the device
Returns
the ID of the master controller for the device
Implemented in org.onosproject.cluster.impl.MastershipManager, and org.onosproject.mastership.MastershipServiceAdapter.
Referenced by org.onosproject.store.group.impl.DistributedGroupStore.deleteGroupDescription(), org.onosproject.store.group.impl.DistributedGroupStore.storeGroupDescription(), and org.onosproject.store.group.impl.DistributedGroupStore.updateGroupDescription().
RoleInfo org.onosproject.mastership.MastershipService.getNodesFor (DeviceId deviceId)
Returns controllers connected to a given device, in order of preference.
The first entry in the list is the current master.
Parameters
deviceId the identifier of the device
Returns
a list of controller IDs
Implemented in org.onosproject.cluster.impl.MastershipManager, and org.onosproject.mastership.MastershipServiceAdapter.
Referenced by org.onosproject.store.flow.impl.ReplicaInfoManager.getReplicaInfoFor().
default boolean org.onosproject.mastership.MastershipService.isLocalMaster (DeviceId deviceId)
Returns true if the local controller is the Master for the specified deviceId.
Parameters
deviceId the the identifier of the device
Returns
true if local node is master; false otherwise
Definition at line 53 of file MastershipService.java.
References org.onosproject.mastership.MastershipService.getLocalRole().
Referenced by org.onosproject.vtn.manager.impl.VTNManager.onControllerDetected(), org.onosproject.vtn.manager.impl.VTNManager.onControllerVanished(), org.onosproject.segmentrouting.DefaultRoutingHandler.populateAllRoutingRules(), org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterIpPunts(), org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterMacVlanFilters(), and org.onosproject.segmentrouting.DefaultRoutingHandler.populateRoutingRulesForLinkStatusChange().
CompletableFuture<Void> org.onosproject.mastership.MastershipService.relinquishMastership (DeviceId deviceId)
Abandons mastership of the specified device on the local node thus forcing selection of a new master.
If the local node is not a master for this device, no master selection will occur.
Parameters
deviceId the identifier of the device
Returns
future that is completed when relinquish is complete
Implemented in org.onosproject.cluster.impl.MastershipManager, and org.onosproject.mastership.MastershipServiceAdapter.
CompletableFuture<MastershipRole> org.onosproject.mastership.MastershipService.requestRoleFor (DeviceId deviceId)
Returns the mastership status of the local controller for a given device forcing master selection if necessary.
Parameters
deviceId the the identifier of the device
Returns
the role of this controller instance
Implemented in org.onosproject.cluster.impl.MastershipManager, and org.onosproject.mastership.MastershipServiceAdapter.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/mastership/MastershipService.java