onos: org.onosproject.net.driver.Driver Interface Reference
org.onosproject.net.driver.Driver Interface Reference
Representation of a specific family of device drivers.
Public Member Functions
String name ()
Returns the driver name.
Driver parent ()
Returns the parent driver from which this driver inherits behaviours and properties.
String manufacturer ()
Returns the device manufacturer name.
String hwVersion ()
Returns the device hardware version.
String swVersion ()
Returns the device software version.
Set< Class<?extends Behaviour > > behaviours ()
Returns the set of behaviours supported by this driver.
Class<?extends Behaviour > implementation (Class<?extends Behaviour > behaviour)
Returns the implementation class for the specified behaviour.
boolean hasBehaviour (Class<?extends Behaviour > behaviourClass)
Indicates whether or not the driver, or any of its parents, support the specified class of behaviour.
< TextendsBehaviour > T createBehaviour (DriverData data, Class< T > behaviourClass)
Creates an instance of behaviour primed with the specified driver data.
< TextendsBehaviour > T createBehaviour (DriverHandler handler, Class< T > behaviourClass)
Creates an instance of behaviour primed with the specified driver data.
Map< String, String > properties ()
Returns the set of annotations as map of key/value properties.
Driver merge (Driver other)
Merges the specified driver behaviours and properties into this one, giving preference to the other driver when dealing with conflicts.
Public Member Functions inherited from org.onosproject.net.Annotations
Set< String > keys ()
Returns the set of keys for available annotations.
String value (String key)
Returns the value of the specified annotation.
Detailed Description
Representation of a specific family of device drivers.
Behaviour configuration data is stored using org.onosproject.net.Annotations.
Definition at line 27 of file Driver.java.
Member Function Documentation
Set<Class<? extends Behaviour> > org.onosproject.net.driver.Driver.behaviours ()
Returns the set of behaviours supported by this driver.
It reflects behaviours of only this driver and not its parent.
Returns
set of device driver behaviours
Implemented in org.onosproject.net.driver.DefaultDriver, and org.onosproject.openflow.DriverAdapter.
Referenced by org.onosproject.net.driver.XmlDriverLoaderTest.basics(), and org.onosproject.net.driver.DefaultDriverTest.merge().
<TextendsBehaviour> T org.onosproject.net.driver.Driver.createBehaviour (DriverData data, Class< T > behaviourClass)
Creates an instance of behaviour primed with the specified driver data.
If the current driver does not support the specified behaviour and the driver has parent, the request is delegated to the parent driver.
Parameters
data driver data context
behaviourClass driver behaviour class
<T> type of behaviour
Returns
behaviour instance
<TextendsBehaviour> T org.onosproject.net.driver.Driver.createBehaviour (DriverHandler handler, Class< T > behaviourClass)
Creates an instance of behaviour primed with the specified driver data.
If the current driver does not support the specified behaviour and the driver has parent, the request is delegated to the parent driver.
Parameters
handler driver handler context
behaviourClass driver behaviour class
<T> type of behaviour
Returns
behaviour instance
boolean org.onosproject.net.driver.Driver.hasBehaviour (Class<?extends Behaviour > behaviourClass)
Indicates whether or not the driver, or any of its parents, support the specified class of behaviour.
It
Parameters
behaviourClass behaviour class
Returns
true if behaviour is supported
Implemented in org.onosproject.net.driver.DefaultDriver, and org.onosproject.openflow.DriverAdapter.
Referenced by org.onosproject.net.driver.XmlDriverLoaderTest.basics(), org.onosproject.openflow.controller.impl.Controller.getOFSwitchInstance(), org.onosproject.net.driver.DefaultDriver.hasBehaviour(), and org.onosproject.net.driver.DefaultDriverTest.merge().
String org.onosproject.net.driver.Driver.hwVersion ()
Returns the device hardware version.
Returns
hardware version
Implemented in org.onosproject.net.driver.DefaultDriver, and org.onosproject.openflow.DriverAdapter.
Referenced by org.onosproject.net.driver.XmlDriverLoaderTest.basics(), and org.onosproject.net.driver.DefaultDriverTest.merge().
Class<? extends Behaviour> org.onosproject.net.driver.Driver.implementation (Class<?extends Behaviour > behaviour)
Returns the implementation class for the specified behaviour.
It reflects behaviours of only this driver and not its parent.
Parameters
behaviour behaviour interface
Returns
implementation class
Implemented in org.onosproject.net.driver.DefaultDriver, and org.onosproject.openflow.DriverAdapter.
Referenced by org.onosproject.net.driver.DefaultDriver.merge().
String org.onosproject.net.driver.Driver.manufacturer ()
Returns the device manufacturer name.
Returns
manufacturer name
Implemented in org.onosproject.net.driver.DefaultDriver, and org.onosproject.openflow.DriverAdapter.
Referenced by org.onosproject.net.driver.XmlDriverLoaderTest.basics(), and org.onosproject.net.driver.DefaultDriverTest.merge().
Driver org.onosproject.net.driver.Driver.merge (Driver other)
Merges the specified driver behaviours and properties into this one, giving preference to the other driver when dealing with conflicts.
Parameters
other other driver
Returns
merged driver
Implemented in org.onosproject.openflow.DriverAdapter, and org.onosproject.net.driver.DefaultDriver.
Referenced by org.onosproject.net.driver.DefaultDriverProvider.addDriver().
String org.onosproject.net.driver.Driver.name ()
Returns the driver name.
This is expected to be a reverse-DNS, Java package-like name.
Returns
driver name
Implemented in org.onosproject.net.driver.DefaultDriver, and org.onosproject.openflow.DriverAdapter.
Referenced by org.onosproject.net.driver.XmlDriverLoaderTest.basics(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.net.driver.DefaultDriverTest.merge(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
Driver org.onosproject.net.driver.Driver.parent ()
Returns the parent driver from which this driver inherits behaviours and properties.
Returns
parent driver; null if driver has no parent
Implemented in org.onosproject.net.driver.DefaultDriver, and org.onosproject.openflow.DriverAdapter.
Referenced by org.onosproject.codec.impl.DriverCodec.encode(), and org.onosproject.net.driver.DefaultDriver.merge().
Map<String, String> org.onosproject.net.driver.Driver.properties ()
Returns the set of annotations as map of key/value properties.
Returns
map of properties
Implemented in org.onosproject.net.driver.DefaultDriver, and org.onosproject.openflow.DriverAdapter.
Referenced by org.onosproject.net.driver.XmlDriverLoaderTest.basics(), org.onosproject.codec.impl.DriverJsonMatcher.matchesSafely(), org.onosproject.net.driver.DefaultDriverTest.merge(), and org.onosproject.net.driver.DefaultDriver.merge().
String org.onosproject.net.driver.Driver.swVersion ()
Returns the device software version.
Returns
software version
Implemented in org.onosproject.net.driver.DefaultDriver, and org.onosproject.openflow.DriverAdapter.
Referenced by org.onosproject.net.driver.XmlDriverLoaderTest.basics(), and org.onosproject.net.driver.DefaultDriverTest.merge().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/driver/Driver.java