onos: org.onosproject.net.device.PortStatistics Interface Reference
org.onosproject.net.device.PortStatistics Interface Reference
Statistics of a port.
Public Member Functions
int port ()
Returns the port number.
long packetsReceived ()
Returns the number of packets received.
long packetsSent ()
Returns the number of packets sent.
long bytesReceived ()
Returns the bytes received.
long bytesSent ()
Returns the bytes sent.
long packetsRxDropped ()
Returns the number of packets dropped by RX.
long packetsTxDropped ()
Returns the number of packets dropped by TX.
long packetsRxErrors ()
Returns the number of transmit errors.
long packetsTxErrors ()
Returns the number of receive errors.
long durationSec ()
Returns the time port has been alive in seconds.
long durationNano ()
Returns the time port has been alive in nano seconds.
Detailed Description
Statistics of a port.
Definition at line 21 of file PortStatistics.java.
Member Function Documentation
long org.onosproject.net.device.PortStatistics.bytesReceived ()
Returns the bytes received.
Returns
the bytes received
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), and org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction().
long org.onosproject.net.device.PortStatistics.bytesSent ()
Returns the bytes sent.
Returns
the bytes sent
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), and org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction().
long org.onosproject.net.device.PortStatistics.durationNano ()
Returns the time port has been alive in nano seconds.
Returns
the time port has been alive in nano seconds
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), and org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction().
long org.onosproject.net.device.PortStatistics.durationSec ()
Returns the time port has been alive in seconds.
Returns
the time port has been alive in seconds
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), and org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction().
long org.onosproject.net.device.PortStatistics.packetsReceived ()
Returns the number of packets received.
Returns
the number of packets received
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction(), and org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
long org.onosproject.net.device.PortStatistics.packetsRxDropped ()
Returns the number of packets dropped by RX.
Returns
the number of packets dropped by RX
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), and org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction().
long org.onosproject.net.device.PortStatistics.packetsRxErrors ()
Returns the number of transmit errors.
Returns
the number of transmit errors
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), and org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction().
long org.onosproject.net.device.PortStatistics.packetsSent ()
Returns the number of packets sent.
Returns
the number of packets sent
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction(), and org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
long org.onosproject.net.device.PortStatistics.packetsTxDropped ()
Returns the number of packets dropped by TX.
Returns
the number of packets dropped by TX
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), and org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction().
long org.onosproject.net.device.PortStatistics.packetsTxErrors ()
Returns the number of receive errors.
Returns
the number of receive error
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), and org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction().
int org.onosproject.net.device.PortStatistics.port ()
Returns the port number.
Returns
port number
Implemented in org.onosproject.net.device.DefaultPortStatistics.
Referenced by org.onosproject.store.trivial.SimpleDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.ECDeviceStore.calcDeltaStats(), org.onosproject.store.device.impl.GossipDeviceStore.calcDeltaStats(), org.onosproject.net.device.DefaultPortStatisticsTest.testConstruction(), and org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/device/PortStatistics.java