onos: org.onosproject.net.device.DeviceDescription Interface Reference
org.onosproject.net.device.DeviceDescription Interface Reference
Carrier of immutable information about a device.
Public Member Functions
URI deviceUri ()
Protocol/provider specific URI that can be used to encode the identity information required to communicate with the device externally, e.g.
Device.Type type ()
Returns the type of the infrastructure device.
String manufacturer ()
Returns the device manufacturer name.
String hwVersion ()
Returns the device hardware version.
String swVersion ()
Returns the device software version.
String serialNumber ()
Returns the device serial number.
ChassisId chassisId ()
Returns a device chassis id.
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Detailed Description
Carrier of immutable information about a device.
Definition at line 27 of file DeviceDescription.java.
Member Function Documentation
ChassisId org.onosproject.net.device.DeviceDescription.chassisId ()
Returns a device chassis id.
Returns
chassis id
Implemented in org.onosproject.net.device.DefaultDeviceDescription.
Referenced by org.onosproject.net.device.DefaultDeviceDescriptionTest.basics(), and org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription().
URI org.onosproject.net.device.DeviceDescription.deviceUri ()
Protocol/provider specific URI that can be used to encode the identity information required to communicate with the device externally, e.g.
datapath ID.
Returns
provider specific URI for the device
Implemented in org.onosproject.net.device.DefaultDeviceDescription.
Referenced by org.onosproject.net.device.DefaultDeviceDescriptionTest.basics(), org.onosproject.net.device.impl.BasicDeviceOperator.combine(), and org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
String org.onosproject.net.device.DeviceDescription.hwVersion ()
Returns the device hardware version.
Returns
hardware version
Implemented in org.onosproject.net.device.DefaultDeviceDescription.
Referenced by org.onosproject.net.device.DefaultDeviceDescriptionTest.basics(), org.onosproject.net.device.impl.BasicDeviceOperator.combine(), and org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription().
String org.onosproject.net.device.DeviceDescription.manufacturer ()
Returns the device manufacturer name.
Returns
manufacturer name
Implemented in org.onosproject.net.device.DefaultDeviceDescription.
Referenced by org.onosproject.net.device.DefaultDeviceDescriptionTest.basics(), and org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription().
String org.onosproject.net.device.DeviceDescription.serialNumber ()
Returns the device serial number.
Returns
serial number
Implemented in org.onosproject.net.device.DefaultDeviceDescription.
Referenced by org.onosproject.net.device.DefaultDeviceDescriptionTest.basics(), org.onosproject.net.device.impl.BasicDeviceOperator.combine(), and org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription().
String org.onosproject.net.device.DeviceDescription.swVersion ()
Returns the device software version.
Returns
software version
Implemented in org.onosproject.net.device.DefaultDeviceDescription.
Referenced by org.onosproject.net.device.DefaultDeviceDescriptionTest.basics(), and org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription().
Device.Type org.onosproject.net.device.DeviceDescription.type ()
Returns the type of the infrastructure device.
Returns
type of the device
Implemented in org.onosproject.net.device.DefaultDeviceDescription.
Referenced by org.onosproject.net.device.DefaultDeviceDescriptionTest.basics(), org.onosproject.net.device.DefaultDeviceDescription.DefaultDeviceDescription(), org.onosproject.net.device.impl.BasicDeviceOperatorTest.testDescOps(), and org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/device/DeviceDescription.java