onos: org.onosproject.net.behaviour.TunnelDescription Interface Reference
org.onosproject.net.behaviour.TunnelDescription Interface Reference
Describes a tunnel.
Classes
enum Type
Tunnel technology type.
Public Member Functions
TunnelEndPoint src ()
Returns the connection point source.
TunnelEndPoint dst ()
Returns the connection point destination.
Type type ()
Returns the tunnel type.
TunnelName tunnelName ()
Return the name of a tunnel.
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Detailed Description
Describes a tunnel.
Definition at line 27 of file TunnelDescription.java.
Member Function Documentation
TunnelEndPoint org.onosproject.net.behaviour.TunnelDescription.dst ()
Returns the connection point destination.
Returns
tunnel destination
Implemented in org.onosproject.net.behaviour.DefaultTunnelDescription.
Referenced by org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnel(), org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnelInterface(), and org.onosproject.driver.ovsdb.OvsdbTunnelConfig.removeTunnel().
TunnelEndPoint org.onosproject.net.behaviour.TunnelDescription.src ()
Returns the connection point source.
Returns
tunnel source ConnectionPoint
Implemented in org.onosproject.net.behaviour.DefaultTunnelDescription.
Referenced by org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnel(), org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnelInterface(), and org.onosproject.driver.ovsdb.OvsdbTunnelConfig.removeTunnel().
TunnelName org.onosproject.net.behaviour.TunnelDescription.tunnelName ()
Return the name of a tunnel.
Returns
Tunnel Name
Implemented in org.onosproject.net.behaviour.DefaultTunnelDescription.
Referenced by org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnelInterface().
Type org.onosproject.net.behaviour.TunnelDescription.type ()
Returns the tunnel type.
Returns
tunnel type
Implemented in org.onosproject.net.behaviour.DefaultTunnelDescription.
Referenced by org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnelInterface().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/behaviour/TunnelDescription.java