onos: org.onosproject.net.Port Interface Reference
org.onosproject.net.Port Interface Reference
Abstraction of a network port.
Classes
enum Type
Represents coarse port type classification.
Public Member Functions
Element element ()
Returns the parent network element to which this port belongs.
PortNumber number ()
Returns the port number.
boolean isEnabled ()
Indicates whether or not the port is currently up and active.
Type type ()
Returns the port type.
long portSpeed ()
Returns the current port speed in Mbps.
Public Member Functions inherited from org.onosproject.net.Annotated
Annotations annotations ()
Returns the key/value annotations.
Detailed Description
Abstraction of a network port.
Definition at line 22 of file Port.java.
Member Function Documentation
Element org.onosproject.net.Port.element ()
Returns the parent network element to which this port belongs.
Returns
parent network element
Implemented in org.onosproject.net.DefaultPort.
Referenced by org.onosproject.net.DefaultPortTest.basics().
boolean org.onosproject.net.Port.isEnabled ()
Indicates whether or not the port is currently up and active.
Returns
true if the port is operational
Implemented in org.onosproject.net.DefaultPort.
Referenced by org.onosproject.olt.Olt.activate(), and org.onosproject.net.DefaultPortTest.basics().
PortNumber org.onosproject.net.Port.number ()
Returns the port number.
Returns
port number
Implemented in org.onosproject.net.DefaultPort.
Referenced by org.onosproject.net.DefaultPortTest.basics(), and org.onosproject.codec.impl.PortCodec.encode().
long org.onosproject.net.Port.portSpeed ()
Returns the current port speed in Mbps.
Returns
current port speed
Implemented in org.onosproject.net.DefaultPort.
Referenced by org.onosproject.net.DefaultPortTest.basics().
Type org.onosproject.net.Port.type ()
Returns the port type.
Returns
port type
Implemented in org.onosproject.net.DefaultPort.
Referenced by org.onosproject.net.DefaultPortTest.basics().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/Port.java