onos: org.onosproject.net.Annotations Interface Reference
org.onosproject.net.Annotations Interface Reference
Represents an set of simple key/value string annotations.
Public Member Functions
Set< String > keys ()
Returns the set of keys for available annotations.
String value (String key)
Returns the value of the specified annotation.
Detailed Description
Represents an set of simple key/value string annotations.
Definition at line 23 of file Annotations.java.
Member Function Documentation
Set<String> org.onosproject.net.Annotations.keys ()
Returns the set of keys for available annotations.
Returns
annotation keys
Implemented in org.onosproject.net.driver.DefaultDriver, org.onosproject.net.DefaultAnnotations, org.onosproject.openflow.DriverAdapter, org.onosproject.net.driver.DefaultDriverData, and org.onosproject.net.SparseAnnotations.
Referenced by org.onosproject.cli.AbstractShellCommand.annotations(), org.onosproject.codec.impl.AnnotationsCodec.encode(), org.onosproject.net.AnnotationsUtil.isEqual(), and org.onosproject.net.driver.DefaultDriverTest.merge().
String org.onosproject.net.Annotations.value (String key)
Returns the value of the specified annotation.
Parameters
key annotation key
Returns
annotation value
Implemented in org.onosproject.net.driver.DefaultDriver, org.onosproject.net.DefaultAnnotations, org.onosproject.openflow.DriverAdapter, and org.onosproject.net.driver.DefaultDriverData.
Referenced by org.onosproject.cli.AbstractShellCommand.annotations(), org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.asMap(), org.onosproject.store.serializers.KryoSerializerTest.assertAnnotationsEquals(), org.onosproject.net.AnnotationsUtil.isEqual(), and org.onosproject.net.driver.DefaultDriverTest.merge().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/Annotations.java