onos: org.onosproject.net.host.HostService Interface Reference
org.onosproject.net.host.HostService Interface Reference
Service for interacting with the inventory of end-station hosts.
Public Member Functions
int getHostCount ()
Returns the number of end-station hosts known to the system.
Iterable< Host > getHosts ()
Returns a collection of all end-station hosts.
Host getHost (HostId hostId)
Returns the host with the specified identifier.
Set< Host > getHostsByVlan (VlanId vlanId)
Returns the set of hosts that belong to the specified VLAN.
Set< Host > getHostsByMac (MacAddress mac)
Returns the set of hosts that have the specified MAC address.
Set< Host > getHostsByIp (IpAddress ip)
Returns the set of hosts that have the specified IP address.
Set< Host > getConnectedHosts (ConnectPoint connectPoint)
Returns the set of hosts whose most recent location is the specified connection point.
Set< Host > getConnectedHosts (DeviceId deviceId)
Returns the set of hosts whose most recent location is the specified infrastructure device.
void startMonitoringIp (IpAddress ip)
Requests the host service to monitor hosts with the given IP address and notify listeners of changes.
void stopMonitoringIp (IpAddress ip)
Stops the host service from monitoring an IP address.
void requestMac (IpAddress ip)
Requests the host service to resolve the MAC address for the given IP address.
Detailed Description
Service for interacting with the inventory of end-station hosts.
Definition at line 32 of file HostService.java.
Member Function Documentation
Set<Host> org.onosproject.net.host.HostService.getConnectedHosts (ConnectPoint connectPoint)
Returns the set of hosts whose most recent location is the specified connection point.
Parameters
connectPoint connection point
Returns
set of hosts connected to the connection point
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
Set<Host> org.onosproject.net.host.HostService.getConnectedHosts (DeviceId deviceId)
Returns the set of hosts whose most recent location is the specified infrastructure device.
Parameters
deviceId device identifier
Returns
set of hosts connected to the device
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
Host org.onosproject.net.host.HostService.getHost (HostId hostId)
Returns the host with the specified identifier.
Parameters
hostId host identifier
Returns
host or null if one with the given identifier is not known
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
Referenced by org.onosproject.net.intent.impl.compiler.HostToHostIntentCompilerTest.setUp(), org.onosproject.rest.HostResourceTest.testBadGet(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testConfiguredVlan(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testConfiguredVlanOnInterfaces(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testForwardFlood(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testForwardFloodIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testForwardToHost(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testForwardToHostIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyDifferentVlan(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyDifferentVlanIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyKnown(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyKnownIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestForUs(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestForUsIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUs(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUsIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyUnknown(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyUnknownIpv6(), org.onosproject.rest.HostResourceTest.testSingleHostByIdFetch(), and org.onosproject.rest.HostResourceTest.testSingleHostByMacAndVlanFetch().
int org.onosproject.net.host.HostService.getHostCount ()
Returns the number of end-station hosts known to the system.
Returns
number of end-station hosts
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
Iterable<Host> org.onosproject.net.host.HostService.getHosts ()
Returns a collection of all end-station hosts.
Returns
collection of hosts
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
Referenced by org.onosproject.cli.net.HostsListCommand.getSortedHosts(), and org.onosproject.rest.HostResourceTest.setUpTest().
Set<Host> org.onosproject.net.host.HostService.getHostsByIp (IpAddress ip)
Returns the set of hosts that have the specified IP address.
Parameters
ip ip address
Returns
set of hosts with the given IP
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
Referenced by org.onosproject.segmentrouting.IpHandler.forwardPackets(), org.onosproject.segmentrouting.IcmpHandler.processPacketIn(), org.onosproject.segmentrouting.IpHandler.processPacketIn(), org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityHostToHost(), org.onosproject.reactive.routing.ReactiveRoutingFib.setUpConnectivityInternetToHost(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testConfiguredVlan(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testConfiguredVlanOnInterfaces(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testKnown(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testNotKnown(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyDifferentVlan(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyDifferentVlanIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyKnown(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyKnownIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestForUsIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUs(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUsIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyUnknown(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyUnknownIpv6(), org.onosproject.routing.impl.RouterAsyncArpTest.testRouteAdd(), and org.onosproject.routing.impl.RouterAsyncArpTest.testRouteUpdate().
Set<Host> org.onosproject.net.host.HostService.getHostsByMac (MacAddress mac)
Returns the set of hosts that have the specified MAC address.
Parameters
mac mac address
Returns
set of hosts with the given mac
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
Set<Host> org.onosproject.net.host.HostService.getHostsByVlan (VlanId vlanId)
Returns the set of hosts that belong to the specified VLAN.
Parameters
vlanId vlan identifier
Returns
set of hosts in the given vlan id
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
void org.onosproject.net.host.HostService.requestMac (IpAddress ip)
Requests the host service to resolve the MAC address for the given IP address.
This will trigger a notification to the host listeners if the MAC address is found.
Parameters
ip IP address to find the MAC address for
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
void org.onosproject.net.host.HostService.startMonitoringIp (IpAddress ip)
Requests the host service to monitor hosts with the given IP address and notify listeners of changes.
Parameters
ip IP address of the host to monitor
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
void org.onosproject.net.host.HostService.stopMonitoringIp (IpAddress ip)
Stops the host service from monitoring an IP address.
Parameters
ip IP address to stop monitoring
Implemented in org.onosproject.net.host.impl.HostManager, and org.onosproject.net.host.HostServiceAdapter.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/host/HostService.java