onos: org.onosproject.net.config.NetworkConfigService Interface Reference
org.onosproject.net.config.NetworkConfigService Interface Reference
Service for tracking network configurations which specify how the discovered network information should be interpreted and how the core or applications should act on or configure the network.
Public Member Functions
Set< Class > getSubjectClasses ()
Returns the set of subject classes for which configuration may be available.
SubjectFactory getSubjectFactory (String subjectClassKey)
Returns the subject factory with the specified key.
SubjectFactory getSubjectFactory (Class subjectClass)
Returns the subject factory for the specified class.
Class<?extends Config > getConfigClass (String subjectClassKey, String configKey)
Returns the configuration class with the specified key.
< S > Set< S > getSubjects (Class< S > subjectClass)
Returns the set of subjects for which some configuration is available.
< S, CextendsConfig< S > Set< S > getSubjects (Class< S > subjectClass, Class< C > configClass)
Returns the set of subjects for which the specified configuration is available.
< S > Set<?extends Config< S > > getConfigs (S subject)
Returns all configurations for the specified subject.
< S, CextendsConfig< S > C getConfig (S subject, Class< C > configClass)
Returns the configuration for the specified subject and configuration class if one is available; null otherwise.
< S, CextendsConfig< S > C addConfig (S subject, Class< C > configClass)
Creates a new configuration for the specified subject and configuration class.
< S, CextendsConfig< S > C applyConfig (S subject, Class< C > configClass, JsonNode json)
Applies configuration for the specified subject and configuration class using the raw JSON node.
< S, CextendsConfig< S > void removeConfig (S subject, Class< C > configClass)
Clears any configuration for the specified subject and configuration class.
Detailed Description
Service for tracking network configurations which specify how the discovered network information should be interpreted and how the core or applications should act on or configure the network.
Definition at line 30 of file NetworkConfigService.java.
Member Function Documentation
<S,CextendsConfig<S> C org.onosproject.net.config.NetworkConfigService.addConfig (S subject, Class< C > configClass)
Creates a new configuration for the specified subject and configuration class.
If one already exists, it is simply returned.
Parameters
subject configuration subject
configClass configuration class
<S> type of subject
<C> type of configuration
Returns
configuration or null if one is not available
<S,CextendsConfig<S> C org.onosproject.net.config.NetworkConfigService.applyConfig (S subject, Class< C > configClass, JsonNode json)
Applies configuration for the specified subject and configuration class using the raw JSON node.
If configuration already exists, it will be updated.
Parameters
subject configuration subject
configClass configuration class
json raw JSON node containing the configuration data
<S> type of subject
<C> type of configuration
Returns
configuration or null if one is not available
Exceptions
IllegalArgumentException if the supplied JSON node contains invalid data
<S,CextendsConfig<S> C org.onosproject.net.config.NetworkConfigService.getConfig (S subject, Class< C > configClass)
Returns the configuration for the specified subject and configuration class if one is available; null otherwise.
Parameters
subject configuration subject
configClass configuration class
<S> type of subject
<C> type of configuration
Returns
configuration or null if one is not available
Referenced by org.onosproject.rest.resources.NetworkConfigWebResource.download().
Class<? extends Config> org.onosproject.net.config.NetworkConfigService.getConfigClass (String subjectClassKey, String configKey)
Returns the configuration class with the specified key.
Parameters
subjectClassKey subject class key
configKey subject class name
Returns
subject class
Implemented in org.onosproject.net.config.impl.NetworkConfigManager, and org.onosproject.net.config.NetworkConfigServiceAdapter.
Referenced by org.onosproject.rest.resources.NetworkConfigWebResource.download().
<S> Set<? extends Config<S> > org.onosproject.net.config.NetworkConfigService.getConfigs (S subject)
Returns all configurations for the specified subject.
Parameters
subject configuration subject
<S> type of subject
Returns
set of configurations
Referenced by org.onosproject.rest.resources.NetworkConfigWebResource.delete().
Set<Class> org.onosproject.net.config.NetworkConfigService.getSubjectClasses ()
Returns the set of subject classes for which configuration may be available.
Returns
set of subject classes
Implemented in org.onosproject.net.config.impl.NetworkConfigManager, and org.onosproject.net.config.NetworkConfigServiceAdapter.
SubjectFactory org.onosproject.net.config.NetworkConfigService.getSubjectFactory (String subjectClassKey)
Returns the subject factory with the specified key.
Parameters
subjectClassKey subject class key
Returns
subject class
Implemented in org.onosproject.net.config.impl.NetworkConfigManager, and org.onosproject.net.config.NetworkConfigServiceAdapter.
Referenced by org.onosproject.rest.resources.NetworkConfigWebResource.download(), org.onosproject.net.config.impl.NetworkConfigManagerTest.testAddConfig(), org.onosproject.net.config.impl.NetworkConfigManagerTest.testApplyConfig(), and org.onosproject.rest.resources.NetworkConfigWebResource.upload().
SubjectFactory org.onosproject.net.config.NetworkConfigService.getSubjectFactory (Class subjectClass)
Returns the subject factory for the specified class.
Parameters
subjectClass subject class
Returns
subject class factory
Implemented in org.onosproject.net.config.impl.NetworkConfigManager, and org.onosproject.net.config.NetworkConfigServiceAdapter.
<S> Set<S> org.onosproject.net.config.NetworkConfigService.getSubjects (Class< S > subjectClass)
Returns the set of subjects for which some configuration is available.
Parameters
subjectClass subject class
<S> type of subject
Returns
set of configured subjects
Referenced by org.onosproject.rest.resources.NetworkConfigWebResource.delete().
<S,CextendsConfig<S> Set<S> org.onosproject.net.config.NetworkConfigService.getSubjects (Class< S > subjectClass, Class< C > configClass)
Returns the set of subjects for which the specified configuration is available.
Parameters
subjectClass subject class
configClass configuration class
<S> type of subject
<C> type of configuration
Returns
set of configured subjects
<S,CextendsConfig<S> void org.onosproject.net.config.NetworkConfigService.removeConfig (S subject, Class< C > configClass)
Clears any configuration for the specified subject and configuration class.
If one does not exist, this call has no effect.
Parameters
subject configuration subject
configClass configuration class
<S> type of subject
<C> type of configuration
Referenced by org.onosproject.rest.resources.NetworkConfigWebResource.delete().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/config/NetworkConfigService.java