onos: org.onosproject.net.flow.TrafficTreatment Interface Reference
org.onosproject.net.flow.TrafficTreatment Interface Reference
Abstraction of network traffic treatment.
Classes
interface Builder
Builder of traffic treatment entities.
Public Member Functions
List< Instruction > deferred ()
Returns the list of treatment instructions that will be applied further down the pipeline.
List< Instruction > immediate ()
Returns the list of treatment instructions that will be applied immediately.
List< Instruction > allInstructions ()
Returns the list of all instructions in the treatment, both immediate and deferred.
Instructions.TableTypeTransition tableTransition ()
Returns the next table in the pipeline.
boolean clearedDeferred ()
Whether the deferred treatment instructions will be cleared by the device.
Instructions.MetadataInstruction writeMetadata ()
Returns the metadata instruction if there is one.
Instructions.MeterInstruction metered ()
Returns the meter instruction if there is one.
Detailed Description
Abstraction of network traffic treatment.
Definition at line 37 of file TrafficTreatment.java.
Member Function Documentation
List<Instruction> org.onosproject.net.flow.TrafficTreatment.allInstructions ()
Returns the list of all instructions in the treatment, both immediate and deferred.
Returns
list of treatment instructions
Implemented in org.onosproject.net.flow.DefaultTrafficTreatment.
Referenced by org.onosproject.driver.pipeline.PicaPipeline.next(), org.onosproject.driver.pipeline.CentecV350Pipeline.next(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.revertTreatmentSelector(), org.onosproject.net.flow.DefaultFlowRule.toString(), and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.unionTrafficTreatment().
boolean org.onosproject.net.flow.TrafficTreatment.clearedDeferred ()
Whether the deferred treatment instructions will be cleared by the device.
Returns
a boolean
Implemented in org.onosproject.net.flow.DefaultTrafficTreatment.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd(), and org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod().
List<Instruction> org.onosproject.net.flow.TrafficTreatment.deferred ()
Returns the list of treatment instructions that will be applied further down the pipeline.
Returns
list of treatment instructions
Implemented in org.onosproject.net.flow.DefaultTrafficTreatment.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod(), and org.onosproject.codec.impl.TrafficTreatmentCodec.encode().
List<Instruction> org.onosproject.net.flow.TrafficTreatment.immediate ()
Returns the list of treatment instructions that will be applied immediately.
Returns
list of treatment instructions
Implemented in org.onosproject.net.flow.DefaultTrafficTreatment.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd(), org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod(), and org.onosproject.codec.impl.TrafficTreatmentCodec.encode().
Instructions.MeterInstruction org.onosproject.net.flow.TrafficTreatment.metered ()
Returns the meter instruction if there is one.
Returns
a meter instruction that may be null
Implemented in org.onosproject.net.flow.DefaultTrafficTreatment.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd(), and org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod().
Instructions.TableTypeTransition org.onosproject.net.flow.TrafficTreatment.tableTransition ()
Returns the next table in the pipeline.
Returns
a table transition; may be null.
Implemented in org.onosproject.net.flow.DefaultTrafficTreatment.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd(), and org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod().
Instructions.MetadataInstruction org.onosproject.net.flow.TrafficTreatment.writeMetadata ()
Returns the metadata instruction if there is one.
Returns
a metadata instruction that may be null
Implemented in org.onosproject.net.flow.DefaultTrafficTreatment.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowAdd(), and org.onosproject.provider.of.flow.impl.FlowModBuilderVer13.buildFlowMod().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/TrafficTreatment.java