onos: org.onosproject.net.group.Group Interface Reference
org.onosproject.net.group.Group Interface Reference
ONOS representation of group that is stored in the system.
Classes
enum GroupState
State of the group object in ONOS.
Public Member Functions
GroupId id ()
Returns group identifier associated with a group object.
GroupState state ()
Returns current state of a group object.
long life ()
Returns the number of milliseconds this group has been alive.
long packets ()
Returns the number of packets processed by this group.
long bytes ()
Returns the number of bytes processed by this group.
long referenceCount ()
Returns the number of flow rules or other groups reference this group.
Public Member Functions inherited from org.onosproject.net.group.GroupDescription
Type type ()
Returns type of a group object.
DeviceId deviceId ()
Returns device identifier on which this group object is created.
ApplicationId appId ()
Returns application identifier that has created this group object.
GroupKey appCookie ()
Returns application cookie associated with a group object.
Integer givenGroupId ()
Returns groupId passed in by caller.
GroupBuckets buckets ()
Returns group buckets of a group.
Detailed Description
ONOS representation of group that is stored in the system.
Definition at line 23 of file Group.java.
Member Function Documentation
long org.onosproject.net.group.Group.bytes ()
Returns the number of bytes processed by this group.
Returns
number of bytes
Implemented in org.onosproject.net.group.DefaultGroup.
Referenced by org.onosproject.store.group.impl.DistributedGroupStoreTest.testPushGroupMetrics().
GroupId org.onosproject.net.group.Group.id ()
Returns group identifier associated with a group object.
Returns
GroupId Group Identifier
Implemented in org.onosproject.net.group.DefaultGroup.
Referenced by org.onosproject.store.trivial.SimpleGroupStore.addOrUpdateGroupEntry(), org.onosproject.store.group.impl.DistributedGroupStore.groupOperationFailed(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific(), org.onosproject.store.trivial.SimpleGroupStore.removeGroupEntry(), and org.onosproject.store.trivial.SimpleGroupStore.updateGroupDescription().
long org.onosproject.net.group.Group.life ()
Returns the number of milliseconds this group has been alive.
Returns
number of millis
Implemented in org.onosproject.net.group.DefaultGroup.
long org.onosproject.net.group.Group.packets ()
Returns the number of packets processed by this group.
Returns
number of packets
Implemented in org.onosproject.net.group.DefaultGroup.
Referenced by org.onosproject.store.group.impl.DistributedGroupStoreTest.testPushGroupMetrics().
long org.onosproject.net.group.Group.referenceCount ()
Returns the number of flow rules or other groups reference this group.
Returns
number of flow rules or other groups pointing to this group
Implemented in org.onosproject.net.group.DefaultGroup.
Referenced by org.onosproject.store.trivial.SimpleGroupStore.addOrUpdateExtraneousGroupEntry().
GroupState org.onosproject.net.group.Group.state ()
Returns current state of a group object.
Returns
GroupState Group State
Implemented in org.onosproject.net.group.DefaultGroup.
Referenced by org.onosproject.store.trivial.SimpleGroupStore.addOrUpdateGroupEntry(), org.onosproject.store.group.impl.DistributedGroupStore.addOrUpdateGroupEntry(), org.onosproject.codec.impl.GroupCodec.encode(), and org.onosproject.store.group.impl.DistributedGroupStore.groupOperationFailed().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/group/Group.java