onos: org.onosproject.net.flowobjective.NextObjective Interface Reference
org.onosproject.net.flowobjective.NextObjective Interface Reference
Represents a nexthop which will be translated by a driver into the appropriate group or actions needed to implement the egress function.
Classes
interface Builder
A next step builder.
enum Type
Represents the type of next phase to build.
Public Member Functions
Collection< TrafficTreatment > next ()
The collection of treatments that need to be applied to a set of traffic.
Type type ()
The type of operation that will be applied to the traffic using the collection of treatments.
TrafficSelector meta ()
Auxiliary optional information provided to the device-driver.Typically conveys information about selectors (matches) that are intended to use this Next Objective.
Public Member Functions inherited from org.onosproject.net.flowobjective.Objective
int id ()
An identifier for this objective.
int priority ()
The priority for this objective.
ApplicationId appId ()
The application which applied this objective.
int timeout ()
The timeout for this objective.
boolean permanent ()
Whether this objective is permanent.
Operation op ()
The type of operation for this objective.
Optional< ObjectiveContext > context ()
Obtains an optional context.
Additional Inherited Members
Public Attributes inherited from org.onosproject.net.flowobjective.Objective
boolean DEFAULT_PERMANENT = true
int DEFAULT_TIMEOUT = 0
int DEFAULT_PRIORITY = 32768
Detailed Description
Represents a nexthop which will be translated by a driver into the appropriate group or actions needed to implement the egress function.
A next objective is made up of a collection of traffic treatments associated with a type. These types are:
Hashed
Broadcast
Failover
Simple
These types will indicate to the driver what the intended behavior is. For example, a broadcast next objective with a collection of output treatments will indicate to a driver that all output actions are expected to be executed simultaneously. The driver is then free to implement this as a group or a simple action list.
Definition at line 45 of file NextObjective.java.
Member Function Documentation
TrafficSelector org.onosproject.net.flowobjective.NextObjective.meta ()
Auxiliary optional information provided to the device-driver.Typically conveys information about selectors (matches) that are intended to use this Next Objective.
Returns
a selector intended to pass meta information to the device driver. Value may be null if no meta information is provided.
Implemented in org.onosproject.net.flowobjective.DefaultNextObjective.
Collection<TrafficTreatment> org.onosproject.net.flowobjective.NextObjective.next ()
The collection of treatments that need to be applied to a set of traffic.
Returns
a collection of traffic treatments
Implemented in org.onosproject.net.flowobjective.DefaultNextObjective.
Type org.onosproject.net.flowobjective.NextObjective.type ()
The type of operation that will be applied to the traffic using the collection of treatments.
Returns
a type
Implemented in org.onosproject.net.flowobjective.DefaultNextObjective.
Referenced by org.onosproject.driver.pipeline.SoftRouterPipeline.next(), org.onosproject.driver.pipeline.PicaPipeline.next(), org.onosproject.driver.pipeline.OVSCorsaPipeline.next(), and org.onosproject.driver.pipeline.CentecV350Pipeline.next().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/flowobjective/NextObjective.java