onos: org.onosproject.pcep.api.PcepTunnel Interface Reference
org.onosproject.pcep.api.PcepTunnel Interface Reference
Abstraction of a generalized PCEP Tunnel entity (bandwidth pipe) for L2 networks or L1/L0 networks, representation of e.g., VLAN, L1 ODUk connection, WDM OCH, etc.
Classes
enum Ability
The ability of a tunnel.
enum PathState
Represents state of the path, work normally or broken down.
enum PATHTYPE
enum Type
Describe the type of a tunnel.
Public Member Functions
Type type ()
Returns the type of a tunnel.
String name ()
Returns the name of a tunnel.
PcepDpid srcDeviceID ()
Returns the device id of destination endpoint of a tunnel.
PcepDpid dstDeviceId ()
Returns the device id of source endpoint of a tunnel.
long srcPort ()
Returns source port of a tunnel.
long dstPort ()
Returns destination port of a tunnel.
long bandWidth ()
Returns the bandwidth of a tunnel.
long id ()
Returns the tunnel id.
List< PcepHopNodeDescription > getHopList ()
Returns the detail hop list of a tunnel.
int getInstance ()
Returns the instance of a pcep tunnel,a instance is used to mark the times of a tunnel created.
PathState getPathState ()
Returns the state of a path.
Ability getSla ()
Returns the ability of a tunnel.
PATHTYPE getPathType ()
Returns the path type of a path if the tunnel's ability is diamond .
long underlayTunnelId ()
Get the under lay tunnel id of VLAN tunnel.
Public Member Functions inherited from org.onosproject.pcep.api.PcepOperator
OperationType getOperationType ()
Get operate type of a event,such as device add ,device update.
Detailed Description
Abstraction of a generalized PCEP Tunnel entity (bandwidth pipe) for L2 networks or L1/L0 networks, representation of e.g., VLAN, L1 ODUk connection, WDM OCH, etc.
Definition at line 26 of file PcepTunnel.java.
Member Function Documentation
long org.onosproject.pcep.api.PcepTunnel.bandWidth ()
Returns the bandwidth of a tunnel.
Returns
bandwidth
PcepDpid org.onosproject.pcep.api.PcepTunnel.dstDeviceId ()
Returns the device id of source endpoint of a tunnel.
Returns
device id
long org.onosproject.pcep.api.PcepTunnel.dstPort ()
Returns destination port of a tunnel.
Returns
port number
List<PcepHopNodeDescription> org.onosproject.pcep.api.PcepTunnel.getHopList ()
Returns the detail hop list of a tunnel.
Returns
hop list
int org.onosproject.pcep.api.PcepTunnel.getInstance ()
Returns the instance of a pcep tunnel,a instance is used to mark the times of a tunnel created.
instance and id identify a tunnel together.
Returns
the instance of a tunnel.
PathState org.onosproject.pcep.api.PcepTunnel.getPathState ()
Returns the state of a path.
Returns
normal or broken
PATHTYPE org.onosproject.pcep.api.PcepTunnel.getPathType ()
Returns the path type of a path if the tunnel's ability is diamond .
Returns
the type of a path, the preferred or alternate.
Ability org.onosproject.pcep.api.PcepTunnel.getSla ()
Returns the ability of a tunnel.
Returns
ability of the tunenl
long org.onosproject.pcep.api.PcepTunnel.id ()
Returns the tunnel id.
Returns
id of the PCEP tunnel
String org.onosproject.pcep.api.PcepTunnel.name ()
Returns the name of a tunnel.
Returns
tunnel name
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
PcepDpid org.onosproject.pcep.api.PcepTunnel.srcDeviceID ()
Returns the device id of destination endpoint of a tunnel.
Returns
device id
long org.onosproject.pcep.api.PcepTunnel.srcPort ()
Returns source port of a tunnel.
Returns
port number
Type org.onosproject.pcep.api.PcepTunnel.type ()
Returns the type of a tunnel.
Returns
tunnel type
long org.onosproject.pcep.api.PcepTunnel.underlayTunnelId ()
Get the under lay tunnel id of VLAN tunnel.
Returns
the tunnel id of a OCH tunnel under lay of a VLAN tunnel.
The documentation for this interface was generated from the following file:
apps/pcep-api/src/main/java/org/onosproject/pcep/api/PcepTunnel.java