onos: org.onosproject.store.service.Serializer Interface Reference
org.onosproject.store.service.Serializer Interface Reference
Interface for serialization of store artifacts.
Public Member Functions
< T > byte[] encode (T object)
Serialize the specified object.
< T > T decode (byte[] bytes)
Deserialize the specified bytes.
Static Public Member Functions
static Serializer using (KryoNamespace kryo)
Creates a new Serializer instance from a KryoNamespace.
static Serializer using (List< KryoNamespace > namespaces, Class<?>...classes)
static Serializer forTypes (Class<?>...classes)
Detailed Description
Interface for serialization of store artifacts.
Definition at line 29 of file Serializer.java.
Member Function Documentation
<T> T org.onosproject.store.service.Serializer.decode (byte[] bytes)
Deserialize the specified bytes.
Parameters
bytes byte array to deserialize.
Returns
deserialized object.
Parameters
<T> decoded type
Referenced by org.onosproject.store.consistent.impl.DefaultAsyncConsistentMap< K, V >.DefaultAsyncConsistentMap(), and org.onosproject.store.service.Serializer< InternalDeviceOfflineEvent >.using().
<T> byte [] org.onosproject.store.service.Serializer.encode (T object)
Serialize the specified object.
Parameters
object object to serialize.
Returns
serialized bytes.
Parameters
<T> encoded type
Referenced by org.onosproject.store.service.Serializer< InternalDeviceOfflineEvent >.using().
static Serializer org.onosproject.store.service.Serializer.forTypes (Class<?>... classes) static
Definition at line 75 of file Serializer.java.
static Serializer org.onosproject.store.service.Serializer.using (KryoNamespace kryo) static
Creates a new Serializer instance from a KryoNamespace.
Parameters
kryo kryo namespace
Returns
Serializer instance
Definition at line 52 of file Serializer.java.
Referenced by org.onosproject.store.flowobjective.impl.DistributedFlowObjectiveStore.activate(), org.onosproject.vtnrsc.tenantnetwork.impl.TenantNetworkManager.activate(), org.onosproject.dhcp.impl.DistributedDhcpStore.activate(), org.onosproject.vtnrsc.subnet.impl.SubnetManager.activate(), org.onosproject.store.consistent.impl.MutexExecutionManager.activate(), org.onosproject.vtnrsc.virtualport.impl.VirtualPortManager.activate(), org.onosproject.incubator.store.meter.impl.DistributedMeterStore.activate(), and org.onosproject.store.device.impl.ECDeviceStore.activate().
static Serializer org.onosproject.store.service.Serializer.using (List< KryoNamespace > namespaces, Class<?>... classes) static
Definition at line 56 of file Serializer.java.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/store/service/Serializer.java