onos: org.onosproject.cluster.LeadershipService Interface Reference
org.onosproject.cluster.LeadershipService Interface Reference
Service for leader election.
Public Member Functions
NodeId getLeader (String path)
Returns the current leader for the topic.
Leadership getLeadership (String path)
Returns the current leadership info for the topic.
Set< String > ownedTopics (NodeId nodeId)
Returns the set of topics owned by the specified node.
CompletableFuture< Leadership > runForLeadership (String path)
Joins the leadership contest.
CompletableFuture< Void > withdraw (String path)
Withdraws from a leadership contest.
boolean stepdown (String path)
If the local nodeId is the leader for specified topic, this method causes it to step down temporarily from leadership.
boolean makeTopCandidate (String path, NodeId nodeId)
Moves the specified nodeId to the top of the candidates list for the topic.
Map< String, Leadership > getLeaderBoard ()
Returns the current leader board.
Map< String, List< NodeId > > getCandidates ()
Returns the candidates for all known topics.
List< NodeId > getCandidates (String path)
Returns the candidates for a given topic.
Detailed Description
Service for leader election.
Leadership contests are organized around topics. A instance can join the leadership race for a topic or withdraw from a race it has previously joined. Listeners can be added to receive notifications asynchronously for various leadership contests.
Definition at line 32 of file LeadershipService.java.
Member Function Documentation
Map<String, List<NodeId> > org.onosproject.cluster.LeadershipService.getCandidates ()
Returns the candidates for all known topics.
Returns
A mapping from topics to corresponding list of candidates.
Implemented in org.onosproject.store.consistent.impl.DistributedLeadershipManager, org.onosproject.store.trivial.SimpleLeadershipManager, and org.onosproject.cluster.LeadershipServiceAdapter.
List<NodeId> org.onosproject.cluster.LeadershipService.getCandidates (String path)
Returns the candidates for a given topic.
Parameters
path topic
Returns
A lists of NodeIds, which may be empty.
Implemented in org.onosproject.store.consistent.impl.DistributedLeadershipManager, org.onosproject.store.trivial.SimpleLeadershipManager, and org.onosproject.cluster.LeadershipServiceAdapter.
NodeId org.onosproject.cluster.LeadershipService.getLeader (String path)
Returns the current leader for the topic.
Parameters
path topic
Returns
nodeId of the leader, null if so such topic exists.
Implemented in org.onosproject.store.consistent.impl.DistributedLeadershipManager, org.onosproject.store.trivial.SimpleLeadershipManager, and org.onosproject.cluster.LeadershipServiceAdapter.
Map<String, Leadership> org.onosproject.cluster.LeadershipService.getLeaderBoard ()
Returns the current leader board.
Returns
mapping from topic to leadership info.
Implemented in org.onosproject.store.consistent.impl.DistributedLeadershipManager, org.onosproject.store.trivial.SimpleLeadershipManager, and org.onosproject.cluster.LeadershipServiceAdapter.
Leadership org.onosproject.cluster.LeadershipService.getLeadership (String path)
Returns the current leadership info for the topic.
Parameters
path topic
Returns
leadership info or null if so such topic exists.
Implemented in org.onosproject.store.consistent.impl.DistributedLeadershipManager, org.onosproject.store.trivial.SimpleLeadershipManager, and org.onosproject.cluster.LeadershipServiceAdapter.
boolean org.onosproject.cluster.LeadershipService.makeTopCandidate (String path, NodeId nodeId)
Moves the specified nodeId to the top of the candidates list for the topic.
If the node is not a candidate for this topic, this method will be a noop.
Parameters
path leadership topic
nodeId nodeId to make the top candidate
Returns
true if nodeId is now the top candidate, false otherwise
Implemented in org.onosproject.store.consistent.impl.DistributedLeadershipManager, org.onosproject.store.trivial.SimpleLeadershipManager, and org.onosproject.cluster.LeadershipServiceAdapter.
Referenced by org.onosproject.store.mastership.impl.ConsistentDeviceMastershipStore.setMaster().
Set<String> org.onosproject.cluster.LeadershipService.ownedTopics (NodeId nodeId)
Returns the set of topics owned by the specified node.
Parameters
nodeId node Id.
Returns
set of topics for which this node is the current leader.
Implemented in org.onosproject.store.consistent.impl.DistributedLeadershipManager, org.onosproject.store.trivial.SimpleLeadershipManager, and org.onosproject.cluster.LeadershipServiceAdapter.
CompletableFuture<Leadership> org.onosproject.cluster.LeadershipService.runForLeadership (String path)
Joins the leadership contest.
Parameters
path topic for which this controller node wishes to be a leader
Returns
Leadership
future
Implemented in org.onosproject.store.consistent.impl.DistributedLeadershipManager, org.onosproject.store.trivial.SimpleLeadershipManager, and org.onosproject.cluster.LeadershipServiceAdapter.
Referenced by org.onosproject.store.intent.impl.PartitionManagerTest.setUp(), and org.onosproject.store.intent.impl.PartitionManagerTest.testActivate().
boolean org.onosproject.cluster.LeadershipService.stepdown (String path)
If the local nodeId is the leader for specified topic, this method causes it to step down temporarily from leadership.
The node will continue to be in contention for leadership and can potentially become the leader again if and when it becomes the highest priority candidate
If the local nodeId is not the leader, this method will make no changes and simply return false.
Parameters
path topic for which this controller node should give up leadership
Returns
true if this node stepped down from leadership, false otherwise
Implemented in org.onosproject.store.consistent.impl.DistributedLeadershipManager, org.onosproject.store.trivial.SimpleLeadershipManager, and org.onosproject.cluster.LeadershipServiceAdapter.
CompletableFuture<Void> org.onosproject.cluster.LeadershipService.withdraw (String path)
Withdraws from a leadership contest.
Parameters
path topic for which this controller node no longer wishes to be a leader
Returns
future that is successfully completed when withdraw is done
Implemented in org.onosproject.store.consistent.impl.DistributedLeadershipManager, org.onosproject.store.trivial.SimpleLeadershipManager, and org.onosproject.cluster.LeadershipServiceAdapter.
Referenced by org.onosproject.store.intent.impl.PartitionManagerTest.testRebalance().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/cluster/LeadershipService.java