onos: org.onosproject.vtnrsc.FloatingIp Interface Reference
org.onosproject.vtnrsc.FloatingIp Interface Reference
Representation of a floatingIp.
Classes
enum Status
Coarse classification of the type of the FloatingIp.
Public Member Functions
FloatingIpId id ()
Returns the floatingIp identifier.
TenantId tenantId ()
Returns the tenant identifier.
TenantNetworkId networkId ()
Returns the network identifier.
VirtualPortId portId ()
Returns the port identifier.
RouterId routerId ()
Returns the router identifier.
IpAddress floatingIp ()
Returns the floating ip address.
IpAddress fixedIp ()
Returns the fixed ip address.
Status status ()
Returns the status of floating ip.
Detailed Description
Representation of a floatingIp.
Definition at line 23 of file FloatingIp.java.
Member Function Documentation
IpAddress org.onosproject.vtnrsc.FloatingIp.fixedIp ()
Returns the fixed ip address.
Returns
fixedIp
Implemented in org.onosproject.vtnrsc.DefaultFloatingIp.
Referenced by org.onosproject.vtnweb.web.FloatingIpCodec.encode().
IpAddress org.onosproject.vtnrsc.FloatingIp.floatingIp ()
Returns the floating ip address.
Returns
floatingIp
Implemented in org.onosproject.vtnrsc.DefaultFloatingIp.
FloatingIpId org.onosproject.vtnrsc.FloatingIp.id ()
Returns the floatingIp identifier.
Returns
identifier
Implemented in org.onosproject.vtnrsc.DefaultFloatingIp.
TenantNetworkId org.onosproject.vtnrsc.FloatingIp.networkId ()
Returns the network identifier.
Returns
the network identifier
Implemented in org.onosproject.vtnrsc.DefaultFloatingIp.
VirtualPortId org.onosproject.vtnrsc.FloatingIp.portId ()
Returns the port identifier.
Returns
the port identifier
Implemented in org.onosproject.vtnrsc.DefaultFloatingIp.
Referenced by org.onosproject.vtnweb.web.FloatingIpCodec.encode().
RouterId org.onosproject.vtnrsc.FloatingIp.routerId ()
Returns the router identifier.
Returns
the router identifier
Implemented in org.onosproject.vtnrsc.DefaultFloatingIp.
Referenced by org.onosproject.vtnweb.web.FloatingIpCodec.encode().
Status org.onosproject.vtnrsc.FloatingIp.status ()
Returns the status of floating ip.
Returns
floatingIpStatus
Implemented in org.onosproject.vtnrsc.DefaultFloatingIp.
Referenced by org.onosproject.vtnweb.web.FloatingIpCodec.encode().
TenantId org.onosproject.vtnrsc.FloatingIp.tenantId ()
Returns the tenant identifier.
Returns
the tenant identifier
Implemented in org.onosproject.vtnrsc.DefaultFloatingIp.
Referenced by org.onosproject.vtnweb.web.FloatingIpCodec.encode().
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/FloatingIp.java