onos: org.onosproject.net.flowobjective.Objective Interface Reference
org.onosproject.net.flowobjective.Objective Interface Reference
Base representation of a flow-objective description.
Classes
interface Builder
An objective builder.
enum Operation
Type of operation.
Public Member Functions
int id ()
An identifier for this objective.
int priority ()
The priority for this objective.
ApplicationId appId ()
The application which applied this objective.
int timeout ()
The timeout for this objective.
boolean permanent ()
Whether this objective is permanent.
Operation op ()
The type of operation for this objective.
Optional< ObjectiveContext > context ()
Obtains an optional context.
Public Attributes
boolean DEFAULT_PERMANENT = true
int DEFAULT_TIMEOUT = 0
int DEFAULT_PRIORITY = 32768
Detailed Description
Base representation of a flow-objective description.
Definition at line 27 of file Objective.java.
Member Function Documentation
ApplicationId org.onosproject.net.flowobjective.Objective.appId ()
The application which applied this objective.
Returns
an application id
Implemented in org.onosproject.net.flowobjective.DefaultFilteringObjective, org.onosproject.net.flowobjective.DefaultForwardingObjective, and org.onosproject.net.flowobjective.DefaultNextObjective.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeOverride(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeParallel(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeSequential(), org.onosproject.driver.pipeline.OpenVSwitchPipeline.forward(), org.onosproject.driver.pipeline.OVSCorsaPipeline.next(), org.onosproject.driver.pipeline.CentecV350Pipeline.next(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateFilter(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateForwardNode(), and org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionTree.updateNext().
Optional<ObjectiveContext> org.onosproject.net.flowobjective.Objective.context ()
Obtains an optional context.
Returns
optional; which will be empty if there is no context. Otherwise it will return the context.
Implemented in org.onosproject.net.flowobjective.DefaultFilteringObjective, org.onosproject.net.flowobjective.DefaultForwardingObjective, and org.onosproject.net.flowobjective.DefaultNextObjective.
Referenced by org.onosproject.driver.pipeline.OFDPA2Pipeline.fail(), org.onosproject.driver.pipeline.SpringOpenTTP.fail(), org.onosproject.driver.pipeline.DefaultSingleTablePipeline.forward(), and org.onosproject.driver.pipeline.OltPipeline.forward().
int org.onosproject.net.flowobjective.Objective.id ()
An identifier for this objective.
Returns
an integer
Implemented in org.onosproject.net.flowobjective.DefaultForwardingObjective, org.onosproject.net.flowobjective.DefaultFilteringObjective, and org.onosproject.net.flowobjective.DefaultNextObjective.
Referenced by org.onosproject.driver.pipeline.OVSCorsaPipeline.next(), org.onosproject.driver.pipeline.CentecV350Pipeline.next(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), and org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective().
Operation org.onosproject.net.flowobjective.Objective.op ()
The type of operation for this objective.
Returns
an operation
Implemented in org.onosproject.net.flowobjective.DefaultFilteringObjective, org.onosproject.net.flowobjective.DefaultForwardingObjective, and org.onosproject.net.flowobjective.DefaultNextObjective.
Referenced by org.onosproject.driver.pipeline.SoftRouterPipeline.filter(), org.onosproject.driver.pipeline.PicaPipeline.filter(), org.onosproject.driver.pipeline.OVSCorsaPipeline.filter(), org.onosproject.driver.pipeline.CentecV350Pipeline.filter(), org.onosproject.driver.pipeline.SpringOpenTTP.filter(), org.onosproject.driver.pipeline.OFDPA2Pipeline.filter(), org.onosproject.driver.pipeline.DefaultSingleTablePipeline.forward(), org.onosproject.driver.pipeline.OpenVSwitchPipeline.forward(), org.onosproject.driver.pipeline.OltPipeline.forward(), org.onosproject.driver.pipeline.SoftRouterPipeline.forward(), org.onosproject.driver.pipeline.PicaPipeline.forward(), org.onosproject.driver.pipeline.OVSCorsaPipeline.forward(), org.onosproject.driver.pipeline.CentecV350Pipeline.forward(), org.onosproject.driver.pipeline.SpringOpenTTP.forward(), org.onosproject.driver.pipeline.OFDPA2Pipeline.forward(), org.onosproject.driver.pipeline.SpringOpenTTP.next(), org.onosproject.driver.pipeline.OFDPA2Pipeline.next(), org.onosproject.net.flowobjective.impl.composition.FilterTable.updateFilter(), org.onosproject.net.flowobjective.impl.composition.ForwardTable.updateForward(), and org.onosproject.net.flowobjective.impl.composition.NextTable.updateNext().
boolean org.onosproject.net.flowobjective.Objective.permanent ()
Whether this objective is permanent.
Returns
a boolean
Implemented in org.onosproject.net.flowobjective.DefaultFilteringObjective, org.onosproject.net.flowobjective.DefaultForwardingObjective, and org.onosproject.net.flowobjective.DefaultNextObjective.
Referenced by org.onosproject.driver.pipeline.DefaultSingleTablePipeline.forward(), org.onosproject.driver.pipeline.OltPipeline.forward(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthDstSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
int org.onosproject.net.flowobjective.Objective.priority ()
The priority for this objective.
Returns
an integer
Implemented in org.onosproject.net.flowobjective.DefaultFilteringObjective, org.onosproject.net.flowobjective.DefaultForwardingObjective, and org.onosproject.net.flowobjective.DefaultNextObjective.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeParallel(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.composeSequential(), org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardingObjectiveHash(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.SpringOpenTTPDell.processSpecific(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
int org.onosproject.net.flowobjective.Objective.timeout ()
The timeout for this objective.
Returns
an integer
Implemented in org.onosproject.net.flowobjective.DefaultFilteringObjective, org.onosproject.net.flowobjective.DefaultForwardingObjective, and org.onosproject.net.flowobjective.DefaultNextObjective.
Referenced by org.onosproject.net.flowobjective.impl.composition.ForwardTable.forwardingObjectiveHash().
Member Data Documentation
boolean org.onosproject.net.flowobjective.Objective.DEFAULT_PERMANENT = true
Definition at line 29 of file Objective.java.
int org.onosproject.net.flowobjective.Objective.DEFAULT_PRIORITY = 32768
Definition at line 31 of file Objective.java.
int org.onosproject.net.flowobjective.Objective.DEFAULT_TIMEOUT = 0
Definition at line 30 of file Objective.java.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/flowobjective/Objective.java