onos: org.onosproject.net.flow.TrafficSelector Interface Reference
org.onosproject.net.flow.TrafficSelector Interface Reference
Abstraction of a slice of network traffic.
Classes
interface Builder
Builder of traffic selector entities.
Public Member Functions
Set< Criterion > criteria ()
Returns selection criteria as an ordered list.
Criterion getCriterion (Criterion.Type type)
Returns the selection criterion for a particular type, if it exists in this traffic selector.
Detailed Description
Abstraction of a slice of network traffic.
Definition at line 33 of file TrafficSelector.java.
Member Function Documentation
Set<Criterion> org.onosproject.net.flow.TrafficSelector.criteria ()
Returns selection criteria as an ordered list.
Returns
list of criteria
Implemented in org.onosproject.net.flow.DefaultTrafficSelector.
Referenced by org.onosproject.provider.of.flow.impl.FlowModBuilder.buildMatch(), org.onosproject.codec.impl.TrafficSelectorCodec.encode(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.getTypeSet(), org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.revertTreatmentSelector(), and org.onosproject.net.flow.DefaultFlowRule.toString().
Criterion org.onosproject.net.flow.TrafficSelector.getCriterion (Criterion.Type type)
Returns the selection criterion for a particular type, if it exists in this traffic selector.
Parameters
type criterion type to look up
Returns
the criterion of the specified type if one exists, otherwise null
Implemented in org.onosproject.net.flow.DefaultTrafficSelector.
Referenced by org.onosproject.net.flowobjective.impl.composition.FlowObjectiveCompositionUtil.intersectTrafficSelector(), org.onosproject.driver.pipeline.SpringOpenTTP.processEthTypeSpecificObjective(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processSpecific(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.processSpecific().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/TrafficSelector.java