onos: org.onosproject.store.service.Transaction Interface Reference
org.onosproject.store.service.Transaction Interface Reference
An immutable transaction object.
Classes
enum State
Public Member Functions
long id ()
Returns the transaction Id.
List< DatabaseUpdate > updates ()
Returns the list of updates that are part of this transaction.
State state ()
Returns the current state of this transaction.
default boolean isDone ()
Returns true if this transaction has completed execution.
Transaction transition (State newState)
Returns a new transaction that is created by transitioning this one to the specified state.
long lastUpdated ()
Returns the system time when the transaction was last updated.
Detailed Description
An immutable transaction object.
Definition at line 23 of file Transaction.java.
Member Function Documentation
long org.onosproject.store.service.Transaction.id ()
Returns the transaction Id.
Returns
transaction id
Implemented in org.onosproject.store.consistent.impl.DefaultTransaction.
Referenced by org.onosproject.store.consistent.impl.DefaultDatabaseState.commit(), org.onosproject.store.consistent.impl.DefaultDatabaseState.prepare(), and org.onosproject.store.consistent.impl.DefaultDatabaseState.rollback().
default boolean org.onosproject.store.service.Transaction.isDone ()
Returns true if this transaction has completed execution.
Returns
true is yes, false otherwise
Definition at line 84 of file Transaction.java.
References org.onosproject.store.service.Transaction.State.ROLLEDBACK, and org.onosproject.store.service.Transaction.state().
long org.onosproject.store.service.Transaction.lastUpdated ()
Returns the system time when the transaction was last updated.
Returns
last update time
Implemented in org.onosproject.store.consistent.impl.DefaultTransaction.
State org.onosproject.store.service.Transaction.state ()
Returns the current state of this transaction.
Returns
transaction state
Implemented in org.onosproject.store.consistent.impl.DefaultTransaction.
Referenced by org.onosproject.store.consistent.impl.TransactionManager.execute(), and org.onosproject.store.service.Transaction.isDone().
Transaction org.onosproject.store.service.Transaction.transition (State newState)
Returns a new transaction that is created by transitioning this one to the specified state.
Parameters
newState destination state
Returns
a new transaction instance similar to the current one but its state set to specified state
Implemented in org.onosproject.store.consistent.impl.DefaultTransaction.
List<DatabaseUpdate> org.onosproject.store.service.Transaction.updates ()
Returns the list of updates that are part of this transaction.
Returns
list of database updates
Implemented in org.onosproject.store.consistent.impl.DefaultTransaction.
Referenced by org.onosproject.store.consistent.impl.DefaultDatabaseState.prepare().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/store/service/Transaction.java