onos: org.onosproject.segmentrouting.config.DeviceProperties Interface Reference
org.onosproject.segmentrouting.config.DeviceProperties Interface Reference
Mechanism through which group handler module retrieves the device specific attributes such as segment ID, Mac address...etc from group handler applications.
Public Member Functions
boolean isConfigured (DeviceId deviceId)
Checks if the device is configured.
int getSegmentId (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the segment id of a device to be used in group creation.
MacAddress getDeviceMac (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the Mac address of a device to be used in group creation.
Ip4Address getRouterIp (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the router ip address of a segment router.
boolean isEdgeDevice (DeviceId deviceId) throws DeviceConfigNotFoundException
Indicates whether a device is edge device or transit/core device.
List< Integer > getAllDeviceSegmentIds ()
Returns all segment IDs to be considered in building auto.
Map< Ip4Prefix, List
< PortNumber > > getSubnetPortsMap (DeviceId deviceId)
Returns subnet-to-ports mapping of given device.
Detailed Description
Mechanism through which group handler module retrieves the device specific attributes such as segment ID, Mac address...etc from group handler applications.
Definition at line 32 of file DeviceProperties.java.
Member Function Documentation
List<Integer> org.onosproject.segmentrouting.config.DeviceProperties.getAllDeviceSegmentIds ()
Returns all segment IDs to be considered in building auto.
created groups.
Returns
list of segment IDs
Implemented in org.onosproject.segmentrouting.config.DeviceConfiguration.
Referenced by org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.DefaultGroupHandler().
MacAddress org.onosproject.segmentrouting.config.DeviceProperties.getDeviceMac (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the Mac address of a device to be used in group creation.
Parameters
deviceId device identifier
Exceptions
DeviceConfigNotFoundException if the device configuration is not found
Returns
mac address of a device
Implemented in org.onosproject.segmentrouting.config.DeviceConfiguration.
Referenced by org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.DefaultGroupHandler().
Ip4Address org.onosproject.segmentrouting.config.DeviceProperties.getRouterIp (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the router ip address of a segment router.
Parameters
deviceId device identifier
Exceptions
DeviceConfigNotFoundException if the device configuration is not found
Returns
router ip address
Implemented in org.onosproject.segmentrouting.config.DeviceConfiguration.
int org.onosproject.segmentrouting.config.DeviceProperties.getSegmentId (DeviceId deviceId) throws DeviceConfigNotFoundException
Returns the segment id of a device to be used in group creation.
Parameters
deviceId device identifier
Exceptions
DeviceConfigNotFoundException if the device configuration is not found
Returns
segment id of a device
Implemented in org.onosproject.segmentrouting.config.DeviceConfiguration.
Map<Ip4Prefix, List<PortNumber> > org.onosproject.segmentrouting.config.DeviceProperties.getSubnetPortsMap (DeviceId deviceId)
Returns subnet-to-ports mapping of given device.
For each entry of the map Key: a subnet Value: a list of ports, which are bound to the subnet
Parameters
deviceId device identifier
Returns
a map that contains all subnet-to-ports mapping of given device
Implemented in org.onosproject.segmentrouting.config.DeviceConfiguration.
boolean org.onosproject.segmentrouting.config.DeviceProperties.isConfigured (DeviceId deviceId)
Checks if the device is configured.
Parameters
deviceId device identifier
Returns
true if the device is configured
Implemented in org.onosproject.segmentrouting.config.DeviceConfiguration.
boolean org.onosproject.segmentrouting.config.DeviceProperties.isEdgeDevice (DeviceId deviceId) throws DeviceConfigNotFoundException
Indicates whether a device is edge device or transit/core device.
Parameters
deviceId device identifier
Exceptions
DeviceConfigNotFoundException if the device configuration is not found
Returns
boolean
Implemented in org.onosproject.segmentrouting.config.DeviceConfiguration.
Referenced by org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.createGroupHandler().
The documentation for this interface was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/config/DeviceProperties.java