onos: org.onosproject.incubator.net.virtual .VirtualNetworkStore Interface Reference
org.onosproject.incubator.net.virtual .VirtualNetworkStore Interface Reference
Mechanism for distributing and storing virtual network model information.
Public Member Functions
void addTenantId (TenantId tenantId)
Adds a new tenant ID to the store.
void removeTenantId (TenantId tenantId)
Removes the specified tenant ID from the store.
Set< TenantId > getTenantIds ()
Returns set of registered tenant IDs.
VirtualNetwork addNetwork (TenantId tenantId)
Adds a new virtual network for the specified tenant to the store.
void removeNetwork (NetworkId networkId)
Removes the specified virtual network from the store.
VirtualDevice addDevice (NetworkId networkId, DeviceId deviceId)
Adds a new virtual device to the store.
void removeDevice (NetworkId networkId, DeviceId deviceId)
Renmoves the specified virtual device from the given network.
VirtualLink addLink (NetworkId networkId, ConnectPoint src, ConnectPoint dst, TunnelId realizedBy)
Adds a new virtual link.
void removeLink (NetworkId networkId, ConnectPoint src, ConnectPoint dst)
Removes the specified link from the store.
VirtualPort addPort (NetworkId networkId, DeviceId deviceId, PortNumber portNumber, Port realizedBy)
Adds a new virtual port to the network.
void removePort (NetworkId networkId, DeviceId deviceId, PortNumber portNumber)
Removes the specified port from the given device and network.
Set< VirtualNetwork > getNetworks (TenantId tenantId)
Returns the list of networks.
Set< VirtualDevice > getDevices (NetworkId networkId)
Returns the list of devices in the specified virtual network.
Set< VirtualLink > getLinks (NetworkId networkId)
Returns the list of virtual links in the specified virtual network.
Set< VirtualPort > getPorts (NetworkId networkId, DeviceId deviceId)
Returns the list of ports of the specified virtual device.
Detailed Description
Mechanism for distributing and storing virtual network model information.
Definition at line 30 of file VirtualNetworkStore.java.
Member Function Documentation
VirtualDevice org.onosproject.incubator.net.virtual .VirtualNetworkStore.addDevice (NetworkId networkId, DeviceId deviceId)
Adds a new virtual device to the store.
This device will have no ports.
Parameters
networkId network identifier
deviceId device identifier
Returns
the virtual device
VirtualLink org.onosproject.incubator.net.virtual .VirtualNetworkStore.addLink (NetworkId networkId, ConnectPoint src, ConnectPoint dst, TunnelId realizedBy)
Adds a new virtual link.
Parameters
networkId network identifier
src source end-point of the link
dst destination end-point of the link
realizedBy underlying tunnel using which this link is realized
Returns
the virtual link
Referenced by obelisk.ObeliskTopo.__init__(), topo-200sw-linkalarm.MyTopo.__init__(), chordal.chordalTopo.__init__(), rftesttopo.ReactiveForwardingTestTopo.__init__(), attmpls.AttMplsTopo.__init__(), optical2.OpticalTopo.__init__(), newFuncTopo.MyTopo.__init__(), onos.ControlNetwork.__init__(), optical2.OpticalTopo.addIntf(), optical.OpticalTopo.addIntf(), metro.FabricDomain.addTether(), fractal.FractalTopo.build(), opticalTestBig.BigOpticalTopo.build(), opticalTest.SmallOpticalTopo.build(), tower.TowerTopo.build(), attmplsfast.AttMplsTopo.build(), optical.OpticalTopo.build(), tutorial.SdnIpTopo.build(), tutorial_ipv6.SdnIpTopo.build(), metro.OpticalDomain.build(), and metro.FabricDomain.build().
VirtualNetwork org.onosproject.incubator.net.virtual .VirtualNetworkStore.addNetwork (TenantId tenantId)
Adds a new virtual network for the specified tenant to the store.
Parameters
tenantId tenant identifier
Returns
the virtual network
VirtualPort org.onosproject.incubator.net.virtual .VirtualNetworkStore.addPort (NetworkId networkId, DeviceId deviceId, PortNumber portNumber, Port realizedBy)
Adds a new virtual port to the network.
Parameters
networkId network identifier
deviceId device identifier
portNumber port number
realizedBy underlying port which realizes the virtual port
Returns
the virtual port
void org.onosproject.incubator.net.virtual .VirtualNetworkStore.addTenantId (TenantId tenantId)
Adds a new tenant ID to the store.
Parameters
tenantId tenant identifier
Set<VirtualDevice> org.onosproject.incubator.net.virtual .VirtualNetworkStore.getDevices (NetworkId networkId)
Returns the list of devices in the specified virtual network.
Parameters
networkId network identifier
Returns
set of virtual devices
Set<VirtualLink> org.onosproject.incubator.net.virtual .VirtualNetworkStore.getLinks (NetworkId networkId)
Returns the list of virtual links in the specified virtual network.
Parameters
networkId network identifier
Returns
set of virtual links
Set<VirtualNetwork> org.onosproject.incubator.net.virtual .VirtualNetworkStore.getNetworks (TenantId tenantId)
Returns the list of networks.
Parameters
tenantId tenant identifier
Returns
set of virtual networks
Set<VirtualPort> org.onosproject.incubator.net.virtual .VirtualNetworkStore.getPorts (NetworkId networkId, DeviceId deviceId)
Returns the list of ports of the specified virtual device.
Parameters
networkId network identifier
deviceId device identifier
Returns
set of virtual networks
Set<TenantId> org.onosproject.incubator.net.virtual .VirtualNetworkStore.getTenantIds ()
Returns set of registered tenant IDs.
Returns
set of tenant identifiers
void org.onosproject.incubator.net.virtual .VirtualNetworkStore.removeDevice (NetworkId networkId, DeviceId deviceId)
Renmoves the specified virtual device from the given network.
Parameters
networkId network identifier
deviceId device identifier
void org.onosproject.incubator.net.virtual .VirtualNetworkStore.removeLink (NetworkId networkId, ConnectPoint src, ConnectPoint dst)
Removes the specified link from the store.
Parameters
networkId network identifier
src source connection point
dst destination connection point
void org.onosproject.incubator.net.virtual .VirtualNetworkStore.removeNetwork (NetworkId networkId)
Removes the specified virtual network from the store.
Parameters
networkId network identifier
void org.onosproject.incubator.net.virtual .VirtualNetworkStore.removePort (NetworkId networkId, DeviceId deviceId, PortNumber portNumber)
Removes the specified port from the given device and network.
Parameters
networkId network identifier
deviceId device identifier
portNumber port number
void org.onosproject.incubator.net.virtual .VirtualNetworkStore.removeTenantId (TenantId tenantId)
Removes the specified tenant ID from the store.
Parameters
tenantId tenant identifier
The documentation for this interface was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/virtual/VirtualNetworkStore.java