onos: org.onosproject.core.ApplicationId Interface Reference
org.onosproject.core.ApplicationId Interface Reference
Application identifier.
Public Member Functions
short id ()
Returns the application id.
String name ()
Returns the applications supplied identifier.
Detailed Description
Application identifier.
Definition at line 22 of file ApplicationId.java.
Member Function Documentation
short org.onosproject.core.ApplicationId.id ()
Returns the application id.
Returns
a short value
Implemented in org.onosproject.core.DefaultApplicationId, and org.onosproject.TestApplicationId.
Referenced by org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesByGroupId().
String org.onosproject.core.ApplicationId.name ()
Returns the applications supplied identifier.
Returns
a string identifier
Implemented in org.onosproject.core.DefaultApplicationId, and org.onosproject.TestApplicationId.
Referenced by org.onosproject.store.trivial.SimpleApplicationStore.activate(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.store.trivial.SimpleApplicationStore.deactivate(), org.onosproject.ui.table.cell.AppIdFormatter.nonNullFormat(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.setUp(), org.onosproject.provider.host.impl.HostLocationProviderTest.setUp(), org.onosproject.codec.impl.IntentCodecTest.setUpIntentService(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), tutorial_ipv6.Router.terminate(), org.onosproject.rest.IntentsResourceTest.testIntentsSingle(), and org.onosproject.net.meter.DefaultMeterRequest.toString().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/core/ApplicationId.java