onos: org.onosproject.net.driver.DriverService Interface Reference
org.onosproject.net.driver.DriverService Interface Reference
Service for obtaining drivers and driver behaviour implementations.
Public Member Functions
Set< Driver > getDrivers ()
Returns the overall set of drivers being provided.
Set< Driver > getDrivers (Class<?extends Behaviour > withBehaviour)
Returns the set of drivers which support the specified behaviour.
Driver getDriver (String mfr, String hw, String sw)
Returns the driver that matches the specified primordial device discovery information.
Driver getDriver (DeviceId deviceId)
Returns the driver for the specified device.
DriverHandler createHandler (DeviceId deviceId, String...credentials)
Creates a new driver handler for interacting with the specified device.
Public Member Functions inherited from org.onosproject.net.driver.DriverResolver
Driver getDriver (String driverName)
Returns the specified driver.
Detailed Description
Service for obtaining drivers and driver behaviour implementations.
Definition at line 25 of file DriverService.java.
Member Function Documentation
DriverHandler org.onosproject.net.driver.DriverService.createHandler (DeviceId deviceId, String... credentials)
Creates a new driver handler for interacting with the specified device.
The driver is looked-up using the same semantics as getDriver(DeviceId) method.
Parameters
deviceId device identifier
credentials optional login credentials in string form
Returns
driver handler
Exceptions
org.onlab.util.ItemNotFoundException if device or driver for it are not found
Implemented in org.onosproject.net.driver.impl.DriverManager, and org.onosproject.openflow.DriverServiceAdapter.
Driver org.onosproject.net.driver.DriverService.getDriver (String mfr, String hw, String sw)
Returns the driver that matches the specified primordial device discovery information.
Parameters
mfr device manufacturer
hw device hardware name/version
sw device software version
Returns
driver or null of no matching one is found
Implemented in org.onosproject.net.driver.impl.DriverManager, and org.onosproject.openflow.DriverServiceAdapter.
Referenced by org.onosproject.cli.net.DriversListCommand.execute(), and org.onosproject.store.serializers.ExtensionInstructionSerializer.read().
Driver org.onosproject.net.driver.DriverService.getDriver (DeviceId deviceId)
Returns the driver for the specified device.
If the device carries
driver
annotation, its value is used to look-up the driver. Otherwise, the device manufacturer, hardware and software version attributes are used to look-up the driver. First using their literal values and if no driver is found, using ERE matching against the driver manufacturer, hardware and software version fields.
Parameters
deviceId device identifier
Returns
driver or null of no matching one is found
Exceptions
org.onlab.util.ItemNotFoundException if device or driver for it are not found
Implemented in org.onosproject.net.driver.impl.DriverManager, and org.onosproject.openflow.DriverServiceAdapter.
Set<Driver> org.onosproject.net.driver.DriverService.getDrivers ()
Returns the overall set of drivers being provided.
Returns
provided drivers
Implemented in org.onosproject.net.driver.impl.DriverManager, and org.onosproject.openflow.DriverServiceAdapter.
Referenced by org.onosproject.cli.net.DriversListCommand.execute().
Set<Driver> org.onosproject.net.driver.DriverService.getDrivers (Class<?extends Behaviour > withBehaviour)
Returns the set of drivers which support the specified behaviour.
Parameters
withBehaviour behaviour class to query by
Returns
provided drivers
Implemented in org.onosproject.net.driver.impl.DriverManager, and org.onosproject.openflow.DriverServiceAdapter.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/driver/DriverService.java