onos: org.onosproject.net.link.LinkService Interface Reference
org.onosproject.net.link.LinkService Interface Reference
Service for interacting with the inventory of infrastructure links.
Public Member Functions
int getLinkCount ()
Returns the count of all known infrastructure links.
Iterable< Link > getLinks ()
Returns a collection of all known infrastructure links.
Iterable< Link > getActiveLinks ()
Returns a collection of all active infrastructure links.
Set< Link > getDeviceLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to and from the specified device.
Set< Link > getDeviceEgressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading from the specified device.
Set< Link > getDeviceIngressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to the specified device.
Set< Link > getLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to and from the specified connection point.
Set< Link > getEgressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading from the specified connection point.
Set< Link > getIngressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to the specified connection point.
Link getLink (ConnectPoint src, ConnectPoint dst)
Returns the infrastructure links between the specified source and destination connection points.
Detailed Description
Service for interacting with the inventory of infrastructure links.
Definition at line 28 of file LinkService.java.
Member Function Documentation
Iterable<Link> org.onosproject.net.link.LinkService.getActiveLinks ()
Returns a collection of all active infrastructure links.
Returns
all infrastructure links
Implemented in org.onosproject.net.link.impl.LinkManager, and org.onosproject.net.link.LinkServiceAdapter.
Set<Link> org.onosproject.net.link.LinkService.getDeviceEgressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading from the specified device.
Parameters
deviceId device identifier
Returns
set of device egress links
Implemented in org.onosproject.net.link.impl.LinkManager, org.onosproject.net.link.LinkServiceAdapter, and org.onosproject.flowanalyzer.MockLinkService.
Set<Link> org.onosproject.net.link.LinkService.getDeviceIngressLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to the specified device.
Parameters
deviceId device identifier
Returns
set of device ingress links
Implemented in org.onosproject.net.link.impl.LinkManager, org.onosproject.flowanalyzer.MockLinkService, and org.onosproject.net.link.LinkServiceAdapter.
Referenced by org.onosproject.rest.LinksResourceTest.testLinksByDeviceDirection().
Set<Link> org.onosproject.net.link.LinkService.getDeviceLinks (DeviceId deviceId)
Returns set of all infrastructure links leading to and from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implemented in org.onosproject.net.link.impl.LinkManager, org.onosproject.net.link.LinkServiceAdapter, and org.onosproject.flowanalyzer.MockLinkService.
Referenced by org.onosproject.rest.LinksResourceTest.testLinksByDevice().
Set<Link> org.onosproject.net.link.LinkService.getEgressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading from the specified connection point.
Parameters
connectPoint connection point
Returns
set of device egress links
Implemented in org.onosproject.net.link.impl.LinkManager, org.onosproject.flowanalyzer.MockLinkService, and org.onosproject.net.link.LinkServiceAdapter.
Set<Link> org.onosproject.net.link.LinkService.getIngressLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to the specified connection point.
Parameters
connectPoint connection point
Returns
set of device ingress links
Implemented in org.onosproject.net.link.impl.LinkManager, org.onosproject.flowanalyzer.MockLinkService, and org.onosproject.net.link.LinkServiceAdapter.
Referenced by org.onosproject.rest.LinksResourceTest.testLinksByDevicePortDirection().
Link org.onosproject.net.link.LinkService.getLink (ConnectPoint src, ConnectPoint dst)
Returns the infrastructure links between the specified source and destination connection points.
Parameters
src source connection point
dst destination connection point
Returns
link from source to destination; null if none found
Implemented in org.onosproject.net.link.impl.LinkManager, and org.onosproject.net.link.LinkServiceAdapter.
Referenced by org.onosproject.net.link.impl.LinkManagerTest.removeLink(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksAsAdminByConnectionPoint(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksAsAdminByDevice(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksByConnectionPoint(), and org.onosproject.net.link.impl.LinkManagerTest.removeLinksByDevice().
int org.onosproject.net.link.LinkService.getLinkCount ()
Returns the count of all known infrastructure links.
Returns
number of infrastructure links
Implemented in org.onosproject.net.link.impl.LinkManager, org.onosproject.net.link.LinkServiceAdapter, and org.onosproject.flowanalyzer.MockLinkService.
Referenced by org.onosproject.net.link.impl.LinkManagerTest.createLink(), org.onosproject.net.link.impl.LinkManagerTest.getLinks(), org.onosproject.net.link.impl.LinkManagerTest.removeLink(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksAsAdminByConnectionPoint(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksAsAdminByDevice(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksByConnectionPoint(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksByDevice(), and org.onosproject.net.link.impl.LinkManagerTest.updateLink().
Iterable<Link> org.onosproject.net.link.LinkService.getLinks ()
Returns a collection of all known infrastructure links.
Returns
all infrastructure links
Implemented in org.onosproject.net.link.impl.LinkManager, org.onosproject.net.link.LinkServiceAdapter, and org.onosproject.flowanalyzer.MockLinkService.
Referenced by org.onosproject.cli.net.LinksListCommand.execute(), org.onosproject.rest.StatisticsResourceTest.setUpTest(), org.onosproject.rest.LinksResourceTest.testLinks(), org.onosproject.rest.LinksResourceTest.testLinksByDevicePort(), and org.onosproject.rest.LinksResourceTest.testLinksEmptyArray().
Set<Link> org.onosproject.net.link.LinkService.getLinks (ConnectPoint connectPoint)
Returns set of all infrastructure links leading to and from the specified connection point.
Parameters
connectPoint connection point
Returns
set of links
Implemented in org.onosproject.net.link.impl.LinkManager, org.onosproject.flowanalyzer.MockLinkService, and org.onosproject.net.link.LinkServiceAdapter.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/link/LinkService.java