onos: org.onosproject.net.link.LinkDescription Interface Reference
org.onosproject.net.link.LinkDescription Interface Reference
Describes an infrastructure link.
Public Member Functions
ConnectPoint src ()
Returns the link source.
ConnectPoint dst ()
Returns the link destination.
Link.Type type ()
Returns the link type.
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Detailed Description
Describes an infrastructure link.
Definition at line 25 of file LinkDescription.java.
Member Function Documentation
ConnectPoint org.onosproject.net.link.LinkDescription.dst ()
Returns the link destination.
Returns
links destination
Implemented in org.onosproject.net.link.DefaultLinkDescription.
Referenced by org.onosproject.net.link.DefaultLinkDescriptionTest.basics().
ConnectPoint org.onosproject.net.link.LinkDescription.src ()
Returns the link source.
Returns
links source
Implemented in org.onosproject.net.link.DefaultLinkDescription.
Referenced by org.onosproject.net.link.DefaultLinkDescriptionTest.basics(), org.onosproject.net.link.impl.BasicLinkOperator.combine(), org.onosproject.store.trivial.SimpleLinkStore.createOrUpdateLink(), and org.onosproject.store.link.impl.ECLinkStore.createOrUpdateLink().
Link.Type org.onosproject.net.link.LinkDescription.type ()
Returns the link type.
Returns
link type
Implemented in org.onosproject.net.link.DefaultLinkDescription.
Referenced by org.onosproject.net.link.DefaultLinkDescriptionTest.basics().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/link/LinkDescription.java