onos: org.onosproject.net.statistic.Load Interface Reference
org.onosproject.net.statistic.Load Interface Reference
Simple data repository for link load information.
Public Member Functions
long rate ()
Obtain the current observed rate (in bytes/s) on a link.
long latest ()
Obtain the latest bytes counter viewed on that link.
boolean isValid ()
Indicates whether this load was built on valid values.
long time ()
Returns when this value was seen.
Detailed Description
Simple data repository for link load information.
Definition at line 21 of file Load.java.
Member Function Documentation
boolean org.onosproject.net.statistic.Load.isValid ()
Indicates whether this load was built on valid values.
Returns
boolean
Implemented in org.onosproject.net.statistic.DefaultLoad.
long org.onosproject.net.statistic.Load.latest ()
Obtain the latest bytes counter viewed on that link.
Returns
long value
Implemented in org.onosproject.net.statistic.DefaultLoad.
long org.onosproject.net.statistic.Load.rate ()
Obtain the current observed rate (in bytes/s) on a link.
Returns
long value
Implemented in org.onosproject.net.statistic.DefaultLoad.
Referenced by org.onosproject.incubator.net.impl.PortStatisticsManager.load(), org.onosproject.net.statistic.impl.StatisticManager.max(), and org.onosproject.net.statistic.impl.StatisticManager.min().
long org.onosproject.net.statistic.Load.time ()
Returns when this value was seen.
Returns
epoch time
Implemented in org.onosproject.net.statistic.DefaultLoad.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/statistic/Load.java