onos: org.onosproject.vtnrsc.FlowClassifier Interface Reference
org.onosproject.vtnrsc.FlowClassifier Interface Reference
Abstraction of an entity which provides flow classifier for service function chain.
Classes
interface Builder
Builder for flow Classifier.
Public Member Functions
FlowClassifierId flowClassifierId ()
Returns flow classifier ID.
TenantId tenantId ()
Returns Tenant ID.
String name ()
Returns flow classifier name.
String description ()
Returns flow classifier description.
String etherType ()
Returns EtherType.
String protocol ()
Returns IP Protocol.
int minSrcPortRange ()
Returns minimum source port range.
int maxSrcPortRange ()
Returns maximum source port range.
int minDstPortRange ()
Returns minimum destination port range.
int maxDstPortRange ()
Returns maximum destination port range.
IpPrefix srcIpPrefix ()
Returns Source IP prefix.
IpPrefix dstIpPrefix ()
Returns Destination IP prefix.
VirtualPortId srcPort ()
Returns Source virtual port.
VirtualPortId dstPort ()
Returns Destination virtual port.
boolean exactMatch (FlowClassifier flowClassifier)
Returns whether this Flow classifier is an exact match to the Flow classifier given in the argument.
Detailed Description
Abstraction of an entity which provides flow classifier for service function chain.
FlowClassifier classify the traffic based on the criteria defined in the request. The classification can be based on port range or source and destination IP address or other flow classifier elements.
Definition at line 26 of file FlowClassifier.java.
Member Function Documentation
String org.onosproject.vtnrsc.FlowClassifier.description ()
Returns flow classifier description.
Returns
flow classifier description
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest(), and org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
IpPrefix org.onosproject.vtnrsc.FlowClassifier.dstIpPrefix ()
Returns Destination IP prefix.
Returns
Destination IP prefix
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodec.encode(), and org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
VirtualPortId org.onosproject.vtnrsc.FlowClassifier.dstPort ()
Returns Destination virtual port.
Returns
Destination virtual port
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodec.encode(), and org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
String org.onosproject.vtnrsc.FlowClassifier.etherType ()
Returns EtherType.
Returns
EtherType
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
boolean org.onosproject.vtnrsc.FlowClassifier.exactMatch (FlowClassifier flowClassifier)
Returns whether this Flow classifier is an exact match to the Flow classifier given in the argument.
Parameters
flowClassifier other flowClassifier to match against
Returns
true if the flowClassifiers are an exact match, otherwise false
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
FlowClassifierId org.onosproject.vtnrsc.FlowClassifier.flowClassifierId ()
Returns flow classifier ID.
Returns
flow classifier id
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest(), org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch(), and org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.updateFlowClassifier().
int org.onosproject.vtnrsc.FlowClassifier.maxDstPortRange ()
Returns maximum destination port range.
Returns
maximum destination port range.
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest(), and org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
int org.onosproject.vtnrsc.FlowClassifier.maxSrcPortRange ()
Returns maximum source port range.
Returns
maximum source port range
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest(), and org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
int org.onosproject.vtnrsc.FlowClassifier.minDstPortRange ()
Returns minimum destination port range.
Returns
minimum destination port range
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest(), and org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
int org.onosproject.vtnrsc.FlowClassifier.minSrcPortRange ()
Returns minimum source port range.
Returns
minimum source port range
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest(), and org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
String org.onosproject.vtnrsc.FlowClassifier.name ()
Returns flow classifier name.
Returns
flow classifier name
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.vtnrsc.FlowClassifier.protocol ()
Returns IP Protocol.
Returns
IP protocol
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest(), and org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
IpPrefix org.onosproject.vtnrsc.FlowClassifier.srcIpPrefix ()
Returns Source IP prefix.
Returns
Source IP prefix
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
VirtualPortId org.onosproject.vtnrsc.FlowClassifier.srcPort ()
Returns Source virtual port.
Returns
Source virtual port
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
TenantId org.onosproject.vtnrsc.FlowClassifier.tenantId ()
Returns Tenant ID.
Returns
tenant Id
Implemented in org.onosproject.vtnrsc.DefaultFlowClassifier.
Referenced by org.onosproject.vtnweb.web.FlowClassifierCodecTest.codecFlowClassifierTest(), org.onosproject.vtnweb.web.FlowClassifierCodec.encode(), and org.onosproject.vtnrsc.DefaultFlowClassifier.exactMatch().
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/FlowClassifier.java