onos: org.onosproject.vtnrsc.Subnet Interface Reference
org.onosproject.vtnrsc.Subnet Interface Reference
Representation of a subnet.
Classes
enum Mode
Coarse classification of the type of the ipV6Mode.
Public Member Functions
SubnetId id ()
Returns the subnet identifier.
String subnetName ()
Returns the name of the subnet.
TenantNetworkId networkId ()
Returns the network identifier.
TenantId tenantId ()
Returns tenant identifier.
Version ipVersion ()
Returns the IP version, which is 4 or 6.
IpPrefix cidr ()
Returns the cidr.
IpAddress gatewayIp ()
Returns the gateway IP address.
boolean dhcpEnabled ()
Returns true if DHCP is enabled and return false if DHCP is disabled.
boolean shared ()
Indicates whether this tenantNetwork is shared across all tenants.
Iterable< HostRoute > hostRoutes ()
Returns a collection of hostRoutes.
Mode ipV6AddressMode ()
Returns the ipV6AddressMode.
Mode ipV6RaMode ()
Returns the ipV6RaMode.A valid value is dhcpv6-stateful, dhcpv6-stateless, or slaac.
Iterable< AllocationPool > allocationPools ()
Returns a collection of allocation_pools.
Detailed Description
Representation of a subnet.
Definition at line 25 of file Subnet.java.
Member Function Documentation
Iterable<AllocationPool> org.onosproject.vtnrsc.Subnet.allocationPools ()
Returns a collection of allocation_pools.
Returns
a collection of allocationPools
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
IpPrefix org.onosproject.vtnrsc.Subnet.cidr ()
Returns the cidr.
Returns
cidr
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
boolean org.onosproject.vtnrsc.Subnet.dhcpEnabled ()
Returns true if DHCP is enabled and return false if DHCP is disabled.
Returns
true or false
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
Referenced by org.onosproject.vtnweb.web.SubnetCodec.encode().
IpAddress org.onosproject.vtnrsc.Subnet.gatewayIp ()
Returns the gateway IP address.
Returns
gatewayIp
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
Referenced by org.onosproject.vtnweb.web.SubnetCodec.encode().
Iterable<HostRoute> org.onosproject.vtnrsc.Subnet.hostRoutes ()
Returns a collection of hostRoutes.
Returns
a collection of hostRoutes
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
SubnetId org.onosproject.vtnrsc.Subnet.id ()
Returns the subnet identifier.
Returns
identifier
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
Mode org.onosproject.vtnrsc.Subnet.ipV6AddressMode ()
Returns the ipV6AddressMode.
A valid value is dhcpv6-stateful, dhcpv6-stateless, or slaac.
Returns
ipV6AddressMode whose value is dhcpv6-stateful, dhcpv6-stateless or slaac
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
Referenced by org.onosproject.vtnweb.web.SubnetCodec.encode().
Mode org.onosproject.vtnrsc.Subnet.ipV6RaMode ()
Returns the ipV6RaMode.A valid value is dhcpv6-stateful, dhcpv6-stateless, or slaac.
Returns
ipV6RaMode whose value is dhcpv6-stateful, dhcpv6-stateless or slaac
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
Referenced by org.onosproject.vtnweb.web.SubnetCodec.encode().
Version org.onosproject.vtnrsc.Subnet.ipVersion ()
Returns the IP version, which is 4 or 6.
Returns
ipVersion
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
Referenced by org.onosproject.vtnweb.web.SubnetCodec.encode().
TenantNetworkId org.onosproject.vtnrsc.Subnet.networkId ()
Returns the network identifier.
Returns
the network identifier
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
boolean org.onosproject.vtnrsc.Subnet.shared ()
Indicates whether this tenantNetwork is shared across all tenants.
By default, only administrative user can change this value.
Returns
true or false
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
Referenced by org.onosproject.vtnweb.web.SubnetCodec.encode().
String org.onosproject.vtnrsc.Subnet.subnetName ()
Returns the name of the subnet.
Returns
subnetName
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
Referenced by org.onosproject.vtnweb.web.SubnetCodec.encode().
TenantId org.onosproject.vtnrsc.Subnet.tenantId ()
Returns tenant identifier.
Returns
the tenant identifier
Implemented in org.onosproject.vtnrsc.DefaultSubnet.
Referenced by org.onosproject.vtnweb.web.SubnetCodec.encode().
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/Subnet.java