onos: org.onosproject.incubator.net.tunnel.Tunnel Interface Reference
org.onosproject.incubator.net.tunnel.Tunnel Interface Reference
Abstraction of a generalized Tunnel entity (bandwidth pipe) for either L3/L2 networks or L1/L0 networks, representation of e.g., VLAN, GRE tunnel, MPLS LSP, L1 ODUk connection, WDM OCH, etc.
Classes
enum State
Representation of the tunnel state.
enum Type
Tunnel technology type.
Public Member Functions
State state ()
Returns the tunnel state.
TunnelEndPoint src ()
the origin of a tunnel.
TunnelEndPoint dst ()
the terminal of a tunnel.
Type type ()
Returns the tunnel type.
DefaultGroupId groupId ()
Returns group flow table id which a tunnel match up.
TunnelId tunnelId ()
Returns tunnel identify generated by ONOS as primary key.
TunnelName tunnelName ()
Return the name of a tunnel.
NetworkResource resource ()
Network resource backing the tunnel, e.g.
Path path ()
Returns the path of the tunnel.
Public Member Functions inherited from org.onosproject.net.Annotated
Annotations annotations ()
Returns the key/value annotations.
Public Member Functions inherited from org.onosproject.net.Provided
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Detailed Description
Abstraction of a generalized Tunnel entity (bandwidth pipe) for either L3/L2 networks or L1/L0 networks, representation of e.g., VLAN, GRE tunnel, MPLS LSP, L1 ODUk connection, WDM OCH, etc.
. Each Tunnel is associated with at least two tunnel end point objects that model the logical ports essentially. Note that it supports nested case.
Definition at line 33 of file Tunnel.java.
Member Function Documentation
TunnelEndPoint org.onosproject.incubator.net.tunnel.Tunnel.dst ()
the terminal of a tunnel.
Returns
the terminal of a tunnel
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnel.
Referenced by org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.createOrUpdateTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.releaseTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.setupTunnel(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.updateTunnel().
DefaultGroupId org.onosproject.incubator.net.tunnel.Tunnel.groupId ()
Returns group flow table id which a tunnel match up.
Returns
OpenFlowGroupId
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnel.
Path org.onosproject.incubator.net.tunnel.Tunnel.path ()
Returns the path of the tunnel.
Returns
the path of the tunnel
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnel.
Referenced by org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.createOrUpdateTunnel().
NetworkResource org.onosproject.incubator.net.tunnel.Tunnel.resource ()
Network resource backing the tunnel, e.g.
lambda, VLAN id, MPLS tag.
Returns
backing resource
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnel.
TunnelEndPoint org.onosproject.incubator.net.tunnel.Tunnel.src ()
the origin of a tunnel.
Returns
the origin of a tunnel
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnel.
Referenced by org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.deleteTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.releaseTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.setupTunnel(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.updateTunnel().
State org.onosproject.incubator.net.tunnel.Tunnel.state ()
Returns the tunnel state.
Returns
tunnel state
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnel.
Referenced by org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.borrowTunnel(), and org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.createOrUpdateTunnel().
TunnelId org.onosproject.incubator.net.tunnel.Tunnel.tunnelId ()
Returns tunnel identify generated by ONOS as primary key.
Returns
TunnelId
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnel.
Referenced by org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.createOrUpdateTunnel(), and org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.deleteTunnel().
TunnelName org.onosproject.incubator.net.tunnel.Tunnel.tunnelName ()
Return the name of a tunnel.
Returns
Tunnel Name
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnel.
Referenced by org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.createOrUpdateTunnel().
Type org.onosproject.incubator.net.tunnel.Tunnel.type ()
Returns the tunnel type.
Returns
tunnel type
Implemented in org.onosproject.incubator.net.tunnel.DefaultTunnel.
Referenced by org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.borrowTunnel(), org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.deleteTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.releaseTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.setupTunnel(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelRemoved(), org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.tunnelUpdated(), and org.onosproject.provider.pcep.tunnel.impl.PcepTunnelProvider.updateTunnel().
The documentation for this interface was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/tunnel/Tunnel.java