onos: org.onosproject.core.CoreService Interface Reference
org.onosproject.core.CoreService Interface Reference
Service for interacting with the core system of the controller.
Public Member Functions
Version version ()
Returns the product version.
Set< ApplicationId > getAppIds ()
Returns the set of currently registered application identifiers.
ApplicationId getAppId (Short id)
Returns an existing application id from a given id.
ApplicationId getAppId (String name)
Returns an existing application id from a given id.
ApplicationId registerApplication (String name)
Registers a new application by its name, which is expected to follow the reverse DNS convention, e.g.
ApplicationId registerApplication (String name, Runnable preDeactivate)
Registers a new application by its name, which is expected to follow the reverse DNS convention, e.g.
IdGenerator getIdGenerator (String topic)
Returns an id generator for a given topic.
Public Attributes
String CORE_APP_NAME = "org.onosproject.core"
Name of the core "application".
ProviderId CORE_PROVIDER_ID = new ProviderId("core", CORE_APP_NAME)
Identifier of the core "provider".
Detailed Description
Service for interacting with the core system of the controller.
Definition at line 25 of file CoreService.java.
Member Function Documentation
ApplicationId org.onosproject.core.CoreService.getAppId (Short id)
Returns an existing application id from a given id.
Parameters
id the short value of the id
Returns
an application id
Implemented in org.onosproject.core.impl.CoreManager, and org.onosproject.core.CoreServiceAdapter.
Referenced by org.onosproject.codec.impl.IntentCodecTest.setUpIntentService(), org.onosproject.rest.FlowsResourceTest.setUpTest(), org.onosproject.rest.IntentsResourceTest.testBadRemove(), org.onosproject.rest.IntentsResourceTest.testIntentsSingle(), org.onosproject.rest.IntentsResourceTest.testPost(), and org.onosproject.rest.IntentsResourceTest.testRemove().
ApplicationId org.onosproject.core.CoreService.getAppId (String name)
Returns an existing application id from a given id.
Parameters
name the name portion of the ID to look up
Returns
an application id
Implemented in org.onosproject.core.impl.CoreManager, and org.onosproject.core.CoreServiceAdapter.
Set<ApplicationId> org.onosproject.core.CoreService.getAppIds ()
Returns the set of currently registered application identifiers.
Returns
set of application ids
Implemented in org.onosproject.core.impl.CoreManager, and org.onosproject.core.CoreServiceAdapter.
Referenced by org.onosproject.cli.app.ApplicationIdListCommand.execute().
IdGenerator org.onosproject.core.CoreService.getIdGenerator (String topic)
Returns an id generator for a given topic.
Parameters
topic topic identified
Returns
the id generator
Implemented in org.onosproject.core.impl.CoreManager, org.onosproject.core.CoreServiceAdapter, and org.onosproject.core.impl.TestCoreManager.
ApplicationId org.onosproject.core.CoreService.registerApplication (String name)
Registers a new application by its name, which is expected to follow the reverse DNS convention, e.g.
org.flying.circus.app
Parameters
name string identifier
Returns
the application id
Implemented in org.onosproject.core.impl.CoreManager, and org.onosproject.core.CoreServiceAdapter.
Referenced by org.onosproject.codec.impl.ConstraintCodecTest.setUp(), org.onosproject.net.intent.impl.compiler.OpticalPathIntentCompilerTest.setUp(), org.onosproject.net.intent.impl.compiler.LinkCollectionIntentCompilerTest.setUp(), org.onosproject.net.intent.impl.compiler.MplsPathIntentCompilerTest.setUp(), org.onosproject.net.intent.impl.compiler.PathIntentCompilerTest.setUp(), org.onosproject.codec.impl.FlowRuleCodecTest.setUp(), org.onosproject.provider.lldp.impl.LldpLinkProviderTest.setUp(), org.onosproject.provider.host.impl.HostLocationProviderTest.setUp(), and org.onosproject.rest.FlowsResourceTest.setUpTest().
ApplicationId org.onosproject.core.CoreService.registerApplication (String name, Runnable preDeactivate)
Registers a new application by its name, which is expected to follow the reverse DNS convention, e.g.
org.flying.circus.app
, along with its pre-deactivation hook.
Parameters
name string identifier
preDeactivate pre-deactivation hook
Returns
the application id
Implemented in org.onosproject.core.impl.CoreManager, and org.onosproject.core.CoreServiceAdapter.
Version org.onosproject.core.CoreService.version ()
Returns the product version.
Returns
product version
Implemented in org.onosproject.core.impl.CoreManager, and org.onosproject.core.CoreServiceAdapter.
Member Data Documentation
String org.onosproject.core.CoreService.CORE_APP_NAME = "org.onosproject.core"
Name of the core "application".
Definition at line 30 of file CoreService.java.
Referenced by org.onosproject.core.impl.CoreManager.activate(), and org.onosproject.net.packet.impl.PacketManager.activate().
ProviderId org.onosproject.core.CoreService.CORE_PROVIDER_ID = new ProviderId("core", CORE_APP_NAME)
Identifier of the core "provider".
Definition at line 35 of file CoreService.java.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/core/CoreService.java