onos: org.onosproject.segmentrouting.Tunnel Interface Reference
org.onosproject.segmentrouting.Tunnel Interface Reference
Tunnel interface.
Public Member Functions
String id ()
Returns the tunnel ID.
List< Integer > labelIds ()
Returns Segment IDs for the tunnel including source and destination.
int groupId ()
Returns the group ID for the tunnel.
void setGroupId (int groupId)
Sets group ID for the tunnel.
void allowToRemoveGroup (boolean ok)
Sets the flag to allow to remove the group or not.
boolean isAllowedToRemoveGroup ()
Checks if it is allowed to remove the group for the tunnel.
Detailed Description
Tunnel interface.
Definition at line 24 of file Tunnel.java.
Member Function Documentation
void org.onosproject.segmentrouting.Tunnel.allowToRemoveGroup (boolean ok)
Sets the flag to allow to remove the group or not.
Parameters
ok the flag; true - allow to remove
Implemented in org.onosproject.segmentrouting.DefaultTunnel.
int org.onosproject.segmentrouting.Tunnel.groupId ()
Returns the group ID for the tunnel.
Returns
group ID
Implemented in org.onosproject.segmentrouting.DefaultTunnel.
Referenced by org.onosproject.segmentrouting.PolicyHandler.createPolicy(), and org.onosproject.segmentrouting.PolicyHandler.removePolicy().
String org.onosproject.segmentrouting.Tunnel.id ()
Returns the tunnel ID.
Returns
tunnel ID
Implemented in org.onosproject.segmentrouting.DefaultTunnel.
Referenced by org.onosproject.segmentrouting.TunnelHandler.createTunnel().
boolean org.onosproject.segmentrouting.Tunnel.isAllowedToRemoveGroup ()
Checks if it is allowed to remove the group for the tunnel.
Returns
true if allowed, false otherwise
Implemented in org.onosproject.segmentrouting.DefaultTunnel.
Referenced by org.onosproject.segmentrouting.TunnelHandler.removeTunnel().
List<Integer> org.onosproject.segmentrouting.Tunnel.labelIds ()
Returns Segment IDs for the tunnel including source and destination.
Returns
List of Node ID
Implemented in org.onosproject.segmentrouting.DefaultTunnel.
Referenced by org.onosproject.segmentrouting.TunnelHandler.createTunnel().
void org.onosproject.segmentrouting.Tunnel.setGroupId (int groupId)
Sets group ID for the tunnel.
Parameters
groupId group identifier
Implemented in org.onosproject.segmentrouting.DefaultTunnel.
The documentation for this interface was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/Tunnel.java