onos: org.onosproject.vtnrsc.PortChain Interface Reference
org.onosproject.vtnrsc.PortChain Interface Reference
Abstraction of an entity providing Port Chain information.
Classes
interface Builder
A port chain builder.
Public Member Functions
PortChainId portChainId ()
Returns the ID of this port chain.
TenantId tenantId ()
Returns the tenant id of this port chain.
String name ()
Returns the name of this port chain.
String description ()
Returns the description of this port chain.
List< PortPairGroupId > portPairGroups ()
Returns the list of port pair groups associated with this port chain.
List< FlowClassifierId > flowClassifiers ()
Returns the list of flow classifiers associated with this port chain.
boolean exactMatch (PortChain portChain)
Returns whether this port chain is an exact match to the port chain given in the argument.
Detailed Description
Abstraction of an entity providing Port Chain information.
A Port Chain (Service Function Path) consists of a set of Neutron ports, to define the sequence of service functions a set of flow classifiers, to specify the classified traffic flows to enter the chain
Definition at line 26 of file PortChain.java.
Member Function Documentation
String org.onosproject.vtnrsc.PortChain.description ()
Returns the description of this port chain.
Returns
description of port chain
Implemented in org.onosproject.vtnrsc.DefaultPortChain.
Referenced by org.onosproject.vtnweb.web.PortChainCodecTest.codecPortChainTest().
boolean org.onosproject.vtnrsc.PortChain.exactMatch (PortChain portChain)
Returns whether this port chain is an exact match to the port chain given in the argument.
Exact match means the port pair groups and flow classifiers match with the given port chain. It does not consider the port chain id, name and description.
Parameters
portChain other port chain to match against
Returns
true if the port chains are an exact match, otherwise false
Implemented in org.onosproject.vtnrsc.DefaultPortChain.
List<FlowClassifierId> org.onosproject.vtnrsc.PortChain.flowClassifiers ()
Returns the list of flow classifiers associated with this port chain.
Returns
list of flow classifiers
Implemented in org.onosproject.vtnrsc.DefaultPortChain.
Referenced by org.onosproject.vtnweb.web.PortChainCodecTest.codecPortChainTest(), and org.onosproject.vtnweb.web.PortChainCodec.encode().
String org.onosproject.vtnrsc.PortChain.name ()
Returns the name of this port chain.
Returns
name of port chain
Implemented in org.onosproject.vtnrsc.DefaultPortChain.
Referenced by org.onosproject.vtnweb.web.PortChainCodecTest.codecPortChainTest(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
PortChainId org.onosproject.vtnrsc.PortChain.portChainId ()
Returns the ID of this port chain.
Returns
the port chain id
Implemented in org.onosproject.vtnrsc.DefaultPortChain.
Referenced by org.onosproject.vtnweb.web.PortChainCodecTest.codecPortChainTest(), org.onosproject.vtnrsc.portchain.impl.PortChainManager.createPortChain(), org.onosproject.vtnrsc.DefaultPortChain.exactMatch(), and org.onosproject.vtnrsc.portchain.impl.PortChainManager.updatePortChain().
List<PortPairGroupId> org.onosproject.vtnrsc.PortChain.portPairGroups ()
Returns the list of port pair groups associated with this port chain.
Returns
list of port pair groups
Implemented in org.onosproject.vtnrsc.DefaultPortChain.
Referenced by org.onosproject.vtnweb.web.PortChainCodecTest.codecPortChainTest().
TenantId org.onosproject.vtnrsc.PortChain.tenantId ()
Returns the tenant id of this port chain.
Returns
the tenant id
Implemented in org.onosproject.vtnrsc.DefaultPortChain.
Referenced by org.onosproject.vtnweb.web.PortChainCodecTest.codecPortChainTest(), org.onosproject.vtnweb.web.PortChainCodec.encode(), and org.onosproject.vtnrsc.DefaultPortChain.exactMatch().
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/PortChain.java