onos: org.onosproject.net.packet.PacketContext Interface Reference
org.onosproject.net.packet.PacketContext Interface Reference
Represents context for processing an inbound packet, and (optionally) emitting a corresponding outbound packet.
Public Member Functions
long time ()
Returns the time when the packet was received.
InboundPacket inPacket ()
Returns the inbound packet being processed.
OutboundPacket outPacket ()
Returns the view of the outbound packet.
TrafficTreatment.Builder treatmentBuilder ()
Returns a builder for constructing traffic treatment.
void send ()
Triggers the outbound packet to be sent.
boolean block ()
Blocks the outbound packet from being sent from this point onward.
boolean isHandled ()
Indicates whether the outbound packet is handled, i.e.
Detailed Description
Represents context for processing an inbound packet, and (optionally) emitting a corresponding outbound packet.
Definition at line 24 of file PacketContext.java.
Member Function Documentation
boolean org.onosproject.net.packet.PacketContext.block ()
Blocks the outbound packet from being sent from this point onward.
Returns
whether the outbound packet is blocked.
Implemented in org.onosproject.net.packet.DefaultPacketContext.
InboundPacket org.onosproject.net.packet.PacketContext.inPacket ()
Returns the inbound packet being processed.
Returns
inbound packet
Implemented in org.onosproject.net.packet.DefaultPacketContext.
Referenced by org.onosproject.pim.impl.PIMPacketHandler.PIMPacketProcessor.process().
boolean org.onosproject.net.packet.PacketContext.isHandled ()
Indicates whether the outbound packet is handled, i.e.
sent or blocked.
Returns
true uf the packed is handled
Implemented in org.onosproject.net.packet.DefaultPacketContext.
Referenced by org.onosproject.pim.impl.PIMPacketHandler.PIMPacketProcessor.process(), and org.onosproject.provider.lldp.impl.LldpLinkProviderTest.unknownPktCtx().
OutboundPacket org.onosproject.net.packet.PacketContext.outPacket ()
Returns the view of the outbound packet.
Returns
outbound packet
Implemented in org.onosproject.net.packet.DefaultPacketContext.
void org.onosproject.net.packet.PacketContext.send ()
Triggers the outbound packet to be sent.
Implemented in org.onosproject.net.packet.DefaultPacketContext, and org.onosproject.provider.of.packet.impl.OpenFlowCorePacketContext.
long org.onosproject.net.packet.PacketContext.time ()
Returns the time when the packet was received.
Returns
the time in millis since start of epoch
Implemented in org.onosproject.net.packet.DefaultPacketContext.
TrafficTreatment.Builder org.onosproject.net.packet.PacketContext.treatmentBuilder ()
Returns a builder for constructing traffic treatment.
Returns
traffic treatment builder
Implemented in org.onosproject.net.packet.DefaultPacketContext.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/packet/PacketContext.java