onos: org.onosproject.net.Annotated Interface Reference
org.onosproject.net.Annotated Interface Reference
Represents an entity that carries arbitrary annotations.
Public Member Functions
Annotations annotations ()
Returns the key/value annotations.
Detailed Description
Represents an entity that carries arbitrary annotations.
Definition at line 21 of file Annotated.java.
Member Function Documentation
Annotations org.onosproject.net.Annotated.annotations ()
Returns the key/value annotations.
Returns
key/value annotations
Implemented in org.onosproject.incubator.net.resource.label.DefaultLabelResource, org.onosproject.net.AbstractDescription, org.onosproject.net.AbstractAnnotated, and org.onosproject.net.Description.
Referenced by org.onosproject.net.DefaultDeviceTest.annotations(), org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.createOrUpdateTunnel(), org.onosproject.net.link.impl.BasicLinkOperator.descriptionOf(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceMessage(), org.onosproject.vtnrsc.service.impl.VtnRscManager.getSFToSFFMaping(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.hostMessage(), org.onosproject.cli.net.LinksListCommand.linkString(), org.onosproject.cli.net.DevicesListCommand.printDevice(), and org.onosproject.cli.net.HostsListCommand.printHost().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/Annotated.java