onos: org.onosproject.net.link.LinkStore Interface Reference
org.onosproject.net.link.LinkStore Interface Reference
Manages inventory of infrastructure links; not intended for direct use.
Public Member Functions
int getLinkCount ()
Returns the number of links in the store.
Iterable< Link > getLinks ()
Returns an iterable collection of all links in the inventory.
Set< Link > getDeviceEgressLinks (DeviceId deviceId)
Returns all links egressing from the specified device.
Set< Link > getDeviceIngressLinks (DeviceId deviceId)
Returns all links ingressing from the specified device.
Link getLink (ConnectPoint src, ConnectPoint dst)
Returns the link between the two end-points.
Set< Link > getEgressLinks (ConnectPoint src)
Returns all links egressing from the specified connection point.
Set< Link > getIngressLinks (ConnectPoint dst)
Returns all links ingressing to the specified connection point.
LinkEvent createOrUpdateLink (ProviderId providerId, LinkDescription linkDescription)
Creates a new link, or updates an existing one, based on the given information.
LinkEvent removeOrDownLink (ConnectPoint src, ConnectPoint dst)
Removes the link, or marks it as inactive if the link is durable, based on the specified information.
LinkEvent removeLink (ConnectPoint src, ConnectPoint dst)
Removes the link based on the specified information.
Detailed Description
Manages inventory of infrastructure links; not intended for direct use.
Definition at line 29 of file LinkStore.java.
Member Function Documentation
LinkEvent org.onosproject.net.link.LinkStore.createOrUpdateLink (ProviderId providerId, LinkDescription linkDescription)
Creates a new link, or updates an existing one, based on the given information.
Parameters
providerId provider identity
linkDescription link description
Returns
create or update link event, or null if no change resulted
Implemented in org.onosproject.store.link.impl.GossipLinkStore, org.onosproject.store.link.impl.ECLinkStore, and org.onosproject.store.trivial.SimpleLinkStore.
Set<Link> org.onosproject.net.link.LinkStore.getDeviceEgressLinks (DeviceId deviceId)
Returns all links egressing from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implemented in org.onosproject.store.link.impl.GossipLinkStore, org.onosproject.store.link.impl.ECLinkStore, and org.onosproject.store.trivial.SimpleLinkStore.
Set<Link> org.onosproject.net.link.LinkStore.getDeviceIngressLinks (DeviceId deviceId)
Returns all links ingressing from the specified device.
Parameters
deviceId device identifier
Returns
set of device links
Implemented in org.onosproject.store.link.impl.GossipLinkStore, org.onosproject.store.link.impl.ECLinkStore, and org.onosproject.store.trivial.SimpleLinkStore.
Referenced by org.onosproject.net.link.impl.LinkManager.getDeviceLinks().
Set<Link> org.onosproject.net.link.LinkStore.getEgressLinks (ConnectPoint src)
Returns all links egressing from the specified connection point.
Parameters
src source connection point
Returns
set of connection point links
Implemented in org.onosproject.store.link.impl.GossipLinkStore, org.onosproject.store.link.impl.ECLinkStore, and org.onosproject.store.trivial.SimpleLinkStore.
Set<Link> org.onosproject.net.link.LinkStore.getIngressLinks (ConnectPoint dst)
Returns all links ingressing to the specified connection point.
Parameters
dst destination connection point
Returns
set of connection point links
Implemented in org.onosproject.store.link.impl.GossipLinkStore, org.onosproject.store.link.impl.ECLinkStore, and org.onosproject.store.trivial.SimpleLinkStore.
Referenced by org.onosproject.net.link.impl.LinkManager.getLinks().
Link org.onosproject.net.link.LinkStore.getLink (ConnectPoint src, ConnectPoint dst)
Returns the link between the two end-points.
Parameters
src source connection point
dst destination connection point
Returns
link or null if one not found between the end-points
Implemented in org.onosproject.store.link.impl.GossipLinkStore, org.onosproject.store.link.impl.ECLinkStore, and org.onosproject.store.trivial.SimpleLinkStore.
Referenced by org.onosproject.store.trivial.SimpleLinkStoreTest.testAncillaryVisible(), org.onosproject.store.link.impl.GossipLinkStoreTest.testAncillaryVisible(), org.onosproject.store.trivial.SimpleLinkStoreTest.testDurableToNonDurable(), org.onosproject.store.trivial.SimpleLinkStoreTest.testGetLink(), org.onosproject.store.link.impl.GossipLinkStoreTest.testGetLink(), org.onosproject.store.trivial.SimpleLinkStoreTest.testNonDurableToDurable(), org.onosproject.store.trivial.SimpleLinkStoreTest.testRemoveLink(), and org.onosproject.store.link.impl.GossipLinkStoreTest.testRemoveLink().
int org.onosproject.net.link.LinkStore.getLinkCount ()
Returns the number of links in the store.
Returns
number of links
Implemented in org.onosproject.store.link.impl.GossipLinkStore, org.onosproject.store.link.impl.ECLinkStore, and org.onosproject.store.trivial.SimpleLinkStore.
Referenced by org.onosproject.store.trivial.SimpleLinkStoreTest.testAncillaryVisible(), org.onosproject.store.link.impl.GossipLinkStoreTest.testAncillaryVisible(), org.onosproject.store.trivial.SimpleLinkStoreTest.testGetLinkCount(), and org.onosproject.store.link.impl.GossipLinkStoreTest.testGetLinkCount().
Iterable<Link> org.onosproject.net.link.LinkStore.getLinks ()
Returns an iterable collection of all links in the inventory.
Returns
collection of all links
Implemented in org.onosproject.store.link.impl.GossipLinkStore, org.onosproject.store.link.impl.ECLinkStore, and org.onosproject.store.trivial.SimpleLinkStore.
Referenced by org.onosproject.store.trivial.SimpleLinkStoreTest.testGetLinks(), and org.onosproject.store.link.impl.GossipLinkStoreTest.testGetLinks().
LinkEvent org.onosproject.net.link.LinkStore.removeLink (ConnectPoint src, ConnectPoint dst)
Removes the link based on the specified information.
Parameters
src link source
dst link destination
Returns
remove link event, or null if no change resulted
Implemented in org.onosproject.store.link.impl.GossipLinkStore, org.onosproject.store.link.impl.ECLinkStore, and org.onosproject.store.trivial.SimpleLinkStore.
Referenced by org.onosproject.net.link.impl.LinkManager.removeLink().
LinkEvent org.onosproject.net.link.LinkStore.removeOrDownLink (ConnectPoint src, ConnectPoint dst)
Removes the link, or marks it as inactive if the link is durable, based on the specified information.
Parameters
src link source
dst link destination
Returns
remove or update link event, or null if no change resulted
Implemented in org.onosproject.store.link.impl.GossipLinkStore, org.onosproject.store.link.impl.ECLinkStore, and org.onosproject.store.trivial.SimpleLinkStore.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/link/LinkStore.java