onos: org.onosproject.net.flow.FlowRuleService Interface Reference
org.onosproject.net.flow.FlowRuleService Interface Reference
Service for injecting flow rules into the environment and for obtaining information about flow rules already in the environment.
Public Member Functions
int getFlowRuleCount ()
Returns the number of flow rules in the system.
Iterable< FlowEntry > getFlowEntries (DeviceId deviceId)
Returns the collection of flow entries applied on the specified device.
void applyFlowRules (FlowRule...flowRules)
Applies the specified flow rules onto their respective devices.
void removeFlowRules (FlowRule...flowRules)
Removes the specified flow rules from their respective devices.
void removeFlowRulesById (ApplicationId appId)
Removes all rules by id.
Iterable< FlowRule > getFlowRulesById (ApplicationId id)
Returns a list of rules with this application id.
Iterable< FlowRule > getFlowRulesByGroupId (ApplicationId appId, short groupId)
Returns a list of rules filterd by application and group id.
void apply (FlowRuleOperations ops)
Applies a batch operation of FlowRules.
Iterable< TableStatisticsEntry > getFlowTableStatistics (DeviceId deviceId)
Returns the collection of flow table statistics of the specified device.
Public Attributes
String FLOW_OP_TOPIC = "flow-ops-ids"
The topic used for obtaining globally unique ids.
Detailed Description
Service for injecting flow rules into the environment and for obtaining information about flow rules already in the environment.
This implements semantics of a distributed authoritative flow table where the master copy of the flow rules lies with the controller and the devices hold only the 'cached' copy.
Definition at line 29 of file FlowRuleService.java.
Member Function Documentation
void org.onosproject.net.flow.FlowRuleService.apply (FlowRuleOperations ops)
Applies a batch operation of FlowRules.
Parameters
ops batch operation to apply
Implemented in org.onosproject.net.flow.impl.FlowRuleManager, org.onosproject.net.flow.FlowRuleServiceAdapter, org.onosproject.net.intent.impl.MockFlowRuleService, and org.onosproject.flowanalyzer.MockFlowRuleService.
void org.onosproject.net.flow.FlowRuleService.applyFlowRules (FlowRule... flowRules)
Applies the specified flow rules onto their respective devices.
These flow rules will be retained by the system and re-applied anytime the device reconnects to the controller.
Parameters
flowRules one or more flow rules
Implemented in org.onosproject.net.flow.impl.FlowRuleManager, org.onosproject.net.intent.impl.MockFlowRuleService, org.onosproject.flowanalyzer.MockFlowRuleService, and org.onosproject.net.flow.FlowRuleServiceAdapter.
Iterable<FlowEntry> org.onosproject.net.flow.FlowRuleService.getFlowEntries (DeviceId deviceId)
Returns the collection of flow entries applied on the specified device.
This will include flow rules which may not yet have been applied to the device.
Parameters
deviceId device identifier
Returns
collection of flow rules
Implemented in org.onosproject.net.flow.impl.FlowRuleManager, org.onosproject.net.intent.impl.MockFlowRuleService, org.onosproject.flowanalyzer.MockFlowRuleService, and org.onosproject.net.flow.FlowRuleServiceAdapter.
Referenced by org.onosproject.net.flow.impl.FlowRuleManagerTest.applyFlowRules(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.getFlowCount(), org.onosproject.net.flow.impl.FlowRuleManagerTest.getFlowEntries(), org.onosproject.cli.net.FlowsListCommand.getSortedFlows(), org.onosproject.rest.FlowsResourceTest.testBadGet(), org.onosproject.rest.FlowsResourceTest.testFlowsEmptyArray(), org.onosproject.rest.FlowsResourceTest.testFlowsSingleDevice(), and org.onosproject.rest.FlowsResourceTest.testFlowsSingleDeviceWithFlowId().
int org.onosproject.net.flow.FlowRuleService.getFlowRuleCount ()
Returns the number of flow rules in the system.
Returns
flow rule count
Implemented in org.onosproject.net.flow.impl.FlowRuleManager, org.onosproject.net.intent.impl.MockFlowRuleService, org.onosproject.flowanalyzer.MockFlowRuleService, and org.onosproject.net.flow.FlowRuleServiceAdapter.
Referenced by org.onosproject.ui.impl.TopologyViewMessageHandlerBase.summmaryMessage().
Iterable<FlowRule> org.onosproject.net.flow.FlowRuleService.getFlowRulesByGroupId (ApplicationId appId, short groupId)
Returns a list of rules filterd by application and group id.
Parameters
appId the application id to lookup
groupId the groupid to lookup
Returns
collection of flow rules
Implemented in org.onosproject.net.flow.impl.FlowRuleManager, org.onosproject.net.intent.impl.MockFlowRuleService, org.onosproject.flowanalyzer.MockFlowRuleService, and org.onosproject.net.flow.FlowRuleServiceAdapter.
Iterable<FlowRule> org.onosproject.net.flow.FlowRuleService.getFlowRulesById (ApplicationId id)
Returns a list of rules with this application id.
Parameters
id the id to look up
Returns
collection of flow rules
Implemented in org.onosproject.net.flow.impl.FlowRuleManager, org.onosproject.net.intent.impl.MockFlowRuleService, org.onosproject.flowanalyzer.MockFlowRuleService, and org.onosproject.net.flow.FlowRuleServiceAdapter.
Iterable<TableStatisticsEntry> org.onosproject.net.flow.FlowRuleService.getFlowTableStatistics (DeviceId deviceId)
Returns the collection of flow table statistics of the specified device.
Parameters
deviceId device identifier
Returns
collection of flow table statistics
Implemented in org.onosproject.net.flow.impl.FlowRuleManager, and org.onosproject.net.flow.FlowRuleServiceAdapter.
Referenced by org.onosproject.cli.net.TableStatisticsCommand.getSortedTableStats().
void org.onosproject.net.flow.FlowRuleService.removeFlowRules (FlowRule... flowRules)
Removes the specified flow rules from their respective devices.
If the device is not presently connected to the controller, these flow will be removed once the device reconnects.
Parameters
flowRules one or more flow rules throws SomeKindOfException that indicates which ones were removed and which ones failed
Implemented in org.onosproject.net.flow.impl.FlowRuleManager, org.onosproject.net.intent.impl.MockFlowRuleService, org.onosproject.flowanalyzer.MockFlowRuleService, and org.onosproject.net.flow.FlowRuleServiceAdapter.
void org.onosproject.net.flow.FlowRuleService.removeFlowRulesById (ApplicationId appId)
Removes all rules by id.
Parameters
appId id to remove
Implemented in org.onosproject.net.flow.impl.FlowRuleManager, and org.onosproject.net.flow.FlowRuleServiceAdapter.
Member Data Documentation
String org.onosproject.net.flow.FlowRuleService.FLOW_OP_TOPIC = "flow-ops-ids"
The topic used for obtaining globally unique ids.
Definition at line 35 of file FlowRuleService.java.
Referenced by org.onosproject.net.flow.impl.FlowRuleManager.activate(), and org.onosproject.store.flow.impl.NewDistributedFlowRuleStore.activate().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/FlowRuleService.java