onos: org.onosproject.net.group.GroupBucket Interface Reference
org.onosproject.net.group.GroupBucket Interface Reference
Group Bucket definition.
Public Member Functions
GroupDescription.Type type ()
Returns group type of the bucket.
TrafficTreatment treatment ()
Returns list of Traffic instructions that are part of the bucket.
short weight ()
Returns weight of select group bucket.
PortNumber watchPort ()
Returns port number used for liveness detection for a failover bucket.
GroupId watchGroup ()
Returns group identifier used for liveness detection for a failover bucket.
long packets ()
Returns the number of packets processed by this group bucket.
long bytes ()
Returns the number of bytes processed by this group bucket.
Detailed Description
Group Bucket definition.
A default group Bucket is collection of Instructions that can be performed on a traffic flow. A failover group bucket is associated with a specific port or group that controls its liveness. A select group bucket contains optional weight field to define the weights among the buckets in the group.
Definition at line 29 of file GroupBucket.java.
Member Function Documentation
long org.onosproject.net.group.GroupBucket.bytes ()
Returns the number of bytes processed by this group bucket.
Returns
number of bytes
Implemented in org.onosproject.net.group.DefaultGroupBucket.
Referenced by org.onosproject.codec.impl.GroupBucketCodec.encode(), and org.onosproject.codec.impl.GroupBucketJsonMatcher.matchesSafely().
long org.onosproject.net.group.GroupBucket.packets ()
Returns the number of packets processed by this group bucket.
Returns
number of packets
Implemented in org.onosproject.net.group.DefaultGroupBucket.
Referenced by org.onosproject.codec.impl.GroupBucketCodec.encode(), and org.onosproject.codec.impl.GroupBucketJsonMatcher.matchesSafely().
TrafficTreatment org.onosproject.net.group.GroupBucket.treatment ()
Returns list of Traffic instructions that are part of the bucket.
Returns
TrafficTreatment traffic instruction list
Implemented in org.onosproject.net.group.DefaultGroupBucket.
Referenced by org.onosproject.codec.impl.GroupBucketCodec.encode().
GroupDescription.Type org.onosproject.net.group.GroupBucket.type ()
Returns group type of the bucket.
Returns
GroupType group type
Implemented in org.onosproject.net.group.DefaultGroupBucket.
Referenced by org.onosproject.codec.impl.GroupBucketJsonMatcher.matchesSafely().
GroupId org.onosproject.net.group.GroupBucket.watchGroup ()
Returns group identifier used for liveness detection for a failover bucket.
Returns
GroupId group identifier to be used for liveness detection
Implemented in org.onosproject.net.group.DefaultGroupBucket.
Referenced by org.onosproject.codec.impl.GroupBucketCodec.encode().
PortNumber org.onosproject.net.group.GroupBucket.watchPort ()
Returns port number used for liveness detection for a failover bucket.
Returns
PortNumber port number used for liveness detection
Implemented in org.onosproject.net.group.DefaultGroupBucket.
Referenced by org.onosproject.codec.impl.GroupBucketCodec.encode().
short org.onosproject.net.group.GroupBucket.weight ()
Returns weight of select group bucket.
Returns
short weight associated with a bucket
Implemented in org.onosproject.net.group.DefaultGroupBucket.
Referenced by org.onosproject.codec.impl.GroupBucketCodec.encode(), and org.onosproject.codec.impl.GroupBucketJsonMatcher.matchesSafely().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/group/GroupBucket.java