onos: org.onosproject.net.Link Interface Reference
org.onosproject.net.Link Interface Reference
Abstraction of a network infrastructure link.
Classes
enum State
Representation of the link state, which applies primarily only to configured durable links, i.e.
enum Type
Coarse representation of the link type.
Public Member Functions
ConnectPoint src ()
Returns the link source connection point.
ConnectPoint dst ()
Returns the link destination connection point.
Type type ()
Returns the link type.
State state ()
Returns the link state.
boolean isDurable ()
Indicates if the link is to be considered durable.
Public Member Functions inherited from org.onosproject.net.Annotated
Annotations annotations ()
Returns the key/value annotations.
Public Member Functions inherited from org.onosproject.net.Provided
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Detailed Description
Abstraction of a network infrastructure link.
Definition at line 21 of file Link.java.
Member Function Documentation
ConnectPoint org.onosproject.net.Link.dst ()
Returns the link destination connection point.
Returns
link destination connection point
Implemented in org.onosproject.net.DefaultLink.
Referenced by org.onosproject.net.DefaultLinkTest.basics(), org.onosproject.net.DefaultEdgeLinkTest.basics(), org.onosproject.ui.topo.TopoUtils.canonicalLinkKey(), org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.linkUp(), org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler.newNeighbor(), org.onosproject.segmentrouting.grouphandler.DefaultEdgeGroupHandler.newNeighbor(), org.onosproject.net.DefaultEdgeLinkTest.phantomIngress(), org.onosproject.store.trivial.SimpleLinkStore.removeOrDownLink(), org.onosproject.store.link.impl.ECLinkStore.removeOrDownLink(), org.onosproject.store.link.impl.GossipLinkStore.removeOrDownLink(), and org.onosproject.segmentrouting.ECMPShortestPathGraph.toString().
boolean org.onosproject.net.Link.isDurable ()
Indicates if the link is to be considered durable.
Returns
true if the link is durable
Implemented in org.onosproject.net.DefaultLink.
Referenced by org.onosproject.store.trivial.SimpleLinkStore.removeOrDownLink(), org.onosproject.store.link.impl.ECLinkStore.removeOrDownLink(), and org.onosproject.store.link.impl.GossipLinkStore.removeOrDownLink().
ConnectPoint org.onosproject.net.Link.src ()
Returns the link source connection point.
Returns
link source connection point
Implemented in org.onosproject.net.DefaultLink.
Referenced by org.onosproject.net.DefaultLinkTest.basics(), org.onosproject.net.DefaultEdgeLinkTest.basics(), org.onosproject.ui.topo.TopoUtils.canonicalLinkKey(), org.onosproject.net.LinkKey.linkKey(), org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.linkUp(), org.onosproject.net.statistic.impl.StatisticManager.load(), org.onosproject.segmentrouting.grouphandler.DefaultTransitGroupHandler.newNeighbor(), org.onosproject.segmentrouting.grouphandler.DefaultEdgeGroupHandler.newNeighbor(), org.onosproject.net.DefaultEdgeLinkTest.phantomEgress(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksAsAdminByConnectionPoint(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksAsAdminByDevice(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksByConnectionPoint(), org.onosproject.net.link.impl.LinkManagerTest.removeLinksByDevice(), org.onosproject.store.trivial.SimpleLinkStore.removeOrDownLink(), org.onosproject.store.link.impl.ECLinkStore.removeOrDownLink(), and org.onosproject.store.link.impl.GossipLinkStore.removeOrDownLink().
State org.onosproject.net.Link.state ()
Returns the link state.
Returns
link state
Implemented in org.onosproject.net.DefaultLink.
Referenced by org.onosproject.codec.impl.LinkCodec.encode(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.linkMessage(), and org.onosproject.cli.net.LinksListCommand.linkString().
Type org.onosproject.net.Link.type ()
Returns the link type.
Returns
link type
Implemented in org.onosproject.net.DefaultLink.
Referenced by org.onosproject.net.DefaultLinkTest.basics(), org.onosproject.net.DefaultEdgeLinkTest.basics(), org.onosproject.net.link.impl.BasicLinkOperator.descriptionOf(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.linkMessage(), org.onosproject.segmentrouting.grouphandler.DefaultGroupHandler.linkUp(), org.onosproject.net.DefaultEdgeLinkTest.phantomEgress(), and org.onosproject.net.DefaultEdgeLinkTest.phantomIngress().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/Link.java