onos: org.onosproject.cord.gui.model.BundleDescriptor Interface Reference
org.onosproject.cord.gui.model.BundleDescriptor Interface Reference
Defines a bundle of XOS functions.
Public Member Functions
String id ()
Bundle internal identifier.
String displayName ()
Bundle display name.
String description ()
Textual description of this bundle.
Set< XosFunctionDescriptor > functions ()
The set of functions in this bundle instance.
Detailed Description
Defines a bundle of XOS functions.
Definition at line 25 of file BundleDescriptor.java.
Member Function Documentation
String org.onosproject.cord.gui.model.BundleDescriptor.description ()
Textual description of this bundle.
Returns
description
Implemented in org.onosproject.cord.gui.model.DefaultBundleDescriptor.
String org.onosproject.cord.gui.model.BundleDescriptor.displayName ()
Bundle display name.
Returns
display name
Implemented in org.onosproject.cord.gui.model.DefaultBundleDescriptor.
Referenced by org.onosproject.cord.gui.model.BundleFactoryTest.basicBundle(), and org.onosproject.cord.gui.model.BundleFactoryTest.familyBundle().
Set<XosFunctionDescriptor> org.onosproject.cord.gui.model.BundleDescriptor.functions ()
The set of functions in this bundle instance.
Returns
the functions
Implemented in org.onosproject.cord.gui.model.DefaultBundleDescriptor.
String org.onosproject.cord.gui.model.BundleDescriptor.id ()
Bundle internal identifier.
Returns
bundle identifier
Implemented in org.onosproject.cord.gui.model.DefaultBundleDescriptor.
Referenced by org.onosproject.cord.gui.model.BundleFactoryTest.basicBundle(), and org.onosproject.cord.gui.model.BundleFactoryTest.familyBundle().
The documentation for this interface was generated from the following file:
apps/demo/cord-gui/src/main/java/org/onosproject/cord/gui/model/BundleDescriptor.java