onos: org.onosproject.dhcp.DhcpService Interface Reference
org.onosproject.dhcp.DhcpService Interface Reference
DHCP Service Interface.
Public Member Functions
Map< HostId, IpAssignment > listMapping ()
Returns a collection of all the MacAddress to IPAddress mapping.
int getLeaseTime ()
Returns the default lease time granted by the DHCP Server.
int getRenewalTime ()
Returns the default renewal time granted by the DHCP Server.
int getRebindingTime ()
Returns the default rebinding time granted by the DHCP Server.
boolean setStaticMapping (MacAddress macID, Ip4Address ipAddress, boolean rangeNotEnforced, List< Ip4Address > addressList)
Registers a static IP mapping with the DHCP Server.
boolean removeStaticMapping (MacAddress macID)
Removes a static IP mapping with the DHCP Server.
Iterable< Ip4Address > getAvailableIPs ()
Returns the list of all the available IPs with the server.
Detailed Description
DHCP Service Interface.
Definition at line 29 of file DhcpService.java.
Member Function Documentation
Iterable<Ip4Address> org.onosproject.dhcp.DhcpService.getAvailableIPs ()
Returns the list of all the available IPs with the server.
Returns
list of available IPs
Implemented in org.onosproject.dhcp.impl.DhcpManager.
int org.onosproject.dhcp.DhcpService.getLeaseTime ()
Returns the default lease time granted by the DHCP Server.
Returns
lease time
Implemented in org.onosproject.dhcp.impl.DhcpManager.
Referenced by org.onosproject.dhcp.rest.DhcpWebResource.getConfigs().
int org.onosproject.dhcp.DhcpService.getRebindingTime ()
Returns the default rebinding time granted by the DHCP Server.
Returns
rebinding time
Implemented in org.onosproject.dhcp.impl.DhcpManager.
Referenced by org.onosproject.dhcp.rest.DhcpWebResource.getConfigs().
int org.onosproject.dhcp.DhcpService.getRenewalTime ()
Returns the default renewal time granted by the DHCP Server.
Returns
renewal time
Implemented in org.onosproject.dhcp.impl.DhcpManager.
Referenced by org.onosproject.dhcp.rest.DhcpWebResource.getConfigs().
Map<HostId, IpAssignment> org.onosproject.dhcp.DhcpService.listMapping ()
Returns a collection of all the MacAddress to IPAddress mapping.
Returns
collection of mappings.
Implemented in org.onosproject.dhcp.impl.DhcpManager.
boolean org.onosproject.dhcp.DhcpService.removeStaticMapping (MacAddress macID)
Removes a static IP mapping with the DHCP Server.
Parameters
macID macID of the client
Returns
true if the mapping was successfully removed, false otherwise
Implemented in org.onosproject.dhcp.impl.DhcpManager.
Referenced by org.onosproject.dhcp.cli.DhcpRemoveStaticMapping.execute().
boolean org.onosproject.dhcp.DhcpService.setStaticMapping (MacAddress macID, Ip4Address ipAddress, boolean rangeNotEnforced, List< Ip4Address > addressList)
Registers a static IP mapping with the DHCP Server.
Supports rangeNotEnforced option
Parameters
macID macID of the client
ipAddress IP Address requested for the client
rangeNotEnforced true if rangeNotEnforced was set and the mapping will be eternal
addressList subnetMask, DHCP/Router/DNS IP Addresses if rangeNotEnforced was set
Returns
true if the mapping was successfully added, false otherwise
Implemented in org.onosproject.dhcp.impl.DhcpManager.
Referenced by org.onosproject.dhcp.cli.DhcpSetStaticMapping.execute().
The documentation for this interface was generated from the following file:
apps/dhcp/api/src/main/java/org/onosproject/dhcp/DhcpService.java