onos: org.onosproject.core.MetricsHelper Interface Reference
org.onosproject.core.MetricsHelper Interface Reference
Collection of utility methods used for providing Metrics.
Public Member Functions
MetricsService metricsService ()
Returns MetricService instance.
default Timer createTimer (String component, String feature, String name)
Creates a Timer instance with given name.
Detailed Description
Collection of utility methods used for providing Metrics.
Definition at line 28 of file MetricsHelper.java.
Member Function Documentation
default Timer org.onosproject.core.MetricsHelper.createTimer (String component, String feature, String name)
Creates a Timer instance with given name.
Parameters
component component name
feature feature name
name timer name
Returns
Timer instance
Definition at line 46 of file MetricsHelper.java.
References org.onosproject.core.MetricsHelper.metricsService(), and create-flow.name.
Referenced by org.onosproject.cluster.impl.MastershipManager.activate().
MetricsService org.onosproject.core.MetricsHelper.metricsService ()
Returns MetricService instance.
Returns
MetricService instance
Implemented in org.onosproject.cluster.impl.MastershipManager.
Referenced by org.onosproject.core.MetricsHelper.createTimer().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/core/MetricsHelper.java