onos: org.onosproject.app.ApplicationDescription Interface Reference
org.onosproject.app.ApplicationDescription Interface Reference
Description of a network control/management application.
Public Member Functions
String name ()
Returns the application name id.
Version version ()
Returns the application version.
String description ()
Returns description of the application.
String origin ()
Returns the name of the application origin, group or company.
ApplicationRole role ()
Returns the role of the application.
Set< Permission > permissions ()
Returns the permissions requested by the application.
Optional< URI > featuresRepo ()
Returns the feature repository URI.
List< String > features ()
Returns the list of features comprising the application.
List< String > requiredApps ()
Returns list of required application names.
Detailed Description
Description of a network control/management application.
Definition at line 30 of file ApplicationDescription.java.
Member Function Documentation
String org.onosproject.app.ApplicationDescription.description ()
Returns description of the application.
Returns
application description text
Implemented in org.onosproject.app.DefaultApplicationDescription.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
List<String> org.onosproject.app.ApplicationDescription.features ()
Returns the list of features comprising the application.
At least one feature must be given.
Returns
application features
Implemented in org.onosproject.app.DefaultApplicationDescription.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics(), and org.onosproject.store.trivial.SimpleApplicationStore.create().
Optional<URI> org.onosproject.app.ApplicationDescription.featuresRepo ()
Returns the feature repository URI.
Null value signifies that the application did not provide its own features repository.
Returns
optional feature repo URL
Implemented in org.onosproject.app.DefaultApplicationDescription.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
String org.onosproject.app.ApplicationDescription.name ()
Returns the application name id.
Returns
application identifier
Implemented in org.onosproject.app.DefaultApplicationDescription.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.store.app.GossipApplicationStore.create(), org.onosproject.common.app.ApplicationArchive.saveApplication(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
String org.onosproject.app.ApplicationDescription.origin ()
Returns the name of the application origin, group or company.
Returns
application origin
Implemented in org.onosproject.app.DefaultApplicationDescription.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics(), and org.onosproject.store.trivial.SimpleApplicationStore.create().
Set<Permission> org.onosproject.app.ApplicationDescription.permissions ()
Returns the permissions requested by the application.
Returns
requested permissions
Implemented in org.onosproject.app.DefaultApplicationDescription.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics(), and org.onosproject.store.trivial.SimpleApplicationStore.create().
List<String> org.onosproject.app.ApplicationDescription.requiredApps ()
Returns list of required application names.
Returns
list of application names
Implemented in org.onosproject.app.DefaultApplicationDescription.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
ApplicationRole org.onosproject.app.ApplicationDescription.role ()
Returns the role of the application.
Returns
application role
Implemented in org.onosproject.app.DefaultApplicationDescription.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics().
Version org.onosproject.app.ApplicationDescription.version ()
Returns the application version.
Returns
application version
Implemented in org.onosproject.app.DefaultApplicationDescription.
Referenced by org.onosproject.app.DefaultApplicationDescriptionTest.basics(), and org.onosproject.store.trivial.SimpleApplicationStore.create().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/app/ApplicationDescription.java