onos: org.onosproject.net.Host Interface Reference
org.onosproject.net.Host Interface Reference
Abstraction of an end-station host on the network, essentially a NIC.
Public Member Functions
HostId id ()
Host identification.
MacAddress mac ()
Returns the host MAC address.
VlanId vlan ()
Returns the VLAN ID tied to this host.
Set< IpAddress > ipAddresses ()
Returns set of IP addresses currently bound to the host MAC address.
HostLocation location ()
Returns the most recent host location where the host attaches to the network edge.
Public Member Functions inherited from org.onosproject.net.Annotated
Annotations annotations ()
Returns the key/value annotations.
Public Member Functions inherited from org.onosproject.net.Provided
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Detailed Description
Abstraction of an end-station host on the network, essentially a NIC.
Definition at line 27 of file Host.java.
Member Function Documentation
HostId org.onosproject.net.Host.id ()
Host identification.
Returns
host id
Implements org.onosproject.net.Element.
Implemented in org.onosproject.net.DefaultHost.
Referenced by org.onosproject.net.DefaultHostTest.basics(), org.onosproject.net.DefaultEdgeLink.createEdgeLink(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.hostMessage(), and org.onosproject.cli.net.HostsListCommand.printHost().
Set<IpAddress> org.onosproject.net.Host.ipAddresses ()
Returns set of IP addresses currently bound to the host MAC address.
Returns
set of IP addresses; empty if no IP address is bound
Implemented in org.onosproject.net.DefaultHost.
Referenced by org.onosproject.net.DefaultHostTest.basics(), org.onosproject.codec.impl.HostCodec.encode(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.hostMessage().
HostLocation org.onosproject.net.Host.location ()
Returns the most recent host location where the host attaches to the network edge.
Returns
host location
Implemented in org.onosproject.net.DefaultHost.
Referenced by org.onosproject.net.DefaultHostTest.basics(), org.onosproject.net.DefaultEdgeLink.createEdgeLink(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.hostMessage(), and org.onosproject.cli.net.HostsListCommand.printHost().
MacAddress org.onosproject.net.Host.mac ()
Returns the host MAC address.
Returns
mac address
Implemented in org.onosproject.net.DefaultHost.
Referenced by org.onosproject.net.DefaultHostTest.basics(), org.onosproject.codec.impl.HostCodec.encode(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.hostMessage(), and org.onosproject.net.intent.impl.compiler.HostToHostIntentCompilerTest.setUp().
VlanId org.onosproject.net.Host.vlan ()
Returns the VLAN ID tied to this host.
Returns
VLAN ID value
Implemented in org.onosproject.net.DefaultHost.
Referenced by org.onosproject.net.DefaultHostTest.basics(), org.onosproject.cli.net.HostsListCommand.printHost(), and org.onosproject.net.intent.impl.compiler.HostToHostIntentCompilerTest.setUp().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/Host.java