onos: org.onosproject.vtnrsc.portpair.PortPairService Interface Reference
org.onosproject.vtnrsc.portpair.PortPairService Interface Reference
Service for interacting with the inventory of port pairs.
Public Member Functions
boolean exists (PortPairId portPairId)
Returns if the port pair is existed.
int getPortPairCount ()
Returns the number of port pairs known to the system.
Iterable< PortPair > getPortPairs ()
Returns an iterable collection of the currently known port pairs.
PortPair getPortPair (PortPairId portPairId)
Returns the portPair with the given identifier.
boolean createPortPair (PortPair portPair)
Creates a PortPair in the store.
boolean updatePortPair (PortPair portPair)
Updates the portPair in the store.
boolean removePortPair (PortPairId portPairId)
Deletes portPair by given portPairId.
Detailed Description
Service for interacting with the inventory of port pairs.
Definition at line 24 of file PortPairService.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.portpair.PortPairService.createPortPair (PortPair portPair)
Creates a PortPair in the store.
Parameters
portPair the port pair to create
Returns
true if given port pair is created successfully.
Implemented in org.onosproject.vtnrsc.portpair.impl.PortPairManager.
Referenced by org.onosproject.vtnweb.resources.PortPairResourceTest.testPost().
boolean org.onosproject.vtnrsc.portpair.PortPairService.exists (PortPairId portPairId)
Returns if the port pair is existed.
Parameters
portPairId port pair identifier
Returns
true or false if one with the given identifier exists.
Implemented in org.onosproject.vtnrsc.portpair.impl.PortPairManager.
Referenced by org.onosproject.vtnweb.resources.PortPairResourceTest.testGetPortPairId().
PortPair org.onosproject.vtnrsc.portpair.PortPairService.getPortPair (PortPairId portPairId)
Returns the portPair with the given identifier.
Parameters
portPairId port pair identifier
Returns
PortPair or null if port pair with the given identifier is not known.
Implemented in org.onosproject.vtnrsc.portpair.impl.PortPairManager.
Referenced by org.onosproject.vtnweb.resources.PortPairResourceTest.testBadGet(), and org.onosproject.vtnweb.resources.PortPairResourceTest.testGetPortPairId().
int org.onosproject.vtnrsc.portpair.PortPairService.getPortPairCount ()
Returns the number of port pairs known to the system.
Returns
number of port pairs.
Implemented in org.onosproject.vtnrsc.portpair.impl.PortPairManager.
Iterable<PortPair> org.onosproject.vtnrsc.portpair.PortPairService.getPortPairs ()
Returns an iterable collection of the currently known port pairs.
Returns
collection of port pairs.
Implemented in org.onosproject.vtnrsc.portpair.impl.PortPairManager.
Referenced by org.onosproject.vtnweb.resources.PortPairResourceTest.testPortPairsEmpty().
boolean org.onosproject.vtnrsc.portpair.PortPairService.removePortPair (PortPairId portPairId)
Deletes portPair by given portPairId.
Parameters
portPairId id of port pair to remove
Returns
true if the give port pair is deleted successfully.
Implemented in org.onosproject.vtnrsc.portpair.impl.PortPairManager.
Referenced by org.onosproject.vtnweb.resources.PortPairResourceTest.testDelete().
boolean org.onosproject.vtnrsc.portpair.PortPairService.updatePortPair (PortPair portPair)
Updates the portPair in the store.
Parameters
portPair the port pair to update
Returns
true if given port pair is updated successfully.
Implemented in org.onosproject.vtnrsc.portpair.impl.PortPairManager.
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/portpair/PortPairService.java