onos: org.onosproject.net.topology.TopologyService Interface Reference
org.onosproject.net.topology.TopologyService Interface Reference
Service for providing network topology information.
Public Member Functions
Topology currentTopology ()
Returns the current topology descriptor.
boolean isLatest (Topology topology)
Indicates whether the specified topology is the latest or not.
TopologyGraph getGraph (Topology topology)
Returns the graph view of the specified topology.
Set< TopologyCluster > getClusters (Topology topology)
Returns the set of clusters in the specified topology.
TopologyCluster getCluster (Topology topology, ClusterId clusterId)
Returns the cluster with the specified ID.
Set< DeviceId > getClusterDevices (Topology topology, TopologyCluster cluster)
Returns the set of devices that belong to the specified cluster.
Set< Link > getClusterLinks (Topology topology, TopologyCluster cluster)
Returns the set of links that form the specified cluster.
Set< Path > getPaths (Topology topology, DeviceId src, DeviceId dst)
Returns the set of all shortest paths, precomputed in terms of hop-count, between the specified source and destination devices.
Set< Path > getPaths (Topology topology, DeviceId src, DeviceId dst, LinkWeight weight)
Returns the set of all shortest paths, computed using the supplied edge-weight entity, between the specified source and destination devices.
Set< DisjointPath > getDisjointPaths (Topology topology, DeviceId src, DeviceId dst)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Set< DisjointPath > getDisjointPaths (Topology topology, DeviceId src, DeviceId dst, LinkWeight weight)
Returns the set of all disjoint shortest path pairs, computed using the supplied edge-weight entity, between the specified source and destination devices.
Set< DisjointPath > getDisjointPaths (Topology topology, DeviceId src, DeviceId dst, Map< Link, Object > riskProfile)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Set< DisjointPath > getDisjointPaths (Topology topology, DeviceId src, DeviceId dst, LinkWeight weight, Map< Link, Object > riskProfile)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
boolean isInfrastructure (Topology topology, ConnectPoint connectPoint)
Indicates whether the specified connection point is part of the network infrastructure or part of network edge.
boolean isBroadcastPoint (Topology topology, ConnectPoint connectPoint)
Indicates whether broadcast is allowed for traffic received on the specified connection point.
Detailed Description
Service for providing network topology information.
Definition at line 31 of file TopologyService.java.
Member Function Documentation
Topology org.onosproject.net.topology.TopologyService.currentTopology ()
Returns the current topology descriptor.
Returns
current topology
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
TopologyCluster org.onosproject.net.topology.TopologyService.getCluster (Topology topology, ClusterId clusterId)
Returns the cluster with the specified ID.
Parameters
topology topology descriptor
clusterId cluster identifier
Returns
topology cluster
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Set<DeviceId> org.onosproject.net.topology.TopologyService.getClusterDevices (Topology topology, TopologyCluster cluster)
Returns the set of devices that belong to the specified cluster.
Parameters
topology topology descriptor
cluster topology cluster
Returns
set of cluster devices
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.clusters().
Set<Link> org.onosproject.net.topology.TopologyService.getClusterLinks (Topology topology, TopologyCluster cluster)
Returns the set of links that form the specified cluster.
Parameters
topology topology descriptor
cluster topology cluster
Returns
set of cluster links
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.clusters().
Set<TopologyCluster> org.onosproject.net.topology.TopologyService.getClusters (Topology topology)
Returns the set of clusters in the specified topology.
Parameters
topology topology descriptor
Returns
set of topology clusters
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.clusters(), org.onosproject.cli.net.ClusterIdCompleter.complete(), and org.onosproject.cli.SummaryCommand.execute().
Set<DisjointPath> org.onosproject.net.topology.TopologyService.getDisjointPaths (Topology topology, DeviceId src, DeviceId dst)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Parameters
topology topology descriptor
src source device
dst destination device
Returns
set of all shortest paths between the two devices
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Referenced by org.onosproject.net.topology.impl.PathManager.getDisjointPaths().
Set<DisjointPath> org.onosproject.net.topology.TopologyService.getDisjointPaths (Topology topology, DeviceId src, DeviceId dst, LinkWeight weight)
Returns the set of all disjoint shortest path pairs, computed using the supplied edge-weight entity, between the specified source and destination devices.
Parameters
topology topology descriptor
src source device
dst destination device
weight edge-weight entity
Returns
set of all shortest paths between the two devices
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Set<DisjointPath> org.onosproject.net.topology.TopologyService.getDisjointPaths (Topology topology, DeviceId src, DeviceId dst, Map< Link, Object > riskProfile)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Parameters
topology topology descriptor
src source device
dst destination device
riskProfile map of edges to risk profiles
Returns
set of all shortest paths between the two devices
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Set<DisjointPath> org.onosproject.net.topology.TopologyService.getDisjointPaths (Topology topology, DeviceId src, DeviceId dst, LinkWeight weight, Map< Link, Object > riskProfile)
Returns the set of all disjoint shortest path pairs, precomputed in terms of hop-count, between the specified source and destination devices.
Parameters
topology topology descriptor
src source device
dst destination device
weight edge-weight entity
riskProfile map of edges to risk profiles
Returns
set of all shortest paths between the two devices
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
TopologyGraph org.onosproject.net.topology.TopologyService.getGraph (Topology topology)
Returns the graph view of the specified topology.
Parameters
topology topology descriptor
Returns
topology graph view
Implemented in org.onosproject.net.topology.impl.TopologyManager, org.onosproject.net.topology.TopologyServiceAdapter, and org.onosproject.flowanalyzer.MockTopologyService.
Set<Path> org.onosproject.net.topology.TopologyService.getPaths (Topology topology, DeviceId src, DeviceId dst)
Returns the set of all shortest paths, precomputed in terms of hop-count, between the specified source and destination devices.
Parameters
topology topology descriptor
src source device
dst destination device
Returns
set of all shortest paths between the two devices
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Referenced by org.onosproject.net.topology.impl.PathManager.getPaths().
Set<Path> org.onosproject.net.topology.TopologyService.getPaths (Topology topology, DeviceId src, DeviceId dst, LinkWeight weight)
Returns the set of all shortest paths, computed using the supplied edge-weight entity, between the specified source and destination devices.
Parameters
topology topology descriptor
src source device
dst destination device
weight edge-weight entity
Returns
set of all shortest paths between the two devices
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
boolean org.onosproject.net.topology.TopologyService.isBroadcastPoint (Topology topology, ConnectPoint connectPoint)
Indicates whether broadcast is allowed for traffic received on the specified connection point.
Parameters
topology topology descriptor
connectPoint connection point
Returns
true if broadcast is permissible
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.structure().
boolean org.onosproject.net.topology.TopologyService.isInfrastructure (Topology topology, ConnectPoint connectPoint)
Indicates whether the specified connection point is part of the network infrastructure or part of network edge.
Parameters
topology topology descriptor
connectPoint connection point
Returns
true of connection point is in infrastructure; false if edge
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.structure().
boolean org.onosproject.net.topology.TopologyService.isLatest (Topology topology)
Indicates whether the specified topology is the latest or not.
Parameters
topology topology descriptor
Returns
true if the topology is the most recent; false otherwise
Implemented in org.onosproject.net.topology.impl.TopologyManager, and org.onosproject.net.topology.TopologyServiceAdapter.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.basics().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/topology/TopologyService.java