onos: org.onosproject.net.Description Interface Reference
org.onosproject.net.Description Interface Reference
Base abstraction of a piece of information about network elements.
Public Member Functions
SparseAnnotations annotations ()
Returns the key/value annotations.
Detailed Description
Base abstraction of a piece of information about network elements.
Definition at line 21 of file Description.java.
Member Function Documentation
SparseAnnotations org.onosproject.net.Description.annotations ()
Returns the key/value annotations.
Returns
key/value annotations
Implements org.onosproject.net.Annotated.
Referenced by org.onosproject.net.host.impl.BasicHostOperator.combine(), org.onosproject.net.device.impl.BasicDeviceOperator.combine(), org.onosproject.net.link.impl.BasicLinkOperator.combine(), org.onosproject.net.device.impl.OpticalPortOperator.combine(), org.onosproject.driver.ovsdb.OvsdbTunnelConfig.createTunnelInterface(), org.onosproject.net.host.impl.BasicHostOperatorTest.testDescOps(), org.onosproject.net.link.impl.BasicLinkOperatorTest.testDescOps(), org.onosproject.net.device.impl.BasicDeviceOperatorTest.testDescOps(), and org.onosproject.incubator.rpc.grpc.GrpcDeviceUtils.translate().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/Description.java