onos: org.onosproject.vtnrsc.PortPairGroup Interface Reference
org.onosproject.vtnrsc.PortPairGroup Interface Reference
Abstraction of an entity providing Port Pair Group information.
Classes
interface Builder
A port pair group builder.
Public Member Functions
PortPairGroupId portPairGroupId ()
Returns the ID of this port pair group.
TenantId tenantId ()
Returns the tenant id of this port pair group.
String name ()
Returns the name of this port pair group.
String description ()
Returns the description of this port pair group.
List< PortPairId > portPairs ()
Returns the list of port pairs associated with this port pair group.
boolean exactMatch (PortPairGroup portPairGroup)
Returns whether this port pair group is an exact match to the port pair group given in the argument.
Detailed Description
Abstraction of an entity providing Port Pair Group information.
A port pair group consists of one or more port pairs.
Definition at line 24 of file PortPairGroup.java.
Member Function Documentation
String org.onosproject.vtnrsc.PortPairGroup.description ()
Returns the description of this port pair group.
Returns
description of port pair group
Implemented in org.onosproject.vtnrsc.DefaultPortPairGroup.
Referenced by org.onosproject.vtnweb.web.PortPairGroupCodecTest.codecPortPairGroupTest().
boolean org.onosproject.vtnrsc.PortPairGroup.exactMatch (PortPairGroup portPairGroup)
Returns whether this port pair group is an exact match to the port pair group given in the argument.
Exact match means the Port pairs match with the given port pair group. It does not consider the port pair group id, name and description.
Parameters
portPairGroup other port pair group to match against
Returns
true if the port pairs are an exact match, otherwise false
Implemented in org.onosproject.vtnrsc.DefaultPortPairGroup.
String org.onosproject.vtnrsc.PortPairGroup.name ()
Returns the name of this port pair group.
Returns
name of port pair group
Implemented in org.onosproject.vtnrsc.DefaultPortPairGroup.
Referenced by org.onosproject.vtnweb.web.PortPairGroupCodecTest.codecPortPairGroupTest(), tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
PortPairGroupId org.onosproject.vtnrsc.PortPairGroup.portPairGroupId ()
Returns the ID of this port pair group.
Returns
the port pair group id
Implemented in org.onosproject.vtnrsc.DefaultPortPairGroup.
Referenced by org.onosproject.vtnweb.web.PortPairGroupCodecTest.codecPortPairGroupTest(), org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.createPortPairGroup(), org.onosproject.vtnrsc.DefaultPortPairGroup.exactMatch(), and org.onosproject.vtnrsc.portpairgroup.impl.PortPairGroupManager.updatePortPairGroup().
List<PortPairId> org.onosproject.vtnrsc.PortPairGroup.portPairs ()
Returns the list of port pairs associated with this port pair group.
Returns
list of port pairs
Implemented in org.onosproject.vtnrsc.DefaultPortPairGroup.
Referenced by org.onosproject.vtnweb.web.PortPairGroupCodecTest.codecPortPairGroupTest().
TenantId org.onosproject.vtnrsc.PortPairGroup.tenantId ()
Returns the tenant id of this port pair group.
Returns
the tenant id
Implemented in org.onosproject.vtnrsc.DefaultPortPairGroup.
Referenced by org.onosproject.vtnweb.web.PortPairGroupCodecTest.codecPortPairGroupTest(), org.onosproject.vtnweb.web.PortPairGroupCodec.encode(), and org.onosproject.vtnrsc.DefaultPortPairGroup.exactMatch().
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/PortPairGroup.java