onos: org.onosproject.net.topology.TopologyCluster Interface Reference
org.onosproject.net.topology.TopologyCluster Interface Reference
Representation of an SCC (strongly-connected component) in a network topology.
Public Member Functions
ClusterId id ()
Returns the cluster id.
int deviceCount ()
Returns the number of devices in the cluster.
int linkCount ()
Returns the number of infrastructure links in the cluster.
TopologyVertex root ()
Returns the cluster root vertex.
Detailed Description
Representation of an SCC (strongly-connected component) in a network topology.
Definition at line 21 of file TopologyCluster.java.
Member Function Documentation
int org.onosproject.net.topology.TopologyCluster.deviceCount ()
Returns the number of devices in the cluster.
Returns
number of cluster devices
Implemented in org.onosproject.net.topology.DefaultTopologyCluster.
Referenced by org.onosproject.net.topology.DefaultTopologyClusterTest.basics(), org.onosproject.net.topology.impl.TopologyManagerTest.clusters(), and org.onosproject.codec.impl.TopologyClusterCodec.encode().
ClusterId org.onosproject.net.topology.TopologyCluster.id ()
Returns the cluster id.
Returns
cluster identifier
Implemented in org.onosproject.net.topology.DefaultTopologyCluster.
Referenced by org.onosproject.net.topology.DefaultTopologyClusterTest.basics(), and org.onosproject.common.DefaultTopology.isBroadcastPoint().
int org.onosproject.net.topology.TopologyCluster.linkCount ()
Returns the number of infrastructure links in the cluster.
Returns
number of cluster links
Implemented in org.onosproject.net.topology.DefaultTopologyCluster.
Referenced by org.onosproject.net.topology.DefaultTopologyClusterTest.basics(), org.onosproject.net.topology.impl.TopologyManagerTest.clusters(), and org.onosproject.codec.impl.TopologyClusterCodec.encode().
TopologyVertex org.onosproject.net.topology.TopologyCluster.root ()
Returns the cluster root vertex.
Returns
cluster root vertex
Implemented in org.onosproject.net.topology.DefaultTopologyCluster.
Referenced by org.onosproject.net.topology.DefaultTopologyClusterTest.basics(), and org.onosproject.codec.impl.TopologyClusterCodec.encode().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/topology/TopologyCluster.java