onos: org.onosproject.vtnrsc.VirtualPort Interface Reference
org.onosproject.vtnrsc.VirtualPort Interface Reference
Representation of the VirtualPort.
Classes
enum State
Coarse classification of the type of the virtual port.
Public Member Functions
VirtualPortId portId ()
Returns the virtualPort identifier.
TenantNetworkId networkId ()
Returns the network identifier.
String name ()
Returns the symbolic name for the virtualPort.
boolean adminStateUp ()
Returns the administrative status of the port,which is up(true) or down(false).
State state ()
Returns the state.
MacAddress macAddress ()
Returns the MAC address.
TenantId tenantId ()
Returns the port tenantId.
DeviceId deviceId ()
Returns the device identifier.
String deviceOwner ()
Returns the identifier of the entity that uses this port.
Collection< AllowedAddressPair > allowedAddressPairs ()
Returns the virtualPort allowedAddressPairs.
Set< FixedIp > fixedIps ()
Returns set of IP addresses for the port, include the IP addresses and subnet identity.
BindingHostId bindingHostId ()
Returns the virtualPort bindinghostId.
String bindingVnicType ()
Returns the virtualPort bindingVnicType.
String bindingVifType ()
Returns the virtualPort bindingVifType.
String bindingVifDetails ()
Returns the virtualPort bindingvifDetail.
Iterable< SecurityGroup > securityGroups ()
Returns the security groups.
Detailed Description
Representation of the VirtualPort.
Definition at line 27 of file VirtualPort.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.VirtualPort.adminStateUp ()
Returns the administrative status of the port,which is up(true) or down(false).
Returns
true if the administrative status of the port is up
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
Collection<AllowedAddressPair> org.onosproject.vtnrsc.VirtualPort.allowedAddressPairs ()
Returns the virtualPort allowedAddressPairs.
Returns
virtualPort allowedAddressPairs
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
BindingHostId org.onosproject.vtnrsc.VirtualPort.bindingHostId ()
Returns the virtualPort bindinghostId.
Returns
virtualPort bindinghostId
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
String org.onosproject.vtnrsc.VirtualPort.bindingVifDetails ()
Returns the virtualPort bindingvifDetail.
Returns
virtualPort bindingvifDetail
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
Referenced by org.onosproject.vtnweb.web.VirtualPortCodec.encode().
String org.onosproject.vtnrsc.VirtualPort.bindingVifType ()
Returns the virtualPort bindingVifType.
Returns
virtualPort bindingVifType
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
String org.onosproject.vtnrsc.VirtualPort.bindingVnicType ()
Returns the virtualPort bindingVnicType.
Returns
virtualPort bindingVnicType
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
DeviceId org.onosproject.vtnrsc.VirtualPort.deviceId ()
Returns the device identifier.
Returns
deviceId
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
Referenced by org.onosproject.vtnweb.web.VirtualPortCodec.encode().
String org.onosproject.vtnrsc.VirtualPort.deviceOwner ()
Returns the identifier of the entity that uses this port.
Returns
deviceOwner
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
Set<FixedIp> org.onosproject.vtnrsc.VirtualPort.fixedIps ()
Returns set of IP addresses for the port, include the IP addresses and subnet identity.
Returns
FixedIps Set of fixedIp
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
MacAddress org.onosproject.vtnrsc.VirtualPort.macAddress ()
Returns the MAC address.
Returns
MAC Address
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
Referenced by org.onosproject.vtnweb.web.VirtualPortCodec.encode().
String org.onosproject.vtnrsc.VirtualPort.name ()
Returns the symbolic name for the virtualPort.
Returns
virtualPort name
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
TenantNetworkId org.onosproject.vtnrsc.VirtualPort.networkId ()
Returns the network identifier.
Returns
tenantNetwork identifier
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
Referenced by org.onosproject.vtnweb.web.VirtualPortCodec.encode().
VirtualPortId org.onosproject.vtnrsc.VirtualPort.portId ()
Returns the virtualPort identifier.
Returns
virtualPort identifier
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
Referenced by org.onosproject.vtnrsc.service.impl.VtnRscManager.getSFToSFFMaping().
Iterable<SecurityGroup> org.onosproject.vtnrsc.VirtualPort.securityGroups ()
Returns the security groups.
Returns
port security groups
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
State org.onosproject.vtnrsc.VirtualPort.state ()
Returns the state.
Returns
state
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
TenantId org.onosproject.vtnrsc.VirtualPort.tenantId ()
Returns the port tenantId.
Returns
port tenantId
Implemented in org.onosproject.vtnrsc.DefaultVirtualPort.
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/VirtualPort.java