onos: org.onosproject.incubator.net.intf.InterfaceService Interface Reference
org.onosproject.incubator.net.intf.InterfaceService Interface Reference
Service for interacting with interfaces.
Public Member Functions
Set< Interface > getInterfaces ()
Returns the set of all interfaces in the system.
Set< Interface > getInterfacesByPort (ConnectPoint port)
Returns the set of interfaces configured on the given port.
Set< Interface > getInterfacesByIp (IpAddress ip)
Returns the set of interfaces with the given IP address.
Set< Interface > getInterfacesByVlan (VlanId vlan)
Returns the set of interfaces in the given VLAN.
Interface getMatchingInterface (IpAddress ip)
Returns an interface that has an address that is in the same subnet as the given IP address.
Detailed Description
Service for interacting with interfaces.
Definition at line 30 of file InterfaceService.java.
Member Function Documentation
Set<Interface> org.onosproject.incubator.net.intf.InterfaceService.getInterfaces ()
Returns the set of all interfaces in the system.
Returns
set of interfaces
Implemented in org.onosproject.incubator.net.intf.impl.InterfaceManager.
Referenced by org.onosproject.sdnip.PeerConnectivityManagerTest.testNullInterfaces().
Set<Interface> org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByIp (IpAddress ip)
Returns the set of interfaces with the given IP address.
Parameters
ip IP address
Returns
set of interfaces
Implemented in org.onosproject.incubator.net.intf.impl.InterfaceManager.
Referenced by org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testConfiguredVlan(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testConfiguredVlanOnInterfaces(), org.onosproject.sdnip.PeerConnectivityManagerTest.testNullInterfaces(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyDifferentVlan(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyDifferentVlanIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUs(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyToRequestFromUsIpv6(), org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyUnknown(), and org.onosproject.net.proxyarp.impl.ProxyArpManagerTest.testReplyUnknownIpv6().
Set<Interface> org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByPort (ConnectPoint port)
Returns the set of interfaces configured on the given port.
Parameters
port connect point
Returns
set of interfaces
Implemented in org.onosproject.incubator.net.intf.impl.InterfaceManager.
Referenced by org.onosproject.sdnip.PeerConnectivityManagerTest.testNullInterfaces().
Set<Interface> org.onosproject.incubator.net.intf.InterfaceService.getInterfacesByVlan (VlanId vlan)
Returns the set of interfaces in the given VLAN.
Parameters
vlan VLAN ID of the interfaces
Returns
set of interfaces
Implemented in org.onosproject.incubator.net.intf.impl.InterfaceManager.
Interface org.onosproject.incubator.net.intf.InterfaceService.getMatchingInterface (IpAddress ip)
Returns an interface that has an address that is in the same subnet as the given IP address.
Parameters
ip IP address to find matching subnet interface for
Returns
interface
Implemented in org.onosproject.incubator.net.intf.impl.InterfaceManager.
Referenced by org.onosproject.sdnip.cli.AddPeerCommand.execute(), org.onosproject.routing.config.impl.RoutingConfigurationImpl.getBgpPeerConnectPoints(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExist(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExistWithVlan(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExist(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExistWithVlan(), and org.onosproject.sdnip.PeerConnectivityManagerTest.testNullInterfaces().
The documentation for this interface was generated from the following file:
incubator/api/src/main/java/org/onosproject/incubator/net/intf/InterfaceService.java