onos: org.onosproject.metrics.intent.IntentMetricsService Interface Reference
org.onosproject.metrics.intent.IntentMetricsService Interface Reference
Service interface exported by IntentMetrics.
Public Member Functions
List< IntentEvent > getEvents ()
Gets the last saved intent events.
EventMetric intentSubmittedEventMetric ()
Gets the Event Metric for the intent INSTALL_REQ events.
EventMetric intentInstalledEventMetric ()
Gets the Event Metric for the intent INSTALLED events.
EventMetric intentFailedEventMetric ()
Gets the Event Metric for the intent FAILED events.
EventMetric intentWithdrawRequestedEventMetric ()
Gets the Event Metric for the intent WITHDRAW_REQ events.
EventMetric intentWithdrawnEventMetric ()
Gets the Event Metric for the intent WITHDRAWN events.
EventMetric intentPurgedEventMetric ()
Gets the Event Metric for the intent PURGED events.
Detailed Description
Service interface exported by IntentMetrics.
Definition at line 25 of file IntentMetricsService.java.
Member Function Documentation
List<IntentEvent> org.onosproject.metrics.intent.IntentMetricsService.getEvents ()
Gets the last saved intent events.
Returns
the last saved intent events
Implemented in org.onosproject.metrics.intent.IntentMetrics.
Referenced by org.onosproject.metrics.intent.cli.IntentEventsListCommand.execute().
EventMetric org.onosproject.metrics.intent.IntentMetricsService.intentFailedEventMetric ()
Gets the Event Metric for the intent FAILED events.
Returns
the Event Metric for the intent FAILED events
Implemented in org.onosproject.metrics.intent.IntentMetrics.
Referenced by org.onosproject.metrics.intent.cli.IntentEventsMetricsCommand.execute().
EventMetric org.onosproject.metrics.intent.IntentMetricsService.intentInstalledEventMetric ()
Gets the Event Metric for the intent INSTALLED events.
Returns
the Event Metric for the intent INSTALLED events
Implemented in org.onosproject.metrics.intent.IntentMetrics.
Referenced by org.onosproject.metrics.intent.cli.IntentEventsMetricsCommand.execute().
EventMetric org.onosproject.metrics.intent.IntentMetricsService.intentPurgedEventMetric ()
Gets the Event Metric for the intent PURGED events.
Returns
the Event Metric for the intent PURGED events
Implemented in org.onosproject.metrics.intent.IntentMetrics.
Referenced by org.onosproject.metrics.intent.cli.IntentEventsMetricsCommand.execute().
EventMetric org.onosproject.metrics.intent.IntentMetricsService.intentSubmittedEventMetric ()
Gets the Event Metric for the intent INSTALL_REQ events.
Returns
the Event Metric for the intent INSTALL_REQ events
Implemented in org.onosproject.metrics.intent.IntentMetrics.
Referenced by org.onosproject.metrics.intent.cli.IntentEventsMetricsCommand.execute().
EventMetric org.onosproject.metrics.intent.IntentMetricsService.intentWithdrawnEventMetric ()
Gets the Event Metric for the intent WITHDRAWN events.
Returns
the Event Metric for the intent WITHDRAWN events
Implemented in org.onosproject.metrics.intent.IntentMetrics.
Referenced by org.onosproject.metrics.intent.cli.IntentEventsMetricsCommand.execute().
EventMetric org.onosproject.metrics.intent.IntentMetricsService.intentWithdrawRequestedEventMetric ()
Gets the Event Metric for the intent WITHDRAW_REQ events.
Returns
the Event Metric for the intent WITHDRAW_REQ events
Implemented in org.onosproject.metrics.intent.IntentMetrics.
Referenced by org.onosproject.metrics.intent.cli.IntentEventsMetricsCommand.execute().
The documentation for this interface was generated from the following file:
apps/metrics/src/main/java/org/onosproject/metrics/intent/IntentMetricsService.java