onos: org.onosproject.bgp.controller.BgpLinkListener Interface Reference
org.onosproject.bgp.controller.BgpLinkListener Interface Reference
Allows for providers interested in Link events to be notified.
Public Member Functions
void addLink (BgpLinkLsNlriVer4 linkNlri)
Notify that got a packet of link from network and need do processing.
void deleteLink (BgpLinkLsNlriVer4 linkNlri)
Notify that got a packet of link from network and need do processing.
Detailed Description
Allows for providers interested in Link events to be notified.
Definition at line 20 of file BgpLinkListener.java.
Member Function Documentation
void org.onosproject.bgp.controller.BgpLinkListener.addLink (BgpLinkLsNlriVer4 linkNlri)
Notify that got a packet of link from network and need do processing.
Parameters
linkNlri bgp link
Referenced by obelisk.ObeliskTopo.__init__(), topo-200sw-linkalarm.MyTopo.__init__(), chordal.chordalTopo.__init__(), rftesttopo.ReactiveForwardingTestTopo.__init__(), attmpls.AttMplsTopo.__init__(), optical2.OpticalTopo.__init__(), newFuncTopo.MyTopo.__init__(), onos.ControlNetwork.__init__(), optical2.OpticalTopo.addIntf(), optical.OpticalTopo.addIntf(), metro.FabricDomain.addTether(), fractal.FractalTopo.build(), opticalTestBig.BigOpticalTopo.build(), opticalTest.SmallOpticalTopo.build(), tower.TowerTopo.build(), attmplsfast.AttMplsTopo.build(), optical.OpticalTopo.build(), tutorial.SdnIpTopo.build(), tutorial_ipv6.SdnIpTopo.build(), metro.OpticalDomain.build(), and metro.FabricDomain.build().
void org.onosproject.bgp.controller.BgpLinkListener.deleteLink (BgpLinkLsNlriVer4 linkNlri)
Notify that got a packet of link from network and need do processing.
Parameters
linkNlri bgp link
The documentation for this interface was generated from the following file:
bgp/api/src/main/java/org/onosproject/bgp/controller/BgpLinkListener.java