onos: org.onosproject.net.Provided Interface Reference
org.onosproject.net.Provided Interface Reference
Abstraction of an entity supplied by a provider.
Public Member Functions
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Detailed Description
Abstraction of an entity supplied by a provider.
Definition at line 23 of file Provided.java.
Member Function Documentation
ProviderId org.onosproject.net.Provided.providerId ()
Returns the identifier of the provider which supplied the entity.
Returns
provider identification
Implemented in org.onosproject.incubator.net.resource.label.DefaultLabelResource, and org.onosproject.net.AbstractModel.
Referenced by org.onosproject.net.DefaultHostTest.basics(), org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.createOrUpdateTunnel(), org.onosproject.incubator.store.tunnel.impl.DistributedTunnelStore.deleteTunnel(), org.onosproject.store.trivial.SimpleLinkStore.removeOrDownLink(), org.onosproject.store.link.impl.ECLinkStore.removeOrDownLink(), org.onosproject.store.link.impl.GossipLinkStore.removeOrDownLink(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostExists(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostExists(), and org.onosproject.incubator.net.tunnel.impl.TunnelManager.updateTunnel().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/Provided.java