onos: org.onosproject.net.meter.MeterRequest Interface Reference
org.onosproject.net.meter.MeterRequest Interface Reference
Represents a generalized meter request to be deployed on a device.
Classes
interface Builder
A meter builder.
enum Type
Public Member Functions
DeviceId deviceId ()
The target device for this meter.
ApplicationId appId ()
The id of the application which created this meter.
Meter.Unit unit ()
The unit used within this meter.
boolean isBurst ()
Signals whether this meter applies to bursts only.
Collection< Band > bands ()
The collection of bands to apply on the dataplane.
Optional< MeterContext > context ()
Returns the callback context for this meter.
Detailed Description
Represents a generalized meter request to be deployed on a device.
Definition at line 27 of file MeterRequest.java.
Member Function Documentation
ApplicationId org.onosproject.net.meter.MeterRequest.appId ()
The id of the application which created this meter.
Returns
an application id
Implemented in org.onosproject.net.meter.DefaultMeterRequest.
Referenced by org.onosproject.incubator.net.meter.impl.MeterManager.submit(), and org.onosproject.incubator.net.meter.impl.MeterManager.withdraw().
Collection<Band> org.onosproject.net.meter.MeterRequest.bands ()
The collection of bands to apply on the dataplane.
Returns
a collection of bands.
Implemented in org.onosproject.net.meter.DefaultMeterRequest.
Referenced by org.onosproject.incubator.net.meter.impl.MeterManager.submit(), and org.onosproject.incubator.net.meter.impl.MeterManager.withdraw().
Optional<MeterContext> org.onosproject.net.meter.MeterRequest.context ()
Returns the callback context for this meter.
Returns
an optional meter context
Implemented in org.onosproject.net.meter.DefaultMeterRequest.
DeviceId org.onosproject.net.meter.MeterRequest.deviceId ()
The target device for this meter.
Returns
a device id
Implemented in org.onosproject.net.meter.DefaultMeterRequest.
Referenced by org.onosproject.incubator.net.meter.impl.MeterManager.submit(), and org.onosproject.incubator.net.meter.impl.MeterManager.withdraw().
boolean org.onosproject.net.meter.MeterRequest.isBurst ()
Signals whether this meter applies to bursts only.
Returns
a boolean
Implemented in org.onosproject.net.meter.DefaultMeterRequest.
Referenced by org.onosproject.incubator.net.meter.impl.MeterManager.submit(), and org.onosproject.incubator.net.meter.impl.MeterManager.withdraw().
Meter.Unit org.onosproject.net.meter.MeterRequest.unit ()
The unit used within this meter.
Returns
the unit
Implemented in org.onosproject.net.meter.DefaultMeterRequest.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/meter/MeterRequest.java