onos: org.onosproject.net.SparseAnnotations Interface Reference
org.onosproject.net.SparseAnnotations Interface Reference
Represents an set of sparse key/value string annotations capable of carrying annotation keys tagged for removal.
Public Member Functions
Set< String > keys ()
Returns the set of keys for available annotations.
Returns
annotation keys
boolean isRemoved (String key)
Indicates whether the specified key has been tagged as removed.
Public Member Functions inherited from org.onosproject.net.Annotations
String value (String key)
Returns the value of the specified annotation.
Detailed Description
Represents an set of sparse key/value string annotations capable of carrying annotation keys tagged for removal.
Definition at line 24 of file SparseAnnotations.java.
Member Function Documentation
boolean org.onosproject.net.SparseAnnotations.isRemoved (String key)
Indicates whether the specified key has been tagged as removed.
This is used for merging sparse annotation sets.
Parameters
key annotation key
Returns
true if the previous annotation has been tagged for removal
Implemented in org.onosproject.net.DefaultAnnotations.
Referenced by org.onosproject.net.DefaultAnnotations.merge().
Set<String> org.onosproject.net.SparseAnnotations.keys ()
Returns the set of keys for available annotations.
Returns
annotation keys
Note that this set includes keys for any attributes tagged for removal.
Implements org.onosproject.net.Annotations.
Implemented in org.onosproject.net.DefaultAnnotations.
Referenced by org.onosproject.store.serializers.KryoSerializerTest.assertAnnotationsEquals(), and org.onosproject.net.DefaultAnnotations.merge().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/SparseAnnotations.java