onos: org.onosproject.net.Device Interface Reference
org.onosproject.net.Device Interface Reference
Representation of a network infrastructure device.
Classes
enum Type
Coarse classification of the type of the infrastructure device.
Public Member Functions
DeviceId id ()
Returns the device identifier.
Type type ()
Returns the type of the infrastructure device.
String manufacturer ()
Returns the device manufacturer name.
String hwVersion ()
Returns the device hardware version.
String swVersion ()
Returns the device software version.
String serialNumber ()
Returns the device serial number.
ChassisId chassisId ()
Returns the device chassis id.
Public Member Functions inherited from org.onosproject.net.Annotated
Annotations annotations ()
Returns the key/value annotations.
Public Member Functions inherited from org.onosproject.net.Provided
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Detailed Description
Representation of a network infrastructure device.
Definition at line 23 of file Device.java.
Member Function Documentation
ChassisId org.onosproject.net.Device.chassisId ()
Returns the device chassis id.
Returns
chassis id
Implemented in org.onosproject.net.DefaultDevice.
Referenced by org.onosproject.codec.impl.DeviceCodec.encode().
String org.onosproject.net.Device.hwVersion ()
Returns the device hardware version.
Returns
hardware version
Implemented in org.onosproject.net.DefaultDevice.
Referenced by org.onosproject.net.device.impl.BasicDeviceOperator.descriptionOf(), and org.onosproject.codec.impl.DeviceCodec.encode().
DeviceId org.onosproject.net.Device.id ()
Returns the device identifier.
Returns
device id
Implements org.onosproject.net.Element.
Implemented in org.onosproject.net.DefaultDevice.
Referenced by org.onosproject.net.device.impl.BasicDeviceOperator.descriptionOf(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceMessage(), org.onosproject.codec.impl.DeviceCodec.encode(), org.onosproject.cli.net.DevicePortStatsCommand.execute(), org.onosproject.cli.net.DevicePortsListCommand.jsonPorts(), org.onosproject.net.statistic.impl.FlowStatisticManager.loadAllByType(), org.onosproject.net.statistic.impl.FlowStatisticManager.loadSummary(), org.onosproject.net.statistic.impl.FlowStatisticManager.loadTopnByType(), org.onosproject.cli.net.DevicesListCommand.printDevice(), org.onosproject.cli.net.FlowsListCommand.printFlows(), org.onosproject.cli.net.TableStatisticsCommand.printTableStats(), org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv4HostDoesNotExistWithVlan(), and org.onosproject.net.host.impl.HostMonitorTest.testMonitorIpv6HostDoesNotExistWithVlan().
String org.onosproject.net.Device.manufacturer ()
Returns the device manufacturer name.
Returns
manufacturer name
Implemented in org.onosproject.net.DefaultDevice.
Referenced by org.onosproject.codec.impl.DeviceCodec.encode(), org.onosproject.net.driver.impl.DriverManager.getDriver(), and org.onosproject.cli.net.DevicesListCommand.printDevice().
String org.onosproject.net.Device.serialNumber ()
Returns the device serial number.
Returns
serial number
Implemented in org.onosproject.net.DefaultDevice.
Referenced by org.onosproject.net.device.impl.BasicDeviceOperator.descriptionOf(), and org.onosproject.codec.impl.DeviceCodec.encode().
String org.onosproject.net.Device.swVersion ()
Returns the device software version.
Returns
software version
Implemented in org.onosproject.net.DefaultDevice.
Referenced by org.onosproject.codec.impl.DeviceCodec.encode(), org.onosproject.net.driver.impl.DriverManager.getDriver(), and org.onosproject.cli.net.DevicesListCommand.printDevice().
Type org.onosproject.net.Device.type ()
Returns the type of the infrastructure device.
Returns
type of the device
Implemented in org.onosproject.net.DefaultDevice.
Referenced by org.onosproject.net.device.impl.BasicDeviceOperator.descriptionOf(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceMessage(), org.onosproject.codec.impl.DeviceCodec.encode(), and org.onosproject.provider.lldp.impl.SuppressionRules.isSuppressed().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/Device.java