onos: org.onosproject.security.store.SecurityModeStore Interface Reference
org.onosproject.security.store.SecurityModeStore Interface Reference
Security-Mode ONOS distributed store service.
Public Member Functions
boolean registerApplication (ApplicationId appId)
Updates the local bundle-application directories.
void unregisterApplication (ApplicationId appId)
Removes application info from the local bundle-application directories.
SecurityModeState getState (ApplicationId appId)
Returns state of the specified application.
Set< String > getBundleLocations (ApplicationId appId)
Returns bundle locations of specified application.
Set< ApplicationId > getApplicationIds (String location)
Returns application identifiers that are associated with given bundle location.
Set< Permission > getRequestedPermissions (ApplicationId appId)
Returns a list of permissions that have been requested by given application.
Set< Permission > getGrantedPermissions (ApplicationId appId)
Returns an array of permissions that have been granted to given application.
void requestPermission (ApplicationId appId, Permission permission)
Request permission that is required to run given application.
boolean isSecured (ApplicationId appId)
Returns true if given application has been secured.
void reviewPolicy (ApplicationId appId)
Notifies SM-ONOS that operator has reviewed the policy.
void acceptPolicy (ApplicationId appId, Set< Permission > permissionSet)
Accept the current security policy of given application.
Detailed Description
Security-Mode ONOS distributed store service.
Definition at line 28 of file SecurityModeStore.java.
Member Function Documentation
void org.onosproject.security.store.SecurityModeStore.acceptPolicy (ApplicationId appId, Set< Permission > permissionSet)
Accept the current security policy of given application.
Parameters
appId application identifier
permissionSet array of PermissionInfo
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
Set<ApplicationId> org.onosproject.security.store.SecurityModeStore.getApplicationIds (String location)
Returns application identifiers that are associated with given bundle location.
Parameters
location OSGi bundle location
Returns
set of application identifiers
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
Set<String> org.onosproject.security.store.SecurityModeStore.getBundleLocations (ApplicationId appId)
Returns bundle locations of specified application.
Parameters
appId application identifier
Returns
set of bundle location strings
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
Set<Permission> org.onosproject.security.store.SecurityModeStore.getGrantedPermissions (ApplicationId appId)
Returns an array of permissions that have been granted to given application.
Parameters
appId application identifier
Returns
array of permissionInfo
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
Referenced by org.onosproject.security.impl.SecurityModeManager.getPrintableGrantedPermissions().
Set<Permission> org.onosproject.security.store.SecurityModeStore.getRequestedPermissions (ApplicationId appId)
Returns a list of permissions that have been requested by given application.
Parameters
appId application identifier
Returns
list of permissions
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
Referenced by org.onosproject.security.impl.SecurityModeManager.getPrintableRequestedPermissions().
SecurityModeState org.onosproject.security.store.SecurityModeStore.getState (ApplicationId appId)
Returns state of the specified application.
Parameters
appId application identifier
Returns
Security-Mode State of application
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
Referenced by org.onosproject.security.impl.SecurityModeManager.acceptPolicy(), org.onosproject.security.impl.SecurityModeManager.isSecured(), and org.onosproject.security.impl.SecurityModeManager.review().
boolean org.onosproject.security.store.SecurityModeStore.isSecured (ApplicationId appId)
Returns true if given application has been secured.
Parameters
appId application identifier
Returns
true indicates secured
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
boolean org.onosproject.security.store.SecurityModeStore.registerApplication (ApplicationId appId)
Updates the local bundle-application directories.
Parameters
appId application identifier
Returns
true if successfully registered.
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
void org.onosproject.security.store.SecurityModeStore.requestPermission (ApplicationId appId, Permission permission)
Request permission that is required to run given application.
Parameters
appId application identifier
permission permission
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
void org.onosproject.security.store.SecurityModeStore.reviewPolicy (ApplicationId appId)
Notifies SM-ONOS that operator has reviewed the policy.
Parameters
appId application identifier
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
void org.onosproject.security.store.SecurityModeStore.unregisterApplication (ApplicationId appId)
Removes application info from the local bundle-application directories.
Parameters
appId application identifier
Implemented in org.onosproject.security.store.DistributedSecurityModeStore.
The documentation for this interface was generated from the following file:
core/security/src/main/java/org/onosproject/security/store/SecurityModeStore.java