onos: org.onosproject.cluster.ControllerNode Interface Reference
org.onosproject.cluster.ControllerNode Interface Reference
Represents a controller instance as a member in a cluster.
Classes
enum State
Represents the operational state of the instance.
Public Member Functions
NodeId id ()
Returns the instance identifier.
IpAddress ip ()
Returns the IP address of the controller instance.
int tcpPort ()
Returns the TCP port on which the node listens for connections.
Detailed Description
Represents a controller instance as a member in a cluster.
Definition at line 23 of file ControllerNode.java.
Member Function Documentation
NodeId org.onosproject.cluster.ControllerNode.id ()
Returns the instance identifier.
Returns
instance identifier
Implemented in org.onosproject.cluster.DefaultControllerNode.
Referenced by org.onosproject.store.cluster.impl.StaticClusterMetadataStore.activate(), org.onosproject.store.trivial.SimpleMastershipStore.activate(), and org.onosproject.ui.impl.TopologyViewMessageHandlerBase.instanceMessage().
IpAddress org.onosproject.cluster.ControllerNode.ip ()
Returns the IP address of the controller instance.
Returns
IP address
Implemented in org.onosproject.cluster.DefaultControllerNode.
Referenced by org.onosproject.store.cluster.messaging.impl.IOLoopMessagingManager.activate(), org.onosproject.store.cluster.messaging.impl.NettyMessagingManager.activate(), org.onosproject.codec.impl.ControllerNodeCodec.encode(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.instanceMessage(), onos.ONOS.start(), and onos.ONOS.updateHazelcast().
int org.onosproject.cluster.ControllerNode.tcpPort ()
Returns the TCP port on which the node listens for connections.
Returns
TCP port
Implemented in org.onosproject.cluster.DefaultControllerNode.
Referenced by org.onosproject.store.consistent.impl.DatabaseManager.nodeIdToUri().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/cluster/ControllerNode.java