onos: org.onosproject.net.host.HostDescription Interface Reference
org.onosproject.net.host.HostDescription Interface Reference
Information describing host and its location.
Public Member Functions
MacAddress hwAddress ()
Returns the MAC address associated with this host (NIC).
VlanId vlan ()
Returns the VLAN associated with this host.
HostLocation location ()
Returns the location of the host on the network edge.
Set< IpAddress > ipAddress ()
Returns the IP address associated with this host's MAC.
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Detailed Description
Information describing host and its location.
Definition at line 29 of file HostDescription.java.
Member Function Documentation
MacAddress org.onosproject.net.host.HostDescription.hwAddress ()
Returns the MAC address associated with this host (NIC).
Returns
the MAC address of this host
Implemented in org.onosproject.net.host.DefaultHostDescription.
Referenced by org.onosproject.net.host.DefaultHostDecriptionTest.basics(), org.onosproject.net.host.impl.BasicHostOperator.combine(), org.onosproject.store.host.impl.ECHostStore.createOrUpdateHost(), org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveIpv6Unicast(), and org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveNa().
Set<IpAddress> org.onosproject.net.host.HostDescription.ipAddress ()
Returns the IP address associated with this host's MAC.
Returns
host IP address
Implemented in org.onosproject.net.host.DefaultHostDescription.
Referenced by org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveIpv6Unicast(), and org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveNa().
HostLocation org.onosproject.net.host.HostDescription.location ()
Returns the location of the host on the network edge.
Returns
the network location
Implemented in org.onosproject.net.host.DefaultHostDescription.
Referenced by org.onosproject.net.host.DefaultHostDecriptionTest.basics(), org.onosproject.net.host.impl.BasicHostOperator.combine(), org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveIpv6Unicast(), and org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveNa().
VlanId org.onosproject.net.host.HostDescription.vlan ()
Returns the VLAN associated with this host.
Returns
the VLAN ID value
Implemented in org.onosproject.net.host.DefaultHostDescription.
Referenced by org.onosproject.net.host.DefaultHostDecriptionTest.basics(), org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveIpv6Unicast(), and org.onosproject.provider.host.impl.HostLocationProviderTest.testReceiveNa().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/host/HostDescription.java