onos: org.onosproject.core.Application Interface Reference
org.onosproject.core.Application Interface Reference
Abstraction of a network control/management application.
Public Member Functions
ApplicationId id ()
Returns the application name id.
Version version ()
Returns the application version.
String description ()
Returns description of the application.
String origin ()
Returns the name of the application origin, group or company.
ApplicationRole role ()
Returns the role of the application.
Set< Permission > permissions ()
Returns the permissions requested by the application.
Optional< URI > featuresRepo ()
Returns the feature repository URI.
List< String > features ()
Returns the list of features comprising the application.
List< String > requiredApps ()
Returns list of required application names.
Detailed Description
Abstraction of a network control/management application.
Definition at line 28 of file Application.java.
Member Function Documentation
String org.onosproject.core.Application.description ()
Returns description of the application.
Returns
application description text
Implemented in org.onosproject.core.DefaultApplication.
Referenced by org.onosproject.core.DefaultApplicationTest.basics(), and org.onosproject.codec.impl.ApplicationCodec.encode().
List<String> org.onosproject.core.Application.features ()
Returns the list of features comprising the application.
At least one feature must be given.
Returns
application features
Implemented in org.onosproject.core.DefaultApplication.
Referenced by org.onosproject.core.DefaultApplicationTest.basics().
Optional<URI> org.onosproject.core.Application.featuresRepo ()
Returns the feature repository URI.
Null value signifies that the application did not provide its own features repository.
Returns
optional feature repo URL
Implemented in org.onosproject.core.DefaultApplication.
Referenced by org.onosproject.core.DefaultApplicationTest.basics().
ApplicationId org.onosproject.core.Application.id ()
Returns the application name id.
Returns
application identifier
Implemented in org.onosproject.core.DefaultApplication.
Referenced by org.onosproject.store.trivial.SimpleApplicationStoreTest.activate(), org.onosproject.core.DefaultApplicationTest.basics(), org.onosproject.store.trivial.SimpleApplicationStoreTest.create(), org.onosproject.store.trivial.SimpleApplicationStoreTest.deactivate(), org.onosproject.codec.impl.ApplicationCodec.encode(), org.onosproject.store.trivial.SimpleApplicationStoreTest.permissions(), and org.onosproject.store.trivial.SimpleApplicationStore.remove().
String org.onosproject.core.Application.origin ()
Returns the name of the application origin, group or company.
Returns
application origin
Implemented in org.onosproject.core.DefaultApplication.
Referenced by org.onosproject.core.DefaultApplicationTest.basics(), and org.onosproject.codec.impl.ApplicationCodec.encode().
Set<Permission> org.onosproject.core.Application.permissions ()
Returns the permissions requested by the application.
Returns
requested permissions
Implemented in org.onosproject.core.DefaultApplication.
Referenced by org.onosproject.core.DefaultApplicationTest.basics(), and org.onosproject.codec.impl.ApplicationCodec.encode().
List<String> org.onosproject.core.Application.requiredApps ()
Returns list of required application names.
Returns
list of application names
Implemented in org.onosproject.core.DefaultApplication.
Referenced by org.onosproject.core.DefaultApplicationTest.basics(), and org.onosproject.codec.impl.ApplicationCodec.encode().
ApplicationRole org.onosproject.core.Application.role ()
Returns the role of the application.
Returns
application role
Implemented in org.onosproject.core.DefaultApplication.
Referenced by org.onosproject.core.DefaultApplicationTest.basics().
Version org.onosproject.core.Application.version ()
Returns the application version.
Returns
application version
Implemented in org.onosproject.core.DefaultApplication.
Referenced by org.onosproject.core.DefaultApplicationTest.basics().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/core/Application.java