onos: org.onosproject.net.group.GroupStore Interface Reference
org.onosproject.net.group.GroupStore Interface Reference
Manages inventory of groups per device; not intended for direct use.
Classes
enum UpdateType
Public Member Functions
int getGroupCount (DeviceId deviceId)
Returns the number of groups for the specified device in the store.
Iterable< Group > getGroups (DeviceId deviceId)
Returns the groups associated with a device.
Group getGroup (DeviceId deviceId, GroupKey appCookie)
Returns the stored group entry.
Group getGroup (DeviceId deviceId, GroupId groupId)
Returns the stored group entry for an id.
void storeGroupDescription (GroupDescription groupDesc)
Stores a new group entry using the information from group description.
void updateGroupDescription (DeviceId deviceId, GroupKey oldAppCookie, UpdateType type, GroupBuckets newBuckets, GroupKey newAppCookie)
Updates the existing group entry with the information from group description.
void deleteGroupDescription (DeviceId deviceId, GroupKey appCookie)
Triggers deleting the existing group entry.
void addOrUpdateGroupEntry (Group group)
Stores a new group entry, or updates an existing entry.
void removeGroupEntry (Group group)
Removes the group entry from store.
void addOrUpdateExtraneousGroupEntry (Group group)
A group entry that is present in switch but not in the store.
void removeExtraneousGroupEntry (Group group)
Remove the group entry from extraneous database.
Iterable< Group > getExtraneousGroups (DeviceId deviceId)
Returns the extraneous groups associated with a device.
void deviceInitialAuditCompleted (DeviceId deviceId, boolean completed)
Indicates the first group audit is completed.
boolean deviceInitialAuditStatus (DeviceId deviceId)
Retrieves the initial group audit status for a device.
void groupOperationFailed (DeviceId deviceId, GroupOperation operation)
Indicates the group operations failed.
void pushGroupMetrics (DeviceId deviceId, Collection< Group > groupEntries)
Submits the group metrics to store for a given device ID.
Detailed Description
Manages inventory of groups per device; not intended for direct use.
Definition at line 27 of file GroupStore.java.
Member Function Documentation
void org.onosproject.net.group.GroupStore.addOrUpdateExtraneousGroupEntry (Group group)
A group entry that is present in switch but not in the store.
Parameters
group group entry
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
void org.onosproject.net.group.GroupStore.addOrUpdateGroupEntry (Group group)
Stores a new group entry, or updates an existing entry.
Parameters
group group entry
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
void org.onosproject.net.group.GroupStore.deleteGroupDescription (DeviceId deviceId, GroupKey appCookie)
Triggers deleting the existing group entry.
Parameters
deviceId the device ID
appCookie the group key
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
void org.onosproject.net.group.GroupStore.deviceInitialAuditCompleted (DeviceId deviceId, boolean completed)
Indicates the first group audit is completed.
Parameters
deviceId the device ID
completed initial audit status
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
boolean org.onosproject.net.group.GroupStore.deviceInitialAuditStatus (DeviceId deviceId)
Retrieves the initial group audit status for a device.
Parameters
deviceId the device ID
Returns
initial group audit status
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
Referenced by org.onosproject.store.group.impl.DistributedGroupStoreTest.testAddRemoveGroup().
Iterable<Group> org.onosproject.net.group.GroupStore.getExtraneousGroups (DeviceId deviceId)
Returns the extraneous groups associated with a device.
Parameters
deviceId the device ID
Returns
the extraneous group entries
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
Group org.onosproject.net.group.GroupStore.getGroup (DeviceId deviceId, GroupKey appCookie)
Returns the stored group entry.
Parameters
deviceId the device ID
appCookie the group key
Returns
a group associated with the key
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
Referenced by org.onosproject.store.group.impl.DistributedGroupStoreTest.testAddPendingGroup(), org.onosproject.store.group.impl.DistributedGroupStoreTest.testAddRemoveGroup(), and org.onosproject.store.group.impl.DistributedGroupStoreTest.testEmptyStore().
Group org.onosproject.net.group.GroupStore.getGroup (DeviceId deviceId, GroupId groupId)
Returns the stored group entry for an id.
Parameters
deviceId the device ID
groupId the group identifier
Returns
a group associated with the key
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
int org.onosproject.net.group.GroupStore.getGroupCount (DeviceId deviceId)
Returns the number of groups for the specified device in the store.
Parameters
deviceId the device ID
Returns
number of groups for the specified device
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
Referenced by org.onosproject.store.group.impl.DistributedGroupStoreTest.testAddPendingGroup(), org.onosproject.store.group.impl.DistributedGroupStoreTest.testAddRemoveGroup(), org.onosproject.store.group.impl.DistributedGroupStoreTest.testEmptyStore(), and org.onosproject.store.group.impl.DistributedGroupStoreTest.testRemoveGroupDescription().
Iterable<Group> org.onosproject.net.group.GroupStore.getGroups (DeviceId deviceId)
Returns the groups associated with a device.
Parameters
deviceId the device ID
Returns
the group entries
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
void org.onosproject.net.group.GroupStore.groupOperationFailed (DeviceId deviceId, GroupOperation operation)
Indicates the group operations failed.
Parameters
deviceId the device ID
operation the group operation failed
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
void org.onosproject.net.group.GroupStore.pushGroupMetrics (DeviceId deviceId, Collection< Group > groupEntries)
Submits the group metrics to store for a given device ID.
Parameters
deviceId the device ID
groupEntries the group entries as received from southbound
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
void org.onosproject.net.group.GroupStore.removeExtraneousGroupEntry (Group group)
Remove the group entry from extraneous database.
Parameters
group group entry
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
void org.onosproject.net.group.GroupStore.removeGroupEntry (Group group)
Removes the group entry from store.
Parameters
group group entry
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
void org.onosproject.net.group.GroupStore.storeGroupDescription (GroupDescription groupDesc)
Stores a new group entry using the information from group description.
Parameters
groupDesc group description to be used to store group entry
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
void org.onosproject.net.group.GroupStore.updateGroupDescription (DeviceId deviceId, GroupKey oldAppCookie, UpdateType type, GroupBuckets newBuckets, GroupKey newAppCookie)
Updates the existing group entry with the information from group description.
Parameters
deviceId the device ID
oldAppCookie the current group key
type update type
newBuckets group buckets for updates
newAppCookie optional new group key
Implemented in org.onosproject.store.group.impl.DistributedGroupStore, and org.onosproject.store.trivial.SimpleGroupStore.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/group/GroupStore.java