onos: org.onosproject.net.intent.IntentService Interface Reference
org.onosproject.net.intent.IntentService Interface Reference
Service for application submitting or withdrawing their intents.
Public Member Functions
void submit (Intent intent)
Submits an intent into the system.
void withdraw (Intent intent)
Withdraws an intent from the system.
void purge (Intent intent)
Purges a specific intent from the system if it is FAILED or WITHDRAWN.
Intent getIntent (Key key)
Fetches an intent based on its key.
Iterable< Intent > getIntents ()
Returns an iterable of intents currently in the system.
Iterable< IntentData > getIntentData ()
Returns an iterable of intent data objects currently in the system.
long getIntentCount ()
Returns the number of intents currently in the system.
IntentState getIntentState (Key intentKey)
Retrieves the state of an intent by its identifier.
List< Intent > getInstallableIntents (Key intentKey)
Returns the list of the installable events associated with the specified top-level intent.
boolean isLocal (Key intentKey)
Signifies whether the local node is responsible for processing the given intent key.
Iterable< Intent > getPending ()
Returns the list of intent requests pending processing.
Detailed Description
Service for application submitting or withdrawing their intents.
Definition at line 28 of file IntentService.java.
Member Function Documentation
List<Intent> org.onosproject.net.intent.IntentService.getInstallableIntents (Key intentKey)
Returns the list of the installable events associated with the specified top-level intent.
Parameters
intentKey top-level intent identifier
Returns
compiled installable intents
Implemented in org.onosproject.net.intent.FakeIntentManager, org.onosproject.net.intent.impl.IntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
Intent org.onosproject.net.intent.IntentService.getIntent (Key key)
Fetches an intent based on its key.
Parameters
key key of the intent
Returns
intent object if the key is found, null otherwise
Implemented in org.onosproject.net.intent.FakeIntentManager, org.onosproject.net.intent.impl.IntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
Referenced by org.onosproject.rest.IntentsResourceTest.testBadGet(), org.onosproject.rest.IntentsResourceTest.testBadRemove(), org.onosproject.rest.IntentsResourceTest.testIntentsSingle(), and org.onosproject.rest.IntentsResourceTest.testRemove().
long org.onosproject.net.intent.IntentService.getIntentCount ()
Returns the number of intents currently in the system.
Returns
number of intents
Implemented in org.onosproject.net.intent.FakeIntentManager, org.onosproject.net.intent.impl.IntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
Referenced by org.onosproject.net.intent.IntentServiceTest.basics(), org.onosproject.net.intent.impl.IntentManagerTest.intentSubclassCompile(), org.onosproject.net.intent.impl.IntentManagerTest.stressSubmitWithdrawSame(), org.onosproject.net.intent.impl.IntentManagerTest.submitIntent(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.summmaryMessage(), and org.onosproject.net.intent.impl.IntentManagerTest.withdrawIntent().
Iterable<IntentData> org.onosproject.net.intent.IntentService.getIntentData ()
Returns an iterable of intent data objects currently in the system.
Returns
set of intent data objects
Implemented in org.onosproject.net.intent.FakeIntentManager, org.onosproject.net.intent.impl.IntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
Referenced by org.onosproject.net.intent.impl.ObjectiveTracker.doIntentUpdate().
Iterable<Intent> org.onosproject.net.intent.IntentService.getIntents ()
Returns an iterable of intents currently in the system.
Returns
set of intents
Implemented in org.onosproject.net.intent.FakeIntentManager, org.onosproject.net.intent.impl.IntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
Referenced by org.onosproject.cli.net.IntentPurgeCommand.execute(), org.onosproject.cli.net.IntentsListCommand.execute(), org.onosproject.cli.net.IntentRemoveCommand.execute(), org.onosproject.net.intent.impl.IntentManagerTest.setUp(), org.onosproject.rest.IntentsResourceTest.setUpTest(), org.onosproject.sdnip.IntentSyncTest.testIntentSync(), org.onosproject.sdnip.IntentSyncTest.testSubmit(), org.onosproject.sdnip.IntentSyncTest.testWithdraw(), and org.onosproject.net.intent.impl.IntentManagerTest.verifyState().
IntentState org.onosproject.net.intent.IntentService.getIntentState (Key intentKey)
Retrieves the state of an intent by its identifier.
Parameters
intentKey intent identifier
Returns
the intent state or null if one with the given identifier is not found
Implemented in org.onosproject.net.intent.FakeIntentManager, org.onosproject.net.intent.impl.IntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
Referenced by org.onosproject.net.intent.IntentServiceTest.basics(), org.onosproject.cli.net.IntentPurgeCommand.execute(), org.onosproject.net.intent.IntentServiceTest.failedCompilation(), org.onosproject.net.intent.IntentServiceTest.implicitRegistration(), org.onosproject.rest.IntentsResourceTest.setUpTest(), and org.onosproject.sdnip.IntentSyncTest.testIntentSync().
Iterable<Intent> org.onosproject.net.intent.IntentService.getPending ()
Returns the list of intent requests pending processing.
Returns
intents pending processing
Implemented in org.onosproject.net.intent.impl.IntentManager, org.onosproject.net.intent.FakeIntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
Referenced by org.onosproject.cli.net.IntentsListCommand.execute().
boolean org.onosproject.net.intent.IntentService.isLocal (Key intentKey)
Signifies whether the local node is responsible for processing the given intent key.
Parameters
intentKey intent key to check
Returns
true if the local node is responsible for the intent key, otherwise false
Implemented in org.onosproject.net.intent.FakeIntentManager, org.onosproject.net.intent.impl.IntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
void org.onosproject.net.intent.IntentService.purge (Intent intent)
Purges a specific intent from the system if it is FAILED or WITHDRAWN.
Otherwise, the intent remains in its current state.
Parameters
intent intent to purge
Implemented in org.onosproject.net.intent.FakeIntentManager, org.onosproject.net.intent.impl.IntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
void org.onosproject.net.intent.IntentService.submit (Intent intent)
Submits an intent into the system.
This is an asynchronous request meaning that any compiling or installation activities may be done at later time.
Parameters
intent intent to be submitted
Implemented in org.onosproject.net.intent.FakeIntentManager, org.onosproject.net.intent.impl.IntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
void org.onosproject.net.intent.IntentService.withdraw (Intent intent)
Withdraws an intent from the system.
This is an asynchronous request meaning that the environment may be affected at later time.
Parameters
intent intent to be withdrawn
Implemented in org.onosproject.net.intent.FakeIntentManager, org.onosproject.net.intent.impl.IntentManager, and org.onosproject.net.intent.IntentServiceAdapter.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/intent/IntentService.java