onos: org.onosproject.metrics.topology.TopologyMetricsService Interface Reference
org.onosproject.metrics.topology.TopologyMetricsService Interface Reference
Service interface exported by TopologyMetrics.
Public Member Functions
List< Event > getEvents ()
Gets the last saved topology events.
EventMetric topologyDeviceEventMetric ()
Gets the Event Metric for the Device Events.
EventMetric topologyHostEventMetric ()
Gets the Event Metric for the Host Events.
EventMetric topologyLinkEventMetric ()
Gets the Event Metric for the Link Events.
EventMetric topologyGraphEventMetric ()
Gets the Event Metric for the Topology Graph Events.
EventMetric topologyGraphReasonsEventMetric ()
Gets the Event Metric for the Topology Graph Reasons Events.
Detailed Description
Service interface exported by TopologyMetrics.
Definition at line 25 of file TopologyMetricsService.java.
Member Function Documentation
List<Event> org.onosproject.metrics.topology.TopologyMetricsService.getEvents ()
Gets the last saved topology events.
Returns
the last saved topology events
Implemented in org.onosproject.metrics.topology.TopologyMetrics.
Referenced by org.onosproject.metrics.topology.cli.TopologyEventsListCommand.execute().
EventMetric org.onosproject.metrics.topology.TopologyMetricsService.topologyDeviceEventMetric ()
Gets the Event Metric for the Device Events.
Returns
the Event Metric for the Device Events
Implemented in org.onosproject.metrics.topology.TopologyMetrics.
Referenced by org.onosproject.metrics.topology.cli.TopologyEventsMetricsCommand.execute().
EventMetric org.onosproject.metrics.topology.TopologyMetricsService.topologyGraphEventMetric ()
Gets the Event Metric for the Topology Graph Events.
Returns
the Event Metric for the Topology Graph Events
Implemented in org.onosproject.metrics.topology.TopologyMetrics.
Referenced by org.onosproject.metrics.topology.cli.TopologyEventsMetricsCommand.execute().
EventMetric org.onosproject.metrics.topology.TopologyMetricsService.topologyGraphReasonsEventMetric ()
Gets the Event Metric for the Topology Graph Reasons Events.
Returns
the Event Metric for the Topology Graph Reasons Events
Implemented in org.onosproject.metrics.topology.TopologyMetrics.
Referenced by org.onosproject.metrics.topology.cli.TopologyEventsMetricsCommand.execute().
EventMetric org.onosproject.metrics.topology.TopologyMetricsService.topologyHostEventMetric ()
Gets the Event Metric for the Host Events.
Returns
the Event Metric for the Host Events
Implemented in org.onosproject.metrics.topology.TopologyMetrics.
Referenced by org.onosproject.metrics.topology.cli.TopologyEventsMetricsCommand.execute().
EventMetric org.onosproject.metrics.topology.TopologyMetricsService.topologyLinkEventMetric ()
Gets the Event Metric for the Link Events.
Returns
the Event Metric for the Link Events
Implemented in org.onosproject.metrics.topology.TopologyMetrics.
Referenced by org.onosproject.metrics.topology.cli.TopologyEventsMetricsCommand.execute().
The documentation for this interface was generated from the following file:
apps/metrics/src/main/java/org/onosproject/metrics/topology/TopologyMetricsService.java