onos: org.onosproject.cluster.ClusterService Interface Reference
org.onosproject.cluster.ClusterService Interface Reference
Service for obtaining information about the individual nodes within the controller cluster.
Public Member Functions
ControllerNode getLocalNode ()
Returns the local controller node.
Set< ControllerNode > getNodes ()
Returns the set of current cluster members.
ControllerNode getNode (NodeId nodeId)
Returns the specified controller node.
ControllerNode.State getState (NodeId nodeId)
Returns the availability state of the specified controller node.
DateTime getLastUpdated (NodeId nodeId)
Returns the system time when the availability state was last updated.
Detailed Description
Service for obtaining information about the individual nodes within the controller cluster.
Definition at line 27 of file ClusterService.java.
Member Function Documentation
DateTime org.onosproject.cluster.ClusterService.getLastUpdated (NodeId nodeId)
Returns the system time when the availability state was last updated.
Parameters
nodeId controller node identifier
Returns
system time when the availability state was last updated.
Implemented in org.onosproject.cluster.impl.ClusterManager, and org.onosproject.cluster.ClusterServiceAdapter.
ControllerNode org.onosproject.cluster.ClusterService.getLocalNode ()
Returns the local controller node.
Returns
local controller node
Implemented in org.onosproject.cluster.impl.ClusterManager, org.onosproject.store.cluster.StaticClusterService, and org.onosproject.cluster.ClusterServiceAdapter.
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.applyFromDevicePool(), org.onosproject.store.link.impl.ECLinkStore.createOrUpdateLink(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.destroyDevicePool(), org.onosproject.store.statistic.impl.DistributedStatisticStore.getCurrentStatistic(), org.onosproject.store.trivial.SimpleLeadershipManager.getLeader(), org.onosproject.store.trivial.SimpleLeadershipManager.getLeadership(), org.onosproject.store.statistic.impl.DistributedStatisticStore.getPreviousStatistic(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.instanceMessage(), org.onosproject.store.intent.impl.PartitionManager.isMine(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.releaseToDevicePool(), org.onosproject.store.trivial.SimpleLeadershipManager.runForLeadership(), org.onosproject.store.ecmap.EventuallyConsistentMapImplTest.setUp(), and org.onosproject.store.trivial.SimpleLeadershipManager.withdraw().
ControllerNode org.onosproject.cluster.ClusterService.getNode (NodeId nodeId)
Returns the specified controller node.
Parameters
nodeId controller node identifier
Returns
controller node
Implemented in org.onosproject.cluster.impl.ClusterManager, org.onosproject.store.cluster.StaticClusterService, and org.onosproject.cluster.ClusterServiceAdapter.
Set<ControllerNode> org.onosproject.cluster.ClusterService.getNodes ()
Returns the set of current cluster members.
Returns
set of cluster members
Implemented in org.onosproject.cluster.impl.ClusterManager, org.onosproject.store.cluster.StaticClusterService, and org.onosproject.cluster.ClusterServiceAdapter.
Referenced by org.onosproject.cluster.impl.MastershipManager.balanceRoles(), org.onosproject.store.consistent.impl.DistributedLeadershipManager.deactivate(), org.onosproject.cli.MastersListCommand.execute(), org.onosproject.cli.NodesListCommand.execute(), and org.onosproject.store.ecmap.EventuallyConsistentMapImplTest.setUp().
ControllerNode.State org.onosproject.cluster.ClusterService.getState (NodeId nodeId)
Returns the availability state of the specified controller node.
Parameters
nodeId controller node identifier
Returns
availability state
Implemented in org.onosproject.cluster.impl.ClusterManager, org.onosproject.store.cluster.StaticClusterService, and org.onosproject.cluster.ClusterServiceAdapter.
Referenced by org.onosproject.cluster.impl.MastershipManager.balanceRoles().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/cluster/ClusterService.java