onos: org.onosproject.net.device.DeviceStore Interface Reference
org.onosproject.net.device.DeviceStore Interface Reference
Manages inventory of infrastructure devices; not intended for direct use.
Public Member Functions
int getDeviceCount ()
Returns the number of devices known to the system.
Iterable< Device > getDevices ()
Returns an iterable collection of all devices known to the system.
Iterable< Device > getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Device getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
DeviceEvent createOrUpdateDevice (ProviderId providerId, DeviceId deviceId, DeviceDescription deviceDescription)
Creates a new infrastructure device, or updates an existing one using the supplied device description.
DeviceEvent markOffline (DeviceId deviceId)
Removes the specified infrastructure device.
List< DeviceEvent > updatePorts (ProviderId providerId, DeviceId deviceId, List< PortDescription > portDescriptions)
Updates the ports of the specified infrastructure device using the given list of port descriptions.
DeviceEvent updatePortStatus (ProviderId providerId, DeviceId deviceId, PortDescription portDescription)
Updates the port status of the specified infrastructure device using the given port description.
List< Port > getPorts (DeviceId deviceId)
Returns the list of ports that belong to the specified device.
DeviceEvent updatePortStatistics (ProviderId providerId, DeviceId deviceId, Collection< PortStatistics > portStats)
Updates the port statistics of the specified device using the give port statistics.
List< PortStatistics > getPortStatistics (DeviceId deviceId)
Returns the list of port statistics of the specified device.
List< PortStatistics > getPortDeltaStatistics (DeviceId deviceId)
Returns the list of delta port statistics of the specified device.
Port getPort (DeviceId deviceId, PortNumber portNumber)
Returns the specified device port.
boolean isAvailable (DeviceId deviceId)
Indicates whether the specified device is available/online.
DeviceEvent removeDevice (DeviceId deviceId)
Administratively removes the specified device from the store.
Detailed Description
Manages inventory of infrastructure devices; not intended for direct use.
Definition at line 31 of file DeviceStore.java.
Member Function Documentation
DeviceEvent org.onosproject.net.device.DeviceStore.createOrUpdateDevice (ProviderId providerId, DeviceId deviceId, DeviceDescription deviceDescription)
Creates a new infrastructure device, or updates an existing one using the supplied device description.
Parameters
providerId provider identifier
deviceId device identifier
deviceDescription device description
Returns
ready to send event describing what occurred; null if no change
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
Referenced by org.onosproject.store.trivial.SimpleDeviceStoreTest.testCreateOrUpdateDevice(), org.onosproject.store.device.impl.GossipDeviceStoreTest.testCreateOrUpdateDevice(), org.onosproject.store.trivial.SimpleDeviceStoreTest.testCreateOrUpdateDeviceAncillary(), and org.onosproject.store.device.impl.GossipDeviceStoreTest.testCreateOrUpdateDeviceAncillary().
Iterable<Device> org.onosproject.net.device.DeviceStore.getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Returns
device collection
Implemented in org.onosproject.store.device.impl.ECDeviceStore, org.onosproject.store.device.impl.GossipDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
Device org.onosproject.net.device.DeviceStore.getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
Parameters
deviceId device identifier
Returns
device
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
Referenced by org.onosproject.store.trivial.SimpleDeviceStoreTest.testGetDevice(), org.onosproject.store.device.impl.GossipDeviceStoreTest.testGetDevice(), org.onosproject.store.trivial.SimpleDeviceStoreTest.testRemoveDevice(), and org.onosproject.store.device.impl.GossipDeviceStoreTest.testRemoveDevice().
int org.onosproject.net.device.DeviceStore.getDeviceCount ()
Returns the number of devices known to the system.
Returns
number of devices
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
Referenced by org.onosproject.store.trivial.SimpleDeviceStoreTest.testGetDeviceCount(), org.onosproject.store.device.impl.GossipDeviceStoreTest.testGetDeviceCount(), org.onosproject.store.trivial.SimpleDeviceStoreTest.testRemoveDevice(), and org.onosproject.store.device.impl.GossipDeviceStoreTest.testRemoveDevice().
Iterable<Device> org.onosproject.net.device.DeviceStore.getDevices ()
Returns an iterable collection of all devices known to the system.
Returns
device collection
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
Referenced by org.onosproject.store.trivial.SimpleDeviceStoreTest.testGetDevices(), and org.onosproject.store.device.impl.GossipDeviceStoreTest.testGetDevices().
Port org.onosproject.net.device.DeviceStore.getPort (DeviceId deviceId, PortNumber portNumber)
Returns the specified device port.
Parameters
deviceId device identifier
portNumber port number
Returns
device port
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
Referenced by org.onosproject.store.trivial.SimpleDeviceStoreTest.testRemoveDevice(), and org.onosproject.store.device.impl.GossipDeviceStoreTest.testRemoveDevice().
List<PortStatistics> org.onosproject.net.device.DeviceStore.getPortDeltaStatistics (DeviceId deviceId)
Returns the list of delta port statistics of the specified device.
Parameters
deviceId device identifier
Returns
list of delta port statistics of all ports of the device
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
List<Port> org.onosproject.net.device.DeviceStore.getPorts (DeviceId deviceId)
Returns the list of ports that belong to the specified device.
Parameters
deviceId device identifier
Returns
list of device ports
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
Referenced by org.onosproject.store.trivial.SimpleDeviceStoreTest.testGetPorts(), org.onosproject.store.device.impl.GossipDeviceStoreTest.testGetPorts(), org.onosproject.store.trivial.SimpleDeviceStoreTest.testRemoveDevice(), and org.onosproject.store.device.impl.GossipDeviceStoreTest.testRemoveDevice().
List<PortStatistics> org.onosproject.net.device.DeviceStore.getPortStatistics (DeviceId deviceId)
Returns the list of port statistics of the specified device.
Parameters
deviceId device identifier
Returns
list of port statistics of all ports of the device
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
boolean org.onosproject.net.device.DeviceStore.isAvailable (DeviceId deviceId)
Indicates whether the specified device is available/online.
Parameters
deviceId device identifier
Returns
true if device is available
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
Referenced by org.onosproject.store.trivial.SimpleDeviceStoreTest.testCreateOrUpdateDeviceAncillary(), org.onosproject.store.device.impl.GossipDeviceStoreTest.testCreateOrUpdateDeviceAncillary(), org.onosproject.store.trivial.SimpleDeviceStoreTest.testMarkOffline(), and org.onosproject.store.device.impl.GossipDeviceStoreTest.testMarkOffline().
DeviceEvent org.onosproject.net.device.DeviceStore.markOffline (DeviceId deviceId)
Removes the specified infrastructure device.
Parameters
deviceId device identifier
Returns
ready to send event describing what occurred; null if no change
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
DeviceEvent org.onosproject.net.device.DeviceStore.removeDevice (DeviceId deviceId)
Administratively removes the specified device from the store.
Parameters
deviceId device to be removed
Returns
null if no such device, or was forwarded to remove master
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
List<DeviceEvent> org.onosproject.net.device.DeviceStore.updatePorts (ProviderId providerId, DeviceId deviceId, List< PortDescription > portDescriptions)
Updates the ports of the specified infrastructure device using the given list of port descriptions.
The list is assumed to be comprehensive.
Parameters
providerId provider identifier
deviceId device identifier
portDescriptions list of port descriptions
Returns
ready to send events describing what occurred; empty list if no change
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
DeviceEvent org.onosproject.net.device.DeviceStore.updatePortStatistics (ProviderId providerId, DeviceId deviceId, Collection< PortStatistics > portStats)
Updates the port statistics of the specified device using the give port statistics.
Parameters
providerId provider identifier
deviceId device identifier
portStats list of port statistics
Returns
ready to send event describing what occurred;
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
DeviceEvent org.onosproject.net.device.DeviceStore.updatePortStatus (ProviderId providerId, DeviceId deviceId, PortDescription portDescription)
Updates the port status of the specified infrastructure device using the given port description.
Parameters
providerId provider identifier
deviceId device identifier
portDescription port description
Returns
ready to send event describing what occurred; null if no change
Implemented in org.onosproject.store.device.impl.GossipDeviceStore, org.onosproject.store.device.impl.ECDeviceStore, and org.onosproject.store.trivial.SimpleDeviceStore.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/device/DeviceStore.java