onos: org.onosproject.vtnrsc.flowclassifier.FlowClassifierService Interface Reference
org.onosproject.vtnrsc.flowclassifier.FlowClassifierService Interface Reference
Provides Services for Flow Classifier.
Public Member Functions
boolean exists (FlowClassifierId id)
Check whether Flow Classifier is present based on given Flow Classifier Id.
int getFlowClassifierCount ()
Returns the number of flow classifiers known to the system.
boolean createFlowClassifier (FlowClassifier flowClassifier)
Store Flow Classifier.
Iterable< FlowClassifier > getFlowClassifiers ()
Return the existing collection of Flow Classifier.
FlowClassifier getFlowClassifier (FlowClassifierId id)
Retrieve the Flow Classifier based on given Flow Classifier id.
boolean updateFlowClassifier (FlowClassifier flowClassifier)
Update Flow Classifier based on given Flow Classifier Id.
boolean removeFlowClassifier (FlowClassifierId id)
Remove Flow Classifier from store based on given Flow Classifier Id.
Detailed Description
Provides Services for Flow Classifier.
Definition at line 24 of file FlowClassifierService.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.createFlowClassifier (FlowClassifier flowClassifier)
Store Flow Classifier.
Parameters
flowClassifier flow classifier
Returns
true if adding flow classifier into store is success otherwise return false
Implemented in org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.
Referenced by org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testPost().
boolean org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.exists (FlowClassifierId id)
Check whether Flow Classifier is present based on given Flow Classifier Id.
Parameters
id flow classifier identifier
Returns
true if flow classifier is present otherwise return false
Implemented in org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.
Referenced by org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testGetFlowClassifierId().
FlowClassifier org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.getFlowClassifier (FlowClassifierId id)
Retrieve the Flow Classifier based on given Flow Classifier id.
Parameters
id flow classifier identifier
Returns
flow classifier if present otherwise returns null
Implemented in org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.
Referenced by org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testBadGet(), and org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testGetFlowClassifierId().
int org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.getFlowClassifierCount ()
Returns the number of flow classifiers known to the system.
Returns
number of flow classifiers
Implemented in org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.
Iterable<FlowClassifier> org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.getFlowClassifiers ()
Return the existing collection of Flow Classifier.
Returns
flow classifier collections
Implemented in org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.
Referenced by org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testFlowClassifiersEmpty().
boolean org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.removeFlowClassifier (FlowClassifierId id)
Remove Flow Classifier from store based on given Flow Classifier Id.
Parameters
id flow classifier identifier
Returns
true if flow classifier removal is success otherwise return false
Implemented in org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.
Referenced by org.onosproject.vtnweb.resources.FlowClassifierResourceTest.testDelete().
boolean org.onosproject.vtnrsc.flowclassifier.FlowClassifierService.updateFlowClassifier (FlowClassifier flowClassifier)
Update Flow Classifier based on given Flow Classifier Id.
Parameters
flowClassifier flow classifier
Returns
true if flow classifier update is success otherwise return false
Implemented in org.onosproject.vtnrsc.flowclassifier.impl.FlowClassifierManager.
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/flowclassifier/FlowClassifierService.java