onos: org.onosproject.net.topology.GraphDescription Interface Reference
org.onosproject.net.topology.GraphDescription Interface Reference
Describes attribute(s) of a network graph.
Public Member Functions
long timestamp ()
Returns the creation timestamp of the graph description.
long creationTime ()
Returns the creation timestamp of the graph description.
ImmutableSet< TopologyVertex > vertexes ()
Returns the set of topology graph vertexes.
ImmutableSet< TopologyEdge > edges ()
Returns the set of topology graph edges.
Public Member Functions inherited from org.onosproject.net.Description
SparseAnnotations annotations ()
Returns the key/value annotations.
Detailed Description
Describes attribute(s) of a network graph.
Definition at line 25 of file GraphDescription.java.
Member Function Documentation
long org.onosproject.net.topology.GraphDescription.creationTime ()
Returns the creation timestamp of the graph description.
This is expressed in system millis to allow proper date and time formatting.
Returns
graph description creation timestamp in millis
Implemented in org.onosproject.net.topology.DefaultGraphDescription.
ImmutableSet<TopologyEdge> org.onosproject.net.topology.GraphDescription.edges ()
Returns the set of topology graph edges.
Returns
set of graph edges
Implemented in org.onosproject.net.topology.DefaultGraphDescription.
Referenced by org.onosproject.net.topology.DefaultGraphDescriptionTest.missingVertex().
long org.onosproject.net.topology.GraphDescription.timestamp ()
Returns the creation timestamp of the graph description.
This is expressed in system nanos to allow proper sequencing.
Returns
graph description creation timestamp
Implemented in org.onosproject.net.topology.DefaultGraphDescription.
Referenced by org.onosproject.net.topology.DefaultGraphDescriptionTest.missingVertex(), org.onosproject.store.trivial.SimpleTopologyStore.updateTopology(), and org.onosproject.store.topology.impl.DistributedTopologyStore.updateTopology().
ImmutableSet<TopologyVertex> org.onosproject.net.topology.GraphDescription.vertexes ()
Returns the set of topology graph vertexes.
Returns
set of graph vertexes
Implemented in org.onosproject.net.topology.DefaultGraphDescription.
Referenced by org.onosproject.common.DefaultTopology.DefaultTopology(), and org.onosproject.net.topology.DefaultGraphDescriptionTest.missingVertex().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/topology/GraphDescription.java