onos: org.onosproject.net.flowobjective.FilteringObjective Interface Reference
org.onosproject.net.flowobjective.FilteringObjective Interface Reference
Represents a filtering flow objective.
Classes
interface Builder
Builder of Filtering objective entities.
enum Type
Public Member Functions
Criterion key ()
Obtain the key for this filter.
Type type ()
Obtain this filtering type.
Collection< Criterion > conditions ()
The set of conditions the filter must provision at the device.
TrafficTreatment meta ()
Auxiliary optional information provided to the device-driver.Typically conveys information about changes (treatments) to packets that are permitted into the pipeline by the PERMIT filtering condition.
Public Member Functions inherited from org.onosproject.net.flowobjective.Objective
int id ()
An identifier for this objective.
int priority ()
The priority for this objective.
ApplicationId appId ()
The application which applied this objective.
int timeout ()
The timeout for this objective.
boolean permanent ()
Whether this objective is permanent.
Operation op ()
The type of operation for this objective.
Optional< ObjectiveContext > context ()
Obtains an optional context.
Additional Inherited Members
Public Attributes inherited from org.onosproject.net.flowobjective.Objective
boolean DEFAULT_PERMANENT = true
int DEFAULT_TIMEOUT = 0
int DEFAULT_PRIORITY = 32768
Detailed Description
Represents a filtering flow objective.
Each filtering flow objective is made up of a key (typically a PortCriterion) mapped to a set of criteria. Using this information, a pipeline aware driver will decide how this objective should be mapped to the device specific pipeline-tables in order to satisfy the filtering condition. For example, consider the following PERMIT filtering objective:
portX -> {MAC1, VLAN1}
The driver could decide to pass packets to the MAC table or VLAN or PORT tables to ensure that only those packets arriving with the correct dst MAC and VLAN ids from Port X are allowed into the pipeline.
Filtering objectives of type PERMIT allow packets that match the key:criteria to enter the pipeline. As a result, the implication is that packets that don't match are automatically denied (dropped).
Filtering objectives of type DENY, are used to deny packets that would otherwise be permitted and forwarded through the pipeline (ie. those packets that make it through the PERMIT filters).
Definition at line 48 of file FilteringObjective.java.
Member Function Documentation
Collection<Criterion> org.onosproject.net.flowobjective.FilteringObjective.conditions ()
The set of conditions the filter must provision at the device.
Returns
a collection of criteria
Implemented in org.onosproject.net.flowobjective.DefaultFilteringObjective.
Criterion org.onosproject.net.flowobjective.FilteringObjective.key ()
Obtain the key for this filter.
The filter may or may not require a key.
Returns
a criterion, which could be null if no key was provided.
Implemented in org.onosproject.net.flowobjective.DefaultFilteringObjective.
Referenced by org.onosproject.driver.pipeline.SpringOpenTTP.processVlanIdFilter().
TrafficTreatment org.onosproject.net.flowobjective.FilteringObjective.meta ()
Auxiliary optional information provided to the device-driver.Typically conveys information about changes (treatments) to packets that are permitted into the pipeline by the PERMIT filtering condition.
Returns
a treatment on the packets that make it through the PERMIT filters. Value may be null if no meta information is provided.
Implemented in org.onosproject.net.flowobjective.DefaultFilteringObjective.
Type org.onosproject.net.flowobjective.FilteringObjective.type ()
Obtain this filtering type.
Returns
the type
Implemented in org.onosproject.net.flowobjective.DefaultFilteringObjective.
Referenced by org.onosproject.driver.pipeline.SoftRouterPipeline.filter(), org.onosproject.driver.pipeline.PicaPipeline.filter(), org.onosproject.driver.pipeline.OVSCorsaPipeline.filter(), org.onosproject.driver.pipeline.CentecV350Pipeline.filter(), org.onosproject.driver.pipeline.SpringOpenTTP.filter(), and org.onosproject.driver.pipeline.OFDPA2Pipeline.filter().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/flowobjective/FilteringObjective.java