onos: org.onosproject.routing.config.RoutingConfigurationService Interface Reference
org.onosproject.routing.config.RoutingConfigurationService Interface Reference
Provides information about the routing configuration.
Public Member Functions
Map< String, BgpSpeaker > getBgpSpeakers ()
Gets the list of BGP speakers inside the SDN network.
Map< IpAddress, BgpPeer > getBgpPeers ()
Gets the list of configured BGP peers.
MacAddress getVirtualGatewayMacAddress ()
Gets the MAC address configured for virtual gateway in SDN network.
boolean isVirtualGatewayIpAddress (IpAddress ipAddress)
Evaluates whether an IP address is a virtual gateway IP address.
boolean isIpAddressLocal (IpAddress ipAddress)
Evaluates whether an IP address belongs to local SDN network.
boolean isIpPrefixLocal (IpPrefix ipPrefix)
Evaluates whether an IP prefix belongs to local SDN network.
Set< Interface > getInterfaces ()
Retrieves the entire set of interfaces in the network.
Set< ConnectPoint > getBgpPeerConnectPoints ()
Retrieves the entire set of connect points connected to BGP peers in the network.
Interface getInterface (ConnectPoint connectPoint)
Retrieves the interface associated with the given connect point.
Interface getInterface (IpAddress ip)
Retrieves the interface associated with the given IP address.
Interface getMatchingInterface (IpAddress ipAddress)
Retrieves the interface that matches the given IP address.
Detailed Description
Provides information about the routing configuration.
Definition at line 29 of file RoutingConfigurationService.java.
Member Function Documentation
Set<ConnectPoint> org.onosproject.routing.config.RoutingConfigurationService.getBgpPeerConnectPoints ()
Retrieves the entire set of connect points connected to BGP peers in the network.
Returns
the set of connect points connected to BGP peers
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
Map<IpAddress, BgpPeer> org.onosproject.routing.config.RoutingConfigurationService.getBgpPeers ()
Gets the list of configured BGP peers.
Returns
the map from peer IP address to BgpPeer object
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
Referenced by org.onosproject.sdnip.PeerConnectivityManagerTest.testNullBgpSpeakers().
Map<String, BgpSpeaker> org.onosproject.routing.config.RoutingConfigurationService.getBgpSpeakers ()
Gets the list of BGP speakers inside the SDN network.
Returns
the map of BGP speaker names to BGP speaker objects
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
Interface org.onosproject.routing.config.RoutingConfigurationService.getInterface (ConnectPoint connectPoint)
Retrieves the interface associated with the given connect point.
Parameters
connectPoint the connect point to retrieve interface information for
Returns
the interface
Deprecated:
in Drake release - use InterfaceService instead
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
Interface org.onosproject.routing.config.RoutingConfigurationService.getInterface (IpAddress ip)
Retrieves the interface associated with the given IP address.
Parameters
ip IP address of the interface
Returns
the interface
Deprecated:
in Drake release - use InterfaceService instead
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
Set<Interface> org.onosproject.routing.config.RoutingConfigurationService.getInterfaces ()
Retrieves the entire set of interfaces in the network.
Returns
the set of interfaces
Deprecated:
in Drake release - use InterfaceService instead
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
Interface org.onosproject.routing.config.RoutingConfigurationService.getMatchingInterface (IpAddress ipAddress)
Retrieves the interface that matches the given IP address.
Matching means that the IP address is in one of the interface's assigned subnets.
Parameters
ipAddress IP address to match
Returns
the matching interface
Deprecated:
in Drake release - use InterfaceService instead
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
MacAddress org.onosproject.routing.config.RoutingConfigurationService.getVirtualGatewayMacAddress ()
Gets the MAC address configured for virtual gateway in SDN network.
Returns
the MAC address of virtual gateway
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
boolean org.onosproject.routing.config.RoutingConfigurationService.isIpAddressLocal (IpAddress ipAddress)
Evaluates whether an IP address belongs to local SDN network.
Parameters
ipAddress the IP address to evaluate
Returns
true if the IP address belongs to local SDN network, otherwise false
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
boolean org.onosproject.routing.config.RoutingConfigurationService.isIpPrefixLocal (IpPrefix ipPrefix)
Evaluates whether an IP prefix belongs to local SDN network.
Parameters
ipPrefix the IP prefix to evaluate
Returns
true if the IP prefix belongs to local SDN network, otherwise false
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
Referenced by org.onosproject.routing.impl.RouterTest.testIpv4LocalRouteAdd(), org.onosproject.routing.impl.RouterTest.testIpv6LocalRouteAdd(), org.onosproject.routing.impl.RouterTest.testIpv6RouteUpdate(), org.onosproject.routing.impl.RouterAsyncArpTest.testRouteAdd(), org.onosproject.routing.impl.RouterAsyncArpTest.testRouteUpdate(), and org.onosproject.routing.impl.RouterTest.testRouteUpdate().
boolean org.onosproject.routing.config.RoutingConfigurationService.isVirtualGatewayIpAddress (IpAddress ipAddress)
Evaluates whether an IP address is a virtual gateway IP address.
Parameters
ipAddress the IP address to evaluate
Returns
true if the IP address is a virtual gateway address, otherwise false
Implemented in org.onosproject.routing.config.impl.RoutingConfigurationImpl.
The documentation for this interface was generated from the following file:
apps/routing-api/src/main/java/org/onosproject/routing/config/RoutingConfigurationService.java