onos: org.onosproject.openflow.controller.OpenFlowSwitch Interface Reference
org.onosproject.openflow.controller.OpenFlowSwitch Interface Reference
Represents to provider facing side of a switch.
Public Member Functions
void sendMsg (OFMessage msg)
Writes the message to the driver.
void sendMsg (List< OFMessage > msgs)
Writes the OFMessage list to the driver.
void handleMessage (OFMessage fromSwitch)
Handle a message from the switch.
void setRole (RoleState role)
Sets the role for this switch.
RoleState getRole ()
Fetch the role for this switch.
List< OFPortDesc > getPorts ()
Fetches the ports of this switch.
OFFactory factory ()
Provides the factory for this OF version.
String getStringId ()
Gets a string version of the ID for this switch.
long getId ()
Gets the datapathId of the switch.
String manufacturerDescription ()
fetch the manufacturer description.
String datapathDescription ()
fetch the datapath description.
String hardwareDescription ()
fetch the hardware description.
String softwareDescription ()
fetch the software description.
String serialNumber ()
fetch the serial number.
boolean isConnected ()
Checks if the switch is still connected.
void disconnectSwitch ()
Disconnects the switch by closing the TCP connection.
void returnRoleReply (RoleState requested, RoleState response)
Notifies the controller that the device has responded to a set-role request.
Device.Type deviceType ()
Returns the switch device type.
String channelId ()
Identifies the channel used to communicate with the switch.
Detailed Description
Represents to provider facing side of a switch.
Definition at line 28 of file OpenFlowSwitch.java.
Member Function Documentation
String org.onosproject.openflow.controller.OpenFlowSwitch.channelId ()
Identifies the channel used to communicate with the switch.
Returns
string representation of the connection to the device
Implemented in org.onosproject.openflow.OpenflowSwitchDriverAdapter, and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
String org.onosproject.openflow.controller.OpenFlowSwitch.datapathDescription ()
fetch the datapath description.
Returns
the description
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, and org.onosproject.openflow.OpenflowSwitchDriverAdapter.
Device.Type org.onosproject.openflow.controller.OpenFlowSwitch.deviceType ()
Returns the switch device type.
Returns
device type
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, org.onosproject.openflow.OpenflowSwitchDriverAdapter, org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13, org.onosproject.driver.handshaker.OFOpticalSwitch13, and org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker.
void org.onosproject.openflow.controller.OpenFlowSwitch.disconnectSwitch ()
Disconnects the switch by closing the TCP connection.
Results in a call to the channel handler's channelDisconnected method for cleanup
Implemented in org.onosproject.openflow.OpenflowSwitchDriverAdapter, and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
OFFactory org.onosproject.openflow.controller.OpenFlowSwitch.factory ()
Provides the factory for this OF version.
Returns
OF version specific factory.
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, and org.onosproject.openflow.OpenflowSwitchDriverAdapter.
Referenced by org.onosproject.provider.of.group.impl.OpenFlowGroupProvider.performGroupOperation().
long org.onosproject.openflow.controller.OpenFlowSwitch.getId ()
Gets the datapathId of the switch.
Returns
the switch dpid in long format
Implemented in org.onosproject.openflow.OpenflowSwitchDriverAdapter, and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
Referenced by metro.FabricDomain.build(), and org.onosproject.openflow.controller.DefaultOpenFlowPacketContext.dpid().
List<OFPortDesc> org.onosproject.openflow.controller.OpenFlowSwitch.getPorts ()
Fetches the ports of this switch.
Returns
unmodifiable list of the ports.
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, org.onosproject.openflow.OpenflowSwitchDriverAdapter, org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13, org.onosproject.driver.handshaker.OFOpticalSwitch13, and org.onosproject.driver.handshaker.DefaultSwitchHandshaker.
RoleState org.onosproject.openflow.controller.OpenFlowSwitch.getRole ()
Fetch the role for this switch.
Returns
the role.
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, and org.onosproject.openflow.OpenflowSwitchDriverAdapter.
Referenced by org.onosproject.openflow.controller.impl.OpenFlowControllerImplTest.testRoleSetting().
String org.onosproject.openflow.controller.OpenFlowSwitch.getStringId ()
Gets a string version of the ID for this switch.
Returns
string version of the ID
Implemented in org.onosproject.openflow.OpenflowSwitchDriverAdapter, and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
Referenced by org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.addOrUpdateFlows().
void org.onosproject.openflow.controller.OpenFlowSwitch.handleMessage (OFMessage fromSwitch)
Handle a message from the switch.
Parameters
fromSwitch the message to handle
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, and org.onosproject.openflow.OpenflowSwitchDriverAdapter.
String org.onosproject.openflow.controller.OpenFlowSwitch.hardwareDescription ()
fetch the hardware description.
Returns
the description
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, and org.onosproject.openflow.OpenflowSwitchDriverAdapter.
boolean org.onosproject.openflow.controller.OpenFlowSwitch.isConnected ()
Checks if the switch is still connected.
Returns
whether the switch is still connected
Implemented in org.onosproject.openflow.OpenflowSwitchDriverAdapter, and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
String org.onosproject.openflow.controller.OpenFlowSwitch.manufacturerDescription ()
fetch the manufacturer description.
Returns
the description
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, and org.onosproject.openflow.OpenflowSwitchDriverAdapter.
void org.onosproject.openflow.controller.OpenFlowSwitch.returnRoleReply (RoleState requested, RoleState response)
Notifies the controller that the device has responded to a set-role request.
Parameters
requested the role requested by the controller
response the role set at the device
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, and org.onosproject.openflow.OpenflowSwitchDriverAdapter.
void org.onosproject.openflow.controller.OpenFlowSwitch.sendMsg (OFMessage msg)
Writes the message to the driver.
Note: Messages may be silently dropped/lost due to IOExceptions or role. If this is a concern, then a caller should use barriers.
Parameters
msg the message to write
Implemented in org.onosproject.driver.handshaker.OfOpticalSwitchImplLinc13, org.onosproject.openflow.OpenflowSwitchDriverAdapter, org.onosproject.driver.handshaker.CalientFiberSwitchHandshaker, and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
void org.onosproject.openflow.controller.OpenFlowSwitch.sendMsg (List< OFMessage > msgs)
Writes the OFMessage list to the driver.
Note: Messages may be silently dropped/lost due to IOExceptions or role. If this is a concern, then a caller should use barriers.
Parameters
msgs the messages to be written
Implemented in org.onosproject.openflow.OpenflowSwitchDriverAdapter, and org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.
String org.onosproject.openflow.controller.OpenFlowSwitch.serialNumber ()
fetch the serial number.
Returns
the serial
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, and org.onosproject.openflow.OpenflowSwitchDriverAdapter.
void org.onosproject.openflow.controller.OpenFlowSwitch.setRole (RoleState role)
Sets the role for this switch.
Parameters
role the role to set.
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, and org.onosproject.openflow.OpenflowSwitchDriverAdapter.
String org.onosproject.openflow.controller.OpenFlowSwitch.softwareDescription ()
fetch the software description.
Returns
the description
Implemented in org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch, and org.onosproject.openflow.OpenflowSwitchDriverAdapter.
The documentation for this interface was generated from the following file:
protocols/openflow/api/src/main/java/org/onosproject/openflow/controller/OpenFlowSwitch.java