onos: org.onosproject.net.device.DeviceService Interface Reference
org.onosproject.net.device.DeviceService Interface Reference
Service for interacting with the inventory of infrastructure devices.
Public Member Functions
int getDeviceCount ()
Returns the number of infrastructure devices known to the system.
Iterable< Device > getDevices ()
Returns a collection of the currently known infrastructure devices.
Iterable< Device > getDevices (Device.Type type)
Returns a collection of the currently known infrastructure devices by device type.
Iterable< Device > getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Iterable< Device > getAvailableDevices (Device.Type type)
Returns an iterable collection of all devices currently available to the system by device type.
Device getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
MastershipRole getRole (DeviceId deviceId)
Returns the current mastership role for the specified device.
List< Port > getPorts (DeviceId deviceId)
Returns the list of ports associated with the device.
List< PortStatistics > getPortStatistics (DeviceId deviceId)
Returns the list of port statistics associated with the device.
List< PortStatistics > getPortDeltaStatistics (DeviceId deviceId)
Returns the list of port delta statistics associated with the device.
Port getPort (DeviceId deviceId, PortNumber portNumber)
Returns the port with the specified number and hosted by the given device.
boolean isAvailable (DeviceId deviceId)
Indicates whether or not the device is presently online and available.
Detailed Description
Service for interacting with the inventory of infrastructure devices.
Definition at line 30 of file DeviceService.java.
Member Function Documentation
Iterable<Device> org.onosproject.net.device.DeviceService.getAvailableDevices ()
Returns an iterable collection of all devices currently available to the system.
Returns
device collection
Implemented in org.onosproject.net.device.impl.DeviceManager, and org.onosproject.net.device.DeviceServiceAdapter.
Iterable<Device> org.onosproject.net.device.DeviceService.getAvailableDevices (Device.Type type)
Returns an iterable collection of all devices currently available to the system by device type.
Parameters
type device type
Returns
device collection
Device org.onosproject.net.device.DeviceService.getDevice (DeviceId deviceId)
Returns the device with the specified identifier.
Parameters
deviceId device identifier
Returns
device or null if one with the given identifier is not known
Implemented in org.onosproject.net.device.impl.DeviceManager, and org.onosproject.net.device.DeviceServiceAdapter.
Referenced by org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.applyFromDevicePool(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.destroyDevicePool(), org.onosproject.net.device.impl.DeviceManagerTest.deviceConnected(), org.onosproject.net.device.impl.DeviceManagerTest.deviceDisconnected(), org.onosproject.rest.resources.DevicesWebResource.getDevicePorts(), org.onosproject.net.driver.impl.DriverManager.getDriver(), org.onosproject.cli.net.TableStatisticsCommand.getSortedTableStats(), org.onosproject.incubator.store.resource.impl.DistributedLabelResourceStore.releaseToDevicePool(), org.onosproject.net.device.impl.DeviceManagerTest.removeDevice(), org.onosproject.rest.FlowsResourceTest.setUpTest(), org.onosproject.rest.DevicesResourceTest.testBadGet(), org.onosproject.rest.DevicesResourceTest.testDeviceAndPorts(), and org.onosproject.rest.DevicesResourceTest.testDevicesSingle().
int org.onosproject.net.device.DeviceService.getDeviceCount ()
Returns the number of infrastructure devices known to the system.
Returns
number of infrastructure devices
Implemented in org.onosproject.net.device.impl.DeviceManager, and org.onosproject.net.device.DeviceServiceAdapter.
Referenced by org.onosproject.net.device.impl.DeviceManagerTest.deviceConnected(), org.onosproject.net.device.impl.DeviceManagerTest.deviceDisconnected(), and org.onosproject.net.device.impl.DeviceManagerTest.removeDevice().
Iterable<Device> org.onosproject.net.device.DeviceService.getDevices ()
Returns a collection of the currently known infrastructure devices.
Returns
collection of devices
Implemented in org.onosproject.net.device.impl.DeviceManager, and org.onosproject.net.device.DeviceServiceAdapter.
Referenced by org.onosproject.cli.net.ConnectPointCompleter.complete(), org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesByGroupId(), org.onosproject.net.flow.impl.FlowRuleManager.getFlowRulesById(), org.onosproject.cli.net.DevicesListCommand.getSortedDevices(), org.onosproject.cli.net.FlowsListCommand.getSortedFlows(), org.onosproject.cli.net.GroupsListCommand.getSortedGroups(), org.onosproject.segmentrouting.DefaultRoutingHandler.populateAllRoutingRules(), org.onosproject.segmentrouting.DefaultRoutingHandler.populateRoutingRulesForLinkStatusChange(), org.onosproject.rest.FlowsResourceTest.setUpTest(), org.onosproject.rest.DevicesResourceTest.testDevices(), org.onosproject.rest.DevicesResourceTest.testDevicesEmptyArray(), and org.onosproject.segmentrouting.ECMPShortestPathGraph.toString().
Iterable<Device> org.onosproject.net.device.DeviceService.getDevices (Device.Type type)
Returns a collection of the currently known infrastructure devices by device type.
Parameters
type device type
Returns
collection of devices
Port org.onosproject.net.device.DeviceService.getPort (DeviceId deviceId, PortNumber portNumber)
Returns the port with the specified number and hosted by the given device.
Parameters
deviceId device identifier
portNumber port number
Returns
device port
Implemented in org.onosproject.net.device.impl.DeviceManager, and org.onosproject.net.device.DeviceServiceAdapter.
Referenced by org.onosproject.net.device.impl.DeviceManagerTest.getPorts().
List<PortStatistics> org.onosproject.net.device.DeviceService.getPortDeltaStatistics (DeviceId deviceId)
Returns the list of port delta statistics associated with the device.
Parameters
deviceId device identifier
Returns
list of port statistics
Implemented in org.onosproject.net.device.impl.DeviceManager, and org.onosproject.net.device.DeviceServiceAdapter.
List<Port> org.onosproject.net.device.DeviceService.getPorts (DeviceId deviceId)
Returns the list of ports associated with the device.
Parameters
deviceId device identifier
Returns
list of ports
Implemented in org.onosproject.net.device.impl.DeviceManager, and org.onosproject.net.device.DeviceServiceAdapter.
Referenced by org.onosproject.cli.net.ConnectPointCompleter.complete(), org.onosproject.rest.resources.DevicesWebResource.getDevicePorts(), org.onosproject.net.device.impl.DeviceManagerTest.getPorts(), org.onosproject.cli.net.DevicePortsListCommand.jsonPorts(), org.onosproject.segmentrouting.RoutingRulePopulator.populateRouterMacVlanFilters(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processEthDstFilter(), org.onosproject.driver.pipeline.CpqdOFDPA2Pipeline.processVlanIdFilter(), org.onosproject.driver.pipeline.OFDPA2Pipeline.processVlanIdFilter(), org.onosproject.rest.DevicesResourceTest.testDeviceAndPorts(), and org.onosproject.net.edgeservice.impl.EdgeManagerTest.testDeviceUpdates().
List<PortStatistics> org.onosproject.net.device.DeviceService.getPortStatistics (DeviceId deviceId)
Returns the list of port statistics associated with the device.
Parameters
deviceId device identifier
Returns
list of port statistics
Implemented in org.onosproject.net.device.impl.DeviceManager, and org.onosproject.net.device.DeviceServiceAdapter.
MastershipRole org.onosproject.net.device.DeviceService.getRole (DeviceId deviceId)
Returns the current mastership role for the specified device.
Parameters
deviceId device identifier
Returns
designated mastership role
Implemented in org.onosproject.net.device.impl.DeviceManager, and org.onosproject.net.device.DeviceServiceAdapter.
Referenced by org.onosproject.codec.impl.DeviceCodec.encode(), org.onosproject.net.device.impl.DeviceManagerTest.getRole(), org.onosproject.net.link.impl.LinkManager.removeLinks(), and org.onosproject.rest.DevicesResourceTest.setUpMocks().
boolean org.onosproject.net.device.DeviceService.isAvailable (DeviceId deviceId)
Indicates whether or not the device is presently online and available.
Parameters
deviceId device identifier
Returns
true if the device is available
Implemented in org.onosproject.net.device.impl.DeviceManager, and org.onosproject.net.device.DeviceServiceAdapter.
Referenced by org.onosproject.net.device.impl.DeviceManagerTest.deviceConnected(), org.onosproject.net.device.impl.DeviceManagerTest.deviceDisconnected(), org.onosproject.ui.impl.TopologyViewMessageHandlerBase.deviceMessage(), and org.onosproject.rest.DevicesResourceTest.setUpMocks().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/device/DeviceService.java