onos: org.onosproject.net.meter.Meter Interface Reference
org.onosproject.net.meter.Meter Interface Reference
Represents a generalized meter to be deployed on a device.
Classes
interface Builder
A meter builder.
enum Unit
Public Member Functions
DeviceId deviceId ()
The target device for this meter.
MeterId id ()
This meters id.
ApplicationId appId ()
The id of the application which created this meter.
Unit unit ()
The unit used within this meter.
boolean isBurst ()
Signals whether this meter applies to bursts only.
Collection< Band > bands ()
The collection of bands to apply on the dataplane.
MeterState state ()
Fetches the state of this meter.
long life ()
The lifetime in seconds of this meter.
long referenceCount ()
The number of flows pointing to this meter.
long packetsSeen ()
Number of packets processed by this meter.
long bytesSeen ()
Number of bytes processed by this meter.
Detailed Description
Represents a generalized meter to be deployed on a device.
Definition at line 26 of file Meter.java.
Member Function Documentation
ApplicationId org.onosproject.net.meter.Meter.appId ()
The id of the application which created this meter.
Returns
an application id
Implemented in org.onosproject.net.meter.DefaultMeter.
Collection<Band> org.onosproject.net.meter.Meter.bands ()
The collection of bands to apply on the dataplane.
Returns
a collection of bands.
Implemented in org.onosproject.net.meter.DefaultMeter.
long org.onosproject.net.meter.Meter.bytesSeen ()
Number of bytes processed by this meter.
Returns
a byte count
Implemented in org.onosproject.net.meter.DefaultMeter.
DeviceId org.onosproject.net.meter.Meter.deviceId ()
The target device for this meter.
Returns
a device id
Implemented in org.onosproject.net.meter.DefaultMeter.
MeterId org.onosproject.net.meter.Meter.id ()
This meters id.
Returns
a meter id
Implemented in org.onosproject.net.meter.DefaultMeter.
Referenced by org.onosproject.incubator.store.meter.impl.DistributedMeterStore.deleteMeter(), org.onosproject.incubator.store.meter.impl.DistributedMeterStore.deleteMeterNow(), org.onosproject.incubator.store.meter.impl.DistributedMeterStore.storeMeter(), org.onosproject.incubator.net.meter.impl.MeterManagerTest.testRemove(), org.onosproject.incubator.store.meter.impl.DistributedMeterStore.updateMeter(), and org.onosproject.incubator.store.meter.impl.DistributedMeterStore.updateMeterState().
boolean org.onosproject.net.meter.Meter.isBurst ()
Signals whether this meter applies to bursts only.
Returns
a boolean
Implemented in org.onosproject.net.meter.DefaultMeter.
long org.onosproject.net.meter.Meter.life ()
The lifetime in seconds of this meter.
Returns
number of seconds
Implemented in org.onosproject.net.meter.DefaultMeter.
long org.onosproject.net.meter.Meter.packetsSeen ()
Number of packets processed by this meter.
Returns
a packet count
Implemented in org.onosproject.net.meter.DefaultMeter.
long org.onosproject.net.meter.Meter.referenceCount ()
The number of flows pointing to this meter.
Returns
a reference count
Implemented in org.onosproject.net.meter.DefaultMeter.
MeterState org.onosproject.net.meter.Meter.state ()
Fetches the state of this meter.
Returns
a meter state
Implemented in org.onosproject.net.meter.DefaultMeter.
Unit org.onosproject.net.meter.Meter.unit ()
The unit used within this meter.
Returns
the unit
Implemented in org.onosproject.net.meter.DefaultMeter.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/meter/Meter.java