onos: org.onosproject.net.flow.FlowEntry Interface Reference
org.onosproject.net.flow.FlowEntry Interface Reference
Represents a generalized match & action pair to be applied to an infrastucture device.
Classes
enum FlowEntryState
Public Member Functions
FlowEntryState state ()
Returns the flow entry state.
long life ()
Returns the number of milliseconds this flow rule has been applied.
long packets ()
Returns the number of packets this flow rule has matched.
long bytes ()
Returns the number of bytes this flow rule has matched.
long lastSeen ()
When this flow entry was last deemed active.
int errType ()
Indicates the error type.
int errCode ()
Indicates the error code.
Public Member Functions inherited from org.onosproject.net.flow.FlowRule
FlowId id ()
Returns the ID of this flow.
short appId ()
Returns the application id of this flow.
GroupId groupId ()
Returns the group id of this flow.
int priority ()
Returns the flow rule priority given in natural order; higher numbers mean higher priorities.
DeviceId deviceId ()
Returns the identity of the device where this rule applies.
TrafficSelector selector ()
Returns the traffic selector that identifies what traffic this rule should apply to.
TrafficTreatment treatment ()
Returns the traffic treatment that applies to selected traffic.
int timeout ()
Returns the timeout for this flow requested by an application.
boolean isPermanent ()
Returns whether the flow is permanent i.e.
int tableId ()
Returns the table id for this rule.
boolean equals (Object obj)
boolean exactMatch (FlowRule rule)
Returns whether this flow rule is an exact match to the flow rule given in the argument.
FlowRuleExtPayLoad payLoad ()
Returns the third party original flow rule.
Additional Inherited Members
Public Attributes inherited from org.onosproject.net.flow.FlowRule
int MAX_TIMEOUT = 60
int MIN_PRIORITY = 0
Detailed Description
Represents a generalized match & action pair to be applied to an infrastucture device.
Definition at line 23 of file FlowEntry.java.
Member Function Documentation
long org.onosproject.net.flow.FlowEntry.bytes ()
Returns the number of bytes this flow rule has matched.
Returns
number of bytes
Implemented in org.onosproject.net.flow.DefaultFlowEntry.
Referenced by org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.addOrUpdateFlows(), org.onosproject.codec.impl.FlowEntryCodec.encode(), org.onosproject.net.statistic.TypedFlowEntryWithLoad.TypedFlowEntryWithLoad(), and org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.updateFlowStatistic().
int org.onosproject.net.flow.FlowEntry.errCode ()
Indicates the error code.
Returns
an integer value of the error
Implemented in org.onosproject.net.flow.DefaultFlowEntry.
int org.onosproject.net.flow.FlowEntry.errType ()
Indicates the error type.
Returns
an integer value of the error
Implemented in org.onosproject.net.flow.DefaultFlowEntry.
long org.onosproject.net.flow.FlowEntry.lastSeen ()
When this flow entry was last deemed active.
Returns
epoch time of last activity
Implemented in org.onosproject.net.flow.DefaultFlowEntry.
Referenced by org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.addOrUpdateFlows(), org.onosproject.codec.impl.FlowEntryCodec.encode(), and org.onosproject.store.statistic.impl.DistributedFlowStatisticStore.updateFlowStatistic().
long org.onosproject.net.flow.FlowEntry.life ()
Returns the number of milliseconds this flow rule has been applied.
Returns
number of millis
Implemented in org.onosproject.net.flow.DefaultFlowEntry.
Referenced by org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.addOrUpdateFlows(), and org.onosproject.codec.impl.FlowEntryCodec.encode().
long org.onosproject.net.flow.FlowEntry.packets ()
Returns the number of packets this flow rule has matched.
Returns
number of packets
Implemented in org.onosproject.net.flow.DefaultFlowEntry.
Referenced by org.onosproject.net.flow.DefaultTypedFlowEntry.DefaultTypedFlowEntry(), and org.onosproject.codec.impl.FlowEntryCodec.encode().
FlowEntryState org.onosproject.net.flow.FlowEntry.state ()
Returns the flow entry state.
Returns
flow entry state
Implemented in org.onosproject.net.flow.DefaultFlowEntry.
Referenced by org.onosproject.provider.of.flow.impl.NewAdaptiveFlowStatsCollector.addOrUpdateFlows(), and org.onosproject.net.flow.DefaultTypedFlowEntry.DefaultTypedFlowEntry().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/FlowEntry.java