onos: org.onosproject.segmentrouting.Policy Interface Reference
org.onosproject.segmentrouting.Policy Interface Reference
Interface for Segment Routing Policy.
Classes
enum Type
Enums for policy type.
Public Member Functions
String id ()
Returns the policy ID.
int priority ()
Returns the priority of the policy.
Type type ()
Returns the policy type.
String srcIp ()
Returns the source IP address of the policy.
String dstIp ()
Returns the destination IP address of the policy.
String ipProto ()
Returns the IP protocol of the policy.
short srcPort ()
Returns the source port of the policy.
short dstPort ()
Returns the destination of the policy.
Detailed Description
Interface for Segment Routing Policy.
Definition at line 22 of file Policy.java.
Member Function Documentation
String org.onosproject.segmentrouting.Policy.dstIp ()
Returns the destination IP address of the policy.
Returns
destination IP address
Implemented in org.onosproject.segmentrouting.TunnelPolicy.
Referenced by org.onosproject.segmentrouting.web.PolicyCodec.encode().
short org.onosproject.segmentrouting.Policy.dstPort ()
Returns the destination of the policy.
Returns
destination port
Implemented in org.onosproject.segmentrouting.TunnelPolicy.
Referenced by org.onosproject.segmentrouting.web.PolicyCodec.encode().
String org.onosproject.segmentrouting.Policy.id ()
Returns the policy ID.
Returns
policy ID
Implemented in org.onosproject.segmentrouting.TunnelPolicy.
Referenced by org.onosproject.segmentrouting.PolicyHandler.createPolicy(), and org.onosproject.segmentrouting.PolicyHandler.removePolicy().
String org.onosproject.segmentrouting.Policy.ipProto ()
Returns the IP protocol of the policy.
Returns
IP protocol
Implemented in org.onosproject.segmentrouting.TunnelPolicy.
Referenced by org.onosproject.segmentrouting.web.PolicyCodec.encode().
int org.onosproject.segmentrouting.Policy.priority ()
Returns the priority of the policy.
Returns
priority
Implemented in org.onosproject.segmentrouting.TunnelPolicy.
String org.onosproject.segmentrouting.Policy.srcIp ()
Returns the source IP address of the policy.
Returns
source IP address
Implemented in org.onosproject.segmentrouting.TunnelPolicy.
Referenced by org.onosproject.segmentrouting.web.PolicyCodec.encode().
short org.onosproject.segmentrouting.Policy.srcPort ()
Returns the source port of the policy.
Returns
source port
Implemented in org.onosproject.segmentrouting.TunnelPolicy.
Referenced by org.onosproject.segmentrouting.web.PolicyCodec.encode().
Type org.onosproject.segmentrouting.Policy.type ()
Returns the policy type.
Returns
policy type
Implemented in org.onosproject.segmentrouting.TunnelPolicy.
Referenced by org.onosproject.segmentrouting.web.PolicyWebResource.createPolicy(), org.onosproject.segmentrouting.PolicyHandler.createPolicy(), org.onosproject.segmentrouting.web.PolicyCodec.encode(), and org.onosproject.segmentrouting.PolicyHandler.removePolicy().
The documentation for this interface was generated from the following file:
apps/segmentrouting/src/main/java/org/onosproject/segmentrouting/Policy.java