onos: org.onosproject.net.newresource.ResourceService Interface Reference
org.onosproject.net.newresource.ResourceService Interface Reference
Service for allocating/releasing resource(s) and retrieving allocation(s) and availability.
Public Member Functions
default Optional
< ResourceAllocation > allocate (ResourceConsumer consumer, ResourcePath resource)
Allocates the specified resource to the specified user.
List< ResourceAllocation > allocate (ResourceConsumer consumer, List< ResourcePath > resources)
Transactionally allocates the specified resources to the specified user.
default List< ResourceAllocation > allocate (ResourceConsumer consumer, ResourcePath...resources)
Transactionally allocates the specified resources to the specified user.
default boolean release (ResourceAllocation allocation)
Releases the specified resource allocation.
boolean release (List< ResourceAllocation > allocations)
Transactionally releases the specified resource allocations.
default boolean release (ResourceAllocation...allocations)
Transactionally releases the specified resource allocations.
boolean release (ResourceConsumer consumer)
Transactionally releases the resources allocated to the specified consumer.
Optional< ResourceAllocation > getResourceAllocation (ResourcePath resource)
Returns resource allocation of the specified resource.
< T > Collection
< ResourceAllocation > getResourceAllocations (ResourcePath parent, Class< T > cls)
Returns allocated resources being as children of the specified parent and being the specified resource type.
Collection< ResourceAllocation > getResourceAllocations (ResourceConsumer consumer)
Returns resources allocated to the specified consumer.
Collection< ResourcePath > getAvailableResources (ResourcePath parent)
Returns resource paths that point available child resources under the specified resource path.
boolean isAvailable (ResourcePath resource)
Returns the availability of the specified resource.
Detailed Description
Service for allocating/releasing resource(s) and retrieving allocation(s) and availability.
Definition at line 33 of file ResourceService.java.
Member Function Documentation
default Optional<ResourceAllocation> org.onosproject.net.newresource.ResourceService.allocate (ResourceConsumer consumer, ResourcePath resource)
Allocates the specified resource to the specified user.
Parameters
consumer resource user which the resource is allocated to
resource resource to be allocated
Returns
allocation information enclosed by Optional. If the allocation fails, the return value is empty
Definition at line 41 of file ResourceService.java.
Referenced by org.onosproject.net.newresource.ResourceService.allocate().
List<ResourceAllocation> org.onosproject.net.newresource.ResourceService.allocate (ResourceConsumer consumer, List< ResourcePath > resources)
Transactionally allocates the specified resources to the specified user.
All allocations are made when this method succeeds, or no allocation is made when this method fails.
Parameters
consumer resource user which the resources are allocated to
resources resources to be allocated
Returns
non-empty list of allocation information if succeeded, otherwise empty list
Implemented in org.onosproject.net.newresource.impl.ResourceManager.
default List<ResourceAllocation> org.onosproject.net.newresource.ResourceService.allocate (ResourceConsumer consumer, ResourcePath... resources)
Transactionally allocates the specified resources to the specified user.
All allocations are made when this method succeeds, or no allocation is made when this method fails.
Parameters
consumer resource user which the resources are allocated to
resources resources to be allocated
Returns
non-empty list of allocation information if succeeded, otherwise empty list
Definition at line 78 of file ResourceService.java.
References org.onosproject.net.newresource.ResourceService.allocate().
Collection<ResourcePath> org.onosproject.net.newresource.ResourceService.getAvailableResources (ResourcePath parent)
Returns resource paths that point available child resources under the specified resource path.
Parameters
parent parent resource path
Returns
available resource paths under the specified resource path
Implemented in org.onosproject.net.newresource.impl.ResourceManager.
Optional<ResourceAllocation> org.onosproject.net.newresource.ResourceService.getResourceAllocation (ResourcePath resource)
Returns resource allocation of the specified resource.
Parameters
resource resource to check the allocation
Returns
allocation information enclosed by Optional. If the resource is not allocated, the return value is empty.
Implemented in org.onosproject.net.newresource.impl.ResourceManager.
<T> Collection<ResourceAllocation> org.onosproject.net.newresource.ResourceService.getResourceAllocations (ResourcePath parent, Class< T > cls)
Returns allocated resources being as children of the specified parent and being the specified resource type.
Parameters
parent parent resource path
cls class to specify a type of resource
<T> type of the resource
Returns
non-empty collection of resource allocations if resources are allocated with the subject and type, empty collection if no resource is allocated with the subject and type
Collection<ResourceAllocation> org.onosproject.net.newresource.ResourceService.getResourceAllocations (ResourceConsumer consumer)
Returns resources allocated to the specified consumer.
Parameters
consumer consumer whose allocated resources are to be returned
Returns
resources allocated to the consumer
Implemented in org.onosproject.net.newresource.impl.ResourceManager.
boolean org.onosproject.net.newresource.ResourceService.isAvailable (ResourcePath resource)
Returns the availability of the specified resource.
Parameters
resource resource to check the availability
Returns
true if available, otherwise false
Implemented in org.onosproject.net.newresource.impl.ResourceManager.
default boolean org.onosproject.net.newresource.ResourceService.release (ResourceAllocation allocation)
Releases the specified resource allocation.
Parameters
allocation resource allocation to be released
Returns
true if succeeded, otherwise false
Definition at line 91 of file ResourceService.java.
Referenced by org.onosproject.net.newresource.ResourceService.release().
boolean org.onosproject.net.newresource.ResourceService.release (List< ResourceAllocation > allocations)
Transactionally releases the specified resource allocations.
All allocations are released when this method succeeded, or no allocation is released when this method fails.
Parameters
allocations resource allocations to be released
Returns
true if succeeded, otherwise false
Implemented in org.onosproject.net.newresource.impl.ResourceManager.
default boolean org.onosproject.net.newresource.ResourceService.release (ResourceAllocation... allocations)
Transactionally releases the specified resource allocations.
All allocations are released when this method succeeded, or no allocation is released when this method fails.
Parameters
allocations resource allocations to be released
Returns
true if succeeded, otherwise false
Definition at line 113 of file ResourceService.java.
References org.onosproject.net.newresource.ResourceService.release().
boolean org.onosproject.net.newresource.ResourceService.release (ResourceConsumer consumer)
Transactionally releases the resources allocated to the specified consumer.
All allocations are released when this method succeeded, or no allocation is released when this method fails.
Parameters
consumer consumer whose allocated resources are to be released
Returns
true if succeeded, otherwise false
Implemented in org.onosproject.net.newresource.impl.ResourceManager.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/newresource/ResourceService.java