onos: org.onosproject.ui.table.CellComparator Interface Reference
org.onosproject.ui.table.CellComparator Interface Reference
Defines a comparator for cell values.
Public Member Functions
int compare (Object o1, Object o2)
Compares its two arguments for order.
Detailed Description
Defines a comparator for cell values.
Definition at line 22 of file CellComparator.java.
Member Function Documentation
int org.onosproject.ui.table.CellComparator.compare (Object o1, Object o2)
Compares its two arguments for order.
Returns a negative integer, zero, or a positive integer as the first argument is less than, equal to, or greater than the second.
Note that nulls are permitted, and should be sorted to the beginning of an ascending sort; i.e. null is considered to be "smaller" than non-null values.
See Also
java.util.Comparator::compare(Object, Object)
Parameters
o1 the first object to be compared.
o2 the second object to be compared.
Returns
a negative integer, zero, or a positive integer as the first argument is less than, equal to, or greater than the second.
Exceptions
ClassCastException if the arguments' types prevent them from being compared by this comparator.
Implemented in org.onosproject.ui.table.cell.AbstractCellComparator.
Referenced by org.onosproject.ui.table.cell.DefaultCellComparatorTest.intBigSmall(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.intElevenTwo(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.intEqual(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.intSmallBig(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.longBigSmall(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.longEqual(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.longSmallBig(), org.onosproject.ui.table.cell.AbstractCellComparatorTest.noNulls(), org.onosproject.ui.table.cell.AbstractCellComparatorTest.nullArgOne(), org.onosproject.ui.table.cell.AbstractCellComparatorTest.nullArgTwo(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.nullVsSome(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.otherVsSome(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.sameString(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.someVsNull(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.someVsOther(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.strElevenTwo(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.swEpisodeI(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.swEpisodeIi(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.swEpisodeIii(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.swEpisodeIv(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.swEpisodeV(), org.onosproject.ui.table.cell.DefaultCellComparatorTest.swEpisodeVi(), and org.onosproject.ui.table.cell.AbstractCellComparatorTest.twoNullArgs().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/ui/table/CellComparator.java