onos: org.onosproject.net.EdgeLink Interface Reference
org.onosproject.net.EdgeLink Interface Reference
Abstraction of a link between an end-station host and the network infrastructure.
Public Member Functions
HostId hostId ()
Returns the host identification.
HostLocation hostLocation ()
Returns the connection point where the host attaches to the network infrastructure.
Public Member Functions inherited from org.onosproject.net.Link
ConnectPoint src ()
Returns the link source connection point.
ConnectPoint dst ()
Returns the link destination connection point.
Type type ()
Returns the link type.
State state ()
Returns the link state.
boolean isDurable ()
Indicates if the link is to be considered durable.
Public Member Functions inherited from org.onosproject.net.Annotated
Annotations annotations ()
Returns the key/value annotations.
Public Member Functions inherited from org.onosproject.net.Provided
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Detailed Description
Abstraction of a link between an end-station host and the network infrastructure.
Definition at line 22 of file EdgeLink.java.
Member Function Documentation
HostId org.onosproject.net.EdgeLink.hostId ()
Returns the host identification.
Returns
host identifier
Implemented in org.onosproject.net.DefaultEdgeLink.
Referenced by org.onosproject.net.DefaultEdgeLinkTest.basics().
HostLocation org.onosproject.net.EdgeLink.hostLocation ()
Returns the connection point where the host attaches to the network infrastructure.
Returns
host location point
Implemented in org.onosproject.net.DefaultEdgeLink.
Referenced by org.onosproject.net.DefaultEdgeLinkTest.basics(), org.onosproject.net.intent.LinksHaveEntryWithSourceDestinationPairMatcher.matchesSafely(), org.onosproject.net.DefaultEdgeLinkTest.phantomEgress(), and org.onosproject.net.DefaultEdgeLinkTest.phantomIngress().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/EdgeLink.java