onos: org.onosproject.net.topology.Topology Interface Reference
org.onosproject.net.topology.Topology Interface Reference
Represents a network topology computation snapshot.
Public Member Functions
long time ()
Returns the time, specified in system nanos of when the topology became available.
long creationTime ()
Returns the time, specified in system millis of when the topology became available.
long computeCost ()
Returns the time, specified in system nanos of how long the topology took to compute.
int clusterCount ()
Returns the number of SCCs (strongly connected components) in the topology.
int deviceCount ()
Returns the number of infrastructure devices in the topology.
int linkCount ()
Returns the number of infrastructure links in the topology.
Public Member Functions inherited from org.onosproject.net.Provided
ProviderId providerId ()
Returns the identifier of the provider which supplied the entity.
Detailed Description
Represents a network topology computation snapshot.
Definition at line 23 of file Topology.java.
Member Function Documentation
int org.onosproject.net.topology.Topology.clusterCount ()
Returns the number of SCCs (strongly connected components) in the topology.
Returns
number of clusters
Implemented in org.onosproject.common.DefaultTopology.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.clusters().
long org.onosproject.net.topology.Topology.computeCost ()
Returns the time, specified in system nanos of how long the topology took to compute.
Returns
elapsed time in system nanos
Implemented in org.onosproject.common.DefaultTopology.
long org.onosproject.net.topology.Topology.creationTime ()
Returns the time, specified in system millis of when the topology became available.
Returns
time in system nanos
Implemented in org.onosproject.common.DefaultTopology.
Referenced by org.onosproject.cli.net.TopologyCommand.execute().
int org.onosproject.net.topology.Topology.deviceCount ()
Returns the number of infrastructure devices in the topology.
Returns
number of devices
Implemented in org.onosproject.common.DefaultTopology.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.clusters(), and org.onosproject.cli.SummaryCommand.execute().
int org.onosproject.net.topology.Topology.linkCount ()
Returns the number of infrastructure links in the topology.
Returns
number of links
Implemented in org.onosproject.common.DefaultTopology.
Referenced by org.onosproject.net.topology.impl.TopologyManagerTest.clusters(), org.onosproject.cli.net.TopologyCommand.execute(), and org.onosproject.cli.SummaryCommand.execute().
long org.onosproject.net.topology.Topology.time ()
Returns the time, specified in system nanos of when the topology became available.
Returns
time in system nanos
Implemented in org.onosproject.common.DefaultTopology.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/topology/Topology.java