onos: org.onosproject.cfg.ComponentConfigService Interface Reference
org.onosproject.cfg.ComponentConfigService Interface Reference
Service for tracking system-wide configurations for various software components.
Public Member Functions
Set< String > getComponentNames ()
Returns names of all components that have registered their configuration properties.
void registerProperties (Class<?> componentClass)
Registers configuration properties for the specified component.
void unregisterProperties (Class<?> componentClass, boolean clear)
Unregisters configuration properties for the specified component.
Set< ConfigProperty > getProperties (String componentName)
Returns configuration properties of the named components.
void setProperty (String componentName, String name, String value)
Sets the value of the specified configuration property.
void preSetProperty (String componentName, String name, String value)
Presets the value of the specified configuration property, regardless of the component's state.
void unsetProperty (String componentName, String name)
Clears the value of the specified configuration property thus making the property take on its default value.
Detailed Description
Service for tracking system-wide configurations for various software components.
Definition at line 23 of file ComponentConfigService.java.
Member Function Documentation
Set<String> org.onosproject.cfg.ComponentConfigService.getComponentNames ()
Returns names of all components that have registered their configuration properties.
Returns
set of component names
Implemented in org.onosproject.cfg.impl.ComponentConfigManager, and org.onosproject.cfg.ComponentConfigAdapter.
Set<ConfigProperty> org.onosproject.cfg.ComponentConfigService.getProperties (String componentName)
Returns configuration properties of the named components.
Parameters
componentName component name
Returns
set of configuration properties
Implemented in org.onosproject.cfg.impl.ComponentConfigManager, and org.onosproject.cfg.ComponentConfigAdapter.
Referenced by org.onosproject.rest.resources.ComponentConfigWebResource.getComponentConfigs().
void org.onosproject.cfg.ComponentConfigService.preSetProperty (String componentName, String name, String value)
Presets the value of the specified configuration property, regardless of the component's state.
Parameters
componentName component name
name property name
value new property value
Implemented in org.onosproject.cfg.impl.ComponentConfigManager, and org.onosproject.cfg.ComponentConfigAdapter.
void org.onosproject.cfg.ComponentConfigService.registerProperties (Class<?> componentClass)
Registers configuration properties for the specified component.
Parameters
componentClass class of configurable component
Implemented in org.onosproject.cfg.impl.ComponentConfigManager, and org.onosproject.cfg.ComponentConfigAdapter.
void org.onosproject.cfg.ComponentConfigService.setProperty (String componentName, String name, String value)
Sets the value of the specified configuration property.
Parameters
componentName component name
name property name
value new property value
Implemented in org.onosproject.cfg.impl.ComponentConfigManager, and org.onosproject.cfg.ComponentConfigAdapter.
Referenced by org.onosproject.rest.resources.ComponentConfigWebResource.setConfigs().
void org.onosproject.cfg.ComponentConfigService.unregisterProperties (Class<?> componentClass, boolean clear)
Unregisters configuration properties for the specified component.
Parameters
componentClass class of configurable component
clear true indicates any settings should be cleared
Implemented in org.onosproject.cfg.impl.ComponentConfigManager, and org.onosproject.cfg.ComponentConfigAdapter.
void org.onosproject.cfg.ComponentConfigService.unsetProperty (String componentName, String name)
Clears the value of the specified configuration property thus making the property take on its default value.
Parameters
componentName component name
name property name
Implemented in org.onosproject.cfg.impl.ComponentConfigManager, and org.onosproject.cfg.ComponentConfigAdapter.
Referenced by org.onosproject.rest.resources.ComponentConfigWebResource.unsetConfigs().
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/cfg/ComponentConfigService.java