onos: org.onosproject.net.flow.TableStatisticsEntry Interface Reference
org.onosproject.net.flow.TableStatisticsEntry Interface Reference
Interface for flow table statistics of a device.
Public Member Functions
DeviceId deviceId ()
Returns the device Id.
int tableId ()
Returns the table number.
long activeFlowEntries ()
Returns the number of active flow entries in this table.
long packetsLookedup ()
Returns the number of packets looked up in the table.
long packetsMatched ()
Returns the number of packets that successfully matched in the table.
Detailed Description
Interface for flow table statistics of a device.
Definition at line 23 of file TableStatisticsEntry.java.
Member Function Documentation
long org.onosproject.net.flow.TableStatisticsEntry.activeFlowEntries ()
Returns the number of active flow entries in this table.
Returns
the number of active flow entries
Implemented in org.onosproject.net.flow.DefaultTableStatisticsEntry.
Referenced by org.onosproject.codec.impl.TableStatisticsEntryCodec.encode().
DeviceId org.onosproject.net.flow.TableStatisticsEntry.deviceId ()
Returns the device Id.
Returns
device id
Implemented in org.onosproject.net.flow.DefaultTableStatisticsEntry.
long org.onosproject.net.flow.TableStatisticsEntry.packetsLookedup ()
Returns the number of packets looked up in the table.
Returns
the number of packets looked up in the table
Implemented in org.onosproject.net.flow.DefaultTableStatisticsEntry.
Referenced by org.onosproject.codec.impl.TableStatisticsEntryCodec.encode().
long org.onosproject.net.flow.TableStatisticsEntry.packetsMatched ()
Returns the number of packets that successfully matched in the table.
Returns
the number of packets that successfully matched in the table
Implemented in org.onosproject.net.flow.DefaultTableStatisticsEntry.
Referenced by org.onosproject.codec.impl.TableStatisticsEntryCodec.encode().
int org.onosproject.net.flow.TableStatisticsEntry.tableId ()
Returns the table number.
Returns
table number
Implemented in org.onosproject.net.flow.DefaultTableStatisticsEntry.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/flow/TableStatisticsEntry.java