onos: org.onosproject.net.group.GroupDescription Interface Reference
org.onosproject.net.group.GroupDescription Interface Reference
ONOS representation of group description that is used to create a group.
Classes
enum Type
Types of the group supported by ONOS.
Public Member Functions
Type type ()
Returns type of a group object.
DeviceId deviceId ()
Returns device identifier on which this group object is created.
ApplicationId appId ()
Returns application identifier that has created this group object.
GroupKey appCookie ()
Returns application cookie associated with a group object.
Integer givenGroupId ()
Returns groupId passed in by caller.
GroupBuckets buckets ()
Returns group buckets of a group.
Detailed Description
ONOS representation of group description that is used to create a group.
It contains immutable properties of a ONOS group construct such as "type", "DeviceId", "appCookie", "appId" and "buckets"
Definition at line 26 of file GroupDescription.java.
Member Function Documentation
GroupKey org.onosproject.net.group.GroupDescription.appCookie ()
Returns application cookie associated with a group object.
Returns
GroupKey application cookie
Implemented in org.onosproject.net.group.DefaultGroupDescription.
Referenced by org.onosproject.codec.impl.GroupCodec.encode().
ApplicationId org.onosproject.net.group.GroupDescription.appId ()
Returns application identifier that has created this group object.
Returns
ApplicationId application identifier
Implemented in org.onosproject.net.group.DefaultGroupDescription.
Referenced by org.onosproject.codec.impl.GroupCodec.encode().
GroupBuckets org.onosproject.net.group.GroupDescription.buckets ()
Returns group buckets of a group.
Returns
GroupBuckets immutable list of group bucket
Implemented in org.onosproject.net.group.DefaultGroupDescription.
Referenced by org.onosproject.store.trivial.SimpleGroupStore.addOrUpdateGroupEntry(), org.onosproject.store.group.impl.DistributedGroupStore.addOrUpdateGroupEntry(), and org.onosproject.codec.impl.GroupJsonMatcher.matchesSafely().
DeviceId org.onosproject.net.group.GroupDescription.deviceId ()
Returns device identifier on which this group object is created.
Returns
DeviceId device identifier
Implemented in org.onosproject.net.group.DefaultGroupDescription.
Referenced by org.onosproject.store.trivial.SimpleGroupStore.addOrUpdateExtraneousGroupEntry(), org.onosproject.store.group.impl.DistributedGroupStore.addOrUpdateExtraneousGroupEntry(), org.onosproject.store.trivial.SimpleGroupStore.addOrUpdateGroupEntry(), org.onosproject.store.group.impl.DistributedGroupStore.addOrUpdateGroupEntry(), org.onosproject.codec.impl.GroupCodec.encode(), org.onosproject.store.trivial.SimpleGroupStore.groupOperationFailed(), org.onosproject.store.group.impl.DistributedGroupStore.groupOperationFailed(), org.onosproject.store.trivial.SimpleGroupStore.removeExtraneousGroupEntry(), org.onosproject.store.group.impl.DistributedGroupStore.removeExtraneousGroupEntry(), org.onosproject.store.trivial.SimpleGroupStore.removeGroupEntry(), org.onosproject.store.group.impl.DistributedGroupStore.removeGroupEntry(), org.onosproject.store.trivial.SimpleGroupStore.storeGroupDescription(), org.onosproject.store.group.impl.DistributedGroupStore.storeGroupDescription(), and org.onosproject.store.trivial.SimpleGroupStore.updateGroupDescription().
Integer org.onosproject.net.group.GroupDescription.givenGroupId ()
Returns groupId passed in by caller.
Returns
Integer group id passed in by caller. May be null if caller passed in null to let groupService determin the group id.
Implemented in org.onosproject.net.group.DefaultGroupDescription.
Referenced by org.onosproject.codec.impl.GroupCodec.encode(), and org.onosproject.store.trivial.SimpleGroupStore.updateGroupDescription().
Type org.onosproject.net.group.GroupDescription.type ()
Returns type of a group object.
Returns
GroupType group type
Implemented in org.onosproject.net.group.DefaultGroupDescription.
The documentation for this interface was generated from the following file:
core/api/src/main/java/org/onosproject/net/group/GroupDescription.java