onos: org.onosproject.vtnrsc.TenantNetwork Interface Reference
org.onosproject.vtnrsc.TenantNetwork Interface Reference
Representation of the tenantNetwork.
Classes
enum State
Coarse classification of the state of the tenantNetwork.
enum Type
Coarse classification of the type of the tenantNetwork.
Public Member Functions
TenantNetworkId id ()
Returns the tenantNetwork identifier.
String name ()
Returns the tenantNetwork name.
boolean adminStateUp ()
Returns the administrative state of the tenantNetwork,which is up(true) or down(false).
State state ()
Returns the tenantNetwork state.
boolean shared ()
Indicates whether this tenantNetwork is shared across all tenants.
TenantId tenantId ()
Returns the UUID of the tenant that will own the tenantNetwork.
boolean routerExternal ()
Returns the routerExternal.Indicates whether this network is externally accessible.
Type type ()
Returns the tenantNetwork Type.
PhysicalNetwork physicalNetwork ()
Returns the tenantNetwork physical network.
SegmentationId segmentationId ()
Returns the tenantNetwork segmentation id.
Detailed Description
Representation of the tenantNetwork.
Definition at line 21 of file TenantNetwork.java.
Member Function Documentation
boolean org.onosproject.vtnrsc.TenantNetwork.adminStateUp ()
Returns the administrative state of the tenantNetwork,which is up(true) or down(false).
Returns
true or false
Implemented in org.onosproject.vtnrsc.DefaultTenantNetwork.
Referenced by org.onosproject.vtnweb.web.TenantNetworkCodec.encode().
TenantNetworkId org.onosproject.vtnrsc.TenantNetwork.id ()
Returns the tenantNetwork identifier.
Returns
tenantNetwork identifier
Implemented in org.onosproject.vtnrsc.DefaultTenantNetwork.
Referenced by org.onosproject.vtnweb.resources.TenantNetworkWebResource.getNetworks().
String org.onosproject.vtnrsc.TenantNetwork.name ()
Returns the tenantNetwork name.
Returns
tenantNetwork name
Implemented in org.onosproject.vtnrsc.DefaultTenantNetwork.
Referenced by tutorial.Router.config(), tutorial_ipv6.Router.config(), metro.IpHost.config(), org.onosproject.vtnweb.web.TenantNetworkCodec.encode(), org.onosproject.vtnweb.resources.TenantNetworkWebResource.getNetworks(), onos.ONOS.start(), tutorial_ipv6.SdnSwitch.start(), tutorial.Router.terminate(), and tutorial_ipv6.Router.terminate().
PhysicalNetwork org.onosproject.vtnrsc.TenantNetwork.physicalNetwork ()
Returns the tenantNetwork physical network.
Returns
tenantNetwork physical network
Implemented in org.onosproject.vtnrsc.DefaultTenantNetwork.
boolean org.onosproject.vtnrsc.TenantNetwork.routerExternal ()
Returns the routerExternal.Indicates whether this network is externally accessible.
Returns
true or false
Implemented in org.onosproject.vtnrsc.DefaultTenantNetwork.
SegmentationId org.onosproject.vtnrsc.TenantNetwork.segmentationId ()
Returns the tenantNetwork segmentation id.
Returns
tenantNetwork segmentation id
Implemented in org.onosproject.vtnrsc.DefaultTenantNetwork.
Referenced by org.onosproject.vtnweb.web.TenantNetworkCodec.encode().
boolean org.onosproject.vtnrsc.TenantNetwork.shared ()
Indicates whether this tenantNetwork is shared across all tenants.
By default,only administrative user can change this value.
Returns
true or false
Implemented in org.onosproject.vtnrsc.DefaultTenantNetwork.
Referenced by org.onosproject.vtnweb.web.TenantNetworkCodec.encode().
State org.onosproject.vtnrsc.TenantNetwork.state ()
Returns the tenantNetwork state.
Returns
tenant network state
Implemented in org.onosproject.vtnrsc.DefaultTenantNetwork.
Referenced by org.onosproject.vtnweb.web.TenantNetworkCodec.encode().
TenantId org.onosproject.vtnrsc.TenantNetwork.tenantId ()
Returns the UUID of the tenant that will own the tenantNetwork.
This tenant can be different from the tenant that makes the create tenantNetwork request.
Returns
the tenant identifier
Implemented in org.onosproject.vtnrsc.DefaultTenantNetwork.
Referenced by org.onosproject.vtnweb.web.TenantNetworkCodec.encode().
Type org.onosproject.vtnrsc.TenantNetwork.type ()
Returns the tenantNetwork Type.
Returns
tenantNetwork Type
Implemented in org.onosproject.vtnrsc.DefaultTenantNetwork.
The documentation for this interface was generated from the following file:
apps/vtn/vtnrsc/src/main/java/org/onosproject/vtnrsc/TenantNetwork.java