audit: lib/audit_logging.c File Reference
audit_logging.c File Reference
#include "config.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/stat.h>
#include <errno.h>
#include <netinet/in.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <utmp.h>
#include <limits.h>
#include "libaudit.h"
#include "private.h"
Macros
#define TTY_PATH 32
#define MAX_USER (UT_NAMESIZE * 2) + 8
Functions
int audit_value_needs_encoding (const char *str, unsigned int size)
char * audit_encode_value (char *final, const char *buf, unsigned int size)
char * audit_encode_nv_string (const char *name, const char *value, unsigned int vlen)
int audit_log_user_message (int audit_fd, int type, const char *message, const char *hostname, const char *addr, const char *tty, int result)
int audit_log_user_comm_message (int audit_fd, int type, const char *message, const char *comm, const char *hostname, const char *addr, const char *tty, int result)
int audit_log_acct_message (int audit_fd, int type, const char *pgname, const char *op, const char *name, unsigned int id, const char *host, const char *addr, const char *tty, int result)
int audit_log_user_avc_message (int audit_fd, int type, const char *message, const char *hostname, const char *addr, const char *tty, uid_t uid)
int audit_log_semanage_message (int audit_fd, int type, const char *pgname, const char *op, const char *name, unsigned int id, const char *new_seuser, const char *new_role, const char *new_range, const char *old_seuser, const char *old_role, const char *old_range, const char *host, const char *addr, const char *tty, int result)
int audit_log_user_command (int audit_fd, int type, const char *command, const char *tty, int result)
Macro Definition Documentation
#define MAX_USER (UT_NAMESIZE * 2) + 8
Definition at line 40 of file audit_logging.c.
Referenced by audit_log_acct_message(), and audit_log_semanage_message().
#define TTY_PATH 32
Definition at line 39 of file audit_logging.c.
Referenced by audit_log_acct_message(), audit_log_semanage_message(), audit_log_user_avc_message(), audit_log_user_comm_message(), audit_log_user_command(), and audit_log_user_message().
Function Documentation
char* audit_encode_nv_string (const char * name, const char * value, unsigned int vlen)
Definition at line 124 of file audit_logging.c.
References audit_encode_value(), and audit_value_needs_encoding().
char* audit_encode_value (char * final, const char * buf, unsigned int size)
Definition at line 102 of file audit_logging.c.
Referenced by audit_encode_nv_string(), audit_log_acct_message(), audit_log_semanage_message(), and audit_log_user_command().
int audit_log_acct_message (int audit_fd, int type, const char * pgname, const char * op, const char * name, unsigned int id, const char * host, const char * addr, const char * tty, int result)
Definition at line 381 of file audit_logging.c.
References audit_encode_value(), audit_send_user_message(), audit_value_needs_encoding(), MAX_AUDIT_MESSAGE_LENGTH, MAX_USER, REAL_ERR, and TTY_PATH.
int audit_log_semanage_message (int audit_fd, int type, const char * pgname, const char * op, const char * name, unsigned int id, const char * new_seuser, const char * new_role, const char * new_range, const char * old_seuser, const char * old_role, const char * old_range, const char * host, const char * addr, const char * tty, int result)
Definition at line 551 of file audit_logging.c.
References audit_encode_value(), audit_send_user_message(), audit_value_needs_encoding(), MAX_AUDIT_MESSAGE_LENGTH, MAX_USER, REAL_ERR, and TTY_PATH.
int audit_log_user_avc_message (int audit_fd, int type, const char * message, const char * hostname, const char * addr, const char * tty, uid_t uid)
Definition at line 478 of file audit_logging.c.
References audit_msg_type_to_name(), audit_send_user_message(), MAX_AUDIT_MESSAGE_LENGTH, REAL_ERR, and TTY_PATH.
int audit_log_user_comm_message (int audit_fd, int type, const char * message, const char * comm, const char * hostname, const char * addr, const char * tty, int result)
Definition at line 307 of file audit_logging.c.
References audit_send_user_message(), HIDE_IT, MAX_AUDIT_MESSAGE_LENGTH, and TTY_PATH.
int audit_log_user_command (int audit_fd, int type, const char * command, const char * tty, int result)
Definition at line 656 of file audit_logging.c.
References audit_encode_value(), audit_send_user_message(), audit_value_needs_encoding(), HIDE_IT, MAX_AUDIT_MESSAGE_LENGTH, and TTY_PATH.
int audit_log_user_message (int audit_fd, int type, const char * message, const char * hostname, const char * addr, const char * tty, int result)
Definition at line 240 of file audit_logging.c.
References audit_send_user_message(), HIDE_IT, MAX_AUDIT_MESSAGE_LENGTH, and TTY_PATH.
int audit_value_needs_encoding (const char * str, unsigned int size)
Definition at line 84 of file audit_logging.c.
Referenced by audit_encode_nv_string(), audit_log_acct_message(), audit_log_semanage_message(), and audit_log_user_command().