audit: src/auditd-listen.c File Reference
auditd-listen.c File Reference
#include "config.h"
#include <stdio.h>
#include <unistd.h>
#include <sys/stat.h>
#include <errno.h>
#include <string.h>
#include <dirent.h>
#include <ctype.h>
#include <stdlib.h>
#include <netdb.h>
#include <fcntl.h>
#include <libgen.h>
#include <arpa/inet.h>
#include <limits.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include "libaudit.h"
#include "auditd-event.h"
#include "auditd-config.h"
#include "private.h"
#include "ev.h"
Data Structures
struct ev_tcp
Macros
#define DEFAULT_BUF_SZ 192
#define auditd_tcpd_check(s) ({ 0; })
Typedefs
typedef struct ev_tcp ev_tcp
Functions
int send_audit_event (int type, const char *str)
int auditd_tcp_listen_init (struct ev_loop *loop, struct daemon_conf *config)
void auditd_tcp_listen_uninit (struct ev_loop *loop, struct daemon_conf *config)
void auditd_tcp_listen_reconfigure (struct daemon_conf *nconf, struct daemon_conf *oconf)
Variables
volatile int stop
Macro Definition Documentation
#define auditd_tcpd_check (s) ({ 0; })
Definition at line 717 of file auditd-listen.c.
#define DEFAULT_BUF_SZ 192
Definition at line 59 of file auditd-listen.c.
Typedef Documentation
typedef struct ev_tcp ev_tcp
Function Documentation
int auditd_tcp_listen_init (struct ev_loop * loop, struct daemon_conf * config)
Definition at line 903 of file auditd-listen.c.
References audit_msg, config, daemon_conf::enable_krb5, ev_io_init, ev_io_start(), ev_periodic_init, ev_periodic_start(), EV_READ, daemon_conf::krb5_key_file, daemon_conf::krb5_principal, daemon_conf::tcp_client_max_idle, daemon_conf::tcp_client_max_port, daemon_conf::tcp_client_min_port, daemon_conf::tcp_listen_port, daemon_conf::tcp_listen_queue, daemon_conf::tcp_max_per_addr, and daemon_conf::use_libwrap.
Referenced by main().
void auditd_tcp_listen_reconfigure (struct daemon_conf * nconf, struct daemon_conf * oconf)
Definition at line 1041 of file auditd-listen.c.
References daemon_conf::tcp_client_max_idle, daemon_conf::tcp_client_max_port, daemon_conf::tcp_client_min_port, daemon_conf::tcp_listen_port, daemon_conf::tcp_listen_queue, and daemon_conf::tcp_max_per_addr.
void auditd_tcp_listen_uninit (struct ev_loop * loop, struct daemon_conf * config)
Definition at line 999 of file auditd-listen.c.
References AUDIT_RMW_HEADER_SIZE, AUDIT_RMW_PACK_HEADER, AUDIT_RMW_TYPE_ENDING, ev_io_stop(), ev_periodic_stop(), ev_tcp::io, and daemon_conf::tcp_client_max_idle.
Referenced by main().
int send_audit_event (int type, const char * str)
Definition at line 214 of file auditd.c.
References audit_msg, DMSG_SIZE, audit_reply::len, audit_reply::message, auditd_reply_list::reply, auparse_test::type, and audit_reply::type.
Referenced by main().
Variable Documentation
volatile int stop
Definition at line 46 of file audispd.c.
Referenced by add_stop_guest_event(), main(), print_summary(), and push_event().