audit: src/auditd.c File Reference
auditd.c File Reference
#include "config.h"
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <signal.h>
#include <errno.h>
#include <string.h>
#include <time.h>
#include <sys/resource.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <fcntl.h>
#include <pthread.h>
#include <sys/utsname.h>
#include <getopt.h>
#include "libaudit.h"
#include "auditd-event.h"
#include "auditd-config.h"
#include "auditd-dispatch.h"
#include "auditd-listen.h"
#include "private.h"
#include "ev.h"
Macros
#define EV_STOP() ev_unloop (ev_default_loop (EVFLAG_AUTO), EVUNLOOP_ALL), stop = 1;
#define DEFAULT_BUF_SZ 448
#define DMSG_SIZE (DEFAULT_BUF_SZ + 48)
#define SUCCESS 0
#define FAILURE 1
#define SUBJ_LEN 4097
Enumerations
enum startup_state { startup_disable =0, startup_enable, startup_nochange, startup_INVALID }
Functions
int send_audit_event (int type, const char *str)
int main (int argc, char *argv[])
Variables
volatile int stop = 0
Macro Definition Documentation
#define DEFAULT_BUF_SZ 448
Definition at line 53 of file auditd.c.
Referenced by main().
#define DMSG_SIZE (DEFAULT_BUF_SZ + 48)
Definition at line 54 of file auditd.c.
Referenced by send_audit_event().
#define EV_STOP () ev_unloop (ev_default_loop (EVFLAG_AUTO), EVUNLOOP_ALL), stop = 1;
Definition at line 51 of file auditd.c.
#define FAILURE 1
Definition at line 56 of file auditd.c.
Referenced by main().
#define SUBJ_LEN 4097
Definition at line 57 of file auditd.c.
#define SUCCESS 0
Definition at line 55 of file auditd.c.
Referenced by main().
Enumeration Type Documentation
enum startup_state
Enumerator
startup_disable
startup_enable
startup_nochange
startup_INVALID
Definition at line 80 of file auditd.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 488 of file auditd.c.
References audit_getloginuid(), audit_is_enabled(), audit_lookup_format(), audit_msg, audit_open(), audit_request_signal_info(), audit_set_enabled(), audit_set_pid(), auditd_tcp_listen_init(), auditd_tcp_listen_uninit(), config, audit_sig_info::ctx, D_BACKGROUND, D_FOREGROUND, DBG_NO, DBG_YES, DEFAULT_BUF_SZ, ev_default_destroy(), ev_default_loop(), ev_io_init, ev_io_start(), ev_io_stop(), ev_loop(), EV_READ, ev_signal_init, ev_signal_start(), ev_signal_stop(), EVFLAG_NOENV, FAILURE, free_config(), init_config_manager(), init_dispatcher(), init_event(), load_config(), MAX_AUDIT_MESSAGE_LENGTH, MSG_STDERR, MSG_SYSLOG, audit_sig_info::pid, resolve_node(), send_audit_event(), set_allow_links(), set_aumessage_mode, shutdown_dispatcher(), audit_reply::signal_info, startup_enable, startup_INVALID, startup_nochange, stop, auparse_test::subj, SUCCESS, TEST_AUDITD, audit_sig_info::uid, and WAIT_YES.
int send_audit_event (int type, const char * str)
Definition at line 214 of file auditd.c.
References audit_msg, DMSG_SIZE, audit_reply::len, audit_reply::message, auditd_reply_list::reply, auparse_test::type, and audit_reply::type.
Referenced by main().
Variable Documentation
volatile int stop = 0
Definition at line 60 of file auditd.c.