audit: src/auditctl-listing.c File Reference
auditctl-listing.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "auditctl-listing.h"
#include "private.h"
#include "auditctl-llist.h"
#include "auparse-idata.h"
Functions
int key_match (const struct audit_rule_data *r)
void audit_print_init (void)
const char * get_enable (unsigned e)
const char * get_failure (unsigned f)
int audit_print_reply (struct audit_reply *rep, int fd)
Variables
int list_requested
int interpret
char key [AUDIT_MAX_KEY_LEN+1]
const char key_sep [2]
Function Documentation
void audit_print_init (void)
Definition at line 459 of file auditctl-listing.c.
References list_create().
int audit_print_reply (struct audit_reply * rep, int fd)
Definition at line 500 of file auditctl-listing.c.
References audit_close(), AUDIT_GET_FEATURE, llist::cur, audit_reply::error, get_enable(), get_failure(), interpret, key_match(), list_append(), list_clear(), list_first(), list_next(), list_requested, audit_reply::nlh, _lnode::r, audit_reply::ruledata, audit_reply::status, and audit_reply::type.
const char* get_enable (unsigned e)
Definition at line 465 of file auditctl-listing.c.
Referenced by audit_print_reply().
const char* get_failure (unsigned f)
Definition at line 480 of file auditctl-listing.c.
Referenced by audit_print_reply().
int key_match (const struct audit_rule_data * r)
Definition at line 42 of file auditctl-listing.c.
References auparse_test::key.
Referenced by audit_print_reply(), and delete_all_rules().
Variable Documentation
static void interpret
Definition at line 287 of file ausearch-report.c.
Referenced by audit_print_reply(), and nvlist_interp_cur_val().
char key[AUDIT_MAX_KEY_LEN+1]
Definition at line 120 of file auparse_test.ref.py.
Referenced by audit_machine_to_elf(), audit_number_to_errmsg(), and key_match().
const char key_sep[2]
Definition at line 57 of file auditctl.c.
int list_requested
Definition at line 55 of file auditctl.c.
Referenced by audit_print_reply(), and audit_request_rule_list().