audit: audisp/plugins/prelude/audisp-prelude.c File Reference
audisp-prelude.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <syslog.h>
#include <string.h>
#include <ctype.h>
#include <pwd.h>
#include <sys/stat.h>
#include <sys/select.h>
#include <errno.h>
#include <libprelude/prelude.h>
#include <libprelude/idmef-message-print.h>
#include "libaudit.h"
#include "auparse.h"
#include "prelude-config.h"
Macros
#define CONFIG_FILE "/etc/audisp/audisp-prelude.conf"
#define ANALYZER_MODEL "auditd"
#define ANALYZER_CLASS "HIDS"
#define ANALYZER_MANUFACTURER "Red Hat, http://people.redhat.com/sgrubb/audit/"
#define PRELUDE_FAIL_CHECK if (ret < 0) goto err;
Enumerations
enum as_description_t {
AS_LOGIN, AS_MAX_LOGIN_FAIL, AS_MAX_LOGIN_SESS, AS_ABEND,
AS_PROM, AS_MAC_STAT, AS_LOGIN_LOCATION, AS_LOGIN_TIME,
AS_MAC, AS_AUTH, AS_WATCHED_LOGIN, AS_WATCHED_FILE,
AS_WATCHED_EXEC, AS_MK_EXE, AS_MMAP0, AS_WATCHED_SYSCALL,
AS_TTY, AS_TOTAL
}
enum output_t { M_NORMAL, M_TEST }
enum watched_t { W_NO, W_FILE, W_EXEC, W_MK_EXE }
Functions
int main (int argc, char *argv[])
Variables
const char * assessment_description [AS_TOTAL]
Macro Definition Documentation
#define ANALYZER_CLASS "HIDS"
Definition at line 45 of file audisp-prelude.c.
#define ANALYZER_MANUFACTURER "Red Hat, http://people.redhat.com/sgrubb/audit/"
Definition at line 46 of file audisp-prelude.c.
#define ANALYZER_MODEL "auditd"
Definition at line 44 of file audisp-prelude.c.
#define CONFIG_FILE "/etc/audisp/audisp-prelude.conf"
Definition at line 43 of file audisp-prelude.c.
Referenced by load_config(), and main().
#define PRELUDE_FAIL_CHECK if (ret < 0) goto err;
Definition at line 47 of file audisp-prelude.c.
Enumeration Type Documentation
enum as_description_t
Enumerator
AS_LOGIN
AS_MAX_LOGIN_FAIL
AS_MAX_LOGIN_SESS
AS_ABEND
AS_PROM
AS_MAC_STAT
AS_LOGIN_LOCATION
AS_LOGIN_TIME
AS_MAC
AS_AUTH
AS_WATCHED_LOGIN
AS_WATCHED_FILE
AS_WATCHED_EXEC
AS_MK_EXE
AS_MMAP0
AS_WATCHED_SYSCALL
AS_TTY
AS_TOTAL
Definition at line 49 of file audisp-prelude.c.
enum output_t
Enumerator
M_NORMAL
M_TEST
Definition at line 72 of file audisp-prelude.c.
enum watched_t
Enumerator
W_NO
W_FILE
W_EXEC
W_MK_EXE
Definition at line 73 of file audisp-prelude.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 198 of file audisp-prelude.c.
References auparse_add_callback(), auparse_destroy(), auparse_feed(), auparse_feed_has_data(), auparse_flush_feed(), auparse_init(), AUSOURCE_FEED, CONFIG_FILE, free_config(), hup, load_config(), M_TEST, MAX_AUDIT_MESSAGE_LENGTH, and stop.
Variable Documentation
const char* assessment_description[AS_TOTAL]
Initial value:
= {
 "A user has attempted to login",
 "The maximum allowed login failures for this account has been reached. This could be an attempt to gain access to the account by someone other than the real account holder.",
 "The maximum allowed concurrent logins for this account has been reached.",
 "An application terminated abnormally. An attacker may be trying to exploit a weakness in the program.",
 "A program has opened or closed a promiscuous socket. If this is not expected, it could be an attacker trying to sniff traffic.",
 "A program has changed SE Linux policy enforcement. If this is not expected, it could be an attempt to subvert the system.",
 "A user attempted to login from a location that is not allowed. This could be an attempt to gain access to the account by someone other than the real account holder.",
 "A user attempted to login during a time that the user should not be logging into the system. This could be an attempt to gain access to the account by someone other than the real account holder.",
 "A program has tried to access something that is not allowed in the MAC policy. This could indicate an attacker trying to exploit a weakness in the program.",
 "A user has attempted to use an authentication mechanism and failed. This could be an attempt to gain privileges that they are not supposed to have.",
 "A user has logged in to an account that is being watched.",
 "A user has attempted to access a file that is being watched.",
 "A user has attempted to execute a program that is being watched.",
 "A user has attempted to create an executable program",
 "A program has attempted mmap a fixed memory page at an address sometimes used as part of a kernel exploit",
 "A user has run a command that issued a watched syscall",
 "A user has typed keystrokes on a terminal"
}
Definition at line 53 of file audisp-prelude.c.