audit: audisp/audispd-builtins.c File Reference
audispd-builtins.c File Reference
#include "config.h"
#include <string.h>
#include <dirent.h>
#include <libgen.h>
#include <ctype.h>
#include <errno.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/un.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "audispd-pconfig.h"
#include "audispd-builtins.h"
Functions
void start_builtin (plugin_conf_t *conf)
void stop_builtin (plugin_conf_t *conf)
void send_af_unix_string (const char *s, unsigned int len)
void send_af_unix_binary (event_t *e)
void destroy_af_unix (void)
void send_syslog (const char *s)
void destroy_syslog (void)
Function Documentation
void destroy_af_unix (void)
Definition at line 249 of file audispd-builtins.c.
Referenced by main(), and stop_builtin().
void destroy_syslog (void)
Definition at line 326 of file audispd-builtins.c.
Referenced by main(), and stop_builtin().
void send_af_unix_binary (event_t * e)
Definition at line 225 of file audispd-builtins.c.
References add_event(), event::data, event::hdr, and MAX_AUDIT_MESSAGE_LENGTH.
void send_af_unix_string (const char * s, unsigned int len)
Definition at line 207 of file audispd-builtins.c.
References add_event().
void send_syslog (const char * s)
Definition at line 320 of file audispd-builtins.c.
void start_builtin (plugin_conf_t * conf)
Definition at line 48 of file audispd-builtins.c.
References plugin_conf::path, S_AF_UNIX, S_SYSLOG, and plugin_conf::type.
void stop_builtin (plugin_conf_t * conf)
Definition at line 60 of file audispd-builtins.c.
References destroy_af_unix(), destroy_syslog(), plugin_conf::path, S_AF_UNIX, S_SYSLOG, and plugin_conf::type.