audit: src/auditd-config.h File Reference
auditd-config.h File Reference
#include "libaudit.h"
#include <grp.h>
Data Structures
struct daemon_conf
Macros
#define CONFIG_FILE "/etc/audit/auditd.conf"
#define MEGABYTE 1048576UL
Enumerations
enum daemon_t { D_FOREGROUND, D_BACKGROUND }
enum logging_formats { LF_RAW, LF_NOLOG }
enum flush_technique { FT_NONE, FT_INCREMENTAL, FT_DATA, FT_SYNC }
enum failure_action_t {
FA_IGNORE, FA_SYSLOG, FA_EXEC, FA_RECONNECT,
FA_SUSPEND, FA_SINGLE, FA_HALT, FA_STOP,
FA_IGNORE, FA_SYSLOG, FA_ROTATE, FA_EMAIL,
FA_EXEC, FA_SUSPEND, FA_SINGLE, FA_HALT
}
enum size_action {
SZ_IGNORE, SZ_SYSLOG, SZ_SUSPEND, SZ_ROTATE,
SZ_KEEP_LOGS
}
enum qos_t { QOS_NON_BLOCKING, QOS_BLOCKING }
enum log_test_t { TEST_AUDITD, TEST_SEARCH }
enum node_t {
N_NONE, N_HOSTNAME, N_FQD, N_NUMERIC,
N_USER, N_NONE, N_HOSTNAME, N_FQD,
N_NUMERIC, N_USER
}
Functions
void set_allow_links (int allow)
int load_config (struct daemon_conf *config, log_test_t lt)
void clear_config (struct daemon_conf *config)
const char * audit_lookup_format (int fmt)
int create_log_file (const char *val)
int resolve_node (struct daemon_conf *config)
void init_config_manager (void)
void shutdown_config (void)
void free_config (struct daemon_conf *config)
Macro Definition Documentation
#define CONFIG_FILE "/etc/audit/auditd.conf"
Definition at line 29 of file auditd-config.h.
#define MEGABYTE 1048576UL
Definition at line 30 of file auditd-config.h.
Enumeration Type Documentation
enum daemon_t
Enumerator
D_FOREGROUND
D_BACKGROUND
Definition at line 32 of file auditd-config.h.
enum failure_action_t
Enumerator
FA_IGNORE
FA_SYSLOG
FA_EXEC
FA_RECONNECT
FA_SUSPEND
FA_SINGLE
FA_HALT
FA_STOP
FA_IGNORE
FA_SYSLOG
FA_ROTATE
FA_EMAIL
FA_EXEC
FA_SUSPEND
FA_SINGLE
FA_HALT
Definition at line 35 of file auditd-config.h.
enum flush_technique
Enumerator
FT_NONE
FT_INCREMENTAL
FT_DATA
FT_SYNC
Definition at line 34 of file auditd-config.h.
enum log_test_t
Enumerator
TEST_AUDITD
TEST_SEARCH
Definition at line 40 of file auditd-config.h.
enum logging_formats
Enumerator
LF_RAW
LF_NOLOG
Definition at line 33 of file auditd-config.h.
enum node_t
Enumerator
N_NONE
N_HOSTNAME
N_FQD
N_NUMERIC
N_USER
N_NONE
N_HOSTNAME
N_FQD
N_NUMERIC
N_USER
Definition at line 41 of file auditd-config.h.
enum qos_t
Enumerator
QOS_NON_BLOCKING
QOS_BLOCKING
Definition at line 39 of file auditd-config.h.
enum size_action
Enumerator
SZ_IGNORE
SZ_SYSLOG
SZ_SUSPEND
SZ_ROTATE
SZ_KEEP_LOGS
Definition at line 37 of file auditd-config.h.
Function Documentation
const char* audit_lookup_format (int fmt)
Definition at line 1616 of file auditd-config.c.
References nv_list::name.
Referenced by main().
void clear_config (struct daemon_conf * config)
Definition at line 111 of file audispd-config.c.
References daemon_conf::action_mail_acct, daemon_conf::admin_space_left, daemon_conf::admin_space_left_action, daemon_conf::admin_space_left_exe, daemon_conf::disk_error_action, daemon_conf::disk_error_exe, daemon_conf::disk_full_action, daemon_conf::disk_full_exe, daemon_conf::dispatcher, daemon_conf::enable_krb5, FA_IGNORE, FA_SYSLOG, daemon_conf::flush, daemon_conf::freq, FT_NONE, daemon_conf::krb5_key_file, daemon_conf::krb5_principal, LF_RAW, daemon_conf::log_file, daemon_conf::log_format, daemon_conf::log_group, daemon_conf::max_log_size, daemon_conf::max_log_size_action, daemon_conf::max_restarts, N_NONE, daemon_conf::name, daemon_conf::node_name, daemon_conf::node_name_format, daemon_conf::num_logs, O_SYSLOG, daemon_conf::overflow_action, daemon_conf::priority_boost, daemon_conf::q_depth, daemon_conf::qos, QOS_NON_BLOCKING, daemon_conf::sender_ctx, daemon_conf::sender_pid, daemon_conf::sender_uid, daemon_conf::space_left, daemon_conf::space_left_action, daemon_conf::space_left_exe, SZ_IGNORE, daemon_conf::tcp_client_max_idle, daemon_conf::tcp_client_max_port, daemon_conf::tcp_client_min_port, daemon_conf::tcp_listen_port, daemon_conf::tcp_listen_queue, daemon_conf::tcp_max_per_addr, TCP_PORT_MAX, and daemon_conf::use_libwrap.
Referenced by get_auditfail_action(), and load_config().
int create_log_file (const char * val)
Definition at line 1627 of file auditd-config.c.
References audit_msg.
void free_config (struct daemon_conf * config)
Definition at line 503 of file audispd-config.c.
References daemon_conf::action_mail_acct, daemon_conf::admin_space_left_exe, daemon_conf::disk_error_exe, daemon_conf::disk_full_exe, daemon_conf::dispatcher, daemon_conf::krb5_key_file, daemon_conf::krb5_principal, daemon_conf::log_file, daemon_conf::name, daemon_conf::node_name, daemon_conf::sender_ctx, and daemon_conf::space_left_exe.
Referenced by load_config(), and main().
void init_config_manager (void)
Definition at line 41 of file auditd-reconfig.c.
References audit_msg.
Referenced by main().
int load_config (struct daemon_conf * config, log_test_t lt)
Definition at line 116 of file auditd-config.c.
References audit_msg, clear_config(), CONFIG_FILE, auparse_test::f, kw_pair::max_options, _pair::name, nv_pair::name, kw_pair::name, nv_pair::option, kw_pair::parser, _pair::value, and nv_pair::value.
int resolve_node (struct daemon_conf * config)
Definition at line 1654 of file auditd-config.c.
References audit_msg, N_FQD, N_HOSTNAME, N_NONE, N_NUMERIC, N_USER, daemon_conf::node_name, and daemon_conf::node_name_format.
Referenced by main().
void set_allow_links (int allow)
Definition at line 231 of file auditd-config.c.
Referenced by main().
void shutdown_config (void)
Definition at line 77 of file auditd-reconfig.c.