audit: src/auditctl-listing.h File Reference
auditctl-listing.h File Reference
#include "config.h"
#include "libaudit.h"
Functions
void audit_print_init (void)
int audit_print_reply (struct audit_reply *rep, int fd)
int key_match (const struct audit_rule_data *r)
Function Documentation
void audit_print_init (void)
Definition at line 459 of file auditctl-listing.c.
References list_create().
int audit_print_reply (struct audit_reply * rep, int fd)
Definition at line 500 of file auditctl-listing.c.
References audit_close(), AUDIT_GET_FEATURE, llist::cur, audit_reply::error, get_enable(), get_failure(), interpret, key_match(), list_append(), list_clear(), list_first(), list_next(), list_requested, audit_reply::nlh, _lnode::r, audit_reply::ruledata, audit_reply::status, and audit_reply::type.
int key_match (const struct audit_rule_data * r)
Definition at line 42 of file auditctl-listing.c.