audit: src/auditctl-llist.h File Reference
auditctl-llist.h File Reference
#include "config.h"
#include <sys/types.h>
#include "libaudit.h"
Data Structures
struct _lnode
struct llist
Typedefs
typedef struct _lnode lnode
Functions
void list_create (llist *l)
void list_first (llist *l)
void list_last (llist *l)
lnode * list_next (llist *l)
void list_append (llist *l, struct audit_rule_data *r, size_t sz)
void list_clear (llist *l)
Typedef Documentation
typedef struct _lnode lnode
Function Documentation
void list_append (llist * l, struct audit_rule_data * r, size_t sz)
Definition at line 61 of file auditctl-llist.c.
References llist::cnt, llist::cur, llist::head, _lnode::next, _lnode::r, and _lnode::size.
Referenced by add_resource(), add_start_guest_event(), add_stop_guest_event(), audit_print_reply(), delete_all_rules(), list_create_session(), lol_add_record(), main(), process_anom(), process_avc_selinux_context(), process_machine_id_event(), and process_shutdown().
void list_clear (llist * l)
Definition at line 89 of file auditctl-llist.c.
void list_create (llist * l)
Definition at line 28 of file auditctl-llist.c.
void list_first (llist * l)
Definition at line 35 of file auditctl-llist.c.
References llist::cur, and llist::head.
Referenced by audit_print_reply(), delete_all_rules(), extract_search_items(), main(), and match().
void list_last (llist * l)
Definition at line 40 of file auditctl-llist.c.
lnode* list_next (llist * l)
Definition at line 53 of file auditctl-llist.c.