audit: audisp/audispd.c File Reference
audispd.c File Reference
#include "config.h"
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <signal.h>
#include <errno.h>
#include <string.h>
#include <sys/wait.h>
#include <pthread.h>
#include <dirent.h>
#include <fcntl.h>
#include <sys/poll.h>
#include <netdb.h>
#include <arpa/inet.h>
#include "audispd-config.h"
#include "audispd-pconfig.h"
#include "audispd-llist.h"
#include "audispd-builtins.h"
#include "queue.h"
#include "libaudit.h"
Functions
int main (int argc, char *argv[])
int add_event (int fd, poll_callback_ptr cb)
int remove_event (int fd)
Variables
volatile int stop = 0
volatile int hup = 0
Function Documentation
int add_event (int fd, poll_callback_ptr cb)
Definition at line 741 of file audispd.c.
Referenced by main(), send_af_unix_binary(), and send_af_unix_string().
int main (int argc, char * argv[])
Definition at line 330 of file audispd.c.
References add_event(), DBG_YES, destroy_af_unix(), destroy_queue(), destroy_syslog(), free_config(), free_pconfig(), hup, init_queue(), load_config(), MSG_SYSLOG, _lnode::p, plist_clear(), plist_next(), daemon_conf::priority_boost, daemon_conf::q_depth, and set_aumessage_mode.
int remove_event (int fd)
Definition at line 754 of file audispd.c.
Variable Documentation
volatile int hup = 0
Definition at line 47 of file audispd.c.
Referenced by dequeue(), and main().
volatile int stop = 0
Definition at line 46 of file audispd.c.
Referenced by add_stop_guest_event(), main(), print_summary(), and push_event().