audit: src/auditctl.c File Reference
auditctl.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <getopt.h>
#include <time.h>
#include <sys/stat.h>
#include <ctype.h>
#include <unistd.h>
#include <sys/utsname.h>
#include <fcntl.h>
#include <errno.h>
#include <libgen.h>
#include <limits.h>
#include "libaudit.h"
#include "auditctl-listing.h"
#include "private.h"
Macros
#define LINE_SIZE 6144
Functions
int delete_all_rules (int fd)
int audit_request_rule_list (int fd)
void check_rule_mismatch (int lineno, const char *option)
int report_status (int fd)
int parse_syscall (struct audit_rule_data *rule_new, const char *optarg)
void preprocess (char *buf)
void postprocess (char *buf)
int main (int argc, char *argv[])
Variables
int list_requested = 0
int interpret = 0
char key [AUDIT_MAX_KEY_LEN+1]
const char key_sep [2] = { AUDIT_KEY_SEPARATOR, 0 }
struct option long_opts []
Macro Definition Documentation
#define LINE_SIZE 6144
Definition at line 46 of file auditctl.c.
Function Documentation
int audit_request_rule_list (int fd)
Definition at line 419 of file auditctl.c.
References audit_request_rules_list_data(), and list_requested.
void check_rule_mismatch (int lineno, const char * option)
Definition at line 429 of file auditctl.c.
References _audit_elf, audit_msg, and audit_rule_syscallbyname_data().
int delete_all_rules (int fd)
Definition at line 35 of file delete_all.c.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 1288 of file auditctl.c.
References AUDIT_FILTER_UNSET, audit_msg, audit_open(), DBG_NO, MSG_STDERR, MSG_SYSLOG, and set_aumessage_mode.
int parse_syscall (struct audit_rule_data * rule_new, const char * optarg)
Definition at line 482 of file auditctl.c.
References audit_msg, and audit_rule_syscallbyname_data().
Referenced by extract_search_items().
void postprocess (char * buf)
Definition at line 1115 of file auditctl.c.
void preprocess (char * buf)
Definition at line 1088 of file auditctl.c.
int report_status (int fd)
Definition at line 460 of file auditctl.c.
References audit_request_features(), and audit_request_status().
Variable Documentation
int interpret = 0
Definition at line 55 of file auditctl.c.
Referenced by audit_print_reply(), and nvlist_interp_cur_val().
char key[AUDIT_MAX_KEY_LEN+1]
Definition at line 56 of file auditctl.c.
const char key_sep[2] = { AUDIT_KEY_SEPARATOR, 0 }
Definition at line 57 of file auditctl.c.
int list_requested = 0
Definition at line 55 of file auditctl.c.
Referenced by audit_print_reply(), and audit_request_rule_list().
struct option long_opts[]
Initial value:
=
{
  {"loginuid-immutable", 0, NULL, 1},
  {"backlog_wait_time", 1, NULL, 2},
  {NULL, 0, NULL, 0}
}
Definition at line 512 of file auditctl.c.