audit: audisp/audispd-pconfig.h File Reference
audispd-pconfig.h File Reference
#include <sys/types.h>
#include "libaudit.h"
Data Structures
struct plugin_conf
Macros
#define MAX_PLUGIN_ARGS 2
Typedefs
typedef struct plugin_conf plugin_conf_t
Enumerations
enum active_t { A_NO, A_YES }
enum direction_t { D_UNSET, D_IN, D_OUT }
enum service_t { S_ALWAYS, S_BUILTIN, S_AF_UNIX, S_SYSLOG }
enum format_t { F_BINARY, F_STRING, F_ASCII, F_MANAGED }
Functions
void clear_pconfig (plugin_conf_t *config)
int load_pconfig (plugin_conf_t *config, char *file)
void free_pconfig (plugin_conf_t *config)
Macro Definition Documentation
#define MAX_PLUGIN_ARGS 2
Definition at line 29 of file audispd-pconfig.h.
Referenced by clear_pconfig(), and free_pconfig().
Typedef Documentation
typedef struct plugin_conf plugin_conf_t
Enumeration Type Documentation
enum active_t
Enumerator
A_NO
A_YES
Definition at line 31 of file audispd-pconfig.h.
enum direction_t
Enumerator
D_UNSET
D_IN
D_OUT
Definition at line 32 of file audispd-pconfig.h.
enum format_t
Enumerator
F_BINARY
F_STRING
F_ASCII
F_MANAGED
Definition at line 34 of file audispd-pconfig.h.
enum service_t
Enumerator
S_ALWAYS
S_BUILTIN
S_AF_UNIX
S_SYSLOG
Definition at line 33 of file audispd-pconfig.h.
Function Documentation
void clear_pconfig (plugin_conf_t * config)
Definition at line 117 of file audispd-pconfig.c.
References A_NO, plugin_conf::active, plugin_conf::args, plugin_conf::checked, D_UNSET, plugin_conf::direction, F_STRING, plugin_conf::format, plugin_conf::inode, MAX_PLUGIN_ARGS, plugin_conf::name, plugin_conf::path, plugin_conf::pid, plugin_conf::plug_pipe, plugin_conf::restart_cnt, S_ALWAYS, and plugin_conf::type.
Referenced by load_pconfig().
void free_pconfig (plugin_conf_t * config)
Definition at line 500 of file audispd-pconfig.c.
References plugin_conf::args, MAX_PLUGIN_ARGS, plugin_conf::name, plugin_conf::path, and plugin_conf::plug_pipe.
Referenced by main().
int load_pconfig (plugin_conf_t * config, char * file)
Definition at line 137 of file audispd-pconfig.c.
References audit_msg, clear_pconfig(), auparse_test::f, kw_pair::max_options, nv_pair::name, plugin_conf::name, kw_pair::name, nv_pair::option, kw_pair::parser, and nv_pair::value.