audit: src/auditd-dispatch.c File Reference
auditd-dispatch.c File Reference
#include "config.h"
#include <unistd.h>
#include <sys/uio.h>
#include <fcntl.h>
#include <signal.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include "libaudit.h"
#include "private.h"
#include "auditd-dispatch.h"
Macros
#define REPORT_LIMIT 10
Functions
int dispatcher_pid (void)
void dispatcher_reaped (void)
int init_dispatcher (const struct daemon_conf *config)
void shutdown_dispatcher (void)
void reconfigure_dispatcher (const struct daemon_conf *config)
int dispatch_event (const struct audit_reply *rep, int is_err)
Macro Definition Documentation
#define REPORT_LIMIT 10
Definition at line 41 of file auditd-dispatch.c.
Function Documentation
int dispatch_event (const struct audit_reply * rep, int is_err)
Definition at line 157 of file auditd-dispatch.c.
References AUDISP_PROTOCOL_VER, AUDIT_DAEMON_RECONFIG, AUDIT_DAEMON_ROTATE, audit_dispatcher_header::hlen, audit_reply::len, audit_reply::message, audit_dispatcher_header::size, audit_reply::type, audit_dispatcher_header::type, and audit_dispatcher_header::ver.
int dispatcher_pid (void)
Definition at line 43 of file auditd-dispatch.c.
References auparse_test::pid.
void dispatcher_reaped (void)
Definition at line 48 of file auditd-dispatch.c.
References audit_msg, auparse_test::pid, and shutdown_dispatcher().
int init_dispatcher (const struct daemon_conf * config)
Definition at line 72 of file auditd-dispatch.c.
References audit_msg, daemon_conf::dispatcher, auparse_test::exit, auparse_test::pid, daemon_conf::qos, and QOS_NON_BLOCKING.
Referenced by main(), and reconfigure_dispatcher().
void reconfigure_dispatcher (const struct daemon_conf * config)
Definition at line 147 of file auditd-dispatch.c.
References init_dispatcher(), and auparse_test::pid.
void shutdown_dispatcher (void)
Definition at line 127 of file auditd-dispatch.c.
References auparse_test::pid.
Referenced by dispatcher_reaped(), and main().