audit: audisp/plugins/remote/audisp-remote.c File Reference
audisp-remote.c File Reference
#include "config.h"
#include <stdio.h>
#include <signal.h>
#include <syslog.h>
#include <string.h>
#include <ctype.h>
#include <netdb.h>
#include <unistd.h>
#include <stdlib.h>
#include <errno.h>
#include <time.h>
#include <fcntl.h>
#include <sys/select.h>
#include <poll.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include "libaudit.h"
#include "private.h"
#include "remote-config.h"
#include "queue.h"
#include "remote-fgets.h"
Macros
#define CONFIG_FILE "/etc/audisp/audisp-remote.conf"
#define BUF_SIZE 32
#define QUEUE_ENTRY_SIZE (3*4096)
#define ET_SUCCESS 0
#define ET_PERMANENT -1
#define ET_TEMPORARY -2
#define verify(E)
Functions
int main (int argc, char *argv[])
Variables
remote_conf_t config
Macro Definition Documentation
#define BUF_SIZE 32
Definition at line 58 of file audisp-remote.c.
#define CONFIG_FILE "/etc/audisp/audisp-remote.conf"
Definition at line 57 of file audisp-remote.c.
Referenced by main().
#define ET_PERMANENT -1
Definition at line 66 of file audisp-remote.c.
Referenced by main().
#define ET_SUCCESS 0
Definition at line 65 of file audisp-remote.c.
Referenced by main().
#define ET_TEMPORARY -2
Definition at line 67 of file audisp-remote.c.
#define QUEUE_ENTRY_SIZE (3*4096)
Definition at line 62 of file audisp-remote.c.
#define verify (E)
Value:
do {                \
        char verify__[(E) ? 1 : -1];    \
        (void)verify__;         \
    } while (0)
Definition at line 104 of file audisp-remote.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 421 of file audisp-remote.c.
References CONFIG_FILE, ET_PERMANENT, ET_SUCCESS, FA_RECONNECT, free_config(), remote_conf::heartbeat_timeout, hup, load_config(), remote_conf::local_port, MAX_AUDIT_MESSAGE_LENGTH, q_append(), q_close(), q_queue_length(), remote_conf::remote_ending_action, remote_fgets(), remote_fgets_eof(), remote_fgets_more(), and stop.
Variable Documentation
remote_conf_t config
Definition at line 78 of file audisp-remote.c.
Referenced by auditd_tcp_listen_init(), get_auditfail_action(), init_event(), and main().