audit: audisp/plugins/prelude/audisp-int.c File Reference
audisp-int.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include "audisp-int.h"
Functions
void ilist_create (ilist *l)
int_node * ilist_next (ilist *l)
void ilist_append (ilist *l, int num)
int ilist_find_num (ilist *l, unsigned int num)
void ilist_clear (ilist *l)
int ilist_add_if_uniq (ilist *l, int num)
Function Documentation
int ilist_add_if_uniq (ilist * l, int num)
Definition at line 98 of file audisp-int.c.
References ilist::head, ilist_append(), _int_node::next, and _int_node::num.
Referenced by main().
void ilist_append (ilist * l, int num)
Definition at line 44 of file audisp-int.c.
References ilist::cnt, ilist::cur, ilist::head, _int_node::next, and _int_node::num.
Referenced by ilist_add_if_uniq().
void ilist_clear (ilist * l)
Definition at line 79 of file audisp-int.c.
Referenced by destroy_counters(), free_config(), and main().
void ilist_create (ilist * l)
Definition at line 29 of file audisp-int.c.
Referenced by clear_config(), destroy_counters(), main(), and reset_counters().
int ilist_find_num (ilist * l, unsigned int num)
Definition at line 64 of file audisp-int.c.
References ilist::cur, ilist::head, _int_node::next, and _int_node::num.
int_node* ilist_next (ilist * l)
Definition at line 36 of file audisp-int.c.
Referenced by main(), and match().