audit: audisp/audispd-pconfig.c File Reference
audispd-pconfig.c File Reference
#include "config.h"
#include <string.h>
#include <stdio.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <errno.h>
#include <unistd.h>
#include <stdlib.h>
#include <libgen.h>
#include "audispd-pconfig.h"
#include "private.h"
Data Structures
struct nv_pair
struct kw_pair
struct nv_list
Functions
void clear_pconfig (plugin_conf_t *config)
int load_pconfig (plugin_conf_t *config, char *file)
void free_pconfig (plugin_conf_t *config)
Function Documentation
void clear_pconfig (plugin_conf_t * config)
Definition at line 117 of file audispd-pconfig.c.
References A_NO, plugin_conf::active, plugin_conf::args, plugin_conf::checked, D_UNSET, plugin_conf::direction, F_STRING, plugin_conf::format, plugin_conf::inode, MAX_PLUGIN_ARGS, plugin_conf::name, plugin_conf::path, plugin_conf::pid, plugin_conf::plug_pipe, plugin_conf::restart_cnt, S_ALWAYS, and plugin_conf::type.
Referenced by load_pconfig().
void free_pconfig (plugin_conf_t * config)
Definition at line 500 of file audispd-pconfig.c.
References plugin_conf::args, MAX_PLUGIN_ARGS, plugin_conf::name, plugin_conf::path, and plugin_conf::plug_pipe.
Referenced by main().
int load_pconfig (plugin_conf_t * config, char * file)
Definition at line 137 of file audispd-pconfig.c.
References audit_msg, clear_pconfig(), auparse_test::f, kw_pair::max_options, nv_pair::name, plugin_conf::name, kw_pair::name, nv_pair::option, kw_pair::parser, and nv_pair::value.