audit: audisp/plugins/prelude/audisp-int.h File Reference
audisp-int.h File Reference
#include "config.h"
#include <sys/types.h>
Data Structures
struct _int_node
struct ilist
Typedefs
typedef struct _int_node int_node
Functions
void ilist_create (ilist *l)
int_node * ilist_next (ilist *l)
void ilist_append (ilist *l, int num)
void ilist_clear (ilist *l)
int ilist_find_num (ilist *l, unsigned int num)
int ilist_add_if_uniq (ilist *l, int num)
Typedef Documentation
typedef struct _int_node int_node
Function Documentation
int ilist_add_if_uniq (ilist * l, int num)
Definition at line 98 of file audisp-int.c.
References ilist::head, ilist_append(), _int_node::next, and _int_node::num.
Referenced by main().
void ilist_append (ilist * l, int num)
Definition at line 44 of file audisp-int.c.
References ilist::cnt, ilist::cur, ilist::head, _int_node::next, and _int_node::num.
Referenced by ilist_add_if_uniq().
void ilist_clear (ilist * l)
Definition at line 79 of file audisp-int.c.
void ilist_create (ilist * l)
Definition at line 29 of file audisp-int.c.
int ilist_find_num (ilist * l, unsigned int num)
Definition at line 64 of file audisp-int.c.
References ilist::cur, ilist::head, _int_node::next, and _int_node::num.
int_node* ilist_next (ilist * l)
Definition at line 36 of file audisp-int.c.