audit: tools/aulastlog/aulastlog.c File Reference
aulastlog.c File Reference
#include <stdio.h>
#include <locale.h>
#include <string.h>
#include <errno.h>
#include <pwd.h>
#include "auparse.h"
#include "aulastlog-llist.h"
Functions
void usage (void)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 37 of file aulastlog.c.
References auparse_destroy(), auparse_find_field(), auparse_get_field_int(), auparse_get_timestamp(), auparse_init(), auparse_next_event(), ausearch_add_item(), ausearch_next_event(), AUSEARCH_RULE_AND, AUSEARCH_RULE_CLEAR, ausearch_set_stop(), AUSEARCH_STOP_RECORD, AUSOURCE_FILE_POINTER, AUSOURCE_LOGS, _lnode::host, list_append(), list_clear(), list_create(), list_find_uid(), list_first(), list_next(), list_update_host(), list_update_login(), list_update_term(), _lnode::name, _lnode::sec, au_event_t::sec, _lnode::term, _lnode::uid, and usage().
void usage (void)
Definition at line 32 of file aulastlog.c.
References usage().