audit: tools/aulastlog/aulastlog-llist.c File Reference
aulastlog-llist.c File Reference
#include <stdlib.h>
#include <string.h>
#include "aulastlog-llist.h"
Functions
void list_create (llist *l)
lnode * list_next (llist *l)
void list_append (llist *l, lnode *node)
void list_clear (llist *l)
int list_update_login (llist *l, time_t t)
int list_update_host (llist *l, const char *h)
int list_update_term (llist *l, const char *t)
lnode * list_find_uid (llist *l, uid_t uid)
Function Documentation
void list_append (llist * l, lnode * node)
Definition at line 43 of file aulastlog-llist.c.
References _lnode::a0, _lnode::a1, llist::cnt, llist::cur, llist::head, _lnode::host, _lnode::item, _lnode::message, _lnode::mlen, _lnode::name, _lnode::next, _lnode::sec, _lnode::term, _lnode::type, and _lnode::uid.
void list_clear (llist * l)
Definition at line 74 of file aulastlog-llist.c.
References llist::cnt, llist::cur, llist::head, _lnode::host, _lnode::name, _lnode::next, _lnode::r, and _lnode::term.
void list_create (llist * l)
Definition at line 28 of file aulastlog-llist.c.
References llist::cnt, llist::cur, and llist::head.
lnode* list_find_uid (llist * l, uid_t uid)
Definition at line 134 of file aulastlog-llist.c.
References llist::cur, llist::head, _lnode::next, and _lnode::uid.
Referenced by main().
lnode* list_next (llist * l)
Definition at line 35 of file aulastlog-llist.c.
References llist::cur, and _lnode::next.
int list_update_host (llist * l, const char * h)
Definition at line 104 of file aulastlog-llist.c.
References _lnode::host.
Referenced by main().
int list_update_login (llist * l, time_t t)
Definition at line 93 of file aulastlog-llist.c.
References _lnode::sec.
Referenced by main().
int list_update_term (llist * l, const char * t)
Definition at line 119 of file aulastlog-llist.c.
References _lnode::term.
Referenced by main().