audit: tools/aulastlog/aulastlog-llist.h File Reference
aulastlog-llist.h File Reference
#include <sys/types.h>
Data Structures
struct _lnode
struct llist
Typedefs
typedef struct _lnode lnode
Functions
void list_create (llist *l)
lnode * list_next (llist *l)
void list_append (llist *l, lnode *node)
void list_clear (llist *l)
int list_update_login (llist *l, time_t t)
int list_update_host (llist *l, const char *h)
int list_update_term (llist *l, const char *t)
lnode * list_find_uid (llist *l, uid_t uid)
Typedef Documentation
typedef struct _lnode lnode
Function Documentation
void list_append (llist * l, lnode * node)
Definition at line 99 of file ausearch-llist.c.
References _lnode::a0, _lnode::a1, llist::cnt, llist::cur, llist::head, _lnode::host, _lnode::item, _lnode::message, _lnode::mlen, _lnode::name, _lnode::next, _lnode::sec, _lnode::term, _lnode::type, and _lnode::uid.
void list_clear (llist * l)
Definition at line 89 of file auditctl-llist.c.
References search_items::acct, alist_clear(), search_items::arch, search_items::avc, llist::cnt, search_items::comm, llist::cur, search_items::cwd, llist::e, search_items::egid, search_items::euid, search_items::exe, search_items::exit, search_items::exit_is_set, search_items::filename, search_items::gid, llist::head, _lnode::host, search_items::hostname, search_items::key, search_items::loginuid, _lnode::message, event::milli, _lnode::name, _lnode::next, event::node, search_items::pid, search_items::ppid, _lnode::r, llist::s, S_UNSET, event::sec, event::serial, search_items::session_id, slist_clear(), search_items::success, search_items::syscall, _lnode::term, search_items::terminal, event::type, search_items::uid, search_items::uuid, and search_items::vmname.
Referenced by audit_print_reply(), delete_all_rules(), lol_clear(), and main().
void list_create (llist * l)
Definition at line 28 of file auditctl-llist.c.
References search_items::acct, search_items::arch, search_items::avc, llist::cnt, search_items::comm, llist::cur, search_items::cwd, llist::e, search_items::egid, search_items::euid, search_items::exe, search_items::exit, search_items::exit_is_set, search_items::filename, search_items::gid, llist::head, search_items::hostname, search_items::key, search_items::loginuid, event::milli, event::node, search_items::pid, search_items::ppid, llist::s, S_UNSET, event::sec, event::serial, search_items::session_id, search_items::success, search_items::syscall, search_items::terminal, event::type, search_items::uid, search_items::uuid, and search_items::vmname.
Referenced by audit_print_init(), delete_all_rules(), lol_add_record(), and main().
lnode* list_find_uid (llist * l, uid_t uid)
Definition at line 134 of file aulastlog-llist.c.
References llist::cur, llist::head, _lnode::next, and _lnode::uid.
Referenced by main().
lnode* list_next (llist * l)
Definition at line 53 of file auditctl-llist.c.
References llist::cur, and _lnode::next.
Referenced by audit_print_reply(), delete_all_rules(), extract_search_items(), main(), and match().
int list_update_host (llist * l, const char * h)
Definition at line 104 of file aulastlog-llist.c.
References _lnode::host.
Referenced by main().
int list_update_login (llist * l, time_t t)
Definition at line 93 of file aulastlog-llist.c.
References _lnode::sec.
Referenced by main().
int list_update_term (llist * l, const char * t)
Definition at line 119 of file aulastlog-llist.c.
References _lnode::term.
Referenced by main().