audit: tools/aulast/aulast.c File Reference
aulast.c File Reference
#include "config.h"
#include <stdio.h>
#include <locale.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <pwd.h>
#include <stdlib.h>
#include "libaudit.h"
#include "auparse.h"
#include "aulast-llist.h"
Functions
void usage (void)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 472 of file aulast.c.
References AUDIT_SYSTEM_BOOT, AUDIT_SYSTEM_SHUTDOWN, AUDIT_USER_END, AUDIT_USER_LOGIN, auparse_destroy(), auparse_get_type(), auparse_init(), auparse_next_event(), AUSOURCE_FILE, AUSOURCE_FILE_POINTER, AUSOURCE_LOGS, auparse_test::f, list_clear(), list_create(), list_first(), list_next(), process_shutdown(), auparse_test::type, and usage().
void usage (void)
Definition at line 45 of file aulast.c.
References usage().
Referenced by main(), and usage().