audit: auparse/auparse.h File Reference
auparse.h File Reference
#include "auparse-defs.h"
Typedefs
typedef struct opaque auparse_state_t
typedef void(* user_destroy)(void *user_data)
typedef void(* auparse_callback_ptr)(auparse_state_t *au, auparse_cb_event_t cb_event_type, void *user_data)
Functions
auparse_state_t * auparse_init (ausource_t source, const void *b)
int auparse_feed (auparse_state_t *au, const char *data, size_t data_len)
int auparse_flush_feed (auparse_state_t *au)
int auparse_feed_has_data (const auparse_state_t *au)
void auparse_add_callback (auparse_state_t *au, auparse_callback_ptr callback, void *user_data, user_destroy user_destroy_func)
void auparse_set_escape_mode (auparse_esc_t mode)
int auparse_reset (auparse_state_t *au)
void auparse_destroy (auparse_state_t *au)
int ausearch_add_expression (auparse_state_t *au, const char *expression, char **error, ausearch_rule_t how)
int ausearch_add_item (auparse_state_t *au, const char *field, const char *op, const char *value, ausearch_rule_t how)
int ausearch_add_interpreted_item (auparse_state_t *au, const char *field, const char *op, const char *value, ausearch_rule_t how)
int ausearch_add_timestamp_item (auparse_state_t *au, const char *op, time_t sec, unsigned milli, ausearch_rule_t how)
int ausearch_add_timestamp_item_ex (auparse_state_t *au, const char *op, time_t sec, unsigned milli, unsigned serial, ausearch_rule_t how)
int ausearch_add_regex (auparse_state_t *au, const char *expr)
int ausearch_set_stop (auparse_state_t *au, austop_t where)
void ausearch_clear (auparse_state_t *au)
int ausearch_next_event (auparse_state_t *au)
int auparse_next_event (auparse_state_t *au)
const au_event_t * auparse_get_timestamp (auparse_state_t *au)
time_t auparse_get_time (auparse_state_t *au)
unsigned int auparse_get_milli (auparse_state_t *au)
unsigned long auparse_get_serial (auparse_state_t *au)
const char * auparse_get_node (auparse_state_t *au)
int auparse_node_compare (au_event_t *e1, au_event_t *e2)
int auparse_timestamp_compare (au_event_t *e1, au_event_t *e2)
unsigned int auparse_get_num_records (auparse_state_t *au)
int auparse_first_record (auparse_state_t *au)
int auparse_next_record (auparse_state_t *au)
int auparse_goto_record_num (auparse_state_t *au, unsigned int num)
int auparse_get_type (auparse_state_t *au)
const char * auparse_get_type_name (auparse_state_t *au)
unsigned int auparse_get_line_number (auparse_state_t *au)
const char * auparse_get_filename (auparse_state_t *au)
int auparse_first_field (auparse_state_t *au)
int auparse_next_field (auparse_state_t *au)
unsigned int auparse_get_num_fields (auparse_state_t *au)
const char * auparse_get_record_text (auparse_state_t *au)
const char * auparse_find_field (auparse_state_t *au, const char *name)
const char * auparse_find_field_next (auparse_state_t *au)
const char * auparse_get_field_name (auparse_state_t *au)
const char * auparse_get_field_str (auparse_state_t *au)
int auparse_get_field_type (auparse_state_t *au)
int auparse_get_field_int (auparse_state_t *au)
const char * auparse_interpret_field (auparse_state_t *au)
Typedef Documentation
typedef void(* auparse_callback_ptr)(auparse_state_t *au, auparse_cb_event_t cb_event_type, void *user_data)
Definition at line 39 of file auparse.h.
typedef struct opaque auparse_state_t
Definition at line 36 of file auparse.h.
typedef void(* user_destroy)(void *user_data)
Definition at line 38 of file auparse.h.
Function Documentation
void auparse_add_callback (auparse_state_t * au, auparse_callback_ptr callback, void * user_data, user_destroy user_destroy_func)
Definition at line 223 of file auparse.c.
References opaque::callback, opaque::callback_user_data, and opaque::callback_user_data_destroy.
Referenced by main().
void auparse_destroy (auparse_state_t * au)
Definition at line 532 of file auparse.c.
References aulookup_destroy_gid_list(), aulookup_destroy_uid_list(), aup_list_clear(), ausearch_clear(), opaque::callback_user_data, opaque::callback_user_data_destroy, opaque::cur_buf, opaque::databuf, databuf_free(), EVENT_EMPTY, opaque::find_field, opaque::in, opaque::le, opaque::next_buf, opaque::parse_state, and opaque::source_list.
Referenced by compound_search(), main(), regex_search(), and simple_search().
int auparse_feed (auparse_state_t * au, const char * data, size_t data_len)
Definition at line 265 of file auparse.c.
References opaque::databuf, and databuf_append().
Referenced by main().
int auparse_feed_has_data (const auparse_state_t * au)
Definition at line 281 of file auparse.c.
References EVENT_ACCUMULATING, and opaque::parse_state.
Referenced by main().
const char* auparse_find_field (auparse_state_t * au, const char * name)
Definition at line 1272 of file auparse.c.
References auparse_find_field_next(), event_list_t::e, opaque::find_field, opaque::le, _rnode::nv, and au_event_t::sec.
Referenced by add_resource(), add_start_guest_event(), add_stop_guest_event(), extract_virt_fields(), main(), process_anom(), process_avc(), process_avc_selinux_context(), process_control_event(), process_machine_id_event(), process_resource_event(), and push_event().
const char* auparse_find_field_next (auparse_state_t * au)
Definition at line 1295 of file auparse.c.
int auparse_first_field (auparse_state_t * au)
Definition at line 1233 of file auparse.c.
References aup_list_first_field(), and opaque::le.
Referenced by push_event().
int auparse_first_record (auparse_state_t * au)
Definition at line 1138 of file auparse.c.
References aup_list_first_field(), auparse_next_event(), and opaque::le.
Referenced by add_start_guest_event(), add_stop_guest_event(), auparse_next_record(), ausearch_next_event(), extract_virt_fields(), light_test(), process_anom(), process_avc(), process_avc_selinux_context(), process_resource_event(), and push_event().
int auparse_flush_feed (auparse_state_t * au)
Definition at line 273 of file auparse.c.
Referenced by main().
int auparse_get_field_int (auparse_state_t * au)
Definition at line 1353 of file auparse.c.
References auparse_get_field_str(), and expr::v.
Referenced by add_start_guest_event(), add_stop_guest_event(), extract_virt_fields(), main(), and process_anom().
const char* auparse_get_field_name (auparse_state_t * au)
Definition at line 1322 of file auparse.c.
References event_list_t::e, opaque::le, _rnode::nv, and au_event_t::sec.
Referenced by compound_search(), main(), push_event(), regex_search(), and simple_search().
const char* auparse_get_field_str (auparse_state_t * au)
Definition at line 1333 of file auparse.c.
References event_list_t::e, opaque::le, _rnode::nv, and au_event_t::sec.
Referenced by auparse_get_field_int(), compound_search(), extract_virt_fields(), main(), regex_search(), and simple_search().
int auparse_get_field_type (auparse_state_t * au)
Definition at line 1343 of file auparse.c.
References AUPARSE_TYPE_UNCLASSIFIED, event_list_t::e, opaque::le, nvlist_get_cur_type(), and au_event_t::sec.
const char* auparse_get_filename (auparse_state_t * au)
Definition at line 1212 of file auparse.c.
References AUSOURCE_FILE, AUSOURCE_FILE_ARRAY, opaque::le, _rnode::list_idx, opaque::source, and opaque::source_list.
Referenced by light_test().
unsigned int auparse_get_line_number (auparse_state_t * au)
Definition at line 1202 of file auparse.c.
References opaque::le, and _rnode::line_number.
Referenced by light_test().
unsigned int auparse_get_milli (auparse_state_t * au)
Definition at line 1067 of file auparse.c.
References event_list_t::e, opaque::le, and au_event_t::milli.
Referenced by add_proof(), and extract_virt_fields().
const char* auparse_get_node (auparse_state_t * au)
Definition at line 1086 of file auparse.c.
References event_list_t::e, au_event_t::host, and opaque::le.
Referenced by push_event().
unsigned int auparse_get_num_fields (auparse_state_t * au)
Definition at line 1252 of file auparse.c.
References opaque::le, and _rnode::nv.
Referenced by light_test().
unsigned int auparse_get_num_records (auparse_state_t * au)
Definition at line 1131 of file auparse.c.
References opaque::le.
Referenced by light_test().
const char* auparse_get_record_text (auparse_state_t * au)
Definition at line 1261 of file auparse.c.
References opaque::le, and _rnode::record.
Referenced by process_anom(), and push_event().
unsigned long auparse_get_serial (auparse_state_t * au)
Definition at line 1076 of file auparse.c.
References event_list_t::e, opaque::le, and au_event_t::serial.
Referenced by add_proof(), and extract_virt_fields().
time_t auparse_get_time (auparse_state_t * au)
Definition at line 1058 of file auparse.c.
References event_list_t::e, opaque::le, and au_event_t::sec.
Referenced by add_proof(), and extract_virt_fields().
const au_event_t* auparse_get_timestamp (auparse_state_t * au)
Definition at line 1049 of file auparse.c.
References event_list_t::e, opaque::le, and au_event_t::sec.
Referenced by light_test(), main(), and push_event().
int auparse_get_type (auparse_state_t * au)
Definition at line 1182 of file auparse.c.
References opaque::le, and _rnode::type.
Referenced by light_test(), and main().
const char* auparse_get_type_name (auparse_state_t * au)
Definition at line 1192 of file auparse.c.
References audit_msg_type_to_name(), opaque::le, and _rnode::type.
int auparse_goto_record_num (auparse_state_t * au, unsigned int num)
Definition at line 1168 of file auparse.c.
References aup_list_goto_rec(), and opaque::le.
auparse_state_t* auparse_init (ausource_t source, const void * b)
Definition at line 111 of file auparse.c.
References aup_list_create(), AUSEARCH_STOP_EVENT, AUSOURCE_BUFFER, AUSOURCE_BUFFER_ARRAY, AUSOURCE_DESCRIPTOR, AUSOURCE_FEED, AUSOURCE_FILE, AUSOURCE_FILE_ARRAY, AUSOURCE_FILE_POINTER, AUSOURCE_LOGS, opaque::callback, opaque::callback_user_data, opaque::callback_user_data_destroy, opaque::cur_buf, opaque::databuf, databuf_append(), DATABUF_FLAG_PRESERVE_HEAD, databuf_free(), databuf_init(), EVENT_EMPTY, opaque::expr, opaque::find_field, opaque::in, opaque::le, opaque::line_number, opaque::line_pushed, opaque::list_idx, opaque::next_buf, opaque::off, opaque::parse_state, opaque::search_where, opaque::source, and opaque::source_list.
Referenced by compound_search(), init_auparse(), main(), regex_search(), and simple_search().
const char* auparse_interpret_field (auparse_state_t * au)
Definition at line 1368 of file auparse.c.
References event_list_t::e, opaque::le, nvlist_interp_cur_val(), and au_event_t::sec.
Referenced by add_resource(), extract_virt_fields(), main(), process_avc_selinux_context(), process_resource_event(), and push_event().
int auparse_next_event (auparse_state_t * au)
Definition at line 956 of file auparse.c.
References AUDIT_FIRST_ANOM_MSG, AUDIT_FIRST_EVENT, aup_list_append(), aup_list_clear(), aup_list_first_field(), aup_list_set_event(), opaque::cur_buf, event_list_t::e, EVENT_ACCUMULATING, EVENT_EMITTED, EVENT_EMPTY, au_event_t::host, opaque::le, opaque::line_number, opaque::list_idx, opaque::parse_state, and _rnode::type.
Referenced by auparse_first_record(), ausearch_next_event(), light_test(), and main().
int auparse_next_field (auparse_state_t * au)
Definition at line 1239 of file auparse.c.
References opaque::le, _rnode::nv, and nvlist_next().
Referenced by push_event().
int auparse_next_record (auparse_state_t * au)
Definition at line 1154 of file auparse.c.
References aup_list_next(), auparse_first_record(), and opaque::le.
Referenced by ausearch_next_event(), light_test(), and push_event().
int auparse_node_compare (au_event_t * e1, au_event_t * e2)
Definition at line 1095 of file auparse.c.
References au_event_t::host.
int auparse_reset (auparse_state_t * au)
Definition at line 293 of file auparse.c.
References aup_list_clear(), AUSOURCE_BUFFER, AUSOURCE_BUFFER_ARRAY, AUSOURCE_DESCRIPTOR, AUSOURCE_FILE, AUSOURCE_FILE_ARRAY, AUSOURCE_FILE_POINTER, AUSOURCE_LOGS, opaque::databuf, databuf_reset(), EVENT_EMPTY, opaque::in, opaque::le, opaque::line_number, opaque::list_idx, opaque::off, opaque::parse_state, and opaque::source.
Referenced by main().
void auparse_set_escape_mode (auparse_esc_t mode)
Definition at line 288 of file auparse.c.
References set_escape_mode().
int auparse_timestamp_compare (au_event_t * e1, au_event_t * e2)
Definition at line 1111 of file auparse.c.
References au_event_t::milli, au_event_t::sec, and au_event_t::serial.
int ausearch_add_expression (auparse_state_t * au, const char * expression, char ** error, ausearch_rule_t how)
Definition at line 467 of file auparse.c.
References err, and expr_parse().
Referenced by create_search_criteria().
int ausearch_add_interpreted_item (auparse_state_t * au, const char * field, const char * op, const char * value, ausearch_rule_t how)
Definition at line 408 of file auparse.c.
References EO_INTERPRETED_EQ, and EO_INTERPRETED_NE.
Referenced by create_search_criteria().
int ausearch_add_item (auparse_state_t * au, const char * field, const char * op, const char * value, ausearch_rule_t how)
Definition at line 401 of file auparse.c.
References EO_RAW_EQ, and EO_RAW_NE.
Referenced by compound_search(), create_search_criteria(), main(), and simple_search().
int ausearch_add_regex (auparse_state_t * au, const char * expr)
Definition at line 492 of file auparse.c.
References expr_create_regexp_expression().
Referenced by regex_search().
int ausearch_add_timestamp_item (auparse_state_t * au, const char * op, time_t sec, unsigned milli, ausearch_rule_t how)
Definition at line 461 of file auparse.c.
References ausearch_add_timestamp_item_ex().
Referenced by create_search_criteria().
int ausearch_add_timestamp_item_ex (auparse_state_t * au, const char * op, time_t sec, unsigned milli, unsigned serial, ausearch_rule_t how)
Definition at line 415 of file auparse.c.
References EO_VALUE_EQ, EO_VALUE_GE, EO_VALUE_GT, EO_VALUE_LE, EO_VALUE_LT, expr_create_timestamp_comparison_ex(), expr::name, auparse_test::name, and expr::value.
Referenced by ausearch_add_timestamp_item().
void ausearch_clear (auparse_state_t * au)
Definition at line 523 of file auparse.c.
References AUSEARCH_STOP_EVENT, opaque::expr, expr_free(), and opaque::search_where.
Referenced by auparse_destroy(), and main().
int ausearch_next_event (auparse_state_t * au)
Definition at line 928 of file auparse.c.
References auparse_first_record(), auparse_next_event(), auparse_next_record(), and opaque::expr.
Referenced by compound_search(), main(), regex_search(), and simple_search().
int ausearch_set_stop (auparse_state_t * au, austop_t where)
Definition at line 512 of file auparse.c.
References AUSEARCH_STOP_FIELD, and opaque::search_where.
Referenced by compound_search(), main(), regex_search(), and simple_search().