audit: auparse/test/auparse_test.c File Reference
auparse_test.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <locale.h>
#include <errno.h>
#include <libaudit.h>
#include <auparse.h>
Functions
void light_test (auparse_state_t *au)
void simple_search (ausource_t source, austop_t where)
void compound_search (ausearch_rule_t how)
void regex_search (const char *expr)
int main (void)
Function Documentation
void compound_search (ausearch_rule_t how)
Definition at line 135 of file auparse_test.c.
References auparse_destroy(), auparse_get_field_name(), auparse_get_field_str(), auparse_init(), ausearch_add_item(), ausearch_next_event(), AUSEARCH_RULE_AND, AUSEARCH_RULE_CLEAR, ausearch_set_stop(), AUSEARCH_STOP_FIELD, AUSOURCE_FILE, and auparse_test::exit.
Referenced by main().
void light_test (auparse_state_t * au)
Definition at line 66 of file auparse_test.c.
References audit_msg_type_to_name(), auparse_first_record(), auparse_get_filename(), auparse_get_line_number(), auparse_get_num_fields(), auparse_get_num_records(), auparse_get_timestamp(), auparse_get_type(), auparse_next_event(), auparse_next_record(), auparse_test::exit, au_event_t::host, au_event_t::milli, au_event_t::sec, and au_event_t::serial.
Referenced by main().
int main (void)
Definition at line 266 of file auparse_test.c.
References auparse_add_callback(), auparse_destroy(), auparse_feed(), auparse_find_field(), auparse_find_field_next(), auparse_flush_feed(), auparse_get_field_name(), auparse_get_field_str(), auparse_init(), auparse_interpret_field(), auparse_next_event(), auparse_reset(), ausearch_add_item(), ausearch_clear(), ausearch_next_event(), AUSEARCH_RULE_AND, AUSEARCH_RULE_CLEAR, AUSEARCH_RULE_OR, ausearch_set_stop(), AUSEARCH_STOP_EVENT, AUSEARCH_STOP_FIELD, AUSEARCH_STOP_RECORD, AUSOURCE_BUFFER, AUSOURCE_BUFFER_ARRAY, AUSOURCE_FEED, AUSOURCE_FILE, AUSOURCE_FILE_ARRAY, auparse_test::chunk_len, compound_search(), auparse_test::exit, auparse_test::files, light_test(), regex_search(), and simple_search().
void regex_search (const char * expr)
Definition at line 192 of file auparse_test.c.
References auparse_destroy(), auparse_get_field_name(), auparse_get_field_str(), auparse_init(), ausearch_add_regex(), ausearch_next_event(), ausearch_set_stop(), AUSEARCH_STOP_RECORD, AUSOURCE_BUFFER_ARRAY, and auparse_test::exit.
Referenced by main().
void simple_search (ausource_t source, austop_t where)
Definition at line 103 of file auparse_test.c.
References auparse_destroy(), auparse_get_field_name(), auparse_get_field_str(), auparse_init(), ausearch_add_item(), ausearch_next_event(), AUSEARCH_RULE_CLEAR, ausearch_set_stop(), AUSOURCE_BUFFER_ARRAY, AUSOURCE_FILE, and auparse_test::exit.
Referenced by main().