audit: bindings/python/auparse_python.c File Reference
auparse_python.c File Reference
#include <Python.h>
#include "structmember.h"
#include <errno.h>
#include <time.h>
#include "auparse.h"
Data Structures
struct AuEvent
struct AuParser
struct CallbackData
Macros
#define MODINITERROR return
#define PYNUM_FROMLONG PyInt_FromLong
#define PYSTR_CHECK PyString_Check
#define PYSTR_FROMSTRING PyString_FromString
#define PYSTR_ASSTRING PyString_AsString
#define PYFILE_ASFILE(f) PyFile_AsFile(f)
#define PARSER_CHECK
Functions
PyDoc_STRVAR (AuEvent_doc,"An internal object which encapsulates the timestamp, serial number\n\ and host information of an audit event. The object cannot be\n\ instantiated from python code, rather it is returned from the\n\ audit parsing API.")
void callback_data_destroy (void *user_data)
PyDoc_STRVAR (feed_doc,"feed(data) supplies new data for the parser to consume.\n\ \n\ AuParser() must have been called with a source type of AUSOURCE_FEED.\n\ The parser consumes as much data as it can invoking a user supplied\n\ callback specified with add_callback() with a cb_event_type of\n\ AUPARSE_CB_EVENT_READY each time the parser recognizes a complete event\n\ in the data stream. Data not fully parsed will persist and be prepended\n\ to the next feed data. After all data has been feed to the parser flush_feed()\n\ should be called to signal the end of input data and flush any pending\n\ parse data through the parsing system.\n\ \n\ Returns None.\n\ Raises exception (EnvironmentError) on error\n\ ")
PyDoc_STRVAR (flush_feed_doc,"flush_feed() flush any unconsumed feed data through parser\n\ \n\ flush_feed() should be called to signal the end of feed input data\n\ and flush any pending parse data through the parsing system.\n\ \n\ Returns None.\n\ Raises exception (EnvironmentError) on error\n\ ")
PyDoc_STRVAR (add_callback_doc,"add_callback(callback, user_data) add a callback handler for notifications.\n\ \n\ auparse_add_callback adds a callback function to the parse state which\n\ is invoked to notify the application of parsing events.\n\ \n\ The signature of the callback is:\n\ \n\ callback(au, cb_event_type,user_data)\n\ \n\ When the callback is invoked it is passed:\n\ au: the AuParser object\n\ cb_event_type: enumerated value indicating the reason why the callback was invoked\n\ user_data: user supplied private data\n\ \n\ The cb_event_type argument indicates why the callback was invoked.\n\ It's possible values are:\n\ \n\ AUPARSE_CB_EVENT_READY\n\ A complete event has been parsed and is ready to be examined.\n\ This is logically equivalent to the parse state immediately following\n\ auparse_next_event()\n\ \n\ Returns None.\n\ Raises exception (EnvironmentError) on error\n\ ")
PyDoc_STRVAR (set_escape_mode_doc,"set_escape_mode() Set audit parser escaping\n\ \n\ This function sets the character escaping applied to value fields in the audit record.\n\ Returns None.\n\ ")
PyDoc_STRVAR (reset_doc,"reset() Reset audit parser instance\n\ \n\ reset resets all internal cursors to the beginning.\n\ It closes files and descriptors.\n\ \n\ Returns None.\n\ Raises exception (EnvironmentError) on error\n\ ")
PyDoc_STRVAR (search_add_expression_doc,"search_add_expression(expression, how) Build up search expression\n\ \n\ \n\ ausearch_add_item adds an expression to the current audit search\n\ expression. The search conditions can then be used to scan logs,\n\ files, or buffers for something of interest. The expression parameter\n\ contains an expression, as specified in ausearch-expression(5).\n\ \n\ The how parameter determines how this search expression will affect the\n\ existing search expression, if one is already defined. The possible\n\ values are:\n\ \n\ AUSEARCH_RULE_CLEAR:\n\ Clear the current search expression, if any, and use only this search\n\ expression.\n\ \n\ AUSEARCH_RULE_OR:\n\ \n\ If a search expression E is already configured, replace it by\n\ (E || this_search_expression).\n\ \n\ AUSEARCH_RULE_AND:\n\ If a search expression E is already configured, replace it by\n\ (E && this_search_expression).\n\ \n\ No Return value, raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (search_add_item_doc,"search_add_item(field, op, value, how) Build up search rule\n\ \n\ \n\ search_add_item() adds one search condition to the current audit search\n\ expression. The search conditions can then be used to scan logs, files, or\n\ buffers for something of interest. The field value is the field name\n\ that the value will be checked for. The op variable describes what\n\ kind of check is to be done. Legal op values are:\n\ \n\ 'exists':\n\ Just check that a field name exists\n\ \n\ '=':\n\ locate the field name and check that the value associated with it\n\ is equal to the value given in this rule.\n\ \n\ '!=':\n\ locate the field name and check that the value associated with\n\ it is NOT equal to the value given in this rule.\n\ \n\ The value parameter is compared to the uninterpreted field value.\n\ \n\ The how parameter determines how this search expression will affect the\n\ existing search expression, if one is already defined. The possible\n\ values are:\n\ \n\ AUSEARCH_RULE_CLEAR:\n\ Clear the current search expression, if any, and use only this search\n\ expression.\n\ \n\ AUSEARCH_RULE_OR:\n\ \n\ If a search expression E is already configured, replace it by\n\ (E || this_search_expression).\n\ \n\ AUSEARCH_RULE_AND:\n\ If a search expression E is already configured, replace it by\n\ (E && this_search_expression).\n\ \n\ No Return value, raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (search_add_interpreted_item_doc,"search_add_interpreted_item(field, op, value, how) Build up search rule\n\ \n\ \n\ search_add_interpreted_item() adds one search condition to the current audit\n\ search expression. The search conditions can then be used to scan logs,\n\ files, or buffers for something of interest. The field value is the field\n\ name that the value will be checked for. The op variable describes what\n\ kind of check is to be done. Legal op values are:\n\ \n\ 'exists':\n\ Just check that a field name exists\n\ \n\ '=':\n\ locate the field name and check that the value associated with it\n\ is equal to the value given in this rule.\n\ \n\ '!=':\n\ locate the field name and check that the value associated with\n\ it is NOT equal to the value given in this rule.\n\ \n\ The value parameter is compared to the interpreted field value (the value\n\ that would be returned by AuParser.interpret_field).\n\ \n\ The how parameter determines how this search expression will affect the\n\ existing search expression, if one is already defined. The possible\n\ values are:\n\ \n\ AUSEARCH_RULE_CLEAR:\n\ Clear the current search expression, if any, and use only this search\n\ expression.\n\ \n\ AUSEARCH_RULE_OR:\n\ \n\ If a search expression E is already configured, replace it by\n\ (E || this_search_expression).\n\ \n\ AUSEARCH_RULE_AND:\n\ If a search expression E is already configured, replace it by\n\ (E && this_search_expression).\n\ \n\ No Return value, raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (search_add_timestamp_item_doc,"search_add_timestamp_item(op, sec, milli, how) Build up search rule\n\ \n\ \n\ search_add_timestamp_item adds an event time condition to the current audit\n\ search expression. The search conditions can then be used to scan logs,\n\ files, or buffers for something of interest. The op parameter specifies the\n\ desired comparison. Legal op values are \"<\", \"<=\", \">=\", \">\" and\n\ \"=\". The left operand of the comparison operator is the timestamp of the\n\ examined event, the right operand is specified by the sec and milli\n\ parameters.\n\ \n\ The how parameter determines how this search expression will affect the\n\ existing search expression, if one is already defined. The possible\n\ values are:\n\ \n\ AUSEARCH_RULE_CLEAR:\n\ Clear the current search expression, if any, and use only this search\n\ expression.\n\ \n\ AUSEARCH_RULE_OR:\n\ \n\ If a search expression E is already configured, replace it by\n\ (E || this_search_expression).\n\ \n\ AUSEARCH_RULE_AND:\n\ If a search expression E is already configured, replace it by\n\ (E && this_search_expression).\n\ \n\ No Return value, raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (search_add_timestamp_item_ex_doc,"search_add_timestamp_item_ex(op, sec, milli, serial, how) Build up search rule\n\ search_add_timestamp_item_ex adds an event time condition to the current audit\n\ search expression. Its similar to search_add_timestamp_item except it adds\n\ the event serial number.\n\ ")
PyDoc_STRVAR (search_add_regex_doc,"search_add_regex(regexp) Add a regular expression to the search criteria.\n\ \n\ No Return value, raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (search_set_stop_doc,"search_set_stop(where) Set where cursor is positioned on search match.\n\ \n\ search_set_stop() determines where the internal cursor will stop when\n\ a search condition is met. The possible values are:\n\ \n\ AUSEARCH_STOP_EVENT:\n\ This one repositions the cursors to the first field of the first\n\ record of the event con- taining the items searched for.\n\ \n\ AUSEARCH_STOP_RECORD:\n\ This one repositions the cursors to the first field of the record\n\ containing the items searched for.\n\ \n\ AUSEARCH_STOP_FIELD:\n\ This one simply stops on the current field when the evaluation of the\n\ rules becomes true.\n\ \n\ No Return value, raises exception (ValueError) on error.\n\ ")
PyDoc_STRVAR (search_clear_doc,"search_clear() Clear search parameters.\n\ \n\ ausearch_clear clears any search parameters stored in the parser\n\ instance and frees memory associated with it.\n\ \n\ No Return value.\n\ ")
PyDoc_STRVAR (search_next_event_doc,"search_next_event() Find the next event that meets search criteria.\n\ \n\ search_next_event() will scan the input source and evaluate whether\n\ any record in an event contains the data being searched\n\ for. Evaluation is done at the record level.\n\ \n\ Returns True if a match was found\n\ Returns False if a match was not found.\n\ \n\ Raises exception (EnvironmentError) on error\n\ ")
PyDoc_STRVAR (parse_next_event_doc,"parse_next_event() Advance the parser to the next event.\n\ \n\ parse_next_event() will position the cursors at the first field of the first\n\ record of the next event in a file or buffer. It does not skip events\n\ or honor any search criteria that may be stored.\n\ \n\ Returns True if parser advances to next event.\n\ Returns False if there are no more events to parse\n\ \n\ Raises exception (EnvironmentError) on error\n\ ")
PyDoc_STRVAR (get_timestamp_doc,"get_timestamp() Return current event's timestamp.\n\ \n\ Returns the current event's timestamp info as an AuEvent object.\n\ No Return value, raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (get_num_records_doc,"get_num_records() Get the number of records.\n\ \n\ Returns the number of records in the current event.\n\ Raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (first_record_doc,"first_record() Reposition record cursor.\n\ \n\ first_record() repositions the internal cursors of the parsing library\n\ to point to the first record in the current event.\n\ \n\ Return True for success, False if there is no event data.\n\ Raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (next_record_doc,"next_record() Advance record cursor.\n\ \n\ next_record() will move the internal library cursors to point to the\n\ next record of the current event.\n\ \n\ Returns True on success, False if no more records in current event\n\ Raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (goto_record_num_doc,"goto_record_num() Move record cursor to specific position.\n\ \n\ goto_record_num() will move the internal library cursors to point\n\ to a specific physical record number. Records within the same event are\n\ numbered starting from 0. This is generally not needed but there are\n\ some cases where one may want precise control over the exact record\n\ being looked at.\n\ \n\ Returns True on success, False if no more records in current event\n\ Raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (get_type_doc,"get_type() Get record’s type.\n\ \n\ get_type() will return the integer value for the current record of the\n\ current event.\n\ \n\ Returns record type.\n\ Raises exception (LookupError) on error.\n\ ")
PyDoc_STRVAR (get_type_name_doc,"get_type_name() Get current record’s type name.\n\ \n\ get_type_name() allows access to the current record type name in the\n\ current event.\n\ \n\ Returns None if the record type name is unavailable.\n\ ")
PyDoc_STRVAR (get_line_number_doc,"auparse_get_line_number() get line number where record was found\n\ \n\ get_line_number will return the source input line number for\n\ the current record of the current event. Line numbers start at 1. If\n\ the source input type is AUSOURCE_FILE_ARRAY the line numbering will\n\ reset back to 1 each time a new life in the file array is opened.\n\ ")
PyDoc_STRVAR (get_filename_doc,"auparse_get_filename() get the filename where record was found\n\ get_filename() will return the name of the source file where the\n\ record was found if the source type is AUSOURCE_FILE or\n\ AUSOURCE_FILE_ARRAY. For other source types the return value will be\n\ None.\n\ ")
PyDoc_STRVAR (first_field_doc,"first_field() Reposition field cursor.\n\ \n\ Returns True on success, False if there is no event data\n\ ")
PyDoc_STRVAR (next_field_doc,"next_field() Advance the field cursor.\n\ \n\ next_field() moves the library’s internal cursor to point to the next\n\ field in the current record of the current event.\n\ \n\ Returns True on success, False if there is no more fields exist\n\ ")
PyDoc_STRVAR (get_num_fields_doc,"get_num_fields() Get the number of fields.\n\ \n\ Returns the number of fields in the current event.\n\ Raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (get_record_text_doc,"get_record_text() Return unparsed record data\n\ \n\ get_record_text() returns the full unparsed record.\n\ Raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (find_field_doc,"find_field(name) Search for field name.\n\ \n\ find_field() will scan all records in an event to find the first\n\ occurance of the field name passed to it. Searching begins from the\n\ cursor’s current position. The field name is stored for subsequent\n\ searching.\n\ \n\ Returns value associated with field or None if not found.\n\ ")
const char * auparse_find_field_next (auparse_state_t *au)
PyDoc_STRVAR (find_field_next_doc,"find_field_next() Get next occurrance of field name\n\ \n\ find_field_next() returns the value associated next occurrance of field name.\n\ Returns value associated with field or None if there is no next field.\n\ Raises exception (EnvironmentError) on error.\n\ ")
PyDoc_STRVAR (get_field_name_doc,"get_field_name() Get current field’s name.\n\ \n\ get_field_name() allows access to the current field name of the\n\ current record in the current event.\n\ \n\ Returns None if the field value is unavailable.\n\ ")
PyDoc_STRVAR (get_field_str_doc,"get_field_str() get current field’s value\n\ \n\ get_field_str() allows access to the value in the current field of the\n\ current record in the current event.\n\ \n\ Returns None if the field value is unavailable.\n\ ")
PyDoc_STRVAR (get_field_type_doc,"get_field_type() Get current field’s data type value.\n\ \n\ get_field_type() returns a value from the auparse_type_t enum that\n\ describes the kind of data in the current field of the current record\n\ in the current event.\n\ \n\ Returns AUPARSE_TYPE_UNCLASSIFIED if the field’s data type has no\n\ known description or is an integer. Otherwise it returns another enum.\n\ Fields with the type AUPARSE_TYPE_ESCAPED must be interpretted to access\n\ their value since those field’s raw value is encoded.\n\ ")
PyDoc_STRVAR (get_field_int_doc,"get_field_int() Get current field’s value as an integer.\n\ \n\ get_field_int() allows access to the value as an int of the current\n\ field of the current record in the current event.\n\ \n\ Returns None if the field value is unavailable.\n\ ")
PyDoc_STRVAR (interpret_field_doc,"interpret_field() Return an interpretation of the current field as a string that has the chosen character escaping applied.\n\ \n\ If the field cannot be interpreted the field is returned unmodified.\n\ Returns None if the field value is unavailable.\n\ ")
PyDoc_STRVAR (AuParser_doc,"AuParser(source_type, source)\n\ \n\ Construct a new audit parser object and bind it to input data.\n\ source_type: one of the AUSOURCE_* constants.\n\ source: the input data, dependent on the source_type as follows:\n\ \n\ AUSOURCE_LOGS: None (system log files will be parsed)\n\ AUSOURCE_FILE: string containing file path name\n\ AUSOURCE_FILE_ARRAY: list or tuple of strings each containing a file path name\n\ AUSOURCE_BUFFER: string containing audit data to parse\n\ AUSOURCE_BUFFER_ARRAY: list or tuple of strings each containing audit data to parse\n\ AUSOURCE_DESCRIPTOR: integer file descriptor (e.g. fileno)\n\ AUSOURCE_FILE_POINTER: file object (e.g. types.FileType)\n\ AUSOURCE_FEED: None (data supplied via feed()\n\ ")
PyDoc_STRVAR (auparse_doc,"Parsing library for audit messages.\n\ \n\ The module defines the following exceptions:\n\ \n\ NoParser: Raised if the underlying C code parser is not bound to the AuParser object.\n\ ")
Variables
PyMODINIT_FUNC
Macro Definition Documentation
#define MODINITERROR return
Definition at line 41 of file auparse_python.c.
#define PARSER_CHECK
Value:
if (self->au == NULL) {                                                        \
        PyErr_SetString(NoParserError, "object has no parser associated with it"); \
        return NULL;                                                               \
    }
Definition at line 238 of file auparse_python.c.
#define PYFILE_ASFILE (f) PyFile_AsFile(f)
Definition at line 46 of file auparse_python.c.
#define PYNUM_FROMLONG PyInt_FromLong
Definition at line 42 of file auparse_python.c.
#define PYSTR_ASSTRING PyString_AsString
Definition at line 45 of file auparse_python.c.
#define PYSTR_CHECK PyString_Check
Definition at line 43 of file auparse_python.c.
#define PYSTR_FROMSTRING PyString_FromString
Definition at line 44 of file auparse_python.c.
Function Documentation
const char* auparse_find_field_next (auparse_state_t * au)
Definition at line 1295 of file auparse.c.
References aup_list_first_field(), aup_list_next(), event_list_t::e, opaque::find_field, opaque::le, _rnode::nv, nvlist_find_name(), nvlist_next(), and au_event_t::sec.
Referenced by auparse_find_field(), and main().
void callback_data_destroy (void * user_data)
Definition at line 255 of file auparse_python.c.
References CallbackData::func, and CallbackData::user_data.
PyDoc_STRVAR (AuEvent_doc , "An internal object which encapsulates the timestamp, serial number\n\and host information of an audit event.The object cannot be\n\instantiated from python code, rather it is returned from the\n\audit parsing API.")
PyDoc_STRVAR (feed_doc , "feed(data) supplies new data for the parser to consume.\n\\n\AuParser() must have been called with a source type of AUSOURCE_FEED.\n\The parser consumes as much data as it can invoking a user supplied\n\callback specified with add_callback() with a cb_event_type of\n\AUPARSE_CB_EVENT_READY each time the parser recognizes a complete event\n\in the data stream. Data not fully parsed will persist and be prepended\n\to the next feed data. After all data has been feed to the parser flush_feed()\n\should be called to signal the end of input data and flush any pending\n\parse data through the parsing system.\n\\n\Returns None.\n\Raises exception (EnvironmentError) on error\n\")
PyDoc_STRVAR (flush_feed_doc , "flush_feed() flush any unconsumed feed data through parser\n\\n\flush_feed() should be called to signal the end of feed input data\n\and flush any pending parse data through the parsing system.\n\\n\Returns None.\n\Raises exception (EnvironmentError) on error\n\")
PyDoc_STRVAR (add_callback_doc , "add_callback(callback, user_data) add a callback handler for notifications.\n\\n\auparse_add_callback adds a callback function to the parse state which\n\is invoked to notify the application of parsing events.\n\\n\The signature of the callback is:\n\\n\callback(au, cb_event_type,user_data)\n\\n\When the callback is invoked it is passed:\n\au: the AuParser object\n\cb_event_type: enumerated value indicating the reason why the callback was invoked\n\user_data: user supplied private data\n\\n\The cb_event_type argument indicates why the callback was invoked.\n\It's possible values are:\n\\n\AUPARSE_CB_EVENT_READY\n\A complete event has been parsed and is ready to be examined.\n\This is logically equivalent to the parse state immediately following\n\auparse_next_event()\n\\n\Returns None.\n\Raises exception (EnvironmentError) on error\n\")
PyDoc_STRVAR (set_escape_mode_doc , "set_escape_mode() Set audit parser escaping\n\\n\This function sets the character escaping applied to value fields in the audit record.\n\Returns None.\n\")
PyDoc_STRVAR (reset_doc , "reset() Reset audit parser instance\n\\n\reset resets all internal cursors to the beginning.\n\It closes files and descriptors.\n\\n\Returns None.\n\Raises exception (EnvironmentError) on error\n\")
PyDoc_STRVAR (search_add_expression_doc , "search_add_expression(expression, how) Build up search expression\n\\n\\n\ausearch_add_item adds an expression to the current audit search\n\expression. The search conditions can then be used to scan logs, \n\ files, or buffers for something of interest.The expression parameter\n\contains an expression, as specified in ausearch-expression(5).\n\\n\The how parameter determines how this search expression will affect the\n\existing search expression, if one is already defined.The possible\n\values are:\n\\n\AUSEARCH_RULE_CLEAR:\n\Clear the current search expression, if any, and use only this search\n\expression.\n\\n\AUSEARCH_RULE_OR:\n\\n\If a search expression E is already configured, replace it by\n\(E||this_search_expression).\n\\n\AUSEARCH_RULE_AND:\n\If a search expression E is already configured, replace it by\n\(E &&this_search_expression).\n\\n\No Return value, raises exception(EnvironmentError) on error.\n\")
PyDoc_STRVAR (search_add_item_doc , "search_add_item(field, op, value, how) Build up search rule\n\\n\\n\search_add_item() adds one search condition to the current audit search\n\expression. The search conditions can then be used to scan logs, files , or\n\buffers for something of interest.The field value is the field name\n\that the value will be checked for.The op variable describes what\n\kind of check is to be done.Legal op values are:\n\\n\'exists':\n\Just check that a field name exists\n\\n\' = ':\n\locate the field name and check that the value associated with it\n\is equal to the value given in this rule.\n\\n\'!=':\n\locate the field name and check that the value associated with\n\it is NOT equal to the value given in this rule.\n\\n\The value parameter is compared to the uninterpreted field value.\n\\n\The how parameter determines how this search expression will affect the\n\existing search expression, if one is already defined.The possible\n\values are:\n\\n\AUSEARCH_RULE_CLEAR:\n\Clear the current search expression, if any, and use only this search\n\expression.\n\\n\AUSEARCH_RULE_OR:\n\\n\If a search expression E is already configured, replace it by\n\(E||this_search_expression).\n\\n\AUSEARCH_RULE_AND:\n\If a search expression E is already configured, replace it by\n\(E &&this_search_expression).\n\\n\No Return value, raises exception(EnvironmentError) on error.\n\")
PyDoc_STRVAR (search_add_interpreted_item_doc , "search_add_interpreted_item(field, op, value, how) Build up search rule\n\\n\\n\search_add_interpreted_item() adds one search condition to the current audit\n\search expression. The search conditions can then be used to scan logs, \n\ files, or buffers for something of interest.The field value is the field\n\name that the value will be checked for.The op variable describes what\n\kind of check is to be done.Legal op values are:\n\\n\'exists':\n\Just check that a field name exists\n\\n\' = ':\n\locate the field name and check that the value associated with it\n\is equal to the value given in this rule.\n\\n\'!=':\n\locate the field name and check that the value associated with\n\it is NOT equal to the value given in this rule.\n\\n\The value parameter is compared to the interpreted field value (the value\n\that would be returned by AuParser.interpret_field).\n\\n\The how parameter determines how this search expression will affect the\n\existing search expression, if one is already defined.The possible\n\values are:\n\\n\AUSEARCH_RULE_CLEAR:\n\Clear the current search expression, if any, and use only this search\n\expression.\n\\n\AUSEARCH_RULE_OR:\n\\n\If a search expression E is already configured, replace it by\n\(E||this_search_expression).\n\\n\AUSEARCH_RULE_AND:\n\If a search expression E is already configured, replace it by\n\(E &&this_search_expression).\n\\n\No Return value, raises exception(EnvironmentError) on error.\n\")
PyDoc_STRVAR (search_add_timestamp_item_doc , "search_add_timestamp_item(op, sec, milli, how) Build up search rule\n\\n\\n\search_add_timestamp_item adds an event time condition to the current audit\n\search expression. The search conditions can then be used to scan logs, \n\ files, or buffers for something of interest.The op parameter specifies the\n\desired comparison.Legal op values are\"<\", \"<=\", \">=\", \">\" and\n\\" = \". The left operand of the comparison operator is the timestamp of the\n\examined event, the right operand is specified by the sec and milli\n\parameters.\n\\n\The how parameter determines how this search expression will affect the\n\existing search expression, if one is already defined. The possible\n\values are:\n\\n\AUSEARCH_RULE_CLEAR:\n\Clear the current search expression, if any, and use only this search\n\expression.\n\\n\AUSEARCH_RULE_OR:\n\\n\If a search expression E is already configured, replace it by\n\(E || this_search_expression).\n\\n\AUSEARCH_RULE_AND:\n\If a search expression E is already configured, replace it by\n\(E && this_search_expression).\n\\n\No Return value, raises exception (EnvironmentError) on error.\n\")
PyDoc_STRVAR (search_add_timestamp_item_ex_doc , "search_add_timestamp_item_ex(op, sec, milli, serial, how) Build up search rule\n\search_add_timestamp_item_ex adds an event time condition to the current audit\n\search expression. Its similar to search_add_timestamp_item except it adds\n\the event serial number.\n\")
PyDoc_STRVAR (search_add_regex_doc , "search_add_regex(regexp) Add a regular expression to the search criteria.\n\\n\No Return value, raises exception(EnvironmentError) on error.\n\")
PyDoc_STRVAR (search_set_stop_doc , "search_set_stop(where) Set where cursor is positioned on search match.\n\\n\search_set_stop() determines where the internal cursor will stop when\n\a search condition is met. The possible values are:\n\\n\AUSEARCH_STOP_EVENT:\n\This one repositions the cursors to the first field of the first\n\record of the event con- taining the items searched for.\n\\n\AUSEARCH_STOP_RECORD:\n\This one repositions the cursors to the first field of the record\n\containing the items searched for.\n\\n\AUSEARCH_STOP_FIELD:\n\This one simply stops on the current field when the evaluation of the\n\rules becomes true.\n\\n\No Return value, raises exception(ValueError) on error.\n\")
PyDoc_STRVAR (search_clear_doc , "search_clear() Clear search parameters.\n\\n\ausearch_clear clears any search parameters stored in the parser\n\instance and frees memory associated with it.\n\\n\No Return value.\n\")
PyDoc_STRVAR (search_next_event_doc , "search_next_event() Find the next event that meets search criteria.\n\\n\search_next_event() will scan the input source and evaluate whether\n\any record in an event contains the data being searched\n\for. Evaluation is done at the record level.\n\\n\Returns True if a match was found\n\Returns False if a match was not found.\n\\n\Raises exception (EnvironmentError) on error\n\")
PyDoc_STRVAR (parse_next_event_doc , "parse_next_event() Advance the parser to the next event.\n\\n\parse_next_event() will position the cursors at the first field of the first\n\record of the next event in a file or buffer. It does not skip events\n\or honor any search criteria that may be stored.\n\\n\Returns True if parser advances to next event.\n\Returns False if there are no more events to parse\n\\n\Raises exception (EnvironmentError) on error\n\")
PyDoc_STRVAR (get_timestamp_doc , "get_timestamp() Return current event's timestamp.\n\\n\Returns the current event's timestamp info as an AuEvent object.\n\No Return value, raises exception(EnvironmentError) on error.\n\")
PyDoc_STRVAR (get_num_records_doc , "get_num_records() Get the number of records.\n\\n\Returns the number of records in the current event.\n\Raises exception (EnvironmentError) on error.\n\")
PyDoc_STRVAR (first_record_doc , "first_record() Reposition record cursor.\n\\n\first_record() repositions the internal cursors of the parsing library\n\to point to the first record in the current event.\n\\n\Return True for success, False if there is no event data.\n\Raises exception(EnvironmentError) on error.\n\")
PyDoc_STRVAR (next_record_doc , "next_record() Advance record cursor.\n\\n\next_record() will move the internal library cursors to point to the\n\next record of the current event.\n\\n\Returns True on success, False if no more records in current event\n\Raises exception(EnvironmentError) on error.\n\")
PyDoc_STRVAR (goto_record_num_doc , "goto_record_num() Move record cursor to specific position.\n\\n\goto_record_num() will move the internal library cursors to point\n\to a specific physical record number. Records within the same event are\n\numbered starting from 0. This is generally not needed but there are\n\some cases where one may want precise control over the exact record\n\being looked at.\n\\n\Returns True on success, False if no more records in current event\n\Raises exception(EnvironmentError) on error.\n\")
PyDoc_STRVAR (get_type_doc , "get_type() Get record’s type.\n\\n\get_type() will return the integer value for the current record of the\n\current event.\n\\n\Returns record type.\n\Raises exception (LookupError) on error.\n\")
PyDoc_STRVAR (get_type_name_doc , "get_type_name() Get current record’s type name.\n\\n\get_type_name() allows access to the current record type name in the\n\current event.\n\\n\Returns None if the record type name is unavailable.\n\")
PyDoc_STRVAR (get_line_number_doc , "auparse_get_line_number() get line number where record was found\n\\n\get_line_number will return the source input line number for\n\the current record of the current event. Line numbers start at 1. If\n\the source input type is AUSOURCE_FILE_ARRAY the line numbering will\n\reset back to 1 each time a new life in the file array is opened.\n\")
PyDoc_STRVAR (get_filename_doc , "auparse_get_filename() get the filename where record was found\n\get_filename() will return the name of the source file where the\n\record was found if the source type is AUSOURCE_FILE or\n\AUSOURCE_FILE_ARRAY. For other source types the return value will be\n\None.\n\")
PyDoc_STRVAR (first_field_doc , "first_field() Reposition field cursor.\n\\n\Returns True on success, False if there is no event data\n\")
PyDoc_STRVAR (next_field_doc , "next_field() Advance the field cursor.\n\\n\next_field() moves the library’s internal cursor to point to the next\n\field in the current record of the current event.\n\\n\Returns True on success, False if there is no more fields exist\n\")
PyDoc_STRVAR (get_num_fields_doc , "get_num_fields() Get the number of fields.\n\\n\Returns the number of fields in the current event.\n\Raises exception (EnvironmentError) on error.\n\")
PyDoc_STRVAR (get_record_text_doc , "get_record_text() Return unparsed record data\n\\n\get_record_text() returns the full unparsed record.\n\Raises exception (EnvironmentError) on error.\n\")
PyDoc_STRVAR (find_field_doc , "find_field(name) Search for field name.\n\\n\find_field() will scan all records in an event to find the first\n\occurance of the field name passed to it. Searching begins from the\n\cursor’s current position. The field name is stored for subsequent\n\searching.\n\\n\Returns value associated with field or None if not found.\n\")
PyDoc_STRVAR (find_field_next_doc , "find_field_next() Get next occurrance of field name\n\\n\find_field_next() returns the value associated next occurrance of field name.\n\Returns value associated with field or None if there is no next field.\n\Raises exception (EnvironmentError) on error.\n\")
PyDoc_STRVAR (get_field_name_doc , "get_field_name() Get current field’s name.\n\\n\get_field_name() allows access to the current field name of the\n\current record in the current event.\n\\n\Returns None if the field value is unavailable.\n\")
PyDoc_STRVAR (get_field_str_doc , "get_field_str() get current field’s value\n\\n\get_field_str() allows access to the value in the current field of the\n\current record in the current event.\n\\n\Returns None if the field value is unavailable.\n\")
PyDoc_STRVAR (get_field_type_doc , "get_field_type() Get current field’s data type value.\n\\n\get_field_type() returns a value from the auparse_type_t enum that\n\describes the kind of data in the current field of the current record\n\in the current event.\n\\n\Returns AUPARSE_TYPE_UNCLASSIFIED if the field’s data type has no\n\known description or is an integer. Otherwise it returns another enum.\n\Fields with the type AUPARSE_TYPE_ESCAPED must be interpretted to access\n\their value since those field’s raw value is encoded.\n\")
PyDoc_STRVAR (get_field_int_doc , "get_field_int() Get current field’s value as an integer.\n\\n\get_field_int() allows access to the value as an int of the current\n\field of the current record in the current event.\n\\n\Returns None if the field value is unavailable.\n\")
PyDoc_STRVAR (interpret_field_doc , "interpret_field() Return an interpretation of the current field as a string that has the chosen character escaping applied.\n\\n\If the field cannot be interpreted the field is returned unmodified.\n\Returns None if the field value is unavailable.\n\")
PyDoc_STRVAR (AuParser_doc , "AuParser(source_type, source)\n\\n\Construct a new audit parser object and bind it to input data.\n\source_type: one of the AUSOURCE_* constants.\n\source: the input data)
PyDoc_STRVAR (auparse_doc , "Parsing library for audit messages.\n\\n\The module defines the following exceptions:\n\\n\NoParser: Raised if the underlying C code parser is not bound to the AuParser object.\n\")
Variable Documentation
PyMODINIT_FUNC
Initial value:
{
    PyObject* m
Definition at line 1671 of file auparse_python.c.