audit: auparse/auparse-idata.h File Reference
auparse-idata.h File Reference
#include "config.h"
#include "dso.h"
#include "auparse-defs.h"
Data Structures
struct _idata
Typedefs
typedef struct _idata idata
Functions
int auparse_interp_adjust_type (int rtype, const char *name, const char *val)
const char * auparse_do_interpretation (int type, const idata *id)
int set_escape_mode (auparse_esc_t mode)
Typedef Documentation
typedef struct _idata idata
Function Documentation
const char* auparse_do_interpretation (int type, const idata * id)
Definition at line 2530 of file interpret.c.
References AUPARSE_ESC_RAW, AUPARSE_TYPE_A0, AUPARSE_TYPE_A1, AUPARSE_TYPE_A2, AUPARSE_TYPE_A3, AUPARSE_TYPE_ADDR, AUPARSE_TYPE_ARCH, AUPARSE_TYPE_CAP_BITMAP, AUPARSE_TYPE_CAPABILITY, AUPARSE_TYPE_ESCAPED, AUPARSE_TYPE_EXIT, AUPARSE_TYPE_FLAGS, AUPARSE_TYPE_GID, AUPARSE_TYPE_ICMPTYPE, AUPARSE_TYPE_LIST, AUPARSE_TYPE_MAC_LABEL, AUPARSE_TYPE_MMAP, AUPARSE_TYPE_MODE, AUPARSE_TYPE_MODE_SHORT, AUPARSE_TYPE_NFPROTO, AUPARSE_TYPE_OFLAG, AUPARSE_TYPE_PERM, AUPARSE_TYPE_PERSONALITY, AUPARSE_TYPE_PROCTITLE, AUPARSE_TYPE_PROMISC, AUPARSE_TYPE_PROTOCOL, AUPARSE_TYPE_SECCOMP, AUPARSE_TYPE_SESSION, AUPARSE_TYPE_SIGNAL, AUPARSE_TYPE_SOCKADDR, AUPARSE_TYPE_SUCCESS, AUPARSE_TYPE_SYSCALL, AUPARSE_TYPE_TTY_DATA, AUPARSE_TYPE_UID, AUPARSE_TYPE_UNCLASSIFIED, and print_list().
Referenced by interpret().
int auparse_interp_adjust_type (int rtype, const char * name, const char * val)
Definition at line 2490 of file interpret.c.
References AUDIT_ADD_GROUP, AUDIT_CRYPTO_KEY_USER, AUDIT_DEL_GROUP, AUDIT_GRP_MGMT, AUDIT_NETFILTER_PKT, AUDIT_USER_TTY, AUPARSE_TYPE_ADDR, AUPARSE_TYPE_ESCAPED, AUPARSE_TYPE_FLAGS, AUPARSE_TYPE_GID, AUPARSE_TYPE_MODE_SHORT, AUPARSE_TYPE_UNCLASSIFIED, lookup_type(), and auparse_test::type.
Referenced by interpret(), and nvlist_get_cur_type().
int set_escape_mode (auparse_esc_t mode)
Definition at line 264 of file interpret.c.
References AUPARSE_ESC_SHELL_QUOTE.
Referenced by auparse_set_escape_mode().