audit: src/aureport-scan.h File Reference
aureport-scan.h File Reference
#include "ausearch-llist.h"
#include "ausearch-int.h"
Data Structures
struct sdata
Typedefs
typedef struct sdata summary_data
Functions
void reset_counters (void)
void destroy_counters (void)
int scan (llist *l)
int per_event_processing (llist *l)
void print_title (void)
void print_per_event_item (llist *l)
void print_wrap_up (void)
Variables
summary_data sd
Typedef Documentation
typedef struct sdata summary_data
Function Documentation
void destroy_counters (void)
Definition at line 78 of file aureport-scan.c.
References sdata::acct_changes, sdata::anom_list, sdata::anomalies, sdata::avc_objs, sdata::avcs, sdata::bad_auth, sdata::bad_logins, sdata::changes, sdata::comms, sdata::crypto, sdata::crypto_list, sdata::events, sdata::exes, sdata::failed_syscalls, sdata::files, sdata::good_auth, sdata::good_logins, sdata::hosts, ilist_clear(), ilist_create(), sdata::integ, sdata::integ_list, sdata::keys, sdata::mac, sdata::mac_list, sdata::pids, sdata::resp_list, sdata::responses, slist_clear(), sdata::sys_list, sdata::terms, sdata::users, sdata::virt, and sdata::virt_list.
Referenced by main().
int per_event_processing (llist * l)
Definition at line 245 of file aureport-scan.c.
References D_DETAILED, D_SPECIFIC, D_SUM, and report_detail.
void print_per_event_item (llist * l)
Definition at line 484 of file aureport-output.c.
References search_items::acct, alist_find_avc(), alist_next_avc(), audit_msg_type_to_name(), aulookup_result(), aulookup_success(), aulookup_syscall(), aulookup_uid(), search_items::avc, _anode::avc_class, _anode::avc_perm, _anode::avc_result, search_items::comm, slist::cur, alist::cur, llist::e, search_items::exe, search_items::filename, llist::head, search_items::hostname, search_items::key, line_item, search_items::loginuid, _lnode::message, auparse_test::name, search_items::pid, print_tty_data(), report_type, RPT_ACCT_MOD, RPT_ANOMALY, RPT_AUTH, RPT_AVC, RPT_COMM, RPT_CONFIG, RPT_CRYPTO, RPT_EVENT, RPT_EXE, RPT_FILE, RPT_HOST, RPT_INTEG, RPT_KEY, RPT_LOGIN, RPT_MAC, RPT_PID, RPT_RESPONSE, RPT_SYSCALL, RPT_TERM, RPT_TTY, RPT_USER, RPT_VIRT, llist::s, S_FAILED, safe_print_string(), _anode::scontext, event::sec, event::serial, search_items::session_id, _snode::str, search_items::success, _anode::tcontext, search_items::terminal, _lnode::type, and search_items::uid.
void print_title (void)
Definition at line 47 of file aureport-output.c.
References D_DETAILED, D_SPECIFIC, D_SUM, line_item, and report_detail.
Referenced by main().
void print_wrap_up (void)
Definition at line 741 of file aureport-output.c.
References sdata::anom_list, sdata::avc_objs, sdata::comms, sdata::crypto_list, D_SUM, sdata::exes, sdata::files, sdata::hosts, ilist_sort_by_hits(), sdata::integ_list, sdata::keys, sdata::mac_list, sdata::pids, report_detail, report_type, sdata::resp_list, RPT_ACCT_MOD, RPT_ANOMALY, RPT_AUTH, RPT_AVC, RPT_COMM, RPT_CONFIG, RPT_CRYPTO, RPT_EVENT, RPT_EXE, RPT_FILE, RPT_HOST, RPT_INTEG, RPT_KEY, RPT_LOGIN, RPT_MAC, RPT_PID, RPT_RESPONSE, RPT_SUMMARY, RPT_SYSCALL, RPT_TERM, RPT_USER, RPT_VIRT, sd, slist_sort_by_hits(), sdata::sys_list, sdata::terms, sdata::users, and sdata::virt_list.
Referenced by main().
void reset_counters (void)
Definition at line 42 of file aureport-scan.c.
References sdata::acct_changes, sdata::anom_list, sdata::anomalies, sdata::avc_objs, sdata::avcs, sdata::bad_auth, sdata::bad_logins, sdata::changes, sdata::comms, sdata::crypto, sdata::crypto_list, sdata::events, sdata::exes, sdata::failed_syscalls, sdata::files, sdata::good_auth, sdata::good_logins, sdata::hosts, ilist_create(), sdata::integ, sdata::integ_list, sdata::keys, sdata::mac, sdata::mac_list, sdata::pids, sdata::resp_list, sdata::responses, slist_create(), sdata::sys_list, sdata::terms, sdata::users, sdata::virt, and sdata::virt_list.
Referenced by main().
int scan (llist * l)
Definition at line 208 of file aureport-scan.c.
References classify_conf(), classify_success(), llist::e, end_time, event_node_list, extract_search_items(), event::node, event::sec, slist_next(), start_time, and _snode::str.
Variable Documentation
summary_data sd
Definition at line 39 of file aureport-scan.c.
Referenced by print_wrap_up().