audit: src/aureport-scan.c File Reference
aureport-scan.c File Reference
#include "config.h"
#include <string.h>
#include <stdio.h>
#include <pwd.h>
#include "libaudit.h"
#include "aureport-options.h"
#include "ausearch-parse.h"
#include "ausearch-string.h"
#include "ausearch-lookup.h"
#include "aureport-scan.h"
Functions
void reset_counters (void)
void destroy_counters (void)
int classify_success (const llist *l)
int classify_conf (const llist *l)
int scan (llist *l)
int per_event_processing (llist *l)
Variables
summary_data sd
Function Documentation
int classify_conf (const llist * l)
Definition at line 128 of file aureport-scan.c.
References AUDIT_ADD_GROUP, AUDIT_ADD_USER, AUDIT_DEL_GROUP, AUDIT_DEL_USER, AUDIT_USYS_CONFIG, C_ADD, C_DEL, event_conf_act, llist::head, no_config, and _lnode::type.
Referenced by scan().
int classify_success (const llist * l)
Definition at line 114 of file aureport-scan.c.
References event_failed, F_FAILED, F_SUCCESS, llist::s, S_FAILED, S_SUCCESS, and search_items::success.
Referenced by scan().
void destroy_counters (void)
Definition at line 78 of file aureport-scan.c.
References sdata::acct_changes, sdata::anom_list, sdata::anomalies, sdata::avc_objs, sdata::avcs, sdata::bad_auth, sdata::bad_logins, sdata::changes, sdata::comms, sdata::crypto, sdata::crypto_list, sdata::events, sdata::exes, sdata::failed_syscalls, sdata::files, sdata::good_auth, sdata::good_logins, sdata::hosts, ilist_clear(), ilist_create(), sdata::integ, sdata::integ_list, sdata::keys, sdata::mac, sdata::mac_list, sdata::pids, sdata::resp_list, sdata::responses, slist_clear(), sdata::sys_list, sdata::terms, sdata::users, sdata::virt, and sdata::virt_list.
Referenced by main().
int per_event_processing (llist * l)
Definition at line 245 of file aureport-scan.c.
References D_DETAILED, D_SPECIFIC, D_SUM, and report_detail.
void reset_counters (void)
Definition at line 42 of file aureport-scan.c.
References sdata::acct_changes, sdata::anom_list, sdata::anomalies, sdata::avc_objs, sdata::avcs, sdata::bad_auth, sdata::bad_logins, sdata::changes, sdata::comms, sdata::crypto, sdata::crypto_list, sdata::events, sdata::exes, sdata::failed_syscalls, sdata::files, sdata::good_auth, sdata::good_logins, sdata::hosts, ilist_create(), sdata::integ, sdata::integ_list, sdata::keys, sdata::mac, sdata::mac_list, sdata::pids, sdata::resp_list, sdata::responses, slist_create(), sdata::sys_list, sdata::terms, sdata::users, sdata::virt, and sdata::virt_list.
Referenced by main().
int scan (llist * l)
Definition at line 208 of file aureport-scan.c.
References classify_conf(), classify_success(), llist::e, end_time, event_node_list, extract_search_items(), event::node, event::sec, slist_next(), start_time, and _snode::str.
Variable Documentation
summary_data sd
Definition at line 39 of file aureport-scan.c.
Referenced by print_wrap_up().