audit: src/aureport-output.c File Reference
aureport-output.c File Reference
#include "config.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "aureport-scan.h"
#include "aureport-options.h"
#include "ausearch-lookup.h"
Functions
void print_title (void)
void print_per_event_item (llist *l)
void print_wrap_up (void)
Variables
unsigned int line_item
Function Documentation
void print_per_event_item (llist * l)
Definition at line 484 of file aureport-output.c.
References search_items::acct, alist_find_avc(), alist_next_avc(), audit_msg_type_to_name(), aulookup_result(), aulookup_success(), aulookup_syscall(), aulookup_uid(), search_items::avc, _anode::avc_class, _anode::avc_perm, _anode::avc_result, search_items::comm, slist::cur, alist::cur, llist::e, search_items::exe, search_items::filename, llist::head, search_items::hostname, search_items::key, line_item, search_items::loginuid, _lnode::message, auparse_test::name, search_items::pid, print_tty_data(), report_type, RPT_ACCT_MOD, RPT_ANOMALY, RPT_AUTH, RPT_AVC, RPT_COMM, RPT_CONFIG, RPT_CRYPTO, RPT_EVENT, RPT_EXE, RPT_FILE, RPT_HOST, RPT_INTEG, RPT_KEY, RPT_LOGIN, RPT_MAC, RPT_PID, RPT_RESPONSE, RPT_SYSCALL, RPT_TERM, RPT_TTY, RPT_USER, RPT_VIRT, llist::s, S_FAILED, safe_print_string(), _anode::scontext, event::sec, event::serial, search_items::session_id, _snode::str, search_items::success, _anode::tcontext, search_items::terminal, _lnode::type, and search_items::uid.
void print_title (void)
Definition at line 47 of file aureport-output.c.
References D_DETAILED, D_SPECIFIC, D_SUM, line_item, and report_detail.
Referenced by main().
void print_wrap_up (void)
Definition at line 741 of file aureport-output.c.
References sdata::anom_list, sdata::avc_objs, sdata::comms, sdata::crypto_list, D_SUM, sdata::exes, sdata::files, sdata::hosts, ilist_sort_by_hits(), sdata::integ_list, sdata::keys, sdata::mac_list, sdata::pids, report_detail, report_type, sdata::resp_list, RPT_ACCT_MOD, RPT_ANOMALY, RPT_AUTH, RPT_AVC, RPT_COMM, RPT_CONFIG, RPT_CRYPTO, RPT_EVENT, RPT_EXE, RPT_FILE, RPT_HOST, RPT_INTEG, RPT_KEY, RPT_LOGIN, RPT_MAC, RPT_PID, RPT_RESPONSE, RPT_SUMMARY, RPT_SYSCALL, RPT_TERM, RPT_USER, RPT_VIRT, sd, slist_sort_by_hits(), sdata::sys_list, sdata::terms, sdata::users, and sdata::virt_list.
Referenced by main().
Variable Documentation
unsigned int line_item
Definition at line 44 of file aureport-output.c.
Referenced by print_per_event_item(), and print_title().