audit: src/aureport.c File Reference
aureport.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdio_ext.h>
#include <string.h>
#include <stdlib.h>
#include <getopt.h>
#include <unistd.h>
#include <ctype.h>
#include <time.h>
#include <errno.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <locale.h>
#include <sys/param.h>
#include "libaudit.h"
#include "auditd-config.h"
#include "aureport-options.h"
#include "aureport-scan.h"
#include "ausearch-lol.h"
#include "ausearch-lookup.h"
Functions
int main (int argc, char *argv[])
Variables
event very_first_event
event very_last_event
char * user_file
int force_logs
Function Documentation
int main (int argc, char * argv[])
Definition at line 73 of file aureport.c.
References aulookup_destroy_gid_list(), aulookup_destroy_uid_list(), check_params(), D_DETAILED, DBG_NO, destroy_counters(), force_logs, lol_clear(), lol_create(), MSG_STDERR, print_title(), print_wrap_up(), report_detail, report_type, reset_counters(), RPT_TIME, event::sec, set_aumessage_mode, user_file, and very_first_event.
Variable Documentation
int force_logs
Definition at line 41 of file aureport-options.c.
char* user_file
Definition at line 40 of file aureport-options.c.
event very_first_event
Definition at line 46 of file aureport.c.
Referenced by main().
event very_last_event
Definition at line 46 of file aureport.c.