audit: src/ausearch-time.c File Reference
ausearch-time.c File Reference
#include "config.h"
#include <stdio.h>
#include <string.h>
#include "ausearch-time.h"
Data Structures
struct nv_pair
Macros
#define SECONDS_IN_DAY 24*60*60
#define TIME_NAMES (sizeof(timetab)/sizeof(timetab[0]))
Functions
int lookup_time (const char *name)
int ausearch_time_start (const char *da, const char *ti)
int ausearch_time_end (const char *da, const char *ti)
Variables
time_t start_time = 0
time_t end_time = 0
Macro Definition Documentation
#define SECONDS_IN_DAY 24*60*60
Definition at line 29 of file ausearch-time.c.
#define TIME_NAMES (sizeof(timetab)/sizeof(timetab[0]))
Definition at line 52 of file ausearch-time.c.
Referenced by lookup_time().
Function Documentation
int ausearch_time_end (const char * da, const char * ti)
Definition at line 329 of file ausearch-time.c.
References end_time, lookup_time(), T_NOW, T_RECENT, and T_TODAY.
Referenced by check_params(), and parse_args().
int ausearch_time_start (const char * da, const char * ti)
Definition at line 258 of file ausearch-time.c.
References lookup_time(), start_time, T_NOW, and T_RECENT.
Referenced by check_params(), and parse_args().
int lookup_time (const char * name)
Definition at line 54 of file ausearch-time.c.
References TIME_NAMES, and nv_pair::value.
Referenced by ausearch_time_end(), ausearch_time_start(), and check_params().
Variable Documentation
time_t end_time = 0
Definition at line 35 of file ausearch-time.c.
Referenced by ausearch_time_end(), create_search_criteria(), match(), parse_args(), print_summary(), and scan().
time_t start_time = 0
Definition at line 35 of file ausearch-time.c.
Referenced by ausearch_time_start(), create_search_criteria(), match(), parse_args(), print_summary(), and scan().