audit: src/ausearch-int.h File Reference
ausearch-int.h File Reference
#include "config.h"
Data Structures
struct _int_node
struct ilist
Typedefs
typedef struct _int_node int_node
Functions
void ilist_create (ilist *l)
int_node * ilist_next (ilist *l)
void ilist_append (ilist *l, int num, unsigned int hits, int aux)
void ilist_clear (ilist *l)
int ilist_add_if_uniq (ilist *l, int num, int aux)
void ilist_sort_by_hits (ilist *l)
Typedef Documentation
typedef struct _int_node int_node
Function Documentation
int ilist_add_if_uniq (ilist * l, int num, int aux)
Definition at line 85 of file ausearch-int.c.
References ilist::cur, ilist::head, _int_node::hits, ilist_append(), _int_node::next, and _int_node::num.
void ilist_append (ilist * l, int num, unsigned int hits, int aux)
Definition at line 44 of file ausearch-int.c.
References _int_node::aux1, ilist::cnt, ilist::cur, ilist::head, _int_node::hits, _int_node::next, and _int_node::num.
void ilist_clear (ilist * l)
Definition at line 79 of file audisp-int.c.
References ilist::cnt, ilist::cur, ilist::head, and _int_node::next.
Referenced by destroy_counters(), free_config(), and main().
void ilist_create (ilist * l)
Definition at line 29 of file audisp-int.c.
References ilist::cnt, ilist::cur, and ilist::head.
Referenced by clear_config(), destroy_counters(), main(), and reset_counters().
int_node* ilist_next (ilist * l)
Definition at line 36 of file audisp-int.c.
References ilist::cur, and _int_node::next.
Referenced by main(), and match().
void ilist_sort_by_hits (ilist * l)
Definition at line 134 of file ausearch-int.c.
References ilist::cnt, ilist::cur, ilist::head, _int_node::hits, and _int_node::next.
Referenced by main(), and print_wrap_up().