audit: src/ausearch-checkpt.c File Reference
ausearch-checkpt.c File Reference
#include <stdlib.h>
#include <errno.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include "ausearch-checkpt.h"
Macros
#define DBG 0 /* set to non-zero for debug */
#define MAX_LN 1023
Functions
int set_ChkPtFileDetails (const char *fn)
int set_ChkPtLastEvent (const event *e)
void free_ChkPtMemory (void)
void save_ChkPt (const char *fn)
int load_ChkPt (const char *fn)
Variables
unsigned checkpt_failure = 0
dev_t chkpt_input_dev = (dev_t)NULL
ino_t chkpt_input_ino = (ino_t)NULL
event chkpt_input_levent = {0, 0, 0, NULL, 0}
Macro Definition Documentation
#define DBG 0 /* set to non-zero for debug */
Definition at line 26 of file ausearch-checkpt.c.
#define MAX_LN 1023
Referenced by load_ChkPt().
Function Documentation
void free_ChkPtMemory (void)
Definition at line 105 of file ausearch-checkpt.c.
References chkpt_input_levent, and event::node.
Referenced by main().
int load_ChkPt (const char * fn)
Definition at line 193 of file ausearch-checkpt.c.
References checkpt_failure, chkpt_input_dev, chkpt_input_ino, chkpt_input_levent, CP_STATUSBAD, MAX_LN, event::milli, event::node, event::sec, event::serial, and event::type.
Referenced by main().
void save_ChkPt (const char * fn)
Definition at line 121 of file ausearch-checkpt.c.
References checkpt_failure, CP_STATUSIO, event::milli, event::node, event::sec, event::serial, and event::type.
Referenced by main().
int set_ChkPtFileDetails (const char * fn)
Definition at line 53 of file ausearch-checkpt.c.
References checkpt_failure, and CP_STATFAILED.
int set_ChkPtLastEvent (const event * e)
Definition at line 75 of file ausearch-checkpt.c.
References event::milli, event::node, event::sec, event::serial, and event::type.
Variable Documentation
unsigned checkpt_failure = 0
Definition at line 29 of file ausearch-checkpt.c.
Referenced by load_ChkPt(), main(), save_ChkPt(), and set_ChkPtFileDetails().
dev_t chkpt_input_dev = (dev_t)NULL
Definition at line 42 of file ausearch-checkpt.c.
Referenced by load_ChkPt().
ino_t chkpt_input_ino = (ino_t)NULL
Definition at line 43 of file ausearch-checkpt.c.
Referenced by load_ChkPt().
event chkpt_input_levent = {0, 0, 0, NULL, 0}
Definition at line 44 of file ausearch-checkpt.c.
Referenced by free_ChkPtMemory(), and load_ChkPt().