audit: src/ausearch-string.h File Reference
ausearch-string.h File Reference
#include "config.h"
Data Structures
struct _snode
struct slist
Typedefs
typedef struct _snode snode
Functions
void slist_create (slist *l)
void slist_last (slist *l)
snode * slist_next (slist *l)
void slist_append (slist *l, snode *node)
void slist_clear (slist *l)
int slist_add_if_uniq (slist *l, const char *str)
void slist_sort_by_hits (slist *l)
Typedef Documentation
typedef struct _snode snode
Function Documentation
int slist_add_if_uniq (slist * l, const char * str)
Definition at line 115 of file ausearch-string.c.
References slist::cur, slist::head, _snode::hits, _snode::key, _snode::next, slist_append(), and _snode::str.
Referenced by main().
void slist_append (slist * l, snode * node)
Definition at line 63 of file ausearch-string.c.
References slist::cnt, slist::cur, slist::head, _snode::hits, _snode::key, _snode::next, slist_last(), and _snode::str.
Referenced by check_params(), main(), and slist_add_if_uniq().
void slist_clear (slist * l)
Definition at line 96 of file ausearch-string.c.
References slist::cnt, slist::cur, slist::head, _snode::key, _snode::next, and _snode::str.
Referenced by destroy_counters(), list_clear(), and main().
void slist_create (slist * l)
Definition at line 29 of file ausearch-string.c.
References slist::cnt, slist::cur, and slist::head.
Referenced by check_params(), main(), and reset_counters().
void slist_last (slist * l)
Definition at line 36 of file ausearch-string.c.
References slist::cur, slist::head, and _snode::next.
Referenced by slist_append().
snode* slist_next (slist * l)
Definition at line 55 of file ausearch-string.c.
References slist::cur, and _snode::next.
Referenced by main(), match(), print_list(), and scan().
void slist_sort_by_hits (slist * l)
Definition at line 149 of file ausearch-string.c.
References slist::cnt, slist::cur, slist::head, _snode::hits, and _snode::next.
Referenced by main(), and print_wrap_up().