audit: src/ausearch-lookup.h File Reference
ausearch-lookup.h File Reference
#include "config.h"
#include <pwd.h>
#include <grp.h>
#include "libaudit.h"
#include "ausearch-llist.h"
Functions
const char * aulookup_result (avc_t result)
const char * aulookup_success (int s)
const char * aulookup_syscall (llist *l, char *buf, size_t size)
const char * aulookup_uid (uid_t uid, char *buf, size_t size)
void aulookup_destroy_uid_list (void)
const char * aulookup_gid (gid_t gid, char *buf, size_t size)
void aulookup_destroy_gid_list (void)
char * unescape (const char *buf)
int is_hex_string (const char *str)
void print_tty_data (const char *val)
int need_sanitize (const unsigned char *s, unsigned int len)
void sanitize (const char *s, unsigned int len)
void safe_print_string_n (const char *s, unsigned int len, int ret)
void safe_print_string (const char *s, int ret)
Function Documentation
void aulookup_destroy_gid_list (void)
Definition at line 432 of file interpret.c.
References nvlist_clear(), and nvpair_clear().
Referenced by auparse_destroy(), and main().
void aulookup_destroy_uid_list (void)
Definition at line 383 of file interpret.c.
References nvlist_clear(), and nvpair_clear().
Referenced by auparse_destroy(), and main().
const char* aulookup_gid (gid_t gid, char * buf, size_t size)
Definition at line 237 of file ausearch-lookup.c.
References aulookup_gid(), nvlist::cur, auparse_test::gid, _nvnode::name, auparse_test::name, nvlist_append(), nvlist_clear(), nvlist_create(), nvlist_find_val(), report_format, RPT_DEFAULT, and _nvnode::val.
Referenced by aulookup_gid().
const char* aulookup_result (avc_t result)
Definition at line 49 of file ausearch-lookup.c.
Referenced by print_per_event_item().
const char* aulookup_success (int s)
Definition at line 54 of file ausearch-lookup.c.
References aulookup_success(), S_FAILED, and S_SUCCESS.
Referenced by aulookup_success(), and print_per_event_item().
const char* aulookup_syscall (llist * l, char * buf, size_t size)
Definition at line 70 of file ausearch-lookup.c.
References _lnode::a0, search_items::arch, audit_elf_to_machine(), audit_syscall_to_name(), llist::cur, list_find_item(), report_format, RPT_DEFAULT, llist::s, and search_items::syscall.
Referenced by print_per_event_item().
const char* aulookup_uid (uid_t uid, char * buf, size_t size)
Definition at line 184 of file ausearch-lookup.c.
References aulookup_uid(), nvlist::cur, _nvnode::name, auparse_test::name, nvlist_append(), nvlist_clear(), nvlist_create(), nvlist_find_val(), report_format, RPT_DEFAULT, auparse_test::uid, and _nvnode::val.
Referenced by aulookup_uid(), and print_per_event_item().
int is_hex_string (const char * str)
Definition at line 288 of file ausearch-lookup.c.
References is_hex_string().
Referenced by is_hex_string(), and print_tty_data().
int need_sanitize (const unsigned char * s, unsigned int len)
Definition at line 359 of file ausearch-lookup.c.
Referenced by safe_print_string_n().
void print_tty_data (const char * val)
Definition at line 453 of file ausearch-lookup.c.
References auparse_test::data, is_hex_string(), print_tty_data(), and unescape().
Referenced by print_per_event_item(), and print_tty_data().
void safe_print_string (const char * s, int ret)
Definition at line 397 of file ausearch-lookup.c.
References safe_print_string_n().
Referenced by print_per_event_item().
void safe_print_string_n (const char * s, unsigned int len, int ret)
Definition at line 385 of file ausearch-lookup.c.
References need_sanitize(), and sanitize().
Referenced by safe_print_string().
void sanitize (const char * s, unsigned int len)
Definition at line 370 of file ausearch-lookup.c.
Referenced by safe_print_string_n().
char* unescape (const char * buf)
Definition at line 320 of file ausearch-lookup.c.
Referenced by print_tty_data().