audit: src/ausearch-time.h File Reference
ausearch-time.h File Reference
#include <time.h>
Enumerations
enum {
T_NOW, T_RECENT, T_TODAY, T_YESTERDAY,
T_THIS_WEEK, T_WEEK_AGO, T_THIS_MONTH, T_THIS_YEAR
}
Functions
int lookup_time (const char *name)
int ausearch_time_start (const char *da, const char *ti)
int ausearch_time_end (const char *da, const char *ti)
Variables
time_t start_time
time_t end_time
Enumeration Type Documentation
anonymous enum
Enumerator
T_NOW
T_RECENT
T_TODAY
T_YESTERDAY
T_THIS_WEEK
T_WEEK_AGO
T_THIS_MONTH
T_THIS_YEAR
Definition at line 28 of file ausearch-time.h.
Function Documentation
int ausearch_time_end (const char * da, const char * ti)
Definition at line 329 of file ausearch-time.c.
References end_time, lookup_time(), T_NOW, T_RECENT, and T_TODAY.
Referenced by check_params(), and parse_args().
int ausearch_time_start (const char * da, const char * ti)
Definition at line 258 of file ausearch-time.c.
References lookup_time(), start_time, T_NOW, and T_RECENT.
Referenced by check_params(), and parse_args().
int lookup_time (const char * name)
Definition at line 54 of file ausearch-time.c.
References TIME_NAMES, and nv_pair::value.
Referenced by ausearch_time_end(), ausearch_time_start(), and check_params().
Variable Documentation
time_t end_time
Definition at line 35 of file ausearch-time.c.
time_t start_time
Definition at line 35 of file ausearch-time.c.