audit: src/ausearch-parse.h File Reference
ausearch-parse.h File Reference
#include "config.h"
#include "ausearch-llist.h"
Functions
int extract_search_items (llist *l)
Function Documentation
int extract_search_items (llist * l)
Definition at line 79 of file ausearch-parse.c.
References AUDIT_DAEMON_ACCEPT, AUDIT_DAEMON_CLOSE, AUDIT_DAEMON_RESUME, AUDIT_DAEMON_ROTATE, AUDIT_FIRST_KERN_ANOM_MSG, AUDIT_FIRST_USER_MSG, AUDIT_FIRST_USER_MSG2, AUDIT_INTEGRITY_DATA, AUDIT_MMAP, AUDIT_NETFILTER_CFG, AUDIT_NETFILTER_PKT, AUDIT_SECCOMP, event_debug, list_first(), list_next(), _lnode::message, parse_syscall(), llist::s, and _lnode::type.
Referenced by match(), and scan().