audit: src/ausearch-llist.c File Reference
ausearch-llist.c File Reference
#include <stdlib.h>
#include <string.h>
#include "ausearch-llist.h"
Functions
void list_create (llist *l)
void list_last (llist *l)
lnode * list_next (llist *l)
lnode * list_prev (llist *l)
void list_append (llist *l, lnode *node)
int list_find_item (llist *l, unsigned int i)
void list_clear (llist *l)
int list_get_event (llist *l, event *e)
lnode * list_find_msg (llist *l, int i)
lnode * list_find_msg_range (llist *l, int low, int high)
Function Documentation
void list_append (llist * l, lnode * node)
Definition at line 99 of file ausearch-llist.c.
void list_clear (llist * l)
Definition at line 147 of file ausearch-llist.c.
References search_items::acct, alist_clear(), search_items::arch, search_items::avc, llist::cnt, search_items::comm, llist::cur, search_items::cwd, llist::e, search_items::egid, search_items::euid, search_items::exe, search_items::exit, search_items::exit_is_set, search_items::filename, search_items::gid, llist::head, search_items::hostname, search_items::key, search_items::loginuid, _lnode::message, event::milli, _lnode::next, event::node, search_items::pid, search_items::ppid, llist::s, S_UNSET, event::sec, event::serial, search_items::session_id, slist_clear(), search_items::success, search_items::syscall, search_items::terminal, event::type, search_items::uid, search_items::uuid, and search_items::vmname.
void list_create (llist * l)
Definition at line 30 of file ausearch-llist.c.
References search_items::acct, search_items::arch, search_items::avc, llist::cnt, search_items::comm, llist::cur, search_items::cwd, llist::e, search_items::egid, search_items::euid, search_items::exe, search_items::exit, search_items::exit_is_set, search_items::filename, search_items::gid, llist::head, search_items::hostname, search_items::key, search_items::loginuid, event::milli, event::node, search_items::pid, search_items::ppid, llist::s, S_UNSET, event::sec, event::serial, search_items::session_id, search_items::success, search_items::syscall, search_items::terminal, event::type, search_items::uid, search_items::uuid, and search_items::vmname.
int list_find_item (llist * l, unsigned int i)
Definition at line 128 of file ausearch-llist.c.
References llist::cur, llist::head, _lnode::item, and _lnode::next.
Referenced by aulookup_syscall(), and list_prev().
lnode* list_find_msg (llist * l, int i)
Definition at line 225 of file ausearch-llist.c.
References llist::cur, llist::head, _lnode::next, and _lnode::type.
lnode* list_find_msg_range (llist * l, int low, int high)
Definition at line 240 of file ausearch-llist.c.
References llist::cur, llist::head, _lnode::next, and _lnode::type.
int list_get_event (llist * l, event * e)
Definition at line 214 of file ausearch-llist.c.
References llist::e, event::milli, event::sec, and event::serial.
void list_last (llist * l)
Definition at line 66 of file ausearch-llist.c.
References llist::cur, llist::head, and _lnode::next.
lnode* list_next (llist * l)
Definition at line 79 of file ausearch-llist.c.
References llist::cur, and _lnode::next.
lnode* list_prev (llist * l)
Definition at line 87 of file ausearch-llist.c.
References llist::cur, _lnode::item, and list_find_item().