audit: src/ausearch-avc.h File Reference
ausearch-avc.h File Reference
#include "config.h"
#include <sys/types.h>
#include "libaudit.h"
Data Structures
struct _anode
struct alist
Typedefs
typedef struct _anode anode
Enumerations
enum avc_t {
AVC_UNSET, AVC_DENIED, AVC_GRANTED, AVC_UNSET,
AVC_DENIED, AVC_GRANTED
}
Functions
void alist_create (alist *l)
anode * alist_next (alist *l)
void alist_append (alist *l, anode *node)
void anode_init (anode *an)
void anode_clear (anode *an)
void alist_clear (alist *l)
int alist_find_subj (alist *l)
anode * alist_next_subj (alist *l)
int alist_find_obj (alist *l)
anode * alist_next_obj (alist *l)
int alist_find_avc (alist *l)
anode * alist_next_avc (alist *l)
Typedef Documentation
typedef struct _anode anode
Enumeration Type Documentation
enum avc_t
Enumerator
AVC_UNSET
AVC_DENIED
AVC_GRANTED
AVC_UNSET
AVC_DENIED
AVC_GRANTED
Definition at line 31 of file ausearch-avc.h.
Function Documentation
void alist_append (alist * l, anode * node)
Definition at line 64 of file ausearch-avc.c.
References _anode::avc_class, _anode::avc_perm, _anode::avc_result, alist::cnt, alist::cur, alist::head, _anode::next, _anode::scontext, and _anode::tcontext.
void alist_clear (alist * l)
Definition at line 189 of file ausearch-avc.c.
References anode_clear(), alist::cnt, alist::cur, alist::head, and _anode::next.
Referenced by list_clear().
void alist_create (alist * l)
Definition at line 30 of file ausearch-avc.c.
References alist::cnt, alist::cur, and alist::head.
int alist_find_avc (alist * l)
Definition at line 162 of file ausearch-avc.c.
References _anode::avc_result, AVC_UNSET, alist::cur, alist::head, and _anode::next.
Referenced by print_per_event_item().
int alist_find_obj (alist * l)
Definition at line 135 of file ausearch-avc.c.
References alist::cur, alist::head, _anode::next, and _anode::tcontext.
int alist_find_subj (alist * l)
Definition at line 108 of file ausearch-avc.c.
References alist::cur, alist::head, _anode::next, and _anode::scontext.
anode* alist_next (alist * l)
Definition at line 37 of file ausearch-avc.c.
References alist::cur, and _anode::next.
anode* alist_next_avc (alist * l)
Definition at line 177 of file ausearch-avc.c.
References _anode::avc_result, AVC_UNSET, alist::cur, and _anode::next.
Referenced by print_per_event_item().
anode* alist_next_obj (alist * l)
Definition at line 150 of file ausearch-avc.c.
References alist::cur, _anode::next, and _anode::tcontext.
anode* alist_next_subj (alist * l)
Definition at line 123 of file ausearch-avc.c.
References alist::cur, _anode::next, and _anode::scontext.
void anode_clear (anode * an)
Definition at line 215 of file ausearch-avc.c.
References _anode::avc_class, _anode::avc_perm, _anode::scontext, and _anode::tcontext.
Referenced by alist_clear().
void anode_init (anode * an)
Definition at line 206 of file ausearch-avc.c.
References _anode::avc_class, _anode::avc_perm, _anode::avc_result, AVC_UNSET, _anode::scontext, and _anode::tcontext.