audit: src/ausearch-lol.c File Reference
ausearch-lol.c File Reference
#include "ausearch-lol.h"
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include "ausearch-common.h"
#include "private.h"
Macros
#define ARRAY_LIMIT 80
Functions
void lol_create (lol *lo)
void lol_clear (lol *lo)
int lol_add_record (lol *lo, char *buff)
void terminate_all_events (lol *lo)
llist * get_ready_event (lol *lo)
Macro Definition Documentation
#define ARRAY_LIMIT 80
Definition at line 32 of file ausearch-lol.c.
Referenced by lol_create().
Function Documentation
llist* get_ready_event (lol * lo)
Definition at line 278 of file ausearch-lol.c.
References lol::array, _lolnode::l, L_COMPLETE, L_EMPTY, lol::maxi, and _lolnode::status.
int lol_add_record (lol * lo, char * buff)
Definition at line 215 of file ausearch-lol.c.
References lol::array, llist::e, _lolnode::l, L_BUILDING, list_append(), list_create(), MAX_AUDIT_MESSAGE_LENGTH, lol::maxi, _lnode::message, event::milli, _lnode::mlen, event::node, event::sec, event::serial, _lolnode::status, event::type, and _lnode::type.
void lol_clear (lol * lo)
Definition at line 45 of file ausearch-lol.c.
References lol::array, _lolnode::l, list_clear(), lol::maxi, and _lolnode::status.
Referenced by main().
void lol_create (lol * lo)
Definition at line 35 of file ausearch-lol.c.
References lol::array, ARRAY_LIMIT, lol::limit, and lol::maxi.
Referenced by main().
void terminate_all_events (lol * lo)
Definition at line 262 of file ausearch-lol.c.
References lol::array, L_BUILDING, L_COMPLETE, lol::maxi, and _lolnode::status.