audit: src/ausearch-nvpair.h File Reference
ausearch-nvpair.h File Reference
#include "config.h"
#include <sys/types.h>
Data Structures
struct _nvnode
struct nvlist
Typedefs
typedef struct _nvnode nvnode
Functions
void nvlist_create (nvlist *l)
nvnode * nvlist_next (nvlist *l)
void nvlist_append (nvlist *l, nvnode *node)
void nvlist_clear (nvlist *l)
int nvlist_find_val (nvlist *l, long val)
Typedef Documentation
typedef struct _nvnode nvnode
Function Documentation
void nvlist_append (nvlist * l, nvnode * node)
Definition at line 59 of file nvlist.c.
References nvlist::cnt, nvlist::cur, nvlist::head, _nvnode::interp_val, _nvnode::item, _nvnode::name, _nvnode::next, and _nvnode::val.
Referenced by aulookup_gid(), and aulookup_uid().
void nvlist_clear (nvlist * l)
Definition at line 120 of file nvlist.c.
References nvlist::cnt, nvlist::cur, nvlist::head, _nvnode::interp_val, _nvnode::name, _nvnode::next, and _nvnode::val.
Referenced by aulookup_destroy_gid_list(), aulookup_destroy_uid_list(), aulookup_gid(), aulookup_uid(), and aup_list_clear().
void nvlist_create (nvlist * l)
Definition at line 32 of file nvlist.c.
References nvlist::cnt, nvlist::cur, and nvlist::head.
Referenced by aulookup_gid(), aulookup_uid(), and aup_list_append().
int nvlist_find_val (nvlist * l, long val)
Definition at line 66 of file ausearch-nvpair.c.
References nvlist::cur, nvlist::head, _nvnode::next, and _nvnode::val.
Referenced by aulookup_gid(), and aulookup_uid().
nvnode* nvlist_next (nvlist * l)
Definition at line 52 of file nvlist.c.
References nvlist::cur, and _nvnode::next.
Referenced by auparse_find_field_next(), and auparse_next_field().