audit: src/ausearch-match.c File Reference
ausearch-match.c File Reference
#include "config.h"
#include <string.h>
#include "libaudit.h"
#include "ausearch-options.h"
#include "ausearch-parse.h"
#include <stdio.h>
Functions
int match (llist *l)
Function Documentation
int match (llist * l)
Definition at line 46 of file ausearch-match.c.
References search_items::arch, audit_elf_to_machine(), search_items::comm, search_items::cwd, llist::e, end_time, event_comm, event_exe, event_exit, event_exit_is_set, event_filename, event_hostname, event_id, event_key, event_machine, event_node_list, event_pid, event_ppid, event_session_id, event_success, event_syscall, event_terminal, event_uuid, event_vmname, search_items::exe, search_items::exit, search_items::exit_is_set, extract_search_items(), search_items::filename, search_items::hostname, ilist_next(), search_items::key, list_first(), list_next(), event::node, _int_node::num, search_items::pid, search_items::ppid, llist::s, S_UNSET, event::sec, event::serial, search_items::session_id, slist_next(), start_time, _snode::str, search_items::success, search_items::syscall, search_items::terminal, _lnode::type, search_items::uuid, and search_items::vmname.