audit: src/ausearch-lol.h File Reference
ausearch-lol.h File Reference
#include "config.h"
#include "ausearch-llist.h"
Data Structures
struct _lolnode
struct lol
Typedefs
typedef struct _lolnode lolnode
Enumerations
enum lol_t { L_EMPTY, L_BUILDING, L_COMPLETE }
Functions
void lol_create (lol *lo)
void lol_clear (lol *lo)
int lol_add_record (lol *lo, char *buff)
void terminate_all_events (lol *lo)
llist * get_ready_event (lol *lo)
Typedef Documentation
typedef struct _lolnode lolnode
Enumeration Type Documentation
enum lol_t
Enumerator
L_EMPTY
L_BUILDING
L_COMPLETE
Definition at line 30 of file ausearch-lol.h.
Function Documentation
llist* get_ready_event (lol * lo)
Definition at line 278 of file ausearch-lol.c.
References lol::array, _lolnode::l, L_COMPLETE, L_EMPTY, lol::maxi, and _lolnode::status.
int lol_add_record (lol * lo, char * buff)
Definition at line 215 of file ausearch-lol.c.
References lol::array, llist::e, _lolnode::l, L_BUILDING, list_append(), list_create(), MAX_AUDIT_MESSAGE_LENGTH, lol::maxi, _lnode::message, event::milli, _lnode::mlen, event::node, event::sec, event::serial, _lolnode::status, event::type, and _lnode::type.
void lol_clear (lol * lo)
Definition at line 45 of file ausearch-lol.c.
References lol::array, _lolnode::l, list_clear(), lol::maxi, and _lolnode::status.
Referenced by main().
void lol_create (lol * lo)
Definition at line 35 of file ausearch-lol.c.
References lol::array, ARRAY_LIMIT, lol::limit, and lol::maxi.
Referenced by main().
void terminate_all_events (lol * lo)
Definition at line 262 of file ausearch-lol.c.
References lol::array, L_BUILDING, L_COMPLETE, lol::maxi, and _lolnode::status.