audit: src/ausearch-options.c File Reference
ausearch-options.c File Reference
#include "config.h"
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <pwd.h>
#include <grp.h>
#include "ausearch-options.h"
#include "ausearch-time.h"
#include "ausearch-int.h"
#include "libaudit.h"
Data Structures
struct nv_pair
Macros
#define OPTION_NAMES (sizeof(optiontab)/sizeof(optiontab[0]))
Enumerations
enum {
S_EVENT, S_COMM, S_FILENAME, S_ALL_GID,
S_EFF_GID, S_GID, S_HELP, S_HOSTNAME,
S_INTERP, S_INFILE, S_MESSAGE_TYPE, S_PID,
S_SYSCALL, S_OSUCCESS, S_TIME_END, S_TIME_START,
S_TERMINAL, S_ALL_UID, S_EFF_UID, S_UID,
S_LOGINID, S_VERSION, S_EXACT_MATCH, S_EXECUTABLE,
S_CONTEXT, S_SUBJECT, S_OBJECT, S_PPID,
S_KEY, S_RAW, S_NODE, S_IN_LOGS,
S_JUST_ONE, S_SESSION, S_EXIT, S_LINEBUFFERED,
S_UUID, S_VMNAME, S_DEBUG, S_CHECKPOINT,
S_ARCH
}
Functions
int check_params (int count, char *vars[])
Variables
char * user_file = NULL
int force_logs = 0
unsigned int event_id = -1
gid_t event_gid = -1
gid_t event_egid = -1
ilist * event_type = NULL
pid_t event_pid = -1
pid_t event_ppid = -1
success_t event_success = S_UNSET
int event_exact_match = 0
uid_t event_uid = -1
uid_t event_euid = -1
uid_t event_loginuid = -2
int event_syscall = -1
int event_machine = -1
int event_ua = 0
int event_ga = 0
int event_se = 0
int just_one = 0
uint32_t event_session_id = -2
long long event_exit = 0
int event_exit_is_set = 0
int line_buffered = 0
int event_debug = 0
int checkpt_timeonly = 0
const char * event_key = NULL
const char * event_filename = NULL
const char * event_exe = NULL
const char * event_comm = NULL
const char * event_hostname = NULL
const char * event_terminal = NULL
const char * event_subject = NULL
const char * event_object = NULL
const char * event_uuid = NULL
const char * event_vmname = NULL
const char * checkpt_filename = NULL
report_t report_format = RPT_DEFAULT
slist * event_node_list = NULL
Macro Definition Documentation
#define OPTION_NAMES (sizeof(optiontab)/sizeof(optiontab[0]))
Definition at line 168 of file ausearch-options.c.
Enumeration Type Documentation
anonymous enum
Enumerator
S_EVENT
S_COMM
S_FILENAME
S_ALL_GID
S_EFF_GID
S_GID
S_HELP
S_HOSTNAME
S_INTERP
S_INFILE
S_MESSAGE_TYPE
S_PID
S_SYSCALL
S_OSUCCESS
S_TIME_END
S_TIME_START
S_TERMINAL
S_ALL_UID
S_EFF_UID
S_UID
S_LOGINID
S_VERSION
S_EXACT_MATCH
S_EXECUTABLE
S_CONTEXT
S_SUBJECT
S_OBJECT
S_PPID
S_KEY
S_RAW
S_NODE
S_IN_LOGS
S_JUST_ONE
S_SESSION
S_EXIT
S_LINEBUFFERED
S_UUID
S_VMNAME
S_DEBUG
S_CHECKPOINT
S_ARCH
Definition at line 83 of file ausearch-options.c.
Function Documentation
int check_params (int count, char * vars[])
Definition at line 287 of file ausearch-options.c.
References audit_detect_machine(), audit_determine_machine(), AUDIT_FIRST_USER_MSG, AUDIT_LAST_VIRT_MSG, audit_msg_type_to_name(), audit_name_to_errno(), audit_name_to_syscall(), ausearch_time_end(), ausearch_time_start(), C_ADD, C_DEL, checkpt_filename, checkpt_timeonly, D_DETAILED, D_SUM, dummy, event_comm, event_conf_act, event_debug, event_egid, event_euid, event_exact_match, event_exe, event_exit, event_exit_is_set, event_failed, event_filename, event_ga, event_gid, event_hostname, event_id, event_key, event_loginuid, event_machine, event_object, event_pid, event_ppid, event_se, event_session_id, event_subject, event_success, event_syscall, event_terminal, event_ua, event_uid, event_uuid, event_vmname, auparse_test::exit, F_FAILED, F_SUCCESS, force_logs, _snode::hits, just_one, _snode::key, line_buffered, lookup_time(), auparse_test::name, no_config, R_ACCT_MODS, R_ADD, R_ANOMALY, R_AUTH, R_AVCS, R_COMM, R_CONFIGS, R_CRYPTO, R_DEL, R_EVENTS, R_EXES, R_FAILED, R_FILES, R_HELP, R_HOSTS, R_IN_LOGS, R_INFILE, R_INTEG, R_INTERPRET, R_KEYS, R_LOG_TIMES, R_LOGINS, R_MAC, R_NO_CONFIG, R_NODE, R_PIDS, R_RESPONSE, R_SUCCESS, R_SUMMARY_DET, R_SYSCALLS, R_TERMINALS, R_TIME_END, R_TIME_START, R_TTY, R_USERS, R_VERSION, R_VIRT, report_format, report_type, RPT_ACCT_MOD, RPT_ANOMALY, RPT_AUTH, RPT_AVC, RPT_COMM, RPT_CONFIG, RPT_CRYPTO, RPT_DEFAULT, RPT_EVENT, RPT_EXE, RPT_FILE, RPT_HOST, RPT_INTEG, RPT_INTERP, RPT_KEY, RPT_LOGIN, RPT_MAC, RPT_PID, RPT_RAW, RPT_RESPONSE, RPT_SUMMARY, RPT_SYSCALL, RPT_TERM, RPT_TIME, RPT_TTY, RPT_UNSET, RPT_USER, RPT_VIRT, S_ALL_GID, S_ALL_UID, S_ARCH, S_CHECKPOINT, S_COMM, S_CONTEXT, S_DEBUG, S_EFF_GID, S_EFF_UID, S_EVENT, S_EXACT_MATCH, S_EXECUTABLE, S_EXIT, S_FAILED, S_FILENAME, S_GID, S_HELP, S_HOSTNAME, S_IN_LOGS, S_INFILE, S_INTERP, S_JUST_ONE, S_KEY, S_LINEBUFFERED, S_LOGINID, S_MESSAGE_TYPE, S_NODE, S_OBJECT, S_OSUCCESS, S_PID, S_PPID, S_RAW, S_SESSION, S_SUBJECT, S_SUCCESS, S_SYSCALL, S_TERMINAL, S_TIME_END, S_TIME_START, S_UID, S_UUID, S_VERSION, S_VMNAME, slist_append(), slist_create(), _snode::str, UNIMPLEMENTED, and user_file.
Variable Documentation
const char* checkpt_filename = NULL
Definition at line 71 of file ausearch-options.c.
Referenced by check_params(), and main().
int checkpt_timeonly = 0
Definition at line 60 of file ausearch-options.c.
Referenced by check_params().
const char* event_comm = NULL
Definition at line 64 of file ausearch-options.c.
int event_debug = 0
Definition at line 59 of file ausearch-options.c.
gid_t event_egid = -1
Definition at line 46 of file ausearch-options.c.
uid_t event_euid = -1
Definition at line 51 of file ausearch-options.c.
int event_exact_match = 0
Definition at line 50 of file ausearch-options.c.
Referenced by check_params().
const char* event_exe = NULL
Definition at line 63 of file ausearch-options.c.
long long event_exit = 0
Definition at line 56 of file ausearch-options.c.
int event_exit_is_set = 0
Definition at line 57 of file ausearch-options.c.
const char* event_filename = NULL
Definition at line 62 of file ausearch-options.c.
int event_ga = 0
Definition at line 53 of file ausearch-options.c.
Referenced by check_params().
gid_t event_gid = -1
Definition at line 46 of file ausearch-options.c.
const char* event_hostname = NULL
Definition at line 65 of file ausearch-options.c.
unsigned int event_id = -1
Definition at line 45 of file ausearch-options.c.
const char* event_key = NULL
Definition at line 61 of file ausearch-options.c.
uid_t event_loginuid = -2
Definition at line 51 of file ausearch-options.c.
int event_machine = -1
Definition at line 52 of file ausearch-options.c.
slist* event_node_list = NULL
Definition at line 75 of file ausearch-options.c.
const char* event_object = NULL
Definition at line 68 of file ausearch-options.c.
pid_t event_pid = -1
Definition at line 48 of file ausearch-options.c.
pid_t event_ppid = -1
Definition at line 48 of file ausearch-options.c.
int event_se = 0
Definition at line 53 of file ausearch-options.c.
Referenced by check_params().
uint32_t event_session_id = -2
Definition at line 55 of file ausearch-options.c.
const char* event_subject = NULL
Definition at line 67 of file ausearch-options.c.
success_t event_success = S_UNSET
Definition at line 49 of file ausearch-options.c.
int event_syscall = -1
Definition at line 52 of file ausearch-options.c.
Referenced by check_params(), and match().
const char* event_terminal = NULL
Definition at line 66 of file ausearch-options.c.
ilist* event_type = NULL
Definition at line 47 of file ausearch-options.c.
int event_ua = 0
Definition at line 53 of file ausearch-options.c.
Referenced by check_params().
uid_t event_uid = -1
Definition at line 51 of file ausearch-options.c.
const char* event_uuid = NULL
Definition at line 69 of file ausearch-options.c.
const char* event_vmname = NULL
Definition at line 70 of file ausearch-options.c.
int force_logs = 0
Definition at line 42 of file ausearch-options.c.
int just_one = 0
Definition at line 54 of file ausearch-options.c.
Referenced by check_params().
int line_buffered = 0
Definition at line 58 of file ausearch-options.c.
Referenced by check_params().
report_t report_format = RPT_DEFAULT
Definition at line 72 of file ausearch-options.c.
char* user_file = NULL
Definition at line 41 of file ausearch-options.c.