audit: src/ausearch.c File Reference
ausearch.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdio_ext.h>
#include <string.h>
#include <stdlib.h>
#include <getopt.h>
#include <unistd.h>
#include <ctype.h>
#include <time.h>
#include <errno.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/param.h>
#include <locale.h>
#include <signal.h>
#include "libaudit.h"
#include "auditd-config.h"
#include "ausearch-options.h"
#include "ausearch-lol.h"
#include "ausearch-lookup.h"
#include "auparse.h"
#include "ausearch-checkpt.h"
Functions
int match (llist *l)
void output_record (llist *l)
int main (int argc, char *argv[])
Variables
const char * checkpt_filename
int checkpt_timeonly
char * user_file
int force_logs
Function Documentation
int main (int argc, char * argv[])
Definition at line 82 of file ausearch.c.
References auparse_destroy(), check_params(), checkpt_failure, checkpt_filename, CP_CORRUPTED, DBG_NO, event_key, force_logs, free_ChkPtMemory(), ilist_clear(), load_ChkPt(), lol_clear(), lol_create(), MSG_STDERR, report_format, RPT_RAW, save_ChkPt(), set_aumessage_mode, and user_file.
int match (llist * l)
Definition at line 46 of file ausearch-match.c.
References search_items::arch, audit_elf_to_machine(), search_items::comm, search_items::cwd, llist::e, end_time, event_comm, event_exe, event_exit, event_exit_is_set, event_filename, event_hostname, event_id, event_key, event_machine, event_node_list, event_pid, event_ppid, event_session_id, event_success, event_syscall, event_terminal, event_uuid, event_vmname, search_items::exe, search_items::exit, search_items::exit_is_set, extract_search_items(), search_items::filename, search_items::hostname, ilist_next(), search_items::key, list_first(), list_next(), event::node, _int_node::num, search_items::pid, search_items::ppid, llist::s, S_UNSET, event::sec, event::serial, search_items::session_id, slist_next(), start_time, _snode::str, search_items::success, search_items::syscall, search_items::terminal, _lnode::type, search_items::uuid, and search_items::vmname.
void output_record (llist * l)
Definition at line 51 of file ausearch-report.c.
References auparse_test::exit, report_format, RPT_DEFAULT, RPT_INTERP, RPT_PRETTY, and RPT_RAW.
Variable Documentation
const char* checkpt_filename
Definition at line 71 of file ausearch-options.c.
Referenced by check_params(), and main().
int checkpt_timeonly
Definition at line 60 of file ausearch-options.c.
Referenced by check_params().
int force_logs
Definition at line 41 of file aureport-options.c.
Referenced by check_params(), and main().
char* user_file
Definition at line 40 of file aureport-options.c.
Referenced by check_params(), and main().