audit: src/ausearch-llist.h File Reference
ausearch-llist.h File Reference
#include "config.h"
#include <sys/types.h>
#include "ausearch-string.h"
#include "ausearch-avc.h"
#include "ausearch-common.h"
Data Structures
struct event
struct search_items
struct _lnode
struct llist
Typedefs
typedef struct _lnode lnode
Functions
void list_create (llist *l)
void list_last (llist *l)
lnode * list_next (llist *l)
lnode * list_prev (llist *l)
void list_append (llist *l, lnode *node)
void list_clear (llist *l)
int list_get_event (llist *l, event *e)
int list_find_item (llist *l, unsigned int i)
lnode * list_find_msg (llist *l, int i)
lnode * list_find_msg_range (llist *l, int low, int high)
Typedef Documentation
typedef struct _lnode lnode
Function Documentation
void list_append (llist * l, lnode * node)
Definition at line 99 of file ausearch-llist.c.
void list_clear (llist * l)
Definition at line 89 of file auditctl-llist.c.
void list_create (llist * l)
Definition at line 28 of file auditctl-llist.c.
int list_find_item (llist * l, unsigned int i)
Definition at line 128 of file ausearch-llist.c.
References llist::cur, llist::head, _lnode::item, and _lnode::next.
Referenced by aulookup_syscall(), and list_prev().
lnode* list_find_msg (llist * l, int i)
Definition at line 225 of file ausearch-llist.c.
References llist::cur, llist::head, _lnode::next, and _lnode::type.
lnode* list_find_msg_range (llist * l, int low, int high)
Definition at line 240 of file ausearch-llist.c.
References llist::cur, llist::head, _lnode::next, and _lnode::type.
int list_get_event (llist * l, event * e)
Definition at line 214 of file ausearch-llist.c.
References llist::e, event::milli, event::sec, and event::serial.
void list_last (llist * l)
Definition at line 40 of file auditctl-llist.c.
References llist::cur, llist::head, and _lnode::next.
lnode* list_next (llist * l)
Definition at line 53 of file auditctl-llist.c.
lnode* list_prev (llist * l)
Definition at line 87 of file ausearch-llist.c.
References llist::cur, _lnode::item, and list_find_item().