audit: src/ausearch-options.h File Reference
ausearch-options.h File Reference
#include <time.h>
#include <sys/types.h>
#include <stdint.h>
#include "ausearch-common.h"
#include "ausearch-int.h"
Functions
int check_params (int count, char *vars[])
Variables
const char * event_key
const char * event_subject
const char * event_object
int event_se
int just_one
int line_buffered
int event_debug
pid_t event_ppid
uint32_t event_session_id
ilist * event_type
report_t report_format
Function Documentation
int check_params (int count, char * vars[])
Definition at line 233 of file aureport-options.c.
References audit_detect_machine(), audit_determine_machine(), AUDIT_FIRST_USER_MSG, AUDIT_LAST_VIRT_MSG, audit_msg_type_to_name(), audit_name_to_errno(), audit_name_to_syscall(), ausearch_time_end(), ausearch_time_start(), C_ADD, C_DEL, checkpt_filename, checkpt_timeonly, D_DETAILED, D_SUM, dummy, event_comm, event_conf_act, event_debug, event_egid, event_euid, event_exact_match, event_exe, event_exit, event_exit_is_set, event_failed, event_filename, event_ga, event_gid, event_hostname, event_id, event_key, event_loginuid, event_machine, event_object, event_pid, event_ppid, event_se, event_session_id, event_subject, event_success, event_syscall, event_terminal, event_ua, event_uid, event_uuid, event_vmname, auparse_test::exit, F_FAILED, F_SUCCESS, force_logs, _snode::hits, just_one, _snode::key, line_buffered, lookup_time(), auparse_test::name, no_config, R_ACCT_MODS, R_ADD, R_ANOMALY, R_AUTH, R_AVCS, R_COMM, R_CONFIGS, R_CRYPTO, R_DEL, R_EVENTS, R_EXES, R_FAILED, R_FILES, R_HELP, R_HOSTS, R_IN_LOGS, R_INFILE, R_INTEG, R_INTERPRET, R_KEYS, R_LOG_TIMES, R_LOGINS, R_MAC, R_NO_CONFIG, R_NODE, R_PIDS, R_RESPONSE, R_SUCCESS, R_SUMMARY_DET, R_SYSCALLS, R_TERMINALS, R_TIME_END, R_TIME_START, R_TTY, R_USERS, R_VERSION, R_VIRT, report_format, report_type, RPT_ACCT_MOD, RPT_ANOMALY, RPT_AUTH, RPT_AVC, RPT_COMM, RPT_CONFIG, RPT_CRYPTO, RPT_DEFAULT, RPT_EVENT, RPT_EXE, RPT_FILE, RPT_HOST, RPT_INTEG, RPT_INTERP, RPT_KEY, RPT_LOGIN, RPT_MAC, RPT_PID, RPT_RAW, RPT_RESPONSE, RPT_SUMMARY, RPT_SYSCALL, RPT_TERM, RPT_TIME, RPT_TTY, RPT_UNSET, RPT_USER, RPT_VIRT, S_ALL_GID, S_ALL_UID, S_ARCH, S_CHECKPOINT, S_COMM, S_CONTEXT, S_DEBUG, S_EFF_GID, S_EFF_UID, S_EVENT, S_EXACT_MATCH, S_EXECUTABLE, S_EXIT, S_FAILED, S_FILENAME, S_GID, S_HELP, S_HOSTNAME, S_IN_LOGS, S_INFILE, S_INTERP, S_JUST_ONE, S_KEY, S_LINEBUFFERED, S_LOGINID, S_MESSAGE_TYPE, S_NODE, S_OBJECT, S_OSUCCESS, S_PID, S_PPID, S_RAW, S_SESSION, S_SUBJECT, S_SUCCESS, S_SYSCALL, S_TERMINAL, S_TIME_END, S_TIME_START, S_UID, S_UUID, S_VERSION, S_VMNAME, slist_append(), slist_create(), _snode::str, UNIMPLEMENTED, and user_file.
Referenced by main().
Variable Documentation
int event_debug
Definition at line 62 of file aureport-options.c.
Referenced by check_params(), and extract_search_items().
const char* event_key
Definition at line 49 of file aureport-options.c.
Referenced by check_params(), main(), and match().
const char* event_object
Definition at line 56 of file aureport-options.c.
Referenced by check_params().
pid_t event_ppid
Definition at line 61 of file aureport-options.c.
Referenced by check_params(), and match().
int event_se
Definition at line 53 of file ausearch-options.c.
Referenced by check_params().
uint32_t event_session_id
Definition at line 61 of file aureport-options.c.
Referenced by check_params(), and match().
const char* event_subject
Definition at line 55 of file aureport-options.c.
Referenced by check_params().
ilist* event_type
Definition at line 47 of file ausearch-options.c.
int just_one
Definition at line 54 of file ausearch-options.c.
Referenced by check_params().
int line_buffered
Definition at line 58 of file ausearch-options.c.
Referenced by check_params().
report_t report_format
Definition at line 68 of file aureport-options.c.
Referenced by aulookup_gid(), aulookup_syscall(), aulookup_uid(), check_params(), main(), and output_record().