audit: tools/ausyscall/ausyscall.c File Reference
ausyscall.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include "libaudit.h"
Macros
#define LAST_SYSCALL 1400
Functions
void usage (void)
int main (int argc, char *argv[])
Macro Definition Documentation
#define LAST_SYSCALL 1400
Definition at line 30 of file ausyscall.c.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 38 of file ausyscall.c.
References audit_detect_machine(), audit_machine_to_name(), audit_name_to_machine(), audit_name_to_syscall(), audit_syscall_to_name(), auparse_test::exit, LAST_SYSCALL, auparse_test::name, and usage().
void usage (void)
Definition at line 32 of file ausyscall.c.
References auparse_test::exit, and usage().