audit: tools/auvirt/auvirt-list.c File Reference
auvirt-list.c File Reference
#include "auvirt-list.h"
#include <stdlib.h>
Functions
list_t * list_init (list_t *list, list_free_data_fn *free_data_fn)
list_t * list_new (list_free_data_fn *free_data_fn)
void list_free_node (list_node_t *node, list_free_data_fn *free_data_fn)
void list_free_ (list_t *list, list_free_data_fn *free_data_fn)
void list_free (list_t *list)
list_node_t * list_insert_after (list_t *list, list_node_t *it, void *data)
list_node_t * list_append (list_t *list, void *data)
int list_remove_ (list_t *list, list_node_t *it, list_free_data_fn *free_data_fn)
int list_remove (list_t *list, list_node_t *it)
Function Documentation
list_node_t* list_append (list_t * list, void * data)
Definition at line 79 of file auvirt-list.c.
References list_insert_after(), and list_t::tail.
void list_free (list_t * list)
Definition at line 40 of file auvirt-list.c.
References list_t::free_data_fn, and list_free_().
Referenced by main().
void list_free_ (list_t * list, list_free_data_fn * free_data_fn)
Definition at line 27 of file auvirt-list.c.
References list_t::head, list_free_node(), list_node_t::next, and list_node_t::prev.
Referenced by list_free().
void list_free_node (list_node_t * node, list_free_data_fn * free_data_fn)
Definition at line 18 of file auvirt-list.c.
References list_node_t::data.
Referenced by list_free_(), and list_remove_().
list_t* list_init (list_t * list, list_free_data_fn * free_data_fn)
Definition at line 4 of file auvirt-list.c.
References list_t::free_data_fn, list_t::head, and list_t::tail.
Referenced by list_new().
list_node_t* list_insert_after (list_t * list, list_node_t * it, void * data)
Definition at line 46 of file auvirt-list.c.
References list_node_t::data, auparse_test::data, list_t::head, list_node_t::next, list_node_t::prev, and list_t::tail.
Referenced by list_append().
list_t* list_new (list_free_data_fn * free_data_fn)
Definition at line 13 of file auvirt-list.c.
References list_init().
Referenced by main().
int list_remove (list_t * list, list_node_t * it)
Definition at line 101 of file auvirt-list.c.
References list_t::free_data_fn, and list_remove_().
int list_remove_ (list_t * list, list_node_t * it, list_free_data_fn * free_data_fn)
Definition at line 84 of file auvirt-list.c.
References list_t::head, list_free_node(), list_node_t::next, list_node_t::prev, and list_t::tail.
Referenced by list_remove().