audit: tools/auvirt/auvirt.c File Reference
auvirt.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <ctype.h>
#include <locale.h>
#include <string.h>
#include <regex.h>
#include <time.h>
#include <sys/types.h>
#include <pwd.h>
#include <unistd.h>
#include "auparse.h"
#include "libaudit.h"
#include "ausearch-time.h"
#include "auvirt-list.h"
Data Structures
struct record_id
struct event
Macros
#define N(str) ((str) ? str : "")
Enumerations
enum event_type {
ET_NONE = 0, ET_START, ET_STOP, ET_MACHINE_ID,
ET_AVC, ET_RES, ET_ANOM, ET_DOWN
}
Functions
struct event * event_alloc (void)
void event_free (struct event *event)
char * copy_str (const char *str)
void usage (FILE *output)
int parse_args (int argc, char **argv)
auparse_state_t * init_auparse (void)
int create_search_criteria (auparse_state_t *au)
int extract_virt_fields (auparse_state_t *au, const char **p_uuid, uid_t *p_uid, time_t *p_time, const char **p_name, int *p_suc)
const char * get_seclevel (const char *seclabel)
int add_proof (struct event *event, auparse_state_t *au)
int process_machine_id_event (auparse_state_t *au)
int add_start_guest_event (auparse_state_t *au)
int add_stop_guest_event (auparse_state_t *au)
int process_control_event (auparse_state_t *au)
int is_resource (const char *res)
int add_resource (auparse_state_t *au, const char *uuid, uid_t uid, time_t time, const char *name, int success, const char *reason, const char *res_type, const char *res)
int update_resource (auparse_state_t *au, const char *uuid, uid_t uid, time_t time, const char *name, int success, const char *reason, const char *res_type, const char *res)
int process_resource_event (auparse_state_t *au)
struct event * get_machine_id_by_seclevel (const char *seclevel)
int process_avc_selinux_context (auparse_state_t *au, const char *context)
int process_avc_selinux (auparse_state_t *au)
int process_avc (auparse_state_t *au)
int process_anom (auparse_state_t *au)
int process_shutdown (auparse_state_t *au)
const char * get_rec_type (struct event *e)
const char * get_username (struct event *e)
const char * get_time_period (struct event *event)
void print_event (struct event *event)
void print_events (void)
void print_summary (void)
int main (int argc, char **argv)
Variables
list_t * events = NULL
Macro Definition Documentation
#define N (str) ((str) ? str : "")
Referenced by print_event(), and reheap().
Enumeration Type Documentation
enum ilist * event_type
Enumerator
ET_NONE
ET_START
ET_STOP
ET_MACHINE_ID
ET_AVC
ET_RES
ET_ANOM
ET_DOWN
Definition at line 63 of file auvirt.c.
Function Documentation
int add_proof (struct event * event, auparse_state_t * au)
Definition at line 436 of file auvirt.c.
References auparse_get_milli(), auparse_get_serial(), auparse_get_time(), event::proof, and record_id::time.
Referenced by add_resource(), add_start_guest_event(), add_stop_guest_event(), process_anom(), process_avc_selinux_context(), process_machine_id_event(), process_shutdown(), and update_resource().
int add_resource (auparse_state_t * au, const char * uuid, uid_t uid, time_t time, const char * name, int success, const char * reason, const char * res_type, const char * res)
Definition at line 663 of file auvirt.c.
References add_proof(), auparse_find_field(), auparse_interpret_field(), event::cgroup_class, copy_str(), ET_RES, event_alloc(), event_free(), is_resource(), list_append(), event::success, and auparse_test::uid.
Referenced by process_resource_event().
int add_start_guest_event (auparse_state_t * au)
Definition at line 498 of file auvirt.c.
References add_proof(), auparse_find_field(), auparse_first_record(), auparse_get_field_int(), copy_str(), list_node_t::data, event::end, ET_MACHINE_ID, ET_RES, ET_START, ET_STOP, event_alloc(), event_free(), extract_virt_fields(), list_append(), event::name, auparse_test::name, event::pid, list_node_t::prev, event::start, event::success, list_t::tail, event::type, auparse_test::uid, event::uid, and event::uuid.
Referenced by process_control_event().
int add_stop_guest_event (auparse_state_t * au)
Definition at line 555 of file auvirt.c.
References add_proof(), auparse_find_field(), auparse_first_record(), auparse_get_field_int(), copy_str(), list_node_t::data, event::end, ET_MACHINE_ID, ET_RES, ET_START, ET_STOP, event_alloc(), event_free(), extract_virt_fields(), list_append(), event::name, auparse_test::name, event::pid, list_node_t::prev, event::start, stop, event::success, list_t::tail, event::type, auparse_test::uid, event::uid, and event::uuid.
Referenced by process_control_event().
char* copy_str (const char * str) inline
Definition at line 141 of file auvirt.c.
Referenced by add_resource(), add_start_guest_event(), add_stop_guest_event(), process_anom(), process_avc_selinux_context(), and process_machine_id_event().
int create_search_criteria (auparse_state_t * au)
Definition at line 306 of file auvirt.c.
References AUDIT_FIRST_ANOM_MSG, AUDIT_FIRST_KERN_ANOM_MSG, AUDIT_FIRST_VIRT_MSG, AUDIT_LAST_ANOM_MSG, AUDIT_LAST_KERN_ANOM_MSG, AUDIT_LAST_VIRT_MSG, ausearch_add_expression(), ausearch_add_interpreted_item(), ausearch_add_item(), ausearch_add_timestamp_item(), AUSEARCH_RULE_AND, AUSEARCH_RULE_CLEAR, AUSEARCH_RULE_OR, end_time, start_time, and event::uuid.
Referenced by main().
struct event* event_alloc (void)
Definition at line 104 of file auvirt.c.
Referenced by add_resource(), add_start_guest_event(), add_stop_guest_event(), process_anom(), process_avc_selinux_context(), process_machine_id_event(), and process_shutdown().
void event_free (struct event * event)
Definition at line 120 of file auvirt.c.
References event::avc_operation, event::avc_result, event::cgroup_acl, event::cgroup_class, event::cgroup_detail, event::comm, event::context, event::name, event::reason, event::res, event::res_type, event::seclevel, event::target, and event::uuid.
Referenced by add_resource(), add_start_guest_event(), add_stop_guest_event(), main(), process_anom(), process_avc_selinux_context(), process_machine_id_event(), and process_shutdown().
int extract_virt_fields (auparse_state_t * au, const char ** p_uuid, uid_t * p_uid, time_t * p_time, const char ** p_name, int * p_suc)
Definition at line 373 of file auvirt.c.
References auparse_find_field(), auparse_first_record(), auparse_get_field_int(), auparse_get_field_str(), auparse_get_milli(), auparse_get_serial(), auparse_get_time(), auparse_interpret_field(), and auparse_test::res.
Referenced by add_start_guest_event(), add_stop_guest_event(), process_anom(), process_avc_selinux_context(), process_machine_id_event(), process_resource_event(), and process_shutdown().
struct event* get_machine_id_by_seclevel (const char * seclevel)
Definition at line 813 of file auvirt.c.
References list_node_t::data, ET_MACHINE_ID, list_node_t::prev, event::seclevel, list_t::tail, and event::type.
Referenced by process_anom(), and process_avc_selinux_context().
const char* get_rec_type (struct event * e)
Definition at line 1289 of file auvirt.c.
References ET_ANOM, ET_AVC, ET_DOWN, ET_RES, ET_START, ET_STOP, and event::type.
Referenced by print_event().
const char* get_seclevel (const char * seclabel)
Definition at line 418 of file auvirt.c.
Referenced by process_anom(), process_avc_selinux_context(), and process_machine_id_event().
const char* get_time_period (struct event * event)
Definition at line 1333 of file auvirt.c.
References event::end, ET_ANOM, ET_AVC, event::start, event::success, and event::type.
Referenced by print_event().
const char* get_username (struct event * e)
Definition at line 1315 of file auvirt.c.
References s, and event::uid.
Referenced by print_event().
auparse_state_t* init_auparse (void)
Definition at line 285 of file auvirt.c.
References auparse_init(), AUSOURCE_FILE, AUSOURCE_FILE_POINTER, and AUSOURCE_LOGS.
Referenced by main().
int is_resource (const char * res) inline
Definition at line 653 of file auvirt.c.
Referenced by add_resource(), and update_resource().
int main (int argc, char ** argv)
Definition at line 1518 of file auvirt.c.
References AUDIT_FIRST_ANOM_MSG, AUDIT_FIRST_KERN_ANOM_MSG, AUDIT_LAST_ANOM_MSG, AUDIT_LAST_KERN_ANOM_MSG, AUDIT_SYSTEM_SHUTDOWN, AUDIT_VIRT_CONTROL, AUDIT_VIRT_MACHINE_ID, AUDIT_VIRT_RESOURCE, auparse_destroy(), auparse_get_type(), auparse_next_event(), ausearch_next_event(), create_search_criteria(), err, event_free(), auparse_test::exit, init_auparse(), list_free(), list_new(), parse_args(), print_events(), print_summary(), process_anom(), process_avc(), process_control_event(), process_machine_id_event(), process_resource_event(), process_shutdown(), and usage().
int parse_args (int argc, char ** argv)
Definition at line 156 of file auvirt.c.
References ausearch_time_end(), ausearch_time_start(), end_time, auparse_test::exit, start_time, and event::uuid.
Referenced by main().
void print_event (struct event * event)
Definition at line 1362 of file auvirt.c.
References event::avc_operation, event::avc_result, event::cgroup_acl, event::cgroup_class, event::cgroup_detail, event::comm, event::context, ET_AVC, ET_MACHINE_ID, ET_RES, ET_START, get_rec_type(), get_time_period(), get_username(), record_id::milli, N, event::name, event::proof, event::reason, event::res, event::res_type, event::seclevel, record_id::serial, event::target, record_id::time, event::type, and event::uuid.
Referenced by print_events().
void print_events (void)
Definition at line 1426 of file auvirt.c.
References list_node_t::data, list_t::head, list_node_t::next, and print_event().
Referenced by main().
void print_summary (void)
Definition at line 1437 of file auvirt.c.
References list_node_t::data, event::end, end_time, ET_ANOM, ET_AVC, ET_DOWN, ET_RES, ET_START, ET_STOP, list_t::head, list_node_t::next, event::start, start_time, stop, event::success, and event::type.
Referenced by main().
int process_anom (auparse_state_t * au)
Definition at line 1143 of file auvirt.c.
References add_proof(), auparse_find_field(), auparse_first_record(), auparse_get_field_int(), auparse_get_record_text(), copy_str(), list_node_t::data, event::end, ET_ANOM, ET_START, ET_STOP, event_alloc(), event_free(), extract_virt_fields(), get_machine_id_by_seclevel(), get_seclevel(), list_append(), event::name, list_node_t::next, auparse_test::pid, event::pid, event::proof, event::seclevel, event::start, event::success, list_t::tail, event::type, auparse_test::uid, event::uid, and event::uuid.
Referenced by main().
int process_avc (auparse_state_t * au)
Definition at line 1122 of file auvirt.c.
References auparse_find_field(), auparse_first_record(), and process_avc_selinux().
Referenced by main().
int process_avc_selinux (auparse_state_t * au)
Definition at line 901 of file auvirt.c.
References event::context, and process_avc_selinux_context().
Referenced by process_avc().
int process_avc_selinux_context (auparse_state_t * au, const char * context)
Definition at line 831 of file auvirt.c.
References add_proof(), auparse_find_field(), auparse_first_record(), auparse_interpret_field(), event::avc_operation, event::avc_result, event::comm, event::context, copy_str(), ET_AVC, event_alloc(), event_free(), extract_virt_fields(), get_machine_id_by_seclevel(), get_seclevel(), list_append(), event::name, event::proof, event::seclevel, event::start, event::target, event::type, auparse_test::uid, event::uid, and event::uuid.
Referenced by process_avc_selinux().
int process_control_event (auparse_state_t * au)
Definition at line 630 of file auvirt.c.
References add_start_guest_event(), add_stop_guest_event(), and auparse_find_field().
Referenced by main().
int process_machine_id_event (auparse_state_t * au)
Definition at line 462 of file auvirt.c.
References add_proof(), auparse_find_field(), copy_str(), ET_MACHINE_ID, event_alloc(), event_free(), extract_virt_fields(), get_seclevel(), list_append(), auparse_test::name, event::seclevel, event::success, auparse_test::uid, and event::uuid.
Referenced by main().
int process_resource_event (auparse_state_t * au)
Definition at line 741 of file auvirt.c.
References add_resource(), auparse_find_field(), auparse_first_record(), auparse_interpret_field(), extract_virt_fields(), auparse_test::name, event::reason, auparse_test::res, event::res_type, event::success, auparse_test::uid, update_resource(), and event::uuid.
Referenced by main().
int process_shutdown (auparse_state_t * au)
Definition at line 1248 of file auvirt.c.
References add_proof(), list_node_t::data, event::end, ET_DOWN, ET_RES, ET_START, event_alloc(), event_free(), extract_virt_fields(), list_append(), list_node_t::prev, event::start, event::success, list_t::tail, event::type, auparse_test::uid, and event::uid.
Referenced by main().
int update_resource (auparse_state_t * au, const char * uuid, uid_t uid, time_t time, const char * name, int success, const char * reason, const char * res_type, const char * res)
Definition at line 707 of file auvirt.c.
References add_proof(), list_node_t::data, event::end, ET_RES, is_resource(), list_node_t::prev, event::res, event::res_type, event::start, event::success, list_t::tail, event::type, and event::uuid.
Referenced by process_resource_event().
void usage (FILE * output)
Definition at line 146 of file auvirt.c.
References usage().
Variable Documentation
list_t* events = NULL
Definition at line 100 of file auvirt.c.
Referenced by event_set().