audit: auparse/data_buf.h File Reference
data_buf.h File Reference
#include "config.h"
#include "private.h"
Data Structures
struct Databuf
Macros
#define DATABUF_FLAG_PRESERVE_HEAD (1 << 0)
#define DATABUF_FLAG_STRING (2 << 0)
Typedefs
typedef struct Databuf DataBuf
Functions
void databuf_print (DataBuf *db, int print_data, char *fmt,...) hidden
int databuf_init (DataBuf *db, size_t size, unsigned flags) hidden
void databuf_free (DataBuf *db) hidden
int databuf_append (DataBuf *db, const char *src, size_t src_size) hidden
int databuf_advance (DataBuf *db, size_t advance) hidden
int databuf_reset (DataBuf *db) hidden
Macro Definition Documentation
#define DATABUF_FLAG_PRESERVE_HEAD (1 << 0)
Definition at line 36 of file data_buf.h.
Referenced by auparse_init(), databuf_append(), databuf_print(), and databuf_reset().
#define DATABUF_FLAG_STRING (2 << 0)
Definition at line 37 of file data_buf.h.
Referenced by databuf_init(), and databuf_print().
Typedef Documentation
typedef struct Databuf DataBuf
Function Documentation
int databuf_advance (DataBuf * db, size_t advance)
Definition at line 279 of file data_buf.c.
References databuf_print(), DATABUF_VALIDATE, Databuf::len, MIN, and Databuf::offset.
int databuf_append (DataBuf * db, const char * src, size_t src_size)
Definition at line 205 of file data_buf.c.
References Databuf::alloc_ptr, Databuf::alloc_size, DATABUF_FLAG_PRESERVE_HEAD, databuf_print(), DATABUF_VALIDATE, Databuf::flags, Databuf::len, MAX, and Databuf::max_len.
Referenced by auparse_feed(), and auparse_init().
void databuf_free (DataBuf * db)
Definition at line 188 of file data_buf.c.
References Databuf::alloc_ptr, Databuf::alloc_size, DATABUF_VALIDATE, Databuf::len, Databuf::max_len, and Databuf::offset.
Referenced by auparse_destroy(), and auparse_init().
int databuf_init (DataBuf * db, size_t size, unsigned flags)
Definition at line 164 of file data_buf.c.
References Databuf::alloc_ptr, Databuf::alloc_size, DATABUF_FLAG_STRING, Databuf::flags, Databuf::len, Databuf::max_len, and Databuf::offset.
Referenced by auparse_init().
void databuf_print (DataBuf * db, int print_data, char * fmt, ...)
Definition at line 141 of file data_buf.c.
References Databuf::alloc_ptr, Databuf::alloc_size, DATABUF_FLAG_PRESERVE_HEAD, DATABUF_FLAG_STRING, Databuf::flags, Databuf::len, Databuf::max_len, and Databuf::offset.
Referenced by databuf_advance(), databuf_append(), and databuf_reset().
int databuf_reset (DataBuf * db)
Definition at line 303 of file data_buf.c.
References Databuf::alloc_size, DATABUF_FLAG_PRESERVE_HEAD, databuf_print(), Databuf::flags, Databuf::len, Databuf::max_len, MIN, and Databuf::offset.
Referenced by auparse_reset().