audit: auparse/data_buf.c File Reference
data_buf.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <stdarg.h>
#include <errno.h>
#include "data_buf.h"
Macros
#define MIN(a, b) (((a)<=(b))?(a):(b))
#define MAX(a, b) (((a)>=(b))?(a):(b))
#define DATABUF_VALIDATE(db)
Functions
void databuf_print (DataBuf *db, int print_data, char *fmt,...)
int databuf_init (DataBuf *db, size_t size, unsigned flags)
void databuf_free (DataBuf *db)
int databuf_append (DataBuf *db, const char *src, size_t src_size)
int databuf_advance (DataBuf *db, size_t advance)
int databuf_reset (DataBuf *db)
Macro Definition Documentation
#define DATABUF_VALIDATE (db)
Definition at line 72 of file data_buf.c.
Referenced by databuf_advance(), databuf_append(), and databuf_free().
#define MAX (a, b) (((a)>=(b))?(a):(b))
Definition at line 53 of file data_buf.c.
Referenced by databuf_append().
#define MIN (a, b) (((a)<=(b))?(a):(b))
Definition at line 49 of file data_buf.c.
Referenced by databuf_advance(), and databuf_reset().
Function Documentation
int databuf_advance (DataBuf * db, size_t advance)
Definition at line 279 of file data_buf.c.
References databuf_print(), DATABUF_VALIDATE, Databuf::len, MIN, and Databuf::offset.
int databuf_append (DataBuf * db, const char * src, size_t src_size)
Definition at line 205 of file data_buf.c.
References Databuf::alloc_ptr, Databuf::alloc_size, DATABUF_FLAG_PRESERVE_HEAD, databuf_print(), DATABUF_VALIDATE, Databuf::flags, Databuf::len, MAX, and Databuf::max_len.
Referenced by auparse_feed(), and auparse_init().
void databuf_free (DataBuf * db)
Definition at line 188 of file data_buf.c.
References Databuf::alloc_ptr, Databuf::alloc_size, DATABUF_VALIDATE, Databuf::len, Databuf::max_len, and Databuf::offset.
Referenced by auparse_destroy(), and auparse_init().
int databuf_init (DataBuf * db, size_t size, unsigned flags)
Definition at line 164 of file data_buf.c.
References Databuf::alloc_ptr, Databuf::alloc_size, DATABUF_FLAG_STRING, Databuf::flags, Databuf::len, Databuf::max_len, and Databuf::offset.
Referenced by auparse_init().
void databuf_print (DataBuf * db, int print_data, char * fmt, ...)
Definition at line 141 of file data_buf.c.
References Databuf::alloc_ptr, Databuf::alloc_size, DATABUF_FLAG_PRESERVE_HEAD, DATABUF_FLAG_STRING, Databuf::flags, Databuf::len, Databuf::max_len, and Databuf::offset.
Referenced by databuf_advance(), databuf_append(), and databuf_reset().
int databuf_reset (DataBuf * db)
Definition at line 303 of file data_buf.c.
References Databuf::alloc_size, DATABUF_FLAG_PRESERVE_HEAD, databuf_print(), Databuf::flags, Databuf::len, Databuf::max_len, MIN, and Databuf::offset.
Referenced by auparse_reset().