audit: lib/deprecated.c File Reference
deprecated.c File Reference
#include "config.h"
#include <errno.h>
#include <string.h>
#include <pwd.h>
#include <grp.h>
#include <ctype.h>
#include <stdlib.h>
#include <unistd.h>
#include "libaudit.h"
#include "private.h"
Functions
int audit_send_user_message (int fd, int type, hide_t hide_error, const char *message)
Function Documentation
int audit_send_user_message (int fd, int type, hide_t hide_error, const char * message)
Definition at line 41 of file deprecated.c.
References AUDIT_FIRST_USER_MSG, AUDIT_LAST_USER_MSG, audit_send(), and HIDE_IT.
Referenced by audit_log_acct_message(), audit_log_semanage_message(), audit_log_user_avc_message(), audit_log_user_comm_message(), audit_log_user_command(), and audit_log_user_message().