audit: auparse/ellist.h File Reference
ellist.h File Reference
#include "config.h"
#include "private.h"
#include "auparse-defs.h"
#include <sys/types.h>
#include "nvlist.h"
Data Structures
struct event_list_t
Functions
void aup_list_create (event_list_t *l) hidden
void aup_list_clear (event_list_t *l) hidden
rnode * aup_list_next (event_list_t *l) hidden
int aup_list_append (event_list_t *l, char *record, int list_idx, unsigned int line_number) hidden
int aup_list_set_event (event_list_t *l, au_event_t *e) hidden
rnode * aup_list_find_rec (event_list_t *l, int i) hidden
rnode * aup_list_goto_rec (event_list_t *l, int i) hidden
rnode * aup_list_find_rec_range (event_list_t *l, int low, int high) hidden
int aup_list_first_field (event_list_t *l) hidden
Function Documentation
int aup_list_append (event_list_t * l, char * record, int list_idx, unsigned int line_number)
Definition at line 277 of file ellist.c.
References _rnode::a0, _rnode::a1, event_list_t::cnt, event_list_t::cur, event_list_t::head, _rnode::item, _rnode::line_number, _rnode::list_idx, _rnode::machine, _rnode::next, _rnode::nv, nvlist_create(), _rnode::record, _rnode::syscall, and _rnode::type.
Referenced by auparse_next_event().
void aup_list_clear (event_list_t * l)
Definition at line 318 of file ellist.c.
References event_list_t::cnt, event_list_t::cur, event_list_t::e, event_list_t::head, au_event_t::host, au_event_t::milli, _rnode::next, _rnode::nv, nvlist_clear(), _rnode::record, au_event_t::sec, and au_event_t::serial.
Referenced by auparse_destroy(), auparse_next_event(), and auparse_reset().
void aup_list_create (event_list_t * l)
Definition at line 34 of file ellist.c.
References event_list_t::cnt, event_list_t::cur, event_list_t::e, event_list_t::head, au_event_t::host, au_event_t::milli, au_event_t::sec, and au_event_t::serial.
Referenced by auparse_init().
rnode* aup_list_find_rec (event_list_t * l, int i)
Definition at line 372 of file ellist.c.
References event_list_t::cur, event_list_t::head, _rnode::next, and _rnode::type.
rnode* aup_list_find_rec_range (event_list_t * l, int low, int high)
Definition at line 402 of file ellist.c.
References event_list_t::cur, event_list_t::head, _rnode::next, and _rnode::type.
int aup_list_first_field (event_list_t * l)
Definition at line 420 of file ellist.c.
References event_list_t::cur, and _rnode::nv.
Referenced by auparse_find_field_next(), auparse_first_field(), auparse_first_record(), and auparse_next_event().
rnode* aup_list_goto_rec (event_list_t * l, int i)
Definition at line 387 of file ellist.c.
References event_list_t::cur, event_list_t::head, _rnode::item, and _rnode::next.
Referenced by auparse_goto_record_num().
rnode* aup_list_next (event_list_t * l)
Definition at line 58 of file ellist.c.
References event_list_t::cur, and _rnode::next.
Referenced by auparse_find_field_next(), and auparse_next_record().
int aup_list_set_event (event_list_t * l, au_event_t * e)
Definition at line 359 of file ellist.c.
References event_list_t::e, au_event_t::host, au_event_t::milli, au_event_t::sec, and au_event_t::serial.
Referenced by auparse_next_event().