audit: src/libev/ev.h File Reference
ev.h File Reference
#include <string.h>
#include <signal.h>
#include <sys/stat.h>
Data Structures
struct ev_watcher
struct ev_watcher_list
struct ev_watcher_time
struct ev_io
struct ev_timer
struct ev_periodic
struct ev_signal
struct ev_child
struct ev_stat
struct ev_idle
struct ev_prepare
struct ev_check
struct ev_fork
struct ev_cleanup
struct ev_embed
struct ev_async
union ev_any_watcher
Macros
#define EV_CPP(x)
#define EV_THROW
#define EV_COMPAT3 1
#define EV_FEATURES 0x7f
#define EV_FEATURE_CODE ((EV_FEATURES) & 1)
#define EV_FEATURE_DATA ((EV_FEATURES) & 2)
#define EV_FEATURE_CONFIG ((EV_FEATURES) & 4)
#define EV_FEATURE_API ((EV_FEATURES) & 8)
#define EV_FEATURE_WATCHERS ((EV_FEATURES) & 16)
#define EV_FEATURE_BACKENDS ((EV_FEATURES) & 32)
#define EV_FEATURE_OS ((EV_FEATURES) & 64)
#define EV_MINPRI (EV_FEATURE_CONFIG ? -2 : 0)
#define EV_MAXPRI (EV_FEATURE_CONFIG ? +2 : 0)
#define EV_MULTIPLICITY EV_FEATURE_CONFIG
#define EV_PERIODIC_ENABLE EV_FEATURE_WATCHERS
#define EV_STAT_ENABLE EV_FEATURE_WATCHERS
#define EV_PREPARE_ENABLE EV_FEATURE_WATCHERS
#define EV_CHECK_ENABLE EV_FEATURE_WATCHERS
#define EV_IDLE_ENABLE EV_FEATURE_WATCHERS
#define EV_FORK_ENABLE EV_FEATURE_WATCHERS
#define EV_CLEANUP_ENABLE EV_FEATURE_WATCHERS
#define EV_SIGNAL_ENABLE EV_FEATURE_WATCHERS
#define EV_CHILD_ENABLE EV_FEATURE_WATCHERS
#define EV_ASYNC_ENABLE EV_FEATURE_WATCHERS
#define EV_EMBED_ENABLE EV_FEATURE_WATCHERS
#define EV_WALK_ENABLE 0 /* not yet */
#define EV_ATOMIC_T sig_atomic_t volatile
#define EV_P struct ev_loop *loop /* a loop as sole parameter in a declaration */
#define EV_P_ EV_P, /* a loop as first of multiple parameters */
#define EV_A loop /* a loop as sole argument to a function call */
#define EV_A_ EV_A, /* a loop as first of multiple arguments */
#define EV_DEFAULT_UC ev_default_loop_uc_ () /* the default loop, if initialised, as sole arg */
#define EV_DEFAULT_UC_ EV_DEFAULT_UC, /* the default loop as first of multiple arguments */
#define EV_DEFAULT ev_default_loop (0) /* the default loop as sole arg */
#define EV_DEFAULT_ EV_DEFAULT, /* the default loop as first of multiple arguments */
#define EV_INLINE static
#define EV_API_DECL extern
#define EV_PROTOTYPES 1
#define EV_VERSION_MAJOR 4
#define EV_VERSION_MINOR 20
#define EV_COMMON void *data;
#define EV_CB_DECLARE(type) void (*cb)(EV_P_ struct type *w, int revents);
#define EV_CB_INVOKE(watcher, revents) (watcher)->cb (EV_A_ (watcher), (revents))
#define EV_CB(type, name) void name (EV_P_ struct ev_ ## type *w, int revents)
#define EV_DECL_PRIORITY int priority;
#define EV_WATCHER(type)
#define EV_WATCHER_LIST(type)
#define EV_WATCHER_TIME(type)
#define ev_async_pending(w) (+(w)->sent)
#define ev_init(ev, cb_)
#define ev_io_set(ev, fd_, events_) do { (ev)->fd = (fd_); (ev)->events = (events_) | EV__IOFDSET; } while (0)
#define ev_timer_set(ev, after_, repeat_) do { ((ev_watcher_time *)(ev))->at = (after_); (ev)->repeat = (repeat_); } while (0)
#define ev_periodic_set(ev, ofs_, ival_, rcb_) do { (ev)->offset = (ofs_); (ev)->interval = (ival_); (ev)->reschedule_cb = (rcb_); } while (0)
#define ev_signal_set(ev, signum_) do { (ev)->signum = (signum_); } while (0)
#define ev_child_set(ev, pid_, trace_) do { (ev)->pid = (pid_); (ev)->flags = !!(trace_); } while (0)
#define ev_stat_set(ev, path_, interval_) do { (ev)->path = (path_); (ev)->interval = (interval_); (ev)->wd = -2; } while (0)
#define ev_idle_set(ev) /* nop, yes, this is a serious in-joke */
#define ev_prepare_set(ev) /* nop, yes, this is a serious in-joke */
#define ev_check_set(ev) /* nop, yes, this is a serious in-joke */
#define ev_embed_set(ev, other_) do { (ev)->other = (other_); } while (0)
#define ev_fork_set(ev) /* nop, yes, this is a serious in-joke */
#define ev_cleanup_set(ev) /* nop, yes, this is a serious in-joke */
#define ev_async_set(ev) /* nop, yes, this is a serious in-joke */
#define ev_io_init(ev, cb, fd, events) do { ev_init ((ev), (cb)); ev_io_set ((ev),(fd),(events)); } while (0)
#define ev_timer_init(ev, cb, after, repeat) do { ev_init ((ev), (cb)); ev_timer_set ((ev),(after),(repeat)); } while (0)
#define ev_periodic_init(ev, cb, ofs, ival, rcb) do { ev_init ((ev), (cb)); ev_periodic_set ((ev),(ofs),(ival),(rcb)); } while (0)
#define ev_signal_init(ev, cb, signum) do { ev_init ((ev), (cb)); ev_signal_set ((ev), (signum)); } while (0)
#define ev_child_init(ev, cb, pid, trace) do { ev_init ((ev), (cb)); ev_child_set ((ev),(pid),(trace)); } while (0)
#define ev_stat_init(ev, cb, path, interval) do { ev_init ((ev), (cb)); ev_stat_set ((ev),(path),(interval)); } while (0)
#define ev_idle_init(ev, cb) do { ev_init ((ev), (cb)); ev_idle_set ((ev)); } while (0)
#define ev_prepare_init(ev, cb) do { ev_init ((ev), (cb)); ev_prepare_set ((ev)); } while (0)
#define ev_check_init(ev, cb) do { ev_init ((ev), (cb)); ev_check_set ((ev)); } while (0)
#define ev_embed_init(ev, cb, other) do { ev_init ((ev), (cb)); ev_embed_set ((ev),(other)); } while (0)
#define ev_fork_init(ev, cb) do { ev_init ((ev), (cb)); ev_fork_set ((ev)); } while (0)
#define ev_cleanup_init(ev, cb) do { ev_init ((ev), (cb)); ev_cleanup_set ((ev)); } while (0)
#define ev_async_init(ev, cb) do { ev_init ((ev), (cb)); ev_async_set ((ev)); } while (0)
#define ev_is_pending(ev) (0 + ((ev_watcher *)(void *)(ev))->pending) /* ro, true when watcher is waiting for callback invocation */
#define ev_is_active(ev) (0 + ((ev_watcher *)(void *)(ev))->active) /* ro, true when the watcher has been started */
#define ev_cb_(ev) (ev)->cb /* rw */
#define ev_cb(ev) (memmove (&ev_cb_ (ev), &((ev_watcher *)(ev))->cb, sizeof (ev_cb_ (ev))), (ev)->cb)
#define ev_priority(ev) (+(((ev_watcher *)(void *)(ev))->priority))
#define ev_set_priority(ev, pri) ((ev_watcher *)(void *)(ev))->priority = (pri)
#define ev_periodic_at(ev) (+((ev_watcher_time *)(ev))->at)
#define ev_set_cb(ev, cb_) (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
#define EVLOOP_NONBLOCK EVRUN_NOWAIT
#define EVLOOP_ONESHOT EVRUN_ONCE
#define EVUNLOOP_CANCEL EVBREAK_CANCEL
#define EVUNLOOP_ONE EVBREAK_ONE
#define EVUNLOOP_ALL EVBREAK_ALL
Typedefs
typedef double ev_tstamp
typedef struct ev_watcher ev_watcher
typedef struct ev_watcher_list ev_watcher_list
typedef struct ev_watcher_time ev_watcher_time
typedef struct ev_io ev_io
typedef struct ev_timer ev_timer
typedef struct ev_periodic ev_periodic
typedef struct ev_signal ev_signal
typedef struct ev_child ev_child
typedef struct stat ev_statdata
typedef struct ev_stat ev_stat
typedef struct ev_idle ev_idle
typedef struct ev_prepare ev_prepare
typedef struct ev_check ev_check
typedef struct ev_fork ev_fork
typedef struct ev_cleanup ev_cleanup
typedef struct ev_embed ev_embed
typedef struct ev_async ev_async
typedef void(* ev_loop_callback)(EV_P)
Enumerations
enum {
EV_UNDEF = (int)0xFFFFFFFF, EV_NONE = 0x00, EV_READ = 0x01, EV_WRITE = 0x02,
EV__IOFDSET = 0x80, EV_IO = EV_READ, EV_TIMER = 0x00000100, EV_TIMEOUT = EV_TIMER,
EV_PERIODIC = 0x00000200, EV_SIGNAL = 0x00000400, EV_CHILD = 0x00000800, EV_STAT = 0x00001000,
EV_IDLE = 0x00002000, EV_PREPARE = 0x00004000, EV_CHECK = 0x00008000, EV_EMBED = 0x00010000,
EV_FORK = 0x00020000, EV_CLEANUP = 0x00040000, EV_ASYNC = 0x00080000, EV_CUSTOM = 0x01000000,
EV_ERROR = (int)0x80000000
}
enum {
EVFLAG_AUTO = 0x00000000U, EVFLAG_NOENV = 0x01000000U, EVFLAG_FORKCHECK = 0x02000000U, EVFLAG_NOINOTIFY = 0x00100000U,
EVFLAG_NOSIGFD = 0, EVFLAG_SIGNALFD = 0x00200000U, EVFLAG_NOSIGMASK = 0x00400000U
}
enum {
EVBACKEND_SELECT = 0x00000001U, EVBACKEND_POLL = 0x00000002U, EVBACKEND_EPOLL = 0x00000004U, EVBACKEND_KQUEUE = 0x00000008U,
EVBACKEND_DEVPOLL = 0x00000010U, EVBACKEND_PORT = 0x00000020U, EVBACKEND_ALL = 0x0000003FU, EVBACKEND_MASK = 0x0000FFFFU
}
enum { EVRUN_NOWAIT = 1, EVRUN_ONCE = 2 }
enum { EVBREAK_CANCEL = 0, EVBREAK_ONE = 1, EVBREAK_ALL = 2 }
Functions
EV_API_DECL int ev_version_major (void) EV_THROW
EV_API_DECL int ev_version_minor (void) EV_THROW
EV_API_DECL unsigned int ev_supported_backends (void) EV_THROW
EV_API_DECL unsigned int ev_recommended_backends (void) EV_THROW
EV_API_DECL unsigned int ev_embeddable_backends (void) EV_THROW
EV_API_DECL ev_tstamp ev_time (void) EV_THROW
EV_API_DECL void ev_sleep (ev_tstamp delay) EV_THROW
EV_API_DECL void ev_set_allocator (void *(*cb)(void *ptr, long size) EV_THROW) EV_THROW
EV_API_DECL void ev_set_syserr_cb (void(*cb)(const char *msg) EV_THROW) EV_THROW
EV_API_DECL struct ev_loop * ev_default_loop (unsigned int flags EV_CPP(=0)) EV_THROW
EV_INLINE struct ev_loop * ev_default_loop_uc_ (void) EV_THROW
EV_INLINE int ev_is_default_loop (EV_P) EV_THROW
EV_API_DECL struct ev_loop * ev_loop_new (unsigned int flags EV_CPP(=0)) EV_THROW
EV_API_DECL ev_tstamp ev_now (EV_P) EV_THROW
EV_API_DECL void ev_loop_destroy (EV_P)
EV_API_DECL void ev_loop_fork (EV_P) EV_THROW
EV_API_DECL unsigned int ev_backend (EV_P) EV_THROW
EV_API_DECL void ev_now_update (EV_P) EV_THROW
EV_API_DECL int ev_run (EV_P_ int flags EV_CPP(=0))
EV_API_DECL void ev_break (EV_P_ int how EV_CPP(=EVBREAK_ONE)) EV_THROW
EV_API_DECL void ev_ref (EV_P) EV_THROW
EV_API_DECL void ev_unref (EV_P) EV_THROW
EV_API_DECL void ev_once (EV_P_ int fd, int events, ev_tstamp timeout, void(*cb)(int revents, void *arg), void *arg) EV_THROW
EV_API_DECL unsigned int ev_iteration (EV_P) EV_THROW
EV_API_DECL unsigned int ev_depth (EV_P) EV_THROW
EV_API_DECL void ev_verify (EV_P) EV_THROW
EV_API_DECL void ev_set_io_collect_interval (EV_P_ ev_tstamp interval) EV_THROW
EV_API_DECL void ev_set_timeout_collect_interval (EV_P_ ev_tstamp interval) EV_THROW
EV_API_DECL void ev_set_userdata (EV_P_ void *data) EV_THROW
EV_API_DECL void * ev_userdata (EV_P) EV_THROW
EV_API_DECL void ev_set_invoke_pending_cb (EV_P_ ev_loop_callback invoke_pending_cb) EV_THROW
EV_API_DECL void ev_set_loop_release_cb (EV_P_ void(*release)(EV_P) EV_THROW, void(*acquire)(EV_P) EV_THROW) EV_THROW
EV_API_DECL unsigned int ev_pending_count (EV_P) EV_THROW
EV_API_DECL void ev_invoke_pending (EV_P)
EV_API_DECL void ev_suspend (EV_P) EV_THROW
EV_API_DECL void ev_resume (EV_P) EV_THROW
EV_API_DECL void ev_feed_event (EV_P_ void *w, int revents) EV_THROW
EV_API_DECL void ev_feed_fd_event (EV_P_ int fd, int revents) EV_THROW
EV_API_DECL void ev_feed_signal (int signum) EV_THROW
EV_API_DECL void ev_feed_signal_event (EV_P_ int signum) EV_THROW
EV_API_DECL void ev_invoke (EV_P_ void *w, int revents)
EV_API_DECL int ev_clear_pending (EV_P_ void *w) EV_THROW
EV_API_DECL void ev_io_start (EV_P_ ev_io *w) EV_THROW
EV_API_DECL void ev_io_stop (EV_P_ ev_io *w) EV_THROW
EV_API_DECL void ev_timer_start (EV_P_ ev_timer *w) EV_THROW
EV_API_DECL void ev_timer_stop (EV_P_ ev_timer *w) EV_THROW
EV_API_DECL void ev_timer_again (EV_P_ ev_timer *w) EV_THROW
EV_API_DECL ev_tstamp ev_timer_remaining (EV_P_ ev_timer *w) EV_THROW
EV_API_DECL void ev_periodic_start (EV_P_ ev_periodic *w) EV_THROW
EV_API_DECL void ev_periodic_stop (EV_P_ ev_periodic *w) EV_THROW
EV_API_DECL void ev_periodic_again (EV_P_ ev_periodic *w) EV_THROW
EV_API_DECL void ev_signal_start (EV_P_ ev_signal *w) EV_THROW
EV_API_DECL void ev_signal_stop (EV_P_ ev_signal *w) EV_THROW
EV_API_DECL void ev_child_start (EV_P_ ev_child *w) EV_THROW
EV_API_DECL void ev_child_stop (EV_P_ ev_child *w) EV_THROW
EV_API_DECL void ev_stat_start (EV_P_ ev_stat *w) EV_THROW
EV_API_DECL void ev_stat_stop (EV_P_ ev_stat *w) EV_THROW
EV_API_DECL void ev_stat_stat (EV_P_ ev_stat *w) EV_THROW
EV_API_DECL void ev_idle_start (EV_P_ ev_idle *w) EV_THROW
EV_API_DECL void ev_idle_stop (EV_P_ ev_idle *w) EV_THROW
EV_API_DECL void ev_prepare_start (EV_P_ ev_prepare *w) EV_THROW
EV_API_DECL void ev_prepare_stop (EV_P_ ev_prepare *w) EV_THROW
EV_API_DECL void ev_check_start (EV_P_ ev_check *w) EV_THROW
EV_API_DECL void ev_check_stop (EV_P_ ev_check *w) EV_THROW
EV_API_DECL void ev_fork_start (EV_P_ ev_fork *w) EV_THROW
EV_API_DECL void ev_fork_stop (EV_P_ ev_fork *w) EV_THROW
EV_API_DECL void ev_cleanup_start (EV_P_ ev_cleanup *w) EV_THROW
EV_API_DECL void ev_cleanup_stop (EV_P_ ev_cleanup *w) EV_THROW
EV_API_DECL void ev_embed_start (EV_P_ ev_embed *w) EV_THROW
EV_API_DECL void ev_embed_stop (EV_P_ ev_embed *w) EV_THROW
EV_API_DECL void ev_embed_sweep (EV_P_ ev_embed *w) EV_THROW
EV_API_DECL void ev_async_start (EV_P_ ev_async *w) EV_THROW
EV_API_DECL void ev_async_stop (EV_P_ ev_async *w) EV_THROW
EV_API_DECL void ev_async_send (EV_P_ ev_async *w) EV_THROW
EV_INLINE void ev_loop (EV_P_ int flags)
EV_INLINE void ev_unloop (EV_P_ int how)
EV_INLINE void ev_default_destroy (void)
EV_INLINE void ev_default_fork (void)
EV_INLINE unsigned int ev_loop_count (EV_P)
EV_INLINE unsigned int ev_loop_depth (EV_P)
EV_INLINE void ev_loop_verify (EV_P)
Macro Definition Documentation
#define EV_A loop /* a loop as sole argument to a function call */
Definition at line 175 of file ev.h.
Referenced by epoll_fork(), ev_async_start(), ev_cleanup_start(), ev_cleanup_stop(), ev_default_loop(), ev_feed_signal(), ev_feed_signal_event(), ev_is_default_loop(), ev_loop_count(), ev_loop_depth(), ev_loop_destroy(), ev_loop_new(), ev_loop_verify(), ev_resume(), ev_run(), ev_signal_start(), ev_start(), ev_stat_start(), ev_stat_stop(), ev_stop(), ev_suspend(), event_pending(), loop_fork(), and time_update().
#define EV_A_ EV_A, /* a loop as first of multiple arguments */
Definition at line 176 of file ev.h.
Referenced by child_reap(), ev_async_send(), ev_async_start(), ev_async_stop(), ev_check_start(), ev_check_stop(), ev_child_start(), ev_child_stop(), ev_cleanup_start(), ev_cleanup_stop(), ev_default_loop(), ev_embed_start(), ev_embed_stop(), ev_feed_fd_event(), ev_feed_signal(), ev_feed_signal_event(), ev_fork_start(), ev_fork_stop(), ev_idle_start(), ev_idle_stop(), ev_io_start(), ev_io_stop(), ev_loop(), ev_loop_destroy(), ev_loop_new(), ev_now_update(), ev_once(), ev_periodic_again(), ev_periodic_start(), ev_periodic_stop(), ev_prepare_start(), ev_prepare_stop(), ev_resume(), ev_run(), ev_signal_start(), ev_signal_stop(), ev_start(), ev_stat_start(), ev_stat_stop(), ev_timer_again(), ev_timer_start(), ev_timer_stop(), ev_unloop(), ev_verify(), event_active(), event_add(), event_base_loop(), event_base_loopexit(), event_base_once(), event_del(), fd_event(), fd_event_nocheck(), fd_kill(), fd_reify(), feed_reverse_done(), idle_reify(), loop_fork(), periodics_reify(), queue_events(), time_update(), and timers_reify().
#define EV_API_DECL extern
Definition at line 203 of file ev.h.
#define EV_ASYNC_ENABLE EV_FEATURE_WATCHERS
Definition at line 133 of file ev.h.
#define ev_async_init (ev, cb) do { ev_init ((ev), (cb)); ev_async_set ((ev)); } while (0)
Definition at line 719 of file ev.h.
#define ev_async_pending (w) (+(w)->sent)
Definition at line 464 of file ev.h.
#define ev_async_set (ev) /* nop, yes, this is a serious in-joke */
Definition at line 705 of file ev.h.
#define EV_ATOMIC_T sig_atomic_t volatile
Definition at line 159 of file ev.h.
#define EV_CB (type, name) void name (EV_P_ struct ev_ ## type *w, int revents)
Definition at line 256 of file ev.h.
#define ev_cb (ev) (memmove (&ev_cb_ (ev), &((ev_watcher *)(ev))->cb, sizeof (ev_cb_ (ev))), (ev)->cb)
Definition at line 725 of file ev.h.
#define ev_cb_ (ev) (ev)->cb /* rw */
Definition at line 724 of file ev.h.
#define EV_CB_DECLARE (type) void (*cb)(EV_P_ struct type *w, int revents);
Definition at line 249 of file ev.h.
#define EV_CB_INVOKE (watcher, revents) (watcher)->cb (EV_A_ (watcher), (revents))
Definition at line 252 of file ev.h.
Referenced by ev_invoke(), and ev_invoke_pending().
#define EV_CHECK_ENABLE EV_FEATURE_WATCHERS
Definition at line 105 of file ev.h.
#define ev_check_init (ev, cb) do { ev_init ((ev), (cb)); ev_check_set ((ev)); } while (0)
Definition at line 715 of file ev.h.
#define ev_check_set (ev) /* nop, yes, this is a serious in-joke */
Definition at line 701 of file ev.h.
#define EV_CHILD_ENABLE EV_FEATURE_WATCHERS
Definition at line 128 of file ev.h.
#define ev_child_init (ev, cb, pid, trace) do { ev_init ((ev), (cb)); ev_child_set ((ev),(pid),(trace)); } while (0)
Definition at line 711 of file ev.h.
#define ev_child_set (ev, pid_, trace_) do { (ev)->pid = (pid_); (ev)->flags = !!(trace_); } while (0)
Definition at line 697 of file ev.h.
#define EV_CLEANUP_ENABLE EV_FEATURE_WATCHERS
Definition at line 117 of file ev.h.
#define ev_cleanup_init (ev, cb) do { ev_init ((ev), (cb)); ev_cleanup_set ((ev)); } while (0)
Definition at line 718 of file ev.h.
#define ev_cleanup_set (ev) /* nop, yes, this is a serious in-joke */
Definition at line 704 of file ev.h.
#define EV_COMMON void *data;
Definition at line 245 of file ev.h.
#define EV_COMPAT3 1
Definition at line 61 of file ev.h.
#define EV_CPP (x)
Definition at line 51 of file ev.h.
#define EV_DECL_PRIORITY int priority;
Definition at line 278 of file ev.h.
#define EV_DEFAULT ev_default_loop (0) /* the default loop as sole arg */
Definition at line 179 of file ev.h.
Referenced by ev_default_destroy(), and ev_default_fork().
#define EV_DEFAULT_ EV_DEFAULT, /* the default loop as first of multiple arguments */
Definition at line 180 of file ev.h.
#define EV_DEFAULT_UC ev_default_loop_uc_ () /* the default loop, if initialised, as sole arg */
Definition at line 177 of file ev.h.
Referenced by ev_is_default_loop().
#define EV_DEFAULT_UC_ EV_DEFAULT_UC, /* the default loop as first of multiple arguments */
Definition at line 178 of file ev.h.
#define EV_EMBED_ENABLE EV_FEATURE_WATCHERS
Definition at line 137 of file ev.h.
#define ev_embed_init (ev, cb, other) do { ev_init ((ev), (cb)); ev_embed_set ((ev),(other)); } while (0)
Definition at line 716 of file ev.h.
#define ev_embed_set (ev, other_) do { (ev)->other = (other_); } while (0)
Definition at line 702 of file ev.h.
#define EV_FEATURE_API ((EV_FEATURES) & 8)
Definition at line 75 of file ev.h.
#define EV_FEATURE_BACKENDS ((EV_FEATURES) & 32)
Definition at line 77 of file ev.h.
#define EV_FEATURE_CODE ((EV_FEATURES) & 1)
Definition at line 72 of file ev.h.
#define EV_FEATURE_CONFIG ((EV_FEATURES) & 4)
Definition at line 74 of file ev.h.
#define EV_FEATURE_DATA ((EV_FEATURES) & 2)
Definition at line 73 of file ev.h.
#define EV_FEATURE_OS ((EV_FEATURES) & 64)
Definition at line 78 of file ev.h.
#define EV_FEATURE_WATCHERS ((EV_FEATURES) & 16)
Definition at line 76 of file ev.h.
#define EV_FEATURES 0x7f
Definition at line 68 of file ev.h.
#define EV_FORK_ENABLE EV_FEATURE_WATCHERS
Definition at line 113 of file ev.h.
#define ev_fork_init (ev, cb) do { ev_init ((ev), (cb)); ev_fork_set ((ev)); } while (0)
Definition at line 717 of file ev.h.
Referenced by ev_embed_start().
#define ev_fork_set (ev) /* nop, yes, this is a serious in-joke */
Definition at line 703 of file ev.h.
#define EV_IDLE_ENABLE EV_FEATURE_WATCHERS
Definition at line 109 of file ev.h.
#define ev_idle_init (ev, cb) do { ev_init ((ev), (cb)); ev_idle_set ((ev)); } while (0)
Definition at line 713 of file ev.h.
#define ev_idle_set (ev) /* nop, yes, this is a serious in-joke */
Definition at line 699 of file ev.h.
#define ev_init (ev, cb_)
Value:
do {            \
  ((ev_watcher *)(void *)(ev))->active  =   \
  ((ev_watcher *)(void *)(ev))->pending = 0;    \
  ev_set_priority ((ev), 0);            \
  ev_set_cb ((ev), cb_);            \
} while (0)
Definition at line 686 of file ev.h.
Referenced by ev_once(), and event_set().
#define EV_INLINE static
Definition at line 197 of file ev.h.
#define ev_io_init (ev, cb, fd, events) do { ev_init ((ev), (cb)); ev_io_set ((ev),(fd),(events)); } while (0)
Definition at line 707 of file ev.h.
Referenced by auditd_tcp_listen_init(), ev_embed_start(), ev_signal_start(), and main().
#define ev_io_set (ev, fd_, events_) do { (ev)->fd = (fd_); (ev)->events = (events_) | EV__IOFDSET; } while (0)
Definition at line 693 of file ev.h.
Referenced by ev_once(), and event_add().
#define ev_is_active (ev) (0 + ((ev_watcher *)(void *)(ev))->active) /* ro, true when the watcher has been started */
Definition at line 722 of file ev.h.
Referenced by ev_async_start(), ev_async_stop(), ev_check_start(), ev_check_stop(), ev_child_start(), ev_child_stop(), ev_cleanup_start(), ev_cleanup_stop(), ev_embed_start(), ev_embed_stop(), ev_fork_start(), ev_fork_stop(), ev_idle_start(), ev_idle_stop(), ev_io_start(), ev_io_stop(), ev_loop_destroy(), ev_periodic_start(), ev_periodic_stop(), ev_prepare_start(), ev_prepare_stop(), ev_run(), ev_signal_start(), ev_signal_stop(), ev_stat_start(), ev_stat_stop(), ev_timer_again(), ev_timer_remaining(), ev_timer_start(), ev_timer_stop(), event_add(), event_del(), event_pending(), and loop_fork().
#define ev_is_pending (ev) (0 + ((ev_watcher *)(void *)(ev))->pending) /* ro, true when watcher is waiting for callback invocation */
Definition at line 721 of file ev.h.
Referenced by event_pending().
#define EV_MAXPRI (EV_FEATURE_CONFIG ? +2 : 0)
Definition at line 85 of file ev.h.
Referenced by child_reap(), ev_default_loop(), ev_signal_start(), and pri_adjust().
#define EV_MINPRI (EV_FEATURE_CONFIG ? -2 : 0)
Definition at line 82 of file ev.h.
Referenced by ev_embed_start(), and pri_adjust().
#define EV_MULTIPLICITY EV_FEATURE_CONFIG
Definition at line 89 of file ev.h.
#define EV_P struct ev_loop *loop /* a loop as sole parameter in a declaration */
Definition at line 173 of file ev.h.
Referenced by ev_default_loop(), ev_embed_start(), ev_feed_signal(), and ev_loop_new().
#define EV_P_ EV_P, /* a loop as first of multiple parameters */
Definition at line 174 of file ev.h.
#define ev_periodic_at (ev) (+((ev_watcher_time *)(ev))->at)
Definition at line 735 of file ev.h.
#define EV_PERIODIC_ENABLE EV_FEATURE_WATCHERS
Definition at line 93 of file ev.h.
#define ev_periodic_init (ev, cb, ofs, ival, rcb) do { ev_init ((ev), (cb)); ev_periodic_set ((ev),(ofs),(ival),(rcb)); } while (0)
Definition at line 709 of file ev.h.
Referenced by auditd_tcp_listen_init().
#define ev_periodic_set (ev, ofs_, ival_, rcb_) do { (ev)->offset = (ofs_); (ev)->interval = (ival_); (ev)->reschedule_cb = (rcb_); } while (0)
Definition at line 695 of file ev.h.
#define EV_PREPARE_ENABLE EV_FEATURE_WATCHERS
Definition at line 101 of file ev.h.
#define ev_prepare_init (ev, cb) do { ev_init ((ev), (cb)); ev_prepare_set ((ev)); } while (0)
Definition at line 714 of file ev.h.
Referenced by ev_embed_start().
#define ev_prepare_set (ev) /* nop, yes, this is a serious in-joke */
Definition at line 700 of file ev.h.
#define ev_priority (ev) (+(((ev_watcher *)(void *)(ev))->priority))
Definition at line 731 of file ev.h.
Referenced by ev_embed_start(), ev_stat_start(), and pri_adjust().
#define EV_PROTOTYPES 1
Definition at line 208 of file ev.h.
#define ev_set_cb (ev, cb_) (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
Definition at line 738 of file ev.h.
#define ev_set_priority (ev, pri) ((ev_watcher *)(void *)(ev))->priority = (pri)
Definition at line 732 of file ev.h.
Referenced by child_reap(), ev_default_loop(), ev_embed_start(), ev_signal_start(), ev_stat_start(), and pri_adjust().
#define EV_SIGNAL_ENABLE EV_FEATURE_WATCHERS
Definition at line 121 of file ev.h.
#define ev_signal_init (ev, cb, signum) do { ev_init ((ev), (cb)); ev_signal_set ((ev), (signum)); } while (0)
Definition at line 710 of file ev.h.
Referenced by ev_default_loop(), and main().
#define ev_signal_set (ev, signum_) do { (ev)->signum = (signum_); } while (0)
Definition at line 696 of file ev.h.
Referenced by event_add().
#define EV_STAT_ENABLE EV_FEATURE_WATCHERS
Definition at line 97 of file ev.h.
#define ev_stat_init (ev, cb, path, interval) do { ev_init ((ev), (cb)); ev_stat_set ((ev),(path),(interval)); } while (0)
Definition at line 712 of file ev.h.
#define ev_stat_set (ev, path_, interval_) do { (ev)->path = (path_); (ev)->interval = (interval_); (ev)->wd = -2; } while (0)
Definition at line 698 of file ev.h.
#define EV_THROW
Definition at line 52 of file ev.h.
#define ev_timer_init (ev, cb, after, repeat) do { ev_init ((ev), (cb)); ev_timer_set ((ev),(after),(repeat)); } while (0)
Definition at line 708 of file ev.h.
Referenced by ev_stat_start().
#define ev_timer_set (ev, after_, repeat_) do { ((ev_watcher_time *)(ev))->at = (after_); (ev)->repeat = (repeat_); } while (0)
Definition at line 694 of file ev.h.
Referenced by ev_once().
#define EV_VERSION_MAJOR 4
Definition at line 213 of file ev.h.
Referenced by ev_version_major(), and event_get_version().
#define EV_VERSION_MINOR 20
Definition at line 214 of file ev.h.
Referenced by ev_version_minor(), and event_get_version().
#define EV_WALK_ENABLE 0 /* not yet */
Definition at line 141 of file ev.h.
#define EV_WATCHER (type)
Value:
int active; /* private */           \
  int pending; /* private */            \
  EV_DECL_PRIORITY /* private */        \
  EV_COMMON /* rw */                \
  EV_CB_DECLARE (type) /* private */
Definition at line 282 of file ev.h.
#define EV_WATCHER_LIST (type)
Value:
EV_WATCHER (type)               \
  struct ev_watcher_list *next; /* private */
Definition at line 289 of file ev.h.
#define EV_WATCHER_TIME (type)
Value:
EV_WATCHER (type)               \
  ev_tstamp at;     /* private */
Definition at line 293 of file ev.h.
#define EVLOOP_NONBLOCK EVRUN_NOWAIT
Definition at line 829 of file ev.h.
#define EVLOOP_ONESHOT EVRUN_ONCE
Definition at line 830 of file ev.h.
#define EVUNLOOP_ALL EVBREAK_ALL
Definition at line 833 of file ev.h.
#define EVUNLOOP_CANCEL EVBREAK_CANCEL
Definition at line 831 of file ev.h.
#define EVUNLOOP_ONE EVBREAK_ONE
Definition at line 832 of file ev.h.
Typedef Documentation
typedef struct ev_async ev_async
typedef struct ev_check ev_check
typedef struct ev_child ev_child
typedef struct ev_cleanup ev_cleanup
typedef struct ev_embed ev_embed
typedef struct ev_fork ev_fork
typedef struct ev_idle ev_idle
typedef struct ev_io ev_io
typedef void(* ev_loop_callback)(EV_P)
Definition at line 667 of file ev.h.
typedef struct ev_periodic ev_periodic
typedef struct ev_prepare ev_prepare
typedef struct ev_signal ev_signal
typedef struct ev_stat ev_stat
typedef struct stat ev_statdata
Definition at line 372 of file ev.h.
typedef struct ev_timer ev_timer
typedef double ev_tstamp
Definition at line 153 of file ev.h.
typedef struct ev_watcher ev_watcher
typedef struct ev_watcher_list ev_watcher_list
typedef struct ev_watcher_time ev_watcher_time
Enumeration Type Documentation
anonymous enum
Enumerator
EV_UNDEF
EV_NONE
EV_READ
EV_WRITE
EV__IOFDSET
EV_IO
EV_TIMER
EV_TIMEOUT
EV_PERIODIC
EV_SIGNAL
EV_CHILD
EV_STAT
EV_IDLE
EV_PREPARE
EV_CHECK
EV_EMBED
EV_FORK
EV_CLEANUP
EV_ASYNC
EV_CUSTOM
EV_ERROR
Definition at line 217 of file ev.h.
anonymous enum
Enumerator
EVFLAG_AUTO
EVFLAG_NOENV
EVFLAG_FORKCHECK
EVFLAG_NOINOTIFY
EVFLAG_NOSIGFD
EVFLAG_SIGNALFD
EVFLAG_NOSIGMASK
Definition at line 501 of file ev.h.
anonymous enum
Enumerator
EVBACKEND_SELECT
EVBACKEND_POLL
EVBACKEND_EPOLL
EVBACKEND_KQUEUE
EVBACKEND_DEVPOLL
EVBACKEND_PORT
EVBACKEND_ALL
EVBACKEND_MASK
Definition at line 517 of file ev.h.
anonymous enum
Enumerator
EVRUN_NOWAIT
EVRUN_ONCE
Definition at line 626 of file ev.h.
anonymous enum
Enumerator
EVBREAK_CANCEL
EVBREAK_ONE
EVBREAK_ALL
Definition at line 632 of file ev.h.
Function Documentation
EV_API_DECL void ev_async_send (EV_P_ ev_async * w)
Definition at line 4777 of file ev.c.
References async_pending, EV_A_, and evpipe_write().
EV_API_DECL void ev_async_start (EV_P_ ev_async * w)
Definition at line 4737 of file ev.c.
References array_needsize, asynccnt, asyncmax, asyncs, EMPTY2, EV_A, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), and expect_false.
EV_API_DECL void ev_async_stop (EV_P_ ev_async * w)
Definition at line 4756 of file ev.c.
References asynccnt, asyncs, clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), and expect_false.
EV_API_DECL unsigned int ev_backend (EV_P)
Definition at line 2643 of file ev.c.
References backend.
Referenced by ev_default_loop(), and ev_loop_new().
EV_API_DECL void ev_break (EV_P_ int how EV_CPP=EVBREAK_ONE)
EV_API_DECL void ev_check_start (EV_P_ ev_check * w)
Definition at line 4511 of file ev.c.
References array_needsize, checkcnt, checkmax, checks, EMPTY2, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), and expect_false.
EV_API_DECL void ev_check_stop (EV_P_ ev_check * w)
Definition at line 4526 of file ev.c.
References checkcnt, checks, clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), and expect_false.
EV_API_DECL void ev_child_start (EV_P_ ev_child * w)
Definition at line 4032 of file ev.c.
References EV_A_, EV_FREQUENT_CHECK, ev_is_active, EV_PID_HASHSIZE, ev_start(), expect_false, and wlist_add().
EV_API_DECL void ev_child_stop (EV_P_ ev_child * w)
Definition at line 4049 of file ev.c.
References clear_pending(), EV_A_, EV_FREQUENT_CHECK, ev_is_active, EV_PID_HASHSIZE, ev_stop(), expect_false, and wlist_del().
EV_API_DECL void ev_cleanup_start (EV_P_ ev_cleanup * w)
Definition at line 4696 of file ev.c.
References array_needsize, cleanupcnt, cleanupmax, cleanups, EMPTY2, EV_A, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), ev_unref(), and expect_false.
EV_API_DECL void ev_cleanup_stop (EV_P_ ev_cleanup * w)
Definition at line 4713 of file ev.c.
References cleanupcnt, cleanups, clear_pending(), EV_A, EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_ref(), ev_stop(), and expect_false.
EV_API_DECL int ev_clear_pending (EV_P_ void * w)
Definition at line 3660 of file ev.c.
References ABSPRI, ANPENDING::events, expect_true, pending_w, pendings, and ANPENDING::w.
EV_INLINE void ev_default_destroy (void)
Definition at line 837 of file ev.h.
References EV_DEFAULT, and ev_loop_destroy().
Referenced by main().
EV_INLINE void ev_default_fork (void)
Definition at line 838 of file ev.h.
References EV_DEFAULT, and ev_loop_fork().
EV_API_DECL struct ev_loop* ev_default_loop (unsigned int flags EV_CPP=0)
EV_INLINE struct ev_loop* ev_default_loop_uc_ (void)
Definition at line 564 of file ev.h.
References ev_default_loop_ptr.
EV_API_DECL unsigned int ev_depth (EV_P)
Definition at line 2656 of file ev.c.
References loop_depth.
Referenced by ev_loop_depth().
EV_API_DECL void ev_embed_start (EV_P_ ev_embed * w)
Definition at line 4607 of file ev.c.
References backend, backend_fd, EV_A_, ev_embeddable_backends(), ev_fork_init, ev_fork_start(), EV_FREQUENT_CHECK, ev_io_init, ev_io_start(), ev_is_active, EV_MINPRI, EV_P, ev_prepare_init, ev_prepare_start(), ev_priority, ev_set_priority, ev_start(), expect_false, ev_embed::fork, ev_embed::io, ev_embed::other, and ev_embed::prepare.
EV_API_DECL void ev_embed_stop (EV_P_ ev_embed * w)
Definition at line 4638 of file ev.c.
References clear_pending(), EV_A_, ev_fork_stop(), EV_FREQUENT_CHECK, ev_io_stop(), ev_is_active, ev_prepare_stop(), ev_stop(), and expect_false.
EV_API_DECL void ev_embed_sweep (EV_P_ ev_embed * w)
Definition at line 4549 of file ev.c.
References ev_run(), and EVRUN_NOWAIT.
EV_API_DECL unsigned int ev_embeddable_backends (void)
Definition at line 2631 of file ev.c.
References EVBACKEND_EPOLL, EVBACKEND_KQUEUE, and EVBACKEND_PORT.
Referenced by ev_embed_start().
EV_API_DECL void ev_feed_event (EV_P_ void * w, int revents)
Definition at line 1856 of file ev.c.
References ABSPRI, array_needsize, EMPTY2, expect_false, NUMPRI, pendingcnt, pendingmax, pendingpri, and pendings.
Referenced by child_reap(), ev_feed_signal_event(), ev_run(), event_active(), fd_event_nocheck(), fd_kill(), feed_reverse_done(), loop_fork(), and queue_events().
EV_API_DECL void ev_feed_fd_event (EV_P_ int fd, int revents)
Definition at line 1927 of file ev.c.
References anfdmax, EV_A_, and fd_event_nocheck().
EV_API_DECL void ev_feed_signal (int signum)
Definition at line 2418 of file ev.c.
References ECB_MEMORY_FENCE_ACQUIRE, EV_A, EV_A_, EV_P, evpipe_write(), ANSIG::pending, and sig_pending.
EV_API_DECL void ev_feed_signal_event (EV_P_ int signum)
Definition at line 2444 of file ev.c.
References ECB_MEMORY_FENCE_RELEASE, EV_A, EV_A_, ev_feed_event(), EV_NSIG, EV_SIGNAL, expect_false, and ANSIG::pending.
EV_API_DECL void ev_fork_start (EV_P_ ev_fork * w)
Definition at line 4658 of file ev.c.
References array_needsize, EMPTY2, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), expect_false, forkcnt, forkmax, and forks.
Referenced by ev_embed_start().
EV_API_DECL void ev_fork_stop (EV_P_ ev_fork * w)
Definition at line 4673 of file ev.c.
References clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, forkcnt, and forks.
Referenced by ev_embed_stop().
EV_API_DECL void ev_idle_start (EV_P_ ev_idle * w)
Definition at line 4426 of file ev.c.
References ABSPRI, array_needsize, EMPTY2, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), expect_false, idleall, idlecnt, idlemax, idles, and pri_adjust().
EV_API_DECL void ev_idle_stop (EV_P_ ev_idle * w)
Definition at line 4449 of file ev.c.
References ABSPRI, clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, idleall, idlecnt, and idles.
EV_API_DECL void ev_invoke (EV_P_ void * w, int revents)
Definition at line 3131 of file ev.c.
References EV_CB_INVOKE.
EV_API_DECL void ev_invoke_pending (EV_P)
Definition at line 3149 of file ev.c.
References EV_CB_INVOKE, EV_FREQUENT_CHECK, ANPENDING::events, NUMPRI, pendingcnt, pendingpri, pendings, and ANPENDING::w.
EV_API_DECL void ev_io_start (EV_P_ ev_io * w)
Definition at line 3703 of file ev.c.
References anfds, array_init_zero, array_needsize, EV__IOFDSET, EV_A_, EV_ANFD_REIFY, EV_FREQUENT_CHECK, ev_is_active, ev_start(), EV_WRITE, expect_false, fd_change(), and wlist_add().
Referenced by auditd_tcp_listen_init(), ev_embed_start(), ev_once(), ev_signal_start(), event_add(), and main().
EV_API_DECL void ev_io_stop (EV_P_ ev_io * w)
Definition at line 3729 of file ev.c.
References anfds, clear_pending(), EV_A_, EV_ANFD_REIFY, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, fd_change(), and wlist_del().
Referenced by auditd_tcp_listen_uninit(), ev_embed_stop(), event_del(), fd_kill(), loop_fork(), and main().
EV_INLINE int ev_is_default_loop (EV_P)
Definition at line 572 of file ev.h.
References EV_A, and EV_DEFAULT_UC.
Referenced by ev_loop_destroy(), and event_base_free().
EV_API_DECL unsigned int ev_iteration (EV_P)
Definition at line 2650 of file ev.c.
References loop_count.
Referenced by ev_loop_count().
EV_INLINE void ev_loop (EV_P_ int flags)
Definition at line 835 of file ev.h.
References EV_A_, and ev_run().
Referenced by main().
EV_INLINE unsigned int ev_loop_count (EV_P)
Definition at line 840 of file ev.h.
References EV_A, and ev_iteration().
EV_INLINE unsigned int ev_loop_depth (EV_P)
Definition at line 841 of file ev.h.
References EV_A, and ev_depth().
EV_API_DECL void ev_loop_destroy (EV_P)
Definition at line 2798 of file ev.c.
References anfds, array_free, backend, backend_fd, cleanupcnt, cleanups, EMPTY, epoll_destroy(), EV_A, EV_A_, EV_CLEANUP, ev_free, EV_INVOKE_PENDING, ev_is_active, ev_is_default_loop(), ev_ref(), ev_signal_stop(), EV_WIN32_CLOSE_FD, EVBACKEND_SELECT, evpipe, expect_false, fs_fd, NUMPRI, pipe_w, poll_destroy(), queue_events(), select_destroy(), sigfd, and sigfd_w.
Referenced by ev_default_destroy(), and event_base_free().
EV_API_DECL void ev_loop_fork (EV_P)
Definition at line 3123 of file ev.c.
References postfork.
Referenced by ev_default_fork().
EV_API_DECL struct ev_loop* ev_loop_new (unsigned int flags EV_CPP=0)
EV_INLINE void ev_loop_verify (EV_P)
Definition at line 842 of file ev.h.
References EV_A, and ev_verify().
EV_API_DECL ev_tstamp ev_now (EV_P)
Definition at line 1758 of file ev.c.
References ev_rt_now.
Referenced by event_pending().
EV_API_DECL void ev_now_update (EV_P)
Definition at line 3599 of file ev.c.
References EV_A_, and time_update().
Referenced by ev_resume(), and ev_suspend().
EV_API_DECL void ev_once (EV_P_ int fd, int events, ev_tstamp timeout, void(*)(int revents, void *arg) cb, void * arg)
Definition at line 4824 of file ev.c.
References ev_once::arg, ev_once::cb, EV_A_, EV_ERROR, ev_init, ev_io_set, ev_io_start(), ev_malloc, EV_TIMER, ev_timer_set, ev_timer_start(), EV_WRITE, expect_false, ev_once::io, and ev_once::to.
Referenced by event_base_loopexit(), and event_base_once().
EV_API_DECL unsigned int ev_pending_count (EV_P)
Definition at line 3137 of file ev.c.
References NUMPRI, and pendingcnt.
EV_API_DECL void ev_periodic_again (EV_P_ ev_periodic * w)
Definition at line 3894 of file ev.c.
References EV_A_, ev_periodic_start(), and ev_periodic_stop().
EV_API_DECL void ev_periodic_start (EV_P_ ev_periodic * w)
Definition at line 3836 of file ev.c.
References ANHE_at_cache, ANHE_w, array_needsize, EMPTY2, EV_A_, ev_active, ev_at, EV_FREQUENT_CHECK, ev_is_active, ev_start(), expect_false, ev_periodic::interval, ev_periodic::offset, periodiccnt, periodicmax, periodics, ev_periodic::reschedule_cb, and upheap().
Referenced by auditd_tcp_listen_init(), and ev_periodic_again().
EV_API_DECL void ev_periodic_stop (EV_P_ ev_periodic * w)
Definition at line 3866 of file ev.c.
References adjustheap(), ANHE_w, clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, expect_true, HEAP0, periodiccnt, and periodics.
Referenced by auditd_tcp_listen_uninit(), ev_periodic_again(), and periodics_reify().
EV_API_DECL void ev_prepare_start (EV_P_ ev_prepare * w)
Definition at line 4473 of file ev.c.
References array_needsize, EMPTY2, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), expect_false, preparecnt, preparemax, and prepares.
Referenced by ev_embed_start().
EV_API_DECL void ev_prepare_stop (EV_P_ ev_prepare * w)
Definition at line 4488 of file ev.c.
References clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, preparecnt, and prepares.
Referenced by ev_embed_stop().
EV_API_DECL unsigned int ev_recommended_backends (void)
Definition at line 2609 of file ev.c.
References ev_supported_backends(), EVBACKEND_KQUEUE, and EVBACKEND_POLL.
EV_API_DECL void ev_ref (EV_P)
Definition at line 3587 of file ev.c.
References activecnt.
Referenced by ev_cleanup_stop(), ev_loop_destroy(), ev_start(), ev_stat_stop(), and loop_fork().
EV_API_DECL void ev_resume (EV_P)
Definition at line 3611 of file ev.c.
References EV_A, EV_A_, ev_now_update(), and mn_now.
EV_API_DECL int ev_run (EV_P_ int flags EV_CPP=0)
EV_API_DECL void ev_set_allocator (void *(*)(void *ptr, long size) EV_THROW cb)
Definition at line 1597 of file ev.c.
EV_API_DECL void ev_set_invoke_pending_cb (EV_P_ ev_loop_callback invoke_pending_cb)
Definition at line 2686 of file ev.c.
References invoke_cb.
EV_API_DECL void ev_set_io_collect_interval (EV_P_ ev_tstamp interval)
Definition at line 2662 of file ev.c.
References io_blocktime.
EV_API_DECL void ev_set_loop_release_cb (EV_P_ void(*)(EV_P) EV_THROW release, void(*)(EV_P) EV_THROW acquire)
Definition at line 2692 of file ev.c.
References acquire_cb, and release_cb.
EV_API_DECL void ev_set_syserr_cb (void(*)(const char *msg) EV_THROW cb)
Definition at line 1550 of file ev.c.
EV_API_DECL void ev_set_timeout_collect_interval (EV_P_ ev_tstamp interval)
Definition at line 2668 of file ev.c.
References timeout_blocktime.
EV_API_DECL void ev_set_userdata (EV_P_ void * data)
Definition at line 2674 of file ev.c.
References auparse_test::data, and userdata.
EV_API_DECL void ev_signal_start (EV_P_ ev_signal * w)
Definition at line 3909 of file ev.c.
References ECB_MEMORY_FENCE_RELEASE, EV_A, EV_A_, EV_FREQUENT_CHECK, ev_io_init, ev_io_start(), ev_is_active, EV_MAXPRI, EV_NSIG, ev_set_priority, ev_start(), ev_unref(), EVFLAG_NOSIGMASK, expect_false, fd_intern(), ANSIG::head, origflags, SA_RESTART, sigfd, sigfd_set, sigfd_w, and wlist_add().
Referenced by ev_default_loop(), event_add(), and main().
EV_API_DECL void ev_signal_stop (EV_P_ ev_signal * w)
Definition at line 3991 of file ev.c.
References clear_pending(), EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, ANSIG::head, sigfd, sigfd_set, and wlist_del().
Referenced by ev_loop_destroy(), event_del(), and main().
EV_API_DECL void ev_sleep (ev_tstamp delay)
Definition at line 1765 of file ev.c.
References EV_TS_SET, and EV_TV_SET.
Referenced by ev_run().
EV_API_DECL void ev_stat_start (EV_P_ ev_stat * w)
Definition at line 4369 of file ev.c.
References DEF_STAT_INTERVAL, EV_A, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_priority, ev_set_priority, ev_start(), ev_stat_stat(), ev_timer_again(), ev_timer_init, ev_unref(), expect_false, fs_fd, and MIN_STAT_INTERVAL.
EV_API_DECL void ev_stat_stat (EV_P_ ev_stat * w)
Definition at line 4320 of file ev.c.
References ev_stat::attr, and ev_stat::path.
Referenced by ev_stat_start().
EV_API_DECL void ev_stat_stop (EV_P_ ev_stat * w)
Definition at line 4400 of file ev.c.
References clear_pending(), EV_A, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_ref(), ev_stop(), ev_timer_stop(), and expect_false.
EV_API_DECL unsigned int ev_supported_backends (void)
Definition at line 2595 of file ev.c.
References EV_USE_EPOLL, EV_USE_KQUEUE, EV_USE_POLL, EV_USE_PORT, EV_USE_SELECT, EVBACKEND_EPOLL, EVBACKEND_KQUEUE, EVBACKEND_POLL, EVBACKEND_PORT, and EVBACKEND_SELECT.
Referenced by ev_recommended_backends().
EV_API_DECL void ev_suspend (EV_P)
Definition at line 3605 of file ev.c.
References EV_A, and ev_now_update().
EV_API_DECL ev_tstamp ev_time (void)
Definition at line 1724 of file ev.c.
References expect_true.
Referenced by get_clock(), and time_update().
EV_API_DECL void ev_timer_again (EV_P_ ev_timer * w)
Definition at line 3802 of file ev.c.
References adjustheap(), ANHE_at_cache, clear_pending(), EV_A_, ev_active, ev_at, EV_FREQUENT_CHECK, ev_is_active, ev_timer_start(), ev_timer_stop(), and timers.
Referenced by ev_stat_start(), and event_add().
EV_API_DECL ev_tstamp ev_timer_remaining (EV_P_ ev_timer * w)
Definition at line 3829 of file ev.c.
References ev_at, and ev_is_active.
EV_API_DECL void ev_timer_start (EV_P_ ev_timer * w)
Definition at line 3748 of file ev.c.
References ANHE_at_cache, ANHE_w, array_needsize, EMPTY2, EV_A_, ev_active, ev_at, EV_FREQUENT_CHECK, ev_is_active, ev_start(), expect_false, mn_now, timercnt, timermax, timers, and upheap().
Referenced by ev_once(), and ev_timer_again().
EV_API_DECL void ev_timer_stop (EV_P_ ev_timer * w)
Definition at line 3772 of file ev.c.
References adjustheap(), ANHE_w, clear_pending(), EV_A_, ev_active, ev_at, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, expect_true, HEAP0, mn_now, timercnt, and timers.
Referenced by ev_stat_stop(), ev_timer_again(), event_add(), event_del(), and timers_reify().
EV_INLINE void ev_unloop (EV_P_ int how)
Definition at line 836 of file ev.h.
References EV_A_, and ev_break().
EV_API_DECL void ev_unref (EV_P)
Definition at line 3593 of file ev.c.
References activecnt.
Referenced by ev_cleanup_start(), ev_default_loop(), ev_signal_start(), ev_stat_start(), and ev_stop().
EV_API_DECL void* ev_userdata (EV_P)
Definition at line 2680 of file ev.c.
References userdata.
EV_API_DECL void ev_verify (EV_P)
Definition at line 3004 of file ev.c.
References activecnt, anfdmax, anfds, asynccnt, asyncmax, asyncs, checkcnt, checkmax, checks, cleanupcnt, cleanupmax, cleanups, EV_A_, ev_active, EV_NSIG, EV_PID_HASHSIZE, fdchangecnt, fdchangemax, fdchanges, forkcnt, forkmax, forks, idleall, idlecnt, idlemax, idles, NUMPRI, pendingcnt, pendingmax, periodiccnt, periodicmax, periodics, preparecnt, preparemax, prepares, timercnt, timermax, and timers.
Referenced by ev_loop_verify(), and ev_run().
EV_API_DECL int ev_version_major (void)
Definition at line 2571 of file ev.c.
References EV_VERSION_MAJOR.
EV_API_DECL int ev_version_minor (void)
Definition at line 2577 of file ev.c.
References EV_VERSION_MINOR.