audit: src/libev/ev.c File Reference
ev.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <stddef.h>
#include <stdio.h>
#include <assert.h>
#include <errno.h>
#include <sys/types.h>
#include <time.h>
#include <limits.h>
#include <signal.h>
#include "ev.h"
#include <sys/time.h>
#include <sys/wait.h>
#include <unistd.h>
#include <sys/select.h>
#include <inttypes.h>
#include <pthread.h>
#include <math.h>
#include <float.h>
#include "ev_vars.h"
#include "ev_wrap.h"
Data Structures
struct ANFD
struct ANPENDING
struct ANHE
struct ev_loop
struct ANSIG
struct ev_once
Macros
#define EV_USE_CLOCK_SYSCALL 0
#define EV_USE_MONOTONIC 0
#define EV_USE_REALTIME 0
#define EV_USE_NANOSLEEP 0
#define EV_USE_SELECT 0
#define EV_USE_POLL 0
#define EV_USE_EPOLL 0
#define EV_USE_KQUEUE 0
#define EV_USE_PORT 0
#define EV_USE_INOTIFY 0
#define EV_USE_SIGNALFD 0
#define EV_USE_EVENTFD 0
#define _DARWIN_UNLIMITED_SELECT 1
#define EV_NSIG (8 * sizeof (sigset_t) + 1)
#define EV_USE_FLOOR 0
#define EV_PID_HASHSIZE EV_FEATURE_DATA ? 16 : 1
#define EV_INOTIFY_HASHSIZE EV_FEATURE_DATA ? 16 : 1
#define EV_VERIFY (EV_FEATURE_API ? 1 : 0)
#define EV_USE_4HEAP EV_FEATURE_DATA
#define EV_HEAP_CACHE_AT EV_FEATURE_DATA
#define EV_USE_MONOTONIC 0
#define EV_USE_REALTIME 0
#define EV_FREQUENT_CHECK do { } while (0)
#define MIN_INTERVAL 0.0001220703125 /* 1/2**13, good till 4000 */
#define MIN_TIMEJUMP 1. /* minimum timejump that gets detected (if monotonic clock available) */
#define MAX_BLOCKTIME 59.743 /* never wait longer than this time (to detect time jumps) */
#define EV_TV_SET(tv, t) do { tv.tv_sec = (long)t; tv.tv_usec = (long)((t - tv.tv_sec) * 1e6); } while (0)
#define EV_TS_SET(ts, t) do { ts.tv_sec = (long)t; ts.tv_nsec = (long)((t - ts.tv_sec) * 1e9); } while (0)
#define ECB_H
#define ECB_VERSION 0x00010004
#define ECB_PTRSIZE 4
#define ECB_GCC_AMD64 (__amd64 || __amd64__ || __x86_64 || __x86_64__)
#define ECB_MSVC_AMD64 (_M_AMD64 || _M_X64)
#define ECB_GCC_VERSION(major, minor) 0
#define ECB_CLANG_VERSION(major, minor) (__clang_major__ > (major) || (__clang_major__ == (major) && __clang_minor__ >= (minor)))
#define ECB_CLANG_BUILTIN(x) 0
#define ECB_CLANG_EXTENSION(x) 0
#define ECB_CPP (__cplusplus+0)
#define ECB_CPP11 (__cplusplus >= 201103L)
#define ECB_C 1
#define ECB_STDC_VERSION __STDC_VERSION__
#define ECB_C99 (ECB_STDC_VERSION >= 199901L)
#define ECB_C11 (ECB_STDC_VERSION >= 201112L)
#define ECB_EXTERN_C extern
#define ECB_EXTERN_C_BEG
#define ECB_EXTERN_C_END
#define ECB_NEEDS_PTHREADS 1
#define ECB_MEMORY_FENCE_NEEDS_PTHREADS 1
#define ECB_MEMORY_FENCE do { pthread_mutex_lock (&ecb_mf_lock); pthread_mutex_unlock (&ecb_mf_lock); } while (0)
#define ECB_MEMORY_FENCE_ACQUIRE ECB_MEMORY_FENCE
#define ECB_MEMORY_FENCE_RELEASE ECB_MEMORY_FENCE
#define ecb_inline static
#define ecb_restrict
#define ECB_CONCAT_(a, b) a ## b
#define ECB_CONCAT(a, b) ECB_CONCAT_(a, b)
#define ECB_STRINGIFY_(a) # a
#define ECB_STRINGIFY(a) ECB_STRINGIFY_(a)
#define ECB_STRINGIFY_EXPR(expr) ((expr), ECB_STRINGIFY_ (expr))
#define ecb_function_ ecb_inline
#define ecb_attribute(attrlist)
#define ecb_is_constant(expr) 0
#define ecb_expect(expr, value) (expr)
#define ecb_prefetch(addr, rw, locality)
#define ecb_deprecated ecb_attribute ((__deprecated__))
#define ecb_deprecated_message(msg) ecb_deprecated
#define ecb_noinline ecb_attribute ((__noinline__))
#define ecb_unused ecb_attribute ((__unused__))
#define ecb_const ecb_attribute ((__const__))
#define ecb_pure ecb_attribute ((__pure__))
#define ecb_noreturn ecb_attribute ((__noreturn__))
#define ecb_artificial
#define ecb_hot
#define ecb_cold
#define ecb_expect_false(expr) ecb_expect (!!(expr), 0)
#define ecb_expect_true(expr) ecb_expect (!!(expr), 1)
#define ecb_likely(expr) ecb_expect_true (expr)
#define ecb_unlikely(expr) ecb_expect_false (expr)
#define ecb_assume(cond) if (!(cond)) ecb_unreachable (); else 0
#define ecb_mod(m, n) ((m) < 0 ? ((n) - 1 - ((-1 - (m)) % (n))) : ((m) % (n)))
#define ecb_div_rd(val, div) ((val) < 0 ? - ((-(val) + (div) - 1) / (div)) : ((val)) / (div))
#define ecb_div_ru(val, div) ((val) < 0 ? - ((-(val)) / (div)) : ((val) + (div) - 1) / (div))
#define ecb_array_length(name) (sizeof (name) / sizeof (name [0]))
#define ECB_STDFP 1
#define ECB_INFINITY HUGE_VAL
#define ECB_NAN ECB_INFINITY
#define ecb_ldexpf(x, e) (float) ldexp ((double) (x), (e))
#define ecb_frexpf(x, e) (float) frexp ((double) (x), (e))
#define expect_false(cond) ecb_expect_false (cond)
#define expect_true(cond) ecb_expect_true (cond)
#define noinline ecb_noinline
#define inline_size ecb_inline
#define inline_speed ecb_inline
#define NUMPRI (EV_MAXPRI - EV_MINPRI + 1)
#define ABSPRI(w) (((W)w)->priority - EV_MINPRI)
#define EMPTY /* required for microsofts broken pseudo-c compiler */
#define EMPTY2(a, b) /* used to suppress some warnings */
#define ev_active(w) ((W)(w))->active
#define ev_at(w) ((WT)(w))->at
#define EV_FD_TO_WIN32_HANDLE(fd) _get_osfhandle (fd)
#define EV_WIN32_HANDLE_TO_FD(handle) _open_osfhandle (handle, 0)
#define EV_WIN32_CLOSE_FD(fd) close (fd)
#define ev_malloc(size) ev_realloc (0, (size))
#define ev_free(ptr) free (ptr)
#define EV_ANFD_REIFY 1
#define ANHE_w(he) (he).w /* access watcher, read-write */
#define ANHE_at(he) (he).at /* access cached at, read-only */
#define ANHE_at_cache(he) (he).at = (he).w->at /* update at from watcher */
#define ev_rt_now ((loop)->ev_rt_now)
#define VAR(name, decl) decl;
#define EV_RELEASE_CB if (expect_false (release_cb)) release_cb (EV_A)
#define EV_ACQUIRE_CB if (expect_false (acquire_cb)) acquire_cb (EV_A)
#define EV_INVOKE_PENDING invoke_cb (EV_A)
#define EVBREAK_RECURSE 0x80
#define MALLOC_ROUND 4096 /* prefer to allocate in chunks of this size, must be 2**n and >> 4 longs */
#define array_init_zero(base, count) memset ((void *)(base), 0, sizeof (*(base)) * (count))
#define array_needsize(type, base, cur, cnt, init)
#define array_free(stem, idx) ev_free (stem ## s idx); stem ## cnt idx = stem ## max idx = 0; stem ## s idx = 0
#define DHEAP 4
#define HEAP0 (DHEAP - 1) /* index of first element in heap */
#define HPARENT(k) ((((k) - HEAP0 - 1) / DHEAP) + HEAP0)
#define UPHEAP_DONE(p, k) ((p) == (k))
#define WIFCONTINUED(status) 0
#define WCONTINUED 0
#define SA_RESTART 0
#define DEF_STAT_INTERVAL 5.0074891
#define NFS_STAT_INTERVAL 30.1074891 /* for filesystems potentially failing inotify */
#define MIN_STAT_INTERVAL 0.1074891
#define EV_LSTAT(p, b) lstat (p, b)
Typedefs
typedef int ecb_bool
typedef ev_watcher * W
typedef ev_watcher_list * WL
typedef ev_watcher_time * WT
Functions
ecb_function_ ecb_const int ecb_ctz32 (uint32_t x)
ecb_function_ ecb_const int ecb_ctz64 (uint64_t x)
ecb_function_ ecb_const int ecb_popcount32 (uint32_t x)
ecb_function_ ecb_const int ecb_ld32 (uint32_t x)
ecb_function_ ecb_const int ecb_ld64 (uint64_t x)
ecb_function_ ecb_const ecb_bool ecb_is_pot32 (uint32_t x)
ecb_function_ ecb_const ecb_bool ecb_is_pot64 (uint64_t x)
ecb_function_ ecb_const uint8_t ecb_bitrev8 (uint8_t x)
ecb_function_ ecb_const uint16_t ecb_bitrev16 (uint16_t x)
ecb_function_ ecb_const uint32_t ecb_bitrev32 (uint32_t x)
ecb_function_ ecb_const int ecb_popcount64 (uint64_t x)
ecb_inline ecb_const uint8_t ecb_rotl8 (uint8_t x, unsigned int count)
ecb_inline ecb_const uint8_t ecb_rotr8 (uint8_t x, unsigned int count)
ecb_inline ecb_const uint16_t ecb_rotl16 (uint16_t x, unsigned int count)
ecb_inline ecb_const uint16_t ecb_rotr16 (uint16_t x, unsigned int count)
ecb_inline ecb_const uint32_t ecb_rotl32 (uint32_t x, unsigned int count)
ecb_inline ecb_const uint32_t ecb_rotr32 (uint32_t x, unsigned int count)
ecb_inline ecb_const uint64_t ecb_rotl64 (uint64_t x, unsigned int count)
ecb_inline ecb_const uint64_t ecb_rotr64 (uint64_t x, unsigned int count)
ecb_function_ ecb_const uint16_t ecb_bswap16 (uint16_t x)
ecb_function_ ecb_const uint32_t ecb_bswap32 (uint32_t x)
ecb_function_ ecb_const uint64_t ecb_bswap64 (uint64_t x)
ecb_inline ecb_noreturn void ecb_unreachable (void)
ecb_inline ecb_const unsigned char ecb_byteorder_helper (void)
ecb_inline ecb_const ecb_bool ecb_big_endian (void)
ecb_inline ecb_const ecb_bool ecb_little_endian (void)
ecb_function_ ecb_const float ecb_binary16_to_float (uint16_t x)
ecb_function_ ecb_const uint32_t ecb_float_to_binary32 (float x)
ecb_function_ ecb_const float ecb_binary32_to_float (uint32_t x)
ecb_function_ ecb_const uint64_t ecb_double_to_binary64 (double x)
ecb_function_ ecb_const double ecb_binary64_to_double (uint64_t x)
void ecb_cold ev_set_syserr_cb (void(*cb)(const char *msg) EV_THROW) EV_THROW
void ecb_cold ev_set_allocator (void *(*cb)(void *ptr, long size) EV_THROW) EV_THROW
inline_speed void * ev_realloc (void *ptr, long size)
ev_tstamp ev_time (void)
inline_size ev_tstamp get_clock (void)
ev_tstamp ev_now (EV_P)
void ev_sleep (ev_tstamp delay) EV_THROW
inline_size int array_nextsize (int elem, int cur, int cnt)
void noinline ev_feed_event (EV_P_ void *w, int revents) EV_THROW
inline_speed void feed_reverse (EV_P_ W w)
inline_size void feed_reverse_done (EV_P_ int revents)
inline_speed void queue_events (EV_P_ W *events, int eventcnt, int type)
inline_speed void fd_event_nocheck (EV_P_ int fd, int revents)
inline_speed void fd_event (EV_P_ int fd, int revents)
void ev_feed_fd_event (EV_P_ int fd, int revents) EV_THROW
inline_size void fd_reify (EV_P)
inline_size void fd_change (EV_P_ int fd, int flags)
inline_speed void ecb_cold fd_kill (EV_P_ int fd)
inline_size int ecb_cold fd_valid (int fd)
inline_speed void fd_intern (int fd)
inline_speed void downheap (ANHE *heap, int N, int k)
inline_speed void upheap (ANHE *heap, int k)
inline_size void adjustheap (ANHE *heap, int N, int k)
inline_size void reheap (ANHE *heap, int N)
inline_speed void evpipe_write (EV_P_ EV_ATOMIC_T *flag)
void ev_feed_signal (int signum) EV_THROW
void noinline ev_feed_signal_event (EV_P_ int signum) EV_THROW
inline_speed void child_reap (EV_P_ int chain, int pid, int status)
int ecb_cold ev_version_major (void)
int ecb_cold ev_version_minor (void)
int inline_size ecb_cold enable_secure (void)
unsigned int ecb_cold ev_supported_backends (void)
unsigned int ecb_cold ev_recommended_backends (void)
unsigned int ecb_cold ev_embeddable_backends (void)
unsigned int ev_backend (EV_P)
unsigned int ev_iteration (EV_P)
unsigned int ev_depth (EV_P)
void ev_set_io_collect_interval (EV_P_ ev_tstamp interval) EV_THROW
void ev_set_timeout_collect_interval (EV_P_ ev_tstamp interval) EV_THROW
void ev_set_userdata (EV_P_ void *data) EV_THROW
void * ev_userdata (EV_P)
void ev_set_invoke_pending_cb (EV_P_ ev_loop_callback invoke_pending_cb) EV_THROW
void ev_set_loop_release_cb (EV_P_ void(*release)(EV_P) EV_THROW, void(*acquire)(EV_P) EV_THROW) EV_THROW
void ecb_cold ev_loop_destroy (EV_P)
inline_size void loop_fork (EV_P)
struct ev_loop *ecb_cold ev_loop_new (unsigned int flags) EV_THROW
void ecb_cold ev_verify (EV_P)
struct ev_loop *ecb_cold ev_default_loop (unsigned int flags) EV_THROW
void ev_loop_fork (EV_P)
void ev_invoke (EV_P_ void *w, int revents)
unsigned int ev_pending_count (EV_P)
void noinline ev_invoke_pending (EV_P)
inline_size void idle_reify (EV_P)
inline_size void timers_reify (EV_P)
inline_size void periodics_reify (EV_P)
inline_speed void time_update (EV_P_ ev_tstamp max_block)
int ev_run (EV_P_ int flags)
void ev_break (EV_P_ int how) EV_THROW
void ev_ref (EV_P)
void ev_unref (EV_P)
void ev_now_update (EV_P)
void ev_suspend (EV_P)
void ev_resume (EV_P)
inline_size void wlist_add (WL *head, WL elem)
inline_size void wlist_del (WL *head, WL elem)
inline_speed void clear_pending (EV_P_ W w)
int ev_clear_pending (EV_P_ void *w) EV_THROW
inline_size void pri_adjust (EV_P_ W w)
inline_speed void ev_start (EV_P_ W w, int active)
inline_size void ev_stop (EV_P_ W w)
void noinline ev_io_start (EV_P_ ev_io *w) EV_THROW
void noinline ev_io_stop (EV_P_ ev_io *w) EV_THROW
void noinline ev_timer_start (EV_P_ ev_timer *w) EV_THROW
void noinline ev_timer_stop (EV_P_ ev_timer *w) EV_THROW
void noinline ev_timer_again (EV_P_ ev_timer *w) EV_THROW
ev_tstamp ev_timer_remaining (EV_P_ ev_timer *w) EV_THROW
void noinline ev_periodic_start (EV_P_ ev_periodic *w) EV_THROW
void noinline ev_periodic_stop (EV_P_ ev_periodic *w) EV_THROW
void noinline ev_periodic_again (EV_P_ ev_periodic *w) EV_THROW
void noinline ev_signal_start (EV_P_ ev_signal *w) EV_THROW
void noinline ev_signal_stop (EV_P_ ev_signal *w) EV_THROW
void ev_child_start (EV_P_ ev_child *w) EV_THROW
void ev_child_stop (EV_P_ ev_child *w) EV_THROW
void ev_stat_stat (EV_P_ ev_stat *w) EV_THROW
void ev_stat_start (EV_P_ ev_stat *w) EV_THROW
void ev_stat_stop (EV_P_ ev_stat *w) EV_THROW
void ev_idle_start (EV_P_ ev_idle *w) EV_THROW
void ev_idle_stop (EV_P_ ev_idle *w) EV_THROW
void ev_prepare_start (EV_P_ ev_prepare *w) EV_THROW
void ev_prepare_stop (EV_P_ ev_prepare *w) EV_THROW
void ev_check_start (EV_P_ ev_check *w) EV_THROW
void ev_check_stop (EV_P_ ev_check *w) EV_THROW
void noinline ev_embed_sweep (EV_P_ ev_embed *w) EV_THROW
void ev_embed_start (EV_P_ ev_embed *w) EV_THROW
void ev_embed_stop (EV_P_ ev_embed *w) EV_THROW
void ev_fork_start (EV_P_ ev_fork *w) EV_THROW
void ev_fork_stop (EV_P_ ev_fork *w) EV_THROW
void ev_cleanup_start (EV_P_ ev_cleanup *w) EV_THROW
void ev_cleanup_stop (EV_P_ ev_cleanup *w) EV_THROW
void ev_async_start (EV_P_ ev_async *w) EV_THROW
void ev_async_stop (EV_P_ ev_async *w) EV_THROW
void ev_async_send (EV_P_ ev_async *w) EV_THROW
void ev_once (EV_P_ int fd, int events, ev_tstamp timeout, void(*cb)(int revents, void *arg), void *arg) EV_THROW
Variables
EV_API_DECL struct ev_loop * ev_default_loop_ptr = 0
Macro Definition Documentation
#define _DARWIN_UNLIMITED_SELECT 1
Definition at line 220 of file ev.c.
#define ABSPRI (w) (((W)w)->priority - EV_MINPRI)
Definition at line 1407 of file ev.c.
Referenced by clear_pending(), ev_clear_pending(), ev_feed_event(), ev_idle_start(), and ev_idle_stop().
#define ANHE_at (he) (he).at /* access cached at, read-only */
Definition at line 1671 of file ev.c.
Referenced by adjustheap(), downheap(), ev_run(), periodics_reify(), timers_reify(), and upheap().
#define ANHE_at_cache (he) (he).at = (he).w->at /* update at from watcher */
Definition at line 1672 of file ev.c.
Referenced by ev_periodic_start(), ev_timer_again(), ev_timer_start(), periodics_reify(), and timers_reify().
#define ANHE_w (he) (he).w /* access watcher, read-write */
Definition at line 1670 of file ev.c.
Referenced by downheap(), ev_periodic_start(), ev_periodic_stop(), ev_timer_start(), ev_timer_stop(), periodics_reify(), timers_reify(), and upheap().
#define array_free (stem, idx) ev_free (stem ## s idx); stem ## cnt idx = stem ## max idx = 0; stem ## s idx = 0
Definition at line 1844 of file ev.c.
Referenced by epoll_destroy(), and ev_loop_destroy().
#define array_init_zero (base, count) memset ((void *)(base), 0, sizeof (*(base)) * (count))
Definition at line 1822 of file ev.c.
Referenced by ev_io_start().
#define array_needsize (type, base, cur, cnt, init)
Value:
if (expect_false ((cnt) > (cur)))               \
    {                               \
      int ecb_unused ocur_ = (cur);                 \
      (base) = (type *)array_realloc                \
         (sizeof (type), (base), &(cur), (cnt));        \
      init ((base) + (ocur_), (cur) - ocur_);           \
    }
Definition at line 1825 of file ev.c.
Referenced by ev_async_start(), ev_check_start(), ev_cleanup_start(), ev_feed_event(), ev_fork_start(), ev_idle_start(), ev_io_start(), ev_periodic_start(), ev_prepare_start(), ev_timer_start(), fd_change(), and feed_reverse().
#define DEF_STAT_INTERVAL 5.0074891
Definition at line 4072 of file ev.c.
Referenced by ev_stat_start().
#define DHEAP 4
Definition at line 2104 of file ev.c.
Referenced by downheap().
#define ecb_array_length (name) (sizeof (name) / sizeof (name [0]))
Definition at line 1156 of file ev.c.
#define ecb_artificial
Definition at line 889 of file ev.c.
#define ecb_assume (cond) if (!(cond)) ecb_unreachable (); else 0
Definition at line 1093 of file ev.c.
#define ecb_attribute (attrlist)
Definition at line 814 of file ev.c.
#define ECB_C 1
Definition at line 617 of file ev.c.
#define ECB_C11 (ECB_STDC_VERSION >= 201112L)
Definition at line 622 of file ev.c.
#define ECB_C99 (ECB_STDC_VERSION >= 199901L)
Definition at line 621 of file ev.c.
#define ECB_CLANG_BUILTIN (x) 0
Definition at line 601 of file ev.c.
#define ECB_CLANG_EXTENSION (x) 0
Definition at line 607 of file ev.c.
#define ECB_CLANG_VERSION (major, minor) (__clang_major__ > (major) || (__clang_major__ == (major) && __clang_minor__ >= (minor)))
Definition at line 596 of file ev.c.
#define ecb_cold
Definition at line 891 of file ev.c.
#define ECB_CONCAT (a, b) ECB_CONCAT_(a, b)
Definition at line 804 of file ev.c.
#define ECB_CONCAT_ (a, b) a ## b
Definition at line 803 of file ev.c.
#define ecb_const ecb_attribute ((__const__))
Definition at line 869 of file ev.c.
#define ECB_CPP (__cplusplus+0)
Definition at line 610 of file ev.c.
#define ECB_CPP11 (__cplusplus >= 201103L)
Definition at line 611 of file ev.c.
#define ecb_deprecated ecb_attribute ((__deprecated__))
Definition at line 851 of file ev.c.
#define ecb_deprecated_message (msg) ecb_deprecated
Definition at line 859 of file ev.c.
#define ecb_div_rd (val, div) ((val) < 0 ? - ((-(val) + (div) - 1) / (div)) : ((val)) / (div))
Definition at line 1144 of file ev.c.
#define ecb_div_ru (val, div) ((val) < 0 ? - ((-(val)) / (div)) : ((val) + (div) - 1) / (div))
Definition at line 1145 of file ev.c.
#define ecb_expect (expr, value) (expr)
Definition at line 830 of file ev.c.
#define ecb_expect_false (expr) ecb_expect (!!(expr), 0)
Definition at line 897 of file ev.c.
#define ecb_expect_true (expr) ecb_expect (!!(expr), 1)
Definition at line 898 of file ev.c.
#define ECB_EXTERN_C extern
Definition at line 629 of file ev.c.
#define ECB_EXTERN_C_BEG
Definition at line 630 of file ev.c.
#define ECB_EXTERN_C_END
Definition at line 631 of file ev.c.
#define ecb_frexpf (x, e) (float) frexp ((double) (x), (e))
Definition at line 1207 of file ev.c.
Referenced by ecb_float_to_binary32().
#define ecb_function_ ecb_inline
Definition at line 809 of file ev.c.
#define ECB_GCC_AMD64 (__amd64 || __amd64__ || __x86_64 || __x86_64__)
Definition at line 571 of file ev.c.
#define ECB_GCC_VERSION (major, minor) 0
Definition at line 591 of file ev.c.
#define ECB_H
Definition at line 534 of file ev.c.
#define ecb_hot
Definition at line 890 of file ev.c.
#define ECB_INFINITY HUGE_VAL
Definition at line 1193 of file ev.c.
Referenced by ecb_binary16_to_float().
#define ecb_inline static
Definition at line 790 of file ev.c.
#define ecb_is_constant (expr) 0
Definition at line 824 of file ev.c.
#define ecb_ldexpf (x, e) (float) ldexp ((double) (x), (e))
Definition at line 1206 of file ev.c.
Referenced by ecb_binary16_to_float(), and ecb_binary32_to_float().
#define ecb_likely (expr) ecb_expect_true (expr)
Definition at line 900 of file ev.c.
#define ECB_MEMORY_FENCE do { pthread_mutex_lock (&ecb_mf_lock); pthread_mutex_unlock (&ecb_mf_lock); } while (0)
Definition at line 769 of file ev.c.
Referenced by ev_run(), and evpipe_write().
#define ECB_MEMORY_FENCE_ACQUIRE ECB_MEMORY_FENCE
Definition at line 774 of file ev.c.
Referenced by ev_feed_signal(), and ev_run().
#define ECB_MEMORY_FENCE_NEEDS_PTHREADS 1
Definition at line 766 of file ev.c.
#define ECB_MEMORY_FENCE_RELEASE ECB_MEMORY_FENCE
Definition at line 778 of file ev.c.
Referenced by ev_feed_signal_event(), ev_signal_start(), and evpipe_write().
#define ecb_mod (m, n) ((m) < 0 ? ((n) - 1 - ((-1 - (m)) % (n))) : ((m) % (n)))
Definition at line 1129 of file ev.c.
#define ECB_MSVC_AMD64 (_M_AMD64 || _M_X64)
Definition at line 572 of file ev.c.
#define ECB_NAN ECB_INFINITY
Definition at line 1199 of file ev.c.
Referenced by ecb_binary16_to_float().
#define ECB_NEEDS_PTHREADS 1
Definition at line 765 of file ev.c.
#define ecb_noinline ecb_attribute ((__noinline__))
Definition at line 865 of file ev.c.
#define ecb_noreturn ecb_attribute ((__noreturn__))
Definition at line 881 of file ev.c.
#define ecb_prefetch (addr, rw, locality)
Definition at line 836 of file ev.c.
#define ECB_PTRSIZE 4
Definition at line 567 of file ev.c.
#define ecb_pure ecb_attribute ((__pure__))
Definition at line 870 of file ev.c.
#define ecb_restrict
Definition at line 798 of file ev.c.
#define ECB_STDC_VERSION __STDC_VERSION__
Definition at line 618 of file ev.c.
#define ECB_STDFP 1
Definition at line 1179 of file ev.c.
#define ECB_STRINGIFY (a) ECB_STRINGIFY_(a)
Definition at line 806 of file ev.c.
#define ECB_STRINGIFY_ (a) # a
Definition at line 805 of file ev.c.
#define ECB_STRINGIFY_EXPR (expr) ((expr), ECB_STRINGIFY_ (expr))
Definition at line 807 of file ev.c.
#define ecb_unlikely (expr) ecb_expect_false (expr)
Definition at line 901 of file ev.c.
#define ecb_unused ecb_attribute ((__unused__))
Definition at line 868 of file ev.c.
#define ECB_VERSION 0x00010004
Definition at line 537 of file ev.c.
#define EMPTY /* required for microsofts broken pseudo-c compiler */
Definition at line 1410 of file ev.c.
Referenced by epoll_destroy(), and ev_loop_destroy().
#define EMPTY2 (a, b) /* used to suppress some warnings */
Definition at line 1411 of file ev.c.
Referenced by ev_async_start(), ev_check_start(), ev_cleanup_start(), ev_feed_event(), ev_fork_start(), ev_idle_start(), ev_periodic_start(), ev_prepare_start(), ev_timer_start(), fd_change(), and feed_reverse().
#define EV_ACQUIRE_CB if (expect_false (acquire_cb)) acquire_cb (EV_A)
Definition at line 1710 of file ev.c.
#define ev_active (w) ((W)(w))->active
Definition at line 1417 of file ev.c.
Referenced by downheap(), ev_async_stop(), ev_check_stop(), ev_cleanup_stop(), ev_fork_stop(), ev_idle_stop(), ev_periodic_start(), ev_periodic_stop(), ev_prepare_stop(), ev_timer_again(), ev_timer_start(), ev_timer_stop(), ev_verify(), and upheap().
#define EV_ANFD_REIFY 1
Definition at line 1626 of file ev.c.
Referenced by ev_io_start(), and ev_io_stop().
#define ev_at (w) ((WT)(w))->at
Definition at line 1418 of file ev.c.
Referenced by ev_periodic_start(), ev_timer_again(), ev_timer_remaining(), ev_timer_start(), ev_timer_stop(), periodics_reify(), and timers_reify().
#define EV_FD_TO_WIN32_HANDLE (fd) _get_osfhandle (fd)
Definition at line 1431 of file ev.c.
Referenced by evpipe_write(), fd_intern(), fd_reify(), and fd_valid().
#define ev_free (ptr) free (ptr)
Definition at line 1621 of file ev.c.
Referenced by epoll_destroy(), ev_loop_destroy(), ev_loop_new(), poll_destroy(), and select_destroy().
#define EV_FREQUENT_CHECK do { } while (0)
Definition at line 475 of file ev.c.
Referenced by ev_async_start(), ev_async_stop(), ev_check_start(), ev_check_stop(), ev_child_start(), ev_child_stop(), ev_cleanup_start(), ev_cleanup_stop(), ev_embed_start(), ev_embed_stop(), ev_fork_start(), ev_fork_stop(), ev_idle_start(), ev_idle_stop(), ev_invoke_pending(), ev_io_start(), ev_io_stop(), ev_periodic_start(), ev_periodic_stop(), ev_prepare_start(), ev_prepare_stop(), ev_signal_start(), ev_signal_stop(), ev_stat_start(), ev_stat_stop(), ev_timer_again(), ev_timer_start(), ev_timer_stop(), periodics_reify(), and timers_reify().
#define EV_HEAP_CACHE_AT EV_FEATURE_DATA
Definition at line 365 of file ev.c.
#define EV_INOTIFY_HASHSIZE EV_FEATURE_DATA ? 16 : 1
Definition at line 331 of file ev.c.
#define EV_INVOKE_PENDING invoke_cb (EV_A)
Definition at line 1711 of file ev.c.
Referenced by ev_loop_destroy(), and ev_run().
#define EV_LSTAT (p, b) lstat (p, b)
Definition at line 4316 of file ev.c.
#define ev_malloc (size) ev_realloc (0, (size))
Definition at line 1620 of file ev.c.
Referenced by epoll_init(), ev_loop_new(), ev_once(), and select_init().
#define EV_NSIG (8 * sizeof (sigset_t) + 1)
Definition at line 246 of file ev.c.
Referenced by ev_feed_signal_event(), ev_signal_start(), and ev_verify().
#define EV_PID_HASHSIZE EV_FEATURE_DATA ? 16 : 1
Definition at line 327 of file ev.c.
Referenced by child_reap(), ev_child_start(), ev_child_stop(), and ev_verify().
#define EV_RELEASE_CB if (expect_false (release_cb)) release_cb (EV_A)
Definition at line 1709 of file ev.c.
#define ev_rt_now ((loop)->ev_rt_now)
Definition at line 1687 of file ev.c.
Referenced by ev_now(), ev_run(), and time_update().
#define EV_TS_SET (ts, t) do { ts.tv_sec = (long)t; ts.tv_nsec = (long)((t - ts.tv_sec) * 1e9); } while (0)
Definition at line 489 of file ev.c.
Referenced by ev_sleep().
#define EV_TV_SET (tv, t) do { tv.tv_sec = (long)t; tv.tv_usec = (long)((t - tv.tv_sec) * 1e6); } while (0)
Definition at line 488 of file ev.c.
Referenced by ev_sleep().
#define EV_USE_4HEAP EV_FEATURE_DATA
Definition at line 361 of file ev.c.
#define EV_USE_CLOCK_SYSCALL 0
Definition at line 65 of file ev.c.
#define EV_USE_EPOLL 0
Definition at line 117 of file ev.c.
Referenced by ev_supported_backends().
#define EV_USE_EVENTFD 0
Definition at line 162 of file ev.c.
#define EV_USE_FLOOR 0
Definition at line 250 of file ev.c.
#define EV_USE_INOTIFY 0
Definition at line 144 of file ev.c.
#define EV_USE_KQUEUE 0
Definition at line 126 of file ev.c.
Referenced by ev_supported_backends().
#define EV_USE_MONOTONIC 0
Definition at line 402 of file ev.c.
#define EV_USE_MONOTONIC 0
Definition at line 402 of file ev.c.
#define EV_USE_NANOSLEEP 0
Definition at line 90 of file ev.c.
#define EV_USE_POLL 0
Definition at line 108 of file ev.c.
Referenced by ev_supported_backends().
#define EV_USE_PORT 0
Definition at line 135 of file ev.c.
Referenced by ev_supported_backends().
#define EV_USE_REALTIME 0
Definition at line 407 of file ev.c.
#define EV_USE_REALTIME 0
Definition at line 407 of file ev.c.
#define EV_USE_SELECT 0
Definition at line 99 of file ev.c.
Referenced by ev_supported_backends().
#define EV_USE_SIGNALFD 0
Definition at line 153 of file ev.c.
#define EV_VERIFY (EV_FEATURE_API ? 1 : 0)
Definition at line 357 of file ev.c.
#define EV_WIN32_CLOSE_FD (fd) close (fd)
Definition at line 1437 of file ev.c.
Referenced by ev_loop_destroy(), and loop_fork().
#define EV_WIN32_HANDLE_TO_FD (handle) _open_osfhandle (handle, 0)
Definition at line 1434 of file ev.c.
#define EVBREAK_RECURSE 0x80
Definition at line 1718 of file ev.c.
Referenced by ev_run().
#define expect_false (cond) ecb_expect_false (cond)
Definition at line 1390 of file ev.c.
Referenced by ev_async_start(), ev_async_stop(), ev_check_start(), ev_check_stop(), ev_child_start(), ev_child_stop(), ev_cleanup_start(), ev_cleanup_stop(), ev_embed_start(), ev_embed_stop(), ev_feed_event(), ev_feed_signal_event(), ev_fork_start(), ev_fork_stop(), ev_idle_start(), ev_idle_stop(), ev_io_start(), ev_io_stop(), ev_loop_destroy(), ev_once(), ev_periodic_start(), ev_periodic_stop(), ev_prepare_start(), ev_prepare_stop(), ev_run(), ev_signal_start(), ev_signal_stop(), ev_stat_start(), ev_stat_stop(), ev_timer_start(), ev_timer_stop(), idle_reify(), and time_update().
#define expect_true (cond) ecb_expect_true (cond)
Definition at line 1391 of file ev.c.
Referenced by downheap(), ev_clear_pending(), ev_periodic_stop(), ev_run(), ev_time(), ev_timer_stop(), evpipe_write(), fd_change(), fd_event(), get_clock(), time_update(), and wlist_del().
#define HEAP0 (DHEAP - 1) /* index of first element in heap */
Definition at line 2105 of file ev.c.
Referenced by adjustheap(), downheap(), ev_periodic_stop(), ev_timer_stop(), and reheap().
#define HPARENT (k) ((((k) - HEAP0 - 1) / DHEAP) + HEAP0)
Definition at line 2106 of file ev.c.
Referenced by adjustheap(), and upheap().
#define inline_size ecb_inline
Definition at line 1394 of file ev.c.
#define inline_speed ecb_inline
Definition at line 1397 of file ev.c.
#define MALLOC_ROUND 4096 /* prefer to allocate in chunks of this size, must be 2**n and >> 4 longs */
Definition at line 1790 of file ev.c.
Referenced by array_nextsize().
#define MAX_BLOCKTIME 59.743 /* never wait longer than this time (to detect time jumps) */
Definition at line 486 of file ev.c.
Referenced by ev_run().
#define MIN_INTERVAL 0.0001220703125 /* 1/2**13, good till 4000 */
Definition at line 482 of file ev.c.
#define MIN_STAT_INTERVAL 0.1074891
Definition at line 4074 of file ev.c.
Referenced by ev_stat_start().
#define MIN_TIMEJUMP 1. /* minimum timejump that gets detected (if monotonic clock available) */
Definition at line 485 of file ev.c.
Referenced by time_update().
#define NFS_STAT_INTERVAL 30.1074891 /* for filesystems potentially failing inotify */
Definition at line 4073 of file ev.c.
#define noinline ecb_noinline
Definition at line 1392 of file ev.c.
#define NUMPRI (EV_MAXPRI - EV_MINPRI + 1)
Definition at line 1402 of file ev.c.
Referenced by ev_feed_event(), ev_invoke_pending(), ev_loop_destroy(), ev_pending_count(), ev_verify(), and idle_reify().
#define SA_RESTART 0
Definition at line 3903 of file ev.c.
Referenced by ev_signal_start().
#define UPHEAP_DONE (p, k) ((p) == (k))
Definition at line 2107 of file ev.c.
Referenced by upheap().
#define VAR (name, decl) decl;
Definition at line 1688 of file ev.c.
#define WCONTINUED 0
Definition at line 2522 of file ev.c.
#define WIFCONTINUED (status) 0
Definition at line 2498 of file ev.c.
Referenced by child_reap().
Typedef Documentation
typedef int ecb_bool
Definition at line 801 of file ev.c.
typedef ev_watcher* W
Definition at line 1413 of file ev.c.
typedef ev_watcher_list* WL
Definition at line 1414 of file ev.c.
typedef ev_watcher_time* WT
Definition at line 1415 of file ev.c.
Function Documentation
inline_size void adjustheap (ANHE * heap, int N, int k)
Definition at line 2213 of file ev.c.
References ANHE_at, downheap(), HEAP0, HPARENT, and upheap().
Referenced by ev_periodic_stop(), ev_timer_again(), and ev_timer_stop().
inline_size int array_nextsize (int elem, int cur, int cnt)
Definition at line 1795 of file ev.c.
References MALLOC_ROUND.
inline_speed void child_reap (EV_P_ int chain, int pid, int status)
Definition at line 2503 of file ev.c.
References EV_A_, EV_CHILD, ev_feed_event(), EV_MAXPRI, EV_PID_HASHSIZE, ev_set_priority, auparse_test::pid, and WIFCONTINUED.
inline_speed void clear_pending (EV_P_ W w)
Definition at line 3650 of file ev.c.
References ABSPRI, pending_w, and pendings.
Referenced by ev_async_stop(), ev_check_stop(), ev_child_stop(), ev_cleanup_stop(), ev_embed_stop(), ev_fork_stop(), ev_idle_stop(), ev_io_stop(), ev_periodic_stop(), ev_prepare_stop(), ev_signal_stop(), ev_stat_stop(), ev_timer_again(), and ev_timer_stop().
inline_speed void downheap (ANHE * heap, int N, int k)
Definition at line 2111 of file ev.c.
References ANHE_at, ANHE_w, DHEAP, E, ev_active, expect_true, and HEAP0.
Referenced by adjustheap(), periodics_reify(), and timers_reify().
ecb_inline ecb_const ecb_bool ecb_big_endian (void)
Definition at line 1122 of file ev.c.
References ecb_byteorder_helper().
ecb_function_ ecb_const float ecb_binary16_to_float (uint16_t x)
Definition at line 1213 of file ev.c.
References ECB_INFINITY, ecb_ldexpf, and ECB_NAN.
ecb_function_ ecb_const float ecb_binary32_to_float (uint32_t x)
Definition at line 1270 of file ev.c.
References ecb_ldexpf, and auparse_test::f.
ecb_function_ ecb_const double ecb_binary64_to_double (uint64_t x)
Definition at line 1340 of file ev.c.
ecb_function_ ecb_const uint16_t ecb_bitrev16 (uint16_t x)
Definition at line 999 of file ev.c.
ecb_function_ ecb_const uint32_t ecb_bitrev32 (uint32_t x)
Definition at line 1010 of file ev.c.
ecb_function_ ecb_const uint8_t ecb_bitrev8 (uint8_t x)
Definition at line 992 of file ev.c.
ecb_function_ ecb_const uint16_t ecb_bswap16 (uint16_t x)
Definition at line 1064 of file ev.c.
References ecb_rotl16().
Referenced by ecb_bswap32().
ecb_function_ ecb_const uint32_t ecb_bswap32 (uint32_t x)
Definition at line 1071 of file ev.c.
References ecb_bswap16().
Referenced by ecb_bswap64().
ecb_function_ ecb_const uint64_t ecb_bswap64 (uint64_t x)
Definition at line 1078 of file ev.c.
References ecb_bswap32().
ecb_inline ecb_const unsigned char ecb_byteorder_helper (void)
Definition at line 1097 of file ev.c.
Referenced by ecb_big_endian(), and ecb_little_endian().
ecb_function_ ecb_const int ecb_ctz32 (uint32_t x)
Definition at line 918 of file ev.c.
Referenced by ecb_ctz64().
ecb_function_ ecb_const int ecb_ctz64 (uint64_t x)
Definition at line 943 of file ev.c.
References ecb_ctz32().
ecb_function_ ecb_const uint64_t ecb_double_to_binary64 (double x)
Definition at line 1300 of file ev.c.
ecb_function_ ecb_const uint32_t ecb_float_to_binary32 (float x)
Definition at line 1230 of file ev.c.
References ecb_frexpf, and auparse_test::f.
ecb_function_ ecb_const ecb_bool ecb_is_pot32 (uint32_t x)
Definition at line 987 of file ev.c.
ecb_function_ ecb_const ecb_bool ecb_is_pot64 (uint64_t x)
Definition at line 989 of file ev.c.
ecb_function_ ecb_const int ecb_ld32 (uint32_t x)
Definition at line 962 of file ev.c.
Referenced by ecb_ld64().
ecb_function_ ecb_const int ecb_ld64 (uint64_t x)
Definition at line 976 of file ev.c.
References ecb_ld32().
ecb_inline ecb_const ecb_bool ecb_little_endian (void)
Definition at line 1124 of file ev.c.
References ecb_byteorder_helper().
ecb_function_ ecb_const int ecb_popcount32 (uint32_t x)
Definition at line 951 of file ev.c.
Referenced by ecb_popcount64().
ecb_function_ ecb_const int ecb_popcount64 (uint64_t x)
Definition at line 1025 of file ev.c.
References ecb_popcount32().
ecb_inline ecb_const uint16_t ecb_rotl16 (uint16_t x, unsigned int count)
Definition at line 1041 of file ev.c.
Referenced by ecb_bswap16().
ecb_inline ecb_const uint32_t ecb_rotl32 (uint32_t x, unsigned int count)
Definition at line 1043 of file ev.c.
ecb_inline ecb_const uint64_t ecb_rotl64 (uint64_t x, unsigned int count)
Definition at line 1045 of file ev.c.
ecb_inline ecb_const uint8_t ecb_rotl8 (uint8_t x, unsigned int count)
Definition at line 1039 of file ev.c.
ecb_inline ecb_const uint16_t ecb_rotr16 (uint16_t x, unsigned int count)
Definition at line 1042 of file ev.c.
ecb_inline ecb_const uint32_t ecb_rotr32 (uint32_t x, unsigned int count)
Definition at line 1044 of file ev.c.
ecb_inline ecb_const uint64_t ecb_rotr64 (uint64_t x, unsigned int count)
Definition at line 1046 of file ev.c.
ecb_inline ecb_const uint8_t ecb_rotr8 (uint8_t x, unsigned int count)
Definition at line 1040 of file ev.c.
ecb_inline ecb_noreturn void ecb_unreachable (void)
Definition at line 1089 of file ev.c.
int inline_size ecb_cold enable_secure (void)
Definition at line 2584 of file ev.c.
void ev_async_send (EV_P_ ev_async * w)
Definition at line 4777 of file ev.c.
References async_pending, EV_A_, and evpipe_write().
void ev_async_start (EV_P_ ev_async * w)
Definition at line 4737 of file ev.c.
References array_needsize, asynccnt, asyncmax, asyncs, EMPTY2, EV_A, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), and expect_false.
void ev_async_stop (EV_P_ ev_async * w)
Definition at line 4756 of file ev.c.
References asynccnt, asyncs, clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), and expect_false.
unsigned int ev_backend (EV_P)
Definition at line 2643 of file ev.c.
References backend.
Referenced by ev_default_loop(), and ev_loop_new().
void ev_break (EV_P_ int how)
Definition at line 3581 of file ev.c.
References loop_done.
Referenced by ev_unloop().
void ev_check_start (EV_P_ ev_check * w)
Definition at line 4511 of file ev.c.
References array_needsize, checkcnt, checkmax, checks, EMPTY2, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), and expect_false.
void ev_check_stop (EV_P_ ev_check * w)
Definition at line 4526 of file ev.c.
References checkcnt, checks, clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), and expect_false.
void ev_child_start (EV_P_ ev_child * w)
Definition at line 4032 of file ev.c.
References EV_A_, EV_FREQUENT_CHECK, ev_is_active, EV_PID_HASHSIZE, ev_start(), expect_false, and wlist_add().
void ev_child_stop (EV_P_ ev_child * w)
Definition at line 4049 of file ev.c.
References clear_pending(), EV_A_, EV_FREQUENT_CHECK, ev_is_active, EV_PID_HASHSIZE, ev_stop(), expect_false, and wlist_del().
void ev_cleanup_start (EV_P_ ev_cleanup * w)
Definition at line 4696 of file ev.c.
References array_needsize, cleanupcnt, cleanupmax, cleanups, EMPTY2, EV_A, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), ev_unref(), and expect_false.
void ev_cleanup_stop (EV_P_ ev_cleanup * w)
Definition at line 4713 of file ev.c.
References cleanupcnt, cleanups, clear_pending(), EV_A, EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_ref(), ev_stop(), and expect_false.
int ev_clear_pending (EV_P_ void * w)
Definition at line 3660 of file ev.c.
References ABSPRI, ANPENDING::events, expect_true, pending_w, pendings, and ANPENDING::w.
struct ev_loop* ecb_cold ev_default_loop (unsigned int flags)
Definition at line 3094 of file ev.c.
References EV_A, EV_A_, ev_backend(), ev_default_loop_ptr, EV_MAXPRI, EV_P, ev_set_priority, ev_signal_init, ev_signal_start(), and ev_unref().
Referenced by event_init(), and main().
unsigned int ev_depth (EV_P)
Definition at line 2656 of file ev.c.
References loop_depth.
Referenced by ev_loop_depth().
void ev_embed_start (EV_P_ ev_embed * w)
Definition at line 4607 of file ev.c.
References backend, backend_fd, EV_A_, ev_embeddable_backends(), ev_fork_init, ev_fork_start(), EV_FREQUENT_CHECK, ev_io_init, ev_io_start(), ev_is_active, EV_MINPRI, EV_P, ev_prepare_init, ev_prepare_start(), ev_priority, ev_set_priority, ev_start(), expect_false, ev_embed::fork, ev_embed::io, ev_embed::other, and ev_embed::prepare.
void ev_embed_stop (EV_P_ ev_embed * w)
Definition at line 4638 of file ev.c.
References clear_pending(), EV_A_, ev_fork_stop(), EV_FREQUENT_CHECK, ev_io_stop(), ev_is_active, ev_prepare_stop(), ev_stop(), and expect_false.
void noinline ev_embed_sweep (EV_P_ ev_embed * w)
Definition at line 4549 of file ev.c.
References ev_run(), and EVRUN_NOWAIT.
unsigned int ecb_cold ev_embeddable_backends (void)
Definition at line 2631 of file ev.c.
References EVBACKEND_EPOLL, EVBACKEND_KQUEUE, and EVBACKEND_PORT.
Referenced by ev_embed_start().
void noinline ev_feed_event (EV_P_ void * w, int revents)
Definition at line 1856 of file ev.c.
References ABSPRI, array_needsize, EMPTY2, expect_false, NUMPRI, pendingcnt, pendingmax, pendingpri, and pendings.
Referenced by child_reap(), ev_feed_signal_event(), ev_run(), event_active(), fd_event_nocheck(), fd_kill(), feed_reverse_done(), loop_fork(), and queue_events().
void ev_feed_fd_event (EV_P_ int fd, int revents)
Definition at line 1927 of file ev.c.
References anfdmax, EV_A_, and fd_event_nocheck().
void ev_feed_signal (int signum)
Definition at line 2418 of file ev.c.
References ECB_MEMORY_FENCE_ACQUIRE, EV_A, EV_A_, EV_P, evpipe_write(), ANSIG::pending, and sig_pending.
void noinline ev_feed_signal_event (EV_P_ int signum)
Definition at line 2444 of file ev.c.
References ECB_MEMORY_FENCE_RELEASE, EV_A, EV_A_, ev_feed_event(), EV_NSIG, EV_SIGNAL, expect_false, and ANSIG::pending.
void ev_fork_start (EV_P_ ev_fork * w)
Definition at line 4658 of file ev.c.
References array_needsize, EMPTY2, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), expect_false, forkcnt, forkmax, and forks.
Referenced by ev_embed_start().
void ev_fork_stop (EV_P_ ev_fork * w)
Definition at line 4673 of file ev.c.
References clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, forkcnt, and forks.
Referenced by ev_embed_stop().
void ev_idle_start (EV_P_ ev_idle * w)
Definition at line 4426 of file ev.c.
References ABSPRI, array_needsize, EMPTY2, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), expect_false, idleall, idlecnt, idlemax, idles, and pri_adjust().
void ev_idle_stop (EV_P_ ev_idle * w)
Definition at line 4449 of file ev.c.
References ABSPRI, clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, idleall, idlecnt, and idles.
void ev_invoke (EV_P_ void * w, int revents)
Definition at line 3131 of file ev.c.
References EV_CB_INVOKE.
void noinline ev_invoke_pending (EV_P)
Definition at line 3149 of file ev.c.
References EV_CB_INVOKE, EV_FREQUENT_CHECK, ANPENDING::events, NUMPRI, pendingcnt, pendingpri, pendings, and ANPENDING::w.
void noinline ev_io_start (EV_P_ ev_io * w)
Definition at line 3703 of file ev.c.
References anfds, array_init_zero, array_needsize, EV__IOFDSET, EV_A_, EV_ANFD_REIFY, EV_FREQUENT_CHECK, ev_is_active, ev_start(), EV_WRITE, expect_false, fd_change(), and wlist_add().
Referenced by auditd_tcp_listen_init(), ev_embed_start(), ev_once(), ev_signal_start(), event_add(), and main().
void noinline ev_io_stop (EV_P_ ev_io * w)
Definition at line 3729 of file ev.c.
References anfds, clear_pending(), EV_A_, EV_ANFD_REIFY, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, fd_change(), and wlist_del().
Referenced by auditd_tcp_listen_uninit(), ev_embed_stop(), event_del(), fd_kill(), loop_fork(), and main().
unsigned int ev_iteration (EV_P)
Definition at line 2650 of file ev.c.
References loop_count.
Referenced by ev_loop_count().
void ecb_cold ev_loop_destroy (EV_P)
Definition at line 2798 of file ev.c.
References anfds, array_free, backend, backend_fd, cleanupcnt, cleanups, EMPTY, epoll_destroy(), EV_A, EV_A_, EV_CLEANUP, ev_free, EV_INVOKE_PENDING, ev_is_active, ev_is_default_loop(), ev_ref(), ev_signal_stop(), EV_WIN32_CLOSE_FD, EVBACKEND_SELECT, evpipe, expect_false, fs_fd, NUMPRI, pipe_w, poll_destroy(), queue_events(), select_destroy(), sigfd, and sigfd_w.
Referenced by ev_default_destroy(), and event_base_free().
void ev_loop_fork (EV_P)
Definition at line 3123 of file ev.c.
References postfork.
Referenced by ev_default_fork().
struct ev_loop* ecb_cold ev_loop_new (unsigned int flags)
Definition at line 2950 of file ev.c.
References EV_A, EV_A_, ev_backend(), ev_free, ev_malloc, and EV_P.
Referenced by event_base_new(), and event_init().
ev_tstamp ev_now (EV_P)
Definition at line 1758 of file ev.c.
References ev_rt_now.
Referenced by event_pending().
void ev_now_update (EV_P)
Definition at line 3599 of file ev.c.
References EV_A_, and time_update().
Referenced by ev_resume(), and ev_suspend().
void ev_once (EV_P_ int fd, int events, ev_tstamp timeout, void(*)(int revents, void *arg) cb, void * arg)
Definition at line 4824 of file ev.c.
References ev_once::arg, ev_once::cb, EV_A_, EV_ERROR, ev_init, ev_io_set, ev_io_start(), ev_malloc, EV_TIMER, ev_timer_set, ev_timer_start(), EV_WRITE, expect_false, ev_once::io, and ev_once::to.
Referenced by event_base_loopexit(), and event_base_once().
unsigned int ev_pending_count (EV_P)
Definition at line 3137 of file ev.c.
References NUMPRI, and pendingcnt.
void noinline ev_periodic_again (EV_P_ ev_periodic * w)
Definition at line 3894 of file ev.c.
References EV_A_, ev_periodic_start(), and ev_periodic_stop().
void noinline ev_periodic_start (EV_P_ ev_periodic * w)
Definition at line 3836 of file ev.c.
References ANHE_at_cache, ANHE_w, array_needsize, EMPTY2, EV_A_, ev_active, ev_at, EV_FREQUENT_CHECK, ev_is_active, ev_start(), expect_false, ev_periodic::interval, ev_periodic::offset, periodiccnt, periodicmax, periodics, ev_periodic::reschedule_cb, and upheap().
Referenced by auditd_tcp_listen_init(), and ev_periodic_again().
void noinline ev_periodic_stop (EV_P_ ev_periodic * w)
Definition at line 3866 of file ev.c.
References adjustheap(), ANHE_w, clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, expect_true, HEAP0, periodiccnt, and periodics.
Referenced by auditd_tcp_listen_uninit(), ev_periodic_again(), and periodics_reify().
void ev_prepare_start (EV_P_ ev_prepare * w)
Definition at line 4473 of file ev.c.
References array_needsize, EMPTY2, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_start(), expect_false, preparecnt, preparemax, and prepares.
Referenced by ev_embed_start().
void ev_prepare_stop (EV_P_ ev_prepare * w)
Definition at line 4488 of file ev.c.
References clear_pending(), EV_A_, ev_active, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, preparecnt, and prepares.
Referenced by ev_embed_stop().
inline_speed void* ev_realloc (void * ptr, long size)
Definition at line 1603 of file ev.c.
unsigned int ecb_cold ev_recommended_backends (void)
Definition at line 2609 of file ev.c.
References ev_supported_backends(), EVBACKEND_KQUEUE, and EVBACKEND_POLL.
void ev_ref (EV_P)
Definition at line 3587 of file ev.c.
References activecnt.
Referenced by ev_cleanup_stop(), ev_loop_destroy(), ev_start(), ev_stat_stop(), and loop_fork().
void ev_resume (EV_P)
Definition at line 3611 of file ev.c.
References EV_A, EV_A_, ev_now_update(), and mn_now.
int ev_run (EV_P_ int flags)
Definition at line 3409 of file ev.c.
References activecnt, ANHE_at, backend_mintime, backend_poll, checkcnt, checks, curpid, ECB_MEMORY_FENCE, ECB_MEMORY_FENCE_ACQUIRE, EV_A, EV_A_, EV_CHECK, EV_CUSTOM, ev_feed_event(), EV_FORK, EV_INVOKE_PENDING, ev_is_active, EV_PREPARE, ev_rt_now, ev_sleep(), ev_verify(), EVBREAK_CANCEL, EVBREAK_ONE, EVBREAK_RECURSE, EVRUN_NOWAIT, EVRUN_ONCE, expect_false, expect_true, fd_reify(), forkcnt, forks, idle_reify(), idleall, io_blocktime, loop_count, loop_depth, loop_done, loop_fork(), MAX_BLOCKTIME, mn_now, periodiccnt, periodics, periodics_reify(), pipe_w, pipe_write_skipped, pipe_write_wanted, postfork, preparecnt, prepares, queue_events(), time_update(), timeout_blocktime, timers, and timers_reify().
Referenced by ev_embed_sweep(), ev_loop(), and event_base_loop().
void ecb_cold ev_set_allocator (void *(*)(void *ptr, long size) EV_THROW cb)
Definition at line 1597 of file ev.c.
void ev_set_invoke_pending_cb (EV_P_ ev_loop_callback invoke_pending_cb)
Definition at line 2686 of file ev.c.
References invoke_cb.
void ev_set_io_collect_interval (EV_P_ ev_tstamp interval)
Definition at line 2662 of file ev.c.
References io_blocktime.
void ev_set_loop_release_cb (EV_P_ void(*)(EV_P) EV_THROW release, void(*)(EV_P) EV_THROW acquire)
Definition at line 2692 of file ev.c.
References acquire_cb, and release_cb.
void ecb_cold ev_set_syserr_cb (void(*)(const char *msg) EV_THROW cb)
Definition at line 1550 of file ev.c.
void ev_set_timeout_collect_interval (EV_P_ ev_tstamp interval)
Definition at line 2668 of file ev.c.
References timeout_blocktime.
void ev_set_userdata (EV_P_ void * data)
Definition at line 2674 of file ev.c.
References auparse_test::data, and userdata.
void noinline ev_signal_start (EV_P_ ev_signal * w)
Definition at line 3909 of file ev.c.
References ECB_MEMORY_FENCE_RELEASE, EV_A, EV_A_, EV_FREQUENT_CHECK, ev_io_init, ev_io_start(), ev_is_active, EV_MAXPRI, EV_NSIG, ev_set_priority, ev_start(), ev_unref(), EVFLAG_NOSIGMASK, expect_false, fd_intern(), ANSIG::head, origflags, SA_RESTART, sigfd, sigfd_set, sigfd_w, and wlist_add().
Referenced by ev_default_loop(), event_add(), and main().
void noinline ev_signal_stop (EV_P_ ev_signal * w)
Definition at line 3991 of file ev.c.
References clear_pending(), EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, ANSIG::head, sigfd, sigfd_set, and wlist_del().
Referenced by ev_loop_destroy(), event_del(), and main().
void ev_sleep (ev_tstamp delay)
Definition at line 1765 of file ev.c.
References EV_TS_SET, and EV_TV_SET.
Referenced by ev_run().
inline_speed void ev_start (EV_P_ W w, int active)
Definition at line 3686 of file ev.c.
References EV_A, EV_A_, ev_ref(), and pri_adjust().
Referenced by ev_async_start(), ev_check_start(), ev_child_start(), ev_cleanup_start(), ev_embed_start(), ev_fork_start(), ev_idle_start(), ev_io_start(), ev_periodic_start(), ev_prepare_start(), ev_signal_start(), ev_stat_start(), and ev_timer_start().
void ev_stat_start (EV_P_ ev_stat * w)
Definition at line 4369 of file ev.c.
References DEF_STAT_INTERVAL, EV_A, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_priority, ev_set_priority, ev_start(), ev_stat_stat(), ev_timer_again(), ev_timer_init, ev_unref(), expect_false, fs_fd, and MIN_STAT_INTERVAL.
void ev_stat_stat (EV_P_ ev_stat * w)
Definition at line 4320 of file ev.c.
References ev_stat::attr, and ev_stat::path.
Referenced by ev_stat_start().
void ev_stat_stop (EV_P_ ev_stat * w)
Definition at line 4400 of file ev.c.
References clear_pending(), EV_A, EV_A_, EV_FREQUENT_CHECK, ev_is_active, ev_ref(), ev_stop(), ev_timer_stop(), and expect_false.
inline_size void ev_stop (EV_P_ W w)
Definition at line 3694 of file ev.c.
References EV_A, and ev_unref().
Referenced by ev_async_stop(), ev_check_stop(), ev_child_stop(), ev_cleanup_stop(), ev_embed_stop(), ev_fork_stop(), ev_idle_stop(), ev_io_stop(), ev_periodic_stop(), ev_prepare_stop(), ev_signal_stop(), ev_stat_stop(), and ev_timer_stop().
unsigned int ecb_cold ev_supported_backends (void)
Definition at line 2595 of file ev.c.
References EV_USE_EPOLL, EV_USE_KQUEUE, EV_USE_POLL, EV_USE_PORT, EV_USE_SELECT, EVBACKEND_EPOLL, EVBACKEND_KQUEUE, EVBACKEND_POLL, EVBACKEND_PORT, and EVBACKEND_SELECT.
Referenced by ev_recommended_backends().
void ev_suspend (EV_P)
Definition at line 3605 of file ev.c.
References EV_A, and ev_now_update().
ev_tstamp ev_time (void)
Definition at line 1724 of file ev.c.
References expect_true.
Referenced by get_clock(), and time_update().
void noinline ev_timer_again (EV_P_ ev_timer * w)
Definition at line 3802 of file ev.c.
References adjustheap(), ANHE_at_cache, clear_pending(), EV_A_, ev_active, ev_at, EV_FREQUENT_CHECK, ev_is_active, ev_timer_start(), ev_timer_stop(), and timers.
Referenced by ev_stat_start(), and event_add().
ev_tstamp ev_timer_remaining (EV_P_ ev_timer * w)
Definition at line 3829 of file ev.c.
References ev_at, and ev_is_active.
void noinline ev_timer_start (EV_P_ ev_timer * w)
Definition at line 3748 of file ev.c.
References ANHE_at_cache, ANHE_w, array_needsize, EMPTY2, EV_A_, ev_active, ev_at, EV_FREQUENT_CHECK, ev_is_active, ev_start(), expect_false, mn_now, timercnt, timermax, timers, and upheap().
Referenced by ev_once(), and ev_timer_again().
void noinline ev_timer_stop (EV_P_ ev_timer * w)
Definition at line 3772 of file ev.c.
References adjustheap(), ANHE_w, clear_pending(), EV_A_, ev_active, ev_at, EV_FREQUENT_CHECK, ev_is_active, ev_stop(), expect_false, expect_true, HEAP0, mn_now, timercnt, and timers.
Referenced by ev_stat_stop(), ev_timer_again(), event_add(), event_del(), and timers_reify().
void ev_unref (EV_P)
Definition at line 3593 of file ev.c.
References activecnt.
Referenced by ev_cleanup_start(), ev_default_loop(), ev_signal_start(), ev_stat_start(), and ev_stop().
void* ev_userdata (EV_P)
Definition at line 2680 of file ev.c.
References userdata.
void ecb_cold ev_verify (EV_P)
Definition at line 3004 of file ev.c.
References activecnt, anfdmax, anfds, asynccnt, asyncmax, asyncs, checkcnt, checkmax, checks, cleanupcnt, cleanupmax, cleanups, EV_A_, ev_active, EV_NSIG, EV_PID_HASHSIZE, fdchangecnt, fdchangemax, fdchanges, forkcnt, forkmax, forks, idleall, idlecnt, idlemax, idles, NUMPRI, pendingcnt, pendingmax, periodiccnt, periodicmax, periodics, preparecnt, preparemax, prepares, timercnt, timermax, and timers.
Referenced by ev_loop_verify(), and ev_run().
int ecb_cold ev_version_major (void)
Definition at line 2571 of file ev.c.
References EV_VERSION_MAJOR.
int ecb_cold ev_version_minor (void)
Definition at line 2577 of file ev.c.
References EV_VERSION_MINOR.
inline_speed void evpipe_write (EV_P_ EV_ATOMIC_T * flag)
Definition at line 2297 of file ev.c.
References ECB_MEMORY_FENCE, ECB_MEMORY_FENCE_RELEASE, EV_FD_TO_WIN32_HANDLE, evpipe, expect_true, pipe_write_skipped, and pipe_write_wanted.
Referenced by ev_async_send(), and ev_feed_signal().
inline_size void fd_change (EV_P_ int fd, int flags)
Definition at line 1996 of file ev.c.
References anfds, array_needsize, EMPTY2, expect_true, fdchangecnt, fdchangemax, and fdchanges.
Referenced by ev_io_start(), and ev_io_stop().
inline_speed void fd_event (EV_P_ int fd, int revents)
Definition at line 1918 of file ev.c.
References anfds, EV_A_, expect_true, fd_event_nocheck(), and ANFD::reify.
inline_speed void fd_event_nocheck (EV_P_ int fd, int revents)
Definition at line 1901 of file ev.c.
References anfds, EV_A_, ev_feed_event(), and ANFD::head.
Referenced by ev_feed_fd_event(), and fd_event().
inline_speed void fd_intern (int fd)
Definition at line 2077 of file ev.c.
References EV_FD_TO_WIN32_HANDLE.
Referenced by ev_signal_start().
inline_speed void ecb_cold fd_kill (EV_P_ int fd)
Definition at line 2011 of file ev.c.
References anfds, EV_A_, EV_ERROR, ev_feed_event(), ev_io_stop(), EV_READ, and EV_WRITE.
inline_size void fd_reify (EV_P)
Definition at line 1936 of file ev.c.
References anfds, backend_modify, EV__IOFDSET, EV_A_, EV_FD_TO_WIN32_HANDLE, ANFD::events, fdchangecnt, fdchanges, ANFD::head, and ANFD::reify.
Referenced by ev_run().
inline_size int ecb_cold fd_valid (int fd)
Definition at line 2024 of file ev.c.
References EV_FD_TO_WIN32_HANDLE.
inline_speed void feed_reverse (EV_P_ W w)
Definition at line 1875 of file ev.c.
References array_needsize, EMPTY2, rfeedcnt, rfeedmax, and rfeeds.
Referenced by periodics_reify(), and timers_reify().
inline_size void feed_reverse_done (EV_P_ int revents)
Definition at line 1882 of file ev.c.
References EV_A_, ev_feed_event(), rfeedcnt, and rfeeds.
Referenced by periodics_reify(), and timers_reify().
inline_size ev_tstamp get_clock (void)
Definition at line 1742 of file ev.c.
References ev_time(), and expect_true.
Referenced by time_update().
inline_size void idle_reify (EV_P)
Definition at line 3172 of file ev.c.
References EV_A_, EV_IDLE, expect_false, idleall, idlecnt, idles, NUMPRI, pendingcnt, and queue_events().
Referenced by ev_run().
inline_size void loop_fork (EV_P)
Definition at line 2912 of file ev.c.
References backend, epoll_fork(), EV_A, EV_A_, EV_CUSTOM, ev_feed_event(), ev_io_stop(), ev_is_active, ev_ref(), EV_WIN32_CLOSE_FD, evpipe, pipe_w, and postfork.
Referenced by ev_run().
inline_size void periodics_reify (EV_P)
Definition at line 3259 of file ev.c.
References ANHE_at, ANHE_at_cache, ANHE_w, downheap(), EV_A_, ev_at, EV_FREQUENT_CHECK, EV_PERIODIC, ev_periodic_stop(), feed_reverse(), feed_reverse_done(), ev_periodic::interval, periodiccnt, periodics, and ev_periodic::reschedule_cb.
Referenced by ev_run().
inline_size void pri_adjust (EV_P_ W w)
Definition at line 3677 of file ev.c.
References EV_MAXPRI, EV_MINPRI, ev_priority, and ev_set_priority.
Referenced by ev_idle_start(), and ev_start().
inline_speed void queue_events (EV_P_ W * events, int eventcnt, int type)
Definition at line 1890 of file ev.c.
References EV_A_, and ev_feed_event().
Referenced by ev_loop_destroy(), ev_run(), and idle_reify().
inline_size void reheap (ANHE * heap, int N)
Definition at line 2223 of file ev.c.
References HEAP0, N, and upheap().
inline_speed void time_update (EV_P_ ev_tstamp max_block)
Definition at line 3340 of file ev.c.
References EV_A, EV_A_, ev_rt_now, ev_time(), expect_false, expect_true, get_clock(), MIN_TIMEJUMP, mn_now, now_floor, and rtmn_diff.
Referenced by ev_now_update(), and ev_run().
inline_size void timers_reify (EV_P)
Definition at line 3195 of file ev.c.
References ANHE_at, ANHE_at_cache, ANHE_w, downheap(), EV_A_, ev_at, EV_FREQUENT_CHECK, EV_TIMER, ev_timer_stop(), feed_reverse(), feed_reverse_done(), mn_now, ev_timer::repeat, timercnt, and timers.
Referenced by ev_run().
inline_speed void upheap (ANHE * heap, int k)
Definition at line 2191 of file ev.c.
References ANHE_at, ANHE_w, ev_active, HPARENT, and UPHEAP_DONE.
Referenced by adjustheap(), ev_periodic_start(), ev_timer_start(), and reheap().
inline_size void wlist_add (WL * head, WL elem)
Definition at line 3627 of file ev.c.
Referenced by ev_child_start(), ev_io_start(), and ev_signal_start().
inline_size void wlist_del (WL * head, WL elem)
Definition at line 3634 of file ev.c.
References expect_true.
Referenced by ev_child_stop(), ev_io_stop(), and ev_signal_stop().
Variable Documentation
EV_API_DECL struct ev_loop* ev_default_loop_ptr = 0
Definition at line 1695 of file ev.c.
Referenced by ev_default_loop(), and ev_default_loop_uc_().