audit: src/libev/ev_vars.h File Reference
ev_vars.h File Reference
Macros
#define VARx(type, name) VAR(name, type name)
#define VARx(type, name) VAR(name, type name)
Functions
VARx (ev_tstamp, now_floor) VARx(ev_tstamp
mn_now VARx (ev_tstamp, rtmn_diff) VARx(int
mn_now pendingpri VARx (ev_prepare, pending_w) VARx(int
mn_now pendingpri activecnt VARx (EV_ATOMIC_T, loop_done) VARx(ev_tstamp
mn_now pendingpri activecnt
backend_mintime VAR (backend_modify, void(*backend_modify)(EV_P_ int fd, int oev, int nev)) VAR(backend_poll
Variables
mn_now pendingpri activecnt
backend_mintime void(* backend_poll)(EV_P_ ev_tstamp timeout)) VARx(char
mn_now pendingpri activecnt
backend_mintime void(*)
postfor VARx)(int, idleall) VARx(unsigned int
Macro Definition Documentation
#define VARx (type, name) VAR(name, type name)
#define VARx (type, name) VAR(name, type name)
Definition at line 40 of file ev_vars.h.
Function Documentation
mn_now pendingpri activecnt backend_mintime VAR (backend_modify , void(*)(EV_P_ int fd, int oev, int nev) backend_modify)
VARx (ev_tstamp , now_floor)
mn_now VARx (ev_tstamp , rtmn_diff)
mn_now pendingpri VARx (ev_prepare , pending_w)
mn_now pendingpri activecnt VARx (EV_ATOMIC_T , loop_done)
Variable Documentation
mn_now pendingpri activecnt backend_mintime void(* backend_poll)(EV_P_ ev_tstamp timeout)) VARx(char
Definition at line 67 of file ev_vars.h.
Referenced by epoll_init(), ev_run(), poll_init(), and select_init().
mn_now pendingpri activecnt backend_mintime void(*) postfor VARx)(int, idleall)VARx(unsigned int
Definition at line 147 of file ev_vars.h.