audit: src/libev/event.c File Reference
event.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <assert.h>
#include "event.h"
Data Structures
struct event_base
struct ev_x_once
Macros
#define dLOOPev struct ev_loop *loop = (struct ev_loop *)ev->ev_base
#define dLOOPbase struct ev_loop *loop = (struct ev_loop *)base
#define EVENT_STRINGIFY(s) # s
#define EVENT_VERSION(a, b) EVENT_STRINGIFY (a) "." EVENT_STRINGIFY (b)
Functions
const char * event_get_version (void)
const char * event_get_method (void)
void * event_init (void)
const char * event_base_get_method (const struct event_base *base)
struct event_base * event_base_new (void)
void event_base_free (struct event_base *base)
int event_dispatch (void)
int event_loop (int flags)
int event_loopexit (struct timeval *tv)
event_callback_fn event_get_callback (const struct event *ev)
void event_set (struct event *ev, int fd, short events, void(*cb)(int, short, void *), void *arg)
int event_once (int fd, short events, void(*cb)(int, short, void *), void *arg, struct timeval *tv)
int event_add (struct event *ev, struct timeval *tv)
int event_del (struct event *ev)
void event_active (struct event *ev, int res, short ncalls)
int event_pending (struct event *ev, short events, struct timeval *tv)
int event_priority_init (int npri)
int event_priority_set (struct event *ev, int pri)
int event_base_set (struct event_base *base, struct event *ev)
int event_base_loop (struct event_base *base, int flags)
int event_base_dispatch (struct event_base *base)
int event_base_loopexit (struct event_base *base, struct timeval *tv)
int event_base_once (struct event_base *base, int fd, short events, void(*cb)(int, short, void *), void *arg, struct timeval *tv)
int event_base_priority_init (struct event_base *base, int npri)
Macro Definition Documentation
#define dLOOPbase struct ev_loop *loop = (struct ev_loop *)base
Definition at line 52 of file event.c.
Referenced by event_base_free(), event_base_loop(), event_base_loopexit(), and event_base_once().
#define dLOOPev struct ev_loop *loop = (struct ev_loop *)ev->ev_base
Definition at line 51 of file event.c.
Referenced by event_active(), event_add(), event_del(), and event_pending().
#define EVENT_STRINGIFY (s) # s
Definition at line 78 of file event.c.
#define EVENT_VERSION (a, b) EVENT_STRINGIFY (a) "." EVENT_STRINGIFY (b)
Definition at line 79 of file event.c.
Referenced by event_get_version().
Function Documentation
void event_active (struct event * ev, int res, short ncalls)
Definition at line 289 of file event.c.
References dLOOPev, EV_A_, ev_feed_event(), EV_READ, EV_SIGNAL, EV_TIMEOUT, EV_WRITE, event::io, event::iosig, event::sig, and event::to.
int event_add (struct event * ev, struct timeval * tv)
Definition at line 230 of file event.c.
References dLOOPev, EV_A_, event::ev_events, event::ev_fd, event::ev_flags, ev_io_set, ev_io_start(), ev_is_active, EV_READ, EV_SIGNAL, ev_signal_set, ev_signal_start(), ev_timer_again(), ev_timer_stop(), EV_WRITE, EVLIST_ACTIVE, EVLIST_INSERTED, EVLIST_SIGNAL, EVLIST_TIMEOUT, event::io, event::iosig, ev_timer::repeat, event::sig, and event::to.
int event_base_dispatch (struct event_base * base)
Definition at line 363 of file event.c.
References event_base_loop().
Referenced by event_dispatch().
void event_base_free (struct event_base * base)
Definition at line 127 of file event.c.
References dLOOPbase, ev_is_default_loop(), and ev_loop_destroy().
const char* event_base_get_method (const struct event_base * base)
Definition at line 111 of file event.c.
int event_base_loop (struct event_base * base, int flags)
Definition at line 356 of file event.c.
References dLOOPbase, EV_A_, and ev_run().
Referenced by event_base_dispatch(), and event_loop().
int event_base_loopexit (struct event_base * base, struct timeval * tv)
Definition at line 376 of file event.c.
References dLOOPbase, EV_A_, and ev_once().
Referenced by event_loopexit().
struct event_base* event_base_new (void)
Definition at line 117 of file event.c.
References ev_loop_new(), and EVFLAG_AUTO.
int event_base_once (struct event_base * base, int fd, short events, void(*)(int, short, void *) cb, void * arg, struct timeval * tv)
Definition at line 402 of file event.c.
References ev_x_once::arg, ev_x_once::cb, dLOOPbase, EV_A_, ev_once(), EV_READ, EV_WRITE, and ev_x_once::fd.
Referenced by event_once().
int event_base_priority_init (struct event_base * base, int npri)
Definition at line 419 of file event.c.
Referenced by event_priority_init().
int event_base_set (struct event_base * base, struct event * ev)
Definition at line 349 of file event.c.
References event::ev_base.
int event_del (struct event * ev)
Definition at line 272 of file event.c.
References dLOOPev, EV_A_, event::ev_events, event::ev_flags, ev_io_stop(), ev_is_active, EV_READ, EV_SIGNAL, ev_signal_stop(), ev_timer_stop(), EV_WRITE, EVLIST_INIT, event::io, event::iosig, event::sig, and event::to.
int event_dispatch (void)
Definition at line 137 of file event.c.
References event_base_dispatch().
event_callback_fn event_get_callback (const struct event * ev)
Definition at line 160 of file event.c.
References event::ev_callback.
const char* event_get_method (void)
Definition at line 89 of file event.c.
const char* event_get_version (void)
Definition at line 82 of file event.c.
References EV_VERSION_MAJOR, EV_VERSION_MINOR, and EVENT_VERSION.
void* event_init (void)
Definition at line 94 of file event.c.
References ev_default_loop(), ev_loop_new(), and EVFLAG_AUTO.
int event_loop (int flags)
Definition at line 149 of file event.c.
References event_base_loop(), and event_loop().
Referenced by event_loop().
int event_loopexit (struct timeval * tv)
Definition at line 154 of file event.c.
References event_base_loopexit().
int event_once (int fd, short events, void(*)(int, short, void *) cb, void * arg, struct timeval * tv)
Definition at line 225 of file event.c.
References event_base_once().
int event_pending (struct event * ev, short events, struct timeval * tv)
Definition at line 303 of file event.c.
References dLOOPev, EV_A, event::ev_events, ev_is_active, ev_is_pending, ev_now(), EV_READ, EV_SIGNAL, EV_TIMEOUT, EV_WRITE, event::io, event::iosig, event::sig, and event::to.
int event_priority_init (int npri)
Definition at line 337 of file event.c.
References event_base_priority_init().
int event_priority_set (struct event * ev, int pri)
Definition at line 342 of file event.c.
References event::ev_pri.
void event_set (struct event * ev, int fd, short events, void(*)(int, short, void *) cb, void * arg)
Definition at line 206 of file event.c.
References event::ev_arg, event::ev_base, event::ev_callback, event::ev_events, event::ev_fd, event::ev_flags, ev_init, event::ev_pri, event::ev_res, EV_SIGNAL, events, EVLIST_INIT, event::io, event::iosig, event::sig, and event::to.