audit: src/libev/event.h File Reference
event.h File Reference
#include "ev.h"
#include <time.h>
#include <sys/time.h>
Data Structures
struct event
Macros
#define EV_TIMEOUT EV_TIMER
#define EVLIST_TIMEOUT 0x01
#define EVLIST_INSERTED 0x02
#define EVLIST_SIGNAL 0x04
#define EVLIST_ACTIVE 0x08
#define EVLIST_INTERNAL 0x10
#define EVLIST_INIT 0x80
#define EV_READ EV_READ
#define EV_WRITE EV_WRITE
#define EV_PERSIST 0x10
#define EV_ET 0x20 /* nop */
#define EVENT_SIGNAL(ev) ((int) (ev)->ev_fd)
#define EVENT_FD(ev) ((int) (ev)->ev_fd)
#define event_initialized(ev) ((ev)->ev_flags & EVLIST_INIT)
#define evtimer_add(ev, tv) event_add (ev, tv)
#define evtimer_set(ev, cb, data) event_set (ev, -1, 0, cb, data)
#define evtimer_del(ev) event_del (ev)
#define evtimer_pending(ev, tv) event_pending (ev, EV_TIMEOUT, tv)
#define evtimer_initialized(ev) event_initialized (ev)
#define timeout_add(ev, tv) evtimer_add (ev, tv)
#define timeout_set(ev, cb, data) evtimer_set (ev, cb, data)
#define timeout_del(ev) evtimer_del (ev)
#define timeout_pending(ev, tv) evtimer_pending (ev, tv)
#define timeout_initialized(ev) evtimer_initialized (ev)
#define signal_add(ev, tv) event_add (ev, tv)
#define signal_set(ev, sig, cb, data) event_set (ev, sig, EV_SIGNAL | EV_PERSIST, cb, data)
#define signal_del(ev) event_del (ev)
#define signal_pending(ev, tv) event_pending (ev, EV_SIGNAL, tv)
#define signal_initialized(ev) event_initialized (ev)
#define EVLOOP_ONCE EVLOOP_ONESHOT
#define _EVENT_LOG_DEBUG 0
#define _EVENT_LOG_MSG 1
#define _EVENT_LOG_WARN 2
#define _EVENT_LOG_ERR 3
Typedefs
typedef void(* event_callback_fn)(int, short, void *)
typedef void(* event_log_cb)(int severity, const char *msg)
Functions
event_callback_fn event_get_callback (const struct event *ev)
const char * event_get_version (void)
const char * event_get_method (void)
void * event_init (void)
void event_base_free (struct event_base *base)
int event_loop (int)
int event_loopexit (struct timeval *tv)
int event_dispatch (void)
void event_set_log_callback (event_log_cb cb)
void event_set (struct event *ev, int fd, short events, void(*cb)(int, short, void *), void *arg)
int event_once (int fd, short events, void(*cb)(int, short, void *), void *arg, struct timeval *tv)
int event_add (struct event *ev, struct timeval *tv)
int event_del (struct event *ev)
void event_active (struct event *ev, int res, short ncalls)
int event_pending (struct event *ev, short, struct timeval *tv)
int event_priority_init (int npri)
int event_priority_set (struct event *ev, int pri)
struct event_base * event_base_new (void)
const char * event_base_get_method (const struct event_base *)
int event_base_set (struct event_base *base, struct event *ev)
int event_base_loop (struct event_base *base, int)
int event_base_loopexit (struct event_base *base, struct timeval *tv)
int event_base_dispatch (struct event_base *base)
int event_base_once (struct event_base *base, int fd, short events, void(*cb)(int, short, void *), void *arg, struct timeval *tv)
int event_base_priority_init (struct event_base *base, int fd)
Macro Definition Documentation
#define _EVENT_LOG_DEBUG 0
Definition at line 141 of file event.h.
#define _EVENT_LOG_ERR 3
Definition at line 144 of file event.h.
#define _EVENT_LOG_MSG 1
Definition at line 142 of file event.h.
#define _EVENT_LOG_WARN 2
Definition at line 143 of file event.h.
#define EV_ET 0x20 /* nop */
Definition at line 105 of file event.h.
#define EV_PERSIST 0x10
Definition at line 104 of file event.h.
#define EV_READ EV_READ
Definition at line 102 of file event.h.
#define EV_TIMEOUT EV_TIMER
Definition at line 56 of file event.h.
#define EV_WRITE EV_WRITE
Definition at line 103 of file event.h.
#define EVENT_FD (ev) ((int) (ev)->ev_fd)
Definition at line 108 of file event.h.
#define event_initialized (ev) ((ev)->ev_flags & EVLIST_INIT)
Definition at line 110 of file event.h.
#define EVENT_SIGNAL (ev) ((int) (ev)->ev_fd)
Definition at line 107 of file event.h.
#define EVLIST_ACTIVE 0x08
Definition at line 74 of file event.h.
Referenced by event_add().
#define EVLIST_INIT 0x80
Definition at line 76 of file event.h.
Referenced by event_del(), and event_set().
#define EVLIST_INSERTED 0x02
Definition at line 72 of file event.h.
Referenced by event_add().
#define EVLIST_INTERNAL 0x10
Definition at line 75 of file event.h.
#define EVLIST_SIGNAL 0x04
Definition at line 73 of file event.h.
Referenced by event_add().
#define EVLIST_TIMEOUT 0x01
Definition at line 71 of file event.h.
Referenced by event_add().
#define EVLOOP_ONCE EVLOOP_ONESHOT
Definition at line 136 of file event.h.
#define evtimer_add (ev, tv) event_add (ev, tv)
Definition at line 112 of file event.h.
#define evtimer_del (ev) event_del (ev)
Definition at line 114 of file event.h.
#define evtimer_initialized (ev) event_initialized (ev)
Definition at line 116 of file event.h.
#define evtimer_pending (ev, tv) event_pending (ev, EV_TIMEOUT, tv)
Definition at line 115 of file event.h.
#define evtimer_set (ev, cb, data) event_set (ev, -1, 0, cb, data)
Definition at line 113 of file event.h.
#define signal_add (ev, tv) event_add (ev, tv)
Definition at line 124 of file event.h.
#define signal_del (ev) event_del (ev)
Definition at line 126 of file event.h.
#define signal_initialized (ev) event_initialized (ev)
Definition at line 128 of file event.h.
#define signal_pending (ev, tv) event_pending (ev, EV_SIGNAL, tv)
Definition at line 127 of file event.h.
#define signal_set (ev, sig, cb, data) event_set (ev, sig, EV_SIGNAL | EV_PERSIST, cb, data)
Definition at line 125 of file event.h.
#define timeout_add (ev, tv) evtimer_add (ev, tv)
Definition at line 118 of file event.h.
#define timeout_del (ev) evtimer_del (ev)
Definition at line 120 of file event.h.
#define timeout_initialized (ev) evtimer_initialized (ev)
Definition at line 122 of file event.h.
#define timeout_pending (ev, tv) evtimer_pending (ev, tv)
Definition at line 121 of file event.h.
#define timeout_set (ev, cb, data) evtimer_set (ev, cb, data)
Definition at line 119 of file event.h.
Typedef Documentation
typedef void(* event_callback_fn)(int, short, void *)
Definition at line 78 of file event.h.
typedef void(* event_log_cb)(int severity, const char *msg)
Definition at line 145 of file event.h.
Function Documentation
void event_active (struct event * ev, int res, short ncalls)
Definition at line 289 of file event.c.
References dLOOPev, EV_A_, ev_feed_event(), EV_READ, EV_SIGNAL, EV_TIMEOUT, EV_WRITE, event::io, event::iosig, event::sig, and event::to.
int event_add (struct event * ev, struct timeval * tv)
Definition at line 230 of file event.c.
References dLOOPev, EV_A_, event::ev_events, event::ev_fd, event::ev_flags, ev_io_set, ev_io_start(), ev_is_active, EV_READ, EV_SIGNAL, ev_signal_set, ev_signal_start(), ev_timer_again(), ev_timer_stop(), EV_WRITE, EVLIST_ACTIVE, EVLIST_INSERTED, EVLIST_SIGNAL, EVLIST_TIMEOUT, event::io, event::iosig, ev_timer::repeat, event::sig, and event::to.
int event_base_dispatch (struct event_base * base)
Definition at line 363 of file event.c.
References event_base_loop().
Referenced by event_dispatch().
void event_base_free (struct event_base * base)
Definition at line 127 of file event.c.
References dLOOPbase, ev_is_default_loop(), and ev_loop_destroy().
const char* event_base_get_method (const struct event_base *)
Definition at line 111 of file event.c.
int event_base_loop (struct event_base * base, int)
Definition at line 356 of file event.c.
References dLOOPbase, EV_A_, and ev_run().
Referenced by event_base_dispatch(), and event_loop().
int event_base_loopexit (struct event_base * base, struct timeval * tv)
Definition at line 376 of file event.c.
References dLOOPbase, EV_A_, and ev_once().
Referenced by event_loopexit().
struct event_base* event_base_new (void)
Definition at line 117 of file event.c.
References ev_loop_new(), and EVFLAG_AUTO.
int event_base_once (struct event_base * base, int fd, short events, void(*)(int, short, void *) cb, void * arg, struct timeval * tv)
Definition at line 402 of file event.c.
References ev_x_once::arg, ev_x_once::cb, dLOOPbase, EV_A_, ev_once(), EV_READ, EV_WRITE, and ev_x_once::fd.
Referenced by event_once().
int event_base_priority_init (struct event_base * base, int fd)
Definition at line 419 of file event.c.
Referenced by event_priority_init().
int event_base_set (struct event_base * base, struct event * ev)
Definition at line 349 of file event.c.
References event::ev_base.
int event_del (struct event * ev)
Definition at line 272 of file event.c.
References dLOOPev, EV_A_, event::ev_events, event::ev_flags, ev_io_stop(), ev_is_active, EV_READ, EV_SIGNAL, ev_signal_stop(), ev_timer_stop(), EV_WRITE, EVLIST_INIT, event::io, event::iosig, event::sig, and event::to.
int event_dispatch (void)
Definition at line 137 of file event.c.
References event_base_dispatch().
event_callback_fn event_get_callback (const struct event * ev)
Definition at line 160 of file event.c.
References event::ev_callback.
const char* event_get_method (void)
Definition at line 89 of file event.c.
const char* event_get_version (void)
Definition at line 82 of file event.c.
References EV_VERSION_MAJOR, EV_VERSION_MINOR, and EVENT_VERSION.
void* event_init (void)
Definition at line 94 of file event.c.
References ev_default_loop(), ev_loop_new(), and EVFLAG_AUTO.
int event_loop (int)
Definition at line 149 of file event.c.
References event_base_loop(), and event_loop().
Referenced by event_loop().
int event_loopexit (struct timeval * tv)
Definition at line 154 of file event.c.
References event_base_loopexit().
int event_once (int fd, short events, void(*)(int, short, void *) cb, void * arg, struct timeval * tv)
Definition at line 225 of file event.c.
References event_base_once().
int event_pending (struct event * ev, short , struct timeval * tv)
Definition at line 303 of file event.c.
References dLOOPev, EV_A, event::ev_events, ev_is_active, ev_is_pending, ev_now(), EV_READ, EV_SIGNAL, EV_TIMEOUT, EV_WRITE, event::io, event::iosig, event::sig, and event::to.
int event_priority_init (int npri)
Definition at line 337 of file event.c.
References event_base_priority_init().
int event_priority_set (struct event * ev, int pri)
Definition at line 342 of file event.c.
References event::ev_pri.
void event_set (struct event * ev, int fd, short events, void(*)(int, short, void *) cb, void * arg)
Definition at line 206 of file event.c.
References event::ev_arg, event::ev_base, event::ev_callback, event::ev_events, event::ev_fd, event::ev_flags, ev_init, event::ev_pri, event::ev_res, EV_SIGNAL, events, EVLIST_INIT, event::io, event::iosig, event::sig, and event::to.
void event_set_log_callback (event_log_cb cb)