audit: auparse/expression.h File Reference
expression.h File Reference
#include <regex.h>
#include <sys/types.h>
#include "internal.h"
Data Structures
struct expr
Enumerations
enum {
EO_NOT, EO_AND, EO_OR, EO_RAW_EQ,
EO_RAW_NE, EO_INTERPRETED_EQ, EO_INTERPRETED_NE, EO_VALUE_EQ,
EO_VALUE_NE, EO_VALUE_LT, EO_VALUE_LE, EO_VALUE_GT,
EO_VALUE_GE, EO_FIELD_EXISTS, EO_REGEXP_MATCHES, NUM_EO_VALUES
}
enum field_id { EF_TIMESTAMP, EF_RECORD_TYPE, EF_TIMESTAMP_EX }
Functions
void expr_free (struct expr *expr) hidden
struct expr * expr_parse (const char *string, char **error) hidden
struct expr * expr_create_comparison (const char *field, unsigned op, const char *value) hidden
struct expr * expr_create_timestamp_comparison (unsigned op, time_t sec, unsigned milli) hidden
struct expr * expr_create_timestamp_comparison_ex (unsigned op, time_t sec, unsigned milli, unsigned serial) hidden
struct expr * expr_create_field_exists (const char *field) hidden
struct expr * expr_create_regexp_expression (const char *regexp) hidden
struct expr * expr_create_binary (unsigned op, struct expr *e1, struct expr *e2) hidden
int expr_eval (auparse_state_t *au, rnode *record, const struct expr *expr) hidden
Enumeration Type Documentation
anonymous enum
Enumerator
EO_NOT
EO_AND
EO_OR
EO_RAW_EQ
EO_RAW_NE
EO_INTERPRETED_EQ
EO_INTERPRETED_NE
EO_VALUE_EQ
EO_VALUE_NE
EO_VALUE_LT
EO_VALUE_LE
EO_VALUE_GT
EO_VALUE_GE
EO_FIELD_EXISTS
EO_REGEXP_MATCHES
NUM_EO_VALUES
Definition at line 33 of file expression.h.
enum field_id
Enumerator
EF_TIMESTAMP
EF_RECORD_TYPE
EF_TIMESTAMP_EX
Definition at line 46 of file expression.h.
Function Documentation
struct expr* expr_create_binary (unsigned op, struct expr * e1, struct expr * e2)
Definition at line 897 of file expression.c.
References EO_AND, EO_OR, expr::op, auparse_test::res, expr::sub, and expr::v.
struct expr* expr_create_comparison (const char * field, unsigned op, const char * value)
Definition at line 777 of file expression.c.
References EO_INTERPRETED_EQ, EO_INTERPRETED_NE, EO_RAW_EQ, EO_RAW_NE, err, expr::op, expr::p, expr::precomputed_value, auparse_test::res, expr::v, and expr::virtual_field.
struct expr* expr_create_field_exists (const char * field)
Definition at line 844 of file expression.c.
References EO_FIELD_EXISTS, err, expr::op, expr::p, auparse_test::res, expr::v, and expr::virtual_field.
struct expr* expr_create_regexp_expression (const char * regexp)
Definition at line 868 of file expression.c.
References EO_REGEXP_MATCHES, err, expr::op, expr::regexp, auparse_test::res, and expr::v.
Referenced by ausearch_add_regex().
struct expr* expr_create_timestamp_comparison (unsigned op, time_t sec, unsigned milli)
Definition at line 835 of file expression.c.
References expr_create_timestamp_comparison_ex().
struct expr* expr_create_timestamp_comparison_ex (unsigned op, time_t sec, unsigned milli, unsigned serial)
Definition at line 810 of file expression.c.
References EF_TIMESTAMP_EX, EO_VALUE_EQ, EO_VALUE_GE, EO_VALUE_GT, EO_VALUE_LE, EO_VALUE_LT, EO_VALUE_NE, expr::milli, expr::op, expr::p, expr::precomputed_value, auparse_test::res, expr::sec, expr::serial, expr::v, and expr::virtual_field.
Referenced by ausearch_add_timestamp_item_ex(), and expr_create_timestamp_comparison().
int expr_eval (auparse_state_t * au, rnode * record, const struct expr * expr)
Definition at line 1027 of file expression.c.
References EO_AND, EO_FIELD_EXISTS, EO_INTERPRETED_EQ, EO_INTERPRETED_NE, EO_NOT, EO_OR, EO_RAW_EQ, EO_RAW_NE, EO_REGEXP_MATCHES, EO_VALUE_EQ, EO_VALUE_GE, EO_VALUE_GT, EO_VALUE_LE, EO_VALUE_LT, EO_VALUE_NE, err, expr_eval(), _rnode::nv, nvlist_find_name(), expr::op, expr::p, expr::precomputed_value, _rnode::record, expr::regexp, expr::sub, expr::v, expr::value, and expr::virtual_field.
Referenced by expr_eval().
void expr_free (struct expr * expr)
Definition at line 37 of file expression.c.
References EO_AND, EO_FIELD_EXISTS, EO_INTERPRETED_EQ, EO_INTERPRETED_NE, EO_NOT, EO_OR, EO_RAW_EQ, EO_RAW_NE, EO_REGEXP_MATCHES, EO_VALUE_EQ, EO_VALUE_GE, EO_VALUE_GT, EO_VALUE_LE, EO_VALUE_LT, EO_VALUE_NE, expr_free(), expr::op, expr::p, expr::precomputed_value, expr::regexp, expr::sub, expr::v, and expr::virtual_field.
Referenced by ausearch_clear(), expr_free(), and expr_parse().
struct expr* expr_parse (const char * string, char ** error)
Definition at line 741 of file expression.c.
References err, parsing::error, expr_free(), auparse_test::res, parsing::src, expr::string, T_EOF, parsing::token, parsing::token_len, parsing::token_start, and parsing::token_value.
Referenced by ausearch_add_expression().