audit: auparse/interpret.c File Reference
interpret.c File Reference
#include "config.h"
#include "nvlist.h"
#include "nvpair.h"
#include "libaudit.h"
#include "internal.h"
#include "interpret.h"
#include "auparse-idata.h"
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <ctype.h>
#include <errno.h>
#include <string.h>
#include <pwd.h>
#include <grp.h>
#include <sys/stat.h>
#include <linux/net.h>
#include <netdb.h>
#include <sys/un.h>
#include <linux/ax25.h>
#include <linux/atm.h>
#include <linux/x25.h>
#include <linux/if.h>
#include <linux/ipx.h>
#include <linux/capability.h>
#include <sys/personality.h>
#include <sys/prctl.h>
#include <sched.h>
#include "auparse-defs.h"
#include "gen_tables.h"
#include "captabs.h"
#include "clone-flagtabs.h"
#include "epoll_ctls.h"
#include "famtabs.h"
#include "fcntl-cmdtabs.h"
#include "flagtabs.h"
#include "ipctabs.h"
#include "ipccmdtabs.h"
#include "mmaptabs.h"
#include "mounttabs.h"
#include "open-flagtabs.h"
#include "persontabs.h"
#include "prottabs.h"
#include "ptracetabs.h"
#include "recvtabs.h"
#include "rlimittabs.h"
#include "seektabs.h"
#include "socktabs.h"
#include "socktypetabs.h"
#include "signaltabs.h"
#include "clocktabs.h"
#include "typetabs.h"
#include "nfprototabs.h"
#include "icmptypetabs.h"
#include "seccomptabs.h"
#include "accesstabs.h"
#include "prctl_opttabs.h"
#include "schedtabs.h"
#include "shm_modetabs.h"
#include "sockoptnametabs.h"
#include "sockleveltabs.h"
#include "ipoptnametabs.h"
#include "ip6optnametabs.h"
#include "tcpoptnametabs.h"
#include "pktoptnametabs.h"
#include "umounttabs.h"
#include "ioctlreqtabs.h"
#include "tty_named_keys.h"
Data Structures
struct string_buf
Macros
#define ADDR_NO_RANDOMIZE 0x0040000
#define SEMOP 1
#define SEMGET 2
#define SEMCTL 3
#define SEMTIMEDOP 4
#define MSGSND 11
#define MSGRCV 12
#define MSGGET 13
#define MSGCTL 14
#define SHMAT 21
#define SHMDT 22
#define SHMGET 23
#define SHMCTL 24
#define DIPC 25
#define MASK(x) (1U << (x))
#define SCHED_RESET_ON_FORK 0x40000000
#define E(SEQ, NAME) SEQ "\0" NAME "\0"
#define SECCOMP_RET_ACTION 0x7fff0000U
Enumerations
enum avc_t {
AVC_UNSET, AVC_DENIED, AVC_GRANTED, AVC_UNSET,
AVC_DENIED, AVC_GRANTED
}
enum success_t {
S_UNSET =-1, S_FAILED, S_SUCCESS, S_UNSET =-1,
S_FAILED, S_SUCCESS
}
Functions
int set_escape_mode (auparse_esc_t mode)
char * au_unescape (char *buf)
void aulookup_destroy_uid_list (void)
void aulookup_destroy_gid_list (void)
int lookup_type (const char *name)
const char * interpret (const rnode *r)
int auparse_interp_adjust_type (int rtype, const char *name, const char *val)
const char * auparse_do_interpretation (int type, const idata *id)
Macro Definition Documentation
#define ADDR_NO_RANDOMIZE 0x0040000
Definition at line 57 of file interpret.c.
#define DIPC 25
Definition at line 74 of file interpret.c.
#define E (SEQ, NAME) SEQ "\0" NAME "\0"
Referenced by downheap().
#define MASK (x) (1U << (x))
#define MSGCTL 14
Definition at line 69 of file interpret.c.
#define MSGGET 13
Definition at line 68 of file interpret.c.
#define MSGRCV 12
Definition at line 67 of file interpret.c.
#define MSGSND 11
Definition at line 66 of file interpret.c.
#define SCHED_RESET_ON_FORK 0x40000000
Definition at line 1563 of file interpret.c.
#define SECCOMP_RET_ACTION 0x7fff0000U
Definition at line 2430 of file interpret.c.
#define SEMCTL 3
Definition at line 64 of file interpret.c.
#define SEMGET 2
Definition at line 63 of file interpret.c.
#define SEMOP 1
Definition at line 62 of file interpret.c.
#define SEMTIMEDOP 4
Definition at line 65 of file interpret.c.
#define SHMAT 21
Definition at line 70 of file interpret.c.
#define SHMCTL 24
Definition at line 73 of file interpret.c.
#define SHMDT 22
Definition at line 71 of file interpret.c.
#define SHMGET 23
Definition at line 72 of file interpret.c.
Enumeration Type Documentation
enum avc_t
Enumerator
AVC_UNSET
AVC_DENIED
AVC_GRANTED
AVC_UNSET
AVC_DENIED
AVC_GRANTED
Definition at line 114 of file interpret.c.
enum success_t
Enumerator
S_UNSET
S_FAILED
S_SUCCESS
S_UNSET
S_FAILED
S_SUCCESS
Definition at line 115 of file interpret.c.
Function Documentation
char* au_unescape (char * buf)
Definition at line 284 of file interpret.c.
void aulookup_destroy_gid_list (void)
Definition at line 432 of file interpret.c.
Referenced by auparse_destroy(), and main().
void aulookup_destroy_uid_list (void)
Definition at line 383 of file interpret.c.
Referenced by auparse_destroy(), and main().
const char* auparse_do_interpretation (int type, const idata * id)
Definition at line 2530 of file interpret.c.
References AUPARSE_ESC_RAW, AUPARSE_TYPE_A0, AUPARSE_TYPE_A1, AUPARSE_TYPE_A2, AUPARSE_TYPE_A3, AUPARSE_TYPE_ADDR, AUPARSE_TYPE_ARCH, AUPARSE_TYPE_CAP_BITMAP, AUPARSE_TYPE_CAPABILITY, AUPARSE_TYPE_ESCAPED, AUPARSE_TYPE_EXIT, AUPARSE_TYPE_FLAGS, AUPARSE_TYPE_GID, AUPARSE_TYPE_ICMPTYPE, AUPARSE_TYPE_LIST, AUPARSE_TYPE_MAC_LABEL, AUPARSE_TYPE_MMAP, AUPARSE_TYPE_MODE, AUPARSE_TYPE_MODE_SHORT, AUPARSE_TYPE_NFPROTO, AUPARSE_TYPE_OFLAG, AUPARSE_TYPE_PERM, AUPARSE_TYPE_PERSONALITY, AUPARSE_TYPE_PROCTITLE, AUPARSE_TYPE_PROMISC, AUPARSE_TYPE_PROTOCOL, AUPARSE_TYPE_SECCOMP, AUPARSE_TYPE_SESSION, AUPARSE_TYPE_SIGNAL, AUPARSE_TYPE_SOCKADDR, AUPARSE_TYPE_SUCCESS, AUPARSE_TYPE_SYSCALL, AUPARSE_TYPE_TTY_DATA, AUPARSE_TYPE_UID, AUPARSE_TYPE_UNCLASSIFIED, and print_list().
Referenced by interpret().
int auparse_interp_adjust_type (int rtype, const char * name, const char * val)
Definition at line 2490 of file interpret.c.
References AUDIT_ADD_GROUP, AUDIT_CRYPTO_KEY_USER, AUDIT_DEL_GROUP, AUDIT_GRP_MGMT, AUDIT_NETFILTER_PKT, AUDIT_USER_TTY, AUPARSE_TYPE_ADDR, AUPARSE_TYPE_ESCAPED, AUPARSE_TYPE_FLAGS, AUPARSE_TYPE_GID, AUPARSE_TYPE_MODE_SHORT, AUPARSE_TYPE_UNCLASSIFIED, lookup_type(), and auparse_test::type.
Referenced by interpret(), and nvlist_get_cur_type().
const char* interpret (const rnode * r)
Definition at line 2461 of file interpret.c.
References _rnode::a0, _rnode::a1, auparse_do_interpretation(), auparse_interp_adjust_type(), _nvnode::interp_val, _rnode::machine, _rnode::nv, _rnode::syscall, auparse_test::type, and _rnode::type.
int lookup_type (const char * name)
Definition at line 2452 of file interpret.c.
References AUPARSE_TYPE_UNCLASSIFIED.
Referenced by auparse_interp_adjust_type().
int set_escape_mode (auparse_esc_t mode)
Definition at line 264 of file interpret.c.
References AUPARSE_ESC_SHELL_QUOTE.
Referenced by auparse_set_escape_mode().