audit: auparse/interpret.h File Reference
interpret.h File Reference
#include "config.h"
#include "private.h"
#include "rnode.h"
#include <time.h>
Functions
int lookup_type (const char *name)
const char * interpret (const rnode *r)
void aulookup_destroy_uid_list (void)
void aulookup_destroy_gid_list (void)
char * au_unescape (char *buf)
hidden_proto (lookup_type)
hidden_proto (interpret)
hidden_proto (aulookup_destroy_uid_list)
hidden_proto (aulookup_destroy_gid_list)
hidden_proto (au_unescape)
Function Documentation
char* au_unescape (char * buf)
Definition at line 284 of file interpret.c.
void aulookup_destroy_gid_list (void)
Definition at line 432 of file interpret.c.
void aulookup_destroy_uid_list (void)
Definition at line 383 of file interpret.c.
hidden_proto (lookup_type)
hidden_proto (interpret)
hidden_proto (aulookup_destroy_uid_list)
hidden_proto (aulookup_destroy_gid_list)
hidden_proto (au_unescape)
const char* interpret (const rnode * r)
Definition at line 2461 of file interpret.c.
References _rnode::a0, _rnode::a1, auparse_do_interpretation(), auparse_interp_adjust_type(), _nvnode::interp_val, _rnode::machine, _rnode::nv, _rnode::syscall, auparse_test::type, and _rnode::type.
int lookup_type (const char * name)
Definition at line 2452 of file interpret.c.
References AUPARSE_TYPE_UNCLASSIFIED.
Referenced by auparse_interp_adjust_type().