audit: lib/private.h File Reference
private.h File Reference
#include "dso.h"
Data Structures
struct auditd_remote_message_wrapper
Macros
#define AUDIT_RMW_HEADER_SIZE 16
#define AUDIT_RMW_MAGIC 0xff0000feUL
#define AUDIT_RMW_HEADER_VERSION 0
#define AUDIT_RMW_TYPE_REPLYMASK 0x40000000
#define AUDIT_RMW_TYPE_FATALMASK 0x20000000
#define AUDIT_RMW_TYPE_WARNMASK 0x10000000
#define AUDIT_RMW_TYPE_DETAILMASK 0x0fffffff
#define AUDIT_RMW_TYPE_MESSAGE 0x00000000
#define AUDIT_RMW_TYPE_HEARTBEAT 0x00000001
#define AUDIT_RMW_TYPE_ACK 0x40000000
#define AUDIT_RMW_TYPE_ENDING 0x40000001
#define AUDIT_RMW_TYPE_DISKLOW 0x50000001
#define AUDIT_RMW_TYPE_DISKFULL 0x60000001
#define AUDIT_RMW_TYPE_DISKERROR 0x60000002
#define _AUDIT_RMW_PUTN32(header, i, v)
#define _AUDIT_RMW_PUTN16(header, i, v)
#define _AUDIT_RMW_GETN32(header, i)
#define _AUDIT_RMW_GETN16(header, i) ((uint32_t)(header[i] & 0xFF) | ((uint32_t)(header[i+1] & 0xFF)<<8))
#define AUDIT_RMW_PACK_HEADER(header, mver, type, len, seq)
#define AUDIT_RMW_IS_MAGIC(header, length) (length >= 4 && _AUDIT_RMW_GETN32 (header,0) == AUDIT_RMW_MAGIC)
#define AUDIT_RMW_UNPACK_HEADER(header, hver, mver, type, len, seq)
Enumerations
enum hide_t { REAL_ERR, HIDE_IT }
Functions
void audit_msg (int priority, const char *fmt,...)
int audit_send (int fd, int type, const void *data, unsigned int size)
int audit_send_user_message (int fd, int type, hide_t hide_err, const char *message)
hidden_proto (audit_send_user_message)
hidden_proto (audit_add_watch_dir)
hidden_proto (audit_detect_machine)
hidden_proto (audit_request_status)
hidden_proto (audit_rule_syscall_data)
hidden_proto (audit_rule_syscallbyname_data)
hidden_proto (audit_set_feature)
hidden_proto (audit_request_features)
hidden_proto (audit_elf_to_machine)
hidden_proto (audit_machine_to_elf)
hidden_proto (audit_msg_type_to_name)
hidden_proto (audit_name_to_errno)
hidden_proto (audit_name_to_field)
hidden_proto (audit_name_to_machine)
hidden_proto (audit_name_to_msg_type)
hidden_proto (audit_name_to_syscall)
hidden_proto (audit_operator_to_symbol)
hidden_proto (audit_name_to_ftype)
hidden_proto (audit_get_reply)
char * audit_strsplit_r (char *s, char **savedpp)
char * audit_strsplit (char *s)
Variables
int _audit_permadded
int _audit_archadded
int _audit_syscalladded
unsigned int _audit_elf
Macro Definition Documentation
#define _AUDIT_RMW_GETN16 (header, i) ((uint32_t)(header[i] & 0xFF) | ((uint32_t)(header[i+1] & 0xFF)<<8))
Definition at line 98 of file private.h.
#define _AUDIT_RMW_GETN32 (header, i)
Value:
(((uint32_t)(header[i] & 0xFF)) |               \
     (((uint32_t)(header[i+1] & 0xFF))<<8) |        \
     (((uint32_t)(header[i+2] & 0xFF ))<<16) |      \
     (((uint32_t)(header[i+3] & 0xFF))<<24))
Definition at line 93 of file private.h.
#define _AUDIT_RMW_PUTN16 (header, i, v)
Value:
header[i] = v & 0xff;       \
    header[i+1] = (v>>8) & 0xff;
Definition at line 90 of file private.h.
#define _AUDIT_RMW_PUTN32 (header, i, v)
Value:
header[i] = v & 0xff;       \
    header[i+1] = (v>>8) & 0xff;    \
    header[i+2] = (v>>16) & 0xff;   \
    header[i+3] = (v>>24) & 0xff;
Definition at line 85 of file private.h.
#define AUDIT_RMW_HEADER_SIZE 16
Definition at line 60 of file private.h.
Referenced by auditd_tcp_listen_uninit().
#define AUDIT_RMW_HEADER_VERSION 0
Definition at line 64 of file private.h.
#define AUDIT_RMW_IS_MAGIC (header, length) (length >= 4 && _AUDIT_RMW_GETN32 (header,0) == AUDIT_RMW_MAGIC)
Definition at line 112 of file private.h.
#define AUDIT_RMW_MAGIC 0xff0000feUL
Definition at line 62 of file private.h.
#define AUDIT_RMW_PACK_HEADER (header, mver, type, len, seq)
Value:
_AUDIT_RMW_PUTN32 (header,0, AUDIT_RMW_MAGIC); \
    header[4] = AUDIT_RMW_HEADER_VERSION;  \
    header[5] = mver;  \
    _AUDIT_RMW_PUTN32 (header,6, type);  \
    _AUDIT_RMW_PUTN16 (header,10, len); \
    _AUDIT_RMW_PUTN32 (header,12, seq);
Definition at line 104 of file private.h.
Referenced by auditd_tcp_listen_uninit().
#define AUDIT_RMW_TYPE_ACK 0x40000000
Definition at line 78 of file private.h.
#define AUDIT_RMW_TYPE_DETAILMASK 0x0fffffff
Definition at line 73 of file private.h.
#define AUDIT_RMW_TYPE_DISKERROR 0x60000002
Definition at line 82 of file private.h.
#define AUDIT_RMW_TYPE_DISKFULL 0x60000001
Definition at line 81 of file private.h.
#define AUDIT_RMW_TYPE_DISKLOW 0x50000001
Definition at line 80 of file private.h.
#define AUDIT_RMW_TYPE_ENDING 0x40000001
Definition at line 79 of file private.h.
Referenced by auditd_tcp_listen_uninit().
#define AUDIT_RMW_TYPE_FATALMASK 0x20000000
Definition at line 69 of file private.h.
#define AUDIT_RMW_TYPE_HEARTBEAT 0x00000001
Definition at line 77 of file private.h.
#define AUDIT_RMW_TYPE_MESSAGE 0x00000000
Definition at line 76 of file private.h.
#define AUDIT_RMW_TYPE_REPLYMASK 0x40000000
Definition at line 67 of file private.h.
#define AUDIT_RMW_TYPE_WARNMASK 0x10000000
Definition at line 71 of file private.h.
#define AUDIT_RMW_UNPACK_HEADER (header, hver, mver, type, len, seq)
Value:
hver = header[4]; \
    mver = header[5]; \
    type = _AUDIT_RMW_GETN32 (header,6); \
    len = _AUDIT_RMW_GETN16 (header,10); \
    seq = _AUDIT_RMW_GETN32 (header,12);
Definition at line 115 of file private.h.
Enumeration Type Documentation
enum hide_t
Enumerator
REAL_ERR
HIDE_IT
Definition at line 31 of file private.h.
Function Documentation
void audit_msg (int priority, const char * fmt, ...)
Definition at line 40 of file message.c.
References DBG_NO, MSG_QUIET, and MSG_SYSLOG.
int audit_send (int fd, int type, const void * data, unsigned int size)
Definition at line 205 of file netlink.c.
References MAX_AUDIT_MESSAGE_LENGTH, audit_message::nlh, and auparse_test::type.
Referenced by audit_add_rule_data(), audit_delete_rule_data(), audit_make_equivalent(), audit_request_features(), audit_request_rules_list_data(), audit_request_signal_info(), audit_request_status(), audit_send_user_message(), audit_set_backlog_limit(), audit_set_backlog_wait_time(), audit_set_enabled(), audit_set_failure(), audit_set_feature(), audit_set_pid(), audit_set_rate_limit(), audit_trim_subtrees(), and delete_all_rules().
int audit_send_user_message (int fd, int type, hide_t hide_err, const char * message)
Definition at line 41 of file deprecated.c.
References AUDIT_FIRST_USER_MSG, AUDIT_LAST_USER_MSG, audit_send(), and HIDE_IT.
Referenced by audit_log_acct_message(), audit_log_semanage_message(), audit_log_user_avc_message(), audit_log_user_comm_message(), audit_log_user_command(), and audit_log_user_message().
char* audit_strsplit (char * s)
Definition at line 60 of file strsplit.c.
References s.
char* audit_strsplit_r (char * s, char ** savedpp)
Definition at line 28 of file strsplit.c.
References s.
hidden_proto (audit_send_user_message)
hidden_proto (audit_add_watch_dir)
hidden_proto (audit_detect_machine)
hidden_proto (audit_request_status)
hidden_proto (audit_rule_syscall_data)
hidden_proto (audit_rule_syscallbyname_data)
hidden_proto (audit_set_feature)
hidden_proto (audit_request_features)
hidden_proto (audit_elf_to_machine)
hidden_proto (audit_machine_to_elf)
hidden_proto (audit_msg_type_to_name)
hidden_proto (audit_name_to_errno)
hidden_proto (audit_name_to_field)
hidden_proto (audit_name_to_machine)
hidden_proto (audit_name_to_msg_type)
hidden_proto (audit_name_to_syscall)
hidden_proto (audit_operator_to_symbol)
hidden_proto (audit_name_to_ftype)
hidden_proto (audit_get_reply)
Variable Documentation
int _audit_archadded
Definition at line 83 of file libaudit.c.
Referenced by audit_rule_fieldpair_data().
unsigned int _audit_elf
Definition at line 85 of file libaudit.c.
Referenced by audit_rule_fieldpair_data(), audit_rule_syscallbyname_data(), and check_rule_mismatch().
int _audit_permadded
Definition at line 82 of file libaudit.c.
Referenced by audit_add_watch_dir(), and audit_rule_fieldpair_data().
int _audit_syscalladded
Definition at line 84 of file libaudit.c.
Referenced by audit_rule_fieldpair_data().