audit: lib/libaudit.c File Reference
libaudit.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <ctype.h>
#include <time.h>
#include <pwd.h>
#include <grp.h>
#include <errno.h>
#include <sys/poll.h>
#include <sys/utsname.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <limits.h>
#include <sys/types.h>
#include "libaudit.h"
#include "private.h"
#include "errormsg.h"
Data Structures
struct nv_pair
struct kw_pair
struct nv_list
struct libaudit_conf
Macros
#define CONFIG_FILE "/etc/libaudit.conf"
Functions
int audit_request_status (int fd)
int get_auditfail_action (auditfail_t *failmode)
int audit_set_enabled (int fd, uint32_t enabled)
int audit_is_enabled (int fd)
int audit_set_failure (int fd, uint32_t failure)
int audit_set_pid (int fd, uint32_t pid, rep_wait_t wmode)
int audit_set_rate_limit (int fd, uint32_t limit)
int audit_set_backlog_limit (int fd, uint32_t limit)
int audit_set_backlog_wait_time (int fd, uint32_t bwt)
int audit_set_feature (int fd, unsigned feature, unsigned value, unsigned lock)
int audit_request_features (int fd)
int audit_set_loginuid_immutable (int fd)
int audit_request_rules_list_data (int fd)
int audit_request_signal_info (int fd)
int audit_update_watch_perms (struct audit_rule_data *rule, int perms)
int audit_add_watch (struct audit_rule_data **rulep, const char *path)
int audit_add_dir (struct audit_rule_data **rulep, const char *path)
int audit_add_watch_dir (int type, struct audit_rule_data **rulep, const char *path)
int audit_add_rule_data (int fd, struct audit_rule_data *rule, int flags, int action)
int audit_delete_rule_data (int fd, struct audit_rule_data *rule, int flags, int action)
int audit_trim_subtrees (int fd)
int audit_make_equivalent (int fd, const char *mount_point, const char *subtree)
uid_t audit_getloginuid (void)
int audit_setloginuid (uid_t uid)
int audit_rule_syscall_data (struct audit_rule_data *rule, int scall)
int audit_rule_syscallbyname_data (struct audit_rule_data *rule, const char *scall)
int audit_rule_interfield_comp_data (struct audit_rule_data **rulep, const char *pair, int flags)
int audit_determine_machine (const char *arch)
int audit_rule_fieldpair_data (struct audit_rule_data **rulep, const char *pair, int flags)
void audit_rule_free_data (struct audit_rule_data *rule)
int audit_detect_machine (void)
void audit_number_to_errmsg (int errnumber, const char *opt)
Variables
int _audit_permadded = 0
int _audit_archadded = 0
int _audit_syscalladded = 0
unsigned int _audit_elf = 0U
Macro Definition Documentation
#define CONFIG_FILE "/etc/libaudit.conf"
Definition at line 48 of file libaudit.c.
Referenced by get_auditfail_action().
Function Documentation
int audit_add_dir (struct audit_rule_data ** rulep, const char * path)
Definition at line 622 of file libaudit.c.
References audit_add_watch_dir().
int audit_add_rule_data (int fd, struct audit_rule_data * rule, int flags, int action)
Definition at line 673 of file libaudit.c.
References audit_msg, and audit_send().
int audit_add_watch (struct audit_rule_data ** rulep, const char * path)
Definition at line 617 of file libaudit.c.
References audit_add_watch_dir().
int audit_add_watch_dir (int type, struct audit_rule_data ** rulep, const char * path)
Definition at line 627 of file libaudit.c.
References _audit_permadded, audit_msg, audit_rule_syscallbyname_data(), and auparse_test::type.
Referenced by audit_add_dir(), and audit_add_watch().
int audit_delete_rule_data (int fd, struct audit_rule_data * rule, int flags, int action)
Definition at line 694 of file libaudit.c.
References audit_msg, and audit_send().
int audit_detect_machine (void)
Definition at line 1568 of file libaudit.c.
References audit_name_to_machine().
Referenced by audit_determine_machine(), audit_rule_syscallbyname_data(), check_params(), and main().
int audit_determine_machine (const char * arch)
Definition at line 1146 of file libaudit.c.
References audit_detect_machine(), audit_elf_to_machine(), audit_name_to_machine(), MACH_86_64, MACH_AARCH64, MACH_ARM, MACH_IA64, MACH_PPC, MACH_PPC64, MACH_PPC64LE, MACH_S390, MACH_S390X, and MACH_X86.
Referenced by audit_rule_fieldpair_data(), and check_params().
uid_t audit_getloginuid (void)
Definition at line 766 of file libaudit.c.
References auparse_test::uid.
Referenced by main().
int audit_is_enabled (int fd)
Definition at line 357 of file libaudit.c.
References audit_get_reply(), audit_request_status(), GET_REPLY_NONBLOCKING, audit_reply::status, and audit_reply::type.
Referenced by main().
int audit_make_equivalent (int fd, const char * mount_point, const char * subtree)
Definition at line 735 of file libaudit.c.
References audit_msg, and audit_send().
void audit_number_to_errmsg (int errnumber, const char * opt)
Definition at line 1579 of file libaudit.c.
References auparse_test::key.
int audit_request_features (int fd)
Definition at line 539 of file libaudit.c.
References AUDIT_GET_FEATURE, audit_msg, and audit_send().
Referenced by report_status().
int audit_request_rules_list_data (int fd)
Definition at line 569 of file libaudit.c.
References audit_msg, and audit_send().
Referenced by audit_request_rule_list(), and delete_all_rules().
int audit_request_signal_info (int fd)
Definition at line 579 of file libaudit.c.
References audit_msg, and audit_send().
Referenced by main().
int audit_request_status (int fd)
Definition at line 109 of file libaudit.c.
References audit_msg, and audit_send().
Referenced by audit_is_enabled(), and report_status().
int audit_rule_fieldpair_data (struct audit_rule_data ** rulep, const char * pair, int flags)
Definition at line 1227 of file libaudit.c.
References _audit_archadded, _audit_elf, _audit_permadded, _audit_syscalladded, auparse_test::arch, audit_determine_machine(), audit_elf_to_machine(), AUDIT_FILTER_EXCLUDE, audit_machine_to_elf(), audit_msg, audit_name_to_errno(), audit_name_to_field(), audit_name_to_ftype(), audit_name_to_msg_type(), AUDIT_OBJ_GID, and AUDIT_OBJ_UID.
void audit_rule_free_data (struct audit_rule_data * rule)
Definition at line 1538 of file libaudit.c.
int audit_rule_interfield_comp_data (struct audit_rule_data ** rulep, const char * pair, int flags)
Definition at line 866 of file libaudit.c.
References AUDIT_COMPARE_AUID_TO_EUID, AUDIT_COMPARE_AUID_TO_FSUID, AUDIT_COMPARE_AUID_TO_OBJ_UID, AUDIT_COMPARE_AUID_TO_SUID, AUDIT_COMPARE_EGID_TO_FSGID, AUDIT_COMPARE_EGID_TO_OBJ_GID, AUDIT_COMPARE_EGID_TO_SGID, AUDIT_COMPARE_EUID_TO_FSUID, AUDIT_COMPARE_EUID_TO_OBJ_UID, AUDIT_COMPARE_EUID_TO_SUID, AUDIT_COMPARE_FSGID_TO_OBJ_GID, AUDIT_COMPARE_FSUID_TO_OBJ_UID, AUDIT_COMPARE_GID_TO_EGID, AUDIT_COMPARE_GID_TO_FSGID, AUDIT_COMPARE_GID_TO_OBJ_GID, AUDIT_COMPARE_GID_TO_SGID, AUDIT_COMPARE_SGID_TO_FSGID, AUDIT_COMPARE_SGID_TO_OBJ_GID, AUDIT_COMPARE_SUID_TO_FSUID, AUDIT_COMPARE_SUID_TO_OBJ_UID, AUDIT_COMPARE_UID_TO_AUID, AUDIT_COMPARE_UID_TO_EUID, AUDIT_COMPARE_UID_TO_FSUID, AUDIT_COMPARE_UID_TO_OBJ_UID, AUDIT_COMPARE_UID_TO_SUID, AUDIT_FIELD_COMPARE, audit_name_to_field(), AUDIT_OBJ_GID, and AUDIT_OBJ_UID.
int audit_rule_syscall_data (struct audit_rule_data * rule, int scall)
Definition at line 826 of file libaudit.c.
Referenced by audit_rule_syscallbyname_data().
int audit_rule_syscallbyname_data (struct audit_rule_data * rule, const char * scall)
Definition at line 838 of file libaudit.c.
References _audit_elf, audit_detect_machine(), audit_elf_to_machine(), audit_name_to_syscall(), and audit_rule_syscall_data().
Referenced by audit_add_watch_dir(), check_rule_mismatch(), and parse_syscall().
int audit_set_backlog_limit (int fd, uint32_t limit)
Definition at line 480 of file libaudit.c.
References audit_msg, and audit_send().
int audit_set_backlog_wait_time (int fd, uint32_t bwt)
Definition at line 496 of file libaudit.c.
References audit_msg, and audit_send().
int audit_set_enabled (int fd, uint32_t enabled)
Definition at line 338 of file libaudit.c.
References audit_msg, and audit_send().
Referenced by main().
int audit_set_failure (int fd, uint32_t failure)
Definition at line 411 of file libaudit.c.
References audit_msg, and audit_send().
int audit_set_feature (int fd, unsigned feature, unsigned value, unsigned lock)
Definition at line 514 of file libaudit.c.
References audit_msg, audit_send(), and AUDIT_SET_FEATURE.
Referenced by audit_set_loginuid_immutable().
int audit_set_loginuid_immutable (int fd)
Definition at line 559 of file libaudit.c.
References audit_set_feature().
int audit_set_pid (int fd, uint32_t pid, rep_wait_t wmode)
Definition at line 430 of file libaudit.c.
References audit_get_reply(), audit_msg, audit_send(), GET_REPLY_NONBLOCKING, auparse_test::pid, and WAIT_NO.
Referenced by main().
int audit_set_rate_limit (int fd, uint32_t limit)
Definition at line 464 of file libaudit.c.
References audit_msg, and audit_send().
int audit_setloginuid (uid_t uid)
Definition at line 794 of file libaudit.c.
References audit_msg.
int audit_trim_subtrees (int fd)
Definition at line 722 of file libaudit.c.
References audit_msg, and audit_send().
int audit_update_watch_perms (struct audit_rule_data * rule, int perms)
Definition at line 589 of file libaudit.c.
int get_auditfail_action (auditfail_t * failmode)
Definition at line 325 of file libaudit.c.
References clear_config(), config, and CONFIG_FILE.
Variable Documentation
int _audit_archadded = 0
Definition at line 83 of file libaudit.c.
Referenced by audit_rule_fieldpair_data().
unsigned int _audit_elf = 0U
Definition at line 85 of file libaudit.c.
Referenced by audit_rule_fieldpair_data(), audit_rule_syscallbyname_data(), and check_rule_mismatch().
int _audit_permadded = 0
Definition at line 82 of file libaudit.c.
Referenced by audit_add_watch_dir(), and audit_rule_fieldpair_data().
int _audit_syscalladded = 0
Definition at line 84 of file libaudit.c.
Referenced by audit_rule_fieldpair_data().