audit: lib/libaudit.h File Reference
libaudit.h File Reference
#include <asm/types.h>
#include <stdint.h>
#include <sys/socket.h>
#include <linux/netlink.h>
#include <linux/audit.h>
#include <stdarg.h>
#include <syslog.h>
Data Structures
struct audit_sig_info
struct audit_message
struct audit_reply
struct audit_dispatcher_header
Macros
#define AUDIT_FIRST_USER_MSG 1100 /* First user space message */
#define AUDIT_LAST_USER_MSG 1199 /* Last user space message */
#define AUDIT_USER_AUTH 1100 /* User system access authentication */
#define AUDIT_USER_ACCT 1101 /* User system access authorization */
#define AUDIT_USER_MGMT 1102 /* User acct attribute change */
#define AUDIT_CRED_ACQ 1103 /* User credential acquired */
#define AUDIT_CRED_DISP 1104 /* User credential disposed */
#define AUDIT_USER_START 1105 /* User session start */
#define AUDIT_USER_END 1106 /* User session end */
#define AUDIT_USER_AVC 1107 /* User space avc message */
#define AUDIT_USER_CHAUTHTOK 1108 /* User acct password or pin changed */
#define AUDIT_USER_ERR 1109 /* User acct state error */
#define AUDIT_CRED_REFR 1110 /* User credential refreshed */
#define AUDIT_USYS_CONFIG 1111 /* User space system config change */
#define AUDIT_USER_LOGIN 1112 /* User has logged in */
#define AUDIT_USER_LOGOUT 1113 /* User has logged out */
#define AUDIT_ADD_USER 1114 /* User account added */
#define AUDIT_DEL_USER 1115 /* User account deleted */
#define AUDIT_ADD_GROUP 1116 /* Group account added */
#define AUDIT_DEL_GROUP 1117 /* Group account deleted */
#define AUDIT_DAC_CHECK 1118 /* User space DAC check results */
#define AUDIT_CHGRP_ID 1119 /* User space group ID changed */
#define AUDIT_TEST 1120 /* Used for test success messages */
#define AUDIT_TRUSTED_APP 1121 /* Trusted app msg - freestyle text */
#define AUDIT_USER_SELINUX_ERR 1122 /* SE Linux user space error */
#define AUDIT_USER_CMD 1123 /* User shell command and args */
#define AUDIT_USER_TTY 1124 /* Non-ICANON TTY input meaning */
#define AUDIT_CHUSER_ID 1125 /* Changed user ID supplemental data */
#define AUDIT_GRP_AUTH 1126 /* Authentication for group password */
#define AUDIT_SYSTEM_BOOT 1127 /* System boot */
#define AUDIT_SYSTEM_SHUTDOWN 1128 /* System shutdown */
#define AUDIT_SYSTEM_RUNLEVEL 1129 /* System runlevel change */
#define AUDIT_SERVICE_START 1130 /* Service (daemon) start */
#define AUDIT_SERVICE_STOP 1131 /* Service (daemon) stop */
#define AUDIT_GRP_MGMT 1132 /* Group account attr was modified */
#define AUDIT_GRP_CHAUTHTOK 1133 /* Group acct password or pin changed */
#define AUDIT_MAC_CHECK 1134 /* User space MAC decision results */
#define AUDIT_FIRST_DAEMON 1200
#define AUDIT_LAST_DAEMON 1299
#define AUDIT_DAEMON_RECONFIG 1204 /* Auditd should reconfigure */
#define AUDIT_DAEMON_ROTATE 1205 /* Auditd should rotate logs */
#define AUDIT_DAEMON_RESUME 1206 /* Auditd should resume logging */
#define AUDIT_DAEMON_ACCEPT 1207 /* Auditd accepted remote connection */
#define AUDIT_DAEMON_CLOSE 1208 /* Auditd closed remote connection */
#define AUDIT_FIRST_EVENT 1300
#define AUDIT_LAST_EVENT 1399
#define AUDIT_FIRST_SELINUX 1400
#define AUDIT_LAST_SELINUX 1499
#define AUDIT_FIRST_APPARMOR 1500
#define AUDIT_LAST_APPARMOR 1599
#define AUDIT_AA 1500 /* Not upstream yet */
#define AUDIT_APPARMOR_AUDIT 1501
#define AUDIT_APPARMOR_ALLOWED 1502
#define AUDIT_APPARMOR_DENIED 1503
#define AUDIT_APPARMOR_HINT 1504
#define AUDIT_APPARMOR_STATUS 1505
#define AUDIT_APPARMOR_ERROR 1506
#define AUDIT_FIRST_KERN_CRYPTO_MSG 1600
#define AUDIT_LAST_KERN_CRYPTO_MSG 1699
#define AUDIT_FIRST_KERN_ANOM_MSG 1700
#define AUDIT_LAST_KERN_ANOM_MSG 1799
#define AUDIT_INTEGRITY_FIRST_MSG 1800
#define AUDIT_INTEGRITY_LAST_MSG 1899
#define AUDIT_INTEGRITY_DATA 1800 /* Data integrity verification */
#define AUDIT_INTEGRITY_METADATA 1801
#define AUDIT_INTEGRITY_STATUS 1802 /* Integrity enable status */
#define AUDIT_INTEGRITY_HASH 1803 /* Integrity HASH type */
#define AUDIT_INTEGRITY_PCR 1804 /* PCR invalidation msgs */
#define AUDIT_INTEGRITY_RULE 1805 /* Policy rule */
#define AUDIT_FIRST_ANOM_MSG 2100
#define AUDIT_LAST_ANOM_MSG 2199
#define AUDIT_ANOM_LOGIN_FAILURES 2100
#define AUDIT_ANOM_LOGIN_TIME 2101
#define AUDIT_ANOM_LOGIN_SESSIONS 2102
#define AUDIT_ANOM_LOGIN_ACCT 2103
#define AUDIT_ANOM_LOGIN_LOCATION 2104
#define AUDIT_ANOM_MAX_DAC 2105
#define AUDIT_ANOM_MAX_MAC 2106
#define AUDIT_ANOM_AMTU_FAIL 2107
#define AUDIT_ANOM_RBAC_FAIL 2108
#define AUDIT_ANOM_RBAC_INTEGRITY_FAIL 2109
#define AUDIT_ANOM_CRYPTO_FAIL 2110
#define AUDIT_ANOM_ACCESS_FS 2111
#define AUDIT_ANOM_EXEC 2112
#define AUDIT_ANOM_MK_EXEC 2113
#define AUDIT_ANOM_ADD_ACCT 2114
#define AUDIT_ANOM_DEL_ACCT 2115
#define AUDIT_ANOM_MOD_ACCT 2116
#define AUDIT_ANOM_ROOT_TRANS 2117
#define AUDIT_FIRST_ANOM_RESP 2200
#define AUDIT_LAST_ANOM_RESP 2299
#define AUDIT_RESP_ANOMALY 2200 /* Anomaly not reacted to */
#define AUDIT_RESP_ALERT 2201 /* Alert email was sent */
#define AUDIT_RESP_KILL_PROC 2202 /* Kill program */
#define AUDIT_RESP_TERM_ACCESS 2203 /* Terminate session */
#define AUDIT_RESP_ACCT_REMOTE 2204 /* Acct locked from remote access*/
#define AUDIT_RESP_ACCT_LOCK_TIMED 2205 /* User acct locked for time */
#define AUDIT_RESP_ACCT_UNLOCK_TIMED 2206 /* User acct unlocked from time */
#define AUDIT_RESP_ACCT_LOCK 2207 /* User acct was locked */
#define AUDIT_RESP_TERM_LOCK 2208 /* Terminal was locked */
#define AUDIT_RESP_SEBOOL 2209 /* Set an SE Linux boolean */
#define AUDIT_RESP_EXEC 2210 /* Execute a script */
#define AUDIT_RESP_SINGLE 2211 /* Go to single user mode */
#define AUDIT_RESP_HALT 2212 /* take the system down */
#define AUDIT_FIRST_USER_LSPP_MSG 2300
#define AUDIT_LAST_USER_LSPP_MSG 2399
#define AUDIT_USER_ROLE_CHANGE 2300 /* User changed to a new role */
#define AUDIT_ROLE_ASSIGN 2301 /* Admin assigned user to role */
#define AUDIT_ROLE_REMOVE 2302 /* Admin removed user from role */
#define AUDIT_LABEL_OVERRIDE 2303 /* Admin is overriding a label */
#define AUDIT_LABEL_LEVEL_CHANGE 2304 /* Object's level was changed */
#define AUDIT_USER_LABELED_EXPORT 2305 /* Object exported with label */
#define AUDIT_USER_UNLABELED_EXPORT 2306 /* Object exported without label */
#define AUDIT_DEV_ALLOC 2307 /* Device was allocated */
#define AUDIT_DEV_DEALLOC 2308 /* Device was deallocated */
#define AUDIT_FS_RELABEL 2309 /* Filesystem relabeled */
#define AUDIT_USER_MAC_POLICY_LOAD 2310 /* Userspc daemon loaded policy */
#define AUDIT_ROLE_MODIFY 2311 /* Admin modified a role */
#define AUDIT_USER_MAC_CONFIG_CHANGE 2312 /* Change made to MAC policy */
#define AUDIT_FIRST_CRYPTO_MSG 2400
#define AUDIT_CRYPTO_TEST_USER 2400 /* Crypto test results */
#define AUDIT_CRYPTO_PARAM_CHANGE_USER 2401 /* Crypto attribute change */
#define AUDIT_CRYPTO_LOGIN 2402 /* Logged in as crypto officer */
#define AUDIT_CRYPTO_LOGOUT 2403 /* Logged out from crypto */
#define AUDIT_CRYPTO_KEY_USER 2404 /* Create,delete,negotiate */
#define AUDIT_CRYPTO_FAILURE_USER 2405 /* Fail decrypt,encrypt,randomiz */
#define AUDIT_CRYPTO_REPLAY_USER 2406 /* Crypto replay detected */
#define AUDIT_CRYPTO_SESSION
#define AUDIT_CRYPTO_IKE_SA
#define AUDIT_CRYPTO_IPSEC_SA
#define AUDIT_LAST_CRYPTO_MSG 2499
#define AUDIT_FIRST_VIRT_MSG 2500
#define AUDIT_VIRT_CONTROL 2500 /* Start, Pause, Stop VM */
#define AUDIT_VIRT_RESOURCE 2501 /* Resource assignment */
#define AUDIT_VIRT_MACHINE_ID 2502 /* Binding of label to VM */
#define AUDIT_LAST_VIRT_MSG 2599
#define AUDIT_FIRST_USER_MSG2 2100 /* More userspace messages */
#define AUDIT_LAST_USER_MSG2 2999
#define AUDIT_SET_FEATURE 1018 /* Turn an audit feature on or off */
#define AUDIT_GET_FEATURE 1019 /* Get which features are enabled */
#define AUDIT_MMAP 1323 /* Descriptor and flags in mmap */
#define AUDIT_NETFILTER_PKT 1324 /* Packets traversing netfilter chains */
#define AUDIT_NETFILTER_CFG 1325 /* Netfilter chain modifications */
#define AUDIT_SECCOMP 1326 /* Secure Computing event */
#define AUDIT_PROCTITLE 1327 /* Process Title info */
#define AUDIT_FEATURE_CHANGE 1328 /* Audit feature changed value */
#define AUDIT_ANOM_LINK 1702 /* Suspicious use of file links */
#define AUDIT_KEY_SEPARATOR 0x01
#define AUDIT_FILTER_EXCLUDE AUDIT_FILTER_TYPE
#define AUDIT_FILTER_MASK 0x07 /* Mask to get actual filter */
#define AUDIT_FILTER_UNSET 0x80 /* This value means filter is unset */
#define AUDIT_OBJ_UID 109
#define AUDIT_OBJ_GID 110
#define AUDIT_FIELD_COMPARE 111
#define AUDIT_COMPARE_UID_TO_OBJ_UID 1
#define AUDIT_COMPARE_GID_TO_OBJ_GID 2
#define AUDIT_COMPARE_EUID_TO_OBJ_UID 3
#define AUDIT_COMPARE_EGID_TO_OBJ_GID 4
#define AUDIT_COMPARE_AUID_TO_OBJ_UID 5
#define AUDIT_COMPARE_SUID_TO_OBJ_UID 6
#define AUDIT_COMPARE_SGID_TO_OBJ_GID 7
#define AUDIT_COMPARE_FSUID_TO_OBJ_UID 8
#define AUDIT_COMPARE_FSGID_TO_OBJ_GID 9
#define AUDIT_COMPARE_UID_TO_AUID 10
#define AUDIT_COMPARE_UID_TO_EUID 11
#define AUDIT_COMPARE_UID_TO_FSUID 12
#define AUDIT_COMPARE_UID_TO_SUID 13
#define AUDIT_COMPARE_AUID_TO_FSUID 14
#define AUDIT_COMPARE_AUID_TO_SUID 15
#define AUDIT_COMPARE_AUID_TO_EUID 16
#define AUDIT_COMPARE_EUID_TO_SUID 17
#define AUDIT_COMPARE_EUID_TO_FSUID 18
#define AUDIT_COMPARE_SUID_TO_FSUID 19
#define AUDIT_COMPARE_GID_TO_EGID 20
#define AUDIT_COMPARE_GID_TO_FSGID 21
#define AUDIT_COMPARE_GID_TO_SGID 22
#define AUDIT_COMPARE_EGID_TO_FSGID 23
#define AUDIT_COMPARE_EGID_TO_SGID 24
#define AUDIT_COMPARE_SGID_TO_FSGID 25
#define EM_ARM 40
#define EM_AARCH64 183
#define AUDIT_ARCH_AARCH64 (EM_AARCH64|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)
#define AUDIT_ARCH_PPC64LE (EM_PPC64|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)
#define MAX_AUDIT_MESSAGE_LENGTH 8970
#define AUDISP_PROTOCOL_VER 0
Enumerations
enum machine_t {
MACH_X86 =0, MACH_86_64, MACH_IA64, MACH_PPC64,
MACH_PPC, MACH_S390X, MACH_S390, MACH_ALPHA,
MACH_ARM, MACH_AARCH64, MACH_PPC64LE
}
enum auditfail_t { FAIL_IGNORE =0, FAIL_LOG, FAIL_TERMINATE }
enum message_t { MSG_STDERR, MSG_SYSLOG, MSG_QUIET }
enum debug_message_t { DBG_NO, DBG_YES }
enum reply_t { GET_REPLY_BLOCKING =0, GET_REPLY_NONBLOCKING }
enum rep_wait_t { WAIT_NO, WAIT_YES }
Functions
void set_aumessage_mode (message_t mode, debug_message_t debug)
int audit_open (void)
void audit_close (int fd)
int audit_get_reply (int fd, struct audit_reply *rep, reply_t block, int peek)
uid_t audit_getloginuid (void)
int audit_setloginuid (uid_t uid)
int audit_detect_machine (void)
int audit_determine_machine (const char *arch)
int audit_name_to_field (const char *field)
const char * audit_field_to_name (int field)
int audit_name_to_syscall (const char *sc, int machine)
const char * audit_syscall_to_name (int sc, int machine)
int audit_name_to_flag (const char *flag)
const char * audit_flag_to_name (int flag)
int audit_name_to_action (const char *action)
const char * audit_action_to_name (int action)
int audit_name_to_msg_type (const char *msg_type)
const char * audit_msg_type_to_name (int msg_type)
int audit_name_to_machine (const char *machine)
const char * audit_machine_to_name (int machine)
unsigned int audit_machine_to_elf (int machine)
int audit_elf_to_machine (unsigned int elf)
const char * audit_operator_to_symbol (int op)
int audit_name_to_errno (const char *error)
const char * audit_errno_to_name (int error)
int audit_name_to_ftype (const char *name)
const char * audit_ftype_to_name (int ftype)
void audit_number_to_errmsg (int errnumber, const char *opt)
int audit_request_status (int fd)
int audit_is_enabled (int fd)
int get_auditfail_action (auditfail_t *failmode)
int audit_request_features (int fd)
int audit_set_pid (int fd, uint32_t pid, rep_wait_t wmode)
int audit_set_enabled (int fd, uint32_t enabled)
int audit_set_failure (int fd, uint32_t failure)
int audit_set_rate_limit (int fd, uint32_t limit)
int audit_set_backlog_limit (int fd, uint32_t limit)
int audit_set_backlog_wait_time (int fd, uint32_t bwt)
int audit_set_feature (int fd, unsigned feature, unsigned value, unsigned lock)
int audit_set_loginuid_immutable (int fd)
int audit_request_rules_list_data (int fd)
int audit_request_signal_info (int fd)
int audit_update_watch_perms (struct audit_rule_data *rule, int perms)
int audit_add_watch (struct audit_rule_data **rulep, const char *path)
int audit_add_dir (struct audit_rule_data **rulep, const char *path)
int audit_add_watch_dir (int type, struct audit_rule_data **rulep, const char *path)
int audit_trim_subtrees (int fd)
int audit_make_equivalent (int fd, const char *mount_point, const char *subtree)
int audit_add_rule_data (int fd, struct audit_rule_data *rule, int flags, int action)
int audit_delete_rule_data (int fd, struct audit_rule_data *rule, int flags, int action)
int audit_value_needs_encoding (const char *str, unsigned int len)
char * audit_encode_value (char *final, const char *buf, unsigned int size)
char * audit_encode_nv_string (const char *name, const char *value, unsigned int vlen)
int audit_log_user_message (int audit_fd, int type, const char *message, const char *hostname, const char *addr, const char *tty, int result)
int audit_log_user_comm_message (int audit_fd, int type, const char *message, const char *comm, const char *hostname, const char *addr, const char *tty, int result)
int audit_log_acct_message (int audit_fd, int type, const char *pgname, const char *op, const char *name, unsigned int id, const char *host, const char *addr, const char *tty, int result)
int audit_log_user_avc_message (int audit_fd, int type, const char *message, const char *hostname, const char *addr, const char *tty, uid_t uid)
int audit_log_semanage_message (int audit_fd, int type, const char *pgname, const char *op, const char *name, unsigned int id, const char *new_seuser, const char *new_role, const char *new_range, const char *old_seuser, const char *old_role, const char *old_range, const char *host, const char *addr, const char *tty, int result)
int audit_log_user_command (int audit_fd, int type, const char *command, const char *tty, int result)
int audit_rule_syscall_data (struct audit_rule_data *rule, int scall)
int audit_rule_syscallbyname_data (struct audit_rule_data *rule, const char *scall)
int audit_rule_fieldpair_data (struct audit_rule_data **rulep, const char *pair, int flags)
int audit_rule_interfield_comp_data (struct audit_rule_data **rulep, const char *pair, int flags)
void audit_rule_free_data (struct audit_rule_data *rule)
Macro Definition Documentation
#define AUDISP_PROTOCOL_VER 0
Definition at line 434 of file libaudit.h.
Referenced by dispatch_event().
#define AUDIT_AA 1500 /* Not upstream yet */
Definition at line 115 of file libaudit.h.
#define AUDIT_ADD_GROUP 1116 /* Group account added */
Definition at line 78 of file libaudit.h.
Referenced by auparse_interp_adjust_type(), and classify_conf().
#define AUDIT_ADD_USER 1114 /* User account added */
Definition at line 76 of file libaudit.h.
Referenced by classify_conf().
#define AUDIT_ANOM_ACCESS_FS 2111
Definition at line 154 of file libaudit.h.
#define AUDIT_ANOM_ADD_ACCT 2114
Definition at line 157 of file libaudit.h.
#define AUDIT_ANOM_AMTU_FAIL 2107
Definition at line 150 of file libaudit.h.
#define AUDIT_ANOM_CRYPTO_FAIL 2110
Definition at line 153 of file libaudit.h.
#define AUDIT_ANOM_DEL_ACCT 2115
Definition at line 158 of file libaudit.h.
#define AUDIT_ANOM_EXEC 2112
Definition at line 155 of file libaudit.h.
#define AUDIT_ANOM_LINK 1702 /* Suspicious use of file links */
Definition at line 257 of file libaudit.h.
#define AUDIT_ANOM_LOGIN_ACCT 2103
Definition at line 146 of file libaudit.h.
#define AUDIT_ANOM_LOGIN_FAILURES 2100
Definition at line 143 of file libaudit.h.
#define AUDIT_ANOM_LOGIN_LOCATION 2104
Definition at line 147 of file libaudit.h.
#define AUDIT_ANOM_LOGIN_SESSIONS 2102
Definition at line 145 of file libaudit.h.
#define AUDIT_ANOM_LOGIN_TIME 2101
Definition at line 144 of file libaudit.h.
#define AUDIT_ANOM_MAX_DAC 2105
Definition at line 148 of file libaudit.h.
#define AUDIT_ANOM_MAX_MAC 2106
Definition at line 149 of file libaudit.h.
#define AUDIT_ANOM_MK_EXEC 2113
Definition at line 156 of file libaudit.h.
#define AUDIT_ANOM_MOD_ACCT 2116
Definition at line 159 of file libaudit.h.
#define AUDIT_ANOM_RBAC_FAIL 2108
Definition at line 151 of file libaudit.h.
#define AUDIT_ANOM_RBAC_INTEGRITY_FAIL 2109
Definition at line 152 of file libaudit.h.
#define AUDIT_ANOM_ROOT_TRANS 2117
Definition at line 160 of file libaudit.h.
#define AUDIT_APPARMOR_ALLOWED 1502
Definition at line 117 of file libaudit.h.
#define AUDIT_APPARMOR_AUDIT 1501
Definition at line 116 of file libaudit.h.
#define AUDIT_APPARMOR_DENIED 1503
Definition at line 118 of file libaudit.h.
#define AUDIT_APPARMOR_ERROR 1506
Definition at line 121 of file libaudit.h.
#define AUDIT_APPARMOR_HINT 1504
Definition at line 119 of file libaudit.h.
#define AUDIT_APPARMOR_STATUS 1505
Definition at line 120 of file libaudit.h.
#define AUDIT_ARCH_AARCH64 (EM_AARCH64|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)
Definition at line 363 of file libaudit.h.
#define AUDIT_ARCH_PPC64LE (EM_PPC64|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)
Definition at line 367 of file libaudit.h.
#define AUDIT_CHGRP_ID 1119 /* User space group ID changed */
Definition at line 81 of file libaudit.h.
#define AUDIT_CHUSER_ID 1125 /* Changed user ID supplemental data */
Definition at line 87 of file libaudit.h.
#define AUDIT_COMPARE_AUID_TO_EUID 16
Definition at line 325 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_AUID_TO_FSUID 14
Definition at line 319 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_AUID_TO_OBJ_UID 5
Definition at line 292 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_AUID_TO_SUID 15
Definition at line 322 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_EGID_TO_FSGID 23
Definition at line 346 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_EGID_TO_OBJ_GID 4
Definition at line 289 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_EGID_TO_SGID 24
Definition at line 349 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_EUID_TO_FSUID 18
Definition at line 331 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_EUID_TO_OBJ_UID 3
Definition at line 286 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_EUID_TO_SUID 17
Definition at line 328 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_FSGID_TO_OBJ_GID 9
Definition at line 304 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_FSUID_TO_OBJ_UID 8
Definition at line 301 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_GID_TO_EGID 20
Definition at line 337 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_GID_TO_FSGID 21
Definition at line 340 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_GID_TO_OBJ_GID 2
Definition at line 283 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_GID_TO_SGID 22
Definition at line 343 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_SGID_TO_FSGID 25
Definition at line 352 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_SGID_TO_OBJ_GID 7
Definition at line 298 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_SUID_TO_FSUID 19
Definition at line 334 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_SUID_TO_OBJ_UID 6
Definition at line 295 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_UID_TO_AUID 10
Definition at line 307 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_UID_TO_EUID 11
Definition at line 310 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_UID_TO_FSUID 12
Definition at line 313 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_UID_TO_OBJ_UID 1
Definition at line 280 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_COMPARE_UID_TO_SUID 13
Definition at line 316 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_CRED_ACQ 1103 /* User credential acquired */
Definition at line 65 of file libaudit.h.
#define AUDIT_CRED_DISP 1104 /* User credential disposed */
Definition at line 66 of file libaudit.h.
#define AUDIT_CRED_REFR 1110 /* User credential refreshed */
Definition at line 72 of file libaudit.h.
#define AUDIT_CRYPTO_FAILURE_USER 2405 /* Fail decrypt,encrypt,randomiz */
Definition at line 200 of file libaudit.h.
#define AUDIT_CRYPTO_IKE_SA
Value:
2408 /* Record parameters related to
                        IKE SA */
Definition at line 204 of file libaudit.h.
#define AUDIT_CRYPTO_IPSEC_SA
Value:
2409 /* Record parameters related to
                        IPSEC SA */
Definition at line 206 of file libaudit.h.
#define AUDIT_CRYPTO_KEY_USER 2404 /* Create,delete,negotiate */
Definition at line 199 of file libaudit.h.
Referenced by auparse_interp_adjust_type().
#define AUDIT_CRYPTO_LOGIN 2402 /* Logged in as crypto officer */
Definition at line 197 of file libaudit.h.
#define AUDIT_CRYPTO_LOGOUT 2403 /* Logged out from crypto */
Definition at line 198 of file libaudit.h.
#define AUDIT_CRYPTO_PARAM_CHANGE_USER 2401 /* Crypto attribute change */
Definition at line 196 of file libaudit.h.
#define AUDIT_CRYPTO_REPLAY_USER 2406 /* Crypto replay detected */
Definition at line 201 of file libaudit.h.
#define AUDIT_CRYPTO_SESSION
Value:
2407 /* Record parameters set during
                        TLS session establishment */
Definition at line 202 of file libaudit.h.
#define AUDIT_CRYPTO_TEST_USER 2400 /* Crypto test results */
Definition at line 195 of file libaudit.h.
#define AUDIT_DAC_CHECK 1118 /* User space DAC check results */
Definition at line 80 of file libaudit.h.
#define AUDIT_DAEMON_ACCEPT 1207 /* Auditd accepted remote connection */
Definition at line 103 of file libaudit.h.
Referenced by extract_search_items().
#define AUDIT_DAEMON_CLOSE 1208 /* Auditd closed remote connection */
Definition at line 104 of file libaudit.h.
Referenced by extract_search_items().
#define AUDIT_DAEMON_RECONFIG 1204 /* Auditd should reconfigure */
Definition at line 100 of file libaudit.h.
Referenced by dispatch_event(), and enqueue_event().
#define AUDIT_DAEMON_RESUME 1206 /* Auditd should resume logging */
Definition at line 102 of file libaudit.h.
Referenced by extract_search_items().
#define AUDIT_DAEMON_ROTATE 1205 /* Auditd should rotate logs */
Definition at line 101 of file libaudit.h.
Referenced by dispatch_event(), enqueue_event(), and extract_search_items().
#define AUDIT_DEL_GROUP 1117 /* Group account deleted */
Definition at line 79 of file libaudit.h.
Referenced by auparse_interp_adjust_type(), and classify_conf().
#define AUDIT_DEL_USER 1115 /* User account deleted */
Definition at line 77 of file libaudit.h.
Referenced by classify_conf().
#define AUDIT_DEV_ALLOC 2307 /* Device was allocated */
Definition at line 187 of file libaudit.h.
#define AUDIT_DEV_DEALLOC 2308 /* Device was deallocated */
Definition at line 188 of file libaudit.h.
#define AUDIT_FEATURE_CHANGE 1328 /* Audit feature changed value */
Definition at line 253 of file libaudit.h.
#define AUDIT_FIELD_COMPARE 111
Definition at line 276 of file libaudit.h.
Referenced by audit_rule_interfield_comp_data().
#define AUDIT_FILTER_EXCLUDE AUDIT_FILTER_TYPE
Definition at line 264 of file libaudit.h.
Referenced by audit_rule_fieldpair_data().
#define AUDIT_FILTER_MASK 0x07 /* Mask to get actual filter */
Definition at line 265 of file libaudit.h.
#define AUDIT_FILTER_UNSET 0x80 /* This value means filter is unset */
Definition at line 266 of file libaudit.h.
Referenced by main().
#define AUDIT_FIRST_ANOM_MSG 2100
Definition at line 141 of file libaudit.h.
Referenced by auparse_next_event(), create_search_criteria(), and main().
#define AUDIT_FIRST_ANOM_RESP 2200
Definition at line 162 of file libaudit.h.
#define AUDIT_FIRST_APPARMOR 1500
Definition at line 112 of file libaudit.h.
#define AUDIT_FIRST_CRYPTO_MSG 2400
Definition at line 194 of file libaudit.h.
#define AUDIT_FIRST_DAEMON 1200
Definition at line 98 of file libaudit.h.
Referenced by enqueue_event().
#define AUDIT_FIRST_EVENT 1300
Definition at line 106 of file libaudit.h.
Referenced by auparse_next_event().
#define AUDIT_FIRST_KERN_ANOM_MSG 1700
Definition at line 127 of file libaudit.h.
Referenced by create_search_criteria(), extract_search_items(), and main().
#define AUDIT_FIRST_KERN_CRYPTO_MSG 1600
Definition at line 124 of file libaudit.h.
#define AUDIT_FIRST_SELINUX 1400
Definition at line 109 of file libaudit.h.
#define AUDIT_FIRST_USER_LSPP_MSG 2300
Definition at line 178 of file libaudit.h.
#define AUDIT_FIRST_USER_MSG 1100 /* First user space message */
Definition at line 60 of file libaudit.h.
Referenced by audit_send_user_message(), check_params(), and extract_search_items().
#define AUDIT_FIRST_USER_MSG2 2100 /* More userspace messages */
Definition at line 219 of file libaudit.h.
Referenced by extract_search_items().
#define AUDIT_FIRST_VIRT_MSG 2500
Definition at line 211 of file libaudit.h.
Referenced by create_search_criteria().
#define AUDIT_FS_RELABEL 2309 /* Filesystem relabeled */
Definition at line 189 of file libaudit.h.
#define AUDIT_GET_FEATURE 1019 /* Get which features are enabled */
Definition at line 229 of file libaudit.h.
Referenced by audit_print_reply(), and audit_request_features().
#define AUDIT_GRP_AUTH 1126 /* Authentication for group password */
Definition at line 88 of file libaudit.h.
#define AUDIT_GRP_CHAUTHTOK 1133 /* Group acct password or pin changed */
Definition at line 95 of file libaudit.h.
#define AUDIT_GRP_MGMT 1132 /* Group account attr was modified */
Definition at line 94 of file libaudit.h.
Referenced by auparse_interp_adjust_type().
#define AUDIT_INTEGRITY_DATA 1800 /* Data integrity verification */
Definition at line 133 of file libaudit.h.
Referenced by extract_search_items().
#define AUDIT_INTEGRITY_FIRST_MSG 1800
Definition at line 130 of file libaudit.h.
#define AUDIT_INTEGRITY_HASH 1803 /* Integrity HASH type */
Definition at line 136 of file libaudit.h.
#define AUDIT_INTEGRITY_LAST_MSG 1899
Definition at line 131 of file libaudit.h.
#define AUDIT_INTEGRITY_METADATA 1801
Definition at line 134 of file libaudit.h.
#define AUDIT_INTEGRITY_PCR 1804 /* PCR invalidation msgs */
Definition at line 137 of file libaudit.h.
#define AUDIT_INTEGRITY_RULE 1805 /* Policy rule */
Definition at line 138 of file libaudit.h.
#define AUDIT_INTEGRITY_STATUS 1802 /* Integrity enable status */
Definition at line 135 of file libaudit.h.
#define AUDIT_KEY_SEPARATOR 0x01
Definition at line 261 of file libaudit.h.
#define AUDIT_LABEL_LEVEL_CHANGE 2304 /* Object's level was changed */
Definition at line 184 of file libaudit.h.
#define AUDIT_LABEL_OVERRIDE 2303 /* Admin is overriding a label */
Definition at line 183 of file libaudit.h.
#define AUDIT_LAST_ANOM_MSG 2199
Definition at line 142 of file libaudit.h.
Referenced by create_search_criteria(), and main().
#define AUDIT_LAST_ANOM_RESP 2299
Definition at line 163 of file libaudit.h.
#define AUDIT_LAST_APPARMOR 1599
Definition at line 113 of file libaudit.h.
#define AUDIT_LAST_CRYPTO_MSG 2499
Definition at line 209 of file libaudit.h.
#define AUDIT_LAST_DAEMON 1299
Definition at line 99 of file libaudit.h.
Referenced by enqueue_event().
#define AUDIT_LAST_EVENT 1399
Definition at line 107 of file libaudit.h.
#define AUDIT_LAST_KERN_ANOM_MSG 1799
Definition at line 128 of file libaudit.h.
Referenced by create_search_criteria(), and main().
#define AUDIT_LAST_KERN_CRYPTO_MSG 1699
Definition at line 125 of file libaudit.h.
#define AUDIT_LAST_SELINUX 1499
Definition at line 110 of file libaudit.h.
#define AUDIT_LAST_USER_LSPP_MSG 2399
Definition at line 179 of file libaudit.h.
#define AUDIT_LAST_USER_MSG 1199 /* Last user space message */
Definition at line 61 of file libaudit.h.
Referenced by audit_send_user_message().
#define AUDIT_LAST_USER_MSG2 2999
Definition at line 220 of file libaudit.h.
#define AUDIT_LAST_VIRT_MSG 2599
Definition at line 216 of file libaudit.h.
Referenced by check_params(), and create_search_criteria().
#define AUDIT_MAC_CHECK 1134 /* User space MAC decision results */
Definition at line 96 of file libaudit.h.
#define AUDIT_MMAP 1323 /* Descriptor and flags in mmap */
Definition at line 233 of file libaudit.h.
Referenced by extract_search_items().
#define AUDIT_NETFILTER_CFG 1325 /* Netfilter chain modifications */
Definition at line 240 of file libaudit.h.
Referenced by extract_search_items().
#define AUDIT_NETFILTER_PKT 1324 /* Packets traversing netfilter chains */
Definition at line 237 of file libaudit.h.
Referenced by auparse_interp_adjust_type(), and extract_search_items().
#define AUDIT_OBJ_GID 110
Definition at line 273 of file libaudit.h.
Referenced by audit_rule_fieldpair_data(), and audit_rule_interfield_comp_data().
#define AUDIT_OBJ_UID 109
Definition at line 270 of file libaudit.h.
Referenced by audit_rule_fieldpair_data(), and audit_rule_interfield_comp_data().
#define AUDIT_PROCTITLE 1327 /* Process Title info */
Definition at line 248 of file libaudit.h.
#define AUDIT_RESP_ACCT_LOCK 2207 /* User acct was locked */
Definition at line 171 of file libaudit.h.
#define AUDIT_RESP_ACCT_LOCK_TIMED 2205 /* User acct locked for time */
Definition at line 169 of file libaudit.h.
#define AUDIT_RESP_ACCT_REMOTE 2204 /* Acct locked from remote access*/
Definition at line 168 of file libaudit.h.
#define AUDIT_RESP_ACCT_UNLOCK_TIMED 2206 /* User acct unlocked from time */
Definition at line 170 of file libaudit.h.
#define AUDIT_RESP_ALERT 2201 /* Alert email was sent */
Definition at line 165 of file libaudit.h.
#define AUDIT_RESP_ANOMALY 2200 /* Anomaly not reacted to */
Definition at line 164 of file libaudit.h.
#define AUDIT_RESP_EXEC 2210 /* Execute a script */
Definition at line 174 of file libaudit.h.
#define AUDIT_RESP_HALT 2212 /* take the system down */
Definition at line 176 of file libaudit.h.
#define AUDIT_RESP_KILL_PROC 2202 /* Kill program */
Definition at line 166 of file libaudit.h.
#define AUDIT_RESP_SEBOOL 2209 /* Set an SE Linux boolean */
Definition at line 173 of file libaudit.h.
#define AUDIT_RESP_SINGLE 2211 /* Go to single user mode */
Definition at line 175 of file libaudit.h.
#define AUDIT_RESP_TERM_ACCESS 2203 /* Terminate session */
Definition at line 167 of file libaudit.h.
#define AUDIT_RESP_TERM_LOCK 2208 /* Terminal was locked */
Definition at line 172 of file libaudit.h.
#define AUDIT_ROLE_ASSIGN 2301 /* Admin assigned user to role */
Definition at line 181 of file libaudit.h.
#define AUDIT_ROLE_MODIFY 2311 /* Admin modified a role */
Definition at line 191 of file libaudit.h.
#define AUDIT_ROLE_REMOVE 2302 /* Admin removed user from role */
Definition at line 182 of file libaudit.h.
#define AUDIT_SECCOMP 1326 /* Secure Computing event */
Definition at line 244 of file libaudit.h.
Referenced by extract_search_items().
#define AUDIT_SERVICE_START 1130 /* Service (daemon) start */
Definition at line 92 of file libaudit.h.
#define AUDIT_SERVICE_STOP 1131 /* Service (daemon) stop */
Definition at line 93 of file libaudit.h.
#define AUDIT_SET_FEATURE 1018 /* Turn an audit feature on or off */
Definition at line 225 of file libaudit.h.
Referenced by audit_set_feature().
#define AUDIT_SYSTEM_BOOT 1127 /* System boot */
Definition at line 89 of file libaudit.h.
Referenced by main().
#define AUDIT_SYSTEM_RUNLEVEL 1129 /* System runlevel change */
Definition at line 91 of file libaudit.h.
#define AUDIT_SYSTEM_SHUTDOWN 1128 /* System shutdown */
Definition at line 90 of file libaudit.h.
Referenced by main().
#define AUDIT_TEST 1120 /* Used for test success messages */
Definition at line 82 of file libaudit.h.
#define AUDIT_TRUSTED_APP 1121 /* Trusted app msg - freestyle text */
Definition at line 83 of file libaudit.h.
#define AUDIT_USER_ACCT 1101 /* User system access authorization */
Definition at line 63 of file libaudit.h.
#define AUDIT_USER_AUTH 1100 /* User system access authentication */
Definition at line 62 of file libaudit.h.
#define AUDIT_USER_AVC 1107 /* User space avc message */
Definition at line 69 of file libaudit.h.
#define AUDIT_USER_CHAUTHTOK 1108 /* User acct password or pin changed */
Definition at line 70 of file libaudit.h.
#define AUDIT_USER_CMD 1123 /* User shell command and args */
Definition at line 85 of file libaudit.h.
#define AUDIT_USER_END 1106 /* User session end */
Definition at line 68 of file libaudit.h.
Referenced by main().
#define AUDIT_USER_ERR 1109 /* User acct state error */
Definition at line 71 of file libaudit.h.
#define AUDIT_USER_LABELED_EXPORT 2305 /* Object exported with label */
Definition at line 185 of file libaudit.h.
#define AUDIT_USER_LOGIN 1112 /* User has logged in */
Definition at line 74 of file libaudit.h.
Referenced by main().
#define AUDIT_USER_LOGOUT 1113 /* User has logged out */
Definition at line 75 of file libaudit.h.
#define AUDIT_USER_MAC_CONFIG_CHANGE 2312 /* Change made to MAC policy */
Definition at line 192 of file libaudit.h.
#define AUDIT_USER_MAC_POLICY_LOAD 2310 /* Userspc daemon loaded policy */
Definition at line 190 of file libaudit.h.
#define AUDIT_USER_MGMT 1102 /* User acct attribute change */
Definition at line 64 of file libaudit.h.
#define AUDIT_USER_ROLE_CHANGE 2300 /* User changed to a new role */
Definition at line 180 of file libaudit.h.
#define AUDIT_USER_SELINUX_ERR 1122 /* SE Linux user space error */
Definition at line 84 of file libaudit.h.
#define AUDIT_USER_START 1105 /* User session start */
Definition at line 67 of file libaudit.h.
#define AUDIT_USER_TTY 1124 /* Non-ICANON TTY input meaning */
Definition at line 86 of file libaudit.h.
Referenced by auparse_interp_adjust_type().
#define AUDIT_USER_UNLABELED_EXPORT 2306 /* Object exported without label */
Definition at line 186 of file libaudit.h.
#define AUDIT_USYS_CONFIG 1111 /* User space system config change */
Definition at line 73 of file libaudit.h.
Referenced by classify_conf().
#define AUDIT_VIRT_CONTROL 2500 /* Start, Pause, Stop VM */
Definition at line 212 of file libaudit.h.
Referenced by main().
#define AUDIT_VIRT_MACHINE_ID 2502 /* Binding of label to VM */
Definition at line 214 of file libaudit.h.
Referenced by main().
#define AUDIT_VIRT_RESOURCE 2501 /* Resource assignment */
Definition at line 213 of file libaudit.h.
Referenced by main().
#define EM_AARCH64 183
Definition at line 359 of file libaudit.h.
#define EM_ARM 40
Definition at line 356 of file libaudit.h.
#define MAX_AUDIT_MESSAGE_LENGTH 8970
Definition at line 384 of file libaudit.h.
Referenced by audit_log_acct_message(), audit_log_semanage_message(), audit_log_user_avc_message(), audit_log_user_comm_message(), audit_log_user_command(), audit_log_user_message(), audit_send(), enqueue_event(), enqueue_formatted_event(), init_event(), lol_add_record(), main(), and send_af_unix_binary().
Enumeration Type Documentation
enum auditfail_t
Enumerator
FAIL_IGNORE
FAIL_LOG
FAIL_TERMINATE
Definition at line 456 of file libaudit.h.
enum debug_message_t
Enumerator
DBG_NO
DBG_YES
Definition at line 464 of file libaudit.h.
enum machine_t
Enumerator
MACH_X86
MACH_86_64
MACH_IA64
MACH_PPC64
MACH_PPC
MACH_S390X
MACH_S390
MACH_ALPHA
MACH_ARM
MACH_AARCH64
MACH_PPC64LE
Definition at line 441 of file libaudit.h.
enum message_t
Enumerator
MSG_STDERR
MSG_SYSLOG
MSG_QUIET
Definition at line 463 of file libaudit.h.
enum rep_wait_t
Enumerator
WAIT_NO
WAIT_YES
Definition at line 507 of file libaudit.h.
enum reply_t
Enumerator
GET_REPLY_BLOCKING
GET_REPLY_NONBLOCKING
Definition at line 468 of file libaudit.h.
Function Documentation
const char* audit_action_to_name (int action)
Definition at line 221 of file lookup_table.c.
int audit_add_dir (struct audit_rule_data ** rulep, const char * path)
Definition at line 622 of file libaudit.c.
References audit_add_watch_dir().
int audit_add_rule_data (int fd, struct audit_rule_data * rule, int flags, int action)
Definition at line 673 of file libaudit.c.
References audit_msg, and audit_send().
int audit_add_watch (struct audit_rule_data ** rulep, const char * path)
Definition at line 617 of file libaudit.c.
References audit_add_watch_dir().
int audit_add_watch_dir (int type, struct audit_rule_data ** rulep, const char * path)
Definition at line 627 of file libaudit.c.
References _audit_permadded, audit_msg, audit_rule_syscallbyname_data(), and auparse_test::type.
Referenced by audit_add_dir(), and audit_add_watch().
void audit_close (int fd)
Definition at line 78 of file netlink.c.
Referenced by audit_print_reply().
int audit_delete_rule_data (int fd, struct audit_rule_data * rule, int flags, int action)
Definition at line 694 of file libaudit.c.
References audit_msg, and audit_send().
int audit_detect_machine (void)
Definition at line 1568 of file libaudit.c.
References audit_name_to_machine().
Referenced by audit_determine_machine(), audit_rule_syscallbyname_data(), check_params(), and main().
int audit_determine_machine (const char * arch)
Definition at line 1146 of file libaudit.c.
References audit_detect_machine(), audit_elf_to_machine(), audit_name_to_machine(), MACH_86_64, MACH_AARCH64, MACH_ARM, MACH_IA64, MACH_PPC, MACH_PPC64, MACH_PPC64LE, MACH_S390, MACH_S390X, and MACH_X86.
Referenced by audit_rule_fieldpair_data(), and check_params().
int audit_elf_to_machine (unsigned int elf)
Definition at line 290 of file lookup_table.c.
References AUDIT_ELF_NAMES, int_transtab::key, and int_transtab::lvalue.
Referenced by audit_determine_machine(), audit_rule_fieldpair_data(), audit_rule_syscallbyname_data(), aulookup_syscall(), and match().
char* audit_encode_nv_string (const char * name, const char * value, unsigned int vlen)
Definition at line 124 of file audit_logging.c.
References audit_encode_value(), and audit_value_needs_encoding().
char* audit_encode_value (char * final, const char * buf, unsigned int size)
Definition at line 102 of file audit_logging.c.
Referenced by audit_encode_nv_string(), audit_log_acct_message(), audit_log_semanage_message(), and audit_log_user_command().
const char* audit_errno_to_name (int error)
Definition at line 327 of file lookup_table.c.
const char* audit_field_to_name (int field)
Definition at line 101 of file lookup_table.c.
const char* audit_flag_to_name (int flag)
Definition at line 207 of file lookup_table.c.
const char* audit_ftype_to_name (int ftype)
Definition at line 351 of file lookup_table.c.
int audit_get_reply (int fd, struct audit_reply * rep, reply_t block, int peek)
Definition at line 89 of file netlink.c.
References audit_msg, GET_REPLY_NONBLOCKING, and audit_reply::msg.
Referenced by audit_is_enabled(), audit_set_pid(), and delete_all_rules().
uid_t audit_getloginuid (void)
Definition at line 766 of file libaudit.c.
References auparse_test::uid.
Referenced by main().
int audit_is_enabled (int fd)
Definition at line 357 of file libaudit.c.
References audit_get_reply(), audit_request_status(), GET_REPLY_NONBLOCKING, audit_reply::status, and audit_reply::type.
Referenced by main().
int audit_log_acct_message (int audit_fd, int type, const char * pgname, const char * op, const char * name, unsigned int id, const char * host, const char * addr, const char * tty, int result)
Definition at line 381 of file audit_logging.c.
References audit_encode_value(), audit_send_user_message(), audit_value_needs_encoding(), MAX_AUDIT_MESSAGE_LENGTH, MAX_USER, REAL_ERR, and TTY_PATH.
int audit_log_semanage_message (int audit_fd, int type, const char * pgname, const char * op, const char * name, unsigned int id, const char * new_seuser, const char * new_role, const char * new_range, const char * old_seuser, const char * old_role, const char * old_range, const char * host, const char * addr, const char * tty, int result)
Definition at line 551 of file audit_logging.c.
References audit_encode_value(), audit_send_user_message(), audit_value_needs_encoding(), MAX_AUDIT_MESSAGE_LENGTH, MAX_USER, REAL_ERR, and TTY_PATH.
int audit_log_user_avc_message (int audit_fd, int type, const char * message, const char * hostname, const char * addr, const char * tty, uid_t uid)
Definition at line 478 of file audit_logging.c.
References audit_msg_type_to_name(), audit_send_user_message(), MAX_AUDIT_MESSAGE_LENGTH, REAL_ERR, and TTY_PATH.
int audit_log_user_comm_message (int audit_fd, int type, const char * message, const char * comm, const char * hostname, const char * addr, const char * tty, int result)
Definition at line 307 of file audit_logging.c.
References audit_send_user_message(), HIDE_IT, MAX_AUDIT_MESSAGE_LENGTH, and TTY_PATH.
int audit_log_user_command (int audit_fd, int type, const char * command, const char * tty, int result)
Definition at line 656 of file audit_logging.c.
References audit_encode_value(), audit_send_user_message(), audit_value_needs_encoding(), HIDE_IT, MAX_AUDIT_MESSAGE_LENGTH, and TTY_PATH.
int audit_log_user_message (int audit_fd, int type, const char * message, const char * hostname, const char * addr, const char * tty, int result)
Definition at line 240 of file audit_logging.c.
References audit_send_user_message(), HIDE_IT, MAX_AUDIT_MESSAGE_LENGTH, and TTY_PATH.
unsigned int audit_machine_to_elf (int machine)
Definition at line 279 of file lookup_table.c.
References AUDIT_ELF_NAMES, auparse_test::key, and int_transtab::lvalue.
Referenced by audit_rule_fieldpair_data().
const char* audit_machine_to_name (int machine)
Definition at line 274 of file lookup_table.c.
Referenced by main().
int audit_make_equivalent (int fd, const char * mount_point, const char * subtree)
Definition at line 735 of file libaudit.c.
References audit_msg, and audit_send().
const char* audit_msg_type_to_name (int msg_type)
Definition at line 258 of file lookup_table.c.
Referenced by audit_log_user_avc_message(), auparse_get_type_name(), check_params(), light_test(), and print_per_event_item().
int audit_name_to_action (const char * action)
Definition at line 212 of file lookup_table.c.
References auparse_test::res.
int audit_name_to_errno (const char * error)
Definition at line 307 of file lookup_table.c.
Referenced by audit_rule_fieldpair_data(), and check_params().
int audit_name_to_field (const char * field)
Definition at line 89 of file lookup_table.c.
References auparse_test::res.
Referenced by audit_rule_fieldpair_data(), and audit_rule_interfield_comp_data().
int audit_name_to_flag (const char * flag)
Definition at line 198 of file lookup_table.c.
References auparse_test::res.
int audit_name_to_ftype (const char * name)
Definition at line 339 of file lookup_table.c.
References auparse_test::res.
Referenced by audit_rule_fieldpair_data().
int audit_name_to_machine (const char * machine)
Definition at line 264 of file lookup_table.c.
References auparse_test::res.
Referenced by audit_detect_machine(), audit_determine_machine(), and main().
int audit_name_to_msg_type (const char * msg_type)
Definition at line 227 of file lookup_table.c.
References auparse_test::end.
Referenced by audit_rule_fieldpair_data().
int audit_name_to_syscall (const char * sc, int machine)
Definition at line 110 of file lookup_table.c.
References MACH_86_64, MACH_AARCH64, MACH_ALPHA, MACH_ARM, MACH_IA64, MACH_PPC, MACH_PPC64, MACH_PPC64LE, MACH_S390, MACH_S390X, MACH_X86, and auparse_test::res.
Referenced by audit_rule_syscallbyname_data(), check_params(), and main().
void audit_number_to_errmsg (int errnumber, const char * opt)
Definition at line 1579 of file libaudit.c.
References auparse_test::key.
int audit_open (void)
Definition at line 47 of file netlink.c.
References audit_msg, and NETLINK_AUDIT.
Referenced by main().
const char* audit_operator_to_symbol (int op)
Definition at line 300 of file lookup_table.c.
int audit_request_features (int fd)
Definition at line 539 of file libaudit.c.
References AUDIT_GET_FEATURE, audit_msg, and audit_send().
Referenced by report_status().
int audit_request_rules_list_data (int fd)
Definition at line 569 of file libaudit.c.
References audit_msg, and audit_send().
Referenced by audit_request_rule_list(), and delete_all_rules().
int audit_request_signal_info (int fd)
Definition at line 579 of file libaudit.c.
References audit_msg, and audit_send().
Referenced by main().
int audit_request_status (int fd)
Definition at line 109 of file libaudit.c.
References audit_msg, and audit_send().
Referenced by audit_is_enabled(), and report_status().
int audit_rule_fieldpair_data (struct audit_rule_data ** rulep, const char * pair, int flags)
Definition at line 1227 of file libaudit.c.
References _audit_archadded, _audit_elf, _audit_permadded, _audit_syscalladded, auparse_test::arch, audit_determine_machine(), audit_elf_to_machine(), AUDIT_FILTER_EXCLUDE, audit_machine_to_elf(), audit_msg, audit_name_to_errno(), audit_name_to_field(), audit_name_to_ftype(), audit_name_to_msg_type(), AUDIT_OBJ_GID, and AUDIT_OBJ_UID.
void audit_rule_free_data (struct audit_rule_data * rule)
Definition at line 1538 of file libaudit.c.
int audit_rule_interfield_comp_data (struct audit_rule_data ** rulep, const char * pair, int flags)
Definition at line 866 of file libaudit.c.
References AUDIT_COMPARE_AUID_TO_EUID, AUDIT_COMPARE_AUID_TO_FSUID, AUDIT_COMPARE_AUID_TO_OBJ_UID, AUDIT_COMPARE_AUID_TO_SUID, AUDIT_COMPARE_EGID_TO_FSGID, AUDIT_COMPARE_EGID_TO_OBJ_GID, AUDIT_COMPARE_EGID_TO_SGID, AUDIT_COMPARE_EUID_TO_FSUID, AUDIT_COMPARE_EUID_TO_OBJ_UID, AUDIT_COMPARE_EUID_TO_SUID, AUDIT_COMPARE_FSGID_TO_OBJ_GID, AUDIT_COMPARE_FSUID_TO_OBJ_UID, AUDIT_COMPARE_GID_TO_EGID, AUDIT_COMPARE_GID_TO_FSGID, AUDIT_COMPARE_GID_TO_OBJ_GID, AUDIT_COMPARE_GID_TO_SGID, AUDIT_COMPARE_SGID_TO_FSGID, AUDIT_COMPARE_SGID_TO_OBJ_GID, AUDIT_COMPARE_SUID_TO_FSUID, AUDIT_COMPARE_SUID_TO_OBJ_UID, AUDIT_COMPARE_UID_TO_AUID, AUDIT_COMPARE_UID_TO_EUID, AUDIT_COMPARE_UID_TO_FSUID, AUDIT_COMPARE_UID_TO_OBJ_UID, AUDIT_COMPARE_UID_TO_SUID, AUDIT_FIELD_COMPARE, audit_name_to_field(), AUDIT_OBJ_GID, and AUDIT_OBJ_UID.
int audit_rule_syscall_data (struct audit_rule_data * rule, int scall)
Definition at line 826 of file libaudit.c.
Referenced by audit_rule_syscallbyname_data().
int audit_rule_syscallbyname_data (struct audit_rule_data * rule, const char * scall)
Definition at line 838 of file libaudit.c.
References _audit_elf, audit_detect_machine(), audit_elf_to_machine(), audit_name_to_syscall(), and audit_rule_syscall_data().
Referenced by audit_add_watch_dir(), check_rule_mismatch(), and parse_syscall().
int audit_set_backlog_limit (int fd, uint32_t limit)
Definition at line 480 of file libaudit.c.
References audit_msg, and audit_send().
int audit_set_backlog_wait_time (int fd, uint32_t bwt)
Definition at line 496 of file libaudit.c.
References audit_msg, and audit_send().
int audit_set_enabled (int fd, uint32_t enabled)
Definition at line 338 of file libaudit.c.
References audit_msg, and audit_send().
Referenced by main().
int audit_set_failure (int fd, uint32_t failure)
Definition at line 411 of file libaudit.c.
References audit_msg, and audit_send().
int audit_set_feature (int fd, unsigned feature, unsigned value, unsigned lock)
Definition at line 514 of file libaudit.c.
References audit_msg, audit_send(), and AUDIT_SET_FEATURE.
Referenced by audit_set_loginuid_immutable().
int audit_set_loginuid_immutable (int fd)
Definition at line 559 of file libaudit.c.
References audit_set_feature().
int audit_set_pid (int fd, uint32_t pid, rep_wait_t wmode)
Definition at line 430 of file libaudit.c.
References audit_get_reply(), audit_msg, audit_send(), GET_REPLY_NONBLOCKING, auparse_test::pid, and WAIT_NO.
Referenced by main().
int audit_set_rate_limit (int fd, uint32_t limit)
Definition at line 464 of file libaudit.c.
References audit_msg, and audit_send().
int audit_setloginuid (uid_t uid)
Definition at line 794 of file libaudit.c.
References audit_msg.
const char* audit_syscall_to_name (int sc, int machine)
Definition at line 162 of file lookup_table.c.
References MACH_86_64, MACH_AARCH64, MACH_ALPHA, MACH_ARM, MACH_IA64, MACH_PPC, MACH_PPC64, MACH_PPC64LE, MACH_S390, MACH_S390X, and MACH_X86.
Referenced by aulookup_syscall(), and main().
int audit_trim_subtrees (int fd)
Definition at line 722 of file libaudit.c.
References audit_msg, and audit_send().
int audit_update_watch_perms (struct audit_rule_data * rule, int perms)
Definition at line 589 of file libaudit.c.
int audit_value_needs_encoding (const char * str, unsigned int len)
Definition at line 84 of file audit_logging.c.
Referenced by audit_encode_nv_string(), audit_log_acct_message(), audit_log_semanage_message(), and audit_log_user_command().
int get_auditfail_action (auditfail_t * failmode)
Definition at line 325 of file libaudit.c.
References clear_config(), config, and CONFIG_FILE.
void set_aumessage_mode (message_t mode, debug_message_t debug)
Definition at line 34 of file message.c.