audit: lib/lookup_table.c File Reference
lookup_table.c File Reference
#include "config.h"
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <ctype.h>
#include <errno.h>
#include "libaudit.h"
#include "gen_tables.h"
#include "private.h"
#include "i386_tables.h"
#include "ia64_tables.h"
#include "ppc_tables.h"
#include "s390_tables.h"
#include "s390x_tables.h"
#include "x86_64_tables.h"
#include "errtabs.h"
#include "ftypetabs.h"
#include "fieldtabs.h"
#include "msg_typetabs.h"
#include "actiontabs.h"
#include "flagtabs.h"
#include "machinetabs.h"
#include "optabs.h"
Data Structures
struct int_transtab
Macros
#define AUDIT_ELF_NAMES (sizeof(elftab)/sizeof(elftab[0]))
Functions
int audit_name_to_field (const char *field)
const char * audit_field_to_name (int field)
int audit_name_to_syscall (const char *sc, int machine)
const char * audit_syscall_to_name (int sc, int machine)
int audit_name_to_flag (const char *flag)
const char * audit_flag_to_name (int flag)
int audit_name_to_action (const char *action)
const char * audit_action_to_name (int action)
int audit_name_to_msg_type (const char *msg_type)
const char * audit_msg_type_to_name (int msg_type)
int audit_name_to_machine (const char *machine)
const char * audit_machine_to_name (int machine)
unsigned int audit_machine_to_elf (int machine)
int audit_elf_to_machine (unsigned int elf)
const char * audit_operator_to_symbol (int op)
int audit_name_to_errno (const char *error)
const char * audit_errno_to_name (int error)
int audit_name_to_ftype (const char *name)
const char * audit_ftype_to_name (int ftype)
Macro Definition Documentation
#define AUDIT_ELF_NAMES (sizeof(elftab)/sizeof(elftab[0]))
Definition at line 87 of file lookup_table.c.
Referenced by audit_elf_to_machine(), and audit_machine_to_elf().
Function Documentation
const char* audit_action_to_name (int action)
Definition at line 221 of file lookup_table.c.
int audit_elf_to_machine (unsigned int elf)
Definition at line 290 of file lookup_table.c.
References AUDIT_ELF_NAMES, int_transtab::key, and int_transtab::lvalue.
Referenced by audit_determine_machine(), audit_rule_fieldpair_data(), audit_rule_syscallbyname_data(), aulookup_syscall(), and match().
const char* audit_errno_to_name (int error)
Definition at line 327 of file lookup_table.c.
const char* audit_field_to_name (int field)
Definition at line 101 of file lookup_table.c.
const char* audit_flag_to_name (int flag)
Definition at line 207 of file lookup_table.c.
const char* audit_ftype_to_name (int ftype)
Definition at line 351 of file lookup_table.c.
unsigned int audit_machine_to_elf (int machine)
Definition at line 279 of file lookup_table.c.
References AUDIT_ELF_NAMES, auparse_test::key, and int_transtab::lvalue.
Referenced by audit_rule_fieldpair_data().
const char* audit_machine_to_name (int machine)
Definition at line 274 of file lookup_table.c.
Referenced by main().
const char* audit_msg_type_to_name (int msg_type)
Definition at line 258 of file lookup_table.c.
Referenced by audit_log_user_avc_message(), auparse_get_type_name(), check_params(), light_test(), and print_per_event_item().
int audit_name_to_action (const char * action)
Definition at line 212 of file lookup_table.c.
References auparse_test::res.
int audit_name_to_errno (const char * error)
Definition at line 307 of file lookup_table.c.
Referenced by audit_rule_fieldpair_data(), and check_params().
int audit_name_to_field (const char * field)
Definition at line 89 of file lookup_table.c.
References auparse_test::res.
Referenced by audit_rule_fieldpair_data(), and audit_rule_interfield_comp_data().
int audit_name_to_flag (const char * flag)
Definition at line 198 of file lookup_table.c.
References auparse_test::res.
int audit_name_to_ftype (const char * name)
Definition at line 339 of file lookup_table.c.
References auparse_test::res.
Referenced by audit_rule_fieldpair_data().
int audit_name_to_machine (const char * machine)
Definition at line 264 of file lookup_table.c.
References auparse_test::res.
Referenced by audit_detect_machine(), audit_determine_machine(), and main().
int audit_name_to_msg_type (const char * msg_type)
Definition at line 227 of file lookup_table.c.
References auparse_test::end.
Referenced by audit_rule_fieldpair_data().
int audit_name_to_syscall (const char * sc, int machine)
Definition at line 110 of file lookup_table.c.
References MACH_86_64, MACH_AARCH64, MACH_ALPHA, MACH_ARM, MACH_IA64, MACH_PPC, MACH_PPC64, MACH_PPC64LE, MACH_S390, MACH_S390X, MACH_X86, and auparse_test::res.
Referenced by audit_rule_syscallbyname_data(), check_params(), and main().
const char* audit_operator_to_symbol (int op)
Definition at line 300 of file lookup_table.c.
const char* audit_syscall_to_name (int sc, int machine)
Definition at line 162 of file lookup_table.c.
References MACH_86_64, MACH_AARCH64, MACH_ALPHA, MACH_ARM, MACH_IA64, MACH_PPC, MACH_PPC64, MACH_PPC64LE, MACH_S390, MACH_S390X, and MACH_X86.
Referenced by aulookup_syscall(), and main().