audit: auparse_test Namespace Reference
auparse_test Namespace Reference
Functions
def none_to_null
def walk_test
def light_test
def simple_search
def compound_search
def feed_callback
Variables
tuple srcdir = os.getenv('srcdir')
list buf
list files = [srcdir + "/test.log", srcdir + "/test2.log"]
string load_path = '../../bindings/python/build/lib.linux-i686-2.4'
tuple au = auparse.AuParser(auparse.AUSOURCE_BUFFER_ARRAY, buf)
int event_cnt = 1
int chunk_len = 3
tuple s_len = len(s)
int beg = 0
tuple end = min(s_len, beg + chunk_len)
list data = s[beg:end]
tuple f = open(srcdir + "/test.log")
int auid = 4294967295
int line = 1
tuple type = LOGIN(LOGIN)
int pid = 2027
int uid = 0
tuple arch = c000003e(x86_64)
int syscall = 188
tuple success = yes(yes)
int exit = 0
int a0 = 7
int a1 = 3958
int a2 = 5131
int a3 = 20
int items = 1
int gid = 0
int euid = 0
int suid = 0
int fsuid = 0
int egid = 0
int sgid = 0
int fsgid = 0
tuple tty = tty3(tty3)
string comm = "login"
string exe = "/bin/login"
tuple subj = system_u:system_r:local_login_t:s0-s0:c0.c255(system_u:system_r:local_login_t:s0-s0:c0.c255)
tuple hostname = ?(?)
tuple addr = ?(?)
tuple terminal = tty3(tty3)
tuple res = success(success)
tuple seresult = denied(denied)
tuple seperms = read,write(read,write)
string name = "maildrop"
tuple dev = hda7(hda7)
int ino = 14911367
tuple scontext = system_u:system_r:postfix_pickup_t:s0(system_u:system_r:postfix_pickup_t:s0)
tuple tcontext = system_u:object_r:postfix_spool_maildrop_t:s0(system_u:object_r:postfix_spool_maildrop_t:s0)
tuple tclass = dir(dir)
int ppid = 2013
tuple key = (null)
string cwd = "/var/spool/postfix"
int item = 0
int inode = 14911367
int mode = 040730
int ouid = 890
int ogid = 891
int rdev = 00
tuple obj = system_u:object_r:postfix_spool_maildrop_t:s0(system_u:object_r:postfix_spool_maildrop_t:s0)
tuple acct = root(root)
Function Documentation
def auparse_test.compound_search (au, how)
Definition at line 104 of file auparse_test.py.
def auparse_test.feed_callback (au, cb_event_type, event_cnt)
Definition at line 122 of file auparse_test.py.
References none_to_null().
def auparse_test.light_test (au)
Definition at line 62 of file auparse_test.py.
References none_to_null().
def auparse_test.none_to_null (s)
Definition at line 20 of file auparse_test.py.
Referenced by feed_callback(), light_test(), and walk_test().
def auparse_test.simple_search (au, source, where)
Definition at line 88 of file auparse_test.py.
def auparse_test.walk_test (au)
Definition at line 27 of file auparse_test.py.
References none_to_null().
Variable Documentation
int auparse_test.a0 = 7
Definition at line 30 of file auparse_test.ref.py.
int auparse_test.a1 = 3958
Definition at line 31 of file auparse_test.ref.py.
int auparse_test.a2 = 5131
Definition at line 32 of file auparse_test.ref.py.
int auparse_test.a3 = 20
Definition at line 33 of file auparse_test.ref.py.
tuple auparse_test.acct = root(root)
Definition at line 151 of file auparse_test.ref.py.
tuple auparse_test.addr = ?(?)
Definition at line 61 of file auparse_test.ref.py.
tuple auparse_test.arch = c000003e(x86_64)
Definition at line 26 of file auparse_test.ref.py.
Referenced by audit_rule_fieldpair_data().
tuple auparse_test.au = auparse.AuParser(auparse.AUSOURCE_BUFFER_ARRAY, buf)
Definition at line 152 of file auparse_test.py.
int auparse_test.auid = 4294967295
Definition at line 2 of file auparse_test.ref.py.
Referenced by list_create_session().
int auparse_test.beg = 0
Definition at line 236 of file auparse_test.py.
list auparse_test.buf
Initial value:
 = ["type=LOGIN msg=audit(1143146623.787:142): login pid=2027 uid=0 old auid=4294967295 new auid=848\ntype=SYSCALL msg=audit(1143146623.875:143): arch=c000003e syscall=188 success=yes exit=0 a0=7fffffa9a9f0 a1=3958d11333 a2=5131f0 a3=20 items=1 pid=2027 auid=848 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=tty3 comm=\"login\" exe=\"/bin/login\" subj=system_u:system_r:local_login_t:s0-s0:c0.c255\n",
 "type=USER_LOGIN msg=audit(1143146623.879:146): user pid=2027 uid=0 auid=848 msg=\'uid=848: exe=\"/bin/login\" (hostname=?, addr=?, terminal=tty3 res=success)\'\n",
 ]
Definition at line 6 of file auparse_test.py.
int auparse_test.chunk_len = 3
Definition at line 233 of file auparse_test.py.
Referenced by main().
string auparse_test.comm = "login"
Definition at line 46 of file auparse_test.ref.py.
string auparse_test.cwd = "/var/spool/postfix"
Definition at line 126 of file auparse_test.ref.py.
tuple auparse_test.data = s[beg:end]
Definition at line 239 of file auparse_test.py.
Referenced by ev_set_userdata(), list_insert_after(), print_tty_data(), push_event(), and q_peek().
int auparse_test.dev = hda7(hda7)
Definition at line 86 of file auparse_test.ref.py.
int auparse_test.egid = 0
Definition at line 42 of file auparse_test.ref.py.
tuple auparse_test.end = min(s_len, beg + chunk_len)
Definition at line 238 of file auparse_test.py.
Referenced by audit_name_to_msg_type(), E(), and q_peek().
int auparse_test.euid = 0
Definition at line 39 of file auparse_test.ref.py.
int auparse_test.event_cnt = 1
Definition at line 231 of file auparse_test.py.
string auparse_test.exe = "/bin/login"
Definition at line 47 of file auparse_test.ref.py.
int auparse_test.exit = 0
Definition at line 29 of file auparse_test.ref.py.
Referenced by check_params(), compound_search(), init_dispatcher(), light_test(), main(), output_record(), parse_args(), regex_search(), simple_search(), and usage().
tuple auparse_test.f = open(srcdir + "/test.log")
Definition at line 250 of file auparse_test.py.
Referenced by ecb_binary32_to_float(), ecb_float_to_binary32(), load_config(), load_pconfig(), main(), and plugin_load_config().
list auparse_test.files = [srcdir + "/test.log", srcdir + "/test2.log"]
Definition at line 9 of file auparse_test.py.
Referenced by main().
int auparse_test.fsgid = 0
Definition at line 44 of file auparse_test.ref.py.
int auparse_test.fsuid = 0
Definition at line 41 of file auparse_test.ref.py.
int auparse_test.gid = 0
Definition at line 38 of file auparse_test.ref.py.
Referenced by aulookup_gid().
tuple auparse_test.hostname = ?(?)
Definition at line 60 of file auparse_test.ref.py.
int auparse_test.ino = 14911367
Definition at line 87 of file auparse_test.ref.py.
int auparse_test.inode = 14911367
Definition at line 134 of file auparse_test.ref.py.
int auparse_test.item = 0
Definition at line 132 of file auparse_test.ref.py.
int auparse_test.items = 1
Definition at line 34 of file auparse_test.ref.py.
tuple auparse_test.key = (null)
Definition at line 120 of file auparse_test.ref.py.
Referenced by audit_machine_to_elf(), audit_number_to_errmsg(), and key_match().
int auparse_test.line = 1
Definition at line 13 of file auparse_test.ref.py.
string auparse_test.load_path = '../../bindings/python/build/lib.linux-i686-2.4'
Definition at line 13 of file auparse_test.py.
int auparse_test.mode = 040730
Definition at line 136 of file auparse_test.ref.py.
string auparse_test.name = "maildrop"
Definition at line 85 of file auparse_test.ref.py.
Referenced by add_start_guest_event(), add_stop_guest_event(), aulookup_gid(), aulookup_uid(), ausearch_add_timestamp_item_ex(), check_params(), main(), print_per_event_item(), process_machine_id_event(), process_resource_event(), and push_event().
tuple auparse_test.obj = system_u:object_r:postfix_spool_maildrop_t:s0(system_u:object_r:postfix_spool_maildrop_t:s0)
Definition at line 140 of file auparse_test.ref.py.
int auparse_test.ogid = 891
Definition at line 138 of file auparse_test.ref.py.
int auparse_test.ouid = 890
Definition at line 137 of file auparse_test.ref.py.
int auparse_test.pid = 2027
Definition at line 16 of file auparse_test.ref.py.
Referenced by audit_set_pid(), child_reap(), dispatcher_pid(), dispatcher_reaped(), init_dispatcher(), list_create_session(), main(), process_anom(), reconfigure_dispatcher(), sendmail(), and shutdown_dispatcher().
int auparse_test.ppid = 2013
Definition at line 105 of file auparse_test.ref.py.
int auparse_test.rdev = 00
Definition at line 139 of file auparse_test.ref.py.
tuple auparse_test.res = success(success)
Definition at line 63 of file auparse_test.ref.py.
Referenced by audit_name_to_action(), audit_name_to_field(), audit_name_to_flag(), audit_name_to_ftype(), audit_name_to_machine(), audit_name_to_syscall(), expr_create_binary(), expr_create_comparison(), expr_create_field_exists(), expr_create_regexp_expression(), expr_create_timestamp_comparison_ex(), expr_parse(), extract_virt_fields(), list_update_start(), process_resource_event(), and push_event().
tuple auparse_test.s_len = len(s)
Definition at line 235 of file auparse_test.py.
tuple auparse_test.scontext = system_u:system_r:postfix_pickup_t:s0(system_u:system_r:postfix_pickup_t:s0)
Definition at line 88 of file auparse_test.ref.py.
tuple auparse_test.seperms = read,write(read,write)
Definition at line 82 of file auparse_test.ref.py.
tuple auparse_test.seresult = denied(denied)
Definition at line 81 of file auparse_test.ref.py.
int auparse_test.sgid = 0
Definition at line 43 of file auparse_test.ref.py.
tuple auparse_test.srcdir = os.getenv('srcdir')
Definition at line 4 of file auparse_test.py.
tuple auparse_test.subj = system_u:system_r:local_login_t:s0-s0:c0.c255(system_u:system_r:local_login_t:s0-s0:c0.c255)
Definition at line 48 of file auparse_test.ref.py.
Referenced by main().
tuple auparse_test.success = yes(yes)
Definition at line 28 of file auparse_test.ref.py.
int auparse_test.suid = 0
Definition at line 40 of file auparse_test.ref.py.
int auparse_test.syscall = 188
Definition at line 27 of file auparse_test.ref.py.
tuple auparse_test.tclass = dir(dir)
Definition at line 90 of file auparse_test.ref.py.
tuple auparse_test.tcontext = system_u:object_r:postfix_spool_maildrop_t:s0(system_u:object_r:postfix_spool_maildrop_t:s0)
Definition at line 89 of file auparse_test.ref.py.
tuple auparse_test.terminal = tty3(tty3)
Definition at line 62 of file auparse_test.ref.py.
tuple auparse_test.tty = tty3(tty3)
Definition at line 45 of file auparse_test.ref.py.
tuple auparse_test.type = LOGIN(LOGIN)
Definition at line 15 of file auparse_test.ref.py.
Referenced by audit_add_watch_dir(), audit_send(), auparse_interp_adjust_type(), interpret(), main(), push_event(), and send_audit_event().
int auparse_test.uid = 0
Definition at line 17 of file auparse_test.ref.py.
Referenced by add_resource(), add_start_guest_event(), add_stop_guest_event(), audit_getloginuid(), aulookup_uid(), process_anom(), process_avc_selinux_context(), process_machine_id_event(), process_resource_event(), and process_shutdown().