audit: lib/netlink.c File Reference
netlink.c File Reference
#include "config.h"
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <time.h>
#include <sys/poll.h>
#include "libaudit.h"
#include "private.h"
Macros
#define NETLINK_AUDIT 9
Functions
int audit_open (void)
void audit_close (int fd)
int audit_get_reply (int fd, struct audit_reply *rep, reply_t block, int peek)
int audit_send (int fd, int type, const void *data, unsigned int size)
Macro Definition Documentation
#define NETLINK_AUDIT 9
Definition at line 35 of file netlink.c.
Referenced by audit_open().
Function Documentation
void audit_close (int fd)
Definition at line 78 of file netlink.c.
Referenced by audit_print_reply().
int audit_get_reply (int fd, struct audit_reply * rep, reply_t block, int peek)
Definition at line 89 of file netlink.c.
References audit_msg, GET_REPLY_NONBLOCKING, and audit_reply::msg.
Referenced by audit_is_enabled(), audit_set_pid(), and delete_all_rules().
int audit_open (void)
Definition at line 47 of file netlink.c.
References audit_msg, and NETLINK_AUDIT.
Referenced by main().
int audit_send (int fd, int type, const void * data, unsigned int size)
Definition at line 205 of file netlink.c.
References MAX_AUDIT_MESSAGE_LENGTH, audit_message::nlh, and auparse_test::type.
Referenced by audit_add_rule_data(), audit_delete_rule_data(), audit_make_equivalent(), audit_request_features(), audit_request_rules_list_data(), audit_request_signal_info(), audit_request_status(), audit_send_user_message(), audit_set_backlog_limit(), audit_set_backlog_wait_time(), audit_set_enabled(), audit_set_failure(), audit_set_feature(), audit_set_pid(), audit_set_rate_limit(), audit_trim_subtrees(), and delete_all_rules().