audit: auparse/nvlist.h File Reference
nvlist.h File Reference
#include "config.h"
#include "private.h"
#include <sys/types.h>
#include "rnode.h"
#include "ellist.h"
Functions
void nvlist_create (nvlist *l) hidden
void nvlist_clear (nvlist *l) hidden
nvnode * nvlist_next (nvlist *l) hidden
int nvlist_get_cur_type (const rnode *r) hidden
const char * nvlist_interp_cur_val (const rnode *r) hidden
void nvlist_append (nvlist *l, nvnode *node) hidden
int nvlist_find_name (nvlist *l, const char *name) hidden
Function Documentation
void nvlist_append (nvlist * l, nvnode * node)
Definition at line 59 of file nvlist.c.
void nvlist_clear (nvlist * l)
Definition at line 120 of file nvlist.c.
void nvlist_create (nvlist * l)
Definition at line 32 of file nvlist.c.
int nvlist_find_name (nvlist * l, const char * name)
Definition at line 90 of file nvlist.c.
References nvlist::cur, _nvnode::name, and _nvnode::next.
Referenced by auparse_find_field_next(), and expr_eval().
int nvlist_get_cur_type (const rnode * r)
Definition at line 106 of file nvlist.c.
References auparse_interp_adjust_type(), nvlist::cur, _nvnode::name, _rnode::nv, _rnode::type, and _nvnode::val.
Referenced by auparse_get_field_type().
const char* nvlist_interp_cur_val (const rnode * r)
Definition at line 112 of file nvlist.c.
References nvlist::cur, _nvnode::interp_val, interpret, and _rnode::nv.
Referenced by auparse_interpret_field().
nvnode* nvlist_next (nvlist * l)
Definition at line 52 of file nvlist.c.