audit: audisp/plugins/remote/queue.h File Reference
queue.h File Reference
#include <sys/types.h>
Enumerations
enum {
Q_IN_MEMORY = 1 << 0, Q_IN_FILE = 1 << 1, Q_CREAT = 1 << 2, Q_EXCL = 1 << 3,
Q_SYNC = 1 << 4, Q_RESIZE = 1 << 5
}
Functions
struct queue * q_open (int q_flags, const char *path, size_t num_entries, size_t entry_size)
void q_close (struct queue *q)
int q_append (struct queue *q, const char *data)
int q_peek (struct queue *q, char *buf, size_t size)
int q_drop_head (struct queue *q)
size_t q_queue_length (const struct queue *q)
Enumeration Type Documentation
anonymous enum
Enumerator
Q_IN_MEMORY
Q_IN_FILE
Q_CREAT
Q_EXCL
Q_SYNC
Q_RESIZE
Definition at line 31 of file queue.h.
Function Documentation
int q_append (struct queue * q, const char * data)
Definition at line 382 of file queue.c.
Referenced by main().
void q_close (struct queue * q)
Definition at line 315 of file queue.c.
References queue::fd, queue::memory, and queue::num_entries.
Referenced by main(), and q_open().
int q_drop_head (struct queue * q)
Definition at line 461 of file queue.c.
struct queue* q_open (int q_flags, const char * path, size_t num_entries, size_t entry_size)
Definition at line 477 of file queue.c.
References queue::fd, queue::flags, queue::num_entries, q_close(), Q_CREAT, Q_EXCL, q_peek(), Q_RESIZE, and queue::queue_length.
int q_peek (struct queue * q, char * buf, size_t size)
Definition at line 393 of file queue.c.
References queue::buffer, auparse_test::data, auparse_test::end, queue::entry_size, queue::fd, queue::memory, queue::queue_head, and queue::queue_length.
Referenced by q_open().
size_t q_queue_length (const struct queue * q)
Definition at line 472 of file queue.c.
References queue::queue_length.
Referenced by main().