audit: audisp/plugins/remote/queue.c File Reference
queue.c File Reference
#include "config.h"
#include <stdio.h>
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "queue.h"
Data Structures
struct queue
struct fh_state
struct file_header
Macros
#define verify(E)
#define FH_VERSION_0 0x00
Functions
void q_close (struct queue *q)
int q_append (struct queue *q, const char *data)
int q_peek (struct queue *q, char *buf, size_t size)
int q_drop_head (struct queue *q)
size_t q_queue_length (const struct queue *q)
struct queue * q_open (int q_flags, const char *path, size_t num_entries, size_t entry_size)
Macro Definition Documentation
#define FH_VERSION_0 0x00
Definition at line 134 of file queue.c.
#define verify (E)
Value:
do {                \
        char verify__[(E) ? 1 : -1];    \
        (void)verify__;         \
    } while (0)
Definition at line 55 of file queue.c.
Function Documentation
int q_append (struct queue * q, const char * data)
Definition at line 382 of file queue.c.
Referenced by main().
void q_close (struct queue * q)
Definition at line 315 of file queue.c.
References queue::fd, queue::memory, and queue::num_entries.
Referenced by main(), and q_open().
int q_drop_head (struct queue * q)
Definition at line 461 of file queue.c.
struct queue* q_open (int q_flags, const char * path, size_t num_entries, size_t entry_size)
Definition at line 477 of file queue.c.
References queue::fd, queue::flags, queue::num_entries, q_close(), Q_CREAT, Q_EXCL, q_peek(), Q_RESIZE, and queue::queue_length.
int q_peek (struct queue * q, char * buf, size_t size)
Definition at line 393 of file queue.c.
References queue::buffer, auparse_test::data, auparse_test::end, queue::entry_size, queue::fd, queue::memory, queue::queue_head, and queue::queue_length.
Referenced by q_open().
size_t q_queue_length (const struct queue * q)
Definition at line 472 of file queue.c.
References queue::queue_length.
Referenced by main().