audit: audisp/plugins/prelude/prelude-config.h File Reference
prelude-config.h File Reference
#include "audisp-int.h"
Data Structures
struct prelude_conf
Typedefs
typedef struct prelude_conf prelude_conf_t
Enumerations
enum enable_t { E_NO, E_YES }
enum action_t {
A_IGNORE, A_IDMEF =1, A_KILL =2, A_SESSION =4,
A_SINGLE =8, A_HALT =16
}
Functions
void clear_config (prelude_conf_t *config)
int load_config (prelude_conf_t *config, const char *file)
void free_config (prelude_conf_t *config)
Typedef Documentation
typedef struct prelude_conf prelude_conf_t
Enumeration Type Documentation
enum action_t
Enumerator
A_IGNORE
A_IDMEF
A_KILL
A_SESSION
A_SINGLE
A_HALT
Definition at line 30 of file prelude-config.h.
enum enable_t
Enumerator
E_NO
E_YES
Definition at line 29 of file prelude-config.h.
Function Documentation
void clear_config (prelude_conf_t * config)
Definition at line 191 of file prelude-config.c.
References A_IDMEF, prelude_conf::abends, prelude_conf::abends_act, prelude_conf::avcs, prelude_conf::avcs_act, E_NO, E_YES, prelude_conf::group_auth, prelude_conf::group_auth_act, ilist_create(), prelude_conf::login_failure_max, prelude_conf::login_failure_max_act, prelude_conf::login_location, prelude_conf::login_location_act, prelude_conf::login_session_max, prelude_conf::login_session_max_act, prelude_conf::login_time, prelude_conf::login_time_act, prelude_conf::logins, prelude_conf::logins_act, prelude_conf::mac_status, prelude_conf::mac_status_act, prelude_conf::profile, prelude_conf::promiscuous, prelude_conf::promiscuous_act, prelude_conf::tty, prelude_conf::tty_act, prelude_conf::watched_accounts, prelude_conf::watched_acct, prelude_conf::watched_acct_act, prelude_conf::watched_exec, prelude_conf::watched_exec_act, prelude_conf::watched_file, prelude_conf::watched_file_act, prelude_conf::watched_mk_exe, prelude_conf::watched_mk_exe_act, prelude_conf::watched_syscall, and prelude_conf::watched_syscall_act.
void free_config (prelude_conf_t * config)
Definition at line 839 of file prelude-config.c.
References ilist_clear(), prelude_conf::profile, and prelude_conf::watched_accounts.
int load_config (prelude_conf_t * config, const char * file)
Definition at line 229 of file prelude-config.c.
References clear_config(), auparse_test::f, free_config(), kw_pair::max_options, nv_pair::name, kw_pair::name, nv_pair::option, kw_pair::parser, and nv_pair::value.