audit: audisp/queue.h File Reference
queue.h File Reference
#include "libaudit.h"
#include "audispd-config.h"
Data Structures
struct event
Typedefs
typedef struct event event_t
Functions
void reset_suspended (void)
int init_queue (unsigned int size)
void enqueue (event_t *e, struct daemon_conf *config)
event_t * dequeue (void)
void nudge_queue (void)
void increase_queue_depth (unsigned int size)
void destroy_queue (void)
Typedef Documentation
typedef struct event event_t
Function Documentation
event_t* dequeue (void)
Definition at line 86 of file zos-remote-queue.c.
References hup.
void destroy_queue (void)
Definition at line 134 of file zos-remote-queue.c.
Referenced by main().
void enqueue (event_t * e, struct daemon_conf * config)
Definition at line 129 of file queue.c.
void increase_queue_depth (unsigned int size)
Definition at line 118 of file zos-remote-queue.c.
Referenced by main().
int init_queue (unsigned int size)
Definition at line 38 of file zos-remote-queue.c.
References init_queue().
Referenced by init_queue(), and main().
void nudge_queue (void)
Definition at line 113 of file zos-remote-queue.c.
void reset_suspended (void)
Definition at line 40 of file queue.c.