audit: audisp/plugins/remote/remote-fgets.c File Reference
remote-fgets.c File Reference
#include "config.h"
#include <assert.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include "remote-fgets.h"
Macros
#define BUF_SIZE 8192
Functions
int remote_fgets_eof (void)
int remote_fgets_more (size_t blen)
int remote_fgets (char *buf, size_t blen, int fd)
Macro Definition Documentation
#define BUF_SIZE 8192
Definition at line 30 of file remote-fgets.c.
Function Documentation
int remote_fgets (char * buf, size_t blen, int fd)
Definition at line 54 of file remote-fgets.c.
Referenced by main().
int remote_fgets_eof (void)
Definition at line 36 of file remote-fgets.c.
Referenced by main().
int remote_fgets_more (size_t blen)
Definition at line 45 of file remote-fgets.c.
Referenced by main().