audit: src/test/slist_test.c File Reference
slist_test.c File Reference
#include <stdio.h>
#include <string.h>
#include "ausearch-string.h"
Functions
int print_list (void)
int main (void)
Variables
slist s
Function Documentation
int main (void)
Definition at line 21 of file slist_test.c.
References slist::cnt, _snode::hits, _snode::key, print_list(), slist_add_if_uniq(), slist_append(), slist_clear(), slist_create(), slist_next(), slist_sort_by_hits(), and _snode::str.
int print_list (void)
Definition at line 7 of file slist_test.c.
References slist_next(), and _snode::str.
Referenced by auparse_do_interpretation(), and main().
Variable Documentation
slist s
Definition at line 5 of file slist_test.c.
Referenced by audit_strsplit(), audit_strsplit_r(), and get_username().