audit: src/auditd-config.c File Reference
auditd-config.c File Reference
#include "config.h"
#include <stdio.h>
#include <unistd.h>
#include <sys/stat.h>
#include <errno.h>
#include <string.h>
#include <dirent.h>
#include <ctype.h>
#include <stdlib.h>
#include <netdb.h>
#include <fcntl.h>
#include <libgen.h>
#include <arpa/inet.h>
#include <limits.h>
#include "auditd-config.h"
#include "libaudit.h"
#include "private.h"
Data Structures
struct nv_pair
struct kw_pair
struct nv_list
Macros
#define TCP_PORT_MAX 65535
Functions
void set_allow_links (int allow)
void clear_config (struct daemon_conf *config)
int load_config (struct daemon_conf *config, log_test_t lt)
const char * audit_lookup_format (int fmt)
int create_log_file (const char *val)
void free_config (struct daemon_conf *config)
int resolve_node (struct daemon_conf *config)
Variables
const char * email_command = "/usr/lib/sendmail"
Macro Definition Documentation
#define TCP_PORT_MAX 65535
Definition at line 42 of file auditd-config.c.
Referenced by clear_config().
Function Documentation
const char* audit_lookup_format (int fmt)
Definition at line 1616 of file auditd-config.c.
References nv_list::name.
Referenced by main().
void clear_config (struct daemon_conf * config)
Definition at line 239 of file auditd-config.c.
References daemon_conf::action_mail_acct, daemon_conf::admin_space_left, daemon_conf::admin_space_left_action, daemon_conf::admin_space_left_exe, daemon_conf::disk_error_action, daemon_conf::disk_error_exe, daemon_conf::disk_full_action, daemon_conf::disk_full_exe, daemon_conf::dispatcher, daemon_conf::enable_krb5, FA_IGNORE, FA_SYSLOG, daemon_conf::flush, daemon_conf::freq, FT_NONE, daemon_conf::krb5_key_file, daemon_conf::krb5_principal, LF_RAW, daemon_conf::log_file, daemon_conf::log_format, daemon_conf::log_group, daemon_conf::max_log_size, daemon_conf::max_log_size_action, daemon_conf::max_restarts, N_NONE, daemon_conf::name, daemon_conf::node_name, daemon_conf::node_name_format, daemon_conf::num_logs, O_SYSLOG, daemon_conf::overflow_action, daemon_conf::priority_boost, daemon_conf::q_depth, daemon_conf::qos, QOS_NON_BLOCKING, daemon_conf::sender_ctx, daemon_conf::sender_pid, daemon_conf::sender_uid, daemon_conf::space_left, daemon_conf::space_left_action, daemon_conf::space_left_exe, SZ_IGNORE, daemon_conf::tcp_client_max_idle, daemon_conf::tcp_client_max_port, daemon_conf::tcp_client_min_port, daemon_conf::tcp_listen_port, daemon_conf::tcp_listen_queue, daemon_conf::tcp_max_per_addr, TCP_PORT_MAX, and daemon_conf::use_libwrap.
int create_log_file (const char * val)
Definition at line 1627 of file auditd-config.c.
References audit_msg.
void free_config (struct daemon_conf * config)
Definition at line 1639 of file auditd-config.c.
References daemon_conf::action_mail_acct, daemon_conf::admin_space_left_exe, daemon_conf::disk_error_exe, daemon_conf::disk_full_exe, daemon_conf::dispatcher, daemon_conf::krb5_key_file, daemon_conf::krb5_principal, daemon_conf::log_file, daemon_conf::name, daemon_conf::node_name, daemon_conf::sender_ctx, and daemon_conf::space_left_exe.
int load_config (struct daemon_conf * config, log_test_t lt)
Definition at line 281 of file auditd-config.c.
References audit_msg, clear_config(), CONFIG_FILE, auparse_test::f, kw_pair::max_options, _pair::name, nv_pair::name, kw_pair::name, nv_pair::option, kw_pair::parser, _pair::value, and nv_pair::value.
int resolve_node (struct daemon_conf * config)
Definition at line 1654 of file auditd-config.c.
References audit_msg, N_FQD, N_HOSTNAME, N_NONE, N_NUMERIC, N_USER, daemon_conf::node_name, and daemon_conf::node_name_format.
Referenced by main().
void set_allow_links (int allow)
Definition at line 231 of file auditd-config.c.
Referenced by main().
Variable Documentation
const char* email_command = "/usr/lib/sendmail"
Definition at line 227 of file auditd-config.c.
Referenced by sendmail().