audit: audisp/plugins/zos-remote/zos-remote-config.c File Reference
zos-remote-config.c File Reference
#include "zos-remote-config.h"
#include <string.h>
#include <stdio.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <errno.h>
#include <ctype.h>
#include <unistd.h>
#include <stdlib.h>
#include "zos-remote-log.h"
Data Structures
struct nv_pair
struct kw_pair
struct nv_list
Macros
#define UNUSED(x) (void)(x)
Functions
void plugin_clear_config (plugin_conf_t *c)
int plugin_load_config (plugin_conf_t *c, const char *file)
void plugin_free_config (plugin_conf_t *c)
Macro Definition Documentation
#define UNUSED (x) (void)(x)
Definition at line 79 of file zos-remote-config.c.
Function Documentation
void plugin_clear_config (plugin_conf_t * c)
Definition at line 84 of file zos-remote-config.c.
References plugin_conf::password, plugin_conf::port, plugin_conf::q_depth, plugin_conf::server, plugin_conf::timeout, and plugin_conf::user.
Referenced by main(), and plugin_load_config().
void plugin_free_config (plugin_conf_t * c)
Definition at line 433 of file zos-remote-config.c.
References plugin_conf::name, plugin_conf::password, plugin_conf::server, and plugin_conf::user.
Referenced by main().
int plugin_load_config (plugin_conf_t * c, const char * file)
Definition at line 95 of file zos-remote-config.c.
References auparse_test::f, log_err(), log_warn(), kw_pair::max_options, nv_pair::name, kw_pair::name, plugin_conf::name, nv_pair::option, kw_pair::parser, plugin_clear_config(), and nv_pair::value.
Referenced by main().