audit: audisp/plugins/zos-remote/zos-remote-plugin.c File Reference
zos-remote-plugin.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <signal.h>
#include <limits.h>
#include <string.h>
#include <time.h>
#include <errno.h>
#include <pthread.h>
#include <lber.h>
#include <netinet/in.h>
#include "auparse.h"
#include "zos-remote-log.h"
#include "zos-remote-ldap.h"
#include "zos-remote-config.h"
#include "zos-remote-queue.h"
Macros
#define UNUSED(x) (void)(x)
Functions
void push_event (auparse_state_t *au, auparse_cb_event_t cb_event_type, void *user_data)
int main (int argc, char *argv[])
Variables
volatile int stop = 0
volatile int hup = 0
volatile ZOS_REMOTE zos_remote_inst
pid_t mypid = 0
Macro Definition Documentation
#define UNUSED (x) (void)(x)
Definition at line 50 of file zos-remote-plugin.c.
Referenced by push_event().
Function Documentation
int main (int argc, char * argv[])
Definition at line 412 of file zos-remote-plugin.c.
References auparse_add_callback(), auparse_destroy(), auparse_feed(), auparse_flush_feed(), auparse_init(), AUSOURCE_FEED, plugin_conf::counter, destroy_queue(), hup, increase_queue_depth(), init_queue(), log_debug, log_err(), log_info(), log_warn(), mypid, plugin_clear_config(), plugin_free_config(), plugin_load_config(), push_event(), plugin_conf::q_depth, and stop.
void push_event (auparse_state_t * au, auparse_cb_event_t cb_event_type, void * user_data)
Definition at line 152 of file zos-remote-plugin.c.
References ASN1_IA5STRING_TAG, AUPARSE_CB_EVENT_READY, auparse_find_field(), auparse_first_field(), auparse_first_record(), auparse_get_field_name(), auparse_get_node(), auparse_get_record_text(), auparse_get_timestamp(), auparse_interpret_field(), auparse_next_field(), auparse_next_record(), plugin_conf::counter, auparse_test::data, enqueue(), ICTX_REQUESTVER, log_debug, log_err(), log_warn(), auparse_test::name, auparse_test::res, au_event_t::sec, au_event_t::serial, stop, auparse_test::type, UNUSED, ZOS_REMOTE_EVENT_AUTHORIZATION, ZOS_REMOTE_LINK_VALUE_SIZE, ZOS_REMOTE_LOGSTRING_SIZE, ZOS_REMOTE_QUALIF_FAIL, ZOS_REMOTE_QUALIF_INFO, ZOS_REMOTE_QUALIF_SUCCESS, ZOS_REMOTE_RELOC_OTHER, and ZOS_REMOTE_RELOC_TIMESTAMP.
Referenced by main().
Variable Documentation
volatile int hup = 0
Definition at line 56 of file zos-remote-plugin.c.
pid_t mypid = 0
Definition at line 61 of file zos-remote-plugin.c.
Referenced by main().
volatile int stop = 0
Definition at line 55 of file zos-remote-plugin.c.
volatile ZOS_REMOTE zos_remote_inst
Definition at line 57 of file zos-remote-plugin.c.