audit: audisp/plugins/zos-remote/zos-remote-log.h File Reference
zos-remote-log.h File Reference
#include "zos-remote-ldap.h"
#include <syslog.h>
#include <sys/types.h>
#include <unistd.h>
#include <lber.h>
Macros
#define log_debug(fmt,...)
#define debug_bv(bv)
#define debug_ber(ber)
Functions
void log_err (const char *,...)
void log_warn (const char *,...)
void log_info (const char *,...)
void _log_debug (const char *,...)
void _debug_bv (struct berval *)
void _debug_ber (BerElement *)
Variables
pid_t mypid
Macro Definition Documentation
#define debug_ber (ber)
Definition at line 53 of file zos-remote-log.h.
#define debug_bv (bv)
Definition at line 52 of file zos-remote-log.h.
Referenced by _debug_ber().
#define log_debug (fmt, ...)
Definition at line 51 of file zos-remote-log.h.
Referenced by _debug_bv(), main(), push_event(), and submit_request_s().
Function Documentation
void _debug_ber (BerElement *)
Definition at line 77 of file zos-remote-log.c.
References debug_bv.
void _debug_bv (struct berval *)
Definition at line 86 of file zos-remote-log.c.
References log_debug.
void _log_debug (const char * , ...)
Definition at line 68 of file zos-remote-log.c.
void log_err (const char * , ...)
Definition at line 41 of file zos-remote-log.c.
Referenced by enqueue(), main(), plugin_load_config(), push_event(), submit_request_s(), and zos_remote_init().
void log_info (const char * , ...)
Definition at line 59 of file zos-remote-log.c.
Referenced by main().
void log_warn (const char * , ...)
Definition at line 50 of file zos-remote-log.c.
Referenced by main(), plugin_load_config(), and push_event().
Variable Documentation
pid_t mypid
Definition at line 61 of file zos-remote-plugin.c.
Referenced by main().