suricata: src/alert-syslog.c File Reference
alert-syslog.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "flow.h"
#include "conf.h"
#include "threads.h"
#include "tm-threads.h"
#include "threadvars.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-reference.h"
#include "output.h"
#include "alert-syslog.h"
#include "util-classification-config.h"
#include "util-debug.h"
#include "util-print.h"
#include "util-proto-name.h"
#include "util-syslog.h"
#include "util-optimize.h"
#include "util-logopenfile.h"
Data Structures
struct AlertSyslogThread_
Macros
#define DEFAULT_ALERT_SYSLOG_FACILITY_STR "local0"
#define DEFAULT_ALERT_SYSLOG_FACILITY LOG_LOCAL0
#define DEFAULT_ALERT_SYSLOG_LEVEL LOG_ERR
#define MODULE_NAME "AlertSyslog"
Typedefs
typedef struct AlertSyslogThread_ AlertSyslogThread
Functions
OutputCtx * AlertSyslogInitCtx (ConfNode *conf)
Create a new LogFileCtx for "syslog" output style.
void TmModuleAlertSyslogRegister (void)
Function to register the AlertSyslog module.
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Logs alerts in a line based text format in to syslog.
Definition in file alert-syslog.c.
Macro Definition Documentation
#define DEFAULT_ALERT_SYSLOG_FACILITY LOG_LOCAL0
Definition at line 56 of file alert-syslog.c.
Referenced by AlertSyslogInitCtx().
#define DEFAULT_ALERT_SYSLOG_FACILITY_STR "local0"
Definition at line 55 of file alert-syslog.c.
Referenced by AlertSyslogInitCtx().
#define DEFAULT_ALERT_SYSLOG_LEVEL LOG_ERR
Definition at line 57 of file alert-syslog.c.
#define MODULE_NAME "AlertSyslog"
Definition at line 58 of file alert-syslog.c.
Referenced by TmModuleAlertSyslogRegister().
Typedef Documentation
typedef struct AlertSyslogThread_ AlertSyslogThread
Function Documentation
OutputCtx* AlertSyslogInitCtx (ConfNode * conf)
Create a new LogFileCtx for "syslog" output style.
Parameters
conf The configuration node for this output.
Returns
A OutputCtx pointer on success, NULL on failure.
Definition at line 91 of file alert-syslog.c.
References ConfNodeLookupChildValue(), OutputCtx_::data, DEFAULT_ALERT_SYSLOG_FACILITY, DEFAULT_ALERT_SYSLOG_FACILITY_STR, OutputCtx_::DeInit, LogFileNewCtx(), openlog, SC_ERR_INVALID_ARGUMENT, SCLogDebug, SCLogInfo, SCLogWarning, SCMalloc, SCMapEnumNameToValue(), SCSyslogGetFacilityMap(), SCSyslogGetLogLevelMap(), and unlikely.
Referenced by TmModuleAlertSyslogRegister().
void TmModuleAlertSyslogRegister (void)
Function to register the AlertSyslog module.
Definition at line 411 of file alert-syslog.c.
References AlertSyslogInitCtx(), TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, MODULE_NAME, TmModule_::name, OutputRegisterPacketModule(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_ALERTSYSLOG, and tmm_modules.
Referenced by RegisterAllModules().