suricata: src/alert-syslog.h File Reference
alert-syslog.h File Reference
Functions
void TmModuleAlertSyslogRegister (void)
Function to register the AlertSyslog module.
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
alert syslog modeule header file
Definition in file alert-syslog.h.
Function Documentation
void TmModuleAlertSyslogRegister (void)
Function to register the AlertSyslog module.
Definition at line 411 of file alert-syslog.c.
References AlertSyslogInitCtx(), TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, MODULE_NAME, TmModule_::name, OutputRegisterPacketModule(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_ALERTSYSLOG, and tmm_modules.
Referenced by RegisterAllModules().