suricata: src/alert-fastlog.h File Reference
alert-fastlog.h File Reference
Functions
void TmModuleAlertFastLogRegister (void)
void TmModuleAlertFastLogIPv4Register (void)
void TmModuleAlertFastLogIPv6Register (void)
OutputCtx * AlertFastLogInitCtx (ConfNode *)
Create a new LogFileCtx for "fast" output style.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file alert-fastlog.h.
Function Documentation
OutputCtx* AlertFastLogInitCtx (ConfNode * conf)
Create a new LogFileCtx for "fast" output style.
Parameters
conf The configuration node for this output.
Returns
A LogFileCtx pointer on success, NULL on failure.
Definition at line 245 of file alert-fastlog.c.
References OutputCtx_::data, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, LogFileFreeCtx(), LogFileNewCtx(), SCCalloc, SCConfLogOpenGeneric(), SCLogDebug, and unlikely.
Referenced by TmModuleAlertFastLogRegister().
void TmModuleAlertFastLogIPv4Register (void)
void TmModuleAlertFastLogIPv6Register (void)
void TmModuleAlertFastLogRegister (void)
Definition at line 80 of file alert-fastlog.c.
References AlertFastLogCondition(), AlertFastLogExitPrintStats(), AlertFastLogger(), AlertFastLogInitCtx(), AlertFastLogRegisterTests(), AlertFastLogThreadDeinit(), AlertFastLogThreadInit(), TmModule_::cap_flags, TmModule_::flags, MODULE_NAME, TmModule_::name, OutputRegisterPacketModule(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_ALERTFASTLOG, and tmm_modules.
Referenced by RegisterAllModules().