suricata: src/alert-fastlog.c File Reference
alert-fastlog.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "detect.h"
#include "flow.h"
#include "conf.h"
#include "threads.h"
#include "tm-threads.h"
#include "threadvars.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-reference.h"
#include "util-classification-config.h"
#include "output.h"
#include "alert-fastlog.h"
#include "util-privs.h"
#include "util-print.h"
#include "util-proto-name.h"
#include "util-optimize.h"
#include "util-logopenfile.h"
#include "util-time.h"
Data Structures
struct AlertFastLogThread_
Macros
#define DEFAULT_LOG_FILENAME "fast.log"
#define MODULE_NAME "AlertFastLog"
#define MAX_FASTLOG_ALERT_SIZE 2048
#define MAX_FASTLOG_BUFFER_SIZE (2 * MAX_FASTLOG_ALERT_SIZE)
Typedefs
typedef struct AlertFastLogThread_ AlertFastLogThread
Functions
TmEcode AlertFastLogThreadInit (ThreadVars *, void *, void **)
TmEcode AlertFastLogThreadDeinit (ThreadVars *, void *)
void AlertFastLogExitPrintStats (ThreadVars *, void *)
void AlertFastLogRegisterTests (void)
This function registers unit tests for AlertFastLog API.
int AlertFastLogCondition (ThreadVars *tv, const Packet *p)
int AlertFastLogger (ThreadVars *tv, void *data, const Packet *p)
void TmModuleAlertFastLogRegister (void)
OutputCtx * AlertFastLogInitCtx (ConfNode *conf)
Create a new LogFileCtx for "fast" output style.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Logs alerts in a line based text format compatible to Snort's alert_fast format.
Todo:
Support classifications
Support more than just IPv4/IPv6 TCP/UDP.
Definition in file alert-fastlog.c.
Macro Definition Documentation
#define DEFAULT_LOG_FILENAME "fast.log"
Definition at line 61 of file alert-fastlog.c.
Referenced by AlertFastLogInitCtx().
#define MAX_FASTLOG_ALERT_SIZE 2048
Definition at line 66 of file alert-fastlog.c.
Referenced by AlertFastLogger().
#define MAX_FASTLOG_BUFFER_SIZE (2 * MAX_FASTLOG_ALERT_SIZE)
Definition at line 69 of file alert-fastlog.c.
Referenced by AlertFastLogger().
#define MODULE_NAME "AlertFastLog"
Definition at line 63 of file alert-fastlog.c.
Referenced by TmModuleAlertFastLogRegister().
Typedef Documentation
typedef struct AlertFastLogThread_ AlertFastLogThread
Function Documentation
int AlertFastLogCondition (ThreadVars * tv, const Packet * p)
Definition at line 99 of file alert-fastlog.c.
References Packet_::alerts, PacketAlerts_::cnt, FALSE, and TRUE.
Referenced by TmModuleAlertFastLogRegister().
void AlertFastLogExitPrintStats (ThreadVars * tv, void * data)
Definition at line 230 of file alert-fastlog.c.
References LogFileCtx_::alerts, AlertFastLogThread_::file_ctx, and SCLogInfo.
Referenced by TmModuleAlertFastLogRegister().
int AlertFastLogger (ThreadVars * tv, void * data, const Packet * p)
Definition at line 115 of file alert-fastlog.c.
References PacketAlert_::action, ACTION_DROP, PacketAlerts_::alerts, Packet_::alerts, Signature_::class_msg, PacketAlerts_::cnt, CreateTimeString(), Packet_::dp, EngineModeIsIPS(), GET_IPV4_DST_ADDR_PTR, GET_IPV4_SRC_ADDR_PTR, GET_IPV6_DST_ADDR, GET_IPV6_SRC_ADDR, GET_PKT_DATA, GET_PKT_LEN, Signature_::gid, Signature_::id, IP_GET_IPPROTO, known_proto, likely, MAX_FASTLOG_ALERT_SIZE, MAX_FASTLOG_BUFFER_SIZE, Signature_::msg, Packet_::pcap_cnt, PKT_IS_IPV4, PKT_IS_IPV6, PrintBufferData, PrintBufferRawLineHex(), PrintInet(), Signature_::prio, proto, Signature_::rev, PacketAlert_::s, SCProtoNameValid(), Packet_::sp, strlcpy(), TM_ECODE_OK, TRUE, Packet_::ts, and unlikely.
Referenced by TmModuleAlertFastLogRegister().
OutputCtx* AlertFastLogInitCtx (ConfNode * conf)
Create a new LogFileCtx for "fast" output style.
Parameters
conf The configuration node for this output.
Returns
A LogFileCtx pointer on success, NULL on failure.
Definition at line 245 of file alert-fastlog.c.
References OutputCtx_::data, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, LogFileFreeCtx(), LogFileNewCtx(), SCCalloc, SCConfLogOpenGeneric(), SCLogDebug, and unlikely.
Referenced by TmModuleAlertFastLogRegister().
void AlertFastLogRegisterTests (void)
This function registers unit tests for AlertFastLog API.
Definition at line 376 of file alert-fastlog.c.
Referenced by TmModuleAlertFastLogRegister().
TmEcode AlertFastLogThreadDeinit (ThreadVars * t, void * data)
Definition at line 216 of file alert-fastlog.c.
References SCFree, and TM_ECODE_OK.
Referenced by TmModuleAlertFastLogRegister().
TmEcode AlertFastLogThreadInit (ThreadVars * t, void * initdata, void ** data)
Use the Ouptut Context (file pointer and mutex)
Definition at line 197 of file alert-fastlog.c.
References AlertFastLogThread_::file_ctx, SCFree, SCLogDebug, SCMalloc, TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by TmModuleAlertFastLogRegister().
void TmModuleAlertFastLogRegister (void)
Definition at line 80 of file alert-fastlog.c.
References AlertFastLogCondition(), AlertFastLogExitPrintStats(), AlertFastLogger(), AlertFastLogInitCtx(), AlertFastLogRegisterTests(), AlertFastLogThreadDeinit(), AlertFastLogThreadInit(), TmModule_::cap_flags, TmModule_::flags, MODULE_NAME, TmModule_::name, OutputRegisterPacketModule(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_ALERTFASTLOG, and tmm_modules.
Referenced by RegisterAllModules().