suricata: src/alert-unified2-alert.c File Reference
alert-unified2-alert.c File Reference
#include "suricata-common.h"
#include "runmodes.h"
#include "debug.h"
#include "detect.h"
#include "flow.h"
#include "conf.h"
#include "pkt-var.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "alert-unified2-alert.h"
#include "decode-ipv4.h"
#include "host.h"
#include "util-profiling.h"
#include "decode.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-byte.h"
#include "util-misc.h"
#include "util-logopenfile.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "app-layer.h"
#include "app-layer-htp-xff.h"
#include "output.h"
#include "util-privs.h"
#include "stream.h"
#include "stream-tcp-inline.h"
#include "util-optimize.h"
Data Structures
struct Unified2ExtraDataHdr_
struct Unified2AlertFileHeader_
struct AlertIPv4Unified2_
struct AlertIPv6Unified2_
struct AlertUnified2Packet_
struct Unified2AlertFileCtx_
struct Unified2AlertThread_
struct _FakeIPv4Hdr
struct _FakeIPv6Hdr
Macros
#define DEFAULT_LOG_FILENAME "unified2.alert"
#define DEFAULT_LIMIT 32 * 1024 * 1024
#define MIN_LIMIT 1 * 1024 * 1024
#define UNIFIED2_ALERT_XFF_IPV4 8
#define UNIFIED2_ALERT_XFF_IPV6 16
#define UNIFIED2_ALERT_FLAGS_EMIT_PACKET (1 << 0)
#define UNIFIED2_PACKET_SIZE (sizeof(Unified2Packet) - 4)
#define MODULE_NAME "Unified2Alert"
Typedefs
typedef struct
Unified2AlertFileHeader_ Unified2AlertFileHeader
typedef struct AlertIPv4Unified2_ AlertIPv4Unified2
typedef struct AlertIPv6Unified2_ AlertIPv6Unified2
typedef struct AlertUnified2Packet_ Unified2Packet
typedef struct
Unified2AlertFileCtx_ Unified2AlertFileCtx
typedef struct Unified2AlertThread_ Unified2AlertThread
Functions
struct Unified2ExtraDataHdr_ __attribute__ ((__packed__))
DNS packet header.
SC_ATOMIC_DECLARE (unsigned int, unified2_event_id)
TmEcode Unified2AlertThreadInit (ThreadVars *t, void *initdata, void **data)
Thread init function.
TmEcode Unified2AlertThreadDeinit (ThreadVars *t, void *data)
Thread deinit function.
void Unified2RegisterTests (void)
this function registers unit tests for Unified2
int Unified2AlertOpenFileCtx (LogFileCtx *file_ctx, const char *prefix)
Read the config set the file pointer, open the file.
int Unified2Condition (ThreadVars *tv, const Packet *p)
int Unified2Logger (ThreadVars *t, void *data, const Packet *p)
Unified2 main entry function.
void TmModuleUnified2AlertRegister (void)
int Unified2AlertCloseFile (ThreadVars *t, Unified2AlertThread *aun)
Function to close unified2 file.
int Unified2AlertRotateFile (ThreadVars *t, Unified2AlertThread *aun)
Function to rotate unified2 file.
OutputCtx * Unified2AlertInitCtx (ConfNode *conf)
Create a new LogFileCtx from the provided ConfNode.
Variables
uint32_t event_type
uint32_t event_length
Unified2ExtraData
IPV4Hdr ip4h
TCPHdr tcph
IPV6Hdr ip6h
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Ignacio Sanchez sanch.nosp@m.ezma.nosp@m.rtin..nosp@m.ji@g.nosp@m.mail..nosp@m.com
Duarte Silva duart.nosp@m.e.si.nosp@m.lva@s.nosp@m.eria.nosp@m.lizin.nosp@m.g.me
Logs alerts in a format compatible to Snort's unified2 format, so it should be readable by Barnyard2.
Definition in file alert-unified2-alert.c.
Macro Definition Documentation
#define DEFAULT_LIMIT 32 * 1024 * 1024
Minimum log file limit in MB.
Definition at line 79 of file alert-unified2-alert.c.
Referenced by Unified2AlertInitCtx().
#define DEFAULT_LOG_FILENAME "unified2.alert"
Default log file limit in MB.
Definition at line 76 of file alert-unified2-alert.c.
Referenced by Unified2AlertInitCtx().
#define MIN_LIMIT 1 * 1024 * 1024
Definition at line 82 of file alert-unified2-alert.c.
Referenced by Unified2AlertInitCtx().
#define MODULE_NAME "Unified2Alert"
Definition at line 237 of file alert-unified2-alert.c.
Referenced by TmModuleUnified2AlertRegister().
#define UNIFIED2_ALERT_FLAGS_EMIT_PACKET (1 << 0)
Definition at line 192 of file alert-unified2-alert.c.
Referenced by Unified2AlertInitCtx().
#define UNIFIED2_ALERT_XFF_IPV4 8
Extracted XFF IP is v4
Definition at line 182 of file alert-unified2-alert.c.
#define UNIFIED2_ALERT_XFF_IPV6 16
Extracted XFF IP is v4
Definition at line 184 of file alert-unified2-alert.c.
#define UNIFIED2_PACKET_SIZE (sizeof(Unified2Packet) - 4)
Definition at line 219 of file alert-unified2-alert.c.
Typedef Documentation
typedef struct AlertIPv4Unified2_ AlertIPv4Unified2
Unified2 Ipv4 struct
Used for storing ipv4 type values.
typedef struct AlertIPv6Unified2_ AlertIPv6Unified2
Unified2 Ipv6 type struct
Used for storing ipv6 type values.
typedef struct Unified2AlertFileCtx_ Unified2AlertFileCtx
typedef struct Unified2AlertFileHeader_ Unified2AlertFileHeader
Unified2 file header struct
Used for storing file header options.
typedef struct Unified2AlertThread_ Unified2AlertThread
Unified2 thread vars
Used for storing file options.
typedef struct AlertUnified2Packet_ Unified2Packet
Unified2 packet type struct
Used for storing packet type values.
Function Documentation
SC_ATOMIC_DECLARE (unsigned int, unified2_event_id)
Atomic counter, to link relative event
void TmModuleUnified2AlertRegister (void)
Definition at line 239 of file alert-unified2-alert.c.
References TmModule_::cap_flags, TmModule_::flags, MODULE_NAME, TmModule_::name, OutputRegisterPacketModule(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_ALERTUNIFIED2ALERT, tmm_modules, Unified2AlertInitCtx(), Unified2AlertThreadDeinit(), Unified2AlertThreadInit(), Unified2Condition(), Unified2Logger(), and Unified2RegisterTests().
Referenced by RegisterAllModules().
int Unified2AlertCloseFile (ThreadVars * t, Unified2AlertThread * aun)
Function to close unified2 file.
Parameters
t Thread Variable containing input/output queue, cpu affinity etc.
aun Unified2 thread variable.
Definition at line 261 of file alert-unified2-alert.c.
References Unified2AlertFileCtx_::file_ctx, LogFileCtx_::fp, LogFileCtx_::size_current, and Unified2AlertThread_::unified2alert_ctx.
Referenced by Unified2AlertRotateFile().
OutputCtx* Unified2AlertInitCtx (ConfNode * conf)
Create a new LogFileCtx from the provided ConfNode.
Parameters
conf The configuration node for this output.
Returns
NULL if failure, LogFileCtx* to the file_ctx if succesful
Definition at line 1247 of file alert-unified2-alert.c.
References ByteExtractStringUint32(), ConfNodeLookupChildValue(), ConfValIsFalse(), ConfValIsTrue(), OutputCtx_::data, DEFAULT_LIMIT, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, Unified2AlertFileCtx_::file_ctx, flags, Unified2AlertFileCtx_::flags, HttpXFFGetCfg(), LogFileNewCtx(), MIN_LIMIT, ParseSizeStringU64(), LogFileCtx_::prefix, SC_ATOMIC_INIT, SC_ERR_INVALID_ARGUMENT, SC_ERR_MEM_ALLOC, SC_ERR_UNIFIED2_ALERT_GENERIC, SCCalloc, SCFree, SCLogError, SCLogInfo, SCMalloc, SCStrdup, LogFileCtx_::size_limit, UNIFIED2_ALERT_FLAGS_EMIT_PACKET, Unified2AlertOpenFileCtx(), unlikely, and Unified2AlertFileCtx_::xff_cfg.
Referenced by TmModuleUnified2AlertRegister().
int Unified2AlertOpenFileCtx (LogFileCtx * file_ctx, const char * prefix)
Read the config set the file pointer, open the file.
Parameters
file_ctx pointer to a created LogFileCtx using LogFileNewCtx()
prefix Prefix of the log file.
Returns
-1 if failure, 0 if succesful
get the time so we can have a filename with seconds since epoch
Definition at line 1394 of file alert-unified2-alert.c.
References ConfigGetLogDirectory(), LogFileCtx_::filename, LogFileCtx_::fp, run_mode, RUNMODE_UNITTEST, SC_ERR_FOPEN, SCLogError, SCMalloc, TimeGet(), and unlikely.
Referenced by Unified2AlertInitCtx(), and Unified2AlertRotateFile().
int Unified2AlertRotateFile (ThreadVars * t, Unified2AlertThread * aun)
Function to rotate unified2 file.
Parameters
t Thread Variable containing input/output queue, cpu affinity etc.
aun Unified2 thread variable.
Return values
0 on succces
-1 on failure
Definition at line 280 of file alert-unified2-alert.c.
References Unified2AlertFileCtx_::file_ctx, SC_ERR_UNIFIED2_ALERT_GENERIC, SCLogError, Unified2AlertThread_::unified2alert_ctx, Unified2AlertCloseFile(), and Unified2AlertOpenFileCtx().
TmEcode Unified2AlertThreadDeinit (ThreadVars * t, void * data)
Thread deinit function.
Parameters
t Thread Variable containing input/output queue, cpu affinity etc.
data Unified2 thread data.
Return values
TM_ECODE_OK on succces
TM_ECODE_FAILED on failure
Definition at line 1213 of file alert-unified2-alert.c.
References LogFileCtx_::alerts, Unified2AlertThread_::data, Unified2AlertThread_::datalen, Unified2AlertFileCtx_::file_ctx, LogFileCtx_::flags, LOGFILE_ALERTS_PRINTED, SCFree, SCLogInfo, TM_ECODE_FAILED, TM_ECODE_OK, and Unified2AlertThread_::unified2alert_ctx.
Referenced by TmModuleUnified2AlertRegister().
TmEcode Unified2AlertThreadInit (ThreadVars * t, void * initdata, void ** data)
Thread init function.
prototypes
Parameters
t Thread Variable containing input/output queue, cpu affinity etc.
initdata Unified2 thread initial data.
data Unified2 thread data.
Return values
TM_ECODE_OK on succces
TM_ECODE_FAILED on failure
Use the Ouptut Context (file pointer and mutex)
Definition at line 1175 of file alert-unified2-alert.c.
References Unified2AlertThread_::data, Unified2AlertThread_::datalen, IPV4_MAXPACKET_LEN, SCFree, SCLogDebug, SCMalloc, TM_ECODE_FAILED, TM_ECODE_OK, Unified2AlertThread_::unified2alert_ctx, Unified2ExtraData, and unlikely.
Referenced by TmModuleUnified2AlertRegister().
int Unified2Condition (ThreadVars * tv, const Packet * p)
Definition at line 318 of file alert-unified2-alert.c.
References Packet_::alerts, PacketAlerts_::cnt, FALSE, Packet_::flags, likely, PKT_HAS_TAG, and TRUE.
Referenced by TmModuleUnified2AlertRegister().
int Unified2Logger (ThreadVars * t, void * data, const Packet * p)
Unified2 main entry function.
Return values
TM_ECODE_OK all is good
TM_ECODE_FAILED serious error
Be sure that we have a nice zeroed buffer
We can only have override mode if packet IP version matches the XFF IP version, otherwise fall-back to extra data
Definition at line 330 of file alert-unified2-alert.c.
Referenced by TmModuleUnified2AlertRegister().
void Unified2RegisterTests (void)
this function registers unit tests for Unified2
Definition at line 1971 of file alert-unified2-alert.c.
Referenced by TmModuleUnified2AlertRegister().
Variable Documentation
uint32_t event_length
Definition at line 87 of file alert-unified2-alert.c.
uint32_t event_type
Definition at line 86 of file alert-unified2-alert.c.
IPV4Hdr ip4h
Definition at line 331 of file alert-unified2-alert.c.
Referenced by DecodeIPFW(), and DecodeNFQ().
IPV6Hdr ip6h
Definition at line 331 of file alert-unified2-alert.c.
Referenced by DecodeIPFW(), and DecodeNFQ().
TCPHdr tcph
Definition at line 332 of file alert-unified2-alert.c.
Unified2ExtraData
Definition at line 107 of file alert-unified2-alert.c.
Referenced by Unified2AlertThreadInit().