suricata: src/alert-unified2-alert.h File Reference
alert-unified2-alert.h File Reference
Macros
#define UNIFIED2_PACKET_FLAG 1
#define UNIFIED2_BLOCKED_FLAG 0x20
#define UNIFIED2_EVENT_TYPE 1
#define UNIFIED2_PACKET_TYPE 2
#define UNIFIED2_IDS_EVENT_TYPE 7
#define UNIFIED2_EVENT_EXTENDED_TYPE 66
#define UNIFIED2_PERFORMANCE_TYPE 67
#define UNIFIED2_PORTSCAN_TYPE 68
#define UNIFIED2_IDS_EVENT_IPV6_TYPE 72
#define UNIFIED2_IDS_EVENT_MPLS_TYPE 99
#define UNIFIED2_IDS_EVENT_IPV6_MPLS_TYPE 100
#define UNIFIED2_IDS_EVENT_EXTRADATA_TYPE 110
#define UNIFIED2_EXTRADATA_CLIENT_IPV4_TYPE 1
#define UNIFIED2_EXTRADATA_CLIENT_IPV6_TYPE 1
#define UNIFIED2_EXTRADATA_TYPE_BLOB 1
#define UNIFIED2_EXTRADATA_TYPE_EXTRA_DATA 4
Functions
void TmModuleUnified2AlertRegister (void)
OutputCtx * Unified2AlertInitCtx (ConfNode *)
Create a new LogFileCtx from the provided ConfNode.
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Definition in file alert-unified2-alert.h.
Macro Definition Documentation
#define UNIFIED2_BLOCKED_FLAG 0x20
Definition at line 28 of file alert-unified2-alert.h.
#define UNIFIED2_EVENT_EXTENDED_TYPE 66
Definition at line 34 of file alert-unified2-alert.h.
#define UNIFIED2_EVENT_TYPE 1
Unified2 Header Types
Definition at line 31 of file alert-unified2-alert.h.
#define UNIFIED2_EXTRADATA_CLIENT_IPV4_TYPE 1
Definition at line 41 of file alert-unified2-alert.h.
#define UNIFIED2_EXTRADATA_CLIENT_IPV6_TYPE 1
Definition at line 42 of file alert-unified2-alert.h.
#define UNIFIED2_EXTRADATA_TYPE_BLOB 1
Definition at line 43 of file alert-unified2-alert.h.
#define UNIFIED2_EXTRADATA_TYPE_EXTRA_DATA 4
Definition at line 44 of file alert-unified2-alert.h.
#define UNIFIED2_IDS_EVENT_EXTRADATA_TYPE 110
Definition at line 40 of file alert-unified2-alert.h.
#define UNIFIED2_IDS_EVENT_IPV6_MPLS_TYPE 100
Definition at line 39 of file alert-unified2-alert.h.
#define UNIFIED2_IDS_EVENT_IPV6_TYPE 72
Definition at line 37 of file alert-unified2-alert.h.
#define UNIFIED2_IDS_EVENT_MPLS_TYPE 99
Definition at line 38 of file alert-unified2-alert.h.
#define UNIFIED2_IDS_EVENT_TYPE 7
Definition at line 33 of file alert-unified2-alert.h.
#define UNIFIED2_PACKET_FLAG 1
Unified2 Option packet action
Definition at line 27 of file alert-unified2-alert.h.
#define UNIFIED2_PACKET_TYPE 2
Definition at line 32 of file alert-unified2-alert.h.
#define UNIFIED2_PERFORMANCE_TYPE 67
Definition at line 35 of file alert-unified2-alert.h.
#define UNIFIED2_PORTSCAN_TYPE 68
Definition at line 36 of file alert-unified2-alert.h.
Function Documentation
void TmModuleUnified2AlertRegister (void)
Definition at line 239 of file alert-unified2-alert.c.
References TmModule_::cap_flags, TmModule_::flags, MODULE_NAME, TmModule_::name, OutputRegisterPacketModule(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_ALERTUNIFIED2ALERT, tmm_modules, Unified2AlertInitCtx(), Unified2AlertThreadDeinit(), Unified2AlertThreadInit(), Unified2Condition(), Unified2Logger(), and Unified2RegisterTests().
Referenced by RegisterAllModules().
OutputCtx* Unified2AlertInitCtx (ConfNode * conf)
Create a new LogFileCtx from the provided ConfNode.
Parameters
conf The configuration node for this output.
Returns
NULL if failure, LogFileCtx* to the file_ctx if succesful
Definition at line 1247 of file alert-unified2-alert.c.
References ByteExtractStringUint32(), ConfNodeLookupChildValue(), ConfValIsFalse(), ConfValIsTrue(), OutputCtx_::data, DEFAULT_LIMIT, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, Unified2AlertFileCtx_::file_ctx, flags, Unified2AlertFileCtx_::flags, HttpXFFGetCfg(), LogFileNewCtx(), MIN_LIMIT, ParseSizeStringU64(), LogFileCtx_::prefix, SC_ATOMIC_INIT, SC_ERR_INVALID_ARGUMENT, SC_ERR_MEM_ALLOC, SC_ERR_UNIFIED2_ALERT_GENERIC, SCCalloc, SCFree, SCLogError, SCLogInfo, SCMalloc, SCStrdup, LogFileCtx_::size_limit, UNIFIED2_ALERT_FLAGS_EMIT_PACKET, Unified2AlertOpenFileCtx(), unlikely, and Unified2AlertFileCtx_::xff_cfg.
Referenced by TmModuleUnified2AlertRegister().