suricata: src/app-layer-htp-file.c File Reference
app-layer-htp-file.c File Reference
#include "suricata.h"
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "util-radix-tree.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "util-spm.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "flow-util.h"
#include "detect-engine.h"
#include "detect-engine-state.h"
#include "detect-parse.h"
#include "conf.h"
#include "util-memcmp.h"
Functions
int HTPFileOpen (HtpState *s, uint8_t *filename, uint16_t filename_len, uint8_t *data, uint32_t data_len, uint16_t txid, uint8_t direction)
Open the file with "filename" and pass the first chunk of data if any.
int HTPFileStoreChunk (HtpState *s, uint8_t *data, uint32_t data_len, uint8_t direction)
Store a chunk of data in the flow.
int HTPFileClose (HtpState *s, uint8_t *data, uint32_t data_len, uint8_t flags, uint8_t direction)
Close the file in the flow.
void HTPFileParserRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
This file provides HTTP protocol file handling support for the engine using HTP library.
Definition in file app-layer-htp-file.c.
Function Documentation
int HTPFileClose (HtpState * s, uint8_t * data, uint32_t data_len, uint8_t flags, uint8_t direction)
Close the file in the flow.
Parameters
s http state
data data chunk if any
data_len length of the data portion
flags flags to indicate events
direction flow direction
Currently on the FLOW_FILE_TRUNCATED flag is implemented, indicating that the file isn't complete but we're stopping storing it.
Return values
0 ok
-1 error
-2 not storing files on this flow/tx
Definition at line 258 of file app-layer-htp-file.c.
References FileCloseFile(), FilePrune(), HtpState_::files_tc, HtpState_::files_ts, SCEnter, SCReturnInt, and STREAM_TOCLIENT.
Referenced by HtpRequestBodyHandleMultipart().
int HTPFileOpen (HtpState * s, uint8_t * filename, uint16_t filename_len, uint8_t * data, uint32_t data_len, uint16_t txid, uint8_t direction)
Open the file with "filename" and pass the first chunk of data if any.
Parameters
s http state
filename name of the file
filename_len length of the name
data data chunk (if any)
data_len length of the data portion
direction flow direction
Return values
0 ok
-1 error
-2 not handling files on this flow
Definition at line 79 of file app-layer-htp-file.c.
References HtpState_::f, FILE_NOMAGIC, FILE_NOMD5, FILE_NOSTORE, FILE_STORE, FileContainerAlloc(), FileOpenFile(), FilePrune(), HtpState_::files_tc, HtpState_::files_ts, FileSetTx(), flags, HtpState_::flags, Flow_::flags, FLOW_FILE_NO_MAGIC_TC, FLOW_FILE_NO_MAGIC_TS, FLOW_FILE_NO_MD5_TC, FLOW_FILE_NO_MD5_TS, FLOW_FILE_NO_STORE_TC, FLOW_FILE_NO_STORE_TS, HTP_FLAG_NEW_FILE_TX_TC, HTP_FLAG_NEW_FILE_TX_TS, HTP_FLAG_STORE_FILES_TC, HTP_FLAG_STORE_FILES_TS, HTP_FLAG_STORE_FILES_TX_TC, HTP_FLAG_STORE_FILES_TX_TS, SCLogDebug, SCReturnInt, HtpState_::store_tx_id, STREAM_TOCLIENT, FileContainer_::tail, and File_::txid.
Referenced by HtpRequestBodyHandleMultipart(), and HtpResponseBodyHandle().
void HTPFileParserRegisterTests (void)
Definition at line 1620 of file app-layer-htp-file.c.
Referenced by HTPParserRegisterTests().
int HTPFileStoreChunk (HtpState * s, uint8_t * data, uint32_t data_len, uint8_t direction)
Store a chunk of data in the flow.
Parameters
s http state
data data chunk (if any)
data_len length of the data portion
direction flow direction
Return values
0 ok
-1 error
-2 file doesn't need storing
Definition at line 204 of file app-layer-htp-file.c.
References FileAppendData(), FilePrune(), HtpState_::files_tc, HtpState_::files_ts, SCEnter, SCLogDebug, SCReturnInt, and STREAM_TOCLIENT.
Referenced by HtpRequestBodyHandleMultipart(), and HtpResponseBodyHandle().