suricata: src/app-layer-dcerpc-udp.c File Reference
app-layer-dcerpc-udp.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "debug.h"
#include "decode.h"
#include "flow-util.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "util-debug.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer.h"
#include "util-spm.h"
#include "util-unittest.h"
#include "app-layer-dcerpc-udp.h"
Enumerations
enum {
DCERPC_FIELD_NONE = 0, DCERPC_PARSE_DCERPC_HEADER, DCERPC_PARSE_DCERPC_BIND, DCERPC_PARSE_DCERPC_BIND_ACK,
DCERPC_PARSE_DCERPC_REQUEST, DCERPC_FIELD_MAX
}
Functions
void RegisterDCERPCUDPParsers (void)
Enumeration Type Documentation
anonymous enum
Enumerator
DCERPC_FIELD_NONE
DCERPC_PARSE_DCERPC_HEADER
DCERPC_PARSE_DCERPC_BIND
DCERPC_PARSE_DCERPC_BIND_ACK
DCERPC_PARSE_DCERPC_REQUEST
DCERPC_FIELD_MAX
Definition at line 38 of file app-layer-dcerpc-udp.c.
Function Documentation
void RegisterDCERPCUDPParsers (void)
Definition at line 822 of file app-layer-dcerpc-udp.c.
References ALPROTO_DCERPC, AppLayerParserConfParserEnabled(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), DCERPCUDPParserRegisterTests(), SCLogInfo, STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().