suricata: src/app-layer-template.h File Reference
app-layer-template.h File Reference
#include "detect-engine-state.h"
#include "queue.h"
Data Structures
struct TemplateTransaction_
struct TemplateState_
Typedefs
typedef struct TemplateTransaction_ TemplateTransaction
typedef struct TemplateState_ TemplateState
Functions
void RegisterTemplateParsers (void)
void TemplateParserRegisterTests (void)
Typedef Documentation
typedef struct TemplateState_ TemplateState
typedef struct TemplateTransaction_ TemplateTransaction
Function Documentation
void RegisterTemplateParsers (void)
Definition at line 428 of file app-layer-template.c.
References ALPROTO_TEMPLATE, AppLayerParserConfParserEnabled(), AppLayerParserRegisterDetectStateFuncs(), AppLayerParserRegisterGetEventInfo(), AppLayerParserRegisterGetEventsFunc(), AppLayerParserRegisterGetStateProgressCompletionStatus(), AppLayerParserRegisterGetStateProgressFunc(), AppLayerParserRegisterGetTx(), AppLayerParserRegisterGetTxCnt(), AppLayerParserRegisterHasEventsFunc(), AppLayerParserRegisterParser(), AppLayerParserRegisterStateFuncs(), AppLayerParserRegisterTxFreeFunc(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectPPParseConfPorts(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), ConfGetNode(), RunmodeIsUnittests(), SCLogNotice, STREAM_TOCLIENT, STREAM_TOSERVER, TEMPLATE_DEFAULT_PORT, TEMPLATE_MIN_FRAME_LEN, and TemplateParserRegisterTests().
Referenced by AppLayerParserRegisterProtocolParsers().
void TemplateParserRegisterTests (void)
Definition at line 537 of file app-layer-template.c.
Referenced by RegisterTemplateParsers().