suricata: src/app-layer-detect-proto.h File Reference
app-layer-detect-proto.h File Reference
Typedefs
typedef struct
AppLayerProtoDetectThreadCtx_ AppLayerProtoDetectThreadCtx
typedef AppProto(* ProbingParserFPtr)(uint8_t *input, uint32_t input_len, uint32_t *offset)
Functions
AppProto AppLayerProtoDetectGetProto (AppLayerProtoDetectThreadCtx *tctx, Flow *f, uint8_t *buf, uint32_t buflen, uint8_t ipproto, uint8_t direction)
Returns the app layer protocol given a buffer.
int AppLayerProtoDetectPrepareState (void)
Prepares the internal state for protocol detection. This needs to be called once all the patterns and probing parser ports have been registered.
void AppLayerProtoDetectPPRegister (uint8_t ipproto, char *portstr, AppProto alproto, uint16_t min_depth, uint16_t max_depth, uint8_t direction, ProbingParserFPtr ProbingParser)
register parser at a port
int AppLayerProtoDetectPPParseConfPorts (const char *ipproto_name, uint8_t ipproto, const char *alproto_name, AppProto alproto, uint16_t min_depth, uint16_t max_depth, ProbingParserFPtr ProbingParser)
int AppLayerProtoDetectPMRegisterPatternCS (uint8_t ipproto, AppProto alproto, char *pattern, uint16_t depth, uint16_t offset, uint8_t direction)
Registers a case-sensitive pattern for protocol detection.
int AppLayerProtoDetectPMRegisterPatternCI (uint8_t ipproto, AppProto alproto, char *pattern, uint16_t depth, uint16_t offset, uint8_t direction)
Registers a case-insensitive pattern for protocol detection.
int AppLayerProtoDetectSetup (void)
The first function to be called. This initializes a global protocol detection context.
int AppLayerProtoDetectDeSetup (void)
Cleans up the app layer protocol detection phase.
void AppLayerProtoDetectRegisterProtocol (AppProto alproto, char *alproto_name)
Registers a protocol for protocol detection phase.
int AppLayerProtoDetectConfProtoDetectionEnabled (const char *ipproto, const char *alproto)
Given a protocol name, checks if proto detection is enabled in the conf file.
AppLayerProtoDetectThreadCtx * AppLayerProtoDetectGetCtxThread (void)
Inits and returns an app layer protocol detection thread context.
void AppLayerProtoDetectDestroyCtxThread (AppLayerProtoDetectThreadCtx *tctx)
Destroys the app layer protocol detection thread context.
void AppLayerProtoDetectSupportedIpprotos (AppProto alproto, uint8_t *ipprotos)
AppProto AppLayerProtoDetectGetProtoByName (char *alproto_name)
char * AppLayerProtoDetectGetProtoName (AppProto alproto)
void AppLayerProtoDetectSupportedAppProtocols (AppProto *alprotos)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file app-layer-detect-proto.h.
Typedef Documentation
typedef struct AppLayerProtoDetectThreadCtx_ AppLayerProtoDetectThreadCtx
Definition at line 28 of file app-layer-detect-proto.h.
typedef AppProto(* ProbingParserFPtr)(uint8_t *input, uint32_t input_len, uint32_t *offset)
Definition at line 30 of file app-layer-detect-proto.h.
Function Documentation
int AppLayerProtoDetectConfProtoDetectionEnabled (const char * ipproto, const char * alproto)
Given a protocol name, checks if proto detection is enabled in the conf file.
Parameters
alproto Name of the app layer protocol.
Return values
1 If enabled.
0 If disabled.
Definition at line 1592 of file app-layer-detect-proto.c.
References BUG_ON, ConfGetNode(), ConfValIsFalse(), ConfValIsTrue(), RunmodeIsUnittests(), SC_ERR_FATAL, SCEnter, SCLogDebug, SCLogError, SCReturnInt, and ConfNode_::val.
Referenced by AppLayerParserRegisterProtocolParsers(), HTPFreeConfig(), RegisterDCERPCParsers(), RegisterDCERPCUDPParsers(), RegisterDNSTCPParsers(), RegisterDNSUDPParsers(), RegisterFTPParsers(), RegisterHTPParsers(), RegisterModbusParsers(), RegisterSMB2Parsers(), RegisterSMBParsers(), RegisterSMTPParsers(), RegisterSSHParsers(), RegisterSSLParsers(), and RegisterTemplateParsers().
int AppLayerProtoDetectDeSetup (void)
Cleans up the app layer protocol detection phase.
Todo:
incomplete. Need more work.
Definition at line 1548 of file app-layer-detect-proto.c.
References MpmCtx_::ctx, AppLayerProtoDetectCtx_::ctx_ipp, AppLayerProtoDetectCtxIpproto_::ctx_pm, AppLayerProtoDetectCtx_::ctx_pp, MpmTableElmt_::DestroyCtx, FLOW_PROTO_DEFAULT, AppLayerProtoDetectPMCtx_::map, AppLayerProtoDetectPMCtx_::max_pat_id, AppLayerProtoDetectPMCtx_::mpm_ctx, mpm_table, MpmCtx_::mpm_type, AppLayerProtoDetectPMSignature_::next, PatIntId, SCEnter, and SCReturnInt.
Referenced by AppLayerDeSetup().
void AppLayerProtoDetectDestroyCtxThread (AppLayerProtoDetectThreadCtx * tctx)
Destroys the app layer protocol detection thread context.
Parameters
tctx Pointer to the app layer protocol detection thread context.
Definition at line 1706 of file app-layer-detect-proto.c.
References AppLayerProtoDetectCtx_::ctx_ipp, AppLayerProtoDetectCtxIpproto_::ctx_pm, MpmTableElmt_::DestroyThreadCtx, FLOW_PROTO_DEFAULT, AppLayerProtoDetectPMCtx_::mpm_ctx, mpm_table, AppLayerProtoDetectThreadCtx_::mpm_tctx, MpmCtx_::mpm_type, AppLayerProtoDetectThreadCtx_::pmq, PmqFree(), SCEnter, SCFree, and SCReturn.
Referenced by AppLayerDestroyCtxThread(), and AppLayerProtoDetectGetCtxThread().
AppLayerProtoDetectThreadCtx* AppLayerProtoDetectGetCtxThread (void)
Inits and returns an app layer protocol detection thread context.
Parameters
ctx Pointer to the app layer protocol detection context.
Return values
Pointer to the thread context, on success; NULL, on failure.
Definition at line 1657 of file app-layer-detect-proto.c.
References AppLayerProtoDetectDestroyCtxThread(), AppLayerProtoDetectCtx_::ctx_ipp, AppLayerProtoDetectCtxIpproto_::ctx_pm, FLOW_PROTO_DEFAULT, MpmTableElmt_::InitThreadCtx, AppLayerProtoDetectPMCtx_::max_pat_id, AppLayerProtoDetectPMCtx_::mpm_ctx, mpm_table, AppLayerProtoDetectThreadCtx_::mpm_tctx, MpmCtx_::mpm_type, PatIntId, AppLayerProtoDetectThreadCtx_::pmq, PmqSetup(), SCEnter, SCMalloc, and SCReturnPtr.
Referenced by AppLayerGetCtxThread().
AppProto AppLayerProtoDetectGetProto (AppLayerProtoDetectThreadCtx * tctx, Flow * f, uint8_t * buf, uint32_t buflen, uint8_t ipproto, uint8_t direction)
Returns the app layer protocol given a buffer.
Parameters
tctx Pointer to the app layer protocol detection thread context.
f Pointer to the flow.
buf The buffer to be inspected.
buflen The length of the above buffer.
ipproto The ip protocol.
direction The direction bitfield - STREAM_TOSERVER/STREAM_TOCLIENT.
Return values
The app layer protocol.
Definition at line 1293 of file app-layer-detect-proto.c.
References ALPROTO_MAX, ALPROTO_UNKNOWN, FLOW_IS_PM_DONE, FLOW_IS_PP_DONE, SCEnter, and SCReturnCT.
Referenced by AppLayerHandleTCPData(), and AppLayerHandleUdp().
AppProto AppLayerProtoDetectGetProtoByName (char * alproto_name)
Definition at line 1739 of file app-layer-detect-proto.c.
References ALPROTO_MAX, AppLayerProtoDetectCtx_::alproto_names, ALPROTO_UNKNOWN, SCEnter, SCMemcmp, and SCReturnCT.
Referenced by AppLayerGetProtoByName().
char* AppLayerProtoDetectGetProtoName (AppProto alproto)
Definition at line 1756 of file app-layer-detect-proto.c.
References AppLayerProtoDetectCtx_::alproto_names.
Referenced by AppLayerGetProtoName().
int AppLayerProtoDetectPMRegisterPatternCI (uint8_t ipproto, AppProto alproto, char * pattern, uint16_t depth, uint16_t offset, uint8_t direction)
Registers a case-insensitive pattern for protocol detection.
Definition at line 1512 of file app-layer-detect-proto.c.
References SCEnter, and SCReturnInt.
int AppLayerProtoDetectPMRegisterPatternCS (uint8_t ipproto, AppProto alproto, char * pattern, uint16_t depth, uint16_t offset, uint8_t direction)
Registers a case-sensitive pattern for protocol detection.
Definition at line 1497 of file app-layer-detect-proto.c.
References SCEnter, and SCReturnInt.
Referenced by AppLayerParserRegisterProtocolParsers().
int AppLayerProtoDetectPPParseConfPorts (const char * ipproto_name, uint8_t ipproto, const char * alproto_name, AppProto alproto, uint16_t min_depth, uint16_t max_depth, ProbingParserFPtr ProbingParser)
Return values
bool 0 if no config was found, 1 if config was found
Definition at line 1420 of file app-layer-detect-proto.c.
References AppLayerProtoDetectPPRegister(), ConfGetNode(), ConfNodeLookupChild(), SC_ERR_FATAL, SCEnter, SCLogDebug, SCLogError, SCReturnInt, STREAM_TOCLIENT, and ConfNode_::val.
Referenced by RegisterDNSTCPParsers(), RegisterDNSUDPParsers(), RegisterModbusParsers(), RegisterSMBParsers(), RegisterSSLParsers(), and RegisterTemplateParsers().
void AppLayerProtoDetectPPRegister (uint8_t ipproto, char * portstr, AppProto alproto, uint16_t min_depth, uint16_t max_depth, uint8_t direction, ProbingParserFPtr ProbingParser)
register parser at a port
Parameters
direction STREAM_TOSERVER or STREAM_TOCLIENT for dp or sp
Definition at line 1388 of file app-layer-detect-proto.c.
References AppLayerProtoDetectCtx_::ctx_pp, DetectPortCleanupList(), DetectPortParse(), head, DetectPort_::next, DetectPort_::port, DetectPort_::port2, SCEnter, and SCReturn.
Referenced by AppLayerProtoDetectPPParseConfPorts(), RegisterDNSTCPParsers(), RegisterDNSUDPParsers(), RegisterModbusParsers(), RegisterSMBParsers(), RegisterSSLParsers(), and RegisterTemplateParsers().
int AppLayerProtoDetectPrepareState (void)
Prepares the internal state for protocol detection. This needs to be called once all the patterns and probing parser ports have been registered.
Definition at line 1344 of file app-layer-detect-proto.c.
References AppLayerProtoDetectPrintProbingParsers(), AppLayerProtoDetectCtx_::ctx_ipp, AppLayerProtoDetectCtxIpproto_::ctx_pm, AppLayerProtoDetectCtx_::ctx_pp, FLOW_PROTO_DEFAULT, AppLayerProtoDetectPMCtx_::max_pat_id, SCEnter, SCLogDebugEnabled(), and SCReturnInt.
Referenced by AppLayerSetup().
void AppLayerProtoDetectRegisterProtocol (AppProto alproto, char * alproto_name)
Registers a protocol for protocol detection phase.
   This is the first function to be called after calling the
   setup function, AppLayerProtoDetectSetup(), before calling any other
   app layer functions, AppLayerParser or AppLayerProtoDetect, alike.
   With this function you are associating/registering a string
   that can be used by users to write rules, i.e.
   you register the http protocol for protocol detection using
   AppLayerProtoDetectRegisterProtocol(ctx, ALPROTO_HTTP, "http"),
   following which you can write rules like -
   alert http any any -> any any (sid:1;)
   which basically matches on the HTTP protocol.
Parameters
alproto The protocol.
alproto_str The string to associate with the above "alproto". Please send a static string that won't be destroyed post making this call, since this function won't create a copy of the received argument.
Return values
0 On success; -1 On failure.
Definition at line 1578 of file app-layer-detect-proto.c.
References AppLayerProtoDetectCtx_::alproto_names, SCEnter, and SCReturn.
Referenced by AppLayerParserRegisterProtocolParsers(), RegisterDCERPCParsers(), RegisterDCERPCUDPParsers(), RegisterDNSTCPParsers(), RegisterDNSUDPParsers(), RegisterFTPParsers(), RegisterHTPParsers(), RegisterModbusParsers(), RegisterSMBParsers(), RegisterSMTPParsers(), RegisterSSHParsers(), RegisterSSLParsers(), and RegisterTemplateParsers().
int AppLayerProtoDetectSetup (void)
The first function to be called. This initializes a global protocol detection context.
Return values
0 On succcess;
-1 On failure.
Definition at line 1529 of file app-layer-detect-proto.c.
References AppLayerProtoDetectCtx_::ctx_ipp, AppLayerProtoDetectCtxIpproto_::ctx_pm, FLOW_PROTO_DEFAULT, MPM_AC, AppLayerProtoDetectPMCtx_::mpm_ctx, MpmInitCtx(), SCEnter, and SCReturnInt.
Referenced by AppLayerSetup().
void AppLayerProtoDetectSupportedAppProtocols (AppProto * alprotos)
Definition at line 1761 of file app-layer-detect-proto.c.
References ALPROTO_MAX, AppLayerProtoDetectCtx_::alproto_names, SCEnter, and SCReturn.
Referenced by AppLayerListSupportedProtocols().
void AppLayerProtoDetectSupportedIpprotos (AppProto alproto, uint8_t * ipprotos)
Definition at line 1729 of file app-layer-detect-proto.c.
References SCEnter, and SCReturn.