suricata: src/app-layer-smb2.h File Reference
app-layer-smb2.h File Reference
#include "suricata-common.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer-nbss.h"
#include "flow.h"
#include "stream.h"
Data Structures
struct SMB2Hdr
struct SMB2State_
Macros
#define SMB2_HDR_LEN 64
#define SMB2_NEGOTIATE 0x0000
#define SMB2_SESSION_SETUP 0x0001
#define SMB2_LOGOFF 0x0002
#define SMB2_TREE_CONNECT 0x0003
#define SMB2_TREE_DISCONNECT 0x0004
#define SMB2_CREATE 0x0005
#define SMB2_CLOSE 0x0006
#define SMB2_FLUSH 0x0007
#define SMB2_READ 0x0008
#define SMB2_WRITE 0x0009
#define SMB2_LOCK 0x000A
#define SMB2_IOCTL 0x000B
#define SMB2_CANCEL 0x000C
#define SMB2_ECHO 0x000D
#define SMB2_QUERY_DIRECTORY 0x000E
#define SMB2_CHANGE_NOTIFY 0x000F
#define SMB2_QUERY_INFO 0x0010
#define SMB2_SET_INFO 0x0011
#define SMB2_OPLOCK_BREAK 0x0012
Typedefs
typedef struct SMB2Hdr SMB2Hdr
typedef struct SMB2State_ SMB2State
Functions
void RegisterSMB2Parsers (void)
void SMB2ParserRegisterTests (void)
Detailed Description
Author
Kirby Kuehl kkueh.nosp@m.l@gm.nosp@m.ail.c.nosp@m.om
Definition in file app-layer-smb2.h.
Macro Definition Documentation
#define SMB2_CANCEL 0x000C
Definition at line 71 of file app-layer-smb2.h.
#define SMB2_CHANGE_NOTIFY 0x000F
Definition at line 74 of file app-layer-smb2.h.
#define SMB2_CLOSE 0x0006
Definition at line 65 of file app-layer-smb2.h.
#define SMB2_CREATE 0x0005
Definition at line 64 of file app-layer-smb2.h.
#define SMB2_ECHO 0x000D
Definition at line 72 of file app-layer-smb2.h.
#define SMB2_FLUSH 0x0007
Definition at line 66 of file app-layer-smb2.h.
#define SMB2_HDR_LEN 64
Definition at line 50 of file app-layer-smb2.h.
#define SMB2_IOCTL 0x000B
Definition at line 70 of file app-layer-smb2.h.
#define SMB2_LOCK 0x000A
Definition at line 69 of file app-layer-smb2.h.
#define SMB2_LOGOFF 0x0002
Definition at line 61 of file app-layer-smb2.h.
#define SMB2_NEGOTIATE 0x0000
from http://msdn.microsoft.com/en-us/library/cc246528(PROT.13).aspx
Definition at line 59 of file app-layer-smb2.h.
#define SMB2_OPLOCK_BREAK 0x0012
Definition at line 77 of file app-layer-smb2.h.
#define SMB2_QUERY_DIRECTORY 0x000E
Definition at line 73 of file app-layer-smb2.h.
#define SMB2_QUERY_INFO 0x0010
Definition at line 75 of file app-layer-smb2.h.
#define SMB2_READ 0x0008
Definition at line 67 of file app-layer-smb2.h.
#define SMB2_SESSION_SETUP 0x0001
Definition at line 60 of file app-layer-smb2.h.
#define SMB2_SET_INFO 0x0011
Definition at line 76 of file app-layer-smb2.h.
#define SMB2_TREE_CONNECT 0x0003
Definition at line 62 of file app-layer-smb2.h.
#define SMB2_TREE_DISCONNECT 0x0004
Definition at line 63 of file app-layer-smb2.h.
#define SMB2_WRITE 0x0009
Definition at line 68 of file app-layer-smb2.h.
Typedef Documentation
typedef struct SMB2Hdr SMB2Hdr
typedef struct SMB2State_ SMB2State
Function Documentation
void RegisterSMB2Parsers (void)
SMB2
Definition at line 597 of file app-layer-smb2.c.
References ALPROTO_SMB2, AppLayerParserRegisterParser(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), SCLogInfo, SMB2ParserRegisterTests(), STREAM_TOCLIENT, and STREAM_TOSERVER.
void SMB2ParserRegisterTests (void)
Referenced by RegisterSMB2Parsers().