suricata: src/app-layer-ssl.h File Reference
app-layer-ssl.h File Reference
#include "decode-events.h"
#include "queue.h"
Data Structures
struct SSLCertsChain_
struct SSLStateConnp_
struct SSLState_
SSLv[2.0|3.[0|1|2|3]] state structure.
Macros
#define SSL_AL_FLAG_SERVER_CHANGE_CIPHER_SPEC 0x0001
#define SSL_AL_FLAG_CLIENT_CHANGE_CIPHER_SPEC 0x0002
#define SSL_AL_FLAG_CHANGE_CIPHER_SPEC 0x0004
#define SSL_AL_FLAG_SSL_CLIENT_HS 0x0008
#define SSL_AL_FLAG_SSL_SERVER_HS 0x0010
#define SSL_AL_FLAG_SSL_CLIENT_MASTER_KEY 0x0020
#define SSL_AL_FLAG_SSL_CLIENT_SSN_ENCRYPTED 0x0040
#define SSL_AL_FLAG_SSL_SERVER_SSN_ENCRYPTED 0x0080
#define SSL_AL_FLAG_SSL_NO_SESSION_ID 0x0100
#define SSL_AL_FLAG_STATE_CLIENT_HELLO 0x0200
#define SSL_AL_FLAG_STATE_SERVER_HELLO 0x0400
#define SSL_AL_FLAG_STATE_CLIENT_KEYX 0x0800
#define SSL_AL_FLAG_STATE_SERVER_KEYX 0x1000
#define SSL_AL_FLAG_STATE_UNKNOWN 0x2000
#define SSL_AL_FLAG_STATE_LOGGED 0x4000
#define SSL_AL_FLAG_HB_INFLIGHT 0x8000
#define SSL_AL_FLAG_HB_CLIENT_INIT 0x10000
#define SSL_AL_FLAG_HB_SERVER_INIT 0x20000
#define SSL_AL_FLAG_STATE_STORED 0x40000
#define SSL_AL_FLAG_STATE_LOGGED_LUA 0x80000
#define SSL_TLS_LOG_PEM (1 << 0)
Typedefs
typedef struct SSLCertsChain_ SSLCertsChain
typedef struct SSLStateConnp_ SSLStateConnp
typedef struct SSLState_ SSLState
SSLv[2.0|3.[0|1|2|3]] state structure.
Enumerations
enum {
TLS_DECODER_EVENT_INVALID_SSLV2_HEADER, TLS_DECODER_EVENT_INVALID_TLS_HEADER, TLS_DECODER_EVENT_INVALID_RECORD_VERSION, TLS_DECODER_EVENT_INVALID_RECORD_TYPE,
TLS_DECODER_EVENT_INVALID_HANDSHAKE_MESSAGE, TLS_DECODER_EVENT_HEARTBEAT, TLS_DECODER_EVENT_INVALID_HEARTBEAT, TLS_DECODER_EVENT_OVERFLOW_HEARTBEAT,
TLS_DECODER_EVENT_DATALEAK_HEARTBEAT_MISMATCH, TLS_DECODER_EVENT_INVALID_CERTIFICATE, TLS_DECODER_EVENT_CERTIFICATE_MISSING_ELEMENT, TLS_DECODER_EVENT_CERTIFICATE_UNKNOWN_ELEMENT,
TLS_DECODER_EVENT_CERTIFICATE_INVALID_LENGTH, TLS_DECODER_EVENT_CERTIFICATE_INVALID_STRING, TLS_DECODER_EVENT_ERROR_MSG_ENCOUNTERED, TLS_DECODER_EVENT_INVALID_SSL_RECORD
}
enum {
TLS_VERSION_UNKNOWN = 0x0000, SSL_VERSION_2 = 0x0200, SSL_VERSION_3 = 0x0300, TLS_VERSION_10 = 0x0301,
TLS_VERSION_11 = 0x0302, TLS_VERSION_12 = 0x0303
}
Functions
void RegisterSSLParsers (void)
Function to register the SSL protocol parser and other functions.
void SSLParserRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Pierre Chifflier pierr.nosp@m.e.ch.nosp@m.iffli.nosp@m.er@s.nosp@m.si.go.nosp@m.uv.f.nosp@m.r
Definition in file app-layer-ssl.h.
Macro Definition Documentation
#define SSL_AL_FLAG_CHANGE_CIPHER_SPEC 0x0004
Definition at line 57 of file app-layer-ssl.h.
#define SSL_AL_FLAG_CLIENT_CHANGE_CIPHER_SPEC 0x0002
Definition at line 56 of file app-layer-ssl.h.
#define SSL_AL_FLAG_HB_CLIENT_INIT 0x10000
Definition at line 78 of file app-layer-ssl.h.
#define SSL_AL_FLAG_HB_INFLIGHT 0x8000
Definition at line 77 of file app-layer-ssl.h.
#define SSL_AL_FLAG_HB_SERVER_INIT 0x20000
Definition at line 79 of file app-layer-ssl.h.
#define SSL_AL_FLAG_SERVER_CHANGE_CIPHER_SPEC 0x0001
Definition at line 54 of file app-layer-ssl.h.
#define SSL_AL_FLAG_SSL_CLIENT_HS 0x0008
Definition at line 60 of file app-layer-ssl.h.
#define SSL_AL_FLAG_SSL_CLIENT_MASTER_KEY 0x0020
Definition at line 62 of file app-layer-ssl.h.
#define SSL_AL_FLAG_SSL_CLIENT_SSN_ENCRYPTED 0x0040
Definition at line 63 of file app-layer-ssl.h.
#define SSL_AL_FLAG_SSL_NO_SESSION_ID 0x0100
Definition at line 65 of file app-layer-ssl.h.
#define SSL_AL_FLAG_SSL_SERVER_HS 0x0010
Definition at line 61 of file app-layer-ssl.h.
#define SSL_AL_FLAG_SSL_SERVER_SSN_ENCRYPTED 0x0080
Definition at line 64 of file app-layer-ssl.h.
#define SSL_AL_FLAG_STATE_CLIENT_HELLO 0x0200
Definition at line 68 of file app-layer-ssl.h.
Referenced by DetectSslStateMatch().
#define SSL_AL_FLAG_STATE_CLIENT_KEYX 0x0800
Definition at line 70 of file app-layer-ssl.h.
Referenced by DetectSslStateMatch().
#define SSL_AL_FLAG_STATE_LOGGED 0x4000
Definition at line 74 of file app-layer-ssl.h.
#define SSL_AL_FLAG_STATE_LOGGED_LUA 0x80000
Definition at line 84 of file app-layer-ssl.h.
#define SSL_AL_FLAG_STATE_SERVER_HELLO 0x0400
Definition at line 69 of file app-layer-ssl.h.
Referenced by DetectSslStateMatch().
#define SSL_AL_FLAG_STATE_SERVER_KEYX 0x1000
Definition at line 71 of file app-layer-ssl.h.
Referenced by DetectSslStateMatch().
#define SSL_AL_FLAG_STATE_STORED 0x40000
Definition at line 82 of file app-layer-ssl.h.
#define SSL_AL_FLAG_STATE_UNKNOWN 0x2000
Definition at line 72 of file app-layer-ssl.h.
#define SSL_TLS_LOG_PEM (1 << 0)
Definition at line 87 of file app-layer-ssl.h.
Typedef Documentation
typedef struct SSLCertsChain_ SSLCertsChain
typedef struct SSLState_ SSLState
SSLv[2.0|3.[0|1|2|3]] state structure.
Structure to store the SSL state values.
typedef struct SSLStateConnp_ SSLStateConnp
Enumeration Type Documentation
anonymous enum
Enumerator
TLS_DECODER_EVENT_INVALID_SSLV2_HEADER
TLS_DECODER_EVENT_INVALID_TLS_HEADER
TLS_DECODER_EVENT_INVALID_RECORD_VERSION
TLS_DECODER_EVENT_INVALID_RECORD_TYPE
TLS_DECODER_EVENT_INVALID_HANDSHAKE_MESSAGE
TLS_DECODER_EVENT_HEARTBEAT
TLS_DECODER_EVENT_INVALID_HEARTBEAT
TLS_DECODER_EVENT_OVERFLOW_HEARTBEAT
TLS_DECODER_EVENT_DATALEAK_HEARTBEAT_MISMATCH
TLS_DECODER_EVENT_INVALID_CERTIFICATE
TLS_DECODER_EVENT_CERTIFICATE_MISSING_ELEMENT
TLS_DECODER_EVENT_CERTIFICATE_UNKNOWN_ELEMENT
TLS_DECODER_EVENT_CERTIFICATE_INVALID_LENGTH
TLS_DECODER_EVENT_CERTIFICATE_INVALID_STRING
TLS_DECODER_EVENT_ERROR_MSG_ENCOUNTERED
TLS_DECODER_EVENT_INVALID_SSL_RECORD
Definition at line 32 of file app-layer-ssl.h.
anonymous enum
Enumerator
TLS_VERSION_UNKNOWN
SSL_VERSION_2
SSL_VERSION_3
TLS_VERSION_10
TLS_VERSION_11
TLS_VERSION_12
Definition at line 93 of file app-layer-ssl.h.
Function Documentation
void RegisterSSLParsers (void)
Function to register the SSL protocol parser and other functions.
SSLv2 and SSLv23
Definition at line 1345 of file app-layer-ssl.c.
References ALPROTO_TLS, AppLayerParserConfParserEnabled(), AppLayerParserRegisterGetEventInfo(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectPPParseConfPorts(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), ConfGetBool(), ConfGetNode(), SslConfig_::no_reassemble, RunmodeIsUnittests(), SCLogInfo, SSLParseClientRecord(), SSLParserRegisterTests(), SSLParseServerRecord(), SSLStateAlloc(), SSLStateFree(), SSLStateGetEventInfo(), STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().
void SSLParserRegisterTests (void)
Definition at line 4184 of file app-layer-ssl.c.
Referenced by RegisterSSLParsers().