suricata: src/app-layer-smb2.c File Reference
app-layer-smb2.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "util-spm.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "util-memcmp.h"
#include "app-layer-smb2.h"
Enumerations
enum { SMB2_FIELD_NONE = 0, SMB2_PARSE_NBSS_HEADER, SMB2_PARSE_SMB_HEADER, SMB_FIELD_MAX }
Functions
void RegisterSMB2Parsers (void)
Detailed Description
Author
Kirby Kuehl kkueh.nosp@m.l@gm.nosp@m.ail.c.nosp@m.om
SMBv2 parser/decoder
Definition in file app-layer-smb2.c.
Enumeration Type Documentation
anonymous enum
Enumerator
SMB2_FIELD_NONE
SMB2_PARSE_NBSS_HEADER
SMB2_PARSE_SMB_HEADER
SMB_FIELD_MAX
Definition at line 51 of file app-layer-smb2.c.
Function Documentation
void RegisterSMB2Parsers (void)
SMB2
Definition at line 597 of file app-layer-smb2.c.
References ALPROTO_SMB2, AppLayerParserRegisterParser(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), SCLogInfo, SMB2ParserRegisterTests(), STREAM_TOCLIENT, and STREAM_TOSERVER.