suricata: src/app-layer-htp-libhtp.c File Reference
app-layer-htp-libhtp.c File Reference
#include "suricata.h"
#include "suricata-common.h"
Functions
int64_t SC_htp_parse_content_length (bstr *b)
A direct flick off libhtp-0.5.x htp_parse_content_length()
bstr * SCHTPGenerateNormalizedUri (htp_tx_t *tx, htp_uri_t *uri, int uri_include_all)
Generates the normalized uri.
Function Documentation
int64_t SC_htp_parse_content_length (bstr * b)
A direct flick off libhtp-0.5.x htp_parse_content_length()
Definition at line 90 of file app-layer-htp-libhtp.c.
References bstr_len, and bstr_ptr.
bstr* SCHTPGenerateNormalizedUri (htp_tx_t * tx, htp_uri_t * uri, int uri_include_all)
Generates the normalized uri.
   Libhtp doesn't recreate the whole normalized uri and save it.
   That duty has now been passed to us.  A lot of this code has been
   copied from libhtp.
   Keep an eye out on the tx->parsed_uri struct and how the parameters
   in it are generated, just in case some modifications are made to
   them in the future.
Parameters
uri_include_all boolean to indicate if scheme, username/password, hostname and port should be part of the buffer
Definition at line 109 of file app-layer-htp-libhtp.c.
References bstr_add_c(), bstr_add_c_noex(), bstr_add_noex(), bstr_alloc(), bstr_dup(), bstr_free(), bstr_len, htp_tx_t::cfg, flags, htp_uri_t::fragment, htp_uri_t::hostname, HTP_DECODER_URLENCODED, htp_urldecode_inplace(), htp_uri_t::password, htp_uri_t::path, htp_uri_t::port, htp_uri_t::query, htp_uri_t::scheme, and htp_uri_t::username.