suricata: src/app-layer-ssh.c File Reference
app-layer-ssh.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer-ssh.h"
#include "conf.h"
#include "util-spm.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "flow-private.h"
#include "util-byte.h"
#include "util-memcmp.h"
Macros
#define MAX_BANNER_LEN 256
Functions
void RegisterSSHParsers (void)
Function to register the SSH protocol parsers and other functions.
void SSHParserRegisterTests (void)
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
App-layer parser for SSH protocol
Definition in file app-layer-ssh.c.
Macro Definition Documentation
#define MAX_BANNER_LEN 256
Definition at line 347 of file app-layer-ssh.c.
Function Documentation
void RegisterSSHParsers (void)
Function to register the SSH protocol parsers and other functions.
Definition at line 517 of file app-layer-ssh.c.
References ALPROTO_SSH, AppLayerParserConfParserEnabled(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), SSHParserRegisterTests(), STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().
void SSHParserRegisterTests (void)
Definition at line 2578 of file app-layer-ssh.c.
Referenced by RegisterSSHParsers().