suricata: src/app-layer-dcerpc.c File Reference
app-layer-dcerpc.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "debug.h"
#include "decode.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "util-debug.h"
#include "flow-util.h"
#include "detect-engine-state.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer.h"
#include "util-spm.h"
#include "util-unittest.h"
#include "app-layer-dcerpc.h"
Enumerations
enum {
DCERPC_FIELD_NONE = 0, DCERPC_PARSE_DCERPC_HEADER, DCERPC_PARSE_DCERPC_BIND, DCERPC_PARSE_DCERPC_BIND_ACK,
DCERPC_PARSE_DCERPC_REQUEST, DCERPC_FIELD_MAX
}
Functions
void hexdump (const void *buf, size_t len)
void printUUID (char *type, DCERPCUuidEntry *uuid)
printUUID function used to print UUID, Major and Minor Version Number and if it was Accepted or Rejected in the BIND_ACK.
int32_t DCERPCParser (DCERPC *dcerpc, uint8_t *input, uint32_t input_len)
void RegisterDCERPCParsers (void)
void DCERPCParserRegisterTests (void)
Detailed Description
Author
Kirby Kuehl kkueh.nosp@m.l@gm.nosp@m.ail.c.nosp@m.om
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file app-layer-dcerpc.c.
Enumeration Type Documentation
anonymous enum
Enumerator
DCERPC_FIELD_NONE
DCERPC_PARSE_DCERPC_HEADER
DCERPC_PARSE_DCERPC_BIND
DCERPC_PARSE_DCERPC_BIND_ACK
DCERPC_PARSE_DCERPC_REQUEST
DCERPC_FIELD_MAX
Definition at line 70 of file app-layer-dcerpc.c.
Function Documentation
int32_t DCERPCParser (DCERPC * dcerpc, uint8_t * input, uint32_t input_len)
Todo:
Currently the parser is very generic. Enable target based reassembly.
Disable reiniting tailq for mid and last bind/alter_context pdus.
Use a PM to search for subsequent 05 00 when we see an inconsistent pdu. This should be done for each platform based on how it handles a condition where it has receives a segment with 2 pdus, while the first pdu in the segment is corrupt.
Definition at line 1476 of file app-layer-dcerpc.c.
References ALTER_CONTEXT, ALTER_CONTEXT_RESP, DCERPCHdr_::auth_length, BIND, BIND_ACK, DCERPC_::bytesprocessed, DCERPCHdr_::call_id, DCERPCBindBindAck_::ctxbytesprocessed, DCERPC_HDR_LEN, DCERPC_::dcerpcbindbindack, DCERPC_::dcerpchdr, DCERPC_::dcerpcrequest, DCERPC_::dcerpcresponse, DCERPCHdr_::frag_length, DCERPCBindBindAck_::numctxitems, DCERPCBindBindAck_::numctxitemsleft, DCERPCRequest_::opnum, DCERPCHdr_::packed_drep, DCERPC_::pad, DCERPC_::padleft, DCERPC_::pdu_fragged, PFC_FIRST_FRAG, DCERPCHdr_::pfc_flags, REQUEST, RESPONSE, DCERPCHdr_::rpc_vers, DCERPCHdr_::rpc_vers_minor, SCEnter, SCLogDebug, SCReturnInt, DCERPCBindBindAck_::secondaryaddrlen, DCERPCRequest_::stub_data_fresh, DCERPCResponse_::stub_data_fresh, DCERPC_::transaction_id, and DCERPCHdr_::type.
void DCERPCParserRegisterTests (void)
Definition at line 6386 of file app-layer-dcerpc.c.
Referenced by RegisterDCERPCParsers().
void hexdump (const void * buf, size_t len)
Definition at line 81 of file app-layer-dcerpc.c.
References len, and strlcat().
void printUUID (char * type, DCERPCUuidEntry * uuid)
printUUID function used to print UUID, Major and Minor Version Number and if it was Accepted or Rejected in the BIND_ACK.
Definition at line 144 of file app-layer-dcerpc.c.
References DCERPCUuidEntry_::ctxid, DCERPCUuidEntry_::result, DCERPCUuidEntry_::uuid, DCERPCUuidEntry_::version, and DCERPCUuidEntry_::versionminor.
void RegisterDCERPCParsers (void)
Definition at line 2018 of file app-layer-dcerpc.c.
References ALPROTO_DCERPC, AppLayerParserConfParserEnabled(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), DCERPCParserRegisterTests(), SCLogInfo, STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().