suricata: src/app-layer-ssh.h File Reference
app-layer-ssh.h File Reference
Data Structures
struct SshHeader_
struct SshState_
Macros
#define SSH_FLAG_VERSION_PARSED 0x01
#define SSH_FLAG_PARSER_DONE 0x02
#define SSH_FLAG_STATE_LOGGED 0x04
#define SSH_FLAG_STATE_LOGGED_LUA 0x08
#define SSH_MSG_NEWKEYS 21
Typedefs
typedef struct SshHeader_ SshHeader
typedef struct SshState_ SshState
Functions
void RegisterSSHParsers (void)
Function to register the SSH protocol parsers and other functions.
void SSHParserRegisterTests (void)
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file app-layer-ssh.h.
Macro Definition Documentation
#define SSH_FLAG_PARSER_DONE 0x02
Definition at line 33 of file app-layer-ssh.h.
#define SSH_FLAG_STATE_LOGGED 0x04
Definition at line 35 of file app-layer-ssh.h.
#define SSH_FLAG_STATE_LOGGED_LUA 0x08
Definition at line 37 of file app-layer-ssh.h.
#define SSH_FLAG_VERSION_PARSED 0x01
Definition at line 29 of file app-layer-ssh.h.
Referenced by DetectSshSoftwareVersionMatch(), and DetectSshVersionMatch().
#define SSH_MSG_NEWKEYS 21
Definition at line 40 of file app-layer-ssh.h.
Typedef Documentation
typedef struct SshHeader_ SshHeader
From SSH-TRANSP rfc
SSH Bunary packet structure: uint32 packet_length byte padding_length byte[n1] payload; n1 = packet_length - padding_length - 1 byte[n2] random padding; n2 = padding_length byte[m] mac (Message Authentication Code - MAC); m = mac_length
So we are going to do a header struct to store the lenghts and msg_code (inside payload, if any)
typedef struct SshState_ SshState
structure to store the SSH state values
Function Documentation
void RegisterSSHParsers (void)
Function to register the SSH protocol parsers and other functions.
Definition at line 517 of file app-layer-ssh.c.
References ALPROTO_SSH, AppLayerParserConfParserEnabled(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), SSHParserRegisterTests(), STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().
void SSHParserRegisterTests (void)
Definition at line 2578 of file app-layer-ssh.c.
Referenced by RegisterSSHParsers().