suricata: src/app-layer-dcerpc.h File Reference
app-layer-dcerpc.h File Reference
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer-dcerpc-common.h"
#include "flow.h"
#include "queue.h"
#include "util-byte.h"
Data Structures
struct DCERPCState_
Typedefs
typedef struct DCERPCState_ DCERPCState
Functions
void RegisterDCERPCParsers (void)
void DCERPCParserTests (void)
void DCERPCParserRegisterTests (void)
Detailed Description
Author
Kirby Kuehl kkueh.nosp@m.l@gm.nosp@m.ail.c.nosp@m.om
Definition in file app-layer-dcerpc.h.
Typedef Documentation
typedef struct DCERPCState_ DCERPCState
Function Documentation
void DCERPCParserRegisterTests (void)
Definition at line 6386 of file app-layer-dcerpc.c.
void DCERPCParserTests (void)
void RegisterDCERPCParsers (void)
Definition at line 2018 of file app-layer-dcerpc.c.
References ALPROTO_DCERPC, AppLayerParserConfParserEnabled(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), DCERPCParserRegisterTests(), SCLogInfo, STREAM_TOCLIENT, and STREAM_TOSERVER.