suricata: src/app-layer-template.c File Reference
app-layer-template.c File Reference
#include "suricata-common.h"
#include "stream.h"
#include "conf.h"
#include "util-unittest.h"
#include "app-layer-detect-proto.h"
#include "app-layer-parser.h"
#include "app-layer-template.h"
Macros
#define TEMPLATE_DEFAULT_PORT "7"
#define TEMPLATE_MIN_FRAME_LEN 1
Enumerations
enum { TEMPLATE_DECODER_EVENT_EMPTY_MESSAGE }
Functions
void RegisterTemplateParsers (void)
void TemplateParserRegisterTests (void)
Variables
SCEnumCharMap template_decoder_event_table []
Macro Definition Documentation
#define TEMPLATE_DEFAULT_PORT "7"
Definition at line 39 of file app-layer-template.c.
Referenced by RegisterTemplateParsers().
#define TEMPLATE_MIN_FRAME_LEN 1
Definition at line 43 of file app-layer-template.c.
Referenced by RegisterTemplateParsers().
Enumeration Type Documentation
anonymous enum
Enumerator
TEMPLATE_DECODER_EVENT_EMPTY_MESSAGE
Definition at line 55 of file app-layer-template.c.
Function Documentation
void RegisterTemplateParsers (void)
Definition at line 428 of file app-layer-template.c.
References ALPROTO_TEMPLATE, AppLayerParserConfParserEnabled(), AppLayerParserRegisterDetectStateFuncs(), AppLayerParserRegisterGetEventInfo(), AppLayerParserRegisterGetEventsFunc(), AppLayerParserRegisterGetStateProgressCompletionStatus(), AppLayerParserRegisterGetStateProgressFunc(), AppLayerParserRegisterGetTx(), AppLayerParserRegisterGetTxCnt(), AppLayerParserRegisterHasEventsFunc(), AppLayerParserRegisterParser(), AppLayerParserRegisterStateFuncs(), AppLayerParserRegisterTxFreeFunc(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectPPParseConfPorts(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), ConfGetNode(), RunmodeIsUnittests(), SCLogNotice, STREAM_TOCLIENT, STREAM_TOSERVER, TEMPLATE_DEFAULT_PORT, TEMPLATE_MIN_FRAME_LEN, and TemplateParserRegisterTests().
Referenced by AppLayerParserRegisterProtocolParsers().
void TemplateParserRegisterTests (void)
Definition at line 537 of file app-layer-template.c.
Referenced by RegisterTemplateParsers().
Variable Documentation
SCEnumCharMap template_decoder_event_table[]
Initial value:
= {
    {"EMPTY_MESSAGE", TEMPLATE_DECODER_EVENT_EMPTY_MESSAGE},
}
Definition at line 59 of file app-layer-template.c.