suricata: src/app-layer-smtp.h File Reference
app-layer-smtp.h File Reference
#include "decode-events.h"
#include "util-decode-mime.h"
#include "queue.h"
Data Structures
struct SMTPString_
struct SMTPTransaction_
struct SMTPConfig
struct SMTPState_
Typedefs
typedef struct SMTPString_ SMTPString
typedef struct SMTPTransaction_ SMTPTransaction
typedef struct SMTPConfig SMTPConfig
typedef struct SMTPState_ SMTPState
Enumerations
enum {
SMTP_DECODER_EVENT_INVALID_REPLY, SMTP_DECODER_EVENT_UNABLE_TO_MATCH_REPLY_WITH_REQUEST, SMTP_DECODER_EVENT_MAX_COMMAND_LINE_LEN_EXCEEDED, SMTP_DECODER_EVENT_MAX_REPLY_LINE_LEN_EXCEEDED,
SMTP_DECODER_EVENT_INVALID_PIPELINED_SEQUENCE, SMTP_DECODER_EVENT_BDAT_CHUNK_LEN_EXCEEDED, SMTP_DECODER_EVENT_NO_SERVER_WELCOME_MESSAGE, SMTP_DECODER_EVENT_TLS_REJECTED,
SMTP_DECODER_EVENT_DATA_COMMAND_REJECTED, SMTP_DECODER_EVENT_MIME_PARSE_FAILED, SMTP_DECODER_EVENT_MIME_MALFORMED_MSG, SMTP_DECODER_EVENT_MIME_INVALID_BASE64,
SMTP_DECODER_EVENT_MIME_INVALID_QP, SMTP_DECODER_EVENT_MIME_LONG_LINE, SMTP_DECODER_EVENT_MIME_LONG_ENC_LINE, SMTP_DECODER_EVENT_MIME_LONG_HEADER_NAME,
SMTP_DECODER_EVENT_MIME_LONG_HEADER_VALUE, SMTP_DECODER_EVENT_MIME_BOUNDARY_TOO_LONG
}
Functions
int SMTPProcessDataChunk (const uint8_t *chunk, uint32_t len, MimeDecParseState *state)
void * SMTPStateAlloc (void)
void RegisterSMTPParsers (void)
Register the SMTP Protocol parser.
void SMTPParserRegisterTests (void)
Variables
SMTPConfig smtp_config
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file app-layer-smtp.h.
Typedef Documentation
typedef struct SMTPConfig SMTPConfig
typedef struct SMTPState_ SMTPState
typedef struct SMTPString_ SMTPString
typedef struct SMTPTransaction_ SMTPTransaction
Enumeration Type Documentation
anonymous enum
Enumerator
SMTP_DECODER_EVENT_INVALID_REPLY
SMTP_DECODER_EVENT_UNABLE_TO_MATCH_REPLY_WITH_REQUEST
SMTP_DECODER_EVENT_MAX_COMMAND_LINE_LEN_EXCEEDED
SMTP_DECODER_EVENT_MAX_REPLY_LINE_LEN_EXCEEDED
SMTP_DECODER_EVENT_INVALID_PIPELINED_SEQUENCE
SMTP_DECODER_EVENT_BDAT_CHUNK_LEN_EXCEEDED
SMTP_DECODER_EVENT_NO_SERVER_WELCOME_MESSAGE
SMTP_DECODER_EVENT_TLS_REJECTED
SMTP_DECODER_EVENT_DATA_COMMAND_REJECTED
SMTP_DECODER_EVENT_MIME_PARSE_FAILED
SMTP_DECODER_EVENT_MIME_MALFORMED_MSG
SMTP_DECODER_EVENT_MIME_INVALID_BASE64
SMTP_DECODER_EVENT_MIME_INVALID_QP
SMTP_DECODER_EVENT_MIME_LONG_LINE
SMTP_DECODER_EVENT_MIME_LONG_ENC_LINE
SMTP_DECODER_EVENT_MIME_LONG_HEADER_NAME
SMTP_DECODER_EVENT_MIME_LONG_HEADER_VALUE
SMTP_DECODER_EVENT_MIME_BOUNDARY_TOO_LONG
Definition at line 31 of file app-layer-smtp.h.
Function Documentation
void RegisterSMTPParsers (void)
Register the SMTP Protocol parser.
Definition at line 1528 of file app-layer-smtp.c.
References ALPROTO_SMTP, AppLayerParserConfParserEnabled(), AppLayerParserRegisterDetectStateFuncs(), AppLayerParserRegisterGetEventInfo(), AppLayerParserRegisterGetEventsFunc(), AppLayerParserRegisterGetFilesFunc(), AppLayerParserRegisterGetStateProgressCompletionStatus(), AppLayerParserRegisterGetStateProgressFunc(), AppLayerParserRegisterGetTx(), AppLayerParserRegisterGetTxCnt(), AppLayerParserRegisterLocalStorageFunc(), AppLayerParserRegisterParser(), AppLayerParserRegisterStateFuncs(), AppLayerParserRegisterTruncateFunc(), AppLayerParserRegisterTxFreeFunc(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), SCLogInfo, SMTPParserRegisterTests(), SMTPStateAlloc(), SMTPStateGetEventInfo(), STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().
void SMTPParserRegisterTests (void)
Definition at line 4995 of file app-layer-smtp.c.
Referenced by RegisterSMTPParsers().
int SMTPProcessDataChunk (const uint8_t * chunk, uint32_t len, MimeDecParseState * state)
Definition at line 338 of file app-layer-smtp.c.
References Flow_::alstate, MimeDecParseState::body_begin, MimeDecParseState::body_end, MimeDecEntity::ctnt_flags, CTNT_IS_ATTACHMENT, MimeDecStackNode::data, MimeDecParseState::data, FILE_NOMAGIC, FILE_NOMD5, FILE_NOSTORE, FILE_STATE_OPENED, FILE_STORE, FileAppendData(), FileCloseFile(), FileContainerAlloc(), MimeDecEntity::filename, MimeDecEntity::filename_len, FileOpenFile(), FilePrune(), flags, Flow_::flags, FLOW_FILE_NO_MAGIC_TS, FLOW_FILE_NO_MD5_TS, FLOW_FILE_NO_STORE_TS, MIME_DEC_ERR_DATA, MIME_DEC_ERR_MEM, MIME_DEC_OK, SC_ERR_MEM_ALLOC, SCLogDebug, SCLogDebugEnabled(), SCLogError, SCReturnInt, MimeDecParseState::stack, and MimeDecStack::top.
void* SMTPStateAlloc (void)
Definition at line 1221 of file app-layer-smtp.c.
References SMTPState_::cmds, SMTPState_::cmds_buffer_len, SCFree, SCMalloc, SMTP_COMMAND_BUFFER_STEPS, TAILQ_INIT, and unlikely.
Referenced by RegisterSMTPParsers().
Variable Documentation
SMTPConfig smtp_config
Definition at line 223 of file app-layer-smtp.c.