suricata: src/app-layer.c File Reference
app-layer.c File Reference
#include "suricata-common.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-protos.h"
#include "app-layer-detect-proto.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp-private.h"
#include "stream-tcp-inline.h"
#include "flow.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-print.h"
#include "util-profiling.h"
#include "util-validate.h"
#include "decode-events.h"
#include "app-layer-htp-mem.h"
#include "app-layer-dns-common.h"
Data Structures
struct AppLayerThreadCtx_
This is for the app layer in general and it contains per thread context relevant to both the alpd and alp.
Functions
int AppLayerHandleTCPData (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, Packet *p, Flow *f, TcpSession *ssn, TcpStream *stream, uint8_t *data, uint32_t data_len, uint8_t flags)
Handles reassembled tcp stream.
int AppLayerHandleUdp (ThreadVars *tv, AppLayerThreadCtx *tctx, Packet *p, Flow *f)
Handle a app layer UDP message.
AppProto AppLayerGetProtoByName (char *alproto_name)
Given a protocol string, returns the corresponding internal protocol id.
char * AppLayerGetProtoName (AppProto alproto)
Given the internal protocol id, returns a string representation of the protocol.
void AppLayerListSupportedProtocols (void)
int AppLayerSetup (void)
Setup the app layer.
int AppLayerDeSetup (void)
De initializes the app layer.
AppLayerThreadCtx * AppLayerGetCtxThread (ThreadVars *tv)
Creates a new app layer thread context.
void AppLayerDestroyCtxThread (AppLayerThreadCtx *app_tctx)
Destroys the context created by AppLayeGetCtxThread().
void AppLayerProfilingResetInternal (AppLayerThreadCtx *app_tctx)
void AppLayerProfilingStoreInternal (AppLayerThreadCtx *app_tctx, Packet *p)
void AppLayerRegisterGlobalCounters (void)
HACK to work around our broken unix manager (re)init loop.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Generic App-layer functions
Definition in file app-layer.c.
Function Documentation
int AppLayerDeSetup (void)
De initializes the app layer.
Includes de initializing protocol detection and the protocol parser.
Definition at line 585 of file app-layer.c.
References AppLayerParserDeSetup(), AppLayerProtoDetectDeSetup(), SCEnter, and SCReturnInt.
Referenced by main().
void AppLayerDestroyCtxThread (AppLayerThreadCtx * tctx)
Destroys the context created by AppLayeGetCtxThread().
Parameters
tctx Pointer to the thread context to destroy.
Definition at line 617 of file app-layer.c.
References AppLayerThreadCtx_::alp_tctx, AppLayerThreadCtx_::alpd_tctx, AppLayerParserThreadCtxFree(), AppLayerProtoDetectDestroyCtxThread(), SCEnter, SCFree, and SCReturn.
Referenced by AppLayerGetCtxThread(), DecodeThreadVarsFree(), and StreamTcpReassembleFreeThreadCtx().
AppLayerThreadCtx* AppLayerGetCtxThread (ThreadVars * tv)
Creates a new app layer thread context.
Return values
Pointer to the newly create thread context, on success; NULL, on failure.
Definition at line 595 of file app-layer.c.
References AppLayerThreadCtx_::alp_tctx, AppLayerThreadCtx_::alpd_tctx, AppLayerDestroyCtxThread(), AppLayerParserThreadCtxAlloc(), AppLayerProtoDetectGetCtxThread(), SCEnter, SCMalloc, and SCReturnPtr.
Referenced by DecodeThreadVarsAlloc(), and StreamTcpReassembleInitThreadCtx().
AppProto AppLayerGetProtoByName (char * alproto_name)
Given a protocol string, returns the corresponding internal protocol id.
Parameters
The internal protocol id.
Definition at line 538 of file app-layer.c.
References AppLayerProtoDetectGetProtoByName(), SCEnter, and SCReturnCT.
Referenced by SigParseProto().
char* AppLayerGetProtoName (AppProto alproto)
Given the internal protocol id, returns a string representation of the protocol.
Parameters
alproto The internal protocol id.
Return values
String representation of the protocol.
Definition at line 545 of file app-layer.c.
References AppLayerProtoDetectGetProtoName(), SCEnter, and SCReturnCT.
Referenced by AppLayerListSupportedProtocols(), AppLayerParserParse(), and SigTableList().
int AppLayerHandleTCPData (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, Packet * p, Flow * f, TcpSession * ssn, TcpStream * stream, uint8_t * data, uint32_t data_len, uint8_t flags)
Handles reassembled tcp stream.
Definition at line 83 of file app-layer.c.
References AppLayerThreadCtx_::alp_tctx, AppLayerThreadCtx_::alpd_tctx, Flow_::alproto, Flow_::alproto_tc, Flow_::alproto_ts, ALPROTO_UNKNOWN, APP_LAYER_DATA_ALREADY_SENT_TO_APP_LAYER, Packet_::app_layer_events, TcpReassemblyThreadCtx_::app_tctx, APPLAYER_DETECT_PROTOCOL_ONLY_ONE_DIRECTION, APPLAYER_MISMATCH_PROTOCOL_BOTH_DIRECTIONS, APPLAYER_PROTO_DETECTION_SKIPPED, APPLAYER_WRONG_DIRECTION_FIRST_DATA, AppLayerDecoderEventsSetEventRaw(), AppLayerParserGetFirstDataDir(), AppLayerParserParse(), AppLayerProtoDetectGetProto(), BUG_ON, TcpSession_::client, Flow_::data_al_so_far, TcpSession_::data_first_seen_dir, DEBUG_ASSERT_FLOW_LOCKED, TcpStream_::flags, TcpSession_::flags, FLOW_IS_PM_DONE, FLOW_IS_PP_DONE, FLOW_PKT_TOCLIENT, FLOW_PKT_TOSERVER, FLOW_RESET_PM_DONE, FLOW_RESET_PP_DONE, FlowCleanupAppLayer(), Packet_::flowflags, TcpStream_::isn, TcpStream_::last_ack, PACKET_PROFILING_APP_END, PACKET_PROFILING_APP_PD_END, PACKET_PROFILING_APP_PD_START, PACKET_PROFILING_APP_START, PrintRawDataFp(), Flow_::proto, SCEnter, SCLogDebug, SCReturnInt, TcpSession_::server, STREAM_GAP, STREAM_START, STREAM_TOCLIENT, STREAM_TOSERVER, STREAMTCP_FLAG_APP_LAYER_DISABLED, STREAMTCP_FLAG_MIDSTREAM, STREAMTCP_FLAG_MIDSTREAM_SYNACK, STREAMTCP_STREAM_FLAG_GAP, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, StreamTcpInlineMode(), StreamTcpReassembleAppLayer(), StreamTcpResetStreamFlagAppProtoDetectionCompleted, StreamTcpSetSessionNoReassemblyFlag(), and StreamTcpSetStreamFlagAppProtoDetectionCompleted.
Referenced by DoHandleGap(), and StreamTcpReassembleAppLayer().
int AppLayerHandleUdp (ThreadVars * tv, AppLayerThreadCtx * tctx, Packet * p, Flow * f)
Handle a app layer UDP message.
Handles an udp chunk.
If the protocol is yet unknown, the proto detection code is run first.
Parameters
dp_ctx Thread app layer detect context
f unlocked flow
p UDP packet
Return values
0 ok
-1 error
Definition at line 470 of file app-layer.c.
References AppLayerThreadCtx_::alp_tctx, AppLayerThreadCtx_::alpd_tctx, Flow_::alproto, ALPROTO_UNKNOWN, AppLayerParserParse(), AppLayerProtoDetectGetProto(), flags, Flow_::flags, FLOW_ALPROTO_DETECT_DONE, FLOW_PKT_TOSERVER, Packet_::flowflags, FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, PACKET_PROFILING_APP_END, PACKET_PROFILING_APP_PD_END, PACKET_PROFILING_APP_PD_START, PACKET_PROFILING_APP_START, PACKET_PROFILING_APP_STORE, Packet_::payload, Packet_::payload_len, SCEnter, SCLogDebug, SCReturnInt, STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by DecodeUDP().
void AppLayerListSupportedProtocols (void)
Definition at line 552 of file app-layer.c.
References ALPROTO_MAX, AppLayerGetProtoName(), AppLayerProtoDetectSupportedAppProtocols(), SCEnter, and SCReturn.
Referenced by ListAppLayerProtocols().
void AppLayerProfilingResetInternal (AppLayerThreadCtx * app_tctx)
Definition at line 633 of file app-layer.c.
References PACKET_PROFILING_APP_RESET.
void AppLayerProfilingStoreInternal (AppLayerThreadCtx * app_tctx, Packet * p)
Definition at line 638 of file app-layer.c.
References PACKET_PROFILING_APP_STORE.
void AppLayerRegisterGlobalCounters (void)
HACK to work around our broken unix manager (re)init loop.
Definition at line 645 of file app-layer.c.
References DNSMemcapGetMemcapGlobalCounter(), DNSMemcapGetMemcapStateCounter(), DNSMemcapGetMemuseCounter(), HTPMemcapGlobalCounter(), HTPMemuseGlobalCounter(), and StatsRegisterGlobalCounter().
Referenced by main().
int AppLayerSetup (void)
Setup the app layer.
   Includes protocol detection setup and the protocol parser setup.
Return values
0 On success.
-1 On failure.
Definition at line 572 of file app-layer.c.
References AppLayerParserRegisterProtocolParsers(), AppLayerParserSetup(), AppLayerProtoDetectPrepareState(), AppLayerProtoDetectSetup(), SCEnter, and SCReturnInt.
Referenced by ListAppLayerProtocols(), ListKeywords(), and RunUnittests().