suricata: src/app-layer-htp-mem.c File Reference
app-layer-htp-mem.c File Reference
HTTP layer support
#include "suricata-common.h"
#include "suricata.h"
#include "conf.h"
#include "util-mem.h"
#include "util-misc.h"
#include "app-layer-htp-mem.h"
uint64_t htp_config_memcap = 0
SC_ATOMIC_DECLARE (uint64_t, htp_memuse)
SC_ATOMIC_DECLARE (uint64_t, htp_memcap)
void HTPParseMemcap ()
void HTPIncrMemuse (uint64_t size)
void HTPDecrMemuse (uint64_t size)
uint64_t HTPMemuseGlobalCounter (void)
uint64_t HTPMemcapGlobalCounter (void)
int HTPCheckMemcap (uint64_t size)
Check if alloc'ing "size" would mean we're over memcap.
void * HTPMalloc (size_t size)
void * HTPRealloc (void *ptr, size_t orig_size, size_t size)
void HTPFree (void *ptr, size_t size)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
This file provides a memory handling for the HTTP protocol support.
Definition in file app-layer-htp-mem.c.
Function Documentation
int HTPCheckMemcap (uint64_t size)
Check if alloc'ing "size" would mean we're over memcap.
Return values
1 if in bounds
0 if not in bounds
Definition at line 99 of file app-layer-htp-mem.c.
References htp_config_memcap, SC_ATOMIC_ADD, and SC_ATOMIC_GET.
Referenced by HTPMalloc(), and HTPRealloc().
void HTPDecrMemuse (uint64_t size)
Definition at line 75 of file app-layer-htp-mem.c.
References SC_ATOMIC_SUB.
Referenced by HTPFree().
void HTPFree (void * ptr, size_t size)
Definition at line 140 of file app-layer-htp-mem.c.
References HTPDecrMemuse(), and SCFree.
Referenced by DetectEngineThreadCtxFree(), HtpBodyAppendChunk(), HtpBodyFree(), HtpBodyPrune(), HTPCallbackRequestBodyData(), HtpRequestBodyHandleMultipart(), and HTPStateFree().
void HTPIncrMemuse (uint64_t size)
Definition at line 69 of file app-layer-htp-mem.c.
References SC_ATOMIC_ADD.
Referenced by HTPMalloc(), and HTPRealloc().
void* HTPMalloc (size_t size)
Definition at line 107 of file app-layer-htp-mem.c.
References HTPCheckMemcap(), HTPIncrMemuse(), SCMalloc, and unlikely.
Referenced by HtpBodyAppendChunk(), HTPCallbackRequestBodyData(), and HTPCallbackResponseBodyData().
uint64_t HTPMemcapGlobalCounter (void)
Definition at line 87 of file app-layer-htp-mem.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
uint64_t HTPMemuseGlobalCounter (void)
Definition at line 81 of file app-layer-htp-mem.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
void HTPParseMemcap ()
set config values for memcap, prealloc and hash_size
Definition at line 46 of file app-layer-htp-mem.c.
References ConfGet(), htp_config_memcap, ParseSizeStringU64(), SC_ATOMIC_INIT, SC_ERR_SIZE_PARSE, SCLogError, and SCLogInfo.
Referenced by HTPConfigure().
void* HTPRealloc (void * ptr, size_t orig_size, size_t size)
Definition at line 124 of file app-layer-htp-mem.c.
References HTPCheckMemcap(), HTPIncrMemuse(), and SCRealloc.
SC_ATOMIC_DECLARE (uint64_t , htp_memuse)
SC_ATOMIC_DECLARE (uint64_t , htp_memcap)
Variable Documentation
uint64_t htp_config_memcap = 0
Definition at line 41 of file app-layer-htp-mem.c.
Referenced by HTPCheckMemcap(), and HTPParseMemcap().