suricata: src/app-layer-smb.c File Reference
app-layer-smb.c File Reference
SMBv1 parser/decoder.
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "util-debug.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer.h"
#include "app-layer-detect-proto.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "util-spm.h"
#include "util-unittest.h"
#include "util-memcmp.h"
#include "app-layer-smb.h"
Macros
#define SMB_PROBING_PARSER_MIN_DEPTH 8
Enumerations
enum {
SMB_FIELD_NONE = 0, SMB_PARSE_NBSS_HEADER, SMB_PARSE_SMB_HEADER, SMB_PARSE_GET_WORDCOUNT,
SMB_PARSE_WORDCOUNT, SMB_PARSE_GET_BYTECOUNT, SMB_PARSE_BYTECOUNT, SMB_FIELD_MAX
}
Functions
int isAndX (SMBState *smb_state)
determines if the SMB command is an ANDX command
void RegisterSMBParsers (void)
void SMBParserRegisterTests (void)
Detailed Description
SMBv1 parser/decoder.
Author
Kirby Kuehl kkueh.nosp@m.l@gm.nosp@m.ail.c.nosp@m.om
Definition in file app-layer-smb.c.
Macro Definition Documentation
#define SMB_PROBING_PARSER_MIN_DEPTH 8
Definition at line 1469 of file app-layer-smb.c.
Referenced by RegisterSMBParsers().
Enumeration Type Documentation
anonymous enum
Enumerator
SMB_FIELD_NONE
SMB_PARSE_NBSS_HEADER
SMB_PARSE_SMB_HEADER
SMB_PARSE_GET_WORDCOUNT
SMB_PARSE_WORDCOUNT
SMB_PARSE_GET_BYTECOUNT
SMB_PARSE_BYTECOUNT
SMB_FIELD_MAX
Definition at line 52 of file app-layer-smb.c.
Function Documentation
int isAndX (SMBState * smb_state)
determines if the SMB command is an ANDX command
Return values
1 if smb command is an AndX command
0 if smb command is not an AndX command
Definition at line 1400 of file app-layer-smb.c.
References SMBState_::andx, SMBAndX_::andxbytesprocessed, SMBHdr_::command, SCEnter, SCReturnInt, SMBState_::smb, SMB_COM_LOCKING_ANDX, SMB_COM_LOGOFF_ANDX, SMB_COM_NT_CREATE_ANDX, SMB_COM_OPEN_ANDX, SMB_COM_READ_ANDX, SMB_COM_SESSION_SETUP_ANDX, SMB_COM_TREE_CONNECT_ANDX, SMB_COM_WRITE_ANDX, and SMB_NO_SECONDARY_ANDX_COMMAND.
void RegisterSMBParsers (void)
Definition at line 1529 of file app-layer-smb.c.
References ALPROTO_SMB, AppLayerParserConfParserEnabled(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectPPParseConfPorts(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), RunmodeIsUnittests(), SCLogInfo, SMB_PROBING_PARSER_MIN_DEPTH, SMBParserRegisterTests(), STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().
void SMBParserRegisterTests (void)
Definition at line 2702 of file app-layer-smb.c.
Referenced by RegisterSMBParsers().