suricata: src/app-layer-events.h File Reference
app-layer-events.h File Reference
#include "decode.h"
Data Structures
struct AppLayerDecoderEvents_
Data structure to store app layer decoder events.
Typedefs
typedef enum AppLayerEventType_ AppLayerEventType
Enumerations
enum { APPLAYER_MISMATCH_PROTOCOL_BOTH_DIRECTIONS, APPLAYER_WRONG_DIRECTION_FIRST_DATA, APPLAYER_DETECT_PROTOCOL_ONLY_ONE_DIRECTION, APPLAYER_PROTO_DETECTION_SKIPPED }
enum AppLayerEventType_ { APP_LAYER_EVENT_TYPE_GENERAL = 1, APP_LAYER_EVENT_TYPE_TRANSACTION, APP_LAYER_EVENT_TYPE_PACKET }
Functions
int AppLayerGetPktEventInfo (const char *event_name, int *event_id)
void AppLayerDecoderEventsSetEventRaw (AppLayerDecoderEvents **sevents, uint8_t event)
Set an app layer decoder event.
void AppLayerDecoderEventsSetEvent (Flow *f, uint8_t event)
Set an app layer decoder event.
void AppLayerDecoderEventsResetEvents (AppLayerDecoderEvents *events)
void AppLayerDecoderEventsFreeEvents (AppLayerDecoderEvents **events)
Variables
struct AppLayerDecoderEvents_ __attribute__
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file app-layer-events.h.
Typedef Documentation
typedef enum AppLayerEventType_ AppLayerEventType
Enumeration Type Documentation
anonymous enum
Enumerator
APPLAYER_MISMATCH_PROTOCOL_BOTH_DIRECTIONS
APPLAYER_WRONG_DIRECTION_FIRST_DATA
APPLAYER_DETECT_PROTOCOL_ONLY_ONE_DIRECTION
APPLAYER_PROTO_DETECTION_SKIPPED
Definition at line 44 of file app-layer-events.h.
enum AppLayerEventType_
Enumerator
APP_LAYER_EVENT_TYPE_GENERAL
APP_LAYER_EVENT_TYPE_TRANSACTION
APP_LAYER_EVENT_TYPE_PACKET
Definition at line 52 of file app-layer-events.h.
Function Documentation
void AppLayerDecoderEventsFreeEvents (AppLayerDecoderEvents ** events)
Definition at line 128 of file app-layer-events.c.
void AppLayerDecoderEventsResetEvents (AppLayerDecoderEvents * events)
Definition at line 121 of file app-layer-events.c.
void AppLayerDecoderEventsSetEvent (Flow * f, uint8_t event)
Set an app layer decoder event.
Parameters
f Pointer to a flow containing DecoderEvents pointer head. If the head points to a DecoderEvents instance, a new instance would be created and the pointer head would would be updated with this new instance
event The event to be stored.
Definition at line 112 of file app-layer-events.c.
References Flow_::alparser, AppLayerDecoderEventsSetEventRaw(), AppLayerParserGetDecoderEvents(), and AppLayerParserSetDecoderEvents().
Referenced by DecodeTLSHandshakeServerCertificate().
void AppLayerDecoderEventsSetEventRaw (AppLayerDecoderEvents ** sevents, uint8_t event)
Set an app layer decoder event.
Parameters
sevents Pointer to a AppLayerDecoderEvents pointer. If *sevents is NULL memory will be allocated.
event The event to be stored.
Definition at line 69 of file app-layer-events.c.
References DECODER_EVENTS_BUFFER_STEPS, SCMalloc, and SCRealloc.
Referenced by AppLayerDecoderEventsSetEvent(), AppLayerHandleTCPData(), DNSSetEvent(), HTPSetEvent(), ModbusSetEvent(), SMTPSetEvent(), and StreamTcpReassembleHandleSegmentHandleData().
int AppLayerGetPktEventInfo (const char * event_name, int * event_id)
Definition at line 47 of file app-layer-events.c.
References SC_ERR_INVALID_ENUM_MAP, SCLogError, and SCMapEnumNameToValue().
Variable Documentation
struct AppLayerDecoderEvents_ __attribute__