suricata: src/app-layer-tls-handshake.c File Reference
app-layer-tls-handshake.c File Reference
Decode TLS Handshake messages, as described in RFC2246.
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "app-layer-parser.h"
#include "decode-events.h"
#include "app-layer-ssl.h"
#include "app-layer-tls-handshake.h"
#include <stdint.h>
#include "util-decode-der.h"
#include "util-decode-der-get.h"
#include "util-crypt.h"
Macros
#define SSLV3_RECORD_LEN 5
Functions
int DecodeTLSHandshakeServerCertificate (SSLState *ssl_state, uint8_t *input, uint32_t input_len)
Detailed Description
Decode TLS Handshake messages, as described in RFC2246.
Author
Pierre Chifflier pierr.nosp@m.e.ch.nosp@m.iffli.nosp@m.er@s.nosp@m.si.go.nosp@m.uv.f.nosp@m.r
Definition in file app-layer-tls-handshake.c.
Macro Definition Documentation
#define SSLV3_RECORD_LEN 5
Definition at line 55 of file app-layer-tls-handshake.c.
Function Documentation
int DecodeTLSHandshakeServerCertificate (SSLState * ssl_state, uint8_t * input, uint32_t input_len)
Definition at line 88 of file app-layer-tls-handshake.c.
References AppLayerDecoderEventsSetEvent(), Asn1DerGetIssuerDN(), Asn1DerGetSubjectDN(), SSLStateConnp_::cert0_fingerprint, SSLStateConnp_::cert0_issuerdn, SSLStateConnp_::cert0_subject, SSLCertsChain_::cert_data, SSLStateConnp_::cert_input, SSLStateConnp_::cert_input_len, SSLCertsChain_::cert_len, ComputeSHA1(), DecodeDer(), DerFree(), SSLState_::f, next, ptxdump::out, SC_ERR_MEM_ALLOC, SCFree, SCLogWarning, SCMalloc, SCStrdup, SSLState_::server_connp, TAILQ_INSERT_TAIL, and TLS_DECODER_EVENT_INVALID_CERTIFICATE.