suricata: src/app-layer-dcerpc-udp.h File Reference
app-layer-dcerpc-udp.h File Reference
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer-dcerpc-common.h"
#include "flow.h"
#include "queue.h"
#include "util-byte.h"
Data Structures
struct DCERPCUDPState_
Typedefs
typedef struct DCERPCUDPState_ DCERPCUDPState
Functions
void RegisterDCERPCUDPParsers (void)
void DCERPCUDPParserTests (void)
void DCERPCUDPParserRegisterTests (void)
Typedef Documentation
typedef struct DCERPCUDPState_ DCERPCUDPState
Function Documentation
void DCERPCUDPParserRegisterTests (void)
Referenced by RegisterDCERPCUDPParsers().
void DCERPCUDPParserTests (void)
void RegisterDCERPCUDPParsers (void)
Definition at line 822 of file app-layer-dcerpc-udp.c.
References ALPROTO_DCERPC, AppLayerParserConfParserEnabled(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), DCERPCUDPParserRegisterTests(), SCLogInfo, STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().