suricata: src/app-layer-htp-body.c File Reference
app-layer-htp-body.c File Reference
#include "suricata.h"
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "util-radix-tree.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "util-spm.h"
#include "util-debug.h"
#include "app-layer-htp-file.h"
#include "util-time.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "flow-util.h"
#include "detect-engine.h"
#include "detect-engine-state.h"
#include "detect-parse.h"
#include "conf.h"
#include "util-memcmp.h"
Functions
int HtpBodyAppendChunk (HtpTxUserData *htud, HtpBody *body, uint8_t *data, uint32_t len)
Append a chunk of body to the HtpBody struct.
void HtpBodyPrint (HtpBody *body)
Print the information and chunks of a Body.
void HtpBodyFree (HtpBody *body)
Free the information held in the request body.
void HtpBodyPrune (HtpState *state, HtpBody *body, int direction)
Free request body chunks that are already fully parsed.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Brian Rectanus brect.nosp@m.anu@.nosp@m.gmail.nosp@m..com
This file provides a HTTP protocol support for the engine using HTP library.
Definition in file app-layer-htp-body.c.
Function Documentation
int HtpBodyAppendChunk (HtpTxUserData * htud, HtpBody * body, uint8_t * data, uint32_t len)
Append a chunk of body to the HtpBody struct.
Parameters
body pointer to the HtpBody holding the list
data pointer to the data of the chunk
len length of the chunk pointed by data
Return values
0 ok
-1 error
Definition at line 76 of file app-layer-htp-body.c.
References HtpBody_::content_len_so_far, HtpBodyChunk_::data, HtpBody_::first, HTPFree(), HTPMalloc(), HtpBody_::last, len, HtpBodyChunk_::len, HtpBodyChunk_::logged, HtpBodyChunk_::next, SCEnter, SCLogDebug, SCReturnInt, and HtpBodyChunk_::stream_offset.
Referenced by HTPCallbackRequestBodyData(), and HTPCallbackResponseBodyData().
void HtpBodyPrune (HtpState * state, HtpBody * body, int direction)
Free request body chunks that are already fully parsed.
Parameters
state htp_state, with reference to our config
body the body to prune
direction STREAM_TOSERVER (request), STREAM_TOCLIENT (response)
Return values
none
Definition at line 204 of file app-layer-htp-body.c.
References HtpBody_::body_inspected, HtpBody_::body_parsed, HtpState_::cfg, HtpBodyChunk_::data, HtpBody_::first, HTPFree(), HtpBody_::last, HtpBodyChunk_::len, HtpBodyChunk_::next, next, HTPCfgRec_::request_inspect_min_size, HTPCfgRec_::request_inspect_window, HTPCfgRec_::response_inspect_min_size, HTPCfgRec_::response_inspect_window, SCEnter, SCLogDebug, SCReturn, HtpBodyChunk_::stream_offset, and STREAM_TOSERVER.
Referenced by HTPCallbackRequestBodyData(), and HTPCallbackResponseBodyData().