suricata: src/app-layer-ftp.h File Reference
app-layer-ftp.h File Reference
Data Structures
struct FtpLineState_
struct FtpState_
Typedefs
typedef uint32_t FtpRequestCommandArgOfs
typedef uint16_t FtpResponseCode
typedef struct FtpLineState_ FtpLineState
typedef struct FtpState_ FtpState
Enumerations
enum FtpRequestCommand {
FTP_COMMAND_UNKNOWN = 0, FTP_COMMAND_ABOR, FTP_COMMAND_ACCT, FTP_COMMAND_ALLO,
FTP_COMMAND_APPE, FTP_COMMAND_CDUP, FTP_COMMAND_CHMOD, FTP_COMMAND_CWD,
FTP_COMMAND_DELE, FTP_COMMAND_HELP, FTP_COMMAND_IDLE, FTP_COMMAND_LIST,
FTP_COMMAND_MAIL, FTP_COMMAND_MDTM, FTP_COMMAND_MKD, FTP_COMMAND_MLFL,
FTP_COMMAND_MODE, FTP_COMMAND_MRCP, FTP_COMMAND_MRSQ, FTP_COMMAND_MSAM,
FTP_COMMAND_MSND, FTP_COMMAND_MSOM, FTP_COMMAND_NLST, FTP_COMMAND_NOOP,
FTP_COMMAND_PASS, FTP_COMMAND_PASV, FTP_COMMAND_PORT, FTP_COMMAND_PWD,
FTP_COMMAND_QUIT, FTP_COMMAND_REIN, FTP_COMMAND_REST, FTP_COMMAND_RETR,
FTP_COMMAND_RMD, FTP_COMMAND_RNFR, FTP_COMMAND_RNTO, FTP_COMMAND_SITE,
FTP_COMMAND_SIZE, FTP_COMMAND_SMNT, FTP_COMMAND_STAT, FTP_COMMAND_STOR,
FTP_COMMAND_STOU, FTP_COMMAND_STRU, FTP_COMMAND_SYST, FTP_COMMAND_TYPE,
FTP_COMMAND_UMASK, FTP_COMMAND_USER
}
enum {
FTP_FIELD_NONE = 0, FTP_FIELD_REQUEST_LINE, FTP_FIELD_REQUEST_COMMAND, FTP_FIELD_REQUEST_ARGS,
FTP_FIELD_RESPONSE_LINE, FTP_FIELD_REPONSE_CODE, FTP_FIELD_MAX
}
Functions
void RegisterFTPParsers (void)
void FTPParserRegisterTests (void)
void FTPAtExitPrintStats (void)
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file app-layer-ftp.h.
Typedef Documentation
typedef struct FtpLineState_ FtpLineState
used to hold the line state when we have fragmentation.
typedef uint32_t FtpRequestCommandArgOfs
Definition at line 76 of file app-layer-ftp.h.
typedef uint16_t FtpResponseCode
Definition at line 78 of file app-layer-ftp.h.
typedef struct FtpState_ FtpState
FTP State for app layer parser
Enumeration Type Documentation
anonymous enum
Enumerator
FTP_FIELD_NONE
FTP_FIELD_REQUEST_LINE
FTP_FIELD_REQUEST_COMMAND
FTP_FIELD_REQUEST_ARGS
FTP_FIELD_RESPONSE_LINE
FTP_FIELD_REPONSE_CODE
FTP_FIELD_MAX
Definition at line 80 of file app-layer-ftp.h.
enum FtpRequestCommand
Enumerator
FTP_COMMAND_UNKNOWN
FTP_COMMAND_ABOR
FTP_COMMAND_ACCT
FTP_COMMAND_ALLO
FTP_COMMAND_APPE
FTP_COMMAND_CDUP
FTP_COMMAND_CHMOD
FTP_COMMAND_CWD
FTP_COMMAND_DELE
FTP_COMMAND_HELP
FTP_COMMAND_IDLE
FTP_COMMAND_LIST
FTP_COMMAND_MAIL
FTP_COMMAND_MDTM
FTP_COMMAND_MKD
FTP_COMMAND_MLFL
FTP_COMMAND_MODE
FTP_COMMAND_MRCP
FTP_COMMAND_MRSQ
FTP_COMMAND_MSAM
FTP_COMMAND_MSND
FTP_COMMAND_MSOM
FTP_COMMAND_NLST
FTP_COMMAND_NOOP
FTP_COMMAND_PASS
FTP_COMMAND_PASV
FTP_COMMAND_PORT
FTP_COMMAND_PWD
FTP_COMMAND_QUIT
FTP_COMMAND_REIN
FTP_COMMAND_REST
FTP_COMMAND_RETR
FTP_COMMAND_RMD
FTP_COMMAND_RNFR
FTP_COMMAND_RNTO
FTP_COMMAND_SITE
FTP_COMMAND_SIZE
FTP_COMMAND_SMNT
FTP_COMMAND_STAT
FTP_COMMAND_STOR
FTP_COMMAND_STOU
FTP_COMMAND_STRU
FTP_COMMAND_SYST
FTP_COMMAND_TYPE
FTP_COMMAND_UMASK
FTP_COMMAND_USER
Todo:
more if missing..
Definition at line 27 of file app-layer-ftp.h.
Function Documentation
void FTPAtExitPrintStats (void)
Definition at line 363 of file app-layer-ftp.c.
References SCLogDebug, SCMutexLock, and SCMutexUnlock.
void FTPParserRegisterTests (void)
Definition at line 671 of file app-layer-ftp.c.
Referenced by RegisterFTPParsers().
void RegisterFTPParsers (void)
FTP
Definition at line 336 of file app-layer-ftp.c.
References ALPROTO_FTP, AppLayerParserConfParserEnabled(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), FTPParserRegisterTests(), SCLogInfo, STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().