suricata: src/app-layer-ftp.c File Reference
app-layer-ftp.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "flow-util.h"
#include "detect-engine-state.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer-ftp.h"
#include "util-spm.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "util-memcmp.h"
Functions
void RegisterFTPParsers (void)
void FTPAtExitPrintStats (void)
void FTPParserRegisterTests (void)
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
App Layer Parser for FTP
Definition in file app-layer-ftp.c.
Function Documentation
void FTPAtExitPrintStats (void)
Definition at line 363 of file app-layer-ftp.c.
References SCLogDebug, SCMutexLock, and SCMutexUnlock.
void FTPParserRegisterTests (void)
Definition at line 671 of file app-layer-ftp.c.
Referenced by RegisterFTPParsers().
void RegisterFTPParsers (void)
FTP
Definition at line 336 of file app-layer-ftp.c.
References ALPROTO_FTP, AppLayerParserConfParserEnabled(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), FTPParserRegisterTests(), SCLogInfo, STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().