suricata: src/app-layer-protos.c File Reference
app-layer-protos.c File Reference
#include "suricata-common.h"
#include "app-layer-protos.h"
Macros
#define CASE_CODE(E) case E: return #E
Functions
const char * AppProtoToString (AppProto alproto)
Maps the ALPROTO_*, to its string equivalent.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file app-layer-protos.c.
Macro Definition Documentation
#define CASE_CODE (E) case E: return #E
Definition at line 28 of file app-layer-protos.c.
Function Documentation
const char* AppProtoToString (AppProto alproto)
Maps the ALPROTO_*, to its string equivalent.
Parameters
alproto App layer protocol id.
Return values
String equivalent for the alproto.
Definition at line 30 of file app-layer-protos.c.
References ALPROTO_DCERPC, ALPROTO_DNS, ALPROTO_FAILED, ALPROTO_FTP, ALPROTO_HTTP, ALPROTO_IMAP, ALPROTO_IRC, ALPROTO_JABBER, ALPROTO_MAX, ALPROTO_MODBUS, ALPROTO_MSN, ALPROTO_SMB, ALPROTO_SMB2, ALPROTO_SMTP, ALPROTO_SSH, ALPROTO_TEMPLATE, ALPROTO_TLS, ALPROTO_UNKNOWN, and proto.
Referenced by EngineAnalysisRules(), SCProfilingDumpPacketStats(), and SCProfilingInit().