suricata: src/app-layer-dns-common.c File Reference
app-layer-dns-common.c File Reference
#include "suricata-common.h"
#include "stream.h"
#include "app-layer-parser.h"
#include "app-layer-dns-common.h"
#include "util-memcmp.h"
#include "util-atomic.h"
Data Structures
struct DNSConfig_
Typedefs
typedef struct DNSConfig_ DNSConfig
Functions
void DNSConfigInit (void)
void DNSConfigSetRequestFlood (uint32_t value)
void DNSConfigSetStateMemcap (uint32_t value)
SC_ATOMIC_DECLARE (uint64_t, dns_memuse)
SC_ATOMIC_DECLARE (uint64_t, dns_memcap_state)
SC_ATOMIC_DECLARE (uint64_t, dns_memcap_global)
void DNSConfigSetGlobalMemcap (uint64_t value)
void DNSIncrMemcap (uint32_t size, DNSState *state)
void DNSDecrMemcap (uint32_t size, DNSState *state)
int DNSCheckMemcap (uint32_t want, DNSState *state)
uint64_t DNSMemcapGetMemuseCounter (void)
uint64_t DNSMemcapGetMemcapStateCounter (void)
uint64_t DNSMemcapGetMemcapGlobalCounter (void)
int DNSStateGetEventInfo (const char *event_name, int *event_id, AppLayerEventType *event_type)
void DNSAppLayerRegisterGetEventInfo (uint8_t ipproto, AppProto alproto)
AppLayerDecoderEvents * DNSGetEvents (void *state, uint64_t id)
int DNSHasEvents (void *state)
void * DNSGetTx (void *alstate, uint64_t tx_id)
uint64_t DNSGetTxCnt (void *alstate)
int DNSGetAlstateProgress (void *tx, uint8_t direction)
int DNSGetAlstateProgressCompletionStatus (uint8_t direction)
get value for 'complete' status in DNS
void DNSSetEvent (DNSState *s, uint8_t e)
void DNSStateTransactionFree (void *state, uint64_t tx_id)
dns transaction cleanup callback
DNSTransaction * DNSTransactionFindByTxId (const DNSState *dns_state, const uint16_t tx_id)
int DNSStateHasTxDetectState (void *alstate)
DetectEngineState * DNSGetTxDetectState (void *vtx)
int DNSSetTxDetectState (void *alstate, void *vtx, DetectEngineState *s)
void * DNSStateAlloc (void)
void DNSStateFree (void *s)
int DNSValidateRequestHeader (DNSState *dns_state, const DNSHeader *dns_header)
Validation checks for DNS request header.
int DNSValidateResponseHeader (DNSState *dns_state, const DNSHeader *dns_header)
Validation checks for DNS response header.
void DNSStoreQueryInState (DNSState *dns_state, const uint8_t *fqdn, const uint16_t fqdn_len, const uint16_t type, const uint16_t class, const uint16_t tx_id)
void DNSStoreAnswerInState (DNSState *dns_state, const int rtype, const uint8_t *fqdn, const uint16_t fqdn_len, const uint16_t type, const uint16_t class, const uint16_t ttl, const uint8_t *data, const uint16_t data_len, const uint16_t tx_id)
const uint8_t * DNSReponseParse (DNSState *dns_state, const DNSHeader *const dns_header, const uint16_t num, const DnsListEnum list, const uint8_t *const input, const uint32_t input_len, const uint8_t *data)
void DNSCreateTypeString (uint16_t type, char *str, size_t str_size)
void DNSCreateRcodeString (uint8_t rcode, char *str, size_t str_size)
Variables
SCEnumCharMap dns_decoder_event_table []
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file app-layer-dns-common.c.
Typedef Documentation
typedef struct DNSConfig_ DNSConfig
Function Documentation
void DNSAppLayerRegisterGetEventInfo (uint8_t ipproto, AppProto alproto)
Definition at line 152 of file app-layer-dns-common.c.
References AppLayerParserRegisterGetEventInfo(), and DNSStateGetEventInfo().
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
int DNSCheckMemcap (uint32_t want, DNSState * state)
Definition at line 88 of file app-layer-dns-common.c.
References DNS_DECODER_EVENT_STATE_MEMCAP_REACHED, DNSSetEvent(), DNSConfig_::global_memcap, DNSState_::memuse, SC_ATOMIC_ADD, SC_ATOMIC_GET, and DNSConfig_::state_memcap.
Referenced by DNSStoreAnswerInState(), and DNSStoreQueryInState().
void DNSConfigInit (void)
Definition at line 41 of file app-layer-dns-common.c.
void DNSConfigSetGlobalMemcap (uint64_t value)
Definition at line 60 of file app-layer-dns-common.c.
References DNSConfig_::global_memcap, and SC_ATOMIC_INIT.
void DNSConfigSetRequestFlood (uint32_t value)
Definition at line 46 of file app-layer-dns-common.c.
References DNSConfig_::request_flood.
void DNSConfigSetStateMemcap (uint32_t value)
Definition at line 51 of file app-layer-dns-common.c.
References DNSConfig_::state_memcap.
void DNSCreateRcodeString (uint8_t rcode, char * str, size_t str_size)
Definition at line 1078 of file app-layer-dns-common.c.
References DNS_RCODE_BADALG, DNS_RCODE_BADKEY, DNS_RCODE_BADMODE, DNS_RCODE_BADNAME, DNS_RCODE_BADTIME, DNS_RCODE_BADTRUNC, DNS_RCODE_BADVERS, DNS_RCODE_FORMERR, DNS_RCODE_NOERROR, DNS_RCODE_NOTAUTH, DNS_RCODE_NOTIMP, DNS_RCODE_NOTZONE, DNS_RCODE_NXDOMAIN, DNS_RCODE_NXRRSET, DNS_RCODE_REFUSED, DNS_RCODE_SERVFAIL, DNS_RCODE_YXDOMAIN, DNS_RCODE_YXRRSET, and SCLogDebug.
void DNSCreateTypeString (uint16_t type, char * str, size_t str_size)
Definition at line 1019 of file app-layer-dns-common.c.
References DNS_RECORD_TYPE_A, DNS_RECORD_TYPE_AAAA, DNS_RECORD_TYPE_ANY, DNS_RECORD_TYPE_CNAME, DNS_RECORD_TYPE_DS, DNS_RECORD_TYPE_MX, DNS_RECORD_TYPE_NAPTR, DNS_RECORD_TYPE_NS, DNS_RECORD_TYPE_NSEC, DNS_RECORD_TYPE_NSEC3, DNS_RECORD_TYPE_PTR, DNS_RECORD_TYPE_RRSIG, DNS_RECORD_TYPE_SOA, DNS_RECORD_TYPE_SRV, DNS_RECORD_TYPE_TKEY, DNS_RECORD_TYPE_TSIG, and DNS_RECORD_TYPE_TXT.
void DNSDecrMemcap (uint32_t size, DNSState * state)
< TODO remove later
< TODO remove later
Definition at line 77 of file app-layer-dns-common.c.
References BUG_ON, DNSState_::memuse, SC_ATOMIC_GET, and SC_ATOMIC_SUB.
Referenced by DNSStateFree().
int DNSGetAlstateProgress (void * tx, uint8_t direction)
Definition at line 223 of file app-layer-dns-common.c.
References DNSTransaction_::replied, DNSTransaction_::reply_lost, and STREAM_TOCLIENT.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
int DNSGetAlstateProgressCompletionStatus (uint8_t direction)
get value for 'complete' status in DNS
For DNS we use a simple bool. 1 means done.
Definition at line 243 of file app-layer-dns-common.c.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
AppLayerDecoderEvents* DNSGetEvents (void * state, uint64_t id)
Definition at line 159 of file app-layer-dns-common.c.
References DNSState_::curr, DNSTransaction_::decoder_events, next, TAILQ_FOREACH, and DNSTransaction_::tx_num.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
void* DNSGetTx (void * alstate, uint64_t tx_id)
Definition at line 181 of file app-layer-dns-common.c.
References DNSState_::curr, DNSState_::iter, next, SCLogDebug, TAILQ_FOREACH, TAILQ_NEXT, and DNSTransaction_::tx_num.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
uint64_t DNSGetTxCnt (void * alstate)
Definition at line 217 of file app-layer-dns-common.c.
References DNSState_::transaction_max.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
DetectEngineState* DNSGetTxDetectState (void * vtx)
Definition at line 393 of file app-layer-dns-common.c.
References DNSTransaction_::de_state.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
int DNSHasEvents (void * state)
Definition at line 175 of file app-layer-dns-common.c.
References DNSState_::events.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
void DNSIncrMemcap (uint32_t size, DNSState * state)
Definition at line 69 of file app-layer-dns-common.c.
References DNSState_::memuse, and SC_ATOMIC_ADD.
Referenced by DNSStateAlloc(), DNSStoreAnswerInState(), and DNSStoreQueryInState().
uint64_t DNSMemcapGetMemcapGlobalCounter (void)
Definition at line 118 of file app-layer-dns-common.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
uint64_t DNSMemcapGetMemcapStateCounter (void)
Definition at line 112 of file app-layer-dns-common.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
uint64_t DNSMemcapGetMemuseCounter (void)
Definition at line 106 of file app-layer-dns-common.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
const uint8_t* DNSReponseParse (DNSState * dns_state, const DNSHeader *const dns_header, const uint16_t num, const DnsListEnum list, const uint8_t *const input, const uint32_t input_len, const uint8_t * data)
Definition at line 773 of file app-layer-dns-common.c.
References BUG_ON, DNSAnswerHeader_::class, data, DNS_MAX_SIZE, DNS_RECORD_TYPE_A, DNS_RECORD_TYPE_AAAA, DNS_RECORD_TYPE_CNAME, DNS_RECORD_TYPE_MX, DNS_RECORD_TYPE_NS, DNS_RECORD_TYPE_PTR, DNS_RECORD_TYPE_SOA, DNS_RECORD_TYPE_TXT, DNSStoreAnswerInState(), head, DNSAnswerHeader_::len, PrintRawDataFp(), SCLogDebug, tail, DNSAnswerHeader_::ttl, and DNSAnswerHeader_::type.
void DNSSetEvent (DNSState * s, uint8_t e)
Definition at line 248 of file app-layer-dns-common.c.
References AppLayerDecoderEventsSetEventRaw(), DNSState_::curr, DNSTransaction_::decoder_events, DNSState_::events, and SCLogDebug.
Referenced by DNSCheckMemcap(), DNSStoreQueryInState(), DNSValidateRequestHeader(), and DNSValidateResponseHeader().
int DNSSetTxDetectState (void * alstate, void * vtx, DetectEngineState * s)
Definition at line 399 of file app-layer-dns-common.c.
References DNSTransaction_::de_state, and DNSState_::tx_with_detect_state_cnt.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
void* DNSStateAlloc (void)
Definition at line 408 of file app-layer-dns-common.c.
References DNSIncrMemcap(), SCMalloc, TAILQ_INIT, and unlikely.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
void DNSStateFree (void * s)
TODO update if/once we alloc in a smarter way
Definition at line 424 of file app-layer-dns-common.c.
References DNSState_::buffer, BUG_ON, DNSDecrMemcap(), DNSState_::memuse, next, SCEnter, SCFree, SCReturn, TAILQ_FIRST, TAILQ_REMOVE, and DNSState_::tx_with_detect_state_cnt.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
int DNSStateGetEventInfo (const char * event_name, int * event_id, AppLayerEventType * event_type)
Definition at line 136 of file app-layer-dns-common.c.
References APP_LAYER_EVENT_TYPE_TRANSACTION, SC_ERR_INVALID_ENUM_MAP, SCLogError, and SCMapEnumNameToValue().
Referenced by DNSAppLayerRegisterGetEventInfo().
int DNSStateHasTxDetectState (void * alstate)
Definition at line 387 of file app-layer-dns-common.c.
References DNSState_::tx_with_detect_state_cnt.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
void DNSStateTransactionFree (void * state, uint64_t tx_id)
dns transaction cleanup callback
Definition at line 328 of file app-layer-dns-common.c.
References AppLayerDecoderEvents_::cnt, DNSState_::curr, DNSTransaction_::decoder_events, DNSState_::events, next, SCEnter, SCLogDebug, SCReturn, TAILQ_FOREACH, TAILQ_REMOVE, and DNSTransaction_::tx_num.
Referenced by RegisterDNSTCPParsers(), and RegisterDNSUDPParsers().
void DNSStoreAnswerInState (DNSState * dns_state, const int rtype, const uint8_t * fqdn, const uint16_t fqdn_len, const uint16_t type, const uint16_t class, const uint16_t ttl, const uint8_t * data, const uint16_t data_len, const uint16_t tx_id)
Definition at line 586 of file app-layer-dns-common.c.
References BUG_ON, DNSAnswerEntry_::class, DNSState_::curr, DNSAnswerEntry_::data_len, DNS_LIST_ANSWER, DNS_LIST_AUTHORITY, DNSCheckMemcap(), DNSIncrMemcap(), DNSTransactionFindByTxId(), DNSAnswerEntry_::fqdn_len, next, DNSTransaction_::replied, SCLogDebug, SCMalloc, TAILQ_INSERT_TAIL, DNSState_::transaction_max, ttl, DNSAnswerEntry_::ttl, DNSTransaction_::tx_num, type, DNSAnswerEntry_::type, unlikely, and DNSState_::unreplied_cnt.
Referenced by DNSReponseParse().
void DNSStoreQueryInState (DNSState * dns_state, const uint8_t * fqdn, const uint16_t fqdn_len, const uint16_t type, const uint16_t class, const uint16_t tx_id)
Definition at line 528 of file app-layer-dns-common.c.
References DNSQueryEntry_::class, DNSState_::curr, DNS_DECODER_EVENT_FLOODED, DNSCheckMemcap(), DNSIncrMemcap(), DNSSetEvent(), DNSTransactionFindByTxId(), DNSState_::givenup, DNSQueryEntry_::len, next, DNSTransaction_::replied, DNSTransaction_::reply_lost, DNSConfig_::request_flood, SCLogDebug, SCMalloc, TAILQ_INSERT_TAIL, DNSState_::transaction_max, TRUE, DNSTransaction_::tx_id, DNSTransaction_::tx_num, type, DNSQueryEntry_::type, unlikely, and DNSState_::unreplied_cnt.
DNSTransaction* DNSTransactionFindByTxId (const DNSState * dns_state, const uint16_t tx_id)
Definition at line 365 of file app-layer-dns-common.c.
References DNSState_::curr, next, TAILQ_FOREACH, and DNSTransaction_::tx_id.
Referenced by DNSStoreAnswerInState(), and DNSStoreQueryInState().
int DNSValidateRequestHeader (DNSState * dns_state, const DNSHeader * dns_header)
Validation checks for DNS request header.
Will set decoder events if anomalies are found.
Return values
0 ok
-1 error
Definition at line 458 of file app-layer-dns-common.c.
References DNS_DECODER_EVENT_NOT_A_REQUEST, DNS_DECODER_EVENT_Z_FLAG_SET, DNSSetEvent(), flags, and SCLogDebug.
int DNSValidateResponseHeader (DNSState * dns_state, const DNSHeader * dns_header)
Validation checks for DNS response header.
Will set decoder events if anomalies are found.
Return values
0 ok
-1 error
Definition at line 486 of file app-layer-dns-common.c.
References DNS_DECODER_EVENT_NOT_A_RESPONSE, DNS_DECODER_EVENT_Z_FLAG_SET, DNSSetEvent(), flags, and SCLogDebug.
SC_ATOMIC_DECLARE (uint64_t , dns_memuse)
byte counter of current memuse
SC_ATOMIC_DECLARE (uint64_t , dns_memcap_state)
counts number of 'rejects'
SC_ATOMIC_DECLARE (uint64_t , dns_memcap_global)
counts number of 'rejects'
Variable Documentation
SCEnumCharMap dns_decoder_event_table[]
Initial value:
= {
    { "UNSOLLICITED_RESPONSE",      DNS_DECODER_EVENT_UNSOLLICITED_RESPONSE, },
    { "MALFORMED_DATA",             DNS_DECODER_EVENT_MALFORMED_DATA, },
    { "NOT_A_REQUEST",              DNS_DECODER_EVENT_NOT_A_REQUEST, },
    { "NOT_A_RESPONSE",             DNS_DECODER_EVENT_NOT_A_RESPONSE, },
    { "Z_FLAG_SET",                 DNS_DECODER_EVENT_Z_FLAG_SET, },
    { "FLOODED",                    DNS_DECODER_EVENT_FLOODED, },
    { "STATE_MEMCAP_REACHED",       DNS_DECODER_EVENT_STATE_MEMCAP_REACHED, },
    { NULL,                         -1 },
}
Definition at line 124 of file app-layer-dns-common.c.