suricata: src/app-layer-htp.c File Reference
app-layer-htp.c File Reference
HTTP layer support
#include "suricata.h"
#include "suricata-common.h"
#include "conf.h"
#include "debug.h"
#include "decode.h"
#include "threads.h"
#include "counters.h"
#include "util-print.h"
#include "util-pool.h"
#include "util-radix-tree.h"
#include "util-file.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer.h"
#include "app-layer-htp.h"
#include "app-layer-htp-body.h"
#include "app-layer-htp-file.h"
#include "app-layer-htp-libhtp.h"
#include "app-layer-htp-xff.h"
#include "util-spm.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-misc.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "flow-util.h"
#include "detect-engine.h"
#include "detect-engine-state.h"
#include "detect-parse.h"
#include "decode-events.h"
#include "util-memcmp.h"
Macros
#define IF_HTP_PERSONALITY_NUM(p) if (strcasecmp(#p, str) == 0) return HTP_SERVER_ ## p
#define HTP_ERROR_MAX (sizeof(htp_errors) / sizeof(htp_errors[0]))
#define HTP_WARNING_MAX (sizeof(htp_warnings) / sizeof(htp_warnings[0]))
#define C_D_HDR "content-disposition:"
#define C_D_HDR_LEN 20
#define C_T_HDR "content-type:"
#define C_T_HDR_LEN 13
SCEnumCharMap http_decoder_event_table []
struct {
char * msg
int de
} htp_errors []
struct {
char * msg
int de
} htp_warnings []
void HTPSetEvent (HtpState *s, HtpTxUserData *htud, uint8_t e)
void HTPStateFree (void *state)
Function to frees the HTTP state memory and also frees the HTTP connection parser memory which was used by the HTP library.
void AppLayerHtpEnableRequestBodyCallback (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request body data. .
void AppLayerHtpEnableResponseBodyCallback (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request body data. .
void AppLayerHtpNeedMultipartHeader (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request multi part header.
void AppLayerHtpNeedFileInspection (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request file.
int HtpRequestBodyHandleMultipart (HtpState *hstate, HtpTxUserData *htud, void *tx, uint8_t *chunks_buffer, uint32_t chunks_buffer_len)
int HtpRequestBodySetupPUT (htp_tx_data_t *d, HtpTxUserData *htud)
setup things for put request
int HtpResponseBodyHandle (HtpState *hstate, HtpTxUserData *htud, htp_tx_t *tx, uint8_t *data, uint32_t data_len)
int HTPCallbackRequestBodyData (htp_tx_data_t *d)
Function callback to append chunks for Requests.
int HTPCallbackResponseBodyData (htp_tx_data_t *d)
Function callback to append chunks for Responses.
void HTPAtExitPrintStats (void)
Print the stats of the HTTP requests.
void HTPFreeConfig (void)
Clears the HTTP server configuration memory used by HTP library.
void HTPConfigure (void)
void AppLayerHtpPrintStats (void)
int HTPStateGetEventInfo (const char *event_name, int *event_id, AppLayerEventType *event_type)
void RegisterHTPParsers (void)
Register the HTTP protocol and state handling functions to APP layer of the engine.
void HTPParserRegisterTests (void)
Register the Unit tests for the HTTP protocol.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Brian Rectanus brect.nosp@m.anu@.nosp@m.gmail.nosp@m..com
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
This file provides a HTTP protocol support for the engine using HTP library.
Definition in file app-layer-htp.c.
Macro Definition Documentation
#define C_D_HDR "content-disposition:"
Definition at line 1129 of file app-layer-htp.c.
#define C_D_HDR_LEN 20
Definition at line 1130 of file app-layer-htp.c.
#define C_T_HDR "content-type:"
Definition at line 1131 of file app-layer-htp.c.
#define C_T_HDR_LEN 13
Definition at line 1132 of file app-layer-htp.c.
#define HTP_ERROR_MAX (sizeof(htp_errors) / sizeof(htp_errors[0]))
Definition at line 525 of file app-layer-htp.c.
#define HTP_WARNING_MAX (sizeof(htp_warnings) / sizeof(htp_warnings[0]))
Definition at line 526 of file app-layer-htp.c.
#define IF_HTP_PERSONALITY_NUM (p) if (strcasecmp(#p, str) == 0) return HTP_SERVER_ ## p
Function Documentation
void AppLayerHtpNeedMultipartHeader (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request multi part header.
Definition at line 455 of file app-layer-htp.c.
References AppLayerHtpEnableRequestBodyCallback(), HTP_REQUIRE_REQUEST_MULTIPART, SC_ATOMIC_OR, SCEnter, and SCReturn.
Referenced by AppLayerHtpNeedFileInspection().
int HTPCallbackResponseBodyData (htp_tx_data_t * d)
Function callback to append chunks for Responses.
Parameters
d pointer to the htp_tx_data_t structure (a chunk from htp lib)
Return values
int HTP_OK if all goes well
Definition at line 1880 of file app-layer-htp.c.
References BUG_ON, HtpState_::cfg, htp_tx_t::connp, HtpBody_::content_len_so_far, htp_tx_data_t::data, HtpState_::flags, HTP_BODY_RESPONSE, htp_connp_get_user_data(), HTP_ERROR, HTP_FLAG_NEW_BODY_SET, HTP_OK, HTP_REQUIRE_RESPONSE_BODY, htp_tx_get_user_data(), htp_tx_set_user_data(), HtpBodyAppendChunk(), HtpBodyPrune(), HTPMalloc(), HtpResponseBodyHandle(), htp_tx_data_t::len, HtpTxUserData_::operation, HtpTxUserData_::request_body_init, HtpTxUserData_::response_body, HTPCfgRec_::response_body_limit, SC_ATOMIC_GET, SCEnter, SCLogDebug, SCReturnInt, STREAM_TOCLIENT, htp_tx_data_t::tx, and unlikely.
int HtpRequestBodyHandleMultipart (HtpState * hstate, HtpTxUserData * htud, void * tx, uint8_t * chunks_buffer, uint32_t chunks_buffer_len)
Definition at line 1278 of file app-layer-htp.c.
References ALPROTO_HTTP, AppLayerParserGetStateProgress(), HtpBody_::body_parsed, Bs2bmSearch(), FILE_TRUNCATED, flags, ptxdump::header, HTP_DONTSTORE, HTP_FILENAME_SET, HTP_REQUEST_BODY, HTP_RESPONSE_BODY, HTPFileClose(), HTPFileOpen(), HTPFileStoreChunk(), HTPFree(), HTPSetEvent(), HTTP_DECODER_EVENT_MULTIPART_GENERIC_ERROR, HTTP_DECODER_EVENT_MULTIPART_NO_FILEDATA, next, PrintRawDataFp(), HtpTxUserData_::request_body, SCLogDebug, STREAM_TOSERVER, HtpState_::transaction_cnt, and HtpTxUserData_::tsflags.
Referenced by HTPCallbackRequestBodyData().
int HtpRequestBodySetupPUT (htp_tx_data_t * d, HtpTxUserData * htud)
setup things for put request
Todo:
really needed?
Definition at line 1569 of file app-layer-htp.c.
Referenced by HTPCallbackRequestBodyData().
int HtpResponseBodyHandle (HtpState * hstate, HtpTxUserData * htud, htp_tx_t * tx, uint8_t * data, uint32_t data_len)
Definition at line 1686 of file app-layer-htp.c.
References HtpBody_::body_parsed, bstr_len, bstr_ptr, HTP_DONTSTORE, HTP_FILENAME_SET, htp_table_get_c(), HTPFileOpen(), HTPFileStoreChunk(), htp_tx_t::parsed_uri, htp_uri_t::path, HtpTxUserData_::response_body, htp_tx_t::response_headers, SCEnter, SCLogDebug, STREAM_TOCLIENT, HtpTxUserData_::tcflags, HtpState_::transaction_cnt, and htp_header_t::value.
Referenced by HTPCallbackResponseBodyData().
void HTPSetEvent (HtpState * s, HtpTxUserData * htud, uint8_t e)
Definition at line 236 of file app-layer-htp.c.
References AppLayerDecoderEventsSetEventRaw(), HtpTxUserData_::decoder_events, HtpState_::events, htp_tx_get_user_data(), SCLogDebug, and HtpState_::transaction_cnt.
Referenced by HtpRequestBodyHandleMultipart().
int HTPStateGetEventInfo (const char * event_name, int * event_id, AppLayerEventType * event_type)
Definition at line 2647 of file app-layer-htp.c.
References APP_LAYER_EVENT_TYPE_TRANSACTION, SC_ERR_INVALID_ENUM_MAP, SCLogError, and SCMapEnumNameToValue().
Referenced by RegisterHTPParsers().
Variable Documentation
int de
Definition at line 484 of file app-layer-htp.c.
Referenced by DetectEngineEventMatch(), DetectEngineEventParse(), DetectIpOptsMatch(), and DetectIpOptsParse().
struct { ... } htp_errors[]
Initial value:
= {
    { "GZip decompressor: inflateInit2 failed", HTTP_DECODER_EVENT_GZIP_DECOMPRESSION_FAILED},
    { "Request field invalid: colon missing", HTTP_DECODER_EVENT_REQUEST_FIELD_MISSING_COLON},
    { "Response field invalid: missing colon", HTTP_DECODER_EVENT_RESPONSE_FIELD_MISSING_COLON},
    { "Request chunk encoding: Invalid chunk length", HTTP_DECODER_EVENT_INVALID_REQUEST_CHUNK_LEN},
    { "Response chunk encoding: Invalid chunk length", HTTP_DECODER_EVENT_INVALID_RESPONSE_CHUNK_LEN},
    { "Invalid C-L field in response", HTTP_DECODER_EVENT_INVALID_CONTENT_LENGTH_FIELD_IN_RESPONSE},
    { "Already seen 100-Continue", HTTP_DECODER_EVENT_100_CONTINUE_ALREADY_SEEN},
    { "Unable to match response to request", HTTP_DECODER_EVENT_UNABLE_TO_MATCH_RESPONSE_TO_REQUEST},
    { "Invalid server port information in request", HTTP_DECODER_EVENT_INVALID_SERVER_PORT_IN_REQUEST},
    { "Request buffer over", HTTP_DECODER_EVENT_REQUEST_FIELD_TOO_LONG},
    { "Response buffer over", HTTP_DECODER_EVENT_RESPONSE_FIELD_TOO_LONG},
}
struct { ... } htp_warnings[]
Initial value:
= {
    { "GZip decompressor:", HTTP_DECODER_EVENT_GZIP_DECOMPRESSION_FAILED},
    { "Request field invalid", HTTP_DECODER_EVENT_REQUEST_HEADER_INVALID},
    { "Response field invalid", HTTP_DECODER_EVENT_RESPONSE_HEADER_INVALID},
    { "Request header name is not a token", HTTP_DECODER_EVENT_REQUEST_HEADER_INVALID},
    { "Response header name is not a token", HTTP_DECODER_EVENT_RESPONSE_HEADER_INVALID},
    { "Invalid request field folding", HTTP_DECODER_EVENT_INVALID_REQUEST_FIELD_FOLDING},
    { "Invalid response field folding", HTTP_DECODER_EVENT_INVALID_RESPONSE_FIELD_FOLDING},
    { "Request server port=", HTTP_DECODER_EVENT_REQUEST_SERVER_PORT_TCP_PORT_MISMATCH},
    { "Request line: URI contains non-compliant delimiter", HTTP_DECODER_EVENT_URI_DELIM_NON_COMPLIANT},
    { "Request line: non-compliant delimiter between Method and URI", HTTP_DECODER_EVENT_METHOD_DELIM_NON_COMPLIANT},
    { "Request line: leading whitespace", HTTP_DECODER_EVENT_REQUEST_LINE_LEADING_WHITESPACE},
}
SCEnumCharMap http_decoder_event_table[]
Definition at line 94 of file app-layer-htp.c.
char* msg
Definition at line 483 of file app-layer-htp.c.
Referenced by DetectRpcMatch(), and MimeDecParseFullMsg().