suricata: src/app-layer-dns-tcp.c File Reference
app-layer-dns-tcp.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "debug.h"
#include "decode.h"
#include "flow-util.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "util-debug.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "util-spm.h"
#include "util-unittest.h"
#include "app-layer-dns-tcp.h"
Data Structures
struct DNSTcpHeader_
Typedefs
typedef struct DNSTcpHeader_ DNSTcpHeader
Functions
struct DNSTcpHeader_ __attribute__ ((__packed__))
DNS packet header.
void RegisterDNSTCPParsers (void)
Variables
uint16_t len
uint16_t tx_id
uint16_t flags
uint16_t questions
uint16_t answer_rr
uint16_t authority_rr
uint16_t additional_rr
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file app-layer-dns-tcp.c.
Typedef Documentation
typedef struct DNSTcpHeader_ DNSTcpHeader
Definition at line 59 of file app-layer-dns-tcp.c.
Function Documentation
struct DNSTcpHeader_ __attribute__ ((__packed__))
DNS packet header.
Unified2 Extra Data Header Unified2 Extra Data (currently used only for XFF)
Definition at line 94 of file alert-unified2-alert.c.
void RegisterDNSTCPParsers (void)
DNS
Definition at line 609 of file app-layer-dns-tcp.c.
References ALPROTO_DNS, AppLayerParserConfParserEnabled(), AppLayerParserRegisterDetectStateFuncs(), AppLayerParserRegisterGetEventsFunc(), AppLayerParserRegisterGetStateProgressCompletionStatus(), AppLayerParserRegisterGetStateProgressFunc(), AppLayerParserRegisterGetTx(), AppLayerParserRegisterGetTxCnt(), AppLayerParserRegisterHasEventsFunc(), AppLayerParserRegisterParser(), AppLayerParserRegisterStateFuncs(), AppLayerParserRegisterTxFreeFunc(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectPPParseConfPorts(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), DNSAppLayerRegisterGetEventInfo(), DNSGetAlstateProgress(), DNSGetAlstateProgressCompletionStatus(), DNSGetEvents(), DNSGetTx(), DNSGetTxCnt(), DNSGetTxDetectState(), DNSHasEvents(), DNSSetTxDetectState(), DNSStateAlloc(), DNSStateFree(), DNSStateHasTxDetectState(), DNSStateTransactionFree(), RunmodeIsUnittests(), SC_ERR_DNS_CONFIG, SCLogInfo, SCLogWarning, STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().
Variable Documentation
uint16_t additional_rr
Definition at line 201 of file app-layer-dns-tcp.c.
uint16_t answer_rr
Definition at line 199 of file app-layer-dns-tcp.c.
uint16_t authority_rr
Definition at line 200 of file app-layer-dns-tcp.c.
uint16_t flags
Definition at line 197 of file app-layer-dns-tcp.c.
uint16_t len
Definition at line 195 of file app-layer-dns-tcp.c.
uint16_t questions
Definition at line 198 of file app-layer-dns-tcp.c.
uint16_t tx_id
Definition at line 196 of file app-layer-dns-tcp.c.