suricata: src/app-layer-dns-udp.c File Reference
app-layer-dns-udp.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "conf.h"
#include "util-misc.h"
#include "debug.h"
#include "decode.h"
#include "flow-util.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "util-debug.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "util-spm.h"
#include "util-unittest.h"
#include "app-layer-dns-udp.h"
Functions
void RegisterDNSUDPParsers (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file app-layer-dns-udp.c.
Function Documentation
void RegisterDNSUDPParsers (void)
DNS
Definition at line 365 of file app-layer-dns-udp.c.
References ALPROTO_DNS, AppLayerParserConfParserEnabled(), AppLayerParserRegisterDetectStateFuncs(), AppLayerParserRegisterGetEventsFunc(), AppLayerParserRegisterGetStateProgressCompletionStatus(), AppLayerParserRegisterGetStateProgressFunc(), AppLayerParserRegisterGetTx(), AppLayerParserRegisterGetTxCnt(), AppLayerParserRegisterHasEventsFunc(), AppLayerParserRegisterParser(), AppLayerParserRegisterStateFuncs(), AppLayerParserRegisterTxFreeFunc(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectPPParseConfPorts(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), DNSAppLayerRegisterGetEventInfo(), DNSGetAlstateProgress(), DNSGetAlstateProgressCompletionStatus(), DNSGetEvents(), DNSGetTx(), DNSGetTxCnt(), DNSGetTxDetectState(), DNSHasEvents(), DNSSetTxDetectState(), DNSStateAlloc(), DNSStateFree(), DNSStateHasTxDetectState(), DNSStateTransactionFree(), DNSUDPParserRegisterTests(), RunmodeIsUnittests(), SC_ERR_DNS_CONFIG, SCLogInfo, SCLogWarning, STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by AppLayerParserRegisterProtocolParsers().