suricata: libhtp/htp/bstr.h File Reference
bstr.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "bstr_builder.h"
Data Structures
struct bstr_t
Macros
#define bstr_len(X) ((*(X)).len)
#define bstr_size(X) ((*(X)).size)
#define bstr_ptr(X) (((*(X)).realptr == NULL) ? ((unsigned char *)(X) + sizeof(bstr)) : (unsigned char *)(*(X)).realptr)
#define bstr_realptr(X) ((*(X)).realptr)
Typedefs
typedef struct bstr_t bstr
Functions
bstr * bstr_add (bstr *bdestination, const bstr *bsource)
bstr * bstr_add_c (bstr *b, const char *cstr)
bstr * bstr_add_c_noex (bstr *b, const char *cstr)
bstr * bstr_add_mem (bstr *b, const void *data, size_t len)
bstr * bstr_add_mem_noex (bstr *b, const void *data, size_t len)
bstr * bstr_add_noex (bstr *bdestination, const bstr *bsource)
void bstr_adjust_len (bstr *b, size_t newlen)
void bstr_adjust_realptr (bstr *b, void *newrealptr)
void bstr_adjust_size (bstr *b, size_t newsize)
bstr * bstr_alloc (size_t size)
int bstr_begins_with (const bstr *bhaystack, const bstr *bneedle)
int bstr_begins_with_c (const bstr *bhaystack, const char *cneedle)
int bstr_begins_with_c_nocase (const bstr *bhaystack, const char *cneedle)
int bstr_begins_with_mem (const bstr *bhaystack, const void *data, size_t len)
int bstr_begins_with_mem_nocase (const bstr *bhaystack, const void *data, size_t len)
int bstr_begins_with_nocase (const bstr *bhaystack, const bstr *cneedle)
int bstr_char_at (const bstr *b, size_t pos)
int bstr_char_at_end (const bstr *b, size_t pos)
void bstr_chop (bstr *b)
int bstr_chr (const bstr *b, int c)
int bstr_cmp (const bstr *b1, const bstr *b2)
int bstr_cmp_c (const bstr *b, const char *cstr)
int bstr_cmp_c_nocase (const bstr *b, const char *cstr)
int bstr_cmp_mem (const bstr *b, const void *data, size_t len)
int bstr_cmp_mem_nocase (const bstr *b, const void *data, size_t len)
int bstr_cmp_nocase (const bstr *b1, const bstr *b2)
bstr * bstr_dup (const bstr *b)
bstr * bstr_dup_c (const char *cstr)
bstr * bstr_dup_ex (const bstr *b, size_t offset, size_t len)
bstr * bstr_dup_lower (const bstr *b)
bstr * bstr_dup_mem (const void *data, size_t len)
bstr * bstr_expand (bstr *b, size_t newsize)
void bstr_free (bstr *b)
int bstr_index_of (const bstr *bhaystack, const bstr *bneedle)
int bstr_index_of_nocase (const bstr *bhaystack, const bstr *bneedle)
int bstr_index_of_c (const bstr *bhaystack, const char *cneedle)
int bstr_index_of_c_nocase (const bstr *bhaystack, const char *cneedle)
int bstr_index_of_mem (const bstr *bhaystack, const void *data, size_t len)
int bstr_index_of_mem_nocase (const bstr *bhaystack, const void *data, size_t len)
int bstr_rchr (const bstr *b, int c)
bstr * bstr_to_lowercase (bstr *b)
int bstr_util_cmp_mem (const void *data1, size_t len1, const void *data2, size_t len2)
int bstr_util_cmp_mem_nocase (const void *data1, size_t len1, const void *data2, size_t len2)
int64_t bstr_util_mem_to_pint (const void *data, size_t len, int base, size_t *lastlen)
int bstr_util_mem_index_of_c (const void *data, size_t len, const char *cstr)
int bstr_util_mem_index_of_c_nocase (const void *data, size_t len, const char *cstr)
int bstr_util_mem_index_of_mem (const void *data1, size_t len1, const void *data2, size_t len2)
int bstr_util_mem_index_of_mem_nocase (const void *data1, size_t len1, const void *data2, size_t len2)
void bstr_util_mem_trim (unsigned char **data, size_t *len)
char * bstr_util_memdup_to_c (const void *data, size_t len)
char * bstr_util_strdup_to_c (const bstr *b)
bstr * bstr_wrap_c (const char *cstr)
bstr * bstr_wrap_mem (const void *data, size_t len)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file bstr.h.
Macro Definition Documentation
#define bstr_len (X) ((*(X)).len)
Definition at line 77 of file bstr.h.
Referenced by bstr_add(), bstr_add_mem(), bstr_add_mem_noex(), bstr_add_noex(), bstr_begins_with(), bstr_begins_with_mem(), bstr_begins_with_mem_nocase(), bstr_begins_with_nocase(), bstr_builder_to_str(), bstr_char_at(), bstr_char_at_end(), bstr_chop(), bstr_chr(), bstr_cmp(), bstr_cmp_c(), bstr_cmp_c_nocase(), bstr_cmp_mem(), bstr_cmp_mem_nocase(), bstr_cmp_nocase(), bstr_dup(), bstr_index_of(), bstr_index_of_mem(), bstr_index_of_mem_nocase(), bstr_index_of_nocase(), bstr_rchr(), bstr_to_lowercase(), bstr_util_strdup_to_c(), DetectEngineInspectHttpCookie(), DetectEngineInspectHttpHH(), DetectEngineInspectHttpHRH(), DetectEngineInspectHttpMethod(), DetectEngineInspectHttpRawUri(), DetectEngineInspectHttpRequestLine(), DetectEngineInspectHttpStatCode(), DetectEngineInspectHttpStatMsg(), DetectEngineInspectHttpUA(), DetectEngineInspectPacketUris(), DetectEngineRunHttpCookieMpm(), DetectEngineRunHttpHHMpm(), DetectEngineRunHttpHRHMpm(), DetectEngineRunHttpMethodMpm(), DetectEngineRunHttpRawUriMpm(), DetectEngineRunHttpStatCodeMpm(), DetectEngineRunHttpStatMsgMpm(), DetectEngineRunHttpUAMpm(), DetectUricontentInspectMpm(), fprint_bstr(), htp_base64_decode_bstr(), htp_ch_urlencoded_callback_request_line(), htp_connp_REQ_HEADERS(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_HEADERS(), htp_decode_path_inplace(), htp_mpart_part_handle_data(), htp_mpart_part_parse_c_d(), htp_mpartp_create(), htp_mpartp_find_boundary(), htp_mpartp_parse_header(), htp_normalize_parsed_uri(), htp_normalize_uri_path_inplace(), htp_parse_authorization_basic(), htp_parse_authorization_digest(), htp_parse_content_length(), htp_parse_cookies_v0(), htp_parse_ct_header(), htp_parse_hostport(), htp_parse_protocol(), htp_parse_request_line_generic_ex(), htp_parse_response_line_generic(), htp_parse_status(), htp_parse_uri(), htp_php_parameter_processor(), htp_process_request_header_generic(), htp_process_response_header_generic(), htp_transcode_bstr(), htp_treat_response_line_as_body(), htp_unparse_uri_noencode(), htp_urldecode_inplace_ex(), htp_utf8_decode_path_inplace(), htp_utf8_validate_path(), htp_validate_hostname(), HtpResponseBodyHandle(), HttpXFFGetIPFromTx(), SC_htp_parse_content_length(), and SCHTPGenerateNormalizedUri().
#define bstr_ptr (X) (((*(X)).realptr == NULL) ? ((unsigned char *)(X) + sizeof(bstr)) : (unsigned char *)(*(X)).realptr)
Definition at line 79 of file bstr.h.
Referenced by bstr_add(), bstr_add_mem(), bstr_add_mem_noex(), bstr_add_noex(), bstr_begins_with(), bstr_begins_with_mem(), bstr_begins_with_mem_nocase(), bstr_begins_with_nocase(), bstr_char_at(), bstr_char_at_end(), bstr_chr(), bstr_cmp(), bstr_cmp_c(), bstr_cmp_c_nocase(), bstr_cmp_mem(), bstr_cmp_mem_nocase(), bstr_cmp_nocase(), bstr_dup_ex(), bstr_dup_mem(), bstr_index_of(), bstr_index_of_mem(), bstr_index_of_mem_nocase(), bstr_index_of_nocase(), bstr_rchr(), bstr_to_lowercase(), bstr_util_strdup_to_c(), DetectEngineInspectHttpCookie(), DetectEngineInspectHttpHH(), DetectEngineInspectHttpHRH(), DetectEngineInspectHttpMethod(), DetectEngineInspectHttpRawUri(), DetectEngineInspectHttpRequestLine(), DetectEngineInspectHttpStatCode(), DetectEngineInspectHttpStatMsg(), DetectEngineInspectHttpUA(), DetectEngineInspectPacketUris(), DetectEngineRunHttpCookieMpm(), DetectEngineRunHttpHHMpm(), DetectEngineRunHttpHRHMpm(), DetectEngineRunHttpMethodMpm(), DetectEngineRunHttpRawUriMpm(), DetectEngineRunHttpStatCodeMpm(), DetectEngineRunHttpStatMsgMpm(), DetectEngineRunHttpUAMpm(), DetectUricontentInspectMpm(), fprint_bstr(), htp_base64_decode_bstr(), htp_ch_urlencoded_callback_request_line(), htp_connp_REQ_HEADERS(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_HEADERS(), htp_decode_path_inplace(), htp_extract_quoted_string_as_bstr(), htp_mpart_part_handle_data(), htp_mpart_part_parse_c_d(), htp_mpartp_create(), htp_mpartp_find_boundary(), htp_normalize_parsed_uri(), htp_normalize_uri_path_inplace(), htp_parse_authorization_basic(), htp_parse_authorization_digest(), htp_parse_content_length(), htp_parse_cookies_v0(), htp_parse_ct_header(), htp_parse_hostport(), htp_parse_protocol(), htp_parse_request_line_generic_ex(), htp_parse_response_line_generic(), htp_parse_status(), htp_parse_uri(), htp_php_parameter_processor(), htp_transcode_bstr(), htp_treat_response_line_as_body(), htp_urldecode_inplace_ex(), htp_utf8_decode_path_inplace(), htp_utf8_validate_path(), htp_validate_hostname(), HtpResponseBodyHandle(), HttpXFFGetIPFromTx(), and SC_htp_parse_content_length().
#define bstr_realptr (X) ((*(X)).realptr)
Definition at line 80 of file bstr.h.
Referenced by bstr_expand().
#define bstr_size (X) ((*(X)).size)
Definition at line 78 of file bstr.h.
Referenced by bstr_add_mem(), bstr_add_mem_noex(), and bstr_expand().
Typedef Documentation
typedef struct bstr_t bstr
Definition at line 46 of file bstr.h.
Function Documentation
bstr* bstr_add (bstr * bdestination, const bstr * bsource)
Append source bstring to destination bstring, growing destination if necessary. If the destination bstring is expanded, the pointer will change. You must replace the original destination pointer with the returned one. Destination is not changed on memory allocation failure.
Parameters
[in] bdestination
[in] bsource
Returns
Updated bstring, or NULL on memory allocation failure.
Definition at line 54 of file bstr.c.
References bstr_add_mem(), bstr_len, and bstr_ptr.
bstr* bstr_add_c (bstr * b, const char * cstr)
Append a NUL-terminated source to destination, growing destination if necessary. If the string is expanded, the pointer will change. You must replace the original destination pointer with the returned one. Destination is not changed on memory allocation failure.
Parameters
[in] b
[in] cstr
Returns
Updated bstring, or NULL on memory allocation failure.
Definition at line 58 of file bstr.c.
References bstr_add_mem().
Referenced by SCHTPGenerateNormalizedUri().
bstr* bstr_add_c_noex (bstr * b, const char * cstr)
Append as many bytes from the source to destination bstring. The destination storage will not be expanded if there is not enough space in it already to accommodate all of the data.
Parameters
[in] b
[in] cstr
Returns
The destination bstring.
Definition at line 62 of file bstr.c.
References bstr_add_mem_noex().
Referenced by htp_unparse_uri_noencode(), and SCHTPGenerateNormalizedUri().
bstr* bstr_add_mem (bstr * b, const void * data, size_t len)
Append a memory region to destination, growing destination if necessary. If the string is expanded, the pointer will change. You must replace the original destination pointer with the returned one. Destination is not changed on memory allocation failure.
Parameters
[in] b
[in] data
[in] len
Returns
Updated bstring, or NULL on memory allocation failure.
Definition at line 66 of file bstr.c.
References bstr_adjust_len(), bstr_expand(), bstr_len, bstr_ptr, and bstr_size.
Referenced by bstr_add(), bstr_add_c(), htp_connp_REQ_HEADERS(), htp_connp_RES_HEADERS(), and htp_mpart_part_handle_data().
bstr* bstr_add_mem_noex (bstr * b, const void * data, size_t len)
Append as many bytes from the source to destination bstring. The destination storage will not be expanded if there is not enough space in it already to accommodate all of the data.
Parameters
[in] b
[in] data
[in] len
Returns
The destination bstring.
Definition at line 81 of file bstr.c.
References bstr_adjust_len(), bstr_len, bstr_ptr, bstr_size, and len.
Referenced by bstr_add_c_noex(), bstr_add_noex(), htp_mpartp_parse_header(), htp_process_request_header_generic(), and htp_process_response_header_generic().
bstr* bstr_add_noex (bstr * bdestination, const bstr * bsource)
Append as many bytes from the source bstring to destination bstring. The destination storage will not be expanded if there is not enough space in it already to accommodate all of the data.
Parameters
[in] bdestination
[in] bsource
Returns
The destination bstring.
Definition at line 98 of file bstr.c.
References bstr_add_mem_noex(), bstr_len, and bstr_ptr.
Referenced by bstr_builder_to_str(), htp_mpartp_parse_header(), htp_process_request_header_generic(), htp_process_response_header_generic(), htp_unparse_uri_noencode(), and SCHTPGenerateNormalizedUri().
void bstr_adjust_len (bstr * b, size_t newlen)
Adjust bstring length. You will need to use this method whenever you work directly with the string contents, and end up changing its length by direct structure manipulation.
Parameters
[in] b
[in] newlen
Definition at line 102 of file bstr.c.
References bstr_t::len.
Referenced by bstr_add_mem(), bstr_add_mem_noex(), bstr_chop(), bstr_dup_ex(), bstr_dup_mem(), htp_connp_RES_BODY_DETERMINE(), htp_decode_path_inplace(), htp_extract_quoted_string_as_bstr(), htp_normalize_uri_path_inplace(), htp_urldecode_inplace_ex(), and htp_utf8_decode_path_inplace().
void bstr_adjust_realptr (bstr * b, void * newrealptr)
Change the external pointer used by bstring. You will need to use this function only if you're messing with bstr internals. Use with caution.
Parameters
[in] b
[in] newrealptr
Definition at line 106 of file bstr.c.
References bstr_t::realptr.
void bstr_adjust_size (bstr * b, size_t newsize)
Adjust bstring size. This does not change the size of the storage behind the bstring, just changes the field that keeps track of how many bytes there are in the storage. You will need to use this function only if you're messing with bstr internals. Use with caution.
Parameters
[in] b
[in] newsize
Definition at line 110 of file bstr.c.
References bstr_t::size.
Referenced by bstr_expand().
bstr* bstr_alloc (size_t size)
Allocate a zero-length bstring, reserving space for at least size bytes.
Parameters
[in] size
Returns
New string instance
Definition at line 43 of file bstr.c.
References len, bstr_t::len, bstr_t::realptr, and bstr_t::size.
Referenced by bstr_builder_to_str(), bstr_dup_ex(), bstr_dup_mem(), htp_extract_quoted_string_as_bstr(), htp_unparse_uri_noencode(), and SCHTPGenerateNormalizedUri().
int bstr_begins_with (const bstr * bhaystack, const bstr * bneedle)
Checks whether bstring begins with another bstring. Case sensitive.
Parameters
[in] bhaystack
[in] bneedle
Returns
1 if true, otherwise 0.
Definition at line 114 of file bstr.c.
References bstr_begins_with_mem(), bstr_len, and bstr_ptr.
int bstr_begins_with_c (const bstr * bhaystack, const char * cneedle)
Checks whether bstring begins with NUL-terminated string. Case sensitive.
Parameters
[in] bhaystack
[in] cneedle
Returns
1 if true, otherwise 0.
Definition at line 118 of file bstr.c.
References bstr_begins_with_mem().
Referenced by htp_ch_urlencoded_callback_request_headers(), and htp_mpartp_find_boundary().
int bstr_begins_with_c_nocase (const bstr * bhaystack, const char * cneedle)
Checks whether bstring begins with NUL-terminated string. Case insensitive.
Parameters
[in] bhaystack
[in] cneedle
Returns
1 if true, otherwise 0.
Definition at line 122 of file bstr.c.
References bstr_begins_with_mem_nocase().
Referenced by htp_parse_authorization().
int bstr_begins_with_mem (const bstr * bhaystack, const void * data, size_t len)
Checks whether the bstring begins with the given memory block. Case sensitive.
Parameters
[in] bhaystack
[in] data
[in] len
Returns
1 if true, otherwise 0.
Definition at line 130 of file bstr.c.
References bstr_len, bstr_ptr, and data.
Referenced by bstr_begins_with(), and bstr_begins_with_c().
int bstr_begins_with_mem_nocase (const bstr * bhaystack, const void * data, size_t len)
Checks whether bstring begins with memory block. Case insensitive.
Parameters
[in] bhaystack
[in] data
[in] len
Returns
1 if true, otherwise 0.
Definition at line 151 of file bstr.c.
References bstr_len, bstr_ptr, and data.
Referenced by bstr_begins_with_c_nocase(), and bstr_begins_with_nocase().
int bstr_begins_with_nocase (const bstr * bhaystack, const bstr * cneedle)
Checks whether bstring begins with another bstring. Case insensitive.
Parameters
[in] bhaystack
[in] cneedle
Returns
1 if true, otherwise 0.
Definition at line 126 of file bstr.c.
References bstr_begins_with_mem_nocase(), bstr_len, and bstr_ptr.
int bstr_char_at (const bstr * b, size_t pos)
Return the byte at the given position.
Parameters
[in] b
[in] pos
Returns
The byte at the given location, or -1 if the position is out of range.
Definition at line 172 of file bstr.c.
References bstr_len, bstr_ptr, data, and len.
int bstr_char_at_end (const bstr * b, size_t pos)
Return the byte at the given position, counting from the end of the string (e.g., byte at position 0 is the last byte in the string.)
Parameters
[in] b
[in] pos
Returns
The byte at the given location, or -1 if the position is out of range.
Definition at line 180 of file bstr.c.
References bstr_len, bstr_ptr, data, and len.
Referenced by htp_normalize_hostname_inplace().
void bstr_chop (bstr * b)
Remove the last byte from bstring, assuming it contains at least one byte. This function will not reduce the storage that backs the string, only the amount of data used.
Parameters
[in] b
Definition at line 188 of file bstr.c.
References bstr_adjust_len(), and bstr_len.
Referenced by htp_normalize_hostname_inplace().
int bstr_chr (const bstr * b, int c)
Return the first position of the provided byte.
Parameters
[in] b
[in] c
Returns
The first position of the byte, or -1 if it could not be found
Definition at line 194 of file bstr.c.
References bstr_len, bstr_ptr, data, and len.
int bstr_cmp (const bstr * b1, const bstr * b2)
Case-sensitive comparison of two bstrings.
Parameters
[in] b1
[in] b2
Returns
Zero on string match, 1 if b1 is greater than b2, and -1 if b2 is greater than b1.
Definition at line 210 of file bstr.c.
References bstr_len, bstr_ptr, and bstr_util_cmp_mem().
int bstr_cmp_c (const bstr * b, const char * cstr)
Case-sensitive comparison of a bstring and a NUL-terminated string.
Parameters
[in] b
[in] cstr
Returns
Zero on string match, 1 if b is greater than cstr, and -1 if cstr is greater than b.
Definition at line 214 of file bstr.c.
References bstr_len, bstr_ptr, and bstr_util_cmp_mem().
Referenced by htp_convert_method_to_number().
int bstr_cmp_c_nocase (const bstr * b, const char * cstr)
Case-insensitive comparison of a bstring with a NUL-terminated string.
Parameters
[in] b
[in] cstr
Returns
Zero on string match, 1 if b is greater than cstr, and -1 if cstr is greater than b.
Definition at line 218 of file bstr.c.
References bstr_len, bstr_ptr, and bstr_util_cmp_mem_nocase().
Referenced by htp_connp_RES_BODY_DETERMINE(), htp_mpartp_parse_header(), htp_process_response_header_generic(), htp_table_get_c(), and htp_tx_state_response_headers().
int bstr_cmp_mem (const bstr * b, const void * data, size_t len)
Performs a case-sensitive comparison of a bstring with a memory region.
Parameters
[in] b
[in] data
[in] len
Returns
Zero ona match, 1 if b is greater than data, and -1 if data is greater than b.
Definition at line 222 of file bstr.c.
References bstr_len, bstr_ptr, and bstr_util_cmp_mem().
int bstr_cmp_mem_nocase (const bstr * b, const void * data, size_t len)
Performs a case-insensitive comparison of a bstring with a memory region.
Parameters
[in] b
[in] data
[in] len
Returns
Zero ona match, 1 if b is greater than data, and -1 if data is greater than b.
Definition at line 226 of file bstr.c.
References bstr_len, bstr_ptr, and bstr_util_cmp_mem_nocase().
Referenced by htp_table_get_mem(), and htp_tx_req_get_param_ex().
int bstr_cmp_nocase (const bstr * b1, const bstr * b2)
Case-insensitive comparison two bstrings.
Parameters
[in] b1
[in] b2
Returns
Zero on string match, 1 if b1 is greater than b2, and -1 if b2 is greater than b1.
Definition at line 230 of file bstr.c.
References bstr_len, bstr_ptr, and bstr_util_cmp_mem_nocase().
Referenced by htp_table_get().
bstr* bstr_dup (const bstr * b)
Create a new bstring by copying the provided bstring.
Parameters
[in] b
Returns
New bstring, or NULL if memory allocation failed.
Definition at line 234 of file bstr.c.
References bstr_dup_ex(), and bstr_len.
Referenced by bstr_dup_lower(), htp_normalize_parsed_uri(), htp_php_parameter_processor(), htp_table_add(), and SCHTPGenerateNormalizedUri().
bstr* bstr_dup_c (const char * cstr)
Create a new bstring by copying the provided NUL-terminated string.
Parameters
[in] cstr
Returns
New bstring, or NULL if memory allocation failed.
Definition at line 238 of file bstr.c.
References bstr_dup_mem().
Referenced by bstr_builder_append_c(), htp_parse_request_header_generic(), and htp_parse_single_cookie_v0().
bstr* bstr_dup_ex (const bstr * b, size_t offset, size_t len)
Create a new bstring by copying a part of the provided bstring.
Parameters
[in] b
[in] offset
[in] len
Returns
New bstring, or NULL if memory allocation failed.
Definition at line 242 of file bstr.c.
References bstr_adjust_len(), bstr_alloc(), and bstr_ptr.
Referenced by bstr_dup(), htp_parse_authorization_basic(), and htp_parse_ct_header().
bstr* bstr_dup_lower (const bstr * b)
Create a copy of the provided bstring, then convert it to lowercase.
Parameters
[in] b
Returns
New bstring, or NULL if memory allocation failed
Definition at line 250 of file bstr.c.
References bstr_dup(), and bstr_to_lowercase().
Referenced by htp_connp_RES_BODY_DETERMINE(), and htp_normalize_parsed_uri().
bstr* bstr_dup_mem (const void * data, size_t len)
Create a new bstring by copying the provided memory region.
Parameters
[in] data
[in] len
Returns
New bstring, or NULL if memory allocation failed
Definition at line 254 of file bstr.c.
References bstr_adjust_len(), bstr_alloc(), and bstr_ptr.
Referenced by bstr_builder_append_mem(), bstr_dup_c(), htp_base64_decode_mem(), htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_REQ_HEADERS(), htp_connp_REQ_LINE_complete(), htp_connp_RES_HEADERS(), htp_connp_RES_LINE(), htp_mpart_part_handle_data(), htp_mpart_part_parse_c_d(), htp_mpartp_find_boundary(), htp_mpartp_parse_header(), htp_parse_hostport(), htp_parse_request_header_generic(), htp_parse_request_line_generic_ex(), htp_parse_response_header_generic(), htp_parse_response_line_generic(), htp_parse_single_cookie_v0(), htp_parse_uri(), htp_php_parameter_processor(), and htp_transcode_bstr().
bstr* bstr_expand (bstr * b, size_t newsize)
Expand internal bstring storage to support at least newsize bytes. The storage is not expanded if the current size is equal or greater to newsize. Because realloc is used underneath, the old pointer to bstring may no longer be valid after this function completes successfully.
Parameters
[in] b
[in] newsize
Returns
Updated string instance, or NULL if memory allocation failed or if attempt was made to "expand" the bstring to a smaller size.
Definition at line 262 of file bstr.c.
References bstr_adjust_size(), bstr_realptr, and bstr_size.
Referenced by bstr_add_mem(), htp_mpartp_parse_header(), htp_process_request_header_generic(), and htp_process_response_header_generic().
void bstr_free (bstr * b)
Deallocate the supplied bstring instance and set it to NULL. Allows NULL on input.
Parameters
[in] b
Definition at line 281 of file bstr.c.
Referenced by bstr_builder_clear(), bstr_builder_destroy(), htp_ch_multipart_callback_request_headers(), htp_connp_destroy(), htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_REQ_HEADERS(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_HEADERS(), htp_connp_RES_LINE(), htp_mpart_part_destroy(), htp_mpart_part_handle_data(), htp_mpartp_create(), htp_mpartp_destroy(), htp_mpartp_parse_header(), htp_parse_authorization_basic(), htp_parse_hostport(), htp_parse_request_header_generic(), htp_parse_response_header_generic(), htp_parse_single_cookie_v0(), htp_php_parameter_processor(), htp_process_request_header_generic(), htp_process_response_header_generic(), htp_table_add(), htp_table_clear(), htp_transcode_params(), htp_tx_destroy_incomplete(), htp_tx_req_set_header(), htp_tx_req_set_headers_clear(), htp_tx_res_set_header(), htp_tx_res_set_headers_clear(), htp_tx_res_set_status_message(), htp_tx_state_request_complete_partial(), htp_uri_free(), htp_urlenp_destroy(), and SCHTPGenerateNormalizedUri().
int bstr_index_of (const bstr * bhaystack, const bstr * bneedle)
Find the needle in the haystack.
Parameters
[in] bhaystack
[in] bneedle
Returns
Position of the match, or -1 if the needle could not be found.
Definition at line 286 of file bstr.c.
References bstr_index_of_mem(), bstr_len, and bstr_ptr.
int bstr_index_of_c (const bstr * bhaystack, const char * cneedle)
Find the needle in the haystack, with the needle being a NUL-terminated string.
Parameters
[in] bhaystack
[in] cneedle
Returns
Position of the match, or -1 if the needle could not be found.
Definition at line 290 of file bstr.c.
References bstr_index_of_mem().
Referenced by htp_mpart_part_parse_c_d(), htp_parse_authorization_basic(), and htp_parse_authorization_digest().
int bstr_index_of_c_nocase (const bstr * bhaystack, const char * cneedle)
Find the needle in the haystack, with the needle being a NUL-terminated string. Ignore case differences.
Parameters
[in] bhaystack
[in] cneedle
Returns
Position of the match, or -1 if the needle could not be found.
Definition at line 294 of file bstr.c.
References bstr_index_of_mem_nocase().
Referenced by htp_connp_RES_BODY_DETERMINE(), and htp_mpartp_find_boundary().
int bstr_index_of_mem (const bstr * bhaystack, const void * data, size_t len)
Find the needle in the haystack, with the needle being a memory region.
Parameters
[in] bhaystack
[in] data
[in] len
Returns
Position of the match, or -1 if the needle could not be found.
Definition at line 298 of file bstr.c.
References bstr_len, bstr_ptr, and bstr_util_mem_index_of_mem().
Referenced by bstr_index_of(), and bstr_index_of_c().
int bstr_index_of_mem_nocase (const bstr * bhaystack, const void * data, size_t len)
Find the needle in the haystack, with the needle being a memory region. Ignore case differences.
Parameters
[in] bhaystack
[in] data
[in] len
Returns
Position of the match, or -1 if the needle could not be found.
Definition at line 302 of file bstr.c.
References bstr_len, bstr_ptr, and bstr_util_mem_index_of_mem_nocase().
Referenced by bstr_index_of_c_nocase(), and bstr_index_of_nocase().
int bstr_index_of_nocase (const bstr * bhaystack, const bstr * bneedle)
Find the needle in the haystack, ignoring case differences.
Parameters
[in] bhaystack
[in] bneedle
Returns
Position of the match, or -1 if the needle could not be found.
Definition at line 306 of file bstr.c.
References bstr_index_of_mem_nocase(), bstr_len, and bstr_ptr.
int bstr_rchr (const bstr * b, int c)
Return the last position of a character (byte).
Parameters
[in] b
[in] c
Returns
The last position of the character, or -1 if it could not be found.
Definition at line 310 of file bstr.c.
References bstr_len, bstr_ptr, data, and len.
bstr* bstr_to_lowercase (bstr * b)
Convert bstring to lowercase. This function converts the supplied string, it does not create a new string.
Parameters
[in] b
Returns
The same bstring received on input
Definition at line 326 of file bstr.c.
References bstr_len, bstr_ptr, data, and len.
Referenced by bstr_dup_lower(), htp_normalize_hostname_inplace(), htp_parse_ct_header(), and htp_parse_hostport().
int bstr_util_cmp_mem (const void * data1, size_t len1, const void * data2, size_t len2)
Case-sensitive comparison of two memory regions.
Parameters
[in] data1
[in] len1
[in] data2
[in] len2
Returns
Zero if the memory regions are identical, 1 if data1 is greater than data2, and -1 if data2 is greater than data1.
Definition at line 341 of file bstr.c.
Referenced by bstr_cmp(), bstr_cmp_c(), and bstr_cmp_mem().
int bstr_util_cmp_mem_nocase (const void * data1, size_t len1, const void * data2, size_t len2)
Case-insensitive comparison of two memory regions.
Parameters
[in] data1
[in] len1
[in] data2
[in] len2
Returns
Zero if the memory regions are identical, 1 if data1 is greater than data2, and -1 if data2 is greater than data1.
Definition at line 366 of file bstr.c.
Referenced by bstr_cmp_c_nocase(), bstr_cmp_mem_nocase(), and bstr_cmp_nocase().
int bstr_util_mem_index_of_c (const void * data, size_t len, const char * cstr)
Searches a memory block for the given NUL-terminated string. Case sensitive.
Parameters
[in] data
[in] len
[in] cstr
Returns
Index of the first location of the needle on success, or -1 if the needle was not found.
Definition at line 453 of file bstr.c.
References bstr_util_mem_index_of_mem().
int bstr_util_mem_index_of_c_nocase (const void * data, size_t len, const char * cstr)
Searches a memory block for the given NUL-terminated string. Case insensitive.
Parameters
[in] data
[in] len
[in] cstr
Returns
Index of the first location of the needle on success, or -1 if the needle was not found.
Definition at line 457 of file bstr.c.
References bstr_util_mem_index_of_mem_nocase().
int bstr_util_mem_index_of_mem (const void * data1, size_t len1, const void * data2, size_t len2)
Searches the haystack memory block for the needle memory block. Case sensitive.
Parameters
data1
len1
data2
len2
Returns
Index of the first location of the needle on success, or -1 if the needle was not found.
Definition at line 461 of file bstr.c.
Referenced by bstr_index_of_mem(), and bstr_util_mem_index_of_c().
int bstr_util_mem_index_of_mem_nocase (const void * data1, size_t len1, const void * data2, size_t len2)
Searches the haystack memory block for the needle memory block. Case sensitive.
Parameters
data1
len1
data2
len2
Returns
Index of the first location of the needle on success, or -1 if the needle was not found.
Definition at line 484 of file bstr.c.
Referenced by bstr_index_of_mem_nocase(), and bstr_util_mem_index_of_c_nocase().
int64_t bstr_util_mem_to_pint (const void * data, size_t len, int base, size_t * lastlen)
Convert contents of a memory region to a positive integer.
Parameters
[in] data
[in] len
[in] base The desired number base.
[in] lastlen Points to the first unused byte in the region
Returns
If the conversion was successful, this function returns the number. When the conversion fails, -1 will be returned when not one valid digit was found, and -2 will be returned if an overflow occurred.
Definition at line 391 of file bstr.c.
References data, and len.
Referenced by htp_parse_positive_integer_whitespace().
void bstr_util_mem_trim (unsigned char ** data, size_t * len)
Removes whitespace from the beginning and the end of a memory region. The data itself is not modified; this function only adjusts the provided pointers.
Parameters
[in,out] data
[in,out] len
Definition at line 507 of file bstr.c.
References data, and len.
Referenced by htp_parse_hostport().
char* bstr_util_memdup_to_c (const void * data, size_t len)
Take the provided memory region, allocate a new memory buffer, and construct a NUL-terminated string, replacing each NUL byte with "\0" (two bytes). The caller is responsible to keep track of the allocated memory area and free it once it is no longer needed.
Parameters
[in] data
[in] len
Returns
The newly created NUL-terminated string, or NULL in case of memory allocation failure.
Definition at line 526 of file bstr.c.
References data, and len.
Referenced by bstr_util_strdup_to_c().
char* bstr_util_strdup_to_c (const bstr * b)
Create a new NUL-terminated string out of the provided bstring. If NUL bytes are contained in the bstring, each will be replaced with "\0" (two characters). The caller is responsible to keep track of the allocated memory area and free it once it is no longer needed.
Parameters
[in] b
Returns
The newly created NUL-terminated string, or NULL in case of memory allocation failure.
Definition at line 558 of file bstr.c.
References bstr_len, bstr_ptr, and bstr_util_memdup_to_c().
bstr* bstr_wrap_c (const char * cstr)
Create a new bstring from the provided NUL-terminated string and without copying the data. The caller must ensure that the input string continues to point to a valid memory location for as long as the bstring is used.
Parameters
[in] cstr
Returns
New bstring, or NULL on memory allocation failure.
Definition at line 563 of file bstr.c.
References bstr_wrap_mem().
bstr* bstr_wrap_mem (const void * data, size_t len)
Create a new bstring from the provided memory buffer without copying the data. The caller must ensure that the buffer remains valid for as long as the bstring is used.
Parameters
[in] data
[in] len
Returns
New bstring, or NULL on memory allocation failure.
Definition at line 567 of file bstr.c.
References len, bstr_t::len, bstr_t::realptr, and bstr_t::size.
Referenced by bstr_wrap_c().