suricata: src/conf-yaml-loader.h File Reference
conf-yaml-loader.h File Reference
Functions
int ConfYamlLoadFile (const char *)
Load configuration from a YAML file.
int ConfYamlLoadString (const char *, size_t)
Load configuration from a YAML string.
int ConfYamlLoadFileWithPrefix (const char *filename, const char *prefix)
Load configuration from a YAML file, insert in tree at 'prefix'.
void ConfYamlRegisterTests (void)
Detailed Description
Author
Endace Technology Limited - Jason Ish jason.nosp@m..ish.nosp@m.@enda.nosp@m.ce.c.nosp@m.om
Definition in file conf-yaml-loader.h.
Function Documentation
int ConfYamlLoadFile (const char * filename)
Load configuration from a YAML file.
This function will load a configuration file. On failure -1 will be returned and it is suggested that the program then exit. Any errors while loading the configuration file will have already been logged.
Parameters
filename Filename of configuration file to load.
Return values
0 on success, -1 on failure.
Definition at line 388 of file conf-yaml-loader.c.
References ConfGetRootNode(), SC_ERR_FATAL, and SCLogError.
Referenced by ListAppLayerProtocols(), ListKeywords(), and LoadYamlConfig().
int ConfYamlLoadFileWithPrefix (const char * filename, const char * prefix)
Load configuration from a YAML file, insert in tree at 'prefix'.
This function will load a configuration file and insert it into the config tree at 'prefix'. This means that if this is called with prefix "abc" and the file contains a parameter "def", it will be loaded as "abc.def".
Parameters
filename Filename of configuration file to load.
prefix Name prefix to use.
Return values
0 on success, -1 on failure.
Definition at line 464 of file conf-yaml-loader.c.
References ConfGetNode(), ConfSet(), SC_ERR_FATAL, and SCLogError.
Referenced by DetectEngineMultiTenantSetup(), and DetectEngineReload().
int ConfYamlLoadString (const char * , size_t)
Load configuration from a YAML string.
Definition at line 433 of file conf-yaml-loader.c.
References ConfGetRootNode().
void ConfYamlRegisterTests (void)
Definition at line 936 of file conf-yaml-loader.c.
Referenced by RunUnittests().