suricata: src/counters.h File Reference
counters.h File Reference
Data Structures
struct StatsCounter_
Container to hold the counter variable.
struct StatsPublicThreadContext_
Stats Context for a ThreadVars instance.
struct StatsLocalCounter_
Storage for local counters, with a link to the public counter used for syncs.
struct StatsPrivateThreadContext_
used to hold the private version of the counters registered
Macros
#define StatsSyncCounters(tv) StatsUpdateCounterArray(&(tv)->perf_private_ctx, &(tv)->perf_public_ctx); \
#define StatsSyncCountersIfSignalled(tv)
Typedefs
typedef struct StatsCounter_ StatsCounter
Container to hold the counter variable.
typedef struct
StatsPublicThreadContext_ StatsPublicThreadContext
Stats Context for a ThreadVars instance.
typedef struct StatsLocalCounter_ StatsLocalCounter
Storage for local counters, with a link to the public counter used for syncs.
typedef struct
StatsPrivateThreadContext_ StatsPrivateThreadContext
used to hold the private version of the counters registered
Functions
void StatsInit (void)
Initializes the perf counter api. Things are hard coded currently. More work to be done when we implement multiple interfaces.
void StatsSetupPostConfig (void)
void StatsSpawnThreads (void)
Spawns the wakeup, and the management thread used by the stats api.
void StatsRegisterTests (void)
void StatsReleaseResources (void)
Releases the resources alloted by the Stats API.
uint16_t StatsRegisterCounter (char *, struct ThreadVars_ *)
Registers a normal, unqualified counter.
uint16_t StatsRegisterAvgCounter (char *, struct ThreadVars_ *)
Registers a counter, whose value holds the average of all the values assigned to it.
uint16_t StatsRegisterMaxCounter (char *, struct ThreadVars_ *)
Registers a counter, whose value holds the maximum of all the values assigned to it.
uint16_t StatsRegisterGlobalCounter (char *cname, uint64_t(*Func)(void))
Registers a counter, which represents a global value.
void StatsAddUI64 (struct ThreadVars_ *, uint16_t, uint64_t)
Adds a value of type uint64_t to the local counter.
void StatsSetUI64 (struct ThreadVars_ *, uint16_t, uint64_t)
Sets a value of type double to the local counter.
void StatsIncr (struct ThreadVars_ *, uint16_t)
Increments the local counter.
int StatsUpdateCounterArray (StatsPrivateThreadContext *, StatsPublicThreadContext *)
Syncs the counter array with the global counter variables.
uint64_t StatsGetLocalCounterValue (struct ThreadVars_ *, uint16_t)
Get the value of the local copy of the counter that hold this id.
int StatsSetupPrivate (struct ThreadVars_ *)
void StatsThreadCleanup (struct ThreadVars_ *)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file counters.h.
Macro Definition Documentation
#define StatsSyncCounters (tv) StatsUpdateCounterArray(&(tv)->perf_private_ctx, &(tv)->perf_public_ctx); \
Definition at line 132 of file counters.h.
Referenced by TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
#define StatsSyncCountersIfSignalled (tv)
Value:
do {                                                                        \
        if ((tv)->perf_public_ctx.perf_flag == 1) {                             \
            StatsUpdateCounterArray(&(tv)->perf_private_ctx,                   \
                                     &(tv)->perf_public_ctx);                   \
        }                                                                       \
    } while (0)
Definition at line 135 of file counters.h.
Referenced by NapatechStreamLoop(), ReceiveAFPLoop(), ReceiveErfDagLoop(), ReceiveIPFWLoop(), ReceiveNFQLoop(), ReceivePcapFileLoop(), ReceivePcapLoop(), ReceivePfringLoop(), TmqhInputFlow(), TmqhInputRingBufferMrSw(), TmqhInputRingBufferSrMw(), TmqhInputRingBufferSrSw(), and TmqhInputSimple().
Typedef Documentation
typedef struct StatsCounter_ StatsCounter
Container to hold the counter variable.
typedef struct StatsLocalCounter_ StatsLocalCounter
Storage for local counters, with a link to the public counter used for syncs.
typedef struct StatsPrivateThreadContext_ StatsPrivateThreadContext
used to hold the private version of the counters registered
typedef struct StatsPublicThreadContext_ StatsPublicThreadContext
Stats Context for a ThreadVars instance.
Function Documentation
void StatsAddUI64 (ThreadVars * tv, uint16_t id, uint64_t x)
Adds a value of type uint64_t to the local counter.
Parameters
id ID of the counter as set by the API
pca Counter array that holds the local counter for this TM
x Value to add to this local counter
Definition at line 130 of file counters.c.
References BUG_ON, StatsPrivateThreadContext_::head, StatsPrivateThreadContext_::initialized, ThreadVars_::perf_private_ctx, StatsPrivateThreadContext_::size, StatsLocalCounter_::updates, and StatsLocalCounter_::value.
Referenced by DecodeUpdatePacketCounters(), and SigMatchSignatures().
uint64_t StatsGetLocalCounterValue (ThreadVars * tv, uint16_t id)
Get the value of the local copy of the counter that hold this id.
Parameters
tv threadvars
id The counter id.
Return values
0 on success.
-1 on error.
Definition at line 1161 of file counters.c.
References BUG_ON, StatsPrivateThreadContext_::head, ThreadVars_::perf_private_ctx, StatsPrivateThreadContext_::size, and StatsLocalCounter_::value.
Referenced by ReceiveAFPThreadExitStats(), ReceiveErfDagThreadExitStats(), and ReceivePfringThreadExitStats().
void StatsIncr (ThreadVars * tv, uint16_t id)
Increments the local counter.
Parameters
id Index of the counter in the counter array
pca Counter array that holds the local counters for this TM
Definition at line 151 of file counters.c.
References BUG_ON, StatsPrivateThreadContext_::head, StatsPrivateThreadContext_::initialized, ThreadVars_::perf_private_ctx, StatsPrivateThreadContext_::size, StatsLocalCounter_::updates, and StatsLocalCounter_::value.
Referenced by CaptureStatsUpdate(), DecodeAFP(), DecodeERSPAN(), DecodeEthernet(), DecodeGRE(), DecodeICMPV4(), DecodeICMPV6(), DecodeIPV4(), DecodeIPV6(), DecodeMPLS(), DecodeNull(), DecodePfring(), DecodePPP(), DecodePPPOEDiscovery(), DecodePPPOESession(), DecodeRaw(), DecodeSCTP(), DecodeSll(), DecodeTCP(), DecodeTeredo(), DecodeUDP(), DecodeUpdatePacketCounters(), DecodeVLAN(), Defrag(), DoHandleGap(), PacketDecodeFinalize(), StreamTcp(), StreamTcpGetSegment(), StreamTcpPacket(), StreamTcpPseudoPacketCreateStreamEndPacket(), StreamTcpReassembleAppLayer(), and StreamTcpReassembleHandleSegmentHandleData().
void StatsInit (void)
Initializes the perf counter api. Things are hard coded currently. More work to be done when we implement multiple interfaces.
Definition at line 773 of file counters.c.
References BUG_ON, StatsGlobalContext_::global_counter_ctx, SC_ERR_FATAL, SCLogError, and SCMalloc.
Referenced by main().
uint16_t StatsRegisterAvgCounter (char * name, struct ThreadVars_ * tv)
Registers a counter, whose value holds the average of all the values assigned to it.
Parameters
name Name of the counter, to be registered
tv Pointer to the ThreadVars instance for which the counter would be registered
Return values
id Counter id for the newly registered counter, or the already present counter
Definition at line 871 of file counters.c.
References ThreadVars_::name, ThreadVars_::perf_public_ctx, STATS_TYPE_AVERAGE, and ThreadVars_::thread_group_name.
Referenced by DecodeRegisterPerfCounters(), and DetectEngineThreadCtxInit().
uint16_t StatsRegisterCounter (char * name, struct ThreadVars_ * tv)
Registers a normal, unqualified counter.
Parameters
name Name of the counter, to be registered
tv Pointer to the ThreadVars instance for which the counter would be registered
Return values
id Counter id for the newly registered counter, or the already present counter
Definition at line 850 of file counters.c.
References ThreadVars_::name, ThreadVars_::perf_public_ctx, STATS_TYPE_NORMAL, and ThreadVars_::thread_group_name.
Referenced by CaptureStatsSetup(), DecodeRegisterPerfCounters(), DetectEngineThreadCtxInit(), ReceiveAFPThreadInit(), ReceiveErfDagThreadInit(), ReceivePcapThreadInit(), ReceivePfringThreadInit(), and StreamTcpThreadInit().
uint16_t StatsRegisterGlobalCounter (char * name, uint64_t(*)(void) Func)
Registers a counter, which represents a global value.
Parameters
name Name of the counter, to be registered
Func Function Pointer returning a uint64_t
Return values
id Counter id for the newly registered counter, or the already present counter
Definition at line 911 of file counters.c.
References BUG_ON, StatsGlobalContext_::global_counter_ctx, and STATS_TYPE_FUNC.
Referenced by AppLayerRegisterGlobalCounters(), FlowManagerThreadSpawn(), StreamTcpInitConfig(), and StreamTcpReassembleInit().
uint16_t StatsRegisterMaxCounter (char * name, struct ThreadVars_ * tv)
Registers a counter, whose value holds the maximum of all the values assigned to it.
Parameters
name Name of the counter, to be registered
tv Pointer to the ThreadVars instance for which the counter would be registered
Return values
the counter id for the newly registered counter, or the already present counter
Definition at line 892 of file counters.c.
References ThreadVars_::name, ThreadVars_::perf_public_ctx, STATS_TYPE_MAXIMUM, and ThreadVars_::thread_group_name.
Referenced by DecodeRegisterPerfCounters().
void StatsRegisterTests (void)
Definition at line 1485 of file counters.c.
Referenced by RunUnittests().
void StatsReleaseResources (void)
Releases the resources alloted by the Stats API.
Definition at line 1173 of file counters.c.
Referenced by main().
void StatsSetUI64 (ThreadVars * tv, uint16_t id, uint64_t x)
Sets a value of type double to the local counter.
Parameters
id Index of the local counter in the counter array
pca Pointer to the StatsPrivateThreadContext
x The value to set for the counter
Definition at line 173 of file counters.c.
References BUG_ON, StatsPrivateThreadContext_::head, StatsPrivateThreadContext_::initialized, StatsLocalCounter_::pc, ThreadVars_::perf_private_ctx, StatsPrivateThreadContext_::size, STATS_TYPE_MAXIMUM, STATS_TYPE_NORMAL, StatsCounter_::type, StatsLocalCounter_::updates, and StatsLocalCounter_::value.
Referenced by DecodeUpdatePacketCounters().
void StatsSetupPostConfig (void)
Definition at line 785 of file counters.c.
Referenced by main().
int StatsSetupPrivate (struct ThreadVars_ *)
Definition at line 1112 of file counters.c.
References ThreadVars_::name.
Referenced by TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
void StatsSpawnThreads (void)
Spawns the wakeup, and the management thread used by the stats api.
The threads use the condition variable in the thread vars to control their wait loops to make sure the main thread can quickly kill them.
Definition at line 796 of file counters.c.
References SC_ERR_THREAD_CREATE, SC_ERR_THREAD_SPAWN, SCEnter, SCLogError, SCReturn, TmThreadCreateMgmtThread(), and TmThreadSpawn().
Referenced by main().
void StatsThreadCleanup (struct ThreadVars_ *)
Definition at line 1219 of file counters.c.
References ThreadVars_::perf_private_ctx, ThreadVars_::perf_public_ctx, and StatsReleasePrivateThreadContext().
Referenced by TmThreadFree().
int StatsUpdateCounterArray (StatsPrivateThreadContext * pca, StatsPublicThreadContext * pctx)
Syncs the counter array with the global counter variables.
Parameters
pca Pointer to the StatsPrivateThreadContext
pctx Pointer the the tv's StatsPublicThreadContext
Return values
0 on success
-1 on error
Definition at line 1129 of file counters.c.
References StatsPrivateThreadContext_::head, StatsPublicThreadContext_::m, StatsPublicThreadContext_::perf_flag, SCLogDebug, SCMutexLock, SCMutexUnlock, and StatsPrivateThreadContext_::size.