suricata: src/counters.c File Reference
counters.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "counters.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "conf.h"
#include "util-time.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "util-privs.h"
#include "util-signal.h"
#include "unix-manager.h"
#include "output.h"
Data Structures
struct StatsThreadStore_
per thread store of counters
struct StatsGlobalContext_
Holds the output interface context for the counter api.
struct CountersIdType_
Macros
#define STATS_WUT_TTS 3
#define STATS_MGMTT_TTS 8
Typedefs
typedef struct StatsThreadStore_ StatsThreadStore
per thread store of counters
typedef struct StatsGlobalContext_ StatsGlobalContext
Holds the output interface context for the counter api.
typedef struct CountersIdType_ CountersIdType
Enumerations
enum {
STATS_TYPE_NORMAL = 1, STATS_TYPE_AVERAGE = 2, STATS_TYPE_MAXIMUM = 3, STATS_TYPE_FUNC = 4,
STATS_TYPE_MAX = 5
}
Different kinds of qualifier that can be used to modify the behaviour of the counter to be registered.
Functions
void StatsReleaseCounters (StatsCounter *head)
Releases counters.
void StatsAddUI64 (ThreadVars *tv, uint16_t id, uint64_t x)
Adds a value of type uint64_t to the local counter.
void StatsIncr (ThreadVars *tv, uint16_t id)
Increments the local counter.
void StatsSetUI64 (ThreadVars *tv, uint16_t id, uint64_t x)
Sets a value of type double to the local counter.
void StatsInit (void)
Initializes the perf counter api. Things are hard coded currently. More work to be done when we implement multiple interfaces.
void StatsSetupPostConfig (void)
void StatsSpawnThreads (void)
Spawns the wakeup, and the management thread used by the stats api.
uint16_t StatsRegisterCounter (char *name, struct ThreadVars_ *tv)
Registers a normal, unqualified counter.
uint16_t StatsRegisterAvgCounter (char *name, struct ThreadVars_ *tv)
Registers a counter, whose value holds the average of all the values assigned to it.
uint16_t StatsRegisterMaxCounter (char *name, struct ThreadVars_ *tv)
Registers a counter, whose value holds the maximum of all the values assigned to it.
uint16_t StatsRegisterGlobalCounter (char *name, uint64_t(*Func)(void))
Registers a counter, which represents a global value.
uint32_t CountersIdHashFunc (HashTable *ht, void *data, uint16_t datalen)
char CountersIdHashCompareFunc (void *data1, uint16_t datalen1, void *data2, uint16_t datalen2)
void CountersIdHashFreeFunc (void *data)
int StatsSetupPrivate (ThreadVars *tv)
int StatsUpdateCounterArray (StatsPrivateThreadContext *pca, StatsPublicThreadContext *pctx)
Syncs the counter array with the global counter variables.
uint64_t StatsGetLocalCounterValue (ThreadVars *tv, uint16_t id)
Get the value of the local copy of the counter that hold this id.
void StatsReleaseResources ()
Releases the resources alloted by the Stats API.
void StatsReleasePrivateThreadContext (StatsPrivateThreadContext *pca)
Releases the StatsPrivateThreadContext allocated by the user, for storing and updating local counter values.
void StatsThreadCleanup (ThreadVars *tv)
void StatsRegisterTests ()
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Engine stats API
Definition in file counters.c.
Macro Definition Documentation
#define STATS_MGMTT_TTS 8
Definition at line 45 of file counters.c.
#define STATS_WUT_TTS 3
Definition at line 42 of file counters.c.
Typedef Documentation
typedef struct CountersIdType_ CountersIdType
typedef struct StatsGlobalContext_ StatsGlobalContext
Holds the output interface context for the counter api.
typedef struct StatsThreadStore_ StatsThreadStore
per thread store of counters
Enumeration Type Documentation
anonymous enum
Different kinds of qualifier that can be used to modify the behaviour of the counter to be registered.
Enumerator
STATS_TYPE_NORMAL
STATS_TYPE_AVERAGE
STATS_TYPE_MAXIMUM
STATS_TYPE_FUNC
STATS_TYPE_MAX
Definition at line 51 of file counters.c.
Function Documentation
char CountersIdHashCompareFunc (void * data1, uint16_t datalen1, void * data2, uint16_t datalen2)
Definition at line 947 of file counters.c.
References CountersIdType_::string.
void CountersIdHashFreeFunc (void * data)
Definition at line 971 of file counters.c.
References SCFree.
uint32_t CountersIdHashFunc (HashTable * ht, void * data, uint16_t datalen)
Definition at line 931 of file counters.c.
References HashTable_::array_size, len, and CountersIdType_::string.
void StatsAddUI64 (ThreadVars * tv, uint16_t id, uint64_t x)
Adds a value of type uint64_t to the local counter.
Parameters
id ID of the counter as set by the API
pca Counter array that holds the local counter for this TM
x Value to add to this local counter
Definition at line 130 of file counters.c.
References BUG_ON, StatsPrivateThreadContext_::head, StatsPrivateThreadContext_::initialized, ThreadVars_::perf_private_ctx, StatsPrivateThreadContext_::size, StatsLocalCounter_::updates, and StatsLocalCounter_::value.
Referenced by DecodeUpdatePacketCounters(), and SigMatchSignatures().
uint64_t StatsGetLocalCounterValue (ThreadVars * tv, uint16_t id)
Get the value of the local copy of the counter that hold this id.
Parameters
tv threadvars
id The counter id.
Return values
0 on success.
-1 on error.
Definition at line 1161 of file counters.c.
References BUG_ON, StatsPrivateThreadContext_::head, ThreadVars_::perf_private_ctx, StatsPrivateThreadContext_::size, and StatsLocalCounter_::value.
Referenced by ReceiveAFPThreadExitStats(), ReceiveErfDagThreadExitStats(), and ReceivePfringThreadExitStats().
void StatsIncr (ThreadVars * tv, uint16_t id)
Increments the local counter.
Parameters
id Index of the counter in the counter array
pca Counter array that holds the local counters for this TM
Definition at line 151 of file counters.c.
References BUG_ON, StatsPrivateThreadContext_::head, StatsPrivateThreadContext_::initialized, ThreadVars_::perf_private_ctx, StatsPrivateThreadContext_::size, StatsLocalCounter_::updates, and StatsLocalCounter_::value.
Referenced by CaptureStatsUpdate(), DecodeAFP(), DecodeERSPAN(), DecodeEthernet(), DecodeGRE(), DecodeICMPV4(), DecodeICMPV6(), DecodeIPV4(), DecodeIPV6(), DecodeMPLS(), DecodeNull(), DecodePfring(), DecodePPP(), DecodePPPOEDiscovery(), DecodePPPOESession(), DecodeRaw(), DecodeSCTP(), DecodeSll(), DecodeTCP(), DecodeTeredo(), DecodeUDP(), DecodeUpdatePacketCounters(), DecodeVLAN(), Defrag(), DoHandleGap(), PacketDecodeFinalize(), StreamTcp(), StreamTcpGetSegment(), StreamTcpPacket(), StreamTcpPseudoPacketCreateStreamEndPacket(), StreamTcpReassembleAppLayer(), and StreamTcpReassembleHandleSegmentHandleData().
void StatsInit (void)
Initializes the perf counter api. Things are hard coded currently. More work to be done when we implement multiple interfaces.
Definition at line 773 of file counters.c.
References BUG_ON, StatsGlobalContext_::global_counter_ctx, SC_ERR_FATAL, SCLogError, and SCMalloc.
Referenced by main().
uint16_t StatsRegisterAvgCounter (char * name, struct ThreadVars_ * tv)
Registers a counter, whose value holds the average of all the values assigned to it.
Parameters
name Name of the counter, to be registered
tv Pointer to the ThreadVars instance for which the counter would be registered
Return values
id Counter id for the newly registered counter, or the already present counter
Definition at line 871 of file counters.c.
References ThreadVars_::name, ThreadVars_::perf_public_ctx, STATS_TYPE_AVERAGE, and ThreadVars_::thread_group_name.
Referenced by DecodeRegisterPerfCounters(), and DetectEngineThreadCtxInit().
uint16_t StatsRegisterCounter (char * name, struct ThreadVars_ * tv)
Registers a normal, unqualified counter.
Parameters
name Name of the counter, to be registered
tv Pointer to the ThreadVars instance for which the counter would be registered
Return values
id Counter id for the newly registered counter, or the already present counter
Definition at line 850 of file counters.c.
References ThreadVars_::name, ThreadVars_::perf_public_ctx, STATS_TYPE_NORMAL, and ThreadVars_::thread_group_name.
Referenced by CaptureStatsSetup(), DecodeRegisterPerfCounters(), DetectEngineThreadCtxInit(), ReceiveAFPThreadInit(), ReceiveErfDagThreadInit(), ReceivePcapThreadInit(), ReceivePfringThreadInit(), and StreamTcpThreadInit().
uint16_t StatsRegisterGlobalCounter (char * name, uint64_t(*)(void) Func)
Registers a counter, which represents a global value.
Parameters
name Name of the counter, to be registered
Func Function Pointer returning a uint64_t
Return values
id Counter id for the newly registered counter, or the already present counter
Definition at line 911 of file counters.c.
References BUG_ON, StatsGlobalContext_::global_counter_ctx, and STATS_TYPE_FUNC.
Referenced by AppLayerRegisterGlobalCounters(), FlowManagerThreadSpawn(), StreamTcpInitConfig(), and StreamTcpReassembleInit().
uint16_t StatsRegisterMaxCounter (char * name, struct ThreadVars_ * tv)
Registers a counter, whose value holds the maximum of all the values assigned to it.
Parameters
name Name of the counter, to be registered
tv Pointer to the ThreadVars instance for which the counter would be registered
Return values
the counter id for the newly registered counter, or the already present counter
Definition at line 892 of file counters.c.
References ThreadVars_::name, ThreadVars_::perf_public_ctx, STATS_TYPE_MAXIMUM, and ThreadVars_::thread_group_name.
Referenced by DecodeRegisterPerfCounters().
void StatsRegisterTests (void)
Definition at line 1485 of file counters.c.
Referenced by RunUnittests().
void StatsReleaseCounters (StatsCounter * head)
Releases counters.
Parameters
head Pointer to the head of the list of perf counters that have to be freed
Definition at line 1186 of file counters.c.
References head, and StatsCounter_::next.
void StatsReleasePrivateThreadContext (StatsPrivateThreadContext * pca)
Releases the StatsPrivateThreadContext allocated by the user, for storing and updating local counter values.
Parameters
pca Pointer to the StatsPrivateThreadContext
Definition at line 1205 of file counters.c.
References StatsPrivateThreadContext_::head, StatsPrivateThreadContext_::initialized, SCFree, and StatsPrivateThreadContext_::size.
Referenced by StatsThreadCleanup().
void StatsReleaseResources (void)
Releases the resources alloted by the Stats API.
Definition at line 1173 of file counters.c.
Referenced by main().
void StatsSetUI64 (ThreadVars * tv, uint16_t id, uint64_t x)
Sets a value of type double to the local counter.
Parameters
id Index of the local counter in the counter array
pca Pointer to the StatsPrivateThreadContext
x The value to set for the counter
Definition at line 173 of file counters.c.
References BUG_ON, StatsPrivateThreadContext_::head, StatsPrivateThreadContext_::initialized, StatsLocalCounter_::pc, ThreadVars_::perf_private_ctx, StatsPrivateThreadContext_::size, STATS_TYPE_MAXIMUM, STATS_TYPE_NORMAL, StatsCounter_::type, StatsLocalCounter_::updates, and StatsLocalCounter_::value.
Referenced by DecodeUpdatePacketCounters().
void StatsSetupPostConfig (void)
Definition at line 785 of file counters.c.
Referenced by main().
int StatsSetupPrivate (ThreadVars * tv)
Definition at line 1112 of file counters.c.
References ThreadVars_::name.
Referenced by TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
void StatsSpawnThreads (void)
Spawns the wakeup, and the management thread used by the stats api.
The threads use the condition variable in the thread vars to control their wait loops to make sure the main thread can quickly kill them.
Definition at line 796 of file counters.c.
References SC_ERR_THREAD_CREATE, SC_ERR_THREAD_SPAWN, SCEnter, SCLogError, SCReturn, TmThreadCreateMgmtThread(), and TmThreadSpawn().
Referenced by main().
void StatsThreadCleanup (ThreadVars * tv)
Definition at line 1219 of file counters.c.
References ThreadVars_::perf_private_ctx, ThreadVars_::perf_public_ctx, and StatsReleasePrivateThreadContext().
Referenced by TmThreadFree().
int StatsUpdateCounterArray (StatsPrivateThreadContext * pca, StatsPublicThreadContext * pctx)
Syncs the counter array with the global counter variables.
Parameters
pca Pointer to the StatsPrivateThreadContext
pctx Pointer the the tv's StatsPublicThreadContext
Return values
0 on success
-1 on error
Definition at line 1129 of file counters.c.
References StatsPrivateThreadContext_::head, StatsPublicThreadContext_::m, StatsPublicThreadContext_::perf_flag, SCLogDebug, SCMutexLock, SCMutexUnlock, and StatsPrivateThreadContext_::size.