suricata: src/decode-icmpv4.c File Reference
decode-icmpv4.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-events.h"
#include "decode-ipv4.h"
#include "decode-icmpv4.h"
#include "flow.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
#include "util-print.h"
Functions
void DecodePartialIPV4 (Packet *p, uint8_t *partial_packet, uint16_t len)
int DecodeICMPV4 (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
Main ICMPv4 decoding function.
void DecodeICMPV4RegisterTests (void)
Registers ICMPV4 unit test.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decode ICMPv4
Definition in file decode-icmpv4.c.
Function Documentation
int DecodeICMPV4 (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Main ICMPv4 decoding function.
DecodeICMPV4
Definition at line 154 of file decode-icmpv4.c.
References Packet_::code, DecodeThreadVars_::counter_icmpv4, DecodePartialIPV4(), ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, FlowHandlePacket(), ICMPV4_DEST_UNREACH_IS_VALID, ICMPV4_HEADER_LEN, ICMPV4_HEADER_PKT_OFFSET, ICMPV4_PKT_TOO_SMALL, ICMPV4_UNKNOWN_CODE, ICMPV4_UNKNOWN_TYPE, Packet_::icmpv4h, Packet_::icmpv4vars, ICMPV4ExtHdr_::id, ICMPV4Vars_::id, Packet_::payload, Packet_::payload_len, Packet_::proto, SCLogDebug, ICMPV4ExtHdr_::seq, ICMPV4Vars_::seq, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, and Packet_::type.
Referenced by DecodeIPV4().
void DecodeICMPV4RegisterTests (void)
Registers ICMPV4 unit test.
Definition at line 766 of file decode-icmpv4.c.
Referenced by RunUnittests().
void DecodePartialIPV4 (Packet * p, uint8_t * partial_packet, uint16_t len)
Note, this is the IP header, plus a bit of the original packet, not the whole thing!
Check the sizes, the header must fit at least
Check the embedded version
Check the embedded version
We need to fill icmpv4vars
Get the IP address from the contained packet
Definition at line 50 of file decode-icmpv4.c.
References ICMPV4Vars_::emb_dport, ICMPV4Vars_::emb_icmpv4h, ICMPV4Vars_::emb_ip4_dst, ICMPV4Vars_::emb_ip4_hlen, ICMPV4Vars_::emb_ip4_proto, ICMPV4Vars_::emb_ip4_src, ICMPV4Vars_::emb_ipv4h, ICMPV4Vars_::emb_sport, ICMPV4Vars_::emb_tcph, ICMPV4Vars_::emb_udph, ENGINE_SET_INVALID_EVENT, ICMPV4_IPV4_TRUNC_PKT, ICMPV4_IPV4_UNKNOWN_VER, Packet_::icmpv4vars, IPV4_GET_RAW_HLEN, IPV4_GET_RAW_IPDST, IPV4_GET_RAW_IPID, IPV4_GET_RAW_IPPROTO, IPV4_GET_RAW_IPSRC, IPV4_GET_RAW_VER, IPV4_HEADER_LEN, PrintInet(), SCLogDebug, TCP_HEADER_LEN, and UDP_HEADER_LEN.
Referenced by DecodeICMPV4().