suricata: src/decode-ethernet.c File Reference
decode-ethernet.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-ethernet.h"
#include "decode-events.h"
#include "util-unittest.h"
#include "util-debug.h"
Functions
int DecodeEthernet (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
void DecodeEthernetRegisterTests (void)
Registers Ethernet unit tests.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decode Ethernet
Definition in file decode-ethernet.c.
Function Documentation
int DecodeEthernet (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Definition at line 41 of file decode-ethernet.c.
References DecodeThreadVars_::counter_eth, DecodeIPV4(), DecodeIPV6(), DecodeMPLS(), DecodePPPOEDiscovery(), DecodePPPOESession(), DecodeVLAN(), ENGINE_SET_INVALID_EVENT, ETHERNET_HEADER_LEN, ETHERNET_PKT_TOO_SMALL, ETHERNET_TYPE_8021QINQ, ETHERNET_TYPE_IP, ETHERNET_TYPE_IPV6, ETHERNET_TYPE_MPLS_MULTICAST, ETHERNET_TYPE_MPLS_UNICAST, ETHERNET_TYPE_PPPOE_DISC, ETHERNET_TYPE_PPPOE_SESS, ETHERNET_TYPE_VLAN, Packet_::ethh, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by DecodeAFP(), DecodeErfDag(), DecodeErfFile(), DecodeERSPAN(), DecodeMPLS(), DecodePcap(), DecodePfring(), DecodeTunnel(), NapatechDecode(), and ReceivePcapFileThreadInit().
void DecodeEthernetRegisterTests (void)
Registers Ethernet unit tests.
Todo:
More Ethernet tests
Definition at line 144 of file decode-ethernet.c.