suricata: src/decode-raw.c File Reference
decode-raw.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-raw.h"
#include "decode-events.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "pkt-var.h"
#include "util-profiling.h"
#include "host.h"
Functions
int DecodeRaw (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
void DecodeRawRegisterTests (void)
Registers Raw unit tests.
Detailed Description
Author
William Metcalf willi.nosp@m.am.m.nosp@m.etcal.nosp@m.f@gm.nosp@m.ail.c.nosp@m.om
Decode RAW
Definition in file decode-raw.c.
Function Documentation
int DecodeRaw (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Definition at line 46 of file decode-raw.c.
References DecodeThreadVars_::counter_raw, DecodeIPV4(), DecodeIPV6(), ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, GET_PKT_DATA, GET_PKT_LEN, IP_GET_RAW_VER, IPRAW_INVALID_IPV, IPV4_HEADER_LEN, IPV4_PKT_TOO_SMALL, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by DecodeAFP(), DecodePcap(), and ReceivePcapFileThreadInit().
void DecodeRawRegisterTests (void)
Registers Raw unit tests.
Todo:
More Raw tests
Definition at line 222 of file decode-raw.c.
Referenced by RunUnittests().