suricata: src/decode-vlan.c File Reference
decode-vlan.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-vlan.h"
#include "decode-events.h"
#include "flow.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "pkt-var.h"
#include "util-profiling.h"
#include "host.h"
Functions
int DecodeVLAN (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
uint16_t DecodeVLANGetId (const Packet *p, uint8_t layer)
void DecodeVLANRegisterTests (void)
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Decode 802.1q
Definition in file decode-vlan.c.
Function Documentation
int DecodeVLAN (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Definition at line 59 of file decode-vlan.c.
References DecodeThreadVars_::counter_vlan, DecodeThreadVars_::counter_vlan_qinq, DecodeIPV4(), DecodeIPV6(), DecodePPPOEDiscovery(), DecodePPPOESession(), DecodeVLAN(), ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, ETHERNET_TYPE_8021AD, ETHERNET_TYPE_IP, ETHERNET_TYPE_IPV6, ETHERNET_TYPE_PPPOE_DISC, ETHERNET_TYPE_PPPOE_SESS, ETHERNET_TYPE_VLAN, GET_VLAN_CFI, GET_VLAN_ID, GET_VLAN_PRIORITY, GET_VLAN_PROTO, proto, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, DecodeThreadVars_::vlan_disabled, VLAN_HEADER_LEN, VLAN_HEADER_TOO_MANY_LAYERS, VLAN_HEADER_TOO_SMALL, Packet_::vlan_id, Packet_::vlan_idx, VLAN_UNKNOWN_TYPE, and Packet_::vlanh.
Referenced by DecodeEthernet(), DecodeSll(), DecodeTunnel(), and DecodeVLAN().
uint16_t DecodeVLANGetId (const Packet * p, uint8_t layer)
Definition at line 129 of file decode-vlan.c.
References GET_VLAN_ID, unlikely, Packet_::vlan_id, Packet_::vlan_idx, and Packet_::vlanh.
void DecodeVLANRegisterTests (void)
Definition at line 268 of file decode-vlan.c.
Referenced by RunUnittests().