suricata: src/decode-sctp.c File Reference
decode-sctp.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-sctp.h"
#include "decode-events.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "util-optimize.h"
#include "flow.h"
Functions
int DecodeSCTP (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Decode SCTP
Definition in file decode-sctp.c.
Function Documentation
int DecodeSCTP (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Definition at line 62 of file decode-sctp.c.
References DecodeThreadVars_::counter_sctp, FlowHandlePacket(), SCLogDebug, SCTP_GET_DST_PORT, SCTP_GET_SRC_PORT, Packet_::sctph, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by DecodeIPV4(), and DecodeIPV6().