suricata: src/decode-udp.c File Reference
decode-udp.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-udp.h"
#include "decode-teredo.h"
#include "decode-events.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "flow.h"
#include "app-layer.h"
Functions
int DecodeUDP (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
void DecodeUDPV4RegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decode UDP
Definition in file decode-udp.c.
Function Documentation
int DecodeUDP (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Definition at line 73 of file decode-udp.c.
References DecodeThreadVars_::app_tctx, AppLayerHandleUdp(), DecodeThreadVars_::counter_udp, DecodeTeredo(), Packet_::flow, FlowHandlePacket(), Packet_::payload, Packet_::payload_len, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, UDP_GET_DST_PORT, UDP_GET_SRC_PORT, UDP_HEADER_LEN, Packet_::udph, and unlikely.
Referenced by DecodeIPV4(), DecodeIPV6(), and DecodeTEMPLATE().
void DecodeUDPV4RegisterTests (void)
Definition at line 203 of file decode-udp.c.
Referenced by RunUnittests().