suricata: src/decode-erspan.c File Reference
decode-erspan.c File Reference
Packet decoding
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "decode-events.h"
#include "decode-erspan.h"
#include "util-unittest.h"
#include "util-debug.h"
Functions
int DecodeERSPAN (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
Function to decode ERSPAN packets.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decodes ERSPAN
Definition in file decode-erspan.c.
Function Documentation
int DecodeERSPAN (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Function to decode ERSPAN packets.
Definition at line 46 of file decode-erspan.c.
References DecodeThreadVars_::counter_erspan, DecodeEthernet(), ENGINE_SET_EVENT, ERSPAN_HEADER_TOO_SMALL, ERSPAN_TOO_MANY_VLAN_LAYERS, ERSPAN_UNSUPPORTED_VERSION, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, version, DecodeThreadVars_::vlan_disabled, Packet_::vlan_id, and Packet_::vlan_idx.
Referenced by DecodeTunnel().