suricata: src/decode-tcp.c File Reference
decode-tcp.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-tcp.h"
#include "decode-events.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "util-optimize.h"
#include "flow.h"
#include "util-profiling.h"
#include "pkt-var.h"
#include "host.h"
Functions
int DecodeTCP (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
void DecodeTCPRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decode TCP
Definition in file decode-tcp.c.
Function Documentation
int DecodeTCP (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Definition at line 187 of file decode-tcp.c.
References DecodeThreadVars_::counter_tcp, FlowHandlePacket(), GET_TCP_DST_PORT, GET_TCP_SRC_PORT, TCPVars_::mss, TCPVars_::sack, TCPVars_::sackok, SCLogDebug, StatsIncr(), TCP_GET_HLEN, Packet_::tcph, Packet_::tcpvars, TM_ECODE_FAILED, TM_ECODE_OK, TCPVars_::ts, unlikely, and TCPVars_::ws.
Referenced by DecodeIPV4(), and DecodeIPV6().
void DecodeTCPRegisterTests (void)
Definition at line 502 of file decode-tcp.c.
Referenced by RunUnittests().