suricata: src/decode-icmpv6.c File Reference
decode-icmpv6.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode-icmpv6.h"
#include "decode.h"
#include "decode-tcp.h"
#include "decode-sctp.h"
#include "decode-udp.h"
#include "decode-events.h"
#include "util-unittest.h"
#include "flow.h"
#include "util-debug.h"
#include "util-print.h"
#include "pkt-var.h"
#include "util-profiling.h"
#include "host.h"
Functions
void DecodePartialIPV6 (Packet *p, uint8_t *partial_packet, uint16_t len)
Get variables and do some checks of the embedded IPV6 packet.
int DecodeICMPV6 (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
Decode ICMPV6 packets and fill the Packet with the decoded info.
void DecodeICMPV6RegisterTests (void)
Registers ICMPV6 unit tests.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decode ICMPv6
Definition in file decode-icmpv6.c.
Function Documentation
int DecodeICMPV6 (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Decode ICMPV6 packets and fill the Packet with the decoded info.
Parameters
tv Pointer to the thread variables
dtv Pointer to the decode thread variables
p Pointer to the packet we are filling
pkt Pointer to the raw packet buffer
len the len of the rest of the packet not processed yet
pq the packet queue were this packet go
Return values
void No return value
Definition at line 167 of file decode-icmpv6.c.
References ICMPV6Hdr_::code, Packet_::code, DecodeThreadVars_::counter_icmpv6, DecodePartialIPV6(), ENGINE_ISSET_EVENT, ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, ICMPV6Vars_::error_ptr, FlowHandlePacket(), ICMP6_DST_UNREACH, ICMP6_DST_UNREACH_REJECTROUTE, ICMP6_ECHO_REPLY, ICMP6_ECHO_REQUEST, ICMP6_PACKET_TOO_BIG, ICMP6_PARAM_PROB, ICMP6_PARAMPROB_OPTION, ICMP6_TIME_EXCEED_REASSEMBLY, ICMP6_TIME_EXCEEDED, ICMPV6_GET_CODE, ICMPV6_GET_ERROR_PTR, ICMPV6_GET_MTU, ICMPV6_GET_TYPE, ICMPV6_HEADER_LEN, ICMPV6_MLD_MESSAGE_WITH_INVALID_HL, ICMPV6_PKT_TOO_SMALL, ICMPV6_UNKNOWN_CODE, ICMPV6_UNKNOWN_TYPE, ICMPV6Hdr_::icmpv6b, Packet_::icmpv6h, ICMPV6Hdr_::icmpv6i, Packet_::icmpv6vars, ICMPV6Info_::id, ICMPV6Vars_::id, IPV6_GET_HLIM, MLD_LISTENER_QUERY, MLD_LISTENER_REDUCTION, MLD_LISTENER_REPORT, ICMPV6Vars_::mtu, ND_NEIGHBOR_ADVERT, ND_NEIGHBOR_SOLICIT, ND_REDIRECT, ND_ROUTER_ADVERT, ND_ROUTER_SOLICIT, Packet_::payload, Packet_::payload_len, Packet_::proto, SCLogDebug, ICMPV6Info_::seq, ICMPV6Vars_::seq, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, ICMPV6Hdr_::type, and Packet_::type.
Referenced by DecodeIPV6().
void DecodeICMPV6RegisterTests (void)
Registers ICMPV6 unit tests.
Todo:
More ICMPv6 tests
Definition at line 1595 of file decode-icmpv6.c.
Referenced by RunUnittests().
void DecodePartialIPV6 (Packet * p, uint8_t * partial_packet, uint16_t len)
Get variables and do some checks of the embedded IPV6 packet.
Parameters
p Pointer to the packet we are filling
partial_packet Pointer to the raw packet buffer
len the len of the rest of the packet not processed yet
Return values
void No return value
Check the sizes, the header must fit at least
Check the embedded version
We need to fill icmpv6vars
Get the IP6 address
Get protocol and ports inside the embedded ipv6 packet and set the pointers
Definition at line 59 of file decode-icmpv6.c.
References ICMPV6Vars_::emb_dport, ICMPV6Vars_::emb_icmpv6h, ICMPV6Vars_::emb_ip6_dst, ICMPV6Vars_::emb_ip6_proto_next, ICMPV6Vars_::emb_ip6_src, ICMPV6Vars_::emb_ipv6h, ICMPV6Vars_::emb_sport, ICMPV6Vars_::emb_tcph, ICMPV6Vars_::emb_udph, ENGINE_SET_INVALID_EVENT, ICMPV6_IPV6_TRUNC_PKT, ICMPV6_IPV6_UNKNOWN_VER, Packet_::icmpv6vars, IPV6_GET_RAW_CLASS, IPV6_GET_RAW_FLOW, IPV6_GET_RAW_HLIM, IPV6_GET_RAW_NH, IPV6_GET_RAW_PLEN, IPV6_HEADER_LEN, PrintInet(), SCLogDebug, TCP_HEADER_LEN, and UDP_HEADER_LEN.
Referenced by DecodeICMPV6().