suricata: src/decode-ipv4.c File Reference
decode-ipv4.c File Reference
Packet decoding
#include "suricata-common.h"
#include "packet-queue.h"
#include "decode.h"
#include "decode-ipv4.h"
#include "decode-events.h"
#include "defrag.h"
#include "pkt-var.h"
#include "host.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "util-optimize.h"
#include "util-print.h"
#include "util-profiling.h"
Functions
int DecodeIPV4 (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
void DecodeIPV4RegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Brian Rectanus brect.nosp@m.anu@.nosp@m.gmail.nosp@m..com
Decode IPv4
Definition in file decode-ipv4.c.
Function Documentation
int DecodeIPV4 (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Definition at line 520 of file decode-ipv4.c.
References DecodeThreadVars_::counter_ipv4, DECODE_TUNNEL_IPV6, DecodeGRE(), DecodeICMPV4(), DecodeSCTP(), DecodeTCP(), DecodeUDP(), Defrag(), ENGINE_SET_INVALID_EVENT, Packet_::flags, GET_IPV4_DST_ADDR_PTR, GET_IPV4_SRC_ADDR_PTR, Packet_::ip4h, IPPROTO_GRE, IPV4_GET_DF, IPV4_GET_HLEN, IPV4_GET_IPID, IPV4_GET_IPLEN, IPV4_GET_IPOFFSET, IPV4_GET_IPPROTO, IPV4_GET_MF, IPV4_GET_RF, IPV4_WITH_ICMPV6, PacketEnqueue(), PacketTunnelPktSetup(), PKT_IS_FRAGMENT, PKT_SET_SRC, PKT_SRC_DECODER_IPV4, PPP_VJ_UCOMP, Packet_::ppph, PrintInet(), Packet_::proto, SCLogDebug, SCLogDebugEnabled(), StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by DecodeEthernet(), DecodeIPFW(), DecodeMPLS(), DecodeNFQ(), DecodeNull(), DecodePPP(), DecodePPPOESession(), DecodeRaw(), DecodeSll(), DecodeTunnel(), and DecodeVLAN().
void DecodeIPV4RegisterTests (void)
Definition at line 1871 of file decode-ipv4.c.
Referenced by RunUnittests().