suricata: src/decode-teredo.c File Reference
decode-teredo.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-ipv6.h"
#include "util-debug.h"
#define TEREDO_ORIG_INDICATION_LENGTH 8
int DecodeTeredo (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq)
Function to decode Teredo packets.
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Decode Teredo Tunneling protocol.
This implementation is based upon RFC 4380: http://www.ietf.org/rfc/rfc4380.txt
Definition in file decode-teredo.c.
Macro Definition Documentation
#define TEREDO_ORIG_INDICATION_LENGTH 8
Definition at line 40 of file decode-teredo.c.
Referenced by DecodeTeredo().
Function Documentation
int DecodeTeredo (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq)
Function to decode Teredo packets.
Return values
TM_ECODE_FAILED if packet is not a Teredo packet, TM_ECODE_OK if it is
Definition at line 47 of file decode-teredo.c.
References DecodeThreadVars_::counter_teredo, DECODE_TUNNEL_IPV6, IP_GET_RAW_VER, IPV6_GET_RAW_PLEN, IPV6_HEADER_LEN, PacketEnqueue(), PacketTunnelPktSetup(), PKT_SET_SRC, PKT_SRC_DECODER_TEREDO, StatsIncr(), TEREDO_ORIG_INDICATION_LENGTH, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by DecodeUDP().