suricata: src/defrag.c File Reference
defrag.c File Reference
#include "suricata-common.h"
#include "queue.h"
#include "suricata.h"
#include "threads.h"
#include "conf.h"
#include "decode-ipv6.h"
#include "util-hashlist.h"
#include "util-pool.h"
#include "util-time.h"
#include "util-print.h"
#include "util-debug.h"
#include "util-fix_checksum.h"
#include "util-random.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "util-host-os-info.h"
#include "defrag.h"
#include "defrag-hash.h"
#include "defrag-queue.h"
#include "defrag-config.h"
#include "tmqh-packetpool.h"
#include "decode.h"
Macros
#define DEFAULT_DEFRAG_HASH_SIZE 0xffff
#define DEFAULT_DEFRAG_POOL_SIZE 0xffff
#define TIMEOUT_DEFAULT 60
#define TIMEOUT_MAX (60 * 60 * 24)
#define TIMEOUT_MIN 1
Enumerations
enum defrag_policies {
DEFRAG_POLICY_FIRST = 1, DEFRAG_POLICY_LAST, DEFRAG_POLICY_BSD, DEFRAG_POLICY_BSD_RIGHT,
DEFRAG_POLICY_LINUX, DEFRAG_POLICY_WINDOWS, DEFRAG_POLICY_SOLARIS, DEFRAG_POLICY_DEFAULT = DEFRAG_POLICY_BSD
}
Functions
void DefragTrackerFreeFrags (DefragTracker *tracker)
Free all frags associated with a tracker.
uint8_t DefragGetOsPolicy (Packet *p)
Get the defrag policy based on the destination address of the packet.
Packet * Defrag (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, PacketQueue *pq)
Entry point for IPv4 and IPv6 fragments.
void DefragInit (void)
void DefragDestroy (void)
void DefragRegisterTests (void)
Detailed Description
Author
Endace Technology Limited, Jason Ish jason.nosp@m..ish.nosp@m.@enda.nosp@m.ce.c.nosp@m.om
Defragmentation module. References:
RFC 815
OpenBSD PF's IP normalizaton (pf_norm.c)
Todo:
pool for frag packet storage
policy bsd-right
profile hash function
log anomalies
Definition in file defrag.c.
Macro Definition Documentation
#define DEFAULT_DEFRAG_HASH_SIZE 0xffff
Definition at line 65 of file defrag.c.
Referenced by DefragInit().
#define DEFAULT_DEFRAG_POOL_SIZE 0xffff
Definition at line 66 of file defrag.c.
#define TIMEOUT_DEFAULT 60
Default timeout (in seconds) before a defragmentation tracker will be released.
Definition at line 72 of file defrag.c.
#define TIMEOUT_MAX (60 * 60 * 24)
Maximum allowed timeout, 24 hours.
Definition at line 77 of file defrag.c.
#define TIMEOUT_MIN 1
Minimum allowed timeout, 1 second.
Definition at line 82 of file defrag.c.
Enumeration Type Documentation
enum defrag_policies
Fragment reassembly policies.
Enumerator
DEFRAG_POLICY_FIRST
DEFRAG_POLICY_LAST
DEFRAG_POLICY_BSD
DEFRAG_POLICY_BSD_RIGHT
DEFRAG_POLICY_LINUX
DEFRAG_POLICY_WINDOWS
DEFRAG_POLICY_SOLARIS
DEFRAG_POLICY_DEFAULT
Definition at line 85 of file defrag.c.
Function Documentation
Packet* Defrag (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, PacketQueue * pq)
Entry point for IPv4 and IPv6 fragments.
Parameters
tv ThreadVars for the calling decoder.
p The packet fragment.
Return values
A new Packet resembling the re-assembled packet if the most recent fragment allowed the packet to be re-assembled, otherwise NULL is returned.
Definition at line 908 of file defrag.c.
References af, DecodeThreadVars_::counter_defrag_ipv4_fragments, DecodeThreadVars_::counter_defrag_ipv6_fragments, DefragTrackerRelease(), IPV4_GET_IPOFFSET, IPV4_GET_MF, IPV6_EXTHDR_GET_FH_FLAG, IPV6_EXTHDR_GET_FH_OFFSET, PKT_IS_IPV4, PKT_IS_IPV6, and StatsIncr().
Referenced by DecodeIPV4(), and DecodeIPV6().
void DefragDestroy (void)
Definition at line 976 of file defrag.c.
References DefragHashShutdown().
Referenced by main().
uint8_t DefragGetOsPolicy (Packet * p)
Get the defrag policy based on the destination address of the packet.
Parameters
p The packet used to get the destination address.
Return values
The defrag policy to use.
Definition at line 829 of file defrag.c.
References DEFRAG_POLICY_BSD, DEFRAG_POLICY_BSD_RIGHT, DEFRAG_POLICY_FIRST, DEFRAG_POLICY_LAST, DEFRAG_POLICY_LINUX, DEFRAG_POLICY_SOLARIS, DEFRAG_POLICY_WINDOWS, GET_IPV4_DST_ADDR_PTR, GET_IPV6_DST_ADDR, OS_POLICY_BSD, OS_POLICY_BSD_RIGHT, OS_POLICY_FIRST, OS_POLICY_HPUX10, OS_POLICY_HPUX11, OS_POLICY_IRIX, OS_POLICY_LAST, OS_POLICY_LINUX, OS_POLICY_MACOS, OS_POLICY_OLD_LINUX, OS_POLICY_OLD_SOLARIS, OS_POLICY_SOLARIS, OS_POLICY_VISTA, OS_POLICY_WINDOWS, OS_POLICY_WINDOWS2K3, PKT_IS_IPV4, PKT_IS_IPV6, SCHInfoGetIPv4HostOSFlavour(), and SCHInfoGetIPv6HostOSFlavour().
void DefragInit (void)
Definition at line 954 of file defrag.c.
References ConfGetInt(), DEFAULT_DEFRAG_HASH_SIZE, DefragInitConfig(), DefragPolicyLoadFromConfig(), DefragSetDefaultTimeout(), FALSE, SC_ERR_MEM_ALLOC, SCLogError, and DefragContext_::timeout.
void DefragRegisterTests (void)
Definition at line 2535 of file defrag.c.
Referenced by RunUnittests().
void DefragTrackerFreeFrags (DefragTracker * tracker)
Free all frags associated with a tracker.
Definition at line 150 of file defrag.c.
References DefragContext_::frag_pool, DefragContext_::frag_pool_lock, next, PoolReturn(), SCMutexLock, SCMutexUnlock, TAILQ_FIRST, and TAILQ_REMOVE.
Referenced by DefragTrackerClearMemory().