suricata: src/defrag-hash.h File Reference
defrag-hash.h File Reference
#include "decode.h"
#include "defrag.h"
Data Structures
struct DefragTrackerHashRow_
struct DefragConfig_
Macros
#define DRLOCK_MUTEX
#define DRLOCK_TYPE SCMutex
#define DRLOCK_INIT(fb) SCMutexInit(&(fb)->lock, NULL)
#define DRLOCK_DESTROY(fb) SCMutexDestroy(&(fb)->lock)
#define DRLOCK_LOCK(fb) SCMutexLock(&(fb)->lock)
#define DRLOCK_TRYLOCK(fb) SCMutexTrylock(&(fb)->lock)
#define DRLOCK_UNLOCK(fb) SCMutexUnlock(&(fb)->lock)
#define DEFRAG_VERBOSE 0
#define DEFRAG_QUIET 1
#define DEFRAG_CHECK_MEMCAP(size) ((((uint64_t)SC_ATOMIC_GET(defrag_memuse) + (uint64_t)(size)) <= defrag_config.memcap))
check if a memory alloc would fit in the memcap
Typedefs
typedef struct
DefragTrackerHashRow_ DefragTrackerHashRow
typedef struct DefragConfig_ DefragConfig
Functions
SC_ATOMIC_DECLARE (unsigned long long int, defrag_memuse)
SC_ATOMIC_DECLARE (unsigned int, defragtracker_counter)
SC_ATOMIC_DECLARE (unsigned int, defragtracker_prune_idx)
void DefragInitConfig (char quiet)
initialize the configuration
void DefragHashShutdown (void)
shutdown the flow engine
DefragTracker * DefragLookupTrackerFromHash (Packet *)
look up a tracker in the hash
DefragTracker * DefragGetTrackerFromHash (Packet *)
void DefragTrackerRelease (DefragTracker *)
void DefragTrackerClearMemory (DefragTracker *)
void DefragTrackerMoveToSpare (DefragTracker *)
uint32_t DefragTrackerSpareQueueGetSize (void)
Variables
DefragTrackerHashRow * defragtracker_hash
DefragConfig defrag_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file defrag-hash.h.
Macro Definition Documentation
#define DEFRAG_CHECK_MEMCAP (size) ((((uint64_t)SC_ATOMIC_GET(defrag_memuse) + (uint64_t)(size)) <= defrag_config.memcap))
check if a memory alloc would fit in the memcap
Parameters
size memory allocation size to check
Return values
1 it fits
0 no fit
Definition at line 84 of file defrag-hash.h.
Referenced by DefragInitConfig(), and DefragTrackerAlloc().
#define DEFRAG_QUIET 1
Definition at line 68 of file defrag-hash.h.
#define DEFRAG_VERBOSE 0
Definition at line 67 of file defrag-hash.h.
#define DRLOCK_DESTROY (fb) SCMutexDestroy(&(fb)->lock)
Definition at line 50 of file defrag-hash.h.
Referenced by DefragHashShutdown().
#define DRLOCK_INIT (fb) SCMutexInit(&(fb)->lock, NULL)
Definition at line 49 of file defrag-hash.h.
Referenced by DefragInitConfig().
#define DRLOCK_LOCK (fb) SCMutexLock(&(fb)->lock)
Definition at line 51 of file defrag-hash.h.
Referenced by DefragGetTrackerFromHash(), and DefragLookupTrackerFromHash().
#define DRLOCK_MUTEX
Spinlocks or Mutex for the flow buckets.
Definition at line 32 of file defrag-hash.h.
#define DRLOCK_TRYLOCK (fb) SCMutexTrylock(&(fb)->lock)
Definition at line 52 of file defrag-hash.h.
Referenced by DefragTimeoutHash().
#define DRLOCK_TYPE SCMutex
Definition at line 48 of file defrag-hash.h.
#define DRLOCK_UNLOCK (fb) SCMutexUnlock(&(fb)->lock)
Definition at line 53 of file defrag-hash.h.
Referenced by DefragGetTrackerFromHash(), DefragLookupTrackerFromHash(), and DefragTimeoutHash().
Typedef Documentation
typedef struct DefragConfig_ DefragConfig
typedef struct DefragTrackerHashRow_ DefragTrackerHashRow
Function Documentation
DefragTracker* DefragGetTrackerFromHash (Packet *)
Definition at line 485 of file defrag-hash.c.
References defragtracker_hash, DefragTrackerIncrUsecnt, DRLOCK_LOCK, DRLOCK_UNLOCK, DefragTrackerHashRow_::head, DefragTracker_::hnext, DefragTracker_::hprev, DefragTracker_::lock, DefragTracker_::remove, SCMutexLock, and DefragTrackerHashRow_::tail.
void DefragHashShutdown (void)
shutdown the flow engine
Warning
Not thread safe
Definition at line 255 of file defrag-hash.c.
References BUG_ON, defrag_config, defragtracker_hash, DefragTrackerClearMemory(), DefragTrackerDequeue(), DefragTrackerFree(), DefragTrackerQueueDestroy(), DRLOCK_DESTROY, DefragConfig_::hash_size, DefragTrackerHashRow_::head, DefragTracker_::hnext, SC_ATOMIC_DESTROY, SC_ATOMIC_GET, SC_ATOMIC_SUB, and SCFree.
Referenced by DefragDestroy().
void DefragInitConfig (char quiet)
initialize the configuration
Warning
Not thread safe
set config values for memcap, prealloc and hash_size
Definition at line 124 of file defrag-hash.c.
References ByteExtractStringUint32(), ConfGet(), ConfValIsTrue(), DEFRAG_CHECK_MEMCAP, defrag_config, DEFRAG_DEFAULT_HASHSIZE, DEFRAG_DEFAULT_MEMCAP, DEFRAG_DEFAULT_PREALLOC, defragtracker_hash, DefragTrackerAlloc(), DefragTrackerEnqueue(), DefragTrackerQueueInit(), DRLOCK_INIT, FALSE, DefragConfig_::hash_rand, DefragConfig_::hash_size, DefragTrackerQueue_::len, DefragConfig_::memcap, ParseSizeStringU64(), DefragConfig_::prealloc, RandomTimePreseed(), SC_ATOMIC_ADD, SC_ATOMIC_GET, SC_ATOMIC_INIT, SC_ERR_DEFRAG_INIT, SC_ERR_FATAL, SC_ERR_SIZE_PARSE, SCCalloc, SCLogDebug, SCLogError, SCLogInfo, unlikely, and WarnInvalidConfEntry.
Referenced by DefragInit().
DefragTracker* DefragLookupTrackerFromHash (Packet * p)
look up a tracker in the hash
Parameters
a address to look up
Return values
h LOCKED tracker or NULL
Definition at line 584 of file defrag-hash.c.
References defragtracker_hash, DefragTrackerIncrUsecnt, DRLOCK_LOCK, DRLOCK_UNLOCK, DefragTrackerHashRow_::head, DefragTracker_::hnext, DefragTracker_::hprev, DefragTracker_::lock, SCMutexLock, and DefragTrackerHashRow_::tail.
void DefragTrackerClearMemory (DefragTracker *)
Definition at line 112 of file defrag-hash.c.
References DefragTrackerFreeFrags(), and SC_ATOMIC_DESTROY.
Referenced by DefragHashShutdown(), and DefragTrackerFree().
void DefragTrackerMoveToSpare (DefragTracker *)
Definition at line 38 of file defrag-hash.c.
References DefragTrackerEnqueue(), and SC_ATOMIC_SUB.
void DefragTrackerRelease (DefragTracker *)
Definition at line 106 of file defrag-hash.c.
References DefragTrackerDecrUsecnt, DefragTracker_::lock, and SCMutexUnlock.
Referenced by Defrag().
uint32_t DefragTrackerSpareQueueGetSize (void)
Definition at line 33 of file defrag-hash.c.
References DefragTrackerQueueLen().
Referenced by DefragTrackerGetSpareCount().
SC_ATOMIC_DECLARE (unsigned long long int, defrag_memuse)
SC_ATOMIC_DECLARE (unsigned int, defragtracker_counter)
SC_ATOMIC_DECLARE (unsigned int, defragtracker_prune_idx)
Variable Documentation
DefragConfig defrag_config
Definition at line 87 of file defrag-hash.h.
Referenced by DefragHashShutdown(), DefragInitConfig(), and DefragTimeoutHash().
DefragTrackerHashRow* defragtracker_hash
defrag tracker hash table
Definition at line 65 of file defrag-hash.h.
Referenced by DefragGetTrackerFromHash(), DefragHashShutdown(), DefragInitConfig(), DefragLookupTrackerFromHash(), and DefragTimeoutHash().