suricata: src/defrag.h File Reference
defrag.h File Reference
#include "util-pool.h"
Data Structures
struct DefragContext_
struct Frag_
struct DefragTracker_
Typedefs
typedef struct DefragContext_ DefragContext
typedef struct Frag_ Frag
typedef struct DefragTracker_ DefragTracker
Functions
void DefragInit (void)
void DefragDestroy (void)
void DefragReload (void)
uint8_t DefragGetOsPolicy (Packet *)
Get the defrag policy based on the destination address of the packet.
void DefragTrackerFreeFrags (DefragTracker *)
Free all frags associated with a tracker.
Packet * Defrag (ThreadVars *, DecodeThreadVars *, Packet *, PacketQueue *)
Entry point for IPv4 and IPv6 fragments.
void DefragRegisterTests (void)
Detailed Description
Author
Endace Technology Limited, Jason Ish jason.nosp@m..ish.nosp@m.@enda.nosp@m.ce.c.nosp@m.om
Definition in file defrag.h.
Typedef Documentation
typedef struct DefragContext_ DefragContext
A context for an instance of a fragmentation re-assembler, in case we ever need more than one.
typedef struct DefragTracker_ DefragTracker
A defragmentation tracker. Used to track fragments that make up a single packet.
typedef struct Frag_ Frag
Storage for an individual fragment.
Function Documentation
Packet* Defrag (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, PacketQueue * pq)
Entry point for IPv4 and IPv6 fragments.
Parameters
tv ThreadVars for the calling decoder.
p The packet fragment.
Return values
A new Packet resembling the re-assembled packet if the most recent fragment allowed the packet to be re-assembled, otherwise NULL is returned.
Definition at line 908 of file defrag.c.
References af, DecodeThreadVars_::counter_defrag_ipv4_fragments, DecodeThreadVars_::counter_defrag_ipv6_fragments, DefragTrackerRelease(), IPV4_GET_IPOFFSET, IPV4_GET_MF, IPV6_EXTHDR_GET_FH_FLAG, IPV6_EXTHDR_GET_FH_OFFSET, PKT_IS_IPV4, PKT_IS_IPV6, and StatsIncr().
Referenced by DecodeIPV4(), and DecodeIPV6().
void DefragDestroy (void)
Definition at line 976 of file defrag.c.
References DefragHashShutdown().
Referenced by main().
uint8_t DefragGetOsPolicy (Packet * p)
Get the defrag policy based on the destination address of the packet.
Parameters
p The packet used to get the destination address.
Return values
The defrag policy to use.
Definition at line 829 of file defrag.c.
References DEFRAG_POLICY_BSD, DEFRAG_POLICY_BSD_RIGHT, DEFRAG_POLICY_FIRST, DEFRAG_POLICY_LAST, DEFRAG_POLICY_LINUX, DEFRAG_POLICY_SOLARIS, DEFRAG_POLICY_WINDOWS, GET_IPV4_DST_ADDR_PTR, GET_IPV6_DST_ADDR, OS_POLICY_BSD, OS_POLICY_BSD_RIGHT, OS_POLICY_FIRST, OS_POLICY_HPUX10, OS_POLICY_HPUX11, OS_POLICY_IRIX, OS_POLICY_LAST, OS_POLICY_LINUX, OS_POLICY_MACOS, OS_POLICY_OLD_LINUX, OS_POLICY_OLD_SOLARIS, OS_POLICY_SOLARIS, OS_POLICY_VISTA, OS_POLICY_WINDOWS, OS_POLICY_WINDOWS2K3, PKT_IS_IPV4, PKT_IS_IPV6, SCHInfoGetIPv4HostOSFlavour(), and SCHInfoGetIPv6HostOSFlavour().
void DefragInit (void)
Definition at line 954 of file defrag.c.
References ConfGetInt(), DEFAULT_DEFRAG_HASH_SIZE, DefragInitConfig(), DefragPolicyLoadFromConfig(), DefragSetDefaultTimeout(), FALSE, SC_ERR_MEM_ALLOC, SCLogError, and DefragContext_::timeout.
void DefragRegisterTests (void)
Definition at line 2535 of file defrag.c.
Referenced by RunUnittests().
void DefragReload (void)
use only in unittests
void DefragTrackerFreeFrags (DefragTracker *)
Free all frags associated with a tracker.
Definition at line 150 of file defrag.c.
References DefragContext_::frag_pool, DefragContext_::frag_pool_lock, next, PoolReturn(), SCMutexLock, SCMutexUnlock, TAILQ_FIRST, and TAILQ_REMOVE.
Referenced by DefragTrackerClearMemory().