suricata: src/defrag-queue.h File Reference
defrag-queue.h File Reference
#include "suricata-common.h"
#include "defrag.h"
Data Structures
struct DefragTrackerQueue_
Macros
#define DQLOCK_MUTEX
#define DQLOCK_INIT(q) SCMutexInit(&(q)->m, NULL)
#define DQLOCK_DESTROY(q) SCMutexDestroy(&(q)->m)
#define DQLOCK_LOCK(q) SCMutexLock(&(q)->m)
#define DQLOCK_TRYLOCK(q) SCMutexTrylock(&(q)->m)
#define DQLOCK_UNLOCK(q) SCMutexUnlock(&(q)->m)
Typedefs
typedef struct DefragTrackerQueue_ DefragTrackerQueue
Functions
DefragTrackerQueue * DefragTrackerQueueNew ()
DefragTrackerQueue * DefragTrackerQueueInit (DefragTrackerQueue *)
void DefragTrackerQueueDestroy (DefragTrackerQueue *)
Destroy a tracker queue.
void DefragTrackerEnqueue (DefragTrackerQueue *, DefragTracker *)
add a tracker to a queue
DefragTracker * DefragTrackerDequeue (DefragTrackerQueue *)
remove a tracker from the queue
uint32_t DefragTrackerQueueLen (DefragTrackerQueue *)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file defrag-queue.h.
Macro Definition Documentation
#define DQLOCK_DESTROY (q) SCMutexDestroy(&(q)->m)
Definition at line 66 of file defrag-queue.h.
Referenced by DefragTrackerQueueDestroy().
#define DQLOCK_INIT (q) SCMutexInit(&(q)->m, NULL)
Definition at line 65 of file defrag-queue.h.
Referenced by DefragTrackerQueueInit().
#define DQLOCK_LOCK (q) SCMutexLock(&(q)->m)
Definition at line 67 of file defrag-queue.h.
Referenced by DefragTrackerDequeue(), DefragTrackerEnqueue(), and DefragTrackerQueueLen().
#define DQLOCK_MUTEX
Spinlocks or Mutex for the defrag tracker queues.
Definition at line 32 of file defrag-queue.h.
#define DQLOCK_TRYLOCK (q) SCMutexTrylock(&(q)->m)
Definition at line 68 of file defrag-queue.h.
#define DQLOCK_UNLOCK (q) SCMutexUnlock(&(q)->m)
Definition at line 69 of file defrag-queue.h.
Referenced by DefragTrackerDequeue(), DefragTrackerEnqueue(), and DefragTrackerQueueLen().
Typedef Documentation
typedef struct DefragTrackerQueue_ DefragTrackerQueue
Function Documentation
DefragTracker* DefragTrackerDequeue (DefragTrackerQueue * q)
remove a tracker from the queue
Parameters
q queue
Return values
dt tracker or NULL if empty list.
Definition at line 103 of file defrag-queue.c.
References DefragTrackerQueue_::bot, BUG_ON, DQLOCK_LOCK, DQLOCK_UNLOCK, DefragTrackerQueue_::len, DefragTracker_::lnext, DefragTracker_::lprev, and DefragTrackerQueue_::top.
Referenced by DefragHashShutdown().
void DefragTrackerEnqueue (DefragTrackerQueue * q, DefragTracker * dt)
add a tracker to a queue
Parameters
q queue
dt tracker
Definition at line 70 of file defrag-queue.c.
References DefragTrackerQueue_::bot, BUG_ON, DQLOCK_LOCK, DQLOCK_UNLOCK, DefragTrackerQueue_::len, DefragTracker_::lnext, DefragTracker_::lprev, and DefragTrackerQueue_::top.
Referenced by DefragInitConfig(), and DefragTrackerMoveToSpare().
void DefragTrackerQueueDestroy (DefragTrackerQueue * q)
Destroy a tracker queue.
Parameters
q the tracker queue to destroy
Definition at line 59 of file defrag-queue.c.
References DQLOCK_DESTROY.
Referenced by DefragHashShutdown().
DefragTrackerQueue* DefragTrackerQueueInit (DefragTrackerQueue *)
Definition at line 34 of file defrag-queue.c.
References DQLOCK_INIT.
Referenced by DefragInitConfig(), and DefragTrackerQueueNew().
uint32_t DefragTrackerQueueLen (DefragTrackerQueue *)
Definition at line 136 of file defrag-queue.c.
References DQLOCK_LOCK, DQLOCK_UNLOCK, len, and DefragTrackerQueue_::len.
Referenced by DefragTrackerSpareQueueGetSize().
DefragTrackerQueue* DefragTrackerQueueNew ()
Definition at line 43 of file defrag-queue.c.
References DefragTrackerQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.