suricata: src/defrag-hash.c File Reference
defrag-hash.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "defrag-hash.h"
#include "defrag-queue.h"
#include "defrag-config.h"
#include "util-random.h"
#include "util-byte.h"
#include "util-misc.h"
#include "util-hash-lookup3.h"
Data Structures
struct DefragHashKey4_
struct DefragHashKey6_
Macros
#define DefragTrackerIncrUsecnt(dt) SC_ATOMIC_ADD((dt)->use_cnt, 1)
#define DefragTrackerDecrUsecnt(dt) SC_ATOMIC_SUB((dt)->use_cnt, 1)
#define DEFRAG_DEFAULT_HASHSIZE 4096
#define DEFRAG_DEFAULT_MEMCAP 16777216
#define DEFRAG_DEFAULT_PREALLOC 1000
#define CMP_DEFRAGTRACKER(d1, d2, id)
Typedefs
typedef struct DefragHashKey4_ DefragHashKey4
typedef struct DefragHashKey6_ DefragHashKey6
Functions
uint32_t DefragTrackerSpareQueueGetSize (void)
void DefragTrackerMoveToSpare (DefragTracker *h)
DefragTracker * DefragTrackerAlloc (void)
void DefragTrackerFree (DefragTracker *dt)
void DefragTrackerRelease (DefragTracker *t)
void DefragTrackerClearMemory (DefragTracker *dt)
void DefragInitConfig (char quiet)
initialize the configuration
void DefragHashShutdown (void)
shutdown the flow engine
DefragTracker * DefragGetTrackerFromHash (Packet *p)
DefragTracker * DefragLookupTrackerFromHash (Packet *p)
look up a tracker in the hash
Macro Definition Documentation
#define CMP_DEFRAGTRACKER (d1, d2, id)
Value:
(((CMP_ADDR(&(d1)->src_addr, &(d2)->src) && \
       CMP_ADDR(&(d1)->dst_addr, &(d2)->dst)) || \
      (CMP_ADDR(&(d1)->src_addr, &(d2)->dst) && \
       CMP_ADDR(&(d1)->dst_addr, &(d2)->src))) && \
     (d1)->id == (id) && \
     (d1)->vlan_id[0] == (d2)->vlan_id[0] && \
     (d1)->vlan_id[1] == (d2)->vlan_id[1])
Definition at line 403 of file defrag-hash.c.
#define DEFRAG_DEFAULT_HASHSIZE 4096
Definition at line 118 of file defrag-hash.c.
Referenced by DefragInitConfig().
#define DEFRAG_DEFAULT_MEMCAP 16777216
Definition at line 119 of file defrag-hash.c.
Referenced by DefragInitConfig().
#define DEFRAG_DEFAULT_PREALLOC 1000
Definition at line 120 of file defrag-hash.c.
Referenced by DefragInitConfig().
#define DefragTrackerDecrUsecnt (dt) SC_ATOMIC_SUB((dt)->use_cnt, 1)
Definition at line 79 of file defrag-hash.c.
Referenced by DefragTrackerRelease().
#define DefragTrackerIncrUsecnt (dt) SC_ATOMIC_ADD((dt)->use_cnt, 1)
Definition at line 77 of file defrag-hash.c.
Referenced by DefragGetTrackerFromHash(), and DefragLookupTrackerFromHash().
Typedef Documentation
typedef struct DefragHashKey4_ DefragHashKey4
typedef struct DefragHashKey6_ DefragHashKey6
Function Documentation
DefragTracker* DefragGetTrackerFromHash (Packet * p)
Definition at line 485 of file defrag-hash.c.
References defragtracker_hash, DefragTrackerIncrUsecnt, DRLOCK_LOCK, DRLOCK_UNLOCK, DefragTrackerHashRow_::head, DefragTracker_::hnext, DefragTracker_::hprev, DefragTracker_::lock, DefragTracker_::remove, SCMutexLock, and DefragTrackerHashRow_::tail.
void DefragHashShutdown (void)
shutdown the flow engine
Warning
Not thread safe
Definition at line 255 of file defrag-hash.c.
References BUG_ON, defrag_config, defragtracker_hash, DefragTrackerClearMemory(), DefragTrackerDequeue(), DefragTrackerFree(), DefragTrackerQueueDestroy(), DRLOCK_DESTROY, DefragConfig_::hash_size, DefragTrackerHashRow_::head, DefragTracker_::hnext, SC_ATOMIC_DESTROY, SC_ATOMIC_GET, SC_ATOMIC_SUB, and SCFree.
Referenced by DefragDestroy().
void DefragInitConfig (char quiet)
initialize the configuration
Warning
Not thread safe
set config values for memcap, prealloc and hash_size
Definition at line 124 of file defrag-hash.c.
References ByteExtractStringUint32(), ConfGet(), ConfValIsTrue(), DEFRAG_CHECK_MEMCAP, defrag_config, DEFRAG_DEFAULT_HASHSIZE, DEFRAG_DEFAULT_MEMCAP, DEFRAG_DEFAULT_PREALLOC, defragtracker_hash, DefragTrackerAlloc(), DefragTrackerEnqueue(), DefragTrackerQueueInit(), DRLOCK_INIT, FALSE, DefragConfig_::hash_rand, DefragConfig_::hash_size, DefragTrackerQueue_::len, DefragConfig_::memcap, ParseSizeStringU64(), DefragConfig_::prealloc, RandomTimePreseed(), SC_ATOMIC_ADD, SC_ATOMIC_GET, SC_ATOMIC_INIT, SC_ERR_DEFRAG_INIT, SC_ERR_FATAL, SC_ERR_SIZE_PARSE, SCCalloc, SCLogDebug, SCLogError, SCLogInfo, unlikely, and WarnInvalidConfEntry.
Referenced by DefragInit().
DefragTracker* DefragLookupTrackerFromHash (Packet * p)
look up a tracker in the hash
Parameters
a address to look up
Return values
h LOCKED tracker or NULL
Definition at line 584 of file defrag-hash.c.
References defragtracker_hash, DefragTrackerIncrUsecnt, DRLOCK_LOCK, DRLOCK_UNLOCK, DefragTrackerHashRow_::head, DefragTracker_::hnext, DefragTracker_::hprev, DefragTracker_::lock, SCMutexLock, and DefragTrackerHashRow_::tail.
DefragTracker* DefragTrackerAlloc (void)
Definition at line 44 of file defrag-hash.c.
References DEFRAG_CHECK_MEMCAP, DefragTracker_::lock, SC_ATOMIC_ADD, SC_ATOMIC_INIT, SCMalloc, SCMutexInit, and unlikely.
Referenced by DefragInitConfig().
void DefragTrackerClearMemory (DefragTracker * dt)
Definition at line 112 of file defrag-hash.c.
References DefragTrackerFreeFrags(), and SC_ATOMIC_DESTROY.
Referenced by DefragHashShutdown(), and DefragTrackerFree().
void DefragTrackerFree (DefragTracker * dt)
Definition at line 66 of file defrag-hash.c.
References DefragTrackerClearMemory(), DefragTracker_::lock, SC_ATOMIC_SUB, SCFree, and SCMutexDestroy.
Referenced by DefragHashShutdown().
void DefragTrackerMoveToSpare (DefragTracker * h)
Definition at line 38 of file defrag-hash.c.
References DefragTrackerEnqueue(), and SC_ATOMIC_SUB.
void DefragTrackerRelease (DefragTracker * t)
Definition at line 106 of file defrag-hash.c.
References DefragTrackerDecrUsecnt, DefragTracker_::lock, and SCMutexUnlock.
Referenced by Defrag().
uint32_t DefragTrackerSpareQueueGetSize (void)
Definition at line 33 of file defrag-hash.c.
References DefragTrackerQueueLen().
Referenced by DefragTrackerGetSpareCount().