suricata: src/defrag-queue.c File Reference
defrag-queue.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "defrag-queue.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-print.h"
Functions
DefragTrackerQueue * DefragTrackerQueueInit (DefragTrackerQueue *q)
DefragTrackerQueue * DefragTrackerQueueNew ()
void DefragTrackerQueueDestroy (DefragTrackerQueue *q)
Destroy a tracker queue.
void DefragTrackerEnqueue (DefragTrackerQueue *q, DefragTracker *dt)
add a tracker to a queue
DefragTracker * DefragTrackerDequeue (DefragTrackerQueue *q)
remove a tracker from the queue
uint32_t DefragTrackerQueueLen (DefragTrackerQueue *q)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Defrag tracker queue handler functions
Definition in file defrag-queue.c.
Function Documentation
DefragTracker* DefragTrackerDequeue (DefragTrackerQueue * q)
remove a tracker from the queue
Parameters
q queue
Return values
dt tracker or NULL if empty list.
Definition at line 103 of file defrag-queue.c.
References DefragTrackerQueue_::bot, BUG_ON, DQLOCK_LOCK, DQLOCK_UNLOCK, DefragTrackerQueue_::len, DefragTracker_::lnext, DefragTracker_::lprev, and DefragTrackerQueue_::top.
Referenced by DefragHashShutdown().
void DefragTrackerEnqueue (DefragTrackerQueue * q, DefragTracker * dt)
add a tracker to a queue
Parameters
q queue
dt tracker
Definition at line 70 of file defrag-queue.c.
References DefragTrackerQueue_::bot, BUG_ON, DQLOCK_LOCK, DQLOCK_UNLOCK, DefragTrackerQueue_::len, DefragTracker_::lnext, DefragTracker_::lprev, and DefragTrackerQueue_::top.
Referenced by DefragInitConfig(), and DefragTrackerMoveToSpare().
void DefragTrackerQueueDestroy (DefragTrackerQueue * q)
Destroy a tracker queue.
Parameters
q the tracker queue to destroy
Definition at line 59 of file defrag-queue.c.
References DQLOCK_DESTROY.
Referenced by DefragHashShutdown().
DefragTrackerQueue* DefragTrackerQueueInit (DefragTrackerQueue * q)
Definition at line 34 of file defrag-queue.c.
References DQLOCK_INIT.
Referenced by DefragInitConfig(), and DefragTrackerQueueNew().
uint32_t DefragTrackerQueueLen (DefragTrackerQueue * q)
Definition at line 136 of file defrag-queue.c.
References DQLOCK_LOCK, DQLOCK_UNLOCK, len, and DefragTrackerQueue_::len.
Referenced by DefragTrackerSpareQueueGetSize().
DefragTrackerQueue* DefragTrackerQueueNew ()
Definition at line 43 of file defrag-queue.c.
References DefragTrackerQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.