suricata: src/defrag-config.h File Reference
defrag-config.h File Reference
Functions
void DefragSetDefaultTimeout (intmax_t timeout)
void DefragPolicyLoadFromConfig (void)
int DefragPolicyGetHostTimeout (Packet *p)
Detailed Description
Author
Giuseppe Longo giuse.nosp@m.ppel.nosp@m.ng@gm.nosp@m.ail..nosp@m.com
Definition in file defrag-config.h.
Function Documentation
int DefragPolicyGetHostTimeout (Packet * p)
Definition at line 91 of file defrag-config.c.
References GET_IPV4_DST_ADDR_PTR, GET_IPV6_DST_ADDR, PKT_IS_IPV4, and PKT_IS_IPV6.
void DefragPolicyLoadFromConfig (void)
Definition at line 134 of file defrag-config.c.
References ConfGetNode(), ConfNode_::name, next, SC_ERR_MEM_ALLOC, SCEnter, SCLogDebug, SCLogError, SCRadixCreateRadixTree(), SCReturn, and TAILQ_FOREACH.
Referenced by DefragInit().
void DefragSetDefaultTimeout (intmax_t timeout)
Definition at line 128 of file defrag-config.c.
References SCLogDebug.
Referenced by DefragInit().