suricata: src/detect-ipopts.c File Reference
detect-ipopts.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "flow-var.h"
#include "decode-events.h"
#include "util-debug.h"
#include "detect-ipopts.h"
#include "util-unittest.h"
Macros
#define DETECT_EVENTS
#define PARSE_REGEX "\\S[A-z]"
#define MAX_SUBSTRINGS 30
Functions
int DetectIpOptsMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, const SigMatchCtx *)
void IpOptsRegisterTests (void)
this function registers unit tests for IpOpts
void DetectIpOptsFree (void *)
void DetectIpOptsRegister (void)
Registration function for ipopts: keyword.
DetectIpOptsData * DetectIpOptsParse (char *rawstr)
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Implements the ipopts keyword
Definition in file detect-ipopts.c.
Macro Definition Documentation
#define DETECT_EVENTS
Definition at line 39 of file detect-ipopts.c.
#define MAX_SUBSTRINGS 30
Referenced by DetectIpOptsParse().
#define PARSE_REGEX "\\S[A-z]"
Definition at line 44 of file detect-ipopts.c.
Referenced by DetectIpOptsRegister().
Function Documentation
void DetectIpOptsFree (void * de_ptr)
Definition at line 223 of file detect-ipopts.c.
References SCFree.
Referenced by DetectIpOptsRegister().
int DetectIpOptsMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Definition at line 104 of file detect-ipopts.c.
References de, DetectIpOptsData_::ipopt, IPV4_OPTS_CNT, PKT_IS_IPV4, PKT_IS_PSEUDOPKT, and Packet_::type.
Referenced by DetectIpOptsRegister().
DetectIpOptsData* DetectIpOptsParse (char * rawstr)
Definition at line 142 of file detect-ipopts.c.
References de, DetectIpOptsData_::ipopt, MAX_SUBSTRINGS, SC_ERR_PCRE_MATCH, SCFree, SCLogError, SCMalloc, and unlikely.
void DetectIpOptsRegister (void)
Registration function for ipopts: keyword.
Registration function for ipopts: keyword
Definition at line 57 of file detect-ipopts.c.
References SigTableElmt_::desc, DETECT_IPOPTS, DetectIpOptsFree(), DetectIpOptsMatch(), SigTableElmt_::Free, IpOptsRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void IpOptsRegisterTests (void)
this function registers unit tests for IpOpts
Definition at line 378 of file detect-ipopts.c.
Referenced by DetectIpOptsRegister().