suricata: src/detect-id.h File Reference
detect-id.h File Reference
Data Structures
struct DetectIdData_
Macros
#define DETECT_IPID_MIN 0
#define DETECT_IPID_MAX 65536
Typedefs
typedef struct DetectIdData_ DetectIdData
Functions
void DetectIdRegister (void)
Registration function for keyword: id.
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file detect-id.h.
Macro Definition Documentation
#define DETECT_IPID_MAX 65536
Definition at line 29 of file detect-id.h.
Referenced by DetectIdParse().
#define DETECT_IPID_MIN 0
Definition at line 28 of file detect-id.h.
Referenced by DetectIdParse().
Typedef Documentation
typedef struct DetectIdData_ DetectIdData
Function Documentation
void DetectIdRegister (void)
Registration function for keyword: id.
Definition at line 60 of file detect-id.c.
References SigTableElmt_::desc, DETECT_ID, DetectIdFree(), DetectIdMatch(), DetectIdRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().