suricata: src/detect-urilen.c File Reference
detect-urilen.c File Reference
#include "suricata-common.h"
#include "app-layer.h"
#include "app-layer-protos.h"
#include "app-layer-htp.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine-state.h"
#include "detect-urilen.h"
#include "util-debug.h"
#include "util-byte.h"
#include "flow-util.h"
#include "stream-tcp.h"
Macros
#define PARSE_REGEX "^(?:\\s*)(<|>)?(?:\\s*)([0-9]{1,5})(?:\\s*)(?:(<>)(?:\\s*)([0-9]{1,5}))?\\s*(?:,\\s*(norm|raw))?\\s*$"
Regex for parsing our urilen.
#define MAX_SUBSTRINGS 30
Functions
void DetectUrilenFree (void *ptr)
this function will free memory associated with DetectUrilenData
void DetectUrilenRegisterTests (void)
this function registers unit tests for DetectUrilen
void DetectUrilenRegister (void)
Registration function for urilen: keyword.
DetectUrilenData * DetectUrilenParse (char *urilenstr)
This function is used to parse urilen options passed via urilen: keyword.
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.sighd.nosp@m.ahiy.nosp@m.a@gma.nosp@m.il.c.nosp@m.om
Implements the urilen keyword
Definition in file detect-urilen.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectUrilenParse().
#define PARSE_REGEX "^(?:\\s*)(<|>)?(?:\\s*)([0-9]{1,5})(?:\\s*)(?:(<>)(?:\\s*)([0-9]{1,5}))?\\s*(?:,\\s*(norm|raw))?\\s*$"
Regex for parsing our urilen.
Definition at line 46 of file detect-urilen.c.
Referenced by DetectUrilenRegister().
Function Documentation
void DetectUrilenFree (void * ptr)
this function will free memory associated with DetectUrilenData
Parameters
ptr pointer to DetectUrilenData
Definition at line 305 of file detect-urilen.c.
References SCFree.
Referenced by DetectUrilenRegister().
DetectUrilenData* DetectUrilenParse (char * urilenstr)
This function is used to parse urilen options passed via urilen: keyword.
Parameters
urilenstr Pointer to the user provided urilen options
Return values
urilend pointer to DetectUrilenData on success
NULL on failure
set the first urilen value
set the second urilen value if specified
Definition at line 108 of file detect-urilen.c.
References ByteExtractStringUint16(), DETECT_URILEN_EQ, DETECT_URILEN_GT, DETECT_URILEN_LT, DETECT_URILEN_RA, MAX_SUBSTRINGS, DetectUrilenData_::mode, DetectUrilenData_::raw_buffer, SC_ERR_INVALID_ARGUMENT, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_PARSE, SCFree, SCLogDebug, SCLogError, SCMalloc, unlikely, DetectUrilenData_::urilen1, and DetectUrilenData_::urilen2.
void DetectUrilenRegister (void)
Registration function for urilen: keyword.
< We handle this at detect-engine-uri.c now
Definition at line 60 of file detect-urilen.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, SigTableElmt_::desc, DETECT_AL_URILEN, DetectUrilenFree(), DetectUrilenRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, pcre_free_study, SigTableElmt_::RegisterTests, SCLogDebug, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectUrilenRegisterTests (void)
this function registers unit tests for DetectUrilen
Definition at line 684 of file detect-urilen.c.
Referenced by DetectUrilenRegister().