suricata: src/detect-http-server-body.h File Reference
detect-http-server-body.h File Reference
Functions
void DetectHttpServerBodyRegister (void)
Registers the keyword handlers for the "http_server_body" keyword.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-http-server-body.h.
Function Documentation
void DetectHttpServerBodyRegister (void)
Registers the keyword handlers for the "http_server_body" keyword.
Definition at line 69 of file detect-http-server-body.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, SigTableElmt_::desc, DETECT_AL_HTTP_SERVER_BODY, DetectHttpServerBodyFree(), DetectHttpServerBodyRegisterTests(), DetectHttpServerBodySetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().