suricata: src/detect-bytejump.c File Reference
detect-bytejump.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "app-layer.h"
#include "detect-bytejump.h"
#include "detect-byte-extract.h"
#include "detect-content.h"
#include "detect-uricontent.h"
#include "util-byte.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "detect-pcre.h"
Macros
#define PARSE_REGEX
Regex for parsing our options.
#define MAX_SUBSTRINGS 30
Functions
void DetectBytejumpRegisterTests (void)
this function registers unit tests for DetectBytejump
void DetectBytejumpRegister (void)
int DetectBytejumpDoMatch (DetectEngineThreadCtx *det_ctx, Signature *s, const SigMatchCtx *ctx, uint8_t *payload, uint32_t payload_len, uint8_t flags, int32_t offset)
Byte jump match function.
int DetectBytejumpMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
DetectBytejumpData * DetectBytejumpParse (char *optstr, char **offset)
int DetectBytejumpSetup (DetectEngineCtx *de_ctx, Signature *s, char *optstr)
void DetectBytejumpFree (void *ptr)
this function will free memory associated with DetectBytejumpData
Detailed Description
Author
Brian Rectanus brect.nosp@m.anu@.nosp@m.gmail.nosp@m..com
Implements byte_jump keyword.
Definition in file detect-bytejump.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectBytejumpParse().
#define PARSE_REGEX
Value:
"^\\s*" \
                     "([^\\s,]+\\s*,\\s*[^\\s,]+)" \
                     "(?:\\s*,\\s*((?:multiplier|post_offset)\\s+[^\\s,]+|[^\\s,]+))?" \
                     "(?:\\s*,\\s*((?:multiplier|post_offset)\\s+[^\\s,]+|[^\\s,]+))?" \
                     "(?:\\s*,\\s*((?:multiplier|post_offset)\\s+[^\\s,]+|[^\\s,]+))?" \
                     "(?:\\s*,\\s*((?:multiplier|post_offset)\\s+[^\\s,]+|[^\\s,]+))?" \
                     "(?:\\s*,\\s*((?:multiplier|post_offset)\\s+[^\\s,]+|[^\\s,]+))?" \
                     "(?:\\s*,\\s*((?:multiplier|post_offset)\\s+[^\\s,]+|[^\\s,]+))?" \
                     "(?:\\s*,\\s*((?:multiplier|post_offset)\\s+[^\\s,]+|[^\\s,]+))?" \
                     "(?:\\s*,\\s*((?:multiplier|post_offset)\\s+[^\\s,]+|[^\\s,]+))?" \
                     "(?:\\s*,\\s*((?:multiplier|post_offset)\\s+[^\\s,]+|[^\\s,]+))?" \
                     "\\s*$"
Regex for parsing our options.
Definition at line 47 of file detect-bytejump.c.
Referenced by DetectBytejumpRegister().
Function Documentation
int DetectBytejumpDoMatch (DetectEngineThreadCtx * det_ctx, Signature * s, const SigMatchCtx * ctx, uint8_t * payload, uint32_t payload_len, uint8_t flags, int32_t offset)
Byte jump match function.
Parameters
det_ctx thread detect engine ctx
s signature
m byte jump sigmatch
payload ptr to the payload
payload_len length of the payload
Return values
1 match
0 no match
Definition at line 109 of file detect-bytejump.c.
References DetectBytejumpData_::base, DetectEngineThreadCtx_::buffer_offset, BYTE_BIG_ENDIAN, BYTE_LITTLE_ENDIAN, ByteExtractStringUint64(), ByteExtractUint64(), data, DETECT_BYTEJUMP_ALIGN, DETECT_BYTEJUMP_BEGIN, DETECT_BYTEJUMP_LITTLE, DETECT_BYTEJUMP_RELATIVE, DETECT_BYTEJUMP_STRING, len, DetectBytejumpData_::multiplier, DetectBytejumpData_::nbytes, DetectBytejumpData_::post_offset, SC_ERR_BYTE_EXTRACT_FAILED, SCEnter, SCLogDebug, SCLogDebugEnabled(), SCLogError, and SCReturnInt.
void DetectBytejumpFree (void * ptr)
this function will free memory associated with DetectBytejumpData
Parameters
data pointer to DetectBytejumpData
Definition at line 746 of file detect-bytejump.c.
References data, and SCFree.
Referenced by DetectBytejumpParse(), DetectBytejumpRegister(), and DetectBytejumpSetup().
int DetectBytejumpMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match byte_jump
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectBytejumpData
Return values
-1 error
0 no match
1 match
Todo:
The return seems backwards. We should return a non-zero error code. One of the error codes is "no match". As-is if someone accidentally does: if (DetectBytejumpMatch(...)) { match }, then they catch an error as a match.
Definition at line 221 of file detect-bytejump.c.
References DetectBytejumpData_::base, DetectEngineThreadCtx_::buffer_offset, BYTE_BIG_ENDIAN, BYTE_LITTLE_ENDIAN, ByteExtractStringUint64(), ByteExtractUint64(), data, DETECT_BYTEJUMP_ALIGN, DETECT_BYTEJUMP_BEGIN, DETECT_BYTEJUMP_LITTLE, DETECT_BYTEJUMP_RELATIVE, DETECT_BYTEJUMP_STRING, DetectBytejumpData_::flags, len, DetectBytejumpData_::multiplier, DetectBytejumpData_::nbytes, DetectBytejumpData_::offset, Packet_::payload, Packet_::payload_len, DetectBytejumpData_::post_offset, SC_ERR_BYTE_EXTRACT_FAILED, SCLogDebug, SCLogDebugEnabled(), and SCLogError.
Referenced by DetectBytejumpRegister().
DetectBytejumpData* DetectBytejumpParse (char * optstr, char ** offset)
This function is used to parse byte_jump options passed via
byte_jump: bytes, offset [,flags [, ...]]
flags: "big", "little", "relative", "string", "oct", "dec", "hex" "align", "from beginning", "multiplier N", "post_offset N"
Parameters
optstr Pointer to the user provided byte_jump options
offset Used to pass the offset back, if byte_jump uses a byte_extract var.
Return values
data pointer to DetectBytejumpData on success
NULL on failure
Todo:
Error on dups?
Definition at line 331 of file detect-bytejump.c.
References DetectBytejumpData_::base, ByteExtractStringInt32(), ByteExtractStringUint32(), data, DETECT_BYTEJUMP_ALIGN, DETECT_BYTEJUMP_BASE_DEC, DETECT_BYTEJUMP_BASE_HEX, DETECT_BYTEJUMP_BASE_OCT, DETECT_BYTEJUMP_BASE_UNSET, DETECT_BYTEJUMP_BEGIN, DETECT_BYTEJUMP_BIG, DETECT_BYTEJUMP_DCE, DETECT_BYTEJUMP_LITTLE, DETECT_BYTEJUMP_RELATIVE, DETECT_BYTEJUMP_STRING, DetectBytejumpFree(), DetectBytejumpData_::flags, MAX_SUBSTRINGS, DetectBytejumpData_::multiplier, DetectBytejumpData_::nbytes, DetectBytejumpData_::offset, DetectBytejumpData_::post_offset, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_PARSE, SCFree, SCLogError, SCMalloc, SCStrdup, str, strlcpy(), and unlikely.
Referenced by DetectBytejumpSetup().
void DetectBytejumpRegister (void)
Registration function for byte_jump.
Todo:
add support for no_stream and stream_only
Definition at line 65 of file detect-bytejump.c.
References DETECT_BYTEJUMP, DetectBytejumpFree(), DetectBytejumpMatch(), DetectBytejumpRegisterTests(), DetectBytejumpSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void DetectBytejumpRegisterTests (void)
this function registers unit tests for DetectBytejump
Definition at line 1404 of file detect-bytejump.c.
Referenced by DetectBytejumpRegister().
int DetectBytejumpSetup (DetectEngineCtx * , Signature * , char *)
This function is used to add the parsed byte_jump data into the current signature.
Parameters
de_ctx pointer to the Detection Engine Context
s pointer to the Current Signature
optstr pointer to the user provided options
Return values
0 on Success
-1 on Failure
Definition at line 525 of file detect-bytejump.c.
References Signature_::alproto, ALPROTO_DCERPC, ALPROTO_UNKNOWN, AppLayerHtpEnableResponseBodyCallback(), DetectBytejumpData_::base, SigMatch_::ctx, data, DETECT_BYTE_EXTRACT, DETECT_BYTEJUMP, DETECT_BYTEJUMP_BASE_DEC, DETECT_BYTEJUMP_BASE_HEX, DETECT_BYTEJUMP_BASE_OCT, DETECT_BYTEJUMP_BEGIN, DETECT_BYTEJUMP_BIG, DETECT_BYTEJUMP_DCE, DETECT_BYTEJUMP_LITTLE, DETECT_BYTEJUMP_OFFSET_BE, DETECT_BYTEJUMP_RELATIVE, DETECT_BYTEJUMP_STRING, DETECT_BYTETEST, DETECT_CONTENT, DETECT_CONTENT_RELATIVE_NEXT, DETECT_ISDATAAT, DETECT_PCRE, DETECT_PCRE_RELATIVE_NEXT, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_NOTSET, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectByteExtractRetrieveSMVar(), DetectBytejumpFree(), DetectBytejumpParse(), DetectPcreData_::flags, DetectBytejumpData_::flags, DetectContentData_::flags, Signature_::flags, Signature_::list, DetectBytejumpData_::offset, SC_ERR_CONFLICTING_RULE_KEYWORDS, SC_ERR_INVALID_SIGNATURE, SCFree, SCLogError, SIG_FLAG_APPLAYER, SigMatchAlloc(), SigMatchAppendSMToList(), SigMatchGetLastSMFromLists(), SigMatchListSMBelongsTo(), Signature_::sm_lists_tail, and SigMatch_::type.
Referenced by DetectBytejumpRegister().