suricata: src/detect-icode.c File Reference
detect-icode.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-icode.h"
#include "util-byte.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^\\s*(<|>)?\\s*([0-9]+)\\s*(?:<>\\s*([0-9]+))?\\s*$"
Regex for parsing our icode options.
#define MAX_SUBSTRINGS 30
Functions
int DetectICodeMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match icode rule option set on a packet with those passed via icode:
void DetectICodeRegisterTests (void)
this function registers unit tests for DetectICode
void DetectICodeFree (void *ptr)
this function will free memory associated with DetectICodeData
void DetectICodeRegister (void)
Registration function for icode: keyword.
DetectICodeData * DetectICodeParse (char *icodestr)
This function is used to parse icode options passed via icode: keyword.
Detailed Description
Author
Gerardo Iglesias igles.nosp@m.iasg.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Implements icode keyword support
Author
Gerardo Iglesias igles.nosp@m.iasg.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Definition in file detect-icode.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectICodeParse().
#define PARSE_REGEX "^\\s*(<|>)?\\s*([0-9]+)\\s*(?:<>\\s*([0-9]+))?\\s*$"
Regex for parsing our icode options.
Definition at line 43 of file detect-icode.c.
Referenced by DetectICodeRegister().
Function Documentation
void DetectICodeFree (void * ptr)
this function will free memory associated with DetectICodeData
Parameters
ptr pointer to DetectICodeData
Definition at line 280 of file detect-icode.c.
References SCFree.
Referenced by DetectICodeParse(), and DetectICodeRegister().
int DetectICodeMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match icode rule option set on a packet with those passed via icode:
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectICodeData
Return values
0 no match
1 match
Definition at line 101 of file detect-icode.c.
References DetectICodeData_::code1, DetectICodeData_::code2, DETECT_ICODE_EQ, DETECT_ICODE_GT, DETECT_ICODE_LT, DETECT_ICODE_RN, ICMPV4_GET_CODE, ICMPV6_GET_CODE, DetectICodeData_::mode, PKT_IS_ICMPV4, PKT_IS_ICMPV6, and PKT_IS_PSEUDOPKT.
Referenced by DetectICodeRegister().
DetectICodeData* DetectICodeParse (char * icodestr)
This function is used to parse icode options passed via icode: keyword.
Parameters
icodestr Pointer to the user provided icode options
Return values
icd pointer to DetectICodeData on success
NULL on failure
Definition at line 145 of file detect-icode.c.
References ByteExtractStringUint8(), DetectICodeData_::code1, DetectICodeData_::code2, DETECT_ICODE_EQ, DETECT_ICODE_GT, DETECT_ICODE_LT, DETECT_ICODE_RN, DetectICodeFree(), MAX_SUBSTRINGS, DetectICodeData_::mode, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogError, SCMalloc, and unlikely.
void DetectICodeRegister (void)
Registration function for icode: keyword.
Definition at line 57 of file detect-icode.c.
References SigTableElmt_::desc, DETECT_ICODE, DetectICodeFree(), DetectICodeMatch(), DetectICodeRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectICodeRegisterTests (void)
this function registers unit tests for DetectICode
Definition at line 515 of file detect-icode.c.
Referenced by DetectICodeRegister().