suricata: src/detect-hostbits.h File Reference
detect-hostbits.h File Reference
#include "detect-xbits.h"
Functions
int DetectXbitMatchHost (Packet *p, const DetectXbitsData *xd)
void DetectHostbitsRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-hostbits.h.
Function Documentation
void DetectHostbitsRegister (void)
Definition at line 73 of file detect-hostbits.c.
References SigTableElmt_::desc, DETECT_HOSTBITS, DetectHostbitFree(), DetectHostbitMatch(), SigTableElmt_::flags, SigTableElmt_::Free, HostBitsRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, and sigmatch_table.
Referenced by SigTableSetup().
int DetectXbitMatchHost (Packet * p, const DetectXbitsData * xd)
Definition at line 259 of file detect-hostbits.c.
References DetectXbitsData_::cmd, DETECT_XBITS_CMD_ISNOTSET, DETECT_XBITS_CMD_ISSET, DETECT_XBITS_CMD_SET, DETECT_XBITS_CMD_TOGGLE, DETECT_XBITS_CMD_UNSET, SC_ERR_UNKNOWN_VALUE, and SCLogError.
Referenced by DetectHostbitMatch(), and DetectXbitMatch().