suricata: src/detect-app-layer-protocol.c File Reference
detect-app-layer-protocol.c File Reference
#include "suricata-common.h"
#include "detect-engine.h"
#include "detect-parse.h"
#include "detect-app-layer-protocol.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
Functions
void DetectAppLayerProtocolRegisterTests (void)
int DetectAppLayerProtocolMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Flow *f, uint8_t flags, void *state, Signature *s, SigMatch *m)
int DetectAppLayerProtocolSetup (DetectEngineCtx *de_ctx, Signature *s, char *arg)
void DetectAppLayerProtocolFree (void *ptr)
void DetectAppLayerProtocolRegister (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-app-layer-protocol.c.
Function Documentation
void DetectAppLayerProtocolFree (void * ptr)
Definition at line 128 of file detect-app-layer-protocol.c.
References SCFree.
Referenced by DetectAppLayerProtocolRegister().
int DetectAppLayerProtocolMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Flow * f, uint8_t flags, void * state, Signature * s, SigMatch * m)
Definition at line 36 of file detect-app-layer-protocol.c.
References DetectAppLayerProtocolData_::alproto, Flow_::alproto, SigMatch_::ctx, data, and DetectAppLayerProtocolData_::negated.
Referenced by DetectAppLayerProtocolRegister().
void DetectAppLayerProtocolRegister (void)
Definition at line 135 of file detect-app-layer-protocol.c.
References SigTableElmt_::AppLayerMatch, DETECT_AL_APP_LAYER_PROTOCOL, DetectAppLayerProtocolFree(), DetectAppLayerProtocolMatch(), DetectAppLayerProtocolRegisterTests(), DetectAppLayerProtocolSetup(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void DetectAppLayerProtocolRegisterTests (void)
Definition at line 392 of file detect-app-layer-protocol.c.
Referenced by DetectAppLayerProtocolRegister().
int DetectAppLayerProtocolSetup (DetectEngineCtx * de_ctx, Signature * s, char * arg)
Definition at line 89 of file detect-app-layer-protocol.c.
References DetectAppLayerProtocolData_::alproto, Signature_::alproto, ALPROTO_UNKNOWN, SigMatch_::ctx, DETECT_AL_APP_LAYER_PROTOCOL, DETECT_SM_LIST_AMATCH, Signature_::flags, DetectAppLayerProtocolData_::negated, SC_ERR_CONFLICTING_RULE_KEYWORDS, SCFree, SCLogError, SIG_FLAG_APPLAYER, SigMatchAlloc(), SigMatchAppendSMToList(), and SigMatch_::type.
Referenced by DetectAppLayerProtocolRegister().