suricata: src/detect-gid.h File Reference
detect-gid.h File Reference
#include "decode-events.h"
#include "decode-ipv4.h"
#include "decode-tcp.h"
Functions
void DetectGidRegister (void)
Registration function for gid: keyword.
void GidRegisterTests (void)
this function registers unit tests for Gid
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Implements the gid keyword
Definition in file detect-gid.h.
Function Documentation
void DetectGidRegister (void)
Registration function for gid: keyword.
Registration function for gid: keyword
Definition at line 47 of file detect-gid.c.
References SigTableElmt_::desc, DETECT_GID, SigTableElmt_::Free, GidRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void GidRegisterTests (void)
this function registers unit tests for Gid
This function registers unit tests for Gid
Definition at line 195 of file detect-gid.c.
Referenced by DetectGidRegister().