suricata: src/detect-ssh-software-version.c File Reference
detect-ssh-software-version.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-ssh.h"
#include "detect-ssh-software-version.h"
#include "stream-tcp.h"
Macros
#define PARSE_REGEX "^\\s*\"?\\s*?([0-9a-zA-Z\\:\\.\\-\\_\\+\\s+]+)\\s*\"?\\s*$"
Regex for parsing the softwareversion string.
#define MAX_SUBSTRINGS 30
Functions
int DetectSshSoftwareVersionMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Flow *f, uint8_t flags, void *state, Signature *s, SigMatch *m)
match the specified version on a ssh session
void DetectSshSoftwareVersionRegisterTests (void)
this function registers unit tests for DetectSshSoftwareVersion
void DetectSshSoftwareVersionFree (void *ptr)
this function will free memory associated with DetectSshSoftwareVersionData
void DetectSshSoftwareVersionRegister (void)
Registration function for keyword: ssh.softwareversion.
DetectSshSoftwareVersionData * DetectSshSoftwareVersionParse (char *str)
This function is used to parse IPV4 ip_id passed via keyword: "id".
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements the ssh.softwareversion keyword You can match over the software version string of ssh, and it will be compared from the beginning of the string so you can say for example ssh.softwareversion:"PuTTY" and it can match, or you can also specify the version, something like ssh.softwareversion:"PuTTY-Release-0.55" I find this useful to match over a known vulnerable server/client software version incombination to other checks, so you can know that the risk is higher
Definition in file detect-ssh-software-version.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectSshSoftwareVersionParse().
#define PARSE_REGEX "^\\s*\"?\\s*?([0-9a-zA-Z\\:\\.\\-\\_\\+\\s+]+)\\s*\"?\\s*$"
Regex for parsing the softwareversion string.
Definition at line 64 of file detect-ssh-software-version.c.
Referenced by DetectSshSoftwareVersionRegister().
Function Documentation
void DetectSshSoftwareVersionFree (void * ptr)
this function will free memory associated with DetectSshSoftwareVersionData
Parameters
id_d pointer to DetectSshSoftwareVersionData
Definition at line 256 of file detect-ssh-software-version.c.
References SCFree, and DetectSshSoftwareVersionData_::software_ver.
Referenced by DetectSshSoftwareVersionParse(), and DetectSshSoftwareVersionRegister().
int DetectSshSoftwareVersionMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Flow * f, uint8_t flags, void * state, Signature * s, SigMatch * m)
match the specified version on a ssh session
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectSshSoftwareVersionData
Return values
0 no match
1 match
Definition at line 123 of file detect-ssh-software-version.c.
References SigMatch_::ctx, DetectSshSoftwareVersionData_::len, SCEnter, SCLogDebug, SCReturnInt, DetectSshSoftwareVersionData_::software_ver, SSH_FLAG_VERSION_PARSED, STREAM_TOCLIENT, and STREAM_TOSERVER.
Referenced by DetectSshSoftwareVersionRegister().
DetectSshSoftwareVersionData* DetectSshSoftwareVersionParse (char * str)
This function is used to parse IPV4 ip_id passed via keyword: "id".
Parameters
idstr Pointer to the user provided id option
Return values
id_d pointer to DetectSshSoftwareVersionData on success
NULL on failure
Definition at line 153 of file detect-ssh-software-version.c.
References DetectSshSoftwareVersionFree(), DetectSshSoftwareVersionData_::len, MAX_SUBSTRINGS, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCLogDebug, SCLogError, SCMalloc, SCStrdup, DetectSshSoftwareVersionData_::software_ver, and unlikely.
void DetectSshSoftwareVersionRegister (void)
Registration function for keyword: ssh.softwareversion.
Definition at line 78 of file detect-ssh-software-version.c.
References SigTableElmt_::alproto, ALPROTO_SSH, SigTableElmt_::AppLayerMatch, DETECT_AL_SSH_SOFTWAREVERSION, DetectSshSoftwareVersionFree(), DetectSshSoftwareVersionMatch(), DetectSshSoftwareVersionRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void DetectSshSoftwareVersionRegisterTests (void)
this function registers unit tests for DetectSshSoftwareVersion
Definition at line 662 of file detect-ssh-software-version.c.
Referenced by DetectSshSoftwareVersionRegister().