suricata: src/detect-dce-stub-data.c File Reference
detect-dce-stub-data.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "app-layer.h"
#include "app-layer-dcerpc.h"
#include "queue.h"
#include "stream-tcp-reassemble.h"
#include "detect-dce-stub-data.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "stream-tcp.h"
Functions
int DetectDceStubDataMatch (ThreadVars *, DetectEngineThreadCtx *, Flow *, uint8_t, void *, Signature *, SigMatch *)
void DetectDceStubDataRegister (void)
Registers the keyword handlers for the "dce_stub_data" keyword.
void DetectDceStubDataRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements dce_stub_data keyword
Definition in file detect-dce-stub-data.c.
Function Documentation
int DetectDceStubDataMatch (ThreadVars * , DetectEngineThreadCtx * , Flow * , uint8_t , void * , Signature * , SigMatch *)
void DetectDceStubDataRegister (void)
Registers the keyword handlers for the "dce_stub_data" keyword.
Definition at line 59 of file detect-dce-stub-data.c.
References SigTableElmt_::alproto, ALPROTO_DCERPC, SigTableElmt_::AppLayerMatch, DETECT_DCE_STUB_DATA, DetectDceStubDataRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void DetectDceStubDataRegisterTests (void)
Definition at line 1837 of file detect-dce-stub-data.c.
Referenced by DetectDceStubDataRegister().