suricata: src/detect-dsize.c File Reference
detect-dsize.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "flow-var.h"
#include "detect-dsize.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "util-byte.h"
#include "pkt-var.h"
#include "host.h"
#include "util-profiling.h"
Macros
#define PARSE_REGEX "^\\s*(<|>)?\\s*([0-9]{1,5})\\s*(?:(<>)\\s*([0-9]{1,5}))?\\s*$"
#define MAX_SUBSTRINGS 30
Functions
int DetectDsizeMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, const SigMatchCtx *)
void DsizeRegisterTests (void)
this function registers unit tests for dsize
void DetectDsizeRegister (void)
Registration function for dsize: keyword.
DetectDsizeData * DetectDsizeParse (char *rawstr)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements the dsize keyword
Definition in file detect-dsize.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectDsizeParse().
#define PARSE_REGEX "^\\s*(<|>)?\\s*([0-9]{1,5})\\s*(?:(<>)\\s*([0-9]{1,5}))?\\s*$"
dsize:[<>]<0-65535>[<><0-65535>];
Definition at line 47 of file detect-dsize.c.
Referenced by DetectDsizeRegister().
Function Documentation
int DetectDsizeMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Definition at line 106 of file detect-dsize.c.
References DETECTDSIZE_EQ, DETECTDSIZE_GT, DETECTDSIZE_LT, DETECTDSIZE_RA, DetectDsizeData_::dsize, DetectDsizeData_::dsize2, DetectDsizeData_::mode, Packet_::payload_len, PKT_IS_PSEUDOPKT, SCEnter, SCLogDebug, and SCReturnInt.
Referenced by DetectDsizeRegister().
DetectDsizeData* DetectDsizeParse (char * rawstr)
set the first dsize value
set the second dsize value if specified
Definition at line 140 of file detect-dsize.c.
References ByteExtractStringUint16(), DETECTDSIZE_EQ, DETECTDSIZE_GT, DETECTDSIZE_LT, DETECTDSIZE_RA, DetectDsizeData_::dsize, DetectDsizeData_::dsize2, MAX_SUBSTRINGS, DetectDsizeData_::mode, SC_ERR_INVALID_ARGUMENT, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogDebug, SCLogError, SCMalloc, and unlikely.
void DetectDsizeRegister (void)
Registration function for dsize: keyword.
Definition at line 59 of file detect-dsize.c.
References SigTableElmt_::desc, DETECT_DSIZE, DetectDsizeMatch(), DsizeRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DsizeRegisterTests (void)
this function registers unit tests for dsize
Definition at line 811 of file detect-dsize.c.
Referenced by DetectDsizeRegister().