suricata: src/detect-app-layer-protocol.h File Reference
detect-app-layer-protocol.h File Reference
Data Structures
struct DetectAppLayerProtocolData_
Typedefs
typedef struct
DetectAppLayerProtocolData_ DetectAppLayerProtocolData
Functions
void DetectAppLayerProtocolRegister (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-app-layer-protocol.h.
Typedef Documentation
typedef struct DetectAppLayerProtocolData_ DetectAppLayerProtocolData
Function Documentation
void DetectAppLayerProtocolRegister (void)
Definition at line 135 of file detect-app-layer-protocol.c.
References SigTableElmt_::AppLayerMatch, DETECT_AL_APP_LAYER_PROTOCOL, DetectAppLayerProtocolFree(), DetectAppLayerProtocolMatch(), DetectAppLayerProtocolRegisterTests(), DetectAppLayerProtocolSetup(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().