suricata: src/detect-detection-filter.c File Reference
detect-detection-filter.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "host.h"
#include "detect-detection-filter.h"
#include "detect-threshold.h"
#include "detect-parse.h"
#include "util-byte.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
Macros
#define TRACK_DST 1
#define TRACK_SRC 2
#define PARSE_REGEX "^\\s*(track|count|seconds)\\s+(by_src|by_dst|\\d+)\\s*,\\s*(track|count|seconds)\\s+(by_src|by_dst|\\d+)\\s*,\\s*(track|count|seconds)\\s+(by_src|by_dst|\\d+)\\s*$"
Regex for parsing our detection_filter options.
#define MAX_SUBSTRINGS 30
Functions
int DetectDetectionFilterMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, const SigMatchCtx *)
void DetectDetectionFilterRegisterTests (void)
void DetectDetectionFilterFree (void *)
void DetectDetectionFilterRegister (void)
Registration function for detection_filter: keyword.
DetectThresholdData * DetectDetectionFilterParse (char *rawstr)
Detailed Description
Author
Gerardo Iglesias igles.nosp@m.iasg.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Implements the detection_filter keyword
Definition in file detect-detection-filter.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectDetectionFilterParse().
#define PARSE_REGEX "^\\s*(track|count|seconds)\\s+(by_src|by_dst|\\d+)\\s*,\\s*(track|count|seconds)\\s+(by_src|by_dst|\\d+)\\s*,\\s*(track|count|seconds)\\s+(by_src|by_dst|\\d+)\\s*$"
Regex for parsing our detection_filter options.
Definition at line 49 of file detect-detection-filter.c.
Referenced by DetectDetectionFilterRegister().
#define TRACK_DST 1
Definition at line 43 of file detect-detection-filter.c.
Referenced by DetectDetectionFilterParse(), PacketAlertThreshold(), and ThresholdHandlePacketSuppress().
#define TRACK_SRC 2
Definition at line 44 of file detect-detection-filter.c.
Referenced by DetectDetectionFilterParse(), PacketAlertThreshold(), and ThresholdHandlePacketSuppress().
Function Documentation
void DetectDetectionFilterFree (void * df_ptr)
Definition at line 277 of file detect-detection-filter.c.
References SCFree.
Referenced by DetectDetectionFilterRegister().
int DetectDetectionFilterMatch (ThreadVars * thv, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Definition at line 97 of file detect-detection-filter.c.
Referenced by DetectDetectionFilterRegister().
DetectThresholdData* DetectDetectionFilterParse (char * rawstr)
Definition at line 111 of file detect-detection-filter.c.
References ByteExtractStringUint32(), DetectThresholdData_::count, MAX_SUBSTRINGS, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogError, SCMalloc, SCStrdup, DetectThresholdData_::seconds, DetectThresholdData_::track, TRACK_DST, TRACK_SRC, DetectThresholdData_::type, TYPE_DETECTION, and unlikely.
void DetectDetectionFilterRegister (void)
Registration function for detection_filter: keyword.
Registration function for detection_filter: keyword
Definition at line 62 of file detect-detection-filter.c.
References SigTableElmt_::desc, DETECT_DETECTION_FILTER, DetectDetectionFilterFree(), DetectDetectionFilterMatch(), DetectDetectionFilterRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectDetectionFilterRegisterTests (void)
This function registers unit tests for detection_filter
Definition at line 651 of file detect-detection-filter.c.
Referenced by DetectDetectionFilterRegister().