suricata: src/detect-ipopts.h File Reference
detect-ipopts.h File Reference
#include "decode-events.h"
#include "decode-ipv4.h"
Data Structures
struct DetectIpOptsData_
Typedefs
typedef struct DetectIpOptsData_ DetectIpOptsData
Functions
void DetectIpOptsRegister (void)
Registration function for ipopts: keyword.
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Definition in file detect-ipopts.h.
Typedef Documentation
DetectIpOptsData
A typedef for DetectIpOptsData_
Function Documentation
void DetectIpOptsRegister (void)
Registration function for ipopts: keyword.
Registration function for ipopts: keyword
Definition at line 57 of file detect-ipopts.c.
References SigTableElmt_::desc, DETECT_IPOPTS, DetectIpOptsFree(), DetectIpOptsMatch(), SigTableElmt_::Free, IpOptsRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().