suricata: src/detect-urilen.h File Reference
detect-urilen.h File Reference
Data Structures
struct DetectUrilenData_
Macros
#define DETECT_URILEN_LT 0
#define DETECT_URILEN_GT 1
#define DETECT_URILEN_RA 2
#define DETECT_URILEN_EQ 3
Typedefs
typedef struct DetectUrilenData_ DetectUrilenData
Functions
int DetectUrilenMatch (ThreadVars *, DetectEngineThreadCtx *, Flow *, uint8_t, void *, Signature *, SigMatch *)
void DetectUrilenRegister (void)
Registration function for urilen: keyword.
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.sighd.nosp@m.ahiy.nosp@m.a@gma.nosp@m.il.c.nosp@m.om
Definition in file detect-urilen.h.
Macro Definition Documentation
#define DETECT_URILEN_EQ 3
equal operator
Definition at line 30 of file detect-urilen.h.
Referenced by DetectUrilenParse().
#define DETECT_URILEN_GT 1
"greater than" operator
Definition at line 28 of file detect-urilen.h.
Referenced by DetectUrilenParse().
#define DETECT_URILEN_LT 0
"less than" operator
Definition at line 27 of file detect-urilen.h.
Referenced by DetectUrilenParse().
#define DETECT_URILEN_RA 2
range operator
Definition at line 29 of file detect-urilen.h.
Referenced by DetectUrilenParse().
Typedef Documentation
typedef struct DetectUrilenData_ DetectUrilenData
Function Documentation
int DetectUrilenMatch (ThreadVars * , DetectEngineThreadCtx * , Flow * , uint8_t , void * , Signature * , SigMatch *)
void DetectUrilenRegister (void)
Registration function for urilen: keyword.
< We handle this at detect-engine-uri.c now
Definition at line 60 of file detect-urilen.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, SigTableElmt_::desc, DETECT_AL_URILEN, DetectUrilenFree(), DetectUrilenRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, pcre_free_study, SigTableElmt_::RegisterTests, SCLogDebug, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().