suricata: src/detect-fragoffset.c File Reference
detect-fragoffset.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "decode-ipv4.h"
#include "decode-ipv6.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-fragoffset.h"
#include "util-byte.h"
#include "util-unittest.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^\\s*(?:(<|>))?\\s*([0-9]+)"
#define MAX_SUBSTRINGS 30
Functions
int DetectFragOffsetMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match fragoffset rule option set on a packet.
void DetectFragOffsetRegisterTests (void)
void DetectFragOffsetFree (void *ptr)
this function will free memory associated with DetectFragOffsetData
void DetectFragOffsetRegister (void)
Registration function for fragoffset.
DetectFragOffsetData * DetectFragOffsetParse (char *fragoffsetstr)
This function is used to parse fragoffset option passed via fragoffset: keyword.
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Implements fragoffset keyword
Definition in file detect-fragoffset.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectFragOffsetParse().
#define PARSE_REGEX "^\\s*(?:(<|>))?\\s*([0-9]+)"
Definition at line 41 of file detect-fragoffset.c.
Referenced by DetectFragOffsetRegister().
Function Documentation
void DetectFragOffsetFree (void * ptr)
this function will free memory associated with DetectFragOffsetData
Parameters
ptr pointer to DetectFragOffsetData
Definition at line 252 of file detect-fragoffset.c.
References SCFree.
Referenced by DetectFragOffsetParse(), and DetectFragOffsetRegister().
int DetectFragOffsetMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match fragoffset rule option set on a packet.
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectFragOffsetData
Return values
0 no match or frag is not set
1 match
Definition at line 97 of file detect-fragoffset.c.
References FRAG_LESS, FRAG_MORE, DetectFragOffsetData_::frag_off, IPV4_GET_IPOFFSET, IPV6_EXTHDR_FH, IPV6_EXTHDR_GET_FH_OFFSET, DetectFragOffsetData_::mode, PKT_IS_IPV4, PKT_IS_IPV6, PKT_IS_PSEUDOPKT, and SCLogDebug.
Referenced by DetectFragOffsetRegister().
DetectFragOffsetData* DetectFragOffsetParse (char * fragoffsetstr)
This function is used to parse fragoffset option passed via fragoffset: keyword.
Parameters
fragoffsetstr Pointer to the user provided fragoffset options
Return values
fragoff pointer to DetectFragOffsetData on success
NULL on failure
Definition at line 140 of file detect-fragoffset.c.
References ByteExtractStringUint16(), DetectFragOffsetFree(), FRAG_LESS, FRAG_MORE, DetectFragOffsetData_::frag_off, MAX_SUBSTRINGS, DetectFragOffsetData_::mode, SC_ERR_INVALID_ARGUMENT, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogError, SCMalloc, and unlikely.
void DetectFragOffsetRegister (void)
Registration function for fragoffset.
Definition at line 54 of file detect-fragoffset.c.
References SigTableElmt_::desc, DETECT_FRAGOFFSET, DetectFragOffsetFree(), DetectFragOffsetMatch(), DetectFragOffsetRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectFragOffsetRegisterTests (void)
Definition at line 387 of file detect-fragoffset.c.
Referenced by DetectFragOffsetRegister().