suricata: src/detect-priority.c File Reference
detect-priority.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-unittest.h"
Macros
#define DETECT_PRIORITY_REGEX "^\\s*(\\d+|\"\\d+\")\\s*$"
#define MAX_SUBSTRINGS 30
Functions
void SCPriorityRegisterTests (void)
This function registers unit tests for Classification Config API.
void DetectPriorityRegister (void)
Registers the handler functions for the "priority" keyword.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements the priority keyword
Definition in file detect-priority.c.
Macro Definition Documentation
#define DETECT_PRIORITY_REGEX "^\\s*(\\d+|\"\\d+\")\\s*$"
Definition at line 36 of file detect-priority.c.
Referenced by DetectPriorityRegister().
#define MAX_SUBSTRINGS 30
Function Documentation
void DetectPriorityRegister (void)
Registers the handler functions for the "priority" keyword.
Definition at line 47 of file detect-priority.c.
References SigTableElmt_::desc, DETECT_PRIORITY, DETECT_PRIORITY_REGEX, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SCPriorityRegisterTests(), SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void SCPriorityRegisterTests (void)
This function registers unit tests for Classification Config API.
Definition at line 211 of file detect-priority.c.
Referenced by DetectPriorityRegister().