suricata: src/detect-ttl.c File Reference
detect-ttl.c File Reference
#include "suricata-common.h"
#include "stream-tcp.h"
#include "util-unittest.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-ttl.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^\\s*([0-9]*)?\\s*([<>=-]+)?\\s*([0-9]+)?\\s*$"
Regex for parsing our flow options.
#define MAX_SUBSTRINGS 30
Functions
int DetectTtlMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match TTL rule option on a packet with those passed via ttl:
void DetectTtlFree (void *ptr)
this function will free memory associated with DetectTtlData
void DetectTtlRegisterTests (void)
this function registers unit tests for DetectTtl
void DetectTtlRegister (void)
Registration function for ttl: keyword.
DetectTtlData * DetectTtlParse (char *ttlstr)
This function is used to parse ttl options passed via ttl: keyword.
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.sighd.nosp@m.ahiy.nosp@m.a@gma.nosp@m.il.c.nosp@m.om
Implements the ttl keyword
Definition in file detect-ttl.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectTtlParse().
#define PARSE_REGEX "^\\s*([0-9]*)?\\s*([<>=-]+)?\\s*([0-9]+)?\\s*$"
Regex for parsing our flow options.
Definition at line 39 of file detect-ttl.c.
Referenced by DetectTtlRegister().
Function Documentation
void DetectTtlFree (void * ptr)
this function will free memory associated with DetectTtlData
Parameters
ptr pointer to DetectTtlData
Definition at line 309 of file detect-ttl.c.
References SCFree.
Referenced by DetectTtlRegister().
int DetectTtlMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match TTL rule option on a packet with those passed via ttl:
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectTtlData
Return values
0 no match
1 match
Definition at line 98 of file detect-ttl.c.
References DETECT_TTL_EQ, DETECT_TTL_GT, DETECT_TTL_LT, DETECT_TTL_RA, IPV4_GET_IPTTL, IPV6_GET_HLIM, DetectTtlData_::mode, PKT_IS_IPV4, PKT_IS_IPV6, PKT_IS_PSEUDOPKT, SCLogDebug, and DetectTtlData_::ttl1.
Referenced by DetectTtlRegister().
DetectTtlData* DetectTtlParse (char * ttlstr)
This function is used to parse ttl options passed via ttl: keyword.
Parameters
ttlstr Pointer to the user provided ttl options
Return values
ttld pointer to DetectTtlData on success
NULL on failure
Definition at line 138 of file detect-ttl.c.
References DETECT_TTL_EQ, DETECT_TTL_GT, DETECT_TTL_LT, DETECT_TTL_RA, MAX_SUBSTRINGS, DetectTtlData_::mode, SC_ERR_INVALID_SIGNATURE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogDebug, SCLogError, SCMalloc, DetectTtlData_::ttl1, DetectTtlData_::ttl2, and unlikely.
void DetectTtlRegister (void)
Registration function for ttl: keyword.
Definition at line 54 of file detect-ttl.c.
References SigTableElmt_::desc, DETECT_TTL, DetectTtlFree(), DetectTtlMatch(), DetectTtlRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCFree, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectTtlRegisterTests (void)
this function registers unit tests for DetectTtl
Definition at line 625 of file detect-ttl.c.
Referenced by DetectTtlRegister().