suricata: src/detect-flowvar.h File Reference
detect-flowvar.h File Reference
Data Structures
struct DetectFlowvarData_
Typedefs
typedef struct DetectFlowvarData_ DetectFlowvarData
Functions
void DetectFlowvarRegister (void)
int DetectFlowvarPostMatchSetup (Signature *s, uint16_t idx)
Setup a post-match for flowvar storage We're piggyback riding the DetectFlowvarData struct.
int DetectFlowvarStoreMatch (DetectEngineThreadCtx *, uint16_t, uint8_t *, uint16_t, int)
Store flowvar in det_ctx so we can exec it post-match.
void DetectFlowvarProcessListInternal (DetectFlowvarList *fs, Flow *f, const int flow_locked)
Handle flowvar candidate list in det_ctx:
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-flowvar.h.
Typedef Documentation
typedef struct DetectFlowvarData_ DetectFlowvarData
Function Documentation
int DetectFlowvarPostMatchSetup (Signature * s, uint16_t idx)
Setup a post-match for flowvar storage We're piggyback riding the DetectFlowvarData struct.
Definition at line 254 of file detect-flowvar.c.
References SigMatch_::ctx, DETECT_FLOWVAR_POSTMATCH, DETECT_SM_LIST_POSTMATCH, DetectFlowvarData_::idx, SCMalloc, SigMatchAlloc(), SigMatchAppendSMToList(), SigMatch_::type, and unlikely.
void DetectFlowvarProcessListInternal (DetectFlowvarList * fs, Flow * f, const int flow_locked)
Handle flowvar candidate list in det_ctx:
  - clean up the list
  - enforce storage for type ALWAYS (luajit)
Only called from DetectFlowvarProcessList() when flowvarlist is not NULL .
Definition at line 334 of file detect-flowvar.c.
References DetectFlowvarList_::buffer, BUG_ON, DETECT_FLOWVAR_TYPE_ALWAYS, FlowVarAddStr(), FlowVarAddStrNoLock(), DetectFlowvarList_::idx, DetectFlowvarList_::len, DetectFlowvarList_::next, next, SCFree, SCLogDebug, and DetectFlowvarList_::type.
void DetectFlowvarRegister (void)
Definition at line 52 of file detect-flowvar.c.
References DETECT_FLOWVAR, DETECT_FLOWVAR_POSTMATCH, DetectFlowvarMatch(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
int DetectFlowvarStoreMatch (DetectEngineThreadCtx * , uint16_t , uint8_t * , uint16_t , int)
Store flowvar in det_ctx so we can exec it post-match.
Definition at line 219 of file detect-flowvar.c.
References DetectFlowvarList_::buffer, DetectEngineThreadCtx_::flowvarlist, DetectFlowvarList_::idx, len, DetectFlowvarList_::len, DetectFlowvarList_::next, SCFree, SCMalloc, type, DetectFlowvarList_::type, and unlikely.
Referenced by DetectPcrePayloadMatch().