suricata: src/detect-reference.c File Reference
detect-reference.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "decode.h"
#include "flow-var.h"
#include "decode-events.h"
#include "stream-tcp.h"
#include "util-reference-config.h"
#include "detect-reference.h"
#include "util-unittest.h"
#include "util-byte.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^\\s*([A-Za-z0-9]+)\\s*,\"?\\s*\"?\\s*([a-zA-Z0-9\\-_\\.\\/\\?\\=]+)\"?\\s*\"?"
#define MAX_SUBSTRINGS 30
Functions
void DetectReferenceRegister (void)
Registration function for the reference: keyword.
void DetectReferenceFree (DetectReference *ref)
Free a Reference object.
void ReferenceRegisterTests (void)
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements the reference keyword support
Definition in file detect-reference.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
#define PARSE_REGEX "^\\s*([A-Za-z0-9]+)\\s*,\"?\\s*\"?\\s*([a-zA-Z0-9\\-_\\.\\/\\?\\=]+)\"?\\s*\"?"
Definition at line 46 of file detect-reference.c.
Referenced by DetectReferenceRegister().
Function Documentation
void DetectReferenceFree (DetectReference *)
Free a Reference object.
Free function for a Reference object
Definition at line 92 of file detect-reference.c.
References DetectReference_::reference, SCEnter, SCFree, and SCReturn.
void DetectReferenceRegister (void)
Registration function for the reference: keyword.
Registration function for Reference keyword
Definition at line 56 of file detect-reference.c.
References SigTableElmt_::desc, DETECT_REFERENCE, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, ReferenceRegisterTests(), SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void ReferenceRegisterTests (void)
This function registers unit tests for Reference keyword.
Definition at line 367 of file detect-reference.c.
Referenced by DetectReferenceRegister().