suricata: src/detect-window.c File Reference
detect-window.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-window.h"
#include "flow.h"
#include "flow-var.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-byte.h"
Macros
#define PARSE_REGEX "^\\s*([!])?\\s*([0-9]{1,9}+)\\s*$"
Regex for parsing our window option.
#define MAX_SUBSTRINGS 30
Functions
int DetectWindowMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match the window size on a packet.
int DetectWindowSetup (DetectEngineCtx *de_ctx, Signature *s, char *windowstr)
this function is used to add the parsed window sizedata into the current signature
void DetectWindowRegisterTests (void)
this function registers unit tests for DetectWindow
void DetectWindowFree (void *ptr)
this function will free memory associated with DetectWindowData
void DetectWindowRegister (void)
Registration function for window: keyword.
DetectWindowData * DetectWindowParse (char *windowstr)
This function is used to parse window options passed via window: keyword.
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements the window keyword.
Definition in file detect-window.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectWindowParse().
#define PARSE_REGEX "^\\s*([!])?\\s*([0-9]{1,9}+)\\s*$"
Regex for parsing our window option.
Definition at line 45 of file detect-window.c.
Referenced by DetectWindowRegister().
Function Documentation
void DetectWindowFree (void * ptr)
this function will free memory associated with DetectWindowData
Parameters
wd pointer to DetectWindowData
Definition at line 231 of file detect-window.c.
References SCFree.
Referenced by DetectWindowParse(), DetectWindowRegister(), and DetectWindowSetup().
int DetectWindowMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match the window size on a packet.
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectWindowData
Return values
0 no match
1 match
Definition at line 107 of file detect-window.c.
References DetectWindowData_::negated, PKT_IS_PSEUDOPKT, PKT_IS_TCP, DetectWindowData_::size, and TCP_GET_WINDOW.
Referenced by DetectWindowRegister().
DetectWindowData* DetectWindowParse (char * windowstr)
This function is used to parse window options passed via window: keyword.
Parameters
windowstr Pointer to the user provided window options (negation! and size)
Return values
wd pointer to DetectWindowData on success
NULL on failure
Definition at line 130 of file detect-window.c.
References ByteExtractStringUint16(), DetectWindowFree(), MAX_SUBSTRINGS, DetectWindowData_::negated, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCLogError, SCMalloc, DetectWindowData_::size, and unlikely.
Referenced by DetectWindowSetup().
void DetectWindowRegister (void)
Registration function for window: keyword.
Definition at line 58 of file detect-window.c.
References SigTableElmt_::desc, DETECT_WINDOW, DetectWindowFree(), DetectWindowMatch(), DetectWindowRegisterTests(), DetectWindowSetup(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectWindowRegisterTests (void)
this function registers unit tests for DetectWindow
Definition at line 358 of file detect-window.c.
Referenced by DetectWindowRegister().
int DetectWindowSetup (DetectEngineCtx * de_ctx, Signature * s, char * windowstr)
this function is used to add the parsed window sizedata into the current signature
Parameters
de_ctx pointer to the Detection Engine Context
s pointer to the Current Signature
windowstr pointer to the user provided window options
Return values
0 on Success
-1 on Failure
Definition at line 197 of file detect-window.c.
References SigMatch_::ctx, DETECT_SM_LIST_MATCH, DETECT_WINDOW, DetectWindowFree(), DetectWindowParse(), Signature_::flags, SCFree, SIG_FLAG_REQUIRE_PACKET, SigMatchAlloc(), SigMatchAppendSMToList(), and SigMatch_::type.
Referenced by DetectWindowRegister().