suricata: src/detect-engine-hrl.h File Reference
detect-engine-hrl.h File Reference
Functions
int DetectEngineInspectHttpRequestLine (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *tx, uint64_t tx_id)
Do the content inspection & validation for a signature.
void HttpRequestLineRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-engine-hrl.h.
Function Documentation
int DetectEngineInspectHttpRequestLine (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * txv, uint64_t tx_id)
Do the content inspection & validation for a signature.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
sm SigMatch to inspect
f Flow
flags app layer flags
state App layer state
Return values
0 no match.
1 match.
2 Sig can't match.
Definition at line 65 of file detect-engine-hrl.c.
References ALPROTO_HTTP, AppLayerParserGetStateProgress(), bstr_len, bstr_ptr, DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HRL, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DETECT_SM_LIST_HRLMATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, HTP_REQUEST_LINE, DetectEngineThreadCtx_::inspection_recursion_counter, PrintRawDataFp(), htp_tx_t::request_line, and Signature_::sm_lists.
Referenced by DetectEngineRegisterAppInspectionEngines().
void HttpRequestLineRegisterTests (void)
Definition at line 4175 of file detect-engine-hrl.c.