suricata: src/detect-tls-version.c File Reference
detect-tls-version.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-ssl.h"
#include "detect-tls-version.h"
#include "stream-tcp.h"
Macros
#define PARSE_REGEX "^\\s*([A-z0-9\\.]+|\"[A-z0-9\\.]+\")\\s*$"
Regex for parsing "id" option, matching number or "number".
#define MAX_SUBSTRINGS 30
Functions
int DetectTlsVersionMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Flow *f, uint8_t flags, void *state, Signature *s, SigMatch *m)
match the specified version on a tls session
void DetectTlsVersionRegisterTests (void)
this function registers unit tests for DetectTlsVersion
void DetectTlsVersionFree (void *ptr)
this function will free memory associated with DetectTlsVersionData
void DetectTlsVersionRegister (void)
Registration function for keyword: tls.version.
DetectTlsVersionData * DetectTlsVersionParse (char *str)
This function is used to parse IPV4 ip_id passed via keyword: "id".
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements the tls.version keyword
Definition in file detect-tls-version.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectTlsVersionParse().
#define PARSE_REGEX "^\\s*([A-z0-9\\.]+|\"[A-z0-9\\.]+\")\\s*$"
Regex for parsing "id" option, matching number or "number".
Definition at line 57 of file detect-tls-version.c.
Referenced by DetectTlsVersionRegister().
Function Documentation
void DetectTlsVersionFree (void * ptr)
this function will free memory associated with DetectTlsVersionData
Parameters
id_d pointer to DetectTlsVersionData
Definition at line 273 of file detect-tls-version.c.
References SCFree.
Referenced by DetectTlsVersionParse(), and DetectTlsVersionRegister().
int DetectTlsVersionMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Flow * f, uint8_t flags, void * state, Signature * s, SigMatch * m)
match the specified version on a tls session
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectTlsVersionData
Return values
0 no match
1 match
Definition at line 117 of file detect-tls-version.c.
References SigMatch_::ctx, SCEnter, SCLogDebug, SCReturnInt, STREAM_TOCLIENT, STREAM_TOSERVER, and DetectTlsVersionData_::ver.
Referenced by DetectTlsVersionRegister().
DetectTlsVersionData* DetectTlsVersionParse (char * str)
This function is used to parse IPV4 ip_id passed via keyword: "id".
Parameters
idstr Pointer to the user provided id option
Return values
id_d pointer to DetectTlsVersionData on success
NULL on failure
Definition at line 152 of file detect-tls-version.c.
References DetectTlsVersionFree(), MAX_SUBSTRINGS, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogDebug, SCLogError, SCMalloc, SCStrdup, TLS_VERSION_10, TLS_VERSION_11, TLS_VERSION_12, unlikely, and DetectTlsVersionData_::ver.
void DetectTlsVersionRegister (void)
Registration function for keyword: tls.version.
Definition at line 70 of file detect-tls-version.c.
References SigTableElmt_::alproto, ALPROTO_TLS, SigTableElmt_::AppLayerMatch, SigTableElmt_::desc, DETECT_AL_TLS_VERSION, DetectTlsVersionFree(), DetectTlsVersionMatch(), DetectTlsVersionRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectTlsVersionRegisterTests (void)
this function registers unit tests for DetectTlsVersion
Definition at line 712 of file detect-tls-version.c.
Referenced by DetectTlsVersionRegister().