suricata: src/detect-engine-analyzer.c File Reference
detect-engine-analyzer.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-analyzer.h"
#include "detect-engine-mpm.h"
#include "conf.h"
#include "detect-content.h"
#include "detect-flow.h"
#include "detect-flags.h"
#include "util-print.h"
Data Structures
struct FpPatternStats_
Macros
#define DETECT_PERCENT_ENCODING_REGEX "%[0-9|a-f|A-F]{2}"
#define MAX_ENCODED_CHARS 240
Typedefs
typedef struct FpPatternStats_ FpPatternStats
Functions
void EngineAnalysisFP (Signature *s, char *line)
int SetupFPAnalyzer (void)
Sets up the fast pattern analyzer according to the config.
int SetupRuleAnalyzer (void)
Sets up the rule analyzer according to the config.
void CleanupFPAnalyzer (void)
void CleanupRuleAnalyzer (void)
int PerCentEncodingSetup ()
Compiles regex for rule analysis.
int PerCentEncodingMatch (uint8_t *content, uint8_t content_len)
Checks for % encoding in content.
void EngineAnalysisRulesFailure (char *line, char *file, int lineno)
void EngineAnalysisRules (Signature *s, char *line)
Prints analysis of loaded rules.
Detailed Description
Author
Eileen Donlon emdon.nosp@m.lo@g.nosp@m.mail..nosp@m.com
Rule analyzer for the detection engine
Definition in file detect-engine-analyzer.c.
Macro Definition Documentation
#define DETECT_PERCENT_ENCODING_REGEX "%[0-9|a-f|A-F]{2}"
Referenced by PerCentEncodingSetup().
#define MAX_ENCODED_CHARS 240
Referenced by PerCentEncodingMatch().
Typedef Documentation
typedef struct FpPatternStats_ FpPatternStats
Function Documentation
void CleanupFPAnalyzer (void)
Definition at line 321 of file detect-engine-analyzer.c.
References FpPatternStats_::cnt, DETECT_SM_LIST_MAX, DetectSigmatchListEnumToString(), FpPatternStats_::max, FpPatternStats_::min, and FpPatternStats_::tot.
Referenced by SigLoadSignatures().
void CleanupRuleAnalyzer (void)
Definition at line 345 of file detect-engine-analyzer.c.
References SCLogInfo.
Referenced by SigLoadSignatures().
void EngineAnalysisFP (Signature * s, char * line)
Definition at line 74 of file detect-engine-analyzer.c.
References DetectContentData_::content, DetectContentData_::content_len, SigMatch_::ctx, DETECT_CONTENT_DEPTH, DETECT_CONTENT_DISTANCE, DETECT_CONTENT_FAST_PATTERN, DETECT_CONTENT_FAST_PATTERN_CHOP, DETECT_CONTENT_FAST_PATTERN_ONLY, DETECT_CONTENT_NEGATED, DETECT_CONTENT_NOCASE, DETECT_CONTENT_OFFSET, DETECT_CONTENT_WITHIN, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectContentData_::flags, DetectContentData_::fp_chop_len, DetectContentData_::fp_chop_offset, Signature_::id, Signature_::mpm_sm, PrintRawUriFp(), SC_ERR_MEM_ALLOC, SCFree, SCLogError, SCMalloc, SigMatchListSMBelongsTo(), and unlikely.
void EngineAnalysisRules (Signature * s, char * line)
Prints analysis of loaded rules.
   Warns if potential rule issues are detected. For example,
   warns if a rule uses a construct that may perform poorly,
   e.g. pcre without content or with http_method content only;
   warns if a rule uses a construct that may not be consistent with intent,
   e.g. client side ports only, http and content without any http_* modifiers, etc.
Parameters
s Pointer to the signature.
Definition at line 509 of file detect-engine-analyzer.c.
References Signature_::alproto, ALPROTO_HTTP, ALPROTO_UNKNOWN, AppProtoToString(), DetectContentData_::content, DetectContentData_::content_len, SigMatch_::ctx, DETECT_CONTENT, DETECT_CONTENT_DEPTH, DETECT_CONTENT_OFFSET, DETECT_FLAGS, DETECT_FLOW, DETECT_FLOW_FLAG_NOSTREAM, DETECT_FLOWBITS, DETECT_FLOWINT, DETECT_PCRE, DETECT_PROTO_ANY, DETECT_PROTO_IPV4, DETECT_PROTO_IPV6, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_MATCH, DETECT_SM_LIST_MAX, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectProtoContainsProto(), DetectFlowData_::flags, DetectProto_::flags, DetectContentData_::flags, Signature_::flags, Signature_::id, Signature_::init_flags, Signature_::mpm_sm, SigMatch_::next, PerCentEncodingMatch(), Signature_::proto, SIG_FLAG_DP_ANY, SIG_FLAG_INIT_BIDIREC, SIG_FLAG_IPONLY, SIG_FLAG_REQUIRE_PACKET, SIG_FLAG_REQUIRE_STREAM, SIG_FLAG_SP_ANY, SIG_FLAG_TOCLIENT, SIG_FLAG_TOSERVER, SigMatchListSMBelongsTo(), Signature_::sm_lists, and SigMatch_::type.
void EngineAnalysisRulesFailure (char * line, char * file, int lineno)
Definition at line 488 of file detect-engine-analyzer.c.
int PerCentEncodingMatch (uint8_t * content, uint8_t content_len)
Checks for % encoding in content.
Parameters
Pointer to content
Return values
number of matches if content has % encoding
0 if it doesn't have % encoding
-1 on error
Definition at line 388 of file detect-engine-analyzer.c.
References MAX_ENCODED_CHARS, SC_ERR_PCRE_MATCH, and SCLogError.
Referenced by EngineAnalysisRules().
int PerCentEncodingSetup ()
Compiles regex for rule analysis.
Return values
1 if successful
0 if on error
Definition at line 359 of file detect-engine-analyzer.c.
References DETECT_PERCENT_ENCODING_REGEX, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, and SCLogError.
Referenced by SetupRuleAnalyzer().
int SetupFPAnalyzer (void)
Sets up the fast pattern analyzer according to the config.
Return values
1 If rule analyzer successfully enabled.
0 If not enabled.
Definition at line 215 of file detect-engine-analyzer.c.
References ConfGetBool(), ConfigGetLogDirectory(), SC_ERR_FOPEN, SCLocalTime(), SCLogError, and SCLogInfo.
Referenced by SigLoadSignatures().
int SetupRuleAnalyzer (void)
Sets up the rule analyzer according to the config.
Return values
1 if rule analyzer successfully enabled
0 if not enabled
Definition at line 265 of file detect-engine-analyzer.c.
References ConfGetNode(), ConfigGetLogDirectory(), ConfNodeLookupChildValue(), ConfValIsTrue(), PerCentEncodingSetup(), SC_ERR_FOPEN, SCLocalTime(), SCLogError, and SCLogInfo.
Referenced by SigLoadSignatures().