suricata: src/detect-engine-event.h File Reference
detect-engine-event.h File Reference
#include "decode-events.h"
Data Structures
struct DetectEngineEventData_
Typedefs
typedef struct
DetectEngineEventData_ DetectEngineEventData
Functions
void DetectEngineEventRegister (void)
Registration function for decode-event: keyword.
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Definition in file detect-engine-event.h.
Typedef Documentation
typedef struct DetectEngineEventData_ DetectEngineEventData
Function Documentation
void DetectEngineEventRegister (void)
Registration function for decode-event: keyword.
Definition at line 62 of file detect-engine-event.c.
References DETECT_DECODE_EVENT, DETECT_ENGINE_EVENT, DETECT_STREAM_EVENT, DetectEngineEventMatch(), EngineEventRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_DEONLY_COMPAT, and sigmatch_table.
Referenced by SigTableSetup().