suricata: src/detect-engine-payload.c File Reference
detect-engine-payload.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-parse.h"
#include "detect-engine-content-inspection.h"
#include "util-debug.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
Functions
int DetectEngineInspectPacketPayload (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, Packet *p)
Do the content inspection & validation for a signature.
int DetectEngineInspectStreamPayload (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t *payload, uint32_t payload_len)
Do the content inspection & validation for a signature for a stream chunk.
void PayloadRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Performs payload matching functions
Definition in file detect-engine-payload.c.
Function Documentation
int DetectEngineInspectPacketPayload (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, Packet * p)
Do the content inspection & validation for a signature.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
f flow (for pcre flowvar storage)
p Packet
Return values
0 no match
1 match
Definition at line 54 of file detect-engine-payload.c.
References DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_PAYLOAD, DETECT_SM_LIST_PMATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, DetectEngineThreadCtx_::inspection_recursion_counter, Packet_::payload, Packet_::payload_len, DetectEngineThreadCtx_::replist, SCEnter, SCReturnInt, and Signature_::sm_lists.
Referenced by SigMatchSignatures().
int DetectEngineInspectStreamPayload (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t * payload, uint32_t payload_len)
Do the content inspection & validation for a signature for a stream chunk.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
f flow (for pcre flowvar storage)
payload ptr to the payload to inspect
payload_len length of the payload
Return values
0 no match
1 match
Todo:
we might also pass the packet to this function for the pktvar storage. Only, would that be right? We're not inspecting data from the current packet here.
Definition at line 98 of file detect-engine-payload.c.
References DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_STREAM, DETECT_SM_LIST_PMATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, DetectEngineThreadCtx_::inspection_recursion_counter, SCEnter, SCReturnInt, and Signature_::sm_lists.
Referenced by SigMatchSignatures().
void PayloadRegisterTests (void)
Definition at line 1071 of file detect-engine-payload.c.
Referenced by RunUnittests().