suricata: src/detect-engine.c File Reference
detect-engine.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "debug.h"
#include "detect.h"
#include "flow.h"
#include "flow-private.h"
#include "flow-util.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "app-layer-htp.h"
#include "detect-parse.h"
#include "detect-engine-sigorder.h"
#include "detect-engine-siggroup.h"
#include "detect-engine-address.h"
#include "detect-engine-port.h"
#include "detect-engine-mpm.h"
#include "detect-engine-hcbd.h"
#include "detect-engine-iponly.h"
#include "detect-engine-tag.h"
#include "detect-engine-uri.h"
#include "detect-engine-hsbd.h"
#include "detect-engine-hhd.h"
#include "detect-engine-hrhd.h"
#include "detect-engine-hmd.h"
#include "detect-engine-hcd.h"
#include "detect-engine-hrud.h"
#include "detect-engine-hrl.h"
#include "detect-engine-hsmd.h"
#include "detect-engine-hscd.h"
#include "detect-engine-hua.h"
#include "detect-engine-hhhd.h"
#include "detect-engine-hrhhd.h"
#include "detect-engine-file.h"
#include "detect-engine-dns.h"
#include "detect-engine-modbus.h"
#include "detect-engine-filedata-smtp.h"
#include "detect-engine-template.h"
#include "detect-engine.h"
#include "detect-engine-state.h"
#include "detect-byte-extract.h"
#include "detect-content.h"
#include "detect-uricontent.h"
#include "detect-engine-threshold.h"
#include "detect-engine-loader.h"
#include "util-classification-config.h"
#include "util-reference-config.h"
#include "util-threshold-config.h"
#include "util-error.h"
#include "util-hash.h"
#include "util-byte.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-action.h"
#include "util-magic.h"
#include "util-signal.h"
#include "util-var-name.h"
#include "tm-threads.h"
#include "runmodes.h"
#include "util-profiling.h"
#include "reputation.h"
Data Structures
struct DetectEngineSyncer_
struct TenantLoaderCtx_
Macros
#define DETECT_ENGINE_DEFAULT_INSPECTION_RECURSION_LIMIT 3000
Typedefs
typedef struct DetectEngineSyncer_ DetectEngineSyncer
typedef struct TenantLoaderCtx_ TenantLoaderCtx
Enumerations
enum DetectEngineSyncState { IDLE, RELOAD, DONE }
Functions
void DetectEngineRegisterAppInspectionEngines (void)
void DetectEngineRegisterAppInspectionEngine (uint8_t ipproto, AppProto alproto, uint16_t dir, int32_t sm_list, uint32_t inspect_flags, int(*Callback)(ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *sig, Flow *f, uint8_t flags, void *alstate, void *tx, uint64_t tx_id), DetectEngineAppInspectionEngine *list[][ALPROTO_MAX][2])
Registers an app inspection engine.
int DetectEngineReloadStart (void)
int DetectEngineReloadIsStart (void)
void DetectEngineReloadSetDone (void)
int DetectEngineReloadIsDone (void)
DetectEngineCtx * DetectEngineCtxInitMinimal (void)
DetectEngineCtx * DetectEngineCtxInit (void)
DetectEngineCtx * DetectEngineCtxInitWithPrefix (const char *prefix)
void DetectEngineCtxFree (DetectEngineCtx *de_ctx)
Free a DetectEngineCtx::
void DetectEngineResetMaxSigId (DetectEngineCtx *de_ctx)
TmEcode DetectEngineThreadCtxInit (ThreadVars *tv, void *initdata, void **data)
initialize thread specific detection engine context
void DetectEngineThreadCtxFree (DetectEngineThreadCtx *det_ctx)
TmEcode DetectEngineThreadCtxDeinit (ThreadVars *tv, void *data)
void DetectEngineThreadCtxInfo (ThreadVars *t, DetectEngineThreadCtx *det_ctx)
int DetectRegisterThreadCtxFuncs (DetectEngineCtx *de_ctx, const char *name, void *(*InitFunc)(void *), void *data, void(*FreeFunc)(void *), int mode)
Register Thread keyword context Funcs.
void * DetectThreadCtxGetKeywordThreadCtx (DetectEngineThreadCtx *det_ctx, int id)
Retrieve thread local keyword ctx by id.
int DetectEngineEnabled (void)
Check if detection is enabled.
DetectEngineCtx * DetectEngineGetCurrent (void)
DetectEngineCtx * DetectEngineReference (DetectEngineCtx *de_ctx)
int DetectEngineMultiTenantEnabled (void)
int DetectLoaderSetupLoadTenant (uint32_t tenant_id, const char *yaml)
int DetectLoaderSetupReloadTenant (uint32_t tenant_id, const char *yaml, int reload_cnt)
int DetectEngineLoadTenantBlocking (uint32_t tenant_id, const char *yaml)
Load a tenant and wait for loading to complete.
int DetectEngineReloadTenantBlocking (uint32_t tenant_id, const char *yaml, int reload_cnt)
Reload a tenant and wait for loading to complete.
void DetectEngineMultiTenantSetup (void)
setup multi-detect / multi-tenancy
uint32_t DetectEngineTentantGetIdFromVlanId (const void *ctx, const Packet *p)
int DetectEngineTentantRegisterVlanId (uint32_t tenant_id, uint16_t vlan_id)
int DetectEngineTentantUnregisterVlanId (uint32_t tenant_id, uint16_t vlan_id)
int DetectEngineTentantRegisterPcapFile (uint32_t tenant_id)
int DetectEngineTentantUnregisterPcapFile (uint32_t tenant_id)
uint32_t DetectEngineTentantGetIdFromPcap (const void *ctx, const Packet *p)
DetectEngineCtx * DetectEngineGetByTenantId (int tenant_id)
void DetectEngineDeReference (DetectEngineCtx **de_ctx)
int DetectEngineAddToMaster (DetectEngineCtx *de_ctx)
int DetectEngineMoveToFreeList (DetectEngineCtx *de_ctx)
void DetectEnginePruneFreeList (void)
int DetectEngineReload (const char *filename, SCInstance *suri)
Reload the detection engine.
int DetectEngineMTApply (void)
const char * DetectSigmatchListEnumToString (enum DetectSigmatchListEnum type)
void DetectEngineRegisterTests ()
Variables
DetectEngineAppInspectionEngine * app_inspection_engine [FLOW_PROTO_DEFAULT][ALPROTO_MAX][2]
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-engine.c.
Macro Definition Documentation
#define DETECT_ENGINE_DEFAULT_INSPECTION_RECURSION_LIMIT 3000
Definition at line 100 of file detect-engine.c.
Typedef Documentation
typedef struct DetectEngineSyncer_ DetectEngineSyncer
typedef struct TenantLoaderCtx_ TenantLoaderCtx
Enumeration Type Documentation
enum DetectEngineSyncState
Enumerator
IDLE
ready to start a reload
RELOAD
command main thread to do the reload
DONE
main thread telling us reload is done
Definition at line 479 of file detect-engine.c.
Function Documentation
int DetectEngineAddToMaster (DetectEngineCtx * de_ctx)
Definition at line 2237 of file detect-engine.c.
References DetectEngineMasterCtx_::lock, SCLogDebug, SCMutexLock, and SCMutexUnlock.
Referenced by DetectEngineReload(), and main().
void DetectEngineCtxFree (DetectEngineCtx * de_ctx)
Free a DetectEngineCtx::
Parameters
de_ctx DetectEngineCtx:: to be freed
Definition at line 894 of file detect-engine.c.
References ConfDump(), ConfGetNode(), DetectEngineCtx_::config_prefix, ConfNodeRemove(), DetectParseDupSigHashFree(), DetectPortDpHashFree(), DetectPortSpHashFree(), ENGINE_SGH_MPM_FACTORY_CONTEXT_SINGLE, DetectEngineCtx_::mpm_pattern_id_store, MpmFactoryDeRegisterAllMpmCtxProfiles(), MpmPatternIdTableFreeHash(), DetectEngineCtx_::profile_ctx, DetectEngineCtx_::profile_keyword_ctx, SCClassConfDeInitContext(), SCFree, SCProfilingKeywordDestroyCtx(), SCProfilingRuleDestroyCtx(), SCRConfDeInitContext(), SCSigSignatureOrderingModuleCleanup(), DetectEngineCtx_::sgh_mpm_context, DetectEngineCtx_::sig_array, SigCleanSignatures(), SigGroupCleanup(), SigGroupHeadDPortHashFree(), SigGroupHeadHashFree(), SigGroupHeadMpmHashFree(), SigGroupHeadMpmUriHashFree(), SigGroupHeadSPortHashFree(), SRepDestroy(), ThresholdContextDestroy(), and VariableNameFreeHash().
Referenced by DetectEnginePruneFreeList(), and DetectEngineReload().
DetectEngineCtx* DetectEngineCtxInit (void)
Definition at line 865 of file detect-engine.c.
Referenced by DetectEngineCtxInitWithPrefix(), and main().
DetectEngineCtx* DetectEngineCtxInitMinimal (void)
Definition at line 860 of file detect-engine.c.
Referenced by DetectEngineMTApply(), and main().
DetectEngineCtx* DetectEngineCtxInitWithPrefix (const char * prefix)
Definition at line 870 of file detect-engine.c.
References DetectEngineCtxInit().
Referenced by DetectEngineReload().
void DetectEngineDeReference (DetectEngineCtx ** de_ctx)
Definition at line 2213 of file detect-engine.c.
References BUG_ON.
Referenced by DetectEngineReload(), DetectEngineThreadCtxFree(), DetectLoaderSetupReloadTenant(), and main().
int DetectEngineEnabled (void)
Check if detection is enabled.
Return values
bool true or false
Definition at line 1648 of file detect-engine.c.
References DetectEngineMasterCtx_::list, DetectEngineMasterCtx_::lock, SCMutexLock, and SCMutexUnlock.
Referenced by main(), RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), and RunModeSetLiveCaptureAutoFp().
DetectEngineCtx* DetectEngineGetByTenantId (int tenant_id)
Definition at line 2189 of file detect-engine.c.
References DetectEngineMasterCtx_::list, DetectEngineMasterCtx_::lock, DetectEngineCtx_::next, DetectEngineCtx_::ref_cnt, SCMutexLock, SCMutexUnlock, and DetectEngineCtx_::tenant_id.
Referenced by DetectLoaderSetupReloadTenant().
DetectEngineCtx* DetectEngineGetCurrent (void)
Definition at line 1662 of file detect-engine.c.
References DetectEngineMasterCtx_::list, DetectEngineMasterCtx_::lock, DetectEngineCtx_::ref_cnt, SCLogDebug, SCMutexLock, and SCMutexUnlock.
Referenced by DetectEngineReload(), DetectEngineThreadCtxInit(), and main().
int DetectEngineLoadTenantBlocking (uint32_t tenant_id, const char * yaml)
Load a tenant and wait for loading to complete.
Definition at line 1879 of file detect-engine.c.
References DetectLoaderSetupLoadTenant(), and DetectLoadersSync().
int DetectEngineMoveToFreeList (DetectEngineCtx * de_ctx)
Definition at line 2253 of file detect-engine.c.
References DetectEngineMasterCtx_::free_list, DetectEngineMasterCtx_::list, DetectEngineMasterCtx_::lock, next, DetectEngineCtx_::next, DetectEngineCtx_::ref_cnt, SCLogDebug, SCMutexLock, and SCMutexUnlock.
Referenced by DetectEngineReload(), and main().
int DetectEngineMTApply (void)
Definition at line 2555 of file detect-engine.c.
References DetectEngineCtxInitMinimal(), DetectEnginePruneFreeList(), DetectEngineMasterCtx_::list, DetectEngineMasterCtx_::lock, DetectEngineCtx_::next, SCLogDebug, SCLogInfo, SCMutexLock, SCMutexUnlock, DetectEngineCtx_::tenant_id, DetectEngineMasterCtx_::tenant_selector, and TENANT_SELECTOR_UNKNOWN.
Referenced by DetectEngineMultiTenantSetup().
int DetectEngineMultiTenantEnabled (void)
TODO locking? Not needed if this is a one time setting at startup
Definition at line 1687 of file detect-engine.c.
References DetectEngineMasterCtx_::multi_tenant_enabled.
Referenced by DetectEngineThreadCtxInit().
void DetectEngineMultiTenantSetup (void)
setup multi-detect / multi-tenancy
See if MT is enabled. If so, setup the selector, tenants and mappings. Tenants and mappings are optional, and can also dynamically be added and removed from the unix socket.
Definition at line 1912 of file detect-engine.c.
References ByteExtractStringUint16(), ByteExtractStringUint32(), ConfGet(), ConfGetBool(), ConfGetNode(), ConfNodeLookupChild(), ConfYamlLoadFileWithPrefix(), DetectEngineMTApply(), DetectEngineTentantRegisterVlanId(), DetectLoaderSetupLoadTenant(), DetectLoadersInit(), DetectLoadersSync(), DetectLoaderThreadSpawn(), DetectEngineMasterCtx_::lock, DetectEngineMasterCtx_::multi_tenant_enabled, next, SC_ERR_CONF_YAML_ERROR, SC_ERR_DETECT_PREPARE, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SCLogDebug, SCLogError, SCLogInfo, SCLogWarning, SCMutexLock, SCMutexUnlock, TAILQ_FOREACH, DetectEngineMasterCtx_::tenant_selector, TENANT_SELECTOR_DIRECT, TENANT_SELECTOR_VLAN, TmModuleDetectLoaderRegister(), TmThreadContinueDetectLoaderThreads(), and ConfNode_::val.
Referenced by main().
void DetectEnginePruneFreeList (void)
Definition at line 2304 of file detect-engine.c.
References DetectEngineCtxFree(), DetectEngineMasterCtx_::free_list, DetectEngineMasterCtx_::lock, next, DetectEngineCtx_::next, DetectEngineCtx_::ref_cnt, SCLogDebug, SCMutexLock, and SCMutexUnlock.
Referenced by DetectEngineMTApply(), DetectEngineReload(), and main().
DetectEngineCtx* DetectEngineReference (DetectEngineCtx * de_ctx)
Definition at line 1678 of file detect-engine.c.
References DetectEngineCtx_::ref_cnt.
void DetectEngineRegisterAppInspectionEngine (uint8_t ipproto, AppProto alproto, uint16_t direction, int32_t sm_list, uint32_t inspect_flags, int(*)(ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *sig, Flow *f, uint8_t flags, void *alstate, void *tx, uint64_t tx_id) Callback, DetectEngineAppInspectionEngine * list[][ALPROTO_MAX][2])
Registers an app inspection engine.
Parameters
alproto App layer protocol for which we will register the engine.
direction The direction for the engine. 0 - toserver; 1- toclient.
sm_list The SigMatch list against which the engine works.
inspect_flags The inspection flags to be used by de_state against the engine.
match_flags The match flags to be used by de_state in tandem with the inpsect_flags.
Callback The engine callback.
Definition at line 429 of file detect-engine.c.
References DetectEngineAppInspectionEngine_::alproto, ALPROTO_FAILED, DetectEngineAppInspectionEngine_::Callback, DETECT_SM_LIST_MAX, DetectEngineAppInspectionEngine_::dir, FlowGetProtoMapping(), DetectEngineAppInspectionEngine_::inspect_flags, DetectEngineAppInspectionEngine_::ipproto, DetectEngineAppInspectionEngine_::next, SC_ERR_INVALID_ARGUMENTS, SCLogError, SCMalloc, DetectEngineAppInspectionEngine_::sm_list, and unlikely.
Referenced by DetectEngineRegisterAppInspectionEngines().
void DetectEngineRegisterAppInspectionEngines (void)
Definition at line 147 of file detect-engine.c.
References ALPROTO_DNS, ALPROTO_HTTP, ALPROTO_MODBUS, ALPROTO_SMTP, ALPROTO_TEMPLATE, DE_STATE_FLAG_DNSQUERYNAME_INSPECT, DE_STATE_FLAG_DNSREQUEST_INSPECT, DE_STATE_FLAG_DNSRESPONSE_INSPECT, DE_STATE_FLAG_FD_SMTP_INSPECT, DE_STATE_FLAG_FILE_TC_INSPECT, DE_STATE_FLAG_FILE_TS_INSPECT, DE_STATE_FLAG_HCBD_INSPECT, DE_STATE_FLAG_HCD_INSPECT, DE_STATE_FLAG_HHD_INSPECT, DE_STATE_FLAG_HHHD_INSPECT, DE_STATE_FLAG_HMD_INSPECT, DE_STATE_FLAG_HRHD_INSPECT, DE_STATE_FLAG_HRHHD_INSPECT, DE_STATE_FLAG_HRL_INSPECT, DE_STATE_FLAG_HRUD_INSPECT, DE_STATE_FLAG_HSBD_INSPECT, DE_STATE_FLAG_HSCD_INSPECT, DE_STATE_FLAG_HSMD_INSPECT, DE_STATE_FLAG_HUAD_INSPECT, DE_STATE_FLAG_MODBUS_INSPECT, DE_STATE_FLAG_TEMPLATE_BUFFER_INSPECT, DE_STATE_FLAG_URI_INSPECT, DETECT_SM_LIST_DNSQUERYNAME_MATCH, DETECT_SM_LIST_DNSREQUEST_MATCH, DETECT_SM_LIST_DNSRESPONSE_MATCH, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_FILEMATCH, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRLMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_MODBUS_MATCH, DETECT_SM_LIST_TEMPLATE_BUFFER_MATCH, DETECT_SM_LIST_UMATCH, DetectEngineInspectDnsQueryName(), DetectEngineInspectDnsRequest(), DetectEngineInspectDnsResponse(), DetectEngineInspectHttpClientBody(), DetectEngineInspectHttpCookie(), DetectEngineInspectHttpHeader(), DetectEngineInspectHttpHH(), DetectEngineInspectHttpHRH(), DetectEngineInspectHttpMethod(), DetectEngineInspectHttpRawHeader(), DetectEngineInspectHttpRawUri(), DetectEngineInspectHttpRequestLine(), DetectEngineInspectHttpServerBody(), DetectEngineInspectHttpStatCode(), DetectEngineInspectHttpStatMsg(), DetectEngineInspectHttpUA(), DetectEngineInspectModbus(), DetectEngineInspectPacketUris(), DetectEngineInspectSMTPFiledata(), DetectEngineInspectTemplateBuffer(), DetectEngineRegisterAppInspectionEngine(), DetectFileInspectHttp(), DetectFileInspectSmtp(), flags, and tx_id.
Referenced by RunUnittests().
void DetectEngineRegisterTests (void)
Definition at line 3228 of file detect-engine.c.
Referenced by RunUnittests().
int DetectEngineReload (const char * filename, SCInstance * suri)
Reload the detection engine.
Parameters
filename YAML file to load for the detect config
Return values
-1 error
0 ok
Definition at line 2343 of file detect-engine.c.
References ConfDump(), ConfGetNode(), ConfYamlLoadFileWithPrefix(), DetectEngineAddToMaster(), DetectEngineCtxFree(), DetectEngineCtxInitWithPrefix(), DetectEngineDeReference(), DetectEngineGetCurrent(), DetectEngineMoveToFreeList(), DetectEnginePruneFreeList(), SC_ERR_CONF_YAML_ERROR, SC_ERR_INITIALIZATION, SCLogDebug, SCLogError, SCThresholdConfInitContext(), SCInstance_::sig_file, SCInstance_::sig_file_exclusive, and SigLoadSignatures().
Referenced by main().
int DetectEngineReloadIsDone (void)
Definition at line 528 of file detect-engine.c.
References DONE, IDLE, DetectEngineSyncer_::m, SCMutexLock, SCMutexUnlock, and DetectEngineSyncer_::state.
int DetectEngineReloadIsStart (void)
Definition at line 508 of file detect-engine.c.
References DetectEngineSyncer_::m, RELOAD, SCMutexLock, SCMutexUnlock, and DetectEngineSyncer_::state.
Referenced by main().
void DetectEngineReloadSetDone (void)
Definition at line 520 of file detect-engine.c.
References DONE, DetectEngineSyncer_::m, SCMutexLock, SCMutexUnlock, and DetectEngineSyncer_::state.
Referenced by main().
int DetectEngineReloadStart (void)
Definition at line 494 of file detect-engine.c.
References IDLE, DetectEngineSyncer_::m, RELOAD, SCMutexLock, SCMutexUnlock, and DetectEngineSyncer_::state.
int DetectEngineReloadTenantBlocking (uint32_t tenant_id, const char * yaml, int reload_cnt)
Reload a tenant and wait for loading to complete.
Definition at line 1893 of file detect-engine.c.
References DetectLoaderSetupReloadTenant(), and DetectLoadersSync().
void DetectEngineResetMaxSigId (DetectEngineCtx * de_ctx)
Definition at line 1235 of file detect-engine.c.
References DetectEngineCtx_::signum.
Referenced by SigCleanSignatures().
uint32_t DetectEngineTentantGetIdFromPcap (const void * ctx, const Packet * p)
Definition at line 2184 of file detect-engine.c.
References Packet_::pcap_v, and PcapPacketVars_::tenant_id.
uint32_t DetectEngineTentantGetIdFromVlanId (const void * ctx, const Packet * p)
Definition at line 2061 of file detect-engine.c.
References DetectEngineThreadCtx_::tenant_array, DetectEngineThreadCtx_::tenant_array_size, DetectEngineTenantMapping_::tenant_id, DetectEngineTenantMapping_::traffic_id, Packet_::vlan_id, and Packet_::vlan_idx.
int DetectEngineTentantRegisterPcapFile (uint32_t tenant_id)
Definition at line 2172 of file detect-engine.c.
References SCLogInfo, and TENANT_SELECTOR_DIRECT.
int DetectEngineTentantRegisterVlanId (uint32_t tenant_id, uint16_t vlan_id)
Definition at line 2162 of file detect-engine.c.
References TENANT_SELECTOR_VLAN.
Referenced by DetectEngineMultiTenantSetup().
int DetectEngineTentantUnregisterPcapFile (uint32_t tenant_id)
Definition at line 2178 of file detect-engine.c.
References SCLogInfo, and TENANT_SELECTOR_DIRECT.
int DetectEngineTentantUnregisterVlanId (uint32_t tenant_id, uint16_t vlan_id)
Definition at line 2167 of file detect-engine.c.
References TENANT_SELECTOR_VLAN.
TmEcode DetectEngineThreadCtxDeinit (ThreadVars * tv, void * data)
Definition at line 1557 of file detect-engine.c.
References DetectEngineThreadCtxFree(), HashTableFree(), DetectEngineThreadCtx_::mt_det_ctxs_hash, SC_ERR_INVALID_ARGUMENTS, SCLogWarning, and TM_ECODE_OK.
Referenced by DetectEngineThreadCtxInit(), and DetectThreadDeinit().
void DetectEngineThreadCtxFree (DetectEngineThreadCtx * det_ctx)
Todo:
get rid of this static
Definition at line 1473 of file detect-engine.c.
References DetectEngineThreadCtx_::bj_values, HttpReassembledBody_::buffer, HttpReassembledBody_::buffer_size, DetectEngineThreadCtx_::de_ctx, DetectEngineThreadCtx_::de_state_sig_array, DETECT_SMSG_PMQ_NUM, DetectEngineDeReference(), DetectEngineIPOnlyThreadDeinit(), DetectEngineThreadCtx_::hcbd, DetectEngineThreadCtx_::hcbd_buffers_size, DetectEngineThreadCtx_::hhd_buffers, DetectEngineThreadCtx_::hhd_buffers_len, DetectEngineThreadCtx_::hhd_buffers_size, DetectEngineThreadCtx_::hsbd, DetectEngineThreadCtx_::hsbd_buffers_size, HTPFree(), DetectEngineThreadCtx_::io_ctx, DetectEngineThreadCtx_::match_array, DetectEngineCtx_::mpm_matcher, DetectEngineThreadCtx_::mtc, DetectEngineThreadCtx_::mtcs, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::non_mpm_id_array, PatternMatchThreadDestroy(), DetectEngineThreadCtx_::pmq, PmqFree(), DetectEngineCtx_::ref_cnt, RunmodeIsUnittests(), SCFree, SCLogDebug, SCProfilingKeywordThreadCleanup(), SCProfilingRuleThreadCleanup(), DetectEngineThreadCtx_::smsg_pmq, and DetectEngineThreadCtx_::tenant_array.
Referenced by DetectEngineThreadCtxDeinit().
void DetectEngineThreadCtxInfo (ThreadVars * t, DetectEngineThreadCtx * det_ctx)
Definition at line 1575 of file detect-engine.c.
References DetectEngineThreadCtx_::de_ctx, DetectEngineCtx_::mpm_matcher, DetectEngineThreadCtx_::mtc, DetectEngineThreadCtx_::mtcu, and PatternMatchThreadPrint().
TmEcode DetectEngineThreadCtxInit (ThreadVars * tv, void * initdata, void ** data)
initialize thread specific detection engine context
Note
there is a special case when using delayed detect. In this case the function is called twice per thread. The first time the rules are not yet loaded. de_ctx->delayed_detect_initialized will be 0. The 2nd time they will be loaded. de_ctx->delayed_detect_initialized will be 1. This is needed to do the per thread counter registration before the packet runtime starts. In delayed detect mode, the first call will return a NULL ptr through the data ptr.
Parameters
tv ThreadVars for this thread
initdata pointer to de_ctx
data[out] pointer to store our thread detection ctx
Return values
TM_ECODE_OK if all went well
TM_ECODE_FAILED on serious erro
alert counter setup
Definition at line 1368 of file detect-engine.c.
References DetectEngineThreadCtx_::counter_alerts, DetectEngineThreadCtx_::counter_fnonmpm_list, DetectEngineThreadCtx_::counter_match_list, DetectEngineThreadCtx_::counter_mpm_list, DetectEngineThreadCtx_::counter_nonmpm_list, DetectEngineThreadCtx_::de_ctx, DetectEngineGetCurrent(), DetectEngineMultiTenantEnabled(), DetectEngineThreadCtxDeinit(), DetectEngineCtx_::minimal, RunmodeIsUnittests(), SCMalloc, StatsRegisterAvgCounter(), StatsRegisterCounter(), TM_ECODE_FAILED, TM_ECODE_OK, DetectEngineThreadCtx_::tv, and unlikely.
Referenced by DetectThreadInit().
int DetectLoaderSetupLoadTenant (uint32_t tenant_id, const char * yaml)
Definition at line 1832 of file detect-engine.c.
References DetectLoaderQueueTask(), SCCalloc, TenantLoaderCtx_::tenant_id, and TenantLoaderCtx_::yaml.
Referenced by DetectEngineLoadTenantBlocking(), and DetectEngineMultiTenantSetup().
int DetectLoaderSetupReloadTenant (uint32_t tenant_id, const char * yaml, int reload_cnt)
Definition at line 1856 of file detect-engine.c.
References DetectEngineDeReference(), DetectEngineGetByTenantId(), DetectLoaderQueueTask(), DetectEngineCtx_::loader_id, TenantLoaderCtx_::reload_cnt, SCCalloc, SCLogDebug, TenantLoaderCtx_::tenant_id, and TenantLoaderCtx_::yaml.
Referenced by DetectEngineReloadTenantBlocking().
int DetectRegisterThreadCtxFuncs (DetectEngineCtx * de_ctx, const char * name, void *(*)(void *) InitFunc, void * data, void(*)(void *) FreeFunc, int mode)
Register Thread keyword context Funcs.
Parameters
de_ctx detection engine to register in
name keyword name for error printing
InitFunc function ptr
data keyword init data to pass to Func
FreeFunc function ptr
mode 0 normal (ctx per keyword instance) 1 shared (one ctx per det_ct)
Return values
id for retrieval of ctx at runtime
-1 on error
Note
make sure "data" remains valid and it free'd elsewhere. It's recommended to store it in the keywords global ctx so that it's freed when the de_ctx is freed.
Definition at line 1598 of file detect-engine.c.
References BUG_ON, data, DetectEngineThreadKeywordCtxItem_::data, DetectEngineThreadKeywordCtxItem_::FreeFunc, DetectEngineThreadKeywordCtxItem_::id, DetectEngineThreadKeywordCtxItem_::InitFunc, DetectEngineCtx_::keyword_id, DetectEngineCtx_::keyword_list, DetectEngineThreadKeywordCtxItem_::name, DetectEngineThreadKeywordCtxItem_::next, SCMalloc, and unlikely.
const char* DetectSigmatchListEnumToString (enum DetectSigmatchListEnum type)
Definition at line 2590 of file detect-engine.c.
References DETECT_SM_LIST_AMATCH, DETECT_SM_LIST_APP_EVENT, DETECT_SM_LIST_DMATCH, DETECT_SM_LIST_DNSQUERYNAME_MATCH, DETECT_SM_LIST_DNSREQUEST_MATCH, DETECT_SM_LIST_DNSRESPONSE_MATCH, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_FILEMATCH, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRLMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_MATCH, DETECT_SM_LIST_MAX, DETECT_SM_LIST_MODBUS_MATCH, DETECT_SM_LIST_NOTSET, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_POSTMATCH, DETECT_SM_LIST_SUPPRESS, DETECT_SM_LIST_TEMPLATE_BUFFER_MATCH, DETECT_SM_LIST_THRESHOLD, DETECT_SM_LIST_TMATCH, and DETECT_SM_LIST_UMATCH.
Referenced by CleanupFPAnalyzer(), and SCProfilingKeywordDump().
void* DetectThreadCtxGetKeywordThreadCtx (DetectEngineThreadCtx * det_ctx, int id)
Retrieve thread local keyword ctx by id.
Parameters
det_ctx detection engine thread ctx to retrieve the ctx from
id id of the ctx returned by DetectRegisterThreadCtxInitFunc at keyword init.
Return values
ctx or NULL on error
Definition at line 1638 of file detect-engine.c.
References DetectEngineThreadCtx_::keyword_ctxs_array, and DetectEngineThreadCtx_::keyword_ctxs_size.
Variable Documentation
DetectEngineAppInspectionEngine* app_inspection_engine[FLOW_PROTO_DEFAULT][ALPROTO_MAX][2]
Definition at line 114 of file detect-engine.c.
Referenced by DeStateDetectStartDetection().