suricata: src/detect-asn1.h File Reference
detect-asn1.h File Reference
Data Structures
struct DetectAsn1Data_
Macros
#define ASN1_BITSTRING_OVF 0x01
#define ASN1_DOUBLE_OVF 0x02
#define ASN1_OVERSIZE_LEN 0x04
#define ASN1_ABSOLUTE_OFFSET 0x10
#define ASN1_RELATIVE_OFFSET 0x20
Typedefs
typedef struct DetectAsn1Data_ DetectAsn1Data
Functions
void DetectAsn1Register (void)
Registration function for asn1.
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements "asn1" keyword
Definition in file detect-asn1.h.
Macro Definition Documentation
#define ASN1_ABSOLUTE_OFFSET 0x10
Definition at line 33 of file detect-asn1.h.
Referenced by DetectAsn1Match(), and DetectAsn1Parse().
#define ASN1_BITSTRING_OVF 0x01
Definition at line 30 of file detect-asn1.h.
Referenced by DetectAsn1Parse().
#define ASN1_DOUBLE_OVF 0x02
Definition at line 31 of file detect-asn1.h.
Referenced by DetectAsn1Parse().
#define ASN1_OVERSIZE_LEN 0x04
Definition at line 32 of file detect-asn1.h.
Referenced by DetectAsn1Parse().
#define ASN1_RELATIVE_OFFSET 0x20
Definition at line 34 of file detect-asn1.h.
Referenced by DetectAsn1Match(), and DetectAsn1Parse().
Typedef Documentation
typedef struct DetectAsn1Data_ DetectAsn1Data
Function Documentation
void DetectAsn1Register (void)
Registration function for asn1.
Definition at line 54 of file detect-asn1.c.
References DETECT_ASN1, DetectAsn1Free(), DetectAsn1Match(), DetectAsn1RegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().