suricata: src/detect-filestore.c File Reference
detect-filestore.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-spm-bm.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "stream-tcp.h"
#include "detect-filestore.h"
Macros
#define PARSE_REGEX "^\\s*([A-z_]+)\\s*(?:,\\s*([A-z_]+))?\\s*(?:,\\s*([A-z_]+))?\\s*$"
Regex for parsing our flow options.
#define MAX_SUBSTRINGS 30
Functions
void DetectFilestoreRegister (void)
Registration function for keyword: filestore.
int DetectFilestorePostMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s)
post-match function for filestore
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements the filestore keyword
Definition in file detect-filestore.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
#define PARSE_REGEX "^\\s*([A-z_]+)\\s*(?:,\\s*([A-z_]+))?\\s*(?:,\\s*([A-z_]+))?\\s*$"
Regex for parsing our flow options.
Definition at line 57 of file detect-filestore.c.
Referenced by DetectFilestoreRegister().
Function Documentation
int DetectFilestorePostMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s)
post-match function for filestore
Parameters
t thread local vars
det_ctx pattern matcher thread local data
p packet
The match function for filestore records store candidates in the det_ctx. When we are sure all parts of the signature matched, we run this function to finalize the filestore.
Definition at line 204 of file detect-filestore.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), BUG_ON, SigMatch_::ctx, DetectEngineThreadCtx_::file_id, DetectEngineThreadCtx_::filestore, DetectEngineThreadCtx_::filestore_cnt, Signature_::filestore_sm, FileStoreFileById(), flags, Packet_::flow, DetectEngineThreadCtx_::flow_locked, FLOW_PKT_TOCLIENT, Packet_::flowflags, FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, Flow_::proto, SCEnter, SCReturnInt, STREAM_TOCLIENT, STREAM_TOSERVER, and DetectEngineThreadCtx_::tx_id.
Referenced by SigMatchSignaturesRunPostMatch().
void DetectFilestoreRegister (void)
Registration function for keyword: filestore.
Definition at line 70 of file detect-filestore.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::desc, DETECT_FILESTORE, SigTableElmt_::FileMatch, SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, SIGMATCH_OPTIONAL_OPT, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().