suricata: src/detect-dce-iface.h File Reference
detect-dce-iface.h File Reference
Data Structures
struct DetectDceIfaceData_
Typedefs
typedef enum
DetectDceIfaceOperators_ DetectDceIfaceOperators
typedef struct DetectDceIfaceData_ DetectDceIfaceData
Enumerations
enum DetectDceIfaceOperators_ {
DETECT_DCE_IFACE_OP_NONE = 0, DETECT_DCE_IFACE_OP_LT, DETECT_DCE_IFACE_OP_GT, DETECT_DCE_IFACE_OP_EQ,
DETECT_DCE_IFACE_OP_NE
}
Functions
void DetectDceIfaceRegister (void)
Registers the keyword handlers for the "dce_iface" keyword.
void DetectDceIfaceRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-dce-iface.h.
Typedef Documentation
typedef struct DetectDceIfaceData_ DetectDceIfaceData
typedef enum DetectDceIfaceOperators_ DetectDceIfaceOperators
Enumeration Type Documentation
enum DetectDceIfaceOperators_
Enumerator
DETECT_DCE_IFACE_OP_NONE
DETECT_DCE_IFACE_OP_LT
DETECT_DCE_IFACE_OP_GT
DETECT_DCE_IFACE_OP_EQ
DETECT_DCE_IFACE_OP_NE
Definition at line 27 of file detect-dce-iface.h.
Function Documentation
void DetectDceIfaceRegister (void)
Registers the keyword handlers for the "dce_iface" keyword.
Definition at line 63 of file detect-dce-iface.c.
References SigTableElmt_::alproto, ALPROTO_DCERPC, SigTableElmt_::AppLayerMatch, DETECT_DCE_IFACE, DETECT_DCE_IFACE_PCRE_PARSE_ARGS, DetectDceIfaceFree(), DetectDceIfaceMatch(), DetectDceIfaceRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SCLogDebug, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void DetectDceIfaceRegisterTests (void)
Definition at line 1811 of file detect-dce-iface.c.
Referenced by DetectDceIfaceRegister().