suricata: src/detect-rpc.c File Reference
detect-rpc.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-rpc.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-siggroup.h"
#include "detect-engine-address.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
#include "util-byte.h"
Macros
#define PARSE_REGEX "^\\s*([0-9]{0,10})\\s*(?:,\\s*([0-9]{0,10}|[*])\\s*(?:,\\s*([0-9]{0,10}|[*]))?)?\\s*$"
Regex for parsing our rpc options.
#define MAX_SUBSTRINGS 30
Functions
int DetectRpcMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match rpc request set on a packet with those passed via rpc.
int DetectRpcSetup (DetectEngineCtx *de_ctx, Signature *s, char *rpcstr)
this function is used to add the parsed rpcdata into the current signature
void DetectRpcRegisterTests (void)
this function registers unit tests for DetectRpc
void DetectRpcFree (void *ptr)
this function will free memory associated with DetectRpcData
void DetectRpcRegister (void)
Registration function for rpc keyword.
DetectRpcData * DetectRpcParse (char *rpcstr)
This function is used to parse rpc options passed via rpc keyword.
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements RPC keyword
Definition in file detect-rpc.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectRpcParse().
#define PARSE_REGEX "^\\s*([0-9]{0,10})\\s*(?:,\\s*([0-9]{0,10}|[*])\\s*(?:,\\s*([0-9]{0,10}|[*]))?)?\\s*$"
Regex for parsing our rpc options.
Definition at line 46 of file detect-rpc.c.
Referenced by DetectRpcRegister().
Function Documentation
void DetectRpcFree (void * ptr)
this function will free memory associated with DetectRpcData
Parameters
rd pointer to DetectRpcData
Definition at line 308 of file detect-rpc.c.
References SCEnter, SCFree, and SCReturn.
Referenced by DetectRpcParse(), DetectRpcRegister(), and DetectRpcSetup().
int DetectRpcMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match rpc request set on a packet with those passed via rpc.
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectRpcData
Return values
0 no match
1 match
Definition at line 110 of file detect-rpc.c.
References DETECT_RPC_CHECK_PROCEDURE, DETECT_RPC_CHECK_VERSION, DetectRpcData_::flags, msg, Packet_::payload, Packet_::payload_len, PKT_IS_TCP, PKT_IS_UDP, RpcMsg_::proc, DetectRpcData_::procedure, RpcMsg_::prog, DetectRpcData_::program, DetectRpcData_::program_version, SCLogDebug, RpcMsg_::type, and RpcMsg_::vers.
Referenced by DetectRpcRegister().
DetectRpcData* DetectRpcParse (char * rpcstr)
This function is used to parse rpc options passed via rpc keyword.
Parameters
rpcstr Pointer to the user provided rpc options
Return values
rd pointer to DetectRpcData on success
NULL on failure
Definition at line 164 of file detect-rpc.c.
References ByteExtractStringUint32(), DETECT_RPC_CHECK_PROCEDURE, DETECT_RPC_CHECK_PROGRAM, DETECT_RPC_CHECK_VERSION, DetectRpcFree(), DetectRpcData_::flags, MAX_SUBSTRINGS, DetectRpcData_::procedure, DetectRpcData_::program, DetectRpcData_::program_version, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogError, SCMalloc, and unlikely.
Referenced by DetectRpcSetup().
void DetectRpcRegister (void)
Registration function for rpc keyword.
Definition at line 59 of file detect-rpc.c.
References SigTableElmt_::desc, DETECT_RPC, DetectRpcFree(), DetectRpcMatch(), DetectRpcRegisterTests(), DetectRpcSetup(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectRpcRegisterTests (void)
this function registers unit tests for DetectRpc
Definition at line 599 of file detect-rpc.c.
Referenced by DetectRpcRegister().
int DetectRpcSetup (DetectEngineCtx * de_ctx, Signature * s, char * rpcstr)
this function is used to add the parsed rpcdata into the current signature
Parameters
de_ctx pointer to the Detection Engine Context
s pointer to the Current Signature
m pointer to the Current SigMatch
rpcstr pointer to the user provided rpc options
Return values
0 on Success
-1 on Failure
Definition at line 276 of file detect-rpc.c.
References SigMatch_::ctx, DETECT_RPC, DETECT_SM_LIST_MATCH, DetectRpcFree(), DetectRpcParse(), Signature_::flags, SCFree, SIG_FLAG_REQUIRE_PACKET, SigMatchAlloc(), SigMatchAppendSMToList(), and SigMatch_::type.
Referenced by DetectRpcRegister().