suricata: src/detect-isdataat.h File Reference
detect-isdataat.h File Reference
Data Structures
struct DetectIsdataatData_
Macros
#define ISDATAAT_RELATIVE 0x01
#define ISDATAAT_RAWBYTES 0x02
#define ISDATAAT_NEGATED 0x04
#define ISDATAAT_OFFSET_BE 0x08
#define ISDATAAT_MIN 0
#define ISDATAAT_MAX 65535
Typedefs
typedef struct DetectIsdataatData_ DetectIsdataatData
Functions
void DetectIsdataatRegister (void)
Registration function for isdataat: keyword.
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file detect-isdataat.h.
Macro Definition Documentation
#define ISDATAAT_MAX 65535
Definition at line 33 of file detect-isdataat.h.
#define ISDATAAT_MIN 0
Definition at line 32 of file detect-isdataat.h.
#define ISDATAAT_NEGATED 0x04
Definition at line 29 of file detect-isdataat.h.
Referenced by DetectEngineContentInspection(), and DetectIsdataatParse().
#define ISDATAAT_OFFSET_BE 0x08
Definition at line 30 of file detect-isdataat.h.
Referenced by DetectIsdataatSetup().
#define ISDATAAT_RAWBYTES 0x02
Definition at line 28 of file detect-isdataat.h.
Referenced by DetectIsdataatParse().
#define ISDATAAT_RELATIVE 0x01
Definition at line 27 of file detect-isdataat.h.
Referenced by DetectEngineContentInspection(), DetectIsdataatMatch(), DetectIsdataatParse(), and DetectIsdataatSetup().
Typedef Documentation
typedef struct DetectIsdataatData_ DetectIsdataatData
Function Documentation
void DetectIsdataatRegister (void)
Registration function for isdataat: keyword.
Definition at line 66 of file detect-isdataat.c.
References SigTableElmt_::desc, DETECT_ISDATAAT, DetectIsdataatFree(), DetectIsdataatMatch(), DetectIsdataatRegisterTests(), DetectIsdataatSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().