suricata: src/detect-tag.c File Reference
detect-tag.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-tag.h"
#include "detect-engine-tag.h"
#include "detect-engine.h"
#include "detect-engine-state.h"
#include "app-layer-parser.h"
#include "debug.h"
#include "decode.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "stream-tcp-private.h"
#include "util-time.h"
#include "util-byte.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
#include "threads.h"
Macros
#define PARSE_REGEX "^\\s*(host|session)\\s*(,\\s*(\\d+)\\s*,\\s*(packets|bytes|seconds)\\s*(,\\s*(src|dst))?\\s*)?$"
#define MAX_SUBSTRINGS 30
Functions
SC_ATOMIC_EXTERN (unsigned int, num_tags)
int DetectTagMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to setup a tag for session/host.
void DetectTagRegisterTests (void)
this function registers unit tests for DetectTag
void DetectTagDataFree (void *ptr)
this function will free memory associated with DetectTagData
void DetectTagRegister (void)
Registration function for keyword tag.
DetectTagData * DetectTagParse (char *tagstr)
This function is used to parse tag options passed to tag keyword.
void DetectTagDataListFree (void *ptr)
this function will free all the entries of a list DetectTagDataEntry
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements the tag keyword
Definition in file detect-tag.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectTagParse().
#define PARSE_REGEX "^\\s*(host|session)\\s*(,\\s*(\\d+)\\s*,\\s*(packets|bytes|seconds)\\s*(,\\s*(src|dst))?\\s*)?$"
Definition at line 55 of file detect-tag.c.
Referenced by DetectTagRegister().
Function Documentation
void DetectTagDataFree (void * ptr)
this function will free memory associated with DetectTagData
Parameters
td pointer to DetectTagData
Definition at line 370 of file detect-tag.c.
References SCFree.
Referenced by DetectTagRegister().
void DetectTagDataListFree (void * ptr)
this function will free all the entries of a list DetectTagDataEntry
Parameters
td pointer to DetectTagDataEntryList
Definition at line 351 of file detect-tag.c.
References DetectTagDataEntry_::next, and SC_ATOMIC_SUB.
Referenced by TagInitCtx().
int DetectTagMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to setup a tag for session/host.
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectTagData
Return values
0 no match
1 match
Definition at line 112 of file detect-tag.c.
References BUG_ON, DetectTagData_::count, DetectTagDataEntry_::count, DETECT_TAG_DIR_DST, DETECT_TAG_DIR_SRC, DETECT_TAG_TYPE_HOST, DETECT_TAG_TYPE_SESSION, DetectTagData_::direction, DetectTagDataEntry_::first_ts, DetectTagDataEntry_::flags, Packet_::flow, DetectTagDataEntry_::gid, Signature_::gid, Signature_::id, DetectTagDataEntry_::last_ts, DetectTagData_::metric, DetectTagDataEntry_::metric, SCLogDebug, DetectTagDataEntry_::sid, TAG_ENTRY_FLAG_DIR_DST, TAG_ENTRY_FLAG_DIR_SRC, TagFlowAdd(), TagHashAddTag(), Packet_::ts, and DetectTagData_::type.
Referenced by DetectTagRegister().
DetectTagData* DetectTagParse (char * tagstr)
This function is used to parse tag options passed to tag keyword.
Parameters
tagstr Pointer to the user provided tag options
Return values
td pointer to DetectTagData on success
NULL on failure
Definition at line 173 of file detect-tag.c.
References ByteExtractStringUint32(), DetectTagData_::count, DETECT_TAG_DIR_DST, DETECT_TAG_DIR_SRC, DETECT_TAG_MAX_PKTS, DETECT_TAG_METRIC_BYTES, DETECT_TAG_METRIC_PACKET, DETECT_TAG_METRIC_SECONDS, DETECT_TAG_TYPE_HOST, DETECT_TAG_TYPE_SESSION, DetectTagData_::direction, MAX_SUBSTRINGS, DetectTagData_::metric, SC_ERR_INVALID_VALUE, SC_ERR_MEM_ALLOC, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCLogError, SCLogWarning, SCMalloc, DetectTagData_::type, and unlikely.
void DetectTagRegister (void)
Registration function for keyword tag.
Definition at line 68 of file detect-tag.c.
References DETECT_TAG, DetectTagDataFree(), DetectTagMatch(), DetectTagRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, and sigmatch_table.
Referenced by SigTableSetup().
void DetectTagRegisterTests (void)
this function registers unit tests for DetectTag
Definition at line 477 of file detect-tag.c.
References DetectEngineTagRegisterTests().
Referenced by DetectTagRegister().
SC_ATOMIC_EXTERN (unsigned int, num_tags)