suricata: src/detect-engine-content-inspection.h File Reference
detect-engine-content-inspection.h File Reference
Enumerations
enum {
DETECT_ENGINE_CONTENT_INSPECTION_MODE_PAYLOAD = 0, DETECT_ENGINE_CONTENT_INSPECTION_MODE_STREAM, DETECT_ENGINE_CONTENT_INSPECTION_MODE_DCE, DETECT_ENGINE_CONTENT_INSPECTION_MODE_URI,
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HRL, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HRUD, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HHD, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HRHD,
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HCBD, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HSBD, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HCD, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HMD,
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HSCD, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HSMD, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HUAD, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HHHD,
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HRHHD, DETECT_ENGINE_CONTENT_INSPECTION_MODE_DNSQUERY, DETECT_ENGINE_CONTENT_INSPECTION_MODE_FD_SMTP, DETECT_ENGINE_CONTENT_INSPECTION_MODE_TEMPLATE_BUFFER
}
Functions
int DetectEngineContentInspection (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, SigMatch *sm, Flow *f, uint8_t *buffer, uint32_t buffer_len, uint32_t stream_start_offset, uint8_t inspection_mode, void *data)
Run the actual payload match functions.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-engine-content-inspection.h.
Enumeration Type Documentation
anonymous enum
Warning
make sure to add new entries to the proper position wrt flow lock status
Enumerator
DETECT_ENGINE_CONTENT_INSPECTION_MODE_PAYLOAD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_STREAM
DETECT_ENGINE_CONTENT_INSPECTION_MODE_DCE
DETECT_ENGINE_CONTENT_INSPECTION_MODE_URI
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HRL
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HRUD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HHD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HRHD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HCBD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HSBD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HCD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HMD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HSCD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HSMD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HUAD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HHHD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_HRHHD
DETECT_ENGINE_CONTENT_INSPECTION_MODE_DNSQUERY
DETECT_ENGINE_CONTENT_INSPECTION_MODE_FD_SMTP
DETECT_ENGINE_CONTENT_INSPECTION_MODE_TEMPLATE_BUFFER
Definition at line 30 of file detect-engine-content-inspection.h.
Function Documentation
int DetectEngineContentInspection (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, SigMatch * sm, Flow * f, uint8_t * buffer, uint32_t buffer_len, uint32_t stream_start_offset, uint8_t inspection_mode, void * data)
Run the actual payload match functions.
The following keywords are inspected:
content, including all the http and dce modified contents
isdaatat
pcre
bytejump
bytetest
byte_extract
urilen
All keywords are evaluated against the buffer with buffer_len.
For accounting the last match in relative matching the det_ctx->buffer_offset int is used.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
sm SigMatch to inspect
f Flow (for pcre flowvar storage)
buffer Ptr to the buffer to inspect
buffer_len Length of the payload
stream_start_offset Indicates the start of the current buffer in the whole buffer stream inspected. This applies if the current buffer is inspected in chunks.
inspection_mode Refers to the engine inspection mode we are currently inspecting. Can be payload, stream, one of the http buffer inspection modes or dce inspection mode.
data Used to send some custom data. For example in payload inspection mode, data contains packet ptr, and under dce inspection mode, contains dce state.
Return values
0 no match
1 match
< used in recursive searching
Definition at line 100 of file detect-engine-content-inspection.c.
References DetectEngineThreadCtx_::bj_values, DetectContentData_::bm_ctx, BoyerMoore(), BoyerMooreNocase(), DetectEngineThreadCtx_::buffer_offset, BUG_ON, DetectContentData_::content, DetectContentData_::content_len, SigMatch_::ctx, DetectIsdataatData_::dataat, DetectContentData_::depth, DETECT_CONTENT, DETECT_CONTENT_DEPTH, DETECT_CONTENT_DEPTH_BE, DETECT_CONTENT_DISTANCE, DETECT_CONTENT_DISTANCE_BE, DETECT_CONTENT_IS_SINGLE, DETECT_CONTENT_NEGATED, DETECT_CONTENT_NOCASE, DETECT_CONTENT_OFFSET_BE, DETECT_CONTENT_RELATIVE_NEXT, DETECT_CONTENT_REPLACE, DETECT_CONTENT_WITHIN, DETECT_CONTENT_WITHIN_BE, DETECT_ENGINE_CONTENT_INSPECTION_MODE_PAYLOAD, DETECT_ISDATAAT, DETECT_PCRE, DETECT_PCRE_RELATIVE_NEXT, DetectEngineContentInspection(), DetectPcrePayloadMatch(), DetectReplaceAddToList(), DetectEngineThreadCtx_::discontinue_matching, DetectContentData_::distance, DetectIsdataatData_::flags, DetectPcreData_::flags, DetectContentData_::flags, DetectContentData_::id, DetectEngineThreadCtx_::inspection_recursion_counter, DetectEngineCtx_::inspection_recursion_limit, ISDATAAT_NEGATED, ISDATAAT_RELATIVE, KEYWORD_PROFILING_END, KEYWORD_PROFILING_START, SigMatch_::next, DetectContentData_::offset, DetectEngineThreadCtx_::pcre_match_start_offset, DetectEngineThreadCtx_::replist, SC_ERR_INVALID_VALUE, SCEnter, SCLogDebug, SCLogWarning, SCReturnInt, SigMatch_::type, and DetectContentData_::within.
Referenced by DetectEngineContentInspection(), DetectEngineInspectDcePayload(), DetectEngineInspectDnsQueryName(), DetectEngineInspectHttpClientBody(), DetectEngineInspectHttpCookie(), DetectEngineInspectHttpHeader(), DetectEngineInspectHttpHH(), DetectEngineInspectHttpHRH(), DetectEngineInspectHttpMethod(), DetectEngineInspectHttpRawHeader(), DetectEngineInspectHttpRawUri(), DetectEngineInspectHttpRequestLine(), DetectEngineInspectHttpServerBody(), DetectEngineInspectHttpStatCode(), DetectEngineInspectHttpStatMsg(), DetectEngineInspectHttpUA(), DetectEngineInspectPacketPayload(), DetectEngineInspectPacketUris(), DetectEngineInspectSMTPFiledata(), DetectEngineInspectStreamPayload(), and DetectEngineInspectTemplateBuffer().