suricata: src/detect-bytejump.h File Reference
detect-bytejump.h File Reference
Data Structures
struct DetectBytejumpData_
Macros
#define DETECT_BYTEJUMP_BASE_UNSET 0
#define DETECT_BYTEJUMP_BASE_OCT 8
#define DETECT_BYTEJUMP_BASE_DEC 10
#define DETECT_BYTEJUMP_BASE_HEX 16
#define DETECT_BYTEJUMP_BEGIN 0x01
#define DETECT_BYTEJUMP_LITTLE 0x02
#define DETECT_BYTEJUMP_BIG 0x04
#define DETECT_BYTEJUMP_STRING 0x08
#define DETECT_BYTEJUMP_RELATIVE 0x10
#define DETECT_BYTEJUMP_ALIGN 0x20
#define DETECT_BYTEJUMP_DCE 0x40
#define DETECT_BYTEJUMP_OFFSET_BE 0x80
Typedefs
typedef struct DetectBytejumpData_ DetectBytejumpData
Functions
void DetectBytejumpRegister (void)
int DetectBytejumpSetup (DetectEngineCtx *, Signature *, char *)
void DetectBytejumpFree (void *ptr)
this function will free memory associated with DetectBytejumpData
DetectBytejumpData * DetectBytejumpParse (char *optstr, char **offset)
int DetectBytejumpMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
int DetectBytejumpDoMatch (DetectEngineThreadCtx *, Signature *, const SigMatchCtx *, uint8_t *, uint32_t, uint8_t, int32_t)
Byte jump match function.
Detailed Description
Author
Brian Rectanus brect.nosp@m.anu@.nosp@m.gmail.nosp@m..com
Definition in file detect-bytejump.h.
Macro Definition Documentation
#define DETECT_BYTEJUMP_ALIGN 0x20
"align" offset
Definition at line 39 of file detect-bytejump.h.
Referenced by DetectBytejumpDoMatch(), DetectBytejumpMatch(), and DetectBytejumpParse().
#define DETECT_BYTEJUMP_BASE_DEC 10
"dec" type value string
Definition at line 30 of file detect-bytejump.h.
Referenced by DetectBytejumpParse(), and DetectBytejumpSetup().
#define DETECT_BYTEJUMP_BASE_HEX 16
"hex" type value string
Definition at line 31 of file detect-bytejump.h.
Referenced by DetectBytejumpParse(), and DetectBytejumpSetup().
#define DETECT_BYTEJUMP_BASE_OCT 8
"oct" type value string
Definition at line 29 of file detect-bytejump.h.
Referenced by DetectBytejumpParse(), and DetectBytejumpSetup().
#define DETECT_BYTEJUMP_BASE_UNSET 0
Bytejump Base Unset type value string (automatic)
Definition at line 28 of file detect-bytejump.h.
Referenced by DetectBytejumpParse().
#define DETECT_BYTEJUMP_BEGIN 0x01
Bytejump Flags "from_beginning" jump
Definition at line 34 of file detect-bytejump.h.
Referenced by DetectBytejumpDoMatch(), DetectBytejumpMatch(), DetectBytejumpParse(), and DetectBytejumpSetup().
#define DETECT_BYTEJUMP_BIG 0x04
"big" endian value
Definition at line 36 of file detect-bytejump.h.
Referenced by DetectBytejumpParse(), and DetectBytejumpSetup().
#define DETECT_BYTEJUMP_DCE 0x40
"dce" enabled
Definition at line 40 of file detect-bytejump.h.
Referenced by DetectBytejumpParse(), and DetectBytejumpSetup().
#define DETECT_BYTEJUMP_LITTLE 0x02
"little" endian value
Definition at line 35 of file detect-bytejump.h.
Referenced by DetectBytejumpDoMatch(), DetectBytejumpMatch(), DetectBytejumpParse(), and DetectBytejumpSetup().
#define DETECT_BYTEJUMP_OFFSET_BE 0x80
"byte extract" enabled
Definition at line 41 of file detect-bytejump.h.
Referenced by DetectBytejumpSetup().
#define DETECT_BYTEJUMP_RELATIVE 0x10
"relative" offset
Definition at line 38 of file detect-bytejump.h.
Referenced by DetectBytejumpDoMatch(), DetectBytejumpMatch(), DetectBytejumpParse(), and DetectBytejumpSetup().
#define DETECT_BYTEJUMP_STRING 0x08
"string" value
Definition at line 37 of file detect-bytejump.h.
Referenced by DetectBytejumpDoMatch(), DetectBytejumpMatch(), DetectBytejumpParse(), and DetectBytejumpSetup().
Typedef Documentation
typedef struct DetectBytejumpData_ DetectBytejumpData
Function Documentation
int DetectBytejumpDoMatch (DetectEngineThreadCtx * det_ctx, Signature * s, const SigMatchCtx * ctx, uint8_t * payload, uint32_t payload_len, uint8_t flags, int32_t offset)
Byte jump match function.
Parameters
det_ctx thread detect engine ctx
s signature
m byte jump sigmatch
payload ptr to the payload
payload_len length of the payload
Return values
1 match
0 no match
Definition at line 109 of file detect-bytejump.c.
References DetectBytejumpData_::base, DetectEngineThreadCtx_::buffer_offset, BYTE_BIG_ENDIAN, BYTE_LITTLE_ENDIAN, ByteExtractStringUint64(), ByteExtractUint64(), data, DETECT_BYTEJUMP_ALIGN, DETECT_BYTEJUMP_BEGIN, DETECT_BYTEJUMP_LITTLE, DETECT_BYTEJUMP_RELATIVE, DETECT_BYTEJUMP_STRING, len, DetectBytejumpData_::multiplier, DetectBytejumpData_::nbytes, DetectBytejumpData_::post_offset, SC_ERR_BYTE_EXTRACT_FAILED, SCEnter, SCLogDebug, SCLogDebugEnabled(), SCLogError, and SCReturnInt.
void DetectBytejumpFree (void * ptr)
this function will free memory associated with DetectBytejumpData
Parameters
data pointer to DetectBytejumpData
Definition at line 746 of file detect-bytejump.c.
References data, and SCFree.
Referenced by DetectBytejumpParse(), DetectBytejumpRegister(), and DetectBytejumpSetup().
int DetectBytejumpMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match byte_jump
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectBytejumpData
Return values
-1 error
0 no match
1 match
Todo:
The return seems backwards. We should return a non-zero error code. One of the error codes is "no match". As-is if someone accidentally does: if (DetectBytejumpMatch(...)) { match }, then they catch an error as a match.
Definition at line 221 of file detect-bytejump.c.
References DetectBytejumpData_::base, DetectEngineThreadCtx_::buffer_offset, BYTE_BIG_ENDIAN, BYTE_LITTLE_ENDIAN, ByteExtractStringUint64(), ByteExtractUint64(), data, DETECT_BYTEJUMP_ALIGN, DETECT_BYTEJUMP_BEGIN, DETECT_BYTEJUMP_LITTLE, DETECT_BYTEJUMP_RELATIVE, DETECT_BYTEJUMP_STRING, DetectBytejumpData_::flags, len, DetectBytejumpData_::multiplier, DetectBytejumpData_::nbytes, DetectBytejumpData_::offset, Packet_::payload, Packet_::payload_len, DetectBytejumpData_::post_offset, SC_ERR_BYTE_EXTRACT_FAILED, SCLogDebug, SCLogDebugEnabled(), and SCLogError.
Referenced by DetectBytejumpRegister().
DetectBytejumpData* DetectBytejumpParse (char * optstr, char ** offset)
This function is used to parse byte_jump options passed via
byte_jump: bytes, offset [,flags [, ...]]
flags: "big", "little", "relative", "string", "oct", "dec", "hex" "align", "from beginning", "multiplier N", "post_offset N"
Parameters
optstr Pointer to the user provided byte_jump options
offset Used to pass the offset back, if byte_jump uses a byte_extract var.
Return values
data pointer to DetectBytejumpData on success
NULL on failure
Todo:
Error on dups?
Definition at line 331 of file detect-bytejump.c.
References DetectBytejumpData_::base, ByteExtractStringInt32(), ByteExtractStringUint32(), data, DETECT_BYTEJUMP_ALIGN, DETECT_BYTEJUMP_BASE_DEC, DETECT_BYTEJUMP_BASE_HEX, DETECT_BYTEJUMP_BASE_OCT, DETECT_BYTEJUMP_BASE_UNSET, DETECT_BYTEJUMP_BEGIN, DETECT_BYTEJUMP_BIG, DETECT_BYTEJUMP_DCE, DETECT_BYTEJUMP_LITTLE, DETECT_BYTEJUMP_RELATIVE, DETECT_BYTEJUMP_STRING, DetectBytejumpFree(), DetectBytejumpData_::flags, MAX_SUBSTRINGS, DetectBytejumpData_::multiplier, DetectBytejumpData_::nbytes, DetectBytejumpData_::offset, DetectBytejumpData_::post_offset, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_PARSE, SCFree, SCLogError, SCMalloc, SCStrdup, str, strlcpy(), and unlikely.
Referenced by DetectBytejumpSetup().
void DetectBytejumpRegister (void)
Registration function for byte_jump.
Todo:
add support for no_stream and stream_only
Definition at line 65 of file detect-bytejump.c.
References DETECT_BYTEJUMP, DetectBytejumpFree(), DetectBytejumpMatch(), DetectBytejumpRegisterTests(), DetectBytejumpSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
int DetectBytejumpSetup (DetectEngineCtx * , Signature * , char *)
This function is used to add the parsed byte_jump data into the current signature.
Parameters
de_ctx pointer to the Detection Engine Context
s pointer to the Current Signature
optstr pointer to the user provided options
Return values
0 on Success
-1 on Failure
Definition at line 525 of file detect-bytejump.c.
References Signature_::alproto, ALPROTO_DCERPC, ALPROTO_UNKNOWN, AppLayerHtpEnableResponseBodyCallback(), DetectBytejumpData_::base, SigMatch_::ctx, data, DETECT_BYTE_EXTRACT, DETECT_BYTEJUMP, DETECT_BYTEJUMP_BASE_DEC, DETECT_BYTEJUMP_BASE_HEX, DETECT_BYTEJUMP_BASE_OCT, DETECT_BYTEJUMP_BEGIN, DETECT_BYTEJUMP_BIG, DETECT_BYTEJUMP_DCE, DETECT_BYTEJUMP_LITTLE, DETECT_BYTEJUMP_OFFSET_BE, DETECT_BYTEJUMP_RELATIVE, DETECT_BYTEJUMP_STRING, DETECT_BYTETEST, DETECT_CONTENT, DETECT_CONTENT_RELATIVE_NEXT, DETECT_ISDATAAT, DETECT_PCRE, DETECT_PCRE_RELATIVE_NEXT, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_NOTSET, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectByteExtractRetrieveSMVar(), DetectBytejumpFree(), DetectBytejumpParse(), DetectPcreData_::flags, DetectBytejumpData_::flags, DetectContentData_::flags, Signature_::flags, Signature_::list, DetectBytejumpData_::offset, SC_ERR_CONFLICTING_RULE_KEYWORDS, SC_ERR_INVALID_SIGNATURE, SCFree, SCLogError, SIG_FLAG_APPLAYER, SigMatchAlloc(), SigMatchAppendSMToList(), SigMatchGetLastSMFromLists(), SigMatchListSMBelongsTo(), Signature_::sm_lists_tail, and SigMatch_::type.
Referenced by DetectBytejumpRegister().