suricata: src/detect-iprep.c File Reference
detect-iprep.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "threads.h"
#include "flow.h"
#include "flow-bit.h"
#include "flow-util.h"
#include "detect-iprep.h"
#include "util-spm.h"
#include "app-layer-parser.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-fmemopen.h"
#include "reputation.h"
#include "host.h"
Macros
#define PARSE_REGEX "\\s*(any|src|dst|both)\\s*,\\s*([A-Za-z0-9\\-\\_]+)\\s*,\\s*(\<|\>|\\=)\\s*,\\s*([0-9]+)\\s*"
#define MAX_SUBSTRINGS 30
Functions
int DetectIPRepMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, const SigMatchCtx *)
void DetectIPRepFree (void *)
void IPRepRegisterTests (void)
this function registers unit tests for IPRep
void DetectIPRepRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements the iprep keyword
Definition in file detect-iprep.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
#define PARSE_REGEX "\\s*(any|src|dst|both)\\s*,\\s*([A-Za-z0-9\\-\\_]+)\\s*,\\s*(\<|\>|\\=)\\s*,\\s*([0-9]+)\\s*"
Definition at line 51 of file detect-iprep.c.
Referenced by DetectIPRepRegister().
Function Documentation
void DetectIPRepFree (void * ptr)
Definition at line 389 of file detect-iprep.c.
References SCFree.
Referenced by DetectIPRepRegister().
int DetectIPRepMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Definition at line 190 of file detect-iprep.c.
References DetectIPRepData_::cat, DetectIPRepData_::cmd, DetectEngineThreadCtx_::de_ctx, DETECT_IPREP_CMD_ANY, DETECT_IPREP_CMD_BOTH, DETECT_IPREP_CMD_DST, DETECT_IPREP_CMD_SRC, DetectIPRepData_::op, SCLogDebug, DetectEngineCtx_::srep_version, DetectEngineCtx_::srepCIDR_ctx, SRepCIDRGetIPRepDst(), SRepCIDRGetIPRepSrc(), and DetectIPRepData_::val.
Referenced by DetectIPRepRegister().
void DetectIPRepRegister (void)
Definition at line 60 of file detect-iprep.c.
References DETECT_IPREP, DetectIPRepFree(), DetectIPRepMatch(), SigTableElmt_::flags, SigTableElmt_::Free, IPRepRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, and sigmatch_table.
Referenced by SigTableSetup().
void IPRepRegisterTests (void)
this function registers unit tests for IPRep
Definition at line 1017 of file detect-iprep.c.
Referenced by DetectIPRepRegister().