suricata: src/detect-icmp-seq.c File Reference
detect-icmp-seq.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-icmp-seq.h"
#include "util-byte.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^\\s*(\"\\s*)?([0-9]+)(\\s*\")?\\s*$"
#define MAX_SUBSTRINGS 30
Functions
int DetectIcmpSeqMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match icmp_seq rule option set on a packet.
void DetectIcmpSeqRegisterTests (void)
void DetectIcmpSeqFree (void *ptr)
this function will free memory associated with DetectIcmpSeqData
void DetectIcmpSeqRegister (void)
Registration function for icmp_seq.
DetectIcmpSeqData * DetectIcmpSeqParse (char *icmpseqstr)
This function is used to parse icmp_seq option passed via icmp_seq: keyword.
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Implements the icmp_seq keyword
Definition in file detect-icmp-seq.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectIcmpSeqParse().
#define PARSE_REGEX "^\\s*(\"\\s*)?([0-9]+)(\\s*\")?\\s*$"
Definition at line 40 of file detect-icmp-seq.c.
Referenced by DetectIcmpSeqRegister().
Function Documentation
void DetectIcmpSeqFree (void * ptr)
this function will free memory associated with DetectIcmpSeqData
Parameters
ptr pointer to DetectIcmpSeqData
Definition at line 263 of file detect-icmp-seq.c.
References SCFree.
Referenced by DetectIcmpSeqParse(), and DetectIcmpSeqRegister().
int DetectIcmpSeqMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match icmp_seq rule option set on a packet.
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectIcmpSeqData
Return values
0 no match
1 match
Definition at line 95 of file detect-icmp-seq.c.
References ICMP6_ECHO_REPLY, ICMP6_ECHO_REQUEST, ICMPV4_GET_SEQ, ICMPV4_GET_TYPE, ICMPV6_GET_SEQ, ICMPV6_GET_TYPE, PKT_IS_ICMPV4, PKT_IS_ICMPV6, PKT_IS_PSEUDOPKT, SCLogDebug, and DetectIcmpSeqData_::seq.
Referenced by DetectIcmpSeqRegister().
DetectIcmpSeqData* DetectIcmpSeqParse (char * icmpseqstr)
This function is used to parse icmp_seq option passed via icmp_seq: keyword.
Parameters
icmpseqstr Pointer to the user provided icmp_seq options
Return values
iseq pointer to DetectIcmpSeqData on success
NULL on failure
Definition at line 157 of file detect-icmp-seq.c.
References ByteExtractStringUint16(), DetectIcmpSeqFree(), MAX_SUBSTRINGS, SC_ERR_INVALID_ARGUMENT, SC_ERR_MISSING_QUOTE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogError, SCMalloc, DetectIcmpSeqData_::seq, and unlikely.
void DetectIcmpSeqRegister (void)
Registration function for icmp_seq.
Definition at line 53 of file detect-icmp-seq.c.
References SigTableElmt_::desc, DETECT_ICMP_SEQ, DetectIcmpSeqFree(), DetectIcmpSeqMatch(), DetectIcmpSeqRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectIcmpSeqRegisterTests (void)
Definition at line 381 of file detect-icmp-seq.c.
Referenced by DetectIcmpSeqRegister().