suricata: src/detect-fragbits.c File Reference
detect-fragbits.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "flow-var.h"
#include "decode-events.h"
#include "app-layer.h"
#include "app-layer-detect-proto.h"
#include "detect-fragbits.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "pkt-var.h"
#include "host.h"
#include "util-profiling.h"
Macros
#define PARSE_REGEX "^\\s*(?:([\\+\\*!]))?\\s*([MDR]+)"
#define MODIFIER_NOT 1
#define MODIFIER_PLUS 2
#define MODIFIER_ANY 3
#define FRAGBITS_HAVE_MF 0x01
#define FRAGBITS_HAVE_DF 0x02
#define FRAGBITS_HAVE_RF 0x04
#define MAX_SUBSTRINGS 30
Functions
void DetectFragBitsRegister (void)
Registration function for fragbits: keyword.
void FragBitsRegisterTests (void)
this function registers unit tests for FragBits
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Implements fragbits keyword
Definition in file detect-fragbits.c.
Macro Definition Documentation
#define FRAGBITS_HAVE_DF 0x02
Definition at line 62 of file detect-fragbits.c.
#define FRAGBITS_HAVE_MF 0x01
Definition at line 61 of file detect-fragbits.c.
#define FRAGBITS_HAVE_RF 0x04
Definition at line 63 of file detect-fragbits.c.
#define MAX_SUBSTRINGS 30
#define MODIFIER_ANY 3
Definition at line 59 of file detect-fragbits.c.
#define MODIFIER_NOT 1
FragBits args[0] *(3) +(2) !(1)
Definition at line 57 of file detect-fragbits.c.
#define MODIFIER_PLUS 2
Definition at line 58 of file detect-fragbits.c.
#define PARSE_REGEX "^\\s*(?:([\\+\\*!]))?\\s*([MDR]+)"
Regex fragbits: [!+*](MDR)
Definition at line 50 of file detect-fragbits.c.
Referenced by DetectFragBitsRegister().
Function Documentation
void DetectFragBitsRegister (void)
Registration function for fragbits: keyword.
Registration function for fragbits: keyword
Definition at line 76 of file detect-fragbits.c.
References SigTableElmt_::desc, DETECT_FRAGBITS, FragBitsRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void FragBitsRegisterTests (void)
this function registers unit tests for FragBits
This function registers unit tests for FragBits
Definition at line 573 of file detect-fragbits.c.
Referenced by DetectFragBitsRegister().