suricata: src/detect.c File Reference
detect.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "debug.h"
#include "detect.h"
#include "flow.h"
#include "flow-private.h"
#include "flow-bit.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-alert.h"
#include "detect-engine-siggroup.h"
#include "detect-engine-address.h"
#include "detect-engine-proto.h"
#include "detect-engine-port.h"
#include "detect-engine-mpm.h"
#include "detect-engine-iponly.h"
#include "detect-engine-threshold.h"
#include "detect-engine-payload.h"
#include "detect-engine-dcepayload.h"
#include "detect-engine-uri.h"
#include "detect-dns-query.h"
#include "detect-engine-state.h"
#include "detect-engine-analyzer.h"
#include "detect-engine-filedata-smtp.h"
#include "detect-http-cookie.h"
#include "detect-http-method.h"
#include "detect-http-ua.h"
#include "detect-http-hh.h"
#include "detect-http-hrh.h"
#include "detect-engine-event.h"
#include "decode.h"
#include "detect-ipopts.h"
#include "detect-flags.h"
#include "detect-fragbits.h"
#include "detect-fragoffset.h"
#include "detect-gid.h"
#include "detect-ack.h"
#include "detect-seq.h"
#include "detect-content.h"
#include "detect-uricontent.h"
#include "detect-pcre.h"
#include "detect-depth.h"
#include "detect-nocase.h"
#include "detect-rawbytes.h"
#include "detect-bytetest.h"
#include "detect-bytejump.h"
#include "detect-sameip.h"
#include "detect-l3proto.h"
#include "detect-ipproto.h"
#include "detect-within.h"
#include "detect-distance.h"
#include "detect-offset.h"
#include "detect-sid.h"
#include "detect-priority.h"
#include "detect-classtype.h"
#include "detect-reference.h"
#include "detect-tag.h"
#include "detect-threshold.h"
#include "detect-metadata.h"
#include "detect-msg.h"
#include "detect-rev.h"
#include "detect-flow.h"
#include "detect-window.h"
#include "detect-ftpbounce.h"
#include "detect-isdataat.h"
#include "detect-id.h"
#include "detect-rpc.h"
#include "detect-asn1.h"
#include "detect-filename.h"
#include "detect-fileext.h"
#include "detect-filestore.h"
#include "detect-filemagic.h"
#include "detect-filemd5.h"
#include "detect-filesize.h"
#include "detect-dsize.h"
#include "detect-flowvar.h"
#include "detect-flowint.h"
#include "detect-pktvar.h"
#include "detect-noalert.h"
#include "detect-flowbits.h"
#include "detect-hostbits.h"
#include "detect-xbits.h"
#include "detect-csum.h"
#include "detect-stream_size.h"
#include "detect-engine-sigorder.h"
#include "detect-ttl.h"
#include "detect-fast-pattern.h"
#include "detect-itype.h"
#include "detect-icode.h"
#include "detect-icmp-id.h"
#include "detect-icmp-seq.h"
#include "detect-dce-iface.h"
#include "detect-dce-opnum.h"
#include "detect-dce-stub-data.h"
#include "detect-urilen.h"
#include "detect-detection-filter.h"
#include "detect-http-client-body.h"
#include "detect-http-server-body.h"
#include "detect-http-header.h"
#include "detect-http-raw-header.h"
#include "detect-http-uri.h"
#include "detect-http-raw-uri.h"
#include "detect-http-stat-msg.h"
#include "detect-engine-hcbd.h"
#include "detect-engine-hsbd.h"
#include "detect-engine-hhd.h"
#include "detect-engine-hrhd.h"
#include "detect-engine-hmd.h"
#include "detect-engine-hcd.h"
#include "detect-engine-hrud.h"
#include "detect-engine-hsmd.h"
#include "detect-engine-hscd.h"
#include "detect-engine-hua.h"
#include "detect-engine-hhhd.h"
#include "detect-engine-hrhhd.h"
#include "detect-byte-extract.h"
#include "detect-file-data.h"
#include "detect-pkt-data.h"
#include "detect-replace.h"
#include "detect-tos.h"
#include "detect-app-layer-event.h"
#include "detect-lua.h"
#include "detect-iprep.h"
#include "detect-geoip.h"
#include "detect-app-layer-protocol.h"
#include "detect-template.h"
#include "detect-template-buffer.h"
#include "util-rule-vars.h"
#include "app-layer.h"
#include "app-layer-protos.h"
#include "app-layer-htp.h"
#include "app-layer-smtp.h"
#include "app-layer-template.h"
#include "detect-tls.h"
#include "detect-tls-version.h"
#include "detect-ssh-proto-version.h"
#include "detect-ssh-software-version.h"
#include "detect-http-stat-code.h"
#include "detect-ssl-version.h"
#include "detect-ssl-state.h"
#include "detect-modbus.h"
#include "action-globals.h"
#include "tm-threads.h"
#include "pkt-var.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "stream-tcp.h"
#include "stream-tcp-inline.h"
#include "util-var-name.h"
#include "util-classification-config.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
#include "util-hashlist.h"
#include "util-cuda.h"
#include "util-privs.h"
#include "util-profiling.h"
#include "util-validate.h"
#include "util-optimize.h"
#include "util-path.h"
#include "util-mpm-ac.h"
#include "runmodes.h"
#include <glob.h>
Macros
#define SMS_USE_FLOW_SGH 0x01
#define SMS_USED_PM 0x02
#define SMS_USED_STREAM_PM 0x04
#define MALLOC_JUMP 5
#define MASK_TCP_INITDEINIT_FLAGS (TH_SYN|TH_RST|TH_FIN)
#define MASK_TCP_UNUSUAL_FLAGS (TH_URG|TH_ECN|TH_CWR)
#define SMALL_MPM(c) ((c) == 1)
#define PRINTSIGS
Functions
SigMatch * SigMatchAlloc (void)
void DetectExitPrintStats (ThreadVars *tv, void *data)
void DbgPrintSigs (DetectEngineCtx *, SigGroupHead *)
void DbgPrintSigs2 (DetectEngineCtx *, SigGroupHead *)
TmEcode Detect (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
Detection engine thread wrapper.
TmEcode DetectThreadInit (ThreadVars *, void *, void **)
TmEcode DetectThreadDeinit (ThreadVars *, void *)
void TmModuleDetectRegister (void)
char * DetectLoadCompleteSigPath (const DetectEngineCtx *de_ctx, char *sig_file)
Create the path if default-rule-path was specified.
int SigLoadSignatures (DetectEngineCtx *de_ctx, char *sig_file, int sig_file_exclusive)
Load signatures.
int SigMatchSignaturesRunPostMatch (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s)
SigGroupHead * SigMatchSignaturesGetSgh (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Packet *p)
Get the SigGroupHead for a packet.
int SigMatchSignatures (ThreadVars *th_v, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Packet *p)
Signature match function.
void DetectSignatureApplyActions (Packet *p, const Signature *s)
Apply action(s) and Set 'drop' sig info, if applicable.
void SigCleanSignatures (DetectEngineCtx *de_ctx)
Signature * SigFindSignatureBySidGid (DetectEngineCtx *de_ctx, uint32_t sid, uint32_t gid)
Find a specific signature by sid and gid.
int SignatureIsAppLayer (DetectEngineCtx *de_ctx, Signature *s)
int SignatureIsFilestoring (Signature *s)
Check if a signature contains the filestore keyword.
int SignatureIsFilemagicInspecting (Signature *s)
Check if a signature contains the filemagic keyword.
int SignatureIsFileMd5Inspecting (Signature *s)
Check if a signature contains the filemd5 keyword.
int SignatureIsFilesizeInspecting (Signature *s)
Check if a signature contains the filesize keyword.
int SignatureIsIPOnly (DetectEngineCtx *de_ctx, Signature *s)
Test is a initialized signature is IP only.
int SigAddressPrepareStage1 (DetectEngineCtx *de_ctx)
Preprocess signature, classify ip-only, etc, build sig array.
int CreateGroupedAddrListCmpCnt (DetectAddress *a, DetectAddress *b)
int CreateGroupedAddrListCmpMpmMinlen (DetectAddress *a, DetectAddress *b)
int CreateGroupedAddrList (DetectEngineCtx *de_ctx, DetectAddress *srchead, int family, DetectAddressHead *newhead, uint32_t unique_groups, int(*CompareFunc)(DetectAddress *, DetectAddress *), uint32_t max_idx)
int CreateGroupedPortListCmpCnt (DetectPort *a, DetectPort *b)
int CreateGroupedPortListCmpMpmMinlen (DetectPort *a, DetectPort *b)
int CreateGroupedPortList (DetectEngineCtx *de_ctx, HashListTable *port_hash, DetectPort **newhead, uint32_t unique_groups, int(*CompareFunc)(DetectPort *, DetectPort *), uint32_t max_idx)
int SigAddressPrepareStage2 (DetectEngineCtx *de_ctx)
Fill the global src group head, with the sigs included.
int BuildDestinationAddressHeads (DetectEngineCtx *de_ctx, DetectAddressHead *head, int family, int flow)
Build the destination address portion of the match tree.
int BuildDestinationAddressHeadsWithBothPorts (DetectEngineCtx *de_ctx, DetectAddressHead *head, int family, int flow)
int SigAddressPrepareStage3 (DetectEngineCtx *de_ctx)
int SigAddressCleanupStage1 (DetectEngineCtx *de_ctx)
void DbgSghContainsSig (DetectEngineCtx *de_ctx, SigGroupHead *sgh, uint32_t sid)
int SigAddressPrepareStage4 (DetectEngineCtx *de_ctx)
finalize preparing sgh's
int SigAddressPrepareStage5 (DetectEngineCtx *de_ctx)
int SigGroupBuild (DetectEngineCtx *de_ctx)
Convert the signature list into the runtime match structure.
int SigGroupCleanup (DetectEngineCtx *de_ctx)
void SigTableList (const char *keyword)
void SigTableSetup (void)
void SigTableRegisterTests (void)
void SigRegisterTests (void)
Variables
int rule_reload
int engine_analysis
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Basic detection engine
Definition in file detect.c.
Macro Definition Documentation
#define MALLOC_JUMP 5
#define MASK_TCP_INITDEINIT_FLAGS (TH_SYN|TH_RST|TH_FIN)
Definition at line 2365 of file detect.c.
#define MASK_TCP_UNUSUAL_FLAGS (TH_URG|TH_ECN|TH_CWR)
Definition at line 2366 of file detect.c.
#define PRINTSIGS
Definition at line 4277 of file detect.c.
#define SMALL_MPM (c) ((c) == 1)
Definition at line 3097 of file detect.c.
Referenced by CreateGroupedAddrList(), CreateGroupedAddrListCmpMpmMinlen(), CreateGroupedPortList(), and CreateGroupedPortListCmpMpmMinlen().
#define SMS_USE_FLOW_SGH 0x01
Definition at line 854 of file detect.c.
Referenced by SigMatchSignatures().
#define SMS_USED_PM 0x02
Definition at line 855 of file detect.c.
Referenced by SigMatchSignatures().
#define SMS_USED_STREAM_PM 0x04
Definition at line 856 of file detect.c.
Referenced by SigMatchSignatures().
Function Documentation
int BuildDestinationAddressHeads (DetectEngineCtx * de_ctx, DetectAddressHead * head, int family, int flow)
Build the destination address portion of the match tree.
Definition at line 3635 of file detect.c.
References ADDRESS_SIGGROUPHEAD_COPY, CreateGroupedAddrList(), CreateGroupedAddrListCmpMpmMinlen(), DetectAddressAdd(), DetectAddressCleanupList(), DetectAddressCopy(), DetectAddressHeadInit(), DetectAddressLookupInList(), Signature_::dst, DetectAddress_::dst_gh, DetectEngineCtx_::gh_reuse, DetectEngineCtx_::gh_unique, SigGroupHead_::init, DetectEngineCtx_::max_uniq_toclient_dst_groups, DetectEngineCtx_::max_uniq_toserver_dst_groups, DetectAddress_::next, PatternMatchPrepareGroup(), SCLogDebug, DetectAddress_::sh, DetectEngineCtx_::sig_array, SigGroupHeadInitData_::sig_array, DetectEngineCtx_::sig_array_len, SIG_GROUP_HEAD_REFERENCED, SigGroupHeadAppendSig(), SigGroupHeadBuildMatchArray(), SigGroupHeadFree(), SigGroupHeadHashAdd(), SigGroupHeadHashLookup(), SigGroupHeadSetSigCnt(), and SigGroupHeadStore().
Referenced by SigAddressPrepareStage3().
int BuildDestinationAddressHeadsWithBothPorts (DetectEngineCtx * de_ctx, DetectAddressHead * head, int family, int flow)
Definition at line 3754 of file detect.c.
References ADDRESS_HAVEPORT, ADDRESS_PORTS_COPY, ADDRESS_SIGGROUPHEAD_COPY, BUG_ON, DetectPort_::cnt, CreateGroupedAddrList(), CreateGroupedAddrListCmpMpmMinlen(), CreateGroupedPortList(), CreateGroupedPortListCmpMpmMinlen(), DetectAddressAdd(), DetectAddressCleanupList(), DetectAddressCopy(), DetectAddressHeadInit(), DetectAddressLookupInList(), DetectPortCleanupList(), DetectPortCopySingle(), DetectPortDpHashAdd(), DetectPortDpHashLookup(), DetectPortDpHashReset(), DetectPortSpHashAdd(), DetectPortSpHashLookup(), DetectPortSpHashReset(), Signature_::dp, DetectEngineCtx_::dport_hash_table, Signature_::dst, DetectAddress_::dst_gh, DetectPort_::dst_ph, DetectPort_::flags, SigGroupHead_::flags, DetectEngineCtx_::gh_reuse, DetectEngineCtx_::gh_unique, SigGroupHead_::init, DetectEngineCtx_::max_uniq_toclient_dp_groups, DetectEngineCtx_::max_uniq_toclient_dst_groups, DetectEngineCtx_::max_uniq_toclient_sp_groups, DetectEngineCtx_::max_uniq_toserver_dp_groups, DetectEngineCtx_::max_uniq_toserver_dst_groups, DetectEngineCtx_::max_uniq_toserver_sp_groups, DetectAddress_::next, DetectPort_::next, PatternMatchPrepareGroup(), DetectPort_::port, SigGroupHeadInitData_::port, PORT_GROUP_PORTS_COPY, PORT_SIGGROUPHEAD_COPY, SCLogDebug, DetectAddress_::sh, DetectPort_::sh, DetectEngineCtx_::sig_array, SigGroupHeadInitData_::sig_array, DetectEngineCtx_::sig_array_len, SIG_GROUP_HEAD_FREE, SIG_GROUP_HEAD_REFERENCED, SigGroupHeadAppendSig(), SigGroupHeadBuildMatchArray(), SigGroupHeadDPortHashAdd(), SigGroupHeadDPortHashLookup(), SigGroupHeadFree(), SigGroupHeadHashAdd(), SigGroupHeadHashLookup(), SigGroupHeadHashRemove(), SigGroupHeadSetSigCnt(), SigGroupHeadSPortHashAdd(), SigGroupHeadSPortHashLookup(), SigGroupHeadStore(), Signature_::sp, and DetectEngineCtx_::sport_hash_table.
Referenced by SigAddressPrepareStage3().
int CreateGroupedAddrList (DetectEngineCtx * de_ctx, DetectAddress * srchead, int family, DetectAddressHead * newhead, uint32_t unique_groups, int(*)(DetectAddress *, DetectAddress *) CompareFunc, uint32_t max_idx)
Definition at line 3126 of file detect.c.
References ADDRESS_FLAG_ANY, ADDRESS_HAVEPORT, BUG_ON, DetectAddressCopy(), DetectAddressFree(), DetectAddressInsert(), DetectAddressJoin(), DetectPortInsertCopy(), Address_::family, DetectAddress_::flags, DetectAddress_::ip, SigGroupHead_::mpm_content_minlen, DetectAddress_::next, DetectPort_::next, DetectAddress_::port, DetectAddress_::sh, SigGroupHeadCopySigs(), and SMALL_MPM.
Referenced by BuildDestinationAddressHeads(), BuildDestinationAddressHeadsWithBothPorts(), and SigAddressPrepareStage2().
int CreateGroupedAddrListCmpCnt (DetectAddress * a, DetectAddress * b)
Definition at line 3101 of file detect.c.
References DetectAddress_::cnt.
int CreateGroupedAddrListCmpMpmMinlen (DetectAddress * a, DetectAddress * b)
Definition at line 3108 of file detect.c.
References SigGroupHead_::mpm_content_minlen, DetectAddress_::sh, and SMALL_MPM.
Referenced by BuildDestinationAddressHeads(), BuildDestinationAddressHeadsWithBothPorts(), and SigAddressPrepareStage2().
int CreateGroupedPortList (DetectEngineCtx * de_ctx, HashListTable * port_hash, DetectPort ** newhead, uint32_t unique_groups, int(*)(DetectPort *, DetectPort *) CompareFunc, uint32_t max_idx)
Definition at line 3301 of file detect.c.
References BUG_ON, DetectPortCopySingle(), DetectPortFree(), DetectPortInsert(), DetectPortJoin(), DetectPortPrint(), DetectPortPrintList(), HashListTableGetListData, HashListTableGetListHead(), HashListTableGetListNext, SigGroupHead_::mpm_content_minlen, DetectPort_::next, SCLogDebug, DetectPort_::sh, and SMALL_MPM.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
int CreateGroupedPortListCmpCnt (DetectPort * a, DetectPort * b)
Definition at line 3276 of file detect.c.
References DetectPort_::cnt.
int CreateGroupedPortListCmpMpmMinlen (DetectPort * a, DetectPort * b)
Definition at line 3283 of file detect.c.
References SigGroupHead_::mpm_content_minlen, DetectPort_::sh, and SMALL_MPM.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DbgPrintSigs (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Definition at line 4185 of file detect.c.
References Signature_::id, SigGroupHead_::match_array, and SigGroupHead_::sig_cnt.
void DbgPrintSigs2 (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Definition at line 4199 of file detect.c.
References DetectEngineGetMaxSigId, Signature_::id, SigGroupHead_::init, DetectEngineCtx_::sig_array, and SigGroupHeadInitData_::sig_array.
void DbgSghContainsSig (DetectEngineCtx * de_ctx, SigGroupHead * sgh, uint32_t sid)
Definition at line 4215 of file detect.c.
References DetectEngineGetMaxSigId, Signature_::id, SigGroupHead_::init, DetectEngineCtx_::sig_array, and SigGroupHeadInitData_::sig_array.
TmEcode Detect (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
Detection engine thread wrapper.
Parameters
tv thread vars
p packet to inspect
data thread specific data
pq packet queue
Return values
TM_ECODE_FAILED error
TM_ECODE_OK ok
Definition at line 1954 of file detect.c.
References ACTION_DROP, AppLayerParserProtocolSupportsTxs(), DetectEngineThreadCtx_::de_ctx, DEBUG_VALIDATE_PACKET, DeStateUpdateInspectTransactionId(), Flow_::flags, Packet_::flags, Packet_::flow, FLOW_NOPACKET_INSPECTION, FLOW_PKT_TOSERVER, Packet_::flowflags, FlowGetAppProtocol(), FlowGetDisruptionFlags(), FLOWLOCK_RDLOCK, FLOWLOCK_UNLOCK, DetectEngineThreadCtx_::mt_det_ctxs_cnt, DetectEngineThreadCtx_::mt_det_ctxs_hash, PACKET_TEST_ACTION, PKT_NOPACKET_INSPECTION, Packet_::proto, SC_ATOMIC_GET, SC_ATOMIC_SET, SCLogDebug, SigMatchSignatures(), STREAM_TOCLIENT, STREAM_TOSERVER, Packet_::tenant_id, DetectEngineThreadCtx_::TenantGetId, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleDetectRegister().
void DetectExitPrintStats (ThreadVars * tv, void * data)
Definition at line 239 of file detect.c.
Referenced by TmModuleDetectRegister().
char* DetectLoadCompleteSigPath (const DetectEngineCtx * de_ctx, char * sig_file)
Create the path if default-rule-path was specified.
Parameters
sig_file The name of the file
Return values
str Pointer to the string path + sig_file
Definition at line 251 of file detect.c.
References ConfGet(), DetectEngineCtx_::config_prefix, PathIsRelative(), SCLogDebug, SCMalloc, SCStrdup, strlcat(), strlcpy(), unlikely, and ptxdump::varname.
Referenced by SigLoadSignatures().
void DetectSignatureApplyActions (Packet * p, const Signature * s)
Apply action(s) and Set 'drop' sig info, if applicable.
Definition at line 1923 of file detect.c.
References PacketAlert_::action, Signature_::action, ACTION_DROP, Packet_::alerts, PacketAlerts_::drop, PacketAlert_::num, Signature_::num, PACKET_UPDATE_ACTION, and PacketAlert_::s.
Referenced by DeStateDetectStartDetection(), IPOnlyMatchPacket(), PacketAlertFinalize(), and SigMatchSignatures().
TmEcode DetectThreadDeinit (ThreadVars * t, void * data)
Definition at line 2041 of file detect.c.
References DetectEngineThreadCtxDeinit().
Referenced by TmModuleDetectRegister().
TmEcode DetectThreadInit (ThreadVars * t, void * initdata, void ** data)
Definition at line 2036 of file detect.c.
References DetectEngineThreadCtxInit().
Referenced by TmModuleDetectRegister().
int SigAddressCleanupStage1 (DetectEngineCtx * de_ctx)
Definition at line 4156 of file detect.c.
References BUG_ON, DE_QUIET, DetectEngineCtx_::decoder_event_sgh, DetectAddressHeadFree(), DetectEngineCtx_::flags, DetectEngineCtx_::flow_gh, FLOW_STATES, DetectEngineCtx_::io_ctx, IPOnlyDeinit(), proto, SCLogDebug, SCLogInfo, SigGroupHeadFree(), and DetectEngineLookupFlow_::src_gh.
Referenced by SigGroupCleanup().
int SigAddressPrepareStage1 (DetectEngineCtx * de_ctx)
Preprocess signature, classify ip-only, etc, build sig array.
Parameters
de_ctx Pointer to the Detection Engine Context
Return values
0 on success
-1 on failure
Definition at line 2880 of file detect.c.
References DetectContentData_::content_len, SigMatch_::ctx, DE_QUIET, DETECT_CONTENT, DetectEngineCtx_::detect_luajit_instances, DETECT_SM_LIST_MATCH, DetectEngineGetMaxSigId, DetectEngineCtx_::failure_fatal, Signature_::flags, DetectEngineCtx_::flags, Signature_::id, Signature_::init_flags, SigMatch_::next, Signature_::next, Signature_::num, DetectProto_::proto, proto, Signature_::proto, SCLogDebug, SCLogDebugEnabled(), SCLogInfo, SCMalloc, DetectEngineCtx_::sig_array, DetectEngineCtx_::sig_array_len, DetectEngineCtx_::sig_array_size, DetectEngineCtx_::sig_cnt, SIG_FLAG_APPLAYER, SIG_FLAG_INIT_DEONLY, SIG_FLAG_INIT_PAYLOAD, SIG_FLAG_IPONLY, DetectEngineCtx_::sig_list, SignatureIsIPOnly(), Signature_::sm_lists, TRUE, and SigMatch_::type.
Referenced by SigGroupBuild().
int SigAddressPrepareStage2 (DetectEngineCtx * de_ctx)
Fill the global src group head, with the sigs included.
Parameters
de_ctx Pointer to the Detection Engine Context whose Signatures have to be processed
Return values
0 On success
-1 On failure
Definition at line 3456 of file detect.c.
References DetectAddressHead_::any_head, CreateGroupedAddrList(), CreateGroupedAddrListCmpMpmMinlen(), DE_QUIET, DetectAddressHeadFree(), DetectAddressHeadInit(), DetectEngineGetMaxSigId, Signature_::flags, DetectEngineCtx_::flags, DetectEngineCtx_::flow_gh, FLOW_STATES, Signature_::id, Signature_::init_flags, DetectEngineCtx_::io_ctx, IPOnlyAddSignature(), IPOnlyInit(), IPOnlyPrepare(), IPOnlyPrint(), DetectAddressHead_::ipv4_head, DetectAddressHead_::ipv6_head, DetectEngineCtx_::max_uniq_toclient_src_groups, DetectEngineCtx_::max_uniq_toserver_src_groups, DetectAddress_::next, Signature_::next, proto, SCLogDebug, SCLogInfo, SIG_FLAG_INIT_DEONLY, SIG_FLAG_IPONLY, DetectEngineCtx_::sig_list, DetectEngineLookupFlow_::src_gh, and DetectEngineLookupFlow_::tmp_gh.
Referenced by SigGroupBuild().
int SigAddressPrepareStage3 (DetectEngineCtx * de_ctx)
Definition at line 4043 of file detect.c.
References BuildDestinationAddressHeads(), BuildDestinationAddressHeadsWithBothPorts(), DE_QUIET, DetectEngineGetMaxSigId, DetectPortDpHashFree(), DetectPortSpHashFree(), DetectEngineCtx_::flags, DetectEngineCtx_::flow_gh, FLOW_STATES, DetectEngineCtx_::gh_reuse, DetectEngineCtx_::gh_unique, proto, SCLogDebug, SCLogInfo, SigGroupHeadDPortHashFree(), SigGroupHeadFreeMpmArrays(), SigGroupHeadFreeSigArrays(), SigGroupHeadHashFree(), SigGroupHeadMpmHashFree(), SigGroupHeadMpmUriHashFree(), SigGroupHeadSPortHashFree(), and DetectEngineLookupFlow_::src_gh.
Referenced by SigGroupBuild().
int SigAddressPrepareStage4 (DetectEngineCtx * de_ctx)
finalize preparing sgh's
Definition at line 4239 of file detect.c.
References DetectEngineCtx_::decoder_event_sgh, DETECT_SM_LIST_UMATCH, SigGroupHead_::filestore_cnt, SigGroupHead_::mpm_uricontent_minlen, SCEnter, SCFree, SCLogDebug, SCReturnInt, DetectEngineCtx_::sgh_array, DetectEngineCtx_::sgh_array_cnt, DetectEngineCtx_::sgh_array_size, SigGroupHeadBuildNonMpmArray(), SigGroupHeadGetMinMpmSize(), SigGroupHeadSetFilemagicFlag(), SigGroupHeadSetFileMd5Flag(), SigGroupHeadSetFilesizeFlag(), and SigGroupHeadSetFilestoreCount().
Referenced by SigGroupBuild().
int SigAddressPrepareStage5 (DetectEngineCtx * de_ctx)
Definition at line 4280 of file detect.c.
References ADDRESS_SIGGROUPHEAD_COPY, DetectAddressHead_::any_head, DetectAddressPrint(), DetectPortPrint(), DetectAddress_::dst_gh, DetectPort_::dst_ph, DetectEngineCtx_::flow_gh, FLOW_STATES, Signature_::id, DetectAddressHead_::ipv4_head, DetectAddressHead_::ipv6_head, SigGroupHead_::match_array, SigGroupHead_::mpm_content_minlen, DetectAddress_::next, DetectPort_::next, DetectPort_::port, proto, DetectAddress_::sh, DetectPort_::sh, DetectEngineCtx_::sig_array, SigGroupHead_::sig_cnt, SigGroupHeadPrintSigs(), and DetectEngineLookupFlow_::src_gh.
void SigCleanSignatures (DetectEngineCtx * de_ctx)
Definition at line 2046 of file detect.c.
References DetectEngineResetMaxSigId(), Signature_::next, DetectEngineCtx_::sig_list, and SigFree().
Referenced by DetectEngineCtxFree().
Signature* SigFindSignatureBySidGid (DetectEngineCtx * de_ctx, uint32_t sid, uint32_t gid)
Find a specific signature by sid and gid.
Parameters
de_ctx detection engine ctx
sid the signature id
gid the signature group id
Return values
s sig found
NULL sig not found
Definition at line 2073 of file detect.c.
References Signature_::gid, Signature_::id, Signature_::next, and DetectEngineCtx_::sig_list.
int SigGroupBuild (DetectEngineCtx * de_ctx)
Convert the signature list into the runtime match structure.
Parameters
de_ctx Pointer to the Detection Engine Context whose Signatures have to be processed
Return values
0 On Success.
-1 On failure.
Definition at line 4637 of file detect.c.
References CudaHandlerGetCudaProfile(), CudaHandlerModuleGetContext(), DetectSetFastPatternAndItsId(), ENGINE_SGH_MPM_FACTORY_CONTEXT_SINGLE, DetectEngineCtx_::mpm_matcher, mpm_table, MpmFactoryGetMpmCtxForProfile(), Signature_::next, Signature_::num, PatternMatchDefaultMatcher(), MpmTableElmt_::Prepare, SC_ERR_DETECT_PREPARE, SC_ERR_FATAL, SCLogError, SCProfilingRuleInitCounters(), DetectEngineCtx_::sgh_mpm_context, DetectEngineCtx_::sgh_mpm_context_hcbd, DetectEngineCtx_::sgh_mpm_context_hcd, DetectEngineCtx_::sgh_mpm_context_hhd, DetectEngineCtx_::sgh_mpm_context_hhhd, DetectEngineCtx_::sgh_mpm_context_hmd, DetectEngineCtx_::sgh_mpm_context_hrhd, DetectEngineCtx_::sgh_mpm_context_hrhhd, DetectEngineCtx_::sgh_mpm_context_hrud, DetectEngineCtx_::sgh_mpm_context_hsbd, DetectEngineCtx_::sgh_mpm_context_hscd, DetectEngineCtx_::sgh_mpm_context_hsmd, DetectEngineCtx_::sgh_mpm_context_huad, DetectEngineCtx_::sgh_mpm_context_proto_other_packet, DetectEngineCtx_::sgh_mpm_context_proto_tcp_packet, DetectEngineCtx_::sgh_mpm_context_proto_udp_packet, DetectEngineCtx_::sgh_mpm_context_smtp, DetectEngineCtx_::sgh_mpm_context_stream, DetectEngineCtx_::sgh_mpm_context_uri, DetectEngineCtx_::sig_list, SigAddressPrepareStage1(), SigAddressPrepareStage2(), SigAddressPrepareStage3(), SigAddressPrepareStage4(), and DetectEngineCtx_::signum.
Referenced by SigLoadSignatures().
int SigGroupCleanup (DetectEngineCtx * de_ctx)
Definition at line 4918 of file detect.c.
References SigAddressCleanupStage1().
Referenced by DetectEngineCtxFree().
int SigLoadSignatures (DetectEngineCtx * de_ctx, char * sig_file, int sig_file_exclusive)
Load signatures.
Parameters
de_ctx Pointer to the detection engine context
sig_file Filename (or pattern) holding signatures
sig_file_exclusive File passed in 'sig_file' should be loaded exclusively.
Return values
-1 on error
Definition at line 442 of file detect.c.
References SigFileLoaderStat_::bad_files, SigFileLoaderStat_::bad_sigs_total, CleanupFPAnalyzer(), CleanupRuleAnalyzer(), ConfGetNode(), DetectEngineCtx_::config_prefix, ConfNodeIsSequence(), DetectLoadCompleteSigPath(), DetectParseDupSigHashFree(), DetectEngineCtx_::failure_fatal, SigFileLoaderStat_::good_sigs_total, next, RUNMODE_ENGINE_ANALYSIS, RunmodeGetCurrent(), SC_ERR_INVALID_ARGUMENT, SC_ERR_NO_RULES, SC_ERR_NO_RULES_LOADED, SCEnter, SCFree, SCLogError, SCLogInfo, SCLogWarning, SCReturnInt, SCSigOrderSignatures(), SCSigRegisterSignatureOrderingFuncs(), SCSigSignatureOrderingModuleCleanup(), SetupFPAnalyzer(), SetupRuleAnalyzer(), SigGroupBuild(), TAILQ_FOREACH, SigFileLoaderStat_::total_files, TRUE, ConfNode_::val, and ptxdump::varname.
Referenced by DetectEngineReload().
SigMatch* SigMatchAlloc (void)
Definition at line 240 of file detect-parse.c.
int SigMatchSignatures (ThreadVars * th_v, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Packet * p)
Signature match function.
Return values
1 one or more signatures matched
0 no matches were found
Definition at line 1232 of file detect.c.
References Signature_::action, ACTION_DROP, Signature_::addr_dst_match4, Signature_::addr_dst_match4_cnt, Signature_::addr_dst_match6, Signature_::addr_dst_match6_cnt, Signature_::addr_src_match4, Signature_::addr_src_match4_cnt, Signature_::addr_src_match6, Signature_::addr_src_match6_cnt, Packet_::alerts, Flow_::alparser, Flow_::alproto, Signature_::alproto, ALPROTO_DCERPC, ALPROTO_SMB, ALPROTO_SMB2, ALPROTO_UNKNOWN, Flow_::alstate, AppLayerParserGetStateVersion(), AppLayerParserHasDecoderEvents(), AppLayerParserProtocolSupportsTxs(), PacketAlerts_::cnt, DetectEngineThreadCtx_::counter_alerts, DetectEngineThreadCtx_::counter_fnonmpm_list, DetectEngineThreadCtx_::counter_match_list, DetectEngineThreadCtx_::counter_mpm_list, DetectEngineThreadCtx_::counter_nonmpm_list, SigMatchData_::ctx, StreamMsg_::data, StreamMsg_::data_len, Flow_::de_ctx_id, Flow_::de_state, DE_STATE_MATCH_NO_NEW_STATE, DetectEngineThreadCtx_::de_state_sig_array, DetectEngineThreadCtx_::de_state_sig_array_len, debuglog_enabled, DeStateDetectContinueDetection(), DeStateDetectStartDetection(), DeStateFlowHasInspectableState(), DeStateUpdateInspectTransactionId(), DETECT_ENGINE_THREAD_CTX_STREAM_CONTENT_MATCH, DETECT_PROTO_IPV4, DETECT_PROTO_IPV6, DETECT_SM_LIST_AMATCH, DETECT_SM_LIST_DMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_MATCH, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectAddressMatchIPv4(), DetectAddressMatchIPv6(), DetectEngineCleanHCBDBuffers(), DetectEngineCleanHHDBuffers(), DetectEngineCleanHSBDBuffers(), DetectEngineInspectPacketPayload(), DetectEngineInspectStreamPayload(), DetectEngineStateReset(), DetectEngineStateResetTxs(), DetectPortLookupGroup(), DetectProtoContainsProto(), DetectSignatureApplyActions(), Packet_::dp, Signature_::dp, Signature_::dsize_high, Signature_::dsize_low, Packet_::dst, FileDisableFilesize(), FileDisableMagic(), FileDisableMd5(), FileDisableStoring(), FileForceMagic(), FileForceMd5(), DetectEngineThreadCtx_::filestore_cnt, SigGroupHead_::filestore_cnt, DetectProto_::flags, Flow_::flags, Signature_::flags, Packet_::flags, DetectEngineThreadCtx_::flags, SigGroupHead_::flags, Packet_::flow, FLOW_ACTION_DROP, FLOW_PKT_ESTABLISHED, FLOW_PKT_TOCLIENT, FLOW_PKT_TOCLIENT_IPONLY_SET, FLOW_PKT_TOSERVER, FLOW_PKT_TOSERVER_IPONLY_SET, FLOW_SGH_TOCLIENT, FLOW_SGH_TOSERVER, FLOW_TOCLIENT_IPONLY_SET, FLOW_TOSERVER_IPONLY_SET, Packet_::flowflags, FlowGetAppProtocol(), FlowGetAppState(), FlowGetDisruptionFlags(), FLOWLOCK_RDLOCK, FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, FlowSetIPOnlyFlag(), Flow_::flowvar, GenericVarFree(), Signature_::id, DetectEngineCtx_::id, DetectEngineCtx_::io_ctx, DetectEngineThreadCtx_::io_ctx, IP_GET_IPPROTO, IPOnlyMatchPacket(), SigMatchData_::is_last, KEYWORD_PROFILING_END, KEYWORD_PROFILING_SET_LIST, KEYWORD_PROFILING_START, likely, m, Flow_::m, SigTableElmt_::Match, DetectEngineThreadCtx_::match_array, DetectEngineThreadCtx_::match_array_cnt, Signature_::mpm_pattern_id_div_8, Signature_::mpm_pattern_id_mod_8, StreamMsg_::next, next, DetectEngineThreadCtx_::non_mpm_id_cnt, SigGroupHead_::non_mpm_store_cnt, Signature_::num, PACKET_ALERT_FLAG_DROP_FLOW, PACKET_ALERT_FLAG_STATE_MATCH, PACKET_ALERT_FLAG_STREAM_MATCH, PACKET_DROP, PACKET_PROFILING_DETECT_END, PACKET_PROFILING_DETECT_START, PacketAlertAppend(), PacketAlertFinalize(), PacketPatternCleanup(), PatternMatcherQueue_::pattern_id_bitarray, Packet_::payload_len, Packet_::pcap_cnt, PKT_HAS_FLOW, PKT_IS_FRAGMENT, PKT_IS_IPV4, PKT_IS_IPV6, PKT_NOPACKET_INSPECTION, PKT_STREAM_ADD, PKT_STREAM_EOF, PKT_STREAM_EST, DetectEngineThreadCtx_::pmq, PrintRawDataFp(), PROF_DETECT_ALERT, PROF_DETECT_CLEANUP, PROF_DETECT_GETSGH, PROF_DETECT_IPONLY, PROF_DETECT_MPM, PROF_DETECT_NONMPMLIST, PROF_DETECT_PREFILTER, PROF_DETECT_RULES, PROF_DETECT_STATEFUL, Flow_::proto, Packet_::proto, Signature_::proto, PatternMatcherQueue_::rule_id_array_cnt, RULE_PROFILING_END, RULE_PROFILING_START, SCEnter, SCLogDebug, SCMutexLock, SCMutexUnlock, SCReturnInt, DetectEngineThreadCtx_::sgh, Flow_::sgh_toclient, Flow_::sgh_toserver, SIG_FLAG_APPLAYER, SIG_FLAG_DP_ANY, SIG_FLAG_DSIZE, SIG_FLAG_DST_ANY, SIG_FLAG_MPM_APPLAYER, SIG_FLAG_MPM_APPLAYER_NEG, SIG_FLAG_MPM_PACKET, SIG_FLAG_MPM_PACKET_NEG, SIG_FLAG_MPM_STREAM, SIG_FLAG_MPM_STREAM_NEG, SIG_FLAG_NOALERT, SIG_FLAG_REQUIRE_FLOWVAR, SIG_FLAG_REQUIRE_PACKET, SIG_FLAG_REQUIRE_STREAM, SIG_FLAG_SP_ANY, SIG_FLAG_SRC_ANY, SIG_FLAG_STATE_MATCH, SIG_GROUP_HEAD_HAVEFILEMAGIC, SIG_GROUP_HEAD_HAVEFILEMD5, SIG_GROUP_HEAD_HAVEFILESIZE, SigIntId, sigmatch_table, SigMatchSignaturesGetSgh(), SigMatchSignaturesRunPostMatch(), SignatureMask, Signature_::sm_arrays, Signature_::sm_lists, SMS_USE_FLOW_SGH, SMS_USED_PM, SMS_USED_STREAM_PM, DetectEngineThreadCtx_::smsg_pmq, Packet_::sp, Signature_::sp, Packet_::src, StatsAddUI64(), STREAM_EOF, STREAM_TOCLIENT, STREAM_TOSERVER, StreamMsgReturnListToPool(), StreamPatternCleanup(), Flow_::tenant_id, Packet_::tenant_id, SigMatchData_::type, and unlikely.
Referenced by Detect().
SigGroupHead* SigMatchSignaturesGetSgh (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Packet * p)
Get the SigGroupHead for a packet.
Parameters
de_ctx detection engine context
det_ctx thread detection engine content
p packet
Return values
sgh the SigGroupHead or NULL if non applies to the packet
Definition at line 595 of file detect.c.
References PacketEngineEvents_::cnt, DetectEngineCtx_::decoder_event_sgh, DetectAddressLookupInHead(), DetectPortLookupGroup(), Packet_::dp, Packet_::dst, DetectAddress_::dst_gh, DetectPort_::dst_ph, Packet_::events, DetectEngineCtx_::flow_gh, FLOW_PKT_TOCLIENT, Packet_::flowflags, IP_GET_IPPROTO, DetectAddress_::port, Packet_::proto, SCEnter, SCLogDebug, SCReturnPtr, DetectAddress_::sh, DetectPort_::sh, Packet_::sp, Packet_::src, and DetectEngineLookupFlow_::src_gh.
Referenced by SigMatchSignatures().
int SigMatchSignaturesRunPostMatch (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s)
Definition at line 555 of file detect.c.
References SigMatchData_::ctx, DETECT_SM_LIST_POSTMATCH, DetectFilestorePostMatch(), Signature_::flags, SigMatchData_::is_last, KEYWORD_PROFILING_END, KEYWORD_PROFILING_SET_LIST, KEYWORD_PROFILING_START, SigTableElmt_::Match, SCLogDebug, SIG_FLAG_FILESTORE, sigmatch_table, Signature_::sm_arrays, and SigMatchData_::type.
Referenced by SigMatchSignatures().
int SignatureIsAppLayer (DetectEngineCtx * de_ctx, Signature * s)
Definition at line 2089 of file detect.c.
References Signature_::alproto.
int SignatureIsFilemagicInspecting (Signature * s)
Check if a signature contains the filemagic keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 2124 of file detect.c.
References Signature_::file_flags, and FILE_SIG_NEED_MAGIC.
Referenced by SigGroupHeadSetFilemagicFlag().
int SignatureIsFileMd5Inspecting (Signature * s)
Check if a signature contains the filemd5 keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 2143 of file detect.c.
References Signature_::file_flags, and FILE_SIG_NEED_MD5.
Referenced by SigGroupHeadSetFileMd5Flag().
int SignatureIsFilesizeInspecting (Signature * s)
Check if a signature contains the filesize keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 2162 of file detect.c.
References Signature_::file_flags, and FILE_SIG_NEED_SIZE.
Referenced by SigGroupHeadSetFilesizeFlag().
int SignatureIsFilestoring (Signature * s)
Check if a signature contains the filestore keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 2105 of file detect.c.
References Signature_::flags, and SIG_FLAG_FILESTORE.
Referenced by SigGroupHeadSetFilestoreCount().
int SignatureIsIPOnly (DetectEngineCtx * de_ctx, Signature * s)
Test is a initialized signature is IP only.
Parameters
de_ctx detection engine ctx
s the signature
Return values
1 sig is ip only
0 sig is not ip only
Definition at line 2179 of file detect.c.
References Signature_::alproto, ALPROTO_UNKNOWN, Signature_::CidrDst, Signature_::CidrSrc, SigMatch_::ctx, DE_QUIET, DETECT_FLOWBITS, DETECT_FLOWBITS_CMD_SET, DETECT_SM_LIST_AMATCH, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_MATCH, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, Signature_::flags, DetectEngineCtx_::flags, SigTableElmt_::flags, Signature_::id, IPOnlyCIDRItem_::negated, IPOnlyCIDRItem_::next, SigMatch_::next, SCLogDebug, SIG_FLAG_DST_ANY, SIG_FLAG_SRC_ANY, SIGMATCH_IPONLY_COMPAT, sigmatch_table, Signature_::sm_lists, and SigMatch_::type.
Referenced by SigAddressPrepareStage1().
void SigRegisterTests (void)
Definition at line 12117 of file detect.c.
References DetectSimdRegisterTests(), IPOnlyRegisterTests(), and SigParseRegisterTests().
Referenced by TmModuleDetectRegister().
void SigTableList (const char * keyword)
Definition at line 4970 of file detect.c.
References AppLayerGetProtoName(), SIGMATCH_NOT_BUILT, and sigmatch_table.
Referenced by ListKeywords().
void SigTableRegisterTests (void)
Definition at line 5137 of file detect.c.
References coverage_unittests, DETECT_TBLSIZE, g_ut_covered, g_ut_modules, SigTableElmt_::RegisterTests, SC_WARN_NO_UNITTESTS, SCLogDebug, SCLogWarning, and sigmatch_table.
Referenced by RunUnittests().
void SigTableSetup (void)
Definition at line 5032 of file detect.c.
References DetectAckRegister(), DetectAppLayerEventRegister(), DetectAppLayerProtocolRegister(), DetectAsn1Register(), DetectByteExtractRegister(), DetectBytejumpRegister(), DetectBytetestRegister(), DetectClasstypeRegister(), DetectContentRegister(), DetectCsumRegister(), DetectDceIfaceRegister(), DetectDceOpnumRegister(), DetectDceStubDataRegister(), DetectDepthRegister(), DetectDetectionFilterRegister(), DetectDistanceRegister(), DetectDnsQueryRegister(), DetectDsizeRegister(), DetectEngineEventRegister(), DetectFastPatternRegister(), DetectFiledataRegister(), DetectFileextRegister(), DetectFilemagicRegister(), DetectFileMd5Register(), DetectFilenameRegister(), DetectFilesizeRegister(), DetectFilestoreRegister(), DetectFlagsRegister(), DetectFlowbitsRegister(), DetectFlowintRegister(), DetectFlowRegister(), DetectFlowvarRegister(), DetectFragBitsRegister(), DetectFragOffsetRegister(), DetectFtpbounceRegister(), DetectGeoipRegister(), DetectGidRegister(), DetectHostbitsRegister(), DetectHttpClientBodyRegister(), DetectHttpCookieRegister(), DetectHttpHeaderRegister(), DetectHttpHHRegister(), DetectHttpHRHRegister(), DetectHttpMethodRegister(), DetectHttpRawHeaderRegister(), DetectHttpRawUriRegister(), DetectHttpServerBodyRegister(), DetectHttpStatCodeRegister(), DetectHttpStatMsgRegister(), DetectHttpUARegister(), DetectHttpUriRegister(), DetectIcmpIdRegister(), DetectIcmpSeqRegister(), DetectICodeRegister(), DetectIdRegister(), DetectIpOptsRegister(), DetectIPProtoRegister(), DetectIPRepRegister(), DetectIsdataatRegister(), DetectITypeRegister(), DetectL3ProtoRegister(), DetectLuaRegister(), DetectMarkRegister(), DetectMetadataRegister(), DetectModbusRegister(), DetectMsgRegister(), DetectNoalertRegister(), DetectNocaseRegister(), DetectOffsetRegister(), DetectPcreRegister(), DetectPktDataRegister(), DetectPktvarRegister(), DetectPriorityRegister(), DetectRawbytesRegister(), DetectReferenceRegister(), DetectReplaceRegister(), DetectRevRegister(), DetectRpcRegister(), DetectSameipRegister(), DetectSeqRegister(), DetectSidRegister(), DetectSshSoftwareVersionRegister(), DetectSshVersionRegister(), DetectSslStateRegister(), DetectSslVersionRegister(), DetectStreamSizeRegister(), DetectTagRegister(), DetectTemplateBufferRegister(), DetectTemplateRegister(), DetectThresholdRegister(), DetectTlsRegister(), DetectTlsVersionRegister(), DetectTosRegister(), DetectTtlRegister(), DetectUricontentRegister(), DetectUrilenRegister(), DetectWindowRegister(), DetectWithinRegister(), DetectXbitsRegister(), and sigmatch_table.
Referenced by ListKeywords(), and RunUnittests().
void TmModuleDetectRegister (void)
Definition at line 225 of file detect.c.
References TmModule_::cap_flags, Detect(), DetectExitPrintStats(), DetectThreadDeinit(), DetectThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, PacketAlertTagInit(), TmModule_::RegisterTests, SigRegisterTests(), TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DETECT_TM, TMM_DETECT, and tmm_modules.
Referenced by RegisterAllModules().
Variable Documentation
int engine_analysis
int rule_reload