suricata: src/detect-ssh-proto-version.c File Reference
detect-ssh-proto-version.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-ssh.h"
#include "detect-ssh-proto-version.h"
#include "stream-tcp.h"
Macros
#define PARSE_REGEX "^\\s*\"?\\s*([0-9]+([\\.\\-0-9]+)?|2_compat)\\s*\"?\\s*$"
Regex for parsing the protoversion string.
#define MAX_SUBSTRINGS 30
Functions
int DetectSshVersionMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Flow *f, uint8_t flags, void *state, Signature *s, SigMatch *m)
match the specified version on a ssh session
void DetectSshVersionRegisterTests (void)
this function registers unit tests for DetectSshVersion
void DetectSshVersionFree (void *ptr)
this function will free memory associated with DetectSshVersionData
void DetectSshVersionRegister (void)
Registration function for keyword: ssh.protoversion.
DetectSshVersionData * DetectSshVersionParse (char *str)
This function is used to parse IPV4 ip_id passed via keyword: "id".
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements the ssh.protoversion keyword You can specify a concrete version like ssh.protoversion: 1.66 or search for protoversion 2 compat (1.99 is considered as 2) like ssh.protoversion:2_compat or just the beginning of the string like ssh.protoversion:"1."
Definition in file detect-ssh-proto-version.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectSshVersionParse().
#define PARSE_REGEX "^\\s*\"?\\s*([0-9]+([\\.\\-0-9]+)?|2_compat)\\s*\"?\\s*$"
Regex for parsing the protoversion string.
Definition at line 60 of file detect-ssh-proto-version.c.
Referenced by DetectSshVersionRegister().
Function Documentation
void DetectSshVersionFree (void * ptr)
this function will free memory associated with DetectSshVersionData
Parameters
id_d pointer to DetectSshVersionData
Definition at line 274 of file detect-ssh-proto-version.c.
References SCFree.
Referenced by DetectSshVersionParse(), and DetectSshVersionRegister().
int DetectSshVersionMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Flow * f, uint8_t flags, void * state, Signature * s, SigMatch * m)
match the specified version on a ssh session
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectSshVersionData
Return values
0 no match
1 match
Definition at line 118 of file detect-ssh-proto-version.c.
References SigMatch_::ctx, DetectSshVersionData_::flags, DetectSshVersionData_::len, SCEnter, SCLogDebug, SCReturnInt, SSH_FLAG_PROTOVERSION_2_COMPAT, SSH_FLAG_VERSION_PARSED, STREAM_TOCLIENT, STREAM_TOSERVER, and DetectSshVersionData_::ver.
Referenced by DetectSshVersionRegister().
DetectSshVersionData* DetectSshVersionParse (char * str)
This function is used to parse IPV4 ip_id passed via keyword: "id".
Parameters
idstr Pointer to the user provided id option
Return values
id_d pointer to DetectSshVersionData on success
NULL on failure
Definition at line 164 of file detect-ssh-proto-version.c.
References DetectSshVersionFree(), DetectSshVersionData_::flags, DetectSshVersionData_::len, MAX_SUBSTRINGS, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCLogDebug, SCLogError, SCMalloc, SCStrdup, SSH_FLAG_PROTOVERSION_2_COMPAT, unlikely, and DetectSshVersionData_::ver.
void DetectSshVersionRegister (void)
Registration function for keyword: ssh.protoversion.
Definition at line 73 of file detect-ssh-proto-version.c.
References SigTableElmt_::alproto, ALPROTO_SSH, SigTableElmt_::AppLayerMatch, DETECT_AL_SSH_PROTOVERSION, DetectSshVersionFree(), DetectSshVersionMatch(), DetectSshVersionRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void DetectSshVersionRegisterTests (void)
this function registers unit tests for DetectSshVersion
Definition at line 689 of file detect-ssh-proto-version.c.
Referenced by DetectSshVersionRegister().