suricata: src/detect-itype.c File Reference
detect-itype.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-itype.h"
#include "util-byte.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^\\s*(<|>)?\\s*([0-9]+)\\s*(?:<>\\s*([0-9]+))?\\s*$"
Regex for parsing our itype options.
#define MAX_SUBSTRINGS 30
Functions
int DetectITypeMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match itype rule option set on a packet with those passed via itype:
void DetectITypeRegisterTests (void)
this function registers unit tests for DetectIType
void DetectITypeFree (void *ptr)
this function will free memory associated with DetectITypeData
void DetectITypeRegister (void)
Registration function for itype: keyword.
DetectITypeData * DetectITypeParse (char *itypestr)
This function is used to parse itype options passed via itype: keyword.
Detailed Description
Author
Gerardo Iglesias igles.nosp@m.iasg.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Implements itype keyword support
Definition in file detect-itype.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectITypeParse().
#define PARSE_REGEX "^\\s*(<|>)?\\s*([0-9]+)\\s*(?:<>\\s*([0-9]+))?\\s*$"
Regex for parsing our itype options.
Definition at line 43 of file detect-itype.c.
Referenced by DetectITypeRegister().
Function Documentation
void DetectITypeFree (void * ptr)
this function will free memory associated with DetectITypeData
Parameters
ptr pointer to DetectITypeData
Definition at line 280 of file detect-itype.c.
References SCFree.
Referenced by DetectITypeParse(), and DetectITypeRegister().
int DetectITypeMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match itype rule option set on a packet with those passed via itype:
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectITypeData
Return values
0 no match
1 match
Definition at line 101 of file detect-itype.c.
References DETECT_ITYPE_EQ, DETECT_ITYPE_GT, DETECT_ITYPE_LT, DETECT_ITYPE_RN, ICMPV4_GET_TYPE, ICMPV6_GET_TYPE, DetectITypeData_::mode, PKT_IS_ICMPV4, PKT_IS_ICMPV6, PKT_IS_PSEUDOPKT, DetectITypeData_::type1, and DetectITypeData_::type2.
Referenced by DetectITypeRegister().
DetectITypeData* DetectITypeParse (char * itypestr)
This function is used to parse itype options passed via itype: keyword.
Parameters
itypestr Pointer to the user provided itype options
Return values
itd pointer to DetectITypeData on success
NULL on failure
Definition at line 145 of file detect-itype.c.
References ByteExtractStringUint8(), DETECT_ITYPE_EQ, DETECT_ITYPE_GT, DETECT_ITYPE_LT, DETECT_ITYPE_RN, DetectITypeFree(), MAX_SUBSTRINGS, DetectITypeData_::mode, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogError, SCMalloc, DetectITypeData_::type1, DetectITypeData_::type2, and unlikely.
void DetectITypeRegister (void)
Registration function for itype: keyword.
Definition at line 57 of file detect-itype.c.
References SigTableElmt_::desc, DETECT_ITYPE, DetectITypeFree(), DetectITypeMatch(), DetectITypeRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectITypeRegisterTests (void)
this function registers unit tests for DetectIType
Definition at line 516 of file detect-itype.c.
Referenced by DetectITypeRegister().