suricata: src/detect-distance.c File Reference
detect-distance.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "app-layer.h"
#include "detect-content.h"
#include "detect-uricontent.h"
#include "detect-pcre.h"
#include "detect-byte-extract.h"
#include "flow-var.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "detect-bytejump.h"
#include "util-unittest-helper.h"
Functions
void DetectDistanceRegisterTests (void)
void DetectDistanceRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements the distance keyword
Definition in file detect-distance.c.
Function Documentation
void DetectDistanceRegister (void)
Definition at line 52 of file detect-distance.c.
References SigTableElmt_::desc, DETECT_DISTANCE, DetectDistanceRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectDistanceRegisterTests (void)
Definition at line 263 of file detect-distance.c.
Referenced by DetectDistanceRegister().