suricata: src/detect-filestore.h File Reference
detect-filestore.h File Reference
Data Structures
struct DetectFilestoreData_
Macros
#define FILESTORE_DIR_DEFAULT 0 /* rule dir */
#define FILESTORE_DIR_TOSERVER 1
#define FILESTORE_DIR_TOCLIENT 2
#define FILESTORE_DIR_BOTH 3
#define FILESTORE_SCOPE_DEFAULT 0 /* per file */
#define FILESTORE_SCOPE_TX 1 /* per transaction */
#define FILESTORE_SCOPE_SSN 2 /* per flow/ssn */
Typedefs
typedef struct DetectFilestoreData_ DetectFilestoreData
Functions
void DetectFilestoreRegister (void)
Registration function for keyword: filestore.
int DetectFilestorePostMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *)
post-match function for filestore
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-filestore.h.
Macro Definition Documentation
#define FILESTORE_DIR_BOTH 3
Definition at line 30 of file detect-filestore.h.
#define FILESTORE_DIR_DEFAULT 0 /* rule dir */
Definition at line 27 of file detect-filestore.h.
#define FILESTORE_DIR_TOCLIENT 2
Definition at line 29 of file detect-filestore.h.
#define FILESTORE_DIR_TOSERVER 1
Definition at line 28 of file detect-filestore.h.
#define FILESTORE_SCOPE_DEFAULT 0 /* per file */
Definition at line 32 of file detect-filestore.h.
#define FILESTORE_SCOPE_SSN 2 /* per flow/ssn */
Definition at line 34 of file detect-filestore.h.
#define FILESTORE_SCOPE_TX 1 /* per transaction */
Definition at line 33 of file detect-filestore.h.
Typedef Documentation
typedef struct DetectFilestoreData_ DetectFilestoreData
Function Documentation
int DetectFilestorePostMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s)
post-match function for filestore
Parameters
t thread local vars
det_ctx pattern matcher thread local data
p packet
The match function for filestore records store candidates in the det_ctx. When we are sure all parts of the signature matched, we run this function to finalize the filestore.
Definition at line 204 of file detect-filestore.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), BUG_ON, SigMatch_::ctx, DetectEngineThreadCtx_::file_id, DetectEngineThreadCtx_::filestore, DetectEngineThreadCtx_::filestore_cnt, Signature_::filestore_sm, FileStoreFileById(), flags, Packet_::flow, DetectEngineThreadCtx_::flow_locked, FLOW_PKT_TOCLIENT, Packet_::flowflags, FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, Flow_::proto, SCEnter, SCReturnInt, STREAM_TOCLIENT, STREAM_TOSERVER, and DetectEngineThreadCtx_::tx_id.
Referenced by SigMatchSignaturesRunPostMatch().
void DetectFilestoreRegister (void)
Registration function for keyword: filestore.
Definition at line 70 of file detect-filestore.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::desc, DETECT_FILESTORE, SigTableElmt_::FileMatch, SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, SIGMATCH_OPTIONAL_OPT, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().