suricata: src/detect-dce-opnum.c File Reference
detect-dce-opnum.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "app-layer.h"
#include "app-layer-dcerpc.h"
#include "queue.h"
#include "stream-tcp-reassemble.h"
#include "detect-dce-opnum.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "stream-tcp.h"
Macros
#define DETECT_DCE_OPNUM_PCRE_PARSE_ARGS "^\\s*([0-9]{1,5}(\\s*-\\s*[0-9]{1,5}\\s*)?)(,\\s*[0-9]{1,5}(\\s*-\\s*[0-9]{1,5})?\\s*)*$"
#define MAX_SUBSTRINGS 30
Functions
int DetectDceOpnumMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Flow *f, uint8_t flags, void *state, Signature *s, SigMatch *m)
App layer match function for the "dce_opnum" keyword.
void DetectDceOpnumFree (void *)
void DetectDceOpnumRegister (void)
Registers the keyword handlers for the "dce_opnum" keyword.
void DetectDceOpnumRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements dce_opnum keyword
Definition in file detect-dce-opnum.c.
Macro Definition Documentation
#define DETECT_DCE_OPNUM_PCRE_PARSE_ARGS "^\\s*([0-9]{1,5}(\\s*-\\s*[0-9]{1,5}\\s*)?)(,\\s*[0-9]{1,5}(\\s*-\\s*[0-9]{1,5})?\\s*)*$"
Definition at line 50 of file detect-dce-opnum.c.
Referenced by DetectDceOpnumRegister().
#define MAX_SUBSTRINGS 30
Function Documentation
void DetectDceOpnumFree (void * ptr)
Definition at line 350 of file detect-dce-opnum.c.
References DetectDceOpnumRange_::next, DetectDceOpnumData_::range, and SCFree.
Referenced by DetectDceOpnumRegister().
int DetectDceOpnumMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Flow * f, uint8_t flags, void * state, Signature * s, SigMatch * m)
App layer match function for the "dce_opnum" keyword.
Parameters
t Pointer to the ThreadVars instance.
det_ctx Pointer to the DetectEngineThreadCtx.
f Pointer to the flow.
flags Pointer to the flags indicating the flow direction.
state Pointer to the app layer state data.
s Pointer to the Signature instance.
m Pointer to the SigMatch.
Return values
1 On Match.
0 On no match.
Definition at line 263 of file detect-dce-opnum.c.
References SigMatch_::ctx, DCE_OPNUM_RANGE_UNINITIALIZED, DetectDceOpnumRange_::next, DetectDceOpnumData_::range, DetectDceOpnumRange_::range1, DetectDceOpnumRange_::range2, SCEnter, SCLogDebug, and SCReturnInt.
Referenced by DetectDceOpnumRegister().
void DetectDceOpnumRegister (void)
Registers the keyword handlers for the "dce_opnum" keyword.
Definition at line 63 of file detect-dce-opnum.c.
References SigTableElmt_::alproto, ALPROTO_DCERPC, SigTableElmt_::AppLayerMatch, DETECT_DCE_OPNUM, DETECT_DCE_OPNUM_PCRE_PARSE_ARGS, DetectDceOpnumFree(), DetectDceOpnumMatch(), DetectDceOpnumRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void DetectDceOpnumRegisterTests (void)
Definition at line 2926 of file detect-dce-opnum.c.
Referenced by DetectDceOpnumRegister().