suricata: src/detect-http-server-body.c File Reference
detect-http-server-body.c File Reference
HTTP layer support
#include "suricata-common.h"
#include "threads.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "detect-content.h"
#include "detect-pcre.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-spm.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "detect-http-server-body.h"
#include "stream-tcp.h"
Functions
int DetectHttpServerBodySetup (DetectEngineCtx *de_ctx, Signature *s, char *arg)
The setup function for the http_server_body keyword for a signature.
void DetectHttpServerBodyRegisterTests (void)
void DetectHttpServerBodyFree (void *ptr)
The function to free the http_server_body data.
void DetectHttpServerBodyRegister (void)
Registers the keyword handlers for the "http_server_body" keyword.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements support for the http_server_body keyword
Definition in file detect-http-server-body.c.
Function Documentation
void DetectHttpServerBodyFree (void * ptr)
The function to free the http_server_body data.
Parameters
ptr Pointer to the http_server_body.
Definition at line 120 of file detect-http-server-body.c.
References DetectContentData_::bm_ctx, BoyerMooreCtxDeInit(), DetectContentData_::content, SCEnter, SCFree, and SCReturn.
Referenced by DetectHttpServerBodyRegister().
void DetectHttpServerBodyRegister (void)
Registers the keyword handlers for the "http_server_body" keyword.
Definition at line 69 of file detect-http-server-body.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, SigTableElmt_::desc, DETECT_AL_HTTP_SERVER_BODY, DetectHttpServerBodyFree(), DetectHttpServerBodyRegisterTests(), DetectHttpServerBodySetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectHttpServerBodyRegisterTests (void)
Definition at line 3823 of file detect-http-server-body.c.
Referenced by DetectHttpServerBodyRegister().
int DetectHttpServerBodySetup (DetectEngineCtx * de_ctx, Signature * s, char * arg)
The setup function for the http_server_body keyword for a signature.
Parameters
de_ctx Pointer to the detection engine context.
s Pointer to signature for the current Signature being parsed from the rules.
m Pointer to the head of the SigMatchs for the current rule being parsed.
arg Pointer to the string holding the keyword value.
Return values
0 On success
-1 On failure
Definition at line 106 of file detect-http-server-body.c.
References ALPROTO_HTTP, DETECT_AL_HTTP_SERVER_BODY, DETECT_SM_LIST_FILEDATA, and DetectEngineContentModifierBufferSetup().
Referenced by DetectHttpServerBodyRegister().