suricata: src/detect-engine-mpm.c File Reference
detect-engine-mpm.c File Reference
#include "suricata.h"
#include "suricata-common.h"
#include "app-layer-protos.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-siggroup.h"
#include "detect-engine-mpm.h"
#include "detect-engine-iponly.h"
#include "detect-parse.h"
#include "util-mpm.h"
#include "util-memcmp.h"
#include "util-memcpy.h"
#include "conf.h"
#include "detect-fast-pattern.h"
#include "flow.h"
#include "flow-var.h"
#include "detect-flow.h"
#include "detect-content.h"
#include "detect-uricontent.h"
#include "stream.h"
#include "util-enum.h"
#include "util-debug.h"
#include "util-print.h"
#include "util-validate.h"
Data Structures
struct ContentHash_
Hash for looking up contents that are most used, always used, etc.
struct UricontentHash_
struct MpmPatternIdTableElmt_
Pattern ID Hash for sharing pattern id's.
struct DetectFPAndItsId_
Macros
#define POPULATE_MPM_AVOID_PACKET_MPM_PATTERNS 0x01
#define POPULATE_MPM_AVOID_STREAM_MPM_PATTERNS 0x02
#define POPULATE_MPM_AVOID_URI_MPM_PATTERNS 0x04
Typedefs
typedef struct ContentHash_ ContentHash
Hash for looking up contents that are most used, always used, etc.
typedef struct UricontentHash_ UricontentHash
typedef struct
MpmPatternIdTableElmt_ MpmPatternIdTableElmt
Pattern ID Hash for sharing pattern id's.
typedef struct DetectFPAndItsId_ DetectFPAndItsId
Functions
int SignatureHasPacketContent (Signature *s)
check if a signature has patterns that are to be inspected against a packets payload (as opposed to the stream payload)
int SignatureHasStreamContent (Signature *s)
check if a signature has patterns that are to be inspected against the stream payload (as opposed to the individual packets payload(s))
uint16_t PatternMatchDefaultMatcher (void)
Function to return the multi pattern matcher algorithm to be used by the engine, based on the mpm-algo setting in yaml Use the default mpm if none is specified in the yaml file.
uint32_t PacketPatternSearchWithStreamCtx (DetectEngineThreadCtx *det_ctx, Packet *p)
uint32_t PacketPatternSearch (DetectEngineThreadCtx *det_ctx, Packet *p)
Pattern match – searches for only one pattern per signature.
uint32_t UriPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *uri, uint16_t uri_len, uint8_t flags)
Uri Pattern match – searches for one pattern per signature.
uint32_t HttpClientBodyPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *body, uint32_t body_len, uint8_t flags)
Http client body pattern match – searches for one pattern per signature.
uint32_t HttpServerBodyPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *body, uint32_t body_len, uint8_t flags)
Http server body pattern match – searches for one pattern per signature.
uint32_t HttpHeaderPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *headers, uint32_t headers_len, uint8_t flags)
Http header match – searches for one pattern per signature.
uint32_t HttpRawHeaderPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *raw_headers, uint32_t raw_headers_len, uint8_t flags)
Http raw header match – searches for one pattern per signature.
uint32_t HttpMethodPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *raw_method, uint32_t raw_method_len, uint8_t flags)
Http method match – searches for one pattern per signature.
uint32_t HttpCookiePatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *cookie, uint32_t cookie_len, uint8_t flags)
Http cookie match – searches for one pattern per signature.
uint32_t HttpRawUriPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *uri, uint32_t uri_len, uint8_t flags)
Http raw uri match – searches for one pattern per signature.
uint32_t HttpStatMsgPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *stat_msg, uint32_t stat_msg_len, uint8_t flags)
Http stat msg match – searches for one pattern per signature.
uint32_t HttpStatCodePatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *stat_code, uint32_t stat_code_len, uint8_t flags)
Http stat code match – searches for one pattern per signature.
uint32_t HttpUAPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *ua, uint32_t ua_len, uint8_t flags)
Http user agent match – searches for one pattern per signature.
uint32_t HttpHHPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *hh, uint32_t hh_len, uint8_t flags)
Http host header match – searches for one pattern per signature.
uint32_t HttpHRHPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *hrh, uint32_t hrh_len, uint8_t flags)
Http raw host header match – searches for one pattern per signature.
uint32_t DnsQueryPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *buffer, uint32_t buffer_len, uint8_t flags)
DNS query match – searches for one pattern per signature.
uint32_t StreamPatternSearch (DetectEngineThreadCtx *det_ctx, Packet *p, StreamMsg *smsg, uint8_t flags)
Pattern match – searches for only one pattern per signature.
uint32_t SMTPFiledataPatternSearch (DetectEngineThreadCtx *det_ctx, uint8_t *buffer, uint32_t buffer_len, uint8_t flags)
SMTP Filedata match – searches for one pattern per signature.
void PacketPatternCleanup (ThreadVars *t, DetectEngineThreadCtx *det_ctx)
cleans up the mpm instance after a match
void StreamPatternCleanup (ThreadVars *t, DetectEngineThreadCtx *det_ctx, StreamMsg *smsg)
void PatternMatchDestroy (MpmCtx *mpm_ctx, uint16_t mpm_matcher)
void PatternMatchPrepare (MpmCtx *mpm_ctx, uint16_t mpm_matcher)
void PatternMatchThreadPrint (MpmThreadCtx *mpm_thread_ctx, uint16_t mpm_matcher)
void PatternMatchThreadDestroy (MpmThreadCtx *mpm_thread_ctx, uint16_t mpm_matcher)
void PatternMatchThreadPrepare (MpmThreadCtx *mpm_thread_ctx, uint16_t mpm_matcher, uint32_t max_id)
void PatternMatchDestroyGroup (SigGroupHead *sh)
uint32_t ContentHashFunc (HashTable *ht, void *data, uint16_t datalen)
uint32_t UricontentHashFunc (HashTable *ht, void *data, uint16_t datalen)
char ContentHashCompareFunc (void *data1, uint16_t len1, void *data2, uint16_t len2)
char UricontentHashCompareFunc (void *data1, uint16_t len1, void *data2, uint16_t len2)
ContentHash * ContentHashAlloc (DetectContentData *ptr)
UricontentHash * UricontentHashAlloc (DetectContentData *ptr)
void ContentHashFree (void *ch)
void UricontentHashFree (void *ch)
uint32_t PatternStrength (uint8_t *pat, uint16_t patlen)
Predict a strength value for patterns.
SigMatch * RetrieveFPForSig (Signature *s)
SigMatch * RetrieveFPForSigV2 (Signature *s)
int PatternMatchPrepareGroup (DetectEngineCtx *de_ctx, SigGroupHead *sh)
Prepare the pattern matcher ctx in a sig group head.
MpmPatternIdStore * MpmPatternIdTableInitHash (void)
alloc initialize the MpmPatternIdHash
void MpmPatternIdTableFreeHash (MpmPatternIdStore *ht)
uint32_t MpmPatternIdStoreGetMaxId (MpmPatternIdStore *ht)
uint32_t DetectContentGetId (MpmPatternIdStore *ht, DetectContentData *co)
Get the pattern id for a content pattern.
int DetectSetFastPatternAndItsId (DetectEngineCtx *de_ctx)
Figured out the FP and their respective content ids for all the sigs in the engine.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Multi pattern matcher
Definition in file detect-engine-mpm.c.
Macro Definition Documentation
#define POPULATE_MPM_AVOID_PACKET_MPM_PATTERNS 0x01
Todo:
make it possible to use multiple pattern matcher algorithms next to each other.
Definition at line 66 of file detect-engine-mpm.c.
#define POPULATE_MPM_AVOID_STREAM_MPM_PATTERNS 0x02
Definition at line 67 of file detect-engine-mpm.c.
#define POPULATE_MPM_AVOID_URI_MPM_PATTERNS 0x04
Definition at line 68 of file detect-engine-mpm.c.
Typedef Documentation
typedef struct ContentHash_ ContentHash
Hash for looking up contents that are most used, always used, etc.
typedef struct DetectFPAndItsId_ DetectFPAndItsId
typedef struct MpmPatternIdTableElmt_ MpmPatternIdTableElmt
Pattern ID Hash for sharing pattern id's.
A per detection engine hash to make sure each pattern has a unique global id but patterns that are the same share id's.
typedef struct UricontentHash_ UricontentHash
Function Documentation
ContentHash* ContentHashAlloc (DetectContentData * ptr)
Definition at line 1135 of file detect-engine-mpm.c.
References ContentHash_::cnt, ContentHash_::ptr, SCMalloc, unlikely, and ContentHash_::use.
char ContentHashCompareFunc (void * data1, uint16_t len1, void * data2, uint16_t len2)
Definition at line 1105 of file detect-engine-mpm.c.
References DetectContentData_::content, DetectContentData_::content_len, DETECT_CONTENT_NOCASE, DetectContentData_::flags, ContentHash_::ptr, and SCMemcmp.
void ContentHashFree (void * ch)
Definition at line 1161 of file detect-engine-mpm.c.
References SCFree.
uint32_t ContentHashFunc (HashTable * ht, void * data, uint16_t datalen)
Definition at line 1077 of file detect-engine-mpm.c.
References HashTable_::array_size, DetectContentData_::content, DetectContentData_::content_len, ContentHash_::ptr, and SCLogDebug.
uint32_t DetectContentGetId (MpmPatternIdStore * ht, DetectContentData * co)
Get the pattern id for a content pattern.
Parameters
ht mpm pattern id hash table store
co content pattern data
Return values
id pattern id
Definition at line 2824 of file detect-engine-mpm.c.
References BUG_ON, DetectContentData_::content, DetectContentData_::content_len, MpmPatternIdStore_::hash, HashTableAdd(), HashTableLookup(), MpmPatternIdTableElmt_::id, MpmPatternIdStore_::max_id, MpmPatternIdTableElmt_::pattern, MpmPatternIdTableElmt_::pattern_len, SCEnter, SCMalloc, SCReturnUInt, MpmPatternIdStore_::shared_patterns, and MpmPatternIdStore_::unique_patterns.
int DetectSetFastPatternAndItsId (DetectEngineCtx * de_ctx)
Figured out the FP and their respective content ids for all the sigs in the engine.
Parameters
de_ctx Detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 2885 of file detect-engine-mpm.c.
References BUG_ON, DetectContentData_::content, DetectFPAndItsId_::content, DetectContentData_::content_len, DetectFPAndItsId_::content_len, SigMatch_::ctx, DETECT_CONTENT_FAST_PATTERN_CHOP, DETECT_CONTENT_NOCASE, flags, DetectContentData_::flags, DetectFPAndItsId_::flags, DetectContentData_::fp_chop_len, DetectContentData_::fp_chop_offset, DetectContentData_::id, DetectFPAndItsId_::id, DetectEngineCtx_::max_fp_id, Signature_::mpm_sm, Signature_::next, PatIntId, RetrieveFPForSigV2(), SCFree, SCMalloc, SCMemcmp, DetectEngineCtx_::sig_list, SigMatchListSMBelongsTo(), DetectFPAndItsId_::sm_list, and unlikely.
Referenced by SigGroupBuild().
uint32_t DnsQueryPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * buffer, uint32_t buffer_len, uint8_t flags)
DNS query match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
hrh Buffer to inspect.
hrh_len buffer length.
flags Flags
Return values
ret Number of matches.
Definition at line 625 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_dnsquery_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectDnsQueryInspectMpm().
uint32_t HttpClientBodyPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * body, uint32_t body_len, uint8_t flags)
Http client body pattern match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
body The request body to inspect.
body_len Body length.
Return values
ret Number of matches.
Definition at line 292 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hcbd_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectEngineRunHttpClientBodyMpm().
uint32_t HttpCookiePatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * cookie, uint32_t cookie_len, uint8_t flags)
Http cookie match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
cookie Cookie to inspect.
cookie_len Cookie length.
Return values
ret Number of matches.
Definition at line 434 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hcd_ctx_tc, SigGroupHead_::mpm_hcd_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOSERVER.
Referenced by DetectEngineRunHttpCookieMpm().
uint32_t HttpHeaderPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * headers, uint32_t headers_len, uint8_t flags)
Http header match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
headers Headers to inspect.
headers_len Headers length.
Return values
ret Number of matches.
Definition at line 344 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hhd_ctx_tc, SigGroupHead_::mpm_hhd_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOSERVER.
Referenced by DetectEngineRunHttpHeaderMpm().
uint32_t HttpHHPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * hh, uint32_t hh_len, uint8_t flags)
Http host header match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
hh Host header to inspect.
hh_len Host header buffer length.
flags Flags
Return values
ret Number of matches.
Definition at line 571 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hhhd_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectEngineRunHttpHHMpm().
uint32_t HttpHRHPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * hrh, uint32_t hrh_len, uint8_t flags)
Http raw host header match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
hrh Raw hostname to inspect.
hrh_len Raw hostname buffer length.
flags Flags
Return values
ret Number of matches.
Definition at line 598 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hrhhd_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectEngineRunHttpHRHMpm().
uint32_t HttpMethodPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * raw_method, uint32_t raw_method_len, uint8_t flags)
Http method match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
method Method to inspect.
method_len Method length.
Return values
ret Number of matches.
Definition at line 408 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hmd_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectEngineRunHttpMethodMpm().
uint32_t HttpRawHeaderPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * raw_headers, uint32_t raw_headers_len, uint8_t flags)
Http raw header match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
headers Raw headers to inspect.
headers_len Raw headers length.
Return values
ret Number of matches.
Definition at line 376 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hrhd_ctx_tc, SigGroupHead_::mpm_hrhd_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOSERVER.
Referenced by DetectEngineRunHttpRawHeaderMpm().
uint32_t HttpRawUriPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * uri, uint32_t uri_len, uint8_t flags)
Http raw uri match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
uri Raw uri to inspect.
uri_len Raw uri length.
Return values
ret Number of matches.
Definition at line 466 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hrud_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectEngineRunHttpRawUriMpm().
uint32_t HttpServerBodyPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * body, uint32_t body_len, uint8_t flags)
Http server body pattern match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
body The request body to inspect.
body_len Body length.
Return values
ret Number of matches.
Definition at line 318 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hsbd_ctx_tc, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectEngineRunHttpServerBodyMpm().
uint32_t HttpStatCodePatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * stat_code, uint32_t stat_code_len, uint8_t flags)
Http stat code match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
stat_code Stat code to inspect.
stat_code_len Stat code length.
Return values
ret Number of matches.
Definition at line 518 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hscd_ctx_tc, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectEngineRunHttpStatCodeMpm().
uint32_t HttpStatMsgPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * stat_msg, uint32_t stat_msg_len, uint8_t flags)
Http stat msg match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
stat_msg Stat msg to inspect.
stat_msg_len Stat msg length.
Return values
ret Number of matches.
Definition at line 492 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_hsmd_ctx_tc, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectEngineRunHttpStatMsgMpm().
uint32_t HttpUAPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * ua, uint32_t ua_len, uint8_t flags)
Http user agent match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
cookie User-Agent to inspect.
cookie_len User-Agent buffer length.
Return values
ret Number of matches.
Definition at line 544 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_huad_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectEngineRunHttpUAMpm().
uint32_t MpmPatternIdStoreGetMaxId (MpmPatternIdStore * ht)
Definition at line 2806 of file detect-engine-mpm.c.
References MpmPatternIdStore_::max_id.
Referenced by DetectContentMaxId(), and DetectUricontentMaxId().
void MpmPatternIdTableFreeHash (MpmPatternIdStore * ht)
Definition at line 2790 of file detect-engine-mpm.c.
References MpmPatternIdStore_::hash, HashTableFree(), SCEnter, SCFree, and SCReturn.
Referenced by DetectEngineCtxFree().
MpmPatternIdStore* MpmPatternIdTableInitHash (void)
alloc initialize the MpmPatternIdHash
Definition at line 2776 of file detect-engine-mpm.c.
References BUG_ON, MpmPatternIdStore_::hash, HashTableInit(), SCEnter, SCMalloc, and SCReturnPtr.
void PacketPatternCleanup (ThreadVars * t, DetectEngineThreadCtx * det_ctx)
cleans up the mpm instance after a match
Definition at line 729 of file detect-engine-mpm.c.
References MpmTableElmt_::Cleanup, SigGroupHead_::mpm_proto_other_ctx, SigGroupHead_::mpm_proto_tcp_ctx_tc, SigGroupHead_::mpm_proto_tcp_ctx_ts, SigGroupHead_::mpm_proto_udp_ctx_tc, SigGroupHead_::mpm_proto_udp_ctx_ts, SigGroupHead_::mpm_stream_ctx_tc, SigGroupHead_::mpm_stream_ctx_ts, mpm_table, MpmCtx_::mpm_type, SigGroupHead_::mpm_uri_ctx_ts, DetectEngineThreadCtx_::mtc, DetectEngineThreadCtx_::mtcs, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, PmqReset(), and DetectEngineThreadCtx_::sgh.
Referenced by SigMatchSignatures().
uint32_t PacketPatternSearch (DetectEngineThreadCtx * det_ctx, Packet * p)
Pattern match – searches for only one pattern per signature.
Parameters
det_ctx detection engine thread ctx
p packet to inspect
Return values
ret number of matches
Definition at line 211 of file detect-engine-mpm.c.
References FLOW_PKT_TOSERVER, Packet_::flowflags, SigGroupHead_::mpm_proto_other_ctx, SigGroupHead_::mpm_proto_tcp_ctx_tc, SigGroupHead_::mpm_proto_tcp_ctx_ts, SigGroupHead_::mpm_proto_udp_ctx_tc, SigGroupHead_::mpm_proto_udp_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtc, Packet_::payload, Packet_::payload_len, Packet_::pkt_src, PKT_SRC_WIRE, DetectEngineThreadCtx_::pmq, Packet_::proto, SCEnter, SCReturnInt, MpmTableElmt_::Search, DetectEngineThreadCtx_::sgh, and unlikely.
uint32_t PacketPatternSearchWithStreamCtx (DetectEngineThreadCtx * det_ctx, Packet * p)
Definition at line 180 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, FLOW_PKT_TOSERVER, Packet_::flowflags, SigGroupHead_::mpm_stream_ctx_tc, SigGroupHead_::mpm_stream_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtc, Packet_::payload, Packet_::payload_len, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnInt, and DetectEngineThreadCtx_::sgh.
uint16_t PatternMatchDefaultMatcher (void)
Function to return the multi pattern matcher algorithm to be used by the engine, based on the mpm-algo setting in yaml Use the default mpm if none is specified in the yaml file.
Return values
mpm algo value
Definition at line 145 of file detect-engine-mpm.c.
References ConfGet(), DEFAULT_MPM, MPM_AC, MPM_AC_TILE, mpm_table, MPM_TABLE_SIZE, SC_ERR_INVALID_YAML_CONF_ENTRY, and SCLogError.
Referenced by main(), RunModeDispatch(), RunUnittests(), and SigGroupBuild().
void PatternMatchDestroy (MpmCtx * mpm_ctx, uint16_t mpm_matcher)
Definition at line 788 of file detect-engine-mpm.c.
References MpmTableElmt_::DestroyCtx, mpm_table, and SCLogDebug.
void PatternMatchDestroyGroup (SigGroupHead * sh)
Definition at line 819 of file detect-engine-mpm.c.
References MpmTableElmt_::DestroyCtx, SigGroupHead_::flags, MpmCtx_::global, SigGroupHead_::mpm_dnsquery_ctx_ts, SigGroupHead_::mpm_hcbd_ctx_ts, SigGroupHead_::mpm_hcd_ctx_tc, SigGroupHead_::mpm_hcd_ctx_ts, SigGroupHead_::mpm_hhd_ctx_tc, SigGroupHead_::mpm_hhd_ctx_ts, SigGroupHead_::mpm_hmd_ctx_ts, SigGroupHead_::mpm_hrhd_ctx_tc, SigGroupHead_::mpm_hrhd_ctx_ts, SigGroupHead_::mpm_hrud_ctx_ts, SigGroupHead_::mpm_hsbd_ctx_tc, SigGroupHead_::mpm_hscd_ctx_tc, SigGroupHead_::mpm_hsmd_ctx_tc, SigGroupHead_::mpm_huad_ctx_ts, SigGroupHead_::mpm_proto_other_ctx, SigGroupHead_::mpm_proto_tcp_ctx_tc, SigGroupHead_::mpm_proto_tcp_ctx_ts, SigGroupHead_::mpm_proto_udp_ctx_tc, SigGroupHead_::mpm_proto_udp_ctx_ts, SigGroupHead_::mpm_smtp_filedata_ctx_ts, SigGroupHead_::mpm_stream_ctx_tc, SigGroupHead_::mpm_stream_ctx_ts, mpm_table, MpmCtx_::mpm_type, SigGroupHead_::mpm_uri_ctx_ts, SCFree, SCLogDebug, SIG_GROUP_HEAD_MPM_COPY, SIG_GROUP_HEAD_MPM_STREAM_COPY, and SIG_GROUP_HEAD_MPM_URI_COPY.
Referenced by SigGroupHeadFree().
void PatternMatchPrepare (MpmCtx * mpm_ctx, uint16_t mpm_matcher)
Definition at line 794 of file detect-engine-mpm.c.
References MpmInitCtx(), and SCLogDebug.
int PatternMatchPrepareGroup (DetectEngineCtx * de_ctx, SigGroupHead * sh)
Prepare the pattern matcher ctx in a sig group head.
Todo:
determine if a content match can set the 'single' flag
do error checking
rewrite the COPY stuff
< our sgh has packet payload inspecting content
< our sgh has stream inspecting content
< our sgh has uri inspecting content
Definition at line 1935 of file detect-engine-mpm.c.
References Signature_::alproto, ALPROTO_HTTP, ALPROTO_SMTP, ALPROTO_UNKNOWN, DETECT_SM_LIST_DNSQUERYNAME_MATCH, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_UMATCH, ENGINE_SGH_MPM_FACTORY_CONTEXT_FULL, ENGINE_SGH_MPM_FACTORY_CONTEXT_SINGLE, SigGroupHead_::match_array, MPM_CTX_FACTORY_UNIQUE_CONTEXT, SigGroupHead_::mpm_dnsquery_ctx_ts, SigGroupHead_::mpm_hcbd_ctx_ts, SigGroupHead_::mpm_hcd_ctx_tc, SigGroupHead_::mpm_hcd_ctx_ts, SigGroupHead_::mpm_hhd_ctx_tc, SigGroupHead_::mpm_hhd_ctx_ts, SigGroupHead_::mpm_hhhd_ctx_ts, SigGroupHead_::mpm_hmd_ctx_ts, SigGroupHead_::mpm_hrhd_ctx_tc, SigGroupHead_::mpm_hrhd_ctx_ts, SigGroupHead_::mpm_hrhhd_ctx_ts, SigGroupHead_::mpm_hrud_ctx_ts, SigGroupHead_::mpm_hsbd_ctx_tc, SigGroupHead_::mpm_hscd_ctx_tc, SigGroupHead_::mpm_hsmd_ctx_tc, SigGroupHead_::mpm_huad_ctx_ts, DetectEngineCtx_::mpm_matcher, SigGroupHead_::mpm_proto_other_ctx, SigGroupHead_::mpm_proto_tcp_ctx_tc, SigGroupHead_::mpm_proto_tcp_ctx_ts, SigGroupHead_::mpm_proto_udp_ctx_tc, SigGroupHead_::mpm_proto_udp_ctx_ts, SigGroupHead_::mpm_smtp_filedata_ctx_ts, SigGroupHead_::mpm_stream_ctx_tc, SigGroupHead_::mpm_stream_ctx_ts, mpm_table, MpmCtx_::mpm_type, SigGroupHead_::mpm_uri_ctx_ts, MpmFactoryGetMpmCtxForProfile(), MpmFactoryReClaimMpmCtx(), MpmInitCtx(), MpmCtx_::pattern_cnt, MpmTableElmt_::Prepare, SCLogDebug, DetectEngineCtx_::sgh_mpm_context, DetectEngineCtx_::sgh_mpm_context_dnsquery, DetectEngineCtx_::sgh_mpm_context_hcbd, DetectEngineCtx_::sgh_mpm_context_hcd, DetectEngineCtx_::sgh_mpm_context_hhd, DetectEngineCtx_::sgh_mpm_context_hhhd, DetectEngineCtx_::sgh_mpm_context_hmd, DetectEngineCtx_::sgh_mpm_context_hrhd, DetectEngineCtx_::sgh_mpm_context_hrhhd, DetectEngineCtx_::sgh_mpm_context_hrud, DetectEngineCtx_::sgh_mpm_context_hsbd, DetectEngineCtx_::sgh_mpm_context_hscd, DetectEngineCtx_::sgh_mpm_context_hsmd, DetectEngineCtx_::sgh_mpm_context_huad, DetectEngineCtx_::sgh_mpm_context_proto_other_packet, DetectEngineCtx_::sgh_mpm_context_proto_tcp_packet, DetectEngineCtx_::sgh_mpm_context_proto_udp_packet, DetectEngineCtx_::sgh_mpm_context_smtp, DetectEngineCtx_::sgh_mpm_context_stream, DetectEngineCtx_::sgh_mpm_context_uri, SigGroupHead_::sig_cnt, SignatureHasPacketContent(), SignatureHasStreamContent(), and Signature_::sm_lists.
Referenced by BuildDestinationAddressHeads(), and BuildDestinationAddressHeadsWithBothPorts().
void PatternMatchThreadDestroy (MpmThreadCtx * mpm_thread_ctx, uint16_t mpm_matcher)
Definition at line 805 of file detect-engine-mpm.c.
References MpmTableElmt_::DestroyThreadCtx, mpm_table, and SCLogDebug.
Referenced by DetectEngineThreadCtxFree().
void PatternMatchThreadPrepare (MpmThreadCtx * mpm_thread_ctx, uint16_t mpm_matcher, uint32_t max_id)
Definition at line 811 of file detect-engine-mpm.c.
References MpmInitThreadCtx(), and SCLogDebug.
void PatternMatchThreadPrint (MpmThreadCtx * mpm_thread_ctx, uint16_t mpm_matcher)
Definition at line 800 of file detect-engine-mpm.c.
References SCLogDebug.
Referenced by DetectEngineThreadCtxInfo().
uint32_t PatternStrength (uint8_t * pat, uint16_t patlen)
Predict a strength value for patterns.
Patterns with high character diversity score higher. Alpha chars score not so high Other printable + a few common codes a little higher Everything else highest. Longer patterns score better than short patters.
Parameters
pat pattern
patlen length of the patternn
Return values
s pattern score
Definition at line 1184 of file detect-engine-mpm.c.
Referenced by RetrieveFPForSig(), and RetrieveFPForSigV2().
SigMatch* RetrieveFPForSig (Signature * s)
Definition at line 1669 of file detect-engine-mpm.c.
References DetectContentData_::content, DetectContentData_::content_len, SigMatch_::ctx, DETECT_CONTENT, DETECT_CONTENT_FAST_PATTERN, DETECT_CONTENT_NEGATED, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_MAX, DETECT_SM_LIST_PMATCH, DetectContentData_::flags, Signature_::mpm_sm, SigMatch_::next, PatternStrength(), SCLogDebug, and Signature_::sm_lists.
SigMatch* RetrieveFPForSigV2 (Signature * s)
Definition at line 1785 of file detect-engine-mpm.c.
References BUG_ON, DetectContentData_::content, DetectContentData_::content_len, SigMatch_::ctx, DETECT_CONTENT, DETECT_CONTENT_FAST_PATTERN, DETECT_CONTENT_NEGATED, DETECT_SM_LIST_MAX, DetectContentData_::flags, SCFPSupportSMList_::list_id, Signature_::mpm_sm, SCFPSupportSMList_::next, SigMatch_::next, PatternStrength(), SCFPSupportSMList_::priority, SCLogDebug, sm_fp_support_smlist_list, and Signature_::sm_lists.
Referenced by DetectSetFastPatternAndItsId().
int SignatureHasPacketContent (Signature * s)
check if a signature has patterns that are to be inspected against a packets payload (as opposed to the stream payload)
Parameters
s signature
Return values
1 true
0 false
Definition at line 79 of file detect-engine-mpm.c.
References DETECT_SM_LIST_PMATCH, Signature_::flags, DetectProto_::proto, Signature_::proto, SCEnter, SCLogDebug, SCReturnInt, SIG_FLAG_REQUIRE_PACKET, and Signature_::sm_lists.
Referenced by PatternMatchPrepareGroup(), and SigGroupHeadLoadStreamContent().
int SignatureHasStreamContent (Signature * s)
check if a signature has patterns that are to be inspected against the stream payload (as opposed to the individual packets payload(s))
Parameters
s signature
Return values
1 true
0 false
Definition at line 113 of file detect-engine-mpm.c.
References DETECT_SM_LIST_PMATCH, Signature_::flags, DetectProto_::proto, Signature_::proto, SCEnter, SCLogDebug, SCReturnInt, SIG_FLAG_REQUIRE_STREAM, and Signature_::sm_lists.
Referenced by PatternMatchPrepareGroup().
uint32_t SMTPFiledataPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * buffer, uint32_t buffer_len, uint8_t flags)
SMTP Filedata match – searches for one pattern per signature.
Parameters
det_ctx Detection engine thread ctx.
buffer Buffer to inspect.
buffer_len buffer length.
flags Flags
Return values
ret Number of matches.
Definition at line 710 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, SigGroupHead_::mpm_smtp_filedata_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.
Referenced by DetectEngineRunSMTPMpm().
void StreamPatternCleanup (ThreadVars * t, DetectEngineThreadCtx * det_ctx, StreamMsg * smsg)
Definition at line 776 of file detect-engine-mpm.c.
References StreamMsg_::next, PmqReset(), and DetectEngineThreadCtx_::smsg_pmq.
Referenced by SigMatchSignatures().
uint32_t StreamPatternSearch (DetectEngineThreadCtx * det_ctx, Packet * p, StreamMsg * smsg, uint8_t flags)
Pattern match – searches for only one pattern per signature.
Parameters
det_ctx detection engine thread ctx
p packet
smsg stream msg (reassembled stream data)
flags stream flags
Return values
ret number of matches
Definition at line 652 of file detect-engine-mpm.c.
References StreamMsg_::data, StreamMsg_::data_len, SigGroupHead_::mpm_stream_ctx_tc, SigGroupHead_::mpm_stream_ctx_ts, mpm_table, MpmCtx_::mpm_type, DetectEngineThreadCtx_::mtcs, StreamMsg_::next, DetectEngineThreadCtx_::pmq, PmqMerge(), SCEnter, SCLogDebug, SCReturnInt, DetectEngineThreadCtx_::sgh, DetectEngineThreadCtx_::smsg_pmq, and STREAM_TOSERVER.
UricontentHash* UricontentHashAlloc (DetectContentData * ptr)
Definition at line 1148 of file detect-engine-mpm.c.
References UricontentHash_::cnt, UricontentHash_::ptr, SCMalloc, unlikely, and UricontentHash_::use.
char UricontentHashCompareFunc (void * data1, uint16_t len1, void * data2, uint16_t len2)
Definition at line 1120 of file detect-engine-mpm.c.
References DetectContentData_::content, DetectContentData_::content_len, DETECT_CONTENT_NOCASE, DetectContentData_::flags, UricontentHash_::ptr, and SCMemcmp.
void UricontentHashFree (void * ch)
Definition at line 1166 of file detect-engine-mpm.c.
References SCFree.
uint32_t UricontentHashFunc (HashTable * ht, void * data, uint16_t datalen)
Definition at line 1091 of file detect-engine-mpm.c.
References HashTable_::array_size, DetectContentData_::content, DetectContentData_::content_len, UricontentHash_::ptr, and SCLogDebug.
uint32_t UriPatternSearch (DetectEngineThreadCtx * det_ctx, uint8_t * uri, uint16_t uri_len, uint8_t flags)
Uri Pattern match – searches for one pattern per signature.
Parameters
det_ctx detection engine thread ctx
p packet to inspect
Return values
ret number of matches
Definition at line 264 of file detect-engine-mpm.c.
References DEBUG_VALIDATE_BUG_ON, mpm_table, MpmCtx_::mpm_type, SigGroupHead_::mpm_uri_ctx_ts, DetectEngineThreadCtx_::mtcu, DetectEngineThreadCtx_::pmq, SCEnter, SCReturnUInt, DetectEngineThreadCtx_::sgh, and STREAM_TOCLIENT.