suricata: src/detect-engine-filedata-smtp.h File Reference
detect-engine-filedata-smtp.h File Reference
#include "app-layer-smtp.h"
Functions
int DetectEngineInspectSMTPFiledata (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *tx, uint64_t tx_id)
void DetectEngineCleanSMTPBuffers (DetectEngineThreadCtx *det_ctx)
int DetectEngineRunSMTPMpm (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Flow *f, SMTPState *smtp_state, uint8_t flags, void *tx, uint64_t idx)
void DetectEngineSMTPFiledataRegisterTests (void)
Detailed Description
Author
Giuseppe Longo giuse.nosp@m.ppel.nosp@m.ng@gm.nosp@m.ail..nosp@m.com
Definition in file detect-engine-filedata-smtp.h.
Function Documentation
void DetectEngineCleanSMTPBuffers (DetectEngineThreadCtx * det_ctx)
Definition at line 247 of file detect-engine-filedata-smtp.c.
References FiledataReassembledBody_::buffer_len, FiledataReassembledBody_::offset, DetectEngineThreadCtx_::smtp, DetectEngineThreadCtx_::smtp_buffers_list_len, and DetectEngineThreadCtx_::smtp_start_tx_id.
int DetectEngineInspectSMTPFiledata (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * tx, uint64_t tx_id)
Definition at line 199 of file detect-engine-filedata-smtp.c.
References DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_FD_SMTP, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DETECT_SM_LIST_FILEDATA, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, SMTPState_::files_ts, FileContainer_::head, DetectEngineThreadCtx_::inspection_recursion_counter, File_::next, and Signature_::sm_lists.
Referenced by DetectEngineRegisterAppInspectionEngines().
int DetectEngineRunSMTPMpm (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Flow * f, SMTPState * smtp_state, uint8_t flags, void * tx, uint64_t idx)
Definition at line 261 of file detect-engine-filedata-smtp.c.
References SMTPState_::files_ts, FileContainer_::head, File_::next, and SMTPFiledataPatternSearch().
void DetectEngineSMTPFiledataRegisterTests (void)
Definition at line 550 of file detect-engine-filedata-smtp.c.
Referenced by RunUnittests().