suricata: src/detect-xbits.c File Reference
detect-xbits.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "threads.h"
#include "flow.h"
#include "flow-util.h"
#include "detect-xbits.h"
#include "detect-hostbits.h"
#include "util-spm.h"
#include "detect-engine-sigorder.h"
#include "app-layer-parser.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow-bit.h"
#include "host-bit.h"
#include "ippair-bit.h"
#include "util-var-name.h"
#include "util-unittest.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "([a-z]+)" "(?:,\\s*([^,]+))?" "(?:,\\s*(?:track\\s+([^,]+)))" "(?:,\\s*(?:expire\\s+([^,]+)))?"
#define MAX_SUBSTRINGS 30
Functions
int DetectXbitMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, const SigMatchCtx *)
void DetectXbitFree (void *)
void XBitsRegisterTests (void)
this function registers unit tests for XBits
void DetectXbitsRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements the xbits keyword
Definition in file detect-xbits.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
#define PARSE_REGEX "([a-z]+)" "(?:,\\s*([^,]+))?" "(?:,\\s*(?:track\\s+([^,]+)))" "(?:,\\s*(?:expire\\s+([^,]+)))?"
Definition at line 56 of file detect-xbits.c.
Referenced by DetectXbitsRegister().
Function Documentation
void DetectXbitFree (void * ptr)
Definition at line 356 of file detect-xbits.c.
References SCFree.
Referenced by DetectXbitsRegister().
int DetectXbitMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Definition at line 185 of file detect-xbits.c.
References DetectXbitMatchHost(), DetectXbitsData_::type, VAR_TYPE_HOST_BIT, and VAR_TYPE_IPPAIR_BIT.
Referenced by DetectXbitsRegister().
void DetectXbitsRegister (void)
Definition at line 65 of file detect-xbits.c.
References SigTableElmt_::desc, DETECT_XBITS, DetectXbitFree(), DetectXbitMatch(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, sigmatch_table, and XBitsRegisterTests().
Referenced by SigTableSetup().
void XBitsRegisterTests (void)
this function registers unit tests for XBits
Definition at line 539 of file detect-xbits.c.
Referenced by DetectXbitsRegister().