suricata: src/detect-engine-hcbd.c File Reference
detect-engine-hcbd.c File Reference
HTTP layer support
Handle HTTP request body match corresponding to http_client_body keyword.
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-parse.h"
#include "detect-engine-state.h"
#include "detect-engine-content-inspection.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-print.h"
#include "flow.h"
#include "app-layer-parser.h"
#include "stream-tcp.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "app-layer-htp.h"
#include "app-layer-protos.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#define BUFFER_STEP 50
int DetectEngineRunHttpClientBodyMpm (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Flow *f, HtpState *htp_state, uint8_t flags, void *tx, uint64_t idx)
int DetectEngineInspectHttpClientBody (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *tx, uint64_t tx_id)
void DetectEngineCleanHCBDBuffers (DetectEngineThreadCtx *det_ctx)
void DetectEngineHttpClientBodyRegisterTests (void)
Detailed Description
Handle HTTP request body match corresponding to http_client_body keyword.
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-engine-hcbd.c.
Macro Definition Documentation
#define BUFFER_STEP 50
Definition at line 63 of file detect-engine-hcbd.c.
Function Documentation
void DetectEngineCleanHCBDBuffers (DetectEngineThreadCtx * det_ctx)
Definition at line 283 of file detect-engine-hcbd.c.
References HttpReassembledBody_::buffer_len, DetectEngineThreadCtx_::hcbd, DetectEngineThreadCtx_::hcbd_buffers_list_len, DetectEngineThreadCtx_::hcbd_start_tx_id, and HttpReassembledBody_::offset.
Referenced by SigMatchSignatures().
void DetectEngineHttpClientBodyRegisterTests (void)
Definition at line 1043 of file detect-engine-hcbd.c.
Referenced by RunUnittests().
int DetectEngineInspectHttpClientBody (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * tx, uint64_t tx_id)
Definition at line 245 of file detect-engine-hcbd.c.
References ALPROTO_HTTP, AppLayerParserGetStateProgress(), DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HCBD, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DETECT_SM_LIST_HCBDMATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, HTP_REQUEST_BODY, DetectEngineThreadCtx_::inspection_recursion_counter, and Signature_::sm_lists.
Referenced by DetectEngineRegisterAppInspectionEngines().
int DetectEngineRunHttpClientBodyMpm (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Flow * f, HtpState * htp_state, uint8_t flags, void * tx, uint64_t idx)
Definition at line 222 of file detect-engine-hcbd.c.
References HttpClientBodyPatternSearch().