suricata: src/detect-fast-pattern.c File Reference
detect-fast-pattern.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "flow.h"
#include "detect-content.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-fast-pattern.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
Macros
#define DETECT_FAST_PATTERN_REGEX "^(\\s*only\\s*)|\\s*([0-9]+)\\s*,\\s*([0-9]+)\\s*$"
#define MAX_SUBSTRINGS 30
Functions
void DetectFastPatternRegisterTests (void)
void SupportFastPatternForSigMatchTypes (void)
Registers the keywords(SMs) that should be given fp support.
void DetectFastPatternRegister (void)
Registration function for fast_pattern keyword.
Variables
SCFPSupportSMList * sm_fp_support_smlist_list = NULL
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements the fast_pattern keyword
Definition in file detect-fast-pattern.c.
Macro Definition Documentation
#define DETECT_FAST_PATTERN_REGEX "^(\\s*only\\s*)|\\s*([0-9]+)\\s*,\\s*([0-9]+)\\s*$"
Definition at line 40 of file detect-fast-pattern.c.
Referenced by DetectFastPatternRegister().
#define MAX_SUBSTRINGS 30
Function Documentation
void DetectFastPatternRegister (void)
Registration function for fast_pattern keyword.
Definition at line 154 of file detect-fast-pattern.c.
References SigTableElmt_::desc, DETECT_FAST_PATTERN, DETECT_FAST_PATTERN_REGEX, DetectFastPatternRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectFastPatternRegisterTests (void)
Definition at line 19439 of file detect-fast-pattern.c.
Referenced by DetectFastPatternRegister().
void SupportFastPatternForSigMatchTypes (void)
Registers the keywords(SMs) that should be given fp support.
Definition at line 115 of file detect-fast-pattern.c.
References DETECT_SM_LIST_DNSQUERYNAME_MATCH, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, SCFPSupportSMList_::list_id, SCFPSupportSMList_::next, SCFPSupportSMList_::priority, and sm_fp_support_smlist_list.
Referenced by main(), and RunUnittests().
Variable Documentation
SCFPSupportSMList* sm_fp_support_smlist_list = NULL
Definition at line 50 of file detect-fast-pattern.c.
Referenced by RetrieveFPForSigV2(), and SupportFastPatternForSigMatchTypes().