suricata: src/detect-engine-event.c File Reference
detect-engine-event.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "flow-var.h"
#include "decode-events.h"
#include "util-debug.h"
#include "stream-tcp.h"
#include "detect-engine-event.h"
#include "util-unittest.h"
Macros
#define DETECT_EVENTS
#define PARSE_REGEX "\\S[0-9A-z_]+[.][A-z0-9_+]+$"
#define MAX_SUBSTRINGS 30
Functions
int DetectEngineEventMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match decoder event flags set on a packet with those passed via decode-event:
void EngineEventRegisterTests (void)
this function registers unit tests for EngineEvent
void DetectEngineEventRegister (void)
Registration function for decode-event: keyword.
DetectEngineEventData * DetectEngineEventParse (char *rawstr)
This function is used to parse decoder events options passed via decode-event: keyword.
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Implements the decode-event keyword
Definition in file detect-engine-event.c.
Macro Definition Documentation
#define DETECT_EVENTS
Definition at line 41 of file detect-engine-event.c.
#define MAX_SUBSTRINGS 30
Referenced by DetectEngineEventParse().
#define PARSE_REGEX "\\S[0-9A-z_]+[.][A-z0-9_+]+$"
Definition at line 46 of file detect-engine-event.c.
Referenced by DetectEngineEventRegister().
Function Documentation
int DetectEngineEventMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match decoder event flags set on a packet with those passed via decode-event:
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
s pointer to the Signature
m pointer to the sigmatch
Return values
0 no match
1 match
Definition at line 117 of file detect-engine-event.c.
References de, ENGINE_ISSET_EVENT, DetectEngineEventData_::event, SCEnter, SCLogDebug, and SCReturnInt.
Referenced by DetectEngineEventRegister().
DetectEngineEventData* DetectEngineEventParse (char * rawstr)
This function is used to parse decoder events options passed via decode-event: keyword.
Parameters
rawstr Pointer to the user provided decode-event options
Return values
de pointer to DetectFlowData on success
NULL on failure
Definition at line 139 of file detect-engine-event.c.
References de, DetectEngineEventData_::event, MAX_SUBSTRINGS, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SC_ERR_UNKNOWN_DECODE_EVENT, SCFree, SCLogError, SCMalloc, STREAM_REASSEMBLY_OVERLAP_DIFFERENT_DATA, StreamTcpReassembleConfigEnableOverlapCheck(), and unlikely.
void DetectEngineEventRegister (void)
Registration function for decode-event: keyword.
Definition at line 62 of file detect-engine-event.c.
References DETECT_DECODE_EVENT, DETECT_ENGINE_EVENT, DETECT_STREAM_EVENT, DetectEngineEventMatch(), EngineEventRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_DEONLY_COMPAT, and sigmatch_table.
Referenced by SigTableSetup().
void EngineEventRegisterTests (void)
this function registers unit tests for EngineEvent
Definition at line 402 of file detect-engine-event.c.
Referenced by DetectEngineEventRegister().