suricata: src/detect-ssl-version.h File Reference
detect-ssl-version.h File Reference
Data Structures
struct SSLVersionData_
struct DetectSslVersionData_
Macros
#define DETECT_SSL_VERSION_NEGATED 0x01
Typedefs
typedef struct SSLVersionData_ SSLVersionData
typedef struct
DetectSslVersionData_ DetectSslVersionData
Enumerations
enum {
SSLv2 = 0, SSLv3 = 1, TLS10 = 2, TLS11 = 3,
TLS12 = 4, TLS_SIZE = 5, TLS_UNKNOWN = 6
}
Functions
void DetectSslVersionRegister (void)
Registration function for keyword: ssl_version.
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Definition in file detect-ssl-version.h.
Macro Definition Documentation
#define DETECT_SSL_VERSION_NEGATED 0x01
Definition at line 28 of file detect-ssl-version.h.
Referenced by DetectSslVersionMatch(), and DetectSslVersionParse().
Typedef Documentation
typedef struct DetectSslVersionData_ DetectSslVersionData
typedef struct SSLVersionData_ SSLVersionData
Enumeration Type Documentation
anonymous enum
Enumerator
SSLv2
SSLv3
TLS10
TLS11
TLS12
TLS_SIZE
TLS_UNKNOWN
Definition at line 30 of file detect-ssl-version.h.
Function Documentation
void DetectSslVersionRegister (void)
Registration function for keyword: ssl_version.
Definition at line 72 of file detect-ssl-version.c.
References SigTableElmt_::alproto, ALPROTO_TLS, SigTableElmt_::AppLayerMatch, DETECT_AL_SSL_VERSION, DetectSslVersionFree(), DetectSslVersionMatch(), DetectSslVersionRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().