suricata: src/detect-http-raw-header.c File Reference
detect-http-raw-header.c File Reference
HTTP layer support
#include "suricata-common.h"
#include "threads.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "detect-content.h"
#include "detect-pcre.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-spm.h"
#include "util-print.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "detect-http-raw-header.h"
#include "stream-tcp.h"
Functions
int DetectHttpRawHeaderSetup (DetectEngineCtx *de_ctx, Signature *s, char *arg)
The setup function for the http_raw_header keyword for a signature.
void DetectHttpRawHeaderRegisterTests (void)
void DetectHttpRawHeaderFree (void *ptr)
this function clears the memory of http_raw_header modifier keyword
void DetectHttpRawHeaderRegister (void)
Registers the keyword handlers for the "http_raw_header" keyword.
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements support for http_raw_header keyword.
Definition in file detect-http-raw-header.c.
Function Documentation
void DetectHttpRawHeaderFree (void * ptr)
this function clears the memory of http_raw_header modifier keyword
Parameters
ptr Pointer to the Detection Header Data
Definition at line 91 of file detect-http-raw-header.c.
References DetectContentData_::content, and SCFree.
Referenced by DetectHttpRawHeaderRegister().
void DetectHttpRawHeaderRegister (void)
Registers the keyword handlers for the "http_raw_header" keyword.
Definition at line 69 of file detect-http-raw-header.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, DETECT_AL_HTTP_RAW_HEADER, DetectHttpRawHeaderFree(), DetectHttpRawHeaderRegisterTests(), DetectHttpRawHeaderSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void DetectHttpRawHeaderRegisterTests (void)
Definition at line 1527 of file detect-http-raw-header.c.
Referenced by DetectHttpRawHeaderRegister().
int DetectHttpRawHeaderSetup (DetectEngineCtx * de_ctx, Signature * s, char * arg)
The setup function for the http_raw_header keyword for a signature.
Parameters
de_ctx Pointer to the detection engine context.
s Pointer to signature for the current Signature being parsed from the rules.
m Pointer to the head of the SigMatchs for the current rule being parsed.
arg Pointer to the string holding the keyword value.
Return values
0 On success.
-1 On failure.
Definition at line 117 of file detect-http-raw-header.c.
References ALPROTO_HTTP, DETECT_AL_HTTP_RAW_HEADER, DETECT_SM_LIST_HRHDMATCH, and DetectEngineContentModifierBufferSetup().
Referenced by DetectHttpRawHeaderRegister().