suricata: src/detect-flowvar.c File Reference
detect-flowvar.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-content.h"
#include "threads.h"
#include "flow.h"
#include "flow-var.h"
#include "detect-flowvar.h"
#include "util-spm.h"
#include "util-var-name.h"
#include "util-debug.h"
#include "util-print.h"
Macros
#define PARSE_REGEX "(.*),(.*)"
#define MAX_SUBSTRINGS 30
Functions
int DetectFlowvarMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, const SigMatchCtx *)
void DetectFlowvarRegister (void)
int DetectFlowvarStoreMatch (DetectEngineThreadCtx *det_ctx, uint16_t idx, uint8_t *buffer, uint16_t len, int type)
Store flowvar in det_ctx so we can exec it post-match.
int DetectFlowvarPostMatchSetup (Signature *s, uint16_t idx)
Setup a post-match for flowvar storage We're piggyback riding the DetectFlowvarData struct.
void DetectFlowvarProcessListInternal (DetectFlowvarList *fs, Flow *f, const int flow_locked)
Handle flowvar candidate list in det_ctx:
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Simple flowvar content match part of the detection engine.
Definition in file detect-flowvar.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
#define PARSE_REGEX "(.*),(.*)"
Definition at line 43 of file detect-flowvar.c.
Referenced by DetectFlowvarRegister().
Function Documentation
int DetectFlowvarMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Definition at line 117 of file detect-flowvar.c.
References DetectFlowvarData_::content, DetectFlowvarData_::content_len, FlowVar_::data, Packet_::flow, FLOWLOCK_RDLOCK, FLOWLOCK_UNLOCK, FlowVarGet(), FlowVar_::fv_str, DetectFlowvarData_::idx, SpmSearch, FlowVarTypeStr::value, and FlowVarTypeStr::value_len.
Referenced by DetectFlowvarRegister().
int DetectFlowvarPostMatchSetup (Signature * s, uint16_t idx)
Setup a post-match for flowvar storage We're piggyback riding the DetectFlowvarData struct.
Definition at line 254 of file detect-flowvar.c.
References SigMatch_::ctx, DETECT_FLOWVAR_POSTMATCH, DETECT_SM_LIST_POSTMATCH, DetectFlowvarData_::idx, SCMalloc, SigMatchAlloc(), SigMatchAppendSMToList(), SigMatch_::type, and unlikely.
void DetectFlowvarProcessListInternal (DetectFlowvarList * fs, Flow * f, const int flow_locked)
Handle flowvar candidate list in det_ctx:
  - clean up the list
  - enforce storage for type ALWAYS (luajit)
Only called from DetectFlowvarProcessList() when flowvarlist is not NULL .
Definition at line 334 of file detect-flowvar.c.
References DetectFlowvarList_::buffer, BUG_ON, DETECT_FLOWVAR_TYPE_ALWAYS, FlowVarAddStr(), FlowVarAddStrNoLock(), DetectFlowvarList_::idx, DetectFlowvarList_::len, DetectFlowvarList_::next, next, SCFree, SCLogDebug, and DetectFlowvarList_::type.
void DetectFlowvarRegister (void)
Definition at line 52 of file detect-flowvar.c.
References DETECT_FLOWVAR, DETECT_FLOWVAR_POSTMATCH, DetectFlowvarMatch(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
int DetectFlowvarStoreMatch (DetectEngineThreadCtx * det_ctx, uint16_t idx, uint8_t * buffer, uint16_t len, int type)
Store flowvar in det_ctx so we can exec it post-match.
Definition at line 219 of file detect-flowvar.c.
References DetectFlowvarList_::buffer, DetectEngineThreadCtx_::flowvarlist, DetectFlowvarList_::idx, len, DetectFlowvarList_::len, DetectFlowvarList_::next, SCFree, SCMalloc, type, DetectFlowvarList_::type, and unlikely.
Referenced by DetectPcrePayloadMatch().