suricata: src/detect-window.h File Reference
detect-window.h File Reference
Data Structures
struct DetectWindowData_
Macros
#define MIN_WINDOW_VALUE 0
#define MAX_WINDOW_VALUE 65535
Typedefs
typedef struct DetectWindowData_ DetectWindowData
Functions
void DetectWindowRegister (void)
Registration function for window: keyword.
Macro Definition Documentation
#define MAX_WINDOW_VALUE 65535
Definition at line 22 of file detect-window.h.
#define MIN_WINDOW_VALUE 0
Definition at line 21 of file detect-window.h.
Typedef Documentation
typedef struct DetectWindowData_ DetectWindowData
Function Documentation
void DetectWindowRegister (void)
Registration function for window: keyword.
Definition at line 58 of file detect-window.c.
References SigTableElmt_::desc, DETECT_WINDOW, DetectWindowFree(), DetectWindowMatch(), DetectWindowRegisterTests(), DetectWindowSetup(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().