suricata: src/detect-flowint.c File Reference
detect-flowint.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "threads.h"
#include "flow.h"
#include "flow-var.h"
#include "detect-flowint.h"
#include "util-spm.h"
#include "util-var-name.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "pkt-var.h"
#include "host.h"
#include "util-profiling.h"
Macros
#define PARSE_REGEX "^\\s*([a-zA-Z][\\w\\d_.]+)\\s*,\\s*([+=-]{1}|==|!=|<|<=|>|>=|isset|notset)\\s*,?\\s*([a-zA-Z][\\w\\d]+|[\\d]{1,10})?\\s*$"
#define MAX_SUBSTRINGS 30
Functions
int DetectFlowintMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to create a flowint, add/substract values, compare it with other flowints, etc.
void DetectFlowintFree (void *tmp)
This function is used to free the data of DetectFlowintData.
void DetectFlowintRegisterTests (void)
this function registers unit tests for DetectFlowint
void DetectFlowintRegister (void)
DetectFlowintData * DetectFlowintParse (DetectEngineCtx *de_ctx, char *rawstr)
This function is used to parse a flowint option.
void DetectFlowintPrintData (DetectFlowintData *sfd)
This is a helper funtion used for debugging purposes.
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Flowvar management for integer types, part of the detection engine Keyword: flowint
Definition in file detect-flowint.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectFlowintParse().
#define PARSE_REGEX "^\\s*([a-zA-Z][\\w\\d_.]+)\\s*,\\s*([+=-]{1}|==|!=|<|<=|>|>=|isset|notset)\\s*,?\\s*([a-zA-Z][\\w\\d]+|[\\d]{1,10})?\\s*$"
Definition at line 48 of file detect-flowint.c.
Referenced by DetectFlowintRegister().
Function Documentation
void DetectFlowintFree (void * tmp)
This function is used to free the data of DetectFlowintData.
Definition at line 436 of file detect-flowint.c.
References FLOWINT_TARGET_VAR, TargetVar_::name, DetectFlowintData_::name, SCFree, DetectFlowintData_::target, DetectFlowintData_::targettype, and DetectFlowintData_::tvar.
Referenced by DetectFlowintRegister().
int DetectFlowintMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to create a flowint, add/substract values, compare it with other flowints, etc.
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
s pointer to the current Signature
m pointer to the sigmatch that we will cast into DetectFlowintData
Return values
0 no match, when a var doesn't exist
1 match, when a var is initialized well, add/substracted, or a true condition
ATM If we are going to compare the current var with another that doesn't exist, the default value will be zero; if you don't want this behaviour, you can use the keyword "isset" to make it match or not before using the default value of zero; But it is mandatory that the current var exist, otherwise, it will return zero(not match).
Definition at line 107 of file detect-flowint.c.
References BUG_ON, FlowVar_::data, FlowVar_::datatype, DetectEngineThreadCtx_::de_ctx, Packet_::flow, DetectEngineThreadCtx_::flow_locked, FLOWINT_MODIFIER_ADD, FLOWINT_MODIFIER_EQ, FLOWINT_MODIFIER_GE, FLOWINT_MODIFIER_GT, FLOWINT_MODIFIER_ISSET, FLOWINT_MODIFIER_LE, FLOWINT_MODIFIER_LT, FLOWINT_MODIFIER_NE, FLOWINT_MODIFIER_NOTSET, FLOWINT_MODIFIER_SET, FLOWINT_MODIFIER_SUB, FLOWINT_TARGET_VAR, FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, FLOWVAR_TYPE_INT, FlowVarAddIntNoLock(), FlowVarGet(), FlowVar_::fv_int, DetectFlowintData_::idx, DetectFlowintData_::modifier, TargetVar_::name, DetectFlowintData_::name, SCLogDebug, DetectFlowintData_::target, DetectFlowintData_::targettype, DetectFlowintData_::tvar, FlowVarTypeInt_::value, DetectFlowintData_::value, VAR_TYPE_FLOW_INT, and VariableNameGetIdx().
Referenced by DetectFlowintRegister().
DetectFlowintData* DetectFlowintParse (DetectEngineCtx * de_ctx, char * rawstr)
This function is used to parse a flowint option.
Parameters
de_ctx pointer to the engine context
rawstr pointer to the string holding the options
Return values
NULL if invalid option
DetectFlowintData pointer with the flowint parsed
Definition at line 245 of file detect-flowint.c.
References FLOWINT_MODIFIER_ADD, FLOWINT_MODIFIER_EQ, FLOWINT_MODIFIER_GE, FLOWINT_MODIFIER_GT, FLOWINT_MODIFIER_ISSET, FLOWINT_MODIFIER_LE, FLOWINT_MODIFIER_LT, FLOWINT_MODIFIER_NE, FLOWINT_MODIFIER_NOTSET, FLOWINT_MODIFIER_SET, FLOWINT_MODIFIER_SUB, FLOWINT_MODIFIER_UNKNOWN, FLOWINT_TARGET_SELF, FLOWINT_TARGET_VAL, FLOWINT_TARGET_VAR, DetectFlowintData_::idx, MAX_SUBSTRINGS, DetectFlowintData_::modifier, TargetVar_::name, DetectFlowintData_::name, SC_ERR_MEM_ALLOC, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SC_ERR_UNKNOWN_VALUE, SCFree, SCLogDebug, SCLogError, SCMalloc, SCStrdup, DetectFlowintData_::target, DetectFlowintData_::targettype, DetectFlowintData_::tvar, unlikely, DetectFlowintData_::value, VAR_TYPE_FLOW_INT, VariableNameGetIdx(), and ptxdump::varname.
void DetectFlowintPrintData (DetectFlowintData * sfd)
This is a helper funtion used for debugging purposes.
Definition at line 452 of file detect-flowint.c.
References FLOWINT_TARGET_VAL, FLOWINT_TARGET_VAR, DetectFlowintData_::idx, DetectFlowintData_::modifier, TargetVar_::name, DetectFlowintData_::name, SCLogDebug, DetectFlowintData_::target, DetectFlowintData_::targettype, DetectFlowintData_::tvar, and DetectFlowintData_::value.
void DetectFlowintRegister (void)
Definition at line 60 of file detect-flowint.c.
References SigTableElmt_::desc, DETECT_FLOWINT, DetectFlowintFree(), DetectFlowintMatch(), DetectFlowintRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SCLogInfo, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectFlowintRegisterTests (void)
this function registers unit tests for DetectFlowint
Definition at line 2128 of file detect-flowint.c.
Referenced by DetectFlowintRegister().