suricata: src/detect-http-hrh.h File Reference
detect-http-hrh.h File Reference
Functions
void DetectHttpHRHRegister (void)
Registers the keyword handlers for the "http_raw_host" keyword.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-http-hrh.h.
Function Documentation
void DetectHttpHRHRegister (void)
Registers the keyword handlers for the "http_raw_host" keyword.
Definition at line 68 of file detect-http-hrh.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, SigTableElmt_::desc, DETECT_AL_HTTP_RAW_HOST, DetectHttpHRHFree(), DetectHttpHRHRegisterTests(), DetectHttpHRHSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().