suricata: src/detect-engine-dns.c File Reference
detect-engine-dns.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-parse.h"
#include "detect-engine-state.h"
#include "detect-engine-content-inspection.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-print.h"
#include "flow.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-protos.h"
#include "app-layer-dns-common.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
Functions
int DetectEngineInspectDnsQueryName (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *txv, uint64_t tx_id)
Do the content inspection & validation for a signature.
int DetectEngineInspectGenericList (ThreadVars *tv, const DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, const Signature *s, Flow *f, const uint8_t flags, void *alstate, void *txv, uint64_t tx_id, const int list)
Do the content inspection & validation for a signature.
int DetectEngineInspectDnsRequest (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *txv, uint64_t tx_id)
int DetectEngineInspectDnsResponse (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *txv, uint64_t tx_id)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Based on detect-engine-uri.c
Definition in file detect-engine-dns.c.
Function Documentation
int DetectEngineInspectDnsQueryName (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * txv, uint64_t tx_id)
Do the content inspection & validation for a signature.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
sm SigMatch to inspect
f Flow
flags app layer flags
state App layer state
Return values
0 no match
1 match
Definition at line 61 of file detect-engine-dns.c.
References DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_DNSQUERY, DETECT_SM_LIST_DNSQUERYNAME_MATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, DetectEngineThreadCtx_::inspection_recursion_counter, DNSQueryEntry_::len, next, SCLogDebug, Signature_::sm_lists, and TAILQ_FOREACH.
Referenced by DetectEngineRegisterAppInspectionEngines().
int DetectEngineInspectDnsRequest (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * txv, uint64_t tx_id)
Definition at line 143 of file detect-engine-dns.c.
References DETECT_SM_LIST_DNSREQUEST_MATCH, and DetectEngineInspectGenericList().
Referenced by DetectEngineRegisterAppInspectionEngines().
int DetectEngineInspectDnsResponse (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * txv, uint64_t tx_id)
Definition at line 154 of file detect-engine-dns.c.
References DETECT_SM_LIST_DNSRESPONSE_MATCH, and DetectEngineInspectGenericList().
Referenced by DetectEngineRegisterAppInspectionEngines().
int DetectEngineInspectGenericList (ThreadVars * tv, const DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, const Signature * s, Flow * f, const uint8_t flags, void * alstate, void * txv, uint64_t tx_id, const int list)
Do the content inspection & validation for a signature.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
sm SigMatch to inspect
f Flow
flags app layer flags
state App layer state
Return values
0 no match
1 match
Definition at line 110 of file detect-engine-dns.c.
References SigMatchData_::ctx, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, SigMatchData_::is_last, KEYWORD_PROFILING_END, KEYWORD_PROFILING_SET_LIST, KEYWORD_PROFILING_START, SCLogDebug, sigmatch_table, Signature_::sm_arrays, and SigMatchData_::type.
Referenced by DetectEngineInspectDnsRequest(), and DetectEngineInspectDnsResponse().