suricata: src/detect-ssl-state.h File Reference
detect-ssl-state.h File Reference
#include "app-layer-ssl.h"
Data Structures
struct DetectSslStateData_
Macros
#define DETECT_SSL_STATE_CLIENT_HELLO SSL_AL_FLAG_STATE_CLIENT_HELLO
#define DETECT_SSL_STATE_SERVER_HELLO SSL_AL_FLAG_STATE_SERVER_HELLO
#define DETECT_SSL_STATE_CLIENT_KEYX SSL_AL_FLAG_STATE_CLIENT_KEYX
#define DETECT_SSL_STATE_SERVER_KEYX SSL_AL_FLAG_STATE_SERVER_KEYX
#define DETECT_SSL_STATE_UNKNOWN SSL_AL_FLAG_STATE_UNKNOWN
Typedefs
typedef struct DetectSslStateData_ DetectSslStateData
Functions
void DetectSslStateRegister (void)
Registers the keyword handlers for the "ssl_state" keyword.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-ssl-state.h.
Macro Definition Documentation
#define DETECT_SSL_STATE_CLIENT_HELLO SSL_AL_FLAG_STATE_CLIENT_HELLO
Definition at line 30 of file detect-ssl-state.h.
Referenced by DetectSslStateParse().
#define DETECT_SSL_STATE_CLIENT_KEYX SSL_AL_FLAG_STATE_CLIENT_KEYX
Definition at line 32 of file detect-ssl-state.h.
Referenced by DetectSslStateParse().
#define DETECT_SSL_STATE_SERVER_HELLO SSL_AL_FLAG_STATE_SERVER_HELLO
Definition at line 31 of file detect-ssl-state.h.
Referenced by DetectSslStateParse().
#define DETECT_SSL_STATE_SERVER_KEYX SSL_AL_FLAG_STATE_SERVER_KEYX
Definition at line 33 of file detect-ssl-state.h.
Referenced by DetectSslStateParse().
#define DETECT_SSL_STATE_UNKNOWN SSL_AL_FLAG_STATE_UNKNOWN
Definition at line 34 of file detect-ssl-state.h.
Referenced by DetectSslStateParse().
Typedef Documentation
typedef struct DetectSslStateData_ DetectSslStateData
Function Documentation
void DetectSslStateRegister (void)
Registers the keyword handlers for the "ssl_state" keyword.
Definition at line 71 of file detect-ssl-state.c.
References SigTableElmt_::alproto, ALPROTO_TLS, SigTableElmt_::AppLayerMatch, DETECT_AL_SSL_STATE, DetectSslStateFree(), DetectSslStateMatch(), DetectSslStateRegisterTests(), DetectSslStateSetup(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX1, PARSE_REGEX2, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().