suricata: src/detect-engine-dcepayload.c File Reference
detect-engine-dcepayload.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-parse.h"
#include "detect-pcre.h"
#include "detect-isdataat.h"
#include "detect-bytetest.h"
#include "detect-bytejump.h"
#include "detect-byte-extract.h"
#include "detect-content.h"
#include "detect-engine-content-inspection.h"
#include "stream-tcp.h"
#include "app-layer.h"
#include "app-layer-dcerpc.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
Functions
int DetectEngineInspectDcePayload (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate)
Do the content inspection & validation for a signature against dce stub.
void DcePayloadRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-engine-dcepayload.c.
Function Documentation
void DcePayloadRegisterTests (void)
Definition at line 10133 of file detect-engine-dcepayload.c.
Referenced by RunUnittests().
int DetectEngineInspectDcePayload (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate)
Do the content inspection & validation for a signature against dce stub.
Parameters
de_ctx Detection engine context.
det_ctx Detection engine thread context.
s Signature to inspect.
sm SigMatch to inspect.
f Flow.
flags App layer flags.
state App layer state.
Return values
0 No match.
1 Match.
Definition at line 64 of file detect-engine-dcepayload.c.
References DetectEngineThreadCtx_::buffer_offset, DCERPCState_::dcerpc, DCERPC_::dcerpcrequest, DCERPC_::dcerpcresponse, DETECT_ENGINE_CONTENT_INSPECTION_MODE_DCE, DETECT_SM_LIST_DMATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, DetectEngineThreadCtx_::inspection_recursion_counter, SCEnter, SCReturnInt, Signature_::sm_lists, DCERPCRequest_::stub_data_buffer, DCERPCResponse_::stub_data_buffer, DCERPCRequest_::stub_data_buffer_len, DCERPCResponse_::stub_data_buffer_len, DCERPCRequest_::stub_data_fresh, and DCERPCResponse_::stub_data_fresh.
Referenced by DeStateDetectStartDetection().