suricata: src/detect-filemagic.c File Reference
detect-filemagic.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-spm-bm.h"
#include "util-magic.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "stream-tcp.h"
#include "detect-filemagic.h"
#include "conf.h"
Macros
#define FILEMAGIC_MIN_SIZE 512
Functions
void DetectFilemagicRegister (void)
Registration function for keyword: filemagic.
int FilemagicGlobalLookup (File *file)
run the magic check
int FilemagicThreadLookup (magic_t *ctx, File *file)
run the magic check
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-filemagic.c.
Macro Definition Documentation
#define FILEMAGIC_MIN_SIZE 512
Definition at line 82 of file detect-filemagic.c.
Referenced by FilemagicGlobalLookup(), and FilemagicThreadLookup().
Function Documentation
void DetectFilemagicRegister (void)
Registration function for keyword: filemagic.
Definition at line 67 of file detect-filemagic.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::desc, DETECT_FILEMAGIC, SigTableElmt_::FileMatch, SigTableElmt_::Free, SigTableElmt_::name, SigTableElmt_::RegisterTests, SCLogDebug, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
int FilemagicGlobalLookup (File * file)
run the magic check
Parameters
file the file
Return values
-1 error
0 ok
Definition at line 92 of file detect-filemagic.c.
References File_::chunks_head, FileData_::data, FILE_STATE_CLOSED, FILEMAGIC_MIN_SIZE, FileData_::len, likely, File_::magic, MagicGlobalLookup(), FileData_::next, SCFree, SCMalloc, SCReturnInt, and File_::state.
int FilemagicThreadLookup (magic_t * ctx, File * file)
run the magic check
Parameters
file the file
Return values
-1 error
0 ok
Definition at line 142 of file detect-filemagic.c.
References File_::chunks_head, FileData_::data, FILE_STATE_CLOSED, FILEMAGIC_MIN_SIZE, FileData_::len, likely, File_::magic, MagicThreadLookup(), FileData_::next, SCFree, SCMalloc, SCReturnInt, and File_::state.