suricata: src/detect-dce-opnum.h File Reference
detect-dce-opnum.h File Reference
Data Structures
struct DetectDceOpnumRange_
struct DetectDceOpnumData_
Macros
#define DCE_OPNUM_RANGE_MAX 65535
#define DCE_OPNUM_RANGE_UNINITIALIZED 100000
Typedefs
typedef struct DetectDceOpnumRange_ DetectDceOpnumRange
typedef struct DetectDceOpnumData_ DetectDceOpnumData
Functions
void DetectDceOpnumRegister (void)
Registers the keyword handlers for the "dce_opnum" keyword.
void DetectDceOpnumRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-dce-opnum.h.
Macro Definition Documentation
#define DCE_OPNUM_RANGE_MAX 65535
Definition at line 27 of file detect-dce-opnum.h.
#define DCE_OPNUM_RANGE_UNINITIALIZED 100000
Definition at line 28 of file detect-dce-opnum.h.
Referenced by DetectDceOpnumMatch().
Typedef Documentation
typedef struct DetectDceOpnumData_ DetectDceOpnumData
typedef struct DetectDceOpnumRange_ DetectDceOpnumRange
Function Documentation
void DetectDceOpnumRegister (void)
Registers the keyword handlers for the "dce_opnum" keyword.
Definition at line 63 of file detect-dce-opnum.c.
References SigTableElmt_::alproto, ALPROTO_DCERPC, SigTableElmt_::AppLayerMatch, DETECT_DCE_OPNUM, DETECT_DCE_OPNUM_PCRE_PARSE_ARGS, DetectDceOpnumFree(), DetectDceOpnumMatch(), DetectDceOpnumRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void DetectDceOpnumRegisterTests (void)
Definition at line 2926 of file detect-dce-opnum.c.
Referenced by DetectDceOpnumRegister().