suricata: src/detect-dce-iface.c File Reference
detect-dce-iface.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "detect-dce-iface.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "app-layer.h"
#include "app-layer-dcerpc.h"
#include "queue.h"
#include "stream-tcp-reassemble.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "stream-tcp.h"
Macros
#define DETECT_DCE_IFACE_PCRE_PARSE_ARGS "^\\s*([0-9a-zA-Z]{8}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{12})(?:\\s*,(<|>|=|!)([0-9]{1,5}))?(?:\\s*,(any_frag))?\\s*$"
#define MAX_SUBSTRINGS 30
Functions
int DetectDceIfaceMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Flow *f, uint8_t flags, void *state, Signature *s, SigMatch *m)
App layer match function for the "dce_iface" keyword.
void DetectDceIfaceFree (void *)
void DetectDceIfaceRegister (void)
Registers the keyword handlers for the "dce_iface" keyword.
void DetectDceIfaceRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements dce_iface keyword.
Definition in file detect-dce-iface.c.
Macro Definition Documentation
#define DETECT_DCE_IFACE_PCRE_PARSE_ARGS "^\\s*([0-9a-zA-Z]{8}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{12})(?:\\s*,(<|>|=|!)([0-9]{1,5}))?(?:\\s*,(any_frag))?\\s*$"
Definition at line 50 of file detect-dce-iface.c.
Referenced by DetectDceIfaceRegister().
#define MAX_SUBSTRINGS 30
Function Documentation
void DetectDceIfaceFree (void * ptr)
Definition at line 380 of file detect-dce-iface.c.
References SCFree.
Referenced by DetectDceIfaceRegister().
int DetectDceIfaceMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Flow * f, uint8_t flags, void * state, Signature * s, SigMatch * m)
App layer match function for the "dce_iface" keyword.
Parameters
t Pointer to the ThreadVars instance.
det_ctx Pointer to the DetectEngineThreadCtx.
f Pointer to the flow.
flags Pointer to the flags indicating the flow direction.
state Pointer to the app layer state data.
s Pointer to the Signature instance.
m Pointer to the SigMatch.
Return values
1 On Match.
0 On no match.
Definition at line 268 of file detect-dce-iface.c.
References DetectDceIfaceData_::any_frag, SigMatch_::ctx, DCERPCUuidEntry_::ctxid, DCERPC_UUID_ENTRY_FLAG_FF, DETECT_DCE_IFACE_OP_NONE, DCERPCUuidEntry_::flags, next, DetectDceIfaceData_::op, REQUEST, DCERPCUuidEntry_::result, SCEnter, SCLogDebug, SCReturnInt, TAILQ_FOREACH, DetectDceIfaceData_::uuid, DCERPCUuidEntry_::uuid, and DCERPCUuidEntry_::version.
Referenced by DetectDceIfaceRegister().
void DetectDceIfaceRegister (void)
Registers the keyword handlers for the "dce_iface" keyword.
Definition at line 63 of file detect-dce-iface.c.
References SigTableElmt_::alproto, ALPROTO_DCERPC, SigTableElmt_::AppLayerMatch, DETECT_DCE_IFACE, DETECT_DCE_IFACE_PCRE_PARSE_ARGS, DetectDceIfaceFree(), DetectDceIfaceMatch(), DetectDceIfaceRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SCLogDebug, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void DetectDceIfaceRegisterTests (void)
Definition at line 1811 of file detect-dce-iface.c.
Referenced by DetectDceIfaceRegister().