suricata: src/detect-byte-extract.h File Reference
detect-byte-extract.h File Reference
Data Structures
struct DetectByteExtractData_
Holds data related to byte_extract keyword.
Macros
#define DETECT_BYTE_EXTRACT_FLAG_RELATIVE 0x01
#define DETECT_BYTE_EXTRACT_FLAG_MULTIPLIER 0x02
#define DETECT_BYTE_EXTRACT_FLAG_STRING 0x04
#define DETECT_BYTE_EXTRACT_FLAG_ALIGN 0x08
#define DETECT_BYTE_EXTRACT_FLAG_ENDIAN 0x10
#define DETECT_BYTE_EXTRACT_ENDIAN_NONE 0
#define DETECT_BYTE_EXTRACT_ENDIAN_BIG 1
#define DETECT_BYTE_EXTRACT_ENDIAN_LITTLE 2
#define DETECT_BYTE_EXTRACT_ENDIAN_DCE 3
Typedefs
typedef struct
DetectByteExtractData_ DetectByteExtractData
Holds data related to byte_extract keyword.
Functions
void DetectByteExtractRegister (void)
Registers the keyword handlers for the "byte_extract" keyword.
int DetectByteExtractSetup (DetectEngineCtx *, Signature *, char *)
The setup function for the byte_extract keyword for a signature.
void DetectByteExtractFree (void *)
Used to free instances of DetectByteExtractData.
int DetectByteExtractMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, SigMatch *)
SigMatch * DetectByteExtractRetrieveSMVar (const char *, Signature *)
Lookup the SigMatch for a named byte_extract variable.
int DetectByteExtractDoMatch (DetectEngineThreadCtx *, SigMatch *, Signature *, uint8_t *, uint16_t, uint64_t *, uint8_t)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-byte-extract.h.
Macro Definition Documentation
#define DETECT_BYTE_EXTRACT_ENDIAN_BIG 1
Definition at line 36 of file detect-byte-extract.h.
Referenced by DetectByteExtractDoMatch().
#define DETECT_BYTE_EXTRACT_ENDIAN_DCE 3
Definition at line 38 of file detect-byte-extract.h.
Referenced by DetectByteExtractSetup().
#define DETECT_BYTE_EXTRACT_ENDIAN_LITTLE 2
Definition at line 37 of file detect-byte-extract.h.
#define DETECT_BYTE_EXTRACT_ENDIAN_NONE 0
Definition at line 35 of file detect-byte-extract.h.
#define DETECT_BYTE_EXTRACT_FLAG_ALIGN 0x08
Definition at line 31 of file detect-byte-extract.h.
Referenced by DetectByteExtractDoMatch().
#define DETECT_BYTE_EXTRACT_FLAG_ENDIAN 0x10
Definition at line 32 of file detect-byte-extract.h.
#define DETECT_BYTE_EXTRACT_FLAG_MULTIPLIER 0x02
Definition at line 29 of file detect-byte-extract.h.
#define DETECT_BYTE_EXTRACT_FLAG_RELATIVE 0x01
Definition at line 28 of file detect-byte-extract.h.
Referenced by DetectByteExtractDoMatch(), and DetectByteExtractSetup().
#define DETECT_BYTE_EXTRACT_FLAG_STRING 0x04
Definition at line 30 of file detect-byte-extract.h.
Referenced by DetectByteExtractDoMatch(), and DetectByteExtractSetup().
Typedef Documentation
typedef struct DetectByteExtractData_ DetectByteExtractData
Holds data related to byte_extract keyword.
Function Documentation
int DetectByteExtractDoMatch (DetectEngineThreadCtx * , SigMatch * , Signature * , uint8_t * , uint16_t , uint64_t * , uint8_t)
Definition at line 134 of file detect-byte-extract.c.
References DetectByteExtractData_::align_value, DetectByteExtractData_::base, DetectEngineThreadCtx_::buffer_offset, BYTE_BIG_ENDIAN, BYTE_LITTLE_ENDIAN, ByteExtractStringUint64(), ByteExtractUint64(), SigMatch_::ctx, data, DETECT_BYTE_EXTRACT_ENDIAN_BIG, DETECT_BYTE_EXTRACT_FLAG_ALIGN, DETECT_BYTE_EXTRACT_FLAG_RELATIVE, DETECT_BYTE_EXTRACT_FLAG_STRING, DetectByteExtractData_::flags, len, DetectByteExtractData_::multiplier_value, DetectByteExtractData_::nbytes, DetectByteExtractData_::offset, SC_ERR_INVALID_NUM_BYTES, SCLogDebug, and SCLogError.
void DetectByteExtractFree (void * ptr)
Used to free instances of DetectByteExtractData.
Parameters
ptr Instance of DetectByteExtractData to be freed.
Definition at line 761 of file detect-byte-extract.c.
References DetectByteExtractData_::name, and SCFree.
Referenced by DetectByteExtractRegister(), and DetectByteExtractSetup().
int DetectByteExtractMatch (ThreadVars * , DetectEngineThreadCtx * , Packet * , Signature * , SigMatch *)
Definition at line 225 of file detect-byte-extract.c.
void DetectByteExtractRegister (void)
Registers the keyword handlers for the "byte_extract" keyword.
Definition at line 101 of file detect-byte-extract.c.
References SigTableElmt_::AppLayerMatch, DETECT_BYTE_EXTRACT, DetectByteExtractFree(), DetectByteExtractRegisterTests(), DetectByteExtractSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
SigMatch* DetectByteExtractRetrieveSMVar (const char * arg, Signature * s)
Lookup the SigMatch for a named byte_extract variable.
Parameters
arg The name of the byte_extract variable to lookup.
s Pointer the signature to look in.
Return values
A pointer to the SigMatch if found, otherwise NULL.
Definition at line 781 of file detect-byte-extract.c.
References SigMatch_::ctx, DETECT_BYTE_EXTRACT, DETECT_SM_LIST_MAX, DetectByteExtractData_::name, SigMatch_::next, Signature_::sm_lists, and SigMatch_::type.
Referenced by DetectBytejumpSetup(), DetectBytetestSetup(), and DetectIsdataatSetup().
int DetectByteExtractSetup (DetectEngineCtx * de_ctx, Signature * s, char * arg)
The setup function for the byte_extract keyword for a signature.
Parameters
de_ctx Pointer to the detection engine context.
s Pointer to signature for the current Signature being parsed from the rules.
m Pointer to the head of the SigMatch for the current rule being parsed.
arg Pointer to the string holding the keyword value.
Return values
0 On success.
-1 On failure.
Definition at line 543 of file detect-byte-extract.c.
References Signature_::alproto, ALPROTO_DCERPC, ALPROTO_UNKNOWN, AppLayerHtpEnableResponseBodyCallback(), DetectByteExtractData_::base, DetectEngineCtx_::byte_extract_max_local_id, SigMatch_::ctx, data, DETECT_BYTE_EXTRACT, DETECT_BYTE_EXTRACT_BASE_DEC, DETECT_BYTE_EXTRACT_BASE_HEX, DETECT_BYTE_EXTRACT_BASE_OCT, DETECT_BYTE_EXTRACT_ENDIAN_DCE, DETECT_BYTE_EXTRACT_FLAG_RELATIVE, DETECT_BYTE_EXTRACT_FLAG_STRING, DETECT_BYTEJUMP, DETECT_BYTETEST, DETECT_CONTENT, DETECT_CONTENT_RELATIVE_NEXT, DETECT_ISDATAAT, DETECT_PCRE, DETECT_PCRE_RELATIVE_NEXT, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_NOTSET, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectByteExtractFree(), DetectByteExtractData_::endian, DetectPcreData_::flags, DetectByteExtractData_::flags, DetectContentData_::flags, Signature_::flags, Signature_::list, DetectByteExtractData_::local_id, SC_ERR_CONFLICTING_RULE_KEYWORDS, SC_ERR_INVALID_SIGNATURE, SCLogError, SIG_FLAG_APPLAYER, SigMatchAlloc(), SigMatchAppendSMToList(), SigMatchGetLastSMFromLists(), SigMatchListSMBelongsTo(), Signature_::sm_lists_tail, and SigMatch_::type.
Referenced by DetectByteExtractRegister().