suricata: src/detect-mark.h File Reference
detect-mark.h File Reference
#include "decode.h"
#include "detect.h"
Data Structures
struct DetectMarkData_
Typedefs
typedef struct DetectMarkData_ DetectMarkData
Functions
void DetectMarkRegister (void)
Registration function for nfq_set_mark: keyword.
void MarkRegisterTests (void)
this function registers unit tests for Mark
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Based on detect-mark.h by Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Implements the nfq_set_mark keyword
Definition in file detect-mark.h.
Typedef Documentation
DetectMarkData
A typedef for DetectMarkData_
Function Documentation
void DetectMarkRegister (void)
Registration function for nfq_set_mark: keyword.
Registration function for nfq_set_mark: keyword
Definition at line 53 of file detect-mark.c.
References DETECT_MARK, DetectMarkDataFree(), DetectMarkPacket(), SigTableElmt_::Free, MarkRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void MarkRegisterTests (void)
this function registers unit tests for Mark
This function registers unit tests for Mark
Definition at line 345 of file detect-mark.c.
Referenced by DetectMarkRegister().