suricata: src/detect-csum.h File Reference
detect-csum.h File Reference
Data Structures
struct DetectCsumData_
Macros
#define DETECT_CSUM_VALID "valid"
#define DETECT_CSUM_INVALID "invalid"
Typedefs
typedef struct DetectCsumData_ DetectCsumData
Functions
void DetectCsumRegister (void)
Registers handlers for all the checksum keywords. The checksum keywords that are registered are ipv4-sum, tcpv4-csum, tcpv6-csum, udpv4-csum, udpv6-csum, icmpv4-csum and icmpv6-csum.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-csum.h.
Macro Definition Documentation
#define DETECT_CSUM_INVALID "invalid"
Definition at line 28 of file detect-csum.h.
#define DETECT_CSUM_VALID "valid"
Definition at line 27 of file detect-csum.h.
Typedef Documentation
typedef struct DetectCsumData_ DetectCsumData
Function Documentation
void DetectCsumRegister (void)
Registers handlers for all the checksum keywords. The checksum keywords that are registered are ipv4-sum, tcpv4-csum, tcpv6-csum, udpv4-csum, udpv6-csum, icmpv4-csum and icmpv6-csum.
Each of the checksum keywords implemented here takes 2 arguments - "valid" or "invalid". If the rule keyword in the signature is specified as "valid", the Match function would return TRUE if the checksum for that particular packet and protocol is valid. Similarly for "invalid".
The Setup functions takes 4 arguments -
DetectEngineCtx * (de_ctx) - A pointer to the detection engine context Signature *(s) - Pointer to signature for the current Signature being parsed from the rules SigMatchCtx * (m) - Pointer to the head of the SigMatchs added to the current Signature being parsed char * (csum_str) - Pointer to a string holding the keyword value
The Setup function returns 0 if it successfully parses the keyword value, and -1 otherwise.
The Match function takes 5 arguments -
ThreadVars * (t) - Pointer to the tv for the detection module instance DetectEngineThreadCtx * (det_ctx) - Pointer to the detection engine thread context Packet * (p) - Pointer to the Packet currently being handled Signature * (s) - Pointer to the Signature, the packet is being currently matched with SigMatchCtx * (m) - Pointer to the keyword structure from the above Signature, the Packet is being currently matched with
The Match function returns 1 if the Packet contents match the keyword, and 0 otherwise
The Free function takes a single argument -
void * (ptr) - Pointer to the DetectCsumData for a keyword
Definition at line 128 of file detect-csum.c.
References DETECT_ICMPV4_CSUM, DETECT_ICMPV6_CSUM, DETECT_IPV4_CSUM, DETECT_TCPV4_CSUM, DETECT_TCPV6_CSUM, DETECT_UDPV4_CSUM, DETECT_UDPV6_CSUM, DetectCsumRegisterTests(), DetectICMPV4CsumFree(), DetectICMPV4CsumMatch(), DetectICMPV6CsumFree(), DetectICMPV6CsumMatch(), DetectIPV4CsumFree(), DetectIPV4CsumMatch(), DetectTCPV4CsumFree(), DetectTCPV4CsumMatch(), DetectTCPV6CsumFree(), DetectTCPV6CsumMatch(), DetectUDPV4CsumFree(), DetectUDPV4CsumMatch(), DetectUDPV6CsumFree(), DetectUDPV6CsumMatch(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().