suricata: src/detect-parse.c File Reference
detect-parse.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-address.h"
#include "detect-engine-port.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "detect-content.h"
#include "detect-pcre.h"
#include "detect-uricontent.h"
#include "detect-reference.h"
#include "detect-ipproto.h"
#include "detect-flow.h"
#include "detect-app-layer-protocol.h"
#include "detect-engine-apt-event.h"
#include "detect-lua.h"
#include "detect-app-layer-event.h"
#include "pkt-var.h"
#include "host.h"
#include "util-profiling.h"
#include "decode.h"
#include "flow.h"
#include "util-rule-vars.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "app-layer.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "util-classification-config.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
#include "string.h"
#include "detect-parse.h"
#include "detect-engine-iponly.h"
#include "app-layer-detect-proto.h"
Data Structures
struct SigDuplWrapper_
We use this as data to the hash table DetectEngineCtx->dup_sig_hash_table.
struct SignatureParser_
Macros
#define CONFIG_PARTS 8
#define CONFIG_ACTION 0
#define CONFIG_PROTO 1
#define CONFIG_SRC 2
#define CONFIG_SP 3
#define CONFIG_DIREC 4
#define CONFIG_DST 5
#define CONFIG_DP 6
#define CONFIG_OPTS 7
#define CONFIG_PCRE_SRCDST
#define CONFIG_PCRE_PORT
#define CONFIG_PCRE
#define OPTION_PARTS 3
#define OPTION_PCRE "^\\s*([A-z_0-9-\\.]+)(?:\\s*\\:\\s*(.*)(?<!\\\\))?\\s*;\\s*(?:\\s*(.*))?\\s*$"
#define MAX_SUBSTRINGS 30
#define MAX_SUBSTRINGS 30
Typedefs
typedef struct SigDuplWrapper_ SigDuplWrapper
We use this as data to the hash table DetectEngineCtx->dup_sig_hash_table.
typedef struct SignatureParser_ SignatureParser
Functions
int DetectEngineContentModifierBufferSetup (DetectEngineCtx *de_ctx, Signature *s, char *arg, uint8_t sm_type, uint8_t sm_list, AppProto alproto, void(*CustomCallback)(Signature *s))
uint32_t DbgGetSrcPortAnyCnt (void)
uint32_t DbgGetDstPortAnyCnt (void)
SigMatch * SigMatchAlloc (void)
void SigMatchFree (SigMatch *sm)
free a SigMatch
SigTableElmt * SigTableGet (char *name)
void SigMatchAppendSMToList (Signature *s, SigMatch *new, int list)
Append a SigMatch to the list type.
void SigMatchRemoveSMFromList (Signature *s, SigMatch *sm, int sm_list)
SigMatch * SigMatchGetLastSMFromLists (Signature *s, int args,...)
Returns the sm with the largest index (added latest) from all the lists.
void SigMatchTransferSigMatchAcrossLists (SigMatch *sm, SigMatch **src_sm_list, SigMatch **src_sm_list_tail, SigMatch **dst_sm_list, SigMatch **dst_sm_list_tail)
int SigMatchListSMBelongsTo (Signature *s, SigMatch *key_sm)
void SigParsePrepare (void)
int SigParseAddress (const DetectEngineCtx *de_ctx, Signature *s, const char *addrstr, char flag)
Parse address string and update signature.
int SigParseProto (Signature *s, const char *protostr)
Parses the protocol supplied by the Signature.
int SigParseAction (Signature *s, const char *action)
Parses the action that has been used by the Signature and allots it to its Signature instance.
int SigParse (DetectEngineCtx *de_ctx, Signature *s, char *sigstr, uint8_t addrs_direction)
parse a signature
Signature * SigAlloc (void)
void SigFree (Signature *s)
int SigValidate (DetectEngineCtx *de_ctx, Signature *s)
Signature * SigInit (DetectEngineCtx *de_ctx, char *sigstr)
Parses a signature and adds it to the Detection Engine Context.
void DetectParseDupSigFreeFunc (void *data)
The hash free function to be the used by the hash table - DetectEngineCtx->dup_sig_hash_table.
uint32_t DetectParseDupSigHashFunc (HashListTable *ht, void *data, uint16_t datalen)
The hash function to be the used by the hash table - DetectEngineCtx->dup_sig_hash_table.
char DetectParseDupSigCompareFunc (void *data1, uint16_t len1, void *data2, uint16_t len2)
The Compare function to be used by the hash table - DetectEngineCtx->dup_sig_hash_table.
int DetectParseDupSigHashInit (DetectEngineCtx *de_ctx)
Initializes the hash table that is used to cull duplicate sigs.
void DetectParseDupSigHashFree (DetectEngineCtx *de_ctx)
Frees the hash table that is used to cull duplicate sigs.
Signature * DetectEngineAppendSig (DetectEngineCtx *de_ctx, char *sigstr)
Parse and append a Signature into the Detection Engine Context signature list.
void SigParseRegisterTests (void)
Variables
int sc_set_caps
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
signature parser
Definition in file detect-parse.c.
Macro Definition Documentation
#define CONFIG_ACTION 0
Definition at line 94 of file detect-parse.c.
#define CONFIG_DIREC 4
Definition at line 98 of file detect-parse.c.
#define CONFIG_DP 6
Definition at line 100 of file detect-parse.c.
#define CONFIG_DST 5
Definition at line 99 of file detect-parse.c.
#define CONFIG_OPTS 7
Definition at line 101 of file detect-parse.c.
#define CONFIG_PARTS 8
Definition at line 92 of file detect-parse.c.
#define CONFIG_PCRE
Value:
"^([A-z]+)\\s+([A-z0-9\\-]+)\\s+" \
                    CONFIG_PCRE_SRCDST \
                    "\\s+"\
                    CONFIG_PCRE_PORT \
                    "\\s+(-\\>|\\<\\>|\\<\\-)\\s+" \
                    CONFIG_PCRE_SRCDST \
                    "\\s+" \
                    CONFIG_PCRE_PORT \
                    "(?:\\s+\\((.*)?(?:\\s*)\\))?(?:(?:\\s*)\\n)?\\s*$"
Definition at line 118 of file detect-parse.c.
Referenced by SigParsePrepare().
#define CONFIG_PCRE_PORT
Value:
"(" \
                            "[\\:A-z0-9_\\$\\!,]+"\
                           "|"\
                            "\\[[\\:A-z0-9_\\$\\!,\\s]+\\]"\
                           ")"
Definition at line 111 of file detect-parse.c.
#define CONFIG_PCRE_SRCDST
Value:
"(" \
                            "[\\[\\]A-z0-9\\.\\:_\\$\\!\\-,\\/]+" \
                           "|" \
                            "\\[[\\[\\]A-z0-9\\.\\:_\\$\\!\\-,\\/\\s]+\\]"\
                           ")"
Definition at line 104 of file detect-parse.c.
#define CONFIG_PROTO 1
Definition at line 95 of file detect-parse.c.
#define CONFIG_SP 3
Definition at line 97 of file detect-parse.c.
#define CONFIG_SRC 2
Definition at line 96 of file detect-parse.c.
#define MAX_SUBSTRINGS 30
#define MAX_SUBSTRINGS 30
#define OPTION_PARTS 3
Definition at line 127 of file detect-parse.c.
#define OPTION_PCRE "^\\s*([A-z_0-9-\\.]+)(?:\\s*\\:\\s*(.*)(?<!\\\\))?\\s*;\\s*(?:\\s*(.*))?\\s*$"
Definition at line 128 of file detect-parse.c.
Referenced by SigParsePrepare().
Typedef Documentation
typedef struct SigDuplWrapper_ SigDuplWrapper
We use this as data to the hash table DetectEngineCtx->dup_sig_hash_table.
typedef struct SignatureParser_ SignatureParser
helper structure for sig parsing
Function Documentation
uint32_t DbgGetDstPortAnyCnt (void)
Definition at line 235 of file detect-parse.c.
uint32_t DbgGetSrcPortAnyCnt (void)
Definition at line 230 of file detect-parse.c.
Signature* DetectEngineAppendSig (DetectEngineCtx * de_ctx, char * sigstr)
Parse and append a Signature into the Detection Engine Context signature list.
   If the signature is bidirectional it should append two signatures
   (with the addresses switched) into the list.  Also handle duplicate
   signatures.  In case of duplicate sigs, use the ones that have the
   latest revision.  We use the sid and the msg to identifiy duplicate
   sigs.  If 2 sigs have the same sid and gid, they are duplicates.
Parameters
de_ctx Pointer to the Detection Engine Context.
sigstr Pointer to a character string containing the signature to be parsed.
sig_file Pointer to a character string containing the filename from which signature is read
lineno Line number from where signature is read
Return values
Pointer to the head Signature in the detection engine ctx sig_list on success; NULL on failure.
In DetectEngineAppendSig(), the signatures are prepended and we always return the first one so if the signature is bidirectional, the returned sig will point through "next" ptr to the cloned signatures with the switched addresses
Definition at line 1813 of file detect-parse.c.
References Signature_::init_flags, Signature_::next, SC_ERR_DUPLICATE_SIG, SCLogError, SCLogWarning, SIG_FLAG_INIT_BIDIREC, DetectEngineCtx_::sig_list, SigFree(), and SigInit().
int DetectEngineContentModifierBufferSetup (DetectEngineCtx * de_ctx, Signature * s, char * arg, uint8_t sm_type, uint8_t sm_list, AppProto alproto, void(*)(Signature *s) CustomCallback)
Definition at line 142 of file detect-parse.c.
References Signature_::alproto, ALPROTO_UNKNOWN, SigMatch_::ctx, DETECT_CONTENT, DETECT_CONTENT_DISTANCE, DETECT_CONTENT_RAWBYTES, DETECT_CONTENT_RELATIVE_NEXT, DETECT_CONTENT_WITHIN, DETECT_PCRE, DETECT_PCRE_RELATIVE_NEXT, DETECT_SM_LIST_NOTSET, DETECT_SM_LIST_PMATCH, DetectPcreData_::flags, DetectContentData_::flags, Signature_::flags, Signature_::list, SigMatch_::prev, SC_ERR_CONFLICTING_RULE_KEYWORDS, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_SIGNATURE, SCLogError, SIG_FLAG_APPLAYER, sigmatch_table, SigMatchGetLastSMFromLists(), SigMatchTransferSigMatchAcrossLists(), Signature_::sm_lists, Signature_::sm_lists_tail, and SigMatch_::type.
Referenced by DetectHttpClientBodySetup(), DetectHttpHeaderSetup(), DetectHttpHHSetup(), DetectHttpHRHSetup(), DetectHttpRawHeaderSetup(), DetectHttpServerBodySetup(), DetectHttpUASetup(), and DetectHttpUriSetup().
char DetectParseDupSigCompareFunc (void * data1, uint16_t len1, void * data2, uint16_t len2)
The Compare function to be used by the hash table - DetectEngineCtx->dup_sig_hash_table.
Parameters
data1 Pointer to the first SigDuplWrapper.
len1 Not used.
data2 Pointer to the second SigDuplWrapper.
len2 Not used.
Return values
1 If the 2 SigDuplWrappers sent as args match.
0 If the 2 SigDuplWrappers sent as args do not match.
Definition at line 1617 of file detect-parse.c.
References Signature_::gid, Signature_::id, and SigDuplWrapper_::s.
Referenced by DetectParseDupSigHashInit().
void DetectParseDupSigFreeFunc (void * data)
The hash free function to be the used by the hash table - DetectEngineCtx->dup_sig_hash_table.
Parameters
data Pointer to the data, in our case SigDuplWrapper to be freed.
Definition at line 1580 of file detect-parse.c.
References SCFree.
Referenced by DetectParseDupSigHashInit().
void DetectParseDupSigHashFree (DetectEngineCtx * de_ctx)
Frees the hash table that is used to cull duplicate sigs.
Parameters
de_ctx Pointer to the detection engine context that holds this table.
Definition at line 1658 of file detect-parse.c.
References DetectEngineCtx_::dup_sig_hash_table, and HashListTableFree().
Referenced by DetectEngineCtxFree(), and SigLoadSignatures().
uint32_t DetectParseDupSigHashFunc (HashListTable * ht, void * data, uint16_t datalen)
The hash function to be the used by the hash table - DetectEngineCtx->dup_sig_hash_table.
Parameters
ht Pointer to the hash table.
data Pointer to the data, in our case SigDuplWrapper.
datalen Not used in our case.
Return values
sw->s->id The generated hash value.
Definition at line 1598 of file detect-parse.c.
References HashListTable_::array_size, Signature_::id, and SigDuplWrapper_::s.
Referenced by DetectParseDupSigHashInit().
int DetectParseDupSigHashInit (DetectEngineCtx * de_ctx)
Initializes the hash table that is used to cull duplicate sigs.
Parameters
de_ctx Pointer to the detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 1641 of file detect-parse.c.
References DetectParseDupSigCompareFunc(), DetectParseDupSigFreeFunc(), DetectParseDupSigHashFunc(), DetectEngineCtx_::dup_sig_hash_table, and HashListTableInit().
Signature* SigAlloc (void)
Definition at line 873 of file detect-parse.c.
References DETECT_SM_LIST_NOTSET, Signature_::list, Signature_::prio, SCMalloc, and unlikely.
void SigFree (Signature * s)
Definition at line 931 of file detect-parse.c.
References Signature_::addr_dst_match4, Signature_::addr_dst_match6, Signature_::addr_src_match4, Signature_::addr_src_match6, Signature_::CidrDst, Signature_::CidrSrc, DETECT_SM_LIST_MAX, DetectAddressHeadCleanup(), DetectPortCleanupList(), Signature_::dp, Signature_::dst, IPOnlyCIDRListFree(), Signature_::msg, SigMatch_::next, SCFree, SigMatchFree(), Signature_::sm_lists, Signature_::sp, and Signature_::src.
Referenced by DetectEngineAppendSig(), SigCleanSignatures(), and SigInit().
Signature* SigInit (DetectEngineCtx * de_ctx, char * sigstr)
Parses a signature and adds it to the Detection Engine Context.
Parameters
de_ctx Pointer to the Detection Engine Context.
sigstr Pointer to a character string containing the signature to be parsed.
Return values
Pointer to the Signature instance on success; NULL on failure.
Definition at line 1542 of file detect-parse.c.
References Signature_::init_flags, Signature_::next, SCEnter, SCReturnPtr, SIG_DIREC_NORMAL, SIG_DIREC_SWITCHED, SIG_FLAG_INIT_BIDIREC, SigFree(), and DetectEngineCtx_::signum.
Referenced by DetectEngineAppendSig().
SigMatch* SigMatchAlloc (void)
Definition at line 240 of file detect-parse.c.
References SigMatch_::next, SigMatch_::prev, SCMalloc, and unlikely.
Referenced by DetectAppLayerProtocolSetup(), DetectByteExtractSetup(), DetectBytejumpSetup(), DetectBytetestSetup(), DetectContentSetup(), DetectFlowvarPostMatchSetup(), DetectIsdataatSetup(), DetectRpcSetup(), DetectSslStateSetup(), and DetectWindowSetup().
void SigMatchAppendSMToList (Signature * s, SigMatch * new, int list)
Append a SigMatch to the list type.
Parameters
s Signature.
new The sig match to append.
list The list to append to.
Definition at line 296 of file detect-parse.c.
References SigMatch_::idx, SigMatch_::next, SigMatch_::prev, Signature_::sm_cnt, Signature_::sm_lists, and Signature_::sm_lists_tail.
Referenced by DetectAppLayerProtocolSetup(), DetectByteExtractSetup(), DetectBytejumpSetup(), DetectBytetestSetup(), DetectContentSetup(), DetectFlowvarPostMatchSetup(), DetectIsdataatSetup(), DetectRpcSetup(), DetectSslStateSetup(), and DetectWindowSetup().
void SigMatchFree (SigMatch * sm)
free a SigMatch
Parameters
sm SigMatch to free.
free the ctx, for that we call the Free func
Definition at line 255 of file detect-parse.c.
References SigMatch_::ctx, SigTableElmt_::Free, SCFree, sigmatch_table, and SigMatch_::type.
Referenced by DetectIPProtoRemoveAllSMs(), and SigFree().
SigMatch* SigMatchGetLastSMFromLists (Signature * s, int args, ...)
Returns the sm with the largest index (added latest) from all the lists.
Return values
Pointer to Last sm.
Definition at line 357 of file detect-parse.c.
References BUG_ON, SigMatch_::idx, SC_ERR_INVALID_ARGUMENTS, and SCLogError.
Referenced by DetectByteExtractSetup(), DetectBytejumpSetup(), DetectBytetestSetup(), DetectEngineContentModifierBufferSetup(), DetectIsdataatSetup(), and SigValidate().
int SigMatchListSMBelongsTo (Signature * s, SigMatch * key_sm)
Definition at line 422 of file detect-parse.c.
References DETECT_SM_LIST_MAX, SigMatch_::next, SC_ERR_INVALID_SIGNATURE, SCLogError, and Signature_::sm_lists.
Referenced by DetectByteExtractSetup(), DetectBytejumpSetup(), DetectBytetestSetup(), DetectIsdataatSetup(), DetectSetFastPatternAndItsId(), EngineAnalysisFP(), and EngineAnalysisRules().
void SigMatchRemoveSMFromList (Signature * s, SigMatch * sm, int sm_list)
Definition at line 315 of file detect-parse.c.
References SigMatch_::next, SigMatch_::prev, Signature_::sm_lists, and Signature_::sm_lists_tail.
Referenced by DetectIPProtoRemoveAllSMs().
void SigMatchTransferSigMatchAcrossLists (SigMatch * sm, SigMatch ** src_sm_list, SigMatch ** src_sm_list_tail, SigMatch ** dst_sm_list, SigMatch ** dst_sm_list_tail)
Definition at line 390 of file detect-parse.c.
References SigMatch_::next, and SigMatch_::prev.
Referenced by DetectEngineContentModifierBufferSetup().
int SigParse (DetectEngineCtx * de_ctx, Signature * s, char * sigstr, uint8_t addrs_direction)
parse a signature
Parameters
de_ctx detection engine ctx to add it to
s memory structure to store the signature in
sigstr the raw signature as a null terminated string
addrs_direction direction (for bi-directional sigs)
-1 parse error
0 ok
Definition at line 830 of file detect-parse.c.
References DetectIPProtoRemoveAllSMs(), SignatureParser_::opts, SCEnter, SCLogDebug, SCReturnInt, and Signature_::sig_str.
int SigParseAction (Signature * s, const char * action)
Parses the action that has been used by the Signature and allots it to its Signature instance.
Parameters
s Pointer to the Signature instance to which the action belongs.
action Pointer to the action string used by the Signature.
Return values
0 On successfully parsing the action string and adding it to the Signature.
-1 On failure.
Definition at line 702 of file detect-parse.c.
References Signature_::action, ACTION_ALERT, ACTION_DROP, ACTION_PASS, ACTION_REJECT, ACTION_REJECT_BOTH, ACTION_REJECT_DST, SC_ERR_INVALID_ACTION, and SCLogError.
int SigParseAddress (const DetectEngineCtx * de_ctx, Signature * s, const char * addrstr, char flag)
Parse address string and update signature.
Return values
0 ok, -1 error
Definition at line 559 of file detect-parse.c.
References DetectAddressParse(), Signature_::dst, Signature_::flags, SCLogDebug, SIG_FLAG_DST_ANY, SIG_FLAG_SRC_ANY, and Signature_::src.
void SigParsePrepare (void)
Definition at line 440 of file detect-parse.c.
References CONFIG_PCRE, OPTION_PCRE, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, and SCLogError.
Referenced by RunUnittests().
int SigParseProto (Signature * s, const char * protostr)
Parses the protocol supplied by the Signature.
   http://www.iana.org/assignments/protocol-numbers
Parameters
s Pointer to the Signature instance to which the parsed protocol has to be added.
protostr Pointer to the character string containing the protocol name.
Return values
0 On successfully parsing the protocl sent as the argument.
-1 On failure
Definition at line 597 of file detect-parse.c.
References Signature_::alproto, ALPROTO_UNKNOWN, AppLayerGetProtoByName(), DETECT_PROTO_ONLY_PKT, DETECT_PROTO_ONLY_STREAM, DetectProtoParse(), DetectProto_::flags, Signature_::flags, Signature_::proto, SC_ERR_UNKNOWN_PROTOCOL, SCEnter, SCLogError, SCReturnInt, SIG_FLAG_APPLAYER, SIG_FLAG_REQUIRE_PACKET, and SIG_FLAG_REQUIRE_STREAM.
void SigParseRegisterTests (void)
Definition at line 3371 of file detect-parse.c.
Referenced by SigRegisterTests().
SigTableElmt* SigTableGet (char * name)
Definition at line 270 of file detect-parse.c.
References SigTableElmt_::alias, DETECT_TBLSIZE, SigTableElmt_::name, and sigmatch_table.
int SigValidate (DetectEngineCtx * de_ctx, Signature * s)
Definition at line 1098 of file detect-parse.c.
References Signature_::alproto, ALPROTO_HTTP, ALPROTO_SMTP, ALPROTO_UNKNOWN, BUG_ON, DetectContentData_::content, DetectContentData_::content_len, SigMatch_::ctx, DETECT_AL_APP_LAYER_PROTOCOL, DETECT_CONTENT, DETECT_CONTENT_DEPTH, DETECT_CONTENT_NOCASE, DETECT_CONTENT_OFFSET, DETECT_FLOW, DETECT_REPLACE, DETECT_SM_LIST_AMATCH, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_MATCH, DETECT_SM_LIST_MAX, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectLuaPostSetup(), DetectFlowData_::flags, DetectContentData_::flags, Signature_::flags, FLOW_PKT_TOCLIENT, FLOW_PKT_TOSERVER, SigMatch_::next, SigMatch_::prev, DetectProto_::proto, Signature_::proto, SC_ERR_CONFLICTING_RULE_KEYWORDS, SC_ERR_INVALID_SIGNATURE, SCEnter, SCLogError, SCLogWarning, SCReturnInt, SIG_FLAG_REQUIRE_PACKET, SIG_FLAG_REQUIRE_STREAM, SIG_FLAG_TOCLIENT, SIG_FLAG_TOSERVER, SigMatchGetLastSMFromLists(), Signature_::sm_lists, Signature_::sm_lists_tail, and SigMatch_::type.
Variable Documentation
int sc_set_caps
set caps or not
Definition at line 239 of file suricata.c.
Referenced by main().