suricata: src/detect-engine-address-ipv6.h File Reference
detect-engine-address-ipv6.h File Reference
Functions
int AddressIPv6Lt (Address *, Address *)
Compares 2 ipv6 addresses and returns if the first address(a) is less than the second address(b) or not.
int AddressIPv6Gt (Address *, Address *)
Compares 2 ipv6 addresses and returns if the first address(a) is greater than the second address(b) or not.
int AddressIPv6Eq (Address *, Address *)
Compares 2 ipv6 addresses and returns if the addresses are equal or not.
int AddressIPv6Le (Address *, Address *)
Compares 2 ipv6 addresses and returns if the first address(a) is less than or equal to the second address(b) or not.
int AddressIPv6Ge (Address *, Address *)
Compares 2 ipv6 addresses and returns if the first address(a) is greater than or equal to the second address(b) or not.
int DetectAddressCutNotIPv6 (DetectAddress *, DetectAddress **)
Cuts and returns an address range, which is the complement of the address range that is supplied as the argument.
int DetectAddressCmpIPv6 (DetectAddress *a, DetectAddress *b)
Compares 2 addresses(address ranges) and returns the relationship between the 2 addresses.
int DetectAddressCutIPv6 (DetectEngineCtx *, DetectAddress *, DetectAddress *, DetectAddress **)
int DetectAddressJoinIPv6 (DetectEngineCtx *, DetectAddress *, DetectAddress *)
Extends a target address range if the the source address range is wider than the target address range on either sides.
void DetectAddressIPv6Tests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-engine-address-ipv6.h.
Function Documentation
int AddressIPv6Eq (Address * a, Address * b)
Compares 2 ipv6 addresses and returns if the addresses are equal or not.
Parameters
a The first ipv6 address to be compared.
b The second ipv6 address to be compared.
Return values
1 If a == b.
0 Otherwise.
Definition at line 127 of file detect-engine-address-ipv6.c.
Referenced by AddressIPv6Ge(), AddressIPv6Le(), and DetectAddressCmpIPv6().
int AddressIPv6Ge (Address * a, Address * b)
Compares 2 ipv6 addresses and returns if the first address(a) is greater than or equal to the second address(b) or not.
Parameters
a The first ipv6 address to be compared.
b The second ipv6 address to be compared.
Return values
1 If a >= b.
0 Otherwise, i.e. a < b.
Definition at line 193 of file detect-engine-address-ipv6.c.
References AddressIPv6Eq(), and AddressIPv6Gt().
Referenced by DetectAddressCmpIPv6(), and DetectAddressMatch().
int AddressIPv6Gt (Address * a, Address * b)
Compares 2 ipv6 addresses and returns if the first address(a) is greater than the second address(b) or not.
Parameters
a The first ipv6 address to be compared.
b The second ipv6 address to be compared.
Return values
1 If a > b.
0 Otherwise, i.e. a <= b.
Definition at line 89 of file detect-engine-address-ipv6.c.
Referenced by AddressIPv6Ge(), DetectAddressCmpIPv6(), DetectAddressJoinIPv6(), and DetectAddressParseString().
int AddressIPv6Le (Address * a, Address * b)
Compares 2 ipv6 addresses and returns if the first address(a) is less than or equal to the second address(b) or not.
Parameters
a The first ipv6 address to be compared.
b The second ipv6 address to be compared.
Return values
1 If a <= b.
0 Otherwise, i.e. a > b.
Definition at line 161 of file detect-engine-address-ipv6.c.
References AddressIPv6Eq(), and AddressIPv6Lt().
Referenced by DetectAddressCmpIPv6(), and DetectAddressMatch().
int AddressIPv6Lt (Address * a, Address * b)
Compares 2 ipv6 addresses and returns if the first address(a) is less than the second address(b) or not.
Parameters
a The first ipv6 address to be compared.
b The second ipv6 address to be compared.
Return values
1 If a < b.
0 Otherwise, i.e. a >= b.
Definition at line 51 of file detect-engine-address-ipv6.c.
Referenced by AddressIPv6Le(), DetectAddressCmpIPv6(), and DetectAddressJoinIPv6().
int DetectAddressCmpIPv6 (DetectAddress * a, DetectAddress * b)
Compares 2 addresses(address ranges) and returns the relationship between the 2 addresses.
Parameters
a Pointer to the first address instance to be compared.
b Pointer to the second address instance to be compared.
Return values
ADDRESS_EQ If the 2 address ranges a and b, are equal.
ADDRESS_ES b encapsulates a. b_ip1[...a_ip1...a_ip2...]b_ip2.
ADDRESS_EB a encapsulates b. a_ip1[...b_ip1....b_ip2...]a_ip2.
ADDRESS_LE a_ip1(...b_ip1==a_ip2...)b_ip2
ADDRESS_LT a_ip1(...b_ip1...a_ip2...)b_ip2
ADDRESS_GE b_ip1(...a_ip1==b_ip2...)a_ip2
ADDRESS_GT a_ip1 > b_ip2, i.e. the address range for 'a' starts only after the end of the address range for 'b'
Definition at line 231 of file detect-engine-address-ipv6.c.
References ADDRESS_EB, ADDRESS_EQ, ADDRESS_ER, ADDRESS_ES, ADDRESS_GE, ADDRESS_GT, ADDRESS_LE, ADDRESS_LT, AddressIPv6Eq(), AddressIPv6Ge(), AddressIPv6Gt(), AddressIPv6Le(), AddressIPv6Lt(), DetectAddress_::ip, DetectAddress_::ip2, and SCLogDebug.
Referenced by DetectAddressCmp(), and DetectAddressCutIPv6().
int DetectAddressCutIPv6 (DetectEngineCtx * , DetectAddress * , DetectAddress * , DetectAddress **)
Definition at line 358 of file detect-engine-address-ipv6.c.
References ADDRESS_EB, ADDRESS_ES, ADDRESS_GE, ADDRESS_LE, AddressIPv6EqU32(), DetectAddress_::cnt, DetectAddressCmpIPv6(), DetectAddressFree(), DetectAddressInit(), DetectPortInsertCopy(), Address_::family, DetectAddress_::ip, DetectAddress_::ip2, DetectPort_::next, DetectAddress_::port, DetectAddress_::sh, SigGroupHeadClearSigs(), and SigGroupHeadCopySigs().
int DetectAddressCutNotIPv6 (DetectAddress * a, DetectAddress ** b)
Cuts and returns an address range, which is the complement of the address range that is supplied as the argument.
   For example:
   If a = ::-2000::,
       then a = 2000::1-FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF and b = NULL
   If a = 2000::1-FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF,
       then a = ::-2000:: and b = NULL
   If a = 2000::1-20FF::2,
       then a = ::-2000:: and
            b = 20FF::3-FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF
Parameters
a Pointer to an address range (DetectAddress) instance whose complement has to be returned in a and b.
b Pointer to DetectAddress pointer, that will be supplied back with a new DetectAddress instance, if the complement demands so.
Return values
0 On success.
-1 On failure.
Definition at line 871 of file detect-engine-address-ipv6.c.
References DetectAddressInit(), Address_::family, DetectAddress_::ip, and DetectAddress_::ip2.
void DetectAddressIPv6Tests (void)
Definition at line 2229 of file detect-engine-address-ipv6.c.
Referenced by DetectAddressTests().
int DetectAddressJoinIPv6 (DetectEngineCtx * de_ctx, DetectAddress * target, DetectAddress * source)
Extends a target address range if the the source address range is wider than the target address range on either sides.
   Every address is a range, i.e. address->ip1....address->ip2.  For
   example 2000::-2010::
   if source->ip1 is smaller than target->ip1, it indicates that the
   source's left address limit is greater(range wise) than the target's
   left address limit, and hence we reassign the target's left address
   limit to source's left address limit.
   Similary if source->ip2 is greater than target->ip2, it indicates that
   the source's right address limit is greater(range wise) than the
   target's right address limit, and hence we reassign the target's right
   address limit to source's right address limit.
Parameters
de_ctx Pointer to the detection engine context.
target Pointer to the target DetectAddress instance that has to be updated.
source Pointer to the source DetectAddress instance that is used to decided whether we extend the target's address range.
Return values
0 On success.
-1 On failure.
Definition at line 944 of file detect-engine-address-ipv6.c.
References AddressIPv6Gt(), AddressIPv6Lt(), COPY_ADDRESS, DetectAddress_::ip, and DetectAddress_::ip2.
Referenced by DetectAddressJoin().