suricata: src/detect-replace.c File Reference
detect-replace.c File Reference
#include "suricata-common.h"
#include "runmodes.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-content.h"
#include "detect-uricontent.h"
#include "detect-byte-extract.h"
#include "detect-replace.h"
#include "app-layer.h"
#include "detect-engine-mpm.h"
#include "detect-engine.h"
#include "detect-engine-state.h"
#include "util-checksum.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "flow-var.h"
#include "util-debug.h"
#include "pkt-var.h"
#include "host.h"
#include "util-profiling.h"
Functions
void DetectReplaceRegisterTests (void)
this function registers unit tests for DetectContent
void DetectReplaceRegister (void)
DetectReplaceList * DetectReplaceAddToList (DetectReplaceList *replist, uint8_t *found, DetectContentData *cd)
void DetectReplaceExecuteInternal (Packet *p, DetectReplaceList *replist)
void DetectReplaceFreeInternal (DetectReplaceList *replist)
Variables
int run_mode
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Replace part of the detection engine.
If previous filter is of content type, replace can be used to change the matched part to a new value.
Definition in file detect-replace.c.
Function Documentation
DetectReplaceList* DetectReplaceAddToList (DetectReplaceList * replist, uint8_t * found, DetectContentData * cd)
Definition at line 162 of file detect-replace.c.
References DetectReplaceList_::cd, DetectContentData_::content_len, DetectReplaceList_::found, DetectReplaceList_::next, DetectContentData_::replace_len, SCLogDebug, SCMalloc, and unlikely.
Referenced by DetectEngineContentInspection().
void DetectReplaceExecuteInternal (Packet * p, DetectReplaceList * replist)
Definition at line 184 of file detect-replace.c.
References DetectReplaceList_::cd, Packet_::flags, DetectReplaceList_::found, DetectReplaceList_::next, PKT_STREAM_MODIFIED, ReCalculateChecksum(), DetectContentData_::replace, DetectContentData_::replace_len, SCFree, and SCLogDebug.
void DetectReplaceFreeInternal (DetectReplaceList * replist)
Definition at line 201 of file detect-replace.c.
References DetectReplaceList_::next, SCFree, and SCLogDebug.
void DetectReplaceRegister (void)
Definition at line 65 of file detect-replace.c.
References DETECT_REPLACE, DetectReplaceRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void DetectReplaceRegisterTests (void)
this function registers unit tests for DetectContent
Definition at line 817 of file detect-replace.c.
Referenced by DetectReplaceRegister().
Variable Documentation
int run_mode
Run mode selected
Definition at line 222 of file suricata.c.
Referenced by RunmodeGetCurrent(), RunmodeIsUnittests(), and Unified2AlertOpenFileCtx().