suricata: src/detect-isdataat.c File Reference
detect-isdataat.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-parse.h"
#include "app-layer.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "detect-isdataat.h"
#include "detect-content.h"
#include "detect-uricontent.h"
#include "flow.h"
#include "flow-var.h"
#include "util-debug.h"
#include "util-byte.h"
#include "detect-pcre.h"
#include "detect-bytejump.h"
#include "detect-byte-extract.h"
Macros
#define PARSE_REGEX "^\\s*!?([^\\s,]+)\\s*(,\\s*relative)?\\s*(,\\s*rawbytes\\s*)?\\s*$"
Regex for parsing our isdataat options.
#define MAX_SUBSTRINGS 30
Functions
int DetectIsdataatMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match isdataat on a packet.
int DetectIsdataatSetup (DetectEngineCtx *de_ctx, Signature *s, char *isdataatstr)
This function is used to add the parsed isdataatdata into the current signature.
void DetectIsdataatRegisterTests (void)
this function registers unit tests for DetectIsdataat
void DetectIsdataatFree (void *ptr)
this function will free memory associated with DetectIsdataatData
void DetectIsdataatRegister (void)
Registration function for isdataat: keyword.
DetectIsdataatData * DetectIsdataatParse (char *isdataatstr, char **offset)
This function is used to parse isdataat options passed via isdataat: keyword.
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements isdataat keyword
Definition in file detect-isdataat.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectIsdataatParse().
#define PARSE_REGEX "^\\s*!?([^\\s,]+)\\s*(,\\s*relative)?\\s*(,\\s*rawbytes\\s*)?\\s*$"
Regex for parsing our isdataat options.
Definition at line 53 of file detect-isdataat.c.
Referenced by DetectIsdataatRegister().
Function Documentation
void DetectIsdataatFree (void * ptr)
this function will free memory associated with DetectIsdataatData
Parameters
idad pointer to DetectIsdataatData
Definition at line 427 of file detect-isdataat.c.
References SCFree.
Referenced by DetectIsdataatParse(), DetectIsdataatRegister(), and DetectIsdataatSetup().
int DetectIsdataatMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match isdataat on a packet.
Todo:
We need to add support for rawbytes
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectIsdataatData
Return values
0 no match
1 match
Definition at line 112 of file detect-isdataat.c.
References DetectIsdataatData_::dataat, DetectIsdataatData_::flags, ISDATAAT_RELATIVE, Packet_::payload_len, and SCLogDebug.
Referenced by DetectIsdataatRegister().
DetectIsdataatData* DetectIsdataatParse (char * isdataatstr, char ** offset)
This function is used to parse isdataat options passed via isdataat: keyword.
Parameters
isdataatstr Pointer to the user provided isdataat options
Return values
idad pointer to DetectIsdataatData on success
NULL on failure
Definition at line 139 of file detect-isdataat.c.
References ByteExtractStringUint16(), DetectIsdataatData_::dataat, DetectIsdataatFree(), DetectIsdataatData_::flags, ISDATAAT_NEGATED, ISDATAAT_RAWBYTES, ISDATAAT_RELATIVE, MAX_SUBSTRINGS, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogError, SCMalloc, SCStrdup, and unlikely.
Referenced by DetectIsdataatSetup().
void DetectIsdataatRegister (void)
Registration function for isdataat: keyword.
Definition at line 66 of file detect-isdataat.c.
References SigTableElmt_::desc, DETECT_ISDATAAT, DetectIsdataatFree(), DetectIsdataatMatch(), DetectIsdataatRegisterTests(), DetectIsdataatSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectIsdataatRegisterTests (void)
this function registers unit tests for DetectIsdataat
Definition at line 1225 of file detect-isdataat.c.
Referenced by DetectIsdataatRegister().
int DetectIsdataatSetup (DetectEngineCtx * de_ctx, Signature * s, char * isdataatstr)
This function is used to add the parsed isdataatdata into the current signature.
Parameters
de_ctx pointer to the Detection Engine Context
s pointer to the Current Signature
isdataatstr pointer to the user provided isdataat options
Return values
0 on Success
-1 on Failure
Definition at line 250 of file detect-isdataat.c.
References Signature_::alproto, ALPROTO_HTTP, AppLayerHtpEnableResponseBodyCallback(), SigMatch_::ctx, DetectIsdataatData_::dataat, DETECT_BYTE_EXTRACT, DETECT_BYTEJUMP, DETECT_BYTETEST, DETECT_CONTENT, DETECT_CONTENT_RELATIVE_NEXT, DETECT_ISDATAAT, DETECT_PCRE, DETECT_PCRE_RELATIVE_NEXT, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_NOTSET, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectByteExtractRetrieveSMVar(), DetectIsdataatFree(), DetectIsdataatParse(), DetectIsdataatData_::flags, DetectPcreData_::flags, DetectContentData_::flags, Signature_::flags, ISDATAAT_OFFSET_BE, ISDATAAT_RELATIVE, Signature_::list, SC_ERR_INVALID_SIGNATURE, SCFree, SCLogError, SIG_FLAG_APPLAYER, SigMatchAlloc(), SigMatchAppendSMToList(), SigMatchGetLastSMFromLists(), SigMatchListSMBelongsTo(), Signature_::sm_lists_tail, and SigMatch_::type.
Referenced by DetectIsdataatRegister().