suricata: src/detect-icmp-seq.h File Reference
detect-icmp-seq.h File Reference
Data Structures
struct DetectIcmpSeqData_
Typedefs
typedef struct DetectIcmpSeqData_ DetectIcmpSeqData
Functions
void DetectIcmpSeqRegister (void)
Registration function for icmp_seq.
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Definition in file detect-icmp-seq.h.
Typedef Documentation
typedef struct DetectIcmpSeqData_ DetectIcmpSeqData
Function Documentation
void DetectIcmpSeqRegister (void)
Registration function for icmp_seq.
Definition at line 53 of file detect-icmp-seq.c.
References SigTableElmt_::desc, DETECT_ICMP_SEQ, DetectIcmpSeqFree(), DetectIcmpSeqMatch(), DetectIcmpSeqRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().