suricata: src/detect-engine-proto.c File Reference
detect-engine-proto.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "app-layer-parser.h"
#include "flow-util.h"
#include "flow-var.h"
#include "detect-engine-siggroup.h"
#include "detect-engine-state.h"
#include "util-cidr.h"
#include "util-byte.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
Functions
DetectProto * DetectProtoInit (void)
Function to initialize the protocol detection and allocate memory to the DetectProto structure.
void DetectProtoFree (DetectProto *dp)
Free a DetectProto object.
int DetectProtoParse (DetectProto *dp, char *str)
Parses a protocol sent as a string.
int DetectProtoContainsProto (DetectProto *dp, int proto)
see if a DetectProto contains a certain proto
void DetectProtoTests (void)
this function registers unit tests for DetectProto
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Proto part of the detection engine.
Todo:
move this out of the detection plugin structure
Definition in file detect-engine-proto.c.
Function Documentation
int DetectProtoContainsProto (DetectProto * dp, int proto)
see if a DetectProto contains a certain proto
Parameters
dp detect proto to inspect
proto protocol (such as IPPROTO_TCP) to look for
Return values
0 protocol not in the set
1 protocol is in the set
Definition at line 165 of file detect-engine-proto.c.
References DETECT_PROTO_ANY, DetectProto_::flags, and DetectProto_::proto.
Referenced by EngineAnalysisRules(), IPOnlyMatchPacket(), and SigMatchSignatures().
void DetectProtoFree (DetectProto * dp)
Free a DetectProto object.
Parameters
dp Pointer to the DetectProto instance to be freed
Definition at line 69 of file detect-engine-proto.c.
References SCFree.
DetectProto* DetectProtoInit (void)
Function to initialize the protocol detection and allocate memory to the DetectProto structure.
Return values
DetectProto instance pointer if successful otherwise NULL
Definition at line 54 of file detect-engine-proto.c.
References SCMalloc, and unlikely.
int DetectProtoParse (DetectProto * dp, char * str)
Parses a protocol sent as a string.
Parameters
dp Pointer to the DetectProto instance which will be updated with the incoming protocol information.
str Pointer to the string containing the protocol name.
Return values
>=0 If proto is detected, -1 otherwise.
Todo:
are numeric protocols even valid?
Definition at line 86 of file detect-engine-proto.c.
References ByteExtractStringUint8(), DETECT_PROTO_ANY, DETECT_PROTO_IPV4, DETECT_PROTO_IPV6, DETECT_PROTO_ONLY_PKT, DETECT_PROTO_ONLY_STREAM, DetectProto_::flags, DetectProto_::proto, proto, and SCLogDebug.
Referenced by SigParseProto().
void DetectProtoTests (void)
this function registers unit tests for DetectProto
Definition at line 609 of file detect-engine-proto.c.
Referenced by RunUnittests().