suricata: src/detect-bytetest.h File Reference
detect-bytetest.h File Reference
Data Structures
struct DetectBytetestData_
Macros
#define DETECT_BYTETEST_OP_LT 1
#define DETECT_BYTETEST_OP_GT 2
#define DETECT_BYTETEST_OP_EQ 3
#define DETECT_BYTETEST_OP_AND 4
#define DETECT_BYTETEST_OP_OR 5
#define DETECT_BYTETEST_OP_GE 6
#define DETECT_BYTETEST_OP_LE 7
#define DETECT_BYTETEST_BASE_UNSET 0
#define DETECT_BYTETEST_BASE_OCT 8
#define DETECT_BYTETEST_BASE_DEC 10
#define DETECT_BYTETEST_BASE_HEX 16
#define DETECT_BYTETEST_NEGOP 0x01
#define DETECT_BYTETEST_LITTLE 0x02
#define DETECT_BYTETEST_BIG 0x04
#define DETECT_BYTETEST_STRING 0x08
#define DETECT_BYTETEST_RELATIVE 0x10
#define DETECT_BYTETEST_DCE 0x20
#define DETECT_BYTETEST_VALUE_BE 0x40
#define DETECT_BYTETEST_OFFSET_BE 0x80
Typedefs
typedef struct DetectBytetestData_ DetectBytetestData
Functions
void DetectBytetestRegister (void)
int DetectBytetestSetup (DetectEngineCtx *, Signature *, char *)
void DetectBytetestFree (void *ptr)
this function will free memory associated with DetectBytetestData
DetectBytetestData * DetectBytetestParse (char *optstr, char **value, char **offset)
int DetectBytetestMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
int DetectBytetestDoMatch (DetectEngineThreadCtx *, Signature *, const SigMatchCtx *ctx, uint8_t *, uint32_t, uint8_t, int32_t, uint64_t)
Bytetest detection code.
Detailed Description
Author
Brian Rectanus brect.nosp@m.anu@.nosp@m.gmail.nosp@m..com
Definition in file detect-bytetest.h.
Macro Definition Documentation
#define DETECT_BYTETEST_BASE_DEC 10
"dec" type value string
Definition at line 39 of file detect-bytetest.h.
Referenced by DetectBytetestParse(), and DetectBytetestSetup().
#define DETECT_BYTETEST_BASE_HEX 16
"hex" type value string
Definition at line 40 of file detect-bytetest.h.
Referenced by DetectBytetestParse(), and DetectBytetestSetup().
#define DETECT_BYTETEST_BASE_OCT 8
"oct" type value string
Definition at line 38 of file detect-bytetest.h.
Referenced by DetectBytetestParse(), and DetectBytetestSetup().
#define DETECT_BYTETEST_BASE_UNSET 0
Bytetest Base Unset type value string (automatic)
Definition at line 37 of file detect-bytetest.h.
Referenced by DetectBytetestParse().
#define DETECT_BYTETEST_BIG 0x04
"bi" endian value
Definition at line 45 of file detect-bytetest.h.
Referenced by DetectBytetestParse(), and DetectBytetestSetup().
#define DETECT_BYTETEST_DCE 0x20
dce enabled
Definition at line 48 of file detect-bytetest.h.
Referenced by DetectBytetestParse(), and DetectBytetestSetup().
#define DETECT_BYTETEST_LITTLE 0x02
"little" endian value
Definition at line 44 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), DetectBytetestParse(), and DetectBytetestSetup().
#define DETECT_BYTETEST_NEGOP 0x01
Bytetest Flags "!" negated operator
Definition at line 43 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), and DetectBytetestParse().
#define DETECT_BYTETEST_OFFSET_BE 0x80
byte extract value enabled
Definition at line 50 of file detect-bytetest.h.
Referenced by DetectBytetestSetup().
#define DETECT_BYTETEST_OP_AND 4
"bitwise and" operator
Definition at line 31 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), and DetectBytetestParse().
#define DETECT_BYTETEST_OP_EQ 3
"equals" operator
Definition at line 30 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), and DetectBytetestParse().
#define DETECT_BYTETEST_OP_GE 6
greater than equal operator
Definition at line 33 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), and DetectBytetestParse().
#define DETECT_BYTETEST_OP_GT 2
"greater than" operator
Definition at line 29 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), and DetectBytetestParse().
#define DETECT_BYTETEST_OP_LE 7
less than equal operator
Definition at line 34 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), and DetectBytetestParse().
#define DETECT_BYTETEST_OP_LT 1
Bytetest Operators "less than" operator
Definition at line 28 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), and DetectBytetestParse().
#define DETECT_BYTETEST_OP_OR 5
"bitwise or" operator
Definition at line 32 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), and DetectBytetestParse().
#define DETECT_BYTETEST_RELATIVE 0x10
"relative" offset
Definition at line 47 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), DetectBytetestParse(), and DetectBytetestSetup().
#define DETECT_BYTETEST_STRING 0x08
"string" value
Definition at line 46 of file detect-bytetest.h.
Referenced by DetectBytetestDoMatch(), DetectBytetestParse(), and DetectBytetestSetup().
#define DETECT_BYTETEST_VALUE_BE 0x40
byte extract value enabled
Definition at line 49 of file detect-bytetest.h.
Referenced by DetectBytetestSetup().
Typedef Documentation
typedef struct DetectBytetestData_ DetectBytetestData
Function Documentation
int DetectBytetestDoMatch (DetectEngineThreadCtx * det_ctx, Signature * s, const SigMatchCtx * ctx, uint8_t * payload, uint32_t payload_len, uint8_t flags, int32_t offset, uint64_t value)
Bytetest detection code.
Byte test works on the packet payload.
Parameters
det_ctx thread de ctx
s signature
m sigmatch for this bytettest
payload ptr to the start of the buffer to inspect
payload_len length of the payload
Return values
1 match
0 no match
Definition at line 114 of file detect-bytetest.c.
References DetectBytetestData_::base, DetectEngineThreadCtx_::buffer_offset, BYTE_BIG_ENDIAN, BYTE_LITTLE_ENDIAN, ByteExtractStringUint64(), ByteExtractUint64(), data, DETECT_BYTETEST_LITTLE, DETECT_BYTETEST_NEGOP, DETECT_BYTETEST_OP_AND, DETECT_BYTETEST_OP_EQ, DETECT_BYTETEST_OP_GE, DETECT_BYTETEST_OP_GT, DETECT_BYTETEST_OP_LE, DETECT_BYTETEST_OP_LT, DETECT_BYTETEST_OP_OR, DETECT_BYTETEST_RELATIVE, DETECT_BYTETEST_STRING, len, DetectBytetestData_::nbytes, DetectBytetestData_::offset, DetectBytetestData_::op, SC_ERR_INVALID_NUM_BYTES, SCEnter, SCLogDebug, SCLogError, SCReturnInt, and DetectBytetestData_::value.
Referenced by DetectBytetestMatch().
void DetectBytetestFree (void * ptr)
this function will free memory associated with DetectBytetestData
Parameters
data pointer to DetectBytetestData
Definition at line 682 of file detect-bytetest.c.
References data, and SCFree.
Referenced by DetectBytetestParse(), DetectBytetestRegister(), and DetectBytetestSetup().
int DetectBytetestMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match byte_test
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectBytetestData
Return values
-1 error
0 no match
1 match
Todo:
The return seems backwards. We should return a non-zero error code. One of the error codes is "no match". As-is if someone accidentally does: if (DetectBytetestMatch(...)) { match }, then they catch an error as a match.
Definition at line 255 of file detect-bytetest.c.
References DetectBytetestDoMatch(), Packet_::payload, and Packet_::payload_len.
Referenced by DetectBytetestRegister().
DetectBytetestData* DetectBytetestParse (char * optstr, char ** value, char ** offset)
This function is used to parse byte_test options passed via
byte_test: bytes, [!]op, value, offset [,flags [, ...]]
flags: "big", "little", "relative", "string", "oct", "dec", "hex"
Parameters
optstr Pointer to the user provided byte_test options
value Used to pass the value back, if byte_test uses a byte_extract var.
offset Used to pass the offset back, if byte_test uses a byte_extract var.
Return values
data pointer to DetectBytetestData on success
NULL on failure
Todo:
Error on dups?
Definition at line 262 of file detect-bytetest.c.
References DetectBytetestData_::base, ByteExtractStringInt32(), ByteExtractStringUint32(), ByteExtractStringUint64(), data, DETECT_BYTETEST_BASE_DEC, DETECT_BYTETEST_BASE_HEX, DETECT_BYTETEST_BASE_OCT, DETECT_BYTETEST_BASE_UNSET, DETECT_BYTETEST_BIG, DETECT_BYTETEST_DCE, DETECT_BYTETEST_LITTLE, DETECT_BYTETEST_NEGOP, DETECT_BYTETEST_OP_AND, DETECT_BYTETEST_OP_EQ, DETECT_BYTETEST_OP_GE, DETECT_BYTETEST_OP_GT, DETECT_BYTETEST_OP_LE, DETECT_BYTETEST_OP_LT, DETECT_BYTETEST_OP_OR, DETECT_BYTETEST_RELATIVE, DETECT_BYTETEST_STRING, DetectBytetestFree(), DetectBytetestData_::flags, MAX_SUBSTRINGS, DetectBytetestData_::nbytes, DetectBytetestData_::offset, DetectBytetestData_::op, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_OPERATOR, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_PARSE, SC_ERR_UNKNOWN_VALUE, SCFree, SCLogError, SCMalloc, SCStrdup, unlikely, and DetectBytetestData_::value.
Referenced by DetectBytetestSetup().
void DetectBytetestRegister (void)
Registration function for byte_test.
Todo:
add support for no_stream and stream_only
Definition at line 67 of file detect-bytetest.c.
References DETECT_BYTETEST, DetectBytetestFree(), DetectBytetestMatch(), DetectBytetestRegisterTests(), DetectBytetestSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
int DetectBytetestSetup (DetectEngineCtx * , Signature * , char *)
This function is used to add the parsed byte_test data into the current signature.
Parameters
de_ctx pointer to the Detection Engine Context
s pointer to the Current Signature
optstr pointer to the user provided options
Return values
0 on Success
-1 on Failure
Definition at line 450 of file detect-bytetest.c.
References Signature_::alproto, ALPROTO_DCERPC, ALPROTO_UNKNOWN, AppLayerHtpEnableResponseBodyCallback(), DetectBytetestData_::base, SigMatch_::ctx, data, DETECT_BYTE_EXTRACT, DETECT_BYTEJUMP, DETECT_BYTETEST, DETECT_BYTETEST_BASE_DEC, DETECT_BYTETEST_BASE_HEX, DETECT_BYTETEST_BASE_OCT, DETECT_BYTETEST_BIG, DETECT_BYTETEST_DCE, DETECT_BYTETEST_LITTLE, DETECT_BYTETEST_OFFSET_BE, DETECT_BYTETEST_RELATIVE, DETECT_BYTETEST_STRING, DETECT_BYTETEST_VALUE_BE, DETECT_CONTENT, DETECT_CONTENT_RELATIVE_NEXT, DETECT_ISDATAAT, DETECT_PCRE, DETECT_PCRE_RELATIVE_NEXT, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_NOTSET, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectByteExtractRetrieveSMVar(), DetectBytetestFree(), DetectBytetestParse(), DetectPcreData_::flags, DetectBytetestData_::flags, DetectContentData_::flags, Signature_::flags, Signature_::list, DetectBytetestData_::offset, SC_ERR_CONFLICTING_RULE_KEYWORDS, SC_ERR_INVALID_SIGNATURE, SCFree, SCLogError, SIG_FLAG_APPLAYER, SigMatchAlloc(), SigMatchAppendSMToList(), SigMatchGetLastSMFromLists(), SigMatchListSMBelongsTo(), Signature_::sm_lists_tail, SigMatch_::type, and DetectBytetestData_::value.
Referenced by DetectBytetestRegister().