suricata: src/detect-engine-hmd.c File Reference
detect-engine-hmd.c File Reference
HTTP layer support
Handle HTTP method match.
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-hmd.h"
#include "detect-engine-mpm.h"
#include "detect-parse.h"
#include "detect-engine-state.h"
#include "detect-engine-content-inspection.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-print.h"
#include "flow.h"
#include "stream-tcp.h"
#include "app-layer-parser.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "app-layer-htp.h"
#include "app-layer-protos.h"
Functions
int DetectEngineRunHttpMethodMpm (DetectEngineThreadCtx *det_ctx, Flow *f, HtpState *htp_state, uint8_t flags, void *txv, uint64_t idx)
int DetectEngineInspectHttpMethod (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *txv, uint64_t tx_id)
Do the http_method content inspection for a signature.
void DetectEngineHttpMethodRegisterTests (void)
Detailed Description
Handle HTTP method match.
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-engine-hmd.c.
Function Documentation
void DetectEngineHttpMethodRegisterTests (void)
Definition at line 1783 of file detect-engine-hmd.c.
Referenced by RunUnittests().
int DetectEngineInspectHttpMethod (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * txv, uint64_t tx_id)
Do the http_method content inspection for a signature.
Parameters
de_ctx Detection engine context.
det_ctx Detection engine thread context.
s Signature to inspect.
f Flow.
flags App layer flags.
state App layer state.
Return values
0 No match.
1 Match.
Definition at line 90 of file detect-engine-hmd.c.
References ALPROTO_HTTP, AppLayerParserGetStateProgress(), bstr_len, bstr_ptr, DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HMD, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DETECT_SM_LIST_HMDMATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, HTP_REQUEST_LINE, DetectEngineThreadCtx_::inspection_recursion_counter, htp_tx_t::request_method, and Signature_::sm_lists.
Referenced by DetectEngineRegisterAppInspectionEngines().
int DetectEngineRunHttpMethodMpm (DetectEngineThreadCtx * det_ctx, Flow * f, HtpState * htp_state, uint8_t flags, void * txv, uint64_t idx)
Definition at line 60 of file detect-engine-hmd.c.
References bstr_len, bstr_ptr, HttpMethodPatternSearch(), and htp_tx_t::request_method.