suricata: src/detect-reference.h File Reference
detect-reference.h File Reference
#include "decode-events.h"
#include "decode-ipv4.h"
#include "decode-tcp.h"
Data Structures
struct DetectReference_
Signature reference list.
Typedefs
typedef struct DetectReference_ DetectReference
Signature reference list.
Functions
void DetectReferenceRegister (void)
Registration function for the reference: keyword.
void ReferenceRegisterTests (void)
void DetectReferenceFree (DetectReference *)
Free a Reference object.
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Definition in file detect-reference.h.
Typedef Documentation
typedef struct DetectReference_ DetectReference
Signature reference list.
Function Documentation
void DetectReferenceFree (DetectReference *)
Free a Reference object.
Free function for a Reference object
Definition at line 92 of file detect-reference.c.
References DetectReference_::reference, SCEnter, SCFree, and SCReturn.
void DetectReferenceRegister (void)
Registration function for the reference: keyword.
Registration function for Reference keyword
Definition at line 56 of file detect-reference.c.
References SigTableElmt_::desc, DETECT_REFERENCE, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, ReferenceRegisterTests(), SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void ReferenceRegisterTests (void)
This function registers unit tests for Reference keyword.
Definition at line 367 of file detect-reference.c.
Referenced by DetectReferenceRegister().