suricata: src/detect-engine-loader.h File Reference
detect-engine-loader.h File Reference
Data Structures
struct DetectLoaderTask_
struct DetectLoaderControl_
Typedefs
typedef int(* LoaderFunc)(void *ctx, int loader_id)
typedef struct DetectLoaderTask_ DetectLoaderTask
typedef struct DetectLoaderControl_ DetectLoaderControl
Functions
int DetectLoaderQueueTask (int loader_id, LoaderFunc Func, void *func_ctx)
int DetectLoadersSync (void)
wait for loader tasks to complete
void DetectLoadersInit (void)
void TmThreadContinueDetectLoaderThreads ()
Unpauses all threads present in tv_root.
void DetectLoaderThreadSpawn ()
spawn the detect loader manager thread
void TmModuleDetectLoaderRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Detect loader API, for using multiple 'loader' threads that can load multiple detection engines in parallel.
Definition in file detect-engine-loader.h.
Typedef Documentation
typedef struct DetectLoaderControl_ DetectLoaderControl
typedef struct DetectLoaderTask_ DetectLoaderTask
typedef int(* LoaderFunc)(void *ctx, int loader_id)
Parameters
ctx function specific data
loader_id id of the loader that executed the task
Definition at line 34 of file detect-engine-loader.h.
Function Documentation
int DetectLoaderQueueTask (int loader_id, LoaderFunc Func, void * func_ctx)
Parameters
loader -1 for auto select
Return values
loader_id or negative in case of error
Definition at line 45 of file detect-engine-loader.c.
References DetectLoaderTask_::ctx, DetectLoaderTask_::Func, DetectLoaderControl_::m, next, SCCalloc, SCLogDebug, SCMutexLock, SCMutexUnlock, TAILQ_INSERT_TAIL, and TmThreadWakeupDetectLoaderThreads().
Referenced by DetectLoaderSetupLoadTenant(), and DetectLoaderSetupReloadTenant().
void DetectLoadersInit (void)
Definition at line 116 of file detect-engine-loader.c.
References BUG_ON, ConfGetInt(), NLOADERS, SC_ERR_INVALID_ARGUMENTS, SCCalloc, SCLogError, and SCLogInfo.
Referenced by DetectEngineMultiTenantSetup().
int DetectLoadersSync (void)
wait for loader tasks to complete
Return values
result 0 for ok, -1 for errors
Definition at line 78 of file detect-engine-loader.c.
References DetectLoaderControl_::m, DetectLoaderControl_::result, SC_ERR_INITIALIZATION, SCLogDebug, SCLogError, SCMutexLock, SCMutexUnlock, and TAILQ_EMPTY.
Referenced by DetectEngineLoadTenantBlocking(), DetectEngineMultiTenantSetup(), and DetectEngineReloadTenantBlocking().
void DetectLoaderThreadSpawn ()
spawn the detect loader manager thread
Definition at line 264 of file detect-engine-loader.c.
References BUG_ON, TM_ECODE_OK, TmThreadCreateCmdThreadByName(), and TmThreadSpawn().
Referenced by DetectEngineMultiTenantSetup().
void TmModuleDetectLoaderRegister (void)
Definition at line 289 of file detect-engine-loader.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Management, TmModule_::name, SC_ATOMIC_INIT, SCLogDebug, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_MANAGEMENT_TM, TMM_DETECTLOADER, and tmm_modules.
Referenced by DetectEngineMultiTenantSetup().
void TmThreadContinueDetectLoaderThreads ()
Unpauses all threads present in tv_root.
Definition at line 167 of file detect-engine-loader.c.
References ThreadVars_::name, ThreadVars_::next, SCMutexLock, SCMutexUnlock, TmThreadContinue(), tv_root, tv_root_lock, and TVT_MAX.
Referenced by DetectEngineMultiTenantSetup().