suricata: src/detect-engine-hsbd.h File Reference
detect-engine-hsbd.h File Reference
#include "app-layer-htp.h"
Macros
#define ENGINE_HSBD_BUFFER_LIMIT 20000
Functions
int DetectEngineRunHttpServerBodyMpm (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Flow *f, HtpState *htp_state, uint8_t flags, void *tx, uint64_t idx)
int DetectEngineInspectHttpServerBody (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *tx, uint64_t tx_id)
void DetectEngineCleanHSBDBuffers (DetectEngineThreadCtx *det_ctx)
void DetectEngineHttpServerBodyRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-engine-hsbd.h.
Macro Definition Documentation
#define ENGINE_HSBD_BUFFER_LIMIT 20000
Definition at line 26 of file detect-engine-hsbd.h.
Function Documentation
void DetectEngineCleanHSBDBuffers (DetectEngineThreadCtx * det_ctx)
Definition at line 377 of file detect-engine-hsbd.c.
References HttpReassembledBody_::buffer_len, DetectEngineThreadCtx_::hsbd, DetectEngineThreadCtx_::hsbd_buffers_list_len, DetectEngineThreadCtx_::hsbd_start_tx_id, and HttpReassembledBody_::offset.
Referenced by SigMatchSignatures().
void DetectEngineHttpServerBodyRegisterTests (void)
Definition at line 4423 of file detect-engine-hsbd.c.
Referenced by RunUnittests().
int DetectEngineInspectHttpServerBody (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * tx, uint64_t tx_id)
Definition at line 339 of file detect-engine-hsbd.c.
References ALPROTO_HTTP, AppLayerParserGetStateProgress(), DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HSBD, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DETECT_SM_LIST_FILEDATA, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, HTP_RESPONSE_BODY, DetectEngineThreadCtx_::inspection_recursion_counter, and Signature_::sm_lists.
Referenced by DetectEngineRegisterAppInspectionEngines().
int DetectEngineRunHttpServerBodyMpm (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Flow * f, HtpState * htp_state, uint8_t flags, void * tx, uint64_t idx)
Definition at line 316 of file detect-engine-hsbd.c.
References HttpServerBodyPatternSearch().