suricata: src/detect-engine-address.c File Reference
detect-engine-address.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "flow-var.h"
#include "util-cidr.h"
#include "util-unittest.h"
#include "util-rule-vars.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "detect-engine-siggroup.h"
#include "detect-engine-address.h"
#include "detect-engine-address-ipv4.h"
#include "detect-engine-address-ipv6.h"
#include "detect-engine-port.h"
#include "util-debug.h"
#include "util-print.h"
Functions
void DetectAddressPrint (DetectAddress *gr)
Prints the address data held by the DetectAddress. If the address data family is any, we print "ANY". If the address data family is IPv4, we print the the ipv4 address and mask, and if the address data family is IPv6, we print the ipv6 address and mask.
int DetectAddressMergeNot (DetectAddressHead *gh, DetectAddressHead *ghn)
Merge the + and the - list (+ positive match, - 'not' match)
DetectAddress * DetectAddressInit (void)
Creates and returns a new instance of a DetectAddress.
void DetectAddressFree (DetectAddress *ag)
Frees a DetectAddress instance.
DetectAddress * DetectAddressCopy (DetectAddress *orig)
Copies the contents of one Address group in DetectAddress and returns a new instance of the DetectAddress that contains the copied address.
void DetectAddressPrintMemory (void)
Prints the memory statistics for the detection-engine-address section.
DetectAddress * DetectAddressLookupInList (DetectAddress *head, DetectAddress *gr)
Used to check if a DetectAddress list contains an instance with a similar DetectAddress. The comparison done is not the one that checks the memory for the same instance, but one that checks that the two instances hold the same content.
void DetectAddressPrintList (DetectAddress *head)
Prints the address data information for all the DetectAddress instances in the DetectAddress list sent as the argument.
void DetectAddressCleanupList (DetectAddress *head)
Frees a list of DetectAddress instances.
int DetectAddressAdd (DetectAddress **head, DetectAddress *ag)
Do a sorted insert, where the top of the list should be the biggest network/range.
int DetectAddressInsert (DetectEngineCtx *de_ctx, DetectAddressHead *gh, DetectAddress *new)
Same as DetectAddressInsert, but then for inserting a address group object. This also makes sure SigGroupContainer lists are handled correctly.
int DetectAddressJoin (DetectEngineCtx *de_ctx, DetectAddress *target, DetectAddress *source)
Join two addresses groups together.
int DetectAddressParseString (DetectAddress *dd, char *str)
int DetectAddressSetup (DetectAddressHead *gh, char *s)
Setup a single address string, parse it and add the resulting Address-Range(s) to the AddessHead(DetectAddressHead instance).
int DetectAddressTestConfVars (void)
int DetectAddressParse (const DetectEngineCtx *de_ctx, DetectAddressHead *gh, char *str)
Parses an address group sent as a character string and updates the DetectAddressHead sent as the argument with the relevant address ranges from the parsed string.
DetectAddressHead * DetectAddressHeadInit (void)
Returns a new instance of DetectAddressHead.
void DetectAddressHeadCleanup (DetectAddressHead *gh)
Cleans a DetectAddressHead. The functions frees the 3 address group heads(any, ipv4 and ipv6) inside the DetectAddressHead instance.
void DetectAddressHeadFree (DetectAddressHead *gh)
Frees a DetectAddressHead instance.
int DetectAddressCmp (DetectAddress *a, DetectAddress *b)
Used to compare 2 address ranges.
int DetectAddressMatchIPv4 (DetectMatchAddressIPv4 *addrs, uint16_t addrs_cnt, Address *a)
Match a packets address against a signatures addrs array.
int DetectAddressMatchIPv6 (DetectMatchAddressIPv6 *addrs, uint16_t addrs_cnt, Address *a)
Match a packets address against a signatures addrs array.
int DetectAddressMatch (DetectAddress *dd, Address *a)
Check if a particular address(ipv4 or ipv6) matches the address range in the DetectAddress instance.
DetectAddress * DetectAddressLookupInHead (DetectAddressHead *gh, Address *a)
Find the group matching address in a group head.
void DetectAddressTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Address part of the detection engine.
Todo:
Move this out of the detection plugin structure rename to detect-engine-address.c
Definition in file detect-engine-address.c.
Function Documentation
int DetectAddressAdd (DetectAddress ** head, DetectAddress * ag)
Do a sorted insert, where the top of the list should be the biggest network/range.
   XXX current sorting only works for overlapping nets
Parameters
head Pointer to the list of DetectAddress.
ag Pointer to the DetectAddress that has to be added to the above list.
Return values
0 On successfully inserting the DetectAddress.
-1 On failure.
Definition at line 281 of file detect-engine-address.c.
References ADDRESS_EB, DetectAddressCmp(), DetectAddress_::next, and DetectAddress_::prev.
Referenced by BuildDestinationAddressHeads(), and BuildDestinationAddressHeadsWithBothPorts().
void DetectAddressCleanupList (DetectAddress * head)
Frees a list of DetectAddress instances.
Parameters
head Pointer to a list of DetectAddress instances to be freed.
Definition at line 250 of file detect-engine-address.c.
References DetectAddressFree(), DetectAddress_::next, and next.
Referenced by BuildDestinationAddressHeads(), BuildDestinationAddressHeadsWithBothPorts(), and DetectAddressHeadCleanup().
int DetectAddressCmp (DetectAddress * a, DetectAddress * b)
Used to compare 2 address ranges.
Parameters
a Pointer to the first DetectAddressData to be compared.
b Pointer to the second DetectAddressData to be compared.
Definition at line 1620 of file detect-engine-address.c.
References ADDRESS_EQ, ADDRESS_ER, ADDRESS_FLAG_ANY, DetectAddressCmpIPv4(), DetectAddressCmpIPv6(), Address_::family, DetectAddress_::flags, and DetectAddress_::ip.
Referenced by DetectAddressAdd(), DetectAddressInsert(), DetectAddressLookupInList(), and DetectAddressMergeNot().
DetectAddress* DetectAddressCopy (DetectAddress * orig)
Copies the contents of one Address group in DetectAddress and returns a new instance of the DetectAddress that contains the copied address.
Parameters
orig Pointer to the instance of DetectAddress that contains the address data to be copied to the new instance.
Return values
ag Pointer to the new instance of DetectAddress that contains the copied address.
Definition at line 144 of file detect-engine-address.c.
References DetectAddress_::cnt, COPY_ADDRESS, DetectAddressInit(), DetectAddress_::flags, DetectAddress_::ip, and DetectAddress_::ip2.
Referenced by BuildDestinationAddressHeads(), BuildDestinationAddressHeadsWithBothPorts(), CreateGroupedAddrList(), and DetectAddressMergeNot().
void DetectAddressFree (DetectAddress * ag)
Frees a DetectAddress instance.
Parameters
ag Pointer to the DetectAddress instance to be freed.
Definition at line 94 of file detect-engine-address.c.
References ADDRESS_HAVEPORT, ADDRESS_PORTS_COPY, ADDRESS_SIGGROUPHEAD_COPY, DetectAddressHeadFree(), DetectPortCleanupList(), DetectAddress_::dst_gh, DetectAddress_::flags, DetectAddress_::port, SCFree, SCLogDebug, DetectAddress_::sh, and SigGroupHeadFree().
Referenced by CreateGroupedAddrList(), DetectAddressCleanupList(), DetectAddressCutIPv4(), DetectAddressCutIPv6(), DetectAddressInsert(), and DetectAddressMergeNot().
void DetectAddressHeadCleanup (DetectAddressHead * gh)
Cleans a DetectAddressHead. The functions frees the 3 address group heads(any, ipv4 and ipv6) inside the DetectAddressHead instance.
Parameters
gh Pointer to the DetectAddressHead instance that has to be cleaned.
Definition at line 1509 of file detect-engine-address.c.
References DetectAddressHead_::any_head, DetectAddressCleanupList(), DetectAddressHead_::ipv4_head, and DetectAddressHead_::ipv6_head.
Referenced by DetectAddressHeadFree(), and SigFree().
void DetectAddressHeadFree (DetectAddressHead * gh)
Frees a DetectAddressHead instance.
Parameters
gh Pointer to the DetectAddressHead instance to be freed.
Definition at line 1534 of file detect-engine-address.c.
References DetectAddressHeadCleanup(), and SCFree.
Referenced by DetectAddressFree(), DetectAddressParse(), DetectAddressTestConfVars(), SigAddressCleanupStage1(), and SigAddressPrepareStage2().
DetectAddressHead* DetectAddressHeadInit (void)
Returns a new instance of DetectAddressHead.
Return values
gh Pointer to the new instance of DetectAddressHead.
Definition at line 1486 of file detect-engine-address.c.
References SCMalloc, and unlikely.
Referenced by BuildDestinationAddressHeads(), BuildDestinationAddressHeadsWithBothPorts(), DetectAddressParse(), DetectAddressTestConfVars(), and SigAddressPrepareStage2().
DetectAddress* DetectAddressInit (void)
Creates and returns a new instance of a DetectAddress.
memory usage counters
Todo:
not MT safe
Return values
ag Pointer to the newly created DetectAddress on success; NULL on failure.
Definition at line 74 of file detect-engine-address.c.
References SCMalloc, and unlikely.
Referenced by DetectAddressCopy(), DetectAddressCutIPv4(), DetectAddressCutIPv6(), DetectAddressCutNotIPv4(), and DetectAddressCutNotIPv6().
int DetectAddressInsert (DetectEngineCtx * de_ctx, DetectAddressHead * gh, DetectAddress * new)
Same as DetectAddressInsert, but then for inserting a address group object. This also makes sure SigGroupContainer lists are handled correctly.
Parameters
de_ctx Pointer to the detection engine context.
gh Pointer to the DetectAddressHead list to which it has to be inserted.
new Pointer to the DetectAddress, that has to be inserted.
Return values
1 On successfully inserting it.
-1 On error.
0 Not inserted, memory of new is freed.
Definition at line 381 of file detect-engine-address.c.
References ADDRESS_EB, ADDRESS_EQ, ADDRESS_ER, ADDRESS_ES, ADDRESS_FLAG_ANY, ADDRESS_GE, ADDRESS_GT, ADDRESS_LE, ADDRESS_LT, BUG_ON, DetectAddress_::cnt, DetectAddressCmp(), DetectAddressFree(), DetectAddressInsert(), DetectPortInsertCopy(), DetectAddress_::next, DetectPort_::next, DetectAddress_::port, DetectPort_::port, DetectAddress_::prev, SCLogDebug, DetectAddress_::sh, and SigGroupHeadCopySigs().
Referenced by CreateGroupedAddrList(), DetectAddressInsert(), DetectAddressMergeNot(), and DetectAddressSetup().
int DetectAddressJoin (DetectEngineCtx * de_ctx, DetectAddress * target, DetectAddress * source)
Join two addresses groups together.
Parameters
de_ctx Pointer to the detection engine context.
target Pointer to the target address group.
source Pointer to the source address group.
Return values
0 On success.
-1 On failure.
Definition at line 522 of file detect-engine-address.c.
References DetectAddress_::cnt, DetectAddressJoinIPv4(), DetectAddressJoinIPv6(), DetectPortInsertCopy(), Address_::family, DetectAddress_::ip, DetectPort_::next, DetectAddress_::port, DetectAddress_::sh, and SigGroupHeadCopySigs().
Referenced by CreateGroupedAddrList().
DetectAddress* DetectAddressLookupInHead (DetectAddressHead * gh, Address * a)
Find the group matching address in a group head.
Parameters
gh Pointer to the address group head(DetectAddressHead instance).
a Pointer to an Address instance.
Return values
g On success pointer to an DetectAddress if we find a match for the Address "a", in the DetectAddressHead "gh".
Definition at line 1867 of file detect-engine-address.c.
References DetectAddressHead_::any_head, DetectAddressMatch(), Address_::family, DetectAddressHead_::ipv4_head, DetectAddressHead_::ipv6_head, DetectAddress_::next, SCEnter, SCLogDebug, and SCReturnPtr.
Referenced by SigMatchSignaturesGetSgh(), and ThresholdHandlePacketSuppress().
DetectAddress* DetectAddressLookupInList (DetectAddress * head, DetectAddress * gr)
Used to check if a DetectAddress list contains an instance with a similar DetectAddress. The comparison done is not the one that checks the memory for the same instance, but one that checks that the two instances hold the same content.
Parameters
head Pointer to the DetectAddress list.
ad Pointer to the DetectAddress that has to be checked for in the DetectAddress list.
Return values
cur Returns a pointer to the DetectAddress on a match; NULL if no match.
Definition at line 209 of file detect-engine-address.c.
References ADDRESS_EQ, DetectAddressCmp(), and DetectAddress_::next.
Referenced by BuildDestinationAddressHeads(), and BuildDestinationAddressHeadsWithBothPorts().
int DetectAddressMatch (DetectAddress * dd, Address * a)
Check if a particular address(ipv4 or ipv6) matches the address range in the DetectAddress instance.
   We basically check that the address falls inbetween the address
   range in DetectAddress.
Parameters
dd Pointer to the DetectAddress instance.
a Pointer to an Address instance.
1 On a match.
0 On no match.
Definition at line 1773 of file detect-engine-address.c.
References AddressIPv6Ge(), AddressIPv6Le(), Address_::family, DetectAddress_::ip, DetectAddress_::ip2, SCEnter, SCLogDebug, and SCReturnInt.
Referenced by DetectAddressLookupInHead().
int DetectAddressMatchIPv4 (DetectMatchAddressIPv4 * addrs, uint16_t addrs_cnt, Address * a)
Match a packets address against a signatures addrs array.
Parameters
addrs array of DetectMatchAddressIPv4's
addrs_cnt array size in members
a packets address
Return values
0 no match
1 match
Note
addresses in addrs are in host order
Todo:
array should be ordered, so we can break out of the loop
Definition at line 1650 of file detect-engine-address.c.
References DetectMatchAddressIPv4_::ip, DetectMatchAddressIPv4_::ip2, SCEnter, and SCReturnInt.
Referenced by SigMatchSignatures().
int DetectAddressMatchIPv6 (DetectMatchAddressIPv6 * addrs, uint16_t addrs_cnt, Address * a)
Match a packets address against a signatures addrs array.
Parameters
addrs array of DetectMatchAddressIPv6's
addrs_cnt array size in members
a packets address
Return values
0 no match
1 match
Note
addresses in addrs are in host order
Todo:
array should be ordered, so we can break out of the loop
Definition at line 1684 of file detect-engine-address.c.
References DetectMatchAddressIPv6_::ip, DetectMatchAddressIPv6_::ip2, SCEnter, and SCReturnInt.
Referenced by SigMatchSignatures().
int DetectAddressMergeNot (DetectAddressHead * gh, DetectAddressHead * ghn)
Merge the + and the - list (+ positive match, - 'not' match)
Parameters
gh Pointer to the address head containing the non-NOT groups.
ghn Pointer to the address head containing the NOT groups.
Return values
0 On success.
-1 On failure.
Definition at line 1182 of file detect-engine-address.c.
References ADDRESS_EB, ADDRESS_EQ, DetectAddressCmp(), DetectAddressCopy(), DetectAddressFree(), DetectAddressInsert(), DetectAddressPrint(), DetectAddressSetup(), DetectAddressHead_::ipv4_head, DetectAddressHead_::ipv6_head, DetectAddress_::next, DetectAddress_::prev, SC_ERR_INVALID_SIGNATURE, SCLogDebug, and SCLogError.
Referenced by DetectAddressParse().
int DetectAddressParse (const DetectEngineCtx * de_ctx, DetectAddressHead * gh, char * str)
Parses an address group sent as a character string and updates the DetectAddressHead sent as the argument with the relevant address ranges from the parsed string.
Parameters
gh Pointer to the DetectAddressHead.
str Pointer to the character string containing the address group that has to be parsed.
Return values
0 On success.
-1 On failure.
Definition at line 1437 of file detect-engine-address.c.
References DetectAddressHeadFree(), DetectAddressHeadInit(), DetectAddressMergeNot(), DetectAddressHead_::ipv4_head, and SCLogDebug.
Referenced by SigParseAddress().
int DetectAddressParseString (DetectAddress * dd, char * str)
Definition at line 598 of file detect-engine-address.c.
References Address_::address, ADDRESS_FLAG_ANY, ADDRESS_FLAG_NOT, AddressIPv6Gt(), BUG_ON, CIDRGet(), Address_::family, DetectAddress_::flags, inet_pton(), DetectAddress_::ip, DetectAddress_::ip2, SCLogDebug, and strlcpy().
void DetectAddressPrint (DetectAddress * gr)
Prints the address data held by the DetectAddress. If the address data family is any, we print "ANY". If the address data family is IPv4, we print the the ipv4 address and mask, and if the address data family is IPv6, we print the ipv6 address and mask.
Parameters
ad Pointer to the DetectAddress instance to be printed.
Definition at line 1824 of file detect-engine-address.c.
References ADDRESS_FLAG_ANY, Address_::family, DetectAddress_::flags, DetectAddress_::ip, DetectAddress_::ip2, PrintInet(), and SCLogDebug.
Referenced by DetectAddressMergeNot(), DetectAddressPrintList(), and SigAddressPrepareStage5().
void DetectAddressPrintList (DetectAddress * head)
Prints the address data information for all the DetectAddress instances in the DetectAddress list sent as the argument.
Parameters
head Pointer to a list of DetectAddress instances.
Definition at line 229 of file detect-engine-address.c.
References DetectAddressPrint(), DetectAddress_::next, SCLogInfo, DetectAddress_::sh, and SigGroupHead_::sig_cnt.
void DetectAddressPrintMemory (void)
Prints the memory statistics for the detection-engine-address section.
Definition at line 163 of file detect-engine-address.c.
References SCLogDebug.
int DetectAddressSetup (DetectAddressHead * gh, char * s)
Setup a single address string, parse it and add the resulting Address-Range(s) to the AddessHead(DetectAddressHead instance).
Parameters
gh Pointer to the Address-Head(DetectAddressHead) to which the resulting Address-Range(s) from the parsed ip string has to be added.
s Pointer to the ip address string to be parsed.
Return values
0 On success.
-1 On failure.
Definition at line 815 of file detect-engine-address.c.
References ADDRESS_FLAG_ANY, ADDRESS_FLAG_NOT, BUG_ON, DetectAddressInsert(), FALSE, Address_::family, DetectAddress_::flags, DetectAddress_::ip, SC_ERR_ADDRESS_ENGINE_GENERIC, SCLogDebug, SCLogError, and TRUE.
Referenced by DetectAddressMergeNot().
int DetectAddressTestConfVars (void)
Definition at line 1367 of file detect-engine-address.c.
References ConfGetNode(), DetectAddressHeadFree(), DetectAddressHeadInit(), ConfNode_::name, next, SC_ERR_INVALID_YAML_CONF_ENTRY, SCLogDebug, SCLogError, TAILQ_FOREACH, and ConfNode_::val.
void DetectAddressTests (void)
Definition at line 5213 of file detect-engine-address.c.
References DetectAddressIPv4Tests(), and DetectAddressIPv6Tests().
Referenced by RunUnittests().