suricata: src/detect-ssh-proto-version.h File Reference
detect-ssh-proto-version.h File Reference
Data Structures
struct DetectSshVersionData_
Macros
#define SSH_FLAG_PROTOVERSION_2_COMPAT 0x01
Typedefs
typedef struct
DetectSshVersionData_ DetectSshVersionData
Functions
void DetectSshVersionRegister (void)
Registration function for keyword: ssh.protoversion.
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file detect-ssh-proto-version.h.
Macro Definition Documentation
#define SSH_FLAG_PROTOVERSION_2_COMPAT 0x01
proto version 1.99 is considered proto version 2
Definition at line 28 of file detect-ssh-proto-version.h.
Referenced by DetectSshVersionMatch(), and DetectSshVersionParse().
Typedef Documentation
typedef struct DetectSshVersionData_ DetectSshVersionData
Function Documentation
void DetectSshVersionRegister (void)
Registration function for keyword: ssh.protoversion.
Definition at line 73 of file detect-ssh-proto-version.c.
References SigTableElmt_::alproto, ALPROTO_SSH, SigTableElmt_::AppLayerMatch, DETECT_AL_SSH_PROTOVERSION, DetectSshVersionFree(), DetectSshVersionMatch(), DetectSshVersionRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().