suricata: src/detect-fragoffset.h File Reference
detect-fragoffset.h File Reference
Data Structures
struct DetectFragOffsetData_
Macros
#define FRAG_LESS 1
#define FRAG_MORE 2
Typedefs
typedef struct
DetectFragOffsetData_ DetectFragOffsetData
Functions
void DetectFragOffsetRegister (void)
Registration function for fragoffset.
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Definition in file detect-fragoffset.h.
Macro Definition Documentation
#define FRAG_LESS 1
Definition at line 27 of file detect-fragoffset.h.
Referenced by DetectFragOffsetMatch(), and DetectFragOffsetParse().
#define FRAG_MORE 2
Definition at line 28 of file detect-fragoffset.h.
Referenced by DetectFragOffsetMatch(), and DetectFragOffsetParse().
Typedef Documentation
typedef struct DetectFragOffsetData_ DetectFragOffsetData
Function Documentation
void DetectFragOffsetRegister (void)
Registration function for fragoffset.
Definition at line 54 of file detect-fragoffset.c.
References SigTableElmt_::desc, DETECT_FRAGOFFSET, DetectFragOffsetFree(), DetectFragOffsetMatch(), DetectFragOffsetRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().