suricata: src/detect-gid.c File Reference
detect-gid.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-parse.h"
#include "flow-var.h"
#include "decode-events.h"
#include "detect-gid.h"
#include "util-unittest.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "[0-9]+"
Functions
void DetectGidRegister (void)
Registration function for gid: keyword.
void GidRegisterTests (void)
this function registers unit tests for Gid
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Implements the gid keyword
Definition in file detect-gid.c.
Macro Definition Documentation
#define PARSE_REGEX "[0-9]+"
Definition at line 39 of file detect-gid.c.
Function Documentation
void DetectGidRegister (void)
Registration function for gid: keyword.
Registration function for gid: keyword
Definition at line 47 of file detect-gid.c.
References SigTableElmt_::desc, DETECT_GID, SigTableElmt_::Free, GidRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void GidRegisterTests (void)
this function registers unit tests for Gid
This function registers unit tests for Gid
Definition at line 195 of file detect-gid.c.
Referenced by DetectGidRegister().