suricata: src/detect-msg.c File Reference
detect-msg.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "util-classification-config.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
Functions
void DetectMsgRegisterTests (void)
this function registers unit tests for DetectMsg
void DetectMsgRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements the msg keyword
Definition in file detect-msg.c.
Function Documentation
void DetectMsgRegister (void)
Definition at line 39 of file detect-msg.c.
References SigTableElmt_::desc, DETECT_MSG, DetectMsgRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectMsgRegisterTests (void)
this function registers unit tests for DetectMsg
Definition at line 204 of file detect-msg.c.
Referenced by DetectMsgRegister().