suricata: src/detect-engine-apt-event.c File Reference
detect-engine-apt-event.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "app-layer-parser.h"
#include "detect-app-layer-event.h"
#include "detect-engine-state.h"
#include "stream.h"
#include "detect-engine-apt-event.h"
#include "util-profiling.h"
#include "util-unittest.h"
Functions
int DetectEngineAptEventInspect (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *tx, uint64_t tx_id)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-engine-apt-event.c.
Function Documentation
int DetectEngineAptEventInspect (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * tx, uint64_t tx_id)
Definition at line 34 of file detect-engine-apt-event.c.
References Flow_::alproto, AppLayerParserGetEventsByTx(), AppLayerParserGetStateProgress(), AppLayerParserGetStateProgressCompletionStatus(), SigMatch_::ctx, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DETECT_SM_LIST_APP_EVENT, DetectAppLayerEventData_::event_id, KEYWORD_PROFILING_END, KEYWORD_PROFILING_START, SigMatch_::next, Flow_::proto, Signature_::sm_lists, and SigMatch_::type.