suricata: src/detect-csum.c File Reference
detect-csum.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-csum.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "pkt-var.h"
#include "host.h"
#include "util-profiling.h"
Functions
int DetectIPV4CsumMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
Checks if the packet sent as the argument, has a valid or invalid ipv4 checksum, based on whether ipv4-csum option for this rule has been supplied with "valid" or "invalid" argument.
void DetectIPV4CsumFree (void *)
int DetectTCPV4CsumMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
Checks if the packet sent as the argument, has a valid or invalid tcpv4 checksum, based on whether tcpv4-csum option for this rule has been supplied with "valid" or "invalid" argument.
void DetectTCPV4CsumFree (void *)
int DetectTCPV6CsumMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
Checks if the packet sent as the argument, has a valid or invalid tcpv6 checksum, based on whether tcpv6-csum option for this rule has been supplied with "valid" or "invalid" argument.
void DetectTCPV6CsumFree (void *)
int DetectUDPV4CsumMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
Checks if the packet sent as the argument, has a valid or invalid udpv4 checksum, based on whether udpv4-csum option for this rule has been supplied with "valid" or "invalid" argument.
void DetectUDPV4CsumFree (void *)
int DetectUDPV6CsumMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
Checks if the packet sent as the argument, has a valid or invalid udpv6 checksum, based on whether udpv6-csum option for this rule has been supplied with "valid" or "invalid" argument.
void DetectUDPV6CsumFree (void *)
int DetectICMPV4CsumMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
Checks if the packet sent as the argument, has a valid or invalid icmpv4 checksum, based on whether icmpv4-csum option for this rule has been supplied with "valid" or "invalid" argument.
void DetectICMPV4CsumFree (void *)
int DetectICMPV6CsumMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
Checks if the packet sent as the argument, has a valid or invalid icmpv6 checksum, based on whether icmpv6-csum option for this rule has been supplied with "valid" or "invalid" argument.
void DetectICMPV6CsumFree (void *)
void DetectCsumRegisterTests (void)
void DetectCsumRegister (void)
Registers handlers for all the checksum keywords. The checksum keywords that are registered are ipv4-sum, tcpv4-csum, tcpv6-csum, udpv4-csum, udpv6-csum, icmpv4-csum and icmpv6-csum.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements checksum keyword.
Definition in file detect-csum.c.
Function Documentation
void DetectCsumRegister (void)
Registers handlers for all the checksum keywords. The checksum keywords that are registered are ipv4-sum, tcpv4-csum, tcpv6-csum, udpv4-csum, udpv6-csum, icmpv4-csum and icmpv6-csum.
Each of the checksum keywords implemented here takes 2 arguments - "valid" or "invalid". If the rule keyword in the signature is specified as "valid", the Match function would return TRUE if the checksum for that particular packet and protocol is valid. Similarly for "invalid".
The Setup functions takes 4 arguments -
DetectEngineCtx * (de_ctx) - A pointer to the detection engine context Signature *(s) - Pointer to signature for the current Signature being parsed from the rules SigMatchCtx * (m) - Pointer to the head of the SigMatchs added to the current Signature being parsed char * (csum_str) - Pointer to a string holding the keyword value
The Setup function returns 0 if it successfully parses the keyword value, and -1 otherwise.
The Match function takes 5 arguments -
ThreadVars * (t) - Pointer to the tv for the detection module instance DetectEngineThreadCtx * (det_ctx) - Pointer to the detection engine thread context Packet * (p) - Pointer to the Packet currently being handled Signature * (s) - Pointer to the Signature, the packet is being currently matched with SigMatchCtx * (m) - Pointer to the keyword structure from the above Signature, the Packet is being currently matched with
The Match function returns 1 if the Packet contents match the keyword, and 0 otherwise
The Free function takes a single argument -
void * (ptr) - Pointer to the DetectCsumData for a keyword
Definition at line 128 of file detect-csum.c.
References DETECT_ICMPV4_CSUM, DETECT_ICMPV6_CSUM, DETECT_IPV4_CSUM, DETECT_TCPV4_CSUM, DETECT_TCPV6_CSUM, DETECT_UDPV4_CSUM, DETECT_UDPV6_CSUM, DetectCsumRegisterTests(), DetectICMPV4CsumFree(), DetectICMPV4CsumMatch(), DetectICMPV6CsumFree(), DetectICMPV6CsumMatch(), DetectIPV4CsumFree(), DetectIPV4CsumMatch(), DetectTCPV4CsumFree(), DetectTCPV4CsumMatch(), DetectTCPV6CsumFree(), DetectTCPV6CsumMatch(), DetectUDPV4CsumFree(), DetectUDPV4CsumMatch(), DetectUDPV6CsumFree(), DetectUDPV6CsumMatch(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void DetectCsumRegisterTests (void)
Definition at line 1587 of file detect-csum.c.
Referenced by DetectCsumRegister().
void DetectICMPV4CsumFree (void * ptr)
Definition at line 778 of file detect-csum.c.
References SCFree.
Referenced by DetectCsumRegister().
int DetectICMPV4CsumMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Checks if the packet sent as the argument, has a valid or invalid icmpv4 checksum, based on whether icmpv4-csum option for this rule has been supplied with "valid" or "invalid" argument.
Parameters
t Pointer to the tv for this detection module instance
det_ctx Pointer to the detection engine thread context
p Pointer to the Packet currently being matched
s Pointer to the Signature, the packet is being currently matched with
m Pointer to the keyword_structure(SigMatch) from the above Signature, the Packet is being currently matched with
Return values
1 if the Packet contents match the keyword option; 0 otherwise
Definition at line 708 of file detect-csum.c.
References Packet_::flags, Packet_::icmpv4h, Packet_::ip4h, IPV4_GET_RAW_HLEN, IPV4_GET_RAW_IPLEN, Packet_::level4_comp_csum, PKT_IGNORE_CHECKSUM, PKT_IS_PSEUDOPKT, Packet_::proto, and DetectCsumData_::valid.
Referenced by DetectCsumRegister().
void DetectICMPV6CsumFree (void * ptr)
Definition at line 873 of file detect-csum.c.
References SCFree.
Referenced by DetectCsumRegister().
int DetectICMPV6CsumMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Checks if the packet sent as the argument, has a valid or invalid icmpv6 checksum, based on whether icmpv6-csum option for this rule has been supplied with "valid" or "invalid" argument.
Parameters
t Pointer to the tv for this detection module instance
det_ctx Pointer to the detection engine thread context
p Pointer to the Packet currently being matched
s Pointer to the Signature, the packet is being currently matched with
m Pointer to the keyword_structure(SigMatch) from the above Signature, the Packet is being currently matched with
Return values
1 if the Packet contents match the keyword option; 0 otherwise
Definition at line 803 of file detect-csum.c.
References ICMPV6Hdr_::csum, Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, Packet_::icmpv6h, Packet_::ip6h, Packet_::level4_comp_csum, PKT_IGNORE_CHECKSUM, PKT_IS_PSEUDOPKT, Packet_::proto, and DetectCsumData_::valid.
Referenced by DetectCsumRegister().
void DetectIPV4CsumFree (void * ptr)
Definition at line 301 of file detect-csum.c.
References SCFree.
Referenced by DetectCsumRegister().
int DetectIPV4CsumMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Checks if the packet sent as the argument, has a valid or invalid ipv4 checksum, based on whether ipv4-csum option for this rule has been supplied with "valid" or "invalid" argument.
Parameters
t Pointer to the tv for this detection module instance
det_ctx Pointer to the detection engine thread context
p Pointer to the Packet currently being matched
s Pointer to the Signature, the packet is being currently matched with
m Pointer to the keyword_structure(SigMatch) from the above Signature, the Packet is being currently matched with
Return values
1 if the Packet contents match the keyword option; 0 otherwise
Definition at line 232 of file detect-csum.c.
References Packet_::flags, Packet_::ip4h, IPV4_GET_HLEN, Packet_::level3_comp_csum, PKT_IGNORE_CHECKSUM, PKT_IS_PSEUDOPKT, and DetectCsumData_::valid.
Referenced by DetectCsumRegister().
void DetectTCPV4CsumFree (void * ptr)
Definition at line 396 of file detect-csum.c.
References SCFree.
Referenced by DetectCsumRegister().
int DetectTCPV4CsumMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Checks if the packet sent as the argument, has a valid or invalid tcpv4 checksum, based on whether tcpv4-csum option for this rule has been supplied with "valid" or "invalid" argument.
Parameters
t Pointer to the tv for this detection module instance
det_ctx Pointer to the detection engine thread context
p Pointer to the Packet currently being matched
s Pointer to the Signature, the packet is being currently matched with
m Pointer to the keyword_structure(SigMatch) from the above Signature, the Packet is being currently matched with
Return values
1 if the Packet contents match the keyword option; 0 otherwise
Definition at line 326 of file detect-csum.c.
References Packet_::flags, Packet_::ip4h, Packet_::level4_comp_csum, Packet_::payload_len, PKT_IGNORE_CHECKSUM, PKT_IS_PSEUDOPKT, Packet_::proto, TCP_GET_HLEN, Packet_::tcph, and DetectCsumData_::valid.
Referenced by DetectCsumRegister().
void DetectTCPV6CsumFree (void * ptr)
Definition at line 491 of file detect-csum.c.
References SCFree.
Referenced by DetectCsumRegister().
int DetectTCPV6CsumMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Checks if the packet sent as the argument, has a valid or invalid tcpv6 checksum, based on whether tcpv6-csum option for this rule has been supplied with "valid" or "invalid" argument.
Parameters
t Pointer to the tv for this detection module instance
det_ctx Pointer to the detection engine thread context
p Pointer to the Packet currently being matched
s Pointer to the Signature, the packet is being currently matched with
m Pointer to the keyword_structure(SigMatch) from the above Signature, the Packet is being currently matched with
Return values
1 if the Packet contents match the keyword option; 0 otherwise
Definition at line 421 of file detect-csum.c.
References Packet_::flags, Packet_::ip6h, Packet_::level4_comp_csum, Packet_::payload_len, PKT_IGNORE_CHECKSUM, PKT_IS_PSEUDOPKT, Packet_::proto, TCP_GET_HLEN, Packet_::tcph, and DetectCsumData_::valid.
Referenced by DetectCsumRegister().
void DetectUDPV4CsumFree (void * ptr)
Definition at line 587 of file detect-csum.c.
References SCFree.
Referenced by DetectCsumRegister().
int DetectUDPV4CsumMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Checks if the packet sent as the argument, has a valid or invalid udpv4 checksum, based on whether udpv4-csum option for this rule has been supplied with "valid" or "invalid" argument.
Parameters
t Pointer to the tv for this detection module instance
det_ctx Pointer to the detection engine thread context
p Pointer to the Packet currently being matched
s Pointer to the Signature, the packet is being currently matched with
m Pointer to the keyword_structure(SigMatch) from the above Signature, the Packet is being currently matched with
Return values
1 if the Packet contents match the keyword option; 0 otherwise
Definition at line 516 of file detect-csum.c.
References Packet_::flags, Packet_::ip4h, Packet_::level4_comp_csum, Packet_::payload_len, PKT_IGNORE_CHECKSUM, PKT_IS_PSEUDOPKT, Packet_::proto, UDP_HEADER_LEN, Packet_::udph, and DetectCsumData_::valid.
Referenced by DetectCsumRegister().
void DetectUDPV6CsumFree (void * ptr)
Definition at line 683 of file detect-csum.c.
References SCFree.
Referenced by DetectCsumRegister().
int DetectUDPV6CsumMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Checks if the packet sent as the argument, has a valid or invalid udpv6 checksum, based on whether udpv6-csum option for this rule has been supplied with "valid" or "invalid" argument.
Parameters
t Pointer to the tv for this detection module instance
det_ctx Pointer to the detection engine thread context
p Pointer to the Packet currently being matched
s Pointer to the Signature, the packet is being currently matched with
m Pointer to the keyword_structure(SigMatch) from the above Signature, the Packet is being currently matched with
Return values
1 if the Packet contents match the keyword option; 0 otherwise
Definition at line 612 of file detect-csum.c.
References Packet_::flags, Packet_::ip6h, Packet_::level4_comp_csum, Packet_::payload_len, PKT_IGNORE_CHECKSUM, PKT_IS_PSEUDOPKT, Packet_::proto, UDP_HEADER_LEN, Packet_::udph, and DetectCsumData_::valid.
Referenced by DetectCsumRegister().