suricata: src/detect-engine-siggroup.c File Reference
detect-engine-siggroup.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "flow-var.h"
#include "app-layer-protos.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-address.h"
#include "detect-engine-mpm.h"
#include "detect-engine-siggroup.h"
#include "detect-content.h"
#include "detect-uricontent.h"
#include "util-hash.h"
#include "util-hashlist.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-cidr.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-memcmp.h"
Functions
int SigGroupHeadClearSigs (SigGroupHead *sgh)
Clears the bitarray holding the sids for this SigGroupHead.
void SigGroupHeadInitDataFree (SigGroupHeadInitData *sghid)
void SigGroupHeadStore (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
void SigGroupHeadFree (SigGroupHead *sgh)
Free a SigGroupHead and its members.
uint32_t SigGroupHeadMpmHashFunc (HashListTable *ht, void *data, uint16_t datalen)
The hash function to be the used by the mpm SigGroupHead hash table - DetectEngineCtx->sgh_mpm_hash_table.
char SigGroupHeadMpmCompareFunc (void *data1, uint16_t len1, void *data2, uint16_t len2)
The Compare function to be used by the mpm SigGroupHead hash table - DetectEngineCtx->sgh_mpm_hash_table.
int SigGroupHeadMpmHashInit (DetectEngineCtx *de_ctx)
Initializes the SigGroupHead mpm hash table to be used by the detection engine context.
int SigGroupHeadMpmHashAdd (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Adds a SigGroupHead to the detection engine context SigGroupHead mpm hash table.
SigGroupHead * SigGroupHeadMpmHashLookup (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Used to lookup a SigGroupHead from the detection engine context SigGroupHead mpm hash table.
void SigGroupHeadMpmHashFree (DetectEngineCtx *de_ctx)
Frees the hash table - DetectEngineCtx->sgh_mpm_hash_table, allocated by SigGroupHeadMpmHashInit() function.
uint32_t SigGroupHeadMpmUriHashFunc (HashListTable *ht, void *data, uint16_t datalen)
The hash function to be the used by the mpm uri SigGroupHead hash table - DetectEngineCtx->sgh_mpm_uri_hash_table.
char SigGroupHeadMpmUriCompareFunc (void *data1, uint16_t len1, void *data2, uint16_t len2)
The Compare function to be used by the mpm uri SigGroupHead hash table - DetectEngineCtx->sgh_mpm_uri_hash_table.
int SigGroupHeadMpmUriHashInit (DetectEngineCtx *de_ctx)
Initializes the mpm uri hash table to be used by the detection engine context.
int SigGroupHeadMpmUriHashAdd (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Adds a SigGroupHead to the detection engine context SigGroupHead mpm uri hash table.
SigGroupHead * SigGroupHeadMpmUriHashLookup (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Used to lookup a SigGroupHead from the detection engine context SigGroupHead mpm uri hash table.
void SigGroupHeadMpmUriHashFree (DetectEngineCtx *de_ctx)
Frees the hash table - DetectEngineCtx->sgh_mpm_uri_hash_table, allocated by SigGroupHeadMpmUriHashInit() function.
uint32_t SigGroupHeadMpmStreamHashFunc (HashListTable *ht, void *data, uint16_t datalen)
The hash function to be the used by the mpm uri SigGroupHead hash table - DetectEngineCtx->sgh_mpm_uri_hash_table.
char SigGroupHeadMpmStreamCompareFunc (void *data1, uint16_t len1, void *data2, uint16_t len2)
The Compare function to be used by the mpm uri SigGroupHead hash table - DetectEngineCtx->sgh_mpm_uri_hash_table.
int SigGroupHeadMpmStreamHashInit (DetectEngineCtx *de_ctx)
Initializes the mpm uri hash table to be used by the detection engine context.
int SigGroupHeadMpmStreamHashAdd (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Adds a SigGroupHead to the detection engine context SigGroupHead mpm uri hash table.
SigGroupHead * SigGroupHeadMpmStreamHashLookup (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Used to lookup a SigGroupHead from the detection engine context SigGroupHead mpm uri hash table.
void SigGroupHeadMpmStreamHashFree (DetectEngineCtx *de_ctx)
Frees the hash table - DetectEngineCtx->sgh_mpm_uri_hash_table, allocated by SigGroupHeadMpmUriHashInit() function.
uint32_t SigGroupHeadHashFunc (HashListTable *ht, void *data, uint16_t datalen)
The hash function to be the used by the hash table - DetectEngineCtx->sgh_hash_table.
char SigGroupHeadCompareFunc (void *data1, uint16_t len1, void *data2, uint16_t len2)
The Compare function to be used by the SigGroupHead hash table - DetectEngineCtx->sgh_hash_table.
int SigGroupHeadHashInit (DetectEngineCtx *de_ctx)
Initializes the hash table in the detection engine context to hold the SigGroupHeads.
int SigGroupHeadHashAdd (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Adds a SigGroupHead to the detection engine context SigGroupHead hash table.
int SigGroupHeadHashRemove (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
SigGroupHead * SigGroupHeadHashLookup (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Used to lookup a SigGroupHead hash from the detection engine context SigGroupHead hash table.
void SigGroupHeadHashFree (DetectEngineCtx *de_ctx)
Frees the hash table - DetectEngineCtx->sgh_hash_table, allocated by SigGroupHeadHashInit() function.
int SigGroupHeadDPortHashInit (DetectEngineCtx *de_ctx)
Initializes the dport based SigGroupHead hash table to hold the SigGroupHeads. The hash table that would be initialized is DetectEngineCtx->sgh_dport_hash_table.
int SigGroupHeadDPortHashAdd (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Adds a SigGroupHead to the detection engine context dport based SigGroupHead hash table(DetectEngineCtx->sgh_dport_hash_table).
SigGroupHead * SigGroupHeadDPortHashLookup (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Used to lookup a SigGroupHead hash from the detection engine ctx dport based SigGroupHead hash table(DetectEngineCtx->sgh_dport_hash_table).
void SigGroupHeadDPortHashFree (DetectEngineCtx *de_ctx)
Frees the hash table - DetectEngineCtx->sgh_dport_hash_table, allocated by the SigGroupHeadDPortHashInit() function.
int SigGroupHeadSPortHashInit (DetectEngineCtx *de_ctx)
Initializes the sport based SigGroupHead hash table to hold the SigGroupHeads. The hash table that would be initialized is DetectEngineCtx->sgh_sport_hash_table.
int SigGroupHeadSPortHashAdd (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Adds a SigGroupHead to the detection engine context dport based SigGroupHead hash table(DetectEngineCtx->sgh_sport_hash_table).
int SigGroupHeadSPortHashRemove (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
SigGroupHead * SigGroupHeadSPortHashLookup (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Used to lookup a SigGroupHead hash from the detection engine ctx sport based SigGroupHead hash table(DetectEngineCtx->sgh_dport_hash_table).
void SigGroupHeadSPortHashFree (DetectEngineCtx *de_ctx)
Frees the hash table - DetectEngineCtx->sgh_sport_hash_table, allocated by the SigGroupHeadSPortHashInit() function.
void SigGroupHeadFreeSigArrays (DetectEngineCtx *de_ctx)
Free the sigarrays in the sgh's. Those are only used during the init stage.
void SigGroupHeadFreeMpmArrays (DetectEngineCtx *de_ctx)
Free the mpm arrays that are only used during the init stage.
int SigGroupHeadAppendSig (DetectEngineCtx *de_ctx, SigGroupHead **sgh, Signature *s)
Add a Signature to a SigGroupHead.
int SigGroupHeadCopySigs (DetectEngineCtx *de_ctx, SigGroupHead *src, SigGroupHead **dst)
Copies the bitarray holding the sids from the source SigGroupHead to the destination SigGroupHead.
void SigGroupHeadSetSigCnt (SigGroupHead *sgh, uint32_t max_idx)
Updates the SigGroupHead->sig_cnt with the total count of all the Signatures present in this SigGroupHead.
void DetectSigGroupPrintMemory (void)
Prints the memory statistics for the detect-engine-siggroup.[ch] module.
void SigGroupHeadPrintSigs (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Helper function used to print the list of sids for the Signatures present in this SigGroupHead.
void SigGroupHeadPrintContent (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Helper function used to print the content ids of all the contents that have been added to the bitarray of this SigGroupHead.
void SigGroupHeadPrintContentCnt (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Helper function used to print the total no of contents that have been added to the bitarray for this SigGroupHead.
int SigGroupHeadLoadContent (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Loads all the content ids from all the contents belonging to all the Signatures in this SigGroupHead, into a bitarray. A fast and an efficient way of comparing pattern sets.
int SigGroupHeadClearContent (SigGroupHead *sh)
Clears the memory allocated by SigGroupHeadLoadContent() for the bitarray to hold the content ids for a SigGroupHead.
int SigGroupHeadLoadUricontent (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Loads all the uri content ids from all the uri contents belonging to all the Signatures in this SigGroupHead, into a bitarray. A fast and an efficient way of comparing pattern sets.
int SigGroupHeadClearUricontent (SigGroupHead *sh)
Clears the memory allocated by SigGroupHeadLoadUriContent() for the bitarray to hold the uri content ids for a SigGroupHead.
int SigGroupHeadLoadStreamContent (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Loads all the content ids from all the contents belonging to all the Signatures in this SigGroupHead, into a bitarray. A fast and an efficient way of comparing pattern sets.
int SigGroupHeadClearStreamContent (SigGroupHead *sh)
Clears the memory allocated by SigGroupHeadLoadContent() for the bitarray to hold the content ids for a SigGroupHead.
int SigGroupHeadBuildMatchArray (DetectEngineCtx *de_ctx, SigGroupHead *sgh, uint32_t max_idx)
Create an array with all the internal ids of the sigs that this sig group head will check for.
void SigGroupHeadSetFilemagicFlag (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Set the need md5 flag in the sgh.
uint16_t SigGroupHeadGetMinMpmSize (DetectEngineCtx *de_ctx, SigGroupHead *sgh, int list)
Get size of the shortest mpm pattern.
void SigGroupHeadSetFilesizeFlag (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Set the need size flag in the sgh.
void SigGroupHeadSetFileMd5Flag (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Set the need magic flag in the sgh.
void SigGroupHeadSetFilestoreCount (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
Set the filestore_cnt in the sgh.
int SigGroupHeadBuildNonMpmArray (DetectEngineCtx *de_ctx, SigGroupHead *sgh)
build an array of rule id's for sigs with no mpm Also updated de_ctx::non_mpm_store_cnt_max to track the highest cnt
int SigGroupHeadContainsSigId (DetectEngineCtx *de_ctx, SigGroupHead *sgh, uint32_t sid)
Check if a SigGroupHead contains a Signature, whose sid is sent as an argument.
void SigGroupHeadRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Signature grouping part of the detection engine.
Definition in file detect-engine-siggroup.c.
Function Documentation
void DetectSigGroupPrintMemory (void)
Prints the memory statistics for the detect-engine-siggroup.[ch] module.
Definition at line 1148 of file detect-engine-siggroup.c.
References SCLogDebug.
int SigGroupHeadAppendSig (DetectEngineCtx * de_ctx, SigGroupHead ** sgh, Signature * s)
Add a Signature to a SigGroupHead.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to a SigGroupHead. Can be NULL also.
s Pointer to the Signature that has to be added to the SigGroupHead.
Return values
0 On success.
-1 On failure.
Definition at line 1023 of file detect-engine-siggroup.c.
References DETECT_SM_LIST_PMATCH, DetectEngineGetMaxSigId, SigGroupHead_::mpm_content_minlen, Signature_::num, SCLogDebug, and Signature_::sm_lists.
Referenced by BuildDestinationAddressHeads(), and BuildDestinationAddressHeadsWithBothPorts().
int SigGroupHeadBuildMatchArray (DetectEngineCtx * de_ctx, SigGroupHead * sgh, uint32_t max_idx)
Create an array with all the internal ids of the sigs that this sig group head will check for.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
max_idx The maximum value of the sid in the SigGroupHead arg.
Return values
0 success
-1 error
Definition at line 1538 of file detect-engine-siggroup.c.
References BUG_ON, SigGroupHead_::init, SigGroupHead_::match_array, SCMalloc, DetectEngineCtx_::sig_array, SigGroupHeadInitData_::sig_array, and SigGroupHead_::sig_cnt.
Referenced by BuildDestinationAddressHeads(), and BuildDestinationAddressHeadsWithBothPorts().
int SigGroupHeadBuildNonMpmArray (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
build an array of rule id's for sigs with no mpm Also updated de_ctx::non_mpm_store_cnt_max to track the highest cnt
Definition at line 1725 of file detect-engine-siggroup.c.
References BUG_ON, Signature_::flags, SignatureNonMpmStore_::id, Signature_::mask, SignatureNonMpmStore_::mask, SigGroupHead_::match_array, Signature_::mpm_sm, SigGroupHead_::non_mpm_store_array, SigGroupHead_::non_mpm_store_cnt, DetectEngineCtx_::non_mpm_store_cnt_max, Signature_::num, SCMalloc, SigGroupHead_::sig_cnt, SIG_FLAG_MPM_APPLAYER_NEG, SIG_FLAG_MPM_PACKET_NEG, and SIG_FLAG_MPM_STREAM_NEG.
Referenced by SigAddressPrepareStage4().
int SigGroupHeadClearContent (SigGroupHead * sh)
Clears the memory allocated by SigGroupHeadLoadContent() for the bitarray to hold the content ids for a SigGroupHead.
Parameters
Pointer to the SigGroupHead whose content_array would to be cleared.
0 Always.
Definition at line 1344 of file detect-engine-siggroup.c.
References SigGroupHeadInitData_::content_array, SigGroupHeadInitData_::content_size, SigGroupHead_::init, and SCFree.
int SigGroupHeadClearSigs (SigGroupHead * sgh)
Clears the bitarray holding the sids for this SigGroupHead.
Parameters
sgh Pointer to the SigGroupHead.
Return values
0 Always.
Definition at line 1066 of file detect-engine-siggroup.c.
References SigGroupHead_::init, SigGroupHeadInitData_::sig_array, SigGroupHead_::sig_cnt, and SigGroupHeadInitData_::sig_size.
Referenced by DetectAddressCutIPv4(), and DetectAddressCutIPv6().
int SigGroupHeadClearStreamContent (SigGroupHead * sh)
Clears the memory allocated by SigGroupHeadLoadContent() for the bitarray to hold the content ids for a SigGroupHead.
Parameters
Pointer to the SigGroupHead whose content_array would to be cleared.
0 Always.
Definition at line 1514 of file detect-engine-siggroup.c.
References SigGroupHead_::init, SCFree, SigGroupHeadInitData_::stream_content_array, and SigGroupHeadInitData_::stream_content_size.
int SigGroupHeadClearUricontent (SigGroupHead * sh)
Clears the memory allocated by SigGroupHeadLoadUriContent() for the bitarray to hold the uri content ids for a SigGroupHead.
Parameters
Pointer to the SigGroupHead whose uri_content_array would to be cleared.
Return values
0 Always.
Definition at line 1423 of file detect-engine-siggroup.c.
References SigGroupHead_::init, SCFree, SigGroupHeadInitData_::uri_content_array, and SigGroupHeadInitData_::uri_content_size.
char SigGroupHeadCompareFunc (void * data1, uint16_t len1, void * data2, uint16_t len2)
The Compare function to be used by the SigGroupHead hash table - DetectEngineCtx->sgh_hash_table.
Parameters
data1 Pointer to the first SigGroupHead.
len1 Not used.
data2 Pointer to the second SigGroupHead.
len2 Not used.
Return values
1 If the 2 SigGroupHeads sent as args match.
0 If the 2 SigGroupHeads sent as args do not match.
Definition at line 633 of file detect-engine-siggroup.c.
References SigGroupHead_::init, SCMemcmp, SigGroupHeadInitData_::sig_array, and SigGroupHeadInitData_::sig_size.
Referenced by SigGroupHeadDPortHashInit(), SigGroupHeadHashInit(), and SigGroupHeadSPortHashInit().
int SigGroupHeadContainsSigId (DetectEngineCtx * de_ctx, SigGroupHead * sgh, uint32_t sid)
Check if a SigGroupHead contains a Signature, whose sid is sent as an argument.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead that has to be checked for the presence of a Signature.
sid The Signature id(sid) that has to be checked in the SigGroupHead.
Return values
1 On successfully finding the sid in the SigGroupHead.
0 If the sid is not found in the SigGroupHead
Definition at line 1793 of file detect-engine-siggroup.c.
References DetectEngineGetMaxSigId, Signature_::id, SigGroupHead_::init, SCEnter, SCReturnInt, DetectEngineCtx_::sig_array, and SigGroupHeadInitData_::sig_array.
int SigGroupHeadCopySigs (DetectEngineCtx * de_ctx, SigGroupHead * src, SigGroupHead ** dst)
Copies the bitarray holding the sids from the source SigGroupHead to the destination SigGroupHead.
Parameters
de_ctx Pointer to the detection engine context.
src Pointer to the source SigGroupHead.
dst Pointer to the destination SigGroupHead.
Return values
0 On success.
-1 On failure.
Definition at line 1090 of file detect-engine-siggroup.c.
References BUG_ON, DetectEngineGetMaxSigId, SigGroupHead_::init, SigGroupHead_::mpm_content_minlen, SCLogDebug, SigGroupHeadInitData_::sig_array, and SigGroupHeadInitData_::sig_size.
Referenced by CreateGroupedAddrList(), DetectAddressCutIPv4(), DetectAddressCutIPv6(), DetectAddressInsert(), DetectAddressJoin(), DetectPortCopySingle(), DetectPortInsert(), and DetectPortJoin().
int SigGroupHeadDPortHashAdd (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Adds a SigGroupHead to the detection engine context dport based SigGroupHead hash table(DetectEngineCtx->sgh_dport_hash_table).
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
ret 0 on Successfully adding the argument sgh and -1 on failure.
Definition at line 764 of file detect-engine-siggroup.c.
References HashListTableAdd(), and DetectEngineCtx_::sgh_dport_hash_table.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void SigGroupHeadDPortHashFree (DetectEngineCtx * de_ctx)
Frees the hash table - DetectEngineCtx->sgh_dport_hash_table, allocated by the SigGroupHeadDPortHashInit() function.
Parameters
de_ctx Pointer to the detection engine context.
Definition at line 798 of file detect-engine-siggroup.c.
References HashListTableFree(), and DetectEngineCtx_::sgh_dport_hash_table.
Referenced by DetectEngineCtxFree(), and SigAddressPrepareStage3().
int SigGroupHeadDPortHashInit (DetectEngineCtx * de_ctx)
Initializes the dport based SigGroupHead hash table to hold the SigGroupHeads. The hash table that would be initialized is DetectEngineCtx->sgh_dport_hash_table.
Parameters
de_ctx Pointer to the detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 741 of file detect-engine-siggroup.c.
References HashListTableInit(), DetectEngineCtx_::sgh_dport_hash_table, SigGroupHeadCompareFunc(), and SigGroupHeadHashFunc().
SigGroupHead* SigGroupHeadDPortHashLookup (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Used to lookup a SigGroupHead hash from the detection engine ctx dport based SigGroupHead hash table(DetectEngineCtx->sgh_dport_hash_table).
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
rsgh On success a pointer to the SigGroupHead if the SigGroupHead is found in the hash table; NULL on failure.
Definition at line 781 of file detect-engine-siggroup.c.
References HashListTableLookup(), SCEnter, SCReturnPtr, and DetectEngineCtx_::sgh_dport_hash_table.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void SigGroupHeadFree (SigGroupHead * sgh)
Free a SigGroupHead and its members.
Parameters
sgh Pointer to the SigGroupHead that has to be freed.
Definition at line 179 of file detect-engine-siggroup.c.
References SigGroupHead_::init, SigGroupHead_::match_array, SigGroupHead_::non_mpm_store_array, SigGroupHead_::non_mpm_store_cnt, PatternMatchDestroyGroup(), SCFree, SCLogDebug, SigGroupHead_::sig_cnt, and SigGroupHeadInitDataFree().
Referenced by BuildDestinationAddressHeads(), BuildDestinationAddressHeadsWithBothPorts(), DetectAddressFree(), DetectPortFree(), and SigAddressCleanupStage1().
void SigGroupHeadFreeMpmArrays (DetectEngineCtx * de_ctx)
Free the mpm arrays that are only used during the init stage.
Parameters
de_ctx Pointer to the detection engine context.
Definition at line 977 of file detect-engine-siggroup.c.
References HashListTableGetListData, HashListTableGetListHead(), HashListTableGetListNext, SigGroupHead_::init, DetectEngineCtx_::sgh_dport_hash_table, DetectEngineCtx_::sgh_sport_hash_table, and SigGroupHeadInitDataFree().
Referenced by SigAddressPrepareStage3().
void SigGroupHeadFreeSigArrays (DetectEngineCtx * de_ctx)
Free the sigarrays in the sgh's. Those are only used during the init stage.
Parameters
de_ctx Pointer to the detection engine context whose sigarrays have to be freed.
Definition at line 963 of file detect-engine-siggroup.c.
References DetectEngineCtx_::sgh_dport_hash_table, DetectEngineCtx_::sgh_hash_table, and DetectEngineCtx_::sgh_sport_hash_table.
Referenced by SigAddressPrepareStage3().
uint16_t SigGroupHeadGetMinMpmSize (DetectEngineCtx * de_ctx, SigGroupHead * sgh, int list)
Get size of the shortest mpm pattern.
Parameters
de_ctx detection engine ctx for the signatures
sgh sig group head to set the flag in
list sm_list to consider
Definition at line 1609 of file detect-engine-siggroup.c.
References DETECT_SM_LIST_PMATCH, SigGroupHead_::match_array, SCLogDebug, and SigGroupHead_::sig_cnt.
Referenced by SigAddressPrepareStage4().
int SigGroupHeadHashAdd (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Adds a SigGroupHead to the detection engine context SigGroupHead hash table.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
ret 0 on Successfully adding the SigGroupHead; -1 on failure.
Definition at line 682 of file detect-engine-siggroup.c.
References HashListTableAdd(), and DetectEngineCtx_::sgh_hash_table.
Referenced by BuildDestinationAddressHeads(), and BuildDestinationAddressHeadsWithBothPorts().
void SigGroupHeadHashFree (DetectEngineCtx * de_ctx)
Frees the hash table - DetectEngineCtx->sgh_hash_table, allocated by SigGroupHeadHashInit() function.
Parameters
de_ctx Pointer to the detection engine context.
Definition at line 720 of file detect-engine-siggroup.c.
References HashListTableFree(), and DetectEngineCtx_::sgh_hash_table.
Referenced by DetectEngineCtxFree(), and SigAddressPrepareStage3().
uint32_t SigGroupHeadHashFunc (HashListTable * ht, void * data, uint16_t datalen)
The hash function to be the used by the hash table - DetectEngineCtx->sgh_hash_table.
Parameters
ht Pointer to the hash table.
data Pointer to the SigGroupHead.
datalen Not used in our case.
Return values
hash The generated hash value.
Definition at line 605 of file detect-engine-siggroup.c.
References HashListTable_::array_size, SigGroupHead_::init, SigGroupHead_::mpm_content_minlen, SCLogDebug, SigGroupHeadInitData_::sig_array, and SigGroupHeadInitData_::sig_size.
Referenced by SigGroupHeadDPortHashInit(), SigGroupHeadHashInit(), and SigGroupHeadSPortHashInit().
int SigGroupHeadHashInit (DetectEngineCtx * de_ctx)
Initializes the hash table in the detection engine context to hold the SigGroupHeads.
Parameters
de_ctx Pointer to the detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 660 of file detect-engine-siggroup.c.
References HashListTableInit(), DetectEngineCtx_::sgh_hash_table, SigGroupHeadCompareFunc(), and SigGroupHeadHashFunc().
SigGroupHead* SigGroupHeadHashLookup (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Used to lookup a SigGroupHead hash from the detection engine context SigGroupHead hash table.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
rsgh On success a pointer to the SigGroupHead if the SigGroupHead is found in the hash table; NULL on failure.
Definition at line 704 of file detect-engine-siggroup.c.
References HashListTableLookup(), SCEnter, SCReturnPtr, and DetectEngineCtx_::sgh_hash_table.
Referenced by BuildDestinationAddressHeads(), and BuildDestinationAddressHeadsWithBothPorts().
int SigGroupHeadHashRemove (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Definition at line 689 of file detect-engine-siggroup.c.
References HashListTableRemove(), and DetectEngineCtx_::sgh_hash_table.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void SigGroupHeadInitDataFree (SigGroupHeadInitData * sghid)
Definition at line 69 of file detect-engine-siggroup.c.
References SigGroupHeadInitData_::content_array, SigGroupHeadInitData_::content_size, SCFree, SigGroupHeadInitData_::sig_array, SigGroupHeadInitData_::sig_size, SigGroupHeadInitData_::uri_content_array, and SigGroupHeadInitData_::uri_content_size.
Referenced by SigGroupHeadFree(), and SigGroupHeadFreeMpmArrays().
int SigGroupHeadLoadContent (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Loads all the content ids from all the contents belonging to all the Signatures in this SigGroupHead, into a bitarray. A fast and an efficient way of comparing pattern sets.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
0 On success, i.e. on either the detection engine context being NULL or on successfully allocating memory and updating it with relevant data.
-1 On failure.
Definition at line 1290 of file detect-engine-siggroup.c.
References Signature_::alproto, ALPROTO_UNKNOWN, BUG_ON, SigGroupHeadInitData_::content_array, SigGroupHeadInitData_::content_size, SigMatch_::ctx, DETECT_CONTENT, DETECT_SM_LIST_PMATCH, DetectContentMaxId(), DetectContentData_::id, SigGroupHead_::init, SigGroupHead_::match_array, SigMatch_::next, SCMalloc, SigGroupHead_::sig_cnt, Signature_::sm_lists, and SigMatch_::type.
int SigGroupHeadLoadStreamContent (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Loads all the content ids from all the contents belonging to all the Signatures in this SigGroupHead, into a bitarray. A fast and an efficient way of comparing pattern sets.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
0 On success, i.e. on either the detection engine context being NULL or on successfully allocating memory and updating it with relevant data.
-1 On failure.
Definition at line 1450 of file detect-engine-siggroup.c.
References BUG_ON, SigMatch_::ctx, DETECT_CONTENT, DETECT_SM_LIST_PMATCH, DetectContentMaxId(), DetectContentData_::id, Signature_::id, SigGroupHead_::init, SigGroupHead_::match_array, SigMatch_::next, SCEnter, SCLogDebug, SCMalloc, SCReturnInt, SigGroupHead_::sig_cnt, SignatureHasPacketContent(), Signature_::sm_lists, SigGroupHeadInitData_::stream_content_array, SigGroupHeadInitData_::stream_content_size, and SigMatch_::type.
int SigGroupHeadLoadUricontent (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Loads all the uri content ids from all the uri contents belonging to all the Signatures in this SigGroupHead, into a bitarray. A fast and an efficient way of comparing pattern sets.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
0 On success, i.e. on either the detection engine context being NULL or on successfully allocating memory and updating it with relevant data.
-1 On failure.
Definition at line 1370 of file detect-engine-siggroup.c.
References BUG_ON, SigMatch_::ctx, DETECT_CONTENT, DETECT_SM_LIST_UMATCH, DetectUricontentMaxId(), DetectContentData_::id, SigGroupHead_::init, SigGroupHead_::match_array, SigMatch_::next, SCMalloc, SigGroupHead_::sig_cnt, Signature_::sm_lists, SigMatch_::type, SigGroupHeadInitData_::uri_content_array, and SigGroupHeadInitData_::uri_content_size.
char SigGroupHeadMpmCompareFunc (void * data1, uint16_t len1, void * data2, uint16_t len2)
The Compare function to be used by the mpm SigGroupHead hash table - DetectEngineCtx->sgh_mpm_hash_table.
Parameters
data1 Pointer to the first SigGroupHead.
len1 Not used.
data2 Pointer to the second SigGroupHead.
len2 Not used.
Return values
1 If the 2 SigGroupHeads sent as args match.
0 If the 2 SigGroupHeads sent as args do not match.
Definition at line 250 of file detect-engine-siggroup.c.
References SigGroupHeadInitData_::content_array, SigGroupHeadInitData_::content_size, SigGroupHead_::init, and SCMemcmp.
Referenced by SigGroupHeadMpmHashInit().
int SigGroupHeadMpmHashAdd (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Adds a SigGroupHead to the detection engine context SigGroupHead mpm hash table.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
ret 0 on Successfully adding the argument sgh; -1 on failure.
Definition at line 300 of file detect-engine-siggroup.c.
References HashListTableAdd(), and DetectEngineCtx_::sgh_mpm_hash_table.
void SigGroupHeadMpmHashFree (DetectEngineCtx * de_ctx)
Frees the hash table - DetectEngineCtx->sgh_mpm_hash_table, allocated by SigGroupHeadMpmHashInit() function.
Parameters
de_ctx Pointer to the detection engine context.
Definition at line 332 of file detect-engine-siggroup.c.
References HashListTableFree(), and DetectEngineCtx_::sgh_mpm_hash_table.
Referenced by DetectEngineCtxFree(), and SigAddressPrepareStage3().
uint32_t SigGroupHeadMpmHashFunc (HashListTable * ht, void * data, uint16_t datalen)
The hash function to be the used by the mpm SigGroupHead hash table - DetectEngineCtx->sgh_mpm_hash_table.
Parameters
ht Pointer to the hash table.
data Pointer to the SigGroupHead.
datalen Not used in our case.
Return values
hash The generated hash value.
Definition at line 226 of file detect-engine-siggroup.c.
References HashListTable_::array_size, SigGroupHeadInitData_::content_array, SigGroupHeadInitData_::content_size, and SigGroupHead_::init.
Referenced by SigGroupHeadMpmHashInit().
int SigGroupHeadMpmHashInit (DetectEngineCtx * de_ctx)
Initializes the SigGroupHead mpm hash table to be used by the detection engine context.
Parameters
de_ctx Pointer to the detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 276 of file detect-engine-siggroup.c.
References HashListTableInit(), DetectEngineCtx_::sgh_mpm_hash_table, SigGroupHeadMpmCompareFunc(), and SigGroupHeadMpmHashFunc().
SigGroupHead* SigGroupHeadMpmHashLookup (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Used to lookup a SigGroupHead from the detection engine context SigGroupHead mpm hash table.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
rsgh On success a pointer to the SigGroupHead if the SigGroupHead is found in the hash table; NULL on failure.
Definition at line 317 of file detect-engine-siggroup.c.
References HashListTableLookup(), and DetectEngineCtx_::sgh_mpm_hash_table.
char SigGroupHeadMpmStreamCompareFunc (void * data1, uint16_t len1, void * data2, uint16_t len2)
The Compare function to be used by the mpm uri SigGroupHead hash table - DetectEngineCtx->sgh_mpm_uri_hash_table.
Parameters
data1 Pointer to the first SigGroupHead.
len1 Not used.
data2 Pointer to the second SigGroupHead.
len2 Not used.
Return values
1 If the 2 SigGroupHeads sent as args match.
0 If the 2 SigGroupHeads sent as args do not match.
Definition at line 504 of file detect-engine-siggroup.c.
References SigGroupHead_::init, SCMemcmp, SigGroupHeadInitData_::stream_content_array, and SigGroupHeadInitData_::stream_content_size.
Referenced by SigGroupHeadMpmStreamHashInit().
int SigGroupHeadMpmStreamHashAdd (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Adds a SigGroupHead to the detection engine context SigGroupHead mpm uri hash table.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
ret 0 on Successfully adding the argument sgh and -1 on failure.
Definition at line 552 of file detect-engine-siggroup.c.
References HashListTableAdd(), and DetectEngineCtx_::sgh_mpm_stream_hash_table.
void SigGroupHeadMpmStreamHashFree (DetectEngineCtx * de_ctx)
Frees the hash table - DetectEngineCtx->sgh_mpm_uri_hash_table, allocated by SigGroupHeadMpmUriHashInit() function.
Parameters
de_ctx Pointer to the detection engine context.
Definition at line 584 of file detect-engine-siggroup.c.
References HashListTableFree(), and DetectEngineCtx_::sgh_mpm_stream_hash_table.
uint32_t SigGroupHeadMpmStreamHashFunc (HashListTable * ht, void * data, uint16_t datalen)
The hash function to be the used by the mpm uri SigGroupHead hash table - DetectEngineCtx->sgh_mpm_uri_hash_table.
Parameters
ht Pointer to the hash table.
data Pointer to the SigGroupHead.
datalen Not used in our case.
Return values
hash The generated hash value.
Definition at line 480 of file detect-engine-siggroup.c.
References HashListTable_::array_size, SigGroupHead_::init, SigGroupHeadInitData_::stream_content_array, and SigGroupHeadInitData_::stream_content_size.
Referenced by SigGroupHeadMpmStreamHashInit().
int SigGroupHeadMpmStreamHashInit (DetectEngineCtx * de_ctx)
Initializes the mpm uri hash table to be used by the detection engine context.
Parameters
de_ctx Pointer to the detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 530 of file detect-engine-siggroup.c.
References HashListTableInit(), DetectEngineCtx_::sgh_mpm_stream_hash_table, SigGroupHeadMpmStreamCompareFunc(), and SigGroupHeadMpmStreamHashFunc().
SigGroupHead* SigGroupHeadMpmStreamHashLookup (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Used to lookup a SigGroupHead from the detection engine context SigGroupHead mpm uri hash table.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
rsgh On success a pointer to the SigGroupHead if the SigGroupHead is found in the hash table; NULL on failure.
Definition at line 569 of file detect-engine-siggroup.c.
References HashListTableLookup(), and DetectEngineCtx_::sgh_mpm_stream_hash_table.
char SigGroupHeadMpmUriCompareFunc (void * data1, uint16_t len1, void * data2, uint16_t len2)
The Compare function to be used by the mpm uri SigGroupHead hash table - DetectEngineCtx->sgh_mpm_uri_hash_table.
Parameters
data1 Pointer to the first SigGroupHead.
len1 Not used.
data2 Pointer to the second SigGroupHead.
len2 Not used.
Return values
1 If the 2 SigGroupHeads sent as args match.
0 If the 2 SigGroupHeads sent as args do not match.
Definition at line 377 of file detect-engine-siggroup.c.
References SigGroupHead_::init, SCMemcmp, SigGroupHeadInitData_::uri_content_array, and SigGroupHeadInitData_::uri_content_size.
Referenced by SigGroupHeadMpmUriHashInit().
int SigGroupHeadMpmUriHashAdd (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Adds a SigGroupHead to the detection engine context SigGroupHead mpm uri hash table.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
ret 0 on Successfully adding the argument sgh and -1 on failure.
Definition at line 427 of file detect-engine-siggroup.c.
References HashListTableAdd(), and DetectEngineCtx_::sgh_mpm_uri_hash_table.
void SigGroupHeadMpmUriHashFree (DetectEngineCtx * de_ctx)
Frees the hash table - DetectEngineCtx->sgh_mpm_uri_hash_table, allocated by SigGroupHeadMpmUriHashInit() function.
Parameters
de_ctx Pointer to the detection engine context.
Definition at line 459 of file detect-engine-siggroup.c.
References HashListTableFree(), and DetectEngineCtx_::sgh_mpm_uri_hash_table.
Referenced by DetectEngineCtxFree(), and SigAddressPrepareStage3().
uint32_t SigGroupHeadMpmUriHashFunc (HashListTable * ht, void * data, uint16_t datalen)
The hash function to be the used by the mpm uri SigGroupHead hash table - DetectEngineCtx->sgh_mpm_uri_hash_table.
Parameters
ht Pointer to the hash table.
data Pointer to the SigGroupHead.
datalen Not used in our case.
Return values
hash The generated hash value.
Definition at line 353 of file detect-engine-siggroup.c.
References HashListTable_::array_size, SigGroupHead_::init, SigGroupHeadInitData_::uri_content_array, and SigGroupHeadInitData_::uri_content_size.
Referenced by SigGroupHeadMpmUriHashInit().
int SigGroupHeadMpmUriHashInit (DetectEngineCtx * de_ctx)
Initializes the mpm uri hash table to be used by the detection engine context.
Parameters
de_ctx Pointer to the detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 403 of file detect-engine-siggroup.c.
References HashListTableInit(), DetectEngineCtx_::sgh_mpm_uri_hash_table, SigGroupHeadMpmUriCompareFunc(), and SigGroupHeadMpmUriHashFunc().
SigGroupHead* SigGroupHeadMpmUriHashLookup (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Used to lookup a SigGroupHead from the detection engine context SigGroupHead mpm uri hash table.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
rsgh On success a pointer to the SigGroupHead if the SigGroupHead is found in the hash table; NULL on failure.
Definition at line 444 of file detect-engine-siggroup.c.
References HashListTableLookup(), and DetectEngineCtx_::sgh_mpm_uri_hash_table.
void SigGroupHeadPrintContent (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Helper function used to print the content ids of all the contents that have been added to the bitarray of this SigGroupHead.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Definition at line 1236 of file detect-engine-siggroup.c.
References SigGroupHeadInitData_::content_array, DetectContentMaxId(), SigGroupHead_::init, SCEnter, SCLogDebug, and SCReturn.
void SigGroupHeadPrintContentCnt (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Helper function used to print the total no of contents that have been added to the bitarray for this SigGroupHead.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Definition at line 1259 of file detect-engine-siggroup.c.
References SigGroupHeadInitData_::content_array, DetectContentMaxId(), SigGroupHead_::init, SCEnter, SCLogDebug, and SCReturn.
void SigGroupHeadPrintSigs (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Helper function used to print the list of sids for the Signatures present in this SigGroupHead.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Definition at line 1208 of file detect-engine-siggroup.c.
References SigGroupHead_::init, SCEnter, SCLogDebug, SCReturn, SigGroupHeadInitData_::sig_array, and SigGroupHeadInitData_::sig_size.
Referenced by SigAddressPrepareStage5().
void SigGroupHeadRegisterTests (void)
Definition at line 2405 of file detect-engine-siggroup.c.
Referenced by RunUnittests().
void SigGroupHeadSetFilemagicFlag (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Set the need md5 flag in the sgh.
Parameters
de_ctx detection engine ctx for the signatures
sgh sig group head to set the flag in
Definition at line 1580 of file detect-engine-siggroup.c.
References SigGroupHead_::flags, SigGroupHead_::match_array, SigGroupHead_::sig_cnt, SIG_GROUP_HEAD_HAVEFILEMAGIC, and SignatureIsFilemagicInspecting().
Referenced by SigAddressPrepareStage4().
void SigGroupHeadSetFileMd5Flag (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Set the need magic flag in the sgh.
Parameters
de_ctx detection engine ctx for the signatures
sgh sig group head to set the flag in
Definition at line 1672 of file detect-engine-siggroup.c.
References SigGroupHead_::flags, SigGroupHead_::match_array, SCLogDebug, SigGroupHead_::sig_cnt, SIG_GROUP_HEAD_HAVEFILEMD5, and SignatureIsFileMd5Inspecting().
Referenced by SigAddressPrepareStage4().
void SigGroupHeadSetFilesizeFlag (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Set the need size flag in the sgh.
Parameters
de_ctx detection engine ctx for the signatures
sgh sig group head to set the flag in
Definition at line 1644 of file detect-engine-siggroup.c.
References SigGroupHead_::flags, SigGroupHead_::match_array, SigGroupHead_::sig_cnt, SIG_GROUP_HEAD_HAVEFILESIZE, and SignatureIsFilesizeInspecting().
Referenced by SigAddressPrepareStage4().
void SigGroupHeadSetFilestoreCount (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Set the filestore_cnt in the sgh.
Parameters
de_ctx detection engine ctx for the signatures
sgh sig group head to set the counter in
Definition at line 1701 of file detect-engine-siggroup.c.
References SigGroupHead_::filestore_cnt, SigGroupHead_::match_array, SigGroupHead_::sig_cnt, and SignatureIsFilestoring().
Referenced by SigAddressPrepareStage4().
void SigGroupHeadSetSigCnt (SigGroupHead * sgh, uint32_t max_idx)
Updates the SigGroupHead->sig_cnt with the total count of all the Signatures present in this SigGroupHead.
Parameters
sgh Pointer to the SigGroupHead.
max_idx Maximum sid of the all the Signatures present in this SigGroupHead.
Definition at line 1132 of file detect-engine-siggroup.c.
References SigGroupHead_::init, SigGroupHeadInitData_::sig_array, and SigGroupHead_::sig_cnt.
Referenced by BuildDestinationAddressHeads(), and BuildDestinationAddressHeadsWithBothPorts().
int SigGroupHeadSPortHashAdd (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Adds a SigGroupHead to the detection engine context dport based SigGroupHead hash table(DetectEngineCtx->sgh_sport_hash_table).
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
ret 0 on Successfully adding the argument sgh and -1 on failure.
Definition at line 843 of file detect-engine-siggroup.c.
References HashListTableAdd(), and DetectEngineCtx_::sgh_sport_hash_table.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void SigGroupHeadSPortHashFree (DetectEngineCtx * de_ctx)
Frees the hash table - DetectEngineCtx->sgh_sport_hash_table, allocated by the SigGroupHeadSPortHashInit() function.
Parameters
de_ctx Pointer to the detection engine context.
Definition at line 880 of file detect-engine-siggroup.c.
References HashListTableFree(), and DetectEngineCtx_::sgh_sport_hash_table.
Referenced by DetectEngineCtxFree(), and SigAddressPrepareStage3().
int SigGroupHeadSPortHashInit (DetectEngineCtx * de_ctx)
Initializes the sport based SigGroupHead hash table to hold the SigGroupHeads. The hash table that would be initialized is DetectEngineCtx->sgh_sport_hash_table.
Parameters
de_ctx Pointer to the detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 819 of file detect-engine-siggroup.c.
References HashListTableInit(), DetectEngineCtx_::sgh_sport_hash_table, SigGroupHeadCompareFunc(), and SigGroupHeadHashFunc().
SigGroupHead* SigGroupHeadSPortHashLookup (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Used to lookup a SigGroupHead hash from the detection engine ctx sport based SigGroupHead hash table(DetectEngineCtx->sgh_dport_hash_table).
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the SigGroupHead.
Return values
rsgh On success a pointer to the SigGroupHead if the SigGroupHead is found in the hash table; NULL on failure.
Definition at line 865 of file detect-engine-siggroup.c.
References HashListTableLookup(), and DetectEngineCtx_::sgh_sport_hash_table.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
int SigGroupHeadSPortHashRemove (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Definition at line 850 of file detect-engine-siggroup.c.
References HashListTableRemove(), and DetectEngineCtx_::sgh_sport_hash_table.
void SigGroupHeadStore (DetectEngineCtx * de_ctx, SigGroupHead * sgh)
Definition at line 121 of file detect-engine-siggroup.c.
References SCFree, SCRealloc, DetectEngineCtx_::sgh_array, DetectEngineCtx_::sgh_array_cnt, and DetectEngineCtx_::sgh_array_size.
Referenced by BuildDestinationAddressHeads(), and BuildDestinationAddressHeadsWithBothPorts().