suricata: src/detect-engine-tag.c File Reference
detect-engine-tag.c File Reference
#include "suricata-common.h"
#include "detect-engine.h"
#include "util-hash.h"
#include "util-atomic.h"
#include "util-time.h"
#include "util-hashlist.h"
#include "detect-engine-tag.h"
#include "detect-tag.h"
#include "host.h"
#include "host-storage.h"
#include "flow-storage.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "flow-util.h"
#include "stream-tcp-private.h"
Functions
SC_ATOMIC_DECLARE (unsigned int, num_tags)
void TagInitCtx (void)
void TagDestroyCtx (void)
Destroy tag context hash tables.
void TagRestartCtx ()
Reset the tagging engine context.
int TagHostHasTag (Host *host)
int TagFlowAdd (Packet *p, DetectTagDataEntry *tde)
This function is used to add a tag to a session (type session) or update it if it's already installed. The number of times to allow an update is limited by DETECT_TAG_MATCH_LIMIT. This way repetitive matches to the same rule are limited of setting tags, to avoid DOS attacks.
int TagHashAddTag (DetectTagDataEntry *tde, Packet *p)
Add a tag entry for a host. If it already exist, update it.
void TagHandlePacketHost (Host *host, Packet *p)
void TagHandlePacket (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Packet *p)
Search tags for src and dst. Update entries of the tag, remove if necessary.
int TagTimeoutCheck (Host *host, struct timeval *tv)
Removes the entries exceding the max timeout value.
void DetectEngineTagRegisterTests (void)
this function registers unit tests for DetectTag
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements a global context to store data related to hosts flagged tag keyword
Definition in file detect-engine-tag.c.
Function Documentation
void DetectEngineTagRegisterTests (void)
this function registers unit tests for DetectTag
Definition at line 1507 of file detect-engine-tag.c.
Referenced by DetectTagRegisterTests().
SC_ATOMIC_DECLARE (unsigned int, num_tags)
Atomic counter, to know if we have tagged hosts/sessions, to avoid locking
void TagDestroyCtx (void)
Destroy tag context hash tables.
Parameters
tag_ctx Tag Context
Definition at line 73 of file detect-engine-tag.c.
References BUG_ON, SC_ATOMIC_DESTROY, and SC_ATOMIC_GET.
Referenced by main(), and TagRestartCtx().
int TagFlowAdd (Packet * p, DetectTagDataEntry * tde)
This function is used to add a tag to a session (type session) or update it if it's already installed. The number of times to allow an update is limited by DETECT_TAG_MATCH_LIMIT. This way repetitive matches to the same rule are limited of setting tags, to avoid DOS attacks.
Parameters
p pointer to the current packet
tde pointer to the new DetectTagDataEntry
Return values
0 if the tde was added succesfuly
1 if an entry of this sid/gid already exist and was updated
Definition at line 126 of file detect-engine-tag.c.
References DetectTagDataEntry_::bytes, DetectTagDataEntry_::cnt_match, DETECT_TAG_MATCH_LIMIT, DETECT_TAG_MAX_TAGS, DetectTagDataEntry_::first_ts, Packet_::flow, FlowGetStorageById(), FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, FlowSetStorageById(), DetectTagDataEntry_::gid, DetectTagDataEntry_::last_ts, DetectTagDataEntry_::next, DetectTagDataEntry_::packets, SC_ATOMIC_ADD, SCLogDebug, and DetectTagDataEntry_::sid.
Referenced by DetectTagMatch().
void TagHandlePacket (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Packet * p)
Search tags for src and dst. Update entries of the tag, remove if necessary.
Parameters
de_ctx Detect context
det_ctx Detect thread context
p packet
Definition at line 507 of file detect-engine-tag.c.
References Packet_::dst, Packet_::flow, FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, HostLookupHostFromHash(), HostRelease(), SC_ATOMIC_GET, SCEnter, SCReturn, Packet_::src, TagHandlePacketHost(), and TagHostHasTag().
Referenced by PacketAlertFinalize().
void TagHandlePacketHost (Host * host, Packet * p)
Definition at line 380 of file detect-engine-tag.c.
References DetectTagDataEntry_::bytes, DetectTagDataEntry_::count, DETECT_TAG_METRIC_BYTES, DETECT_TAG_METRIC_PACKET, DETECT_TAG_METRIC_SECONDS, DetectTagDataEntry_::first_ts, DetectTagDataEntry_::flags, Packet_::flags, GET_PKT_LEN, HostGetStorageById(), HostSetStorageById(), DetectTagDataEntry_::last_ts, DetectTagDataEntry_::metric, DetectTagDataEntry_::next, DetectTagDataEntry_::packets, PKT_HAS_TAG, SC_ATOMIC_SUB, SCFree, SCLogDebug, TAG_ENTRY_FLAG_SKIPPED_FIRST, and Packet_::ts.
Referenced by TagHandlePacket().
int TagHashAddTag (DetectTagDataEntry * tde, Packet * p)
Add a tag entry for a host. If it already exist, update it.
Parameters
tag_ctx Tag context for hosts
tde Tag data
p packet
Return values
0 if it was added, 1 if it was updated
Definition at line 185 of file detect-engine-tag.c.
References DetectTagDataEntry_::bytes, DetectTagDataEntry_::cnt_match, DETECT_TAG_MATCH_LIMIT, DETECT_TAG_MAX_TAGS, Packet_::dst, DetectTagDataEntry_::first_ts, DetectTagDataEntry_::flags, DetectTagDataEntry_::gid, HostGetHostFromHash(), HostGetStorageById(), HostRelease(), HostSetStorageById(), DetectTagDataEntry_::last_ts, DetectTagDataEntry_::next, DetectTagDataEntry_::packets, SC_ATOMIC_ADD, SCEnter, SCLogDebug, SCReturnInt, DetectTagDataEntry_::sid, Packet_::src, tag, TAG_ENTRY_FLAG_DIR_DST, and TAG_ENTRY_FLAG_DIR_SRC.
Referenced by DetectTagMatch().
int TagHostHasTag (Host * host)
Definition at line 89 of file detect-engine-tag.c.
References HostGetStorageById().
Referenced by TagHandlePacket().
void TagInitCtx (void)
Definition at line 51 of file detect-engine-tag.c.
References DetectTagDataListFree(), FlowStorageRegister(), HostStorageRegister(), SC_ATOMIC_INIT, SC_ERR_FLOW_INIT, SC_ERR_HOST_INIT, and SCLogError.
Referenced by RunUnittests(), and TagRestartCtx().
void TagRestartCtx (void)
Reset the tagging engine context.
Definition at line 83 of file detect-engine-tag.c.
References TagDestroyCtx(), and TagInitCtx().
int TagTimeoutCheck (Host * host, struct timeval * tv)
Removes the entries exceding the max timeout value.
Parameters
tag_ctx Tag context
ts the current time
Return values
1 no tags or tags removed – host is free to go (from tag perspective)
0 still active tags
Definition at line 550 of file detect-engine-tag.c.
References HostGetStorageById(), HostSetStorageById(), DetectTagDataEntry_::last_ts, DetectTagDataEntry_::next, SC_ATOMIC_SUB, SCFree, and TAG_MAX_LAST_TIME_SEEN.