suricata: src/detect-ssl-version.c File Reference
detect-ssl-version.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "detect-ssl-version.h"
#include "stream-tcp.h"
#include "app-layer-ssl.h"
Macros
#define PARSE_REGEX
Regex for parsing "id" option, matching number or "number".
#define MAX_SUBSTRINGS 30
Functions
int DetectSslVersionMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Flow *f, uint8_t flags, void *state, Signature *s, SigMatch *m)
match the specified version on a ssl session
void DetectSslVersionRegisterTests (void)
this function registers unit tests for DetectSslVersion
void DetectSslVersionFree (void *ptr)
this function will free memory associated with DetectSslVersionData
void DetectSslVersionRegister (void)
Registration function for keyword: ssl_version.
DetectSslVersionData * DetectSslVersionParse (char *str)
This function is used to parse ssl_version data passed via keyword: "ssl_version".
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Implements the ssl_version keyword
Definition in file detect-ssl-version.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectSslVersionParse().
#define PARSE_REGEX
Value:
"^\\s*(!?[A-z0-9.]+)\\s*,?\\s*(!?[A-z0-9.]+)?\\s*\\,?\\s*" \
        "(!?[A-z0-9.]+)?\\s*,?\\s*(!?[A-z0-9.]+)?\\s*,?\\s*(!?[A-z0-9.]+)?\\s*$"
Regex for parsing "id" option, matching number or "number".
Definition at line 57 of file detect-ssl-version.c.
Referenced by DetectSslVersionRegister().
Function Documentation
void DetectSslVersionFree (void * ptr)
this function will free memory associated with DetectSslVersionData
Parameters
id_d pointer to DetectSslVersionData
Definition at line 339 of file detect-ssl-version.c.
References SCFree.
Referenced by DetectSslVersionParse(), and DetectSslVersionRegister().
int DetectSslVersionMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Flow * f, uint8_t flags, void * state, Signature * s, SigMatch * m)
match the specified version on a ssl session
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectSslVersionData
Return values
0 no match
1 match
Definition at line 118 of file detect-ssl-version.c.
References SigMatch_::ctx, DetectSslVersionData_::data, DETECT_SSL_VERSION_NEGATED, SSLVersionData_::flags, SCEnter, SCLogDebug, SCReturnInt, SSL_VERSION_2, SSL_VERSION_3, SSLv2, SSLv3, STREAM_TOCLIENT, STREAM_TOSERVER, TLS10, TLS11, TLS12, TLS_UNKNOWN, TLS_VERSION_10, TLS_VERSION_11, TLS_VERSION_12, and SSLVersionData_::ver.
Referenced by DetectSslVersionRegister().
DetectSslVersionData* DetectSslVersionParse (char * str)
This function is used to parse ssl_version data passed via keyword: "ssl_version".
Parameters
str Pointer to the user provided options
Return values
ssl pointer to DetectSslVersionData on success
NULL on failure
Definition at line 187 of file detect-ssl-version.c.
References DetectSslVersionData_::data, DETECT_SSL_VERSION_NEGATED, DetectSslVersionFree(), SSLVersionData_::flags, MAX_SUBSTRINGS, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCCalloc, SCFree, SCLogError, SCStrdup, SSL_VERSION_2, SSL_VERSION_3, SSLv2, SSLv3, TLS10, TLS11, TLS12, TLS_VERSION_10, TLS_VERSION_11, TLS_VERSION_12, unlikely, and SSLVersionData_::ver.
void DetectSslVersionRegister (void)
Registration function for keyword: ssl_version.
Definition at line 72 of file detect-ssl-version.c.
References SigTableElmt_::alproto, ALPROTO_TLS, SigTableElmt_::AppLayerMatch, DETECT_AL_SSL_VERSION, DetectSslVersionFree(), DetectSslVersionMatch(), DetectSslVersionRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void DetectSslVersionRegisterTests (void)
this function registers unit tests for DetectSslVersion
Definition at line 792 of file detect-ssl-version.c.
Referenced by DetectSslVersionRegister().