suricata: src/detect-flowint.h File Reference
detect-flowint.h File Reference
Data Structures
struct TargetVar_
struct DetectFlowintData_
Typedefs
typedef struct TargetVar_ TargetVar
typedef struct DetectFlowintData_ DetectFlowintData
Enumerations
enum {
FLOWINT_MODIFIER_SET, FLOWINT_MODIFIER_ADD, FLOWINT_MODIFIER_SUB, FLOWINT_MODIFIER_LT,
FLOWINT_MODIFIER_LE, FLOWINT_MODIFIER_EQ, FLOWINT_MODIFIER_NE, FLOWINT_MODIFIER_GE,
FLOWINT_MODIFIER_GT, FLOWINT_MODIFIER_ISSET, FLOWINT_MODIFIER_NOTSET, FLOWINT_MODIFIER_UNKNOWN
}
enum { FLOWINT_TARGET_VAL, FLOWINT_TARGET_VAR, FLOWINT_TARGET_SELF, FLOWINT_TARGET_UNKNOWN }
Functions
void DetectFlowintRegister (void)
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file detect-flowint.h.
Typedef Documentation
typedef struct DetectFlowintData_ DetectFlowintData
Context data for flowint vars
typedef struct TargetVar_ TargetVar
If the target is another var, get the name and the idx
Enumeration Type Documentation
anonymous enum
Flowint operations allowed
Enumerator
FLOWINT_MODIFIER_SET
Changing integer values
FLOWINT_MODIFIER_ADD
FLOWINT_MODIFIER_SUB
FLOWINT_MODIFIER_LT
Comparing integer values
FLOWINT_MODIFIER_LE
FLOWINT_MODIFIER_EQ
FLOWINT_MODIFIER_NE
FLOWINT_MODIFIER_GE
FLOWINT_MODIFIER_GT
FLOWINT_MODIFIER_ISSET
Checking if a var is set (keyword isset/notset)
FLOWINT_MODIFIER_NOTSET
FLOWINT_MODIFIER_UNKNOWN
Definition at line 28 of file detect-flowint.h.
anonymous enum
The target can be a value, or another variable arleady declared
Enumerator
FLOWINT_TARGET_VAL
FLOWINT_TARGET_VAR
FLOWINT_TARGET_SELF
FLOWINT_TARGET_UNKNOWN
Definition at line 49 of file detect-flowint.h.
Function Documentation
void DetectFlowintRegister (void)
Definition at line 60 of file detect-flowint.c.
References SigTableElmt_::desc, DETECT_FLOWINT, DetectFlowintFree(), DetectFlowintMatch(), DetectFlowintRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SCLogInfo, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().