suricata: src/detect-http-stat-msg.c File Reference
detect-http-stat-msg.c File Reference
HTTP layer support
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-content.h"
#include "detect-pcre.h"
#include "detect-engine-mpm.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-error.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-spm.h"
#include "util-print.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "detect-http-stat-msg.h"
#include "stream-tcp-private.h"
#include "stream-tcp.h"
Functions
int DetectHttpStatMsgMatch (ThreadVars *, DetectEngineThreadCtx *, Flow *, uint8_t, void *, Signature *, SigMatch *)
void DetectHttpStatMsgRegisterTests (void)
Register the UNITTESTS for the http_stat_msg keyword.
void DetectHttpStatMsgFree (void *)
void DetectHttpStatMsgRegister (void)
Registration function for keyword: http_stat_msg.
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements the http_stat_msg keyword
Definition in file detect-http-stat-msg.c.
Function Documentation
void DetectHttpStatMsgFree (void *)
int DetectHttpStatMsgMatch (ThreadVars * , DetectEngineThreadCtx * , Flow * , uint8_t , void * , Signature * , SigMatch *)
void DetectHttpStatMsgRegister (void)
Registration function for keyword: http_stat_msg.
Definition at line 75 of file detect-http-stat-msg.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, SigTableElmt_::desc, DETECT_AL_HTTP_STAT_MSG, DetectHttpStatMsgRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectHttpStatMsgRegisterTests (void)
Register the UNITTESTS for the http_stat_msg keyword.
Definition at line 550 of file detect-http-stat-msg.c.
Referenced by DetectHttpStatMsgRegister().