suricata: src/detect-engine-filedata-smtp.c File Reference
detect-engine-filedata-smtp.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-parse.h"
#include "detect-engine-state.h"
#include "detect-engine-content-inspection.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-print.h"
#include "flow.h"
#include "stream-tcp.h"
#include "app-layer-parser.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "app-layer-smtp.h"
#include "app-layer-protos.h"
#include "conf.h"
#include "conf-yaml-loader.h"
Macros
#define BUFFER_STEP 50
Functions
int DetectEngineInspectSMTPFiledata (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *tx, uint64_t tx_id)
void DetectEngineCleanSMTPBuffers (DetectEngineThreadCtx *det_ctx)
int DetectEngineRunSMTPMpm (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Flow *f, SMTPState *smtp_state, uint8_t flags, void *tx, uint64_t idx)
void DetectEngineSMTPFiledataRegisterTests (void)
Detailed Description
Author
Giuseppe Longo giuse.nosp@m.ppel.nosp@m.ng@gm.nosp@m.ail..nosp@m.com
Definition in file detect-engine-filedata-smtp.c.
Macro Definition Documentation
#define BUFFER_STEP 50
Definition at line 55 of file detect-engine-filedata-smtp.c.
Function Documentation
void DetectEngineCleanSMTPBuffers (DetectEngineThreadCtx * det_ctx)
Definition at line 247 of file detect-engine-filedata-smtp.c.
References FiledataReassembledBody_::buffer_len, FiledataReassembledBody_::offset, DetectEngineThreadCtx_::smtp, DetectEngineThreadCtx_::smtp_buffers_list_len, and DetectEngineThreadCtx_::smtp_start_tx_id.
int DetectEngineInspectSMTPFiledata (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * tx, uint64_t tx_id)
Definition at line 199 of file detect-engine-filedata-smtp.c.
References DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_FD_SMTP, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DETECT_SM_LIST_FILEDATA, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, SMTPState_::files_ts, FileContainer_::head, DetectEngineThreadCtx_::inspection_recursion_counter, File_::next, and Signature_::sm_lists.
Referenced by DetectEngineRegisterAppInspectionEngines().
int DetectEngineRunSMTPMpm (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Flow * f, SMTPState * smtp_state, uint8_t flags, void * tx, uint64_t idx)
Definition at line 261 of file detect-engine-filedata-smtp.c.
References SMTPState_::files_ts, FileContainer_::head, File_::next, and SMTPFiledataPatternSearch().
void DetectEngineSMTPFiledataRegisterTests (void)
Definition at line 550 of file detect-engine-filedata-smtp.c.
Referenced by RunUnittests().