suricata: src/detect.h File Reference
detect.h File Reference
#include <stdint.h>
#include "flow.h"
#include "detect-engine-proto.h"
#include "detect-reference.h"
#include "packet-queue.h"
#include "util-mpm.h"
#include "util-hash.h"
#include "util-hashlist.h"
#include "util-debug.h"
#include "util-error.h"
#include "util-radix-tree.h"
#include "util-file.h"
#include "reputation.h"
#include "detect-mark.h"
#include "detect-threshold.h"
Data Structures
struct DetectAddress_
address structure for use in the detection engine.
struct DetectAddressHead_
struct DetectMatchAddressIPv4_
struct DetectMatchAddressIPv6_
struct DetectPort_
Port structure for detection engine.
struct IPOnlyCIDRItem_
struct SigMatchCtx_
Used to start a pointer to SigMatch context Should never be dereferenced without casting to something else.
struct SigMatch_
a single match condition for a signature
struct SigMatchData_
Data needed for Match()
struct Signature_
Signature container.
struct DetectReplaceList_
struct DetectFlowvarList_
struct DetectEngineIPOnlyThreadCtx_
struct DetectEngineIPOnlyCtx_
IP only rules matching ctx.
struct DetectEngineLookupFlow_
struct MpmPatternIdStore_
struct ThresholdCtx_
threshold ctx
struct DetectEngineThreadKeywordCtxItem_
struct DetectEngineCtx_
main detection engine ctx
struct HttpReassembledBody_
struct FiledataReassembledBody_
struct DetectEngineThreadCtx_
struct SigTableElmt_
element in sigmatch type table.
struct SigGroupHeadInitData_
struct SignatureNonMpmStore_
struct SigGroupHead_
Container for matching data for a signature group.
struct DetectEngineTenantMapping_
struct DetectEngineMasterCtx_
struct SigFileLoaderStat_
Signature loader statistics.
Macros
#define DETECT_MAX_RULE_SIZE 8192
#define ADDRESS_FLAG_ANY 0x01
#define ADDRESS_FLAG_NOT 0x02
#define ADDRESS_SIGGROUPHEAD_COPY 0x04
#define ADDRESS_PORTS_COPY 0x08
#define ADDRESS_PORTS_NOTUNIQ 0x10
#define ADDRESS_HAVEPORT 0x20
#define PORT_FLAG_ANY 0x01
#define PORT_FLAG_NOT 0x02
#define PORT_SIGGROUPHEAD_COPY 0x04
#define PORT_GROUP_PORTS_COPY 0x08
#define SIG_FLAG_SRC_ANY (1)
#define SIG_FLAG_DST_ANY (1<<1)
#define SIG_FLAG_SP_ANY (1<<2)
#define SIG_FLAG_DP_ANY (1<<3)
#define SIG_FLAG_NOALERT (1<<4)
#define SIG_FLAG_DSIZE (1<<5)
#define SIG_FLAG_APPLAYER (1<<6)
#define SIG_FLAG_IPONLY (1<<7)
#define SIG_FLAG_STATE_MATCH (1<<8)
#define SIG_FLAG_REQUIRE_PACKET (1<<9)
#define SIG_FLAG_REQUIRE_STREAM (1<<10)
#define SIG_FLAG_MPM_PACKET (1<<11)
#define SIG_FLAG_MPM_PACKET_NEG (1<<12)
#define SIG_FLAG_MPM_STREAM (1<<13)
#define SIG_FLAG_MPM_STREAM_NEG (1<<14)
#define SIG_FLAG_MPM_APPLAYER (1<<15)
#define SIG_FLAG_MPM_APPLAYER_NEG (1<<16)
#define SIG_FLAG_REQUIRE_FLOWVAR (1<<17)
#define SIG_FLAG_FILESTORE (1<<18)
#define SIG_FLAG_TOSERVER (1<<19)
#define SIG_FLAG_TOCLIENT (1<<20)
#define SIG_FLAG_TLSSTORE (1<<21)
#define SIG_FLAG_INIT_DEONLY 1
#define SIG_FLAG_INIT_PACKET (1<<1)
#define SIG_FLAG_INIT_FLOW (1<<2)
#define SIG_FLAG_INIT_BIDIREC (1<<3)
#define SIG_FLAG_INIT_PAYLOAD (1<<4)
#define SIG_FLAG_INIT_FIRST_IPPROTO_SEEN (1 << 5) /** < signature has seen the first ip_proto keyword */
#define SIG_MASK_REQUIRE_PAYLOAD (1<<0)
#define SIG_MASK_REQUIRE_FLOW (1<<1)
#define SIG_MASK_REQUIRE_FLAGS_INITDEINIT (1<<2) /* SYN, FIN, RST */
#define SIG_MASK_REQUIRE_FLAGS_UNUSUAL (1<<3) /* URG, ECN, CWR */
#define SIG_MASK_REQUIRE_NO_PAYLOAD (1<<4)
#define SIG_MASK_REQUIRE_HTTP_STATE (1<<5)
#define SIG_MASK_REQUIRE_DCE_STATE (1<<6)
#define SIG_MASK_REQUIRE_ENGINE_EVENT (1<<7)
#define SIG_MASK_REQUIRE_SSH_STATE (1<<8)
#define SIG_MASK_REQUIRE_TLS_STATE (1<<9)
#define SIG_MASK_REQUIRE_DNS_STATE (1<<10)
#define SIG_MASK_REQUIRE_FTP_STATE (1<<11)
#define SIG_MASK_REQUIRE_SMTP_STATE (1<<12)
#define SIG_MASK_REQUIRE_TEMPLATE_STATE (1<<13)
#define SignatureMask uint16_t
#define DETECT_ENGINE_THREAD_CTX_INSPECTING_PACKET 0x0001
#define DETECT_ENGINE_THREAD_CTX_INSPECTING_STREAM 0x0002
#define DETECT_ENGINE_THREAD_CTX_STREAM_CONTENT_MATCH 0x0004
#define FILE_SIG_NEED_FILE 0x01
#define FILE_SIG_NEED_FILENAME 0x02
#define FILE_SIG_NEED_TYPE 0x04
#define FILE_SIG_NEED_MAGIC 0x08
#define FILE_SIG_NEED_FILECONTENT 0x10
#define FILE_SIG_NEED_MD5 0x20
#define FILE_SIG_NEED_SIZE 0x40
#define DE_QUIET 0x01
#define DETECT_FLOWVAR_TYPE_POSTMATCH 1
#define DETECT_FLOWVAR_TYPE_ALWAYS 2
#define FLOW_STATES 2
#define DETECT_FILESTORE_MAX 15
#define DETECT_SMSG_PMQ_NUM 256
#define SIG_GROUP_HEAD_MPM_URI (1)
#define SIG_GROUP_HEAD_MPM_HCBD (1 << 1)
#define SIG_GROUP_HEAD_MPM_HHD (1 << 2)
#define SIG_GROUP_HEAD_MPM_HRHD (1 << 3)
#define SIG_GROUP_HEAD_MPM_HMD (1 << 4)
#define SIG_GROUP_HEAD_MPM_HCD (1 << 5)
#define SIG_GROUP_HEAD_MPM_HRUD (1 << 6)
#define SIG_GROUP_HEAD_MPM_HSBD (1 << 7)
#define SIG_GROUP_HEAD_MPM_HSMD (1 << 8)
#define SIG_GROUP_HEAD_MPM_HSCD (1 << 9)
#define SIG_GROUP_HEAD_MPM_HUAD (1 << 10)
#define SIG_GROUP_HEAD_MPM_HHHD (1 << 11)
#define SIG_GROUP_HEAD_MPM_HRHHD (1 << 12)
#define SIG_GROUP_HEAD_MPM_COPY (1 << 13)
#define SIG_GROUP_HEAD_MPM_URI_COPY (1 << 14)
#define SIG_GROUP_HEAD_MPM_STREAM_COPY (1 << 15)
#define SIG_GROUP_HEAD_FREE (1 << 16)
#define SIG_GROUP_HEAD_MPM_PACKET (1 << 17)
#define SIG_GROUP_HEAD_MPM_STREAM (1 << 18)
#define SIG_GROUP_HEAD_REFERENCED (1 << 19)
#define SIG_GROUP_HEAD_HAVEFILEMAGIC (1 << 20)
#define SIG_GROUP_HEAD_HAVEFILEMD5 (1 << 21)
#define SIG_GROUP_HEAD_HAVEFILESIZE (1 << 22)
#define SIG_GROUP_HEAD_MPM_DNSQUERY (1 << 23)
#define SIG_GROUP_HEAD_MPM_FD_SMTP (1 << 24)
#define SIGMATCH_NOOPT (1 << 0)
#define SIGMATCH_IPONLY_COMPAT (1 << 1)
#define SIGMATCH_DEONLY_COMPAT (1 << 2)
#define SIGMATCH_PAYLOAD (1 << 3)
#define SIGMATCH_NOT_BUILT (1 << 4)
#define SIGMATCH_OPTIONAL_OPT (1 << 5)
Typedefs
typedef struct DetectAddress_ DetectAddress
address structure for use in the detection engine.
typedef struct DetectAddressHead_ DetectAddressHead
typedef struct
DetectMatchAddressIPv4_ DetectMatchAddressIPv4
typedef struct
DetectMatchAddressIPv6_ DetectMatchAddressIPv6
typedef struct DetectPort_ DetectPort
Port structure for detection engine.
typedef struct IPOnlyCIDRItem_ IPOnlyCIDRItem
typedef struct SigMatchCtx_ SigMatchCtx
Used to start a pointer to SigMatch context Should never be dereferenced without casting to something else.
typedef struct SigMatch_ SigMatch
a single match condition for a signature
typedef struct SigMatchData_ SigMatchData
Data needed for Match()
typedef struct Signature_ Signature
Signature container.
typedef struct DetectReplaceList_ DetectReplaceList
typedef struct DetectFlowvarList_ DetectFlowvarList
typedef struct
DetectEngineIPOnlyThreadCtx_ DetectEngineIPOnlyThreadCtx
typedef struct
DetectEngineIPOnlyCtx_ DetectEngineIPOnlyCtx
IP only rules matching ctx.
typedef struct
DetectEngineLookupFlow_ DetectEngineLookupFlow
typedef struct MpmPatternIdStore_ MpmPatternIdStore
typedef struct ThresholdCtx_ ThresholdCtx
threshold ctx
typedef struct
DetectEngineThreadKeywordCtxItem_ DetectEngineThreadKeywordCtxItem
typedef struct DetectEngineCtx_ DetectEngineCtx
main detection engine ctx
typedef struct HttpReassembledBody_ HttpReassembledBody
typedef struct
FiledataReassembledBody_ FiledataReassembledBody
typedef struct
DetectEngineThreadCtx_ DetectEngineThreadCtx
typedef struct SigTableElmt_ SigTableElmt
element in sigmatch type table.
typedef struct
SigGroupHeadInitData_ SigGroupHeadInitData
typedef struct
SignatureNonMpmStore_ SignatureNonMpmStore
typedef struct SigGroupHead_ SigGroupHead
Container for matching data for a signature group.
typedef struct
DetectEngineTenantMapping_ DetectEngineTenantMapping
typedef struct
DetectEngineMasterCtx_ DetectEngineMasterCtx
typedef struct SigFileLoaderStat_ SigFileLoaderStat
Signature loader statistics.
Enumerations
enum DetectSigmatchListEnum {
DETECT_SM_LIST_MATCH = 0, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DETECT_SM_LIST_HRUDMATCH,
DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HRHDMATCH,
DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HRHHDMATCH,
DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_HRLMATCH,
DETECT_SM_LIST_APP_EVENT, DETECT_SM_LIST_AMATCH, DETECT_SM_LIST_DMATCH, DETECT_SM_LIST_TMATCH,
DETECT_SM_LIST_FILEMATCH, DETECT_SM_LIST_DNSREQUEST_MATCH, DETECT_SM_LIST_DNSRESPONSE_MATCH, DETECT_SM_LIST_DNSQUERYNAME_MATCH,
DETECT_SM_LIST_MODBUS_MATCH, DETECT_SM_LIST_TEMPLATE_BUFFER_MATCH, DETECT_SM_LIST_POSTMATCH, DETECT_SM_LIST_SUPPRESS,
DETECT_SM_LIST_THRESHOLD, DETECT_SM_LIST_MAX, DETECT_SM_LIST_NOTSET
}
enum {
ADDRESS_ER = -1, ADDRESS_LT, ADDRESS_LE, ADDRESS_EQ,
ADDRESS_ES, ADDRESS_EB, ADDRESS_GE, ADDRESS_GT
}
enum {
PORT_ER = -1, PORT_LT, PORT_LE, PORT_EQ,
PORT_ES, PORT_EB, PORT_GE, PORT_GT
}
enum {
ENGINE_PROFILE_UNKNOWN, ENGINE_PROFILE_LOW, ENGINE_PROFILE_MEDIUM, ENGINE_PROFILE_HIGH,
ENGINE_PROFILE_CUSTOM, ENGINE_PROFILE_MAX
}
enum { ENGINE_SGH_MPM_FACTORY_CONTEXT_FULL, ENGINE_SGH_MPM_FACTORY_CONTEXT_SINGLE, ENGINE_SGH_MPM_FACTORY_CONTEXT_AUTO }
enum DetectEngineTenantSelectors { TENANT_SELECTOR_UNKNOWN = 0, TENANT_SELECTOR_DIRECT, TENANT_SELECTOR_VLAN }
enum {
DETECT_SID, DETECT_PRIORITY, DETECT_REV, DETECT_CLASSTYPE,
DETECT_THRESHOLD, DETECT_METADATA, DETECT_REFERENCE, DETECT_TAG,
DETECT_MSG, DETECT_CONTENT, DETECT_URICONTENT, DETECT_PCRE,
DETECT_ACK, DETECT_SEQ, DETECT_DEPTH, DETECT_DISTANCE,
DETECT_WITHIN, DETECT_OFFSET, DETECT_REPLACE, DETECT_NOCASE,
DETECT_FAST_PATTERN, DETECT_RAWBYTES, DETECT_BYTETEST, DETECT_BYTEJUMP,
DETECT_SAMEIP, DETECT_GEOIP, DETECT_IPPROTO, DETECT_FLOW,
DETECT_WINDOW, DETECT_FTPBOUNCE, DETECT_ISDATAAT, DETECT_ID,
DETECT_RPC, DETECT_DSIZE, DETECT_FLOWVAR, DETECT_FLOWVAR_POSTMATCH,
DETECT_FLOWINT, DETECT_PKTVAR, DETECT_NOALERT, DETECT_FLOWBITS,
DETECT_HOSTBITS, DETECT_IPV4_CSUM, DETECT_TCPV4_CSUM, DETECT_TCPV6_CSUM,
DETECT_UDPV4_CSUM, DETECT_UDPV6_CSUM, DETECT_ICMPV4_CSUM, DETECT_ICMPV6_CSUM,
DETECT_STREAM_SIZE, DETECT_TTL, DETECT_ITYPE, DETECT_ICODE,
DETECT_TOS, DETECT_ICMP_ID, DETECT_ICMP_SEQ, DETECT_DETECTION_FILTER,
DETECT_DECODE_EVENT, DETECT_IPOPTS, DETECT_FLAGS, DETECT_FRAGBITS,
DETECT_FRAGOFFSET, DETECT_GID, DETECT_MARK, DETECT_AL_TLS_VERSION,
DETECT_AL_TLS_SUBJECT, DETECT_AL_TLS_ISSUERDN, DETECT_AL_TLS_FINGERPRINT, DETECT_AL_TLS_STORE,
DETECT_AL_HTTP_COOKIE, DETECT_AL_HTTP_METHOD, DETECT_AL_URILEN, DETECT_AL_HTTP_CLIENT_BODY,
DETECT_AL_HTTP_SERVER_BODY, DETECT_AL_HTTP_HEADER, DETECT_AL_HTTP_RAW_HEADER, DETECT_AL_HTTP_URI,
DETECT_AL_HTTP_RAW_URI, DETECT_AL_HTTP_STAT_MSG, DETECT_AL_HTTP_STAT_CODE, DETECT_AL_HTTP_USER_AGENT,
DETECT_AL_HTTP_HOST, DETECT_AL_HTTP_RAW_HOST, DETECT_AL_SSH_PROTOVERSION, DETECT_AL_SSH_SOFTWAREVERSION,
DETECT_AL_SSL_VERSION, DETECT_AL_SSL_STATE, DETECT_BYTE_EXTRACT, DETECT_FILE_DATA,
DETECT_PKT_DATA, DETECT_AL_APP_LAYER_EVENT, DETECT_AL_APP_LAYER_PROTOCOL, DETECT_DCE_IFACE,
DETECT_DCE_OPNUM, DETECT_DCE_STUB_DATA, DETECT_ASN1, DETECT_ENGINE_EVENT,
DETECT_STREAM_EVENT, DETECT_FILENAME, DETECT_FILEEXT, DETECT_FILESTORE,
DETECT_FILEMAGIC, DETECT_FILEMD5, DETECT_FILESIZE, DETECT_L3PROTO,
DETECT_LUA, DETECT_IPREP, DETECT_AL_DNS_QUERY, DETECT_AL_MODBUS,
DETECT_XBITS, DETECT_TEMPLATE, DETECT_AL_TEMPLATE_BUFFER, DETECT_TBLSIZE
}
Functions
SigMatch * SigMatchAlloc (void)
Signature * SigFindSignatureBySidGid (DetectEngineCtx *, uint32_t, uint32_t)
Find a specific signature by sid and gid.
void SigMatchSignaturesBuildMatchArray (DetectEngineThreadCtx *, Packet *, SignatureMask, uint16_t)
void SigMatchFree (SigMatch *sm)
free a SigMatch
void SigCleanSignatures (DetectEngineCtx *)
void SigTableRegisterTests (void)
void SigRegisterTests (void)
void DetectSimdRegisterTests (void)
void TmModuleDetectRegister (void)
int SigGroupBuild (DetectEngineCtx *)
Convert the signature list into the runtime match structure.
int SigGroupCleanup (DetectEngineCtx *de_ctx)
void SigAddressPrepareBidirectionals (DetectEngineCtx *)
char * DetectLoadCompleteSigPath (const DetectEngineCtx *, char *sig_file)
Create the path if default-rule-path was specified.
int SigLoadSignatures (DetectEngineCtx *, char *, int)
Load signatures.
void SigTableList (const char *keyword)
void SigTableSetup (void)
int SigMatchSignatures (ThreadVars *th_v, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Packet *p)
Signature match function.
int SignatureIsIPOnly (DetectEngineCtx *de_ctx, Signature *s)
Test is a initialized signature is IP only.
SigGroupHead * SigMatchSignaturesGetSgh (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Packet *p)
Get the SigGroupHead for a packet.
Signature * DetectGetTagSignature (void)
int SignatureIsFilestoring (Signature *)
Check if a signature contains the filestore keyword.
int SignatureIsFilemagicInspecting (Signature *)
Check if a signature contains the filemagic keyword.
int SignatureIsFileMd5Inspecting (Signature *)
Check if a signature contains the filemd5 keyword.
int SignatureIsFilesizeInspecting (Signature *)
Check if a signature contains the filesize keyword.
int DetectRegisterThreadCtxFuncs (DetectEngineCtx *, const char *name, void *(*InitFunc)(void *), void *data, void(*FreeFunc)(void *), int)
Register Thread keyword context Funcs.
void * DetectThreadCtxGetKeywordThreadCtx (DetectEngineThreadCtx *, int)
Retrieve thread local keyword ctx by id.
int SigMatchSignaturesRunPostMatch (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s)
void DetectSignatureApplyActions (Packet *p, const Signature *s)
Apply action(s) and Set 'drop' sig info, if applicable.
Variables
SigTableElmt sigmatch_table [DETECT_TBLSIZE]
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect.h.
Macro Definition Documentation
#define ADDRESS_FLAG_ANY 0x01
address is "any"
Definition at line 157 of file detect.h.
Referenced by CreateGroupedAddrList(), DetectAddressCmp(), DetectAddressInsert(), DetectAddressParseString(), DetectAddressPrint(), and DetectAddressSetup().
#define ADDRESS_FLAG_NOT 0x02
address is negated
Definition at line 158 of file detect.h.
Referenced by DetectAddressParseString(), and DetectAddressSetup().
#define ADDRESS_HAVEPORT 0x20
address has a ports ptr
Definition at line 163 of file detect.h.
Referenced by BuildDestinationAddressHeadsWithBothPorts(), CreateGroupedAddrList(), and DetectAddressFree().
#define ADDRESS_PORTS_COPY 0x08
ports are a ptr to other ports
Definition at line 161 of file detect.h.
Referenced by BuildDestinationAddressHeadsWithBothPorts(), and DetectAddressFree().
#define ADDRESS_PORTS_NOTUNIQ 0x10
Definition at line 162 of file detect.h.
#define ADDRESS_SIGGROUPHEAD_COPY 0x04
sgh is a ptr to another sgh
Definition at line 160 of file detect.h.
Referenced by BuildDestinationAddressHeads(), BuildDestinationAddressHeadsWithBothPorts(), DetectAddressFree(), and SigAddressPrepareStage5().
#define DE_QUIET 0x01
DE is quiet (esp for unittests)
Definition at line 328 of file detect.h.
Referenced by SigAddressCleanupStage1(), SigAddressPrepareStage1(), SigAddressPrepareStage2(), SigAddressPrepareStage3(), and SignatureIsIPOnly().
#define DETECT_ENGINE_THREAD_CTX_INSPECTING_PACKET 0x0001
Definition at line 315 of file detect.h.
#define DETECT_ENGINE_THREAD_CTX_INSPECTING_STREAM 0x0002
Definition at line 316 of file detect.h.
#define DETECT_ENGINE_THREAD_CTX_STREAM_CONTENT_MATCH 0x0004
Definition at line 317 of file detect.h.
Referenced by DetectFlowMatch(), and SigMatchSignatures().
#define DETECT_FILESTORE_MAX 15
Definition at line 752 of file detect.h.
#define DETECT_FLOWVAR_TYPE_ALWAYS 2
execute flowvar storage even if rule doesn't match (for luajit)
Definition at line 473 of file detect.h.
Referenced by DetectFlowvarProcessListInternal().
#define DETECT_FLOWVAR_TYPE_POSTMATCH 1
only execute flowvar storage if rule matched
Definition at line 471 of file detect.h.
Referenced by DetectPcrePayloadMatch().
#define DETECT_MAX_RULE_SIZE 8192
Definition at line 46 of file detect.h.
#define DETECT_SMSG_PMQ_NUM 256
Todo:
review how many we actually need here
Definition at line 754 of file detect.h.
Referenced by DetectEngineThreadCtxFree().
#define FILE_SIG_NEED_FILE 0x01
Definition at line 319 of file detect.h.
#define FILE_SIG_NEED_FILECONTENT 0x10
Definition at line 323 of file detect.h.
#define FILE_SIG_NEED_FILENAME 0x02
Definition at line 320 of file detect.h.
#define FILE_SIG_NEED_MAGIC 0x08
need the start of the file
Definition at line 322 of file detect.h.
Referenced by SignatureIsFilemagicInspecting().
#define FILE_SIG_NEED_MD5 0x20
Definition at line 324 of file detect.h.
Referenced by SignatureIsFileMd5Inspecting().
#define FILE_SIG_NEED_SIZE 0x40
Definition at line 325 of file detect.h.
Referenced by SignatureIsFilesizeInspecting().
#define FILE_SIG_NEED_TYPE 0x04
Definition at line 321 of file detect.h.
#define FLOW_STATES 2
Definition at line 530 of file detect.h.
Referenced by SigAddressCleanupStage1(), SigAddressPrepareStage2(), SigAddressPrepareStage3(), and SigAddressPrepareStage5().
#define PORT_FLAG_ANY 0x01
'any' special port
Definition at line 230 of file detect.h.
Referenced by DetectPortCmp(), and DetectPortPrint().
#define PORT_FLAG_NOT 0x02
negated port
Definition at line 231 of file detect.h.
Referenced by PortParse().
#define PORT_GROUP_PORTS_COPY 0x08
dst_ph is a ptr copy
Definition at line 233 of file detect.h.
Referenced by BuildDestinationAddressHeadsWithBothPorts(), and DetectPortFree().
#define PORT_SIGGROUPHEAD_COPY 0x04
sgh is a ptr copy
Definition at line 232 of file detect.h.
Referenced by BuildDestinationAddressHeadsWithBothPorts(), and DetectPortFree().
#define SIG_FLAG_APPLAYER (1<<6)
signature applies to app layer instead of packets
Definition at line 264 of file detect.h.
Referenced by DetectAppLayerProtocolSetup(), DetectByteExtractSetup(), DetectBytejumpSetup(), DetectBytetestSetup(), DetectContentSetup(), DetectEngineContentModifierBufferSetup(), DetectIsdataatSetup(), PacketAlertFinalize(), SigAddressPrepareStage1(), SigMatchSignatures(), and SigParseProto().
#define SIG_FLAG_DP_ANY (1<<3)
destination port is any
Definition at line 260 of file detect.h.
Referenced by EngineAnalysisRules(), IPOnlyMatchPacket(), and SigMatchSignatures().
#define SIG_FLAG_DSIZE (1<<5)
signature has a dsize setting
Definition at line 263 of file detect.h.
Referenced by SigMatchSignatures().
#define SIG_FLAG_DST_ANY (1<<1)
destination is any
Definition at line 258 of file detect.h.
Referenced by IPOnlySigParseAddress(), SigMatchSignatures(), SignatureIsIPOnly(), and SigParseAddress().
#define SIG_FLAG_FILESTORE (1<<18)
signature has filestore keyword
Definition at line 281 of file detect.h.
Referenced by SigMatchSignaturesRunPostMatch(), and SignatureIsFilestoring().
#define SIG_FLAG_INIT_BIDIREC (1<<3)
signature has bidirectional operator
Definition at line 292 of file detect.h.
Referenced by DetectEngineAppendSig(), EngineAnalysisRules(), and SigInit().
#define SIG_FLAG_INIT_DEONLY 1
decode event only signature
Definition at line 289 of file detect.h.
Referenced by SigAddressPrepareStage1(), and SigAddressPrepareStage2().
#define SIG_FLAG_INIT_FIRST_IPPROTO_SEEN (1 << 5) /** < signature has seen the first ip_proto keyword */
Definition at line 294 of file detect.h.
#define SIG_FLAG_INIT_FLOW (1<<2)
signature has a flow setting
Definition at line 291 of file detect.h.
#define SIG_FLAG_INIT_PACKET (1<<1)
signature has matches against a packet (as opposed to app layer)
Definition at line 290 of file detect.h.
#define SIG_FLAG_INIT_PAYLOAD (1<<4)
signature is inspecting the packet payload
Definition at line 293 of file detect.h.
Referenced by SigAddressPrepareStage1().
#define SIG_FLAG_IPONLY (1<<7)
ip only signature
Definition at line 265 of file detect.h.
Referenced by EngineAnalysisRules(), IPOnlyAddSignature(), PacketAlertFinalize(), SigAddressPrepareStage1(), and SigAddressPrepareStage2().
#define SIG_FLAG_MPM_APPLAYER (1<<15)
Definition at line 276 of file detect.h.
Referenced by SigMatchSignatures().
#define SIG_FLAG_MPM_APPLAYER_NEG (1<<16)
Definition at line 277 of file detect.h.
Referenced by SigGroupHeadBuildNonMpmArray(), and SigMatchSignatures().
#define SIG_FLAG_MPM_PACKET (1<<11)
Definition at line 272 of file detect.h.
Referenced by SigMatchSignatures().
#define SIG_FLAG_MPM_PACKET_NEG (1<<12)
Definition at line 273 of file detect.h.
Referenced by SigGroupHeadBuildNonMpmArray(), and SigMatchSignatures().
#define SIG_FLAG_MPM_STREAM (1<<13)
Definition at line 274 of file detect.h.
Referenced by SigMatchSignatures().
#define SIG_FLAG_MPM_STREAM_NEG (1<<14)
Definition at line 275 of file detect.h.
Referenced by SigGroupHeadBuildNonMpmArray(), and SigMatchSignatures().
#define SIG_FLAG_NOALERT (1<<4)
no alert flag is set
Definition at line 262 of file detect.h.
Referenced by DeStateDetectStartDetection(), IPOnlyMatchPacket(), and SigMatchSignatures().
#define SIG_FLAG_REQUIRE_FLOWVAR (1<<17)
signature can only match if a flowbit, flowvar or flowint is available.
Definition at line 279 of file detect.h.
Referenced by SigMatchSignatures().
#define SIG_FLAG_REQUIRE_PACKET (1<<9)
signature is requiring packet match
Definition at line 269 of file detect.h.
Referenced by DetectRpcSetup(), DetectWindowSetup(), EngineAnalysisRules(), SigMatchSignatures(), SignatureHasPacketContent(), SigParseProto(), and SigValidate().
#define SIG_FLAG_REQUIRE_STREAM (1<<10)
signature is requiring stream match
Definition at line 270 of file detect.h.
Referenced by EngineAnalysisRules(), SigMatchSignatures(), SignatureHasStreamContent(), SigParseProto(), and SigValidate().
#define SIG_FLAG_SP_ANY (1<<2)
source port is any
Definition at line 259 of file detect.h.
Referenced by EngineAnalysisRules(), IPOnlyMatchPacket(), and SigMatchSignatures().
#define SIG_FLAG_SRC_ANY (1)
source is any
Definition at line 257 of file detect.h.
Referenced by IPOnlySigParseAddress(), SigMatchSignatures(), SignatureIsIPOnly(), and SigParseAddress().
#define SIG_FLAG_STATE_MATCH (1<<8)
signature has matches that require stateful inspection
Definition at line 267 of file detect.h.
Referenced by SigMatchSignatures().
#define SIG_FLAG_TLSSTORE (1<<21)
Definition at line 286 of file detect.h.
#define SIG_FLAG_TOCLIENT (1<<20)
Definition at line 284 of file detect.h.
Referenced by EngineAnalysisRules(), and SigValidate().
#define SIG_FLAG_TOSERVER (1<<19)
Definition at line 283 of file detect.h.
Referenced by EngineAnalysisRules(), and SigValidate().
#define SIG_GROUP_HEAD_FREE (1 << 16)
Definition at line 950 of file detect.h.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
#define SIG_GROUP_HEAD_HAVEFILEMAGIC (1 << 20)
Definition at line 954 of file detect.h.
Referenced by SigGroupHeadSetFilemagicFlag(), and SigMatchSignatures().
#define SIG_GROUP_HEAD_HAVEFILEMD5 (1 << 21)
Definition at line 955 of file detect.h.
Referenced by SigGroupHeadSetFileMd5Flag(), and SigMatchSignatures().
#define SIG_GROUP_HEAD_HAVEFILESIZE (1 << 22)
Definition at line 956 of file detect.h.
Referenced by SigGroupHeadSetFilesizeFlag(), and SigMatchSignatures().
#define SIG_GROUP_HEAD_MPM_COPY (1 << 13)
Definition at line 947 of file detect.h.
Referenced by PatternMatchDestroyGroup().
#define SIG_GROUP_HEAD_MPM_DNSQUERY (1 << 23)
Definition at line 957 of file detect.h.
#define SIG_GROUP_HEAD_MPM_FD_SMTP (1 << 24)
Definition at line 958 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HCBD (1 << 1)
Definition at line 934 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HCD (1 << 5)
Definition at line 938 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HHD (1 << 2)
Definition at line 935 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HHHD (1 << 11)
Definition at line 944 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HMD (1 << 4)
Definition at line 937 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HRHD (1 << 3)
Definition at line 936 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HRHHD (1 << 12)
Definition at line 945 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HRUD (1 << 6)
Definition at line 939 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HSBD (1 << 7)
Definition at line 940 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HSCD (1 << 9)
Definition at line 942 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HSMD (1 << 8)
Definition at line 941 of file detect.h.
#define SIG_GROUP_HEAD_MPM_HUAD (1 << 10)
Definition at line 943 of file detect.h.
#define SIG_GROUP_HEAD_MPM_PACKET (1 << 17)
Definition at line 951 of file detect.h.
#define SIG_GROUP_HEAD_MPM_STREAM (1 << 18)
Definition at line 952 of file detect.h.
#define SIG_GROUP_HEAD_MPM_STREAM_COPY (1 << 15)
Definition at line 949 of file detect.h.
Referenced by PatternMatchDestroyGroup().
#define SIG_GROUP_HEAD_MPM_URI (1)
Definition at line 933 of file detect.h.
#define SIG_GROUP_HEAD_MPM_URI_COPY (1 << 14)
Definition at line 948 of file detect.h.
Referenced by PatternMatchDestroyGroup().
#define SIG_GROUP_HEAD_REFERENCED (1 << 19)
sgh is being referenced by others, don't clear
Definition at line 953 of file detect.h.
Referenced by BuildDestinationAddressHeads(), and BuildDestinationAddressHeadsWithBothPorts().
#define SIG_MASK_REQUIRE_DCE_STATE (1<<6)
Definition at line 303 of file detect.h.
#define SIG_MASK_REQUIRE_DNS_STATE (1<<10)
Definition at line 307 of file detect.h.
#define SIG_MASK_REQUIRE_ENGINE_EVENT (1<<7)
Definition at line 304 of file detect.h.
#define SIG_MASK_REQUIRE_FLAGS_INITDEINIT (1<<2) /* SYN, FIN, RST */
Definition at line 299 of file detect.h.
#define SIG_MASK_REQUIRE_FLAGS_UNUSUAL (1<<3) /* URG, ECN, CWR */
Definition at line 300 of file detect.h.
#define SIG_MASK_REQUIRE_FLOW (1<<1)
Definition at line 298 of file detect.h.
#define SIG_MASK_REQUIRE_FTP_STATE (1<<11)
Definition at line 308 of file detect.h.
#define SIG_MASK_REQUIRE_HTTP_STATE (1<<5)
Definition at line 302 of file detect.h.
#define SIG_MASK_REQUIRE_NO_PAYLOAD (1<<4)
Definition at line 301 of file detect.h.
#define SIG_MASK_REQUIRE_PAYLOAD (1<<0)
Definition at line 297 of file detect.h.
#define SIG_MASK_REQUIRE_SMTP_STATE (1<<12)
Definition at line 309 of file detect.h.
#define SIG_MASK_REQUIRE_SSH_STATE (1<<8)
Definition at line 305 of file detect.h.
#define SIG_MASK_REQUIRE_TEMPLATE_STATE (1<<13)
Definition at line 310 of file detect.h.
#define SIG_MASK_REQUIRE_TLS_STATE (1<<9)
Definition at line 306 of file detect.h.
#define SIGMATCH_DEONLY_COMPAT (1 << 2)
sigmatch is compatible with a decode event only rule Flag to indicate that the signature inspects the packet payload
Definition at line 1046 of file detect.h.
Referenced by DetectEngineEventRegister().
#define SIGMATCH_IPONLY_COMPAT (1 << 1)
sigmatch is compatible with a ip only rule
Definition at line 1044 of file detect.h.
Referenced by DetectDetectionFilterRegister(), DetectFlowbitsRegister(), DetectHostbitsRegister(), DetectIPRepRegister(), DetectTagRegister(), DetectThresholdRegister(), DetectXbitsRegister(), and SignatureIsIPOnly().
#define SIGMATCH_NOOPT (1 << 0)
sigmatch has no options, so the parser shouldn't expect any
Definition at line 1042 of file detect.h.
Referenced by DetectDceStubDataRegister(), DetectDnsQueryRegister(), DetectFastPatternRegister(), DetectFiledataRegister(), DetectFtpbounceRegister(), DetectHttpClientBodyRegister(), DetectHttpCookieRegister(), DetectHttpHeaderRegister(), DetectHttpHHRegister(), DetectHttpHRHRegister(), DetectHttpMethodRegister(), DetectHttpRawHeaderRegister(), DetectHttpRawUriRegister(), DetectHttpServerBodyRegister(), DetectHttpStatCodeRegister(), DetectHttpStatMsgRegister(), DetectHttpUARegister(), DetectHttpUriRegister(), DetectNoalertRegister(), DetectNocaseRegister(), DetectPktDataRegister(), DetectRawbytesRegister(), DetectSameipRegister(), DetectTemplateBufferRegister(), and DetectTlsRegister().
#define SIGMATCH_NOT_BUILT (1 << 4)
Definition at line 1050 of file detect.h.
Referenced by DetectFileMd5Register(), DetectLuaRegister(), and SigTableList().
#define SIGMATCH_OPTIONAL_OPT (1 << 5)
sigmatch may have options, so the parser should be ready to deal with both cases
Definition at line 1053 of file detect.h.
Referenced by DetectFilestoreRegister().
#define SIGMATCH_PAYLOAD (1 << 3)
Flag to indicate that the signature is not built-in
Definition at line 1048 of file detect.h.
Referenced by DetectByteExtractRegister(), DetectBytejumpRegister(), DetectBytetestRegister(), DetectContentRegister(), DetectDceIfaceRegister(), DetectDceOpnumRegister(), DetectDceStubDataRegister(), DetectDepthRegister(), DetectDistanceRegister(), DetectDnsQueryRegister(), DetectFastPatternRegister(), DetectFilesizeRegister(), DetectHttpClientBodyRegister(), DetectHttpCookieRegister(), DetectHttpHeaderRegister(), DetectHttpHHRegister(), DetectHttpHRHRegister(), DetectHttpMethodRegister(), DetectHttpRawHeaderRegister(), DetectHttpRawUriRegister(), DetectHttpServerBodyRegister(), DetectHttpStatCodeRegister(), DetectHttpStatMsgRegister(), DetectHttpUARegister(), DetectHttpUriRegister(), DetectIsdataatRegister(), DetectNocaseRegister(), DetectOffsetRegister(), DetectPcreRegister(), DetectPktvarRegister(), DetectRawbytesRegister(), DetectReplaceRegister(), DetectTemplateBufferRegister(), DetectUricontentRegister(), DetectUrilenRegister(), and DetectWithinRegister().
#define SignatureMask uint16_t
Definition at line 313 of file detect.h.
Referenced by SigMatchSignatures().
Typedef Documentation
typedef struct DetectAddress_ DetectAddress
address structure for use in the detection engine.
Contains the address information and matching information.
typedef struct DetectAddressHead_ DetectAddressHead
Signature grouping head. Here 'any', ipv4 and ipv6 are split out
typedef struct DetectEngineCtx_ DetectEngineCtx
main detection engine ctx
typedef struct DetectEngineIPOnlyCtx_ DetectEngineIPOnlyCtx
IP only rules matching ctx.
typedef struct DetectEngineIPOnlyThreadCtx_ DetectEngineIPOnlyThreadCtx
typedef struct DetectEngineLookupFlow_ DetectEngineLookupFlow
typedef struct DetectEngineMasterCtx_ DetectEngineMasterCtx
typedef struct DetectEngineTenantMapping_ DetectEngineTenantMapping
typedef struct DetectEngineThreadCtx_ DetectEngineThreadCtx
Detection engine thread data.
typedef struct DetectEngineThreadKeywordCtxItem_ DetectEngineThreadKeywordCtxItem
typedef struct DetectFlowvarList_ DetectFlowvarList
list for flowvar store candidates, to be stored from post-match function
typedef struct DetectMatchAddressIPv4_ DetectMatchAddressIPv4
typedef struct DetectMatchAddressIPv6_ DetectMatchAddressIPv6
typedef struct DetectPort_ DetectPort
Port structure for detection engine.
typedef struct DetectReplaceList_ DetectReplaceList
typedef struct FiledataReassembledBody_ FiledataReassembledBody
typedef struct HttpReassembledBody_ HttpReassembledBody
typedef struct IPOnlyCIDRItem_ IPOnlyCIDRItem
typedef struct MpmPatternIdStore_ MpmPatternIdStore
typedef struct SigFileLoaderStat_ SigFileLoaderStat
Signature loader statistics.
typedef struct SigGroupHead_ SigGroupHead
Container for matching data for a signature group.
typedef struct SigGroupHeadInitData_ SigGroupHeadInitData
typedef struct SigMatch_ SigMatch
a single match condition for a signature
typedef struct SigMatchCtx_ SigMatchCtx
Used to start a pointer to SigMatch context Should never be dereferenced without casting to something else.
typedef struct SigMatchData_ SigMatchData
Data needed for Match()
typedef struct Signature_ Signature
Signature container.
typedef struct SignatureNonMpmStore_ SignatureNonMpmStore
typedef struct SigTableElmt_ SigTableElmt
element in sigmatch type table.
Note
FileMatch pointer below takes a locked flow, AppLayerMatch an unlocked flow
typedef struct ThresholdCtx_ ThresholdCtx
threshold ctx
Enumeration Type Documentation
anonymous enum
Enumerator
ADDRESS_ER
error e.g. compare ipv4 and ipv6
ADDRESS_LT
smaller [aaa] [bbb]
ADDRESS_LE
smaller with overlap [aa[bab]bb]
ADDRESS_EQ
exactly equal [abababab]
ADDRESS_ES
within [bb[aaa]bb] and [[abab]bbb] and [bbb[abab]]
ADDRESS_EB
completely overlaps [aa[bbb]aa] and [[baba]aaa] and [aaa[baba]]
ADDRESS_GE
bigger with overlap [bb[aba]aa]
ADDRESS_GT
bigger [bbb] [aaa]
Definition at line 146 of file detect.h.
anonymous enum
Enumerator
PORT_ER
PORT_LT
PORT_LE
PORT_EQ
PORT_ES
PORT_EB
PORT_GE
PORT_GT
Definition at line 219 of file detect.h.
anonymous enum
Enumerator
ENGINE_PROFILE_UNKNOWN
ENGINE_PROFILE_LOW
ENGINE_PROFILE_MEDIUM
ENGINE_PROFILE_HIGH
ENGINE_PROFILE_CUSTOM
ENGINE_PROFILE_MAX
Definition at line 722 of file detect.h.
anonymous enum
Enumerator
ENGINE_SGH_MPM_FACTORY_CONTEXT_FULL
ENGINE_SGH_MPM_FACTORY_CONTEXT_SINGLE
ENGINE_SGH_MPM_FACTORY_CONTEXT_AUTO
Definition at line 732 of file detect.h.
anonymous enum
Remember to add the options in SignatureIsIPOnly() at detect.c otherwise it wont be part of a signature group
Enumerator
DETECT_SID
DETECT_PRIORITY
DETECT_REV
DETECT_CLASSTYPE
DETECT_THRESHOLD
DETECT_METADATA
DETECT_REFERENCE
DETECT_TAG
DETECT_MSG
DETECT_CONTENT
DETECT_URICONTENT
DETECT_PCRE
DETECT_ACK
DETECT_SEQ
DETECT_DEPTH
DETECT_DISTANCE
DETECT_WITHIN
DETECT_OFFSET
DETECT_REPLACE
DETECT_NOCASE
DETECT_FAST_PATTERN
DETECT_RAWBYTES
DETECT_BYTETEST
DETECT_BYTEJUMP
DETECT_SAMEIP
DETECT_GEOIP
DETECT_IPPROTO
DETECT_FLOW
DETECT_WINDOW
DETECT_FTPBOUNCE
DETECT_ISDATAAT
DETECT_ID
DETECT_RPC
DETECT_DSIZE
DETECT_FLOWVAR
DETECT_FLOWVAR_POSTMATCH
DETECT_FLOWINT
DETECT_PKTVAR
DETECT_NOALERT
DETECT_FLOWBITS
DETECT_HOSTBITS
DETECT_IPV4_CSUM
DETECT_TCPV4_CSUM
DETECT_TCPV6_CSUM
DETECT_UDPV4_CSUM
DETECT_UDPV6_CSUM
DETECT_ICMPV4_CSUM
DETECT_ICMPV6_CSUM
DETECT_STREAM_SIZE
DETECT_TTL
DETECT_ITYPE
DETECT_ICODE
DETECT_TOS
DETECT_ICMP_ID
DETECT_ICMP_SEQ
DETECT_DETECTION_FILTER
DETECT_DECODE_EVENT
DETECT_IPOPTS
DETECT_FLAGS
DETECT_FRAGBITS
DETECT_FRAGOFFSET
DETECT_GID
DETECT_MARK
DETECT_AL_TLS_VERSION
DETECT_AL_TLS_SUBJECT
DETECT_AL_TLS_ISSUERDN
DETECT_AL_TLS_FINGERPRINT
DETECT_AL_TLS_STORE
DETECT_AL_HTTP_COOKIE
DETECT_AL_HTTP_METHOD
DETECT_AL_URILEN
DETECT_AL_HTTP_CLIENT_BODY
DETECT_AL_HTTP_SERVER_BODY
DETECT_AL_HTTP_HEADER
DETECT_AL_HTTP_RAW_HEADER
DETECT_AL_HTTP_URI
DETECT_AL_HTTP_RAW_URI
DETECT_AL_HTTP_STAT_MSG
DETECT_AL_HTTP_STAT_CODE
DETECT_AL_HTTP_USER_AGENT
DETECT_AL_HTTP_HOST
DETECT_AL_HTTP_RAW_HOST
DETECT_AL_SSH_PROTOVERSION
DETECT_AL_SSH_SOFTWAREVERSION
DETECT_AL_SSL_VERSION
DETECT_AL_SSL_STATE
DETECT_BYTE_EXTRACT
DETECT_FILE_DATA
DETECT_PKT_DATA
DETECT_AL_APP_LAYER_EVENT
DETECT_AL_APP_LAYER_PROTOCOL
DETECT_DCE_IFACE
DETECT_DCE_OPNUM
DETECT_DCE_STUB_DATA
DETECT_ASN1
DETECT_ENGINE_EVENT
DETECT_STREAM_EVENT
DETECT_FILENAME
DETECT_FILEEXT
DETECT_FILESTORE
DETECT_FILEMAGIC
DETECT_FILEMD5
DETECT_FILESIZE
DETECT_L3PROTO
DETECT_LUA
DETECT_IPREP
DETECT_AL_DNS_QUERY
DETECT_AL_MODBUS
DETECT_XBITS
DETECT_TEMPLATE
DETECT_AL_TEMPLATE_BUFFER
DETECT_TBLSIZE
Definition at line 1104 of file detect.h.
enum DetectEngineTenantSelectors
Enumerator
TENANT_SELECTOR_UNKNOWN
not set
TENANT_SELECTOR_DIRECT
method provides direct tenant id
TENANT_SELECTOR_VLAN
map vlan to tenant id
Definition at line 1055 of file detect.h.
enum DetectSigmatchListEnum
Enumerator
DETECT_SM_LIST_MATCH
DETECT_SM_LIST_PMATCH
DETECT_SM_LIST_UMATCH
DETECT_SM_LIST_HRUDMATCH
DETECT_SM_LIST_HCBDMATCH
DETECT_SM_LIST_FILEDATA
DETECT_SM_LIST_HHDMATCH
DETECT_SM_LIST_HRHDMATCH
DETECT_SM_LIST_HSMDMATCH
DETECT_SM_LIST_HSCDMATCH
DETECT_SM_LIST_HHHDMATCH
DETECT_SM_LIST_HRHHDMATCH
DETECT_SM_LIST_HMDMATCH
DETECT_SM_LIST_HCDMATCH
DETECT_SM_LIST_HUADMATCH
DETECT_SM_LIST_HRLMATCH
DETECT_SM_LIST_APP_EVENT
DETECT_SM_LIST_AMATCH
DETECT_SM_LIST_DMATCH
DETECT_SM_LIST_TMATCH
DETECT_SM_LIST_FILEMATCH
DETECT_SM_LIST_DNSREQUEST_MATCH
per DNS query tx match list
DETECT_SM_LIST_DNSRESPONSE_MATCH
per DNS response tx match list
DETECT_SM_LIST_DNSQUERYNAME_MATCH
per query in a tx list
DETECT_SM_LIST_MODBUS_MATCH
DETECT_SM_LIST_TEMPLATE_BUFFER_MATCH
DETECT_SM_LIST_POSTMATCH
DETECT_SM_LIST_SUPPRESS
DETECT_SM_LIST_THRESHOLD
DETECT_SM_LIST_MAX
DETECT_SM_LIST_NOTSET
Definition at line 83 of file detect.h.
Function Documentation
Signature* DetectGetTagSignature (void)
char* DetectLoadCompleteSigPath (const DetectEngineCtx * de_ctx, char * sig_file)
Create the path if default-rule-path was specified.
Parameters
sig_file The name of the file
Return values
str Pointer to the string path + sig_file
Definition at line 251 of file detect.c.
References ConfGet(), DetectEngineCtx_::config_prefix, PathIsRelative(), SCLogDebug, SCMalloc, SCStrdup, strlcat(), strlcpy(), unlikely, and ptxdump::varname.
Referenced by SigLoadSignatures().
int DetectRegisterThreadCtxFuncs (DetectEngineCtx * de_ctx, const char * name, void *(*)(void *) InitFunc, void * data, void(*)(void *) FreeFunc, int mode)
Register Thread keyword context Funcs.
Parameters
de_ctx detection engine to register in
name keyword name for error printing
InitFunc function ptr
data keyword init data to pass to Func
FreeFunc function ptr
mode 0 normal (ctx per keyword instance) 1 shared (one ctx per det_ct)
Return values
id for retrieval of ctx at runtime
-1 on error
Note
make sure "data" remains valid and it free'd elsewhere. It's recommended to store it in the keywords global ctx so that it's freed when the de_ctx is freed.
Definition at line 1598 of file detect-engine.c.
References BUG_ON, data, DetectEngineThreadKeywordCtxItem_::data, DetectEngineThreadKeywordCtxItem_::FreeFunc, DetectEngineThreadKeywordCtxItem_::id, DetectEngineThreadKeywordCtxItem_::InitFunc, DetectEngineCtx_::keyword_id, DetectEngineCtx_::keyword_list, DetectEngineThreadKeywordCtxItem_::name, DetectEngineThreadKeywordCtxItem_::next, SCMalloc, and unlikely.
void DetectSignatureApplyActions (Packet * p, const Signature * s)
Apply action(s) and Set 'drop' sig info, if applicable.
Definition at line 1923 of file detect.c.
References PacketAlert_::action, Signature_::action, ACTION_DROP, Packet_::alerts, PacketAlerts_::drop, PacketAlert_::num, Signature_::num, PACKET_UPDATE_ACTION, and PacketAlert_::s.
Referenced by DeStateDetectStartDetection(), IPOnlyMatchPacket(), PacketAlertFinalize(), and SigMatchSignatures().
void DetectSimdRegisterTests (void)
Referenced by SigRegisterTests().
void* DetectThreadCtxGetKeywordThreadCtx (DetectEngineThreadCtx * det_ctx, int id)
Retrieve thread local keyword ctx by id.
Parameters
det_ctx detection engine thread ctx to retrieve the ctx from
id id of the ctx returned by DetectRegisterThreadCtxInitFunc at keyword init.
Return values
ctx or NULL on error
Definition at line 1638 of file detect-engine.c.
References DetectEngineThreadCtx_::keyword_ctxs_array, and DetectEngineThreadCtx_::keyword_ctxs_size.
void SigAddressPrepareBidirectionals (DetectEngineCtx *)
void SigCleanSignatures (DetectEngineCtx *)
Definition at line 2046 of file detect.c.
References DetectEngineResetMaxSigId(), Signature_::next, DetectEngineCtx_::sig_list, and SigFree().
Referenced by DetectEngineCtxFree().
Signature* SigFindSignatureBySidGid (DetectEngineCtx * de_ctx, uint32_t sid, uint32_t gid)
Find a specific signature by sid and gid.
Parameters
de_ctx detection engine ctx
sid the signature id
gid the signature group id
Return values
s sig found
NULL sig not found
Definition at line 2073 of file detect.c.
References Signature_::gid, Signature_::id, Signature_::next, and DetectEngineCtx_::sig_list.
int SigGroupBuild (DetectEngineCtx * de_ctx)
Convert the signature list into the runtime match structure.
Parameters
de_ctx Pointer to the Detection Engine Context whose Signatures have to be processed
Return values
0 On Success.
-1 On failure.
Definition at line 4637 of file detect.c.
References CudaHandlerGetCudaProfile(), CudaHandlerModuleGetContext(), DetectSetFastPatternAndItsId(), ENGINE_SGH_MPM_FACTORY_CONTEXT_SINGLE, DetectEngineCtx_::mpm_matcher, mpm_table, MpmFactoryGetMpmCtxForProfile(), Signature_::next, Signature_::num, PatternMatchDefaultMatcher(), MpmTableElmt_::Prepare, SC_ERR_DETECT_PREPARE, SC_ERR_FATAL, SCLogError, SCProfilingRuleInitCounters(), DetectEngineCtx_::sgh_mpm_context, DetectEngineCtx_::sgh_mpm_context_hcbd, DetectEngineCtx_::sgh_mpm_context_hcd, DetectEngineCtx_::sgh_mpm_context_hhd, DetectEngineCtx_::sgh_mpm_context_hhhd, DetectEngineCtx_::sgh_mpm_context_hmd, DetectEngineCtx_::sgh_mpm_context_hrhd, DetectEngineCtx_::sgh_mpm_context_hrhhd, DetectEngineCtx_::sgh_mpm_context_hrud, DetectEngineCtx_::sgh_mpm_context_hsbd, DetectEngineCtx_::sgh_mpm_context_hscd, DetectEngineCtx_::sgh_mpm_context_hsmd, DetectEngineCtx_::sgh_mpm_context_huad, DetectEngineCtx_::sgh_mpm_context_proto_other_packet, DetectEngineCtx_::sgh_mpm_context_proto_tcp_packet, DetectEngineCtx_::sgh_mpm_context_proto_udp_packet, DetectEngineCtx_::sgh_mpm_context_smtp, DetectEngineCtx_::sgh_mpm_context_stream, DetectEngineCtx_::sgh_mpm_context_uri, DetectEngineCtx_::sig_list, SigAddressPrepareStage1(), SigAddressPrepareStage2(), SigAddressPrepareStage3(), SigAddressPrepareStage4(), and DetectEngineCtx_::signum.
Referenced by SigLoadSignatures().
int SigGroupCleanup (DetectEngineCtx * de_ctx)
Definition at line 4918 of file detect.c.
References SigAddressCleanupStage1().
Referenced by DetectEngineCtxFree().
int SigLoadSignatures (DetectEngineCtx * de_ctx, char * sig_file, int sig_file_exclusive)
Load signatures.
Parameters
de_ctx Pointer to the detection engine context
sig_file Filename (or pattern) holding signatures
sig_file_exclusive File passed in 'sig_file' should be loaded exclusively.
Return values
-1 on error
Definition at line 442 of file detect.c.
References SigFileLoaderStat_::bad_files, SigFileLoaderStat_::bad_sigs_total, CleanupFPAnalyzer(), CleanupRuleAnalyzer(), ConfGetNode(), DetectEngineCtx_::config_prefix, ConfNodeIsSequence(), DetectLoadCompleteSigPath(), DetectParseDupSigHashFree(), DetectEngineCtx_::failure_fatal, SigFileLoaderStat_::good_sigs_total, next, RUNMODE_ENGINE_ANALYSIS, RunmodeGetCurrent(), SC_ERR_INVALID_ARGUMENT, SC_ERR_NO_RULES, SC_ERR_NO_RULES_LOADED, SCEnter, SCFree, SCLogError, SCLogInfo, SCLogWarning, SCReturnInt, SCSigOrderSignatures(), SCSigRegisterSignatureOrderingFuncs(), SCSigSignatureOrderingModuleCleanup(), SetupFPAnalyzer(), SetupRuleAnalyzer(), SigGroupBuild(), TAILQ_FOREACH, SigFileLoaderStat_::total_files, TRUE, ConfNode_::val, and ptxdump::varname.
Referenced by DetectEngineReload().
SigMatch* SigMatchAlloc (void)
Definition at line 240 of file detect-parse.c.
References SigMatch_::next, SigMatch_::prev, SCMalloc, and unlikely.
Referenced by DetectAppLayerProtocolSetup(), DetectByteExtractSetup(), DetectBytejumpSetup(), DetectBytetestSetup(), DetectContentSetup(), DetectFlowvarPostMatchSetup(), DetectIsdataatSetup(), DetectRpcSetup(), DetectSslStateSetup(), and DetectWindowSetup().
void SigMatchFree (SigMatch * sm)
free a SigMatch
Parameters
sm SigMatch to free.
free the ctx, for that we call the Free func
Definition at line 255 of file detect-parse.c.
References SigMatch_::ctx, SigTableElmt_::Free, SCFree, sigmatch_table, and SigMatch_::type.
Referenced by DetectIPProtoRemoveAllSMs(), and SigFree().
int SigMatchSignatures (ThreadVars * th_v, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Packet * p)
Signature match function.
Return values
1 one or more signatures matched
0 no matches were found
Definition at line 1232 of file detect.c.
References Signature_::action, ACTION_DROP, Signature_::addr_dst_match4, Signature_::addr_dst_match4_cnt, Signature_::addr_dst_match6, Signature_::addr_dst_match6_cnt, Signature_::addr_src_match4, Signature_::addr_src_match4_cnt, Signature_::addr_src_match6, Signature_::addr_src_match6_cnt, Packet_::alerts, Flow_::alparser, Flow_::alproto, Signature_::alproto, ALPROTO_DCERPC, ALPROTO_SMB, ALPROTO_SMB2, ALPROTO_UNKNOWN, Flow_::alstate, AppLayerParserGetStateVersion(), AppLayerParserHasDecoderEvents(), AppLayerParserProtocolSupportsTxs(), PacketAlerts_::cnt, DetectEngineThreadCtx_::counter_alerts, DetectEngineThreadCtx_::counter_fnonmpm_list, DetectEngineThreadCtx_::counter_match_list, DetectEngineThreadCtx_::counter_mpm_list, DetectEngineThreadCtx_::counter_nonmpm_list, SigMatchData_::ctx, StreamMsg_::data, StreamMsg_::data_len, Flow_::de_ctx_id, Flow_::de_state, DE_STATE_MATCH_NO_NEW_STATE, DetectEngineThreadCtx_::de_state_sig_array, DetectEngineThreadCtx_::de_state_sig_array_len, debuglog_enabled, DeStateDetectContinueDetection(), DeStateDetectStartDetection(), DeStateFlowHasInspectableState(), DeStateUpdateInspectTransactionId(), DETECT_ENGINE_THREAD_CTX_STREAM_CONTENT_MATCH, DETECT_PROTO_IPV4, DETECT_PROTO_IPV6, DETECT_SM_LIST_AMATCH, DETECT_SM_LIST_DMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_MATCH, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectAddressMatchIPv4(), DetectAddressMatchIPv6(), DetectEngineCleanHCBDBuffers(), DetectEngineCleanHHDBuffers(), DetectEngineCleanHSBDBuffers(), DetectEngineInspectPacketPayload(), DetectEngineInspectStreamPayload(), DetectEngineStateReset(), DetectEngineStateResetTxs(), DetectPortLookupGroup(), DetectProtoContainsProto(), DetectSignatureApplyActions(), Packet_::dp, Signature_::dp, Signature_::dsize_high, Signature_::dsize_low, Packet_::dst, FileDisableFilesize(), FileDisableMagic(), FileDisableMd5(), FileDisableStoring(), FileForceMagic(), FileForceMd5(), DetectEngineThreadCtx_::filestore_cnt, SigGroupHead_::filestore_cnt, DetectProto_::flags, Flow_::flags, Signature_::flags, Packet_::flags, DetectEngineThreadCtx_::flags, SigGroupHead_::flags, Packet_::flow, FLOW_ACTION_DROP, FLOW_PKT_ESTABLISHED, FLOW_PKT_TOCLIENT, FLOW_PKT_TOCLIENT_IPONLY_SET, FLOW_PKT_TOSERVER, FLOW_PKT_TOSERVER_IPONLY_SET, FLOW_SGH_TOCLIENT, FLOW_SGH_TOSERVER, FLOW_TOCLIENT_IPONLY_SET, FLOW_TOSERVER_IPONLY_SET, Packet_::flowflags, FlowGetAppProtocol(), FlowGetAppState(), FlowGetDisruptionFlags(), FLOWLOCK_RDLOCK, FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, FlowSetIPOnlyFlag(), Flow_::flowvar, GenericVarFree(), Signature_::id, DetectEngineCtx_::id, DetectEngineCtx_::io_ctx, DetectEngineThreadCtx_::io_ctx, IP_GET_IPPROTO, IPOnlyMatchPacket(), SigMatchData_::is_last, KEYWORD_PROFILING_END, KEYWORD_PROFILING_SET_LIST, KEYWORD_PROFILING_START, likely, m, Flow_::m, SigTableElmt_::Match, DetectEngineThreadCtx_::match_array, DetectEngineThreadCtx_::match_array_cnt, Signature_::mpm_pattern_id_div_8, Signature_::mpm_pattern_id_mod_8, StreamMsg_::next, next, DetectEngineThreadCtx_::non_mpm_id_cnt, SigGroupHead_::non_mpm_store_cnt, Signature_::num, PACKET_ALERT_FLAG_DROP_FLOW, PACKET_ALERT_FLAG_STATE_MATCH, PACKET_ALERT_FLAG_STREAM_MATCH, PACKET_DROP, PACKET_PROFILING_DETECT_END, PACKET_PROFILING_DETECT_START, PacketAlertAppend(), PacketAlertFinalize(), PacketPatternCleanup(), PatternMatcherQueue_::pattern_id_bitarray, Packet_::payload_len, Packet_::pcap_cnt, PKT_HAS_FLOW, PKT_IS_FRAGMENT, PKT_IS_IPV4, PKT_IS_IPV6, PKT_NOPACKET_INSPECTION, PKT_STREAM_ADD, PKT_STREAM_EOF, PKT_STREAM_EST, DetectEngineThreadCtx_::pmq, PrintRawDataFp(), PROF_DETECT_ALERT, PROF_DETECT_CLEANUP, PROF_DETECT_GETSGH, PROF_DETECT_IPONLY, PROF_DETECT_MPM, PROF_DETECT_NONMPMLIST, PROF_DETECT_PREFILTER, PROF_DETECT_RULES, PROF_DETECT_STATEFUL, Flow_::proto, Packet_::proto, Signature_::proto, PatternMatcherQueue_::rule_id_array_cnt, RULE_PROFILING_END, RULE_PROFILING_START, SCEnter, SCLogDebug, SCMutexLock, SCMutexUnlock, SCReturnInt, DetectEngineThreadCtx_::sgh, Flow_::sgh_toclient, Flow_::sgh_toserver, SIG_FLAG_APPLAYER, SIG_FLAG_DP_ANY, SIG_FLAG_DSIZE, SIG_FLAG_DST_ANY, SIG_FLAG_MPM_APPLAYER, SIG_FLAG_MPM_APPLAYER_NEG, SIG_FLAG_MPM_PACKET, SIG_FLAG_MPM_PACKET_NEG, SIG_FLAG_MPM_STREAM, SIG_FLAG_MPM_STREAM_NEG, SIG_FLAG_NOALERT, SIG_FLAG_REQUIRE_FLOWVAR, SIG_FLAG_REQUIRE_PACKET, SIG_FLAG_REQUIRE_STREAM, SIG_FLAG_SP_ANY, SIG_FLAG_SRC_ANY, SIG_FLAG_STATE_MATCH, SIG_GROUP_HEAD_HAVEFILEMAGIC, SIG_GROUP_HEAD_HAVEFILEMD5, SIG_GROUP_HEAD_HAVEFILESIZE, SigIntId, sigmatch_table, SigMatchSignaturesGetSgh(), SigMatchSignaturesRunPostMatch(), SignatureMask, Signature_::sm_arrays, Signature_::sm_lists, SMS_USE_FLOW_SGH, SMS_USED_PM, SMS_USED_STREAM_PM, DetectEngineThreadCtx_::smsg_pmq, Packet_::sp, Signature_::sp, Packet_::src, StatsAddUI64(), STREAM_EOF, STREAM_TOCLIENT, STREAM_TOSERVER, StreamMsgReturnListToPool(), StreamPatternCleanup(), Flow_::tenant_id, Packet_::tenant_id, SigMatchData_::type, and unlikely.
Referenced by Detect().
void SigMatchSignaturesBuildMatchArray (DetectEngineThreadCtx * , Packet * , SignatureMask , uint16_t)
SigGroupHead* SigMatchSignaturesGetSgh (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Packet * p)
Get the SigGroupHead for a packet.
Parameters
de_ctx detection engine context
det_ctx thread detection engine content
p packet
Return values
sgh the SigGroupHead or NULL if non applies to the packet
Definition at line 595 of file detect.c.
References PacketEngineEvents_::cnt, DetectEngineCtx_::decoder_event_sgh, DetectAddressLookupInHead(), DetectPortLookupGroup(), Packet_::dp, Packet_::dst, DetectAddress_::dst_gh, DetectPort_::dst_ph, Packet_::events, DetectEngineCtx_::flow_gh, FLOW_PKT_TOCLIENT, Packet_::flowflags, IP_GET_IPPROTO, DetectAddress_::port, Packet_::proto, SCEnter, SCLogDebug, SCReturnPtr, DetectAddress_::sh, DetectPort_::sh, Packet_::sp, Packet_::src, and DetectEngineLookupFlow_::src_gh.
Referenced by SigMatchSignatures().
int SigMatchSignaturesRunPostMatch (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s)
Definition at line 555 of file detect.c.
References SigMatchData_::ctx, DETECT_SM_LIST_POSTMATCH, DetectFilestorePostMatch(), Signature_::flags, SigMatchData_::is_last, KEYWORD_PROFILING_END, KEYWORD_PROFILING_SET_LIST, KEYWORD_PROFILING_START, SigTableElmt_::Match, SCLogDebug, SIG_FLAG_FILESTORE, sigmatch_table, Signature_::sm_arrays, and SigMatchData_::type.
Referenced by SigMatchSignatures().
int SignatureIsFilemagicInspecting (Signature * s)
Check if a signature contains the filemagic keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 2124 of file detect.c.
References Signature_::file_flags, and FILE_SIG_NEED_MAGIC.
Referenced by SigGroupHeadSetFilemagicFlag().
int SignatureIsFileMd5Inspecting (Signature * s)
Check if a signature contains the filemd5 keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 2143 of file detect.c.
References Signature_::file_flags, and FILE_SIG_NEED_MD5.
Referenced by SigGroupHeadSetFileMd5Flag().
int SignatureIsFilesizeInspecting (Signature * s)
Check if a signature contains the filesize keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 2162 of file detect.c.
References Signature_::file_flags, and FILE_SIG_NEED_SIZE.
Referenced by SigGroupHeadSetFilesizeFlag().
int SignatureIsFilestoring (Signature * s)
Check if a signature contains the filestore keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 2105 of file detect.c.
References Signature_::flags, and SIG_FLAG_FILESTORE.
Referenced by SigGroupHeadSetFilestoreCount().
int SignatureIsIPOnly (DetectEngineCtx * de_ctx, Signature * s)
Test is a initialized signature is IP only.
Parameters
de_ctx detection engine ctx
s the signature
Return values
1 sig is ip only
0 sig is not ip only
Definition at line 2179 of file detect.c.
References Signature_::alproto, ALPROTO_UNKNOWN, Signature_::CidrDst, Signature_::CidrSrc, SigMatch_::ctx, DE_QUIET, DETECT_FLOWBITS, DETECT_FLOWBITS_CMD_SET, DETECT_SM_LIST_AMATCH, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_MATCH, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, Signature_::flags, DetectEngineCtx_::flags, SigTableElmt_::flags, Signature_::id, IPOnlyCIDRItem_::negated, IPOnlyCIDRItem_::next, SigMatch_::next, SCLogDebug, SIG_FLAG_DST_ANY, SIG_FLAG_SRC_ANY, SIGMATCH_IPONLY_COMPAT, sigmatch_table, Signature_::sm_lists, and SigMatch_::type.
Referenced by SigAddressPrepareStage1().
void SigRegisterTests (void)
Definition at line 12117 of file detect.c.
References DetectSimdRegisterTests(), IPOnlyRegisterTests(), and SigParseRegisterTests().
Referenced by TmModuleDetectRegister().
void SigTableList (const char * keyword)
Definition at line 4970 of file detect.c.
References AppLayerGetProtoName(), SIGMATCH_NOT_BUILT, and sigmatch_table.
Referenced by ListKeywords().
void SigTableRegisterTests (void)
Definition at line 5137 of file detect.c.
References coverage_unittests, DETECT_TBLSIZE, g_ut_covered, g_ut_modules, SigTableElmt_::RegisterTests, SC_WARN_NO_UNITTESTS, SCLogDebug, SCLogWarning, and sigmatch_table.
Referenced by RunUnittests().
void SigTableSetup (void)
Definition at line 5032 of file detect.c.
References DetectAckRegister(), DetectAppLayerEventRegister(), DetectAppLayerProtocolRegister(), DetectAsn1Register(), DetectByteExtractRegister(), DetectBytejumpRegister(), DetectBytetestRegister(), DetectClasstypeRegister(), DetectContentRegister(), DetectCsumRegister(), DetectDceIfaceRegister(), DetectDceOpnumRegister(), DetectDceStubDataRegister(), DetectDepthRegister(), DetectDetectionFilterRegister(), DetectDistanceRegister(), DetectDnsQueryRegister(), DetectDsizeRegister(), DetectEngineEventRegister(), DetectFastPatternRegister(), DetectFiledataRegister(), DetectFileextRegister(), DetectFilemagicRegister(), DetectFileMd5Register(), DetectFilenameRegister(), DetectFilesizeRegister(), DetectFilestoreRegister(), DetectFlagsRegister(), DetectFlowbitsRegister(), DetectFlowintRegister(), DetectFlowRegister(), DetectFlowvarRegister(), DetectFragBitsRegister(), DetectFragOffsetRegister(), DetectFtpbounceRegister(), DetectGeoipRegister(), DetectGidRegister(), DetectHostbitsRegister(), DetectHttpClientBodyRegister(), DetectHttpCookieRegister(), DetectHttpHeaderRegister(), DetectHttpHHRegister(), DetectHttpHRHRegister(), DetectHttpMethodRegister(), DetectHttpRawHeaderRegister(), DetectHttpRawUriRegister(), DetectHttpServerBodyRegister(), DetectHttpStatCodeRegister(), DetectHttpStatMsgRegister(), DetectHttpUARegister(), DetectHttpUriRegister(), DetectIcmpIdRegister(), DetectIcmpSeqRegister(), DetectICodeRegister(), DetectIdRegister(), DetectIpOptsRegister(), DetectIPProtoRegister(), DetectIPRepRegister(), DetectIsdataatRegister(), DetectITypeRegister(), DetectL3ProtoRegister(), DetectLuaRegister(), DetectMarkRegister(), DetectMetadataRegister(), DetectModbusRegister(), DetectMsgRegister(), DetectNoalertRegister(), DetectNocaseRegister(), DetectOffsetRegister(), DetectPcreRegister(), DetectPktDataRegister(), DetectPktvarRegister(), DetectPriorityRegister(), DetectRawbytesRegister(), DetectReferenceRegister(), DetectReplaceRegister(), DetectRevRegister(), DetectRpcRegister(), DetectSameipRegister(), DetectSeqRegister(), DetectSidRegister(), DetectSshSoftwareVersionRegister(), DetectSshVersionRegister(), DetectSslStateRegister(), DetectSslVersionRegister(), DetectStreamSizeRegister(), DetectTagRegister(), DetectTemplateBufferRegister(), DetectTemplateRegister(), DetectThresholdRegister(), DetectTlsRegister(), DetectTlsVersionRegister(), DetectTosRegister(), DetectTtlRegister(), DetectUricontentRegister(), DetectUrilenRegister(), DetectWindowRegister(), DetectWithinRegister(), DetectXbitsRegister(), and sigmatch_table.
Referenced by ListKeywords(), and RunUnittests().
void TmModuleDetectRegister (void)
Definition at line 225 of file detect.c.
References TmModule_::cap_flags, Detect(), DetectExitPrintStats(), DetectThreadDeinit(), DetectThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, PacketAlertTagInit(), TmModule_::RegisterTests, SigRegisterTests(), TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DETECT_TM, TMM_DETECT, and tmm_modules.
Referenced by RegisterAllModules().
Variable Documentation
SigTableElmt sigmatch_table[DETECT_TBLSIZE]
Definition at line 1233 of file detect.h.
Referenced by DeStateDetectStartDetection(), DetectAckRegister(), DetectAppLayerEventRegister(), DetectAppLayerProtocolRegister(), DetectAsn1Register(), DetectByteExtractRegister(), DetectBytejumpRegister(), DetectBytetestRegister(), DetectClasstypeRegister(), DetectContentRegister(), DetectCsumRegister(), DetectDceIfaceRegister(), DetectDceOpnumRegister(), DetectDceStubDataRegister(), DetectDepthRegister(), DetectDetectionFilterRegister(), DetectDistanceRegister(), DetectDnsQueryRegister(), DetectDsizeRegister(), DetectEngineContentModifierBufferSetup(), DetectEngineEventRegister(), DetectEngineInspectGenericList(), DetectFastPatternRegister(), DetectFiledataRegister(), DetectFileextRegister(), DetectFilemagicRegister(), DetectFileMd5Register(), DetectFilenameRegister(), DetectFilesizeRegister(), DetectFilestoreRegister(), DetectFlagsRegister(), DetectFlowbitsRegister(), DetectFlowintRegister(), DetectFlowRegister(), DetectFlowvarRegister(), DetectFragBitsRegister(), DetectFragOffsetRegister(), DetectFtpbounceRegister(), DetectGeoipRegister(), DetectGidRegister(), DetectHostbitsRegister(), DetectHttpClientBodyRegister(), DetectHttpCookieRegister(), DetectHttpHeaderRegister(), DetectHttpHHRegister(), DetectHttpHRHRegister(), DetectHttpMethodRegister(), DetectHttpRawHeaderRegister(), DetectHttpRawUriRegister(), DetectHttpServerBodyRegister(), DetectHttpStatCodeRegister(), DetectHttpStatMsgRegister(), DetectHttpUARegister(), DetectHttpUriRegister(), DetectIcmpIdRegister(), DetectIcmpSeqRegister(), DetectICodeRegister(), DetectIdRegister(), DetectIpOptsRegister(), DetectIPProtoRegister(), DetectIPRepRegister(), DetectIsdataatRegister(), DetectITypeRegister(), DetectL3ProtoRegister(), DetectLuaRegister(), DetectMarkRegister(), DetectMetadataRegister(), DetectModbusRegister(), DetectMsgRegister(), DetectNoalertRegister(), DetectNocaseRegister(), DetectOffsetRegister(), DetectPcreRegister(), DetectPktDataRegister(), DetectPktvarRegister(), DetectPriorityRegister(), DetectRawbytesRegister(), DetectReferenceRegister(), DetectReplaceRegister(), DetectRevRegister(), DetectRpcRegister(), DetectSameipRegister(), DetectSeqRegister(), DetectSidRegister(), DetectSshSoftwareVersionRegister(), DetectSshVersionRegister(), DetectSslStateRegister(), DetectSslVersionRegister(), DetectStreamSizeRegister(), DetectTagRegister(), DetectTemplateBufferRegister(), DetectTemplateRegister(), DetectThresholdRegister(), DetectTlsRegister(), DetectTlsVersionRegister(), DetectTosRegister(), DetectTtlRegister(), DetectUricontentRegister(), DetectUrilenRegister(), DetectWindowRegister(), DetectWithinRegister(), DetectXbitsRegister(), DoDump(), IPOnlyMatchPacket(), PacketAlertFinalize(), SigMatchFree(), SigMatchSignatures(), SigMatchSignaturesRunPostMatch(), SignatureIsIPOnly(), SigTableGet(), SigTableList(), SigTableRegisterTests(), and SigTableSetup().