suricata: src/detect-mark.c File Reference
detect-mark.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "flow-var.h"
#include "decode-events.h"
#include "detect-mark.h"
#include "detect-parse.h"
#include "util-unittest.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "([0x]*[0-9a-f]+)/([0x]*[0-9a-f]+)"
#define MAX_SUBSTRINGS 30
Functions
int DetectMarkPacket (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
void DetectMarkDataFree (void *ptr)
void DetectMarkRegister (void)
Registration function for nfq_set_mark: keyword.
void MarkRegisterTests (void)
this function registers unit tests for Mark
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Implements the mark keyword. Based on detect-gid by Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Definition in file detect-mark.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
#define PARSE_REGEX "([0x]*[0-9a-f]+)/([0x]*[0-9a-f]+)"
Definition at line 40 of file detect-mark.c.
Referenced by DetectMarkRegister().
Function Documentation
void DetectMarkDataFree (void * ptr)
Definition at line 233 of file detect-mark.c.
References SCFree.
Referenced by DetectMarkRegister().
int DetectMarkPacket (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Definition at line 240 of file detect-mark.c.
References Packet_::flags, DetectMarkData_::mark, NFQPacketVars_::mark, DetectMarkData_::mask, Packet_::nfq_v, and PKT_MARK_MODIFIED.
Referenced by DetectMarkRegister().
void DetectMarkRegister (void)
Registration function for nfq_set_mark: keyword.
Registration function for nfq_set_mark: keyword
Definition at line 53 of file detect-mark.c.
References DETECT_MARK, DetectMarkDataFree(), DetectMarkPacket(), SigTableElmt_::Free, MarkRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void MarkRegisterTests (void)
this function registers unit tests for Mark
This function registers unit tests for Mark
Definition at line 345 of file detect-mark.c.
Referenced by DetectMarkRegister().