suricata: src/detect-hostbits.c File Reference
detect-hostbits.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "threads.h"
#include "flow.h"
#include "flow-util.h"
#include "detect-hostbits.h"
#include "util-spm.h"
#include "detect-engine-sigorder.h"
#include "app-layer-parser.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow-bit.h"
#include "host-bit.h"
#include "util-var-name.h"
#include "util-unittest.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "([a-z]+)(?:\\s*,\\s*([^\\s,]+))?(?:\\s*,\\s*([^,\\s]+))?"
Functions
int DetectHostbitMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, const SigMatchCtx *)
void DetectHostbitFree (void *)
void HostBitsRegisterTests (void)
this function registers unit tests for HostBits
void DetectHostbitsRegister (void)
int DetectXbitMatchHost (Packet *p, const DetectXbitsData *xd)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements the hostbits keyword
Definition in file detect-hostbits.c.
Macro Definition Documentation
#define PARSE_REGEX "([a-z]+)(?:\\s*,\\s*([^\\s,]+))?(?:\\s*,\\s*([^,\\s]+))?"
Definition at line 64 of file detect-hostbits.c.
Referenced by DetectHostbitsRegister().
Function Documentation
void DetectHostbitFree (void * ptr)
Definition at line 449 of file detect-hostbits.c.
References SCFree.
Referenced by DetectHostbitsRegister().
int DetectHostbitMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
Definition at line 286 of file detect-hostbits.c.
References DetectXbitMatchHost().
Referenced by DetectHostbitsRegister().
void DetectHostbitsRegister (void)
Definition at line 73 of file detect-hostbits.c.
References SigTableElmt_::desc, DETECT_HOSTBITS, DetectHostbitFree(), DetectHostbitMatch(), SigTableElmt_::flags, SigTableElmt_::Free, HostBitsRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, and sigmatch_table.
Referenced by SigTableSetup().
int DetectXbitMatchHost (Packet * p, const DetectXbitsData * xd)
Definition at line 259 of file detect-hostbits.c.
References DetectXbitsData_::cmd, DETECT_XBITS_CMD_ISNOTSET, DETECT_XBITS_CMD_ISSET, DETECT_XBITS_CMD_SET, DETECT_XBITS_CMD_TOGGLE, DETECT_XBITS_CMD_UNSET, SC_ERR_UNKNOWN_VALUE, and SCLogError.
Referenced by DetectHostbitMatch(), and DetectXbitMatch().
void HostBitsRegisterTests (void)
this function registers unit tests for HostBits
Definition at line 1456 of file detect-hostbits.c.
Referenced by DetectHostbitsRegister().