suricata: src/detect-engine-port.h File Reference
detect-engine-port.h File Reference
Functions
int DetectPortParse (const DetectEngineCtx *, DetectPort **head, char *str)
Function for parsing port strings.
DetectPort * DetectPortCopy (DetectEngineCtx *, DetectPort *)
Function that return a copy of DetectPort src.
DetectPort * DetectPortCopySingle (DetectEngineCtx *, DetectPort *)
Function that return a copy of DetectPort src sigs.
int DetectPortInsertCopy (DetectEngineCtx *, DetectPort **, DetectPort *)
Copy and insert the new DetectPort, with a copy list of sigs.
int DetectPortInsert (DetectEngineCtx *, DetectPort **, DetectPort *)
function for inserting a port group object. This also makes sure SigGroupContainer lists are handled correctly.
void DetectPortCleanupList (DetectPort *head)
Free a DetectPort list and each of its members.
DetectPort * DetectPortLookup (DetectPort *head, DetectPort *dp)
Used to see if the exact same portrange exists in the list.
int DetectPortAdd (DetectPort **head, DetectPort *dp)
Do a sorted insert, where the top of the list should be the biggest port range.
DetectPort * DetectPortLookupGroup (DetectPort *dp, uint16_t port)
Function that find the group matching address in a group head.
void DetectPortPrintMemory (void)
Prints Memory statistics of the counters at detect-engine-port.[c,h].
DetectPort * DetectPortDpHashLookup (DetectEngineCtx *, DetectPort *)
Function that search a destination DetectPort in the hashtable.
DetectPort * DetectPortDpHashGetListPtr (DetectEngineCtx *)
int DetectPortDpHashInit (DetectEngineCtx *)
Function that initialize the HashListTable of destination DetectPort.
void DetectPortDpHashFree (DetectEngineCtx *)
Function that free the HashListTable of destination DetectPort.
int DetectPortDpHashAdd (DetectEngineCtx *, DetectPort *)
Function that add a destination DetectPort into the hashtable.
void DetectPortDpHashReset (DetectEngineCtx *)
Function that reset the HashListTable of destination DetectPort (Free and Initialize it)
DetectPort * DetectPortSpHashLookup (DetectEngineCtx *, DetectPort *)
Function that search a source DetectPort in the hashtable.
int DetectPortSpHashInit (DetectEngineCtx *)
Function that initialize the HashListTable of source DetectPort.
void DetectPortSpHashFree (DetectEngineCtx *)
Function that free the HashListTable of source DetectPort.
int DetectPortSpHashAdd (DetectEngineCtx *, DetectPort *)
Function that add a source DetectPort into the hashtable.
void DetectPortSpHashReset (DetectEngineCtx *)
Function that reset the HashListTable of source DetectPort (Free and Initialize it)
int DetectPortJoin (DetectEngineCtx *, DetectPort *target, DetectPort *source)
Function to join the source group to the target and its members.
void DetectPortPrint (DetectPort *)
Helper function that print the DetectPort info.
void DetectPortPrintList (DetectPort *head)
Helper function used to print the list of ports present in this DetectPort list.
int DetectPortCmp (DetectPort *, DetectPort *)
Function that compare port groups.
void DetectPortFree (DetectPort *)
Free a DetectPort and its members.
int DetectPortTestConfVars (void)
void DetectPortTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-engine-port.h.
Function Documentation
int DetectPortAdd (DetectPort ** head, DetectPort * dp)
Do a sorted insert, where the top of the list should be the biggest port range.
Todo:
XXX current sorting only works for overlapping ranges
Parameters
head Pointer to the DetectPort list head
dp Pointer to DetectPort to search in the DetectPort list
Return values
0 if dp is added correctly
Definition at line 202 of file detect-engine-port.c.
References DetectPortCmp(), DetectPort_::next, PORT_EB, and DetectPort_::prev.
void DetectPortCleanupList (DetectPort * head)
Free a DetectPort list and each of its members.
Parameters
head Pointer to the DetectPort list head
Definition at line 177 of file detect-engine-port.c.
References DetectPortFree(), DetectPort_::next, and next.
Referenced by AppLayerProtoDetectPPRegister(), BuildDestinationAddressHeadsWithBothPorts(), DetectAddressFree(), DetectPortFree(), DetectPortParse(), DetectPortTestConfVars(), PortParse(), and SigFree().
int DetectPortCmp (DetectPort * a, DetectPort * b)
Function that compare port groups.
Parameters
a pointer to DetectPort "a"
b pointer to DetectPort "b"
Return values
PORT_XX (Port enum value, XX is EQ, ES, EB, LE, etc)
PORT_ER on error
Definition at line 710 of file detect-engine-port.c.
References BUG_ON, DetectPort_::flags, DetectPort_::port, DetectPort_::port2, PORT_EB, PORT_EQ, PORT_ER, PORT_ES, PORT_FLAG_ANY, PORT_GE, PORT_GT, PORT_LE, and PORT_LT.
Referenced by DetectPortAdd(), DetectPortInsert(), DetectPortLookup(), and DetectPortParseMergeNotPorts().
DetectPort* DetectPortCopy (DetectEngineCtx * de_ctx, DetectPort * src)
Function that return a copy of DetectPort src.
Parameters
de_ctx Pointer to the current Detection Engine Context
src Pointer to a DetectPort group to copy
Return values
Pointer to a DetectPort instance (copy of src)
NULL on error
Definition at line 766 of file detect-engine-port.c.
References DetectPortCopy(), DetectPortInit(), DetectPort_::next, DetectPort_::port, DetectPort_::port2, and DetectPort_::prev.
Referenced by DetectPortCopy(), and DetectPortParseMergeNotPorts().
DetectPort* DetectPortCopySingle (DetectEngineCtx * de_ctx, DetectPort * src)
Function that return a copy of DetectPort src sigs.
Parameters
de_ctx Pointer to the current Detection Engine Context
src Pointer to a DetectPort group to copy
Return values
Pointer to a DetectPort instance (copy of src)
NULL on error
Definition at line 800 of file detect-engine-port.c.
References DetectPortInit(), DetectPort_::port, DetectPort_::port2, DetectPort_::sh, and SigGroupHeadCopySigs().
Referenced by BuildDestinationAddressHeadsWithBothPorts(), CreateGroupedPortList(), and DetectPortInsertCopy().
int DetectPortDpHashAdd (DetectEngineCtx * de_ctx, DetectPort * p)
Function that add a destination DetectPort into the hashtable.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
p Pointer to the DetectPort to add
Definition at line 1625 of file detect-engine-port.c.
References DetectEngineCtx_::dport_hash_table, and HashListTableAdd().
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DetectPortDpHashFree (DetectEngineCtx * de_ctx)
Function that free the HashListTable of destination DetectPort.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
Definition at line 1598 of file detect-engine-port.c.
References DetectEngineCtx_::dport_hash_table, and HashListTableFree().
Referenced by DetectEngineCtxFree(), DetectPortDpHashReset(), and SigAddressPrepareStage3().
DetectPort* DetectPortDpHashGetListPtr (DetectEngineCtx *)
int DetectPortDpHashInit (DetectEngineCtx * de_ctx)
Function that initialize the HashListTable of destination DetectPort.
Parameters
de_ctx Pointer to the current DetectionEngineContext
Return values
0 HashListTable initialization succes
-1 Error
Definition at line 1581 of file detect-engine-port.c.
References DetectPortCompareFunc(), DetectPortFreeFunc(), DetectPortHashFunc(), DetectEngineCtx_::dport_hash_table, HashListTableInit(), and PORT_HASH_SIZE.
Referenced by DetectPortDpHashReset().
DetectPort* DetectPortDpHashLookup (DetectEngineCtx * de_ctx, DetectPort * p)
Function that search a destination DetectPort in the hashtable.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
p Pointer to the DetectPort to search
Definition at line 1636 of file detect-engine-port.c.
References DetectEngineCtx_::dport_hash_table, and HashListTableLookup().
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DetectPortDpHashReset (DetectEngineCtx * de_ctx)
Function that reset the HashListTable of destination DetectPort (Free and Initialize it)
Parameters
de_ctx Pointer to the current DetectionEngineCtx
Definition at line 1613 of file detect-engine-port.c.
References DetectPortDpHashFree(), and DetectPortDpHashInit().
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DetectPortFree (DetectPort * dp)
Free a DetectPort and its members.
Parameters
dp Pointer to the DetectPort that has to be freed.
Definition at line 90 of file detect-engine-port.c.
References DetectPortCleanupList(), DetectPort_::dst_ph, DetectPort_::flags, PORT_GROUP_PORTS_COPY, PORT_SIGGROUPHEAD_COPY, SCFree, DetectPort_::sh, and SigGroupHeadFree().
Referenced by CreateGroupedPortList(), DetectPortCleanupList(), DetectPortFreeFunc(), DetectPortInsert(), and DetectPortParseMergeNotPorts().
int DetectPortInsert (DetectEngineCtx * de_ctx, DetectPort ** head, DetectPort * new)
function for inserting a port group object. This also makes sure SigGroupContainer lists are handled correctly.
Parameters
de_ctx Pointer to the current detection engine context
head Pointer to the DetectPort list head
dp DetectPort to search in the DetectPort list
Return values
1 inserted
0 not inserted, memory of new is freed
-1 error
Definition at line 267 of file detect-engine-port.c.
References BUG_ON, DetectPort_::cnt, DetectPortCmp(), DetectPortFree(), DetectPortInsert(), DetectPortPrint(), DetectPort_::next, PORT_EQ, PORT_ER, PORT_GT, PORT_LT, DetectPort_::prev, SCLogDebug, SCLogDebugEnabled(), DetectPort_::sh, and SigGroupHeadCopySigs().
Referenced by CreateGroupedPortList(), DetectPortInsert(), and DetectPortInsertCopy().
int DetectPortInsertCopy (DetectEngineCtx * de_ctx, DetectPort ** head, DetectPort * new)
Copy and insert the new DetectPort, with a copy list of sigs.
Parameters
de_ctx Pointer to the current detection engine context
head Pointer to the DetectPort list head
new Pointer to DetectPort to search in the DetectPort list
Return values
0 if dp is added correctly
Definition at line 245 of file detect-engine-port.c.
References DetectPortCopySingle(), and DetectPortInsert().
Referenced by CreateGroupedAddrList(), DetectAddressCutIPv4(), DetectAddressCutIPv6(), DetectAddressInsert(), and DetectAddressJoin().
int DetectPortJoin (DetectEngineCtx * de_ctx, DetectPort * target, DetectPort * source)
Function to join the source group to the target and its members.
Parameters
de_ctx Pointer to the current Detection Engine Context
target Pointer to DetectPort group where the source is joined
source Pointer to DetectPort group that will join into the target
Return values
-1 on error
0 on success
Definition at line 895 of file detect-engine-port.c.
References DetectPort_::cnt, DetectPort_::port, DetectPort_::port2, DetectPort_::sh, and SigGroupHeadCopySigs().
Referenced by CreateGroupedPortList().
DetectPort* DetectPortLookup (DetectPort * head, DetectPort * dp)
Used to see if the exact same portrange exists in the list.
Parameters
head Pointer to the DetectPort list head
dp DetectPort to search in the DetectPort list
Return values
returns a ptr to the match, or NULL if no match
Definition at line 136 of file detect-engine-port.c.
References DetectPortCmp(), DetectPort_::next, and PORT_EQ.
DetectPort* DetectPortLookupGroup (DetectPort * dp, uint16_t port)
Function that find the group matching address in a group head.
Parameters
dp Pointer to DetectPort group where we try to find the group
port port to search/lookup
Return values
Pointer to the DetectPort group of our port if it matched
NULL if port is not in the list
Definition at line 867 of file detect-engine-port.c.
References DetectPortMatch(), and DetectPort_::next.
Referenced by IPOnlyMatchPacket(), SigMatchSignatures(), and SigMatchSignaturesGetSgh().
int DetectPortParse (const DetectEngineCtx * de_ctx, DetectPort ** head, char * str)
Function for parsing port strings.
Parameters
head Pointer to the head of the DetectPort group list
str Pointer to the port string
Return values
0 on success
-1 on error
Definition at line 1402 of file detect-engine-port.c.
References DetectPortCleanupList(), DetectPortParseMergeNotPorts(), and SCLogDebug.
Referenced by AppLayerProtoDetectPPRegister().
void DetectPortPrint (DetectPort * dp)
Helper function that print the DetectPort info.
Return values
none
Definition at line 843 of file detect-engine-port.c.
References DetectPort_::flags, DetectPort_::port, DetectPort_::port2, PORT_FLAG_ANY, and SCLogDebug.
Referenced by CreateGroupedPortList(), DetectPortInsert(), DetectPortParseMergeNotPorts(), DetectPortPrintList(), and SigAddressPrepareStage5().
void DetectPortPrintList (DetectPort * head)
Helper function used to print the list of ports present in this DetectPort list.
Parameters
head Pointer to the DetectPort list head
Definition at line 156 of file detect-engine-port.c.
References DetectPortPrint(), DetectPort_::next, and SCLogDebug.
Referenced by CreateGroupedPortList().
void DetectPortPrintMemory (void)
Prints Memory statistics of the counters at detect-engine-port.[c,h].
Definition at line 116 of file detect-engine-port.c.
References SCLogDebug.
int DetectPortSpHashAdd (DetectEngineCtx * de_ctx, DetectPort * p)
Function that add a source DetectPort into the hashtable.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
p Pointer to the DetectPort to add
Definition at line 1695 of file detect-engine-port.c.
References HashListTableAdd(), and DetectEngineCtx_::sport_hash_table.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DetectPortSpHashFree (DetectEngineCtx * de_ctx)
Function that free the HashListTable of source DetectPort.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
Definition at line 1668 of file detect-engine-port.c.
References HashListTableFree(), and DetectEngineCtx_::sport_hash_table.
Referenced by DetectEngineCtxFree(), DetectPortSpHashReset(), and SigAddressPrepareStage3().
int DetectPortSpHashInit (DetectEngineCtx * de_ctx)
Function that initialize the HashListTable of source DetectPort.
Parameters
de_ctx Pointer to the current DetectionEngineContext
Return values
0 HashListTable initialization succes
-1 Error
Definition at line 1651 of file detect-engine-port.c.
References DetectPortCompareFunc(), DetectPortFreeFunc(), DetectPortHashFunc(), HashListTableInit(), PORT_HASH_SIZE, and DetectEngineCtx_::sport_hash_table.
Referenced by DetectPortSpHashReset().
DetectPort* DetectPortSpHashLookup (DetectEngineCtx * de_ctx, DetectPort * p)
Function that search a source DetectPort in the hashtable.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
p Pointer to the DetectPort to search
Definition at line 1706 of file detect-engine-port.c.
References HashListTableLookup(), and DetectEngineCtx_::sport_hash_table.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DetectPortSpHashReset (DetectEngineCtx * de_ctx)
Function that reset the HashListTable of source DetectPort (Free and Initialize it)
Parameters
de_ctx Pointer to the current DetectionEngineCtx
Definition at line 1683 of file detect-engine-port.c.
References DetectPortSpHashFree(), and DetectPortSpHashInit().
Referenced by BuildDestinationAddressHeadsWithBothPorts().
int DetectPortTestConfVars (void)
Definition at line 1336 of file detect-engine-port.c.
References ConfGetNode(), DetectPortCleanupList(), DetectPortInit(), DetectPortIsCompletePortSpace(), ConfNode_::name, next, SC_ERR_INVALID_YAML_CONF_ENTRY, SCLogDebug, SCLogError, TAILQ_FOREACH, and ConfNode_::val.
void DetectPortTests (void)
Definition at line 2800 of file detect-engine-port.c.
Referenced by RunUnittests().