suricata: src/detect-ssl-state.c File Reference
detect-ssl-state.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "detect-ssl-state.h"
#include "stream-tcp.h"
#include "app-layer-ssl.h"
Macros
#define PARSE_REGEX1 "^\\s*([_a-zA-Z0-9]+)(.*)$"
#define PARSE_REGEX2 "^(?:\\s*[|]\\s*([_a-zA-Z0-9]+))(.*)$"
#define MAX_SUBSTRINGS 30
Functions
int DetectSslStateMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Flow *f, uint8_t flags, void *alstate, Signature *s, SigMatch *m)
App layer match function ssl_state keyword.
int DetectSslStateSetup (DetectEngineCtx *, Signature *, char *)
void DetectSslStateRegisterTests (void)
void DetectSslStateFree (void *ptr)
Free memory associated with DetectSslStateData.
void DetectSslStateRegister (void)
Registers the keyword handlers for the "ssl_state" keyword.
DetectSslStateData * DetectSslStateParse (char *arg)
Parse the arg supplied with ssl_state and return it in a DetectSslStateData instance.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements support for ssl_state keyword.
Definition in file detect-ssl-state.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectSslStateParse().
#define PARSE_REGEX1 "^\\s*([_a-zA-Z0-9]+)(.*)$"
Definition at line 54 of file detect-ssl-state.c.
Referenced by DetectSslStateRegister().
#define PARSE_REGEX2 "^(?:\\s*[|]\\s*([_a-zA-Z0-9]+))(.*)$"
Definition at line 58 of file detect-ssl-state.c.
Referenced by DetectSslStateRegister().
Function Documentation
void DetectSslStateFree (void * ptr)
Free memory associated with DetectSslStateData.
Parameters
ptr pointer to the data to be freed.
Definition at line 330 of file detect-ssl-state.c.
References SCFree.
Referenced by DetectSslStateParse(), DetectSslStateRegister(), and DetectSslStateSetup().
int DetectSslStateMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Flow * f, uint8_t flags, void * alstate, Signature * s, SigMatch * m)
App layer match function ssl_state keyword.
Parameters
tv Pointer to threadvars.
det_ctx Pointer to the thread's detection context.
f Pointer to the flow.
flags Flags.
state App layer state.
s Sig we are currently inspecting.
m SigMatch we are currently inspecting.
Return values
1 Match.
0 No match.
Definition at line 133 of file detect-ssl-state.c.
References SigMatch_::ctx, DetectSslStateData_::flags, SCLogDebug, SSL_AL_FLAG_STATE_CLIENT_HELLO, SSL_AL_FLAG_STATE_CLIENT_KEYX, SSL_AL_FLAG_STATE_SERVER_HELLO, and SSL_AL_FLAG_STATE_SERVER_KEYX.
Referenced by DetectSslStateRegister().
DetectSslStateData* DetectSslStateParse (char * arg)
Parse the arg supplied with ssl_state and return it in a DetectSslStateData instance.
Parameters
arg Pointer to the string to be parsed.
Return values
ssd Pointer to DetectSslStateData on succese.
NULL On failure.
Definition at line 179 of file detect-ssl-state.c.
References DETECT_SSL_STATE_CLIENT_HELLO, DETECT_SSL_STATE_CLIENT_KEYX, DETECT_SSL_STATE_SERVER_HELLO, DETECT_SSL_STATE_SERVER_KEYX, DETECT_SSL_STATE_UNKNOWN, DetectSslStateFree(), DetectSslStateData_::flags, flags, MAX_SUBSTRINGS, SC_ERR_INVALID_SIGNATURE, SC_ERR_PCRE_GET_SUBSTRING, SCLogError, and SCMalloc.
Referenced by DetectSslStateSetup().
void DetectSslStateRegister (void)
Registers the keyword handlers for the "ssl_state" keyword.
Definition at line 71 of file detect-ssl-state.c.
References SigTableElmt_::alproto, ALPROTO_TLS, SigTableElmt_::AppLayerMatch, DETECT_AL_SSL_STATE, DetectSslStateFree(), DetectSslStateMatch(), DetectSslStateRegisterTests(), DetectSslStateSetup(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX1, PARSE_REGEX2, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void DetectSslStateRegisterTests (void)
Definition at line 900 of file detect-ssl-state.c.
Referenced by DetectSslStateRegister().
int DetectSslStateSetup (DetectEngineCtx * de_ctx, Signature * s, char * arg)
Definition at line 289 of file detect-ssl-state.c.
References Signature_::alproto, ALPROTO_TLS, ALPROTO_UNKNOWN, SigMatch_::ctx, DETECT_AL_SSL_STATE, DETECT_SM_LIST_AMATCH, DetectSslStateFree(), DetectSslStateParse(), SC_ERR_CONFLICTING_RULE_KEYWORDS, SCFree, SCLogError, SigMatchAlloc(), SigMatchAppendSMToList(), and SigMatch_::type.
Referenced by DetectSslStateRegister().