suricata: src/detect-http-raw-header.h File Reference
detect-http-raw-header.h File Reference
Functions
void DetectHttpRawHeaderRegister (void)
Registers the keyword handlers for the "http_raw_header" keyword.
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file detect-http-raw-header.h.
Function Documentation
void DetectHttpRawHeaderRegister (void)
Registers the keyword handlers for the "http_raw_header" keyword.
Definition at line 69 of file detect-http-raw-header.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, DETECT_AL_HTTP_RAW_HEADER, DetectHttpRawHeaderFree(), DetectHttpRawHeaderRegisterTests(), DetectHttpRawHeaderSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, and sigmatch_table.