suricata: src/detect-dce-stub-data.h File Reference
detect-dce-stub-data.h File Reference
Functions
void DetectDceStubDataRegister (void)
Registers the keyword handlers for the "dce_stub_data" keyword.
void DetectDceStubDataRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-dce-stub-data.h.
Function Documentation
void DetectDceStubDataRegister (void)
Registers the keyword handlers for the "dce_stub_data" keyword.
Definition at line 59 of file detect-dce-stub-data.c.
References SigTableElmt_::alproto, ALPROTO_DCERPC, SigTableElmt_::AppLayerMatch, DETECT_DCE_STUB_DATA, DetectDceStubDataRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void DetectDceStubDataRegisterTests (void)
Definition at line 1837 of file detect-dce-stub-data.c.
Referenced by DetectDceStubDataRegister().