suricata: src/detect-id.c File Reference
detect-id.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-id.h"
#include "flow.h"
#include "flow-var.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
Macros
#define PARSE_REGEX "^\\s*([0-9]{1,5}|\"[0-9]{1,5}\")\\s*$"
Regex for parsing "id" option, matching number or "number".
#define MAX_SUBSTRINGS 30
Functions
int DetectIdMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match the specified id on a packet.
void DetectIdRegisterTests (void)
this function registers unit tests for DetectId
void DetectIdFree (void *ptr)
this function will free memory associated with DetectIdData
void DetectIdRegister (void)
Registration function for keyword: id.
DetectIdData * DetectIdParse (char *idstr)
This function is used to parse IPV4 ip_id passed via keyword: "id".
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements the id keyword
Definition in file detect-id.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectIdParse().
#define PARSE_REGEX "^\\s*([0-9]{1,5}|\"[0-9]{1,5}\")\\s*$"
Regex for parsing "id" option, matching number or "number".
Definition at line 46 of file detect-id.c.
Referenced by DetectIdRegister().
Function Documentation
void DetectIdFree (void * ptr)
this function will free memory associated with DetectIdData
Parameters
id_d pointer to DetectIdData
Definition at line 247 of file detect-id.c.
References SCFree.
Referenced by DetectIdParse(), and DetectIdRegister().
int DetectIdMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match the specified id on a packet.
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectIdData
Return values
0 no match
1 match
To match a ipv4 packet with a "id" rule
Definition at line 105 of file detect-id.c.
References DetectIdData_::id, IPV4_GET_IPID, PKT_IS_IPV4, PKT_IS_PSEUDOPKT, and SCLogDebug.
Referenced by DetectIdRegister().
DetectIdData* DetectIdParse (char * idstr)
This function is used to parse IPV4 ip_id passed via keyword: "id".
Parameters
idstr Pointer to the user provided id option
Return values
id_d pointer to DetectIdData on success
NULL on failure
Definition at line 134 of file detect-id.c.
References DETECT_IPID_MAX, DETECT_IPID_MIN, DetectIdFree(), DetectIdData_::id, MAX_SUBSTRINGS, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCLogDebug, SCLogError, SCMalloc, and unlikely.
void DetectIdRegister (void)
Registration function for keyword: id.
Definition at line 60 of file detect-id.c.
References SigTableElmt_::desc, DETECT_ID, DetectIdFree(), DetectIdMatch(), DetectIdRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectIdRegisterTests (void)
this function registers unit tests for DetectId
Definition at line 374 of file detect-id.c.
Referenced by DetectIdRegister().