suricata: src/detect-content.c File Reference
detect-content.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "detect-content.h"
#include "detect-uricontent.h"
#include "detect-engine-mpm.h"
#include "detect-engine.h"
#include "detect-engine-state.h"
#include "detect-parse.h"
#include "util-mpm.h"
#include "flow.h"
#include "flow-util.h"
#include "flow-var.h"
#include "detect-flow.h"
#include "app-layer.h"
#include "util-unittest.h"
#include "util-print.h"
#include "util-debug.h"
#include "util-spm-bm.h"
#include "threads.h"
#include "util-unittest-helper.h"
#include "pkt-var.h"
#include "host.h"
#include "util-profiling.h"
Functions
int DetectContentMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, SigMatch *)
int DetectContentSetup (DetectEngineCtx *de_ctx, Signature *s, char *contentstr)
Function to setup a content pattern.
void DetectContentRegisterTests (void)
this function registers unit tests for DetectContent
void DetectContentRegister (void)
uint32_t DetectContentMaxId (DetectEngineCtx *de_ctx)
int DetectContentDataParse (const char *keyword, const char *contentstr, uint8_t **pstr, uint16_t *plen, uint32_t *flags)
Parse a content string, ie "abc|DE|fgh".
DetectContentData * DetectContentParse (char *contentstr)
DetectContentParse .
DetectContentData * DetectContentParseEncloseQuotes (char *contentstr)
void DetectContentPrint (DetectContentData *cd)
Helper function to print a DetectContentData.
void DetectContentPrintAll (SigMatch *sm)
Print list of DETECT_CONTENT SigMatch's allocated in a SigMatch list, from the current sm to the end.
void DetectContentFree (void *ptr)
this function will SCFree memory associated with DetectContentData
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Simple content match part of the detection engine.
Definition in file detect-content.c.
Function Documentation
int DetectContentDataParse (const char * keyword, const char * contentstr, uint8_t ** pstr, uint16_t * plen, uint32_t * flags)
Parse a content string, ie "abc|DE|fgh".
Parameters
content_str null terminated string containing the content
result result pointer to pass the fully parsed byte array
result_len size of the resulted data
flags flags to be set by this parsing function
Return values
-1 error
0 ok
Definition at line 85 of file detect-content.c.
References DETECT_CONTENT_NEGATED, len, SC_ERR_INVALID_SIGNATURE, SCFree, SCLogDebug, SCLogError, SCStrdup, and str.
Referenced by DetectContentParse().
void DetectContentFree (void * ptr)
this function will SCFree memory associated with DetectContentData
Parameters
cd pointer to DetectCotentData
Definition at line 416 of file detect-content.c.
References DetectContentData_::bm_ctx, BoyerMooreCtxDeInit(), SCEnter, SCFree, and SCReturn.
Referenced by DetectContentRegister(), and DetectContentSetup().
int DetectContentMatch (ThreadVars * , DetectEngineThreadCtx * , Packet * , Signature * , SigMatch *)
uint32_t DetectContentMaxId (DetectEngineCtx * de_ctx)
Definition at line 69 of file detect-content.c.
References DetectEngineCtx_::mpm_pattern_id_store, and MpmPatternIdStoreGetMaxId().
Referenced by SigGroupHeadLoadContent(), SigGroupHeadLoadStreamContent(), SigGroupHeadPrintContent(), and SigGroupHeadPrintContentCnt().
DetectContentData* DetectContentParse (char * contentstr)
DetectContentParse .
Definition at line 226 of file detect-content.c.
References DetectContentData_::bm_ctx, BoyerMooreCtxInit(), DetectContentData_::content, DetectContentData_::content_len, DetectContentData_::depth, DETECT_CONTENT_NEGATED, DetectContentDataParse(), DetectContentData_::distance, flags, DetectContentData_::flags, len, DetectContentData_::offset, SCFree, SCMalloc, unlikely, and DetectContentData_::within.
Referenced by DetectContentParseEncloseQuotes(), and DetectContentSetup().
DetectContentData* DetectContentParseEncloseQuotes (char * contentstr)
Definition at line 266 of file detect-content.c.
References DetectContentParse(), and str.
void DetectContentPrint (DetectContentData * cd)
Helper function to print a DetectContentData.
Definition at line 281 of file detect-content.c.
References DetectContentData_::content, DetectContentData_::content_len, DetectContentData_::depth, DETECT_CONTENT_NEGATED, DETECT_CONTENT_RELATIVE_NEXT, DetectContentData_::distance, DetectContentData_::flags, DetectContentData_::id, DetectContentData_::offset, DetectContentData_::replace, DetectContentData_::replace_len, SCFree, SCLogDebug, SCMalloc, and DetectContentData_::within.
Referenced by DetectContentPrintAll(), and DetectContentSetup().
void DetectContentPrintAll (SigMatch * sm)
Print list of DETECT_CONTENT SigMatch's allocated in a SigMatch list, from the current sm to the end.
Parameters
sm pointer to the current SigMatch to start printing from
Definition at line 342 of file detect-content.c.
References SigMatch_::ctx, DETECT_CONTENT, DetectContentPrint(), SigMatch_::next, SCLogDebug, SCLogDebugEnabled(), and SigMatch_::type.
void DetectContentRegister (void)
Definition at line 55 of file detect-content.c.
References SigTableElmt_::desc, DETECT_CONTENT, DetectContentFree(), DetectContentRegisterTests(), DetectContentSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectContentRegisterTests (void)
this function registers unit tests for DetectContent
Definition at line 2719 of file detect-content.c.
Referenced by DetectContentRegister().
int DetectContentSetup (DetectEngineCtx * de_ctx, Signature * s, char * contentstr)
Function to setup a content pattern.
Parameters
de_ctx pointer to the current detection_engine
s pointer to the current Signature
m pointer to the last parsed SigMatch
contentstr pointer to the current keyword content string
Return values
-1 if error
0 if all was ok
Definition at line 374 of file detect-content.c.
References Signature_::alproto, ALPROTO_HTTP, AppLayerHtpEnableResponseBodyCallback(), SigMatch_::ctx, DETECT_CONTENT, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_NOTSET, DETECT_SM_LIST_PMATCH, DetectContentFree(), DetectContentParse(), DetectContentPrint(), Signature_::flags, Signature_::list, SIG_FLAG_APPLAYER, SigMatchAlloc(), SigMatchAppendSMToList(), and SigMatch_::type.
Referenced by DetectContentRegister().