suricata: src/detect-flowbits.h File Reference
detect-flowbits.h File Reference
Data Structures
struct DetectFlowbitsData_
Macros
#define DETECT_FLOWBITS_CMD_SET 0
#define DETECT_FLOWBITS_CMD_TOGGLE 1
#define DETECT_FLOWBITS_CMD_UNSET 2
#define DETECT_FLOWBITS_CMD_ISNOTSET 3
#define DETECT_FLOWBITS_CMD_ISSET 4
#define DETECT_FLOWBITS_CMD_NOALERT 5
#define DETECT_FLOWBITS_CMD_MAX 6
Typedefs
typedef struct DetectFlowbitsData_ DetectFlowbitsData
Functions
void DetectFlowbitsRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Definition in file detect-flowbits.h.
Macro Definition Documentation
#define DETECT_FLOWBITS_CMD_ISNOTSET 3
Definition at line 31 of file detect-flowbits.h.
Referenced by DetectFlowbitMatch().
#define DETECT_FLOWBITS_CMD_ISSET 4
Definition at line 32 of file detect-flowbits.h.
Referenced by DetectFlowbitMatch().
#define DETECT_FLOWBITS_CMD_MAX 6
Definition at line 34 of file detect-flowbits.h.
#define DETECT_FLOWBITS_CMD_NOALERT 5
Definition at line 33 of file detect-flowbits.h.
#define DETECT_FLOWBITS_CMD_SET 0
Definition at line 28 of file detect-flowbits.h.
Referenced by DetectFlowbitMatch(), and SignatureIsIPOnly().
#define DETECT_FLOWBITS_CMD_TOGGLE 1
Definition at line 29 of file detect-flowbits.h.
Referenced by DetectFlowbitMatch().
#define DETECT_FLOWBITS_CMD_UNSET 2
Definition at line 30 of file detect-flowbits.h.
Referenced by DetectFlowbitMatch().
Typedef Documentation
typedef struct DetectFlowbitsData_ DetectFlowbitsData
Function Documentation
void DetectFlowbitsRegister (void)
Definition at line 58 of file detect-flowbits.c.
References SigTableElmt_::desc, DETECT_FLOWBITS, DetectFlowbitFree(), DetectFlowbitMatch(), SigTableElmt_::flags, FlowBitsRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().