suricata: src/detect-flags.c File Reference
detect-flags.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "flow-var.h"
#include "decode-events.h"
#include "detect-flags.h"
#include "util-unittest.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^\\s*(?:([\\+\\*!]))?\\s*([SAPRFU120CE\\+\\*!]+)(?:\\s*,\\s*([SAPRFU12CE]+))?\\s*$"
#define MODIFIER_NOT 1
#define MODIFIER_PLUS 2
#define MODIFIER_ANY 3
#define MAX_SUBSTRINGS 30
Functions
void DetectFlagsRegister (void)
Registration function for flags: keyword.
void FlagsRegisterTests (void)
this function registers unit tests for Flags
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Implements the flags keyword
Definition in file detect-flags.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
#define MODIFIER_ANY 3
Definition at line 54 of file detect-flags.c.
#define MODIFIER_NOT 1
Flags args[0] *(3) +(2) !(1)
Definition at line 52 of file detect-flags.c.
#define MODIFIER_PLUS 2
Definition at line 53 of file detect-flags.c.
#define PARSE_REGEX "^\\s*(?:([\\+\\*!]))?\\s*([SAPRFU120CE\\+\\*!]+)(?:\\s*,\\s*([SAPRFU12CE]+))?\\s*$"
Regex (by Brian Rectanus) flags: [!+*](SAPRFU120)[,SAPRFU12]
Definition at line 45 of file detect-flags.c.
Referenced by DetectFlagsRegister().
Function Documentation
void DetectFlagsRegister (void)
Registration function for flags: keyword.
Registration function for flags: keyword
Definition at line 67 of file detect-flags.c.
References DETECT_FLAGS, FlagsRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void FlagsRegisterTests (void)
this function registers unit tests for Flags
This function registers unit tests for Flags
Definition at line 1320 of file detect-flags.c.
Referenced by DetectFlagsRegister().