suricata: src/detect-ssh-software-version.h File Reference
detect-ssh-software-version.h File Reference
Data Structures
struct DetectSshSoftwareVersionData_
Typedefs
typedef struct
DetectSshSoftwareVersionData_ DetectSshSoftwareVersionData
Functions
void DetectSshSoftwareVersionRegister (void)
Registration function for keyword: ssh.softwareversion.
void DetectSshSoftwareVersionRegisterTests (void)
this function registers unit tests for DetectSshSoftwareVersion
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file detect-ssh-software-version.h.
Typedef Documentation
typedef struct DetectSshSoftwareVersionData_ DetectSshSoftwareVersionData
Function Documentation
void DetectSshSoftwareVersionRegister (void)
Registration function for keyword: ssh.softwareversion.
Definition at line 78 of file detect-ssh-software-version.c.
References SigTableElmt_::alproto, ALPROTO_SSH, SigTableElmt_::AppLayerMatch, DETECT_AL_SSH_SOFTWAREVERSION, DetectSshSoftwareVersionFree(), DetectSshSoftwareVersionMatch(), DetectSshSoftwareVersionRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void DetectSshSoftwareVersionRegisterTests (void)
this function registers unit tests for DetectSshSoftwareVersion
Definition at line 662 of file detect-ssh-software-version.c.
Referenced by DetectSshSoftwareVersionRegister().