suricata: src/detect-stream_size.c File Reference
detect-stream_size.c File Reference
#include "suricata-common.h"
#include "stream-tcp.h"
#include "util-unittest.h"
#include "detect.h"
#include "detect-parse.h"
#include "flow.h"
#include "detect-stream_size.h"
#include "stream-tcp-private.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^\\s*([A-z_]+)\\s*,\\s*([<=>!]+)\\s*,\\s*([0-9]+)\\s*$"
Regex for parsing our flow options.
#define MAX_SUBSTRINGS 30
Functions
int DetectStreamSizeMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match Stream size rule option on a packet with those passed via stream_size:
void DetectStreamSizeFree (void *ptr)
this function will free memory associated with DetectStreamSizeData
void DetectStreamSizeRegisterTests (void)
this function registers unit tests for DetectStreamSize
void DetectStreamSizeRegister (void)
Registration function for stream_size: keyword.
DetectStreamSizeData * DetectStreamSizeParse (char *streamstr)
This function is used to parse stream options passed via stream_size: keyword.
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Stream size for the engine.
Definition in file detect-stream_size.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectStreamSizeParse().
#define PARSE_REGEX "^\\s*([A-z_]+)\\s*,\\s*([<=>!]+)\\s*,\\s*([0-9]+)\\s*$"
Regex for parsing our flow options.
Definition at line 41 of file detect-stream_size.c.
Referenced by DetectStreamSizeRegister().
Function Documentation
void DetectStreamSizeFree (void * ptr)
this function will free memory associated with DetectStreamSizeData
Parameters
ptr pointer to DetectStreamSizeData
Definition at line 340 of file detect-stream_size.c.
References SCFree.
Referenced by DetectStreamSizeParse(), and DetectStreamSizeRegister().
int DetectStreamSizeMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match Stream size rule option on a packet with those passed via stream_size:
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectStreamSizeData
Return values
0 no match
1 match
Definition at line 144 of file detect-stream_size.c.
References TcpSession_::client, DetectStreamSizeData_::flags, Packet_::flow, TcpStream_::isn, DetectStreamSizeData_::mode, TcpStream_::next_seq, PKT_IS_TCP, Flow_::protoctx, TcpSession_::server, DetectStreamSizeData_::ssize, STREAM_SIZE_BOTH, STREAM_SIZE_CLIENT, STREAM_SIZE_EITHER, and STREAM_SIZE_SERVER.
Referenced by DetectStreamSizeRegister().
DetectStreamSizeData* DetectStreamSizeParse (char * streamstr)
This function is used to parse stream options passed via stream_size: keyword.
Parameters
streamstr Pointer to the user provided stream_size options
Return values
sd pointer to DetectStreamSizeData on success
NULL on failure
Definition at line 198 of file detect-stream_size.c.
References DETECTSSIZE_EQ, DETECTSSIZE_GEQ, DETECTSSIZE_GT, DETECTSSIZE_LEQ, DETECTSSIZE_LT, DETECTSSIZE_NEQ, DetectStreamSizeFree(), DetectStreamSizeData_::flags, MAX_SUBSTRINGS, DetectStreamSizeData_::mode, SC_ERR_INVALID_OPERATOR, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogError, SCMalloc, DetectStreamSizeData_::ssize, STREAM_SIZE_BOTH, STREAM_SIZE_CLIENT, STREAM_SIZE_EITHER, STREAM_SIZE_SERVER, and unlikely.
void DetectStreamSizeRegister (void)
Registration function for stream_size: keyword.
Definition at line 56 of file detect-stream_size.c.
References SigTableElmt_::desc, DETECT_STREAM_SIZE, DetectStreamSizeFree(), DetectStreamSizeMatch(), DetectStreamSizeRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCFree, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectStreamSizeRegisterTests (void)
this function registers unit tests for DetectStreamSize
Definition at line 523 of file detect-stream_size.c.
Referenced by DetectStreamSizeRegister().