suricata: src/detect-http-ua.c File Reference
detect-http-ua.c File Reference
HTTP layer support
#include "suricata-common.h"
#include "threads.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "detect-content.h"
#include "detect-pcre.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-spm.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "stream-tcp.h"
#include "detect-http-ua.h"
Functions
int DetectHttpUASetup (DetectEngineCtx *de_ctx, Signature *s, char *arg)
The setup function for the http_user_agent keyword for a signature.
void DetectHttpUARegisterTests (void)
void DetectHttpUAFree (void *ptr)
The function to free the http_user_agent data.
void DetectHttpUARegister (void)
Registers the keyword handlers for the "http_user_agent" keyword.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements support for the http_user_agent keyword.
Definition in file detect-http-ua.c.
Function Documentation
void DetectHttpUAFree (void * ptr)
The function to free the http_user_agent data.
Parameters
ptr Pointer to the http_user_agent.
Definition at line 113 of file detect-http-ua.c.
References DetectContentData_::bm_ctx, BoyerMooreCtxDeInit(), DetectContentData_::content, and SCFree.
Referenced by DetectHttpUARegister().
void DetectHttpUARegister (void)
Registers the keyword handlers for the "http_user_agent" keyword.
Definition at line 68 of file detect-http-ua.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, SigTableElmt_::desc, DETECT_AL_HTTP_USER_AGENT, DetectHttpUAFree(), DetectHttpUARegisterTests(), DetectHttpUASetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectHttpUARegisterTests (void)
Definition at line 2071 of file detect-http-ua.c.
Referenced by DetectHttpUARegister().
int DetectHttpUASetup (DetectEngineCtx * de_ctx, Signature * s, char * arg)
The setup function for the http_user_agent keyword for a signature.
Parameters
de_ctx Pointer to the detection engine context.
s Pointer to the signature for the current Signature being parsed from the rules.
m Pointer to the head of the SigMatch for the current rule being parsed.
arg Pointer to the string holding the keyword value.
Return values
0 On success
-1 On failure
Definition at line 99 of file detect-http-ua.c.
References ALPROTO_HTTP, DETECT_AL_HTTP_USER_AGENT, DETECT_SM_LIST_HUADMATCH, and DetectEngineContentModifierBufferSetup().
Referenced by DetectHttpUARegister().