suricata: src/detect-engine-hmd.h File Reference
detect-engine-hmd.h File Reference
#include "app-layer-htp.h"
Functions
int DetectEngineInspectHttpMethod (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *tx, uint64_t tx_id)
Do the http_method content inspection for a signature.
int DetectEngineRunHttpMethodMpm (DetectEngineThreadCtx *det_ctx, Flow *f, HtpState *htp_state, uint8_t flags, void *tx, uint64_t idx)
void DetectEngineHttpMethodRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-engine-hmd.h.
Function Documentation
void DetectEngineHttpMethodRegisterTests (void)
Definition at line 1783 of file detect-engine-hmd.c.
Referenced by RunUnittests().
int DetectEngineInspectHttpMethod (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * txv, uint64_t tx_id)
Do the http_method content inspection for a signature.
Parameters
de_ctx Detection engine context.
det_ctx Detection engine thread context.
s Signature to inspect.
f Flow.
flags App layer flags.
state App layer state.
Return values
0 No match.
1 Match.
Definition at line 90 of file detect-engine-hmd.c.
References ALPROTO_HTTP, AppLayerParserGetStateProgress(), bstr_len, bstr_ptr, DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HMD, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DETECT_SM_LIST_HMDMATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, HTP_REQUEST_LINE, DetectEngineThreadCtx_::inspection_recursion_counter, htp_tx_t::request_method, and Signature_::sm_lists.
Referenced by DetectEngineRegisterAppInspectionEngines().
int DetectEngineRunHttpMethodMpm (DetectEngineThreadCtx * det_ctx, Flow * f, HtpState * htp_state, uint8_t flags, void * tx, uint64_t idx)
Definition at line 60 of file detect-engine-hmd.c.
References bstr_len, bstr_ptr, HttpMethodPatternSearch(), and htp_tx_t::request_method.