suricata: src/detect-engine-uri.c File Reference
detect-engine-uri.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-parse.h"
#include "detect-engine-state.h"
#include "detect-engine-content-inspection.h"
#include "flow-util.h"
#include "util-debug.h"
#include "util-print.h"
#include "flow.h"
#include "stream-tcp.h"
#include "app-layer-parser.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer.h"
#include "app-layer-htp.h"
#include "app-layer-protos.h"
Functions
int DetectEngineInspectPacketUris (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Flow *f, uint8_t flags, void *alstate, void *txv, uint64_t tx_id)
Do the content inspection & validation for a signature.
void UriRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Based on detect-engine-uri.c
Definition in file detect-engine-uri.c.
Function Documentation
int DetectEngineInspectPacketUris (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Flow * f, uint8_t flags, void * alstate, void * txv, uint64_t tx_id)
Do the content inspection & validation for a signature.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
sm SigMatch to inspect
f Flow
flags app layer flags
state App layer state
Return values
0 no match.
1 match.
2 Sig can't match.
Definition at line 66 of file detect-engine-uri.c.
References ALPROTO_HTTP, AppLayerParserGetStateProgress(), bstr_len, bstr_ptr, DetectEngineThreadCtx_::buffer_offset, DETECT_ENGINE_CONTENT_INSPECTION_MODE_URI, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DETECT_SM_LIST_UMATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, HTP_REQUEST_LINE, htp_tx_get_user_data(), DetectEngineThreadCtx_::inspection_recursion_counter, PrintRawDataFp(), HtpTxUserData_::request_uri_normalized, and Signature_::sm_lists.
Referenced by DetectEngineRegisterAppInspectionEngines().
void UriRegisterTests (void)
Definition at line 4176 of file detect-engine-uri.c.
Referenced by RunUnittests().