suricata: src/detect-flow.c File Reference
detect-flow.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "flow.h"
#include "flow-var.h"
#include "detect-flow.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^\\s*([A-z_]+)\\s*(?:,\\s*([A-z_]+))?\\s*(?:,\\s*([A-z_]+))?\\s*$"
Regex for parsing our flow options.
#define MAX_SUBSTRINGS 30
Functions
int DetectFlowMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match flow flags set on a packet with those passed via flow:
void DetectFlowRegisterTests (void)
this function registers unit tests for DetectFlow
void DetectFlowFree (void *ptr)
this function will free memory associated with DetectFlowData
void DetectFlowRegister (void)
Registration function for flow: keyword.
DetectFlowData * DetectFlowParse (char *flowstr)
This function is used to parse flow options passed via flow: keyword.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
FLOW part of the detection engine.
Definition in file detect-flow.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectFlowParse().
#define PARSE_REGEX "^\\s*([A-z_]+)\\s*(?:,\\s*([A-z_]+))?\\s*(?:,\\s*([A-z_]+))?\\s*$"
Regex for parsing our flow options.
Definition at line 46 of file detect-flow.c.
Referenced by DetectFlowRegister().
Function Documentation
void DetectFlowFree (void * ptr)
this function will free memory associated with DetectFlowData
Parameters
fd pointer to DetectFlowData
Definition at line 356 of file detect-flow.c.
References SCFree.
Referenced by DetectFlowParse(), and DetectFlowRegister().
int DetectFlowMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match flow flags set on a packet with those passed via flow:
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectFlowData
Return values
0 no match
1 match
Definition at line 110 of file detect-flow.c.
References DETECT_ENGINE_THREAD_CTX_STREAM_CONTENT_MATCH, DETECT_FLOW_FLAG_ESTABLISHED, DETECT_FLOW_FLAG_NOSTREAM, DETECT_FLOW_FLAG_ONLYSTREAM, DETECT_FLOW_FLAG_STATELESS, DETECT_FLOW_FLAG_TOCLIENT, DETECT_FLOW_FLAG_TOSERVER, DetectFlowData_::flags, DetectEngineThreadCtx_::flags, FLOW_PKT_ESTABLISHED, FLOW_PKT_TOCLIENT, FLOW_PKT_TOSERVER, Packet_::flowflags, DetectFlowData_::match_cnt, SCEnter, SCLogDebug, and SCReturnInt.
Referenced by DetectFlowRegister().
DetectFlowData* DetectFlowParse (char * flowstr)
This function is used to parse flow options passed via flow: keyword.
Parameters
flowstr Pointer to the user provided flow options
Return values
fd pointer to DetectFlowData on success
NULL on failure
Definition at line 163 of file detect-flow.c.
References DETECT_FLOW_FLAG_ESTABLISHED, DETECT_FLOW_FLAG_NOSTREAM, DETECT_FLOW_FLAG_ONLYSTREAM, DETECT_FLOW_FLAG_STATELESS, DETECT_FLOW_FLAG_TOCLIENT, DETECT_FLOW_FLAG_TOSERVER, DetectFlowFree(), DetectFlowData_::flags, DetectFlowData_::match_cnt, MAX_SUBSTRINGS, SC_ERR_FLAGS_MODIFIER, SC_ERR_INVALID_VALUE, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCLogError, SCMalloc, and unlikely.
void DetectFlowRegister (void)
Registration function for flow: keyword.
Definition at line 59 of file detect-flow.c.
References SigTableElmt_::desc, DETECT_FLOW, DetectFlowFree(), DetectFlowMatch(), DetectFlowRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectFlowRegisterTests (void)
this function registers unit tests for DetectFlow
Definition at line 1087 of file detect-flow.c.
Referenced by DetectFlowRegister().