suricata: src/detect-tag.h File Reference
detect-tag.h File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "util-time.h"
Data Structures
struct DetectTagData_
struct DetectTagDataEntry_
Macros
#define DETECT_TAG_MATCH_LIMIT 10
#define DETECT_TAG_MAX_TAGS 50
#define DETECT_TAG_MAX_PKTS 256
#define TAG_ENTRY_FLAG_DIR_SRC 0x01
#define TAG_ENTRY_FLAG_DIR_DST 0x02
#define TAG_ENTRY_FLAG_SKIPPED_FIRST 0x04
Typedefs
typedef struct DetectTagData_ DetectTagData
typedef struct DetectTagDataEntry_ DetectTagDataEntry
Enumerations
enum { DETECT_TAG_TYPE_SESSION, DETECT_TAG_TYPE_HOST, DETECT_TAG_TYPE_MAX }
enum { DETECT_TAG_DIR_SRC, DETECT_TAG_DIR_DST, DETECT_TAG_DIR_MAX }
enum { DETECT_TAG_METRIC_PACKET, DETECT_TAG_METRIC_SECONDS, DETECT_TAG_METRIC_BYTES, DETECT_TAG_METRIC_MAX }
Functions
void DetectTagRegister (void)
Registration function for keyword tag.
void DetectTagDataFree (void *ptr)
this function will free memory associated with DetectTagData
void DetectTagDataListFree (void *ptr)
this function will free all the entries of a list DetectTagDataEntry
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-tag.h.
Macro Definition Documentation
#define DETECT_TAG_MATCH_LIMIT 10
Definition at line 34 of file detect-tag.h.
Referenced by TagFlowAdd(), and TagHashAddTag().
#define DETECT_TAG_MAX_PKTS 256
Definition at line 42 of file detect-tag.h.
Referenced by DetectTagParse().
#define DETECT_TAG_MAX_TAGS 50
Definition at line 37 of file detect-tag.h.
Referenced by TagFlowAdd(), and TagHashAddTag().
#define TAG_ENTRY_FLAG_DIR_DST 0x02
Definition at line 96 of file detect-tag.h.
Referenced by DetectTagMatch(), and TagHashAddTag().
#define TAG_ENTRY_FLAG_DIR_SRC 0x01
Definition at line 95 of file detect-tag.h.
Referenced by DetectTagMatch(), and TagHashAddTag().
#define TAG_ENTRY_FLAG_SKIPPED_FIRST 0x04
Definition at line 97 of file detect-tag.h.
Referenced by TagHandlePacketHost().
Typedef Documentation
typedef struct DetectTagData_ DetectTagData
This will be the rule options/parameters
typedef struct DetectTagDataEntry_ DetectTagDataEntry
This is the installed data at the session/global or host table
Enumeration Type Documentation
anonymous enum
Enumerator
DETECT_TAG_TYPE_SESSION
DETECT_TAG_TYPE_HOST
DETECT_TAG_TYPE_MAX
Definition at line 45 of file detect-tag.h.
anonymous enum
Enumerator
DETECT_TAG_DIR_SRC
DETECT_TAG_DIR_DST
DETECT_TAG_DIR_MAX
Definition at line 51 of file detect-tag.h.
anonymous enum
Enumerator
DETECT_TAG_METRIC_PACKET
DETECT_TAG_METRIC_SECONDS
DETECT_TAG_METRIC_BYTES
DETECT_TAG_METRIC_MAX
Definition at line 57 of file detect-tag.h.
Function Documentation
void DetectTagDataFree (void * ptr)
this function will free memory associated with DetectTagData
Parameters
td pointer to DetectTagData
Definition at line 370 of file detect-tag.c.
References SCFree.
Referenced by DetectTagRegister().
void DetectTagDataListFree (void * ptr)
this function will free all the entries of a list DetectTagDataEntry
Parameters
td pointer to DetectTagDataEntryList
Definition at line 351 of file detect-tag.c.
References DetectTagDataEntry_::next, and SC_ATOMIC_SUB.
Referenced by TagInitCtx().
void DetectTagRegister (void)
Registration function for keyword tag.
Definition at line 68 of file detect-tag.c.
References DETECT_TAG, DetectTagDataFree(), DetectTagMatch(), DetectTagRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, and sigmatch_table.
Referenced by SigTableSetup().