suricata: src/detect-http-cookie.h File Reference
detect-http-cookie.h File Reference
Functions
void DetectHttpCookieRegister (void)
Registration function for keyword: http_cookie.
int DetectHttpCookieDoMatch (DetectEngineThreadCtx *, Signature *, SigMatch *, Flow *, uint8_t, void *)
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Definition in file detect-http-cookie.h.
Function Documentation
int DetectHttpCookieDoMatch (DetectEngineThreadCtx * , Signature * , SigMatch * , Flow * , uint8_t , void *)
void DetectHttpCookieRegister (void)
Registration function for keyword: http_cookie.
Definition at line 70 of file detect-http-cookie.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, SigTableElmt_::desc, DETECT_AL_HTTP_COOKIE, DetectHttpCookieFree(), DetectHttpCookieRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().