suricata: src/detect-threshold.c File Reference
detect-threshold.c File Reference
Thresholding
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "host.h"
#include "host-storage.h"
#include "detect.h"
#include "detect-parse.h"
#include "flow-var.h"
#include "decode-events.h"
#include "stream-tcp.h"
#include "detect-threshold.h"
#include "detect-engine-threshold.h"
#include "detect-engine-address.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-byte.h"
#include "util-debug.h"
Macros
#define MAX_SUBSTRINGS 30
#define PARSE_REGEX "^\\s*(track|type|count|seconds)\\s+(limit|both|threshold|by_dst|by_src|\\d+)\\s*,\\s*(track|type|count|seconds)\\s+(limit|both|threshold|by_dst|by_src|\\d+)\\s*,\\s*(track|type|count|seconds)\\s+(limit|both|threshold|by_dst|by_src|\\d+)\\s*,\\s*(track|type|count|seconds)\\s+(limit|both|threshold|by_dst|by_src|\\d+)\\s*"
void DetectThresholdRegister (void)
Registration function for threshold: keyword.
void ThresholdRegisterTests (void)
Detailed Description
Author
Breno Silva breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements the threshold keyword.
The feature depends on what is provided by detect-engine-threshold.c and util-threshold-config.c
Definition in file detect-threshold.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
#define PARSE_REGEX "^\\s*(track|type|count|seconds)\\s+(limit|both|threshold|by_dst|by_src|\\d+)\\s*,\\s*(track|type|count|seconds)\\s+(limit|both|threshold|by_dst|by_src|\\d+)\\s*,\\s*(track|type|count|seconds)\\s+(limit|both|threshold|by_dst|by_src|\\d+)\\s*,\\s*(track|type|count|seconds)\\s+(limit|both|threshold|by_dst|by_src|\\d+)\\s*"
Definition at line 63 of file detect-threshold.c.
Referenced by DetectThresholdRegister().
Function Documentation
void DetectThresholdRegister (void)
Registration function for threshold: keyword.
Registration function for threshold: keyword
Definition at line 76 of file detect-threshold.c.
References SigTableElmt_::desc, DETECT_THRESHOLD, SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, sigmatch_table, ThresholdRegisterTests(), and SigTableElmt_::url.
Referenced by SigTableSetup().
void ThresholdRegisterTests (void)
This function registers unit tests for Threshold
Definition at line 1500 of file detect-threshold.c.
Referenced by DetectThresholdRegister().