suricata: src/detect-content.h File Reference
detect-content.h File Reference
#include "util-spm-bm.h"
Data Structures
struct DetectContentData_
Macros
#define DETECT_CONTENT_NOCASE (1)
#define DETECT_CONTENT_DISTANCE (1 << 1)
#define DETECT_CONTENT_WITHIN (1 << 2)
#define DETECT_CONTENT_OFFSET (1 << 3)
#define DETECT_CONTENT_DEPTH (1 << 4)
#define DETECT_CONTENT_FAST_PATTERN (1 << 5)
#define DETECT_CONTENT_FAST_PATTERN_ONLY (1 << 6)
#define DETECT_CONTENT_FAST_PATTERN_CHOP (1 << 7)
#define DETECT_CONTENT_RAWBYTES (1 << 8)
#define DETECT_CONTENT_NEGATED (1 << 9)
#define DETECT_CONTENT_RELATIVE_NEXT (1 << 10)
#define DETECT_CONTENT_OFFSET_BE (1 << 11)
#define DETECT_CONTENT_DEPTH_BE (1 << 12)
#define DETECT_CONTENT_DISTANCE_BE (1 << 13)
#define DETECT_CONTENT_WITHIN_BE (1 << 14)
#define DETECT_CONTENT_REPLACE (1 << 15)
#define DETECT_CONTENT_NO_DOUBLE_INSPECTION_REQUIRED (1 << 16)
#define DETECT_CONTENT_IS_SINGLE(c)
Typedefs
typedef struct DetectContentData_ DetectContentData
Functions
void DetectContentRegister (void)
uint32_t DetectContentMaxId (DetectEngineCtx *)
DetectContentData * DetectContentParse (char *contentstr)
DetectContentParse .
int DetectContentDataParse (const char *keyword, const char *contentstr, uint8_t **pstr, uint16_t *plen, uint32_t *flags)
Parse a content string, ie "abc|DE|fgh".
DetectContentData * DetectContentParseEncloseQuotes (char *)
int DetectContentSetup (DetectEngineCtx *de_ctx, Signature *s, char *contentstr)
Function to setup a content pattern.
void DetectContentPrint (DetectContentData *)
Helper function to print a DetectContentData.
void DetectContentFree (void *)
this function will SCFree memory associated with DetectContentData
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-content.h.
Macro Definition Documentation
#define DETECT_CONTENT_DEPTH (1 << 4)
Definition at line 33 of file detect-content.h.
Referenced by DetectEngineContentInspection(), EngineAnalysisFP(), EngineAnalysisRules(), and SigValidate().
#define DETECT_CONTENT_DEPTH_BE (1 << 12)
Definition at line 47 of file detect-content.h.
Referenced by DetectEngineContentInspection().
#define DETECT_CONTENT_DISTANCE (1 << 1)
Definition at line 30 of file detect-content.h.
Referenced by DetectEngineContentInspection(), DetectEngineContentModifierBufferSetup(), and EngineAnalysisFP().
#define DETECT_CONTENT_DISTANCE_BE (1 << 13)
Definition at line 48 of file detect-content.h.
Referenced by DetectEngineContentInspection().
#define DETECT_CONTENT_FAST_PATTERN (1 << 5)
Definition at line 34 of file detect-content.h.
Referenced by EngineAnalysisFP(), RetrieveFPForSig(), and RetrieveFPForSigV2().
#define DETECT_CONTENT_FAST_PATTERN_CHOP (1 << 7)
Definition at line 36 of file detect-content.h.
Referenced by DetectSetFastPatternAndItsId(), and EngineAnalysisFP().
#define DETECT_CONTENT_FAST_PATTERN_ONLY (1 << 6)
Definition at line 35 of file detect-content.h.
Referenced by EngineAnalysisFP().
#define DETECT_CONTENT_IS_SINGLE (c)
Value:
(!(((c)->flags & DETECT_CONTENT_DISTANCE) || \
                                        ((c)->flags & DETECT_CONTENT_WITHIN) || \
                                        ((c)->flags & DETECT_CONTENT_RELATIVE_NEXT) || \
                                        ((c)->flags & DETECT_CONTENT_DEPTH) || \
                                        ((c)->flags & DETECT_CONTENT_OFFSET) ))
Definition at line 58 of file detect-content.h.
Referenced by DetectEngineContentInspection().
#define DETECT_CONTENT_NEGATED (1 << 9)
content is negated
Definition at line 40 of file detect-content.h.
Referenced by DetectContentDataParse(), DetectContentParse(), DetectContentPrint(), DetectEngineContentInspection(), DetectUricontentPrint(), EngineAnalysisFP(), RetrieveFPForSig(), and RetrieveFPForSigV2().
#define DETECT_CONTENT_NO_DOUBLE_INSPECTION_REQUIRED (1 << 16)
Definition at line 56 of file detect-content.h.
#define DETECT_CONTENT_NOCASE (1)
Definition at line 29 of file detect-content.h.
Referenced by ContentHashCompareFunc(), DetectEngineContentInspection(), DetectSetFastPatternAndItsId(), EngineAnalysisFP(), SigValidate(), and UricontentHashCompareFunc().
#define DETECT_CONTENT_OFFSET (1 << 3)
Definition at line 32 of file detect-content.h.
Referenced by EngineAnalysisFP(), EngineAnalysisRules(), and SigValidate().
#define DETECT_CONTENT_OFFSET_BE (1 << 11)
Definition at line 46 of file detect-content.h.
Referenced by DetectEngineContentInspection().
#define DETECT_CONTENT_RAWBYTES (1 << 8)
content applies to a "raw"/undecoded field if applicable
Definition at line 38 of file detect-content.h.
Referenced by DetectEngineContentModifierBufferSetup().
#define DETECT_CONTENT_RELATIVE_NEXT (1 << 10)
a relative match to this content is next, used in matching phase
Definition at line 43 of file detect-content.h.
Referenced by DetectByteExtractSetup(), DetectBytejumpSetup(), DetectBytetestSetup(), DetectContentPrint(), DetectEngineContentInspection(), DetectEngineContentModifierBufferSetup(), DetectIsdataatSetup(), and DetectUricontentPrint().
#define DETECT_CONTENT_REPLACE (1 << 15)
Definition at line 52 of file detect-content.h.
Referenced by DetectEngineContentInspection().
#define DETECT_CONTENT_WITHIN (1 << 2)
Definition at line 31 of file detect-content.h.
Referenced by DetectEngineContentInspection(), DetectEngineContentModifierBufferSetup(), and EngineAnalysisFP().
#define DETECT_CONTENT_WITHIN_BE (1 << 14)
Definition at line 49 of file detect-content.h.
Referenced by DetectEngineContentInspection().
Typedef Documentation
typedef struct DetectContentData_ DetectContentData
Function Documentation
int DetectContentDataParse (const char * keyword, const char * contentstr, uint8_t ** pstr, uint16_t * plen, uint32_t * flags)
Parse a content string, ie "abc|DE|fgh".
Parameters
content_str null terminated string containing the content
result result pointer to pass the fully parsed byte array
result_len size of the resulted data
flags flags to be set by this parsing function
Return values
-1 error
0 ok
Definition at line 85 of file detect-content.c.
References DETECT_CONTENT_NEGATED, len, SC_ERR_INVALID_SIGNATURE, SCFree, SCLogDebug, SCLogError, SCStrdup, and str.
Referenced by DetectContentParse().
void DetectContentFree (void * ptr)
this function will SCFree memory associated with DetectContentData
Parameters
cd pointer to DetectCotentData
Definition at line 416 of file detect-content.c.
References DetectContentData_::bm_ctx, BoyerMooreCtxDeInit(), SCEnter, SCFree, and SCReturn.
Referenced by DetectContentRegister(), and DetectContentSetup().
uint32_t DetectContentMaxId (DetectEngineCtx *)
Definition at line 69 of file detect-content.c.
References DetectEngineCtx_::mpm_pattern_id_store, and MpmPatternIdStoreGetMaxId().
Referenced by SigGroupHeadLoadContent(), SigGroupHeadLoadStreamContent(), SigGroupHeadPrintContent(), and SigGroupHeadPrintContentCnt().
DetectContentData* DetectContentParse (char * contentstr)
DetectContentParse .
Definition at line 226 of file detect-content.c.
References DetectContentData_::bm_ctx, BoyerMooreCtxInit(), DetectContentData_::content, DetectContentData_::content_len, DetectContentData_::depth, DETECT_CONTENT_NEGATED, DetectContentDataParse(), DetectContentData_::distance, flags, DetectContentData_::flags, len, DetectContentData_::offset, SCFree, SCMalloc, unlikely, and DetectContentData_::within.
Referenced by DetectContentParseEncloseQuotes(), and DetectContentSetup().
DetectContentData* DetectContentParseEncloseQuotes (char *)
Definition at line 266 of file detect-content.c.
References DetectContentParse(), and str.
void DetectContentPrint (DetectContentData *)
Helper function to print a DetectContentData.
Definition at line 281 of file detect-content.c.
References DetectContentData_::content, DetectContentData_::content_len, DetectContentData_::depth, DETECT_CONTENT_NEGATED, DETECT_CONTENT_RELATIVE_NEXT, DetectContentData_::distance, DetectContentData_::flags, DetectContentData_::id, DetectContentData_::offset, DetectContentData_::replace, DetectContentData_::replace_len, SCFree, SCLogDebug, SCMalloc, and DetectContentData_::within.
Referenced by DetectContentPrintAll(), and DetectContentSetup().
void DetectContentRegister (void)
Definition at line 55 of file detect-content.c.
References SigTableElmt_::desc, DETECT_CONTENT, DetectContentFree(), DetectContentRegisterTests(), DetectContentSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
int DetectContentSetup (DetectEngineCtx * de_ctx, Signature * s, char * contentstr)
Function to setup a content pattern.
Parameters
de_ctx pointer to the current detection_engine
s pointer to the current Signature
m pointer to the last parsed SigMatch
contentstr pointer to the current keyword content string
Return values
-1 if error
0 if all was ok
Definition at line 374 of file detect-content.c.
References Signature_::alproto, ALPROTO_HTTP, AppLayerHtpEnableResponseBodyCallback(), SigMatch_::ctx, DETECT_CONTENT, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_NOTSET, DETECT_SM_LIST_PMATCH, DetectContentFree(), DetectContentParse(), DetectContentPrint(), Signature_::flags, Signature_::list, SIG_FLAG_APPLAYER, SigMatchAlloc(), SigMatchAppendSMToList(), and SigMatch_::type.
Referenced by DetectContentRegister().