suricata: src/detect-xbits.h File Reference
detect-xbits.h File Reference
Data Structures
struct DetectXbitsData_
Macros
#define DETECT_XBITS_CMD_SET 0
#define DETECT_XBITS_CMD_TOGGLE 1
#define DETECT_XBITS_CMD_UNSET 2
#define DETECT_XBITS_CMD_ISNOTSET 3
#define DETECT_XBITS_CMD_ISSET 4
#define DETECT_XBITS_CMD_NOALERT 5
#define DETECT_XBITS_CMD_MAX 6
#define DETECT_XBITS_TRACK_IPSRC 0
#define DETECT_XBITS_TRACK_IPDST 1
#define DETECT_XBITS_TRACK_IPPAIR 2
#define DETECT_XBITS_TRACK_FLOW 3
Typedefs
typedef struct DetectXbitsData_ DetectXbitsData
Functions
void DetectXbitsRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-xbits.h.
Macro Definition Documentation
#define DETECT_XBITS_CMD_ISNOTSET 3
Definition at line 30 of file detect-xbits.h.
Referenced by DetectXbitMatchHost().
#define DETECT_XBITS_CMD_ISSET 4
Definition at line 31 of file detect-xbits.h.
Referenced by DetectXbitMatchHost().
#define DETECT_XBITS_CMD_MAX 6
Definition at line 33 of file detect-xbits.h.
#define DETECT_XBITS_CMD_NOALERT 5
Definition at line 32 of file detect-xbits.h.
#define DETECT_XBITS_CMD_SET 0
Definition at line 27 of file detect-xbits.h.
Referenced by DetectXbitMatchHost().
#define DETECT_XBITS_CMD_TOGGLE 1
Definition at line 28 of file detect-xbits.h.
Referenced by DetectXbitMatchHost().
#define DETECT_XBITS_CMD_UNSET 2
Definition at line 29 of file detect-xbits.h.
Referenced by DetectXbitMatchHost().
#define DETECT_XBITS_TRACK_FLOW 3
Definition at line 38 of file detect-xbits.h.
#define DETECT_XBITS_TRACK_IPDST 1
Definition at line 36 of file detect-xbits.h.
#define DETECT_XBITS_TRACK_IPPAIR 2
Definition at line 37 of file detect-xbits.h.
#define DETECT_XBITS_TRACK_IPSRC 0
Definition at line 35 of file detect-xbits.h.
Typedef Documentation
typedef struct DetectXbitsData_ DetectXbitsData
Function Documentation
void DetectXbitsRegister (void)
Definition at line 65 of file detect-xbits.c.
References SigTableElmt_::desc, DETECT_XBITS, DetectXbitFree(), DetectXbitMatch(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, sigmatch_table, and XBitsRegisterTests().
Referenced by SigTableSetup().