suricata: src/detect-engine-port.c File Reference
detect-engine-port.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "flow-var.h"
#include "util-cidr.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-rule-vars.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-siggroup.h"
#include "detect-engine-port.h"
#include "conf.h"
#include "util-debug.h"
#include "util-error.h"
#include "pkt-var.h"
#include "host.h"
#include "util-profiling.h"
Macros
#define PORT_HASH_SIZE 1024
Functions
DetectPort * PortParse (char *str)
Helper function for parsing port strings.
int DetectPortIsValidRange (char *port)
Helper function to check if a parsed port is in the valid range of available ports.
DetectPort * DetectPortInit (void)
Alloc a DetectPort structure and update counters.
void DetectPortFree (DetectPort *dp)
Free a DetectPort and its members.
void DetectPortPrintMemory (void)
Prints Memory statistics of the counters at detect-engine-port.[c,h].
DetectPort * DetectPortLookup (DetectPort *head, DetectPort *dp)
Used to see if the exact same portrange exists in the list.
void DetectPortPrintList (DetectPort *head)
Helper function used to print the list of ports present in this DetectPort list.
void DetectPortCleanupList (DetectPort *head)
Free a DetectPort list and each of its members.
int DetectPortAdd (DetectPort **head, DetectPort *dp)
Do a sorted insert, where the top of the list should be the biggest port range.
int DetectPortInsertCopy (DetectEngineCtx *de_ctx, DetectPort **head, DetectPort *new)
Copy and insert the new DetectPort, with a copy list of sigs.
int DetectPortInsert (DetectEngineCtx *de_ctx, DetectPort **head, DetectPort *new)
function for inserting a port group object. This also makes sure SigGroupContainer lists are handled correctly.
int DetectPortCmp (DetectPort *a, DetectPort *b)
Function that compare port groups.
DetectPort * DetectPortCopy (DetectEngineCtx *de_ctx, DetectPort *src)
Function that return a copy of DetectPort src.
DetectPort * DetectPortCopySingle (DetectEngineCtx *de_ctx, DetectPort *src)
Function that return a copy of DetectPort src sigs.
int DetectPortMatch (DetectPort *dp, uint16_t port)
Function Match to Match a port against a DetectPort group.
void DetectPortPrint (DetectPort *dp)
Helper function that print the DetectPort info.
DetectPort * DetectPortLookupGroup (DetectPort *dp, uint16_t port)
Function that find the group matching address in a group head.
int DetectPortJoin (DetectEngineCtx *de_ctx, DetectPort *target, DetectPort *source)
Function to join the source group to the target and its members.
int DetectPortIsCompletePortSpace (DetectPort *p)
Check if the port group list covers the complete port space.
int DetectPortParseMergeNotPorts (DetectPort **head, DetectPort **nhead)
Helper function for the parsing process.
int DetectPortTestConfVars (void)
int DetectPortParse (const DetectEngineCtx *de_ctx, DetectPort **head, char *str)
Function for parsing port strings.
uint32_t DetectPortHashFunc (HashListTable *ht, void *data, uint16_t datalen)
Generate a hash for a DetectPort group.
char DetectPortCompareFunc (void *data1, uint16_t len1, void *data2, uint16_t len2)
Function that return if the two DetectPort groups are equal or not.
void DetectPortFreeFunc (void *p)
int DetectPortDpHashInit (DetectEngineCtx *de_ctx)
Function that initialize the HashListTable of destination DetectPort.
void DetectPortDpHashFree (DetectEngineCtx *de_ctx)
Function that free the HashListTable of destination DetectPort.
void DetectPortDpHashReset (DetectEngineCtx *de_ctx)
Function that reset the HashListTable of destination DetectPort (Free and Initialize it)
int DetectPortDpHashAdd (DetectEngineCtx *de_ctx, DetectPort *p)
Function that add a destination DetectPort into the hashtable.
DetectPort * DetectPortDpHashLookup (DetectEngineCtx *de_ctx, DetectPort *p)
Function that search a destination DetectPort in the hashtable.
int DetectPortSpHashInit (DetectEngineCtx *de_ctx)
Function that initialize the HashListTable of source DetectPort.
void DetectPortSpHashFree (DetectEngineCtx *de_ctx)
Function that free the HashListTable of source DetectPort.
void DetectPortSpHashReset (DetectEngineCtx *de_ctx)
Function that reset the HashListTable of source DetectPort (Free and Initialize it)
int DetectPortSpHashAdd (DetectEngineCtx *de_ctx, DetectPort *p)
Function that add a source DetectPort into the hashtable.
DetectPort * DetectPortSpHashLookup (DetectEngineCtx *de_ctx, DetectPort *p)
Function that search a source DetectPort in the hashtable.
void DetectPortTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Ports part of the detection engine.
Todo:
move this out of the detection plugin structure
more unittesting
Definition in file detect-engine-port.c.
Macro Definition Documentation
#define PORT_HASH_SIZE 1024
Definition at line 1524 of file detect-engine-port.c.
Referenced by DetectPortDpHashInit(), and DetectPortSpHashInit().
Function Documentation
int DetectPortAdd (DetectPort ** head, DetectPort * dp)
Do a sorted insert, where the top of the list should be the biggest port range.
Todo:
XXX current sorting only works for overlapping ranges
Parameters
head Pointer to the DetectPort list head
dp Pointer to DetectPort to search in the DetectPort list
Return values
0 if dp is added correctly
Definition at line 202 of file detect-engine-port.c.
References DetectPortCmp(), DetectPort_::next, PORT_EB, and DetectPort_::prev.
void DetectPortCleanupList (DetectPort * head)
Free a DetectPort list and each of its members.
Parameters
head Pointer to the DetectPort list head
Definition at line 177 of file detect-engine-port.c.
References DetectPortFree(), DetectPort_::next, and next.
Referenced by AppLayerProtoDetectPPRegister(), BuildDestinationAddressHeadsWithBothPorts(), DetectAddressFree(), DetectPortFree(), DetectPortParse(), DetectPortTestConfVars(), PortParse(), and SigFree().
int DetectPortCmp (DetectPort * a, DetectPort * b)
Function that compare port groups.
Parameters
a pointer to DetectPort "a"
b pointer to DetectPort "b"
Return values
PORT_XX (Port enum value, XX is EQ, ES, EB, LE, etc)
PORT_ER on error
Definition at line 710 of file detect-engine-port.c.
References BUG_ON, DetectPort_::flags, DetectPort_::port, DetectPort_::port2, PORT_EB, PORT_EQ, PORT_ER, PORT_ES, PORT_FLAG_ANY, PORT_GE, PORT_GT, PORT_LE, and PORT_LT.
Referenced by DetectPortAdd(), DetectPortInsert(), DetectPortLookup(), and DetectPortParseMergeNotPorts().
char DetectPortCompareFunc (void * data1, uint16_t len1, void * data2, uint16_t len2)
Function that return if the two DetectPort groups are equal or not.
Parameters
data1 Pointer to the DetectPort 1
len1 sizeof data 1 (not used here atm)
data2 Pointer to the DetectPort 2
len2 sizeof data 2 (not used here atm)
Return values
1 if the DetectPort groups are equal
0 if not equal
Definition at line 1554 of file detect-engine-port.c.
References DetectPort_::flags, DetectPort_::port, and DetectPort_::port2.
Referenced by DetectPortDpHashInit(), and DetectPortSpHashInit().
DetectPort* DetectPortCopy (DetectEngineCtx * de_ctx, DetectPort * src)
Function that return a copy of DetectPort src.
Parameters
de_ctx Pointer to the current Detection Engine Context
src Pointer to a DetectPort group to copy
Return values
Pointer to a DetectPort instance (copy of src)
NULL on error
Definition at line 766 of file detect-engine-port.c.
References DetectPortCopy(), DetectPortInit(), DetectPort_::next, DetectPort_::port, DetectPort_::port2, and DetectPort_::prev.
Referenced by DetectPortCopy(), and DetectPortParseMergeNotPorts().
DetectPort* DetectPortCopySingle (DetectEngineCtx * de_ctx, DetectPort * src)
Function that return a copy of DetectPort src sigs.
Parameters
de_ctx Pointer to the current Detection Engine Context
src Pointer to a DetectPort group to copy
Return values
Pointer to a DetectPort instance (copy of src)
NULL on error
Definition at line 800 of file detect-engine-port.c.
References DetectPortInit(), DetectPort_::port, DetectPort_::port2, DetectPort_::sh, and SigGroupHeadCopySigs().
Referenced by BuildDestinationAddressHeadsWithBothPorts(), CreateGroupedPortList(), and DetectPortInsertCopy().
int DetectPortDpHashAdd (DetectEngineCtx * de_ctx, DetectPort * p)
Function that add a destination DetectPort into the hashtable.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
p Pointer to the DetectPort to add
Definition at line 1625 of file detect-engine-port.c.
References DetectEngineCtx_::dport_hash_table, and HashListTableAdd().
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DetectPortDpHashFree (DetectEngineCtx * de_ctx)
Function that free the HashListTable of destination DetectPort.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
Definition at line 1598 of file detect-engine-port.c.
References DetectEngineCtx_::dport_hash_table, and HashListTableFree().
Referenced by DetectEngineCtxFree(), DetectPortDpHashReset(), and SigAddressPrepareStage3().
int DetectPortDpHashInit (DetectEngineCtx * de_ctx)
Function that initialize the HashListTable of destination DetectPort.
Parameters
de_ctx Pointer to the current DetectionEngineContext
Return values
0 HashListTable initialization succes
-1 Error
Definition at line 1581 of file detect-engine-port.c.
References DetectPortCompareFunc(), DetectPortFreeFunc(), DetectPortHashFunc(), DetectEngineCtx_::dport_hash_table, HashListTableInit(), and PORT_HASH_SIZE.
Referenced by DetectPortDpHashReset().
DetectPort* DetectPortDpHashLookup (DetectEngineCtx * de_ctx, DetectPort * p)
Function that search a destination DetectPort in the hashtable.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
p Pointer to the DetectPort to search
Definition at line 1636 of file detect-engine-port.c.
References DetectEngineCtx_::dport_hash_table, and HashListTableLookup().
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DetectPortDpHashReset (DetectEngineCtx * de_ctx)
Function that reset the HashListTable of destination DetectPort (Free and Initialize it)
Parameters
de_ctx Pointer to the current DetectionEngineCtx
Definition at line 1613 of file detect-engine-port.c.
References DetectPortDpHashFree(), and DetectPortDpHashInit().
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DetectPortFree (DetectPort * dp)
Free a DetectPort and its members.
Parameters
dp Pointer to the DetectPort that has to be freed.
Definition at line 90 of file detect-engine-port.c.
References DetectPortCleanupList(), DetectPort_::dst_ph, DetectPort_::flags, PORT_GROUP_PORTS_COPY, PORT_SIGGROUPHEAD_COPY, SCFree, DetectPort_::sh, and SigGroupHeadFree().
Referenced by CreateGroupedPortList(), DetectPortCleanupList(), DetectPortFreeFunc(), DetectPortInsert(), and DetectPortParseMergeNotPorts().
void DetectPortFreeFunc (void * p)
Definition at line 1567 of file detect-engine-port.c.
References DetectPortFree().
Referenced by DetectPortDpHashInit(), and DetectPortSpHashInit().
uint32_t DetectPortHashFunc (HashListTable * ht, void * data, uint16_t datalen)
Generate a hash for a DetectPort group.
Parameters
ht HashListTable
data Pointer to the DetectPort
datalen sizeof data (not used here atm)
Return values
uint32_t the value of the generated hash
Definition at line 1535 of file detect-engine-port.c.
References HashListTable_::array_size, DetectPort_::port, and DetectPort_::port2.
Referenced by DetectPortDpHashInit(), and DetectPortSpHashInit().
DetectPort* DetectPortInit (void)
Alloc a DetectPort structure and update counters.
Return values
sgh Pointer to the newly created DetectPort on success; or NULL in case of error.
Definition at line 72 of file detect-engine-port.c.
References SCMalloc, and unlikely.
Referenced by DetectPortCopy(), DetectPortCopySingle(), DetectPortTestConfVars(), and PortParse().
int DetectPortInsert (DetectEngineCtx * de_ctx, DetectPort ** head, DetectPort * new)
function for inserting a port group object. This also makes sure SigGroupContainer lists are handled correctly.
Parameters
de_ctx Pointer to the current detection engine context
head Pointer to the DetectPort list head
dp DetectPort to search in the DetectPort list
Return values
1 inserted
0 not inserted, memory of new is freed
-1 error
Definition at line 267 of file detect-engine-port.c.
References BUG_ON, DetectPort_::cnt, DetectPortCmp(), DetectPortFree(), DetectPortInsert(), DetectPortPrint(), DetectPort_::next, PORT_EQ, PORT_ER, PORT_GT, PORT_LT, DetectPort_::prev, SCLogDebug, SCLogDebugEnabled(), DetectPort_::sh, and SigGroupHeadCopySigs().
Referenced by CreateGroupedPortList(), DetectPortInsert(), and DetectPortInsertCopy().
int DetectPortInsertCopy (DetectEngineCtx * de_ctx, DetectPort ** head, DetectPort * new)
Copy and insert the new DetectPort, with a copy list of sigs.
Parameters
de_ctx Pointer to the current detection engine context
head Pointer to the DetectPort list head
new Pointer to DetectPort to search in the DetectPort list
Return values
0 if dp is added correctly
Definition at line 245 of file detect-engine-port.c.
References DetectPortCopySingle(), and DetectPortInsert().
Referenced by CreateGroupedAddrList(), DetectAddressCutIPv4(), DetectAddressCutIPv6(), DetectAddressInsert(), and DetectAddressJoin().
int DetectPortIsCompletePortSpace (DetectPort * p)
Check if the port group list covers the complete port space.
Return values
0 no
1 yes
Definition at line 1208 of file detect-engine-port.c.
References DetectPort_::next, DetectPort_::port, and DetectPort_::port2.
Referenced by DetectPortParseMergeNotPorts(), and DetectPortTestConfVars().
int DetectPortIsValidRange (char * port)
Helper function to check if a parsed port is in the valid range of available ports.
Parameters
str Pointer to the port string
Return values
1 if port is in the valid range
0 if invalid
Definition at line 1513 of file detect-engine-port.c.
Referenced by PortParse().
int DetectPortJoin (DetectEngineCtx * de_ctx, DetectPort * target, DetectPort * source)
Function to join the source group to the target and its members.
Parameters
de_ctx Pointer to the current Detection Engine Context
target Pointer to DetectPort group where the source is joined
source Pointer to DetectPort group that will join into the target
Return values
-1 on error
0 on success
Definition at line 895 of file detect-engine-port.c.
References DetectPort_::cnt, DetectPort_::port, DetectPort_::port2, DetectPort_::sh, and SigGroupHeadCopySigs().
Referenced by CreateGroupedPortList().
DetectPort* DetectPortLookup (DetectPort * head, DetectPort * dp)
Used to see if the exact same portrange exists in the list.
Parameters
head Pointer to the DetectPort list head
dp DetectPort to search in the DetectPort list
Return values
returns a ptr to the match, or NULL if no match
Definition at line 136 of file detect-engine-port.c.
References DetectPortCmp(), DetectPort_::next, and PORT_EQ.
DetectPort* DetectPortLookupGroup (DetectPort * dp, uint16_t port)
Function that find the group matching address in a group head.
Parameters
dp Pointer to DetectPort group where we try to find the group
port port to search/lookup
Return values
Pointer to the DetectPort group of our port if it matched
NULL if port is not in the list
Definition at line 867 of file detect-engine-port.c.
References DetectPortMatch(), and DetectPort_::next.
Referenced by IPOnlyMatchPacket(), SigMatchSignatures(), and SigMatchSignaturesGetSgh().
int DetectPortMatch (DetectPort * dp, uint16_t port)
Function Match to Match a port against a DetectPort group.
Parameters
dp Pointer to DetectPort group where we try to match the port
port To compare/match
Return values
1 if port is in the range (it match)
0 if port is not in the range
Definition at line 829 of file detect-engine-port.c.
References DetectPort_::port.
Referenced by DetectPortLookupGroup().
int DetectPortParse (const DetectEngineCtx * de_ctx, DetectPort ** head, char * str)
Function for parsing port strings.
Parameters
head Pointer to the head of the DetectPort group list
str Pointer to the port string
Return values
0 on success
-1 on error
Definition at line 1402 of file detect-engine-port.c.
References DetectPortCleanupList(), DetectPortParseMergeNotPorts(), and SCLogDebug.
Referenced by AppLayerProtoDetectPPRegister().
int DetectPortParseMergeNotPorts (DetectPort ** head, DetectPort ** nhead)
Helper function for the parsing process.
Parameters
head Pointer to the head of the DetectPort group list
nhead Pointer to the new head of the DetectPort group list
Return values
0 on success
-1 on error
check if the full port space is negated
step 0: if the head list is empty, but the nhead list isn't we have a pure not thingy. In that case we add a 0:65535 first.
step 1: insert our ghn members into the gh list
work with a copy of the ad so we can easily clean up the ghn group later.
step 2: pull the address blocks that match our 'not' blocks
store the next ptr and remove the group
Definition at line 1248 of file detect-engine-port.c.
References DetectPortCmp(), DetectPortCopy(), DetectPortFree(), DetectPortIsCompletePortSpace(), DetectPortPrint(), DetectPort_::next, PORT_EB, PORT_EQ, DetectPort_::prev, SC_ERR_COMPLETE_PORT_SPACE_NEGATED, SC_ERR_NO_PORTS_LEFT_AFTER_MERGE, SCLogDebug, and SCLogError.
Referenced by DetectPortParse().
void DetectPortPrint (DetectPort * dp)
Helper function that print the DetectPort info.
Return values
none
Definition at line 843 of file detect-engine-port.c.
References DetectPort_::flags, DetectPort_::port, DetectPort_::port2, PORT_FLAG_ANY, and SCLogDebug.
Referenced by CreateGroupedPortList(), DetectPortInsert(), DetectPortParseMergeNotPorts(), DetectPortPrintList(), and SigAddressPrepareStage5().
void DetectPortPrintList (DetectPort * head)
Helper function used to print the list of ports present in this DetectPort list.
Parameters
head Pointer to the DetectPort list head
Definition at line 156 of file detect-engine-port.c.
References DetectPortPrint(), DetectPort_::next, and SCLogDebug.
Referenced by CreateGroupedPortList().
void DetectPortPrintMemory (void)
Prints Memory statistics of the counters at detect-engine-port.[c,h].
Definition at line 116 of file detect-engine-port.c.
References SCLogDebug.
int DetectPortSpHashAdd (DetectEngineCtx * de_ctx, DetectPort * p)
Function that add a source DetectPort into the hashtable.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
p Pointer to the DetectPort to add
Definition at line 1695 of file detect-engine-port.c.
References HashListTableAdd(), and DetectEngineCtx_::sport_hash_table.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DetectPortSpHashFree (DetectEngineCtx * de_ctx)
Function that free the HashListTable of source DetectPort.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
Definition at line 1668 of file detect-engine-port.c.
References HashListTableFree(), and DetectEngineCtx_::sport_hash_table.
Referenced by DetectEngineCtxFree(), DetectPortSpHashReset(), and SigAddressPrepareStage3().
int DetectPortSpHashInit (DetectEngineCtx * de_ctx)
Function that initialize the HashListTable of source DetectPort.
Parameters
de_ctx Pointer to the current DetectionEngineContext
Return values
0 HashListTable initialization succes
-1 Error
Definition at line 1651 of file detect-engine-port.c.
References DetectPortCompareFunc(), DetectPortFreeFunc(), DetectPortHashFunc(), HashListTableInit(), PORT_HASH_SIZE, and DetectEngineCtx_::sport_hash_table.
Referenced by DetectPortSpHashReset().
DetectPort* DetectPortSpHashLookup (DetectEngineCtx * de_ctx, DetectPort * p)
Function that search a source DetectPort in the hashtable.
Parameters
de_ctx Pointer to the current DetectionEngineCtx
p Pointer to the DetectPort to search
Definition at line 1706 of file detect-engine-port.c.
References HashListTableLookup(), and DetectEngineCtx_::sport_hash_table.
Referenced by BuildDestinationAddressHeadsWithBothPorts().
void DetectPortSpHashReset (DetectEngineCtx * de_ctx)
Function that reset the HashListTable of source DetectPort (Free and Initialize it)
Parameters
de_ctx Pointer to the current DetectionEngineCtx
Definition at line 1683 of file detect-engine-port.c.
References DetectPortSpHashFree(), and DetectPortSpHashInit().
Referenced by BuildDestinationAddressHeadsWithBothPorts().
int DetectPortTestConfVars (void)
Definition at line 1336 of file detect-engine-port.c.
References ConfGetNode(), DetectPortCleanupList(), DetectPortInit(), DetectPortIsCompletePortSpace(), ConfNode_::name, next, SC_ERR_INVALID_YAML_CONF_ENTRY, SCLogDebug, SCLogError, TAILQ_FOREACH, and ConfNode_::val.
void DetectPortTests (void)
Definition at line 2800 of file detect-engine-port.c.
Referenced by RunUnittests().
DetectPort * PortParse (char * str)
Helper function for parsing port strings.
Parameters
str Pointer to the port string
Return values
DetectPort pointer of the parse string on success
NULL on error
Definition at line 1439 of file detect-engine-port.c.
References DetectPortCleanupList(), DetectPortInit(), DetectPortIsValidRange(), DetectPort_::flags, DetectPort_::port, DetectPort_::port2, PORT_FLAG_NOT, and strlcpy().