suricata: src/detect-ftpbounce.h File Reference
detect-ftpbounce.h File Reference
Functions
void DetectFtpbounceRegister (void)
Registration function for ftpbounce: keyword.
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file detect-ftpbounce.h.
Function Documentation
void DetectFtpbounceRegister (void)
Registration function for ftpbounce: keyword.
Todo:
add support for no_stream and stream_only
Definition at line 64 of file detect-ftpbounce.c.
References SigTableElmt_::alproto, ALPROTO_FTP, SigTableElmt_::AppLayerMatch, DETECT_FTPBOUNCE, DetectFtpbounceALMatch(), DetectFtpbounceRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, and sigmatch_table.
Referenced by SigTableSetup().