suricata: src/detect-pcre.h File Reference
detect-pcre.h File Reference
Data Structures
struct DetectPcreData_
Macros
#define DETECT_PCRE_RELATIVE 0x00001
#define DETECT_PCRE_RAWBYTES 0x00002
#define DETECT_PCRE_CASELESS 0x00004
#define DETECT_PCRE_CAPTURE_PKT 0x00008
#define DETECT_PCRE_CAPTURE_FLOW 0x00010
#define DETECT_PCRE_MATCH_LIMIT 0x00020
#define DETECT_PCRE_RELATIVE_NEXT 0x00040
#define DETECT_PCRE_NEGATE 0x00080
Typedefs
typedef struct DetectPcreData_ DetectPcreData
Functions
int DetectPcrePayloadMatch (DetectEngineThreadCtx *, Signature *, SigMatch *, Packet *, Flow *, uint8_t *, uint32_t)
Match a regex on a single payload.
int DetectPcrePacketPayloadMatch (DetectEngineThreadCtx *, Packet *, Signature *, SigMatch *)
int DetectPcrePayloadDoMatch (DetectEngineThreadCtx *, Signature *, SigMatch *, Packet *, uint8_t *, uint16_t)
void DetectPcreRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-pcre.h.
Macro Definition Documentation
#define DETECT_PCRE_CAPTURE_FLOW 0x00010
Definition at line 31 of file detect-pcre.h.
Referenced by DetectPcrePayloadMatch().
#define DETECT_PCRE_CAPTURE_PKT 0x00008
Definition at line 30 of file detect-pcre.h.
Referenced by DetectPcrePayloadMatch().
#define DETECT_PCRE_CASELESS 0x00004
Definition at line 29 of file detect-pcre.h.
#define DETECT_PCRE_MATCH_LIMIT 0x00020
Definition at line 32 of file detect-pcre.h.
#define DETECT_PCRE_NEGATE 0x00080
Definition at line 34 of file detect-pcre.h.
Referenced by DetectPcrePayloadMatch().
#define DETECT_PCRE_RAWBYTES 0x00002
Definition at line 28 of file detect-pcre.h.
#define DETECT_PCRE_RELATIVE 0x00001
Definition at line 27 of file detect-pcre.h.
Referenced by DetectPcrePayloadMatch().
#define DETECT_PCRE_RELATIVE_NEXT 0x00040
Definition at line 33 of file detect-pcre.h.
Referenced by DetectByteExtractSetup(), DetectBytejumpSetup(), DetectBytetestSetup(), DetectEngineContentInspection(), DetectEngineContentModifierBufferSetup(), and DetectIsdataatSetup().
Typedef Documentation
typedef struct DetectPcreData_ DetectPcreData
Function Documentation
int DetectPcrePacketPayloadMatch (DetectEngineThreadCtx * , Packet * , Signature * , SigMatch *)
int DetectPcrePayloadDoMatch (DetectEngineThreadCtx * , Signature * , SigMatch * , Packet * , uint8_t * , uint16_t)
int DetectPcrePayloadMatch (DetectEngineThreadCtx * det_ctx, Signature * s, SigMatch * sm, Packet * p, Flow * f, uint8_t * payload, uint32_t payload_len)
Match a regex on a single payload.
Parameters
det_ctx Thread detection ctx.
s Signature.
sm Sig match to match against.
p Packet to set PktVars if any.
f Flow to set FlowVars if any.
payload Payload to inspect.
payload_len Length of the payload.
Return values
1 Match.
0 No match.
Definition at line 182 of file detect-pcre.c.
References DetectEngineThreadCtx_::buffer_offset, DetectPcreData_::capidx, DetectPcreData_::capname, SigMatch_::ctx, DETECT_FLOWVAR_TYPE_POSTMATCH, DETECT_PCRE_CAPTURE_FLOW, DETECT_PCRE_CAPTURE_PKT, DETECT_PCRE_NEGATE, DETECT_PCRE_RELATIVE, DetectFlowvarStoreMatch(), DetectPcreData_::flags, len, MAX_SUBSTRINGS, DetectEngineThreadCtx_::pcre_match_start_offset, PktVarAdd(), DetectPcreData_::re, SCEnter, SCLogDebug, SCReturnInt, and DetectPcreData_::sd.
Referenced by DetectEngineContentInspection().
void DetectPcreRegister (void)
Definition at line 86 of file detect-pcre.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, ConfGetInt(), SigTableElmt_::desc, DETECT_PCRE, DetectPcreFree(), DetectPcreRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_CAPTURE_REGEX, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SC_MATCH_LIMIT_DEFAULT, SC_MATCH_LIMIT_RECURSION_DEFAULT, SCLogDebug, SCLogError, SCLogInfo, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().