suricata: src/detect-asn1.c File Reference
detect-asn1.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "flow.h"
#include "detect-asn1.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-byte.h"
#include "util-debug.h"
#include "util-decode-asn1.h"
Functions
int DetectAsn1Match (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function will decode the asn1 data and inspect the resulting nodes to detect if any of the specified checks match this data.
void DetectAsn1RegisterTests (void)
this function registers unit tests for DetectAsn1
void DetectAsn1Free (void *ptr)
this function will free memory associated with DetectAsn1Data
void DetectAsn1Register (void)
Registration function for asn1.
DetectAsn1Data * DetectAsn1Parse (char *asn1str)
This function is used to parse asn1 options passed via asn1: keyword.
Variables
const char * ASN_DELIM = " \t,\n"
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements "asn1" keyword
Definition in file detect-asn1.c.
Function Documentation
void DetectAsn1Free (void * ptr)
this function will free memory associated with DetectAsn1Data
Parameters
ad pointer to DetectAsn1Data
Definition at line 325 of file detect-asn1.c.
References SCFree.
Referenced by DetectAsn1Register().
int DetectAsn1Match (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function will decode the asn1 data and inspect the resulting nodes to detect if any of the specified checks match this data.
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectAsn1Data
Return values
0 no match
1 match
Definition at line 140 of file detect-asn1.c.
References DetectAsn1Data_::absolute_offset, ASN1_ABSOLUTE_OFFSET, ASN1_RELATIVE_OFFSET, Asn1Ctx_::asn1_stack, ASN1CTX_GET_NODE, Asn1Ctx_::cur_frame, DetectAsn1Data_::flags, Asn1Node_::id, Packet_::payload, Packet_::payload_len, Asn1Id_::ptr, DetectAsn1Data_::relative_offset, SCAsn1CtxDestroy(), SCAsn1CtxInit(), SCAsn1CtxNew(), and SCAsn1Decode().
Referenced by DetectAsn1Register().
DetectAsn1Data* DetectAsn1Parse (char * asn1str)
This function is used to parse asn1 options passed via asn1: keyword.
Parameters
asn1str Pointer to the user provided asn1 options
Return values
fd pointer to DetectAsn1Data on success
NULL on failure
Definition at line 200 of file detect-asn1.c.
References DetectAsn1Data_::absolute_offset, ASN1_ABSOLUTE_OFFSET, ASN1_BITSTRING_OVF, ASN1_DOUBLE_OVF, ASN1_OVERSIZE_LEN, ASN1_RELATIVE_OFFSET, ASN_DELIM, ByteExtractStringInt32(), ByteExtractStringUint32(), DetectAsn1Data_::flags, flags, DetectAsn1Data_::oversize_length, DetectAsn1Data_::relative_offset, SC_ERR_INVALID_VALUE, SCLogError, SCMalloc, and unlikely.
void DetectAsn1Register (void)
Registration function for asn1.
Definition at line 54 of file detect-asn1.c.
References DETECT_ASN1, DetectAsn1Free(), DetectAsn1Match(), DetectAsn1RegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
void DetectAsn1RegisterTests (void)
this function registers unit tests for DetectAsn1
Definition at line 1333 of file detect-asn1.c.
Referenced by DetectAsn1Register().
Variable Documentation
const char* ASN_DELIM = " \t,\n"
Definition at line 43 of file detect-asn1.c.
Referenced by DetectAsn1Parse().