suricata: src/detect-classtype.c File Reference
detect-classtype.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-classtype.h"
#include "flow-var.h"
#include "util-classification-config.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-unittest.h"
Macros
#define DETECT_CLASSTYPE_REGEX "^\\s*([a-zA-Z][a-zA-Z0-9-_]*)\\s*$"
#define MAX_SUBSTRINGS 30
Functions
void DetectClasstypeRegisterTests (void)
This function registers unit tests for Classification Config API.
void DetectClasstypeRegister (void)
Registers the handler functions for the "Classtype" keyword.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Implements classtype keyword.
Definition in file detect-classtype.c.
Macro Definition Documentation
#define DETECT_CLASSTYPE_REGEX "^\\s*([a-zA-Z][a-zA-Z0-9-_]*)\\s*$"
Definition at line 40 of file detect-classtype.c.
Referenced by DetectClasstypeRegister().
#define MAX_SUBSTRINGS 30
Function Documentation
void DetectClasstypeRegister (void)
Registers the handler functions for the "Classtype" keyword.
Definition at line 51 of file detect-classtype.c.
References SigTableElmt_::desc, DETECT_CLASSTYPE, DETECT_CLASSTYPE_REGEX, DetectClasstypeRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectClasstypeRegisterTests (void)
This function registers unit tests for Classification Config API.
Definition at line 331 of file detect-classtype.c.
Referenced by DetectClasstypeRegister().