suricata: src/detect-byte-extract.c File Reference
detect-byte-extract.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "detect-content.h"
#include "detect-pcre.h"
#include "detect-bytejump.h"
#include "detect-bytetest.h"
#include "detect-byte-extract.h"
#include "detect-isdataat.h"
#include "app-layer-protos.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-byte.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-spm.h"
Macros
#define DETECT_BYTE_EXTRACT_ENDIAN_DEFAULT DETECT_BYTE_EXTRACT_ENDIAN_BIG
#define DETECT_BYTE_EXTRACT_BASE_NONE 0
#define DETECT_BYTE_EXTRACT_BASE_HEX 16
#define DETECT_BYTE_EXTRACT_BASE_DEC 10
#define DETECT_BYTE_EXTRACT_BASE_OCT 8
#define DETECT_BYTE_EXTRACT_MULTIPLIER_DEFAULT 1
#define DETECT_BYTE_EXTRACT_MULTIPLIER_MIN_LIMIT 1
#define DETECT_BYTE_EXTRACT_MULTIPLIER_MAX_LIMIT 65535
#define STRING_MAX_BYTES_TO_EXTRACT_FOR_OCT 23
#define STRING_MAX_BYTES_TO_EXTRACT_FOR_DEC 20
#define STRING_MAX_BYTES_TO_EXTRACT_FOR_HEX 14
#define NO_STRING_MAX_BYTES_TO_EXTRACT 8
#define PARSE_REGEX
#define MAX_SUBSTRINGS 100
Functions
int DetectByteExtractMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, SigMatch *)
int DetectByteExtractSetup (DetectEngineCtx *de_ctx, Signature *s, char *arg)
The setup function for the byte_extract keyword for a signature.
void DetectByteExtractRegisterTests (void)
void DetectByteExtractFree (void *ptr)
Used to free instances of DetectByteExtractData.
void DetectByteExtractRegister (void)
Registers the keyword handlers for the "byte_extract" keyword.
int DetectByteExtractDoMatch (DetectEngineThreadCtx *det_ctx, SigMatch *sm, Signature *s, uint8_t *payload, uint16_t payload_len, uint64_t *value, uint8_t endian)
SigMatch * DetectByteExtractRetrieveSMVar (const char *arg, Signature *s)
Lookup the SigMatch for a named byte_extract variable.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-byte-extract.c.
Macro Definition Documentation
#define DETECT_BYTE_EXTRACT_BASE_DEC 10
Definition at line 59 of file detect-byte-extract.c.
Referenced by DetectByteExtractSetup().
#define DETECT_BYTE_EXTRACT_BASE_HEX 16
Definition at line 58 of file detect-byte-extract.c.
Referenced by DetectByteExtractSetup().
#define DETECT_BYTE_EXTRACT_BASE_NONE 0
Definition at line 57 of file detect-byte-extract.c.
#define DETECT_BYTE_EXTRACT_BASE_OCT 8
Definition at line 60 of file detect-byte-extract.c.
Referenced by DetectByteExtractSetup().
#define DETECT_BYTE_EXTRACT_ENDIAN_DEFAULT DETECT_BYTE_EXTRACT_ENDIAN_BIG
Definition at line 53 of file detect-byte-extract.c.
#define DETECT_BYTE_EXTRACT_MULTIPLIER_DEFAULT 1
Definition at line 65 of file detect-byte-extract.c.
#define DETECT_BYTE_EXTRACT_MULTIPLIER_MAX_LIMIT 65535
Definition at line 68 of file detect-byte-extract.c.
#define DETECT_BYTE_EXTRACT_MULTIPLIER_MIN_LIMIT 1
Definition at line 67 of file detect-byte-extract.c.
#define MAX_SUBSTRINGS 100
Referenced by DetectPcrePayloadMatch().
#define NO_STRING_MAX_BYTES_TO_EXTRACT 8
Definition at line 76 of file detect-byte-extract.c.
#define PARSE_REGEX
Value:
"^"                                                  \
    "\\s*([0-9]+)\\s*"                                                   \
    ",\\s*(-?[0-9]+)\\s*"                                               \
    ",\\s*([^\\s,]+)\\s*"                                                \
    "(?:(?:,\\s*([^\\s,]+)\\s*)|(?:,\\s*([^\\s,]+)\\s+([^\\s,]+)\\s*))?" \
    "(?:(?:,\\s*([^\\s,]+)\\s*)|(?:,\\s*([^\\s,]+)\\s+([^\\s,]+)\\s*))?" \
    "(?:(?:,\\s*([^\\s,]+)\\s*)|(?:,\\s*([^\\s,]+)\\s+([^\\s,]+)\\s*))?" \
    "(?:(?:,\\s*([^\\s,]+)\\s*)|(?:,\\s*([^\\s,]+)\\s+([^\\s,]+)\\s*))?" \
    "(?:(?:,\\s*([^\\s,]+)\\s*)|(?:,\\s*([^\\s,]+)\\s+([^\\s,]+)\\s*))?" \
    "$"
Definition at line 78 of file detect-byte-extract.c.
Referenced by DetectByteExtractRegister().
#define STRING_MAX_BYTES_TO_EXTRACT_FOR_DEC 20
Definition at line 73 of file detect-byte-extract.c.
#define STRING_MAX_BYTES_TO_EXTRACT_FOR_HEX 14
Definition at line 74 of file detect-byte-extract.c.
#define STRING_MAX_BYTES_TO_EXTRACT_FOR_OCT 23
Definition at line 72 of file detect-byte-extract.c.
Function Documentation
int DetectByteExtractDoMatch (DetectEngineThreadCtx * det_ctx, SigMatch * sm, Signature * s, uint8_t * payload, uint16_t payload_len, uint64_t * value, uint8_t endian)
Definition at line 134 of file detect-byte-extract.c.
References DetectByteExtractData_::align_value, DetectByteExtractData_::base, DetectEngineThreadCtx_::buffer_offset, BYTE_BIG_ENDIAN, BYTE_LITTLE_ENDIAN, ByteExtractStringUint64(), ByteExtractUint64(), SigMatch_::ctx, data, DETECT_BYTE_EXTRACT_ENDIAN_BIG, DETECT_BYTE_EXTRACT_FLAG_ALIGN, DETECT_BYTE_EXTRACT_FLAG_RELATIVE, DETECT_BYTE_EXTRACT_FLAG_STRING, DetectByteExtractData_::flags, len, DetectByteExtractData_::multiplier_value, DetectByteExtractData_::nbytes, DetectByteExtractData_::offset, SC_ERR_INVALID_NUM_BYTES, SCLogDebug, and SCLogError.
void DetectByteExtractFree (void * ptr)
Used to free instances of DetectByteExtractData.
Parameters
ptr Instance of DetectByteExtractData to be freed.
Definition at line 761 of file detect-byte-extract.c.
References DetectByteExtractData_::name, and SCFree.
Referenced by DetectByteExtractRegister(), and DetectByteExtractSetup().
int DetectByteExtractMatch (ThreadVars * tv, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, SigMatch * m)
Definition at line 225 of file detect-byte-extract.c.
void DetectByteExtractRegister (void)
Registers the keyword handlers for the "byte_extract" keyword.
Definition at line 101 of file detect-byte-extract.c.
References SigTableElmt_::AppLayerMatch, DETECT_BYTE_EXTRACT, DetectByteExtractFree(), DetectByteExtractRegisterTests(), DetectByteExtractSetup(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void DetectByteExtractRegisterTests (void)
Definition at line 4820 of file detect-byte-extract.c.
Referenced by DetectByteExtractRegister().
SigMatch* DetectByteExtractRetrieveSMVar (const char * arg, Signature * s)
Lookup the SigMatch for a named byte_extract variable.
Parameters
arg The name of the byte_extract variable to lookup.
s Pointer the signature to look in.
Return values
A pointer to the SigMatch if found, otherwise NULL.
Definition at line 781 of file detect-byte-extract.c.
References SigMatch_::ctx, DETECT_BYTE_EXTRACT, DETECT_SM_LIST_MAX, DetectByteExtractData_::name, SigMatch_::next, Signature_::sm_lists, and SigMatch_::type.
Referenced by DetectBytejumpSetup(), DetectBytetestSetup(), and DetectIsdataatSetup().
int DetectByteExtractSetup (DetectEngineCtx * de_ctx, Signature * s, char * arg)
The setup function for the byte_extract keyword for a signature.
Parameters
de_ctx Pointer to the detection engine context.
s Pointer to signature for the current Signature being parsed from the rules.
m Pointer to the head of the SigMatch for the current rule being parsed.
arg Pointer to the string holding the keyword value.
Return values
0 On success.
-1 On failure.
Definition at line 543 of file detect-byte-extract.c.
References Signature_::alproto, ALPROTO_DCERPC, ALPROTO_UNKNOWN, AppLayerHtpEnableResponseBodyCallback(), DetectByteExtractData_::base, DetectEngineCtx_::byte_extract_max_local_id, SigMatch_::ctx, data, DETECT_BYTE_EXTRACT, DETECT_BYTE_EXTRACT_BASE_DEC, DETECT_BYTE_EXTRACT_BASE_HEX, DETECT_BYTE_EXTRACT_BASE_OCT, DETECT_BYTE_EXTRACT_ENDIAN_DCE, DETECT_BYTE_EXTRACT_FLAG_RELATIVE, DETECT_BYTE_EXTRACT_FLAG_STRING, DETECT_BYTEJUMP, DETECT_BYTETEST, DETECT_CONTENT, DETECT_CONTENT_RELATIVE_NEXT, DETECT_ISDATAAT, DETECT_PCRE, DETECT_PCRE_RELATIVE_NEXT, DETECT_SM_LIST_FILEDATA, DETECT_SM_LIST_HCBDMATCH, DETECT_SM_LIST_HCDMATCH, DETECT_SM_LIST_HHDMATCH, DETECT_SM_LIST_HHHDMATCH, DETECT_SM_LIST_HMDMATCH, DETECT_SM_LIST_HRHDMATCH, DETECT_SM_LIST_HRHHDMATCH, DETECT_SM_LIST_HRUDMATCH, DETECT_SM_LIST_HSCDMATCH, DETECT_SM_LIST_HSMDMATCH, DETECT_SM_LIST_HUADMATCH, DETECT_SM_LIST_NOTSET, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_UMATCH, DetectByteExtractFree(), DetectByteExtractData_::endian, DetectPcreData_::flags, DetectByteExtractData_::flags, DetectContentData_::flags, Signature_::flags, Signature_::list, DetectByteExtractData_::local_id, SC_ERR_CONFLICTING_RULE_KEYWORDS, SC_ERR_INVALID_SIGNATURE, SCLogError, SIG_FLAG_APPLAYER, SigMatchAlloc(), SigMatchAppendSMToList(), SigMatchGetLastSMFromLists(), SigMatchListSMBelongsTo(), Signature_::sm_lists_tail, and SigMatch_::type.
Referenced by DetectByteExtractRegister().