suricata: src/detect-ftpbounce.c File Reference
detect-ftpbounce.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "detect-content.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-ftp.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "threads.h"
#include "detect-ftpbounce.h"
#include "stream-tcp.h"
#include "util-byte.h"
Functions
int DetectFtpbounceMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, Signature *, SigMatch *)
int DetectFtpbounceALMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Flow *f, uint8_t flags, void *state, Signature *s, SigMatch *m)
This function is used to check matches from the FTP App Layer Parser.
int DetectFtpbounceMatchArgs (uint8_t *payload, uint16_t payload_len, uint32_t ip_orig, uint16_t offset)
This function is used to match ftpbounce attacks.
void DetectFtpbounceRegisterTests (void)
this function registers unit tests for DetectFtpbounce
void DetectFtpbounceFree (void *)
void DetectFtpbounceRegister (void)
Registration function for ftpbounce: keyword.
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
ftpbounce keyword, part of the detection engine.
Definition in file detect-ftpbounce.c.
Function Documentation
int DetectFtpbounceALMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Flow * f, uint8_t flags, void * state, Signature * s, SigMatch * m)
This function is used to check matches from the FTP App Layer Parser.
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch but we don't use it since ftpbounce has no options
Return values
0 no match
1 match
Definition at line 172 of file detect-ftpbounce.c.
References FlowAddress_::address, FlowAddress_::address_un_data32, FtpState_::arg_offset, FtpState_::command, DetectFtpbounceMatchArgs(), FTP_COMMAND_PORT, FtpState_::port_line, FtpState_::port_line_len, SCEnter, SCLogDebug, SCReturnInt, and Flow_::src.
Referenced by DetectFtpbounceRegister().
void DetectFtpbounceFree (void *)
int DetectFtpbounceMatch (ThreadVars * , DetectEngineThreadCtx * , Packet * , Signature * , SigMatch *)
int DetectFtpbounceMatchArgs (uint8_t * payload, uint16_t payload_len, uint32_t ip_orig, uint16_t offset)
This function is used to match ftpbounce attacks.
Parameters
payload Payload of the PORT command
payload_len Length of the payload
ip_orig IP source to check the ftpbounce condition
offset offset to the arguments of the PORT command
Return values
1 if ftpbounce detected, 0 if not
Definition at line 87 of file detect-ftpbounce.c.
References SCByteSwap32, SCEnter, and SCLogDebug.
Referenced by DetectFtpbounceALMatch().
void DetectFtpbounceRegister (void)
Registration function for ftpbounce: keyword.
Todo:
add support for no_stream and stream_only
Definition at line 64 of file detect-ftpbounce.c.
References SigTableElmt_::alproto, ALPROTO_FTP, SigTableElmt_::AppLayerMatch, DETECT_FTPBOUNCE, DetectFtpbounceALMatch(), DetectFtpbounceRegisterTests(), SigTableElmt_::flags, SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_NOOPT, and sigmatch_table.
Referenced by SigTableSetup().
void DetectFtpbounceRegisterTests (void)
this function registers unit tests for DetectFtpbounce
Definition at line 551 of file detect-ftpbounce.c.
Referenced by DetectFtpbounceRegister().