suricata: src/detect-iprep.h File Reference
detect-iprep.h File Reference
Data Structures
struct DetectIPRepData_
Macros
#define DETECT_IPREP_CMD_ANY 0
#define DETECT_IPREP_CMD_BOTH 1
#define DETECT_IPREP_CMD_SRC 2
#define DETECT_IPREP_CMD_DST 3
#define DETECT_IPREP_OP_LT 0
#define DETECT_IPREP_OP_GT 1
#define DETECT_IPREP_OP_EQ 2
Typedefs
typedef struct DetectIPRepData_ DetectIPRepData
Functions
void DetectIPRepRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-iprep.h.
Macro Definition Documentation
#define DETECT_IPREP_CMD_ANY 0
Definition at line 27 of file detect-iprep.h.
Referenced by DetectIPRepMatch().
#define DETECT_IPREP_CMD_BOTH 1
Definition at line 28 of file detect-iprep.h.
Referenced by DetectIPRepMatch().
#define DETECT_IPREP_CMD_DST 3
Definition at line 30 of file detect-iprep.h.
Referenced by DetectIPRepMatch().
#define DETECT_IPREP_CMD_SRC 2
Definition at line 29 of file detect-iprep.h.
Referenced by DetectIPRepMatch().
#define DETECT_IPREP_OP_EQ 2
Definition at line 34 of file detect-iprep.h.
#define DETECT_IPREP_OP_GT 1
Definition at line 33 of file detect-iprep.h.
#define DETECT_IPREP_OP_LT 0
Definition at line 32 of file detect-iprep.h.
Typedef Documentation
typedef struct DetectIPRepData_ DetectIPRepData
Function Documentation
void DetectIPRepRegister (void)
Definition at line 60 of file detect-iprep.c.
References DETECT_IPREP, DetectIPRepFree(), DetectIPRepMatch(), SigTableElmt_::flags, SigTableElmt_::Free, IPRepRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, SIGMATCH_IPONLY_COMPAT, and sigmatch_table.
Referenced by SigTableSetup().