suricata: src/detect-uricontent.c File Reference
detect-uricontent.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "detect-content.h"
#include "detect-http-uri.h"
#include "detect-uricontent.h"
#include "detect-engine-mpm.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "detect-flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "threads.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-protos.h"
#include "app-layer-htp.h"
#include "util-mpm.h"
#include "util-print.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-binsearch.h"
#include "util-spm.h"
#include "util-spm-bm.h"
#include "conf.h"
Functions
void HttpUriRegisterTests (void)
int DetectAppLayerUricontentMatch (ThreadVars *, DetectEngineThreadCtx *, Flow *, uint8_t, void *, Signature *, SigMatch *)
void DetectUricontentFree (void *ptr)
this function will Free memory associated with DetectContentData
void DetectUricontentRegister (void)
Registration function for uricontent: keyword.
uint32_t DetectUricontentMaxId (DetectEngineCtx *de_ctx)
pass on the uricontent_max_id
void DetectUricontentPrint (DetectContentData *cd)
Helper function to print a DetectContentData.
uint32_t DetectUricontentInspectMpm (DetectEngineThreadCtx *det_ctx, Flow *f, HtpState *htp_state, uint8_t flags, void *txv, uint64_t idx)
Run the pattern matcher against the uri(s)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Simple uricontent match part of the detection engine.
Definition in file detect-uricontent.c.
Function Documentation
int DetectAppLayerUricontentMatch (ThreadVars * , DetectEngineThreadCtx * , Flow * , uint8_t , void * , Signature * , SigMatch *)
void DetectUricontentFree (void * ptr)
this function will Free memory associated with DetectContentData
Parameters
cd pointer to DetectUricotentData
Definition at line 99 of file detect-uricontent.c.
References DetectContentData_::bm_ctx, BoyerMooreCtxDeInit(), SCEnter, SCFree, and SCReturn.
Referenced by DetectUricontentRegister().
uint32_t DetectUricontentInspectMpm (DetectEngineThreadCtx * det_ctx, Flow * f, HtpState * htp_state, uint8_t flags, void * txv, uint64_t idx)
Run the pattern matcher against the uri(s)
We run against all uri(s) we have as the pattern matcher will flag each sig that has a match. We need to do this for all uri(s) to not miss possible events.
Parameters
f locked flow
htp_state initialized htp state
Warning
Make sure the flow/state is locked
Todo:
what should we return? Just the fact that we matched?
Definition at line 247 of file detect-uricontent.c.
References bstr_len, bstr_ptr, htp_tx_get_user_data(), HtpTxUserData_::request_uri_normalized, SCEnter, and SCReturnUInt.
uint32_t DetectUricontentMaxId (DetectEngineCtx * de_ctx)
pass on the uricontent_max_id
Parameters
de_ctx pointer to the detect egine context whose max id is asked
Definition at line 89 of file detect-uricontent.c.
References DetectEngineCtx_::mpm_pattern_id_store, and MpmPatternIdStoreGetMaxId().
Referenced by SigGroupHeadLoadUricontent().
void DetectUricontentPrint (DetectContentData * cd)
Helper function to print a DetectContentData.
Definition at line 116 of file detect-uricontent.c.
References DetectContentData_::content, DetectContentData_::content_len, DetectContentData_::depth, DETECT_CONTENT_NEGATED, DETECT_CONTENT_RELATIVE_NEXT, DetectContentData_::distance, DetectContentData_::flags, DetectContentData_::id, DetectContentData_::offset, SCFree, SCLogDebug, SCMalloc, unlikely, and DetectContentData_::within.
void DetectUricontentRegister (void)
Registration function for uricontent: keyword.
Definition at line 72 of file detect-uricontent.c.
References SigTableElmt_::alproto, ALPROTO_HTTP, SigTableElmt_::AppLayerMatch, DETECT_URICONTENT, DetectUricontentFree(), SigTableElmt_::flags, SigTableElmt_::Free, HttpUriRegisterTests(), SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, SIGMATCH_PAYLOAD, and sigmatch_table.
Referenced by SigTableSetup().
void HttpUriRegisterTests (void)
Definition at line 1949 of file detect-uricontent.c.
Referenced by DetectUricontentRegister().