suricata: src/detect-icmp-id.c File Reference
detect-icmp-id.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-icmp-id.h"
#include "util-byte.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^\\s*(\"\\s*)?([0-9]+)(\\s*\")?\\s*$"
#define MAX_SUBSTRINGS 30
Functions
int DetectIcmpIdMatch (ThreadVars *t, DetectEngineThreadCtx *det_ctx, Packet *p, Signature *s, const SigMatchCtx *ctx)
This function is used to match icmp_id rule option set on a packet.
void DetectIcmpIdRegisterTests (void)
void DetectIcmpIdFree (void *ptr)
this function will free memory associated with DetectIcmpIdData
void DetectIcmpIdRegister (void)
Registration function for icode: icmp_id.
DetectIcmpIdData * DetectIcmpIdParse (char *icmpidstr)
This function is used to parse icmp_id option passed via icmp_id: keyword.
Detailed Description
Author
Gerardo Iglesias Galvan igles.nosp@m.iasg.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Implements the icmp_id keyword
Definition in file detect-icmp-id.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Referenced by DetectIcmpIdParse().
#define PARSE_REGEX "^\\s*(\"\\s*)?([0-9]+)(\\s*\")?\\s*$"
Definition at line 40 of file detect-icmp-id.c.
Referenced by DetectIcmpIdRegister().
Function Documentation
void DetectIcmpIdFree (void * ptr)
this function will free memory associated with DetectIcmpIdData
Parameters
ptr pointer to DetectIcmpIdData
Definition at line 262 of file detect-icmp-id.c.
References SCFree.
Referenced by DetectIcmpIdParse(), and DetectIcmpIdRegister().
int DetectIcmpIdMatch (ThreadVars * t, DetectEngineThreadCtx * det_ctx, Packet * p, Signature * s, const SigMatchCtx * ctx)
This function is used to match icmp_id rule option set on a packet.
Parameters
t pointer to thread vars
det_ctx pointer to the pattern matcher thread
p pointer to the current packet
m pointer to the sigmatch that we will cast into DetectIcmpIdData
Return values
0 no match
1 match
Definition at line 95 of file detect-icmp-id.c.
References ICMP6_ECHO_REPLY, ICMP6_ECHO_REQUEST, ICMPV4_GET_ID, ICMPV4_GET_TYPE, ICMPV6_GET_ID, ICMPV6_GET_TYPE, DetectIcmpIdData_::id, PKT_IS_ICMPV4, PKT_IS_ICMPV6, PKT_IS_PSEUDOPKT, and SCLogDebug.
Referenced by DetectIcmpIdRegister().
DetectIcmpIdData* DetectIcmpIdParse (char * icmpidstr)
This function is used to parse icmp_id option passed via icmp_id: keyword.
Parameters
icmpidstr Pointer to the user provided icmp_id options
Return values
iid pointer to DetectIcmpIdData on success
NULL on failure
Todo:
can ByteExtractStringUint16 do this?
Definition at line 156 of file detect-icmp-id.c.
References ByteExtractStringUint16(), DetectIcmpIdFree(), DetectIcmpIdData_::id, MAX_SUBSTRINGS, SC_ERR_INVALID_ARGUMENT, SC_ERR_PCRE_GET_SUBSTRING, SC_ERR_PCRE_MATCH, SCFree, SCLogError, SCMalloc, and unlikely.
void DetectIcmpIdRegister (void)
Registration function for icode: icmp_id.
Definition at line 53 of file detect-icmp-id.c.
References SigTableElmt_::desc, DETECT_ICMP_ID, DetectIcmpIdFree(), DetectIcmpIdMatch(), DetectIcmpIdRegisterTests(), SigTableElmt_::Free, SigTableElmt_::Match, SigTableElmt_::name, PARSE_REGEX, SigTableElmt_::RegisterTests, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogError, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
void DetectIcmpIdRegisterTests (void)
Definition at line 488 of file detect-icmp-id.c.
Referenced by DetectIcmpIdRegister().