suricata: src/flow-bit.h File Reference
flow-bit.h File Reference
#include "flow.h"
#include "util-var.h"
Data Structures
struct FlowBit_
Typedefs
typedef struct FlowBit_ FlowBit
Functions
void FlowBitFree (FlowBit *)
void FlowBitRegisterTests (void)
void FlowBitSetNoLock (Flow *, uint16_t)
void FlowBitSet (Flow *, uint16_t)
void FlowBitUnsetNoLock (Flow *, uint16_t)
void FlowBitUnset (Flow *, uint16_t)
void FlowBitToggleNoLock (Flow *, uint16_t)
void FlowBitToggle (Flow *, uint16_t)
int FlowBitIsset (Flow *, uint16_t)
int FlowBitIsnotset (Flow *, uint16_t)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file flow-bit.h.
Typedef Documentation
typedef struct FlowBit_ FlowBit
Function Documentation
void FlowBitFree (FlowBit *)
Definition at line 181 of file flow-bit.c.
References SCFree, SCMutexLock, and SCMutexUnlock.
Referenced by GenericVarFree().
int FlowBitIsnotset (Flow * , uint16_t)
Definition at line 167 of file flow-bit.c.
References FLOWLOCK_RDLOCK, and FLOWLOCK_UNLOCK.
int FlowBitIsset (Flow * , uint16_t)
Definition at line 153 of file flow-bit.c.
References FLOWLOCK_RDLOCK, and FLOWLOCK_UNLOCK.
void FlowBitRegisterTests (void)
Definition at line 467 of file flow-bit.c.
Referenced by RunUnittests().
void FlowBitSet (Flow * , uint16_t)
Definition at line 114 of file flow-bit.c.
References FlowBitSetNoLock(), FLOWLOCK_UNLOCK, and FLOWLOCK_WRLOCK.
void FlowBitSetNoLock (Flow * , uint16_t)
Definition at line 106 of file flow-bit.c.
Referenced by FlowBitSet().
void FlowBitToggle (Flow * , uint16_t)
Definition at line 146 of file flow-bit.c.
References FlowBitToggleNoLock(), FLOWLOCK_UNLOCK, and FLOWLOCK_WRLOCK.
void FlowBitToggleNoLock (Flow * , uint16_t)
Definition at line 136 of file flow-bit.c.
Referenced by FlowBitToggle().
void FlowBitUnset (Flow * , uint16_t)
Definition at line 129 of file flow-bit.c.
References FlowBitUnsetNoLock(), FLOWLOCK_UNLOCK, and FLOWLOCK_WRLOCK.
void FlowBitUnsetNoLock (Flow * , uint16_t)
Definition at line 121 of file flow-bit.c.
Referenced by FlowBitUnset().