suricata: src/flow-timeout.c File Reference
flow-timeout.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "conf.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "runmodes.h"
#include "util-random.h"
#include "util-time.h"
#include "flow.h"
#include "flow-queue.h"
#include "flow-hash.h"
#include "flow-util.h"
#include "flow-var.h"
#include "flow-private.h"
#include "flow-manager.h"
#include "pkt-var.h"
#include "host.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-byte.h"
#include "util-debug.h"
#include "util-privs.h"
#include "detect.h"
#include "detect-engine-state.h"
#include "stream.h"
#include "app-layer-parser.h"
#include "app-layer.h"
#include "util-profiling.h"
Functions
int FlowForceReassemblyNeedReassembly (Flow *f, int *server, int *client)
Check if a flow needs forced reassembly, or any other processing.
int FlowForceReassemblyForFlow (Flow *f, int server, int client)
void FlowForceReassembly (void)
Force reassembly for all the flows that have unprocessed segments.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file flow-timeout.c.
Function Documentation
void FlowForceReassembly (void)
Force reassembly for all the flows that have unprocessed segments.
Definition at line 566 of file flow-timeout.c.
Referenced by main().
int FlowForceReassemblyForFlow (Flow * f, int server, int client)
< null terminated array of packets
Definition at line 358 of file flow-timeout.c.
References BUG_ON, Packet_::flow, PKT_SET_SRC, PKT_SRC_FFR, Flow_::protoctx, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_REASSEMBLY, Flow_::thread_id, and TmqhOutputPacketpool().
int FlowForceReassemblyNeedReassembly (Flow * f, int * server, int * client)
Check if a flow needs forced reassembly, or any other processing.
Parameters
f LOCKED flow
server ptr to int that should be set to 1 or 2 if we return 1
client ptr to int that should be set to 1 or 2 if we return 1
Return values
0 no
1 yes
Definition at line 287 of file flow-timeout.c.
References Flow_::alparser, Flow_::alproto, ALPROTO_UNKNOWN, Flow_::alstate, AppLayerParserGetTransactionActive(), AppLayerParserGetTxCnt(), AppLayerParserProtocolSupportsTxs(), Flow_::proto, Flow_::protoctx, SCReturnInt, TcpSession_::state, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_REASSEMBLY, STREAM_HAS_UNPROCESSED_SEGMENTS_NONE, STREAM_TOCLIENT, STREAM_TOSERVER, TCP_CLOSED, and TCP_ESTABLISHED.