suricata: src/flow-var.h File Reference
flow-var.h File Reference
#include "flow.h"
#include "util-var.h"
Data Structures
struct FlowVarTypeStr
struct FlowVarTypeInt_
struct FlowVar_
Macros
#define FLOWVAR_TYPE_STR 1
#define FLOWVAR_TYPE_INT 2
Typedefs
typedef struct FlowVarTypeStr FlowVarTypeStr
typedef struct FlowVarTypeInt_ FlowVarTypeInt
typedef struct FlowVar_ FlowVar
Functions
void FlowVarAddStrNoLock (Flow *, uint16_t, uint8_t *, uint16_t)
void FlowVarAddStr (Flow *, uint16_t, uint8_t *, uint16_t)
void FlowVarAddIntNoLock (Flow *, uint16_t, uint32_t)
void FlowVarAddInt (Flow *, uint16_t, uint32_t)
FlowVar * FlowVarGet (Flow *, uint16_t)
get the flowvar with index 'idx' from the flow
void FlowVarFree (FlowVar *)
void FlowVarPrint (GenericVar *)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file flow-var.h.
Macro Definition Documentation
#define FLOWVAR_TYPE_INT 2
Definition at line 34 of file flow-var.h.
Referenced by DetectFlowintMatch(), FlowVarAddIntNoLock(), and FlowVarPrint().
#define FLOWVAR_TYPE_STR 1
Available data types for Flowvars
Definition at line 33 of file flow-var.h.
Referenced by FlowVarAddStrNoLock(), FlowVarFree(), and FlowVarPrint().
Typedef Documentation
typedef struct FlowVar_ FlowVar
Generic Flowvar Structure
typedef struct FlowVarTypeInt_ FlowVarTypeInt
Struct used to hold the integer data type for flowvars
typedef struct FlowVarTypeStr FlowVarTypeStr
Struct used to hold the string data type for flowvars
Function Documentation
void FlowVarAddInt (Flow * , uint16_t , uint32_t)
Definition at line 118 of file flow-var.c.
References FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, and FlowVarAddIntNoLock().
void FlowVarAddIntNoLock (Flow * , uint16_t , uint32_t)
Definition at line 97 of file flow-var.c.
References FlowVar_::data, FlowVar_::datatype, DETECT_FLOWVAR, Flow_::flowvar, FLOWVAR_TYPE_INT, FlowVarGet(), FlowVar_::fv_int, GenericVarAppend(), FlowVar_::idx, FlowVar_::next, SCMalloc, FlowVar_::type, unlikely, and FlowVarTypeInt_::value.
Referenced by DetectFlowintMatch(), and FlowVarAddInt().
void FlowVarAddStr (Flow * , uint16_t , uint8_t * , uint16_t)
Definition at line 89 of file flow-var.c.
References FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, and FlowVarAddStrNoLock().
Referenced by DetectFlowvarProcessListInternal().
void FlowVarAddStrNoLock (Flow * , uint16_t , uint8_t * , uint16_t)
Flowvar Interface API
Definition at line 67 of file flow-var.c.
References FlowVar_::data, FlowVar_::datatype, DETECT_FLOWVAR, Flow_::flowvar, FLOWVAR_TYPE_STR, FlowVarGet(), FlowVar_::fv_str, GenericVarAppend(), FlowVar_::idx, FlowVar_::next, SCMalloc, FlowVar_::type, unlikely, FlowVarTypeStr::value, and FlowVarTypeStr::value_len.
Referenced by DetectFlowvarProcessListInternal(), and FlowVarAddStr().
void FlowVarFree (FlowVar *)
Definition at line 125 of file flow-var.c.
References FlowVar_::data, FlowVar_::datatype, FLOWVAR_TYPE_STR, FlowVar_::fv_str, SCFree, and FlowVarTypeStr::value.
Referenced by GenericVarFree().
FlowVar* FlowVarGet (Flow * f, uint16_t idx)
get the flowvar with index 'idx' from the flow
Note
flow is not locked by this function, caller is responsible
Definition at line 54 of file flow-var.c.
References DETECT_FLOWVAR, Flow_::flowvar, GenericVar_::idx, GenericVar_::next, and GenericVar_::type.
Referenced by DetectFlowintMatch(), DetectFlowvarMatch(), FlowVarAddIntNoLock(), and FlowVarAddStrNoLock().
void FlowVarPrint (GenericVar *)
Definition at line 137 of file flow-var.c.
References FlowVar_::data, FlowVar_::datatype, DETECT_FLOWINT, DETECT_FLOWVAR, FLOWVAR_TYPE_INT, FLOWVAR_TYPE_STR, FlowVarPrint(), FlowVar_::fv_int, FlowVar_::fv_str, FlowVar_::idx, GenericVar_::next, SCLogDebug, SCLogDebugEnabled(), GenericVar_::type, FlowVarTypeStr::value, FlowVarTypeInt_::value, and FlowVarTypeStr::value_len.
Referenced by FlowVarPrint().