suricata: src/flow-manager.c File Reference
flow-manager.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "conf.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "runmodes.h"
#include "util-random.h"
#include "util-time.h"
#include "flow.h"
#include "flow-queue.h"
#include "flow-hash.h"
#include "flow-util.h"
#include "flow-var.h"
#include "flow-private.h"
#include "flow-timeout.h"
#include "flow-manager.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-byte.h"
#include "util-debug.h"
#include "util-privs.h"
#include "util-signal.h"
#include "threads.h"
#include "detect.h"
#include "detect-engine-state.h"
#include "stream.h"
#include "app-layer-parser.h"
#include "host-timeout.h"
#include "defrag-timeout.h"
#include "ippair-timeout.h"
#include "output-flow.h"
Data Structures
struct FlowTimeoutCounters_
struct FlowManagerThreadData_
struct FlowRecyclerThreadData_
Macros
#define FLOW_NORMAL_MODE_UPDATE_DELAY_SEC 1
#define FLOW_NORMAL_MODE_UPDATE_DELAY_NSEC 0
#define FLOW_EMERG_MODE_UPDATE_DELAY_SEC 0
#define FLOW_EMERG_MODE_UPDATE_DELAY_NSEC 100000
#define NEW_FLOW_COUNT_COND 10
#define THREAD_KILL_MAX_WAIT_TIME 60
#define WAIT_TIME 100
#define THREAD_KILL_MAX_WAIT_TIME 60
#define WAIT_TIME 100
Typedefs
typedef struct FlowTimeoutCounters_ FlowTimeoutCounters
typedef struct
FlowManagerThreadData_ FlowManagerThreadData
typedef struct
FlowRecyclerThreadData_ FlowRecyclerThreadData
Functions
SC_ATOMIC_DECLARE (uint32_t, flowmgr_cnt)
SC_ATOMIC_DECLARE (uint32_t, flowrec_cnt)
SC_ATOMIC_EXTERN (unsigned int, flow_flags)
void FlowDisableFlowManagerThread (void)
Used to disable flow manager thread(s).
void FlowManagerThreadSpawn ()
spawn the flow manager thread
int FlowRecyclerReadyToShutdown (void)
void FlowRecyclerThreadSpawn ()
spawn the flow recycler thread
void FlowDisableFlowRecyclerThread (void)
Used to disable flow recycler thread(s).
void TmModuleFlowManagerRegister (void)
void TmModuleFlowRecyclerRegister (void)
void FlowMgrRegisterTests (void)
Function to register the Flow Unitests.
Variables
int run_mode
int g_detect_disabled
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file flow-manager.c.
Macro Definition Documentation
#define FLOW_EMERG_MODE_UPDATE_DELAY_NSEC 100000
Definition at line 90 of file flow-manager.c.
#define FLOW_EMERG_MODE_UPDATE_DELAY_SEC 0
Definition at line 89 of file flow-manager.c.
#define FLOW_NORMAL_MODE_UPDATE_DELAY_NSEC 0
Definition at line 87 of file flow-manager.c.
#define FLOW_NORMAL_MODE_UPDATE_DELAY_SEC 1
Definition at line 86 of file flow-manager.c.
#define NEW_FLOW_COUNT_COND 10
Definition at line 91 of file flow-manager.c.
#define THREAD_KILL_MAX_WAIT_TIME 60
Referenced by FlowDisableFlowManagerThread(), FlowDisableFlowRecyclerThread(), TmThreadDisablePacketThreads(), and TmThreadDisableReceiveThreads().
#define THREAD_KILL_MAX_WAIT_TIME 60
#define WAIT_TIME 100
Referenced by FlowDisableFlowManagerThread(), FlowDisableFlowRecyclerThread(), TmThreadDisablePacketThreads(), and TmThreadDisableReceiveThreads().
#define WAIT_TIME 100
Typedef Documentation
typedef struct FlowManagerThreadData_ FlowManagerThreadData
typedef struct FlowRecyclerThreadData_ FlowRecyclerThreadData
typedef struct FlowTimeoutCounters_ FlowTimeoutCounters
Function Documentation
void FlowDisableFlowManagerThread (void)
Used to disable flow manager thread(s).
Todo:
Kinda hackish since it uses the tv name to identify flow manager thread. We need an all weather identification scheme.
Definition at line 106 of file flow-manager.c.
References flow_manager_ctrl_cond, ThreadVars_::name, ThreadVars_::next, SC_ATOMIC_SET, SC_ERR_FATAL, SCCtrlCondSignal, SCLogError, SCMutexLock, SCMutexUnlock, THREAD_KILL_MAX_WAIT_TIME, THV_KILL, THV_RUNNING_DONE, TmThreadsCheckFlag(), TmThreadsSetFlag(), tv_root, tv_root_lock, TVT_MGMT, and WAIT_TIME.
Referenced by main().
void FlowDisableFlowRecyclerThread (void)
Used to disable flow recycler thread(s).
Note
this should only be called when the flow manager is already gone
Todo:
Kinda hackish since it uses the tv name to identify flow recycler thread. We need an all weather identification scheme.
Definition at line 918 of file flow-manager.c.
References flow_recycler_ctrl_cond, FlowRecyclerReadyToShutdown(), ThreadVars_::name, ThreadVars_::next, SC_ATOMIC_SET, SC_ERR_FATAL, SCCtrlCondSignal, SCLogError, SCMutexLock, SCMutexUnlock, THREAD_KILL_MAX_WAIT_TIME, THV_KILL, THV_RUNNING_DONE, TmThreadsCheckFlag(), TmThreadsSetFlag(), tv_root, tv_root_lock, TVT_MGMT, and WAIT_TIME.
Referenced by main().
void FlowManagerThreadSpawn (void)
spawn the flow manager thread
Definition at line 709 of file flow-manager.c.
References BUG_ON, ConfGetInt(), flow_manager_ctrl_cond, flow_manager_ctrl_mutex, SC_ERR_INVALID_ARGUMENTS, SCCtrlCondInit, SCCtrlMutexInit, SCLogError, SCLogInfo, StatsRegisterGlobalCounter(), TM_ECODE_OK, TmThreadCreateMgmtThreadByName(), and TmThreadSpawn().
Referenced by main().
void FlowMgrRegisterTests (void)
Function to register the Flow Unitests.
Definition at line 1276 of file flow-manager.c.
Referenced by FlowRegisterTests().
int FlowRecyclerReadyToShutdown (void)
Definition at line 858 of file flow-manager.c.
References flow_recycle_q, FQLOCK_LOCK, FQLOCK_UNLOCK, and FlowQueue_::len.
Referenced by FlowDisableFlowRecyclerThread().
void FlowRecyclerThreadSpawn (void)
spawn the flow recycler thread
Definition at line 869 of file flow-manager.c.
References BUG_ON, ConfGetInt(), flow_recycler_ctrl_cond, flow_recycler_ctrl_mutex, SC_ERR_INVALID_ARGUMENTS, SCCtrlCondInit, SCCtrlMutexInit, SCLogError, SCLogInfo, TM_ECODE_OK, TmThreadCreateMgmtThreadByName(), and TmThreadSpawn().
Referenced by main().
SC_ATOMIC_DECLARE (uint32_t , flowmgr_cnt)
SC_ATOMIC_DECLARE (uint32_t , flowrec_cnt)
SC_ATOMIC_EXTERN (unsigned int, flow_flags)
void TmModuleFlowManagerRegister (void)
Definition at line 978 of file flow-manager.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Management, TmModule_::name, SC_ATOMIC_INIT, SCLogDebug, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_MANAGEMENT_TM, TMM_FLOWMANAGER, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleFlowRecyclerRegister (void)
Definition at line 992 of file flow-manager.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Management, TmModule_::name, SC_ATOMIC_INIT, SCLogDebug, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_MANAGEMENT_TM, TMM_FLOWRECYCLER, and tmm_modules.
Referenced by RegisterAllModules().
Variable Documentation
int g_detect_disabled
global indicating if detection is enabled
Definition at line 236 of file suricata.c.
int run_mode
Run mode selected
Definition at line 222 of file suricata.c.