suricata: src/flow-queue.c File Reference
flow-queue.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "flow-private.h"
#include "flow-queue.h"
#include "flow-util.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-print.h"
Functions
FlowQueue * FlowQueueNew ()
FlowQueue * FlowQueueInit (FlowQueue *q)
void FlowQueueDestroy (FlowQueue *q)
Destroy a flow queue.
void FlowEnqueue (FlowQueue *q, Flow *f)
add a flow to a queue
Flow * FlowDequeue (FlowQueue *q)
remove a flow from the queue
void FlowMoveToSpare (Flow *f)
Transfer a flow from a queue to the spare queue.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Flow queue handler functions
Definition in file flow-queue.c.
Function Documentation
Flow* FlowDequeue (FlowQueue * q)
remove a flow from the queue
Parameters
q queue
Return values
f flow or NULL if empty list.
Definition at line 105 of file flow-queue.c.
References FlowQueue_::bot, BUG_ON, FQLOCK_LOCK, FQLOCK_UNLOCK, FlowQueue_::len, Flow_::lnext, Flow_::lprev, and FlowQueue_::top.
Referenced by FlowShutdown(), and FlowUpdateSpareFlows().
void FlowEnqueue (FlowQueue * q, Flow * f)
add a flow to a queue
Parameters
q queue
f flow
Definition at line 72 of file flow-queue.c.
References FlowQueue_::bot, BUG_ON, FQLOCK_LOCK, FQLOCK_UNLOCK, FlowQueue_::len, Flow_::lnext, Flow_::lprev, and FlowQueue_::top.
Referenced by FlowInitConfig(), and FlowUpdateSpareFlows().
void FlowMoveToSpare (Flow * f)
Transfer a flow from a queue to the spare queue.
Parameters
f the flow to be transfered
q the source queue, where the flow will be removed. This queue is locked.
Note
spare queue needs locking
Definition at line 146 of file flow-queue.c.
References FlowQueue_::bot, flow_spare_q, FQLOCK_LOCK, FQLOCK_UNLOCK, FlowQueue_::len, Flow_::lnext, Flow_::lprev, and FlowQueue_::top.
void FlowQueueDestroy (FlowQueue * q)
Destroy a flow queue.
Parameters
q the flow queue to destroy
Definition at line 61 of file flow-queue.c.
References FQLOCK_DESTROY.
Referenced by FlowShutdown().
FlowQueue* FlowQueueInit (FlowQueue * q)
Definition at line 47 of file flow-queue.c.
References FQLOCK_INIT.
Referenced by FlowInitConfig(), and FlowQueueNew().
FlowQueue* FlowQueueNew ()
Definition at line 36 of file flow-queue.c.
References FlowQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.