suricata: src/flow-util.c File Reference
flow-util.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "flow.h"
#include "flow-private.h"
#include "flow-util.h"
#include "flow-var.h"
#include "app-layer.h"
#include "util-var.h"
#include "util-debug.h"
#include "flow-storage.h"
#include "detect.h"
#include "detect-engine-state.h"
Functions
Flow * FlowAlloc (void)
allocate a flow
void FlowFree (Flow *f)
cleanup & free the memory of a flow
uint8_t FlowGetProtoMapping (uint8_t proto)
Function to map the protocol to the defined FLOW_PROTO_* enumeration.
uint8_t FlowGetReverseProtoMapping (uint8_t rproto)
void FlowInit (Flow *f, const Packet *p)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Flow utility functions
Definition in file flow-util.c.
Function Documentation
Flow* FlowAlloc (void)
allocate a flow
We check against the memuse counter. If it passes that check we increment the counter first, then we try to alloc.
Return values
f the flow or NULL on out of memory
Definition at line 49 of file flow-util.c.
References FLOW_CHECK_MEMCAP, FLOW_INITIALIZE, FlowStorageSize(), SC_ATOMIC_ADD, SC_ATOMIC_SUB, SCMalloc, and unlikely.
Referenced by FlowInitConfig(), and FlowUpdateSpareFlows().
void FlowFree (Flow * f)
cleanup & free the memory of a flow
Parameters
f flow to clear & destroy
Definition at line 77 of file flow-util.c.
References FLOW_DESTROY, FlowStorageSize(), SC_ATOMIC_SUB, and SCFree.
Referenced by FlowShutdown(), and FlowUpdateSpareFlows().
uint8_t FlowGetProtoMapping (uint8_t proto)
Function to map the protocol to the defined FLOW_PROTO_* enumeration.
Parameters
proto protocol which is needed to be mapped
Definition at line 92 of file flow-util.c.
References FLOW_PROTO_DEFAULT, FLOW_PROTO_ICMP, FLOW_PROTO_SCTP, FLOW_PROTO_TCP, and FLOW_PROTO_UDP.
Referenced by AppLayerParserDestroyProtocolParserLocalStorage(), AppLayerParserGetEventInfo(), AppLayerParserGetEventsByTx(), AppLayerParserGetFiles(), AppLayerParserGetFirstDataDir(), AppLayerParserGetProtocolParserLocalStorage(), AppLayerParserGetStateProgress(), AppLayerParserGetStateProgressCompletionStatus(), AppLayerParserGetTransactionActive(), AppLayerParserGetTx(), AppLayerParserGetTxCnt(), AppLayerParserGetTxDetectState(), AppLayerParserHasDecoderEvents(), AppLayerParserHasTxDetectState(), AppLayerParserParse(), AppLayerParserProtocolHasLogger(), AppLayerParserProtocolIsTxAware(), AppLayerParserProtocolIsTxEventAware(), AppLayerParserProtocolSupportsTxs(), AppLayerParserRegisterDetectStateFuncs(), AppLayerParserRegisterGetEventInfo(), AppLayerParserRegisterGetEventsFunc(), AppLayerParserRegisterGetFilesFunc(), AppLayerParserRegisterGetStateProgressCompletionStatus(), AppLayerParserRegisterGetStateProgressFunc(), AppLayerParserRegisterGetTx(), AppLayerParserRegisterGetTxCnt(), AppLayerParserRegisterHasEventsFunc(), AppLayerParserRegisterLocalStorageFunc(), AppLayerParserRegisterLogger(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerParserRegisterTruncateFunc(), AppLayerParserRegisterTxFreeFunc(), AppLayerParserSetTxDetectState(), AppLayerParserStateCleanup(), AppLayerParserStreamTruncated(), AppLayerParserSupportsTxDetectState(), AppLayerTransactionGetActiveDetectLog(), DetectEngineRegisterAppInspectionEngine(), FlowInit(), FlowSetProtoEmergencyTimeout(), FlowSetProtoFreeFunc(), FlowSetProtoTimeout(), and FlowShutdown().
uint8_t FlowGetReverseProtoMapping (uint8_t rproto)
Definition at line 108 of file flow-util.c.
References FLOW_PROTO_ICMP, FLOW_PROTO_SCTP, FLOW_PROTO_TCP, and FLOW_PROTO_UDP.
Referenced by AppLayerParserThreadCtxAlloc(), and AppLayerParserThreadCtxFree().
void FlowInit (Flow * f, const Packet * p)
Definition at line 126 of file flow-util.c.
References Flow_::code, Packet_::code, COPY_TIMESTAMP, Flow_::dp, Flow_::dst, Flow_::flags, FLOW_IPV4, FLOW_IPV6, FLOW_SET_IPV4_DST_ADDR_FROM_PACKET, FLOW_SET_IPV4_SRC_ADDR_FROM_PACKET, FLOW_SET_IPV6_DST_ADDR_FROM_PACKET, FLOW_SET_IPV6_SRC_ADDR_FROM_PACKET, FlowGetProtoMapping(), Packet_::icmpv4h, Packet_::icmpv6h, PKT_IS_IPV4, PKT_IS_IPV6, Flow_::proto, Packet_::proto, Flow_::protomap, Flow_::recursion_level, Packet_::recursion_level, SCEnter, SCLogDebug, SCReturn, Packet_::sctph, SET_SCTP_DST_PORT, SET_SCTP_SRC_PORT, SET_TCP_DST_PORT, SET_TCP_SRC_PORT, SET_UDP_DST_PORT, SET_UDP_SRC_PORT, Flow_::sp, Flow_::src, Flow_::startts, Packet_::tcph, Packet_::ts, Flow_::type, Packet_::type, Packet_::udph, Flow_::vlan_id, and Packet_::vlan_id.
Referenced by FlowGetFlowFromHash(), and FlowGetFlowFromHashByPacket().