suricata: src/flow-manager.h File Reference
flow-manager.h File Reference
Macros
#define FlowWakeupFlowManagerThread() SCCtrlCondSignal(&flow_manager_ctrl_cond)
#define FlowWakeupFlowRecyclerThread() SCCtrlCondSignal(&flow_recycler_ctrl_cond)
Functions
void FlowManagerThreadSpawn (void)
spawn the flow manager thread
void FlowDisableFlowManagerThread (void)
Used to disable flow manager thread(s).
void FlowMgrRegisterTests (void)
Function to register the Flow Unitests.
void FlowRecyclerThreadSpawn (void)
spawn the flow recycler thread
void FlowDisableFlowRecyclerThread (void)
Used to disable flow recycler thread(s).
void TmModuleFlowManagerRegister (void)
void TmModuleFlowRecyclerRegister (void)
Variables
SCCtrlCondT flow_manager_ctrl_cond
SCCtrlMutex flow_manager_ctrl_mutex
SCCtrlCondT flow_recycler_ctrl_cond
SCCtrlMutex flow_recycler_ctrl_mutex
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file flow-manager.h.
Macro Definition Documentation
#define FlowWakeupFlowManagerThread () SCCtrlCondSignal(&flow_manager_ctrl_cond)
Definition at line 30 of file flow-manager.h.
Referenced by DecodePcapFile().
#define FlowWakeupFlowRecyclerThread () SCCtrlCondSignal(&flow_recycler_ctrl_cond)
Definition at line 39 of file flow-manager.h.
Function Documentation
void FlowDisableFlowManagerThread (void)
Used to disable flow manager thread(s).
Todo:
Kinda hackish since it uses the tv name to identify flow manager thread. We need an all weather identification scheme.
Definition at line 106 of file flow-manager.c.
References flow_manager_ctrl_cond, ThreadVars_::name, ThreadVars_::next, SC_ATOMIC_SET, SC_ERR_FATAL, SCCtrlCondSignal, SCLogError, SCMutexLock, SCMutexUnlock, THREAD_KILL_MAX_WAIT_TIME, THV_KILL, THV_RUNNING_DONE, TmThreadsCheckFlag(), TmThreadsSetFlag(), tv_root, tv_root_lock, TVT_MGMT, and WAIT_TIME.
Referenced by main().
void FlowDisableFlowRecyclerThread (void)
Used to disable flow recycler thread(s).
Note
this should only be called when the flow manager is already gone
Todo:
Kinda hackish since it uses the tv name to identify flow recycler thread. We need an all weather identification scheme.
Definition at line 918 of file flow-manager.c.
References flow_recycler_ctrl_cond, FlowRecyclerReadyToShutdown(), ThreadVars_::name, ThreadVars_::next, SC_ATOMIC_SET, SC_ERR_FATAL, SCCtrlCondSignal, SCLogError, SCMutexLock, SCMutexUnlock, THREAD_KILL_MAX_WAIT_TIME, THV_KILL, THV_RUNNING_DONE, TmThreadsCheckFlag(), TmThreadsSetFlag(), tv_root, tv_root_lock, TVT_MGMT, and WAIT_TIME.
Referenced by main().
void FlowManagerThreadSpawn (void)
spawn the flow manager thread
Definition at line 709 of file flow-manager.c.
References BUG_ON, ConfGetInt(), flow_manager_ctrl_cond, flow_manager_ctrl_mutex, SC_ERR_INVALID_ARGUMENTS, SCCtrlCondInit, SCCtrlMutexInit, SCLogError, SCLogInfo, StatsRegisterGlobalCounter(), TM_ECODE_OK, TmThreadCreateMgmtThreadByName(), and TmThreadSpawn().
Referenced by main().
void FlowMgrRegisterTests (void)
Function to register the Flow Unitests.
Definition at line 1276 of file flow-manager.c.
Referenced by FlowRegisterTests().
void FlowRecyclerThreadSpawn (void)
spawn the flow recycler thread
Definition at line 869 of file flow-manager.c.
References BUG_ON, ConfGetInt(), flow_recycler_ctrl_cond, flow_recycler_ctrl_mutex, SC_ERR_INVALID_ARGUMENTS, SCCtrlCondInit, SCCtrlMutexInit, SCLogError, SCLogInfo, TM_ECODE_OK, TmThreadCreateMgmtThreadByName(), and TmThreadSpawn().
Referenced by main().
void TmModuleFlowManagerRegister (void)
Definition at line 978 of file flow-manager.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Management, TmModule_::name, SC_ATOMIC_INIT, SCLogDebug, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_MANAGEMENT_TM, TMM_FLOWMANAGER, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleFlowRecyclerRegister (void)
Definition at line 992 of file flow-manager.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Management, TmModule_::name, SC_ATOMIC_INIT, SCLogDebug, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_MANAGEMENT_TM, TMM_FLOWRECYCLER, and tmm_modules.
Referenced by RegisterAllModules().
Variable Documentation
SCCtrlCondT flow_manager_ctrl_cond
flow manager scheduling condition
Definition at line 28 of file flow-manager.h.
Referenced by FlowDisableFlowManagerThread(), and FlowManagerThreadSpawn().
SCCtrlMutex flow_manager_ctrl_mutex
Definition at line 29 of file flow-manager.h.
Referenced by FlowManagerThreadSpawn().
SCCtrlCondT flow_recycler_ctrl_cond
flow recycler scheduling condition
Definition at line 37 of file flow-manager.h.
Referenced by FlowDisableFlowRecyclerThread(), and FlowRecyclerThreadSpawn().
SCCtrlMutex flow_recycler_ctrl_mutex
Definition at line 38 of file flow-manager.h.
Referenced by FlowRecyclerThreadSpawn().