suricata: src/flow-bit.c File Reference
flow-bit.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "flow-bit.h"
#include "flow.h"
#include "flow-util.h"
#include "flow-private.h"
#include "detect.h"
#include "util-var.h"
#include "util-debug.h"
#include "util-unittest.h"
Functions
void FlowBitSetNoLock (Flow *f, uint16_t idx)
void FlowBitSet (Flow *f, uint16_t idx)
void FlowBitUnsetNoLock (Flow *f, uint16_t idx)
void FlowBitUnset (Flow *f, uint16_t idx)
void FlowBitToggleNoLock (Flow *f, uint16_t idx)
void FlowBitToggle (Flow *f, uint16_t idx)
int FlowBitIsset (Flow *f, uint16_t idx)
int FlowBitIsnotset (Flow *f, uint16_t idx)
void FlowBitFree (FlowBit *fb)
void FlowBitRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements per flow bits. Actually, not a bit, but called that way because of Snort's flowbits. It's a binary storage.
Todo:
move away from a linked list implementation
use different datatypes, such as string, int, etc.
have more than one instance of the same var, and be able to match on a specific one, or one all at a time. So if a certain capture matches multiple times, we can operate on all of them.
Definition in file flow-bit.c.
Function Documentation
void FlowBitFree (FlowBit * fb)
Definition at line 181 of file flow-bit.c.
References SCFree, SCMutexLock, and SCMutexUnlock.
Referenced by GenericVarFree().
int FlowBitIsnotset (Flow * f, uint16_t idx)
Definition at line 167 of file flow-bit.c.
References FLOWLOCK_RDLOCK, and FLOWLOCK_UNLOCK.
int FlowBitIsset (Flow * f, uint16_t idx)
Definition at line 153 of file flow-bit.c.
References FLOWLOCK_RDLOCK, and FLOWLOCK_UNLOCK.
void FlowBitRegisterTests (void)
Definition at line 467 of file flow-bit.c.
Referenced by RunUnittests().
void FlowBitSet (Flow * f, uint16_t idx)
Definition at line 114 of file flow-bit.c.
References FlowBitSetNoLock(), FLOWLOCK_UNLOCK, and FLOWLOCK_WRLOCK.
void FlowBitSetNoLock (Flow * f, uint16_t idx)
Definition at line 106 of file flow-bit.c.
Referenced by FlowBitSet().
void FlowBitToggle (Flow * f, uint16_t idx)
Definition at line 146 of file flow-bit.c.
References FlowBitToggleNoLock(), FLOWLOCK_UNLOCK, and FLOWLOCK_WRLOCK.
void FlowBitToggleNoLock (Flow * f, uint16_t idx)
Definition at line 136 of file flow-bit.c.
Referenced by FlowBitToggle().
void FlowBitUnset (Flow * f, uint16_t idx)
Definition at line 129 of file flow-bit.c.
References FlowBitUnsetNoLock(), FLOWLOCK_UNLOCK, and FLOWLOCK_WRLOCK.
void FlowBitUnsetNoLock (Flow * f, uint16_t idx)
Definition at line 121 of file flow-bit.c.
Referenced by FlowBitUnset().