suricata: src/flow-storage.h File Reference
flow-storage.h File Reference
#include "util-storage.h"
#include "flow.h"
Functions
unsigned int FlowStorageSize (void)
void * FlowGetStorageById (Flow *h, int id)
int FlowSetStorageById (Flow *h, int id, void *ptr)
void * FlowAllocStorageById (Flow *h, int id)
void FlowFreeStorageById (Flow *h, int id)
void FlowFreeStorage (Flow *h)
void RegisterFlowStorageTests (void)
int FlowStorageRegister (const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Flow wrapper around storage api
Definition in file flow-storage.h.
Function Documentation
void* FlowAllocStorageById (Flow * h, int id)
Definition at line 49 of file flow-storage.c.
References STORAGE_FLOW, and StorageAllocByIdPrealloc().
void FlowFreeStorage (Flow * h)
Definition at line 59 of file flow-storage.c.
References FlowStorageSize(), STORAGE_FLOW, and StorageFreeAll().
Referenced by FlowClearMemory().
void FlowFreeStorageById (Flow * h, int id)
Definition at line 54 of file flow-storage.c.
References STORAGE_FLOW, and StorageFreeById().
void* FlowGetStorageById (Flow * h, int id)
Definition at line 39 of file flow-storage.c.
References STORAGE_FLOW, and StorageGetById().
Referenced by TagFlowAdd().
int FlowSetStorageById (Flow * h, int id, void * ptr)
Definition at line 44 of file flow-storage.c.
References STORAGE_FLOW, and StorageSetById().
Referenced by TagFlowAdd().
int FlowStorageRegister (const char * name, const unsigned int size, void *(*)(unsigned int) Alloc, void(*)(void *) Free)
Definition at line 65 of file flow-storage.c.
References STORAGE_FLOW, and StorageRegister().
Referenced by TagInitCtx().
unsigned int FlowStorageSize (void)
Definition at line 34 of file flow-storage.c.
References STORAGE_FLOW, and StorageGetSize().
Referenced by FlowAlloc(), FlowFree(), FlowFreeStorage(), and FlowInitConfig().
void RegisterFlowStorageTests (void)
Definition at line 289 of file flow-storage.c.
Referenced by FlowRegisterTests().