suricata: src/flow-util.h File Reference
flow-util.h File Reference
#include "detect-engine-state.h"
#include "tmqh-flow.h"
Macros
#define COPY_TIMESTAMP(src, dst) ((dst)->tv_sec = (src)->tv_sec, (dst)->tv_usec = (src)->tv_usec)
#define RESET_COUNTERS(f)
#define FLOW_INITIALIZE(f)
#define FLOW_RECYCLE(f)
macro to recycle a flow before it goes into the spare queue for reuse.
#define FLOW_DESTROY(f)
#define FLOW_CHECK_MEMCAP(size) ((((uint64_t)SC_ATOMIC_GET(flow_memuse) + (uint64_t)(size)) <= flow_config.memcap))
check if a memory alloc would fit in the memcap
Functions
Flow * FlowAlloc (void)
allocate a flow
Flow * FlowAllocDirect (void)
void FlowFree (Flow *)
cleanup & free the memory of a flow
uint8_t FlowGetProtoMapping (uint8_t)
Function to map the protocol to the defined FLOW_PROTO_* enumeration.
void FlowInit (Flow *, const Packet *)
uint8_t FlowGetReverseProtoMapping (uint8_t rproto)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file flow-util.h.
Macro Definition Documentation
#define COPY_TIMESTAMP (src, dst) ((dst)->tv_sec = (src)->tv_sec, (dst)->tv_usec = (src)->tv_usec)
Definition at line 30 of file flow-util.h.
Referenced by FlowGetFlowFromHash(), FlowGetFlowFromHashByPacket(), FlowInit(), and FlowLookupFlowFromHash().
#define FLOW_CHECK_MEMCAP (size) ((((uint64_t)SC_ATOMIC_GET(flow_memuse) + (uint64_t)(size)) <= flow_config.memcap))
check if a memory alloc would fit in the memcap
Parameters
size memory allocation size to check
Return values
1 it fits
0 no fit
Definition at line 142 of file flow-util.h.
Referenced by FlowAlloc(), and FlowInitConfig().
#define FLOW_DESTROY (f)
Value:
do { \
        FlowCleanupAppLayer((f)); \
        SC_ATOMIC_DESTROY((f)->flow_state); \
        SC_ATOMIC_DESTROY((f)->use_cnt); \
        \
        FLOWLOCK_DESTROY((f)); \
        if ((f)->de_state != NULL) { \
            DetectEngineStateFlowFree((f)->de_state); \
        } \
        GenericVarFree((f)->flowvar); \
        SC_ATOMIC_DESTROY((f)->autofp_tmqh_flow_qid);   \
    } while(0)
Definition at line 122 of file flow-util.h.
Referenced by FlowFree().
#define FLOW_INITIALIZE (f)
Definition at line 39 of file flow-util.h.
Referenced by FlowAlloc().
#define FLOW_RECYCLE (f)
macro to recycle a flow before it goes into the spare queue for reuse.
Note that the lnext, lprev, hnext, hprev fields are untouched, those are managed by the queueing code. Same goes for fb (FlowBucket ptr) field.
Definition at line 83 of file flow-util.h.
Referenced by FlowClearMemory().
#define RESET_COUNTERS (f)
Value:
do { \
        (f)->todstpktcnt = 0; \
        (f)->tosrcpktcnt = 0; \
        (f)->todstbytecnt = 0; \
        (f)->tosrcbytecnt = 0; \
    } while (0)
Definition at line 32 of file flow-util.h.
Function Documentation
Flow* FlowAlloc (void)
allocate a flow
We check against the memuse counter. If it passes that check we increment the counter first, then we try to alloc.
Return values
f the flow or NULL on out of memory
Definition at line 49 of file flow-util.c.
References FLOW_CHECK_MEMCAP, FLOW_INITIALIZE, FlowStorageSize(), SC_ATOMIC_ADD, SC_ATOMIC_SUB, SCMalloc, and unlikely.
Referenced by FlowInitConfig(), and FlowUpdateSpareFlows().
Flow* FlowAllocDirect (void)
void FlowFree (Flow * f)
cleanup & free the memory of a flow
Parameters
f flow to clear & destroy
Definition at line 77 of file flow-util.c.
References FLOW_DESTROY, FlowStorageSize(), SC_ATOMIC_SUB, and SCFree.
Referenced by FlowShutdown(), and FlowUpdateSpareFlows().
uint8_t FlowGetProtoMapping (uint8_t proto)
Function to map the protocol to the defined FLOW_PROTO_* enumeration.
Parameters
proto protocol which is needed to be mapped
Definition at line 92 of file flow-util.c.
References FLOW_PROTO_DEFAULT, FLOW_PROTO_ICMP, FLOW_PROTO_SCTP, FLOW_PROTO_TCP, and FLOW_PROTO_UDP.
Referenced by AppLayerParserDestroyProtocolParserLocalStorage(), AppLayerParserGetEventInfo(), AppLayerParserGetEventsByTx(), AppLayerParserGetFiles(), AppLayerParserGetFirstDataDir(), AppLayerParserGetProtocolParserLocalStorage(), AppLayerParserGetStateProgress(), AppLayerParserGetStateProgressCompletionStatus(), AppLayerParserGetTransactionActive(), AppLayerParserGetTx(), AppLayerParserGetTxCnt(), AppLayerParserGetTxDetectState(), AppLayerParserHasDecoderEvents(), AppLayerParserHasTxDetectState(), AppLayerParserParse(), AppLayerParserProtocolHasLogger(), AppLayerParserProtocolIsTxAware(), AppLayerParserProtocolIsTxEventAware(), AppLayerParserProtocolSupportsTxs(), AppLayerParserRegisterDetectStateFuncs(), AppLayerParserRegisterGetEventInfo(), AppLayerParserRegisterGetEventsFunc(), AppLayerParserRegisterGetFilesFunc(), AppLayerParserRegisterGetStateProgressCompletionStatus(), AppLayerParserRegisterGetStateProgressFunc(), AppLayerParserRegisterGetTx(), AppLayerParserRegisterGetTxCnt(), AppLayerParserRegisterHasEventsFunc(), AppLayerParserRegisterLocalStorageFunc(), AppLayerParserRegisterLogger(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerParserRegisterTruncateFunc(), AppLayerParserRegisterTxFreeFunc(), AppLayerParserSetTxDetectState(), AppLayerParserStateCleanup(), AppLayerParserStreamTruncated(), AppLayerParserSupportsTxDetectState(), AppLayerTransactionGetActiveDetectLog(), DetectEngineRegisterAppInspectionEngine(), FlowInit(), FlowSetProtoEmergencyTimeout(), FlowSetProtoFreeFunc(), FlowSetProtoTimeout(), and FlowShutdown().
uint8_t FlowGetReverseProtoMapping (uint8_t rproto)
Definition at line 108 of file flow-util.c.
References FLOW_PROTO_ICMP, FLOW_PROTO_SCTP, FLOW_PROTO_TCP, and FLOW_PROTO_UDP.
Referenced by AppLayerParserThreadCtxAlloc(), and AppLayerParserThreadCtxFree().
void FlowInit (Flow * , const Packet *)
Definition at line 126 of file flow-util.c.
References Flow_::code, Packet_::code, COPY_TIMESTAMP, Flow_::dp, Flow_::dst, Flow_::flags, FLOW_IPV4, FLOW_IPV6, FLOW_SET_IPV4_DST_ADDR_FROM_PACKET, FLOW_SET_IPV4_SRC_ADDR_FROM_PACKET, FLOW_SET_IPV6_DST_ADDR_FROM_PACKET, FLOW_SET_IPV6_SRC_ADDR_FROM_PACKET, FlowGetProtoMapping(), Packet_::icmpv4h, Packet_::icmpv6h, PKT_IS_IPV4, PKT_IS_IPV6, Flow_::proto, Packet_::proto, Flow_::protomap, Flow_::recursion_level, Packet_::recursion_level, SCEnter, SCLogDebug, SCReturn, Packet_::sctph, SET_SCTP_DST_PORT, SET_SCTP_SRC_PORT, SET_TCP_DST_PORT, SET_TCP_SRC_PORT, SET_UDP_DST_PORT, SET_UDP_SRC_PORT, Flow_::sp, Flow_::src, Flow_::startts, Packet_::tcph, Packet_::ts, Flow_::type, Packet_::type, Packet_::udph, Flow_::vlan_id, and Packet_::vlan_id.
Referenced by FlowGetFlowFromHash(), and FlowGetFlowFromHashByPacket().