suricata: src/flow-hash.c File Reference
flow-hash.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "decode.h"
#include "detect-engine-state.h"
#include "flow.h"
#include "flow-hash.h"
#include "flow-util.h"
#include "flow-private.h"
#include "flow-manager.h"
#include "flow-storage.h"
#include "app-layer-parser.h"
#include "util-time.h"
#include "util-debug.h"
#include "util-hash-lookup3.h"
#include "conf.h"
#include "output.h"
#include "output-flow.h"
Data Structures
struct FlowHashKey4_
struct FlowHashKey6_
Macros
#define FLOW_DEFAULT_FLOW_PRUNE 5
#define FlowHashCountUpdate
#define FlowHashCountInit
#define FlowHashCountIncr
#define CMP_FLOW(f1, f2)
Typedefs
typedef struct FlowHashKey4_ FlowHashKey4
typedef struct FlowHashKey6_ FlowHashKey6
Functions
SC_ATOMIC_EXTERN (unsigned int, flow_prune_idx)
SC_ATOMIC_EXTERN (unsigned int, flow_flags)
void FlowDisableTcpReuseHandling (void)
int TcpSessionPacketSsnReuse (const Packet *p, const Flow *f, void *tcp_ssn)
Flow * FlowGetFlowFromHashByPacket (const Packet *p)
Flow * FlowLookupFlowFromHash (const Packet *p)
Lookup flow based on packet.
Flow * FlowGetFlowFromHash (ThreadVars *tv, DecodeThreadVars *dtv, const Packet *p)
Get Flow for packet.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Flow Hashing functions.
Definition in file flow-hash.c.
Macro Definition Documentation
#define CMP_FLOW (f1, f2)
Value:
(((CMP_ADDR(&(f1)->src, &(f2)->src) && \
       CMP_ADDR(&(f1)->dst, &(f2)->dst) && \
       CMP_PORT((f1)->sp, (f2)->sp) && CMP_PORT((f1)->dp, (f2)->dp)) || \
      (CMP_ADDR(&(f1)->src, &(f2)->dst) && \
       CMP_ADDR(&(f1)->dst, &(f2)->src) && \
       CMP_PORT((f1)->sp, (f2)->dp) && CMP_PORT((f1)->dp, (f2)->sp))) && \
     (f1)->proto == (f2)->proto && \
     (f1)->recursion_level == (f2)->recursion_level && \
     (f1)->vlan_id[0] == (f2)->vlan_id[0] && \
     (f1)->vlan_id[1] == (f2)->vlan_id[1])
Definition at line 338 of file flow-hash.c.
#define FLOW_DEFAULT_FLOW_PRUNE 5
Definition at line 50 of file flow-hash.c.
#define FlowHashCountIncr
Definition at line 149 of file flow-hash.c.
Referenced by FlowGetFlowFromHash(), and FlowLookupFlowFromHash().
#define FlowHashCountInit
Definition at line 148 of file flow-hash.c.
Referenced by FlowGetFlowFromHash().
#define FlowHashCountUpdate
Definition at line 147 of file flow-hash.c.
Referenced by FlowGetFlowFromHash().
Typedef Documentation
typedef struct FlowHashKey4_ FlowHashKey4
typedef struct FlowHashKey6_ FlowHashKey6
Function Documentation
void FlowDisableTcpReuseHandling (void)
Definition at line 153 of file flow-hash.c.
Referenced by RunmodeSetFlowStreamAsync().
Flow* FlowGetFlowFromHash (ThreadVars * tv, DecodeThreadVars * dtv, const Packet * p)
Get Flow for packet.
Hash retrieval function for flows. Looks up the hash bucket containing the flow pointer. Then compares the packet with the found flow to see if it is the flow we need. If it isn't, walk the list until the right flow is found.
If the flow is not found or the bucket was emtpy, a new flow is taken from the queue. FlowDequeue() will alloc new flows as long as we stay within our memcap limit.
The p->flow pointer is updated to point to the flow.
Parameters
tv thread vars
dtv decode thread vars (for flow log api thread data)
Return values
f LOCKED flow or NULL
Definition at line 653 of file flow-hash.c.
References COPY_TIMESTAMP, Flow_::fb, FBLOCK_LOCK, FBLOCK_UNLOCK, flow_hash, FlowHashCountIncr, FlowHashCountInit, FlowHashCountUpdate, FlowInit(), FLOWLOCK_WRLOCK, Flow_::hnext, Flow_::hprev, Flow_::lastts, SCLogDebug, and Packet_::ts.
Referenced by FlowHandlePacket().
Flow* FlowGetFlowFromHashByPacket (const Packet * p)
Definition at line 521 of file flow-hash.c.
References COPY_TIMESTAMP, Flow_::fb, FBLOCK_LOCK, FBLOCK_UNLOCK, flow_hash, FlowInit(), Flow_::hnext, Flow_::hprev, Flow_::lastts, SCLogDebug, and Packet_::ts.
Flow* FlowLookupFlowFromHash (const Packet * p)
Lookup flow based on packet.
Find the flow belonging to this packet. If not found, no new flow is set up.
Parameters
p packet to lookup the flow for
Return values
f flow or NULL if not found
Definition at line 565 of file flow-hash.c.
References COPY_TIMESTAMP, FBLOCK_LOCK, FBLOCK_UNLOCK, flow_hash, FlowHashCountIncr, FLOWLOCK_WRLOCK, Flow_::hnext, Flow_::hprev, Flow_::lastts, SCLogDebug, and Packet_::ts.
SC_ATOMIC_EXTERN (unsigned int, flow_prune_idx)
SC_ATOMIC_EXTERN (unsigned int, flow_flags)
int TcpSessionPacketSsnReuse (const Packet * p, const Flow * f, void * tcp_ssn)