suricata: src/flow-timeout.h File Reference
flow-timeout.h File Reference
Functions
int FlowForceReassemblyForFlow (Flow *f, int server, int client)
int FlowForceReassemblyNeedReassembly (Flow *f, int *server, int *client)
Check if a flow needs forced reassembly, or any other processing.
void FlowForceReassembly (void)
Force reassembly for all the flows that have unprocessed segments.
void FlowForceReassemblySetup (int detect_disabled)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file flow-timeout.h.
Function Documentation
void FlowForceReassembly (void)
Force reassembly for all the flows that have unprocessed segments.
Definition at line 566 of file flow-timeout.c.
Referenced by main().
int FlowForceReassemblyForFlow (Flow * f, int server, int client)
< null terminated array of packets
Definition at line 358 of file flow-timeout.c.
References BUG_ON, Packet_::flow, PKT_SET_SRC, PKT_SRC_FFR, Flow_::protoctx, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_REASSEMBLY, Flow_::thread_id, and TmqhOutputPacketpool().
int FlowForceReassemblyNeedReassembly (Flow * f, int * server, int * client)
Check if a flow needs forced reassembly, or any other processing.
Parameters
f LOCKED flow
server ptr to int that should be set to 1 or 2 if we return 1
client ptr to int that should be set to 1 or 2 if we return 1
Return values
0 no
1 yes
Definition at line 287 of file flow-timeout.c.
References Flow_::alparser, Flow_::alproto, ALPROTO_UNKNOWN, Flow_::alstate, AppLayerParserGetTransactionActive(), AppLayerParserGetTxCnt(), AppLayerParserProtocolSupportsTxs(), Flow_::proto, Flow_::protoctx, SCReturnInt, TcpSession_::state, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_REASSEMBLY, STREAM_HAS_UNPROCESSED_SEGMENTS_NONE, STREAM_TOCLIENT, STREAM_TOSERVER, TCP_CLOSED, and TCP_ESTABLISHED.
void FlowForceReassemblySetup (int detect_disabled)