suricata: src/flow-queue.h File Reference
flow-queue.h File Reference
#include "suricata-common.h"
#include "flow.h"
Data Structures
struct FlowQueue_
Macros
#define FQLOCK_MUTEX
#define FQLOCK_INIT(q) SCMutexInit(&(q)->m, NULL)
#define FQLOCK_DESTROY(q) SCMutexDestroy(&(q)->m)
#define FQLOCK_LOCK(q) SCMutexLock(&(q)->m)
#define FQLOCK_TRYLOCK(q) SCMutexTrylock(&(q)->m)
#define FQLOCK_UNLOCK(q) SCMutexUnlock(&(q)->m)
Typedefs
typedef struct FlowQueue_ FlowQueue
Functions
FlowQueue * FlowQueueNew ()
FlowQueue * FlowQueueInit (FlowQueue *)
void FlowQueueDestroy (FlowQueue *)
Destroy a flow queue.
void FlowEnqueue (FlowQueue *, Flow *)
add a flow to a queue
Flow * FlowDequeue (FlowQueue *)
remove a flow from the queue
void FlowMoveToSpare (Flow *)
Transfer a flow from a queue to the spare queue.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file flow-queue.h.
Macro Definition Documentation
#define FQLOCK_DESTROY (q) SCMutexDestroy(&(q)->m)
Definition at line 66 of file flow-queue.h.
Referenced by FlowQueueDestroy().
#define FQLOCK_INIT (q) SCMutexInit(&(q)->m, NULL)
Definition at line 65 of file flow-queue.h.
Referenced by FlowQueueInit().
#define FQLOCK_LOCK (q) SCMutexLock(&(q)->m)
Definition at line 67 of file flow-queue.h.
Referenced by FlowDequeue(), FlowEnqueue(), FlowMoveToSpare(), FlowRecyclerReadyToShutdown(), and FlowUpdateSpareFlows().
#define FQLOCK_MUTEX
Spinlocks or Mutex for the flow queues.
Definition at line 32 of file flow-queue.h.
#define FQLOCK_TRYLOCK (q) SCMutexTrylock(&(q)->m)
Definition at line 68 of file flow-queue.h.
#define FQLOCK_UNLOCK (q) SCMutexUnlock(&(q)->m)
Definition at line 69 of file flow-queue.h.
Referenced by FlowDequeue(), FlowEnqueue(), FlowMoveToSpare(), FlowRecyclerReadyToShutdown(), and FlowUpdateSpareFlows().
Typedef Documentation
typedef struct FlowQueue_ FlowQueue
Function Documentation
Flow* FlowDequeue (FlowQueue * q)
remove a flow from the queue
Parameters
q queue
Return values
f flow or NULL if empty list.
Definition at line 105 of file flow-queue.c.
References FlowQueue_::bot, BUG_ON, FQLOCK_LOCK, FQLOCK_UNLOCK, FlowQueue_::len, Flow_::lnext, Flow_::lprev, and FlowQueue_::top.
Referenced by FlowShutdown(), and FlowUpdateSpareFlows().
void FlowEnqueue (FlowQueue * q, Flow * f)
add a flow to a queue
Parameters
q queue
f flow
Definition at line 72 of file flow-queue.c.
References FlowQueue_::bot, BUG_ON, FQLOCK_LOCK, FQLOCK_UNLOCK, FlowQueue_::len, Flow_::lnext, Flow_::lprev, and FlowQueue_::top.
Referenced by FlowInitConfig(), and FlowUpdateSpareFlows().
void FlowMoveToSpare (Flow * f)
Transfer a flow from a queue to the spare queue.
Parameters
f the flow to be transfered
q the source queue, where the flow will be removed. This queue is locked.
Note
spare queue needs locking
Definition at line 146 of file flow-queue.c.
References FlowQueue_::bot, flow_spare_q, FQLOCK_LOCK, FQLOCK_UNLOCK, FlowQueue_::len, Flow_::lnext, Flow_::lprev, and FlowQueue_::top.
void FlowQueueDestroy (FlowQueue * q)
Destroy a flow queue.
Parameters
q the flow queue to destroy
Definition at line 61 of file flow-queue.c.
References FQLOCK_DESTROY.
Referenced by FlowShutdown().
FlowQueue* FlowQueueInit (FlowQueue *)
Definition at line 47 of file flow-queue.c.
References FQLOCK_INIT.
Referenced by FlowInitConfig(), and FlowQueueNew().
FlowQueue* FlowQueueNew ()
Definition at line 36 of file flow-queue.c.
References FlowQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.