suricata: AF_PACKET running mode
AF_PACKET running mode
Modules
AFP peers list
Files
file runmode-af-packet.c
file source-af-packet.c
Data Structures
union thdr
struct AFPThreadVars_
Structure to hold thread specific variables.
Macros
#define AFP_IFACE_NAME_LENGTH 48
#define AFP_STATE_DOWN 0
#define AFP_STATE_UP 1
#define AFP_RECONNECT_TIMEOUT 500000
#define AFP_DOWN_COUNTER_INTERVAL 40
#define POLL_TIMEOUT 100
#define TP_STATUS_USER_BUSY (1 << 31)
#define TP_STATUS_VLAN_VALID (1 << 4)
Typedefs
typedef struct AFPThreadVars_ AFPThreadVars
Structure to hold thread specific variables.
Enumerations
enum { AFP_READ_OK, AFP_READ_FAILURE, AFP_FAILURE, AFP_KERNEL_DROP }
enum { AFP_FATAL_ERROR = 1, AFP_RECOVERABLE_ERROR }
Functions
TmEcode ReceiveAFP (ThreadVars *, Packet *, void *, PacketQueue *, PacketQueue *)
TmEcode ReceiveAFPThreadInit (ThreadVars *tv, void *initdata, void **data)
Init function for ReceiveAFP.
void ReceiveAFPThreadExitStats (ThreadVars *tv, void *data)
This function prints stats to the screen at exit.
TmEcode ReceiveAFPThreadDeinit (ThreadVars *tv, void *data)
DeInit function closes af packet socket at exit.
TmEcode ReceiveAFPLoop (ThreadVars *tv, void *data, void *slot)
Main AF_PACKET reading Loop function.
TmEcode DecodeAFPThreadInit (ThreadVars *, void *, void **)
TmEcode DecodeAFPThreadDeinit (ThreadVars *tv, void *data)
TmEcode DecodeAFP (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
This function passes off to link type decoders.
TmEcode AFPSetBPFFilter (AFPThreadVars *ptv)
void TmModuleReceiveAFPRegister (void)
Registration Function for RecieveAFP.
void TmModuleDecodeAFPRegister (void)
Registration Function for DecodeAFP.
int AFPRead (AFPThreadVars *ptv)
AF packet read function.
TmEcode AFPWritePacket (Packet *p)
void AFPReleaseDataFromRing (Packet *p)
void AFPReleasePacket (Packet *p)
int AFPReadFromRing (AFPThreadVars *ptv)
AF packet read function for ring.
void AFPSwitchState (AFPThreadVars *ptv, int state)
Variables
int max_pending_packets
Detailed Description
Macro Definition Documentation
#define AFP_DOWN_COUNTER_INTERVAL 40
Definition at line 152 of file source-af-packet.c.
#define AFP_IFACE_NAME_LENGTH 48
Definition at line 146 of file source-af-packet.c.
Referenced by AFPPeersListAdd(), and ReceiveAFPThreadInit().
#define AFP_RECONNECT_TIMEOUT 500000
Definition at line 151 of file source-af-packet.c.
Referenced by ReceiveAFPLoop().
#define AFP_STATE_DOWN 0
Definition at line 148 of file source-af-packet.c.
Referenced by AFPPeersListAdd(), AFPSwitchState(), AFPWritePacket(), ReceiveAFPLoop(), and ReceiveAFPThreadDeinit().
#define AFP_STATE_UP 1
Definition at line 149 of file source-af-packet.c.
Referenced by AFPSwitchState(), and ReceiveAFPLoop().
#define POLL_TIMEOUT 100
Definition at line 154 of file source-af-packet.c.
Referenced by ReceiveAFPLoop().
#define TP_STATUS_USER_BUSY (1 << 31)
Definition at line 158 of file source-af-packet.c.
Referenced by AFPReadFromRing().
#define TP_STATUS_VLAN_VALID (1 << 4)
Definition at line 162 of file source-af-packet.c.
Referenced by AFPReadFromRing().
Typedef Documentation
typedef struct AFPThreadVars_ AFPThreadVars
Structure to hold thread specific variables.
Enumeration Type Documentation
anonymous enum
Enumerator
AFP_READ_OK
AFP_READ_FAILURE
AFP_FAILURE
AFP_KERNEL_DROP
Definition at line 168 of file source-af-packet.c.
anonymous enum
Enumerator
AFP_FATAL_ERROR
AFP_RECOVERABLE_ERROR
Definition at line 175 of file source-af-packet.c.
Function Documentation
int AFPRead (AFPThreadVars * ptv)
AF packet read function.
This function fills From here the packets are picked up by the DecodeAFP thread.
Parameters
user pointer to AFPThreadVars
Return values
TM_ECODE_FAILED on failure and TM_ECODE_OK on success
Definition at line 531 of file source-af-packet.c.
References AFP_FAILURE, AFP_READ_FAILURE, AFP_READ_OK, AFPThreadVars_::bytes, AFPThreadVars_::checksum_mode, CHECKSUM_VALIDATION_AUTO, CHECKSUM_VALIDATION_DISABLE, ChecksumAutoModeCheck(), AFPThreadVars_::cooked, AFPThreadVars_::data, AFPThreadVars_::datalen, AFPThreadVars_::datalink, Packet_::datalink, Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, LiveDevice_::ignore_checksum, AFPThreadVars_::livedev, Packet_::livedev, PacketCopyData(), PacketGetFromQueueOrAlloc(), PKT_IGNORE_CHECKSUM, PKT_SET_SRC, PKT_SRC_WIRE, AFPThreadVars_::pkts, SC_ATOMIC_GET, SC_ERR_AFP_READ, SCLogDebug, SCLogWarning, SCReturnInt, SET_PKT_LEN, SLL_HEADER_LEN, AFPThreadVars_::slot, AFPThreadVars_::socket, TM_ECODE_OK, TmqhOutputPacketpool(), Packet_::ts, and AFPThreadVars_::tv.
Referenced by ReceiveAFPLoop().
int AFPReadFromRing (AFPThreadVars * ptv)
AF packet read function for ring.
This function fills From here the packets are picked up by the DecodeAFP thread.
Parameters
user pointer to AFPThreadVars
Return values
TM_ECODE_FAILED on failure and TM_ECODE_OK on success
Definition at line 725 of file source-af-packet.c.
References AFP_COPY_MODE_NONE, AFP_EMERGENCY_MODE, AFP_FAILURE, AFP_KERNEL_DROP, AFP_READ_OK, AFP_ZERO_COPY, AFPReleasePacket(), AFPThreadVars_::bytes, AFPThreadVars_::checksum_mode, CHECKSUM_VALIDATION_AUTO, CHECKSUM_VALIDATION_DISABLE, ChecksumAutoModeCheck(), AFPThreadVars_::cooked, AFPThreadVars_::copy_mode, AFPThreadVars_::data, AFPThreadVars_::datalink, Packet_::datalink, AFPThreadVars_::flags, Packet_::flags, AFPThreadVars_::frame_buf, AFPThreadVars_::frame_offset, GET_PKT_DATA, GET_PKT_LEN, thdr::h2, LiveDevice_::ignore_checksum, AFPThreadVars_::livedev, Packet_::livedev, AFPThreadVars_::mpeer, PacketCopyData(), PacketGetFromQueueOrAlloc(), PacketSetData(), AFPPeer_::peer, PKT_IGNORE_CHECKSUM, PKT_SET_SRC, PKT_SRC_WIRE, AFPThreadVars_::pkts, thdr::raw, Packet_::ReleasePacket, AFPThreadVars_::req, SC_ATOMIC_GET, SCLogDebug, SCReturnInt, AFPThreadVars_::slot, suricata_ctl_flags, TM_ECODE_OK, TmqhOutputPacketpool(), AFPThreadVars_::tp_hdrlen, TP_STATUS_USER_BUSY, TP_STATUS_VLAN_VALID, Packet_::ts, AFPThreadVars_::tv, unlikely, AFPThreadVars_::vlan_disabled, Packet_::vlan_id, Packet_::vlan_idx, and Packet_::vlanh.
Referenced by ReceiveAFPLoop().
void AFPReleaseDataFromRing (Packet * p)
Definition at line 689 of file source-af-packet.c.
References AFP_COPY_MODE_NONE, AFPV_CLEANUP, AFPWritePacket(), thdr::h2, PKT_IS_PSEUDOPKT, and thdr::raw.
Referenced by AFPReleasePacket().
void AFPReleasePacket (Packet * p)
Definition at line 710 of file source-af-packet.c.
References AFPReleaseDataFromRing(), and PacketFreeOrRelease().
Referenced by AFPReadFromRing().
TmEcode AFPSetBPFFilter (AFPThreadVars * ptv)
Definition at line 1607 of file source-af-packet.c.
References AFPThreadVars_::bpf_filter, AFPThreadVars_::datalink, default_packet_size, AFPThreadVars_::iface, SC_ERR_AFP_CREATE, SCLogError, SCLogInfo, SCMutexLock, SCMutexUnlock, AFPThreadVars_::socket, TM_ECODE_FAILED, and TM_ECODE_OK.
void AFPSwitchState (AFPThreadVars * ptv, int state)
Definition at line 929 of file source-af-packet.c.
References AFPThreadVars_::afp_state, AFP_STATE_DOWN, AFP_STATE_UP, AFPPeerUpdate(), AFPThreadVars_::down_count, AFPThreadVars_::frame_buf, AFPThreadVars_::iface, AFPThreadVars_::mpeer, SC_ATOMIC_SET, SC_ATOMIC_SUB, SCFree, SCLogInfo, and AFPThreadVars_::socket.
Referenced by ReceiveAFPLoop(), and ReceiveAFPThreadDeinit().
TmEcode AFPWritePacket (Packet * p)
Definition at line 644 of file source-af-packet.c.
References ACTION_DROP, AFP_COPY_MODE_IPS, AFP_SOCK_PROTECT, AFP_STATE_DOWN, Packet_::ethh, Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, PACKET_TEST_ACTION, SC_ATOMIC_GET, SC_ERR_INVALID_VALUE, SC_ERR_SOCKET, SCLogWarning, SCMutexLock, SCMutexUnlock, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by AFPReleaseDataFromRing().
TmEcode DecodeAFP (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
This function passes off to link type decoders.
DecodeAFP reads packets from the PacketQueue and passes them off to the proper link type decoder.
Parameters
t pointer to ThreadVars
p pointer to the current packet
data pointer that gets cast into AFPThreadVars for ptv
pq pointer to the current PacketQueue
Definition at line 1844 of file source-af-packet.c.
References DecodeThreadVars_::counter_vlan, Packet_::datalink, DecodeEthernet(), DecodePPP(), DecodeRaw(), DecodeSll(), DecodeUpdatePacketCounters(), Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, LINKTYPE_ETHERNET, LINKTYPE_LINUX_SLL, LINKTYPE_PPP, LINKTYPE_RAW, PacketDecodeFinalize(), PKT_PSEUDO_STREAM_END, SC_ERR_DATALINK_UNIMPLEMENTED, SCEnter, SCLogError, SCReturnInt, StatsIncr(), TM_ECODE_OK, and Packet_::vlan_idx.
Referenced by TmModuleDecodeAFPRegister().
TmEcode DecodeAFPThreadDeinit (ThreadVars * tv, void * data)
Definition at line 1908 of file source-af-packet.c.
References DecodeThreadVarsFree(), SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodeAFPRegister().
TmEcode DecodeAFPThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 1886 of file source-af-packet.c.
References DecodeRegisterPerfCounters(), DecodeThreadVarsAlloc(), SCEnter, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleDecodeAFPRegister().
TmEcode ReceiveAFP (ThreadVars * , Packet * , void * , PacketQueue * , PacketQueue *)
TmEcode ReceiveAFPLoop (ThreadVars * tv, void * data, void * slot)
Main AF_PACKET reading Loop function.
Definition at line 1120 of file source-af-packet.c.
References AFP_FAILURE, AFP_FATAL_ERROR, AFP_KERNEL_DROP, AFP_READ_FAILURE, AFP_READ_OK, AFP_RECONNECT_TIMEOUT, AFP_RECOVERABLE_ERROR, AFP_RING_MODE, AFPThreadVars_::afp_state, AFP_STATE_DOWN, AFP_STATE_UP, AFPPeersListReachedInc(), AFPPeersListWaitTurn(), AFPRead(), AFPReadFromRing(), AFPSwitchState(), EngineKill(), AFPThreadVars_::flags, AFPThreadVars_::iface, AFPThreadVars_::mpeer, ThreadVars_::name, PacketPoolWait(), POLL_TIMEOUT, SC_ERR_AFP_CREATE, SC_ERR_AFP_READ, SCEnter, SCLogError, SCLogInfo, SCLogWarning, SCReturnInt, AFPThreadVars_::slot, TmSlot_::slot_next, AFPThreadVars_::socket, StatsSyncCountersIfSignalled, suricata_ctl_flags, TimeGet(), TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by TmModuleReceiveAFPRegister().
TmEcode ReceiveAFPThreadDeinit (ThreadVars * tv, void * data)
DeInit function closes af packet socket at exit.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into AFPThreadVars for ptv
Definition at line 1816 of file source-af-packet.c.
References AFP_STATE_DOWN, AFPSwitchState(), AFPThreadVars_::bpf_filter, AFPThreadVars_::data, AFPThreadVars_::datalen, SCFree, SCReturnInt, and TM_ECODE_OK.
void ReceiveAFPThreadExitStats (ThreadVars * tv, void * data)
This function prints stats to the screen at exit.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into AFPThreadVars for ptv
Definition at line 1795 of file source-af-packet.c.
References AFPThreadVars_::bytes, AFPThreadVars_::capture_kernel_drops, AFPThreadVars_::capture_kernel_packets, ThreadVars_::name, AFPThreadVars_::pkts, SCEnter, SCLogInfo, and StatsGetLocalCounterValue().
Referenced by TmModuleReceiveAFPRegister().
TmEcode ReceiveAFPThreadInit (ThreadVars * tv, void * initdata, void ** data)
Init function for ReceiveAFP.
Parameters
tv pointer to ThreadVars
initdata pointer to the interface passed from the user
data pointer gets populated with AFPThreadVars
Todo:
Create a general AFP setup function.
Definition at line 1662 of file source-af-packet.c.
References AFP_COPY_MODE_NONE, AFP_IFACE_NAME_LENGTH, AFP_RING_MODE, AFP_SOCK_PROTECT, AFP_ZERO_COPY, AFPPeersListAdd(), AFPIfaceConfig_::bpf_filter, AFPThreadVars_::bpf_filter, AFPIfaceConfig_::buffer_size, AFPThreadVars_::buffer_size, AFPThreadVars_::capture_kernel_drops, AFPThreadVars_::capture_kernel_packets, AFPIfaceConfig_::checksum_mode, AFPThreadVars_::checksum_mode, AFPIfaceConfig_::cluster_id, AFPThreadVars_::cluster_id, AFPIfaceConfig_::cluster_type, AFPThreadVars_::cluster_type, ConfGetBool(), AFPThreadVars_::cooked, AFPIfaceConfig_::copy_mode, AFPThreadVars_::copy_mode, AFPThreadVars_::data, AFPThreadVars_::datalen, AFPIfaceConfig_::DerefFunc, AFPIfaceConfig_::flags, AFPThreadVars_::flags, AFPIfaceConfig_::iface, AFPThreadVars_::iface, AFPThreadVars_::livedev, LiveGetDevice(), AFPIfaceConfig_::out_iface, AFPThreadVars_::out_iface, PACKET_FANOUT_LB, AFPIfaceConfig_::promisc, AFPThreadVars_::promisc, AFPIfaceConfig_::ring_size, AFPThreadVars_::ring_size, RunmodeGetActive(), SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SC_WARN_UNCOMMON, SCEnter, SCFree, SCKernelVersionIsAtLeast(), SCLogError, SCLogInfo, SCLogWarning, SCMalloc, SCReturnInt, StatsRegisterCounter(), strlcpy(), T_DATA_SIZE, AFPIfaceConfig_::threads, AFPThreadVars_::threads, TM_ECODE_FAILED, TM_ECODE_OK, AFPThreadVars_::tv, unlikely, and AFPThreadVars_::vlan_disabled.
Referenced by TmModuleReceiveAFPRegister().
void TmModuleDecodeAFPRegister (void)
Registration Function for DecodeAFP.
Todo:
Unit tests are needed for this module.
Definition at line 489 of file source-af-packet.c.
References TmModule_::cap_flags, DecodeAFP(), DecodeAFPThreadDeinit(), DecodeAFPThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEAFP, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceiveAFPRegister (void)
Registration Function for RecieveAFP.
Todo:
Unit tests are needed for this module.
Definition at line 268 of file source-af-packet.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceiveAFPLoop(), ReceiveAFPThreadExitStats(), ReceiveAFPThreadInit(), TmModule_::RegisterTests, SC_CAP_NET_RAW, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEAFP.
Referenced by RegisterAllModules().
Variable Documentation
int max_pending_packets
Maximum packets to simultaneously process.
Definition at line 233 of file suricata.c.