suricata: Thresholding
Thresholding
Files
file detect-engine-threshold.c
file detect-threshold.c
file util-threshold-config.c
Functions
int ThresholdHostStorageId (void)
void ThresholdInit (void)
int ThresholdHostHasThreshold (Host *host)
DetectThresholdData * SigGetThresholdTypeIter (Signature *sig, Packet *p, SigMatch **psm, int list)
Return next DetectThresholdData for signature.
int ThresholdTimeoutCheck (Host *host, struct timeval *tv)
Remove timeout threshold hash elements.
int ThresholdHandlePacketSuppress (Packet *p, DetectThresholdData *td, uint32_t sid, uint32_t gid)
int ThresholdHandlePacketHost (Host *h, Packet *p, DetectThresholdData *td, uint32_t sid, uint32_t gid)
int PacketAlertThreshold (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, DetectThresholdData *td, Packet *p, Signature *s)
Make the threshold logic for signatures.
void ThresholdHashInit (DetectEngineCtx *de_ctx)
Init threshold context hash tables.
void ThresholdContextDestroy (DetectEngineCtx *de_ctx)
Destroy threshold context hash tables.
void ThresholdListFree (void *ptr)
this function will free all the entries of a list DetectTagDataEntry
Detailed Description
This feature is used to reduce the number of logged alerts for noisy rules. This can be tuned to significantly reduce false alarms, and it can also be used to write a newer breed of rules. Thresholding commands limit the number of times a particular event is logged during a specified time interval.
Function Documentation
int PacketAlertThreshold (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, DetectThresholdData * td, Packet * p, Signature * s)
Make the threshold logic for signatures.
Parameters
de_ctx Dectection Context
tsh_ptr Threshold element
p Packet structure
s Signature structure
Return values
2 silent match (no alert but apply actions)
1 alert on this event
0 do not alert on this event
Definition at line 607 of file detect-engine-threshold.c.
References Packet_::dst, Signature_::gid, HostGetHostFromHash(), HostRelease(), Signature_::id, SCEnter, SCMutexLock, SCMutexUnlock, SCReturnInt, Packet_::src, ThresholdCtx_::threshold_table_lock, ThresholdHandlePacketHost(), ThresholdHandlePacketSuppress(), DetectEngineCtx_::ths_ctx, DetectThresholdData_::track, TRACK_DST, TRACK_RULE, TRACK_SRC, DetectThresholdData_::type, and TYPE_SUPPRESS.
DetectThresholdData* SigGetThresholdTypeIter (Signature * sig, Packet * p, SigMatch ** psm, int list)
Return next DetectThresholdData for signature.
Parameters
sig Signature pointer
p Packet structure
sm Pointer to a Signature Match pointer
Return values
tsh Return the threshold data from signature or NULL if not found
Definition at line 101 of file detect-engine-threshold.c.
References SigMatch_::ctx, DETECT_DETECTION_FILTER, DETECT_THRESHOLD, SigMatch_::prev, Signature_::sm_lists_tail, and SigMatch_::type.
void ThresholdContextDestroy (DetectEngineCtx * de_ctx)
Destroy threshold context hash tables.
Parameters
de_ctx Dectection Context
Definition at line 661 of file detect-engine-threshold.c.
References SCFree, SCMutexDestroy, ThresholdCtx_::th_entry, ThresholdCtx_::threshold_table_lock, and DetectEngineCtx_::ths_ctx.
Referenced by DetectEngineCtxFree().
int ThresholdHandlePacketHost (Host * h, Packet * p, DetectThresholdData * td, uint32_t sid, uint32_t gid)
Return values
2 silent match (no alert but apply actions)
1 normal match
0 no match
Definition at line 252 of file detect-engine-threshold.c.
References DetectThresholdData_::count, DetectThresholdEntry_::current_count, HostGetStorageById(), HostSetStorageById(), DetectThresholdData_::new_action, DetectThresholdEntry_::next, PACKET_ALERT, PACKET_DROP, PACKET_PASS, PACKET_REJECT, SC_ERR_INVALID_VALUE, SCLogDebug, SCLogError, DetectThresholdData_::seconds, TH_ACTION_ALERT, TH_ACTION_DROP, TH_ACTION_PASS, TH_ACTION_REJECT, DetectThresholdData_::timeout, Packet_::ts, DetectThresholdEntry_::tv_sec1, DetectThresholdEntry_::tv_timeout, DetectThresholdEntry_::tv_usec1, DetectThresholdData_::type, TYPE_BOTH, TYPE_DETECTION, TYPE_LIMIT, TYPE_RATE, and TYPE_THRESHOLD.
Referenced by PacketAlertThreshold().
int ThresholdHandlePacketSuppress (Packet * p, DetectThresholdData * td, uint32_t sid, uint32_t gid)
Definition at line 212 of file detect-engine-threshold.c.
References DetectThresholdData_::addrs, DetectAddressLookupInHead(), Packet_::dst, m, SC_ERR_INVALID_VALUE, SCLogDebug, SCLogError, Packet_::src, DetectThresholdData_::track, TRACK_DST, TRACK_EITHER, TRACK_RULE, and TRACK_SRC.
Referenced by PacketAlertThreshold().
void ThresholdHashInit (DetectEngineCtx * de_ctx)
Init threshold context hash tables.
Parameters
de_ctx Dectection Context
Definition at line 646 of file detect-engine-threshold.c.
References SC_ERR_MEM_ALLOC, SCLogError, SCMutexInit, ThresholdCtx_::threshold_table_lock, and DetectEngineCtx_::ths_ctx.
int ThresholdHostHasThreshold (Host * host)
Definition at line 85 of file detect-engine-threshold.c.
References HostGetStorageById().
int ThresholdHostStorageId (void)
Definition at line 71 of file detect-engine-threshold.c.
void ThresholdInit (void)
Definition at line 76 of file detect-engine-threshold.c.
References HostStorageRegister(), SC_ERR_HOST_INIT, SCLogError, and ThresholdListFree().
void ThresholdListFree (void * ptr)
this function will free all the entries of a list DetectTagDataEntry
Parameters
td pointer to DetectTagDataEntryList
Definition at line 674 of file detect-engine-threshold.c.
References DetectThresholdEntry_::next, and SCFree.
Referenced by ThresholdInit().
int ThresholdTimeoutCheck (Host * host, struct timeval * tv)
Remove timeout threshold hash elements.
Parameters
de_ctx Dectection Context
Definition at line 140 of file detect-engine-threshold.c.
References HostGetStorageById(), HostSetStorageById(), DetectThresholdEntry_::next, SCFree, DetectThresholdEntry_::seconds, and DetectThresholdEntry_::tv_sec1.