suricata: Netmap running mode
Netmap running mode
Files
file runmode-netmap.c
file source-netmap.c
Functions
TmEcode NoNetmapSupportExit (ThreadVars *tv, void *initdata, void **data)
this function prints an error message and exits.
void TmModuleReceiveNetmapRegister (void)
void TmModuleDecodeNetmapRegister (void)
Registration Function for DecodeNetmap.
Variables
int max_pending_packets
Detailed Description
Function Documentation
TmEcode NoNetmapSupportExit (ThreadVars * tv, void * initdata, void ** data)
this function prints an error message and exits.
Definition at line 120 of file source-netmap.c.
References ThreadVars_::name, SC_ERR_NO_NETMAP, and SCLogError.
Referenced by TmModuleDecodeNetmapRegister(), and TmModuleReceiveNetmapRegister().
void TmModuleDecodeNetmapRegister (void)
Registration Function for DecodeNetmap.
Todo:
Unit tests are needed for this module.
Definition at line 105 of file source-netmap.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, NoNetmapSupportExit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODENETMAP, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceiveNetmapRegister (void)
Definition at line 89 of file source-netmap.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, NoNetmapSupportExit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVENETMAP.
Referenced by RegisterAllModules().
Variable Documentation
int max_pending_packets
Maximum packets to simultaneously process.
Definition at line 233 of file suricata.c.