suricata: AFP peers list
AFP peers list
AF_PACKET running mode
Data Structures
struct AFPPeersList_
struct AFPPeer_
Typedefs
typedef struct AFPPeersList_ AFPPeersList
Functions
void AFPPeerUpdate (AFPThreadVars *ptv)
Update the peer.
void AFPPeerClean (AFPPeer *peer)
Clean and free ressource used by an AFPPeer.
TmEcode AFPPeersListInit ()
Init the global list of AFPPeer.
TmEcode AFPPeersListCheck ()
Check that all AFPPeer got a peer.
TmEcode AFPPeersListAdd (AFPThreadVars *ptv)
Declare a new AFP thread to AFP peers list.
int AFPPeersListWaitTurn (AFPPeer *peer)
void AFPPeersListReachedInc ()
void AFPPeersListClean ()
Clean the global peers list.
Variables
AFPPeersList peerslist
typedef struct AFPPeer_ AFPPeer
Detailed Description
AF_PACKET has an IPS mode were interface are peered: packet from on interface are sent the peered interface and the other way. The AFPPeer list is maitaining the list of peers. Each AFPPeer is storing the needed information to be able to send packet on the interface. A element of the list must not be destroyed during the run of Suricata as it is used by Packet and other threads.
Typedef Documentation
typedef struct AFPPeer_ AFPPeer
typedef struct AFPPeersList_ AFPPeersList
Function Documentation
void AFPPeerClean (AFPPeer * peer)
Clean and free ressource used by an AFPPeer.
Definition at line 323 of file source-af-packet.c.
References AFP_SOCK_PROTECT, AFPPeer_::flags, SC_ATOMIC_DESTROY, SCFree, SCMutexDestroy, and AFPPeer_::sock_protect.
Referenced by AFPPeersListClean().
TmEcode AFPPeersListAdd (AFPThreadVars * ptv)
Declare a new AFP thread to AFP peers list.
Definition at line 377 of file source-af-packet.c.
References AFP_COPY_MODE_NONE, AFP_IFACE_NAME_LENGTH, AFP_SOCK_PROTECT, AFP_STATE_DOWN, AFPPeerUpdate(), AFPThreadVars_::copy_mode, AFPPeer_::flags, AFPThreadVars_::flags, GetIfaceMTU(), AFPPeer_::iface, AFPThreadVars_::iface, AFPThreadVars_::mpeer, next, AFPThreadVars_::out_iface, AFPPeer_::peer, SC_ATOMIC_INIT, SC_ATOMIC_SET, SC_ERR_AFP_CREATE, SCEnter, SCLogError, SCMalloc, SCMutexInit, SCReturnInt, AFPPeer_::sock_protect, strlcpy(), TAILQ_FOREACH, TAILQ_INSERT_TAIL, TM_ECODE_FAILED, TM_ECODE_OK, AFPPeer_::turn, and unlikely.
Referenced by ReceiveAFPThreadInit().
TmEcode AFPPeersListCheck ()
Check that all AFPPeer got a peer.
Return values
TM_ECODE_FAILED if some threads are not peered or TM_ECODE_OK else.
Definition at line 356 of file source-af-packet.c.
References AFP_PEERS_MAX_TRY, AFP_PEERS_WAIT, SC_ERR_AFP_CREATE, SCEnter, SCLogError, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), and RunModeIdsAFPWorkers().
void AFPPeersListClean ()
Clean the global peers list.
Definition at line 471 of file source-af-packet.c.
References AFPPeerClean(), next, TAILQ_FIRST, and TAILQ_REMOVE.
Referenced by main().
TmEcode AFPPeersListInit ()
Init the global list of AFPPeer.
Definition at line 339 of file source-af-packet.c.
References SC_ATOMIC_INIT, SC_ATOMIC_SET, SCEnter, SCReturnInt, TAILQ_INIT, and TM_ECODE_OK.
Referenced by RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), and RunModeIdsAFPWorkers().
void AFPPeersListReachedInc ()
Definition at line 448 of file source-af-packet.c.
References SC_ATOMIC_ADD, SC_ATOMIC_SET, and SCLogInfo.
Referenced by ReceiveAFPLoop().
int AFPPeersListWaitTurn (AFPPeer * peer)
Definition at line 437 of file source-af-packet.c.
References SC_ATOMIC_GET, and AFPPeer_::turn.
Referenced by ReceiveAFPLoop().
void AFPPeerUpdate (AFPThreadVars * ptv)
Update the peer.
Update the AFPPeer of a thread ie set new state, socket number or iface index.
Definition at line 310 of file source-af-packet.c.
References AFPThreadVars_::afp_state, AFPThreadVars_::iface, AFPThreadVars_::mpeer, SC_ATOMIC_SET, and AFPThreadVars_::socket.
Referenced by AFPPeersListAdd(), and AFPSwitchState().
Variable Documentation
AFPPeersList peerslist
Definition at line 333 of file source-af-packet.c.