suricata: Host storage API
Host storage API
Functions
int HostStorageRegister (const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
Register a Host storage.
int HostSetStorageById (Host *h, int id, void *ptr)
Store a pointer in a given Host storage.
void * HostGetStorageById (Host *h, int id)
Get a value from a given Host storage.
Detailed Description
The Host storage API is a per-host storage. It is a mean to extend the Host structure with arbitrary data.
You have first to register the storage via HostStorageRegister() during the init of your module. Then you can attach data via HostSetStorageById() and access them via HostGetStorageById().
Function Documentation
void* HostGetStorageById (Host * h, int id)
Get a value from a given Host storage.
Parameters
h a pointer to the Host
id the id of the storage (return of HostStorageRegister() call)
Definition at line 84 of file host-storage.c.
References STORAGE_HOST, and StorageGetById().
Referenced by HostBitsTimedoutCheck(), HostHasHostBits(), TagHandlePacketHost(), TagHashAddTag(), TagHostHasTag(), TagTimeoutCheck(), ThresholdHandlePacketHost(), ThresholdHostHasThreshold(), and ThresholdTimeoutCheck().
int HostSetStorageById (Host * h, int id, void * ptr)
Store a pointer in a given Host storage.
Parameters
h a pointer to the Host
id the id of the storage (return of HostStorageRegister() call)
ptr pointer to the data to store
Definition at line 71 of file host-storage.c.
References STORAGE_HOST, and StorageSetById().
Referenced by TagHandlePacketHost(), TagHashAddTag(), TagTimeoutCheck(), ThresholdHandlePacketHost(), and ThresholdTimeoutCheck().
int HostStorageRegister (const char * name, const unsigned int size, void *(*)(unsigned int) Alloc, void(*)(void *) Free)
Register a Host storage.
Parameters
name the name of the storage
size integer coding the size of the stored value (sizeof(void *) is best choice here)
Alloc allocation function for the storage (can be null)
Free free function for the new storage
Return values
The ID of the newly register storage that will be used to access data
It has to be called once during the init of the sub system
Definition at line 59 of file host-storage.c.
References STORAGE_HOST, and StorageRegister().
Referenced by HostBitInitCtx(), TagInitCtx(), and ThresholdInit().