suricata: Pool
Pool
Files
file util-pool-thread.c
file util-pool-thread.h
file util-pool.c
file util-pool.h
Functions
PoolThread * PoolThreadInit (int threads, uint32_t size, uint32_t prealloc_size, uint32_t elt_size, void *(*Alloc)(), int(*Init)(void *, void *), void *InitData, void(*Cleanup)(void *), void(*Free)(void *))
initialize a thread pool
int PoolThreadGrow (PoolThread *pt, uint32_t size, uint32_t prealloc_size, uint32_t elt_size, void *(*Alloc)(), int(*Init)(void *, void *), void *InitData, void(*Cleanup)(void *), void(*Free)(void *))
grow a thread pool by one
int PoolThreadSize (PoolThread *pt)
get size of PoolThread (number of 'threads', so array elements)
void PoolThreadFree (PoolThread *pt)
destroy the thread pool
void * PoolThreadGetById (PoolThread *pt, uint16_t id)
get data from thread pool by thread id
void PoolThreadReturn (PoolThread *pt, void *data)
return data to thread pool
void PoolThreadRegisterTests (void)
Pool * PoolInit (uint32_t size, uint32_t prealloc_size, uint32_t elt_size, void *(*Alloc)(), int(*Init)(void *, void *), void *InitData, void(*Cleanup)(void *), void(*Free)(void *))
Init a Pool.
void PoolFree (Pool *p)
void PoolPrint (Pool *p)
void * PoolGet (Pool *p)
void PoolReturn (Pool *p, void *data)
void PoolPrintSaturation (Pool *p)
void * PoolTestAlloc ()
int PoolTestInitArg (void *data, void *allocdata)
void PoolTestFree (void *ptr)
void PoolRegisterTests (void)
Detailed Description
Pool are an effective way to maintain a set of ready to use structures.
To create a Pool, you need to use PoolInit(). You can get an item from the Pool by using PoolGet(). When you're done with it call PoolReturn(). To destroy the Pool, call PoolFree(), it will free all used memory.
Function Documentation
void PoolFree (Pool * p)
Definition at line 225 of file util-pool.c.
References Pool_::alloc_stack, Pool_::Cleanup, PoolBucket_::data, Pool_::data_buffer, Pool_::empty_stack, PoolBucket_::flags, Pool_::Free, PoolBucket_::next, Pool_::pb_buffer, POOL_BUCKET_PREALLOCATED, and SCFree.
Referenced by PoolInit(), PoolThreadFree(), StreamMsgQueuesDeinit(), and StreamTcpReassembleFree().
void* PoolGet (Pool * p)
Definition at line 280 of file util-pool.c.
References Pool_::Alloc, Pool_::alloc_stack, Pool_::alloc_stack_size, Pool_::allocated, Pool_::Cleanup, PoolBucket_::data, Pool_::elt_size, Pool_::empty_stack, Pool_::empty_stack_size, Pool_::Free, Pool_::Init, Pool_::InitData, Pool_::max_buckets, Pool_::max_outstanding, PoolBucket_::next, Pool_::outstanding, SCEnter, SCFree, SCLogDebug, SCMalloc, and SCReturnPtr.
Referenced by PoolThreadGetById(), StreamMsgGetFromPool(), and StreamTcpGetSegment().
Pool* PoolInit (uint32_t size, uint32_t prealloc_size, uint32_t elt_size, void *(*)() Alloc, int(*)(void *, void *) Init, void * InitData, void(*)(void *) Cleanup, void(*)(void *) Free)
Init a Pool.
PoolInit() creates a Pool. The Alloc function must only do allocation stuff. The Cleanup function must not try to free the PoolBucket::data. This is done by the Pool management system.
Parameters
size
prealloc_size
elt_size Memory size of an element
Alloc An allocation function or NULL to use a standard SCMalloc
Init An init function or NULL to use a standard memset to 0
InitData Init data
Cleanup a free function or NULL if no special treatment is needed
Free free func
Return values
the allocated Pool
Definition at line 84 of file util-pool.c.
References Pool_::Alloc, Pool_::alloc_stack, Pool_::alloc_stack_size, Pool_::allocated, Pool_::Cleanup, PoolBucket_::data, Pool_::data_buffer, Pool_::data_buffer_size, Pool_::elt_size, Pool_::empty_stack, Pool_::empty_stack_size, PoolBucket_::flags, Pool_::Free, Pool_::Init, Pool_::InitData, Pool_::max_buckets, PoolBucket_::next, Pool_::pb_buffer, POOL_BUCKET_PREALLOCATED, PoolFree(), Pool_::preallocated, SC_ERR_POOL_INIT, SCCalloc, SCFree, SCLogError, SCMalloc, and unlikely.
Referenced by PoolThreadGrow(), PoolThreadInit(), StreamMsgQueuesInit(), and StreamTcpReassemblyConfig().
void PoolPrint (Pool * p)
Definition at line 273 of file util-pool.c.
References Pool_::alloc_stack_size, and Pool_::empty_stack_size.
void PoolPrintSaturation (Pool * p)
Definition at line 377 of file util-pool.c.
References Pool_::max_buckets, Pool_::max_outstanding, Pool_::outstanding, and SCLogDebug.
Referenced by StreamTcpReassembleFree().
void PoolRegisterTests (void)
Definition at line 719 of file util-pool.c.
References PoolThreadRegisterTests().
Referenced by RunUnittests().
void PoolReturn (Pool * p, void * data)
Definition at line 337 of file util-pool.c.
References Pool_::alloc_stack, Pool_::alloc_stack_size, Pool_::allocated, Pool_::Cleanup, PoolBucket_::data, data, Pool_::empty_stack, Pool_::empty_stack_size, Pool_::Free, PoolBucket_::next, Pool_::outstanding, SCEnter, SCFree, SCLogDebug, and SCReturn.
Referenced by DefragTrackerFreeFrags(), PoolThreadReturn(), StreamMsgReturnToPool(), and StreamTcpSegmentReturntoPool().
void* PoolTestAlloc ()
Definition at line 386 of file util-pool.c.
References SCMalloc, and unlikely.
void PoolTestFree (void * ptr)
Definition at line 402 of file util-pool.c.
int PoolTestInitArg (void * data, void * allocdata)
Definition at line 393 of file util-pool.c.
References data, len, str, and strlcpy().
void PoolThreadFree (PoolThread * pt)
destroy the thread pool
Note
wrapper around PoolFree()
Parameters
pt thread pool
Definition at line 133 of file util-pool-thread.c.
References PoolThread_::array, PoolThreadElement_::lock, PoolThreadElement_::pool, PoolFree(), SCFree, SCMutexDestroy, SCMutexLock, SCMutexUnlock, and PoolThread_::size.
Referenced by PoolThreadInit(), and StreamTcpFreeConfig().
void* PoolThreadGetById (PoolThread * pt, uint16_t id)
get data from thread pool by thread id
Note
wrapper around PoolGet()
Parameters
pt thread pool
id thread id
Return values
ptr data or NULL
Definition at line 153 of file util-pool-thread.c.
References PoolThread_::array, data, DetectEngineCtx_::id, PoolThreadElement_::lock, PoolThreadElement_::pool, PoolGet(), SCMutexLock, SCMutexUnlock, and PoolThread_::size.
Referenced by StreamTcpNewSession().
int PoolThreadGrow (PoolThread * pt, uint32_t size, uint32_t prealloc_size, uint32_t elt_size, void *(*)() Alloc, int(*)(void *, void *) Init, void * InitData, void(*)(void *) Cleanup, void(*)(void *) Free)
grow a thread pool by one
Note
calls PoolInit so all args but 'pt' are the same
Parameters
pt thread pool to grow
Return values
r id of new entry on succes, -1 on error
Definition at line 88 of file util-pool-thread.c.
References PoolThread_::array, PoolThreadElement_::lock, PoolThreadElement_::pool, PoolInit(), SC_ERR_POOL_INIT, SCFree, SCLogDebug, SCLogError, SCMutexInit, SCMutexLock, SCMutexUnlock, SCRealloc, and PoolThread_::size.
Referenced by StreamTcpThreadInit().
PoolThread* PoolThreadInit (int threads, uint32_t size, uint32_t prealloc_size, uint32_t elt_size, void *(*)() Alloc, int(*)(void *, void *) Init, void * InitData, void(*)(void *) Cleanup, void(*)(void *) Free)
initialize a thread pool
Note
same as PoolInit() except for "threads"
Parameters
threads number of threads to use this
Return values
pt thread pool or NULL on error
Definition at line 38 of file util-pool-thread.c.
References PoolThread_::array, PoolThreadElement_::lock, PoolThreadElement_::pool, PoolInit(), PoolThreadFree(), SCLogDebug, SCMalloc, SCMutexInit, SCMutexLock, SCMutexUnlock, PoolThread_::size, and unlikely.
Referenced by StreamTcpInitConfig(), and StreamTcpThreadInit().
void PoolThreadRegisterTests (void)
Definition at line 439 of file util-pool-thread.c.
Referenced by PoolRegisterTests().
void PoolThreadReturn (PoolThread * pt, void * data)
return data to thread pool
Note
wrapper around PoolReturn()
Parameters
pt thread pool
data memory block to return, with PoolThreadReserved as it's first member
Definition at line 172 of file util-pool-thread.c.
References PoolThread_::array, data, DetectEngineCtx_::id, PoolThreadElement_::lock, PoolThreadElement_::pool, PoolReturn(), SCLogDebug, SCMutexLock, SCMutexUnlock, and PoolThread_::size.
Referenced by StreamTcpSessionClear().
int PoolThreadSize (PoolThread * pt)
get size of PoolThread (number of 'threads', so array elements)
Parameters
pt thread pool
Return values
size or -1 on error
Definition at line 126 of file util-pool-thread.c.
References PoolThread_::size.
Referenced by StreamTcpThreadInit().