suricata: HTTP layer support
HTTP layer support
Files
file app-layer-htp-mem.c
file app-layer-htp.c
file app-layer-htp.h
file detect-engine-hcbd.c
Handle HTTP request body match corresponding to http_client_body keyword.
file detect-engine-hcd.c
Handle HTTP cookie match.
file detect-engine-hhd.c
Handle HTTP header match.
file detect-engine-hhhd.c
Handle HTTP host header. HHHD - Http Host Header Data.
file detect-engine-hmd.c
Handle HTTP method match.
file detect-engine-hrhd.c
Handle HTTP raw header match.
file detect-engine-hrhhd.c
Handle HTTP host header. HRHHD - Http Raw Host Header Data.
file detect-engine-hrud.c
Handle HTTP raw uri match.
file detect-engine-hsbd.c
Handle HTTP response body match corresponding to http_server_body keyword.
file detect-engine-hscd.c
file detect-engine-hsmd.c
file detect-engine-hua.c
Handle HTTP user agent match.
file detect-http-client-body.c
file detect-http-cookie.c
file detect-http-header.c
file detect-http-hh.c
file detect-http-hrh.c
file detect-http-method.c
file detect-http-raw-header.c
file detect-http-raw-uri.c
file detect-http-server-body.c
file detect-http-stat-code.c
file detect-http-stat-msg.c
file detect-http-ua.c
file detect-http-uri.c
Data Structures
struct HTPCfgRec_
struct HtpBodyChunk_
struct HtpBody_
struct HtpTxUserData_
struct HtpState_
Macros
#define HTP_CONFIG_DEFAULT_REQUEST_BODY_LIMIT 4096U
#define HTP_CONFIG_DEFAULT_RESPONSE_BODY_LIMIT 4096U
#define HTP_CONFIG_DEFAULT_REQUEST_INSPECT_MIN_SIZE 32768U
#define HTP_CONFIG_DEFAULT_REQUEST_INSPECT_WINDOW 4096U
#define HTP_CONFIG_DEFAULT_RESPONSE_INSPECT_MIN_SIZE 32768U
#define HTP_CONFIG_DEFAULT_RESPONSE_INSPECT_WINDOW 4096U
#define HTP_CONFIG_DEFAULT_FIELD_LIMIT_SOFT 9000U
#define HTP_CONFIG_DEFAULT_FIELD_LIMIT_HARD 18000U
#define HTP_CONFIG_DEFAULT_RANDOMIZE 1
#define HTP_CONFIG_DEFAULT_RANDOMIZE_RANGE 10
#define HTP_BOUNDARY_MAX 200U
#define HTP_FLAG_STATE_OPEN 0x0001
#define HTP_FLAG_STATE_CLOSED_TS 0x0002
#define HTP_FLAG_STATE_CLOSED_TC 0x0004
#define HTP_FLAG_STATE_DATA 0x0008
#define HTP_FLAG_STATE_ERROR 0x0010
#define HTP_FLAG_NEW_BODY_SET 0x0020
#define HTP_FLAG_STORE_FILES_TS 0x0040
#define HTP_FLAG_STORE_FILES_TC 0x0080
#define HTP_FLAG_STORE_FILES_TX_TS 0x0100
#define HTP_FLAG_STORE_FILES_TX_TC 0x0200
#define HTP_FLAG_NEW_FILE_TX_TS 0x0400
#define HTP_FLAG_NEW_FILE_TX_TC 0x0800
#define HTP_PCRE_NONE 0x00
#define HTP_PCRE_DONE 0x01
#define HTP_PCRE_HAS_MATCH 0x02
#define HTP_CONTENTTYPE_SET 0x01
#define HTP_BOUNDARY_SET 0x02
#define HTP_BOUNDARY_OPEN 0x04
#define HTP_FILENAME_SET 0x08
#define HTP_DONTSTORE 0x10
#define HTP_TX_HAS_FILE 0x01
#define HTP_TX_HAS_FILENAME 0x02
#define HTP_TX_HAS_TYPE 0x04
#define HTP_TX_HAS_FILECONTENT 0x08
#define HTP_RULE_NEED_FILE HTP_TX_HAS_FILE
#define HTP_RULE_NEED_FILENAME HTP_TX_HAS_FILENAME
#define HTP_RULE_NEED_TYPE HTP_TX_HAS_TYPE
#define HTP_RULE_NEED_FILECONTENT HTP_TX_HAS_FILECONTENT
#define HTP_REQUIRE_REQUEST_BODY (1 << 0)
#define HTP_REQUIRE_REQUEST_MULTIPART (1 << 1)
#define HTP_REQUIRE_REQUEST_FILE (1 << 2)
#define HTP_REQUIRE_RESPONSE_BODY (1 << 3)
Typedefs
typedef struct HTPCfgRec_ HTPCfgRec
typedef struct HtpBodyChunk_ HtpBodyChunk
typedef struct HtpBody_ HtpBody
typedef struct HtpTxUserData_ HtpTxUserData
typedef struct HtpState_ HtpState
Enumerations
enum { HTP_BODY_NONE = 0, HTP_BODY_REQUEST, HTP_BODY_RESPONSE }
enum { HTP_BODY_REQUEST_NONE = 0, HTP_BODY_REQUEST_MULTIPART, HTP_BODY_REQUEST_POST, HTP_BODY_REQUEST_PUT }
enum {
HTTP_DECODER_EVENT_UNKNOWN_ERROR, HTTP_DECODER_EVENT_GZIP_DECOMPRESSION_FAILED, HTTP_DECODER_EVENT_REQUEST_FIELD_MISSING_COLON, HTTP_DECODER_EVENT_RESPONSE_FIELD_MISSING_COLON,
HTTP_DECODER_EVENT_INVALID_REQUEST_CHUNK_LEN, HTTP_DECODER_EVENT_INVALID_RESPONSE_CHUNK_LEN, HTTP_DECODER_EVENT_INVALID_TRANSFER_ENCODING_VALUE_IN_REQUEST, HTTP_DECODER_EVENT_INVALID_TRANSFER_ENCODING_VALUE_IN_RESPONSE,
HTTP_DECODER_EVENT_INVALID_CONTENT_LENGTH_FIELD_IN_REQUEST, HTTP_DECODER_EVENT_INVALID_CONTENT_LENGTH_FIELD_IN_RESPONSE, HTTP_DECODER_EVENT_100_CONTINUE_ALREADY_SEEN, HTTP_DECODER_EVENT_UNABLE_TO_MATCH_RESPONSE_TO_REQUEST,
HTTP_DECODER_EVENT_INVALID_SERVER_PORT_IN_REQUEST, HTTP_DECODER_EVENT_INVALID_AUTHORITY_PORT, HTTP_DECODER_EVENT_REQUEST_HEADER_INVALID, HTTP_DECODER_EVENT_RESPONSE_HEADER_INVALID,
HTTP_DECODER_EVENT_MISSING_HOST_HEADER, HTTP_DECODER_EVENT_HOST_HEADER_AMBIGUOUS, HTTP_DECODER_EVENT_INVALID_REQUEST_FIELD_FOLDING, HTTP_DECODER_EVENT_INVALID_RESPONSE_FIELD_FOLDING,
HTTP_DECODER_EVENT_REQUEST_FIELD_TOO_LONG, HTTP_DECODER_EVENT_RESPONSE_FIELD_TOO_LONG, HTTP_DECODER_EVENT_REQUEST_SERVER_PORT_TCP_PORT_MISMATCH, HTTP_DECODER_EVENT_URI_HOST_INVALID,
HTTP_DECODER_EVENT_HEADER_HOST_INVALID, HTTP_DECODER_EVENT_METHOD_DELIM_NON_COMPLIANT, HTTP_DECODER_EVENT_URI_DELIM_NON_COMPLIANT, HTTP_DECODER_EVENT_REQUEST_LINE_LEADING_WHITESPACE,
HTTP_DECODER_EVENT_MULTIPART_GENERIC_ERROR, HTTP_DECODER_EVENT_MULTIPART_NO_FILEDATA, HTTP_DECODER_EVENT_MULTIPART_INVALID_HEADER
}
Functions
struct HtpBodyChunk_ __attribute__ ((__packed__))
DNS packet header.
SC_ATOMIC_DECLARE (uint32_t, htp_config_flags)
void RegisterHTPParsers (void)
Register the HTTP protocol and state handling functions to APP layer of the engine.
void HTPParserRegisterTests (void)
Register the Unit tests for the HTTP protocol.
void HTPAtExitPrintStats (void)
Print the stats of the HTTP requests.
void HTPFreeConfig (void)
Clears the HTTP server configuration memory used by HTP library.
htp_tx_t * HTPTransactionMain (const HtpState *)
int HTPCallbackRequestBodyData (htp_tx_data_t *)
Function callback to append chunks for Requests.
int HtpTransactionGetLoggableId (Flow *)
void HtpBodyPrint (HtpBody *)
Print the information and chunks of a Body.
void HtpBodyFree (HtpBody *)
Free the information held in the request body.
void HTPStateFree (void *)
Function to frees the HTTP state memory and also frees the HTTP connection parser memory which was used by the HTP library.
void AppLayerHtpEnableRequestBodyCallback (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request body data. .
void AppLayerHtpEnableResponseBodyCallback (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request body data. .
void AppLayerHtpNeedFileInspection (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request file.
void AppLayerHtpPrintStats (void)
void HTPConfigure (void)
void HtpConfigCreateBackup (void)
void HtpConfigRestoreBackup (void)
Detailed Description
Macro Definition Documentation
#define HTP_BOUNDARY_MAX 200U
a boundary should be smaller in size
Definition at line 57 of file app-layer-htp.h.
#define HTP_BOUNDARY_OPEN 0x04
We have a boundary string
Definition at line 199 of file app-layer-htp.h.
#define HTP_BOUNDARY_SET 0x02
We have a boundary string
Definition at line 198 of file app-layer-htp.h.
Referenced by HTPCallbackRequestBodyData().
#define HTP_CONFIG_DEFAULT_FIELD_LIMIT_HARD 18000U
Definition at line 51 of file app-layer-htp.h.
#define HTP_CONFIG_DEFAULT_FIELD_LIMIT_SOFT 9000U
Definition at line 50 of file app-layer-htp.h.
#define HTP_CONFIG_DEFAULT_RANDOMIZE 1
Definition at line 53 of file app-layer-htp.h.
#define HTP_CONFIG_DEFAULT_RANDOMIZE_RANGE 10
Definition at line 54 of file app-layer-htp.h.
#define HTP_CONFIG_DEFAULT_REQUEST_BODY_LIMIT 4096U
Definition at line 44 of file app-layer-htp.h.
#define HTP_CONFIG_DEFAULT_REQUEST_INSPECT_MIN_SIZE 32768U
Definition at line 46 of file app-layer-htp.h.
#define HTP_CONFIG_DEFAULT_REQUEST_INSPECT_WINDOW 4096U
Definition at line 47 of file app-layer-htp.h.
#define HTP_CONFIG_DEFAULT_RESPONSE_BODY_LIMIT 4096U
Definition at line 45 of file app-layer-htp.h.
#define HTP_CONFIG_DEFAULT_RESPONSE_INSPECT_MIN_SIZE 32768U
Definition at line 48 of file app-layer-htp.h.
#define HTP_CONFIG_DEFAULT_RESPONSE_INSPECT_WINDOW 4096U
Definition at line 49 of file app-layer-htp.h.
#define HTP_CONTENTTYPE_SET 0x01
We have the content type
Definition at line 197 of file app-layer-htp.h.
#define HTP_DONTSTORE 0x10
not storing this file
Definition at line 201 of file app-layer-htp.h.
Referenced by HtpRequestBodyHandleMultipart(), and HtpResponseBodyHandle().
#define HTP_FILENAME_SET 0x08
filename is registered in the flow
Definition at line 200 of file app-layer-htp.h.
Referenced by HtpRequestBodyHandleMultipart(), and HtpResponseBodyHandle().
#define HTP_FLAG_NEW_BODY_SET 0x0020
Flag to indicate that HTTP has parsed a new body (for pcre)
Definition at line 76 of file app-layer-htp.h.
Referenced by HTPCallbackRequestBodyData(), HTPCallbackResponseBodyData(), and HTPStateFree().
#define HTP_FLAG_NEW_FILE_TX_TC 0x0800
flag the state that a new file has been set in this tx
Definition at line 88 of file app-layer-htp.h.
Referenced by HTPFileOpen().
#define HTP_FLAG_NEW_FILE_TX_TS 0x0400
flag the state that a new file has been set in this tx
Definition at line 86 of file app-layer-htp.h.
Referenced by HTPFileOpen().
#define HTP_FLAG_STATE_CLOSED_TC 0x0004
Flag to indicate that HTTP connection is closed
Definition at line 65 of file app-layer-htp.h.
#define HTP_FLAG_STATE_CLOSED_TS 0x0002
Flag to indicate that HTTP connection is closed
Definition at line 62 of file app-layer-htp.h.
#define HTP_FLAG_STATE_DATA 0x0008
Flag to indicate that HTTP connection needs more data
Definition at line 68 of file app-layer-htp.h.
#define HTP_FLAG_STATE_ERROR 0x0010
Flag to indicate that an error has been occured on HTTP connection
Definition at line 71 of file app-layer-htp.h.
#define HTP_FLAG_STATE_OPEN 0x0001
Flag to indicate that HTTP connection is open
Definition at line 59 of file app-layer-htp.h.
#define HTP_FLAG_STORE_FILES_TC 0x0080
Definition at line 82 of file app-layer-htp.h.
Referenced by HTPFileOpen().
#define HTP_FLAG_STORE_FILES_TS 0x0040
Definition at line 81 of file app-layer-htp.h.
Referenced by HTPFileOpen().
#define HTP_FLAG_STORE_FILES_TX_TC 0x0200
Definition at line 84 of file app-layer-htp.h.
Referenced by HTPFileOpen().
#define HTP_FLAG_STORE_FILES_TX_TS 0x0100
Definition at line 83 of file app-layer-htp.h.
Referenced by HTPFileOpen().
#define HTP_PCRE_DONE 0x01
Flag to indicate that pcre has done some inspection in the chunks
Definition at line 144 of file app-layer-htp.h.
#define HTP_PCRE_HAS_MATCH 0x02
Flag to indicate that the chunks matched on some rule
Definition at line 149 of file app-layer-htp.h.
#define HTP_PCRE_NONE 0x00
No pcre executed yet
Definition at line 143 of file app-layer-htp.h.
#define HTP_REQUIRE_REQUEST_BODY (1 << 0)
part of the engine needs the request body (e.g. http_client_body keyword)
Definition at line 267 of file app-layer-htp.h.
Referenced by AppLayerHtpEnableRequestBodyCallback(), and HTPCallbackRequestBodyData().
#define HTP_REQUIRE_REQUEST_FILE (1 << 2)
part of the engine needs the request file (e.g. log-file module)
Definition at line 272 of file app-layer-htp.h.
Referenced by AppLayerHtpNeedFileInspection().
#define HTP_REQUIRE_REQUEST_MULTIPART (1 << 1)
part of the engine needs the request body multipart header (e.g. filename and / or fileext keywords)
Definition at line 270 of file app-layer-htp.h.
Referenced by AppLayerHtpNeedMultipartHeader().
#define HTP_REQUIRE_RESPONSE_BODY (1 << 3)
part of the engine needs the request body (e.g. file_data keyword)
Definition at line 274 of file app-layer-htp.h.
Referenced by AppLayerHtpEnableResponseBodyCallback(), and HTPCallbackResponseBodyData().
#define HTP_RULE_NEED_FILE HTP_TX_HAS_FILE
Definition at line 208 of file app-layer-htp.h.
#define HTP_RULE_NEED_FILECONTENT HTP_TX_HAS_FILECONTENT
Definition at line 211 of file app-layer-htp.h.
#define HTP_RULE_NEED_FILENAME HTP_TX_HAS_FILENAME
Definition at line 209 of file app-layer-htp.h.
#define HTP_RULE_NEED_TYPE HTP_TX_HAS_TYPE
Definition at line 210 of file app-layer-htp.h.
#define HTP_TX_HAS_FILE 0x01
Definition at line 203 of file app-layer-htp.h.
#define HTP_TX_HAS_FILECONTENT 0x08
file has content so we can do type detect
Definition at line 206 of file app-layer-htp.h.
#define HTP_TX_HAS_FILENAME 0x02
filename is known at this time
Definition at line 204 of file app-layer-htp.h.
#define HTP_TX_HAS_TYPE 0x04
Definition at line 205 of file app-layer-htp.h.
Typedef Documentation
typedef struct HtpBody_ HtpBody
Struct used to hold all the chunks of a body on a request
typedef struct HtpBodyChunk_ HtpBodyChunk
Definition at line 182 of file app-layer-htp.h.
typedef struct HTPCfgRec_ HTPCfgRec
Need a linked list in order to keep track of these
typedef struct HtpState_ HtpState
typedef struct HtpTxUserData_ HtpTxUserData
Now the Body Chunks will be stored per transaction, at the tx user data
Enumeration Type Documentation
anonymous enum
Enumerator
HTP_BODY_NONE
Flag to indicate the current operation
HTP_BODY_REQUEST
Flag to indicate that the current operation is a request
HTP_BODY_RESPONSE
Flag to indicate that the current operation is a response
Definition at line 90 of file app-layer-htp.h.
anonymous enum
Enumerator
HTP_BODY_REQUEST_NONE
HTP_BODY_REQUEST_MULTIPART
HTP_BODY_REQUEST_POST
HTP_BODY_REQUEST_PUT
Definition at line 99 of file app-layer-htp.h.
anonymous enum
Enumerator
HTTP_DECODER_EVENT_UNKNOWN_ERROR
HTTP_DECODER_EVENT_GZIP_DECOMPRESSION_FAILED
HTTP_DECODER_EVENT_REQUEST_FIELD_MISSING_COLON
HTTP_DECODER_EVENT_RESPONSE_FIELD_MISSING_COLON
HTTP_DECODER_EVENT_INVALID_REQUEST_CHUNK_LEN
HTTP_DECODER_EVENT_INVALID_RESPONSE_CHUNK_LEN
HTTP_DECODER_EVENT_INVALID_TRANSFER_ENCODING_VALUE_IN_REQUEST
HTTP_DECODER_EVENT_INVALID_TRANSFER_ENCODING_VALUE_IN_RESPONSE
HTTP_DECODER_EVENT_INVALID_CONTENT_LENGTH_FIELD_IN_REQUEST
HTTP_DECODER_EVENT_INVALID_CONTENT_LENGTH_FIELD_IN_RESPONSE
HTTP_DECODER_EVENT_100_CONTINUE_ALREADY_SEEN
HTTP_DECODER_EVENT_UNABLE_TO_MATCH_RESPONSE_TO_REQUEST
HTTP_DECODER_EVENT_INVALID_SERVER_PORT_IN_REQUEST
HTTP_DECODER_EVENT_INVALID_AUTHORITY_PORT
HTTP_DECODER_EVENT_REQUEST_HEADER_INVALID
HTTP_DECODER_EVENT_RESPONSE_HEADER_INVALID
HTTP_DECODER_EVENT_MISSING_HOST_HEADER
HTTP_DECODER_EVENT_HOST_HEADER_AMBIGUOUS
HTTP_DECODER_EVENT_INVALID_REQUEST_FIELD_FOLDING
HTTP_DECODER_EVENT_INVALID_RESPONSE_FIELD_FOLDING
HTTP_DECODER_EVENT_REQUEST_FIELD_TOO_LONG
HTTP_DECODER_EVENT_RESPONSE_FIELD_TOO_LONG
HTTP_DECODER_EVENT_REQUEST_SERVER_PORT_TCP_PORT_MISMATCH
HTTP_DECODER_EVENT_URI_HOST_INVALID
HTTP_DECODER_EVENT_HEADER_HOST_INVALID
HTTP_DECODER_EVENT_METHOD_DELIM_NON_COMPLIANT
HTTP_DECODER_EVENT_URI_DELIM_NON_COMPLIANT
HTTP_DECODER_EVENT_REQUEST_LINE_LEADING_WHITESPACE
HTTP_DECODER_EVENT_MULTIPART_GENERIC_ERROR
HTTP_DECODER_EVENT_MULTIPART_NO_FILEDATA
HTTP_DECODER_EVENT_MULTIPART_INVALID_HEADER
Definition at line 106 of file app-layer-htp.h.
Function Documentation
struct HtpBodyChunk_ __attribute__ ((__packed__))
DNS packet header.
Unified2 Extra Data Header Unified2 Extra Data (currently used only for XFF)
Definition at line 94 of file alert-unified2-alert.c.
void AppLayerHtpEnableRequestBodyCallback (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request body data. .
Definition at line 428 of file app-layer-htp.c.
References HTP_REQUIRE_REQUEST_BODY, SC_ATOMIC_OR, SCEnter, and SCReturn.
Referenced by AppLayerHtpNeedFileInspection(), AppLayerHtpNeedMultipartHeader(), and RunUnittests().
void AppLayerHtpEnableResponseBodyCallback (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request body data. .
Definition at line 441 of file app-layer-htp.c.
References HTP_REQUIRE_RESPONSE_BODY, SC_ATOMIC_OR, SCEnter, and SCReturn.
Referenced by AppLayerHtpNeedFileInspection(), DetectByteExtractSetup(), DetectBytejumpSetup(), DetectBytetestSetup(), DetectContentSetup(), and DetectIsdataatSetup().
void AppLayerHtpNeedFileInspection (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request file.
Definition at line 470 of file app-layer-htp.c.
References AppLayerHtpEnableRequestBodyCallback(), AppLayerHtpEnableResponseBodyCallback(), AppLayerHtpNeedMultipartHeader(), HTP_REQUIRE_REQUEST_FILE, SC_ATOMIC_OR, SCEnter, and SCReturn.
Referenced by RunUnittests().
void AppLayerHtpPrintStats (void)
Definition at line 2585 of file app-layer-htp.c.
References SCLogInfo, SCMutexLock, and SCMutexUnlock.
Referenced by main().
void HTPAtExitPrintStats (void)
Print the stats of the HTTP requests.
Definition at line 1947 of file app-layer-htp.c.
References SCEnter, SCLogDebug, SCMutexLock, SCMutexUnlock, and SCReturn.
Referenced by main().
void HtpBodyFree (HtpBody * body)
Free the information held in the request body.
Parameters
body pointer to the HtpBody holding the list
Return values
none
Definition at line 171 of file app-layer-htp-body.c.
References HtpBodyChunk_::data, HtpBody_::first, HTPFree(), HtpBody_::last, HtpBodyChunk_::len, HtpBodyChunk_::next, SCEnter, and SCLogDebug.
void HtpBodyPrint (HtpBody * body)
Print the information and chunks of a Body.
Parameters
body pointer to the HtpBody holding the list
Return values
none
Definition at line 146 of file app-layer-htp-body.c.
References HtpBodyChunk_::data, HtpBody_::first, HtpBodyChunk_::len, HtpBodyChunk_::next, PrintRawDataFp(), SCEnter, SCLogDebug, and SCLogDebugEnabled().
int HTPCallbackRequestBodyData (htp_tx_data_t * d)
Function callback to append chunks for Requests.
Parameters
d pointer to the htp_tx_data_t structure (a chunk from htp lib)
Return values
int HTP_OK if all goes well
Definition at line 1760 of file app-layer-htp.c.
References BUG_ON, HtpState_::cfg, htp_tx_t::connp, HtpBody_::content_len_so_far, htp_tx_data_t::data, HtpState_::flags, HTP_BODY_REQUEST, HTP_BODY_REQUEST_MULTIPART, HTP_BODY_REQUEST_POST, HTP_BODY_REQUEST_PUT, HTP_BOUNDARY_SET, htp_connp_get_user_data(), HTP_ERROR, HTP_FLAG_NEW_BODY_SET, HTP_M_POST, HTP_M_PUT, HTP_OK, HTP_REQUIRE_REQUEST_BODY, htp_tx_get_user_data(), htp_tx_set_user_data(), HtpBodyAppendChunk(), HtpBodyPrune(), HTPFree(), HTPMalloc(), HtpRequestBodyHandleMultipart(), HtpRequestBodySetupPUT(), htp_tx_data_t::len, HtpTxUserData_::operation, PrintRawDataFp(), HtpTxUserData_::request_body, HTPCfgRec_::request_body_limit, HtpTxUserData_::request_body_type, htp_tx_t::request_method_number, HtpTxUserData_::response_body_init, SC_ATOMIC_GET, SCEnter, SCLogDebug, SCReturnInt, STREAM_TOSERVER, HtpTxUserData_::tsflags, htp_tx_data_t::tx, and unlikely.
void HtpConfigCreateBackup (void)
void HtpConfigRestoreBackup (void)
void HTPConfigure (void)
Definition at line 2511 of file app-layer-htp.c.
References HTPCfgRec_::cfg, ConfGetNode(), htp_config_create(), HTPParseMemcap(), ConfNode_::name, HTPCfgRec_::next, next, SC_ERR_MEM_ALLOC, SCEnter, SCLogDebug, SCLogError, SCMalloc, SCRadixCreateRadixTree(), SCReturn, TAILQ_FIRST, and TAILQ_FOREACH.
Referenced by RegisterHTPParsers().
void HTPFreeConfig (void)
Clears the HTTP server configuration memory used by HTP library.
Definition at line 1960 of file app-layer-htp.c.
References AppLayerParserConfParserEnabled(), AppLayerProtoDetectConfProtoDetectionEnabled(), HTPCfgRec_::cfg, htp_config_destroy(), HTPCfgRec_::next, SCEnter, SCFree, SCRadixReleaseRadixTree(), and SCReturn.
Referenced by main().
void HTPParserRegisterTests (void)
Register the Unit tests for the HTTP protocol.
Definition at line 6178 of file app-layer-htp.c.
References HTPFileParserRegisterTests(), and HTPXFFParserRegisterTests().
Referenced by RegisterHTPParsers(), and RunUnittests().
void HTPStateFree (void *)
Function to frees the HTTP state memory and also frees the HTTP connection parser memory which was used by the HTP library.
Definition at line 339 of file app-layer-htp.c.
References BUG_ON, HtpState_::conn, HtpState_::connp, FileContainerFree(), HtpState_::files_tc, HtpState_::files_ts, HtpState_::flags, htp_connp_destroy_all(), HTP_FLAG_NEW_BODY_SET, htp_tx_get_user_data(), htp_tx_set_user_data(), HTPFree(), SCEnter, SCLogDebug, SCMutexLock, SCMutexUnlock, SCReturn, tx_id, and HtpState_::tx_with_detect_state_cnt.
Referenced by RegisterHTPParsers().
int HtpTransactionGetLoggableId (Flow *)
htp_tx_t* HTPTransactionMain (const HtpState *)
void RegisterHTPParsers (void)
Register the HTTP protocol and state handling functions to APP layer of the engine.
HTTP
Definition at line 2753 of file app-layer-htp.c.
References ALPROTO_HTTP, AppLayerParserConfParserEnabled(), AppLayerParserRegisterDetectStateFuncs(), AppLayerParserRegisterGetEventInfo(), AppLayerParserRegisterGetEventsFunc(), AppLayerParserRegisterGetFilesFunc(), AppLayerParserRegisterGetStateProgressCompletionStatus(), AppLayerParserRegisterGetStateProgressFunc(), AppLayerParserRegisterGetTx(), AppLayerParserRegisterGetTxCnt(), AppLayerParserRegisterHasEventsFunc(), AppLayerParserRegisterParser(), AppLayerParserRegisterParserAcceptableDataDirection(), AppLayerParserRegisterStateFuncs(), AppLayerParserRegisterTruncateFunc(), AppLayerParserRegisterTxFreeFunc(), AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), HTPConfigure(), HTPParserRegisterTests(), HTPStateFree(), HTPStateGetEventInfo(), SC_ATOMIC_INIT, SCEnter, SCLogInfo, SCReturn, and STREAM_TOCLIENT.
Referenced by AppLayerParserRegisterProtocolParsers().
SC_ATOMIC_DECLARE (uint32_t , htp_config_flags)