suricata: State support
State support
Files
file detect-engine-state.c
State based signature handling.
file detect-engine-state.h
Data structures and function prototypes for keeping state for the detection engine.
Macros
#define CASE_CODE(E) case E: return #E
#define MAX_STORED_TXID_OFFSET 127
Functions
DetectEngineState * DetectEngineStateAlloc (void)
Alloc a DetectEngineState object.
DetectEngineStateFlow * DetectEngineStateFlowAlloc (void)
void DetectEngineStateFree (DetectEngineState *state)
Frees a DetectEngineState object.
void DetectEngineStateFlowFree (DetectEngineStateFlow *state)
int DeStateFlowHasInspectableState (Flow *f, AppProto alproto, const uint8_t alversion, uint8_t flags)
Check if we need to inspect this state.
int DeStateDetectStartDetection (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Signature *s, Packet *p, Flow *f, uint8_t flags, AppProto alproto, const uint8_t alversion)
Match app layer sig list against app state and store relevant match information.
void DeStateDetectContinueDetection (ThreadVars *tv, DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Packet *p, Flow *f, uint8_t flags, AppProto alproto, const uint8_t alversion)
Continue DeState detection of the signatures stored in the state.
void DeStateUpdateInspectTransactionId (Flow *f, const uint8_t flags)
update flow's inspection id's
void DetectEngineStateReset (DetectEngineStateFlow *state, uint8_t direction)
Reset a DetectEngineState state.
void DetectEngineStateResetTxs (Flow *f)
Reset de state for active tx' To be used on detect engine reload.
void DeStateRegisterTests (void)
Detailed Description
It is possible to do matching on reconstructed applicative flow. This is done by this code. It uses the Flow structure to store the list of signatures to match on the reconstructed stream.
The Flow::de_state is a DetectEngineState structure. This is basically a containter for storage item of type DeStateStore. They contains an array of DeStateStoreItem which store the state of match for an individual signature identified by DeStateStoreItem::sid.
The state is constructed by DeStateDetectStartDetection() which also starts the matching. Work is continued by DeStateDetectContinueDetection().
Once a transaction has been analysed DeStateRestartDetection() is used to reset the structures.
Macro Definition Documentation
#define CASE_CODE (E) case E: return #E
convert enum to string
Definition at line 82 of file detect-engine-state.c.
#define MAX_STORED_TXID_OFFSET 127
The DetectEngineThreadCtx::de_state_sig_array contains 2 separate values:
the first bit tells the prefilter engine to bypass the rule (or not)
the other bits allow 'ContinueDetect' to specify an offset again the base tx id. This offset will then be used by 'StartDetect' to not inspect transactions again for the same signature.
The offset in (2) has a max value due to the limited data type. If it is set to max the code will fall back to a slower path that validates that we're not adding duplicate rules to the detection state.
Definition at line 94 of file detect-engine-state.c.
Referenced by DeStateDetectStartDetection().
Function Documentation
void DeStateDetectContinueDetection (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Packet * p, Flow * f, uint8_t flags, AppProto alproto, uint8_t alversion)
Continue DeState detection of the signatures stored in the state.
Parameters
tv Pointer to the threadvars.
de_ctx DetectEngineCtx instance.
det_ctx DetectEngineThreadCtx instance.
f Pointer to the flow.
flags Flags.
alproto App protocol.
alversion Current app layer version.
Definition at line 979 of file detect-engine-state.c.
References Flow_::alparser, AppLayerParserGetStateProgress(), AppLayerParserGetStateProgressCompletionStatus(), AppLayerParserGetTransactionInspectId(), AppLayerParserGetTx(), AppLayerParserGetTxCnt(), AppLayerParserGetTxDetectState(), AppLayerParserProtocolSupportsTxs(), DetectEngineStateDirection_::cnt, DetectEngineStateDirectionFlow_::cnt, Flow_::de_state, DE_STATE_CHUNK_SIZE, DetectEngineState_::dir_state, DetectEngineStateFlow_::dir_state, DetectEngineStateDirection_::flags, DetectEngineStateDirectionFlow_::flags, FlowGetAppState(), FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, DetectEngineStateDirection_::head, DetectEngineStateDirectionFlow_::head, DeStateStore_::next, DeStateStoreFlowRules_::next, Packet_::pcap_cnt, Flow_::proto, SCLogDebug, SigIntId, DeStateStore_::store, DeStateStoreFlowRules_::store, STREAM_TOSERVER, DetectEngineThreadCtx_::tx_id, and DetectEngineThreadCtx_::tx_id_set.
Referenced by SigMatchSignatures().
int DeStateDetectStartDetection (ThreadVars * tv, DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Signature * s, Packet * p, Flow * f, uint8_t flags, AppProto alproto, uint8_t alversion)
Match app layer sig list against app state and store relevant match information.
Parameters
tv Pointer to the threadvars.
de_ctx DetectEngineCtx instance.
det_ctx DetectEngineThreadCtx instance.
s Pointer to the signature.
f Pointer to the flow.
flags Flags.
alproto App protocol.
alversion Current app layer version.
Return values
>= 0 An integer value indicating the no of matches.
Definition at line 476 of file detect-engine-state.c.
References Flow_::alparser, ALPROTO_DCERPC, ALPROTO_SMB, ALPROTO_SMB2, app_inspection_engine, SigTableElmt_::AppLayerMatch, AppLayerParserGetStateProgress(), AppLayerParserGetStateProgressCompletionStatus(), AppLayerParserGetTransactionInspectId(), AppLayerParserGetTx(), AppLayerParserGetTxCnt(), AppLayerParserProtocolSupportsTxs(), DetectEngineAppInspectionEngine_::Callback, SMBState_::dcerpc, SMBState_::dcerpc_present, DE_STATE_FLAG_FULL_INSPECT, DE_STATE_FLAG_SIG_CANT_MATCH, DetectEngineThreadCtx_::de_state_sig_array, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH_FILESTORE, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_SM_LIST_AMATCH, DETECT_SM_LIST_DMATCH, DetectEngineInspectDcePayload(), DetectSignatureApplyActions(), Signature_::flags, FlowGetAppState(), FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, DetectEngineAppInspectionEngine_::inspect_flags, KEYWORD_PROFILING_END, KEYWORD_PROFILING_SET_LIST, KEYWORD_PROFILING_START, MAX_STORED_TXID_OFFSET, DetectEngineAppInspectionEngine_::next, SigMatch_::next, Signature_::num, PACKET_ALERT_FLAG_STATE_MATCH, PACKET_ALERT_FLAG_TX, PacketAlertAppend(), Packet_::pcap_cnt, Flow_::proto, Flow_::protomap, SCLogDebug, SIG_FLAG_NOALERT, sigmatch_table, DetectEngineAppInspectionEngine_::sm_list, Signature_::sm_lists, STREAM_TOSERVER, tx_id, DetectEngineThreadCtx_::tx_id, DetectEngineThreadCtx_::tx_id_set, and SigMatch_::type.
Referenced by SigMatchSignatures().
int DeStateFlowHasInspectableState (Flow * f, AppProto alproto, const uint8_t alversion, uint8_t flags)
Check if we need to inspect this state.
Check if a flow already contains(newly updated as well) de state.
State needs to be inspected if:
state has been updated
we already have de_state in progress
Return values
0 no inspectable state
1 inspectable state
2 inspectable state, but no update
Definition at line 376 of file detect-engine-state.c.
References Flow_::de_state, Flow_::detect_alversion, FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, SCLogDebug, STREAM_EOF, and STREAM_TOSERVER.
Referenced by SigMatchSignatures().
void DeStateRegisterTests (void)
Definition at line 2326 of file detect-engine-state.c.
Referenced by RunUnittests().
void DeStateUpdateInspectTransactionId (Flow * f, const uint8_t flags)
update flow's inspection id's
Update the inspect id.
Parameters
f unlocked flow
flags direction and disruption flags
Note
it is possible that f->alstate, f->alparser are NULL
Definition at line 1103 of file detect-engine-state.c.
References Flow_::alparser, Flow_::alproto, Flow_::alstate, AppLayerParserSetTransactionInspectId(), FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, and Flow_::proto.
Referenced by Detect(), and SigMatchSignatures().
DetectEngineState* DetectEngineStateAlloc (void)
Alloc a DetectEngineState object.
Return values
Alloc'd instance of DetectEngineState.
Definition at line 266 of file detect-engine-state.c.
References SCMalloc, and unlikely.
DetectEngineStateFlow* DetectEngineStateFlowAlloc (void)
Definition at line 276 of file detect-engine-state.c.
References SCMalloc, and unlikely.
void DetectEngineStateFlowFree (DetectEngineStateFlow * state)
Definition at line 305 of file detect-engine-state.c.
References DetectEngineStateFlow_::dir_state, DetectEngineStateDirectionFlow_::head, DeStateStoreFlowRules_::next, and SCFree.
void DetectEngineStateFree (DetectEngineState * state)
Frees a DetectEngineState object.
Parameters
state DetectEngineState instance to free.
Definition at line 286 of file detect-engine-state.c.
References DetectEngineState_::dir_state, DetectEngineStateDirection_::head, DeStateStore_::next, and SCFree.
void DetectEngineStateReset (DetectEngineStateFlow * state, uint8_t direction)
Reset a DetectEngineState state.
Parameters
state Pointer to the state(LOCKED).
direction Direction flags - STREAM_TOSERVER or STREAM_TOCLIENT.
Definition at line 1115 of file detect-engine-state.c.
References DetectEngineStateDirectionFlow_::cnt, DetectEngineStateFlow_::dir_state, and DetectEngineStateDirectionFlow_::flags.
Referenced by SigMatchSignatures().
void DetectEngineStateResetTxs (Flow * f)
Reset de state for active tx' To be used on detect engine reload.
Parameters
f write LOCKED flow
Definition at line 1135 of file detect-engine-state.c.
References Flow_::alparser, Flow_::alproto, AppLayerParserGetTransactionInspectId(), AppLayerParserGetTx(), AppLayerParserGetTxCnt(), AppLayerParserGetTxDetectState(), AppLayerParserProtocolSupportsTxs(), DetectEngineStateDirection_::cnt, DetectEngineState_::dir_state, DetectEngineStateDirection_::filestore_cnt, DetectEngineStateDirection_::flags, FlowGetAppState(), MIN, and Flow_::proto.
Referenced by SigMatchSignatures().