suricata: Packet decoding
Packet decoding
Code in charge of protocol decoding.
Files
file decode-erspan.c
file decode-ethernet.c
file decode-gre.c
file decode-icmpv4.c
file decode-icmpv6.c
file decode-ipv4.c
file decode-ipv6.c
file decode-null.c
file decode-ppp.c
file decode-pppoe.c
file decode-raw.c
file decode-sctp.c
file decode-sll.c
file decode-tcp.c
file decode-template.c
file decode-teredo.c
file decode-udp.c
file decode-vlan.c
file decode.c
Functions
int DecodeTunnel (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, uint8_t *pkt, uint16_t len, PacketQueue *pq, enum DecodeTunnelProto proto)
void PacketFree (Packet *p)
Return a malloced packet.
void PacketDecodeFinalize (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p)
Finalize decoding of a packet.
Packet * PacketGetFromAlloc (void)
Get a malloced packet.
void PacketFreeOrRelease (Packet *p)
Return a packet to where it was allocated.
Packet * PacketGetFromQueueOrAlloc (void)
Get a packet. We try to get a packet from the packetpool first, but if that is empty we alloc a packet that is free'd again after processing.
int PacketCallocExtPkt (Packet *p, int datalen)
int PacketCopyDataOffset (Packet *p, int offset, uint8_t *data, int datalen)
Copy data to Packet payload at given offset.
int PacketCopyData (Packet *p, uint8_t *pktdata, int pktlen)
Copy data to Packet payload and set packet length.
Packet * PacketTunnelPktSetup (ThreadVars *tv, DecodeThreadVars *dtv, Packet *parent, uint8_t *pkt, uint16_t len, enum DecodeTunnelProto proto, PacketQueue *pq)
Setup a pseudo packet (tunnel)
Packet * PacketDefragPktSetup (Packet *parent, uint8_t *pkt, uint16_t len, uint8_t proto)
Setup a pseudo packet (reassembled frags)
void PacketDefragPktSetupParent (Packet *parent)
inform defrag "parent" that a pseudo packet is now assosiated to it.
void DecodeRegisterPerfCounters (DecodeThreadVars *dtv, ThreadVars *tv)
void DecodeUpdatePacketCounters (ThreadVars *tv, const DecodeThreadVars *dtv, const Packet *p)
void AddressDebugPrint (Address *a)
Debug print function for printing addresses.
DecodeThreadVars * DecodeThreadVarsAlloc (ThreadVars *tv)
Alloc and setup DecodeThreadVars.
void DecodeThreadVarsFree (ThreadVars *tv, DecodeThreadVars *dtv)
int PacketSetData (Packet *p, uint8_t *pktdata, int pktlen)
Set data for Packet and set length when zeo copy is used.
const char * PktSrcToString (enum PktSrcEnum pkt_src)
void CaptureStatsUpdate (ThreadVars *tv, CaptureStats *s, const Packet *p)
void CaptureStatsSetup (ThreadVars *tv, CaptureStats *s)
Detailed Description
Code in charge of protocol decoding.
The task of decoding packets is made in different files and as Suricata is supporting encapsulation there is a potential recursivity in the call.
For each protocol a DecodePROTO function is provided. For example we have DecodeIPV4() for IPv4 and DecodePPP() for PPP.
These functions have all a pkt and and a len argument which are respectively a pointer to the protocol data and the length of this protocol data.
Attention
The pkt parameter must point to the effective data because it will be used later to set per protocol pointer like Packet::tcph
Function Documentation
void AddressDebugPrint (Address * a)
Debug print function for printing addresses.
Parameters
Address object
Todo:
IPv6
Definition at line 443 of file decode.c.
References Address_::family, PrintInet(), and SCLogDebug.
void CaptureStatsSetup (ThreadVars * tv, CaptureStats * s)
Definition at line 563 of file decode.c.
References CaptureStats_::counter_ips_accepted, CaptureStats_::counter_ips_blocked, CaptureStats_::counter_ips_rejected, CaptureStats_::counter_ips_replaced, and StatsRegisterCounter().
Referenced by VerdictNFQThreadInit().
void CaptureStatsUpdate (ThreadVars * tv, CaptureStats * s, const Packet * p)
Definition at line 550 of file decode.c.
References ACTION_DROP, ACTION_REJECT, ACTION_REJECT_BOTH, ACTION_REJECT_DST, CaptureStats_::counter_ips_accepted, CaptureStats_::counter_ips_blocked, CaptureStats_::counter_ips_rejected, CaptureStats_::counter_ips_replaced, Packet_::flags, PACKET_TEST_ACTION, PKT_STREAM_MODIFIED, StatsIncr(), and unlikely.
Referenced by VerdictNFQ().
void DecodeRegisterPerfCounters (DecodeThreadVars * dtv, ThreadVars * tv)
Definition at line 377 of file decode.c.
References DecodeThreadVars_::counter_avg_pkt_size, DecodeThreadVars_::counter_bytes, DecodeThreadVars_::counter_defrag_ipv4_fragments, DecodeThreadVars_::counter_defrag_ipv4_reassembled, DecodeThreadVars_::counter_defrag_ipv4_timeouts, DecodeThreadVars_::counter_defrag_ipv6_fragments, DecodeThreadVars_::counter_defrag_ipv6_reassembled, DecodeThreadVars_::counter_defrag_ipv6_timeouts, DecodeThreadVars_::counter_defrag_max_hit, DecodeThreadVars_::counter_erspan, DecodeThreadVars_::counter_eth, DecodeThreadVars_::counter_flow_memcap, DecodeThreadVars_::counter_gre, DecodeThreadVars_::counter_icmpv4, DecodeThreadVars_::counter_icmpv6, DecodeThreadVars_::counter_invalid, DecodeThreadVars_::counter_ipv4, DecodeThreadVars_::counter_ipv4inipv6, DecodeThreadVars_::counter_ipv6, DecodeThreadVars_::counter_ipv6inipv6, DecodeThreadVars_::counter_max_pkt_size, DecodeThreadVars_::counter_mpls, DecodeThreadVars_::counter_null, DecodeThreadVars_::counter_pkts, DecodeThreadVars_::counter_ppp, DecodeThreadVars_::counter_pppoe, DecodeThreadVars_::counter_raw, DecodeThreadVars_::counter_sctp, DecodeThreadVars_::counter_sll, DecodeThreadVars_::counter_tcp, DecodeThreadVars_::counter_teredo, DecodeThreadVars_::counter_udp, DecodeThreadVars_::counter_vlan, DecodeThreadVars_::counter_vlan_qinq, StatsRegisterAvgCounter(), StatsRegisterCounter(), and StatsRegisterMaxCounter().
Referenced by DecodeAFPThreadInit(), DecodeErfDagThreadInit(), DecodeErfFileThreadInit(), DecodeIPFWThreadInit(), DecodeNFQThreadInit(), DecodePcapFileThreadInit(), DecodePcapThreadInit(), DecodePfringThreadInit(), and NapatechDecodeThreadInit().
DecodeThreadVars* DecodeThreadVarsAlloc (ThreadVars * tv)
Alloc and setup DecodeThreadVars.
set config defaults
Definition at line 460 of file decode.c.
References DecodeThreadVars_::app_tctx, AppLayerGetCtxThread(), ConfGetBool(), DecodeThreadVarsFree(), DecodeThreadVars_::output_flow_thread_data, OutputFlowLogThreadInit(), SC_ERR_THREAD_INIT, SCLogDebug, SCLogError, SCMalloc, TM_ECODE_OK, and DecodeThreadVars_::vlan_disabled.
Referenced by DecodeAFPThreadInit(), DecodeErfDagThreadInit(), DecodeErfFileThreadInit(), DecodeIPFWThreadInit(), DecodeNFQThreadInit(), DecodePcapFileThreadInit(), DecodePcapThreadInit(), DecodePfringThreadInit(), and NapatechDecodeThreadInit().
void DecodeThreadVarsFree (ThreadVars * tv, DecodeThreadVars * dtv)
Definition at line 486 of file decode.c.
References DecodeThreadVars_::app_tctx, AppLayerDestroyCtxThread(), DecodeThreadVars_::output_flow_thread_data, OutputFlowLogThreadDeinit(), and SCFree.
Referenced by DecodeAFPThreadDeinit(), DecodeErfDagThreadDeinit(), DecodeErfFileThreadDeinit(), DecodeIPFWThreadDeinit(), DecodeNFQThreadDeinit(), DecodePcapFileThreadDeinit(), DecodePcapThreadDeinit(), DecodePfringThreadDeinit(), DecodeThreadVarsAlloc(), and NapatechDecodeThreadDeinit().
int DecodeTunnel (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, uint8_t * pkt, uint16_t len, PacketQueue * pq, enum DecodeTunnelProto proto)
Definition at line 69 of file decode.c.
References DECODE_TUNNEL_ERSPAN, DECODE_TUNNEL_ETHERNET, DECODE_TUNNEL_IPV4, DECODE_TUNNEL_IPV6, DECODE_TUNNEL_PPP, DECODE_TUNNEL_VLAN, DecodeERSPAN(), DecodeEthernet(), DecodeIPV4(), DecodeIPV6(), DecodePPP(), DecodeVLAN(), SCLogInfo, and TM_ECODE_OK.
Referenced by PacketTunnelPktSetup().
void DecodeUpdatePacketCounters (ThreadVars * tv, const DecodeThreadVars * dtv, const Packet * p)
Definition at line 426 of file decode.c.
References DecodeThreadVars_::counter_avg_pkt_size, DecodeThreadVars_::counter_bytes, DecodeThreadVars_::counter_max_pkt_size, DecodeThreadVars_::counter_pkts, GET_PKT_LEN, StatsAddUI64(), StatsIncr(), and StatsSetUI64().
Referenced by DecodeAFP(), DecodeErfDag(), DecodeErfFile(), DecodeIPFW(), DecodeNFQ(), DecodePcap(), DecodePcapFile(), DecodePfring(), and NapatechDecode().
int PacketCallocExtPkt (Packet * p, int datalen) inline
Definition at line 178 of file decode.c.
References Packet_::ext_pkt, SCCalloc, SET_PKT_LEN, and unlikely.
int PacketCopyData (Packet * p, uint8_t * pktdata, int pktlen) inline
Copy data to Packet payload and set packet length.
Parameters
Pointer to the Packet to modify
Pointer to the data to copy
Length of the data to copy
Definition at line 241 of file decode.c.
References PacketCopyDataOffset(), and SET_PKT_LEN.
Referenced by AFPRead(), AFPReadFromRing(), NapatechStreamLoop(), NFQSetupPkt(), PacketDefragPktSetup(), PacketTunnelPktSetup(), PcapCallbackLoop(), PcapFileCallbackLoop(), ReceiveIPFWLoop(), and StreamTcpPseudoSetup().
int PacketCopyDataOffset (Packet * p, int offset, uint8_t * data, int datalen) inline
Copy data to Packet payload at given offset.
This function copies data/payload to a Packet. It uses the space allocated at Packet creation (pointed by Packet::pkt) or allocate some memory (pointed by Packet::ext_pkt) if the data size is to big to fit in initial space (of size default_packet_size).
Parameters
Pointer to the Packet to modify
Offset of the copy relatively to payload of Packet
Pointer to the data to copy
Length of the data to copy
Definition at line 204 of file decode.c.
References default_packet_size, Packet_::ext_pkt, GET_PKT_DIRECT_DATA, GET_PKT_DIRECT_MAX_SIZE, MAX_PAYLOAD_SIZE, SCMalloc, SET_PKT_LEN, and unlikely.
Referenced by PacketCopyData().
void PacketDecodeFinalize (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p)
Finalize decoding of a packet.
This function needs to be call at the end of decode functions when decoding has been succesful.
Definition at line 109 of file decode.c.
References DecodeThreadVars_::counter_invalid, Packet_::flags, PKT_IS_INVALID, and StatsIncr().
Referenced by DecodeAFP(), DecodeErfDag(), DecodeErfFile(), DecodeIPFW(), DecodeNFQ(), DecodePcap(), DecodePcapFile(), DecodePfring(), and NapatechDecode().
Packet* PacketDefragPktSetup (Packet * parent, uint8_t * pkt, uint16_t len, uint8_t proto)
Setup a pseudo packet (reassembled frags)
Difference with PacketPseudoPktSetup is that this func doesn't increment the recursion level. It needs to be on the same level as the frags because we run the flow engine against this and we need to get the same flow.
Parameters
parent parent packet for this pseudo pkt
pkt raw packet data
len packet data length
proto protocol of the tunneled packet
Return values
p the pseudo packet or NULL if out of memory
Definition at line 327 of file decode.c.
References Packet_::datalink, PacketCopyData(), PacketGetFromQueueOrAlloc(), Packet_::recursion_level, Packet_::root, SCEnter, SCReturnPtr, SET_TUNNEL_PKT, Packet_::tenant_id, Packet_::ts, unlikely, Packet_::vlan_id, and Packet_::vlan_idx.
void PacketDefragPktSetupParent (Packet * parent)
inform defrag "parent" that a pseudo packet is now assosiated to it.
Definition at line 363 of file decode.c.
References DecodeSetNoPayloadInspectionFlag, SET_TUNNEL_PKT, and TUNNEL_INCR_PKT_TPR.
void PacketFree (Packet * p)
Return a malloced packet.
Definition at line 95 of file decode.c.
References PACKET_DESTRUCTOR, and SCFree.
Referenced by PacketFreeOrRelease(), PacketGetFromAlloc(), PacketPoolDestroy(), and PacketPoolReturnPacket().
void PacketFreeOrRelease (Packet * p)
Return a packet to where it was allocated.
Definition at line 148 of file decode.c.
References Packet_::flags, PacketFree(), PacketPoolReturnPacket(), and PKT_ALLOC.
Referenced by AFPReleasePacket().
Packet* PacketGetFromAlloc (void)
Get a malloced packet.
Return values
p packet, NULL on error
Definition at line 127 of file decode.c.
References Packet_::flags, PACKET_INITIALIZE, PACKET_PROFILING_START, PacketFree(), PKT_ALLOC, Packet_::ReleasePacket, SCLogDebug, SCMalloc, SIZE_OF_PACKET, and unlikely.
Referenced by PacketGetFromQueueOrAlloc(), and PacketPoolInit().
Packet* PacketGetFromQueueOrAlloc (void)
Get a packet. We try to get a packet from the packetpool first, but if that is empty we alloc a packet that is free'd again after processing.
Return values
p packet, NULL on error
Definition at line 163 of file decode.c.
References PACKET_PROFILING_START, PacketGetFromAlloc(), and PacketPoolGetPacket().
Referenced by AFPRead(), AFPReadFromRing(), NapatechStreamLoop(), PacketDefragPktSetup(), PacketTunnelPktSetup(), PcapCallbackLoop(), PcapFileCallbackLoop(), ReceiveErfFileLoop(), ReceiveIPFWLoop(), ReceivePfringLoop(), and StreamTcpPseudoSetup().
int PacketSetData (Packet * p, uint8_t * pktdata, int pktlen) inline
Set data for Packet and set length when zeo copy is used.
Parameters
Pointer to the Packet to modify
Pointer to the data
Length of the data
Definition at line 506 of file decode.c.
References Packet_::ext_pkt, Packet_::flags, PKT_ZERO_COPY, SET_PKT_LEN, and unlikely.
Referenced by AFPReadFromRing(), NFQSetupPkt(), and ReceivePfringLoop().
Packet* PacketTunnelPktSetup (ThreadVars * tv, DecodeThreadVars * dtv, Packet * parent, uint8_t * pkt, uint16_t len, enum DecodeTunnelProto proto, PacketQueue * pq)
Setup a pseudo packet (tunnel)
Parameters
parent parent packet for this pseudo pkt
pkt raw packet data
len packet data length
proto protocol of the tunneled packet
Return values
p the pseudo packet or NULL if out of memory
Definition at line 257 of file decode.c.
References Packet_::datalink, DecodeSetNoPayloadInspectionFlag, DecodeTunnel(), GET_PKT_DATA, GET_PKT_LEN, PacketCopyData(), PacketGetFromQueueOrAlloc(), Packet_::recursion_level, Packet_::root, SCEnter, SCReturnPtr, SET_TUNNEL_PKT, Packet_::tenant_id, TM_ECODE_OK, TmqhOutputPacketpool(), Packet_::ts, TUNNEL_INCR_PKT_TPR, unlikely, and UNSET_TUNNEL_PKT.
Referenced by DecodeGRE(), DecodeIPV4(), and DecodeTeredo().
const char* PktSrcToString (enum PktSrcEnum pkt_src)
Definition at line 518 of file decode.c.
References PKT_SRC_DECODER_GRE, PKT_SRC_DECODER_IPV4, PKT_SRC_DECODER_IPV6, PKT_SRC_DECODER_TEREDO, PKT_SRC_DEFRAG, PKT_SRC_FFR, PKT_SRC_STREAM_TCP_STREAM_END_PSEUDO, and PKT_SRC_WIRE.