suricata: src/host.c File Reference
host.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "util-debug.h"
#include "host.h"
#include "host-storage.h"
#include "host-bit.h"
#include "util-random.h"
#include "util-misc.h"
#include "util-byte.h"
#include "host-queue.h"
#include "detect-tag.h"
#include "detect-engine-tag.h"
#include "detect-engine-threshold.h"
#include "util-hash-lookup3.h"
Macros
#define HOST_DEFAULT_HASHSIZE 4096
#define HOST_DEFAULT_MEMCAP 16777216
#define HOST_DEFAULT_PREALLOC 1000
#define CMP_HOST(h, a) (CMP_ADDR(&(h)->a, (a)))
Functions
uint32_t HostSpareQueueGetSize (void)
void HostMoveToSpare (Host *h)
Host * HostAlloc (void)
void HostFree (Host *h)
Host * HostNew (Address *a)
void HostClearMemory (Host *h)
void HostInitConfig (char quiet)
initialize the configuration
void HostPrintStats (void)
print some host stats
void HostShutdown (void)
shutdown the flow engine
void HostCleanup (void)
Cleanup the host engine.
uint32_t HostGetKey (Address *a)
void HostInit (Host *h, Address *a)
void HostRelease (Host *h)
void HostLock (Host *h)
void HostUnlock (Host *h)
Host * HostGetHostFromHash (Address *a)
Host * HostLookupHostFromHash (Address *a)
look up a host in the hash
void HostRegisterUnittests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Information about hosts.
Definition in file host.c.
Macro Definition Documentation
#define CMP_HOST (h, a) (CMP_ADDR(&(h)->a, (a)))
Definition at line 368 of file host.c.
#define HOST_DEFAULT_HASHSIZE 4096
Definition at line 125 of file host.c.
Referenced by HostInitConfig().
#define HOST_DEFAULT_MEMCAP 16777216
Definition at line 126 of file host.c.
Referenced by HostInitConfig().
#define HOST_DEFAULT_PREALLOC 1000
Definition at line 127 of file host.c.
Referenced by HostInitConfig().
Function Documentation
Host* HostAlloc (void)
Definition at line 66 of file host.c.
References HOST_CHECK_MEMCAP, Host_::m, SC_ATOMIC_ADD, SC_ATOMIC_INIT, SCMalloc, SCMutexInit, and unlikely.
Referenced by HostInitConfig(), and HostNew().
void HostCleanup (void)
Cleanup the host engine.
Cleanup the host engine from tag and threshold.
Definition at line 304 of file host.c.
References HostConfig_::hash_size, Host_::hnext, host_config, host_hash, HostClearMemory(), HostFreeStorage(), HostMoveToSpare(), Host_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, Host_::iprep, and SC_ATOMIC_GET.
void HostClearMemory (Host * h)
Definition at line 114 of file host.c.
References HostFreeStorage(), HostStorageSize(), Host_::iprep, and SCFree.
Referenced by HostCleanup(), and HostFree().
void HostFree (Host * h)
Definition at line 87 of file host.c.
References HostClearMemory(), Host_::m, SC_ATOMIC_DESTROY, SC_ATOMIC_SUB, SCFree, and SCMutexDestroy.
Referenced by HostShutdown().
Host* HostGetHostFromHash (Address * a)
Definition at line 460 of file host.c.
References Host_::hnext, host_hash, HostGetKey(), HostIncrUsecnt, HostInit(), Host_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, Host_::m, and SCMutexLock.
Referenced by PacketAlertThreshold(), SRepLoadFileFromFD(), and TagHashAddTag().
uint32_t HostGetKey (Address * a)
Definition at line 350 of file host.c.
References Address_::family, HostConfig_::hash_rand, HostConfig_::hash_size, hashword(), and host_config.
Referenced by HostGetHostFromHash(), and HostLookupHostFromHash().
void HostInit (Host * h, Address * a)
Definition at line 429 of file host.c.
References Host_::a, COPY_ADDRESS, and HostIncrUsecnt.
Referenced by HostGetHostFromHash().
void HostInitConfig (char quiet)
initialize the configuration
Warning
Not thread safe
set config values for memcap, prealloc and hash_size
Definition at line 131 of file host.c.
References ByteExtractStringUint32(), ConfGet(), FALSE, HostConfig_::hash_rand, HostConfig_::hash_size, HOST_CHECK_MEMCAP, host_config, HOST_DEFAULT_HASHSIZE, HOST_DEFAULT_MEMCAP, HOST_DEFAULT_PREALLOC, host_hash, HostAlloc(), HostEnqueue(), HostQueueInit(), HostStorageSize(), HRLOCK_INIT, HostQueue_::len, HostConfig_::memcap, ParseSizeStringU64(), HostConfig_::prealloc, RandomTimePreseed(), SC_ATOMIC_ADD, SC_ATOMIC_GET, SC_ATOMIC_INIT, SC_ERR_FATAL, SC_ERR_HOST_INIT, SC_ERR_SIZE_PARSE, SCCalloc, SCLogDebug, SCLogError, SCLogInfo, unlikely, and WarnInvalidConfEntry.
Referenced by main().
void HostLock (Host * h)
Definition at line 441 of file host.c.
References Host_::m, and SCMutexLock.
Host* HostLookupHostFromHash (Address * a)
look up a host in the hash
Parameters
a address to look up
Return values
h LOCKED host or NULL
Definition at line 559 of file host.c.
References Host_::hnext, host_hash, HostGetKey(), HostIncrUsecnt, Host_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, Host_::m, and SCMutexLock.
Referenced by TagHandlePacket().
void HostMoveToSpare (Host * h)
Definition at line 60 of file host.c.
References HostEnqueue(), and SC_ATOMIC_SUB.
Referenced by HostCleanup().
Host* HostNew (Address * a)
Definition at line 99 of file host.c.
References Host_::a, COPY_ADDRESS, and HostAlloc().
void HostPrintStats (void)
print some host stats
Warning
Not thread safe
Definition at line 248 of file host.c.
References host_config, HostConfig_::memcap, SC_ATOMIC_GET, and SCLogInfo.
Referenced by HostShutdown(), and SRepInit().
void HostRegisterUnittests (void)
Definition at line 691 of file host.c.
References RegisterHostStorageTests().
Referenced by RunUnittests().
void HostRelease (Host * h)
Definition at line 435 of file host.c.
References HostDecrUsecnt, Host_::m, and SCMutexUnlock.
Referenced by PacketAlertThreshold(), SRepLoadFileFromFD(), TagHandlePacket(), and TagHashAddTag().
void HostShutdown (void)
shutdown the flow engine
Warning
Not thread safe
Definition at line 261 of file host.c.
References BUG_ON, HostConfig_::hash_size, Host_::hnext, host_config, host_hash, HostDequeue(), HostFree(), HostPrintStats(), HostQueueDestroy(), HRLOCK_DESTROY, SC_ATOMIC_DESTROY, SC_ATOMIC_GET, SC_ATOMIC_SUB, and SCFree.
Referenced by main().
uint32_t HostSpareQueueGetSize (void)
Definition at line 55 of file host.c.
References HostQueueLen().
Referenced by HostGetSpareCount().
void HostUnlock (Host * h)
Definition at line 446 of file host.c.
References Host_::m, and SCMutexUnlock.