suricata: src/host-storage.c File Reference
host-storage.c File Reference
#include "suricata-common.h"
#include "host-storage.h"
#include "util-unittest.h"
Functions
unsigned int HostStorageSize (void)
int HostStorageRegister (const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
Register a Host storage.
int HostSetStorageById (Host *h, int id, void *ptr)
Store a pointer in a given Host storage.
void * HostGetStorageById (Host *h, int id)
Get a value from a given Host storage.
void * HostAllocStorageById (Host *h, int id)
void HostFreeStorageById (Host *h, int id)
void HostFreeStorage (Host *h)
void RegisterHostStorageTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Host wrapper around storage api
Definition in file host-storage.c.
Function Documentation
void* HostAllocStorageById (Host * h, int id)
Definition at line 95 of file host-storage.c.
References STORAGE_HOST, and StorageAllocByIdPrealloc().
void HostFreeStorage (Host * h)
Definition at line 105 of file host-storage.c.
References HostStorageSize(), STORAGE_HOST, and StorageFreeAll().
Referenced by HostCleanup(), and HostClearMemory().
void HostFreeStorageById (Host * h, int id)
Definition at line 100 of file host-storage.c.
References STORAGE_HOST, and StorageFreeById().
unsigned int HostStorageSize (void)
Definition at line 30 of file host-storage.c.
References STORAGE_HOST, and StorageGetSize().
Referenced by HostClearMemory(), HostFreeStorage(), and HostInitConfig().
void RegisterHostStorageTests (void)
Definition at line 330 of file host-storage.c.
Referenced by HostRegisterUnittests().