suricata: src/host-queue.c File Reference
host-queue.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "debug.h"
#include "host-queue.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-print.h"
Functions
HostQueue * HostQueueInit (HostQueue *q)
HostQueue * HostQueueNew ()
void HostQueueDestroy (HostQueue *q)
Destroy a host queue.
void HostEnqueue (HostQueue *q, Host *h)
add a host to a queue
Host * HostDequeue (HostQueue *q)
remove a host from the queue
uint32_t HostQueueLen (HostQueue *q)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Host queue handler functions
Definition in file host-queue.c.
Function Documentation
Host* HostDequeue (HostQueue * q)
remove a host from the queue
Parameters
q queue
Return values
h host or NULL if empty list.
Definition at line 103 of file host-queue.c.
References HostQueue_::bot, BUG_ON, HQLOCK_LOCK, HQLOCK_UNLOCK, HostQueue_::len, Host_::lnext, Host_::lprev, and HostQueue_::top.
Referenced by HostShutdown().
void HostEnqueue (HostQueue * q, Host * h)
add a host to a queue
Parameters
q queue
h host
Definition at line 70 of file host-queue.c.
References HostQueue_::bot, BUG_ON, HQLOCK_LOCK, HQLOCK_UNLOCK, HostQueue_::len, Host_::lnext, Host_::lprev, and HostQueue_::top.
Referenced by HostInitConfig(), and HostMoveToSpare().
void HostQueueDestroy (HostQueue * q)
Destroy a host queue.
Parameters
q the host queue to destroy
Definition at line 59 of file host-queue.c.
References HQLOCK_DESTROY.
Referenced by HostShutdown().
HostQueue* HostQueueInit (HostQueue * q)
Definition at line 34 of file host-queue.c.
References HQLOCK_INIT.
Referenced by HostInitConfig(), and HostQueueNew().
uint32_t HostQueueLen (HostQueue * q)
Definition at line 136 of file host-queue.c.
References HQLOCK_LOCK, HQLOCK_UNLOCK, len, and HostQueue_::len.
Referenced by HostSpareQueueGetSize().
HostQueue* HostQueueNew ()
Definition at line 43 of file host-queue.c.
References HostQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.