suricata: src/host-queue.h File Reference
host-queue.h File Reference
#include "suricata-common.h"
#include "host.h"
Data Structures
struct HostQueue_
Macros
#define HQLOCK_MUTEX
#define HQLOCK_INIT(q) SCMutexInit(&(q)->m, NULL)
#define HQLOCK_DESTROY(q) SCMutexDestroy(&(q)->m)
#define HQLOCK_LOCK(q) SCMutexLock(&(q)->m)
#define HQLOCK_TRYLOCK(q) SCMutexTrylock(&(q)->m)
#define HQLOCK_UNLOCK(q) SCMutexUnlock(&(q)->m)
Typedefs
typedef struct HostQueue_ HostQueue
Functions
HostQueue * HostQueueNew ()
HostQueue * HostQueueInit (HostQueue *)
void HostQueueDestroy (HostQueue *)
Destroy a host queue.
void HostEnqueue (HostQueue *, Host *)
add a host to a queue
Host * HostDequeue (HostQueue *)
remove a host from the queue
uint32_t HostQueueLen (HostQueue *)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file host-queue.h.
Macro Definition Documentation
#define HQLOCK_DESTROY (q) SCMutexDestroy(&(q)->m)
Definition at line 66 of file host-queue.h.
Referenced by HostQueueDestroy(), and IPPairQueueDestroy().
#define HQLOCK_INIT (q) SCMutexInit(&(q)->m, NULL)
Definition at line 65 of file host-queue.h.
Referenced by HostQueueInit(), and IPPairQueueInit().
#define HQLOCK_LOCK (q) SCMutexLock(&(q)->m)
Definition at line 67 of file host-queue.h.
Referenced by HostDequeue(), HostEnqueue(), HostQueueLen(), IPPairDequeue(), IPPairEnqueue(), and IPPairQueueLen().
#define HQLOCK_MUTEX
Spinlocks or Mutex for the host queues.
Definition at line 32 of file host-queue.h.
#define HQLOCK_TRYLOCK (q) SCMutexTrylock(&(q)->m)
Definition at line 68 of file host-queue.h.
#define HQLOCK_UNLOCK (q) SCMutexUnlock(&(q)->m)
Definition at line 69 of file host-queue.h.
Referenced by HostDequeue(), HostEnqueue(), HostQueueLen(), IPPairDequeue(), IPPairEnqueue(), and IPPairQueueLen().
Typedef Documentation
typedef struct HostQueue_ HostQueue
Function Documentation
Host* HostDequeue (HostQueue * q)
remove a host from the queue
Parameters
q queue
Return values
h host or NULL if empty list.
Definition at line 103 of file host-queue.c.
References HostQueue_::bot, BUG_ON, HQLOCK_LOCK, HQLOCK_UNLOCK, HostQueue_::len, Host_::lnext, Host_::lprev, and HostQueue_::top.
Referenced by HostShutdown().
void HostEnqueue (HostQueue * q, Host * h)
add a host to a queue
Parameters
q queue
h host
Definition at line 70 of file host-queue.c.
References HostQueue_::bot, BUG_ON, HQLOCK_LOCK, HQLOCK_UNLOCK, HostQueue_::len, Host_::lnext, Host_::lprev, and HostQueue_::top.
Referenced by HostInitConfig(), and HostMoveToSpare().
void HostQueueDestroy (HostQueue * q)
Destroy a host queue.
Parameters
q the host queue to destroy
Definition at line 59 of file host-queue.c.
References HQLOCK_DESTROY.
Referenced by HostShutdown().
HostQueue* HostQueueInit (HostQueue *)
Definition at line 34 of file host-queue.c.
References HQLOCK_INIT.
Referenced by HostInitConfig(), and HostQueueNew().
uint32_t HostQueueLen (HostQueue *)
Definition at line 136 of file host-queue.c.
References HQLOCK_LOCK, HQLOCK_UNLOCK, len, and HostQueue_::len.
Referenced by HostSpareQueueGetSize().
HostQueue* HostQueueNew ()
Definition at line 43 of file host-queue.c.
References HostQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.