suricata: src/host-bit.h File Reference
host-bit.h File Reference
#include "host.h"
#include "util-var.h"
Functions
void HostBitInitCtx (void)
void HostBitRegisterTests (void)
int HostHasHostBits (Host *host)
int HostBitsTimedoutCheck (Host *h, struct timeval *ts)
void HostBitSet (Host *, uint16_t, uint32_t)
void HostBitUnset (Host *, uint16_t)
void HostBitToggle (Host *, uint16_t, uint32_t)
int HostBitIsset (Host *, uint16_t, uint32_t)
int HostBitIsnotset (Host *, uint16_t, uint32_t)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file host-bit.h.
Function Documentation
void HostBitInitCtx (void)
Definition at line 48 of file host-bit.c.
References HostBitFreeAll(), HostStorageRegister(), SC_ERR_HOST_INIT, and SCLogError.
Referenced by RunUnittests().
int HostBitIsnotset (Host * , uint16_t , uint32_t)
Definition at line 169 of file host-bit.c.
References XBit_::expire.
int HostBitIsset (Host * , uint16_t , uint32_t)
Definition at line 156 of file host-bit.c.
References XBit_::expire.
void HostBitRegisterTests (void)
Definition at line 488 of file host-bit.c.
Referenced by RunUnittests().
void HostBitSet (Host * , uint16_t , uint32_t)
Definition at line 130 of file host-bit.c.
int HostBitsTimedoutCheck (Host * h, struct timeval * ts)
Return values
1 host timed out wrt xbits
0 host still has active (non-expired) xbits
Definition at line 67 of file host-bit.c.
References DETECT_XBITS, XBit_::expire, HostGetStorageById(), GenericVar_::next, and GenericVar_::type.
void HostBitToggle (Host * , uint16_t , uint32_t)
Definition at line 146 of file host-bit.c.
void HostBitUnset (Host * , uint16_t)
Definition at line 138 of file host-bit.c.
int HostHasHostBits (Host * host)
Definition at line 58 of file host-bit.c.
References HostGetStorageById().