suricata: src/host.h File Reference
host.h File Reference
#include "decode.h"
#include "util-storage.h"
Data Structures
struct Host_
struct HostHashRow_
struct HostConfig_
Macros
#define HRLOCK_MUTEX
#define HRLOCK_TYPE SCMutex
#define HRLOCK_INIT(fb) SCMutexInit(&(fb)->lock, NULL)
#define HRLOCK_DESTROY(fb) SCMutexDestroy(&(fb)->lock)
#define HRLOCK_LOCK(fb) SCMutexLock(&(fb)->lock)
#define HRLOCK_TRYLOCK(fb) SCMutexTrylock(&(fb)->lock)
#define HRLOCK_UNLOCK(fb) SCMutexUnlock(&(fb)->lock)
#define HOST_VERBOSE 0
#define HOST_QUIET 1
#define HOST_CHECK_MEMCAP(size) ((((uint64_t)SC_ATOMIC_GET(host_memuse) + (uint64_t)(size)) <= host_config.memcap))
check if a memory alloc would fit in the memcap
#define HostIncrUsecnt(h) (void)SC_ATOMIC_ADD((h)->use_cnt, 1)
#define HostDecrUsecnt(h) (void)SC_ATOMIC_SUB((h)->use_cnt, 1)
#define HostReference(dst_h_ptr, h)
#define HostDeReference(src_h_ptr)
Typedefs
typedef struct Host_ Host
typedef struct HostConfig_ HostConfig
Functions
struct HostHashRow_ __attribute__ ((aligned(CLS))) HostHashRow
SC_ATOMIC_DECLARE (unsigned long long int, host_memuse)
SC_ATOMIC_DECLARE (unsigned int, host_counter)
SC_ATOMIC_DECLARE (unsigned int, host_prune_idx)
void HostInitConfig (char quiet)
initialize the configuration
void HostShutdown (void)
shutdown the flow engine
void HostCleanup (void)
Cleanup the host engine.
Host * HostLookupHostFromHash (Address *)
look up a host in the hash
Host * HostGetHostFromHash (Address *)
void HostRelease (Host *)
void HostLock (Host *)
void HostClearMemory (Host *)
void HostMoveToSpare (Host *)
uint32_t HostSpareQueueGetSize (void)
void HostPrintStats (void)
print some host stats
void HostRegisterUnittests (void)
Host * HostAlloc ()
void HostFree ()
void HostUnlock (Host *h)
Variables
HRLOCK_TYPE lock
Host * head
Host * tail
HostHashRow * host_hash
HostConfig host_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file host.h.
Macro Definition Documentation
#define HOST_CHECK_MEMCAP (size) ((((uint64_t)SC_ATOMIC_GET(host_memuse) + (uint64_t)(size)) <= host_config.memcap))
check if a memory alloc would fit in the memcap
Parameters
size memory allocation size to check
Return values
1 it fits
0 no fit
Definition at line 109 of file host.h.
Referenced by HostAlloc(), and HostInitConfig().
#define HOST_QUIET 1
Definition at line 93 of file host.h.
#define HOST_VERBOSE 0
Definition at line 92 of file host.h.
Referenced by main().
#define HostDecrUsecnt (h) (void)SC_ATOMIC_SUB((h)->use_cnt, 1)
Definition at line 114 of file host.h.
Referenced by HostRelease(), and SRepHostTimedOut().
#define HostDeReference (src_h_ptr)
Value:
do {               \
        if (*(src_h_ptr) != NULL) {                   \
            HostDecrUsecnt(*(src_h_ptr));             \
            *(src_h_ptr) = NULL;                      \
        }                                             \
    } while (0)
Definition at line 124 of file host.h.
#define HostIncrUsecnt (h) (void)SC_ATOMIC_ADD((h)->use_cnt, 1)
Definition at line 112 of file host.h.
Referenced by HostGetHostFromHash(), HostInit(), HostLookupHostFromHash(), and SRepLoadFileFromFD().
#define HostReference (dst_h_ptr, h)
Value:
do {            \
        if ((h) != NULL) {                          \
            HostIncrUsecnt((h));                    \
            *(dst_h_ptr) = h;                       \
        }                                           \
    } while (0)
Definition at line 117 of file host.h.
#define HRLOCK_DESTROY (fb) SCMutexDestroy(&(fb)->lock)
Definition at line 50 of file host.h.
Referenced by HostShutdown(), and IPPairShutdown().
#define HRLOCK_INIT (fb) SCMutexInit(&(fb)->lock, NULL)
Definition at line 49 of file host.h.
Referenced by HostInitConfig(), and IPPairInitConfig().
#define HRLOCK_LOCK (fb) SCMutexLock(&(fb)->lock)
Definition at line 51 of file host.h.
Referenced by HostCleanup(), HostGetHostFromHash(), HostLookupHostFromHash(), IPPairCleanup(), IPPairGetIPPairFromHash(), and IPPairLookupIPPairFromHash().
#define HRLOCK_MUTEX
Spinlocks or Mutex for the flow buckets.
Definition at line 32 of file host.h.
#define HRLOCK_TRYLOCK (fb) SCMutexTrylock(&(fb)->lock)
Definition at line 52 of file host.h.
Referenced by HostTimeoutHash(), and IPPairTimeoutHash().
#define HRLOCK_TYPE SCMutex
Definition at line 48 of file host.h.
#define HRLOCK_UNLOCK (fb) SCMutexUnlock(&(fb)->lock)
Definition at line 53 of file host.h.
Referenced by HostCleanup(), HostGetHostFromHash(), HostLookupHostFromHash(), HostTimeoutHash(), IPPairCleanup(), IPPairGetIPPairFromHash(), IPPairLookupIPPairFromHash(), and IPPairTimeoutHash().
Typedef Documentation
typedef struct Host_ Host
typedef struct HostConfig_ HostConfig
Function Documentation
struct HostHashRow_ __attribute__ ((aligned(CLS)))
Host* HostAlloc ()
Definition at line 66 of file host.c.
References HOST_CHECK_MEMCAP, Host_::m, SC_ATOMIC_ADD, SC_ATOMIC_INIT, SCMalloc, SCMutexInit, and unlikely.
Referenced by HostInitConfig(), and HostNew().
void HostCleanup (void)
Cleanup the host engine.
Cleanup the host engine from tag and threshold.
Definition at line 304 of file host.c.
References HostConfig_::hash_size, Host_::hnext, host_config, host_hash, HostClearMemory(), HostFreeStorage(), HostMoveToSpare(), Host_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, Host_::iprep, and SC_ATOMIC_GET.
void HostClearMemory (Host *)
Definition at line 114 of file host.c.
References HostFreeStorage(), HostStorageSize(), Host_::iprep, and SCFree.
Referenced by HostCleanup(), and HostFree().
void HostFree ()
Host* HostGetHostFromHash (Address *)
Definition at line 460 of file host.c.
References Host_::hnext, host_hash, HostGetKey(), HostIncrUsecnt, HostInit(), Host_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, Host_::m, and SCMutexLock.
Referenced by PacketAlertThreshold(), SRepLoadFileFromFD(), and TagHashAddTag().
void HostInitConfig (char quiet)
initialize the configuration
Warning
Not thread safe
set config values for memcap, prealloc and hash_size
Definition at line 131 of file host.c.
References ByteExtractStringUint32(), ConfGet(), FALSE, HostConfig_::hash_rand, HostConfig_::hash_size, HOST_CHECK_MEMCAP, host_config, HOST_DEFAULT_HASHSIZE, HOST_DEFAULT_MEMCAP, HOST_DEFAULT_PREALLOC, host_hash, HostAlloc(), HostEnqueue(), HostQueueInit(), HostStorageSize(), HRLOCK_INIT, HostQueue_::len, HostConfig_::memcap, ParseSizeStringU64(), HostConfig_::prealloc, RandomTimePreseed(), SC_ATOMIC_ADD, SC_ATOMIC_GET, SC_ATOMIC_INIT, SC_ERR_FATAL, SC_ERR_HOST_INIT, SC_ERR_SIZE_PARSE, SCCalloc, SCLogDebug, SCLogError, SCLogInfo, unlikely, and WarnInvalidConfEntry.
Referenced by main().
void HostLock (Host *)
Definition at line 441 of file host.c.
References Host_::m, and SCMutexLock.
Host* HostLookupHostFromHash (Address * a)
look up a host in the hash
Parameters
a address to look up
Return values
h LOCKED host or NULL
Definition at line 559 of file host.c.
References Host_::hnext, host_hash, HostGetKey(), HostIncrUsecnt, Host_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, Host_::m, and SCMutexLock.
Referenced by TagHandlePacket().
void HostMoveToSpare (Host *)
Definition at line 60 of file host.c.
References HostEnqueue(), and SC_ATOMIC_SUB.
Referenced by HostCleanup().
void HostPrintStats (void)
print some host stats
Warning
Not thread safe
Definition at line 248 of file host.c.
References host_config, HostConfig_::memcap, SC_ATOMIC_GET, and SCLogInfo.
Referenced by HostShutdown(), and SRepInit().
void HostRegisterUnittests (void)
Definition at line 691 of file host.c.
References RegisterHostStorageTests().
Referenced by RunUnittests().
void HostRelease (Host *)
Definition at line 435 of file host.c.
References HostDecrUsecnt, Host_::m, and SCMutexUnlock.
Referenced by PacketAlertThreshold(), SRepLoadFileFromFD(), TagHandlePacket(), and TagHashAddTag().
void HostShutdown (void)
shutdown the flow engine
Warning
Not thread safe
Definition at line 261 of file host.c.
References BUG_ON, HostConfig_::hash_size, Host_::hnext, host_config, host_hash, HostDequeue(), HostFree(), HostPrintStats(), HostQueueDestroy(), HRLOCK_DESTROY, SC_ATOMIC_DESTROY, SC_ATOMIC_GET, SC_ATOMIC_SUB, and SCFree.
Referenced by main().
uint32_t HostSpareQueueGetSize (void)
Definition at line 55 of file host.c.
References HostQueueLen().
Referenced by HostGetSpareCount().
void HostUnlock (Host * h)
Definition at line 446 of file host.c.
References Host_::m, and SCMutexUnlock.
SC_ATOMIC_DECLARE (unsigned long long int, host_memuse)
SC_ATOMIC_DECLARE (unsigned int, host_counter)
SC_ATOMIC_DECLARE (unsigned int, host_prune_idx)
Variable Documentation
Host* head
Definition at line 693 of file host.h.
HostConfig host_config
Definition at line 131 of file host.h.
Referenced by HostCleanup(), HostGetKey(), HostInitConfig(), HostPrintStats(), HostShutdown(), and HostTimeoutHash().
HostHashRow* host_hash
host hash table
Definition at line 90 of file host.h.
Referenced by HostCleanup(), HostGetHostFromHash(), HostInitConfig(), HostLookupHostFromHash(), HostShutdown(), and HostTimeoutHash().
HRLOCK_TYPE lock
Definition at line 692 of file host.h.
Host* tail
Definition at line 694 of file host.h.