suricata: libhtp/htp/htp_parsers.c File Reference
htp_parsers.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Functions
int htp_parse_protocol (bstr *protocol)
int htp_parse_status (bstr *status)
int htp_parse_authorization_digest (htp_connp_t *connp, htp_header_t *auth_header)
int htp_parse_authorization_basic (htp_connp_t *connp, htp_header_t *auth_header)
int htp_parse_authorization (htp_connp_t *connp)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_parsers.c.
Function Documentation
int htp_parse_authorization (htp_connp_t * connp)
Parses Authorization request header.
Parameters
[in] connp
Definition at line 163 of file htp_parsers.c.
References bstr_begins_with_c_nocase(), HTP_AUTH_BASIC, HTP_AUTH_DIGEST, HTP_AUTH_NONE, HTP_AUTH_UNRECOGNIZED, HTP_OK, htp_parse_authorization_basic(), htp_parse_authorization_digest(), htp_table_get_c(), htp_connp_t::in_tx, htp_tx_t::request_auth_type, htp_tx_t::request_headers, and htp_header_t::value.
int htp_parse_authorization_basic (htp_connp_t * connp, htp_header_t * auth_header)
Parses Basic Authorization request header.
Parameters
[in] connp
[in] auth_header
Definition at line 120 of file htp_parsers.c.
References bstr_dup_ex(), bstr_free(), bstr_index_of_c(), bstr_len, bstr_ptr, data, htp_base64_decode_mem(), HTP_DECLINED, HTP_ERROR, HTP_OK, htp_connp_t::in_tx, len, htp_tx_t::request_auth_password, htp_tx_t::request_auth_username, and htp_header_t::value.
Referenced by htp_parse_authorization().
int htp_parse_authorization_digest (htp_connp_t * connp, htp_header_t * auth_header)
Parses Digest Authorization request header.
Parameters
[in] connp
[in] auth_header
Definition at line 97 of file htp_parsers.c.
References bstr_index_of_c(), bstr_len, bstr_ptr, data, HTP_DECLINED, htp_extract_quoted_string_as_bstr(), htp_connp_t::in_tx, len, htp_tx_t::request_auth_username, and htp_header_t::value.
Referenced by htp_parse_authorization().
int htp_parse_protocol (bstr * protocol)
Determines protocol number from a textual representation (i.e., "HTTP/1.1"). This function will only understand a properly formatted protocol information. It does not try to be flexible.
Parameters
[in] protocol
Returns
Protocol version or PROTOCOL_UNKNOWN.
Definition at line 51 of file htp_parsers.c.
References bstr_len, bstr_ptr, HTP_PROTOCOL_0_9, HTP_PROTOCOL_1_0, HTP_PROTOCOL_1_1, and HTP_PROTOCOL_INVALID.
Referenced by htp_parse_request_line_generic_ex(), and htp_parse_response_line_generic().
int htp_parse_status (bstr * status)
Determines the numerical value of a response status given as a string.
Parameters
[in] status
Returns
Status code on success, or -1 on error.
Definition at line 87 of file htp_parsers.c.
References bstr_len, bstr_ptr, and htp_parse_positive_integer_whitespace().
Referenced by htp_parse_response_line_generic().