suricata: libhtp/htp/htp_cookies.c File Reference
htp_cookies.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Functions
int htp_parse_single_cookie_v0 (htp_connp_t *connp, unsigned char *data, size_t len)
htp_status_t htp_parse_cookies_v0 (htp_connp_t *connp)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_cookies.c.
Function Documentation
htp_status_t htp_parse_cookies_v0 (htp_connp_t * connp)
Parses the Cookie request header in v0 format.
Parameters
[in] connp
Returns
HTP_OK on success, HTP_ERROR on error
Definition at line 88 of file htp_cookies.c.
References bstr_len, bstr_ptr, data, HTP_ERROR, HTP_OK, htp_parse_single_cookie_v0(), htp_table_create(), htp_table_get_c(), htp_connp_t::in_tx, len, htp_tx_t::request_cookies, htp_tx_t::request_headers, and htp_header_t::value.
int htp_parse_single_cookie_v0 (htp_connp_t * connp, unsigned char * data, size_t len)
Parses a single v0 request cookie and places the results into tx->request_cookies.
Parameters
[in] connp
[in] data
[in] len
Returns
HTP_OK on success, HTP_ERROR on error.
Definition at line 51 of file htp_cookies.c.
References bstr_dup_c(), bstr_dup_mem(), bstr_free(), HTP_ERROR, HTP_OK, htp_table_addn(), htp_connp_t::in_tx, and htp_tx_t::request_cookies.
Referenced by htp_parse_cookies_v0().