suricata: libhtp/htp/htp_multipart.h File Reference
htp_multipart.h File Reference
#include "bstr.h"
#include "htp.h"
#include "htp_table.h"
Data Structures
struct htp_multipart_t
struct htp_multipart_part_t
Macros
#define HTP_MULTIPART_LF_LINE 0x0001
#define HTP_MULTIPART_CRLF_LINE 0x0002
#define HTP_MULTIPART_BBOUNDARY_LWS_AFTER 0x0004
#define HTP_MULTIPART_BBOUNDARY_NLWS_AFTER 0x0008
#define HTP_MULTIPART_HAS_PREAMBLE 0x0010
#define HTP_MULTIPART_HAS_EPILOGUE 0x0020
#define HTP_MULTIPART_SEEN_LAST_BOUNDARY 0x0040
#define HTP_MULTIPART_PART_AFTER_LAST_BOUNDARY 0x0080
#define HTP_MULTIPART_INCOMPLETE 0x0100
#define HTP_MULTIPART_HBOUNDARY_INVALID 0x0200
#define HTP_MULTIPART_HBOUNDARY_UNUSUAL 0x0400
#define HTP_MULTIPART_HBOUNDARY_QUOTED 0x0800
#define HTP_MULTIPART_PART_HEADER_FOLDING 0x1000
#define HTP_MULTIPART_PART_UNKNOWN 0x2000
#define HTP_MULTIPART_PART_HEADER_REPEATED 0x4000
#define HTP_MULTIPART_PART_HEADER_UNKNOWN 0x8000
#define HTP_MULTIPART_PART_HEADER_INVALID 0x10000
#define HTP_MULTIPART_CD_TYPE_INVALID 0x20000
#define HTP_MULTIPART_CD_PARAM_REPEATED 0x40000
#define HTP_MULTIPART_CD_PARAM_UNKNOWN 0x80000
#define HTP_MULTIPART_CD_SYNTAX_INVALID 0x100000
#define HTP_MULTIPART_PART_INCOMPLETE 0x200000
#define HTP_MULTIPART_NUL_BYTE 0x400000
#define HTP_MULTIPART_CD_INVALID
#define HTP_MULTIPART_PART_INVALID
#define HTP_MULTIPART_INVALID
#define HTP_MULTIPART_UNUSUAL
#define HTP_MULTIPART_UNUSUAL_PARANOID
#define HTP_MULTIPART_MIME_TYPE "multipart/form-data"
Typedefs
typedef struct htp_mpartp_t htp_mpartp_t
typedef struct htp_multipart_t htp_multipart_t
typedef struct htp_multipart_part_t htp_multipart_part_t
Enumerations
enum htp_multipart_type_t {
MULTIPART_PART_UNKNOWN = 0, MULTIPART_PART_TEXT = 1, MULTIPART_PART_FILE = 2, MULTIPART_PART_PREAMBLE = 3,
MULTIPART_PART_EPILOGUE = 4
}
Functions
htp_mpartp_t * htp_mpartp_create (htp_cfg_t *cfg, bstr *boundary, uint64_t flags)
htp_status_t htp_mpartp_find_boundary (bstr *content_type, bstr **boundary, uint64_t *multipart_flags)
htp_multipart_t * htp_mpartp_get_multipart (htp_mpartp_t *parser)
void htp_mpartp_destroy (htp_mpartp_t *parser)
htp_status_t htp_mpartp_finalize (htp_mpartp_t *parser)
htp_status_t htp_mpartp_parse (htp_mpartp_t *parser, const void *data, size_t len)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_multipart.h.
Macro Definition Documentation
#define HTP_MULTIPART_BBOUNDARY_LWS_AFTER 0x0004
Seen LWS after a boundary instance in the body. Unusual.
Definition at line 64 of file htp_multipart.h.
Referenced by htp_mpartp_parse().
#define HTP_MULTIPART_BBOUNDARY_NLWS_AFTER 0x0008
Seen non-LWS content after a boundary instance in the body. Highly unusual.
Definition at line 67 of file htp_multipart.h.
Referenced by htp_mpartp_parse().
#define HTP_MULTIPART_CD_INVALID
Value:
(\
    HTP_MULTIPART_CD_TYPE_INVALID | \
    HTP_MULTIPART_CD_PARAM_REPEATED | \
    HTP_MULTIPART_CD_PARAM_UNKNOWN | \
    HTP_MULTIPART_CD_SYNTAX_INVALID )
A collection of flags that all indicate an invalid C-D header.
Definition at line 158 of file htp_multipart.h.
#define HTP_MULTIPART_CD_PARAM_REPEATED 0x40000
Content-Disposition part header with multiple parameters with the same name.
Definition at line 139 of file htp_multipart.h.
Referenced by htp_mpart_part_parse_c_d().
#define HTP_MULTIPART_CD_PARAM_UNKNOWN 0x80000
Unknown Content-Disposition parameter.
Definition at line 142 of file htp_multipart.h.
Referenced by htp_mpart_part_parse_c_d().
#define HTP_MULTIPART_CD_SYNTAX_INVALID 0x100000
Invalid Content-Disposition syntax.
Definition at line 145 of file htp_multipart.h.
Referenced by htp_mpart_part_parse_c_d().
#define HTP_MULTIPART_CD_TYPE_INVALID 0x20000
Part type specified in the C-D header is neither MULTIPART_PART_TEXT nor MULTIPART_PART_FILE.
Definition at line 136 of file htp_multipart.h.
#define HTP_MULTIPART_CRLF_LINE 0x0002
Seen a CRLF line in the payload. This is normal and expected.
Definition at line 61 of file htp_multipart.h.
Referenced by htp_mpartp_parse().
#define HTP_MULTIPART_HAS_EPILOGUE 0x0020
Payload has an epilogue part. Unusual.
Definition at line 77 of file htp_multipart.h.
Referenced by htp_mpart_part_finalize_data().
#define HTP_MULTIPART_HAS_PREAMBLE 0x0010
Payload has a preamble part. Might not be that unusual.
Definition at line 72 of file htp_multipart.h.
#define HTP_MULTIPART_HBOUNDARY_INVALID 0x0200
The boundary in the Content-Type header is invalid.
Definition at line 102 of file htp_multipart.h.
Referenced by htp_mpartp_find_boundary().
#define HTP_MULTIPART_HBOUNDARY_QUOTED 0x0800
The boundary in the Content-Type header is quoted. This is very unusual, and may be indicative of an evasion attempt.
Definition at line 115 of file htp_multipart.h.
#define HTP_MULTIPART_HBOUNDARY_UNUSUAL 0x0400
The boundary in the Content-Type header is unusual. This may mean that evasion is attempted, but it could also mean that we have encountered a client that does not do things in the way it should.
Definition at line 109 of file htp_multipart.h.
Referenced by htp_mpartp_find_boundary().
#define HTP_MULTIPART_INCOMPLETE 0x0100
The payloads ends abruptly, without proper termination. Can occur if the client gives up, or if the connection is interrupted. When this flag is raised, HTP_MULTIPART_PART_INCOMPLETE will also be raised for the part that was only partially processed. (But the opposite may not always be the case – there are other ways in which a part can be left incomplete.)
Definition at line 99 of file htp_multipart.h.
Referenced by htp_mpartp_finalize().
#define HTP_MULTIPART_INVALID
Value:
(\
    HTP_MULTIPART_PART_INVALID | \
    HTP_MULTIPART_PART_AFTER_LAST_BOUNDARY | \
    HTP_MULTIPART_INCOMPLETE | \
    HTP_MULTIPART_HBOUNDARY_INVALID )
A collection of flags that all indicate an invalid Multipart payload.
Definition at line 175 of file htp_multipart.h.
#define HTP_MULTIPART_LF_LINE 0x0001
Seen a LF line in the payload. LF lines are not allowed, but some clients do use them and some backends do accept them. Mixing LF and CRLF lines within some payload might be unusual.
Definition at line 58 of file htp_multipart.h.
Referenced by htp_mpartp_parse().
#define HTP_MULTIPART_MIME_TYPE "multipart/form-data"
Definition at line 197 of file htp_multipart.h.
#define HTP_MULTIPART_NUL_BYTE 0x400000
A NUL byte was seen in a part header area.
Definition at line 155 of file htp_multipart.h.
Referenced by htp_mpartp_parse_header().
#define HTP_MULTIPART_PART_AFTER_LAST_BOUNDARY 0x0080
There was a part after the last boundary. This is highly irregular and indicative of evasion.
Definition at line 91 of file htp_multipart.h.
Referenced by htp_mpart_part_finalize_data(), and htp_mpartp_parse().
#define HTP_MULTIPART_PART_HEADER_FOLDING 0x1000
Header folding was used in part headers. Very unusual.
Definition at line 118 of file htp_multipart.h.
Referenced by htp_mpart_part_handle_data().
#define HTP_MULTIPART_PART_HEADER_INVALID 0x10000
Invalid part header encountered.
Definition at line 133 of file htp_multipart.h.
Referenced by htp_mpartp_parse_header().
#define HTP_MULTIPART_PART_HEADER_REPEATED 0x4000
There was a repeated part header, possibly in an attempt to confuse the parser. Very unusual.
Definition at line 127 of file htp_multipart.h.
Referenced by htp_mpartp_parse_header().
#define HTP_MULTIPART_PART_HEADER_UNKNOWN 0x8000
Unknown part header encountered.
Definition at line 130 of file htp_multipart.h.
Referenced by htp_mpartp_parse_header().
#define HTP_MULTIPART_PART_INCOMPLETE 0x200000
There is an abruptly terminated part. This can happen when the payload itself is abruptly terminated (in which case HTP_MULTIPART_INCOMPLETE) will be raised. However, it can also happen when a boundary is seen before any part data.
Definition at line 152 of file htp_multipart.h.
Referenced by htp_mpart_part_finalize_data().
#define HTP_MULTIPART_PART_INVALID
Value:
(\
    HTP_MULTIPART_CD_INVALID | \
    HTP_MULTIPART_NUL_BYTE | \
    HTP_MULTIPART_PART_UNKNOWN | \
    HTP_MULTIPART_PART_HEADER_REPEATED | \
    HTP_MULTIPART_PART_INCOMPLETE | \
    HTP_MULTIPART_PART_HEADER_UNKNOWN | \
    HTP_MULTIPART_PART_HEADER_INVALID )
A collection of flags that all indicate an invalid part.
Definition at line 165 of file htp_multipart.h.
#define HTP_MULTIPART_PART_UNKNOWN 0x2000
A part of unknown type was encountered, which probably means that the part is lacking a Content-Disposition header, or that the header is invalid. Highly unusual.
Definition at line 124 of file htp_multipart.h.
Referenced by htp_mpart_part_finalize_data(), and htp_mpart_part_parse_c_d().
#define HTP_MULTIPART_SEEN_LAST_BOUNDARY 0x0040
The last boundary was seen in the payload. Absence of the last boundary may not break parsing with some (most?) backends, but it means that the payload is not well formed. Can occur if the client gives up, or if the connection is interrupted. Incomplete payloads should be blocked whenever possible.
Definition at line 85 of file htp_multipart.h.
Referenced by htp_mpart_part_finalize_data(), htp_mpart_part_handle_data(), and htp_mpartp_parse().
#define HTP_MULTIPART_UNUSUAL
Value:
(\
    HTP_MULTIPART_INVALID | \
    HTP_MULTIPART_PART_HEADER_FOLDING | \
    HTP_MULTIPART_BBOUNDARY_NLWS_AFTER | \
    HTP_MULTIPART_HAS_EPILOGUE | \
    HTP_MULTIPART_HBOUNDARY_UNUSUAL \
    HTP_MULTIPART_HBOUNDARY_QUOTED )
A collection of flags that all indicate an unusual Multipart payload.
Definition at line 182 of file htp_multipart.h.
#define HTP_MULTIPART_UNUSUAL_PARANOID
Value:
(\
    HTP_MULTIPART_UNUSUAL | \
    HTP_MULTIPART_LF_LINE | \
    HTP_MULTIPART_BBOUNDARY_LWS_AFTER | \
    HTP_MULTIPART_HAS_PREAMBLE )
A collection of flags that all indicate an unusual Multipart payload, with a low sensitivity to irregularities.
Definition at line 191 of file htp_multipart.h.
Typedef Documentation
typedef struct htp_mpartp_t htp_mpartp_t
Holds multipart parser configuration and state. Private.
Definition at line 223 of file htp_multipart.h.
typedef struct htp_multipart_part_t htp_multipart_part_t
Holds information related to a part.
typedef struct htp_multipart_t htp_multipart_t
Holds information related to a multipart body.
Enumeration Type Documentation
enum htp_multipart_type_t
Enumerator
MULTIPART_PART_UNKNOWN
Unknown part.
MULTIPART_PART_TEXT
Text (parameter) part.
MULTIPART_PART_FILE
File part.
MULTIPART_PART_PREAMBLE
Free-text part before the first boundary.
MULTIPART_PART_EPILOGUE
Free-text part after the last boundary.
Definition at line 199 of file htp_multipart.h.
Function Documentation
htp_mpartp_t* htp_mpartp_create (htp_cfg_t * cfg, bstr * boundary, uint64_t flags)
Creates a new multipart/form-data parser. On a successful invocation, the ownership of the boundary parameter is transferred to the parser.
Parameters
[in] cfg
[in] boundary
[in] flags
Returns
New parser instance, or NULL on memory allocation failure.
Definition at line 885 of file htp_multipart.c.
References htp_mpartp_t::boundary_pieces, bstr_builder_create(), bstr_free(), bstr_len, bstr_ptr, htp_mpartp_t::cfg, DEFAULT_FILE_EXTRACT_LIMIT, htp_mpartp_t::extract_dir, htp_mpartp_t::extract_files, htp_mpartp_t::extract_limit, htp_cfg_t::extract_request_files, htp_cfg_t::extract_request_files_limit, flags, htp_multipart_t::flags, htp_mpartp_t::handle_boundary, htp_mpartp_t::handle_data, htp_list_create, htp_mpartp_destroy(), HTP_OK, htp_mpartp_t::multipart, htp_mpartp_t::parser_state, htp_mpartp_t::part_data_pieces, htp_mpartp_t::part_header_pieces, htp_multipart_t::parts, STATE_INIT, and htp_cfg_t::tmpdir.
Referenced by htp_ch_multipart_callback_request_headers().
void htp_mpartp_destroy (htp_mpartp_t * parser)
Destroys the provided parser.
Parameters
[in] parser
Definition at line 944 of file htp_multipart.c.
References htp_multipart_t::boundary, htp_mpartp_t::boundary_pieces, bstr_builder_destroy(), bstr_free(), htp_mpartp_t::gave_up_data, htp_list_destroy, htp_list_get, htp_list_size, htp_mpart_part_destroy(), htp_mpartp_t::multipart, htp_mpartp_t::part_data_pieces, htp_mpartp_t::part_header_pieces, htp_multipart_t::parts, and htp_mpartp_t::pending_header_line.
Referenced by htp_mpartp_create(), and htp_tx_destroy_incomplete().
htp_status_t htp_mpartp_finalize (htp_mpartp_t * parser)
Finalize parsing.
Parameters
[in] parser
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 1080 of file htp_multipart.c.
References htp_mpartp_t::boundary_pieces, bstr_builder_clear(), htp_mpartp_t::current_part, htp_multipart_t::flags, HTP_ERROR, htp_mpart_part_finalize_data(), HTP_MULTIPART_INCOMPLETE, HTP_OK, htp_mpartp_t::multipart, MULTIPART_PART_EPILOGUE, and htp_multipart_part_t::type.
Referenced by htp_ch_multipart_callback_request_body_data().
htp_status_t htp_mpartp_find_boundary (bstr * content_type, bstr ** boundary, uint64_t * multipart_flags)
Looks for boundary in the supplied Content-Type request header. The extracted boundary will be allocated on the heap.
Parameters
[in] content_type
[out] boundary
[out] multipart_flags Multipart flags, which are not compatible from general LibHTP flags.
Returns
HTP_OK on success (boundary found), HTP_DECLINED if boundary was not found, and HTP_ERROR on failure. Flags may be set on HTP_OK and HTP_DECLINED. For example, if a boundary could not be extracted but there is indication that one is present, HTP_MULTIPART_HBOUNDARY_INVALID will be set.
Definition at line 1472 of file htp_multipart.c.
References bstr_begins_with_c(), bstr_dup_mem(), bstr_index_of_c_nocase(), bstr_len, bstr_ptr, fprint_bstr(), HTP_DECLINED, HTP_ERROR, htp_is_space(), HTP_MULTIPART_HBOUNDARY_INVALID, HTP_MULTIPART_HBOUNDARY_UNUSUAL, and HTP_OK.
Referenced by htp_ch_multipart_callback_request_headers().
htp_multipart_t* htp_mpartp_get_multipart (htp_mpartp_t * parser)
Returns the multipart structure created by the parser.
Parameters
[in] parser
Returns
The main multipart structure.
Definition at line 61 of file htp_multipart.c.
References htp_mpartp_t::multipart.
Referenced by htp_ch_multipart_callback_request_body_data().
htp_status_t htp_mpartp_parse (htp_mpartp_t * parser, const void * data, size_t len)
Parses a chunk of multipart/form-data data. This function should be called as many times as necessary until all data has been consumed.
Parameters
[in] parser
[in] data
[in] len
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 1099 of file htp_multipart.c.
References htp_multipart_t::boundary, htp_mpartp_t::boundary_candidate_pos, htp_multipart_t::boundary_count, htp_multipart_t::boundary_len, htp_mpartp_t::boundary_match_pos, htp_mpartp_t::boundary_pieces, bstr_builder_append_mem(), CR, htp_mpartp_t::cr_aside, htp_mpartp_t::current_part_mode, htp_multipart_t::flags, fprint_raw_data(), htp_mpartp_t::handle_boundary, htp_mpartp_t::handle_data, HTP_ERROR, htp_is_lws(), HTP_MULTIPART_BBOUNDARY_LWS_AFTER, HTP_MULTIPART_BBOUNDARY_NLWS_AFTER, HTP_MULTIPART_CRLF_LINE, HTP_MULTIPART_LF_LINE, HTP_MULTIPART_PART_AFTER_LAST_BOUNDARY, HTP_MULTIPART_SEEN_LAST_BOUNDARY, HTP_OK, LF, MODE_LINE, htp_mpartp_t::multipart, htp_mpartp_t::parser_state, STATE_BOUNDARY, STATE_BOUNDARY_EAT_LWS, STATE_BOUNDARY_EAT_LWS_CR, STATE_BOUNDARY_IS_LAST1, STATE_BOUNDARY_IS_LAST2, STATE_DATA, and STATE_INIT.
Referenced by htp_ch_multipart_callback_request_body_data().