suricata: libhtp/htp/htp.h File Reference
htp.h File Reference
#include <sys/time.h>
#include "htp_version.h"
#include "htp_core.h"
#include "bstr.h"
#include "htp_base64.h"
#include "htp_config.h"
#include "htp_connection_parser.h"
#include "htp_decompressors.h"
#include "htp_hooks.h"
#include "htp_list.h"
#include "htp_multipart.h"
#include "htp_table.h"
#include "htp_transaction.h"
#include "htp_urlencoded.h"
#include "htp_utf8_decoder.h"
Data Structures
struct htp_conn_t
struct htp_file_t
struct htp_file_data_t
struct htp_log_t
struct htp_header_t
struct htp_param_t
struct htp_tx_t
struct htp_tx_data_t
struct htp_uri_t
Functions
void htp_uri_free (htp_uri_t *uri)
htp_uri_t * htp_uri_alloc (void)
void htp_log (htp_connp_t *connp, const char *file, int line, enum htp_log_level_t level, int code, const char *fmt,...)
htp_status_t htp_urldecode_inplace (htp_cfg_t *cfg, enum htp_decoder_ctx_t ctx, bstr *input, uint64_t *flags)
htp_status_t htp_urldecode_inplace_ex (htp_cfg_t *cfg, enum htp_decoder_ctx_t ctx, bstr *input, uint64_t *flags, int *expected_status_code)
char * htp_get_version (void)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp.h.
Function Documentation
char* htp_get_version (void)
Returns the LibHTP version string.
Returns
LibHTP version, for example "LibHTP v0.5.x".
Definition at line 2576 of file htp_util.c.
Referenced by SCPrintBuildInfo().
void htp_log (htp_connp_t * connp, const char * file, int line, enum htp_log_level_t level, int code, const char * fmt, ...)
Creates a new log entry and stores it with the connection. The file and line parameters are typically auto-generated using the HTP_LOG_MARK macro.
Parameters
[in] connp
[in] file
[in] line
[in] level
[in] code
[in] fmt
[in] ... Records one log message.
[in] connp
[in] file
[in] line
[in] level
[in] code
[in] fmt
Definition at line 339 of file htp_util.c.
References htp_connp_t::cfg, htp_log_t::code, code, htp_connp_t::conn, htp_log_t::connp, htp_log_t::file, htp_cfg_t::hook_log, htp_hook_run_all(), htp_list_add, HTP_LOG_ERROR, htp_connp_t::last_error, htp_log_t::level, htp_log_t::line, htp_cfg_t::log_level, htp_conn_t::messages, and htp_log_t::msg.
Referenced by htp_connp_open(), htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_req_data(), htp_connp_REQ_HEADERS(), htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_RES_BODY_DETERMINE(), htp_connp_res_data(), htp_connp_RES_HEADERS(), htp_connp_RES_IDLE(), htp_gzip_decompressor_create(), htp_parse_request_header_generic(), htp_parse_request_line_generic_ex(), htp_parse_response_header_generic(), htp_process_response_header_generic(), htp_tx_req_process_body_data_ex(), htp_tx_res_process_body_data_ex(), htp_tx_state_request_headers(), htp_tx_state_response_headers(), htp_tx_state_response_line(), and htp_tx_state_response_start().
htp_uri_t* htp_uri_alloc (void)
Allocates and initializes a new htp_uri_t structure.
Returns
New structure, or NULL on memory allocation failure.
Definition at line 2567 of file htp_util.c.
References htp_uri_t::port_number.
Referenced by htp_tx_create(), and htp_tx_state_request_line().
void htp_uri_free (htp_uri_t * uri)
Frees all data contained in the uri, and then the uri itself.
Parameters
[in] uri
Definition at line 2552 of file htp_util.c.
References bstr_free(), htp_uri_t::fragment, htp_uri_t::hostname, htp_uri_t::password, htp_uri_t::path, htp_uri_t::port, htp_uri_t::query, htp_uri_t::scheme, and htp_uri_t::username.
Referenced by htp_tx_destroy_incomplete(), and htp_tx_req_set_parsed_uri().
htp_status_t htp_urldecode_inplace (htp_cfg_t * cfg, enum htp_decoder_ctx_t ctx, bstr * input, uint64_t * flags)
Performs in-place decoding of the input string, according to the configuration specified by cfg and ctx. On output, various flags (HTP_URLEN_*) might be set.
Parameters
[in] cfg
[in] ctx
[in] input
[out] flags
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 1478 of file htp_util.c.
References htp_urldecode_inplace_ex().
Referenced by SCHTPGenerateNormalizedUri().
htp_status_t htp_urldecode_inplace_ex (htp_cfg_t * cfg, enum htp_decoder_ctx_t ctx, bstr * input, uint64_t * flags, int * expected_status_code)
Performs in-place decoding of the input string, according to the configuration specified by cfg and ctx. On output, various flags (HTP_URLEN_*) might be set. If something in the input would cause a particular server to respond with an error, the appropriate status code will be set.
Parameters
[in] cfg
[in] ctx
[in] input
[out] flags
[out] expected_status_code 0 by default, or status code as necessary
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 1483 of file htp_util.c.
References bstr_adjust_len(), bstr_len, bstr_ptr, htp_cfg_t::decoder_cfgs, HTP_ERROR, HTP_OK, HTP_UNWANTED_IGNORE, HTP_URL_DECODE_PRESERVE_PERCENT, HTP_URL_DECODE_PROCESS_INVALID, HTP_URL_DECODE_REMOVE_PERCENT, HTP_URLEN_ENCODED_NUL, HTP_URLEN_INVALID_ENCODING, HTP_URLEN_RAW_NUL, htp_decoder_cfg_t::nul_encoded_terminates, htp_decoder_cfg_t::nul_encoded_unwanted, htp_decoder_cfg_t::nul_raw_terminates, htp_decoder_cfg_t::nul_raw_unwanted, htp_decoder_cfg_t::plusspace_decode, htp_decoder_cfg_t::u_encoding_decode, htp_decoder_cfg_t::u_encoding_unwanted, htp_decoder_cfg_t::url_encoding_invalid_handling, and htp_decoder_cfg_t::url_encoding_invalid_unwanted.
Referenced by htp_tx_urldecode_params_inplace(), htp_tx_urldecode_uri_inplace(), and htp_urldecode_inplace().