suricata: libhtp/htp/htp_base64.h File Reference
htp_base64.h File Reference
#include "bstr.h"
Data Structures
struct htp_base64_decoder
Enumerations
enum htp_base64_decodestep { step_a, step_b, step_c, step_d }
Functions
void htp_base64_decoder_init (htp_base64_decoder *state_in)
int htp_base64_decode_single (signed char value_in)
int htp_base64_decode (htp_base64_decoder *decoder, const void *code_in, int length_in, void *plaintext_out, int length_out)
bstr * htp_base64_decode_bstr (bstr *input)
bstr * htp_base64_decode_mem (const void *data, size_t len)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_base64.h.
Enumeration Type Documentation
enum htp_base64_decodestep
Enumerator
step_a
step_b
step_c
step_d
Definition at line 50 of file htp_base64.h.
Function Documentation
int htp_base64_decode (htp_base64_decoder * decoder, const void * _code_in, int length_in, void * _plaintext_out, int length_out)
Feed the supplied memory range to the decoder.
Parameters
[in] decoder
[in] _code_in
[in] length_in
[in] _plaintext_out
[in] length_out
Returns
how many bytes were placed into plaintext output
Definition at line 84 of file htp_base64.c.
References htp_base64_decode_single(), htp_base64_decoder::plainchar, htp_base64_decoder::step, step_a, step_b, step_c, and step_d.
Referenced by htp_base64_decode_mem().
bstr* htp_base64_decode_bstr (bstr * input)
Base64-decode input, given as bstring.
Parameters
[in] input
Returns
new base64-decoded bstring
Definition at line 164 of file htp_base64.c.
References bstr_len, bstr_ptr, and htp_base64_decode_mem().
bstr* htp_base64_decode_mem (const void * data, size_t len)
Base64-decode input, given as memory range.
Parameters
[in] data
[in] len
Returns
new base64-decoded bstring
Definition at line 175 of file htp_base64.c.
References bstr_dup_mem(), htp_base64_decode(), and htp_base64_decoder_init().
Referenced by htp_base64_decode_bstr(), and htp_parse_authorization_basic().
int htp_base64_decode_single (signed char value_in)
Decode single base64-encoded character.
Parameters
[in] value_in
Returns
decoded character
Definition at line 50 of file htp_base64.c.
Referenced by htp_base64_decode().
void htp_base64_decoder_init (htp_base64_decoder * decoder)
Initialize base64 decoder.
Parameters
[in] decoder
Definition at line 69 of file htp_base64.c.
References htp_base64_decoder::plainchar, htp_base64_decoder::step, and step_a.
Referenced by htp_base64_decode_mem().