suricata: libhtp/htp/htp_table.h File Reference
htp_table.h File Reference
Typedefs
typedef struct htp_table_t htp_table_t
Functions
htp_status_t htp_table_add (htp_table_t *table, const bstr *key, const void *element)
htp_status_t htp_table_addn (htp_table_t *table, const bstr *key, const void *element)
htp_status_t htp_table_addk (htp_table_t *table, const bstr *key, const void *element)
void htp_table_clear (htp_table_t *table)
void htp_table_clear_ex (htp_table_t *table)
htp_table_t * htp_table_create (size_t size)
void htp_table_destroy (htp_table_t *table)
void htp_table_destroy_ex (htp_table_t *table)
void * htp_table_get (const htp_table_t *table, const bstr *key)
void * htp_table_get_c (const htp_table_t *table, const char *ckey)
void * htp_table_get_index (const htp_table_t *table, size_t idx, bstr **key)
void * htp_table_get_mem (const htp_table_t *table, const void *key, size_t key_len)
size_t htp_table_size (const htp_table_t *table)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_table.h.
Typedef Documentation
typedef struct htp_table_t htp_table_t
Definition at line 46 of file htp_table.h.
Function Documentation
htp_status_t htp_table_add (htp_table_t * table, const bstr * key, const void * element)
Add a new element to the table. The key will be copied, and the copy managed by the table. The table keeps a pointer to the element. It is the callers responsibility to ensure the pointer remains valid.
Parameters
[in] table
[in] key
[in] element
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 56 of file htp_table.c.
References htp_table_t::alloc_type, bstr_dup(), bstr_free(), HTP_ERROR, HTP_OK, HTP_TABLE_KEYS_ALLOC_UKNOWN, and HTP_TABLE_KEYS_COPIED.
Referenced by htp_mpartp_parse_header(), htp_process_request_header_generic(), htp_process_response_header_generic(), htp_tx_req_set_header(), and htp_tx_res_set_header().
htp_status_t htp_table_addk (htp_table_t * table, const bstr * key, const void * element)
Add a new element to the table. The key provided will be only referenced and the caller remains responsible to keep it alive until after the table is destroyed. The table keeps a pointer to the element. It is the callers responsibility to ensure the pointer remains valid.
Parameters
[in] table
[in] key
[in] element
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 106 of file htp_table.c.
References htp_table_t::alloc_type, HTP_ERROR, HTP_TABLE_KEYS_ALLOC_UKNOWN, and HTP_TABLE_KEYS_REFERENCED.
Referenced by htp_tx_req_add_param().
htp_status_t htp_table_addn (htp_table_t * table, const bstr * key, const void * element)
Add a new element to the table. The key provided will be adopted and managed by the table. You should not keep a copy of the pointer to the key unless you're certain that the table will live longer that the copy. The table keeps a pointer to the element. It is the callers responsibility to ensure the pointer remains valid.
Parameters
[in] table
[in] key
[in] element
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 85 of file htp_table.c.
References htp_table_t::alloc_type, HTP_ERROR, HTP_TABLE_KEYS_ADOPTED, and HTP_TABLE_KEYS_ALLOC_UKNOWN.
Referenced by htp_parse_single_cookie_v0(), and htp_transcode_params().
void htp_table_clear (htp_table_t * table)
Remove all elements from the table. This function handles keys according to the active allocation strategy. If the elements need freeing, you need to free them before invoking this function.
Parameters
[in] table
Definition at line 127 of file htp_table.c.
References htp_table_t::alloc_type, bstr_free(), htp_list_clear, htp_list_get, htp_list_size, HTP_TABLE_KEYS_ADOPTED, HTP_TABLE_KEYS_COPIED, and htp_table_t::list.
Referenced by htp_connp_RES_BODY_DETERMINE(), and htp_table_destroy().
void htp_table_clear_ex (htp_table_t * table)
Remove all elements from the table without freeing any of the keys, even if the table is using an allocation strategy where keys belong to it. This function is useful if all the keys have been adopted by some other structure.
Parameters
[in] table
Definition at line 142 of file htp_table.c.
References htp_list_clear, and htp_table_t::list.
htp_table_t* htp_table_create (size_t size)
Create a new table structure. The table will grow automatically as needed, but you are required to provide a starting size.
Parameters
[in] size The starting size.
Returns
Newly created table instance, or NULL on failure.
Definition at line 150 of file htp_table.c.
References htp_table_t::alloc_type, htp_list_array_create(), HTP_TABLE_KEYS_ALLOC_UKNOWN, and htp_table_t::list.
Referenced by htp_mpart_part_create(), htp_parse_cookies_v0(), htp_transcode_params(), htp_tx_create(), htp_tx_req_set_headers_clear(), htp_tx_res_set_headers_clear(), and htp_urlenp_create().
void htp_table_destroy (htp_table_t * table)
Destroy a table. This function handles the keys according to the active allocation strategy. If the elements need freeing, you need to free them before invoking this function. After the table has been destroyed, the pointer is set to NULL.
Parameters
[in] table
Definition at line 168 of file htp_table.c.
References htp_list_destroy, htp_table_clear(), and htp_table_t::list.
Referenced by htp_mpart_part_destroy(), htp_table_destroy_ex(), htp_transcode_params(), htp_tx_destroy_incomplete(), htp_tx_req_set_headers_clear(), htp_tx_res_set_headers_clear(), htp_urlenp_create(), and htp_urlenp_destroy().
void htp_table_destroy_ex (htp_table_t * table)
Destroy the given table, but don't free the keys. even if they are managed by the table. Use this method when the responsibility for the keys has been transferred elsewhere. After the table has been destroyed, the pointer is set to NULL.
Parameters
[in] table
Definition at line 179 of file htp_table.c.
References htp_table_t::alloc_type, htp_table_destroy(), and HTP_TABLE_KEYS_REFERENCED.
Referenced by htp_ch_urlencoded_callback_request_body_data(), and htp_ch_urlencoded_callback_request_line().
void* htp_table_get (const htp_table_t * table, const bstr * key)
Retrieve the first element that matches the given bstr key.
Parameters
[in] table
[in] key
Returns
Matched element, or NULL if no elements match the key.
Definition at line 189 of file htp_table.c.
References bstr_cmp_nocase(), htp_list_get, htp_list_size, and htp_table_t::list.
Referenced by htp_mpartp_parse_header(), htp_process_request_header_generic(), and htp_process_response_header_generic().
void* htp_table_get_c (const htp_table_t * table, const char * ckey)
Retrieve the first element that matches the given NUL-terminated key.
Parameters
[in] table
[in] ckey
Returns
Matched element, or NULL if no elements match the key.
Definition at line 205 of file htp_table.c.
References bstr_cmp_c_nocase(), htp_list_get, htp_list_size, and htp_table_t::list.
Referenced by DetectEngineInspectHttpCookie(), DetectEngineInspectHttpHRH(), DetectEngineInspectHttpUA(), DetectEngineRunHttpCookieMpm(), DetectEngineRunHttpHRHMpm(), DetectEngineRunHttpUAMpm(), htp_ch_multipart_callback_request_headers(), htp_connp_RES_BODY_DETERMINE(), htp_mpart_part_parse_c_d(), htp_parse_authorization(), htp_parse_cookies_v0(), htp_tx_state_response_headers(), HtpResponseBodyHandle(), and HttpXFFGetIPFromTx().
void* htp_table_get_index (const htp_table_t * table, size_t idx, bstr ** key)
Retrieve key and element at the given index.
Parameters
[in] table
[in] idx
[in,out] key Pointer in which the key will be returned. Can be NULL.
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 221 of file htp_table.c.
References htp_list_get, htp_list_size, and htp_table_t::list.
Referenced by htp_ch_urlencoded_callback_request_body_data(), htp_ch_urlencoded_callback_request_line(), htp_connp_RES_BODY_DETERMINE(), htp_mpart_part_destroy(), htp_transcode_params(), htp_tx_destroy_incomplete(), htp_tx_req_get_param_ex(), htp_tx_req_set_headers_clear(), htp_tx_res_set_headers_clear(), and htp_urlenp_destroy().
void* htp_table_get_mem (const htp_table_t * table, const void * key, size_t key_len)
Retrieve table key defined by the provided pointer and length.
Parameters
[in] table
[in] key
[in] key_len
Returns
Matched element, or NULL if no elements match the key.
Definition at line 233 of file htp_table.c.
References bstr_cmp_mem_nocase(), htp_list_get, htp_list_size, and htp_table_t::list.
Referenced by htp_tx_req_get_param().
size_t htp_table_size (const htp_table_t * table)
Return the size of the table.
Parameters
[in] table
Returns
table size
Definition at line 249 of file htp_table.c.
References htp_list_size, and htp_table_t::list.
Referenced by htp_ch_urlencoded_callback_request_body_data(), htp_ch_urlencoded_callback_request_line(), htp_connp_RES_BODY_DETERMINE(), htp_mpart_part_destroy(), htp_transcode_params(), htp_tx_destroy_incomplete(), htp_tx_req_get_param_ex(), htp_tx_req_set_headers_clear(), htp_tx_res_set_headers_clear(), and htp_urlenp_destroy().