suricata: libhtp/htp/htp_util.c File Reference
htp_util.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Functions
int htp_is_lws (int c)
int htp_is_separator (int c)
int htp_is_text (int c)
int htp_is_token (int c)
int htp_chomp (unsigned char *data, size_t *len)
int htp_is_space (int c)
int htp_convert_method_to_number (bstr *method)
int htp_is_line_empty (unsigned char *data, size_t len)
int htp_is_line_whitespace (unsigned char *data, size_t len)
int64_t htp_parse_content_length (bstr *b)
int64_t htp_parse_chunked_length (unsigned char *data, size_t len)
int64_t htp_parse_positive_integer_whitespace (unsigned char *data, size_t len, int base)
void htp_log (htp_connp_t *connp, const char *file, int line, enum htp_log_level_t level, int code, const char *fmt,...)
int htp_connp_is_line_folded (unsigned char *data, size_t len)
int htp_is_folding_char (int c)
int htp_connp_is_line_terminator (htp_connp_t *connp, unsigned char *data, size_t len)
int htp_connp_is_line_ignorable (htp_connp_t *connp, unsigned char *data, size_t len)
htp_status_t htp_parse_hostport (bstr *hostport, bstr **hostname, bstr **port, int *port_number, int *invalid)
int htp_parse_uri_hostport (htp_connp_t *connp, bstr *hostport, htp_uri_t *uri)
htp_status_t htp_parse_header_hostport (bstr *hostport, bstr **hostname, bstr **port, int *port_number, uint64_t *flags)
int htp_parse_uri (bstr *input, htp_uri_t **uri)
void htp_utf8_decode_path_inplace (htp_cfg_t *cfg, htp_tx_t *tx, bstr *path)
void htp_utf8_validate_path (htp_tx_t *tx, bstr *path)
htp_status_t htp_decode_path_inplace (htp_tx_t *tx, bstr *path)
htp_status_t htp_tx_urldecode_uri_inplace (htp_tx_t *tx, bstr *input)
htp_status_t htp_tx_urldecode_params_inplace (htp_tx_t *tx, bstr *input)
htp_status_t htp_urldecode_inplace (htp_cfg_t *cfg, enum htp_decoder_ctx_t ctx, bstr *input, uint64_t *flags)
htp_status_t htp_urldecode_inplace_ex (htp_cfg_t *cfg, enum htp_decoder_ctx_t ctx, bstr *input, uint64_t *flags, int *expected_status_code)
int htp_normalize_parsed_uri (htp_tx_t *tx, htp_uri_t *incomplete, htp_uri_t *normalized)
bstr * htp_normalize_hostname_inplace (bstr *hostname)
void htp_normalize_uri_path_inplace (bstr *s)
void fprint_bstr (FILE *stream, const char *name, bstr *b)
void fprint_raw_data (FILE *stream, const char *name, const void *data, size_t len)
void fprint_raw_data_ex (FILE *stream, const char *name, const void *_data, size_t offset, size_t printlen)
char * htp_connp_in_state_as_string (htp_connp_t *connp)
char * htp_connp_out_state_as_string (htp_connp_t *connp)
char * htp_tx_request_progress_as_string (htp_tx_t *tx)
char * htp_tx_response_progress_as_string (htp_tx_t *tx)
bstr * htp_unparse_uri_noencode (htp_uri_t *uri)
int htp_treat_response_line_as_body (htp_tx_t *tx)
htp_status_t htp_req_run_hook_body_data (htp_connp_t *connp, htp_tx_data_t *d)
htp_status_t htp_res_run_hook_body_data (htp_connp_t *connp, htp_tx_data_t *d)
htp_status_t htp_extract_quoted_string_as_bstr (unsigned char *data, size_t len, bstr **out, size_t *endoffset)
htp_status_t htp_parse_ct_header (bstr *header, bstr **ct)
int htp_validate_hostname (bstr *hostname)
void htp_uri_free (htp_uri_t *uri)
htp_uri_t * htp_uri_alloc ()
char * htp_get_version (void)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_util.c.
Function Documentation
void fprint_bstr (FILE * stream, const char * name, bstr * b)
Definition at line 2039 of file htp_util.c.
References bstr_len, bstr_ptr, and fprint_raw_data_ex().
Referenced by htp_mpartp_find_boundary(), htp_process_request_header_generic(), and htp_process_response_header_generic().
void fprint_raw_data (FILE * stream, const char * name, const void * data, size_t len)
Definition at line 2051 of file htp_util.c.
References fprint_raw_data_ex().
Referenced by htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_req_data(), htp_connp_REQ_HEADERS(), htp_connp_REQ_LINE_complete(), htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_res_data(), htp_connp_RES_HEADERS(), htp_connp_RES_LINE(), htp_mpart_part_handle_data(), htp_mpartp_parse(), htp_parse_request_line_generic_ex(), htp_parse_response_line_generic(), and htp_tx_res_process_body_data_ex().
void fprint_raw_data_ex (FILE * stream, const char * name, const void * _data, size_t offset, size_t printlen)
Definition at line 2058 of file htp_util.c.
References strlcat().
Referenced by fprint_bstr(), and fprint_raw_data().
int htp_chomp (unsigned char * data, size_t * len)
Remove all line terminators (LF or CRLF) from the end of the line provided as input.
Returns
0 if nothing was removed, 1 if one or more LF characters were removed, or 2 if one or more CR and/or LF characters were removed.
Definition at line 125 of file htp_util.c.
References CR, and LF.
Referenced by htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_REQ_HEADERS(), htp_connp_REQ_LINE_complete(), htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_RES_HEADERS(), htp_connp_RES_LINE(), htp_parse_request_header_generic(), and htp_parse_response_header_generic().
char* htp_connp_in_state_as_string (htp_connp_t * connp)
Definition at line 2125 of file htp_util.c.
References htp_connp_REQ_BODY_CHUNKED_DATA(), htp_connp_REQ_BODY_CHUNKED_DATA_END(), htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_REQ_BODY_DETERMINE(), htp_connp_REQ_BODY_IDENTITY(), htp_connp_REQ_CONNECT_CHECK(), htp_connp_REQ_CONNECT_WAIT_RESPONSE(), htp_connp_REQ_FINALIZE(), htp_connp_REQ_HEADERS(), htp_connp_REQ_IDLE(), htp_connp_REQ_IGNORE_DATA_AFTER_HTTP_0_9(), htp_connp_REQ_LINE(), htp_connp_REQ_PROTOCOL(), and htp_connp_t::in_state.
Referenced by htp_connp_req_data().
int htp_connp_is_line_folded (unsigned char * data, size_t len)
Determines if the given line is a continuation (of some previous line).
Parameters
[in] data
[in] len
Returns
0 or 1 for false and true, respectively. Returns -1 on error (NULL pointer or length zero).
Definition at line 397 of file htp_util.c.
References htp_is_folding_char().
Referenced by htp_connp_REQ_HEADERS(), and htp_connp_RES_HEADERS().
int htp_connp_is_line_ignorable (htp_connp_t * connp, unsigned char * data, size_t len)
Determines if the given line can be ignored when it appears before a request.
Parameters
[in] connp
[in] data
[in] len
Returns
0 or 1
Definition at line 444 of file htp_util.c.
References htp_connp_is_line_terminator().
Referenced by htp_connp_REQ_LINE_complete(), and htp_connp_RES_LINE().
int htp_connp_is_line_terminator (htp_connp_t * connp, unsigned char * data, size_t len)
Determines if the given line is a request terminator.
Parameters
[in] connp
[in] data
[in] len
Returns
0 or 1
Definition at line 415 of file htp_util.c.
References htp_connp_t::cfg, htp_is_line_empty(), htp_is_line_whitespace(), HTP_SERVER_IIS_5_1, and htp_cfg_t::server_personality.
Referenced by htp_connp_is_line_ignorable(), htp_connp_REQ_HEADERS(), and htp_connp_RES_HEADERS().
char* htp_connp_out_state_as_string (htp_connp_t * connp)
Definition at line 2148 of file htp_util.c.
References htp_connp_RES_BODY_CHUNKED_DATA(), htp_connp_RES_BODY_CHUNKED_DATA_END(), htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_BODY_IDENTITY_CL_KNOWN(), htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE(), htp_connp_RES_FINALIZE(), htp_connp_RES_HEADERS(), htp_connp_RES_IDLE(), htp_connp_RES_LINE(), and htp_connp_t::out_state.
Referenced by htp_connp_res_data().
int htp_convert_method_to_number (bstr * method)
Converts request method, given as a string, into a number.
Parameters
[in] method
Returns
Method number of M_UNKNOWN
Definition at line 174 of file htp_util.c.
References bstr_cmp_c(), HTP_M_BASELINE_CONTROL, HTP_M_CHECKIN, HTP_M_CHECKOUT, HTP_M_CONNECT, HTP_M_COPY, HTP_M_DELETE, HTP_M_GET, HTP_M_HEAD, HTP_M_INVALID, HTP_M_LABEL, HTP_M_LOCK, HTP_M_MERGE, HTP_M_MKACTIVITY, HTP_M_MKCOL, HTP_M_MKWORKSPACE, HTP_M_MOVE, HTP_M_OPTIONS, HTP_M_PATCH, HTP_M_POST, HTP_M_PROPFIND, HTP_M_PROPPATCH, HTP_M_PUT, HTP_M_REPORT, HTP_M_TRACE, HTP_M_UNCHECKOUT, HTP_M_UNKNOWN, HTP_M_UNLOCK, HTP_M_UPDATE, and HTP_M_VERSION_CONTROL.
Referenced by htp_connp_REQ_CONNECT_PROBE_DATA(), and htp_parse_request_line_generic_ex().
htp_status_t htp_decode_path_inplace (htp_tx_t * tx, bstr * path)
Decode a request path according to the settings in the provided configuration structure.
Parameters
[in] cfg
[in] tx
[in] path
Definition at line 1190 of file htp_util.c.
References htp_decoder_cfg_t::backslash_convert_slashes, bstr_adjust_len(), bstr_len, bstr_ptr, htp_tx_t::cfg, htp_decoder_cfg_t::control_chars_unwanted, htp_decoder_cfg_t::convert_lowercase, htp_cfg_t::decoder_cfgs, htp_tx_t::flags, HTP_DECODER_URL_PATH, HTP_ERROR, HTP_OK, HTP_PATH_ENCODED_NUL, HTP_PATH_ENCODED_SEPARATOR, HTP_PATH_INVALID_ENCODING, HTP_UNWANTED_IGNORE, HTP_URL_DECODE_PRESERVE_PERCENT, HTP_URL_DECODE_PROCESS_INVALID, HTP_URL_DECODE_REMOVE_PERCENT, htp_decoder_cfg_t::nul_encoded_terminates, htp_decoder_cfg_t::nul_encoded_unwanted, htp_decoder_cfg_t::nul_raw_terminates, htp_decoder_cfg_t::nul_raw_unwanted, htp_decoder_cfg_t::path_separators_compress, htp_decoder_cfg_t::path_separators_decode, htp_decoder_cfg_t::path_separators_encoded_unwanted, htp_tx_t::response_status_expected_number, htp_decoder_cfg_t::u_encoding_decode, htp_decoder_cfg_t::u_encoding_unwanted, htp_decoder_cfg_t::url_encoding_invalid_handling, and htp_decoder_cfg_t::url_encoding_invalid_unwanted.
Referenced by htp_normalize_parsed_uri().
htp_status_t htp_extract_quoted_string_as_bstr (unsigned char * data, size_t len, bstr ** out, size_t * endoffset)
Parses the provided memory region, extracting the double-quoted string.
Parameters
[in] data
[in] len
[out] out
[out] endoffset
Returns
HTP_OK on success, HTP_DECLINED if the input is not well formed, and HTP_ERROR on fatal errors.
Definition at line 2420 of file htp_util.c.
References bstr_adjust_len(), bstr_alloc(), bstr_ptr, HTP_DECLINED, HTP_ERROR, and HTP_OK.
Referenced by htp_parse_authorization_digest().
char* htp_get_version (void)
Returns the LibHTP version string.
Returns
LibHTP version, for example "LibHTP v0.5.x".
Definition at line 2576 of file htp_util.c.
Referenced by SCPrintBuildInfo().
int htp_is_folding_char (int c)
Definition at line 402 of file htp_util.c.
References htp_is_lws().
Referenced by htp_connp_is_line_folded(), htp_connp_REQ_HEADERS(), and htp_connp_RES_HEADERS().
int htp_is_line_empty (unsigned char * data, size_t len)
Is the given line empty? This function expects the line to have a terminating LF.
Parameters
[in] data
[in] len
Returns
0 or 1
Definition at line 219 of file htp_util.c.
References CR.
Referenced by htp_connp_is_line_terminator().
int htp_is_line_whitespace (unsigned char * data, size_t len)
Does line consist entirely of whitespace characters?
Parameters
[in] data
[in] len
Returns
0 or 1
Definition at line 234 of file htp_util.c.
References len.
Referenced by htp_connp_is_line_terminator().
int htp_is_lws (int c)
Is character a linear white space character?
Parameters
[in] c
Returns
0 or 1
Definition at line 49 of file htp_util.c.
Referenced by htp_is_folding_char(), htp_mpartp_parse(), htp_mpartp_parse_header(), htp_parse_positive_integer_whitespace(), htp_parse_request_header_generic(), and htp_parse_response_header_generic().
int htp_is_separator (int c)
Is character a separator character?
Parameters
[in] c
Returns
0 or 1
Definition at line 60 of file htp_util.c.
Referenced by htp_is_token().
int htp_is_space (int c)
Is character a white space character?
Parameters
[in] c
Returns
0 or 1
Definition at line 154 of file htp_util.c.
Referenced by htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_RES_BODY_DETERMINE(), htp_mpartp_find_boundary(), htp_mpartp_parse_header(), htp_parse_request_line_generic_ex(), and htp_parse_response_line_generic().
int htp_is_text (int c)
Is character a text character?
Parameters
[in] c
Returns
0 or 1
Definition at line 98 of file htp_util.c.
int htp_is_token (int c)
Is character a token character?
Parameters
[in] c
Returns
0 or 1
Definition at line 110 of file htp_util.c.
References htp_is_separator().
Referenced by htp_mpartp_parse_header(), htp_parse_request_header_generic(), and htp_parse_response_header_generic().
void htp_log (htp_connp_t * connp, const char * file, int line, enum htp_log_level_t level, int code, const char * fmt, ...)
Records one log message.
Parameters
[in] connp
[in] file
[in] line
[in] level
[in] code
[in] fmt
Definition at line 339 of file htp_util.c.
References htp_connp_t::cfg, htp_log_t::code, code, htp_connp_t::conn, htp_log_t::connp, htp_log_t::file, htp_cfg_t::hook_log, htp_hook_run_all(), htp_list_add, HTP_LOG_ERROR, htp_connp_t::last_error, htp_log_t::level, htp_log_t::line, htp_cfg_t::log_level, htp_conn_t::messages, and htp_log_t::msg.
Referenced by htp_connp_open(), htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_req_data(), htp_connp_REQ_HEADERS(), htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_RES_BODY_DETERMINE(), htp_connp_res_data(), htp_connp_RES_HEADERS(), htp_connp_RES_IDLE(), htp_gzip_decompressor_create(), htp_parse_request_header_generic(), htp_parse_request_line_generic_ex(), htp_parse_response_header_generic(), htp_process_response_header_generic(), htp_tx_req_process_body_data_ex(), htp_tx_res_process_body_data_ex(), htp_tx_state_request_headers(), htp_tx_state_response_headers(), htp_tx_state_response_line(), and htp_tx_state_response_start().
bstr* htp_normalize_hostname_inplace (bstr * hostname)
Normalize request hostname. Convert all characters to lowercase and remove trailing dots from the end, if present.
Parameters
[in] hostname
Returns
Normalized hostname.
Definition at line 1793 of file htp_util.c.
References bstr_char_at_end(), bstr_chop(), and bstr_to_lowercase().
Referenced by htp_normalize_parsed_uri().
int htp_normalize_parsed_uri (htp_tx_t * tx, htp_uri_t * incomplete, htp_uri_t * normalized)
Normalize a previously-parsed request URI.
Parameters
[in] connp
[in] incomplete
[in] normalized
Returns
HTP_OK or HTP_ERROR
Definition at line 1694 of file htp_util.c.
References bstr_dup(), bstr_dup_lower(), bstr_len, bstr_ptr, htp_tx_t::cfg, htp_cfg_t::decoder_cfgs, htp_tx_t::flags, htp_uri_t::fragment, htp_uri_t::hostname, htp_decode_path_inplace(), HTP_DECODER_URL_PATH, HTP_ERROR, HTP_HOSTU_INVALID, htp_normalize_hostname_inplace(), htp_normalize_uri_path_inplace(), HTP_OK, htp_parse_positive_integer_whitespace(), htp_tx_urldecode_uri_inplace(), htp_utf8_decode_path_inplace(), htp_utf8_validate_path(), htp_uri_t::password, htp_uri_t::path, htp_uri_t::port, htp_uri_t::port_number, htp_uri_t::query, htp_uri_t::scheme, htp_uri_t::username, and htp_decoder_cfg_t::utf8_convert_bestfit.
Referenced by htp_tx_state_request_line().
void htp_normalize_uri_path_inplace (bstr * s)
Normalize URL path. This function implements the remove dot segments algorithm specified in RFC 3986, section 5.2.4.
Parameters
[in] s
Definition at line 1940 of file htp_util.c.
References bstr_adjust_len(), bstr_len, and bstr_ptr.
Referenced by htp_normalize_parsed_uri().
int64_t htp_parse_chunked_length (unsigned char * data, size_t len)
Parses chunk length (positive hexadecimal number). White space is allowed before and after the number. An error will be returned if the chunk length is greater than INT32_MAX.
Parameters
[in] data
[in] len
Returns
Chunk length, or a negative number on error.
Definition at line 266 of file htp_util.c.
References htp_parse_positive_integer_whitespace().
Referenced by htp_connp_REQ_BODY_CHUNKED_LENGTH(), and htp_connp_RES_BODY_CHUNKED_LENGTH().
int64_t htp_parse_content_length (bstr * b)
Parses Content-Length string (positive decimal number). White space is allowed before and after the number.
Parameters
[in] b
Returns
Content-Length as a number, or -1 on error.
Definition at line 253 of file htp_util.c.
References bstr_len, bstr_ptr, and htp_parse_positive_integer_whitespace().
Referenced by htp_connp_RES_BODY_DETERMINE(), and htp_process_response_header_generic().
htp_status_t htp_parse_ct_header (bstr * header, bstr ** ct)
Definition at line 2486 of file htp_util.c.
References bstr_dup_ex(), bstr_len, bstr_ptr, bstr_to_lowercase(), HTP_ERROR, and HTP_OK.
htp_status_t htp_parse_header_hostport (bstr * hostport, bstr ** hostname, bstr ** port, int * port_number, uint64_t * flags)
Parses hostport provided in the Host header.
Parameters
[in] hostport
[out] hostname
[out] port
[out] port_number
[out] flags
Returns
HTP_OK on success or HTP_ERROR error.
Definition at line 613 of file htp_util.c.
References HTP_HOSTH_INVALID, HTP_OK, htp_parse_hostport(), and htp_validate_hostname().
htp_status_t htp_parse_hostport (bstr * hostport, bstr ** hostname, bstr ** port, int * port_number, int * invalid)
Parses an authority string, which consists of a hostname with an optional port number; username and password are not allowed and will not be handled.
Parameters
[in] hostport
[out] hostname A bstring containing the hostname, or NULL if the hostname is invalid. If this value is not NULL, the caller assumes responsibility for memory management.
[out] port Port as text, or NULL if not provided.
[out] port_number Port number, or -1 if the port is not present or invalid.
[out] invalid Set to 1 if any part of the authority is invalid.
Returns
HTP_OK on success, HTP_ERROR on memory allocation failure.
Definition at line 485 of file htp_util.c.
References bstr_dup_mem(), bstr_free(), bstr_len, bstr_ptr, bstr_to_lowercase(), bstr_util_mem_trim(), HTP_ERROR, and HTP_OK.
Referenced by htp_parse_header_hostport(), and htp_parse_uri_hostport().
int64_t htp_parse_positive_integer_whitespace (unsigned char * data, size_t len, int base)
A somewhat forgiving parser for a positive integer in a given base. Only LWS is allowed before and after the number.
Parameters
[in] data
[in] len
[in] base
Returns
The parsed number on success; a negative number on error.
Definition at line 282 of file htp_util.c.
References bstr_util_mem_to_pint(), and htp_is_lws().
Referenced by htp_normalize_parsed_uri(), htp_parse_chunked_length(), htp_parse_content_length(), and htp_parse_status().
int htp_parse_uri (bstr * input, htp_uri_t ** uri)
Parses request URI, making no attempt to validate the contents.
Parameters
[in] input
[in] uri
Returns
HTP_ERROR on memory allocation failure, HTP_OK otherwise
Definition at line 639 of file htp_util.c.
References bstr_dup_mem(), bstr_len, bstr_ptr, HTP_ERROR, HTP_OK, and m.
Referenced by htp_tx_state_request_line().
int htp_parse_uri_hostport (htp_connp_t * connp, bstr * hostport, htp_uri_t * uri)
Parses hostport provided in the URI.
Parameters
[in] connp
[in] hostport
[in] uri
Returns
HTP_OK on success or HTP_ERROR error.
Definition at line 584 of file htp_util.c.
References htp_tx_t::flags, htp_uri_t::hostname, HTP_HOSTU_INVALID, HTP_OK, htp_parse_hostport(), htp_validate_hostname(), htp_connp_t::in_tx, htp_uri_t::port, and htp_uri_t::port_number.
Referenced by htp_tx_state_request_line().
htp_status_t htp_req_run_hook_body_data (htp_connp_t * connp, htp_tx_data_t * d)
Run the REQUEST_BODY_DATA hook.
Parameters
[in] connp
[in] d
Definition at line 2359 of file htp_util.c.
References htp_connp_t::cfg, htp_file_data_t::data, htp_tx_data_t::data, htp_file_data_t::file, htp_cfg_t::hook_request_body_data, htp_tx_t::hook_request_body_data, htp_cfg_t::hook_request_file_data, htp_hook_run_all(), HTP_OK, htp_connp_t::in_tx, htp_file_t::len, htp_file_data_t::len, htp_tx_data_t::len, and htp_connp_t::put_file.
Referenced by htp_tx_req_process_body_data_ex().
htp_status_t htp_res_run_hook_body_data (htp_connp_t * connp, htp_tx_data_t * d)
Run the RESPONSE_BODY_DATA hook.
Parameters
[in] connp
[in] d
Definition at line 2396 of file htp_util.c.
References htp_connp_t::cfg, htp_tx_data_t::data, htp_cfg_t::hook_response_body_data, htp_tx_t::hook_response_body_data, htp_hook_run_all(), HTP_OK, htp_tx_data_t::len, and htp_connp_t::out_tx.
Referenced by htp_tx_res_process_body_data_ex().
int htp_treat_response_line_as_body (htp_tx_t * tx)
Determine if the information provided on the response line is good enough. Browsers are lax when it comes to response line parsing. In most cases they will only look for the words "http" at the beginning.
Parameters
[in] tx
Returns
1 for good enough or 0 for not good enough
Definition at line 2334 of file htp_util.c.
References bstr_len, bstr_ptr, and htp_tx_t::response_protocol.
Referenced by htp_connp_RES_LINE().
char* htp_tx_request_progress_as_string (htp_tx_t * tx)
Definition at line 2168 of file htp_util.c.
References HTP_REQUEST_BODY, HTP_REQUEST_COMPLETE, HTP_REQUEST_HEADERS, HTP_REQUEST_LINE, HTP_REQUEST_NOT_STARTED, HTP_REQUEST_TRAILER, and htp_tx_t::request_progress.
Referenced by htp_connp_req_data().
char* htp_tx_response_progress_as_string (htp_tx_t * tx)
Definition at line 2192 of file htp_util.c.
References HTP_RESPONSE_BODY, HTP_RESPONSE_COMPLETE, HTP_RESPONSE_HEADERS, HTP_RESPONSE_LINE, HTP_RESPONSE_NOT_STARTED, HTP_RESPONSE_TRAILER, and htp_tx_t::response_progress.
Referenced by htp_connp_res_data().
htp_status_t htp_tx_urldecode_params_inplace (htp_tx_t * tx, bstr * input)
Definition at line 1474 of file htp_util.c.
References htp_tx_t::cfg, htp_tx_t::flags, HTP_DECODER_URLENCODED, htp_urldecode_inplace_ex(), and htp_tx_t::response_status_expected_number.
htp_status_t htp_tx_urldecode_uri_inplace (htp_tx_t * tx, bstr * input)
Definition at line 1454 of file htp_util.c.
References htp_tx_t::cfg, htp_tx_t::flags, HTP_DECODER_URL_PATH, HTP_PATH_ENCODED_NUL, HTP_PATH_INVALID_ENCODING, HTP_PATH_RAW_NUL, htp_urldecode_inplace_ex(), HTP_URLEN_ENCODED_NUL, HTP_URLEN_INVALID_ENCODING, HTP_URLEN_RAW_NUL, and htp_tx_t::response_status_expected_number.
Referenced by htp_normalize_parsed_uri().
bstr* htp_unparse_uri_noencode (htp_uri_t * uri)
Definition at line 2213 of file htp_util.c.
References bstr_add_c_noex(), bstr_add_noex(), bstr_alloc(), bstr_len, htp_uri_t::fragment, htp_uri_t::hostname, htp_uri_t::password, htp_uri_t::path, htp_uri_t::port, htp_uri_t::query, htp_uri_t::scheme, and htp_uri_t::username.
htp_uri_t* htp_uri_alloc (void)
Allocates and initializes a new htp_uri_t structure.
Returns
New structure, or NULL on memory allocation failure.
Definition at line 2567 of file htp_util.c.
References htp_uri_t::port_number.
Referenced by htp_tx_create(), and htp_tx_state_request_line().
void htp_uri_free (htp_uri_t * uri)
Frees all data contained in the uri, and then the uri itself.
Parameters
[in] uri
Definition at line 2552 of file htp_util.c.
References bstr_free(), htp_uri_t::fragment, htp_uri_t::hostname, htp_uri_t::password, htp_uri_t::path, htp_uri_t::port, htp_uri_t::query, htp_uri_t::scheme, and htp_uri_t::username.
Referenced by htp_tx_destroy_incomplete(), and htp_tx_req_set_parsed_uri().
htp_status_t htp_urldecode_inplace (htp_cfg_t * cfg, enum htp_decoder_ctx_t ctx, bstr * input, uint64_t * flags)
Performs in-place decoding of the input string, according to the configuration specified by cfg and ctx. On output, various flags (HTP_URLEN_*) might be set.
Parameters
[in] cfg
[in] ctx
[in] input
[out] flags
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 1478 of file htp_util.c.
References htp_urldecode_inplace_ex().
Referenced by SCHTPGenerateNormalizedUri().
htp_status_t htp_urldecode_inplace_ex (htp_cfg_t * cfg, enum htp_decoder_ctx_t ctx, bstr * input, uint64_t * flags, int * expected_status_code)
Performs in-place decoding of the input string, according to the configuration specified by cfg and ctx. On output, various flags (HTP_URLEN_*) might be set. If something in the input would cause a particular server to respond with an error, the appropriate status code will be set.
Parameters
[in] cfg
[in] ctx
[in] input
[out] flags
[out] expected_status_code 0 by default, or status code as necessary
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 1483 of file htp_util.c.
References bstr_adjust_len(), bstr_len, bstr_ptr, htp_cfg_t::decoder_cfgs, HTP_ERROR, HTP_OK, HTP_UNWANTED_IGNORE, HTP_URL_DECODE_PRESERVE_PERCENT, HTP_URL_DECODE_PROCESS_INVALID, HTP_URL_DECODE_REMOVE_PERCENT, HTP_URLEN_ENCODED_NUL, HTP_URLEN_INVALID_ENCODING, HTP_URLEN_RAW_NUL, htp_decoder_cfg_t::nul_encoded_terminates, htp_decoder_cfg_t::nul_encoded_unwanted, htp_decoder_cfg_t::nul_raw_terminates, htp_decoder_cfg_t::nul_raw_unwanted, htp_decoder_cfg_t::plusspace_decode, htp_decoder_cfg_t::u_encoding_decode, htp_decoder_cfg_t::u_encoding_unwanted, htp_decoder_cfg_t::url_encoding_invalid_handling, and htp_decoder_cfg_t::url_encoding_invalid_unwanted.
Referenced by htp_tx_urldecode_params_inplace(), htp_tx_urldecode_uri_inplace(), and htp_urldecode_inplace().
void htp_utf8_decode_path_inplace (htp_cfg_t * cfg, htp_tx_t * tx, bstr * path)
Decode a UTF-8 encoded path. Overlong characters will be decoded, invalid characters will be left as-is. Best-fit mapping will be used to convert UTF-8 into a single-byte stream.
Parameters
[in] cfg
[in] tx
[in] path
Definition at line 887 of file htp_util.c.
References htp_decoder_cfg_t::bestfit_replacement_byte, bstr_adjust_len(), bstr_len, bstr_ptr, htp_cfg_t::decoder_cfgs, htp_tx_t::flags, HTP_DECODER_URL_PATH, HTP_PATH_HALF_FULL_RANGE, HTP_PATH_UTF8_INVALID, HTP_PATH_UTF8_OVERLONG, HTP_PATH_UTF8_VALID, HTP_UNWANTED_IGNORE, HTP_UTF8_ACCEPT, htp_utf8_decode_allow_overlong(), HTP_UTF8_REJECT, htp_tx_t::response_status_expected_number, and htp_decoder_cfg_t::utf8_invalid_unwanted.
Referenced by htp_normalize_parsed_uri().
void htp_utf8_validate_path (htp_tx_t * tx, bstr * path)
Validate a path that is quite possibly UTF-8 encoded.
Parameters
[in] tx
[in] path
Definition at line 997 of file htp_util.c.
References bstr_len, bstr_ptr, htp_tx_t::flags, HTP_PATH_HALF_FULL_RANGE, HTP_PATH_UTF8_INVALID, HTP_PATH_UTF8_OVERLONG, HTP_PATH_UTF8_VALID, HTP_UTF8_ACCEPT, htp_utf8_decode_allow_overlong(), and HTP_UTF8_REJECT.
Referenced by htp_normalize_parsed_uri().
int htp_validate_hostname (bstr * hostname)
Implements relaxed (not strictly RFC) hostname validation.
Parameters
[in] hostname
Returns
1 if the supplied hostname is valid; 0 if it is not.
Definition at line 2515 of file htp_util.c.
References bstr_len, and bstr_ptr.
Referenced by htp_parse_header_hostport(), htp_parse_uri_hostport(), and htp_tx_state_request_line().