suricata: libhtp/htp/htp_request.c File Reference
htp_request.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Macros
#define IN_TEST_NEXT_BYTE_OR_RETURN(X)
#define IN_PEEK_NEXT(X)
#define IN_NEXT_BYTE(X)
#define IN_NEXT_BYTE_OR_RETURN(X)
#define IN_COPY_BYTE_OR_RETURN(X)
Functions
htp_status_t htp_connp_req_receiver_finalize_clear (htp_connp_t *connp)
htp_status_t htp_connp_REQ_CONNECT_CHECK (htp_connp_t *connp)
htp_status_t htp_connp_REQ_CONNECT_PROBE_DATA (htp_connp_t *connp)
htp_status_t htp_connp_REQ_CONNECT_WAIT_RESPONSE (htp_connp_t *connp)
htp_status_t htp_connp_REQ_BODY_CHUNKED_DATA_END (htp_connp_t *connp)
htp_status_t htp_connp_REQ_BODY_CHUNKED_DATA (htp_connp_t *connp)
htp_status_t htp_connp_REQ_BODY_CHUNKED_LENGTH (htp_connp_t *connp)
htp_status_t htp_connp_REQ_BODY_IDENTITY (htp_connp_t *connp)
htp_status_t htp_connp_REQ_BODY_DETERMINE (htp_connp_t *connp)
htp_status_t htp_connp_REQ_HEADERS (htp_connp_t *connp)
htp_status_t htp_connp_REQ_PROTOCOL (htp_connp_t *connp)
htp_status_t htp_connp_REQ_LINE_complete (htp_connp_t *connp)
htp_status_t htp_connp_REQ_LINE (htp_connp_t *connp)
htp_status_t htp_connp_REQ_FINALIZE (htp_connp_t *connp)
htp_status_t htp_connp_REQ_IGNORE_DATA_AFTER_HTTP_0_9 (htp_connp_t *connp)
htp_status_t htp_connp_REQ_IDLE (htp_connp_t *connp)
size_t htp_connp_req_data_consumed (htp_connp_t *connp)
int htp_connp_req_data (htp_connp_t *connp, const htp_time_t *timestamp, const void *data, size_t len)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_request.c.
Macro Definition Documentation
#define IN_COPY_BYTE_OR_RETURN (X)
Value:
if ((X)->in_current_read_offset < (X)->in_current_len) { \
    (X)->in_next_byte = (X)->in_current_data[(X)->in_current_read_offset]; \
    (X)->in_current_read_offset++; \
    (X)->in_stream_offset++; \
} else { \
    return HTP_DATA_BUFFER; \
}
Definition at line 75 of file htp_request.c.
Referenced by htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_REQ_HEADERS(), and htp_connp_REQ_LINE().
#define IN_NEXT_BYTE (X)
Value:
if ((X)->in_current_read_offset < (X)->in_current_len) { \
    (X)->in_next_byte = (X)->in_current_data[(X)->in_current_read_offset]; \
    (X)->in_current_read_offset++; \
    (X)->in_current_consume_offset++; \
    (X)->in_stream_offset++; \
} else { \
    (X)->in_next_byte = -1; \
}
Definition at line 55 of file htp_request.c.
#define IN_NEXT_BYTE_OR_RETURN (X)
Value:
if ((X)->in_current_read_offset < (X)->in_current_len) { \
    (X)->in_next_byte = (X)->in_current_data[(X)->in_current_read_offset]; \
    (X)->in_current_read_offset++; \
    (X)->in_current_consume_offset++; \
    (X)->in_stream_offset++; \
} else { \
    return HTP_DATA; \
}
Definition at line 65 of file htp_request.c.
Referenced by htp_connp_REQ_BODY_CHUNKED_DATA_END().
#define IN_PEEK_NEXT (X)
Value:
if ((X)->in_current_read_offset >= (X)->in_current_len) { \
    (X)->in_next_byte = -1; \
} else { \
    (X)->in_next_byte = (X)->in_current_data[(X)->in_current_read_offset]; \
}
Definition at line 48 of file htp_request.c.
Referenced by htp_connp_REQ_CONNECT_PROBE_DATA(), and htp_connp_REQ_HEADERS().
#define IN_TEST_NEXT_BYTE_OR_RETURN (X)
Value:
if ((X)->in_current_read_offset >= (X)->in_current_len) { \
    return HTP_DATA; \
}
Definition at line 43 of file htp_request.c.
Referenced by htp_connp_REQ_IDLE().
Function Documentation
htp_status_t htp_connp_REQ_BODY_CHUNKED_DATA (htp_connp_t * connp)
Processes a chunk of data.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 437 of file htp_request.c.
References htp_connp_REQ_BODY_CHUNKED_DATA_END(), HTP_DATA, HTP_OK, htp_tx_req_process_body_data_ex(), htp_connp_t::in_chunked_length, htp_connp_t::in_current_consume_offset, htp_connp_t::in_current_data, htp_connp_t::in_current_len, htp_connp_t::in_current_read_offset, htp_connp_t::in_state, htp_connp_t::in_stream_offset, htp_connp_t::in_tx, and htp_tx_t::request_message_len.
Referenced by htp_connp_in_state_as_string(), and htp_connp_REQ_BODY_CHUNKED_LENGTH().
htp_status_t htp_connp_REQ_BODY_CHUNKED_DATA_END (htp_connp_t * connp)
Consumes bytes until the end of the current line.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 413 of file htp_request.c.
References htp_connp_REQ_BODY_CHUNKED_LENGTH(), HTP_ERROR, HTP_OK, htp_connp_t::in_next_byte, IN_NEXT_BYTE_OR_RETURN, htp_connp_t::in_state, htp_connp_t::in_tx, LF, and htp_tx_t::request_message_len.
Referenced by htp_connp_in_state_as_string(), and htp_connp_REQ_BODY_CHUNKED_DATA().
htp_status_t htp_connp_REQ_BODY_CHUNKED_LENGTH (htp_connp_t * connp)
Extracts chunk length.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 482 of file htp_request.c.
References data, fprint_raw_data(), htp_chomp(), htp_connp_REQ_BODY_CHUNKED_DATA(), htp_connp_REQ_HEADERS(), HTP_ERROR, htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, htp_parse_chunked_length(), HTP_REQUEST_TRAILER, htp_connp_t::in_chunked_length, IN_COPY_BYTE_OR_RETURN, htp_connp_t::in_next_byte, htp_connp_t::in_state, htp_connp_t::in_tx, len, LF, htp_tx_t::request_message_len, and htp_tx_t::request_progress.
Referenced by htp_connp_in_state_as_string(), htp_connp_REQ_BODY_CHUNKED_DATA_END(), and htp_connp_REQ_BODY_DETERMINE().
htp_status_t htp_connp_REQ_BODY_DETERMINE (htp_connp_t * connp)
Determines presence (and encoding) of a request body.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 573 of file htp_request.c.
References htp_tx_t::connp, HTP_CODING_CHUNKED, HTP_CODING_IDENTITY, HTP_CODING_NO_BODY, htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_REQ_BODY_IDENTITY(), htp_connp_REQ_FINALIZE(), HTP_ERROR, HTP_OK, HTP_REQUEST_BODY, htp_connp_t::in_body_data_left, htp_connp_t::in_content_length, htp_connp_t::in_state, htp_connp_t::in_tx, htp_tx_t::request_content_length, htp_tx_t::request_progress, and htp_tx_t::request_transfer_coding.
Referenced by htp_connp_in_state_as_string(), and htp_connp_REQ_CONNECT_CHECK().
htp_status_t htp_connp_REQ_BODY_IDENTITY (htp_connp_t * connp)
Processes identity request body.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 534 of file htp_request.c.
References htp_connp_REQ_FINALIZE(), HTP_DATA, HTP_OK, htp_tx_req_process_body_data_ex(), htp_connp_t::in_body_data_left, htp_connp_t::in_current_consume_offset, htp_connp_t::in_current_data, htp_connp_t::in_current_len, htp_connp_t::in_current_read_offset, htp_connp_t::in_state, htp_connp_t::in_stream_offset, htp_connp_t::in_tx, and htp_tx_t::request_message_len.
Referenced by htp_connp_in_state_as_string(), and htp_connp_REQ_BODY_DETERMINE().
htp_status_t htp_connp_REQ_CONNECT_CHECK (htp_connp_t * connp)
Performs a check for a CONNECT transaction to decide whether inbound parsing needs to be suspended.
Parameters
[in] connp
Returns
HTP_OK if the request does not use CONNECT, HTP_DATA_OTHER if inbound parsing needs to be suspended until we hear from the other side
Definition at line 291 of file htp_request.c.
References htp_connp_REQ_BODY_DETERMINE(), htp_connp_REQ_CONNECT_WAIT_RESPONSE(), HTP_DATA_OTHER, HTP_M_CONNECT, HTP_OK, HTP_STREAM_DATA_OTHER, htp_connp_t::in_state, htp_connp_t::in_status, htp_connp_t::in_tx, and htp_tx_t::request_method_number.
Referenced by htp_connp_in_state_as_string(), and htp_tx_state_request_headers().
htp_status_t htp_connp_REQ_CONNECT_PROBE_DATA (htp_connp_t * connp)
Determines whether inbound parsing needs to continue or stop. In case the data appears to be plain text HTTP, we try to continue.
Parameters
[in] connp
Returns
HTP_OK if the parser can resume parsing, HTP_DATA_BUFFER if we need more data.
Definition at line 317 of file htp_request.c.
References bstr_dup_mem(), bstr_free(), data, fprint_raw_data(), htp_connp_REQ_IDLE(), htp_convert_method_to_number(), HTP_ERROR, htp_is_space(), HTP_M_UNKNOWN, HTP_OK, HTP_STREAM_TUNNEL, IN_COPY_BYTE_OR_RETURN, htp_connp_t::in_next_byte, IN_PEEK_NEXT, htp_connp_t::in_state, htp_connp_t::in_status, len, LF, and htp_connp_t::out_status.
Referenced by htp_connp_REQ_CONNECT_WAIT_RESPONSE().
htp_status_t htp_connp_REQ_CONNECT_WAIT_RESPONSE (htp_connp_t * connp)
Determines whether inbound parsing, which was suspended after encountering a CONNECT transaction, can proceed (after receiving the response).
Parameters
[in] connp
Returns
HTP_OK if the parser can resume parsing, HTP_DATA_OTHER if it needs to continue waiting.
Definition at line 384 of file htp_request.c.
References htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_REQ_FINALIZE(), HTP_DATA_OTHER, HTP_OK, HTP_RESPONSE_LINE, htp_connp_t::in_state, htp_connp_t::in_tx, htp_tx_t::response_progress, and htp_tx_t::response_status_number.
Referenced by htp_connp_in_state_as_string(), and htp_connp_REQ_CONNECT_CHECK().
int htp_connp_req_data (htp_connp_t * connp, const htp_time_t * timestamp, const void * data, size_t len)
Parameters
[in] connp
[in] timestamp
[in] data
[in] len
Returns
HTP_STREAM_DATA, HTP_STREAM_ERROR or STEAM_STATE_DATA_OTHER (see QUICK_START). HTP_STREAM_CLOSED and HTP_STREAM_TUNNEL are also possible.
Definition at line 848 of file htp_request.c.
References htp_connp_t::conn, fprint_raw_data(), htp_conn_track_inbound_data(), htp_connp_in_state_as_string(), htp_connp_REQ_IDLE(), HTP_DATA, HTP_DATA_BUFFER, HTP_DATA_OTHER, htp_log(), HTP_LOG_ERROR, HTP_LOG_INFO, HTP_LOG_MARK, HTP_OK, HTP_STOP, HTP_STREAM_CLOSED, HTP_STREAM_DATA, HTP_STREAM_DATA_OTHER, HTP_STREAM_ERROR, HTP_STREAM_STOP, HTP_STREAM_TUNNEL, htp_tx_request_progress_as_string(), htp_connp_t::in_chunk_count, htp_connp_t::in_current_consume_offset, htp_connp_t::in_current_data, htp_connp_t::in_current_len, htp_connp_t::in_current_read_offset, htp_connp_t::in_current_receiver_offset, htp_connp_t::in_state, htp_connp_t::in_status, htp_connp_t::in_timestamp, htp_connp_t::in_tx, len, and htp_connp_t::out_status.
Referenced by htp_connp_close().
size_t htp_connp_req_data_consumed (htp_connp_t * connp)
Returns how many bytes from the current data chunks were consumed so far.
Parameters
[in] connp
Returns
The number of bytes consumed.
Definition at line 844 of file htp_request.c.
References htp_connp_t::in_current_read_offset.
htp_status_t htp_connp_REQ_FINALIZE (htp_connp_t * connp)
Definition at line 794 of file htp_request.c.
References htp_tx_state_request_complete(), and htp_connp_t::in_tx.
Referenced by htp_connp_in_state_as_string(), htp_connp_REQ_BODY_DETERMINE(), htp_connp_REQ_BODY_IDENTITY(), htp_connp_REQ_CONNECT_WAIT_RESPONSE(), htp_connp_REQ_PROTOCOL(), and htp_tx_state_request_headers().
htp_status_t htp_connp_REQ_HEADERS (htp_connp_t * connp)
Parses request headers.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 616 of file htp_request.c.
References bstr_add_mem(), bstr_dup_mem(), bstr_free(), bstr_len, bstr_ptr, htp_connp_t::cfg, data, htp_tx_t::flags, fprint_raw_data(), htp_chomp(), htp_connp_is_line_folded(), htp_connp_is_line_terminator(), HTP_ERROR, HTP_INVALID_FOLDING, htp_is_folding_char(), htp_log(), HTP_LOG_MARK, HTP_LOG_WARNING, HTP_OK, htp_tx_state_request_headers(), IN_COPY_BYTE_OR_RETURN, htp_connp_t::in_header, htp_connp_t::in_next_byte, IN_PEEK_NEXT, htp_connp_t::in_tx, len, LF, and htp_cfg_t::process_request_header.
Referenced by htp_connp_in_state_as_string(), htp_connp_REQ_BODY_CHUNKED_LENGTH(), and htp_connp_REQ_PROTOCOL().
htp_status_t htp_connp_REQ_IDLE (htp_connp_t * connp)
The idle state is where the parser will end up after a transaction is processed. If there is more data available, a new request will be started.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 821 of file htp_request.c.
References htp_connp_tx_create(), HTP_ERROR, HTP_OK, htp_tx_state_request_start(), IN_TEST_NEXT_BYTE_OR_RETURN, and htp_connp_t::in_tx.
Referenced by htp_connp_create(), htp_connp_in_state_as_string(), htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_req_data(), and htp_tx_state_request_complete().
htp_status_t htp_connp_REQ_IGNORE_DATA_AFTER_HTTP_0_9 (htp_connp_t * connp)
Definition at line 798 of file htp_request.c.
References htp_connp_t::conn, htp_conn_t::flags, HTP_CONN_HTTP_0_9_EXTRA, HTP_DATA, htp_connp_t::in_current_consume_offset, htp_connp_t::in_current_len, htp_connp_t::in_current_read_offset, and htp_connp_t::in_stream_offset.
Referenced by htp_connp_in_state_as_string(), and htp_tx_state_request_complete().
htp_status_t htp_connp_REQ_LINE (htp_connp_t * connp)
Parses request line.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 780 of file htp_request.c.
References htp_connp_REQ_LINE_complete(), HTP_ERROR, IN_COPY_BYTE_OR_RETURN, htp_connp_t::in_next_byte, and LF.
Referenced by htp_connp_in_state_as_string(), htp_tx_state_request_start(), and htp_tx_state_response_start().
htp_status_t htp_connp_REQ_LINE_complete (htp_connp_t * connp)
Parse the request line.
Parameters
[in] connp
Returns
HTP_OK on succesful parse, HTP_ERROR on error.
Definition at line 731 of file htp_request.c.
References bstr_dup_mem(), htp_connp_t::cfg, data, fprint_raw_data(), htp_chomp(), htp_connp_is_line_ignorable(), HTP_ERROR, HTP_OK, htp_tx_state_request_line(), htp_connp_t::in_tx, len, htp_cfg_t::parse_request_line, htp_tx_t::request_ignored_lines, and htp_tx_t::request_line.
Referenced by htp_connp_REQ_LINE(), and htp_tx_state_response_start().
htp_status_t htp_connp_REQ_PROTOCOL (htp_connp_t * connp)
Determines request protocol.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 710 of file htp_request.c.
References htp_connp_REQ_FINALIZE(), htp_connp_REQ_HEADERS(), HTP_OK, HTP_REQUEST_HEADERS, htp_connp_t::in_state, htp_connp_t::in_tx, htp_tx_t::is_protocol_0_9, and htp_tx_t::request_progress.
Referenced by htp_connp_in_state_as_string(), and htp_tx_state_request_line().
htp_status_t htp_connp_req_receiver_finalize_clear (htp_connp_t * connp)
Finalizes an existing data receiver hook by sending any outstanding data to it. The hook is then removed so that it receives no more data.
Parameters
[in] connp
Returns
HTP_OK, or a value returned from a callback.
Definition at line 131 of file htp_request.c.
References HTP_OK, and htp_connp_t::in_data_receiver_hook.
Referenced by htp_tx_state_request_headers().