suricata: libhtp/htp/htp_content_handlers.c File Reference
htp_content_handlers.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Functions
htp_status_t htp_ch_urlencoded_callback_request_body_data (htp_tx_data_t *d)
htp_status_t htp_ch_urlencoded_callback_request_headers (htp_tx_t *tx)
htp_status_t htp_ch_urlencoded_callback_request_line (htp_tx_t *tx)
htp_status_t htp_ch_multipart_callback_request_body_data (htp_tx_data_t *d)
htp_status_t htp_ch_multipart_callback_request_headers (htp_tx_t *tx)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_content_handlers.c.
Function Documentation
htp_status_t htp_ch_multipart_callback_request_body_data (htp_tx_data_t * d)
Finalize Multipart processing.
Parameters
[in] d
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 193 of file htp_content_handlers.c.
References htp_tx_data_t::data, htp_mpartp_t::gave_up_data, HTP_ERROR, htp_list_get, htp_list_size, htp_mpartp_finalize(), htp_mpartp_get_multipart(), htp_mpartp_parse(), HTP_OK, HTP_PARSER_MULTIPART, HTP_SOURCE_BODY, htp_tx_req_add_param(), htp_tx_data_t::len, MULTIPART_PART_TEXT, htp_param_t::name, htp_multipart_part_t::name, htp_param_t::parser_data, htp_param_t::parser_id, htp_multipart_t::parts, htp_tx_t::request_mpartp, htp_param_t::source, htp_tx_data_t::tx, htp_multipart_part_t::type, htp_param_t::value, and htp_multipart_part_t::value.
Referenced by htp_ch_multipart_callback_request_headers().
htp_status_t htp_ch_multipart_callback_request_headers (htp_tx_t * tx)
Inspect request headers and register the Multipart request data hook if it contains a multipart/form-data body.
Parameters
[in] connp
Returns
HTP_OK if a new parser has been setup, HTP_DECLINED if the MIME type is not appropriate for this parser, and HTP_ERROR on failure.
Definition at line 244 of file htp_content_handlers.c.
References bstr_free(), htp_connp_t::cfg, htp_tx_t::cfg, htp_tx_t::connp, htp_mpartp_t::extract_dir, htp_mpartp_t::extract_files, htp_cfg_t::extract_request_files, flags, htp_ch_multipart_callback_request_body_data(), HTP_DECLINED, HTP_ERROR, htp_mpartp_create(), htp_mpartp_find_boundary(), HTP_OK, htp_table_get_c(), htp_tx_register_request_body_data(), htp_tx_t::request_content_type, htp_tx_t::request_headers, htp_tx_t::request_mpartp, htp_cfg_t::tmpdir, and htp_header_t::value.
Referenced by htp_config_register_multipart_parser().
htp_status_t htp_ch_urlencoded_callback_request_body_data (htp_tx_data_t * d)
This callback function feeds request body data to a Urlencoded parser and, later, feeds the parsed parameters to the correct structures.
Parameters
[in] d
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 50 of file htp_content_handlers.c.
References htp_tx_data_t::data, HTP_ERROR, HTP_OK, HTP_PARSER_URLENCODED, HTP_SOURCE_BODY, htp_table_destroy_ex(), htp_table_get_index(), htp_table_size(), htp_tx_req_add_param(), htp_urlenp_finalize(), htp_urlenp_parse_partial(), htp_tx_data_t::len, htp_param_t::name, htp_urlenp_t::params, htp_param_t::parser_data, htp_param_t::parser_id, htp_tx_t::request_urlenp_body, htp_param_t::source, htp_tx_data_t::tx, and htp_param_t::value.
Referenced by htp_ch_urlencoded_callback_request_headers().
htp_status_t htp_ch_urlencoded_callback_request_headers (htp_tx_t * tx)
Determine if the request has a Urlencoded body, and, if it does, create and attach an instance of the Urlencoded parser to the transaction.
Parameters
[in] connp
Returns
HTP_OK if a new parser has been setup, HTP_DECLINED if the MIME type is not appropriate for this parser, and HTP_ERROR on failure.
Definition at line 103 of file htp_content_handlers.c.
References bstr_begins_with_c(), htp_ch_urlencoded_callback_request_body_data(), HTP_DECLINED, HTP_ERROR, HTP_OK, htp_tx_register_request_body_data(), HTP_URLENCODED_MIME_TYPE, htp_urlenp_create(), htp_tx_t::request_content_type, and htp_tx_t::request_urlenp_body.
Referenced by htp_config_register_urlencoded_parser().
htp_status_t htp_ch_urlencoded_callback_request_line (htp_tx_t * tx)
Parses request query string, if present.
Parameters
[in] connp
[in] raw_data
[in] raw_len
Returns
HTP_OK if query string was parsed, HTP_DECLINED if there was no query string, and HTP_ERROR on failure.
Definition at line 136 of file htp_content_handlers.c.
References bstr_len, bstr_ptr, HTP_DECLINED, HTP_ERROR, HTP_OK, HTP_PARSER_URLENCODED, HTP_SOURCE_QUERY_STRING, htp_table_destroy_ex(), htp_table_get_index(), htp_table_size(), htp_tx_req_add_param(), htp_urlenp_create(), htp_urlenp_destroy(), htp_urlenp_parse_complete(), htp_param_t::name, htp_urlenp_t::params, htp_tx_t::parsed_uri, htp_param_t::parser_data, htp_param_t::parser_id, htp_uri_t::query, htp_tx_t::request_urlenp_query, htp_param_t::source, and htp_param_t::value.
Referenced by htp_config_register_urlencoded_parser().