suricata: libhtp/htp/htp_hooks.c File Reference
htp_hooks.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Functions
htp_hook_t * htp_hook_copy (const htp_hook_t *hook)
htp_hook_t * htp_hook_create (void)
void htp_hook_destroy (htp_hook_t *hook)
htp_status_t htp_hook_register (htp_hook_t **hook, const htp_callback_fn_t callback_fn)
htp_status_t htp_hook_run_all (htp_hook_t *hook, void *user_data)
htp_status_t htp_hook_run_one (htp_hook_t *hook, void *user_data)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_hooks.c.
Function Documentation
htp_hook_t* htp_hook_copy (const htp_hook_t * hook)
Creates a copy of the provided hook. The hook is allowed to be NULL, in which case this function simply returns a NULL.
Parameters
[in] hook
Returns
A copy of the hook, or NULL (if the provided hook was NULL or, if it wasn't, if there was a memory allocation problem while constructing a copy).
Definition at line 43 of file htp_hooks.c.
References htp_hook_t::callbacks, htp_callback_t::fn, htp_hook_create(), htp_hook_destroy(), htp_hook_register(), htp_list_get, htp_list_size, and HTP_OK.
Referenced by htp_config_copy().
htp_hook_t* htp_hook_create (void)
Creates a new hook.
Returns
New htp_hook_t structure on success, NULL on failure.
Definition at line 60 of file htp_hooks.c.
References htp_hook_t::callbacks, and htp_list_array_create().
Referenced by htp_hook_copy(), and htp_hook_register().
void htp_hook_destroy (htp_hook_t * hook)
Destroys an existing hook. It is all right to send a NULL to this method because it will simply return straight away.
Parameters
[in] hook
Definition at line 73 of file htp_hooks.c.
References htp_hook_t::callbacks, htp_list_array_destroy(), htp_list_get, and htp_list_size.
Referenced by htp_config_destroy(), htp_hook_copy(), and htp_tx_destroy_incomplete().
htp_status_t htp_hook_register (htp_hook_t ** hook, const htp_callback_fn_t callback_fn)
Registers a new callback with the hook.
Parameters
[in] hook
[in] callback_fn
Returns
HTP_OK on success, HTP_ERROR on memory allocation error.
Definition at line 85 of file htp_hooks.c.
References htp_callback_t::fn, HTP_ERROR, htp_hook_create(), htp_list_array_push(), and HTP_OK.
Referenced by htp_config_register_log(), htp_config_register_request_body_data(), htp_config_register_request_complete(), htp_config_register_request_file_data(), htp_config_register_request_header_data(), htp_config_register_request_headers(), htp_config_register_request_line(), htp_config_register_request_start(), htp_config_register_request_trailer(), htp_config_register_request_trailer_data(), htp_config_register_request_uri_normalize(), htp_config_register_response_body_data(), htp_config_register_response_complete(), htp_config_register_response_header_data(), htp_config_register_response_headers(), htp_config_register_response_line(), htp_config_register_response_start(), htp_config_register_response_trailer(), htp_config_register_response_trailer_data(), htp_config_register_transaction_complete(), htp_hook_copy(), htp_tx_register_request_body_data(), and htp_tx_register_response_body_data().
htp_status_t htp_hook_run_all (htp_hook_t * hook, void * user_data)
Runs all the callbacks associated with a given hook. Only stops if one of the callbacks returns an error (HTP_ERROR) or stop (HTP_STOP).
Parameters
[in] hook
[in] user_data
Returns
HTP_OK if at least one hook ran successfully, HTP_STOP if there was no error but processing should stop, and HTP_ERROR or any other value less than zero on error.
Definition at line 120 of file htp_hooks.c.
References htp_hook_t::callbacks, htp_callback_t::fn, HTP_DECLINED, htp_list_get, htp_list_size, and HTP_OK.
Referenced by htp_connp_RES_HEADERS(), htp_log(), htp_mpartp_run_request_file_data_hook(), htp_req_run_hook_body_data(), htp_res_run_hook_body_data(), htp_tx_finalize(), htp_tx_state_request_complete_partial(), htp_tx_state_request_headers(), htp_tx_state_request_line(), htp_tx_state_request_start(), htp_tx_state_response_complete_ex(), htp_tx_state_response_headers(), htp_tx_state_response_line(), and htp_tx_state_response_start().
htp_status_t htp_hook_run_one (htp_hook_t * hook, void * user_data)
Run callbacks one by one until one of them accepts to service the hook.
Parameters
[in] hook
[in] user_data
Returns
HTP_OK if a hook was found to process the callback, HTP_DECLINED if no hook could be found, HTP_STOP if a hook signalled the processing to stop, and HTP_ERROR or any other value less than zero on error.
Definition at line 140 of file htp_hooks.c.
References htp_hook_t::callbacks, htp_callback_t::fn, HTP_DECLINED, htp_list_get, and htp_list_size.