suricata: libhtp/htp/htp_request_apache_2_2.c File Reference
htp_request_apache_2_2.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Functions
htp_status_t htp_process_request_header_apache_2_2 (htp_connp_t *connp, unsigned char *data, size_t len)
htp_status_t htp_parse_request_line_apache_2_2 (htp_connp_t *connp)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_request_apache_2_2.c.
Function Documentation
htp_status_t htp_parse_request_line_apache_2_2 (htp_connp_t * connp)
Parse request line as Apache 2.2 does.
Parameters
[in] connp
Returns
HTP_OK or HTP_ERROR
Definition at line 62 of file htp_request_apache_2_2.c.
References htp_parse_request_line_generic_ex().
Referenced by htp_config_set_server_personality().
htp_status_t htp_process_request_header_apache_2_2 (htp_connp_t * connp, unsigned char * data, size_t len)
Extract one request header. A header can span multiple lines, in which case they will be folded into one before parsing is attempted.
Parameters
[in] connp
[in] data
[in] len
Returns
HTP_OK or HTP_ERROR
Definition at line 52 of file htp_request_apache_2_2.c.
References htp_process_request_header_generic().
Referenced by htp_config_set_server_personality().