suricata: libhtp/htp/htp_urlencoded.h File Reference
htp_urlencoded.h File Reference
#include "htp.h"
Data Structures
struct htp_urlenp_t
struct htp_urlen_param_t
Macros
#define HTP_URLENP_DEFAULT_PARAMS_SIZE 32
#define HTP_URLENP_STATE_KEY 1
#define HTP_URLENP_STATE_VALUE 2
#define HTP_URLENCODED_MIME_TYPE "application/x-www-form-urlencoded"
Typedefs
typedef struct htp_urlenp_t htp_urlenp_t
typedef struct htp_urlen_param_t htp_urlen_param_t
Functions
htp_urlenp_t * htp_urlenp_create (htp_tx_t *tx)
void htp_urlenp_destroy (htp_urlenp_t *urlenp)
void htp_urlenp_set_argument_separator (htp_urlenp_t *urlenp, unsigned char argument_separator)
void htp_urlenp_set_decode_url_encoding (htp_urlenp_t *urlenp, int decode_url_encoding)
htp_status_t htp_urlenp_parse_partial (htp_urlenp_t *urlenp, const void *data, size_t len)
htp_status_t htp_urlenp_parse_complete (htp_urlenp_t *urlenp, const void *data, size_t len)
htp_status_t htp_urlenp_finalize (htp_urlenp_t *urlenp)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_urlencoded.h.
Macro Definition Documentation
#define HTP_URLENCODED_MIME_TYPE "application/x-www-form-urlencoded"
Definition at line 55 of file htp_urlencoded.h.
Referenced by htp_ch_urlencoded_callback_request_headers().
#define HTP_URLENP_DEFAULT_PARAMS_SIZE 32
Definition at line 49 of file htp_urlencoded.h.
Referenced by htp_urlenp_create().
#define HTP_URLENP_STATE_KEY 1
Definition at line 51 of file htp_urlencoded.h.
Referenced by htp_urlenp_create(), and htp_urlenp_parse_partial().
#define HTP_URLENP_STATE_VALUE 2
Definition at line 52 of file htp_urlencoded.h.
Referenced by htp_urlenp_parse_partial().
Typedef Documentation
typedef struct htp_urlen_param_t htp_urlen_param_t
Definition at line 47 of file htp_urlencoded.h.
typedef struct htp_urlenp_t htp_urlenp_t
Definition at line 46 of file htp_urlencoded.h.
Function Documentation
htp_urlenp_t* htp_urlenp_create (htp_tx_t * tx)
Creates a new URLENCODED parser.
Returns
New parser, or NULL on memory allocation failure.
Definition at line 176 of file htp_urlencoded.c.
References htp_urlenp_t::_bb, htp_urlenp_t::_state, htp_urlenp_t::argument_separator, bstr_builder_create(), htp_urlenp_t::decode_url_encoding, htp_table_create(), htp_table_destroy(), HTP_URLENP_DEFAULT_PARAMS_SIZE, HTP_URLENP_STATE_KEY, htp_urlenp_t::params, and htp_urlenp_t::tx.
Referenced by htp_ch_urlencoded_callback_request_headers(), and htp_ch_urlencoded_callback_request_line().
void htp_urlenp_destroy (htp_urlenp_t * urlenp)
Destroys an existing URLENCODED parser.
Parameters
[in] urlenp
Definition at line 207 of file htp_urlencoded.c.
References htp_urlenp_t::_bb, htp_urlenp_t::_name, bstr_builder_destroy(), bstr_free(), htp_table_destroy(), htp_table_get_index(), htp_table_size(), and htp_urlenp_t::params.
Referenced by htp_ch_urlencoded_callback_request_line(), and htp_tx_destroy_incomplete().
htp_status_t htp_urlenp_finalize (htp_urlenp_t * urlenp)
Finalizes parsing, forcing the parser to convert any outstanding data into parameters. This method should be invoked at the end of a parsing operation that used htp_urlenp_parse_partial().
Parameters
[in] urlenp
Returns
Success indication
Definition at line 238 of file htp_urlencoded.c.
References htp_urlenp_t::_complete, and htp_urlenp_parse_partial().
Referenced by htp_ch_urlencoded_callback_request_body_data(), and htp_urlenp_parse_complete().
htp_status_t htp_urlenp_parse_complete (htp_urlenp_t * urlenp, const void * data, size_t len)
Parses the provided data chunk under the assumption that it contains all the data that will be parsed. When this method is used for parsing the finalization method should not be invoked.
Parameters
[in] urlenp
[in] data
[in] len
Returns
Definition at line 254 of file htp_urlencoded.c.
References htp_urlenp_finalize(), and htp_urlenp_parse_partial().
Referenced by htp_ch_urlencoded_callback_request_line().
htp_status_t htp_urlenp_parse_partial (htp_urlenp_t * urlenp, const void * _data, size_t len)
Parses the provided data chunk, keeping state to allow streaming parsing, i.e., the parsing where only partial information is available at any one time. The method htp_urlenp_finalize() must be invoked at the end to finalize parsing.
Parameters
[in] urlenp
[in] _data
[in] len
Returns
Definition at line 269 of file htp_urlencoded.c.
References htp_urlenp_t::_state, htp_urlenp_t::argument_separator, HTP_ERROR, HTP_OK, HTP_URLENP_STATE_KEY, and HTP_URLENP_STATE_VALUE.
Referenced by htp_ch_urlencoded_callback_request_body_data(), htp_urlenp_finalize(), and htp_urlenp_parse_complete().
void htp_urlenp_set_argument_separator (htp_urlenp_t * urlenp, unsigned char argument_separator)
void htp_urlenp_set_decode_url_encoding (htp_urlenp_t * urlenp, int decode_url_encoding)