suricata: libhtp/htp/htp_response.c File Reference
htp_response.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Macros
#define OUT_TEST_NEXT_BYTE_OR_RETURN(X)
#define OUT_PEEK_NEXT(X)
#define OUT_NEXT_BYTE(X)
#define OUT_NEXT_BYTE_OR_RETURN(X)
#define OUT_COPY_BYTE_OR_RETURN(X)
Functions
htp_status_t htp_connp_res_receiver_finalize_clear (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_CHUNKED_DATA_END (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_CHUNKED_DATA (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_CHUNKED_LENGTH (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_IDENTITY_CL_KNOWN (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_DETERMINE (htp_connp_t *connp)
htp_status_t htp_connp_RES_HEADERS (htp_connp_t *connp)
htp_status_t htp_connp_RES_LINE (htp_connp_t *connp)
size_t htp_connp_res_data_consumed (htp_connp_t *connp)
htp_status_t htp_connp_RES_FINALIZE (htp_connp_t *connp)
htp_status_t htp_connp_RES_IDLE (htp_connp_t *connp)
int htp_connp_res_data (htp_connp_t *connp, const htp_time_t *timestamp, const void *data, size_t len)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_response.c.
Macro Definition Documentation
#define OUT_COPY_BYTE_OR_RETURN (X)
Value:
if ((X)->out_current_read_offset < (X)->out_current_len) { \
    (X)->out_next_byte = (X)->out_current_data[(X)->out_current_read_offset]; \
    (X)->out_current_read_offset++; \
    (X)->out_stream_offset++; \
} else { \
    return HTP_DATA_BUFFER; \
}
Definition at line 75 of file htp_response.c.
Referenced by htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_RES_HEADERS(), and htp_connp_RES_LINE().
#define OUT_NEXT_BYTE (X)
Value:
if ((X)->out_current_read_offset < (X)->out_current_len) { \
    (X)->out_next_byte = (X)->out_current_data[(X)->out_current_read_offset]; \
    (X)->out_current_read_offset++; \
    (X)->out_current_consume_offset++; \
    (X)->out_stream_offset++; \
} else { \
    (X)->out_next_byte = -1; \
}
Definition at line 55 of file htp_response.c.
#define OUT_NEXT_BYTE_OR_RETURN (X)
Value:
if ((X)->out_current_read_offset < (X)->out_current_len) { \
    (X)->out_next_byte = (X)->out_current_data[(X)->out_current_read_offset]; \
    (X)->out_current_read_offset++; \
    (X)->out_current_consume_offset++; \
    (X)->out_stream_offset++; \
} else { \
    return HTP_DATA; \
}
Definition at line 65 of file htp_response.c.
Referenced by htp_connp_RES_BODY_CHUNKED_DATA_END().
#define OUT_PEEK_NEXT (X)
Value:
if ((X)->out_current_read_offset >= (X)->out_current_len) { \
    (X)->out_next_byte = -1; \
} else { \
    (X)->out_next_byte = (X)->out_current_data[(X)->out_current_read_offset]; \
}
Definition at line 48 of file htp_response.c.
Referenced by htp_connp_RES_HEADERS().
#define OUT_TEST_NEXT_BYTE_OR_RETURN (X)
Value:
if ((X)->out_current_read_offset >= (X)->out_current_len) { \
    return HTP_DATA; \
}
Definition at line 43 of file htp_response.c.
Referenced by htp_connp_RES_IDLE().
Function Documentation
htp_status_t htp_connp_RES_BODY_CHUNKED_DATA (htp_connp_t * connp)
Processes a chunk of data.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 312 of file htp_response.c.
References htp_connp_RES_BODY_CHUNKED_DATA_END(), HTP_DATA, HTP_OK, htp_tx_res_process_body_data_ex(), htp_connp_t::out_chunked_length, htp_connp_t::out_current_consume_offset, htp_connp_t::out_current_data, htp_connp_t::out_current_len, htp_connp_t::out_current_read_offset, htp_connp_t::out_state, htp_connp_t::out_stream_offset, and htp_connp_t::out_tx.
Referenced by htp_connp_out_state_as_string(), and htp_connp_RES_BODY_CHUNKED_LENGTH().
htp_status_t htp_connp_RES_BODY_CHUNKED_DATA_END (htp_connp_t * connp)
Consumes bytes until the end of the current line.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 287 of file htp_response.c.
References htp_connp_RES_BODY_CHUNKED_LENGTH(), HTP_ERROR, HTP_OK, LF, htp_connp_t::out_next_byte, OUT_NEXT_BYTE_OR_RETURN, htp_connp_t::out_state, htp_connp_t::out_tx, and htp_tx_t::response_message_len.
Referenced by htp_connp_out_state_as_string(), and htp_connp_RES_BODY_CHUNKED_DATA().
htp_status_t htp_connp_RES_BODY_CHUNKED_LENGTH (htp_connp_t * connp)
Extracts chunk length.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 349 of file htp_response.c.
References data, fprint_raw_data(), htp_chomp(), htp_connp_RES_BODY_CHUNKED_DATA(), htp_connp_RES_HEADERS(), HTP_ERROR, htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, htp_parse_chunked_length(), HTP_RESPONSE_TRAILER, len, LF, htp_connp_t::out_chunked_length, OUT_COPY_BYTE_OR_RETURN, htp_connp_t::out_next_byte, htp_connp_t::out_state, htp_connp_t::out_tx, htp_tx_t::response_message_len, and htp_tx_t::response_progress.
Referenced by htp_connp_out_state_as_string(), htp_connp_RES_BODY_CHUNKED_DATA_END(), and htp_connp_RES_BODY_DETERMINE().
htp_status_t htp_connp_RES_BODY_DETERMINE (htp_connp_t * connp)
Determines presence (and encoding) of a response body.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 469 of file htp_response.c.
References bstr_adjust_len(), bstr_cmp_c_nocase(), bstr_dup_lower(), bstr_free(), bstr_index_of_c_nocase(), bstr_len, bstr_ptr, htp_header_t::flags, htp_tx_t::flags, HTP_CODING_CHUNKED, HTP_CODING_IDENTITY, HTP_CODING_NO_BODY, htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_RES_BODY_IDENTITY_CL_KNOWN(), htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE(), htp_connp_RES_FINALIZE(), htp_connp_RES_LINE(), HTP_ERROR, HTP_FIELD_REPEATED, htp_is_space(), htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_M_CONNECT, HTP_M_HEAD, HTP_OK, htp_parse_content_length(), HTP_REQUEST_SMUGGLING, HTP_RESPONSE_BODY, HTP_RESPONSE_LINE, HTP_STREAM_DATA, htp_table_clear(), htp_table_get_c(), htp_table_get_index(), htp_table_size(), htp_tx_state_response_headers(), htp_connp_t::in_status, htp_header_t::name, htp_connp_t::out_body_data_left, htp_connp_t::out_content_length, htp_connp_t::out_data_other_at_tx_end, htp_connp_t::out_state, htp_connp_t::out_tx, htp_tx_t::request_method_number, htp_tx_t::response_content_length, htp_tx_t::response_content_type, htp_tx_t::response_headers, htp_tx_t::response_progress, htp_tx_t::response_status_number, htp_tx_t::response_transfer_coding, htp_tx_t::seen_100continue, and htp_header_t::value.
Referenced by htp_connp_out_state_as_string(), and htp_connp_RES_HEADERS().
htp_status_t htp_connp_RES_BODY_IDENTITY_CL_KNOWN (htp_connp_t * connp)
Processes an identity response body of known length.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 402 of file htp_response.c.
References htp_connp_RES_FINALIZE(), HTP_DATA, HTP_OK, htp_tx_res_process_body_data_ex(), htp_connp_t::out_body_data_left, htp_connp_t::out_current_consume_offset, htp_connp_t::out_current_data, htp_connp_t::out_current_len, htp_connp_t::out_current_read_offset, htp_connp_t::out_state, htp_connp_t::out_stream_offset, and htp_connp_t::out_tx.
Referenced by htp_connp_out_state_as_string(), and htp_connp_RES_BODY_DETERMINE().
htp_status_t htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE (htp_connp_t * connp)
Processes identity response body of unknown length. In this case, we assume the response body consumes all data until the end of the stream.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 440 of file htp_response.c.
References htp_connp_RES_FINALIZE(), HTP_DATA, HTP_OK, HTP_STREAM_CLOSED, htp_tx_res_process_body_data_ex(), htp_connp_t::out_current_consume_offset, htp_connp_t::out_current_data, htp_connp_t::out_current_len, htp_connp_t::out_current_read_offset, htp_connp_t::out_state, htp_connp_t::out_status, htp_connp_t::out_stream_offset, and htp_connp_t::out_tx.
Referenced by htp_connp_out_state_as_string(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_LINE(), and htp_tx_state_response_start().
int htp_connp_res_data (htp_connp_t * connp, const htp_time_t * timestamp, const void * data, size_t len)
Process a chunk of outbound (server or response) data.
Parameters
[in] connp
[in] timestamp Optional.
[in] data
[in] len
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed
Definition at line 906 of file htp_response.c.
References htp_connp_t::conn, fprint_raw_data(), htp_conn_track_outbound_data(), htp_connp_out_state_as_string(), htp_connp_RES_IDLE(), HTP_DATA, HTP_DATA_BUFFER, HTP_DATA_OTHER, htp_log(), HTP_LOG_ERROR, HTP_LOG_INFO, HTP_LOG_MARK, HTP_OK, HTP_STOP, HTP_STREAM_CLOSED, HTP_STREAM_DATA, HTP_STREAM_DATA_OTHER, HTP_STREAM_ERROR, HTP_STREAM_STOP, HTP_STREAM_TUNNEL, htp_tx_response_progress_as_string(), len, htp_connp_t::out_current_consume_offset, htp_connp_t::out_current_data, htp_connp_t::out_current_len, htp_connp_t::out_current_read_offset, htp_connp_t::out_current_receiver_offset, htp_connp_t::out_state, htp_connp_t::out_status, htp_connp_t::out_timestamp, and htp_connp_t::out_tx.
Referenced by htp_connp_close().
size_t htp_connp_res_data_consumed (htp_connp_t * connp)
Returns the number of bytes consumed from the most recent outbound data chunk. Normally, an invocation of htp_connp_res_data() will consume all data from the supplied buffer, but there are circumstances where only partial consumption is possible. In such cases HTP_STREAM_DATA_OTHER will be returned. Consumed bytes are no longer necessary, but the remainder of the buffer will be need to be saved for later.
Parameters
[in] connp
Returns
The number of bytes consumed from the last data chunk sent for outbound processing.
Definition at line 860 of file htp_response.c.
References htp_connp_t::out_current_read_offset.
htp_status_t htp_connp_RES_FINALIZE (htp_connp_t * connp)
Definition at line 864 of file htp_response.c.
References htp_tx_state_response_complete_ex(), and htp_connp_t::out_tx.
Referenced by htp_connp_out_state_as_string(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_BODY_IDENTITY_CL_KNOWN(), htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE(), and htp_connp_RES_HEADERS().
htp_status_t htp_connp_RES_HEADERS (htp_connp_t * connp)
Parses response headers.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 642 of file htp_response.c.
References bstr_add_mem(), bstr_dup_mem(), bstr_free(), bstr_len, bstr_ptr, htp_connp_t::cfg, data, htp_tx_t::flags, fprint_raw_data(), htp_cfg_t::hook_response_trailer, htp_chomp(), htp_connp_is_line_folded(), htp_connp_is_line_terminator(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_FINALIZE(), htp_connp_res_receiver_finalize_clear(), HTP_ERROR, htp_hook_run_all(), HTP_INVALID_FOLDING, htp_is_folding_char(), htp_log(), HTP_LOG_MARK, HTP_LOG_WARNING, HTP_OK, HTP_RESPONSE_HEADERS, len, LF, OUT_COPY_BYTE_OR_RETURN, htp_connp_t::out_header, htp_connp_t::out_next_byte, OUT_PEEK_NEXT, htp_connp_t::out_state, htp_connp_t::out_tx, htp_cfg_t::process_response_header, and htp_tx_t::response_progress.
Referenced by htp_connp_out_state_as_string(), htp_connp_RES_BODY_CHUNKED_LENGTH(), and htp_connp_RES_LINE().
htp_status_t htp_connp_RES_IDLE (htp_connp_t * connp)
The response idle state will initialize response processing, as well as finalize each transactions after we are done with it.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 875 of file htp_response.c.
References htp_connp_t::conn, HTP_ERROR, htp_list_get, htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, htp_tx_state_response_start(), htp_connp_t::out_body_data_left, htp_connp_t::out_content_length, htp_connp_t::out_next_tx_index, OUT_TEST_NEXT_BYTE_OR_RETURN, htp_connp_t::out_tx, and htp_conn_t::transactions.
Referenced by htp_connp_create(), htp_connp_out_state_as_string(), htp_connp_res_data(), and htp_tx_state_response_complete_ex().
htp_status_t htp_connp_RES_LINE (htp_connp_t * connp)
Parses response line.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 756 of file htp_response.c.
References bstr_dup_mem(), bstr_free(), htp_connp_t::cfg, data, fprint_raw_data(), htp_chomp(), HTP_CODING_IDENTITY, HTP_COMPRESSION_NONE, htp_connp_is_line_ignorable(), htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE(), htp_connp_RES_HEADERS(), HTP_ERROR, HTP_OK, HTP_RESPONSE_BODY, HTP_RESPONSE_HEADERS, HTP_STREAM_CLOSED, htp_treat_response_line_as_body(), htp_tx_res_process_body_data_ex(), htp_tx_state_response_line(), len, LF, htp_connp_t::out_body_data_left, OUT_COPY_BYTE_OR_RETURN, htp_connp_t::out_next_byte, htp_connp_t::out_state, htp_connp_t::out_status, htp_connp_t::out_tx, htp_cfg_t::parse_response_line, htp_tx_t::response_content_encoding_processing, htp_tx_t::response_ignored_lines, htp_tx_t::response_line, htp_tx_t::response_message, htp_tx_t::response_progress, htp_tx_t::response_protocol, htp_tx_t::response_status, and htp_tx_t::response_transfer_coding.
Referenced by htp_connp_out_state_as_string(), htp_connp_RES_BODY_DETERMINE(), and htp_tx_state_response_start().
htp_status_t htp_connp_res_receiver_finalize_clear (htp_connp_t * connp)
Finalizes an existing data receiver hook by sending any outstanding data to it. The hook is then removed so that it receives no more data.
Parameters
[in] connp
Returns
HTP_OK, or a value returned from a callback.
Definition at line 115 of file htp_response.c.
References HTP_OK, and htp_connp_t::out_data_receiver_hook.
Referenced by htp_connp_RES_HEADERS(), and htp_tx_state_response_headers().