suricata: libhtp/htp/htp_connection_private.h File Reference
htp_connection_private.h File Reference
Functions
htp_conn_t * htp_conn_create (void)
void htp_conn_close (htp_conn_t *conn, const htp_time_t *timestamp)
void htp_conn_destroy (htp_conn_t *conn)
htp_status_t htp_conn_open (htp_conn_t *conn, const char *remote_addr, int remote_port, const char *local_addr, int local_port, const htp_time_t *timestamp)
htp_status_t htp_conn_remove_tx (htp_conn_t *conn, const htp_tx_t *tx)
void htp_conn_track_inbound_data (htp_conn_t *conn, size_t len, const htp_time_t *timestamp)
void htp_conn_track_outbound_data (htp_conn_t *conn, size_t len, const htp_time_t *timestamp)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_connection_private.h.
Function Documentation
void htp_conn_close (htp_conn_t * conn, const htp_time_t * timestamp)
Closes the connection.
Parameters
[in] conn
[in] timestamp
Definition at line 64 of file htp_connection.c.
References htp_conn_t::close_timestamp.
Referenced by htp_connp_close().
htp_conn_t* htp_conn_create (void)
Creates a new connection structure.
Returns
A new connection structure on success, NULL on memory allocation failure.
Definition at line 43 of file htp_connection.c.
References htp_list_create, htp_list_destroy, htp_conn_t::messages, and htp_conn_t::transactions.
Referenced by htp_connp_create().
void htp_conn_destroy (htp_conn_t * conn)
Destroys a connection, as well as all the transactions it contains. It is not possible to destroy a connection structure yet leave any of its transactions intact. This is because transactions need its connection and connection structures hold little data anyway. The opposite is true, though it is possible to delete a transaction but leave its connection alive.
Parameters
[in] conn
Definition at line 73 of file htp_connection.c.
References htp_conn_t::client_addr, htp_list_destroy, htp_list_get, htp_list_size, htp_tx_destroy_incomplete(), htp_conn_t::messages, htp_log_t::msg, htp_conn_t::server_addr, and htp_conn_t::transactions.
Referenced by htp_connp_destroy_all().
htp_status_t htp_conn_open (htp_conn_t * conn, const char * remote_addr, int remote_port, const char * local_addr, int local_port, const htp_time_t * timestamp)
Opens a connection. This function will essentially only store the provided data for future reference. The timestamp parameter is optional.
Parameters
[in] conn
[in] remote_addr
[in] remote_port
[in] local_addr
[in] local_port
[in] timestamp
Returns
Definition at line 115 of file htp_connection.c.
References htp_conn_t::client_addr, htp_conn_t::client_port, HTP_ERROR, HTP_OK, htp_conn_t::open_timestamp, htp_conn_t::server_addr, and htp_conn_t::server_port.
Referenced by htp_connp_open().
htp_status_t htp_conn_remove_tx (htp_conn_t * conn, const htp_tx_t * tx)
Removes the given transaction structure, which makes it possible to safely destroy it. It is safe to destroy transactions in this way because the index of the transactions (in a connection) is preserved.
Parameters
[in] conn
[in] tx
Returns
HTP_OK if transaction was removed (replaced with NULL) or HTP_ERROR if it wasn't found.
Definition at line 148 of file htp_connection.c.
References HTP_ERROR, htp_list_replace, htp_tx_t::index, and htp_conn_t::transactions.
Referenced by htp_tx_destroy_incomplete().
void htp_conn_track_inbound_data (htp_conn_t * conn, size_t len, const htp_time_t * timestamp)
Keeps track of inbound packets and data.
Parameters
[in] conn
[in] len
[in] timestamp
Definition at line 155 of file htp_connection.c.
References htp_conn_t::in_data_counter, and len.
Referenced by htp_connp_req_data().
void htp_conn_track_outbound_data (htp_conn_t * conn, size_t len, const htp_time_t * timestamp)
Keeps track of outbound packets and data.
Parameters
[in] conn
[in] len
[in] timestamp
Definition at line 160 of file htp_connection.c.
References len, and htp_conn_t::out_data_counter.
Referenced by htp_connp_res_data().