suricata: libhtp/htp/htp_transcoder.c File Reference
htp_transcoder.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Functions
int htp_transcode_params (htp_connp_t *connp, htp_table_t **params, int destroy_old)
int htp_transcode_bstr (iconv_t cd, bstr *input, bstr **output)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_transcoder.c.
Function Documentation
int htp_transcode_bstr (iconv_t cd, bstr * input, bstr ** output)
Transcode one bstr.
Parameters
[in] cd
[in] input
[in] output
Definition at line 143 of file htp_transcoder.c.
References bstr_builder_append_mem(), bstr_builder_create(), bstr_builder_destroy(), bstr_builder_to_str(), bstr_dup_mem(), bstr_len, bstr_ptr, HTP_ERROR, and HTP_OK.
Referenced by htp_transcode_params().
int htp_transcode_params (htp_connp_t * connp, htp_table_t ** params, int destroy_old)
Transcode all parameters supplied in the table.
Parameters
[in] connp
[in] params
[in] destroy_old
Definition at line 50 of file htp_transcoder.c.
References bstr_free(), htp_connp_t::cfg, HTP_ERROR, HTP_OK, htp_table_addn(), htp_table_create(), htp_table_destroy(), htp_table_get_index(), htp_table_size(), htp_transcode_bstr(), htp_cfg_t::internal_encoding, and htp_cfg_t::request_encoding.