suricata: libhtp/htp/htp_connection_parser.h File Reference
htp_connection_parser.h File Reference
Functions
void htp_connp_clear_error (htp_connp_t *connp)
void htp_connp_close (htp_connp_t *connp, const htp_time_t *timestamp)
htp_connp_t * htp_connp_create (htp_cfg_t *cfg)
void htp_connp_destroy (htp_connp_t *connp)
void htp_connp_destroy_all (htp_connp_t *connp)
htp_conn_t * htp_connp_get_connection (const htp_connp_t *connp)
htp_tx_t * htp_connp_get_in_tx (const htp_connp_t *connp)
htp_log_t * htp_connp_get_last_error (const htp_connp_t *connp)
htp_tx_t * htp_connp_get_out_tx (const htp_connp_t *connp)
void * htp_connp_get_user_data (const htp_connp_t *connp)
void htp_connp_open (htp_connp_t *connp, const char *client_addr, int client_port, const char *server_addr, int server_port, htp_time_t *timestamp)
void htp_connp_set_user_data (htp_connp_t *connp, const void *user_data)
int htp_connp_req_data (htp_connp_t *connp, const htp_time_t *timestamp, const void *data, size_t len)
size_t htp_connp_req_data_consumed (htp_connp_t *connp)
int htp_connp_res_data (htp_connp_t *connp, const htp_time_t *timestamp, const void *data, size_t len)
size_t htp_connp_res_data_consumed (htp_connp_t *connp)
htp_tx_t * htp_connp_tx_create (htp_connp_t *connp)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_connection_parser.h.
Function Documentation
void htp_connp_clear_error (htp_connp_t * connp)
Clears the most recent error, if any.
Parameters
[in] connp
Definition at line 43 of file htp_connection_parser.c.
References htp_connp_t::last_error.
void htp_connp_close (htp_connp_t * connp, const htp_time_t * timestamp)
Closes the connection associated with the supplied parser.
Parameters
[in] connp
[in] timestamp Optional.
Definition at line 47 of file htp_connection_parser.c.
References htp_connp_t::conn, htp_conn_close(), htp_connp_req_data(), htp_connp_res_data(), HTP_STREAM_CLOSED, HTP_STREAM_ERROR, htp_connp_t::in_status, and htp_connp_t::out_status.
htp_connp_t* htp_connp_create (htp_cfg_t * cfg)
Creates a new connection parser using the provided configuration. Because the configuration structure is used directly, in a multithreaded environment you are not allowed to change the structure, ever. If you have a need to change configuration on per-connection basis, make a copy of the configuration structure to go along with every connection parser.
Parameters
[in] cfg
Returns
New connection parser instance, or NULL on error.
Definition at line 65 of file htp_connection_parser.c.
References htp_connp_t::cfg, htp_connp_t::conn, htp_conn_create(), htp_connp_REQ_IDLE(), htp_connp_RES_IDLE(), HTP_STREAM_NEW, htp_connp_t::in_state, htp_connp_t::in_status, htp_connp_t::out_state, and htp_connp_t::out_status.
void htp_connp_destroy (htp_connp_t * connp)
Destroys the connection parser and its data structures, leaving all the data (connection, transactions, etc) intact.
Parameters
[in] connp
Definition at line 90 of file htp_connection_parser.c.
References bstr_free(), htp_decompressor_t::destroy, htp_file_t::filename, htp_connp_t::in_buf, htp_connp_t::out_buf, htp_connp_t::out_decompressor, and htp_connp_t::put_file.
Referenced by htp_connp_destroy_all().
void htp_connp_destroy_all (htp_connp_t * connp)
Destroys the connection parser, its data structures, as well as the connection and its transactions.
Parameters
[in] connp
Definition at line 114 of file htp_connection_parser.c.
References htp_connp_t::conn, htp_conn_destroy(), and htp_connp_destroy().
Referenced by HTPStateFree().
htp_conn_t* htp_connp_get_connection (const htp_connp_t * connp)
Returns the connection associated with the connection parser.
Parameters
[in] connp
Returns
htp_conn_t instance, or NULL if one is not available.
Definition at line 125 of file htp_connection_parser.c.
References htp_connp_t::conn.
htp_tx_t* htp_connp_get_in_tx (const htp_connp_t * connp)
Retrieves the pointer to the active inbound transaction. In connection parsing mode there can be many open transactions, and up to 2 active transactions at any one time. This is due to HTTP pipelining. Can be NULL.
Parameters
[in] connp
Returns
Active inbound transaction, or NULL if there isn't one.
Definition at line 130 of file htp_connection_parser.c.
References htp_connp_t::in_tx.
htp_log_t* htp_connp_get_last_error (const htp_connp_t * connp)
Returns the last error that occurred with this connection parser. Do note, however, that the value in this field will only be valid immediately after an error condition, but it is not guaranteed to remain valid if the parser is invoked again.
Parameters
[in] connp
Returns
A pointer to an htp_log_t instance if there is an error, or NULL if there isn't.
Definition at line 135 of file htp_connection_parser.c.
References htp_connp_t::last_error.
htp_tx_t* htp_connp_get_out_tx (const htp_connp_t * connp)
Retrieves the pointer to the active outbound transaction. In connection parsing mode there can be many open transactions, and up to 2 active transactions at any one time. This is due to HTTP pipelining. Can be NULL.
Parameters
[in] connp
Returns
Active outbound transaction, or NULL if there isn't one.
Definition at line 140 of file htp_connection_parser.c.
References htp_connp_t::out_tx.
void* htp_connp_get_user_data (const htp_connp_t * connp)
Retrieve the user data associated with this connection parser.
Parameters
[in] connp
Returns
User data, or NULL if there isn't any.
Definition at line 145 of file htp_connection_parser.c.
References htp_connp_t::user_data.
Referenced by HTPCallbackRequestBodyData(), and HTPCallbackResponseBodyData().
void htp_connp_open (htp_connp_t * connp, const char * client_addr, int client_port, const char * server_addr, int server_port, htp_time_t * timestamp)
Opens connection.
Parameters
[in] connp
[in] client_addr Client address
[in] client_port Client port
[in] server_addr Server address
[in] server_port Server port
[in] timestamp Optional.
Definition at line 157 of file htp_connection_parser.c.
References htp_connp_t::conn, htp_conn_open(), htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, HTP_STREAM_NEW, HTP_STREAM_OPEN, htp_connp_t::in_status, and htp_connp_t::out_status.
int htp_connp_req_data (htp_connp_t * connp, const htp_time_t * timestamp, const void * data, size_t len)
Parameters
[in] connp
[in] timestamp
[in] data
[in] len
Returns
HTP_STREAM_DATA, HTP_STREAM_ERROR or STEAM_STATE_DATA_OTHER (see QUICK_START). HTP_STREAM_CLOSED and HTP_STREAM_TUNNEL are also possible.
Definition at line 848 of file htp_request.c.
References htp_connp_t::conn, fprint_raw_data(), htp_conn_track_inbound_data(), htp_connp_in_state_as_string(), htp_connp_REQ_IDLE(), HTP_DATA, HTP_DATA_BUFFER, HTP_DATA_OTHER, htp_log(), HTP_LOG_ERROR, HTP_LOG_INFO, HTP_LOG_MARK, HTP_OK, HTP_STOP, HTP_STREAM_CLOSED, HTP_STREAM_DATA, HTP_STREAM_DATA_OTHER, HTP_STREAM_ERROR, HTP_STREAM_STOP, HTP_STREAM_TUNNEL, htp_tx_request_progress_as_string(), htp_connp_t::in_chunk_count, htp_connp_t::in_current_consume_offset, htp_connp_t::in_current_data, htp_connp_t::in_current_len, htp_connp_t::in_current_read_offset, htp_connp_t::in_current_receiver_offset, htp_connp_t::in_state, htp_connp_t::in_status, htp_connp_t::in_timestamp, htp_connp_t::in_tx, len, and htp_connp_t::out_status.
Referenced by htp_connp_close().
size_t htp_connp_req_data_consumed (htp_connp_t * connp)
Returns the number of bytes consumed from the most recent inbound data chunk. Normally, an invocation of htp_connp_req_data() will consume all data from the supplied buffer, but there are circumstances where only partial consumption is possible. In such cases HTP_STREAM_DATA_OTHER will be returned. Consumed bytes are no longer necessary, but the remainder of the buffer will be need to be saved for later.
Parameters
[in] connp
Returns
The number of bytes consumed from the last data chunk sent for inbound processing.
Returns how many bytes from the current data chunks were consumed so far.
Parameters
[in] connp
Returns
The number of bytes consumed.
Definition at line 844 of file htp_request.c.
References htp_connp_t::in_current_read_offset.
int htp_connp_res_data (htp_connp_t * connp, const htp_time_t * timestamp, const void * data, size_t len)
Process a chunk of outbound (server or response) data.
Parameters
[in] connp
[in] timestamp Optional.
[in] data
[in] len
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed
Definition at line 906 of file htp_response.c.
References htp_connp_t::conn, fprint_raw_data(), htp_conn_track_outbound_data(), htp_connp_out_state_as_string(), htp_connp_RES_IDLE(), HTP_DATA, HTP_DATA_BUFFER, HTP_DATA_OTHER, htp_log(), HTP_LOG_ERROR, HTP_LOG_INFO, HTP_LOG_MARK, HTP_OK, HTP_STOP, HTP_STREAM_CLOSED, HTP_STREAM_DATA, HTP_STREAM_DATA_OTHER, HTP_STREAM_ERROR, HTP_STREAM_STOP, HTP_STREAM_TUNNEL, htp_tx_response_progress_as_string(), len, htp_connp_t::out_current_consume_offset, htp_connp_t::out_current_data, htp_connp_t::out_current_len, htp_connp_t::out_current_read_offset, htp_connp_t::out_current_receiver_offset, htp_connp_t::out_state, htp_connp_t::out_status, htp_connp_t::out_timestamp, and htp_connp_t::out_tx.
Referenced by htp_connp_close().
size_t htp_connp_res_data_consumed (htp_connp_t * connp)
Returns the number of bytes consumed from the most recent outbound data chunk. Normally, an invocation of htp_connp_res_data() will consume all data from the supplied buffer, but there are circumstances where only partial consumption is possible. In such cases HTP_STREAM_DATA_OTHER will be returned. Consumed bytes are no longer necessary, but the remainder of the buffer will be need to be saved for later.
Parameters
[in] connp
Returns
The number of bytes consumed from the last data chunk sent for outbound processing.
Definition at line 860 of file htp_response.c.
References htp_connp_t::out_current_read_offset.
void htp_connp_set_user_data (htp_connp_t * connp, const void * user_data)
Associate user data with the supplied parser.
Parameters
[in] connp
[in] user_data
Definition at line 176 of file htp_connection_parser.c.
References htp_connp_t::user_data.
htp_tx_t* htp_connp_tx_create (htp_connp_t * connp)
Create a new transaction using the connection parser provided.
Parameters
[in] connp
Returns
Transaction instance on success, NULL on failure.
Definition at line 181 of file htp_connection_parser.c.
References htp_connp_t::conn, htp_conn_t::flags, HTP_CONN_PIPELINED, htp_connp_in_reset(), htp_list_size, htp_tx_create(), htp_connp_t::in_tx, htp_connp_t::out_next_tx_index, and htp_conn_t::transactions.
Referenced by htp_connp_REQ_IDLE().