suricata: libhtp/htp/htp_response_generic.c File Reference
htp_response_generic.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Functions
htp_status_t htp_parse_response_line_generic (htp_connp_t *connp)
htp_status_t htp_parse_response_header_generic (htp_connp_t *connp, htp_header_t *h, unsigned char *data, size_t len)
htp_status_t htp_process_response_header_generic (htp_connp_t *connp, unsigned char *data, size_t len)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_response_generic.c.
Function Documentation
htp_status_t htp_parse_response_header_generic (htp_connp_t * connp, htp_header_t * h, unsigned char * data, size_t len)
Generic response header parser.
Parameters
[in] connp
[in] h
[in] data
[in] len
Returns
HTP status
Definition at line 124 of file htp_response_generic.c.
References bstr_dup_mem(), bstr_free(), htp_header_t::flags, htp_tx_t::flags, htp_chomp(), HTP_ERROR, HTP_FIELD_INVALID, HTP_FIELD_UNPARSEABLE, htp_is_lws(), htp_is_token(), htp_log(), HTP_LOG_MARK, HTP_LOG_WARNING, HTP_OK, len, htp_header_t::name, htp_connp_t::out_tx, and htp_header_t::value.
Referenced by htp_process_response_header_generic().
htp_status_t htp_parse_response_line_generic (htp_connp_t * connp)
Generic response line parser.
Parameters
[in] connp
Returns
HTP status
Definition at line 49 of file htp_response_generic.c.
References bstr_dup_mem(), bstr_len, bstr_ptr, data, fprint_raw_data(), HTP_ERROR, htp_is_space(), HTP_OK, htp_parse_protocol(), htp_parse_status(), HTP_PROTOCOL_INVALID, HTP_STATUS_INVALID, len, htp_connp_t::out_tx, htp_tx_t::response_line, htp_tx_t::response_message, htp_tx_t::response_protocol, htp_tx_t::response_protocol_number, htp_tx_t::response_status, and htp_tx_t::response_status_number.
Referenced by htp_config_set_server_personality().
htp_status_t htp_process_response_header_generic (htp_connp_t * connp, unsigned char * data, size_t len)
Generic response header line(s) processor, which assembles folded lines into a single buffer before invoking the parsing function.
Parameters
[in] connp
[in] data
[in] len
Returns
HTP status
Definition at line 239 of file htp_response_generic.c.
References bstr_add_mem_noex(), bstr_add_noex(), bstr_cmp_c_nocase(), bstr_expand(), bstr_free(), bstr_len, htp_header_t::flags, fprint_bstr(), HTP_ERROR, HTP_FIELD_REPEATED, htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, htp_parse_content_length(), htp_parse_response_header_generic(), htp_table_add(), htp_table_get(), htp_header_t::name, htp_connp_t::out_tx, htp_tx_t::response_headers, and htp_header_t::value.
Referenced by htp_config_set_server_personality().