suricata: libhtp/htp/htp_private.h File Reference
htp_private.h File Reference
#include <ctype.h>
#include <errno.h>
#include <iconv.h>
#include <inttypes.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "htp.h"
#include "htp_config_private.h"
#include "htp_connection_parser_private.h"
#include "htp_connection_private.h"
#include "htp_list_private.h"
#include "htp_multipart_private.h"
#include "htp_table_private.h"
Macros
#define CR '\r'
#define LF '\n'
#define HTP_FIELD_LIMIT_HARD 18000
#define HTP_FIELD_LIMIT_SOFT 9000
#define HTP_VALID_STATUS_MIN 100
#define HTP_VALID_STATUS_MAX 999
Functions
htp_status_t htp_connp_REQ_IDLE (htp_connp_t *connp)
htp_status_t htp_connp_REQ_LINE (htp_connp_t *connp)
htp_status_t htp_connp_REQ_LINE_complete (htp_connp_t *connp)
htp_status_t htp_connp_REQ_PROTOCOL (htp_connp_t *connp)
htp_status_t htp_connp_REQ_HEADERS (htp_connp_t *connp)
htp_status_t htp_connp_REQ_CONNECT_CHECK (htp_connp_t *connp)
htp_status_t htp_connp_REQ_CONNECT_WAIT_RESPONSE (htp_connp_t *connp)
htp_status_t htp_connp_REQ_CONNECT_PROBE_DATA (htp_connp_t *connp)
htp_status_t htp_connp_REQ_BODY_DETERMINE (htp_connp_t *connp)
htp_status_t htp_connp_REQ_BODY_IDENTITY (htp_connp_t *connp)
htp_status_t htp_connp_REQ_BODY_CHUNKED_LENGTH (htp_connp_t *connp)
htp_status_t htp_connp_REQ_BODY_CHUNKED_DATA (htp_connp_t *connp)
htp_status_t htp_connp_REQ_BODY_CHUNKED_DATA_END (htp_connp_t *connp)
htp_status_t htp_connp_REQ_FINALIZE (htp_connp_t *connp)
htp_status_t htp_connp_REQ_IGNORE_DATA_AFTER_HTTP_0_9 (htp_connp_t *connp)
htp_status_t htp_connp_RES_IDLE (htp_connp_t *connp)
htp_status_t htp_connp_RES_LINE (htp_connp_t *connp)
htp_status_t htp_connp_RES_HEADERS (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_DETERMINE (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_IDENTITY_CL_KNOWN (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_CHUNKED_LENGTH (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_CHUNKED_DATA (htp_connp_t *connp)
htp_status_t htp_connp_RES_BODY_CHUNKED_DATA_END (htp_connp_t *connp)
htp_status_t htp_connp_RES_FINALIZE (htp_connp_t *connp)
htp_status_t htp_parse_request_line_generic (htp_connp_t *connp)
htp_status_t htp_parse_request_line_generic_ex (htp_connp_t *connp, int nul_terminates)
htp_status_t htp_parse_request_header_generic (htp_connp_t *connp, htp_header_t *h, unsigned char *data, size_t len)
htp_status_t htp_process_request_header_generic (htp_connp_t *, unsigned char *data, size_t len)
htp_status_t htp_parse_request_line_apache_2_2 (htp_connp_t *connp)
htp_status_t htp_process_request_header_apache_2_2 (htp_connp_t *, unsigned char *data, size_t len)
htp_status_t htp_parse_response_line_generic (htp_connp_t *connp)
htp_status_t htp_parse_response_header_generic (htp_connp_t *connp, htp_header_t *h, unsigned char *data, size_t len)
htp_status_t htp_process_response_header_generic (htp_connp_t *connp, unsigned char *data, size_t len)
htp_status_t htp_tx_state_response_complete_ex (htp_tx_t *tx, int hybrid_mode)
int htp_convert_method_to_number (bstr *)
int htp_is_lws (int c)
int htp_is_separator (int c)
int htp_is_text (int c)
int htp_is_token (int c)
int htp_chomp (unsigned char *data, size_t *len)
int htp_is_space (int c)
int htp_parse_protocol (bstr *protocol)
int htp_is_line_empty (unsigned char *data, size_t len)
int htp_is_line_whitespace (unsigned char *data, size_t len)
int htp_connp_is_line_folded (unsigned char *data, size_t len)
int htp_is_folding_char (int c)
int htp_connp_is_line_terminator (htp_connp_t *connp, unsigned char *data, size_t len)
int htp_connp_is_line_ignorable (htp_connp_t *connp, unsigned char *data, size_t len)
int htp_parse_uri (bstr *input, htp_uri_t **uri)
htp_status_t htp_parse_hostport (bstr *authority, bstr **hostname, bstr **port, int *port_number, int *invalid)
htp_status_t htp_parse_header_hostport (bstr *authority, bstr **hostname, bstr **port, int *port_number, uint64_t *flags)
int htp_validate_hostname (bstr *hostname)
int htp_parse_uri_hostport (htp_connp_t *connp, bstr *input, htp_uri_t *uri)
int htp_normalize_parsed_uri (htp_tx_t *tx, htp_uri_t *parsed_uri_incomplete, htp_uri_t *parsed_uri)
bstr * htp_normalize_hostname_inplace (bstr *input)
void htp_replace_hostname (htp_connp_t *connp, htp_uri_t *parsed_uri, bstr *hostname)
int htp_is_uri_unreserved (unsigned char c)
int htp_decode_path_inplace (htp_tx_t *tx, bstr *path)
int htp_prenormalize_uri_path_inplace (bstr *s, int *flags, int case_insensitive, int backslash, int decode_separators, int remove_consecutive)
void htp_normalize_uri_path_inplace (bstr *s)
void htp_utf8_decode_path_inplace (htp_cfg_t *cfg, htp_tx_t *tx, bstr *path)
void htp_utf8_validate_path (htp_tx_t *tx, bstr *path)
int64_t htp_parse_content_length (bstr *b)
int64_t htp_parse_chunked_length (unsigned char *data, size_t len)
int64_t htp_parse_positive_integer_whitespace (unsigned char *data, size_t len, int base)
int htp_parse_status (bstr *status)
int htp_parse_authorization_digest (htp_connp_t *connp, htp_header_t *auth_header)
int htp_parse_authorization_basic (htp_connp_t *connp, htp_header_t *auth_header)
void htp_print_log (FILE *stream, htp_log_t *log)
void fprint_bstr (FILE *stream, const char *name, bstr *b)
void fprint_raw_data (FILE *stream, const char *name, const void *data, size_t len)
void fprint_raw_data_ex (FILE *stream, const char *name, const void *data, size_t offset, size_t len)
char * htp_connp_in_state_as_string (htp_connp_t *connp)
char * htp_connp_out_state_as_string (htp_connp_t *connp)
char * htp_tx_request_progress_as_string (htp_tx_t *tx)
char * htp_tx_response_progress_as_string (htp_tx_t *tx)
bstr * htp_unparse_uri_noencode (htp_uri_t *uri)
int htp_treat_response_line_as_body (htp_tx_t *tx)
htp_status_t htp_req_run_hook_body_data (htp_connp_t *connp, htp_tx_data_t *d)
htp_status_t htp_res_run_hook_body_data (htp_connp_t *connp, htp_tx_data_t *d)
htp_status_t htp_ch_urlencoded_callback_request_body_data (htp_tx_data_t *d)
htp_status_t htp_ch_urlencoded_callback_request_headers (htp_tx_t *tx)
htp_status_t htp_ch_urlencoded_callback_request_line (htp_tx_t *tx)
htp_status_t htp_ch_multipart_callback_request_body_data (htp_tx_data_t *d)
htp_status_t htp_ch_multipart_callback_request_headers (htp_tx_t *tx)
htp_status_t htp_php_parameter_processor (htp_param_t *p)
int htp_transcode_params (htp_connp_t *connp, htp_table_t **params, int destroy_old)
int htp_transcode_bstr (iconv_t cd, bstr *input, bstr **output)
int htp_parse_single_cookie_v0 (htp_connp_t *connp, unsigned char *data, size_t len)
int htp_parse_cookies_v0 (htp_connp_t *connp)
int htp_parse_authorization (htp_connp_t *connp)
htp_status_t htp_extract_quoted_string_as_bstr (unsigned char *data, size_t len, bstr **out, size_t *endoffset)
htp_header_t * htp_connp_header_parse (htp_connp_t *, unsigned char *, size_t)
htp_status_t htp_parse_ct_header (bstr *header, bstr **ct)
htp_status_t htp_connp_req_receiver_finalize_clear (htp_connp_t *connp)
htp_status_t htp_connp_res_receiver_finalize_clear (htp_connp_t *connp)
htp_status_t htp_tx_finalize (htp_tx_t *tx)
int htp_tx_is_complete (htp_tx_t *tx)
htp_status_t htp_tx_state_request_complete_partial (htp_tx_t *tx)
void htp_connp_tx_remove (htp_connp_t *connp, htp_tx_t *tx)
void htp_tx_destroy_incomplete (htp_tx_t *tx)
htp_status_t htp_tx_req_process_body_data_ex (htp_tx_t *tx, const void *data, size_t len)
htp_status_t htp_tx_res_process_body_data_ex (htp_tx_t *tx, const void *data, size_t len)
htp_status_t htp_tx_urldecode_uri_inplace (htp_tx_t *tx, bstr *input)
htp_status_t htp_tx_urldecode_params_inplace (htp_tx_t *tx, bstr *input)
size_t strlcat (char *dst, const char *src, size_t size)
size_t strlcpy (char *dst, const char *src, size_t size)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_private.h.
Macro Definition Documentation
#define CR '\r'
Definition at line 72 of file htp_private.h.
#define HTP_FIELD_LIMIT_HARD 18000
Definition at line 79 of file htp_private.h.
Referenced by htp_config_create().
#define HTP_FIELD_LIMIT_SOFT 9000
Definition at line 80 of file htp_private.h.
Referenced by htp_config_create().
#define HTP_VALID_STATUS_MAX 999
Definition at line 83 of file htp_private.h.
Referenced by htp_tx_state_response_line().
#define HTP_VALID_STATUS_MIN 100
Definition at line 82 of file htp_private.h.
Referenced by htp_tx_state_response_line().
#define LF '\n'
Definition at line 76 of file htp_private.h.
Function Documentation
void fprint_bstr (FILE * stream, const char * name, bstr * b)
Definition at line 2039 of file htp_util.c.
References bstr_len, bstr_ptr, and fprint_raw_data_ex().
Referenced by htp_mpartp_find_boundary(), htp_process_request_header_generic(), and htp_process_response_header_generic().
void fprint_raw_data (FILE * stream, const char * name, const void * data, size_t len)
Definition at line 2051 of file htp_util.c.
References fprint_raw_data_ex().
Referenced by htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_req_data(), htp_connp_REQ_HEADERS(), htp_connp_REQ_LINE_complete(), htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_res_data(), htp_connp_RES_HEADERS(), htp_connp_RES_LINE(), htp_mpart_part_handle_data(), htp_mpartp_parse(), htp_parse_request_line_generic_ex(), htp_parse_response_line_generic(), and htp_tx_res_process_body_data_ex().
void fprint_raw_data_ex (FILE * stream, const char * name, const void * data, size_t offset, size_t len)
Definition at line 2058 of file htp_util.c.
References strlcat().
Referenced by fprint_bstr(), and fprint_raw_data().
htp_status_t htp_ch_multipart_callback_request_body_data (htp_tx_data_t * d)
Finalize Multipart processing.
Parameters
[in] d
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 193 of file htp_content_handlers.c.
References htp_tx_data_t::data, htp_mpartp_t::gave_up_data, HTP_ERROR, htp_list_get, htp_list_size, htp_mpartp_finalize(), htp_mpartp_get_multipart(), htp_mpartp_parse(), HTP_OK, HTP_PARSER_MULTIPART, HTP_SOURCE_BODY, htp_tx_req_add_param(), htp_tx_data_t::len, MULTIPART_PART_TEXT, htp_param_t::name, htp_multipart_part_t::name, htp_param_t::parser_data, htp_param_t::parser_id, htp_multipart_t::parts, htp_tx_t::request_mpartp, htp_param_t::source, htp_tx_data_t::tx, htp_multipart_part_t::type, htp_param_t::value, and htp_multipart_part_t::value.
Referenced by htp_ch_multipart_callback_request_headers().
htp_status_t htp_ch_multipart_callback_request_headers (htp_tx_t * tx)
Inspect request headers and register the Multipart request data hook if it contains a multipart/form-data body.
Parameters
[in] connp
Returns
HTP_OK if a new parser has been setup, HTP_DECLINED if the MIME type is not appropriate for this parser, and HTP_ERROR on failure.
Definition at line 244 of file htp_content_handlers.c.
References bstr_free(), htp_connp_t::cfg, htp_tx_t::cfg, htp_tx_t::connp, htp_mpartp_t::extract_dir, htp_mpartp_t::extract_files, htp_cfg_t::extract_request_files, flags, htp_ch_multipart_callback_request_body_data(), HTP_DECLINED, HTP_ERROR, htp_mpartp_create(), htp_mpartp_find_boundary(), HTP_OK, htp_table_get_c(), htp_tx_register_request_body_data(), htp_tx_t::request_content_type, htp_tx_t::request_headers, htp_tx_t::request_mpartp, htp_cfg_t::tmpdir, and htp_header_t::value.
Referenced by htp_config_register_multipart_parser().
htp_status_t htp_ch_urlencoded_callback_request_body_data (htp_tx_data_t * d)
This callback function feeds request body data to a Urlencoded parser and, later, feeds the parsed parameters to the correct structures.
Parameters
[in] d
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 50 of file htp_content_handlers.c.
References htp_tx_data_t::data, HTP_ERROR, HTP_OK, HTP_PARSER_URLENCODED, HTP_SOURCE_BODY, htp_table_destroy_ex(), htp_table_get_index(), htp_table_size(), htp_tx_req_add_param(), htp_urlenp_finalize(), htp_urlenp_parse_partial(), htp_tx_data_t::len, htp_param_t::name, htp_urlenp_t::params, htp_param_t::parser_data, htp_param_t::parser_id, htp_tx_t::request_urlenp_body, htp_param_t::source, htp_tx_data_t::tx, and htp_param_t::value.
Referenced by htp_ch_urlencoded_callback_request_headers().
htp_status_t htp_ch_urlencoded_callback_request_headers (htp_tx_t * tx)
Determine if the request has a Urlencoded body, and, if it does, create and attach an instance of the Urlencoded parser to the transaction.
Parameters
[in] connp
Returns
HTP_OK if a new parser has been setup, HTP_DECLINED if the MIME type is not appropriate for this parser, and HTP_ERROR on failure.
Definition at line 103 of file htp_content_handlers.c.
References bstr_begins_with_c(), htp_ch_urlencoded_callback_request_body_data(), HTP_DECLINED, HTP_ERROR, HTP_OK, htp_tx_register_request_body_data(), HTP_URLENCODED_MIME_TYPE, htp_urlenp_create(), htp_tx_t::request_content_type, and htp_tx_t::request_urlenp_body.
Referenced by htp_config_register_urlencoded_parser().
htp_status_t htp_ch_urlencoded_callback_request_line (htp_tx_t * tx)
Parses request query string, if present.
Parameters
[in] connp
[in] raw_data
[in] raw_len
Returns
HTP_OK if query string was parsed, HTP_DECLINED if there was no query string, and HTP_ERROR on failure.
Definition at line 136 of file htp_content_handlers.c.
References bstr_len, bstr_ptr, HTP_DECLINED, HTP_ERROR, HTP_OK, HTP_PARSER_URLENCODED, HTP_SOURCE_QUERY_STRING, htp_table_destroy_ex(), htp_table_get_index(), htp_table_size(), htp_tx_req_add_param(), htp_urlenp_create(), htp_urlenp_destroy(), htp_urlenp_parse_complete(), htp_param_t::name, htp_urlenp_t::params, htp_tx_t::parsed_uri, htp_param_t::parser_data, htp_param_t::parser_id, htp_uri_t::query, htp_tx_t::request_urlenp_query, htp_param_t::source, and htp_param_t::value.
Referenced by htp_config_register_urlencoded_parser().
int htp_chomp (unsigned char * data, size_t * len)
Remove all line terminators (LF or CRLF) from the end of the line provided as input.
Returns
0 if nothing was removed, 1 if one or more LF characters were removed, or 2 if one or more CR and/or LF characters were removed.
Definition at line 125 of file htp_util.c.
References CR, and LF.
Referenced by htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_REQ_HEADERS(), htp_connp_REQ_LINE_complete(), htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_RES_HEADERS(), htp_connp_RES_LINE(), htp_parse_request_header_generic(), and htp_parse_response_header_generic().
htp_header_t* htp_connp_header_parse (htp_connp_t * , unsigned char * , size_t)
char* htp_connp_in_state_as_string (htp_connp_t * connp)
Definition at line 2125 of file htp_util.c.
References htp_connp_REQ_BODY_CHUNKED_DATA(), htp_connp_REQ_BODY_CHUNKED_DATA_END(), htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_REQ_BODY_DETERMINE(), htp_connp_REQ_BODY_IDENTITY(), htp_connp_REQ_CONNECT_CHECK(), htp_connp_REQ_CONNECT_WAIT_RESPONSE(), htp_connp_REQ_FINALIZE(), htp_connp_REQ_HEADERS(), htp_connp_REQ_IDLE(), htp_connp_REQ_IGNORE_DATA_AFTER_HTTP_0_9(), htp_connp_REQ_LINE(), htp_connp_REQ_PROTOCOL(), and htp_connp_t::in_state.
Referenced by htp_connp_req_data().
int htp_connp_is_line_folded (unsigned char * data, size_t len)
Determines if the given line is a continuation (of some previous line).
Parameters
[in] data
[in] len
Returns
0 or 1 for false and true, respectively. Returns -1 on error (NULL pointer or length zero).
Definition at line 397 of file htp_util.c.
References htp_is_folding_char().
Referenced by htp_connp_REQ_HEADERS(), and htp_connp_RES_HEADERS().
int htp_connp_is_line_ignorable (htp_connp_t * connp, unsigned char * data, size_t len)
Determines if the given line can be ignored when it appears before a request.
Parameters
[in] connp
[in] data
[in] len
Returns
0 or 1
Definition at line 444 of file htp_util.c.
References htp_connp_is_line_terminator().
Referenced by htp_connp_REQ_LINE_complete(), and htp_connp_RES_LINE().
int htp_connp_is_line_terminator (htp_connp_t * connp, unsigned char * data, size_t len)
Determines if the given line is a request terminator.
Parameters
[in] connp
[in] data
[in] len
Returns
0 or 1
Definition at line 415 of file htp_util.c.
References htp_connp_t::cfg, htp_is_line_empty(), htp_is_line_whitespace(), HTP_SERVER_IIS_5_1, and htp_cfg_t::server_personality.
Referenced by htp_connp_is_line_ignorable(), htp_connp_REQ_HEADERS(), and htp_connp_RES_HEADERS().
char* htp_connp_out_state_as_string (htp_connp_t * connp)
Definition at line 2148 of file htp_util.c.
References htp_connp_RES_BODY_CHUNKED_DATA(), htp_connp_RES_BODY_CHUNKED_DATA_END(), htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_BODY_IDENTITY_CL_KNOWN(), htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE(), htp_connp_RES_FINALIZE(), htp_connp_RES_HEADERS(), htp_connp_RES_IDLE(), htp_connp_RES_LINE(), and htp_connp_t::out_state.
Referenced by htp_connp_res_data().
htp_status_t htp_connp_REQ_BODY_CHUNKED_DATA (htp_connp_t * connp)
Processes a chunk of data.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 437 of file htp_request.c.
References htp_connp_REQ_BODY_CHUNKED_DATA_END(), HTP_DATA, HTP_OK, htp_tx_req_process_body_data_ex(), htp_connp_t::in_chunked_length, htp_connp_t::in_current_consume_offset, htp_connp_t::in_current_data, htp_connp_t::in_current_len, htp_connp_t::in_current_read_offset, htp_connp_t::in_state, htp_connp_t::in_stream_offset, htp_connp_t::in_tx, and htp_tx_t::request_message_len.
Referenced by htp_connp_in_state_as_string(), and htp_connp_REQ_BODY_CHUNKED_LENGTH().
htp_status_t htp_connp_REQ_BODY_CHUNKED_DATA_END (htp_connp_t * connp)
Consumes bytes until the end of the current line.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 413 of file htp_request.c.
References htp_connp_REQ_BODY_CHUNKED_LENGTH(), HTP_ERROR, HTP_OK, htp_connp_t::in_next_byte, IN_NEXT_BYTE_OR_RETURN, htp_connp_t::in_state, htp_connp_t::in_tx, LF, and htp_tx_t::request_message_len.
Referenced by htp_connp_in_state_as_string(), and htp_connp_REQ_BODY_CHUNKED_DATA().
htp_status_t htp_connp_REQ_BODY_CHUNKED_LENGTH (htp_connp_t * connp)
Extracts chunk length.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 482 of file htp_request.c.
References data, fprint_raw_data(), htp_chomp(), htp_connp_REQ_BODY_CHUNKED_DATA(), htp_connp_REQ_HEADERS(), HTP_ERROR, htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, htp_parse_chunked_length(), HTP_REQUEST_TRAILER, htp_connp_t::in_chunked_length, IN_COPY_BYTE_OR_RETURN, htp_connp_t::in_next_byte, htp_connp_t::in_state, htp_connp_t::in_tx, len, LF, htp_tx_t::request_message_len, and htp_tx_t::request_progress.
Referenced by htp_connp_in_state_as_string(), htp_connp_REQ_BODY_CHUNKED_DATA_END(), and htp_connp_REQ_BODY_DETERMINE().
htp_status_t htp_connp_REQ_BODY_DETERMINE (htp_connp_t * connp)
Determines presence (and encoding) of a request body.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 573 of file htp_request.c.
References htp_tx_t::connp, HTP_CODING_CHUNKED, HTP_CODING_IDENTITY, HTP_CODING_NO_BODY, htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_REQ_BODY_IDENTITY(), htp_connp_REQ_FINALIZE(), HTP_ERROR, HTP_OK, HTP_REQUEST_BODY, htp_connp_t::in_body_data_left, htp_connp_t::in_content_length, htp_connp_t::in_state, htp_connp_t::in_tx, htp_tx_t::request_content_length, htp_tx_t::request_progress, and htp_tx_t::request_transfer_coding.
Referenced by htp_connp_in_state_as_string(), and htp_connp_REQ_CONNECT_CHECK().
htp_status_t htp_connp_REQ_BODY_IDENTITY (htp_connp_t * connp)
Processes identity request body.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 534 of file htp_request.c.
References htp_connp_REQ_FINALIZE(), HTP_DATA, HTP_OK, htp_tx_req_process_body_data_ex(), htp_connp_t::in_body_data_left, htp_connp_t::in_current_consume_offset, htp_connp_t::in_current_data, htp_connp_t::in_current_len, htp_connp_t::in_current_read_offset, htp_connp_t::in_state, htp_connp_t::in_stream_offset, htp_connp_t::in_tx, and htp_tx_t::request_message_len.
Referenced by htp_connp_in_state_as_string(), and htp_connp_REQ_BODY_DETERMINE().
htp_status_t htp_connp_REQ_CONNECT_CHECK (htp_connp_t * connp)
Performs a check for a CONNECT transaction to decide whether inbound parsing needs to be suspended.
Parameters
[in] connp
Returns
HTP_OK if the request does not use CONNECT, HTP_DATA_OTHER if inbound parsing needs to be suspended until we hear from the other side
Definition at line 291 of file htp_request.c.
References htp_connp_REQ_BODY_DETERMINE(), htp_connp_REQ_CONNECT_WAIT_RESPONSE(), HTP_DATA_OTHER, HTP_M_CONNECT, HTP_OK, HTP_STREAM_DATA_OTHER, htp_connp_t::in_state, htp_connp_t::in_status, htp_connp_t::in_tx, and htp_tx_t::request_method_number.
Referenced by htp_connp_in_state_as_string(), and htp_tx_state_request_headers().
htp_status_t htp_connp_REQ_CONNECT_PROBE_DATA (htp_connp_t * connp)
Determines whether inbound parsing needs to continue or stop. In case the data appears to be plain text HTTP, we try to continue.
Parameters
[in] connp
Returns
HTP_OK if the parser can resume parsing, HTP_DATA_BUFFER if we need more data.
Definition at line 317 of file htp_request.c.
References bstr_dup_mem(), bstr_free(), data, fprint_raw_data(), htp_connp_REQ_IDLE(), htp_convert_method_to_number(), HTP_ERROR, htp_is_space(), HTP_M_UNKNOWN, HTP_OK, HTP_STREAM_TUNNEL, IN_COPY_BYTE_OR_RETURN, htp_connp_t::in_next_byte, IN_PEEK_NEXT, htp_connp_t::in_state, htp_connp_t::in_status, len, LF, and htp_connp_t::out_status.
Referenced by htp_connp_REQ_CONNECT_WAIT_RESPONSE().
htp_status_t htp_connp_REQ_CONNECT_WAIT_RESPONSE (htp_connp_t * connp)
Determines whether inbound parsing, which was suspended after encountering a CONNECT transaction, can proceed (after receiving the response).
Parameters
[in] connp
Returns
HTP_OK if the parser can resume parsing, HTP_DATA_OTHER if it needs to continue waiting.
Definition at line 384 of file htp_request.c.
References htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_REQ_FINALIZE(), HTP_DATA_OTHER, HTP_OK, HTP_RESPONSE_LINE, htp_connp_t::in_state, htp_connp_t::in_tx, htp_tx_t::response_progress, and htp_tx_t::response_status_number.
Referenced by htp_connp_in_state_as_string(), and htp_connp_REQ_CONNECT_CHECK().
htp_status_t htp_connp_REQ_FINALIZE (htp_connp_t * connp)
Definition at line 794 of file htp_request.c.
References htp_tx_state_request_complete(), and htp_connp_t::in_tx.
Referenced by htp_connp_in_state_as_string(), htp_connp_REQ_BODY_DETERMINE(), htp_connp_REQ_BODY_IDENTITY(), htp_connp_REQ_CONNECT_WAIT_RESPONSE(), htp_connp_REQ_PROTOCOL(), and htp_tx_state_request_headers().
htp_status_t htp_connp_REQ_HEADERS (htp_connp_t * connp)
Parses request headers.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 616 of file htp_request.c.
References bstr_add_mem(), bstr_dup_mem(), bstr_free(), bstr_len, bstr_ptr, htp_connp_t::cfg, data, htp_tx_t::flags, fprint_raw_data(), htp_chomp(), htp_connp_is_line_folded(), htp_connp_is_line_terminator(), HTP_ERROR, HTP_INVALID_FOLDING, htp_is_folding_char(), htp_log(), HTP_LOG_MARK, HTP_LOG_WARNING, HTP_OK, htp_tx_state_request_headers(), IN_COPY_BYTE_OR_RETURN, htp_connp_t::in_header, htp_connp_t::in_next_byte, IN_PEEK_NEXT, htp_connp_t::in_tx, len, LF, and htp_cfg_t::process_request_header.
Referenced by htp_connp_in_state_as_string(), htp_connp_REQ_BODY_CHUNKED_LENGTH(), and htp_connp_REQ_PROTOCOL().
htp_status_t htp_connp_REQ_IDLE (htp_connp_t * connp)
The idle state is where the parser will end up after a transaction is processed. If there is more data available, a new request will be started.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 821 of file htp_request.c.
References htp_connp_tx_create(), HTP_ERROR, HTP_OK, htp_tx_state_request_start(), IN_TEST_NEXT_BYTE_OR_RETURN, and htp_connp_t::in_tx.
Referenced by htp_connp_create(), htp_connp_in_state_as_string(), htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_req_data(), and htp_tx_state_request_complete().
htp_status_t htp_connp_REQ_IGNORE_DATA_AFTER_HTTP_0_9 (htp_connp_t * connp)
Definition at line 798 of file htp_request.c.
References htp_connp_t::conn, htp_conn_t::flags, HTP_CONN_HTTP_0_9_EXTRA, HTP_DATA, htp_connp_t::in_current_consume_offset, htp_connp_t::in_current_len, htp_connp_t::in_current_read_offset, and htp_connp_t::in_stream_offset.
Referenced by htp_connp_in_state_as_string(), and htp_tx_state_request_complete().
htp_status_t htp_connp_REQ_LINE (htp_connp_t * connp)
Parses request line.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 780 of file htp_request.c.
References htp_connp_REQ_LINE_complete(), HTP_ERROR, IN_COPY_BYTE_OR_RETURN, htp_connp_t::in_next_byte, and LF.
Referenced by htp_connp_in_state_as_string(), htp_tx_state_request_start(), and htp_tx_state_response_start().
htp_status_t htp_connp_REQ_LINE_complete (htp_connp_t * connp)
Parse the request line.
Parameters
[in] connp
Returns
HTP_OK on succesful parse, HTP_ERROR on error.
Definition at line 731 of file htp_request.c.
References bstr_dup_mem(), htp_connp_t::cfg, data, fprint_raw_data(), htp_chomp(), htp_connp_is_line_ignorable(), HTP_ERROR, HTP_OK, htp_tx_state_request_line(), htp_connp_t::in_tx, len, htp_cfg_t::parse_request_line, htp_tx_t::request_ignored_lines, and htp_tx_t::request_line.
Referenced by htp_connp_REQ_LINE(), and htp_tx_state_response_start().
htp_status_t htp_connp_REQ_PROTOCOL (htp_connp_t * connp)
Determines request protocol.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 710 of file htp_request.c.
References htp_connp_REQ_FINALIZE(), htp_connp_REQ_HEADERS(), HTP_OK, HTP_REQUEST_HEADERS, htp_connp_t::in_state, htp_connp_t::in_tx, htp_tx_t::is_protocol_0_9, and htp_tx_t::request_progress.
Referenced by htp_connp_in_state_as_string(), and htp_tx_state_request_line().
htp_status_t htp_connp_req_receiver_finalize_clear (htp_connp_t * connp)
Finalizes an existing data receiver hook by sending any outstanding data to it. The hook is then removed so that it receives no more data.
Parameters
[in] connp
Returns
HTP_OK, or a value returned from a callback.
Definition at line 131 of file htp_request.c.
References HTP_OK, and htp_connp_t::in_data_receiver_hook.
Referenced by htp_tx_state_request_headers().
htp_status_t htp_connp_RES_BODY_CHUNKED_DATA (htp_connp_t * connp)
Processes a chunk of data.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 312 of file htp_response.c.
References htp_connp_RES_BODY_CHUNKED_DATA_END(), HTP_DATA, HTP_OK, htp_tx_res_process_body_data_ex(), htp_connp_t::out_chunked_length, htp_connp_t::out_current_consume_offset, htp_connp_t::out_current_data, htp_connp_t::out_current_len, htp_connp_t::out_current_read_offset, htp_connp_t::out_state, htp_connp_t::out_stream_offset, and htp_connp_t::out_tx.
Referenced by htp_connp_out_state_as_string(), and htp_connp_RES_BODY_CHUNKED_LENGTH().
htp_status_t htp_connp_RES_BODY_CHUNKED_DATA_END (htp_connp_t * connp)
Consumes bytes until the end of the current line.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 287 of file htp_response.c.
References htp_connp_RES_BODY_CHUNKED_LENGTH(), HTP_ERROR, HTP_OK, LF, htp_connp_t::out_next_byte, OUT_NEXT_BYTE_OR_RETURN, htp_connp_t::out_state, htp_connp_t::out_tx, and htp_tx_t::response_message_len.
Referenced by htp_connp_out_state_as_string(), and htp_connp_RES_BODY_CHUNKED_DATA().
htp_status_t htp_connp_RES_BODY_CHUNKED_LENGTH (htp_connp_t * connp)
Extracts chunk length.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 349 of file htp_response.c.
References data, fprint_raw_data(), htp_chomp(), htp_connp_RES_BODY_CHUNKED_DATA(), htp_connp_RES_HEADERS(), HTP_ERROR, htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, htp_parse_chunked_length(), HTP_RESPONSE_TRAILER, len, LF, htp_connp_t::out_chunked_length, OUT_COPY_BYTE_OR_RETURN, htp_connp_t::out_next_byte, htp_connp_t::out_state, htp_connp_t::out_tx, htp_tx_t::response_message_len, and htp_tx_t::response_progress.
Referenced by htp_connp_out_state_as_string(), htp_connp_RES_BODY_CHUNKED_DATA_END(), and htp_connp_RES_BODY_DETERMINE().
htp_status_t htp_connp_RES_BODY_DETERMINE (htp_connp_t * connp)
Determines presence (and encoding) of a response body.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 469 of file htp_response.c.
References bstr_adjust_len(), bstr_cmp_c_nocase(), bstr_dup_lower(), bstr_free(), bstr_index_of_c_nocase(), bstr_len, bstr_ptr, htp_header_t::flags, htp_tx_t::flags, HTP_CODING_CHUNKED, HTP_CODING_IDENTITY, HTP_CODING_NO_BODY, htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_RES_BODY_IDENTITY_CL_KNOWN(), htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE(), htp_connp_RES_FINALIZE(), htp_connp_RES_LINE(), HTP_ERROR, HTP_FIELD_REPEATED, htp_is_space(), htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_M_CONNECT, HTP_M_HEAD, HTP_OK, htp_parse_content_length(), HTP_REQUEST_SMUGGLING, HTP_RESPONSE_BODY, HTP_RESPONSE_LINE, HTP_STREAM_DATA, htp_table_clear(), htp_table_get_c(), htp_table_get_index(), htp_table_size(), htp_tx_state_response_headers(), htp_connp_t::in_status, htp_header_t::name, htp_connp_t::out_body_data_left, htp_connp_t::out_content_length, htp_connp_t::out_data_other_at_tx_end, htp_connp_t::out_state, htp_connp_t::out_tx, htp_tx_t::request_method_number, htp_tx_t::response_content_length, htp_tx_t::response_content_type, htp_tx_t::response_headers, htp_tx_t::response_progress, htp_tx_t::response_status_number, htp_tx_t::response_transfer_coding, htp_tx_t::seen_100continue, and htp_header_t::value.
Referenced by htp_connp_out_state_as_string(), and htp_connp_RES_HEADERS().
htp_status_t htp_connp_RES_BODY_IDENTITY_CL_KNOWN (htp_connp_t * connp)
Processes an identity response body of known length.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 402 of file htp_response.c.
References htp_connp_RES_FINALIZE(), HTP_DATA, HTP_OK, htp_tx_res_process_body_data_ex(), htp_connp_t::out_body_data_left, htp_connp_t::out_current_consume_offset, htp_connp_t::out_current_data, htp_connp_t::out_current_len, htp_connp_t::out_current_read_offset, htp_connp_t::out_state, htp_connp_t::out_stream_offset, and htp_connp_t::out_tx.
Referenced by htp_connp_out_state_as_string(), and htp_connp_RES_BODY_DETERMINE().
htp_status_t htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE (htp_connp_t * connp)
Processes identity response body of unknown length. In this case, we assume the response body consumes all data until the end of the stream.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 440 of file htp_response.c.
References htp_connp_RES_FINALIZE(), HTP_DATA, HTP_OK, HTP_STREAM_CLOSED, htp_tx_res_process_body_data_ex(), htp_connp_t::out_current_consume_offset, htp_connp_t::out_current_data, htp_connp_t::out_current_len, htp_connp_t::out_current_read_offset, htp_connp_t::out_state, htp_connp_t::out_status, htp_connp_t::out_stream_offset, and htp_connp_t::out_tx.
Referenced by htp_connp_out_state_as_string(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_LINE(), and htp_tx_state_response_start().
htp_status_t htp_connp_RES_FINALIZE (htp_connp_t * connp)
Definition at line 864 of file htp_response.c.
References htp_tx_state_response_complete_ex(), and htp_connp_t::out_tx.
Referenced by htp_connp_out_state_as_string(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_BODY_IDENTITY_CL_KNOWN(), htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE(), and htp_connp_RES_HEADERS().
htp_status_t htp_connp_RES_HEADERS (htp_connp_t * connp)
Parses response headers.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 642 of file htp_response.c.
References bstr_add_mem(), bstr_dup_mem(), bstr_free(), bstr_len, bstr_ptr, htp_connp_t::cfg, data, htp_tx_t::flags, fprint_raw_data(), htp_cfg_t::hook_response_trailer, htp_chomp(), htp_connp_is_line_folded(), htp_connp_is_line_terminator(), htp_connp_RES_BODY_DETERMINE(), htp_connp_RES_FINALIZE(), htp_connp_res_receiver_finalize_clear(), HTP_ERROR, htp_hook_run_all(), HTP_INVALID_FOLDING, htp_is_folding_char(), htp_log(), HTP_LOG_MARK, HTP_LOG_WARNING, HTP_OK, HTP_RESPONSE_HEADERS, len, LF, OUT_COPY_BYTE_OR_RETURN, htp_connp_t::out_header, htp_connp_t::out_next_byte, OUT_PEEK_NEXT, htp_connp_t::out_state, htp_connp_t::out_tx, htp_cfg_t::process_response_header, and htp_tx_t::response_progress.
Referenced by htp_connp_out_state_as_string(), htp_connp_RES_BODY_CHUNKED_LENGTH(), and htp_connp_RES_LINE().
htp_status_t htp_connp_RES_IDLE (htp_connp_t * connp)
The response idle state will initialize response processing, as well as finalize each transactions after we are done with it.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 875 of file htp_response.c.
References htp_connp_t::conn, HTP_ERROR, htp_list_get, htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, htp_tx_state_response_start(), htp_connp_t::out_body_data_left, htp_connp_t::out_content_length, htp_connp_t::out_next_tx_index, OUT_TEST_NEXT_BYTE_OR_RETURN, htp_connp_t::out_tx, and htp_conn_t::transactions.
Referenced by htp_connp_create(), htp_connp_out_state_as_string(), htp_connp_res_data(), and htp_tx_state_response_complete_ex().
htp_status_t htp_connp_RES_LINE (htp_connp_t * connp)
Parses response line.
Parameters
[in] connp
Returns
HTP_OK on state change, HTP_ERROR on error, or HTP_DATA when more data is needed.
Definition at line 756 of file htp_response.c.
References bstr_dup_mem(), bstr_free(), htp_connp_t::cfg, data, fprint_raw_data(), htp_chomp(), HTP_CODING_IDENTITY, HTP_COMPRESSION_NONE, htp_connp_is_line_ignorable(), htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE(), htp_connp_RES_HEADERS(), HTP_ERROR, HTP_OK, HTP_RESPONSE_BODY, HTP_RESPONSE_HEADERS, HTP_STREAM_CLOSED, htp_treat_response_line_as_body(), htp_tx_res_process_body_data_ex(), htp_tx_state_response_line(), len, LF, htp_connp_t::out_body_data_left, OUT_COPY_BYTE_OR_RETURN, htp_connp_t::out_next_byte, htp_connp_t::out_state, htp_connp_t::out_status, htp_connp_t::out_tx, htp_cfg_t::parse_response_line, htp_tx_t::response_content_encoding_processing, htp_tx_t::response_ignored_lines, htp_tx_t::response_line, htp_tx_t::response_message, htp_tx_t::response_progress, htp_tx_t::response_protocol, htp_tx_t::response_status, and htp_tx_t::response_transfer_coding.
Referenced by htp_connp_out_state_as_string(), htp_connp_RES_BODY_DETERMINE(), and htp_tx_state_response_start().
htp_status_t htp_connp_res_receiver_finalize_clear (htp_connp_t * connp)
Finalizes an existing data receiver hook by sending any outstanding data to it. The hook is then removed so that it receives no more data.
Parameters
[in] connp
Returns
HTP_OK, or a value returned from a callback.
Definition at line 115 of file htp_response.c.
References HTP_OK, and htp_connp_t::out_data_receiver_hook.
Referenced by htp_connp_RES_HEADERS(), and htp_tx_state_response_headers().
void htp_connp_tx_remove (htp_connp_t * connp, htp_tx_t * tx)
Removes references to the supplied transaction.
Parameters
[in] connp
[in] tx
Definition at line 205 of file htp_connection_parser.c.
References htp_connp_t::in_tx, and htp_connp_t::out_tx.
Referenced by htp_tx_destroy_incomplete().
int htp_convert_method_to_number (bstr * method)
Converts request method, given as a string, into a number.
Parameters
[in] method
Returns
Method number of M_UNKNOWN
Definition at line 174 of file htp_util.c.
References bstr_cmp_c(), HTP_M_BASELINE_CONTROL, HTP_M_CHECKIN, HTP_M_CHECKOUT, HTP_M_CONNECT, HTP_M_COPY, HTP_M_DELETE, HTP_M_GET, HTP_M_HEAD, HTP_M_INVALID, HTP_M_LABEL, HTP_M_LOCK, HTP_M_MERGE, HTP_M_MKACTIVITY, HTP_M_MKCOL, HTP_M_MKWORKSPACE, HTP_M_MOVE, HTP_M_OPTIONS, HTP_M_PATCH, HTP_M_POST, HTP_M_PROPFIND, HTP_M_PROPPATCH, HTP_M_PUT, HTP_M_REPORT, HTP_M_TRACE, HTP_M_UNCHECKOUT, HTP_M_UNKNOWN, HTP_M_UNLOCK, HTP_M_UPDATE, and HTP_M_VERSION_CONTROL.
Referenced by htp_connp_REQ_CONNECT_PROBE_DATA(), and htp_parse_request_line_generic_ex().
int htp_decode_path_inplace (htp_tx_t * tx, bstr * path)
Decode a request path according to the settings in the provided configuration structure.
Parameters
[in] cfg
[in] tx
[in] path
Definition at line 1190 of file htp_util.c.
References htp_decoder_cfg_t::backslash_convert_slashes, bstr_adjust_len(), bstr_len, bstr_ptr, htp_tx_t::cfg, htp_decoder_cfg_t::control_chars_unwanted, htp_decoder_cfg_t::convert_lowercase, htp_cfg_t::decoder_cfgs, htp_tx_t::flags, HTP_DECODER_URL_PATH, HTP_ERROR, HTP_OK, HTP_PATH_ENCODED_NUL, HTP_PATH_ENCODED_SEPARATOR, HTP_PATH_INVALID_ENCODING, HTP_UNWANTED_IGNORE, HTP_URL_DECODE_PRESERVE_PERCENT, HTP_URL_DECODE_PROCESS_INVALID, HTP_URL_DECODE_REMOVE_PERCENT, htp_decoder_cfg_t::nul_encoded_terminates, htp_decoder_cfg_t::nul_encoded_unwanted, htp_decoder_cfg_t::nul_raw_terminates, htp_decoder_cfg_t::nul_raw_unwanted, htp_decoder_cfg_t::path_separators_compress, htp_decoder_cfg_t::path_separators_decode, htp_decoder_cfg_t::path_separators_encoded_unwanted, htp_tx_t::response_status_expected_number, htp_decoder_cfg_t::u_encoding_decode, htp_decoder_cfg_t::u_encoding_unwanted, htp_decoder_cfg_t::url_encoding_invalid_handling, and htp_decoder_cfg_t::url_encoding_invalid_unwanted.
Referenced by htp_normalize_parsed_uri().
htp_status_t htp_extract_quoted_string_as_bstr (unsigned char * data, size_t len, bstr ** out, size_t * endoffset)
Parses the provided memory region, extracting the double-quoted string.
Parameters
[in] data
[in] len
[out] out
[out] endoffset
Returns
HTP_OK on success, HTP_DECLINED if the input is not well formed, and HTP_ERROR on fatal errors.
Definition at line 2420 of file htp_util.c.
References bstr_adjust_len(), bstr_alloc(), bstr_ptr, HTP_DECLINED, HTP_ERROR, and HTP_OK.
Referenced by htp_parse_authorization_digest().
int htp_is_folding_char (int c)
Definition at line 402 of file htp_util.c.
References htp_is_lws().
Referenced by htp_connp_is_line_folded(), htp_connp_REQ_HEADERS(), and htp_connp_RES_HEADERS().
int htp_is_line_empty (unsigned char * data, size_t len)
Is the given line empty? This function expects the line to have a terminating LF.
Parameters
[in] data
[in] len
Returns
0 or 1
Definition at line 219 of file htp_util.c.
References CR.
Referenced by htp_connp_is_line_terminator().
int htp_is_line_whitespace (unsigned char * data, size_t len)
Does line consist entirely of whitespace characters?
Parameters
[in] data
[in] len
Returns
0 or 1
Definition at line 234 of file htp_util.c.
References len.
Referenced by htp_connp_is_line_terminator().
int htp_is_lws (int c)
Is character a linear white space character?
Parameters
[in] c
Returns
0 or 1
Definition at line 49 of file htp_util.c.
Referenced by htp_is_folding_char(), htp_mpartp_parse(), htp_mpartp_parse_header(), htp_parse_positive_integer_whitespace(), htp_parse_request_header_generic(), and htp_parse_response_header_generic().
int htp_is_separator (int c)
Is character a separator character?
Parameters
[in] c
Returns
0 or 1
Definition at line 60 of file htp_util.c.
Referenced by htp_is_token().
int htp_is_space (int c)
Is character a white space character?
Parameters
[in] c
Returns
0 or 1
Definition at line 154 of file htp_util.c.
Referenced by htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_RES_BODY_DETERMINE(), htp_mpartp_find_boundary(), htp_mpartp_parse_header(), htp_parse_request_line_generic_ex(), and htp_parse_response_line_generic().
int htp_is_text (int c)
Is character a text character?
Parameters
[in] c
Returns
0 or 1
Definition at line 98 of file htp_util.c.
int htp_is_token (int c)
Is character a token character?
Parameters
[in] c
Returns
0 or 1
Definition at line 110 of file htp_util.c.
References htp_is_separator().
Referenced by htp_mpartp_parse_header(), htp_parse_request_header_generic(), and htp_parse_response_header_generic().
int htp_is_uri_unreserved (unsigned char c)
bstr* htp_normalize_hostname_inplace (bstr * hostname)
Normalize request hostname. Convert all characters to lowercase and remove trailing dots from the end, if present.
Parameters
[in] hostname
Returns
Normalized hostname.
Definition at line 1793 of file htp_util.c.
References bstr_char_at_end(), bstr_chop(), and bstr_to_lowercase().
Referenced by htp_normalize_parsed_uri().
int htp_normalize_parsed_uri (htp_tx_t * tx, htp_uri_t * incomplete, htp_uri_t * normalized)
Normalize a previously-parsed request URI.
Parameters
[in] connp
[in] incomplete
[in] normalized
Returns
HTP_OK or HTP_ERROR
Definition at line 1694 of file htp_util.c.
References bstr_dup(), bstr_dup_lower(), bstr_len, bstr_ptr, htp_tx_t::cfg, htp_cfg_t::decoder_cfgs, htp_tx_t::flags, htp_uri_t::fragment, htp_uri_t::hostname, htp_decode_path_inplace(), HTP_DECODER_URL_PATH, HTP_ERROR, HTP_HOSTU_INVALID, htp_normalize_hostname_inplace(), htp_normalize_uri_path_inplace(), HTP_OK, htp_parse_positive_integer_whitespace(), htp_tx_urldecode_uri_inplace(), htp_utf8_decode_path_inplace(), htp_utf8_validate_path(), htp_uri_t::password, htp_uri_t::path, htp_uri_t::port, htp_uri_t::port_number, htp_uri_t::query, htp_uri_t::scheme, htp_uri_t::username, and htp_decoder_cfg_t::utf8_convert_bestfit.
Referenced by htp_tx_state_request_line().
void htp_normalize_uri_path_inplace (bstr * s)
Normalize URL path. This function implements the remove dot segments algorithm specified in RFC 3986, section 5.2.4.
Parameters
[in] s
Definition at line 1940 of file htp_util.c.
References bstr_adjust_len(), bstr_len, and bstr_ptr.
Referenced by htp_normalize_parsed_uri().
int htp_parse_authorization (htp_connp_t * connp)
Parses Authorization request header.
Parameters
[in] connp
Definition at line 163 of file htp_parsers.c.
References bstr_begins_with_c_nocase(), HTP_AUTH_BASIC, HTP_AUTH_DIGEST, HTP_AUTH_NONE, HTP_AUTH_UNRECOGNIZED, HTP_OK, htp_parse_authorization_basic(), htp_parse_authorization_digest(), htp_table_get_c(), htp_connp_t::in_tx, htp_tx_t::request_auth_type, htp_tx_t::request_headers, and htp_header_t::value.
int htp_parse_authorization_basic (htp_connp_t * connp, htp_header_t * auth_header)
Parses Basic Authorization request header.
Parameters
[in] connp
[in] auth_header
Definition at line 120 of file htp_parsers.c.
References bstr_dup_ex(), bstr_free(), bstr_index_of_c(), bstr_len, bstr_ptr, data, htp_base64_decode_mem(), HTP_DECLINED, HTP_ERROR, HTP_OK, htp_connp_t::in_tx, len, htp_tx_t::request_auth_password, htp_tx_t::request_auth_username, and htp_header_t::value.
Referenced by htp_parse_authorization().
int htp_parse_authorization_digest (htp_connp_t * connp, htp_header_t * auth_header)
Parses Digest Authorization request header.
Parameters
[in] connp
[in] auth_header
Definition at line 97 of file htp_parsers.c.
References bstr_index_of_c(), bstr_len, bstr_ptr, data, HTP_DECLINED, htp_extract_quoted_string_as_bstr(), htp_connp_t::in_tx, len, htp_tx_t::request_auth_username, and htp_header_t::value.
Referenced by htp_parse_authorization().
int64_t htp_parse_chunked_length (unsigned char * data, size_t len)
Parses chunk length (positive hexadecimal number). White space is allowed before and after the number. An error will be returned if the chunk length is greater than INT32_MAX.
Parameters
[in] data
[in] len
Returns
Chunk length, or a negative number on error.
Definition at line 266 of file htp_util.c.
References htp_parse_positive_integer_whitespace().
Referenced by htp_connp_REQ_BODY_CHUNKED_LENGTH(), and htp_connp_RES_BODY_CHUNKED_LENGTH().
int64_t htp_parse_content_length (bstr * b)
Parses Content-Length string (positive decimal number). White space is allowed before and after the number.
Parameters
[in] b
Returns
Content-Length as a number, or -1 on error.
Definition at line 253 of file htp_util.c.
References bstr_len, bstr_ptr, and htp_parse_positive_integer_whitespace().
Referenced by htp_connp_RES_BODY_DETERMINE(), and htp_process_response_header_generic().
int htp_parse_cookies_v0 (htp_connp_t * connp)
Parses the Cookie request header in v0 format.
Parameters
[in] connp
Returns
HTP_OK on success, HTP_ERROR on error
Definition at line 88 of file htp_cookies.c.
References bstr_len, bstr_ptr, data, HTP_ERROR, HTP_OK, htp_parse_single_cookie_v0(), htp_table_create(), htp_table_get_c(), htp_connp_t::in_tx, len, htp_tx_t::request_cookies, htp_tx_t::request_headers, and htp_header_t::value.
htp_status_t htp_parse_ct_header (bstr * header, bstr ** ct)
Definition at line 2486 of file htp_util.c.
References bstr_dup_ex(), bstr_len, bstr_ptr, bstr_to_lowercase(), HTP_ERROR, and HTP_OK.
htp_status_t htp_parse_header_hostport (bstr * hostport, bstr ** hostname, bstr ** port, int * port_number, uint64_t * flags)
Parses hostport provided in the Host header.
Parameters
[in] hostport
[out] hostname
[out] port
[out] port_number
[out] flags
Returns
HTP_OK on success or HTP_ERROR error.
Definition at line 613 of file htp_util.c.
References HTP_HOSTH_INVALID, HTP_OK, htp_parse_hostport(), and htp_validate_hostname().
htp_status_t htp_parse_hostport (bstr * hostport, bstr ** hostname, bstr ** port, int * port_number, int * invalid)
Parses an authority string, which consists of a hostname with an optional port number; username and password are not allowed and will not be handled.
Parameters
[in] hostport
[out] hostname A bstring containing the hostname, or NULL if the hostname is invalid. If this value is not NULL, the caller assumes responsibility for memory management.
[out] port Port as text, or NULL if not provided.
[out] port_number Port number, or -1 if the port is not present or invalid.
[out] invalid Set to 1 if any part of the authority is invalid.
Returns
HTP_OK on success, HTP_ERROR on memory allocation failure.
Definition at line 485 of file htp_util.c.
References bstr_dup_mem(), bstr_free(), bstr_len, bstr_ptr, bstr_to_lowercase(), bstr_util_mem_trim(), HTP_ERROR, and HTP_OK.
Referenced by htp_parse_header_hostport(), and htp_parse_uri_hostport().
int64_t htp_parse_positive_integer_whitespace (unsigned char * data, size_t len, int base)
A somewhat forgiving parser for a positive integer in a given base. Only LWS is allowed before and after the number.
Parameters
[in] data
[in] len
[in] base
Returns
The parsed number on success; a negative number on error.
Definition at line 282 of file htp_util.c.
References bstr_util_mem_to_pint(), and htp_is_lws().
Referenced by htp_normalize_parsed_uri(), htp_parse_chunked_length(), htp_parse_content_length(), and htp_parse_status().
int htp_parse_protocol (bstr * protocol)
Determines protocol number from a textual representation (i.e., "HTTP/1.1"). This function will only understand a properly formatted protocol information. It does not try to be flexible.
Parameters
[in] protocol
Returns
Protocol version or PROTOCOL_UNKNOWN.
Definition at line 51 of file htp_parsers.c.
References bstr_len, bstr_ptr, HTP_PROTOCOL_0_9, HTP_PROTOCOL_1_0, HTP_PROTOCOL_1_1, and HTP_PROTOCOL_INVALID.
Referenced by htp_parse_request_line_generic_ex(), and htp_parse_response_line_generic().
htp_status_t htp_parse_request_header_generic (htp_connp_t * connp, htp_header_t * h, unsigned char * data, size_t len)
Generic request header parser.
Parameters
[in] connp
[in] h
[in] data
[in] len
Returns
HTP_OK or HTP_ERROR
Definition at line 111 of file htp_request_generic.c.
References bstr_dup_c(), bstr_dup_mem(), bstr_free(), htp_header_t::flags, htp_tx_t::flags, htp_chomp(), HTP_ERROR, HTP_FIELD_INVALID, HTP_FIELD_UNPARSEABLE, htp_is_lws(), htp_is_token(), htp_log(), HTP_LOG_MARK, HTP_LOG_WARNING, HTP_OK, htp_connp_t::in_tx, htp_header_t::name, and htp_header_t::value.
Referenced by htp_process_request_header_generic().
htp_status_t htp_parse_request_line_apache_2_2 (htp_connp_t * connp)
Parse request line as Apache 2.2 does.
Parameters
[in] connp
Returns
HTP_OK or HTP_ERROR
Definition at line 62 of file htp_request_apache_2_2.c.
References htp_parse_request_line_generic_ex().
Referenced by htp_config_set_server_personality().
htp_status_t htp_parse_request_line_generic (htp_connp_t * connp)
Generic request line parser.
Parameters
[in] connp
Returns
HTP_OK or HTP_ERROR
Definition at line 247 of file htp_request_generic.c.
References htp_parse_request_line_generic_ex().
Referenced by htp_config_set_server_personality().
htp_status_t htp_parse_request_line_generic_ex (htp_connp_t * connp, int nul_terminates)
Definition at line 251 of file htp_request_generic.c.
References bstr_dup_mem(), bstr_len, bstr_ptr, htp_connp_t::cfg, data, fprint_raw_data(), htp_convert_method_to_number(), HTP_ERROR, htp_is_space(), htp_log(), HTP_LOG_MARK, HTP_LOG_WARNING, HTP_OK, htp_parse_protocol(), HTP_PROTOCOL_0_9, HTP_UNWANTED_IGNORE, htp_connp_t::in_tx, htp_tx_t::is_protocol_0_9, len, htp_tx_t::request_line, htp_tx_t::request_method, htp_tx_t::request_method_number, htp_tx_t::request_protocol, htp_tx_t::request_protocol_number, htp_tx_t::request_uri, htp_cfg_t::requestline_leading_whitespace_unwanted, and htp_tx_t::response_status_expected_number.
Referenced by htp_parse_request_line_apache_2_2(), and htp_parse_request_line_generic().
htp_status_t htp_parse_response_header_generic (htp_connp_t * connp, htp_header_t * h, unsigned char * data, size_t len)
Generic response header parser.
Parameters
[in] connp
[in] h
[in] data
[in] len
Returns
HTP status
Definition at line 124 of file htp_response_generic.c.
References bstr_dup_mem(), bstr_free(), htp_header_t::flags, htp_tx_t::flags, htp_chomp(), HTP_ERROR, HTP_FIELD_INVALID, HTP_FIELD_UNPARSEABLE, htp_is_lws(), htp_is_token(), htp_log(), HTP_LOG_MARK, HTP_LOG_WARNING, HTP_OK, len, htp_header_t::name, htp_connp_t::out_tx, and htp_header_t::value.
Referenced by htp_process_response_header_generic().
htp_status_t htp_parse_response_line_generic (htp_connp_t * connp)
Generic response line parser.
Parameters
[in] connp
Returns
HTP status
Definition at line 49 of file htp_response_generic.c.
References bstr_dup_mem(), bstr_len, bstr_ptr, data, fprint_raw_data(), HTP_ERROR, htp_is_space(), HTP_OK, htp_parse_protocol(), htp_parse_status(), HTP_PROTOCOL_INVALID, HTP_STATUS_INVALID, len, htp_connp_t::out_tx, htp_tx_t::response_line, htp_tx_t::response_message, htp_tx_t::response_protocol, htp_tx_t::response_protocol_number, htp_tx_t::response_status, and htp_tx_t::response_status_number.
Referenced by htp_config_set_server_personality().
int htp_parse_single_cookie_v0 (htp_connp_t * connp, unsigned char * data, size_t len)
Parses a single v0 request cookie and places the results into tx->request_cookies.
Parameters
[in] connp
[in] data
[in] len
Returns
HTP_OK on success, HTP_ERROR on error.
Definition at line 51 of file htp_cookies.c.
References bstr_dup_c(), bstr_dup_mem(), bstr_free(), HTP_ERROR, HTP_OK, htp_table_addn(), htp_connp_t::in_tx, and htp_tx_t::request_cookies.
Referenced by htp_parse_cookies_v0().
int htp_parse_status (bstr * status)
Determines the numerical value of a response status given as a string.
Parameters
[in] status
Returns
Status code on success, or -1 on error.
Definition at line 87 of file htp_parsers.c.
References bstr_len, bstr_ptr, and htp_parse_positive_integer_whitespace().
Referenced by htp_parse_response_line_generic().
int htp_parse_uri (bstr * input, htp_uri_t ** uri)
Parses request URI, making no attempt to validate the contents.
Parameters
[in] input
[in] uri
Returns
HTP_ERROR on memory allocation failure, HTP_OK otherwise
Definition at line 639 of file htp_util.c.
References bstr_dup_mem(), bstr_len, bstr_ptr, HTP_ERROR, HTP_OK, and m.
Referenced by htp_tx_state_request_line().
int htp_parse_uri_hostport (htp_connp_t * connp, bstr * hostport, htp_uri_t * uri)
Parses hostport provided in the URI.
Parameters
[in] connp
[in] hostport
[in] uri
Returns
HTP_OK on success or HTP_ERROR error.
Definition at line 584 of file htp_util.c.
References htp_tx_t::flags, htp_uri_t::hostname, HTP_HOSTU_INVALID, HTP_OK, htp_parse_hostport(), htp_validate_hostname(), htp_connp_t::in_tx, htp_uri_t::port, and htp_uri_t::port_number.
Referenced by htp_tx_state_request_line().
htp_status_t htp_php_parameter_processor (htp_param_t * p)
This is a proof-of-concept processor that processes parameter names in a way similar to PHP. Whitespace at the beginning is removed, and the remaining whitespace characters are converted to underscores. Proper research of PHP's behavior is needed before we can claim to be emulating it.
Parameters
[in,out] p
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 52 of file htp_php.c.
References bstr_dup(), bstr_dup_mem(), bstr_free(), bstr_len, bstr_ptr, data, HTP_ERROR, HTP_OK, len, and htp_param_t::name.
int htp_prenormalize_uri_path_inplace (bstr * s, int * flags, int case_insensitive, int backslash, int decode_separators, int remove_consecutive)
void htp_print_log (FILE * stream, htp_log_t * log)
htp_status_t htp_process_request_header_apache_2_2 (htp_connp_t * connp, unsigned char * data, size_t len)
Extract one request header. A header can span multiple lines, in which case they will be folded into one before parsing is attempted.
Parameters
[in] connp
[in] data
[in] len
Returns
HTP_OK or HTP_ERROR
Definition at line 52 of file htp_request_apache_2_2.c.
References htp_process_request_header_generic().
Referenced by htp_config_set_server_personality().
htp_status_t htp_process_request_header_generic (htp_connp_t * connp, unsigned char * data, size_t len)
Extract one request header. A header can span multiple lines, in which case they will be folded into one before parsing is attempted.
Parameters
[in] connp
[in] data
[in] len
Returns
HTP_OK or HTP_ERROR
Definition at line 52 of file htp_request_generic.c.
References bstr_add_mem_noex(), bstr_add_noex(), bstr_expand(), bstr_free(), bstr_len, htp_header_t::flags, fprint_bstr(), HTP_ERROR, HTP_FIELD_REPEATED, HTP_OK, htp_parse_request_header_generic(), htp_table_add(), htp_table_get(), htp_connp_t::in_tx, htp_header_t::name, htp_tx_t::request_headers, and htp_header_t::value.
Referenced by htp_config_set_server_personality(), and htp_process_request_header_apache_2_2().
htp_status_t htp_process_response_header_generic (htp_connp_t * connp, unsigned char * data, size_t len)
Generic response header line(s) processor, which assembles folded lines into a single buffer before invoking the parsing function.
Parameters
[in] connp
[in] data
[in] len
Returns
HTP status
Definition at line 239 of file htp_response_generic.c.
References bstr_add_mem_noex(), bstr_add_noex(), bstr_cmp_c_nocase(), bstr_expand(), bstr_free(), bstr_len, htp_header_t::flags, fprint_bstr(), HTP_ERROR, HTP_FIELD_REPEATED, htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, htp_parse_content_length(), htp_parse_response_header_generic(), htp_table_add(), htp_table_get(), htp_header_t::name, htp_connp_t::out_tx, htp_tx_t::response_headers, and htp_header_t::value.
Referenced by htp_config_set_server_personality().
void htp_replace_hostname (htp_connp_t * connp, htp_uri_t * parsed_uri, bstr * hostname)
htp_status_t htp_req_run_hook_body_data (htp_connp_t * connp, htp_tx_data_t * d)
Run the REQUEST_BODY_DATA hook.
Parameters
[in] connp
[in] d
Definition at line 2359 of file htp_util.c.
References htp_connp_t::cfg, htp_file_data_t::data, htp_tx_data_t::data, htp_file_data_t::file, htp_cfg_t::hook_request_body_data, htp_tx_t::hook_request_body_data, htp_cfg_t::hook_request_file_data, htp_hook_run_all(), HTP_OK, htp_connp_t::in_tx, htp_file_t::len, htp_file_data_t::len, htp_tx_data_t::len, and htp_connp_t::put_file.
Referenced by htp_tx_req_process_body_data_ex().
htp_status_t htp_res_run_hook_body_data (htp_connp_t * connp, htp_tx_data_t * d)
Run the RESPONSE_BODY_DATA hook.
Parameters
[in] connp
[in] d
Definition at line 2396 of file htp_util.c.
References htp_connp_t::cfg, htp_tx_data_t::data, htp_cfg_t::hook_response_body_data, htp_tx_t::hook_response_body_data, htp_hook_run_all(), HTP_OK, htp_tx_data_t::len, and htp_connp_t::out_tx.
Referenced by htp_tx_res_process_body_data_ex().
int htp_transcode_bstr (iconv_t cd, bstr * input, bstr ** output)
Transcode one bstr.
Parameters
[in] cd
[in] input
[in] output
Definition at line 143 of file htp_transcoder.c.
References bstr_builder_append_mem(), bstr_builder_create(), bstr_builder_destroy(), bstr_builder_to_str(), bstr_dup_mem(), bstr_len, bstr_ptr, HTP_ERROR, and HTP_OK.
Referenced by htp_transcode_params().
int htp_transcode_params (htp_connp_t * connp, htp_table_t ** params, int destroy_old)
Transcode all parameters supplied in the table.
Parameters
[in] connp
[in] params
[in] destroy_old
Definition at line 50 of file htp_transcoder.c.
References bstr_free(), htp_connp_t::cfg, HTP_ERROR, HTP_OK, htp_table_addn(), htp_table_create(), htp_table_destroy(), htp_table_get_index(), htp_table_size(), htp_transcode_bstr(), htp_cfg_t::internal_encoding, and htp_cfg_t::request_encoding.
int htp_treat_response_line_as_body (htp_tx_t * tx)
Determine if the information provided on the response line is good enough. Browsers are lax when it comes to response line parsing. In most cases they will only look for the words "http" at the beginning.
Parameters
[in] tx
Returns
1 for good enough or 0 for not good enough
Definition at line 2334 of file htp_util.c.
References bstr_len, bstr_ptr, and htp_tx_t::response_protocol.
Referenced by htp_connp_RES_LINE().
void htp_tx_destroy_incomplete (htp_tx_t * tx)
Definition at line 118 of file htp_transaction.c.
References bstr_free(), htp_tx_t::cfg, htp_tx_t::conn, htp_tx_t::connp, htp_tx_t::hook_request_body_data, htp_config_destroy(), HTP_CONFIG_PRIVATE, htp_conn_remove_tx(), htp_connp_tx_remove(), htp_hook_destroy(), htp_mpartp_destroy(), htp_table_destroy(), htp_table_get_index(), htp_table_size(), htp_uri_free(), htp_urlenp_destroy(), htp_tx_t::is_config_shared, htp_header_t::name, htp_param_t::name, htp_tx_t::parsed_uri, htp_tx_t::parsed_uri_raw, htp_tx_t::request_auth_password, htp_tx_t::request_auth_username, htp_tx_t::request_content_type, htp_tx_t::request_cookies, htp_tx_t::request_headers, htp_tx_t::request_hostname, htp_tx_t::request_line, htp_tx_t::request_method, htp_tx_t::request_mpartp, htp_tx_t::request_params, htp_tx_t::request_protocol, htp_tx_t::request_uri, htp_tx_t::request_urlenp_body, htp_tx_t::request_urlenp_query, htp_tx_t::response_content_type, htp_tx_t::response_headers, htp_tx_t::response_line, htp_tx_t::response_message, htp_tx_t::response_protocol, htp_tx_t::response_status, htp_header_t::value, and htp_param_t::value.
Referenced by htp_conn_destroy(), htp_tx_create(), and htp_tx_destroy().
htp_status_t htp_tx_finalize (htp_tx_t * tx)
Definition at line 998 of file htp_transaction.c.
References htp_connp_t::cfg, htp_tx_t::connp, htp_cfg_t::hook_transaction_complete, HTP_ERROR, htp_hook_run_all(), HTP_OK, htp_tx_destroy(), htp_tx_is_complete(), and htp_cfg_t::tx_auto_destroy.
Referenced by htp_tx_state_request_complete(), and htp_tx_state_response_complete_ex().
int htp_tx_is_complete (htp_tx_t * tx)
Definition at line 1195 of file htp_transaction.c.
References HTP_REQUEST_COMPLETE, HTP_RESPONSE_COMPLETE, htp_tx_t::request_progress, and htp_tx_t::response_progress.
Referenced by htp_tx_destroy(), and htp_tx_finalize().
htp_status_t htp_tx_req_process_body_data_ex (htp_tx_t * tx, const void * data, size_t len)
Definition at line 571 of file htp_transaction.c.
References htp_tx_t::connp, htp_tx_data_t::data, HTP_ERROR, htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, htp_req_run_hook_body_data(), len, htp_tx_data_t::len, htp_tx_t::request_entity_len, and htp_tx_data_t::tx.
Referenced by htp_connp_REQ_BODY_CHUNKED_DATA(), htp_connp_REQ_BODY_IDENTITY(), htp_tx_req_process_body_data(), and htp_tx_state_request_complete_partial().
char* htp_tx_request_progress_as_string (htp_tx_t * tx)
Definition at line 2168 of file htp_util.c.
References HTP_REQUEST_BODY, HTP_REQUEST_COMPLETE, HTP_REQUEST_HEADERS, HTP_REQUEST_LINE, HTP_REQUEST_NOT_STARTED, HTP_REQUEST_TRAILER, and htp_tx_t::request_progress.
Referenced by htp_connp_req_data().
htp_status_t htp_tx_res_process_body_data_ex (htp_tx_t * tx, const void * data, size_t len)
Definition at line 775 of file htp_transaction.c.
References htp_tx_t::connp, htp_tx_data_t::data, htp_decompressor_t::decompress, htp_decompressor_t::destroy, fprint_raw_data(), HTP_COMPRESSION_DEFLATE, HTP_COMPRESSION_GZIP, HTP_COMPRESSION_NONE, HTP_ERROR, htp_log(), HTP_LOG_ERROR, HTP_LOG_MARK, HTP_OK, htp_res_run_hook_body_data(), htp_tx_data_t::is_last, len, htp_tx_data_t::len, htp_connp_t::out_decompressor, htp_tx_t::response_content_encoding_processing, htp_tx_t::response_entity_len, htp_tx_t::response_message_len, and htp_tx_data_t::tx.
Referenced by htp_connp_RES_BODY_CHUNKED_DATA(), htp_connp_RES_BODY_IDENTITY_CL_KNOWN(), htp_connp_RES_BODY_IDENTITY_STREAM_CLOSE(), htp_connp_RES_LINE(), htp_tx_res_process_body_data(), and htp_tx_state_response_complete_ex().
char* htp_tx_response_progress_as_string (htp_tx_t * tx)
Definition at line 2192 of file htp_util.c.
References HTP_RESPONSE_BODY, HTP_RESPONSE_COMPLETE, HTP_RESPONSE_HEADERS, HTP_RESPONSE_LINE, HTP_RESPONSE_NOT_STARTED, HTP_RESPONSE_TRAILER, and htp_tx_t::response_progress.
Referenced by htp_connp_res_data().
htp_status_t htp_tx_state_request_complete_partial (htp_tx_t * tx)
Definition at line 833 of file htp_transaction.c.
References bstr_free(), htp_connp_t::cfg, htp_tx_t::connp, htp_file_t::filename, htp_cfg_t::hook_request_complete, HTP_ERROR, htp_hook_run_all(), HTP_OK, HTP_REQUEST_COMPLETE, htp_tx_req_has_body(), htp_tx_req_process_body_data_ex(), htp_connp_t::put_file, and htp_tx_t::request_progress.
Referenced by htp_tx_state_request_complete().
htp_status_t htp_tx_state_response_complete_ex (htp_tx_t * tx, int hybrid_mode)
Definition at line 1015 of file htp_transaction.c.
References htp_connp_t::cfg, htp_tx_t::connp, htp_cfg_t::hook_response_complete, HTP_CODING_NO_BODY, htp_connp_RES_IDLE(), HTP_DATA_OTHER, HTP_ERROR, htp_hook_run_all(), HTP_OK, HTP_RESPONSE_COMPLETE, HTP_STREAM_DATA_OTHER, htp_tx_finalize(), htp_tx_res_process_body_data_ex(), htp_connp_t::in_status, htp_connp_t::in_tx, htp_connp_t::out_data_other_at_tx_end, htp_connp_t::out_state, htp_connp_t::out_tx, htp_tx_t::response_progress, and htp_tx_t::response_transfer_coding.
Referenced by htp_connp_RES_FINALIZE(), and htp_tx_state_response_complete().
htp_status_t htp_tx_urldecode_params_inplace (htp_tx_t * tx, bstr * input)
Definition at line 1474 of file htp_util.c.
References htp_tx_t::cfg, htp_tx_t::flags, HTP_DECODER_URLENCODED, htp_urldecode_inplace_ex(), and htp_tx_t::response_status_expected_number.
htp_status_t htp_tx_urldecode_uri_inplace (htp_tx_t * tx, bstr * input)
Definition at line 1454 of file htp_util.c.
References htp_tx_t::cfg, htp_tx_t::flags, HTP_DECODER_URL_PATH, HTP_PATH_ENCODED_NUL, HTP_PATH_INVALID_ENCODING, HTP_PATH_RAW_NUL, htp_urldecode_inplace_ex(), HTP_URLEN_ENCODED_NUL, HTP_URLEN_INVALID_ENCODING, HTP_URLEN_RAW_NUL, and htp_tx_t::response_status_expected_number.
Referenced by htp_normalize_parsed_uri().
bstr* htp_unparse_uri_noencode (htp_uri_t * uri)
Definition at line 2213 of file htp_util.c.
References bstr_add_c_noex(), bstr_add_noex(), bstr_alloc(), bstr_len, htp_uri_t::fragment, htp_uri_t::hostname, htp_uri_t::password, htp_uri_t::path, htp_uri_t::port, htp_uri_t::query, htp_uri_t::scheme, and htp_uri_t::username.
void htp_utf8_decode_path_inplace (htp_cfg_t * cfg, htp_tx_t * tx, bstr * path)
Decode a UTF-8 encoded path. Overlong characters will be decoded, invalid characters will be left as-is. Best-fit mapping will be used to convert UTF-8 into a single-byte stream.
Parameters
[in] cfg
[in] tx
[in] path
Definition at line 887 of file htp_util.c.
References htp_decoder_cfg_t::bestfit_replacement_byte, bstr_adjust_len(), bstr_len, bstr_ptr, htp_cfg_t::decoder_cfgs, htp_tx_t::flags, HTP_DECODER_URL_PATH, HTP_PATH_HALF_FULL_RANGE, HTP_PATH_UTF8_INVALID, HTP_PATH_UTF8_OVERLONG, HTP_PATH_UTF8_VALID, HTP_UNWANTED_IGNORE, HTP_UTF8_ACCEPT, htp_utf8_decode_allow_overlong(), HTP_UTF8_REJECT, htp_tx_t::response_status_expected_number, and htp_decoder_cfg_t::utf8_invalid_unwanted.
Referenced by htp_normalize_parsed_uri().
void htp_utf8_validate_path (htp_tx_t * tx, bstr * path)
Validate a path that is quite possibly UTF-8 encoded.
Parameters
[in] tx
[in] path
Definition at line 997 of file htp_util.c.
References bstr_len, bstr_ptr, htp_tx_t::flags, HTP_PATH_HALF_FULL_RANGE, HTP_PATH_UTF8_INVALID, HTP_PATH_UTF8_OVERLONG, HTP_PATH_UTF8_VALID, HTP_UTF8_ACCEPT, htp_utf8_decode_allow_overlong(), and HTP_UTF8_REJECT.
Referenced by htp_normalize_parsed_uri().
int htp_validate_hostname (bstr * hostname)
Implements relaxed (not strictly RFC) hostname validation.
Parameters
[in] hostname
Returns
1 if the supplied hostname is valid; 0 if it is not.
Definition at line 2515 of file htp_util.c.
References bstr_len, and bstr_ptr.
Referenced by htp_parse_header_hostport(), htp_parse_uri_hostport(), and htp_tx_state_request_line().
size_t strlcat (char * dst, const char * src, size_t size)
Definition at line 50 of file util-strlcatu.c.
size_t strlcpy (char * dst, const char * src, size_t size)
Definition at line 48 of file util-strlcpyu.c.