suricata: libhtp/htp/htp_multipart.c File Reference
htp_multipart.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Functions
htp_multipart_t * htp_mpartp_get_multipart (htp_mpartp_t *parser)
htp_status_t htp_mpart_part_parse_c_d (htp_multipart_part_t *part)
htp_status_t htp_mpart_part_process_headers (htp_multipart_part_t *part)
htp_status_t htp_mpartp_parse_header (htp_multipart_part_t *part, const unsigned char *data, size_t len)
htp_multipart_part_t * htp_mpart_part_create (htp_mpartp_t *parser)
void htp_mpart_part_destroy (htp_multipart_part_t *part, int gave_up_data)
htp_status_t htp_mpart_part_finalize_data (htp_multipart_part_t *part)
htp_status_t htp_mpartp_run_request_file_data_hook (htp_multipart_part_t *part, const unsigned char *data, size_t len)
htp_status_t htp_mpart_part_handle_data (htp_multipart_part_t *part, const unsigned char *data, size_t len, int is_line)
htp_mpartp_t * htp_mpartp_create (htp_cfg_t *cfg, bstr *boundary, uint64_t flags)
void htp_mpartp_destroy (htp_mpartp_t *parser)
htp_status_t htp_mpartp_finalize (htp_mpartp_t *parser)
htp_status_t htp_mpartp_parse (htp_mpartp_t *parser, const void *_data, size_t len)
htp_status_t htp_mpartp_find_boundary (bstr *content_type, bstr **boundary, uint64_t *flags)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_multipart.c.
Function Documentation
htp_multipart_part_t* htp_mpart_part_create (htp_mpartp_t * parser)
Creates a new Multipart part.
Parameters
[in] parser
Returns
New part instance, or NULL on memory allocation failure.
Definition at line 454 of file htp_multipart.c.
References bstr_builder_clear(), htp_multipart_part_t::headers, htp_table_create(), htp_multipart_part_t::parser, htp_mpartp_t::part_data_pieces, and htp_mpartp_t::part_header_pieces.
void htp_mpart_part_destroy (htp_multipart_part_t * part, int gave_up_data)
Destroys a part.
Parameters
[in] part
[in] gave_up_data
Definition at line 477 of file htp_multipart.c.
References bstr_free(), htp_multipart_part_t::content_type, htp_multipart_part_t::file, htp_file_t::filename, htp_multipart_part_t::headers, htp_table_destroy(), htp_table_get_index(), htp_table_size(), MULTIPART_PART_TEXT, htp_header_t::name, htp_multipart_part_t::name, htp_file_t::tmpname, htp_multipart_part_t::type, htp_header_t::value, and htp_multipart_part_t::value.
Referenced by htp_mpartp_destroy().
htp_status_t htp_mpart_part_finalize_data (htp_multipart_part_t * part)
Finalizes part processing.
Parameters
[in] part
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 520 of file htp_multipart.c.
References bstr_builder_clear(), bstr_builder_size(), bstr_builder_to_str(), htp_mpartp_t::current_part, htp_mpartp_t::current_part_mode, htp_file_t::fd, htp_multipart_part_t::file, htp_multipart_t::flags, htp_mpartp_run_request_file_data_hook(), HTP_MULTIPART_HAS_EPILOGUE, HTP_MULTIPART_PART_AFTER_LAST_BOUNDARY, HTP_MULTIPART_PART_INCOMPLETE, HTP_MULTIPART_PART_UNKNOWN, HTP_MULTIPART_SEEN_LAST_BOUNDARY, HTP_OK, MODE_DATA, htp_mpartp_t::multipart, MULTIPART_PART_EPILOGUE, MULTIPART_PART_FILE, MULTIPART_PART_UNKNOWN, htp_multipart_part_t::parser, htp_mpartp_t::part_data_pieces, htp_multipart_part_t::type, and htp_multipart_part_t::value.
Referenced by htp_mpartp_finalize().
htp_status_t htp_mpart_part_handle_data (htp_multipart_part_t * part, const unsigned char * data, size_t len, int is_line)
Handles part data.
Parameters
[in] part
[in] data
[in] len
[in] is_line
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 602 of file htp_multipart.c.
References bstr_add_mem(), bstr_builder_append_mem(), bstr_builder_clear(), bstr_builder_size(), bstr_builder_to_str(), bstr_dup_mem(), bstr_free(), bstr_len, bstr_ptr, CR, htp_mpartp_t::current_part_mode, htp_mpartp_t::extract_dir, htp_mpartp_t::extract_files, htp_mpartp_t::extract_limit, htp_file_t::fd, htp_multipart_part_t::file, htp_mpartp_t::file_count, htp_multipart_t::flags, fprint_raw_data(), HTP_ERROR, htp_mpart_part_process_headers(), htp_mpartp_parse_header(), htp_mpartp_run_request_file_data_hook(), HTP_MULTIPART_PART_HEADER_FOLDING, HTP_MULTIPART_SEEN_LAST_BOUNDARY, HTP_OK, len, htp_multipart_part_t::len, LF, MODE_DATA, MODE_LINE, htp_mpartp_t::multipart, MULTIPART_PART_EPILOGUE, MULTIPART_PART_FILE, MULTIPART_PART_PREAMBLE, MULTIPART_PART_TEXT, MULTIPART_PART_UNKNOWN, htp_multipart_part_t::name, htp_multipart_part_t::parser, htp_mpartp_t::part_data_pieces, htp_mpartp_t::part_header_pieces, htp_mpartp_t::pending_header_line, htp_file_t::tmpname, and htp_multipart_part_t::type.
htp_status_t htp_mpart_part_parse_c_d (htp_multipart_part_t * part)
Parses the Content-Disposition part header.
Parameters
[in] part
Returns
HTP_OK on success (header found and parsed), HTP_DECLINED if there is no C-D header or if it could not be processed, and HTP_ERROR on fatal error.
Definition at line 101 of file htp_multipart.c.
References bstr_dup_mem(), bstr_index_of_c(), bstr_len, bstr_ptr, CD_PARAM_FILENAME, CD_PARAM_NAME, htp_file_t::fd, htp_multipart_part_t::file, htp_file_t::filename, htp_multipart_t::flags, htp_multipart_part_t::headers, HTP_DECLINED, HTP_ERROR, HTP_FILE_MULTIPART, HTP_MULTIPART_CD_PARAM_REPEATED, HTP_MULTIPART_CD_PARAM_UNKNOWN, HTP_MULTIPART_CD_SYNTAX_INVALID, HTP_MULTIPART_PART_UNKNOWN, HTP_OK, htp_table_get_c(), htp_mpartp_t::multipart, htp_multipart_part_t::name, htp_multipart_part_t::parser, htp_file_t::source, and htp_header_t::value.
Referenced by htp_mpart_part_process_headers().
htp_status_t htp_mpart_part_process_headers (htp_multipart_part_t * part)
Processes part headers.
Parameters
[in] part
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 297 of file htp_multipart.c.
References HTP_ERROR, htp_mpart_part_parse_c_d(), and HTP_OK.
Referenced by htp_mpart_part_handle_data().
htp_mpartp_t* htp_mpartp_create (htp_cfg_t * cfg, bstr * boundary, uint64_t flags)
Creates a new multipart/form-data parser. On a successful invocation, the ownership of the boundary parameter is transferred to the parser.
Parameters
[in] cfg
[in] boundary
[in] flags
Returns
New parser instance, or NULL on memory allocation failure.
Definition at line 885 of file htp_multipart.c.
References htp_mpartp_t::boundary_pieces, bstr_builder_create(), bstr_free(), bstr_len, bstr_ptr, htp_mpartp_t::cfg, DEFAULT_FILE_EXTRACT_LIMIT, htp_mpartp_t::extract_dir, htp_mpartp_t::extract_files, htp_mpartp_t::extract_limit, htp_cfg_t::extract_request_files, htp_cfg_t::extract_request_files_limit, flags, htp_multipart_t::flags, htp_mpartp_t::handle_boundary, htp_mpartp_t::handle_data, htp_list_create, htp_mpartp_destroy(), HTP_OK, htp_mpartp_t::multipart, htp_mpartp_t::parser_state, htp_mpartp_t::part_data_pieces, htp_mpartp_t::part_header_pieces, htp_multipart_t::parts, STATE_INIT, and htp_cfg_t::tmpdir.
Referenced by htp_ch_multipart_callback_request_headers().
void htp_mpartp_destroy (htp_mpartp_t * parser)
Destroys the provided parser.
Parameters
[in] parser
Definition at line 944 of file htp_multipart.c.
References htp_multipart_t::boundary, htp_mpartp_t::boundary_pieces, bstr_builder_destroy(), bstr_free(), htp_mpartp_t::gave_up_data, htp_list_destroy, htp_list_get, htp_list_size, htp_mpart_part_destroy(), htp_mpartp_t::multipart, htp_mpartp_t::part_data_pieces, htp_mpartp_t::part_header_pieces, htp_multipart_t::parts, and htp_mpartp_t::pending_header_line.
Referenced by htp_mpartp_create(), and htp_tx_destroy_incomplete().
htp_status_t htp_mpartp_finalize (htp_mpartp_t * parser)
Finalize parsing.
Parameters
[in] parser
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 1080 of file htp_multipart.c.
References htp_mpartp_t::boundary_pieces, bstr_builder_clear(), htp_mpartp_t::current_part, htp_multipart_t::flags, HTP_ERROR, htp_mpart_part_finalize_data(), HTP_MULTIPART_INCOMPLETE, HTP_OK, htp_mpartp_t::multipart, MULTIPART_PART_EPILOGUE, and htp_multipart_part_t::type.
Referenced by htp_ch_multipart_callback_request_body_data().
htp_status_t htp_mpartp_find_boundary (bstr * content_type, bstr ** boundary, uint64_t * multipart_flags)
Looks for boundary in the supplied Content-Type request header. The extracted boundary will be allocated on the heap.
Parameters
[in] content_type
[out] boundary
[out] multipart_flags Multipart flags, which are not compatible from general LibHTP flags.
Returns
HTP_OK on success (boundary found), HTP_DECLINED if boundary was not found, and HTP_ERROR on failure. Flags may be set on HTP_OK and HTP_DECLINED. For example, if a boundary could not be extracted but there is indication that one is present, HTP_MULTIPART_HBOUNDARY_INVALID will be set.
Definition at line 1472 of file htp_multipart.c.
References bstr_begins_with_c(), bstr_dup_mem(), bstr_index_of_c_nocase(), bstr_len, bstr_ptr, fprint_bstr(), HTP_DECLINED, HTP_ERROR, htp_is_space(), HTP_MULTIPART_HBOUNDARY_INVALID, HTP_MULTIPART_HBOUNDARY_UNUSUAL, and HTP_OK.
Referenced by htp_ch_multipart_callback_request_headers().
htp_multipart_t* htp_mpartp_get_multipart (htp_mpartp_t * parser)
Returns the multipart structure created by the parser.
Parameters
[in] parser
Returns
The main multipart structure.
Definition at line 61 of file htp_multipart.c.
References htp_mpartp_t::multipart.
Referenced by htp_ch_multipart_callback_request_body_data().
htp_status_t htp_mpartp_parse (htp_mpartp_t * parser, const void * data, size_t len)
Parses a chunk of multipart/form-data data. This function should be called as many times as necessary until all data has been consumed.
Parameters
[in] parser
[in] data
[in] len
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 1099 of file htp_multipart.c.
References htp_multipart_t::boundary, htp_mpartp_t::boundary_candidate_pos, htp_multipart_t::boundary_count, htp_multipart_t::boundary_len, htp_mpartp_t::boundary_match_pos, htp_mpartp_t::boundary_pieces, bstr_builder_append_mem(), CR, htp_mpartp_t::cr_aside, htp_mpartp_t::current_part_mode, htp_multipart_t::flags, fprint_raw_data(), htp_mpartp_t::handle_boundary, htp_mpartp_t::handle_data, HTP_ERROR, htp_is_lws(), HTP_MULTIPART_BBOUNDARY_LWS_AFTER, HTP_MULTIPART_BBOUNDARY_NLWS_AFTER, HTP_MULTIPART_CRLF_LINE, HTP_MULTIPART_LF_LINE, HTP_MULTIPART_PART_AFTER_LAST_BOUNDARY, HTP_MULTIPART_SEEN_LAST_BOUNDARY, HTP_OK, LF, MODE_LINE, htp_mpartp_t::multipart, htp_mpartp_t::parser_state, STATE_BOUNDARY, STATE_BOUNDARY_EAT_LWS, STATE_BOUNDARY_EAT_LWS_CR, STATE_BOUNDARY_IS_LAST1, STATE_BOUNDARY_IS_LAST2, STATE_DATA, and STATE_INIT.
Referenced by htp_ch_multipart_callback_request_body_data().
htp_status_t htp_mpartp_parse_header (htp_multipart_part_t * part, const unsigned char * data, size_t len)
Parses one part header.
Parameters
[in] part
[in] data
[in] len
Returns
HTP_OK on success, HTP_DECLINED on parsing error, HTP_ERROR on fatal error.
Definition at line 312 of file htp_multipart.c.
References bstr_add_mem_noex(), bstr_add_noex(), bstr_cmp_c_nocase(), bstr_dup_mem(), bstr_expand(), bstr_free(), bstr_len, htp_header_t::flags, htp_multipart_t::flags, htp_multipart_part_t::headers, HTP_DECLINED, HTP_ERROR, htp_is_lws(), htp_is_space(), htp_is_token(), HTP_MULTIPART_NUL_BYTE, HTP_MULTIPART_PART_HEADER_INVALID, HTP_MULTIPART_PART_HEADER_REPEATED, HTP_MULTIPART_PART_HEADER_UNKNOWN, HTP_OK, htp_table_add(), htp_table_get(), len, htp_mpartp_t::multipart, htp_header_t::name, htp_multipart_part_t::parser, and htp_header_t::value.
Referenced by htp_mpart_part_handle_data().
htp_status_t htp_mpartp_run_request_file_data_hook (htp_multipart_part_t * part, const unsigned char * data, size_t len)
Definition at line 574 of file htp_multipart.c.
References htp_mpartp_t::cfg, htp_file_data_t::data, data, htp_file_data_t::file, htp_multipart_part_t::file, htp_cfg_t::hook_request_file_data, htp_hook_run_all(), HTP_OK, len, htp_file_t::len, htp_file_data_t::len, and htp_multipart_part_t::parser.
Referenced by htp_mpart_part_finalize_data(), and htp_mpart_part_handle_data().