suricata: libhtp/htp/htp_php.c File Reference
htp_php.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
Functions
htp_status_t htp_php_parameter_processor (htp_param_t *p)
Detailed Description
Author
Ivan Ristic ivanr.nosp@m.@web.nosp@m.kreat.nosp@m.or.c.nosp@m.om
Definition in file htp_php.c.
Function Documentation
htp_status_t htp_php_parameter_processor (htp_param_t * p)
This is a proof-of-concept processor that processes parameter names in a way similar to PHP. Whitespace at the beginning is removed, and the remaining whitespace characters are converted to underscores. Proper research of PHP's behavior is needed before we can claim to be emulating it.
Parameters
[in,out] p
Returns
HTP_OK on success, HTP_ERROR on failure.
Definition at line 52 of file htp_php.c.
References bstr_dup(), bstr_dup_mem(), bstr_free(), bstr_len, bstr_ptr, data, HTP_ERROR, HTP_OK, len, and htp_param_t::name.