suricata: src/ippair-bit.c File Reference
ippair-bit.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "ippair-bit.h"
#include "ippair.h"
#include "detect.h"
#include "util-var.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "ippair-storage.h"
Functions
void XBitFreeAll (void *store)
void IPPairBitInitCtx (void)
int IPPairHasBits (IPPair *ippair)
int IPPairBitsTimedoutCheck (IPPair *h, struct timeval *ts)
void IPPairBitSet (IPPair *h, uint16_t idx, uint32_t expire)
void IPPairBitUnset (IPPair *h, uint16_t idx)
void IPPairBitToggle (IPPair *h, uint16_t idx, uint32_t expire)
int IPPairBitIsset (IPPair *h, uint16_t idx, uint32_t ts)
int IPPairBitIsnotset (IPPair *h, uint16_t idx, uint32_t ts)
void IPPairBitRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements per ippair bits. Actually, not a bit, but called that way because of Snort's flowbits. It's a binary storage.
Todo:
move away from a linked list implementation
use different datatypes, such as string, int, etc.
Definition in file ippair-bit.c.
Function Documentation
void IPPairBitInitCtx (void)
Definition at line 48 of file ippair-bit.c.
References IPPairStorageRegister(), SC_ERR_IPPAIR_INIT, SCLogError, and XBitFreeAll().
int IPPairBitIsnotset (IPPair * h, uint16_t idx, uint32_t ts)
Definition at line 170 of file ippair-bit.c.
References XBit_::expire.
int IPPairBitIsset (IPPair * h, uint16_t idx, uint32_t ts)
Definition at line 156 of file ippair-bit.c.
References XBit_::expire.
void IPPairBitRegisterTests (void)
Definition at line 491 of file ippair-bit.c.
Referenced by RunUnittests().
void IPPairBitSet (IPPair * h, uint16_t idx, uint32_t expire)
Definition at line 130 of file ippair-bit.c.
int IPPairBitsTimedoutCheck (IPPair * h, struct timeval * ts)
Return values
1 ippair timed out wrt xbits
0 ippair still has active (non-expired) xbits
Definition at line 67 of file ippair-bit.c.
References DETECT_XBITS, XBit_::expire, IPPairGetStorageById(), GenericVar_::next, and GenericVar_::type.
void IPPairBitToggle (IPPair * h, uint16_t idx, uint32_t expire)
Definition at line 146 of file ippair-bit.c.
void IPPairBitUnset (IPPair * h, uint16_t idx)
Definition at line 138 of file ippair-bit.c.
int IPPairHasBits (IPPair * ippair)
Definition at line 58 of file ippair-bit.c.
References IPPairGetStorageById().
void XBitFreeAll (void * store)
Definition at line 43 of file ippair-bit.c.
References GenericVarFree().
Referenced by IPPairBitInitCtx().