suricata: src/ippair-storage.c File Reference
ippair-storage.c File Reference
#include "suricata-common.h"
#include "ippair-storage.h"
#include "util-unittest.h"
Functions
unsigned int IPPairStorageSize (void)
void * IPPairGetStorageById (IPPair *h, int id)
int IPPairSetStorageById (IPPair *h, int id, void *ptr)
void * IPPairAllocStorageById (IPPair *h, int id)
void IPPairFreeStorageById (IPPair *h, int id)
void IPPairFreeStorage (IPPair *h)
int IPPairStorageRegister (const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
void RegisterIPPairStorageTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
IPPair wrapper around storage api
Definition in file ippair-storage.c.
Function Documentation
void* IPPairAllocStorageById (IPPair * h, int id)
Definition at line 45 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageAllocByIdPrealloc().
void IPPairFreeStorage (IPPair * h)
Definition at line 55 of file ippair-storage.c.
References IPPairStorageSize(), STORAGE_IPPAIR, and StorageFreeAll().
Referenced by IPPairCleanup(), and IPPairClearMemory().
void IPPairFreeStorageById (IPPair * h, int id)
Definition at line 50 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageFreeById().
void* IPPairGetStorageById (IPPair * h, int id)
Definition at line 35 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageGetById().
Referenced by IPPairBitsTimedoutCheck(), and IPPairHasBits().
int IPPairSetStorageById (IPPair * h, int id, void * ptr)
Definition at line 40 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageSetById().
int IPPairStorageRegister (const char * name, const unsigned int size, void *(*)(unsigned int) Alloc, void(*)(void *) Free)
Definition at line 61 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageRegister().
Referenced by IPPairBitInitCtx().
unsigned int IPPairStorageSize (void)
Definition at line 30 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageGetSize().
Referenced by IPPairClearMemory(), IPPairFreeStorage(), and IPPairInitConfig().
void RegisterIPPairStorageTests (void)
Definition at line 292 of file ippair-storage.c.
Referenced by IPPairRegisterUnittests().