suricata: src/ippair.h File Reference
ippair.h File Reference
#include "decode.h"
#include "util-storage.h"
Data Structures
struct IPPair_
struct IPPairHashRow_
struct IPPairConfig_
Macros
#define HRLOCK_MUTEX
#define HRLOCK_TYPE SCMutex
#define HRLOCK_INIT(fb) SCMutexInit(&(fb)->lock, NULL)
#define HRLOCK_DESTROY(fb) SCMutexDestroy(&(fb)->lock)
#define HRLOCK_LOCK(fb) SCMutexLock(&(fb)->lock)
#define HRLOCK_TRYLOCK(fb) SCMutexTrylock(&(fb)->lock)
#define HRLOCK_UNLOCK(fb) SCMutexUnlock(&(fb)->lock)
#define IPPAIR_VERBOSE 0
#define IPPAIR_QUIET 1
#define IPPAIR_CHECK_MEMCAP(size) ((((uint64_t)SC_ATOMIC_GET(ippair_memuse) + (uint64_t)(size)) <= ippair_config.memcap))
check if a memory alloc would fit in the memcap
#define IPPairIncrUsecnt(h) (void)SC_ATOMIC_ADD((h)->use_cnt, 1)
#define IPPairDecrUsecnt(h) (void)SC_ATOMIC_SUB((h)->use_cnt, 1)
#define IPPairReference(dst_h_ptr, h)
#define IPPairDeReference(src_h_ptr)
Typedefs
typedef struct IPPair_ IPPair
typedef struct IPPairConfig_ IPPairConfig
Functions
struct IPPairHashRow_ __attribute__ ((aligned(CLS))) IPPairHashRow
SC_ATOMIC_DECLARE (unsigned long long int, ippair_memuse)
SC_ATOMIC_DECLARE (unsigned int, ippair_counter)
SC_ATOMIC_DECLARE (unsigned int, ippair_prune_idx)
void IPPairInitConfig (char quiet)
initialize the configuration
void IPPairShutdown (void)
shutdown the flow engine
void IPPairCleanup (void)
Cleanup the ippair engine.
IPPair * IPPairLookupIPPairFromHash (Address *, Address *)
look up a ippair in the hash
IPPair * IPPairGetIPPairFromHash (Address *, Address *)
void IPPairRelease (IPPair *)
void IPPairLock (IPPair *)
void IPPairClearMemory (IPPair *)
void IPPairMoveToSpare (IPPair *)
uint32_t IPPairSpareQueueGetSize (void)
void IPPairPrintStats (void)
print some ippair stats
void IPPairRegisterUnittests (void)
IPPair * IPPairAlloc (void)
void IPPairFree (IPPair *)
void IPPairUnlock (IPPair *)
Variables
HRLOCK_TYPE lock
IPPair * head
IPPair * tail
IPPairHashRow * ippair_hash
IPPairConfig ippair_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file ippair.h.
Macro Definition Documentation
#define HRLOCK_DESTROY (fb) SCMutexDestroy(&(fb)->lock)
Definition at line 50 of file ippair.h.
#define HRLOCK_INIT (fb) SCMutexInit(&(fb)->lock, NULL)
Definition at line 49 of file ippair.h.
#define HRLOCK_LOCK (fb) SCMutexLock(&(fb)->lock)
Definition at line 51 of file ippair.h.
#define HRLOCK_MUTEX
Spinlocks or Mutex for the flow buckets.
Definition at line 32 of file ippair.h.
#define HRLOCK_TRYLOCK (fb) SCMutexTrylock(&(fb)->lock)
Definition at line 52 of file ippair.h.
#define HRLOCK_TYPE SCMutex
Definition at line 48 of file ippair.h.
#define HRLOCK_UNLOCK (fb) SCMutexUnlock(&(fb)->lock)
Definition at line 53 of file ippair.h.
#define IPPAIR_CHECK_MEMCAP (size) ((((uint64_t)SC_ATOMIC_GET(ippair_memuse) + (uint64_t)(size)) <= ippair_config.memcap))
check if a memory alloc would fit in the memcap
Parameters
size memory allocation size to check
Return values
1 it fits
0 no fit
Definition at line 106 of file ippair.h.
Referenced by IPPairAlloc(), and IPPairInitConfig().
#define IPPAIR_QUIET 1
Definition at line 90 of file ippair.h.
#define IPPAIR_VERBOSE 0
Definition at line 89 of file ippair.h.
Referenced by main().
#define IPPairDecrUsecnt (h) (void)SC_ATOMIC_SUB((h)->use_cnt, 1)
Definition at line 111 of file ippair.h.
Referenced by IPPairRelease().
#define IPPairDeReference (src_h_ptr)
Value:
do {               \
        if (*(src_h_ptr) != NULL) {                   \
            IPPairDecrUsecnt(*(src_h_ptr));             \
            *(src_h_ptr) = NULL;                      \
        }                                             \
    } while (0)
Definition at line 121 of file ippair.h.
#define IPPairIncrUsecnt (h) (void)SC_ATOMIC_ADD((h)->use_cnt, 1)
Definition at line 109 of file ippair.h.
Referenced by IPPairGetIPPairFromHash(), IPPairInit(), and IPPairLookupIPPairFromHash().
#define IPPairReference (dst_h_ptr, h)
Value:
do {            \
        if ((h) != NULL) {                          \
            IPPairIncrUsecnt((h));                    \
            *(dst_h_ptr) = h;                       \
        }                                           \
    } while (0)
Definition at line 114 of file ippair.h.
Typedef Documentation
typedef struct IPPair_ IPPair
typedef struct IPPairConfig_ IPPairConfig
Function Documentation
struct IPPairHashRow_ __attribute__ ((aligned(CLS)))
IPPair* IPPairAlloc (void)
Definition at line 65 of file ippair.c.
References IPPAIR_CHECK_MEMCAP, IPPair_::m, SC_ATOMIC_ADD, SC_ATOMIC_INIT, SCMalloc, SCMutexInit, and unlikely.
Referenced by IPPairInitConfig(), and IPPairNew().
void IPPairCleanup (void)
Cleanup the ippair engine.
Cleanup the ippair engine from tag and threshold.
Definition at line 300 of file ippair.c.
References IPPairConfig_::hash_size, IPPair_::hnext, IPPair_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, ippair_config, ippair_hash, IPPairClearMemory(), IPPairFreeStorage(), IPPairMoveToSpare(), and SC_ATOMIC_GET.
void IPPairClearMemory (IPPair *)
Definition at line 115 of file ippair.c.
References IPPairFreeStorage(), and IPPairStorageSize().
Referenced by IPPairCleanup(), and IPPairFree().
void IPPairFree (IPPair *)
Definition at line 87 of file ippair.c.
References IPPairClearMemory(), IPPair_::m, SC_ATOMIC_DESTROY, SC_ATOMIC_SUB, SCFree, and SCMutexDestroy.
Referenced by IPPairShutdown().
IPPair* IPPairGetIPPairFromHash (Address * , Address *)
Definition at line 457 of file ippair.c.
References IPPair_::hnext, IPPair_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, ippair_hash, IPPairIncrUsecnt, IPPairInit(), IPPair_::m, and SCMutexLock.
void IPPairInitConfig (char quiet)
initialize the configuration
Warning
Not thread safe
set config values for memcap, prealloc and hash_size
Definition at line 127 of file ippair.c.
References ByteExtractStringUint32(), ConfGet(), FALSE, IPPairConfig_::hash_rand, IPPairConfig_::hash_size, HRLOCK_INIT, IPPAIR_CHECK_MEMCAP, ippair_config, IPPAIR_DEFAULT_HASHSIZE, IPPAIR_DEFAULT_MEMCAP, IPPAIR_DEFAULT_PREALLOC, ippair_hash, IPPairAlloc(), IPPairEnqueue(), IPPairQueueInit(), IPPairStorageSize(), IPPairQueue_::len, IPPairConfig_::memcap, ParseSizeStringU64(), IPPairConfig_::prealloc, RandomTimePreseed(), SC_ATOMIC_ADD, SC_ATOMIC_GET, SC_ATOMIC_INIT, SC_ERR_FATAL, SC_ERR_IPPAIR_INIT, SC_ERR_SIZE_PARSE, SCCalloc, SCLogDebug, SCLogError, SCLogInfo, unlikely, and WarnInvalidConfEntry.
Referenced by main().
void IPPairLock (IPPair *)
Definition at line 439 of file ippair.c.
References IPPair_::m, and SCMutexLock.
IPPair* IPPairLookupIPPairFromHash (Address * a, Address * b)
look up a ippair in the hash
Parameters
a address to look up
Return values
h LOCKED ippair or NULL
Definition at line 556 of file ippair.c.
References IPPair_::hnext, IPPair_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, ippair_hash, IPPairIncrUsecnt, IPPair_::m, and SCMutexLock.
void IPPairMoveToSpare (IPPair *)
Definition at line 59 of file ippair.c.
References IPPairEnqueue(), and SC_ATOMIC_SUB.
Referenced by IPPairCleanup().
void IPPairPrintStats (void)
print some ippair stats
Warning
Not thread safe
Definition at line 244 of file ippair.c.
References ippair_config, IPPairConfig_::memcap, SC_ATOMIC_GET, and SCLogInfo.
Referenced by IPPairShutdown().
void IPPairRegisterUnittests (void)
Definition at line 688 of file ippair.c.
References RegisterIPPairStorageTests().
Referenced by RunUnittests().
void IPPairRelease (IPPair *)
Definition at line 433 of file ippair.c.
References IPPairDecrUsecnt, IPPair_::m, and SCMutexUnlock.
void IPPairShutdown (void)
shutdown the flow engine
Warning
Not thread safe
Definition at line 257 of file ippair.c.
References BUG_ON, IPPairConfig_::hash_size, IPPair_::hnext, HRLOCK_DESTROY, ippair_config, ippair_hash, IPPairDequeue(), IPPairFree(), IPPairPrintStats(), IPPairQueueDestroy(), SC_ATOMIC_DESTROY, SC_ATOMIC_GET, SC_ATOMIC_SUB, and SCFree.
Referenced by main().
uint32_t IPPairSpareQueueGetSize (void)
Definition at line 54 of file ippair.c.
References IPPairQueueLen().
Referenced by IPPairGetSpareCount().
void IPPairUnlock (IPPair *)
Definition at line 444 of file ippair.c.
References IPPair_::m, and SCMutexUnlock.
SC_ATOMIC_DECLARE (unsigned long long int, ippair_memuse)
SC_ATOMIC_DECLARE (unsigned int, ippair_counter)
SC_ATOMIC_DECLARE (unsigned int, ippair_prune_idx)
Variable Documentation
IPPair* head
Definition at line 690 of file ippair.h.
IPPairConfig ippair_config
Definition at line 128 of file ippair.h.
Referenced by IPPairCleanup(), IPPairInitConfig(), IPPairPrintStats(), IPPairShutdown(), and IPPairTimeoutHash().
IPPairHashRow* ippair_hash
ippair hash table
Definition at line 87 of file ippair.h.
Referenced by IPPairCleanup(), IPPairGetIPPairFromHash(), IPPairInitConfig(), IPPairLookupIPPairFromHash(), IPPairShutdown(), and IPPairTimeoutHash().
HRLOCK_TYPE lock
Definition at line 689 of file ippair.h.
IPPair* tail
Definition at line 691 of file ippair.h.