suricata: src/ippair.c File Reference
ippair.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "util-debug.h"
#include "ippair.h"
#include "ippair-storage.h"
#include "util-random.h"
#include "util-misc.h"
#include "util-byte.h"
#include "ippair-queue.h"
#include "detect-tag.h"
#include "detect-engine-tag.h"
#include "detect-engine-threshold.h"
#include "util-hash-lookup3.h"
Macros
#define IPPAIR_DEFAULT_HASHSIZE 4096
#define IPPAIR_DEFAULT_MEMCAP 16777216
#define IPPAIR_DEFAULT_PREALLOC 1000
Functions
uint32_t IPPairSpareQueueGetSize (void)
void IPPairMoveToSpare (IPPair *h)
IPPair * IPPairAlloc (void)
void IPPairFree (IPPair *h)
IPPair * IPPairNew (Address *a, Address *b)
void IPPairClearMemory (IPPair *h)
void IPPairInitConfig (char quiet)
initialize the configuration
void IPPairPrintStats (void)
print some ippair stats
void IPPairShutdown (void)
shutdown the flow engine
void IPPairCleanup (void)
Cleanup the ippair engine.
void IPPairInit (IPPair *h, Address *a, Address *b)
void IPPairRelease (IPPair *h)
void IPPairLock (IPPair *h)
void IPPairUnlock (IPPair *h)
IPPair * IPPairGetIPPairFromHash (Address *a, Address *b)
IPPair * IPPairLookupIPPairFromHash (Address *a, Address *b)
look up a ippair in the hash
void IPPairRegisterUnittests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Information about ippairs.
Definition in file ippair.c.
Macro Definition Documentation
#define IPPAIR_DEFAULT_HASHSIZE 4096
Definition at line 121 of file ippair.c.
Referenced by IPPairInitConfig().
#define IPPAIR_DEFAULT_MEMCAP 16777216
Definition at line 122 of file ippair.c.
Referenced by IPPairInitConfig().
#define IPPAIR_DEFAULT_PREALLOC 1000
Definition at line 123 of file ippair.c.
Referenced by IPPairInitConfig().
Function Documentation
IPPair* IPPairAlloc (void)
Definition at line 65 of file ippair.c.
References IPPAIR_CHECK_MEMCAP, IPPair_::m, SC_ATOMIC_ADD, SC_ATOMIC_INIT, SCMalloc, SCMutexInit, and unlikely.
Referenced by IPPairInitConfig(), and IPPairNew().
void IPPairCleanup (void)
Cleanup the ippair engine.
Cleanup the ippair engine from tag and threshold.
Definition at line 300 of file ippair.c.
References IPPairConfig_::hash_size, IPPair_::hnext, IPPair_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, ippair_config, ippair_hash, IPPairClearMemory(), IPPairFreeStorage(), IPPairMoveToSpare(), and SC_ATOMIC_GET.
void IPPairClearMemory (IPPair * h)
Definition at line 115 of file ippair.c.
References IPPairFreeStorage(), and IPPairStorageSize().
Referenced by IPPairCleanup(), and IPPairFree().
void IPPairFree (IPPair * h)
Definition at line 87 of file ippair.c.
References IPPairClearMemory(), IPPair_::m, SC_ATOMIC_DESTROY, SC_ATOMIC_SUB, SCFree, and SCMutexDestroy.
Referenced by IPPairShutdown().
IPPair* IPPairGetIPPairFromHash (Address * a, Address * b)
Definition at line 457 of file ippair.c.
References IPPair_::hnext, IPPair_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, ippair_hash, IPPairIncrUsecnt, IPPairInit(), IPPair_::m, and SCMutexLock.
void IPPairInit (IPPair * h, Address * a, Address * b)
Definition at line 426 of file ippair.c.
References IPPair_::a, COPY_ADDRESS, and IPPairIncrUsecnt.
Referenced by IPPairGetIPPairFromHash().
void IPPairInitConfig (char quiet)
initialize the configuration
Warning
Not thread safe
set config values for memcap, prealloc and hash_size
Definition at line 127 of file ippair.c.
References ByteExtractStringUint32(), ConfGet(), FALSE, IPPairConfig_::hash_rand, IPPairConfig_::hash_size, HRLOCK_INIT, IPPAIR_CHECK_MEMCAP, ippair_config, IPPAIR_DEFAULT_HASHSIZE, IPPAIR_DEFAULT_MEMCAP, IPPAIR_DEFAULT_PREALLOC, ippair_hash, IPPairAlloc(), IPPairEnqueue(), IPPairQueueInit(), IPPairStorageSize(), IPPairQueue_::len, IPPairConfig_::memcap, ParseSizeStringU64(), IPPairConfig_::prealloc, RandomTimePreseed(), SC_ATOMIC_ADD, SC_ATOMIC_GET, SC_ATOMIC_INIT, SC_ERR_FATAL, SC_ERR_IPPAIR_INIT, SC_ERR_SIZE_PARSE, SCCalloc, SCLogDebug, SCLogError, SCLogInfo, unlikely, and WarnInvalidConfEntry.
Referenced by main().
void IPPairLock (IPPair * h)
Definition at line 439 of file ippair.c.
References IPPair_::m, and SCMutexLock.
IPPair* IPPairLookupIPPairFromHash (Address * a, Address * b)
look up a ippair in the hash
Parameters
a address to look up
Return values
h LOCKED ippair or NULL
Definition at line 556 of file ippair.c.
References IPPair_::hnext, IPPair_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, ippair_hash, IPPairIncrUsecnt, IPPair_::m, and SCMutexLock.
void IPPairMoveToSpare (IPPair * h)
Definition at line 59 of file ippair.c.
References IPPairEnqueue(), and SC_ATOMIC_SUB.
Referenced by IPPairCleanup().
IPPair* IPPairNew (Address * a, Address * b)
Definition at line 99 of file ippair.c.
References IPPair_::a, COPY_ADDRESS, and IPPairAlloc().
void IPPairPrintStats (void)
print some ippair stats
Warning
Not thread safe
Definition at line 244 of file ippair.c.
References ippair_config, IPPairConfig_::memcap, SC_ATOMIC_GET, and SCLogInfo.
Referenced by IPPairShutdown().
void IPPairRegisterUnittests (void)
Definition at line 688 of file ippair.c.
References RegisterIPPairStorageTests().
Referenced by RunUnittests().
void IPPairRelease (IPPair * h)
Definition at line 433 of file ippair.c.
References IPPairDecrUsecnt, IPPair_::m, and SCMutexUnlock.
void IPPairShutdown (void)
shutdown the flow engine
Warning
Not thread safe
Definition at line 257 of file ippair.c.
References BUG_ON, IPPairConfig_::hash_size, IPPair_::hnext, HRLOCK_DESTROY, ippair_config, ippair_hash, IPPairDequeue(), IPPairFree(), IPPairPrintStats(), IPPairQueueDestroy(), SC_ATOMIC_DESTROY, SC_ATOMIC_GET, SC_ATOMIC_SUB, and SCFree.
Referenced by main().
uint32_t IPPairSpareQueueGetSize (void)
Definition at line 54 of file ippair.c.
References IPPairQueueLen().
Referenced by IPPairGetSpareCount().
void IPPairUnlock (IPPair * h)
Definition at line 444 of file ippair.c.
References IPPair_::m, and SCMutexUnlock.