suricata: src/log-stats.c File Reference
log-stats.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "output.h"
#include "log-stats.h"
#include "util-privs.h"
#include "util-buffer.h"
#include "util-logopenfile.h"
#include "util-time.h"
Data Structures
struct LogStatsFileCtx_
struct LogStatsLogThread_
Macros
#define DEFAULT_LOG_FILENAME "stats.log"
#define MODULE_NAME "LogStatsLog"
#define OUTPUT_BUFFER_SIZE 16384
#define LOG_STATS_TOTALS (1<<0)
#define LOG_STATS_THREADS (1<<1)
Typedefs
typedef struct LogStatsFileCtx_ LogStatsFileCtx
typedef struct LogStatsLogThread_ LogStatsLogThread
Functions
TmEcode LogStatsLogThreadInit (ThreadVars *, void *, void **)
TmEcode LogStatsLogThreadDeinit (ThreadVars *, void *)
void LogStatsLogExitPrintStats (ThreadVars *, void *)
int LogStatsLogger (ThreadVars *tv, void *thread_data, const StatsTable *st)
OutputCtx * LogStatsLogInitCtx (ConfNode *conf)
Create a new http log LogFileCtx.
void TmModuleLogStatsLogRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file log-stats.c.
Macro Definition Documentation
#define DEFAULT_LOG_FILENAME "stats.log"
Definition at line 48 of file log-stats.c.
Referenced by LogStatsLogInitCtx().
#define LOG_STATS_THREADS (1<<1)
Definition at line 53 of file log-stats.c.
Referenced by LogStatsLogger(), and LogStatsLogInitCtx().
#define LOG_STATS_TOTALS (1<<0)
Definition at line 52 of file log-stats.c.
Referenced by LogStatsLogger(), and LogStatsLogInitCtx().
#define MODULE_NAME "LogStatsLog"
Definition at line 49 of file log-stats.c.
Referenced by TmModuleLogStatsLogRegister().
#define OUTPUT_BUFFER_SIZE 16384
Definition at line 50 of file log-stats.c.
Referenced by LogStatsLogger(), and LogStatsLogThreadInit().
Typedef Documentation
typedef struct LogStatsFileCtx_ LogStatsFileCtx
typedef struct LogStatsLogThread_ LogStatsLogThread
Function Documentation
void LogStatsLogExitPrintStats (ThreadVars * tv, void * data)
Definition at line 204 of file log-stats.c.
Referenced by TmModuleLogStatsLogRegister().
int LogStatsLogger (ThreadVars * tv, void * thread_data, const StatsTable * st)
Definition at line 70 of file log-stats.c.
References LogStatsLogThread_::buffer, LogStatsFileCtx_::file_ctx, LogStatsFileCtx_::flags, LogFileCtx_::fp_mutex, len, LOG_STATS_THREADS, LOG_STATS_TOTALS, MEMBUFFER_BUFFER, MEMBUFFER_OFFSET, MEMBUFFER_SIZE, MemBufferExpand(), MemBufferReset, MemBufferWriteString, StatsRecord_::name, StatsTable_::nstats, StatsTable_::ntstats, OUTPUT_BUFFER_SIZE, SCEnter, SCLocalTime(), SCMutexLock, SCMutexUnlock, SCReturnInt, StatsTable_::start_time, StatsTable_::stats, LogStatsLogThread_::statslog_ctx, StatsRecord_::tm_name, StatsTable_::tstats, StatsRecord_::value, and LogFileCtx_::Write.
Referenced by TmModuleLogStatsLogRegister().
OutputCtx* LogStatsLogInitCtx (ConfNode * conf)
Create a new http log LogFileCtx.
Parameters
conf Pointer to ConfNode containing this loggers configuration.
Returns
NULL if failure, LogFileCtx* to the file_ctx if succesful
Definition at line 216 of file log-stats.c.
References ConfNodeLookupChildValue(), ConfValIsFalse(), ConfValIsTrue(), OutputCtx_::data, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, LogStatsFileCtx_::file_ctx, LogStatsFileCtx_::flags, LOG_STATS_THREADS, LOG_STATS_TOTALS, LogFileFreeCtx(), LogFileNewCtx(), SC_ERR_HTTP_LOG_GENERIC, SCCalloc, SCConfLogOpenGeneric(), SCFree, SCLogDebug, SCLogError, SCMalloc, and unlikely.
Referenced by TmModuleLogStatsLogRegister().
TmEcode LogStatsLogThreadDeinit (ThreadVars * t, void * data)
Definition at line 189 of file log-stats.c.
References LogStatsLogThread_::buffer, MemBufferFree(), SCFree, and TM_ECODE_OK.
Referenced by TmModuleLogStatsLogRegister().
TmEcode LogStatsLogThreadInit (ThreadVars * t, void * initdata, void ** data)
Definition at line 162 of file log-stats.c.
References LogStatsLogThread_::buffer, MemBufferCreateNew(), OUTPUT_BUFFER_SIZE, SCFree, SCLogDebug, SCMalloc, LogStatsLogThread_::statslog_ctx, TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by TmModuleLogStatsLogRegister().
void TmModuleLogStatsLogRegister (void)
Definition at line 277 of file log-stats.c.
References TmModule_::cap_flags, TmModule_::flags, LogStatsLogExitPrintStats(), LogStatsLogger(), LogStatsLogInitCtx(), LogStatsLogThreadDeinit(), LogStatsLogThreadInit(), MODULE_NAME, TmModule_::name, OutputRegisterStatsModule(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_LOGSTATSLOG, and tmm_modules.
Referenced by RegisterAllModules().