suricata: src/log-stats.h File Reference
log-stats.h File Reference
Functions
void TmModuleLogStatsLogRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file log-stats.h.
Function Documentation
void TmModuleLogStatsLogRegister (void)
Definition at line 277 of file log-stats.c.
References TmModule_::cap_flags, TmModule_::flags, LogStatsLogExitPrintStats(), LogStatsLogger(), LogStatsLogInitCtx(), LogStatsLogThreadDeinit(), LogStatsLogThreadInit(), MODULE_NAME, TmModule_::name, OutputRegisterStatsModule(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_LOGSTATSLOG, and tmm_modules.
Referenced by RegisterAllModules().