suricata: src/log-httplog.h File Reference
log-httplog.h File Reference
Functions
void TmModuleLogHttpLogRegister (void)
void TmModuleLogHttpLogIPv4Register (void)
void TmModuleLogHttpLogIPv6Register (void)
OutputCtx * LogHttpLogInitCtx (ConfNode *)
Create a new http log LogFileCtx.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file log-httplog.h.
Function Documentation
OutputCtx* LogHttpLogInitCtx (ConfNode * conf)
Create a new http log LogFileCtx.
Parameters
conf Pointer to ConfNode containing this loggers configuration.
Returns
NULL if failure, LogFileCtx* to the file_ctx if succesful
Definition at line 592 of file log-httplog.c.
References ALPROTO_HTTP, AppLayerParserRegisterLogger(), LogHttpFileCtx_::cf_n, LogHttpFileCtx_::cf_nodes, ConfNodeLookupChildValue(), ConfValIsTrue(), OutputCtx_::data, LogHttpCustomFormatNode_::data, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, LogHttpFileCtx_::file_ctx, LogHttpFileCtx_::flags, LOG_HTTP_CF_LITERAL, LOG_HTTP_CUSTOM, LOG_HTTP_DEFAULT, LOG_HTTP_EXTENDED, LOG_HTTP_MAXN_NODES, LOG_HTTP_NODE_MAXOUTPUTLEN, LOG_HTTP_NODE_STRLEN, LogFileFreeCtx(), LogFileNewCtx(), LogHttpCustomFormatNode_::maxlen, SC_ERR_HTTP_LOG_GENERIC, SC_ERR_INVALID_ARGUMENT, SCCalloc, SCConfLogOpenGeneric(), SCFree, SCLogDebug, SCLogError, SCMalloc, strlcpy(), LogHttpCustomFormatNode_::type, and unlikely.
Referenced by TmModuleLogHttpLogRegister().
void TmModuleLogHttpLogIPv4Register (void)
void TmModuleLogHttpLogIPv6Register (void)
void TmModuleLogHttpLogRegister (void)
Definition at line 66 of file log-httplog.c.
References ALPROTO_HTTP, TmModule_::cap_flags, TmModule_::flags, LogHttpLogExitPrintStats(), LogHttpLogger(), LogHttpLogInitCtx(), LogHttpLogThreadDeinit(), LogHttpLogThreadInit(), MODULE_NAME, TmModule_::name, OutputRegisterTxModule(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_LOGHTTPLOG, and tmm_modules.
Referenced by RegisterAllModules().