suricata: src/log-tcp-data.c File Reference
log-tcp-data.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "output.h"
#include "log-tcp-data.h"
#include "app-layer-htp.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "util-privs.h"
#include "util-buffer.h"
#include "util-logopenfile.h"
#include "util-time.h"
Data Structures
struct LogTcpDataFileCtx_
struct LogTcpDataLogThread_
Macros
#define DEFAULT_LOG_FILENAME "tcp-data.log"
#define MODULE_NAME "LogTcpDataLog"
#define OUTPUT_BUFFER_SIZE 65535
Typedefs
typedef struct LogTcpDataFileCtx_ LogTcpDataFileCtx
typedef struct LogTcpDataLogThread_ LogTcpDataLogThread
Functions
TmEcode LogTcpDataLogThreadInit (ThreadVars *, void *, void **)
TmEcode LogTcpDataLogThreadDeinit (ThreadVars *, void *)
void LogTcpDataLogExitPrintStats (ThreadVars *, void *)
int LogTcpDataLogger (ThreadVars *tv, void *thread_data, const Flow *f, const uint8_t *data, uint32_t data_len, uint64_t tx_id, uint8_t flags)
void TmModuleLogTcpDataLogRegister (void)
OutputCtx * LogTcpDataLogInitCtx (ConfNode *conf)
Create a new http log LogFileCtx.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file log-tcp-data.c.
Macro Definition Documentation
#define DEFAULT_LOG_FILENAME "tcp-data.log"
Definition at line 50 of file log-tcp-data.c.
Referenced by LogTcpDataLogInitCtx().
#define MODULE_NAME "LogTcpDataLog"
Definition at line 52 of file log-tcp-data.c.
Referenced by TmModuleLogTcpDataLogRegister().
#define OUTPUT_BUFFER_SIZE 65535
Definition at line 54 of file log-tcp-data.c.
Referenced by LogTcpDataLogThreadInit().
Typedef Documentation
typedef struct LogTcpDataFileCtx_ LogTcpDataFileCtx
typedef struct LogTcpDataLogThread_ LogTcpDataLogThread
Function Documentation
void LogTcpDataLogExitPrintStats (ThreadVars * tv, void * data)
Definition at line 232 of file log-tcp-data.c.
Referenced by TmModuleLogTcpDataLogRegister().
int LogTcpDataLogger (ThreadVars * tv, void * thread_data, const Flow * f, const uint8_t * data, uint32_t data_len, uint64_t tx_id, uint8_t flags)
Definition at line 175 of file log-tcp-data.c.
References LogTcpDataFileCtx_::dir, LogTcpDataFileCtx_::file, SCEnter, SCReturnInt, LogTcpDataLogThread_::tcpdatalog_ctx, and TM_ECODE_OK.
Referenced by TmModuleLogTcpDataLogRegister().
OutputCtx* LogTcpDataLogInitCtx (ConfNode * conf)
Create a new http log LogFileCtx.
Parameters
conf Pointer to ConfNode containing this loggers configuration.
Returns
NULL if failure, LogFileCtx* to the file_ctx if succesful
Definition at line 243 of file log-tcp-data.c.
References ConfigGetLogDirectory(), ConfNodeLookupChildValue(), OutputCtx_::data, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, LogTcpDataFileCtx_::dir, LogTcpDataFileCtx_::file, LogTcpDataFileCtx_::file_ctx, LogTcpDataFileCtx_::log_dir, LogFileFreeCtx(), LogFileNewCtx(), ConfNode_::name, SC_ERR_HTTP_LOG_GENERIC, SC_ERR_INVALID_ARGUMENT, SCCalloc, SCConfLogOpenGeneric(), SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, STREAMING_HTTP_BODIES, STREAMING_TCP_DATA, strlcpy(), LogTcpDataFileCtx_::type, and unlikely.
Referenced by TmModuleLogTcpDataLogRegister().
TmEcode LogTcpDataLogThreadDeinit (ThreadVars * t, void * data)
Definition at line 217 of file log-tcp-data.c.
References LogTcpDataLogThread_::buffer, MemBufferFree(), SCFree, and TM_ECODE_OK.
Referenced by TmModuleLogTcpDataLogRegister().
TmEcode LogTcpDataLogThreadInit (ThreadVars * t, void * initdata, void ** data)
Definition at line 190 of file log-tcp-data.c.
References LogTcpDataLogThread_::buffer, MemBufferCreateNew(), OUTPUT_BUFFER_SIZE, SCFree, SCLogDebug, SCMalloc, LogTcpDataLogThread_::tcpdatalog_ctx, TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by TmModuleLogTcpDataLogRegister().
void TmModuleLogTcpDataLogRegister (void)
Definition at line 63 of file log-tcp-data.c.
References TmModule_::cap_flags, TmModule_::flags, LogTcpDataLogExitPrintStats(), LogTcpDataLogger(), LogTcpDataLogInitCtx(), LogTcpDataLogThreadDeinit(), LogTcpDataLogThreadInit(), MODULE_NAME, TmModule_::name, OutputRegisterStreamingModule(), TmModule_::RegisterTests, STREAMING_HTTP_BODIES, STREAMING_TCP_DATA, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_LOGTCPDATALOG, and tmm_modules.
Referenced by RegisterAllModules().