suricata: src/log-pcap.h File Reference
log-pcap.h File Reference
Functions
void TmModulePcapLogRegister (void)
void PcapLogProfileSetup (void)
Detailed Description
Author
William Metcalf Willi.nosp@m.am.M.nosp@m.etcal.nosp@m.f@gm.nosp@m.ail.c.nosp@m.om
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pcap packet logging module.
Definition in file log-pcap.h.
Function Documentation
void PcapLogProfileSetup (void)
Definition at line 1165 of file log-pcap.c.
References ConfGetNode(), ConfigGetLogDirectory(), ConfNodeChildValueIsTrue(), ConfNodeLookupChildValue(), ConfValIsTrue(), SC_ERR_MEM_ALLOC, SCLogError, SCLogInfo, SCMalloc, and unlikely.
void TmModulePcapLogRegister (void)
Definition at line 153 of file log-pcap.c.
References TmModule_::Func, MODULE_NAME, TmModule_::name, OutputRegisterModule(), TmModule_::RegisterTests, SC_ATOMIC_INIT, TmModule_::ThreadDeinit, TmModule_::ThreadInit, tmm_modules, and TMM_PCAPLOG.
Referenced by RegisterAllModules().