suricata: src/log-httplog.c File Reference
log-httplog.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "output.h"
#include "log-httplog.h"
#include "app-layer-htp.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "util-privs.h"
#include "util-buffer.h"
#include "util-logopenfile.h"
#include "util-time.h"
Data Structures
struct LogHttpCustomFormatNode_
struct LogHttpFileCtx_
struct LogHttpLogThread_
Macros
#define DEFAULT_LOG_FILENAME "http.log"
#define MODULE_NAME "LogHttpLog"
#define OUTPUT_BUFFER_SIZE 65535
#define LOG_HTTP_MAXN_NODES 64
#define LOG_HTTP_NODE_STRLEN 256
#define LOG_HTTP_NODE_MAXOUTPUTLEN 8192
#define TIMESTAMP_DEFAULT_FORMAT "%b %d, %Y; %H:%M:%S"
#define LOG_HTTP_CF_NONE "-"
#define LOG_HTTP_CF_LITERAL '%'
#define LOG_HTTP_CF_REQUEST_HOST 'h'
#define LOG_HTTP_CF_REQUEST_PROTOCOL 'H'
#define LOG_HTTP_CF_REQUEST_METHOD 'm'
#define LOG_HTTP_CF_REQUEST_URI 'u'
#define LOG_HTTP_CF_REQUEST_TIME 't'
#define LOG_HTTP_CF_REQUEST_HEADER 'i'
#define LOG_HTTP_CF_REQUEST_COOKIE 'C'
#define LOG_HTTP_CF_REQUEST_LEN 'b'
#define LOG_HTTP_CF_RESPONSE_STATUS 's'
#define LOG_HTTP_CF_RESPONSE_HEADER 'o'
#define LOG_HTTP_CF_RESPONSE_LEN 'B'
#define LOG_HTTP_CF_TIMESTAMP 't'
#define LOG_HTTP_CF_TIMESTAMP_U 'z'
#define LOG_HTTP_CF_CLIENT_IP 'a'
#define LOG_HTTP_CF_SERVER_IP 'A'
#define LOG_HTTP_CF_CLIENT_PORT 'p'
#define LOG_HTTP_CF_SERVER_PORT 'P'
#define LOG_HTTP_DEFAULT 0
#define LOG_HTTP_EXTENDED 1
#define LOG_HTTP_CUSTOM 2
Typedefs
typedef struct
LogHttpCustomFormatNode_ LogHttpCustomFormatNode
typedef struct LogHttpFileCtx_ LogHttpFileCtx
typedef struct LogHttpLogThread_ LogHttpLogThread
Functions
TmEcode LogHttpLogThreadInit (ThreadVars *, void *, void **)
TmEcode LogHttpLogThreadDeinit (ThreadVars *, void *)
void LogHttpLogExitPrintStats (ThreadVars *, void *)
int LogHttpLogger (ThreadVars *tv, void *thread_data, const Packet *, Flow *f, void *state, void *tx, uint64_t tx_id)
void TmModuleLogHttpLogRegister (void)
OutputCtx * LogHttpLogInitCtx (ConfNode *conf)
Create a new http log LogFileCtx.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Ignacio Sanchez sanch.nosp@m.ezma.nosp@m.rtin..nosp@m.ji@g.nosp@m.mail..nosp@m.com
Implements http logging portion of the engine.
Definition in file log-httplog.c.
Macro Definition Documentation
#define DEFAULT_LOG_FILENAME "http.log"
Definition at line 53 of file log-httplog.c.
Referenced by LogHttpLogInitCtx().
#define LOG_HTTP_CF_CLIENT_IP 'a'
Definition at line 100 of file log-httplog.c.
#define LOG_HTTP_CF_CLIENT_PORT 'p'
Definition at line 102 of file log-httplog.c.
#define LOG_HTTP_CF_LITERAL '%'
Definition at line 86 of file log-httplog.c.
Referenced by LogHttpLogInitCtx().
#define LOG_HTTP_CF_NONE "-"
Definition at line 85 of file log-httplog.c.
#define LOG_HTTP_CF_REQUEST_COOKIE 'C'
Definition at line 93 of file log-httplog.c.
#define LOG_HTTP_CF_REQUEST_HEADER 'i'
Definition at line 92 of file log-httplog.c.
#define LOG_HTTP_CF_REQUEST_HOST 'h'
Definition at line 87 of file log-httplog.c.
#define LOG_HTTP_CF_REQUEST_LEN 'b'
Definition at line 94 of file log-httplog.c.
#define LOG_HTTP_CF_REQUEST_METHOD 'm'
Definition at line 89 of file log-httplog.c.
#define LOG_HTTP_CF_REQUEST_PROTOCOL 'H'
Definition at line 88 of file log-httplog.c.
#define LOG_HTTP_CF_REQUEST_TIME 't'
Definition at line 91 of file log-httplog.c.
#define LOG_HTTP_CF_REQUEST_URI 'u'
Definition at line 90 of file log-httplog.c.
#define LOG_HTTP_CF_RESPONSE_HEADER 'o'
Definition at line 96 of file log-httplog.c.
#define LOG_HTTP_CF_RESPONSE_LEN 'B'
Definition at line 97 of file log-httplog.c.
#define LOG_HTTP_CF_RESPONSE_STATUS 's'
Definition at line 95 of file log-httplog.c.
#define LOG_HTTP_CF_SERVER_IP 'A'
Definition at line 101 of file log-httplog.c.
#define LOG_HTTP_CF_SERVER_PORT 'P'
Definition at line 103 of file log-httplog.c.
#define LOG_HTTP_CF_TIMESTAMP 't'
Definition at line 98 of file log-httplog.c.
#define LOG_HTTP_CF_TIMESTAMP_U 'z'
Definition at line 99 of file log-httplog.c.
#define LOG_HTTP_CUSTOM 2
Definition at line 120 of file log-httplog.c.
Referenced by LogHttpLogInitCtx().
#define LOG_HTTP_DEFAULT 0
Definition at line 118 of file log-httplog.c.
Referenced by LogHttpLogInitCtx().
#define LOG_HTTP_EXTENDED 1
Definition at line 119 of file log-httplog.c.
Referenced by LogHttpLogInitCtx().
#define LOG_HTTP_MAXN_NODES 64
Definition at line 80 of file log-httplog.c.
Referenced by LogHttpLogInitCtx().
#define LOG_HTTP_NODE_MAXOUTPUTLEN 8192
Definition at line 82 of file log-httplog.c.
Referenced by LogHttpLogInitCtx().
#define LOG_HTTP_NODE_STRLEN 256
Definition at line 81 of file log-httplog.c.
Referenced by LogHttpLogInitCtx().
#define MODULE_NAME "LogHttpLog"
Definition at line 55 of file log-httplog.c.
Referenced by TmModuleLogHttpLogRegister().
#define OUTPUT_BUFFER_SIZE 65535
Definition at line 57 of file log-httplog.c.
Referenced by LogHttpLogThreadInit().
#define TIMESTAMP_DEFAULT_FORMAT "%b %d, %Y; %H:%M:%S"
Definition at line 84 of file log-httplog.c.
Typedef Documentation
typedef struct LogHttpCustomFormatNode_ LogHttpCustomFormatNode
typedef struct LogHttpFileCtx_ LogHttpFileCtx
typedef struct LogHttpLogThread_ LogHttpLogThread
Function Documentation
void LogHttpLogExitPrintStats (ThreadVars * tv, void * data)
Definition at line 578 of file log-httplog.c.
References SCLogInfo, and LogHttpLogThread_::uri_cnt.
Referenced by TmModuleLogHttpLogRegister().
int LogHttpLogger (ThreadVars * tv, void * thread_data, const Packet * p, Flow * f, void * state, void * tx, uint64_t tx_id)
Definition at line 518 of file log-httplog.c.
References PKT_IS_IPV4, PKT_IS_IPV6, PKT_IS_TCP, SCEnter, SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleLogHttpLogRegister().
OutputCtx* LogHttpLogInitCtx (ConfNode * conf)
Create a new http log LogFileCtx.
Parameters
conf Pointer to ConfNode containing this loggers configuration.
Returns
NULL if failure, LogFileCtx* to the file_ctx if succesful
Definition at line 592 of file log-httplog.c.
References ALPROTO_HTTP, AppLayerParserRegisterLogger(), LogHttpFileCtx_::cf_n, LogHttpFileCtx_::cf_nodes, ConfNodeLookupChildValue(), ConfValIsTrue(), OutputCtx_::data, LogHttpCustomFormatNode_::data, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, LogHttpFileCtx_::file_ctx, LogHttpFileCtx_::flags, LOG_HTTP_CF_LITERAL, LOG_HTTP_CUSTOM, LOG_HTTP_DEFAULT, LOG_HTTP_EXTENDED, LOG_HTTP_MAXN_NODES, LOG_HTTP_NODE_MAXOUTPUTLEN, LOG_HTTP_NODE_STRLEN, LogFileFreeCtx(), LogFileNewCtx(), LogHttpCustomFormatNode_::maxlen, SC_ERR_HTTP_LOG_GENERIC, SC_ERR_INVALID_ARGUMENT, SCCalloc, SCConfLogOpenGeneric(), SCFree, SCLogDebug, SCLogError, SCMalloc, strlcpy(), LogHttpCustomFormatNode_::type, and unlikely.
Referenced by TmModuleLogHttpLogRegister().
TmEcode LogHttpLogThreadDeinit (ThreadVars * t, void * data)
Definition at line 563 of file log-httplog.c.
References LogHttpLogThread_::buffer, MemBufferFree(), SCFree, and TM_ECODE_OK.
Referenced by TmModuleLogHttpLogRegister().
TmEcode LogHttpLogThreadInit (ThreadVars * t, void * initdata, void ** data)
Definition at line 536 of file log-httplog.c.
References LogHttpLogThread_::buffer, LogHttpLogThread_::httplog_ctx, MemBufferCreateNew(), OUTPUT_BUFFER_SIZE, SCFree, SCLogDebug, SCMalloc, TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by TmModuleLogHttpLogRegister().
void TmModuleLogHttpLogRegister (void)
Definition at line 66 of file log-httplog.c.
References ALPROTO_HTTP, TmModule_::cap_flags, TmModule_::flags, LogHttpLogExitPrintStats(), LogHttpLogger(), LogHttpLogInitCtx(), LogHttpLogThreadDeinit(), LogHttpLogThreadInit(), MODULE_NAME, TmModule_::name, OutputRegisterTxModule(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_LOGHTTPLOG, and tmm_modules.
Referenced by RegisterAllModules().