suricata: src/log-tcp-data.h File Reference
log-tcp-data.h File Reference
Functions
void TmModuleLogTcpDataLogRegister (void)
OutputCtx * LogTcpDataLogInitCtx (ConfNode *)
Create a new http log LogFileCtx.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file log-tcp-data.h.
Function Documentation
OutputCtx* LogTcpDataLogInitCtx (ConfNode * conf)
Create a new http log LogFileCtx.
Parameters
conf Pointer to ConfNode containing this loggers configuration.
Returns
NULL if failure, LogFileCtx* to the file_ctx if succesful
Definition at line 243 of file log-tcp-data.c.
References ConfigGetLogDirectory(), ConfNodeLookupChildValue(), OutputCtx_::data, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, LogTcpDataFileCtx_::dir, LogTcpDataFileCtx_::file, LogTcpDataFileCtx_::file_ctx, LogTcpDataFileCtx_::log_dir, LogFileFreeCtx(), LogFileNewCtx(), ConfNode_::name, SC_ERR_HTTP_LOG_GENERIC, SC_ERR_INVALID_ARGUMENT, SCCalloc, SCConfLogOpenGeneric(), SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, STREAMING_HTTP_BODIES, STREAMING_TCP_DATA, strlcpy(), LogTcpDataFileCtx_::type, and unlikely.
Referenced by TmModuleLogTcpDataLogRegister().
void TmModuleLogTcpDataLogRegister (void)
Definition at line 63 of file log-tcp-data.c.
References TmModule_::cap_flags, TmModule_::flags, LogTcpDataLogExitPrintStats(), LogTcpDataLogger(), LogTcpDataLogInitCtx(), LogTcpDataLogThreadDeinit(), LogTcpDataLogThreadInit(), MODULE_NAME, TmModule_::name, OutputRegisterStreamingModule(), TmModule_::RegisterTests, STREAMING_HTTP_BODIES, STREAMING_TCP_DATA, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_LOGAPI_TM, TMM_LOGTCPDATALOG, and tmm_modules.
Referenced by RegisterAllModules().