suricata: ptxdump Namespace Reference
ptxdump Namespace Reference
Functions
def FormatCharHex
def CleanFileName
Variables
string header
list out_h = sys.argv[1]
tuple out = open(out_h, 'w')
tuple in_ptx = open(file, 'r')
tuple source = in_ptx.read()
tuple source_len = len(source)
tuple varname = CleanFileName(file)
int newlinecnt = 0
Function Documentation
def ptxdump.CleanFileName (f)
Definition at line 18 of file ptxdump.py.
References len.
def ptxdump.FormatCharHex (d)
Definition at line 12 of file ptxdump.py.
References len.
Variable Documentation
string ptxdump.header
Initial value:
 = '''/* Auto-generated by ptxdump.py DO NOT EDIT
 *
 * This file contains the ptx code of the Cuda kernels.
 * A kernel is identified by its name and the compute capability (e.g. _sm_10).
 */
 '''
Definition at line 5 of file ptxdump.py.
Referenced by HtpRequestBodyHandleMultipart().
tuple ptxdump.in_ptx = open(file, 'r')
Definition at line 38 of file ptxdump.py.
int ptxdump.newlinecnt = 0
Definition at line 45 of file ptxdump.py.
tuple ptxdump.out = open(out_h, 'w')
Definition at line 29 of file ptxdump.py.
Referenced by Base64Encode(), and DecodeTLSHandshakeServerCertificate().
list ptxdump.out_h = sys.argv[1]
Definition at line 28 of file ptxdump.py.
tuple ptxdump.source = in_ptx.read()
Definition at line 39 of file ptxdump.py.
tuple ptxdump.source_len = len(source)
Definition at line 40 of file ptxdump.py.
tuple ptxdump.varname = CleanFileName(file)
Definition at line 42 of file ptxdump.py.
Referenced by DetectFlowintParse(), DetectLoadCompleteSigPath(), and SigLoadSignatures().