suricata: src/output-json.c File Reference
output-json.c File Reference
#include "suricata-common.h"
#include "debug.h"
#include "detect.h"
#include "flow.h"
#include "conf.h"
#include "threads.h"
#include "tm-threads.h"
#include "threadvars.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-reference.h"
#include "app-layer-parser.h"
#include "util-classification-config.h"
#include "util-syslog.h"
#include "output.h"
#include "output-json.h"
#include "util-byte.h"
#include "util-privs.h"
#include "util-print.h"
#include "util-proto-name.h"
#include "util-optimize.h"
#include "util-buffer.h"
#include "util-logopenfile.h"
#include "util-device.h"
Functions
TmEcode OutputJson (ThreadVars *, Packet *, void *, PacketQueue *, PacketQueue *)
TmEcode OutputJsonThreadInit (ThreadVars *, void *, void **)
TmEcode OutputJsonThreadDeinit (ThreadVars *, void *)
int OutputJsonOpenFileCtx (LogFileCtx *, char *)
void OutputJsonRegisterTests (void)
void TmModuleOutputJsonRegister (void)
OutputCtx * OutputJsonInitCtx (ConfNode *conf)
Detailed Description
Author
Tom DeCanio td@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Logs alerts in JSON format.
Definition in file output-json.c.
Function Documentation
TmEcode OutputJson (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
Handle the case where no JSON support is compiled in.
Definition at line 96 of file output-json.c.
References TM_ECODE_OK.
Referenced by TmModuleOutputJsonRegister().
OutputCtx* OutputJsonInitCtx (ConfNode * conf)
Definition at line 84 of file output-json.c.
References SCLogDebug.
int OutputJsonOpenFileCtx (LogFileCtx * , char *)
void OutputJsonRegisterTests (void)
Definition at line 106 of file output-json.c.
Referenced by TmModuleOutputJsonRegister().
TmEcode OutputJsonThreadDeinit (ThreadVars * t, void * data)
Definition at line 101 of file output-json.c.
References TM_ECODE_FAILED.
Referenced by TmModuleOutputJsonRegister().
TmEcode OutputJsonThreadInit (ThreadVars * t, void * initdata, void ** data)
Definition at line 90 of file output-json.c.
References SCLogDebug, and TM_ECODE_FAILED.
Referenced by TmModuleJsonAlertLogRegister(), TmModuleJsonDnsLogRegister(), TmModuleJsonDropLogRegister(), TmModuleJsonFileLogRegister(), TmModuleJsonFlowLogRegister(), TmModuleJsonHttpLogRegister(), TmModuleJsonNetFlowLogRegister(), TmModuleJsonSmtpLogRegister(), TmModuleJsonSshLogRegister(), TmModuleJsonStatsLogRegister(), TmModuleJsonTlsLogRegister(), and TmModuleOutputJsonRegister().
void TmModuleOutputJsonRegister (void)
Definition at line 75 of file output-json.c.
References TmModule_::Func, TmModule_::name, OutputJson(), OutputJsonRegisterTests(), OutputJsonThreadDeinit(), OutputJsonThreadInit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadInit, tmm_modules, and TMM_OUTPUTJSON.
Referenced by RegisterAllModules().