suricata: src/output-packet.c File Reference
output-packet.c File Reference
#include "suricata-common.h"
#include "tm-modules.h"
#include "output-packet.h"
#include "util-profiling.h"
Data Structures
struct OutputLoggerThreadStore_
struct OutputLoggerThreadData_
struct OutputPacketLogger_
Typedefs
typedef struct
OutputLoggerThreadStore_ OutputLoggerThreadStore
typedef struct
OutputLoggerThreadData_ OutputLoggerThreadData
typedef struct OutputPacketLogger_ OutputPacketLogger
Functions
int OutputRegisterPacketLogger (const char *name, PacketLogger LogFunc, PacketLogCondition ConditionFunc, OutputCtx *output_ctx)
void TmModulePacketLoggerRegister (void)
void OutputPacketShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Packet Logger Output registration functions
Definition in file output-packet.c.
Typedef Documentation
typedef struct OutputLoggerThreadData_ OutputLoggerThreadData
per thread data for this module, contains a list of per thread data for the packet loggers.
typedef struct OutputLoggerThreadStore_ OutputLoggerThreadStore
typedef struct OutputPacketLogger_ OutputPacketLogger
Function Documentation
void OutputPacketShutdown (void)
Definition at line 230 of file output-packet.c.
References OutputPacketLogger_::next, and SCFree.
Referenced by RunModeShutDown().
int OutputRegisterPacketLogger (const char * name, PacketLogger LogFunc, PacketLogCondition ConditionFunc, OutputCtx * output_ctx)
Definition at line 56 of file output-packet.c.
References OutputPacketLogger_::ConditionFunc, OutputPacketLogger_::LogFunc, OutputPacketLogger_::module_id, OutputPacketLogger_::name, OutputPacketLogger_::next, OutputPacketLogger_::output_ctx, SCLogDebug, SCMalloc, and TmModuleGetIdByName().
void TmModulePacketLoggerRegister (void)
Definition at line 220 of file output-packet.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, tmm_modules, and TMM_PACKETLOGGER.
Referenced by RegisterAllModules().