suricata: src/output-tx.h File Reference
output-tx.h File Reference
#include "decode.h"
Typedefs
typedef int(* TxLogger)(ThreadVars *, void *thread_data, const Packet *, Flow *f, void *state, void *tx, uint64_t tx_id)
Functions
int OutputRegisterTxLogger (const char *name, AppProto alproto, TxLogger LogFunc, OutputCtx *)
void TmModuleTxLoggerRegister (void)
void OutputTxShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
AppLayer TX Logger Output registration functions
Definition in file output-tx.h.
Typedef Documentation
typedef int(* TxLogger)(ThreadVars *, void *thread_data, const Packet *, Flow *f, void *state, void *tx, uint64_t tx_id)
packet logger function pointer type
Definition at line 32 of file output-tx.h.
Function Documentation
int OutputRegisterTxLogger (const char * name, AppProto alproto, TxLogger LogFunc, OutputCtx *)
packet logger condition function pointer type, must return true for packets that should be logged
Definition at line 58 of file output-tx.c.
References OutputTxLogger_::alproto, OutputTxLogger_::LogFunc, OutputTxLogger_::module_id, OutputTxLogger_::name, OutputTxLogger_::next, OutputTxLogger_::output_ctx, SCLogDebug, SCMalloc, and TmModuleGetIdByName().
void OutputTxShutdown (void)
Definition at line 299 of file output-tx.c.
References OutputTxLogger_::next, and SCFree.
Referenced by RunModeShutDown().
void TmModuleTxLoggerRegister (void)
Definition at line 289 of file output-tx.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, tmm_modules, and TMM_TXLOGGER.
Referenced by RegisterAllModules().