suricata: src/output-file.c File Reference
output-file.c File Reference
#include "suricata-common.h"
#include "tm-modules.h"
#include "output-file.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "detect-filemagic.h"
#include "util-profiling.h"
Data Structures
struct OutputLoggerThreadStore_
struct OutputLoggerThreadData_
struct OutputFileLogger_
Typedefs
typedef struct
OutputLoggerThreadStore_ OutputLoggerThreadStore
typedef struct
OutputLoggerThreadData_ OutputLoggerThreadData
typedef struct OutputFileLogger_ OutputFileLogger
Functions
int OutputRegisterFileLogger (const char *name, FileLogger LogFunc, OutputCtx *output_ctx)
void TmModuleFileLoggerRegister (void)
void OutputFileShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
AppLayer File Logger Output registration functions
Definition in file output-file.c.
Typedef Documentation
typedef struct OutputFileLogger_ OutputFileLogger
typedef struct OutputLoggerThreadData_ OutputLoggerThreadData
per thread data for this module, contains a list of per thread data for the packet loggers.
typedef struct OutputLoggerThreadStore_ OutputLoggerThreadStore
Function Documentation
void OutputFileShutdown (void)
Definition at line 288 of file output-file.c.
References OutputFileLogger_::next, and SCFree.
Referenced by RunModeShutDown().
int OutputRegisterFileLogger (const char * name, FileLogger LogFunc, OutputCtx *)
packet logger condition function pointer type, must return true for packets that should be logged
Definition at line 58 of file output-file.c.
References OutputFileLogger_::LogFunc, OutputFileLogger_::module_id, OutputFileLogger_::name, OutputFileLogger_::next, OutputFileLogger_::output_ctx, SCLogDebug, SCMalloc, and TmModuleGetIdByName().
void TmModuleFileLoggerRegister (void)
Definition at line 278 of file output-file.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TMM_FILELOGGER, and tmm_modules.
Referenced by RegisterAllModules().