suricata: src/output-filedata.c File Reference
output-filedata.c File Reference
#include "suricata-common.h"
#include "tm-modules.h"
#include "output-filedata.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "detect-filemagic.h"
#include "conf.h"
#include "util-profiling.h"
Data Structures
struct OutputLoggerThreadStore_
struct OutputLoggerThreadData_
struct OutputFiledataLogger_
Typedefs
typedef struct
OutputLoggerThreadStore_ OutputLoggerThreadStore
typedef struct
OutputLoggerThreadData_ OutputLoggerThreadData
typedef struct
OutputFiledataLogger_ OutputFiledataLogger
Functions
int OutputRegisterFiledataLogger (const char *name, FiledataLogger LogFunc, OutputCtx *output_ctx)
SC_ATOMIC_DECLARE (unsigned int, file_id)
void TmModuleFiledataLoggerRegister (void)
void OutputFiledataShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
AppLayer Filedata Logger Output registration functions
Definition in file output-filedata.c.
Typedef Documentation
typedef struct OutputFiledataLogger_ OutputFiledataLogger
typedef struct OutputLoggerThreadData_ OutputLoggerThreadData
per thread data for this module, contains a list of per thread data for the packet loggers.
typedef struct OutputLoggerThreadStore_ OutputLoggerThreadStore
Function Documentation
void OutputFiledataShutdown (void)
Definition at line 475 of file output-filedata.c.
References OutputFiledataLogger_::next, and SCFree.
Referenced by RunModeShutDown().
int OutputRegisterFiledataLogger (const char * name, FiledataLogger LogFunc, OutputCtx *)
packet logger condition function pointer type, must return true for packets that should be logged
Definition at line 63 of file output-filedata.c.
References OutputFiledataLogger_::LogFunc, OutputFiledataLogger_::module_id, OutputFiledataLogger_::name, OutputFiledataLogger_::next, OutputFiledataLogger_::output_ctx, SCLogDebug, SCMalloc, and TmModuleGetIdByName().
SC_ATOMIC_DECLARE (unsigned int, file_id)
void TmModuleFiledataLoggerRegister (void)
Definition at line 463 of file output-filedata.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, SC_ATOMIC_INIT, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TMM_FILEDATALOGGER, and tmm_modules.
Referenced by RegisterAllModules().