suricata: src/output-filedata.h File Reference
output-filedata.h File Reference
#include "decode.h"
#include "util-file.h"
Macros
#define OUTPUT_FILEDATA_FLAG_OPEN 0x01
#define OUTPUT_FILEDATA_FLAG_CLOSE 0x02
Typedefs
typedef int(* FiledataLogger)(ThreadVars *, void *thread_data, const Packet *, const File *, const FileData *, uint8_t)
Functions
int OutputRegisterFiledataLogger (const char *name, FiledataLogger LogFunc, OutputCtx *)
void TmModuleFiledataLoggerRegister (void)
void OutputFiledataShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
AppLayer Filedata Logger Output registration functions
Definition in file output-filedata.h.
Macro Definition Documentation
#define OUTPUT_FILEDATA_FLAG_CLOSE 0x02
Definition at line 33 of file output-filedata.h.
#define OUTPUT_FILEDATA_FLAG_OPEN 0x01
Definition at line 32 of file output-filedata.h.
Typedef Documentation
typedef int(* FiledataLogger)(ThreadVars *, void *thread_data, const Packet *, const File *, const FileData *, uint8_t)
filedata logger function pointer type
Definition at line 36 of file output-filedata.h.
Function Documentation
void OutputFiledataShutdown (void)
Definition at line 475 of file output-filedata.c.
References OutputFiledataLogger_::next, and SCFree.
Referenced by RunModeShutDown().
int OutputRegisterFiledataLogger (const char * name, FiledataLogger LogFunc, OutputCtx *)
packet logger condition function pointer type, must return true for packets that should be logged
Definition at line 63 of file output-filedata.c.
References OutputFiledataLogger_::LogFunc, OutputFiledataLogger_::module_id, OutputFiledataLogger_::name, OutputFiledataLogger_::next, OutputFiledataLogger_::output_ctx, SCLogDebug, SCMalloc, and TmModuleGetIdByName().
void TmModuleFiledataLoggerRegister (void)
Definition at line 463 of file output-filedata.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, SC_ATOMIC_INIT, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TMM_FILEDATALOGGER, and tmm_modules.
Referenced by RegisterAllModules().