suricata: src/output-packet.h File Reference
output-packet.h File Reference
#include "decode.h"
Typedefs
typedef int(* PacketLogger)(ThreadVars *, void *thread_data, const Packet *)
typedef int(* PacketLogCondition)(ThreadVars *, const Packet *)
Functions
int OutputRegisterPacketLogger (const char *name, PacketLogger LogFunc, PacketLogCondition ConditionFunc, OutputCtx *)
void TmModulePacketLoggerRegister (void)
void OutputPacketShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Packet Logger Output registration functions
Definition in file output-packet.h.
Typedef Documentation
typedef int(* PacketLogCondition)(ThreadVars *, const Packet *)
packet logger condition function pointer type, must return true for packets that should be logged
Definition at line 37 of file output-packet.h.
typedef int(* PacketLogger)(ThreadVars *, void *thread_data, const Packet *)
packet logger function pointer type
Definition at line 32 of file output-packet.h.
Function Documentation
void OutputPacketShutdown (void)
Definition at line 230 of file output-packet.c.
References OutputPacketLogger_::next, and SCFree.
Referenced by RunModeShutDown().
int OutputRegisterPacketLogger (const char * name, PacketLogger LogFunc, PacketLogCondition ConditionFunc, OutputCtx *)
Definition at line 56 of file output-packet.c.
References OutputPacketLogger_::ConditionFunc, OutputPacketLogger_::LogFunc, OutputPacketLogger_::module_id, OutputPacketLogger_::name, OutputPacketLogger_::next, OutputPacketLogger_::output_ctx, SCLogDebug, SCMalloc, and TmModuleGetIdByName().
void TmModulePacketLoggerRegister (void)
Definition at line 220 of file output-packet.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, tmm_modules, and TMM_PACKETLOGGER.
Referenced by RegisterAllModules().