suricata: src/output.c File Reference
output.c File Reference
#include "suricata-common.h"
#include "flow.h"
#include "conf.h"
#include "tm-threads.h"
#include "util-error.h"
#include "util-debug.h"
#include "output.h"
Functions
TAILQ_HEAD (OutputFileRolloverFlag_)
void OutputRegisterPacketModule (const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *), PacketLogger PacketLogFunc, PacketLogCondition PacketConditionFunc)
Register a packet output module.
void OutputRegisterPacketSubModule (const char *parent_name, const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *, OutputCtx *parent_ctx), PacketLogger PacketLogFunc, PacketLogCondition PacketConditionFunc)
Register a packet output sub-module.
void OutputRegisterTxModule (const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *), AppProto alproto, TxLogger TxLogFunc)
Register a tx output module.
void OutputRegisterTxSubModule (const char *parent_name, const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *, OutputCtx *parent_ctx), AppProto alproto, TxLogger TxLogFunc)
void OutputRegisterFileModule (const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *), FileLogger FileLogFunc)
Register a file output module.
void OutputRegisterFileSubModule (const char *parent_name, const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *, OutputCtx *), FileLogger FileLogFunc)
Register a file output sub-module.
void OutputRegisterFiledataModule (const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *), FiledataLogger FiledataLogFunc)
Register a file data output module.
void OutputRegisterFiledataSubModule (const char *parent_name, const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *, OutputCtx *), FiledataLogger FiledataLogFunc)
Register a file data output sub-module.
void OutputRegisterFlowModule (const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *), FlowLogger FlowLogFunc)
Register a flow output module.
void OutputRegisterFlowSubModule (const char *parent_name, const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *, OutputCtx *), FlowLogger FlowLogFunc)
Register a flow output sub-module.
void OutputRegisterStreamingModule (const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *), StreamingLogger StreamingLogFunc, enum OutputStreamingType stream_type)
Register a streaming data output module.
void OutputRegisterStreamingSubModule (const char *parent_name, const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *, OutputCtx *), StreamingLogger StreamingLogFunc, enum OutputStreamingType stream_type)
Register a streaming data output sub-module.
void OutputRegisterStatsModule (const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *), StatsLogger StatsLogFunc)
Register a stats data output module.
void OutputRegisterStatsSubModule (const char *parent_name, const char *name, const char *conf_name, OutputCtx *(*InitFunc)(ConfNode *, OutputCtx *), StatsLogger StatsLogFunc)
Register a stats data output sub-module.
OutputModule * OutputGetModuleByConfName (const char *conf_name)
Get an output module by name.
void OutputDeregisterAll (void)
Deregister all modules. Useful for a memory clean exit.
int OutputDropLoggerEnable (void)
void OutputDropLoggerDisable (void)
int OutputTlsLoggerEnable (void)
void OutputTlsLoggerDisable (void)
int OutputSshLoggerEnable (void)
void OutputSshLoggerDisable (void)
void OutputRegisterFileRotationFlag (int *flag)
Register a flag for file rotation notification.
void OutputUnregisterFileRotationFlag (int *flag)
Unregister a file rotation flag.
void OutputNotifyFileRotation (void)
Notifies all registered file rotation notification flags.
Variables
OutputFileRolloverFlag
Detailed Description
Author
Endace Technology Limited, Jason Ish jason.nosp@m..ish.nosp@m.@enda.nosp@m.ce.c.nosp@m.om
Output registration functions
Definition in file output.c.
Function Documentation
void OutputDeregisterAll (void)
Deregister all modules. Useful for a memory clean exit.
Definition at line 593 of file output.c.
References SCFree, TAILQ_FIRST, and TAILQ_REMOVE.
Referenced by main().
void OutputDropLoggerDisable (void)
Definition at line 613 of file output.c.
int OutputDropLoggerEnable (void)
Definition at line 605 of file output.c.
OutputModule* OutputGetModuleByConfName (const char * conf_name)
Get an output module by name.
Return values
The OutputModule with the given name or NULL if no output module with the given name is registered.
Definition at line 577 of file output.c.
References OutputModule_::conf_name, and TAILQ_FOREACH.
Referenced by RunModeInitializeOutputs().
void OutputNotifyFileRotation (void)
Notifies all registered file rotation notification flags.
Definition at line 696 of file output.c.
References OutputFileRolloverFlag, and TAILQ_FOREACH.
Referenced by main().
void OutputRegisterFiledataModule (const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *) InitFunc, FiledataLogger FiledataLogFunc)
Register a file data output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 296 of file output.c.
References OutputModule_::conf_name, OutputModule_::FiledataLogFunc, OutputModule_::InitFunc, OutputModule_::name, OutputTxLogger_::name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
Referenced by TmModuleLogFilestoreRegister().
void OutputRegisterFiledataSubModule (const char * parent_name, const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *, OutputCtx *) InitFunc, FiledataLogger FiledataLogFunc)
Register a file data output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 330 of file output.c.
References OutputModule_::conf_name, OutputModule_::FiledataLogFunc, OutputModule_::InitSubFunc, OutputModule_::name, OutputTxLogger_::name, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
void OutputRegisterFileModule (const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *) InitFunc, FileLogger FileLogFunc)
Register a file output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 226 of file output.c.
References OutputModule_::conf_name, OutputModule_::FileLogFunc, OutputModule_::InitFunc, OutputModule_::name, OutputTxLogger_::name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
Referenced by TmModuleLogFileLogRegister().
void OutputRegisterFileRotationFlag (int * flag)
Register a flag for file rotation notification.
Parameters
flag A pointer that will be set to 1 when file rotation is requested.
Definition at line 657 of file output.c.
References OutputFileRolloverFlag, SC_ERR_MEM_ALLOC, SCCalloc, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
Referenced by SCConfLogOpenGeneric().
void OutputRegisterFileSubModule (const char * parent_name, const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *, OutputCtx *) InitFunc, FileLogger FileLogFunc)
Register a file output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 260 of file output.c.
References OutputModule_::conf_name, OutputModule_::FileLogFunc, OutputModule_::InitSubFunc, OutputModule_::name, OutputTxLogger_::name, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
void OutputRegisterFlowModule (const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *) InitFunc, FlowLogger FlowLogFunc)
Register a flow output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 366 of file output.c.
References OutputModule_::conf_name, OutputModule_::FlowLogFunc, OutputModule_::InitFunc, OutputModule_::name, OutputTxLogger_::name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
void OutputRegisterFlowSubModule (const char * parent_name, const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *, OutputCtx *) InitFunc, FlowLogger FlowLogFunc)
Register a flow output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 400 of file output.c.
References OutputModule_::conf_name, OutputModule_::FlowLogFunc, OutputModule_::InitSubFunc, OutputModule_::name, OutputTxLogger_::name, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
void OutputRegisterPacketModule (const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *) InitFunc, PacketLogger PacketLogFunc, PacketLogCondition PacketConditionFunc)
Register a packet output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 88 of file output.c.
References OutputModule_::conf_name, OutputModule_::InitFunc, OutputModule_::name, OutputTxLogger_::name, OutputModule_::PacketConditionFunc, OutputModule_::PacketLogFunc, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
Referenced by TmModuleAlertDebugLogRegister(), TmModuleAlertFastLogRegister(), TmModuleAlertPreludeRegister(), TmModuleAlertSyslogRegister(), TmModuleLogDropLogRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), and TmModuleUnified2AlertRegister().
void OutputRegisterPacketSubModule (const char * parent_name, const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *, OutputCtx *parent_ctx) InitFunc, PacketLogger PacketLogFunc, PacketLogCondition PacketConditionFunc)
Register a packet output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 124 of file output.c.
References OutputModule_::conf_name, OutputModule_::InitSubFunc, OutputModule_::name, OutputTxLogger_::name, OutputModule_::PacketConditionFunc, OutputModule_::PacketLogFunc, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
void OutputRegisterStatsModule (const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *) InitFunc, StatsLogger StatsLogFunc)
Register a stats data output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 509 of file output.c.
References OutputModule_::conf_name, OutputModule_::InitFunc, OutputModule_::name, OutputTxLogger_::name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, OutputModule_::StatsLogFunc, TAILQ_INSERT_TAIL, and unlikely.
Referenced by TmModuleLogStatsLogRegister().
void OutputRegisterStatsSubModule (const char * parent_name, const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *, OutputCtx *) InitFunc, StatsLogger StatsLogFunc)
Register a stats data output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 543 of file output.c.
References OutputModule_::conf_name, OutputModule_::InitSubFunc, OutputModule_::name, OutputTxLogger_::name, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, OutputModule_::StatsLogFunc, TAILQ_INSERT_TAIL, and unlikely.
void OutputRegisterStreamingModule (const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *) InitFunc, StreamingLogger StreamingLogFunc, enum OutputStreamingType stream_type)
Register a streaming data output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 436 of file output.c.
References OutputModule_::conf_name, OutputModule_::InitFunc, OutputModule_::name, OutputTxLogger_::name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, OutputModule_::stream_type, OutputModule_::StreamingLogFunc, TAILQ_INSERT_TAIL, and unlikely.
Referenced by TmModuleLogTcpDataLogRegister().
void OutputRegisterStreamingSubModule (const char * parent_name, const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *, OutputCtx *) InitFunc, StreamingLogger StreamingLogFunc, enum OutputStreamingType stream_type)
Register a streaming data output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 472 of file output.c.
References OutputModule_::conf_name, OutputModule_::InitSubFunc, OutputModule_::name, OutputTxLogger_::name, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, OutputModule_::stream_type, OutputModule_::StreamingLogFunc, TAILQ_INSERT_TAIL, and unlikely.
void OutputRegisterTxModule (const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *) InitFunc, AppProto alproto, TxLogger TxLogFunc)
Register a tx output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 161 of file output.c.
References OutputTxLogger_::alproto, OutputModule_::alproto, OutputModule_::conf_name, OutputModule_::InitFunc, OutputModule_::name, OutputTxLogger_::name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, OutputModule_::TxLogFunc, and unlikely.
Referenced by TmModuleLogDnsLogRegister(), and TmModuleLogHttpLogRegister().
void OutputRegisterTxSubModule (const char * parent_name, const char * name, const char * conf_name, OutputCtx *(*)(ConfNode *, OutputCtx *parent_ctx) InitFunc, AppProto alproto, TxLogger TxLogFunc)
Definition at line 189 of file output.c.
References OutputTxLogger_::alproto, OutputModule_::alproto, OutputModule_::conf_name, OutputModule_::InitSubFunc, OutputModule_::name, OutputTxLogger_::name, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, OutputModule_::TxLogFunc, and unlikely.
void OutputSshLoggerDisable (void)
Definition at line 645 of file output.c.
int OutputSshLoggerEnable (void)
Definition at line 637 of file output.c.
void OutputTlsLoggerDisable (void)
Definition at line 629 of file output.c.
int OutputTlsLoggerEnable (void)
Definition at line 621 of file output.c.
void OutputUnregisterFileRotationFlag (int * flag)
Unregister a file rotation flag.
Note that it is safe to call this function with a flag that may not have been registered, in which case this function won't do anything.
Parameters
flag A pointer that has been previously registered for file rotation notifications.
Definition at line 679 of file output.c.
References next, OutputFileRolloverFlag, SCFree, TAILQ_FIRST, TAILQ_NEXT, and TAILQ_REMOVE.
Referenced by LogFileFreeCtx().
TAILQ_HEAD (OutputFileRolloverFlag_)
Definition at line 46 of file output.c.
References OutputModule_::conf_name, OutputModule_::InitFunc, OutputModule_::name, OutputTxLogger_::name, SC_ERR_FATAL, SCCalloc, SCLogDebug, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
Variable Documentation
OutputFileRolloverFlag
Definition at line 44 of file output.c.
Referenced by OutputNotifyFileRotation(), OutputRegisterFileRotationFlag(), and OutputUnregisterFileRotationFlag().