suricata: src/output-streaming.c File Reference
output-streaming.c File Reference
#include "suricata-common.h"
#include "tm-modules.h"
#include "output-streaming.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "util-print.h"
#include "conf.h"
#include "util-profiling.h"
Data Structures
struct OutputLoggerThreadStore_
struct OutputLoggerThreadData_
struct OutputStreamingLogger_
struct StreamerCallbackData_
Typedefs
typedef struct
OutputLoggerThreadStore_ OutputLoggerThreadStore
typedef struct
OutputLoggerThreadData_ OutputLoggerThreadData
typedef struct
OutputStreamingLogger_ OutputStreamingLogger
typedef struct
StreamerCallbackData_ StreamerCallbackData
Functions
int OutputRegisterStreamingLogger (const char *name, StreamingLogger LogFunc, OutputCtx *output_ctx, enum OutputStreamingType type)
int Streamer (void *cbdata, Flow *f, uint8_t *data, uint32_t data_len, uint64_t tx_id, uint8_t flags)
int HttpBodyIterator (Flow *f, int close, void *cbdata, uint8_t iflags)
Http Body Iterator for logging.
int StreamIterator (Flow *f, TcpStream *stream, int close, void *cbdata, uint8_t iflags)
void TmModuleStreamingLoggerRegister (void)
void OutputStreamingShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Logger for streaming data
Definition in file output-streaming.c.
Typedef Documentation
typedef struct OutputLoggerThreadData_ OutputLoggerThreadData
per thread data for this module, contains a list of per thread data for the packet loggers.
typedef struct OutputLoggerThreadStore_ OutputLoggerThreadStore
typedef struct OutputStreamingLogger_ OutputStreamingLogger
typedef struct StreamerCallbackData_ StreamerCallbackData
Function Documentation
int HttpBodyIterator (Flow * f, int close, void * cbdata, uint8_t iflags)
Http Body Iterator for logging.
Global logic:
For each tx
For each body chunk
Invoke Streamer
Definition at line 143 of file output-streaming.c.
References Flow_::alproto, ALPROTO_HTTP, Flow_::alstate, AppLayerParserGetStateProgress(), AppLayerParserGetStateProgressCompletionStatus(), AppLayerParserGetTx(), AppLayerParserGetTxCnt(), HtpState_::conn, HtpBodyChunk_::data, HtpBody_::first, flags, FlowGetDisruptionFlags(), htp_tx_get_user_data(), HtpBody_::last, HtpBodyChunk_::len, HtpBodyChunk_::logged, HtpBodyChunk_::next, next, OUTPUT_STREAMING_FLAG_CLOSE, OUTPUT_STREAMING_FLAG_OPEN, OUTPUT_STREAMING_FLAG_TOCLIENT, OUTPUT_STREAMING_FLAG_TOSERVER, OUTPUT_STREAMING_FLAG_TRANSACTION, Flow_::proto, HtpTxUserData_::request_body, HtpTxUserData_::response_body, SCLogDebug, HtpBodyChunk_::stream_offset, STREAM_TOCLIENT, STREAM_TOSERVER, Streamer(), and tx_id.
int OutputRegisterStreamingLogger (const char * name, StreamingLogger LogFunc, OutputCtx * output_ctx, enum OutputStreamingType type)
Definition at line 62 of file output-streaming.c.
References OutputStreamingLogger_::LogFunc, OutputStreamingLogger_::module_id, OutputStreamingLogger_::name, OutputStreamingLogger_::next, OutputStreamingLogger_::output_ctx, SCLogDebug, SCMalloc, TmModuleGetIdByName(), type, and OutputStreamingLogger_::type.
void OutputStreamingShutdown (void)
Definition at line 460 of file output-streaming.c.
References OutputStreamingLogger_::next, and SCFree.
Referenced by RunModeShutDown().
int Streamer (void * cbdata, Flow * f, uint8_t * data, uint32_t data_len, uint64_t tx_id, uint8_t flags)
Definition at line 101 of file output-streaming.c.
References BUG_ON, OutputStreamingLogger_::LogFunc, StreamerCallbackData_::logger, OutputStreamingLogger_::module_id, OutputLoggerThreadStore_::next, OutputStreamingLogger_::next, StreamerCallbackData_::p, PACKET_PROFILING_TMM_END, PACKET_PROFILING_TMM_START, SCLogDebug, StreamerCallbackData_::store, OutputLoggerThreadStore_::thread_data, StreamerCallbackData_::tv, OutputStreamingLogger_::type, and StreamerCallbackData_::type.
Referenced by HttpBodyIterator(), and StreamIterator().
int StreamIterator (Flow * f, TcpStream * stream, int close, void * cbdata, uint8_t iflags)
Definition at line 240 of file output-streaming.c.
References flags, TcpSegment_::flags, TcpStream_::isn, TcpStream_::last_ack, logged, TcpSegment_::next, OUTPUT_STREAMING_FLAG_CLOSE, OUTPUT_STREAMING_FLAG_OPEN, TcpSegment_::payload, TcpSegment_::payload_len, SCLogDebug, TcpStream_::seg_list, TcpStream_::seg_list_tail, SEGMENTTCP_FLAG_LOGAPI_PROCESSED, TcpSegment_::seq, SEQ_GT, and Streamer().
void TmModuleStreamingLoggerRegister (void)
Definition at line 451 of file output-streaming.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, tmm_modules, and TMM_STREAMINGLOGGER.
Referenced by RegisterAllModules().