suricata: src/output-stats.c File Reference
output-stats.c File Reference
#include "suricata-common.h"
#include "tm-modules.h"
#include "output-stats.h"
Data Structures
struct OutputLoggerThreadStore_
struct OutputLoggerThreadData_
struct OutputStatsLogger_
Typedefs
typedef struct
OutputLoggerThreadStore_ OutputLoggerThreadStore
typedef struct
OutputLoggerThreadData_ OutputLoggerThreadData
typedef struct OutputStatsLogger_ OutputStatsLogger
Functions
int OutputRegisterStatsLogger (const char *name, StatsLogger LogFunc, OutputCtx *output_ctx)
TmEcode OutputStatsLog (ThreadVars *tv, void *thread_data, StatsTable *st)
void TmModuleStatsLoggerRegister (void)
int OutputStatsLoggersRegistered (void)
void OutputStatsShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Stats Logger Output registration functions
Definition in file output-stats.c.
Typedef Documentation
typedef struct OutputLoggerThreadData_ OutputLoggerThreadData
per thread data for this module, contains a list of per thread data for the packet loggers.
typedef struct OutputLoggerThreadStore_ OutputLoggerThreadStore
typedef struct OutputStatsLogger_ OutputStatsLogger
Function Documentation
int OutputRegisterStatsLogger (const char * name, StatsLogger LogFunc, OutputCtx * output_ctx)
Definition at line 54 of file output-stats.c.
References OutputStatsLogger_::LogFunc, OutputStatsLogger_::module_id, OutputStatsLogger_::name, OutputStatsLogger_::next, OutputStatsLogger_::output_ctx, SCLogDebug, SCMalloc, and TmModuleGetIdByName().
TmEcode OutputStatsLog (ThreadVars * tv, void * thread_data, StatsTable * st)
Definition at line 83 of file output-stats.c.
References BUG_ON, OutputStatsLogger_::LogFunc, OutputLoggerThreadStore_::next, OutputStatsLogger_::next, OutputLoggerThreadData_::store, OutputLoggerThreadStore_::thread_data, and TM_ECODE_OK.
int OutputStatsLoggersRegistered (void)
Definition at line 225 of file output-stats.c.
void OutputStatsShutdown (void)
Definition at line 232 of file output-stats.c.
References OutputStatsLogger_::next, and SCFree.
Referenced by RunModeShutDown().
void TmModuleStatsLoggerRegister (void)
Definition at line 215 of file output-stats.c.
References TmModule_::cap_flags, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, tmm_modules, and TMM_STATSLOGGER.
Referenced by RegisterAllModules().