suricata: src/output-file.h File Reference
output-file.h File Reference
#include "decode.h"
#include "util-file.h"
Typedefs
typedef int(* FileLogger)(ThreadVars *, void *thread_data, const Packet *, const File *)
Functions
int OutputRegisterFileLogger (const char *name, FileLogger LogFunc, OutputCtx *)
void TmModuleFileLoggerRegister (void)
void OutputFileShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
AppLayer File Logger Output registration functions
Definition in file output-file.h.
Typedef Documentation
typedef int(* FileLogger)(ThreadVars *, void *thread_data, const Packet *, const File *)
packet logger function pointer type
Definition at line 33 of file output-file.h.
Function Documentation
void OutputFileShutdown (void)
Definition at line 288 of file output-file.c.
References OutputFileLogger_::next, and SCFree.
Referenced by RunModeShutDown().
int OutputRegisterFileLogger (const char * name, FileLogger LogFunc, OutputCtx *)
packet logger condition function pointer type, must return true for packets that should be logged
Definition at line 58 of file output-file.c.
References OutputFileLogger_::LogFunc, OutputFileLogger_::module_id, OutputFileLogger_::name, OutputFileLogger_::next, OutputFileLogger_::output_ctx, SCLogDebug, SCMalloc, and TmModuleGetIdByName().
void TmModuleFileLoggerRegister (void)
Definition at line 278 of file output-file.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TMM_FILELOGGER, and tmm_modules.
Referenced by RegisterAllModules().