suricata: src/output-flow.c File Reference
output-flow.c File Reference
#include "suricata-common.h"
#include "tm-modules.h"
#include "output-flow.h"
#include "util-profiling.h"
Data Structures
struct OutputLoggerThreadStore_
struct OutputLoggerThreadData_
struct OutputFlowLogger_
Typedefs
typedef struct
OutputLoggerThreadStore_ OutputLoggerThreadStore
typedef struct
OutputLoggerThreadData_ OutputLoggerThreadData
typedef struct OutputFlowLogger_ OutputFlowLogger
Functions
int OutputRegisterFlowLogger (const char *name, FlowLogger LogFunc, OutputCtx *output_ctx)
TmEcode OutputFlowLog (ThreadVars *tv, void *thread_data, Flow *f)
Run flow logger(s)
TmEcode OutputFlowLogThreadInit (ThreadVars *tv, void *initdata, void **data)
thread init for the flow logger This will run the thread init functions for the individual registered loggers
TmEcode OutputFlowLogThreadDeinit (ThreadVars *tv, void *thread_data)
void OutputFlowLogExitPrintStats (ThreadVars *tv, void *thread_data)
void OutputFlowShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Flow Logger Output registration functions
Definition in file output-flow.c.
Typedef Documentation
typedef struct OutputFlowLogger_ OutputFlowLogger
typedef struct OutputLoggerThreadData_ OutputLoggerThreadData
per thread data for this module, contains a list of per thread data for the packet loggers.
typedef struct OutputLoggerThreadStore_ OutputLoggerThreadStore
Function Documentation
TmEcode OutputFlowLog (ThreadVars * tv, void * thread_data, Flow * f)
Run flow logger(s)
Note
flow is already write locked
Definition at line 87 of file output-flow.c.
References BUG_ON, OutputFlowLogger_::LogFunc, OutputLoggerThreadStore_::next, OutputFlowLogger_::next, SCLogDebug, OutputLoggerThreadData_::store, OutputLoggerThreadStore_::thread_data, and TM_ECODE_OK.
void OutputFlowLogExitPrintStats (ThreadVars * tv, void * thread_data)
Definition at line 203 of file output-flow.c.
References OutputFlowLogger_::name, OutputLoggerThreadStore_::next, OutputFlowLogger_::next, SC_ERR_INVALID_ARGUMENT, SCLogError, OutputLoggerThreadData_::store, OutputLoggerThreadStore_::thread_data, TmModule_::ThreadExitPrintStats, and TmModuleGetByName().
TmEcode OutputFlowLogThreadDeinit (ThreadVars * tv, void * thread_data)
Definition at line 175 of file output-flow.c.
References OutputFlowLogger_::name, OutputLoggerThreadStore_::next, OutputFlowLogger_::next, SC_ERR_INVALID_ARGUMENT, SCFree, SCLogError, OutputLoggerThreadData_::store, OutputLoggerThreadStore_::thread_data, TmModule_::ThreadDeinit, TM_ECODE_OK, and TmModuleGetByName().
Referenced by DecodeThreadVarsFree().
TmEcode OutputFlowLogThreadInit (ThreadVars * tv, void * initdata, void ** data)
thread init for the flow logger This will run the thread init functions for the individual registered loggers
Definition at line 126 of file output-flow.c.
References BUG_ON, OutputFlowLogger_::name, OutputLoggerThreadStore_::next, OutputFlowLogger_::next, OutputFlowLogger_::output_ctx, SC_ERR_INVALID_ARGUMENT, SCLogDebug, SCLogError, SCMalloc, OutputLoggerThreadData_::store, OutputLoggerThreadStore_::thread_data, TmModule_::ThreadInit, TM_ECODE_FAILED, TM_ECODE_OK, TmModuleGetByName(), and ts.
Referenced by DecodeThreadVarsAlloc().
void OutputFlowShutdown (void)
Definition at line 226 of file output-flow.c.
References OutputFlowLogger_::next, and SCFree.
Referenced by RunModeShutDown().
int OutputRegisterFlowLogger (const char * name, FlowLogger LogFunc, OutputCtx *)
packet logger condition function pointer type, must return true for packets that should be logged
Definition at line 55 of file output-flow.c.
References OutputFlowLogger_::LogFunc, OutputFlowLogger_::module_id, OutputFlowLogger_::name, OutputFlowLogger_::next, OutputFlowLogger_::output_ctx, SCLogDebug, SCMalloc, and TmModuleGetIdByName().