suricata: src/output-stats.h File Reference
output-stats.h File Reference
Data Structures
struct StatsRecord_
struct StatsTable_
Typedefs
typedef struct StatsRecord_ StatsRecord
typedef struct StatsTable_ StatsTable
typedef int(* StatsLogger)(ThreadVars *, void *thread_data, const StatsTable *)
Functions
TmEcode OutputStatsLog (ThreadVars *tv, void *thread_data, StatsTable *st)
int OutputRegisterStatsLogger (const char *name, StatsLogger LogFunc, OutputCtx *)
void TmModuleStatsLoggerRegister (void)
int OutputStatsLoggersRegistered (void)
void OutputStatsShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Stats Logger Output registration functions
Definition in file output-stats.h.
Typedef Documentation
typedef int(* StatsLogger)(ThreadVars *, void *thread_data, const StatsTable *)
Definition at line 47 of file output-stats.h.
typedef struct StatsRecord_ StatsRecord
typedef struct StatsTable_ StatsTable
Function Documentation
int OutputRegisterStatsLogger (const char * name, StatsLogger LogFunc, OutputCtx *)
Definition at line 54 of file output-stats.c.
References OutputStatsLogger_::LogFunc, OutputStatsLogger_::module_id, OutputStatsLogger_::name, OutputStatsLogger_::next, OutputStatsLogger_::output_ctx, SCLogDebug, SCMalloc, and TmModuleGetIdByName().
TmEcode OutputStatsLog (ThreadVars * tv, void * thread_data, StatsTable * st)
Definition at line 83 of file output-stats.c.
References BUG_ON, OutputStatsLogger_::LogFunc, OutputLoggerThreadStore_::next, OutputStatsLogger_::next, OutputLoggerThreadData_::store, OutputLoggerThreadStore_::thread_data, and TM_ECODE_OK.
int OutputStatsLoggersRegistered (void)
Definition at line 225 of file output-stats.c.
void OutputStatsShutdown (void)
Definition at line 232 of file output-stats.c.
References OutputStatsLogger_::next, and SCFree.
Referenced by RunModeShutDown().
void TmModuleStatsLoggerRegister (void)
Definition at line 215 of file output-stats.c.
References TmModule_::cap_flags, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, tmm_modules, and TMM_STATSLOGGER.
Referenced by RegisterAllModules().