suricata: src/output-json.h File Reference
output-json.h File Reference
Functions
void TmModuleOutputJsonRegister (void)
Detailed Description
Author
Tom DeCanio td@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file output-json.h.
Function Documentation
void TmModuleOutputJsonRegister (void)
Definition at line 75 of file output-json.c.
References TmModule_::Func, TmModule_::name, OutputJson(), OutputJsonRegisterTests(), OutputJsonThreadDeinit(), OutputJsonThreadInit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadInit, tmm_modules, and TMM_OUTPUTJSON.
Referenced by RegisterAllModules().