suricata: src/packet-queue.h File Reference
packet-queue.h File Reference
#include "threads.h"
#include "decode.h"
Functions
void PacketEnqueue (PacketQueue *, Packet *)
Packet * PacketDequeue (PacketQueue *)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file packet-queue.h.
Function Documentation
Packet* PacketDequeue (PacketQueue *)
Definition at line 164 of file packet-queue.c.
References PacketQueue_::bot, PacketQueue_::len, Packet_::next, Packet_::prev, and PacketQueue_::top.
Referenced by StreamTcpPacket(), TmqhInputFlow(), TmqhInputSimple(), TmqhReleasePacketsToPacketPool(), TmThreadsSlotVar(), and TmThreadsSlotVarRun().
void PacketEnqueue (PacketQueue * , Packet *)
Definition at line 136 of file packet-queue.c.
References PacketQueue_::bot, PacketQueue_::len, Packet_::next, Packet_::prev, and PacketQueue_::top.
Referenced by DecodeGRE(), DecodeIPV4(), DecodeIPV6(), DecodeTeredo(), StreamTcpPacket(), StreamTcpPseudoPacketCreateStreamEndPacket(), TmqhOutputFlowActivePackets(), TmqhOutputFlowHash(), TmqhOutputFlowRoundRobin(), TmqhOutputSimple(), TmqhOutputVerdictNfq(), and TmThreadsInjectPacketsById().