suricata: src/pkt-var.h File Reference
pkt-var.h File Reference
Functions
void PktVarAdd (Packet *, char *, uint8_t *, uint16_t)
PktVar * PktVarGet (Packet *, char *)
void PktVarFree (PktVar *)
void PktVarPrint (PktVar *)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file pkt-var.h.
Function Documentation
void PktVarAdd (Packet * , char * , uint8_t * , uint16_t)
Definition at line 61 of file pkt-var.c.
References PktVar_::name, PktVar_::next, Packet_::pktvar, PktVarGet(), PktVarUpdate(), SCMalloc, unlikely, PktVar_::value, and PktVar_::value_len.
Referenced by DetectPcrePayloadMatch().
void PktVarFree (PktVar *)
Definition at line 92 of file pkt-var.c.
References PktVar_::name, PktVar_::next, PktVarFree(), SCFree, and PktVar_::value.
Referenced by GenericVarFree(), and PktVarFree().
PktVar* PktVarGet (Packet * , char *)
Definition at line 48 of file pkt-var.c.
References PktVar_::name, PktVar_::next, and Packet_::pktvar.
Referenced by DetectPktvarMatch(), and PktVarAdd().
void PktVarPrint (PktVar *)
Definition at line 108 of file pkt-var.c.
References PktVar_::name, PktVar_::next, PktVarPrint(), PktVar_::value, and PktVar_::value_len.
Referenced by PktVarPrint().