suricata: src/pkt-var.c File Reference
pkt-var.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "pkt-var.h"
#include "util-debug.h"
Functions
void PktVarUpdate (PktVar *pv, uint8_t *value, uint16_t size)
PktVar * PktVarGet (Packet *p, char *name)
void PktVarAdd (Packet *p, char *name, uint8_t *value, uint16_t size)
void PktVarFree (PktVar *pv)
void PktVarPrint (PktVar *pv)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements per packet vars
Todo:
move away from a linked list implementation
use different datatypes, such as string, int, etc.
have more than one instance of the same var, and be able to match on a specific one, or one all at a time. So if a certain capture matches multiple times, we can operate on all of them.
Definition in file pkt-var.c.
Function Documentation
void PktVarAdd (Packet * p, char * name, uint8_t * value, uint16_t size)
Definition at line 61 of file pkt-var.c.
References PktVar_::name, PktVar_::next, Packet_::pktvar, PktVarGet(), PktVarUpdate(), SCMalloc, unlikely, PktVar_::value, and PktVar_::value_len.
Referenced by DetectPcrePayloadMatch().
void PktVarFree (PktVar * pv)
Definition at line 92 of file pkt-var.c.
References PktVar_::name, PktVar_::next, PktVarFree(), SCFree, and PktVar_::value.
Referenced by GenericVarFree(), and PktVarFree().
PktVar* PktVarGet (Packet * p, char * name)
Definition at line 48 of file pkt-var.c.
References PktVar_::name, PktVar_::next, and Packet_::pktvar.
Referenced by DetectPktvarMatch(), and PktVarAdd().
void PktVarPrint (PktVar * pv)
Definition at line 108 of file pkt-var.c.
References PktVar_::name, PktVar_::next, PktVarPrint(), PktVar_::value, and PktVar_::value_len.
Referenced by PktVarPrint().
void PktVarUpdate (PktVar * pv, uint8_t * value, uint16_t size)
Definition at line 38 of file pkt-var.c.
References SCFree, PktVar_::value, and PktVar_::value_len.
Referenced by PktVarAdd().