suricata: src/reputation.c File Reference
reputation.c File Reference
#include "util-error.h"
#include "util-debug.h"
#include "util-ip.h"
#include "util-radix-tree.h"
#include "util-unittest.h"
#include "suricata-common.h"
#include "threads.h"
#include "util-print.h"
#include "host.h"
#include "conf.h"
#include "detect.h"
#include "reputation.h"
Macros
#define SREP_SHORTNAME_LEN 32
Functions
SC_ATOMIC_DECLARE (uint32_t, srep_eversion)
void SRepResetVersion (void)
uint8_t SRepCIDRGetIPRepSrc (SRepCIDRTree *cidr_ctx, Packet *p, uint8_t cat, uint32_t version)
uint8_t SRepCIDRGetIPRepDst (SRepCIDRTree *cidr_ctx, Packet *p, uint8_t cat, uint32_t version)
void SRepReloadComplete (void)
Increment effective reputation version after a rule/reputatio reload is complete.
void SRepInitComplete (void)
Set effective reputation version after reputation initialization is complete.
int SRepHostTimedOut (Host *h)
Check if a Host is timed out wrt ip rep, meaning a new version is in place.
int SRepCatValid (uint8_t cat)
uint8_t SRepCatGetByShortname (char *shortname)
int SRepLoadCatFileFromFD (FILE *fp)
int SRepLoadFileFromFD (SRepCIDRTree *cidr_ctx, FILE *fp)
int SRepInit (DetectEngineCtx *de_ctx)
init reputation
void SRepDestroy (DetectEngineCtx *de_ctx)
IPReputationCtx * SCReputationInitCtx (void)
Initialization fuction for the Reputation Context (IPV4 and IPV6)
Reputation * SCReputationAllocData (void)
Allocates the Reputation structure for a host/netblock.
void SCReputationFreeData (void *data)
Used to SCFree the reputation data that is allocated by Reputation API.
ReputationTransaction * SCReputationTransactionAlloc (void)
Allocates the Reputation structure for a host/netblock.
void SCReputationTransactionFreeData (void *data)
Used to SCFree the transaction data.
void SCReputationApplyTransaction (Reputation *rep_data, ReputationTransaction *rtx)
Apply the transaction of changes to the reputation We use transactions because we cant be locking/unlocking the trees foreach update. This help for a better performance.
int SCReputationEqual (Reputation *rep1, Reputation *rep2)
Function that compare two reputation structs to determine if they are equal.
void SCReputationPrint (Reputation *rep_data)
Helper function to print the Reputation structure.
Reputation * SCReputationClone (Reputation *orig)
Clone all the data of a reputation When you try to update the feed, if the data you have belongs to a netblock, it will be cloned and inserted or a host, with the modifications that you add.
void SCReputationFreeCtx (IPReputationCtx *rep_ctx)
Reputation * SCReputationAddIPV4Data (uint8_t *ipv4addr, int netmask_value, Reputation *rep_data)
Used to add a new reputation to the reputation module (only at the startup)
Reputation * SCReputationLookupIPV4ExactMatch (uint8_t *ipv4_addr)
Retrieves the Reputation of a host (exact match), given an ipv4 address in the raw address format.
Reputation * SCReputationLookupIPV4BestMatch (uint8_t *ipv4_addr)
Retrieves the Reputation of a host (best match), given an ipv4 address in the raw address format.
Reputation * SCReputationLookupIPV6BestMatch (uint8_t *ipv6_addr)
Retrieves the Reputation of a host (best match), given an ipv6 address in the raw address format.
Reputation * SCReputationLookupIPV6ExactMatch (uint8_t *ipv6_addr)
Retrieves the Reputation of a host (exact match), given an ipv6 address in the raw address format.
Reputation * SCReputationLookupIPV4ExactMatchReal (uint8_t *ipv4_addr)
Retrieves the Real Reputation of a host (exact match), given an ipv4 address in the raw address format. (Not thread safe!)
Reputation * SCReputationLookupIPV4BestMatchReal (uint8_t *ipv4_addr)
Retrieves the Real Reputation of a host (best match), given an ipv4 address in the raw address format. (Not thread safe!)
Reputation * SCReputationLookupIPV6BestMatchReal (uint8_t *ipv6_addr)
Retrieves the Real Reputation of a host (best match), given an ipv6 address in the raw address format. (Not thread safe!)
Reputation * SCReputationLookupIPV6ExactMatchReal (uint8_t *ipv6_addr)
Retrieves the Real Reputation of a host (exact match), given an ipv6 address in the raw address format. (Not thread safe!)
void SCReputationRemoveIPV4Data (uint8_t *ipv4_addr, uint8_t netmask_value)
Remove the node of the reputation tree associated to the ipv4 address.
void SCReputationRemoveIPV6Data (uint8_t *ipv6_addr, uint8_t netmask_value)
Remove the node of the reputation tree associated to the ipv6 address.
Reputation * SCReputationAddIPV6Data (uint8_t *ipv6addr, int netmask_value, Reputation *rep_data)
Used to add a new reputation to the reputation module (only at the startup)
Reputation * SCReputationUpdateIPV4Data (uint8_t *ipv4addr, ReputationTransaction *rtx)
Update a reputation or insert a new one. If it doesn't exist it will try to search for the reputation of parent subnets to create the new reputation data based on this one.
Reputation * SCReputationUpdateIPV6Data (uint8_t *ipv6addr, ReputationTransaction *rtx)
Update a reputation or insert a new one. If it doesn't exist it will try to search for the reputation of parent subnets to create the new reputation data based on this one.
void SCReputationRegisterTests (void)
Variables
IPReputationCtx * rep_ctx
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t Original Idea by Matt Jonkman
IP Reputation Module, initial API for IPV4 and IPV6 feed
Definition in file reputation.c.
Macro Definition Documentation
#define SREP_SHORTNAME_LEN 32
Definition at line 337 of file reputation.c.
Referenced by SRepLoadCatFileFromFD().
Function Documentation
SC_ATOMIC_DECLARE (uint32_t , srep_eversion)
effective reputation version, atomic as the host time out code will use it to check if a host's reputation info is outdated.
Reputation* SCReputationAddIPV4Data (uint8_t * ipv4addr, int netmask_value, Reputation * rep_data)
Used to add a new reputation to the reputation module (only at the startup)
Parameters
ipv4addr pointer to the ipv4 address key
netmask_value of the ipv4 address (can be a subnet or a host (32))
rep_data Reputation pointer to the Reputation associated to the host/net
Return values
NULL On failure; rep_data on success
Definition at line 1137 of file reputation.c.
References MaskIPNetblock(), IPReputationCtx_::reputationIPV4_lock, IPReputationCtx_::reputationIPV4_tree, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_IP_NETBLOCK, SCLogError, SCMutexLock, SCMutexUnlock, SCRadixAddKeyIPV4(), and SCRadixAddKeyIPV4Netblock().
Reputation* SCReputationAddIPV6Data (uint8_t * ipv6addr, int netmask_value, Reputation * rep_data)
Used to add a new reputation to the reputation module (only at the startup)
Parameters
ipv6addr pointer to the ipv6 address key
netmask_value of the ipv6 address (can be a subnet)
rep_data Reputation pointer to the Reputation associated to the host/net
Return values
NULL On failure
Definition at line 1415 of file reputation.c.
References MaskIPNetblock(), IPReputationCtx_::reputationIPV6_lock, IPReputationCtx_::reputationIPV6_tree, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_IP_NETBLOCK, SCLogError, SCMutexLock, SCMutexUnlock, SCRadixAddKeyIPV6(), and SCRadixAddKeyIPV6Netblock().
Reputation* SCReputationAllocData (void)
Allocates the Reputation structure for a host/netblock.
Return values
rep_data On success, pointer to the rep_data that has to be sent along with the key, to be added to the Radix tree
Definition at line 966 of file reputation.c.
References Reputation_::ctime, Reputation_::mtime, and SCMalloc.
Referenced by SCReputationUpdateIPV4Data(), and SCReputationUpdateIPV6Data().
void SCReputationApplyTransaction (Reputation * rep_data, ReputationTransaction * rtx)
Apply the transaction of changes to the reputation We use transactions because we cant be locking/unlocking the trees foreach update. This help for a better performance.
Parameters
rep_data pointer to the reputation to update
rtx pointer to the transaction data
Definition at line 1029 of file reputation.c.
References ReputationTransaction_::dec, Reputation_::flags, ReputationTransaction_::flags, ReputationTransaction_::inc, Reputation_::mtime, Reputation_::reps, REPUTATION_FLAG_NEEDSYNC, REPUTATION_NUMBER, TRANSACTION_FLAG_DECS, TRANSACTION_FLAG_INCS, and TRANSACTION_FLAG_NEEDSYNC.
Referenced by SCReputationUpdateIPV4Data(), and SCReputationUpdateIPV6Data().
Reputation* SCReputationClone (Reputation * orig)
Clone all the data of a reputation When you try to update the feed, if the data you have belongs to a netblock, it will be cloned and inserted or a host, with the modifications that you add.
Parameters
orig Pointer to the original reputation (probably of a netblock)
Return values
Reputation Pointer to the reputation copy
Definition at line 1100 of file reputation.c.
References SC_ERR_INVALID_ARGUMENT, SCLogError, and SCMalloc.
Referenced by SCReputationLookupIPV4BestMatch(), SCReputationLookupIPV4ExactMatch(), SCReputationLookupIPV6BestMatch(), SCReputationLookupIPV6ExactMatch(), SCReputationUpdateIPV4Data(), and SCReputationUpdateIPV6Data().
int SCReputationEqual (Reputation * rep1, Reputation * rep2)
Function that compare two reputation structs to determine if they are equal.
Parameters
rep1 pointer to reputation 1
rep2 pointer to reputation 2
Return values
1 if they are equal; 0 if not
Definition at line 1065 of file reputation.c.
References Reputation_::reps, and REPUTATION_NUMBER.
void SCReputationFreeCtx (IPReputationCtx * rep_ctx)
Definition at line 1114 of file reputation.c.
References IPReputationCtx_::reputationIPV4_lock, IPReputationCtx_::reputationIPV4_tree, IPReputationCtx_::reputationIPV6_lock, IPReputationCtx_::reputationIPV6_tree, SCMutexDestroy, and SCRadixReleaseRadixTree().
void SCReputationFreeData (void * data)
Used to SCFree the reputation data that is allocated by Reputation API.
Parameters
Pointer to the data that has to be SCFreed
Definition at line 984 of file reputation.c.
References SCFree.
Referenced by SCReputationInitCtx().
IPReputationCtx* SCReputationInitCtx (void)
Initialization fuction for the Reputation Context (IPV4 and IPV6)
Return values
Pointer to the IPReputationCtx created NULL Error initializing moule;
Definition at line 925 of file reputation.c.
References rep_ctx, IPReputationCtx_::reputationIPV4_lock, IPReputationCtx_::reputationIPV4_tree, IPReputationCtx_::reputationIPV6_lock, IPReputationCtx_::reputationIPV6_tree, SC_ERR_MUTEX, SCLogDebug, SCLogError, SCMalloc, SCMutexInit, SCRadixCreateRadixTree(), and SCReputationFreeData().
Referenced by RunUnittests().
Reputation* SCReputationLookupIPV4BestMatch (uint8_t * ipv4_addr)
Retrieves the Reputation of a host (best match), given an ipv4 address in the raw address format.
Parameters
ipv4_addr Pointer to a raw ipv4 address.
Return values
Pointer to a copy of the host Reputation on success; NULL on failure, or on not finding the key;
Definition at line 1216 of file reputation.c.
References IPReputationCtx_::reputationIPV4_lock, IPReputationCtx_::reputationIPV4_tree, SCMutexLock, SCMutexUnlock, SCRadixFindKeyIPV4BestMatch(), and SCReputationClone().
Reputation* SCReputationLookupIPV4BestMatchReal (uint8_t * ipv4_addr)
Retrieves the Real Reputation of a host (best match), given an ipv4 address in the raw address format. (Not thread safe!)
Parameters
ipv4_addr Pointer to a raw ipv4 address.
Return values
Pointer to the Reputation of the host on success; NULL on failure, or on not finding the key;
Definition at line 1327 of file reputation.c.
References IPReputationCtx_::reputationIPV4_tree, and SCRadixFindKeyIPV4BestMatch().
Referenced by SCReputationUpdateIPV4Data().
Reputation* SCReputationLookupIPV4ExactMatch (uint8_t * ipv4_addr)
Retrieves the Reputation of a host (exact match), given an ipv4 address in the raw address format.
Parameters
ipv4_addr Pointer to a raw ipv4 address.
Return values
Pointer to a copy of the host Reputation on success; NULL on failure, or on not finding the key;
Definition at line 1186 of file reputation.c.
References IPReputationCtx_::reputationIPV4_lock, IPReputationCtx_::reputationIPV4_tree, SCMutexLock, SCMutexUnlock, SCRadixFindKeyIPV4ExactMatch(), and SCReputationClone().
Reputation* SCReputationLookupIPV4ExactMatchReal (uint8_t * ipv4_addr)
Retrieves the Real Reputation of a host (exact match), given an ipv4 address in the raw address format. (Not thread safe!)
Parameters
ipv4_addr Pointer to a raw ipv4 address.
Return values
Pointer to the Reputation of the host on success; NULL on failure, or on not finding the key;
Definition at line 1307 of file reputation.c.
References IPReputationCtx_::reputationIPV4_tree, and SCRadixFindKeyIPV4ExactMatch().
Referenced by SCReputationUpdateIPV4Data().
Reputation* SCReputationLookupIPV6BestMatch (uint8_t * ipv6_addr)
Retrieves the Reputation of a host (best match), given an ipv6 address in the raw address format.
Parameters
Pointer to a raw ipv6 address.
Return values
Pointer to a copy of the host Reputation on success; NULL on failure, or on not finding the key;
Definition at line 1246 of file reputation.c.
References IPReputationCtx_::reputationIPV6_lock, IPReputationCtx_::reputationIPV6_tree, SCMutexLock, SCMutexUnlock, SCRadixFindKeyIPV6BestMatch(), and SCReputationClone().
Reputation* SCReputationLookupIPV6BestMatchReal (uint8_t * ipv6_addr)
Retrieves the Real Reputation of a host (best match), given an ipv6 address in the raw address format. (Not thread safe!)
Parameters
Pointer to a raw ipv6 address.
Return values
Pointer to the Reputation of the host on success; NULL on failure, or on not finding the key;
Definition at line 1347 of file reputation.c.
References IPReputationCtx_::reputationIPV6_tree, and SCRadixFindKeyIPV6BestMatch().
Referenced by SCReputationUpdateIPV6Data().
Reputation* SCReputationLookupIPV6ExactMatch (uint8_t * ipv6_addr)
Retrieves the Reputation of a host (exact match), given an ipv6 address in the raw address format.
Parameters
Pointer to a raw ipv6 address.
Return values
Pointer to a copy of the host reputation on success; NULL on failure, or on not finding the key;
Definition at line 1276 of file reputation.c.
References IPReputationCtx_::reputationIPV6_lock, IPReputationCtx_::reputationIPV6_tree, SCMutexLock, SCMutexUnlock, SCRadixFindKeyIPV6ExactMatch(), and SCReputationClone().
Reputation* SCReputationLookupIPV6ExactMatchReal (uint8_t * ipv6_addr)
Retrieves the Real Reputation of a host (exact match), given an ipv6 address in the raw address format. (Not thread safe!)
Parameters
Pointer to a raw ipv6 address.
Return values
Pointer to the Reputation of the host on success; NULL on failure, or on not finding the key;
Definition at line 1367 of file reputation.c.
References IPReputationCtx_::reputationIPV6_tree, and SCRadixFindKeyIPV6ExactMatch().
Referenced by SCReputationUpdateIPV6Data().
void SCReputationPrint (Reputation * rep_data)
Helper function to print the Reputation structure.
Parameters
Pointer rep_data to a Reputation structure
Definition at line 1076 of file reputation.c.
References Reputation_::flags, Reputation_::reps, REPUTATION_FLAG_NEEDSYNC, and REPUTATION_NUMBER.
void SCReputationRegisterTests (void)
Register the following unittests for the Reputation module
Definition at line 2324 of file reputation.c.
Referenced by RunUnittests().
void SCReputationRemoveIPV4Data (uint8_t * ipv4_addr, uint8_t netmask_value)
Remove the node of the reputation tree associated to the ipv4 address.
Parameters
ipv4_addr Pointer to a raw ipv4 address
netmask_value netmask to apply to the address (32 for host)
Definition at line 1385 of file reputation.c.
References IPReputationCtx_::reputationIPV4_lock, IPReputationCtx_::reputationIPV4_tree, SCMutexLock, SCMutexUnlock, and SCRadixRemoveKeyIPV4Netblock().
void SCReputationRemoveIPV6Data (uint8_t * ipv6_addr, uint8_t netmask_value)
Remove the node of the reputation tree associated to the ipv6 address.
Parameters
ipv6_addr Pointer to a raw ipv6 address
netmask_value netmask to apply to the address (128 for host)
Definition at line 1399 of file reputation.c.
References IPReputationCtx_::reputationIPV6_lock, IPReputationCtx_::reputationIPV6_tree, SCMutexLock, SCMutexUnlock, and SCRadixRemoveKeyIPV6Netblock().
ReputationTransaction* SCReputationTransactionAlloc (void)
Allocates the Reputation structure for a host/netblock.
Return values
ReputationTransaction pointer On success
Definition at line 997 of file reputation.c.
References SCMalloc.
void SCReputationTransactionFreeData (void * data)
Used to SCFree the transaction data.
Parameters
Pointer to the data that has to be SCFreed
Definition at line 1013 of file reputation.c.
References SCFree.
Reputation* SCReputationUpdateIPV4Data (uint8_t * ipv4addr, ReputationTransaction * rtx)
Update a reputation or insert a new one. If it doesn't exist it will try to search for the reputation of parent subnets to create the new reputation data based on this one.
Parameters
ipv6addr pointer to the ipv6 address key
rep_data Reputation pointer to the Reputation associated to the host/net
Return values
NULL On failure
Definition at line 1465 of file reputation.c.
References ReputationTransaction_::flags, IPReputationCtx_::reputationIPV4_lock, IPReputationCtx_::reputationIPV4_tree, SC_ERR_INVALID_ARGUMENT, SCLogError, SCMutexLock, SCMutexUnlock, SCRadixAddKeyIPV4(), SCReputationAllocData(), SCReputationApplyTransaction(), SCReputationClone(), SCReputationLookupIPV4BestMatchReal(), SCReputationLookupIPV4ExactMatchReal(), TRANSACTION_FLAG_INCS, and TRANSACTION_FLAG_NEEDSYNC.
Reputation* SCReputationUpdateIPV6Data (uint8_t * ipv6addr, ReputationTransaction * rtx)
Update a reputation or insert a new one. If it doesn't exist it will try to search for the reputation of parent subnets to create the new reputation data based on this one.
Parameters
ipv6addr pointer to the ipv6 address key
rep_data Reputation pointer to the Reputation associated to the host/net
Return values
NULL On failure
Definition at line 1524 of file reputation.c.
References ReputationTransaction_::flags, IPReputationCtx_::reputationIPV6_lock, IPReputationCtx_::reputationIPV6_tree, SC_ERR_INVALID_ARGUMENT, SCLogError, SCMutexLock, SCMutexUnlock, SCRadixAddKeyIPV6(), SCReputationAllocData(), SCReputationApplyTransaction(), SCReputationClone(), SCReputationLookupIPV6BestMatchReal(), SCReputationLookupIPV6ExactMatchReal(), TRANSACTION_FLAG_INCS, and TRANSACTION_FLAG_NEEDSYNC.
uint8_t SRepCatGetByShortname (char * shortname)
Definition at line 351 of file reputation.c.
References SREP_MAX_CATS.
int SRepCatValid (uint8_t cat)
Definition at line 340 of file reputation.c.
References SREP_MAX_CATS.
uint8_t SRepCIDRGetIPRepDst (SRepCIDRTree * cidr_ctx, Packet * p, uint8_t cat, uint32_t version)
Definition at line 158 of file reputation.c.
References GET_IPV4_DST_ADDR_PTR, GET_IPV6_DST_ADDR, PKT_IS_IPV4, and PKT_IS_IPV6.
Referenced by DetectIPRepMatch().
uint8_t SRepCIDRGetIPRepSrc (SRepCIDRTree * cidr_ctx, Packet * p, uint8_t cat, uint32_t version)
Definition at line 146 of file reputation.c.
References GET_IPV4_SRC_ADDR_PTR, GET_IPV6_SRC_ADDR, PKT_IS_IPV4, and PKT_IS_IPV6.
Referenced by DetectIPRepMatch().
void SRepDestroy (DetectEngineCtx * de_ctx)
Definition at line 673 of file reputation.c.
References SCFree, SCRadixReleaseRadixTree(), SREP_MAX_CATS, DetectEngineCtx_::srepCIDR_ctx, SRepCIDRTree_::srepIPV4_tree, and SRepCIDRTree_::srepIPV6_tree.
Referenced by DetectEngineCtxFree().
int SRepHostTimedOut (Host * h)
Check if a Host is timed out wrt ip rep, meaning a new version is in place.
We clean up the old version here.
Parameters
h host
Return values
0 not timed out
1 timed out
Definition at line 196 of file reputation.c.
References BUG_ON, HostDecrUsecnt, Host_::iprep, SCFree, SCLogDebug, and SReputation_::version.
int SRepInit (DetectEngineCtx * de_ctx)
init reputation
Parameters
de_ctx detection engine ctx for tracking iprep version
Return values
0 ok
-1 error
If this function is called more than once, the category file is not reloaded.
Definition at line 590 of file reputation.c.
References ConfGet(), ConfGetNode(), DetectEngineCtx_::failure_fatal, HostPrintStats(), next, SC_ATOMIC_INIT, SC_ERR_NO_REPUTATION, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, SREP_MAX_CATS, DetectEngineCtx_::srep_version, DetectEngineCtx_::srepCIDR_ctx, SRepInitComplete(), SRepCIDRTree_::srepIPV4_tree, SRepCIDRTree_::srepIPV6_tree, TAILQ_FOREACH, and ConfNode_::val.
void SRepInitComplete (void)
Set effective reputation version after reputation initialization is complete.
Definition at line 180 of file reputation.c.
References SC_ATOMIC_SET, and SCLogDebug.
Referenced by SRepInit().
int SRepLoadCatFileFromFD (FILE * fp)
Definition at line 379 of file reputation.c.
References BUG_ON, Address_::family, len, SC_ERR_NO_REPUTATION, SCLogDebug, SCLogError, SREP_MAX_CATS, SREP_SHORTNAME_LEN, and strlcpy().
int SRepLoadFileFromFD (SRepCIDRTree * cidr_ctx, FILE * fp)
Definition at line 446 of file reputation.c.
References Address_::address, Address_::family, HostGetHostFromHash(), HostIncrUsecnt, HostRelease(), Host_::iprep, len, PrintInet(), SReputation_::rep, SC_ERR_NO_REPUTATION, SCLogDebug, SCLogDebugEnabled(), SCLogError, SCMalloc, SREP_MAX_CATS, and SReputation_::version.
void SRepReloadComplete (void)
Increment effective reputation version after a rule/reputatio reload is complete.
Definition at line 172 of file reputation.c.
References SC_ATOMIC_ADD, and SCLogDebug.
void SRepResetVersion (void)
Definition at line 60 of file reputation.c.
Variable Documentation
IPReputationCtx* rep_ctx
Global trees that hold host reputation for IPV4 and IPV6 hosts
Definition at line 917 of file reputation.c.
Referenced by SCReputationInitCtx().