suricata: src/reputation.h File Reference
reputation.h File Reference
#include "host.h"
Data Structures
struct SRepCIDRTree_
struct SReputation_
struct IPReputationCtx_
struct Reputation_
struct ReputationTransaction_
Macros
#define SREP_MAX_CATS 60
#define REPUTATION_SPAM 0
#define REPUTATION_CNC 1
#define REPUTATION_SCAN 2
#define REPUTATION_HOSTILE 3
#define REPUTATION_DYNAMIC 4
#define REPUTATION_PUBLICACCESS 5
#define REPUTATION_PROXY 6
#define REPUTATION_P2P 7
#define REPUTATION_UTILITY 8
#define REPUTATION_DDOS 9
#define REPUTATION_PHISH 10
#define REPUTATION_MALWARE 11
#define REPUTATION_ZOMBIE 12
#define REPUTATION_NUMBER 13
#define REPUTATION_FLAG_NEEDSYNC 0x01
#define TRANSACTION_FLAG_NEEDSYNC 0x01
#define TRANSACTION_FLAG_INCS 0x02
#define TRANSACTION_FLAG_DECS 0x04
Typedefs
typedef struct SRepCIDRTree_ SRepCIDRTree
typedef struct SReputation_ SReputation
typedef struct IPReputationCtx_ IPReputationCtx
typedef struct Reputation_ Reputation
typedef struct
ReputationTransaction_ ReputationTransaction
Functions
uint8_t SRepCatGetByShortname (char *shortname)
int SRepInit (struct DetectEngineCtx_ *de_ctx)
init reputation
void SRepDestroy (struct DetectEngineCtx_ *de_ctx)
void SRepReloadComplete (void)
Increment effective reputation version after a rule/reputatio reload is complete.
int SRepHostTimedOut (Host *)
Check if a Host is timed out wrt ip rep, meaning a new version is in place.
uint8_t SRepCIDRGetIPRepSrc (SRepCIDRTree *cidr_ctx, Packet *p, uint8_t cat, uint32_t version)
uint8_t SRepCIDRGetIPRepDst (SRepCIDRTree *cidr_ctx, Packet *p, uint8_t cat, uint32_t version)
void SRepResetVersion ()
int SRepLoadCatFileFromFD (FILE *fp)
int SRepLoadFileFromFD (SRepCIDRTree *cidr_ctx, FILE *fp)
Reputation * SCReputationAllocData ()
Allocates the Reputation structure for a host/netblock.
Reputation * SCReputationClone (Reputation *)
Clone all the data of a reputation When you try to update the feed, if the data you have belongs to a netblock, it will be cloned and inserted or a host, with the modifications that you add.
void SCReputationFreeData (void *)
Used to SCFree the reputation data that is allocated by Reputation API.
IPReputationCtx * SCReputationInitCtx (void)
Initialization fuction for the Reputation Context (IPV4 and IPV6)
void SCReputationFreeCtx (IPReputationCtx *)
void SCReputationPrint (Reputation *)
Helper function to print the Reputation structure.
void SCReputationRegisterTests (void)
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t Original Idea by Matt Jonkman
Definition in file reputation.h.
Macro Definition Documentation
#define REPUTATION_CNC 1
CnC server
Definition at line 53 of file reputation.h.
#define REPUTATION_DDOS 9
Known ddos participant
Definition at line 61 of file reputation.h.
#define REPUTATION_DYNAMIC 4
Known dial up, residential, user networks
Definition at line 56 of file reputation.h.
#define REPUTATION_FLAG_NEEDSYNC 0x01
rep was changed by engine, needs sync with external hub
Definition at line 75 of file reputation.h.
Referenced by SCReputationApplyTransaction(), and SCReputationPrint().
#define REPUTATION_HOSTILE 3
hijacked nets, RBN nets, etc
Definition at line 55 of file reputation.h.
#define REPUTATION_MALWARE 11
Known Malware distribution site. Hacked web server, etc
Definition at line 63 of file reputation.h.
#define REPUTATION_NUMBER 13
number of rep types we have for data structure size (be careful with this)
Definition at line 71 of file reputation.h.
Referenced by SCReputationApplyTransaction(), SCReputationEqual(), and SCReputationPrint().
#define REPUTATION_P2P 7
Heavy p2p node, torrent server, other sharing services
Definition at line 59 of file reputation.h.
#define REPUTATION_PHISH 10
Known Phishing site
Definition at line 62 of file reputation.h.
#define REPUTATION_PROXY 6
known tor out nodes, proxy servers, etc
Definition at line 58 of file reputation.h.
#define REPUTATION_PUBLICACCESS 5
known internet cafe's open access points
Definition at line 57 of file reputation.h.
#define REPUTATION_SCAN 2
scanner
Definition at line 54 of file reputation.h.
#define REPUTATION_SPAM 0
Reputation numbers (types) that we can use to lookup/update, etc Please, dont convert this to a enum since we want the same reputation codes always. spammer
Definition at line 52 of file reputation.h.
#define REPUTATION_UTILITY 8
known good places like google, yahoo, msn.com, etc
Definition at line 60 of file reputation.h.
#define REPUTATION_ZOMBIE 12
Known Zombie (botnet member) They typically are Scanner or Hostile, but if collaboration with botnet snooping, like we did back in 2005 or so, can proactively identify online zombies that joined a botnet, you may want to break those out separately
Definition at line 64 of file reputation.h.
#define SREP_MAX_CATS 60
Definition at line 31 of file reputation.h.
Referenced by SRepCatGetByShortname(), SRepCatValid(), SRepDestroy(), SRepInit(), SRepLoadCatFileFromFD(), and SRepLoadFileFromFD().
#define TRANSACTION_FLAG_DECS 0x04
We will decrement only if necesary
Definition at line 106 of file reputation.h.
Referenced by SCReputationApplyTransaction().
#define TRANSACTION_FLAG_INCS 0x02
We will increment only if necesary
Definition at line 105 of file reputation.h.
Referenced by SCReputationApplyTransaction(), SCReputationUpdateIPV4Data(), and SCReputationUpdateIPV6Data().
#define TRANSACTION_FLAG_NEEDSYNC 0x01
We will apply the transaction only if necesary
Definition at line 104 of file reputation.h.
Referenced by SCReputationApplyTransaction(), SCReputationUpdateIPV4Data(), and SCReputationUpdateIPV6Data().
Typedef Documentation
typedef struct IPReputationCtx_ IPReputationCtx
Reputation Context for IPV4 IPV6
typedef struct Reputation_ Reputation
Reputation Data
typedef struct ReputationTransaction_ ReputationTransaction
typedef struct SRepCIDRTree_ SRepCIDRTree
typedef struct SReputation_ SReputation
Function Documentation
Reputation* SCReputationAllocData (void)
Allocates the Reputation structure for a host/netblock.
Return values
rep_data On success, pointer to the rep_data that has to be sent along with the key, to be added to the Radix tree
Definition at line 966 of file reputation.c.
References Reputation_::ctime, Reputation_::mtime, and SCMalloc.
Referenced by SCReputationUpdateIPV4Data(), and SCReputationUpdateIPV6Data().
Reputation* SCReputationClone (Reputation * orig)
Clone all the data of a reputation When you try to update the feed, if the data you have belongs to a netblock, it will be cloned and inserted or a host, with the modifications that you add.
Parameters
orig Pointer to the original reputation (probably of a netblock)
Return values
Reputation Pointer to the reputation copy
Definition at line 1100 of file reputation.c.
References SC_ERR_INVALID_ARGUMENT, SCLogError, and SCMalloc.
Referenced by SCReputationLookupIPV4BestMatch(), SCReputationLookupIPV4ExactMatch(), SCReputationLookupIPV6BestMatch(), SCReputationLookupIPV6ExactMatch(), SCReputationUpdateIPV4Data(), and SCReputationUpdateIPV6Data().
void SCReputationFreeCtx (IPReputationCtx *)
Definition at line 1114 of file reputation.c.
References IPReputationCtx_::reputationIPV4_lock, IPReputationCtx_::reputationIPV4_tree, IPReputationCtx_::reputationIPV6_lock, IPReputationCtx_::reputationIPV6_tree, SCMutexDestroy, and SCRadixReleaseRadixTree().
void SCReputationFreeData (void * data)
Used to SCFree the reputation data that is allocated by Reputation API.
Parameters
Pointer to the data that has to be SCFreed
Definition at line 984 of file reputation.c.
References SCFree.
Referenced by SCReputationInitCtx().
IPReputationCtx* SCReputationInitCtx (void)
Initialization fuction for the Reputation Context (IPV4 and IPV6)
Return values
Pointer to the IPReputationCtx created NULL Error initializing moule;
Definition at line 925 of file reputation.c.
References rep_ctx, IPReputationCtx_::reputationIPV4_lock, IPReputationCtx_::reputationIPV4_tree, IPReputationCtx_::reputationIPV6_lock, IPReputationCtx_::reputationIPV6_tree, SC_ERR_MUTEX, SCLogDebug, SCLogError, SCMalloc, SCMutexInit, SCRadixCreateRadixTree(), and SCReputationFreeData().
Referenced by RunUnittests().
void SCReputationPrint (Reputation * rep_data)
Helper function to print the Reputation structure.
Parameters
Pointer rep_data to a Reputation structure
Definition at line 1076 of file reputation.c.
References Reputation_::flags, Reputation_::reps, REPUTATION_FLAG_NEEDSYNC, and REPUTATION_NUMBER.
void SCReputationRegisterTests (void)
Register the following unittests for the Reputation module
Definition at line 2324 of file reputation.c.
Referenced by RunUnittests().
uint8_t SRepCatGetByShortname (char * shortname)
Definition at line 351 of file reputation.c.
References SREP_MAX_CATS.
uint8_t SRepCIDRGetIPRepDst (SRepCIDRTree * cidr_ctx, Packet * p, uint8_t cat, uint32_t version)
Definition at line 158 of file reputation.c.
References GET_IPV4_DST_ADDR_PTR, GET_IPV6_DST_ADDR, PKT_IS_IPV4, and PKT_IS_IPV6.
Referenced by DetectIPRepMatch().
uint8_t SRepCIDRGetIPRepSrc (SRepCIDRTree * cidr_ctx, Packet * p, uint8_t cat, uint32_t version)
Definition at line 146 of file reputation.c.
References GET_IPV4_SRC_ADDR_PTR, GET_IPV6_SRC_ADDR, PKT_IS_IPV4, and PKT_IS_IPV6.
Referenced by DetectIPRepMatch().
void SRepDestroy (struct DetectEngineCtx_ * de_ctx)
Definition at line 673 of file reputation.c.
References SCFree, SCRadixReleaseRadixTree(), SREP_MAX_CATS, DetectEngineCtx_::srepCIDR_ctx, SRepCIDRTree_::srepIPV4_tree, and SRepCIDRTree_::srepIPV6_tree.
Referenced by DetectEngineCtxFree().
int SRepHostTimedOut (Host * h)
Check if a Host is timed out wrt ip rep, meaning a new version is in place.
We clean up the old version here.
Parameters
h host
Return values
0 not timed out
1 timed out
Definition at line 196 of file reputation.c.
References BUG_ON, HostDecrUsecnt, Host_::iprep, SCFree, SCLogDebug, and SReputation_::version.
int SRepInit (DetectEngineCtx * de_ctx)
init reputation
Parameters
de_ctx detection engine ctx for tracking iprep version
Return values
0 ok
-1 error
If this function is called more than once, the category file is not reloaded.
Definition at line 590 of file reputation.c.
References ConfGet(), ConfGetNode(), DetectEngineCtx_::failure_fatal, HostPrintStats(), next, SC_ATOMIC_INIT, SC_ERR_NO_REPUTATION, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, SREP_MAX_CATS, DetectEngineCtx_::srep_version, DetectEngineCtx_::srepCIDR_ctx, SRepInitComplete(), SRepCIDRTree_::srepIPV4_tree, SRepCIDRTree_::srepIPV6_tree, TAILQ_FOREACH, and ConfNode_::val.
int SRepLoadCatFileFromFD (FILE * fp)
Definition at line 379 of file reputation.c.
References BUG_ON, Address_::family, len, SC_ERR_NO_REPUTATION, SCLogDebug, SCLogError, SREP_MAX_CATS, SREP_SHORTNAME_LEN, and strlcpy().
int SRepLoadFileFromFD (SRepCIDRTree * cidr_ctx, FILE * fp)
Definition at line 446 of file reputation.c.
References Address_::address, Address_::family, HostGetHostFromHash(), HostIncrUsecnt, HostRelease(), Host_::iprep, len, PrintInet(), SReputation_::rep, SC_ERR_NO_REPUTATION, SCLogDebug, SCLogDebugEnabled(), SCLogError, SCMalloc, SREP_MAX_CATS, and SReputation_::version.
void SRepReloadComplete (void)
Increment effective reputation version after a rule/reputatio reload is complete.
Definition at line 172 of file reputation.c.
References SC_ATOMIC_ADD, and SCLogDebug.
void SRepResetVersion ()
Definition at line 60 of file reputation.c.