suricata: src/respond-reject.c File Reference
respond-reject.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "packet-queue.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "action-globals.h"
#include "respond-reject.h"
#include "respond-reject-libnet11.h"
#include "util-debug.h"
#include "util-privs.h"
Functions
int RejectSendIPv4TCP (ThreadVars *, Packet *, void *)
int RejectSendIPv4ICMP (ThreadVars *, Packet *, void *)
int RejectSendIPv6TCP (ThreadVars *, Packet *, void *)
int RejectSendIPv6ICMP (ThreadVars *, Packet *, void *)
void TmModuleRespondRejectRegister (void)
TmEcode RespondRejectFunc (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
Detailed Description
Author
William Metcalf willi.nosp@m.am.m.nosp@m.etcal.nosp@m.f@gm.nosp@m.ail.c.nosp@m.om
RespondReject is a threaded wrapper for sending Rejects
Todo:
RespondRejectFunc returns 1 on error, 0 on ok... why? For now it should just return 0 always, error handling is a TODO in the threading model (VJ)
Definition in file respond-reject.c.
Function Documentation
int RejectSendIPv4ICMP (ThreadVars * tv, Packet * p, void * data)
Definition at line 115 of file respond-reject.c.
References ACTION_REJECT, ACTION_REJECT_BOTH, ACTION_REJECT_DST, PACKET_TEST_ACTION, REJECT_DIR_DST, REJECT_DIR_SRC, RejectSendLibnet11L3IPv4ICMP(), SCEnter, and SCReturnInt.
Referenced by RespondRejectFunc().
int RejectSendIPv4TCP (ThreadVars * tv, Packet * p, void * data)
Definition at line 93 of file respond-reject.c.
References ACTION_REJECT, ACTION_REJECT_BOTH, ACTION_REJECT_DST, PACKET_TEST_ACTION, REJECT_DIR_DST, REJECT_DIR_SRC, RejectSendLibnet11L3IPv4TCP(), SCEnter, and SCReturnInt.
Referenced by RespondRejectFunc().
int RejectSendIPv6ICMP (ThreadVars * tv, Packet * p, void * data)
Definition at line 159 of file respond-reject.c.
References ACTION_REJECT, ACTION_REJECT_BOTH, ACTION_REJECT_DST, PACKET_TEST_ACTION, REJECT_DIR_DST, REJECT_DIR_SRC, RejectSendLibnet11L3IPv6ICMP(), SCEnter, and SCReturnInt.
Referenced by RespondRejectFunc().
int RejectSendIPv6TCP (ThreadVars * tv, Packet * p, void * data)
Definition at line 137 of file respond-reject.c.
References ACTION_REJECT, ACTION_REJECT_BOTH, ACTION_REJECT_DST, PACKET_TEST_ACTION, REJECT_DIR_DST, REJECT_DIR_SRC, RejectSendLibnet11L3IPv6TCP(), SCEnter, and SCReturnInt.
Referenced by RespondRejectFunc().
TmEcode RespondRejectFunc (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
Definition at line 59 of file respond-reject.c.
References ACTION_REJECT, ACTION_REJECT_BOTH, ACTION_REJECT_DST, PACKET_TEST_ACTION, PKT_IS_IPV4, PKT_IS_IPV6, PKT_IS_TCP, RejectSendIPv4ICMP(), RejectSendIPv4TCP(), RejectSendIPv6ICMP(), RejectSendIPv6TCP(), TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleRespondRejectRegister().
void TmModuleRespondRejectRegister (void)
Definition at line 49 of file respond-reject.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, RespondRejectFunc(), TmModule_::ThreadDeinit, TmModule_::ThreadInit, tmm_modules, and TMM_RESPONDREJECT.
Referenced by RegisterAllModules().