suricata: src/respond-reject.h File Reference
respond-reject.h File Reference
#include "tm-threads.h"
Macros
#define REJECT_DIR_SRC 0
#define REJECT_DIR_DST 1
Functions
void TmModuleRespondRejectRegister (void)
TmEcode RespondRejectFunc (ThreadVars *, Packet *, void *, PacketQueue *, PacketQueue *)
Detailed Description
Author
William Metcalf willi.nosp@m.am.m.nosp@m.etcal.nosp@m.f@gm.nosp@m.ail.c.nosp@m.om
Definition in file respond-reject.h.
Macro Definition Documentation
#define REJECT_DIR_DST 1
Definition at line 30 of file respond-reject.h.
Referenced by RejectSendIPv4ICMP(), RejectSendIPv4TCP(), RejectSendIPv6ICMP(), and RejectSendIPv6TCP().
#define REJECT_DIR_SRC 0
Definition at line 29 of file respond-reject.h.
Referenced by RejectSendIPv4ICMP(), RejectSendIPv4TCP(), RejectSendIPv6ICMP(), and RejectSendIPv6TCP().
Function Documentation
TmEcode RespondRejectFunc (ThreadVars * , Packet * , void * , PacketQueue * , PacketQueue *)
Definition at line 59 of file respond-reject.c.
References ACTION_REJECT, ACTION_REJECT_BOTH, ACTION_REJECT_DST, PACKET_TEST_ACTION, PKT_IS_IPV4, PKT_IS_IPV6, PKT_IS_TCP, RejectSendIPv4ICMP(), RejectSendIPv4TCP(), RejectSendIPv6ICMP(), RejectSendIPv6TCP(), TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleRespondRejectRegister().
void TmModuleRespondRejectRegister (void)
Definition at line 49 of file respond-reject.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, RespondRejectFunc(), TmModule_::ThreadDeinit, TmModule_::ThreadInit, tmm_modules, and TMM_RESPONDREJECT.
Referenced by RegisterAllModules().