suricata: src/runmodes.c File Reference
runmodes.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "tm-threads.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-byte.h"
#include "util-affinity.h"
#include "conf.h"
#include "queue.h"
#include "runmodes.h"
#include "util-unittest.h"
#include "util-misc.h"
#include "alert-fastlog.h"
#include "alert-prelude.h"
#include "alert-unified2-alert.h"
#include "alert-debuglog.h"
#include "log-httplog.h"
#include "output.h"
#include "source-pfring.h"
Data Structures
struct RunMode_
Holds description for a runmode.
struct RunModes_
struct RunModeOutput_
Typedefs
typedef struct RunMode_ RunMode
Holds description for a runmode.
typedef struct RunModes_ RunModes
typedef struct RunModeOutput_ RunModeOutput
Functions
TAILQ_HEAD (RunModeOutput_)
TAILQ_HEAD (OutputFreeList_)
char * RunmodeGetActive (void)
const char * RunModeGetMainMode (void)
void RunModeRegisterRunModes (void)
Register all runmodes in the engine.
void RunModeListRunmodes (void)
Lists all registered runmodes.
void RunModeDispatch (int runmode, const char *custom_mode)
void RunModeRegisterNewRunMode (int runmode, const char *name, const char *description, int(*RunModeFunc)(void))
Registers a new runmode.
void RunOutputFreeList (void)
int RunModeOutputFileEnabled (void)
int RunModeOutputFiledataEnabled (void)
void RunModeShutDown (void)
void RunModeInitializeOutputs (void)
void SetupOutputs (ThreadVars *tv)
void RunModeInitialize (void)
Variables
int debuglog_enabled = 0
OutputFreeList
float threading_detect_ratio = 1
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pre-cooked threading runmodes.
Definition in file runmodes.c.
Typedef Documentation
typedef struct RunMode_ RunMode
Holds description for a runmode.
typedef struct RunModeOutput_ RunModeOutput
A list of output modules that will be active for the run mode.
typedef struct RunModes_ RunModes
Function Documentation
void RunModeDispatch (int runmode, const char * custom_mode)
Definition at line 270 of file runmodes.c.
References ConfGet(), PatternMatchDefaultMatcher(), RUNMODE_AFP_DEV, RUNMODE_DAG, RUNMODE_ERF_FILE, RUNMODE_IPFW, RUNMODE_NAPATECH, RUNMODE_NETMAP, RUNMODE_NFLOG, RUNMODE_NFQ, RUNMODE_PCAP_DEV, RUNMODE_PCAP_FILE, RUNMODE_PFRING, RUNMODE_TILERA_MPIPE, RUNMODE_UNIX_SOCKET, RunModeAFPGetDefaultMode(), RunModeErfDagGetDefaultMode(), RunModeErfFileGetDefaultMode(), RunModeFilePcapGetDefaultMode(), RunMode_::RunModeFunc, RunModeIdsGetDefaultMode(), RunModeIdsNflogGetDefaultMode(), RunModeIdsPfringGetDefaultMode(), RunModeIpsIPFWGetDefaultMode(), RunModeIpsNFQGetDefaultMode(), RunModeNapatechGetDefaultMode(), RunModeNetmapGetDefaultMode(), RunModeTileMpipeGetDefaultMode(), RunModeUnixSocketGetDefaultMode(), SC_ERR_MEM_ALLOC, SC_ERR_RUNMODE, SC_ERR_UNKNOWN_RUN_MODE, SCFree, SCLogError, SCLogWarning, SCStrdup, and unlikely.
Referenced by main().
char* RunmodeGetActive (void)
Return the running mode
The returned string must not be freed.
Returns
a string containing the current running mode
Definition at line 179 of file runmodes.c.
Referenced by ReceiveAFPThreadInit(), and ReceivePfringThreadInit().
const char* RunModeGetMainMode (void)
Return the running mode
The returned string must not be freed.
Returns
a string containing the current running mode
Definition at line 191 of file runmodes.c.
References RunmodeGetCurrent().
void RunModeInitialize (void)
Initialize multithreading settings.
Definition at line 910 of file runmodes.c.
References AffinitySetupLoadFromConfig(), ConfGetBool(), ConfGetFloat(), ConfGetNode(), FALSE, SCLogDebug, threading_detect_ratio, threading_set_cpu_affinity, TRUE, and WarnInvalidConfEntry.
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), RunModeIdsAFPWorkers(), RunModeIdsErfDagAutoFp(), RunModeIdsErfDagSingle(), RunModeIdsErfDagWorkers(), RunModeIdsNetmapAutoFp(), RunModeIdsNetmapSingle(), RunModeIdsNetmapWorkers(), RunModeIdsNflogAutoFp(), RunModeIdsNflogSingle(), RunModeIdsNflogWorkers(), RunModeIdsPcapAutoFp(), RunModeIdsPcapSingle(), RunModeIdsPcapWorkers(), RunModeIdsPfringAutoFp(), RunModeIdsPfringSingle(), RunModeIdsPfringWorkers(), RunModeIpsIPFWAutoFp(), RunModeIpsIPFWWorker(), RunModeIpsNFQAutoFp(), and RunModeIpsNFQWorker().
void RunModeInitializeOutputs (void)
Initialize the output modules.
Definition at line 688 of file runmodes.c.
References BUG_ON, OutputModule_::conf_name, ConfGetNode(), ConfNodeLookupChild(), ConfNodeLookupChildValue(), ConfValIsTrue(), FatalError, FatalErrorOnInit, OutputModule_::InitFunc, OutputModule_::InitSubFunc, m, OutputModule_::name, next, OutputGetModuleByConfName(), OutputModule_::parent_name, SC_ERR_CONF_YAML_ERROR, SC_ERR_INVALID_ARGUMENT, SC_ERR_NOT_SUPPORTED, SCLogDebug, SCLogInfo, SCLogWarning, TAILQ_FOREACH, type, and ConfNode_::val.
Referenced by main().
void RunModeListRunmodes (void)
Lists all registered runmodes.
Definition at line 227 of file runmodes.c.
References RunMode_::description, RunMode_::name, RunMode_::runmode, RUNMODE_UNKNOWN, and RUNMODE_USER_MAX.
Referenced by StartInternalRunMode().
int RunModeOutputFiledataEnabled (void)
Definition at line 455 of file runmodes.c.
int RunModeOutputFileEnabled (void)
Definition at line 450 of file runmodes.c.
void RunModeRegisterNewRunMode (int runmode, const char * name, const char * description, int(*)(void) RunModeFunc)
Registers a new runmode.
Parameters
runmode Runmode type.
name Custom mode for this specific runmode type. Within each runmode type, each custom name is a primary key.
description Description for this runmode.
RunModeFunc The function to be run for this runmode.
Definition at line 385 of file runmodes.c.
References RunMode_::description, RunMode_::name, RunMode_::runmode, RunMode_::RunModeFunc, SC_ERR_MEM_ALLOC, SC_ERR_RUNMODE, SCFree, SCLogError, SCRealloc, SCStrdup, and unlikely.
Referenced by RunModeErfDagRegister(), RunModeErfFileRegister(), RunModeFilePcapRegister(), RunModeIdsAFPRegister(), RunModeIdsNetmapRegister(), RunModeIdsNflogRegister(), RunModeIdsPcapRegister(), RunModeIdsPfringRegister(), RunModeIpsIPFWRegister(), RunModeIpsNFQRegister(), RunModeNapatechRegister(), RunModeTileMpipeRegister(), and RunModeUnixSocketRegister().
void RunModeRegisterRunModes (void)
Register all runmodes in the engine.
Definition at line 201 of file runmodes.c.
References RunModeErfDagRegister(), RunModeErfFileRegister(), RunModeFilePcapRegister(), RunModeIdsAFPRegister(), RunModeIdsNetmapRegister(), RunModeIdsNflogRegister(), RunModeIdsPcapRegister(), RunModeIdsPfringRegister(), RunModeIpsIPFWRegister(), RunModeIpsNFQRegister(), RunModeNapatechRegister(), RunModeTileMpipeRegister(), and RunModeUnixSocketRegister().
Referenced by main().
void RunModeShutDown (void)
Cleanup the run mode.
Definition at line 463 of file runmodes.c.
References TmModule_::name, OutputFiledataShutdown(), OutputFileShutdown(), OutputFlowShutdown(), OutputPacketShutdown(), OutputStatsShutdown(), OutputStreamingShutdown(), OutputTxShutdown(), RunOutputFreeList(), SCFree, SCLogDebug, TAILQ_FIRST, TAILQ_REMOVE, and RunModeOutput_::tm_module.
Referenced by main().
void RunOutputFreeList (void)
Setup the outputs for this run mode.
Parameters
tv The ThreadVars for the thread the outputs will be appended to.
Definition at line 430 of file runmodes.c.
References OutputFreeList, SCFree, SCLogDebug, TAILQ_FIRST, and TAILQ_REMOVE.
Referenced by RunModeShutDown().
void SetupOutputs (ThreadVars * tv)
Setup the outputs for this run mode.
Parameters
tv The ThreadVars for the thread the outputs will be appended to.
Definition at line 896 of file runmodes.c.
References TmModule_::cap_flags, ThreadVars_::cap_flags, RunModeOutput_::output_ctx, TAILQ_FOREACH, RunModeOutput_::tm_module, and TmSlotSetFuncAppend().
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), and RunModeSetLiveCaptureAutoFp().
TAILQ_HEAD (RunModeOutput_)
Definition at line 81 of file runmodes.c.
References RunModeOutput_::output_ctx, TAILQ_ENTRY, and RunModeOutput_::tm_module.
TAILQ_HEAD (OutputFreeList_)
Definition at line 95 of file runmodes.c.
References RUNMODE_AFP_DEV, RUNMODE_DAG, RUNMODE_ERF_FILE, RUNMODE_IPFW, RUNMODE_NAPATECH, RUNMODE_NETMAP, RUNMODE_NFLOG, RUNMODE_NFQ, RUNMODE_PCAP_DEV, RUNMODE_PCAP_FILE, RUNMODE_PFRING, RUNMODE_TILERA_MPIPE, RUNMODE_UNITTEST, RUNMODE_UNIX_SOCKET, SC_ERR_UNKNOWN_RUN_MODE, and SCLogError.
Variable Documentation
int debuglog_enabled = 0
Definition at line 52 of file runmodes.c.
Referenced by SigMatchSignatures().
OutputFreeList
Definition at line 94 of file runmodes.c.
Referenced by RunOutputFreeList().
float threading_detect_ratio = 1
Definition at line 905 of file runmodes.c.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeInitialize(), RunModeSetIPSAutoFp(), and RunModeSetLiveCaptureAutoFp().