suricata: src/runmodes.h File Reference
runmodes.h File Reference
#include "runmode-pcap.h"
#include "runmode-pcap-file.h"
#include "runmode-pfring.h"
#include "runmode-tile.h"
#include "runmode-nfq.h"
#include "runmode-ipfw.h"
#include "runmode-erf-file.h"
#include "runmode-erf-dag.h"
#include "runmode-napatech.h"
#include "runmode-af-packet.h"
#include "runmode-nflog.h"
#include "runmode-unix-socket.h"
#include "runmode-netmap.h"
Enumerations
enum {
RUNMODE_UNKNOWN = 0, RUNMODE_PCAP_DEV, RUNMODE_PCAP_FILE, RUNMODE_PFRING,
RUNMODE_NFQ, RUNMODE_NFLOG, RUNMODE_IPFW, RUNMODE_ERF_FILE,
RUNMODE_DAG, RUNMODE_AFP_DEV, RUNMODE_NETMAP, RUNMODE_TILERA_MPIPE,
RUNMODE_UNITTEST, RUNMODE_NAPATECH, RUNMODE_UNIX_SOCKET, RUNMODE_USER_MAX,
RUNMODE_LIST_KEYWORDS, RUNMODE_LIST_APP_LAYERS, RUNMODE_LIST_CUDA_CARDS, RUNMODE_LIST_RUNMODES,
RUNMODE_PRINT_VERSION, RUNMODE_PRINT_BUILDINFO, RUNMODE_PRINT_USAGE, RUNMODE_DUMP_CONFIG,
RUNMODE_CONF_TEST, RUNMODE_LIST_UNITTEST, RUNMODE_ENGINE_ANALYSIS, RUNMODE_MAX
}
Functions
char * RunmodeGetActive (void)
const char * RunModeGetMainMode (void)
void RunModeListRunmodes (void)
Lists all registered runmodes.
void RunModeDispatch (int, const char *)
void RunModeRegisterRunModes (void)
Register all runmodes in the engine.
void RunModeRegisterNewRunMode (int, const char *, const char *, int(*RunModeFunc)(void))
Registers a new runmode.
void RunModeInitialize (void)
void RunModeInitializeOutputs (void)
void SetupOutputs (ThreadVars *)
void RunModeShutDown (void)
int RunModeOutputFileEnabled (void)
int RunModeOutputFiledataEnabled (void)
Variables
int threading_set_cpu_affinity
float threading_detect_ratio
int debuglog_enabled
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file runmodes.h.
Enumeration Type Documentation
anonymous enum
Enumerator
RUNMODE_UNKNOWN
RUNMODE_PCAP_DEV
RUNMODE_PCAP_FILE
RUNMODE_PFRING
RUNMODE_NFQ
RUNMODE_NFLOG
RUNMODE_IPFW
RUNMODE_ERF_FILE
RUNMODE_DAG
RUNMODE_AFP_DEV
RUNMODE_NETMAP
RUNMODE_TILERA_MPIPE
RUNMODE_UNITTEST
RUNMODE_NAPATECH
RUNMODE_UNIX_SOCKET
RUNMODE_USER_MAX
RUNMODE_LIST_KEYWORDS
RUNMODE_LIST_APP_LAYERS
RUNMODE_LIST_CUDA_CARDS
RUNMODE_LIST_RUNMODES
RUNMODE_PRINT_VERSION
RUNMODE_PRINT_BUILDINFO
RUNMODE_PRINT_USAGE
RUNMODE_DUMP_CONFIG
RUNMODE_CONF_TEST
RUNMODE_LIST_UNITTEST
RUNMODE_ENGINE_ANALYSIS
RUNMODE_MAX
Definition at line 27 of file runmodes.h.
Function Documentation
void RunModeDispatch (int , const char *)
Definition at line 270 of file runmodes.c.
References ConfGet(), PatternMatchDefaultMatcher(), RUNMODE_AFP_DEV, RUNMODE_DAG, RUNMODE_ERF_FILE, RUNMODE_IPFW, RUNMODE_NAPATECH, RUNMODE_NETMAP, RUNMODE_NFLOG, RUNMODE_NFQ, RUNMODE_PCAP_DEV, RUNMODE_PCAP_FILE, RUNMODE_PFRING, RUNMODE_TILERA_MPIPE, RUNMODE_UNIX_SOCKET, RunModeAFPGetDefaultMode(), RunModeErfDagGetDefaultMode(), RunModeErfFileGetDefaultMode(), RunModeFilePcapGetDefaultMode(), RunMode_::RunModeFunc, RunModeIdsGetDefaultMode(), RunModeIdsNflogGetDefaultMode(), RunModeIdsPfringGetDefaultMode(), RunModeIpsIPFWGetDefaultMode(), RunModeIpsNFQGetDefaultMode(), RunModeNapatechGetDefaultMode(), RunModeNetmapGetDefaultMode(), RunModeTileMpipeGetDefaultMode(), RunModeUnixSocketGetDefaultMode(), SC_ERR_MEM_ALLOC, SC_ERR_RUNMODE, SC_ERR_UNKNOWN_RUN_MODE, SCFree, SCLogError, SCLogWarning, SCStrdup, and unlikely.
Referenced by main().
char* RunmodeGetActive (void)
Return the running mode
The returned string must not be freed.
Returns
a string containing the current running mode
Definition at line 179 of file runmodes.c.
Referenced by ReceiveAFPThreadInit(), and ReceivePfringThreadInit().
const char* RunModeGetMainMode (void)
Return the running mode
The returned string must not be freed.
Returns
a string containing the current running mode
Definition at line 191 of file runmodes.c.
References RunmodeGetCurrent().
void RunModeInitialize (void)
Initialize multithreading settings.
Definition at line 910 of file runmodes.c.
References AffinitySetupLoadFromConfig(), ConfGetBool(), ConfGetFloat(), ConfGetNode(), FALSE, SCLogDebug, threading_detect_ratio, threading_set_cpu_affinity, TRUE, and WarnInvalidConfEntry.
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), RunModeIdsAFPWorkers(), RunModeIdsErfDagAutoFp(), RunModeIdsErfDagSingle(), RunModeIdsErfDagWorkers(), RunModeIdsNetmapAutoFp(), RunModeIdsNetmapSingle(), RunModeIdsNetmapWorkers(), RunModeIdsNflogAutoFp(), RunModeIdsNflogSingle(), RunModeIdsNflogWorkers(), RunModeIdsPcapAutoFp(), RunModeIdsPcapSingle(), RunModeIdsPcapWorkers(), RunModeIdsPfringAutoFp(), RunModeIdsPfringSingle(), RunModeIdsPfringWorkers(), RunModeIpsIPFWAutoFp(), RunModeIpsIPFWWorker(), RunModeIpsNFQAutoFp(), and RunModeIpsNFQWorker().
void RunModeInitializeOutputs (void)
Initialize the output modules.
Definition at line 688 of file runmodes.c.
References BUG_ON, OutputModule_::conf_name, ConfGetNode(), ConfNodeLookupChild(), ConfNodeLookupChildValue(), ConfValIsTrue(), FatalError, FatalErrorOnInit, OutputModule_::InitFunc, OutputModule_::InitSubFunc, m, OutputModule_::name, next, OutputGetModuleByConfName(), OutputModule_::parent_name, SC_ERR_CONF_YAML_ERROR, SC_ERR_INVALID_ARGUMENT, SC_ERR_NOT_SUPPORTED, SCLogDebug, SCLogInfo, SCLogWarning, TAILQ_FOREACH, type, and ConfNode_::val.
Referenced by main().
void RunModeListRunmodes (void)
Lists all registered runmodes.
Definition at line 227 of file runmodes.c.
References RunMode_::description, RunMode_::name, RunMode_::runmode, RUNMODE_UNKNOWN, and RUNMODE_USER_MAX.
Referenced by StartInternalRunMode().
int RunModeOutputFiledataEnabled (void)
Definition at line 455 of file runmodes.c.
int RunModeOutputFileEnabled (void)
Definition at line 450 of file runmodes.c.
void RunModeRegisterNewRunMode (int runmode, const char * name, const char * description, int(*)(void) RunModeFunc)
Registers a new runmode.
Parameters
runmode Runmode type.
name Custom mode for this specific runmode type. Within each runmode type, each custom name is a primary key.
description Description for this runmode.
RunModeFunc The function to be run for this runmode.
Definition at line 385 of file runmodes.c.
References RunMode_::description, RunMode_::name, RunMode_::runmode, RunMode_::RunModeFunc, SC_ERR_MEM_ALLOC, SC_ERR_RUNMODE, SCFree, SCLogError, SCRealloc, SCStrdup, and unlikely.
Referenced by RunModeErfDagRegister(), RunModeErfFileRegister(), RunModeFilePcapRegister(), RunModeIdsAFPRegister(), RunModeIdsNetmapRegister(), RunModeIdsNflogRegister(), RunModeIdsPcapRegister(), RunModeIdsPfringRegister(), RunModeIpsIPFWRegister(), RunModeIpsNFQRegister(), RunModeNapatechRegister(), RunModeTileMpipeRegister(), and RunModeUnixSocketRegister().
void RunModeRegisterRunModes (void)
Register all runmodes in the engine.
Definition at line 201 of file runmodes.c.
References RunModeErfDagRegister(), RunModeErfFileRegister(), RunModeFilePcapRegister(), RunModeIdsAFPRegister(), RunModeIdsNetmapRegister(), RunModeIdsNflogRegister(), RunModeIdsPcapRegister(), RunModeIdsPfringRegister(), RunModeIpsIPFWRegister(), RunModeIpsNFQRegister(), RunModeNapatechRegister(), RunModeTileMpipeRegister(), and RunModeUnixSocketRegister().
Referenced by main().
void RunModeShutDown (void)
Cleanup the run mode.
Definition at line 463 of file runmodes.c.
References TmModule_::name, OutputFiledataShutdown(), OutputFileShutdown(), OutputFlowShutdown(), OutputPacketShutdown(), OutputStatsShutdown(), OutputStreamingShutdown(), OutputTxShutdown(), RunOutputFreeList(), SCFree, SCLogDebug, TAILQ_FIRST, TAILQ_REMOVE, and RunModeOutput_::tm_module.
Referenced by main().
void SetupOutputs (ThreadVars * tv)
Setup the outputs for this run mode.
Parameters
tv The ThreadVars for the thread the outputs will be appended to.
Definition at line 896 of file runmodes.c.
References TmModule_::cap_flags, ThreadVars_::cap_flags, RunModeOutput_::output_ctx, TAILQ_FOREACH, RunModeOutput_::tm_module, and TmSlotSetFuncAppend().
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), and RunModeSetLiveCaptureAutoFp().
Variable Documentation
int debuglog_enabled
Definition at line 52 of file runmodes.c.
Referenced by SigMatchSignatures().
float threading_detect_ratio
Definition at line 905 of file runmodes.c.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeInitialize(), RunModeSetIPSAutoFp(), and RunModeSetLiveCaptureAutoFp().
int threading_set_cpu_affinity
Definition at line 95 of file runmodes.h.
Referenced by RunModeErfFileAutoFp(), RunModeInitialize(), and TmThreadSetCPU().