suricata: src/runmode-tile.h File Reference
runmode-tile.h File Reference
#include "suricata-common.h"
Functions
const char * RunModeTileMpipeGetDefaultMode (void)
void RunModeTileMpipeRegister (void)
int RunModeTileMpipeWorkers (void)
void * ParseMpipeConfig (const char *iface)
Variables
int tile_num_pipelines
Detailed Description
Author
Tom DeCanio decan.nosp@m.io.t.nosp@m.om@gm.nosp@m.ail..nosp@m.com
Ken Steele, Tilera Corporation suric.nosp@m.ata@.nosp@m.tiler.nosp@m.a.co.nosp@m.m
Tilera TILE-Gx runmode support
Definition in file runmode-tile.h.
Function Documentation
void* ParseMpipeConfig (const char * iface)
const char* RunModeTileMpipeGetDefaultMode (void)
Definition at line 54 of file runmode-tile.c.
Referenced by RunModeDispatch().
void RunModeTileMpipeRegister (void)
Definition at line 59 of file runmode-tile.c.
References RUNMODE_TILERA_MPIPE, RunModeRegisterNewRunMode(), and RunModeTileMpipeWorkers().
Referenced by RunModeRegisterRunModes().
int RunModeTileMpipeWorkers (void)
Referenced by RunModeTileMpipeRegister().
Variable Documentation
int tile_num_pipelines