suricata: src/runmode-nflog.h File Reference
runmode-nflog.h File Reference
Functions
int RunModeIdsNflogAutoFp (void)
int RunModeIdsNflogSingle (void)
int RunModeIdsNflogWorkers (void)
void RunModeIdsNflogRegister (void)
const char * RunModeIdsNflogGetDefaultMode (void)
Detailed Description
Author
Giuseppe Longo giuse.nosp@m.ppel.nosp@m.ng@gm.nosp@m.ail..nosp@m.com
Definition in file runmode-nflog.h.
Function Documentation
int RunModeIdsNflogAutoFp (void)
Definition at line 172 of file runmode-nflog.c.
References NflogConfigGeThreadsCount(), ParseNflogConfig(), RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNflogRegister().
const char* RunModeIdsNflogGetDefaultMode (void)
Definition at line 39 of file runmode-nflog.c.
Referenced by RunModeDispatch().
void RunModeIdsNflogRegister (void)
Definition at line 44 of file runmode-nflog.c.
References RUNMODE_NFLOG, RunModeIdsNflogAutoFp(), RunModeIdsNflogSingle(), RunModeIdsNflogWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsNflogSingle (void)
Definition at line 200 of file runmode-nflog.c.
References NflogConfigGeThreadsCount(), ParseNflogConfig(), RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNflogRegister().
int RunModeIdsNflogWorkers (void)
Definition at line 228 of file runmode-nflog.c.
References NflogConfigGeThreadsCount(), ParseNflogConfig(), RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNflogRegister().