suricata: src/runmode-nfq.c File Reference
runmode-nfq.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-nfq.h"
#include "output.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-runmodes.h"
#include "util-device.h"
Functions
const char * RunModeIpsNFQGetDefaultMode (void)
void RunModeIpsNFQRegister (void)
int RunModeIpsNFQAutoFp (void)
int RunModeIpsNFQWorker (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Handling of NFQ runmodes.
Definition in file runmode-nfq.c.
Function Documentation
int RunModeIpsNFQAutoFp (void)
Definition at line 62 of file runmode-nfq.c.
References LiveDeviceHasNoStats(), NFQGetThread(), RunModeInitialize(), RunModeSetIPSAutoFp(), SCEnter, and TimeModeSetLive().
Referenced by RunModeIpsNFQRegister().
const char* RunModeIpsNFQGetDefaultMode (void)
Definition at line 44 of file runmode-nfq.c.
Referenced by RunModeDispatch().
void RunModeIpsNFQRegister (void)
Definition at line 49 of file runmode-nfq.c.
References RUNMODE_NFQ, RunModeIpsNFQAutoFp(), RunModeIpsNFQWorker(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIpsNFQWorker (void)
Definition at line 82 of file runmode-nfq.c.
References LiveDeviceHasNoStats(), NFQGetThread(), RunModeInitialize(), RunModeSetIPSWorker(), SCEnter, and TimeModeSetLive().
Referenced by RunModeIpsNFQRegister().