suricata: src/runmode-pfring.h File Reference
runmode-pfring.h File Reference
#include "suricata-common.h"
Functions
int RunModeIdsPfringAutoFp (void)
int RunModeIdsPfringSingle (void)
int RunModeIdsPfringWorkers (void)
void RunModeIdsPfringRegister (void)
const char * RunModeIdsPfringGetDefaultMode (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file runmode-pfring.h.
Function Documentation
int RunModeIdsPfringAutoFp (void)
Definition at line 416 of file runmode-pfring.c.
References PfringConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_MISSING_CONFIG_PARAM, SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, and TimeModeSetLive().
Referenced by RunModeIdsPfringRegister().
const char* RunModeIdsPfringGetDefaultMode (void)
Definition at line 39 of file runmode-pfring.c.
Referenced by RunModeDispatch().
void RunModeIdsPfringRegister (void)
Definition at line 48 of file runmode-pfring.c.
References RUNMODE_PFRING, RunModeIdsPfringAutoFp(), RunModeIdsPfringSingle(), RunModeIdsPfringWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsPfringSingle (void)
Definition at line 453 of file runmode-pfring.c.
References PfringConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_MISSING_CONFIG_PARAM, SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, and TimeModeSetLive().
Referenced by RunModeIdsPfringRegister().
int RunModeIdsPfringWorkers (void)
Definition at line 490 of file runmode-pfring.c.
References PfringConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_MISSING_CONFIG_PARAM, SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, and TimeModeSetLive().
Referenced by RunModeIdsPfringRegister().