suricata: src/runmode-nflog.c File Reference
runmode-nflog.c File Reference
#include "suricata-common.h"
#include "config.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-nflog.h"
#include "util-debug.h"
#include "util-device.h"
#include "util-runmodes.h"
#include "util-misc.h"
#include "source-nflog.h"
Functions
const char * RunModeIdsNflogGetDefaultMode (void)
void RunModeIdsNflogRegister (void)
void * ParseNflogConfig (const char *group)
int NflogConfigGeThreadsCount (void *conf)
int RunModeIdsNflogAutoFp (void)
int RunModeIdsNflogSingle (void)
int RunModeIdsNflogWorkers (void)
Detailed Description
Author
Giuseppe Longo giuse.nosp@m.ppel.nosp@m.ng@gm.nosp@m.ail..nosp@m.com
Definition in file runmode-nflog.c.
Function Documentation
int NflogConfigGeThreadsCount (void * conf)
Definition at line 166 of file runmode-nflog.c.
Referenced by RunModeIdsNflogAutoFp(), RunModeIdsNflogSingle(), and RunModeIdsNflogWorkers().
void* ParseNflogConfig (const char * group)
Definition at line 66 of file runmode-nflog.c.
References ConfGetChildValueIntWithDefault(), ConfGetNode(), ConfNodeLookupKeyValue(), NflogGroupConfig_::DerefFunc, NflogGroupConfig_::group, NflogGroupConfig_::nful_overrun_warned, NflogGroupConfig_::nlbufsiz, NflogGroupConfig_::nlbufsiz_max, NflogGroupConfig_::numgroup, ParseSizeStringU16(), NflogGroupConfig_::qthreshold, NflogGroupConfig_::qtimeout, SC_ERR_INVALID_ARGUMENT, SC_ERR_NFLOG_GROUP, SCFree, SCLogError, SCLogInfo, SCLogWarning, SCMalloc, strlcpy(), and unlikely.
Referenced by RunModeIdsNflogAutoFp(), RunModeIdsNflogSingle(), and RunModeIdsNflogWorkers().
int RunModeIdsNflogAutoFp (void)
Definition at line 172 of file runmode-nflog.c.
References NflogConfigGeThreadsCount(), ParseNflogConfig(), RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNflogRegister().
const char* RunModeIdsNflogGetDefaultMode (void)
Definition at line 39 of file runmode-nflog.c.
Referenced by RunModeDispatch().
void RunModeIdsNflogRegister (void)
Definition at line 44 of file runmode-nflog.c.
References RUNMODE_NFLOG, RunModeIdsNflogAutoFp(), RunModeIdsNflogSingle(), RunModeIdsNflogWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsNflogSingle (void)
Definition at line 200 of file runmode-nflog.c.
References NflogConfigGeThreadsCount(), ParseNflogConfig(), RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNflogRegister().
int RunModeIdsNflogWorkers (void)
Definition at line 228 of file runmode-nflog.c.
References NflogConfigGeThreadsCount(), ParseNflogConfig(), RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNflogRegister().