suricata: src/runmode-erf-dag.h File Reference
runmode-erf-dag.h File Reference
Functions
int RunModeIdsErfDagAutoFp (void)
int RunModeIdsErfDagSingle (void)
int RunModeIdsErfDagWorkers (void)
void RunModeErfDagRegister (void)
const char * RunModeErfDagGetDefaultMode (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file runmode-erf-dag.h.
Function Documentation
const char* RunModeErfDagGetDefaultMode (void)
Definition at line 45 of file runmode-erf-dag.c.
Referenced by RunModeDispatch().
void RunModeErfDagRegister (void)
Definition at line 50 of file runmode-erf-dag.c.
References RUNMODE_DAG, RunModeIdsErfDagAutoFp(), RunModeIdsErfDagSingle(), RunModeIdsErfDagWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsErfDagAutoFp (void)
Definition at line 100 of file runmode-erf-dag.c.
References RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeErfDagRegister().
int RunModeIdsErfDagSingle (void)
Definition at line 74 of file runmode-erf-dag.c.
References RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeErfDagRegister().
int RunModeIdsErfDagWorkers (void)
Definition at line 126 of file runmode-erf-dag.c.
References RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeErfDagRegister().