suricata: src/runmode-pcap.h File Reference
runmode-pcap.h File Reference
Functions
int RunModeIdsPcapSingle (void)
Single thread version of the Pcap live processing.
int RunModeIdsPcapAutoFp (void)
RunModIdsPcapAutoFp set up the following thread packet handlers:
void RunModeIdsPcapRegister (void)
const char * RunModeIdsGetDefaultMode (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file runmode-pcap.h.
Function Documentation
const char* RunModeIdsGetDefaultMode (void)
Definition at line 37 of file runmode-pcap.c.
Referenced by RunModeDispatch().
int RunModeIdsPcapAutoFp (void)
RunModIdsPcapAutoFp set up the following thread packet handlers:
   - Receive thread (from pcap device)
   - Decode thread
   - Stream thread
   - Detect: If we have only 1 cpu, it will setup one Detect thread
             If we have more than one, it will setup num_cpus - 1
             starting from the second cpu available.
   - Outputs thread
   By default the threads will use the first cpu available
   except the Detection threads if we have more than one cpu.
Return values
0 If all goes well. (If any problem is detected the engine will exit()).
Definition at line 272 of file runmode-pcap.c.
References ConfGet(), ParsePcapConfig(), PcapConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsPcapRegister().
void RunModeIdsPcapRegister (void)
Definition at line 44 of file runmode-pcap.c.
References RUNMODE_PCAP_DEV, RunModeIdsPcapAutoFp(), RunModeIdsPcapSingle(), RunModeIdsPcapWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsPcapSingle (void)
Single thread version of the Pcap live processing.
Definition at line 230 of file runmode-pcap.c.
References ConfGet(), ParsePcapConfig(), PcapConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsPcapRegister().