suricata: src/runmode-netmap.h File Reference
runmode-netmap.h File Reference
Functions
int RunModeIdsNetmapSingle (void)
Single thread version of the netmap processing.
int RunModeIdsNetmapAutoFp (void)
int RunModeIdsNetmapWorkers (void)
Workers version of the netmap processing.
void RunModeIdsNetmapRegister (void)
const char * RunModeNetmapGetDefaultMode (void)
int NetmapRunModeIsIPS ()
Detailed Description
Author
Aleksey Katargin guree.nosp@m.do@g.nosp@m.mail..nosp@m.com
Definition in file runmode-netmap.h.
Function Documentation
int NetmapRunModeIsIPS ()
int RunModeIdsNetmapAutoFp (void)
Definition at line 355 of file runmode-netmap.c.
References ConfGet(), RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_RUNMODE, SCEnter, SCLogDebug, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNetmapRegister().
void RunModeIdsNetmapRegister (void)
Definition at line 67 of file runmode-netmap.c.
References RUNMODE_NETMAP, RunModeIdsNetmapAutoFp(), RunModeIdsNetmapSingle(), RunModeIdsNetmapWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsNetmapSingle (void)
Single thread version of the netmap processing.
Definition at line 391 of file runmode-netmap.c.
References ConfGet(), RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNetmapRegister().
int RunModeIdsNetmapWorkers (void)
Workers version of the netmap processing.
Start N threads with each thread doing all the work.
Definition at line 427 of file runmode-netmap.c.
References ConfGet(), RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNetmapRegister().
const char* RunModeNetmapGetDefaultMode (void)
Definition at line 62 of file runmode-netmap.c.
Referenced by RunModeDispatch().