suricata: src/runmode-unittests.c File Reference
runmode-unittests.c File Reference
#include "suricata-common.h"
#include "config.h"
#include "util-unittest.h"
Functions
void RegisterAllModules ()
void TmqhSetup (void)
void RunUnittests (int list_unittests, char *regex_arg)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file runmode-unittests.c.
Function Documentation
void RegisterAllModules ()
Definition at line 802 of file suricata.c.
References TmModuleAlertDebugLogRegister(), TmModuleAlertFastLogRegister(), TmModuleAlertPreludeRegister(), TmModuleAlertSyslogRegister(), TmModuleDebugList(), TmModuleDecodeAFPRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFLOGRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDetectRegister(), TmModuleFiledataLoggerRegister(), TmModuleFileLoggerRegister(), TmModuleFlowManagerRegister(), TmModuleFlowRecyclerRegister(), TmModuleJsonAlertLogRegister(), TmModuleJsonDnsLogRegister(), TmModuleJsonDropLogRegister(), TmModuleJsonFileLogRegister(), TmModuleJsonFlowLogRegister(), TmModuleJsonHttpLogRegister(), TmModuleJsonNetFlowLogRegister(), TmModuleJsonSmtpLogRegister(), TmModuleJsonSshLogRegister(), TmModuleJsonStatsLogRegister(), TmModuleJsonTemplateLogRegister(), TmModuleJsonTlsLogRegister(), TmModuleLogDnsLogRegister(), TmModuleLogDropLogRegister(), TmModuleLogFileLogRegister(), TmModuleLogFilestoreRegister(), TmModuleLogHttpLogRegister(), TmModuleLogStatsLogRegister(), TmModuleLogTcpDataLogRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), TmModuleLuaLogRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleOutputJsonRegister(), TmModulePacketLoggerRegister(), TmModulePcapLogRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFLOGRegister(), TmModuleReceiveNFQRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleRespondRejectRegister(), TmModuleStatsLoggerRegister(), TmModuleStreamingLoggerRegister(), TmModuleStreamTcpRegister(), TmModuleTxLoggerRegister(), TmModuleUnified2AlertRegister(), TmModuleUnixManagerRegister(), TmModuleVerdictIPFWRegister(), and TmModuleVerdictNFQRegister().
Referenced by RunUnittests().
void RunUnittests (int list_unittests, char * regex_arg)
Run or list unittests
Parameters
list_unittests If set to 1, list unittests. Run them if set to 0.
regex_arg A regular expression to select unittests to run
This function is terminal and will call exit after being called.
Definition at line 135 of file runmode-unittests.c.
References AppLayerHtpEnableRequestBodyCallback(), AppLayerHtpNeedFileInspection(), AppLayerSetup(), BloomFilterCountingRegisterTests(), BloomFilterRegisterTests(), ByteRegisterTests(), CIDRInit(), ConfRegisterTests(), ConfYamlRegisterTests(), CudaHandlerFreeProfiles(), DcePayloadRegisterTests(), DecodeAsn1RegisterTests(), DecodeGRERegisterTests(), DecodeICMPV4RegisterTests(), DecodeICMPV6RegisterTests(), DecodeIPV4RegisterTests(), DecodeIPV6RegisterTests(), DecodeMPLSRegisterTests(), DecodePPPOERegisterTests(), DecodePPPRegisterTests(), DecodeRawRegisterTests(), DecodeTCPRegisterTests(), DecodeUDPV4RegisterTests(), DecodeVLANRegisterTests(), DEFAULT_PACKET_SIZE, default_packet_size, DefragRegisterTests(), DeStateRegisterTests(), DetectAddressTests(), DetectEngineHttpClientBodyRegisterTests(), DetectEngineHttpCookieRegisterTests(), DetectEngineHttpHeaderRegisterTests(), DetectEngineHttpHHRegisterTests(), DetectEngineHttpHRHRegisterTests(), DetectEngineHttpMethodRegisterTests(), DetectEngineHttpRawHeaderRegisterTests(), DetectEngineHttpRawUriRegisterTests(), DetectEngineHttpServerBodyRegisterTests(), DetectEngineHttpStatCodeRegisterTests(), DetectEngineHttpStatMsgRegisterTests(), DetectEngineHttpUARegisterTests(), DetectEngineInspectModbusRegisterTests(), DetectEngineRegisterAppInspectionEngines(), DetectEngineRegisterTests(), DetectEngineSMTPFiledataRegisterTests(), DetectPortTests(), DetectProtoTests(), DetectRingBufferRegisterTests(), FlowBitRegisterTests(), FlowRegisterTests(), GlobalInits(), HashListTableRegisterTests(), HashTableRegisterTests(), HostBitInitCtx(), HostBitRegisterTests(), HostRegisterUnittests(), HTPParserRegisterTests(), IPPairBitRegisterTests(), IPPairRegisterUnittests(), MagicRegisterTests(), max_pending_packets, MemcmpRegisterTests(), MemrchrRegisterTests(), MimeDecRegisterTests(), MpmRegisterTests(), MpmTableSetup(), PacketPoolDestroy(), PacketPoolInit(), PatternMatchDefaultMatcher(), PayloadRegisterTests(), PoolRegisterTests(), RegisterAllModules(), SC_ERR_NOT_SUPPORTED, SCAtomicRegisterTests(), SCClassConfInit(), SCClassConfRegisterTests(), SCHInfoRegisterTests(), SCLogError, SCLogInfo, SCLogRegisterTests(), SCProfilingRegisterTests(), SCProtoNameInit(), SCRadixRegisterTests(), SCRConfRegisterTests(), SCReferenceConfInit(), SCReputationInitCtx(), SCReputationRegisterTests(), SCRuleVarsRegisterTests(), SCSigRegisterSignatureOrderingTests(), SCThresholdConfRegisterTests(), SigGroupHeadRegisterTests(), SigParsePrepare(), SigTableRegisterTests(), SigTableSetup(), StatsRegisterTests(), StorageFinalize(), StorageInit(), SupportFastPatternForSigMatchTypes(), TagInitCtx(), ThreadMacrosRegisterTests(), TimeInit(), TmModuleRegisterTests(), TmqhFlowRegisterTests(), TmqhSetup(), UriRegisterTests(), UTHRegisterTests(), UtilActionRegisterTests(), UtilMiscRegisterTests(), UtilSpmSearchRegistertests(), and UtRunSelftest().
Referenced by main(), and StartInternalRunMode().
void TmqhSetup (void)
Definition at line 39 of file tm-queuehandlers.c.
Referenced by RunUnittests().