suricata: src/runmode-unix-socket.c File Reference
runmode-unix-socket.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-pcap-file.h"
#include "output.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "unix-manager.h"
#include "detect-engine.h"
#include "flow-manager.h"
#include "flow-timeout.h"
#include "stream-tcp.h"
#include "host.h"
#include "defrag.h"
#include "ippair.h"
#include "app-layer.h"
#include "util-profiling.h"
#include "conf-yaml-loader.h"
Data Structures
struct PcapFiles_
struct PcapCommand_
Typedefs
typedef struct PcapFiles_ PcapFiles
typedef struct PcapCommand_ PcapCommand
Functions
const char * RunModeUnixSocketGetDefaultMode (void)
void RunModeUnixSocketRegister (void)
void UnixSocketPcapFile (TmEcode tm)
int RunModeUnixSocketSingle (void)
Single thread version of the Pcap file processing.
int RunModeUnixSocketIsActive (void)
Variables
int unix_socket_mode_is_running = 0
Typedef Documentation
typedef struct PcapCommand_ PcapCommand
typedef struct PcapFiles_ PcapFiles
Function Documentation
const char* RunModeUnixSocketGetDefaultMode (void)
Definition at line 65 of file runmode-unix-socket.c.
Referenced by RunModeDispatch().
int RunModeUnixSocketIsActive (void)
Definition at line 831 of file runmode-unix-socket.c.
References unix_socket_mode_is_running.
Referenced by ReceivePcapFileLoop(), and ReceivePcapFileThreadInit().
void RunModeUnixSocketRegister (void)
Definition at line 401 of file runmode-unix-socket.c.
References RUNMODE_UNIX_SOCKET, RunModeRegisterNewRunMode(), and RunModeUnixSocketSingle().
Referenced by RunModeRegisterRunModes().
int RunModeUnixSocketSingle (void)
Single thread version of the Pcap file processing.
Definition at line 803 of file runmode-unix-socket.c.
References SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, TAILQ_INIT, UNIX_CMD_TAKE_ARGS, unix_socket_mode_is_running, UnixManagerThreadSpawn(), and unlikely.
Referenced by RunModeUnixSocketRegister().
void UnixSocketPcapFile (TmEcode tm)
Definition at line 412 of file runmode-unix-socket.c.
References TM_ECODE_DONE, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by ReceivePcapFileLoop(), and ReceivePcapFileThreadInit().
Variable Documentation
int unix_socket_mode_is_running = 0
Definition at line 50 of file runmode-unix-socket.c.
Referenced by RunModeUnixSocketIsActive(), and RunModeUnixSocketSingle().