suricata: src/runmode-pfring.c File Reference
runmode-pfring.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-pfring.h"
#include "source-pfring.h"
#include "output.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-runmodes.h"
#include "util-device.h"
Macros
#define PFRING_CONF_V1 1
#define PFRING_CONF_V2 2
Functions
const char * RunModeIdsPfringGetDefaultMode (void)
void RunModeIdsPfringRegister (void)
void PfringDerefConfig (void *conf)
void * OldParsePfringConfig (const char *iface)
extract information from config file
void * ParsePfringConfig (const char *iface)
extract information from config file
int PfringConfigGeThreadsCount (void *conf)
int PfringConfLevel ()
int RunModeIdsPfringAutoFp (void)
int RunModeIdsPfringSingle (void)
int RunModeIdsPfringWorkers (void)
Macro Definition Documentation
#define PFRING_CONF_V1 1
Definition at line 36 of file runmode-pfring.c.
Referenced by PfringConfLevel().
#define PFRING_CONF_V2 2
Definition at line 37 of file runmode-pfring.c.
Referenced by PfringConfLevel().
Function Documentation
void* OldParsePfringConfig (const char * iface)
extract information from config file
The returned structure will be freed by the thread init function. This is thus necessary to or copy the structure before giving it to thread or to reparse the file for each thread (and thus have new structure.
If old config system is used, then return the smae parameters value for each interface.
Returns
a PfringIfaceConfig corresponding to the interface name
Definition at line 92 of file runmode-pfring.c.
References PfringIfaceConfig_::checksum_mode, CHECKSUM_VALIDATION_AUTO, PfringIfaceConfig_::cluster_id, CLUSTER_ROUND_ROBIN, ConfGet(), PfringIfaceConfig_::ctype, PfringIfaceConfig_::DerefFunc, PfringIfaceConfig_::flags, PfringIfaceConfig_::iface, PFRING_CONF_FLAGS_CLUSTER, PfringDerefConfig(), SC_ATOMIC_ADD, SC_ATOMIC_INIT, SC_ATOMIC_RESET, SC_ERR_GET_CLUSTER_TYPE_FAILED, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_CLUSTER_TYPE, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, strlcpy(), PfringIfaceConfig_::threads, and unlikely.
void* ParsePfringConfig (const char * iface)
extract information from config file
The returned structure will be freed by the thread init function. This is thus necessary to or copy the structure before giving it to thread or to reparse the file for each thread (and thus have new structure.
If old config system is used, then return the smae parameters value for each interface.
Returns
a PfringIfaceConfig corresponding to the interface name
Definition at line 191 of file runmode-pfring.c.
References PfringIfaceConfig_::bpf_filter, PfringIfaceConfig_::checksum_mode, CHECKSUM_VALIDATION_AUTO, CHECKSUM_VALIDATION_DISABLE, CHECKSUM_VALIDATION_ENABLE, CHECKSUM_VALIDATION_RXONLY, CLUSTER_FLOW, PfringIfaceConfig_::cluster_id, CLUSTER_ROUND_ROBIN, ConfGet(), ConfGetChildValueWithDefault(), ConfGetNode(), ConfNodeLookupKeyValue(), PfringIfaceConfig_::ctype, PfringIfaceConfig_::DerefFunc, PfringIfaceConfig_::flags, PfringIfaceConfig_::iface, PFRING_CONF_FLAGS_CLUSTER, PfringDerefConfig(), SC_ATOMIC_ADD, SC_ATOMIC_INIT, SC_ATOMIC_RESET, SC_ERR_GET_CLUSTER_TYPE_FAILED, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_CLUSTER_TYPE, SC_ERR_MEM_ALLOC, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, SCStrdup, strlcpy(), PfringIfaceConfig_::threads, and unlikely.
int PfringConfigGeThreadsCount (void * conf)
Definition at line 371 of file runmode-pfring.c.
References PfringIfaceConfig_::threads.
Referenced by RunModeIdsPfringAutoFp(), RunModeIdsPfringSingle(), and RunModeIdsPfringWorkers().
int PfringConfLevel ()
Definition at line 377 of file runmode-pfring.c.
References ConfGet(), PFRING_CONF_V1, and PFRING_CONF_V2.
void PfringDerefConfig (void * conf)
Definition at line 68 of file runmode-pfring.c.
References PfringIfaceConfig_::bpf_filter, SC_ATOMIC_SUB, and SCFree.
Referenced by OldParsePfringConfig(), and ParsePfringConfig().
int RunModeIdsPfringAutoFp (void)
Definition at line 416 of file runmode-pfring.c.
References PfringConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_MISSING_CONFIG_PARAM, SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, and TimeModeSetLive().
Referenced by RunModeIdsPfringRegister().
const char* RunModeIdsPfringGetDefaultMode (void)
Definition at line 39 of file runmode-pfring.c.
Referenced by RunModeDispatch().
void RunModeIdsPfringRegister (void)
Definition at line 48 of file runmode-pfring.c.
References RUNMODE_PFRING, RunModeIdsPfringAutoFp(), RunModeIdsPfringSingle(), RunModeIdsPfringWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsPfringSingle (void)
Definition at line 453 of file runmode-pfring.c.
References PfringConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_MISSING_CONFIG_PARAM, SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, and TimeModeSetLive().
Referenced by RunModeIdsPfringRegister().
int RunModeIdsPfringWorkers (void)
Definition at line 490 of file runmode-pfring.c.
References PfringConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_MISSING_CONFIG_PARAM, SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, and TimeModeSetLive().
Referenced by RunModeIdsPfringRegister().