suricata: src/runmode-af-packet.c File Reference
runmode-af-packet.c File Reference
AF_PACKET running mode
#include "suricata-common.h"
#include "config.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-af-packet.h"
#include "log-httplog.h"
#include "output.h"
#include "detect-engine-mpm.h"
#include "alert-fastlog.h"
#include "alert-prelude.h"
#include "alert-unified2-alert.h"
#include "alert-debuglog.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-device.h"
#include "util-runmodes.h"
#include "util-ioctl.h"
#include "source-af-packet.h"
int max_pending_packets
const char * RunModeAFPGetDefaultMode (void)
void RunModeIdsAFPRegister (void)
void AFPDerefConfig (void *conf)
void * ParseAFPConfig (const char *iface)
extract information from config file
int AFPConfigGeThreadsCount (void *conf)
int AFPRunModeIsIPS ()
int RunModeIdsAFPAutoFp (void)
int RunModeIdsAFPSingle (void)
Single thread version of the AF_PACKET processing.
int RunModeIdsAFPWorkers (void)
Workers version of the AF_PACKET processing.
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
AF_PACKET socket runmode
Definition in file runmode-af-packet.c.
Function Documentation
int AFPConfigGeThreadsCount (void * conf)
Definition at line 373 of file runmode-af-packet.c.
References AFPIfaceConfig_::threads.
Referenced by RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), and RunModeIdsAFPWorkers().
void AFPDerefConfig (void * conf)
Definition at line 86 of file runmode-af-packet.c.
References SC_ATOMIC_SUB, and SCFree.
Referenced by ParseAFPConfig().
int AFPRunModeIsIPS ()
Definition at line 379 of file runmode-af-packet.c.
References ConfGetChildValueWithDefault(), ConfGetNode(), ConfNodeLookupKeyValue(), LiveGetDeviceCount(), LiveGetDeviceName(), SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SCLogError, and SCLogInfo.
void* ParseAFPConfig (const char * iface)
extract information from config file
The returned structure will be freed by the thread init function. This is thus necessary to or copy the structure before giving it to thread or to reparse the file for each thread (and thus have new structure.
Returns
a AFPIfaceConfig corresponding to the interface name
Definition at line 105 of file runmode-af-packet.c.
References AFP_COPY_MODE_IPS, AFP_COPY_MODE_NONE, AFP_COPY_MODE_TAP, AFP_EMERGENCY_MODE, AFP_RING_MODE, AFPDerefConfig(), AFPIfaceConfig_::bpf_filter, AFPIfaceConfig_::buffer_size, AFPIfaceConfig_::checksum_mode, CHECKSUM_VALIDATION_AUTO, CHECKSUM_VALIDATION_DISABLE, CHECKSUM_VALIDATION_ENABLE, CHECKSUM_VALIDATION_KERNEL, AFPIfaceConfig_::cluster_id, AFPIfaceConfig_::cluster_type, ConfGet(), ConfGetChildValueBoolWithDefault(), ConfGetChildValueIntWithDefault(), ConfGetChildValueWithDefault(), ConfGetNode(), ConfNodeLookupKeyValue(), AFPIfaceConfig_::copy_mode, AFPIfaceConfig_::DerefFunc, AFPIfaceConfig_::flags, GetIfaceOffloading(), GetIfaceRSSQueuesNum(), AFPIfaceConfig_::iface, max_pending_packets, AFPIfaceConfig_::out_iface, PACKET_FANOUT_CPU, PACKET_FANOUT_FLAG_DEFRAG, PACKET_FANOUT_FLAG_ROLLOVER, PACKET_FANOUT_HASH, PACKET_FANOUT_LB, PACKET_FANOUT_QM, PACKET_FANOUT_RND, PACKET_FANOUT_ROLLOVER, AFPIfaceConfig_::promisc, AFPIfaceConfig_::ring_size, SC_ATOMIC_ADD, SC_ATOMIC_INIT, SC_ATOMIC_RESET, SC_ERR_AFP_CREATE, SC_ERR_GET_CLUSTER_TYPE_FAILED, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_CLUSTER_TYPE, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCLogWarning, SCMalloc, strlcpy(), AFPIfaceConfig_::threads, unlikely, and UtilCpuGetNumProcessorsOnline().
Referenced by RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), and RunModeIdsAFPWorkers().
const char* RunModeAFPGetDefaultMode (void)
Definition at line 63 of file runmode-af-packet.c.
Referenced by RunModeDispatch().
int RunModeIdsAFPAutoFp (void)
Definition at line 457 of file runmode-af-packet.c.
References AFPConfigGeThreadsCount(), AFPPeersListCheck(), AFPPeersListInit(), ConfGet(), ParseAFPConfig(), RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_RUNMODE, SCEnter, SCLogDebug, SCLogError, SCLogInfo, SCReturnInt, TimeModeSetLive(), and TM_ECODE_OK.
Referenced by RunModeIdsAFPRegister().
void RunModeIdsAFPRegister (void)
Definition at line 68 of file runmode-af-packet.c.
References RUNMODE_AFP_DEV, RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), RunModeIdsAFPWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsAFPSingle (void)
Single thread version of the AF_PACKET processing.
Definition at line 504 of file runmode-af-packet.c.
References AFPConfigGeThreadsCount(), AFPPeersListCheck(), AFPPeersListInit(), ConfGet(), ParseAFPConfig(), RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, TimeModeSetLive(), and TM_ECODE_OK.
Referenced by RunModeIdsAFPRegister().
int RunModeIdsAFPWorkers (void)
Workers version of the AF_PACKET processing.
Start N threads with each thread doing all the work.
Definition at line 549 of file runmode-af-packet.c.
References AFPConfigGeThreadsCount(), AFPPeersListCheck(), AFPPeersListInit(), ConfGet(), ParseAFPConfig(), RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, TimeModeSetLive(), and TM_ECODE_OK.
Referenced by RunModeIdsAFPRegister().
Variable Documentation
int max_pending_packets
Maximum packets to simultaneously process.
Definition at line 233 of file suricata.c.
Referenced by PacketPoolInit(), PacketPoolPostRunmodes(), ParseAFPConfig(), ReceiveNFQThreadInit(), and RunUnittests().