suricata: src/runmode-pcap-file.c File Reference
runmode-pcap-file.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-pcap-file.h"
#include "output.h"
#include "detect-engine.h"
#include "source-pcap-file.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-runmodes.h"
Functions
const char * RunModeFilePcapGetDefaultMode (void)
void RunModeFilePcapRegister (void)
int RunModeFilePcapSingle (void)
Single thread version of the Pcap file processing.
int RunModeFilePcapAutoFp (void)
RunModeFilePcapAutoFp set up the following thread packet handlers:
Function Documentation
int RunModeFilePcapAutoFp (void)
RunModeFilePcapAutoFp set up the following thread packet handlers:
   - Receive thread (from pcap file)
   - Decode thread
   - Stream thread
   - Detect: If we have only 1 cpu, it will setup one Detect thread
             If we have more than one, it will setup num_cpus - 1
             starting from the second cpu available.
   - Outputs thread
   By default the threads will use the first cpu available
   except the Detection threads if we have more than one cpu.
Return values
0 If all goes well. (If any problem is detected the engine will exit()).
Definition at line 142 of file runmode-pcap-file.c.
References ConfGet(), DETECT_CPU_SET, DetectEngineEnabled(), PcapFileGlobalInit(), RECEIVE_CPU_SET, RunmodeAutoFpCreatePickupQueuesString(), RunModeInitialize(), RunmodeSetFlowStreamAsync(), SC_ERR_FATAL, SC_ERR_RUNMODE, SCEnter, SCFree, SCLogDebug, SCLogError, SCStrdup, SetupOutputs(), ThreadVars_::thread_group_name, threading_detect_ratio, TimeModeSetOffline(), TM_ECODE_OK, TM_QUEUE_NAME_MAX, TM_THREAD_NAME_MAX, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadGetNbThreads(), TmThreadSetCPU(), TmThreadSpawn(), unlikely, and UtilCpuGetNumProcessorsOnline().
Referenced by RunModeFilePcapRegister().
const char* RunModeFilePcapGetDefaultMode (void)
Definition at line 37 of file runmode-pcap-file.c.
Referenced by RunModeDispatch().
void RunModeFilePcapRegister (void)
Definition at line 42 of file runmode-pcap-file.c.
References RUNMODE_PCAP_FILE, RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeFilePcapSingle (void)
Single thread version of the Pcap file processing.
Definition at line 62 of file runmode-pcap-file.c.
References ConfGet(), DETECT_CPU_SET, DetectEngineEnabled(), PcapFileGlobalInit(), RunModeInitialize(), SC_ERR_RUNMODE, SCLogError, SetupOutputs(), TimeModeSetOffline(), TM_ECODE_OK, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadSetCPU(), and TmThreadSpawn().
Referenced by RunModeFilePcapRegister().