suricata: src/runmode-nfq.h File Reference
runmode-nfq.h File Reference
Functions
int RunModeIpsNFQAutoFp (void)
int RunModeIpsNFQWorker (void)
void RunModeIpsNFQRegister (void)
const char * RunModeIpsNFQGetDefaultMode (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file runmode-nfq.h.
Function Documentation
int RunModeIpsNFQAutoFp (void)
Definition at line 62 of file runmode-nfq.c.
References LiveDeviceHasNoStats(), NFQGetThread(), RunModeInitialize(), RunModeSetIPSAutoFp(), SCEnter, and TimeModeSetLive().
Referenced by RunModeIpsNFQRegister().
const char* RunModeIpsNFQGetDefaultMode (void)
Definition at line 44 of file runmode-nfq.c.
Referenced by RunModeDispatch().
void RunModeIpsNFQRegister (void)
Definition at line 49 of file runmode-nfq.c.
References RUNMODE_NFQ, RunModeIpsNFQAutoFp(), RunModeIpsNFQWorker(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIpsNFQWorker (void)
Definition at line 82 of file runmode-nfq.c.
References LiveDeviceHasNoStats(), NFQGetThread(), RunModeInitialize(), RunModeSetIPSWorker(), SCEnter, and TimeModeSetLive().
Referenced by RunModeIpsNFQRegister().