suricata: src/runmode-erf-file.h File Reference
runmode-erf-file.h File Reference
Functions
int RunModeErfFileSingle (void)
int RunModeErfFileAutoFp (void)
void RunModeErfFileRegister (void)
const char * RunModeErfFileGetDefaultMode (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file runmode-erf-file.h.
Function Documentation
int RunModeErfFileAutoFp (void)
Definition at line 125 of file runmode-erf-file.c.
References ConfGet(), DETECT_CPU_SET, DetectEngineEnabled(), PRIO_LOW, PRIO_MEDIUM, RunmodeAutoFpCreatePickupQueuesString(), RunModeInitialize(), RunmodeSetFlowStreamAsync(), SC_ERR_RUNMODE, SCEnter, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCReturnInt, SCStrdup, SetupOutputs(), ThreadVars_::thread_group_name, threading_detect_ratio, threading_set_cpu_affinity, TimeModeSetOffline(), TM_ECODE_OK, TM_QUEUE_NAME_MAX, TM_THREAD_NAME_MAX, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadGetNbThreads(), TmThreadSetCPUAffinity(), TmThreadSetThreadPriority(), TmThreadSpawn(), unlikely, and UtilCpuGetNumProcessorsOnline().
Referenced by RunModeErfFileRegister().
const char* RunModeErfFileGetDefaultMode (void)
Definition at line 36 of file runmode-erf-file.c.
Referenced by RunModeDispatch().
void RunModeErfFileRegister (void)
Definition at line 41 of file runmode-erf-file.c.
References RUNMODE_ERF_FILE, RunModeErfFileAutoFp(), RunModeErfFileSingle(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeErfFileSingle (void)
Definition at line 57 of file runmode-erf-file.c.
References ConfGet(), DetectEngineEnabled(), RunModeInitialize(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, SetupOutputs(), TimeModeSetOffline(), TM_ECODE_OK, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), and TmThreadSpawn().
Referenced by RunModeErfFileRegister().