suricata: src/runmode-netmap.c File Reference
runmode-netmap.c File Reference
Netmap running mode
#include "suricata-common.h"
#include "config.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-netmap.h"
#include "log-httplog.h"
#include "output.h"
#include "detect-engine-mpm.h"
#include "alert-fastlog.h"
#include "alert-prelude.h"
#include "alert-unified2-alert.h"
#include "alert-debuglog.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-device.h"
#include "util-runmodes.h"
#include "util-ioctl.h"
#include "source-netmap.h"
int max_pending_packets
const char * RunModeNetmapGetDefaultMode (void)
void RunModeIdsNetmapRegister (void)
int RunModeIdsNetmapAutoFp (void)
int RunModeIdsNetmapSingle (void)
Single thread version of the netmap processing.
int RunModeIdsNetmapWorkers (void)
Workers version of the netmap processing.
Detailed Description
Author
Aleksey Katargin guree.nosp@m.do@g.nosp@m.mail..nosp@m.com
Netmap runmode
Definition in file runmode-netmap.c.
Function Documentation
int RunModeIdsNetmapAutoFp (void)
Definition at line 355 of file runmode-netmap.c.
References ConfGet(), RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_RUNMODE, SCEnter, SCLogDebug, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNetmapRegister().
void RunModeIdsNetmapRegister (void)
Definition at line 67 of file runmode-netmap.c.
References RUNMODE_NETMAP, RunModeIdsNetmapAutoFp(), RunModeIdsNetmapSingle(), RunModeIdsNetmapWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsNetmapSingle (void)
Single thread version of the netmap processing.
Definition at line 391 of file runmode-netmap.c.
References ConfGet(), RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNetmapRegister().
int RunModeIdsNetmapWorkers (void)
Workers version of the netmap processing.
Start N threads with each thread doing all the work.
Definition at line 427 of file runmode-netmap.c.
References ConfGet(), RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsNetmapRegister().
const char* RunModeNetmapGetDefaultMode (void)
Definition at line 62 of file runmode-netmap.c.
Referenced by RunModeDispatch().
Variable Documentation
int max_pending_packets
Maximum packets to simultaneously process.
Definition at line 233 of file suricata.c.