suricata: src/runmode-tile.c File Reference
runmode-tile.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-tile.h"
#include "output.h"
#include "source-mpipe.h"
#include "detect-engine.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-device.h"
Functions
const char * RunModeTileMpipeGetDefaultMode (void)
void RunModeTileMpipeRegister (void)
Detailed Description
Author
Tom DeCanio decan.nosp@m.io.t.nosp@m.om@gm.nosp@m.ail..nosp@m.com
Ken Steele, Tilera Corporation suric.nosp@m.ata@.nosp@m.tiler.nosp@m.a.co.nosp@m.m
Tilera TILE-Gx runmode support
Definition in file runmode-tile.c.
Function Documentation
const char* RunModeTileMpipeGetDefaultMode (void)
Definition at line 54 of file runmode-tile.c.
Referenced by RunModeDispatch().
void RunModeTileMpipeRegister (void)
Definition at line 59 of file runmode-tile.c.
References RUNMODE_TILERA_MPIPE, RunModeRegisterNewRunMode(), and RunModeTileMpipeWorkers().
Referenced by RunModeRegisterRunModes().