suricata: src/runmode-unix-socket.h File Reference
runmode-unix-socket.h File Reference
Functions
int RunModeUnixSocketSingle (void)
Single thread version of the Pcap file processing.
void RunModeUnixSocketRegister (void)
const char * RunModeUnixSocketGetDefaultMode (void)
int RunModeUnixSocketIsActive (void)
void UnixSocketPcapFile (TmEcode tm)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file runmode-unix-socket.h.
Function Documentation
const char* RunModeUnixSocketGetDefaultMode (void)
Definition at line 65 of file runmode-unix-socket.c.
Referenced by RunModeDispatch().
int RunModeUnixSocketIsActive (void)
Definition at line 831 of file runmode-unix-socket.c.
References unix_socket_mode_is_running.
Referenced by ReceivePcapFileLoop(), and ReceivePcapFileThreadInit().
void RunModeUnixSocketRegister (void)
Definition at line 401 of file runmode-unix-socket.c.
References RUNMODE_UNIX_SOCKET, RunModeRegisterNewRunMode(), and RunModeUnixSocketSingle().
Referenced by RunModeRegisterRunModes().
int RunModeUnixSocketSingle (void)
Single thread version of the Pcap file processing.
Definition at line 803 of file runmode-unix-socket.c.
References SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, TAILQ_INIT, UNIX_CMD_TAKE_ARGS, unix_socket_mode_is_running, UnixManagerThreadSpawn(), and unlikely.
Referenced by RunModeUnixSocketRegister().
void UnixSocketPcapFile (TmEcode tm)
Definition at line 412 of file runmode-unix-socket.c.
References TM_ECODE_DONE, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by ReceivePcapFileLoop(), and ReceivePcapFileThreadInit().