suricata: src/runmode-erf-dag.c File Reference
runmode-erf-dag.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-erf-dag.h"
#include "output.h"
#include "detect-engine.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-runmodes.h"
Functions
const char * RunModeErfDagGetDefaultMode (void)
void RunModeErfDagRegister (void)
int RunModeIdsErfDagSingle (void)
int RunModeIdsErfDagAutoFp (void)
int RunModeIdsErfDagWorkers (void)
Function Documentation
const char* RunModeErfDagGetDefaultMode (void)
Definition at line 45 of file runmode-erf-dag.c.
Referenced by RunModeDispatch().
void RunModeErfDagRegister (void)
Definition at line 50 of file runmode-erf-dag.c.
References RUNMODE_DAG, RunModeIdsErfDagAutoFp(), RunModeIdsErfDagSingle(), RunModeIdsErfDagWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsErfDagAutoFp (void)
Definition at line 100 of file runmode-erf-dag.c.
References RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeErfDagRegister().
int RunModeIdsErfDagSingle (void)
Definition at line 74 of file runmode-erf-dag.c.
References RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeErfDagRegister().
int RunModeIdsErfDagWorkers (void)
Definition at line 126 of file runmode-erf-dag.c.
References RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeErfDagRegister().