suricata: src/runmode-napatech.c File Reference
runmode-napatech.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "output.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-runmodes.h"
#include "util-device.h"
#include "runmode-napatech.h"
#include "source-napatech.h"
Macros
#define NT_RUNMODE_AUTOFP 1
#define NT_RUNMODE_WORKERS 2
Functions
const char * RunModeNapatechGetDefaultMode (void)
void RunModeNapatechRegister (void)
int NapatechRegisterDeviceStreams ()
void * NapatechConfigParser (const char *device)
int NapatechGetThreadsCount (void *conf __attribute__((unused)))
int RunModeNapatechAutoFp (void)
int RunModeNapatechWorkers (void)
Detailed Description
Author
nPulse Technologies, LLC.
Matt Keeler mk@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file runmode-napatech.c.
Macro Definition Documentation
#define NT_RUNMODE_AUTOFP 1
Definition at line 42 of file runmode-napatech.c.
Referenced by RunModeNapatechAutoFp().
#define NT_RUNMODE_WORKERS 2
Definition at line 43 of file runmode-napatech.c.
Referenced by RunModeNapatechWorkers().
Function Documentation
void* NapatechConfigParser (const char * device)
Definition at line 152 of file runmode-napatech.c.
References ConfGetInt(), NapatechStreamDevConf::hba, SC_ERR_NAPATECH_PARSE_CONFIG, SCLogError, SCMalloc, NapatechStreamDevConf::stream_id, and unlikely.
int NapatechGetThreadsCount (void *conf __attribute__(unused))
Definition at line 176 of file runmode-napatech.c.
int NapatechRegisterDeviceStreams ()
Definition at line 73 of file runmode-napatech.c.
References ConfGetBool(), ConfGetNode(), LiveRegisterDevice(), next, SC_ERR_NAPATECH_STREAMS_REGISTER_FAILED, SC_ERR_RUNMODE, SCLogError, SCLogInfo, TAILQ_FOREACH, and ConfNode_::val.
int RunModeNapatechAutoFp (void)
Definition at line 225 of file runmode-napatech.c.
References NT_RUNMODE_AUTOFP.
Referenced by RunModeNapatechRegister().
const char* RunModeNapatechGetDefaultMode (void)
Definition at line 50 of file runmode-napatech.c.
Referenced by RunModeDispatch().
void RunModeNapatechRegister (void)
Definition at line 55 of file runmode-napatech.c.
References RUNMODE_NAPATECH, RunModeNapatechAutoFp(), RunModeNapatechWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeNapatechWorkers (void)
Definition at line 230 of file runmode-napatech.c.
References NT_RUNMODE_WORKERS.
Referenced by RunModeNapatechRegister().