suricata: src/runmode-pcap.c File Reference
runmode-pcap.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-pcap.h"
#include "log-httplog.h"
#include "output.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-device.h"
#include "util-runmodes.h"
#include "util-atomic.h"
#include "util-misc.h"
Functions
const char * RunModeIdsGetDefaultMode (void)
int RunModeIdsPcapWorkers (void)
Workers version of the PCAP LIVE processing.
void RunModeIdsPcapRegister (void)
void PcapDerefConfig (void *conf)
void * ParsePcapConfig (const char *iface)
int PcapConfigGeThreadsCount (void *conf)
int RunModeIdsPcapSingle (void)
Single thread version of the Pcap live processing.
int RunModeIdsPcapAutoFp (void)
RunModIdsPcapAutoFp set up the following thread packet handlers:
Function Documentation
void* ParsePcapConfig (const char * iface)
Definition at line 75 of file runmode-pcap.c.
References PcapIfaceConfig_::bpf_filter, PcapIfaceConfig_::buffer_size, PcapIfaceConfig_::checksum_mode, CHECKSUM_VALIDATION_AUTO, CHECKSUM_VALIDATION_DISABLE, CHECKSUM_VALIDATION_ENABLE, ConfGet(), ConfGetChildValueBoolWithDefault(), ConfGetChildValueIntWithDefault(), ConfGetChildValueWithDefault(), ConfGetInt(), ConfGetNode(), ConfNodeLookupKeyValue(), PcapIfaceConfig_::DerefFunc, PcapIfaceConfig_::iface, LIBPCAP_PROMISC, ParseSizeStringU64(), PcapDerefConfig(), PcapIfaceConfig_::promisc, SC_ATOMIC_ADD, SC_ATOMIC_INIT, SC_ERR_INVALID_ARGUMENT, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, PcapIfaceConfig_::snaplen, strlcpy(), PcapIfaceConfig_::threads, and unlikely.
Referenced by RunModeIdsPcapAutoFp(), RunModeIdsPcapSingle(), and RunModeIdsPcapWorkers().
int PcapConfigGeThreadsCount (void * conf)
Definition at line 221 of file runmode-pcap.c.
References PcapIfaceConfig_::threads.
Referenced by RunModeIdsPcapAutoFp(), RunModeIdsPcapSingle(), and RunModeIdsPcapWorkers().
void PcapDerefConfig (void * conf)
Definition at line 65 of file runmode-pcap.c.
References SC_ATOMIC_SUB, and SCFree.
Referenced by ParsePcapConfig().
const char* RunModeIdsGetDefaultMode (void)
Definition at line 37 of file runmode-pcap.c.
Referenced by RunModeDispatch().
int RunModeIdsPcapAutoFp (void)
RunModIdsPcapAutoFp set up the following thread packet handlers:
   - Receive thread (from pcap device)
   - Decode thread
   - Stream thread
   - Detect: If we have only 1 cpu, it will setup one Detect thread
             If we have more than one, it will setup num_cpus - 1
             starting from the second cpu available.
   - Outputs thread
   By default the threads will use the first cpu available
   except the Detection threads if we have more than one cpu.
Return values
0 If all goes well. (If any problem is detected the engine will exit()).
Definition at line 272 of file runmode-pcap.c.
References ConfGet(), ParsePcapConfig(), PcapConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsPcapRegister().
void RunModeIdsPcapRegister (void)
Definition at line 44 of file runmode-pcap.c.
References RUNMODE_PCAP_DEV, RunModeIdsPcapAutoFp(), RunModeIdsPcapSingle(), RunModeIdsPcapWorkers(), and RunModeRegisterNewRunMode().
Referenced by RunModeRegisterRunModes().
int RunModeIdsPcapSingle (void)
Single thread version of the Pcap live processing.
Definition at line 230 of file runmode-pcap.c.
References ConfGet(), ParsePcapConfig(), PcapConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsPcapRegister().
int RunModeIdsPcapWorkers (void)
Workers version of the PCAP LIVE processing.
Start N threads with each thread doing all the work.
Definition at line 304 of file runmode-pcap.c.
References ConfGet(), ParsePcapConfig(), PcapConfigGeThreadsCount(), RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_RUNMODE, SCEnter, SCLogError, SCLogInfo, SCReturnInt, and TimeModeSetLive().
Referenced by RunModeIdsPcapRegister().