suricata: src/source-erf-file.c File Reference
source-erf-file.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "tm-threads.h"
Data Structures
struct DagFlags_
struct DagRecord_
Macros
#define DAG_TYPE_ETH 2
Typedefs
typedef struct DagFlags_ DagFlags
Functions
struct DagRecord_ __attribute__ ((packed))
TmEcode ReceiveErfFileLoop (ThreadVars *tv, void *data, void *slot)
ERF file reading loop.
TmEcode ReceiveErfFileThreadInit (ThreadVars *tv, void *initdata, void **data)
Initialize the ERF receiver thread.
void ReceiveErfFileThreadExitStats (ThreadVars *tv, void *data)
Print some stats to the log at program exit.
TmEcode ReceiveErfFileThreadDeinit (ThreadVars *, void *)
TmEcode DecodeErfFileThreadInit (ThreadVars *tv, void *initdata, void **data)
Initialize the ERF decoder thread.
TmEcode DecodeErfFileThreadDeinit (ThreadVars *tv, void *data)
TmEcode DecodeErfFile (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
Decode the ERF file.
void TmModuleReceiveErfFileRegister (void)
Register the ERF file receiver (reader) module.
void TmModuleDecodeErfFileRegister (void)
Register the ERF file decoder module.
Variables
uint64_t ts
uint8_t type
DagFlags flags
uint16_t rlen
uint16_t lctr
uint16_t wlen
uint16_t pad
ErfFileThreadVars
Detailed Description
Author
Endace Technology Limited.
Support for reading ERF files.
Only ethernet supported at this time.
Definition in file source-erf-file.c.
Macro Definition Documentation
#define DAG_TYPE_ETH 2
Definition at line 32 of file source-erf-file.c.
Typedef Documentation
typedef struct DagFlags_ DagFlags
Function Documentation
struct DagRecord_ __attribute__ ((packed))
Definition at line 52 of file source-erf-file.c.
TmEcode DecodeErfFile (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
Decode the ERF file.
This function ups the decoder counters and then passes the packet off to the ethernet decoder.
Definition at line 276 of file source-erf-file.c.
References DecodeEthernet(), DecodeUpdatePacketCounters(), Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, PacketDecodeFinalize(), PKT_PSEUDO_STREAM_END, SCEnter, SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodeErfFileRegister().
TmEcode DecodeErfFileThreadDeinit (ThreadVars * tv, void * data)
Definition at line 262 of file source-erf-file.c.
References DecodeThreadVarsFree(), SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodeErfFileRegister().
TmEcode DecodeErfFileThreadInit (ThreadVars * tv, void * initdata, void ** data)
Initialize the ERF decoder thread.
Definition at line 246 of file source-erf-file.c.
References DecodeRegisterPerfCounters(), DecodeThreadVarsAlloc(), SCEnter, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleDecodeErfFileRegister().
TmEcode ReceiveErfFileLoop (ThreadVars * tv, void * data, void * slot)
ERF file reading loop.
Definition at line 111 of file source-erf-file.c.
References EngineStop(), ErfFileThreadVars, PacketGetFromQueueOrAlloc(), PacketPoolWait(), PKT_SET_SRC, PKT_SRC_WIRE, SC_ERR_MEM_ALLOC, SCLogError, SCReturnInt, suricata_ctl_flags, SURICATA_KILL, SURICATA_STOP, TM_ECODE_FAILED, TM_ECODE_OK, TmqhOutputPacketpool(), and unlikely.
Referenced by TmModuleReceiveErfFileRegister().
TmEcode ReceiveErfFileThreadDeinit (ThreadVars * , void *)
void ReceiveErfFileThreadExitStats (ThreadVars * tv, void * data)
Print some stats to the log at program exit.
Parameters
tv Pointer to ThreadVars.
data Pointer to data, ErfFileThreadVars.
Definition at line 303 of file source-erf-file.c.
References ErfFileThreadVars, and SCLogInfo.
Referenced by TmModuleReceiveErfFileRegister().
TmEcode ReceiveErfFileThreadInit (ThreadVars * tv, void * initdata, void ** data)
Initialize the ERF receiver thread.
Definition at line 210 of file source-erf-file.c.
References ErfFileThreadVars, SC_ERR_FOPEN, SC_ERR_INVALID_ARGUMENT, SC_ERR_MEM_ALLOC, SCEnter, SCLogError, SCLogInfo, SCMalloc, SCReturnInt, TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by TmModuleReceiveErfFileRegister().
void TmModuleDecodeErfFileRegister (void)
Register the ERF file decoder module.
Definition at line 96 of file source-erf-file.c.
References TmModule_::cap_flags, DecodeErfFile(), DecodeErfFileThreadDeinit(), DecodeErfFileThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEERFFILE, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceiveErfFileRegister (void)
Register the ERF file receiver (reader) module.
Definition at line 78 of file source-erf-file.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceiveErfFileLoop(), ReceiveErfFileThreadExitStats(), ReceiveErfFileThreadInit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEERFFILE.
Referenced by RegisterAllModules().
Variable Documentation
ErfFileThreadVars
Definition at line 62 of file source-erf-file.c.
Referenced by ReceiveErfFileLoop(), ReceiveErfFileThreadExitStats(), and ReceiveErfFileThreadInit().
DagFlags flags
Definition at line 32 of file source-erf-file.c.
uint16_t lctr
Definition at line 34 of file source-erf-file.c.
uint16_t pad
Definition at line 36 of file source-erf-file.c.
uint16_t rlen
Definition at line 33 of file source-erf-file.c.
uint64_t ts
Definition at line 30 of file source-erf-file.c.
Referenced by OutputFlowLogThreadInit().
uint8_t type
Definition at line 31 of file source-erf-file.c.
uint16_t wlen
Definition at line 35 of file source-erf-file.c.