suricata: src/source-pcap-file.c File Reference
source-pcap-file.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "packet-queue.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
#include "source-pcap-file.h"
#include "util-time.h"
#include "util-debug.h"
#include "conf.h"
#include "util-error.h"
#include "util-privs.h"
#include "tmqh-packetpool.h"
#include "tm-threads.h"
#include "util-optimize.h"
#include "flow-manager.h"
#include "util-profiling.h"
#include "runmode-unix-socket.h"
#include "util-checksum.h"
#include "util-atomic.h"
Data Structures
struct PcapFileGlobalVars_
struct PcapFileThreadVars_
Typedefs
typedef struct PcapFileGlobalVars_ PcapFileGlobalVars
typedef struct PcapFileThreadVars_ PcapFileThreadVars
Functions
TmEcode ReceivePcapFileLoop (ThreadVars *tv, void *data, void *slot)
Main PCAP file reading Loop function.
TmEcode ReceivePcapFileThreadInit (ThreadVars *, void *, void **)
void ReceivePcapFileThreadExitStats (ThreadVars *, void *)
TmEcode ReceivePcapFileThreadDeinit (ThreadVars *, void *)
TmEcode DecodePcapFile (ThreadVars *, Packet *, void *, PacketQueue *, PacketQueue *)
TmEcode DecodePcapFileThreadInit (ThreadVars *, void *, void **)
TmEcode DecodePcapFileThreadDeinit (ThreadVars *tv, void *data)
void TmModuleReceivePcapFileRegister (void)
void TmModuleDecodePcapFileRegister (void)
void PcapFileGlobalInit ()
void PcapFileCallbackLoop (char *user, struct pcap_pkthdr *h, u_char *pkt)
void PcapIncreaseInvalidChecksum ()
Variables
int max_pending_packets
double prev_signaled_ts = 0
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
File based pcap packet acquisition support
Definition in file source-pcap-file.c.
Typedef Documentation
typedef struct PcapFileGlobalVars_ PcapFileGlobalVars
typedef struct PcapFileThreadVars_ PcapFileThreadVars
max packets < 65536
Function Documentation
TmEcode DecodePcapFile (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
Definition at line 406 of file source-pcap-file.c.
References BUG_ON, PcapFileGlobalVars_::Decoder, DecodeUpdatePacketCounters(), Packet_::flags, FlowWakeupFlowManagerThread, GET_PKT_DATA, GET_PKT_LEN, PacketDecodeFinalize(), PKT_PSEUDO_STREAM_END, Packet_::pkt_src, PKT_SRC_FFR, PKT_SRC_WIRE, prev_signaled_ts, SCEnter, SCReturnInt, TimeSet(), TM_ECODE_OK, and Packet_::ts.
Referenced by TmModuleDecodePcapFileRegister().
TmEcode DecodePcapFileThreadDeinit (ThreadVars * tv, void * data)
Definition at line 462 of file source-pcap-file.c.
References DecodeThreadVarsFree(), SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodePcapFileRegister().
TmEcode DecodePcapFileThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 441 of file source-pcap-file.c.
References DecodeRegisterPerfCounters(), DecodeThreadVarsAlloc(), SCEnter, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleDecodePcapFileRegister().
void PcapFileCallbackLoop (char * user, struct pcap_pkthdr * h, u_char * pkt)
Definition at line 141 of file source-pcap-file.c.
References PcapFileThreadVars_::bytes, PcapFileThreadVars_::cb_result, PcapFileGlobalVars_::checksum_mode, CHECKSUM_VALIDATION_AUTO, CHECKSUM_VALIDATION_DISABLE, ChecksumAutoModeCheck(), PcapFileGlobalVars_::cnt, PcapFileGlobalVars_::datalink, Packet_::datalink, Packet_::flags, PACKET_PROFILING_TMM_END, PACKET_PROFILING_TMM_START, PacketCopyData(), PacketGetFromQueueOrAlloc(), Packet_::pcap_cnt, PcapFileGlobalVars_::pcap_handle, Packet_::pcap_v, PKT_IGNORE_CHECKSUM, PKT_SET_SRC, PKT_SRC_WIRE, PcapFileThreadVars_::pkts, SC_ATOMIC_GET, SCEnter, SCLogDebug, SCReturn, PcapFileThreadVars_::slot, PcapPacketVars_::tenant_id, PcapFileThreadVars_::tenant_id, TM_ECODE_FAILED, TM_ECODE_OK, TMM_RECEIVEPCAPFILE, TmqhOutputPacketpool(), Packet_::ts, PcapFileThreadVars_::tv, and unlikely.
Referenced by ReceivePcapFileLoop().
void PcapFileGlobalInit ()
Definition at line 136 of file source-pcap-file.c.
References SC_ATOMIC_INIT.
Referenced by RunModeFilePcapAutoFp(), and RunModeFilePcapSingle().
void PcapIncreaseInvalidChecksum ()
Definition at line 469 of file source-pcap-file.c.
References SC_ATOMIC_ADD.
TmEcode ReceivePcapFileLoop (ThreadVars * tv, void * data, void * slot)
Main PCAP file reading Loop function.
Definition at line 194 of file source-pcap-file.c.
References PcapFileThreadVars_::cb_result, EngineKill(), EngineStop(), PacketPoolWait(), PcapFileGlobalVars_::pcap_handle, PcapFileCallbackLoop(), RunModeUnixSocketIsActive(), SC_ERR_PCAP_DISPATCH, SCEnter, SCLogError, SCLogInfo, SCReturnInt, PcapFileThreadVars_::slot, TmSlot_::slot_next, StatsSyncCountersIfSignalled, suricata_ctl_flags, SURICATA_KILL, SURICATA_STOP, TM_ECODE_DONE, TM_ECODE_FAILED, TM_ECODE_OK, UnixSocketPcapFile(), and unlikely.
Referenced by TmModuleReceivePcapFileRegister().
TmEcode ReceivePcapFileThreadDeinit (ThreadVars * tv, void * data)
Definition at line 394 of file source-pcap-file.c.
References SCEnter, SCFree, SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleReceivePcapFileRegister().
void ReceivePcapFileThreadExitStats (ThreadVars * tv, void * data)
Definition at line 371 of file source-pcap-file.c.
References PcapFileThreadVars_::bytes, CHECKSUM_INVALID_RATIO, CHECKSUM_SAMPLE_COUNT, CHECKSUM_VALIDATION_AUTO, PcapFileGlobalVars_::cnt, PcapFileGlobalVars_::conf_checksum_mode, PcapFileThreadVars_::pkts, SC_ATOMIC_GET, SC_ERR_INVALID_CHECKSUM, SCEnter, SCLogInfo, SCLogNotice, and SCLogWarning.
Referenced by TmModuleReceivePcapFileRegister().
TmEcode ReceivePcapFileThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 260 of file source-pcap-file.c.
References PcapFileGlobalVars_::checksum_mode, CHECKSUM_VALIDATION_AUTO, CHECKSUM_VALIDATION_DISABLE, CHECKSUM_VALIDATION_ENABLE, PcapFileGlobalVars_::conf_checksum_mode, ConfGet(), ConfGetInt(), PcapFileGlobalVars_::datalink, DecodeEthernet(), DecodeNull(), DecodePPP(), PcapFileGlobalVars_::Decoder, DecodeRaw(), DecodeSll(), PcapFileGlobalVars_::filter, LINKTYPE_ETHERNET, LINKTYPE_LINUX_SLL, LINKTYPE_NULL, LINKTYPE_PPP, LINKTYPE_RAW, PcapFileGlobalVars_::pcap_handle, RunModeUnixSocketIsActive(), SC_ERR_BPF, SC_ERR_FOPEN, SC_ERR_INVALID_ARGUMENT, SC_ERR_UNIMPLEMENTED, SCEnter, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, SCReturnInt, PcapFileThreadVars_::tenant_id, TM_ECODE_DONE, TM_ECODE_FAILED, TM_ECODE_OK, PcapFileThreadVars_::tv, UnixSocketPcapFile(), and unlikely.
Referenced by TmModuleReceivePcapFileRegister().
void TmModuleDecodePcapFileRegister (void)
Definition at line 124 of file source-pcap-file.c.
References TmModule_::cap_flags, DecodePcapFile(), DecodePcapFileThreadDeinit(), DecodePcapFileThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEPCAPFILE, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceivePcapFileRegister (void)
Definition at line 109 of file source-pcap-file.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceivePcapFileLoop(), ReceivePcapFileThreadDeinit(), ReceivePcapFileThreadExitStats(), ReceivePcapFileThreadInit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEPCAPFILE.
Referenced by RegisterAllModules().
Variable Documentation
double prev_signaled_ts = 0
Definition at line 404 of file source-pcap-file.c.
Referenced by DecodePcapFile().