suricata: src/source-nfq-prototypes.h File Reference
source-nfq-prototypes.h File Reference
Functions
void TmModuleReceiveNFQRegister (void)
void TmModuleVerdictNFQRegister (void)
void TmModuleDecodeNFQRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file source-nfq-prototypes.h.
Function Documentation
void TmModuleDecodeNFQRegister (void)
Definition at line 205 of file source-nfq.c.
References DecodeNFQ(), DecodeNFQThreadDeinit(), DecodeNFQThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODENFQ, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceiveNFQRegister (void)
Definition at line 179 of file source-nfq.c.
References TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceiveNFQLoop(), ReceiveNFQThreadDeinit(), ReceiveNFQThreadExitStats(), ReceiveNFQThreadInit(), TmModule_::RegisterTests, SCMutexInit, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVENFQ.
Referenced by RegisterAllModules().
void TmModuleVerdictNFQRegister (void)
Definition at line 195 of file source-nfq.c.
References TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, tmm_modules, TMM_VERDICTNFQ, VerdictNFQ(), VerdictNFQThreadDeinit(), and VerdictNFQThreadInit().
Referenced by RegisterAllModules().