suricata: src/source-erf-file.h File Reference
source-erf-file.h File Reference
Functions
void TmModuleReceiveErfFileRegister (void)
Register the ERF file receiver (reader) module.
void TmModuleDecodeErfFileRegister (void)
Register the ERF file decoder module.
Detailed Description
Author
Endace Technology Limited
Definition in file source-erf-file.h.
Function Documentation
void TmModuleDecodeErfFileRegister (void)
Register the ERF file decoder module.
Definition at line 96 of file source-erf-file.c.
References TmModule_::cap_flags, DecodeErfFile(), DecodeErfFileThreadDeinit(), DecodeErfFileThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEERFFILE, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceiveErfFileRegister (void)
Register the ERF file receiver (reader) module.
Definition at line 78 of file source-erf-file.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceiveErfFileLoop(), ReceiveErfFileThreadExitStats(), ReceiveErfFileThreadInit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEERFFILE.
Referenced by RegisterAllModules().