suricata: src/source-napatech.c File Reference
source-napatech.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "threadvars.h"
#include "util-optimize.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "tm-modules.h"
#include "util-privs.h"
#include "tmqh-packetpool.h"
#include "source-napatech.h"
#include <nt.h>
Data Structures
struct NapatechThreadVars_
Typedefs
typedef struct NapatechThreadVars_ NapatechThreadVars
Functions
TmEcode NapatechStreamThreadInit (ThreadVars *tv, void *initdata, void **data)
Initialize the Napatech receiver thread, generate a single NapatechThreadVar structure for each thread, this will contain a NtNetStreamRx_t stream handle which is used when the thread executes to acquire the packets.
void NapatechStreamThreadExitStats (ThreadVars *tv, void *data)
Print some stats to the log at program exit.
TmEcode NapatechStreamLoop (ThreadVars *tv, void *data, void *slot)
Main Napatech reading Loop function.
TmEcode NapatechDecodeThreadInit (ThreadVars *, void *, void **)
TmEcode NapatechDecodeThreadDeinit (ThreadVars *tv, void *data)
TmEcode NapatechDecode (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
This function passes off to link type decoders.
void TmModuleNapatechStreamRegister (void)
Register the Napatech receiver (reader) module.
void TmModuleNapatechDecodeRegister (void)
Register the Napatech decoder module.
TmEcode NapatechStreamThreadDeinit (ThreadVars *tv, void *data)
Deinitializes the NAPATECH card.
Variables
int max_pending_packets
Detailed Description
Author
nPulse Technologies, LLC.
Matt Keeler mk@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Support for NAPATECH adapter with the 3GD Driver/API. Requires libntapi from Napatech A/S.
Definition in file source-napatech.c.
Typedef Documentation
typedef struct NapatechThreadVars_ NapatechThreadVars
Function Documentation
TmEcode NapatechDecode (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
This function passes off to link type decoders.
Decode Napatech NapatechDecode reads packets from the PacketQueue and passes them off to the proper link type decoder.
Parameters
t pointer to ThreadVars
p pointer to the current packet
data pointer that gets cast into PcapThreadVars for ptv
pq pointer to the current PacketQueue
Definition at line 347 of file source-napatech.c.
References Packet_::datalink, DecodeEthernet(), DecodeUpdatePacketCounters(), Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, LINKTYPE_ETHERNET, PacketDecodeFinalize(), PKT_PSEUDO_STREAM_END, SC_ERR_DATALINK_UNIMPLEMENTED, SCEnter, SCLogError, SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleNapatechDecodeRegister().
TmEcode NapatechDecodeThreadDeinit (ThreadVars * tv, void * data)
Definition at line 395 of file source-napatech.c.
References DecodeThreadVarsFree(), SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleNapatechDecodeRegister().
TmEcode NapatechDecodeThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 378 of file source-napatech.c.
References DecodeRegisterPerfCounters(), DecodeThreadVarsAlloc(), SCEnter, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleNapatechDecodeRegister().
TmEcode NapatechStreamLoop (ThreadVars * tv, void * data, void * slot)
Main Napatech reading Loop function.
Definition at line 181 of file source-napatech.c.
References NapatechThreadVars_::bytes, Packet_::datalink, NapatechThreadVars_::drops, NapatechThreadVars_::hba, LINKTYPE_ETHERNET, PacketCopyData(), PacketGetFromQueueOrAlloc(), PacketPoolWait(), NapatechThreadVars_::pkts, NapatechThreadVars_::rx_stream, SC_ERR_NAPATECH_OPEN_FAILED, SC_ERR_NAPATECH_STAT_DROPS_FAILED, SC_ERR_NAPATECH_STREAM_NEXT_FAILED, SC_ERR_NAPATECH_TIMESTAMP_TYPE_NOT_SUPPORTED, SCEnter, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCLogWarning, SCReturnInt, NapatechThreadVars_::slot, TmSlot_::slot_next, StatsSyncCountersIfSignalled, NapatechThreadVars_::stream_id, suricata_ctl_flags, SURICATA_KILL, SURICATA_STOP, TM_ECODE_FAILED, TM_ECODE_OK, TmqhOutputPacketpool(), Packet_::ts, NapatechThreadVars_::tv, and unlikely.
Referenced by TmModuleNapatechStreamRegister().
TmEcode NapatechStreamThreadDeinit (ThreadVars * tv, void * data)
Deinitializes the NAPATECH card.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into PcapThreadVars for ptv
Definition at line 324 of file source-napatech.c.
References NapatechThreadVars_::rx_stream, SCEnter, SCLogDebug, SCReturnInt, NapatechThreadVars_::stream_id, and TM_ECODE_OK.
Referenced by TmModuleNapatechStreamRegister().
void NapatechStreamThreadExitStats (ThreadVars * tv, void * data)
Print some stats to the log at program exit.
Parameters
tv Pointer to ThreadVars.
data Pointer to data, ErfFileThreadVars.
Definition at line 309 of file source-napatech.c.
References NapatechThreadVars_::bytes, NapatechThreadVars_::drops, NapatechThreadVars_::pkts, SCLogNotice, and NapatechThreadVars_::stream_id.
Referenced by TmModuleNapatechStreamRegister().
TmEcode NapatechStreamThreadInit (ThreadVars * tv, void * initdata, void ** data)
Initialize the Napatech receiver thread, generate a single NapatechThreadVar structure for each thread, this will contain a NtNetStreamRx_t stream handle which is used when the thread executes to acquire the packets.
Parameters
tv Thread variable to ThreadVars
initdata Initial data to the adapter passed from the user, this is processed by the user.
For now, we assume that we have only a single name for the NAPATECH adapter.
Parameters
data data pointer gets populated with
Definition at line 151 of file source-napatech.c.
References NapatechStreamDevConf::hba, NapatechThreadVars_::hba, SC_ERR_MEM_ALLOC, SCEnter, SCLogError, SCLogInfo, SCMalloc, SCReturnInt, NapatechStreamDevConf::stream_id, NapatechThreadVars_::stream_id, TM_ECODE_OK, NapatechThreadVars_::tv, and unlikely.
Referenced by TmModuleNapatechStreamRegister().
void TmModuleNapatechDecodeRegister (void)
Register the Napatech decoder module.
Definition at line 123 of file source-napatech.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, NapatechDecode(), NapatechDecodeThreadDeinit(), NapatechDecodeThreadInit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODENAPATECH, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleNapatechStreamRegister (void)
Register the Napatech receiver (reader) module.
Definition at line 107 of file source-napatech.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, NapatechStreamLoop(), NapatechStreamThreadDeinit(), NapatechStreamThreadExitStats(), NapatechStreamThreadInit(), TmModule_::PktAcqLoop, TmModule_::RegisterTests, SC_CAP_NET_RAW, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVENAPATECH.
Referenced by RegisterAllModules().