suricata: src/source-ipfw.c File Reference
source-ipfw.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "packet-queue.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "source-ipfw.h"
#include "util-debug.h"
#include "conf.h"
#include "util-byte.h"
#include "util-privs.h"
#include "util-device.h"
#include "runmodes.h"
Data Structures
struct IPFWThreadVars_
Structure to hold thread specific variables.
Macros
#define IPFW_ACCEPT 0
#define IPFW_DROP 1
#define IPFW_SOCKET_POLL_MSEC 300
#define IP_MAXPACKET 65535
Typedefs
typedef struct IPFWThreadVars_ IPFWThreadVars
Structure to hold thread specific variables.
Functions
void * IPFWGetQueue (int number)
Get a pointer to the IPFW queue at index.
TmEcode ReceiveIPFWThreadInit (ThreadVars *tv, void *initdata, void **data)
Init function for RecieveIPFW.
TmEcode ReceiveIPFW (ThreadVars *, Packet *, void *, PacketQueue *, PacketQueue *)
TmEcode ReceiveIPFWLoop (ThreadVars *tv, void *data, void *slot)
void ReceiveIPFWThreadExitStats (ThreadVars *tv, void *data)
This function prints stats to the screen at exit.
TmEcode ReceiveIPFWThreadDeinit (ThreadVars *tv, void *data)
DeInit function closes divert socket at exit.
TmEcode IPFWSetVerdict (ThreadVars *tv, IPFWThreadVars *ptv, Packet *p)
This function sets the Verdict and processes the packet.
TmEcode VerdictIPFW (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
This function handles the Verdict processing.
TmEcode VerdictIPFWThreadInit (ThreadVars *tv, void *initdata, void **data)
This function initializes the VerdictThread.
void VerdictIPFWThreadExitStats (ThreadVars *tv, void *data)
This function prints stats for the VerdictThread.
TmEcode VerdictIPFWThreadDeinit (ThreadVars *tv, void *data)
This function deinitializes the VerdictThread.
TmEcode DecodeIPFWThreadInit (ThreadVars *tv, void *initdata, void **data)
This function initializes the DecodeThreadVariables.
TmEcode DecodeIPFWThreadDeinit (ThreadVars *tv, void *data)
TmEcode DecodeIPFW (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
This function passes off to link type decoders.
void TmModuleReceiveIPFWRegister (void)
Registration Function for RecieveIPFW.
void TmModuleVerdictIPFWRegister (void)
Registration Function for VerdictIPFW.
void TmModuleDecodeIPFWRegister (void)
Registration Function for DecodeIPFW.
int IPFWRegisterQueue (char *queue)
Add an IPFW divert.
void * IPFWGetThread (int number)
Get a pointer to the IPFW thread at index.
Variables
int max_pending_packets
Detailed Description
Author
Nick Rogness nick@.nosp@m.rogn.nosp@m.ess.n.nosp@m.et
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
IPFW packet acquisition support
Definition in file source-ipfw.c.
Macro Definition Documentation
#define IP_MAXPACKET 65535
Definition at line 49 of file source-ipfw.c.
Referenced by ReceiveIPFWLoop().
#define IPFW_ACCEPT 0
Definition at line 43 of file source-ipfw.c.
Referenced by IPFWSetVerdict().
#define IPFW_DROP 1
Definition at line 44 of file source-ipfw.c.
Referenced by IPFWSetVerdict().
#define IPFW_SOCKET_POLL_MSEC 300
Definition at line 46 of file source-ipfw.c.
Referenced by IPFWSetVerdict(), and ReceiveIPFWLoop().
Typedef Documentation
typedef struct IPFWThreadVars_ IPFWThreadVars
Structure to hold thread specific variables.
Function Documentation
TmEcode DecodeIPFW (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
This function passes off to link type decoders.
Todo:
Unit tests are needed for this module.
DecodeIPFW reads packets from the PacketQueue and passes them off to the proper link type decoder.
Parameters
tv pointer to ThreadVars
p pointer to the current packet
data pointer that gets cast into IPFWThreadVars for ptv
pq pointer to the PacketQueue
Definition at line 441 of file source-ipfw.c.
References DecodeIPV4(), DecodeIPV6(), DecodeUpdatePacketCounters(), Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, ip4h, ip6h, IPV4_GET_RAW_VER, IPV6_GET_RAW_VER, PacketDecodeFinalize(), PKT_PSEUDO_STREAM_END, SCEnter, SCLogDebug, SCLogInfo, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleDecodeIPFWRegister().
TmEcode DecodeIPFWThreadDeinit (ThreadVars * tv, void * data)
Definition at line 500 of file source-ipfw.c.
References DecodeThreadVarsFree(), SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodeIPFWRegister().
TmEcode DecodeIPFWThreadInit (ThreadVars * tv, void * initdata, void ** data)
This function initializes the DecodeThreadVariables.
Parameters
tv pointer to ThreadVars
initdata pointer for passing in args
data pointer that gets cast into IPFWThreadVars for ptv
Definition at line 485 of file source-ipfw.c.
References DecodeRegisterPerfCounters(), DecodeThreadVarsAlloc(), SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleDecodeIPFWRegister().
void * IPFWGetQueue (int number)
Get a pointer to the IPFW queue at index.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the IPFWThreadVars at index
NULL on error
Definition at line 767 of file source-ipfw.c.
Referenced by IPFWSetVerdict(), ReceiveIPFWLoop(), ReceiveIPFWThreadDeinit(), and ReceiveIPFWThreadInit().
void* IPFWGetThread (int number)
Get a pointer to the IPFW thread at index.
This function is temporary used as configuration parser.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the IPFWThreadVars at index
NULL on error
Definition at line 785 of file source-ipfw.c.
Referenced by RunModeIpsIPFWAutoFp(), and RunModeIpsIPFWWorker().
int IPFWRegisterQueue (char * queue)
Add an IPFW divert.
Parameters
string with the queue name
Return values
0 on success.
-1 on failure.
Definition at line 720 of file source-ipfw.c.
References ByteExtractStringUint16(), IPFWThreadVars_::ipfw_index, IPFW_MAX_QUEUE, LiveRegisterDevice(), IPFWQueueVars_::port_num, SC_ERR_INVALID_ARGUMENT, SCLogDebug, SCLogError, SCMutexLock, and SCMutexUnlock.
TmEcode IPFWSetVerdict (ThreadVars * tv, IPFWThreadVars * ptv, Packet * p)
This function sets the Verdict and processes the packet.
Parameters
tv pointer to ThreadVars
p pointer to the Packet
Todo:
For divert sockets, dropping means not writing the packet back to the socket. Need to see if there is some better way to free the packet from the queue
Definition at line 514 of file source-ipfw.c.
References IPFWThreadVars_::accepted, ACTION_DROP, IPFWThreadVars_::dropped, GET_PKT_DATA, GET_PKT_LEN, IPFW_ACCEPT, IPFW_DROP, IPFWPacketVars_::ipfw_index, IPFW_SOCKET_POLL_MSEC, Packet_::ipfw_v, IPFWGetQueue(), PACKET_TEST_ACTION, SC_ERR_INVALID_ARGUMENT, SC_WARN_IPFW_XMIT, SCEnter, SCLogDebug, SCLogInfo, SCLogWarning, SCReturnInt, THV_KILL, THV_PAUSE, TM_ECODE_FAILED, TM_ECODE_OK, and TmThreadsCheckFlag().
Referenced by VerdictIPFW().
TmEcode ReceiveIPFW (ThreadVars * , Packet * , void * , PacketQueue * , PacketQueue *)
TmEcode ReceiveIPFWLoop (ThreadVars * tv, void * data, void * slot)
Definition at line 227 of file source-ipfw.c.
References IPFWThreadVars_::bytes, IPFWThreadVars_::datalink, IPFWQueueVars_::fd, GET_PKT_DATA, GET_PKT_LEN, IP_MAXPACKET, IPFWThreadVars_::ipfw_index, IPFWQueueVars_::ipfw_sin, IPFWQueueVars_::ipfw_sinlen, IPFW_SOCKET_POLL_MSEC, IPFWGetQueue(), ThreadVars_::name, PacketCopyData(), PacketGetFromQueueOrAlloc(), PacketPoolWait(), PKT_SET_SRC, PKT_SRC_WIRE, IPFWThreadVars_::pkts, IPFWQueueVars_::port_num, SC_ERR_INVALID_ARGUMENT, SC_WARN_IPFW_RECV, SCEnter, SCLogDebug, SCLogInfo, SCLogWarning, SCReturnInt, StatsSyncCountersIfSignalled, suricata_ctl_flags, TM_ECODE_FAILED, TM_ECODE_OK, TmqhOutputPacketpool(), and unlikely.
Referenced by TmModuleReceiveIPFWRegister().
TmEcode ReceiveIPFWThreadDeinit (ThreadVars * tv, void * data)
DeInit function closes divert socket at exit.
Todo:
Unit tests are needed for this module.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into IPFWThreadVars for ptv
Definition at line 413 of file source-ipfw.c.
References IPFWQueueVars_::fd, IPFWThreadVars_::ipfw_index, IPFWGetQueue(), SC_WARN_IPFW_UNBIND, SCEnter, SCLogWarning, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleReceiveIPFWRegister().
void ReceiveIPFWThreadExitStats (ThreadVars * tv, void * data)
This function prints stats to the screen at exit.
Todo:
Unit tests are needed for this module.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into IPFWThreadVars for ptv
Definition at line 392 of file source-ipfw.c.
References IPFWThreadVars_::accepted, IPFWThreadVars_::bytes, IPFWThreadVars_::dropped, IPFWThreadVars_::errs, ThreadVars_::name, IPFWThreadVars_::pkts, SCEnter, SCLogNotice, and SCReturn.
Referenced by TmModuleReceiveIPFWRegister().
TmEcode ReceiveIPFWThreadInit (ThreadVars * tv, void * initdata, void ** data)
Init function for RecieveIPFW.
This is a setup function for recieving packets via ipfw divert, binds a socket, and prepares to to read from it.
Parameters
tv pointer to ThreadVars
initdata pointer to the divert port passed from the user
data pointer gets populated with IPFWThreadVars
Definition at line 328 of file source-ipfw.c.
References IPFWThreadVars_::datalink, IPFWQueueVars_::fd, IPFWThreadVars_::ipfw_index, IPFWQueueVars_::ipfw_sin, IPFWQueueVars_::ipfw_sinlen, IPFWGetQueue(), IPFWQueueVars_::port_num, SC_ERR_IPFW_BIND, SC_ERR_IPFW_SETSOCKOPT, SC_ERR_IPFW_SOCK, SCEnter, SCLogError, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleReceiveIPFWRegister().
void TmModuleDecodeIPFWRegister (void)
Registration Function for DecodeIPFW.
Todo:
Unit tests are needed for this module.
Definition at line 190 of file source-ipfw.c.
References DecodeIPFW(), DecodeIPFWThreadDeinit(), DecodeIPFWThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEIPFW, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceiveIPFWRegister (void)
Registration Function for RecieveIPFW.
Todo:
Unit tests are needed for this module.
Todo:
untested
Definition at line 153 of file source-ipfw.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceiveIPFWLoop(), ReceiveIPFWThreadDeinit(), ReceiveIPFWThreadExitStats(), ReceiveIPFWThreadInit(), TmModule_::RegisterTests, SC_CAP_NET_ADMIN, SC_CAP_NET_BIND_SERVICE, SC_CAP_NET_BROADCAST, SC_CAP_NET_RAW, SCMutexInit, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEIPFW.
Referenced by RegisterAllModules().
void TmModuleVerdictIPFWRegister (void)
Registration Function for VerdictIPFW.
Todo:
Unit tests are needed for this module.
Todo:
untested
Definition at line 174 of file source-ipfw.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, SC_CAP_NET_ADMIN, SC_CAP_NET_BIND_SERVICE, SC_CAP_NET_RAW, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, tmm_modules, TMM_VERDICTIPFW, VerdictIPFW(), VerdictIPFWThreadDeinit(), VerdictIPFWThreadExitStats(), and VerdictIPFWThreadInit().
Referenced by RegisterAllModules().
TmEcode VerdictIPFW (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
This function handles the Verdict processing.
Todo:
Unit tests are needed for this module.
Parameters
tv pointer to ThreadVars
p pointer to the Packet
data pointer that gets cast into IPFWThreadVars for ptv
pq pointer for the Packet Queue access (Not used)
Definition at line 605 of file source-ipfw.c.
References Packet_::flags, IPFWSetVerdict(), IS_TUNNEL_PKT, m, PKT_PSEUDO_STREAM_END, Packet_::root, SCEnter, SCLogDebug, SCMutex, SCMutexLock, SCMutexUnlock, SCReturnInt, TM_ECODE_OK, TUNNEL_INCR_PKT_RTV, Packet_::tunnel_mutex, TUNNEL_PKT_RTV, and TUNNEL_PKT_TPR.
Referenced by TmModuleVerdictIPFWRegister().
TmEcode VerdictIPFWThreadDeinit (ThreadVars * tv, void * data)
This function deinitializes the VerdictThread.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into IPFWThreadVars for ptv
Definition at line 688 of file source-ipfw.c.
References SCEnter, SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleVerdictIPFWRegister().
void VerdictIPFWThreadExitStats (ThreadVars * tv, void * data)
This function prints stats for the VerdictThread.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into IPFWThreadVars for ptv
Definition at line 706 of file source-ipfw.c.
References IPFWThreadVars_::accepted, IPFWThreadVars_::dropped, ThreadVars_::name, and SCLogInfo.
Referenced by TmModuleVerdictIPFWRegister().
TmEcode VerdictIPFWThreadInit (ThreadVars * tv, void * initdata, void ** data)
This function initializes the VerdictThread.
Parameters
t pointer to ThreadVars
initdata pointer for passing in args
data pointer that gets cast into IPFWThreadVars for ptv
Definition at line 663 of file source-ipfw.c.
References SCEnter, SCMalloc, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleVerdictIPFWRegister().