suricata: src/source-pfring.c File Reference
source-pfring.c File Reference
#include <pfring.h>
#include "suricata-common.h"
#include "suricata.h"
#include "conf.h"
#include "decode.h"
#include "packet-queue.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "source-pfring.h"
#include "util-debug.h"
#include "util-checksum.h"
#include "util-privs.h"
#include "util-device.h"
#include "util-host-info.h"
#include "runmodes.h"
Data Structures
struct PfringThreadVars_
Structure to hold thread specific variables.
Macros
#define LIBPFRING_PROMISC 1
#define LIBPFRING_REENTRANT 0
#define LIBPFRING_WAIT_FOR_INCOMING 1
Typedefs
typedef struct PfringThreadVars_ PfringThreadVars
Structure to hold thread specific variables.
Enumerations
enum PfringThreadVarsFlags { PFRING_FLAGS_ZERO_COPY = 0x1 }
Functions
TmEcode ReceivePfringLoop (ThreadVars *tv, void *data, void *slot)
Recieves packets from an interface via libpfring.
TmEcode ReceivePfringThreadInit (ThreadVars *tv, void *initdata, void **data)
Init function for RecievePfring.
void ReceivePfringThreadExitStats (ThreadVars *tv, void *data)
This function prints stats to the screen at exit.
TmEcode ReceivePfringThreadDeinit (ThreadVars *tv, void *data)
DeInit function closes pd at exit.
TmEcode DecodePfringThreadInit (ThreadVars *tv, void *initdata, void **data)
This an Init function for DecodePfring.
TmEcode DecodePfring (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
This function passes off to link type decoders.
TmEcode DecodePfringThreadDeinit (ThreadVars *tv, void *data)
void TmModuleReceivePfringRegister (void)
Registration Function for RecievePfring.
void TmModuleDecodePfringRegister (void)
Registration Function for DecodePfring.
Variables
int max_pending_packets
Detailed Description
Author
William Metcalf willi.nosp@m.am.m.nosp@m.etcal.nosp@m.f@gm.nosp@m.ail.c.nosp@m.om
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
PF_RING packet acquisition support
Todo:
remove requirement for setting cluster so old 3.x versions are supported
implement DNA support
Allow ring options such as snaplen etc, to be user configurable.
Definition in file source-pfring.c.
Macro Definition Documentation
#define LIBPFRING_PROMISC 1
Definition at line 124 of file source-pfring.c.
#define LIBPFRING_REENTRANT 0
Definition at line 125 of file source-pfring.c.
#define LIBPFRING_WAIT_FOR_INCOMING 1
Definition at line 126 of file source-pfring.c.
Referenced by ReceivePfringLoop().
Typedef Documentation
typedef struct PfringThreadVars_ PfringThreadVars
Structure to hold thread specific variables.
Enumeration Type Documentation
enum PfringThreadVarsFlags
Enumerator
PFRING_FLAGS_ZERO_COPY
Definition at line 128 of file source-pfring.c.
Function Documentation
TmEcode DecodePfring (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
This function passes off to link type decoders.
DecodePfring reads packets from the PacketQueue. Inside of libpcap version of PF_RING all packets are marked as a link type of ethernet so that is what we do here.
Parameters
tv pointer to ThreadVars
p pointer to the current packet
data pointer that gets cast into PfringThreadVars for ptv
pq pointer to the current PacketQueue
Todo:
Verify that PF_RING only deals with ethernet traffic
Warning
This function bypasses the pkt buf and len macro's
Return values
TM_ECODE_OK is always returned
Definition at line 619 of file source-pfring.c.
References DecodeThreadVars_::counter_vlan, DecodeEthernet(), DecodeUpdatePacketCounters(), Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, PacketDecodeFinalize(), PKT_PSEUDO_STREAM_END, StatsIncr(), TM_ECODE_OK, and Packet_::vlan_idx.
Referenced by TmModuleDecodePfringRegister().
TmEcode DecodePfringThreadDeinit (ThreadVars * tv, void * data)
Definition at line 673 of file source-pfring.c.
References DecodeThreadVarsFree(), SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodePfringRegister().
TmEcode DecodePfringThreadInit (ThreadVars * tv, void * initdata, void ** data)
This an Init function for DecodePfring.
Parameters
tv pointer to ThreadVars
initdata pointer to initilization data.
data pointer that gets cast into PfringThreadVars for ptv
Return values
TM_ECODE_OK is returned on success
TM_ECODE_FAILED is returned on error
Definition at line 652 of file source-pfring.c.
References DecodeRegisterPerfCounters(), DecodeThreadVarsAlloc(), SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleDecodePfringRegister().
TmEcode ReceivePfringLoop (ThreadVars * tv, void * data, void * slot)
Recieves packets from an interface via libpfring.
This function recieves packets from an interface and passes the packet on to the pfring callback function.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into PfringThreadVars for ptv
slot slot containing task information
Return values
TM_ECODE_OK on success
TM_ECODE_FAILED on failure
Definition at line 295 of file source-pfring.c.
References PfringThreadVars_::flags, GET_PKT_DIRECT_DATA, GET_PKT_DIRECT_MAX_SIZE, LIBPFRING_WAIT_FOR_INCOMING, PacketGetFromQueueOrAlloc(), PacketPoolWait(), PacketSetData(), PfringThreadVars_::pd, PFRING_FLAGS_ZERO_COPY, PKT_SET_SRC, PKT_SRC_WIRE, SC_ERR_PF_RING_OPEN, SC_ERR_PF_RING_RECV, SCEnter, SCLogError, SCReturnInt, PfringThreadVars_::slot, TmSlot_::slot_next, StatsSyncCountersIfSignalled, suricata_ctl_flags, SURICATA_KILL, SURICATA_STOP, TM_ECODE_FAILED, TM_ECODE_OK, TmqhOutputPacketpool(), Packet_::ts, and PfringThreadVars_::tv.
Referenced by TmModuleReceivePfringRegister().
TmEcode ReceivePfringThreadDeinit (ThreadVars * tv, void * data)
DeInit function closes pd at exit.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into PfringThreadVars for ptvi
Return values
TM_ECODE_OK is always returned
Definition at line 586 of file source-pfring.c.
References PfringThreadVars_::bpf_filter, PfringThreadVars_::interface, PfringThreadVars_::pd, SCFree, and TM_ECODE_OK.
Referenced by TmModuleReceivePfringRegister().
void ReceivePfringThreadExitStats (ThreadVars * tv, void * data)
This function prints stats to the screen at exit.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into PfringThreadVars for ptv
Definition at line 568 of file source-pfring.c.
References PfringThreadVars_::bytes, PfringThreadVars_::capture_kernel_drops, PfringThreadVars_::capture_kernel_packets, ThreadVars_::name, PfringThreadVars_::pkts, SCLogInfo, and StatsGetLocalCounterValue().
Referenced by TmModuleReceivePfringRegister().
TmEcode ReceivePfringThreadInit (ThreadVars * tv, void * initdata, void ** data)
Init function for RecievePfring.
This is a setup function for recieving packets via libpfring.
Parameters
tv pointer to ThreadVars
initdata pointer to the interface passed from the user
data pointer gets populated with PfringThreadVars
Todo:
add a config option for setting cluster id
Create a general pfring setup function.
Return values
TM_ECODE_OK on success
TM_ECODE_FAILED on error
Definition at line 396 of file source-pfring.c.
References PfringIfaceConfig_::bpf_filter, PfringThreadVars_::bpf_filter, PfringThreadVars_::capture_kernel_drops, PfringThreadVars_::capture_kernel_packets, PfringIfaceConfig_::checksum_mode, PfringThreadVars_::checksum_mode, CHECKSUM_VALIDATION_AUTO, CHECKSUM_VALIDATION_RXONLY, CLUSTER_FLOW, CLUSTER_FLOW_5_TUPLE, PfringIfaceConfig_::cluster_id, PfringThreadVars_::cluster_id, ConfGetBool(), PfringIfaceConfig_::ctype, PfringThreadVars_::ctype, default_packet_size, PfringIfaceConfig_::DerefFunc, PfringIfaceConfig_::flags, PfringThreadVars_::flags, PfringIfaceConfig_::iface, PfringThreadVars_::interface, PfringThreadVars_::livedev, LiveGetDevice(), ThreadVars_::name, PfringThreadVars_::pd, PFRING_CONF_FLAGS_CLUSTER, PFRING_FLAGS_ZERO_COPY, PROG_NAME, RunmodeGetActive(), SC_ERR_INVALID_VALUE, SC_ERR_MEM_ALLOC, SC_ERR_PF_RING_OPEN, SC_ERR_PF_RING_SET_CLUSTER_FAILED, SCFree, SCKernelVersionIsAtLeast(), SCLogError, SCLogInfo, SCLogWarning, SCMalloc, SCMutexLock, SCMutexUnlock, SCReturnInt, SCStrdup, StatsRegisterCounter(), PfringIfaceConfig_::threads, PfringThreadVars_::threads, TM_ECODE_FAILED, TM_ECODE_OK, PfringThreadVars_::tv, unlikely, version, and PfringThreadVars_::vlan_disabled.
Referenced by TmModuleReceivePfringRegister().
void TmModuleDecodePfringRegister (void)
Registration Function for DecodePfring.
Todo:
Unit tests are needed for this module.
Definition at line 188 of file source-pfring.c.
References DecodePfring(), DecodePfringThreadDeinit(), DecodePfringThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEPFRING, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceivePfringRegister (void)
Registration Function for RecievePfring.
Todo:
Unit tests are needed for this module.
Definition at line 172 of file source-pfring.c.
References TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceivePfringLoop(), ReceivePfringThreadDeinit(), ReceivePfringThreadExitStats(), ReceivePfringThreadInit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEPFRING.
Referenced by RegisterAllModules().