suricata: src/source-ipfw.h File Reference
source-ipfw.h File Reference
Data Structures
struct IPFWPacketVars_
struct IPFWQueueVars_
Macros
#define IPFW_MAX_QUEUE 16
Typedefs
typedef struct IPFWPacketVars_ IPFWPacketVars
typedef struct IPFWQueueVars_ IPFWQueueVars
Functions
void * IPFWGetThread (int number)
Get a pointer to the IPFW thread at index.
int IPFWRegisterQueue (char *queue)
Add an IPFW divert.
void TmModuleReceiveIPFWRegister (void)
Registration Function for RecieveIPFW.
void TmModuleVerdictIPFWRegister (void)
Registration Function for VerdictIPFW.
void TmModuleDecodeIPFWRegister (void)
Registration Function for DecodeIPFW.
Detailed Description
Author
Nick Rogness nick@.nosp@m.rogn.nosp@m.ess.n.nosp@m.et
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file source-ipfw.h.
Macro Definition Documentation
#define IPFW_MAX_QUEUE 16
Definition at line 28 of file source-ipfw.h.
Referenced by IPFWRegisterQueue().
Typedef Documentation
typedef struct IPFWPacketVars_ IPFWPacketVars
typedef struct IPFWQueueVars_ IPFWQueueVars
Function Documentation
void* IPFWGetThread (int number)
Get a pointer to the IPFW thread at index.
This function is temporary used as configuration parser.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the IPFWThreadVars at index
NULL on error
Definition at line 785 of file source-ipfw.c.
Referenced by RunModeIpsIPFWAutoFp(), and RunModeIpsIPFWWorker().
int IPFWRegisterQueue (char * queue)
Add an IPFW divert.
Parameters
string with the queue name
Return values
0 on success.
-1 on failure.
Definition at line 720 of file source-ipfw.c.
References ByteExtractStringUint16(), IPFWThreadVars_::ipfw_index, IPFW_MAX_QUEUE, LiveRegisterDevice(), IPFWQueueVars_::port_num, SC_ERR_INVALID_ARGUMENT, SCLogDebug, SCLogError, SCMutexLock, and SCMutexUnlock.
void TmModuleDecodeIPFWRegister (void)
Registration Function for DecodeIPFW.
Todo:
Unit tests are needed for this module.
Definition at line 190 of file source-ipfw.c.
References DecodeIPFW(), DecodeIPFWThreadDeinit(), DecodeIPFWThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEIPFW, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceiveIPFWRegister (void)
Registration Function for RecieveIPFW.
Todo:
Unit tests are needed for this module.
Todo:
untested
Definition at line 153 of file source-ipfw.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceiveIPFWLoop(), ReceiveIPFWThreadDeinit(), ReceiveIPFWThreadExitStats(), ReceiveIPFWThreadInit(), TmModule_::RegisterTests, SC_CAP_NET_ADMIN, SC_CAP_NET_BIND_SERVICE, SC_CAP_NET_BROADCAST, SC_CAP_NET_RAW, SCMutexInit, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEIPFW.
Referenced by RegisterAllModules().
void TmModuleVerdictIPFWRegister (void)
Registration Function for VerdictIPFW.
Todo:
Unit tests are needed for this module.
Todo:
untested
Definition at line 174 of file source-ipfw.c.
References TmModule_::cap_flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, SC_CAP_NET_ADMIN, SC_CAP_NET_BIND_SERVICE, SC_CAP_NET_RAW, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, tmm_modules, TMM_VERDICTIPFW, VerdictIPFW(), VerdictIPFWThreadDeinit(), VerdictIPFWThreadExitStats(), and VerdictIPFWThreadInit().
Referenced by RegisterAllModules().