suricata: src/source-pcap-file.h File Reference
source-pcap-file.h File Reference
Functions
void TmModuleReceivePcapFileRegister (void)
void TmModuleDecodePcapFileRegister (void)
void PcapIncreaseInvalidChecksum ()
void PcapFileGlobalInit ()
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file source-pcap-file.h.
Function Documentation
void PcapFileGlobalInit ()
Definition at line 136 of file source-pcap-file.c.
References SC_ATOMIC_INIT.
Referenced by RunModeFilePcapAutoFp(), and RunModeFilePcapSingle().
void PcapIncreaseInvalidChecksum ()
Definition at line 469 of file source-pcap-file.c.
References SC_ATOMIC_ADD.
void TmModuleDecodePcapFileRegister (void)
Definition at line 124 of file source-pcap-file.c.
References TmModule_::cap_flags, DecodePcapFile(), DecodePcapFileThreadDeinit(), DecodePcapFileThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEPCAPFILE, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceivePcapFileRegister (void)
Definition at line 109 of file source-pcap-file.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceivePcapFileLoop(), ReceivePcapFileThreadDeinit(), ReceivePcapFileThreadExitStats(), ReceivePcapFileThreadInit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEPCAPFILE.
Referenced by RegisterAllModules().