suricata: src/source-pcap.c File Reference
source-pcap.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "packet-queue.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "source-pcap.h"
#include "conf.h"
#include "util-debug.h"
#include "util-error.h"
#include "util-privs.h"
#include "util-device.h"
#include "util-optimize.h"
#include "util-checksum.h"
#include "util-ioctl.h"
#include "tmqh-packetpool.h"
Data Structures
struct PcapThreadVars_
Structure to hold thread specific variables.
Macros
#define PCAP_STATE_DOWN 0
#define PCAP_STATE_UP 1
#define PCAP_RECONNECT_TIMEOUT 500000
Typedefs
typedef struct PcapThreadVars_ PcapThreadVars
Structure to hold thread specific variables.
Functions
TmEcode ReceivePcapThreadInit (ThreadVars *tv, void *initdata, void **data)
Init function for ReceivePcap.
void ReceivePcapThreadExitStats (ThreadVars *tv, void *data)
This function prints stats to the screen at exit.
TmEcode ReceivePcapThreadDeinit (ThreadVars *tv, void *data)
DeInit function closes pcap_handle at exit.
TmEcode ReceivePcapLoop (ThreadVars *tv, void *data, void *slot)
Main PCAP reading Loop function.
TmEcode DecodePcapThreadInit (ThreadVars *, void *, void **)
TmEcode DecodePcapThreadDeinit (ThreadVars *tv, void *data)
TmEcode DecodePcap (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
This function passes off to link type decoders.
void TmModuleReceivePcapRegister (void)
Registration Function for RecievePcap.
void TmModuleDecodePcapRegister (void)
Registration Function for DecodePcap.
void PcapCallbackLoop (char *user, struct pcap_pkthdr *h, u_char *pkt)
void PcapTranslateIPToDevice (char *pcap_dev, size_t len)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Live pcap packet acquisition support
Definition in file source-pcap.c.
Macro Definition Documentation
#define PCAP_RECONNECT_TIMEOUT 500000
Definition at line 60 of file source-pcap.c.
Referenced by ReceivePcapLoop().
#define PCAP_STATE_DOWN 0
Definition at line 57 of file source-pcap.c.
#define PCAP_STATE_UP 1
Definition at line 58 of file source-pcap.c.
Typedef Documentation
typedef struct PcapThreadVars_ PcapThreadVars
Structure to hold thread specific variables.
Function Documentation
TmEcode DecodePcap (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
This function passes off to link type decoders.
DecodePcap reads packets from the PacketQueue and passes them off to the proper link type decoder.
Parameters
t pointer to ThreadVars
p pointer to the current packet
data pointer that gets cast into PcapThreadVars for ptv
pq pointer to the current PacketQueue
Definition at line 696 of file source-pcap.c.
References Packet_::datalink, DecodeEthernet(), DecodeNull(), DecodePPP(), DecodeRaw(), DecodeSll(), DecodeUpdatePacketCounters(), Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, LINKTYPE_ETHERNET, LINKTYPE_LINUX_SLL, LINKTYPE_NULL, LINKTYPE_PPP, LINKTYPE_RAW, PacketDecodeFinalize(), PKT_PSEUDO_STREAM_END, SC_ERR_DATALINK_UNIMPLEMENTED, SCEnter, SCLogError, SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodePcapRegister().
TmEcode DecodePcapThreadDeinit (ThreadVars * tv, void * data)
Definition at line 758 of file source-pcap.c.
References DecodeThreadVarsFree(), SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodePcapRegister().
TmEcode DecodePcapThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 736 of file source-pcap.c.
References DecodeRegisterPerfCounters(), DecodeThreadVarsAlloc(), SCEnter, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleDecodePcapRegister().
void PcapCallbackLoop (char * user, struct pcap_pkthdr * h, u_char * pkt)
Definition at line 230 of file source-pcap.c.
References PcapThreadVars_::bytes, PcapThreadVars_::cb_result, PcapThreadVars_::checksum_mode, CHECKSUM_VALIDATION_AUTO, CHECKSUM_VALIDATION_DISABLE, ChecksumAutoModeCheck(), PcapThreadVars_::datalink, Packet_::datalink, Packet_::flags, LiveDevice_::ignore_checksum, PcapThreadVars_::last_stats_dump, PcapThreadVars_::livedev, Packet_::livedev, PacketCopyData(), PacketGetFromQueueOrAlloc(), PcapThreadVars_::pcap_handle, PKT_IGNORE_CHECKSUM, PKT_SET_SRC, PKT_SRC_WIRE, PcapThreadVars_::pkts, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCEnter, SCLogDebug, SCReturn, PcapThreadVars_::slot, TimeGet(), TM_ECODE_FAILED, TM_ECODE_OK, TmqhOutputPacketpool(), Packet_::ts, PcapThreadVars_::tv, and unlikely.
Referenced by ReceivePcapLoop().
void PcapTranslateIPToDevice (char * pcap_dev, size_t len)
Definition at line 765 of file source-pcap.c.
References strlcpy().
TmEcode ReceivePcapLoop (ThreadVars * tv, void * data, void * slot)
Main PCAP reading Loop function.
Definition at line 294 of file source-pcap.c.
References PcapThreadVars_::cb_result, PacketPoolWait(), PcapThreadVars_::pcap_handle, PCAP_RECONNECT_TIMEOUT, PcapCallbackLoop(), SC_ERR_PCAP_DISPATCH, SCEnter, SCLogError, SCReturnInt, PcapThreadVars_::slot, TmSlot_::slot_next, StatsSyncCountersIfSignalled, suricata_ctl_flags, SURICATA_KILL, SURICATA_STOP, TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by TmModuleReceivePcapRegister().
TmEcode ReceivePcapThreadDeinit (ThreadVars * tv, void * data)
DeInit function closes pcap_handle at exit.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into PcapThreadVars for ptv
Definition at line 677 of file source-pcap.c.
References PcapThreadVars_::pcap_handle, SCReturnInt, and TM_ECODE_OK.
void ReceivePcapThreadExitStats (ThreadVars * tv, void * data)
This function prints stats to the screen at exit.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into PcapThreadVars for ptv
Definition at line 643 of file source-pcap.c.
References PcapThreadVars_::bytes, ThreadVars_::name, PcapThreadVars_::pcap_handle, PcapThreadVars_::pkts, SC_ERR_STAT, SCEnter, SCLogError, and SCLogInfo.
Referenced by TmModuleReceivePcapRegister().
TmEcode ReceivePcapThreadInit (ThreadVars * tv, void * initdata, void ** data)
Init function for ReceivePcap.
This is a setup function for recieving packets via libpcap. There are two versions of this function depending on the major version of libpcap used. For versions prior to 1.x we use open_pcap_live, for versions 1.x and greater we use pcap_create + pcap_activate.
Parameters
tv pointer to ThreadVars
initdata pointer to the interface passed from the user
data pointer gets populated with PcapThreadVars
Todo:
Create a general pcap setup function.
Definition at line 535 of file source-pcap.c.
References PcapIfaceConfig_::bpf_filter, PcapThreadVars_::bpf_filter, PcapThreadVars_::capture_kernel_drops, PcapThreadVars_::capture_kernel_ifdrops, PcapThreadVars_::capture_kernel_packets, PcapThreadVars_::datalink, PcapIfaceConfig_::DerefFunc, PcapThreadVars_::filter, GetIfaceMaxPacketSize(), PcapIfaceConfig_::iface, PcapThreadVars_::iface, LIBPCAP_COPYWAIT, LIBPCAP_PROMISC, LIBPCAP_SNAPLEN, PcapThreadVars_::livedev, LiveGetDevice(), PcapThreadVars_::pcap_handle, PCAP_IFACE_NAME_LENGTH, PcapThreadVars_::pcap_snaplen, SC_ERR_BPF, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SC_ERR_PCAP_OPEN_LIVE, SCEnter, SCFree, SCLogError, SCLogInfo, SCMalloc, SCMutexLock, SCMutexUnlock, SCReturnInt, PcapIfaceConfig_::snaplen, StatsRegisterCounter(), strlcpy(), TM_ECODE_FAILED, TM_ECODE_OK, PcapThreadVars_::tv, and unlikely.
Referenced by TmModuleReceivePcapRegister().
void TmModuleDecodePcapRegister (void)
Registration Function for DecodePcap.
Todo:
Unit tests are needed for this module.
Definition at line 142 of file source-pcap.c.
References TmModule_::cap_flags, DecodePcap(), DecodePcapThreadDeinit(), DecodePcapThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEPCAP, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceivePcapRegister (void)
Registration Function for RecievePcap.
Todo:
Unit tests are needed for this module.
Definition at line 125 of file source-pcap.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceivePcapLoop(), ReceivePcapThreadExitStats(), ReceivePcapThreadInit(), TmModule_::RegisterTests, SC_CAP_NET_RAW, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEPCAP.
Referenced by RegisterAllModules().