suricata: src/source-nfq.c File Reference
source-nfq.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "packet-queue.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "tm-queuehandlers.h"
#include "tmqh-packetpool.h"
#include "conf.h"
#include "config.h"
#include "conf-yaml-loader.h"
#include "source-nfq-prototypes.h"
#include "action-globals.h"
#include "util-debug.h"
#include "util-error.h"
#include "util-byte.h"
#include "util-privs.h"
#include "util-device.h"
#include "runmodes.h"
#include "source-nfq.h"
Data Structures
struct NFQThreadVars_
struct NFQCnf_
Macros
#define MAX_ALREADY_TREATED 5
#define NFQ_VERDICT_RETRY_TIME 3
#define NFQ_BURST_FACTOR 4
#define SOL_NETLINK 270
#define NFQ_FLAG_FAIL_OPEN (1 << 0)
#define NFQMutexLock(nq)
#define NFQMutexUnlock(nq)
#define T_DATA_SIZE 70000
Typedefs
typedef struct NFQThreadVars_ NFQThreadVars
typedef enum NFQMode_ NFQMode
typedef struct NFQCnf_ NFQCnf
Enumerations
enum NFQMode_ { NFQ_ACCEPT_MODE, NFQ_REPEAT_MODE, NFQ_ROUTE_MODE }
Functions
TmEcode ReceiveNFQLoop (ThreadVars *tv, void *data, void *slot)
Main NFQ reading Loop function.
TmEcode ReceiveNFQThreadInit (ThreadVars *, void *, void **)
TmEcode ReceiveNFQThreadDeinit (ThreadVars *, void *)
void ReceiveNFQThreadExitStats (ThreadVars *tv, void *data)
NFQ receive module stats printing function.
TmEcode VerdictNFQ (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
NFQ verdict module packet entry function.
TmEcode VerdictNFQThreadInit (ThreadVars *, void *, void **)
TmEcode VerdictNFQThreadDeinit (ThreadVars *, void *)
TmEcode DecodeNFQ (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
Decode a packet coming from NFQ.
TmEcode DecodeNFQThreadInit (ThreadVars *tv, void *initdata, void **data)
Initialize the NFQ Decode threadvars.
TmEcode DecodeNFQThreadDeinit (ThreadVars *tv, void *data)
TmEcode NFQSetVerdict (Packet *p)
NFQ verdict function.
void TmModuleReceiveNFQRegister (void)
void TmModuleVerdictNFQRegister (void)
void TmModuleDecodeNFQRegister (void)
void NFQInitConfig (char quiet)
To initialize the NFQ global configuration data.
int NFQSetupPkt (Packet *p, struct nfq_q_handle *qh, void *data)
Read data from nfq message and setup Packet.
TmEcode NFQInitThread (NFQThreadVars *nfq_t, uint32_t queue_maxlen)
int NFQRegisterQueue (char *queue)
Add a Netfilter queue.
void * NFQGetQueue (int number)
Get a pointer to the NFQ queue at index.
void * NFQGetThread (int number)
Get a pointer to the NFQ thread at index.
void NFQRecvPkt (NFQQueueVars *t, NFQThreadVars *tv)
NFQ function to get a packet from the kernel.
Variables
int max_pending_packets
NFQCnf nfq_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Netfilter's netfilter_queue support for reading packets from the kernel and setting verdicts back to it (inline mode). Supported on Linux and Windows.
Todo:
test if Receive and Verdict if both are present
Definition in file source-nfq.c.
Macro Definition Documentation
#define MAX_ALREADY_TREATED 5
Definition at line 111 of file source-nfq.c.
Referenced by NFQSetupPkt().
#define NFQ_BURST_FACTOR 4
Definition at line 116 of file source-nfq.c.
Referenced by ReceiveNFQThreadInit().
#define NFQ_FLAG_FAIL_OPEN (1 << 0)
Definition at line 166 of file source-nfq.c.
Referenced by NFQInitConfig(), and NFQInitThread().
#define NFQ_VERDICT_RETRY_TIME 3
Definition at line 112 of file source-nfq.c.
Referenced by NFQSetupPkt(), and NFQSetVerdict().
#define NFQMutexLock (nq)
Value:
do {           \
    if ((nq)->use_mutex)                \
        SCMutexLock(&(nq)->mutex_qh);   \
} while (0)
Definition at line 396 of file source-nfq.c.
Referenced by NFQRecvPkt(), NFQSetVerdict(), ReceiveNFQLoop(), ReceiveNFQThreadDeinit(), and VerdictNFQThreadDeinit().
#define NFQMutexUnlock (nq)
Value:
do {         \
    if ((nq)->use_mutex)                \
        SCMutexUnlock(&(nq)->mutex_qh); \
} while (0)
Definition at line 401 of file source-nfq.c.
Referenced by NFQRecvPkt(), NFQSetVerdict(), ReceiveNFQLoop(), ReceiveNFQThreadDeinit(), and VerdictNFQThreadDeinit().
#define SOL_NETLINK 270
Definition at line 119 of file source-nfq.c.
Referenced by NFQInitThread().
#define T_DATA_SIZE 70000
Referenced by ReceiveNFQThreadInit().
Typedef Documentation
typedef struct NFQCnf_ NFQCnf
typedef enum NFQMode_ NFQMode
typedef struct NFQThreadVars_ NFQThreadVars
Enumeration Type Documentation
enum NFQMode_
Enumerator
NFQ_ACCEPT_MODE
NFQ_REPEAT_MODE
NFQ_ROUTE_MODE
Definition at line 160 of file source-nfq.c.
Function Documentation
TmEcode DecodeNFQ (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
Decode a packet coming from NFQ.
Definition at line 1222 of file source-nfq.c.
References DecodeIPV4(), DecodeIPV6(), DecodeUpdatePacketCounters(), Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, ip4h, ip6h, IPV4_GET_RAW_VER, IPV6_GET_RAW_VER, PacketDecodeFinalize(), PKT_PSEUDO_STREAM_END, SCLogDebug, and TM_ECODE_OK.
Referenced by TmModuleDecodeNFQRegister().
TmEcode DecodeNFQThreadDeinit (ThreadVars * tv, void * data)
Definition at line 1269 of file source-nfq.c.
References DecodeThreadVarsFree(), SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodeNFQRegister().
TmEcode DecodeNFQThreadInit (ThreadVars * tv, void * initdata, void ** data)
Initialize the NFQ Decode threadvars.
Definition at line 1254 of file source-nfq.c.
References DecodeRegisterPerfCounters(), DecodeThreadVarsAlloc(), SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleDecodeNFQRegister().
void* NFQGetQueue (int number)
Get a pointer to the NFQ queue at index.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the NFQThreadVars at index
NULL on error
Definition at line 841 of file source-nfq.c.
Referenced by NFQInitThread(), ReceiveNFQLoop(), ReceiveNFQThreadDeinit(), ReceiveNFQThreadExitStats(), and VerdictNFQThreadDeinit().
void* NFQGetThread (int number)
Get a pointer to the NFQ thread at index.
This function is temporary used as configuration parser.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the NFQThreadVars at index
NULL on error
Definition at line 859 of file source-nfq.c.
Referenced by RunModeIpsNFQAutoFp(), and RunModeIpsNFQWorker().
void NFQInitConfig (char quiet)
To initialize the NFQ global configuration data.
Parameters
quiet It tells the mode of operation, if it is TRUE nothing will be get printed.
Definition at line 221 of file source-nfq.c.
References NFQCnf_::batchcount, ConfGet(), ConfGetBool(), ConfGetInt(), NFQCnf_::flags, NFQCnf_::mark, NFQCnf_::mask, NFQCnf_::mode, NFQCnf_::next_queue, NFQ_ACCEPT_MODE, NFQ_FLAG_FAIL_OPEN, NFQ_REPEAT_MODE, NFQ_ROUTE_MODE, SC_ERR_INVALID_ARGUMENT, SC_ERR_NFQ_NOSUPPORT, SCLogDebug, SCLogError, SCLogInfo, and SCLogWarning.
TmEcode NFQInitThread (NFQThreadVars * nfq_t, uint32_t queue_maxlen)
Definition at line 544 of file source-nfq.c.
References NFQCnf_::batchcount, FALSE, NFQQueueVars_::fd, flags, NFQCnf_::flags, NFQQueueVars_::h, NFQQueueVars_::maxlen, NFQ_FLAG_FAIL_OPEN, NFQThreadVars_::nfq_index, NFQGetQueue(), NFQQueueVars_::nh, NFQQueueVars_::qh, NFQQueueVars_::queue_num, SC_ERR_INVALID_ARGUMENT, SC_ERR_NFQ_BIND, SC_ERR_NFQ_CREATE_QUEUE, SC_ERR_NFQ_MAXLEN, SC_ERR_NFQ_OPEN, SC_ERR_NFQ_SET_MODE, SC_ERR_NFQ_SETSOCKOPT, SC_ERR_NFQ_UNBIND, SCLogDebug, SCLogError, SCLogInfo, SCLogWarning, SOL_NETLINK, TM_ECODE_FAILED, TM_ECODE_OK, NFQGlobalVars_::unbind, and NFQQueueVars_::verdict_cache.
Referenced by ReceiveNFQThreadInit().
void NFQRecvPkt (NFQQueueVars * t, NFQThreadVars * tv)
NFQ function to get a packet from the kernel.
Note
separate functions for Linux and Win32 for readability.
Definition at line 873 of file source-nfq.c.
References NFQThreadVars_::data, NFQThreadVars_::datalen, NFQQueueVars_::errs, NFQQueueVars_::fd, NFQQueueVars_::h, NFQMutexLock, NFQMutexUnlock, NFQQueueVars_::qh, SC_ERR_NFQ_HANDLE_PKT, SC_ERR_NFQ_RECV, and SCLogWarning.
Referenced by ReceiveNFQLoop().
int NFQRegisterQueue (char * queue)
Add a Netfilter queue.
Parameters
string with the queue name
Return values
0 on success.
-1 on failure.
Definition at line 792 of file source-nfq.c.
References ByteExtractStringUint16(), LiveRegisterDevice(), NFQThreadVars_::nfq_index, NFQ_MAX_QUEUE, NFQQueueVars_::queue_num, SC_ERR_INVALID_ARGUMENT, SCLogDebug, SCLogError, SCMutexLock, and SCMutexUnlock.
int NFQSetupPkt (Packet * p, struct nfq_q_handle * qh, void * data)
Read data from nfq message and setup Packet.
Note
In case of error, this function verdict the packet to avoid skb to get stuck in kernel.
Definition at line 413 of file source-nfq.c.
References Packet_::datalink, NFQPacketVars_::hw_protocol, NFQPacketVars_::id, NFQPacketVars_::ifi, NFQPacketVars_::ifo, NFQPacketVars_::mark, NFQCnf_::mark, NFQCnf_::mask, MAX_ALREADY_TREATED, NFQCnf_::mode, NFQ_REPEAT_MODE, Packet_::nfq_v, NFQ_VERDICT_RETRY_TIME, PacketCopyData(), PacketSetData(), SC_ERR_INVALID_ARGUMENTS, SC_ERR_NFQ_SET_VERDICT, SCLogInfo, SCLogWarning, SET_PKT_LEN, Packet_::ts, and NFQPacketVars_::verdicted.
TmEcode NFQSetVerdict (Packet * p)
NFQ verdict function.
Todo:
add a test on validity of the entry NFQQueueVars could have been wipeout
Definition at line 1033 of file source-nfq.c.
References NFQQueueVars_::accepted, ACTION_DROP, NFQQueueVars_::dropped, Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, NFQPacketVars_::id, NFQPacketVars_::mark, NFQCnf_::mark, NFQCnf_::mask, NFQCnf_::mode, NFQCnf_::next_queue, NFQ_ACCEPT_MODE, NFQPacketVars_::nfq_index, NFQ_REPEAT_MODE, NFQ_ROUTE_MODE, Packet_::nfq_v, NFQ_VERDICT_RETRY_TIME, NFQMutexLock, NFQMutexUnlock, PACKET_TEST_ACTION, PKT_MARK_MODIFIED, PKT_PSEUDO_STREAM_END, PKT_STREAM_MODIFIED, NFQQueueVars_::qh, NFQQueueVars_::replaced, SC_ERR_NFQ_SET_VERDICT, SCLogWarning, TM_ECODE_FAILED, TM_ECODE_OK, and NFQPacketVars_::verdicted.
Referenced by VerdictNFQ().
TmEcode ReceiveNFQLoop (ThreadVars * tv, void * data, void * slot)
Main NFQ reading Loop function.
Definition at line 990 of file source-nfq.c.
References NFQThreadVars_::nfq_index, NFQGetQueue(), NFQMutexLock, NFQMutexUnlock, NFQRecvPkt(), NFQQueueVars_::qh, SCEnter, SCReturnInt, NFQThreadVars_::slot, TmSlot_::slot_next, StatsSyncCountersIfSignalled, suricata_ctl_flags, and TM_ECODE_OK.
Referenced by TmModuleReceiveNFQRegister().
TmEcode ReceiveNFQThreadDeinit (ThreadVars * t, void * data)
Definition at line 735 of file source-nfq.c.
References NFQThreadVars_::data, NFQThreadVars_::datalen, NFQThreadVars_::nfq_index, NFQGetQueue(), NFQMutexLock, NFQMutexUnlock, NFQQueueVars_::qh, NFQQueueVars_::queue_num, SCFree, SCLogDebug, and TM_ECODE_OK.
Referenced by TmModuleReceiveNFQRegister().
void ReceiveNFQThreadExitStats (ThreadVars * tv, void * data)
NFQ receive module stats printing function.
Definition at line 1018 of file source-nfq.c.
References NFQQueueVars_::accepted, NFQQueueVars_::bytes, NFQQueueVars_::dropped, NFQQueueVars_::errs, ThreadVars_::name, NFQThreadVars_::nfq_index, NFQGetQueue(), NFQQueueVars_::pkts, NFQQueueVars_::replaced, and SCLogNotice.
Referenced by TmModuleReceiveNFQRegister().
TmEcode ReceiveNFQThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 696 of file source-nfq.c.
References NFQThreadVars_::data, NFQThreadVars_::datalen, max_pending_packets, NFQ_BURST_FACTOR, NFQInitThread(), SC_ERR_NFQ_THREAD_INIT, SCLogError, SCMalloc, SCMutexLock, SCMutexUnlock, T_DATA_SIZE, TM_ECODE_FAILED, TM_ECODE_OK, and NFQThreadVars_::tv.
Referenced by TmModuleReceiveNFQRegister().
void TmModuleDecodeNFQRegister (void)
Definition at line 205 of file source-nfq.c.
References DecodeNFQ(), DecodeNFQThreadDeinit(), DecodeNFQThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODENFQ, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceiveNFQRegister (void)
Definition at line 179 of file source-nfq.c.
References TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceiveNFQLoop(), ReceiveNFQThreadDeinit(), ReceiveNFQThreadExitStats(), ReceiveNFQThreadInit(), TmModule_::RegisterTests, SCMutexInit, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVENFQ.
Referenced by RegisterAllModules().
void TmModuleVerdictNFQRegister (void)
Definition at line 195 of file source-nfq.c.
References TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, tmm_modules, TMM_VERDICTNFQ, VerdictNFQ(), VerdictNFQThreadDeinit(), and VerdictNFQThreadInit().
Referenced by RegisterAllModules().
TmEcode VerdictNFQ (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
NFQ verdict module packet entry function.
Definition at line 1174 of file source-nfq.c.
References CaptureStatsUpdate(), IS_TUNNEL_PKT, m, NFQSetVerdict(), Packet_::root, SCLogDebug, SCMutex, SCMutexLock, SCMutexUnlock, NFQThreadVars_::stats, TM_ECODE_OK, TUNNEL_INCR_PKT_RTV, Packet_::tunnel_mutex, TUNNEL_PKT_RTV, and TUNNEL_PKT_TPR.
Referenced by TmModuleVerdictNFQRegister().
TmEcode VerdictNFQThreadDeinit (ThreadVars * tv, void * data)
Definition at line 768 of file source-nfq.c.
References NFQThreadVars_::nfq_index, NFQGetQueue(), NFQMutexLock, NFQMutexUnlock, NFQQueueVars_::qh, NFQQueueVars_::queue_num, SCLogDebug, and TM_ECODE_OK.
Referenced by TmModuleVerdictNFQRegister().
TmEcode VerdictNFQThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 758 of file source-nfq.c.
References CaptureStatsSetup(), NFQThreadVars_::stats, and TM_ECODE_OK.
Referenced by TmModuleVerdictNFQRegister().
Variable Documentation
NFQCnf nfq_config
Definition at line 177 of file source-nfq.c.