suricata: src/source-pfring.h File Reference
source-pfring.h File Reference
#include <config.h>
#include <pfring.h>
Data Structures
struct PfringIfaceConfig_
Macros
#define PFRING_IFACE_NAME_LENGTH 48
#define CLUSTER_FLOW 0
#define CLUSTER_ROUND_ROBIN 1
#define CLUSTER_FLOW_5_TUPLE 4
Typedefs
typedef struct PfringIfaceConfig_ PfringIfaceConfig
Enumerations
enum PfringIfaceConfigFlags { PFRING_CONF_FLAGS_CLUSTER = 0x1 }
Functions
void TmModuleReceivePfringRegister (void)
Registration Function for RecievePfring.
void TmModuleDecodePfringRegister (void)
Registration Function for DecodePfring.
int PfringConfGetThreads (void)
void PfringLoadConfig (void)
Detailed Description
Author
William Metcalf willi.nosp@m.am.m.nosp@m.etcal.nosp@m.f@gm.nosp@m.ail.c.nosp@m.om
Definition in file source-pfring.h.
Macro Definition Documentation
#define CLUSTER_FLOW 0
Definition at line 67 of file source-pfring.h.
Referenced by ParsePfringConfig(), and ReceivePfringThreadInit().
#define CLUSTER_FLOW_5_TUPLE 4
Definition at line 69 of file source-pfring.h.
Referenced by ReceivePfringThreadInit().
#define CLUSTER_ROUND_ROBIN 1
Definition at line 68 of file source-pfring.h.
Referenced by OldParsePfringConfig(), and ParsePfringConfig().
#define PFRING_IFACE_NAME_LENGTH 48
Definition at line 27 of file source-pfring.h.
Typedef Documentation
typedef struct PfringIfaceConfig_ PfringIfaceConfig
Enumeration Type Documentation
enum PfringIfaceConfigFlags
Enumerator
PFRING_CONF_FLAGS_CLUSTER
Definition at line 34 of file source-pfring.h.
Function Documentation
int PfringConfGetThreads (void)
void PfringLoadConfig (void)
void TmModuleDecodePfringRegister (void)
Registration Function for DecodePfring.
Todo:
Unit tests are needed for this module.
Definition at line 188 of file source-pfring.c.
References DecodePfring(), DecodePfringThreadDeinit(), DecodePfringThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEPFRING, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceivePfringRegister (void)
Registration Function for RecievePfring.
Todo:
Unit tests are needed for this module.
Definition at line 172 of file source-pfring.c.
References TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceivePfringLoop(), ReceivePfringThreadDeinit(), ReceivePfringThreadExitStats(), ReceivePfringThreadInit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEPFRING.
Referenced by RegisterAllModules().