suricata: src/source-pcap.h File Reference
source-pcap.h File Reference
Data Structures
struct PcapPacketVars_
struct PcapIfaceConfig_
Macros
#define LIBPCAP_SNAPLEN 1518
#define LIBPCAP_COPYWAIT 500
#define LIBPCAP_PROMISC 1
#define PCAP_IFACE_NAME_LENGTH 128
Typedefs
typedef struct PcapPacketVars_ PcapPacketVars
typedef struct PcapIfaceConfig_ PcapIfaceConfig
Functions
void TmModuleReceivePcapRegister (void)
Registration Function for RecievePcap.
void TmModuleDecodePcapRegister (void)
Registration Function for DecodePcap.
void PcapTranslateIPToDevice (char *pcap_dev, size_t len)
int PcapLiveRegisterDevice (char *)
int PcapLiveGetDeviceCount (void)
char * PcapLiveGetDevice (int)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file source-pcap.h.
Macro Definition Documentation
#define LIBPCAP_COPYWAIT 500
Definition at line 36 of file source-pcap.h.
Referenced by ReceivePcapThreadInit().
#define LIBPCAP_PROMISC 1
Definition at line 37 of file source-pcap.h.
Referenced by ParsePcapConfig(), and ReceivePcapThreadInit().
#define LIBPCAP_SNAPLEN 1518
Definition at line 35 of file source-pcap.h.
Referenced by ReceivePcapThreadInit().
#define PCAP_IFACE_NAME_LENGTH 128
needs to be able to contain Windows adapter id's, so must be quite long.
Definition at line 47 of file source-pcap.h.
Referenced by ReceivePcapThreadInit().
Typedef Documentation
typedef struct PcapIfaceConfig_ PcapIfaceConfig
typedef struct PcapPacketVars_ PcapPacketVars
Function Documentation
char* PcapLiveGetDevice (int)
int PcapLiveGetDeviceCount (void)
int PcapLiveRegisterDevice (char *)
void PcapTranslateIPToDevice (char * pcap_dev, size_t len)
Definition at line 765 of file source-pcap.c.
References strlcpy().
void TmModuleDecodePcapRegister (void)
Registration Function for DecodePcap.
Todo:
Unit tests are needed for this module.
Definition at line 142 of file source-pcap.c.
References TmModule_::cap_flags, DecodePcap(), DecodePcapThreadDeinit(), DecodePcapThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEPCAP, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceivePcapRegister (void)
Registration Function for RecievePcap.
Todo:
Unit tests are needed for this module.
Definition at line 125 of file source-pcap.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceivePcapLoop(), ReceivePcapThreadExitStats(), ReceivePcapThreadInit(), TmModule_::RegisterTests, SC_CAP_NET_RAW, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEPCAP.
Referenced by RegisterAllModules().