suricata: src/source-nfq.h File Reference
source-nfq.h File Reference
#include "threads.h"
#include <linux/netfilter.h>
#include <libnetfilter_queue/libnetfilter_queue.h>
Data Structures
struct NFQPacketVars_
struct NFQQueueVars_
struct NFQGlobalVars_
Macros
#define NFQ_MAX_QUEUE 16
Typedefs
typedef struct NFQPacketVars_ NFQPacketVars
typedef struct NFQQueueVars_ NFQQueueVars
typedef struct NFQGlobalVars_ NFQGlobalVars
Functions
void NFQInitConfig (char quiet)
To initialize the NFQ global configuration data.
int NFQRegisterQueue (char *queue)
Add a Netfilter queue.
int NFQGetQueueCount (void)
void * NFQGetQueue (int number)
Get a pointer to the NFQ queue at index.
int NFQGetQueueNum (int number)
void * NFQGetThread (int number)
Get a pointer to the NFQ thread at index.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file source-nfq.h.
Macro Definition Documentation
#define NFQ_MAX_QUEUE 16
Definition at line 37 of file source-nfq.h.
Referenced by NFQRegisterQueue().
Typedef Documentation
typedef struct NFQGlobalVars_ NFQGlobalVars
typedef struct NFQPacketVars_ NFQPacketVars
typedef struct NFQQueueVars_ NFQQueueVars
Function Documentation
void* NFQGetQueue (int number)
Get a pointer to the NFQ queue at index.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the NFQThreadVars at index
NULL on error
Definition at line 841 of file source-nfq.c.
Referenced by NFQInitThread(), ReceiveNFQLoop(), ReceiveNFQThreadDeinit(), ReceiveNFQThreadExitStats(), and VerdictNFQThreadDeinit().
int NFQGetQueueCount (void)
int NFQGetQueueNum (int number)
void* NFQGetThread (int number)
Get a pointer to the NFQ thread at index.
This function is temporary used as configuration parser.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the NFQThreadVars at index
NULL on error
Definition at line 859 of file source-nfq.c.
Referenced by RunModeIpsNFQAutoFp(), and RunModeIpsNFQWorker().
void NFQInitConfig (char quiet)
To initialize the NFQ global configuration data.
Parameters
quiet It tells the mode of operation, if it is TRUE nothing will be get printed.
Definition at line 221 of file source-nfq.c.
References NFQCnf_::batchcount, ConfGet(), ConfGetBool(), ConfGetInt(), NFQCnf_::flags, NFQCnf_::mark, NFQCnf_::mask, NFQCnf_::mode, NFQCnf_::next_queue, NFQ_ACCEPT_MODE, NFQ_FLAG_FAIL_OPEN, NFQ_REPEAT_MODE, NFQ_ROUTE_MODE, SC_ERR_INVALID_ARGUMENT, SC_ERR_NFQ_NOSUPPORT, SCLogDebug, SCLogError, SCLogInfo, and SCLogWarning.
int NFQRegisterQueue (char * queue)
Add a Netfilter queue.
Parameters
string with the queue name
Return values
0 on success.
-1 on failure.
Definition at line 792 of file source-nfq.c.
References ByteExtractStringUint16(), LiveRegisterDevice(), NFQThreadVars_::nfq_index, NFQ_MAX_QUEUE, NFQQueueVars_::queue_num, SC_ERR_INVALID_ARGUMENT, SCLogDebug, SCLogError, SCMutexLock, and SCMutexUnlock.