suricata: src/source-erf-dag.c File Reference
source-erf-dag.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "tm-threads.h"
#include "util-privs.h"
#include "util-device.h"
#include "tmqh-packetpool.h"
#include "source-erf-dag.h"
#include <dagapi.h>
Data Structures
struct ErfDagThreadVars_
Macros
#define MINDATA 32768
#define MAXWAIT 20000
#define POLL_INTERVAL 1000;
#define BYTES_PER_LOOP (4 * 1024 * 1024) /* 4 MB */
Typedefs
typedef struct ErfDagThreadVars_ ErfDagThreadVars
Functions
TmEcode ReceiveErfDagLoop (ThreadVars *tv, void *data, void *slot)
Receives packets from a DAG interface.
TmEcode ReceiveErfDagThreadInit (ThreadVars *tv, void *initdata, void **data)
Initialize the ERF receiver thread, generate a single ErfDagThreadVar structure for each thread, this will contain a DAG file descriptor which is read when the thread executes.
void ReceiveErfDagThreadExitStats (ThreadVars *tv, void *data)
Print some stats to the log at program exit.
TmEcode ReceiveErfDagThreadDeinit (ThreadVars *tv, void *data)
Deinitializes the DAG card.
TmEcode DecodeErfDagThreadInit (ThreadVars *, void *, void **)
TmEcode DecodeErfDagThreadDeinit (ThreadVars *tv, void *data)
TmEcode DecodeErfDag (ThreadVars *tv, Packet *p, void *data, PacketQueue *pq, PacketQueue *postpq)
This function passes off to link type decoders.
void ReceiveErfDagCloseStream (int dagfd, int stream)
void TmModuleReceiveErfDagRegister (void)
Register the ERF file receiver (reader) module.
void TmModuleDecodeErfDagRegister (void)
Register the ERF file decoder module.
Variables
int max_pending_packets
Detailed Description
Author
Endace Technology Limited.
Jason MacLulich jason.nosp@m..mac.nosp@m.lulic.nosp@m.h@en.nosp@m.dace..nosp@m.com
Support for reading ERF records from a DAG card.
Only ethernet supported at this time.
Definition in file source-erf-dag.c.
Macro Definition Documentation
#define BYTES_PER_LOOP (4 * 1024 * 1024) /* 4 MB */
Definition at line 91 of file source-erf-dag.c.
#define MAXWAIT 20000
Definition at line 85 of file source-erf-dag.c.
Referenced by ReceiveErfDagThreadInit().
#define MINDATA 32768
Definition at line 82 of file source-erf-dag.c.
Referenced by ReceiveErfDagThreadInit().
#define POLL_INTERVAL 1000;
Definition at line 88 of file source-erf-dag.c.
Referenced by ReceiveErfDagThreadInit().
Typedef Documentation
typedef struct ErfDagThreadVars_ ErfDagThreadVars
Function Documentation
TmEcode DecodeErfDag (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
This function passes off to link type decoders.
Decode ErfDag DecodeErfDag reads packets from the PacketQueue and passes them off to the proper link type decoder.
Parameters
t pointer to ThreadVars
p pointer to the current packet
data pointer that gets cast into PcapThreadVars for ptv
pq pointer to the current PacketQueue
Definition at line 612 of file source-erf-dag.c.
References Packet_::datalink, DecodeEthernet(), DecodeUpdatePacketCounters(), Packet_::flags, GET_PKT_DATA, GET_PKT_LEN, LINKTYPE_ETHERNET, PacketDecodeFinalize(), PKT_PSEUDO_STREAM_END, SC_ERR_DATALINK_UNIMPLEMENTED, SCEnter, SCLogError, SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodeErfDagRegister().
TmEcode DecodeErfDagThreadDeinit (ThreadVars * tv, void * data)
Definition at line 663 of file source-erf-dag.c.
References DecodeThreadVarsFree(), SCReturnInt, and TM_ECODE_OK.
Referenced by TmModuleDecodeErfDagRegister().
TmEcode DecodeErfDagThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 645 of file source-erf-dag.c.
References DecodeRegisterPerfCounters(), DecodeThreadVarsAlloc(), SCEnter, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by TmModuleDecodeErfDagRegister().
void ReceiveErfDagCloseStream (int dagfd, int stream)
Definition at line 591 of file source-erf-dag.c.
Referenced by ReceiveErfDagLoop(), and ReceiveErfDagThreadDeinit().
TmEcode ReceiveErfDagLoop (ThreadVars * tv, void * data, void * slot)
Receives packets from a DAG interface.
Parameters
tv pointer to ThreadVars
data pointer to ErfDagThreadVars
slot slot containing task information
Return values
TM_ECODE_OK on success
TM_ECODE_FAILED on failure
Definition at line 330 of file source-erf-dag.c.
References ErfDagThreadVars_::btm, ErfDagThreadVars_::dagfd, ErfDagThreadVars_::dagname, ErfDagThreadVars_::dagstream, ReceiveErfDagCloseStream(), SC_ERR_ERF_DAG_STREAM_READ_FAILED, SCEnter, SCLogDebug, SCLogError, SCReturnInt, ErfDagThreadVars_::slot, TmSlot_::slot_next, StatsSyncCountersIfSignalled, suricata_ctl_flags, SURICATA_KILL, SURICATA_STOP, TM_ECODE_FAILED, TM_ECODE_OK, top, and ErfDagThreadVars_::top.
Referenced by TmModuleReceiveErfDagRegister().
TmEcode ReceiveErfDagThreadDeinit (ThreadVars * tv, void * data)
Deinitializes the DAG card.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into PcapThreadVars for ptv
Definition at line 579 of file source-erf-dag.c.
References ErfDagThreadVars_::dagfd, ErfDagThreadVars_::dagstream, ReceiveErfDagCloseStream(), SCEnter, SCReturnInt, and TM_ECODE_OK.
void ReceiveErfDagThreadExitStats (ThreadVars * tv, void * data)
Print some stats to the log at program exit.
Parameters
tv Pointer to ThreadVars.
data Pointer to data, ErfFileThreadVars.
Definition at line 556 of file source-erf-dag.c.
References ErfDagThreadVars_::bytes, ErfDagThreadVars_::dagstream, ErfDagThreadVars_::drops, ErfDagThreadVars_::livedev, ErfDagThreadVars_::packets, SC_ATOMIC_SET, SCLogInfo, and StatsGetLocalCounterValue().
Referenced by TmModuleReceiveErfDagRegister().
TmEcode ReceiveErfDagThreadInit (ThreadVars * tv, void * initdata, void ** data)
Initialize the ERF receiver thread, generate a single ErfDagThreadVar structure for each thread, this will contain a DAG file descriptor which is read when the thread executes.
Parameters
tv Thread variable to ThreadVars
initdata Initial data to the interface passed from the user, this is processed by the user.
We assume that we have only a single name for the DAG interface.
Parameters
data data pointer gets populated with
Definition at line 182 of file source-erf-dag.c.
References ErfDagThreadVars_::dagfd, ErfDagThreadVars_::dagname, ErfDagThreadVars_::dagstream, ErfDagThreadVars_::drops, ErfDagThreadVars_::livedev, LiveGetDevice(), MAXWAIT, MINDATA, ErfDagThreadVars_::packets, ErfDagThreadVars_::poll, POLL_INTERVAL, SC_ERR_ERF_DAG_OPEN_FAILED, SC_ERR_ERF_DAG_STREAM_OPEN_FAILED, SC_ERR_ERF_DAG_STREAM_SET_FAILED, SC_ERR_ERF_DAG_STREAM_START_FAILED, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SC_ERR_MEM_ALLOC, SCEnter, SCFree, SCLogError, SCLogInfo, SCMalloc, SCReturnInt, StatsRegisterCounter(), TM_ECODE_FAILED, TM_ECODE_OK, ErfDagThreadVars_::tv, and unlikely.
Referenced by TmModuleReceiveErfDagRegister().
void TmModuleDecodeErfDagRegister (void)
Register the ERF file decoder module.
Definition at line 153 of file source-erf-dag.c.
References TmModule_::cap_flags, DecodeErfDag(), DecodeErfDagThreadDeinit(), DecodeErfDagThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEERFDAG, and tmm_modules.
Referenced by RegisterAllModules().
void TmModuleReceiveErfDagRegister (void)
Register the ERF file receiver (reader) module.
Definition at line 135 of file source-erf-dag.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqLoop, ReceiveErfDagLoop(), ReceiveErfDagThreadExitStats(), ReceiveErfDagThreadInit(), TmModule_::RegisterTests, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEERFDAG.
Referenced by RegisterAllModules().