suricata: src/stream.c File Reference
stream.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "threads.h"
#include "stream.h"
#include "util-pool.h"
#include "util-debug.h"
#include "stream-tcp.h"
#include "flow-util.h"
Macros
#define SIZE 4072
Functions
StreamMsg * StreamMsgGetFromPool (void)
void StreamMsgReturnToPool (StreamMsg *s)
StreamMsg * StreamMsgGetFromQueue (StreamMsgQueue *q)
void StreamMsgPutInQueue (StreamMsgQueue *q, StreamMsg *s)
void * StreamMsgPoolAlloc (void)
int StreamMsgInit (void *data, void *initdata)
void StreamMsgPoolFree (void *ptr)
void StreamMsgQueuesInit (uint32_t prealloc)
void StreamMsgQueuesDeinit (char quiet)
StreamMsgQueue * StreamMsgQueueGetNew (void)
alloc a stream msg queue
void StreamMsgQueueFree (StreamMsgQueue *q)
Free a StreamMsgQueue.
void StreamMsgQueueSetMinChunkLen (uint8_t dir, uint16_t len)
uint16_t StreamMsgQueueGetMinChunkLen (uint8_t dir)
void StreamMsgReturnListToPool (void *list)
Return a list of smsgs to the pool.
int StreamSegmentForEach (const Packet *p, uint8_t flag, StreamSegmentCallback CallbackFunc, void *data)
Run callback for all segments.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Stream Chunk Handling API
Definition in file stream.c.
Macro Definition Documentation
#define SIZE 4072
Definition at line 136 of file stream.c.
Referenced by StreamMsgInit(), StreamMsgPoolAlloc(), and StreamMsgPoolFree().
Function Documentation
StreamMsg* StreamMsgGetFromPool (void)
Definition at line 100 of file stream.c.
References PoolGet(), SCMutexLock, and SCMutexUnlock.
StreamMsg* StreamMsgGetFromQueue (StreamMsgQueue * q)
Definition at line 118 of file stream.c.
References StreamMsgQueue_::len.
int StreamMsgInit (void * data, void * initdata)
Definition at line 153 of file stream.c.
References StreamMsg_::data, data, StreamMsg_::data_size, SCMutexLock, SCMutexUnlock, and SIZE.
Referenced by StreamMsgQueuesInit().
void* StreamMsgPoolAlloc (void)
Definition at line 137 of file stream.c.
References StreamMsg_::data, StreamMsg_::data_size, m, SCCalloc, SIZE, StreamTcpReassembleCheckMemcap(), and StreamTcpReassembleIncrMemuse().
Referenced by StreamMsgQueuesInit().
void StreamMsgPoolFree (void * ptr)
Definition at line 167 of file stream.c.
References SCFree, SIZE, and StreamTcpReassembleDecrMemuse().
Referenced by StreamMsgQueuesInit().
void StreamMsgPutInQueue (StreamMsgQueue * q, StreamMsg * s)
Definition at line 130 of file stream.c.
References StreamMsgQueue_::len, and SCLogDebug.
void StreamMsgQueueFree (StreamMsgQueue * q)
Free a StreamMsgQueue.
Parameters
q the queue to free
Todo:
we may want to consider non empty queue's
Definition at line 231 of file stream.c.
References SCFree, and StreamTcpReassembleDecrMemuse().
uint16_t StreamMsgQueueGetMinChunkLen (uint8_t dir)
Definition at line 246 of file stream.c.
References FLOW_PKT_TOSERVER.
StreamMsgQueue* StreamMsgQueueGetNew (void)
alloc a stream msg queue
Return values
smq ptr to the queue or NULL
Definition at line 212 of file stream.c.
References SCMalloc, StreamTcpReassembleCheckMemcap(), StreamTcpReassembleIncrMemuse(), and unlikely.
void StreamMsgQueuesDeinit (char quiet)
Definition at line 189 of file stream.c.
References Pool_::allocated, FALSE, Pool_::max_outstanding, PoolFree(), SCLogDebug, SCLogInfo, SCMutexDestroy, SCMutexLock, and SCMutexUnlock.
Referenced by StreamTcpReassembleFree().
void StreamMsgQueueSetMinChunkLen (uint8_t dir, uint16_t len)
Definition at line 237 of file stream.c.
References FLOW_PKT_TOSERVER, and len.
Referenced by StreamTcpInitConfig().
void StreamMsgQueuesInit (uint32_t prealloc)
Definition at line 175 of file stream.c.
References PoolInit(), SCMutexInit, SCMutexLock, SCMutexUnlock, StreamMsgInit(), StreamMsgPoolAlloc(), and StreamMsgPoolFree().
Referenced by StreamTcpReassemblyConfig().
void StreamMsgReturnListToPool (void * list)
Return a list of smsgs to the pool.
Definition at line 256 of file stream.c.
References StreamMsg_::next, StreamMsg_::prev, SCLogDebug, and StreamMsgReturnToPool().
Referenced by SigMatchSignatures().
void StreamMsgReturnToPool (StreamMsg * s)
Definition at line 109 of file stream.c.
References PoolReturn(), SCLogDebug, SCMutexLock, and SCMutexUnlock.
Referenced by StreamMsgReturnListToPool(), StreamTcpSessionClear(), and StreamTcpSessionPoolCleanup().
int StreamSegmentForEach (const Packet * p, uint8_t flag, StreamSegmentCallback CallbackFunc, void * data)
Run callback for all segments.
Returns
-1 in case of error, the number of segment in case of success
Definition at line 274 of file stream.c.
References Packet_::proto, SC_ERR_UNKNOWN_PROTOCOL, SCLogWarning, and StreamTcpSegmentForEach().