suricata: src/stream-tcp-reassemble.c File Reference
stream-tcp-reassemble.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "debug.h"
#include "detect.h"
#include "flow.h"
#include "threads.h"
#include "conf.h"
#include "flow-util.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-pool.h"
#include "util-unittest.h"
#include "util-print.h"
#include "util-host-os-info.h"
#include "util-unittest-helper.h"
#include "util-byte.h"
#include "stream-tcp.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp-inline.h"
#include "stream-tcp-util.h"
#include "stream.h"
#include "util-debug.h"
#include "app-layer-protos.h"
#include "app-layer.h"
#include "app-layer-events.h"
#include "detect-engine-state.h"
#include "util-profiling.h"
Data Structures
struct SegmentSizes_
struct ReassembleData_
struct ReassembleRawData_
Macros
#define PSEUDO_PACKET_PAYLOAD_SIZE 65416 /* 64 Kb minus max IP and TCP header */
#define StreamTcpAppLayerSegmentProcessed(ssn, stream, segment)
see if app layer is done with a segment
Typedefs
typedef struct SegmentSizes_ SegmentSizes
typedef struct ReassembleData_ ReassembleData
typedef struct ReassembleRawData_ ReassembleRawData
Functions
SC_ATOMIC_DECLARE (uint64_t, ra_memuse)
void StreamTcpSegmentDataReplace (TcpSegment *dst_seg, TcpSegment *src_seg, uint32_t start_point, uint16_t len)
Function to replace the data from a specific point up to given length.
void StreamTcpSegmentDataCopy (TcpSegment *dst_seg, TcpSegment *src_seg)
Function to copy the data from src_seg to dst_seg.
TcpSegment * StreamTcpGetSegment (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, uint16_t len)
Function to get the segment of required length from the pool.
void StreamTcpCreateTestPacket (uint8_t *, uint8_t, uint8_t, uint8_t)
void StreamTcpReassemblePseudoPacketCreate (TcpStream *, Packet *, PacketQueue *)
void StreamTcpReassembleConfigEnableOverlapCheck (void)
void StreamTcpReassembleIncrMemuse (uint64_t size)
Function to Increment the memory usage counter for the TCP reassembly segments.
void StreamTcpReassembleDecrMemuse (uint64_t size)
Function to Decrease the memory usage counter for the TCP reassembly segments.
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
int StreamTcpReassembleCheckMemcap (uint32_t size)
Function to Check the reassembly memory usage counter against the allowed max memory usgae for TCP segments.
void * TcpSegmentPoolAlloc ()
alloc a tcp segment pool entry
int TcpSegmentPoolInit (void *data, void *payload_len)
void TcpSegmentPoolCleanup (void *ptr)
clean up a tcp segment pool entry
void StreamTcpSegmentReturntoPool (TcpSegment *seg)
Function to return the segment back to the pool.
void StreamTcpReturnStreamSegments (TcpStream *stream)
return all segments in this stream into the pool(s)
void StreamTcpDisableAppLayer (Flow *f)
int StreamTcpAppLayerIsDisabled (Flow *f)
int StreamTcpReassemblyConfig (char quiet)
int StreamTcpReassembleInit (char quiet)
void StreamTcpReassembleFree (char quiet)
TcpReassemblyThreadCtx * StreamTcpReassembleInitThreadCtx (ThreadVars *tv)
void StreamTcpReassembleFreeThreadCtx (TcpReassemblyThreadCtx *ra_ctx)
void PrintList2 (TcpSegment *seg)
void PrintList (TcpSegment *seg)
int StreamTcpReassembleInsertSegment (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpStream *stream, TcpSegment *seg, Packet *p)
int StreamTcpReassembleDepthReached (Packet *p)
check if stream in pkt direction has depth reached
int StreamTcpReassembleHandleSegmentHandleData (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, Packet *p)
Insert a packets TCP data into the stream reassembly engine.
void StreamTcpPruneSession (Flow *f, uint8_t flags)
Remove idle TcpSegments from TcpSession.
int DoHandleGap (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, TcpSegment *seg, ReassembleData *rd, Packet *p, uint32_t next_seq)
int StreamTcpReassembleAppLayer (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, Packet *p)
Update the stream reassembly upon receiving an ACK packet.
int StreamTcpReassembleHandleSegmentUpdateACK (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, Packet *p)
update app layer and raw reassembly
int StreamTcpReassembleHandleSegment (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, Packet *p, PacketQueue *pq)
void StreamTcpReassembleTriggerRawReassembly (TcpSession *ssn)
Trigger RAW stream reassembly.
void StreamTcpReassembleRegisterTests (void)
The Function Register the Unit tests to test the reassembly engine for various OS policies.
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Reference: Judy Novak, Steve Sturges: Target-Based TCP Stream Reassembly August, 2007
Definition in file stream-tcp-reassemble.c.
Macro Definition Documentation
#define PSEUDO_PACKET_PAYLOAD_SIZE 65416 /* 64 Kb minus max IP and TCP header */
Definition at line 66 of file stream-tcp-reassemble.c.
#define StreamTcpAppLayerSegmentProcessed (ssn, stream, segment)
Value:
((((ssn)->flags & STREAMTCP_FLAG_APP_LAYER_DISABLED) || \
       ( (stream)->flags & STREAMTCP_STREAM_FLAG_GAP ) || \
       ( (segment)->flags & SEGMENTTCP_FLAG_APPLAYER_PROCESSED ) ? 1 :0 ))
see if app layer is done with a segment
Return values
1 app layer is done with this segment
0 not done yet
Definition at line 2084 of file stream-tcp-reassemble.c.
Referenced by StreamTcpReassembleAppLayer().
Typedef Documentation
typedef struct ReassembleData_ ReassembleData
typedef struct ReassembleRawData_ ReassembleRawData
typedef struct SegmentSizes_ SegmentSizes
Function Documentation
int DoHandleGap (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, TcpSegment * seg, ReassembleData * rd, Packet * p, uint32_t next_seq)
Definition at line 2561 of file stream-tcp-reassemble.c.
References TcpReassemblyThreadCtx_::app_tctx, AppLayerHandleTCPData(), TcpReassemblyThreadCtx_::counter_tcp_reass_gap, ReassembleData_::data, ReassembleData_::data_len, ReassembleData_::data_sent, TcpStream_::flags, Packet_::flow, TcpStream_::last_ack, ReassembleData_::ra_base_seq, SCLogDebug, TcpSegment_::seq, SEQ_GT, TcpSession_::state, StatsIncr(), STREAM_GAP, STREAM_REASSEMBLY_SEQ_GAP, STREAMTCP_STREAM_FLAG_GAP, StreamTcpInlineMode(), StreamTcpSetEvent, TCP_CLOSED, and unlikely.
Referenced by StreamTcpReassembleAppLayer().
void PrintList (TcpSegment * seg)
Definition at line 646 of file stream-tcp-reassemble.c.
References TcpSegment_::flags, TcpSegment_::next, TcpSegment_::payload_len, TcpSegment_::prev, PrintList2(), SCLogDebug, TcpSegment_::seq, and SEQ_LT.
Referenced by StreamTcpReassembleAppLayer(), and StreamTcpReassembleInsertSegment().
void PrintList2 (TcpSegment * seg)
Definition at line 598 of file stream-tcp-reassemble.c.
References TcpSegment_::next, TcpSegment_::payload_len, TcpSegment_::prev, SCLogDebug, TcpSegment_::seq, and SEQ_LT.
Referenced by PrintList().
SC_ATOMIC_DECLARE (uint64_t , ra_memuse)
int StreamTcpAppLayerIsDisabled (Flow * f)
Parameters
f locked flow
Definition at line 293 of file stream-tcp-reassemble.c.
References TcpSession_::flags, Flow_::proto, Flow_::protoctx, and STREAMTCP_FLAG_APP_LAYER_DISABLED.
void StreamTcpCreateTestPacket (uint8_t * , uint8_t , uint8_t , uint8_t)
void StreamTcpDisableAppLayer (Flow * f)
Parameters
f locked flow
Definition at line 281 of file stream-tcp-reassemble.c.
References TcpSession_::client, Flow_::protoctx, TcpSession_::server, StreamTcpDisableAppLayerReassembly, and StreamTcpSetStreamFlagAppProtoDetectionCompleted.
Referenced by AppLayerParserParse(), and StreamTcpPacket().
TcpSegment * StreamTcpGetSegment (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, uint16_t len)
Function to get the segment of required length from the pool.
Parameters
len Length which tells the required size of needed segment.
Return values
seg Segment from the pool or NULL
Definition at line 3611 of file stream-tcp-reassemble.c.
References TcpReassemblyThreadCtx_::counter_tcp_segment_memcap, TcpSegment_::flags, len, TcpSegment_::next, PoolGet(), TcpSegment_::prev, SCLogDebug, SCMutexLock, SCMutexUnlock, TcpStreamCnf_::segment_init_flags, StatsIncr(), and stream_config.
Referenced by StreamTcpReassembleHandleSegmentHandleData().
void StreamTcpPruneSession (Flow * f, uint8_t flags)
Remove idle TcpSegments from TcpSession.
Parameters
f flow
flags direction flags
Definition at line 2473 of file stream-tcp-reassemble.c.
References TcpSession_::client, TcpSegment_::flags, TcpStream_::last_ack, TcpSegment_::next, TcpSegment_::payload_len, Flow_::protoctx, SCLogDebug, TcpStream_::seg_list, TcpSegment_::seq, SEQ_LT, TcpSession_::server, STREAM_TOCLIENT, STREAM_TOSERVER, and StreamTcpSegmentReturntoPool().
Referenced by TmqhOutputPacketpool().
int StreamTcpReassembleAppLayer (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, Packet * p)
Update the stream reassembly upon receiving an ACK packet.
Stream is in the opposite direction of the packet, as the ACK-packet is ACK'ing the stream.
One of the utilities call by this function AppLayerHandleTCPData(), has a feature where it will call this very same function for the stream opposing the stream it is called with. This shouldn't cause any issues, since processing of each stream is independent of the other stream.
Todo:
this function is too long, we need to break it up. It needs it BAD
Definition at line 2878 of file stream-tcp-reassemble.c.
References TcpReassemblyThreadCtx_::app_tctx, AppLayerHandleTCPData(), BUG_ON, TcpReassemblyThreadCtx_::counter_tcp_reass_gap, ReassembleData_::data, ReassembleData_::data_len, ReassembleData_::data_sent, DoHandleGap(), FALSE, TcpSegment_::flags, TcpStream_::flags, TcpSession_::flags, Packet_::flags, Packet_::flow, TcpStream_::isn, TcpStream_::last_ack, TcpSegment_::next, ReassembleData_::partial, TcpSegment_::payload_len, Packet_::pcap_cnt, PKT_PSEUDO_STREAM_END, PrintList(), TcpStream_::ra_app_base_seq, ReassembleData_::ra_base_seq, SCEnter, SCLogDebug, SCReturnInt, TcpStream_::seg_list, TcpStream_::seg_list_tail, SEGMENTTCP_FLAG_APPLAYER_PROCESSED, TcpSegment_::seq, SEQ_GEQ, SEQ_GT, SEQ_LT, TcpSession_::state, StatsIncr(), STREAM_GAP, STREAM_REASSEMBLY_SEQ_GAP, STREAMTCP_FLAG_APP_LAYER_DISABLED, STREAMTCP_STREAM_FLAG_GAP, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, StreamTcpAppLayerSegmentProcessed, StreamTcpInlineMode(), StreamTcpIsSetStreamFlagAppProtoDetectionCompleted, StreamTcpSegmentReturntoPool(), StreamTcpSetEvent, TCP_CLOSING, TCP_ESTABLISHED, TCP_FIN_WAIT2, and TcpStream_::window.
Referenced by AppLayerHandleTCPData(), StreamTcpReassembleHandleSegment(), and StreamTcpReassembleHandleSegmentUpdateACK().
int StreamTcpReassembleCheckMemcap (uint32_t size)
Function to Check the reassembly memory usage counter against the allowed max memory usgae for TCP segments.
Parameters
size Size of the TCP segment and its payload length memory allocated
Return values
1 if in bounds
0 if not in bounds
Definition at line 152 of file stream-tcp-reassemble.c.
References TcpStreamCnf_::reassembly_memcap, SC_ATOMIC_GET, and stream_config.
Referenced by StreamMsgPoolAlloc(), StreamMsgQueueGetNew(), TcpSegmentPoolAlloc(), and TcpSegmentPoolInit().
void StreamTcpReassembleConfigEnableOverlapCheck (void)
Definition at line 109 of file stream-tcp-reassemble.c.
Referenced by DetectEngineEventParse().
void StreamTcpReassembleDecrMemuse (uint64_t size)
Function to Decrease the memory usage counter for the TCP reassembly segments.
Parameters
size Size of the TCP segment and its payload length memory allocated
Definition at line 132 of file stream-tcp-reassemble.c.
References SC_ATOMIC_SUB.
Referenced by StreamMsgPoolFree(), StreamMsgQueueFree(), and TcpSegmentPoolCleanup().
int StreamTcpReassembleDepthReached (Packet * p)
check if stream in pkt direction has depth reached
Parameters
p packet with LOCKED flow
Return values
1 stream has depth reached
0 stream does not have depth reached
Definition at line 1744 of file stream-tcp-reassemble.c.
References TcpSession_::client, TcpStream_::flags, Packet_::flow, FLOW_PKT_TOSERVER, Packet_::flowflags, Flow_::protoctx, TcpSession_::server, and STREAMTCP_STREAM_FLAG_DEPTH_REACHED.
void StreamTcpReassembleFree (char quiet)
Definition at line 527 of file stream-tcp-reassemble.c.
References FALSE, PoolFree(), PoolPrintSaturation(), SCFree, SCLogDebug, SCLogInfo, SCMutexDestroy, SCMutexLock, SCMutexUnlock, and StreamMsgQueuesDeinit().
Referenced by StreamTcpFreeConfig().
void StreamTcpReassembleFreeThreadCtx (TcpReassemblyThreadCtx * ra_ctx)
Definition at line 586 of file stream-tcp-reassemble.c.
References TcpReassemblyThreadCtx_::app_tctx, AppLayerDestroyCtxThread(), SCEnter, SCFree, SCLogDebug, and SCReturn.
Referenced by StreamTcpThreadDeinit().
int StreamTcpReassembleHandleSegment (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, Packet * p, PacketQueue * pq)
Definition at line 3406 of file stream-tcp-reassemble.c.
References TcpSession_::client, TcpStream_::flags, Packet_::flags, Packet_::payload_len, PKT_STREAM_ADD, SCEnter, SCLogDebug, SCReturnInt, TcpSession_::server, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, StreamTcpInlineMode(), StreamTcpReassembleAppLayer(), StreamTcpReassembleHandleSegmentHandleData(), and StreamTcpReassembleHandleSegmentUpdateACK().
Referenced by StreamTcpPacket().
int StreamTcpReassembleHandleSegmentHandleData (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, Packet * p)
Insert a packets TCP data into the stream reassembly engine.
Return values
0 good segment, as far as we checked.
-1 badness, reason to drop in inline mode
If the retval is 0 the segment is inserted correctly, or overlap is handled, or it wasn't added because of reassembly depth.
Definition at line 1883 of file stream-tcp-reassemble.c.
References Packet_::app_layer_events, APPLAYER_PROTO_DETECTION_SKIPPED, AppLayerDecoderEventsSetEventRaw(), BUG_ON, TcpReassemblyThreadCtx_::counter_tcp_stream_depth, TcpSession_::data_first_seen_dir, TcpSegment_::flags, TcpStream_::flags, TcpSession_::flags, FLOW_PKT_TOSERVER, Packet_::flowflags, TcpSegment_::payload, Packet_::payload, TcpSegment_::payload_len, Packet_::payload_len, SCEnter, SCLogDebug, SCReturnInt, TcpStream_::seg_list, SEGMENTTCP_FLAG_APPLAYER_PROCESSED, SEGMENTTCP_FLAG_RAW_PROCESSED, TcpSegment_::seq, StatsIncr(), STREAM_REASSEMBLY_NO_SEGMENT, STREAM_TOCLIENT, STREAM_TOSERVER, STREAMTCP_FLAG_APP_LAYER_DISABLED, STREAMTCP_STREAM_FLAG_APPPROTO_DETECTION_SKIPPED, STREAMTCP_STREAM_FLAG_DEPTH_REACHED, STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, StreamTcpGetSegment(), StreamTcpReassembleInsertSegment(), StreamTcpSetEvent, and TCP_GET_SEQ.
Referenced by StreamTcpReassembleHandleSegment().
int StreamTcpReassembleHandleSegmentUpdateACK (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, Packet * p)
update app layer and raw reassembly
Return values
r 0 on success, -1 on error
Definition at line 3387 of file stream-tcp-reassemble.c.
References SCEnter, SCLogDebug, SCReturnInt, TcpStream_::seg_list, StreamTcpInlineMode(), and StreamTcpReassembleAppLayer().
Referenced by StreamTcpReassembleHandleSegment().
void StreamTcpReassembleIncrMemuse (uint64_t size)
Function to Increment the memory usage counter for the TCP reassembly segments.
Parameters
size Size of the TCP segment and its payload length memory allocated
Definition at line 120 of file stream-tcp-reassemble.c.
References SC_ATOMIC_ADD.
Referenced by StreamMsgPoolAlloc(), StreamMsgQueueGetNew(), and TcpSegmentPoolInit().
int StreamTcpReassembleInit (char quiet)
Definition at line 505 of file stream-tcp-reassemble.c.
References SC_ATOMIC_INIT, SCMutexInit, StatsRegisterGlobalCounter(), StreamTcpReassembleMemuseGlobalCounter(), and StreamTcpReassemblyConfig().
Referenced by StreamTcpInitConfig().
TcpReassemblyThreadCtx* StreamTcpReassembleInitThreadCtx (ThreadVars * tv)
Definition at line 572 of file stream-tcp-reassemble.c.
References TcpReassemblyThreadCtx_::app_tctx, AppLayerGetCtxThread(), SCEnter, SCMalloc, SCReturnPtr, and unlikely.
Referenced by StreamTcpThreadInit().
int StreamTcpReassembleInsertSegment (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpStream * stream, TcpSegment * seg, Packet * p)
Definition at line 729 of file stream-tcp-reassemble.c.
References FALSE, TcpStream_::last_ack, TcpSegment_::next, TcpStream_::os_policy, TcpSegment_::payload_len, Packet_::payload_len, TcpSegment_::prev, PrintList(), TcpStream_::ra_app_base_seq, SCEnter, SCLogDebug, SCReturnInt, TcpStream_::seg_list, TcpStream_::seg_list_tail, TcpSegment_::seq, SEQ_EQ, SEQ_GEQ, SEQ_GT, SEQ_LEQ, SEQ_LT, STREAM_REASSEMBLY_SEGMENT_BEFORE_BASE_SEQ, StreamTcpSegmentReturntoPool(), StreamTcpSetEvent, StreamTcpSetOSPolicy(), TCP_GET_SEQ, and TRUE.
Referenced by StreamTcpReassembleHandleSegmentHandleData().
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
Definition at line 138 of file stream-tcp-reassemble.c.
References SC_ATOMIC_GET.
Referenced by StreamTcpReassembleInit().
void StreamTcpReassemblePseudoPacketCreate (TcpStream * , Packet * , PacketQueue *)
void StreamTcpReassembleRegisterTests (void)
The Function Register the Unit tests to test the reassembly engine for various OS policies.
Definition at line 8689 of file stream-tcp-reassemble.c.
References StreamTcpInlineRegisterTests(), and StreamTcpUtilRegisterTests().
Referenced by StreamTcpRegisterTests().
void StreamTcpReassembleTriggerRawReassembly (TcpSession * ssn)
Trigger RAW stream reassembly.
Used by AppLayerTriggerRawStreamReassembly to trigger RAW stream reassembly from the applayer, for example upon completion of a HTTP request.
Works by setting a flag in the TcpSession that is unset as soon as it's checked. Since everything happens when operating under a single lock period, no side effects are expected.
Parameters
ssn TcpSession
Definition at line 3662 of file stream-tcp-reassemble.c.
References BUG_ON, TcpSession_::flags, SCLogDebug, and STREAMTCP_FLAG_TRIGGER_RAW_REASSEMBLY.
Referenced by AppLayerParserTriggerRawStreamReassembly().
int StreamTcpReassemblyConfig (char quiet)
Definition at line 316 of file stream-tcp-reassemble.c.
References ByteExtractStringUint16(), ByteExtractStringUint32(), ConfGetInt(), ConfGetNode(), ConfNodeLookupChild(), next, SegmentSizes_::pktsize, PoolInit(), SegmentSizes_::prealloc, SC_ERR_INITIALIZATION, SC_ERR_INVALID_ARGUMENT, SC_ERR_MEM_ALLOC, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, SCMutex, SCMutexInit, SCMutexLock, SCMutexUnlock, stream_config, StreamMsgQueuesInit(), TAILQ_FOREACH, TcpSegmentPoolAlloc(), TcpSegmentPoolCleanup(), TcpSegmentPoolInit(), ConfNode_::val, and TcpStreamCnf_::zero_copy_size.
Referenced by StreamTcpReassembleInit().
void StreamTcpReturnStreamSegments (TcpStream * stream)
return all segments in this stream into the pool(s)
Parameters
stream the stream to cleanup
Definition at line 262 of file stream-tcp-reassemble.c.
References TcpSegment_::next, TcpStream_::seg_list, TcpStream_::seg_list_tail, and StreamTcpSegmentReturntoPool().
Referenced by StreamTcpSessionClear(), StreamTcpSessionPktFree(), and StreamTcpSessionPoolCleanup().
void StreamTcpSegmentDataCopy (TcpSegment * dst_seg, TcpSegment * src_seg)
Function to copy the data from src_seg to dst_seg.
Parameters
dst_seg Destination segment for copying the contents
src_seg Source segment to copy its contents
Todo:
VJ wouldn't a memcpy be more appropriate here?
Warning
Both segments need to be properly initialized.
Definition at line 3573 of file stream-tcp-reassemble.c.
References TcpSegment_::payload, TcpSegment_::payload_len, SCLogDebug, TcpSegment_::seq, SEQ_GT, and SEQ_LT.
void StreamTcpSegmentDataReplace (TcpSegment * dst_seg, TcpSegment * src_seg, uint32_t start_point, uint16_t len)
Function to replace the data from a specific point up to given length.
Parameters
dst_seg Destination segment to replace the data
src_seg Source segment of which data is to be written to destination
start_point Starting point to replace the data onwards
len Length up to which data is need to be replaced
Todo:
VJ We can remove the abort()s later.
VJ Why not memcpy?
Definition at line 3471 of file stream-tcp-reassemble.c.
References BUG_ON, TcpSegment_::payload, TcpSegment_::payload_len, SCLogDebug, SCLogDebugEnabled(), TcpSegment_::seq, SEQ_GT, and SEQ_LT.
void StreamTcpSegmentReturntoPool (TcpSegment * seg)
Function to return the segment back to the pool.
Parameters
seg Segment which will be returned back to the pool.
Definition at line 235 of file stream-tcp-reassemble.c.
References TcpSegment_::next, TcpSegment_::pool_size, PoolReturn(), TcpSegment_::prev, SCLogDebug, SCMutexLock, and SCMutexUnlock.
Referenced by StreamTcpPruneSession(), StreamTcpReassembleAppLayer(), StreamTcpReassembleInsertSegment(), and StreamTcpReturnStreamSegments().
void* TcpSegmentPoolAlloc ()
alloc a tcp segment pool entry
Definition at line 161 of file stream-tcp-reassemble.c.
References SCMalloc, StreamTcpReassembleCheckMemcap(), and unlikely.
Referenced by StreamTcpReassemblyConfig().
void TcpSegmentPoolCleanup (void * ptr)
clean up a tcp segment pool entry
Definition at line 209 of file stream-tcp-reassemble.c.
References TcpSegment_::payload, TcpSegment_::pool_size, SCFree, SCLogDebug, SCMutexLock, SCMutexUnlock, and StreamTcpReassembleDecrMemuse().
Referenced by StreamTcpReassemblyConfig().
int TcpSegmentPoolInit (void * data, void * payload_len)
Definition at line 175 of file stream-tcp-reassemble.c.
References TcpSegment_::payload, TcpSegment_::payload_len, TcpSegment_::pool_size, SCLogDebug, SCMalloc, SCMutexLock, SCMutexUnlock, StreamTcpReassembleCheckMemcap(), and StreamTcpReassembleIncrMemuse().
Referenced by StreamTcpReassemblyConfig().