suricata: src/stream-tcp.c File Reference
stream-tcp.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "debug.h"
#include "detect.h"
#include "flow.h"
#include "flow-util.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-pool.h"
#include "util-pool-thread.h"
#include "util-checksum.h"
#include "util-unittest.h"
#include "util-print.h"
#include "util-debug.h"
#include "util-device.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream-tcp-inline.h"
#include "stream-tcp-sack.h"
#include "stream-tcp-util.h"
#include "stream.h"
#include "pkt-var.h"
#include "host.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-protos.h"
#include "app-layer-htp-mem.h"
#include "util-host-os-info.h"
#include "util-privs.h"
#include "util-profiling.h"
#include "util-misc.h"
#include "util-validate.h"
#include "util-runmodes.h"
#include "source-pcap-file.h"
Macros
#define STREAMTCP_DEFAULT_PREALLOC 2048
#define STREAMTCP_DEFAULT_MEMCAP (32 * 1024 * 1024) /* 32mb */
#define STREAMTCP_DEFAULT_REASSEMBLY_MEMCAP (64 * 1024 * 1024) /* 64mb */
#define STREAMTCP_DEFAULT_TOSERVER_CHUNK_SIZE 2560
#define STREAMTCP_DEFAULT_TOCLIENT_CHUNK_SIZE 2560
#define STREAMTCP_DEFAULT_MAX_SYNACK_QUEUED 5
#define STREAMTCP_NEW_TIMEOUT 60
#define STREAMTCP_EST_TIMEOUT 3600
#define STREAMTCP_CLOSED_TIMEOUT 120
#define STREAMTCP_EMERG_NEW_TIMEOUT 10
#define STREAMTCP_EMERG_EST_TIMEOUT 300
#define STREAMTCP_EMERG_CLOSED_TIMEOUT 20
#define StreamTcpUpdateLastAck(ssn, stream, ack)
macro to update last_ack only if the new value is higher
#define StreamTcpUpdateNextWin(ssn, stream, win)
macro to update next_win only if the new value is higher
#define PSEUDO_PKT_SET_IPV4HDR(nipv4h, ipv4h)
#define PSEUDO_PKT_SET_IPV6HDR(nipv6h, ipv6h)
#define PSEUDO_PKT_SET_TCPHDR(ntcph, tcph)
Functions
TmEcode StreamTcp (ThreadVars *, Packet *, void *, PacketQueue *, PacketQueue *)
TmEcode StreamTcpThreadInit (ThreadVars *, void *, void **)
TmEcode StreamTcpThreadDeinit (ThreadVars *, void *)
void StreamTcpExitPrintStats (ThreadVars *, void *)
void StreamTcpRegisterTests (void)
void StreamTcpReturnStreamSegments (TcpStream *)
return all segments in this stream into the pool(s)
void StreamTcpInitConfig (char quiet)
To initialize the stream global configuration data.
int StreamTcpGetFlowState (void *)
void StreamTcpSetOSPolicy (TcpStream *stream, Packet *p)
Function to set the OS policy for the given stream based on the destination of the received packet.
void StreamTcpPseudoPacketCreateStreamEndPacket (ThreadVars *tv, StreamTcpThread *stt, Packet *p, TcpSession *ssn, PacketQueue *pq)
Create a pseudo packet injected into the engine to signal the opposing direction of this stream to wrap up stream reassembly.
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
SC_ATOMIC_DECLARE (uint64_t, st_memuse)
void TmModuleStreamTcpRegister (void)
void StreamTcpIncrMemuse (uint64_t size)
void StreamTcpDecrMemuse (uint64_t size)
uint64_t StreamTcpMemuseCounter (void)
int StreamTcpCheckMemcap (uint64_t size)
Check if alloc'ing "size" would mean we're over memcap.
void StreamTcpSessionClear (void *ssnptr)
Function to return the stream back to the pool. It returns the segments in the stream to the segment pool.
void StreamTcpSessionPktFree (Packet *p)
Function to return the stream segments back to the pool.
void * StreamTcpSessionPoolAlloc ()
Stream alloc function for the Pool.
int StreamTcpSessionPoolInit (void *data, void *initdata)
void StreamTcpSessionPoolCleanup (void *s)
Pool free function.
void StreamTcpFreeConfig (char quiet)
TcpSession * StreamTcpNewSession (Packet *p, int id)
The function is used to to fetch a TCP session from the ssn_pool, when a TCP SYN is received.
uint32_t StreamTcpGetStreamSize (TcpStream *stream)
get the size of a stream
TcpStateQueue * StreamTcp3whsFindSynAckBySynAck (TcpSession *ssn, Packet *p)
int StreamTcp3whsQueueSynAck (TcpSession *ssn, Packet *p)
TcpStateQueue * StreamTcp3whsFindSynAckByAck (TcpSession *ssn, Packet *p)
int StreamTcpPacket (ThreadVars *tv, Packet *p, StreamTcpThread *stt, PacketQueue *pq)
int TcpSessionReuseDoneEnough (const Packet *p, const Flow *f, const TcpSession *ssn)
Check if SSN is done enough for reuse.
int TcpSessionPacketSsnReuse (const Packet *p, const Flow *f, const void *tcp_ssn)
void StreamTcpSetSessionNoReassemblyFlag (TcpSession *ssn, char direction)
Set the No reassembly flag for the given direction in given TCP session.
void StreamTcpSetDisableRawReassemblyFlag (TcpSession *ssn, char direction)
Set the No reassembly flag for the given direction in given TCP session.
Packet * StreamTcpPseudoSetup (Packet *parent, uint8_t *pkt, uint32_t len)
Function to fetch a packet from the packet allocation queue for creation of the pseudo packet from the reassembled stream.
int StreamTcpSegmentForEach (const Packet *p, uint8_t flag, StreamSegmentCallback CallbackFunc, void *data)
Run callback function on each TCP segment.
Variables
int stream_inline = 0
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
TCP stream tracking and reassembly engine.
Todo:
4WHS: what if after the 2nd SYN we turn out to be normal 3WHS anyway?
Definition in file stream-tcp.c.
Macro Definition Documentation
#define PSEUDO_PKT_SET_IPV4HDR (nipv4h, ipv4h)
Value:
do { \
        IPV4_SET_RAW_VER(nipv4h, IPV4_GET_RAW_VER(ipv4h)); \
        IPV4_SET_RAW_HLEN(nipv4h, IPV4_GET_RAW_HLEN(ipv4h)); \
        IPV4_SET_RAW_IPLEN(nipv4h, IPV4_GET_RAW_IPLEN(ipv4h)); \
        IPV4_SET_RAW_IPTOS(nipv4h, IPV4_GET_RAW_IPTOS(ipv4h)); \
        IPV4_SET_RAW_IPPROTO(nipv4h, IPV4_GET_RAW_IPPROTO(ipv4h)); \
        (nipv4h)->s_ip_src = IPV4_GET_RAW_IPDST(ipv4h); \
        (nipv4h)->s_ip_dst = IPV4_GET_RAW_IPSRC(ipv4h); \
    } while (0)
Definition at line 5724 of file stream-tcp.c.
#define PSEUDO_PKT_SET_IPV6HDR (nipv6h, ipv6h)
Value:
do { \
        (nipv6h)->s_ip6_src[0] = (ipv6h)->s_ip6_dst[0]; \
        (nipv6h)->s_ip6_src[1] = (ipv6h)->s_ip6_dst[1]; \
        (nipv6h)->s_ip6_src[2] = (ipv6h)->s_ip6_dst[2]; \
        (nipv6h)->s_ip6_src[3] = (ipv6h)->s_ip6_dst[3]; \
        (nipv6h)->s_ip6_dst[0] = (ipv6h)->s_ip6_src[0]; \
        (nipv6h)->s_ip6_dst[1] = (ipv6h)->s_ip6_src[1]; \
        (nipv6h)->s_ip6_dst[2] = (ipv6h)->s_ip6_src[2]; \
        (nipv6h)->s_ip6_dst[3] = (ipv6h)->s_ip6_src[3]; \
        IPV6_SET_RAW_NH(nipv6h, IPV6_GET_RAW_NH(ipv6h));    \
    } while (0)
Definition at line 5734 of file stream-tcp.c.
#define PSEUDO_PKT_SET_TCPHDR (ntcph, tcph)
Value:
do { \
        COPY_PORT((tcph)->th_dport, (ntcph)->th_sport); \
        COPY_PORT((tcph)->th_sport, (ntcph)->th_dport); \
        (ntcph)->th_seq = (tcph)->th_ack; \
        (ntcph)->th_ack = (tcph)->th_seq; \
    } while (0)
Definition at line 5746 of file stream-tcp.c.
#define STREAMTCP_CLOSED_TIMEOUT 120
Definition at line 90 of file stream-tcp.c.
#define STREAMTCP_DEFAULT_MAX_SYNACK_QUEUED 5
Definition at line 86 of file stream-tcp.c.
Referenced by StreamTcpInitConfig().
#define STREAMTCP_DEFAULT_MEMCAP (32 * 1024 * 1024) /* 32mb */
Definition at line 82 of file stream-tcp.c.
Referenced by StreamTcpInitConfig().
#define STREAMTCP_DEFAULT_PREALLOC 2048
Definition at line 81 of file stream-tcp.c.
Referenced by StreamTcpInitConfig().
#define STREAMTCP_DEFAULT_REASSEMBLY_MEMCAP (64 * 1024 * 1024) /* 64mb */
Definition at line 83 of file stream-tcp.c.
Referenced by StreamTcpInitConfig().
#define STREAMTCP_DEFAULT_TOCLIENT_CHUNK_SIZE 2560
Definition at line 85 of file stream-tcp.c.
Referenced by StreamTcpInitConfig().
#define STREAMTCP_DEFAULT_TOSERVER_CHUNK_SIZE 2560
Definition at line 84 of file stream-tcp.c.
Referenced by StreamTcpInitConfig().
#define STREAMTCP_EMERG_CLOSED_TIMEOUT 20
Definition at line 94 of file stream-tcp.c.
#define STREAMTCP_EMERG_EST_TIMEOUT 300
Definition at line 93 of file stream-tcp.c.
#define STREAMTCP_EMERG_NEW_TIMEOUT 10
Definition at line 92 of file stream-tcp.c.
#define STREAMTCP_EST_TIMEOUT 3600
Definition at line 89 of file stream-tcp.c.
#define STREAMTCP_NEW_TIMEOUT 60
Definition at line 88 of file stream-tcp.c.
#define StreamTcpUpdateLastAck (ssn, stream, ack)
Value:
{ \
    if (SEQ_GT((ack), (stream)->last_ack)) \
    { \
        SCLogDebug("ssn %p: last_ack set to %"PRIu32", moved %u forward", (ssn), (ack), (ack) - (stream)->last_ack); \
        if ((SEQ_LEQ((stream)->last_ack, (stream)->next_seq) && SEQ_GT((ack),(stream)->next_seq))) { \
            SCLogDebug("last_ack just passed next_seq: %u (was %u) > %u", (ack), (stream)->last_ack, (stream)->next_seq); \
        } else { \
            SCLogDebug("next_seq (%u) <> last_ack now %d", (stream)->next_seq, (int)(stream)->next_seq - (ack)); \
        }\
        (stream)->last_ack = (ack); \
        StreamTcpSackPruneList((stream)); \
    } else { \
        SCLogDebug("ssn %p: no update: ack %u, last_ack %"PRIu32", next_seq %u (state %u)", \
                    (ssn), (ack), (stream)->last_ack, (stream)->next_seq, (ssn)->state); \
    }\
}
macro to update last_ack only if the new value is higher
Parameters
ssn session
stream stream to update
ack ACK value to test and set
Definition at line 764 of file stream-tcp.c.
#define StreamTcpUpdateNextWin (ssn, stream, win)
Value:
{ \
    uint32_t sacked_size__ = StreamTcpSackedSize((stream)); \
    if (SEQ_GT(((win) + sacked_size__), (stream)->next_win)) { \
        (stream)->next_win = ((win) + sacked_size__); \
        SCLogDebug("ssn %p: next_win set to %"PRIu32, (ssn), (stream)->next_win); \
    } \
}
macro to update next_win only if the new value is higher
Parameters
ssn session
stream stream to update
win window value to test and set
Definition at line 788 of file stream-tcp.c.
Function Documentation
SC_ATOMIC_DECLARE (uint64_t , st_memuse)
TmEcode StreamTcp (ThreadVars * tv, Packet * p, void * data, PacketQueue * pq, PacketQueue * postpq)
Definition at line 5023 of file stream-tcp.c.
References TcpReassemblyThreadCtx_::app_tctx, StreamTcpThread_::counter_tcp_invalid_checksum, StreamTcpThread_::counter_tcp_no_flow, TcpStreamCnf_::flags, Packet_::flags, Packet_::flow, FLOW_PKT_TOSERVER_FIRST, Packet_::flowflags, FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, PKT_IGNORE_CHECKSUM, PKT_IS_TCP, PKT_PSEUDO_STREAM_END, StreamTcpThread_::pkts, StreamTcpThread_::ra_ctx, StreamTcpThread_::runmode_flow_stream_async, StatsIncr(), stream_config, STREAMTCP_INIT_FLAG_CHECKSUM_VALIDATION, StreamTcpPacket(), and TM_ECODE_OK.
Referenced by TmModuleStreamTcpRegister().
TcpStateQueue* StreamTcp3whsFindSynAckByAck (TcpSession * ssn, Packet * p)
Definition at line 1158 of file stream-tcp.c.
References TcpStateQueue_::ack, TcpStateQueue_::next, TcpSession_::queue, TcpStateQueue_::seq, TCP_GET_ACK, and TCP_GET_SEQ.
TcpStateQueue* StreamTcp3whsFindSynAckBySynAck (TcpSession * ssn, Packet * p)
Definition at line 1098 of file stream-tcp.c.
References TcpStateQueue_::ack, TcpStateQueue_::flags, TcpStateQueue_::next, TcpSession_::queue, TcpStateQueue_::seq, TcpStateQueue_::ts, TcpStateQueue_::win, and TcpStateQueue_::wscale.
Referenced by StreamTcp3whsQueueSynAck().
int StreamTcp3whsQueueSynAck (TcpSession * ssn, Packet * p)
Definition at line 1121 of file stream-tcp.c.
References TcpStreamCnf_::max_synack_queued, TcpStateQueue_::next, TcpSession_::queue, TcpSession_::queue_len, SCLogDebug, SCMalloc, STREAM_3WHS_SYNACK_FLOOD, stream_config, StreamTcp3whsFindSynAckBySynAck(), StreamTcpCheckMemcap(), StreamTcpIncrMemuse(), StreamTcpSetEvent, and unlikely.
int StreamTcpCheckMemcap (uint64_t size)
Check if alloc'ing "size" would mean we're over memcap.
Return values
1 if in bounds
0 if not in bounds
Definition at line 161 of file stream-tcp.c.
References TcpStreamCnf_::memcap, SC_ATOMIC_GET, and stream_config.
Referenced by StreamTcp3whsQueueSynAck(), and StreamTcpSessionPoolAlloc().
void StreamTcpDecrMemuse (uint64_t size)
Definition at line 143 of file stream-tcp.c.
References SC_ATOMIC_SUB.
Referenced by StreamTcpSessionClear(), and StreamTcpSessionPoolCleanup().
void StreamTcpExitPrintStats (ThreadVars * tv, void * data)
Definition at line 5161 of file stream-tcp.c.
References StreamTcpThread_::pkts, and SCLogInfo.
Referenced by TmModuleStreamTcpRegister().
void StreamTcpFreeConfig (char quiet)
Definition at line 620 of file stream-tcp.c.
References PoolThreadFree(), SCLogDebug, SCMutexDestroy, SCMutexLock, SCMutexUnlock, and StreamTcpReassembleFree().
Referenced by main().
int StreamTcpGetFlowState (void *)
uint32_t StreamTcpGetStreamSize (TcpStream * stream)
get the size of a stream
Note
this just calculates the diff between isn and last_ack and will not consider sequence wrap arounds (streams bigger than 4gb).
Return values
size stream size
Definition at line 752 of file stream-tcp.c.
References TcpStream_::isn, and TcpStream_::last_ack.
void StreamTcpIncrMemuse (uint64_t size)
Definition at line 137 of file stream-tcp.c.
References SC_ATOMIC_ADD.
Referenced by StreamTcp3whsQueueSynAck(), and StreamTcpSessionPoolInit().
void StreamTcpInitConfig (char quiet)
To initialize the stream global configuration data.
Parameters
quiet It tells the mode of operation, if it is TRUE nothing will be get printed.
Definition at line 346 of file stream-tcp.c.
References TcpStreamCnf_::async_oneside, ConfGet(), ConfGetBool(), ConfGetInt(), ConfGetNode(), EngineModeIsIPS(), TcpStreamCnf_::flags, FLOW_PKT_TOCLIENT, FLOW_PKT_TOSERVER, FlowSetProtoFreeFunc(), TcpStreamCnf_::max_synack_queued, TcpStreamCnf_::memcap, TcpStreamCnf_::midstream, ParseSizeStringU16(), ParseSizeStringU32(), ParseSizeStringU64(), PoolThreadInit(), TcpStreamCnf_::prealloc_sessions, TcpStreamCnf_::reassembly_depth, TcpStreamCnf_::reassembly_memcap, TcpStreamCnf_::reassembly_toclient_chunk_size, TcpStreamCnf_::reassembly_toserver_chunk_size, RunmodeIsUnittests(), SC_ATOMIC_INIT, SC_ERR_INVALID_VALUE, SC_ERR_SIZE_PARSE, SC_WARN_OPTION_OBSOLETE, SCLogDebug, SCLogError, SCLogInfo, SCLogWarning, SCMutexLock, SCMutexUnlock, TcpStreamCnf_::segment_init_flags, SEGMENTTCP_FLAG_RAW_PROCESSED, TcpStreamCnf_::ssn_init_flags, StatsRegisterGlobalCounter(), stream_config, stream_inline, StreamMsgQueueSetMinChunkLen(), STREAMTCP_DEFAULT_MAX_SYNACK_QUEUED, STREAMTCP_DEFAULT_MEMCAP, STREAMTCP_DEFAULT_PREALLOC, STREAMTCP_DEFAULT_REASSEMBLY_MEMCAP, STREAMTCP_DEFAULT_TOCLIENT_CHUNK_SIZE, STREAMTCP_DEFAULT_TOSERVER_CHUNK_SIZE, STREAMTCP_FLAG_DISABLE_RAW, STREAMTCP_INIT_FLAG_CHECKSUM_VALIDATION, StreamTcpMemuseCounter(), StreamTcpReassembleInit(), StreamTcpSessionClear(), StreamTcpSessionPoolAlloc(), StreamTcpSessionPoolCleanup(), StreamTcpSessionPoolInit(), and WarnInvalidConfEntry.
Referenced by main().
uint64_t StreamTcpMemuseCounter (void)
Definition at line 149 of file stream-tcp.c.
References SC_ATOMIC_GET.
Referenced by StreamTcpInitConfig().
TcpSession* StreamTcpNewSession (Packet * p, int id)
The function is used to to fetch a TCP session from the ssn_pool, when a TCP SYN is received.
Parameters
quiet Packet P, which has been recieved for the new TCP session.
Return values
TcpSession A new TCP session with field initilaized to 0/NULL.
Definition at line 642 of file stream-tcp.c.
References TcpSession_::client, TcpSession_::flags, Packet_::flow, PKT_IS_TOCLIENT, PKT_IS_TOSERVER, PoolThreadGetById(), Flow_::protoctx, SCLogDebug, SCMutexLock, SCMutexUnlock, TcpSession_::server, TcpStreamCnf_::ssn_init_flags, TcpSession_::state, stream_config, TcpStream_::tcp_flags, TCP_NONE, TcpSession_::tcp_packet_flags, and Packet_::tcph.
int StreamTcpPacket (ThreadVars * tv, Packet * p, StreamTcpThread * stt, PacketQueue * pq)
Definition at line 4451 of file stream-tcp.c.
References Flow_::alproto, TcpSession_::client, StreamTcpThread_::counter_tcp_rst, StreamTcpThread_::counter_tcp_syn, StreamTcpThread_::counter_tcp_synack, DEBUG_ASSERT_FLOW_LOCKED, DecodeSetNoPacketInspectionFlag, TcpStream_::flags, TcpSession_::flags, Packet_::flags, Packet_::flow, ThreadVars_::id, TcpStream_::last_ack, PacketQueue_::len, PACKET_DROP, PacketDequeue(), PacketEnqueue(), Packet_::pcap_cnt, PKT_IS_TOCLIENT, PKT_IS_TOSERVER, PKT_PSEUDO_STREAM_END, PKT_STREAM_EST, PKT_STREAM_MODIFIED, PKT_STREAM_NOPCAPLOG, Flow_::protoctx, StreamTcpThread_::pseudo_queue, StreamTcpThread_::ra_ctx, ReCalculateChecksum(), SCEnter, SCLogDebug, SCReturnInt, TcpSession_::server, TcpSession_::state, StatsIncr(), STREAM_PKT_BROKEN_ACK, STREAMTCP_FLAG_MIDSTREAM_SYNACK, STREAMTCP_STREAM_FLAG_DEPTH_REACHED, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, StreamTcpDisableAppLayer(), StreamTcpInlineMode(), StreamTcpReassembleHandleSegment(), StreamTcpSessionPktFree(), StreamTcpSetEvent, TCP_CLOSE_WAIT, TCP_CLOSED, TCP_CLOSING, TCP_ESTABLISHED, TCP_FIN_WAIT1, TCP_FIN_WAIT2, TcpStream_::tcp_flags, TCP_GET_ACK, TCP_LAST_ACK, TCP_NONE, TcpSession_::tcp_packet_flags, TCP_SYN_RECV, TCP_SYN_SENT, TCP_TIME_WAIT, Packet_::tcph, TH_ACK, TH_RST, TH_SYN, Flow_::thread_id, and unlikely.
Referenced by StreamTcp().
void StreamTcpPseudoPacketCreateStreamEndPacket (ThreadVars * tv, StreamTcpThread * stt, Packet * p, TcpSession * ssn, PacketQueue * pq)
Create a pseudo packet injected into the engine to signal the opposing direction of this stream to wrap up stream reassembly.
Parameters
p real packet
pq packet queue to store the new pseudo packet in
Definition at line 5856 of file stream-tcp.c.
References BUG_ON, TcpSession_::client, StreamTcpThread_::counter_tcp_pseudo, StreamTcpThread_::counter_tcp_pseudo_failed, DecodeSetNoPacketInspectionFlag, DecodeSetNoPayloadInspectionFlag, Packet_::flags, Packet_::flow, FLOW_PKT_TOCLIENT, FLOW_PKT_TOSERVER, Packet_::flowflags, GET_PKT_DATA, GET_PKT_LEN, PacketEnqueue(), PKT_HAS_FLOW, PKT_IS_TOCLIENT, PKT_IS_TOSERVER, PKT_NOPACKET_INSPECTION, PKT_NOPAYLOAD_INSPECTION, PKT_PSEUDO_STREAM_END, PKT_SET_SRC, PKT_SRC_STREAM_TCP_STREAM_END_PSEUDO, PKT_STREAM_EOF, PKT_STREAM_EST, SCEnter, SCLogDebug, SCReturn, TcpStream_::seg_list, TcpSession_::server, StatsIncr(), StreamTcpPseudoSetup(), Flow_::tenant_id, and Packet_::tenant_id.
Packet* StreamTcpPseudoSetup (Packet * parent, uint8_t * pkt, uint32_t len)
Function to fetch a packet from the packet allocation queue for creation of the pseudo packet from the reassembled stream.
Parameters
parent Pointer to the parent of the pseudo packet
pkt pointer to the raw packet of the parent
len length of the packet
Returns
upon success returns the pointer to the new pseudo packet otherwise NULL
Definition at line 5763 of file stream-tcp.c.
References Packet_::datalink, Packet_::flow, PacketCopyData(), PacketGetFromQueueOrAlloc(), Packet_::proto, Packet_::recursion_level, Packet_::root, SCEnter, SCReturnPtr, SET_TUNNEL_PKT, Packet_::ts, and TUNNEL_INCR_PKT_TPR.
Referenced by StreamTcpPseudoPacketCreateStreamEndPacket().
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
Definition at line 138 of file stream-tcp-reassemble.c.
References SC_ATOMIC_GET.
Referenced by StreamTcpReassembleInit().
void StreamTcpRegisterTests (void)
Definition at line 10738 of file stream-tcp.c.
References StreamTcpReassembleRegisterTests(), and StreamTcpSackRegisterTests().
Referenced by TmModuleStreamTcpRegister().
void StreamTcpReturnStreamSegments (TcpStream * stream)
return all segments in this stream into the pool(s)
Parameters
stream the stream to cleanup
Definition at line 262 of file stream-tcp-reassemble.c.
References TcpSegment_::next, TcpStream_::seg_list, TcpStream_::seg_list_tail, and StreamTcpSegmentReturntoPool().
Referenced by StreamTcpSessionClear(), StreamTcpSessionPktFree(), and StreamTcpSessionPoolCleanup().
int StreamTcpSegmentForEach (const Packet * p, uint8_t flag, StreamSegmentCallback CallbackFunc, void * data)
Run callback function on each TCP segment.
This function is used by StreamMsgForEach() which should be used directly.
Returns
-1 in case of error, the number of segment in case of success
Definition at line 5929 of file stream-tcp.c.
References TcpSession_::client, Packet_::flow, FLOW_PKT_TOSERVER, FLOWLOCK_RDLOCK, FLOWLOCK_UNLOCK, TcpStream_::last_ack, TcpSegment_::next, TcpSegment_::payload, TcpSegment_::payload_len, Flow_::protoctx, SCLogDebug, TcpStream_::seg_list, TcpSegment_::seq, SEQ_LT, and TcpSession_::server.
Referenced by StreamSegmentForEach().
void StreamTcpSessionClear (void * ssnptr)
Function to return the stream back to the pool. It returns the segments in the stream to the segment pool.
This function is called when the flow is destroyed, so it should free everything related to the tcp session. So including the app layer data. We are guaranteed to only get here when the flow's use_cnt is 0.
Parameters
ssn Void ptr to the ssn.
Definition at line 178 of file stream-tcp.c.
References TcpSession_::client, StreamMsg_::next, TcpStateQueue_::next, PoolThreadReturn(), StreamMsg_::prev, TcpSession_::queue, TcpSession_::queue_len, SCEnter, SCFree, SCLogDebug, SCMutexLock, SCMutexUnlock, SCReturn, TcpSession_::server, StreamMsgReturnToPool(), StreamTcpDecrMemuse(), StreamTcpReturnStreamSegments(), StreamTcpSackFreeList(), TcpSession_::toclient_smsg_head, and TcpSession_::toserver_smsg_head.
Referenced by StreamTcpInitConfig().
void StreamTcpSessionPktFree (Packet * p)
Function to return the stream segments back to the pool.
We don't clear out the app layer storage here as that is under protection of the "use_cnt" reference counter in the flow. This function is called when the use_cnt is always at least 1 (this pkt has incremented the flow use_cnt itself), so we don't bother.
Parameters
p Packet used to identify the stream.
Definition at line 250 of file stream-tcp.c.
References TcpSession_::client, Packet_::flow, Flow_::protoctx, SCEnter, SCReturn, TcpSession_::server, and StreamTcpReturnStreamSegments().
Referenced by StreamTcpPacket().
void* StreamTcpSessionPoolAlloc ()
Stream alloc function for the Pool.
Return values
ptr void ptr to TcpSession structure with all vars set to 0/NULL
Definition at line 267 of file stream-tcp.c.
References SCMalloc, StreamTcpCheckMemcap(), and unlikely.
Referenced by StreamTcpInitConfig(), and StreamTcpThreadInit().
void StreamTcpSessionPoolCleanup (void * s)
Pool free function.
Parameters
s Void ptr to TcpSession memory
Definition at line 291 of file stream-tcp.c.
References TcpSession_::client, StreamMsg_::next, TcpStateQueue_::next, StreamMsg_::prev, TcpSession_::queue, TcpSession_::queue_len, SCFree, SCLogDebug, TcpSession_::server, StreamMsgReturnToPool(), StreamTcpDecrMemuse(), StreamTcpReturnStreamSegments(), TcpSession_::toclient_smsg_head, and TcpSession_::toserver_smsg_head.
Referenced by StreamTcpInitConfig(), and StreamTcpThreadInit().
int StreamTcpSessionPoolInit (void * data, void * initdata)
Definition at line 281 of file stream-tcp.c.
References StreamTcpIncrMemuse().
Referenced by StreamTcpInitConfig(), and StreamTcpThreadInit().
void StreamTcpSetDisableRawReassemblyFlag (TcpSession * ssn, char direction)
Set the No reassembly flag for the given direction in given TCP session.
Parameters
ssn TCP Session to set the flag in
direction direction to set the flag in: 0 toserver, 1 toclient
Definition at line 5718 of file stream-tcp.c.
References TcpSession_::client, TcpStream_::flags, TcpSession_::server, and STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED.
Referenced by AppLayerParserParse().
void StreamTcpSetOSPolicy (TcpStream * stream, Packet * p)
Function to set the OS policy for the given stream based on the destination of the received packet.
Parameters
stream TcpStream of which os_policy needs to set
p Packet which is used to set the os policy
Definition at line 709 of file stream-tcp.c.
References GET_IPV4_DST_ADDR_PTR, GET_IPV6_DST_ADDR, TcpStream_::os_policy, OS_POLICY_BSD, OS_POLICY_BSD_RIGHT, OS_POLICY_DEFAULT, OS_POLICY_OLD_SOLARIS, OS_POLICY_SOLARIS, PKT_IS_IPV4, PKT_IS_IPV6, SCHInfoGetIPv4HostOSFlavour(), SCHInfoGetIPv6HostOSFlavour(), and SCLogDebug.
Referenced by StreamTcpReassembleInsertSegment().
void StreamTcpSetSessionNoReassemblyFlag (TcpSession * ssn, char direction)
Set the No reassembly flag for the given direction in given TCP session.
Parameters
ssn TCP Session to set the flag in
direction direction to set the flag in: 0 toserver, 1 toclient
Definition at line 5706 of file stream-tcp.c.
References TcpSession_::client, TcpStream_::flags, TcpSession_::server, and STREAMTCP_STREAM_FLAG_NOREASSEMBLY.
Referenced by AppLayerHandleTCPData(), and AppLayerParserParse().
TmEcode StreamTcpThreadDeinit (ThreadVars * tv, void * data)
Definition at line 5141 of file stream-tcp.c.
References StreamTcpThread_::ra_ctx, SCEnter, SCFree, SCReturnInt, StreamTcpReassembleFreeThreadCtx(), and TM_ECODE_OK.
Referenced by TmModuleStreamTcpRegister().
TmEcode StreamTcpThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 5074 of file stream-tcp.c.
References StreamTcpThread_::counter_tcp_invalid_checksum, StreamTcpThread_::counter_tcp_no_flow, StreamTcpThread_::counter_tcp_pseudo, StreamTcpThread_::counter_tcp_pseudo_failed, TcpReassemblyThreadCtx_::counter_tcp_reass_gap, StreamTcpThread_::counter_tcp_rst, TcpReassemblyThreadCtx_::counter_tcp_segment_memcap, StreamTcpThread_::counter_tcp_sessions, StreamTcpThread_::counter_tcp_ssn_memcap, TcpReassemblyThreadCtx_::counter_tcp_stream_depth, StreamTcpThread_::counter_tcp_syn, StreamTcpThread_::counter_tcp_synack, PoolThreadGrow(), PoolThreadInit(), PoolThreadSize(), TcpStreamCnf_::prealloc_sessions, StreamTcpThread_::ra_ctx, StreamTcpThread_::runmode_flow_stream_async, RunmodeGetFlowStreamAsync(), SCEnter, SCLogDebug, SCMalloc, SCMutexLock, SCMutexUnlock, SCReturnInt, StreamTcpThread_::ssn_pool_id, StatsRegisterCounter(), stream_config, StreamTcpReassembleInitThreadCtx(), StreamTcpSessionPoolAlloc(), StreamTcpSessionPoolCleanup(), StreamTcpSessionPoolInit(), TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by TmModuleStreamTcpRegister().
int TcpSessionPacketSsnReuse (const Packet * p, const Flow * f, const void * tcp_ssn)
Definition at line 4870 of file stream-tcp.c.
References Packet_::proto, Packet_::tcph, and TcpSessionReuseDoneEnough().
int TcpSessionReuseDoneEnough (const Packet * p, const Flow * f, const TcpSession * ssn)
Check if SSN is done enough for reuse.
Reuse means a new TCP session reuses the tuple (flow in suri)
Return values
bool true if ssn can be reused, false if not
Definition at line 4855 of file stream-tcp.c.
References TcpStreamCnf_::async_oneside, TcpStreamCnf_::midstream, stream_config, Packet_::tcph, TH_ACK, TH_SYN, and TRUE.
Referenced by TcpSessionPacketSsnReuse().
void TmModuleStreamTcpRegister (void)
Definition at line 125 of file stream-tcp.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, StreamTcp(), StreamTcpExitPrintStats(), StreamTcpRegisterTests(), StreamTcpThreadDeinit(), StreamTcpThreadInit(), TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_STREAM_TM, tmm_modules, and TMM_STREAMTCP.
Referenced by RegisterAllModules().
Variable Documentation
int stream_inline = 0
defined in stream-tcp-reassemble.c
Definition at line 123 of file stream-tcp.c.
Referenced by StreamTcpInitConfig(), and StreamTcpInlineMode().