suricata: src/stream-tcp-inline.c File Reference
stream-tcp-inline.c File Reference
#include "suricata-common.h"
#include "stream-tcp-inline.h"
#include "util-memcmp.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
Functions
int StreamTcpInlineMode (void)
See if stream engine is operating in inline mode.
int StreamTcpInlineSegmentCompare (TcpSegment *seg1, TcpSegment *seg2)
Compare the shared data portion of two segments.
void StreamTcpInlineSegmentReplacePacket (Packet *p, TcpSegment *seg)
Replace (part of) the payload portion of a packet by the data in a TCP segment.
void StreamTcpInlineRegisterTests (void)
Variables
int stream_inline
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Functions for the "inline mode" of the stream engine.
Definition in file stream-tcp-inline.c.
Function Documentation
int StreamTcpInlineMode (void)
See if stream engine is operating in inline mode.
Return values
0 no
1 yes
Definition at line 44 of file stream-tcp-inline.c.
References stream_inline.
Referenced by AppLayerHandleTCPData(), DoHandleGap(), StreamTcpPacket(), StreamTcpReassembleAppLayer(), StreamTcpReassembleHandleSegment(), and StreamTcpReassembleHandleSegmentUpdateACK().
void StreamTcpInlineRegisterTests (void)
Definition at line 645 of file stream-tcp-inline.c.
Referenced by StreamTcpReassembleRegisterTests().
int StreamTcpInlineSegmentCompare (TcpSegment * seg1, TcpSegment * seg2)
Compare the shared data portion of two segments.
If no data is shared, 0 will be returned.
Parameters
seg1 first segment
seg2 second segment
Return values
0 shared data is the same (or no data is shared)
1 shared data is different
Definition at line 60 of file stream-tcp-inline.c.
References BUG_ON, TcpSegment_::payload, TcpSegment_::payload_len, PrintRawDataFp(), SCEnter, SCLogDebug, SCMemcmp, SCReturnInt, TcpSegment_::seq, SEQ_EQ, SEQ_GT, and SEQ_LT.
void StreamTcpInlineSegmentReplacePacket (Packet * p, TcpSegment * seg)
Replace (part of) the payload portion of a packet by the data in a TCP segment.
Parameters
p Packet
seg TCP segment
Todo:
What about reassembled fragments?
What about unwrapped tunnel packets?
Todo:
review logic
Definition at line 136 of file stream-tcp-inline.c.
References BUG_ON, Packet_::flags, TcpSegment_::payload, Packet_::payload, TcpSegment_::payload_len, Packet_::payload_len, PKT_STREAM_MODIFIED, SCEnter, SCLogDebug, SCReturn, TcpSegment_::seq, SEQ_GT, SEQ_LT, and TCP_GET_SEQ.
Variable Documentation
int stream_inline
defined in stream-tcp-reassemble.c
Definition at line 123 of file stream-tcp.c.
Referenced by StreamTcpInitConfig(), and StreamTcpInlineMode().