suricata: src/stream-tcp.h File Reference
stream-tcp.h File Reference
#include "stream-tcp-private.h"
#include "app-layer-detect-proto.h"
#include "util-mpm.h"
#include "stream.h"
#include "stream-tcp-reassemble.h"
Data Structures
struct TcpStreamCnf_
struct StreamTcpThread_
Macros
#define COUNTER_STREAMTCP_STREAMS 1
#define STREAM_VERBOSE FALSE
#define STREAMTCP_INIT_FLAG_CHECKSUM_VALIDATION 0x01
Typedefs
typedef struct TcpStreamCnf_ TcpStreamCnf
typedef struct StreamTcpThread_ StreamTcpThread
Enumerations
enum { STREAM_HAS_UNPROCESSED_SEGMENTS_NONE = 0, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_REASSEMBLY = 1, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION = 2 }
Functions
void TmModuleStreamTcpRegister (void)
void StreamTcpInitConfig (char)
To initialize the stream global configuration data.
void StreamTcpFreeConfig (char)
void StreamTcpRegisterTests (void)
void StreamTcpSessionPktFree (Packet *)
Function to return the stream segments back to the pool.
void StreamTcpIncrMemuse (uint64_t)
void StreamTcpDecrMemuse (uint64_t)
int StreamTcpCheckMemcap (uint64_t)
Check if alloc'ing "size" would mean we're over memcap.
Packet * StreamTcpPseudoSetup (Packet *, uint8_t *, uint32_t)
Function to fetch a packet from the packet allocation queue for creation of the pseudo packet from the reassembled stream.
int StreamTcpSegmentForEach (const Packet *p, uint8_t flag, StreamSegmentCallback CallbackFunc, void *data)
Run callback function on each TCP segment.
void StreamTcpReassembleConfigEnableOverlapCheck (void)
TmEcode StreamTcpThreadInit (ThreadVars *, void *, void **)
TmEcode StreamTcpThreadDeinit (ThreadVars *tv, void *data)
int StreamTcpPacket (ThreadVars *tv, Packet *p, StreamTcpThread *stt, PacketQueue *pq)
void StreamTcpSessionClear (void *ssnptr)
Function to return the stream back to the pool. It returns the segments in the stream to the segment pool.
uint32_t StreamTcpGetStreamSize (TcpStream *stream)
get the size of a stream
Variables
TcpStreamCnf stream_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Definition in file stream-tcp.h.
Macro Definition Documentation
#define COUNTER_STREAMTCP_STREAMS 1
Definition at line 30 of file stream-tcp.h.
#define STREAM_VERBOSE FALSE
Definition at line 37 of file stream-tcp.h.
Referenced by main().
#define STREAMTCP_INIT_FLAG_CHECKSUM_VALIDATION 0x01
Definition at line 40 of file stream-tcp.h.
Referenced by StreamTcp(), and StreamTcpInitConfig().
Typedef Documentation
typedef struct StreamTcpThread_ StreamTcpThread
typedef struct TcpStreamCnf_ TcpStreamCnf
Enumeration Type Documentation
anonymous enum
Enumerator
STREAM_HAS_UNPROCESSED_SEGMENTS_NONE
STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_REASSEMBLY
STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION
Definition at line 188 of file stream-tcp.h.
Function Documentation
int StreamTcpCheckMemcap (uint64_t size)
Check if alloc'ing "size" would mean we're over memcap.
Return values
1 if in bounds
0 if not in bounds
Definition at line 161 of file stream-tcp.c.
References TcpStreamCnf_::memcap, SC_ATOMIC_GET, and stream_config.
Referenced by StreamTcp3whsQueueSynAck(), and StreamTcpSessionPoolAlloc().
void StreamTcpDecrMemuse (uint64_t)
Definition at line 143 of file stream-tcp.c.
References SC_ATOMIC_SUB.
Referenced by StreamTcpSessionClear(), and StreamTcpSessionPoolCleanup().
void StreamTcpFreeConfig (char)
Definition at line 620 of file stream-tcp.c.
References PoolThreadFree(), SCLogDebug, SCMutexDestroy, SCMutexLock, SCMutexUnlock, and StreamTcpReassembleFree().
Referenced by main().
uint32_t StreamTcpGetStreamSize (TcpStream * stream)
get the size of a stream
Note
this just calculates the diff between isn and last_ack and will not consider sequence wrap arounds (streams bigger than 4gb).
Return values
size stream size
Definition at line 752 of file stream-tcp.c.
References TcpStream_::isn, and TcpStream_::last_ack.
void StreamTcpIncrMemuse (uint64_t)
Definition at line 137 of file stream-tcp.c.
References SC_ATOMIC_ADD.
Referenced by StreamTcp3whsQueueSynAck(), and StreamTcpSessionPoolInit().
void StreamTcpInitConfig (char quiet)
To initialize the stream global configuration data.
Parameters
quiet It tells the mode of operation, if it is TRUE nothing will be get printed.
Definition at line 346 of file stream-tcp.c.
References TcpStreamCnf_::async_oneside, ConfGet(), ConfGetBool(), ConfGetInt(), ConfGetNode(), EngineModeIsIPS(), TcpStreamCnf_::flags, FLOW_PKT_TOCLIENT, FLOW_PKT_TOSERVER, FlowSetProtoFreeFunc(), TcpStreamCnf_::max_synack_queued, TcpStreamCnf_::memcap, TcpStreamCnf_::midstream, ParseSizeStringU16(), ParseSizeStringU32(), ParseSizeStringU64(), PoolThreadInit(), TcpStreamCnf_::prealloc_sessions, TcpStreamCnf_::reassembly_depth, TcpStreamCnf_::reassembly_memcap, TcpStreamCnf_::reassembly_toclient_chunk_size, TcpStreamCnf_::reassembly_toserver_chunk_size, RunmodeIsUnittests(), SC_ATOMIC_INIT, SC_ERR_INVALID_VALUE, SC_ERR_SIZE_PARSE, SC_WARN_OPTION_OBSOLETE, SCLogDebug, SCLogError, SCLogInfo, SCLogWarning, SCMutexLock, SCMutexUnlock, TcpStreamCnf_::segment_init_flags, SEGMENTTCP_FLAG_RAW_PROCESSED, TcpStreamCnf_::ssn_init_flags, StatsRegisterGlobalCounter(), stream_config, stream_inline, StreamMsgQueueSetMinChunkLen(), STREAMTCP_DEFAULT_MAX_SYNACK_QUEUED, STREAMTCP_DEFAULT_MEMCAP, STREAMTCP_DEFAULT_PREALLOC, STREAMTCP_DEFAULT_REASSEMBLY_MEMCAP, STREAMTCP_DEFAULT_TOCLIENT_CHUNK_SIZE, STREAMTCP_DEFAULT_TOSERVER_CHUNK_SIZE, STREAMTCP_FLAG_DISABLE_RAW, STREAMTCP_INIT_FLAG_CHECKSUM_VALIDATION, StreamTcpMemuseCounter(), StreamTcpReassembleInit(), StreamTcpSessionClear(), StreamTcpSessionPoolAlloc(), StreamTcpSessionPoolCleanup(), StreamTcpSessionPoolInit(), and WarnInvalidConfEntry.
Referenced by main().
int StreamTcpPacket (ThreadVars * tv, Packet * p, StreamTcpThread * stt, PacketQueue * pq)
Definition at line 4451 of file stream-tcp.c.
References Flow_::alproto, TcpSession_::client, StreamTcpThread_::counter_tcp_rst, StreamTcpThread_::counter_tcp_syn, StreamTcpThread_::counter_tcp_synack, DEBUG_ASSERT_FLOW_LOCKED, DecodeSetNoPacketInspectionFlag, TcpStream_::flags, TcpSession_::flags, Packet_::flags, Packet_::flow, ThreadVars_::id, TcpStream_::last_ack, PacketQueue_::len, PACKET_DROP, PacketDequeue(), PacketEnqueue(), Packet_::pcap_cnt, PKT_IS_TOCLIENT, PKT_IS_TOSERVER, PKT_PSEUDO_STREAM_END, PKT_STREAM_EST, PKT_STREAM_MODIFIED, PKT_STREAM_NOPCAPLOG, Flow_::protoctx, StreamTcpThread_::pseudo_queue, StreamTcpThread_::ra_ctx, ReCalculateChecksum(), SCEnter, SCLogDebug, SCReturnInt, TcpSession_::server, TcpSession_::state, StatsIncr(), STREAM_PKT_BROKEN_ACK, STREAMTCP_FLAG_MIDSTREAM_SYNACK, STREAMTCP_STREAM_FLAG_DEPTH_REACHED, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, StreamTcpDisableAppLayer(), StreamTcpInlineMode(), StreamTcpReassembleHandleSegment(), StreamTcpSessionPktFree(), StreamTcpSetEvent, TCP_CLOSE_WAIT, TCP_CLOSED, TCP_CLOSING, TCP_ESTABLISHED, TCP_FIN_WAIT1, TCP_FIN_WAIT2, TcpStream_::tcp_flags, TCP_GET_ACK, TCP_LAST_ACK, TCP_NONE, TcpSession_::tcp_packet_flags, TCP_SYN_RECV, TCP_SYN_SENT, TCP_TIME_WAIT, Packet_::tcph, TH_ACK, TH_RST, TH_SYN, Flow_::thread_id, and unlikely.
Referenced by StreamTcp().
Packet* StreamTcpPseudoSetup (Packet * parent, uint8_t * pkt, uint32_t len)
Function to fetch a packet from the packet allocation queue for creation of the pseudo packet from the reassembled stream.
Parameters
parent Pointer to the parent of the pseudo packet
pkt pointer to the raw packet of the parent
len length of the packet
Returns
upon success returns the pointer to the new pseudo packet otherwise NULL
Definition at line 5763 of file stream-tcp.c.
References Packet_::datalink, Packet_::flow, PacketCopyData(), PacketGetFromQueueOrAlloc(), Packet_::proto, Packet_::recursion_level, Packet_::root, SCEnter, SCReturnPtr, SET_TUNNEL_PKT, Packet_::ts, and TUNNEL_INCR_PKT_TPR.
Referenced by StreamTcpPseudoPacketCreateStreamEndPacket().
void StreamTcpReassembleConfigEnableOverlapCheck (void)
Definition at line 109 of file stream-tcp-reassemble.c.
Referenced by DetectEngineEventParse().
void StreamTcpRegisterTests (void)
Definition at line 10738 of file stream-tcp.c.
References StreamTcpReassembleRegisterTests(), and StreamTcpSackRegisterTests().
Referenced by TmModuleStreamTcpRegister().
int StreamTcpSegmentForEach (const Packet * p, uint8_t flag, StreamSegmentCallback CallbackFunc, void * data)
Run callback function on each TCP segment.
This function is used by StreamMsgForEach() which should be used directly.
Returns
-1 in case of error, the number of segment in case of success
Definition at line 5929 of file stream-tcp.c.
References TcpSession_::client, Packet_::flow, FLOW_PKT_TOSERVER, FLOWLOCK_RDLOCK, FLOWLOCK_UNLOCK, TcpStream_::last_ack, TcpSegment_::next, TcpSegment_::payload, TcpSegment_::payload_len, Flow_::protoctx, SCLogDebug, TcpStream_::seg_list, TcpSegment_::seq, SEQ_LT, and TcpSession_::server.
Referenced by StreamSegmentForEach().
void StreamTcpSessionClear (void * ssnptr)
Function to return the stream back to the pool. It returns the segments in the stream to the segment pool.
This function is called when the flow is destroyed, so it should free everything related to the tcp session. So including the app layer data. We are guaranteed to only get here when the flow's use_cnt is 0.
Parameters
ssn Void ptr to the ssn.
Definition at line 178 of file stream-tcp.c.
References TcpSession_::client, StreamMsg_::next, TcpStateQueue_::next, PoolThreadReturn(), StreamMsg_::prev, TcpSession_::queue, TcpSession_::queue_len, SCEnter, SCFree, SCLogDebug, SCMutexLock, SCMutexUnlock, SCReturn, TcpSession_::server, StreamMsgReturnToPool(), StreamTcpDecrMemuse(), StreamTcpReturnStreamSegments(), StreamTcpSackFreeList(), TcpSession_::toclient_smsg_head, and TcpSession_::toserver_smsg_head.
Referenced by StreamTcpInitConfig().
void StreamTcpSessionPktFree (Packet * p)
Function to return the stream segments back to the pool.
We don't clear out the app layer storage here as that is under protection of the "use_cnt" reference counter in the flow. This function is called when the use_cnt is always at least 1 (this pkt has incremented the flow use_cnt itself), so we don't bother.
Parameters
p Packet used to identify the stream.
Definition at line 250 of file stream-tcp.c.
References TcpSession_::client, Packet_::flow, Flow_::protoctx, SCEnter, SCReturn, TcpSession_::server, and StreamTcpReturnStreamSegments().
Referenced by StreamTcpPacket().
TmEcode StreamTcpThreadDeinit (ThreadVars * tv, void * data)
Definition at line 5141 of file stream-tcp.c.
References StreamTcpThread_::ra_ctx, SCEnter, SCFree, SCReturnInt, StreamTcpReassembleFreeThreadCtx(), and TM_ECODE_OK.
Referenced by TmModuleStreamTcpRegister().
TmEcode StreamTcpThreadInit (ThreadVars * , void * , void **)
Definition at line 5074 of file stream-tcp.c.
References StreamTcpThread_::counter_tcp_invalid_checksum, StreamTcpThread_::counter_tcp_no_flow, StreamTcpThread_::counter_tcp_pseudo, StreamTcpThread_::counter_tcp_pseudo_failed, TcpReassemblyThreadCtx_::counter_tcp_reass_gap, StreamTcpThread_::counter_tcp_rst, TcpReassemblyThreadCtx_::counter_tcp_segment_memcap, StreamTcpThread_::counter_tcp_sessions, StreamTcpThread_::counter_tcp_ssn_memcap, TcpReassemblyThreadCtx_::counter_tcp_stream_depth, StreamTcpThread_::counter_tcp_syn, StreamTcpThread_::counter_tcp_synack, PoolThreadGrow(), PoolThreadInit(), PoolThreadSize(), TcpStreamCnf_::prealloc_sessions, StreamTcpThread_::ra_ctx, StreamTcpThread_::runmode_flow_stream_async, RunmodeGetFlowStreamAsync(), SCEnter, SCLogDebug, SCMalloc, SCMutexLock, SCMutexUnlock, SCReturnInt, StreamTcpThread_::ssn_pool_id, StatsRegisterCounter(), stream_config, StreamTcpReassembleInitThreadCtx(), StreamTcpSessionPoolAlloc(), StreamTcpSessionPoolCleanup(), StreamTcpSessionPoolInit(), TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by TmModuleStreamTcpRegister().
void TmModuleStreamTcpRegister (void)
Definition at line 125 of file stream-tcp.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::RegisterTests, StreamTcp(), StreamTcpExitPrintStats(), StreamTcpRegisterTests(), StreamTcpThreadDeinit(), StreamTcpThreadInit(), TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_STREAM_TM, tmm_modules, and TMM_STREAMTCP.
Referenced by RegisterAllModules().
Variable Documentation
TcpStreamCnf stream_config
Definition at line 114 of file stream-tcp.h.
Referenced by StreamTcp(), StreamTcp3whsQueueSynAck(), StreamTcpCheckMemcap(), StreamTcpGetSegment(), StreamTcpInitConfig(), StreamTcpNewSession(), StreamTcpReassembleCheckMemcap(), StreamTcpReassemblyConfig(), StreamTcpThreadInit(), and TcpSessionReuseDoneEnough().