suricata: libhtp/htp/strlcpy.c File Reference
strlcpy.c File Reference
#include "htp_config_auto.h"
#include "htp_private.h"
#include <sys/types.h>
#include <string.h>
Functions
size_t strlcpy (char *dst, const char *src, size_t siz)
Function Documentation
size_t strlcpy (char * dst, const char * src, size_t siz)
Definition at line 48 of file strlcpy.c.
Referenced by AFPPeersListAdd(), AlertFastLogger(), ConfGetNode(), ConfLoadCompleteIncludePath(), DetectAddressParseString(), DetectBytejumpParse(), DetectLoadCompleteSigPath(), GetIfaceMTU(), GetIfaceOffloading(), GetIfaceRSSQueuesNum(), LogHttpLogInitCtx(), LogTcpDataLogInitCtx(), OldParsePfringConfig(), ParseAFPConfig(), ParseNflogConfig(), ParsePcapConfig(), ParsePfringConfig(), PcapTranslateIPToDevice(), PoolTestInitArg(), PortParse(), ReceiveAFPThreadInit(), ReceivePcapThreadInit(), SCRadixAddKeyIPV4String(), SCRadixAddKeyIPV6String(), and SRepLoadCatFileFromFD().