suricata: TmModule_ Struct Reference
TmModule_ Struct Reference
#include <tm-modules.h>
Data Fields
char * name
TmEcode(* ThreadInit)(ThreadVars *, void *, void **)
void(* ThreadExitPrintStats)(ThreadVars *, void *)
TmEcode(* ThreadDeinit)(ThreadVars *, void *)
TmEcode(* Func)(ThreadVars *, Packet *, void *, PacketQueue *, PacketQueue *)
TmEcode(* PktAcqLoop)(ThreadVars *, void *, void *)
TmEcode(* Management)(ThreadVars *, void *)
TmEcode(* Init)(void)
TmEcode(* DeInit)(void)
void(* RegisterTests)(void)
uint8_t cap_flags
uint8_t flags
uint8_t priority
Detailed Description
Definition at line 39 of file tm-modules.h.
Field Documentation
uint8_t TmModule_::cap_flags
Flags to indicate the capability requierment of the given TmModule
Definition at line 60 of file tm-modules.h.
Referenced by SetupOutputs(), TmModuleAlertDebugLogRegister(), TmModuleAlertFastLogRegister(), TmModuleAlertPreludeRegister(), TmModuleAlertSyslogRegister(), TmModuleDecodeAFPRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDetectLoaderRegister(), TmModuleDetectRegister(), TmModuleFiledataLoggerRegister(), TmModuleFileLoggerRegister(), TmModuleFlowManagerRegister(), TmModuleFlowRecyclerRegister(), TmModuleLogDnsLogRegister(), TmModuleLogDropLogRegister(), TmModuleLogFileLogRegister(), TmModuleLogFilestoreRegister(), TmModuleLogHttpLogRegister(), TmModuleLogStatsLogRegister(), TmModuleLogTcpDataLogRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModulePacketLoggerRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleRespondRejectRegister(), TmModuleStatsLoggerRegister(), TmModuleStreamingLoggerRegister(), TmModuleStreamTcpRegister(), TmModuleTxLoggerRegister(), TmModuleUnified2AlertRegister(), TmModuleUnixManagerRegister(), and TmModuleVerdictIPFWRegister().
TmEcode(* TmModule_::DeInit)(void)
Definition at line 56 of file tm-modules.h.
Referenced by TmModuleRunDeInit().
uint8_t TmModule_::flags
Definition at line 63 of file tm-modules.h.
Referenced by TmModuleAlertDebugLogRegister(), TmModuleAlertFastLogRegister(), TmModuleAlertPreludeRegister(), TmModuleAlertSyslogRegister(), TmModuleDecodeAFPRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDetectLoaderRegister(), TmModuleDetectRegister(), TmModuleFlowManagerRegister(), TmModuleFlowRecyclerRegister(), TmModuleLogDnsLogRegister(), TmModuleLogDropLogRegister(), TmModuleLogFileLogRegister(), TmModuleLogFilestoreRegister(), TmModuleLogHttpLogRegister(), TmModuleLogStatsLogRegister(), TmModuleLogTcpDataLogRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFQRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleStreamTcpRegister(), TmModuleUnified2AlertRegister(), TmModuleUnixManagerRegister(), and TmThreadDisableReceiveThreads().
TmEcode(* TmModule_::Func)(ThreadVars *, Packet *, void *, PacketQueue *, PacketQueue *)
the packet processing function
Definition at line 48 of file tm-modules.h.
Referenced by TmModuleAlertDebugLogRegister(), TmModuleAlertPreludeRegister(), TmModuleAlertSyslogRegister(), TmModuleDebugList(), TmModuleDecodeAFPRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDetectRegister(), TmModuleFiledataLoggerRegister(), TmModuleFileLoggerRegister(), TmModuleLogFileLogRegister(), TmModuleLogFilestoreRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleOutputJsonRegister(), TmModulePacketLoggerRegister(), TmModulePcapLogRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFQRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleRespondRejectRegister(), TmModuleStreamingLoggerRegister(), TmModuleStreamTcpRegister(), TmModuleTxLoggerRegister(), TmModuleVerdictIPFWRegister(), and TmModuleVerdictNFQRegister().
TmEcode(* TmModule_::Init)(void)
global Init/DeInit
Definition at line 55 of file tm-modules.h.
Referenced by TmModuleRunInit().
TmEcode(* TmModule_::Management)(ThreadVars *, void *)
Definition at line 52 of file tm-modules.h.
Referenced by TmModuleDetectLoaderRegister(), TmModuleFlowManagerRegister(), TmModuleFlowRecyclerRegister(), and TmModuleUnixManagerRegister().
char* TmModule_::name
Definition at line 40 of file tm-modules.h.
Referenced by RunModeShutDown(), TmModuleAlertDebugLogRegister(), TmModuleAlertFastLogRegister(), TmModuleAlertPreludeRegister(), TmModuleAlertSyslogRegister(), TmModuleDebugList(), TmModuleDecodeAFPRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFLOGRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDetectLoaderRegister(), TmModuleDetectRegister(), TmModuleFiledataLoggerRegister(), TmModuleFileLoggerRegister(), TmModuleFlowManagerRegister(), TmModuleFlowRecyclerRegister(), TmModuleGetByName(), TmModuleGetIDForTM(), TmModuleJsonAlertLogRegister(), TmModuleJsonDnsLogRegister(), TmModuleJsonDropLogRegister(), TmModuleJsonFileLogRegister(), TmModuleJsonFlowLogRegister(), TmModuleJsonHttpLogRegister(), TmModuleJsonNetFlowLogRegister(), TmModuleJsonSmtpLogRegister(), TmModuleJsonSshLogRegister(), TmModuleJsonStatsLogRegister(), TmModuleJsonTemplateLogRegister(), TmModuleJsonTlsLogRegister(), TmModuleLogDnsLogRegister(), TmModuleLogDropLogRegister(), TmModuleLogFileLogRegister(), TmModuleLogFilestoreRegister(), TmModuleLogHttpLogRegister(), TmModuleLogStatsLogRegister(), TmModuleLogTcpDataLogRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleOutputJsonRegister(), TmModulePacketLoggerRegister(), TmModulePcapLogRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFLOGRegister(), TmModuleReceiveNFQRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleRegisterTests(), TmModuleRespondRejectRegister(), TmModuleRunDeInit(), TmModuleRunInit(), TmModuleStatsLoggerRegister(), TmModuleStreamingLoggerRegister(), TmModuleStreamTcpRegister(), TmModuleTxLoggerRegister(), TmModuleUnified2AlertRegister(), TmModuleUnixManagerRegister(), TmModuleVerdictIPFWRegister(), TmModuleVerdictNFQRegister(), and TmThreadGetFirstTmSlotForPartialPattern().
TmEcode(* TmModule_::PktAcqLoop)(ThreadVars *, void *, void *)
Definition at line 50 of file tm-modules.h.
Referenced by TmModuleNapatechStreamRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNFQRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), and TmModuleReceivePfringRegister().
uint8_t TmModule_::priority
Definition at line 65 of file tm-modules.h.
Referenced by TmModuleLogFilestoreRegister(), and TmModuleLogTlsStoreRegister().
void(* TmModule_::RegisterTests)(void)
Definition at line 58 of file tm-modules.h.
Referenced by TmModuleAlertDebugLogRegister(), TmModuleAlertFastLogRegister(), TmModuleAlertSyslogRegister(), TmModuleDecodeAFPRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDetectRegister(), TmModuleLogDnsLogRegister(), TmModuleLogDropLogRegister(), TmModuleLogFileLogRegister(), TmModuleLogFilestoreRegister(), TmModuleLogHttpLogRegister(), TmModuleLogStatsLogRegister(), TmModuleLogTcpDataLogRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleOutputJsonRegister(), TmModulePcapLogRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFQRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleRegisterTests(), TmModuleRespondRejectRegister(), TmModuleStreamTcpRegister(), TmModuleUnified2AlertRegister(), TmModuleVerdictIPFWRegister(), and TmModuleVerdictNFQRegister().
TmEcode(* TmModule_::ThreadDeinit)(ThreadVars *, void *)
Definition at line 45 of file tm-modules.h.
Referenced by OutputFlowLogThreadDeinit(), TmModuleAlertDebugLogRegister(), TmModuleAlertFastLogRegister(), TmModuleAlertPreludeRegister(), TmModuleAlertSyslogRegister(), TmModuleDecodeAFPRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDetectLoaderRegister(), TmModuleDetectRegister(), TmModuleFiledataLoggerRegister(), TmModuleFileLoggerRegister(), TmModuleFlowManagerRegister(), TmModuleFlowRecyclerRegister(), TmModuleLogDnsLogRegister(), TmModuleLogDropLogRegister(), TmModuleLogFileLogRegister(), TmModuleLogFilestoreRegister(), TmModuleLogHttpLogRegister(), TmModuleLogStatsLogRegister(), TmModuleLogTcpDataLogRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleOutputJsonRegister(), TmModulePacketLoggerRegister(), TmModulePcapLogRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFQRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleRespondRejectRegister(), TmModuleStatsLoggerRegister(), TmModuleStreamingLoggerRegister(), TmModuleStreamTcpRegister(), TmModuleTxLoggerRegister(), TmModuleUnified2AlertRegister(), TmModuleUnixManagerRegister(), TmModuleVerdictIPFWRegister(), and TmModuleVerdictNFQRegister().
void(* TmModule_::ThreadExitPrintStats)(ThreadVars *, void *)
Definition at line 44 of file tm-modules.h.
Referenced by OutputFlowLogExitPrintStats(), TmModuleAlertDebugLogRegister(), TmModuleAlertFastLogRegister(), TmModuleAlertSyslogRegister(), TmModuleDecodeAFPRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDetectRegister(), TmModuleFiledataLoggerRegister(), TmModuleFileLoggerRegister(), TmModuleLogDnsLogRegister(), TmModuleLogDropLogRegister(), TmModuleLogFileLogRegister(), TmModuleLogFilestoreRegister(), TmModuleLogHttpLogRegister(), TmModuleLogStatsLogRegister(), TmModuleLogTcpDataLogRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModulePacketLoggerRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFQRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleStatsLoggerRegister(), TmModuleStreamingLoggerRegister(), TmModuleStreamTcpRegister(), TmModuleTxLoggerRegister(), TmModuleVerdictIPFWRegister(), and TmModuleVerdictNFQRegister().
TmEcode(* TmModule_::ThreadInit)(ThreadVars *, void *, void **)
thread handling
Definition at line 43 of file tm-modules.h.
Referenced by OutputFlowLogThreadInit(), TmModuleAlertDebugLogRegister(), TmModuleAlertFastLogRegister(), TmModuleAlertPreludeRegister(), TmModuleAlertSyslogRegister(), TmModuleDecodeAFPRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFLOGRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDetectLoaderRegister(), TmModuleDetectRegister(), TmModuleFiledataLoggerRegister(), TmModuleFileLoggerRegister(), TmModuleFlowManagerRegister(), TmModuleFlowRecyclerRegister(), TmModuleJsonAlertLogRegister(), TmModuleJsonDnsLogRegister(), TmModuleJsonDropLogRegister(), TmModuleJsonFileLogRegister(), TmModuleJsonFlowLogRegister(), TmModuleJsonHttpLogRegister(), TmModuleJsonNetFlowLogRegister(), TmModuleJsonSmtpLogRegister(), TmModuleJsonSshLogRegister(), TmModuleJsonStatsLogRegister(), TmModuleJsonTemplateLogRegister(), TmModuleJsonTlsLogRegister(), TmModuleLogDnsLogRegister(), TmModuleLogDropLogRegister(), TmModuleLogFileLogRegister(), TmModuleLogFilestoreRegister(), TmModuleLogHttpLogRegister(), TmModuleLogStatsLogRegister(), TmModuleLogTcpDataLogRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleOutputJsonRegister(), TmModulePacketLoggerRegister(), TmModulePcapLogRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFLOGRegister(), TmModuleReceiveNFQRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleRespondRejectRegister(), TmModuleStatsLoggerRegister(), TmModuleStreamingLoggerRegister(), TmModuleStreamTcpRegister(), TmModuleTxLoggerRegister(), TmModuleUnified2AlertRegister(), TmModuleUnixManagerRegister(), TmModuleVerdictIPFWRegister(), and TmModuleVerdictNFQRegister().
The documentation for this struct was generated from the following file:
src/tm-modules.h