suricata: MpmTableElmt_ Struct Reference
MpmTableElmt_ Struct Reference
#include <util-mpm.h>
Data Fields
char * name
uint8_t max_pattern_length
void(* InitCtx)(struct MpmCtx_ *)
void(* InitThreadCtx)(struct MpmCtx_ *, struct MpmThreadCtx_ *, uint32_t)
void(* DestroyCtx)(struct MpmCtx_ *)
void(* DestroyThreadCtx)(struct MpmCtx_ *, struct MpmThreadCtx_ *)
int(* AddPattern)(struct MpmCtx_ *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
int(* AddPatternNocase)(struct MpmCtx_ *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
int(* Prepare)(struct MpmCtx_ *)
uint32_t(* Search)(struct MpmCtx_ *, struct MpmThreadCtx_ *, PatternMatcherQueue *, uint8_t *, uint16_t)
void(* Cleanup)(struct MpmThreadCtx_ *)
void(* PrintCtx)(struct MpmCtx_ *)
void(* PrintThreadCtx)(struct MpmThreadCtx_ *)
void(* RegisterUnittests)(void)
uint8_t flags
Detailed Description
Definition at line 183 of file util-mpm.h.
Field Documentation
int(* MpmTableElmt_::AddPattern)(struct MpmCtx_ *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
function pointers for adding patterns to the mpm ctx.
Parameters
mpm_ctx Mpm context to add the pattern to
pattern pointer to the pattern
pattern_len length of the pattern in bytes
offset pattern offset setting
depth pattern depth setting
pid pattern id
sid signature internal id
flags pattern flags
Definition at line 202 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmAddPatternCS(), MpmB2gRegister(), MpmB3gRegister(), and MpmWuManberRegister().
int(* MpmTableElmt_::AddPatternNocase)(struct MpmCtx_ *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
Definition at line 203 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmAddPatternCI(), MpmB2gRegister(), MpmB3gRegister(), and MpmWuManberRegister().
void(* MpmTableElmt_::Cleanup)(struct MpmThreadCtx_ *)
Definition at line 206 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), MpmWuManberRegister(), and PacketPatternCleanup().
void(* MpmTableElmt_::DestroyCtx)(struct MpmCtx_ *)
Definition at line 188 of file util-mpm.h.
Referenced by AppLayerProtoDetectDeSetup(), MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), MpmFactoryDeRegisterAllMpmCtxProfiles(), MpmFactoryReClaimMpmCtx(), MpmWuManberRegister(), PatternMatchDestroy(), and PatternMatchDestroyGroup().
void(* MpmTableElmt_::DestroyThreadCtx)(struct MpmCtx_ *, struct MpmThreadCtx_ *)
Definition at line 189 of file util-mpm.h.
Referenced by AppLayerProtoDetectDestroyCtxThread(), MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), MpmWuManberRegister(), and PatternMatchThreadDestroy().
uint8_t MpmTableElmt_::flags
Definition at line 210 of file util-mpm.h.
void(* MpmTableElmt_::InitCtx)(struct MpmCtx_ *)
Definition at line 186 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), MpmInitCtx(), and MpmWuManberRegister().
void(* MpmTableElmt_::InitThreadCtx)(struct MpmCtx_ *, struct MpmThreadCtx_ *, uint32_t)
Definition at line 187 of file util-mpm.h.
Referenced by AppLayerProtoDetectGetCtxThread(), MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), MpmInitThreadCtx(), and MpmWuManberRegister().
uint8_t MpmTableElmt_::max_pattern_length
Definition at line 185 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), and MpmWuManberRegister().
char* MpmTableElmt_::name
Definition at line 184 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), and MpmWuManberRegister().
int(* MpmTableElmt_::Prepare)(struct MpmCtx_ *)
Definition at line 204 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), MpmWuManberRegister(), PatternMatchPrepareGroup(), and SigGroupBuild().
void(* MpmTableElmt_::PrintCtx)(struct MpmCtx_ *)
Definition at line 207 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), and MpmWuManberRegister().
void(* MpmTableElmt_::PrintThreadCtx)(struct MpmThreadCtx_ *)
Definition at line 208 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), and MpmWuManberRegister().
void(* MpmTableElmt_::RegisterUnittests)(void)
Definition at line 209 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), MpmRegisterTests(), and MpmWuManberRegister().
uint32_t(* MpmTableElmt_::Search)(struct MpmCtx_ *, struct MpmThreadCtx_ *, PatternMatcherQueue *, uint8_t *, uint16_t)
Definition at line 205 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmB2gRegister(), MpmB3gRegister(), MpmWuManberRegister(), and PacketPatternSearch().
The documentation for this struct was generated from the following file:
src/util-mpm.h