suricata: AppLayerParserProtoCtx_ Struct Reference
AppLayerParserProtoCtx_ Struct Reference
App layer protocol parser context.
Data Fields
int(* Parser [2])(Flow *f, void *protocol_state, AppLayerParserState *pstate, uint8_t *input, uint32_t input_len, void *local_storage)
char logger
void *(* StateAlloc)(void)
void(* StateFree)(void *)
void(* StateTransactionFree)(void *, uint64_t)
void *(* LocalStorageAlloc)(void)
void(* LocalStorageFree)(void *)
void(* Truncate)(void *, uint8_t)
FileContainer *(* StateGetFiles)(void *, uint8_t)
AppLayerDecoderEvents *(* StateGetEvents)(void *, uint64_t)
int(* StateHasEvents)(void *)
int(* StateGetProgress)(void *alstate, uint8_t direction)
uint64_t(* StateGetTxCnt)(void *alstate)
void *(* StateGetTx)(void *alstate, uint64_t tx_id)
int(* StateGetProgressCompletionStatus)(uint8_t direction)
int(* StateGetEventInfo)(const char *event_name, int *event_id, AppLayerEventType *event_type)
int(* StateHasTxDetectState)(void *alstate)
DetectEngineState *(* GetTxDetectState)(void *tx)
int(* SetTxDetectState)(void *alstate, void *tx, DetectEngineState *)
uint8_t first_data_dir
Detailed Description
App layer protocol parser context.
Definition at line 83 of file app-layer-parser.c.
Field Documentation
uint8_t AppLayerParserProtoCtx_::first_data_dir
Definition at line 117 of file app-layer-parser.c.
Referenced by AppLayerParserRegisterParserAcceptableDataDirection().
DetectEngineState*(* AppLayerParserProtoCtx_::GetTxDetectState)(void *tx)
Definition at line 111 of file app-layer-parser.c.
Referenced by AppLayerParserGetTxDetectState(), and AppLayerParserRegisterDetectStateFuncs().
void*(* AppLayerParserProtoCtx_::LocalStorageAlloc)(void)
Definition at line 95 of file app-layer-parser.c.
Referenced by AppLayerParserRegisterLocalStorageFunc().
void(* AppLayerParserProtoCtx_::LocalStorageFree)(void *)
Definition at line 96 of file app-layer-parser.c.
Referenced by AppLayerParserRegisterLocalStorageFunc().
char AppLayerParserProtoCtx_::logger
Definition at line 90 of file app-layer-parser.c.
Referenced by AppLayerParserProtocolHasLogger(), AppLayerParserRegisterLogger(), AppLayerTransactionGetActiveDetectLog(), and AppLayerTransactionGetActiveLogOnly().
int(* AppLayerParserProtoCtx_::Parser[2])(Flow *f, void *protocol_state, AppLayerParserState *pstate, uint8_t *input, uint32_t input_len, void *local_storage)
Definition at line 86 of file app-layer-parser.c.
Referenced by AppLayerParserParse().
int(* AppLayerParserProtoCtx_::SetTxDetectState)(void *alstate, void *tx, DetectEngineState *)
Definition at line 112 of file app-layer-parser.c.
Referenced by AppLayerParserRegisterDetectStateFuncs(), and AppLayerParserSetTxDetectState().
void*(* AppLayerParserProtoCtx_::StateAlloc)(void)
Definition at line 92 of file app-layer-parser.c.
Referenced by AppLayerParserParse(), and AppLayerParserRegisterStateFuncs().
void(* AppLayerParserProtoCtx_::StateFree)(void *)
Definition at line 93 of file app-layer-parser.c.
Referenced by AppLayerParserRegisterStateFuncs(), and AppLayerParserStateCleanup().
int(* AppLayerParserProtoCtx_::StateGetEventInfo)(const char *event_name, int *event_id, AppLayerEventType *event_type)
Definition at line 107 of file app-layer-parser.c.
Referenced by AppLayerParserGetEventInfo().
AppLayerDecoderEvents*(* AppLayerParserProtoCtx_::StateGetEvents)(void *, uint64_t)
Definition at line 100 of file app-layer-parser.c.
Referenced by AppLayerParserProtocolIsTxEventAware(), and AppLayerParserRegisterGetEventsFunc().
FileContainer*(* AppLayerParserProtoCtx_::StateGetFiles)(void *, uint8_t)
Definition at line 99 of file app-layer-parser.c.
Referenced by AppLayerParserRegisterGetFilesFunc().
int(* AppLayerParserProtoCtx_::StateGetProgress)(void *alstate, uint8_t direction)
Definition at line 103 of file app-layer-parser.c.
int(* AppLayerParserProtoCtx_::StateGetProgressCompletionStatus)(uint8_t direction)
Definition at line 106 of file app-layer-parser.c.
void*(* AppLayerParserProtoCtx_::StateGetTx)(void *alstate, uint64_t tx_id)
Definition at line 105 of file app-layer-parser.c.
Referenced by AppLayerParserProtocolIsTxAware().
uint64_t(* AppLayerParserProtoCtx_::StateGetTxCnt)(void *alstate)
Definition at line 104 of file app-layer-parser.c.
int(* AppLayerParserProtoCtx_::StateHasEvents)(void *)
Definition at line 101 of file app-layer-parser.c.
Referenced by AppLayerParserRegisterHasEventsFunc().
int(* AppLayerParserProtoCtx_::StateHasTxDetectState)(void *alstate)
Definition at line 110 of file app-layer-parser.c.
Referenced by AppLayerParserHasTxDetectState(), and AppLayerParserRegisterDetectStateFuncs().
void(* AppLayerParserProtoCtx_::StateTransactionFree)(void *, uint64_t)
Definition at line 94 of file app-layer-parser.c.
Referenced by AppLayerParserProtocolSupportsTxs().
void(* AppLayerParserProtoCtx_::Truncate)(void *, uint8_t)
Definition at line 98 of file app-layer-parser.c.
Referenced by AppLayerParserRegisterTruncateFunc(), and AppLayerParserStreamTruncated().
The documentation for this struct was generated from the following file:
src/app-layer-parser.c