suricata: src/suricata.c File Reference
suricata.c File Reference
#include "suricata-common.h"
#include "config.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "packet-queue.h"
#include "threads.h"
#include "threadvars.h"
#include "util-atomic.h"
#include "util-spm.h"
#include "util-cpu.h"
#include "util-action.h"
#include "util-pidfile.h"
#include "util-ioctl.h"
#include "util-device.h"
#include "util-misc.h"
#include "util-running-modes.h"
#include "detect-engine.h"
#include "detect-parse.h"
#include "detect-fast-pattern.h"
#include "detect-engine-tag.h"
#include "detect-engine-threshold.h"
#include "detect-engine-address.h"
#include "detect-engine-port.h"
#include "detect-engine-mpm.h"
#include "tm-queuehandlers.h"
#include "tm-queues.h"
#include "tm-threads.h"
#include "tmqh-flow.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "alert-fastlog.h"
#include "alert-unified2-alert.h"
#include "alert-debuglog.h"
#include "alert-prelude.h"
#include "alert-syslog.h"
#include "output-json-alert.h"
#include "output-json-flow.h"
#include "output-json-netflow.h"
#include "log-droplog.h"
#include "output-json-drop.h"
#include "log-httplog.h"
#include "output-json-http.h"
#include "log-dnslog.h"
#include "output-json-dns.h"
#include "log-tlslog.h"
#include "log-tlsstore.h"
#include "output-json-tls.h"
#include "output-json-ssh.h"
#include "log-pcap.h"
#include "log-file.h"
#include "output-json-file.h"
#include "output-json-smtp.h"
#include "output-json-stats.h"
#include "log-filestore.h"
#include "log-tcp-data.h"
#include "log-stats.h"
#include "output-json.h"
#include "output-json-template.h"
#include "stream-tcp.h"
#include "source-nfq.h"
#include "source-nfq-prototypes.h"
#include "source-nflog.h"
#include "source-ipfw.h"
#include "source-pcap.h"
#include "source-pcap-file.h"
#include "source-pfring.h"
#include "source-erf-file.h"
#include "source-erf-dag.h"
#include "source-napatech.h"
#include "source-af-packet.h"
#include "source-netmap.h"
#include "source-mpipe.h"
#include "respond-reject.h"
#include "flow.h"
#include "flow-timeout.h"
#include "flow-manager.h"
#include "flow-var.h"
#include "flow-bit.h"
#include "pkt-var.h"
#include "host-bit.h"
#include "ippair.h"
#include "ippair-bit.h"
#include "host.h"
#include "unix-manager.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "util-radix-tree.h"
#include "util-host-os-info.h"
#include "util-cidr.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-time.h"
#include "util-rule-vars.h"
#include "util-classification-config.h"
#include "util-threshold-config.h"
#include "util-reference-config.h"
#include "util-profiling.h"
#include "util-magic.h"
#include "util-signal.h"
#include "util-coredump-config.h"
#include "util-decode-mime.h"
#include "defrag.h"
#include "runmodes.h"
#include "runmode-unittests.h"
#include "util-cuda.h"
#include "util-decode-asn1.h"
#include "util-debug.h"
#include "util-error.h"
#include "util-daemon.h"
#include "reputation.h"
#include "output.h"
#include "output-lua.h"
#include "output-packet.h"
#include "output-tx.h"
#include "output-file.h"
#include "output-filedata.h"
#include "output-streaming.h"
#include "util-privs.h"
#include "tmqh-packetpool.h"
#include "util-proto-name.h"
#include "util-storage.h"
#include "host-storage.h"
#include "build-info.h"
Macros
#define DEFAULT_MAX_PENDING_PACKETS 1024
Functions
SC_ATOMIC_DECLARE (unsigned int, engine_stage)
int EngineModeIsIPS (void)
int EngineModeIsIDS (void)
void EngineModeSetIPS (void)
void EngineModeSetIDS (void)
int RunmodeIsUnittests (void)
int RunmodeGetCurrent (void)
void SignalHandlerSigusr2StartingUp (int sig)
void SignalHandlerSigusr2DelayedDetect (int sig)
void SignalHandlerSigusr2SigFileStartup (int sig)
void SignalHandlerSigusr2 (int sig)
void CreateLowercaseTable ()
void GlobalInits ()
void EngineStop (void)
void EngineKill (void)
void EngineDone (void)
Used to indicate that the current task is done.
void usage (const char *progname)
void SCPrintBuildInfo (void)
void RegisterAllModules ()
TmEcode LoadYamlConfig (char *conf_filename)
int StartInternalRunMode (SCInstance *suri, int argc, char **argv)
int main (int argc, char **argv)
Variables
volatile sig_atomic_t sigint_count = 0
volatile sig_atomic_t sighup_count = 0
volatile sig_atomic_t sigterm_count = 0
volatile sig_atomic_t sigusr2_count = 0
volatile uint8_t suricata_ctl_flags = 0
int run_mode = RUNMODE_UNKNOWN
uint8_t host_mode = SURI_HOST_IS_SNIFFER_ONLY
intmax_t max_pending_packets
int g_detect_disabled = 0
int sc_set_caps
char * conf_filename = NULL
int coverage_unittests
int g_ut_modules
int g_ut_covered
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file suricata.c.
Macro Definition Documentation
#define DEFAULT_MAX_PENDING_PACKETS 1024
Definition at line 216 of file suricata.c.
Function Documentation
void CreateLowercaseTable ()
Definition at line 334 of file suricata.c.
References g_u8_lowercasetable.
Referenced by GlobalInits().
void EngineDone (void)
Used to indicate that the current task is done.
This is mainly used by pcap-file to tell it has finished to treat a pcap files when running in unix-socket mode.
Definition at line 391 of file suricata.c.
References suricata_ctl_flags, and SURICATA_DONE.
Referenced by TmThreadsSlotPktAcqLoop().
void EngineKill (void)
Definition at line 380 of file suricata.c.
References suricata_ctl_flags, and SURICATA_KILL.
Referenced by ReceiveAFPLoop(), ReceivePcapFileLoop(), TmThreadCheckThreadState(), TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
int EngineModeIsIDS (void)
Definition at line 248 of file suricata.c.
References ENGINE_MODE_IDS.
int EngineModeIsIPS (void)
Definition at line 243 of file suricata.c.
References ENGINE_MODE_IPS.
Referenced by AlertFastLogger(), and StreamTcpInitConfig().
void EngineModeSetIDS (void)
Definition at line 258 of file suricata.c.
References ENGINE_MODE_IDS.
Referenced by main().
void EngineModeSetIPS (void)
Definition at line 253 of file suricata.c.
References ENGINE_MODE_IPS.
void EngineStop (void)
Definition at line 375 of file suricata.c.
References suricata_ctl_flags, and SURICATA_STOP.
Referenced by ReceiveErfFileLoop(), and ReceivePcapFileLoop().
void GlobalInits ()
Definition at line 348 of file suricata.c.
References cond_q, CreateLowercaseTable(), data_queues, mutex_q, SCCondInit, SCLogInfo, SCMutexInit, and trans_q.
Referenced by main(), and RunUnittests().
TmEcode LoadYamlConfig (char * conf_filename)
Definition at line 919 of file suricata.c.
References ConfYamlLoadFile(), SCEnter, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by main().
int main (int argc, char ** argv)
Todo:
we need an api for these
TODO this can do into it's own func
Definition at line 2154 of file suricata.c.
References AFPPeersListClean(), AppLayerDeSetup(), AppLayerHtpPrintStats(), AppLayerRegisterGlobalCounters(), AppLayerTransactionGetActiveLogOnly(), CheckValidDaemonModes(), conf_filename, ConfDeInit(), ConfDump(), ConfGetBool(), ConfInit(), ConfSetFinal(), CoredumpLoadConfig(), CudaHandlerFreeProfiles(), SCInstance_::daemon, DEFAULT_CONF_FILE, DefragDestroy(), SCInstance_::delayed_detect, DetectEngineAddToMaster(), DetectEngineCtxInit(), DetectEngineCtxInitMinimal(), DetectEngineDeReference(), DetectEngineEnabled(), DetectEngineGetCurrent(), DetectEngineMoveToFreeList(), DetectEngineMultiTenantSetup(), DetectEnginePruneFreeList(), DetectEngineReload(), DetectEngineReloadIsStart(), DetectEngineReloadSetDone(), SCInstance_::disabled_detect, EngineModeSetIDS(), FALSE, FLOW_VERBOSE, FlowDisableFlowManagerThread(), FlowDisableFlowRecyclerThread(), FlowForceReassembly(), FlowInitConfig(), FlowManagerThreadSpawn(), FlowRecyclerThreadSpawn(), FlowShutdown(), GlobalInits(), SCInstance_::groupid, HOST_VERBOSE, HostInitConfig(), HostShutdown(), HTPAtExitPrintStats(), HTPFreeConfig(), IPPAIR_VERBOSE, IPPairInitConfig(), IPPairShutdown(), LiveDeviceListClean(), LoadYamlConfig(), MagicDeinit(), MagicInit(), OutputDeregisterAll(), OutputNotifyFileRotation(), PacketPoolDestroy(), PacketPoolInit(), PacketPoolPostRunmodes(), ParseSizeDeinit(), ParseSizeInit(), PatternMatchDefaultMatcher(), SCInstance_::pcap_dev, SCInstance_::pid_filename, profiling_rules_enabled, SCInstance_::regex_arg, RegisterAppLayerGetActiveTxIdFunc(), SCInstance_::run_mode, RUNMODE_CONF_TEST, SCInstance_::runmode_custom_mode, RUNMODE_DUMP_CONFIG, RUNMODE_ENGINE_ANALYSIS, RUNMODE_UNITTEST, RUNMODE_UNIX_SOCKET, RunModeDispatch(), RunModeInitializeOutputs(), RunModeRegisterRunModes(), RunModeShutDown(), RunUnittests(), SC_ATOMIC_CAS, SC_ATOMIC_DESTROY, SC_ATOMIC_INIT, SC_ERR_INITIALIZATION, SC_ERR_THREAD_INIT, sc_set_caps, SCAsn1LoadConfig(), SCClassConfDeinit(), SCClassConfInit(), SCDropMainThreadCaps, SCLogError, SCLogInfo, SCLogInitLogModule(), SCLogLoadConfig(), SCLogNotice, SCLogWarning, SCPidfileRemove(), SCProfilingDestroy(), SCProfilingDump(), SCProtoNameDeInit(), SCReferenceConfDeinit(), SCReferenceConfInit(), SCSetThreadName, SCInstance_::sig_file, sighup_count, SignalHandlerSigusr2(), SignalHandlerSigusr2SigFileStartup(), sigusr2_count, StartInternalRunMode(), StatsInit(), StatsReleaseResources(), StatsSetupPostConfig(), StatsSpawnThreads(), STREAM_VERBOSE, StreamTcpFreeConfig(), StreamTcpInitConfig(), SupportFastPatternForSigMatchTypes(), suricata_ctl_flags, SURICATA_DEINIT, SURICATA_INIT, SURICATA_KILL, SURICATA_RUNTIME, SURICATA_STOP, TagDestroyCtx(), TimeDeinit(), TimeInit(), TM_ECODE_DONE, TM_ECODE_FAILED, TM_ECODE_OK, TmModuleRunDeInit(), TmqhCleanup(), TmThreadCheckThreadState(), TmThreadContinueThreads(), TmThreadDisablePacketThreads(), TmThreadDisableReceiveThreads(), TmThreadKillThreads(), TmThreadWaitOnThreadInit(), TmValidateQueueState(), UNIX_CMD_TAKE_ARGS, UnixManagerThreadSpawn(), UnixSocketKillSocketThread(), SCInstance_::userid, UtilCpuPrintSummary(), UtilSignalHandlerSetup(), and SCInstance_::verbose.
void RegisterAllModules ()
Definition at line 802 of file suricata.c.
References TmModuleAlertDebugLogRegister(), TmModuleAlertFastLogRegister(), TmModuleAlertPreludeRegister(), TmModuleAlertSyslogRegister(), TmModuleDebugList(), TmModuleDecodeAFPRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFLOGRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDetectRegister(), TmModuleFiledataLoggerRegister(), TmModuleFileLoggerRegister(), TmModuleFlowManagerRegister(), TmModuleFlowRecyclerRegister(), TmModuleJsonAlertLogRegister(), TmModuleJsonDnsLogRegister(), TmModuleJsonDropLogRegister(), TmModuleJsonFileLogRegister(), TmModuleJsonFlowLogRegister(), TmModuleJsonHttpLogRegister(), TmModuleJsonNetFlowLogRegister(), TmModuleJsonSmtpLogRegister(), TmModuleJsonSshLogRegister(), TmModuleJsonStatsLogRegister(), TmModuleJsonTemplateLogRegister(), TmModuleJsonTlsLogRegister(), TmModuleLogDnsLogRegister(), TmModuleLogDropLogRegister(), TmModuleLogFileLogRegister(), TmModuleLogFilestoreRegister(), TmModuleLogHttpLogRegister(), TmModuleLogStatsLogRegister(), TmModuleLogTcpDataLogRegister(), TmModuleLogTlsLogRegister(), TmModuleLogTlsStoreRegister(), TmModuleLuaLogRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleOutputJsonRegister(), TmModulePacketLoggerRegister(), TmModulePcapLogRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveIPFWRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFLOGRegister(), TmModuleReceiveNFQRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleRespondRejectRegister(), TmModuleStatsLoggerRegister(), TmModuleStreamingLoggerRegister(), TmModuleStreamTcpRegister(), TmModuleTxLoggerRegister(), TmModuleUnified2AlertRegister(), TmModuleUnixManagerRegister(), TmModuleVerdictIPFWRegister(), and TmModuleVerdictNFQRegister().
Referenced by RunUnittests().
int RunmodeGetCurrent (void)
Definition at line 271 of file suricata.c.
References run_mode.
Referenced by RunModeGetMainMode(), and SigLoadSignatures().
int RunmodeIsUnittests (void)
Definition at line 263 of file suricata.c.
References run_mode, and RUNMODE_UNITTEST.
Referenced by AppLayerParserConfParserEnabled(), AppLayerProtoDetectConfProtoDetectionEnabled(), DetectEngineThreadCtxFree(), DetectEngineThreadCtxInit(), RegisterDNSTCPParsers(), RegisterDNSUDPParsers(), RegisterModbusParsers(), RegisterSMBParsers(), RegisterSSLParsers(), RegisterTemplateParsers(), SCClassConfInitContextAndLocalResources(), SCClassConfLoadClassficationConfigFile(), SCRConfLoadReferenceConfigFile(), and StreamTcpInitConfig().
SC_ATOMIC_DECLARE (unsigned int, engine_stage)
void SCPrintBuildInfo (void)
Definition at line 618 of file suricata.c.
References CLS, htp_get_version(), PROG_NAME, PROG_VER, strlcat(), and xstr.
Referenced by StartInternalRunMode().
void SignalHandlerSigusr2 (int sig)
SIGUSR2 handler. Just set sigusr2_count. The main loop will act on it.
Definition at line 306 of file suricata.c.
References sigusr2_count.
Referenced by main().
void SignalHandlerSigusr2DelayedDetect (int sig)
Definition at line 292 of file suricata.c.
References SC_ERR_LIVE_RULE_SWAP, and SCLogWarning.
void SignalHandlerSigusr2SigFileStartup (int sig)
Definition at line 297 of file suricata.c.
References SCLogInfo.
Referenced by main().
void SignalHandlerSigusr2StartingUp (int sig)
Definition at line 287 of file suricata.c.
References SCLogInfo.
int StartInternalRunMode (SCInstance * suri, int argc, char ** argv)
Definition at line 1851 of file suricata.c.
References SCInstance_::keyword_info, ListAppLayerProtocols(), ListKeywords(), SCInstance_::regex_arg, SCInstance_::run_mode, RUNMODE_LIST_APP_LAYERS, RUNMODE_LIST_CUDA_CARDS, RUNMODE_LIST_KEYWORDS, RUNMODE_LIST_RUNMODES, RUNMODE_LIST_UNITTEST, RUNMODE_PRINT_BUILDINFO, RUNMODE_PRINT_USAGE, RUNMODE_PRINT_VERSION, RunModeListRunmodes(), RunUnittests(), SCLogInfo, SCPrintBuildInfo(), TM_ECODE_DONE, TM_ECODE_FAILED, TM_ECODE_OK, and usage().
Referenced by main().
void usage (const char * progname)
Definition at line 521 of file suricata.c.
References PROG_NAME, PROG_VER, and xstr.
Referenced by StartInternalRunMode().
Variable Documentation
char* conf_filename = NULL
Definition at line 241 of file suricata.c.
Referenced by main().
int coverage_unittests
Definition at line 798 of file suricata.c.
Referenced by MpmRegisterTests(), SigTableRegisterTests(), and TmModuleRegisterTests().
int g_detect_disabled = 0
global indicating if detection is enabled
Definition at line 236 of file suricata.c.
int g_ut_covered
Definition at line 800 of file suricata.c.
Referenced by MpmRegisterTests(), SigTableRegisterTests(), and TmModuleRegisterTests().
int g_ut_modules
Definition at line 799 of file suricata.c.
Referenced by MpmRegisterTests(), SigTableRegisterTests(), and TmModuleRegisterTests().
uint8_t host_mode = SURI_HOST_IS_SNIFFER_ONLY
Host mode: set if box is sniffing only or is a router
Definition at line 230 of file suricata.c.
int run_mode = RUNMODE_UNKNOWN
Run mode selected
Definition at line 222 of file suricata.c.
Referenced by RunmodeGetCurrent(), RunmodeIsUnittests(), and Unified2AlertOpenFileCtx().
int sc_set_caps
set caps or not
Definition at line 239 of file suricata.c.
Referenced by main().
volatile sig_atomic_t sighup_count = 0
Definition at line 204 of file suricata.c.
Referenced by main().
volatile sig_atomic_t sigint_count = 0
Definition at line 203 of file suricata.c.
volatile sig_atomic_t sigterm_count = 0
Definition at line 205 of file suricata.c.
volatile sig_atomic_t sigusr2_count = 0
Definition at line 206 of file suricata.c.
Referenced by main(), and SignalHandlerSigusr2().
volatile uint8_t suricata_ctl_flags = 0
suricata engine control flags
Definition at line 219 of file suricata.c.
Referenced by AFPReadFromRing(), EngineDone(), EngineKill(), EngineStop(), main(), NapatechStreamLoop(), ReceiveAFPLoop(), ReceiveErfDagLoop(), ReceiveErfFileLoop(), ReceiveIPFWLoop(), ReceiveNFQLoop(), ReceivePcapFileLoop(), ReceivePcapLoop(), ReceivePfringLoop(), TmThreadCheckThreadState(), and TmThreadsSlotPktAcqLoop().