suricata: src/tm-modules.c File Reference
tm-modules.c File Reference
#include "suricata-common.h"
#include "packet-queue.h"
#include "tm-threads.h"
#include "util-debug.h"
#include "threads.h"
#include "util-logopenfile.h"
Macros
#define CASE_CODE(E) case E: return #E
Functions
void TmModuleDebugList (void)
TmModule * TmModuleGetByName (const char *name)
get a tm module ptr by name
int TmModuleGetIdByName (const char *name)
get the id of a module from it's name
TmModule * TmModuleGetById (int id)
Returns a TM Module by its id.
int TmModuleGetIDForTM (TmModule *tm)
Given a TM Module, returns its id.
void TmModuleRunInit (void)
void TmModuleRunDeInit (void)
void TmModuleRegisterTests (void)
register all unittests for the tm modules
const char * TmModuleTmmIdToString (TmmId id)
Maps the TmmId, to its string equivalent.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Thread Module functions
Definition in file tm-modules.c.
Macro Definition Documentation
#define CASE_CODE (E) case E: return #E
Definition at line 190 of file tm-modules.c.
Referenced by TmModuleTmmIdToString().
Function Documentation
void TmModuleDebugList (void)
Definition at line 33 of file tm-modules.c.
References TmModule_::Func, TmModule_::name, SCLogDebug, ThreadVars_::t, tmm_modules, and TMM_SIZE.
Referenced by RegisterAllModules().
TmModule* TmModuleGetById (int id)
Returns a TM Module by its id.
Parameters
id Id of the TM Module to return.
Return values
Pointer of the module to be returned if available; NULL if unavailable.
Definition at line 88 of file tm-modules.c.
References ThreadVars_::id, SC_ERR_TM_MODULES_ERROR, SCLogError, tmm_modules, and TMM_SIZE.
Referenced by TmThreadDisableReceiveThreads(), and TmThreadGetFirstTmSlotForPartialPattern().
TmModule* TmModuleGetByName (const char * name)
get a tm module ptr by name
Parameters
name name string
Return values
ptr to the module or NULL
Definition at line 51 of file tm-modules.c.
References TmModule_::name, ThreadVars_::t, tmm_modules, and TMM_SIZE.
Referenced by OutputFlowLogExitPrintStats(), OutputFlowLogThreadDeinit(), OutputFlowLogThreadInit(), RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), TmModuleGetIdByName(), TmThreadCreateCmdThreadByName(), and TmThreadCreateMgmtThreadByName().
int TmModuleGetIdByName (const char * name)
get the id of a module from it's name
Parameters
name registered name of the module
Return values
id the id or -1 in case of error
Definition at line 72 of file tm-modules.c.
References TmModuleGetByName(), and TmModuleGetIDForTM().
Referenced by OutputRegisterFiledataLogger(), OutputRegisterFileLogger(), OutputRegisterFlowLogger(), OutputRegisterPacketLogger(), OutputRegisterStatsLogger(), OutputRegisterStreamingLogger(), and OutputRegisterTxLogger().
int TmModuleGetIDForTM (TmModule * tm)
Given a TM Module, returns its id.
Parameters
tm Pointer to the TM Module.
Return values
id of the TM Module if available; -1 if unavailable.
Definition at line 107 of file tm-modules.c.
References TmModule_::name, ThreadVars_::t, tmm_modules, and TMM_SIZE.
Referenced by TmModuleGetIdByName().
void TmModuleRegisterTests (void)
register all unittests for the tm modules
Definition at line 163 of file tm-modules.c.
References coverage_unittests, g_ut_covered, g_ut_modules, TmModule_::name, TmModule_::RegisterTests, SC_WARN_NO_UNITTESTS, SCLogWarning, ThreadVars_::t, tmm_modules, and TMM_SIZE.
Referenced by RunUnittests().
void TmModuleRunDeInit (void)
Definition at line 144 of file tm-modules.c.
References TmModule_::DeInit, TmModule_::name, ThreadVars_::t, tmm_modules, and TMM_SIZE.
Referenced by main().
void TmModuleRunInit (void)
Definition at line 126 of file tm-modules.c.
References TmModule_::Init, TmModule_::name, ThreadVars_::t, tmm_modules, and TMM_SIZE.
const char* TmModuleTmmIdToString (TmmId id)
Maps the TmmId, to its string equivalent.
Parameters
id tmm id
Return values
string equivalent for the tmm id
Definition at line 199 of file tm-modules.c.
References CASE_CODE, TMM_ALERTDEBUGLOG, TMM_ALERTFASTLOG, TMM_ALERTFASTLOG4, TMM_ALERTFASTLOG6, TMM_ALERTPCAPINFO, TMM_ALERTPRELUDE, TMM_ALERTSYSLOG, TMM_ALERTSYSLOG4, TMM_ALERTSYSLOG6, TMM_ALERTUNIFIED2ALERT, TMM_DECODEAFP, TMM_DECODEERFDAG, TMM_DECODEERFFILE, TMM_DECODEIPFW, TMM_DECODEMPIPE, TMM_DECODENAPATECH, TMM_DECODENETMAP, TMM_DECODENFLOG, TMM_DECODENFQ, TMM_DECODEPCAP, TMM_DECODEPCAPFILE, TMM_DECODEPFRING, TMM_DETECT, TMM_DETECTLOADER, TMM_FILEDATALOGGER, TMM_FILELOG, TMM_FILELOGGER, TMM_FILESTORE, TMM_FLOWMANAGER, TMM_FLOWRECYCLER, TMM_JSONALERTLOG, TMM_JSONDNSLOG, TMM_JSONDROPLOG, TMM_JSONFILELOG, TMM_JSONFLOWLOG, TMM_JSONHTTPLOG, TMM_JSONNETFLOWLOG, TMM_JSONSMTPLOG, TMM_JSONSSHLOG, TMM_JSONSTATSLOG, TMM_JSONTEMPLATELOG, TMM_JSONTLSLOG, TMM_LOGDNSLOG, TMM_LOGDROPLOG, TMM_LOGHTTPLOG, TMM_LOGHTTPLOG4, TMM_LOGHTTPLOG6, TMM_LOGSTATSLOG, TMM_LOGTCPDATALOG, TMM_LOGTLSLOG, TMM_LOGTLSLOG4, TMM_LOGTLSLOG6, TMM_LUALOG, TMM_OUTPUTJSON, TMM_PACKETLOGGER, TMM_PCAPLOG, TMM_RECEIVEAFP, TMM_RECEIVEERFDAG, TMM_RECEIVEERFFILE, TMM_RECEIVEIPFW, TMM_RECEIVEMPIPE, TMM_RECEIVENAPATECH, TMM_RECEIVENETMAP, TMM_RECEIVENFLOG, TMM_RECEIVENFQ, TMM_RECEIVEPCAP, TMM_RECEIVEPCAPFILE, TMM_RECEIVEPFRING, TMM_RESPONDREJECT, TMM_SIZE, TMM_STATSLOGGER, TMM_STREAMINGLOGGER, TMM_STREAMTCP, TMM_TLSSTORE, TMM_TXLOGGER, TMM_UNIXMANAGER, TMM_VERDICTIPFW, and TMM_VERDICTNFQ.
Referenced by SCProfilingDumpPacketStats(), and SCProfilingInit().