suricata: src/tm-queuehandlers.c File Reference
tm-queuehandlers.c File Reference
#include "suricata-common.h"
#include "packet-queue.h"
#include "decode.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
#include "tmqh-simple.h"
#include "tmqh-nfq.h"
#include "tmqh-packetpool.h"
#include "tmqh-flow.h"
#include "tmqh-ringbuffer.h"
Functions
void TmqhSetup (void)
void TmqhCleanup (void)
Clean up registration time allocs.
Tmqh * TmqhGetQueueHandlerByName (char *name)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Master Queue Handler
Definition in file tm-queuehandlers.c.
Function Documentation
void TmqhCleanup (void)
Clean up registration time allocs.
Definition at line 51 of file tm-queuehandlers.c.
References TmqhRingBufferDestroy().
Referenced by main().
Tmqh* TmqhGetQueueHandlerByName (char * name)
Definition at line 56 of file tm-queuehandlers.c.
References TMQH_SIZE, and tmqh_table.
Referenced by TmThreadCreate(), and TmThreadKillThread().
void TmqhSetup (void)
Definition at line 39 of file tm-queuehandlers.c.
References tmqh_table, TmqhFlowRegister(), TmqhNfqRegister(), TmqhPacketpoolRegister(), TmqhRingBufferRegister(), and TmqhSimpleRegister().
Referenced by RunUnittests().