suricata: src/tm-queuehandlers.h File Reference
tm-queuehandlers.h File Reference
Data Structures
struct Tmqh_
Typedefs
typedef struct Tmqh_ Tmqh
Enumerations
enum {
TMQH_SIMPLE, TMQH_NFQ, TMQH_PACKETPOOL, TMQH_FLOW,
TMQH_RINGBUFFER_MRSW, TMQH_RINGBUFFER_SRSW, TMQH_RINGBUFFER_SRMW, TMQH_SIZE
}
Functions
void TmqhSetup (void)
void TmqhCleanup (void)
Clean up registration time allocs.
Tmqh * TmqhGetQueueHandlerByName (char *name)
Variables
Tmqh tmqh_table [TMQH_SIZE]
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file tm-queuehandlers.h.
Typedef Documentation
typedef struct Tmqh_ Tmqh
Enumeration Type Documentation
anonymous enum
Enumerator
TMQH_SIMPLE
TMQH_NFQ
TMQH_PACKETPOOL
TMQH_FLOW
TMQH_RINGBUFFER_MRSW
TMQH_RINGBUFFER_SRSW
TMQH_RINGBUFFER_SRMW
TMQH_SIZE
Definition at line 27 of file tm-queuehandlers.h.
Function Documentation
void TmqhCleanup (void)
Clean up registration time allocs.
Definition at line 51 of file tm-queuehandlers.c.
References TmqhRingBufferDestroy().
Referenced by main().
Tmqh* TmqhGetQueueHandlerByName (char * name)
Definition at line 56 of file tm-queuehandlers.c.
References TMQH_SIZE, and tmqh_table.
Referenced by TmThreadCreate(), and TmThreadKillThread().
void TmqhSetup (void)
Definition at line 39 of file tm-queuehandlers.c.
References tmqh_table, TmqhFlowRegister(), TmqhNfqRegister(), TmqhPacketpoolRegister(), TmqhRingBufferRegister(), and TmqhSimpleRegister().
Variable Documentation
Tmqh tmqh_table[TMQH_SIZE]
Definition at line 49 of file tm-queuehandlers.h.
Referenced by TmqhFlowRegister(), TmqhGetQueueHandlerByName(), TmqhNfqRegister(), TmqhPacketpoolRegister(), TmqhRingBufferRegister(), TmqhSetup(), and TmqhSimpleRegister().