suricata: src/tm-threads.c File Reference
tm-threads.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "stream.h"
#include "runmodes.h"
#include "threadvars.h"
#include "tm-queues.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "tmqh-packetpool.h"
#include "threads.h"
#include "util-debug.h"
#include "util-privs.h"
#include "util-cpu.h"
#include "util-optimize.h"
#include "util-profiling.h"
#include "util-signal.h"
#include "queue.h"
Data Structures
struct Thread_
struct Threads_
Macros
#define THREAD_KILL_MAX_WAIT_TIME 60
#define WAIT_TIME 100
#define THREAD_KILL_MAX_WAIT_TIME 60
#define WAIT_TIME 100
#define STEP 32
Typedefs
typedef struct Thread_ Thread
typedef struct Threads_ Threads
Functions
int TmThreadsCheckFlag (ThreadVars *tv, uint16_t flag)
Check if a thread flag is set.
void TmThreadsSetFlag (ThreadVars *tv, uint16_t flag)
Set a thread flag.
void TmThreadsUnsetFlag (ThreadVars *tv, uint16_t flag)
Unset a thread flag.
TmEcode TmThreadsSlotVarRun (ThreadVars *tv, Packet *p, TmSlot *slot)
Separate run function so we can call it recursively.
void * TmThreadsSlotPktAcqLoop (void *td)
void * TmThreadsSlotVar (void *td)
TmEcode TmThreadSetSlots (ThreadVars *tv, char *name, void *(*fn_p)(void *))
We set the slot functions.
ThreadVars * TmThreadsGetTVContainingSlot (TmSlot *tm_slot)
void TmSlotFree (TmSlot *tms)
void TmSlotSetFuncAppend (ThreadVars *tv, TmModule *tm, void *data)
Appends a new entry to the slots.
TmSlot * TmSlotGetSlotForTM (int tm_id)
Returns the slot holding a TM with the particular tm_id.
TmEcode TmThreadSetThreadPriority (ThreadVars *tv, int prio)
Set the thread options (thread priority).
void TmThreadSetPrio (ThreadVars *tv)
Adjusting nice value for threads.
TmEcode TmThreadSetCPUAffinity (ThreadVars *tv, uint16_t cpu)
Set the thread options (cpu affinity).
TmEcode TmThreadSetCPU (ThreadVars *tv, uint8_t type)
int TmThreadGetNbThreads (uint8_t type)
TmEcode TmThreadSetupOptions (ThreadVars *tv)
Set the thread options (cpu affinitythread). Priority should be already set by pthread_create.
ThreadVars * TmThreadCreate (char *name, char *inq_name, char *inqh_name, char *outq_name, char *outqh_name, char *slots, void *(*fn_p)(void *), int mucond)
Creates and returns the TV instance for a new thread.
ThreadVars * TmThreadCreatePacketHandler (char *name, char *inq_name, char *inqh_name, char *outq_name, char *outqh_name, char *slots)
Creates and returns a TV instance for a Packet Processing Thread. This function doesn't support custom slots, and hence shouldn't be supplied "custom" as its slot type. All PPT threads are created with a mucond(see TmThreadCreate declaration) of 0. Hence the tv conditional variables are not used to kill the thread.
ThreadVars * TmThreadCreateMgmtThread (char *name, void *(fn_p)(void *), int mucond)
Creates and returns the TV instance for a Management thread(MGMT). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
ThreadVars * TmThreadCreateMgmtThreadByName (char *name, char *module, int mucond)
Creates and returns the TV instance for a Management thread(MGMT). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
ThreadVars * TmThreadCreateCmdThreadByName (char *name, char *module, int mucond)
Creates and returns the TV instance for a Command thread (CMD). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
void TmThreadAppend (ThreadVars *tv, int type)
Appends this TV to tv_root based on its type.
void TmThreadRemove (ThreadVars *tv, int type)
Removes this TV from tv_root based on its type.
void TmThreadKillThread (ThreadVars *tv)
Kill a thread.
void TmThreadDisableReceiveThreads (void)
Disable all threads having the specified TMs.
void TmThreadDisablePacketThreads (void)
Disable all threads having the specified TMs.
TmSlot * TmThreadGetFirstTmSlotForPartialPattern (const char *tm_name)
void TmThreadKillThreadsFamily (int family)
void TmThreadKillThreads (void)
void TmThreadFree (ThreadVars *tv)
void TmThreadClearThreadsFamily (int family)
TmEcode TmThreadSpawn (ThreadVars *tv)
Spawns a thread associated with the ThreadVars instance tv.
void TmThreadSetAOF (ThreadVars *tv, uint8_t aof)
Sets the thread flags for a thread instance(tv)
void TmThreadInitMC (ThreadVars *tv)
Initializes the mutex and condition variables for this TV.
void TmThreadTestThreadUnPaused (ThreadVars *tv)
Tests if the thread represented in the arg has been unpaused or not.
void TmThreadWaitForFlag (ThreadVars *tv, uint16_t flags)
Waits till the specified flag(s) is(are) set. We don't bother if the kill flag has been set or not on the thread.
void TmThreadContinue (ThreadVars *tv)
Unpauses a thread.
void TmThreadContinueThreads ()
Unpauses all threads present in tv_root.
void TmThreadPause (ThreadVars *tv)
Pauses a thread.
void TmThreadPauseThreads ()
Pauses all threads present in tv_root.
void TmThreadCheckThreadState (void)
Used to check the thread for certain conditions of failure. If the thread has been specified to restart on failure, the thread is restarted. If the thread has been specified to gracefully shutdown the engine on failure, it does so. The global aof flag, tv_aof overrides the thread aof flag, if it holds a THV_ENGINE_EXIT;.
TmEcode TmThreadWaitOnThreadInit (void)
Used to check if all threads have finished their initialization. On finding an un-initialized thread, it waits till that thread completes its initialization, before proceeding to the next thread.
ThreadVars * TmThreadsGetCallingThread (void)
Returns the TV for the calling thread.
uint32_t TmThreadCountThreadsByTmmFlags (uint8_t flags)
returns a count of all the threads that match the flag
void TmThreadsListThreads (void)
int TmThreadsRegisterThread (ThreadVars *tv, const int type)
void TmThreadsUnregisterThread (const int id)
int TmThreadsInjectPacketsById (Packet **packets, const int id)
Variables
ThreadVars * tv_root [TVT_MAX] = { NULL }
SCMutex tv_root_lock = SCMUTEX_INITIALIZER
uint8_t tv_aof = THV_RESTART_THREAD
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Thread management functions.
Definition in file tm-threads.c.
Macro Definition Documentation
#define STEP 32
Definition at line 2093 of file tm-threads.c.
Referenced by TmThreadsRegisterThread().
#define THREAD_KILL_MAX_WAIT_TIME 60
#define THREAD_KILL_MAX_WAIT_TIME 60
#define WAIT_TIME 100
#define WAIT_TIME 100
Typedef Documentation
typedef struct Thread_ Thread
typedef struct Threads_ Threads
Function Documentation
void TmSlotFree (TmSlot * tms)
Definition at line 756 of file tm-threads.c.
References SC_ATOMIC_DESTROY, and SCFree.
TmSlot* TmSlotGetSlotForTM (int tm_id)
Returns the slot holding a TM with the particular tm_id.
Parameters
tm_id TM id of the TM whose slot has to be returned.
Return values
slots Pointer to the slot.
Definition at line 781 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, SCMutexUnlock, TmSlot_::slot_next, TmSlot_::tm_id, ThreadVars_::tm_slots, tv_root_lock, and TVT_MAX.
void TmSlotSetFuncAppend (ThreadVars * tv, TmModule * tm, void * data)
Appends a new entry to the slots.
Parameters
tv TV the slot is attached to.
tm TM to append.
data Data to be passed on to the slot init function.
Definition at line 769 of file tm-threads.c.
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), SetupOutputs(), TmThreadCreateCmdThreadByName(), and TmThreadCreateMgmtThreadByName().
void TmThreadAppend (ThreadVars * tv, int type)
Appends this TV to tv_root based on its type.
Parameters
type holds the type this TV belongs to.
Definition at line 1265 of file tm-threads.c.
References ThreadVars_::next, ThreadVars_::prev, SCMutexLock, SCMutexUnlock, tv_root_lock, and type.
Referenced by TmThreadSpawn().
void TmThreadCheckThreadState (void)
Used to check the thread for certain conditions of failure. If the thread has been specified to restart on failure, the thread is restarted. If the thread has been specified to gracefully shutdown the engine on failure, it does so. The global aof flag, tv_aof overrides the thread aof flag, if it holds a THV_ENGINE_EXIT;.
Definition at line 1916 of file tm-threads.c.
References ThreadVars_::aof, EngineKill(), ThreadVars_::next, SCMutexLock, SCMutexUnlock, suricata_ctl_flags, SURICATA_KILL, SURICATA_STOP, ThreadVars_::t, THV_DEINIT, THV_ENGINE_EXIT, THV_FAILED, TmThreadsCheckFlag(), TmThreadsSetFlag(), tv_aof, tv_root_lock, and TVT_MAX.
Referenced by main().
void TmThreadClearThreadsFamily (int family)
Definition at line 1664 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, SCMutexUnlock, TmThreadFree(), tv_root_lock, and TVT_MAX.
void TmThreadContinue (ThreadVars * tv)
Unpauses a thread.
Parameters
tv Pointer to a TV instance that has to be unpaused
Definition at line 1819 of file tm-threads.c.
References THV_PAUSE, and TmThreadsUnsetFlag().
Referenced by TmThreadContinueDetectLoaderThreads(), and TmThreadContinueThreads().
void TmThreadContinueThreads (void)
Unpauses all threads present in tv_root.
Definition at line 1829 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, SCMutexUnlock, TmThreadContinue(), tv_root_lock, and TVT_MAX.
Referenced by main().
uint32_t TmThreadCountThreadsByTmmFlags (uint8_t flags)
returns a count of all the threads that match the flag
Definition at line 2040 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, SCMutexUnlock, ThreadVars_::tmm_flags, tv_root_lock, and TVT_MAX.
Referenced by PacketPoolPostRunmodes().
ThreadVars* TmThreadCreate (char * name, char * inq_name, char * inqh_name, char * outq_name, char * outqh_name, char * slots, void *(*)(void *) fn_p, int mucond)
Creates and returns the TV instance for a new thread.
Parameters
name Name of this TV instance
inq_name Incoming queue name
inqh_name Incoming queue handler name as set by TmqhSetup()
outq_name Outgoing queue name
outqh_name Outgoing queue handler as set by TmqhSetup()
slots String representation for the slot function to be used
fn_p Pointer to function when "slots" is of type "custom"
mucond Flag to indicate whether to initialize the condition and the mutex variables for this newly created TV.
Return values
the newly created TV instance, or NULL on error
Definition at line 1026 of file tm-threads.c.
References ThreadVars_::aof, Tmqh_::InHandler, ThreadVars_::inq, Tmqh_::InShutdownHandler, ThreadVars_::InShutdownHandler, StatsPublicThreadContext_::m, Tmqh_::name, ThreadVars_::name, ThreadVars_::outctx, Tmqh_::OutHandler, Tmqh_::OutHandlerCtxSetup, ThreadVars_::outq, ThreadVars_::outqh_name, ThreadVars_::perf_public_ctx, Tmq_::reader_cnt, SC_ATOMIC_INIT, SC_ERR_THREAD_CREATE, SCFree, SCLogDebug, SCLogError, SCMalloc, SCMutexInit, THV_PAUSE, THV_RESTART_THREAD, THV_USE, TM_ECODE_OK, TmqCreateQueue(), TmqGetQueueByName(), ThreadVars_::tmqh_in, ThreadVars_::tmqh_out, TmqhGetQueueHandlerByName(), TmThreadInitMC(), TmThreadSetSlots(), TmThreadsSetFlag(), unlikely, and Tmq_::writer_cnt.
Referenced by TmThreadCreateCmdThreadByName(), TmThreadCreateMgmtThread(), TmThreadCreateMgmtThreadByName(), and TmThreadCreatePacketHandler().
ThreadVars* TmThreadCreateCmdThreadByName (char * name, char * module, int mucond)
Creates and returns the TV instance for a Command thread (CMD). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
Parameters
name Name of this TV instance
module Name of TmModule with COMMAND flag set.
mucond Flag to indicate whether to initialize the condition and the mutex variables for this newly created TV.
Return values
the newly created TV instance, or NULL on error
Definition at line 1239 of file tm-threads.c.
References ThreadVars_::id, m, MANAGEMENT_CPU_SET, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreate(), TmThreadSetCPU(), TmThreadsRegisterThread(), TVT_CMD, and ThreadVars_::type.
Referenced by DetectLoaderThreadSpawn().
ThreadVars* TmThreadCreateMgmtThread (char * name, void * fn_p)(void *, int mucond)
Creates and returns the TV instance for a Management thread(MGMT). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
Parameters
name Name of this TV instance
fn_p Pointer to function when "slots" is of type "custom"
mucond Flag to indicate whether to initialize the condition and the mutex variables for this newly created TV.
Return values
the newly created TV instance, or NULL on error
Definition at line 1178 of file tm-threads.c.
References ThreadVars_::id, MANAGEMENT_CPU_SET, TmThreadCreate(), TmThreadSetCPU(), TmThreadsRegisterThread(), TVT_MGMT, and ThreadVars_::type.
Referenced by StatsSpawnThreads().
ThreadVars* TmThreadCreateMgmtThreadByName (char * name, char * module, int mucond)
Creates and returns the TV instance for a Management thread(MGMT). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
Parameters
name Name of this TV instance
module Name of TmModule with MANAGEMENT flag set.
mucond Flag to indicate whether to initialize the condition and the mutex variables for this newly created TV.
Return values
the newly created TV instance, or NULL on error
Definition at line 1206 of file tm-threads.c.
References ThreadVars_::id, m, MANAGEMENT_CPU_SET, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreate(), TmThreadSetCPU(), TmThreadsRegisterThread(), TVT_MGMT, and ThreadVars_::type.
Referenced by FlowManagerThreadSpawn(), and FlowRecyclerThreadSpawn().
ThreadVars* TmThreadCreatePacketHandler (char * name, char * inq_name, char * inqh_name, char * outq_name, char * outqh_name, char * slots)
Creates and returns a TV instance for a Packet Processing Thread. This function doesn't support custom slots, and hence shouldn't be supplied "custom" as its slot type. All PPT threads are created with a mucond(see TmThreadCreate declaration) of 0. Hence the tv conditional variables are not used to kill the thread.
Parameters
name Name of this TV instance
inq_name Incoming queue name
inqh_name Incoming queue handler name as set by TmqhSetup()
outq_name Outgoing queue name
outqh_name Outgoing queue handler as set by TmqhSetup()
slots String representation for the slot function to be used
Return values
the newly created TV instance, or NULL on error
Definition at line 1148 of file tm-threads.c.
References ThreadVars_::id, TmThreadCreate(), TmThreadsRegisterThread(), TVT_PPT, and ThreadVars_::type.
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), and RunModeSetLiveCaptureAutoFp().
void TmThreadDisablePacketThreads (void)
Disable all threads having the specified TMs.
Definition at line 1510 of file tm-threads.c.
References PacketQueue_::cond_q, data_queues, Tmq_::id, ThreadVars_::inq, PacketQueue_::len, Tmq_::name, ThreadVars_::name, ThreadVars_::next, Tmq_::q_type, Tmq_::reader_cnt, SC_ERR_FATAL, SCCondSignal, SCLogDebug, SCLogError, SCMutexLock, SCMutexUnlock, THREAD_KILL_MAX_WAIT_TIME, THV_KILL, THV_RUNNING_DONE, TmThreadsCheckFlag(), TmThreadsSetFlag(), trans_q, tv_root_lock, TVT_PPT, WAIT_TIME, and Tmq_::writer_cnt.
Referenced by main().
void TmThreadDisableReceiveThreads (void)
Disable all threads having the specified TMs.
Breaks out of the packet acquisition loop, and bumps into the 'flow loop', where it will process packets from the flow engine's shutdown handling.
Definition at line 1418 of file tm-threads.c.
References PacketQueue_::cond_q, data_queues, TmModule_::flags, Tmq_::id, ThreadVars_::inq, PacketQueue_::len, Tmq_::name, ThreadVars_::name, ThreadVars_::next, Tmq_::q_type, Tmq_::reader_cnt, SC_ERR_FATAL, SCCondSignal, SCLogDebug, SCLogError, SCMutexLock, SCMutexUnlock, TmSlot_::slot_next, THREAD_KILL_MAX_WAIT_TIME, THV_FLOW_LOOP, THV_KILL_PKTACQ, TM_FLAG_RECEIVE_TM, TmSlot_::tm_id, ThreadVars_::tm_slots, TmModuleGetById(), TmThreadsCheckFlag(), TmThreadsSetFlag(), trans_q, tv_root_lock, TVT_PPT, WAIT_TIME, and Tmq_::writer_cnt.
Referenced by main().
void TmThreadFree (ThreadVars * tv)
Definition at line 1642 of file tm-threads.c.
References ThreadVars_::id, ThreadVars_::name, SCFree, SCLogDebug, TmSlot_::slot_next, StatsThreadCleanup(), ThreadVars_::tm_slots, and TmThreadsUnregisterThread().
Referenced by TmThreadClearThreadsFamily().
TmSlot* TmThreadGetFirstTmSlotForPartialPattern (const char * tm_name)
Definition at line 1582 of file tm-threads.c.
References TmModule_::name, ThreadVars_::next, SCMutexLock, SCMutexUnlock, TmSlot_::slot_next, TmSlot_::tm_id, ThreadVars_::tm_slots, TmModuleGetById(), tv_root_lock, and TVT_PPT.
int TmThreadGetNbThreads (uint8_t type)
Definition at line 951 of file tm-threads.c.
References MAX_CPU_SET, ThreadsAffinityType_::nb_threads, SC_ERR_INVALID_ARGUMENT, SCLogError, thread_affinity, and type.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeSetIPSAutoFp(), and RunModeSetLiveCaptureAutoFp().
void TmThreadInitMC (ThreadVars * tv)
Initializes the mutex and condition variables for this TV.
It can be used by a thread to control a wait loop that can also be influenced by other threads.
Parameters
tv Pointer to a TV instance
Definition at line 1751 of file tm-threads.c.
References ThreadVars_::ctrl_cond, ThreadVars_::ctrl_mutex, SC_ERR_FATAL, SCCtrlCondInit, SCCtrlMutexInit, SCLogError, and SCMalloc.
Referenced by TmThreadCreate().
void TmThreadKillThread (ThreadVars * tv)
Kill a thread.
Parameters
tv A ThreadVars instance corresponding to the thread that has to be killed.
Definition at line 1339 of file tm-threads.c.
References BUG_ON, PacketQueue_::cond_q, ThreadVars_::ctrl_cond, data_queues, Tmq_::id, ThreadVars_::inq, ThreadVars_::InShutdownHandler, PacketQueue_::len, Tmq_::name, ThreadVars_::name, ThreadVars_::outctx, Tmqh_::OutHandlerCtxFree, ThreadVars_::outqh_name, Tmq_::q_type, Tmq_::reader_cnt, SCCondSignal, SCLogDebug, ThreadVars_::t, THV_CLOSED, THV_DEINIT, THV_KILL, TmqhGetQueueHandlerByName(), TmThreadsCheckFlag(), TmThreadsSetFlag(), trans_q, and Tmq_::writer_cnt.
Referenced by TmThreadKillThreadsFamily().
void TmThreadKillThreads (void)
Definition at line 1631 of file tm-threads.c.
References TmThreadKillThreadsFamily(), and TVT_MAX.
Referenced by main().
void TmThreadKillThreadsFamily (int family)
Definition at line 1613 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, SCMutexUnlock, TmThreadKillThread(), tv_root_lock, and TVT_MAX.
Referenced by TmThreadKillThreads().
void TmThreadPause (ThreadVars * tv)
Pauses a thread.
Parameters
tv Pointer to a TV instance that has to be paused
Definition at line 1852 of file tm-threads.c.
References THV_PAUSE, and TmThreadsSetFlag().
Referenced by TmThreadPauseThreads().
void TmThreadPauseThreads (void)
Pauses all threads present in tv_root.
Definition at line 1862 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, SCMutexUnlock, TmThreadPause(), TmThreadsListThreads(), tv_root_lock, and TVT_MAX.
void TmThreadRemove (ThreadVars * tv, int type)
Removes this TV from tv_root based on its type.
Parameters
tv The tv instance to remove from the global tv list.
type Holds the type this TV belongs to.
Definition at line 1303 of file tm-threads.c.
References ThreadVars_::next, ThreadVars_::prev, SCMutexLock, SCMutexUnlock, tv_root_lock, and type.
int TmThreadsCheckFlag (ThreadVars * tv, uint16_t flag)
Check if a thread flag is set.
Return values
1 flag is set.
0 flag is not set.
Definition at line 92 of file tm-threads.c.
References SC_ATOMIC_GET.
Referenced by FlowDisableFlowManagerThread(), FlowDisableFlowRecyclerThread(), IPFWSetVerdict(), TmThreadCheckThreadState(), TmThreadDisablePacketThreads(), TmThreadDisableReceiveThreads(), TmThreadKillThread(), TmThreadsSlotPktAcqLoop(), TmThreadsSlotVar(), TmThreadTestThreadUnPaused(), TmThreadWaitForFlag(), and TmThreadWaitOnThreadInit().
void TmThreadSetAOF (ThreadVars * tv, uint8_t aof)
Sets the thread flags for a thread instance(tv)
Parameters
tv Pointer to the thread instance for which the flag has to be set
flags Holds the thread state this thread instance has to be set to Sets the aof(Action on failure) for a thread instance(tv)
tv Pointer to the thread instance for which the aof has to be set
aof Holds the aof this thread instance has to be set to
Definition at line 1735 of file tm-threads.c.
References ThreadVars_::aof.
TmEcode TmThreadSetCPU (ThreadVars * tv, uint8_t type)
Definition at line 935 of file tm-threads.c.
References ThreadVars_::cpu_affinity, MAX_CPU_SET, SC_ERR_INVALID_ARGUMENT, SCLogError, THREAD_SET_AFFTYPE, ThreadVars_::thread_setup_flags, threading_set_cpu_affinity, TM_ECODE_FAILED, TM_ECODE_OK, and type.
Referenced by RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), TmThreadCreateCmdThreadByName(), TmThreadCreateMgmtThread(), and TmThreadCreateMgmtThreadByName().
TmEcode TmThreadSetCPUAffinity (ThreadVars * tv, uint16_t cpu)
Set the thread options (cpu affinity).
Parameters
tv pointer to the ThreadVars to setup the affinity.
cpu cpu on which affinity is set.
Return values
TM_ECODE_OK
Definition at line 926 of file tm-threads.c.
References ThreadVars_::cpu_affinity, THREAD_SET_AFFINITY, ThreadVars_::thread_setup_flags, and TM_ECODE_OK.
Referenced by RunModeErfFileAutoFp().
void TmThreadSetPrio (ThreadVars * tv)
Adjusting nice value for threads.
Definition at line 891 of file tm-threads.c.
References ThreadVars_::name, SC_ERR_THREAD_NICE_PRIO, SCEnter, SCLogDebug, SCLogError, SCReturn, and ThreadVars_::thread_priority.
Referenced by TmThreadSetupOptions().
TmEcode TmThreadSetSlots (ThreadVars * tv, char * name, void *(*)(void *) fn_p)
We set the slot functions.
Parameters
tv Pointer to the TV to set the slot function for.
name Name of the slot variant.
fn_p Pointer to a custom slot function. Used only if slot variant "name" is "custom".
Return values
TmEcode TM_ECODE_OK on success; TM_ECODE_FAILED on failure.
Definition at line 641 of file tm-threads.c.
References TM_ECODE_FAILED, TM_ECODE_OK, ThreadVars_::tm_func, TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
Referenced by TmThreadCreate().
TmEcode TmThreadSetThreadPriority (ThreadVars * tv, int prio)
Set the thread options (thread priority).
Parameters
tv Pointer to the ThreadVars to setup the thread priority.
Return values
TM_ECODE_OK.
Definition at line 880 of file tm-threads.c.
References ThreadVars_::thread_priority, THREAD_SET_PRIORITY, ThreadVars_::thread_setup_flags, and TM_ECODE_OK.
Referenced by RunModeErfFileAutoFp().
TmEcode TmThreadSetupOptions (ThreadVars * tv)
Set the thread options (cpu affinitythread). Priority should be already set by pthread_create.
Parameters
tv pointer to the ThreadVars of the calling thread.
Definition at line 967 of file tm-threads.c.
References AffinityGetNextCPU(), ThreadVars_::cpu_affinity, ThreadsAffinityType_::cpu_set, EXCLUSIVE_AFFINITY, ThreadsAffinityType_::hiprio_cpu, ThreadsAffinityType_::lowprio_cpu, ThreadsAffinityType_::medprio_cpu, ThreadsAffinityType_::mode_flag, ThreadVars_::name, ThreadsAffinityType_::prio, PRIO_HIGH, PRIO_LOW, PRIO_MEDIUM, SCGetThreadIdLong, SCLogInfo, thread_affinity, ThreadVars_::thread_priority, THREAD_SET_AFFINITY, THREAD_SET_AFFTYPE, THREAD_SET_PRIORITY, ThreadVars_::thread_setup_flags, TM_ECODE_OK, and TmThreadSetPrio().
Referenced by TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
ThreadVars* TmThreadsGetCallingThread (void)
Returns the TV for the calling thread.
Return values
tv Pointer to the ThreadVars instance for the calling thread; NULL on no match
Definition at line 2013 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, SCMutexUnlock, ThreadVars_::t, tv_root_lock, and TVT_MAX.
ThreadVars* TmThreadsGetTVContainingSlot (TmSlot * tm_slot)
Definition at line 676 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, SCMutexUnlock, TmSlot_::slot_next, ThreadVars_::tm_slots, tv_root_lock, and TVT_MAX.
int TmThreadsInjectPacketsById (Packet ** packets, const int id)
Return values
r 1 if packet was accepted, 0 otherwise
Note
if packet was not accepted, it's still the responsibility of the caller.
Definition at line 2178 of file tm-threads.c.
References PacketQueue_::cond_q, Tmq_::id, ThreadVars_::inq, PacketQueue_::mutex_q, PacketEnqueue(), SCCondSignal, SCMutexLock, SCMutexUnlock, ThreadVars_::stream_pq, Threads_::threads, Threads_::threads_size, trans_q, and Thread_::tv.
void TmThreadsListThreads (void)
Definition at line 2076 of file tm-threads.c.
References Thread_::in_use, Thread_::name, SCLogInfo, SCMutexLock, SCMutexUnlock, Threads_::threads, Threads_::threads_size, Thread_::tv, and Thread_::type.
Referenced by TmThreadPauseThreads().
TmEcode TmThreadSpawn (ThreadVars * tv)
Spawns a thread associated with the ThreadVars instance tv.
Return values
TM_ECODE_OK on success and TM_ECODE_FAILED on failure
Definition at line 1689 of file tm-threads.c.
References ThreadVars_::t, THV_INIT_DONE, THV_RUNNING_DONE, TM_ECODE_FAILED, TM_ECODE_OK, ThreadVars_::tm_func, TmThreadAppend(), TmThreadWaitForFlag(), and ThreadVars_::type.
Referenced by DetectLoaderThreadSpawn(), FlowManagerThreadSpawn(), FlowRecyclerThreadSpawn(), RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), and StatsSpawnThreads().
int TmThreadsRegisterThread (ThreadVars * tv, const int type)
Return values
id thread id, or 0 if not found
Definition at line 2097 of file tm-threads.c.
References BUG_ON, Thread_::in_use, ThreadVars_::name, Thread_::name, SCCalloc, SCMutexLock, SCMutexUnlock, SCRealloc, STEP, Threads_::threads, Threads_::threads_size, Thread_::tv, type, and Thread_::type.
Referenced by TmThreadCreateCmdThreadByName(), TmThreadCreateMgmtThread(), TmThreadCreateMgmtThreadByName(), and TmThreadCreatePacketHandler().
void TmThreadsSetFlag (ThreadVars * tv, uint16_t flag)
Set a thread flag.
Definition at line 100 of file tm-threads.c.
References SC_ATOMIC_OR.
Referenced by FlowDisableFlowManagerThread(), FlowDisableFlowRecyclerThread(), TmThreadCheckThreadState(), TmThreadCreate(), TmThreadDisablePacketThreads(), TmThreadDisableReceiveThreads(), TmThreadKillThread(), TmThreadPause(), TmThreadsSlotPktAcqLoop(), TmThreadsSlotVar(), and TmThreadsSlotVarRun().
void* TmThreadsSlotPktAcqLoop (void * td)
Definition at line 255 of file tm-threads.c.
References BUG_ON, EngineDone(), EngineKill(), Tmq_::id, ThreadVars_::inq, PacketQueue_::len, PacketQueue_::mutex_q, ThreadVars_::name, PacketPoolDestroy(), PacketPoolInit(), TmSlot_::PktAcqLoop, SC_ATOMIC_GET, SC_ATOMIC_SET, SC_ERR_FATAL, SC_ERR_THREAD_INIT, SCDropCaps, SCLogDebug, SCLogError, SCLogWarning, SCMutexInit, SCSetThreadName, TmSlot_::slot_initdata, TmSlot_::slot_next, TmSlot_::slot_post_pq, TmSlot_::slot_pre_pq, TmSlot_::SlotThreadDeinit, TmSlot_::SlotThreadExitPrintStats, TmSlot_::SlotThreadInit, StatsSetupPrivate(), StatsSyncCounters, ThreadVars_::stream_pq, suricata_ctl_flags, ThreadVars_::thread_setup_flags, THV_CLOSED, THV_DEINIT, THV_FLOW_LOOP, THV_INIT_DONE, THV_KILL_PKTACQ, THV_PAUSE, THV_PAUSED, THV_RUNNING_DONE, TM_ECODE_DONE, TM_ECODE_FAILED, TM_ECODE_OK, TmSlot_::tm_id, ThreadVars_::tm_slots, TMM_STREAMTCP, ThreadVars_::tmqh_in, ThreadVars_::tmqh_out, TmThreadsCheckFlag(), TmThreadSetupOptions(), TmThreadsSetFlag(), TmThreadsUnsetFlag(), TmThreadTestThreadUnPaused(), TmThreadWaitForFlag(), trans_q, and UtilSignalBlock().
Referenced by TmThreadSetSlots().
void* TmThreadsSlotVar (void * td)
Todo:
Only the first "slot" currently makes the "post_pq" available to the thread module.
Definition at line 392 of file tm-threads.c.
References BUG_ON, EngineKill(), Tmq_::id, ThreadVars_::inq, PacketQueue_::len, PacketQueue_::mutex_q, ThreadVars_::name, PacketDequeue(), PacketPoolDestroy(), PacketPoolInitEmpty(), SC_ATOMIC_GET, SC_ATOMIC_SET, SC_ERR_THREAD_INIT, SCDropCaps, SCLogDebug, SCLogWarning, SCMutexInit, SCMutexLock, SCMutexUnlock, SCSetThreadName, TmSlot_::slot_initdata, TmSlot_::slot_next, TmSlot_::slot_post_pq, TmSlot_::slot_pre_pq, TmSlot_::SlotThreadDeinit, TmSlot_::SlotThreadExitPrintStats, TmSlot_::SlotThreadInit, StatsSetupPrivate(), StatsSyncCounters, ThreadVars_::stream_pq, ThreadVars_::thread_setup_flags, THV_CLOSED, THV_DEINIT, THV_FAILED, THV_INIT_DONE, THV_KILL, THV_PAUSE, THV_PAUSED, THV_RUNNING_DONE, TM_ECODE_FAILED, TM_ECODE_OK, TmSlot_::tm_id, ThreadVars_::tm_slots, TMM_STREAMTCP, ThreadVars_::tmqh_in, ThreadVars_::tmqh_out, TmqhOutputPacketpool(), TmqhReleasePacketsToPacketPool(), TmThreadsCheckFlag(), TmThreadSetupOptions(), TmThreadsSetFlag(), TmThreadsSlotVarRun(), TmThreadsUnsetFlag(), TmThreadTestThreadUnPaused(), TmThreadWaitForFlag(), PacketQueue_::top, trans_q, and UtilSignalBlock().
Referenced by TmThreadSetSlots().
TmEcode TmThreadsSlotVarRun (ThreadVars * tv, Packet * p, TmSlot * slot)
Separate run function so we can call it recursively.
Todo:
Deal with post_pq for slots beyond the first.
Definition at line 118 of file tm-threads.c.
References TmSlot_::id, PacketQueue_::mutex_q, PACKET_PROFILING_TMM_END, PACKET_PROFILING_TMM_START, PacketDequeue(), SC_ATOMIC_GET, SCMutexLock, SCMutexUnlock, TmSlot_::slot_next, TmSlot_::slot_post_pq, TmSlot_::slot_pre_pq, THV_FAILED, TM_ECODE_FAILED, TM_ECODE_OK, TmSlot_::tm_id, ThreadVars_::tmqh_out, TmqhOutputPacketpool(), TmqhReleasePacketsToPacketPool(), TmThreadsSetFlag(), TmThreadsSlotVarRun(), PacketQueue_::top, and unlikely.
Referenced by TmThreadsSlotVar(), and TmThreadsSlotVarRun().
void TmThreadsUnregisterThread (const int id)
Definition at line 2140 of file tm-threads.c.
References Thread_::in_use, SCFree, SCMutexLock, SCMutexUnlock, Threads_::threads, Threads_::threads_cnt, and Threads_::threads_size.
Referenced by TmThreadFree().
void TmThreadsUnsetFlag (ThreadVars * tv, uint16_t flag)
Unset a thread flag.
Definition at line 108 of file tm-threads.c.
References SC_ATOMIC_AND.
Referenced by TmThreadContinue(), TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
void TmThreadTestThreadUnPaused (ThreadVars * tv)
Tests if the thread represented in the arg has been unpaused or not.
   The function would return if the thread tv has been unpaused or if the
   kill flag for the thread has been set.
Parameters
tv Pointer to the TV instance.
Definition at line 1787 of file tm-threads.c.
References THV_KILL, THV_PAUSE, and TmThreadsCheckFlag().
Referenced by TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
void TmThreadWaitForFlag (ThreadVars * tv, uint16_t flags)
Waits till the specified flag(s) is(are) set. We don't bother if the kill flag has been set or not on the thread.
Parameters
tv Pointer to the TV instance.
Definition at line 1805 of file tm-threads.c.
References TmThreadsCheckFlag().
Referenced by TmThreadSpawn(), TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
TmEcode TmThreadWaitOnThreadInit (void)
Used to check if all threads have finished their initialization. On finding an un-initialized thread, it waits till that thread completes its initialization, before proceeding to the next thread.
Return values
TM_ECODE_OK all initialized properly
TM_ECODE_FAILED failure
Definition at line 1958 of file tm-threads.c.
References FALSE, ThreadVars_::name, ThreadVars_::next, SC_ERR_THREAD_INIT, SCLogError, SCLogNotice, SCMutexLock, SCMutexUnlock, THV_CLOSED, THV_FAILED, THV_INIT_DONE, TM_ECODE_FAILED, TM_ECODE_OK, TmThreadsCheckFlag(), TRUE, tv_root_lock, TVT_MAX, TVT_MGMT, and TVT_PPT.
Referenced by main().
Variable Documentation
uint8_t tv_aof = THV_RESTART_THREAD
Definition at line 84 of file tm-threads.c.
Referenced by TmThreadCheckThreadState().
ThreadVars* tv_root[TVT_MAX] = { NULL }
Definition at line 77 of file tm-threads.c.
Referenced by FlowDisableFlowManagerThread(), FlowDisableFlowRecyclerThread(), TmThreadContinueDetectLoaderThreads(), and TmThreadWakeupDetectLoaderThreads().
SCMutex tv_root_lock = SCMUTEX_INITIALIZER
Definition at line 80 of file tm-threads.c.
Referenced by FlowDisableFlowManagerThread(), FlowDisableFlowRecyclerThread(), TmSlotGetSlotForTM(), TmThreadAppend(), TmThreadCheckThreadState(), TmThreadClearThreadsFamily(), TmThreadContinueDetectLoaderThreads(), TmThreadContinueThreads(), TmThreadCountThreadsByTmmFlags(), TmThreadDisablePacketThreads(), TmThreadDisableReceiveThreads(), TmThreadGetFirstTmSlotForPartialPattern(), TmThreadKillThreadsFamily(), TmThreadPauseThreads(), TmThreadRemove(), TmThreadsGetCallingThread(), TmThreadsGetTVContainingSlot(), TmThreadWaitOnThreadInit(), and TmThreadWakeupDetectLoaderThreads().