suricata: src/tmqh-simple.c File Reference
tmqh-simple.c File Reference
#include "suricata.h"
#include "packet-queue.h"
#include "decode.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
Functions
Packet * TmqhInputSimple (ThreadVars *t)
void TmqhOutputSimple (ThreadVars *t, Packet *p)
void TmqhInputSimpleShutdownHandler (ThreadVars *)
void TmqhSimpleRegister (void)
SCDQGenericQData * TmqhInputSimpleOnQ (SCDQDataQueue *q)
Public version of TmqhInputSimple from the tmqh-simple queue handler, except that it is a generic version that is directly tied to a "SCDQDataQueue" instance(sent as an arg).
void TmqhOutputSimpleOnQ (SCDQDataQueue *q, SCDQGenericQData *data)
Public version of TmqhOutputSimple from the tmqh-simple queue handler, except that it is a generic version that is directly tied to a SCDQDataQueue instance(sent as an arg).
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Simple queue handler
Definition in file tmqh-simple.c.
Function Documentation
Packet * TmqhInputSimple (ThreadVars * t)
Definition at line 46 of file tmqh-simple.c.
References PacketQueue_::cond_q, Tmq_::id, ThreadVars_::inq, PacketQueue_::len, PacketQueue_::mutex_q, PacketDequeue(), SCCondWait, SCMutexLock, SCMutexUnlock, StatsSyncCountersIfSignalled, and trans_q.
Referenced by TmqhSimpleRegister().
SCDQGenericQData* TmqhInputSimpleOnQ (SCDQDataQueue * q)
Public version of TmqhInputSimple from the tmqh-simple queue handler, except that it is a generic version that is directly tied to a "SCDQDataQueue" instance(sent as an arg).
   Retrieves a data_instance from the queue.  If the queue is empty, it
   waits on the queue, till a data_instance is enqueued into the queue
   by some other module.
   All references to "data_instance" means a reference to a data structure
   instance that implements the template "struct SCDQGenericQData_".
Parameters
q The SCDQDataQueue instance to wait on.
Return values
p The returned packet from the queue.
data The returned data_instance from the queue.
Definition at line 113 of file tmqh-simple.c.
References data, SCCondWait, SCDQDataDequeue(), SCMutexLock, and SCMutexUnlock.
void TmqhInputSimpleShutdownHandler (ThreadVars * tv)
Definition at line 70 of file tmqh-simple.c.
References PacketQueue_::cond_q, Tmq_::id, ThreadVars_::inq, Tmq_::reader_cnt, SCCondSignal, trans_q, and Tmq_::writer_cnt.
Referenced by TmqhSimpleRegister().
void TmqhOutputSimple (ThreadVars * t, Packet * p)
Definition at line 82 of file tmqh-simple.c.
References PacketQueue_::cond_q, Packet_::flags, Tmq_::id, PacketQueue_::mutex_q, ThreadVars_::outq, PacketEnqueue(), PKT_ALLOC, Packet_::root, SCCondSignal, SCLogDebug, SCMutexLock, SCMutexUnlock, and trans_q.
Referenced by TmqhSimpleRegister().
void TmqhOutputSimpleOnQ (SCDQDataQueue * q, SCDQGenericQData * data)
Public version of TmqhOutputSimple from the tmqh-simple queue handler, except that it is a generic version that is directly tied to a SCDQDataQueue instance(sent as an arg).
   Pumps out a data_instance into the queue.  If the queue is empty, it
   waits on the queue, till a data_instance is enqueued into the queue.
   All references to "data_instance" means a reference to a data structure
   instance that implements the template "struct SCDQGenericQData_".
Parameters
q The SCDQDataQueue instance to pump the data into.
data The data instance to be enqueued.
Definition at line 147 of file tmqh-simple.c.
References SCCondSignal, SCDQDataEnqueue(), SCMutexLock, and SCMutexUnlock.
void TmqhSimpleRegister (void)
Definition at line 38 of file tmqh-simple.c.
References Tmqh_::InHandler, Tmqh_::InShutdownHandler, Tmqh_::name, Tmqh_::OutHandler, TMQH_SIMPLE, tmqh_table, TmqhInputSimple(), TmqhInputSimpleShutdownHandler(), and TmqhOutputSimple().
Referenced by TmqhSetup().