suricata: src/tmqh-ringbuffer.c File Reference
tmqh-ringbuffer.c File Reference
#include "suricata.h"
#include "packet-queue.h"
#include "decode.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
#include "util-ringbuffer.h"
Functions
Packet * TmqhInputRingBufferMrSw (ThreadVars *t)
void TmqhOutputRingBufferMrSw (ThreadVars *t, Packet *p)
Packet * TmqhInputRingBufferSrSw (ThreadVars *t)
void TmqhOutputRingBufferSrSw (ThreadVars *t, Packet *p)
Packet * TmqhInputRingBufferSrMw (ThreadVars *t)
void TmqhOutputRingBufferSrMw (ThreadVars *t, Packet *p)
void TmqhInputRingBufferShutdownHandler (ThreadVars *)
void TmqhRingBufferRegister (void)
TmqhRingBufferRegister .
void TmqhRingBufferDestroy (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
RingBuffer queue handler
Definition in file tmqh-ringbuffer.c.
Function Documentation
Packet * TmqhInputRingBufferMrSw (ThreadVars * t)
Definition at line 101 of file tmqh-ringbuffer.c.
References Tmq_::id, ThreadVars_::inq, RingBufferMrSw8Get(), and StatsSyncCountersIfSignalled.
Referenced by TmqhRingBufferRegister().
void TmqhInputRingBufferShutdownHandler (ThreadVars * tv)
Definition at line 87 of file tmqh-ringbuffer.c.
References Tmq_::id, ThreadVars_::inq, and RingBuffer8Shutdown().
Referenced by TmqhRingBufferRegister().
Packet * TmqhInputRingBufferSrMw (ThreadVars * t)
Definition at line 135 of file tmqh-ringbuffer.c.
References Tmq_::id, ThreadVars_::inq, RingBufferSrMw8Get(), and StatsSyncCountersIfSignalled.
Referenced by TmqhRingBufferRegister().
Packet * TmqhInputRingBufferSrSw (ThreadVars * t)
Definition at line 118 of file tmqh-ringbuffer.c.
References Tmq_::id, ThreadVars_::inq, RingBufferSrSw8Get(), and StatsSyncCountersIfSignalled.
Referenced by TmqhRingBufferRegister().
void TmqhOutputRingBufferMrSw (ThreadVars * t, Packet * p)
Definition at line 112 of file tmqh-ringbuffer.c.
References Tmq_::id, ThreadVars_::outq, and RingBufferMrSw8Put().
Referenced by TmqhRingBufferRegister().
void TmqhOutputRingBufferSrMw (ThreadVars * t, Packet * p)
Definition at line 146 of file tmqh-ringbuffer.c.
References Tmq_::id, ThreadVars_::outq, and RingBufferSrMw8Put().
Referenced by TmqhRingBufferRegister().
void TmqhOutputRingBufferSrSw (ThreadVars * t, Packet * p)
Definition at line 129 of file tmqh-ringbuffer.c.
References Tmq_::id, ThreadVars_::outq, and RingBufferSrSw8Put().
Referenced by TmqhRingBufferRegister().
void TmqhRingBufferDestroy (void)
Definition at line 79 of file tmqh-ringbuffer.c.
References RingBuffer8Destroy().
Referenced by TmqhCleanup().
void TmqhRingBufferRegister (void)
TmqhRingBufferRegister .
Definition at line 50 of file tmqh-ringbuffer.c.
References Tmqh_::InHandler, Tmqh_::InShutdownHandler, Tmqh_::name, Tmqh_::OutHandler, RingBuffer8Init(), SC_ERR_FATAL, SCLogError, TMQH_RINGBUFFER_MRSW, TMQH_RINGBUFFER_SRMW, TMQH_RINGBUFFER_SRSW, tmqh_table, TmqhInputRingBufferMrSw(), TmqhInputRingBufferShutdownHandler(), TmqhInputRingBufferSrMw(), TmqhInputRingBufferSrSw(), TmqhOutputRingBufferMrSw(), TmqhOutputRingBufferSrMw(), and TmqhOutputRingBufferSrSw().
Referenced by TmqhSetup().