suricata: src/tmqh-simple.h File Reference
tmqh-simple.h File Reference
#include "data-queue.h"
Functions
SCDQGenericQData * TmqhInputSimpleOnQ (SCDQDataQueue *)
Public version of TmqhInputSimple from the tmqh-simple queue handler, except that it is a generic version that is directly tied to a "SCDQDataQueue" instance(sent as an arg).
void TmqhOutputSimpleOnQ (SCDQDataQueue *, SCDQGenericQData *)
Public version of TmqhOutputSimple from the tmqh-simple queue handler, except that it is a generic version that is directly tied to a SCDQDataQueue instance(sent as an arg).
void TmqhSimpleRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file tmqh-simple.h.
Function Documentation
SCDQGenericQData* TmqhInputSimpleOnQ (SCDQDataQueue * q)
Public version of TmqhInputSimple from the tmqh-simple queue handler, except that it is a generic version that is directly tied to a "SCDQDataQueue" instance(sent as an arg).
   Retrieves a data_instance from the queue.  If the queue is empty, it
   waits on the queue, till a data_instance is enqueued into the queue
   by some other module.
   All references to "data_instance" means a reference to a data structure
   instance that implements the template "struct SCDQGenericQData_".
Parameters
q The SCDQDataQueue instance to wait on.
Return values
p The returned packet from the queue.
data The returned data_instance from the queue.
Definition at line 113 of file tmqh-simple.c.
References data, SCCondWait, SCDQDataDequeue(), SCMutexLock, and SCMutexUnlock.
void TmqhOutputSimpleOnQ (SCDQDataQueue * q, SCDQGenericQData * data)
Public version of TmqhOutputSimple from the tmqh-simple queue handler, except that it is a generic version that is directly tied to a SCDQDataQueue instance(sent as an arg).
   Pumps out a data_instance into the queue.  If the queue is empty, it
   waits on the queue, till a data_instance is enqueued into the queue.
   All references to "data_instance" means a reference to a data structure
   instance that implements the template "struct SCDQGenericQData_".
Parameters
q The SCDQDataQueue instance to pump the data into.
data The data instance to be enqueued.
Definition at line 147 of file tmqh-simple.c.
References SCCondSignal, SCDQDataEnqueue(), SCMutexLock, and SCMutexUnlock.
void TmqhSimpleRegister (void)
Definition at line 38 of file tmqh-simple.c.
References Tmqh_::InHandler, Tmqh_::InShutdownHandler, Tmqh_::name, Tmqh_::OutHandler, TMQH_SIMPLE, tmqh_table, TmqhInputSimple(), TmqhInputSimpleShutdownHandler(), and TmqhOutputSimple().
Referenced by TmqhSetup().