suricata: src/tmqh-ringbuffer.h File Reference
tmqh-ringbuffer.h File Reference
Functions
void TmqhRingBufferRegister (void)
TmqhRingBufferRegister .
void TmqhRingBufferDestroy (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file tmqh-ringbuffer.h.
Function Documentation
void TmqhRingBufferDestroy (void)
Definition at line 79 of file tmqh-ringbuffer.c.
References RingBuffer8Destroy().
Referenced by TmqhCleanup().
void TmqhRingBufferRegister (void)
TmqhRingBufferRegister .
Definition at line 50 of file tmqh-ringbuffer.c.
References Tmqh_::InHandler, Tmqh_::InShutdownHandler, Tmqh_::name, Tmqh_::OutHandler, RingBuffer8Init(), SC_ERR_FATAL, SCLogError, TMQH_RINGBUFFER_MRSW, TMQH_RINGBUFFER_SRMW, TMQH_RINGBUFFER_SRSW, tmqh_table, TmqhInputRingBufferMrSw(), TmqhInputRingBufferShutdownHandler(), TmqhInputRingBufferSrMw(), TmqhInputRingBufferSrSw(), TmqhOutputRingBufferMrSw(), TmqhOutputRingBufferSrMw(), and TmqhOutputRingBufferSrSw().
Referenced by TmqhSetup().