suricata: src/tmqh-flow.c File Reference
tmqh-flow.c File Reference
#include "suricata.h"
#include "packet-queue.h"
#include "decode.h"
#include "threads.h"
#include "threadvars.h"
#include "tmqh-flow.h"
#include "tm-queuehandlers.h"
#include "conf.h"
#include "util-unittest.h"
Functions
Packet * TmqhInputFlow (ThreadVars *t)
void TmqhOutputFlowHash (ThreadVars *tv, Packet *p)
select the queue to output based on address hash.
void TmqhOutputFlowActivePackets (ThreadVars *tv, Packet *p)
select the queue to output to based on queue lengths.
void TmqhOutputFlowRoundRobin (ThreadVars *tv, Packet *p)
select the queue to output in a round robin fashion.
void * TmqhOutputFlowSetupCtx (char *queue_str)
setup the queue handlers ctx
void TmqhOutputFlowFreeCtx (void *ctx)
void TmqhFlowRegisterTests (void)
void TmqhFlowRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Simple output queue handler that makes sure all packets of the same flow are sent to the same queue. We support different kind of q handlers. Have a look at "autofp-scheduler" conf to further undertsand the various q handlers we provide.
Definition in file tmqh-flow.c.
Function Documentation
void TmqhFlowRegister (void)
Definition at line 50 of file tmqh-flow.c.
References ConfGet(), Tmqh_::InHandler, Tmqh_::name, Tmqh_::OutHandler, Tmqh_::OutHandlerCtxFree, Tmqh_::OutHandlerCtxSetup, Tmqh_::RegisterTests, SC_ERR_INVALID_YAML_CONF_ENTRY, SCLogError, SCLogInfo, TMQH_FLOW, tmqh_table, TmqhFlowRegisterTests(), TmqhInputFlow(), TmqhOutputFlowActivePackets(), TmqhOutputFlowFreeCtx(), TmqhOutputFlowHash(), TmqhOutputFlowRoundRobin(), and TmqhOutputFlowSetupCtx().
Referenced by TmqhSetup().
void TmqhFlowRegisterTests (void)
Definition at line 501 of file tmqh-flow.c.
Referenced by RunUnittests(), and TmqhFlowRegister().
Packet * TmqhInputFlow (ThreadVars * t)
Definition at line 84 of file tmqh-flow.c.
References PacketQueue_::cond_q, Tmq_::id, ThreadVars_::inq, PacketQueue_::len, PacketQueue_::mutex_q, PacketDequeue(), SCCondWait, SCMutexLock, SCMutexUnlock, StatsSyncCountersIfSignalled, and trans_q.
Referenced by TmqhFlowRegister().
void TmqhOutputFlowActivePackets (ThreadVars * tv, Packet * p)
select the queue to output to based on queue lengths.
Parameters
tv thread vars
p packet
Definition at line 272 of file tmqh-flow.c.
References PacketQueue_::cond_q, Packet_::flow, TmqhFlowCtx_::last, PacketQueue_::len, PacketQueue_::mutex_q, ThreadVars_::outctx, PacketEnqueue(), TmqhFlowMode_::q, TmqhFlowCtx_::queues, SC_ATOMIC_ADD, SC_ATOMIC_GET, SC_ATOMIC_SET, SCCondSignal, SCMutexLock, SCMutexUnlock, and TmqhFlowCtx_::size.
Referenced by TmqhFlowRegister().
void TmqhOutputFlowFreeCtx (void * ctx)
Definition at line 204 of file tmqh-flow.c.
References TmqhFlowCtx_::queues, SC_ATOMIC_DESTROY, SC_ATOMIC_GET, SCFree, SCLogInfo, and TmqhFlowCtx_::size.
Referenced by TmqhFlowRegister().
void TmqhOutputFlowHash (ThreadVars * tv, Packet * p)
select the queue to output based on address hash.
Parameters
tv thread vars.
p packet.
Definition at line 320 of file tmqh-flow.c.
References PacketQueue_::cond_q, Packet_::flow, TmqhFlowCtx_::last, PacketQueue_::mutex_q, ThreadVars_::outctx, PacketEnqueue(), TmqhFlowMode_::q, TmqhFlowCtx_::queues, SC_ATOMIC_ADD, SC_ATOMIC_GET, SC_ATOMIC_SET, SCCondSignal, SCMutexLock, SCMutexUnlock, and TmqhFlowCtx_::size.
Referenced by TmqhFlowRegister().
void TmqhOutputFlowRoundRobin (ThreadVars * tv, Packet * p)
select the queue to output in a round robin fashion.
Parameters
tv thread vars
p packet
Definition at line 230 of file tmqh-flow.c.
References PacketQueue_::cond_q, Packet_::flow, TmqhFlowCtx_::last, PacketQueue_::mutex_q, ThreadVars_::outctx, PacketEnqueue(), TmqhFlowMode_::q, TmqhFlowCtx_::queues, SC_ATOMIC_ADD, SC_ATOMIC_GET, SC_ATOMIC_RESET, SC_ATOMIC_SET, SCCondSignal, SCMutexLock, SCMutexUnlock, and TmqhFlowCtx_::size.
Referenced by TmqhFlowRegister().
void * TmqhOutputFlowSetupCtx (char * queue_str)
setup the queue handlers ctx
Parses a comma separated string "queuename1,queuename2,etc" and sets the ctx up to devide flows over these queue's.
Parameters
queue_str comma separated string with output queue names
Return values
ctx queues handlers ctx or NULL in error
Definition at line 156 of file tmqh-flow.c.
References SC_ATOMIC_INIT, SCFree, SCLogDebug, SCMalloc, SCStrdup, str, and unlikely.
Referenced by TmqhFlowRegister().