suricata: src/tmqh-packetpool.c File Reference
tmqh-packetpool.c File Reference
#include "suricata.h"
#include "packet-queue.h"
#include "decode.h"
#include "detect.h"
#include "detect-uricontent.h"
#include "threads.h"
#include "threadvars.h"
#include "flow.h"
#include "flow-util.h"
#include "host.h"
#include "stream.h"
#include "stream-tcp-reassemble.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "tm-modules.h"
#include "pkt-var.h"
#include "tmqh-packetpool.h"
#include "util-debug.h"
#include "util-error.h"
#include "util-profiling.h"
#include "util-device.h"
Macros
#define MAX_PENDING_RETURN_PACKETS 32
Functions
void TmqhPacketpoolRegister (void)
TmqhPacketpoolRegister .
void PacketPoolWait (void)
void PacketPoolWaitForN (int n)
Wait until we have the requested ammount of packets in the pool.
Packet * PacketPoolGetPacket (void)
Get a new packet from the packet pool.
void PacketPoolReturnPacket (Packet *p)
Return packet to Packet pool.
void PacketPoolInitEmpty (void)
void PacketPoolInit (void)
void PacketPoolDestroy (void)
Packet * TmqhInputPacketpool (ThreadVars *tv)
void TmqhOutputPacketpool (ThreadVars *t, Packet *p)
void TmqhReleasePacketsToPacketPool (PacketQueue *pq)
Release all the packets in the queue back to the packetpool. Mainly used by threads that have failed, and wants to return the packets back to the packetpool.
void PacketPoolPostRunmodes (void)
Set the max_pending_return_packets value.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Packetpool queue handlers. Packet pool is implemented as a stack.
Definition in file tmqh-packetpool.c.
Macro Definition Documentation
#define MAX_PENDING_RETURN_PACKETS 32
Definition at line 54 of file tmqh-packetpool.c.
Function Documentation
void PacketPoolDestroy (void)
Definition at line 401 of file tmqh-packetpool.c.
References BUG_ON, Packet_::next, PacketFree(), PacketPoolGetPacket(), PktPool_::pending_count, PktPool_::pending_head, PktPool_::pending_pool, PktPool_::pending_tail, PktPool_::return_stack, and SC_ATOMIC_DESTROY.
Referenced by main(), RunUnittests(), TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
Packet* PacketPoolGetPacket (void)
Get a new packet from the packet pool.
Only allocates from the thread's local stack, or mallocs new packets. If the local stack is empty, first move all the return stack packets to the local stack.
Return values
Packet pointer, or NULL on failure.
Definition at line 244 of file tmqh-packetpool.c.
References BUG_ON, PktPool_::head, Packet_::next, PACKET_REINIT, and Packet_::pool.
Referenced by PacketGetFromQueueOrAlloc(), PacketPoolDestroy(), and TmqhInputPacketpool().
void PacketPoolInit (void)
Definition at line 364 of file tmqh-packetpool.c.
References BUG_ON, max_pending_packets, PacketGetFromAlloc(), PktPool_::return_stack, SC_ATOMIC_INIT, SC_ERR_FATAL, SCCondInit, SCLogDebug, SCLogError, SCLogInfo, SCMutexInit, SIZE_OF_PACKET, and unlikely.
Referenced by main(), RunUnittests(), and TmThreadsSlotPktAcqLoop().
void PacketPoolInitEmpty (void)
Definition at line 345 of file tmqh-packetpool.c.
References BUG_ON, PktPool_::return_stack, SC_ATOMIC_INIT, SCCondInit, and SCMutexInit.
Referenced by TmThreadsSlotVar().
void PacketPoolPostRunmodes (void)
Set the max_pending_return_packets value.
Set it to the max pending packets value, devided by the number of lister threads. Normally, in autofp these are the stream/detect/log worker threads.
The max_pending_return_packets value needs to stay below the packet pool size of the 'producers' (normally pkt capture threads but also flow timeout injection) to avoid a deadlock where all the 'workers' keep packets in their return pools, while the capture thread can't continue because its pool is empty.
Definition at line 583 of file tmqh-packetpool.c.
References max_pending_packets, SCLogDebug, TM_FLAG_DETECT_TM, and TmThreadCountThreadsByTmmFlags().
Referenced by main().
void PacketPoolReturnPacket (Packet * p)
Return packet to Packet pool.
Definition at line 284 of file tmqh-packetpool.c.
References BUG_ON, PktPool_::head, Packet_::next, PACKET_RELEASE_REFS, PacketFree(), PktPool_::pending_count, PktPool_::pending_head, PktPool_::pending_pool, PktPool_::pending_tail, Packet_::pool, PktPool_::return_stack, SC_ATOMIC_GET, SC_ATOMIC_RESET, SCCondSignal, SCMutexLock, and SCMutexUnlock.
Referenced by PacketFreeOrRelease().
void PacketPoolWait (void)
Definition at line 148 of file tmqh-packetpool.c.
References cc_barrier, PktPool_::return_stack, SC_ATOMIC_ADD, SCCondWait, SCMutexLock, and SCMutexUnlock.
Referenced by NapatechStreamLoop(), PacketPoolWaitForN(), ReceiveAFPLoop(), ReceiveErfFileLoop(), ReceiveIPFWLoop(), ReceivePcapFileLoop(), ReceivePcapLoop(), and ReceivePfringLoop().
void PacketPoolWaitForN (int n)
Wait until we have the requested ammount of packets in the pool.
In some cases waiting for packets is undesirable. Especially when a wait would happen under a lock of some kind, other parts of the engine could have to wait.
This function only returns when at least N packets are in our pool.
Parameters
n number of packets needed
Definition at line 173 of file tmqh-packetpool.c.
References PktPool_::head, Packet_::next, PacketPoolWait(), PktPool_::return_stack, SC_ATOMIC_ADD, SCCondWait, SCMutexLock, and SCMutexUnlock.
Packet* TmqhInputPacketpool (ThreadVars * tv)
Definition at line 438 of file tmqh-packetpool.c.
References PacketPoolGetPacket().
Referenced by TmqhPacketpoolRegister().
void TmqhOutputPacketpool (ThreadVars * t, Packet * p)
Todo:
make this a callback Release tcp segments. Done here after alerting can use them.
Definition at line 443 of file tmqh-packetpool.c.
References Packet_::flags, Packet_::flow, FLOW_PKT_TOSERVER, Packet_::flowflags, IS_TUNNEL_PKT, IS_TUNNEL_PKT_VERDICTED, IS_TUNNEL_ROOT_PKT, m, Flow_::m, PACKET_PROFILING_END, PKT_ALLOC, Packet_::proto, Packet_::ReleasePacket, Packet_::root, SCEnter, SCLogDebug, SCMutex, SCMutexLock, SCMutexUnlock, SCReturn, SET_TUNNEL_PKT_VERDICTED, STREAM_TOCLIENT, STREAM_TOSERVER, StreamTcpPruneSession(), TUNNEL_DECR_PKT_TPR_NOLOCK, Packet_::tunnel_mutex, and TUNNEL_PKT_TPR.
Referenced by AFPRead(), AFPReadFromRing(), FlowForceReassemblyForFlow(), NapatechStreamLoop(), PacketTunnelPktSetup(), PcapCallbackLoop(), PcapFileCallbackLoop(), ReceiveErfFileLoop(), ReceiveIPFWLoop(), ReceivePfringLoop(), TmqhPacketpoolRegister(), TmqhReleasePacketsToPacketPool(), TmThreadsSlotVar(), and TmThreadsSlotVarRun().
void TmqhPacketpoolRegister (void)
TmqhPacketpoolRegister .
Definition at line 132 of file tmqh-packetpool.c.
References Tmqh_::InHandler, Tmqh_::name, Tmqh_::OutHandler, TMQH_PACKETPOOL, tmqh_table, TmqhInputPacketpool(), and TmqhOutputPacketpool().
Referenced by TmqhSetup().
void TmqhReleasePacketsToPacketPool (PacketQueue * pq)
Release all the packets in the queue back to the packetpool. Mainly used by threads that have failed, and wants to return the packets back to the packetpool.
Parameters
pq Pointer to the packetqueue from which the packets have to be returned back to the packetpool
Warning
this function assumes that the pq does not use locking
Definition at line 557 of file tmqh-packetpool.c.
References PacketDequeue(), and TmqhOutputPacketpool().
Referenced by TmThreadsSlotVar(), and TmThreadsSlotVarRun().