suricata: src/tmqh-nfq.c File Reference
tmqh-nfq.c File Reference
#include "suricata-common.h"
#include "packet-queue.h"
#include "decode.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
Functions
void TmqhOutputVerdictNfq (ThreadVars *t, Packet *p)
void TmqhNfqRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
NFQ Verdict Handler
Definition in file tmqh-nfq.c.
Function Documentation
void TmqhNfqRegister (void)
Definition at line 36 of file tmqh-nfq.c.
References Tmqh_::InHandler, Tmqh_::name, Tmqh_::OutHandler, TMQH_NFQ, tmqh_table, and TmqhOutputVerdictNfq().
Referenced by TmqhSetup().
void TmqhOutputVerdictNfq (ThreadVars * t, Packet * p)
Definition at line 43 of file tmqh-nfq.c.
References PacketQueue_::cond_q, PacketQueue_::mutex_q, PacketEnqueue(), SCCondSignal, SCMutexLock, SCMutexUnlock, and trans_q.
Referenced by TmqhNfqRegister().