suricata: src/unix-manager.c File Reference
unix-manager.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "unix-manager.h"
#include "detect-engine.h"
#include "tm-threads.h"
#include "runmodes.h"
#include "conf.h"
#include "util-privs.h"
#include "util-debug.h"
#include "util-signal.h"
#include <sys/un.h>
#include <sys/stat.h>
#include <sys/types.h>
Functions
void UnixManagerThreadSpawn (int mode)
void UnixSocketKillSocketThread (void)
void TmModuleUnixManagerRegister (void)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file unix-manager.c.
Function Documentation
void TmModuleUnixManagerRegister (void)
Definition at line 1020 of file unix-manager.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Management, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_COMMAND_TM, tmm_modules, and TMM_UNIXMANAGER.
Referenced by RegisterAllModules().
void UnixManagerThreadSpawn (int mode)
Definition at line 1007 of file unix-manager.c.
References SC_ERR_UNIMPLEMENTED, and SCLogError.
Referenced by main(), and RunModeUnixSocketSingle().
void UnixSocketKillSocketThread (void)
Definition at line 1013 of file unix-manager.c.
Referenced by main().