suricata: src/unix-manager.h File Reference
unix-manager.h File Reference
Macros
#define UNIX_CMD_TAKE_ARGS 1
Functions
void UnixManagerThreadSpawn (int mode)
void UnixSocketKillSocketThread (void)
void TmModuleUnixManagerRegister (void)
Variables
SCCtrlCondT unix_manager_ctrl_cond
SCCtrlMutex unix_manager_ctrl_mutex
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file unix-manager.h.
Macro Definition Documentation
#define UNIX_CMD_TAKE_ARGS 1
Definition at line 31 of file unix-manager.h.
Referenced by main(), and RunModeUnixSocketSingle().
Function Documentation
void TmModuleUnixManagerRegister (void)
Definition at line 1020 of file unix-manager.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Management, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_COMMAND_TM, tmm_modules, and TMM_UNIXMANAGER.
Referenced by RegisterAllModules().
void UnixManagerThreadSpawn (int mode)
Definition at line 1007 of file unix-manager.c.
References SC_ERR_UNIMPLEMENTED, and SCLogError.
Referenced by main(), and RunModeUnixSocketSingle().
void UnixSocketKillSocketThread (void)
Definition at line 1013 of file unix-manager.c.
Referenced by main().
Variable Documentation
SCCtrlCondT unix_manager_ctrl_cond
Definition at line 33 of file unix-manager.h.
SCCtrlMutex unix_manager_ctrl_mutex
Definition at line 34 of file unix-manager.h.