suricata: src/util-hashlist.c File Reference
util-hashlist.c File Reference
#include "suricata-common.h"
#include "util-hashlist.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "util-memcmp.h"
Functions
HashListTable * HashListTableInit (uint32_t size, uint32_t(*Hash)(struct HashListTable_ *, void *, uint16_t), char(*Compare)(void *, uint16_t, void *, uint16_t), void(*Free)(void *))
void HashListTableFree (HashListTable *ht)
void HashListTablePrint (HashListTable *ht)
int HashListTableAdd (HashListTable *ht, void *data, uint16_t datalen)
int HashListTableRemove (HashListTable *ht, void *data, uint16_t datalen)
char HashListTableDefaultCompare (void *data1, uint16_t len1, void *data2, uint16_t len2)
void * HashListTableLookup (HashListTable *ht, void *data, uint16_t datalen)
uint32_t HashListTableGenericHash (HashListTable *ht, void *data, uint16_t datalen)
HashListTableBucket * HashListTableGetListHead (HashListTable *ht)
void HashListTableRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Chained hash table implementation
The 'Free' pointer can be used to have the API free your hashed data. If it's NULL it's the callers responsebility
Definition in file util-hashlist.c.
Function Documentation
int HashListTableAdd (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 116 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTableBucket_::data, data, HashListTable_::Hash, HashListTable_::listhead, HashListTableBucket_::listnext, HashListTableBucket_::listprev, HashListTable_::listtail, SCLogDebug, SCMalloc, HashListTableBucket_::size, and unlikely.
Referenced by DetectPortDpHashAdd(), DetectPortSpHashAdd(), SigGroupHeadDPortHashAdd(), SigGroupHeadHashAdd(), SigGroupHeadMpmHashAdd(), SigGroupHeadMpmStreamHashAdd(), SigGroupHeadMpmUriHashAdd(), SigGroupHeadSPortHashAdd(), and VariableNameGetIdx().
char HashListTableDefaultCompare (void * data1, uint16_t len1, void * data2, uint16_t len2)
Definition at line 237 of file util-hashlist.c.
References SCMemcmp.
Referenced by HashListTableInit().
void HashListTableFree (HashListTable * ht)
Definition at line 82 of file util-hashlist.c.
References HashListTable_::array, HashListTable_::array_size, HashListTableBucket_::bucknext, HashListTableBucket_::data, HashListTable_::Free, and SCFree.
Referenced by DetectParseDupSigHashFree(), DetectPortDpHashFree(), DetectPortSpHashFree(), SigGroupHeadDPortHashFree(), SigGroupHeadHashFree(), SigGroupHeadMpmHashFree(), SigGroupHeadMpmStreamHashFree(), SigGroupHeadMpmUriHashFree(), SigGroupHeadSPortHashFree(), and VariableNameFreeHash().
uint32_t HashListTableGenericHash (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 273 of file util-hashlist.c.
References HashListTable_::array_size.
HashListTableBucket* HashListTableGetListHead (HashListTable * ht)
Definition at line 290 of file util-hashlist.c.
References HashListTable_::listhead.
Referenced by CreateGroupedPortList(), and SigGroupHeadFreeMpmArrays().
HashListTable* HashListTableInit (uint32_t size, uint32_t(*)(struct HashListTable_ *, void *, uint16_t) Hash, char(*)(void *, uint16_t, void *, uint16_t) Compare, void(*)(void *) Free)
Definition at line 35 of file util-hashlist.c.
References HashListTable_::array, HashListTable_::array_size, HashTable_::Compare, HashListTable_::Compare, HashTable_::Free, HashListTable_::Free, HashTable_::Hash, HashListTable_::Hash, HashListTableDefaultCompare(), HashListTable_::listhead, HashListTable_::listtail, SCFree, SCMalloc, and unlikely.
Referenced by DetectParseDupSigHashInit(), DetectPortDpHashInit(), DetectPortSpHashInit(), SigGroupHeadDPortHashInit(), SigGroupHeadHashInit(), SigGroupHeadMpmHashInit(), SigGroupHeadMpmStreamHashInit(), SigGroupHeadMpmUriHashInit(), SigGroupHeadSPortHashInit(), and VariableNameInitHash().
void* HashListTableLookup (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 248 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTable_::Compare, HashListTableBucket_::data, HashListTable_::Hash, SCLogDebug, and HashListTableBucket_::size.
Referenced by DetectPortDpHashLookup(), DetectPortSpHashLookup(), SigGroupHeadDPortHashLookup(), SigGroupHeadHashLookup(), SigGroupHeadMpmHashLookup(), SigGroupHeadMpmStreamHashLookup(), SigGroupHeadMpmUriHashLookup(), SigGroupHeadSPortHashLookup(), VariableIdxGetName(), and VariableNameGetIdx().
void HashListTablePrint (HashListTable * ht)
Definition at line 108 of file util-hashlist.c.
References HashListTable_::array_size, and HashListTable_::Hash.
void HashListTableRegisterTests (void)
Definition at line 501 of file util-hashlist.c.
Referenced by RunUnittests().
int HashListTableRemove (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 157 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTable_::Compare, HashListTableBucket_::data, HashListTable_::Free, HashListTable_::Hash, HashListTable_::listhead, HashListTableBucket_::listnext, HashListTableBucket_::listprev, HashListTable_::listtail, SCFree, SCLogDebug, and HashListTableBucket_::size.
Referenced by SigGroupHeadHashRemove(), and SigGroupHeadSPortHashRemove().