suricata: src/util-spm.h File Reference
util-spm.h File Reference
#include "util-spm-bs.h"
#include "util-spm-bs2bm.h"
#include "util-spm-bm.h"
Macros
#define SpmSearch(text, textlen, needle, needlelen)
#define SpmNocaseSearch(text, textlen, needle, needlelen)
Functions
uint8_t * Bs2bmSearch (uint8_t *text, uint32_t textlen, uint8_t *needle, uint16_t needlelen)
Search a pattern in the text using the Bs2Bm algorithm (build a bad characters array)
uint8_t * Bs2bmNocaseSearch (uint8_t *text, uint32_t textlen, uint8_t *needle, uint16_t needlelen)
Search a pattern in the text using the Bs2Bm nocase algorithm (build a bad characters array)
uint8_t * BoyerMooreSearch (uint8_t *text, uint32_t textlen, uint8_t *needle, uint16_t needlelen)
Search a pattern in the text using Boyer Moore algorithm (build a bad character shifts array and good prefixes shift array)
uint8_t * BoyerMooreNocaseSearch (uint8_t *text, uint32_t textlen, uint8_t *needle, uint16_t needlelen)
Search a pattern in the text using Boyer Moore nocase algorithm (build a bad character shifts array and good prefixes shift array)
void UtilSpmSearchRegistertests (void)
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file util-spm.h.
Macro Definition Documentation
#define SpmNocaseSearch (text, textlen, needle, needlelen)
Value:
({\
    uint8_t *mfound; \
    if (needlelen < 4 && textlen < 512) \
          mfound = BasicSearchNocase(text, textlen, needle, needlelen); \
    else if (needlelen < 4) \
          mfound = BasicSearchNocase(text, textlen, needle, needlelen); \
    else \
          mfound = BoyerMooreNocaseSearch(text, textlen, needle, needlelen); \
    mfound; \
    })
Definition at line 49 of file util-spm.h.
#define SpmSearch (text, textlen, needle, needlelen)
Value:
({\
    uint8_t *mfound; \
    if (needlelen < 4 && textlen < 512) \
          mfound = BasicSearch(text, textlen, needle, needlelen); \
    else if (needlelen < 4) \
          mfound = BasicSearch(text, textlen, needle, needlelen); \
    else \
          mfound = BoyerMooreSearch(text, textlen, needle, needlelen); \
    mfound; \
    })
Definition at line 38 of file util-spm.h.
Referenced by DetectFlowvarMatch(), and DetectPktvarMatch().
Function Documentation
uint8_t* BoyerMooreNocaseSearch (uint8_t * text, uint32_t textlen, uint8_t * needle, uint16_t needlelen)
Search a pattern in the text using Boyer Moore nocase algorithm (build a bad character shifts array and good prefixes shift array)
Parameters
text Text to search in
textlen length of the text
needle pattern to search for
needlelen length of the pattern
Definition at line 123 of file util-spm.c.
References BoyerMooreCtxDeInit(), BoyerMooreNocase(), and BoyerMooreNocaseCtxInit().
uint8_t* BoyerMooreSearch (uint8_t * text, uint32_t textlen, uint8_t * needle, uint16_t needlelen)
Search a pattern in the text using Boyer Moore algorithm (build a bad character shifts array and good prefixes shift array)
Parameters
text Text to search in
textlen length of the text
needle pattern to search for
needlelen length of the pattern
Definition at line 104 of file util-spm.c.
References BoyerMoore(), BoyerMooreCtxDeInit(), and BoyerMooreCtxInit().
uint8_t* Bs2bmNocaseSearch (uint8_t * text, uint32_t textlen, uint8_t * needle, uint16_t needlelen)
Search a pattern in the text using the Bs2Bm nocase algorithm (build a bad characters array)
Parameters
text Text to search in
textlen length of the text
needle pattern to search for
needlelen length of the pattern
Definition at line 87 of file util-spm.c.
References ALPHABET_SIZE, Bs2BmBadchars(), and Bs2BmNocase().
uint8_t* Bs2bmSearch (uint8_t * text, uint32_t textlen, uint8_t * needle, uint16_t needlelen)
Search a pattern in the text using the Bs2Bm algorithm (build a bad characters array)
Default algorithm to use: Boyer Moore
Wrappers for building context and searching (Bs2Bm and boyermoore) Use them if you cant store the context
Parameters
text Text to search in
textlen length of the text
needle pattern to search for
needlelen length of the pattern
Definition at line 71 of file util-spm.c.
References ALPHABET_SIZE, Bs2Bm(), and Bs2BmBadchars().
Referenced by HtpRequestBodyHandleMultipart().
void UtilSpmSearchRegistertests (void)
Definition at line 2318 of file util-spm.c.
Referenced by RunUnittests().