suricata: src/util-signal.c File Reference
util-signal.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "util-debug.h"
Functions
int UtilSignalBlock (int signum)
void UtilSignalHandlerSetup (int sig, void(*handler)())
int UtilSignalIsHandler (int sig, void(*handler)())
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-signal.c.
Function Documentation
int UtilSignalBlock (int signum)
Definition at line 28 of file util-signal.c.
Referenced by TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
void UtilSignalHandlerSetup (int sig, void(*)() handler)
Definition at line 41 of file util-signal.c.
Referenced by main().
int UtilSignalIsHandler (int sig, void(*)() handler)
Definition at line 59 of file util-signal.c.