suricata: src/util-bloomfilter.c File Reference
util-bloomfilter.c File Reference
#include "suricata-common.h"
#include "util-bloomfilter.h"
#include "util-unittest.h"
Functions
BloomFilter * BloomFilterInit (uint32_t size, uint8_t iter, uint32_t(*Hash)(void *, uint16_t, uint8_t, uint32_t))
void BloomFilterFree (BloomFilter *bf)
void BloomFilterPrint (BloomFilter *bf)
int BloomFilterAdd (BloomFilter *bf, void *data, uint16_t datalen)
uint32_t BloomFilterMemoryCnt (BloomFilter *bf)
uint32_t BloomFilterMemorySize (BloomFilter *bf)
void BloomFilterRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Bitwise bloom filter implementation
Definition in file util-bloomfilter.c.
Function Documentation
int BloomFilterAdd (BloomFilter * bf, void * data, uint16_t datalen)
Definition at line 88 of file util-bloomfilter.c.
References BloomFilter_::bitarray, BloomFilter_::bitarray_size, BloomFilter_::Hash, and BloomFilter_::hash_iterations.
void BloomFilterFree (BloomFilter * bf)
Definition at line 68 of file util-bloomfilter.c.
References BloomFilter_::bitarray, and SCFree.
Referenced by B2gDestroyCtx(), B3gDestroyCtx(), and WmDestroyCtx().
BloomFilter* BloomFilterInit (uint32_t size, uint8_t iter, uint32_t(*)(void *, uint16_t, uint8_t, uint32_t) Hash)
Definition at line 30 of file util-bloomfilter.c.
References BloomFilter_::bitarray, BloomFilter_::bitarray_size, BloomFilter_::Hash, BloomFilter_::hash_iterations, SCFree, SCMalloc, and unlikely.
uint32_t BloomFilterMemoryCnt (BloomFilter * bf)
Definition at line 104 of file util-bloomfilter.c.
Referenced by B2gDestroyCtx(), B3gDestroyCtx(), and WmDestroyCtx().
uint32_t BloomFilterMemorySize (BloomFilter * bf)
Definition at line 112 of file util-bloomfilter.c.
References BloomFilter_::bitarray_size.
Referenced by B2gDestroyCtx(), B3gDestroyCtx(), and WmDestroyCtx().
void BloomFilterPrint (BloomFilter * bf)
Definition at line 78 of file util-bloomfilter.c.
References BloomFilter_::bitarray_size, BloomFilter_::Hash, and BloomFilter_::hash_iterations.
void BloomFilterRegisterTests (void)
Definition at line 274 of file util-bloomfilter.c.
Referenced by RunUnittests().