suricata: src/util-affinity.h File Reference
util-affinity.h File Reference
#include "suricata-common.h"
Data Structures
struct ThreadsAffinityType_
Typedefs
typedef struct ThreadsAffinityType_ ThreadsAffinityType
Enumerations
enum {
RECEIVE_CPU_SET, DECODE_CPU_SET, STREAM_CPU_SET, DETECT_CPU_SET,
VERDICT_CPU_SET, REJECT_CPU_SET, OUTPUT_CPU_SET, MANAGEMENT_CPU_SET,
MAX_CPU_SET
}
enum { BALANCED_AFFINITY, EXCLUSIVE_AFFINITY, MAX_AFFINITY }
Functions
void AffinitySetupLoadFromConfig ()
Extract cpu affinity configuration from current config file.
ThreadsAffinityType * GetAffinityTypeFromName (const char *name)
find affinity by its name
int AffinityGetNextCPU (ThreadsAffinityType *taf)
Return next cpu to use for a given thread family.
Variables
ThreadsAffinityType thread_affinity [MAX_CPU_SET]
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file util-affinity.h.
Typedef Documentation
typedef struct ThreadsAffinityType_ ThreadsAffinityType
Enumeration Type Documentation
anonymous enum
Enumerator
RECEIVE_CPU_SET
DECODE_CPU_SET
STREAM_CPU_SET
DETECT_CPU_SET
VERDICT_CPU_SET
REJECT_CPU_SET
OUTPUT_CPU_SET
MANAGEMENT_CPU_SET
MAX_CPU_SET
Definition at line 49 of file util-affinity.h.
anonymous enum
Enumerator
BALANCED_AFFINITY
EXCLUSIVE_AFFINITY
MAX_AFFINITY
Definition at line 61 of file util-affinity.h.
Function Documentation
int AffinityGetNextCPU (ThreadsAffinityType * taf)
Return next cpu to use for a given thread family.
Return values
the cpu to used given by its id
Definition at line 298 of file util-affinity.c.
References ThreadsAffinityType_::cpu_set, ThreadsAffinityType_::lcpu, SC_ERR_INVALID_ARGUMENT, SCLogError, SCLogInfo, SCMutexLock, SCMutexUnlock, ThreadsAffinityType_::taf_mutex, and UtilCpuGetNumProcessorsOnline().
Referenced by TmThreadSetupOptions().
void AffinitySetupLoadFromConfig ()
Extract cpu affinity configuration from current config file.
Definition at line 191 of file util-affinity.c.
References BALANCED_AFFINITY, ConfGetNode(), ConfNodeLookupChild(), ThreadsAffinityType_::cpu_set, EXCLUSIVE_AFFINITY, GetAffinityTypeFromName(), ThreadsAffinityType_::hiprio_cpu, ThreadsAffinityType_::lowprio_cpu, ThreadsAffinityType_::medprio_cpu, ThreadsAffinityType_::mode_flag, ThreadsAffinityType_::nb_threads, next, ThreadsAffinityType_::prio, PRIO_HIGH, PRIO_LOW, PRIO_MEDIUM, SC_ERR_INVALID_ARGUMENT, SCLogDebug, SCLogError, SCLogInfo, TAILQ_FOREACH, thread_affinity_init_done, and ConfNode_::val.
Referenced by RunModeInitialize().
ThreadsAffinityType* GetAffinityTypeFromName (const char * name)
find affinity by its name
Return values
a pointer to the affinity or NULL if not found
Definition at line 92 of file util-affinity.c.
References MAX_CPU_SET.
Referenced by AffinitySetupLoadFromConfig().
Variable Documentation
ThreadsAffinityType thread_affinity[MAX_CPU_SET]
store thread affinity mode for all type of threads
Definition at line 34 of file util-affinity.c.
Referenced by TmThreadGetNbThreads(), and TmThreadSetupOptions().