suricata: src/util-mpm-wumanber.c File Reference
util-mpm-wumanber.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "util-mpm.h"
#include "util-mpm-wumanber.h"
#include "conf.h"
#include "util-unittest.h"
#include "util-debug.h"
Macros
#define INIT_HASH_SIZE 65535
#define HASH16_SIZE 65536
#define HASH16(a, b) (((a)<<8) | (b))
#define HASH15_SIZE 32768
#define HASH15(a, b) (((a)<<7) | (b))
#define HASH14_SIZE 16384
#define HASH14(a, b) (((a)<<6) | (b))
#define HASH12_SIZE 4096
#define HASH12(a, b) (((a)<<4) | (b))
#define HASH9_SIZE 512
#define HASH9(a, b) (((a)<<1) | (b))
#define wm_tolower(c) lowercasetable[(c)]
#define COUNT(counter)
Functions
void WmInitCtx (MpmCtx *mpm_ctx)
void WmThreadInitCtx (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, uint32_t)
void WmDestroyCtx (MpmCtx *mpm_ctx)
void WmThreadDestroyCtx (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx)
int WmAddPatternCI (MpmCtx *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
int WmAddPatternCS (MpmCtx *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
int WmPreparePatterns (MpmCtx *mpm_ctx)
uint32_t WmSearch (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *, uint8_t *buf, uint16_t buflen)
uint32_t WmSearch1 (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *, uint8_t *buf, uint16_t buflen)
uint32_t WmSearch2Hash9 (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *, uint8_t *buf, uint16_t buflen)
uint32_t WmSearch2Hash12 (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *, uint8_t *buf, uint16_t buflen)
uint32_t WmSearch2Hash14 (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *, uint8_t *buf, uint16_t buflen)
uint32_t WmSearch2Hash15 (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *, uint8_t *buf, uint16_t buflen)
uint32_t WmSearch2Hash16 (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *, uint8_t *buf, uint16_t buflen)
void WmPrintInfo (MpmCtx *mpm_ctx)
void WmPrintSearchStats (MpmThreadCtx *mpm_thread_ctx)
void WmRegisterTests (void)
void prt (uint8_t *buf, uint16_t buflen)
void WmFreePattern (MpmCtx *mpm_ctx, WmPattern *p)
void WmGetConfig ()
Function to get the user defined values for wumanber algorithm from the config file 'suricata.yaml'.
void MpmWuManberRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implementation of the Wu-Manber pattern matching algorithm.
Ideas:
the hash contains a list of patterns. Maybe we can 'train' the hash so the most common patterns always appear first in this list.
Todo:
make hash1 a array of ptr and get rid of the flag field in the WmHashItem
remove exit() calls
only calc prefixci_buf for nocase patterns? – would be in a loop though, so probably not a performance inprovement.
make sure runtime counters can be disabled (at compile time)
Definition in file util-mpm-wumanber.c.
Macro Definition Documentation
#define COUNT (counter)
Definition at line 89 of file util-mpm-wumanber.c.
Referenced by WmSearch2Hash12(), WmSearch2Hash14(), WmSearch2Hash15(), WmSearch2Hash16(), and WmSearch2Hash9().
#define HASH12 (a, b) (((a)<<4) | (b))
Definition at line 55 of file util-mpm-wumanber.c.
Referenced by WmSearch2Hash12().
#define HASH12_SIZE 4096
Definition at line 54 of file util-mpm-wumanber.c.
Referenced by WmPreparePatterns().
#define HASH14 (a, b) (((a)<<6) | (b))
Definition at line 53 of file util-mpm-wumanber.c.
Referenced by WmSearch2Hash14().
#define HASH14_SIZE 16384
Definition at line 52 of file util-mpm-wumanber.c.
Referenced by WmPreparePatterns().
#define HASH15 (a, b) (((a)<<7) | (b))
Definition at line 51 of file util-mpm-wumanber.c.
Referenced by WmSearch2Hash15().
#define HASH15_SIZE 32768
Definition at line 50 of file util-mpm-wumanber.c.
Referenced by WmPreparePatterns().
#define HASH16 (a, b) (((a)<<8) | (b))
Definition at line 49 of file util-mpm-wumanber.c.
Referenced by WmSearch2Hash16().
#define HASH16_SIZE 65536
Definition at line 48 of file util-mpm-wumanber.c.
Referenced by WmPreparePatterns().
#define HASH9 (a, b) (((a)<<1) | (b))
Definition at line 57 of file util-mpm-wumanber.c.
Referenced by WmSearch2Hash9().
#define HASH9_SIZE 512
Definition at line 56 of file util-mpm-wumanber.c.
Referenced by WmPreparePatterns().
#define INIT_HASH_SIZE 65535
Definition at line 46 of file util-mpm-wumanber.c.
Referenced by WmDestroyCtx(), WmInitCtx(), and WmPreparePatterns().
#define wm_tolower (c) lowercasetable[(c)]
Definition at line 83 of file util-mpm-wumanber.c.
Referenced by WmSearch1(), WmSearch2Hash12(), WmSearch2Hash14(), WmSearch2Hash15(), WmSearch2Hash16(), and WmSearch2Hash9().
Function Documentation
void MpmWuManberRegister (void)
Definition at line 1526 of file util-mpm-wumanber.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, mpm_table, MPM_WUMANBER, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, MpmTableElmt_::Search, WmAddPatternCI(), WmAddPatternCS(), WmDestroyCtx(), WmInitCtx(), WmPreparePatterns(), WmPrintInfo(), WmPrintSearchStats(), WmRegisterTests(), WmSearch(), WmThreadDestroyCtx(), and WmThreadInitCtx().
Referenced by MpmTableSetup().
void prt (uint8_t * buf, uint16_t buflen)
Definition at line 92 of file util-mpm-wumanber.c.
Referenced by B2gSearchBNDMq().
int WmAddPatternCI (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 414 of file util-mpm-wumanber.c.
References MPM_PATTERN_FLAG_NOCASE.
Referenced by MpmWuManberRegister().
int WmAddPatternCS (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 421 of file util-mpm-wumanber.c.
Referenced by MpmWuManberRegister().
void WmDestroyCtx (MpmCtx * mpm_ctx)
Definition at line 1426 of file util-mpm-wumanber.c.
References WmCtx_::bloom, BloomFilterFree(), BloomFilterMemoryCnt(), BloomFilterMemorySize(), MpmCtx_::ctx, WmCtx_::hash, WmCtx_::hash_size, WmCtx_::init_hash, INIT_HASH_SIZE, MpmCtx_::memory_cnt, MpmCtx_::memory_size, WmCtx_::parray, MpmCtx_::pattern_cnt, WmCtx_::pminlen, SCFree, WmCtx_::shifttable, and WmFreePattern().
Referenced by MpmWuManberRegister().
void WmFreePattern (MpmCtx * mpm_ctx, WmPattern * p)
Definition at line 272 of file util-mpm-wumanber.c.
References WmPattern_::ci, WmPattern_::cs, WmPattern_::len, MpmCtx_::memory_cnt, MpmCtx_::memory_size, SCFree, WmPattern_::sids, and WmPattern_::sids_size.
Referenced by WmDestroyCtx().
void WmGetConfig ()
Function to get the user defined values for wumanber algorithm from the config file 'suricata.yaml'.
Definition at line 1365 of file util-mpm-wumanber.c.
References BLOOMSIZE_MEDIUM, ConfGetNode(), ConfNodeLookupChildValue(), HASHSIZE_LOW, MpmGetBloomSize(), MpmGetHashSize(), next, SCLogDebug, TAILQ_FOREACH, and ConfNode_::val.
Referenced by WmInitCtx().
void WmInitCtx (MpmCtx * mpm_ctx)
Definition at line 1399 of file util-mpm-wumanber.c.
References MpmCtx_::ctx, WmCtx_::init_hash, INIT_HASH_SIZE, MpmCtx_::memory_cnt, MpmCtx_::memory_size, SCLogDebug, SCMalloc, and WmGetConfig().
Referenced by MpmWuManberRegister().
int WmPreparePatterns (MpmCtx * mpm_ctx)
Definition at line 662 of file util-mpm-wumanber.c.
References MpmCtx_::ctx, HASH12_SIZE, HASH14_SIZE, HASH15_SIZE, HASH16_SIZE, HASH9_SIZE, WmCtx_::hash_size, WmCtx_::init_hash, INIT_HASH_SIZE, WmCtx_::MBSearch, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmCtx_::minlen, WmPattern_::next, WmCtx_::parray, MpmCtx_::pattern_cnt, SCFree, SCMalloc, WmCtx_::Search, WmSearch1(), WmSearch2Hash12(), WmSearch2Hash14(), WmSearch2Hash15(), WmSearch2Hash16(), and WmSearch2Hash9().
Referenced by MpmWuManberRegister().
void WmPrintInfo (MpmCtx * mpm_ctx)
Definition at line 103 of file util-mpm-wumanber.c.
References MpmCtx_::ctx, WmCtx_::hash_size, MpmCtx_::maxlen, WmCtx_::MBSearch, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmCtx_::minlen, MpmCtx_::pattern_cnt, WmCtx_::Search, WmCtx_::shiftlen, WmSearch1(), WmSearch2Hash12(), WmSearch2Hash14(), WmSearch2Hash15(), WmSearch2Hash16(), and WmSearch2Hash9().
Referenced by MpmWuManberRegister().
void WmPrintSearchStats (MpmThreadCtx * mpm_thread_ctx)
Definition at line 740 of file util-mpm-wumanber.c.
References MpmThreadCtx_::ctx.
Referenced by MpmWuManberRegister().
void WmRegisterTests (void)
Definition at line 3139 of file util-mpm-wumanber.c.
Referenced by MpmWuManberRegister().
uint32_t WmSearch (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen) inline
Definition at line 769 of file util-mpm-wumanber.c.
References MpmCtx_::ctx, and WmCtx_::Search.
Referenced by MpmWuManberRegister().
uint32_t WmSearch1 (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 1305 of file util-mpm-wumanber.c.
References WmPattern_::ci, WmPattern_::cs, MpmCtx_::ctx, WmPattern_::flags, WmHashItem_::flags, WmCtx_::hash1, WmPattern_::id, WmPattern_::len, MpmCtx_::maxlen, WmCtx_::MBSearch, MpmCtx_::minlen, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), WmHashItem_::nxt, WmCtx_::parray, PatternMatcherQueue_::pattern_id_bitarray_size, WmPattern_::sids, WmPattern_::sids_size, and wm_tolower.
Referenced by WmPreparePatterns(), and WmPrintInfo().
uint32_t WmSearch2Hash12 (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 883 of file util-mpm-wumanber.c.
References WmCtx_::bloom, WmPattern_::ci, COUNT, WmPattern_::cs, MpmThreadCtx_::ctx, MpmCtx_::ctx, WmPattern_::flags, WmCtx_::hash, HASH12, WmPattern_::id, WmHashItem_::idx, WmPattern_::len, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), WmHashItem_::nxt, WmCtx_::parray, PatternMatcherQueue_::pattern_id_bitarray_size, WmCtx_::pminlen, WmPattern_::prefix_ci, WmPattern_::prefix_cs, WmCtx_::shiftlen, WmCtx_::shifttable, WmPattern_::sids, WmPattern_::sids_size, and wm_tolower.
Referenced by WmPreparePatterns(), and WmPrintInfo().
uint32_t WmSearch2Hash14 (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 991 of file util-mpm-wumanber.c.
References WmCtx_::bloom, WmPattern_::ci, COUNT, WmPattern_::cs, MpmThreadCtx_::ctx, MpmCtx_::ctx, WmPattern_::flags, WmCtx_::hash, HASH14, WmPattern_::id, WmHashItem_::idx, WmPattern_::len, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), WmHashItem_::nxt, WmCtx_::parray, PatternMatcherQueue_::pattern_id_bitarray_size, WmCtx_::pminlen, WmPattern_::prefix_ci, WmPattern_::prefix_cs, WmCtx_::shiftlen, WmCtx_::shifttable, WmPattern_::sids, WmPattern_::sids_size, and wm_tolower.
Referenced by WmPreparePatterns(), and WmPrintInfo().
uint32_t WmSearch2Hash15 (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 1095 of file util-mpm-wumanber.c.
References WmCtx_::bloom, WmPattern_::ci, COUNT, WmPattern_::cs, MpmThreadCtx_::ctx, MpmCtx_::ctx, WmPattern_::flags, WmCtx_::hash, HASH15, WmPattern_::id, WmHashItem_::idx, WmPattern_::len, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), WmHashItem_::nxt, WmCtx_::parray, PatternMatcherQueue_::pattern_id_bitarray_size, WmCtx_::pminlen, WmPattern_::prefix_ci, WmPattern_::prefix_cs, WmCtx_::shiftlen, WmCtx_::shifttable, WmPattern_::sids, WmPattern_::sids_size, and wm_tolower.
Referenced by WmPreparePatterns(), and WmPrintInfo().
uint32_t WmSearch2Hash16 (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 1201 of file util-mpm-wumanber.c.
References WmCtx_::bloom, WmPattern_::ci, COUNT, WmPattern_::cs, MpmThreadCtx_::ctx, MpmCtx_::ctx, WmPattern_::flags, WmCtx_::hash, HASH16, WmPattern_::id, WmHashItem_::idx, WmPattern_::len, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), WmHashItem_::nxt, WmCtx_::parray, PatternMatcherQueue_::pattern_id_bitarray_size, WmCtx_::pminlen, WmPattern_::prefix_ci, WmPattern_::prefix_cs, WmCtx_::shiftlen, WmCtx_::shifttable, WmPattern_::sids, WmPattern_::sids_size, and wm_tolower.
Referenced by WmPreparePatterns(), and WmPrintInfo().
uint32_t WmSearch2Hash9 (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 776 of file util-mpm-wumanber.c.
References WmCtx_::bloom, WmPattern_::ci, COUNT, WmPattern_::cs, MpmThreadCtx_::ctx, MpmCtx_::ctx, WmPattern_::flags, WmCtx_::hash, HASH9, WmPattern_::id, WmHashItem_::idx, WmPattern_::len, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), WmHashItem_::nxt, WmCtx_::parray, PatternMatcherQueue_::pattern_id_bitarray_size, WmCtx_::pminlen, WmPattern_::prefix_ci, WmPattern_::prefix_cs, WmCtx_::shiftlen, WmCtx_::shifttable, WmPattern_::sids, WmPattern_::sids_size, and wm_tolower.
Referenced by WmPreparePatterns(), and WmPrintInfo().
void WmThreadDestroyCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx)
Definition at line 1516 of file util-mpm-wumanber.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, and SCFree.
Referenced by MpmWuManberRegister().
void WmThreadInitCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, uint32_t matchsize)
Definition at line 1500 of file util-mpm-wumanber.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, and SCMalloc.
Referenced by MpmWuManberRegister().