suricata: src/util-conf.c File Reference
util-conf.c File Reference
#include "suricata-common.h"
#include "config.h"
#include "conf.h"
Functions
TmEcode ConfigSetLogDirectory (char *name)
char * ConfigGetLogDirectory ()
TmEcode ConfigCheckLogDirectory (char *log_dir)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file util-conf.c.
Function Documentation
TmEcode ConfigCheckLogDirectory (char * log_dir)
Definition at line 52 of file util-conf.c.
References SCEnter, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
char* ConfigGetLogDirectory ()
Definition at line 34 of file util-conf.c.
References ConfGet(), and DEFAULT_LOG_DIR.
Referenced by LogTcpDataLogInitCtx(), PcapLogProfileSetup(), SCConfLogOpenGeneric(), SCProfilingInit(), SCProfilingKeywordsGlobalInit(), SCProfilingRulesGlobalInit(), SetupFPAnalyzer(), SetupRuleAnalyzer(), and Unified2AlertOpenFileCtx().
TmEcode ConfigSetLogDirectory (char * name)
Definition at line 29 of file util-conf.c.
References ConfSetFinal(), TM_ECODE_FAILED, and TM_ECODE_OK.