suricata: src/util-decode-der-get.c File Reference
util-decode-der-get.c File Reference
#include "suricata-common.h"
#include "util-decode-der.h"
#include "util-decode-der-get.h"
Functions
const Asn1Generic * Asn1DerGet (const Asn1Generic *top, const uint8_t *seq_index, const uint32_t seqsz, uint32_t *errcode)
Iterate through an ASN.1 structure, following the index sequence. Context specific elements are skipped.
int Asn1DerGetIssuerDN (const Asn1Generic *cert, char *buffer, uint32_t length, uint32_t *errcode)
int Asn1DerGetSubjectDN (const Asn1Generic *cert, char *buffer, uint32_t length, uint32_t *errcode)
Detailed Description
Author
Pierre Chifflier pierr.nosp@m.e.ch.nosp@m.iffli.nosp@m.er@s.nosp@m.si.go.nosp@m.uv.f.nosp@m.r
Definition in file util-decode-der-get.c.
Function Documentation
const Asn1Generic* Asn1DerGet (const Asn1Generic * top, const uint8_t * seq_index, const uint32_t seqsz, uint32_t * errcode)
Iterate through an ASN.1 structure, following the index sequence. Context specific elements are skipped.
Return values
The matching node, or NULL
Definition at line 81 of file util-decode-der-get.c.
References ASN1_CLASS_CONTEXTSPEC, Asn1Generic_::data, ERR_DER_MISSING_ELEMENT, Asn1Generic_::header, Asn1Generic_::next, and top.
Referenced by Asn1DerGetIssuerDN(), and Asn1DerGetSubjectDN().
int Asn1DerGetIssuerDN (const Asn1Generic * cert, char * buffer, uint32_t length, uint32_t * errcode)
Definition at line 131 of file util-decode-der-get.c.
References ASN1_IA5STRING, ASN1_OCTETSTRING, ASN1_OID, ASN1_PRINTSTRING, ASN1_SEQUENCE, ASN1_SET, ASN1_T61STRING, ASN1_UTF8STRING, Asn1DerGet(), Asn1Generic_::data, ERR_DER_MISSING_ELEMENT, ERR_DER_UNSUPPORTED_STRING, Asn1Generic_::next, Asn1Generic_::str, strlcat(), and Asn1Generic_::type.
Referenced by DecodeTLSHandshakeServerCertificate().
int Asn1DerGetSubjectDN (const Asn1Generic * cert, char * buffer, uint32_t length, uint32_t * errcode)
Definition at line 204 of file util-decode-der-get.c.
References ASN1_IA5STRING, ASN1_OCTETSTRING, ASN1_OID, ASN1_PRINTSTRING, ASN1_SEQUENCE, ASN1_SET, ASN1_T61STRING, ASN1_UTF8STRING, Asn1DerGet(), Asn1Generic_::data, ERR_DER_MISSING_ELEMENT, ERR_DER_UNSUPPORTED_STRING, Asn1Generic_::next, Asn1Generic_::str, strlcat(), and Asn1Generic_::type.
Referenced by DecodeTLSHandshakeServerCertificate().