suricata: src/util-decode-mime.c File Reference
util-decode-mime.c File Reference
#include "suricata-common.h"
#include "util-decode-mime.h"
#include "util-spm-bs.h"
#include "util-unittest.h"
#include "util-memcmp.h"
#include "util-print.h"
Macros
#define CR 13
#define LF 10
#define CRLF "\r\n"
#define COLON 58
#define DASH 45
#define PRINTABLE_START 33
#define PRINTABLE_END 126
#define UC_START 65
#define UC_END 90
#define LC_START 97
#define LC_END 122
#define UC_LC_DIFF 32
#define EOL_LEN 2
#define BASE64_STR "Base64"
#define MAX_LINE_LEN 998 /* Def in RFC 2045, excluding CRLF sequence */
#define MAX_ENC_LINE_LEN 76 /* Def in RFC 2045, excluding CRLF sequence */
#define MAX_HEADER_NAME 75 /* 75 + ":" = 76 */
#define MAX_HEADER_VALUE 2000 /* Default - arbitrary limit */
#define BOUNDARY_BUF 256
#define CTNT_TYPE_STR "content-type"
#define CTNT_DISP_STR "content-disposition"
#define CTNT_TRAN_STR "content-transfer-encoding"
#define MSG_ID_STR "message-id"
#define BND_START_STR "boundary=\""
#define TOK_END_STR "\""
#define MSG_STR "message/"
#define MULTIPART_STR "multipart/"
#define QP_STR "quoted-printable"
#define TXT_STR "text/plain"
#define HTML_STR "text/html"
#define URL_STR "http://"
#define STACK_FREE_NODES 10
#define MAX_IP4_CHARS 15
#define MAX_IP6_CHARS 39
Functions
void MimeDecSetConfig (MimeDecConfig *config)
Set global config policy.
MimeDecConfig * MimeDecGetConfig (void)
Get global config policy.
void MimeDecFreeEntity (MimeDecEntity *entity)
Frees a mime entity tree.
void MimeDecFreeField (MimeDecField *field)
Iteratively frees a header field entry list.
void MimeDecFreeUrl (MimeDecUrl *url)
Iteratively frees a URL entry list.
MimeDecField * MimeDecAddField (MimeDecEntity *entity)
Creates and adds a header field entry to an entity.
int MimeDecFindFieldsForEach (const MimeDecEntity *entity, const char *name, int(*DataCallback)(const uint8_t *val, const size_t, void *data), void *data)
Searches for header fields with the specified name.
MimeDecField * MimeDecFindField (const MimeDecEntity *entity, const char *name)
Searches for a header field with the specified name.
MimeDecEntity * MimeDecAddEntity (MimeDecEntity *parent)
Creates and adds a child entity to the specified parent entity.
const char * MimeDecParseStateGetStatus (MimeDecParseState *state)
MimeDecParseState * MimeDecInitParser (void *data, int(*DataChunkProcessorFunc)(const uint8_t *chunk, uint32_t len, MimeDecParseState *state))
Init the parser by allocating memory for the state and top-level entity.
void MimeDecDeInitParser (MimeDecParseState *state)
De-Init parser by freeing up any residual memory.
int MimeDecParseComplete (MimeDecParseState *state)
Called to indicate that the last message line has been processed and the parsing operation is complete.
int MimeDecParseLine (const uint8_t *line, const uint32_t len, const uint8_t delim_len, MimeDecParseState *state)
Parse a line of a MIME message and update the parser state.
MimeDecEntity * MimeDecParseFullMsg (const uint8_t *buf, uint32_t blen, void *data, int(*dcpfunc)(const uint8_t *chunk, uint32_t len, MimeDecParseState *state))
Parses an entire message when available in its entirety (wraps the line-based parsing functions)
void MimeDecRegisterTests (void)
Detailed Description
Author
David Abarbanel david.nosp@m..aba.nosp@m.rbane.nosp@m.l@ba.nosp@m.esyst.nosp@m.ems..nosp@m.com
Definition in file util-decode-mime.c.
Macro Definition Documentation
#define BASE64_STR "Base64"
Definition at line 53 of file util-decode-mime.c.
#define BND_START_STR "boundary=\""
Definition at line 65 of file util-decode-mime.c.
#define BOUNDARY_BUF 256
Definition at line 60 of file util-decode-mime.c.
#define COLON 58
Definition at line 41 of file util-decode-mime.c.
#define CR 13
Definition at line 36 of file util-decode-mime.c.
Referenced by htp_chomp(), htp_is_line_empty(), htp_mpart_part_handle_data(), and htp_mpartp_parse().
#define CRLF "\r\n"
Definition at line 40 of file util-decode-mime.c.
#define CTNT_DISP_STR "content-disposition"
Definition at line 62 of file util-decode-mime.c.
#define CTNT_TRAN_STR "content-transfer-encoding"
Definition at line 63 of file util-decode-mime.c.
#define CTNT_TYPE_STR "content-type"
Definition at line 61 of file util-decode-mime.c.
#define DASH 45
Definition at line 42 of file util-decode-mime.c.
#define EOL_LEN 2
Definition at line 50 of file util-decode-mime.c.
#define HTML_STR "text/html"
Definition at line 71 of file util-decode-mime.c.
#define LC_END 122
Definition at line 48 of file util-decode-mime.c.
#define LC_START 97
Definition at line 47 of file util-decode-mime.c.
#define LF 10
Definition at line 37 of file util-decode-mime.c.
Referenced by htp_chomp(), htp_connp_REQ_BODY_CHUNKED_DATA_END(), htp_connp_REQ_BODY_CHUNKED_LENGTH(), htp_connp_REQ_CONNECT_PROBE_DATA(), htp_connp_REQ_HEADERS(), htp_connp_REQ_LINE(), htp_connp_RES_BODY_CHUNKED_DATA_END(), htp_connp_RES_BODY_CHUNKED_LENGTH(), htp_connp_RES_HEADERS(), htp_connp_RES_LINE(), htp_mpart_part_handle_data(), and htp_mpartp_parse().
#define MAX_ENC_LINE_LEN 76 /* Def in RFC 2045, excluding CRLF sequence */
Definition at line 57 of file util-decode-mime.c.
#define MAX_HEADER_NAME 75 /* 75 + ":" = 76 */
Definition at line 58 of file util-decode-mime.c.
#define MAX_HEADER_VALUE 2000 /* Default - arbitrary limit */
Definition at line 59 of file util-decode-mime.c.
Referenced by MimeDecSetConfig().
#define MAX_IP4_CHARS 15
Definition at line 78 of file util-decode-mime.c.
#define MAX_IP6_CHARS 39
Definition at line 79 of file util-decode-mime.c.
#define MAX_LINE_LEN 998 /* Def in RFC 2045, excluding CRLF sequence */
Definition at line 56 of file util-decode-mime.c.
#define MSG_ID_STR "message-id"
Definition at line 64 of file util-decode-mime.c.
#define MSG_STR "message/"
Definition at line 67 of file util-decode-mime.c.
#define MULTIPART_STR "multipart/"
Definition at line 68 of file util-decode-mime.c.
#define PRINTABLE_END 126
Definition at line 44 of file util-decode-mime.c.
#define PRINTABLE_START 33
Definition at line 43 of file util-decode-mime.c.
#define QP_STR "quoted-printable"
Definition at line 69 of file util-decode-mime.c.
#define STACK_FREE_NODES 10
Definition at line 75 of file util-decode-mime.c.
#define TOK_END_STR "\""
Definition at line 66 of file util-decode-mime.c.
#define TXT_STR "text/plain"
Definition at line 70 of file util-decode-mime.c.
#define UC_END 90
Definition at line 46 of file util-decode-mime.c.
#define UC_LC_DIFF 32
Definition at line 49 of file util-decode-mime.c.
#define UC_START 65
Definition at line 45 of file util-decode-mime.c.
#define URL_STR "http://"
Definition at line 72 of file util-decode-mime.c.
Function Documentation
MimeDecEntity* MimeDecAddEntity (MimeDecEntity * parent)
Creates and adds a child entity to the specified parent entity.
Parameters
parent The parent entity
Returns
The child entity, or NULL if the operation fails
Definition at line 398 of file util-decode-mime.c.
References MimeDecEntity::child, MimeDecEntity::next, SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, and unlikely.
MimeDecField* MimeDecAddField (MimeDecEntity * entity)
Creates and adds a header field entry to an entity.
The entity is optional. If NULL is specified, than a new stand-alone field is created.
Parameters
entity The parent entity
Returns
The field object, or NULL if the operation fails
Definition at line 278 of file util-decode-mime.c.
References MimeDecEntity::field_list, MimeDecField::next, SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, and unlikely.
void MimeDecDeInitParser (MimeDecParseState * state)
De-Init parser by freeing up any residual memory.
Parameters
state The parser state
Returns
none
Definition at line 2428 of file util-decode-mime.c.
References ANOM_MALFORMED_MSG, MimeDecEntity::anomaly_flags, MimeDecStackNode::data, MimeDecParseState::hname, MimeDecParseState::hvalue, MimeDecParseState::msg, SCFree, SCLogDebug, MimeDecParseState::stack, and MimeDecStack::top.
Referenced by MimeDecParseFullMsg().
MimeDecField* MimeDecFindField (const MimeDecEntity * entity, const char * name)
Searches for a header field with the specified name.
Parameters
entity The entity to search
name The header name (lowercase)
Returns
The field object, or NULL if not found
Definition at line 338 of file util-decode-mime.c.
References MimeDecEntity::field_list, MimeDecField::name, MimeDecField::name_len, MimeDecField::next, SCMemcmp, and Asn1Generic_::strlen.
int MimeDecFindFieldsForEach (const MimeDecEntity * entity, const char * name, int(*)(const uint8_t *val, const size_t, void *data) DataCallback, void * data)
Searches for header fields with the specified name.
Parameters
entity The entity to search
name The header name (lowercase)
Returns
number of items found
Definition at line 310 of file util-decode-mime.c.
References MimeDecEntity::field_list, MimeDecField::name, MimeDecField::name_len, MimeDecField::next, SCMemcmp, Asn1Generic_::strlen, MimeDecField::value, and MimeDecField::value_len.
void MimeDecFreeEntity (MimeDecEntity * entity)
Frees a mime entity tree.
Parameters
entity The root entity
Returns
none
Move child to next Transform tree into list
Move to next element
Definition at line 181 of file util-decode-mime.c.
References MimeDecEntity::child, MimeDecEntity::field_list, MimeDecEntity::filename, MimeDecFreeField(), MimeDecFreeUrl(), MimeDecEntity::next, SCFree, and MimeDecEntity::url_list.
Referenced by MimeDecParseFullMsg().
void MimeDecFreeField (MimeDecField * field)
Iteratively frees a header field entry list.
Parameters
field The header field
Returns
none
Definition at line 220 of file util-decode-mime.c.
References MimeDecField::name, MimeDecField::next, SCFree, and MimeDecField::value.
Referenced by MimeDecFreeEntity().
void MimeDecFreeUrl (MimeDecUrl * url)
Iteratively frees a URL entry list.
Parameters
url The url entry
Returns
none
Definition at line 249 of file util-decode-mime.c.
References MimeDecUrl::next, SCFree, and MimeDecUrl::url.
Referenced by MimeDecFreeEntity().
MimeDecConfig* MimeDecGetConfig (void)
Get global config policy.
Returns
config data structure
Definition at line 151 of file util-decode-mime.c.
MimeDecParseState* MimeDecInitParser (void * data, int(*)(const uint8_t *chunk, uint32_t len, MimeDecParseState *state) DataChunkProcessorFunc)
Init the parser by allocating memory for the state and top-level entity.
Parameters
data A caller-specified pointer to data for access within the data chunk processor callback function
dcpfunc The data chunk processor callback function
Returns
A pointer to the state object, or NULL if the operation fails
Definition at line 2372 of file util-decode-mime.c.
References MimeDecEntity::ctnt_flags, CTNT_IS_MSG, MimeDecStackNode::data, MimeDecParseState::data, data, MimeDecParseState::DataChunkProcessorFunc, HEADER_READY, MimeDecParseState::msg, SC_ERR_MEM_ALLOC, SCFree, SCLogError, SCMalloc, MimeDecParseState::stack, MimeDecParseState::state_flag, MimeDecStack::top, and unlikely.
Referenced by MimeDecParseFullMsg().
int MimeDecParseComplete (MimeDecParseState * state)
Called to indicate that the last message line has been processed and the parsing operation is complete.
This function should be called directly by the caller.
Parameters
state The parser state
Returns
MIME_DEC_OK on success, otherwise < 0 on failure
Definition at line 2466 of file util-decode-mime.c.
References ANOM_MALFORMED_MSG, MimeDecEntity::anomaly_flags, MimeDecStackNode::is_encap, MIME_DEC_ERR_DATA, MIME_DEC_OK, MimeDecParseState::msg, MimeDecStackNode::next, PARSE_DONE, SCLogDebug, MimeDecParseState::stack, MimeDecParseState::state_flag, and MimeDecStack::top.
Referenced by MimeDecParseFullMsg().
MimeDecEntity* MimeDecParseFullMsg (const uint8_t * buf, uint32_t blen, void * data, int(*)(const uint8_t *chunk, uint32_t len, MimeDecParseState *state) dcpfunc)
Parses an entire message when available in its entirety (wraps the line-based parsing functions)
Parameters
buf Buffer pointing to the full message
blen Length of the buffer
data Caller data to be available in callback
dcpfunc Callback for processing each decoded body data chunk
Returns
A pointer to the decoded MIME message, or NULL if the operation fails
Definition at line 2557 of file util-decode-mime.c.
References MimeDecParseState::current_line_delimiter_len, MIME_DEC_OK, MimeDecDeInitParser(), MimeDecFreeEntity(), MimeDecInitParser(), MimeDecParseComplete(), MimeDecParseLine(), MimeDecParseState::msg, msg, and SCLogDebug.
int MimeDecParseLine (const uint8_t * line, const uint32_t len, const uint8_t delim_len, MimeDecParseState * state)
Parse a line of a MIME message and update the parser state.
Parameters
line A string representing the line (w/out CRLF)
len The length of the line
delim_len The length of the line end delimiter
state The parser state
Returns
MIME_DEC_OK on success, otherwise < 0 on failure
Definition at line 2523 of file util-decode-mime.c.
References MimeDecParseState::current_line_delimiter_len, MIME_DEC_OK, PARSE_ERROR, SC_LOG_DEBUG, SCLogDebug, and MimeDecParseState::state_flag.
Referenced by MimeDecParseFullMsg().
const char* MimeDecParseStateGetStatus (MimeDecParseState * state)
Definition at line 2304 of file util-decode-mime.c.
References MimeDecParseState::state_flag.
void MimeDecRegisterTests (void)
Definition at line 2991 of file util-decode-mime.c.
Referenced by RunUnittests().
void MimeDecSetConfig (MimeDecConfig * config)
Set global config policy.
Parameters
config Config policy to set
Returns
none
Definition at line 132 of file util-decode-mime.c.
References MimeDecConfig::header_value_depth, MAX_HEADER_VALUE, SC_ERR_MISSING_CONFIG_PARAM, and SCLogWarning.