suricata: src/util-classification-config.c File Reference
util-classification-config.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-engine.h"
#include "util-hash.h"
#include "conf.h"
#include "util-classification-config.h"
#include "util-unittest.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-fmemopen.h"
Macros
#define DETECT_CLASSCONFIG_REGEX "^\\s*config\\s*classification\\s*:\\s*([a-zA-Z][a-zA-Z0-9-_]*)\\s*,\\s*(.+)\\s*,\\s*(\\d+)\\s*$"
#define SC_CLASS_CONF_DEF_CONF_FILEPATH CONFIG_DIR "/classification.config"
#define MAX_SUBSTRINGS 30
Functions
uint32_t SCClassConfClasstypeHashFunc (HashTable *ht, void *data, uint16_t datalen)
Hashing function to be used to hash the Classtype name. Would be supplied as an argument to the HashTableInit function for DetectEngineCtx->class_conf_ht.
char SCClassConfClasstypeHashCompareFunc (void *data1, uint16_t datalen1, void *data2, uint16_t datalen2)
Used to compare two Classtypes that have been stored in the HashTable. This function is supplied as an argument to the HashTableInit function for DetectionEngineCtx->class_conf_ct.
void SCClassConfClasstypeHashFree (void *ch)
Used to free the Classification Config Hash Data that was stored in DetectEngineCtx->class_conf_ht Hashtable.
void SCClassConfInit (void)
void SCClassConfDeinit (void)
FILE * SCClassConfInitContextAndLocalResources (DetectEngineCtx *de_ctx, FILE *fd)
Inits the context to be used by the Classification Config parsing API.
void SCClassConfDeInitContext (DetectEngineCtx *de_ctx)
Releases resources used by the Classification Config API.
int SCClassConfAddClasstype (char *rawstr, uint8_t index, DetectEngineCtx *de_ctx)
Parses a line from the classification file and adds it to Classtype hash table in DetectEngineCtx, i.e. DetectEngineCtx->class_conf_ht.
void SCClassConfParseFile (DetectEngineCtx *de_ctx, FILE *fd)
Parses the Classification Config file and updates the DetectionEngineCtx->class_conf_ht with the Classtype information.
SCClassConfClasstype * SCClassConfAllocClasstype (uint8_t classtype_id, const char *classtype, const char *classtype_desc, int priority)
Returns a new SCClassConfClasstype instance. The classtype string is converted into lowercase, before being assigned to the instance.
void SCClassConfDeAllocClasstype (SCClassConfClasstype *ct)
Frees a SCClassConfClasstype instance.
void SCClassConfLoadClassficationConfigFile (DetectEngineCtx *de_ctx, FILE *fd)
Loads the Classtype info from the classification.config file.
SCClassConfClasstype * SCClassConfGetClasstype (const char *ct_name, DetectEngineCtx *de_ctx)
Gets the classtype from the corresponding hash table stored in the Detection Engine Context's class conf ht, given the classtype name.
void SCClassConfRegisterTests (void)
This function registers unit tests for Classification Config API.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Used for parsing a classification.config file
Definition in file util-classification-config.c.
Macro Definition Documentation
#define DETECT_CLASSCONFIG_REGEX "^\\s*config\\s*classification\\s*:\\s*([a-zA-Z][a-zA-Z0-9-_]*)\\s*,\\s*(.+)\\s*,\\s*(\\d+)\\s*$"
Definition at line 41 of file util-classification-config.c.
Referenced by SCClassConfInit().
#define MAX_SUBSTRINGS 30
Referenced by SCClassConfAddClasstype().
#define SC_CLASS_CONF_DEF_CONF_FILEPATH CONFIG_DIR "/classification.config"
Definition at line 47 of file util-classification-config.c.
Function Documentation
int SCClassConfAddClasstype (char * rawstr, uint8_t index, DetectEngineCtx * de_ctx)
Parses a line from the classification file and adds it to Classtype hash table in DetectEngineCtx, i.e. DetectEngineCtx->class_conf_ht.
Parameters
rawstr Pointer to the string to be parsed.
index Relative index of the string to be parsed.
de_ctx Pointer to the Detection Engine Context.
Return values
0 On success.
-1 On failure.
Definition at line 247 of file util-classification-config.c.
References DetectEngineCtx_::class_conf_ht, SCClassConfClasstype_::classtype, SCClassConfClasstype_::classtype_desc, HashTableAdd(), HashTableLookup(), index, MAX_SUBSTRINGS, SC_ERR_INVALID_SIGNATURE, SCClassConfAllocClasstype(), SCFree, SCLogDebug, SCLogError, and SCLogInfo.
Referenced by SCClassConfParseFile().
SCClassConfClasstype* SCClassConfAllocClasstype (uint8_t classtype_id, const char * classtype, const char * classtype_desc, int priority)
Returns a new SCClassConfClasstype instance. The classtype string is converted into lowercase, before being assigned to the instance.
Parameters
classtype Pointer to the classification type.
classtype_desc Pointer to the classification type description.
priority Holds the priority for the classification type.
Return values
ct Pointer to the new instance of SCClassConfClasstype on success; NULL on failure.
Definition at line 387 of file util-classification-config.c.
References SCClassConfClasstype_::classtype, SCClassConfClasstype_::classtype_desc, SCClassConfClasstype_::classtype_id, SCClassConfClasstype_::priority, SC_ERR_MEM_ALLOC, SCClassConfDeAllocClasstype(), SCLogError, SCMalloc, and SCStrdup.
Referenced by SCClassConfAddClasstype().
char SCClassConfClasstypeHashCompareFunc (void * data1, uint16_t datalen1, void * data2, uint16_t datalen2)
Used to compare two Classtypes that have been stored in the HashTable. This function is supplied as an argument to the HashTableInit function for DetectionEngineCtx->class_conf_ct.
Parameters
data1 Pointer to the first SCClassConfClasstype to be compared.
len1 Not used by this function.
data2 Pointer to the second SCClassConfClasstype to be compared.
len2 Not used by this function.
Return values
1 On data1 and data2 being equal.
0 On data1 and data2 not being equal.
Definition at line 481 of file util-classification-config.c.
References SCClassConfClasstype_::classtype, and SCLogDebug.
Referenced by SCClassConfInitContextAndLocalResources().
void SCClassConfClasstypeHashFree (void * ch)
Used to free the Classification Config Hash Data that was stored in DetectEngineCtx->class_conf_ht Hashtable.
Parameters
ch Pointer to the data that has to be freed.
Definition at line 512 of file util-classification-config.c.
References SCClassConfDeAllocClasstype().
Referenced by SCClassConfInitContextAndLocalResources().
uint32_t SCClassConfClasstypeHashFunc (HashTable * ht, void * data, uint16_t datalen)
Hashing function to be used to hash the Classtype name. Would be supplied as an argument to the HashTableInit function for DetectEngineCtx->class_conf_ht.
Parameters
ht Pointer to the HashTable.
data Pointer to the data to be hashed. In this case, the data would be a pointer to a SCClassConfClasstype instance.
datalen Not used by this function.
Definition at line 452 of file util-classification-config.c.
References HashTable_::array_size, SCClassConfClasstype_::classtype, and len.
Referenced by SCClassConfInitContextAndLocalResources().
void SCClassConfDeAllocClasstype (SCClassConfClasstype * ct)
Frees a SCClassConfClasstype instance.
Parameters
Pointer to the SCClassConfClasstype instance that has to be freed
Definition at line 427 of file util-classification-config.c.
References SCClassConfClasstype_::classtype, SCClassConfClasstype_::classtype_desc, and SCFree.
Referenced by SCClassConfAllocClasstype(), and SCClassConfClasstypeHashFree().
void SCClassConfDeinit (void)
Definition at line 82 of file util-classification-config.c.
Referenced by main().
void SCClassConfDeInitContext (DetectEngineCtx * de_ctx)
Releases resources used by the Classification Config API.
Definition at line 202 of file util-classification-config.c.
References DetectEngineCtx_::class_conf_ht, and HashTableFree().
Referenced by DetectEngineCtxFree().
SCClassConfClasstype* SCClassConfGetClasstype (const char * ct_name, DetectEngineCtx * de_ctx)
Gets the classtype from the corresponding hash table stored in the Detection Engine Context's class conf ht, given the classtype name.
Parameters
ct_name Pointer to the classtype name that has to be looked up.
de_ctx Pointer to the Detection Engine Context.
Return values
lookup_ct_info Pointer to the SCClassConfClasstype instance from the hash table on success; NULL on failure.
Definition at line 562 of file util-classification-config.c.
References DetectEngineCtx_::class_conf_ht, and HashTableLookup().
void SCClassConfInit (void)
Definition at line 59 of file util-classification-config.c.
References DETECT_CLASSCONFIG_REGEX, and SCLogDebug.
Referenced by main(), and RunUnittests().
FILE* SCClassConfInitContextAndLocalResources (DetectEngineCtx * de_ctx, FILE * fd)
Inits the context to be used by the Classification Config parsing API.
   This function initializes the hash table to be used by the Detection
   Engine Context to hold the data from the classification.config file,
   obtains the file desc to parse the classification.config file, and
   inits the regex used to parse the lines from classification.config
   file.
Parameters
de_ctx Pointer to the Detection Engine Context.
Return values
fp NULL on error
Definition at line 108 of file util-classification-config.c.
References DetectEngineCtx_::class_conf_ht, HashTableFree(), HashTableInit(), RunmodeIsUnittests(), SC_ERR_FOPEN, SC_ERR_HASH_TABLE_INIT, SCClassConfClasstypeHashCompareFunc(), SCClassConfClasstypeHashFree(), SCClassConfClasstypeHashFunc(), and SCLogError.
Referenced by SCClassConfLoadClassficationConfigFile().
void SCClassConfLoadClassficationConfigFile (DetectEngineCtx * de_ctx, FILE * fd)
Loads the Classtype info from the classification.config file.
   The classification.config file contains the different classtypes,
   that can be used to label Signatures.  Each line of the file should
   have the following format -
   classtype_name, classtype_description, priority
   None of the above parameters should hold a quote inside the file.
Parameters
de_ctx Pointer to the Detection Engine Context that should be updated with Classtype information.
Definition at line 531 of file util-classification-config.c.
References RunmodeIsUnittests(), SC_ERR_OPENING_FILE, SCClassConfInitContextAndLocalResources(), SCClassConfParseFile(), and SCLogError.
void SCClassConfParseFile (DetectEngineCtx * de_ctx, FILE * fd)
Parses the Classification Config file and updates the DetectionEngineCtx->class_conf_ht with the Classtype information.
Parameters
de_ctx Pointer to the Detection Engine Context.
Definition at line 355 of file util-classification-config.c.
References DetectEngineCtx_::class_conf_ht, SCClassConfAddClasstype(), and SCLogInfo.
Referenced by SCClassConfLoadClassficationConfigFile().
void SCClassConfRegisterTests (void)
This function registers unit tests for Classification Config API.
Definition at line 825 of file util-classification-config.c.
Referenced by RunUnittests().