suricata: src/util-threshold-config.h File Reference
util-threshold-config.h File Reference
Functions
void SCThresholdConfDeInitContext (DetectEngineCtx *, FILE *)
Releases resources used by the Threshold Config API.
void SCThresholdConfParseFile (DetectEngineCtx *, FILE *)
Parses the Threshold Config file.
int SCThresholdConfInitContext (DetectEngineCtx *, FILE *)
Inits the context to be used by the Threshold Config parsing API.
void SCThresholdConfRegisterTests ()
This function registers unit tests for Classification Config API.
Detailed Description
Author
Breno Silva Pinto breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Definition in file util-threshold-config.h.
Function Documentation
void SCThresholdConfDeInitContext (DetectEngineCtx * de_ctx, FILE * fd)
Releases resources used by the Threshold Config API.
Parameters
de_ctx Pointer to the Detection Engine Context.
fd Pointer to file descriptor.
Definition at line 226 of file util-threshold-config.c.
Referenced by SCThresholdConfInitContext().
int SCThresholdConfInitContext (DetectEngineCtx * de_ctx, FILE * utfd)
Inits the context to be used by the Threshold Config parsing API.
   This function initializes the hash table to be used by the Detection
   Engine Context to hold the data from the threshold.config file,
   obtains the file desc to parse the threshold.config file, and
   inits the regex used to parse the lines from threshold.config
   file.
Parameters
de_ctx Pointer to the Detection Engine Context.
utfd Pointer for unit test file descriptor.
Return values
0 On success.
-1 On failure.
Definition at line 145 of file util-threshold-config.c.
References DETECT_BASE_REGEX, DETECT_RATE_REGEX, DETECT_SUPPRESS_REGEX, DETECT_THRESHOLD_REGEX, SC_ERR_FOPEN, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SCLogWarning, SCThresholdConfDeInitContext(), and SCThresholdConfParseFile().
Referenced by DetectEngineReload().
void SCThresholdConfParseFile (DetectEngineCtx * de_ctx, FILE * fd)
Parses the Threshold Config file.
Parameters
de_ctx Pointer to the Detection Engine Context.
fd Pointer to file descriptor.
Definition at line 1132 of file util-threshold-config.c.
References len, SC_ERR_MEM_ALLOC, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, SCRealloc, SCThresholdConfAddThresholdtype(), SCThresholdConfIsLineBlankOrComment(), SCThresholdConfLineIsMultiline(), SCThresholdConfLineLength(), and unlikely.
Referenced by SCThresholdConfInitContext().
void SCThresholdConfRegisterTests ()
This function registers unit tests for Classification Config API.
Definition at line 2879 of file util-threshold-config.c.
Referenced by RunUnittests().