suricata: src/util-runmodes.c File Reference
util-runmodes.c File Reference
#include "suricata-common.h"
#include "config.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-af-packet.h"
#include "log-httplog.h"
#include "output.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "alert-fastlog.h"
#include "alert-prelude.h"
#include "alert-unified2-alert.h"
#include "alert-debuglog.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-device.h"
#include "util-runmodes.h"
#include "flow-hash.h"
Functions
void RunmodeSetFlowStreamAsync (void)
int RunmodeGetFlowStreamAsync (void)
char * RunmodeAutoFpCreatePickupQueuesString (int n)
create a queue string for autofp to pass to the flow queue handler.
int RunModeSetLiveCaptureAutoFp (ConfigIfaceParserFunc ConfigParser, ConfigIfaceThreadsCountFunc ModThreadsCount, char *recv_mod_name, char *decode_mod_name, char *thread_name, const char *live_dev)
int RunModeSetLiveCaptureWorkers (ConfigIfaceParserFunc ConfigParser, ConfigIfaceThreadsCountFunc ModThreadsCount, char *recv_mod_name, char *decode_mod_name, char *thread_name, const char *live_dev)
int RunModeSetLiveCaptureSingle (ConfigIfaceParserFunc ConfigParser, ConfigIfaceThreadsCountFunc ModThreadsCount, char *recv_mod_name, char *decode_mod_name, char *thread_name, const char *live_dev)
int RunModeSetIPSAutoFp (ConfigIPSParserFunc ConfigParser, char *recv_mod_name, char *verdict_mod_name, char *decode_mod_name)
int RunModeSetIPSWorker (ConfigIPSParserFunc ConfigParser, char *recv_mod_name, char *verdict_mod_name, char *decode_mod_name)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Helper function for runmode.
Definition in file util-runmodes.c.
Function Documentation
char* RunmodeAutoFpCreatePickupQueuesString (int n)
create a queue string for autofp to pass to the flow queue handler.
The string will be "pickup1,pickup2,pickup3\0"
Definition at line 74 of file util-runmodes.c.
References SC_ERR_MEM_ALLOC, SCLogDebug, SCLogError, SCMalloc, strlcat(), TM_QUEUE_NAME_MAX, and unlikely.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeSetIPSAutoFp(), and RunModeSetLiveCaptureAutoFp().
int RunmodeGetFlowStreamAsync (void)
Definition at line 64 of file util-runmodes.c.
Referenced by StreamTcpThreadInit().
void RunmodeSetFlowStreamAsync (void)
Definition at line 58 of file util-runmodes.c.
References FlowDisableTcpReuseHandling().
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeSetIPSAutoFp(), and RunModeSetLiveCaptureAutoFp().
int RunModeSetIPSAutoFp (ConfigIPSParserFunc ConfigParser, char * recv_mod_name, char * verdict_mod_name, char * decode_mod_name)
Definition at line 482 of file util-runmodes.c.
References DETECT_CPU_SET, DetectEngineEnabled(), LiveGetDeviceCount(), LiveGetDeviceName(), RECEIVE_CPU_SET, RunmodeAutoFpCreatePickupQueuesString(), RunmodeSetFlowStreamAsync(), SC_ERR_MEM_ALLOC, SC_ERR_RUNMODE, SCEnter, SCFree, SCLogDebug, SCLogError, SCStrdup, SetupOutputs(), ThreadVars_::thread_group_name, threading_detect_ratio, TM_ECODE_OK, TM_QUEUE_NAME_MAX, TM_THREAD_NAME_MAX, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadGetNbThreads(), TmThreadSetCPU(), TmThreadSpawn(), unlikely, UtilCpuGetNumProcessorsOnline(), and VERDICT_CPU_SET.
Referenced by RunModeIpsIPFWAutoFp(), and RunModeIpsNFQAutoFp().
int RunModeSetIPSWorker (ConfigIPSParserFunc ConfigParser, char * recv_mod_name, char * verdict_mod_name, char * decode_mod_name)
Definition at line 659 of file util-runmodes.c.
References DETECT_CPU_SET, DetectEngineEnabled(), LiveGetDeviceCount(), LiveGetDeviceName(), SC_ERR_INVALID_VALUE, SC_ERR_RUNMODE, SC_ERR_THREAD_CREATE, SCLogError, SCStrdup, SetupOutputs(), TM_ECODE_OK, TM_THREAD_NAME_MAX, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadSetCPU(), TmThreadSpawn(), and unlikely.
Referenced by RunModeIpsIPFWWorker(), and RunModeIpsNFQWorker().
int RunModeSetLiveCaptureAutoFp (ConfigIfaceParserFunc ConfigParser, ConfigIfaceThreadsCountFunc ModThreadsCount, char * recv_mod_name, char * decode_mod_name, char * thread_name, const char * live_dev)
Definition at line 103 of file util-runmodes.c.
References DETECT_CPU_SET, DetectEngineEnabled(), LiveGetDeviceCount(), LiveGetDeviceName(), RECEIVE_CPU_SET, RunmodeAutoFpCreatePickupQueuesString(), RunmodeSetFlowStreamAsync(), SC_ERR_MEM_ALLOC, SC_ERR_RUNMODE, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCStrdup, SetupOutputs(), ThreadVars_::thread_group_name, threading_detect_ratio, TM_ECODE_OK, TM_QUEUE_NAME_MAX, TM_THREAD_NAME_MAX, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadGetNbThreads(), TmThreadSetCPU(), TmThreadSpawn(), unlikely, and UtilCpuGetNumProcessorsOnline().
Referenced by RunModeIdsAFPAutoFp(), RunModeIdsErfDagAutoFp(), RunModeIdsNetmapAutoFp(), RunModeIdsNflogAutoFp(), RunModeIdsPcapAutoFp(), and RunModeIdsPfringAutoFp().
int RunModeSetLiveCaptureSingle (ConfigIfaceParserFunc ConfigParser, ConfigIfaceThreadsCountFunc ModThreadsCount, char * recv_mod_name, char * decode_mod_name, char * thread_name, const char * live_dev)
Definition at line 446 of file util-runmodes.c.
References LiveGetDeviceCount(), LiveGetDeviceName(), SC_ERR_RUNMODE, and SCLogError.
Referenced by RunModeIdsAFPSingle(), RunModeIdsErfDagSingle(), RunModeIdsNetmapSingle(), RunModeIdsNflogSingle(), RunModeIdsPcapSingle(), and RunModeIdsPfringSingle().
int RunModeSetLiveCaptureWorkers (ConfigIfaceParserFunc ConfigParser, ConfigIfaceThreadsCountFunc ModThreadsCount, char * recv_mod_name, char * decode_mod_name, char * thread_name, const char * live_dev)
Definition at line 411 of file util-runmodes.c.
References LiveGetDeviceCount(), LiveGetDeviceName(), SC_ERR_MEM_ALLOC, SCLogError, SCStrdup, and unlikely.
Referenced by RunModeIdsAFPWorkers(), RunModeIdsErfDagWorkers(), RunModeIdsNetmapWorkers(), RunModeIdsNflogWorkers(), RunModeIdsPcapWorkers(), and RunModeIdsPfringWorkers().