suricata: src/util-syslog.c File Reference
util-syslog.c File Reference
#include "suricata-common.h"
Functions
SCEnumCharMap * SCSyslogGetFacilityMap ()
returns the syslog facility enum map
SCEnumCharMap * SCSyslogGetLogLevelMap ()
returns the syslog facility enum map
Variables
SCEnumCharMap sc_syslog_facility_map []
SCEnumCharMap sc_syslog_level_map []
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Syslog utility file
Definition in file util-syslog.c.
Function Documentation
SCEnumCharMap* SCSyslogGetFacilityMap (void)
returns the syslog facility enum map
Definition at line 56 of file util-syslog.c.
References sc_syslog_facility_map.
Referenced by AlertSyslogInitCtx(), SCLogInitOPIfaceCtx(), and SCLogLoadConfig().
SCEnumCharMap* SCSyslogGetLogLevelMap (void)
returns the syslog facility enum map
Definition at line 74 of file util-syslog.c.
References sc_syslog_level_map.
Referenced by AlertSyslogInitCtx().
Variable Documentation
SCEnumCharMap sc_syslog_facility_map[]
Initial value:
= {
    { "auth",           LOG_AUTH },
    { "authpriv",       LOG_AUTHPRIV },
    { "cron",           LOG_CRON },
    { "daemon",         LOG_DAEMON },
    { "ftp",            LOG_FTP },
    { "kern",           LOG_KERN },
    { "lpr",            LOG_LPR },
    { "mail",           LOG_MAIL },
    { "news",           LOG_NEWS },
    { "security",       LOG_AUTH },
    { "syslog",         LOG_SYSLOG },
    { "user",           LOG_USER },
    { "uucp",           LOG_UUCP },
    { "local0",         LOG_LOCAL0 },
    { "local1",         LOG_LOCAL1 },
    { "local2",         LOG_LOCAL2 },
    { "local3",         LOG_LOCAL3 },
    { "local4",         LOG_LOCAL4 },
    { "local5",         LOG_LOCAL5 },
    { "local6",         LOG_LOCAL6 },
    { "local7",         LOG_LOCAL7 },
    { NULL,             -1         }
}
Definition at line 30 of file util-syslog.c.
Referenced by SCSyslogGetFacilityMap().
SCEnumCharMap sc_syslog_level_map[]
Initial value:
= {
    { "Emergency",      LOG_EMERG },
    { "Alert",          LOG_ALERT },
    { "Critical",       LOG_CRIT },
    { "Error",          LOG_ERR },
    { "Warning",        LOG_WARNING },
    { "Notice",         LOG_NOTICE },
    { "Info",           LOG_INFO },
    { "Debug",          LOG_DEBUG },
    { NULL,             -1 }
}
Definition at line 61 of file util-syslog.c.
Referenced by SCSyslogGetLogLevelMap().