suricata: src/util-cuda-handlers.h File Reference
util-cuda-handlers.h File Reference
#include "conf.h"
#include "util-cuda.h"
Macros
#define CUDA_HANDLER_MODULE_DATA_TYPE_MEMORY_HOST 0
#define CUDA_HANDLER_MODULE_DATA_TYPE_MEMORY_DEVICE 1
#define CUDA_HANDLER_MODULE_DATA_TYPE_CUDA_BUFFER 2
Functions
void CudaHandlerAddCudaProfileFromConf (const char *name, void *(*Callback)(ConfNode *node), void(*Free)(void *))
void * CudaHandlerGetCudaProfile (const char *name)
void CudaHandlerFreeProfiles (void)
CUcontext CudaHandlerModuleGetContext (const char *module_name, int device_id)
void CudaHandlerModuleStoreData (const char *module_name, const char *data_name, void *data_ptr)
void * CudaHandlerModuleGetData (const char *module_name, const char *data_name)
int CudaHandlerGetCudaModule (CUmodule *p_module, const char *ptx_image)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-cuda-handlers.h.
Macro Definition Documentation
#define CUDA_HANDLER_MODULE_DATA_TYPE_CUDA_BUFFER 2
Definition at line 42 of file util-cuda-handlers.h.
#define CUDA_HANDLER_MODULE_DATA_TYPE_MEMORY_DEVICE 1
Definition at line 41 of file util-cuda-handlers.h.
#define CUDA_HANDLER_MODULE_DATA_TYPE_MEMORY_HOST 0
Definition at line 40 of file util-cuda-handlers.h.
Function Documentation
void CudaHandlerAddCudaProfileFromConf (const char * name, void *(*)(ConfNode *node) Callback, void(*)(void *) Free)
void CudaHandlerFreeProfiles (void)
Referenced by main(), and RunUnittests().
int CudaHandlerGetCudaModule (CUmodule * p_module, const char * ptx_image)
void* CudaHandlerGetCudaProfile (const char * name)
Referenced by SigGroupBuild().
CUcontext CudaHandlerModuleGetContext (const char * module_name, int device_id)
Referenced by SigGroupBuild().
void* CudaHandlerModuleGetData (const char * module_name, const char * data_name)
void CudaHandlerModuleStoreData (const char * module_name, const char * data_name, void * data_ptr)