suricata: src/util-mpm-b2g.h File Reference
util-mpm-b2g.h File Reference
#include "util-mpm.h"
#include "util-bloomfilter.h"
Data Structures
struct B2gPattern_
struct B2gCtx_
struct B2gThreadCtx_
Macros
#define B2G_HASHSHIFT_MAX 8
#define B2G_HASHSHIFT_HIGHER 7
#define B2G_HASHSHIFT_HIGH 6
#define B2G_HASHSHIFT_MEDIUM 5
#define B2G_HASHSHIFT_LOW 4
#define B2G_HASHSHIFT_LOWEST 3
#define B2G_TYPE uint32_t
#define B2G_WORD_SIZE 32
#define B2G_Q 2
#define B2G_SEARCHFUNC B2gSearchBNDMq
Typedefs
typedef struct B2gPattern_ B2gPattern
typedef struct B2gCtx_ B2gCtx
typedef struct B2gThreadCtx_ B2gThreadCtx
Functions
void MpmB2gRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-mpm-b2g.h.
Macro Definition Documentation
#define B2G_HASHSHIFT_HIGH 6
Definition at line 32 of file util-mpm-b2g.h.
#define B2G_HASHSHIFT_HIGHER 7
Definition at line 31 of file util-mpm-b2g.h.
#define B2G_HASHSHIFT_LOW 4
Definition at line 34 of file util-mpm-b2g.h.
#define B2G_HASHSHIFT_LOWEST 3
Definition at line 35 of file util-mpm-b2g.h.
#define B2G_HASHSHIFT_MAX 8
Definition at line 30 of file util-mpm-b2g.h.
#define B2G_HASHSHIFT_MEDIUM 5
Definition at line 33 of file util-mpm-b2g.h.
#define B2G_Q 2
Definition at line 46 of file util-mpm-b2g.h.
Referenced by B2gBuildMatchArray(), and B2gSearchBNDMq().
#define B2G_SEARCHFUNC B2gSearchBNDMq
Definition at line 48 of file util-mpm-b2g.h.
#define B2G_TYPE uint32_t
Definition at line 38 of file util-mpm-b2g.h.
Referenced by B2gBuildMatchArray(), B2gDestroyCtx(), B2gSearch(), and B2gSearchBNDMq().
#define B2G_WORD_SIZE 32
Definition at line 42 of file util-mpm-b2g.h.
Referenced by B2gPreparePatterns(), and MpmB2gRegister().
Typedef Documentation
typedef struct B2gCtx_ B2gCtx
typedef struct B2gPattern_ B2gPattern
typedef struct B2gThreadCtx_ B2gThreadCtx
Function Documentation
void MpmB2gRegister (void)
Definition at line 84 of file util-mpm-b2g.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, B2G_WORD_SIZE, B2gAddPatternCI(), B2gAddPatternCS(), B2gDestroyCtx(), B2gInitCtx(), B2gPreparePatterns(), B2gPrintInfo(), B2gPrintSearchStats(), B2gRegisterTests(), B2gSearchWrap(), B2gThreadDestroyCtx(), B2gThreadInitCtx(), MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, MPM_B2G, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, and MpmTableElmt_::Search.
Referenced by MpmTableSetup().