suricata: src/util-mpm-b3g.c File Reference
util-mpm-b3g.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "util-bloomfilter.h"
#include "util-mpm-b3g.h"
#include "util-unittest.h"
#include "conf.h"
#include "util-debug.h"
#include "util-memcpy.h"
Macros
#define INIT_HASH_SIZE 65536
#define COUNT(counter)
#define B3G_HASH(a, b, c) (((a) << b3g_hash_shift) | (b) << (b3g_hash_shift2) |(c))
Functions
void B3gInitCtx (MpmCtx *)
void B3gThreadInitCtx (MpmCtx *, MpmThreadCtx *, uint32_t)
void B3gDestroyCtx (MpmCtx *)
void B3gThreadDestroyCtx (MpmCtx *, MpmThreadCtx *)
int B3gAddPatternCI (MpmCtx *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
int B3gAddPatternCS (MpmCtx *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
int B3gPreparePatterns (MpmCtx *)
uint32_t B3gSearchWrap (MpmCtx *, MpmThreadCtx *, PatternMatcherQueue *, uint8_t *, uint16_t)
uint32_t B3gSearch1 (MpmCtx *, MpmThreadCtx *, PatternMatcherQueue *, uint8_t *, uint16_t)
uint32_t B3gSearch2 (MpmCtx *, MpmThreadCtx *, PatternMatcherQueue *, uint8_t *, uint16_t)
uint32_t B3gSearch12 (MpmCtx *, MpmThreadCtx *, PatternMatcherQueue *, uint8_t *, uint16_t)
uint32_t B3gSearch (MpmCtx *, MpmThreadCtx *, PatternMatcherQueue *, uint8_t *, uint16_t)
uint32_t B3gSearchBNDMq (MpmCtx *, MpmThreadCtx *, PatternMatcherQueue *, uint8_t *, uint16_t)
void B3gPrintInfo (MpmCtx *)
void B3gPrintSearchStats (MpmThreadCtx *)
void B3gRegisterTests (void)
void B3gFreePattern (MpmCtx *mpm_ctx, B3gPattern *p)
int B3gBuildMatchArray (MpmCtx *mpm_ctx)
void B3gGetConfig ()
Function to get the user defined values for b3g algorithm from the config file 'suricata.yaml'.
void MpmB3gRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
3 gram implementation of the (S)BNDMq pattern matching algorithm.
Ideas:
B3g does a full match in the search of up to 'm' characters, in case of a case insensitive search we could say it's match if the pattern is of len 'm' or just compare the rest of the chars.
Todo:
Try to get the S0 calculation right.
Definition in file util-mpm-b3g.c.
Macro Definition Documentation
#define B3G_HASH (a, b, c) (((a) << b3g_hash_shift) | (b) << (b3g_hash_shift2) |(c))
Definition at line 57 of file util-mpm-b3g.c.
Referenced by B3gBuildMatchArray(), B3gSearch(), and B3gSearchBNDMq().
#define COUNT (counter)
Definition at line 48 of file util-mpm-b3g.c.
Referenced by B3gSearch(), and B3gSearchBNDMq().
#define INIT_HASH_SIZE 65536
Definition at line 42 of file util-mpm-b3g.c.
Referenced by B3gDestroyCtx(), B3gInitCtx(), and B3gPreparePatterns().
Function Documentation
int B3gAddPatternCI (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 368 of file util-mpm-b3g.c.
References MPM_PATTERN_FLAG_NOCASE.
Referenced by MpmB3gRegister().
int B3gAddPatternCS (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 375 of file util-mpm-b3g.c.
Referenced by MpmB3gRegister().
int B3gBuildMatchArray (MpmCtx * mpm_ctx)
Definition at line 542 of file util-mpm-b3g.c.
References B3gCtx_::B3G, B3G_HASH, B3G_Q, B3G_TYPE, B3gPattern_::ci, MpmCtx_::ctx, B3gCtx_::hash_size, B3gPattern_::len, B3gCtx_::m, MpmCtx_::memory_cnt, MpmCtx_::memory_size, B3gCtx_::parray, MpmCtx_::pattern_cnt, B3gCtx_::s0, SCMalloc, and u8_tolower.
Referenced by B3gPreparePatterns().
void B3gDestroyCtx (MpmCtx * mpm_ctx)
Definition at line 782 of file util-mpm-b3g.c.
References B3gCtx_::B3G, B3G_TYPE, B3gFreePattern(), B3gCtx_::bloom, BloomFilterFree(), BloomFilterMemoryCnt(), BloomFilterMemorySize(), MpmCtx_::ctx, B3gCtx_::hash, B3gCtx_::hash2, B3gCtx_::hash_size, B3gCtx_::init_hash, INIT_HASH_SIZE, MpmCtx_::memory_cnt, MpmCtx_::memory_size, B3gCtx_::parray, MpmCtx_::pattern_cnt, B3gCtx_::pminlen, and SCFree.
Referenced by MpmB3gRegister().
void B3gFreePattern (MpmCtx * mpm_ctx, B3gPattern * p)
Definition at line 234 of file util-mpm-b3g.c.
References B3gPattern_::ci, B3gPattern_::cs, B3gPattern_::len, MpmCtx_::memory_cnt, MpmCtx_::memory_size, SCFree, B3gPattern_::sids, B3gPattern_::sids_size, and SigIntId.
Referenced by B3gDestroyCtx().
void B3gGetConfig ()
Function to get the user defined values for b3g algorithm from the config file 'suricata.yaml'.
Definition at line 679 of file util-mpm-b3g.c.
References B3G_HASHSHIFT_HIGH, B3G_HASHSHIFT_HIGH2, B3G_HASHSHIFT_HIGHER, B3G_HASHSHIFT_HIGHER2, B3G_HASHSHIFT_LOW, B3G_HASHSHIFT_LOW2, B3G_HASHSHIFT_LOWEST, B3G_HASHSHIFT_LOWEST2, B3G_HASHSHIFT_MAX, B3G_HASHSHIFT_MAX2, B3G_HASHSHIFT_MEDIUM, B3G_HASHSHIFT_MEDIUM2, B3G_SEARCHFUNC, B3gSearch(), B3gSearchBNDMq(), BLOOMSIZE_MEDIUM, ConfGetNode(), ConfNodeLookupChildValue(), HASHSIZE_HIGH, HASHSIZE_HIGHER, HASHSIZE_LOW, HASHSIZE_LOWEST, HASHSIZE_MAX, HASHSIZE_MEDIUM, MpmGetBloomSize(), MpmGetHashSize(), next, SCLogDebug, TAILQ_FOREACH, and ConfNode_::val.
Referenced by B3gInitCtx().
void B3gInitCtx (MpmCtx * mpm_ctx)
Definition at line 752 of file util-mpm-b3g.c.
References B3gGetConfig(), MpmCtx_::ctx, B3gCtx_::init_hash, INIT_HASH_SIZE, MpmCtx_::memory_cnt, MpmCtx_::memory_size, SCMalloc, and B3gCtx_::Search.
Referenced by MpmB3gRegister().
int B3gPreparePatterns (MpmCtx * mpm_ctx)
Definition at line 574 of file util-mpm-b3g.c.
References B3G_WORD_SIZE, B3gBuildMatchArray(), B3gSearch1(), B3gSearch12(), B3gSearch2(), MpmCtx_::ctx, B3gCtx_::hash_size, B3gCtx_::init_hash, INIT_HASH_SIZE, B3gCtx_::m, B3gCtx_::MBSearch, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmCtx_::minlen, B3gPattern_::next, B3gCtx_::parray, B3gCtx_::pat_1_cnt, B3gCtx_::pat_2_cnt, MpmCtx_::pattern_cnt, SCFree, SCMalloc, and B3gCtx_::Search.
Referenced by MpmB3gRegister().
void B3gPrintInfo (MpmCtx * mpm_ctx)
Todo:
XXX Unused???
Definition at line 90 of file util-mpm-b3g.c.
References MpmCtx_::ctx, B3gCtx_::hash_size, MpmCtx_::maxlen, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmCtx_::minlen, and MpmCtx_::pattern_cnt.
Referenced by MpmB3gRegister().
void B3gPrintSearchStats (MpmThreadCtx * mpm_thread_ctx)
Definition at line 638 of file util-mpm-b3g.c.
References MpmThreadCtx_::ctx.
Referenced by B3gThreadDestroyCtx(), and MpmB3gRegister().
void B3gRegisterTests (void)
Definition at line 1781 of file util-mpm-b3g.c.
Referenced by MpmB3gRegister().
uint32_t B3gSearch (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 1009 of file util-mpm-b3g.c.
References B3gCtx_::B3G, B3G_HASH, B3G_TYPE, B3gCtx_::bloom, B3gPattern_::ci, COUNT, B3gPattern_::cs, MpmThreadCtx_::ctx, MpmCtx_::ctx, B3gPattern_::flags, B3gCtx_::hash, B3gPattern_::id, len, B3gPattern_::len, B3gCtx_::m, m, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), B3gHashItem_::nxt, B3gCtx_::parray, PatternMatcherQueue_::pattern_id_bitarray_size, B3gCtx_::pminlen, B3gPattern_::sids, B3gPattern_::sids_size, and u8_tolower.
Referenced by B3gGetConfig().
uint32_t B3gSearch1 (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 1238 of file util-mpm-b3g.c.
References B3gPattern_::ci, B3gPattern_::cs, MpmCtx_::ctx, B3gPattern_::flags, B3gHashItem_::flags, B3gCtx_::hash1, B3gPattern_::id, B3gPattern_::len, B3gCtx_::MBSearch, B3gCtx_::MBSearch2, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), B3gHashItem_::nxt, B3gCtx_::parray, B3gCtx_::pat_2_cnt, B3gCtx_::pat_x_cnt, PatternMatcherQueue_::pattern_id_bitarray_size, B3gPattern_::sids, B3gPattern_::sids_size, and u8_tolower.
Referenced by B3gPreparePatterns().
uint32_t B3gSearch12 (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 1111 of file util-mpm-b3g.c.
References B3gPattern_::ci, B3gPattern_::cs, MpmCtx_::ctx, B3gPattern_::flags, B3gHashItem_::flags, B3gCtx_::hash1, B3gCtx_::hash2, B3gPattern_::id, B3gCtx_::MBSearch, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), B3gHashItem_::nxt, B3gCtx_::parray, B3gCtx_::pat_x_cnt, PatternMatcherQueue_::pattern_id_bitarray_size, B3gPattern_::sids, B3gPattern_::sids_size, and u8_tolower.
Referenced by B3gPreparePatterns().
uint32_t B3gSearch2 (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 1180 of file util-mpm-b3g.c.
References B3gPattern_::ci, B3gPattern_::cs, MpmCtx_::ctx, B3gPattern_::flags, B3gCtx_::hash2, B3gPattern_::id, B3gPattern_::len, B3gCtx_::MBSearch, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), B3gHashItem_::nxt, B3gCtx_::parray, B3gCtx_::pat_x_cnt, PatternMatcherQueue_::pattern_id_bitarray_size, B3gPattern_::sids, B3gPattern_::sids_size, and u8_tolower.
Referenced by B3gPreparePatterns().
uint32_t B3gSearchBNDMq (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 904 of file util-mpm-b3g.c.
References B3gCtx_::B3G, B3G_HASH, B3G_Q, B3G_TYPE, B3gCtx_::bloom, B3gPattern_::ci, COUNT, B3gPattern_::cs, MpmThreadCtx_::ctx, MpmCtx_::ctx, B3gPattern_::flags, B3gCtx_::hash, B3gPattern_::id, len, B3gPattern_::len, B3gCtx_::m, m, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), B3gHashItem_::nxt, B3gCtx_::parray, PatternMatcherQueue_::pattern_id_bitarray_size, B3gCtx_::pminlen, B3gPattern_::sids, B3gPattern_::sids_size, and u8_tolower.
Referenced by B3gGetConfig().
uint32_t B3gSearchWrap (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen) inline
Definition at line 898 of file util-mpm-b3g.c.
References MpmCtx_::ctx, and B3gCtx_::Search.
Referenced by MpmB3gRegister().
void B3gThreadDestroyCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx)
Definition at line 885 of file util-mpm-b3g.c.
References B3gPrintSearchStats(), MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, and SCFree.
Referenced by MpmB3gRegister().
void B3gThreadInitCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, uint32_t matchsize)
Definition at line 869 of file util-mpm-b3g.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, and SCMalloc.
Referenced by MpmB3gRegister().
void MpmB3gRegister (void)
Definition at line 1293 of file util-mpm-b3g.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, B3G_WORD_SIZE, B3gAddPatternCI(), B3gAddPatternCS(), B3gDestroyCtx(), B3gInitCtx(), B3gPreparePatterns(), B3gPrintInfo(), B3gPrintSearchStats(), B3gRegisterTests(), B3gSearchWrap(), B3gThreadDestroyCtx(), B3gThreadInitCtx(), MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, MPM_B3G, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, and MpmTableElmt_::Search.
Referenced by MpmTableSetup().