suricata: src/util-reference-config.h File Reference
util-reference-config.h File Reference
Data Structures
struct SCRConfReference_
Holds a reference from the file - reference.config.
Typedefs
typedef struct SCRConfReference_ SCRConfReference
Holds a reference from the file - reference.config.
Functions
SCRConfReference * SCRConfAllocSCRConfReference (const char *, const char *)
Returns a new SCRConfReference instance. The reference string is converted into lowercase, before being assigned to the instance.
void SCRConfDeAllocSCRConfReference (SCRConfReference *)
Frees a SCRConfReference instance.
int SCRConfLoadReferenceConfigFile (DetectEngineCtx *, FILE *)
Loads the Reference info from the reference.config file.
void SCRConfDeInitContext (DetectEngineCtx *)
Releases de_ctx resources related to Reference Config API.
SCRConfReference * SCRConfGetReference (const char *, DetectEngineCtx *)
Gets the refernce config from the corresponding hash table stored in the Detection Engine Context's reference conf ht, given the reference name.
void SCRConfRegisterTests (void)
This function registers unit tests for Reference Config API.
FILE * SCRConfGenerateValidDummyReferenceConfigFD01 (void)
FILE * SCRConfGenerateInValidDummyReferenceConfigFD02 (void)
FILE * SCRConfGenerateInValidDummyReferenceConfigFD03 (void)
void SCReferenceConfInit (void)
void SCReferenceConfDeinit (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-reference-config.h.
Typedef Documentation
typedef struct SCRConfReference_ SCRConfReference
Holds a reference from the file - reference.config.
Function Documentation
SCRConfReference* SCRConfAllocSCRConfReference (const char * system, const char * url)
Returns a new SCRConfReference instance. The reference string is converted into lowercase, before being assigned to the instance.
Parameters
system Pointer to the system.
url Pointer to the reference url.
Return values
ref Pointer to the new instance of SCRConfReference.
Definition at line 366 of file util-reference-config.c.
References SC_ERR_INVALID_SIGNATURE, SCFree, SCLogError, SCMalloc, SCStrdup, SCRConfReference_::system, and SCRConfReference_::url.
Referenced by SCRConfGetReference().
void SCRConfDeAllocSCRConfReference (SCRConfReference * ref)
Frees a SCRConfReference instance.
Parameters
Pointer to the SCRConfReference instance that has to be freed.
Definition at line 400 of file util-reference-config.c.
References SCFree, SCRConfReference_::system, and SCRConfReference_::url.
Referenced by SCRConfGetReference(), and SCRConfReferenceHashFree().
void SCRConfDeInitContext (DetectEngineCtx *)
Releases de_ctx resources related to Reference Config API.
Definition at line 202 of file util-reference-config.c.
References HashTableFree(), and DetectEngineCtx_::reference_conf_ht.
Referenced by DetectEngineCtxFree().
FILE* SCRConfGenerateInValidDummyReferenceConfigFD02 (void)
FILE* SCRConfGenerateInValidDummyReferenceConfigFD03 (void)
FILE* SCRConfGenerateValidDummyReferenceConfigFD01 (void)
SCRConfReference* SCRConfGetReference (const char * rconf_name, DetectEngineCtx * de_ctx)
Gets the refernce config from the corresponding hash table stored in the Detection Engine Context's reference conf ht, given the reference name.
Parameters
ct_name Pointer to the reference name that has to be looked up.
de_ctx Pointer to the Detection Engine Context.
Return values
lookup_rconf_info Pointer to the SCRConfReference instance from the hash table on success; NULL on failure.
Definition at line 536 of file util-reference-config.c.
References HashTableLookup(), DetectEngineCtx_::reference_conf_ht, SCRConfAllocSCRConfReference(), and SCRConfDeAllocSCRConfReference().
int SCRConfLoadReferenceConfigFile (DetectEngineCtx * de_ctx, FILE * fd)
Loads the Reference info from the reference.config file.
   The reference.config file contains references that can be used in
   Signatures.  Each line of the file should  have the following format -
   config reference: system_name, reference_url.
Parameters
de_ctx Pointer to the Detection Engine Context that should be updated with reference information.
Return values
0 On success.
-1 On failure.
Definition at line 505 of file util-reference-config.c.
References RunmodeIsUnittests(), SC_ERR_OPENING_FILE, and SCLogError.
void SCRConfRegisterTests (void)
This function registers unit tests for Reference Config API.
Definition at line 795 of file util-reference-config.c.
Referenced by RunUnittests().
void SCReferenceConfDeinit (void)
Definition at line 80 of file util-reference-config.c.
Referenced by main().
void SCReferenceConfInit (void)
Definition at line 56 of file util-reference-config.c.
References SC_RCONF_REGEX, and SCLogDebug.
Referenced by main(), and RunUnittests().