suricata: src/util-debug.c File Reference
util-debug.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "util-debug.h"
#include "util-error.h"
#include "util-enum.h"
#include "util-debug-filters.h"
#include "decode.h"
#include "detect.h"
#include "packet-queue.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
#include "tm-queues.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-syslog.h"
#include "conf.h"
Macros
#define MAX_SUBSTRINGS 30
Functions
SCError SCLogMessage (const SCLogLevel log_level, const char *file, const unsigned int line, const char *function, const SCError error_code, const char *message)
Adds the global log_format to the outgoing buffer.
int SCLogDebugEnabled (void)
Returns whether debug messages are enabled to be logged or not.
SCLogOPBuffer * SCLogAllocLogOPBuffer (void)
Allocates an output buffer for an output interface. Used when we want the op_interface log_format to override the global_log_format. Currently not used.
SCLogInitData * SCLogAllocLogInitData (void)
Returns a pointer to a new SCLogInitData. This is a public interface intended to be used after the logging paramters are read from the conf file.
void SCLogFreeLogInitData (SCLogInitData *sc_lid)
Frees a SCLogInitData.
void SCLogAppendOPIfaceCtx (SCLogOPIfaceCtx *iface_ctx, SCLogInitData *sc_lid)
Appends an output_interface to the output_interface list sent in head.
SCLogOPIfaceCtx * SCLogInitOPIfaceCtx (const char *iface_name, const char *log_format, int log_level, const char *arg)
Creates a new output interface based on the arguments sent. The kind of output interface to be created is decided by the iface_name arg. If iface_name is "file", the arg argument will hold the filename to be used for logging purposes. If iface_name is "syslog", the arg argument holds the facility code. If iface_name is "console", arg is NULL.
void SCLogInitLogModule (SCLogInitData *sc_lid)
Initializes the logging module.
void SCLogLoadConfig (int daemon, int verbose)
void SCLogDeInitLogModule (void)
De-Initializes the logging module.
void SCLogRegisterTests ()
Variables
SCEnumCharMap sc_log_level_map []
SCEnumCharMap sc_log_op_iface_map []
SCLogLevel sc_log_global_log_level
Holds the global log level. Is the same as sc_log_config->log_level.
int sc_log_module_initialized = 0
Used to indicate whether the logging module has been init or not.
int sc_log_module_cleaned = 0
Used to indicate whether the logging module has been cleaned or not.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Debug utility functions
Definition in file util-debug.c.
Macro Definition Documentation
#define MAX_SUBSTRINGS 30
Function Documentation
SCLogInitData* SCLogAllocLogInitData (void)
Returns a pointer to a new SCLogInitData. This is a public interface intended to be used after the logging paramters are read from the conf file.
Return values
sc_lid Pointer to the newly created SCLogInitData
Definition at line 1069 of file util-debug.c.
References SCMalloc.
Referenced by SCLogLoadConfig().
SCLogOPBuffer* SCLogAllocLogOPBuffer (void)
Allocates an output buffer for an output interface. Used when we want the op_interface log_format to override the global_log_format. Currently not used.
Return values
buffer Pointer to the newly created output_buffer
Definition at line 616 of file util-debug.c.
References SCLogOPBuffer_::log_format, SCLogOPBuffer_::msg, SCLogOPIfaceCtx_::next, SCLogConfig_::op_ifaces, SCLogConfig_::op_ifaces_cnt, SC_ERR_FATAL, SCLogError, SCMalloc, and SCLogOPBuffer_::temp.
void SCLogAppendOPIfaceCtx (SCLogOPIfaceCtx * iface_ctx, SCLogInitData * sc_lid)
Appends an output_interface to the output_interface list sent in head.
Parameters
iface_ctx Pointer to the output_interface that has to be added to head
head Pointer to the output_interface list
Definition at line 1129 of file util-debug.c.
References head, SCLogOPIfaceCtx_::next, SCLogInitData_::op_ifaces, and SCLogInitData_::op_ifaces_cnt.
Referenced by SCLogLoadConfig().
int SCLogDebugEnabled (void)
Returns whether debug messages are enabled to be logged or not.
Return values
1 if debug messages are enabled to be logged
0 if debug messages are not enabled to be logged
Definition at line 597 of file util-debug.c.
References SC_LOG_DEBUG, and sc_log_global_log_level.
Referenced by AppLayerProtoDetectPrepareState(), DecodeIPV4(), DecodeIPV6(), DetectBytejumpDoMatch(), DetectBytejumpMatch(), DetectContentPrintAll(), DetectPortInsert(), FlowVarPrint(), HtpBodyPrint(), SigAddressPrepareStage1(), SMTPProcessDataChunk(), SRepLoadFileFromFD(), and StreamTcpSegmentDataReplace().
void SCLogDeInitLogModule (void)
De-Initializes the logging module.
Definition at line 1425 of file util-debug.c.
References sc_log_global_log_level, sc_log_module_cleaned, sc_log_module_initialized, SCLogReleaseFDFilters(), SCLogReleaseFGFilters(), and SCMutexDestroy.
Referenced by SCLogInitLogModule().
void SCLogFreeLogInitData (SCLogInitData * sc_lid)
Frees a SCLogInitData.
Parameters
sc_lid Pointer to the SCLogInitData to be freed
Definition at line 1087 of file util-debug.c.
References SCLogInitData_::global_log_format, SCLogInitData_::op_filter, SCLogInitData_::op_ifaces, SCFree, and SCLogInitData_::startup_message.
void SCLogInitLogModule (SCLogInitData * sc_lid)
Initializes the logging module.
Parameters
sc_lid The initialization data for the logging module. If sc_lid is NULL, we would stick to the default configuration for the logging subsystem.
Definition at line 1214 of file util-debug.c.
References SC_ERR_FATAL, SC_ERR_MUTEX, sc_log_module_cleaned, sc_log_module_initialized, SCLogDeInitLogModule(), SCLogError, SCMalloc, and SCMutexInit.
Referenced by main(), and SCLogLoadConfig().
SCLogOPIfaceCtx* SCLogInitOPIfaceCtx (const char * iface_name, const char * log_format, int log_level, const char * arg)
Creates a new output interface based on the arguments sent. The kind of output interface to be created is decided by the iface_name arg. If iface_name is "file", the arg argument will hold the filename to be used for logging purposes. If iface_name is "syslog", the arg argument holds the facility code. If iface_name is "console", arg is NULL.
Parameters
iface_name Interface name. Can be "console", "file" or "syslog"
log_format Override for the global_log_format
log_level Override for the global_log_level
log_level Parameter required by a particular interface. Explained in the function description
Return values
iface_ctx Pointer to the newly created output interface
Definition at line 1174 of file util-debug.c.
References SC_LOG_DEBUG, SC_LOG_NOTSET, SC_LOG_OP_IFACE_CONSOLE, SC_LOG_OP_IFACE_FILE, SC_LOG_OP_IFACE_SYSLOG, SC_LOG_OP_TYPE_REGULAR, SCMapEnumNameToValue(), and SCSyslogGetFacilityMap().
void SCLogLoadConfig (int daemon, int verbose)
Definition at line 1247 of file util-debug.c.
References ConfGet(), ConfGetNode(), ConfNodeLookupChild(), ConfNodeLookupChildValue(), ConfValIsFalse(), SCLogInitData_::global_log_format, SCLogInitData_::global_log_level, SCLogConfig_::log_format, ConfNode_::name, next, SCLogInitData_::op_filter, SCLogConfig_::op_filter, SC_ERR_INVALID_ARGUMENT, SC_ERR_MISSING_CONFIG_PARAM, SC_LOG_DEF_LOG_FORMAT, SC_LOG_DEF_SYSLOG_FACILITY, SC_LOG_DEF_SYSLOG_FACILITY_STR, sc_log_global_log_level, SC_LOG_LEVEL_MAX, SC_LOG_NOTICE, SC_LOG_OP_TYPE_JSON, SC_LOG_OP_TYPE_REGULAR, SCFree, SCLogAllocLogInitData(), SCLogAppendOPIfaceCtx(), SCLogDebug, SCLogError, SCLogInitLogModule(), SCLogWarning, SCMapEnumNameToValue(), SCSyslogGetFacilityMap(), TAILQ_FOREACH, and ConfNode_::val.
Referenced by ListAppLayerProtocols(), ListKeywords(), and main().
SCError SCLogMessage (const SCLogLevel log_level, const char * file, const unsigned int line, const char * function, const SCError error_code, const char * message)
Adds the global log_format to the outgoing buffer.
Parameters
log_level log_level of the message that has to be logged
msg Buffer containing the outgoing message
file File_name from where the message originated
function Function_name from where the message originated
line Line_no from where the messaged originated
Return values
SC_OK on success; else an error code
Definition at line 527 of file util-debug.c.
References SCLogOPIfaceCtx_::file_d, SCLogOPIfaceCtx_::iface, SCLogOPIfaceCtx_::log_format, SCLogConfig_::log_format, SCLogOPIfaceCtx_::log_level, SCLogOPIfaceCtx_::next, SCLogConfig_::op_ifaces, SC_LOG_ERROR, SC_LOG_MAX_LOG_MSG_LEN, sc_log_module_initialized, SC_LOG_NOTSET, SC_LOG_OP_IFACE_CONSOLE, SC_LOG_OP_IFACE_FILE, SC_LOG_OP_IFACE_SYSLOG, SC_OK, SCLogOPIfaceCtx_::type, and SCLogOPIfaceCtx_::use_color.
void SCLogRegisterTests (void)
Definition at line 1639 of file util-debug.c.
Referenced by RunUnittests().
Variable Documentation
SCLogLevel sc_log_global_log_level
Holds the global log level. Is the same as sc_log_config->log_level.
Definition at line 90 of file util-debug.c.
Referenced by SCLogDebugEnabled(), SCLogDeInitLogModule(), and SCLogLoadConfig().
SCEnumCharMap sc_log_level_map[]
Initial value:
= {
    { "Not set",        SC_LOG_NOTSET},
    { "None",           SC_LOG_NONE },
    { "Emergency",      SC_LOG_EMERGENCY },
    { "Alert",          SC_LOG_ALERT },
    { "Critical",       SC_LOG_CRITICAL },
    { "Error",          SC_LOG_ERROR },
    { "Warning",        SC_LOG_WARNING },
    { "Notice",         SC_LOG_NOTICE },
    { "Info",           SC_LOG_INFO },
    { "Debug",          SC_LOG_DEBUG },
    { NULL,             -1 }
}
Definition at line 48 of file util-debug.c.
int sc_log_module_cleaned = 0
Used to indicate whether the logging module has been cleaned or not.
Definition at line 100 of file util-debug.c.
Referenced by SCLogDeInitLogModule(), and SCLogInitLogModule().
int sc_log_module_initialized = 0
Used to indicate whether the logging module has been init or not.
Definition at line 95 of file util-debug.c.
Referenced by SCLogAddFDFilter(), SCLogAddFGFilter(), SCLogCheckFDFilterEntry(), SCLogCheckFDFilterExit(), SCLogDeInitLogModule(), SCLogInitLogModule(), SCLogMatchFDFilter(), SCLogMessage(), SCLogPrintFDFilters(), SCLogPrintFGFilters(), and SCLogRemoveFDFilter().
SCEnumCharMap sc_log_op_iface_map[]
Initial value:
= {
    { "Console",        SC_LOG_OP_IFACE_CONSOLE },
    { "File",           SC_LOG_OP_IFACE_FILE },
    { "Syslog",         SC_LOG_OP_IFACE_SYSLOG },
    { NULL,             -1 }
}
Definition at line 63 of file util-debug.c.