suricata: src/util-mpm-ac-gfbs.c File Reference
util-mpm-ac-gfbs.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "util-mpm-ac-gfbs.h"
#include "conf.h"
#include "util-memcmp.h"
#include "util-memcpy.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
Data Structures
struct StateQueue_
Helper structure used by AC during state table creation.
Macros
#define SC_AC_GFBS_FAIL (-1)
#define INIT_HASH_SIZE 65536
#define STATE_QUEUE_CONTAINER_SIZE 65536
Typedefs
typedef struct StateQueue_ StateQueue
Helper structure used by AC during state table creation.
Functions
void SCACGfbsInitCtx (MpmCtx *mpm_ctx)
Initialize the AC context.
void SCACGfbsInitThreadCtx (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, uint32_t matchsize)
Init the mpm thread context.
void SCACGfbsDestroyCtx (MpmCtx *mpm_ctx)
Destroy the mpm context.
void SCACGfbsDestroyThreadCtx (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx)
Destroy the mpm thread context.
int SCACGfbsAddPatternCI (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case insensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
int SCACGfbsAddPatternCS (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case sensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
int SCACGfbsPreparePatterns (MpmCtx *mpm_ctx)
Process the patterns added to the mpm, and create the internal tables.
uint32_t SCACGfbsSearch (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *pmq, uint8_t *buf, uint16_t buflen)
The aho corasick search function.
void SCACGfbsPrintInfo (MpmCtx *mpm_ctx)
void SCACGfbsPrintSearchStats (MpmThreadCtx *mpm_thread_ctx)
void SCACGfbsRegisterTests (void)
void MpmACGfbsRegister (void)
Register the goto failure table based aho-corasick mpm.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
    Implementation of aho-corasick MPM from -
    Efficient String Matching: An Aid to Bibliographic Search
    Alfred V. Aho and Margaret J. Corasick
    - We use the goto-failure table to calculate transitions.
    - If we cross 2 ** 16 states, we use 4 bytes in the transition table
      to hold each state, otherwise we use 2 bytes.
    - To reduce memory consumption, we throw all the failure transitions
      out and use binary search to pick out the right transition in
      the modified goto table.
Todo:
Do a proper analyis of our existing MPMs and suggest a good one based on the pattern distribution and the expected traffic(say http).
Tried out loop unrolling without any perf increase. Need to dig deeper.
Try out holding whether they are any output strings from a particular state in one of the bytes of a state var. Will be useful in cuda esp.
Definition in file util-mpm-ac-gfbs.c.
Macro Definition Documentation
#define INIT_HASH_SIZE 65536
Definition at line 75 of file util-mpm-ac-gfbs.c.
Referenced by SCACGfbsDestroyCtx(), SCACGfbsInitCtx(), and SCACGfbsPreparePatterns().
#define SC_AC_GFBS_FAIL (-1)
Definition at line 73 of file util-mpm-ac-gfbs.c.
Referenced by SCACGfbsSearch().
#define STATE_QUEUE_CONTAINER_SIZE 65536
Definition at line 77 of file util-mpm-ac-gfbs.c.
Typedef Documentation
typedef struct StateQueue_ StateQueue
Helper structure used by AC during state table creation.
Function Documentation
void MpmACGfbsRegister (void)
Register the goto failure table based aho-corasick mpm.
Definition at line 91 of file util-mpm-ac-gfbs.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, MPM_AC_GFBS, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, SCACGfbsAddPatternCI(), SCACGfbsAddPatternCS(), SCACGfbsDestroyCtx(), SCACGfbsDestroyThreadCtx(), SCACGfbsInitCtx(), SCACGfbsInitThreadCtx(), SCACGfbsPreparePatterns(), SCACGfbsPrintInfo(), SCACGfbsPrintSearchStats(), SCACGfbsRegisterTests(), SCACGfbsSearch(), and MpmTableElmt_::Search.
Referenced by MpmTableSetup().
int SCACGfbsAddPatternCI (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case insensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
Parameters
mpm_ctx Pointer to the mpm context.
pat The pattern to add.
patnen The pattern length.
offset Ignored.
depth Ignored.
pid The pattern id.
sid Ignored.
flags Flags associated with this pattern.
Return values
0 On success.
-1 On failure.
Definition at line 1594 of file util-mpm-ac-gfbs.c.
References MPM_PATTERN_FLAG_NOCASE.
Referenced by MpmACGfbsRegister().
int SCACGfbsAddPatternCS (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case sensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
Parameters
mpm_ctx Pointer to the mpm context.
pat The pattern to add.
patnen The pattern length.
offset Ignored.
depth Ignored.
pid The pattern id.
sid Ignored.
flags Flags associated with this pattern.
Return values
0 On success.
-1 On failure.
Definition at line 1619 of file util-mpm-ac-gfbs.c.
Referenced by MpmACGfbsRegister().
void SCACGfbsDestroyCtx (MpmCtx * mpm_ctx)
Destroy the mpm context.
Parameters
mpm_ctx Pointer to the mpm context.
Definition at line 1203 of file util-mpm-ac-gfbs.c.
References SCACGfbsPatternList_::cs, MpmCtx_::ctx, SCACGfbsCtx_::goto_table_mod, SCACGfbsCtx_::goto_table_mod_pointers, SCACGfbsCtx_::init_hash, INIT_HASH_SIZE, SCACGfbsCtx_::max_pat_id, MpmCtx_::memory_cnt, MpmCtx_::memory_size, SCACGfbsCtx_::output_table, SCACGfbsCtx_::parray, MpmCtx_::pattern_cnt, SCACGfbsCtx_::pid_pat_list, SCACGfbsOutputTable_::pids, SC_AC_GFBS_STATE_TYPE_U16, SC_AC_GFBS_STATE_TYPE_U32, SCFree, SCACGfbsPatternList_::sids, and SCACGfbsCtx_::state_count.
Referenced by MpmACGfbsRegister().
void SCACGfbsDestroyThreadCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx)
Destroy the mpm thread context.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
Definition at line 1184 of file util-mpm-ac-gfbs.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, SCACGfbsPrintSearchStats(), and SCFree.
Referenced by MpmACGfbsRegister().
void SCACGfbsInitCtx (MpmCtx * mpm_ctx)
Initialize the AC context.
Parameters
mpm_ctx Mpm context.
module_handle Cuda module handle from the cuda handler API. We don't have to worry about this here.
Definition at line 1149 of file util-mpm-ac-gfbs.c.
References MpmCtx_::ctx, SCACGfbsCtx_::init_hash, INIT_HASH_SIZE, MpmCtx_::memory_cnt, MpmCtx_::memory_size, SCMalloc, and SCReturn.
Referenced by MpmACGfbsRegister().
void SCACGfbsInitThreadCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, uint32_t matchsize)
Init the mpm thread context.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
matchsize We don't need this.
Definition at line 1126 of file util-mpm-ac-gfbs.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, and SCMalloc.
Referenced by MpmACGfbsRegister().
int SCACGfbsPreparePatterns (MpmCtx * mpm_ctx)
Process the patterns added to the mpm, and create the internal tables.
Parameters
mpm_ctx Pointer to the mpm context.
Definition at line 1037 of file util-mpm-ac-gfbs.c.
References SCACGfbsPatternList_::cs, MpmCtx_::ctx, SCACGfbsPattern_::flags, SCACGfbsPattern_::id, SCACGfbsCtx_::init_hash, INIT_HASH_SIZE, SCACGfbsPattern_::len, SCACGfbsCtx_::max_pat_id, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MPM_PATTERN_FLAG_NOCASE, SCACGfbsPattern_::next, SCACGfbsPattern_::original_pat, SCACGfbsCtx_::parray, SCACGfbsPatternList_::patlen, MpmCtx_::pattern_cnt, SCACGfbsCtx_::pid_pat_list, SC_ERR_MEM_ALLOC, SCFree, SCLogDebug, SCLogError, SCMalloc, SCACGfbsPattern_::sids, SCACGfbsPatternList_::sids, SCACGfbsPattern_::sids_size, and SCACGfbsPatternList_::sids_size.
Referenced by MpmACGfbsRegister().
void SCACGfbsPrintInfo (MpmCtx * mpm_ctx)
Definition at line 1639 of file util-mpm-ac-gfbs.c.
References MpmCtx_::ctx, MpmCtx_::maxlen, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmCtx_::minlen, MpmCtx_::pattern_cnt, and SCACGfbsCtx_::state_count.
Referenced by MpmACGfbsRegister().
void SCACGfbsPrintSearchStats (MpmThreadCtx * mpm_thread_ctx)
Definition at line 1626 of file util-mpm-ac-gfbs.c.
References MpmThreadCtx_::ctx, SCACGfbsThreadCtx_::total_calls, and SCACGfbsThreadCtx_::total_matches.
Referenced by MpmACGfbsRegister(), and SCACGfbsDestroyThreadCtx().
void SCACGfbsRegisterTests (void)
Definition at line 2686 of file util-mpm-ac-gfbs.c.
Referenced by MpmACGfbsRegister().
uint32_t SCACGfbsSearch (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
The aho corasick search function.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
pmq Pointer to the Pattern Matcher Queue to hold search matches.
buf Buffer to be searched.
buflen Buffer length.
Return values
matches Match count.
Definition at line 1291 of file util-mpm-ac-gfbs.c.
References MpmCtx_::ctx, SCACGfbsCtx_::goto_table_mod_pointers, SCACGfbsOutputTable_::no_of_entries, SCACGfbsCtx_::output_table, PatternMatcherQueue_::pattern_id_bitarray, PatternMatcherQueue_::pattern_id_bitarray_size, SCACGfbsCtx_::pid_pat_list, SCACGfbsOutputTable_::pids, SC_AC_GFBS_FAIL, SCMemcmp, SCACGfbsCtx_::state_count, and u8_tolower.
Referenced by MpmACGfbsRegister().