suricata: src/util-cpu.c File Reference
util-cpu.c File Reference
#include "util-error.h"
#include "util-debug.h"
#include "suricata-common.h"
Functions
uint16_t UtilCpuGetNumProcessorsConfigured ()
Get the number of cpus configured in the system.
uint16_t UtilCpuGetNumProcessorsOnline ()
Get the number of cpus online in the system.
uint16_t UtilCpuGetNumProcessorsMax ()
Get the maximum number of cpus allowed in the system This syscall is present on Solaris, but it's not on linux or macosx. Maybe you should look at UtilCpuGetNumProcessorsConfigured()
void UtilCpuPrintSummary ()
Print a summary of CPUs detected (configured and online)
uint64_t UtilCpuGetTicks (void)
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Retrieve CPU information (configured CPUs, online CPUs)
Definition in file util-cpu.c.
Function Documentation
uint16_t UtilCpuGetNumProcessorsConfigured ()
Get the number of cpus configured in the system.
Ok, if they should use sysconf, check that they have the macro's (syscalls) defined;
Note: For windows it's different; Check the following: SYSTEM_INFO info; GetSystemInfo(&info); -> info.dwNumberOfProcessors;
Return values
0 if the syscall is not available or we have an error; otherwise it will return the number of cpus configured
Definition at line 57 of file util-cpu.c.
References SC_ERR_SYSCALL, SC_ERR_SYSCONF, SCLogDebug, and SCLogError.
Referenced by UtilCpuGetNumProcessorsOnline(), and UtilCpuPrintSummary().
uint16_t UtilCpuGetNumProcessorsMax ()
Get the maximum number of cpus allowed in the system This syscall is present on Solaris, but it's not on linux or macosx. Maybe you should look at UtilCpuGetNumProcessorsConfigured()
Return values
0 if the syscall is not available or we have an error; otherwise it will return the number of cpus allowed
Definition at line 133 of file util-cpu.c.
References SC_ERR_SYSCALL, SC_ERR_SYSCONF, SCLogDebug, and SCLogError.
uint16_t UtilCpuGetNumProcessorsOnline ()
Get the number of cpus online in the system.
Return values
0 if the syscall is not available or we have an error; otherwise it will return the number of cpus online
Definition at line 98 of file util-cpu.c.
References SC_ERR_SYSCALL, SC_ERR_SYSCONF, SCLogDebug, SCLogError, and UtilCpuGetNumProcessorsConfigured().
Referenced by AffinityGetNextCPU(), ParseAFPConfig(), RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeSetIPSAutoFp(), RunModeSetLiveCaptureAutoFp(), and UtilCpuPrintSummary().
uint64_t UtilCpuGetTicks (void)
Get the current number of ticks from the CPU.
Todo:
We'll have to deal with removig ticks from the extra cpuids inbetween 2 calls.
Definition at line 189 of file util-cpu.c.
void UtilCpuPrintSummary ()
Print a summary of CPUs detected (configured and online)
Definition at line 161 of file util-cpu.c.
References SCLogDebug, SCLogInfo, UtilCpuGetNumProcessorsConfigured(), and UtilCpuGetNumProcessorsOnline().
Referenced by main().