suricata: src/util-ip.h File Reference
util-ip.h File Reference
Functions
struct in_addr * ValidateIPV4Address (const char *)
Validates an IPV4 address and returns the network endian arranged version of the IPV4 address.
struct in6_addr * ValidateIPV6Address (const char *)
Validates an IPV6 address and returns the network endian arranged version of the IPV6 addresss.
void MaskIPNetblock (uint8_t *, int, int)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Duarte Silva duart.nosp@m.e.si.nosp@m.lva@s.nosp@m.eria.nosp@m.lizin.nosp@m.g.me
Definition in file util-ip.h.
Function Documentation
void MaskIPNetblock (uint8_t * , int , int)
struct in_addr* ValidateIPV4Address (const char * addr_str)
Validates an IPV4 address and returns the network endian arranged version of the IPV4 address.
Parameters
addr Pointer to a character string containing an IPV4 address. A valid IPV4 address is a character string containing a dotted format of "ddd.ddd.ddd.ddd"
Return values
Pointer to an in_addr instance containing the network endian format of the IPV4 address
NULL if the IPV4 address is invalid
Definition at line 41 of file util-ip.c.
References inet_pton(), SC_ERR_FATAL, SCFree, SCLogError, and SCMalloc.
Referenced by SCHInfoAddHostOSInfo(), and SCHInfoGetHostOSFlavour().
struct in6_addr* ValidateIPV6Address (const char * addr_str)
Validates an IPV6 address and returns the network endian arranged version of the IPV6 addresss.
Parameters
addr Pointer to a character string containing an IPV6 address
Return values
Pointer to a in6_addr instance containing the network endian format of the IPV6 address
NULL if the IPV6 address is invalid
Definition at line 68 of file util-ip.c.
References inet_pton(), SC_ERR_FATAL, SCFree, SCLogError, and SCMalloc.
Referenced by SCHInfoAddHostOSInfo(), and SCHInfoGetHostOSFlavour().