suricata: src/util-mpm-ac-bs.h File Reference
util-mpm-ac-bs.h File Reference
Data Structures
struct SCACBSPattern_
struct SCACBSPatternList_
struct SCACBSOutputTable_
struct SCACBSCtx_
struct SCACBSThreadCtx_
Macros
#define SC_AC_BS_STATE_TYPE_U16 uint16_t
#define SC_AC_BS_STATE_TYPE_U32 uint32_t
Typedefs
typedef struct SCACBSPattern_ SCACBSPattern
typedef struct SCACBSPatternList_ SCACBSPatternList
typedef struct SCACBSOutputTable_ SCACBSOutputTable
typedef struct SCACBSCtx_ SCACBSCtx
typedef struct SCACBSThreadCtx_ SCACBSThreadCtx
Functions
void MpmACBSRegister (void)
Register the aho-corasick mpm.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-mpm-ac-bs.h.
Macro Definition Documentation
#define SC_AC_BS_STATE_TYPE_U16 uint16_t
Definition at line 25 of file util-mpm-ac-bs.h.
Referenced by SCACBSDestroyCtx(), and SCACBSSearch().
#define SC_AC_BS_STATE_TYPE_U32 uint32_t
Definition at line 26 of file util-mpm-ac-bs.h.
Referenced by SCACBSDestroyCtx(), and SCACBSSearch().
Typedef Documentation
typedef struct SCACBSCtx_ SCACBSCtx
typedef struct SCACBSOutputTable_ SCACBSOutputTable
typedef struct SCACBSPattern_ SCACBSPattern
typedef struct SCACBSPatternList_ SCACBSPatternList
typedef struct SCACBSThreadCtx_ SCACBSThreadCtx
Function Documentation
void MpmACBSRegister (void)
Register the aho-corasick mpm.
Definition at line 97 of file util-mpm-ac-bs.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, MPM_AC_BS, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, SCACBSAddPatternCI(), SCACBSAddPatternCS(), SCACBSDestroyCtx(), SCACBSDestroyThreadCtx(), SCACBSInitCtx(), SCACBSInitThreadCtx(), SCACBSPreparePatterns(), SCACBSPrintInfo(), SCACBSPrintSearchStats(), SCACBSRegisterTests(), SCACBSSearch(), and MpmTableElmt_::Search.
Referenced by MpmTableSetup().