suricata: src/util-hashlist.h File Reference
util-hashlist.h File Reference
Data Structures
struct HashListTableBucket_
struct HashListTable_
Macros
#define HASHLIST_NO_SIZE 0
#define HashListTableGetListNext(hb) (hb)->listnext
#define HashListTableGetListData(hb) (hb)->data
Typedefs
typedef struct HashListTableBucket_ HashListTableBucket
typedef struct HashListTable_ HashListTable
Functions
HashListTable * HashListTableInit (uint32_t, uint32_t(*Hash)(struct HashListTable_ *, void *, uint16_t), char(*Compare)(void *, uint16_t, void *, uint16_t), void(*Free)(void *))
void HashListTableFree (HashListTable *)
void HashListTablePrint (HashListTable *)
int HashListTableAdd (HashListTable *, void *, uint16_t)
int HashListTableRemove (HashListTable *, void *, uint16_t)
void * HashListTableLookup (HashListTable *, void *, uint16_t)
uint32_t HashListTableGenericHash (HashListTable *, void *, uint16_t)
HashListTableBucket * HashListTableGetListHead (HashListTable *)
char HashListTableDefaultCompare (void *, uint16_t, void *, uint16_t)
void HashListTableRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-hashlist.h.
Macro Definition Documentation
#define HASHLIST_NO_SIZE 0
Definition at line 47 of file util-hashlist.h.
#define HashListTableGetListData (hb) (hb)->data
Definition at line 59 of file util-hashlist.h.
Referenced by CreateGroupedPortList(), and SigGroupHeadFreeMpmArrays().
#define HashListTableGetListNext (hb) (hb)->listnext
Definition at line 58 of file util-hashlist.h.
Referenced by CreateGroupedPortList(), and SigGroupHeadFreeMpmArrays().
Typedef Documentation
typedef struct HashListTable_ HashListTable
typedef struct HashListTableBucket_ HashListTableBucket
Function Documentation
int HashListTableAdd (HashListTable * , void * , uint16_t)
Definition at line 116 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTableBucket_::data, data, HashListTable_::Hash, HashListTable_::listhead, HashListTableBucket_::listnext, HashListTableBucket_::listprev, HashListTable_::listtail, SCLogDebug, SCMalloc, HashListTableBucket_::size, and unlikely.
Referenced by DetectPortDpHashAdd(), DetectPortSpHashAdd(), SigGroupHeadDPortHashAdd(), SigGroupHeadHashAdd(), SigGroupHeadMpmHashAdd(), SigGroupHeadMpmStreamHashAdd(), SigGroupHeadMpmUriHashAdd(), SigGroupHeadSPortHashAdd(), and VariableNameGetIdx().
char HashListTableDefaultCompare (void * , uint16_t , void * , uint16_t)
Definition at line 237 of file util-hashlist.c.
References SCMemcmp.
Referenced by HashListTableInit().
void HashListTableFree (HashListTable *)
Definition at line 82 of file util-hashlist.c.
References HashListTable_::array, HashListTable_::array_size, HashListTableBucket_::bucknext, HashListTableBucket_::data, HashListTable_::Free, and SCFree.
Referenced by DetectParseDupSigHashFree(), DetectPortDpHashFree(), DetectPortSpHashFree(), SigGroupHeadDPortHashFree(), SigGroupHeadHashFree(), SigGroupHeadMpmHashFree(), SigGroupHeadMpmStreamHashFree(), SigGroupHeadMpmUriHashFree(), SigGroupHeadSPortHashFree(), and VariableNameFreeHash().
uint32_t HashListTableGenericHash (HashListTable * , void * , uint16_t)
Definition at line 273 of file util-hashlist.c.
References HashListTable_::array_size.
HashListTableBucket* HashListTableGetListHead (HashListTable *)
Definition at line 290 of file util-hashlist.c.
References HashListTable_::listhead.
Referenced by CreateGroupedPortList(), and SigGroupHeadFreeMpmArrays().
HashListTable* HashListTableInit (uint32_t , uint32_t(*)(struct HashListTable_ *, void *, uint16_t) Hash, char(*)(void *, uint16_t, void *, uint16_t) Compare, void(*)(void *) Free)
Definition at line 35 of file util-hashlist.c.
References HashListTable_::array, HashListTable_::array_size, HashTable_::Compare, HashListTable_::Compare, HashTable_::Free, HashListTable_::Free, HashTable_::Hash, HashListTable_::Hash, HashListTableDefaultCompare(), HashListTable_::listhead, HashListTable_::listtail, SCFree, SCMalloc, and unlikely.
Referenced by DetectParseDupSigHashInit(), DetectPortDpHashInit(), DetectPortSpHashInit(), SigGroupHeadDPortHashInit(), SigGroupHeadHashInit(), SigGroupHeadMpmHashInit(), SigGroupHeadMpmStreamHashInit(), SigGroupHeadMpmUriHashInit(), SigGroupHeadSPortHashInit(), and VariableNameInitHash().
void* HashListTableLookup (HashListTable * , void * , uint16_t)
Definition at line 248 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTable_::Compare, HashListTableBucket_::data, HashListTable_::Hash, SCLogDebug, and HashListTableBucket_::size.
Referenced by DetectPortDpHashLookup(), DetectPortSpHashLookup(), SigGroupHeadDPortHashLookup(), SigGroupHeadHashLookup(), SigGroupHeadMpmHashLookup(), SigGroupHeadMpmStreamHashLookup(), SigGroupHeadMpmUriHashLookup(), SigGroupHeadSPortHashLookup(), VariableIdxGetName(), and VariableNameGetIdx().
void HashListTablePrint (HashListTable *)
Definition at line 108 of file util-hashlist.c.
References HashListTable_::array_size, and HashListTable_::Hash.
void HashListTableRegisterTests (void)
Definition at line 501 of file util-hashlist.c.
Referenced by RunUnittests().
int HashListTableRemove (HashListTable * , void * , uint16_t)
Definition at line 157 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTable_::Compare, HashListTableBucket_::data, HashListTable_::Free, HashListTable_::Hash, HashListTable_::listhead, HashListTableBucket_::listnext, HashListTableBucket_::listprev, HashListTable_::listtail, SCFree, SCLogDebug, and HashListTableBucket_::size.
Referenced by SigGroupHeadHashRemove(), and SigGroupHeadSPortHashRemove().