suricata: src/util-decode-asn1.c File Reference
util-decode-asn1.c File Reference
#include "suricata.h"
#include "suricata-common.h"
#include "decode.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-print.h"
#include "util-decode-asn1.h"
#include "conf.h"
Functions
void SCAsn1LoadConfig ()
uint8_t SCAsn1GetHighTagNumber (Asn1Ctx *ac)
Decode and check the identifier information of the current node that is in extended format.
uint32_t SCAsn1GetLengthLongForm (Asn1Ctx *ac)
Decode and check the length, of the current node in definite but extended format, that we are parsing, checking invalid opts.
uint8_t SCAsn1DecodeContent (Asn1Ctx *ac)
Check the content length and perform other inspections and decodings if necessary.
uint8_t SCAsn1DecodeLength (Asn1Ctx *ac)
Decode and check the length, of the current node that we are parsing, also check invalid opts.
uint8_t SCAsn1DecodeIdentifier (Asn1Ctx *ac)
Decode and check the identifier information of the current node that we are parsing, also check invalid opts.
void SCPrintByteBin (uint8_t byte)
Helper function that print the bits of a byte to check encoding internals.
uint8_t SCAsn1CheckBounds (Asn1Ctx *ac)
check if we have remaining data available, otherwise the parser should stop
Asn1Ctx * SCAsn1CtxNew (void)
Create a new ASN1 Parsing context.
void SCAsn1CtxDestroy (Asn1Ctx *ac)
Destroy an ASN1 Parsing context.
Asn1Node * SCAsn1CtxNewFrame (Asn1Ctx *ac, uint16_t node)
Create a new node at the array stack of frames in the ctx.
void SCAsn1CtxInit (Asn1Ctx *ac, uint8_t *data, uint16_t length)
Initialize the data of the ASN1 parser ctx with the asn1 raw buffer.
uint8_t SCAsn1Decode (Asn1Ctx *ac, uint16_t node_id)
Decode the nodes/frames located at certain position/level.
void DecodeAsn1RegisterTests (void)
Variables
uint16_t asn1_max_frames_config = ASN1_MAX_FRAMES
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Implements ASN1 decoding (needed for the asn1 keyword, BER, CER & DER)
Definition in file util-decode-asn1.c.
Function Documentation
void DecodeAsn1RegisterTests (void)
Definition at line 886 of file util-decode-asn1.c.
Referenced by RunUnittests().
uint8_t SCAsn1CheckBounds (Asn1Ctx * ac)
check if we have remaining data available, otherwise the parser should stop
Parameters
ac Asn1Ctx pointer initialized
Return values
1 if we are out of bounds, 0 if not
Definition at line 335 of file util-decode-asn1.c.
References ASN1_PARSER_ERR, ASN1_PARSER_OK, Asn1Ctx_::data, Asn1Ctx_::end, and Asn1Ctx_::iter.
Referenced by SCAsn1Decode(), SCAsn1DecodeIdentifier(), SCAsn1DecodeLength(), SCAsn1GetHighTagNumber(), and SCAsn1GetLengthLongForm().
void SCAsn1CtxDestroy (Asn1Ctx * ac)
Destroy an ASN1 Parsing context.
Parameters
Asn1Ctx pointer to the new ctx
Definition at line 371 of file util-decode-asn1.c.
References ASN1CTX_GET_NODE, Asn1Ctx_::cur_frame, and SCFree.
Referenced by DetectAsn1Match().
void SCAsn1CtxInit (Asn1Ctx * ac, uint8_t * data, uint16_t length)
Initialize the data of the ASN1 parser ctx with the asn1 raw buffer.
Parameters
ac pointer to the ASN1 ctx
data pointer to the data to process (binary raw of asn1)
length length of the asn1 raw buffer
Return values
void
Definition at line 420 of file util-decode-asn1.c.
References ASN1_STATUS_OK, Asn1Ctx_::data, data, Asn1Ctx_::end, Asn1Ctx_::iter, Asn1Ctx_::len, length, and Asn1Ctx_::parser_status.
Referenced by DetectAsn1Match().
Asn1Ctx* SCAsn1CtxNew (void)
Create a new ASN1 Parsing context.
Return values
Asn1Ctx pointer to the new ctx
Definition at line 346 of file util-decode-asn1.c.
References asn1_max_frames_config, Asn1Ctx_::asn1_stack, SC_ERR_MEM_ALLOC, SCFree, SCLogError, SCMalloc, and unlikely.
Referenced by DetectAsn1Match().
Asn1Node* SCAsn1CtxNewFrame (Asn1Ctx * ac, uint16_t node)
Create a new node at the array stack of frames in the ctx.
Parameters
ac pointer to the ASN1 ctx
node index of the frame that we are going to allocate at the asn1 stack in the parser
Return values
Asn1Node pointer to the new node allocated
Definition at line 395 of file util-decode-asn1.c.
References asn1_max_frames_config, Asn1Ctx_::asn1_stack, and SCMalloc.
Referenced by SCAsn1Decode().
uint8_t SCAsn1Decode (Asn1Ctx * ac, uint16_t node_id)
Decode the nodes/frames located at certain position/level.
Parameters
ac pointer to the ASN1 ctx
node_id node index at the asn1 stack of the ctx
Return values
byte of parser status
Definition at line 437 of file util-decode-asn1.c.
References ASN1_BER_EVENT_INVALID_ID, ASN1_BER_EVENT_INVALID_LEN, asn1_max_frames_config, ASN1_NODE_IS_EOC, ASN1_PARSER_ERR, ASN1_PARSER_OK, ASN1_STATUS_DONE, ASN1_TAG_TYPE_CONSTRUCTED, ASN1CTX_GET_NODE, Asn1Id_::class_tag, Asn1Ctx_::ctx_flags, Asn1Ctx_::cur_frame, Asn1Node_::data, Asn1Ctx_::end, Asn1Node_::flags, Asn1Node_::id, Asn1Ctx_::iter, Asn1Len_::len, Asn1Data_::len, Asn1Node_::len, Asn1Ctx_::parser_status, PrintRawDataFp(), Asn1Data_::ptr, SCAsn1CheckBounds(), SCAsn1CtxNewFrame(), SCAsn1Decode(), SCAsn1DecodeContent(), SCAsn1DecodeIdentifier(), SCAsn1DecodeLength(), SCLogDebug, Asn1Id_::tag_num, and Asn1Id_::tag_type.
Referenced by DetectAsn1Match(), and SCAsn1Decode().
uint8_t SCAsn1DecodeContent (Asn1Ctx * ac)
Check the content length and perform other inspections and decodings if necessary.
Parameters
ac pointer to the ASN1 Context data
Return values
byte of the status of the parser
Definition at line 175 of file util-decode-asn1.c.
References ASN1_BER_LEN_INDEFINITE, ASN1_NODE_IS_EOC, ASN1_PARSER_OK, ASN1CTX_CUR_NODE, Asn1Node_::data, Asn1Ctx_::end, Asn1Node_::flags, Asn1Len_::form, Asn1Ctx_::iter, Asn1Len_::len, Asn1Data_::len, Asn1Node_::len, and Asn1Data_::ptr.
Referenced by SCAsn1Decode().
uint8_t SCAsn1DecodeIdentifier (Asn1Ctx * ac)
Decode and check the identifier information of the current node that we are parsing, also check invalid opts.
Parameters
ac pointer to the ASN1 Context data
Return values
byte of the status of the parser
Definition at line 285 of file util-decode-asn1.c.
References ASN1_BER_GET_CLASS_TAG, ASN1_BER_GET_LOW_TAG_NUM, ASN1_BER_IS_CONSTRUCTED, ASN1_BER_IS_HIGH_TAG, ASN1_PARSER_ERR, ASN1_PARSER_OK, ASN1_STATUS_INVALID, ASN1_STATUS_OOB, ASN1CTX_CUR_NODE, Asn1Id_::class_tag, Asn1Node_::id, Asn1Ctx_::iter, Asn1Ctx_::parser_status, Asn1Id_::ptr, SCAsn1CheckBounds(), SCAsn1GetHighTagNumber(), Asn1Id_::tag_num, and Asn1Id_::tag_type.
Referenced by SCAsn1Decode().
uint8_t SCAsn1DecodeLength (Asn1Ctx * ac)
Decode and check the length, of the current node that we are parsing, also check invalid opts.
Parameters
ac pointer to the ASN1 Context data
Return values
byte of the status of the parser
Definition at line 215 of file util-decode-asn1.c.
References ASN1_BER_EVENT_EOC_NOT_FOUND, ASN1_BER_GET_SHORT_LEN, ASN1_BER_IS_EOC, ASN1_BER_IS_INDEFINITE_LEN, ASN1_BER_IS_SHORT_LEN, ASN1_BER_LEN_INDEFINITE, ASN1_BER_LEN_LONG, ASN1_BER_LEN_SHORT, ASN1_NODE_IS_EOC, ASN1_PARSER_ERR, ASN1_PARSER_OK, ASN1_STATUS_INVALID, ASN1_STATUS_OOB, ASN1CTX_CUR_NODE, Asn1Node_::data, Asn1Ctx_::end, Asn1Node_::flags, Asn1Len_::form, Asn1Node_::id, Asn1Ctx_::iter, Asn1Len_::len, Asn1Data_::len, Asn1Node_::len, Asn1Ctx_::parser_status, Asn1Len_::ptr, Asn1Id_::ptr, SCAsn1CheckBounds(), and SCAsn1GetLengthLongForm().
Referenced by SCAsn1Decode().
uint8_t SCAsn1GetHighTagNumber (Asn1Ctx * ac)
Decode and check the identifier information of the current node that is in extended format.
Parameters
ac pointer to the ASN1 Context data
Return values
byte of the status of the parser
Definition at line 58 of file util-decode-asn1.c.
References ASN1_BER_EVENT_ID_TOO_LONG, ASN1_BER_EVENT_INVALID_ID, ASN1_BER_GET_HIGH_TAG_NUM, ASN1_BER_IS_HIGH_TAG_END, ASN1_PARSER_ERR, ASN1_PARSER_OK, ASN1_STATUS_INVALID, ASN1_STATUS_OOB, ASN1CTX_CUR_NODE, Asn1Node_::flags, Asn1Node_::id, Asn1Ctx_::iter, Asn1Ctx_::parser_status, SCAsn1CheckBounds(), and Asn1Id_::tag_num.
Referenced by SCAsn1DecodeIdentifier().
uint32_t SCAsn1GetLengthLongForm (Asn1Ctx * ac)
Decode and check the length, of the current node in definite but extended format, that we are parsing, checking invalid opts.
Parameters
ac pointer to the ASN1 Context data
Return values
byte of the status of the parser
Definition at line 122 of file util-decode-asn1.c.
References ASN1_BER_EVENT_INVALID_LEN, ASN1_BER_EVENT_LEN_TOO_LONG, ASN1_BER_GET_HIGH_TAG_NUM, ASN1_BER_GET_LONG_LEN_OCTETS, ASN1_PARSER_ERR, ASN1_PARSER_OK, ASN1_STATUS_INVALID, ASN1_STATUS_OOB, ASN1CTX_CUR_NODE, Asn1Node_::flags, Asn1Ctx_::iter, Asn1Len_::len, Asn1Node_::len, Asn1Ctx_::parser_status, Asn1Len_::ptr, and SCAsn1CheckBounds().
Referenced by SCAsn1DecodeLength().
void SCAsn1LoadConfig ()
set config defaults
Definition at line 38 of file util-decode-asn1.c.
References asn1_max_frames_config, ConfGetInt(), and SCLogDebug.
Referenced by main().
void SCPrintByteBin (uint8_t byte)
Helper function that print the bits of a byte to check encoding internals.
Parameters
byte value of the byte
Definition at line 318 of file util-decode-asn1.c.
Variable Documentation
uint16_t asn1_max_frames_config = ASN1_MAX_FRAMES
Definition at line 36 of file util-decode-asn1.c.
Referenced by SCAsn1CtxNew(), SCAsn1CtxNewFrame(), SCAsn1Decode(), and SCAsn1LoadConfig().