suricata: src/util-host-os-info.c File Reference
util-host-os-info.c File Reference
#include "suricata-common.h"
#include "util-host-os-info.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-ip.h"
#include "util-radix-tree.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "util-enum.h"
#include "util-unittest.h"
Functions
int SCHInfoAddHostOSInfo (char *host_os, char *host_os_ip_range, int is_ipv4)
Used to add the host-os-info data obtained from the conf.
int SCHInfoGetHostOSFlavour (char *ip_addr_str)
Retrieves the host os flavour, given an ipv4/ipv6 address as a string.
int SCHInfoGetIPv4HostOSFlavour (uint8_t *ipv4_addr)
Retrieves the host os flavour, given an ipv4 address in the raw address format.
int SCHInfoGetIPv6HostOSFlavour (uint8_t *ipv6_addr)
Retrieves the host os flavour, given an ipv6 address in the raw address format.
void SCHInfoCleanResources (void)
void SCHInfoLoadFromConfig (void)
Load the host os policy information from the configuration.
void SCHInfoRegisterTests (void)
Variables
SCEnumCharMap sc_hinfo_os_policy_map []
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Host info utility functions
Definition in file util-host-os-info.c.
Function Documentation
int SCHInfoAddHostOSInfo (char * host_os, char * host_os_ip_range, int is_ipv4)
Used to add the host-os-info data obtained from the conf.
Parameters
host_os The host_os name/flavour from the conf file
host_os_ip_range Pointer to a char string holding the ip/ip_netblock for the host_os specified in the first argument
is_ipv4 Indicates if the ip address to be considered for the default configuration is IPV4; if not it is IPV6. Specified using SC_HINFO_IS_IPV6 or SC_HINFO_IS_IPV4
Return values
0 On successfully adding the host os info to the Radix tree
-1 On failure (only specified from config, at the startup)
Definition at line 122 of file util-host-os-info.c.
References FALSE, index, MaskIPNetblock(), SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_ENUM_MAP, SC_ERR_INVALID_IP_NETBLOCK, SC_ERR_INVALID_IPV4_ADDR, SC_ERR_INVALID_IPV6_ADDR, SC_ERR_MEM_ALLOC, SCFree, SCHInfoAddHostOSInfo(), SCLogError, SCRadixAddKeyIPV4(), SCRadixAddKeyIPV4Netblock(), SCRadixAddKeyIPV6(), SCRadixAddKeyIPV6Netblock(), SCRadixCreateRadixTree(), SCStrdup, TRUE, ValidateIPV4Address(), and ValidateIPV6Address().
Referenced by SCHInfoAddHostOSInfo(), and SCHInfoLoadFromConfig().
void SCHInfoCleanResources (void)
Definition at line 319 of file util-host-os-info.c.
References SCRadixReleaseRadixTree().
int SCHInfoGetHostOSFlavour (char * ip_addr_str)
Retrieves the host os flavour, given an ipv4/ipv6 address as a string.
Parameters
Pointer to a string containing an IP address
Return values
The OS flavour on success; -1 on failure, or on not finding the key
Definition at line 249 of file util-host-os-info.c.
References index, SC_ERR_INVALID_IPV4_ADDR, SCLogError, SCRadixFindKeyIPV4BestMatch(), SCRadixFindKeyIPV6BestMatch(), ValidateIPV4Address(), and ValidateIPV6Address().
int SCHInfoGetIPv4HostOSFlavour (uint8_t * ipv4_addr)
Retrieves the host os flavour, given an ipv4 address in the raw address format.
Parameters
Pointer to a raw ipv4 address.
Return values
The OS flavour on success; -1 on failure, or on not finding the key
Definition at line 291 of file util-host-os-info.c.
References SCRadixFindKeyIPV4BestMatch().
Referenced by DefragGetOsPolicy(), and StreamTcpSetOSPolicy().
int SCHInfoGetIPv6HostOSFlavour (uint8_t * ipv6_addr)
Retrieves the host os flavour, given an ipv6 address in the raw address format.
Parameters
Pointer to a raw ipv6 address.
Return values
The OS flavour on success; -1 on failure, or on not finding the key
Definition at line 309 of file util-host-os-info.c.
References SCRadixFindKeyIPV6BestMatch().
Referenced by DefragGetOsPolicy(), and StreamTcpSetOSPolicy().
void SCHInfoLoadFromConfig (void)
Load the host os policy information from the configuration.
(A mem alloc error should cause an exit failure)
Definition at line 334 of file util-host-os-info.c.
References ConfGetNode(), index, ConfNode_::name, next, SC_ERR_INVALID_ARGUMENT, SCHInfoAddHostOSInfo(), SCLogError, TAILQ_FOREACH, and ConfNode_::val.
void SCHInfoRegisterTests (void)
Definition at line 1626 of file util-host-os-info.c.
Referenced by RunUnittests().
Variable Documentation
SCEnumCharMap sc_hinfo_os_policy_map[]
Initial value:
= {
    { "none",        OS_POLICY_NONE },
    { "bsd",         OS_POLICY_BSD },
    { "bsd-right",   OS_POLICY_BSD_RIGHT },
    { "old-linux",   OS_POLICY_OLD_LINUX },
    { "linux",       OS_POLICY_LINUX },
    { "old-solaris", OS_POLICY_OLD_SOLARIS },
    { "solaris",     OS_POLICY_SOLARIS },
    { "hpux10",      OS_POLICY_HPUX10 },
    { "hpux11",      OS_POLICY_HPUX11 },
    { "irix",        OS_POLICY_IRIX },
    { "macos",       OS_POLICY_MACOS },
    { "windows",     OS_POLICY_WINDOWS },
    { "vista",       OS_POLICY_VISTA },
    { "windows2k3",  OS_POLICY_WINDOWS2K3 },
    { NULL,          -1 },
}
Enum map for the various OS flavours
Definition at line 42 of file util-host-os-info.c.