suricata: src/util-decode-mime.h File Reference
util-decode-mime.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "suricata.h"
#include "util-base64.h"
#include "util-debug.h"
Data Structures
struct MimeDecConfig
Structure for containing configuration options.
struct MimeDecField
This represents a header field name and associated value.
struct MimeDecUrl
This represents a URL value node in a linked list.
struct MimeDecEntity
This represents the MIME Entity (or also top level message) in a child-sibling tree.
struct MimeDecStackNode
Structure contains boundary and entity for the current node (entity) in the stack.
struct MimeDecStack
Structure holds the top of the stack along with some free reusable nodes.
struct DataValue
Structure contains a list of value and lengths for robust data processing.
struct MimeDecParseState
Structure contains the current state of the MIME parser.
Macros
#define CTNT_IS_MSG 1
#define CTNT_IS_ENV 2
#define CTNT_IS_ENCAP 4
#define CTNT_IS_BODYPART 8
#define CTNT_IS_MULTIPART 16
#define CTNT_IS_ATTACHMENT 32
#define CTNT_IS_BASE64 64
#define CTNT_IS_QP 128
#define CTNT_IS_TEXT 256
#define CTNT_IS_HTML 512
#define URL_IS_IP4 1
#define URL_IS_IP6 2
#define URL_IS_EXE 4
#define ANOM_INVALID_BASE64 1 /* invalid base64 chars */
#define ANOM_INVALID_QP 2 /* invalid qouted-printable chars */
#define ANOM_LONG_HEADER_NAME 4 /* header is abnormally long */
#define ANOM_LONG_HEADER_VALUE
#define ANOM_LONG_LINE 16 /* Lines that exceed 998 octets */
#define ANOM_LONG_ENC_LINE 32 /* Lines that exceed 76 octets */
#define ANOM_MALFORMED_MSG 64 /* Misc msg format errors found */
#define ANOM_LONG_BOUNDARY 128 /* Boundary too long */
#define DATA_CHUNK_SIZE 3072 /* Should be divisible by 3 */
#define LINEREM_SIZE 256
#define HEADER_READY 0x01
#define HEADER_STARTED 0x02
#define HEADER_DONE 0x03
#define BODY_STARTED 0x04
#define BODY_DONE 0x05
#define BODY_END_BOUND 0x06
#define PARSE_DONE 0x07
#define PARSE_ERROR 0x08
Typedefs
typedef enum MimeDecRetCode MimeDecRetCode
Mime Decoder Error Codes.
typedef struct MimeDecConfig MimeDecConfig
Structure for containing configuration options.
typedef struct MimeDecField MimeDecField
This represents a header field name and associated value.
typedef struct MimeDecUrl MimeDecUrl
This represents a URL value node in a linked list.
typedef struct MimeDecEntity MimeDecEntity
This represents the MIME Entity (or also top level message) in a child-sibling tree.
typedef struct MimeDecStackNode MimeDecStackNode
Structure contains boundary and entity for the current node (entity) in the stack.
typedef struct MimeDecStack MimeDecStack
Structure holds the top of the stack along with some free reusable nodes.
typedef struct DataValue DataValue
Structure contains a list of value and lengths for robust data processing.
typedef struct MimeDecParseState MimeDecParseState
Structure contains the current state of the MIME parser.
Enumerations
enum MimeDecRetCode {
MIME_DEC_OK = 0, MIME_DEC_MORE = 1, MIME_DEC_ERR_DATA = -1, MIME_DEC_ERR_MEM = -2,
MIME_DEC_ERR_PARSE = -3
}
Mime Decoder Error Codes.
Functions
void MimeDecSetConfig (MimeDecConfig *config)
Set global config policy.
MimeDecConfig * MimeDecGetConfig (void)
Get global config policy.
void MimeDecFreeEntity (MimeDecEntity *entity)
Frees a mime entity tree.
void MimeDecFreeField (MimeDecField *field)
Iteratively frees a header field entry list.
void MimeDecFreeUrl (MimeDecUrl *url)
Iteratively frees a URL entry list.
MimeDecField * MimeDecAddField (MimeDecEntity *entity)
Creates and adds a header field entry to an entity.
MimeDecField * MimeDecFindField (const MimeDecEntity *entity, const char *name)
Searches for a header field with the specified name.
int MimeDecFindFieldsForEach (const MimeDecEntity *entity, const char *name, int(*DataCallback)(const uint8_t *val, const size_t, void *data), void *data)
Searches for header fields with the specified name.
MimeDecEntity * MimeDecAddEntity (MimeDecEntity *parent)
Creates and adds a child entity to the specified parent entity.
MimeDecParseState * MimeDecInitParser (void *data, int(*dcpfunc)(const uint8_t *chunk, uint32_t len, MimeDecParseState *state))
Init the parser by allocating memory for the state and top-level entity.
void MimeDecDeInitParser (MimeDecParseState *state)
De-Init parser by freeing up any residual memory.
int MimeDecParseComplete (MimeDecParseState *state)
Called to indicate that the last message line has been processed and the parsing operation is complete.
int MimeDecParseLine (const uint8_t *line, const uint32_t len, const uint8_t delim_len, MimeDecParseState *state)
Parse a line of a MIME message and update the parser state.
MimeDecEntity * MimeDecParseFullMsg (const uint8_t *buf, uint32_t blen, void *data, int(*DataChunkProcessorFunc)(const uint8_t *chunk, uint32_t len, MimeDecParseState *state))
Parses an entire message when available in its entirety (wraps the line-based parsing functions)
const char * MimeDecParseStateGetStatus (MimeDecParseState *state)
void MimeDecRegisterTests (void)
Detailed Description
Author
David Abarbanel david.nosp@m..aba.nosp@m.rbane.nosp@m.l@ba.nosp@m.esyst.nosp@m.ems..nosp@m.com
Definition in file util-decode-mime.h.
Macro Definition Documentation
#define ANOM_INVALID_BASE64 1 /* invalid base64 chars */
Definition at line 54 of file util-decode-mime.h.
#define ANOM_INVALID_QP 2 /* invalid qouted-printable chars */
Definition at line 55 of file util-decode-mime.h.
#define ANOM_LONG_BOUNDARY 128 /* Boundary too long */
Definition at line 62 of file util-decode-mime.h.
#define ANOM_LONG_ENC_LINE 32 /* Lines that exceed 76 octets */
Definition at line 60 of file util-decode-mime.h.
#define ANOM_LONG_HEADER_NAME 4 /* header is abnormally long */
Definition at line 56 of file util-decode-mime.h.
#define ANOM_LONG_HEADER_VALUE
Value:
8  /* header value is abnormally long
                                     * (includes multi-line) */
Definition at line 57 of file util-decode-mime.h.
#define ANOM_LONG_LINE 16 /* Lines that exceed 998 octets */
Definition at line 59 of file util-decode-mime.h.
#define ANOM_MALFORMED_MSG 64 /* Misc msg format errors found */
Definition at line 61 of file util-decode-mime.h.
Referenced by MimeDecDeInitParser(), and MimeDecParseComplete().
#define BODY_DONE 0x05
Definition at line 73 of file util-decode-mime.h.
#define BODY_END_BOUND 0x06
Definition at line 74 of file util-decode-mime.h.
#define BODY_STARTED 0x04
Definition at line 72 of file util-decode-mime.h.
#define CTNT_IS_ATTACHMENT 32
Definition at line 42 of file util-decode-mime.h.
Referenced by SMTPProcessDataChunk().
#define CTNT_IS_BASE64 64
Definition at line 43 of file util-decode-mime.h.
#define CTNT_IS_BODYPART 8
Definition at line 40 of file util-decode-mime.h.
#define CTNT_IS_ENCAP 4
Definition at line 39 of file util-decode-mime.h.
#define CTNT_IS_ENV 2
Definition at line 38 of file util-decode-mime.h.
#define CTNT_IS_HTML 512
Definition at line 46 of file util-decode-mime.h.
#define CTNT_IS_MSG 1
Definition at line 37 of file util-decode-mime.h.
Referenced by MimeDecInitParser().
#define CTNT_IS_MULTIPART 16
Definition at line 41 of file util-decode-mime.h.
#define CTNT_IS_QP 128
Definition at line 44 of file util-decode-mime.h.
#define CTNT_IS_TEXT 256
Definition at line 45 of file util-decode-mime.h.
#define DATA_CHUNK_SIZE 3072 /* Should be divisible by 3 */
Definition at line 65 of file util-decode-mime.h.
#define HEADER_DONE 0x03
Definition at line 71 of file util-decode-mime.h.
#define HEADER_READY 0x01
Definition at line 69 of file util-decode-mime.h.
Referenced by MimeDecInitParser().
#define HEADER_STARTED 0x02
Definition at line 70 of file util-decode-mime.h.
#define LINEREM_SIZE 256
Definition at line 66 of file util-decode-mime.h.
#define PARSE_DONE 0x07
Definition at line 75 of file util-decode-mime.h.
Referenced by MimeDecParseComplete().
#define PARSE_ERROR 0x08
Definition at line 76 of file util-decode-mime.h.
Referenced by MimeDecParseLine().
#define URL_IS_EXE 4
Definition at line 51 of file util-decode-mime.h.
#define URL_IS_IP4 1
Definition at line 49 of file util-decode-mime.h.
#define URL_IS_IP6 2
Definition at line 50 of file util-decode-mime.h.
Typedef Documentation
typedef struct DataValue DataValue
Structure contains a list of value and lengths for robust data processing.
typedef struct MimeDecConfig MimeDecConfig
Structure for containing configuration options.
typedef struct MimeDecEntity MimeDecEntity
This represents the MIME Entity (or also top level message) in a child-sibling tree.
typedef struct MimeDecField MimeDecField
This represents a header field name and associated value.
typedef struct MimeDecParseState MimeDecParseState
Structure contains the current state of the MIME parser.
typedef enum MimeDecRetCode MimeDecRetCode
Mime Decoder Error Codes.
typedef struct MimeDecStack MimeDecStack
Structure holds the top of the stack along with some free reusable nodes.
typedef struct MimeDecStackNode MimeDecStackNode
Structure contains boundary and entity for the current node (entity) in the stack.
typedef struct MimeDecUrl MimeDecUrl
This represents a URL value node in a linked list.
Since HTML can sometimes contain a high number of URLs, this structure only features the URL host name/IP or those that are pointing to an executable file (see url_flags to determine which).
Enumeration Type Documentation
enum MimeDecRetCode
Mime Decoder Error Codes.
Enumerator
MIME_DEC_OK
MIME_DEC_MORE
MIME_DEC_ERR_DATA
MIME_DEC_ERR_MEM
MIME_DEC_ERR_PARSE
Definition at line 81 of file util-decode-mime.h.
Function Documentation
MimeDecEntity* MimeDecAddEntity (MimeDecEntity * parent)
Creates and adds a child entity to the specified parent entity.
Parameters
parent The parent entity
Returns
The child entity, or NULL if the operation fails
Definition at line 398 of file util-decode-mime.c.
References MimeDecEntity::child, MimeDecEntity::next, SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, and unlikely.
MimeDecField* MimeDecAddField (MimeDecEntity * entity)
Creates and adds a header field entry to an entity.
The entity is optional. If NULL is specified, than a new stand-alone field is created.
Parameters
entity The parent entity
Returns
The field object, or NULL if the operation fails
Definition at line 278 of file util-decode-mime.c.
References MimeDecEntity::field_list, MimeDecField::next, SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, and unlikely.
void MimeDecDeInitParser (MimeDecParseState * state)
De-Init parser by freeing up any residual memory.
Parameters
state The parser state
Returns
none
Definition at line 2428 of file util-decode-mime.c.
References ANOM_MALFORMED_MSG, MimeDecEntity::anomaly_flags, MimeDecStackNode::data, MimeDecParseState::hname, MimeDecParseState::hvalue, MimeDecParseState::msg, SCFree, SCLogDebug, MimeDecParseState::stack, and MimeDecStack::top.
Referenced by MimeDecParseFullMsg().
MimeDecField* MimeDecFindField (const MimeDecEntity * entity, const char * name)
Searches for a header field with the specified name.
Parameters
entity The entity to search
name The header name (lowercase)
Returns
The field object, or NULL if not found
Definition at line 338 of file util-decode-mime.c.
References MimeDecEntity::field_list, MimeDecField::name, MimeDecField::name_len, MimeDecField::next, SCMemcmp, and Asn1Generic_::strlen.
int MimeDecFindFieldsForEach (const MimeDecEntity * entity, const char * name, int(*)(const uint8_t *val, const size_t, void *data) DataCallback, void * data)
Searches for header fields with the specified name.
Parameters
entity The entity to search
name The header name (lowercase)
Returns
number of items found
Definition at line 310 of file util-decode-mime.c.
References MimeDecEntity::field_list, MimeDecField::name, MimeDecField::name_len, MimeDecField::next, SCMemcmp, Asn1Generic_::strlen, MimeDecField::value, and MimeDecField::value_len.
void MimeDecFreeEntity (MimeDecEntity * entity)
Frees a mime entity tree.
Parameters
entity The root entity
Returns
none
Move child to next Transform tree into list
Move to next element
Definition at line 181 of file util-decode-mime.c.
References MimeDecEntity::child, MimeDecEntity::field_list, MimeDecEntity::filename, MimeDecFreeField(), MimeDecFreeUrl(), MimeDecEntity::next, SCFree, and MimeDecEntity::url_list.
Referenced by MimeDecParseFullMsg().
void MimeDecFreeField (MimeDecField * field)
Iteratively frees a header field entry list.
Parameters
field The header field
Returns
none
Definition at line 220 of file util-decode-mime.c.
References MimeDecField::name, MimeDecField::next, SCFree, and MimeDecField::value.
Referenced by MimeDecFreeEntity().
void MimeDecFreeUrl (MimeDecUrl * url)
Iteratively frees a URL entry list.
Parameters
url The url entry
Returns
none
Definition at line 249 of file util-decode-mime.c.
References MimeDecUrl::next, SCFree, and MimeDecUrl::url.
Referenced by MimeDecFreeEntity().
MimeDecConfig* MimeDecGetConfig (void)
Get global config policy.
Returns
config data structure
Definition at line 151 of file util-decode-mime.c.
MimeDecParseState* MimeDecInitParser (void * data, int(*)(const uint8_t *chunk, uint32_t len, MimeDecParseState *state) DataChunkProcessorFunc)
Init the parser by allocating memory for the state and top-level entity.
Parameters
data A caller-specified pointer to data for access within the data chunk processor callback function
dcpfunc The data chunk processor callback function
Returns
A pointer to the state object, or NULL if the operation fails
Definition at line 2372 of file util-decode-mime.c.
References MimeDecEntity::ctnt_flags, CTNT_IS_MSG, MimeDecStackNode::data, MimeDecParseState::data, data, MimeDecParseState::DataChunkProcessorFunc, HEADER_READY, MimeDecParseState::msg, SC_ERR_MEM_ALLOC, SCFree, SCLogError, SCMalloc, MimeDecParseState::stack, MimeDecParseState::state_flag, MimeDecStack::top, and unlikely.
Referenced by MimeDecParseFullMsg().
int MimeDecParseComplete (MimeDecParseState * state)
Called to indicate that the last message line has been processed and the parsing operation is complete.
This function should be called directly by the caller.
Parameters
state The parser state
Returns
MIME_DEC_OK on success, otherwise < 0 on failure
Definition at line 2466 of file util-decode-mime.c.
References ANOM_MALFORMED_MSG, MimeDecEntity::anomaly_flags, MimeDecStackNode::is_encap, MIME_DEC_ERR_DATA, MIME_DEC_OK, MimeDecParseState::msg, MimeDecStackNode::next, PARSE_DONE, SCLogDebug, MimeDecParseState::stack, MimeDecParseState::state_flag, and MimeDecStack::top.
Referenced by MimeDecParseFullMsg().
MimeDecEntity* MimeDecParseFullMsg (const uint8_t * buf, uint32_t blen, void * data, int(*)(const uint8_t *chunk, uint32_t len, MimeDecParseState *state) dcpfunc)
Parses an entire message when available in its entirety (wraps the line-based parsing functions)
Parameters
buf Buffer pointing to the full message
blen Length of the buffer
data Caller data to be available in callback
dcpfunc Callback for processing each decoded body data chunk
Returns
A pointer to the decoded MIME message, or NULL if the operation fails
Definition at line 2557 of file util-decode-mime.c.
References MimeDecParseState::current_line_delimiter_len, MIME_DEC_OK, MimeDecDeInitParser(), MimeDecFreeEntity(), MimeDecInitParser(), MimeDecParseComplete(), MimeDecParseLine(), MimeDecParseState::msg, msg, and SCLogDebug.
int MimeDecParseLine (const uint8_t * line, const uint32_t len, const uint8_t delim_len, MimeDecParseState * state)
Parse a line of a MIME message and update the parser state.
Parameters
line A string representing the line (w/out CRLF)
len The length of the line
delim_len The length of the line end delimiter
state The parser state
Returns
MIME_DEC_OK on success, otherwise < 0 on failure
Definition at line 2523 of file util-decode-mime.c.
References MimeDecParseState::current_line_delimiter_len, MIME_DEC_OK, PARSE_ERROR, SC_LOG_DEBUG, SCLogDebug, and MimeDecParseState::state_flag.
Referenced by MimeDecParseFullMsg().
const char* MimeDecParseStateGetStatus (MimeDecParseState * state)
Definition at line 2304 of file util-decode-mime.c.
References MimeDecParseState::state_flag.
void MimeDecRegisterTests (void)
Definition at line 2991 of file util-decode-mime.c.
Referenced by RunUnittests().
void MimeDecSetConfig (MimeDecConfig * config)
Set global config policy.
Parameters
config Config policy to set
Returns
none
Definition at line 132 of file util-decode-mime.c.
References MimeDecConfig::header_value_depth, MAX_HEADER_VALUE, SC_ERR_MISSING_CONFIG_PARAM, and SCLogWarning.