suricata: src/util-var-name.c File Reference
util-var-name.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "util-hashlist.h"
Data Structures
struct VariableName_
Name2idx mapping structure for flowbits, flowvars and pktvars.
Typedefs
typedef struct VariableName_ VariableName
Name2idx mapping structure for flowbits, flowvars and pktvars.
Functions
int VariableNameInitHash (DetectEngineCtx *de_ctx)
Initialize the Name idx hash.
void VariableNameFreeHash (DetectEngineCtx *de_ctx)
uint16_t VariableNameGetIdx (DetectEngineCtx *de_ctx, char *name, enum VarTypes type)
Get a name idx for a name. If the name is already used reuse the idx.
char * VariableIdxGetName (DetectEngineCtx *de_ctx, uint16_t idx, enum VarTypes type)
Get a name from the idx.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Generic variable name utility functions
Definition in file util-var-name.c.
Typedef Documentation
typedef struct VariableName_ VariableName
Name2idx mapping structure for flowbits, flowvars and pktvars.
Function Documentation
char* VariableIdxGetName (DetectEngineCtx * de_ctx, uint16_t idx, enum VarTypes type)
Get a name from the idx.
Parameters
idx index of the variable whose name is to be fetched
type variable type
Return values
NULL in case of error
name of the variable if successful.
Definition at line 177 of file util-var-name.c.
References HashListTableLookup(), VariableName_::idx, VariableName_::name, SCMalloc, SCStrdup, VariableName_::type, type, unlikely, and DetectEngineCtx_::variable_idxs.
void VariableNameFreeHash (DetectEngineCtx * de_ctx)
Definition at line 120 of file util-var-name.c.
References HashListTableFree(), DetectEngineCtx_::variable_idxs, and DetectEngineCtx_::variable_names.
Referenced by DetectEngineCtxFree().
uint16_t VariableNameGetIdx (DetectEngineCtx * de_ctx, char * name, enum VarTypes type)
Get a name idx for a name. If the name is already used reuse the idx.
Parameters
name nul terminated string with the name
type variable type
Return values
0 in case of error
idx the idx or 0
Definition at line 138 of file util-var-name.c.
References HashListTableAdd(), HashListTableLookup(), VariableName_::idx, VariableName_::name, SCMalloc, SCStrdup, VariableName_::type, type, unlikely, DetectEngineCtx_::variable_idxs, DetectEngineCtx_::variable_names, and DetectEngineCtx_::variable_names_idx.
Referenced by DetectFlowintMatch(), and DetectFlowintParse().
int VariableNameInitHash (DetectEngineCtx * de_ctx)
Initialize the Name idx hash.
Parameters
de_ctx Ptr to the detection engine ctx.
Return values
-1 in case of error
0 in case of success
Definition at line 106 of file util-var-name.c.
References HashListTableInit(), DetectEngineCtx_::variable_idxs, DetectEngineCtx_::variable_names, and DetectEngineCtx_::variable_names_idx.