suricata: src/util-spm.c File Reference
util-spm.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "util-unittest.h"
#include "util-spm.h"
#include "util-spm-bs.h"
#include "util-spm-bs2bm.h"
#include "util-spm-bm.h"
#include "util-clock.h"
Functions
uint8_t * Bs2bmSearch (uint8_t *text, uint32_t textlen, uint8_t *needle, uint16_t needlelen)
Search a pattern in the text using the Bs2Bm algorithm (build a bad characters array)
uint8_t * Bs2bmNocaseSearch (uint8_t *text, uint32_t textlen, uint8_t *needle, uint16_t needlelen)
Search a pattern in the text using the Bs2Bm nocase algorithm (build a bad characters array)
uint8_t * BoyerMooreSearch (uint8_t *text, uint32_t textlen, uint8_t *needle, uint16_t needlelen)
Search a pattern in the text using Boyer Moore algorithm (build a bad character shifts array and good prefixes shift array)
uint8_t * BoyerMooreNocaseSearch (uint8_t *text, uint32_t textlen, uint8_t *needle, uint16_t needlelen)
Search a pattern in the text using Boyer Moore nocase algorithm (build a bad character shifts array and good prefixes shift array)
void UtilSpmSearchRegistertests (void)
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
PR (17/01/2010): Single pattern search algorithms: Currently there are 3 algorithms to choose: BasicSearch, Bs2Bm and BoyerMoore (Boyer Moores algorithm). The first one doesn't need a context. But for Bs2Bm and BoyerMoore, you'll need to build some arrays.
!! If you are going to use the same pattern multiple times, please, try to store the context some where. For Bs2Bm, the context is an array of "badchars". For BoyerMoore you need to store two arrays of shifts. Have a look at the wrappers and unittests for examples of this. If you cant store the context, use the wrappers: Bs2bmSearch, BoyerMooreSearch, and the ones caseless, or BasicSearch That is the most basic.
Use the stats and util-clock.h to determine which one fit better for you Boyer Moore should be used for patterns greater than 1 of length In the range of 2 - 6, if the text length is greater than 1000 you could use boyer moore, otherwise, basic search. If the pattern is greater than 6 and the textlen is greater than 500, use boyer moore. This is an aproximation, but use the stats and util-clock to determine which one fit better for your case.
Definition in file util-spm.c.
Function Documentation
uint8_t* BoyerMooreNocaseSearch (uint8_t * text, uint32_t textlen, uint8_t * needle, uint16_t needlelen)
Search a pattern in the text using Boyer Moore nocase algorithm (build a bad character shifts array and good prefixes shift array)
Parameters
text Text to search in
textlen length of the text
needle pattern to search for
needlelen length of the pattern
Definition at line 123 of file util-spm.c.
References BoyerMooreCtxDeInit(), BoyerMooreNocase(), and BoyerMooreNocaseCtxInit().
uint8_t* BoyerMooreSearch (uint8_t * text, uint32_t textlen, uint8_t * needle, uint16_t needlelen)
Search a pattern in the text using Boyer Moore algorithm (build a bad character shifts array and good prefixes shift array)
Parameters
text Text to search in
textlen length of the text
needle pattern to search for
needlelen length of the pattern
Definition at line 104 of file util-spm.c.
References BoyerMoore(), BoyerMooreCtxDeInit(), and BoyerMooreCtxInit().
uint8_t* Bs2bmNocaseSearch (uint8_t * text, uint32_t textlen, uint8_t * needle, uint16_t needlelen)
Search a pattern in the text using the Bs2Bm nocase algorithm (build a bad characters array)
Parameters
text Text to search in
textlen length of the text
needle pattern to search for
needlelen length of the pattern
Definition at line 87 of file util-spm.c.
References ALPHABET_SIZE, Bs2BmBadchars(), and Bs2BmNocase().
uint8_t* Bs2bmSearch (uint8_t * text, uint32_t textlen, uint8_t * needle, uint16_t needlelen)
Search a pattern in the text using the Bs2Bm algorithm (build a bad characters array)
Wrappers for building context and searching (Bs2Bm and boyermoore) Use them if you cant store the context
Parameters
text Text to search in
textlen length of the text
needle pattern to search for
needlelen length of the pattern
Definition at line 71 of file util-spm.c.
References ALPHABET_SIZE, Bs2Bm(), and Bs2BmBadchars().
Referenced by HtpRequestBodyHandleMultipart().
void UtilSpmSearchRegistertests (void)
Definition at line 2318 of file util-spm.c.
Referenced by RunUnittests().