suricata: src/util-debug-filters.c File Reference
util-debug-filters.c File Reference
#include "suricata-common.h"
Functions
int SCLogAddFGFilter (const char *file, const char *function, int line, int listtype)
Helper function used internally to add a FG filter.
int SCLogMatchFGFilterWL (const char *file, const char *function, int line)
Checks if there is a match for the incoming log_message with any of the FG filters. If there is a match, it allows the message to be logged, else it rejects that message.
int SCLogMatchFGFilterBL (const char *file, const char *function, int line)
Checks if there is a match for the incoming log_message with any of the FG filters. If there is a match it rejects the logging for that messages, else it allows that message to be logged.
int SCLogAddFGFilterWL (const char *file, const char *function, int line)
Adds a Whitelist(WL) fine-grained(FG) filter. A FG filter WL filter allows messages that match this filter, to be logged, while the filter is defined using a file_name, function_name and line_number.
int SCLogAddFGFilterBL (const char *file, const char *function, int line)
Adds a Blacklist(BL) fine-grained(FG) filter. A FG filter BL filter allows messages that don't match this filter, to be logged, while the filter is defined using a file_name, function_name and line_number.
void SCLogReleaseFGFilters (void)
int SCLogPrintFGFilters ()
Prints the FG filters(both WL and BL). Used for debugging purposes.
int SCLogMatchFDFilter (const char *function)
Checks if there is a match for the incoming log_message with any of the FD filters.
int SCLogCheckFDFilterEntry (const char *function)
Updates a FD filter, based on whether the function that calls this function, is registered as a FD filter or not. This is called by a function only on its entry.
void SCLogCheckFDFilterExit (const char *function)
Updates a FD filter, based on whether the function that calls this function, is registered as a FD filter or not. This is called by a function only before its exit.
int SCLogAddFDFilter (const char *function)
Adds a Function-Dependent(FD) filter.
void SCLogReleaseFDFilters (void)
Releases all the FD filters added to the logging module.
int SCLogRemoveFDFilter (const char *function)
Removes a Function-Dependent(FD) filter.
int SCLogPrintFDFilters (void)
Prints the FG filters(both WL and BL). Used for debugging purposes.
void SCLogAddToFGFFileList (SCLogFGFilterFile *fgf_file, const char *file, const char *function, int line, int listtype)
Helper function used internally to add a FG filter. This function is called when the file component of the incoming filter has no entry in the filter list.
void SCLogAddToFGFFuncList (SCLogFGFilterFile *fgf_file, SCLogFGFilterFunc *fgf_func, const char *function, int line)
Helper function used internally to add a FG filter. This function is called when the file component of the incoming filter has an entry in the filter list, but the function component doesn't have an entry for the corresponding file component.
void SCLogAddToFGFLineList (SCLogFGFilterFunc *fgf_func, SCLogFGFilterLine *fgf_line, int line)
Helper function used internally to add a FG filter. This function is called when the file and function components of the incoming filter have an entry in the filter list, but the line component doesn't have an entry for the corresponding function component.
void SCLogReleaseFDFilter (SCLogFDFilter *fdf)
Releases the memory alloted to a FD filter.
Variables
int sc_log_module_initialized
Used to indicate whether the logging module has been init or not.
int sc_log_module_cleaned
Used to indicate whether the logging module has been cleaned or not.
int sc_log_fg_filters_present = 0
int sc_log_fd_filters_present = 0
SCLogFGFilterFile * sc_log_fg_filters [SC_LOG_FILTER_MAX] = { NULL, NULL }
Holds the fine-grained filters.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Debug filter utility functions
Definition in file util-debug-filters.c.
Function Documentation
int SCLogAddFDFilter (const char * function)
Adds a Function-Dependent(FD) filter.
Parameters
Name of the function for which a FD filter has to be registered
Return values
0 on success
-1 on failure
Definition at line 662 of file util-debug-filters.c.
References SCLogFDFilter_::func, SCLogFDFilter_::next, sc_log_fd_filters_present, sc_log_module_initialized, SCMalloc, SCMutexLock, SCMutexUnlock, and SCStrdup.
int SCLogAddFGFilter (const char * file, const char * function, int line, int listtype)
Helper function used internally to add a FG filter.
Parameters
file File_name of the filter
function Function_name of the filter
line Line number of the filter
listtype The filter listtype. Can be either a blacklist or whitelist filter listtype(SC_LOG_FILTER_BL or SC_LOG_FILTER_WL)
Return values
0 on successfully adding the filter;
-1 on failure
Definition at line 81 of file util-debug-filters.c.
References SCLogFGFilterFile_::file, SCLogFGFilterFunc_::func, SCLogFGFilterFile_::func, SCLogFGFilterLine_::line, SCLogFGFilterFunc_::line, m, SCLogFGFilterLine_::next, SCLogFGFilterFunc_::next, SCLogFGFilterFile_::next, sc_log_fg_filters_present, sc_log_module_initialized, SCLogAddToFGFFileList(), SCLogAddToFGFFuncList(), SCLogAddToFGFLineList(), SCMutex, SCMutexLock, and SCMutexUnlock.
Referenced by SCLogAddFGFilterBL(), and SCLogAddFGFilterWL().
int SCLogAddFGFilterBL (const char * file, const char * function, int line)
Adds a Blacklist(BL) fine-grained(FG) filter. A FG filter BL filter allows messages that don't match this filter, to be logged, while the filter is defined using a file_name, function_name and line_number.
   If a particular paramter in the fg-filter(file, function and line),
   shouldn't be considered while logging the message, one can supply
   NULL for the file_name or function_name and a negative line_no.
Parameters
file File_name of the filter
function Function_name of the filter
line Line number of the filter
Return values
0 on successfully adding the filter
-1 on failure
Definition at line 351 of file util-debug-filters.c.
References SC_LOG_FILTER_BL, and SCLogAddFGFilter().
int SCLogAddFGFilterWL (const char * file, const char * function, int line)
Adds a Whitelist(WL) fine-grained(FG) filter. A FG filter WL filter allows messages that match this filter, to be logged, while the filter is defined using a file_name, function_name and line_number.
   If a particular paramter in the fg-filter(file, function and line),
   shouldn't be considered while logging the message, one can supply
   NULL for the file_name or function_name and a negative line_no.
Parameters
file File_name of the filter
function Function_name of the filter
line Line number of the filter
Return values
0 on successfully adding the filter;
-1 on failure
Definition at line 330 of file util-debug-filters.c.
References SC_LOG_FILTER_WL, and SCLogAddFGFilter().
void SCLogAddToFGFFileList (SCLogFGFilterFile * fgf_file, const char * file, const char * function, int line, int listtype)
Helper function used internally to add a FG filter. This function is called when the file component of the incoming filter has no entry in the filter list.
Parameters
fgf_file The file component(basically the position in the list) from the filter list, after which the new filter has to be added
file File_name of the filter
function Function_name of the filter
line Line number of the filter
listtype The filter listtype. Can be either a blacklist or whitelist filter listtype(SC_LOG_FILTER_BL or SC_LOG_FILTER_WL)
Definition at line 855 of file util-debug-filters.c.
References SCLogFGFilterFile_::file, SCLogFGFilterFunc_::func, SCLogFGFilterFile_::func, SCLogFGFilterLine_::line, SCLogFGFilterFunc_::line, SCLogFGFilterFile_::next, SC_ERR_FATAL, SCLogError, SCMalloc, and SCStrdup.
Referenced by SCLogAddFGFilter().
void SCLogAddToFGFFuncList (SCLogFGFilterFile * fgf_file, SCLogFGFilterFunc * fgf_func, const char * function, int line)
Helper function used internally to add a FG filter. This function is called when the file component of the incoming filter has an entry in the filter list, but the function component doesn't have an entry for the corresponding file component.
Parameters
fgf_file The file component from the filter list to which the new filter has to be added
fgf_func The function component(basically the position in the list), from the filter list, after which the new filter has to be added
function Function_name of the filter
line Line number of the filter
Definition at line 921 of file util-debug-filters.c.
References SCLogFGFilterFunc_::func, SCLogFGFilterFile_::func, SCLogFGFilterLine_::line, SCLogFGFilterFunc_::line, SCLogFGFilterFunc_::next, SC_ERR_FATAL, SCLogError, SCMalloc, and SCStrdup.
Referenced by SCLogAddFGFilter().
void SCLogAddToFGFLineList (SCLogFGFilterFunc * fgf_func, SCLogFGFilterLine * fgf_line, int line)
Helper function used internally to add a FG filter. This function is called when the file and function components of the incoming filter have an entry in the filter list, but the line component doesn't have an entry for the corresponding function component.
Parameters
fgf_func The function component from the filter list to which the new filter has to be added
fgf_line The function component(basically the position in the list), from the filter list, after which the new filter has to be added
line Line number of the filter
Definition at line 971 of file util-debug-filters.c.
References SCLogFGFilterLine_::line, SCLogFGFilterFunc_::line, SCLogFGFilterLine_::next, SC_ERR_FATAL, SCLogError, and SCMalloc.
Referenced by SCLogAddFGFilter().
int SCLogCheckFDFilterEntry (const char * function)
Updates a FD filter, based on whether the function that calls this function, is registered as a FD filter or not. This is called by a function only on its entry.
Parameters
function Function_name from where the log_message originated
Return values
1 Since it is a hack to get things working inside the macros
Definition at line 529 of file util-debug-filters.c.
References SCLogFDFilterThreadList_::entered, SCLogFDFilter_::func, SCLogFDFilterThreadList_::next, SCLogFDFilter_::next, sc_log_module_initialized, SCMalloc, SCMutexLock, SCMutexUnlock, and SCLogFDFilterThreadList_::t.
void SCLogCheckFDFilterExit (const char * function)
Updates a FD filter, based on whether the function that calls this function, is registered as a FD filter or not. This is called by a function only before its exit.
Parameters
function Function_name from where the log_message originated
Definition at line 603 of file util-debug-filters.c.
References SCLogFDFilterThreadList_::entered, SCLogFDFilter_::func, SCLogFDFilterThreadList_::next, SCLogFDFilter_::next, sc_log_module_initialized, SCMutexLock, SCMutexUnlock, and SCLogFDFilterThreadList_::t.
int SCLogMatchFDFilter (const char * function)
Checks if there is a match for the incoming log_message with any of the FD filters.
Parameters
function Function_name from where the log_message originated
Return values
1 if there is a match
0 on no match;
Definition at line 476 of file util-debug-filters.c.
References SCLogFDFilterThreadList_::entered, SCLogFDFilterThreadList_::next, sc_log_module_initialized, SCMutexLock, SCMutexUnlock, and SCLogFDFilterThreadList_::t.
int SCLogMatchFGFilterBL (const char * file, const char * function, int line)
Checks if there is a match for the incoming log_message with any of the FG filters. If there is a match it rejects the logging for that messages, else it allows that message to be logged.
file File_name from where the log_message originated
Parameters
function Function_name from where the log_message originated
line Line number from where the log_message originated
Return values
1 if there is a match
0 on no match
-1 on failure
Definition at line 309 of file util-debug-filters.c.
References SC_LOG_FILTER_BL.
int SCLogMatchFGFilterWL (const char * file, const char * function, int line)
Checks if there is a match for the incoming log_message with any of the FG filters. If there is a match, it allows the message to be logged, else it rejects that message.
Parameters
file File_name from where the log_message originated
function Function_name from where the log_message originated
line Line number from where the log_message originated
Return values
1 if there is a match
0 on no match
-1 on failure
Definition at line 291 of file util-debug-filters.c.
References SC_LOG_FILTER_WL.
int SCLogPrintFDFilters (void)
Prints the FG filters(both WL and BL). Used for debugging purposes.
Return values
count The no of FG filters
Definition at line 811 of file util-debug-filters.c.
References SCLogFDFilter_::func, SCLogFDFilter_::next, sc_log_module_initialized, SCMutexLock, and SCMutexUnlock.
int SCLogPrintFGFilters (void)
Prints the FG filters(both WL and BL). Used for debugging purposes.
Return values
count The no of FG filters
Definition at line 408 of file util-debug-filters.c.
References SCLogFGFilterFile_::file, SCLogFGFilterFunc_::func, SCLogFGFilterFile_::func, SCLogFGFilterLine_::line, SCLogFGFilterFunc_::line, SCLogFGFilterLine_::next, SCLogFGFilterFunc_::next, SCLogFGFilterFile_::next, SC_LOG_FILTER_MAX, sc_log_module_initialized, SCMutexLock, and SCMutexUnlock.
void SCLogReleaseFDFilter (SCLogFDFilter * fdf)
Releases the memory alloted to a FD filter.
Parameters
Pointer to the FD filter that has to be freed
Definition at line 999 of file util-debug-filters.c.
References SCLogFDFilter_::func, and SCFree.
Referenced by SCLogReleaseFDFilters(), and SCLogRemoveFDFilter().
void SCLogReleaseFDFilters (void)
Releases all the FD filters added to the logging module.
Definition at line 722 of file util-debug-filters.c.
References SCLogFDFilter_::next, SCLogReleaseFDFilter(), SCMutexLock, and SCMutexUnlock.
Referenced by SCLogDeInitLogModule().
void SCLogReleaseFGFilters (void)
Definition at line 356 of file util-debug-filters.c.
References SCLogFGFilterFile_::file, SCLogFGFilterFunc_::func, SCLogFGFilterFile_::func, SCLogFGFilterFunc_::line, SCLogFGFilterLine_::next, SCLogFGFilterFunc_::next, SCLogFGFilterFile_::next, SC_LOG_FILTER_MAX, SCFree, SCMutexLock, and SCMutexUnlock.
Referenced by SCLogDeInitLogModule().
int SCLogRemoveFDFilter (const char * function)
Removes a Function-Dependent(FD) filter.
Parameters
Name of the function for which a FD filter has to be unregistered
Return values
0 on success(the filter was removed or the filter was not present)
-1 on failure/error
Definition at line 751 of file util-debug-filters.c.
References SCLogFDFilter_::func, SCLogFDFilter_::next, sc_log_fd_filters_present, sc_log_module_initialized, SCLogReleaseFDFilter(), SCMutexLock, and SCMutexUnlock.
Variable Documentation
int sc_log_fd_filters_present = 0
Definition at line 36 of file util-debug-filters.c.
Referenced by SCLogAddFDFilter(), and SCLogRemoveFDFilter().
SCLogFGFilterFile* sc_log_fg_filters[SC_LOG_FILTER_MAX] = { NULL, NULL }
Holds the fine-grained filters.
Definition at line 41 of file util-debug-filters.c.
int sc_log_fg_filters_present = 0
Definition at line 33 of file util-debug-filters.c.
Referenced by SCLogAddFGFilter().
int sc_log_module_cleaned
Used to indicate whether the logging module has been cleaned or not.
Definition at line 100 of file util-debug.c.
Referenced by SCLogDeInitLogModule(), and SCLogInitLogModule().
int sc_log_module_initialized
Used to indicate whether the logging module has been init or not.
Definition at line 95 of file util-debug.c.
Referenced by SCLogAddFDFilter(), SCLogAddFGFilter(), SCLogCheckFDFilterEntry(), SCLogCheckFDFilterExit(), SCLogDeInitLogModule(), SCLogInitLogModule(), SCLogMatchFDFilter(), SCLogMessage(), SCLogPrintFDFilters(), SCLogPrintFGFilters(), and SCLogRemoveFDFilter().