suricata: src/util-classification-config.h File Reference
util-classification-config.h File Reference
Data Structures
struct SCClassConfClasstype_
Container for a Classtype from the Classification.config file.
Typedefs
typedef struct
SCClassConfClasstype_ SCClassConfClasstype
Container for a Classtype from the Classification.config file.
Functions
SCClassConfClasstype * SCClassConfAllocClasstype (uint8_t, const char *, const char *, int)
Returns a new SCClassConfClasstype instance. The classtype string is converted into lowercase, before being assigned to the instance.
void SCClassConfDeAllocClasstype (SCClassConfClasstype *)
Frees a SCClassConfClasstype instance.
void SCClassConfLoadClassficationConfigFile (DetectEngineCtx *, FILE *fd)
Loads the Classtype info from the classification.config file.
SCClassConfClasstype * SCClassConfGetClasstype (const char *, DetectEngineCtx *)
Gets the classtype from the corresponding hash table stored in the Detection Engine Context's class conf ht, given the classtype name.
void SCClassConfDeInitContext (DetectEngineCtx *)
Releases resources used by the Classification Config API.
void SCClassConfRegisterTests (void)
This function registers unit tests for Classification Config API.
FILE * SCClassConfGenerateValidDummyClassConfigFD01 (void)
FILE * SCClassConfGenerateInValidDummyClassConfigFD02 (void)
FILE * SCClassConfGenerateInValidDummyClassConfigFD03 (void)
void SCClassConfInit (void)
void SCClassConfDeinit (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-classification-config.h.
Typedef Documentation
typedef struct SCClassConfClasstype_ SCClassConfClasstype
Container for a Classtype from the Classification.config file.
Function Documentation
SCClassConfClasstype* SCClassConfAllocClasstype (uint8_t classtype_id, const char * classtype, const char * classtype_desc, int priority)
Returns a new SCClassConfClasstype instance. The classtype string is converted into lowercase, before being assigned to the instance.
Parameters
classtype Pointer to the classification type.
classtype_desc Pointer to the classification type description.
priority Holds the priority for the classification type.
Return values
ct Pointer to the new instance of SCClassConfClasstype on success; NULL on failure.
Definition at line 387 of file util-classification-config.c.
References SCClassConfClasstype_::classtype, SCClassConfClasstype_::classtype_desc, SCClassConfClasstype_::classtype_id, SCClassConfClasstype_::priority, SC_ERR_MEM_ALLOC, SCClassConfDeAllocClasstype(), SCLogError, SCMalloc, and SCStrdup.
Referenced by SCClassConfAddClasstype().
void SCClassConfDeAllocClasstype (SCClassConfClasstype * ct)
Frees a SCClassConfClasstype instance.
Parameters
Pointer to the SCClassConfClasstype instance that has to be freed
Definition at line 427 of file util-classification-config.c.
References SCClassConfClasstype_::classtype, SCClassConfClasstype_::classtype_desc, and SCFree.
Referenced by SCClassConfAllocClasstype(), and SCClassConfClasstypeHashFree().
void SCClassConfDeinit (void)
Definition at line 82 of file util-classification-config.c.
Referenced by main().
void SCClassConfDeInitContext (DetectEngineCtx *)
Releases resources used by the Classification Config API.
Definition at line 202 of file util-classification-config.c.
References DetectEngineCtx_::class_conf_ht, and HashTableFree().
Referenced by DetectEngineCtxFree().
FILE* SCClassConfGenerateInValidDummyClassConfigFD02 (void)
FILE* SCClassConfGenerateInValidDummyClassConfigFD03 (void)
FILE* SCClassConfGenerateValidDummyClassConfigFD01 (void)
SCClassConfClasstype* SCClassConfGetClasstype (const char * ct_name, DetectEngineCtx * de_ctx)
Gets the classtype from the corresponding hash table stored in the Detection Engine Context's class conf ht, given the classtype name.
Parameters
ct_name Pointer to the classtype name that has to be looked up.
de_ctx Pointer to the Detection Engine Context.
Return values
lookup_ct_info Pointer to the SCClassConfClasstype instance from the hash table on success; NULL on failure.
Definition at line 562 of file util-classification-config.c.
References DetectEngineCtx_::class_conf_ht, and HashTableLookup().
void SCClassConfInit (void)
Definition at line 59 of file util-classification-config.c.
References DETECT_CLASSCONFIG_REGEX, and SCLogDebug.
Referenced by main(), and RunUnittests().
void SCClassConfLoadClassficationConfigFile (DetectEngineCtx * de_ctx, FILE * fd)
Loads the Classtype info from the classification.config file.
   The classification.config file contains the different classtypes,
   that can be used to label Signatures.  Each line of the file should
   have the following format -
   classtype_name, classtype_description, priority
   None of the above parameters should hold a quote inside the file.
Parameters
de_ctx Pointer to the Detection Engine Context that should be updated with Classtype information.
Definition at line 531 of file util-classification-config.c.
References RunmodeIsUnittests(), SC_ERR_OPENING_FILE, SCClassConfInitContextAndLocalResources(), SCClassConfParseFile(), and SCLogError.
void SCClassConfRegisterTests (void)
This function registers unit tests for Classification Config API.
Definition at line 825 of file util-classification-config.c.
Referenced by RunUnittests().