suricata: src/util-radix-tree.h File Reference
util-radix-tree.h File Reference
Data Structures
struct SCRadixUserData_
Structure that hold the user data and the netmask associated with it.
struct SCRadixPrefix_
Structure for the prefix/key in the radix tree.
struct SCRadixNode_
Structure for the node in the radix tree.
struct SCRadixTree_
Structure for the radix tree.
Macros
#define SC_RADIX_BITTEST(x, y) ((x) & (y))
Typedefs
typedef struct SCRadixUserData_ SCRadixUserData
Structure that hold the user data and the netmask associated with it.
typedef struct SCRadixPrefix_ SCRadixPrefix
Structure for the prefix/key in the radix tree.
typedef struct SCRadixNode_ SCRadixNode
Structure for the node in the radix tree.
typedef struct SCRadixTree_ SCRadixTree
Structure for the radix tree.
Functions
struct in_addr * SCRadixValidateIPV4Address (const char *)
struct in6_addr * SCRadixValidateIPV6Address (const char *)
void SCRadixChopIPAddressAgainstNetmask (uint8_t *, uint8_t, uint16_t)
SCRadixTree * SCRadixCreateRadixTree (void(*Free)(void *), void(*PrintData)(void *))
Creates a new Radix tree.
void SCRadixReleaseRadixTree (SCRadixTree *)
Frees a Radix tree and all its nodes.
SCRadixNode * SCRadixAddKeyGeneric (uint8_t *, uint16_t, SCRadixTree *, void *)
Adds a new generic key to the Radix tree.
SCRadixNode * SCRadixAddKeyIPV4 (uint8_t *, SCRadixTree *, void *)
Adds a new IPV4 address to the Radix tree.
SCRadixNode * SCRadixAddKeyIPV6 (uint8_t *, SCRadixTree *, void *)
Adds a new IPV6 address to the Radix tree.
SCRadixNode * SCRadixAddKeyIPV4Netblock (uint8_t *, SCRadixTree *, void *, uint8_t)
Adds a new IPV4 netblock to the Radix tree.
SCRadixNode * SCRadixAddKeyIPV6Netblock (uint8_t *, SCRadixTree *, void *, uint8_t)
Adds a new IPV6 netblock to the Radix tree.
SCRadixNode * SCRadixAddKeyIPV4String (const char *, SCRadixTree *, void *)
Adds a new IPV4/netblock to the Radix tree from a string.
SCRadixNode * SCRadixAddKeyIPV6String (const char *, SCRadixTree *, void *)
Adds a new IPV6/netblock to the Radix tree from a string.
void SCRadixRemoveKeyGeneric (uint8_t *, uint16_t, SCRadixTree *)
Removes a key from the Radix tree.
void SCRadixRemoveKeyIPV4Netblock (uint8_t *, SCRadixTree *, uint8_t)
Removes an IPV4 address netblock key from the Radix tree.
void SCRadixRemoveKeyIPV4 (uint8_t *, SCRadixTree *)
Removes an IPV4 address key(not a netblock) from the Radix tree. Instead of using this function, we can also used SCRadixRemoveKeyIPV4Netblock(), by supplying a netmask value of 32.
void SCRadixRemoveKeyIPV6Netblock (uint8_t *, SCRadixTree *, uint8_t)
Removes an IPV6 netblock address key from the Radix tree.
void SCRadixRemoveKeyIPV6 (uint8_t *, SCRadixTree *)
Removes an IPV6 address key(not a netblock) from the Radix tree. Instead of using this function, we can also used SCRadixRemoveKeyIPV6Netblock(), by supplying a netmask value of 128.
SCRadixNode * SCRadixFindKeyGeneric (uint8_t *, uint16_t, SCRadixTree *, void **)
Checks if a key is present in the tree.
SCRadixNode * SCRadixFindKeyIPV4ExactMatch (uint8_t *, SCRadixTree *, void **)
Checks if an IPV4 address is present in the tree.
SCRadixNode * SCRadixFindKeyIPV4Netblock (uint8_t *, SCRadixTree *, uint8_t, void **)
Checks if an IPV4 Netblock address is present in the tree.
SCRadixNode * SCRadixFindKeyIPV4BestMatch (uint8_t *, SCRadixTree *, void **)
Checks if an IPV4 address is present in the tree under a netblock.
SCRadixNode * SCRadixFindKeyIPV6ExactMatch (uint8_t *, SCRadixTree *, void **)
Checks if an IPV6 address is present in the tree.
SCRadixNode * SCRadixFindKeyIPV6Netblock (uint8_t *, SCRadixTree *, uint8_t, void **)
Checks if an IPV6 Netblock address is present in the tree.
SCRadixNode * SCRadixFindKeyIPV6BestMatch (uint8_t *, SCRadixTree *, void **)
Checks if an IPV6 address is present in the tree under a netblock.
void SCRadixPrintTree (SCRadixTree *)
Prints the Radix Tree. While printing the radix tree we use the following format.
void SCRadixPrintNodeInfo (SCRadixNode *, int, void(*PrintData)(void *))
Prints the node information from a Radix tree.
void SCRadixRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-radix-tree.h.
Macro Definition Documentation
#define SC_RADIX_BITTEST (x, y) ((x) & (y))
Definition at line 27 of file util-radix-tree.h.
Typedef Documentation
typedef struct SCRadixNode_ SCRadixNode
Structure for the node in the radix tree.
typedef struct SCRadixPrefix_ SCRadixPrefix
Structure for the prefix/key in the radix tree.
typedef struct SCRadixTree_ SCRadixTree
Structure for the radix tree.
typedef struct SCRadixUserData_ SCRadixUserData
Structure that hold the user data and the netmask associated with it.
Function Documentation
SCRadixNode* SCRadixAddKeyGeneric (uint8_t * key_stream, uint16_t key_bitlen, SCRadixTree * tree, void * user)
Adds a new generic key to the Radix tree.
Parameters
key_stream Data that has to be added to the Radix tree
key_bitlen The bitlen of the the above stream. For example if the stream is the string "abcd", the bitlen would be 32
tree Pointer to the Radix tree
user Pointer to the user data that has to be associated with the key
Return values
node Pointer to the newly created node
Definition at line 836 of file util-radix-tree.c.
SCRadixNode* SCRadixAddKeyIPV4 (uint8_t * key_stream, SCRadixTree * tree, void * user)
Adds a new IPV4 address to the Radix tree.
Parameters
key_stream Data that has to be added to the Radix tree. In this case a pointer to an IPV4 address
tree Pointer to the Radix tree
user Pointer to the user data that has to be associated with the key
Return values
node Pointer to the newly created node
Definition at line 855 of file util-radix-tree.c.
Referenced by IPOnlyPrepare(), SCHInfoAddHostOSInfo(), SCReputationAddIPV4Data(), and SCReputationUpdateIPV4Data().
SCRadixNode* SCRadixAddKeyIPV4Netblock (uint8_t * key_stream, SCRadixTree * tree, void * user, uint8_t netmask)
Adds a new IPV4 netblock to the Radix tree.
Parameters
key_stream Data that has to be added to the Radix tree. In this case a pointer to an IPV4 netblock
tree Pointer to the Radix tree
user Pointer to the user data that has to be associated with the key
netmask The netmask (cidr) if we are adding a netblock
Return values
node Pointer to the newly created node
Definition at line 894 of file util-radix-tree.c.
Referenced by IPOnlyPrepare(), SCHInfoAddHostOSInfo(), and SCReputationAddIPV4Data().
SCRadixNode* SCRadixAddKeyIPV4String (const char * str, SCRadixTree * tree, void * user)
Adds a new IPV4/netblock to the Radix tree from a string.
Parameters
str IPV4 string with optional /cidr netmask
tree Pointer to the Radix tree
user Pointer to the user data that has to be associated with the key
Return values
node Pointer to the newly created node
Definition at line 932 of file util-radix-tree.c.
References inet_pton(), and strlcpy().
SCRadixNode* SCRadixAddKeyIPV6 (uint8_t * key_stream, SCRadixTree * tree, void * user)
Adds a new IPV6 address to the Radix tree.
Parameters
key_stream Data that has to be added to the Radix tree. In this case the pointer to an IPV6 address
tree Pointer to the Radix tree
user Pointer to the user data that has to be associated with the key
Return values
node Pointer to the newly created node
Definition at line 874 of file util-radix-tree.c.
Referenced by IPOnlyPrepare(), SCHInfoAddHostOSInfo(), SCReputationAddIPV6Data(), and SCReputationUpdateIPV6Data().
SCRadixNode* SCRadixAddKeyIPV6Netblock (uint8_t * key_stream, SCRadixTree * tree, void * user, uint8_t netmask)
Adds a new IPV6 netblock to the Radix tree.
Parameters
key_stream Data that has to be added to the Radix tree. In this case a pointer to an IPV6 netblock
tree Pointer to the Radix tree
user Pointer to the user data that has to be associated with the key
netmask The netmask (cidr) if we are adding a netblock
Return values
node Pointer to the newly created node
Definition at line 914 of file util-radix-tree.c.
Referenced by IPOnlyPrepare(), SCHInfoAddHostOSInfo(), and SCReputationAddIPV6Data().
SCRadixNode* SCRadixAddKeyIPV6String (const char * str, SCRadixTree * tree, void * user)
Adds a new IPV6/netblock to the Radix tree from a string.
Parameters
str IPV6 string with optional /cidr netmask
tree Pointer to the Radix tree
user Pointer to the user data that has to be associated with the key
Return values
node Pointer to the newly created node
Definition at line 981 of file util-radix-tree.c.
References inet_pton(), and strlcpy().
void SCRadixChopIPAddressAgainstNetmask (uint8_t * , uint8_t , uint16_t)
SCRadixTree* SCRadixCreateRadixTree (void(*)(void *) Free, void(*)(void *) PrintData)
Creates a new Radix tree.
Parameters
Free Function pointer supplied by the user to be used by the Radix cleanup API to free the user suppplied data
Return values
tree The newly created radix tree on success
(all radix trees should be created at init)
Definition at line 426 of file util-radix-tree.c.
References SCRadixTree_::Free, SCRadixTree_::PrintData, SC_ERR_FATAL, SCLogError, and SCMalloc.
Referenced by DefragPolicyLoadFromConfig(), HTPConfigure(), IPOnlyInit(), SCHInfoAddHostOSInfo(), and SCReputationInitCtx().
SCRadixNode* SCRadixFindKeyGeneric (uint8_t * key_stream, uint16_t key_bitlen, SCRadixTree * tree, void ** user_data_result)
Checks if a key is present in the tree.
Parameters
key_stream Data that has to be found in the Radix tree
key_bitlen The bitlen of the the above stream.
tree Pointer to the Radix tree instance
Definition at line 1461 of file util-radix-tree.c.
SCRadixNode* SCRadixFindKeyIPV4BestMatch (uint8_t * key_stream, SCRadixTree * tree, void ** user_data_result)
Checks if an IPV4 address is present in the tree under a netblock.
Parameters
key_stream Data that has to be found in the Radix tree. In this case an IPV4 address
tree Pointer to the Radix tree instance
Definition at line 1486 of file util-radix-tree.c.
Referenced by IPOnlyMatchPacket(), IPOnlyPrepare(), SCHInfoGetHostOSFlavour(), SCHInfoGetIPv4HostOSFlavour(), SCReputationLookupIPV4BestMatch(), and SCReputationLookupIPV4BestMatchReal().
SCRadixNode* SCRadixFindKeyIPV4ExactMatch (uint8_t * key_stream, SCRadixTree * tree, void ** user_data_result)
Checks if an IPV4 address is present in the tree.
Parameters
key_stream Data that has to be found in the Radix tree. In this case an IPV4 address
tree Pointer to the Radix tree instance
Definition at line 1474 of file util-radix-tree.c.
Referenced by IPOnlyPrepare(), SCReputationLookupIPV4ExactMatch(), and SCReputationLookupIPV4ExactMatchReal().
SCRadixNode* SCRadixFindKeyIPV4Netblock (uint8_t * key_stream, SCRadixTree * tree, uint8_t netmask, void ** user_data_result)
Checks if an IPV4 Netblock address is present in the tree.
Parameters
key_stream Data that has to be found in the Radix tree. In this case an IPV4 netblock address
tree Pointer to the Radix tree instance
Definition at line 1498 of file util-radix-tree.c.
References SCRadixNode_::prefix.
Referenced by IPOnlyPrepare().
SCRadixNode* SCRadixFindKeyIPV6BestMatch (uint8_t * key_stream, SCRadixTree * tree, void ** user_data_result)
Checks if an IPV6 address is present in the tree under a netblock.
Parameters
key_stream Data that has to be found in the Radix tree. In this case an IPV6 address
tree Pointer to the Radix tree instance
Definition at line 1552 of file util-radix-tree.c.
Referenced by IPOnlyMatchPacket(), IPOnlyPrepare(), SCHInfoGetHostOSFlavour(), SCHInfoGetIPv6HostOSFlavour(), SCReputationLookupIPV6BestMatch(), and SCReputationLookupIPV6BestMatchReal().
SCRadixNode* SCRadixFindKeyIPV6ExactMatch (uint8_t * key_stream, SCRadixTree * tree, void ** user_data_result)
Checks if an IPV6 address is present in the tree.
Parameters
key_stream Data that has to be found in the Radix tree. In this case an IPV6 address
tree Pointer to the Radix tree instance
Definition at line 1540 of file util-radix-tree.c.
Referenced by IPOnlyPrepare(), SCReputationLookupIPV6ExactMatch(), and SCReputationLookupIPV6ExactMatchReal().
SCRadixNode* SCRadixFindKeyIPV6Netblock (uint8_t * key_stream, SCRadixTree * tree, uint8_t netmask, void ** user_data_result)
Checks if an IPV6 Netblock address is present in the tree.
Parameters
key_stream Data that has to be found in the Radix tree. In this case an IPV6 netblock address
tree Pointer to the Radix tree instance
Definition at line 1519 of file util-radix-tree.c.
References SCRadixNode_::prefix.
Referenced by IPOnlyPrepare().
void SCRadixPrintNodeInfo (SCRadixNode * node, int level, void(*)(void *) PrintData)
Prints the node information from a Radix tree.
Parameters
node Pointer to the Radix node whose information has to be printed
level Used for indentation purposes
Definition at line 1563 of file util-radix-tree.c.
References SCRadixNode_::bit, SCRadixPrefix_::bitlen, SCRadixUserData_::netmask, SCRadixNode_::netmask_cnt, SCRadixNode_::netmasks, SCRadixUserData_::next, SCRadixNode_::prefix, SCRadixPrefix_::stream, SCRadixUserData_::user, and SCRadixPrefix_::user_data.
void SCRadixPrintTree (SCRadixTree * tree)
Prints the Radix Tree. While printing the radix tree we use the following format.
   Parent_0
       Left_Child_1
           Left_Child_2
           Right_Child_2
       Right_Child_1
           Left_Child_2
           Right_Child_2     and so on
   Each node printed out holds details on the next bit that differs
   amongst its children, and if the node holds a prefix, the perfix is
   printed as well.
Parameters
tree Pointer to the Radix tree that has to be printed
Definition at line 1648 of file util-radix-tree.c.
References SCRadixTree_::head, and SCRadixTree_::PrintData.
void SCRadixRegisterTests (void)
Definition at line 4175 of file util-radix-tree.c.
Referenced by RunUnittests().
void SCRadixReleaseRadixTree (SCRadixTree * tree)
Frees a Radix tree and all its nodes.
Parameters
tree Pointer to the Radix tree that has to be freed
Definition at line 465 of file util-radix-tree.c.
References SCRadixTree_::head, and SCFree.
Referenced by HTPFreeConfig(), IPOnlyDeinit(), SCHInfoCleanResources(), SCReputationFreeCtx(), and SRepDestroy().
void SCRadixRemoveKeyGeneric (uint8_t * key_stream, uint16_t key_bitlen, SCRadixTree * tree)
Removes a key from the Radix tree.
Parameters
key_stream Data that has to be removed from the Radix tree
key_bitlen The bitlen of the the above stream.
tree Pointer to the Radix tree from which the key has to be removed
Definition at line 1254 of file util-radix-tree.c.
void SCRadixRemoveKeyIPV4 (uint8_t * key_stream, SCRadixTree * tree)
Removes an IPV4 address key(not a netblock) from the Radix tree. Instead of using this function, we can also used SCRadixRemoveKeyIPV4Netblock(), by supplying a netmask value of 32.
Parameters
key_stream Data that has to be removed from the Radix tree. In this case an IPV4 address
tree Pointer to the Radix tree from which the key has to be removed
Definition at line 1286 of file util-radix-tree.c.
void SCRadixRemoveKeyIPV4Netblock (uint8_t * key_stream, SCRadixTree * tree, uint8_t netmask)
Removes an IPV4 address netblock key from the Radix tree.
Parameters
key_stream Data that has to be removed from the Radix tree. In this case an IPV4 address
tree Pointer to the Radix tree from which the key has to be removed
Definition at line 1269 of file util-radix-tree.c.
Referenced by SCReputationRemoveIPV4Data().
void SCRadixRemoveKeyIPV6 (uint8_t * key_stream, SCRadixTree * tree)
Removes an IPV6 address key(not a netblock) from the Radix tree. Instead of using this function, we can also used SCRadixRemoveKeyIPV6Netblock(), by supplying a netmask value of 128.
Parameters
key_stream Data that has to be removed from the Radix tree. In this case an IPV6 address
tree Pointer to the Radix tree from which the key has to be removed
Definition at line 1317 of file util-radix-tree.c.
void SCRadixRemoveKeyIPV6Netblock (uint8_t * key_stream, SCRadixTree * tree, uint8_t netmask)
Removes an IPV6 netblock address key from the Radix tree.
Parameters
key_stream Data that has to be removed from the Radix tree. In this case an IPV6 address
tree Pointer to the Radix tree from which the key has to be removed
Definition at line 1300 of file util-radix-tree.c.
Referenced by SCReputationRemoveIPV6Data().
struct in_addr* SCRadixValidateIPV4Address (const char *)
struct in6_addr* SCRadixValidateIPV6Address (const char *)