suricata: src/util-path.c File Reference
util-path.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "debug.h"
#include "util-debug.h"
Functions
int PathIsAbsolute (const char *path)
Check if a path is absolute.
int PathIsRelative (const char *path)
Check if a path is relative.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-path.c.
Function Documentation
int PathIsAbsolute (const char * path)
Check if a path is absolute.
Parameters
path string with the path
Return values
1 absolute
0 not absolute
Definition at line 38 of file util-path.c.
Referenced by PathIsRelative(), and SCConfLogOpenGeneric().
int PathIsRelative (const char * path)
Check if a path is relative.
Parameters
path string with the path
Return values
1 relative
0 not relative
Definition at line 63 of file util-path.c.
References PathIsAbsolute().
Referenced by ConfLoadCompleteIncludePath(), and DetectLoadCompleteSigPath().