suricata: src/util-mpm-wumanber.h File Reference
util-mpm-wumanber.h File Reference
#include "util-mpm.h"
#include "util-bloomfilter.h"
Data Structures
struct WmPattern_
struct WmHashItem_
struct WmCtx_
struct WmThreadCtx_
Typedefs
typedef struct WmPattern_ WmPattern
typedef struct WmHashItem_ WmHashItem
typedef struct WmCtx_ WmCtx
typedef struct WmThreadCtx_ WmThreadCtx
Functions
void MpmWuManberRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-mpm-wumanber.h.
Typedef Documentation
typedef struct WmCtx_ WmCtx
typedef struct WmHashItem_ WmHashItem
typedef struct WmPattern_ WmPattern
typedef struct WmThreadCtx_ WmThreadCtx
Function Documentation
void MpmWuManberRegister (void)
Definition at line 1526 of file util-mpm-wumanber.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, mpm_table, MPM_WUMANBER, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, MpmTableElmt_::Search, WmAddPatternCI(), WmAddPatternCS(), WmDestroyCtx(), WmInitCtx(), WmPreparePatterns(), WmPrintInfo(), WmPrintSearchStats(), WmRegisterTests(), WmSearch(), WmThreadDestroyCtx(), and WmThreadInitCtx().
Referenced by MpmTableSetup().