suricata: src/util-magic.c File Reference
util-magic.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "util-unittest.h"
#include <magic.h>
Functions
int MagicInit (void)
Initialize the "magic" context.
char * MagicGlobalLookup (uint8_t *buf, uint32_t buflen)
Find the magic value for a buffer.
char * MagicThreadLookup (magic_t *ctx, uint8_t *buf, uint32_t buflen)
Find the magic value for a buffer.
void MagicDeinit (void)
void MagicRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Wrappers and tests for libmagic usage.
Libmagic's API is not thread safe. The data the pointer returned by magic_buffer is overwritten by the next magic_buffer call. This is why we need to lock calls and copy the returned string.
Definition in file util-magic.c.
Function Documentation
void MagicDeinit (void)
Definition at line 144 of file util-magic.c.
References SCMutexDestroy, SCMutexLock, and SCMutexUnlock.
Referenced by main().
char* MagicGlobalLookup (uint8_t * buf, uint32_t buflen)
Find the magic value for a buffer.
Parameters
buf the buffer
buflen length of the buffer
Return values
result pointer to null terminated string
Definition at line 97 of file util-magic.c.
References SC_ERR_MEM_ALLOC, SCLogError, SCMutexLock, SCMutexUnlock, SCReturnPtr, SCStrdup, and unlikely.
Referenced by FilemagicGlobalLookup().
int MagicInit (void)
Initialize the "magic" context.
Definition at line 42 of file util-magic.c.
References BUG_ON, ConfGet(), SC_ERR_FOPEN, SC_ERR_MAGIC_LOAD, SC_ERR_MAGIC_OPEN, SCEnter, SCLogError, SCLogInfo, SCLogWarning, SCMutexInit, SCMutexLock, SCMutexUnlock, and SCReturnInt.
Referenced by main().
void MagicRegisterTests (void)
Definition at line 658 of file util-magic.c.
Referenced by RunUnittests().
char* MagicThreadLookup (magic_t * ctx, uint8_t * buf, uint32_t buflen)
Find the magic value for a buffer.
Parameters
buf the buffer
buflen length of the buffer
Return values
result pointer to null terminated string
Definition at line 126 of file util-magic.c.
References SC_ERR_MEM_ALLOC, SCLogError, SCReturnPtr, SCStrdup, and unlikely.
Referenced by FilemagicThreadLookup().