suricata: src/util-print.h File Reference
util-print.h File Reference
Macros
#define PrintBufferData(buf, buf_offset_ptr, buf_size,...)
Functions
void PrintBufferRawLineHex (char *, int *, int, uint8_t *, uint32_t)
print a buffer as hex on a single line
void PrintRawUriFp (FILE *, uint8_t *, uint32_t)
void PrintRawUriBuf (char *, uint32_t *, uint32_t, uint8_t *, uint32_t)
void PrintRawJsonFp (FILE *, uint8_t *, uint32_t)
void PrintRawDataFp (FILE *, const uint8_t *, uint32_t)
void PrintRawDataToBuffer (uint8_t *dst_buf, uint32_t *dst_buf_offset_ptr, uint32_t dst_buf_size, uint8_t *src_buf, uint32_t src_buf_len)
void PrintStringsToBuffer (uint8_t *dst_buf, uint32_t *dst_buf_offset_ptr, uint32_t dst_buf_size, uint8_t *src_buf, uint32_t src_buf_len)
void PrintRawLineHexBuf (char *, uint32_t, uint8_t *, uint32_t)
print a buffer as hex on a single line in to retbuf buffer
const char * PrintInet (int, const void *, char *, socklen_t)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-print.h.
Macro Definition Documentation
#define PrintBufferData (buf, buf_offset_ptr, buf_size, ...)
Value:
do {         \
        int cw = snprintf((buf) + *(buf_offset_ptr),                    \
                          (buf_size) - *(buf_offset_ptr),                \
                          __VA_ARGS__);                                 \
        if (cw >= 0) {                                                  \
            if ( (*(buf_offset_ptr) + cw) >= buf_size) {                \
                SCLogDebug("Truncating data write since it exceeded buffer " \
                           "limit of - %"PRIu32"\n", buf_size);         \
                *(buf_offset_ptr) = buf_size - 1;                       \
            } else {                                                    \
                *(buf_offset_ptr) += cw;                                \
            }                                                           \
        }                                                               \
    } while (0)
Definition at line 29 of file util-print.h.
Referenced by AlertFastLogger(), PrintBufferRawLineHex(), PrintRawDataToBuffer(), PrintRawJsonFp(), PrintRawLineHexBuf(), PrintRawUriBuf(), PrintRawUriFp(), and PrintStringsToBuffer().
Function Documentation
void PrintBufferRawLineHex (char * nbuf, int * offset, int max_size, uint8_t * buf, uint32_t buflen)
print a buffer as hex on a single line
Prints in the format "00 AA BB"
Parameters
nbuf buffer into which the output is written
offset of where to start writting into the buffer
max_size the size of the output buffer
buf buffer to print from
buflen length of the input buffer
Definition at line 42 of file util-print.c.
References PrintBufferData.
Referenced by AlertFastLogger().
const char* PrintInet (int , const void * , char * , socklen_t)
Definition at line 260 of file util-print.c.
References inet_ntop(), SC_ERR_INVALID_VALUE, and SCLogError.
Referenced by AddressDebugPrint(), AlertFastLogger(), DecodeIPV4(), DecodeIPV6(), DecodePartialIPV4(), DecodePartialIPV6(), DetectAddressPrint(), IPOnlyPrepare(), SRepLoadFileFromFD(), and TLSGetIPInformations().
void PrintRawDataFp (FILE * , const uint8_t * , uint32_t)
Definition at line 136 of file util-print.c.
Referenced by AppLayerHandleTCPData(), DetectEngineInspectHttpRequestLine(), DetectEngineInspectPacketUris(), DNSReponseParse(), HtpBodyPrint(), HTPCallbackRequestBodyData(), HtpRequestBodyHandleMultipart(), SCAsn1Decode(), SigMatchSignatures(), and StreamTcpInlineSegmentCompare().
void PrintRawDataToBuffer (uint8_t * dst_buf, uint32_t * dst_buf_offset_ptr, uint32_t dst_buf_size, uint8_t * src_buf, uint32_t src_buf_len)
Definition at line 170 of file util-print.c.
References PrintBufferData.
void PrintRawJsonFp (FILE * , uint8_t * , uint32_t)
Definition at line 71 of file util-print.c.
References BUFFER_LENGTH, and PrintBufferData.
void PrintRawLineHexBuf (char * retbuf, uint32_t retbuflen, uint8_t * buf, uint32_t buflen)
print a buffer as hex on a single line in to retbuf buffer
Prints in the format "00 AA BB"
Parameters
retbuf pointer to the buffer which will have the result
rebuflen lenght of the buffer
buf buffer to print from
buflen length of the input buffer
Definition at line 61 of file util-print.c.
References PrintBufferData.
void PrintRawUriBuf (char * , uint32_t * , uint32_t , uint8_t * , uint32_t)
Definition at line 113 of file util-print.c.
References PrintBufferData.
void PrintRawUriFp (FILE * , uint8_t * , uint32_t)
Definition at line 93 of file util-print.c.
References BUFFER_LENGTH, and PrintBufferData.
Referenced by EngineAnalysisFP().
void PrintStringsToBuffer (uint8_t * dst_buf, uint32_t * dst_buf_offset_ptr, uint32_t dst_buf_size, uint8_t * src_buf, uint32_t src_buf_len)
Definition at line 219 of file util-print.c.
References PrintBufferData.