suricata: src/util-threshold-config.c File Reference
util-threshold-config.c File Reference
Thresholding
#include "suricata-common.h"
#include "host.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-address.h"
#include "detect-threshold.h"
#include "detect-parse.h"
#include "conf.h"
#include "util-threshold-config.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-byte.h"
#include "util-time.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-fmemopen.h"
Macros
#define MAX_SUBSTRINGS 30
#define DETECT_BASE_REGEX "^\\s*(event_filter|threshold|rate_filter|suppress)\\s*gen_id\\s*(\\d+)\\s*,\\s*sig_id\\s*(\\d+)\\s*(.*)\\s*$"
#define DETECT_THRESHOLD_REGEX "^,\\s*type\\s*(limit|both|threshold)\\s*,\\s*track\\s*(by_dst|by_src)\\s*,\\s*count\\s*(\\d+)\\s*,\\s*seconds\\s*(\\d+)\\s*$"
#define DETECT_RATE_REGEX "^,\\s*track\\s*(by_dst|by_src|by_rule)\\s*,\\s*count\\s*(\\d+)\\s*,\\s*seconds\\s*(\\d+)\\s*,\\s*new_action\\s*(alert|drop|pass|log|sdrop|reject)\\s*,\\s*timeout\\s*(\\d+)\\s*$"
#define DETECT_SUPPRESS_REGEX "^,\\s*track\\s*(by_dst|by_src|by_either)\\s*,\\s*ip\\s*([\\[\\],\\$\\da-zA-Z.:/_]+)*\\s*$"
#define THRESHOLD_CONF_DEF_CONF_FILEPATH CONFIG_DIR "/threshold.config"
enum ThresholdRuleType { THRESHOLD_TYPE_EVENT_FILTER, THRESHOLD_TYPE_THRESHOLD, THRESHOLD_TYPE_RATE, THRESHOLD_TYPE_SUPPRESS }
typedef enum ThresholdRuleType ThresholdRuleType
int SCThresholdConfInitContext (DetectEngineCtx *de_ctx, FILE *utfd)
Inits the context to be used by the Threshold Config parsing API.
void SCThresholdConfDeInitContext (DetectEngineCtx *de_ctx, FILE *fd)
Releases resources used by the Threshold Config API.
int SCThresholdConfAddThresholdtype (char *rawstr, DetectEngineCtx *de_ctx)
Parses a line from the threshold file and applies it to the detection engine.
int SCThresholdConfIsLineBlankOrComment (char *line)
Checks if a string is a comment or a blank line.
int SCThresholdConfLineIsMultiline (char *line)
Checks if the rule is multiline, by searching an ending slash.
int SCThresholdConfLineLength (FILE *fd)
Get the config line length to allocate the buffer needed.
void SCThresholdConfParseFile (DetectEngineCtx *de_ctx, FILE *fd)
Parses the Threshold Config file.
void SCThresholdConfRegisterTests (void)
This function registers unit tests for Classification Config API.
Detailed Description
Author
Breno Silva Pinto breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Todo:
Need to support suppress
Implements Threshold support
Definition in file util-threshold-config.c.
Macro Definition Documentation
#define DETECT_BASE_REGEX "^\\s*(event_filter|threshold|rate_filter|suppress)\\s*gen_id\\s*(\\d+)\\s*,\\s*sig_id\\s*(\\d+)\\s*(.*)\\s*$"
Definition at line 63 of file util-threshold-config.c.
Referenced by SCThresholdConfInitContext().
#define DETECT_RATE_REGEX "^,\\s*track\\s*(by_dst|by_src|by_rule)\\s*,\\s*count\\s*(\\d+)\\s*,\\s*seconds\\s*(\\d+)\\s*,\\s*new_action\\s*(alert|drop|pass|log|sdrop|reject)\\s*,\\s*timeout\\s*(\\d+)\\s*$"
Definition at line 68 of file util-threshold-config.c.
Referenced by SCThresholdConfInitContext().
#define DETECT_SUPPRESS_REGEX "^,\\s*track\\s*(by_dst|by_src|by_either)\\s*,\\s*ip\\s*([\\[\\],\\$\\da-zA-Z.:/_]+)*\\s*$"
Definition at line 76 of file util-threshold-config.c.
Referenced by SCThresholdConfInitContext().
#define DETECT_THRESHOLD_REGEX "^,\\s*type\\s*(limit|both|threshold)\\s*,\\s*track\\s*(by_dst|by_src)\\s*,\\s*count\\s*(\\d+)\\s*,\\s*seconds\\s*(\\d+)\\s*$"
Definition at line 65 of file util-threshold-config.c.
Referenced by SCThresholdConfInitContext().
#define MAX_SUBSTRINGS 30
#define THRESHOLD_CONF_DEF_CONF_FILEPATH CONFIG_DIR "/threshold.config"
Definition at line 82 of file util-threshold-config.c.
Typedef Documentation
typedef enum ThresholdRuleType ThresholdRuleType
Enumeration Type Documentation
enum ThresholdRuleType
Enumerator
THRESHOLD_TYPE_EVENT_FILTER
THRESHOLD_TYPE_THRESHOLD
THRESHOLD_TYPE_RATE
THRESHOLD_TYPE_SUPPRESS
Definition at line 53 of file util-threshold-config.c.
Function Documentation
int SCThresholdConfAddThresholdtype (char * rawstr, DetectEngineCtx * de_ctx)
Parses a line from the threshold file and applies it to the detection engine.
Parameters
rawstr Pointer to the string to be parsed.
de_ctx Pointer to the Detection Engine Context.
Return values
0 On success.
-1 On failure.
Definition at line 1003 of file util-threshold-config.c.
References SCFree, and TYPE_SUPPRESS.
Referenced by SCThresholdConfParseFile().
void SCThresholdConfDeInitContext (DetectEngineCtx * de_ctx, FILE * fd)
Releases resources used by the Threshold Config API.
Parameters
de_ctx Pointer to the Detection Engine Context.
fd Pointer to file descriptor.
Definition at line 226 of file util-threshold-config.c.
Referenced by SCThresholdConfInitContext().
int SCThresholdConfInitContext (DetectEngineCtx * de_ctx, FILE * utfd)
Inits the context to be used by the Threshold Config parsing API.
   This function initializes the hash table to be used by the Detection
   Engine Context to hold the data from the threshold.config file,
   obtains the file desc to parse the threshold.config file, and
   inits the regex used to parse the lines from threshold.config
   file.
Parameters
de_ctx Pointer to the Detection Engine Context.
utfd Pointer for unit test file descriptor.
Return values
0 On success.
-1 On failure.
Definition at line 145 of file util-threshold-config.c.
References DETECT_BASE_REGEX, DETECT_RATE_REGEX, DETECT_SUPPRESS_REGEX, DETECT_THRESHOLD_REGEX, SC_ERR_FOPEN, SC_ERR_PCRE_COMPILE, SC_ERR_PCRE_STUDY, SCLogDebug, SCLogError, SCLogWarning, SCThresholdConfDeInitContext(), and SCThresholdConfParseFile().
Referenced by DetectEngineReload().
int SCThresholdConfIsLineBlankOrComment (char * line)
Checks if a string is a comment or a blank line.
   Comments lines are lines of the following format -
   "# This is a comment string" or
   "   # This is a comment string".
Parameters
line String that has to be checked
Return values
1 On the argument string being a comment or blank line
0 Otherwise
Definition at line 1053 of file util-threshold-config.c.
Referenced by SCThresholdConfParseFile().
int SCThresholdConfLineIsMultiline (char * line)
Checks if the rule is multiline, by searching an ending slash.
Parameters
line String that has to be checked
Return values
the position of the slash making it multiline
0 Otherwise
Definition at line 1079 of file util-threshold-config.c.
References len.
Referenced by SCThresholdConfParseFile().
int SCThresholdConfLineLength (FILE * fd)
Get the config line length to allocate the buffer needed.
Parameters
fd Pointer to file descriptor.
Return values
int of the line length
Definition at line 1106 of file util-threshold-config.c.
References len, SC_ERR_THRESHOLD_SETUP, and SCLogError.
Referenced by SCThresholdConfParseFile().
void SCThresholdConfParseFile (DetectEngineCtx * de_ctx, FILE * fd)
Parses the Threshold Config file.
Parameters
de_ctx Pointer to the Detection Engine Context.
fd Pointer to file descriptor.
Definition at line 1132 of file util-threshold-config.c.
References len, SC_ERR_MEM_ALLOC, SCFree, SCLogDebug, SCLogError, SCLogInfo, SCMalloc, SCRealloc, SCThresholdConfAddThresholdtype(), SCThresholdConfIsLineBlankOrComment(), SCThresholdConfLineIsMultiline(), SCThresholdConfLineLength(), and unlikely.
Referenced by SCThresholdConfInitContext().
void SCThresholdConfRegisterTests (void)
This function registers unit tests for Classification Config API.
Definition at line 2879 of file util-threshold-config.c.
Referenced by RunUnittests().