suricata: src/util-mpm.h File Reference
util-mpm.h File Reference
#include "suricata-common.h"
Data Structures
struct MpmMatchBucket_
struct MpmThreadCtx_
struct PatternMatcherQueue_
helper structure for the pattern matcher engine. The Pattern Matcher thread has this and passes a pointer to it to the pattern matcher. The actual pattern matcher will fill the structure.
struct MpmCtx_
struct MpmCtxFactoryItem_
struct MpmCtxFactoryContainer_
struct MpmTableElmt_
Macros
#define MPM_ENDMATCH_SINGLE 0x01
#define MPM_ENDMATCH_OFFSET 0x02
#define MPM_ENDMATCH_DEPTH 0x04
#define MPM_ENDMATCH_NOSEARCH 0x08
#define HASHSIZE_LOWEST 2048
#define HASHSIZE_LOW 4096
#define HASHSIZE_MEDIUM 8192
#define HASHSIZE_HIGH 16384
#define HASHSIZE_HIGHER 32768
#define HASHSIZE_MAX 65536
#define BLOOMSIZE_LOW
#define BLOOMSIZE_MEDIUM 1024
#define BLOOMSIZE_HIGH 2048
#define DEFAULT_MPM MPM_AC
#define MPM_CTX_FACTORY_UNIQUE_CONTEXT -1
#define MPM_CTX_FACTORY_FLAGS_PREPARE_WITH_SIG_GROUP_BUILD 0x01
#define MPM_PATTERN_FLAG_NOCASE 0x01
#define MPM_PATTERN_FLAG_NEGATED 0x02
#define MPM_PATTERN_FLAG_DEPTH 0x04
#define MPM_PATTERN_FLAG_OFFSET 0x08
#define MPM_PATTERN_ONE_BYTE 0x10
Typedefs
typedef uint32_t MpmPatternIndex
typedef struct MpmMatchBucket_ MpmMatchBucket
typedef struct MpmThreadCtx_ MpmThreadCtx
typedef struct PatternMatcherQueue_ PatternMatcherQueue
helper structure for the pattern matcher engine. The Pattern Matcher thread has this and passes a pointer to it to the pattern matcher. The actual pattern matcher will fill the structure.
typedef struct MpmCtx_ MpmCtx
typedef struct MpmCtxFactoryItem_ MpmCtxFactoryItem
typedef struct
MpmCtxFactoryContainer_ MpmCtxFactoryContainer
typedef struct MpmTableElmt_ MpmTableElmt
Enumerations
enum {
MPM_NOTSET = 0, MPM_WUMANBER, MPM_B2G, MPM_B3G,
MPM_B2GC, MPM_B2GM, MPM_AC, MPM_AC_GFBS,
MPM_AC_BS, MPM_AC_TILE, MPM_TABLE_SIZE
}
Functions
int32_t MpmFactoryRegisterMpmCtxProfile (struct DetectEngineCtx_ *, const char *, uint8_t)
Register a new Mpm Context.
void MpmFactoryReClaimMpmCtx (struct DetectEngineCtx_ *, MpmCtx *)
MpmCtx * MpmFactoryGetMpmCtxForProfile (struct DetectEngineCtx_ *, int32_t, int)
void MpmFactoryDeRegisterAllMpmCtxProfiles (struct DetectEngineCtx_ *)
int32_t MpmFactoryIsMpmCtxAvailable (struct DetectEngineCtx_ *, MpmCtx *)
int PmqSetup (PatternMatcherQueue *, uint32_t)
Setup a pmq.
void PmqMerge (PatternMatcherQueue *src, PatternMatcherQueue *dst)
Merge two pmq's bitarrays.
void PmqReset (PatternMatcherQueue *)
Reset a Pmq for reusage. Meant to be called after a single search.
void PmqCleanup (PatternMatcherQueue *)
Cleanup a Pmq.
void PmqFree (PatternMatcherQueue *)
Cleanup and free a Pmq.
void MpmTableSetup (void)
void MpmRegisterTests (void)
int MpmVerifyMatch (MpmThreadCtx *thread_ctx, PatternMatcherQueue *pmq, uint32_t patid, uint8_t *bitarray, SigIntId *sids, uint32_t sids_size)
Verify and store a match.
void MpmInitCtx (MpmCtx *mpm_ctx, uint16_t matcher)
void MpmInitThreadCtx (MpmThreadCtx *mpm_thread_ctx, uint16_t, uint32_t)
uint32_t MpmGetHashSize (const char *)
Function to return the default hash size for the mpm algorithm, which has been defined by the user in the config file.
uint32_t MpmGetBloomSize (const char *)
Function to return the default bloomfilter size for the mpm algorithm, which has been defined by the user in the config file.
int MpmAddPatternCS (struct MpmCtx_ *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
int MpmAddPatternCI (struct MpmCtx_ *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
int MpmAddSidsResize (PatternMatcherQueue *pmq, uint32_t new_size)
Add array of Signature IDs to rule ID array.
int MpmAddPidResize (PatternMatcherQueue *pmq, uint32_t new_size)
Increase the size of the Pattern rule ID array.
Variables
MpmTableElmt mpm_table [MPM_TABLE_SIZE]
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-mpm.h.
Macro Definition Documentation
#define BLOOMSIZE_HIGH 2048
High bloomfilter size for the multi pattern matcher algorithms
Definition at line 60 of file util-mpm.h.
Referenced by MpmGetBloomSize().
#define BLOOMSIZE_LOW
Value:
512     /*<* Low bloomfilter size for the multi
                                            pattern matcher algorithms */
Definition at line 55 of file util-mpm.h.
Referenced by MpmGetBloomSize().
#define BLOOMSIZE_MEDIUM 1024
Medium bloomfilter size for the multi pattern matcher algorithms
Definition at line 57 of file util-mpm.h.
Referenced by B3gGetConfig(), MpmGetBloomSize(), and WmGetConfig().
#define DEFAULT_MPM MPM_AC
Definition at line 92 of file util-mpm.h.
Referenced by PatternMatchDefaultMatcher().
#define HASHSIZE_HIGH 16384
High hash size for the multi pattern matcher algorithms
Definition at line 46 of file util-mpm.h.
Referenced by B3gGetConfig(), and MpmGetHashSize().
#define HASHSIZE_HIGHER 32768
Higher hash size for the multi pattern matcher algorithms
Definition at line 49 of file util-mpm.h.
Referenced by B3gGetConfig(), and MpmGetHashSize().
#define HASHSIZE_LOW 4096
Low hash size for the multi pattern matcher algorithms
Definition at line 40 of file util-mpm.h.
Referenced by B3gGetConfig(), MpmGetHashSize(), and WmGetConfig().
#define HASHSIZE_LOWEST 2048
Lowest hash size for the multi pattern matcher algorithms
Definition at line 37 of file util-mpm.h.
Referenced by B3gGetConfig(), and MpmGetHashSize().
#define HASHSIZE_MAX 65536
Max hash size for the multi pattern matcher algorithms
Definition at line 52 of file util-mpm.h.
Referenced by B3gGetConfig(), and MpmGetHashSize().
#define HASHSIZE_MEDIUM 8192
Medium hash size for the multi pattern matcher algorithms
Definition at line 43 of file util-mpm.h.
Referenced by B3gGetConfig(), and MpmGetHashSize().
#define MPM_CTX_FACTORY_FLAGS_PREPARE_WITH_SIG_GROUP_BUILD 0x01
Definition at line 157 of file util-mpm.h.
#define MPM_CTX_FACTORY_UNIQUE_CONTEXT -1
Definition at line 155 of file util-mpm.h.
Referenced by MpmFactoryGetMpmCtxForProfile(), and PatternMatchPrepareGroup().
#define MPM_ENDMATCH_DEPTH 0x04
has depth setting
Definition at line 32 of file util-mpm.h.
#define MPM_ENDMATCH_NOSEARCH 0x08
if this matches, no search is required (for this pattern)
Definition at line 33 of file util-mpm.h.
#define MPM_ENDMATCH_OFFSET 0x02
has offset setting
Definition at line 31 of file util-mpm.h.
#define MPM_ENDMATCH_SINGLE 0x01
A single match is sufficient. No depth, offset, etc settings.
Definition at line 28 of file util-mpm.h.
#define MPM_PATTERN_FLAG_DEPTH 0x04
pattern has a depth setting
Definition at line 177 of file util-mpm.h.
#define MPM_PATTERN_FLAG_NEGATED 0x02
pattern is negated
Definition at line 175 of file util-mpm.h.
#define MPM_PATTERN_FLAG_NOCASE 0x01
pattern is case insensitive
Definition at line 173 of file util-mpm.h.
Referenced by B2gAddPatternCI(), B2gSearch(), B2gSearch1(), B2gSearchBNDMq(), B3gAddPatternCI(), B3gSearch(), B3gSearch1(), B3gSearch12(), B3gSearch2(), B3gSearchBNDMq(), SCACAddPatternCI(), SCACBSAddPatternCI(), SCACBSPreparePatterns(), SCACGfbsAddPatternCI(), SCACGfbsPreparePatterns(), SCACPreparePatterns(), WmAddPatternCI(), WmSearch1(), WmSearch2Hash12(), WmSearch2Hash14(), WmSearch2Hash15(), WmSearch2Hash16(), and WmSearch2Hash9().
#define MPM_PATTERN_FLAG_OFFSET 0x08
pattern has an offset setting
Definition at line 179 of file util-mpm.h.
#define MPM_PATTERN_ONE_BYTE 0x10
one byte pattern (used in b2g)
Definition at line 181 of file util-mpm.h.
Referenced by B2gSearch1().
Typedef Documentation
typedef struct MpmCtx_ MpmCtx
typedef struct MpmCtxFactoryContainer_ MpmCtxFactoryContainer
typedef struct MpmCtxFactoryItem_ MpmCtxFactoryItem
typedef struct MpmMatchBucket_ MpmMatchBucket
typedef uint32_t MpmPatternIndex
Definition at line 96 of file util-mpm.h.
typedef struct MpmTableElmt_ MpmTableElmt
typedef struct MpmThreadCtx_ MpmThreadCtx
typedef struct PatternMatcherQueue_ PatternMatcherQueue
helper structure for the pattern matcher engine. The Pattern Matcher thread has this and passes a pointer to it to the pattern matcher. The actual pattern matcher will fill the structure.
Enumeration Type Documentation
anonymous enum
Enumerator
MPM_NOTSET
MPM_WUMANBER
MPM_B2G
MPM_B3G
MPM_B2GC
MPM_B2GM
MPM_AC
MPM_AC_GFBS
MPM_AC_BS
MPM_AC_TILE
MPM_TABLE_SIZE
Definition at line 64 of file util-mpm.h.
Function Documentation
int MpmAddPatternCI (struct MpmCtx_ * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 747 of file util-mpm.c.
References MpmTableElmt_::AddPatternNocase, mpm_table, and MpmCtx_::mpm_type.
int MpmAddPatternCS (struct MpmCtx_ * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 738 of file util-mpm.c.
References MpmTableElmt_::AddPattern, mpm_table, and MpmCtx_::mpm_type.
int MpmAddPidResize (PatternMatcherQueue * pmq, uint32_t new_size)
Increase the size of the Pattern rule ID array.
Parameters
pmq storage for match results
new_size number of Signature IDs needing to be stored.
Returns
0 on failure.
Definition at line 512 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_array, PatternMatcherQueue_::pattern_id_array_size, SC_ERR_MEM_ALLOC, SCLogError, SCRealloc, and unlikely.
int MpmAddSidsResize (PatternMatcherQueue * pmq, uint32_t new_size)
Add array of Signature IDs to rule ID array.
Checks size of the array first
Parameters
pmq storage for match results
new_size number of Signature IDs needing to be stored.
Definition at line 477 of file util-mpm.c.
References PatternMatcherQueue_::rule_id_array, PatternMatcherQueue_::rule_id_array_size, SC_ERR_MEM_ALLOC, SCLogError, SCRealloc, SigIntId, and unlikely.
void MpmFactoryDeRegisterAllMpmCtxProfiles (struct DetectEngineCtx_ *)
Definition at line 246 of file util-mpm.c.
References MpmTableElmt_::DestroyCtx, MpmCtxFactoryContainer_::items, DetectEngineCtx_::mpm_ctx_factory_container, MpmCtxFactoryItem_::mpm_ctx_tc, MpmCtxFactoryItem_::mpm_ctx_ts, MPM_NOTSET, mpm_table, MpmCtx_::mpm_type, MpmCtxFactoryContainer_::no_of_items, and SCFree.
Referenced by DetectEngineCtxFree().
MpmCtx* MpmFactoryGetMpmCtxForProfile (struct DetectEngineCtx_ * , int32_t , int)
Definition at line 209 of file util-mpm.c.
References MpmCtxFactoryContainer_::items, DetectEngineCtx_::mpm_ctx_factory_container, MPM_CTX_FACTORY_UNIQUE_CONTEXT, MpmCtxFactoryItem_::mpm_ctx_tc, MpmCtxFactoryItem_::mpm_ctx_ts, MpmCtxFactoryContainer_::no_of_items, SC_ERR_INVALID_ARGUMENTS, SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, and unlikely.
Referenced by PatternMatchPrepareGroup(), and SigGroupBuild().
int32_t MpmFactoryIsMpmCtxAvailable (struct DetectEngineCtx_ * , MpmCtx *)
Definition at line 190 of file util-mpm.c.
References MpmCtxFactoryContainer_::items, DetectEngineCtx_::mpm_ctx_factory_container, MpmCtxFactoryItem_::mpm_ctx_tc, MpmCtxFactoryItem_::mpm_ctx_ts, and MpmCtxFactoryContainer_::no_of_items.
Referenced by MpmFactoryReClaimMpmCtx().
void MpmFactoryReClaimMpmCtx (struct DetectEngineCtx_ * , MpmCtx *)
Definition at line 232 of file util-mpm.c.
References MpmTableElmt_::DestroyCtx, MPM_NOTSET, mpm_table, MpmCtx_::mpm_type, MpmFactoryIsMpmCtxAvailable(), and SCFree.
Referenced by PatternMatchPrepareGroup().
int32_t MpmFactoryRegisterMpmCtxProfile (DetectEngineCtx * de_ctx, const char * name, uint8_t flags)
Register a new Mpm Context.
Parameters
name A new profile to be registered to store this MpmCtx.
Return values
id Return the id created for the new MpmCtx profile.
Definition at line 59 of file util-mpm.c.
References flags, MpmCtxFactoryItem_::flags, MpmCtx_::global, MpmCtxFactoryItem_::id, MpmCtxFactoryContainer_::items, DetectEngineCtx_::mpm_ctx_factory_container, MpmCtxFactoryItem_::mpm_ctx_tc, MpmCtxFactoryItem_::mpm_ctx_ts, MpmCtxFactoryItem_::name, MpmCtxFactoryContainer_::no_of_items, SC_ERR_MEM_ALLOC, SCFree, SCLogError, SCMalloc, SCRealloc, SCStrdup, and unlikely.
uint32_t MpmGetBloomSize (const char * conf_val)
Function to return the default bloomfilter size for the mpm algorithm, which has been defined by the user in the config file.
Parameters
conf_val pointer to the string value of bloom filter size
Return values
bloom_value returns the bloom filter value as defined by user, otherwise default medium size value
Definition at line 722 of file util-mpm.c.
References BLOOMSIZE_HIGH, BLOOMSIZE_LOW, BLOOMSIZE_MEDIUM, SCEnter, and SCReturnInt.
Referenced by B3gGetConfig(), and WmGetConfig().
uint32_t MpmGetHashSize (const char * conf_val)
Function to return the default hash size for the mpm algorithm, which has been defined by the user in the config file.
Parameters
conf_val pointer to the string value of hash size
Return values
hash_value returns the hash value as defined by user, otherwise default low size value
Definition at line 689 of file util-mpm.c.
References HASHSIZE_HIGH, HASHSIZE_HIGHER, HASHSIZE_LOW, HASHSIZE_LOWEST, HASHSIZE_MAX, HASHSIZE_MEDIUM, SCEnter, and SCReturnInt.
Referenced by B3gGetConfig(), and WmGetConfig().
void MpmInitCtx (MpmCtx * mpm_ctx, uint16_t matcher)
Definition at line 660 of file util-mpm.c.
References MpmTableElmt_::InitCtx, mpm_table, and MpmCtx_::mpm_type.
Referenced by AppLayerProtoDetectSetup(), PatternMatchPrepare(), and PatternMatchPrepareGroup().
void MpmInitThreadCtx (MpmThreadCtx * mpm_thread_ctx, uint16_t , uint32_t)
Definition at line 655 of file util-mpm.c.
References MpmTableElmt_::InitThreadCtx, and mpm_table.
Referenced by PatternMatchThreadPrepare().
void MpmRegisterTests (void)
Definition at line 763 of file util-mpm.c.
References coverage_unittests, g_ut_covered, g_ut_modules, MPM_NOTSET, mpm_table, MPM_TABLE_SIZE, MpmTableElmt_::RegisterUnittests, SC_WARN_NO_UNITTESTS, and SCLogWarning.
Referenced by RunUnittests().
void MpmTableSetup (void)
Definition at line 666 of file util-mpm.c.
References mpm_table, MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmACTileRegister(), MpmB2gRegister(), MpmB3gRegister(), and MpmWuManberRegister().
Referenced by ListAppLayerProtocols(), ListKeywords(), and RunUnittests().
int MpmVerifyMatch (MpmThreadCtx * thread_ctx, PatternMatcherQueue * pmq, uint32_t patid, uint8_t * bitarray, SigIntId * sids, uint32_t sids_size)
Verify and store a match.
used at search runtime
Parameters
thread_ctx mpm thread ctx
pmq storage for match results
patid pattern ID being checked
bitarray Array of bits for patterns IDs found in current search
sids pointer to array of Signature IDs
sids_size number of Signature IDs in sids array.
Return values
0 no match after all
1 (new) match
Definition at line 553 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_bitarray, SCEnter, SCLogDebug, and SCReturnInt.
Referenced by B2gSearch(), B2gSearch1(), B2gSearchBNDMq(), B3gSearch(), B3gSearch1(), B3gSearch12(), B3gSearch2(), B3gSearchBNDMq(), WmSearch1(), WmSearch2Hash12(), WmSearch2Hash14(), WmSearch2Hash15(), WmSearch2Hash16(), and WmSearch2Hash9().
void PmqCleanup (PatternMatcherQueue * pmq)
Cleanup a Pmq.
Parameters
pmq Pattern matcher queue to be cleaned up.
Definition at line 620 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_array, PatternMatcherQueue_::pattern_id_array_cnt, PatternMatcherQueue_::pattern_id_array_size, PatternMatcherQueue_::pattern_id_bitarray, PatternMatcherQueue_::rule_id_array, and SCFree.
Referenced by PmqFree().
void PmqFree (PatternMatcherQueue * pmq)
Cleanup and free a Pmq.
Parameters
pmq Pattern matcher queue to be free'd.
Definition at line 647 of file util-mpm.c.
References PmqCleanup().
Referenced by AppLayerProtoDetectDestroyCtxThread(), and DetectEngineThreadCtxFree().
void PmqMerge (PatternMatcherQueue * src, PatternMatcherQueue * dst)
Merge two pmq's bitarrays.
Parameters
src source pmq
dst destination pmq to merge into
Todo:
now set merged flag?
Definition at line 581 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_array_cnt, PatternMatcherQueue_::pattern_id_bitarray, PatternMatcherQueue_::pattern_id_bitarray_size, PatternMatcherQueue_::rule_id_array, and PatternMatcherQueue_::rule_id_array_cnt.
Referenced by StreamPatternSearch().
void PmqReset (PatternMatcherQueue * pmq)
Reset a Pmq for reusage. Meant to be called after a single search.
Parameters
pmq Pattern matcher to be reset.
Todo:
memset is expensive, but we need it as we merge pmq's. We might use a flag so we can clear pmq's the old way if we can.
Definition at line 604 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_array_cnt, PatternMatcherQueue_::pattern_id_bitarray, PatternMatcherQueue_::pattern_id_bitarray_size, and PatternMatcherQueue_::rule_id_array_cnt.
Referenced by PacketPatternCleanup(), and StreamPatternCleanup().
int PmqSetup (PatternMatcherQueue * pmq, uint32_t patmaxid)
Setup a pmq.
Parameters
pmq Pattern matcher queue to be initialized
maxid Max sig id to be matched on
patmaxid Max pattern id to be matched on
Return values
-1 error
0 ok
Definition at line 421 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_array, PatternMatcherQueue_::pattern_id_array_cnt, PatternMatcherQueue_::pattern_id_array_size, PatternMatcherQueue_::pattern_id_bitarray, PatternMatcherQueue_::pattern_id_bitarray_size, PatternMatcherQueue_::rule_id_array, PatternMatcherQueue_::rule_id_array_cnt, PatternMatcherQueue_::rule_id_array_size, SCCalloc, SCEnter, SCLogDebug, SCMalloc, SCReturnInt, and SigIntId.
Referenced by AppLayerProtoDetectGetCtxThread().
Variable Documentation
MpmTableElmt mpm_table[MPM_TABLE_SIZE]
Definition at line 213 of file util-mpm.h.
Referenced by AppLayerProtoDetectDeSetup(), AppLayerProtoDetectDestroyCtxThread(), AppLayerProtoDetectGetCtxThread(), DnsQueryPatternSearch(), HttpClientBodyPatternSearch(), HttpCookiePatternSearch(), HttpHeaderPatternSearch(), HttpHHPatternSearch(), HttpHRHPatternSearch(), HttpMethodPatternSearch(), HttpRawHeaderPatternSearch(), HttpRawUriPatternSearch(), HttpServerBodyPatternSearch(), HttpStatCodePatternSearch(), HttpStatMsgPatternSearch(), HttpUAPatternSearch(), MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmAddPatternCI(), MpmAddPatternCS(), MpmB2gRegister(), MpmB3gRegister(), MpmFactoryDeRegisterAllMpmCtxProfiles(), MpmFactoryReClaimMpmCtx(), MpmInitCtx(), MpmInitThreadCtx(), MpmRegisterTests(), MpmTableSetup(), MpmWuManberRegister(), PacketPatternCleanup(), PacketPatternSearch(), PacketPatternSearchWithStreamCtx(), PatternMatchDefaultMatcher(), PatternMatchDestroy(), PatternMatchDestroyGroup(), PatternMatchPrepareGroup(), PatternMatchThreadDestroy(), SigGroupBuild(), SMTPFiledataPatternSearch(), StreamPatternSearch(), and UriPatternSearch().