suricata: src/util-bloomfilter.h File Reference
util-bloomfilter.h File Reference
Data Structures
struct BloomFilter_
Typedefs
typedef struct BloomFilter_ BloomFilter
Functions
BloomFilter * BloomFilterInit (uint32_t, uint8_t, uint32_t(*Hash)(void *, uint16_t, uint8_t, uint32_t))
void BloomFilterFree (BloomFilter *)
void BloomFilterPrint (BloomFilter *)
int BloomFilterAdd (BloomFilter *, void *, uint16_t)
uint32_t BloomFilterMemoryCnt (BloomFilter *)
uint32_t BloomFilterMemorySize (BloomFilter *)
void BloomFilterRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-bloomfilter.h.
Typedef Documentation
typedef struct BloomFilter_ BloomFilter
Function Documentation
int BloomFilterAdd (BloomFilter * , void * , uint16_t)
Definition at line 88 of file util-bloomfilter.c.
References BloomFilter_::bitarray, BloomFilter_::bitarray_size, BloomFilter_::Hash, and BloomFilter_::hash_iterations.
void BloomFilterFree (BloomFilter *)
Definition at line 68 of file util-bloomfilter.c.
References BloomFilter_::bitarray, and SCFree.
Referenced by B2gDestroyCtx(), B3gDestroyCtx(), and WmDestroyCtx().
BloomFilter* BloomFilterInit (uint32_t , uint8_t , uint32_t(*)(void *, uint16_t, uint8_t, uint32_t) Hash)
Definition at line 30 of file util-bloomfilter.c.
References BloomFilter_::bitarray, BloomFilter_::bitarray_size, BloomFilter_::Hash, BloomFilter_::hash_iterations, SCFree, SCMalloc, and unlikely.
uint32_t BloomFilterMemoryCnt (BloomFilter *)
Definition at line 104 of file util-bloomfilter.c.
Referenced by B2gDestroyCtx(), B3gDestroyCtx(), and WmDestroyCtx().
uint32_t BloomFilterMemorySize (BloomFilter *)
Definition at line 112 of file util-bloomfilter.c.
References BloomFilter_::bitarray_size.
Referenced by B2gDestroyCtx(), B3gDestroyCtx(), and WmDestroyCtx().
void BloomFilterPrint (BloomFilter *)
Definition at line 78 of file util-bloomfilter.c.
References BloomFilter_::bitarray_size, BloomFilter_::Hash, and BloomFilter_::hash_iterations.
void BloomFilterRegisterTests (void)
Definition at line 274 of file util-bloomfilter.c.
Referenced by RunUnittests().