suricata: src/util-file.c File Reference
util-file.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "debug.h"
#include "flow.h"
#include "stream.h"
#include "runmodes.h"
#include "util-hash.h"
#include "util-debug.h"
#include "util-memcmp.h"
#include "util-print.h"
#include "app-layer-parser.h"
#include "util-validate.h"
Functions
void FileForceMagicEnable (void)
void FileForceMd5Enable (void)
int FileForceMagic (void)
int FileForceMd5 (void)
void FileForceTrackingEnable (void)
int FileMagicSize (void)
void FilePrune (FileContainer *ffc)
FileContainer * FileContainerAlloc (void)
allocate a FileContainer
void FileContainerRecycle (FileContainer *ffc)
Recycle a FileContainer.
void FileContainerFree (FileContainer *ffc)
Free a FileContainer.
void FileContainerAdd (FileContainer *ffc, File *ff)
int FileStore (File *ff)
Tag a file for storing.
int FileSetTx (File *ff, uint64_t txid)
Set the TX id for a file.
int FileAppendData (FileContainer *ffc, uint8_t *data, uint32_t data_len)
Store a chunk of file data in the flow. The open "flowfile" will be used.
File * FileOpenFile (FileContainer *ffc, uint8_t *name, uint16_t name_len, uint8_t *data, uint32_t data_len, uint8_t flags)
Open a new File.
int FileCloseFile (FileContainer *ffc, uint8_t *data, uint32_t data_len, uint8_t flags)
Close a File.
void FileDisableStoring (Flow *f, uint8_t direction)
disable file storage for a flow
void FileDisableMagic (Flow *f, uint8_t direction)
disable file magic lookups for this flow
void FileDisableMd5 (Flow *f, uint8_t direction)
disable file md5 calc for this flow
void FileDisableFilesize (Flow *f, uint8_t direction)
disable file size tracking for this flow
void FileDisableStoringForFile (File *ff)
set no store flag, close file if needed
void FileDisableStoringForTransaction (Flow *f, uint8_t direction, uint64_t tx_id)
disable file storing for files in a transaction
void FileStoreFileById (FileContainer *fc, uint16_t file_id)
flag a file with id "file_id" to be stored.
void FileStoreAllFilesForTx (FileContainer *fc, uint16_t tx_id)
void FileStoreAllFiles (FileContainer *fc)
void FileTruncateAllOpenFiles (FileContainer *fc)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file util-file.c.
Function Documentation
int FileAppendData (FileContainer * ffc, uint8_t * data, uint32_t data_len)
Store a chunk of file data in the flow. The open "flowfile" will be used.
Parameters
ffc the container
data data chunk
data_len data chunk len
Return values
0 ok
-1 error
-2 no store for this file
Definition at line 453 of file util-file.c.
References File_::chunks_head, FILE_NOSTORE, FILE_NOTRACK, FILE_STATE_ERROR, FILE_STATE_OPENED, FILE_STATE_TRUNCATED, File_::flags, SCEnter, SCLogDebug, SCReturnInt, File_::size, File_::state, FileData_::stream_offset, and FileContainer_::tail.
Referenced by HTPFileStoreChunk(), and SMTPProcessDataChunk().
int FileCloseFile (FileContainer * ffc, uint8_t * data, uint32_t data_len, uint8_t flags)
Close a File.
Parameters
ffc the container
data final data if any
data_len data len if any
flags flags
Return values
0 ok
-1 error
Definition at line 664 of file util-file.c.
References SCEnter, SCReturnInt, and FileContainer_::tail.
Referenced by HTPFileClose(), and SMTPProcessDataChunk().
void FileContainerAdd (FileContainer * ffc, File * ff)
Definition at line 379 of file util-file.c.
References FileContainer_::head, File_::next, and FileContainer_::tail.
Referenced by FileOpenFile().
FileContainer* FileContainerAlloc (void)
allocate a FileContainer
Return values
new newly allocated FileContainer
NULL error
Definition at line 218 of file util-file.c.
References SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, and unlikely.
Referenced by HTPFileOpen(), and SMTPProcessDataChunk().
void FileContainerFree (FileContainer * ffc)
Free a FileContainer.
Parameters
ffc FileContainer
Definition at line 254 of file util-file.c.
References FileContainer_::head, File_::next, next, SCFree, and FileContainer_::tail.
Referenced by HTPStateFree().
void FileContainerRecycle (FileContainer * ffc)
Recycle a FileContainer.
Parameters
ffc FileContainer
Definition at line 235 of file util-file.c.
References FileContainer_::head, File_::next, next, and FileContainer_::tail.
void FileDisableFilesize (Flow * f, uint8_t direction)
disable file size tracking for this flow
Parameters
f LOCKED flow
direction flow direction
Definition at line 788 of file util-file.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), DEBUG_ASSERT_FLOW_LOCKED, FILE_NOTRACK, File_::flags, Flow_::flags, FLOW_FILE_NO_SIZE_TC, FLOW_FILE_NO_SIZE_TS, FileContainer_::head, File_::next, Flow_::proto, SCEnter, SCLogDebug, SCReturn, and STREAM_TOSERVER.
Referenced by SigMatchSignatures().
void FileDisableMagic (Flow * f, uint8_t direction)
disable file magic lookups for this flow
Parameters
f LOCKED flow
direction flow direction
Definition at line 718 of file util-file.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), DEBUG_ASSERT_FLOW_LOCKED, FILE_NOMAGIC, File_::flags, Flow_::flags, FLOW_FILE_NO_MAGIC_TC, FLOW_FILE_NO_MAGIC_TS, FileContainer_::head, File_::next, Flow_::proto, SCEnter, SCLogDebug, SCReturn, and STREAM_TOSERVER.
Referenced by SigMatchSignatures().
void FileDisableMd5 (Flow * f, uint8_t direction)
disable file md5 calc for this flow
Parameters
f LOCKED flow
direction flow direction
Definition at line 749 of file util-file.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), DEBUG_ASSERT_FLOW_LOCKED, FILE_NOMD5, File_::flags, Flow_::flags, FLOW_FILE_NO_MD5_TC, FLOW_FILE_NO_MD5_TS, FileContainer_::head, File_::next, Flow_::proto, SCEnter, SCLogDebug, SCReturn, and STREAM_TOSERVER.
Referenced by SigMatchSignatures().
void FileDisableStoring (Flow * f, uint8_t direction)
disable file storage for a flow
Parameters
f LOCKED flow
direction flow direction
Definition at line 686 of file util-file.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), DEBUG_ASSERT_FLOW_LOCKED, FILE_NOSTORE, FILE_STORE, File_::flags, Flow_::flags, FLOW_FILE_NO_STORE_TC, FLOW_FILE_NO_STORE_TS, FileContainer_::head, File_::next, Flow_::proto, SCEnter, SCLogDebug, SCReturn, and STREAM_TOSERVER.
Referenced by SigMatchSignatures().
void FileDisableStoringForFile (File * ff)
set no store flag, close file if needed
Parameters
ff file
Definition at line 819 of file util-file.c.
References FILE_NOSTORE, FILE_STATE_OPENED, FileMagicSize(), File_::flags, SCEnter, SCLogDebug, SCReturn, File_::size, and File_::state.
Referenced by FileDisableStoringForTransaction().
void FileDisableStoringForTransaction (Flow * f, uint8_t direction, uint64_t tx_id)
disable file storing for files in a transaction
disable file storing for a transaction
Parameters
f LOCKED flow
direction flow direction
tx_id transaction id
Definition at line 845 of file util-file.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), DEBUG_ASSERT_FLOW_LOCKED, FILE_STORE, FileDisableStoringForFile(), File_::flags, FileContainer_::head, File_::next, Flow_::proto, SCEnter, SCLogDebug, SCReturn, and File_::txid.
int FileForceMagic (void)
Definition at line 68 of file util-file.c.
Referenced by SigMatchSignatures().
void FileForceMagicEnable (void)
Definition at line 58 of file util-file.c.
int FileForceMd5 (void)
Definition at line 73 of file util-file.c.
Referenced by SigMatchSignatures().
void FileForceMd5Enable (void)
Definition at line 63 of file util-file.c.
void FileForceTrackingEnable (void)
Definition at line 78 of file util-file.c.
int FileMagicSize (void)
Todo:
make this size configurable
Definition at line 83 of file util-file.c.
Referenced by FileDisableStoringForFile().
File* FileOpenFile (FileContainer * ffc, uint8_t * name, uint16_t name_len, uint8_t * data, uint32_t data_len, uint8_t flags)
Open a new File.
Parameters
ffc flow container
name filename character array
name_len filename len
data initial data
data_len initial data len
flags open flags
Return values
ff flowfile object
Note
filename is not a string, so it's not nul terminated.
Definition at line 525 of file util-file.c.
References FILE_NOMAGIC, FILE_NOMD5, FILE_NOSTORE, FILE_STATE_ERROR, FILE_STATE_OPENED, FILE_STORE, FileContainerAdd(), File_::flags, SCEnter, SCLogDebug, SCReturnPtr, File_::size, and File_::state.
Referenced by HTPFileOpen(), and SMTPProcessDataChunk().
void FilePrune (FileContainer * ffc)
Definition at line 190 of file util-file.c.
References BUG_ON, FileContainer_::head, File_::next, and FileContainer_::tail.
Referenced by HTPFileClose(), HTPFileOpen(), HTPFileStoreChunk(), and SMTPProcessDataChunk().
int FileSetTx (File * ff, uint64_t txid)
Set the TX id for a file.
Parameters
ff The file to store
txid the tx id
Definition at line 406 of file util-file.c.
References SCLogDebug, SCReturnInt, and File_::txid.
Referenced by HTPFileOpen().
int FileStore (File * ff)
Tag a file for storing.
Parameters
ff The file to store
Definition at line 394 of file util-file.c.
References FILE_STORE, File_::flags, and SCReturnInt.
void FileStoreAllFiles (FileContainer * fc)
Definition at line 906 of file util-file.c.
References FILE_STORE, File_::flags, FileContainer_::head, File_::next, and SCEnter.
void FileStoreAllFilesForTx (FileContainer * fc, uint16_t tx_id)
Definition at line 891 of file util-file.c.
References FILE_STORE, File_::flags, FileContainer_::head, File_::next, SCEnter, and File_::txid.
void FileStoreFileById (FileContainer * fc, uint16_t file_id)
flag a file with id "file_id" to be stored.
Parameters
fc file store
file_id the file's id
Definition at line 876 of file util-file.c.
References File_::file_id, FILE_STORE, File_::flags, FileContainer_::head, File_::next, and SCEnter.
Referenced by DetectFilestorePostMatch().
void FileTruncateAllOpenFiles (FileContainer * fc)
Definition at line 919 of file util-file.c.
References FILE_STATE_OPENED, FileContainer_::head, File_::next, SCEnter, and File_::state.