suricata: src/util-running-modes.c File Reference
util-running-modes.c File Reference
#include "suricata-common.h"
#include "config.h"
#include "app-layer-detect-proto.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "util-cuda.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "conf-yaml-loader.h"
Functions
int ListKeywords (const char *keyword_info)
int ListAppLayerProtocols ()
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file util-running-modes.c.
Function Documentation
int ListAppLayerProtocols ()
Definition at line 44 of file util-running-modes.c.
References AppLayerListSupportedProtocols(), AppLayerSetup(), ConfYamlLoadFile(), DEFAULT_CONF_FILE, MpmTableSetup(), and SCLogLoadConfig().
Referenced by StartInternalRunMode().
int ListKeywords (const char * keyword_info)
Definition at line 33 of file util-running-modes.c.
References AppLayerSetup(), ConfYamlLoadFile(), DEFAULT_CONF_FILE, MpmTableSetup(), SCLogLoadConfig(), SigTableList(), and SigTableSetup().
Referenced by StartInternalRunMode().