suricata: src/util-bloomfilter-counting.h File Reference
util-bloomfilter-counting.h File Reference
Data Structures
struct BloomFilterCounting_
Typedefs
typedef struct BloomFilterCounting_ BloomFilterCounting
Functions
BloomFilterCounting * BloomFilterCountingInit (uint32_t, uint8_t, uint8_t, uint32_t(*Hash)(void *, uint16_t, uint8_t, uint32_t))
void BloomFilterCountingFree (BloomFilterCounting *)
void BloomFilterCountingPrint (BloomFilterCounting *)
int BloomFilterCountingAdd (BloomFilterCounting *, void *, uint16_t)
int BloomFilterCountingRemove (BloomFilterCounting *, void *, uint16_t)
int BloomFilterCountingTest (BloomFilterCounting *, void *, uint16_t)
void BloomFilterCountingRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-bloomfilter-counting.h.
Typedef Documentation
typedef struct BloomFilterCounting_ BloomFilterCounting
Function Documentation
int BloomFilterCountingAdd (BloomFilterCounting * , void * , uint16_t)
Definition at line 99 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array, BloomFilterCounting_::array_size, BloomFilterCounting_::Hash, BloomFilterCounting_::hash_iterations, and BloomFilterCounting_::type.
void BloomFilterCountingFree (BloomFilterCounting *)
Definition at line 78 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array, and SCFree.
BloomFilterCounting* BloomFilterCountingInit (uint32_t , uint8_t , uint8_t , uint32_t(*)(void *, uint16_t, uint8_t, uint32_t) Hash)
Definition at line 34 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array, BloomFilterCounting_::array_size, BloomFilterCounting_::Hash, BloomFilterCounting_::hash_iterations, SCFree, SCMalloc, BloomFilterCounting_::type, type, and unlikely.
void BloomFilterCountingPrint (BloomFilterCounting *)
Definition at line 88 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array_size, BloomFilterCounting_::Hash, BloomFilterCounting_::hash_iterations, and BloomFilterCounting_::type.
void BloomFilterCountingRegisterTests (void)
Definition at line 393 of file util-bloomfilter-counting.c.
Referenced by RunUnittests().
int BloomFilterCountingRemove (BloomFilterCounting * , void * , uint16_t)
Definition at line 127 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array, BloomFilterCounting_::array_size, BloomFilterCountingTest(), BloomFilterCounting_::Hash, BloomFilterCounting_::hash_iterations, and BloomFilterCounting_::type.
int BloomFilterCountingTest (BloomFilterCounting * , void * , uint16_t)
Definition at line 183 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array, BloomFilterCounting_::array_size, BloomFilterCounting_::Hash, BloomFilterCounting_::hash_iterations, and BloomFilterCounting_::type.
Referenced by BloomFilterCountingRemove().