suricata: src/util-proto-name.h File Reference
util-proto-name.h File Reference
Macros
#define PROTO_FILE "/etc/protocols"
Functions
uint8_t SCProtoNameValid (uint16_t)
Function to check if the received protocol number is valid and do we have corresponding name entry for this number or not.
void SCProtoNameInit (void)
Function to load the protocol names from the specified protocol file.
void SCProtoNameDeInit (void)
Function to clears the memory used in storing the protocol names.
Variables
char * known_proto [256]
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Definition in file util-proto-name.h.
Macro Definition Documentation
#define PROTO_FILE "/etc/protocols"
Definition at line 28 of file util-proto-name.h.
Referenced by SCProtoNameInit().
Function Documentation
void SCProtoNameDeInit (void)
Function to clears the memory used in storing the protocol names.
Definition at line 108 of file util-proto-name.c.
References known_proto, and SCFree.
Referenced by main().
void SCProtoNameInit (void)
Function to load the protocol names from the specified protocol file.
Definition at line 36 of file util-proto-name.c.
References BUG_ON, known_proto, proto, PROTO_FILE, SC_ERR_MEM_ALLOC, SCFree, SCLogError, SCStrdup, and unlikely.
Referenced by RunUnittests().
uint8_t SCProtoNameValid (uint16_t proto)
Function to check if the received protocol number is valid and do we have corresponding name entry for this number or not.
Parameters
proto Protocol number to be validated
Return values
ret On success returns TRUE otherwise FALSE
Definition at line 94 of file util-proto-name.c.
References FALSE, known_proto, and TRUE.
Referenced by AlertFastLogger().
Variable Documentation
char* known_proto[256]
Lookup array to hold the information related to known protocol in /etc/protocols
Definition at line 35 of file util-proto-name.h.
Referenced by AlertFastLogger(), SCProtoNameDeInit(), SCProtoNameInit(), and SCProtoNameValid().