suricata: src/util-byte.c File Reference
util-byte.c File Reference
#include "suricata-common.h"
#include "util-byte.h"
#include "util-unittest.h"
#include "util-debug.h"
Functions
char * BytesToString (const uint8_t *bytes, size_t nbytes)
Turn byte array into string.
int ByteExtractUint64 (uint64_t *res, int e, uint16_t len, const uint8_t *bytes)
int ByteExtractUint32 (uint32_t *res, int e, uint16_t len, const uint8_t *bytes)
int ByteExtractUint16 (uint16_t *res, int e, uint16_t len, const uint8_t *bytes)
int ByteExtractString (uint64_t *res, int base, uint16_t len, const char *str)
int ByteExtractStringUint64 (uint64_t *res, int base, uint16_t len, const char *str)
int ByteExtractStringUint32 (uint32_t *res, int base, uint16_t len, const char *str)
int ByteExtractStringUint16 (uint16_t *res, int base, uint16_t len, const char *str)
int ByteExtractStringUint8 (uint8_t *res, int base, uint16_t len, const char *str)
int ByteExtractStringSigned (int64_t *res, int base, uint16_t len, const char *str)
int ByteExtractStringInt64 (int64_t *res, int base, uint16_t len, const char *str)
int ByteExtractStringInt32 (int32_t *res, int base, uint16_t len, const char *str)
int ByteExtractStringInt16 (int16_t *res, int base, uint16_t len, const char *str)
int ByteExtractStringInt8 (int8_t *res, int base, uint16_t len, const char *str)
void ByteRegisterTests (void)
Detailed Description
Author
Brian Rectanus brect.nosp@m.anu@.nosp@m.gmail.nosp@m..com
Byte utility functions
Definition in file util-byte.c.
Function Documentation
int ByteExtractString (uint64_t * res, int base, uint16_t len, const char * str)
Extract unsigned integer value from a string.
Parameters
res Stores result
base Base of the number to extract
len Number of bytes to extract (23 max or 0 for unbounded)
str String to extract from
Returns
n Number of bytes extracted on success
-1 On error
Definition at line 137 of file util-byte.c.
References len, SC_ERR_ARG_LEN_LONG, SC_ERR_INVALID_NUMERIC_VALUE, SC_ERR_NUMERIC_VALUE_ERANGE, SCLogDebug, SCLogError, and str.
Referenced by ByteExtractStringUint16(), ByteExtractStringUint32(), ByteExtractStringUint64(), and ByteExtractStringUint8().
int ByteExtractStringInt16 (int16_t * res, int base, uint16_t len, const char * str)
Extract signed integer value from a string as uint16_t.
Parameters
res Stores result
base Base of the number to extract
len Number of bytes to extract (23 max or 0 for unbounded)
str String to extract from
Returns
n Number of bytes extracted on success
-1 On error
Definition at line 336 of file util-byte.c.
References ByteExtractStringSigned(), SC_ERR_NUMERIC_VALUE_ERANGE, and SCLogError.
int ByteExtractStringInt32 (int32_t * res, int base, uint16_t len, const char * str)
Extract signed integer value from a string as uint32_t.
Parameters
res Stores result
base Base of the number to extract
len Number of bytes to extract (23 max or 0 for unbounded)
str String to extract from
Returns
n Number of bytes extracted on success
-1 On error
Definition at line 315 of file util-byte.c.
References ByteExtractStringSigned(), SC_ERR_NUMERIC_VALUE_ERANGE, and SCLogError.
Referenced by DetectAsn1Parse(), DetectBytejumpParse(), and DetectBytetestParse().
int ByteExtractStringInt64 (int64_t * res, int base, uint16_t len, const char * str)
Extract signed integer value from a string as uint64_t.
Parameters
res Stores result
base Base of the number to extract
len Number of bytes to extract (23 max or 0 for unbounded)
str String to extract from
Returns
n Number of bytes extracted on success
-1 On error
Definition at line 310 of file util-byte.c.
References ByteExtractStringSigned().
int ByteExtractStringInt8 (int8_t * res, int base, uint16_t len, const char * str)
Extract signed integer value from a string as uint8_t.
Parameters
res Stores result
base Base of the number to extract
len Number of bytes to extract (23 max or 0 for unbounded)
str String to extract from
Returns
n Number of bytes extracted on success
-1 On error
Definition at line 357 of file util-byte.c.
References ByteExtractStringSigned(), SC_ERR_NUMERIC_VALUE_ERANGE, and SCLogError.
int ByteExtractStringSigned (int64_t * res, int base, uint16_t len, const char * str)
Extract signed integer value from a string.
Parameters
res Stores result
base Base of the number to extract
len Number of bytes to extract (23 max or 0 for unbounded)
str String to extract from
Returns
n Number of bytes extracted on success
-1 On error
Definition at line 259 of file util-byte.c.
References len, SC_ERR_ARG_LEN_LONG, SC_ERR_INVALID_NUMERIC_VALUE, SC_ERR_NUMERIC_VALUE_ERANGE, SCLogError, and str.
Referenced by ByteExtractStringInt16(), ByteExtractStringInt32(), ByteExtractStringInt64(), ByteExtractStringInt8(), and DetectTosParse().
int ByteExtractStringUint16 (uint16_t * res, int base, uint16_t len, const char * str)
Extract unsigned integer value from a string as uint16_t.
Parameters
res Stores result
base Base of the number to extract
len Number of bytes to extract (23 max or 0 for unbounded)
str String to extract from
Returns
n Number of bytes extracted on success
-1 On error
Definition at line 217 of file util-byte.c.
References ByteExtractString(), SC_ERR_NUMERIC_VALUE_ERANGE, and SCLogError.
Referenced by DetectDsizeParse(), DetectEngineMultiTenantSetup(), DetectFragOffsetParse(), DetectIcmpIdParse(), DetectIcmpSeqParse(), DetectIsdataatParse(), DetectUrilenParse(), DetectWindowParse(), IPFWRegisterQueue(), NFQRegisterQueue(), and StreamTcpReassemblyConfig().
int ByteExtractStringUint32 (uint32_t * res, int base, uint16_t len, const char * str)
Extract unsigned integer value from a string as uint32_t.
Parameters
res Stores result
base Base of the number to extract
len Number of bytes to extract (23 max or 0 for unbounded)
str String to extract from
Returns
n Number of bytes extracted on success
-1 On error
Definition at line 196 of file util-byte.c.
References ByteExtractString(), SC_ERR_NUMERIC_VALUE_ERANGE, and SCLogError.
Referenced by DefragInitConfig(), DetectAsn1Parse(), DetectBytejumpParse(), DetectBytetestParse(), DetectDetectionFilterParse(), DetectEngineMultiTenantSetup(), DetectRpcParse(), DetectTagParse(), FlowInitConfig(), FlowInitFlowProto(), HostInitConfig(), IPPairInitConfig(), SCProfilingRulesGlobalInit(), StreamTcpReassemblyConfig(), and Unified2AlertInitCtx().
int ByteExtractStringUint64 (uint64_t * res, int base, uint16_t len, const char * str)
Extract unsigned integer value from a string as uint64_t.
Parameters
res Stores result
base Base of the number to extract
len Number of bytes to extract (23 max or 0 for unbounded)
len Number of bytes to extract (23 max)
str String to extract from
Returns
n Number of bytes extracted on success
-1 On error
Definition at line 191 of file util-byte.c.
References ByteExtractString().
Referenced by DetectByteExtractDoMatch(), DetectBytejumpDoMatch(), DetectBytejumpMatch(), DetectBytetestDoMatch(), and DetectBytetestParse().
int ByteExtractStringUint8 (uint8_t * res, int base, uint16_t len, const char * str)
Extract unsigned integer value from a string as uint8_t.
Parameters
res Stores result
base Base of the number to extract
len Number of bytes to extract (23 max or 0 for unbounded)
str String to extract from
Returns
n Number of bytes extracted on success
-1 On error
Definition at line 238 of file util-byte.c.
References ByteExtractString(), SC_ERR_NUMERIC_VALUE_ERANGE, and SCLogError.
Referenced by DetectICodeParse(), DetectITypeParse(), and DetectProtoParse().
int ByteExtractUint16 (uint16_t * res, int e, uint16_t len, const uint8_t * bytes)
Extract bytes from a byte string and convert to a unint16_t.
Parameters
res Stores result
e Endianness (BYTE_BIG_ENDIAN or BYTE_LITTLE_ENDIAN)
len Number of bytes to extract (8 max)
bytes Data to extract from
Returns
n Number of bytes extracted on success
-1 On error
Todo:
Need standard return values
Definition at line 116 of file util-byte.c.
int ByteExtractUint32 (uint32_t * res, int e, uint16_t len, const uint8_t * bytes)
Extract bytes from a byte string and convert to a unint32_t.
Parameters
res Stores result
e Endianness (BYTE_BIG_ENDIAN or BYTE_LITTLE_ENDIAN)
len Number of bytes to extract (8 max)
bytes Data to extract from
Returns
n Number of bytes extracted on success
-1 On error
Todo:
Need standard return values
Definition at line 95 of file util-byte.c.
int ByteExtractUint64 (uint64_t * res, int e, uint16_t len, const uint8_t * bytes)
Extract bytes from a byte string and convert to a unint64_t.
Parameters
res Stores result
e Endianness (BYTE_BIG_ENDIAN or BYTE_LITTLE_ENDIAN)
len Number of bytes to extract (8 max)
bytes Data to extract from
Returns
n Number of bytes extracted on success
-1 On error
Todo:
Need standard return values
Definition at line 74 of file util-byte.c.
Referenced by DetectByteExtractDoMatch(), DetectBytejumpDoMatch(), DetectBytejumpMatch(), and DetectBytetestDoMatch().
void ByteRegisterTests (void)
Definition at line 607 of file util-byte.c.
Referenced by RunUnittests().
char* BytesToString (const uint8_t * bytes, size_t nbytes)
Turn byte array into string.
All non-printables are copied over, except for '\0', which is turned into literal \0 in the string.
Parameters
bytes byte array
nbytes number of bytes
Returns
string nul-terminated string or NULL on error
Definition at line 40 of file util-byte.c.
References SCCalloc.