suricata: src/util-mpm-ac-gfbs.h File Reference
util-mpm-ac-gfbs.h File Reference
Data Structures
struct SCACGfbsPattern_
struct SCACGfbsPatternList_
struct SCACGfbsOutputTable_
struct SCACGfbsGotoTableMod_
struct SCACGfbsCtx_
struct SCACGfbsThreadCtx_
Macros
#define SC_AC_GFBS_STATE_TYPE_U16 uint16_t
#define SC_AC_GFBS_STATE_TYPE_U32 uint32_t
Typedefs
typedef struct SCACGfbsPattern_ SCACGfbsPattern
typedef struct SCACGfbsPatternList_ SCACGfbsPatternList
typedef struct SCACGfbsOutputTable_ SCACGfbsOutputTable
typedef struct
SCACGfbsGotoTableMod_ SCACGfbsGotoTableMod_
typedef struct SCACGfbsCtx_ SCACGfbsCtx
typedef struct SCACGfbsThreadCtx_ SCACGfbsThreadCtx
Functions
void MpmACGfbsRegister (void)
Register the goto failure table based aho-corasick mpm.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-mpm-ac-gfbs.h.
Macro Definition Documentation
#define SC_AC_GFBS_STATE_TYPE_U16 uint16_t
Definition at line 25 of file util-mpm-ac-gfbs.h.
Referenced by SCACGfbsDestroyCtx().
#define SC_AC_GFBS_STATE_TYPE_U32 uint32_t
Definition at line 26 of file util-mpm-ac-gfbs.h.
Referenced by SCACGfbsDestroyCtx().
Typedef Documentation
typedef struct SCACGfbsCtx_ SCACGfbsCtx
typedef struct SCACGfbsGotoTableMod_ SCACGfbsGotoTableMod_
typedef struct SCACGfbsOutputTable_ SCACGfbsOutputTable
typedef struct SCACGfbsPattern_ SCACGfbsPattern
typedef struct SCACGfbsPatternList_ SCACGfbsPatternList
typedef struct SCACGfbsThreadCtx_ SCACGfbsThreadCtx
Function Documentation
void MpmACGfbsRegister (void)
Register the goto failure table based aho-corasick mpm.
Definition at line 91 of file util-mpm-ac-gfbs.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, MPM_AC_GFBS, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, SCACGfbsAddPatternCI(), SCACGfbsAddPatternCS(), SCACGfbsDestroyCtx(), SCACGfbsDestroyThreadCtx(), SCACGfbsInitCtx(), SCACGfbsInitThreadCtx(), SCACGfbsPreparePatterns(), SCACGfbsPrintInfo(), SCACGfbsPrintSearchStats(), SCACGfbsRegisterTests(), SCACGfbsSearch(), and MpmTableElmt_::Search.
Referenced by MpmTableSetup().