suricata: src/util-mpm-b2g.c File Reference
util-mpm-b2g.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "detect.h"
#include "util-bloomfilter.h"
#include "util-mpm-b2g.h"
#include "util-print.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-memcmp.h"
#include "util-memcpy.h"
#include "conf.h"
Macros
#define INIT_HASH_SIZE 65536
#define COUNT(counter)
#define B2G_HASH16(a, b) (((a) << b2g_hash_shift) | (b))
Functions
void B2gInitCtx (MpmCtx *)
void B2gThreadInitCtx (MpmCtx *, MpmThreadCtx *, uint32_t)
void B2gDestroyCtx (MpmCtx *)
void B2gThreadDestroyCtx (MpmCtx *, MpmThreadCtx *)
int B2gAddPatternCI (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
int B2gAddPatternCS (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
int B2gPreparePatterns (MpmCtx *mpm_ctx)
uint32_t B2gSearchWrap (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *, uint8_t *buf, uint16_t buflen)
uint32_t B2gSearch1 (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *, uint8_t *buf, uint16_t buflen)
uint32_t B2gSearch (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *, uint8_t *buf, uint16_t buflen)
uint32_t B2gSearchBNDMq (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *pmq, uint8_t *buf, uint16_t buflen)
void B2gPrintInfo (MpmCtx *mpm_ctx)
void B2gPrintSearchStats (MpmThreadCtx *mpm_thread_ctx)
void B2gRegisterTests (void)
void MpmB2gRegister (void)
void B2gFreePattern (MpmCtx *mpm_ctx, B2gPattern *p)
int B2gBuildMatchArray (MpmCtx *mpm_ctx)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implementation of the SBNDMq pattern matching algorithm.
Ideas:
B2g does a full match in the search of up to 'm' characters, in case of a case insensitive search we could say it's match if the pattern is of len 'm' or just compare the rest of the chars.
Todo:
Try to get the S0 calculation right.
Definition in file util-mpm-b2g.c.
Macro Definition Documentation
#define B2G_HASH16 (a, b) (((a) << b2g_hash_shift) | (b))
Definition at line 62 of file util-mpm-b2g.c.
Referenced by B2gBuildMatchArray(), B2gSearch(), and B2gSearchBNDMq().
#define COUNT (counter)
Definition at line 54 of file util-mpm-b2g.c.
Referenced by B2gSearch(), and B2gSearchBNDMq().
#define INIT_HASH_SIZE 65536
Definition at line 48 of file util-mpm-b2g.c.
Referenced by B2gDestroyCtx(), B2gInitCtx(), and B2gPreparePatterns().
Function Documentation
int B2gAddPatternCI (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 421 of file util-mpm-b2g.c.
References MPM_PATTERN_FLAG_NOCASE.
Referenced by MpmB2gRegister().
int B2gAddPatternCS (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 428 of file util-mpm-b2g.c.
Referenced by MpmB2gRegister().
int B2gBuildMatchArray (MpmCtx * mpm_ctx)
Definition at line 630 of file util-mpm-b2g.c.
References B2gCtx_::B2G, B2G_HASH16, B2G_Q, B2G_TYPE, B2gPattern_::ci, MpmCtx_::ctx, B2gCtx_::hash_size, B2gPattern_::len, B2gCtx_::m, MpmCtx_::memory_cnt, MpmCtx_::memory_size, B2gCtx_::parray, MpmCtx_::pattern_cnt, B2gCtx_::s0, SCEnter, SCLogDebug, SCMalloc, SCReturnInt, and u8_tolower.
Referenced by B2gPreparePatterns().
void B2gDestroyCtx (MpmCtx * mpm_ctx)
Definition at line 864 of file util-mpm-b2g.c.
References B2gCtx_::B2G, B2G_TYPE, B2gFreePattern(), B2gCtx_::bloom, BloomFilterFree(), BloomFilterMemoryCnt(), BloomFilterMemorySize(), MpmCtx_::ctx, B2gCtx_::hash, B2gCtx_::hash_size, B2gCtx_::init_hash, INIT_HASH_SIZE, MpmCtx_::memory_cnt, MpmCtx_::memory_size, B2gCtx_::parray, MpmCtx_::pattern_cnt, B2gCtx_::pminlen, SCFree, and SCLogDebug.
Referenced by MpmB2gRegister().
void B2gFreePattern (MpmCtx * mpm_ctx, B2gPattern * p)
Definition at line 267 of file util-mpm-b2g.c.
References B2gPattern_::ci, B2gPattern_::cs, B2gPattern_::len, MpmCtx_::memory_cnt, MpmCtx_::memory_size, B2gPattern_::original_pat, SCFree, B2gPattern_::sids, B2gPattern_::sids_size, and SigIntId.
Referenced by B2gDestroyCtx().
void B2gInitCtx (MpmCtx * mpm_ctx)
Definition at line 825 of file util-mpm-b2g.c.
References MpmCtx_::ctx, B2gCtx_::init_hash, INIT_HASH_SIZE, MpmCtx_::memory_cnt, MpmCtx_::memory_size, SCLogDebug, SCMalloc, SCReturn, and B2gCtx_::Search.
Referenced by MpmB2gRegister().
int B2gPreparePatterns (MpmCtx * mpm_ctx)
Definition at line 664 of file util-mpm-b2g.c.
References B2G_WORD_SIZE, B2gBuildMatchArray(), B2gSearch1(), MpmCtx_::ctx, B2gCtx_::hash_size, B2gCtx_::init_hash, INIT_HASH_SIZE, B2gCtx_::m, B2gCtx_::MBSearch, B2gCtx_::MBSearch2, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmCtx_::minlen, B2gPattern_::next, B2gCtx_::parray, B2gCtx_::pat_1_cnt, MpmCtx_::pattern_cnt, SCFree, SCLogDebug, SCMalloc, and B2gCtx_::Search.
Referenced by MpmB2gRegister().
void B2gPrintInfo (MpmCtx * mpm_ctx)
Definition at line 116 of file util-mpm-b2g.c.
References MpmCtx_::ctx, B2gCtx_::hash_size, MpmCtx_::maxlen, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmCtx_::minlen, and MpmCtx_::pattern_cnt.
Referenced by MpmB2gRegister().
void B2gPrintSearchStats (MpmThreadCtx * mpm_thread_ctx)
Definition at line 731 of file util-mpm-b2g.c.
References MpmThreadCtx_::ctx.
Referenced by B2gThreadDestroyCtx(), and MpmB2gRegister().
void B2gRegisterTests (void)
Definition at line 2796 of file util-mpm-b2g.c.
Referenced by MpmB2gRegister().
uint32_t B2gSearch (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 1102 of file util-mpm-b2g.c.
References B2gCtx_::B2G, B2G_HASH16, B2G_TYPE, B2gCtx_::bloom, COUNT, MpmThreadCtx_::ctx, MpmCtx_::ctx, B2gCtx_::hash, len, B2gCtx_::m, m, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), B2gPattern_::next, PatternMatcherQueue_::pattern_id_bitarray_size, B2gCtx_::pminlen, SCMemcmp, and u8_tolower.
uint32_t B2gSearch1 (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 1286 of file util-mpm-b2g.c.
References B2gPattern_::ci, B2gPattern_::cs, MpmCtx_::ctx, B2gPattern_::flags, B2gCtx_::hash1, B2gPattern_::id, B2gPattern_::len, B2gCtx_::MBSearch, B2gCtx_::MBSearch2, MPM_PATTERN_FLAG_NOCASE, MPM_PATTERN_ONE_BYTE, MpmVerifyMatch(), B2gPattern_::next, B2gCtx_::pat_x_cnt, PatternMatcherQueue_::pattern_id_bitarray_size, SCEnter, SCReturnUInt, B2gPattern_::sids, B2gPattern_::sids_size, and u8_tolower.
Referenced by B2gPreparePatterns().
uint32_t B2gSearchBNDMq (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 976 of file util-mpm-b2g.c.
References B2gCtx_::B2G, B2G_HASH16, B2G_Q, B2G_TYPE, B2gCtx_::bloom, B2gPattern_::ci, COUNT, B2gPattern_::cs, MpmThreadCtx_::ctx, MpmCtx_::ctx, B2gCtx_::hash, B2gPattern_::len, B2gCtx_::m, m, MPM_PATTERN_FLAG_NOCASE, MpmVerifyMatch(), B2gPattern_::next, PatternMatcherQueue_::pattern_id_bitarray_size, B2gCtx_::pminlen, prt(), SCLogDebug, SCMemcmp, and u8_tolower.
uint32_t B2gSearchWrap (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
Definition at line 970 of file util-mpm-b2g.c.
References MpmCtx_::ctx, and B2gCtx_::Search.
Referenced by MpmB2gRegister().
void B2gThreadDestroyCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx)
Definition at line 957 of file util-mpm-b2g.c.
References B2gPrintSearchStats(), MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, and SCFree.
Referenced by MpmB2gRegister().
void B2gThreadInitCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, uint32_t matchsize)
Definition at line 940 of file util-mpm-b2g.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, and SCMalloc.
Referenced by MpmB2gRegister().
void MpmB2gRegister (void)
Definition at line 84 of file util-mpm-b2g.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, B2G_WORD_SIZE, B2gAddPatternCI(), B2gAddPatternCS(), B2gDestroyCtx(), B2gInitCtx(), B2gPreparePatterns(), B2gPrintInfo(), B2gPrintSearchStats(), B2gRegisterTests(), B2gSearchWrap(), B2gThreadDestroyCtx(), B2gThreadInitCtx(), MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, MPM_B2G, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, and MpmTableElmt_::Search.
Referenced by MpmTableSetup().