suricata: src/util-profiling-keywords.c File Reference
util-profiling-keywords.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "conf.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-byte.h"
#include "util-profiling.h"
#include "util-profiling-locks.h"
Data Structures
struct SCProfileKeywordData_
struct SCProfileKeywordDetectCtx_
Typedefs
typedef struct
SCProfileKeywordData_ SCProfileKeywordData
typedef struct
SCProfileKeywordDetectCtx_ SCProfileKeywordDetectCtx
Functions
void SCProfilingKeywordsGlobalInit (void)
void DoDump (SCProfileKeywordDetectCtx *rules_ctx, FILE *fp, const char *name)
void SCProfilingKeywordDump (DetectEngineCtx *de_ctx)
void SCProfilingKeywordUpdateCounter (DetectEngineThreadCtx *det_ctx, int id, uint64_t ticks, int match)
Update a rule counter.
SCProfileKeywordDetectCtx * SCProfilingKeywordInitCtx (void)
void SCProfilingKeywordDestroyCtx (DetectEngineCtx *de_ctx)
void SCProfilingKeywordThreadSetup (SCProfileKeywordDetectCtx *ctx, DetectEngineThreadCtx *det_ctx)
void SCProfilingKeywordThreadCleanup (DetectEngineThreadCtx *det_ctx)
void SCProfilingKeywordInitCounters (DetectEngineCtx *de_ctx)
Register the keyword profiling counters.
Variables
int profiling_keyword_enabled = 0
__thread int profiling_keyword_entered = 0
Detailed Description
Author
Endace Technology Limited.
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
An API for rule profiling operations.
Definition in file util-profiling-keywords.c.
Typedef Documentation
typedef struct SCProfileKeywordData_ SCProfileKeywordData
Extra data for rule profiling.
typedef struct SCProfileKeywordDetectCtx_ SCProfileKeywordDetectCtx
Function Documentation
void DoDump (SCProfileKeywordDetectCtx * rules_ctx, FILE * fp, const char * name)
Definition at line 103 of file util-profiling-keywords.c.
References SCProfileKeywordData_::checks, SCProfileKeywordDetectCtx_::data, DETECT_TBLSIZE, SCProfileKeywordData_::matches, SCProfileKeywordData_::max, sigmatch_table, SCProfileKeywordData_::ticks_match, and SCProfileKeywordData_::ticks_no_match.
Referenced by SCProfilingKeywordDump().
void SCProfilingKeywordDestroyCtx (DetectEngineCtx * de_ctx)
Definition at line 275 of file util-profiling-keywords.c.
References DETECT_SM_LIST_MAX, DetectEngineCtx_::profile_keyword_ctx, DetectEngineCtx_::profile_keyword_ctx_per_list, and SCProfilingKeywordDump().
Referenced by DetectEngineCtxFree().
void SCProfilingKeywordDump (DetectEngineCtx * de_ctx)
Definition at line 155 of file util-profiling-keywords.c.
References SCProfileKeywordData_::checks, SCProfileKeywordDetectCtx_::data, DETECT_SM_LIST_MAX, DETECT_TBLSIZE, DetectSigmatchListEnumToString(), DoDump(), DetectEngineCtx_::profile_keyword_ctx, DetectEngineCtx_::profile_keyword_ctx_per_list, profiling_file_name, profiling_keyword_enabled, SC_ERR_FOPEN, SCLocalTime(), SCLogDebug, SCLogError, and SCLogInfo.
Referenced by SCProfilingKeywordDestroyCtx().
void SCProfilingKeywordInitCounters (DetectEngineCtx * de_ctx)
Register the keyword profiling counters.
Parameters
de_ctx The active DetectEngineCtx, used to get at the loaded rules.
Definition at line 366 of file util-profiling-keywords.c.
References BUG_ON, SCProfileKeywordDetectCtx_::data, DETECT_SM_LIST_MAX, DetectEngineCtx_::profile_keyword_ctx, DetectEngineCtx_::profile_keyword_ctx_per_list, profiling_keyword_enabled, SCLogInfo, SCMalloc, and SCProfilingKeywordInitCtx().
SCProfileKeywordDetectCtx* SCProfilingKeywordInitCtx (void)
Definition at line 249 of file util-profiling-keywords.c.
References SCProfileKeywordDetectCtx_::data_m, SC_ERR_MUTEX, SCLogError, and SCMalloc.
Referenced by SCProfilingKeywordInitCounters().
void SCProfilingKeywordsGlobalInit (void)
Definition at line 69 of file util-profiling-keywords.c.
References ConfGetNode(), ConfigGetLogDirectory(), ConfNodeChildValueIsTrue(), ConfNodeLookupChildValue(), ConfValIsTrue(), profiling_file_name, profiling_keyword_enabled, SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, and unlikely.
void SCProfilingKeywordThreadCleanup (DetectEngineThreadCtx * det_ctx)
Definition at line 340 of file util-profiling-keywords.c.
References SCProfileKeywordDetectCtx_::data_m, DetectEngineThreadCtx_::de_ctx, DETECT_SM_LIST_MAX, DetectEngineThreadCtx_::keyword_perf_data, DetectEngineThreadCtx_::keyword_perf_data_per_list, DetectEngineCtx_::profile_keyword_ctx, and SCFree.
Referenced by DetectEngineThreadCtxFree().
void SCProfilingKeywordThreadSetup (SCProfileKeywordDetectCtx * ctx, DetectEngineThreadCtx * det_ctx)
Definition at line 288 of file util-profiling-keywords.c.
References DETECT_SM_LIST_MAX, DETECT_TBLSIZE, DetectEngineThreadCtx_::keyword_perf_data, DetectEngineThreadCtx_::keyword_perf_data_per_list, and SCMalloc.
void SCProfilingKeywordUpdateCounter (DetectEngineThreadCtx * det_ctx, int id, uint64_t ticks, int match)
Update a rule counter.
Parameters
id The ID of this counter.
ticks Number of CPU ticks for this rule.
match Did the rule match?
Definition at line 220 of file util-profiling-keywords.c.
References SCProfileKeywordData_::checks, DETECT_SM_LIST_MAX, DETECT_TBLSIZE, DetectEngineThreadCtx_::keyword_perf_data, DetectEngineThreadCtx_::keyword_perf_data_per_list, DetectEngineThreadCtx_::keyword_perf_list, SCProfileKeywordData_::matches, SCProfileKeywordData_::max, SCProfileKeywordData_::ticks_match, and SCProfileKeywordData_::ticks_no_match.
Variable Documentation
int profiling_keyword_enabled = 0
Definition at line 64 of file util-profiling-keywords.c.
Referenced by SCProfilingKeywordDump(), SCProfilingKeywordInitCounters(), and SCProfilingKeywordsGlobalInit().
__thread int profiling_keyword_entered = 0
Definition at line 65 of file util-profiling-keywords.c.