suricata: src/util-checksum.h File Reference
util-checksum.h File Reference
Macros
#define CHECKSUM_SAMPLE_COUNT 1000
#define CHECKSUM_INVALID_RATIO 10
Functions
int ReCalculateChecksum (Packet *p)
int ChecksumAutoModeCheck (uint32_t thread_count, unsigned int iface_count, unsigned int iface_fail)
Check if the number of invalid checksums indicate checksum offloading in place.
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file util-checksum.h.
Macro Definition Documentation
#define CHECKSUM_INVALID_RATIO 10
Definition at line 34 of file util-checksum.h.
Referenced by ChecksumAutoModeCheck(), and ReceivePcapFileThreadExitStats().
#define CHECKSUM_SAMPLE_COUNT 1000
Definition at line 33 of file util-checksum.h.
Referenced by ChecksumAutoModeCheck(), and ReceivePcapFileThreadExitStats().
Function Documentation
int ChecksumAutoModeCheck (uint32_t thread_count, unsigned int iface_count, unsigned int iface_fail)
Check if the number of invalid checksums indicate checksum offloading in place.
Return values
1 yes, offloading in place
0 no, no offloading used
Definition at line 70 of file util-checksum.c.
References CHECKSUM_INVALID_RATIO, CHECKSUM_SAMPLE_COUNT, and SCLogInfo.
Referenced by AFPRead(), AFPReadFromRing(), PcapCallbackLoop(), and PcapFileCallbackLoop().
int ReCalculateChecksum (Packet * p)
Definition at line 30 of file util-checksum.c.
References Packet_::ip4h, Packet_::ip6h, IPV4_GET_RAW_HLEN, Packet_::payload_len, PKT_IS_IPV4, PKT_IS_IPV6, PKT_IS_TCP, PKT_IS_UDP, TCP_GET_HLEN, Packet_::tcph, UDP_HEADER_LEN, and Packet_::udph.
Referenced by DetectReplaceExecuteInternal(), and StreamTcpPacket().