suricata: src/util-mpm-ac.h File Reference
util-mpm-ac.h File Reference
Data Structures
struct SCACPattern_
struct SCACPatternList_
struct SCACOutputTable_
struct SCACCtx_
struct SCACThreadCtx_
Macros
#define SC_AC_STATE_TYPE_U16 uint16_t
#define SC_AC_STATE_TYPE_U32 uint32_t
Typedefs
typedef struct SCACPattern_ SCACPattern
typedef struct SCACPatternList_ SCACPatternList
typedef struct SCACOutputTable_ SCACOutputTable
typedef struct SCACCtx_ SCACCtx
typedef struct SCACThreadCtx_ SCACThreadCtx
Functions
void MpmACRegister (void)
Register the aho-corasick mpm.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-mpm-ac.h.
Macro Definition Documentation
#define SC_AC_STATE_TYPE_U16 uint16_t
Definition at line 28 of file util-mpm-ac.h.
Referenced by SCACDestroyCtx(), and SCACSearch().
#define SC_AC_STATE_TYPE_U32 uint32_t
Definition at line 29 of file util-mpm-ac.h.
Referenced by SCACDestroyCtx(), and SCACSearch().
Typedef Documentation
typedef struct SCACCtx_ SCACCtx
typedef struct SCACOutputTable_ SCACOutputTable
typedef struct SCACPattern_ SCACPattern
typedef struct SCACPatternList_ SCACPatternList
typedef struct SCACThreadCtx_ SCACThreadCtx
Function Documentation
void MpmACRegister (void)
Register the aho-corasick mpm.
Definition at line 2226 of file util-mpm-ac.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, MPM_AC, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, SCACAddPatternCI(), SCACAddPatternCS(), SCACDestroyCtx(), SCACDestroyThreadCtx(), SCACInitCtx(), SCACInitThreadCtx(), SCACPreparePatterns(), SCACPrintInfo(), SCACPrintSearchStats(), SCACRegisterTests(), SCACSearch(), and MpmTableElmt_::Search.
Referenced by MpmTableSetup().