suricata: src/util-file.h File Reference
util-file.h File Reference
Data Structures
struct FileData_
struct File_
struct FileContainer_
Macros
#define FILE_TRUNCATED 0x0001
#define FILE_NOMAGIC 0x0002
#define FILE_NOMD5 0x0004
#define FILE_MD5 0x0008
#define FILE_LOGGED 0x0010
#define FILE_NOSTORE 0x0020
#define FILE_STORE 0x0040
#define FILE_STORED 0x0080
#define FILE_NOTRACK 0x0100
Typedefs
typedef enum FileState_ FileState
typedef struct FileData_ FileData
typedef struct File_ File
typedef struct FileContainer_ FileContainer
Enumerations
enum FileState_ {
FILE_STATE_NONE = 0, FILE_STATE_OPENED, FILE_STATE_CLOSED, FILE_STATE_TRUNCATED,
FILE_STATE_ERROR, FILE_STATE_MAX
}
Functions
FileContainer * FileContainerAlloc ()
allocate a FileContainer
void FileContainerFree (FileContainer *)
Free a FileContainer.
void FileContainerRecycle (FileContainer *)
Recycle a FileContainer.
void FileContainerAdd (FileContainer *, File *)
File * FileOpenFile (FileContainer *, uint8_t *name, uint16_t name_len, uint8_t *data, uint32_t data_len, uint8_t flags)
Open a new File.
int FileCloseFile (FileContainer *, uint8_t *data, uint32_t data_len, uint8_t flags)
Close a File.
int FileAppendData (FileContainer *, uint8_t *data, uint32_t data_len)
Store a chunk of file data in the flow. The open "flowfile" will be used.
int FileStore (File *)
Tag a file for storing.
int FileSetTx (File *, uint64_t txid)
Set the TX id for a file.
void FileDisableStoring (struct Flow_ *, uint8_t)
disable file storage for a flow
void FileDisableFilesize (Flow *f, uint8_t direction)
disable file size tracking for this flow
void FileDisableStoringForTransaction (Flow *f, uint8_t direction, uint64_t tx_id)
disable file storing for a transaction
void FlowFileDisableStoringForTransaction (struct Flow_ *f, uint16_t tx_id)
void FilePrune (FileContainer *ffc)
void FileDisableMagic (Flow *f, uint8_t)
disable file magic lookups for this flow
void FileForceMagicEnable (void)
int FileForceMagic (void)
void FileDisableMd5 (Flow *f, uint8_t)
disable file md5 calc for this flow
void FileForceMd5Enable (void)
int FileForceMd5 (void)
void FileForceTrackingEnable (void)
void FileStoreAllFiles (FileContainer *)
void FileStoreAllFilesForTx (FileContainer *, uint16_t)
void FileStoreFileById (FileContainer *fc, uint16_t)
flag a file with id "file_id" to be stored.
void FileTruncateAllOpenFiles (FileContainer *)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-file.h.
Macro Definition Documentation
#define FILE_LOGGED 0x0010
Definition at line 36 of file util-file.h.
#define FILE_MD5 0x0008
Definition at line 35 of file util-file.h.
#define FILE_NOMAGIC 0x0002
Definition at line 33 of file util-file.h.
Referenced by FileDisableMagic(), FileOpenFile(), HTPFileOpen(), and SMTPProcessDataChunk().
#define FILE_NOMD5 0x0004
Definition at line 34 of file util-file.h.
Referenced by FileDisableMd5(), FileOpenFile(), HTPFileOpen(), and SMTPProcessDataChunk().
#define FILE_NOSTORE 0x0020
Definition at line 37 of file util-file.h.
Referenced by FileAppendData(), FileDisableStoring(), FileDisableStoringForFile(), FileOpenFile(), HTPFileOpen(), and SMTPProcessDataChunk().
#define FILE_NOTRACK 0x0100
track size of file
Definition at line 40 of file util-file.h.
Referenced by FileAppendData(), and FileDisableFilesize().
#define FILE_STORE 0x0040
Definition at line 38 of file util-file.h.
Referenced by FileDisableStoring(), FileDisableStoringForTransaction(), FileOpenFile(), FileStore(), FileStoreAllFiles(), FileStoreAllFilesForTx(), FileStoreFileById(), HTPFileOpen(), and SMTPProcessDataChunk().
#define FILE_STORED 0x0080
Definition at line 39 of file util-file.h.
#define FILE_TRUNCATED 0x0001
Definition at line 32 of file util-file.h.
Referenced by HtpRequestBodyHandleMultipart().
Typedef Documentation
typedef struct File_ File
typedef struct FileContainer_ FileContainer
typedef struct FileData_ FileData
typedef enum FileState_ FileState
Enumeration Type Documentation
enum FileState_
Enumerator
FILE_STATE_NONE
no state
FILE_STATE_OPENED
flow file is opened
FILE_STATE_CLOSED
flow file is completed, there will be no more data.
FILE_STATE_TRUNCATED
flow file is not complete, but there will be no more data.
FILE_STATE_ERROR
file is in an error state
FILE_STATE_MAX
Definition at line 42 of file util-file.h.
Function Documentation
int FileAppendData (FileContainer * ffc, uint8_t * data, uint32_t data_len)
Store a chunk of file data in the flow. The open "flowfile" will be used.
Parameters
ffc the container
data data chunk
data_len data chunk len
Return values
0 ok
-1 error
Parameters
ffc the container
data data chunk
data_len data chunk len
Return values
0 ok
-1 error
-2 no store for this file
Definition at line 453 of file util-file.c.
References File_::chunks_head, FILE_NOSTORE, FILE_NOTRACK, FILE_STATE_ERROR, FILE_STATE_OPENED, FILE_STATE_TRUNCATED, File_::flags, SCEnter, SCLogDebug, SCReturnInt, File_::size, File_::state, FileData_::stream_offset, and FileContainer_::tail.
Referenced by HTPFileStoreChunk(), and SMTPProcessDataChunk().
int FileCloseFile (FileContainer * ffc, uint8_t * data, uint32_t data_len, uint8_t flags)
Close a File.
Parameters
ffc the container
data final data if any
data_len data len if any
flags flags
Return values
0 ok
-1 error
Definition at line 664 of file util-file.c.
References SCEnter, SCReturnInt, and FileContainer_::tail.
Referenced by HTPFileClose(), and SMTPProcessDataChunk().
void FileContainerAdd (FileContainer * , File *)
Definition at line 379 of file util-file.c.
References FileContainer_::head, File_::next, and FileContainer_::tail.
Referenced by FileOpenFile().
FileContainer* FileContainerAlloc (void)
allocate a FileContainer
Return values
new newly allocated FileContainer
NULL error
Definition at line 218 of file util-file.c.
References SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, and unlikely.
Referenced by HTPFileOpen(), and SMTPProcessDataChunk().
void FileContainerFree (FileContainer * ffc)
Free a FileContainer.
Parameters
ffc FileContainer
Definition at line 254 of file util-file.c.
References FileContainer_::head, File_::next, next, SCFree, and FileContainer_::tail.
Referenced by HTPStateFree().
void FileContainerRecycle (FileContainer * ffc)
Recycle a FileContainer.
Parameters
ffc FileContainer
Definition at line 235 of file util-file.c.
References FileContainer_::head, File_::next, next, and FileContainer_::tail.
void FileDisableFilesize (Flow * f, uint8_t direction)
disable file size tracking for this flow
Parameters
f LOCKED flow
direction flow direction
Definition at line 788 of file util-file.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), DEBUG_ASSERT_FLOW_LOCKED, FILE_NOTRACK, File_::flags, Flow_::flags, FLOW_FILE_NO_SIZE_TC, FLOW_FILE_NO_SIZE_TS, FileContainer_::head, File_::next, Flow_::proto, SCEnter, SCLogDebug, SCReturn, and STREAM_TOSERVER.
Referenced by SigMatchSignatures().
void FileDisableMagic (Flow * f, uint8_t direction)
disable file magic lookups for this flow
Parameters
f LOCKED flow
direction flow direction
Definition at line 718 of file util-file.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), DEBUG_ASSERT_FLOW_LOCKED, FILE_NOMAGIC, File_::flags, Flow_::flags, FLOW_FILE_NO_MAGIC_TC, FLOW_FILE_NO_MAGIC_TS, FileContainer_::head, File_::next, Flow_::proto, SCEnter, SCLogDebug, SCReturn, and STREAM_TOSERVER.
Referenced by SigMatchSignatures().
void FileDisableMd5 (Flow * f, uint8_t direction)
disable file md5 calc for this flow
Parameters
f LOCKED flow
direction flow direction
Definition at line 749 of file util-file.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), DEBUG_ASSERT_FLOW_LOCKED, FILE_NOMD5, File_::flags, Flow_::flags, FLOW_FILE_NO_MD5_TC, FLOW_FILE_NO_MD5_TS, FileContainer_::head, File_::next, Flow_::proto, SCEnter, SCLogDebug, SCReturn, and STREAM_TOSERVER.
Referenced by SigMatchSignatures().
void FileDisableStoring (Flow * f, uint8_t direction)
disable file storage for a flow
Parameters
f LOCKED flow
f LOCKED flow
direction flow direction
Definition at line 686 of file util-file.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), DEBUG_ASSERT_FLOW_LOCKED, FILE_NOSTORE, FILE_STORE, File_::flags, Flow_::flags, FLOW_FILE_NO_STORE_TC, FLOW_FILE_NO_STORE_TS, FileContainer_::head, File_::next, Flow_::proto, SCEnter, SCLogDebug, SCReturn, and STREAM_TOSERVER.
Referenced by SigMatchSignatures().
void FileDisableStoringForTransaction (Flow * f, uint8_t direction, uint64_t tx_id)
disable file storing for a transaction
Parameters
f flow
tx_id transaction id
disable file storing for a transaction
Parameters
f LOCKED flow
direction flow direction
tx_id transaction id
Definition at line 845 of file util-file.c.
References Flow_::alproto, Flow_::alstate, AppLayerParserGetFiles(), DEBUG_ASSERT_FLOW_LOCKED, FILE_STORE, FileDisableStoringForFile(), File_::flags, FileContainer_::head, File_::next, Flow_::proto, SCEnter, SCLogDebug, SCReturn, and File_::txid.
int FileForceMagic (void)
Definition at line 68 of file util-file.c.
Referenced by SigMatchSignatures().
void FileForceMagicEnable (void)
Definition at line 58 of file util-file.c.
int FileForceMd5 (void)
Definition at line 73 of file util-file.c.
Referenced by SigMatchSignatures().
void FileForceMd5Enable (void)
Definition at line 63 of file util-file.c.
void FileForceTrackingEnable (void)
Definition at line 78 of file util-file.c.
File* FileOpenFile (FileContainer * ffc, uint8_t * name, uint16_t name_len, uint8_t * data, uint32_t data_len, uint8_t flags)
Open a new File.
Parameters
ffc flow container
name filename character array
name_len filename len
data initial data
data_len initial data len
flags open flags
Return values
ff flowfile object
Note
filename is not a string, so it's not nul terminated.
Definition at line 525 of file util-file.c.
References FILE_NOMAGIC, FILE_NOMD5, FILE_NOSTORE, FILE_STATE_ERROR, FILE_STATE_OPENED, FILE_STORE, FileContainerAdd(), File_::flags, SCEnter, SCLogDebug, SCReturnPtr, File_::size, and File_::state.
Referenced by HTPFileOpen(), and SMTPProcessDataChunk().
void FilePrune (FileContainer * ffc)
Definition at line 190 of file util-file.c.
References BUG_ON, FileContainer_::head, File_::next, and FileContainer_::tail.
Referenced by HTPFileClose(), HTPFileOpen(), HTPFileStoreChunk(), and SMTPProcessDataChunk().
int FileSetTx (File * ff, uint64_t txid)
Set the TX id for a file.
Parameters
ff The file to store
txid the tx id
Definition at line 406 of file util-file.c.
References SCLogDebug, SCReturnInt, and File_::txid.
Referenced by HTPFileOpen().
int FileStore (File * ff)
Tag a file for storing.
Parameters
ff The file to store
Definition at line 394 of file util-file.c.
References FILE_STORE, File_::flags, and SCReturnInt.
void FileStoreAllFiles (FileContainer *)
Definition at line 906 of file util-file.c.
References FILE_STORE, File_::flags, FileContainer_::head, File_::next, and SCEnter.
void FileStoreAllFilesForTx (FileContainer * , uint16_t)
Definition at line 891 of file util-file.c.
References FILE_STORE, File_::flags, FileContainer_::head, File_::next, SCEnter, and File_::txid.
void FileStoreFileById (FileContainer * fc, uint16_t file_id)
flag a file with id "file_id" to be stored.
Parameters
fc file store
file_id the file's id
Definition at line 876 of file util-file.c.
References File_::file_id, FILE_STORE, File_::flags, FileContainer_::head, File_::next, and SCEnter.
Referenced by DetectFilestorePostMatch().
void FileTruncateAllOpenFiles (FileContainer *)
Definition at line 919 of file util-file.c.
References FILE_STATE_OPENED, FileContainer_::head, File_::next, SCEnter, and File_::state.
void FlowFileDisableStoringForTransaction (struct Flow_ * f, uint16_t tx_id)