suricata: src/util-mpm-b3g.h File Reference
util-mpm-b3g.h File Reference
#include "util-mpm.h"
#include "util-bloomfilter.h"
Data Structures
struct B3gPattern_
struct B3gHashItem_
struct B3gCtx_
struct B3gThreadCtx_
Macros
#define B3G_HASHSHIFT_MAX 8
#define B3G_HASHSHIFT_MAX2 5
#define B3G_HASHSHIFT_HIGHER 7
#define B3G_HASHSHIFT_HIGHER2 4
#define B3G_HASHSHIFT_HIGH 6
#define B3G_HASHSHIFT_HIGH2 3
#define B3G_HASHSHIFT_MEDIUM 5
#define B3G_HASHSHIFT_MEDIUM2 2
#define B3G_HASHSHIFT_LOW 4
#define B3G_HASHSHIFT_LOW2 1
#define B3G_HASHSHIFT_LOWEST 3
#define B3G_HASHSHIFT_LOWEST2 1
#define B3G_TYPE uint32_t
#define B3G_WORD_SIZE 32
#define B3G_Q 3
#define B3G_SEARCHFUNC B3gSearchBNDMq
Typedefs
typedef struct B3gPattern_ B3gPattern
typedef struct B3gHashItem_ B3gHashItem
typedef struct B3gCtx_ B3gCtx
typedef struct B3gThreadCtx_ B3gThreadCtx
Functions
void MpmB3gRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-mpm-b3g.h.
Macro Definition Documentation
#define B3G_HASHSHIFT_HIGH 6
Definition at line 34 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_HIGH2 3
Definition at line 35 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_HIGHER 7
Definition at line 32 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_HIGHER2 4
Definition at line 33 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_LOW 4
Definition at line 38 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_LOW2 1
Definition at line 39 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_LOWEST 3
Definition at line 40 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_LOWEST2 1
Definition at line 41 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_MAX 8
Definition at line 30 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_MAX2 5
Definition at line 31 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_MEDIUM 5
Definition at line 36 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_HASHSHIFT_MEDIUM2 2
Definition at line 37 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_Q 3
Definition at line 50 of file util-mpm-b3g.h.
Referenced by B3gBuildMatchArray(), and B3gSearchBNDMq().
#define B3G_SEARCHFUNC B3gSearchBNDMq
Definition at line 53 of file util-mpm-b3g.h.
Referenced by B3gGetConfig().
#define B3G_TYPE uint32_t
Definition at line 43 of file util-mpm-b3g.h.
Referenced by B3gBuildMatchArray(), B3gDestroyCtx(), B3gSearch(), and B3gSearchBNDMq().
#define B3G_WORD_SIZE 32
Definition at line 48 of file util-mpm-b3g.h.
Referenced by B3gPreparePatterns(), and MpmB3gRegister().
Typedef Documentation
typedef struct B3gCtx_ B3gCtx
typedef struct B3gHashItem_ B3gHashItem
typedef struct B3gPattern_ B3gPattern
typedef struct B3gThreadCtx_ B3gThreadCtx
Function Documentation
void MpmB3gRegister (void)
Definition at line 1293 of file util-mpm-b3g.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, B3G_WORD_SIZE, B3gAddPatternCI(), B3gAddPatternCS(), B3gDestroyCtx(), B3gInitCtx(), B3gPreparePatterns(), B3gPrintInfo(), B3gPrintSearchStats(), B3gRegisterTests(), B3gSearchWrap(), B3gThreadDestroyCtx(), B3gThreadInitCtx(), MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, MPM_B3G, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, and MpmTableElmt_::Search.
Referenced by MpmTableSetup().