suricata: src/util-print.c File Reference
util-print.c File Reference
#include "suricata-common.h"
#include "util-print.h"
#include "util-error.h"
#include "util-debug.h"
Macros
#define BUFFER_LENGTH 2048
#define BUFFER_LENGTH 2048
#define s6_addr16 __u6_addr.__u6_addr16
Functions
void PrintBufferRawLineHex (char *nbuf, int *offset, int max_size, uint8_t *buf, uint32_t buflen)
print a buffer as hex on a single line
void PrintRawLineHexBuf (char *retbuf, uint32_t retbuflen, uint8_t *buf, uint32_t buflen)
print a buffer as hex on a single line in to retbuf buffer
void PrintRawJsonFp (FILE *fp, uint8_t *buf, uint32_t buflen)
void PrintRawUriFp (FILE *fp, uint8_t *buf, uint32_t buflen)
void PrintRawUriBuf (char *retbuf, uint32_t *offset, uint32_t retbuflen, uint8_t *buf, uint32_t buflen)
void PrintRawDataFp (FILE *fp, const uint8_t *buf, uint32_t buflen)
void PrintRawDataToBuffer (uint8_t *dst_buf, uint32_t *dst_buf_offset_ptr, uint32_t dst_buf_size, uint8_t *src_buf, uint32_t src_buf_len)
void PrintStringsToBuffer (uint8_t *dst_buf, uint32_t *dst_buf_offset_ptr, uint32_t dst_buf_size, uint8_t *src_buf, uint32_t src_buf_len)
const char * PrintInet (int af, const void *src, char *dst, socklen_t size)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Print utility functions
Definition in file util-print.c.
Macro Definition Documentation
#define BUFFER_LENGTH 2048
Referenced by PrintRawJsonFp(), and PrintRawUriFp().
#define BUFFER_LENGTH 2048
#define s6_addr16 __u6_addr.__u6_addr16
Definition at line 235 of file util-print.c.
Function Documentation
void PrintBufferRawLineHex (char * nbuf, int * offset, int max_size, uint8_t * buf, uint32_t buflen)
print a buffer as hex on a single line
Prints in the format "00 AA BB"
Parameters
nbuf buffer into which the output is written
offset of where to start writting into the buffer
max_size the size of the output buffer
buf buffer to print from
buflen length of the input buffer
Definition at line 42 of file util-print.c.
References PrintBufferData.
Referenced by AlertFastLogger().
const char* PrintInet (int af, const void * src, char * dst, socklen_t size)
Definition at line 260 of file util-print.c.
References inet_ntop(), SC_ERR_INVALID_VALUE, and SCLogError.
Referenced by AddressDebugPrint(), AlertFastLogger(), DecodeIPV4(), DecodeIPV6(), DecodePartialIPV4(), DecodePartialIPV6(), DetectAddressPrint(), IPOnlyPrepare(), SRepLoadFileFromFD(), and TLSGetIPInformations().
void PrintRawDataFp (FILE * fp, const uint8_t * buf, uint32_t buflen)
Definition at line 136 of file util-print.c.
Referenced by AppLayerHandleTCPData(), DetectEngineInspectHttpRequestLine(), DetectEngineInspectPacketUris(), DNSReponseParse(), HtpBodyPrint(), HTPCallbackRequestBodyData(), HtpRequestBodyHandleMultipart(), SCAsn1Decode(), SigMatchSignatures(), and StreamTcpInlineSegmentCompare().
void PrintRawDataToBuffer (uint8_t * dst_buf, uint32_t * dst_buf_offset_ptr, uint32_t dst_buf_size, uint8_t * src_buf, uint32_t src_buf_len)
Definition at line 170 of file util-print.c.
References PrintBufferData.
void PrintRawJsonFp (FILE * fp, uint8_t * buf, uint32_t buflen)
Definition at line 71 of file util-print.c.
References BUFFER_LENGTH, and PrintBufferData.
void PrintRawLineHexBuf (char * retbuf, uint32_t retbuflen, uint8_t * buf, uint32_t buflen)
print a buffer as hex on a single line in to retbuf buffer
Prints in the format "00 AA BB"
Parameters
retbuf pointer to the buffer which will have the result
rebuflen lenght of the buffer
buf buffer to print from
buflen length of the input buffer
Definition at line 61 of file util-print.c.
References PrintBufferData.
void PrintRawUriBuf (char * retbuf, uint32_t * offset, uint32_t retbuflen, uint8_t * buf, uint32_t buflen)
Definition at line 113 of file util-print.c.
References PrintBufferData.
void PrintRawUriFp (FILE * fp, uint8_t * buf, uint32_t buflen)
Definition at line 93 of file util-print.c.
References BUFFER_LENGTH, and PrintBufferData.
Referenced by EngineAnalysisFP().
void PrintStringsToBuffer (uint8_t * dst_buf, uint32_t * dst_buf_offset_ptr, uint32_t dst_buf_size, uint8_t * src_buf, uint32_t src_buf_len)
Definition at line 219 of file util-print.c.
References PrintBufferData.