suricata: src/util-random.c File Reference
util-random.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "threads.h"
#include "util-debug.h"
Functions
unsigned int RandomTimePreseed (void)
create a seed number to pass to rand() , rand_r(), and similars
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Utility function for seeding rand
Definition in file util-random.c.
Function Documentation
unsigned int RandomTimePreseed (void)
create a seed number to pass to rand() , rand_r(), and similars
Return values
seed for rand()
Definition at line 35 of file util-random.c.
Referenced by DefragInitConfig(), FlowInitConfig(), HostInitConfig(), and IPPairInitConfig().