suricata: src/util-spm-bm.c File Reference
util-spm-bm.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "util-spm-bm.h"
#include "util-debug.h"
#include "util-error.h"
#include "util-memcpy.h"
Functions
void BoyerMooreCtxToNocase (BmCtx *bm_ctx, uint8_t *needle, uint16_t needle_len)
Given a BmCtx structure, recreate the pre/suffixes for nocase.
BmCtx * BoyerMooreCtxInit (uint8_t *needle, uint16_t needle_len)
Setup a Booyer Moore context.
BmCtx * BoyerMooreNocaseCtxInit (uint8_t *needle, uint16_t needle_len)
Setup a Booyer Moore context for nocase search.
void BoyerMooreCtxDeInit (BmCtx *bmctx)
Free the memory allocated to Booyer Moore context.
uint8_t * BoyerMoore (uint8_t *x, uint16_t m, uint8_t *y, int32_t n, BmCtx *bm_ctx)
Boyer Moore search algorithm Is better as the pattern length increases and for big buffers to search in. The algorithm needs a context of two arrays already prepared by prep_bad_chars() and prep_good_suffix()
uint8_t * BoyerMooreNocase (uint8_t *x, uint16_t m, uint8_t *y, int32_t n, BmCtx *bm_ctx)
Boyer Moore search algorithm Is better as the pattern length increases and for big buffers to search in. The algorithm needs a context of two arrays already prepared by prep_bad_chars() and prep_good_suffix()
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Boyer Moore simple pattern matcher implementation
Boyer Moore algorithm has a really good performance. It need two arrays of context for each pattern that hold applicable shifts on the text to seach in, based on characters not available in the pattern and combinations of characters that start a sufix of the pattern. If possible, we should store the context of patterns that we are going to search for multiple times, so we don't spend time on rebuilding them.
Definition in file util-spm-bm.c.
Function Documentation
uint8_t* BoyerMoore (uint8_t * x, uint16_t m, uint8_t * y, int32_t n, BmCtx * bm_ctx)
Boyer Moore search algorithm Is better as the pattern length increases and for big buffers to search in. The algorithm needs a context of two arrays already prepared by prep_bad_chars() and prep_good_suffix()
Parameters
y pointer to the buffer to search in
n length limit of the buffer
x pointer to the pattern we ar searching for
m length limit of the needle
bmBc pointer to an array of BoyerMooreSuffixes prepared by prep_good_suffix()
bmGs pointer to an array of bachars prepared by prep_bad_chars()
Return values
ptr to start of the match; NULL if no match
Definition at line 305 of file util-spm-bm.c.
References ALPHABET_SIZE, BmCtx_::bmBc, BmCtx_::bmGs, and m.
Referenced by BoyerMooreSearch(), and DetectEngineContentInspection().
void BoyerMooreCtxDeInit (BmCtx * bmctx)
Free the memory allocated to Booyer Moore context.
Parameters
bmCtx pointer to the Context for the pattern
Definition at line 124 of file util-spm-bm.c.
References BmCtx_::bmGs, SCEnter, SCFree, and SCReturn.
Referenced by BoyerMooreNocaseSearch(), BoyerMooreSearch(), DetectContentFree(), DetectHttpClientBodyFree(), DetectHttpHHFree(), DetectHttpHRHFree(), DetectHttpServerBodyFree(), DetectHttpUAFree(), and DetectUricontentFree().
BmCtx* BoyerMooreCtxInit (uint8_t * needle, uint16_t needle_len)
Setup a Booyer Moore context.
Parameters
str pointer to the pattern string
size length of the string
Return values
BmCtx pointer to the newly created Context for the pattern BoyerMoore contexts should be created at init
Definition at line 76 of file util-spm-bm.c.
References SC_ERR_FATAL, SCLogError, SCMalloc, and unlikely.
Referenced by BoyerMooreNocaseCtxInit(), BoyerMooreSearch(), and DetectContentParse().
void BoyerMooreCtxToNocase (BmCtx * bm_ctx, uint8_t * needle, uint16_t needle_len)
Given a BmCtx structure, recreate the pre/suffixes for nocase.
Return values
BmCtx pointer to the already created BmCtx (with BoyerMooreCtxInit())
Parameters
str pointer to the pattern string
size length of the string
Definition at line 56 of file util-spm-bm.c.
References BmCtx_::bmBc, and BmCtx_::bmGs.
Referenced by BoyerMooreNocaseCtxInit().
uint8_t* BoyerMooreNocase (uint8_t * x, uint16_t m, uint8_t * y, int32_t n, BmCtx * bm_ctx)
Boyer Moore search algorithm Is better as the pattern length increases and for big buffers to search in. The algorithm needs a context of two arrays already prepared by prep_bad_chars() and prep_good_suffix()
Parameters
y pointer to the buffer to search in
n length limit of the buffer
x pointer to the pattern we ar searching for
m length limit of the needle
bmBc pointer to an array of BoyerMooreSuffixes prepared by prep_good_suffix()
bmGs pointer to an array of bachars prepared by prep_bad_chars()
Return values
ptr to start of the match; NULL if no match
Definition at line 354 of file util-spm-bm.c.
References ALPHABET_SIZE, BmCtx_::bmBc, BmCtx_::bmGs, m, and u8_tolower.
Referenced by BoyerMooreNocaseSearch(), and DetectEngineContentInspection().
BmCtx* BoyerMooreNocaseCtxInit (uint8_t * needle, uint16_t needle_len)
Setup a Booyer Moore context for nocase search.
Parameters
str pointer to the pattern string
size length of the string
Return values
BmCtx pointer to the newly created Context for the pattern BoyerMoore contexts should be created at init
Definition at line 110 of file util-spm-bm.c.
References BoyerMooreCtxInit(), and BoyerMooreCtxToNocase().
Referenced by BoyerMooreNocaseSearch().