suricata: src/util-ip.c File Reference
util-ip.c File Reference
#include "suricata-common.h"
Functions
struct in_addr * ValidateIPV4Address (const char *addr_str)
Validates an IPV4 address and returns the network endian arranged version of the IPV4 address.
struct in6_addr * ValidateIPV6Address (const char *addr_str)
Validates an IPV6 address and returns the network endian arranged version of the IPV6 addresss.
void MaskIPNetblock (uint8_t *stream, uint8_t netmask, uint16_t key_bitlen)
Culls the non-netmask portion of the IP address. For example an IP address 192.168.240.1 would be chopped to 192.168.224.0 against a netmask value of 19.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Duarte Silva duart.nosp@m.e.si.nosp@m.lva@s.nosp@m.eria.nosp@m.lizin.nosp@m.g.me
IP addresses related utility functions
Definition in file util-ip.c.
Function Documentation
void MaskIPNetblock (uint8_t * stream, uint8_t netmask, uint16_t key_bitlen)
Culls the non-netmask portion of the IP address. For example an IP address 192.168.240.1 would be chopped to 192.168.224.0 against a netmask value of 19.
Parameters
stream Pointer the IP address that has to be masked
netmask The netmask value (cidr) to which the IP address has to be culled
key_bitlen The bitlen of the stream
Definition at line 94 of file util-ip.c.
Referenced by SCHInfoAddHostOSInfo(), SCReputationAddIPV4Data(), and SCReputationAddIPV6Data().
struct in_addr* ValidateIPV4Address (const char * addr_str)
Validates an IPV4 address and returns the network endian arranged version of the IPV4 address.
Parameters
addr Pointer to a character string containing an IPV4 address. A valid IPV4 address is a character string containing a dotted format of "ddd.ddd.ddd.ddd"
Return values
Pointer to an in_addr instance containing the network endian format of the IPV4 address
NULL if the IPV4 address is invalid
Definition at line 41 of file util-ip.c.
References inet_pton(), SC_ERR_FATAL, SCFree, SCLogError, and SCMalloc.
Referenced by SCHInfoAddHostOSInfo(), and SCHInfoGetHostOSFlavour().
struct in6_addr* ValidateIPV6Address (const char * addr_str)
Validates an IPV6 address and returns the network endian arranged version of the IPV6 addresss.
Parameters
addr Pointer to a character string containing an IPV6 address
Return values
Pointer to a in6_addr instance containing the network endian format of the IPV6 address
NULL if the IPV6 address is invalid
Definition at line 68 of file util-ip.c.
References inet_pton(), SC_ERR_FATAL, SCFree, SCLogError, and SCMalloc.
Referenced by SCHInfoAddHostOSInfo(), and SCHInfoGetHostOSFlavour().