suricata: src/util-logopenfile.h File Reference
util-logopenfile.h File Reference
#include "conf.h"
#include "tm-modules.h"
#include "util-buffer.h"
Data Structures
struct PcieFile
struct SyslogSetup_
struct LogFileCtx_
Macros
#define LOGFILE_RECONN_MIN_TIME 500
#define LOGFILE_HEADER_WRITTEN 0x01
#define LOGFILE_ALERTS_PRINTED 0x02
Typedefs
typedef struct SyslogSetup_ SyslogSetup
typedef struct LogFileCtx_ LogFileCtx
Enumerations
enum LogFileType {
LOGFILE_TYPE_FILE, LOGFILE_TYPE_SYSLOG, LOGFILE_TYPE_UNIX_DGRAM, LOGFILE_TYPE_UNIX_STREAM,
LOGFILE_TYPE_REDIS
}
Functions
LogFileCtx * LogFileNewCtx (void)
LogFileNewCtx() Get a new LogFileCtx.
int LogFileFreeCtx (LogFileCtx *)
LogFileFreeCtx() Destroy a LogFileCtx (Close the file and free memory)
int LogFileWrite (LogFileCtx *file_ctx, MemBuffer *buffer)
int SCConfLogOpenGeneric (ConfNode *conf, LogFileCtx *, const char *, int)
open a generic output "log file", which may be a regular file or a socket
int SCConfLogOpenRedis (ConfNode *conf, LogFileCtx *log_ctx)
int SCConfLogReopen (LogFileCtx *)
Reopen a regular log file with the side-affect of truncating it.
Detailed Description
Author
Mike Pomraning mpomr.nosp@m.anin.nosp@m.g@qua.nosp@m.lys..nosp@m.com
Definition in file util-logopenfile.h.
Macro Definition Documentation
#define LOGFILE_ALERTS_PRINTED 0x02
Definition at line 129 of file util-logopenfile.h.
Referenced by Unified2AlertThreadDeinit().
#define LOGFILE_HEADER_WRITTEN 0x01
Definition at line 128 of file util-logopenfile.h.
#define LOGFILE_RECONN_MIN_TIME 500
Definition at line 125 of file util-logopenfile.h.
Typedef Documentation
typedef struct LogFileCtx_ LogFileCtx
Global structure for Output Context
typedef struct SyslogSetup_ SyslogSetup
Enumeration Type Documentation
enum LogFileType
Enumerator
LOGFILE_TYPE_FILE
LOGFILE_TYPE_SYSLOG
LOGFILE_TYPE_UNIX_DGRAM
LOGFILE_TYPE_UNIX_STREAM
LOGFILE_TYPE_REDIS
Definition at line 39 of file util-logopenfile.h.
Function Documentation
int LogFileFreeCtx (LogFileCtx * lf_ctx)
LogFileFreeCtx() Destroy a LogFileCtx (Close the file and free memory)
Parameters
motcx pointer to the OutputCtx
Return values
int 1 if succesful, 0 if error
Definition at line 497 of file util-logopenfile.c.
References LogFileCtx_::Close, LogFileCtx_::filename, LogFileCtx_::fp, LogFileCtx_::fp_mutex, LOGFILE_TYPE_REDIS, OutputUnregisterFileRotationFlag(), LogFileCtx_::prefix, LogFileCtx_::rotation_flag, SCFree, SCMutexDestroy, SCMutexLock, SCMutexUnlock, SCReturnInt, LogFileCtx_::sensor_name, and LogFileCtx_::type.
Referenced by AlertFastLogInitCtx(), LogHttpLogInitCtx(), LogStatsLogInitCtx(), and LogTcpDataLogInitCtx().
LogFileCtx* LogFileNewCtx (void)
LogFileNewCtx() Get a new LogFileCtx.
Return values
LogFileCtx * pointer if succesful, NULL if error
Definition at line 471 of file util-logopenfile.c.
References LogFileCtx_::Close, LogFileCtx_::fp_mutex, SCMalloc, SCMutexInit, and LogFileCtx_::Write.
Referenced by AlertFastLogInitCtx(), AlertSyslogInitCtx(), LogHttpLogInitCtx(), LogStatsLogInitCtx(), LogTcpDataLogInitCtx(), and Unified2AlertInitCtx().
int LogFileWrite (LogFileCtx * file_ctx, MemBuffer * buffer)
Definition at line 618 of file util-logopenfile.c.
References SyslogSetup_::alert_syslog_level, LogFileCtx_::fp_mutex, LOGFILE_TYPE_FILE, LOGFILE_TYPE_REDIS, LOGFILE_TYPE_SYSLOG, LOGFILE_TYPE_UNIX_DGRAM, LOGFILE_TYPE_UNIX_STREAM, MEMBUFFER_BUFFER, MEMBUFFER_OFFSET, MemBufferWriteString, SCMutexLock, SCMutexUnlock, syslog, LogFileCtx_::syslog_setup, LogFileCtx_::type, and LogFileCtx_::Write.
int SCConfLogOpenGeneric (ConfNode * conf, LogFileCtx * log_ctx, const char * default_filename, int rotate)
open a generic output "log file", which may be a regular file or a socket
Parameters
conf ConfNode structure for the output section in question
log_ctx Log file context allocated by caller
default_filename Default name of file to open, if not specified in ConfNode
rotate Register the file for rotation in HUP.
Return values
0 on success
-1 on error
Definition at line 214 of file util-logopenfile.c.
References ConfigGetLogDirectory(), ConfNodeLookupChildValue(), DEFAULT_LOG_FILETYPE, DEFAULT_LOG_MODE_APPEND, LogFileCtx_::filename, LogFileCtx_::fp, LogFileCtx_::is_regular, LogFileCtx_::is_sock, ConfNode_::name, OutputRegisterFileRotationFlag(), PathIsAbsolute(), LogFileCtx_::pcie_fp, LogFileCtx_::rotation_flag, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_YAML_CONF_ENTRY, SC_ERR_MEM_ALLOC, SCLogError, SCLogInfo, SCStrdup, LogFileCtx_::sock_type, and unlikely.
Referenced by AlertFastLogInitCtx(), LogHttpLogInitCtx(), LogStatsLogInitCtx(), and LogTcpDataLogInitCtx().
int SCConfLogOpenRedis (ConfNode * conf, LogFileCtx * log_ctx)
int SCConfLogReopen (LogFileCtx * log_ctx)
Reopen a regular log file with the side-affect of truncating it.
This is useful to clear the log file and start a new one, or to re-open the file after its been moved by something external (eg. logrotate).
Definition at line 310 of file util-logopenfile.c.
References LogFileCtx_::filename, LogFileCtx_::fp, LogFileCtx_::is_regular, SC_ERR_INVALID_ARGUMENT, SCLogDebug, and SCLogWarning.