suricata: src/util-ringbuffer.h File Reference
util-ringbuffer.h File Reference
#include "util-atomic.h"
#include "threads.h"
Data Structures
struct RingBuffer8_
struct RingBuffer16_
Macros
#define RING_BUFFER_8_SIZE 256
ring buffer api
#define RING_BUFFER_16_SIZE 65536
Typedefs
typedef struct RingBuffer8_ RingBuffer8
typedef struct RingBuffer16_ RingBuffer16
Functions
RingBuffer8 * RingBuffer8Init (void)
void RingBuffer8Destroy (RingBuffer8 *)
RingBuffer16 * RingBufferInit (void)
void RingBufferDestroy (RingBuffer16 *)
int RingBufferIsEmpty (RingBuffer16 *)
check the ringbuffer is empty (no data in it)
int RingBufferIsFull (RingBuffer16 *)
check the ringbuffer is full (no more data will fit)
uint16_t RingBufferSize (RingBuffer16 *)
get number of items in the ringbuffer
void RingBuffer8Shutdown (RingBuffer8 *)
tell the ringbuffer to shut down
void RingBufferShutdown (RingBuffer16 *)
tell the ringbuffer to shut down
void RingBufferWait (RingBuffer16 *rb)
wait function for condition where ringbuffer is either full or empty.
void * RingBufferSrSw8Get (RingBuffer8 *)
int RingBufferSrSw8Put (RingBuffer8 *, void *)
void * RingBufferMrSw8Get (RingBuffer8 *)
get the next ptr from the ring buffer
int RingBufferMrSw8Put (RingBuffer8 *, void *)
put a ptr in the RingBuffer
void * RingBufferMrSwGet (RingBuffer16 *)
get the next ptr from the ring buffer
int RingBufferMrSwPut (RingBuffer16 *, void *)
put a ptr in the RingBuffer
void * RingBufferSrSwGet (RingBuffer16 *)
int RingBufferSrSwPut (RingBuffer16 *, void *)
void * RingBufferMrMw8Get (RingBuffer8 *)
get the next ptr from the ring buffer
int RingBufferMrMw8Put (RingBuffer8 *, void *)
put a ptr in the RingBuffer.
void * RingBufferMrMwGet (RingBuffer16 *)
get the next ptr from the ring buffer
void * RingBufferMrMwGetNoWait (RingBuffer16 *)
get the next ptr from the ring buffer
int RingBufferMrMwPut (RingBuffer16 *, void *)
put a ptr in the RingBuffer.
void * RingBufferSrMw8Get (RingBuffer8 *)
int RingBufferSrMw8Put (RingBuffer8 *, void *)
put a ptr in the RingBuffer.
void DetectRingBufferRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
See the .c file for a full explanation.
Definition in file util-ringbuffer.h.
Macro Definition Documentation
#define RING_BUFFER_16_SIZE 65536
Definition at line 66 of file util-ringbuffer.h.
#define RING_BUFFER_8_SIZE 256
ring buffer api
When the ringbuffer is full we have two options, either we spin & sleep or we use a pthread condition to wait.
Warning
this approach isn't working due to a race condition between the time it takes for a thread to enter the condwait and the signalling. I've obverved the following case: T1 sees that the ringbuffer is empty, so it decides to start the wait condition. While it is acquiring the lock and entering the wait, T0 puts a number of items in the buffer. For each of these it signals T1. However, as that thread isn't in the "wait" mode yet, the signals are lost. T0 now is done as well and enters it's own wait condition. T1 completes it's "wait" initialization. It waits for signals, but T0 won't be able to send them as it's waiting itself.Ring buffer api for a single writer and a single reader. It uses a read and write pointer. Only the read ptr needs atomic updating.
Definition at line 53 of file util-ringbuffer.h.
Typedef Documentation
typedef struct RingBuffer16_ RingBuffer16
typedef struct RingBuffer8_ RingBuffer8
Function Documentation
void DetectRingBufferRegisterTests (void)
Definition at line 1078 of file util-ringbuffer.c.
Referenced by RunUnittests().
void RingBuffer8Destroy (RingBuffer8 *)
Definition at line 527 of file util-ringbuffer.c.
References SC_ATOMIC_DESTROY, SCCondDestroy, SCFree, SCMutexDestroy, SCSpinDestroy, and RingBuffer8_::spin.
Referenced by TmqhRingBufferDestroy().
RingBuffer8* RingBuffer8Init (void)
Definition at line 507 of file util-ringbuffer.c.
References SC_ATOMIC_INIT, SCCondInit, SCMalloc, SCMutexInit, SCSpinInit, RingBuffer8_::spin, and unlikely.
Referenced by TmqhRingBufferRegister().
void RingBuffer8Shutdown (RingBuffer8 * rb)
tell the ringbuffer to shut down
Parameters
rb ringbuffer
Definition at line 99 of file util-ringbuffer.c.
References SCCondSignal, and RingBuffer8_::shutdown.
Referenced by TmqhInputRingBufferShutdownHandler().
void RingBufferDestroy (RingBuffer16 *)
Definition at line 664 of file util-ringbuffer.c.
References SC_ATOMIC_DESTROY, SCCondDestroy, SCFree, SCMutexDestroy, SCSpinDestroy, and RingBuffer16_::spin.
RingBuffer16* RingBufferInit (void)
Definition at line 644 of file util-ringbuffer.c.
References SC_ATOMIC_INIT, SCCondInit, SCMalloc, SCMutexInit, SCSpinInit, RingBuffer16_::spin, and unlikely.
int RingBufferIsEmpty (RingBuffer16 * rb)
check the ringbuffer is empty (no data in it)
Parameters
rb ringbuffer
Return values
1 empty
0 not empty
Definition at line 166 of file util-ringbuffer.c.
References SC_ATOMIC_GET.
int RingBufferIsFull (RingBuffer16 * rb)
check the ringbuffer is full (no more data will fit)
Parameters
rb ringbuffer
Return values
1 empty
0 not empty
Definition at line 182 of file util-ringbuffer.c.
References SC_ATOMIC_GET.
void* RingBufferMrMw8Get (RingBuffer8 * rb)
get the next ptr from the ring buffer
Multiple Reader, Multi Writer ring buffer, fixed at 256 items so we can use unsigned char's that just wrap around
Because we allow for multiple readers we take great care in making sure that the threads don't interfere with one another.
local pointer for data races. If SCAtomicCompareAndSwap (CAS) fails we increase our local array idx to try the next array member until we succeed. Or when the buffer is empty again we jump back to the waiting loop.
Definition at line 550 of file util-ringbuffer.c.
References RingBuffer8_::array, SC_ATOMIC_CAS, SC_ATOMIC_GET, SCCondSignal, SCLogDebug, and RingBuffer8_::shutdown.
int RingBufferMrMw8Put (RingBuffer8 * rb, void * ptr)
put a ptr in the RingBuffer.
As we support multiple writers we need to protect 2 things:
writing the ptr to the array
incrementing the rb->write idx
We can't do both at the same time in one atomic operation, so we need to (spin) lock it. We do increment rb->write atomically after that, so that we don't need to use the lock in our *Get function.
Parameters
rb the ringbuffer
ptr ptr to store
Return values
0 ok
-1 wait loop interrupted because of engine flags
Definition at line 606 of file util-ringbuffer.c.
References RingBuffer8_::array, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCCondSignal, SCLogDebug, SCSpinLock, SCSpinUnlock, RingBuffer8_::shutdown, and RingBuffer8_::spin.
void* RingBufferMrMwGet (RingBuffer16 * rb)
get the next ptr from the ring buffer
Multiple Reader, Multi Writer ring buffer, fixed at 65536 items so we can use unsigned char's that just wrap around
Because we allow for multiple readers we take great care in making sure that the threads don't interfere with one another.
local pointer for data races. If SCAtomicCompareAndSwap (CAS) fails we increase our local array idx to try the next array member until we succeed. Or when the buffer is empty again we jump back to the waiting loop.
Definition at line 688 of file util-ringbuffer.c.
References RingBuffer16_::array, SC_ATOMIC_CAS, SC_ATOMIC_GET, SCCondSignal, SCLogDebug, and RingBuffer16_::shutdown.
void* RingBufferMrMwGetNoWait (RingBuffer16 * rb)
get the next ptr from the ring buffer
Because we allow for multiple readers we take great care in making sure that the threads don't interfere with one another.
This version does NOT enter a wait if the buffer is empty loop.
Return values
ptr pointer to the data, or NULL if buffer is empty
local pointer for data races. If SCAtomicCompareAndSwap (CAS) fails we increase our local array idx to try the next array member until we succeed. Or when the buffer is empty again we jump back to the waiting loop.
Definition at line 737 of file util-ringbuffer.c.
References RingBuffer16_::array, SC_ATOMIC_CAS, SC_ATOMIC_GET, SCCondSignal, and SCLogDebug.
int RingBufferMrMwPut (RingBuffer16 * rb, void * ptr)
put a ptr in the RingBuffer.
As we support multiple writers we need to protect 2 things:
writing the ptr to the array
incrementing the rb->write idx
We can't do both at the same time in one atomic operation, so we need to (spin) lock it. We do increment rb->write atomically after that, so that we don't need to use the lock in our *Get function.
Parameters
rb the ringbuffer
ptr ptr to store
Return values
0 ok
-1 wait loop interrupted because of engine flags
Definition at line 791 of file util-ringbuffer.c.
References RingBuffer16_::array, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCCondSignal, SCLogDebug, SCSpinLock, SCSpinUnlock, RingBuffer16_::shutdown, and RingBuffer16_::spin.
void* RingBufferMrSw8Get (RingBuffer8 * rb)
get the next ptr from the ring buffer
Multiple Reader, Single Writer ring buffer, fixed at 256 items so we can use unsigned char's that just wrap around
Because we allow for multiple readers we take great care in making sure that the threads don't interfere with one another.
local pointer for data races. If SCAtomicCompareAndSwap (CAS) fails we increase our local array idx to try the next array member until we succeed. Or when the buffer is empty again we jump back to the waiting loop.
Definition at line 322 of file util-ringbuffer.c.
References RingBuffer8_::array, SC_ATOMIC_CAS, SC_ATOMIC_GET, SCCondSignal, SCLogDebug, and RingBuffer8_::shutdown.
Referenced by TmqhInputRingBufferMrSw().
int RingBufferMrSw8Put (RingBuffer8 * , void *)
put a ptr in the RingBuffer
Definition at line 364 of file util-ringbuffer.c.
References RingBuffer8_::array, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCCondSignal, SCLogDebug, and RingBuffer8_::shutdown.
Referenced by TmqhOutputRingBufferMrSw().
void* RingBufferMrSwGet (RingBuffer16 * rb)
get the next ptr from the ring buffer
Multiple Reader, Single Writer ring buffer, fixed at 65536 items so we can use unsigned shorts that just wrap around
Because we allow for multiple readers we take great care in making sure that the threads don't interfere with one another.
local pointer for data races. If SCAtomicCompareAndSwap (CAS) fails we increase our local array idx to try the next array member until we succeed. Or when the buffer is empty again we jump back to the waiting loop.
Definition at line 396 of file util-ringbuffer.c.
References RingBuffer16_::array, SC_ATOMIC_CAS, SC_ATOMIC_GET, SCCondSignal, SCLogDebug, and RingBuffer16_::shutdown.
int RingBufferMrSwPut (RingBuffer16 * , void *)
put a ptr in the RingBuffer
Definition at line 438 of file util-ringbuffer.c.
References RingBuffer16_::array, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCCondSignal, SCLogDebug, and RingBuffer16_::shutdown.
void RingBufferShutdown (RingBuffer16 * rb)
tell the ringbuffer to shut down
Parameters
rb ringbuffer
Definition at line 143 of file util-ringbuffer.c.
References SCCondSignal, and RingBuffer16_::shutdown.
uint16_t RingBufferSize (RingBuffer16 *)
get number of items in the ringbuffer
Definition at line 152 of file util-ringbuffer.c.
References SC_ATOMIC_GET, SCEnter, and SCReturnUInt.
void* RingBufferSrMw8Get (RingBuffer8 *)
Definition at line 237 of file util-ringbuffer.c.
References RingBuffer8_::array, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCCondSignal, and RingBuffer8_::shutdown.
Referenced by TmqhInputRingBufferSrMw().
int RingBufferSrMw8Put (RingBuffer8 * rb, void * ptr)
put a ptr in the RingBuffer.
As we support multiple writers we need to protect 2 things:
writing the ptr to the array
incrementing the rb->write idx
We can't do both at the same time in one atomic operation, so we need to (spin) lock it. We do increment rb->write atomically after that, so that we don't need to use the lock in our *Get function.
Parameters
rb the ringbuffer
ptr ptr to store
Return values
0 ok
-1 wait loop interrupted because of engine flags
Definition at line 277 of file util-ringbuffer.c.
References RingBuffer8_::array, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCCondSignal, SCLogDebug, SCSpinLock, SCSpinUnlock, RingBuffer8_::shutdown, and RingBuffer8_::spin.
Referenced by TmqhOutputRingBufferSrMw().
void* RingBufferSrSw8Get (RingBuffer8 *)
Single Reader, Single Writer ring buffer, fixed at 256 items so we can use unsigned char's that just wrap around
Definition at line 193 of file util-ringbuffer.c.
References RingBuffer8_::array, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCCondSignal, and RingBuffer8_::shutdown.
Referenced by TmqhInputRingBufferSrSw().
int RingBufferSrSw8Put (RingBuffer8 * , void *)
Definition at line 215 of file util-ringbuffer.c.
References RingBuffer8_::array, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCCondSignal, and RingBuffer8_::shutdown.
Referenced by TmqhOutputRingBufferSrSw().
void* RingBufferSrSwGet (RingBuffer16 *)
Single Reader, Single Writer ring buffer, fixed at 65536 items so we can use unsigned shorts that just wrap around
Definition at line 463 of file util-ringbuffer.c.
References RingBuffer16_::array, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCCondSignal, and RingBuffer16_::shutdown.
int RingBufferSrSwPut (RingBuffer16 * , void *)
Definition at line 485 of file util-ringbuffer.c.
References RingBuffer16_::array, SC_ATOMIC_ADD, SC_ATOMIC_GET, SCCondSignal, and RingBuffer16_::shutdown.
void RingBufferWait (RingBuffer16 * rb)
wait function for condition where ringbuffer is either full or empty.
Parameters
rb ringbuffer
Based on RINGBUFFER_MUTEX_WAIT define, we either sleep and spin or use thread condition to wait.
Definition at line 90 of file util-ringbuffer.c.