suricata: src/util-profiling.c File Reference
util-profiling.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "conf.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-byte.h"
#include "util-profiling.h"
#include "util-profiling-locks.h"
Data Structures
struct SCProfilePacketData_
Macros
#define DEFAULT_LOG_FILENAME "profile.log"
#define DEFAULT_LOG_MODE_APPEND "yes"
#define CASE_CODE(E) case E: return #E
Typedefs
typedef struct SCProfilePacketData_ SCProfilePacketData
Functions
void SCProfilingDumpPacketStats (void)
const char * PacketProfileDetectIdToString (PacketProfileDetectId id)
Maps the PacketProfileDetectId, to its string equivalent.
void SCProfilingInit (void)
Initialize profiling.
void SCProfilingDestroy (void)
Free resources used by profiling.
void SCProfilingDump (void)
void SCProfilingPrintPacketProfile (Packet *p)
void SCProfilingUpdatePacketDetectRecords (Packet *p)
void SCProfilingUpdatePacketAppRecords (Packet *p)
void SCProfilingUpdatePacketTmmRecord (int module, uint8_t proto, PktProfilingTmmData *pdt, int ipver)
void SCProfilingUpdatePacketTmmRecords (Packet *p)
void SCProfilingAddPacket (Packet *p)
PktProfiling * SCProfilePacketStart (void)
int SCProfileRuleStart (Packet *p)
void SCProfilingRegisterTests (void)
Variables
int profiling_locks_enabled
int profiling_locks_output_to_file
char * profiling_locks_file_name
char * profiling_locks_file_mode
SCProfilePacketData packet_profile_data4 [257]
SCProfilePacketData packet_profile_data6 [257]
SCProfilePacketData packet_profile_tmm_data4 [TMM_SIZE][257]
SCProfilePacketData packet_profile_tmm_data6 [TMM_SIZE][257]
SCProfilePacketData packet_profile_app_data4 [TMM_SIZE][257]
SCProfilePacketData packet_profile_app_data6 [TMM_SIZE][257]
SCProfilePacketData packet_profile_app_pd_data4 [257]
SCProfilePacketData packet_profile_app_pd_data6 [257]
SCProfilePacketData packet_profile_detect_data4 [PROF_DETECT_SIZE][257]
SCProfilePacketData packet_profile_detect_data6 [PROF_DETECT_SIZE][257]
int profiling_packets_enabled = 0
int profiling_packets_csv_enabled = 0
int profiling_output_to_file = 0
int profiling_packets_output_to_file = 0
char * profiling_file_name
char * profiling_packets_file_name
char * profiling_csv_file_name
const char * profiling_packets_file_mode = "a"
__thread int profiling_rules_entered = 0
Detailed Description
Author
Endace Technology Limited.
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
An API for profiling operations.
Really just a wrapper around the existing perf counters.
Definition in file util-profiling.c.
Macro Definition Documentation
#define CASE_CODE (E) case E: return #E
Definition at line 1003 of file util-profiling.c.
Referenced by PacketProfileDetectIdToString().
#define DEFAULT_LOG_FILENAME "profile.log"
Definition at line 47 of file util-profiling.c.
#define DEFAULT_LOG_MODE_APPEND "yes"
Definition at line 48 of file util-profiling.c.
Typedef Documentation
typedef struct SCProfilePacketData_ SCProfilePacketData
Function Documentation
const char * PacketProfileDetectIdToString (PacketProfileDetectId id)
Maps the PacketProfileDetectId, to its string equivalent.
Parameters
id PacketProfileDetectId id
Return values
string equivalent for the PacketProfileDetectId id
Definition at line 1012 of file util-profiling.c.
References CASE_CODE, PROF_DETECT_ALERT, PROF_DETECT_CLEANUP, PROF_DETECT_GETSGH, PROF_DETECT_IPONLY, PROF_DETECT_MPM, PROF_DETECT_MPM_DNSQUERY, PROF_DETECT_MPM_HCBD, PROF_DETECT_MPM_HCD, PROF_DETECT_MPM_HHD, PROF_DETECT_MPM_HMD, PROF_DETECT_MPM_HRHD, PROF_DETECT_MPM_HRUD, PROF_DETECT_MPM_HSBD, PROF_DETECT_MPM_HSCD, PROF_DETECT_MPM_HSMD, PROF_DETECT_MPM_HUAD, PROF_DETECT_MPM_PACKET, PROF_DETECT_MPM_PKT_STREAM, PROF_DETECT_MPM_STREAM, PROF_DETECT_MPM_URI, PROF_DETECT_NONMPMLIST, PROF_DETECT_PREFILTER, PROF_DETECT_RULES, and PROF_DETECT_STATEFUL.
Referenced by SCProfilingDumpPacketStats(), and SCProfilingInit().
PktProfiling* SCProfilePacketStart (void)
Definition at line 976 of file util-profiling.c.
References SC_ATOMIC_ADD, and SCCalloc.
int SCProfileRuleStart (Packet * p)
Definition at line 986 of file util-profiling.c.
References Packet_::flags, PKT_PROFILE, Packet_::profile, and SC_ATOMIC_ADD.
void SCProfilingAddPacket (Packet * p)
Definition at line 895 of file util-profiling.c.
References SCProfilePacketData_::cnt, IS_TUNNEL_PKT, SCProfilePacketData_::max, SCProfilePacketData_::min, PKT_IS_IPV4, PKT_IS_IPV6, Packet_::profile, profiling_packets_csv_enabled, Packet_::proto, SCProfilingPrintPacketProfile(), SCProfilingUpdatePacketAppRecords(), SCProfilingUpdatePacketDetectRecords(), SCProfilingUpdatePacketTmmRecords(), PktProfiling_::ticks_end, PktProfiling_::ticks_start, and SCProfilePacketData_::tot.
void SCProfilingDestroy (void)
Free resources used by profiling.
Definition at line 273 of file util-profiling.c.
References LockRecordFreeHash(), profiling_csv_file_name, profiling_file_name, profiling_packets_csv_enabled, profiling_packets_enabled, and SCFree.
Referenced by main().
void SCProfilingDump (void)
Definition at line 299 of file util-profiling.c.
References SCLogInfo, and SCProfilingDumpPacketStats().
Referenced by main().
void SCProfilingDumpPacketStats (void)
Definition at line 305 of file util-profiling.c.
References ALPROTO_MAX, AppProtoToString(), SCProfilePacketData_::cnt, flags, m, SCProfilePacketData_::max, SCProfilePacketData_::min, PacketProfileDetectIdToString(), PROF_DETECT_SIZE, profiling_packets_enabled, profiling_packets_file_mode, profiling_packets_file_name, profiling_packets_output_to_file, SC_ERR_FOPEN, SCLogError, TM_FLAG_LOGAPI_TM, tmm_modules, TMM_SIZE, TmModuleTmmIdToString(), and SCProfilePacketData_::tot.
Referenced by SCProfilingDump().
void SCProfilingInit (void)
Initialize profiling.
Definition at line 126 of file util-profiling.c.
References ALPROTO_MAX, AppProtoToString(), ConfGetInt(), ConfGetNode(), ConfigGetLogDirectory(), ConfNodeChildValueIsTrue(), ConfNodeLookupChildValue(), ConfValIsTrue(), LockRecordInitHash(), PacketProfileDetectIdToString(), PROF_DETECT_SIZE, profiling_csv_file_name, profiling_locks_enabled, profiling_locks_file_mode, profiling_locks_file_name, profiling_locks_output_to_file, profiling_packets_csv_enabled, profiling_packets_enabled, profiling_packets_file_mode, profiling_packets_file_name, profiling_packets_output_to_file, SC_ATOMIC_INIT, SC_ERR_MEM_ALLOC, SC_ERR_MUTEX, SC_WARN_PROFILE, SCLogError, SCLogInfo, SCLogWarning, SCMalloc, TMM_SIZE, TmModuleTmmIdToString(), and unlikely.
void SCProfilingPrintPacketProfile (Packet * p)
Definition at line 683 of file util-profiling.c.
References ALPROTO_MAX, PktProfiling_::app, PktProfiling_::detect, Packet_::pcap_cnt, PKT_IS_IPV4, PKT_IS_IPV6, PROF_DETECT_SIZE, Packet_::profile, profiling_packets_csv_enabled, Packet_::proto, PktProfiling_::proto_detect, PktProfilingTmmData_::ticks_end, PktProfiling_::ticks_end, PktProfilingDetectData_::ticks_spent, PktProfilingAppData_::ticks_spent, PktProfilingTmmData_::ticks_start, PktProfiling_::ticks_start, PktProfiling_::tmm, TMM_SIZE, and TMM_STREAMTCP.
Referenced by SCProfilingAddPacket().
void SCProfilingRegisterTests (void)
Definition at line 1153 of file util-profiling.c.
Referenced by RunUnittests().
void SCProfilingUpdatePacketAppRecords (Packet * p)
Definition at line 820 of file util-profiling.c.
References ALPROTO_MAX, PktProfiling_::app, PKT_IS_IPV4, Packet_::profile, Packet_::proto, PktProfiling_::proto_detect, and PktProfilingAppData_::ticks_spent.
Referenced by SCProfilingAddPacket().
void SCProfilingUpdatePacketDetectRecords (Packet * p)
Definition at line 762 of file util-profiling.c.
References PktProfiling_::detect, PKT_IS_IPV4, PROF_DETECT_SIZE, Packet_::profile, Packet_::proto, and PktProfilingDetectData_::ticks_spent.
Referenced by SCProfilingAddPacket().
void SCProfilingUpdatePacketTmmRecord (int module, uint8_t proto, PktProfilingTmmData * pdt, int ipver)
Definition at line 844 of file util-profiling.c.
References SCProfilePacketData_::cnt, SCProfilePacketData_::max, SCProfilePacketData_::min, proto, PktProfilingTmmData_::ticks_end, PktProfilingTmmData_::ticks_start, and SCProfilePacketData_::tot.
Referenced by SCProfilingUpdatePacketTmmRecords().
void SCProfilingUpdatePacketTmmRecords (Packet * p)
Definition at line 877 of file util-profiling.c.
References PKT_IS_IPV4, Packet_::profile, Packet_::proto, SCProfilingUpdatePacketTmmRecord(), PktProfilingTmmData_::ticks_end, PktProfilingTmmData_::ticks_start, PktProfiling_::tmm, and TMM_SIZE.
Referenced by SCProfilingAddPacket().
Variable Documentation
SCProfilePacketData packet_profile_app_data4[TMM_SIZE][257]
Definition at line 80 of file util-profiling.c.
SCProfilePacketData packet_profile_app_data6[TMM_SIZE][257]
Definition at line 81 of file util-profiling.c.
SCProfilePacketData packet_profile_app_pd_data4[257]
Definition at line 83 of file util-profiling.c.
SCProfilePacketData packet_profile_app_pd_data6[257]
Definition at line 84 of file util-profiling.c.
SCProfilePacketData packet_profile_data4[257]
all proto's + tunnel
Definition at line 73 of file util-profiling.c.
SCProfilePacketData packet_profile_data6[257]
all proto's + tunnel
Definition at line 74 of file util-profiling.c.
SCProfilePacketData packet_profile_detect_data4[PROF_DETECT_SIZE][257]
Definition at line 86 of file util-profiling.c.
SCProfilePacketData packet_profile_detect_data6[PROF_DETECT_SIZE][257]
Definition at line 87 of file util-profiling.c.
SCProfilePacketData packet_profile_tmm_data4[TMM_SIZE][257]
Definition at line 77 of file util-profiling.c.
SCProfilePacketData packet_profile_tmm_data6[TMM_SIZE][257]
Definition at line 78 of file util-profiling.c.
char* profiling_csv_file_name
Definition at line 96 of file util-profiling.c.
Referenced by SCProfilingDestroy(), and SCProfilingInit().
char* profiling_file_name
Definition at line 94 of file util-profiling.c.
Referenced by SCProfilingDestroy(), SCProfilingKeywordDump(), SCProfilingKeywordsGlobalInit(), SCProfilingRuleDump(), and SCProfilingRulesGlobalInit().
int profiling_locks_enabled
Referenced by SCProfilingInit().
char* profiling_locks_file_mode
Referenced by SCProfilingInit().
char* profiling_locks_file_name
Referenced by SCProfilingInit().
int profiling_locks_output_to_file
Referenced by SCProfilingInit().
int profiling_output_to_file = 0
Definition at line 92 of file util-profiling.c.
Referenced by SCProfilingRuleDump(), and SCProfilingRulesGlobalInit().
int profiling_packets_csv_enabled = 0
Definition at line 90 of file util-profiling.c.
Referenced by SCProfilingAddPacket(), SCProfilingDestroy(), SCProfilingInit(), and SCProfilingPrintPacketProfile().
int profiling_packets_enabled = 0
Definition at line 89 of file util-profiling.c.
Referenced by SCProfilingDestroy(), SCProfilingDumpPacketStats(), and SCProfilingInit().
const char* profiling_packets_file_mode = "a"
Definition at line 97 of file util-profiling.c.
Referenced by SCProfilingDumpPacketStats(), and SCProfilingInit().
char* profiling_packets_file_name
Definition at line 95 of file util-profiling.c.
Referenced by SCProfilingDumpPacketStats(), and SCProfilingInit().
int profiling_packets_output_to_file = 0
Definition at line 93 of file util-profiling.c.
Referenced by SCProfilingDumpPacketStats(), and SCProfilingInit().
__thread int profiling_rules_entered = 0
Used as a check so we don't double enter a profiling run.
Definition at line 105 of file util-profiling.c.