suricata: src/util-decode-der.c File Reference
util-decode-der.c File Reference
#include "suricata-common.h"
#include "util-decode-der.h"
Macros
#define MAX_OID_LENGTH 256
Functions
Asn1Generic * DecodeDer (const unsigned char *buffer, uint32_t size, uint32_t *errcode)
void DerFree (Asn1Generic *a)
Detailed Description
Author
Pierre Chifflier pierr.nosp@m.e.ch.nosp@m.iffli.nosp@m.er@s.nosp@m.si.go.nosp@m.uv.f.nosp@m.r
Definition in file util-decode-der.c.
Macro Definition Documentation
#define MAX_OID_LENGTH 256
Definition at line 50 of file util-decode-der.c.
Function Documentation
Asn1Generic* DecodeDer (const unsigned char * buffer, uint32_t size, uint32_t * errcode)
Definition at line 737 of file util-decode-der.c.
Referenced by DecodeTLSHandshakeServerCertificate().
void DerFree (Asn1Generic * a)
Definition at line 768 of file util-decode-der.c.
References Asn1Generic_::data, DerFree(), Asn1Generic_::next, SCFree, and Asn1Generic_::str.
Referenced by DecodeTLSHandshakeServerCertificate(), and DerFree().