suricata: src/util-storage.c File Reference
util-storage.c File Reference
#include "suricata-common.h"
#include "util-unittest.h"
#include "util-storage.h"
Data Structures
struct StorageMapping_
struct StorageList_
list of StorageMapping used at registration time
Typedefs
typedef struct StorageMapping_ StorageMapping
typedef struct StorageList_ StorageList
list of StorageMapping used at registration time
Functions
const char * StoragePrintType (StorageEnum type)
void StorageInit (void)
void StorageCleanup (void)
int StorageRegister (const StorageEnum type, const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
Register new storage.
int StorageFinalize (void)
unsigned int StorageGetCnt (StorageEnum type)
unsigned int StorageGetSize (StorageEnum type)
get the size of the void array used to store the pointers
void * StorageGetById (const Storage *storage, const StorageEnum type, const int id)
get storage for id
int StorageSetById (Storage *storage, const StorageEnum type, const int id, void *ptr)
set storage for id
void * StorageAllocByIdPrealloc (Storage *storage, StorageEnum type, int id)
AllocById func for prealloc'd base storage (storage ptrs are part of another memory block)
void * StorageAllocById (Storage **storage, StorageEnum type, int id)
AllocById func for when we manage the Storage ptr itself.
void StorageFreeById (Storage *storage, StorageEnum type, int id)
void StorageFreeAll (Storage *storage, StorageEnum type)
void StorageFree (Storage **storage, StorageEnum type)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Storage API
Definition in file util-storage.c.
Typedef Documentation
typedef struct StorageList_ StorageList
list of StorageMapping used at registration time
typedef struct StorageMapping_ StorageMapping
Function Documentation
void* StorageAllocById (Storage ** storage, StorageEnum type, int id)
AllocById func for when we manage the Storage ptr itself.
Definition at line 252 of file util-storage.c.
References StorageMapping_::Alloc, BUG_ON, StorageList_::id, StorageList_::map, SCFree, SCLogDebug, SCMalloc, StorageMapping_::size, type, and unlikely.
void* StorageAllocByIdPrealloc (Storage * storage, StorageEnum type, int id)
AllocById func for prealloc'd base storage (storage ptrs are part of another memory block)
Definition at line 234 of file util-storage.c.
References StorageMapping_::Alloc, BUG_ON, StorageList_::id, StorageList_::map, SCLogDebug, StorageMapping_::size, and type.
Referenced by FlowAllocStorageById(), HostAllocStorageById(), and IPPairAllocStorageById().
void StorageCleanup (void)
Definition at line 73 of file util-storage.c.
References StorageList_::next, next, SCFree, and STORAGE_MAX.
int StorageFinalize (void)
Definition at line 137 of file util-storage.c.
References StorageMapping_::Alloc, StorageMapping_::Free, StorageList_::id, m, StorageList_::map, StorageMapping_::name, StorageList_::next, SCLogDebug, SCMalloc, StorageMapping_::size, STORAGE_MAX, StoragePrintType(), StorageMapping_::type, and unlikely.
Referenced by RunUnittests().
void StorageFree (Storage ** storage, StorageEnum type)
Definition at line 327 of file util-storage.c.
References BUG_ON, StorageMapping_::Free, StorageList_::map, SCFree, and type.
void StorageFreeAll (Storage * storage, StorageEnum type)
Definition at line 304 of file util-storage.c.
References BUG_ON, StorageMapping_::Free, StorageList_::map, and type.
Referenced by FlowFreeStorage(), HostFreeStorage(), and IPPairFreeStorage().
void StorageFreeById (Storage * storage, StorageEnum type, int id)
Definition at line 282 of file util-storage.c.
References BUG_ON, StorageMapping_::Free, StorageList_::id, StorageList_::map, SCLogDebug, and type.
Referenced by FlowFreeStorageById(), HostFreeStorageById(), and IPPairFreeStorageById().
void* StorageGetById (const Storage * storage, const StorageEnum type, const int id)
get storage for id
Definition at line 211 of file util-storage.c.
References BUG_ON, StorageList_::id, and SCLogDebug.
Referenced by FlowGetStorageById(), HostGetStorageById(), and IPPairGetStorageById().
unsigned int StorageGetCnt (StorageEnum type)
Definition at line 195 of file util-storage.c.
References type.
unsigned int StorageGetSize (StorageEnum type)
get the size of the void array used to store the pointers
Return values
size size in bytes, can return 0 if not storage is needed
Todo:
we could return -1 when registration isn't closed yet, however this will break lots of tests currently, so not doing it now
Definition at line 206 of file util-storage.c.
References type.
Referenced by FlowStorageSize(), HostStorageSize(), and IPPairStorageSize().
void StorageInit (void)
Definition at line 65 of file util-storage.c.
Referenced by RunUnittests().
const char* StoragePrintType (StorageEnum type)
Definition at line 50 of file util-storage.c.
References STORAGE_FLOW, STORAGE_HOST, STORAGE_IPPAIR, and STORAGE_MAX.
Referenced by StorageFinalize(), and StorageRegister().
int StorageRegister (const StorageEnum type, const char * name, const unsigned int size, void *(*)(unsigned int) Alloc, void(*)(void *) Free)
Register new storage.
Parameters
type type from StorageEnum
name name
size size of the per instance storage
Alloc alloc function for per instance storage
Free free function for per instance storage
Note
if size == ptr size (so sizeof(void *)) and Alloc == NULL the API just gives the caller a ptr to store something it alloc'ed itself.
Definition at line 97 of file util-storage.c.
References StorageMapping_::Alloc, StorageMapping_::Free, StorageList_::id, StorageList_::map, StorageMapping_::name, StorageList_::next, SC_ERR_INVALID_VALUE, SCLogError, SCMalloc, StorageMapping_::size, STORAGE_MAX, StoragePrintType(), StorageMapping_::type, type, and unlikely.
Referenced by FlowStorageRegister(), HostStorageRegister(), and IPPairStorageRegister().
int StorageSetById (Storage * storage, const StorageEnum type, const int id, void * ptr)
set storage for id
Definition at line 222 of file util-storage.c.
References BUG_ON, StorageList_::id, and SCLogDebug.
Referenced by FlowSetStorageById(), HostSetStorageById(), and IPPairSetStorageById().