suricata: src/util-syslog.h File Reference
util-syslog.h File Reference
Functions
SCEnumCharMap * SCSyslogGetFacilityMap (void)
returns the syslog facility enum map
SCEnumCharMap * SCSyslogGetLogLevelMap (void)
returns the syslog facility enum map
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Definition in file util-syslog.h.
Function Documentation
SCEnumCharMap* SCSyslogGetFacilityMap (void)
returns the syslog facility enum map
Definition at line 56 of file util-syslog.c.
References sc_syslog_facility_map.
Referenced by AlertSyslogInitCtx(), SCLogInitOPIfaceCtx(), and SCLogLoadConfig().
SCEnumCharMap* SCSyslogGetLogLevelMap (void)
returns the syslog facility enum map
Definition at line 74 of file util-syslog.c.
References sc_syslog_level_map.
Referenced by AlertSyslogInitCtx().