suricata: src/util-device.h File Reference
util-device.h File Reference
#include "queue.h"
#include "unix-manager.h"
Data Structures
struct LiveDevice_
Typedefs
typedef struct LiveDevice_ LiveDevice
Functions
int LiveRegisterDevice (char *dev)
int LiveGetDeviceCount (void)
Get the number of registered devices.
char * LiveGetDeviceName (int number)
Get a pointer to the device name at idx.
LiveDevice * LiveGetDevice (char *dev)
Get a pointer to the device at idx.
int LiveBuildDeviceList (char *base)
void LiveDeviceHasNoStats (void)
int LiveDeviceListClean (void)
int LiveBuildDeviceListCustom (char *base, char *itemname)
Typedef Documentation
typedef struct LiveDevice_ LiveDevice
storage for live device names
Function Documentation
int LiveBuildDeviceList (char * base)
Definition at line 139 of file util-device.c.
References LiveBuildDeviceListCustom().
int LiveBuildDeviceListCustom (char * base, char * itemname)
Definition at line 144 of file util-device.c.
References ConfGetNode(), LiveRegisterDevice(), ConfNode_::name, next, SCLogInfo, TAILQ_FOREACH, and ConfNode_::val.
Referenced by LiveBuildDeviceList().
void LiveDeviceHasNoStats (void)
Call this function to disable stat on live devices
This can be useful in the case, this is not a real interface.
Definition at line 174 of file util-device.c.
Referenced by RunModeIpsIPFWAutoFp(), RunModeIpsIPFWWorker(), RunModeIpsNFQAutoFp(), and RunModeIpsNFQWorker().
int LiveDeviceListClean (void)
Definition at line 179 of file util-device.c.
References LiveDevice_::dev, next, SC_ATOMIC_DESTROY, SC_ATOMIC_GET, SCEnter, SCFree, SCLogNotice, SCReturnInt, TAILQ_FOREACH_SAFE, and TM_ECODE_OK.
Referenced by main().
LiveDevice* LiveGetDevice (char * name)
Get a pointer to the device at idx.
Parameters
number idx of the device in our list
Return values
ptr pointer to the string containing the device
NULL on error
Definition at line 116 of file util-device.c.
References LiveDevice_::dev, next, SC_ERR_INVALID_VALUE, SCLogWarning, and TAILQ_FOREACH.
Referenced by ReceiveAFPThreadInit(), ReceiveErfDagThreadInit(), ReceivePcapThreadInit(), and ReceivePfringThreadInit().
int LiveGetDeviceCount (void)
Get the number of registered devices.
Return values
cnt the number of registered devices
Definition at line 72 of file util-device.c.
References next, and TAILQ_FOREACH.
Referenced by AFPRunModeIsIPS(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), RunModeSetLiveCaptureSingle(), and RunModeSetLiveCaptureWorkers().
char* LiveGetDeviceName (int number)
Get a pointer to the device name at idx.
Parameters
number idx of the device in our list
Return values
ptr pointer to the string containing the device
NULL on error
Definition at line 92 of file util-device.c.
References LiveDevice_::dev, next, and TAILQ_FOREACH.
Referenced by AFPRunModeIsIPS(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), RunModeSetLiveCaptureSingle(), and RunModeSetLiveCaptureWorkers().
int LiveRegisterDevice (char * dev)
Referenced by IPFWRegisterQueue(), LiveBuildDeviceListCustom(), NapatechRegisterDeviceStreams(), and NFQRegisterQueue().