suricata: src/util-mpm.c File Reference
util-mpm.c File Reference
#include "suricata-common.h"
#include "util-mpm.h"
#include "util-debug.h"
#include "util-mpm-wumanber.h"
#include "util-mpm-b2g.h"
#include "util-mpm-b3g.h"
#include "util-mpm-ac.h"
#include "util-mpm-ac-gfbs.h"
#include "util-mpm-ac-bs.h"
#include "util-mpm-ac-tile.h"
#include "util-hashlist.h"
#include "detect-engine.h"
#include "util-cuda.h"
#include "util-misc.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "queue.h"
#include "util-unittest.h"
Functions
int32_t MpmFactoryRegisterMpmCtxProfile (DetectEngineCtx *de_ctx, const char *name, uint8_t flags)
Register a new Mpm Context.
int32_t MpmFactoryIsMpmCtxAvailable (DetectEngineCtx *de_ctx, MpmCtx *mpm_ctx)
MpmCtx * MpmFactoryGetMpmCtxForProfile (DetectEngineCtx *de_ctx, int32_t id, int direction)
void MpmFactoryReClaimMpmCtx (DetectEngineCtx *de_ctx, MpmCtx *mpm_ctx)
void MpmFactoryDeRegisterAllMpmCtxProfiles (DetectEngineCtx *de_ctx)
int PmqSetup (PatternMatcherQueue *pmq, uint32_t patmaxid)
Setup a pmq.
int MpmAddSidsResize (PatternMatcherQueue *pmq, uint32_t new_size)
Add array of Signature IDs to rule ID array.
int MpmAddPidResize (PatternMatcherQueue *pmq, uint32_t new_size)
Increase the size of the Pattern rule ID array.
int MpmVerifyMatch (MpmThreadCtx *thread_ctx, PatternMatcherQueue *pmq, uint32_t patid, uint8_t *bitarray, SigIntId *sids, uint32_t sids_size)
Verify and store a match.
void PmqMerge (PatternMatcherQueue *src, PatternMatcherQueue *dst)
Merge two pmq's bitarrays.
void PmqReset (PatternMatcherQueue *pmq)
Reset a Pmq for reusage. Meant to be called after a single search.
void PmqCleanup (PatternMatcherQueue *pmq)
Cleanup a Pmq.
void PmqFree (PatternMatcherQueue *pmq)
Cleanup and free a Pmq.
void MpmInitThreadCtx (MpmThreadCtx *mpm_thread_ctx, uint16_t matcher, uint32_t max_id)
void MpmInitCtx (MpmCtx *mpm_ctx, uint16_t matcher)
void MpmTableSetup (void)
uint32_t MpmGetHashSize (const char *conf_val)
Function to return the default hash size for the mpm algorithm, which has been defined by the user in the config file.
uint32_t MpmGetBloomSize (const char *conf_val)
Function to return the default bloomfilter size for the mpm algorithm, which has been defined by the user in the config file.
int MpmAddPatternCS (struct MpmCtx_ *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
int MpmAddPatternCI (struct MpmCtx_ *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
void MpmRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pattern matcher utility Functions
Definition in file util-mpm.c.
Function Documentation
int MpmAddPatternCI (struct MpmCtx_ * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 747 of file util-mpm.c.
References MpmTableElmt_::AddPatternNocase, mpm_table, and MpmCtx_::mpm_type.
int MpmAddPatternCS (struct MpmCtx_ * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 738 of file util-mpm.c.
References MpmTableElmt_::AddPattern, mpm_table, and MpmCtx_::mpm_type.
int MpmAddPidResize (PatternMatcherQueue * pmq, uint32_t new_size)
Increase the size of the Pattern rule ID array.
Parameters
pmq storage for match results
new_size number of Signature IDs needing to be stored.
Returns
0 on failure.
Definition at line 512 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_array, PatternMatcherQueue_::pattern_id_array_size, SC_ERR_MEM_ALLOC, SCLogError, SCRealloc, and unlikely.
int MpmAddSidsResize (PatternMatcherQueue * pmq, uint32_t new_size)
Add array of Signature IDs to rule ID array.
Checks size of the array first
Parameters
pmq storage for match results
new_size number of Signature IDs needing to be stored.
Definition at line 477 of file util-mpm.c.
References PatternMatcherQueue_::rule_id_array, PatternMatcherQueue_::rule_id_array_size, SC_ERR_MEM_ALLOC, SCLogError, SCRealloc, SigIntId, and unlikely.
void MpmFactoryDeRegisterAllMpmCtxProfiles (DetectEngineCtx * de_ctx)
Definition at line 246 of file util-mpm.c.
References MpmTableElmt_::DestroyCtx, MpmCtxFactoryContainer_::items, DetectEngineCtx_::mpm_ctx_factory_container, MpmCtxFactoryItem_::mpm_ctx_tc, MpmCtxFactoryItem_::mpm_ctx_ts, MPM_NOTSET, mpm_table, MpmCtx_::mpm_type, MpmCtxFactoryContainer_::no_of_items, and SCFree.
Referenced by DetectEngineCtxFree().
MpmCtx* MpmFactoryGetMpmCtxForProfile (DetectEngineCtx * de_ctx, int32_t id, int direction)
Definition at line 209 of file util-mpm.c.
References MpmCtxFactoryContainer_::items, DetectEngineCtx_::mpm_ctx_factory_container, MPM_CTX_FACTORY_UNIQUE_CONTEXT, MpmCtxFactoryItem_::mpm_ctx_tc, MpmCtxFactoryItem_::mpm_ctx_ts, MpmCtxFactoryContainer_::no_of_items, SC_ERR_INVALID_ARGUMENTS, SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, and unlikely.
Referenced by PatternMatchPrepareGroup(), and SigGroupBuild().
int32_t MpmFactoryIsMpmCtxAvailable (DetectEngineCtx * de_ctx, MpmCtx * mpm_ctx)
Definition at line 190 of file util-mpm.c.
References MpmCtxFactoryContainer_::items, DetectEngineCtx_::mpm_ctx_factory_container, MpmCtxFactoryItem_::mpm_ctx_tc, MpmCtxFactoryItem_::mpm_ctx_ts, and MpmCtxFactoryContainer_::no_of_items.
Referenced by MpmFactoryReClaimMpmCtx().
void MpmFactoryReClaimMpmCtx (DetectEngineCtx * de_ctx, MpmCtx * mpm_ctx)
Definition at line 232 of file util-mpm.c.
References MpmTableElmt_::DestroyCtx, MPM_NOTSET, mpm_table, MpmCtx_::mpm_type, MpmFactoryIsMpmCtxAvailable(), and SCFree.
Referenced by PatternMatchPrepareGroup().
int32_t MpmFactoryRegisterMpmCtxProfile (DetectEngineCtx * de_ctx, const char * name, uint8_t flags)
Register a new Mpm Context.
Parameters
name A new profile to be registered to store this MpmCtx.
Return values
id Return the id created for the new MpmCtx profile.
Definition at line 59 of file util-mpm.c.
References flags, MpmCtxFactoryItem_::flags, MpmCtx_::global, MpmCtxFactoryItem_::id, MpmCtxFactoryContainer_::items, DetectEngineCtx_::mpm_ctx_factory_container, MpmCtxFactoryItem_::mpm_ctx_tc, MpmCtxFactoryItem_::mpm_ctx_ts, MpmCtxFactoryItem_::name, MpmCtxFactoryContainer_::no_of_items, SC_ERR_MEM_ALLOC, SCFree, SCLogError, SCMalloc, SCRealloc, SCStrdup, and unlikely.
uint32_t MpmGetBloomSize (const char * conf_val)
Function to return the default bloomfilter size for the mpm algorithm, which has been defined by the user in the config file.
Parameters
conf_val pointer to the string value of bloom filter size
Return values
bloom_value returns the bloom filter value as defined by user, otherwise default medium size value
Definition at line 722 of file util-mpm.c.
References BLOOMSIZE_HIGH, BLOOMSIZE_LOW, BLOOMSIZE_MEDIUM, SCEnter, and SCReturnInt.
Referenced by B3gGetConfig(), and WmGetConfig().
uint32_t MpmGetHashSize (const char * conf_val)
Function to return the default hash size for the mpm algorithm, which has been defined by the user in the config file.
Parameters
conf_val pointer to the string value of hash size
Return values
hash_value returns the hash value as defined by user, otherwise default low size value
Definition at line 689 of file util-mpm.c.
References HASHSIZE_HIGH, HASHSIZE_HIGHER, HASHSIZE_LOW, HASHSIZE_LOWEST, HASHSIZE_MAX, HASHSIZE_MEDIUM, SCEnter, and SCReturnInt.
Referenced by B3gGetConfig(), and WmGetConfig().
void MpmInitCtx (MpmCtx * mpm_ctx, uint16_t matcher)
Definition at line 660 of file util-mpm.c.
References MpmTableElmt_::InitCtx, mpm_table, and MpmCtx_::mpm_type.
Referenced by AppLayerProtoDetectSetup(), PatternMatchPrepare(), and PatternMatchPrepareGroup().
void MpmInitThreadCtx (MpmThreadCtx * mpm_thread_ctx, uint16_t matcher, uint32_t max_id)
Definition at line 655 of file util-mpm.c.
References MpmTableElmt_::InitThreadCtx, and mpm_table.
Referenced by PatternMatchThreadPrepare().
void MpmRegisterTests (void)
Definition at line 763 of file util-mpm.c.
References coverage_unittests, g_ut_covered, g_ut_modules, MPM_NOTSET, mpm_table, MPM_TABLE_SIZE, MpmTableElmt_::RegisterUnittests, SC_WARN_NO_UNITTESTS, and SCLogWarning.
Referenced by RunUnittests().
void MpmTableSetup (void)
Definition at line 666 of file util-mpm.c.
References mpm_table, MpmACBSRegister(), MpmACGfbsRegister(), MpmACRegister(), MpmACTileRegister(), MpmB2gRegister(), MpmB3gRegister(), and MpmWuManberRegister().
Referenced by ListAppLayerProtocols(), ListKeywords(), and RunUnittests().
int MpmVerifyMatch (MpmThreadCtx * thread_ctx, PatternMatcherQueue * pmq, uint32_t patid, uint8_t * bitarray, SigIntId * sids, uint32_t sids_size)
Verify and store a match.
used at search runtime
Parameters
thread_ctx mpm thread ctx
pmq storage for match results
patid pattern ID being checked
bitarray Array of bits for patterns IDs found in current search
sids pointer to array of Signature IDs
sids_size number of Signature IDs in sids array.
Return values
0 no match after all
1 (new) match
Definition at line 553 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_bitarray, SCEnter, SCLogDebug, and SCReturnInt.
Referenced by B2gSearch(), B2gSearch1(), B2gSearchBNDMq(), B3gSearch(), B3gSearch1(), B3gSearch12(), B3gSearch2(), B3gSearchBNDMq(), WmSearch1(), WmSearch2Hash12(), WmSearch2Hash14(), WmSearch2Hash15(), WmSearch2Hash16(), and WmSearch2Hash9().
void PmqCleanup (PatternMatcherQueue * pmq)
Cleanup a Pmq.
Parameters
pmq Pattern matcher queue to be cleaned up.
Definition at line 620 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_array, PatternMatcherQueue_::pattern_id_array_cnt, PatternMatcherQueue_::pattern_id_array_size, PatternMatcherQueue_::pattern_id_bitarray, PatternMatcherQueue_::rule_id_array, and SCFree.
Referenced by PmqFree().
void PmqFree (PatternMatcherQueue * pmq)
Cleanup and free a Pmq.
Parameters
pmq Pattern matcher queue to be free'd.
Definition at line 647 of file util-mpm.c.
References PmqCleanup().
Referenced by AppLayerProtoDetectDestroyCtxThread(), and DetectEngineThreadCtxFree().
void PmqMerge (PatternMatcherQueue * src, PatternMatcherQueue * dst)
Merge two pmq's bitarrays.
Parameters
src source pmq
dst destination pmq to merge into
Todo:
now set merged flag?
Definition at line 581 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_array_cnt, PatternMatcherQueue_::pattern_id_bitarray, PatternMatcherQueue_::pattern_id_bitarray_size, PatternMatcherQueue_::rule_id_array, and PatternMatcherQueue_::rule_id_array_cnt.
Referenced by StreamPatternSearch().
void PmqReset (PatternMatcherQueue * pmq)
Reset a Pmq for reusage. Meant to be called after a single search.
Parameters
pmq Pattern matcher to be reset.
Todo:
memset is expensive, but we need it as we merge pmq's. We might use a flag so we can clear pmq's the old way if we can.
Definition at line 604 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_array_cnt, PatternMatcherQueue_::pattern_id_bitarray, PatternMatcherQueue_::pattern_id_bitarray_size, and PatternMatcherQueue_::rule_id_array_cnt.
Referenced by PacketPatternCleanup(), and StreamPatternCleanup().
int PmqSetup (PatternMatcherQueue * pmq, uint32_t patmaxid)
Setup a pmq.
Parameters
pmq Pattern matcher queue to be initialized
maxid Max sig id to be matched on
patmaxid Max pattern id to be matched on
Return values
-1 error
0 ok
Definition at line 421 of file util-mpm.c.
References PatternMatcherQueue_::pattern_id_array, PatternMatcherQueue_::pattern_id_array_cnt, PatternMatcherQueue_::pattern_id_array_size, PatternMatcherQueue_::pattern_id_bitarray, PatternMatcherQueue_::pattern_id_bitarray_size, PatternMatcherQueue_::rule_id_array, PatternMatcherQueue_::rule_id_array_cnt, PatternMatcherQueue_::rule_id_array_size, SCCalloc, SCEnter, SCLogDebug, SCMalloc, SCReturnInt, and SigIntId.
Referenced by AppLayerProtoDetectGetCtxThread().