suricata: src/util-mpm-ac.c File Reference
util-mpm-ac.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "conf.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-memcmp.h"
#include "util-mpm-ac.h"
#include "util-memcpy.h"
Data Structures
struct StateQueue_
Helper structure used by AC during state table creation.
Macros
#define SC_AC_FAIL (-1)
#define INIT_HASH_SIZE 65536
#define STATE_QUEUE_CONTAINER_SIZE 65536
Typedefs
typedef struct StateQueue_ StateQueue
Helper structure used by AC during state table creation.
Functions
void SCACInitCtx (MpmCtx *mpm_ctx)
Initialize the AC context.
void SCACInitThreadCtx (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, uint32_t matchsize)
Init the mpm thread context.
void SCACDestroyCtx (MpmCtx *mpm_ctx)
Destroy the mpm context.
void SCACDestroyThreadCtx (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx)
Destroy the mpm thread context.
int SCACAddPatternCI (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case insensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
int SCACAddPatternCS (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case sensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
int SCACPreparePatterns (MpmCtx *mpm_ctx)
Process the patterns added to the mpm, and create the internal tables.
uint32_t SCACSearch (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PatternMatcherQueue *pmq, uint8_t *buf, uint16_t buflen)
The aho corasick search function.
void SCACPrintInfo (MpmCtx *mpm_ctx)
void SCACPrintSearchStats (MpmThreadCtx *mpm_thread_ctx)
void SCACRegisterTests (void)
void MpmACRegister (void)
Register the aho-corasick mpm.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
    First iteration of aho-corasick MPM from -
    Efficient String Matching: An Aid to Bibliographic Search
    Alfred V. Aho and Margaret J. Corasick
    - Uses the delta table for calculating transitions, instead of having
      separate goto and failure transitions.
    - If we cross 2 ** 16 states, we use 4 bytes in the transition table
      to hold each state, otherwise we use 2 bytes.
    - This version of the MPM is heavy on memory, but it performs well.
      If you can fit the ruleset with this mpm on your box without hitting
      swap, this is the MPM to go for.
Todo:
Do a proper analyis of our existing MPMs and suggest a good one based on the pattern distribution and the expected traffic(say http).
Tried out loop unrolling without any perf increase. Need to dig deeper.
Irrespective of whether we cross 2 ** 16 states or not,shift to using uint32_t for state type, so that we can integrate it's status as a final state or not in the topmost byte. We are already doing it if state_count is > 2 ** 16.
Test case-senstive patterns if they have any ascii chars. If they don't treat them as nocase.
Carry out other optimizations we are working on. hashes, compression.
Definition in file util-mpm-ac.c.
Macro Definition Documentation
#define INIT_HASH_SIZE 65536
Definition at line 90 of file util-mpm-ac.c.
Referenced by SCACDestroyCtx(), SCACInitCtx(), and SCACPreparePatterns().
#define SC_AC_FAIL (-1)
Definition at line 88 of file util-mpm-ac.c.
#define STATE_QUEUE_CONTAINER_SIZE 65536
Definition at line 92 of file util-mpm-ac.c.
Typedef Documentation
typedef struct StateQueue_ StateQueue
Helper structure used by AC during state table creation.
Function Documentation
void MpmACRegister (void)
Register the aho-corasick mpm.
Definition at line 2226 of file util-mpm-ac.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::Cleanup, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MpmTableElmt_::max_pattern_length, MPM_AC, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, SCACAddPatternCI(), SCACAddPatternCS(), SCACDestroyCtx(), SCACDestroyThreadCtx(), SCACInitCtx(), SCACInitThreadCtx(), SCACPreparePatterns(), SCACPrintInfo(), SCACPrintSearchStats(), SCACRegisterTests(), SCACSearch(), and MpmTableElmt_::Search.
Referenced by MpmTableSetup().
int SCACAddPatternCI (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case insensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
Parameters
mpm_ctx Pointer to the mpm context.
pat The pattern to add.
patnen The pattern length.
offset Ignored.
depth Ignored.
pid The pattern id.
sid Ignored.
flags Flags associated with this pattern.
Return values
0 On success.
-1 On failure.
Definition at line 1429 of file util-mpm-ac.c.
References MPM_PATTERN_FLAG_NOCASE.
Referenced by MpmACRegister().
int SCACAddPatternCS (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case sensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
Parameters
mpm_ctx Pointer to the mpm context.
pat The pattern to add.
patnen The pattern length.
offset Ignored.
depth Ignored.
pid The pattern id.
sid Ignored.
flags Flags associated with this pattern.
Return values
0 On success.
-1 On failure.
Definition at line 1454 of file util-mpm-ac.c.
Referenced by MpmACRegister().
void SCACDestroyCtx (MpmCtx * mpm_ctx)
Destroy the mpm context.
Parameters
mpm_ctx Pointer to the mpm context.
Definition at line 1221 of file util-mpm-ac.c.
References SCACPatternList_::cs, MpmCtx_::ctx, SCACCtx_::init_hash, INIT_HASH_SIZE, SCACCtx_::max_pat_id, MpmCtx_::memory_cnt, MpmCtx_::memory_size, SCACCtx_::output_table, SCACCtx_::parray, MpmCtx_::pattern_cnt, SCACCtx_::pid_pat_list, SCACOutputTable_::pids, SC_AC_STATE_TYPE_U16, SC_AC_STATE_TYPE_U32, SCFree, SCACPatternList_::sids, SCACCtx_::state_count, SCACCtx_::state_table_u16, and SCACCtx_::state_table_u32.
Referenced by MpmACRegister().
void SCACDestroyThreadCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx)
Destroy the mpm thread context.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
Definition at line 1202 of file util-mpm-ac.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, SCACPrintSearchStats(), and SCFree.
Referenced by MpmACRegister().
void SCACInitCtx (MpmCtx * mpm_ctx)
Initialize the AC context.
Parameters
mpm_ctx Mpm context.
Definition at line 1167 of file util-mpm-ac.c.
References MpmCtx_::ctx, SCACCtx_::init_hash, INIT_HASH_SIZE, MpmCtx_::memory_cnt, MpmCtx_::memory_size, SCMalloc, and SCReturn.
Referenced by MpmACRegister().
void SCACInitThreadCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, uint32_t matchsize)
Init the mpm thread context.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
matchsize We don't need this.
Definition at line 1147 of file util-mpm-ac.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, and SCMalloc.
Referenced by MpmACRegister().
int SCACPreparePatterns (MpmCtx * mpm_ctx)
Process the patterns added to the mpm, and create the internal tables.
Parameters
mpm_ctx Pointer to the mpm context.
Definition at line 1035 of file util-mpm-ac.c.
References SCACPatternList_::cs, MpmCtx_::ctx, SCACPattern_::flags, SCACPattern_::id, SCACCtx_::init_hash, INIT_HASH_SIZE, SCACPattern_::len, SCACCtx_::max_pat_id, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MPM_PATTERN_FLAG_NOCASE, MpmCtx_::mpm_type, SCACPattern_::next, SCACPattern_::original_pat, SCACCtx_::parray, SCACPatternList_::patlen, MpmCtx_::pattern_cnt, SCACCtx_::pid_pat_list, SC_ERR_AC_CUDA_ERROR, SC_ERR_MEM_ALLOC, SCFree, SCLogDebug, SCLogError, SCMalloc, SCACPattern_::sids, SCACPatternList_::sids, SCACPattern_::sids_size, SCACPatternList_::sids_size, SCACCtx_::single_state_size, SCACCtx_::state_count, and SCACCtx_::state_table_u32.
Referenced by MpmACRegister().
void SCACPrintInfo (MpmCtx * mpm_ctx)
Definition at line 1474 of file util-mpm-ac.c.
References MpmCtx_::ctx, MpmCtx_::maxlen, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmCtx_::minlen, MpmCtx_::pattern_cnt, and SCACCtx_::state_count.
Referenced by MpmACRegister().
void SCACPrintSearchStats (MpmThreadCtx * mpm_thread_ctx)
Definition at line 1461 of file util-mpm-ac.c.
References MpmThreadCtx_::ctx, SCACThreadCtx_::total_calls, and SCACThreadCtx_::total_matches.
Referenced by MpmACRegister(), and SCACDestroyThreadCtx().
void SCACRegisterTests (void)
Definition at line 3305 of file util-mpm-ac.c.
Referenced by MpmACRegister().
uint32_t SCACSearch (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PatternMatcherQueue * pmq, uint8_t * buf, uint16_t buflen)
The aho corasick search function.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
pmq Pointer to the Pattern Matcher Queue to hold search matches.
buf Buffer to be searched.
buflen Buffer length.
Return values
matches Match count.
Definition at line 1305 of file util-mpm-ac.c.
References MpmCtx_::ctx, SCACOutputTable_::no_of_entries, SCACCtx_::output_table, PatternMatcherQueue_::pattern_id_bitarray, PatternMatcherQueue_::pattern_id_bitarray_size, SCACCtx_::pid_pat_list, SCACOutputTable_::pids, SC_AC_STATE_TYPE_U16, SC_AC_STATE_TYPE_U32, SCMemcmp, SCACCtx_::state_count, SCACCtx_::state_table_u16, SCACCtx_::state_table_u32, and u8_tolower.
Referenced by MpmACRegister().