suricata: src/util-profiling-rules.c File Reference
util-profiling-rules.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "conf.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-byte.h"
#include "util-profiling.h"
#include "util-profiling-locks.h"
Data Structures
struct SCProfileData_
struct SCProfileDetectCtx_
struct SCProfileSummary_
Typedefs
typedef struct SCProfileData_ SCProfileData
typedef struct SCProfileDetectCtx_ SCProfileDetectCtx
typedef struct SCProfileSummary_ SCProfileSummary
Enumerations
enum {
SC_PROFILING_RULES_SORT_BY_TICKS = 0, SC_PROFILING_RULES_SORT_BY_AVG_TICKS, SC_PROFILING_RULES_SORT_BY_CHECKS, SC_PROFILING_RULES_SORT_BY_MATCHES,
SC_PROFILING_RULES_SORT_BY_MAX_TICKS, SC_PROFILING_RULES_SORT_BY_AVG_TICKS_MATCH, SC_PROFILING_RULES_SORT_BY_AVG_TICKS_NO_MATCH
}
Functions
void SCProfilingRulesGlobalInit (void)
void SCProfilingRuleDump (SCProfileDetectCtx *rules_ctx)
Dump rule profiling information to file.
void SCProfilingRuleUpdateCounter (DetectEngineThreadCtx *det_ctx, uint16_t id, uint64_t ticks, int match)
Update a rule counter.
SCProfileDetectCtx * SCProfilingRuleInitCtx (void)
void SCProfilingRuleDestroyCtx (SCProfileDetectCtx *ctx)
void SCProfilingRuleThreadSetup (SCProfileDetectCtx *ctx, DetectEngineThreadCtx *det_ctx)
void SCProfilingRuleThreadCleanup (DetectEngineThreadCtx *det_ctx)
void SCProfilingRuleInitCounters (DetectEngineCtx *de_ctx)
Register the rule profiling counters.
Variables
int profiling_output_to_file
int profiling_rules_enabled = 0
Detailed Description
Author
Endace Technology Limited.
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
An API for rule profiling operations.
Definition in file util-profiling-rules.c.
Typedef Documentation
typedef struct SCProfileData_ SCProfileData
Extra data for rule profiling.
typedef struct SCProfileDetectCtx_ SCProfileDetectCtx
typedef struct SCProfileSummary_ SCProfileSummary
Used for generating the summary data to print.
Enumeration Type Documentation
anonymous enum
Sort orders for dumping profiled rules.
Enumerator
SC_PROFILING_RULES_SORT_BY_TICKS
SC_PROFILING_RULES_SORT_BY_AVG_TICKS
SC_PROFILING_RULES_SORT_BY_CHECKS
SC_PROFILING_RULES_SORT_BY_MATCHES
SC_PROFILING_RULES_SORT_BY_MAX_TICKS
SC_PROFILING_RULES_SORT_BY_AVG_TICKS_MATCH
SC_PROFILING_RULES_SORT_BY_AVG_TICKS_NO_MATCH
Definition at line 89 of file util-profiling-rules.c.
Function Documentation
void SCProfilingRuleDestroyCtx (SCProfileDetectCtx * ctx)
Definition at line 583 of file util-profiling-rules.c.
References SCProfileDetectCtx_::data, SCProfileDetectCtx_::data_m, SCFree, and SCProfilingRuleDump().
Referenced by DetectEngineCtxFree().
void SCProfilingRuleDump (SCProfileDetectCtx * rules_ctx)
Dump rule profiling information to file.
Parameters
de_ctx The active DetectEngineCtx, used to get at the loaded rules.
Definition at line 425 of file util-profiling-rules.c.
References SCProfileSummary_::avgticks, SCProfileSummary_::avgticks_match, SCProfileSummary_::avgticks_no_match, SCProfileData_::checks, SCProfileSummary_::checks, SCProfileDetectCtx_::data, SCProfileData_::gid, SCProfileSummary_::gid, SCProfileData_::matches, SCProfileSummary_::matches, SCProfileData_::max, SCProfileSummary_::max, profiling_file_name, profiling_output_to_file, SCProfileData_::rev, SCProfileSummary_::rev, SC_ERR_FOPEN, SC_ERR_MEM_ALLOC, SC_PROFILING_RULES_SORT_BY_AVG_TICKS, SC_PROFILING_RULES_SORT_BY_AVG_TICKS_MATCH, SC_PROFILING_RULES_SORT_BY_AVG_TICKS_NO_MATCH, SC_PROFILING_RULES_SORT_BY_CHECKS, SC_PROFILING_RULES_SORT_BY_MATCHES, SC_PROFILING_RULES_SORT_BY_MAX_TICKS, SC_PROFILING_RULES_SORT_BY_TICKS, SCFree, SCLogError, SCLogInfo, SCMalloc, SCProfileData_::sid, SCProfileSummary_::sid, SCProfileDetectCtx_::size, SCProfileSummary_::ticks, SCProfileData_::ticks_match, SCProfileSummary_::ticks_match, SCProfileData_::ticks_no_match, SCProfileSummary_::ticks_no_match, and unlikely.
Referenced by SCProfilingRuleDestroyCtx().
void SCProfilingRuleInitCounters (DetectEngineCtx * de_ctx)
Register the rule profiling counters.
Parameters
de_ctx The active DetectEngineCtx, used to get at the loaded rules.
Definition at line 645 of file util-profiling-rules.c.
References BUG_ON, SCProfileDetectCtx_::data, SCProfileData_::gid, Signature_::gid, Signature_::id, Signature_::next, DetectEngineCtx_::profile_ctx, Signature_::profiling_id, profiling_rules_enabled, SCProfileData_::rev, Signature_::rev, SCLogInfo, SCMalloc, SCProfilingRuleInitCtx(), SCProfileData_::sid, DetectEngineCtx_::sig_list, and SCProfileDetectCtx_::size.
Referenced by SigGroupBuild().
SCProfileDetectCtx* SCProfilingRuleInitCtx (void)
Definition at line 567 of file util-profiling-rules.c.
References SCProfileDetectCtx_::data_m, SC_ERR_MUTEX, SCLogError, and SCMalloc.
Referenced by SCProfilingRuleInitCounters().
void SCProfilingRulesGlobalInit (void)
Definition at line 105 of file util-profiling-rules.c.
References ByteExtractStringUint32(), ConfGetNode(), ConfigGetLogDirectory(), ConfNodeChildValueIsTrue(), ConfNodeLookupChildValue(), ConfValIsTrue(), profiling_file_name, profiling_output_to_file, profiling_rules_enabled, SC_ERR_INVALID_ARGUMENT, SC_ERR_MEM_ALLOC, SC_ERR_NO_JSON_SUPPORT, SC_PROFILING_RULES_SORT_BY_AVG_TICKS, SC_PROFILING_RULES_SORT_BY_AVG_TICKS_MATCH, SC_PROFILING_RULES_SORT_BY_AVG_TICKS_NO_MATCH, SC_PROFILING_RULES_SORT_BY_CHECKS, SC_PROFILING_RULES_SORT_BY_MATCHES, SC_PROFILING_RULES_SORT_BY_MAX_TICKS, SC_PROFILING_RULES_SORT_BY_TICKS, SCLogError, SCLogWarning, SCMalloc, and unlikely.
void SCProfilingRuleThreadCleanup (DetectEngineThreadCtx * det_ctx)
Definition at line 625 of file util-profiling-rules.c.
References SCProfileDetectCtx_::data_m, DetectEngineThreadCtx_::de_ctx, DetectEngineCtx_::profile_ctx, DetectEngineThreadCtx_::rule_perf_data, DetectEngineThreadCtx_::rule_perf_data_size, and SCFree.
Referenced by DetectEngineThreadCtxFree().
void SCProfilingRuleThreadSetup (SCProfileDetectCtx * ctx, DetectEngineThreadCtx * det_ctx)
Definition at line 594 of file util-profiling-rules.c.
References DetectEngineThreadCtx_::rule_perf_data, DetectEngineThreadCtx_::rule_perf_data_size, SCMalloc, and SCProfileDetectCtx_::size.
void SCProfilingRuleUpdateCounter (DetectEngineThreadCtx * det_ctx, uint16_t id, uint64_t ticks, int match)
Update a rule counter.
Parameters
id The ID of this counter.
ticks Number of CPU ticks for this rule.
match Did the rule match?
Definition at line 551 of file util-profiling-rules.c.
References SCProfileData_::checks, SCProfileData_::matches, SCProfileData_::max, DetectEngineThreadCtx_::rule_perf_data, DetectEngineThreadCtx_::rule_perf_data_size, SCProfileData_::ticks_match, and SCProfileData_::ticks_no_match.
Variable Documentation
int profiling_output_to_file
Definition at line 92 of file util-profiling.c.
Referenced by SCProfilingRuleDump(), and SCProfilingRulesGlobalInit().
int profiling_rules_enabled = 0
Definition at line 81 of file util-profiling-rules.c.
Referenced by main(), SCProfilingRuleInitCounters(), and SCProfilingRulesGlobalInit().