suricata: src/util-action.c File Reference
util-action.c File Reference
#include "suricata-common.h"
#include "action-globals.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-sigorder.h"
#include "util-unittest.h"
#include "util-action.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
Functions
uint8_t ActionOrderVal (uint8_t action)
Return the priority associated to an action (to order sigs as specified at config) action_order_sigs has this priority by index val so action_order_sigs[0] has to be inspected first. This function is called from detect-engine-sigorder.
uint8_t ActionAsciiToFlag (char *action)
Return the ACTION_* bit from their ascii value.
int ActionInitConfig ()
Load the action order from config. If none is provided, it will be default to ACTION_PASS, ACTION_DROP, ACTION_REJECT, ACTION_ALERT (pass has the highest prio)
void UtilActionRegisterTests (void)
Variables
uint8_t action_order_sigs [4] = {ACTION_PASS, ACTION_DROP, ACTION_REJECT, ACTION_ALERT}
Detailed Description
Author
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file util-action.c.
Function Documentation
uint8_t ActionAsciiToFlag (char * action)
Return the ACTION_* bit from their ascii value.
Parameters
action can be one of "pass", "drop", "reject" or "alert"
Return values
uint8_t can be one of ACTION_PASS, ACTION_DROP, ACTION_REJECT or ACTION_ALERT
Definition at line 77 of file util-action.c.
References ACTION_ALERT, ACTION_DROP, ACTION_PASS, and ACTION_REJECT.
Referenced by ActionInitConfig().
int ActionInitConfig ()
Load the action order from config. If none is provided, it will be default to ACTION_PASS, ACTION_DROP, ACTION_REJECT, ACTION_ALERT (pass has the highest prio)
Return values
0 on success; -1 on fatal error;
Definition at line 98 of file util-action.c.
References action_order_sigs, ActionAsciiToFlag(), ConfGetNode(), next, SC_ERR_ACTION_ORDER, SCLogDebug, SCLogError, TAILQ_FOREACH, and ConfNode_::val.
uint8_t ActionOrderVal (uint8_t action)
Return the priority associated to an action (to order sigs as specified at config) action_order_sigs has this priority by index val so action_order_sigs[0] has to be inspected first. This function is called from detect-engine-sigorder.
Parameters
action can be one of ACTION_PASS, ACTION_DROP, ACTION_REJECT or ACTION_ALERT
Return values
uint8_t the priority (order of this actions)
Definition at line 53 of file util-action.c.
References action_order_sigs, ACTION_REJECT, ACTION_REJECT_BOTH, and ACTION_REJECT_DST.
void UtilActionRegisterTests (void)
Definition at line 1597 of file util-action.c.
Referenced by RunUnittests().
Variable Documentation
uint8_t action_order_sigs[4] = {ACTION_PASS, ACTION_DROP, ACTION_REJECT, ACTION_ALERT}
Definition at line 40 of file util-action.c.
Referenced by ActionInitConfig(), and ActionOrderVal().