suricata: src/util-signal.h File Reference
util-signal.h File Reference
Functions
int UtilSignalBlock (int)
void UtilSignalHandlerSetup (int, void(*handler)())
int UtilSignalIsHandler (int sig, void(*handler)())
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-signal.h.
Function Documentation
int UtilSignalBlock (int)
Definition at line 28 of file util-signal.c.
Referenced by TmThreadsSlotPktAcqLoop(), and TmThreadsSlotVar().
void UtilSignalHandlerSetup (int , void(*)() handler)
Definition at line 41 of file util-signal.c.
Referenced by main().
int UtilSignalIsHandler (int sig, void(*)() handler)
Definition at line 59 of file util-signal.c.