suricata: src/util-time.c File Reference
util-time.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "threads.h"
#include "util-debug.h"
Functions
struct tm * SCLocalTime (time_t timep, struct tm *result)
void TimeInit (void)
void TimeDeinit (void)
void TimeModeSetLive (void)
void TimeModeSetOffline (void)
void TimeSet (struct timeval *tv)
void TimeSetToCurrentTime (void)
set the time to "gettimeofday" meant for testing
void TimeGet (struct timeval *tv)
void TimeSetIncrementTime (uint32_t tv_sec)
increment the time in the engine
void CreateIsoTimeString (const struct timeval *ts, char *str, size_t size)
void CreateTimeString (const struct timeval *ts, char *str, size_t size)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Ken Steele suric.nosp@m.ata@.nosp@m.tiler.nosp@m.a.co.nosp@m.m
Time keeping for offline (non-live) packet handling (pcap files). And time string generation for alerts.
Definition in file util-time.c.
Function Documentation
void CreateIsoTimeString (const struct timeval * ts, char * str, size_t size)
Definition at line 126 of file util-time.c.
References likely, and SCLocalTime().
void CreateTimeString (const struct timeval * ts, char * str, size_t size)
Definition at line 153 of file util-time.c.
References likely, and SCLocalTime().
Referenced by AlertFastLogger().
struct tm * SCLocalTime (time_t timep, struct tm * result)
Definition at line 148 of file util-time.c.
Referenced by CreateIsoTimeString(), CreateTimeString(), LogStatsLogger(), SCProfilingKeywordDump(), SetupFPAnalyzer(), and SetupRuleAnalyzer().
void TimeDeinit (void)
Definition at line 49 of file util-time.c.
References SCSpinDestroy.
Referenced by main().
void TimeGet (struct timeval * tv)
Definition at line 95 of file util-time.c.
References SCLogDebug, SCSpinLock, SCSpinUnlock, and TRUE.
Referenced by PcapCallbackLoop(), ReceiveAFPLoop(), TimeSetIncrementTime(), and Unified2AlertOpenFileCtx().
void TimeInit (void)
Definition at line 41 of file util-time.c.
References SCSpinInit.
Referenced by main(), and RunUnittests().
void TimeModeSetLive (void)
Definition at line 54 of file util-time.c.
References SCLogDebug, and TRUE.
Referenced by RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), RunModeIdsAFPWorkers(), RunModeIdsErfDagAutoFp(), RunModeIdsErfDagSingle(), RunModeIdsErfDagWorkers(), RunModeIdsNetmapAutoFp(), RunModeIdsNetmapSingle(), RunModeIdsNetmapWorkers(), RunModeIdsNflogAutoFp(), RunModeIdsNflogSingle(), RunModeIdsNflogWorkers(), RunModeIdsPcapAutoFp(), RunModeIdsPcapSingle(), RunModeIdsPcapWorkers(), RunModeIdsPfringAutoFp(), RunModeIdsPfringSingle(), RunModeIdsPfringWorkers(), RunModeIpsIPFWAutoFp(), RunModeIpsIPFWWorker(), RunModeIpsNFQAutoFp(), and RunModeIpsNFQWorker().
void TimeModeSetOffline (void)
Definition at line 60 of file util-time.c.
References FALSE, and SCLogDebug.
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), and RunModeFilePcapSingle().
void TimeSet (struct timeval * tv)
Definition at line 66 of file util-time.c.
References SCLogDebug, SCSpinLock, SCSpinUnlock, and TRUE.
Referenced by DecodePcapFile(), TimeSetIncrementTime(), and TimeSetToCurrentTime().
void TimeSetIncrementTime (uint32_t tv_sec)
increment the time in the engine
Parameters
tv_sec seconds to increment the time with
Definition at line 115 of file util-time.c.
References TimeGet(), and TimeSet().
void TimeSetToCurrentTime (void)
set the time to "gettimeofday" meant for testing
Definition at line 85 of file util-time.c.
References TimeSet().