suricata: src/win32-misc.h File Reference
win32-misc.h File Reference
Macros
#define index strchr
#define rindex strrchr
#define bzero(s, n) memset(s, 0, n)
#define O_NOFOLLOW 0
#define geteuid() (0)
Functions
void setenv (const char *name, const char *value, int overwrite)
void unsetenv (const char *name)
const char * inet_ntop (int af, const void *src, char *dst, uint32_t cnt)
int inet_pton (int af, const char *src, void *dst)
Detailed Description
Author
Jan Jezek jjeze.nosp@m.k@ke.nosp@m.rio.c.nosp@m.om
Definition in file win32-misc.h.
Macro Definition Documentation
#define bzero (s, n) memset(s, 0, n)
Definition at line 30 of file win32-misc.h.
#define geteuid () (0)
Definition at line 42 of file win32-misc.h.
#define index strchr
Definition at line 27 of file win32-misc.h.
Referenced by SCClassConfAddClasstype(), SCHInfoAddHostOSInfo(), SCHInfoGetHostOSFlavour(), and SCHInfoLoadFromConfig().
#define O_NOFOLLOW 0
Definition at line 33 of file win32-misc.h.
Referenced by SCPidfileCreate().
#define rindex strrchr
Definition at line 28 of file win32-misc.h.
Function Documentation
const char* inet_ntop (int af, const void * src, char * dst, uint32_t cnt)
Referenced by PrintInet().
int inet_pton (int af, const char * src, void * dst)
Referenced by DetectAddressParseString(), SCRadixAddKeyIPV4String(), SCRadixAddKeyIPV6String(), ValidateIPV4Address(), and ValidateIPV6Address().
void setenv (const char * name, const char * value, int overwrite)
void unsetenv (const char * name)